### ISSUE TITLE
Docs: 12.0.0 breaking change for loadData/framework prop data loading has been omitted

### ISSUE THREAD

**Issue by henricook** [handsontable/handsontable#10004]
### Description
After spending about three hours today trying to figure out why my table was no longer behaving I narrowed it down to an issue that is only mentioned in the 12.0.0 migration guide and doesn't appear in the breaking changes in the release notes. I hadn't looked at the migration guide as none of the breaking changes sounded like they affected me, and I think this one should be more prominent.

**Action requested:** Please add a reference to the 'framework wrappers'/'loadData' changes mentioned in the migration guide to the release notes as a breaking change to save other people having to waste so much time

Migration guide: https://handsontable.com/docs/javascript-data-grid/migration-from-11.1-to-12.0/

The 'framework wrappers' section: https://handsontable.com/docs/javascript-data-grid/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls

This was a big change to my application, it led to data rows jumping around and all kinds of weird behaviour.

**Comment by adrianszymanski89** [comment]
Hi @henricook 

I checked our release notes for v. 12, and I can see it being mentioned in the first line of the **Changed** section:

https://handsontable.com/docs/javascript-data-grid/release-notes/#_12-0

I mean this line:

> Breaking change: Changed how [updateSettings()](https://handsontable.com/docs/javascript-data-grid/api/core/#updatesettings) handles data updates, to improve performance and the consistency of user experience. Now, when provided with a new data object, [updateSettings()](https://handsontable.com/docs/javascript-data-grid/api/core/#updatesettings) updates the data without resetting any states. [#7263 (opens new window)](https://github.com/handsontable/handsontable/issues/7263)[[migration guide]](https://handsontable.com/docs/javascript-data-grid/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls)

Is that the information that you needed?

**Comment by henricook** [comment]
Hi @adrianszymanski89 - I don't use updateSettings anywhere, but I was setting board data in React via a prop - something that no longer works properly and I think is worth mentioning

**Comment by henricook** [comment]
The biggest use case of mine that was affected by this is that I persist moved rows. So I don't want them to only be preserved for an individual.

**Comment by adrianszymanski89** [comment]
Hi @henricook 

Can you please tell us how would like to see the description of the information about that change in the release notes?

**Comment by henricook** [comment]
Sure thing @adrianszymanski89 

Add a `Breaking change` to the list of breaking changes on the [release page](https://handsontable.com/docs/javascript-data-grid/release-notes/#removed) for 12.0.0 that contains text along the lines of the Framework wrappers heading in the migration guide:

```
Updating your [data](https://handsontable.com/docs/javascript-data-grid/api/options/#data) through a component property no longer resets your index mapper information and configuration options.

To replace [data](https://handsontable.com/docs/javascript-data-grid/api/options/#data) and reset the states, call the [loadData()](https://handsontable.com/docs/javascript-data-grid/api/core/#loadData) method (the same way as above), referencing the Handsontable instance from the component.
```

and a link to the section in the migration guide

**Comment by adrianszymanski89** [comment]
Hi @henricook 

I just want to let you know that we added all of the information that you requested

**Comment by henricook** [comment]
Thanks @adrianszymanski89
