### ISSUE TITLE
Nested rows with hyperfomula works incorrectly

### ISSUE THREAD

**Issue by Paqura** [handsontable/handsontable#10001]
### Description
If you add a hyperformula into a table with nestedRows, autofill does not work correctly.

### Steps to reproduce
1. Add hyperformula to table
2. Hide any line that is above the intended change
![image](https://user-images.githubusercontent.com/22657076/194523221-26a2cf50-5801-4103-94fb-1ee00a556eab.png)

3. Autofill a  few cells
![image](https://user-images.githubusercontent.com/22657076/194523326-fb864c0f-96b9-4715-89d1-6dd872ed1510.png)

### Demo
https://jsfiddle.net/by4es7nw/2/

### Your environment
* React wrapper version: 17.0.2
* Handsontable version: 21.1.2
* Browser name and version: Any
* Operating system: Ubuntu 20.0.4

**Comment by adrianszymanski89** [comment]
Hi @Paqura 

Thank you for reporting this issue. I will mark it as a bug.

**Comment by adrianszymanski89** [comment]
HI @Paqura 

I re-checked this issue with v. 14.4.0, and it's no longer replicable. Here's an example: https://jsfiddle.net/handsoncode/4qtodykg/
