### ISSUE TITLE
The sum formular not working with literal string

### ISSUE THREAD

**Issue by suigetsu12** [handsontable/handsontable#10012]
### Steps to reproduce

I have a custom sum formula literal string as the below image
![image](https://user-images.githubusercontent.com/12743221/195306209-21e4823a-cd24-4085-b821-3dd98fa08ae1.png)
but in the Handsontable, the formula does not work, because it shows the formula as the below image
![image](https://user-images.githubusercontent.com/12743221/195306095-53fc88cd-bd94-41d4-b3e8-af7ad632ea2b.png)

### Your environment
* React wrapper version: 17.0.2
* Handsontable version: 12.1.3
* Browser name and version: Chrome 106.0.5249.103 (Official Build) (64-bit)
* Operating system: Windows

**Comment by AMBudnik** [comment]
Hi @suigetsu12 

I created a simple demo here https://jsfiddle.net/wnqxk2eg/ and it works well. Could you share a demo where we will be able to replicate the issue that you have?

**Comment by suigetsu12** [comment]
I have a demo as below link
[https://codesandbox.io/s/handsontable-react-data-grid-hello-world-app-forked-fw0qlx](url)

**Comment by AMBudnik** [comment]
The demo lacks the `formulas` plugin. Here's an update https://codesandbox.io/s/handsontable-react-data-grid-hello-world-app-forked-hp8cc1

* import in line `4`
* `Formulas` plugin line `20`

**Comment by suigetsu12** [comment]
I don't see any change in here
![image](https://user-images.githubusercontent.com/12743221/195328597-77aa0d63-d0e2-4c69-8c70-e12474be60ae.png)

**Comment by AMBudnik** [comment]
@suigetsu12 did you use my fork?

If it doesn't appear, please try this

1. Import `HyperFormula` dependency
2. Add import on the top of the page `import HyperFormula from "hyperformula"`
3. Add this line to the props of the component `formulas={{engine: HyperFormula}}`
