### ISSUE TITLE
[12.0+] Loading data by changing state break formulas calculation

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#10011]
### Description

If we try to change the data set by changing the state in React, the formulas won't be calculated until we open the cell editor and close it again. This issue was introduced in version 12.0, where the data loading methods were changed.

### Steps to reproduce

1. Open the demo
2. Click on "click" button

### Demo

HOT 11.1 (works correctly) - https://jsfiddle.net/aszymanski/y5xft4rh/3/
HOT 12.0 (broken) - https://jsfiddle.net/aszymanski/y5xft4rh/2/

### Your environment
* Handsontable version: 12.0
* Browser name and version: Google Chrome 106
* Operating system: macOS Monterey 12.6

**Comment by adrianszymanski89** [comment]
Hi @jamshaidbutt055 

Yes, it's fixed and the fix will be available with the next release.

**Comment by aninde** [comment]
This issue will be fixed by the upcoming v12.3

**Comment by AMBudnik** [comment]
Hi @jamshaidbutt055 

Now it is fixed :) We just released Handsontable v12.3.0 that fixes this issue. Here https://handsontable.com/docs/javascript-data-grid/release-notes/#_12-3-0 you can read more about the changes.

ps. I will also update the forum topic you created.
