### ISSUE TITLE
Getting alot of warnings when code compiled

### ISSUE THREAD

**Issue by jamshaidbutt055** [handsontable/handsontable#10032]
### Description
Code Compiled with warnings when I use `HandsOnTable`.
It failed to find module `chevrotain`.

### Steps to Produce
Using `handsOnTable` in React with Typescript Project.

### Demo
Check the file to view the warning.
[warnings.txt](https://github.com/handsontable/handsontable/files/9807303/warnings.txt)

### Your environment
* React wrapper version: V11.1
* Handsontable version: V11.1
* Browser name and version: Chrome V105.0.5195.125 (Official Build) (64-bit)
* Operating system: Ubuntu

**Comment by adrianszymanski89** [comment]
Hi @jamshaidbutt055 

Can you also tell me which version of React, NPM, and Node.js you use?

**Comment by jamshaidbutt055** [comment]
> React : "^18.2.0",
Node : v16.16.0
NPM : 8.11.0

**Comment by adrianszymanski89** [comment]
@jamshaidbutt055 

Thank you, I have basically the same environment, and I don't get these warnings. Would it be possible to you to send me a package with your project so I can check it?

**Comment by jamshaidbutt055** [comment]
@adrianszymanski89 I am afraid I cant provide you with code but I  assure you that I have tried to delete node-modules and run `npm install` many times but still I am getting warnings..

**Comment by adrianszymanski89** [comment]
Hi @jamshaidbutt055 

Can you try running this command and tell me if that helps? Apparently, that might be the reason for getting these errors.

`npm cache clean`

**Comment by jamshaidbutt055** [comment]
> Hi @jamshaidbutt055
> 
> Can you try running this command and tell me if that helps? Apparently, that might be the reason for getting these warnings.
> 
> `npm cache clean --force`
> 
> Can you please also tell me what commands you are using and in which order?

Still getting those warning after cleaning cache

**Comment by adrianszymanski89** [comment]
@jamshaidbutt055 

Ok, I see. And can you tell me what commands you are using and in which order?

**Comment by jamshaidbutt055** [comment]
> @jamshaidbutt055
> 
> Ok, I see. And can you tell me what commands you are using and in which order?

just `npm start` to run the project. not deployed yet.

**Comment by adrianszymanski89** [comment]
@jamshaidbutt055 

There's one more solution you can try. This command should remove those warnings. Just add this line to your `start` script:

`GENERATE_SOURCEMAP=false`

**Comment by AMBudnik** [comment]
I think that we can close this issue as there are no additional questions or updates to the proposed solution. 

@jamshaidbutt055 if any further help is needed, please message us at support@handsontable.com
