### ISSUE TITLE
Click events don't work after clicking inside the iframe

### ISSUE THREAD

**Issue by lexer2086** [handsontable/handsontable#1003]
Hi.
If I click inside the table first, I'm able to move the cursor position and select any cell I want. But, if I click inside the iframe and then click to the table again, I get that the iframe has a focus and I'm not able to move the cursor.

To solve that problem, I must create an input type="text" and set focus there, before I change cursor position.

Something like that:
```javascript
$table.handsontable({
            data: @Html.Raw(data),
            colWidths: @Html.Raw(colWidths),
            colHeaders: @Html.Raw(colHeaders),
            columns: @Html.Raw(columns),
            rowHeaders: true,
            afterSelectionEnd: function () {
                $hiddenInputField.focus();
                $hiddenInputField.blur();
            }
        });
```

Is that expected behaviour or is it a bug?

http://jsfiddle.net/2f3Ym/5/

**Comment by AMBudnik** [comment]
Changed in Bugfix #1003
