### ISSUE TITLE
How to use handsontable in handsontable ？

### ISSUE THREAD

**Issue by sheep5250** [handsontable/handsontable#10039]
![196571707-d14d0a93-ab09-4f38-9fee-a540079c352c](https://user-images.githubusercontent.com/42953487/196572417-58968af5-ce9f-49fe-80e4-88f0676479b5.png)

It is similar to the following code.
` var carData = [
            ['', '2017'],
            ['Chrysler', '2018'],
            ['Nissan', '2019'],
            ['Toyota', '2020']
        ],
            container = document.getElementById('example1'),
            colorData = [],
            hot,
            timer;
        manufacturerData = [
            { name: 'BMW', country: 'Germany', owner: 'Bayerische Motoren Werke AG' },
            { name: 'Chrysler', country: 'USA', owner: 'Chrysler Group LLC' },
            { name: 'Nissan', country: 'Japan', owner: 'Nissan Motor Company Ltd' },
            { name: 'Suzuki', country: 'Japan', owner: 'Suzuki Motor Corporation' },
            { name: 'Toyota', country: 'Japan', owner: 'Toyota Motor Corporation' },
            { name: 'Volvo', country: 'Sweden', owner: 'Zhejiang Geely Holding Group' }
        ];
        manufacturerData2 = JSON.parse(JSON.stringify(manufacturerData))
        hot = new Handsontable(container, {
            data: carData,
            colHeaders: ['Car', 'Year'],
            columns: [
                {
                    type: 'handsontable',
                    handsontable: {
                        colHeaders: ['Marque', 'Country', 'Parent company'],
                        autoColumnSize: true,
                        data: manufacturerData,
                        columns: [
                            { data: 'name' },
                            { data: 'owner' }
                        ],
                        getValue: function () {
                            var selection = this.getSelectedLast();
                            return this.getSourceDataAtRow(selection[0]).name;
                        },
                    }
                },
                { type: 'numeric' }
            ],
            beforeKeyDown: function (e) {
                clearTimeout(timer);
                timer = setTimeout(function () {
                    let newArr = []
                    if(hot.getSelectedLast()[2]==0){
                        for(let item of manufacturerData2){
                            if(item.name.indexOf(e.realTarget.value)!=-1){
                                newArr.push(item)
                            }
                        }
                    }
                    manufacturerData.length=0
                    for(let jtem of newArr){
                        manufacturerData.push(jtem)
                    }
                }, 500);
            }
        });`

**Comment by AMBudnik** [comment]
Hi @sheep5250 

I'm closing this issue as we already replied on the forum at https://forum.handsontable.com/t/how-to-use-handsontable-in-handsontable/6519/2
