### ISSUE TITLE
zone.js:1711 Uncaught TypeError: Cannot destructure property 'wtOverlays' of 'this.hot.view.wt' as it is undefined.

### ISSUE THREAD

**Issue by ericchenty** [handsontable/handsontable#10031]
const { wtOverlays } = this.hot.view.wt;

this in js is ok, but error at angular

how to use this.hot.view.wt in angular v14?

**Comment by adrianszymanski89** [comment]
Hi @ericchenty 

We changed the name of this property with version 12.0:

> Changed an internal property name, from handsontableInstance.view.wt to handsontableInstance.view._wt, to make it clear that Walkontable (Handsontable's rendering engine) is not a part of Handsontable's public API.

That is probably the reason why you are getting an error.
