### ISSUE TITLE
Docs: [12.2] Opened search engine is shifted when the window has a resolution of 800 x 600 or a width less than 850 px

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#10049]
### Description

When search input is opened and has class `focused`, the whole div class="nav-links-right" is misplaced. 
The bug occurs from a window width of 850 px on desktop. Not on mobiles and iPad.
Apparently, most of our users view the documentation at this resolution, it should look good.

<input aria-label="Search" autocomplete="off" spellcheck="false" value="" class="focused" placeholder="Search...">

**Current result:**
<img width="854" alt="Screenshot 2022-10-21 at 14 31 10" src="https://user-images.githubusercontent.com/30186818/197197004-42d867a8-242b-4435-b349-92027fb41ee2.png">

**Result on the current version 12.1:**
https://handsontable.com/docs/javascript-data-grid/

<img width="856" alt="Screenshot 2022-10-21 at 14 36 00" src="https://user-images.githubusercontent.com/30186818/197197272-cd70601c-1b41-4f51-a84d-cfa0b0e17a79.png">

### Links

Not related to the site
https://dev.handsontable.com/docs/javascript-data-grid/angular-installation/
https://dev.handsontable.com/docs/react-data-grid/

**Comment by budnix** [comment]
On the screen with width set as ~350px it looks similar
![image](https://user-images.githubusercontent.com/571316/197199945-3d767b60-d3d2-4627-95d7-5cb5c64d9471.png)

**Comment by krzysztofspilka** [comment]
Continued in https://github.com/handsontable/handsontable/issues/10055
