### ISSUE TITLE
cellProperties.source.find(({ _id }) => _id === value);  error TS7031: Binding element '_id' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by Hayast** [handsontable/handsontable#10045]
import Handsontable from "handsontable/base";
const keyValueListRenderer = function(hot:any, TD:any, row:any, col:any, prop:any, value:any, cellProperties:any) {
  const item = cellProperties.source.find(({ _id }) => _id === value);  
  if (item) {
    value = item.label;
  }  
  Handsontable.renderers.getRenderer('autocomplete').call(hot, hot, TD, row, col, prop, value, cellProperties);
};
export default keyValueListRenderer;

Error: app/components/KeyValueListEditor/keyValueListRenderer.ts:9:46 - error TS7031: Binding element '_id' implicitly has an 'any' type.

   const item = cellProperties.source.find(({ _id }) => _id === value);

how to fix it.

**Comment by adrianszymanski89** [comment]
Hi @Hayast 

Can you please provide more information about your environment? I mean OS, Handsontable version and framework.

**Comment by Hayast** [comment]
> Hi @Hayast
> 
> Can you please provide more information about your environment? I mean OS, Handsontable version and framework.

angular v14 handsontable v12.1

**Comment by adrianszymanski89** [comment]
Thank you. Can you try this solution?

`const item = cellProperties.source.find(({ _id }: {_id: any}) === value);`

**Comment by Hayast** [comment]
> Thank you. Can you try this solution?
> 
> `const item = cellProperties.source.find(({ _id } : {_id: any}) === value);`

same error

**Comment by Hayast** [comment]
thanks

**Comment by Hayast** [comment]
const item = cellProperties.source.find(({ _id }:{_id:any}) => _id === value);

ok.

thanks.
