### ISSUE TITLE
 column type: 'handsontable', can get data from http?  query data return  manufacturerData

### ISSUE THREAD

**Issue by Hayast** [handsontable/handsontable#10053]
columns: [
    {
      type: 'handsontable',
      handsontable: {
        colHeaders: ['Marque', 'Country', 'Parent company'],
        autoColumnSize: true,
        //data: manufacturerData,
        **### data: function(query, process) {
            var newData= http.get('url',{param});
            process(newData);
        };,**

        getValue() {
          const selection = this.getSelectedLast();

          // Get the manufacturer name of the clicked row and ignore header
          // coordinates (negative values)
          return this.getSourceDataAtRow(Math.max(selection[0], 0)).name;
        },
      }
    },

### Description

 data: function(query, process) {
            var newData= http.get('url',{param});
            process(newData);
        };

### Your environment
* Angular version: 14
* Handsontable version: 12.1
* Wrapper version:
* Browser name and version:
* Operating system:

**Comment by adrianszymanski89** [comment]
Hi @Hayast 

Can you please specify what is your expected output here? All available data binding options can be found here:

https://handsontable.com/docs/javascript-data-grid/binding-to-data/

**Comment by AMBudnik** [comment]
Hi @Hayast do we have any updates regarding this topic?

**Comment by AMBudnik** [comment]
I think that we can close this issue as there are no updates.

@Hayast please send us details regarding this issue at support@handsontable.com
