### ISSUE TITLE
Docs: [12.2] Svg images has wrong path

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#10050]
### Description

Svg image has wrong path, picture is not displayed.

<img width="467" alt="Screenshot 2022-10-21 at 14 27 01" src="https://user-images.githubusercontent.com/30186818/197195675-dcd33f2f-1767-46e4-9505-dfd85f3f88b9.png">

### Links

https://dev.handsontable.com/docs/javascript-data-grid/

**Comment by krzysztofspilka** [comment]
Continued in https://github.com/handsontable/handsontable/issues/10055
