### ISSUE TITLE
Docs: [12.2] Dark theme causes the horizontal cell boundaries in the Vuex demos to disappear

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#10051]
### Description

Dark theme pollutes the preview of the demos related to Vuex.  Therefore, it does not show horizontal boundaries between cells

<img width="327" alt="Screenshot 2022-10-21 at 15 00 58" src="https://user-images.githubusercontent.com/30186818/197202916-f8940771-f367-4cc9-b5dc-4ff4591c2af2.png">

https://user-images.githubusercontent.com/30186818/197202955-660132fc-688a-4d52-adca-d5dd0f06814d.mov

### Links

https://dev.handsontable.com/docs/javascript-data-grid/vue-vuex-example/ - broken
https://dev.handsontable.com/docs/javascript-data-grid/vue3-vuex-example/ - broken
https://handsontable.com/docs/javascript-data-grid/vue3-vuex-example/ - 12.1 ok

**Comment by krzysztofspilka** [comment]
Continued in https://github.com/handsontable/handsontable/issues/10055
