### ISSUE TITLE
Docs: [12.2] Release notes page links for the documentation don't work

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#10052]
### Description

Newly added links to the documentation of each version don't work.
All 24 links for documentation returns 404
Example for v12.0 https://dev.handsontable.com/docs/.build-tmp/react-data-grid/guides/upgrade-and-migration/docs/12.0/
Additionally [Blog post](https://dev.handsontable.com/docs/react-data-grid/release-notes/PLACEHOLDER) is 404 too.
The template also seems strange to me because the documentation is listed next to the date in parentheses, what for?

12.2.0
Released on October 25, 2022 ([Documentation](https://dev.handsontable.com/docs/.build-tmp/react-data-grid/guides/upgrade-and-migration/docs/12.2/))
For more information on this release, see:
[Blog post](https://dev.handsontable.com/docs/react-data-grid/release-notes/PLACEHOLDER)

**Reproduction**:
1. Open https://dev.handsontable.com/docs/next/javascript-data-grid/release-notes/ or https://dev.handsontable.com/docs/react-data-grid/release-notes/
2. Click on the link (Documentation) added to each version
![Screenshot 2022-10-24 at 10 50 35](https://user-images.githubusercontent.com/30186818/197487048-5996bc36-e986-436e-b5e2-16fee91653d2.png)

**Actual result**:
Links return 404

**Expected result:**
Links should work when is open by lick, open in the new tab.

### Links

https://dev.handsontable.com/docs/.build-tmp/react-data-grid/guides/upgrade-and-migration/docs/12.0/

**Comment by kirszenbaum** [comment]
@aninde

The **Blog post** links are placeholders. They were updated [here](https://github.com/handsontable/handsontable/pull/10046/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR15)) and will start working once the release blog post is published.

The **Documentation** links were added by Krzysiek and should link to a given version's documentation. They were added as `docs/12.2/`, which works locally but doesn't work on Staging, probably because of [this](https://github.com/handsontable/handsontable/blob/release/12.2.0/docs/docker/redirects.conf#L25-L33) redirect?

**Comment by kirszenbaum** [comment]
@aninde – I hope [this commit](https://github.com/handsontable/handsontable/pull/10046/commits/13492e6c0a87a7998c33b5f38d26377b152a4a9b) fixes the issue with of the cross-version **Documentation** links. It'll need double-checking, though

**Comment by aninde** [comment]
On the current staging those links redirect to the staging version so only those ones to the 12.1 work, but the older ones. 
Example: https://dev.handsontable.com/docs/12.0/ that return 404. I am not able to say whether they will be correct in production. Shouldn't that lead straight to the production version?

**Comment by kirszenbaum** [comment]
@aninde As discussed on today's meeting, I'm adding absolute links instead: https://github.com/handsontable/handsontable/pull/10046/commits/ac6674bc245ec4966ebbea92219c6c1e13da9853.

**Comment by kirszenbaum** [comment]
@aninde – closing, as done: https://handsontable.com/docs/javascript-data-grid/release-notes/
