### ISSUE TITLE
Custom function not recognised

### ISSUE THREAD

**Issue by nicoladaniello** [handsontable/handsontable#10071]
### Description

I'm trying to implement a custom function following the documentation on HyperFormula but with no success.
The function is not being recognised and the cell prompts a `#name?` error.

### Demo

https://codesandbox.io/s/epic-cannon-1fz4m6?file=/src/components/HelloWorld.vue

### Your environment
* Handsontable version: 12.2.0
* Hyperformula version: 2.1.0
* Browser name and version: Chrome 106.0.5249.119
* Operating system: Windows

**Comment by AMBudnik** [comment]
Hi @nicoladaniello 

Thank you for the issue report. I replicated the issue and asked my colleague for feedback.
I should be able to update this thread early next week.

**Comment by AMBudnik** [comment]
Hi @nicoladaniello 

I just got feedback from our developer

https://codesandbox.io/s/nice-worker-yjcsjw the `HyperFormula.registerFunctionPlugin` has to be called before the instance is created. It is mentioned here in the docs: https://hyperformula.handsontable.com/api/classes/hyperformula.html#registerfunctionplugin

> Note: This method does not affect the existing HyperFormula instances.

**Comment by AMBudnik** [comment]
Hi @nicoladaniello were you able to implement the same solution in your project?

**Comment by AMBudnik** [comment]
Hi @nicoladaniello 

I'm closing this issue as solved.

If you'd need anything, please feel free to open a new issue or contact us at support@handsontable.com
