### ISSUE TITLE
Prevent deselection when clicking outside the table

### ISSUE THREAD

**Issue by nicoladaniello** [handsontable/handsontable#10076]
### Description

This is a feature request. I'm building a toolbar to do operations within the currently selected cell, but unfortunately clicking outside the table will deselect the cells.

I think this is a common use case and would be good to have some way to prevent this behavior.

**Comment by AMBudnik** [comment]
Hi @nicoladaniello 

Have you tried the [disableVisualSelection: false](https://handsontable.com/docs/javascript-data-grid/api/options/#disablevisualselection). It seems that it should meet your requirements.
