### ISSUE TITLE
Date/time formulas are not converted to strings

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#10078]
### Description

As [internally discussed](https://handsoncode.slack.com/archives/C031GBX62SE/p1664871825198519), we defined the following list of formulas:

```
DATE
DATEVALUE
EDATE
EOMONTH
NOW
TODAY
```

These formulas return a string representation of a date in the Handsontable cell. Instead, they show a number.

Demo for tests: https://jsfiddle.net/4fov9635/ where one of the formulas (first cell) shows

![Screenshot 2022-10-28 at 15 10 11](https://user-images.githubusercontent.com/10757813/198600447-e0f2b70a-7b48-489a-9410-4321d22a91bc.png)

while it should be showing a string with a date/date format.

### Your environment
* Handsontable version: 12.2.0
_Does not seem to be a regression_
* Browser name and version: Chrome 106
* Operating system: macOS Monterey

cc @sequba 
inform [forum](https://forum.handsontable.com/t/gh-10078-formula-is-not-working-in-handsontable/6556)

**Comment by aninde** [comment]
I verified during the acceptance testing phase of https://github.com/handsontable/handsontable/pull/10317 that the solution effectively addresses this particular issue. Test demo where only version is changed to 931651ec28b67fe25cec00b683ff1b1a52dbc326 https://jsfiddle.net/aninde/715b9fuy/.
The PR contains[ tests covering](handsontable/src/plugins/formulas/__tests__/utils.unit.js) this case, so I think we can close it after release and put it in the RN.

**Before:**
<img width="663" alt="Screenshot 2023-04-24 at 15 28 25" src="https://user-images.githubusercontent.com/30186818/234011224-f1e5c2f3-69c0-4cd8-9e13-d117dbe92151.png">

**After:**
<img width="545" alt="Screenshot 2023-04-24 at 15 28 13" src="https://user-images.githubusercontent.com/30186818/234011199-45173477-752a-4ae4-84f5-63a2dc564e98.png">

**Comment by AMBudnik** [comment]
This issue is no longer replicable using v14.0.0 https://jsfiddle.net/hexq3j60/1/

I will closed it as solved.
