### ISSUE TITLE
option 「className」BUG

### ISSUE THREAD

**Issue by YoRHa21O** [handsontable/handsontable#10075]
### Description
BUG
const hot = new Handsontable(container, {
  data,
  **className: ['abc'],
  columns: [{type: 'numeric'}],**
  licenseKey: 'non-commercial-and-evaluation'
});

OK
const hot = new Handsontable(container, {
  data,
  **className: 'abc',
  columns: [{type: 'numeric'}],**
  licenseKey: 'non-commercial-and-evaluation'
});

className: **_['abc']_**
columns: [{type: **_'numeric'_**}]
cannot be used at the same time

### Your environment
* Handsontable 12.2/12.1

**Comment by AMBudnik** [comment]
Hi @YoRHa21O 

Thank you for sharing. This issue is already reported at https://github.com/handsontable/handsontable/issues/8059 so I need to close this issue as a duplicate. Nevertheless, I'll send you a notification once we solve https://github.com/handsontable/handsontable/issues/8059
