### ISSUE TITLE
Slow scroll when using mouse wheel

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#10080]
### Description
When I scroll a large grid vertically using mouse scroll the table shows every single row from where I am until the mouse wheel stops. This makes scrolling with the mouse wheel much slower than with scroll bars. I would expect it to utilize virtualization when scrolling with the mouse wheel, same as when I click+drag the scroll bars.

Maybe this is intended behavior. In any way, I would like to be able to configure the grid to speed up scrolling large grids.

### Steps to reproduce
1. create grid with many rows
2. scroll using mouse wheel scroll (spin the scroll wheel not mouse3 click scroll)

### Demo
https://jsfiddle.net/yrm9w5gs/

### Your environment
* Handsontable version: 12.2.0
* Browser name and version: Firefox 105
* Operating system: MacOs 12.6

**Comment by AMBudnik** [comment]
Thank you for sharing this issue report @ottosson 

You're right Firefox scrolling is way slower than what we have in Chrome or Safari. But we also do not seem to get the flashing effect in Firefox when we scroll the table really fast. I will leave this topic for further investigation. 

@aninde please take a look at this when you're back

**Comment by ottosson** [comment]
I would expect the flashing effect caused by row virtualization, same as when I drag the scrollbar fast with the mouse.
I much rather have the fast scroll with flashing than slow scroll without :)

**Comment by AMBudnik** [comment]
Hi @ottosson 

We tested the issue, and it doesn't seem to cause any delays. Scrolling with bars and mouse wheel seems to give exact results. Tested on macOS devices with Chrome 125.

Could you please check that once again?

**Comment by ottosson** [comment]
Maybe it's Firefox behavior and not Handsontable related.

https://github.com/handsontable/handsontable/assets/3355320/aecf7c15-ba76-495a-aa6f-fe8d2ca77777

**Comment by AMBudnik** [comment]
Hi @ottosson 

Sorry for the delay. I lost notification for this issue in the mailbox.

Could you tell me what your current OS/Browser version is? We tested it internally on the latest FF on macOS Sonoma and macOS Ventura and did not get the same issue.

**Comment by ottosson** [comment]
I'm using MacOS Somona 14.5 with the latest versions of Firefox and Chrome.

This is not a huge issue. I just found it curious that it worked differently in different browsers.
