### ISSUE TITLE
Using `day` value less than `13` breaks formula visibility

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#10085]
### Description

Using `day` value less than `13` breaks formula visibility. I assume that `13` and more makes the algorithm "think" that this is not a date (12 months only).

### Steps to reproduce

1)  Go to https://jsfiddle.net/9kyet1na/
2) As you can see both dates are shown correctly
![Screenshot 2022-11-02 at 08 14 11](https://user-images.githubusercontent.com/10757813/199423863-92d4c7af-51cc-4c8d-b7d6-cb15d011942c.png)
3) Now change `13` to `12` via date picker in the first cell
![Screenshot 2022-11-02 at 08 14 19](https://user-images.githubusercontent.com/10757813/199424005-a494aced-214e-465e-8344-f282db64d9bf.png)

### Demo

https://jsfiddle.net/9kyet1na/

### Additional info
* might be connected to https://github.com/handsontable/handsontable/issues/10078 
* works the same for `DD/MM/YY` https://jsfiddle.net/p3zqu0av/ but surely has to be tested with all supported date formats
* world the same on Chrome, Safari and Firefox

### Your environment
* Handsontable version: 12.2.0
* Browser name and version: Chrome 106
* Operating system: macOS Monterey

[Inform](https://handsoncode.slack.com/archives/C03VB4EJMND/p1667217630191009)

**Comment by aninde** [comment]
https://github.com/handsontable/dev-handsontable/issues/442#issuecomment-1549600760

**Comment by AMBudnik** [comment]
The following issue is solved in Handsontable v12.4.0. Updated demo https://jsfiddle.net/handsoncode/4sqjncx0/
