### ISSUE TITLE
Row Headers height not adaptive

### ISSUE THREAD

**Issue by lzs246** [handsontable/handsontable#10084]
### Description
demo：https://codesandbox.io/s/amazing-fog-kn2wvn?file=/src/App.js
When customizing the renderer, the height of row headers is not stretched. Is there any way? Thank you

![image](https://user-images.githubusercontent.com/62453543/199149383-490479f5-5ddb-48e8-8752-a404560725aa.png)

**Comment by adrianszymanski89** [comment]
Hi @lzs246 

Such misalignment can be caused if your `HotColumn` element doesn't have a specified width and/or height. You can read more about it here:

https://handsontable.com/docs/react-data-grid/cell-renderer/#declare-a-custom-renderer-as-a-component

**Comment by lzs246** [comment]
Thanks for your reply
