### ISSUE TITLE
Hidden row inside collapsed nested rows becomes visible after settings update

### ISSUE THREAD

**Issue by slavabogov** [handsontable/handsontable#10095]
### Description

When updating HiddenRows plugin settings with the same configuration, it hides different rows depending on expanded/collapsed state of NestedRows plugin.
Looks like HiddenRows plugin works only with visual rows, ignoring what is inside of collapsed nested rows.

### Steps to reproduce

1. Open the demo. Ensure that Row 3 is hidden
2. Collapse Row 1 by clicking on `-` sign
3. Update settings by clicking "Set hidden rows"
4. Row 6 becomes hidden. However, it should remain visible
5. Expand Row 1 by clicking on `+` sign
6. Row 6 becomes visible. However, it should remain hidden

### Demo

https://stackblitz.com/edit/angular-ivy-rxx9lp

### Your environment
* Angular version: 14.2.1
* Handsontable version: 12.2.0
* Wrapper version: 12.2.0
* Browser name and version: Google Chrome 107.0.5304.87 (Official Build) (x86_64)
* Operating system: macOS Ventura 13.0 (22A380)

**Comment by adrianszymanski89** [comment]
Hi @slavabogov 

You are correct. HiddenRows plugin operates only on visual indexes, and that's the reason for this behavior. However, if that's suitable for you while updating the settings, you can force the nestedRows plugin to fire again, and then hiddenRows works as expected:

https://stackblitz.com/edit/angular-ivy-hyiskd?file=src%2Fapp%2Fapp.component.ts

**Comment by slavabogov** [comment]
Hi @adrianszymanski89

I checked your example, and I noticed that after settings update the collapsed row becomes opened. Is there any possibility to keep it collapsed? Our users closing them to reduce amount of rows to see, and they want them to be closed when they hiding other rows.

**Comment by adrianszymanski89** [comment]
Hi @slavabogov 

We don't have an official API for that, but you can refer to nestedRows plugin and use this method:

`getPlugin('nestedRows').collapsingUI.expandChildren(number)`

I suggest to add a bit of timeout for this method to avoid any unexpected behavior.

**Comment by slavabogov** [comment]
Hi @adrianszymanski89 

Thanks, private API helped. I used it without timeout to collapse rows that were collapsed before settings update.
I'm going to close this ticket. We're looking forward to have this API public, or to have some other way to work with hidden rows inside nested rows.
