### ISSUE TITLE
setDataAtCell after alter causes internal error

### ISSUE THREAD

**Issue by akash-pal** [handsontable/handsontable#10109]
### Description
setDataAtCell after alter causes internal error.
`
   alter("insert_row", row, 1);
   setDataAtCell(row, 2, "test");
`
Same snippet was working in version 7.4.0

### Steps to reproduce
1. Click on "add row" in jsfiddle
2. Check the error log

### Demo
https://jsfiddle.net/akashpal/3d7fuwns/

### Your environment
* React wrapper version: 8.4.0
* Handsontable version: 8.4.0
* Browser name and version: Chrome
* Operating system: MacOs

###Error
`
handsontable.full.min.js:34 Uncaught TypeError: Cannot read properties of undefined (reading 'countCols')
    at setDataAtCell (handsontable.full.min.js:34:320418)
    at App.addRow (?editor_console=true:120:707)
    at HTMLUnknownElement.callCallback (react-dom.development.js:182:16)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:231:18)
    at invokeGuardedCallback (react-dom.development.js:286:33)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:300:27)
    at executeDispatch (react-dom.development.js:383:5)
    at executeDispatchesInOrder (react-dom.development.js:408:7)
    at executeDispatchesAndRelease (react-dom.development.js:3401:7)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:3410:12)
`

**Comment by adrianszymanski89** [comment]
Hi @akash-pal 

Here's a working example using Handsontable 8.4.0. We introduced many changes in version 8.0, which might cause issues while upgrading. Currently, this is a recommended way to do this.

https://jsfiddle.net/aszymanski/qg7t512s/

**Comment by akash-pal** [comment]
@adrianszymanski89 ,
The only difference seems to be de-structuring of his.hotTableComponent.current.hotInstance.
Is this understanding correct ?

Before:

```
     addRow() {
       const {
        countRows,
        alter,
        setDataAtCell,
        setCellMeta
       } = this.hotTableComponent.current.hotInstance;
       const row = countRows();
       alter("insert_row", row, 1);
       setDataAtCell(row, 2, "test");
       setCellMeta(1, 2, "readOnly", true);
    }
```

After:

```
  const addRow = () => {
    const row = hotTableComponentRef.current.hotInstance.countRows();
    hotTableComponentRef.current.hotInstance.alter("insert_row", row, 1);
    hotTableComponentRef.current.hotInstance.setDataAtCell(row, 2, "test");
    hotTableComponentRef.current.hotInstance.setCellMeta(row, 2, "readOnly", true);
  };
```

**Comment by adrianszymanski89** [comment]
Yes, that most likely was the issue here.
