### ISSUE TITLE
Hyperformula does not work with array of RowObject

### ISSUE THREAD

**Issue by olosegres** [handsontable/handsontable#10102]
### Description
Formulas does not work (treated as text?) when handsontable instantiates with `data` field that contains RowObject, `columns` and `formulas` settings enabled.

AR: formulas does not calculates, displays as text in cells
ER: formulas calculates, number is displayed inside cell

### Demo
https://codesandbox.io/s/muddy-currying-d0ilo7

Why use RowObjects? We wanted to enable undoRedo for cells with meta via passing it as data.

**Comment by olosegres** [comment]
@AMBudnik Please look at the demo, may be I do something wrong?

**Comment by AMBudnik** [comment]
Thank you for sharing. I was able to replicate the issue.

Please give me some time to test it.

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting, @olosegres 

I've checked the subject and consulted the team. At the moment, formulas are not supporting nested object data.
