### ISSUE TITLE
I want to use vue3 to customize the cell editor. Is there a demo available? The document does not implement the BaseEditorComponent component. thanks

### ISSUE THREAD

**Issue by Angelxiaotao** [handsontable/handsontable#10107]
### Steps to reproduce

I want to use vue3 to customize the cell editor. Is there a demo available? The document does not implement the BaseEditorComponent component. thanks

### Demo

https://jsfiddle.net/handsoncode/nL8sry9u/

### Your environment
* Vue 3 wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by adrianszymanski89** [comment]
Hi @Angelxiaotao 

Here you can find the example of how to implement Custom Editor in Vue3:

https://handsontable.com/docs/javascript-data-grid/vue3-custom-editor-example/

**Comment by Angelxiaotao** [comment]
I want to use the components of vue3 to complete the business. This writing method leads to too much code.













At 2022-11-17 16:46:19, "adrianszymanski89" ***@***.***> wrote:

Hi @Angelxiaotao

Here you can find the example of how to implement Custom Editor in Vue3:

https://handsontable.com/docs/javascript-data-grid/vue3-custom-editor-example/
