### ISSUE TITLE
Cannot read property 'removeEventListener' of undefined - HandsonTable in Angular

### ISSUE THREAD

**Issue by Prasant38** [handsontable/handsontable#10124]
### Description
Unhandled Promise rejection: Cannot read properties of undefined (reading 'removeEventListener')

### Steps to reproduce

1. Go to Code SandBox

### Demo
Issue is similar to #6246  Without removing the commenting the custom editor is there anyway to fix the same?
https://codesandbox.io/s/tags-renderer-and-editor-forked-npjepp?file=/src/app/hello.component.ts
![image](https://user-images.githubusercontent.com/9193645/203799925-5edc8347-7bff-4945-8075-b26426be23fb.png)

### Your environment
* Handsontable version: 9.0.0.
* Browser name and version: Chrome : 107.0.5304.107
* Operating system: Windows

**Comment by adrianszymanski89** [comment]
Hi @Prasant38 

If I uncomment your custom editor and source for the tags, I don't get any errors, and everything seems to work as intended:

https://codesandbox.io/s/tags-renderer-and-editor-forked-bjbju8

I'm noticing the error only when you enable your custom editor but leave the source for tags commented out, which is required in your editor.

**Comment by Prasant38** [comment]
> Hi @Prasant38
> 
> If I uncomment your custom editor and source for the tags, I don't get any errors, and everything seems to work as intended:
> 
> https://codesandbox.io/s/tags-renderer-and-editor-forked-bjbju8
> 
> I'm noticing the error only when you enable your custom editor but leave the source for tags commented out, which is required in your editor.

Hi adrianszymanski89,

Thanks for the reply. Can you please try to copy and paste the cell value of  tags column into cell. You will encounter the issue. Please check.
![image](https://user-images.githubusercontent.com/9193645/203981179-3a80b171-edfb-467b-a4c0-c8cd2b092378.png)

**Comment by adrianszymanski89** [comment]
@Prasant38 

Now I can get the error. After further investigation, I noticed that the error doesn't occur if you open any cell editors first. So while doing copy/paste operations, the app tries removing an event listener that doesn't exist before opening (creating) the editor.
