### ISSUE TITLE
Select cell type

### ISSUE THREAD

**Issue by robertovaldesperez** [handsontable/handsontable#10143]
### Description
If you click on select cell type and scroll up and down the select that is inside the cell moves

### Steps to reproduce
1. Select cell
2. Scroll

### Demo

https://user-images.githubusercontent.com/15571467/205699304-2c6c94af-6b37-4186-91fd-20d4bdd3d060.mp4

### Your environment
* Vue wrapper version: 12.2.0
* Handsontable version: 12.2.0
* Browser name and version: Chrome 108.0.5359.71
* Operating system: Microsoft Windows 10 Pro

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report, @robertovaldesperez 
I replicated the issue using Handsontable v12.2.0 on my Chrome 108/macOS Ventura
I think that we have the same issue reported at https://github.com/handsontable/handsontable/issues/9171. Am I right?

**Comment by robertovaldesperez** [comment]
@AMBudnik you are right. It's the same issue.

**Comment by AMBudnik** [comment]
Thank you for the confirmation. I am closing this issue and will notify you as soon as we fix https://github.com/handsontable/handsontable/issues/9171.
