### ISSUE TITLE
Columnsorting Property giving error

### ISSUE THREAD

**Issue by srikaaaaa1234** [handsontable/handsontable#10164]
We are using handsontable Version 0.16.1

Angular - 1.4.2

When using columnsorting, we are getting below error

{exception: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Flag'…, cause: undefined}
cause
: 
undefined
exception
: 
TypeError: Converting circular structure to JSON --> starting at object with constructor 'Flag' | property 'entityAspect' -> object with constructor 'EntityAspect' --- property 'entity' closes the circle at JSON.stringify (<anonymous>) at Object.observe (http://localhost:57104/scripts/handsontable.full.js:18971:38) at Core.createObserver (http://localhost:57104/scripts/handsontable.full.js:15730:33) at Core.init (http://localhost:57104/scripts/handsontable.full.js:15714:20) at http://localhost:57104/scripts/handsontable.full.js:9446:29 at arrayEach (http://localhost:57104/scripts/handsontable.full.js:9152:9) at Hooks.run (http://localhost:57104/scripts/handsontable.full.js:9442:9) at Core.loadData (http://localhost:57104/scripts/handsontable.full.js:4532:24) at Core.updateSettings (http://localhost:57104/scripts/handsontable.full.js:4584:16) at $.fn.handsontable (http://localhost:57104/scripts/handsontable.full.js:83:20)
[[Prototype]]
: 
Object

**Comment by AMBudnik** [comment]
Hi @srikaaaaa1234 

We are currently at v12.2.2, and the logic for columnSorting changed in many places. Pelase tell me what are the steps that I need to take to replicate this issue? Does it happen when you just sort the column or does it require any other options to be enabled?

**Comment by srikaaaaa1234** [comment]
homeTable.handsontable({
                    data: vm.currentFlags,
                  
                    colHeaders: ['RR', 'CC Id','PP', 'SP', 'CFF','AFF', 'CL', 'RFlag', 'KKFlag','RRR', 'CCC'],
                    columns: [
                        {
                            data: 'reason_cd'
                        },
                       // { /*type: 'checkbox',*/ data: 'to_delete', renderer: DeleteButtonRenderer },
                        {
                            data: 'coop_id'
                        
                        },                        {
                            data: 'rpt_yr' },
                       {
                           data: 'sup_cd', type: 'dropdown',   source: vm.suppliers,  renderer: DefaultRenderer },
                       
                     /*   {
                            data: 'sup_cd'
                        },*/

                        {
                            type: 'dropdown', source: vm.YesNoValues, data: 'cfc_mem_flag', renderer: DefaultRenderer
                        },
                        {
                            type: 'dropdown', source: vm.auth_flag_values, data: 'auth_flag', renderer: DefaultRenderer
                        },
                        {
                            data: 'iid_cls_flag', source: vm.iid_cls_flag_values, type: 'dropdown', renderer: DefaultRenderer
                        },
                        {
                            data: 'state_regu_flag', source: vm.YesNoValues, type: 'dropdown', renderer: DefaultRenderer
                        },
                        {
                            data: 'krta_flag', source: vm.YesNoValues, type: 'dropdown', renderer: DefaultRenderer
                        },
                        {
                            type: 'dropdown', source: vm.reasons, data: 'description', renderer: DefaultRenderer
                        },
                        {
                            data: 'comments' }
                       ],
                    colWidths: [1,46, 40, 60, 56, 56, 56, 56, 56, 190, 190, 160 ],
                    readOnly: true,
                    stretchH: 'last',
                    fillHandle: false,
                    undo: false,
                    manualColumnResize: true,
                   // renderer: DefaultRenderer,
                    afterChange: afterChangeFunction,
                    columnSorting: true

**Comment by AMBudnik** [comment]
There are some variables missing, could you also share the code for `afterChangeFunction`?

**Comment by srikaaaaa1234** [comment]
function afterChangeFunction(changes, source) {
            if (changes) {
                for (var i = changes.length - 1; i >= 0; i--) {
                    var rowNum = changes[i][0];
                    var colName = changes[i][1];
                 
                                
                   
                  
                    if (colName === 'description') {
                        debugger;
                        homeTableInstance.setDataAtCell(rowNum, 0, datacontext.getFlagReasonCode(changes[i][3]));
                    }
                   
                }
            }
        }

**Comment by AMBudnik** [comment]
It seems that this issue should be gone when you update to a newer version of Handsontable. 
I would definitely be hard to update to 6.2.2 (last community version) as it had some breaking changes. But I highly recommend checking v2.0.0. You can download the resources from here https://github.com/handsontable/handsontable/releases?page=5

**Comment by srikaaaaa1234** [comment]
Its still the same and also new error of max call stack size 


Maximum call stack size exceeded at Flag.hasOwnProperty (<anonymous>) at objectEach (http://localhost:57104/scripts/handsontable/handsontable.full.js

**Comment by srikaaaaa1234** [comment]
Its giving error at below line in handsontable.full.js
      mirror.value = JSON.parse(JSON.stringify(obj));
[Log.txt](https://github.com/handsontable/handsontable/files/10225920/Log.txt)

**Comment by AMBudnik** [comment]
>Its still the same and also new error of max call stack size

It is hard to specify when this issue was exactly fixed. I can say that now it is not replicable. Generally in v8.0.0 we remove ObserveChange plugin and introduced Index Mapper so I can recoomend checking this option. Here are the release notes https://handsontable.com/docs/javascript-data-grid/release-notes/#_8-0. But this version has a different license - since v7.0.0 it is no longer MIT. Here https://handsontable.com/blog/articles/2019/3/handsontable-drops-open-source-for-a-non-commercial-license is an articles that descibes that change. 

If you'd have any licensing questions please contact us at sales@handsontable.com
