### ISSUE TITLE
Multi-select non-neighboring cells

### ISSUE THREAD

**Issue by airyt** [handsontable/handsontable#1016]
Howdy - love the HOT. thanks again marcin et al. for all the hard work.

Our current big hurdle is that we absolutely need multi-select for non-neighboring cells. I am wondering if this is on the TODO list and if there is a timeline for it. Failing that, i am prepared to dive into the code and see if i can hack it out. Wondering if you can provide any direction for this.

i assume that the current multi-select is determined by a starting cell x,y and an ending cell x,y. whereas true multi-select would have to keep a full array of all selected cells, even if they are neighboring. so i guess i'm hoping that someone can provide me with a head-start in converting HOT to adopt this array of selected cells.

cheers, airyt

**Comment by AMBudnik** [comment]
For further info please track changes in https://github.com/handsontable/handsontable/issues/2119
