### ISSUE TITLE
Feature: min-height, min-width, max-height, max-width

### ISSUE THREAD

**Issue by mariotacke** [handsontable/handsontable#1017]
I think this might be a good addition to the settings/options of the table. I have been unable to get handsontable to honor the css max-height and min-height settings... my table renders over elements after the handsontable.

If there is a way to do this, please let me know and we can close this out right away.

What I would like to do is define a div with a max-height option which handsontable considers and parks itself in there.

**Comment by donpinkus** [comment]
create a div with a max-height, then set overflow to auto... thats how I'm doing it :)

**Comment by donpinkus** [comment]
This is for *table* height and width.  It is not for *cell* height and width.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by stla** [comment]
> create a div with a max-height, then set overflow to auto... thats how I'm doing it :)

That does not work for me.

I do as follows for the height. First I define this function:

```
function getHeight(hot){
  var pl = hot.getPlugin("autoRowSize");
  pl.recalculateAllRowsHeight();
  var heights = pl.heights;
  var height = heights.reduce(function(total,x){return total+x;});
  return height + pl.getColumnHeaderHeight();
}
```

Then after I create the handsontable `hot`:
```
    var height = getHeight(hot);
    if(height > 450){
      hot.updateSettings({height: 450});
    }else{
      hot.updateSettings({height: height+10});
    }
```
And, in case of changes:
```
    hot.addHook("afterChangesObserved", function(){
      console.log("Setting height");
      var height = getHeight(this);
      if(height > 450){
        this.updateSettings({height: 450});
      }else{
        this.updateSettings({height: height+10});
      }
    });
```

You can do something similar for the width.

Comments are welcome.

**Comment by AMBudnik** [comment]
Please check the progress for the following issue at https://github.com/handsontable/handsontable/issues/487

**Comment by AMBudnik** [comment]
Hey,

we've added an option in Handsontable 7.0.0 that can interest you https://github.com/handsontable/handsontable/issues/5749 
From now on we support a container with relative dimensions (%, vh, vw, rem, em)
