### ISSUE TITLE
Width of last column is greater than others when set stretchH to 'all'

### ISSUE THREAD

**Issue by xinfli** [handsontable/handsontable#1018]
Refer to http://jsfiddle.net/xRF9w/

The width of last column is greater than other columns.

**Comment by AMBudnik** [comment]
Last column should not be wider - like in [this demo](http://jsfiddle.net/ey9zu0tx/) but the first column is wider than others.

**Comment by AMBudnik** [comment]
This issue should not occur any more, [demo](https://jsfiddle.net/AMBudnik/1b00cvsw/) for newest version with `stretchH: 'all'`. All columns are the same width.
