### ISSUE TITLE
Scrollbar artifact cuts off end of last column header after filtering

### ISSUE THREAD

**Issue by SamFinni** [handsontable/handsontable#10187]
### Description
When filtering using the dropdown menu on the last column header in certain circumstances, a portion of the column header gets cut off, equal to the width of the user's browser's scroll bar, potentially causing the dropdown menu button to be obscured (depending on user's scrollbar width). Scrolling the table far enough horizontally or re-filtering the column fixes it, so it does seem to be some kind of rendering issue.

### Steps to reproduce

1. Open a table with a vertical scrollbar (enough rows to overflow)
2. Filter using the last column header's dropdown menu, making sure the newly-filtered data fits in the table without a vertical scrollbar. For demo below, filter column 'O' by value to only show 'O1'
3. See that a portion of the right side of the last column header is now invisible

### Demo

https://jsfiddle.net/r06he27u/

### Your environment
* Handsontable version: 12.3.0
* Browser name and version: Brave 1.46.144 (Chromium 108.0.5359.128) / Waterfox G5.1.1 (Firefox 102.0)
* Operating system: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @SamFinni 

I replicated the issue. I will notify you as soon as we fix it.

**Comment by AMBudnik** [comment]
Hi @SamFinni 

Thank you again for sharing.

The following issue is fixed in v15.0.0 https://jsfiddle.net/o2dwk3c6/

![Zrzut ekranu 2024-12-16 o 14 01 38](https://github.com/user-attachments/assets/8310c613-1181-45fe-965d-0950de88a901)
