### ISSUE TITLE
First column of tables and dropdown is squished

### ISSUE THREAD

**Issue by dloendorfsv** [handsontable/handsontable#10197]
### Description
All HOT tables have the first column set at about 50px which is not what the column width settings says. I just tried a dropdown control for a cell and find the dropdown content is also squished.  For a table I can resolve the issue by turning on Row Headers. For the dropdown I cannot do that.

![image](https://user-images.githubusercontent.com/77278976/210105834-397c4d33-b6b0-42e3-be8f-0a037e965deb.png)

### Your environment
* Handsontable version: 12.3.0
* Browser name and version: All Browsers
* Operating system: Azure WebApp

**Comment by dloendorfsv** [comment]
Here is the table definition for the above example;

` var vln = ['Mike' , 'Roman', 'Juan']
       var rtsettings = {
            rowHeaders: true,
            multiColumnSorting: {
                indicator: true
            },
            startRows: 0,
            licenseKey: 'non-commercial-and-evaluation',
            hiddenColumns: {
                columns: [0],
                indicators: false
            },
            outsideClickDeselects: true,
            manualColumnResize: true,
            colHeaders: ["", "Route", "Group", "Unit", "Primary", "Papers"],
            colWidths: [1, 60, 60, 60, 200, 60],
            columns: [
                { readOnly: true },
                { readOnly: true },
                { readOnly: true },
                { readOnly: true },
                {
                    type: 'dropdown',
                    trimDropdown: true,
                    source: vln
                },
                { editor: 'text', type: 'text' },
            ],
            sortIndicator: true,
            afterChange: function (change, source) {
                if (source === 'loadData') {
                    return; //don't save this change
                }
                var row = change[0];
                var k = routestable.getDataAtCell(row[0], 0);
                $.post('UpdateRoute', { "key": k, "column": row[1], "value": row[3] })
            }

        }; //settings
`

**Comment by dloendorfsv** [comment]
Appears at some point the CSS for the first column was given the class rowheader even though it was nit the header. I had overridden the CSS for rowheader as I wanted a smaller width for the Row Header when that option was selected. Removing the CSS solved the problem. Not sure in which version this showed up. Anyway, now resolved. :)

**Comment by AMBudnik** [comment]
Hi @dloendorfsv 

This issue sounds odd. When I loaded you settings to JSFiddle I am not able to replicate the same issue https://jsfiddle.net/7rx3yk0b/

![Zrzut ekranu 2023-01-3 o 13 17 03](https://user-images.githubusercontent.com/10757813/210355759-744c545a-5c79-4d89-b8ab-bb8ef41c44bc.png)

**Comment by AMBudnik** [comment]
Yes, the issue is closed. But I just wanted to make sure that everything is working well.

Thank you very much for the update. Now everything's clear.
