### ISSUE TITLE
Can't "Remove Column" when "columns" property is used

### ISSUE THREAD

**Issue by mauriciogior** [handsontable/handsontable#10198]
### Description
When using the `columns` property, the `Remove Column` context menu is always disabled (regardless of the `allowRemoveColumn` property value)

### Steps to reproduce
1. Create a **Handsontable** object with a `columns` array for each column;
2. Verify that the `Remove Column` option is always disabled, even when using `allowRemoveColumn: true`;
3. `Remove Row` still works;
4. `Insert Column` is also disabled;

### Demo
https://jsfiddle.net/zg3kvqr6/1/

### Your environment
* Handsontable version: @latest
* Browser name and version: Chrome 108.0.5359.124
* Operating system: macOS Monterrey

**Comment by adrianszymanski89** [comment]
Hi @mauriciogior 

In the second case, you are passing an array of objects to the columns which do not support altering operations:

https://handsontable.com/docs/javascript-data-grid/api/core/#alter

**Comment by mauriciogior** [comment]
Hi @adrianszymanski89, thanks for your reply.

So does that mean that I cannot use the `columns` property if I want to allow altering operations? Why?

**Comment by adrianszymanski89** [comment]
There is a way. You have to use `updateSettings()` method to alter the array of objects in the columns, like here:

https://jsfiddle.net/aszymanski/ocp2bg51/

**Comment by mauriciogior** [comment]
So the Context Menu will not work on this scenario? I'd like to have my users adding columns themselves by using the Context Menu.

Thanks.

**Comment by adrianszymanski89** [comment]
Unfortunately not. You would need to write a custom dropdownMenu function to do this. Here's an example:

https://jsfiddle.net/aszymanski/ocp2bg51/1/

But still, it won't work in the same way as with the array of arrays.
