### ISSUE TITLE
[12.2.0] HandsonTable v12.3.0 is Laggy on Changing Tabs

### ISSUE THREAD

**Issue by KiddoV** [handsontable/handsontable#10194]
### Description
I used this library to create tabs [Fomantic-UI](https://github.com/fomantic/Fomantic-UI), I think it is similar to JQuery tabs.
I notice that on version 12.3.0, when changing tab the browser freeze for like 2-3 seconds, even though my table only has ~10 columns + ~400 rows.

So I rollback to 12.2.0 just to test, and find out the lag only appears on the newest version (12.3.0).

Not sure what changes on the new version that make it laggy like that.

### Steps to reproduce

1. Create simple jQuery tab, or FUI tabs
2. Put Handsontable on a tab with ~10 columns + ~400 rows.
3. Change tab to see the delay.

### Demo
_I can provide a JSFiddle if requires_

### Your environment
* Handsontable version: 12.3.0
* Browser name and version: Webview2 108.0.1462.54 | MS Edge | npm 8.15.0
* Operating system: Windows 10

**Comment by adrianszymanski89** [comment]
Hi @KiddoV 

Thank you for reporting this issue. Can you please send us the demo showing the issue so we can have the correct representation of the problem?

**Comment by KiddoV** [comment]
Here you go: http://jsfiddle.net/KiddoV/a3fpbh7q/18/

**Comment by KiddoV** [comment]
Take a look at my actual app here...

This is v12.2.0
![bug-v12 2 0](https://user-images.githubusercontent.com/28552977/209962533-cb6127b7-6e13-4834-89f2-87a04da7391b.gif)
... you can see the transition is very smooth when changing tabs.

This is v12.3.0
![bug-v12 3 0](https://user-images.githubusercontent.com/28552977/209962604-1628e52b-0b9a-4604-b9d5-cdc4884d9653.gif)
... as you can see, same table values, but there a delay when I go back to the tab that contains the table.

**Comment by adrianszymanski89** [comment]
Hi @KiddoV 

Thank you for the examples. I think that the reason for this might be the change that we introduced with this PR: https://github.com/handsontable/handsontable/pull/10130

We added some logic that fixes the issue with rendering the table if it's been initialized in a hidden container to avoid visual issues.

**Comment by KiddoV** [comment]
@adrianszymanski89 I see, earlier I had to add ``hot.render()`` every time I change the tab - but it works better than this tho. :)

**Comment by adrianszymanski89** [comment]
I'm glad we could find the reason and solution for this issue :)

**Comment by KiddoV** [comment]
I meant calling ``hot.render()`` on the old version v12.2.0. Call ``hot.render()`` on v12.3.0 still doesn't help anything.

**Comment by adrianszymanski89** [comment]
Ah, ok, I see. So, I'll discuss the issue with the team to determine if the fix I mentioned might be causing this.

**Comment by KiddoV** [comment]
Any solution, update on this? It has been awhile.

**Comment by AMBudnik** [comment]
Hi @KiddoV 

I see that this issue is added to our Roadmap, but not added to the next release list. I will keep you updated once it changes.

But also I wanted to confirm if you checked the table recreation. Maybe using [`destroy()`](https://handsontable.com/docs/javascript-data-grid/api/core/#destroy) and then initializing table would work as a temporary workaround?

**Comment by KiddoV** [comment]
@AMBudnik you meant destroy when tab is hide and re-init when it is in active?

**Comment by AMBudnik** [comment]
> @AMBudnik you meant destroy when tab is hide and re-init when it is in active? Will try that.

Yes, please keep me updated.

**Comment by KiddoV** [comment]
It is still laggy when I used ``hot.destroy()`` when tab is hidden.

**Comment by KiddoV** [comment]
Nice job! I will give it a try. Thank you so much!
