### ISSUE TITLE
AutoFill don't work properly with HyperFormula plugin enabled

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#10200]
### Description

If we have a table with the HyperFormula plugin enabled and we want to use autofill after filtering some of the values, the wrong index is taken.

### Steps to reproduce

1. From the dropdown menu filter out values 3 and 6.
2. Select the first cell (with the number 66) and use the autofill downwards the table.
3. The value that is getting repeated is 3, but it should be 66.

### Demo

With Hyperformula enabled (not working properly) - https://jsfiddle.net/aszymanski/2m3Lu159/
Without Hyperformula enabled (works correctly) - https://jsfiddle.net/aszymanski/ez4gn3cv/

### Your environment
* Handsontable version: Any version with HyperFormula 
* Browser name and version: Google Chrome 108
* Operating system: macOS Ventura 13.0

**Comment by AMBudnik** [comment]
The `beforeAutofill` when we use HyperFormula returns **different results for the 1st parameter** `selectionData`. Demo for tests https://jsfiddle.net/rjm6h35e/ (I added the hook log).

While doing this 
![Zrzut ekranu 2023-01-18 o 12 34 27](https://user-images.githubusercontent.com/10757813/213161357-9017d3d3-6e60-4c08-bff3-ba9a67bdd77d.png)

we get

* 4 elements in the console when `Formulas` plugin in on

![Zrzut ekranu 2023-01-18 o 12 34 33](https://user-images.githubusercontent.com/10757813/213161529-857301a7-b896-4b74-8f68-419169517b9c.png)
* 1 element in the console without formulas

![Zrzut ekranu 2023-01-18 o 12 34 50](https://user-images.githubusercontent.com/10757813/213161563-02876d66-a378-4bbf-b3fa-50acc483b365.png)

If we select two items `3` and `66` then 

* 4 elements in the console when `Formulas` plugin in on

![Zrzut ekranu 2023-01-18 o 12 39 12](https://user-images.githubusercontent.com/10757813/213162287-b82da49c-6af8-4bbc-a12a-0060f6a17228.png)
* 1 element in the console without formulas

![Zrzut ekranu 2023-01-18 o 12 39 34](https://user-images.githubusercontent.com/10757813/213162349-c6a4642e-03a7-44de-b173-35bfbf01f98e.png)

**Comment by aninde** [comment]
I made sure it works on 12.4.0. There is one unique specific case that still doesn't work. Autofill may not work properly when we have formulas enabled and we are trying to populate cells that are in the immediate vicinity of a trimmed row.
**Exception case:**
https://github.com/handsontable/handsontable/blob/30d22304b6300c414a3b74eecbe49b07816ee77c/handsontable/src/plugins/formulas/__tests__/plugins/autofill.spec.js#L105-L137

**Comment by AMBudnik** [comment]
Demo updated to v12.4.0 https://jsfiddle.net/handsoncode/enh3mcbz/ works well.

Issue closed as fixed in [Handsontable v12.4.0](https://handsontable.com/docs/javascript-data-grid/release-notes/#_12-4-0)
