### ISSUE TITLE
Horizontal Scrolling with Shift+Mousewheel does not work in Firefox

### ISSUE THREAD

**Issue by Skym0sh0** [handsontable/handsontable#10203]
### Description
I want to scroll horizontally using Shift+Mousewheel. In Chrome and Edge it works like a charm. In Firefox it results in a normal vertical scrolling.

Not even the example of the official documentation works for me: https://handsontable.com/docs/javascript-data-grid/row-virtualization/#configuring-row-virtualization

### Steps to reproduce
1. Have a table which has enough columns to scroll horizontally.
2. Press and hold Shift and scroll with your mousewheel.
3. Table scrolls up/down instead of right/left.

### Demo
Example from the official documentation
https://handsontable.com/docs/javascript-data-grid/row-virtualization/#configuring-row-virtualization

### Your environment
* Handsontable version: 12.3
* Browser name and version: Firefox (108)
* Operating system: Windows 10

**Comment by Skym0sh0** [comment]
Maybe it is related to issue https://github.com/handsontable/handsontable/issues/2722.

And as I am seeing now, it does not work in older versions as well: https://handsontable.com/docs/8.4.0/demo-scrolling.html

**Comment by adrianszymanski89** [comment]
Hi @Skym0sh0 

Yes, this is the same issue. I think we can close this one as a duplicate. Are you ok with that?

**Comment by Skym0sh0** [comment]
Sure
