### ISSUE TITLE
Cannot read properties of undefined (reading 'getBottomEndCorner') at Autofill.getCoordsOfDragAndDropBorders 

### ISSUE THREAD

**Issue by jhon20suarez** [handsontable/handsontable#10211]
### Description
In the current project, we are trying to implement hansontable, carrying out some tests and validating functionalities. So far only the action of dragging a value from one cell to another fails. The issue has been identified to be caused when the Angular component has 'ViewEncapsulation.ShadowDom' enabled.
I had had this problem before with primeNG, and they solved it through a directive.
But so far we have not been successful in solving it with handontabl

### Steps to reproduce
@Component({
... ,
  encapsulation: ViewEncapsulation.ShadowDom,
})

![Screenshot (228)](https://user-images.githubusercontent.com/65566093/212679874-87fd6868-b8bd-4ce4-9a40-ff95ff4790c3.png)

### Your environment
* Angular version: 14.2.0
* Handsontable version: 12.3.0
* Browser name and version: Microsoft Edge 109.0.1518.55; Chrome 109.0.5414.75
* Operating system: Windows 10

**Comment by jhon20suarez** [comment]
[sample code
](https://codesandbox.io/p/github/jhon20suarez/demoHandsontable/draft/jovial-neco?file=%2Fsrc%2Fapp%2Fapp.component.ts&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A8%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cld0ai1z0000c8tfr7gvpe95y%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cld0audmr00132a681jr027cr%2522%253A%257B%2522key%2522%253A%2522cld0audmr00132a681jr027cr%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A4200%252C%2522key%2522%253A%2522cld0audmr00142a68vmjbxwaw%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cld0audmr00132a681jr027cr%2522%252C%2522spacesOrder%2522%253A%255B%2522cld0audmr00132a681jr027cr%2522%255D%257D)

**Comment by adrianszymanski89** [comment]
Hi @jhon20suarez 

Thank you for the example. In the past, we did some testing regarding Handsontable and Shadow DOM. Maybe this example will be helpful for you as a reference:

https://codesandbox.io/s/handsontable-javascript-data-grid-hello-world-app-forked-2x11xm?file=/src/index.js

**Comment by jhon20suarez** [comment]
The example presents the same problem.

![Screenshot (231)](https://user-images.githubusercontent.com/65566093/212937437-489c1454-c1d9-4760-a53e-82a4211df8bd.png)

**Comment by adrianszymanski89** [comment]
You are right. I've found that we have the same issue already reported here: https://github.com/handsontable/handsontable/issues/7199

I will close this one as a duplicate.
