### ISSUE TITLE
ManualRowMove plugin don't work properly with NestedRows plugin enabled

### ISSUE THREAD

**Issue by salimmenari** [handsontable/handsontable#10214]
### Description
If we have a table with the NestedRows plugin enabled and we want to use in addition the ManualRowMove plugin to move a row into a group, or if we want to move a row before or after a group, nothing happen. It should move the row where the user drops it.

### Steps to reproduce
using the demo bellow, trying any of these steps :

- Move the row 1, 2 or 5 into the group at index 3
- Move the row 1 or 2 after the group at index 3
- Move the row 5 before the group at index 3

### Demo
https://jsfiddle.net/qr907fv1/1/

![2023-01-20_12-09-55](https://user-images.githubusercontent.com/24541344/213681641-3f8c4093-b6e9-4c90-9632-d6525310a851.gif)

### Your environment
* Handsontable version: 12.3.0
* Browser name and version: Edge 109.0.1518.55
* Operating system: Windows 10

**Comment by AMBudnik** [comment]
Hi @salimmenari 

Thank you for the report. 

Since v8.0.0 we do not support manual row moving while using nested rows. However, you can still move rows programmatically by using `dragRows()` method. Here's a demo https://jsfiddle.net/51jhb8qf/
