### ISSUE TITLE
Filter by value not possible to customize

### ISSUE THREAD

**Issue by robertovaldesperez** [handsontable/handsontable#10230]
### Description
Filtering by value shows the cell value instead of the one I have rendered

### Steps to reproduce
1. Press column filter

### Demo
![image](https://user-images.githubusercontent.com/15571467/216599149-f202479e-0f38-4464-b4b9-06e27c030fca.png)

### Your environment
* Handsontable version: 12.3.0
* Browser name and version: Chrome 109.0.5414.120
* Operating system: Windows 11 Pro

**Comment by robertovaldesperez** [comment]
Hi I have the application in production and it is important that the user can filter by the columns and that the filters of these columns show a friendly text

**Comment by adrianszymanski89** [comment]
Hi @robertovaldesperez 

You can style the filter menu labels by modifying the CSS directly. At the moment, this is the only option available.

**Comment by robertovaldesperez** [comment]
@adrianszymanski89 Do you think that in the near future they will support this functionality?

**Comment by adrianszymanski89** [comment]
@robertovaldesperez There are plans for better styling customization, but we don't have the timeline for this project yet.

**Comment by robertovaldesperez** [comment]
@adrianszymanski89 How could I customize these values ​​through styles?

**Comment by adrianszymanski89** [comment]
@robertovaldesperez 

You would need to modify this class: `.handsontable .htCheckboxRendererLabel` to style the label of the filtering menu. However, you have to keep in mind that currently, it's a workaround, and there might be some issues with proper table rendering while styling those elements directly like this.
