### ISSUE TITLE
Removed cell values come back

### ISSUE THREAD

**Issue by patrickm** [handsontable/handsontable#1023]
Environment: any cell with data, no cells selected

Reproduction:
1. Click on a cell with data
2. Press backspace to clear cell
3. Press enter to begin editing
Removed cell value will come back in text editor

Note: either moving by arrows to different cell as well as clicking on a different cell and coming back to tested cell properly begins editing empty value

Affected versions checked: 0.9.15, 0.9.16, 0.9.17

**Comment by AMBudnik** [comment]
Please update to [0.14.0](https://github.com/handsontable/handsontable/releases/tag/0.14.0), works fine (value is not comming back)
