### ISSUE TITLE
Destory method don't destroy the instance

### ISSUE THREAD

**Issue by lucasgarciabertaina** [handsontable/handsontable#10248]
### Description
I have a problem deleting the spreadsheet instance before destroying the component. When I mount a new table, the configuration of the previous table persists.

Here is a [video showing the bug](https://www.youtube.com/watch?v=niu-M0xlPuA).

### Your environment
* Handsontable version: 12.3.1
* Browser name and version: 109.0.1
* Operating system: Linux

**Comment by AMBudnik** [comment]
Hi @lucasgarciabertaina 

Did I assume right (based on the port from the video) that you use React? If so, do you use the wrapper for React for Handsontable or the Vanilla version?

**Comment by lucasgarciabertaina** [comment]
Hi @AMBudnik

I don't use react, rather I use vue2 wrapper and the vanilla package.

**Comment by AMBudnik** [comment]
This is an example of the `destroy()` method called for the Handsontable instance with the use of Vue 2 wrapper https://jsfiddle.net/v5gqr9xn/
Do you use it the same way? 

ps. If you would prefer to update the same instance with new data and settings it is also possible by the use of `[updateSettings()` method](https://handsontable.com/docs/javascript-data-grid/api/core/#updatesettings).

**Comment by lucasgarciabertaina** [comment]
Yes, I use it in the same way. I even call the `destroyEditor()` method first and then the `destroy()` method.

**Comment by AMBudnik** [comment]
I think I need to ask for a demo to replicate the issue. Or we can schedule a quick call to replicate it together. If that sounds like a good plan please contact me at support@handsontable.com to discuss details.
