### ISSUE TITLE
Scrolling from bottom to top is slower than from top to bottom

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#10253]
### Description

Scrolling from bottom to top is slower than from top to bottom. It is more noticeable when we have more rows in the table.

### Steps to reproduce

1. Go to the demo
2. Select `A1` and use arrow down key to scroll the table down
3. Select `A500000`and use arrow up key to scroll the table up

### Demo

https://jsfiddle.net/rL6nxpfc/1/ (v12.3.1)

### Your environment
* Handsontable version: 12.3.1
_That is not a regression_
* Browser name and version: Chrome
* Operating system: 110

**Comment by adrianszymanski89** [comment]
Fixed in 14.5.
