### ISSUE TITLE
Sorting while editing updates the wrong row

### ISSUE THREAD

**Issue by EmilioCristalli** [handsontable/handsontable#10254]
### Description
If I sort by a column while editing a cell, the wrong cell is changed.

AFAICT it only happens if the column you are editing has `type: 'numeric'`

With `type: 'numeric'` (edits wrong cell):
https://user-images.githubusercontent.com/972779/220439752-7ed1062b-87b4-4708-8f52-1ffd22c99d17.mov

Without `type: 'numeric'` (edits right cell):
https://user-images.githubusercontent.com/972779/220441147-eefbb546-8265-4f8a-8dd9-4b4d93e1d754.mov

### Steps to reproduce
1. Create table with `columnSorting: true`, and two columns (one of them with `type: 'numeric'`)
2. Start editing one of the cells in the numeric column (without pressing enter or clicking outside)
3. While still editing, click the other column header to sort by that column

I would expect the edited cell to follow the corresponding row after sorting, but it instead stays in the same row so it edits a different cell than the one initially selected

### Demo
https://jsfiddle.net/L5nxw0fh/2/

### Your environment
* Handsontable version: 12.3.1  (See the same issue with 11.1.0)
* Browser name and version: Chrome 109.0.5414.119 (Official Build) (x86_64)
* Operating system: macOS 13.2.1

**Comment by adrianszymanski89** [comment]
Hi @EmilioCristalli 

Thank you for reporting this issue. We weren't aware of this, and the current behavior is definitely wrong. We'll let you know when we fix this.

**Comment by AMBudnik** [comment]
Hi @EmilioCristalli. I have great news today!

The issue that you reported is fixed in the version we released today - Handsontable v14.6.0.
Updated demo: https://jsfiddle.net/w6v4bro2/

Here you can read more about the changes within this version https://handsontable.com/docs/react-data-grid/changelog/
