### ISSUE TITLE
render() issue with AngularJS

### ISSUE THREAD

**Issue by noahkeitel** [handsontable/handsontable#1025]
Issue:
1. handsontable object is inside a DOM element which is hidden via AngularJS's ng-show="false"

2. We add rows to our handsontable via the .alter('insert_row') method and render() it
3. We set our DOM element to ng-show="true".
--everything works fine--

4. Now we remove rows via the .alter('remove_row') method.
5. Set the DOM to ng-show="false"
--still good--

6. Add rows to the same handsontable via the .alter('insert_row') method and .render() it
7. We make sure the rows were added by logging ourTableObject.getData() to the console.
--all good still--

8. We set our DOM to ng-show="true"
-- This is the point at which the table has NOT rendered like it should have--

I've tried to set ng-show to true before adding the rows in step 6 to see if it works but it doesn't. As long as I don't set ng-show="false" ever, all added and removed rows work and render correctly. Not sure if this is an issue with the time things are fired in AngularJS's digest/apply or if it's an issue with handsontable.

**Comment by AMBudnik** [comment]
Issue closed in lack of JSFiddle demo
