### ISSUE TITLE
ChangeSource Type Error :  ContextMenu.clearColumns ->  ContextMenu.clearColumn

### ISSUE THREAD

**Issue by arvinxx** [handsontable/handsontable#10261]
### Description

the type defination is not match document.

Here is the code:
https://github.com/handsontable/handsontable/blob/648dcfa03a4c64bf5a86c84ac39775477bd53301/handsontable/types/common.d.ts#L54

Here is the document:

https://handsontable.com/docs/react-data-grid/events-and-hooks/#definition-for-source-argument

### Demo

<img width="834" alt="image" src="https://user-images.githubusercontent.com/28616219/221420265-6e3faf44-afbb-49ab-aeb7-5fc31e3a1658.png">

### Your environment
* Handsontable version: 12.3.1

**Comment by AMBudnik** [comment]
Hi @arvinxx 

Thank you for taking the time to report this issue.

It seems to be the same issue as https://github.com/handsontable/handsontable/issues/9566. I will raise its priority and notify you as soon as we fix it.
