### ISSUE TITLE
[v12.0.0+] Crash when pressing the delete or backspace keys after deselecting a cell

### ISSUE THREAD

**Issue by kalegos** [handsontable/handsontable#10272]
### Description
Handsontable will crash if you click on a cell, then click on the empty area of the table body and press either delete or backspace

### Steps to reproduce
1. click on a cell
2. click on the empty part of the table body (inside the main container where there are no additional rows) to deselect the cell
3. press the delete or backspace button

### Demo
[Crash on landing page](https://ibb.co/Rbhgkrh)
[Line that is crashing](https://github.com/handsontable/handsontable/blob/9b6b4ad981c1c62ba5b7ad0a2c103d8450db8b4d/handsontable/src/editorManager.js#L203)

### Your environment
* Handsontable version: 12.3.1
* Browser name and version: Firefox
* Operating system: Linux

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report, @kalegos 

It seems that this issue appears when we have a container size defined, and we use Handsontable v12.0.0+. v11.1 works well https://jsfiddle.net/jvr9soq7/

On Firefox the error is

```js
Uncaught TypeError: this.instance.getSelectedRangeLast() is undefined
    prepareEditor https://cdn.jsdelivr.net/npm/handsontable@12/dist/handsontable.full.js:30320
    callback https://cdn.jsdelivr.net/npm/handsontable@12/dist/handsontable.full.js:30238
    keyRecorder https://cdn.jsdelivr.net/npm/handsontable@12/dist/handsontable.full.js:107118
    onkeydown https://cdn.jsdelivr.net/npm/handsontable@12/dist/handsontable.full.js:107506
    mount https://cdn.jsdelivr.net/npm/handsontable@12/dist/handsontable.full.js:107546
    createShortcutManager https://cdn.jsdelivr.net/npm/handsontable@12/dist/handsontable.full.js:107133
    Core https://cdn.jsdelivr.net/npm/handsontable@12/dist/handsontable.full.js:66600
    Handsontable https://cdn.jsdelivr.net/npm/handsontable@12/dist/handsontable.full.js:91613
    <anonymous> https://fiddle.jshell.net/_display/?editor_console=true:116
```

but on Chrome, it's 

```js
Uncaught TypeError: Cannot read properties of undefined (reading 'highlight')
    at EditorManager.prepareEditor (handsontable.full.js:30320:71)
    at callback (handsontable.full.js:30238:18)
    at handsontable.full.js:107118:32
    at HTMLHtmlElement.onkeydown (handsontable.full.js:107506:32)
```

Minimal v12 demo for tests https://jsfiddle.net/jvr9soq7/

**Comment by ganbat96** [comment]
Hello,

We're experiencing the same issue. It was working fine under Handsontable v3.0.0. Issue appeared after we upgraded to v12.

We've also found a workaround for it and it seems like working fine ...
https://github.com/handsontable/handsontable/issues/401#issuecomment-562487158

Hope it helps...

**Comment by AMBudnik** [comment]
Thank you for feedback @ganbat96 

I will notify you as soon as we provide the official fix for this regression
