### ISSUE TITLE
Typo in comment for the API option "maxrows"

### ISSUE THREAD

**Issue by morningdew830** [handsontable/handsontable#10289]
https://github.com/handsontable/handsontable/blob/b65c638d70a897b843edad1831e05f97f8407ef6/handsontable/src/dataMap/metaManager/metaSchema.js#L2943

**Comment by morningdew830** [comment]
`the initial number of columns` should be amended to `the initial number of rows`

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @morningdew830

**Comment by morningdew830** [comment]
I opened [this PR](https://github.com/handsontable/handsontable/pull/10290) but actually its not so worthy lol

**Comment by AMBudnik** [comment]
If it solves the issue it's just enough :)

**Comment by AMBudnik** [comment]
The issue can be closed as the changes are merged into the `develop` branch. Closed as done.
