### ISSUE TITLE
Can i Set CSS for Rowheader ?

### ISSUE THREAD

**Issue by PTOAKKY** [handsontable/handsontable#10283]
how to set CSS for rowheader ?

expect -> i nedd to set rowheader to center in vertical & horizontal

give me some example please.

**Comment by adrianszymanski89** [comment]
Hi @PTOAKKY 

You can attach a custom CSS class to the row headers by using our hook `afterGetRowHeader`. Here's an example:

https://jsfiddle.net/aszymanski/32qnLape/
