### ISSUE TITLE
Error Throws When Removing Fixed Columns

### ISSUE THREAD

**Issue by KiddoV** [handsontable/handsontable#10293]
### Description
I got this error when trying to remove the fixed column(s) using ``contextmenu``:
```console
null:30339 
        
       Uncaught Error: The `fixedColumnsLeft` and `fixedColumnsStart` should not be used together. Please use only the option `fixedColumnsStart`.
    at ExtendMetaPropertiesMod2.onChange2 (null:30339:17)
    at TableMeta2.set [as fixedColumnsStart] (null:30379:21)
    at null:31258:45
    at arrayEach (null:8329:9)
    at removeCol2 (null:31244:13)
    at Object.alter (null:31270:13)
    at Core.alter (null:32251:10)
    at Core.callback (null:45089:12)
    at null:44578:25
    at arrayEach (null:8329:9)
```
Although the error said that ``The `fixedColumnsLeft` and `fixedColumnsStart` should not be used together``, I only used 1 option though which is ``fixedColumnsLeft``.
This error is not for the current situation anyway, and also after the error occurred, user can now remove the entire column on a table, even set ``minCols`` > 0.

### Demo
![bug](https://user-images.githubusercontent.com/28552977/225304175-30a427ee-6d83-44d0-971b-7bbab51ac861.gif)

### Your environment
* Handsontable version: 12.2.0
* Browser name and version: webview2
* Operating system: Windows 10

**Comment by AMBudnik** [comment]
Hi @KiddoV 

If you are on v12+ I recommend replacing `fixedColumnsLeft` with `fixedColumnsStart`. We changed the name, so it's more understandable when users use RTL mode (cause then the column is on the right side of the table). It's just naming, so it will not change anything in your table and the error is no longer there.

However, I see that there's a note in the [Hiding guide](https://handsontable.com/docs/javascript-data-grid/column-freezing/) about an error in RTL

![Zrzut ekranu 2023-03-15 o 14 13 14](https://user-images.githubusercontent.com/10757813/225319235-e19df9d3-7b68-4aba-8773-77d5c60634d6.png)

but we do not mention the error appearing when user hides columns

**Comment by KiddoV** [comment]
Another question. How do I prevent user from deleting the fixed column?

**Comment by AMBudnik** [comment]
Hm... the easiest way would be to prepare an object-based context menu with the `hidden` function for `remove_col` option. You can specify for which index in the table the option should be hidden. So if you have 2 fixed columns then the `hidden` function should be set to

```js
 hidden: function() {
        return hot.getSelectedRangeLast().to.col < 2
}
```

And here is all that in the demo http://jsfiddle.net/eq05wzL9/2/

**Comment by KiddoV** [comment]
Thank you!
