### ISSUE TITLE
Custom location or render for column header

### ISSUE THREAD

**Issue by aboveyunhai** [handsontable/handsontable#10298]
### Description

is it possible to decouple column header UI or get the render data for the column from right click or dropdown icon.
So we can basically render it somewhere else

### Demo

![image](https://user-images.githubusercontent.com/35160613/226408580-92f857f9-5801-483a-ac83-930e525d9002.png)

### Your environment
* React wrapper version: latest
* Handsontable version: latest
* Browser name and version: latest
* Operating system: win10

**Comment by AMBudnik** [comment]
Hi @aboveyunhai 

When the user opens the menu you can try to modify the CSS of the menu element like here https://jsfiddle.net/qbcd0nhy/

Alternatively, there's a method for opening the dropdownMenu, called [`open()`](https://handsontable.com/docs/react-data-grid/api/dropdown-menu/#open) where you can pass the expected position of the window.

**Comment by AMBudnik** [comment]
The `open()` method takes the coordinates, so why can you pass the coordinates of your custom element? It is just a matter of the Handsontable menu showing on the top of that element as still, it is an integral part of the Handsontable structure (and itself a menu is a 1-d Handsontable table). 

It is not possible to pass an external element to be the parent of the dropdown menu in Handsontable. If this does not meet your project requirements, you could consider creating your own panel. For example, in the 'Filter from the outside the table' section of the Handsontable documentation for column filters, there's an example of how to create a custom filter panel. You can find it at https://handsontable.com/docs/javascript-data-grid/column-filter/#filter-from-the-outside-the-table.

**Comment by aboveyunhai** [comment]
@AMBudnik  oh, nice, as long as I can replicated the dropdown functionality by myself, then the right click doesn't matter in this case.
