### ISSUE TITLE
Not every printable key opens editor

### ISSUE THREAD

**Issue by PaperDominicPile** [handsontable/handsontable#1029]
There are keys that do not open the editor. When I push "-" or "_" or "+" on a German layout, nothing happens. I first have to double click on the cell to make it editable and then I can write these symbols. Would be nice if the editor opens whenever I push a key with a printable character and it writes the key to the cell.

Might be related to #1028.

**Comment by AMBudnik** [comment]
I couldn't reproduce it in HOT 0.13.0 version on 
* Chrome 41.0.2272.89 (64-bit)
* Firefox 36.0.1
* Safari 8.0.3 (10600.3.18)

If you still have this problem, please let us know.
