### ISSUE TITLE
Merged cells in fixed column hidden when rowHeaders is false (mergeCells plugin, fixedColumnsStart, rowHeaders)

### ISSUE THREAD

**Issue by andiwi** [handsontable/handsontable#10303]
### Description
I am using the `fixedColumnsStart` property and the `mergeCells` plugin together in a Handsontable table. Specifically, I am merging cells in a column that is fixed using the `mergeCells` plugin.

The issue I am encountering is that when `rowHeaders` is set to false, the merged cell in the fixed column is hidden instead of being displayed as expected. However, when `rowHeaders` is set to true, the merged cell is displayed correctly.

I have verified that the issue is not related to any conflicting settings or custom code in my implementation. I have also checked the Handsontable documentation and could not find any information that suggests that this behavior is expected.

### Steps to reproduce:

1. Set `fixedColumnsStart` to a positive integer value.
2. Enable the `mergeCells` plugin.
3. Merge cells in a fixed column.
4. Set `rowHeaders` to false.

#### Expected behavior:
The merged cell in the fixed column is displayed.

#### Actual behavior:
The merged cell in the fixed column is hidden.

### Demo
See: https://jsfiddle.net/andiwi/tbqe9npL/85/
(set `rowHeaders: true` to see the expected result)

In my example I merge cells in two columns: `A` and `C`
- merging cells in a non-fixed column (column `C`) works as expected
- merging cells in a fixed column (column `A`) hides the merged cell instead of displaying it

### Your environment
* Handsontable version: 12.3.2
* Browser name and version: Chrome
* Operating system: MacOS

**Comment by AMBudnik** [comment]
Hi @andiwi 

I think that this issue is already reported here https://github.com/handsontable/handsontable/issues/4016 

Please let me know if there are any differences, but it seems to have the same origin.

**Comment by andiwi** [comment]
@AMBudnik yes they have the same origin. I didn't find the issue before opening this one.

**Comment by AMBudnik** [comment]
No worries, @andiwi 

I will close this issue as a duplicate. But I will notify you as soon as we fix the origin issue.

**Comment by andiwi** [comment]
Thank you. 

For all who have the same problem and want to hide the rowHeaders: I used the following settings as a workaround:
```
rowHeaders: true,
rowHeaderWidth: 0,
```

**Comment by liu770848166** [comment]
> Thank you.
> 
> For all who have the same problem and want to hide the rowHeaders: I used the following settings as a workaround:
> 
> ```
> rowHeaders: true,
> rowHeaderWidth: 0,
> ```

 Good workaround!

**Comment by adrianszymanski89** [comment]
Hi @andiwi 
 
I am happy to inform you that this issue was fixed in the newest release of Handsontable 14.5: https://github.com/handsontable/handsontable/pull/10995
