### ISSUE TITLE
Column sorting does not work correctly with fixedColumnsLeft option

### ISSUE THREAD

**Issue by AnthonyPeron** [handsontable/handsontable#1031]
When I set fixedColumnsLeft and I try to sort by the fixed column after scrolling horizontally, sort is made on the column that should be there instead of the fixed column.

Here is an example as asked : http://jsfiddle.net/8k38P/
If you scroll right (and hide only column B), when you try to sort by column A, it will sort as if it was column B.

**Comment by AMBudnik** [comment]
Hi I tried to reproduce this issue with updated to 0.14.1 [demo](https://jsfiddle.net/8k38P/1/) and it works OK. Please check it and if it does not work as you expected - give us a feedback.
