### ISSUE TITLE
How to set edit cell with only number.

### ISSUE THREAD

**Issue by PTOAKKY** [handsontable/handsontable#10318]
![image](https://user-images.githubusercontent.com/59352415/230004071-e1287266-78fb-4b2b-aec3-871159d1188d.png)

From this image. Can i set while editing cell user can type only number.

expect 1 -> type "123Test456" on keyboard will show "123456"
expect 2 -> type "abcdefg31.325" on keyboard  will show "31.325"
expect 3 -> can i set max of decimal digits ?

**Comment by AMBudnik** [comment]
Hi @PTOAKKY 

You can use the `beforeKeyDown` hook to block all the non-numeric keys. Here's how to do it https://jsfiddle.net/yedhargb/ (we generate a regex that checks the key).

ps. Here's how it can be handled by the cell validator (you allow to type any value but color it red if incorrect) - https://handsontable.com/blog/guide-to-basic-data-validation

**Comment by PTOAKKY** [comment]
> Hi @PTOAKKY
> 
> You can use the `beforeKeyDown` hook to block all the non-numeric keys. Here's how to do it https://jsfiddle.net/yedhargb/ (we generate a regex that checks the key).
> 
> ps. Here's how it can be handled by the cell validator (you allow to type any value but color it red if incorrect) - https://handsontable.com/blog/guide-to-basic-data-validation

Thanks.
