### ISSUE TITLE
Missing Handsontable.renderers.DropdownRenderer

### ISSUE THREAD

**Issue by omquintela** [handsontable/handsontable#10325]
### Steps to reproduce

1.  Handsontable.renderers.DropdownRenderer => renderers don't have a DropdownRenderer
### Your environment
* Handsontable version: 12.3.1

**Comment by adrianszymanski89** [comment]
Hi @omquintela 

Can you please describe your issue a little bit more? If you mean that you can't access the DropdownRenderer for a start, you can check if you correctly registered all modules. Here's a documentation entry about this process:

https://handsontable.com/docs/react-data-grid/installation/#_3-register-handsontable-s-modules

**Comment by omquintela** [comment]
Hi @adrianszymanski89 thanks for your answer that helped me out. The problem seems to be that the DropdownRenderer is not exported from the renderers namespace. That is why I got a compiler error, I am using Typescript. 

See handsontable/index.d.ts namespace renderers.

**Comment by adrianszymanski89** [comment]
Hi @omquintela 

That's correct, as dropdownRenderer isn't a standalone renderer like others. It's an extension of autocompleteRenderer with swapped cell editor. I'll report this for further investigation.

**Comment by AMBudnik** [comment]
Hi @omquintela I am happy to announce that this issue was fixed in v14.1.

If you would find any difficulties with that please contact us at support@handsontable.com
