### ISSUE TITLE
请问一下handsontable有setData方法吗

### ISSUE THREAD

**Issue by dxfstart521** [handsontable/handsontable#10323]
我的项目中用了handsontable，场景是这样，我导入进来了excel，解析了用js-xlsx库解析出来了数据，请问handsontable有setData更新整个表格api吗？求一个地址

**Comment by dxfstart521** [comment]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/31570901/231333552-0546b311-8e79-4255-ad25-542331ba971d.png">
但是文档中找不到setData 这个方法呢

**Comment by dxfstart521** [comment]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/31570901/231333844-2f1bfc1e-64e3-4c21-964a-16c40b8c366a.png">
官网中没有找到setData使用方法呢

**Comment by AMBudnik** [comment]
Hi @dxfstart521 

to change the data in Handsontable you can either call `updateData()` or `loadData()` to replace the whole dataset or `setDataAtCell()` or `setDataAtRowProp()` to replace a single cell/cells.

* `updateData()` https://handsontable.com/docs/javascript-data-grid/api/core/#updatedata
* `loadData()` https://handsontable.com/docs/javascript-data-grid/api/core/#loaddata
* `setDataAtCell()` https://handsontable.com/docs/javascript-data-grid/api/core/#setdataatcell
* `setDataAtRowProp()` https://handsontable.com/docs/javascript-data-grid/api/core/#setdataatrowprop

**Comment by Chankafung** [comment]
How should I execute the Undo method, when I execute updateData or loadData？

**Comment by AMBudnik** [comment]
If I understand all the requirements correctly, @AMBudnik 

I would recommend using the `populateFromArray()` method to pass all the data at once. Here https://stackblitz.com/edit/vitejs-vite-34zhwh?file=main.js,style.css&terminal=dev is an example where one button copies the data (read from the `getDataAtRow()` method), and the second one uses `populateFromArray()` method to pass the data to the row.

Once we use CTRL/CMD + Z to undo, all the newly added data is reverted.
