### ISSUE TITLE
Missing type for hiddenRows `copyPasteEnabled` setting

### ISSUE THREAD

**Issue by micahbf** [handsontable/handsontable#10329]
### Description
The `copyPasteEnabled` setting is missing from the type for hidden rows settings.

https://github.com/handsontable/handsontable/blob/develop/handsontable/types/plugins/hiddenRows/hiddenRows.d.ts#L4
https://handsontable.com/docs/javascript-data-grid/api/options/#hiddenrows

### Steps to reproduce

1. Add the `copyPasteEnabled` setting to `hiddenRows`
2. Observe type error

### Your environment
* Handsontable version: 12.3.3
* Browser name and version: n/a
* Operating system: n/a

**Comment by AMBudnik** [comment]
Hi @micahbf 

Thanks for sending in your report. Just wanted to let you know that we're already aware of the issue, and it's been reported here: https://github.com/handsontable/handsontable/issues/8850. However, I'll put in a good word to raise the priority and hopefully, we can get a fix out soon. 

I will close this issue as a duplicate but will make sure to notify you as soon as the main issue is solved.
