### ISSUE TITLE
Function copy cell value by mouse down does not work in Edge WebView 2

### ISSUE THREAD

**Issue by conschtek** [handsontable/handsontable#10336]
### Description
When copying a cell value by clicking and holding the right corner of the cell does not function / only copies 0 values. This issue only occurred when using the Edge WebView 2.

### Steps to reproduce
1. Open Handsontable in Edge WebView 2
2. Add value in a cell
3. Click the right corner, hold it and copy the value in the neighbouring cells 
--> Not the given value is copied, but just 0s

### Demo
Please see attached video:
https://user-images.githubusercontent.com/117377149/234219935-ca161179-49cb-4b95-bb4d-abc4c13a4052.mov

### Your environment
* Handsontable version: 12.3.1
* Browser name and version:  Edge WebView(2)
* Operating system: Windows

**Comment by adrianszymanski89** [comment]
Hi @conschtek 

As far as I know, WebView is based on Chromium, just like Edge and Google Chrome, so there shouldn't be any differences. However, there may be some differences in how the compiled app is being interpreted.

Is there a possibility that you can share your app, so we can see the code?

**Comment by AMBudnik** [comment]
Hi @conschtek We will need to close the issue report if the demo is not provided. Can you update us with one?

**Comment by conschtek** [comment]
Sorry for the late reply, unfortunately I cannot provide a demo, but thank you for the quick response!
