### ISSUE TITLE
Autofill after column sort not functioning as expected with HyperFormula in vuejs3

### ISSUE THREAD

**Issue by cricketthomas** [handsontable/handsontable#10339]
### Description
When you have a column sorted, then you drag the selector down to auto fill values, you would expect the value you started from to be filled in all the rows you drag it to. This only happens with when the hyperformula plugin in added to the Handsontable instance.

### Steps to reproduce

1. Add columnSorting, HyperForumla and then sort a column, then try to autofill values. The values will not reflect what has been dragged.

[screen-capture.webm](https://user-images.githubusercontent.com/15821271/234333288-20d42c1f-7a90-4a92-9cea-bb8e4176d3d0.webm)

### Demo
https://jsfiddle.net/ayw4pm7o/2/

### Your environment
* Handsontable version: 12.3.3
* Browser name and version: Edge/Chrome
* Operating system: WindowsOS

**Comment by adrianszymanski89** [comment]
Hi @cricketthomas

This issue is known to us, and currently, we are working on improving the connection between HyperFormula and core Handsontable features. The fix should be ready with the next release.

**Comment by cricketthomas** [comment]
closing as this is a duplicate of https://github.com/handsontable/handsontable/issues/10200

**Comment by AMBudnik** [comment]
Hi @cricketthomas 

I am more than happy to announce that the following issue is closed by https://github.com/handsontable/handsontable/issues/10200 in Handsontable v12.40 - our new release.

Here https://handsontable.com/docs/javascript-data-grid/release-notes/#_12-4-0 you can read more about the changes within this version.
