### ISSUE TITLE
Row header height not adaptative on custom image renderer

### ISSUE THREAD

**Issue by AbdiasCav** [handsontable/handsontable#10330]
### Description
When customizing the image renderer it seems that the image is added after the row height is set, is there any way to solve this?

It seems that only happens the first time you open the page and load the grid, after the first time works fine, even if the page is refreshed

![image](https://user-images.githubusercontent.com/131279663/233157597-24452330-a948-49d9-8618-2d0368d356ab.png)

### Demo
https://jsfiddle.net/AbdiasCavada/6ow0zvem/1/

**Comment by Noothan-am** [comment]
hi i wanted to work on this issue can you please assign it to me?

**Comment by AMBudnik** [comment]
Hi @AbdiasCav @Noothan-am 

Handsontable does not calculate the size of the image, so it renders on the default setting of 23px height for the row. If you, however, know the height of the image, you can use that data to determine the height needed for the image to fully show. Here's an example https://jsfiddle.net/dwzfg6ap/3/  

This topic was also mentioned here https://github.com/handsontable/handsontable/issues/10084.
