### ISSUE TITLE
uncaught exception throw if handsontable is within a display:none div

### ISSUE THREAD

**Issue by byang183** [handsontable/handsontable#10331]
### Description
uncaught exception throw if handsontable is within a display:none div

<img width="1346" alt="Screenshot 2023-04-19 at 4 01 22 PM" src="https://user-images.githubusercontent.com/61418548/233187686-66a4c6ad-1efa-406c-88b4-d7ae9dbb9678.png">

### Steps to reproduce

example repo
https://github.com/byang183/test-handsontable/blob/main/src/App.js

1. clone the app
2. `npm install`
3. launch the app by `npm start`

### Demo

This issue only happens when running react dev mode, so, it cannot be reproduced from jsfiddle

### Your environment
* React wrapper version: `react@18.2.0` `react-dom@18.2.0`
* Handsontable version: `handsontable@12.3.3` `@handsontable/react@12.3.3`
* Browser name and version: Version 112.0.5615.121 (Official Build) (x86_64)
* Operating system: MacOS, Ventura 13.3.1

**Comment by adrianszymanski89** [comment]
Hi @byang183 

There seems to be an issue with the repository. I can't install dependencies within your project. Can you please check if everything is correct here?

**Comment by byang183** [comment]
lock file has been updated, shall able to work now, 

_got corp registry included in lock file_

**Comment by adrianszymanski89** [comment]
Hi @byang183 

Thank you, now it works. I will investigate it and get back to you next week.

**Comment by adrianszymanski89** [comment]
Hi @byang183 

It looks like the issue is connected to the known problem of managing the Handontable visibility through the `display` property in CSS. Until it is fixed by us, we recommend using the `visibility` property instead, which works correctly.

**Comment by byang183** [comment]
Is there a issue link for this `the known problem of managing the Handontable visibility through the display property in CSS.`

**Comment by adrianszymanski89** [comment]
Hi @byang183 

We have it reported internally. I attached your issue there, and I will inform you once we start working on it.
