### ISSUE TITLE
Angular v16 (Ivy support)

### ISSUE THREAD

**Issue by bah99** [handsontable/handsontable#10349]
### Description

I received this error message after migrating to Angular v16, which no longer supports the view engine and requires the usage of the Ivy rendering engine instead.

![image](https://user-images.githubusercontent.com/31727552/236475917-8999e709-77b6-4a35-944f-2d2ff5e25307.png)

### Your environment
* Angular version: 16
* Handsontable version: 12.3.3
* Wrapper version:
* Browser name and version:
* Operating system: windows

**Comment by adrianszymanski89** [comment]
Hi @bah99 

We are aware of this issue and have already reported it internally. We should have more information on the next steps at the beginning of the following week.

**Comment by acayroche** [comment]
Hello, do you have any news about this issue ?

**Comment by chrissena** [comment]
Hi @adrianszymanski89. Any idea of a timeline when this fix will be released?
This issue is currently holding us back from releasing some important features in our app.
Thanks!

**Comment by adrianszymanski89** [comment]
Hi @chrissena 

We are working on the fix right now. I should have more info on the probable release date tomorrow. I'll keep you updated.

**Comment by chrissena** [comment]
@adrianszymanski89  I see this issue is closed and PR merged which is great news. When will the fix be released?
Really desperate for this update!

Thanks again for the updates

**Comment by adrianszymanski89** [comment]
Hi @chrissena 

We are hoping to release it next week. I'll let you know.

**Comment by adrianszymanski89** [comment]
Hi @chrissena 

We just released Handsontable 13.0 with the fix for Angular 16. Please, let me know if everything works fine after the update.

**Comment by AMBudnik** [comment]
Closed as released in v13.0.0.

 For a comprehensive list of all the changes, please visit the following link: [Handsontable Release Notes](https://handsontable.com/docs/javascript-data-grid/release-notes/#_13-0-0).
