### ISSUE TITLE
Can I render two editable lists on one page?

### ISSUE THREAD

**Issue by niuniuLYH** [handsontable/handsontable#10340]
### Description

Excuse me, can I render two editable tables lists on one page
Now I have rendered two editable tables on one page, but the editor portal created by the subsequent tables will overwrite those created by the previous table.
Is there currently a solution to this problem？
Expecting an answer. thank you very mouch.

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/c6rgz08x/

### Your environment
* React wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by AMBudnik** [comment]
I am closing this issue as there are no further questions or unresolved matters.

@niuniuLYH, if you require any further assistance, please don't hesitate to reach out to us at [support@handsontable.com](mailto:support@handsontable.com).
