### ISSUE TITLE
Unable to Copy/Paste to Object Cells

### ISSUE THREAD

**Issue by icle** [handsontable/handsontable#10351]
### Description
Hi,

When the cell type is set to "Object," copying and pasting the cell using shortcut keys does not work. Upon testing, it appears that the data is internally stored as a string. I attempted to use an action hook to convert the data type to "Object," but it seems to be unsuccessful as it only converts the string to "[object object]."

Furthermore, when I delete an Object type cell using the Delete key, an empty string is inserted, making it impossible to enter a new value from the custom editor.

To resolve these issues, I will need to implement various functions on my own.
Do you have any suggestions on how to address this?

Thank you.

### Your environment
* Vue wrapper version: 2.7.14
* Handsontable version: 12.3.3
* Browser name and version: Google Chrome
* Operating system: Windows

**Comment by adrianszymanski89** [comment]
Hi @icle 

This is actually how Handsontable is designed. Many features of Handsontable expect the cell value to be primitive, and they are not tested against object values. Sometimes they work thanks to the implicit `Object.prototype.toString` serialization, but this is not an officially supported scenario.

There was a discussion on this topic here: https://github.com/handsontable/handsontable/pull/9406.
