### ISSUE TITLE
I have created a custom editor called 'CustomAutocomplete' that extends the AutocompleteEditor in the Handsontable core file. However, I am unable to access objects  Apollo service or other services inside the CustomAutocomplete, which prevents me from using their defined functions.

### ISSUE THREAD

**Issue by deepgawade89** [handsontable/handsontable#10352]
### Description
I have created a custom editor called 'CustomAutocomplete' that extends the AutocompleteEditor in the Handsontable core file. However, I am unable to access objects Apollo service or other services inside the CustomAutocomplete, which prevents me from using their defined functions.

### Steps to reproduce

Here is my code
1. Created a service file, inside that I have configured data required for handsontable like colHeaders, colWidths, columns etc. For column for one field, I have set editor value as CustomAutocomplete
2. Separately, have created component name as CustomAutocomplete and written code as below

```
import Handsontable from 'handsontable';
import { Component, OnInit} from "@angular/core";
import { SuggestionsService} from "../../services/suggestions.service";
import { UtilsService } from "../../services/utils.service";
import { Apollo, gql } from "apollo-angular";

@Component({
  selector: "custom-editor",
  template:'',
  styleUrls: ["./custom-editor.component.scss"],
})

export class CustomEditorComponent extends Handsontable.editors.AutocompleteEditor implements OnInit{
  choices: any[] = [];
  htOptions: any;
  customOriginalValue: string | null = null;
  singleValue:any;
  choicesLength:any;
  utilsService: UtilsService = new UtilsService
  suggestionsService: SuggestionsService = new SuggestionsService;
  constructor(instance:Handsontable) {
    super(instance);
  }
  public override init(): void {
    super.init();
    this.query = '';
    this.choices = [];
  }
  public override createElements() {
    super.createElements();
  }
  public override prepare(td: number, row: number, col: string | number, prop: HTMLTableCellElement, value: any, cellProperties: any) {
    super.prepare(td, row, col, prop, value, cellProperties);
  }
  override queryChoices(query:string){
    super.queryChoices(this.query);
  }
  override updateChoicesList(choices: any) {
    super.updateChoicesList(choices);
  }
  override updateDropdownHeight() {
     super.unflipDropdown();
  }
  override finishEditing (restoreOriginalValue: any) {
     super.finishEditing();
  }
}
```
I have imported Apollo into my component class file, but when I try to pass it to the constructor and use this.apollo inside queryChoices() to execute a GraphQL query, the object is undefined.

### Demo

https://stackblitz.com/edit/handsontable-angular

### Your environment
* Angular version: 15.x
* Handsontable version: 12.x
* Wrapper version:
* Browser name and version:
* Operating system: Linux

**Comment by adrianszymanski89** [comment]
Hi @deepgawade89 

Thank you for contacting us. Can you please confirm if that's the correct link for the demo that you sent? It seems to be missing the code you mentioned above.

**Comment by deepgawade89** [comment]
Sorry, my bad. In my given code, what I am trying to do is:

I want to build a custom AutoCompleteEditor.
Inside that custom editor, I want to fetch data via GraphQL using Apollo, as per the given input.
So, for this, I have imported Apollo at the top of the code line, and inside the querychoice() method, I am trying to access the this.apollo object. However, I am getting 'undefined' in this component only. I have already used this in the same project in another component, and it is working.

**Comment by deepgawade89** [comment]
Please let me know if you want more info

**Comment by adrianszymanski89** [comment]
Hi @deepgawade89 

Thank you for a better explanation, but I asked about the link you attached: https://stackblitz.com/edit/handsontable-angular. Can you please update it so it will represent the issue?

**Comment by AMBudnik** [comment]
Hi @deepgawade89 do we have any news regarding this issue report?

**Comment by deepgawade89** [comment]
Hello adrianszymanski89,

Sorry for delay in reply.

Now I have created sample code here [inside](https://stackblitz.com/edit/angular-a87e7k?file=src%2Fapp%2Fcore%2Fcomponents%2Fbulktool%2Fbulktool.component.ts,src%2Fapp%2Fcore%2Fcomponents%2Fcustom-editor%2Fcustom-editor.component.ts) not runnable code now

What I am trying to do here is
1. Using HandsonTable, I want to display data fetching from Hasura. (This is done)
2. I'm using apollo to communicate with Hasura. (This is done)
3. For reference on how we are using Apollo, please check getData() function present in bulktool.component.ts file.
4. The data is displaying correctly in Handson Table.
5. Now, I want to use custom editor for one column of Handsontable. The editor will be AutocompleteEditor.

6. To achieve this, I have created separate custom-editor.component and extended it with Handsontable.editors.AutocompleteEditor.
7. In the handsontable.service.ts file, where I am configuring tableSettings object, I have added an editor property for column and also imported custom-editor component there.
8. I have overridden required methods inside custom-editor.component.ts file.

In queryChoices() method, I am receiving string that I type in handsontable. I am trying to access this.apollo there for append my query to fetch results.
However, when I try to console this.apollo inside this method, it returns undefined.

How I can access this.apollo inside that custom-edior.component.ts file

I will better If you give me the working example

**Comment by deepgawade89** [comment]
For now, our site is in development mode, so I am using 'non-commercial-and-evaluation'. 
If I buy the license key, will it resolve my issue? And for this issue I should buy license key is not fair right?
Your free features list is fulfilling my project requirement.

**Comment by deepgawade89** [comment]
Your assistance in addressing my query will play a crucial role in resolving the main obstacle I'm facing.

**Comment by adrianszymanski89** [comment]
Hi @adrianszymanski89 

What I mean is that the complexity of your example exceeds our pre-sales support abilities. What I can propose instead is to ask you to minimize the example to the point where the issue is still replicable. That also might help in general to locate the source of the problem.

**Comment by deepgawade89** [comment]
Thank you for replying me.

Here is a small description of the issue:

1. We have an Angular project where we have integrated Handsontable with Angular.
2. To fetch data from Hasura, we are using Apollo services (query, watchQuery, mutations).
3. While using Handsontable, I want to create my own custom AutoComplete suggestion editor. For this, I have created a new component and extended it with Handsontable.editors.AutocompleteEditor.
4. Now, inside the customEditorComponent.component.ts file, I am trying to access the Apollo service but unable to do so. My question is: How can I access it here?

For more details plz refer my code sample putted below in link 
https://stackblitz.com/edit/angular-un4mr6?file=src%2Fapp%2Fcore%2Fcomponents%2Fcustom-editor%2Fcustom-editor.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fcore%2Fservices%2Fcommon.service.ts,src%2Fapp%2Fcore%2Fcomponents%2Fbulktool%2Fbulktool.component.ts

Please let me know if I still need to upgrade to a higher plan for this. Will my query be resolved after upgrading? If my query is not resolved, will I be eligible for a refund?

**Comment by adrianszymanski89** [comment]
Hi @deepgawade89 

Thank you for minifying the example. That should be sufficient to find the issue. I'll look into it and get back to you after the weekend.

**Comment by deepgawade89** [comment]
Any updates

**Comment by adrianszymanski89** [comment]
Hi @deepgawade89 

Do you have any update on this issue?
