### ISSUE TITLE
Cannot see sorters and filters without click action

### ISSUE THREAD

**Issue by abhishek-sh111** [handsontable/handsontable#10354]
### Description

By default when the component is rendered, i am not able to see sorters. only if i click on column header,then its displaying for that column..

### Steps to reproduce

1.i have created a component and set columnsorting={{indicators=true}} and indicators=true..
2.
3.

### Demo
Please find the demo link:---- 

https://jsfiddle.net/doht6wqv/

**Comment by adrianszymanski89** [comment]
Hi @abhishek-sh111 

It's not a bug. This is how sorting indicators are designed. You have to sort the data first to see in which direction it is currently sorted.
