### ISSUE TITLE
请问handontable库支持自定义筛选条件吗

### ISSUE THREAD

**Issue by dxfstart521** [handsontable/handsontable#10363]
你好我们的业务场景是这样的，我们想继承默认的筛选条件，但默认的不满足我们的需求，我们再默认的筛选条件下再扩展一些筛选功能，请问这个需要怎么做呢？handontable库支持自定义筛选条件吗?求文档。谢谢大佬

**Comment by AMBudnik** [comment]
Hi @dxfstart521 

At the moment, Filters does not have an API to provide custom filtering conditions. The conditions that we support are 

![Zrzut ekranu 2023-05-12 o 14 15 42](https://github.com/handsontable/handsontable/assets/10757813/b82b94da-0669-4bce-8888-7b3a4953d382)


However, you can always create a custom dropdown menu option. Then you can base the logic on the `hiddenRows` plugin on given rows that do not match the condition you desired.

**Comment by dxfstart521** [comment]
thank you

**Comment by Linjunk** [comment]
@AMBudnik Can you provide the specific implementation code

**Comment by AMBudnik** [comment]
Hi @Linjunk 

As mentioned above, at the moment, the Filters plugin does not expose a public API for defining fully custom filtering conditions.

That said, Handsontable does provide a built in Filters plugin with a solid set of predefined conditions:

* Text types like contains, begins_with, ends_with, equal, not_equal, empty, not_empty
* Numeric types like gt, gte, lt, lte, equal, between
* Date types like before, after, between
* Filter by value

If you need more flexibility, one possible approach is to bypass the standard filtering UI and inject your own custom options directly into the dropdown menu. This allows you to keep the default filter options while adding custom filter items backed by your own callback logic.

With this setup, you can implement custom filtering behavior while still preserving the native Handsontable look and feel.

Hope this helps clarify the options available today. If you can share what specific filtering behavior you are trying to achieve, I would be happy to point you in the best possible direction.
