### ISSUE TITLE
Dropdown source to have Label and Value

### ISSUE THREAD

**Issue by SillasPoulsen** [handsontable/handsontable#10365]
I would like to be able to set source to an object with a value and a label like such in the dropdown source type:

source: [
{ value: “1”, label: “I” },
{ value: “2”, label: “II” },
{ value: “3”, label: “III” },
],

**Comment by AMBudnik** [comment]
Hi @SillasPoulsen 

I see that we just got the same issue on forum at https://forum.handsontable.com/t/set-column-type-dropdown-to-object/6902 which I just updated with a demo so I am closing this topic as a duplicate.

**Comment by SillasPoulsen** [comment]
Okay wow, so this has been a feature request since 2013?

**Comment by AMBudnik** [comment]
Yes, it may not look promising. But most of the Client us the renderer/editor/validator approach that I shared in the first comment. It also gives more flexibility than a predefined cell type. 
Nevertheless, I will contact everyone who shares their interest in the new cell type.
