### ISSUE TITLE
navigator

### ISSUE THREAD

**Issue by datavizcharts** [handsontable/handsontable#10367]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/c6rgz08x/

### Your environment
* React wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by adrianszymanski89** [comment]
Hi @datavizcharts 

Is this issue a duplicate of this one? https://github.com/handsontable/handsontable/issues/10368
