### ISSUE TITLE
Cell Reference

### ISSUE THREAD

**Issue by trongle** [handsontable/handsontable#10362]
Hi. I have a button and when I click on it the Handsontable will move/scroll to a range of cells. Is there a way to do that with Hansontable? 

### Demo
Please look at this gif to understand the function I'm talking about.
![cell reference function](https://i.ibb.co/v1rBpNp/cell-reference-function.gif)

This is the code I have so far.
https://codesandbox.io/s/amazing-estrela-4yz46k?file=/index.html

### Your environment
* Handsontable version: 12.3.3

**Comment by AMBudnik** [comment]
Hi @trongle 

You can use two methods

```js
hot.selectCell(row, col, row, col);
hot.scrollViewportTo(row, col);
```

the first selects the cells and moves the viewport
the second one allows to to move the viewport even further to centralize the selected area in the middle

Docs:
* `selectCell` - https://handsontable.com/docs/javascript-data-grid/api/core/#selectcell
* `scrollViewportTo` - https://handsontable.com/docs/javascript-data-grid/api/core/#scrollviewportto

**Comment by trongle** [comment]
Hi @AMBudnik. It works perfectly. Thanks for your help. :))
