### ISSUE TITLE
Docs: Do "afterselection" this hook have 2 same parameters?

### ISSUE THREAD

**Issue by zy-zero** [handsontable/handsontable#10361]
### Description

Do "afterselection" this hook have 2 same parameters? Or your document is wrong?

### Links

https://handsontable.com/docs/12.1/react-data-grid/api/hooks/#afterselection
![image](https://github.com/handsontable/handsontable/assets/23359848/ef94e2e2-0e2c-4acc-b25a-c80caaabaf75)

**Comment by adrianszymanski89** [comment]
Hi @zy-zero 

Thank you for reporting this. It's definitely a mistake in the description. There should be just one `preventScrolling` parameter described.

**Comment by adrianszymanski89** [comment]
Hi @zy-zero 

I just want to inform you, that we fixed this issue and the changes are implemented in our documentation.
