### ISSUE TITLE
[Bug]: Handsontable is not compatible with Google version 81.0.4044.138 after version 12.2.0

### ISSUE THREAD

**Issue by Chenchaoyang666** [handsontable/handsontable#10387]
### Describe the bug

Handsontable is not compatible with Google version 81.0.4044.138 after version 12.2.0，Table content cannot be displayed

### Video/Screenshots

NA

### Provide a link to the demo with the bug reproduction

https://handsontable.com/docs/javascript-data-grid/binding-to-data/

### Handsontable version

12.4.0

### Framework version

vue 2.0

### Your environment

Chrome

**Comment by AMBudnik** [comment]
Hi @Chenchaoyang666 

By Google version do you mean the Chrome web browser? If so, that might be true as we support only the latest version (v113) and one older version, as written in the documentation


> We carefully test our code on the two latest versions of every modern browser, on both mobile and desktop devices

Source: https://handsontable.com/docs/javascript-data-grid/supported-browsers/
