### ISSUE TITLE
Multiline text and merge - not all lines visible

### ISSUE THREAD

**Issue by OlgaIOn** [handsontable/handsontable#10383]
### Description
If a table contains long texts within the merged cells, the table will not be fully displayed.

The table in the example has 20 rows, only 3 are visible when loading. If you click on the table, more rows are displayed. You have to click twice until the table is fully displayed.

### Demo
https://jsfiddle.net/pmzcktLg/1/

### Environment
* Handsontable version: 12.3.3
* Browser name and version: Mozilla Firefox
* Operating system: Linux Mint

**Comment by AMBudnik** [comment]
Hi @OlgaIOn 

Thank you for reporting the issue.

It seems that this issue https://github.com/handsontable/handsontable/issues/2667 causes the effect we can see in the demo.

I will update you as soon as we fix it.

**Comment by AMBudnik** [comment]
Hi @OlgaIOn 

Our developer checked that issue and it seems that it only requires the `autoRowSize` plugin to be enabled https://jsfiddle.net/tkLxfrs0/
