### ISSUE TITLE
Copying cells programmatically with all column headers does not work

### ISSUE THREAD

**Issue by rvaandrager** [handsontable/handsontable#10380]
### Description
Programmatically copying cells with headers does not work when all headers should be copied. This is applicable in a Handsontable instance with NestedColumns. 

We can use `copyPastePlugin.copy` with an option whether to include headers. See the [documentation](https://handsontable.com/docs/javascript-data-grid/basic-clipboard/)
- When the option `with-column-headers` is used, the nearest headers are copied (not all). This is intended behaviour, this works.
- When the option `with-all-column-headers` is used, no headers are copied. This does not work as intended. Copying a selection of cells this way, all headers should be included.

### Steps to reproduce

1. Create a Handsontable grid with nested columns, see my jsfiddle linked below
2. Select some cells
3. Click on the button "Copy cell with headers". This triggers `copyPastePlugin.copy('with-column-headers');` and paste this in Excel. The selected cells will be copied with the nearest headers.
4. Click on the button "Copy cell with all headers". This triggers `copyPastePlugin.copy('with-all-column-headers');` and paste this in Excel. Only the selected cells are copied, the headers are not copied.

### Demo

https://jsfiddle.net/Lhgu6o9r/

### Your environment
* Handsontable version: 12.3
* Browser name and version: Firefox 113
* Operating system: MacOS

**Comment by adrianszymanski89** [comment]
Hi @rvaandrager 

Thank you for reporting this. I tested it following your steps, and I was able to reproduce this issue.

**Comment by rvaandrager** [comment]
Hi @adrianszymanski89,

That is indeed great news! I adapted this in my project, it works like a charm. Thank you!

**Comment by AMBudnik** [comment]
Hi @rvaandrager 

Just a small update here - we just released a new version - Hadsontable v13.1.0 where we changed the info in the documentation.

Again, thank you for reporting the issue.
