### ISSUE TITLE
[Bug]: button in a cell can't click when viewport just only show one row.

### ISSUE THREAD

**Issue by zy-zero** [handsontable/handsontable#10394]
### Describe the bug

Hi good day @jansiegel  @AMBudnik 
Here have a issue with custom render cell.
When  I render a button in first cell, I can't trigger the button event if only one row show in viewport. Do this is a bug? How can I trigger?

following is my code.
```
import Handsontable from "handsontable";
import ReactDOM from "react-dom";
import { HotTable } from "@handsontable/react";
import { registerAllModules } from "handsontable/registry";
import "handsontable/dist/handsontable.full.min.css";
import { useEffect, useRef, useState } from "react";

registerAllModules();

const actionRender = (
  instance: any,
  td: any,
  row: any,
  col: any,
  prop: any,
  value: any,
  cellProperties: any
) => {
  td.className = td.className + " action-columns";
  td.innerHTML = "";
  const divDom = document.createElement("div");

  divDom.style.width = "100%";
  divDom.style.height = "100%";
  divDom.style.display = "flex";
  divDom.style.justifyContent = "center";
  divDom.style.alignItems = "center";
  const buttonDom = document.createElement("button");
  buttonDom.className = "action-col-add-links ";
  buttonDom.innerHTML =
    'btn click';
  console.log("actionRender", row, col);
  buttonDom.addEventListener("click", (e) => {
    
    console.log("buttonDom click", row, col);
  });
  divDom.appendChild(buttonDom);
  // td.replaceChild(divDom);
  td.appendChild(divDom);

  return td;
};

const createSpreadsheetData = () => {
  const rows = [];
  for (let r = 0; r < 100; r += 1) {
    const row = [];
    for (let c = 0; c < 20; c += 1) {
      row.push(
        r +
          "-:-" +
          c +
          "button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row. button in a cell can't click when viewport just only show one row."
      );
    }
    rows.push(row);
  }
  return rows;
};

const HtTable = () => {
  const tableRef = useRef<HotTable>(null);
  const [hotSetting, setHotSetting] = useState({
    height: 320,
    colWidths: 120,
    rowHeaders: true,
    colHeaders: true,
    contextMenu: true,
    cells: (row: number, column: number) => {
      return getCellProperties(row, column);
    },
  });

  const getCellProperties = (row: number, column: number) => {
    let className = "";

    className = className.replace(/read-only/gi, "");

    if (column === 0) {
      const cellObj = {
        readOnly: true,
        className: className,
        renderer: actionRender,
      };
      return cellObj;
    }

    return {
      className: className,
    };
  };

  useEffect(() => {
    if (tableRef.current) {
      const table = tableRef.current.hotInstance;
      const data = createSpreadsheetData(); //Handsontable.helper.createSpreadsheetData(100, 50);
      if (table) {
        table.updateSettings({
          data: data,
        });
      }
    }
  }, [tableRef.current]);

  const [merge, setMerge] = useState(false);

  const handleMergeChange = () => {
    setMerge(!merge);
  };

  useEffect(() => {
    if (tableRef.current) {
      const table = tableRef.current.hotInstance;
      if (table) {
        if (merge) {
          table.updateSettings({
            mergeCells: [
              { row: 1, col: 1, rowspan: 3, colspan: 3 },
              { row: 3, col: 4, rowspan: 2, colspan: 2 },
              { row: 5, col: 6, rowspan: 3, colspan: 3 },
            ],
          });
        } else {
          table.updateSettings({
            mergeCells: [],
          });
        }
      }
    }
  }, [merge]);

  return (
    <div>
      {/* <button className="merge-cell" type="button" onClick={handleMergeChange}>
        Merge {merge.toString()}
      </button> */}
      <HotTable ref={tableRef} settings={hotSetting} />
    </div>
  );
};

export default HtTable;
```

### Video/Screenshots

![企业微信截图_16857626017662](https://github.com/handsontable/handsontable/assets/23359848/e75ee6b0-1c60-471f-9f8d-1aec8287ab65)

### Handsontable version

12.3.3

### Framework version

react 18

### Your environment

Windows 10 home

**Comment by adrianszymanski89** [comment]
Hi @zy-zero 

I tested your code, and besides the fact that the button isn't visible in the viewport until we scroll down a bit I didn't notice any issues. What is your expected result here?

**Comment by zy-zero** [comment]
> 

Hi @adrianszymanski89 
It should be click without scroll, right?
If the table only 200px height, but the row have 250px, I can't click the button in cell. when I click the button it will trigger cell render function, not the button click listener.

**Comment by adrianszymanski89** [comment]
@zy-zero 

The button is centered in the cell, so if the viewport is shorter than the cell's height, it won't be visible until you scroll down the table.

**Comment by zy-zero** [comment]
> @zy-zero
> 
> The button is centered in the cell, so if the viewport is shorter than the cell's height, it won't be visible until you scroll down the table.

Hi @adrianszymanski89 
But in my case(the picture) you can see and click that, it just can't trigger click event.

**Comment by zy-zero** [comment]
> @zy-zero
> 
> The button is centered in the cell, so if the viewport is shorter than the cell's height, it won't be visible until you scroll down the table.
Hi, @adrianszymanski89 
Sorry, may be the case code text is too long, you can make it short and test agian.

https://codesandbox.io/s/exciting-cdn-1sxmts?file=/src/HotTable.js

**Comment by zy-zero** [comment]
> @zy-zero
> 
> The button is centered in the cell, so if the viewport is shorter than the cell's height, it won't be visible until you scroll down the table.

Or you can use this case: https://codesandbox.io/s/exciting-cdn-1sxmts?file=/src/HotTable.js

**Comment by AMBudnik** [comment]
Hi @zy-zero 

That is a known issue that the event is stolen by the cell. But I can recommend the approach mentioned here https://forum.handsontable.com/t/html-content-loses-focus-in-version-1-15-1/1882 to use `beforeOnCellMouseDown` hook.

Would that meet your project requirements?

**Comment by zy-zero** [comment]
> Hi @zy-zero
> 
> That is a known issue that the event is stolen by the cell. But I can recommend the approach mentioned here https://forum.handsontable.com/t/html-content-loses-focus-in-version-1-15-1/1882 to use `beforeOnCellMouseDown` hook.
> 
> Would that meet your project requirements?

Hi @AMBudnik  
Thanks for your answer, I will try use beforeOnCellMouseDown hook. Thanks again!

**Comment by AMBudnik** [comment]
Hi @zy-zero 

I need to close the issue as there's no update for 2 weeks. However, if the `beforeOnCellMouseDown` does not work for you we can discuss details about other options on email at support@handsontable.com
