### ISSUE TITLE
[Bug]: Cell meta dropped on custom rendered cells

### ISSUE THREAD

**Issue by danelikethedog** [handsontable/handsontable#10390]
### Describe the bug

Cells with custom renderer (`hot-renderer`) seem to drop any changes to the cellMeta. As in, if I use `.setCellMeta` to add a class to a cell, if that cell then uses a custom renderer, the cell meta changes are not persisted and seemingly dropped. Is this by design or is this a bug?

### Video/Screenshots

I'm using a css module to apply a background to rows with edited data which haven't been submitted to a DB (see class `MWkvUwyPFNDKi8q_aLXK` which is added to the cells). Here is what I see when I use the `.setCellMeta()` function to apply to all columns in a row. The two which are still white have custom render components.

<img width="1301" alt="image" src="https://github.com/handsontable/handsontable/assets/7367603/b9478693-0c5f-4045-be66-54fced9796ae">

### Handsontable version

12.3.3

### Framework version

Next.JS / Node

### Your environment

Arc on Mac

**Comment by adrianszymanski89** [comment]
Hi @danelikethedog 

I got the update here. It is a desired behavior as the `setCellMeta()` hook works only if we fire the `render()` method after it, and in this case `render()` method runs the custom renderer, which overrides the `setCellMeta()` changes. 

The other option than the one I proposed would be to add conditional statements to the custom renderer to check if the wanted cell doesn't contain the class name of the new color.
