### ISSUE TITLE
[Bug]: wrong startIndex in beforeCreateRow when click on Insert row below

### ISSUE THREAD

**Issue by olosegres** [handsontable/handsontable#10391]
### Describe the bug

Bug is present in 12.3.3 and 12.4.0 but 12.1.3 does not include this bug.

STR:
1. Right-mouse click on some row and choose “Insert row below”.
2. Check new row placement.

ER:
It should be created below previous row.

AR:
New row appears above previous row.

### Video/Screenshots

https://actonic-my.sharepoint.com/:v:/g/personal/sergei_solomatkin_actonic_de/EVAaUDreqnlJjXOmuBH6u2QBFNqQg_ceODeyn65C-dEO3A?e=BfEXrv

### Handsontable version

12.4.0

### Your environment

Chrome

**Comment by olosegres** [comment]
Yes, to be more precise, `beforeCreateRow` method does not work correctly.

Please add this to your example of code:
```
  beforeCreateRow: (firstIndex, amount) => console.log('beforeCreateRow', { firstIndex, amount }), 
```

Then select first row and try to Add row below,
then select first row again and click on Add row above.

In both cases `firstIndex` will equal `0`, but using 12.3.3 and earlier, in case with 'Add row below' `firstIndex` will equal `1`;

**Comment by adrianszymanski89** [comment]
Hi @olosegres 

Thank you for more details. Now everything is clear. It's a desired behavior, as the previous approach was a limitation and sometimes results in unexpected results. It was fixed in version 12.2.0 with this PR: https://github.com/handsontable/handsontable/pull/9955 

You can find all the details there.

**Comment by olosegres** [comment]
If it desired behavior, how to differentiate between adding row above and below? Is where any direction marker of where new row will appear?

**Comment by adrianszymanski89** [comment]
Let me clarify. The behavior you showed in the recording isn't correct and doesn't take place in any example I tried. Using the `Insert row above` or `Insert row below` options should always give the expected results. 

If you can recreate that issue in any sandbox, then we will be able to see where the problem might be.

**Comment by olosegres** [comment]
it seems as if you are not reading my posts in full.

Неre is example with reproduction of the problem: https://jsfiddle.net/olosegres/hxc8nfd9/1/

When first row is selected, click on
Insert row above produces `firstIndex: 0` in the console,
Insert row below produces `firstIndex: 0` in the console.

if you claim that this is not a bug, how now to understand the direction (or real position of inserted row) inside the `beforeCreateRow` handler?

**Comment by olosegres** [comment]
I do not know where exactly, but one of this PR's introduced a bug in `beforeCreateRow`. 
I still think you don't fully understand the problem I'm describing.

Because new logic violates common sense and examples in test case of #10136 partly incorrect.

It seems that author of #10136 pull request put a different meaning into the function arguments of `beforeCreateRow` (different from origin, described in documentation https://handsontable.com/docs/javascript-data-grid/api/hooks/#beforecreaterow)

His demo example should look like
```
const hot = new Handsontable(document.querySelector('#example'), {
  data: Handsontable.helper.createSpreadsheetData(4, 4),
  rowHeaders: true,
  colHeaders: true,
  contextMenu: true,
  beforeCreateRow: function(index, amount, source) {
    this.setCellMeta(index + amout, 0, 'className', 'green'); // index here should represent future index of new row
  },
  afterCreateRow: function(index, amount, source) {
    for (let i = index; i < index + amount; i++) {
      this.setCellMeta(i, 0, 'className', 'red');
    }
  }
});
```

**Comment by adrianszymanski89** [comment]
Hi @olosegres 

I get the feedback from the development team. They confirmed that the behavior of the hook was correct. The `index` parameter means the visual index of the row.

**Comment by olosegres** [comment]
So, it means that current behavior should be fixed, right?

**Comment by olosegres** [comment]
Our problem is not solved. We cannot update to newer versions of handsontable because one of the function became broken.

How to know row index that is creating inside `beforeCreateRow` hook?
We need to know future row index to prepare cell meta before it is created.

**Comment by olosegres** [comment]
please delve deeper into the problem, all the answers that I received seem to ignore the essence of what I describe

**Comment by AMBudnik** [comment]
Hi @olosegres 

As Adrian said, the behavior of the `beforeCreateRow` was changed to show the results before the action occurs, so now we have [different indexes](https://jsfiddle.net/yaL8x9sd/1/) for `beforeCreateRow` and `afterCreateRow`. We mainly did that to fix cell metadata use and validation. However, I agree that the documentation does not clearly specify what we should expect. I will raise a separate issue for that.

Now, I can imagine that this might be an issue if you set your logic based on the old rules. Could you tell us a little bit more about your use case? I am sure that we will be able to find a way for you to update and meet the previous requirements.

**Comment by olosegres** [comment]
> Sorry, but it seems as if you are not reading my posts in full.
> 
> Неre is example with reproduction of the problem: https://jsfiddle.net/olosegres/hxc8nfd9/1/
> 
> When first row is selected, click on 'Insert row below', it produces `firstIndex: 0` in the console, then click on 'Insert row above', it produces `firstIndex: 0` in the console.
> 
> Actions are different, but data in arguments in beforeCreateRow the same.
> 
> if you claim that this is not a bug, how now to understand the direction (or real position of inserted row) inside the `beforeCreateRow` handler?

I've described how to reproduce problem in this post.

We need to update meta data before new cell will be rendered (insert new row to the `cellMeta` array).
And we cannot do it without knowing the direction where new row will be created.

Without updating our `cellMeta` before render of new row - table renders incorrectly, because `cellMeta` became outdated, compared to `data`

**Comment by adrianszymanski89** [comment]
Hi @olosegres 

For determining the direction of the newly created row, you can use the `source` parameter in the `beforeCreateRow` hook, like this: https://jsfiddle.net/handsoncode/1tg0muwb/

Would that be helpful in your case?

**Comment by olosegres** [comment]
@adrianszymanski89 yes, that's suitable, thanks

**Comment by adrianszymanski89** [comment]
Hi @olosegres 

Thank you for the update. I'm glad that it worked for you.
