### ISSUE TITLE
[Bug]: unfreezeColumns won't restore fixed column to previous position

### ISSUE THREAD

**Issue by chao** [handsontable/handsontable#10400]
### Describe the bug

According to the official document, calling the unfreezeColumn method of the ManualColumnFreeze plugin can unfreeze the frozen column and restore it to its original position. After testing, it was found that unfreezeColumn can unfreeze the frozen columns, but cannot restore them to their original position. For example, in the official example "[User-triggered freeze](https://handsontable.com/docs/javascript-data-grid/column-freezing/)" given for testing the unfreezeColumn method, we first unfreeze columns A and B, then freeze column C, and then unfreeze column C again. It was found that after column C was unfrozen, its contents were still in the first column instead of returning to the third column where it originally was.

### Handsontable version

12.3.3

### Your environment

Chrome, Edge

**Comment by AMBudnik** [comment]
Hi @chao 

On the same page it is said that 

> Mind that a frozen column won't go back to the original position after you unfreeze it.

So we won't get the following order

<img width="722" alt="Zrzut ekranu 2023-06-9 o 09 54 37" src="https://github.com/handsontable/handsontable/assets/10757813/e20cf27f-34bd-4f39-9a67-d47eee1ce61f">

when we unfreeze the columns, like `A` and then `B`, you'd need to unfreeze `B` first and then `A`, and then when you freeze `C` is jumps on the 1st position and we get

<img width="725" alt="Zrzut ekranu 2023-06-9 o 09 56 39" src="https://github.com/handsontable/handsontable/assets/10757813/a7245cf4-1bce-4348-836c-a928e1a6785b">

Did I miss anything?
