### ISSUE TITLE
broken editing with backbone.js and validators

### ISSUE THREAD

**Issue by lipt0n** [handsontable/handsontable#1041]
Hi,
Im trying to use backbone with validators, but it's always highlight wrong cell. my example: http://jsfiddle.net/ghg8H/2/

**Comment by budnix** [comment]
Can you confirm this bug? I tried to reproduce bug with the newest version of Handsontable (0.15.0-beta2) but it seems to be ok - http://jsfiddle.net/yttzddfn/.

**Comment by budnix** [comment]
Issue will stay closed till an author's reply.
