### ISSUE TITLE
cant edit field or fire validator when using backbone

### ISSUE THREAD

**Issue by lipt0n** [handsontable/handsontable#1042]
hi, I'm using handsontable with backbone.js , when I have at least two backbone fields defined in handsontable with validator I cant leave that field. focus stays forever. please help. my code: http://jsfiddle.net/ghg8H/1/

**Comment by AMBudnik** [comment]
Tried in on 0.14.1 on Chrome 41. Please update andlet us know if it still focus the same.

**Comment by AMBudnik** [comment]
I assume that it works fine. If you would still face this issue, please reply.
