### ISSUE TITLE
[Bug]: how can select type cell show option label at  drop down menu filter

### ISSUE THREAD

**Issue by wiexin** [handsontable/handsontable#10426]
### Describe the bug

whene a column cell type is  select, while filtering , filter by value shows keys instead of value. is it possible to change shows instead of value by key.like this topic [https://forum.handsontable.com/t/filtering-key-value-drop-down-menu/6612](url)

### Video/Screenshots

![image](https://github.com/handsontable/handsontable/assets/18095039/5525e7c2-ef03-418c-b787-2eca4d3052f2)

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/hello_jsfiddle/z74mrhwo/16/

### Handsontable version

12.1.2

### Your environment

chrome

**Comment by AMBudnik** [comment]
Hi @wiexin 

At the moment the Filters API does not include an option to alter what is shown in the filter by value list. Please follow this thread https://github.com/handsontable/handsontable/discussions/7699 for updates.
