### ISSUE TITLE
[Bug]: type of CellChange is incorrect

### ISSUE THREAD

**Issue by akeeman** [handsontable/handsontable#10432]
### Describe the bug

The `data` field of the `CellChange` type also accepts `ColumnDataGetterSetterFunction`.

### Handsontable version

13.0.0

### Your environment

Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15

**Comment by AMBudnik** [comment]
Thank you for sharing @akeeman 

I've updated the status of your PR and will inform you after merge.

**Comment by AMBudnik** [comment]
Hi @akeeman 

We've just merged the PR.

I will share the next update after the new Handsontable version publication.

**Comment by AMBudnik** [comment]
Hi @akeeman 

I just wanted to let you know that we've just published Handsontable v13.1.0 where the missing definition is added.
