### ISSUE TITLE
Sorting/filtering does not work correctly when row parent-child (version 13)

### ISSUE THREAD

**Issue by conschtek** [handsontable/handsontable#10439]
In previous versions there was an exact statement at the beginning that "The rows sorting and column filter features don't work with the parent-child row structure".
With the new version (version 13.0) this warning is not there anymore, so I tried it out. The row parent-child does not block anymore these features, but sorting and filtering is not working correctly, please see video.

Is there any chance that this is going to be improved in the near future?

https://github.com/handsontable/handsontable/assets/117377149/ed3fce88-85e5-4703-a198-a4df16b6741d

### Handsontable version

13.0

### Your environment

Browser: Chrome

**Comment by conschtek** [comment]
Hi @AMBudnik 

Thank you for your quick reply. I assume this also means, that it's not planned that these functions are going to work together in the near feature?

**Comment by AMBudnik** [comment]
Sorry, my bad, @conschtek !

I forgot that we've made some structural changes to the website.

Know any limitations are on the bottom of the page, and the same goes for `nestedRows`.

![Zrzut ekranu 2023-07-11 o 15 26 07](https://github.com/handsontable/handsontable/assets/10757813/754c1697-6829-428c-b9b3-479a24e48853)

And, yes, we do not plan to alter this behavior in Q3-2023.

**Comment by conschtek** [comment]
Thank you again!
