### ISSUE TITLE
[Bug]: TypeScript compiler can not recognize index.d.ts due to wrong package.json

### ISSUE THREAD

**Issue by youhogeon** [handsontable/handsontable#10448]
### Describe the bug

# Overview
There Is something wrong in `package.json`

It does not follow the guidelines in TypeScript documentation.
(https://www.typescriptlang.org/docs/handbook/esm-node.html)

> It’s important to note that the CommonJS entrypoint and the ES module entrypoint each needs its own declaration file, even if the contents are the same between them. Every declaration file is interpreted either as a CommonJS module or as an ES module, based on its file extension and the "type" field of the package.json, and this detected module kind must match the module kind that Node will detect for the corresponding JavaScript file for type checking to be correct. Attempting to use a single .d.ts file to type both an ES module entrypoint and a CommonJS entrypoint will cause TypeScript to think only one of those entrypoints exists, causing compiler errors for users of the package.

It seems that the TypeScript compiler cannot properly load the `index.d.ts` file because there is no `types` option in the `exports` section of package.json.

# Situation
1. Starting a new project with `vite+react+ts+swc` following vite documentation.

`npm create vite@latest -- --template react-swc-ts`

2. Install handsontable libraries.

`npm install --save handsontable @handsontable/react`

3. Import handsontable in the `App.tsx` file. Then two typescript errors occur.
```
// App.tsx
import { HotTable } from '@handsontable/react';
import { registerAllModules } from 'handsontable/registry';
```

```
src/App.tsx:6:26 - error TS7016: Could not find a declaration file for module '@handsontable/react'. '.../node_modules/@handsontable/react/es/react-handsontable.mjs' implicitly has an 'any' type.
  There are types at '.../node_modules/@handsontable/react/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@handsontable/react' library may need to update its package.json or typings.


src/App.tsx:7:36 - error TS7016: Could not find a declaration file for module 'handsontable/registry'. '.../node_modules/handsontable/registry.mjs' implicitly has an 'any' type.
  There are types at '.../node_modules/handsontable/registry.d.ts', but this result could not be resolved when respecting package.json "exports". The 'handsontable' library may need to update its package.json or typings.
```

# "Temporary" Solution while waiting for a patch
Remove the `exports` section in `package.json` so that typescript compiler can recognize the `types` option in root of `package.json`.

### Handsontable version

13.0.0

### Your environment

TS 5.0.2 / Nodejs 18 or 20

**Comment by adrianszymanski89** [comment]
Hi @youhogeon 

Thank you for reporting this. I think this issue is connected strictly with this one. However, we have a different workaround proposed there: https://github.com/handsontable/handsontable/discussions/10415

Can you please confirm if it's the same issue as yours? Then we can merge them into one. Also, we have already reported it internally for further investigation.

**Comment by youhogeon** [comment]
I checked all the issues, but I couldn't check the Discussion. You're right it's the same problem. thank you
