### ISSUE TITLE
[Bug]: ChangeSource is missing the type "updateData"

### ISSUE THREAD

**Issue by myessail** [handsontable/handsontable#10455]
### Describe the bug

When typing the `source` of my `afterChange` method with `Handsontable.ChangeSource`, it does not contain the string `updateData` as an option. However, when I change the data in my table and pass it back to the parent component, I get this string as an event which I need to ignore. When looking at `common.d.ts` it looks like that string is not included.

### Handsontable version

13.0.0

### Your environment

Firefox, Mac

**Comment by myessail** [comment]
hi @adrianszymanski89 any updates on this?

**Comment by adrianszymanski89** [comment]
Hi @myessail 

Yes, I have an update. This issue is already fixed in this PR: https://github.com/handsontable/handsontable/pull/10488, and the fix will be available in the next release of Handsontable.
