### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BoXueJi** [handsontable/handsontable#10460]
### Describe the bug

有人使用时会出现表头除了固定列以外的列消失，和固定行在表格下滚时除了固定列以外的列消失，其他内容正常。一旦出现这种情况，所有表格展示都有此问题，换一个浏览器后就显示正常了，而出现过问题的浏览器一直异常。

### Handsontable version

13.0.0

### Your environment

谷歌浏览器，win10系统

**Comment by adrianszymanski89** [comment]
Hi @BoXueJi 

Please describe the issue you are experiencing in English, and provide the steps to reproduce it.

**Comment by BoXueJi** [comment]
![screenshot](https://github.com/handsontable/handsontable/assets/44436600/a4f01ee8-a004-410a-be69-0fa1fc2ec197)Sorry, this is a problem that my co-worker stumbled across and I didn't find a way to reproduce it. Once this problem occurs, he will have this problem when viewing all forms, unless the browser is changed.

**Comment by adrianszymanski89** [comment]
Hi @BoXueJi 

I understand, but I still need to know your table's configuration and the steps to reproduce the issue. Otherwise, there's not much I can do to help.

**Comment by BoXueJi** [comment]
Open the win10 system settings, if you set the size of items such as changing text and applications to 150%, fixedRowsTop will fail.

**Comment by AMBudnik** [comment]
Hi @BoXueJi 

Thank you for providing additional details. 

I see that running the 150% browser zoom on `fixedRowsTop` does not misalign the table and does not produce any other artifacts. We have fixed an issue related to `fixedRowsBottom` recently, but I do not see a corresponding issue related to `fixedRowsTop` on our list of zoom-related issues at https://github.com/handsontable/handsontable/issues/7527

Please give us a few days more to test it.

**Comment by BoXueJi** [comment]
Ok, please reply me as soon as possible.

**Comment by AMBudnik** [comment]
Hi @BoXueJi 

Today I had a chance to test the demo with my colleague who's using a native Windows system and the

* browser scroll makes the difference
* system scale does not make a difference

But the only bug that we get is this (the headers and scrolls are off, creating a gap)


![Zrzut ekranu 2023-08-16 o 10 55 32](https://github.com/handsontable/handsontable/assets/10757813/5092bcfe-c414-4cb0-bc8d-6846ae93ccfc)

That is not the same case as you reported. This is the same case I mentioned that I have with the browser zoom on macOS.

In this case, I think that I would need to ask for a demo where the issue is replicable.

**Comment by BoXueJi** [comment]
[demo](https://github.com/BoXueJi/hottable)
[Element Plus](https://element-plus.org/en-US/)
I use it with Element Plus, I don't know if the bug is related to this.

**Comment by AMBudnik** [comment]
Thank you for sharing the demo @BoXueJi 

I was able to replicate the issue for 125% and 150% browser zoom on Chrome 116/macOS Ventura while scrolling the data down two header from both tables are gone.

![Zrzut ekranu 2023-08-18 o 09 23 58](https://github.com/handsontable/handsontable/assets/10757813/5e4fdeeb-b0b8-44c6-b9da-2bfb96fc4c38)

As I can see you use `fixedColumnsLeft: 2` so the columns that are staying untouched are those which are fixed.

Now comparing our demo with fixed column https://jsfiddle.net/q349ho12/ and your example it seems that the issue lays in the CSS settings. It might be related to Element Plus adding/replacing some settings. I recommend checking of there are any classes that overwrite the Handsontable's `ht_clone_top` class.


![Zrzut ekranu 2023-08-18 o 09 42 27](https://github.com/handsontable/handsontable/assets/10757813/c62f0751-ebb7-4ac9-8eee-0176fc84e281)
![Zrzut ekranu 2023-08-18 o 09 41 55](https://github.com/handsontable/handsontable/assets/10757813/c93964a8-f1f9-4e8e-a71d-3958e1fd4587)

**Comment by BoXueJi** [comment]
According to your suggestion, I found out that the problem was related to my modifying the height of Handsontable's wtHolder. Thanks for your patience and answers as I'm not very familiar with Handsontable causing this issue.
