### ISSUE TITLE
Handsontable data filtering

### ISSUE THREAD

**Issue by Raj2011** [handsontable/handsontable#1046]
We looking to filter the data from handsontable, but it filters data only from the current visible rows. So say if i have 100 rows and because of table height it only display 10 rows and have a vertical scroll bar. If i try to filter it it's only filtering it from present 10 rows.

**Comment by AMBudnik** [comment]
This issue has to be closed, because it doesn't provide a demo. In case you still have the same (or other) issue, please write us back.
