### ISSUE TITLE
[Bug]: 自定义的编辑项，如果在页面进行滚动的时候，操作框发生偏移

### ISSUE THREAD

**Issue by XinYueXiao** [handsontable/handsontable#10465]
### Describe the bug

页面的部分区域使用时，操作框偏移
手动添加overflow:auto
![image](https://github.com/handsontable/handsontable/assets/31272499/a06a4fa5-27d3-4dc5-9242-dfd6049f0277)

我该怎么获取编辑框距离左侧的位置？
如果是页面部分区域的话使用window.pageXOffse获取的是固定值，就会随页面滚动而移动

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/42hx8cpw/60/

### Handsontable version

13

### Your environment

chrome

**Comment by adrianszymanski89** [comment]
Hi @XinYueXiao 

Please describe your issue in English, as we can provide support only in that language.

**Comment by XinYueXiao** [comment]
# Describe the bug
When using the page part of the page,when the operating box is shifted manually, the Overflow: Auto page is used,
 and the operating box is manually adding Overflow: Auto
  
![image](https://github.com/handsontable/handsontable/assets/31272499/1b9b72f6-3d83-43de-be5c-50b060fe4799)

 How do I get the position of the editing box distance from the left side?
If it is part of the page part of the area, use Window.pagexoffse to get a fixed value, and it will move with the page rolling
# Provide a link to the demo with the bug reproduction
https://jsfiddle.net/42hx8cpw/60/

**Comment by AMBudnik** [comment]
Hi @XinYueXiao 

In the *Create <select> input and attaching it to DOM* paragraph in the cell editor guide at https://handsontable.com/docs/javascript-data-grid/cell-editor/ we discuss how to create and style the custom editor.

If you would need more help than that, please contact us support@handsontable.com
