### ISSUE TITLE
[Bug]: Column headers not being rendered

### ISSUE THREAD

**Issue by pretzL** [handsontable/handsontable#10474]
### Describe the bug

In my eyes this bug is two part, but I can create separate issues for them if you would like.

I'm experiencing some weird behavior with column headers and table rendering.
If I supply the table with an array of columns of say 10 items and I supply it with an array of arrays for the table data which at most include say 8 items in one array, the table will only render 8 columns. However, there is also a second part to this being that the table will only render as many columns as the first array in the dataset.

For example:
 ```js
 let columns = ["", "Tesla", "Volvo", "Toyota", "Ford", "Hyundai", "Honda", "Nissan", "Kia", "Chevrolet"];
let rows = [
    ["2019", 10, 11, 12, 13, "", "", "", "", ""],
    ["2020", 20, 11, 14, 13, ""],
    ["2021", 30, 15, 12, 13, ""],
    ["2021", 30, 0, 0, 0, 15, 19, 22, 23],
];
    
table = new Handsontable(container, {
        licenseKey: "non-commercial-and-evaluation",
        rowHeaders: true,
        colHeaders: columns,
        data: rows,
        height: "auto",
        });
 ```
Result:
    
![image](https://github.com/handsontable/handsontable/assets/30121693/c37cde09-4cfb-4862-bc93-ba6bb054f72f)

As you can see, this renders every column header as intended.
Now, remove some items from the rows array:
```js
let columns = ["", "Tesla", "Volvo", "Toyota", "Ford", "Hyundai", "Honda", "Nissan", "Kia", "Chevrolet"];
let rows = [
    ["2019", 10, 11, 12, 13, ""],
    ["2020", 20, 11, 14, 13, ""],
    ["2021", 30, 15, 12, 13, ""],
    ["2021", 30, 0, 0, 0, 15, 19, 22, 23],
];
```
Result:
    
![image](https://github.com/handsontable/handsontable/assets/30121693/e16b33aa-5160-4d97-a1ce-c38b041504d5)

Notice in the result above, the last array contains 9 items, but only 6 columns are being rendered (not counting the rowHeader).

Is this intended behavior? Is there some parameter I'm missing which handles this? Or is it expected that the developer ensures that the data does not include missing values?

### Handsontable version

13.0.0

### Framework version

Svelte 3.54

### Your environment

Chrome, Win11

**Comment by AMBudnik** [comment]
Hi @pretzL 

As mentioned in the documentation

> When using object data binding, Handsontable needs to know what data structure to create when adding a new row. If your data source contains at least one row, Handsontable will figure out the data structure based on the first row.


so we treat the first row as a sample. You can add an empty string or a `null` to the first row if there's actually no data, but the number of elements in the first array determines the size of the table. If, however, you do not want to add all those empty strings you can use `columns` to specify how many of them should be in the table. Here's an example https://jsfiddle.net/3gxy86m1/

**Comment by pretzL** [comment]
> Hi @pretzL
> 
> As mentioned in the documentation
> 
> > When using object data binding, Handsontable needs to know what data structure to create when adding a new row. If your data source contains at least one row, Handsontable will figure out the data structure based on the first row.
> 
> so we treat the first row as a sample. You can add an empty string or a `null` to the first row if there's actually no data, but the number of elements in the first array determines the size of the table. If, however, you do not want to add all those empty strings you can use `columns` to specify how many of them should be in the table. Here's an example https://jsfiddle.net/3gxy86m1/

Thanks for the reply, I've missed that then. I can work with the `columns` solution

**Comment by AMBudnik** [comment]
Great! I'll close the topic as solved. However, if you'd need anything, please feel free to reach out to me at support@handsontable.com
