### ISSUE TITLE
How to use beforeRender hook in 0.9.17?

### ISSUE THREAD

**Issue by provegard** [handsontable/handsontable#1048]
With HOT 0.9.9, I used the beforeRender hook to initialize a rendering cache. When I try to upgrade to 0.9.17, I notice that HOT calls renderers in order to determine column widths, which essentially makes my rendering cache useless.

Isn't it odd/a bug to call renderers in a beforeRender hook?

**Comment by AMBudnik** [comment]
Issue closed cause of no other questions/suggestions in this subject.
