### ISSUE TITLE
[Bug]: Clicking on iPad trackpad doesn't trigger a selection

### ISSUE THREAD

**Issue by mtjoe3** [handsontable/handsontable#10498]
### Describe the bug

Touch events works well on tables on iPad, but clicking on cell using iPad trackpad/mouse does not do anything.

### Handsontable version

12.4.0

### Your environment

Chrome/MacOS

**Comment by AMBudnik** [comment]
Hi @mtjoe3 

Thank you so much for taking the time to report an issue. However, at this point, we do not have official support for iPads. Please take a look at our [Supported browsers page](https://handsontable.com/docs/javascript-data-grid/software-license/). We focus on desktop devices and mobile (iOS, Android) only.
