### ISSUE TITLE
[Bug]: Scroll position

### ISSUE THREAD

**Issue by robertovaldesperez** [handsontable/handsontable#10501]
### Describe the bug

The first 4 columns of the table are fixed, but when I change the resolution in the browser from 100 to 90 percent it looks like the image below

### Video/Screenshots

![image](https://github.com/handsontable/handsontable/assets/15571467/2e774135-ca73-4517-a274-cfb765ae66ce)

### Handsontable version

3.1.0

### Framework version

3.1.0

### Your environment

116.0.5845.141 and Windows 11 Pro

**Comment by AMBudnik** [comment]
Hi @robertovaldesperez 

We have gathered some zoom-related issue reported by our community in this epic https://github.com/handsontable/handsontable/issues/7527. Do you recognize any of them as being the same case as yours? Without a demo, it will be hard for me to confirm that by myself.

**Comment by AMBudnik** [comment]
I need to close this issue @robertovaldesperez

Please let me know when you'll be ready with the demo/settings. If you do not want to share the code here on GitHub we can also talk it over via email at support@handsontable.com
