### ISSUE TITLE
[Bug]: Broken Typescript Types

### ISSUE THREAD

**Issue by jd-carroll** [handsontable/handsontable#10509]
### Describe the bug

Handsontable does not export types for esModules (i.e. package.json `exports`). In almost all locations within Handsontable packages, the exports are structured like:
```jsonc
  // node_modules/handsontable/package.json
  ...
  exports: {
    ...
    "./base": {
      "import": "./base.mjs",
      "require": "./base.js"
    },
  ...
```
When it should be:
```jsonc
  // node_modules/handsontable/package.json
  ...
  exports: {
    ...
    "./base": {
      "types": "./base.d.ts",
      "import": "./base.mjs",
      "require": "./base.js"
    },
  ...
```

To reproduce follow these steps:
1) `npx create-next-app@latest` (make sure to keep typescript enabled)
2) `npm install handsontable@latest @handsontable/react@latest`
3) Open `./src/app/page.tsx`
4) Attempt to install the [react demo](https://handsontable.com/docs/react-data-grid/installation/):
```tsx
<HotTable
  data={[
    ['', 'Tesla', 'Volvo', 'Toyota', 'Ford'],
    ['2019', 10, 11, 12, 13],
    ['2020', 20, 11, 14, 13],
    ['2021', 30, 15, 12, 13]
  ]}
  rowHeaders={true}
  colHeaders={true}
  height="auto"
  licenseKey="non-commercial-and-evaluation" // for non-commercial use only
/>
```

### Handsontable version

@latest

### Your environment

Chrome MacOS

**Comment by jd-carroll** [comment]
No easy way to say this, but this issue combined with #7445 make Handsontable an absolute non-starter.

**I want to be a customer**, this is the right grid framework for us. But add in #9397 and there is just no way we can justify the time investment for Handsontable. The decision for us is now between a competitor or rolling our own (most likely a competitor).

Hope these issues can be resolved in the near future, because again, Handsontable is the right grid framework for our use cases.

Thank you!

**Comment by adrianszymanski89** [comment]
Hi @jd-carroll 

Thank you for reporting this. I understand your arguments, and as I mentioned at  https://github.com/handsontable/handsontable/issues/9397 - this will be worked on in the near future. As for https://github.com/handsontable/handsontable/issues/7445, it needs further investigation, and we don't have any specific timeline for this. The fastest issue to solve would be this one. I'll report it internally.

**Comment by myessail** [comment]
@adrianszymanski89 is there a timeline for this issue, #10509, as well? this is causing a lot of headaches for our team as well.

**Comment by adrianszymanski89** [comment]
Hi @myessail 

Not yet. We have a full backlog at the moment, but as soon as it gets to our roadmap, I'll let you know.
