### ISSUE TITLE
loadData: Reload Table with different row count fails

### ISSUE THREAD

**Issue by sapreuss** [handsontable/handsontable#1050]
Hi,

I'm using handsontable with a feature to change the number of displayed rows.
The user may change the amount and the table data will be reloaded - without creating a new table just using the 'loadData' method. The feature worked fine up to now.

Today I updated to release 0.9.18 and my feature fails.

I spotted the cause in 'this.translateRow' method trying to read a non existent 'instance.sortIndex[row]'. This happens, when the row number exceeds the row number of the original table.

Feature or Bug?

**Comment by AMBudnik** [comment]
@sapreuss I tried to reproduce it - but works fine In my opinion. In reloads the same with and without pressing any column header. Since in an issue from 2013 I assume it can be closed if it's solved.
