### ISSUE TITLE
[Bug]: Problem with Copy/Paste numbers from external source

### ISSUE THREAD

**Issue by julianaiglsdorfer** [handsontable/handsontable#10514]
### Describe the bug

I have of the use case where I copy numbers from external sources into HoT. If these numbers are formatted (e.g. 1,000,000.00) they are not recognised as a number and validated as wrong.

If I copy in an unformatted number, it is recognised correctly and also formatted correctly.

### Video/Screenshots

Formatted number in Microsoft Excel:

![image](https://github.com/handsontable/handsontable/assets/81320072/05872527-2de7-4a00-81dc-acee2428a56f)

Inserted with Copy/Paste in HoT:

![image](https://github.com/handsontable/handsontable/assets/81320072/1b7b15db-554e-4a9a-a8e4-8e39f2dcd421)

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/qc8pfeha/

### Handsontable version

13.0.0

### Your environment

Chrome Version 116.0.5845.141

**Comment by AMBudnik** [comment]
Hi @julianaiglsdorfer 

The `comma` is a string - not a separator. I recommend checking our `Numeric` cell type guide at https://handsontable.com/docs/javascript-data-grid/numeric-cell-type/ for more details. But as it is said in the guide

> You can't enter a thousands separator. After you finish editing the cell, the thousands separator is added automatically, based on your [numericFormat](https://handsontable.com/docs/javascript-data-grid/api/options/#numericformat) configuration.

Now, what you can do when the user is copy-pasting the value from Excel (for example) is to remove those commas. In a case when the `dot` is used as a decimal separator and we'd like to remove all the commas for the numeric cell type we can run `replace()` method within the `beforeChange` hook, like

```
 beforeChange: function(changes, src){
  	if(changes){
    	  if(changes[0][1] === 'price_usd'){
             let yourString = changes[0][3]; //only single change 
	     let stringWithoutCommas = yourString.replace(/,/g, '');
             changes[0][3] = stringWithoutCommas
           }
       }
  }
```

This is the [simplest scenario](https://jsfiddle.net/oLbkaqcn/2/), where we have a single change. For the multiple changes (like copy-paste more than one cell) you'd need to run the loop over all 3rd elements of the changes array. The `changes` array `length` equals the number of changed cells. 

ps. This way, you also do not need to worry about the validation process. The `afterValidate` hook runs after the `beforeChange` hook. You can test it here https://jsfiddle.net/oLbkaqcn/3/. If you'd like to learn more about it please feel free to contact us at support@handsontable.com and share your projects requirements.

**Comment by julianaiglsdorfer** [comment]
Hi @AMBudnik

Thanks for your quick response and your suggested solution. 
I will try to implement it like this.

**Comment by AMBudnik** [comment]
Thank you for sharing the progress and the code you use.

I will close the following ticket.
