### ISSUE TITLE
HOT width issue

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#1051]
Is there any way I can set the width of the table based on its parent.

I have the HOT inside a div (screenshot) but its not working. The table not keeping inside the parent div. Moreover if the screen resolution changes then the parent div is working fine but the inside HOT going haywire. 

I am using IE10

![capture](https://f.cloud.github.com/assets/4745102/1178646/1270152a-21ba-11e3-83eb-21c2b9407a11.png)

Please advice where i am going wrong. Any div sample would be great.

**Comment by AMBudnik** [comment]
Issue closed, because of lack of demo. Please open a new issue if case you would have any other ideas or questions.
