### ISSUE TITLE
[Bug]: Column summary is filtered out

### ISSUE THREAD

**Issue by conschtek** [handsontable/handsontable#10511]
### Describe the bug

There seem to be a bug regarding the column summary and filtering. My expectation was, that if I have a column summary and I use the filter, only the "normal" rows are going to be filtered and the summary row will be still there (with new values).

Against expectation the filter simply just filters out the summary row when the value does not meet the constraints.

### Video/Screenshots

1. The highlighted row is the Column Summary row
<img width="370" alt="image" src="https://github.com/handsontable/handsontable/assets/117377149/3818c8f7-dbb6-4fe8-b6e5-47435012e8fa">

2. Filtering a value which is not equal to the value in the summary row
<img width="393" alt="image" src="https://github.com/handsontable/handsontable/assets/117377149/1bb0941c-812c-42c2-b250-b0c885892fec">

3. Summary row is not visible anymore
<img width="387" alt="image" src="https://github.com/handsontable/handsontable/assets/117377149/b8e3d188-f300-48cb-baa0-e2cbca9ff177">

### Handsontable version

13.0

### Your environment

macOS and Chrome

**Comment by AMBudnik** [comment]
Hi @conschtek 

The summary row is a part of the data, so it is read by the Filters plugin the same as the other rows of data. At the moment, we do not have control over the list of values for the `filter by value` option to remove that row from the list.

**Comment by conschtek** [comment]
Hi @AMBudnik 
thank you for you quick response! I understand the issue, is there maybe a known workaround? How can I always display the summary row?

**Comment by AMBudnik** [comment]
You can bring it back via `afterFilter` hook. So the user will be able to remove it, but at the same time, you can show it again. Would that work for you?

**Comment by conschtek** [comment]
That sounds like a feasible idea, thank you very much!
