### ISSUE TITLE
[Bug]: Column sort does not work after using the manualColumnMove plugin

### ISSUE THREAD

**Issue by flobytes** [handsontable/handsontable#10512]
### Describe the bug

When using the combination of the plugins `persistentState` and `manualColumnMove`, the sorting for some columns does not work anymore. 

I am loading the info for moved columns from the persitentState as an array of indexes for the columns:

`this.hot.getPlugin('persistentState').loadValue('manualColumnMove', responseManualColumnMove);`

From that array, i am slicing the columns that are fixed on the left:

`const columns = responseManualColumnMove.value.slice(start, end);`

After that i am using the `manualColumnMove` plugin to move the columns:

`this.hot.getPlugin('manualColumnMove').moveColumns(columns, start);`

This works as intended, the columns are on the correct positions, however, the sorting for some of the columns is not working anymore. It just does not sort anything, instead does nothing.

For example it happens, when i am moving one column from position 6 to 2, the moved column sorting does still work, but the sort for every column after the moved one does not work anymore.

### Video/Screenshots

cannot provide

### Handsontable version

9.0.2

### Framework version

Vue2

### Your environment

MacOS, Chrome

**Comment by adrianszymanski89** [comment]
Hi @flobytes 

Please, provide a code example so we are able to see the exact settings and follow the steps to reproduce the issue. Also, did you check if the issue exists in the most recent version of Handsontable - 13.1.0?

**Comment by adrianszymanski89** [comment]
I'm closing this issue, as there were no updates for over 3 weeks.
