### ISSUE TITLE
type: 'numeric' invokes to many times beforeChange callback?

### ISSUE THREAD

**Issue by logeshkumars** [handsontable/handsontable#1052]
Hi,

When pasting data in numeric field, The "beforeChange" method call no of times(if you past data in 3 cells means then "beforechange" method calls 3 times).

Please fix this issue as soon as possible.

Thanks,
Logesh

**Comment by AMBudnik** [comment]
Issue does not occur any more. Please check the [example code](https://jsfiddle.net/AMBudnik/bwhm8883/).

If you still face this issue please prepare a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/).
