### ISSUE TITLE
 Custom renderer while scrolling shows cells incorrectly

### ISSUE THREAD

**Issue by conschtek** [handsontable/handsontable#10534]
### Describe the bug

Hi,

I have a custom cell renderer, where its decided based on different properties, how the cell should look like (it might be a merged cell with a text, or checkbox, or with different background color). In one case where I have boolean data, I return `cellProperties.renderer = "checkbox";` because I want the field to be the standard checkbox.

In the first glance it does what is expected, but if I begin to scroll not an empty checkbox but the text "false" stands in the cell. After a few second, or more scrolling the text disappears and the checkboxes are there as they should.

Is there any solution for this? Or other possibility to call the checkbox renderer from my custom renderer? 
Thank you!

### Video/Screenshots

https://github.com/handsontable/handsontable/assets/117377149/cf68a0e5-1ecc-4389-9d1f-a1411063e8de

### Handsontable version

12.3 

### Your environment

Windows, Chrome

**Comment by adrianszymanski89** [comment]
Hi @conschtek 

Thank you for reporting this. We will need a code demo that includes said custom renderer and represents the issue to check it. Please send it to us, and we will continue from there.

**Comment by AMBudnik** [comment]
Hi @conschtek 

I need to close this topic as we did not get a requested demo for a month, and without it, we are not able to replicate the issue.

If the issue remains, please contact us at support@handsontable.com
