### ISSUE TITLE
On scroll checkbox Header values were resetting

### ISSUE THREAD

**Issue by facn** [handsontable/handsontable#1054]
![qq20130923114413](https://f.cloud.github.com/assets/4577545/1189533/854ab218-2416-11e3-974e-30c0d515a82e.png)
![qq20130923114459](https://f.cloud.github.com/assets/4577545/1189535/8c3984e6-2416-11e3-9faf-e5ddd4eb4dd2.png)
checkbox is reset after scrolling

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.
