### ISSUE TITLE
over riding onPaste

### ISSUE THREAD

**Issue by johnhumbrecht** [handsontable/handsontable#1056]
I would like to override the onPaste method.  I would like to know that not all of my rectangular paste will fit in my selected location.

It does not seem the namespace is visible outside the plugin.  I would prefer not to change the handsontable code.  Can you help with some information on how to do it.

Thanks
John

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Feature added in Handsontable PRO as [Filters](https://docs.handsontable.com/pro/demo-filtering.html)

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
