### ISSUE TITLE
[Bug]: peer dependence vue@next will stop the build process in pnpm.

### ISSUE THREAD

**Issue by xywc-s** [handsontable/handsontable#10571]
### Describe the bug

peer dependence vue@next will stop the build process in pnpm.
I think it will be vue@^3.2 ? 

### Video/Screenshots

![image](https://github.com/handsontable/handsontable/assets/31307553/4d097771-0bb8-4a7c-874d-0f71df47a66a)
![image](https://github.com/handsontable/handsontable/assets/31307553/5ef1ec10-211d-4212-b0a7-066debf18566)

### Handsontable version

12.3.1

### Framework version

vue: 3.2.37

### Your environment

ubuntu 20.04

**Comment by AMBudnik** [comment]
Hi @xywc-s 

Thank you for sharing the proposition for a change.

I checked that, and you're right. And the Vue3 wrapper is the only one that causes this issue.

I will let you know about the progress.

**Comment by AMBudnik** [comment]
Hi @xywc-s 

I have great news for you today. We just released Handsontable v14.1.0, where this issue is fixed.

Thank you again for reporting.
