### ISSUE TITLE
Help with currency

### ISSUE THREAD

**Issue by wheelnut06** [handsontable/handsontable#1058]
Hello,

Can anyone out there give me an example of how to set up the currency for english pounds (£) please? When I try out the demo and include the numeral.js lib, I get an error:

TypeError: languages[currentLanguage] is undefined @ http://localhost/dist/jquery.handsontable.full.js:12223

The set up in my table is as follows:

```
    {
        data         : "price",
        type         : 'numeric',
        format       : '$ 0.00',
        readOnly     : true,
        language     : 'en-gb'
    }
```

I do not know how to set up a jsfiddle, sorry. I suspect that I have something silly like a mistake in syntax or I have forgotten a library (I am including numeral/min/numeral.min.js, numeral/min/languages/en-gb.min.js and
numeral/languages.js at the beginning in my .html file).

Many thanks in advance,

Martin

**Comment by AMBudnik** [comment]
updated example: http://jsfiddle.net/zjdzxz95/
