### ISSUE TITLE
[Bug]: row height bug when scroll horizontally

### ISSUE THREAD

**Issue by Kento97** [handsontable/handsontable#10594]
### Describe the bug

In Handsontable, when column fixing is enabled and there is a line break in a cell of a certain row, causing the row height to increase, if you scroll right until the cell with the line break disappears, the row height will decrease back to its default value. How can this issue be resolved?

### Handsontable version

13.1.0

### Your environment

win 10，edge 119.0.2151.72

**Comment by adrianszymanski89** [comment]
Hi @Kento97 

Please provide an example and visual representation of the problem so we can determine what might be the issue.
