### ISSUE TITLE
[Bug]: row height bug report

### ISSUE THREAD

**Issue by Kento97** [handsontable/handsontable#10596]
### Describe the bug

pic1:![image](https://github.com/handsontable/handsontable/assets/55472948/c0d037ba-dda8-4d73-89a6-1b25a63f7159)
pic2:![image](https://github.com/handsontable/handsontable/assets/55472948/1816da8c-7397-42cd-ac2a-97c687a3d8af)
here is the config:
```
this.hotSettings = {
        data: tableDataTemp.bodyData,
        width: 'auto',
        height: 'auto',
        rowHeights: DEFAULT_ROW_HEIGHT,
        autoRowSize: true, // 自动设置行高
        fillHandle: false, // https://handsontable.com/docs/javascript-data-grid/api/options/#fillhandle
        manualColumnResize: false, // 禁用列宽拖拽
        outsideClickDeselects: false,
        copyable: false, // 禁用复制
        colWidths: i => {
          const indexes = tableDataTemp.headData
            .map((item, index) => {
              if (!item.prop.includes('date')) {
                return index
              } else {
                return null
              }
            })
            .filter(item => typeof item === 'number')
          return indexes.includes(i) ? 50 : 85
        },
        rowHeaders: false,
        colHeaders: tableDataTemp.headData.map(item => item.label),
        columns: tableDataTemp.headData.map(item => ({
          ...item,
          data: item.prop,
          className: 'htCenter', // 设置表格居中
          renderer: this.customRender,
          editor: false,
          readOnly: true
        })),
        selectionMode: 'multiple', // 'single', 'range' or 'multiple',
        disableVisualSelection: ['header'],
        fixedColumnsStart: tableDataTemp.headData.filter(
          item => !item.prop.includes('date')
        ).length,
        beforeKeyDown: function(event) {
          if (event.ctrlKey && event.keyCode === 65) {
            // 检测ctrl+A组合键
            event.stopImmediatePropagation() // 阻止事件冒泡
            event.preventDefault() // 阻止默认行为
            return false
          }
          return true
        },
      }
```

**Setting 'autoRowSize: true', when I scroll horizontally, the row height of a scrollable column suddenly becomes too large, causing it to no longer correspond to the row height of the previously fixed column.**

### Handsontable version

13.1.0

### Framework version

vue 2.6

### Your environment

win 10 ,edge 119.0.2151.72

**Comment by adrianszymanski89** [comment]
Hi @Kento97 

Thank you for the details. I'll check your implementation and update you soon.

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> Thank you for the details. I'll check your implementation and update you soon.

This phenomenon is not 100% reproduced, perhaps only 60% of the probability of reproduction.

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> Thank you for the details. I'll check your implementation and update you soon.

And I find that it may be related to the text wrapping within the cell.

**Comment by adrianszymanski89** [comment]
Hi @Kento97 

I checked your configuration, but there are too many missing variables to let me reproduce it. Can you please prepare a code demo where the issue can be replicated? 

Looking at the visual effect and the fact that you are using the `fixedColumnsStart` option might suggest similarity to a known problem with it, but the configuration generally also consists of `mergeCells` in such cases, which are not present in your config. This is why the code demo will be needed to determine what might be the cause here.

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> I checked your configuration, but there are too many missing variables to let me reproduce it. Can you please prepare a code demo where the issue can be replicated?
> 
> Looking at the visual effect and the fact that you are using the `fixedColumnsStart` option might suggest similarity to a known problem with it, but the configuration generally also consists of `mergeCells` in such cases, which are not present in your config. This is why the code demo will be needed to determine what might be the cause here.

[hoy_setting.md](https://github.com/handsontable/handsontable/files/13438818/hoy_setting.md)
I have uploaded the complete configuration items. There are many data, and you can view the attachment for details.

**Comment by adrianszymanski89** [comment]
Hi @Kento97 

Thank you for the details, but I'm still unable to reproduce your issue. You can find the example based on your code here: https://jsfiddle.net/handsoncode/cgrh26ue/

Please adjust it so it represents the problem.

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> Thank you for the details, but I'm still unable to reproduce your issue. You can find the example based on your code here: https://jsfiddle.net/handsoncode/cgrh26ue/
> 
> Please adjust it so it represents the problem.

As I mentioned above, this bug is not 100% reproducible. I will try my best to find a stable reproduction case.

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> Thank you for the details, but I'm still unable to reproduce your issue. You can find the example based on your code here: https://jsfiddle.net/handsoncode/cgrh26ue/
> 
> Please adjust it so it represents the problem.

https://jsfiddle.net/tangyun/3uf7sdj1/1/
HI, I write a demo to reproduce my issue. Now it's 100% percent to reproduce the issue.

**Comment by adrianszymanski89** [comment]
Hi @Kento97 

Thank you for the example. Now, I can see the issue clearly. I will check your demo and get back to you soon.

**Comment by adrianszymanski89** [comment]
Hi @Kento97 

I checked your code, and the issue lies within your custom renderer implementation. I find that this line produces the issue:

```
cellContentDoms.forEach(ele => {
     td.appendChild(ele);
});
```

It seems that it's creating additional elements overlapping the table.

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> I checked your code, and the issue lies within your custom renderer implementation. I find that this line produces the issue:
> 
> ```
> cellContentDoms.forEach(ele => {
>      td.appendChild(ele);
> });
> ```
> 
> It seems that it's creating additional elements overlapping the table.

Can the custom rendering function of cells not return html elements?

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> I checked your code, and the issue lies within your custom renderer implementation. I find that this line produces the issue:
> 
> ```
> cellContentDoms.forEach(ele => {
>      td.appendChild(ele);
> });
> ```
> 
> It seems that it's creating additional elements overlapping the table.

I'm curious why placing a DOM element in a cell can cause row height issues. Now I have a requirement to add color to some text within a cell. Without the DOM element, it would be difficult to do this.

**Comment by adrianszymanski89** [comment]
Hi @Kento97 

I can only perform a partial code review of your implementation, which is quite complex. In general, you can attach, let's say, a custom CSS class to the DOM cell element accessed through a custom renderer.

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> I can only perform a partial code review of your implementation, which is quite complex. In general, you can attach, let's say, a custom CSS class to the DOM cell element accessed through a custom renderer.

If I try to remove the dom element and render the text directly, there will be no problem. If I add the dom element, there will be a line height exception. I can't find a solution at present.

**Comment by Kento97** [comment]
> > Hi @Kento97
> > I can only perform a partial code review of your implementation, which is quite complex. In general, you can attach, let's say, a custom CSS class to the DOM cell element accessed through a custom renderer.
> 
> I'll try using the cells method for custom rendering

I tried it, It doesn't work

**Comment by adrianszymanski89** [comment]
Hi @Kento97 

I prepared a basic example showing how to attach the class to the TD element in a custom renderer: https://jsfiddle.net/handsoncode/xh2yj45L/

I hope it will be helpful for you.

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> I prepared a basic example showing how to attach the class to the TD element in a custom renderer: https://jsfiddle.net/handsoncode/xh2yj45L/
> 
> I hope it will be helpful for you.

Thanks. However, my business logic requires setting a style for a part of string within a td. Setting a class directly on the td cannot achieve this requirement. Additionally, I would like to know how the row height of fixed columns is consistent with that of non-fixed columns. Is there a bug in the current implementation that causes inconsistent row heights?

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> I prepared a basic example showing how to attach the class to the TD element in a custom renderer: https://jsfiddle.net/handsoncode/xh2yj45L/
> 
> I hope it will be helpful for you.

If you turn off 'fixedColumnsStart', the row height will be normal, but if you turn it on, there will be problems. So the problem may be with the 'fixed columns' function?

**Comment by adrianszymanski89** [comment]
Hi @Kento97 

I can see that removing this option results in the same effect as removing the line, as mentioned before. `fixedColumnsStart` shouldn't affect rendering in such way, so I would focus on reviewing the custom renderer.

**Comment by Kento97** [comment]
> Hi @Kento97
> 
> I can see that removing this option results in the same effect as removing the line, as mentioned before. `fixedColumnsStart` shouldn't affect rendering in such way, so I would focus on reviewing the custom renderer.

https://jsfiddle.net/tangyun/3uf7sdj1/24/
My observation at present is that when the 'autoRowSize' and 'fixedColumnsLeft' configurations are enabled, if the non-fixed cells are stretched by html elements, resulting in exceeding the set 'rowHeights', the row height of the fixed columns will not be able to keep up with the change in the row height of the non-fixed columns.
