### ISSUE TITLE
Keyboard navigation issues on scrolled table.

### ISSUE THREAD

**Issue by c4b3z0n** [handsontable/handsontable#1060]
Hi, I'm using handsontable v0.9.18

I have a table with scroll.
Sometimes, while navigating with the down arrow, the last row is cut out (so you can't see it completelly unless you keep scrolling down). 
If I'm standing in one of these cells and press column navigation key (say left key, or tab key, etc), it jumps to the expected column, but the row selected becomes the first that is actually visible. 
I'm attaching two screenshots to show the problem.

![step1](https://f.cloud.github.com/assets/4029635/1210491/988a78b4-25fa-11e3-91a1-addd32a88578.png)
![step2](https://f.cloud.github.com/assets/4029635/1210490/98860626-25fa-11e3-84c6-aa82d96caab9.png)

Also, related to the keyboard navigation, if I'm navigating down, sometimes instead of showing only the next row, it just moves the complete 'view', so the first row being displayed becomes the one that was at the bottom, it's a page-down kind of behavior.
I was able to reproduce this by going to say the bottom of the table, and then going to the top (Ctrl+Home), and then scrolling with the down arrow key.

**Comment by AMBudnik** [comment]
Please write back, do you still face this issue after updating to [0.13.1](https://github.com/handsontable/handsontable/releases/tag/0.13.1).

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply for more than a month.
