### ISSUE TITLE
Does it really support TypeScript now?

### ISSUE THREAD

**Issue by vinoMamba** [handsontable/handsontable#10600]
### Page URL

https://github.com/handsontable/handsontable/blob/develop/examples/13.1.0/docs/ts/demo/src/index.ts

### Improvement description

When i found the typescript demo, I see 
![image](https://github.com/handsontable/handsontable/assets/63380208/e0193ce4-0455-41a6-beae-26c96b9f8289)

In my project: 
![image](https://github.com/handsontable/handsontable/assets/63380208/98da4165-429e-402e-bebb-71cf0926816c)

So what should I do ？ The only method to resolve this eslint error is set `@ts-ignore`. Right?

**Comment by vinoMamba** [comment]
I create a demo



 https://codesandbox.io/p/sandbox/loving-leftpad-6dhs7g


![image](https://github.com/handsontable/handsontable/assets/63380208/c4ab025c-c3ee-47a4-9019-66295891a0a2)


Then I added this line of code in package.json , and now it won't throw an error. It's seems like the `typying`  field is not usefull. 

![image](https://github.com/handsontable/handsontable/assets/63380208/72b0ecfb-f8fd-4513-b14c-c9203138569f)

**Comment by AMBudnik** [comment]
Hi @vinoMamba 

Thank you for mentioning the subject. You're right - there's room for improvement, which we did here https://github.com/handsontable/handsontable/pull/10546. And here https://github.com/handsontable/handsontable/blob/develop/examples/next/docs/ts/demo/src/index.ts is how it will look in the next release. 

I will make sure to update you as soon as we officially publish the new version (should be the end of November).

**Comment by AMBudnik** [comment]
Hi @vinoMamba 

I'm glad to announce that the release has come. Here https://handsontable.com/docs/javascript-data-grid/release-notes/ you can read more about the changes. 

If you'd have any questions please let me know here or at support@handsontable.com
