### ISSUE TITLE
[Bug]: table's first row can not set backgroundColor

### ISSUE THREAD

**Issue by renjieyao** [handsontable/handsontable#10616]
### Describe the bug

 table's first row can not set backgroundColor

### Handsontable version

13.1.0

### Your environment

geogle

**Comment by AMBudnik** [comment]
Hi @renjieyao 

What is your approach to setting up the background color? We have an example like this in the documentation at https://handsontable.com/docs/javascript-data-grid/conditional-formatting/, and the background color is applied.

**Comment by renjieyao** [comment]
![image](https://github.com/handsontable/handsontable/assets/50436535/f64077ec-e2a8-4c26-b398-fbb4ed324255)
When I updateSetting the table ,cells's function makes all rows changed expect the first row.

**Comment by renjieyao** [comment]
> Hi @renjieyao
> 
> What is your approach to setting up the background color? We have an example like this in the documentation at https://handsontable.com/docs/javascript-data-grid/conditional-formatting/, and the background color is applied.
![image](https://github.com/handsontable/handsontable/assets/50436535/2263bcca-f0ed-40e7-9675-f1e8650eff13)

When I updateSetting the table ,cells's function makes all rows changed expect the first row.

**Comment by renjieyao** [comment]
Thank u,I will try it.
---- Replied Message ----
| From | Aleksandra ***@***.***> |
| Date | 11/28/2023 19:49 |
| To | handsontable/handsontable ***@***.***> |
| Cc | renjieyao ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [handsontable/handsontable] [Bug]: table's first row can not set backgroundColor (Issue #10616) |

We recommend using a className or a renderer to add the background color, the CSS style may not stay on the cell upon rendering.

In your case, I recommend changing cell.style.background = 'green' to this.setCellMeta(row, 0, 'className', 'myGreenCell') and create a .myGreenCell in the CSS section for the background-color: 'green'. The this should point to the instance.

If that won't work for you please write me at ***@***.*** we can work on the code snipper together.

**Comment by renjieyao** [comment]
why I use removeCellMeta cannot remove the .myGreenCell?
sourceHotTableComp.removeCellMeta(0, i, 'className')

**Comment by AMBudnik** [comment]
Hi @renjieyao 

Here https://jsfiddle.net/duoaj2tm/ is a simple example that shows the `setCellMeta()` and `removeCellMeta()` methods for a given `className`. If it doesn't work for you
- check if the coordinates are correct
- check if there is no other code that re-attaches the `className`

**Comment by renjieyao** [comment]
const clearLeftTableColor = () => { 
  const hot = proxy.$refs.sourceHotTable.hotInstance
  tableData.value.forEach((item, index) => {
    hot.setCellMeta(index, 0, 'className', 'test')
    console.log(hot.getCellMeta(index, 0), index, 'index')
  })
}
<img width="430" alt="image" src="https://github.com/user-attachments/assets/da4565d7-a30c-4e3f-98b9-a28643301638" />
<img width="927" alt="image" src="https://github.com/user-attachments/assets/369995a0-1612-4bac-832e-218fc699361d" />
I find my data is .test,but my view of css className is .myGreenClass,is it normal?

**Comment by renjieyao** [comment]
// 表格染色
  const tableColorChange = (unmatchedArr, rowData = null) => {
    sourceHotTableComp.updateSettings({
      cells: function (row, col, prop) {
        const cellProperties = {}
        cellProperties.renderer = colorChange(row, rowData, unmatchedArr)
        return cellProperties
      },
    })
  }

My coloring method is like this. Is it because I modified the cell render method that it cannot be removed

**Comment by AMBudnik** [comment]
Hi @renjieyao 

did you call the `hot.render()` after calling `hot.setCellMeta()` with the `test` class name? It would be helpful if you could share a demo where the issue is replicable. It seems that you have two separate logic for two classes and they collapse so only one of them is applied.

**Comment by AMBudnik** [comment]
Hi @renjieyao

I will need to keep this issue closed until we get a demo where the issue can be replicated.
