### ISSUE TITLE
Performance issue  with instance.setDataAtCell()

### ISSUE THREAD

**Issue by zallarak** [handsontable/handsontable#1061]
For a loop like this that has ~500 rows, it takes almost 2 seconds to set boolean values. Is there a way you'd recommend to do something like this with less lag)

    // sets all checkboxes to true in first column
    for (var i = 0; i < handsontableInstance.countRows(); i++) {
      handsontableInstance.setDataAtCell(i, 0, true);
    }

Thank you

**Comment by AMBudnik** [comment]
I assume this issue can be closed in lack of other questions.

**Comment by armensg** [comment]
Is there a way to disable the rendering while using setDataAtCell ()? Its really convenient for my app to use this function but I am suffering from some serious delays.

**Comment by AMBudnik** [comment]
Hi @armensg `setDataAtCell` triggers the render to refresh the table and show new content. If you are loading more data sometimes it is better to use the `loadData` method instead.

Here's a basic demo where you are able to compare `loadData` with `setDataAtCell` : http://jsfiddle.net/1kruLmjo/ Basically this one is easy to achieve with `loadData` as I'm changing only the first column but the case is to show different level of performance for those two methods.
