### ISSUE TITLE
[Bug]: vue3 wrapper not work correctly when data changed

### ISSUE THREAD

**Issue by iHearty** [handsontable/handsontable#10615]
### Describe the bug

i have the following code, when data changed, hot table not refreshed.
```javascript
<template>
  <div>
    <button @click="changeDataHandler">Change Data</button>
    <div>{{ data }}</div>
    <hot-table :data="data" :rowHeaders="rowHeaders" :colHeaders="colHeaders"></hot-table>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { HotTable } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';
import 'handsontable/dist/handsontable.full.css';

registerAllModules();

const data = ref([
   ['', 'Ford', 'Volvo', 'Toyota', 'Honda'],
   ['2016', 10, 11, 12, 13],
   ['2017', 20, 11, 14, 13],
   ['2018', 30, 15, 12, 13]
]);

const changeDataHandler = () => {
  data.value = [
    ['2023', 10, 11, 12, 13],
    ['2024', 10, 11, 12, 13],
  ];
};
</script>

```

### Video/Screenshots

<img width="1264" alt="image" src="https://github.com/handsontable/handsontable/assets/10851527/6a4ee559-9ec8-4aac-9461-65b1024549f6">

<img width="1199" alt="image" src="https://github.com/handsontable/handsontable/assets/10851527/fc6de314-5adf-42d0-a537-e1efb125f840">

### Handsontable version

13.1.0

### Your environment

macos 13.6 (22G120) | chrome 119.0.6045.159

**Comment by adrianszymanski89** [comment]
Hi @iHearty 

Thank you for contacting us. It looks like you are missing the part where you update the data in the table. There are three methods available to do this. You can read more about them here: https://handsontable.com/docs/javascript-data-grid/binding-to-data/#the-data-loading-api-methods
