### ISSUE TITLE
Hiding an ID/Key Column

### ISSUE THREAD

**Issue by gummel** [handsontable/handsontable#1062]
Is there another way to hide a column, such as a ID/Key, without explicitly defining the columns using the "columns" property? I have a situation where there is an ID field and a variable number of other fields, depending on the dataset being bound to the grid. 
Another issue related to this case is when defining columns explicitly, you cannot utilize the "minSpareCols" or "minCols" properties. If anyone has any suggestions, please let me know. Thanks.

**Comment by AMBudnik** [comment]
For further information, please track changes in #2020 issue.
