### ISSUE TITLE
[Bug]:The filter menu items is not working

### ISSUE THREAD

**Issue by DiegoJimenez95** [handsontable/handsontable#10636]
### Describe the bug

There is a problem when the column menu is enabled, but when displaying only the filter menu items as in the example on your page: 
_**dropdownMenu: ['filter_by_condition', 'filter_by_value', 'filter_action_bar'],**_ 
![issue 5](https://github.com/handsontable/handsontable/assets/144830772/af2a92d1-caed-4b35-8988-99bee4a1a6d9)
It doesn't work when I click on the "OK" button it shows the following message in the console (See the message in the console in the first screenshot).

But if I just enable the column menu as in the example code in your page:
_**dropdownMenu: true,**_ 
![issue 4](https://github.com/handsontable/handsontable/assets/144830772/bb444f5f-795d-4f8c-ac38-a11825d1cc36)
It works. 

I think it is a problem of the recent update of your library because before it was working fine.
### Video/Screenshots

![issue](https://github.com/handsontable/handsontable/assets/144830772/2c80774d-f2c1-4c40-af01-1b84ac9feec9)
![issue 2](https://github.com/handsontable/handsontable/assets/144830772/20620cd0-b00c-4b63-b0f7-68fbe282dfd4)
![issue 3](https://github.com/handsontable/handsontable/assets/144830772/3893912b-c201-4651-b15e-f279773f12bb)

### Handsontable version

14.0.0

### Your environment

Opera, Chrome and Firefox

**Comment by DiegoJimenez95** [comment]
Thank u a lot Adrian, I'll be pending 👍

**Comment by AMBudnik** [comment]
Hi @DiegoJimenez95 

We just released v14.1.0, where this issue is fixed. Thank you again for reporting!

Here you can read more about the changes that we introduced and issues that were fixed https://handsontable.com/blog/handsontable-14-1-0-typescript-ssr-improvements
