### ISSUE TITLE
validateChanges - performance issue with simple validators

### ISSUE THREAD

**Issue by LiefMartin** [handsontable/handsontable#1063]
In the validateChanges function (core.js), each cell's validator is called as it is added to the ValidatorsQueue (waitingForValidator) .  Most validators (e.g. for a numeric cell) run the callback function immediately, which removes the validator from the queue.  Because the queue is empty to start with, this triggers the onQueueEmpty function to fire for each celll that has a validator.

As a workaround I'm making one extra call to addValidatorToQueue() before adding the cell validators, and then making the corresponding call to removeValidatorFormQueue() after all of the validators have been added.

**Comment by AMBudnik** [comment]
Please track changes in #1052
