### ISSUE TITLE
[Bug]: Can't paste into Handsontable 14.0.0

### ISSUE THREAD

**Issue by pvermees** [handsontable/handsontable#10641]
### Describe the bug

I recently upgraded an old but heavily used jQuery-based app from Handsontable 6.2 (!) to 14.0. The upgrade was surprisingly easy, except from one problem: I can no longer paste data into the table. Firefox gives me the following error message:

```
   Uncaught TypeError: i.default is undefined
         n             http://127.0.0.1:12644/js/handsontable.min.js:53
         onPaste       http://127.0.0.1:12644/js/handsontable.min.js:64
         enablePlugin  http://127.0.0.1:12644/js/handsontable.min.js:64
         i             http://127.0.0.1:12644/js/handsontable.min.js:32
```

You can test an online version of the app [here](https://pieter-vermeesch.es.ucl.ac.uk/isoplotr/). According to the documentation, the `copypaste` plugin should be enabled by default. Why does it not work here?

### Handsontable version

14.0.0

### Your environment

Firefox and Ubuntu 22.04, but a colleague reported the same issue in Windows.

**Comment by budnix** [comment]
@pvermees I see in your app that there is a lack of the `dompurify` dependency. Add it (https://www.jsdelivr.com/package/npm/dompurify) before Handsontable or use full packed version instead (`handsontable.full.min.js`).
