### ISSUE TITLE
check box In hot-cloumn doesn't show

### ISSUE THREAD

**Issue by renjieyao** [handsontable/handsontable#10665]
<img width="345" alt="image" src="https://github.com/handsontable/handsontable/assets/50436535/33d507f3-b216-494f-bb07-b518f6d7f7c4">
<img width="536" alt="image" src="https://github.com/handsontable/handsontable/assets/50436535/396cdb13-8890-48a2-9f80-42eb8a9fc4e1">
why checkbox doesn't show...

**Comment by adrianszymanski89** [comment]
Hi @renjieyao 

Can you please show us what your data object looks like for the checkbox column?

**Comment by renjieyao** [comment]
> Hi @renjieyao
> 
> Can you please show us what your data object looks like for the checkbox column?

I just give a property that named isCheck, like this:{ isCheck: true }.

**Comment by adrianszymanski89** [comment]
Hi @renjieyao 

Thank you, that looks correct. Can you please check if you registered all of the modules in Handsontable? It's necessary to have all the features working correctly. It is done like this:

> import Handsontable from 'handsontable/base';
import { registerAllModules } from 'handsontable/registry';
registerAllModules();

**Comment by renjieyao** [comment]
> Hi @renjieyao
> 
> Thank you, that looks correct. Can you please check if you registered all of the modules in Handsontable? It's necessary to have all the features working correctly. It is done like this:
> 
> > import Handsontable from 'handsontable/base';
> > import { registerAllModules } from 'handsontable/registry';
> > registerAllModules();

import { reactive, toRefs, onMounted, nextTick } from 'vue'
import { HotTable, HotColumn } from '@handsontable/vue3'
import { registerAllModules } from 'handsontable/registry'
import 'handsontable/dist/handsontable.full.css'
import { ElMessage, ElMessageBox } from 'element-plus'

registerAllModules()

is this right?

**Comment by adrianszymanski89** [comment]
@renjieyao 

Yes. Does that solve the problem? If not, please send us the code demo where the issue is replicable so we can see what's going on.

**Comment by renjieyao** [comment]
> @renjieyao
> 
> Yes. Does that solve the problem? If not, please send us the code demo where the issue is replicable so we can see what's going on.

no, I write it at the beginning.

**Comment by adrianszymanski89** [comment]
Ok, in this case, I will need a code demo representing the issue to determine what can be wrong.

**Comment by renjieyao** [comment]
> Ok, in this case, I will need a code demo representing the issue to determine what can be wrong.

I have solved this problem, but I want to know is handsontable possible to set a radio?

**Comment by adrianszymanski89** [comment]
Hi @renjieyao 

I'm glad to hear that. Yes, you can set radio-type input elements through a custom renderer. Here's an example: https://jsfiddle.net/handsoncode/u19z0hfr/

Here you can read more about custom renderers: https://handsontable.com/docs/javascript-data-grid/cell-renderer/

**Comment by renjieyao** [comment]
> Hi @renjieyao
> 
> I'm glad to hear that. Yes, you can set radio-type input elements through a custom renderer. Here's an example: https://jsfiddle.net/handsoncode/u19z0hfr/
> 
> Here you can read more about custom renderers: https://handsontable.com/docs/javascript-data-grid/cell-renderer/

Ok，thank u very much.
