### ISSUE TITLE
Can I use HyperFormula in Hot-table?

### ISSUE THREAD

**Issue by renjieyao** [handsontable/handsontable#10679]
<img width="753" alt="image" src="https://github.com/handsontable/handsontable/assets/50436535/d41b0d6f-732a-4fcf-9062-ccf0e23c6301">
<img width="782" alt="image" src="https://github.com/handsontable/handsontable/assets/50436535/1dc884b7-77c5-4874-bc8e-e42aa6a0291b">
It doesn't work, please tell me what's wrong.

**Comment by adrianszymanski89** [comment]
Hi @renjieyao 

I see that you are passing just the `engine` property to a configuration object. It has to be passed to the `formulas` option, like here:

>  formulas: {
      engine: hyperformulaInstance,
      sheetName: 'Sheet1',
  },

**Comment by renjieyao** [comment]
Ok,thank you.
