### ISSUE TITLE
[Bug]: After interacting with Handsontable, the clipboard functionality is not working properly.

### ISSUE THREAD

**Issue by Z-Custom-Cyber** [handsontable/handsontable#10689]
### Describe the bug

Handsontable version: 14.0.0. 
I have a simple test static page with a horizontally centered input field, followed by a Handsontable spreadsheet below, and a display area further down. Entering content into both the input field and the spreadsheet causes the display area to show different texts. The interaction with the input field is normal, spreadsheet input functions properly, and content is displayed correctly. However, I am facing the following issues:

After interacting with the spreadsheet (clicking, entering, etc.), when I try to select text in the display area with the mouse, I cannot copy it to the clipboard normally.

After interacting with the spreadsheet and then clicking on the input field, I can select the text in the display area with the mouse and copy it to the clipboard as expected.

I have also tried other behaviors:

After interacting with the spreadsheet, clicking on a blank area of the page, and then selecting text in the display area with the mouse, I am unable to copy it to the clipboard normally.

After interacting with the spreadsheet and then clicking on the display area, trying to select the text with the mouse does not allow me to copy it to the clipboard normally.

It seems that copying works normally only after clicking on an interactive element, like the input box.

### Handsontable version

14.0.0

### Your environment

windows10

**Comment by adrianszymanski89** [comment]
Hi @Z-Custom-Cyber 

Thank you for contacting us. I tried to recreate the scenarios you described, but I could not get the same results. I can copy the values each time. Can you please share a recording showing how to recreate this problem?

**Comment by AMBudnik** [comment]
Hi @Z-Custom-Cyber 

do we have any updates here? Without any details about the replication, we would need to close the issue report.
