### ISSUE TITLE
[Bug]: Styles are different when using react-scripts vs vite

### ISSUE THREAD

**Issue by wave-light** [handsontable/handsontable#10684]
### Describe the bug

The tables are styled differently when using a project configured using react-scripts, versus when using Vite.
Also, the date picker does not open at the correct month when using the Vite app.

Here is the link to the app built with react-scripts: https://github.com/wave-light/handsontable-date-demo-1
Here is the link to the app built with Vite: https://github.com/wave-light/handsontable-date-demo-2

The code is almost identical, but the styling is appearing differently between the two projects. Also, the date picker opens the date at the wrong month when using the app built with Vite. It ignores the date format DD/MM/YYYY and opens the calendar as if the date were MM/DD/YYYY.

### Video/Screenshots

Project built with react-scripts:
![react-scripts-handontable-styles](https://github.com/handsontable/handsontable/assets/40989533/21525a0a-6d35-4f0b-ab57-4ce36f7748d1)

Project built with Vite:
![vite-handsontable-styles](https://github.com/handsontable/handsontable/assets/40989533/69ad8858-e0f6-4bb5-9c49-e9d48273f2cf)

### Provide a link to the demo with the bug reproduction

Links to demo repos have been included.

### Handsontable version

14.0

### Your environment

MacOS, Google Chrome

**Comment by adrianszymanski89** [comment]
Hi @wave-light 

Thank you for reporting this. The issue with font size in an app built with `react-scripts` is easy to fix. You just have to add this styling to the main CSS file:

`table {
    font-size: 13px !important;
}`

Apparently, `react-scripts` overrides the default font size for the `table` element with its own value. Nevertheless, I will report it internally as an issue.

I can also confirm the second issue. I couldn't find the reason for this behavior, so we will need to investigate it further. I will let you know if we find a solution.
