### ISSUE TITLE
why contextmenu not work

### ISSUE THREAD

**Issue by renjieyao** [handsontable/handsontable#10687]
![7557b5b5b82435f54274c9946369af6 (1)](https://github.com/handsontable/handsontable/assets/50436535/5ee77e6d-7438-42b4-8bfe-a3a7882ad500)
![image](https://github.com/handsontable/handsontable/assets/50436535/76dd02b4-9a8e-4ebb-afa7-c9724cb70bf4)

**Comment by AMBudnik** [comment]
Hi @renjieyao 

There seems to be a typo. It should be `contextMenu` (capital 'M'). 

Please let me know if it solved the issue.

**Comment by renjieyao** [comment]
Ok,thank u.
