### ISSUE TITLE
[Bug]: Handsontable getSourceData returns data of cells in wrong order after moving columns in React

### ISSUE THREAD

**Issue by thanhlevu** [handsontable/handsontable#10692]
### Describe the bug

Hi, I am using Handsontable to create excel tables within my React project. 
Since I want to store the raw cell data such as formulas in my database, so I use `hotTableComponent.current.hotInstance.getSourceData()`
I have noticed that if I move the columns/rows, the return of cell order from `getSourceData()` is not in correct order. 

You can look at the picture below, while getData() returns correct order, getSourceData seem to be not updated against the column moves.

### Video/Screenshots

<img width="1650" alt="image" src="https://github.com/handsontable/handsontable/assets/33485829/ee47adfb-94b9-4313-ad12-95c1d9a63ef1">

### Handsontable version

14.0.0

### Your environment

Chrome in macOS Version 119.0.6045.159 (Official Build) (x86_64)

https://github.com/handsontable/handsontable/assets/33485829/f0566e72-ac0c-4812-aec5-7a605dc470b9

**Comment by adrianszymanski89** [comment]
Hi @thanhlevu 

Thank you for contacting us. This is a correct behavior. `getSourceData()` will always return the initial data and skip any alterations to the order or number of rows/columns.

**Comment by thanhlevu** [comment]
Hi @adrianszymanski89,

Thank you for your reply. 
Could I get your suggestion on how to get the table data with formulas like the return of `getSourceData()` but in the correct order ?

Truly appreciate your time on the matter.

**Comment by adrianszymanski89** [comment]
I think, in this case, you can use native HyperFormula methods. In this example, I used `getSheetSerialized` to get all the data from the sheet in the format of an array of arrays: https://jsfiddle.net/handsoncode/hfgL74wt/

You can see that when I use this method inside the `afterColumnMove` hook, you will get the formulas in the correct order.

**Comment by thanhlevu** [comment]
Hi @adrianszymanski89, 
You are such as my life saver today. 
Million thanks for your support.

**Comment by thanhlevu** [comment]
I gonna close the discussion because of the great explanation of @adrianszymanski89 .

**Comment by adrianszymanski89** [comment]
I'm glad I could help!
