### ISSUE TITLE
Scrolling table panel, causes the table Headers to vanish... I am using built in header not custom headers.

### ISSUE THREAD

**Issue by khaziwallis** [handsontable/handsontable#1069]
Hello friends,

handson table header getting vanish, when i am scrolling the table consecutively.
It know it is difficult to understand the code.. because most of data code is comming dynamically from jsp code.

please help me and our report admin.

var $table = $("#hstable")
			.handsontable(
					{
						data:<%=positions%>,
						rowHeaders : true,
						colHeaders : true,
						minRows : 50,
						minCols : 200,
						minSpareCols : 5,
						minSpareRows : 5,
						//contextMenu : true,
						currentRowClassName: 'currentRow',
    					currentColClassName: 'currentCol',
						autoWrapRow : true,
						autoWrapCol : true,
						manualColumnResize : true,
						manualColumnMove : true,
						columnSorting : true,
						outsideClickDeselects : true,
						removeRow : true,
						removeCol : true,
						/*  colHeaders: [A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P],
				        rowHeaders: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],  */
						undo : true,
						stretchH : 'all',
						manualColumnResize : true,
						onSelection : function(r, c, r2, c2) {
							clearRadio();
							var td = $table.handsontable('getCell', r, c), $td = $(td), pos = $td.offset();
							$plus.show();
							
							if(!dragFlag)
							{
								$plus.css('z-index', 1).offset({
							 	top: pos.top+ $td.innerHeight()+5,
								left: pos.left+ $td.innerWidth()/2+30// - $plus.outerWidth(true)
							});
							}
							if (typeof(stylesJson[r+"-"+c]) != "undefined")
								document.getElementById("cellStyle").innerHTML = "Cell Style: "+stylesJson[r+"-"+c];
							else
								document.getElementById("cellStyle").innerHTML = "Cell Style: DEFAULT"
						
								
								
							if (typeof(widthJsonData[c]) != "undefined")
									document.getElementById("columnWidth").innerHTML = "Column Width: "+widthJsonData[c];
							else
								document.getElementById("columnWidth").innerHTML = "Column Width: default"	
								
						},
				  
						 onChange : function() {
							 
							 	change_events("onChange", arguments);
								styleChengeEvent();
						}
						
					
			                       
					});
	
	

	$("#hstable").on('mouseup','.handle', function (e) {
		styleChengeEvent();
	});
	 
	 
	var dragFlag=false;
	var $plus = $(".plus").click(function() {
				var jobValue = null;
				var searchVal=null;
				var jobValues = null;

		    
				searchVal=document.getElementById("headerVal").value;
				jobValues = document.getElementsByName("info");
				for ( var i = 0; i < jobValues.length; i++) {
					if (jobValues[i].checked)
						jobValue = jobValues[i].value;
				}
				if(jobValue==null)
				jobValue=searchVal;
				var sel = $table.handsontable('getSelected'), val = $table
						.handsontable('getDataAtCell', sel[0], sel[1]);
				$table.handsontable('setDataAtCell', sel[0], sel[1], jobValue);
				document.getElementById("radioForm").reset();
			});

	$(document).ready(function() {
		document.getElementById("dataStyle").value="$$$$$$$$$$$";
		hidePane();
	});
	
	$("body").click(function(event) {
		if (event.target.nodeName == "FORM") {
			hidePane();
		}
	});

	function hidePane() {
		dragFlag=false;
		$plus.hide();
	}
	
	function drag()
	{
		dragFlag=true;
	}
	
	var mGroupKeys="";
	
	var mGroupItems="";
	function frameGroupingItems(event)
	{
		var tempData=event.value;
		if(event.checked==true)
		{
			mGroupItems=mGroupItems+"$"+tempData;
		}
		else
		{
			var arr=mGroupItems.split("\\$");
			mGroupItems="";
			for(var i=0;i<arr.length;i++)
			{
				if(arr[i].length>1)
				{
					if(arr[i]==tempData)
					{
						
						
					}
					else
					{
						mGroupItems=mGroupItems+"$"+arr[i];
					}
				}
			
			}
		}
	}
	function frameGroupingKeys(event)
	{
		var tempData=event.value;
		
		if(event.checked==true)
		{
			mGroupKeys=mGroupKeys+"$"+tempData;
		}
		else
		{
			var arr=mGroupKeys.split("\\$");
			mGroupKeys="";
			for(var i=0;i<arr.length;i++)
			{
				if(arr[i].length>1)
				{
					
					if(arr[i]==tempData)
					{
						
						
					}
					else
					{
						mGroupKeys=mGroupKeys+"$"+arr[i];
					}
				}
			}
		}
	}
	
	$(document).ready(function() {
		
		$('.plus').draggable({
			cursor : 'move', // sets the cursor apperance
			opacity : 0.35, // opacity fo the element while it's dragged
			handle : '.row'
		});
		
		
	});
	
	$("#vanish").click(function(event) {
		$('#configurationform').html("");
		setTimeout("$('#myModal1').modal('hide');", 10000);
	});
	
	$("#clear").click(function(event) {
		$('#myModal1').modal('hide');
		$table.handsontable('clear');
		jsonData = {};
	});
	
 	function styleChengeEvent(){
 		
 		
 		 	if(sizeData!="" && sizeValue!="")
		 	{
			 	widthJsonData[c]=sizeValue;
						// alert(sizeData+"  change the width   "+sizeValue);
			 
		 	}
 		
			for ( var key in stylesJson) 
			{
				if (stylesJson.hasOwnProperty(key)) 
				{
					if (!(stylesJson[key] == "" || stylesJson[key] == null || stylesJson[key] == "null")) 
					{
						r=key.split("-")[0];
						c=key.split("-")[1];
						
						
						var styleData=stylesJson[key];
						var styleType=styleType=styleJsonObject[styleData];//$("#dataStyle option: contains(" + styleData + ")").val();
						var stylArray=styleType.split("$");
							
						
				        if($table.handsontable('getCell', r, c)!=null)
				        	$table.handsontable('getCell', r, c).removeAttribute("style");
				        
				        if(stylArray[0]!="") 
				        {
					        if($table.handsontable('getCell', r, c)!=null)
				        		$table.handsontable('getCell', r, c).style.color= stylArray[0];
				        }
				        if(stylArray[1]!=""){
					        if($table.handsontable('getCell', r, c)!=null)
				        		$table.handsontable('getCell', r, c).style.backgroundColor = stylArray[1];
				        }
				        if(stylArray[2]!=""){
					        if($table.handsontable('getCell', r, c)!=null)
					        	$table.handsontable('getCell', r, c).style.fontSize= stylArray[2];
				        }
				        if(stylArray[3]!="") {
					        if($table.handsontable('getCell', r, c)!=null)
					        	$table.handsontable('getCell', r, c).style.fontFamily = stylArray[3];
				        }
				        if(stylArray[4]!="") {
					        if($table.handsontable('getCell', r, c)!=null)
					        	$table.handsontable('getCell', r, c).style.textDecoration = stylArray[4];
				        }
				        if(stylArray[5]!="") {
					        if($table.handsontable('getCell', r, c)!=null)
					        	$table.handsontable('getCell', r, c).style.fontWeight = stylArray[5];
				        }
				        if(stylArray[6]!="") {
					        if($table.handsontable('getCell', r, c)!=null)
					        	$table.handsontable('getCell', r, c).style.fontStyle = stylArray[6];
				        }
				        if(stylArray[7]!="") {
					        if($table.handsontable('getCell', r, c)!=null)
					        	$table.handsontable('getCell', r, c).style.borderLeft = stylArray[7];
				        }
				        if(stylArray[8]!=""){
					        if($table.handsontable('getCell', r, c)!=null)
					        	$table.handsontable('getCell', r, c).style.borderRight = stylArray[8];
				        }
				        if(stylArray[9]!=""){
					        if($table.handsontable('getCell', r, c)!=null)
					        	$table.handsontable('getCell', r, c).style.borderTop = stylArray[9];
				        }
				        if(stylArray[10]!="") {
					        if($table.handsontable('getCell', r, c)!=null)
					        	$table.handsontable('getCell', r, c).style.borderBottom = stylArray[10];
				        }
				        if(stylArray[11]!="") {
					        if($table.handsontable('getCell', r, c)!=null)
					        	$table.handsontable('getCell', r, c).style.textAlign=stylArray[11];
				        }
				       // if($table.handsontable('getCell', r, c)!=null)
				       	 //	$table.handsontable('getCell', r, c).style.min-width=230px;
					}
				}
				
			}
			
			
	} 

	$("#confirm").click(function(event) {
		
		
		//alert("send width data are  "+JSON.stringify(widthJsonData));
		
		var output = "O";
		output += document.getElementById("result").value;
		if (!(output.length > 3))
		{
			alert("Please provide some inputs.");
			$('#myModal2').modal('hide');
		} 
		else if(jqueryFlag==-1)
		{
			if(JSON.stringify(stylesJson)=="{}")
			{
				var styleData=document.getElementById("styleData");
				styleData.value=" ";
			}
			else
			{
				var styleData=document.getElementById("styleData");
				styleData.value=JSON.stringify(stylesJson);
			}
			
			//alert("send width data are  "+JSON.stringify(widthJsonData));
			
			if(JSON.stringify(widthJsonData)=="{}")
			{
				var templateWidthData=document.getElementById("widthDataSend");
				templateWidthData.value=" ";
			}
			else
			{
				var templateWidthData=document.getElementById("widthDataSend");
				templateWidthData.value=JSON.stringify(widthJsonData);
			}
			
			
		 	var dataSender={};
		 	var newSelected="";
			for ( var key in ids) 
			{
				var selected=$('#'+key).data().bootstrapTransfer.get_values();
				for(var i=0; i < selected.length; i++) {
					newSelected+= selected[i].replace(/#/g, ' ')+"$";
					}
			}

			var groupItemsText=document.getElementById("groupItems");
			var groupingItems=document.getElementsByName("groupingItems");
			groupItemsText.value=mGroupItems;          //groupingItem;
		
			var groupKeysText=document.getElementById("groupKeys");   
			var groupingKeys=document.getElementsByName("groupingKeys");
			var groupingKey="";
			
			groupKeysText.value=mGroupKeys;           //groupingKey;
			var rs=document.getElementById("repomaps");
			   var mappings=document.getElementsByName("mapping");
			   var mapping="";
			   for(var i=0;i<mappings.length;i++)
			   {
			    if(mappings[i].checked==true)
			     {
			     mapping+=mappings[i].value+"$";
			     }
			   }
			   rs.value=mapping;
			var cons=document.getElementById("inputCons");
			cons.value=JSON.stringify(newSelected);
			$("#frm1").submit();
		}
		else 
		{
			if(JSON.stringify(stylesJson)=="{}")
			{
				var styleData=document.getElementById("styleData");
				styleData.value=" ";
			}
			else
			{
				var styleData=document.getElementById("styleData");
				styleData.value=JSON.stringify(stylesJson);
			}
			
			//alert("send width data are  "+JSON.stringify(widthJsonData));
			
			if(JSON.stringify(widthJsonData)=="{}")
			{
				var templateWidthData=document.getElementById("widthDataSend");
				templateWidthData.value=" ";
			}
			else
			{
				var templateWidthData=document.getElementById("widthDataSend");
				templateWidthData.value=JSON.stringify(widthJsonData);
			}
			
			
			var groupItemsText=document.getElementById("groupItems");   
			var groupingItems=document.getElementsByName("groupingItems");
			groupItemsText.value=mGroupItems;          //groupingItem;
			var groupKeysText=document.getElementById("groupKeys");   
			var groupingKeys=document.getElementsByName("groupingKeys");

			groupKeysText.value=mGroupKeys;          //groupingKey;
			$("#frm1").submit();
		}
	});

	var ids={};
	function selectId(event)
	{
		ids[event.id]="";
	}

	function clearRadio() {
		jobValues = document.getElementsByName("info");
		for ( var i = 0; i < jobValues.length; i++) {
			jobValues[i].checked = false;
		}
	}
	
	
	
	var jsonData = {};
	var stylesJson={};
	var styleJsonObject=<%=styleJsonObj%>;
	var widthJsonData={};
	$(document).ready(function() {
		stylesJson=frameStyles();
		widthJsonData=load_templateWidthData();
		var prev = {};
		jsonData=load_templateData();   // to load template data in jsonData
		styleChengeEvent();
		var JsonRes = document.getElementById("result");
		JsonRes.value=JSON.stringify(jsonData);  
		
		//alert(JsonRes.value);
		
		
		$("input[name=info]").click(function() {
			if (prev && prev.value == this.value) {
				$(this).prop('checked', !prev.status);
			}
			prev = {
				value : this.value,
				status : this.checked
			};
		});
	});
	
	function frameStyles()
	{
		 var stylesString ="<%=reportStyle%>"; 
			var styleDataz = {};
		
			if(stylesString!="null")
			{
				var dataarr=stylesString.split(",");
				if(dataarr.length>1)
				{
					for(var i=0;i<dataarr.length;i++)
					{
						var positionANDdata=dataarr[i].split(":");
						styleDataz[positionANDdata[0]]=positionANDdata[1];
					}
				}
			} 
			return styleDataz;
	}
	
	function load_templateData() {
		var dataz =<%=positions%>;
		var json = {};
		for ( var i = 0; i < dataz.length; i++) {
			for ( var j = 0; j < dataz[i].length; j++) {
				json[i + "-" + j] = dataz[i][j].trim();
			}
		}
		var sendJson = {};
		for ( var key in json) {
			if (json.hasOwnProperty(key)) {
				if (!(json[key] == "" || json[key] == null || json[key] == "null")) {
					sendJson[key] = json[key];
				}
			}
		}
		//alert(JSON.stringify(sendJson));
		return sendJson;
	}
	
	
	function load_templateWidthData() {
	  
	   var dataz ='<%=templateWidthData%>';
	   var widthDatazz={};
	  // alert(dataz); 
	   
	   if(dataz!="null")
		{
			var dataarr=dataz.split(",");
			if(dataarr.length>1)
			{
				for(var i=0;i<dataarr.length;i++)
				{
					var positionANDwidth=dataarr[i].split(":");
					widthDatazz[positionANDwidth[0]]=positionANDwidth[1];
				}
			}
		} 
	   
		//alert(JSON.stringify(widthDatazz)); 
		return widthDatazz;
	}

	function change_events(event, data) {

		var changeddata = JSON.stringify(data[0][0]);
		changeddata = changeddata.replace(new RegExp(
			    "[^a-zA-Z,0-9,' ','.','&','@',':','-','(',')','/','=','+','_','*',',',':']", "g"), "");
		var str = changeddata.split(',');
		jsonData[str[0].replace("[", "") + "-" + str[1].trim()] = str[3].trim()
				.replace("]", "");
		var res = document.getElementById("result");
		var sendData = {};
		
		var r=str[0].replace("[", "");
		var c=str[1].trim();
		
		
		
				 
		
		for ( var keyD in jsonData) {
			if (jsonData.hasOwnProperty(keyD)) {
				if (!(jsonData[keyD] == "" || jsonData[keyD] == null || jsonData[keyD] == "null")) {
					sendData[keyD] = jsonData[keyD];
					
					var styleType=document.getElementById("dataStyle").value;
			        var stylArray=styleType.split("$");
			        if($table.handsontable('getCell', r, c)!=null)
			        	$table.handsontable('getCell', r, c).removeAttribute("style");
			        
			        if(stylArray[0]!=""){
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.color= stylArray[0];
			        }
			        if(stylArray[1]!=""){
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.backgroundColor = stylArray[1];
			        }
			        if(stylArray[2]!=""){
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.fontSize= stylArray[2];
			        }
			        if(stylArray[3]!=""){
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.fontFamily = stylArray[3];
			        }
			        if(stylArray[4]!=""){
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.textDecoration = stylArray[4];
			        }
			        if(stylArray[5]!="") {
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.fontWeight = stylArray[5];
			        }
			        if(stylArray[6]!="") {
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.fontStyle = stylArray[6];
			        }
			        if(stylArray[7]!="") {
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.borderLeft = stylArray[7];
			        }
			        if(stylArray[8]!="") {
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.borderRight = stylArray[8];
			        }
			        if(stylArray[9]!="") {
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.borderTop = stylArray[9];
			        }
			        if(stylArray[10]!="") {
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.borderBottom = stylArray[10]; 
			        }
			        if(stylArray[11]!="") {
			        	if($table.handsontable('getCell', r, c)!=null)
			        		$table.handsontable('getCell', r, c).style.textAlign=stylArray[11];
			        }
			        stylesJson[r+"-"+c]=$("#dataStyle option:selected").text();
			        
			        if(sizeData!="" && sizeValue!="")
					{
						 widthJsonData[c]=sizeValue;
					 }
			        

				}else{
					stylesJson[keyD]="DEFAULT";
				}
			}
		}
		res.value = JSON.stringify(sendData);
	}

	var jqueryFlag;
	
	var sizeData="";
	var sizeValue="";
	function selectedSize(e)
	{
		if(e.checked==true)
		{
			sizeData=true;
		}
		else
		{
			sizeData="";
			sizeValue="";
		}
		
		
	}

**Comment by AMBudnik** [comment]
Unfortunately issue as to be closed in lack of demo for a long time now. If you would have time to prepare one, please reply and we'll reopen your issue.
