### ISSUE TITLE
[Bug]: if I move some rows,orther use this cells to make formula,they will change,but you cannot catch this change. for example，I make a formula（=A1） in B3,and A1 is number 5,if I move first row from index 1 to index 2,the formula belong to B3 have a change,(=A2),I cannot catch this change，What I mean is that there may be multiple references to this cell, and I cannot record all of them and search for their new formulas in afterRowMove

### ISSUE THREAD

**Issue by yanyinqing** [handsontable/handsontable#10695]
### Describe the bug

if I move some rows,orther use this cells to make formula,they will change,but you cannot catch this change.
for example，I make a formula（=A1） in B3,and A1 is number 5,if I move first row from index 1 to index 2,the formula belong to B3 have a change,(=A2),I cannot catch this change，What I mean is that there may be multiple references to this cell, and I cannot record all of them and search for their new formulas in afterRowMove

### Handsontable version

14.0.0

### Framework version

vue2

### Your environment

edge,macos

**Comment by adrianszymanski89** [comment]
Hi @yanyinqing 

We already have this problem reported by you here: https://github.com/handsontable/handsontable/issues/10691 I'm closing this one as a duplicate.
