### ISSUE TITLE
[Bug]: When using filters, the error "radioInput.mjs:81 Uncaught TypeError: Cannot read properties of undefined (reading 'checked')" is displayed.

### ISSUE THREAD

**Issue by heshaui** [handsontable/handsontable#10703]
### Describe the bug

When using filters in Vue 2, the error occurs when clicking the "OK" button on the filter list, as shown in the screenshot below.

### Video/Screenshots

![image](https://github.com/handsontable/handsontable/assets/21079397/f116ffe3-6d14-4bc8-a896-09e90632b2a9)
![image](https://github.com/handsontable/handsontable/assets/21079397/d7889386-aa8b-4cf1-8f48-609200c02912)
![image](https://github.com/handsontable/handsontable/assets/21079397/07cf9f62-55d0-47e0-8944-2b7efe652db5)

### Handsontable version

14.0.0

### Your environment

macOS12.1.1、Chrome120.0.6099.129

**Comment by adrianszymanski89** [comment]
Hi @heshaui 

Thank you for contacting us. I can see that you closed this issue. Does that mean that you've found the solution?
