### ISSUE TITLE
Autocomplete renderer title text on hover leaking out to non-autocomplete cells

### ISSUE THREAD

**Issue by edallen** [handsontable/handsontable#1071]
In tables with a lot of columns, some of columns using an autocomplete renderer copied from your example, we are seeing the td.title message 'Type to show the list of options' and its hover behavior to display the title text being applied inappropriately to some other columns that do not have the autorender_type(). These columns with inappropriate hover text do not get the italic font style, so however it is happening, it is only leaking the title attribute being set on the td. 

We see this in Handsontable 0.9.6 and handsontable 0.9.18 with jQuery 1.7.2 (on our todo list to update the jQuery).

I will try to set up a JsFiddle to demo this bug based on our code.

**Comment by AMBudnik** [comment]
I assume that if you didn't prepare this demo, everything's working as expected. If I'm wrong, please provide a demo.
