### ISSUE TITLE
[Bug]: It seems like the 'select cell type' is not working. Is there an issue with my implementation? Please see the screenshot below."An error occurred, causing no content to be displayed.

### ISSUE THREAD

**Issue by yanyinqing** [handsontable/handsontable#10714]
### Describe the bug

It seems like the 'select cell type' is not working. Is there an issue with my implementation? Please see the screenshot below."An error occurred, causing no content to be displayed.

### Video/Screenshots

<img width="831" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/20cb993a-ddae-4a0b-bb84-c7e4c1989dcb">
<img width="853" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/6d2c700a-4c82-427a-832e-6ebebf8cc740">

### Handsontable version

14.0.0

### Framework version

vue2

### Your environment

edge,macos

**Comment by AMBudnik** [comment]
Hi @yanyinqing 

Maybe there's a typo or an incorrect placement of the code. Here's an example https://jsfiddle.net/w5ys2k1h/ for `select` cell type and Vue2 implementation.

**Comment by AMBudnik** [comment]
Hi @yanyinqing 

There are no updates, so I believe this issue is no longer replicable.

But if that's not the case please contact us at support@handsontable.com
