### ISSUE TITLE
[Bug]: Is it not possible to use column filters in VUE? I have tried both versions 14.0.0 and 13.0.0 of Handsontable, but it doesn't work. The code and the result are as follows, and the result is the same for both versions, with no content displayed

### ISSUE THREAD

**Issue by yanyinqing** [handsontable/handsontable#10713]
### Describe the bug

Is it not possible to use column filters in VUE? I have tried both versions 14.0.0 and 13.0.0 of Handsontable, but it doesn't work. The code and the result are as follows, and the result is the same for both versions, with no content displayed

### Video/Screenshots

<img width="864" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/7c418cc3-c35e-4730-b76b-db692a6ab425">
<img width="654" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/3a77a603-4cfd-47ee-a7c8-9a3ee98681a4">

### Handsontable version

14.0.0,13.0.0

### Framework version

vue2

### Your environment

edge,macos

**Comment by adrianszymanski89** [comment]
Hi @yanyinqing 

Please add the title to the issue. It's already reported and fixed and will be available with the next release. Here's another issue mentioning this: https://github.com/handsontable/handsontable/issues/10711

**Comment by AMBudnik** [comment]
Hi @yanyinqing 

I have good news. We just released v14.1.0, where this issue is fixed. 

Here is a full list of changes that we introduced and issues that were fixed https://handsontable.com/blog/handsontable-14-1-0-typescript-ssr-improvements
