### ISSUE TITLE
[Bug]: Index.d.ts does not export HotTableClass thus breaking React refs

### ISSUE THREAD

**Issue by MattChowski** [handsontable/handsontable#10736]
### Describe the bug

Hey all, 

I wanted to use refs to access the instance of the HotTable, however, for Typescript to work, I need the HotTableClass inside `useRef<HotTableClass | null>(null)` in order to have everything typed correctly. Currently the `index.d.ts` file does not export HotTableClass and this feels like a missed/forgotten export by mistake.

When trying to access the `hotInstance` of the `current` ref property this is what I get for the lack of typing added to useRef: 

<img width="651" alt="image" src="https://github.com/handsontable/handsontable/assets/32590025/eb479b75-8304-4645-a104-93f77563c8a0">

This is the current `index.d.ts` in the latest version

```export * from './hotColumn';
export * from './hotTable';
export * from './types';
export * from './baseEditorComponent';
export { default } from './hotTable';
```

expected:

```export * from './hotColumn';
export * from './hotTable';
export * from './hotTableClass';
export * from './types';
export * from './baseEditorComponent';
export { default } from './hotTable';
```

### **Current workaround:**

Add type like this: `import { HotTableClass } from "@handsontable//react/hotTableClass";`, note the double slashes which look ugly

Thank you in advance for any clarification/suggestion

### Handsontable version

14.1.0

### Your environment

Chrome

**Comment by evanSe** [comment]
Thanks for reporting @MattChowski,  I will look at this.

**Comment by evanSe** [comment]
This will be resolved with our next release, I will let you know when that happens.

**Comment by henriq-88** [comment]
@adrianszymanski89 The type issue still occurs as of 14.2.0

<img width="569" alt="image" src="https://github.com/handsontable/handsontable/assets/825330/d36d0849-8450-4295-81c5-21e67c12b824">
<img width="351" alt="image" src="https://github.com/handsontable/handsontable/assets/825330/9cf1bdcb-2e67-4701-9bac-70789fd7b439">
<img width="298" alt="image" src="https://github.com/handsontable/handsontable/assets/825330/06b7a9fb-6c34-4997-8ae7-3f2b875f2fd2">
