### ISSUE TITLE
[Bug]:  Cannot move multi columns which are selected by `ctrl + click` 

### ISSUE THREAD

**Issue by SunXinZH** [handsontable/handsontable#10740]
### Describe the bug

If the `manualColumnMove` configuration option to true , moving multi columns is supported.

When the consecutive columns are selected by  `ctrl + click`,  only one column can be moved.  

# Moving columns selected by `ctrl + click`

![db92cdf555861619c522168173715328](https://github.com/handsontable/handsontable/assets/124127990/96eb2668-081c-4d58-a8bf-c7a4f156f503)

# Moving columns selected by `shift + click`

![481df6aeec3a1d09b69df866035805bc](https://github.com/handsontable/handsontable/assets/124127990/fd5a1c05-8ffc-4b1c-bc9d-dd3c64ffc08c)

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/api/post/library/pure/

### Handsontable version

14.1.0

### Your environment

chrome

**Comment by AMBudnik** [comment]
Hi @SunXinZH 

Thank you for describing the case.

Selecting columns with `SHIFT` triggers the non-consecutive cell selection, which is not yet supported by the `manualColumnMove` plugin. But the same goes for CMD/CTRL. We can test this in the demo https://jsfiddle.net/jot3a605/. Once you see that there is a second selection added, only the last one will take part in the `manualColumnMove` action.
