### ISSUE TITLE
[Bug]: When there are many options, there is a bug when filtering in the drop-down menu.

### ISSUE THREAD

**Issue by XJQX6676** [handsontable/handsontable#10741]
### Describe the bug

When I filter options with relatively large values, the drop-down box cannot locate the option.

![4](https://github.com/handsontable/handsontable/assets/34090735/d05900fe-e98b-49ac-95f6-24cebc5fec06)

### Video/Screenshots

![1](https://github.com/handsontable/handsontable/assets/34090735/4541f128-13aa-4325-9be1-7b10de7f884c)
![2](https://github.com/handsontable/handsontable/assets/34090735/e5a96c08-1148-477d-8fe7-4ce3d96d2079)

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/1ayzr3wt/

### Handsontable version

14.1.0

### Your environment

Windows 11, Edge

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report. It seems that it **is only replicable on Edge on Windows**. I tested the combination of Chrome, Safari, Firefox, and Edge on macOS Ventura and virtual Windows 11. That is an interesting case.

I will notify you as soon as we fix it.

**Comment by AMBudnik** [comment]
I did a bit more research, and it seems that the browser does not matter, but the size of the window does. The bigger the height of the window, the larger the list can be. This issue is a regression, it was introduced in v14.0.0.

**Comment by AMBudnik** [comment]
Hi @XJQX6676 

We just released Handsontable v14.2.0, where this pull request https://github.com/handsontable/handsontable/pull/10763 solves the issue that you reported.

Thank you again for reporting. I hope it will work well in your project.
