### ISSUE TITLE
[Bug]: Unable to pass "type" to a HotColumn component in react.

### ISSUE THREAD

**Issue by warrenday** [handsontable/handsontable#10747]
### Describe the bug

Following a basic example I am unable to pass "type" to a HotColumn component without an error throwing:

```
Error: You declared cell type "numeric" as a string that is not mapped to a known object.
                 Cell type must be an object or a string mapped to an object registered by
                 "Handsontable.cellTypes.registerCellType" method
```

This is the basic example which causes the error:

```js
import React from 'react'
import { HotTable, HotColumn } from '@handsontable/react'
import 'handsontable/dist/handsontable.min.css'

const TestExample = () => {
  const settings = {
    data: [
      [1, '#ff6900', '#fcb900'],
      [2, '#fcb900', '#7bdcb5'],
      [3, '#7bdcb5', '#8ed1fc'],
      [4, '#00d084', '#0693e3'],
      [5, '#eb144c', '#abb8c3'],
    ],
    rowHeaders: true,
    rowHeights: 30,
    colHeaders: ['Rating', 'Active star color', 'Inactive star color'],
    licenseKey: 'non-commercial-and-evaluation',
  }

  return (
    <HotTable settings={settings}>
      <HotColumn width={100} type={'numeric'} />
    </HotTable>
  )
}

export default TestExample
```

Removing `type` from `HotColumn` removes the error, but then I cannot specify the field type.

### Video/Screenshots

<img width="1018" alt="Screenshot 2024-01-24 at 11 01 59" src="https://github.com/handsontable/handsontable/assets/2871038/54c651e0-17dc-4e8c-98a7-6c5a80cedf9e">

### Provide a link to the demo with the bug reproduction

https://codesandbox.io/p/sandbox/fervent-jasper-dydj4k

### Handsontable version

13.1.0

### Framework version

NextJS 13

### Your environment

Chrome - Mac

**Comment by haxshith** [comment]
can you please assign me this issue

**Comment by warrenday** [comment]
Would also mention the example does work, but with a much older version, from your official docs:
https://codesandbox.io/p/sandbox/advanced-handsontablereact-implementation-using-hotcolumn-878mz?file=%2Fsrc%2Findex.js%3A1%2C1-61%2C1

**Comment by haxshith** [comment]
hey I think I fixed the table code which was the first problem

**Comment by adrianszymanski89** [comment]
Hi @warrenday 

The issue was that you needed to register the modules necessary for the table to function correctly. Here's a working example: https://codesandbox.io/p/sandbox/mutable-forest-dk5tqy?file=%2Fsrc%2FTable.js

And here's the missing code:

> import { registerAllModules } from 'handsontable/registry';
> 
> // register Handsontable's modules
> registerAllModules();

**Comment by warrenday** [comment]
@adrianszymanski89 thank you! Apologies I missed that part.
