### ISSUE TITLE
Horizontal Scrollbar generated when unnecessary, in v0.9.18 and later

### ISSUE THREAD

**Issue by amclin** [handsontable/handsontable#1074]
"Single Scrollbar" example is broken in Chrome with v 0.9.18 and later.

http://handsontable.com/demo/scroll.html

#### Expected result:
Single Scrollbar example should only generate a visible vertical scrollbar (0.9.17 behavior).

#### Actual result:
Single Scrollbar example generates unnecessary horizontal scrollbar with invalid relative size indicator.

**Comment by AMBudnik** [comment]
Please track this subject in #1079 issue.
