### ISSUE TITLE
[Bug]: Custom border misaligns rows

### ISSUE THREAD

**Issue by conschtek** [handsontable/handsontable#10751]
### Describe the bug

Hi,

I'm using the search plugin's custom search results class, where I make the border of the cell 1px. However if in a column there are multiple search results the table's rows are misaligned. To best display my issue, I added the row headers to the example.
I've might have found a similar issue already reported: #3215

### Video/Screenshots

<img width="278" alt="image" src="https://github.com/handsontable/handsontable/assets/117377149/bde4ce9b-13a2-4bc8-b3cf-a38117f12055">

As the screenshot shows, the rows are misaligned in comparison to the row headers, and the further you're scrolling down the bigger the misalignment.

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/s0uzvc3w/15/

### Handsontable version

12.3.1

### Your environment

Browser: Chrome

**Comment by adrianszymanski89** [comment]
Hi @conschtek 

Yes, the source of this problem is the same as in the issue you mentioned. We have plans to rebuild the table's dimension calculating system, which should solve all those problems. We have yet to set a specific timeline for this project, but it should happen this year.

**Comment by conschtek** [comment]
Hi @adrianszymanski89 
Thank you for your quick response! I'm happy to hear that there are already plans to solve this issue.

**Comment by AMBudnik** [comment]
Hi @conschtek, Till the issue is fixed, I can recommend using `box-shadow` with `inset` value instead of a `border`. That should bring a similar UX. Here's a demo https://jsfiddle.net/kv597g6a/1/ and a result


![Zrzut ekranu 2024-02-2 o 11 52 24](https://github.com/handsontable/handsontable/assets/10757813/ca912e5a-f5d1-4f04-bc22-3ab0f92245d9)

**Comment by conschtek** [comment]
Hi @AMBudnik 
thank you for your response! That is a great workaround, thank you for sharing!
