### ISSUE TITLE
[Bug]: When first cell of selection is a checkbox, it prevents BACKSPACE or DELETE buttons actions

### ISSUE THREAD

**Issue by fernandoalex-edv** [handsontable/handsontable#10757]
### Describe the bug

If the checkbox is the first cell of a row, or the first cell of selected cells in a row, then the DELETE and BACKSPACE actions are ignored. I tried several hooks, but no one is triggered.

![image](https://github.com/handsontable/handsontable/assets/78549025/9e2bd9b9-5322-4ef9-ba7d-533ffda0dda8)

It's the same error related at this Issue here, from more than one year before, without fix yet
https://github.com/handsontable/handsontable/issues/9687

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/qkdfrnL7/

### Handsontable version

14.1

### Your environment

Chrome or Edge

**Comment by adrianszymanski89** [comment]
Hi @fernandoalex-edv 

Yes, that's the same issue, and as you mentioned, it's already reported, so I have to close this one as a duplicate. 

We focused on other big projects for the last year, so this issue hasn't gotten on our roadmap yet. We will update the original issue once it is fixed.

**Comment by AMBudnik** [comment]
Hi @fernandoalex-edv 👋 

Please check Handsontable **v14.6.0** (released today). 

We fixed that issue. Here https://jsfiddle.net/of32c84a/ you can test it and read more about the changes at https://handsontable.com/docs/react-data-grid/changelog/
