### ISSUE TITLE
Getting too many exceptions: 

### ISSUE THREAD

**Issue by singhalavi** [handsontable/handsontable#1076]
throw new Error('row ' + coords[0] + ' does not exist');

above exception is thrown when i try to select cell in the bottom most row. it is coming when i am trying to use 0.9.18, it was not coming in earlier version 0.8.23.

I see that parentCell method is selecting the wrong cell, dont know why.

**Comment by krzysztofspilka** [comment]
We didn't get any further questions, i'm closing this issue.
