### ISSUE TITLE
[Bug]: Different scrolling experience with scrollbar vs. with touchpad

### ISSUE THREAD

**Issue by conschtek** [handsontable/handsontable#10772]
### Describe the bug

Hi,
I would like to report an issue regarding the scrolling. As the video shows, scrolling a large table with the touchpad behaves completely normal, no lagging or jumping. However when I try to scroll via the scrollbar by dragging and scrolling it lags/rendering seems to be slow. Sometimes it results in an endless scroll where I cannot even reach the last column/row.

The video was created using the example of the column virtualization (https://handsontable.com/docs/javascript-data-grid/column-virtualization/?pageId=xv8sf6at). I could not recreate the issue when row/column virtualization was disabled.

### Video/Screenshots

https://github.com/handsontable/handsontable/assets/117377149/246b8b98-bade-4b07-acd6-581391906138

### Handsontable version

14.1

### Your environment

macOS and Chrome

**Comment by adrianszymanski89** [comment]
Hi @conschtek 

Thank you for contacting us. I think it works as it's supposed to. One thing is that you tested it in an embedded form in our documentation, which impacts the performance. If you open the example in a new tab, it will run much smoother. 

The second thing is that touchpad scrolling is always smoother and slightly slower than a scrollbar. Doing that with a scrollbar means you are scrolling through thousands of rows quickly, so it takes a little longer to render them.
