### ISSUE TITLE
[Bug]: Display Issues with `nestedRows` and `nestedHeaders` Options Enabled in Table

### ISSUE THREAD

**Issue by dhgoal** [handsontable/handsontable#10823]
### Describe the bug

![bug1](https://github.com/handsontable/handsontable/assets/153369624/955fd235-93f2-431a-bcdd-4132e4a8aa39)

Here is my options for HotTable. There are about only 100 rows and 20 columns. And I enabled **nestedRows** and **nestedHeaders** together. I checked in both Chrome and Firefox but the result was same.

![code](https://github.com/handsontable/handsontable/assets/153369624/4c08c5e8-eb6f-409c-a7d7-c19b447bb48c)

### Handsontable version

14.1

### Your environment

Browser: Chrome & Firefox / OS: Windows 10

**Comment by dhgoal** [comment]
I am using HotTable in my react application.
Once I changed the code (commented to the `height` option), the table was working correctly. As you know, without refresh, react applications are changed automatically for code changing. If I refresh the page, it didn't work correctly.

**Comment by AMBudnik** [comment]
Hi @dhgoal 

It would be hard to help without a demo so I created one based on your settings in React 18 and newest Handsontable at https://stackblitz.com/edit/vitejs-vite-f6z2kh?file=src%2FApp.jsx&terminal=dev

However, it does not seem to cause any issues. Could you please add the missing variables so we can have the same table structure as in your project?

**Comment by dhgoal** [comment]
This is my code file.
[Dashboard.zip](https://github.com/handsontable/handsontable/files/14418333/Dashboard.zip)

**Comment by dhgoal** [comment]
There are 9 parent rows and if I randomly collapse 7 rows, it works fine.

**Comment by AMBudnik** [comment]
Thank you for providing the code. I spaced that in the demo https://stackblitz.com/edit/vitejs-vite-fthxlp?file=src%2FApp.jsx&terminal=dev

Please tell me what the exact steps are to replicate the issue. I tried collapsing row and column headers, and it works fine. I am testing it on Chrome 121 macOs Ventura.

**Comment by dhgoal** [comment]
Thank you for your kind reply.
I just cloned project to my local and tested. But the result was same.
![bug1](https://github.com/handsontable/handsontable/assets/153369624/2271adef-e1db-4729-a7b6-dc2eae0eca24)
![bug2](https://github.com/handsontable/handsontable/assets/153369624/c306b3bd-79aa-4fe2-aed2-01d1f1ab59c5)

**Comment by AMBudnik** [comment]
Hm... I tested the same demo on Chrome 122/Win 10 on BrowserStack with 100% zoom, 80%, and 110% (as sometimes zoom may cause different visual issues), but everything works well.

Could you check if you have 
* any other browser settings on
* a system scale
* does it work for you on other browsers

![windows-check](https://github.com/handsontable/handsontable/assets/10757813/1f78d895-21cd-4c54-840d-7d18227b7b49)

**Comment by dhgoal** [comment]
Could you please share the whole project?

**Comment by dhgoal** [comment]
In your gif file, all rows are collapsed and just one is expanded. In that case, it works well in my side. But if all the rows are expanded, the table is not displayed correctly. I can't see few data and also scroll is not working.

**Comment by AMBudnik** [comment]
Hi again @dhgoal I checked the issues in our internal board and it seems that it is related to the issue - `preventOverflow` with constant `height` and when we change `height` to `auto` and remove `preventOverflow` the bug is not replicable.

I will inform you as soon as we fix this issue.

**Comment by dhgoal** [comment]
Thanks. Please let me know how to fix the issue.
