### ISSUE TITLE
[Bug]: "mergedHotSettings" Error reporting！

### ISSUE THREAD

**Issue by yanyinqing** [handsontable/handsontable#10824]
### Describe the bug

If I use both Formulas and MergeCells at the same time, this error message will appear. I encountered it after updating to 14.1.0，It is normal to use them separately，Then if I ignore this error and continue to click on the cell for editing, the cell will freeze for a period of time after losing focus

### Video/Screenshots

<img width="761" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/97262a1c-60a4-4a5f-8b8f-18a6396af63b">
<img width="274" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/03254c0a-2b97-483f-90b8-af545d056739">
<img width="556" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/77b0232f-d2a1-44b9-917f-1e445e21b8e4">
<img width="871" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/e26f69e8-d379-46c7-adc3-ae2a81485119">

### Handsontable version

14.1.0

### Framework version

vue2

### Your environment

edge,macos

**Comment by yanyinqing** [comment]
You can skip this error message through this code, but I'm not sure what this code does
<img width="1109" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/193122af-a865-4112-8ab1-94b1f4facd88">
<img width="791" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/d3f06418-2e08-4789-8a83-dcc9bdac9dbe">

**Comment by adrianszymanski89** [comment]
Hi @yanyinqing 

Thank you for reporting this. I can confirm that this issue occurs, but only with the Vue wrapper. I'll report this internally for further investigation, but can you please tell me which previous Handsontable version worked correctly for you?

**Comment by yanyinqing** [comment]
> 你好
> 
> 感谢您报告此事。我可以确认出现此问题，但仅限于 Vue 包装器。我会在内部报告此事以进行进一步调查，但您能告诉我哪个以前的Handsontable版本适合您吗？
In the same situation, there were also multiple errors in the previous v14.0.0 version, which were different from v14.1.0 and did not affect normal use. However, when I updated to v14.1.0, the previous version's error disappeared and replaced it with the current "mergedHotSettings" error, which affected usage

**Comment by yanyinqing** [comment]
> 你好
> 
> 感谢您报告此事。我可以确认出现此问题，但仅限于 Vue 包装器。我会在内部报告此事以进行进一步调查，但您能告诉我哪个以前的Handsontable版本适合您吗？

In the same situation, there were also multiple errors in the previous v14.0.0 version, which were different from v14.1.0 and did not affect normal use. However, when I updated to v14.1.0, the previous version's error disappeared and replaced it with the current "mergedHotSettings" error, which affected usage

**Comment by adrianszymanski89** [comment]
Hi @yanyinqing 

We are happy to announce that this issue has been solved in the latest release with version 14.3.0. Please, let us know if that helped.
