### ISSUE TITLE
wrong highlighting of invalid fields when many columns display the same data

### ISSUE THREAD

**Issue by LukaszWiktor** [handsontable/handsontable#1082]
The table includes 2 or more columns displaying the same property (for example in different formats). When you enter an invalid value to a cell from one of these columns then only the last cell from the group is being highlighted red.

Steps to reproduce:
- open the [Numeric cell type](http://handsontable.com/demo/numeric.html) demo
- select  any cell in the "Price ($)" column
- enter some non-numeric value, let's say: "abc" and confirm (press enter key)
- result: cell on the right became red but not the cell you've edited

Version: 0.9.19

![image](https://f.cloud.github.com/assets/2964543/1267956/d94aad78-2cd1-11e3-9ea0-d1987e5011cb.png)

**Comment by krzysztofspilka** [comment]
@LukaszWiktor thanks for reporting, this was fixed a long ago. Sorry for letting you know that late and thanks for contributing:)
