### ISSUE TITLE
[Bug]: In the demo code for Instance methods, hotInstance is not available when using typescript.

### ISSUE THREAD

**Issue by Dephie** [handsontable/handsontable#10867]
### Describe the bug

In the demo code for Instance methods, hotInstance is not available when using typescript,The type declaration of useRef is unknown.

### Video/Screenshots

![微信图片_20240323164528](https://github.com/handsontable/handsontable/assets/128899536/2b4a0328-8596-4f03-b114-e169d820ccc8)

### Provide a link to the demo with the bug reproduction

https://handsontable.com/docs/react-data-grid/instance-methods/

### Handsontable version

14.2.0

### Your environment

windows 11 and Google Chrome

**Comment by adrianszymanski89** [comment]
Hi @Dephie 

Thank you for reporting this. We are aware of this issue and currently investigating the reason for this error. I will update you as soon as I have more information.

**Comment by adrianszymanski89** [comment]
Hi @Dephie 

We identified the problem. It was due to changes in our React wrapper introduced in v. 14.1.0. Since then, the hotInstance reference type has been stored independently as HotTableClass, which should be passed as the correct type to the useRef hook. Here's a proper import and usage:

> import { HotTableClass } from "@handsontable//react/hotTableClass";
> 
> const hotTableComponentRef = useRef<HotTableClass>();
