### ISSUE TITLE
[Bug]: renderer function execution time?

### ISSUE THREAD

**Issue by zhongguodong** [handsontable/handsontable#10864]
### Describe the bug

I simply show the data row by column, the renderer function was executed 5 times at the beginning of loading, I modified the cell data, and executed 3 times, what is the principle of this?
![image](https://github.com/handsontable/handsontable/assets/10219953/ef414f67-e6b9-47f9-b458-1115dca11e08)

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/zhongguodong/5fL2yxba/111/

### Handsontable version

14.2

### Your environment

windows 10 and Google Chrome

**Comment by AMBudnik** [comment]
Hi @zhongguodong 

Attaching a cell renderer causes more rendering cycles. Here https://jsfiddle.net/qcgej4y2/ we have added the `afterRender` (who table hook) and `afterRenderer` (cell hook) to show how it works without the custom cell renderer.

Plus, each time when you select a cell or table has to rerender to draw the selection. The same goes with the cell editor.

**Comment by adrianszymanski89** [comment]
Issue closed due to inactivity.
