### ISSUE TITLE
[Bug]: rowHeaders insert row above bug

### ISSUE THREAD

**Issue by zhongguodong** [handsontable/handsontable#10868]
### Describe the bug

Right click on the top of the line header to insert a horizontal scroll bar and scroll to the far right. If you right-click on the cell, click on the top to insert a row, but normal.

### Video/Screenshots

https://github.com/handsontable/handsontable/assets/10219953/b478a833-cdc6-45fb-b49c-9a480b71a76f

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/zhongguodong/zv09fyrp/

### Handsontable version

14.2

### Your environment

Chrome,Windows 10

**Comment by adrianszymanski89** [comment]
Hi @zhongguodong 

Thank you for reporting this. We will take a close look at this issue to determine if that's a desired change or if it's a regression. I will update you when I have more information.

**Comment by zhongguodong** [comment]
Hi @adrianszymanski89 
This is obviously a bug, if you look carefully, select a row (do not select the cell), then insert a row up, if there is a horizontal scroll bar, it will automatically scroll to the last column. If you insert a line down, it won't.

**Comment by adrianszymanski89** [comment]
Hi @zhongguodong 

I understand, but as we made numerous changes with v. 14.0 to meet the requirement for accessibility, we need to check if altering this behavior won't break anything.

**Comment by adrianszymanski89** [comment]
Hi @zhongguodong 

I have good news. This issue is already fixed in v. 14.3.0: https://jsfiddle.net/handsoncode/ypf3boz7/

**Comment by adrianszymanski89** [comment]
Hi, @zhongguodong. I am happy to announce that this issue is fixed in v14.4.0.

Related pull request: https://github.com/handsontable/handsontable/pull/10964

Release notes: https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-4-0

Thank you again for sharing the report!
