### ISSUE TITLE
[Bug]: The 'core.spliceRow' method threw an exception

### ISSUE THREAD

**Issue by yanyinqing** [handsontable/handsontable#10860]
### Describe the bug

I want to customize the operation of 'contextMenu' and insert a new row by distinguishing events in different situations in 'submenu'. Perhaps my usage is incorrect. I am able to obtain the 'spliceRow' method, but it may throw an exception that prevents it from being used

### Video/Screenshots

<img width="686" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/9145ad74-27af-4828-bc33-6fd6970d632b">
<img width="915" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/9fff29da-08c4-46ec-b8c0-da33718e745e">
<img width="513" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/997b3cf3-6b8c-4450-96a9-a94fcf4c38c9">
<img width="783" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/ffa48885-1e4c-4e75-ad71-4c396e45a4ee">

### Handsontable version

14.0.0

### Framework version

vue2

### Your environment

macos,edge

**Comment by adrianszymanski89** [comment]
Hi @yanyinqing 

Have you already solved this problem? Because I can see that you closed this issue.

**Comment by yanyinqing** [comment]
> Hi @yanyinqing
> 
> Have you already solved this problem? Because I can see that you closed this issue.

I have taken a look at your source code and it appears that inserting a line normally would result in another function. However, this function may not be suitable for my requirements, so I have stopped using it

**Comment by adrianszymanski89** [comment]
I understand. Thank you for the update. If you would need help with anything else, let me know.
