### ISSUE TITLE
[Bug]: vue2 insert column disable?

### ISSUE THREAD

**Issue by zhongguodong** [handsontable/handsontable#10881]
### Describe the bug

Why is insert column left disabled when I right-click a menu option in Array of objects mode?

### Video/Screenshots

![image](https://github.com/handsontable/handsontable/assets/10219953/8f7b2370-686a-4f99-83d6-af6dee801094)

### Handsontable version

14.2

### Your environment

Chrome,Windows 10

**Comment by AMBudnik** [comment]
Hi @zhongguodong 

When you are using an object-based dataset or/and `columns` options the column addition is disabled. That option in the menu uses [the `alter()` method](https://handsontable.com/docs/react-data-grid/api/core/#alter) underneath.

![Zrzut ekranu 2024-03-29 o 08 56 37](https://github.com/handsontable/handsontable/assets/10757813/27ea8b91-505f-4bf0-9dda-522f1f070382)

To allow users to add a new column, you would need to create you own custom demo option. Here https://handsontable.com/docs/react-data-grid/context-menu/#context-menu-with-a-fully-custom-configuration you can find an example of a custom context menu.

**Comment by AMBudnik** [comment]
Yes, that is correct @zhongguodong . Within your custom menu you would need to create an option that is altering the dataset with a new column.

**Comment by zhongguodong** [comment]
@AMBudnik Array of arrays mode, the menu inside the addition of columns can be. How does this work?

**Comment by AMBudnik** [comment]
If the dataset is an array of arrays you do not need to create a custom menu - the `alter()` method will allow you to remove/add columns.
