### ISSUE TITLE
How can i get the older version document, such as v6,v7?

### ISSUE THREAD

**Issue by yinyihui** [handsontable/handsontable#10882]
### Improvement description

These days, I find out the older version documents were redirect to the latest verion, how can i get the older version documents?Thanks!

**Comment by AMBudnik** [comment]
Hi @yinyihui 

Based on some internal agreements, we have removed older documentation pages, so the only way to check what was on them is to use websites that store the page status - like the Wayback Machine (https://web.archive.org/web/*/https://handsontable.com/docs/7.0*). 

You can also use GitHub releases tab to check differences between the version
* v6 https://github.com/handsontable/handsontable/releases/tag/6.0.0
* v7 ([CE version](https://handsontable.com/blog/handsontable-drops-open-source-for-a-non-commercial-license)) - https://github.com/handsontable/handsontable/releases/tag/7.0.0

**Comment by yinyihui** [comment]
> Hi @yinyihui
> 
> Based on some internal agreements, we have removed older documentation pages, so the only way to check what was on them is to use websites that store the page status - like the Wayback Machine (https://web.archive.org/web/*/https://handsontable.com/docs/7.0*).
> 
> You can also use GitHub releases tab to check differences between the version
> 
> * v6 https://github.com/handsontable/handsontable/releases/tag/6.0.0
> * v7 ([CE version](https://handsontable.com/blog/handsontable-drops-open-source-for-a-non-commercial-license)) - https://github.com/handsontable/handsontable/releases/tag/7.0.0

Thanks for reply, and do you have the copy or source html things of the documents that I can deploy in my private server?
Best wishes and hope for replying!

**Comment by AMBudnik** [comment]
Hi @yinyihui I only have generated docs (zip). You can find it here https://we.tl/t-O08wuQGtjG (~30MB zipped)
If you would need anything else please contact me at support@handsontable.com

**Comment by yinyihui** [comment]
> Hi @yinyihui I only have generated docs (zip). You can find it here https://we.tl/t-O08wuQGtjG (~30MB zipped) If you would need anything else please contact me at [support@handsontable.com](mailto:support@handsontable.com)

Thanks a lot and best wishes!
