### ISSUE TITLE
Internet Explorer 9/10 recent update: autocomplete dropdown not working

### ISSUE THREAD

**Issue by davedrury** [handsontable/handsontable#1090]
It seems recent update from Microsoft is causing issues with the auto complete drop down - on the demo page of Handsontable the following is happening (http://handsontable.com/demo/autocomplete.html):

- For the "Autocomplete lazy mode", you can choose a value the first time: but with any subsequent attempt the drop down disappears after hovering past the first drop down item.

- For "Autocomplete strict mode", when you select an item the page jumps to the top and the item does not get selected.

- On "Autocomplete strict mode (Ajax)" the drop down does not even appear

Similar issues are happening on the implementation of the table on our production code. Some users with IE9/10 are not experiencing the issues. On one pc experiencing the problem, ALL updates from MS have been applied.

**Comment by AMBudnik** [comment]
Please update to 0.13.1 and let us know if you still face the same issue. Until your reply issue will stay closed.
