### ISSUE TITLE
[Bug]: Table crashes when entering a number value with a space between negative symbol and numbers

### ISSUE THREAD

**Issue by CarltonHowell** [handsontable/handsontable#10918]
### Describe the bug

Enter or paste a negative value with a space between the negative symbol and numbers e.g. `- 1234`. Table will crash. Bug is reproducible on demo table: https://handsontable.com/demo

### Video/Screenshots

https://github.com/handsontable/handsontable/assets/54380672/9b35bc74-42c8-4ac1-93e0-69d5e8441f57

### Handsontable version
- v12.4.0
- v14.2.0

### Your environment

MacOs, Chrome

**Comment by adrianszymanski89** [comment]
Hi @CarltonHowell 

Thank you for reporting this. I reported it internally so our developers could investigate it further. I'll keep you updated.

**Comment by adrianszymanski89** [comment]
Hi, @CarltonHowell. I am happy to announce that this issue is fixed in v14.4.0.

Related pull request: https://github.com/handsontable/handsontable/pull/10931

Release notes: https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-4-0

Thank you again for sharing the report!
