### ISSUE TITLE
[Bug]: Vue 3 composition API ref error

### ISSUE THREAD

**Issue by lmvdz** [handsontable/handsontable#10919]
### Describe the bug

When I add a ref to the Vue component and add that same ref to my setup function I get an error in console which completely breaks the page.

![image](https://github.com/handsontable/handsontable/assets/2179775/0771237a-6ca3-4ab0-b791-326b26daf56e)
![image](https://github.com/handsontable/handsontable/assets/2179775/c53a962e-40d7-474d-9503-7a6e87f08fd5)
![image](https://github.com/handsontable/handsontable/assets/2179775/c0e4f772-ebcd-4c39-9b7d-ed609b9144d9)

### Handsontable version

14.2.0

### Your environment

Windows 11, Firefox/Chrome, Node v18.17.1, Vue 3.4.21

**Comment by lmvdz** [comment]
My workaround is this:

![image](https://github.com/handsontable/handsontable/assets/2179775/2576120c-b306-4a72-9043-fc9b7e58bdcf)
![image](https://github.com/handsontable/handsontable/assets/2179775/bb0a7d5a-59db-4e29-b7ff-bc9987495daf)

**Comment by adrianszymanski89** [comment]
Hi @lmvdz 

Thank you for contacting us. Can you please provide a code demo with the minimal settings where the issue is replicable? That would greatly help us to determine the problem.

**Comment by lmvdz** [comment]
Here is the !(https://codesandbox.io/p/devbox/agitated-pond-7fllr9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv1jrr4f00072a675atmj5zt%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv1jrr4f00022a67p6l5q6gz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv1jrr4f00042a675fknwqbh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv1jrr4f00062a67fz9knimn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv1jrr4f00022a67p6l5q6gz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv1jrr4f00012a67s24xsfn7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clv1jrr4f00022a67p6l5q6gz%2522%252C%2522activeTabId%2522%253A%2522clv1jrr4f00012a67s24xsfn7%2522%257D%252C%2522clv1jrr4f00062a67fz9knimn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv1jrr4f00052a6791e8a8k7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clv1jrr4f00062a67fz9knimn%2522%252C%2522activeTabId%2522%253A%2522clv1jrr4f00052a6791e8a8k7%2522%257D%252C%2522clv1jrr4f00042a675fknwqbh%2522%253A%257B%2522id%2522%253A%2522clv1jrr4f00042a675fknwqbh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv1jrr4f00032a67lq5j16zl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clv1jrr4f00032a67lq5j16zl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)[demo]

**Comment by lmvdz** [comment]
Changed to options API instead of composition API and it works, unfortunate I can't use <script setup>
Please add to the documentation for Vue 3 that the **Composition API isn't supported**

**Comment by adrianszymanski89** [comment]
Hi @lmvdz 

Thank you, but I can't see the error in your example. Can you please re-check it? Also, today, we released a new version of Handsontable, 14.3, which includes some fixes to a Vue 3 wrapper. 

Please check the issue with that version and let me know if it persists.

**Comment by lmvdz** [comment]
Use this, and then you'll be able to open the console
![image](https://github.com/handsontable/handsontable/assets/2179775/c8dfe835-d964-44e3-af11-e8b638d84ab9)

**Comment by lmvdz** [comment]
Tried updating to 14.3 and that completely broke it even more..

**Comment by lmvdz** [comment]
I think there is a reason why it wasn't working...

I named my ref `hotTable` which might have been conflicting with the import/vue component
![image](https://github.com/handsontable/handsontable/assets/2179775/bbf159fd-7ba5-4764-aecf-cbd850ad69c5)
![image](https://github.com/handsontable/handsontable/assets/2179775/e69891f2-e3ef-40cf-a8d7-83580e3e4bcc)

**Comment by adrianszymanski89** [comment]
Hi @lmvdz 

Thank you for the update. So is this issue resolved now?
