### ISSUE TITLE
[Bug]: A bug caused by sheetRename

### ISSUE THREAD

**Issue by yanyinqing** [handsontable/handsontable#10928]
### Describe the bug

If I want to update the sheetName of a sheet, but the data of other sheets will be disordered, the example is as follows.The third picture is just running, and the fourth chapter is after clicking rename button. First, the formula of my second sheet is not calculated, and secondly, the third cell that is obviously empty inherits the third cell of the first sheet.

### Video/Screenshots

<img width="662" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/39c8fdcb-a2e6-4de2-8f08-b19eaea4dac0">
<img width="718" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/aff3b529-d83d-4424-aa27-e769505f6d3d">
<img width="913" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/00d322ec-c548-4f55-8066-bafe1ff6ca8c">
<img width="1126" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/682ce6aa-4ab8-49cc-b527-411e52c6d1ff">
<img width="870" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/03740f9c-f44c-4b9e-8f43-8e119eefb265">

### Handsontable version

14.3.0

### Framework version

vue2.7.0

### Your environment

edge MacOS

**Comment by AMBudnik** [comment]
Hi @yanyinqing 

I assume that the lack of reply means that the issue is solved. If not, please contact us at support@handsontable.com to provide more details about the implementation.
