### ISSUE TITLE
Sorting doesn't trigger cell selection events

### ISSUE THREAD

**Issue by amclin** [handsontable/handsontable#1094]
### Steps to reproduce:
1. Select a cell in the middle of a column
2. Sort the column by clicking on the heading

### Expected result:
The following events should fire as the selected cell has changed:

1. afterSelection
2. afterSelectionByProp
3. afterSelectionEnd
4. afterSelectionEndByProp
5. afterDeselect
6. beforeColumnSort
7. afterColumnSort

### Actual result:
No events fired

**Comment by AMBudnik** [comment]
Please try our [main demo](https://jsfiddle.net/g5s1hvfu/) with `columnSorting: true` it fires all needed callbacks.

**Comment by AMBudnik** [comment]
I assume this issue can be closed in lack of recent activity.
