### ISSUE TITLE
[Bug]: vue dev-tools, Select a component

### ISSUE THREAD

**Issue by park00123** [handsontable/handsontable#10991]
### Describe the bug

Parent component of hot-table not selected

### Video/Screenshots

![image](https://github.com/handsontable/handsontable/assets/156289675/dcb9b2ad-dc93-417f-8187-0fbee47b4b30)

### Provide a link to the demo with the bug reproduction

https://w2vdgl.csb.app/

### Handsontable version

14.3.0

### Your environment

window10, Google Chrome 124.0.6367.209

**Comment by AMBudnik** [comment]
Hi @park00123 

Could you share a bit more details about the report? Can you share a demo (with the template) that you use to examine it in the vue tools?

**Comment by AMBudnik** [comment]
Hi @park00123 

I need to close this issue as it hasn't had an update for more than two weeks now.
