### ISSUE TITLE
Pasting from clipboard - too many afterChange

### ISSUE THREAD

**Issue by diginalog** [handsontable/handsontable#1099]
Hi.

I'm using handsontable with 24 columns table. 
Whenever pasting a row(from Google Drive or Handsontable), *afterChange* event fires many times.
Pasting 4 columns, that's ok. 
5 columns, *afterChange* fires 2 times / with 24 columns 9 calling of *afterChange*.

**Comment by dehim** [comment]
try this
var instance = $container.handsontable('getInstance');
Handsontable.hooks.destroy(instance);
