### ISSUE TITLE
Cannot read properties of null (reading 'view') when table is unhidden by changing display: none -> block

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#11006]
### Describe the bug

I'm having a hard time reproducing this issue in a minimal example. So I'm just putting this here hoping for the best.

In my React application I have multiple tables that I show/hide depending on what tab is active in the application.

Since @handsontable/react didn't support custom cell validators (at the time of writing and currently) I removed it and use it as if with vanilla js and put it in a useRef to manage the table. The table is wrapped in multiple component layers exposing the underlying handsontable with useImperativeHandlers to be able to add more and more custom features to the tables in each layer (branching in different feature directions).

I keep all of the tables in the DOM and never destroy them, just hide/unhide them when needed.

Anyway, now when I switch between tables by hiding one and showing another (display: none/block) the table that is shown throws an error every time it is unhidden:

```
Uncaught TypeError: Cannot read properties of null (reading 'view')
    at core.mjs:1117:18
    at element.mjs:1031:9
    at Array.forEach (<anonymous>)
    at IntersectionObserver.root (element.mjs:1029:13)
```

![image](https://github.com/handsontable/handsontable/assets/3355320/3e7cf717-ffcc-4c21-a28a-f07745d82a39)

I don't notice anything in the UI, but it's annoying knowing it's there and potentially causes unknown issues.

Any ideas what's wrong or ways to mitigate the issue?

### Handsontable version

14.3.0

### Framework version

React (but without @handsontable/react)

### Your environment

WebView2 125.0.2535.79

**Comment by adrianszymanski89** [comment]
Hi @ottosson 

Thank you for reporting this. Can you please share more details about your implementation? Do you only hide the tables visually without destroying and re-initializing the instance?

**Comment by ottosson** [comment]
> I keep all of the tables in the DOM and never destroy them, just hide/unhide them when needed.

**Comment by adrianszymanski89** [comment]
@ottosson 

That would be great, as I tried a few scenarios and can't reproduce the issue properly.

**Comment by ottosson** [comment]
I couldn't let this go so here is a minimal reproduction:
https://stackblitz.com/edit/vitejs-vite-wvxyw3?file=src%2Fmain.tsx

I'm sure the approach is not ideal. Let me know if it can be improved.

**Comment by adrianszymanski89** [comment]
@ottosson 

Thank you for the example. I've reviewed it, but so far, I can't find the source for this issue. It's hard to replicate with a React wrapper, but with some trickery, I was able to make it work with hide/show management without the error. Here's an example as a point of reference that, in general, it should work: https://jsfiddle.net/handsoncode/Lcwnzoa8/.

In your case, without the React wrapper, it's more complicated. This might be due to state handling, but it needs more investigation. Also, I noticed that you are destroying the instance and not only visually hiding/showing the table.

**Comment by ottosson** [comment]
Thanks. I checked your example and it creates multiple instances of the table when clicking hide/show a couple of times.

>Also, I noticed that you are destroying the instance and not only visually hiding/showing the table
Yes that seems like something wasn't thinking about in my first post. But it seems to be necessary to not get multiple instances in the DOM.

**Comment by ottosson** [comment]
It was a long time since I wrote the original implementation and it's not how I would have approached it today. So I switched to using a boolean useRef to check if the component has been initialized and return early if that's the case. Now I don't have to destroy the table on component unmount.

It solves my issue but the underlying bug is still there I guess.

**Comment by adrianszymanski89** [comment]
@ottosson 

I'll investigate it further and try to find the source of the issue. I'll keep you updated.
