### ISSUE TITLE
Handsontable does not respond in Adobe Illustrator

### ISSUE THREAD

**Issue by andrei-kav** [handsontable/handsontable#11008]
### Describe the bug

We have an application. It represents CEP HTML/JavaScript Extension for Adobe Illustrator. CEP means Common Extensibility Platform. Before It was called CSXS, then CS6, now CEP. CEP HTML engine is based on Chromium Embedded Framework version 3 ( [https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_10.x/Documentation/CEP%2010.0%20HTML%20Extension%20Cookbook.md](url) )
Our application is built using angular, also it uses handsontable components to interact with the data (handsontable and handsontable/angular wrapper). We have updated it to the last version 14.3.0. When we run the application in browser, it works well, everything as expected.
But if we run it as CEP Extension in Adobe Illustrator, the strange behavior appears. Now it is not possible to use arrow keys, tab key... These keyboard actions are just not caught by handsontable. To enter a new value into cell, you have to doubleclick a cell, and only then enter a value. Otherwise (without doubleclick) this action is also not caught.
We have downgraded the handsontable version to the previous one (13.1.0), and only then it started working well both in browser and in Adobe Illustrator.
We assume there are some contradictions between CEF (Chromium Embedded Framework) and handsontable/angular wrapper v.14

### Handsontable version

14

### Your environment

CEP extension for Adobe Illustrator, MacOs

**Comment by adrianszymanski89** [comment]
Hi @andrei-kav 

Thank you for contacting us. We don't support such extensions, but it's worth mentioning that in v. 14.0, we implemented many changes for accessibility compliance, mainly changes to Handsontable's focus management system. Perhaps some of them collide with the Adobe Illustrator focus management, but I'm afraid there's not much we can do, especially if we cannot reproduce the issue in another supported environment.
