### ISSUE TITLE
Column Filtering

### ISSUE THREAD

**Issue by ngpatel143** [handsontable/handsontable#1101]
Is it Possible to do Column Filtering like excel on Handsontable?

**Comment by philliproso** [comment]
This would be very useful indeed

**Comment by philliproso** [comment]
https://github.com/nicolaskruchten/pivottable, this library has a nice coffee script searchable tickable filter box much like excels. It might be good starting point @psmolenski any tips of the specific methods or hooks you think could be used.

**Comment by kishoreinvits** [comment]
Looking for an excel like filtering in HandsonTable. Any work in progress on this? If yes, i would like to join..

**Comment by kishoreinvits** [comment]
This is open from 2013 and I believe will be one of the much looked after feature! there should be someone working on this!

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
