### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'getSheetDimensions')

### ISSUE THREAD

**Issue by marwaayoub** [handsontable/handsontable#11013]
### Describe the bug

Iam trying to load 45K data and more in my Grid , I added all optimization options and still facing this error . Advise please 

### Video/Screenshots

 // Initialize Handsontable
            hot = new Handsontable(container, {
                data: data,
                colHeaders: headers,
                rowHeaders: true,
                columns: columns,
                licenseKey: 'non-commercial-and-evaluation',
                colWidths: 200,
                stretchH: 'all',
                autoColumnSize: false,
                dropdownMenu: true,
                filters: true,
                rowHeights: 23,
                renderAllRows:false,
                viewportRowRenderingOffset :50,
                allowInvalid: false,
                afterValidate: function (isValid, value, row, prop, source) {
                    if (!isValid) {
                        const cellMeta = hot.getCellMeta(row, prop);
                        const columnHeader = hot.getColHeader(prop);
                        $('#invalidMessageContainer').show();
                        $('#invalidMessageContainer').html(`Invalid value "${value}" in row ${row + 1}, column "${columnHeader}".`);
                    } else {
                        $('#invalidMessageContainer').hide();
                        $('#invalidMessageContainer').html();
                    } $
                },
                columnSorting: {
                    initialConfig: {
                        column: 0,      // Index of the column to be sorted (0 for "Name")
                        sortOrder: 'asc'  // 'asc' for ascending, 'desc' for descending
                    }
                },
                allowRemoveColumn: true,
                formulas: {
                    engine: hf,
                },
                contextMenu: {
                    items: {
                        "row_above": {},
                        "row_below": {},
                        "make_read_only": {},
                        "alignment": {},
                        "---------": {},
                        "undo": {},
                        "redo": {},
                        "---------": {},
                        "rename_column": {
                            name: 'Rename Column',
                            callback: function (key, selection, clickEvent) {

                                const selectedColumn = hot.getSelectedLast()[1];
                                let newColumnName = null;

                                while (newColumnName === null || newColumnName.trim() === '') {
                                    newColumnName = prompt('Enter a new name for the column');
                                    if (newColumnName === null) {
                                        // User canceled the prompt
                                        return;
                                    } else if (newColumnName.trim() === '') {
                                        alert('Please enter a column name');
                                    }
                                }

                                // Update the column header with the new name
                                const colHeaders = hot.getSettings().colHeaders;
                                colHeaders[selectedColumn] = newColumnName;
                                hot.updateSettings({ colHeaders: colHeaders });

                                // Preserve existing type or default to text if not set
                                const columns = hot.getSettings().columns;
                                const currentType = columns[selectedColumn].type || 'text';
                                columns[selectedColumn] = { ...columns[selectedColumn], name: newColumnName, type: currentType };
                                hot.updateSettings({
                                    columns: columns
                                });
                                $('#btnsave').show();
                            }

                        },
                        "col-left": {
                            name: "Insert column left",
                            callback: function () {
                                var selectedCol = hot.getSelectedLast()[1];
                                var newColumnIndex = selectedCol;

                                // Update existing data to include the new column
                                var newData = hot.getSourceData().map(row => {
                                    var newRow = { ...row };
                                    for (let i = Object.keys(newRow).length - 1; i >= newColumnIndex; i--) {
                                        newRow[i + 1] = newRow[i];
                                    }
                                    newRow[newColumnIndex] = null; // Insert null or empty value
                                    return newRow;
                                });

                                // Insert new column configuration
                                columns.splice(newColumnIndex, 0, { name: 'New Column', type: "text" });

                                // Adjust columns data keys
                                for (let i = newColumnIndex + 1; i < columns.length; i++) {
                                    columns[i].data = String(i);

                                }
                                // Insert new header
                                var newHeaders = columns.map(col => col.name);
                                // Update Handsontable settings
                                hot.updateSettings({
                                    data: newData,
                                    columns: columns,
                                    colHeaders: newHeaders
                                });

                                hot.render();

                            }
                        },

                        "col-right": {
                            name: "Insert column right",
                            callback: function () {
                                var selectedCol = hot.getSelectedLast()[1];
                                var newColumnIndex = selectedCol + 1;

                                // Update existing data to include the new column
                                var newData = hot.getSourceData().map(row => {
                                    var newRow = { ...row };
                                    for (let i = Object.keys(newRow).length - 1; i >= newColumnIndex; i--) {
                                        newRow[i + 1] = newRow[i];
                                    }
                                    newRow[newColumnIndex] = null; // Insert null or empty value
                                    return newRow;
                                });

                                // Insert new column configuration
                                columns.splice(newColumnIndex, 0, { name: 'New Column', type: 'text' });

                                // Adjust columns data keys
                                for (let i = newColumnIndex + 1; i < columns.length; i++) {
                                    columns[i].data = String(i);
                                }

                                // Insert new header
                                var newHeaders = columns.map(col => col.name);

                                // Update Handsontable settings
                                hot.updateSettings({
                                    data: newData,
                                    columns: columns,
                                    colHeaders: newHeaders
                                });

                                hot.render(); // Render the Handsontable to reflect changes
                            }
                        },
                        "remove_col": {
                            name: "Delete column",
                            disabled: false,
                            callback: function () {
                                var selectedCol = hot.getSelectedLast()[1];

                                // Update existing data to remove the selected column
                                var newData = hot.getSourceData().map(row => {
                                    var newRow = {};
                                    Object.keys(row).forEach(key => {
                                        if (Number(key) < selectedCol) {
                                            newRow[key] = row[key];
                                        } else if (Number(key) > selectedCol) {
                                            newRow[Number(key) - 1] = row[key];
                                        }
                                    });
                                    return newRow;
                                });

                                // Remove column configuration
                                columns.splice(selectedCol, 1);

                                // Adjust columns data keys
                                for (let i = selectedCol; i < columns.length; i++) {
                                    columns[i].data = String(i);
                                }

                                // Remove header
                                var newHeaders = columns.map(col => col.name);
                                // Update Handsontable settings
                                hot.updateSettings({
                                    data: newData,
                                    columns: columns,
                                    colHeaders: newHeaders
                                });

                                hot.render();
                            }
                        },

                        customFormulas: { // Own custom option
                            name: 'Formulas',
                            submenu: {

                                items: [
                                    {
                                        // Key must be in the form 'parent_key:child_key'
                                        key: 'customFormulas:sum',
                                        name: 'Sum',
                                        callback: function (key, selection) {
                                            var selectedCol = hot.getSelectedLast()[1];
                                            var columnName = headers[selectedCol];
                                            const rowStart = selection[0].start.row;
                                            const colStart = selection[0].start.col;
                                            const rowEnd = selection[0].end.row;
                                            const colEnd = selection[0].end.col;
                                            const startCell = getColumnLetter(colStart) + (rowStart + 1);
                                            const endCell = getColumnLetter(colEnd) + (rowEnd + 1);
                                            const formula = `=SUM(${startCell}:${endCell})`;
                                            // Set data in HyperFormula before calculating
                                            setHyperFormulaDataFromHandsontable(hot, hf, sheetId);
                                            // Evaluate formula
                                            const result = hf.calculateFormula(formula, sheetId);

                                            $("#btnClear").show();
                                            $("#Sum").show();
                                            $("#Sum").empty().text("SUM of " + columnName + " : " + result)
                                        }
                                    },
                                    {
                                        key: 'customFormulas:average',
                                        name: 'Average',
                                        callback: function (key, selection) {
                                            var selectedCol = hot.getSelectedLast()[1];
                                            var columnName = headers[selectedCol];
                                            const rowStart = selection[0].start.row;
                                            const colStart = selection[0].start.col;
                                            const rowEnd = selection[0].end.row;
                                            const colEnd = selection[0].end.col;

                                            // Collect numeric values from the selected range
                                            let values = [];
                                            for (let row = rowStart; row <= rowEnd; row++) {
                                                for (let col = colStart; col <= colEnd; col++) {
                                                    const cellValue = hot.getDataAtCell(row, col);
                                                    if (!isNaN(cellValue) && cellValue !== null && cellValue !== '') {
                                                        values.push(parseFloat(cellValue));
                                                    }
                                                }
                                            }

                                            // Calculate the average of numeric values
                                            let result = null;
                                            if (values.length > 0) {
                                                const sum = values.reduce((acc, val) => acc + val, 0);
                                                result = sum / values.length;
                                            }

                                            $("#Average").show().empty().text("AVG of " + columnName + " : " + (result !== null ? result : 'N/A'));
                                            $("#btnClear").show();

                                            //     const startCell = getColumnLetter(colStart) + (rowStart + 1);
                                            // const endCell = getColumnLetter(colEnd) + (rowEnd + 1);
                                            // const formula = `=AVERAGE(${colStart + 1}${rowStart + 1}:${colEnd + 1}${rowEnd + 1})`;
                                            // setHyperFormulaDataFromHandsontable(hot, hf, sheetId);
                                            //     const result = hf.calculateFormula(formula, sheetId);
                                            // $("#Average").show().empty().text("AVG of " + columnName + " : " + result)
                                            //     $("#btnClear").show();
                                        }
                                    },
                                    {
                                        key: 'customFormulas:count',
                                        name: 'COUNT',
                                        callback: function (key, selection) {
                                            var selectedCol = hot.getSelectedLast()[1];
                                            var columnName = headers[selectedCol];
                                            const rowStart = selection[0].start.row;
                                            const colStart = selection[0].start.col;
                                            const rowEnd = selection[0].end.row;
                                            const colEnd = selection[0].end.col;
                                            const startCell = getColumnLetter(colStart) + (rowStart + 1);
                                            const endCell = getColumnLetter(colEnd) + (rowEnd + 1);
                                            const formula = `=COUNTA(${startCell}:${endCell})`;
                                            // Evaluate formula
                                            setHyperFormulaDataFromHandsontable(hot, hf, sheetId);
                                            const result = hf.calculateFormula(formula, sheetId);
                                            $("#Count").show().empty().text("COUNT of " + columnName + " : " + result);
                                            $("#btnClear").show();
                                        }
                                    },
                                    {
                                        key: 'customFormulas:min', name: 'MIN',
                                        callback: function (key, selection) {
                                            var selectedCol = hot.getSelectedLast()[1];
                                            var columnName = headers[selectedCol];
                                            const rowStart = selection[0].start.row;
                                            const colStart = selection[0].start.col;
                                            const rowEnd = selection[0].end.row;
                                            const colEnd = selection[0].end.col;
                                            const startCell = getColumnLetter(colStart) + (rowStart + 1);
                                            const endCell = getColumnLetter(colEnd) + (rowEnd + 1);
                                            const formula = `=MIN(${startCell}:${endCell})`;
                                            // Evaluate formula
                                            setHyperFormulaDataFromHandsontable(hot, hf, sheetId);
                                            const result = hf.calculateFormula(formula, sheetId);

                                            $("#Min").show().empty().text("MIN of " + columnName + " : " + result);
                                            $("#btnClear").show();
                                        }
                                    },
                                    {
                                        key: 'customFormulas:max', name: 'MAX',
                                        callback: function (key, selection) {
                                            var selectedCol = hot.getSelectedLast()[1];
                                            var columnName = headers[selectedCol];
                                            const rowStart = selection[0].start.row;
                                            const colStart = selection[0].start.col;
                                            const rowEnd = selection[0].end.row;
                                            const colEnd = selection[0].end.col;
                                            const startCell = getColumnLetter(colStart) + (rowStart + 1);
                                            const endCell = getColumnLetter(colEnd) + (rowEnd + 1);
                                            const formula = `=MAX(${startCell}:${endCell})`;
                                            // Evaluate formula
                                            setHyperFormulaDataFromHandsontable(hot, hf, sheetId);
                                            const result = hf.calculateFormula(formula, sheetId);
                                            $("#Max").show().empty().text("MAX of " + columnName + " : " + result);
                                            $("#btnClear").show();
                                        }
                                    },

                                ]
                            }
                        },
                        datatypes: { // Own custom option
                            name: 'Data Types',
                            submenu: {
                                // Custom option with submenu of items
                                items: [
                                    {
                                        key: 'datatypes:Text',
                                        name: 'Text',
                                        callback(key, selection) {
                                            setColumnType(selection[0].start.col, 'text');
                                        }

                                    },
                                    {
                                        key: 'datatypes:Numeric',
                                        name: 'Numeric',
                                        callback(key, selection) {
                                            setColumnType(selection[0].start.col, 'numeric');
                                        }

                                    },
                                    {
                                        key: 'datatypes:Time',
                                        name: 'Time',
                                        callback(key, selection) {
                                            setColumnType(selection[0].start.col, 'time');
                                        }

                                    },
                                    {
                                        key: 'datatypes:Date', name: 'Date',
                                        callback(key, selection) {
                                            setColumnType(selection[0].start.col, 'date');
                                        }
                                    },
                                    {
                                        key: 'datatypes:Currency',
                                        name: 'Currency',
                                        callback(key, selection) {
                                            setColumnType(selection[0].start.col, 'currency');
                                        }
                                    },
                                    {
                                        key: 'datatypes:Percentage',
                                        name: 'Percentage',
                                        callback(key, selection) {
                                            setColumnType(selection[0].start.col, 'percentage');
                                        }
                                    }
                                ]
                            }
                        },
                    },
                }
            });

### Handsontable version

14.3.0

### Your environment

chrome

**Comment by adrianszymanski89** [comment]
Hi @marwaayoub 

Please send the code example in a chosen sandbox so we can investigate the issue.

**Comment by marwaayoub** [comment]
https://jsfiddle.net/uLnc963m/3/

**Comment by adrianszymanski89** [comment]
@marwaayoub 

Can you please recheck this example? It doesn't load and throws an error in the console.

**Comment by AMBudnik** [comment]
Hi @marwaayoub 

It's been a couple of weeks since we last heard from you regarding this issue report, so we're assuming that the issue has been resolved. We're always here to help if you need help or have any other questions.

Nevertheless, I'm closing this issue until there are any new updates.
