### ISSUE TITLE
At the same web page,copy handsontable then cannot copy anything

### ISSUE THREAD

**Issue by renjieyao** [handsontable/handsontable#11016]
### Describe the bug

At the same web page,copy handsontable then cannot copy anything

### Handsontable version

14.0.0

### Your environment

geogle

**Comment by adrianszymanski89** [comment]
Hi @renjieyao 

Please provide more details on the issue. Preferably with the examples.

**Comment by renjieyao** [comment]
> Hi @renjieyao
> 
> Please provide more details on the issue. Preferably with the examples.

In the first picture,I copy the code,and in the second picture,I cannot copy the code.In the demo,I cannot reappear it,please help me.

**Comment by renjieyao** [comment]
![importCountPrice](https://github.com/handsontable/handsontable/assets/50436535/2173462a-f022-42db-88e2-b38ed1c2a155)
![导入量价2](https://github.com/handsontable/handsontable/assets/50436535/5e990714-6137-4298-a5c2-d15f75fb2430)

**Comment by adrianszymanski89** [comment]
@renjieyao 

It looks like a heavily customized implementation. I can't do much without a code demo that replicates the issue. 

The only issue similar to this would be this one: https://github.com/handsontable/dev-handsontable/issues/1880, but it is already fixed in v. 14.4.0. Can you check that version and see if the problem is gone?

**Comment by renjieyao** [comment]
> @renjieyao
> 
> It looks like a heavily customized implementation. I can't do much without a code demo that replicates the issue.
> 
> The only issue similar to this would be this one: https://github.com/handsontable/dev-handsontable/issues/1880, but it is already fixed in v. 14.4.0. Can you check that version and see if the problem is gone?

![image](https://github.com/handsontable/handsontable/assets/50436535/f3c3ab34-b663-458f-b9a5-cddd2bebabaa)
I cannot open the link,this is my version details:"handsontable": "^14.0.0","@handsontable/vue3": "^14.4.0".I want to konw more details about this issue that is https://github.com/handsontable/dev-handsontable/issues/1880 talk about.

**Comment by adrianszymanski89** [comment]
Hi @renjieyao 

The mentioned issue was internal. This is the PR that fixed it: https://github.com/handsontable/handsontable/pull/10976

**Comment by renjieyao** [comment]
I have resolved the issue after updating to 14.4.0
