### ISSUE TITLE
Cell value missing

### ISSUE THREAD

**Issue by wangdingwei** [handsontable/handsontable#11029]
### Describe the bug

https://jsfiddle.net/9L5ochew/1/

as the code above, D2 cell value missing
<img width="1384" alt="image" src="https://github.com/handsontable/handsontable/assets/6716895/5c4c2010-2a2a-442e-8c0c-42160df24a9a">

### Handsontable version

14.4.0

### Your environment

chrome Version 125.0.6422.142

**Comment by adrianszymanski89** [comment]
Hi @wangdingwei 

Thank you for contacting us. You have to define the whole dimension of the array so the data is rendered correctly.  Here's your example with correct implementation: https://jsfiddle.net/handsoncode/p3x68e4m/
