### ISSUE TITLE
[Bug]: Display bug in iphone

### ISSUE THREAD

**Issue by tymzyx** [handsontable/handsontable#11030]
### Describe the bug

I used the old version of Handsontable(7.2.2).
As shown in the figure,
Is this a bug that exists in old version? And solved in lastest version?
Is there a solution that can fix this problem in 7.2.2?

### Video/Screenshots

<img width="330" alt="image" src="https://github.com/handsontable/handsontable/assets/15604763/137a5947-4260-4837-a031-3fa448d5ed9d">

### Handsontable version

7.2.2

### Your environment

iphone, ios 15.0.1

**Comment by adrianszymanski89** [comment]
Hi @tymzyx 

Thank you for contacting us. We would need to have a code demo with your implementation to check it, or you can update it to the latest version and check if the issue persists with your current configuration.

**Comment by tymzyx** [comment]
@adrianszymanski89 Thank you for your reply. I found that a custom style is causing this issue, and it has been fixed.
