### ISSUE TITLE
Closed as duplicate of: https://github.com/handsontable/handsontable/issues/11016

### ISSUE THREAD

**Issue by renjieyao** [handsontable/handsontable#11056]
Closed as duplicate of: https://github.com/handsontable/handsontable/issues/11016

_Originally posted by @adrianszymanski89 in https://github.com/handsontable/handsontable/issues/11017#issuecomment-2160400463_

**Comment by renjieyao** [comment]
https://github.com/handsontable/handsontable/issues/11054,when I update the version 14.4.4,cannot build my project,please help me.

**Comment by adrianszymanski89** [comment]
Hi @renjieyao 

I answered your previous report: https://github.com/handsontable/handsontable/issues/11054. I will close this one as a duplicate.
