### ISSUE TITLE
Remove `-ms-high-constrast` in CSS as it is being deprecated!!

### ISSUE THREAD

**Issue by KiddoV** [handsontable/handsontable#11055]
### Describe the bug

Currently I have a lot of warning for this:

```console
[Deprecation] -ms-high-constrast is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.
```

I found you are using it in: https://github.com/handsontable/handsontable/blob/d16788f9036a9eb9956740978bb4f5415ff1f9a5/handsontable/src/css/handsontable.scss#L202

### Video/Screenshots

![warning](https://github.com/handsontable/handsontable/assets/28552977/1d60f119-fa36-47bf-89bf-8f8b00a33f12)

### Handsontable version

Any

### Framework version

Any

### Your environment

Any

**Comment by garyganyang** [comment]
expect the fix

**Comment by AMBudnik** [comment]
Thank you for sharing. 

We will definitely take a look at this.

Quote: 

> Today, we’re announcing the deprecation of the CSS -ms-high-contrast media query and -ms-high-contrast-adjust property, in favor of the standard-based forced colors feature that we implemented in Chromium-based browsers in 2020.

Warning period

> As part of the deprecation process, Microsoft Edge will also display a warning in the DevTools Console tool for any sites that use the legacy properties in their stylesheets starting with Edge version 126.

Then

> We are planning to completely disable the legacy implementation by Edge 138, but this plan might change depending on the feedback that we receive during this deprecation trial.

Reference: https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/

**Comment by garyganyang** [comment]
got it , thanks
