### ISSUE TITLE
npm run build error,when version from 14.0.0 to 14.4.0

### ISSUE THREAD

**Issue by renjieyao** [handsontable/handsontable#11054]
### Describe the bug

node_modules\handsontable\3rdparty\walkontable\src\utils\columnStretching.mjsUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7977B07BF node_api_throw_syntax_error+175823
 2: 00007FF797735796 DSA_meth_get_flags+59654
 3: 00007FF797737480 DSA_meth_get_flags+67056
 4: 00007FF7981DDCC4 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF7981C9052 v8::Isolate::Exit+674
 6: 00007FF79804AF0C v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF79804812B v8::internal::Heap::CollectGarbage+3963
 8: 00007FF79805E363 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
 9: 00007FF79805EC0D v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
10: 00007FF79806E3D0 v8::internal::Factory::NewFillerObject+816
11: 00007FF797D5F1FF v8::internal::DateCache::Weekday+1071
12: 00007FF79827B1F1 v8::internal::SetupIsolateDelegate::SetupHeap+558193
13: 00007FF718E11602

### Handsontable version

14.4.0

### Your environment

windows

**Comment by renjieyao** [comment]
This error happened when I update the version of handsontable from 14.0.0 to 14.4.0,please help me soon.

**Comment by renjieyao** [comment]
This error happened when I update the version of handsontable from 14.0.0 to 14.4.0,please help me soon.

**Comment by renjieyao** [comment]
> Hi @renjieyao
> 
> Thank you for contacting us. We didn't have any similar reports regarding the update to 14.4.0. Did you try clean installation, with removing node modules?


When I delete node modules and install,the problem still in there.



node_modules\handsontable\3rdparty\walkontable\src\utils\columnStretching.mjsUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
✓ 2905 modules transformed.
rendering chunks (179)...
<--- Last few GCs --->

[31396:000002B8F885C2C0]    99288 ms: Mark-sweep (reduce) 4063.7 (4144.4) -> 4062.4 (4143.8) MB, 1578.6 / 0.0 ms  (average mu = 0.448, current mu = 0.351) allocation failure GC in old space requested
[31396:000002B8F885C2C0]   100830 ms: Mark-sweep (reduce) 4062.6 (4143.8) -> 4062.6 (4144.1) MB, 1542.6 / 0.0 ms  (average mu = 0.256, current mu = 0.000) allocation failure GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF73E2A15AF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+122159
 2: 00007FF73E22B376 DSA_meth_get_flags+64118
 3: 00007FF73E22C3F2 DSA_meth_get_flags+68338
 4: 00007FF73EB63204 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF73EB4D7CD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF73E9F0D8C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF73E9EDEA4 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF73E9EB820 v8::internal::Heap::AllocateExternalBackingStore+2000
 9: 00007FF73EA103A6 v8::internal::Factory::NewFillerObject+214
10: 00007FF73E7428AA v8::internal::DateCache::Weekday+1466
11: 00007FF73EBF0EE1 v8::internal::SetupIsolateDelegate::SetupHeap+494417
12: 000002B88128D4AD
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by adrianszymanski89** [comment]
@renjieyao 

Thank you for the update. Would it be possible for you to share your project so we can check it locally?

**Comment by renjieyao** [comment]
It looke like be the problem of Vite version,thank u for your help.
