### ISSUE TITLE
one double quote is missing after Copy-paste or drag the value (two consecutive double quote) in Handsontable

### ISSUE THREAD

**Issue by angithub** [handsontable/handsontable#1106]
Requirement: 
I have a requirement on my web application, where the user can enter value with two consecutive double-quotes

jsfiddle link:
http://jsfiddle.net/a3uj6/1/

Issue:
If the cell has Two consecutive double quotes, one double quote is missing upon copy-paste the cell to another cell.
Same issue occurs, if the user drags the cell-value to place it in the next column/cell.

jsfiddle link:
http://jsfiddle.net/a3uj6/1/

NOTE: User is not doing copy/paste or dragging a multi-line text, it is just a single-line text with two consecutive quotes.

**Comment by AMBudnik** [comment]
Please track changes in #379 issue

**Comment by felixhagspiel** [comment]
@AMBudnik this seem to be broken again in version 0.14 and 0.15.0-beta2 (I tried it on your demo site)

**Comment by AMBudnik** [comment]
You are right, copying loses one quote - we'll take a look at this.

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/2392
