### ISSUE TITLE
Column headers are cut off for table without rows

### ISSUE THREAD

**Issue by dagroe** [handsontable/handsontable#11075]
### Describe the bug

For a table that has no rows the table is too narrow so that the column headers are cut off. It works fine when adding an empty row but our use case is that the table is initially empty and then the user can add rows.

### Video/Screenshots

<img width="314" alt="Screenshot 2024-07-09 at 10 42 11" src="https://github.com/handsontable/handsontable/assets/6624011/ad7457b1-9c0f-448a-ad21-db9481c5749b">
<img width="314" alt="Screenshot 2024-07-09 at 10 42 04" src="https://github.com/handsontable/handsontable/assets/6624011/e288fdfe-dbcf-480a-946b-da889c13f355">

### Provide a link to the demo with the bug reproduction

https://codesandbox.io/s/affectionate-austin-769hdd?file=/src/index.js

### Handsontable version

14.4.0

### Your environment

Firefox, Chrome, Brave on Mac OS

**Comment by adrianszymanski89** [comment]
Hi @dagroe 

Thank you for contacting us. I checked your example, and in my case, it looks like this:

![image](https://github.com/handsontable/handsontable/assets/92314130/d865b106-b816-498a-8374-c69f4b8cfc16)

Can you please provide the steps to get the same result as yours?

**Comment by AMBudnik** [comment]
Hi @dagroe 

Could you please update to v14.5.0 and check if the issue is still replicable? 

I just tested it on Chrome 127 and FF 129 on my Mac, and it works well. Here's an updated demo https://jsfiddle.net/gpwna5ek/

**Comment by dagroe** [comment]
@AMBudnik Fixed in our app with v14.5.0. thanks!
