### ISSUE TITLE
Horizontal scrollbar disappeared in IE

### ISSUE THREAD

**Issue by itsmesw** [handsontable/handsontable#1108]
I try to insert horizontal scrollbar with Autocomplete cell type.

When I click scrollbar region, typeahead source lists are disappeared.
Thing that never happens using the mouse wheel.

Lists closing problem happens in IE only, my version is 10.0.8.
Chrome and Firefox work well.
http://jsfiddle.net/itsmesw/6g4rF/

Additionaly, I tested the horizontal scrollbar in handsontable version 0.7.2.
It works well in IE, too.
http://jsfiddle.net/itsmesw/w8SMJ/

What should I do for solve it? 
Thanks.

**Comment by AMBudnik** [comment]
Issue closed in lack of issue author reply.
