### ISSUE TITLE
In Tabs Row and col headers disapper when modal open

### ISSUE THREAD

**Issue by jin-benben** [handsontable/handsontable#11080]
### Describe the bug

After modal open , change tabs active  row and col headers disapper

### Provide a link to the demo with the bug reproduction

https://github.com/jin-benben/handsontable.git

### Handsontable version

14.4.0

### Framework version

react 18.2

### Your environment

chrome：126.0.6478.127

**Comment by AMBudnik** [comment]
Hi @jin-benben 

It seems that all you need to do is call `render()` when user clicks the second tab. Did you try that?

**Comment by jin-benben** [comment]
> Hi @jin-benben
> 
> It seems that all you need to do is call `render()` when user clicks the second tab. Did you try that?

Yes, but no use

**Comment by AMBudnik** [comment]
Could you please prepare a demo in a sandbox (JSFiddle, Codesandbox, Stackblitz, etc.) so it is easier to share feedback and changes? Maybe there's a slight delay needed as well to run the function.

**Comment by jin-benben** [comment]
> Stackblitz

https://stackblitz.com/edit/react-7y9twy

**Comment by jin-benben** [comment]
> Could you please prepare a demo in a sandbox (JSFiddle, Codesandbox, Stackblitz, etc.) so it is easier to share feedback and changes? Maybe there's a slight delay needed as well to run the function.

https://stackblitz.com/edit/react-7y9twy

**Comment by AMBudnik** [comment]
Thank you.

Just like I thought a small delay did the change. Please check this demo https://stackblitz.com/edit/react-7y9twy-8ynnkt?file=src%2FExampleComponent.jsx with changes applied.

**Comment by jin-benben** [comment]
> Thank you.
> 
> Just like I thought a small delay did the change. Please check this demo https://stackblitz.com/edit/react-7y9twy-8ynnkt?file=src%2FExampleComponent.jsx with changes applied.

Thank you for your help. The problem has been solved. Have a nice day
