### ISSUE TITLE
Handsontable loadData method issue 

### ISSUE THREAD

**Issue by idleshin** [handsontable/handsontable#1109]
Hi all,
I call loadData() method and process to self.render(),
I got error message "Unable to get property 'length' of undefined or null reference",but I check data which is the same with getdata().

data content:
[[object Object],[object Object],[object Object],[object Object],[object Object]]
    [0]: {...}
    [1]: {...}
    [2]: {...}
    [3]: {...}
    [4]: {...}
    [prototype]: []

**Comment by krzysztofspilka** [comment]
We didn't get any further questions, i'm closing this issue.
