### ISSUE TITLE
dropDownMenu disappear when input space or enter by keyboard after updateSetting of dropDownMenu from false to  true

### ISSUE THREAD

**Issue by chennyang** [handsontable/handsontable#11097]
### Describe the bug

Hi，I updateSetting to set dropDownMenu:false and then set dropDownMenu:true, when I input space or enter to search, the dropDownMenu disappear, Please help to check, Thank you!

You can try by this demo:
```
<template>
  <button @click="updateSettings">Update Data</button>
  <div id="example1">
    <hot-table :settings="hotSettings"></hot-table>
  </div>
</template>

<script>

import { defineComponent } from "vue";
import { HotTable } from "@handsontable/vue3";
import { registerAllModules } from "handsontable/registry";
import "handsontable/dist/handsontable.full.css";

// register Handsontable's modules
registerAllModules();

const ExampleComponent = defineComponent({
  data() {
    return {
      hotSettings: {
        colHeaders: ["Name", "Age", "Country"],
        height: "auto",
        filters: true,
        autoWrapRow: true,
        autoWrapCol: true,
        licenseKey: "non-commercial-and-evaluation",
        rowHeaders: false,
        dropdownMenu: [
          "filter_operators",
          "filter_by_value",
          "filter_action_bar",
        ],
        data: [[" a", "", ""]],
      },
      flag: true,
    };
  },

  components: {
    HotTable,
  },

  methods: {
    updateSettings() {
      this.flag = !this.flag;
      if (this.flag) {
        this.hotSettings = { dropdownMenu: false };
      } else {
        this.hotSettings = {
          dropdownMenu: [
            "filter_operators",
            "filter_by_value",
            "filter_action_bar",
          ],
        };
      }
    },
  },
});

export default ExampleComponent;
</script>
```

### Handsontable version

14.0.0

### Your environment

windows

**Comment by chennyang** [comment]
<template>
  <button @click="updateSettings">Update Data</button>
  <div id="example1">
    <hot-table :settings="hotSettings"></hot-table>
  </div>
</template>

<script>
import { defineComponent } from "vue";
import { HotTable } from "@handsontable/vue3";
import { registerAllModules } from "handsontable/registry";
import "handsontable/dist/handsontable.full.css";

// register Handsontable's modules
registerAllModules();

const ExampleComponent = defineComponent({
  data() {
    return {
      hotSettings: {
        colHeaders: ["Name", "Age", "Country"],
        height: "auto",
        filters: true,
        autoWrapRow: true,
        autoWrapCol: true,
        licenseKey: "non-commercial-and-evaluation",
        rowHeaders: false,
        dropdownMenu: [
          "filter_operators",
          "filter_by_value",
          "filter_action_bar",
        ],
        data: [[" a", "", ""]],
      },
      flag: true,
    };
  },
  components: {
    HotTable,
  },
  methods: {
    updateSettings() {
      this.flag = !this.flag;
      if (this.flag) {
        this.hotSettings = { dropdownMenu: false };
      } else {
        this.hotSettings = {
          dropdownMenu: [
            "filter_operators",
            "filter_by_value",
            "filter_action_bar",
          ],
        };
      }
    },
  },
});

export default ExampleComponent;
</script>

**Comment by chennyang** [comment]
`<template>
  <button @click="updateSettings">Update Data</button>
  <div id="example1">
    <hot-table :settings="hotSettings"></hot-table>
  </div>
</template>

`

**Comment by adrianszymanski89** [comment]
Hi @chennyang 

Thank you for contacting us. I copied your settings to this example: https://jsfiddle.net/handsoncode/173rawoy/, but I can't get the result you describe. Can you please provide the exact steps to reproduce this issue?

**Comment by chennyang** [comment]
Sorry, my network is not support to update the jsfiddle. there is a button to switch the setting of dropdownMenu, 
```<template>
  <button @click="updateSettings">Update Data</button>
  <div id="example1">
    <hot-table :settings="hotSettings"></hot-table>
  </div>
</template>
```
1. click the button to set dropdownMenu:false
2. click the button to set dropdownMenu: [
            "filter_operators",
            "filter_by_value",
            "filter_action_bar",
          ]
3. input space or enter by keyboard in search box in dropdownMenu of any column.
4. the dropdownMenu will disappear.

**Comment by adrianszymanski89** [comment]
@chennyang 

Thanks. I added the button and followed the steps but still can't get the same result. Can you record a video showing the steps? Maybe that will help.

**Comment by adrianszymanski89** [comment]
Hi @chennyang 

Do you have any updates here?

**Comment by bturner1273** [comment]
I actually have this same issue I am working on a repro for. My behavior is seemingly the same, when the column dropdown menu is opened and space is pressed in the filter input the dropdown closes.

**Comment by adrianszymanski89** [comment]
Hi @bturner1273 

Thank you for your input. Please let us know when you have an example where the issue can be replicated.

**Comment by jeong-hojeong** [comment]
Hi @adrianszymanski89,

I have been facing the same issue and was able to replicate it. In my case, the behavior appears when useEffect is used inside the component.

https://stackblitz.com/edit/react-dgwohh?file=src%2FExampleComponent.jsx

Steps to reproduce:
1. Open dropdownMenu
2. Type space in filter_by_value input (or any other input)
3. DropdownMenu closes
4. Comment out the useEffect part (line 13-15)
5. Perform step 2 again
6. DropdownMenu does not close

**Comment by adrianszymanski89** [comment]
Hi @jeong-hojeong 

Thank you for sharing the example. Now I was able to reproduce the issue. Additionally, it seems that not `useEffect` is responsible for this issue, but just modyfying the state. I reported this issue internally and will update you once it's fixed.

**Comment by AMBudnik** [comment]
Hi @chennyang 

I am happy to announce that this issue is no longer replicable in the newest version of Handsontable - v15.0.0.

Here https://stackblitz.com/edit/react-dgwohh-uoscnxyr?file=src%2FExampleComponent.jsx you can test it.

I am closing this issue as solved. However, if you would find any issue with the solution please leave a comment here or send us a message at support@handsontable.com
