### ISSUE TITLE
My right-click menu copy function is not working

### ISSUE THREAD

**Issue by 1557812300** [handsontable/handsontable#11092]
Because of using this API, my right-click menu paste function fails.
How can I fix it? outsideClickDeselects={false}

**Comment by AMBudnik** [comment]
Hi @1557812300 

Could you share a demo where the issue is replicable? 

In the title, you mentioned copying is not working and then pasting it in the description of the issue. I am not sure what the case is.

**Comment by 1557812300** [comment]
outsideClickDeselects={false} affects the use of this.getPlugin('copyPaste').paste(text). Remove outsideClickDeselects={false} and the copy-paste function is normal

**Comment by AMBudnik** [comment]
Thank you for additional details.

This seems to have the same origin as the issue ported at https://github.com/handsontable/handsontable/issues/11034

**Comment by 1557812300** [comment]
问题已解决，查的chatGPT4o,也感谢解答：
   {
        key: '粘贴',
        name: '粘贴',
        /**
         * 粘贴操作的回调函数
         *
         * 从剪贴板读取文本，解析为二维数组，并尝试将其填充到 Handsontable 的选中区域内
         */
        callback() {
            // 确保 Handsontable 实例获取焦点
            const hotInstance = this
            if (hotInstance && hotInstance.rootElement) {
            // 从剪贴板读取文本
                navigator.clipboard
                    .readText()
                    .then(text => {
                        // 解析文本为二维数组
                        const data = text.split('\n').map(row => row.split('\t'))
                        // 获取当前选中的单元格区域
                        const selected = hotInstance.getSelected()
                        if (selected) {
                        // 获取选中区域的起始行和列
                            const [startRow, startCol] = selected[0]
                            // 将数据填充到 Handsontable 的选中区域内
                            hotInstance.populateFromArray(startRow, startCol, data)
                        }
                    })
                    .catch(err => {
                        console.error('读取剪贴板内容失败: ', err)
                    })
            }
        }
    },

**Comment by 1557812300** [comment]
问题已解决，查的chatGPT4o,也感谢帮忙解答：
``` javascript
 {
    key: 'Paste',
    name: 'Paste',
    /**
     * Callback function for paste operation
     *
     * Reads text from the clipboard, parses it into a 2D array, and attempts to populate it into the selected area of Handsontable
     */
    callback() {
        // Ensure the Handsontable instance gains focus
        const hotInstance = this;
        if (hotInstance && hotInstance.rootElement) {
            // Read text from the clipboard
            navigator.clipboard
                .readText()
                .then(text => {
                    // Parse the text into a 2D array
                    const data = text.split('\n').map(row => row.split('\t'));
                    // Get the currently selected cell area
                    const selected = hotInstance.getSelected();
                    if (selected) {
                        // Get the starting row and column of the selected area
                        const [startRow, startCol] = selected[0];
                        // Populate the data into the selected area of Handsontable
                        hotInstance.populateFromArray(startRow, startCol, data);
                    }
                })
                .catch(err => {
                    console.error('Failed to read clipboard contents: ', err);
                });
        }
    }
}
```

**Comment by AMBudnik** [comment]
> 问题已解决，查的chatGPT4o,也感谢帮忙解答：

I am glad that the issue is solved. Thank you for the update.
