### ISSUE TITLE
Can't get the latest data through getSourceData()?

### ISSUE THREAD

**Issue by sheep5250** [handsontable/handsontable#11127]
When I use setDataAtRowProp() to update the data, I immediately use getSourceData() to retrieve the table data. However, the retrieved data is the data before setDataAtRowProp() was updated. How can I obtain the updated data?

**Comment by adrianszymanski89** [comment]
Hi @sheep5250 

Thank you for contacting us. The `setDataAtRowProp()` operates on visual data so that the changes won't be accessible through the `getSourceData()` method. You can use the `getData()` method to get the visual changes.

**Comment by sheep5250** [comment]
@adrianszymanski89   Why do I call setDataAtRowProp() and then getSourceData(), and the execution order is to execute getSourceData() first and then setDataAtRowProp()?And when I use getData() to get the changed value of setDataAtRowProp(), the data I get is still the same as before the change

**Comment by sheep5250** [comment]
@adrianszymanski89  If I want to use getSourceData() to get the values after changing the table through the API, how do I change the values

**Comment by adrianszymanski89** [comment]
@sheep5250 

In this case, you will need to use this method: https://handsontable.com/docs/react-data-grid/api/core/#setsourcedataatcell as it operates on source data, then calling the `getSourceData()` will get you the expected results.
