### ISSUE TITLE
HyperFormula rebuildAndRecalculate() doesn't trigger re-render

### ISSUE THREAD

**Issue by leizha** [handsontable/handsontable#11138]
### Describe the bug

Add a volatile function for example NOW() and HF rebuildAndRecalculate() doesn't seem to trigger re-render so the updates do not show.

The expected behavior: users don't have explicitly call render(). rebuildAndRecalculate() should trigger re-render if there are changes.

### Video/Screenshots

![image](https://github.com/user-attachments/assets/ad535705-c510-466d-8a3d-6373731f5dff)

### Provide a link to the demo with the bug reproduction

https://stackblitz.com/edit/6sjfmr?file=index.js

### Handsontable version

14.5.0

### Your environment

chrome

**Comment by AMBudnik** [comment]
Hi @leizha 

Thank you for sharing the report.

The `rebuildAndRecalculate()` is a Hyperformula method, so it doesn't automatically trigger the Handsontable rendering. 

What we can think of is adding an alias within the `Formulas` plugin, and then we can force the table to render. Would that sound like a suitable solution?

**Comment by AMBudnik** [comment]
I'm closing this issue as solved.

If you need anything more than that, please feel free to open a new issue.
