### ISSUE TITLE
version 14.5.0 merge bug：rows  below the new created row lost merge settings

### ISSUE THREAD

**Issue by LIUKQSGITHUB** [handsontable/handsontable#11133]
### Describe the bug

call hot.alter('insert_row_below') ,rows  below the new created row lost merge settings

### Video/Screenshots

![image](https://github.com/user-attachments/assets/21d5cd64-252a-47b8-bf3f-d66213d76b80)

### Handsontable version

14.5.0

### Your environment

chrome

**Comment by adrianszymanski89** [comment]
Hi @LIUKQSGITHUB 

Can you please send a code demo where the issue can be replicated?

**Comment by LIUKQSGITHUB** [comment]
> Hi @LIUKQSGITHUB
> 
> Can you please send a code demo where the issue can be replicated?

please check this demo https://jsfiddle.net/4mbnqL0g/3/   merge cells changed after  click the button

**Comment by adrianszymanski89** [comment]
@LIUKQSGITHUB 

Thank you for the demo. I can see that you have multiple merge cells configuration errors. That might be the case here, as we made improvements to this plugin in 14.5. 

When I checked our example from the documentation, it works correctly while adding new rows: https://jsfiddle.net/fmoLv7su/

**Comment by LIUKQSGITHUB** [comment]
> @LIUKQSGITHUB
> 
> Thank you for the demo. I can see that you have multiple merge cells configuration errors. That might be the case here, as we made improvements to this plugin in 14.5.
> 
> When I checked our example from the documentation, it works correctly while adding new rows: https://jsfiddle.net/fmoLv7su/

sory,i still can not see any configuratioon errors, here is the simple demo that can be replicated https://jsfiddle.net/yLet7sx2/

**Comment by LIUKQSGITHUB** [comment]
> @LIUKQSGITHUB
> 
> Thank you. Now, I am able to reproduce the issue. It is definitely a regression. I reported it internally for further investigation and will update you once it's fixed.

thanks

**Comment by wendulenmon123why** [comment]
现在还存在这个问题，新建时候保存成功了，刷新页面会报错
