### ISSUE TITLE
F2 Key Press Does Not Trigger The Editing Mode

### ISSUE THREAD

**Issue by anboua** [handsontable/handsontable#11147]
### Describe the bug

The F2 key is commonly used to enter the editing mode of the currently active cell, However, pressing the F2 key does not activate the editing mode for the active cell.

### Steps to Reproduce

- Open a Handsontable instance (version 14.5.0).
- Navigate to any cell.
- Press the F2 key.

### Expected Result
The active cell should enter the editing mode, allowing the user to edit the cell's content.

### Actual Result
The F2 key press does not trigger the editing mode. The cell remains in its normal state.

### Handsontable version

14.5.0

### Framework version

React 18.2.0

### Your environment

Chrome 126.0.6478.226 (Official Build) extended (64-bit) - Windows 11

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @anboua 

You are right. that is a regression for the latest version - v14.5.0.

I will report it internally and notify you of the fix.

**Comment by AMBudnik** [comment]
Hi @anboua 

Here's Aleksandra again. I have great news today! We just released version 14.6.0, which has fixed this issue.

Once again, thank you for sharing the report.
