### ISSUE TITLE
hiddenColumns

### ISSUE THREAD

**Issue by 1004834495** [handsontable/handsontable#11142]
### Describe the bug

Hidden columns use indicators. What should I do if I click this icon to display the hidden columns behind the icon

### Video/Screenshots

![image](https://github.com/user-attachments/assets/97edb1d7-f901-4852-900e-242da11b1680)

### Handsontable version

14.4.0

### Framework version

react 18.1.0

### Your environment

windows10  google

**Comment by adrianszymanski89** [comment]
Hi @1004834495 

Thank you for contacting us. If you want to show the hidden columns, you need to right-click on the "zero" header to open a context menu like here:

![image](https://github.com/user-attachments/assets/10db09ef-bf05-4f0a-892f-1d97d1f8d37c)

And then click `Show columns`.

**Comment by 1004834495** [comment]
But this will show all the columns that I hide, I just want to show the columns that are hidden behind the icon
[全量发票查询导出结果 (开发).zip](https://github.com/user-attachments/files/16517062/default.zip)

**Comment by adrianszymanski89** [comment]
@1004834495 

In this case, it can be done in two ways. First, you can create a custom context menu option and use the plugin's API to show the chosen hidden column with this method: https://handsontable.com/docs/react-data-grid/api/hidden-columns/#showcolumn. Here, you can also find the guide on how to create custom context menu options: https://handsontable.com/docs/react-data-grid/context-menu/#context-menu-with-a-fully-custom-configuration

The second option would be to create an external button using the same method.
