### ISSUE TITLE
TypeScript Type Error in selectCell Method: column Parameter Doesn't Support prop Name as Described in Documentation

### ISSUE THREAD

**Issue by wiexin** [handsontable/handsontable#11158]
### Describe the bug

When using Handsontable and calling selectCell(2, 'first_name'), TypeScript throws a type error indicating that the column parameter must be of type number. However, according to the documentation, the column parameter should support using the prop name as a valid value. Upon reviewing the core.d.ts file, the type definition for selectCell shows that the parameter only accepts a number type, which might be a bug in the type definition.

### Handsontable version

14.5

### Your environment

win11 chrome

**Comment by adrianszymanski89** [comment]
Hi @wiexin 

Thank you for contacting us and reporting the problem. I checked it, and indeed, the type definition for this case is missing. I will report it internally and will update you once it's fixed.

**Comment by AMBudnik** [comment]
Hi @wiexin 

I am happy to inform you that we just released a [new version](https://handsontable.com/docs/react-data-grid/changelog/). Among other great changes, we also fixed the definition. 

Thank you for sharing 🥇
