### ISSUE TITLE
copy/pase not work when imeFastEdit=true outsideClickDeselects=false

### ISSUE THREAD

**Issue by jin-benben** [handsontable/handsontable#11204]
### Describe the bug

copy/pase not work when handsontable set  imeFastEdit=true outsideClickDeselects=false

### Provide a link to the demo with the bug reproduction

https://stackblitz.com/edit/react-qyfynp?file=src%2FExampleComponent.jsx

### Handsontable version

14.5.0

### Framework version

react 18.2

### Your environment

chrome：126.0.6478.127

**Comment by adrianszymanski89** [comment]
Hi @jin-benben 

Can you please recheck your example? It throws an error and doesn't run.

**Comment by jin-benben** [comment]
> Hi @jin-benben
> 
> Can you please recheck your example? It throws an error and doesn't run.

https://stackblitz.com/edit/react-qyfynp?file=src%2FExampleComponent.jsx

**Comment by AMBudnik** [comment]
Hi @jin-benben 

My cousin's on vacation, so I am jumping in to take over the subject.

Thank you for the demo. I was able to replicate the issue. 

It seems that this is a regression that started from v14.4. Here, while we use v14.3, `copyPaste` works well: https://jsfiddle.net/q0afb1xu/. 

I will report this issue internally and notify you as soon as we fix it.

**Comment by AMBudnik** [comment]
Hi @jin-benben 

Please update to v14.6.0 and test the example once again. The issue is already fixed! 

Here's a quick demo where you can check how it works now https://jsfiddle.net/pn3qej8a/.
