### ISSUE TITLE
languages\index.d.ts is missing Arabic import

### ISSUE THREAD

**Issue by mokbkalvad** [handsontable/handsontable#11214]
### Describe the bug

`handsontable\i18n\languages\index.d.ts` is missing the Arabic import 
`import arAR from './ar-AR';` 

### Handsontable version

14.6.0

### Your environment

Chrome/Edge/Firefox on Linux/Windows

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @mokbkalvad 

You are right, we miss 4 languages

```
ar-AR
cs-CZ
hr-HR
sr-SP
```

I will update you as soon as we fix it.

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by AMBudnik** [comment]
Hi @mokbkalvad 

Thank you again for the report. The new languages were added in v15.0.0
