### ISSUE TITLE
After returning false in **beforeRemoveRow** to prevent deletion, although the deletion was successfully prevented, a undo recovery record was recorded, resulting in the addition of rows that were prevented from deletion when clicking **undo**

### ISSUE THREAD

**Issue by wwh-lyl** [handsontable/handsontable#11216]
### Describe the bug

After returning false in **beforeRemoveRow** to prevent deletion, although the deletion was successfully prevented, a undo recovery record was recorded, resulting in the addition of rows that were prevented from deletion when clicking **undo**

### Video/Screenshots

https://github.com/user-attachments/assets/441eee9c-2dcc-4b94-8305-12a2ea241cd0

### Handsontable version

14.5.0

### Framework version

node：18.12.0 

### Your environment

windows10  ,Chrome129.0.6668.90

**Comment by wwh-lyl** [comment]
beforeRemoveRow: function(index, amount) {
      console.log('To prevent deletion of rows :>> ');
      return false;
  }

**Comment by AMBudnik** [comment]
Hi @wwh-lyl 

Could you please check the issue at https://github.com/handsontable/handsontable/issues/2325? It seems like it refers to the same bug.

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by AMBudnik** [comment]
> Could you please check the issue at https://github.com/handsontable/handsontable/issues/2325? It seems like it refers to the same bug.
