### ISSUE TITLE
copy data to handsontable,is column can auto add like row?

### ISSUE THREAD

**Issue by renjieyao** [handsontable/handsontable#11234]
### Improvement description

when I copy data to handsontable,the amount of data's columns is bigger than the amount of  my table columns,my table can auto add new columns?

**Comment by renjieyao** [comment]
![image](https://github.com/user-attachments/assets/480e43ac-a92d-445a-8653-42f1d4e57c82)
I want to use the copyPaste and the afterCopy to confirm my idea,but it can't work.please help me.

**Comment by renjieyao** [comment]
solved

**Comment by adrianszymanski89** [comment]
Hi @renjieyao 

I'm glad that you were able to solve the issue. Let us know if you have any other questions.
