### ISSUE TITLE
Deletion seams impossible when range of selection is outside of the viewport  

### ISSUE THREAD

**Issue by ChristopherGouin** [handsontable/handsontable#11242]
### Describe the bug

Hello,

I am unable to delete data from somes cells when a range of the selection is not visible 

### Video/Screenshots

https://github.com/user-attachments/assets/521d3382-2948-46ba-a80a-7504e6d70585

### Handsontable version

14.6.0

### Your environment

edge/linux, chrome/windàws

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report, @ChristopherGouin 

It seems that the partially visible selection area and `checkbox` are the mix that causes this issue, and it happens only in v14.6.0 and 14.6.1. It is a fresh regression. I marked it to be fixed.

I will updated you as soon as we fix it.

**Comment by AMBudnik** [comment]
Hi @ChristopherGouin 

Thank you again for sharing the issue report. We just released Handsontable v15.0.0 where this issue is solved.

**Comment by ChristopherGouin** [comment]
Hi, nice

Thank you for you work
