### ISSUE TITLE
AutoRowSize not working

### ISSUE THREAD

**Issue by Gandalf930526** [handsontable/handsontable#11257]
### Describe the bug

When I activate AutoRowSize and in a cell the text exceeds the size, the row does not expand, you can only see all the text if you access the cell

### Video/Screenshots

![image](https://github.com/user-attachments/assets/8e0311ba-41cd-4f84-8f88-a552efffa0c4)

### Handsontable version

14.6.1

### Your environment

Chrome and Mozilla, Windows 11

**Comment by adrianszymanski89** [comment]
Hi @Gandalf930526 

Thank you for contacting us. Can you please modify this example so it matches your settings? https://jsfiddle.net/handsoncode/r39746tz/

I checked with the `autoRowSize` enabled and it spreads the column width automatically.

**Comment by Gandalf930526** [comment]
> Hi @Gandalf930526
> 
> Thank you for contacting us. Can you please modify this example so it matches your settings? https://jsfiddle.net/handsoncode/r39746tz/
> 
> I checked with the `autoRowSize` enabled and it spreads the column width automatically.

![image](https://github.com/user-attachments/assets/58a2c05a-a96e-479a-bb73-114bdc847a79)
Hello, yes, what changes is the width of the column, but the correct thing would not be to change the width of the row.

**Comment by AMBudnik** [comment]
Hi @Gandalf930526 

My colleague is at a conference and asked me to answer all his pending tickets. However, I am not sure what the expected outcome is.

Please correct me if I misunderstood anything.

If you type a value that is longer than a column width
* column width should expand
* row height should NOT expand
* value should be fully visible within the cell renderer and cell editor

If that's not correct please share a draft/drawing of what is an expected outcome on a given input. Thanks in advance!

**Comment by AMBudnik** [comment]
Can I ask you to create a demo as my colleague proposed

> Can you please modify this example so it matches your settings?

Using @adrianszymanski89 setup

```
  data: Handsontable.helper.createSpreadsheetData(10, 10),
  colHeaders: true,
  rowHeaders: true,
  autoRowSize: true,
  licenseKey: 'non-commercial-and-evaluation',
```

works the same for me in the latest version as in v14.0.0 (in Chrome 131, macOS Ventura) - it expands the column width.

Now if you have `colWidths` in your setup, so we have now

```
  data: Handsontable.helper.createSpreadsheetData(10, 10),
  colHeaders: true,
  rowHeaders: true,
  autoRowSize: true,
  colWidths: 100,
  licenseKey: 'non-commercial-and-evaluation',
```

still both versions (latest and 14.0) act the same, but now they will show 2 rows and crop the value that is too long to be shown 
![Zrzut ekranu 2024-11-20 o 09 28 48](https://github.com/user-attachments/assets/ed70082d-9f04-4e60-9385-d10f6a062987)

**Comment by AMBudnik** [comment]
Hi @Gandalf930526 

I'm closing this issue as there is no demo to replicate the issue.

If you do not want to share it publicly, please send us a message at support@handsontable.com
