### ISSUE TITLE
The head does not follow the table as it scrolls

### ISSUE THREAD

**Issue by jin-benben** [handsontable/handsontable#11250]
### Describe the bug

In the Modal, The head does not follow the table as it scrolls
![image](https://github.com/user-attachments/assets/d689c5f2-435d-4f7f-9acd-0544ee33887b)

### Provide a link to the demo with the bug reproduction

https://github.com/jin-benben/handsontable.git

### Handsontable version

14.6.1

### Framework version

react 18.2

### Your environment

chrome：126.0.6478.127

**Comment by adrianszymanski89** [comment]
Hi @jin-benben 

I checked the code you sent, and it's most likely caused by the internal modal element styling interfering with Handsontable's styling. I tried several settings changes but found no solution. It looks like some part of the modal styling is affecting column headers.
