### ISSUE TITLE
ie8 bug when removing last row with spares

### ISSUE THREAD

**Issue by briansol** [handsontable/handsontable#1127]
When the last row is tried to be removed via context menu, and the settings are such that minSpares:1 is set, the following error occurs SOMETIMES in ie8.  It may be possible to reproduce in other methods, but this is how i was able to reproduce it after some testing.

![hot2](https://f.cloud.github.com/assets/5598104/1432454/b4435162-40de-11e3-9a36-805c217a1f46.png)

**Comment by AMBudnik** [comment]
We dropped support for IE8 and 9 in 0.12.0, if you would have any issue related to other browsers, please write us back.

**Comment by briansol** [comment]
This was created on .0.10.5  a year and a half ago.   As the app must support ie8, moving to the new version is not possible.
