### ISSUE TITLE
"colHeaders" not work while "columns" is set

### ISSUE THREAD

**Issue by RainThinks** [handsontable/handsontable#1129]
Check the the demo:
http://handsontable.com/demo/autocomplete.html

all headers are "A", "B", "C" ...., despite the "colHeaders" is set.

**Comment by motin** [comment]
For anyone ending up here experiencing the same problem with recent versions of handsontable (0.27) - a `colHeaders` function will not be used for columns with a `title` defined in the `columns` setting. HTML can however be used in the `title` property of a column, and if the `title` property is omitted, then the `colHeaders` function will be invoked for those columns.
