### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by 1004834495** [handsontable/handsontable#11332]
### Describe the bug

select editor How to achieve multiple choices

### Handsontable version

14.6.1

### Framework version

vue3

### Your environment

Chrome

**Comment by AMBudnik** [comment]
Hi @1004834495 

At the moment, each of the selection-type cells (select, dropdown, autocomplete) allows choosing only a single value per cell.

Please join the conversation at https://github.com/handsontable/handsontable/discussions/7879 to stay updated with the feature status.
