### ISSUE TITLE
Problems with undefined rows

### ISSUE THREAD

**Issue by marcsch** [handsontable/handsontable#1143]
I would like to use a Handsontable grid with potentially huge tables, and therefore tried to implement a plugin that only loads the rows that are currently visible. I already wrote about it here: https://github.com/warpech/jquery-handsontable/issues/607#issuecomment-26487435

Unfortunately, there were a few problems that seem all to be related to the fact that there are many undefined (not yet loaded) rows in the data array. I already wrote about that in my comment, but I will try to additionally illustrate the issues using jsfiddle:

1. Problems with the 'minSpareRows' option. All rows that weren't loaded seem to be treated as spare rows, and thus the array is truncated if minSpareRows > 0 (that was in earlier versions). In the most recent version of Handsontable, it just fails silently to create the table: http://jsfiddle.net/7Z3bD/19/
It would be convenient to have this option working with my plugin, but I'm not sure how this can be achieved.

2. Initializing and adding rows gets slow with > 100'000 rows. If I'm not mistaken, this is due to `countEmptyRows()` which is called by these events: http://jsfiddle.net/7Z3bD/21/
I'm no sure what this function is used for anyway. If it's just for adjusting the spare rows, then it does not make much sense in this use case.

3. Deleting rows in a table that is not entirely loaded will remove all undefined rows. (Try to do it manually in http://jsfiddle.net/7Z3bD/20/ and then scroll down)

4. Deleting columns will cause this error: "Cannot call method 'splice' of undefined" (Try to do it manually in http://jsfiddle.net/7Z3bD/20/)

5. Handing over an empty array as data will cause the table not to be displayed, even if the `colHeaders` are defined, and thus the number of colums should be known. The first row seems to be required (http://jsfiddle.net/5YkU9/1/). Of course, this is a very marginal problem that can be worked around easily.

In general I hope that I'm on the right track with the way I implemented the plugin...

**Comment by AMBudnik** [comment]
Most of this issues does not occur in newest version of [HOT](https://github.com/handsontable/handsontable/releases/tag/0.13.1). Please update to 0.13.1. 

If you would have any other questions/suggestions please open a new ticket (if it's possible a single subject for an issue - it's better to track changes in issues for other users.)
