### ISSUE TITLE
0.10.0-beta3 turning on nativeScrollbars causes js error in DragToScroll

### ISSUE THREAD

**Issue by trebuchetty** [handsontable/handsontable#1146]
DragToScroll.prototype.check = function (x, y) {
        var diffX = 0;
        var diffY = 0;

        if (y < this.boundaries.top) {
            //y is less than top
            diffY = y - this.boundaries.top;
        }
....

Specifically, the line: y < this.boundaries.top fails
this.boundaries is null, as is this.callback

To replicate this, I just turned on nativeScrollbars, then clicked on a cell and dragged the mouse to select a range of cells.

**Comment by AMBudnik** [comment]
Please check if after updating HOT to 0.13.0 you have the same issues, if so - please report the in a separate issue.
