### ISSUE TITLE
0.10.0-beta3 - Handsontable select list editor text overflow hidden

### ISSUE THREAD

**Issue by trebuchetty** [handsontable/handsontable#1147]
With 0.10.0-beta3, pulling up a handsontable select list hides the text that overflows the column width, so the extra columns can't be seen.

example: http://handsontable.com/demo/handsontable.html
click on a dropdown arrow for the first column. There should be 4 fields listed, but only the first column, plus a bit of the second is visible.

Also, trying to move the scrollbar to see the other columns just closes the editor.

removing the overflow: hidden or the position: relative from the "wtHider" node seems to show the rest of the list.

**Comment by AMBudnik** [comment]
Please check if after updating HOT to 0.13.0 you have the same issues, if so - please report the in a separate issue.
