### ISSUE TITLE
0.10.0-beta3 Moving through sub-handsontable using arrows

### ISSUE THREAD

**Issue by Niekess** [handsontable/handsontable#1152]
I have a handsontable filled with a variable amount of rows depending on which data will get used. Mostly the data is around 10 rows but sometimes it can be 60+.
One column contains a sub-table where I want to move through using my arrow keys, that sub-table got around 180 rows in it.

The problem I'm experiencing is that how more rows I have shown on the actual table (not the sub table) how slower the reaction is when I use my arrow keys to move through the sub-table. (With 3-10 rows shown it's fast but around 60 it takes one second to move down a row.)

I have done an UI responsiveness test and noticed that there are a lot of appendChild() and removeChild() events triggered. It looks like that it changes the selection in each row while seeing it visually in only one row.

![ss 2013-11-06 at 01_48_34](https://f.cloud.github.com/assets/790585/1482478/00adffbc-46e2-11e3-98ae-b5288242cb72.png)

My expectation is that when I press the arrow key I will directly move down one row in the sub-table and don't have to wait one second.

**Comment by AMBudnik** [comment]
Isssue closed in lack of demo.
