### ISSUE TITLE
setCellReadOnly

### ISSUE THREAD

**Issue by trebuchetty** [handsontable/handsontable#1153]
I see that this method was obsoleted back in 0.8.0, which is unfortunate. 

I have a row at the bottom of my table that is used for totals, so obviously I don't want users to be able to update/edit that row. In the settings, I check if the cell is in the last row of the table, then mark the row readonly. This works great visually. 

For pasting or editing a row, I have minSpareRows set to 2. This allows me to have a spare/empty row at the bottom of the table for pasting in new rows, or adding new rows manually. Followed by the totals row as the last row. The problem here though is that when I paste a dataset, the second pasted row is empty and all cells are marked as readonly. Same deal when I manually change a value on that bottom empty row (creating another empty row below it). the "new" empty row at the bottom is now readonly. 
The way I figured I'd change this is on the afterCreateRow or the beforeChange events, I'd manually set the readonly property for the row to false.

Is there a better way to be doing this?
Attached image shows what I'm trying to accomplish
![image](https://f.cloud.github.com/assets/2650592/1484457/410275aa-4707-11e3-8ef1-a6eae11fd9a6.png)

**Comment by AMBudnik** [comment]
Unfortunately I couldn't reproduce it. If you still have this issue please let us know.
