### ISSUE TITLE
Cell height too big when inputing text

### ISSUE THREAD

**Issue by cjones75** [handsontable/handsontable#1156]
Hi, 

On all the handsontable examples, the input box for cells stays within the confines of the cell. For me the input box always spills out of the cell:

![handsontable](https://f.cloud.github.com/assets/5878669/1490840/b3a70f94-479d-11e3-861b-26506758bdd6.PNG)

Any idea how to fix this:

Thanks

**Comment by AMBudnik** [comment]
Please prepare a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/) for that issue.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo for more than a month. If you still face this issue after updating to newest version, please prepare a demo.
