### ISSUE TITLE
Expose "logical to physical" and "physical to logical" methods

### ISSUE THREAD

**Issue by konrad-garus** [handsontable/handsontable#1161]
Column sorting is common use case, as is setting selection programmatically and getting contents of selected row.

With #989 I figured how to get data for selection, but I still don't see how I could convert physical row to displayed. For instance, I know that I want to select the 3rd row from my dataset - but which row is it in the sorted view?

It would be nice if the table or the sorter plugin exposed a convenient (and performant) way to do the translation.

**Comment by diskerror** [comment]
The documentation states that the methods "translateColIndex" and "translateRowIndex" are available but they are not accessible without manually changing source file. (v0.14.1 & v0.15.0-beta2)

For this to work:
```
hot = new Handsontable( document.getElementById('hot'), hotOptions );
row = hot.translateRowIndex(17);
```
I had to change line 5593 in handsontable.full.js (0.15.0-beta-2) from:
```
  function translateRowIndex(row) {
```
to:
```
  this.translateRowIndex = function(row) {
```
and update all internal references to use "this.".

**Comment by jiteshvassa** [comment]
Please see the following for an alternative solution.  https://github.com/handsontable/handsontable/issues/2718
