### ISSUE TITLE
Enhancement: Nested Tables

### ISSUE THREAD

**Issue by thelok** [handsontable/handsontable#1178]
It would be nice to have nested tables: a table within a table cell. 

We currently have a table that takes in a list of information. So, to represent this we need to add an extra "dimension" in addition to the 2D spreadsheet by using a second table.

We thought it might be nice to instead of having multiple disjoint tables it would be visually more appealing to have a table within a table.

Opinions?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
