### ISSUE TITLE
Autocompete requires double click on last column

### ISSUE THREAD

**Issue by johnhumbrecht** [handsontable/handsontable#1179]
If you set stretchH: 'all'  and have a vertical scroll bar the Handsontable.AutocompleteCell.renderer on the last column requires a double click to bring up the editor.  On other columns it only requires a single click.

See
http://jsfiddle.net/johnhum/eYw2v/

**Comment by AMBudnik** [comment]
I couldn't reproduce it with your demo and with HOT's demos provided on the website. If you still face this issue please provide your OS/Browser information. Until issue stays unanswered it will be closed.
