### ISSUE TITLE
data getting rogue line feeds

### ISSUE THREAD

**Issue by briansol** [handsontable/handsontable#1180]
Using .9 build 

Using the interface (not a paste) after hitting enter to move to the next row, i end up breaking my data.
Note my dates in col 3.

Col 3 was a col copy of col2,   The data pastes in with an extra line feed on the cell for some reason.

When the page is reloaded and re-init'ed with this data set, it fails..... and the user can't fix it...and thus, the JS throws an error because it split the var into physical lines of code.

I will enable some back end parsing to eat lines, but feel this is a bug.

![demo](https://cloud.githubusercontent.com/assets/5598104/6870001/9729830a-d46f-11e4-9709-e27c39edb137.png)

**Comment by AMBudnik** [comment]
Please provide a [demo](jsfiddle.net/api/post/library/pure/)

**Comment by briansol** [comment]
Geeze, this was a year and half ago....  I barely remember this.


I bypassed the bug by ran a routine that parsed the data and stripped out \r and \r\n from the end of each cell.

I no longer have access to the old src that this showed itself on

**Comment by AMBudnik** [comment]
OK, glad to know you got it working, and sorry for such a delay.
