### ISSUE TITLE
Awkward vertical scroll after copy-paste in the invisible area or bottom arrow press

### ISSUE THREAD

**Issue by hastenax** [handsontable/handsontable#1182]
Now I work with lot of copy-pasted data and I get same awkward behavior each time I copy-paste long vertical table.

If I pasted long vertical table (more than vertical visible table area) at visible area after data get pasted it scrolls me to the last pasted row. This is expected behavior I think and almost great feature. 

But If I press bottom arrow some times to get below the current viewport and paste data there, vertical scroll for some reason scrolled back to top for some rows(usually one row). I expected no scroll or maybe scroll down to the last pasted row, but not scrolling back.

Version: 0.10.0-beta3

**Comment by AMBudnik** [comment]
Hi, if you still experience this issue, please prepare a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/)

**Comment by AMBudnik** [comment]
Issue will stay closed until an author's reply.
