### ISSUE TITLE
Remove Row will not fire a Backbone event

### ISSUE THREAD

**Issue by nomad5000** [handsontable/handsontable#1188]
Hi,

I was checking out the Backbone.js Integration for handsontable.
http://jsfiddle.net/api/post/library/pure/
It seems that there are several bugs in that sample app. 

1- When I remove a row it will not fire a remove event in Backbone. 
(This happens because in the removeRow mehtod in handsontable.Core the rows to be removed are filtered instead of spliced.) I have tried to splice the rows, but sadly that introduces a new bug ):  
2- Once a row is removed, the table gets stuck. You can't remove Rows any more.

Maybe a test Spec for all the Backbone related stuff would be great.

Let me congratulate you for your great project!!!

Michael

**Comment by AMBudnik** [comment]
Hi @nomad5000 link you provide is for 'pure' (empty) JSFiddle, please provide working demo, if this issue still occurs.

**Comment by aliaksandr-dzemchanka** [comment]
Hi, you can find jsfiddle example [there](http://jsfiddle.net/e6u9dg3o/1/).
Thanks

**Comment by AMBudnik** [comment]
@aliaksandr-dzemchanka sorry for a delay. I assume you don't need any help with that any more?
