### ISSUE TITLE
Suggestion on ​Synchronization of 2 handsontables

### ISSUE THREAD

**Issue by praveenlobo7** [handsontable/handsontable#1192]
Hi All,

We are working on creating 2 handsontables with the synchronization of data between them.
![table 1](https://f.cloud.github.com/assets/5987400/1589188/c08a7056-5266-11e3-9bff-1655348b19d0.JPG)
![table 2](https://f.cloud.github.com/assets/5987400/1589189/c961e010-5266-11e3-997e-5041d1da4146.JPG)
 
Scenario 1:  The two tables are as shown in image. When i enter the coordinates in table 1 and enter the value, same value should appear in table 2 at position which is specified by table 1. 
Scenario 2: If we delete a value from table 2, the same should be deleted from table 1 based on the coordinates.

We ahve already designed the same, but there is lot of delay since we are keeping the snapshot of handsontable for each value.

Need help!!!

**Comment by AMBudnik** [comment]
Issue closed in lack of issue author reply.
