### ISSUE TITLE
Problem in adding different colors in different rows in Handsontable

### ISSUE THREAD

**Issue by SunandaChatterjee** [handsontable/handsontable#1193]
Hi,
I am using the SetDataAtCell API to add cell data in each row of Handsontable as and when data comes from the user dynamically. So, each row is added in the table one-by-one and in the begining of the row I have set persistantState as true.

The user also sends different color strings to be set as the background of each row along with the row data object. For that I am using the renderers under the "cells" option.

          var _getInstance = $(_container).handsontable('getInstance');
          _getInstance.setDataAtCell(changes);
          _getInstance.updateSettings({
                                 cells: function (row, col, prop) {
                                     if (row == currentRow) {
                                         this.renderer = _colorRenderer;
                                     }
                                    });      
This is the part of code for adding colors to each cell in a particular row. 
My problem is one row with proper color is rendered, but when I am trying to add the next row,the color of the previous row vanishes.
Can you please let me know where am I missing ?

**Comment by AMBudnik** [comment]
You can you [conditional formatting](http://docs.handsontable.com/demo-conditional-formatting.html) like in example code for the first row:

`if (row === 0) {
        cellProperties.renderer = firstRowRenderer; // uses function directly
      }`

with the renderer

`function firstRowRenderer(instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.background = '#CEC';
  }`

and color change can be recieved from HTMLs `<input type="color" />`

**Comment by AMBudnik** [comment]
I assume this issue can be closed. If you would have any other questions/suggestions feel free to create a new issue.
