### ISSUE TITLE
nativescrollbars option causes large amount of jank when scrolling browser

### ISSUE THREAD

**Issue by trebuchetty** [handsontable/handsontable#1194]
Subject pretty much says it all. There's a lot of jank in the screen when scrolling the browser with nativeScrollbars enabled. 
Using Chrome devtools it looks like it's doing some pretty expensive style recalculations. 
The biggest culprit seems to be this method: 

```javascript
WalkontableHorizontalScrollbarNative.prototype.getScrollPosition = function () {
        if (this.scrollHandler === window) {
            return this.scrollHandler.scrollX;
        }
        else {
            return this.scrollHandler.scrollLeft;
        }
    };
```

which comes from here:

```javascript
WalkontableVerticalScrollbarNative.prototype.onScroll = function (forcePosition) {
    ...
    this.instance.draw();
}
```

![image](https://f.cloud.github.com/assets/2650592/1604226/6566178a-53b9-11e3-9179-e27e281d10d6.png)

There's gotta be a better way of doing this.

**Comment by AMBudnik** [comment]
Related to https://github.com/handsontable/handsontable/issues/2404

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/2404
