### ISSUE TITLE
Hidden Columns (attaching data)

### ISSUE THREAD

**Issue by skilesare** [handsontable/handsontable#120]
Is there a way to put 'hidden' data in the table.  Basically I want to associate an ugly primary key with a row but not show it to the user.  I did a legend that set the display to none, but the column still gets picked up by the keyboarding code and shows the fill bar in the wrong place.

http://jsfiddle.net/FDpvV/8/

There may be some other way to assigning data to a row that I don't know about.

**Comment by atul-bhosale** [comment]
Column hidding demo
https://docs.handsontable.com/pro/1.0.0/demo-hiding-columns.html
