### ISSUE TITLE
Multiselection in a dropdown cell style

### ISSUE THREAD

**Issue by Merlino** [handsontable/handsontable#1201]
![image](https://f.cloud.github.com/assets/3223614/1648509/4cd7b48e-59a0-11e3-928d-46d5ea17a1b1.jpg)
How to implementation multiselection in a dropdown menu?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by cumtwwei** [comment]
@AMBudnik 
How to do it now? Please.
Thanks a lot.

**Comment by AMBudnik** [comment]
Hi @cumtwwei the feature is not yet available.

**Comment by Even-Lau** [comment]
6 years passed. Why not just add this feature? @AMBudnik 
Have you solved it yet? @Merlino

**Comment by AMBudnik** [comment]
It was never the no 1 priority. We are aware that many users are waiting for this feature to be added, however, I cannot guarantee that it will be added this year.

**Comment by rashan** [comment]
Probably the following can be a solution:
https://github.com/mydea/handsontable-chosen-editor

Demo: http://mydea.github.io/handsontable-chosen-editor/

**Comment by sahul343** [comment]
> Probably the following can be a solution:
> https://github.com/mydea/handsontable-chosen-editor
> 
> Demo: http://mydea.github.io/handsontable-chosen-editor/

Thanks can I use it in react, are there any compatibility problems with react

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
