### ISSUE TITLE
Fixed columns resize problem

### ISSUE THREAD

**Issue by nms666** [handsontable/handsontable#1206]
Hi

When in fixed columns mode and a column is expanded (after input) there is a problem with the scroll / select.

On the example below just edit some cells with some large text and try to go to the cells on the right.

http://jsfiddle.net/gvtGm/

**Comment by AMBudnik** [comment]
I couldn't reproduce that issue, please leave a feedback if it still occurs.

**Comment by AMBudnik** [comment]
I guess there's not an issue any more cause of 3 weeks without an answer. If you would still face this issue - please reply.
