### ISSUE TITLE
Attach a spin to handsontable until there is no callbacks left

### ISSUE THREAD

**Issue by coder80s** [handsontable/handsontable#1210]
Hello,

I'm working on a dependant handsontable from another control, updating the totals depending on certain values of that control and I would like to attach a spin, so it works until handsontable has ended to do all the operations.

Someone has done some kind of spin control (or he/she has integrated from an external component like Spin.js) that works until handsontable has ended all its callbacks?

If not, wouldn't it be a nice option to attach an spin when handsontable has finished with all the callbacks? It would be useful for big tables, as handsontable looks sometimes blocked when there are a lot of operations pending to finalize.

**Comment by AMBudnik** [comment]
Issue closed in lack of an authors reply
