### ISSUE TITLE
Horizontal scrolling problems When Row Height and Column Width Are Not Fixed Dimensions

### ISSUE THREAD

**Issue by nsubordin81** [handsontable/handsontable#1213]
Within the viewable portion of the handsontable spreadsheet, the cell heights in a row conform to the tallest visible cell. As the user scrolls and some rows go out of visiblity and others come in, the entire row changes height according to which cell is now the tallest. Several rows having this issue in concert can cause large fluctuations in the height of the entire spreadsheet.

The resizing behavior of row height can be addressed with the CSS workaround proposed in #123, however when one does not wish to constrain the height of cells or truncate overflowing text there is no way to preserve expected Excel like scrolling.

Another issue comes up when scrolling horizontally when colWidth isn't set. If columns have varying widths, as  a user keys to the right across columns, in some cases the table will not scroll across following the active cell but instead the whole table will jump forward or back a whole page width and the active cell will no longer be visible on the screen. This issue also has a partial remedy of setting a colWidth value in the configuration options so all columns are the same width, but the auto sizing of the columns to the text is lost and there is a lot of extra white space for shorter entries.  

These two issues in combination have become notable concerns in our system to the extent that we have a future plan to move to another API for our table rendering. Handsontable is an excellent tool with a lot of great features, addressing these two issues would be a huge step in providing a better user experience in future releases.

**Comment by AMBudnik** [comment]
Please prepare a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/). It would be much easier to completly understand and reproduce your issue - if you still face it (after updating to 0.13.1 if it's possible).

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
