### ISSUE TITLE
Question re. sorting

### ISSUE THREAD

**Issue by owenj1976** [handsontable/handsontable#1217]
Hi,
This may be me being stupid, so bear with me. I have a table which users can edit, I get the data they have edited via the afterChange event, this gives me the data that has changed and I then use the getData() function to join this back up to the original array. This is all fine but after using the sort plugin (as it says the view is sorted not the data) there doesn't seem to be a way of working out which row of the original data should be updated. Is there a mapping between the original data and sorted data I am missing? Any advice would be fantastic. Thanks

**Comment by aaronbeall** [comment]
What if `filters` are applied as well? It seems this doesn't take that into account...
