### ISSUE TITLE
Edit cellValue problem

### ISSUE THREAD

**Issue by jimmykwong** [handsontable/handsontable#1218]
1. when i edit the cellValue,which is multiple line text,i can not  move the cursor to above/below line by pressing the arrow up/down, but move to above/below row.
2. when the  cursor in the begin/end of text , it will move to  next column by pressing the arrow left/right, i think it is very inconvenient for editing. it will good if just like what excel do.

I'm so sorry about my bad english, i hope that you can understand what i mean.
Thanks!

**Comment by AMBudnik** [comment]
For more information about this subject, please track changes to issue https://github.com/handsontable/handsontable/issues/2182
