### ISSUE TITLE
Wrong position of DatePicker dialog

### ISSUE THREAD

**Issue by agershun** [handsontable/handsontable#1223]
I use Handsontable with Bootstrap theme. When I use datepicker component the system overlap edit field over datepicker dialog:

pic1 - problem
https://www.dropbox.com/s/en5wtq5i0jat1r7/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202013-12-15%2008.11.28.png

The source of problem that Handsontable does not take in account the padding values of cells.

To fix this problem, it is possible to change the line in jquery.handsontable.full.js :
    this.datePickerStyle.top = (offset.top + $td.height()) + 'px';    
to this line:
    this.datePickerStyle.top = (offset.top + $td.outerHeight()) + 'px';    

pic2 - after fixing
https://www.dropbox.com/s/lh5isdv6l61fm1v/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202013-12-15%2008.11.04.png

**Comment by AMBudnik** [comment]
If someone would still face this issue, please update to [0.12.6](https://github.com/handsontable/handsontable/releases/tag/0.12.6) (or newer) - where Datapicker was replaced with a Pikaday.
