### ISSUE TITLE
0.10.0-beta3 checkbox renderer

### ISSUE THREAD

**Issue by trebuchetty** [handsontable/handsontable#1226]
Any reason why the checkbox renderer doesn't also apply the htDimmed class to the TD?

    if (cellProperties.readOnly) {
        instance.view.wt.wtDom.addClass(TD, 'htDimmed'); // should add this line

From a css perspective, it helps to have a class mark all of the readOnly cells

It was also be sweet if we could do something like:

    cellProperties.cssClass = 'someAwesomeCSSClass';
in a custom renderer so that we could add any classes to the TD as we need.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Currently you are able to set read-only property for checkboxes. Demo: http://jsfiddle.net/handsoncode/Le0vdpqw/
