### ISSUE TITLE
Native scroll div  can't  fixedColumnsLeft 

### ISSUE THREAD

**Issue by antsingle** [handsontable/handsontable#1227]
Native scroll div  can't  fixedColumnsLeft  and row 1 row 2 can't be selected .
http://jsfiddle.net/BFRqp/

**Comment by AMBudnik** [comment]
Can you provide more info? With your [demo](http://jsfiddle.net/BFRqp/2/) updated with new file specification, there is not an issue to select first or second row.

**Comment by AMBudnik** [comment]
If you still face this issue please reply and we will reopen this issue. I close it in lack of reply for more than a month.
