### ISSUE TITLE
On copying single column from excel and Pasting on handsontable single column the blank cells are being deleted before and after data cells.

### ISSUE THREAD

**Issue by mypran** [handsontable/handsontable#1233]
Hi,

I am trying to copy a single column from excel to handsontable as attached where the blank cells are getting deleted before cells containing data. (eg., in attached scenario the blank cells before "dd" and after "ee" are getting deleted. I think it should preserve the blank cells on pasting to hands on table single column.

![image](https://f.cloud.github.com/assets/6203614/1809690/c11936c8-6e00-11e3-953e-39c2f4201e8a.png)

![image](https://f.cloud.github.com/assets/6203614/1809714/82ceadec-6e02-11e3-988b-5d900c38da05.png)

When I copy from excel and paste into text editor and enable white spaces to be shown the CR LF are visible for each data cell as attached. so i think we should not strip/replace the blank cells CR LF.

![image](https://f.cloud.github.com/assets/6203614/1809700/9b914192-6e01-11e3-9e4c-8ba62d035186.png)

Thanks,
Praveen

**Comment by AMBudnik** [comment]
How you're copying (keyboard shortcuts or a function)? When I copy from a text editor on mac or from a spreadsheet in Google docs using `command` + `C` empty rows are pasted also.

**Comment by AMBudnik** [comment]
Issue closed in ack of recent activity.
