### ISSUE TITLE
The edit cell moves when scroll up or down with mouse wheel

### ISSUE THREAD

**Issue by CNiq527** [handsontable/handsontable#1234]
When editing the cell, scroll down or up with mouse wheel, and the cell which is editing move up/down. This can reproduce in any demo with vertical scroll bar. 
Is this a bug? The behave in excel is different, when scroll up/down, the cell still in editor mode, but will not move up/down when scroll up/down with mouse wheel.

**Comment by AMBudnik** [comment]
Can you provide a step by step report how to reproduce this issue?

**Comment by CNiq527** [comment]
This issue was introduced in 0.9.* version of handsontable, just tried to reproduce this issue in IE 11, but it could not reproduced, I think it's no long exist in current stable version any more.

**Comment by AMBudnik** [comment]
Ok, thank you for support.
