### ISSUE TITLE
Issue with the scrollbar

### ISSUE THREAD

**Issue by SunandaChatterjee** [handsontable/handsontable#1237]
Hi there,

I am working with handsontable where on selection of each row a renderer gets applied for that particular row. If I try to scroll the horizontal scrollbar back-and-forth after selecting a row, some portion of the row does not get rendered. It gets re-rendered once selection is made on a different row. The text should always appear even with the selection.

 http://jsfiddle.net/Sunanda/mYBs6/
  
![datarendering](https://f.cloud.github.com/assets/5037602/1821582/74449c4e-7138-11e3-95a5-78c8012df7f7.png)

Again, if I try to scroll the vertical scrollbar downwards, then a portion appears empty. I want it always to be filled with rows so that no empty space appears at the bottom. I tried with minSpareRows property but still the space appears for some cases.

![extraspace](https://f.cloud.github.com/assets/5037602/1821595/1cd2d1e6-7139-11e3-962b-805237642899.png)

Can you please suggest some way out for both these above mentioned scenarios.

Thanks in advance,
Sunanda

**Comment by AMBudnik** [comment]
If you still experience problems with this code, please reply. As it a topic without recent activity it will stay closed till an author's reply.
