### ISSUE TITLE
setDataAtCell throws exception if value=null

### ISSUE THREAD

**Issue by aldmiller** [handsontable/handsontable#124]
When calling setDataAtCell with value set to null, the 'backwards compatability' condition is triggered because typeof evaluates to an object even though it is set to null.  Changes is then set to null, and the exception is thrown in the following for loop because changes.length does not exist.

Suggest changing line 2093 as follows

IS: `else if (typeof value === "object") { //backwards compatibility`
SHOULD BE: `else if ((typeof value === "object") && (value != null)) { //backwards compatibility`

**Comment by andraz-podobnik** [comment]
Hi,

I just tested this with Handsontable version 13.1 and it's not working (when an array of changes is used).
Fiddle: https://jsfiddle.net/sgt9qv2k/2/

I believe there's no workaround for this?

**Comment by AMBudnik** [comment]
Hi @andraz-podobnik 

If you choose to use an array of changes, it should be an array of arrays (even when there's only one change listed). Here's the demo https://jsfiddle.net/kmhtfgc8/

**Comment by andraz-podobnik** [comment]
Oh, my bad, thx for quick answer.
