### ISSUE TITLE
Dropdown with DisplayText and Value return

### ISSUE THREAD

**Issue by honeypc** [handsontable/handsontable#1240]
I want using dropdown like select tag because I can show DisplayText and on change Value save . How do using it ?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
