### ISSUE TITLE
Autocomplete doesn't remove options from dropdown list when using a function to populate

### ISSUE THREAD

**Issue by amclin** [handsontable/handsontable#1241]
In v0.10, When the autocomplete source is a function (instead of a static array) the unmatched items don't get removed from the possible value list.

**Example:**
http://jsfiddle.net/JzL2L/

Compare the behavior of the **Car** column to the **Color** column. Color column has been modified from the example documents to use a function.

**Comment by AMBudnik** [comment]
Please update to 0.14.1 or newer. I tried your example code with a static data and a function, both works fine.
