### ISSUE TITLE
IE 10 - Can't select cell using mouse click when horizontal scrollbar is on the left side.

### ISSUE THREAD

**Issue by kmanoh** [handsontable/handsontable#1246]
Steps to reproduce:

1. URL: http://handsontable.com/demo/scroll.html
2. Use Internet Explorer 10 Browser
3. Try to click on a cell from any of the left side column (A, B, C, etc.).
4. When we click on the cell, scroll bar moves towards right

Thank you for the good work.

We have used this control in our application and we can't skip IE 10 :(

**Comment by AMBudnik** [comment]
Please check if it still occurs. I tried it on IE 10, but it works fine with the latest version.
