### ISSUE TITLE
copy/paste conflict with contenteditable

### ISSUE THREAD

**Issue by dfortner** [handsontable/handsontable#1247]
If handsontable is included in a site with contenteditable elements, it is still possible to copy text from the contenteditable. But when you want to paste some text into it, it won't work.

jsFiddle: http://jsfiddle.net/hU6Kz/2531/

Is it possible to confine your pasting-function just to the .handsontable-divs?

**Comment by AMBudnik** [comment]
Please update to [0.14.0](https://github.com/handsontable/handsontable/releases/tag/0.14.0) it works as expected.
