### ISSUE TITLE
Double Click does not work

### ISSUE THREAD

**Issue by aparthas** [handsontable/handsontable#1249]
Hi,

   I have a Textbox and  a Textarea in the Handsontable header.  I am unable to double-click and select the textbox or the textarea contents or use the mouse and select the contents.

   I have created a JSFiddle for this.. http://jsfiddle.net/aparthas/Wjz97/2/

   Am i missing something? if not is there any way to get around it? 

   Thanks....

Thanks,
Ashok

**Comment by AMBudnik** [comment]
Please check [this demo](https://jsfiddle.net/c1Lav2ng/), works fine with 0.16.1 in IE 11. Issue will stay closed till new activity.
