### ISSUE TITLE
PersistentState Save/Load via ajax

### ISSUE THREAD

**Issue by arafiq** [handsontable/handsontable#1254]
I apologize in advance if this feature currently exists. But I wanted to know if there is a way to save/load the persistent data via ajax to the server as opposed to localStorage.
If not can I request one. It's rather tricky to save info to localstorage as there is no security and can easily be erased with the browser settings.

**Comment by AMBudnik** [comment]
I guess [this](http://handsontable.com/demo/ajax.html) demo could help.

**Comment by AMBudnik** [comment]
OK, I guess this issue can be closed in lack of other questions.

**Comment by xyrintech** [comment]
I believe, the state saving is not allowing the ajax load. 

When we hit the persistentStateLoad then there is no affect.
