### ISSUE TITLE
New autocomplete problem

### ISSUE THREAD

**Issue by fcofabricio** [handsontable/handsontable#1255]
After upgrade to version 0.10.0 a autocomplete column change the layout behaviour. In this column I use a logic after selection to get only one part from the complete value.

Before (0.9.17):

![beaver - projects](https://f.cloud.github.com/assets/1823858/1878492/487dc53e-793c-11e3-902b-ad82f548e431.jpg)

After (0.10.0)

![beaver - projects 1](https://f.cloud.github.com/assets/1823858/1878496/5405d662-793c-11e3-9620-cc532c62c744.jpg)

**Comment by YipYipX4** [comment]
FYI: In issue #2380, I provided a few different fixes for the AutoComplete drop-down list using only CSS.  One of the fixes is a min-width (I don't know how to make it auto-fit the contents, so I used a min-width as a next-best option).

**Comment by AMBudnik** [comment]
Still present in 0.24.1

**Comment by alvarotrigo** [comment]
+1

**Comment by AMBudnik** [comment]
@alvarotrigo @slabbint @fcofabricio 
I was told that we cn do the same using [`trimDropdown`](https://docs.handsontable.com/pro/1.5.0/Options.html#trimDropdown) option
demo: http://jsfiddle.net/aka57qkb/2/

**Comment by alvarotrigo** [comment]
@AMBudnik thanks! that looks like a solution!
