### ISSUE TITLE
search and sort

### ISSUE THREAD

**Issue by zipzapduo** [handsontable/handsontable#1256]
i have implemented a search that hides the rows that dont follow the keyword. it happens taht when i sort one column , it takes in concern all data and not just the filtered ones.How to achieve that?

**Comment by AMBudnik** [comment]
If you still face this issue, please prepare a full [demo](https://jsfiddle.net/api/post/library/pure/) of your code.

**Comment by AMBudnik** [comment]
I assume this issue can be closed in lack of author's reply. If you still face this issue, please leave us feedback.
