### ISSUE TITLE
afterCreateRow callback passes a wrong position

### ISSUE THREAD

**Issue by mariolopes** [handsontable/handsontable#1257]
afterCreateRow(arg1, arg2) is passing the wrong position of the newly created row (through arg1). When inserting a row below, the position passed is of the current row instead of the newly created row. When inserting a row above, the argument passed makes no sense at all. It returns (actualPos - 2).

Using latest release available on dist/ from master branch.

**Comment by AMBudnik** [comment]
I assume this issue is solved and it can be closed. If you would have any other questions, please open a new issue.
