### ISSUE TITLE
event wish: prevent editor from closing

### ISSUE THREAD

**Issue by splitbrain** [handsontable/handsontable#1267]
I'm trying to integrate a toolbar with Handsontable. When a user edits a cell, he can click a toolbar button to insert certain markup in the open editor. Currently the active editor will be closed whenever you click outside the editor.

For my purposes I hacked the mousedown event (tableView.js around line 64) to contain a check on the ```next``` element. If it is one of my buttons I return from the function. It would be nice if this could be done by registering on some event. 

Alternatively it might be an idea to pass the event object down to the ```close()``` method of the editor, so I could simply implement the check in a custom editor.

Or is there a way I missed?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
