### ISSUE TITLE
Saving only rows with data in it

### ISSUE THREAD

**Issue by snelson87** [handsontable/handsontable#1271]
Is there a way to send only rows with data in them? Handsontable automatically creates an empty row under the row you are typing in. When I post that data I do not want that empty set of data. How do I delete that empty row?

**Comment by SalihKARAHAN** [comment]
maybe you can use .slice(0, datasource.length-1);

**Comment by friek108** [comment]
I did something like this:
```
var gridData = hot1.getData();
var cleanedGridData = {};
    
$.each( gridData, function( rowKey, object) {
    if (!hot1.isEmptyRow(rowKey)) cleanedGridData[rowKey] = object;
});
```
