### ISSUE TITLE
Horizontal scrolling is jumpy when drag down

### ISSUE THREAD

**Issue by CNiq527** [handsontable/handsontable#1272]
When drag down to fill the content to other cells, the horizontal scroll bar is jumpy, perhaps the same issue referenced in https://github.com/warpech/jquery-handsontable/issues/789, this could be reproduced in IE 10(10.0.9200.16438) in any HOT with horizontal scroll bar, but it's ok in IE 11.

**Comment by AMBudnik** [comment]
Replicable in IE11, Handsontable v 0.31.0

**Comment by AMBudnik** [comment]
Hi @CNiq527 

Please check version 0.32.0-beta1
You should now experience the 'jumping' behavior in Internet Explorer or Edge.

**Comment by AMBudnik** [comment]
I am closing this issue but if you'd experience similar behavior please let me know

**Comment by CNiq527** [comment]
@AMBudnik that's cool. sorry to say that i've left the company and the source code and environment is not available right now ;(

**Comment by AMBudnik** [comment]
Oh I see @CNiq527 

Thank you for your response. We will have a lot to improve when it comes to IE/Edge so I hope one day it will work as fast as a blink :-)
