### ISSUE TITLE
Handsontable - Ajax save  POST doesnt work

### ISSUE THREAD

**Issue by Blackscr33n** [handsontable/handsontable#1274]
hi guys,

i am using the handsontable plugin and i want to save the changes on a table in a database, i read the examples but it still doesnt work! here my code!
and the error occurs 100% at ajax! plz help my guys!

![screen](https://f.cloud.github.com/assets/6410789/1921439/148be0ea-7dfa-11e3-93aa-d9c679aa00d1.png)

**Comment by AMBudnik** [comment]
Does it still occur after updating to 0.14.1?

**Comment by AMBudnik** [comment]
I assume this issue can be closed, but if you would have any issues about this behaviour with latest version please let us know.
