### ISSUE TITLE
How move scroll horizontal using code in handsontable? <Question>

### ISSUE THREAD

**Issue by coldark** [handsontable/handsontable#1279]
To read value i use,  str += 'colToProp: '+ $("#example1").data('handsontable').colOffset();
How can i write a value to move the scroll to other position? 
I review this and probe using different ways

https://github.com/warpech/jquery-handsontable/wiki/Options
https://github.com/warpech/jquery-handsontable/wiki/Methods
and probe using different ways, but  i can't change this value to move the scroll
In properties of handsontable don't see how change this Value.
the objective is pulse the top buttons move to back year or back month or next or month next year.
![imagen](https://f.cloud.github.com/assets/4923566/1939263/6cc106d6-7f5e-11e3-9706-ba4f49ffc87d.png)

**Comment by AMBudnik** [comment]
Hi, If you still face this issue please provide a demo of your code.

**Comment by AMBudnik** [comment]
issue closed in lack of needed demo.
