### ISSUE TITLE
Problem of events in jquery dialogs

### ISSUE THREAD

**Issue by faubertin-FA** [handsontable/handsontable#1281]
Hello,

We have several problems with handsontable and jquery dialog.

Some of the handsontable event handlers are not called since jquery dialog event handlers are called before, preventing handsontable to handle these events. 

According to one of the jquery dialog widget event handler :
 // stop events if the z-index of the target is < the z-index of the overlay
// we cannot return true when we don't want to cancel the event (#3523)

Some HTML elements have their z-index attribute set : 
- handsontableInputHolder) with a value too small.
- the copyPaste textarea created on the fly have no z-index set.

Libs are : jquery 1.9.1 and jquery UI 1.8.24

Thanks

**Comment by AMBudnik** [comment]
Hi, it would be very helpfull if you could update to 0.13.1 and reply if this issue or similar occurs in your code after updating.

**Comment by AMBudnik** [comment]
Issue will stay closed till a reply will appear.
