### ISSUE TITLE
How do I stop receiving external callbacks in Handsontable 0.10.X?

### ISSUE THREAD

**Issue by coder80s** [handsontable/handsontable#1286]
Hello everyone,

I'm working currently in a project under C# (to obtain and save data) and JavaScript, and I'm using  two handsontable tables (version 0.10.x), (lets say that A is master and B is slave). The B handsontable do some calculations in order to update certain cells in A, something like this example: http://jsfiddle.net/SBRvZ/31/

When I try to do a manual setDataAtCell from B to update certain cell in A, this situation produces much more than one callback in A beforeChange event.

I'm able to determine when a callback contains the same changes as a previous callback in A, but I'm not able to order handsontable to stop receiving external callbacks when receiving some changes. Is there any method to stop receiving external callbacks in Handsontable?.

I tried to use destroyEditor() method but it doesn't look like to work, the other workaround I tried is to ignore these callbacks, that doesn't look like to stop receiving the same changes again and again.

I would appreciate any support on this topic

**Comment by AMBudnik** [comment]
Issue will get reopened with an author reply/request.
