### ISSUE TITLE
Validation fails after column move

### ISSUE THREAD

**Issue by xsim** [handsontable/handsontable#1287]
When one or more column is moved, validation is either very slow or the editor is stuck in the validating cell and it is not possible to edit any other cell:

![image](https://f.cloud.github.com/assets/6488296/1992068/92379a5a-84af-11e3-850c-0a91a5773d51.png)

I have used the jsfiddle of the validation example with column move enabled and allowInvalid is true for the IP and email columns. Moving the IP and email column, would result in the above error. Another issue is that the validation is not triggered as it can be seen in the email column.

**Comment by AMBudnik** [comment]
It should work as expected. Please udpdate to [0.14.1](https://github.com/handsontable/handsontable/releases/tag/0.14.1) and if you will still face this issue, please reply with your OS/Browser information.
