### ISSUE TITLE
Scroll handle not functioning properly when handsontable is maxed

### ISSUE THREAD

**Issue by thronic** [handsontable/handsontable#1296]
We have a handsontable that is being used and we're setting it to the max height of the browser window. We're noticing that the scroll handle sometimes act funny and/or will scroll to the end of the sheet but there will be a 100px gap or so. If we drag the handle to the bottom of the scrolling area it will pause and then jump up 50 or 80 px. 
![scrollwheel-handsontable](https://f.cloud.github.com/assets/6546113/2042083/f5ef4f1c-89cc-11e3-8346-889f30fee1b0.png)

**Comment by AMBudnik** [comment]
Can you please update to 0.13.1 and check if it still occurs if so, please provide a demo.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
