### ISSUE TITLE
When paste and never before move the scroll

### ISSUE THREAD

**Issue by coldark** [handsontable/handsontable#1297]
when i have readonly rows and paste a matrix with elements, the handsontable is copy full data over handsontable hide elements with or without read only protecction but when i move the scroll to the end and paste only in this way the paste is ok and write only where readonly isn't activated.
![error2](https://f.cloud.github.com/assets/4923566/2042526/8643e078-89d2-11e3-8912-4a81112ce91e.png)

**Comment by AMBudnik** [comment]
[JSFiddle](http://jsfiddle.net/api/post/library/pure/) will be appreciated, without a demo there's not more we can say.

**Comment by AMBudnik** [comment]
@coldark please update to [0.14.1](https://github.com/handsontable/handsontable/releases/tag/0.14.1) and check if you still face the issue. If so - please prepare a demo and we'll reopen the issue for you.
