### ISSUE TITLE
Destroy Memory Leak

### ISSUE THREAD

**Issue by insraq** [handsontable/handsontable#1304]
JSFiddle: http://jsfiddle.net/yvbJt/

The method "destroy" does not really destroy all the memory footprint. The DOM will end up being detached DOM and leak memory.

To reproduce with the above fiddle:

1. Take a heap snapshot using Chrome Dev Tools.
![1](https://f.cloud.github.com/assets/608221/2077109/ee8ec322-8dac-11e3-9039-ea55da0bc4fe.PNG)
2. Click open and destroy button, take another snapshot
![2](https://f.cloud.github.com/assets/608221/2077115/fa5c386a-8dac-11e3-8430-49787cb7225b.PNG)
The memory footprint has increased significantly. And looking at the delta (comparison with snapshot 1), all the DOM of the table is detached.
3. Click open and destroy button again, take snapshot.
![3](https://f.cloud.github.com/assets/608221/2077123/27e4e638-8dad-11e3-94dd-83d3124a57d4.PNG)
The same detached DOM has increased by 1 (delta = 1), further prove the memory leak.

This is not a problem if you do not destroy and re-initialize handsontable very frequently. If you do, it can cause a significant amount of memory leak, depending on the size of the table. If unfortunately you have the logic in your code. One workaround is to use "updateSettings" and "loadData" to reset handsontable and avoid calling destroy.

But I think this issue is quite important as for lots of SPAs, as the page does not refresh very often, properly cleaning-up is very important.

**Comment by AMBudnik** [comment]
I assume after updating to 0.11.0-beta4 (or newer) issue does not occur any more. If it still will be an issue, please reply in the same issue.
