### ISSUE TITLE
Must double-click cell to add negative number in Firefox

### ISSUE THREAD

**Issue by ryanwjackson** [handsontable/handsontable#1305]
We have found it necessary to double-click to add a negative number in Firefox.  We cannot reproduce this behavior in Chrome or Safari, and we have tried shifting the code around to see if it might have to do with a configuration option.  In Firefox, you can get it to work (single click to highlight a cell and type negative number) if starting with the negative sign on a numberpad (i.e. not above the lettered keys).  But if you use the negative sign above the lettered keys, it does not start typing in the cell.

I am thinking this is a bug but am definitely open to hearing it is a flaw in our implementation.  Unfortunately, the table is behind authentication at www.visible.vc.  Let me know if there is more I can do to help.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.
