### ISSUE TITLE
Incompatible with IE < 8 or documentMode < 8

### ISSUE THREAD

**Issue by hh-lohmann** [handsontable/handsontable#1306]
Due to use of querySelector (see https://developer.mozilla.org/de/docs/Web/API/Element.querySelector#Browser_compatibility) users of Internet Explorer (yes, they exist) have to use at least IE 8 with at least document mode 8 (see e.g. http://msdn.microsoft.com/en-us/library/ie/cc196988%28v=vs.85%29.aspx) - document mode may be manipulated by sites, pages or users to get compatibility with older (maybe non-standard) stuff (some of us remember IE 6 ...).

Should at least be noted appropriatly, at the moment with IE / document mode < 8 handsontable breaks whole page's Javascript and therefor lets tables disappear.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
