### ISSUE TITLE
Problem with sorting numeric values

### ISSUE THREAD

**Issue by kdenholm** [handsontable/handsontable#1307]
I have a site that was built in Joomla 3.1 and uses mootools throughout.  I love this jquery handsontable and decided to use it in one of the pages.  I can get most of the functionality to work just fine, but I can't seem to get the columns with numbers to sort correctly (they are treated as strings).  I see a fix was put in prior to the 0.10.2 version that I'm using so I think my issue might lie in a conflict with mootools.  I'm hoping someone has some insight into dealing with this or I'll have to find a mootools grid.  :(  

Here is a sample line from my grid:
{data: "sale_price", type: 'numeric', readOnly: true, format: '$ 0,0.00', copyable: true, language: 'en'},

I have included numeric.js

Thank you!

**Comment by AMBudnik** [comment]
Since 0.12.6 we're jQuery-free. Thank you to.
