### ISSUE TITLE
Feature Request: Add zeroFormat option for numeral.js

### ISSUE THREAD

**Issue by zxi** [handsontable/handsontable#1315]
Add support for *numeral.zeroFormat* similar as *numeral.language* in **NumericRenderer**.

```js
if (typeof cellProperties.language !== 'undefined') {
    numeral.language(cellProperties.language)
}
if (typeof cellProperties.zeroFormat !== 'undefined') {
    numeral.zeroFormat(cellProperties.zeroFormat)
}
```

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
