### ISSUE TITLE
Feature Request: add Internationalization to context menu

### ISSUE THREAD

**Issue by pizarropablo** [handsontable/handsontable#1316]
add internationalization to actions in context menu.

"insert row above" translates to spanish "insertar fila arriba".

I'm just hardcoded the code.
I'm trying add a more "elegant" solution.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
