### ISSUE TITLE
How to do descending row number sort by default?

### ISSUE THREAD

**Issue by brianmingus** [handsontable/handsontable#1321]
I've read through the documentation and tried many configurations but I can't figure out how to get Handsontable to simply reverse its normal sort order, i.e., with the element that would normally be last at the very top.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Currently this option is available by using the [sortOrder](https://docs.handsontable.com/pro/1.10.0/demo-sorting.html).
Here's a working demo http://jsfiddle.net/handsoncode/wdm658vj/
