### ISSUE TITLE
Event: beforeColumnMove

### ISSUE THREAD

**Issue by bpostlethwaite** [handsontable/handsontable#1322]
I am attempting to keep a meta data array in sync with the underlying data array of array object and require an event to fire upon moving that will fire before afterGetColHeader. Also this adds reasonable symmetry with the afterColumnMove event.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Event is currently available, docs: https://docs.handsontable.com/0.31.0/Hooks.html#event:beforeColumnMove
