### ISSUE TITLE
pull request for new branch

### ISSUE THREAD

**Issue by mahinder** [handsontable/handsontable#1326]
Hi i created a gem of handsontable for ruby and rails user and want to send pull request for new branch .How can i do .

Thanks .

**Comment by AMBudnik** [comment]
Issue closed till an authors reply/request.

**Comment by mahinder** [comment]
Hey AMBudnik,

Requested to open this ticket and guide me so I can add my this gem Info from your official page.

Thanks,
Mahinder

**Comment by AMBudnik** [comment]
Hi @mahinder thank you for you initiative
I think that something like this quick [jQuery tutorial](https://docs.handsontable.com/0.23.0/demo-jquery.html) would be the best pick.

**Comment by mahinder** [comment]
Hey, 

I was looking on page but not get any idea about how I can add information about my own Gem .

Thanks,
Mahinder

**Comment by AMBudnik** [comment]
Hi @mahinder 
I'll talk with our developing team and I'm back with updates.

**Comment by jansiegel** [comment]
Hi, @mahinder!

I think it would be best, if you could provide us step-by-step instructions on how to use your gem in any form (gist, pdf, html page, doesn't matter), so we could test and review how it actually works before putting it in our documentation.
If you could also prepare a working demo, that would also be great!

And thanks for investing your time in this gem! :)
