### ISSUE TITLE
Selected rows problem with vertical scroll

### ISSUE THREAD

**Issue by dominikstrzelczyk** [handsontable/handsontable#1327]
When I select some rows I have problem with vertical sroll. It's not working fine. Some rows is hide. Bottom picures show this situations:
![1](https://f.cloud.github.com/assets/3463785/2206645/02c62dfc-9966-11e3-831f-30dfffbc112d.PNG)
![2](https://f.cloud.github.com/assets/3463785/2206641/de419692-9965-11e3-89eb-25ab71496a8e.png)

I don't know how to fix this problem. I don't want use dragdealer vertical scroll. Scroll window is enought for me.

**Comment by AMBudnik** [comment]
Issue closed cause of lack of demo
