### ISSUE TITLE
Hansontable RowHeader/ColumnHeader corner set value

### ISSUE THREAD

**Issue by rbudepu** [handsontable/handsontable#1336]
Hi,

I have grid like this and I need to set some description at topcorner postition(intersection of RowHeader/ColumnHeader) but I couldn't able to do this.

Is there any prop/Method to do this? As of now, I am setting this value using Jquery.

![handsontablegrid](https://f.cloud.github.com/assets/6786217/2261939/cf3a1d24-9e54-11e3-836c-fae1f6279219.png)

**Comment by AMBudnik** [comment]
Thanks @myDisconnect for support. Since the was no additional questions issue can be closed.
