### ISSUE TITLE
Customized ColHeader cannot be sorted

### ISSUE THREAD

**Issue by banmtG** [handsontable/handsontable#1338]
Hi developers of handsontable,

First of all, I would like to say thanks for your hard work and contribution by making handsontable freely available to everyone. I love to use your handsontable for my website. It makes my website easy and very convenient to use than ever.

However, I have encountered an issue: When I customized the headers with html code, column sorting does not work.

Example code is here: http://jsfiddle.net/banmtG/nhzLz/3/

To see the issue, please replace GiveTitleFromDataBase(col) by GiveTitleFromDataBaseWithHTMLtag(col) in colHeaders: function (col) {
        return GiveTitleFromDataBase(col);      
},

Could you please fix this? Thank you very much.

**Comment by varun-dev** [comment]
@AMBudnik,

I think I am seeing this same issue in the latest version. If I add any tag in the custom header, sorting does't work. Here is a demo - http://jsfiddle.net/varun_dev/jcaksrnq/1/
If you click on header C' where I have added a span, sorting doesn't work.

Is there any clean way to get around this?

Thanks

**Comment by AMBudnik** [comment]
Thanks for sharing @varun-dev
You're right - sorting does not work. I'm reopening this issue.

**Comment by varun-dev** [comment]
Just to add to this, a workaround I have been using was to add the class 'columnSorting' on the span and it starts working. 

The click handler probably needs to find the target more intelligently instead of looking for the class 'columnSorting' on the target element.

**Comment by AMBudnik** [comment]
Great, thanks for a tip Varun.
I thought that it may have something to do with classes.
It's definitely a big step forward to fix this bug.

**Comment by swistach** [comment]
Only an event.target with 'columnSorting' className could run the `sortByColumn()`.
Example: http://jsfiddle.net/c0n9cxzh/

TODO: rewrite a private method `bindColumnSortingAfterClick` to a hook callback `afterOnCellMouseDown`

**Comment by AMBudnik** [comment]
Hi @varun-dev can you take a moment to check if the following fix works for you?
@banmtG sorry for a late reply but if you are still working with Handsontable I would really appreciate your opinion as well.

**Comment by banmtG** [comment]
Thanks for all of your supports. I unfortunately stop working with websites for the time being. But the solution http://jsfiddle.net/c0n9cxzh/ provided by **swistach** seems to work.

**Comment by AMBudnik** [comment]
Great! Thanks for your prompt reply @banmtG 
I think that we can close this issue.
@varun-dev feel free to leave a comment if you'd find anything concerning in relation to this fix.
