### ISSUE TITLE
Native scroll window doesn't scroll well with arrow keys

### ISSUE THREAD

**Issue by Silenssi** [handsontable/handsontable#1339]
When moving up and down with arrow keys on handsontable with native scroll window  scroll doesn't keep up.

When going down it jumps 60 rows a time and going up 12 rows.

Here's a fiddle with a example.
http://jsfiddle.net/9EHy2/

**Comment by AMBudnik** [comment]
Please update to [0.14.0](https://github.com/handsontable/handsontable/releases/tag/0.14.0) it should work as you expected. If this issue will still occur, please provide your OS/Browser information.
