### ISSUE TITLE
Formatting and data-type support from the context menu

### ISSUE THREAD

**Issue by aionescu** [handsontable/handsontable#134]
Please add support to be able to add/change the data type from the context menu too for a cell, a column or a row, or a selected group, just like it's possible in Excel.
Of course, the idea is not to support all the data types, but just a few basic would be very very helpful, e.g. date patterns, numeric, decimal.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues we decided to reopen the feature requests as Github Discussions.

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change. This issue is very old and it surely needs some updates.
