### ISSUE TITLE
Maximum length of cell input

### ISSUE THREAD

**Issue by bottas** [handsontable/handsontable#1344]
Hi,

Is there a property to control the maximum length of data allowed in each cell? Something that can be setup at the column option level along with its format, perhaps a size as well?

Thanks
Soujanya

**Comment by JonathanLibes** [comment]
afterOnCellMouseDown: (event, coordinates) => { // limit isin col to max lenght
        let textarea = document.getElementsByClassName('handsontableInput');
        if (coordinates.col == 0 && textarea) // target only 0(nth) - column
          (<any>textarea[0]).setAttribute('maxlength', 12);
      }
