### ISSUE TITLE
keydownListener in the CopyPaste portion of handsontable indiscriminately steals focus

### ISSUE THREAD

**Issue by simonsarris** [handsontable/handsontable#1347]
The CopyPaste portion of Handsontable will steal focus from another HTML Element on the page, even if that HTML element was expecting CTRL+Something input.

That problematic code I'm referring to begins here:

https://github.com/warpech/jquery-handsontable/blob/master/src/3rdparty/copypaste.js#L74

I think Handsontable needs to not do this indiscriminately.

The problem is that if I have a library that uses CTRL+C to copy something (in this case it's with GoJS on a Canvas), when I press down CTRL the Canvas loses focus and it goes to the copyPaste textarea element of Handsontable. Seemingly the only way I can stop this is by modifying the Handsontable library right now.

I see that on line 82 Handsontable checks for some conditions itself and if they are true, declines to steal focus:

https://github.com/warpech/jquery-handsontable/blob/master/src/3rdparty/copypaste.js#L82

Handsontable needs to not do this indiscriminately, and if it cannot be "smart" about it then people using this library need the ability to add arbitrary predicates here, so that it does not conflict with other libraries that uses CTRL + Some-key commands.

**Comment by AMBudnik** [comment]
Please update to [0.14.0](https://github.com/handsontable/handsontable/releases/tag/0.14.0), it should work fine. If it does not - please prepare a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/) with your code.

**Comment by AMBudnik** [comment]
I assume this issue can be closed in lack of author's reply for more than a month.

**Comment by simonsarris** [comment]
Sorry, haven't had time to review. Fair to presume fixed, thanks.
