### ISSUE TITLE
Support for visual hint for the changed cells.

### ISSUE THREAD

**Issue by aionescu** [handsontable/handsontable#135]
Please add support to be able to simply use the grid in "tracking" mode when editing, e.g. when that mode is active, the changed cells (after the Ajax load) are marked with a colored corner, e..g like ExtJS does for it's advanced Grid:
http://dev.sencha.com/deploy/ext-4.1.0-gpl/examples/grid/cell-editing.html

Thank you.

**Comment by AMBudnik** [comment]
Feature listed at https://github.com/handsontable/handsontable/wiki/Feature-requests and by issue: https://github.com/handsontable/handsontable/issues/2689

Please track changes to https://github.com/handsontable/handsontable/issues/2689 for updates
