### ISSUE TITLE
Internet explorer version compatible

### ISSUE THREAD

**Issue by clauiordache** [handsontable/handsontable#1359]
Hello Support,

Which version of IE can be totally used without bugs bugs (as Chrome) for handsontable?Some of the features (like Search demo example) do not work on IE.At my work the IT policy is to use IE as official browser.Is an IE version compatible?

Thank you!!

**Comment by aprhandson** [comment]
I am using 0.10.5 on IE 9 which works fine but when I try to launch the page using IE 11 the table is not displayed. Is handsontable 0.10.5 compatible with IE 11? Where can I find a compatibility matrix that shows handsontable versions and browser support?

**Comment by AMBudnik** [comment]
@aprhandson please stick to #2916
