### ISSUE TITLE
the original value of the cell is lost after entering an invalid value in a dropdown field

### ISSUE THREAD

**Issue by slabbint** [handsontable/handsontable#1366]
I have a column with a dropdown list defined as follows :
```javascript
 {
	data: 2, 
	type: 'dropdown', 
	source: ["a", "b", "c"], 
	strict: true, 
	allowInvalid: false
}
```

Suppose the value is currently set to "b". 
When i click the arrow in the cell, the dropdown list shows. 
When i start typing an invalid value like "zzz" and then press enter, the dropdown cell sees that the value is invalid and it sets the value to the first item of the list. 
I would expect that it keeps the original value "b".
Tom
ps i'm using Firefox and Handsontable 0.10.3

**Comment by AMBudnik** [comment]
Please try this [demo](https://jsfiddle.net/8c04df4y/) editor is blocked until the typed value is valid.
