### ISSUE TITLE
Very slow up/down keyboard movement (scroll demo)

### ISSUE THREAD

**Issue by davidhoria** [handsontable/handsontable#1369]
When you press and hold down key in demo scroll (from cell A1)
around cell A200-A300 the system hangs up for 5-6 seconds.

http://handsontable.com/demo/scroll.html

The problem is hands on table does for every down key a render() but the time it
takes to complete the render is much longer than the keyboard repeation time.
When a new render() is called the old render should be stopped.

**Comment by AMBudnik** [comment]
Hi guys. Please check our newest 0.14.0 release - it should smoothly work with an arrow navigation. If you would have any questions related to this issue, feel free to reply and we'll reopen the issue.

**Comment by davidhoria** [comment]
http://handsontable.com/
Load now 100 000 cells
and press and hold up key.
After a couple of seconds, the page freezes for about 16 seconds, in any browser.

**Comment by AMBudnik** [comment]
Hi @davidhoria please track changes to https://github.com/handsontable/handsontable/issues/2404 it is currently in development.

**Comment by Sheetal1289** [comment]
Hi @AMBudnik  

I am using Handsontable Pro version : 1.15.0.
when you scroll down with keyboard up and down the performance is very slow and handsontable get hang. Currently only 100 or 150 records in my table still i am getting this issue.
can you please help me out.

**Comment by AMBudnik** [comment]
Hi @Sheetal1289 
What are your settings? Are you able to replicate the same delay using this demo http://jsfiddle.net/k367nLwv/?

This is how it looks on my local machine (Windows 10/Chrome 63)

![gif](https://user-images.githubusercontent.com/10757813/35905679-451a4ab4-0be8-11e8-9b5a-3203a4f6551a.gif)

**Comment by Sheetal1289** [comment]
Hi @AMBudnik 

It is working fine with your demo. but at my end sometimes business user get this issue or sometime not.

**Comment by AMBudnik** [comment]
The performance issues may be also related to the device/browser and the internet connection. If we would be able to get the specific environment we should be able to test it.

**Comment by davidhoria** [comment]
In demo works fine because there are little columns populated.
If you populate columns A..AC and 300 lines it slows down on *every*
browser/machine/internet connection.

On Wed, Feb 7, 2018 at 11:27 AM, Aleksandra Budnik <notifications@github.com

**Comment by AMBudnik** [comment]
Hi @davidhoria 

sure, when you load more data the table slows down. I have used a table 150x150 as @Sheetal1289 wrote about having 150 records. Still, Handsontable should have thousands of rows. Only formulas and custom renderers can slow the table down significantly.

**Comment by Sheetal1289** [comment]
Hi AMBudnik 

currently it is working fine. we update the chrome version.

**Comment by AMBudnik** [comment]
Thank you for confirmation @Sheetal1289 
How it's working on your end @davidhoria?

**Comment by davidhoria** [comment]
https://handsontable.com/features

Terrible. It's working fine only on computers with powerful graphics cards
for gaming.
On office computers (built in graphics) lacks speed very much.
When I press and hold key down, from row 1 until row 18 it's fine, then it
hangs, then display row 24, then row 36 then row 72.
It's not smooth at all.

Horia.

**Comment by AMBudnik** [comment]
Can you record it @davidhoria?
It is very hard to help when I am not able to replicate the issue.
If that helps the demo and video I have shared a few posts higher is made using Windows 10/Chrome 63 on an Intel Core i7-4510U CPU Lenovo with 2GHz so it's definitely not a demon, just a couple years old office laptop.
I think that the delay may have other reasons. Do you have any browser add-ons or additional scripts that may influence the loading speed? Does any of our example at handsontable.com work as slow as your local example?

**Comment by davidhoria** [comment]
https://www.cpubenchmark.net/cpu.php?cpu=Intel+Core+i7-4510U+%40+2.00GHz
Your CPU has 4000 benchmark points
https://www.cpubenchmark.net/cpu.php?cpu=Intel+Atom+Z3735E+%40+1.33GHz
Mine only has 1000 benchmark points

I tested directly on your web page example
https://handsontable.com/features

I tetsted on 4 different computers (similar in CPU and graphics)

I currently use in my projects slick grid
Example here:
http://mleibman.github.io/SlickGrid/examples/example-optimizing-dataview.html

This is lightning fast (50x) compare to handsontable.
But it is old (2014) and is not updated anymore.

Horia.

**Comment by AMBudnik** [comment]
Yes, you're right. Last time I've tested their table it was fast, but as far as I remember it was only a viewable table so without any editors and validators for cells (and that's a big performance difference). 

Hm... there is not much I can do with your devices but I guess that 
* switching off the editors and validators 
* making cells higher (`rowHeights `adjustment)
* showing less cells in the viewport (`height`, `width`, `viewportColumnRenderingOffset`, `viewportRowRenderingOffset `settings)

But after all, you are the one to decide if the product meets your goal.

I can just say that around summer we are planning to start something I like to call an eco-rendering. The process that allows only changed (or chosen) cells to rerender. And this (in theory) should really boost the performance. If you're interested you can check our progress on [this topic at our Trello](https://trello.com/c/m9KTygSV/80-rewrite-renderers-to-improve-performance-2152).
