### ISSUE TITLE
Way to skip columns on paste?

### ISSUE THREAD

**Issue by briansol** [handsontable/handsontable#1371]
I have business template in excel that i need to 'import'.  HOT is the easiest way.

Due to the nature of the data (multiple blocks of similar data), there are multiple tables, but spaced where cols are blank.  Ie, in this epic paint drawing, cell B2 is skipped because col C is the same for both rows, but row 2 doesn't have B-data.

Row 2 is actually a 2nd logical group, hence the HR.
![skipb2](https://f.cloud.github.com/assets/5598104/2440703/9a04e9b6-ae0a-11e3-8832-98869e7797f4.png)

So, what I want to do is allow the excel template to remain lined up, and at the same time, have a place holder column on the HOT to accept the B col of data, but not really show it as a blank header/etc that may be confusing.

Can this be done?  the hide methods seem to do something different from what I am asking about.

**Comment by AMBudnik** [comment]
About grouping you can try to use this [demo](http://docs.handsontable.com/demo-grouping-and-ungrouping.html) with your code.

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity or new issues.
