### ISSUE TITLE
"Search of values"  doesn't scroll screen to an expected value

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#1383]
I am using 'search of values' to speed up editing lines of my table but the search can't bring up the values I've just typed. The search seems doesn't work with scroll enabled.

**Comment by AMBudnik** [comment]
I made a [demo](http://jsfiddle.net/9pu5Lrn7/) for your example but I couldn't reproduce the behaviour you have described. I'm using 0.13.1.

If you still experience the same thing, please reply in the same issue and we'll reopen it.
