### ISSUE TITLE
Setting blinking caret position of TextEditor

### ISSUE THREAD

**Issue by brianmingus** [handsontable/handsontable#1384]
I haven't been able to set the blinking caret position of an active cell TextEditor.

jsFiddle example that I can't make work in handsontable using the chrome console.

http://jsfiddle.net/brian_mingus/G4qtr/2/

Just to be clear, it's the blinking caret aspect that I can't get working.

**Comment by AMBudnik** [comment]
If you still face this issues with 0.14.1 please let us now. Till it happens issue will stay closed.
