### ISSUE TITLE
'insert_row' and 'insert_col' missing a refresh?

### ISSUE THREAD

**Issue by kkrusty1** [handsontable/handsontable#1388]
When using alter('insert_row', index) to insert a row, the table is refreshed only when clicking in the table. This does not happen when using 'delete_row', the row gets deleted right away without the need of clicking in the table to refresh it. Here is an example:

http://jsfiddle.net/7YQGA/1/

In the example, select a cell then click on Insert Row to insert a row at the current selected cell. The table is not refresh unless you click again in the table. If you try the same thing with the Delete Row button, the row gets deleted immediately.

The same thing happens with columns

**Comment by AMBudnik** [comment]
Tied your demo with 0.14.1. and it works great. Please update it to 0.14.1
