### ISSUE TITLE
Native scroll problem with fixed rows and columns (IE11)

### ISSUE THREAD

**Issue by escobar5** [handsontable/handsontable#1389]
When using native scroll in IE11, if I scroll the page (not the table) with the scrollwheel, the fixed columns and rows stay in the same position for a moment and then they scroll to the correct position.

I can reproduce this problem with the native scrollbar example in IE11: http://handsontable.com/demo/scroll_native_div.html

**Comment by AMBudnik** [comment]
This issue should not occur any more. Please try [this page](http://docs.handsontable.com/0.19.0/demo-fixed-rows-and-columns.html) as an example.
