### ISSUE TITLE
Old date on datepicker with new row

### ISSUE THREAD

**Issue by dante1138** [handsontable/handsontable#1392]
When I have a date column, the last date I pick is saved on the date picker control. When I load a new cell of date type the date from the preview cell is selected by default, instead of being either blank or today date. 

Is there a way to customize this?

Thanks

**Comment by AMBudnik** [comment]
Please check our [demo](http://handsontable.com/demo/date.html), default value is 1th of January 1900 but you can customize it:

` {
      type: 'date',
      dateFormat: 'MM/DD/YYYY',
      correctFormat: true,
      defaultDate: '01/01/1900'
    },`

more about on [Pikaday](https://github.com/dbushell/Pikaday) which we are currently using.
