### ISSUE TITLE
 HandsOnTable Header is rendering again when scrolling the vertical scroller

### ISSUE THREAD

**Issue by kumar31rajesh** [handsontable/handsontable#1393]
HandsOnTable Header is rendering again when scrolling the vertical scroller ...wants to show bootstrap tooltip text on HandsOnTable header but on scrolling bootstrap tooltip changed to normal tooltip for title ......

**Comment by AMBudnik** [comment]
I couldn't reproduce it with 0.13.1. Can you please update to 0.13.1 and reply if you still experience this issue?

**Comment by Areson** [comment]
Might still be happening? I updated my jsFiddle to use the latest build, and it looks like the column headers are still being redraw periodically after scrolling down enough.

http://jsfiddle.net/Areson/w04we809/12/

**Comment by irishsiberian** [comment]
I faced same issue. In jsfiddle provided by Areson the bug is sometimes reproduced when scrolling with PgUp, PgDn keys
Sometimes table isn't partly rendered.
http://screencast.com/t/aqRVLrn5y
Sometimes header is duplicated
http://screencast.com/t/pUPGnWocd

**Comment by tjpeden** [comment]
We are having similar issues, for us, it seems to be reproduced when the window loses focus and then you try scrolling with the mouse. PgUp and PgDn seem to fix the render issues for us. We also noted that our `cells` callback wasn't being called either. I'll update as I find more information.

**Comment by AMBudnik** [comment]
Hi,

I would need as much details as you can provide. At which operating system or/and browser this bug can be reproducible?

**Comment by tjpeden** [comment]
Happy to provide the info, however, it's worth noting that I'm not able to reproduce this issue on any of your examples nor on the fiddle provided on this issue. So, I'm not sure what to make of that.

I'm on Mac OS X Yosemite using Chrome 46. I just updated to HOT 0.20.1 from 0.16.0, that didn't change anything (although, I am happy that the merge cells issue was fixed! Thanks!)

**Comment by AMBudnik** [comment]
@tjpeden do you face the same behaviour with [`demo provided above`](http://jsfiddle.net/Areson/w04we809/12/)?  I can't reproduce it with the same system/browser as yours.

**Comment by Areson** [comment]
Been a bit on this, but I went back and looked at the fiddle I posted. It's pointed at the master branch for HOT, so I think that's the latest build. I'm stilling seeing the issue pop up in the fiddle. What I'm looking at is the count in the upper right hand corner of how many times "afterGetColHeader" has been called. My guess is that the table redraws that are triggered from HOT recycling rows when things have moved off screen triggers a re-draw of the headers in addition to the table itself. This in turns fire the "afterGetColHeader" event.

**Comment by AMBudnik** [comment]
Hey @plamenkoyovchev 

have you tested v6.2.2 and can you send a demo where the issue can be replicable?

**Comment by mehdirazafolio3** [comment]
Did anyone solve this problem?  I have the same issue..

**Comment by MehdiRaza1998** [comment]
Did anyone solve this problem? facing the same issue..

**Comment by AMBudnik** [comment]
Hi @MehdiRaza1998 could you please send me a demo where I will be able to replicate the issue? Also please let me know wich Handsontable version do you use at the moment.
