### ISSUE TITLE
bug: using a confirm statement in the afterSelection event causes selection issue afterwards

### ISSUE THREAD

**Issue by androidmj** [handsontable/handsontable#1394]
here is the jsFiddle http://jsfiddle.net/9jwa7/1/

To duplicate the issue, click on a single cell.  Then answer the confirmation popup however you like.  Then immediately hover over other cells without clicking your mouse (not the one you previously selected).

I realize this essentially simulates an onClick event, but as far as I can tell there is no onClick event for a single cell.  I've dynamically added onClick events before, but this method is much faster.

**Comment by AMBudnik** [comment]
I reproduced it with `prompt` also in this [demo](https://jsfiddle.net/AMBudnik/zymsofgq/)

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1, demo: https://jsfiddle.net/zymsofgq/1/

**Comment by swistach** [comment]
Hi @androidmj 
You should use `afterSelectionEnd`: https://jsfiddle.net/ty90pLf1/
