### ISSUE TITLE
Table height changes automatically and  hiddens last row 

### ISSUE THREAD

**Issue by fragpaolo** [handsontable/handsontable#1397]
The table height change when clicking on editable cells. In practice on the first time, the page is loaded, the last row of the table is not shown and only after clicking on an editable cell, "automagically" last row appears again. Analyzing the source with Firefox Webconsole it's clear that the height value as defined in the "div class="wtHider" containing the actual table is initially calculated in wrong manner.
The issue has been experienced on firefox and chrome on Ubuntu 13.0.4 but also on Windows 7.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.
