### ISSUE TITLE
IE: Uncaught exception in conjunction with SVG

### ISSUE THREAD

**Issue by queequac** [handsontable/handsontable#1399]
(Inline usage of) SVG is possible with all current browsers, but Internet Explorer does not support the blur-method on SVG elements.

Handsontable calls ```document.activeElement.blur();``` in two situations; those are guarded by checks for existence of document.activeElement only.
Focussing a SVG element and clicking into handsontable afterwards results in an exception due to the missing blur-method.

See fiddle: http://jsfiddle.net/8BRRn/1/

Pull request fixing this issue is on the way.

**Comment by belerophon** [comment]
This still happens to me? On IE 11.
Any news on this bug?

**Comment by AMBudnik** [comment]
Hi @belerophon 
I couldn't reproduce it with latest (0.24.1) version, could you please check it?
