### ISSUE TITLE
Column sorting with Chinese character will emit an Error.

### ISSUE THREAD

**Issue by Rykka** [handsontable/handsontable#1408]
When Column sorting option is on, there will be an error at jquery...full.js (line 6899)

SyntaxError: JSON.parse: unexpected character

mirror[key] = JSON.parse(JSON.stringify(obj[key]));

**Comment by AMBudnik** [comment]
We're not using jQuery since 0.12.6 release. If you would have the same issue with latest version, please let us know.

**Comment by Rykka** [comment]
Sorry, Haven't  check it for a long time.

http://jsfiddle.net/tnr9ugas/2/

seems OK now.

**Comment by AMBudnik** [comment]
OK, thanks for your reply. If you would have any other questions or suggestions, feel free to open a new issue.
