### ISSUE TITLE
Autocomplete cell loses focus when moving between two tables

### ISSUE THREAD

**Issue by cjshmyr** [handsontable/handsontable#1410]
When typing in an autocomplete field and abruptly clicking on a cell in a different table, immediate text input isn't allowed until I click the new cell again

A bit odd to explain, example: http://jsfiddle.net/Q9CcH/

- Type anything into one of the autocomplete cells (such as Chassis: Black). Don't hit enter or leave the cell.
- Then click into the grid below in any cell. Typing text won't do anything, though the cell is marked as being focused.
- Seems to be fine with plain cells.

**Comment by AMBudnik** [comment]
Does not occur in newest version [0.15.0-beta2](https://github.com/handsontable/handsontable/releases)
