### ISSUE TITLE
ie freeze on fixed rows and columns example when click ctrl + a to select all the cells

### ISSUE THREAD

**Issue by quiquegallo** [handsontable/handsontable#1411]
Hi All

I'm implementing handsontable, I use large amounts of information 1000 x 40 columns, I notice that handsotable freeze when I click Ctrl + a to select all the information to copy in excel using i.e. 8 and 9, i try doing the same test in the example for fixed rows and columns in the demo and the same is happening, any idea to fix this?

Thanks.
Regards from México City

**Comment by AMBudnik** [comment]
Can you leave as a feedback how it works of your machine? I tried it on IE11 and works perfect.

**Comment by AMBudnik** [comment]
Closed in lack of demo where issue can be reproducible.
