### ISSUE TITLE
Scrolling very slow when using large tables

### ISSUE THREAD

**Issue by alwaysftd** [handsontable/handsontable#1413]
Hello:

I am using handsontable with a grid that is 188 columns x 64 rows with 5,376 values in the table (many values are blanks).  The scrolling both horizontally and vertically is very slow.  I have tested this in IE10 and Firefox.

Is there anything I can do to make the scrolling faster?  It has a lot of latency, which looks bad to the user.

Thanks!

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
