### ISSUE TITLE
multiline cells and scrolling

### ISSUE THREAD

**Issue by Yogi66** [handsontable/handsontable#1414]
Could it be that for calculating if the vertical scrollbar is shown a fixed row/cell height is used?

I have a table which starts with two rows, minSpareRows is 1 and the height of the container is valid for 11 rows. After adding the 11th row (the systen generates the 12th row) the scrollbar should show up - what it does but only as long as I use single lines in a row.
As soon as I start using multi-lines (e.g. in line 11 I inserted two lines in the first cell) and press enter the scrollbar does not show up even though the 12th line is generated - I know this because when I enter data (even though I do not see the new line) and press enter then the scroll bar shows up and I can see line 12 and 13.

The issue becomes even worth when I use multilines with e.g. 10 lines. So I started in the second row with 10 lines in the first cell and the row just fits into my div. When I now press enter the 3rd row is generated but there is no scrollbar. The scrollbar only shows up when I have added in total 12 lines (blindly)

This leads me to the assumption that for calculating - if the scrollbar should be visible - a standard row / cell height is used but does not take the real height of the rows / cells into account.

Any help is appreciated how to make the scrollbar visible as soon as the rows does not fit into the container anymore

Thanks
Juergen

P.S: BTW, I use scrollV: 'scroll'

**Comment by AMBudnik** [comment]
Please reply if you still face this issue with newest hot version - [0.13.1](https://jsfiddle.net/api/post/library/pure/)

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply and any other unsolved questions for a month.
