### ISSUE TITLE
Field moves when scrolling table

### ISSUE THREAD

**Issue by herchako** [handsontable/handsontable#1417]
Hi! Im using de select editor this way:
{data: "type", editor: 'select',
                        selectOptions: ["EMB", "KD", "MRP", "TR", "TWKG", "WKG"]},
The issue appears when I select de cell and scroll down.
![screenshot from 2014-04-09 15 25 52](https://cloud.githubusercontent.com/assets/1670723/2659424/b5a7c582-c014-11e3-823f-0e3a4c77c1c7.png)
When I scroll down this is what happens, the field "scrolls down" too.
![screenshot from 2014-04-09 15 26 06](https://cloud.githubusercontent.com/assets/1670723/2659429/cb83dbe8-c014-11e3-940b-4d0ae0308777.png)

By the way AWSOME WORK!
Thanks!

**Comment by AMBudnik** [comment]
Please update to 0.14.0, like I did with [your demo](https://jsfiddle.net/TaBJ7/20/) - works as expected.
