### ISSUE TITLE
render is not called until I click somewhere

### ISSUE THREAD

**Issue by huehnerhose** [handsontable/handsontable#1418]
Hi,

I'm using handsontable in a custom backbone view. The View is part of another view... 
The "root"view calls the handsontable table view and essentially crunches some data and provides arrays for handsontable.

Then handsontable is initialized:

``` javascript
this.$el.handsontable({
            data: _this.tableData.rowData,
            colHeaders: _this.tableData.colHeader,
            rowHeaders: _this.tableData.rowHeader,

            columns: new _this.CurrencyColumns(_this.qualificationList.models.length),
            stretchH: 'hybrid',
            cells: function(row, col, prop){
                var cellProperties = {};
                cellProperties.renderer = "PriceRenderer";
                return cellProperties;
            },
            afterChange: _this.afterChange,
            afterRender: function(){
                $("#"+_this.htmlId+".handsontable .visibleHeader").tipsy({
                    gravity: "s",
                    opacity: 1,
                });
                // insitu.fn.wait(false);
                console.log("after");
            }, 
            beforeRender: function(){
                console.log("before");
            }
        });
```

As you can see I added before/afterRender functions to check what's happening. These two (before and after) are only fired after clicking somewhere on the webpage. The View itself is rendered (everything but handsontable).

I wasn't able to put my code inside a jsfiddle, there are to many dependencies and I would have to essentially rewrite that view. So if you have any ideas, without a fiddle, that would be great! 

Thanks a lot

edit: I disabled all the custom functions and renderers without any change of behavior. That sounds like I get something totally wrong... ;)

**Comment by Anilshowreddy** [comment]
Use hot.render();hot.refreshDimensions();. This will solve your issue. Thanks.
