### ISSUE TITLE
 Can't save more than 142 after working on my server

### ISSUE THREAD

**Issue by dodok193** [handsontable/handsontable#1421]
Hi! I having a problem while saving a high number of rows with handsontable!  My test about the number of rows sent was wrong! all the rows are not sent! I even tried with just a test project but I'm having still the same problem!
this is a JSFiddle file for my script! Thanks for helping!

@psmolenski : All the rows were not sent as I said!

http://jsfiddle.net/J6S8C/

**Comment by AMBudnik** [comment]
@dodok193 do you still face the same issue after updating to 0.13.1?

**Comment by dodok193** [comment]
Thanks guys! @oliver-graetz  and @AMBudnik! The probleme is solved! now I can even add 10000 rows! I did everything that @oliver-graetz said and also tried to improve the save.php script!

**Comment by AMBudnik** [comment]
Great! Remember if you will have other questions, feel free to open a new issue - this one now can be closed.

**Comment by oliver-graetz** [comment]
@dodok193 : It would be good for others who find this issue if you exaplained what did the trick. Was it the `max-input-vars` limit or did the new version fix it?

**Comment by dodok193** [comment]
OK! give me some time and I will come out with something solid!

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply.
