### ISSUE TITLE
Fixed columns Right?

### ISSUE THREAD

**Issue by clauiordache** [handsontable/handsontable#1428]
Hello,

Is there an option that can freeze some columns at right, as it is with fixedColumnsLeft?

Thank you!

**Comment by Nullpo** [comment]
+1

**Comment by qetr1ck-op** [comment]
+1

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
