### ISSUE TITLE
ColumnSorting - Uncaught SyntaxError: Unexpected token u

### ISSUE THREAD

**Issue by anton164** [handsontable/handsontable#1429]
After updating to HoT 0.10.3, we have had to turn off columnSorting as having it enabled (columnSorting: true) throws the same error at any interaction with the grid, although the sorting functionality works just fine. Here is a call stack example from the console:

```
Uncaught SyntaxError: Unexpected token u jquery.handsontable.js:6821
_generate jquery.handsontable.js:6821
_generate jquery.handsontable.js:6798
_generate jquery.handsontable.js:6798
_generate jquery.handsontable.js:6798
_generate jquery.handsontable.js:6798
_generate jquery.handsontable.js:6798
_generate jquery.handsontable.js:6798
_generate jquery.handsontable.js:6798
_generate jquery.handsontable.js:6798
_generate jquery.handsontable.js:6798
_generate jquery.handsontable.js:6798
_generate jquery.handsontable.js:6798
generate jquery.handsontable.js:6757
dirtyCheck jquery.handsontable.js:6676
(anonymous function)
```

The _generate chain varies in length, but can sometimes be very long and the error itself occurs at the following JSON.parse call in handsontable.js:6821:
`mirror[key] = JSON.parse(JSON.stringify(obj[key]));`  

In jsFiddles it isn't happening, and it is difficult to pinpoint the issue within our application. Do you have any tips on where I should be looking?

Thanks,
-Anton

**Comment by TheLudd** [comment]
> mirror[key] = JSON.parse(JSON.stringify(obj[key]));

This error can occur if the `obj[key] === undefined`. Is there not a better more robust way of cloning objectes?

**Comment by seanthebean** [comment]
I agree with @TheLudd that there ought to be a more robust way to clone the object.

I get the following error
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
when the value at `obj[key]` is a function. According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description:
> If undefined, a function, or a symbol is encountered during conversion it is either omitted (when it is found in an object) or censored to null (when it is found in an array).

I played around in my JS console and discovered that
```javascript
JSON.stringify(function() {})
```
returns `undefined`, and
```javascript
JSON.parse(undefined)
```
throws the same error as above.

I would consider this a bug, as the apparent implication is that Handsontable can't handle using objects with methods as the source data.

However, one very interesting caveat from my experience is that the error occurs frequently in FF, but never occurs in Chrome. In fact, line
```javascript
mirror[key] = JSON.parse(JSON.stringify(obj[key]));
```
is never called when running my application in Chrome. So my question is why would this be browser-dependent?

**Comment by AMBudnik** [comment]
Hi @anton164 
can you share a demo where this issue is replicable?

**Comment by AMBudnik** [comment]
Issue will stay closed till an authors reply.

**Comment by seanthebean** [comment]
Run this in Firefox: http://jsfiddle.net/m0wqomL8/1/ (apparently in Chrome the offending line is never reached. interesting that the code executes differently depending on the browser..)

**Comment by AMBudnik** [comment]
Thanks for sharing demo @seanthebean

**Comment by AMBudnik** [comment]
still in 0.26.0, demo: http://jsfiddle.net/m0wqomL8/1/ (FF 47)

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/2609 ?

**Comment by AMBudnik** [comment]
This issue no longer occur in 0.29.2, Can you check it @anton164 @seanthebean 
Here's an updated demo: http://jsfiddle.net/5djqcf06/

**Comment by AMBudnik** [comment]
Thanks for a quick update @seanthebean 
I am closing this issue.
