### ISSUE TITLE
How to sort complete table irrespective of freezed column

### ISSUE THREAD

**Issue by chandragirisatish** [handsontable/handsontable#1430]
Hello,

   I am facing one problem here. I freezed first row(defaultly it is header row). when i am going to sort the table, it is sorting complete table along with freezed row also. how to stop sorting of freezed row(header row).

here first image(capture1) shows fixed header row. when i sort by clicking on columns, freezed row also sorting(image2 showing this)

I don't want this. 

kindly help me. i would be thankful.

Thanks in Advance.
Satish Chandragiri

![capture1](https://cloud.githubusercontent.com/assets/7312005/2717443/0d41fe9a-c540-11e3-951e-62f44eb82d65.JPG)
![capture2](https://cloud.githubusercontent.com/assets/7312005/2717444/1070ad3c-c540-11e3-9ab8-ff04e1c27b00.JPG)

**Comment by AMBudnik** [comment]
For further information about this subject please track changes to https://github.com/handsontable/handsontable/issues/2197 issue.
