### ISSUE TITLE
Paste lose last column data on IE8

### ISSUE THREAD

**Issue by dbologna** [handsontable/handsontable#1431]
If I paste 3 rows on a 5 x n table, values are not pasted in the last column except for the third row.
Example. Pasting lines 3-5, cell E3 and E4 are empty. Cell E5 contains the correct value.
I found this behaviour affects IE8, chrome and firefox are immune.

Fixed this trimming the pasted values in the method grid.populateFromArray(). The values of the last columns contains a trailing \n which prevents IE from showing the values.

Worked for me but I don't know if ti is the correct fix for other use of hot. Using hot .10.5

**Comment by AMBudnik** [comment]
This issue is related to version of IE that we do not support since 0.12.0. Please let us know do you have similar issue with newer versions. If so, please prepare a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/) also.
