### ISSUE TITLE
date format, read only cells, and datepicker

### ISSUE THREAD

**Issue by cfeduke** [handsontable/handsontable#1432]
When a `type: "date"` cell or column is also set to `readOnly: true` no jQuery UI datepicker button should be rendered in the cell.

**Comment by AMBudnik** [comment]
From [0.12.6](https://github.com/handsontable/handsontable/releases/tag/0.12.6) we don't use Datepicker and with new solution (Pikaday + moment.js) it works as you described, like in [this demo](http://jsfiddle.net/omfo4y7w/)

**Comment by XEonAX** [comment]
This is still reproducible? Can see the drop down button in readonly date cell in below example

> From [0.12.6](https://github.com/handsontable/handsontable/releases/tag/0.12.6) we don't use Datepicker and with new solution (Pikaday + moment.js) it works as you described, like in [this demo](http://jsfiddle.net/omfo4y7w/)

**Comment by AMBudnik** [comment]
Hi, @XEonAX, yes, the arrow for the picker is visible for dates, but so for the `dropdown,` `autocomplete`, and other similar cell types. We'd rather keep the consistency.

You can test it at https://stackblitz.com/edit/sfkszv-jef2gv?file=index.js (Handsontable v14.4.0)

Outcome

![Zrzut ekranu 2024-07-22 o 08 54 10](https://github.com/user-attachments/assets/d4278eaf-12a0-49da-9a4a-6870c0824b1b)
