### ISSUE TITLE
[Feature Request] Native Scroll Offset

### ISSUE THREAD

**Issue by tikitikifoofoo** [handsontable/handsontable#1434]
The native scroll feature could probably use an offsetTop option so you can adjust where on the page the top rows fix themselves, which allows you to compensate for elements already fixed at the top of the page. 

An offsetLeft option also probably makes sense to compensate for fixed elements on the left side of the page.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by duccoder** [comment]
Looking for this feature

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
