### ISSUE TITLE
Table scrolls to right in IE10 Browser

### ISSUE THREAD

**Issue by mothupally** [handsontable/handsontable#1435]
As you keep clicking in different cells of first column, the table scrolls to the right. The behavior is observed in IE10 and below browsers. Is there something that I am missing?

Please find below is the jsfiddle sample

http://jsfiddle.net/P8VgD/3/

**Comment by AMBudnik** [comment]
Please update to 0.14.1 and check if it still occur - if so, provide your OS information.

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply.
