### ISSUE TITLE
How to perform aggregate functions(average, sum, count) for selected cells

### ISSUE THREAD

**Issue by chandragirisatish** [handsontable/handsontable#1436]
Hello Everone,
I am new to handsontable-jquery. My requirement is complete web excel with limited features. Is it possible to perform aggregate operations like Sum, Average Count for selected cells like excel. If possible, kindly let me know how. 

  send me any references for this. i would be thankful.

Thanks in Advance
Satish Chandragiri.

**Comment by AMBudnik** [comment]
Please changes to this issue https://github.com/handsontable/handsontable/issues/22
