### ISSUE TITLE
Cell dropdown height and scrollbar

### ISSUE THREAD

**Issue by piotrromanowski** [handsontable/handsontable#1437]
I modified the library accordingly to introduce a cell dropdown height and scrollbar. I could not find this functionality anywhere else. Maybe introduce this somewhere in a newer version?

I replaced

    this.hiderStyle.height = height + 'px';

with

    if($(this.holder).parent().hasClass('autocompleteEditor')){
        this.hiderStyle.height = height + 'px'
        this.hiderStyle.maxHeight = 200 + 'px';     
		if(height >= 200 ){		// Make scroll-able if needed
			this.hiderStyle.overflow = 'scroll';    
		}
    }else{
        this.hiderStyle.height = height + 'px'   
    }

**Comment by amit147** [comment]
It worked !! Thanks you.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. Please free to continue the conversation there. Thank you.
