### ISSUE TITLE
TypeError: editor.select.find is not a function

### ISSUE THREAD

**Issue by mtdallaire** [handsontable/handsontable#1438]
Hi,

I get this error no matter the browser I take between FireFox Latest version, Chrome Latest version and ie8 over Windwos XP.

to reproduce:
1. go there: http://handsontable.com/demo/selectEditor.html
2. in the first grid, select the cell "Toyota" in the B column
3. Press F2 to edit
4. Press the "Down" arrow
5. TypeError: editor.select.find is not a function

I explored the objet through Visual Studio Watch and FIND doesn't exists as a method.

thank you very much

**Comment by AMBudnik** [comment]
Thank you for that report.

**Comment by AMBudnik** [comment]
issue doesn't occur anymore. Please check v0.24.1: https://docs.handsontable.com/0.24.1/demo-select.html
