### ISSUE TITLE
Hiding columns causes cells to be missing from newer rows

### ISSUE THREAD

**Issue by chandrewz** [handsontable/handsontable#1439]
Can be seen on: http://handsontable.com/demo/datasources.html#array-hidden

Add '2010' to the new row (first cell).
Dump to console and the row (array) is of length 4.
Fill out the row completely.
Dump to console and the row contains 5 elements now (including the hidden field).

I think this is related to "touching and filling out" the last cell of the row. Once done, the hidden cell appears. This particularly comes out when copy and pasting data, and all the rows I paste are missing the cell. A valid bug?

**Comment by AMBudnik** [comment]
This issue should not occur anymore. Please update your code and if you would still face this issue, kindly reply.
