### ISSUE TITLE
Feature Request: Select entire row and column

### ISSUE THREAD

**Issue by chandrewz** [handsontable/handsontable#1440]
Would be cool to select the entire row/column by clicking the rowHeaders or colHeaders!

**Comment by YourDeveloperFriend** [comment]
Is there an option that disables this feature?

**Comment by YourDeveloperFriend** [comment]
Nevermind, I was able to disable column select by adding the following 'beforeOnCellMouseDown' hook:

```Javascript
beforeOnCellMouseDown: function disableColumnSelect(event, coords) {
  if(coords.row < 0) event.stopImmediatePropagation();
}
```

**Comment by diegopamio** [comment]
I had the opposite problem, I wanted to select only by whole column/row. I ended up with this solution:

    beforeOnCellMouseDown: function disableColumnSelect(event, coords) {
      if(coords.row >= 0 && coords.col >= 0) event.stopImmediatePropagation();
    }

Thanks for the hint!
