### ISSUE TITLE
Leaking event handlers?

### ISSUE THREAD

**Issue by albol** [handsontable/handsontable#1442]
Hi,

I attach a click handler to the TH column header in handsontable so I can pop a dialog to the user when they click the column header. But when the grid is re-drawn the TH's are dropped and re-created, so I have to re-attach my handlers. This works, but I'm wondering if handsontable's removal of the TH's drops the event handlers as well?

Thanks.

**Comment by AMBudnik** [comment]
If you still are looking for an answer, please provide your demo code.

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply.
