### ISSUE TITLE
Change the text size of a dropdown list and fixed cols text

### ISSUE THREAD

**Issue by carlosamaya** [handsontable/handsontable#1443]
Hello everyone, i have the issue when I upgraded to the lastest version of hansontable, the upgraded version increased the size of the fixed texts and dropdown list texts, so it´s a problem cause it lost the format, i really need to fix that, td.style.fontSize just work on the result of the selection

**Comment by AMBudnik** [comment]
It should not act like this. Did you changed styles in you HOT? Please prepare a [demo](https://jsfiddle.net/api/post/library/pure/) of your code.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
