### ISSUE TITLE
Numeric cell editor shows previous value on re-open (open via [Enter] key)

### ISSUE THREAD

**Issue by mariotacke** [handsontable/handsontable#1445]
It appears as if the numeric cell editor incorrectly displays a previous value when opening the editor via the [Enter] key. Double clicking the cell opens the editor with the correct value.

Please see fiddle for visual:
http://jsfiddle.net/SFykC/1/

System Specs:
Windows 7 Professional
Chrome 34.0.1847.116

**Comment by AMBudnik** [comment]
I get ```value: '1'``` as expected. Working on mac with Chrome 41.0.2272.89 (64-bit) with 0.13.1 HOT. If you still experience this issue, please reply.
