### ISSUE TITLE
Support for hh:mm time format

### ISSUE THREAD

**Issue by twinpiloot** [handsontable/handsontable#1446]
Handsontable supports time format hh:mm:ss. I had a wish for the time format hhmm. This format allows users to type for example 820 which gets expanded to 08:20 by handsontable. Users do not have to type the colon.

Because I'm not familiar with pull requests (I'm using Visual Studio), I'm sharing my changes here.

    function formatTime (n, format) {
        if (format == '00:00') {
            // Prepend with 0 and slice will pad the numbers with zeroes.
            return ('0' + Math.floor(n._n/100)).slice(-2) + ':' + ('0' + n._n % 100).slice(-2);
        } else {
            var hours = Math.floor(n._n/60/60),
                minutes = Math.floor((n._n - (hours * 60 * 60))/60),
                seconds = Math.round(n._n - (hours * 60 * 60) - (minutes * 60));
            return hours + ':' + ((minutes < 10) ? '0' + minutes : minutes) + ':' + ((seconds < 10) ? '0' + seconds : seconds);
        }
    }

    function unformatTime (string) {
        var timeArray = string.split(':'),
            seconds = 0;
        // turn hours and minutes into seconds and add them all up
        if (timeArray.length === 3) {
            // hours
            seconds = seconds + (Number(timeArray[0]) * 60 * 60);
            // minutes
            seconds = seconds + (Number(timeArray[1]) * 60);
            // seconds
            seconds = seconds + Number(timeArray[2]);
        } else if (timeArray.length === 2) {
            //  Time format is HHmm.
            seconds = Number(timeArray[0]) * 100 + Number(timeArray[1]);
        }
        return Number(seconds);
    }

**Comment by AMBudnik** [comment]
Thank you for that suggestion.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Feature added: https://docs.handsontable.com/0.24.0/demo-time.html in 0.24.0
