### ISSUE TITLE
Undo/redo broken when used with columnSorting enabled

### ISSUE THREAD

**Issue by mariotacke** [handsontable/handsontable#1447]
Please consider this JS fiddle: http://jsfiddle.net/X82yP/

Handsontable throws an error "undefined is not a function" and un-dos an incorrect row after deleting it when columnSorting is enabled. (Steps included in fiddle)

This may be connected to this bug/fix: https://github.com/warpech/jquery-handsontable/issues/1262

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/1503 issue.
