### ISSUE TITLE
AutoComplete with IME Input

### ISSUE THREAD

**Issue by awsp** [handsontable/handsontable#1448]
The autocomplete didn't work when using IME to type especially when typing with the combination more than or equal to 2 characters. It seems like only vowels get converted, but other characters are not. 

For instance, 
- To type the Japanese character `ひ`, the corresponded keys are `h` and `i` => `ひ` but in handsontable's autocomplete, the keys became `h` and `い` => `hい`. The character `い` was actually key `i` only. As a result, the filtered results are not correctly. 
- Character with one key seems okay. For instance, `a` => `あ` is fine.

You could repeat the issue at the very first cell with a red border under `Char`
http://jsfiddle.net/rrLg3/3/

**Comment by AMBudnik** [comment]
Please track changes in https://github.com/handsontable/handsontable/issues/839 issue for more information about this subject.
