### ISSUE TITLE
more natural scrollbar handle size

### ISSUE THREAD

**Issue by startrektng** [handsontable/handsontable#1449]
For a natural handle size, especially for the vertical case (similar to native scollbars, but no extra hassle), you could change ratio and hadleSize in the "WalkontableScrollbar.prototype.refresh" function like this:

ratio = (visibleCount*100) / this.total;
handleSize = Math.round((ratio*sliderSize) /100 );

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
