### ISSUE TITLE
Render so slow onChange

### ISSUE THREAD

**Issue by cuong88pham** [handsontable/handsontable#1451]
![screenshot 2014-04-28 13 25 11](https://cloud.githubusercontent.com/assets/348893/2813967/023c34ae-ce9e-11e3-8250-c5a61d0ad244.png)

I render a list with more than 100 items and when I choose a new Item, it seems to be renderred so slow (more than 5s) to display the Item and Sub-total in the table.

Seem the onChange callback repeat rendering the Handsontable for all the above rows.

Any advise on this performance. Really appreciate your help.

onChange callback : 

        // set data at column Unit Price
        $container.handsontable('setDataAtCell', data_row, 3, product_unit_price);

        // set data at column Sale Discount
        $container.handsontable('setDataAtCell', data_row, 4, product_sale_discount);

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply.
