### ISSUE TITLE
adding `padding-top` to div containing table breaks table display when using bootstrap (0.10.5)

### ISSUE THREAD

**Issue by jcollum-hcg** [handsontable/handsontable#1454]
This has been what I've been trying to figure out for the past few hours now. Had a table that was displaying fine but for some reason the context menu was squashed, or even worse, the whole table: http://imgur.com/UcQT4PO

I've recreated the issue here: 

http://plnkr.co/edit/LBDvkl?p=preview

If you'd like to turn the bug on/off, comment out the `bug.css` file.

**Comment by AMBudnik** [comment]
Seems your demo does not display any data. Please update to 0.14.1 and check if you still face the same issue.

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply.
