### ISSUE TITLE
Touch support for tablets

### ISSUE THREAD

**Issue by masull** [handsontable/handsontable#1455]
Hi,

I was wondering if touch support such as single cell click to edit can be added to a future release? There are branches that support similar functionality but they are not maintained to the current HandsonTable release. 

Mark

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
