### ISSUE TITLE
Handsontable in Handsontable

### ISSUE THREAD

**Issue by jhondavila** [handsontable/handsontable#1456]
Hi , I have problem with handsontable in handsontable.

I would like to retrieve the instance of child handsontable.

if you want I can attach my code...

**Comment by AMBudnik** [comment]
We are currently working on hot in hot feature, please stay updated for changes.

**Comment by 57even** [comment]
I'm really looking forward to this!

**Comment by AMBudnik** [comment]
If you still face problems with your code, please let us take a look. JSFiddle will be appreciated.

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply.
