### ISSUE TITLE
Wrap text in cell should be optional

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1460]
Currently cell text is word wrapped. It is because of the CSS rule `white-space: pre-line;`.

We should add a new option `wordWrap` (default true) that would allow to disable this function (resulting in `white-space: nowrap`)

Matt describes:

> Looking for cells to have a bool attribute which determines whether cell content is to be wrapped. If wrapped   = true then the cell content is rendered in such a way that the text is wrapped in that cell using the full width of that column (and not changing the width as a result of information needing to be wrapped) and there is no content outside of the borders of that cell.
> 
> Currently text is automatically wrapped / broken on the space when there is any overlap with adjacent cells and there is a space within the content - this is not desirable - wrapping should solely be determined by the cell’s wrapped state and the width of the column.
> 
> When wapped = false, iff the rendering of a cell's content would overlap a non-empty cell, the content rendering only goes as far as the non-empty cell.

**Comment by dcsan** [comment]
can this be applied to a whole column?

**Comment by dcsan** [comment]
fwiw I tried leaving out the row parameter, but doesn't seem to result in any column being affected.

```js
        cell: [
          {col: 1, readOnly: true, wordWrap: false}
        ],
```
