### ISSUE TITLE
Grouping and ungrouping of rows or columns

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1463]
Grouping and ungrouping of rows or columns - in the same way as availabe in Excel: 
http://taxodiary.com/wp-content/uploads/2012/04/excel2.jpg
http://img.technospot.net/grouping-large-columns-row.jpg
https://www.youtube.com/watch?v=rz0ObEXa-rk

**Comment by Rex90** [comment]
Does this still work? I cant get it to work with nested headers latest PRO version

**Comment by AMBudnik** [comment]
Hi @Rex90 

We have abandoned the grouping feature. Now we use only nested headers and rows. If you want to collapse columns you can use [collapsing](https://docs.handsontable.com/pro/1.14.3/demo-collapsing-columns.html).
And here's an example on how to collapse columns programmatically http://jsfiddle.net/handsoncode/cLvyr997/
