### ISSUE TITLE
Custom number formats

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1466]
Matt says:

> The intention here is to be able to emulate custom number formats in Excel (most of which appears possible with numeral.js and moment.js). I suspect the solution here would be to extend numeral.js to incorporate the missing formatting elements. Just so there are no misunderstandings, this is not required when communicating with our back-end as we will supply the grid with a number of different datums for each cell, including the string required for rendering. It will however be required for front-end interactivity such as offline evaluation and user entered cells (where the front-end will need to convert new and potentially changed values intro strings, presumably using numeral.js). 

I propose that we just add a context menu on http://handsontable.com/demo/numeric.html that allows to change number formatting to some predefined formats. That would also solve issue #134

Matt can you make a list of desired formats? Or do you want us to recreate as much of them as possible? 

http://lis.dickinson.edu/technology/training/tutorials/2010/excel/format_cells.pdf

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
