### ISSUE TITLE
AutocompleteEditor should ignore diacritics (as an option)

### ISSUE THREAD

**Issue by tabacitu** [handsontable/handsontable#1474]
In languages that use accents or diacritics, AutocompleteEditor won't match if the source items use accents and users type without (as they usually do).

Case in point:
- à la carte
- a la carte

Small changes in:
- AutocompleteEditor.prototype.queryChoices
- AutocompleteEditor.prototype.open
using https://github.com/yvg/js-replace-diacritics would solve that.

I'm thinking that this should be available in the core, as an option, like "filteringCaseSensitive", say "filteringIgnoreDiacritics" (default: false).

I've already done this for a project I maintain, should I rewrite it in a more general way and make a pull request?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
