### ISSUE TITLE
How can I reset column sorting

### ISSUE THREAD

**Issue by xmcdogx2** [handsontable/handsontable#1476]
Hi,

How can I reset column sorting?

Thanks!

**Comment by AMBudnik** [comment]
This feature is not available now, but i'll add it to our feature candidates.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
This action can be achieved by calling `clearSort` method from the `columnSorting` plugin 
Documentation: https://handsontable.com/docs/8.0.0/ColumnSorting.html#clearSort
