### ISSUE TITLE
updateSettings method removes cells validation state

### ISSUE THREAD

**Issue by nicoarya** [handsontable/handsontable#1477]
Hello,

I use updateSettings to update colHeaders after init.

var ht = $(".jq-ht-table").handsontable('getInstance');
var newHeaderSettings = defaultColHeaders.slice();
newHeaderSettings[8] = colVolumeTitle.format(volumeUnit);
newHeaderSettings[10] = colTareWeightTitle.format(weightUnit);
ht.updateSettings({ colHeaders: newHeaderSettings });

It works well, but as updateSettings triggers a full render of the view, invalidated cells lose the css class that identify them as "invalid". I can invoke a full table validation after that, but as some cells need ajax call to be validated it becomes a performance issue.

I also tried to directly update colHeaders via jQuery by selecting elements by class (colHeader) and updating innerHTML but as some columns are not visible (and not accessible in the dom due to scrollbar) and it doesn't work in all cases.

According to me updateSettings should keep validation state. Is it possible to specify such an option ?

Thanks a lot :)

**Comment by AMBudnik** [comment]
Could you please provide a JSFiddle demo of your code?

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
