### ISSUE TITLE
alter("remove_row", row) shifts cells instead of delete

### ISSUE THREAD

**Issue by ToKuVi** [handsontable/handsontable#1478]
In the fiddle http://jsfiddle.net/ToKu/3H5p5/ when you create the following new rows
a  1
b  2
c  3
and you do not leave the last field where you just typed the 3
when you now press the 'x' beside the row with the b in it you will get
a  1
c
    3
instead of
a  1
c  3

What do I do wrong?

**Comment by AMBudnik** [comment]
I couldn't reproduce it - can you please provide more information about this issue it it still up-to-date.

**Comment by ToKuVi** [comment]
Sorry, we do no longer use handsontable

**Comment by AMBudnik** [comment]
OK, thank you for your answer. I assume we can close ths issue.
