### ISSUE TITLE
Renderer only for afterLoad

### ISSUE THREAD

**Issue by jf506** [handsontable/handsontable#1481]
Hello, im new at hot... Im trying to have a specific renderer for the cells that have information on my db (these shouldnt be editable) while the other ones(empty), should be editable...I would like to know how can i do this...is there a way i could mix the afterchange with the cells parameter? anyway here is the little code i have : 

<div class="handsontable" id="example">
<p>
  <button name="dump" data-dump="#example">Dump to console</button>
  <button name="save" data-save="#example">Save</button>
</p>
<script type="text/javascript">
var data = <?php echo json_encode(array_values($array ));?>;
var headers = <?php echo json_encode($headers);?>;
var $container = $('#example');
var $console = $("#example1console");
var $parent = $container.parent();

 
$container.handsontable
({
	data: data,
	minSpareRows: 5,
	colHeaders: true,
	colHeaders: headers,
	contextMenu: true,
	cells: function (row, col, prop)
	{
		var cellProperties = {};
		if (data[row][col]!=""&&data[row][col]!=null) 
		{
			cellProperties.readOnly = true; //make cell read-only if the cell is not empty
		}
		return cellProperties;
	},
 });

**Comment by AMBudnik** [comment]
Unfortunately the link to your demo is missing, can you provide a new one? I think you could use `updateSetting` method
