### ISSUE TITLE
Question: Updating multiple values at onces, causes browser to die/freeze

### ISSUE THREAD

**Issue by balugaa** [handsontable/handsontable#1482]
Hi am seeing this problem, but not sure what the best way to solve it essentially 
I have 2 tables on my page .. 

1. the main data table 
2. The changes you have made table

on the main table i listen to the after change event, and if there is a change detected, i add the information to the change table, which is essentially  just row num,id,  old val , new val 

The main data table can contain a large number of rows,

The issue i have is that there is a button on the page that is meant select all the checkboxes in the data table, i.e. a flag, 

However when this is clikced 
1. I iterate through all the rows and set the received field to true, 
2. This fires an after change event 
3. Check the change in the after change event (ie. old != new)
4. if its different write to the change table 
5. Render the change table 

the change table rendering is within afterchange of the main data table, so it just takes ages when the user clicks the button 

Any ideas or shortcuts to update the values on mutilple rows/ or indeed almost like a setDataAtCol type thing .. or indeed what is the best way to get this to work efficiently

**Comment by AMBudnik** [comment]
If you still face this issue - please prepare a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/)

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
