### ISSUE TITLE
Paste from html table

### ISSUE THREAD

**Issue by ilanza** [handsontable/handsontable#1483]
Hi,
When I copy\paste a table from html page It paste as a one column list, but when I paste the same table into excel or google spreadsheet it paste as a table.

Is it a bug or can I define the paste differently?

Thanks

**Comment by budnix** [comment]
Hi @ilanza, 

Could you provide some more scenarios about this new feature/bug (or page where you copy table which broke handsontable). I investigated this feature and it seems that copying table from html page and pasting it to the handsontable works corectly. Prepared demo where you can try copy/paste example table http://plnkr.co/edit/ITzyNQ?p=preview.

**Comment by krzysztofspilka** [comment]
Not current issue anymore, i'm closing it. @ilanza in case you're still facing problems with Handsontable please open a new issue. Thanks for reporting this.
