### ISSUE TITLE
Question how to update cell 

### ISSUE THREAD

**Issue by thesis4neu** [handsontable/handsontable#1486]
How can I update the cell settings of specific row if a value of a other cell is change?

see fiddle

http://jsfiddle.net/hU6Kz/2727/

**Comment by AMBudnik** [comment]
Hi, did you tried to use this two methods?

`updateSettings (options: Object)`
`Use it if you need to change configuration after initialization`

`getSettings ()`
`Returns an object containing the current grid settings`

**Comment by AMBudnik** [comment]
I assume this issue can be closed. If you would have any other questions, feel free to leave a comment.
