### ISSUE TITLE
Bug: When inserting row using contextmenu on last row, row is added, but can't be used

### ISSUE THREAD

**Issue by frodik** [handsontable/handsontable#1488]
Can be seen here: http://handsontable.com/demo/contextmenu.html
When you right-click last row and click "Insert row below", the new row is inserted. However it is not usable, when you try to click this new row, nothing happens and in console can be seen this error: Uncaught Error: row 5 does not exist - it gets repeated after each click on this row.

EDIT: I also tried using alter method like this: $("#example1").handsontable('getInstance').alter('insert_row'); and it produces the same error. So it's not context menu specific, rather problem with alter() method itself.

**Comment by AMBudnik** [comment]
This issue should work fine. It works like that in major browsers on mac (as I tried), but if you still have this issue please reply with more info about your browser and we'll reopen this issue.
