### ISSUE TITLE
Sorting doesn't work with date - FF/Safari

### ISSUE THREAD

**Issue by frodik** [handsontable/handsontable#1492]
I have dateFormat: 'dd.mm.yy', it's correctly displayed in cell, but sorting this column does not work. Rows are not sorted using custom format.

**Comment by AMBudnik** [comment]
I provided a [JSFiddle demo](http://jsfiddle.net/q27uptqv/) for that issue, which works completly fine in Chrome 41.0.2272.89 (64-bit), but doesn't work correctly in Firefox 36.0.1 and in Safari 8.0.3 (10600.3.18).

**Comment by AMBudnik** [comment]
Issue confirmed with 0.24.0

**Comment by AMBudnik** [comment]
as @dcsan wrote in https://github.com/handsontable/handsontable/issues/3079

> Date `correctFormat: true` formatting doesn't seem to make any difference:

```
  {
            data: 'createdAt',
            type: 'date',
            dateFormat: 'MM/DD/YYYY',
            correctFormat: true,
            defaultDate: '01/01/1900'
          }
```

![image](https://cloud.githubusercontent.com/assets/514002/11902395/5090511c-a566-11e5-8e78-2aed7ea717d4.png)

maybe related #3055

**Comment by AMBudnik** [comment]
reproducible with 0.26.0, demo: http://jsfiddle.net/u4q61fz0/

**Comment by swistach** [comment]
This works properly since version 0.29.0
Related with: #3588
