### ISSUE TITLE
found a issue on _generate,when newVal is null and oldValue is a object

### ISSUE THREAD

**Issue by zhangmq** [handsontable/handsontable#1496]
in this situation,"obj is not a object" raised.
I change the statment
_generate(oldVal, newVal, patches, path + "/" + escapePathComponent(key)); 
to 
_generate(oldVal, newVal || {}, patches, path + "/" + escapePathComponent(key)); 
seems everything all right,does this change create new issue?

**Comment by morungos** [comment]
I've found this is still here, but I think there's a better fix. For example, I'm using `true` as a value, and this wouldn't work, as the primitive would still be passed to the recursive call and keys wrongly accessed. I've got a better workaround, and I'll submit a PR shortly. This happens when values are changing from primitives to objects, and weirdly only seems to manifest for me on Safari, not Chrome (!). Anyway, PR in hand.

**Comment by morungos** [comment]
Well, as a third party module this isn't really tested, so I'm not sure on the protocol for this, but the bug has definitely been fixed upstream, in this commit: https://github.com/Starcounter-Jack/JSON-Patch/commit/1ea71b9a1e5fff46c9f93672a836cedac1beab16. 

However, the updates are breaking jshint a lot, and the standard code doesn't actually run in the test environment. The running is easy to fix with a small handling for `this` being undefined (!) but I don't really know how to handle jshint being this far out for one file. 

Anyway, I just pushed a feature branch for this issue.

**Comment by morungos** [comment]
It's in a pull request, because even though I did the git flow thing, I couldn't push. Let me know if there's a better way. https://github.com/handsontable/handsontable/pull/2329

**Comment by AMBudnik** [comment]
Hi @zhangmq can you confirm that this bug was fixed and it's not present in 0.23.0?

**Comment by AMBudnik** [comment]
I assume that you could solve or abandon presented structure. I'm closing this issue but feel free to leave a comment if there's anything we should know about that is related to present issues.

**Comment by zhangmq** [comment]
thanks for reply, I don't remember details about this issue, it's happy to know this fixed.
