### ISSUE TITLE
Grid in jquery modal window doesn't alow paste

### ISSUE THREAD

**Issue by orshee** [handsontable/handsontable#1497]
Seems like there is a bug when trying to paste multiple rows from excel when grid is loaded in jquery modal window

**Comment by AMBudnik** [comment]
@lgbeno here's the updated demo http://jsfiddle.net/j6DJC/2/
Seems to work fine - could you check it please?

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity and bug confirmation.
