### ISSUE TITLE
handling Calculations on onChange event and setDataAtCell

### ISSUE THREAD

**Issue by josephbaggett** [handsontable/handsontable#150]
When there is a change done on the client, I wanted to do calculations and have calculated fields.  The problem is that when I call the setDataAtCell method, it recursively calls the onChange event, so it can get stuck in an infinite loop if I call the Calculate method that does a call via setDataAtCell.  Is there a clean way to do calculations without having some form outside tracking mechanism to do this?  Here is an example of a method that is called right after a loadData function is called:

function CalculateFirstRowOfTheFirstColumn() {

```
var firstRowValue = $("#balanceSheetExcelGrid").handsontable('getDataAtCell', 0, 1);
var secondRowValue = $("#balanceSheetExcelGrid").handsontable('getDataAtCell', 1, 1);
var thirdRowValue = $("#balanceSheetExcelGrid").handsontable('getDataAtCell', 2, 1);
var fourthRowValue = $("#balanceSheetExcelGrid").handsontable('getDataAtCell', 3, 1);

var fifthRowCalculatedValue = parseFloat(firstRowValue)
                                        + parseFloat(secondRowValue)
                                        + parseFloat(thirdRowValue)
                                        + parseFloat(fourthRowValue);
$("#balanceSheetExcelGrid").handsontable('setDataAtCell', 4, 1, fifthRowCalculatedValue.toFixed(2), false);
```

}

If I were to call this on onChange at any point, it would recursively call itself.  Any easy solution to handling this?

**Comment by kvnandini** [comment]
$("#personal_example").handsontable('getCell', 4, 0); is giving me undefined, not getting value.
here is my example that i have built. http://jsfiddle.net/tngspzp3/1/
