### ISSUE TITLE
Changing Dropdown/Select Cell source Contents Dynamically?

### ISSUE THREAD

**Issue by Rykka** [handsontable/handsontable#1500]
Thanks for your hard work on handsontable .

When using the Dropdown, I have a usage of chaging the Dropdown source content while another dropdown changes.

e.g.:
    The Country Dropdown changes, The Province Dropdown will also change.

How can I achieve this?

Thank You~

**Comment by AMBudnik** [comment]
Issue closed in lack of other questions/suggestions for more than a year.
