### ISSUE TITLE
Sorting passing logical index through afterChange event

### ISSUE THREAD

**Issue by alexpaluzzi** [handsontable/handsontable#1501]
I am seeing the logical index and not the physical index being passed around in the afterChange event. In this documentation, at the very bottom, it says I should be getting the physical index through this event: https://github.com/warpech/jquery-handsontable/wiki/Understanding-column-sorting-plugin#rows-indices-translation

I added the event to the jsfiddle that is in the docs, I changed nothing else-- see here: http://jsfiddle.net/NsxWC/1/

Edit the first row before sorting and row 0 prints to console, as expected. Sort by any column and edit the first row again and the console still prints 0.

Is this intended?

**Comment by thbar** [comment]
@AMBudnik can you confirm that seeing logical indexes here is the intended behaviour? A regression could have nasty consequences.

**Comment by thbar** [comment]
Also, is [`getSelectedRange`](http://docs.handsontable.com/0.20.0/Core.html#getSelectedRange) guaranteed to provide logical indexes?

**Comment by AMBudnik** [comment]
Thanks for your ideas and concerns. I'll mark this issue to be discussed by our programmers.

**Comment by benjamin-meyers** [comment]
I am having the same issue but in the afterValidate event.  Inside the event I need the row index to grab another column in that row.  However, the row indexed shown is incorrect and sortIndex also returns incorrect values.

**Comment by epernice** [comment]
+1... Trying to use trimRows but running into this issue.

**Comment by budnix** [comment]
I think that this can be a bug. To resolve this issue it's necessary to validate all methods and hooks to decide where row/column indexes should be represented as visual index (WYSIWYG) and where as physical (source data).

This issue is related to all plugins which somehow modifies/translates row/column indexes (eq. TrimRows, Sorting, ManualColumnMove etc.).

**Comment by timwis** [comment]
Is there a way to get the logical row index in the meantime? I see `physicalRowsToLogical()` documented in [DataMap](https://docs.handsontable.com/0.24.3/DataMap.html#get) but I can't figure out how to access it.

**Comment by AMBudnik** [comment]
Hi @timwis here's a sorting tutorial where you also have a quick introduction to indices translation: https://docs.handsontable.com/pro/1.3.4/demo-sorting.html

**Comment by AMBudnik** [comment]
This topic needed a little update so I've created a demo (same settings, but simplified). You can test it here https://jsfiddle.net/handsoncode/cotqx48n/. It loads Handsontable v `7.1.1`.

The very first issue in this topic was the indexes. It was told that the `afterChange` hook should return physical indexes and instead we got visual ones. 

### Reproduction
In version `7.1.1` - nothing changes - we still get visual indexes.

![image](https://user-images.githubusercontent.com/10757813/66044126-293c2600-e521-11e9-9b15-41c710dec1bf.png)

ps. it also works the same for the latest build of `8.0.0-rc1` https://jsfiddle.net/handsoncode/0vzfscar/

### Get the physical index
If a developer is eager to get the physical index they have to call the `toPhysicalRow` method. 
The new index mapper doesn't change what we get in the `beforeChange`/`afterChange` hooks.

![image](https://user-images.githubusercontent.com/10757813/66044457-e169ce80-e521-11e9-9048-c2fb4368d644.png)

Once we'll be able to tell which indexes will be returned we should add the type of the index across all the methods/hooks in the documentation. As in some cases, like the one mentioned by @thbar sometimes it might be better to get visual indexes instead. 

When we call 

```js
hot.selectCell(0,0,1,1)
```

on a sorted table

![image](https://user-images.githubusercontent.com/10757813/66045407-f8112500-e523-11e9-8e4e-e1a781689c1c.png)

we get 

> Arguments(6) [0, 0, 1, 1, 0, undefined, callee: ƒ, Symbol(Symbol.iterator): ƒ]

which is easier to understand but may be harder to code when we remove data from those selected cells.

Demo with selection hook https://jsfiddle.net/handsoncode/4ygd7hap/

### Docs
Documentation currently doesn't tell us if we get physical or visual indexes, but this surely should be mentioned. This request will continue on the [/docs repository](https://github.com/handsontable/docs/issues/75).

**Comment by wojciechczerniak** [comment]
@AMBudnik Should we move this task to docs then?

**Comment by AMBudnik** [comment]
@wojciechczerniak I would like to gather `missing indexes descriptions` here https://github.com/handsontable/docs/issues/75
This topic was made to decide which indexes should we return for `beforeChange` / `afterChange` hook so..

1. If we want to keep visual indexes - explain why and close the topic
2. If we want to change them to physical - keep the issue opened

**Comment by AMBudnik** [comment]
Nothing changed here for 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/kvmjqr6L/

**Comment by AMBudnik** [comment]
> @AMBudnik Should we move this task to docs then?

Yes. It's time to move the subject to /docs to create the whole structure on when and how to inform users about the indexes.
