### ISSUE TITLE
Implementing a getDataAtRowHeader method

### ISSUE THREAD

**Issue by eldonbite** [handsontable/handsontable#1502]
Hi warpech,

I was wondering if you could perhaps implement a getDataAtRowHeader method for handsontable. Please refer to the following suggested code:

Handsontable.Core.prototype.getDataAtRowHeader = function(row, headerTxt) {
    var instance = $(this.rootElement).handsontable('getInstance');
    var headers = instance.getCellMeta(0, 0).colHeaders;
    for (var i = 0; i < headers.length; i++) {
        if (headerTxt === $.trim($('\<i\>'+headers[i]+'\</i\>').text().replace(/\\*/g, ''))) {
            return instance.getDataAtCell(row, i);
        }
    }
    return false; // or throw an error
};

Unfortunately I can't fork and make a pull request since I'm using the office network right now, but wanted to write this down so as not to forget. Thanks.

**Comment by AMBudnik** [comment]
Hi @eldonbite could you create a pull request for this case?
I guess if won't be implemented without checking if there are no conflicts with the code.
