### ISSUE TITLE
Undo-Redo don't work after sorting a column

### ISSUE THREAD

**Issue by lkoeller** [handsontable/handsontable#1503]
Problem found on v 0.10.5
See jsfidlle : http://jsfiddle.net/Mm4Eu/2/

Steps to reproduce : 
1) change Nissan by Renault
	Kia	Renault	Toyota	Honda
2008	10	11	12	13
2009	20	11	14	13
2010	30	15	12	13

2) sort column A in descending order (so Renault is now on row 4)
2010	30	15	12	13
2009	20	11	14	13
2008	10	11	12	13
	Kia	Renault	Toyota	Honda

3) Undo
2010	30	Nissan	12	13
2009	20	11	14	13
2008	10	11	12	13
	Kia	Renault	Toyota	Honda

Undo does not work in this use case

After first investigation, this issue is because you store logical row in changes list.
I think you must store physical row in changes list in order undo-redo could work with sorted column.

I will try to propose a patch.

Regards

**Comment by AMBudnik** [comment]
I guess it could be related to #2250

**Comment by AMBudnik** [comment]
Related to https://github.com/handsontable/handsontable/issues/2109

**Comment by AMBudnik** [comment]
As it is the same issue as https://github.com/handsontable/handsontable/issues/2109 please track changes to https://github.com/handsontable/handsontable/issues/2109
