### ISSUE TITLE
Perl script execution from handsontable

### ISSUE THREAD

**Issue by clauiordache** [handsontable/handsontable#1504]
Hello all,

I need to execute a perl script in the root directory of my server from a webpage (on same server). Some parameters need to be passed to this script from input boxes of a handsontable table on the page for it to work.

I have been thinking to use afterChange method..and through an ajax request to call the perl script (as it is called php script in your demos) providing the "changes" parameters from afterChange handsontable method.

Can be realized?At the moment is on the theoretical level..can you please provide me a very short lines of code of the requests through handsontable taking into consideration what user writes in the input box of the table?

Thank you!

**Comment by AMBudnik** [comment]
Hi @clauiordache please kindly open a new topic at [stackoverflow](https://stackoverflow.com/search?q=handsontable), github is used to report bugs.
