### ISSUE TITLE
Applying 'Ellipsis' style to column headers

### ISSUE THREAD

**Issue by SunandaChatterjee** [handsontable/handsontable#1505]
Hi,

We are using handsontable 0.9.18 version for our project. In that, we need to apply 'ellipsis' style to the column headers i.e 'relative' DIVS of the 'th'. Now, we are facing an issue at loadtime where in the end slowCheck method gets called which in turn calls the Handsontable.TableView.prototype.appendColHeader method which overrides our changes to the 'relative' DIV element. 

Code Snippet 

$( _container.getElementsByClassName( 'relative' ) ).css( {
            textAlign: 'right',
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            display: 'inlineBlock'
      });
NOTE: Here, _container is the handsontable instance.

How to avoid this problem? It would be very helpful if you can suggest any idea, since we are struggling for long to get any proper solution for this.

Thanks in advance.
Sunanda

**Comment by AMBudnik** [comment]
Please prepare a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/) for your issue and if it's not a problem update to [0.13.1](https://github.com/handsontable/handsontable/releases/tag/0.13.1)

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo;
