### ISSUE TITLE
getDataAtProp does not behave the same as getDataAtRowProp

### ISSUE THREAD

**Issue by r2evans** [handsontable/handsontable#1507]
`getDataAtRowProp(row,prop)` will return the data from the *data source* from *row* and *prop*, regardless if the *prop* property is being displayed.

`getDataAtProp(prop)`, however, only appears to return values from displayed cells, not from the data source as the [docs state](https://github.com/warpech/jquery-handsontable/wiki/Methods).

Example:

```
var $el = $('#element') ;    /* <div id="element"></div> */
var dat = [ { id:123, name:'John' }, { id:234, name:'Dick' }, { id:345, name:'Harry' } ] ;
$el.handsontable({data:dat, columns: [ {data:'name', type:'text'} ]}) ;
var hot = $el.data('handsontable') ;
hot.getDataAtRowProp(0,'id') /* 123 */
hot.getDataAtProp('name')    /* ["John", "Dick", "Harry"] */
hot.getDataAtProp('id')      /* [] */
                             /* expected: [ 123, 234, 345 ] */
```

(Using jQuery-1.10.2, handsontable-0.10.5, in Chrome on Win7.)

**Comment by AMBudnik** [comment]
Hi @r2evans 
Please check this 0.24.1 example: http://jsfiddle.net/83gmv7au/
Seems to work fine with latest version.

**Comment by AMBudnik** [comment]
I'm closing this issue in lack of reply and ability to reproduce the described issue.
