### ISSUE TITLE
Date sorting is not correct with different date formats

### ISSUE THREAD

**Issue by fincha** [handsontable/handsontable#1509]
I trying to sort with german date format "d.m.Y" and the sorting is not correct.

> dateFormat: 'dd.mm.yy'

sorting works fine with 

> dateFormat: 'mm/dd/yy'

**Comment by AMBudnik** [comment]
Since [0.12.6](https://github.com/handsontable/handsontable/releases/tag/0.12.6) we're using Pikaday + moment.js and this issue doesn't occur anymore. 

If you would face the same issue after updating to 0.12.6 or newer - please leave us a feedback.
