### ISSUE TITLE
Switching Chrome tabs deletes cell content

### ISSUE THREAD

**Issue by bufke** [handsontable/handsontable#1510]
1. In Google chrome go to http://handsontable.com/
2. Select a Cell
3. Switch tabs using ctrl-tab or ctrl-shift-tab or ctrl-number
4. Go back to handsontable tab
5. Move cells using arrow key or tab
6. Cell content is deleted.

Does not happen in Firefox. Handsontable seems to take over the ctrl-tab shortcut in Firefox.

**Comment by AMBudnik** [comment]
I couldn't reproduce it on Chrome 41.0.2272.89 (64-bit). If you still face this issue, please reply and provide more info about your HOT and Chrome version.
