### ISSUE TITLE
Insert row / insert column : Undo is OK but Redo inserts the row/column at initial position plus 1

### ISSUE THREAD

**Issue by lkoeller** [handsontable/handsontable#1511]
Problem found on v 0.10.5
See jsfidlle : http://jsfiddle.net/Mm4Eu/2/

Steps to reproduce : 
1) right clic on row 2 and select "Insert row above" : 
  that creates a new line on row 2
2) Undo --> OK
3) Redo --> NOK: the new line created is now on row 3
4) undo again --> NOK : it creates a new line on row 2, but existing line 2 ("2008") is lost

I corrected this by changing  the following lines : 
  Handsontable.UndoRedo.CreateRowAction.prototype.redo = function (instance, redoneCallback) {
    instance.addHookOnce('afterCreateRow', redoneCallback);
    // instance.alter('insert_row', this.index + 1, this.amount);
    instance.alter('insert_row', this.index, this.amount);
  };

and the same issue occurs with created column and undo-redo, that is corrected with the following code:
  Handsontable.UndoRedo.CreateColumnAction.prototype.redo = function (instance, redoneCallback) {
    instance.addHookOnce('afterCreateCol', redoneCallback);
    // instance.alter('insert_col', this.index + 1, this.amount);
    instance.alter('insert_col', this.index, this.amount);
  };

I do not understand why you intentionally writed index + 1 instead index  !

Regards

**Comment by slat** [comment]
Still happening on 0.13.1 on Windows Chrome v41.
![2015-03-29_00-20-44](https://cloud.githubusercontent.com/assets/2395391/6880892/78c522e8-d5aa-11e4-8063-2a03b58f9a8d.gif)
After insert, alternating between undo and redo has the behavior shown.

**Comment by AMBudnik** [comment]
Connected with https://github.com/handsontable/handsontable/issues/1520

**Comment by AMBudnik** [comment]
Hi @lkoeller  @mariotacke @slat 
The issue seems to be gone in v `2.0.0`. Can you confirm 
Demo: http://jsfiddle.net/72ph3pjf/

**Comment by slat** [comment]
Cheers, appears fixed.

**Comment by AMBudnik** [comment]
Great @slat 
thank you for a prompt confirmation

**Comment by lkoeller** [comment]
OK it is fixed now (according to the jsfiddle demo)
Thanks

**Comment by AMBudnik** [comment]
Thank you for confirmation @lkoeller
