### ISSUE TITLE
beforeRemoveRow and afterRemoveRow ignore sorting

### ISSUE THREAD

**Issue by jpravetz** [handsontable/handsontable#1515]
In the event where data is sorted, it appears that beforeRemoveRow and afterRemoveRow pass the index of the unsorted data, rather than the sorted data. Thus I don't see a way to get the actual data for the list of rows that is to be deleted. The method getDataAtRow() also returns unsorted results. Am I missing the technique that we should be using to get the actual rows that are deleted? Or is this an oversight? 
Note that I am using a JSON copy of my data, rather than the original data, because handsontable can't successfully crawl my input collection (from Parse.com data). Therefore I need to know the actual data that is being deleted, so I can delete it in the database.

**Comment by AMBudnik** [comment]
`getDataAtRow()` works with sorting, sample [demo](https://jsfiddle.net/f7m8190q/). Please check it - and if you still face this issue please prepare a demo of your code.

**Comment by AMBudnik** [comment]
Issue closed in lack of reply for more than a month.

**Comment by nosir** [comment]
After sorting, the third param of beforeRemoveRow still returns the unsorted indexes.
However in the doc, it tells we should expect the `visual indexes of processed rows`, is it wrong?
https://docs.handsontable.com/pro/3.0.0/Hooks.html#event:beforeRemoveRow
The first param returns the correct visual index after sorting has been applied, so it feels confusing

**Comment by AMBudnik** [comment]
Hi @nosir 

You're right, the docs are wrong. 

I'm using [this example](http://jsfiddle.net/w9nhmj58/)
![image](https://user-images.githubusercontent.com/10757813/40161561-744d5e90-59b1-11e8-818d-b3fd043ba836.png)

And if I sort it descending
![image](https://user-images.githubusercontent.com/10757813/40161808-29028ef0-59b2-11e8-8efc-c9f8005b9a01.png)

and remove first two rows I get

`0 2 (2) [4, 3]`
by logging 

```
beforeRemoveRow: function(i, amount, visualRows){
     console.log(i, amount, visualRows)
}
```
`i` (index) return `0` as a visual index of the first deleted row.
`amount` returns `2` which is currect.
But then the `visualRows` returns `4, 3` which are the physical rows indexes as seen in the first table view.

I've added the same report on a new topic at https://github.com/handsontable/handsontable/issues/5100 as this one is closed

**Comment by nosir** [comment]
Actually, I found out that if you apply the sorting and log `toPhysicalRow`, it surprisely transfers the index to visual indexes:
```
    beforeRemoveRow: function(i, amount, rows){
      rows.forEach(row => {
      	console.log(hot.toPhysicalRow(row))
      })
   }
```
Not sure it's the bug of `toPhysicalRow` or that's because the original 3rd param is wrong

**Comment by AMBudnik** [comment]
Hi @nosir 
that's a clever choice! Even if something is already `physical` not `logical` Handsontable can still reverse it to `physical` (the action is not blocked). We even have some parts of the code that changes the index twice (!) physical > logical >physical but as it's not logically smart and uses resources without any reason we decided to create a tool that will allow us to handle indexes in one place (just a prototype at this moment).
