### ISSUE TITLE
Remove Row then Undo action  corrupts the undo stack if sorting is enabled

### ISSUE THREAD

**Issue by lkoeller** [handsontable/handsontable#1516]
Problem found on v 0.10.5
See jsfidlle : http://jsfiddle.net/Mm4Eu/2/

Steps to reproduce : 
1) right clic on row 2 (2008) and select "Remove row"
2) undo --> OK, row 2 is restored
3) right clic --> NOK : Redo is not available and Undo is available

The instance UndoRedo object contains : 
undoRedo: Handsontable.UndoRedo
doneActions: Array[13]
0: Handsontable.UndoRedo.ChangeAction
1: Handsontable.UndoRedo.ChangeAction
2: Handsontable.UndoRedo.ChangeAction
3: Handsontable.UndoRedo.ChangeAction
4: Handsontable.UndoRedo.ChangeAction
5: Handsontable.UndoRedo.ChangeAction
6: Handsontable.UndoRedo.ChangeAction
7: Handsontable.UndoRedo.ChangeAction
8: Handsontable.UndoRedo.ChangeAction
9: Handsontable.UndoRedo.ChangeAction
10: Handsontable.UndoRedo.ChangeAction
11: Handsontable.UndoRedo.ChangeAction
12: Handsontable.UndoRedo.CreateRowAction
     amount: undefined
     index: 4
undoneActions: Array[0]

There are 12 changeAction and 1 CreateRow action in the doneActions array, and the undoneActions array is empty.

The expected content is: doneAction empty and undoneAction contains the removeRow action.

First investigation shows that this corruption is made by the observer plugin, which is started by the sort plugin when column sorting is enabled. (function enableObserveChangesPlugin ).

If i remove the call of enableObserveChangesPlugin function, the issue does not exist and the behaviour seems correct.

Could someone explain to me what is the purpose of this Observe plugin ? And why it is activated when sorting is enabled ?

**Comment by AMBudnik** [comment]
Confirmed with 0.23.0 http://jsfiddle.net/Mm4Eu/55/

**Comment by AMBudnik** [comment]
duplicated with https://github.com/handsontable/handsontable/issues/2325
