### ISSUE TITLE
Illustrate our name

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1517]
A lot of people doubt what is the pronunciation of "Handsontable" (http://stackoverflow.com/questions/24060388/handsontable-pronunciation)

The official pronunciation is like "Hands on table".

Let's put a drawing on http://handsontable.com/ to illustrate that!

My idea is that there needs to be a sweet illustration of "hands on table" (table as in furniture and as in data document). This can be in some style that would appeal to JavaScript ninjas (manga maybe?)

**Comment by krzysztofspilka** [comment]
Good idea but not applicable in our new website.
