### ISSUE TITLE
Serialize Filldown

### ISSUE THREAD

**Issue by jacobetz** [handsontable/handsontable#1521]
In excel you can put in a numeric integer and drag down to serialize the value.

Is there an method already or is this planned?

![image](https://cloud.githubusercontent.com/assets/7818619/3205182/d25ed8d4-edb2-11e3-99d4-14bb1bb645eb.png)

![image](https://cloud.githubusercontent.com/assets/7818619/3205187/d63ef66e-edb2-11e3-8cda-17dbecdeef87.png)

![image](https://cloud.githubusercontent.com/assets/7818619/3205189/d909ff1a-edb2-11e3-8ed6-45aa2abe2191.png)

**Comment by AMBudnik** [comment]
Currently, like in an [this example](http://jsfiddle.net/p5u9ypqr/) when you:

1. Cells range B2:B5
2. Use dragable box to scroll to B9
3. you get the same values in B2:B5 like in B6:B9 

...and so on.

I really like your suggestion, so please let me add it to feature candidates.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
