### ISSUE TITLE
Drag scroll scrolls to far 

### ISSUE THREAD

**Issue by gravey16** [handsontable/handsontable#1523]
table inside of a div when drag scroll to end will continue scroll past the number of rows.  this causes the table to shrink up, problem when fixed number of rows like 10 where one does not want any scrolling.

Hard to explaing, but scroll past the end of the data, you will be left with a table with 3 rows, insteand of filling out the div

http://jsfiddle.net/knvn/u7nYk/

**Comment by AMBudnik** [comment]
I couldn't reproduce it, can you provide more information about this issue?

**Comment by AMBudnik** [comment]
I assume it's not an issue any more since there was no reply for more than a month.
