### ISSUE TITLE
Inheriting Column renderer properties- like type, etc

### ISSUE THREAD

**Issue by udaiarora** [handsontable/handsontable#1532]
So I have a cell renderer which calls this function:

function greenBGRenderer(instance, td, row, col, prop, value, cellProperties) {
Handsontable.renderers.TextRenderer.apply(this, arguments);
td.className= "ed-row";
}
I also have the column option which specifies the "type" of column (and source if its a dropdown, etc)

I might be completely missing something but the problem I am facing is that after the cell renderer is called, the everything including the dropdown, check box cells, etc becomes text. I am pretty sure this is because I use a "TextRenderer" in the function I wrote. Is there a way to not mess up the type of the cells after the cell renderer calls this function?

**Comment by AMBudnik** [comment]
Please provide a demo.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo. Please reply if you still need help in this case.
