### ISSUE TITLE
added arrow button for horizontal scrolling

### ISSUE THREAD

**Issue by u007** [handsontable/handsontable#1533]
hi,

ive added arrow head at most left and most right to allow user
to scroll 1 column at a time.
i'am using bootstrap Glyphicons for the symbol,
you may pull from my fork:
https://github.com/u007/jquery-handsontable/commit/47bba034ed45f6a128152f851cff0c1b7d40726c

thank you

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
