### ISSUE TITLE
#bad value# in an empty cell

### ISSUE THREAD

**Issue by lafar6502** [handsontable/handsontable#1539]
Hi, there's a problem with checkbox columns. When an empty row is added to a table, it contains #bad value# in checkbox cells and you cannot change this value to anything else - the cell is read only, stuck with #bad value# in it. I'd like to specify some default value for a new row, but there's no way to do so.

Version: 0.10.5

**Comment by anoopkp06** [comment]
This issue still exists,

**Comment by rock1984** [comment]
Go to http://handsontable.com/demo/checkbox.html.
Click do Edit in jsFiddle.
Remove 'available: false' from some item in the getCarData function.
Run! the issue remains.

**Comment by sunny061** [comment]
I am also experiencing the same error. When I my cell has a value inside and I change it's type, it displays a #bad value#. If the cell value is null, then it's fine.

**Comment by dgollub** [comment]
"#Bad  value" also happens when you have an empty data set, ie. you are starting out with an empty table, that has only the columns and column headers predefined.

**Comment by ichiriac** [comment]
I also have the issue when I uncheck a checkbox and I use checkedTemplate and uncheckedTemplate. 

You can try this jsfiddle :
http://jsfiddle.net/hzqobm5g/

**Comment by AMBudnik** [comment]
Thanks for sharing @ichiriac I'm reopening this issue.

**Comment by clo-dan** [comment]
I have the same problem as ichiriac. If I use a checkedTemplate of 1 and an uncheckedTemplate of 0, I get #bad-value# when unchecking the box. Any workaround for this? I am using 0.26.0.

**Comment by swistach** [comment]
It's problem with checkedTemplate/uncheckedTemplate.
short list of the problematic conversions:
numeric -> numeric = #bad-value#
numeric -> boolean = #bad-value#
boolean -> numeric = #bad-value#
string -> numeric = #bad-value#

**Comment by marc-antoinepelletier** [comment]
Any workaround for the moment ?

**Comment by mota57** [comment]
I try to set a checkbox by doing the following.  Hot. GetCellMeta(0,0).type= "checkbox";. And i get #bad-value#

**Comment by AMBudnik** [comment]
hi @mota57 I've tested this example here: http://jsfiddle.net/kt6racbp/ seems it works as expected

**Comment by marc-antoinepelletier** [comment]
@AMBudnik if you paste text or drag a cell to the cell with the checkbox you will get #bad-value#

**Comment by AMBudnik** [comment]
Thanks for sharing details and your prompt reply Marc.
I've managed to reproduce the cell type change.
![issue-hot-checkbox](https://cloud.githubusercontent.com/assets/10757813/18268818/c220be8c-7425-11e6-8d59-fc7137709b7f.gif)
The `checkbox` cell type is changing (copied) for the checkbox while it should stay the same (like for the `date` cell in the last row).

**Comment by marc-antoinepelletier** [comment]
I don't think it's the first that this bug is reported no ?

**Comment by mota57** [comment]
@AMBudnik ok but what if you want to put a checkbox on the first cell of the first column. ? It said #bad-value#. So how to handle that ? test it yourself.!!

**Comment by mota57** [comment]
@AMBudnik ok to fix it I add one line to your code so the code should look like this. And the default value for the checkbox is false. :dancer: 

  hot1.getCellMeta(0,0).type = 'checkbox';
  hot1.setDataAtCell(0,0,false)
  hot1.render();

**Comment by mota57** [comment]
Hey I think I fix what I was saying. So your code should look like this and the default value would be "false". Test it!!

 hot1.getCellMeta(lastCoordinates.startRow, lastCoordinates.startColum).type ="checkbox";
 hot1.setDataAtCell(0,0,false);
 hot1.render();

**Comment by AMBudnik** [comment]
Thanks for sharing additional details @mota57 Unfortunately it works like that when there's a bug all actions taken after produce even more bugs.
The issue is not yet reviewed so each tips are highly apperciated.

**Comment by AMBudnik** [comment]
Thanks to our trusted user Chow we have managed to take one step towards understanding this bug.
Here's an updated demo: http://jsfiddle.net/xu8fbqmL/ 
The change was to set the boolean value for the column while initialization. 

Still we can see that the checkbox is shifted
![checkbox](https://cloud.githubusercontent.com/assets/10757813/18381640/78efc85c-767d-11e6-8ce6-d879964c1dd3.gif)

**Comment by marc-antoinepelletier** [comment]
@AMBudnik I am sorry but if you copy paste text in the checkbox cell, the type is still changing with #bad-value#.
Try to copy the first cell containing "Mercedes A 160" and paste it in the checkbox cell.

**Comment by AMBudnik** [comment]
You're right @marc-antoinepelletier 
Thank you for your prompt reply and effort to check the case.
I have a feeling that this can be related to this issue https://github.com/handsontable/handsontable/issues/3540

**Comment by jansiegel** [comment]
@mota57 Let me make sure if I understand what you're trying to achieve. If you're trying to make the cell at (0,0) coordinates a checkbox, you'll need to either:
* assign the `checkedTemplate`/`uncheckedTemplate` (explained in our docs http://docs.handsontable.com/pro/1.6.0/demo-checkbox.html) 

Take a look at this example: http://jsfiddle.net/js_ziggle/2enh673x/
* assign the cell value to `true`/`false`, as these are the default checkbox template values, as in here: http://jsfiddle.net/js_ziggle/2enh673x/1/

Otherwise the checkbox renderer wouldn't know what to render.

Similarly to @marc-antoinepelletier example:
> Try to copy the first cell containing "Mercedes A 160" and paste it in the checkbox cell.

How would the checkbox renderer know if "Mercedes A 160" translates to "checked" or "unchecked"? I wouldn't know either :)

**Comment by jansiegel** [comment]
Oh, and the bug @AMBudnik found is probably caused by `autofill` moving the cell meta where it shouldn't, and it should be definitely fixed, but it's not connected with this isse.

**Comment by marc-antoinepelletier** [comment]
@jansiegel I assume the checkbox renderer would check the value passed the cell, and if it's not a default boolean or any other default checkbox value you assigned in the setting, it would check the value or do nothing no ?

I had to make a custom checkbox renderer to translate this behaviour, I figure that should be handle by default in Handsontable no ?

**Comment by jansiegel** [comment]
I'm not sure what you mean by
> it would check the value or do nothing

What the renderer does is checking if the cell value is the same as the one defined in the templates, and if there are none, check if the value is a boolean. If nothing passes that verification it displays `#bad-value#`, as it means the cell's value is not supported by the renderer.

**Comment by marc-antoinepelletier** [comment]
I meant it would check (true value) or leave the cell as it is without updating it. From what you are saying, the most logic way would be that nothing should happen to the checkbox cell at the end instead of displaying #bad-value# if the value doesn't correspond no ?

**Comment by jansiegel** [comment]
@marc-antoinepelletier Ok, now I get it. Thanks for clarifying!

I think it's a good idea for a new feature - setting the `allowInvalid` property to `false` for the checkbox-typed cell would work just like you explained. The property is currently available for the autocomplete and date editors, but it would be also useful for the checkboxes.
I've created a new issue for this: #3755

**Comment by marc-antoinepelletier** [comment]
@jansiegel Awesome, Thanks ! :)
