### ISSUE TITLE
Checkbox in Header of Handsontable is getting unchecked on Scroll and also value is lost

### ISSUE THREAD

**Issue by bongdreams** [handsontable/handsontable#1540]
Hi,

I am facing a blocker issue where I have CheckBoxes in the header of the Handsontable and there are multiple columns (more than what can be accommodated to be viewed on a single page so scrolling is initiated). Now if I check a column and then scroll horizontally or vertically then the 'checked' checkbox is unchecked

Here is a sample visual of the issue. Check the checkbox and then scroll the handsontable. You will notice that the checkbox is getting unchecked.

http://jsfiddle.net/vECgN/15/

Please help.

Thanks,
Saikat

**Comment by AMBudnik** [comment]
Hi @banerjeesaikat6 I would really appreciate if you could check if this issue still occurs in your code after updating to 0.13.0.

**Comment by abctytc** [comment]
here , it still happened in 0.13.1 .  is there any choise to solve this issue , i would really want it

**Comment by banerjeesaikat6** [comment]
I solved the issue by capturing the instance of the checkboxes in an array (say value etc.) and triggering the checking and unchecking of these from the render event of HOT..

**Comment by abctytc** [comment]
I get it , HOT has to refresh its hearder . so we could store the value of the checkboxes into a collection ,and then reback the value when HOT refresh refreshing by own way .

**Comment by AMBudnik** [comment]
Glad you solved it out. If any our help will be needed, feel free to write back.

**Comment by AMBudnik** [comment]
I'm reopening this issue as the was no official fix for it.

**Comment by wojciechczerniak** [comment]
Old issue but IMO it's not a bug. We're changing header renderer that is refreshed with every Handsontable cycle so it's up to us to keep the state and set it with the next rendering cycle. Headers are not meant to store data.

The solution is what the original author did 👍 Closing.
