### ISSUE TITLE
enterMoves not working in IE 11

### ISSUE THREAD

**Issue by BDworak** [handsontable/handsontable#1541]
After creating a hands-on-table with the enterMoves option and returning an object in form {row: 1, col: 0}, IE changes the position of the selection to 0,0 on the table. 

Same code tested with Chrome works fine. Is there a quick solution??
Is there a workaround using another option and doing a grid.selectCell()?

**Comment by AMBudnik** [comment]
Hi @BDworak please update to 0.14.1 I tried it with IE 11 - works fine with any typed data.
