### ISSUE TITLE
Setting dropdown strict to false doesn't work

### ISSUE THREAD

**Issue by tikitikifoofoo** [handsontable/handsontable#1542]
If you just use one of the JSFiddle examples from the website and add the strict: false option to one of the columns, the validator will tell you there's an error if you type in a value not provided in the list. Oddly enough, if you don't define the strict option, the validation works fine.

**Comment by AMBudnik** [comment]
Hi, please check [it](http://handsontable.com/demo/autocomplete.html) now. It should work fine - if it does not, please provide your OS/Browser info.
