### ISSUE TITLE
Dropdowns not working in IE10

### ISSUE THREAD

**Issue by akarsha4** [handsontable/handsontable#1544]
Hi,

In our application we have around 40 drop downs in each row .. And around 30 rows minimum.

I am impressed with this library and i tried every possibility of our application, everything seems to work fine..Except when i have 40 rows with 40 drop downs in each row - performance is really really bad in IE 10 whereas in chrome is fine.

But we need to work it out to make it work in IE 10.

Could you please give any solutions to this kind of things

Thanks !

**Comment by AMBudnik** [comment]
Please update to [0.14.0](https://github.com/handsontable/handsontable/releases/tag/0.14.0) dropdown should work as expected. If you would have issues with your code after updating, please prepare a demo.
