### ISSUE TITLE
Context menu to add column not working when defining columns property to hide some columns

### ISSUE THREAD

**Issue by dshrestha** [handsontable/handsontable#1545]
I needed a way to create a spreadsheet where user can potentially paste in any no of columns. Currently pasting things in the spreadsheet does not work as mentioned here https://github.com/warpech/jquery-handsontable/issues/553, so I wanted to enable the context menu to add column. This works fine when you have plain array as data source and you are not setting the columns property, but if you do need to define the columns attribute then things dont work when setting the 

```
contextMenu: ['col_right']
```

I needed to define the columns property because I need to hide certain columns (as mentioned here https://github.com/warpech/jquery-handsontable/issues/120).
The only way to make things work would be to define custom action for context menu, but I am not sure how to go about it.

Here is a jsbin : http://jsfiddle.net/8V4Z5/1/
I have the asked same question here too : http://stackoverflow.com/questions/24372649/context-menu-to-add-column-not-working-when-defining-columns-property-to-hide-so

Thanks

**Comment by AMBudnik** [comment]
Please update to 0.14.1 pasting multiple columns works as expected. About hiding columns please check [this demo](http://handsontable.com/demo/sorting.html) you can hide columns by an `columns` option like here:

`columns: [
    {data: 0},
    {data: 1}
  ],`
(shows only 1 and 2 column)

**Comment by alexob** [comment]
I have identical problem. The items "Insert column..." in the context menu are greyed.

I was tried set "data" parameter as array (not by object) and was removed init object for parameter "columns". After that the items "Insert column..." were enabled.

Please help me initialize type of the columns and have posibility to add new column from context menu.

Thanks

**Comment by AMBudnik** [comment]
hi @alexob can you create a demo where we will be able to replicate the same behavior?

**Comment by alexob** [comment]
yes of course
here [http://jsfiddle.net/b2g2h7oh/273/]

Why I cannt add new column in this grid? 
But can to add new row.

**Comment by AMBudnik** [comment]
Thanks for a demo @alexob 
If you define number of columns via object structure like in your example:

```
columns: [
    {type: 'numeric', format: '$0,0.00'},
    {type: 'date', dateFormat: 'DD/MM/YYYY', correctFormat: true},
    {type: 'numeric', format: '0.00%'},
    {type: 'numeric', format: '0.00%'},
    {type: 'checkbox'}
  ]
```

adding columns is not available.

Here's a demo where I've made custom context menu options to allow it: http://jsfiddle.net/1my0pct0/
That way the column that is added has default settings (no data, text cell type).

**Comment by alexob** [comment]
thank you.
It help me.

**Comment by AMBudnik** [comment]
happy to help,
have a great day @alexob

**Comment by patarapolw** [comment]
Not intuitive at all, and undocumented:

```javascript
const contextMenu = hot.getPlugin('contextMenu');
contextMenu.menu.menuItems.splice(3, 2,
  {
    key: "col_left",
    name: "Insert column left",
    callback: ()=>{
      const currentCol = hot.getSelected()[0][1];
      insertColumn(currentCol, actualConfig, hot);
    },
    disabled: false
  },
  {
    key: "col_right",
    name: "Insert column right",
    callback: ()=>{
      const currentCol = hot.getSelected()[0][1];
      insertColumn(currentCol + 1, actualConfig, hot);
    },
    disabled: false
  }
);

hot.updateSettings({
  contextMenu: contextMenu.menu.menuItems
});

function insertColumn(index, actualConfig, hotInstance){
  if(typeof renderers === 'string'){
    actualConfig.columns.splice(index, 0, {
      renderer: renderers
    });
  } else {
    actualConfig.columns.splice(index, 0, {});
  }

  if(Array.isArray(actualConfig.colHeaders)){
    actualConfig.colHeaders.splice(index, 0,
      characterRange('A', actualConfig.colHeaders.length + 1)[index]);
  } else {

  }

  actualConfig.colWidths.splice(index, 0, null);

  actualConfig.data.forEach((item)=>{
    item.splice(index, 0, '');
  });

  hotInstance.updateSettings({
    columns: actualConfig.columns,
    colHeaders: actualConfig.colHeaders,
    colWidths: actualConfig.colWidths,
    data: actualConfig.data
  });
}

function range(size, startAt = 0) {
  return [...Array(size).keys()].map(i => i + startAt);
}

function characterRange(startChar, numberOfChar) {
  return String.fromCharCode(...range(numberOfChar, startChar.charCodeAt(0)))
}
```
