### ISSUE TITLE
Cell properties and sorting/column reorder

### ISSUE THREAD

**Issue by svwhite** [handsontable/handsontable#1548]
I am trying to implement some functionality, where I keep track of certain information for the content of each cell and use this in a custom renderer.

In the first case, I need to mark cells that are changed from their initial value.
The next step is to change marking based on the type of data change.

It works fine, until, I sort on a column or reorder the columns.

for example, 
In the beforeChangeevent, I set a property like, 
  $(ele.getCell(element[0], ele.propToCol(element[1]))).data("initialized", true);

I use this (and another value) in the renderer like,
  if ($(td).data("initialized") == true && $(td).data("original") != value) {

This works fine, but the data is associated with the table cell, not the content.
So, when I sort or reorder, the data becomes disassociated with the data.
What I am looking for is a way to connect "properties" to the data that remains with the data after sorting/reordering.

With respect to sorting, I know that I could do this by adding hidden columns for each visible column that I want to track data on. Although this would mean having more hidden columns, than visible columns (ultimately I need more than 2 properties associated with each value), plus the number of columns is quite high. But this would still not solve my problem when reordering columns (not quite true, this would work in cases where I can reference a visible column by name and use something like "ele.propToCol(a_col_name)".

Hmm, I would appreciate any pointers / tips that you might have.

Regards,
Steve

**Comment by AMBudnik** [comment]
Thank you @mvagnoni for support. I assume I can close this issue in lack of reply from an author since more than a month. But this issue can be reopened if needed.
