### ISSUE TITLE
Multiple call backs while using afterRemoveRow

### ISSUE THREAD

**Issue by dharish008** [handsontable/handsontable#1549]
I have been facing some issue with the call back function afterRemoveRow. I used it to get the index and then remove the entry in mysql database, but I have observed that after a few operations of editing and saving new values in the handsontable the records are getting deleted on its own without the remove row operation. I have also observed the ajax calls originating from html in the access logs. Is there a bug in it or am I doing something wrong. My ajax code goes like this. 

afterRemoveRow: function (index, amount) {
				  $.ajax({
						url: "save_values.php",
						dataType: "json",
						type: "POST",
						data: {"index": index}
						});
				  }

**Comment by AMBudnik** [comment]
Can you say when exactly data is removed?

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply for more than a month.
