### ISSUE TITLE
CopyPaste steals focus from any contentEditable element when CTRL pressed

### ISSUE THREAD

**Issue by elfiq** [handsontable/handsontable#1550]
so, no copy and paste to contentEditable element.

i've just added this:
document.activeElement.contentEditable==='true' || 

to the line #6343 at jquery.handsontable.full.js
that solves my problem

**Comment by adi-pjackson** [comment]
Here's a jsfiddle that shows the problem: http://jsfiddle.net/jqwnj1w6/

I'm finding that it only steals focus if there's no text selected. This still affects users because it breaks the ctrl+A shortcut in contenteditable elements.

**Comment by AMBudnik** [comment]
Please try this exaple with newest handsontable version. It should work as expected right now.

**Comment by adi-pjackson** [comment]
Yes, fixed in the latest version

**Comment by AMBudnik** [comment]
Thank you @adi-pjackson Issue will be closed.
