### ISSUE TITLE
getSelected is not working for me

### ISSUE THREAD

**Issue by ashish4710** [handsontable/handsontable#1553]
Code I used,
var $container = $("#myExcelSheet");
$container.handsontable({
    rowHeaders:true,
    colHeaders:true,
  
    manualColumnResize:true,
    persistentState:false,
    contextMenu:true,
    currentRowClassName:'currentRow',
    currentColClassName:'currentCol',
	multiSelect:true,
    columnSorting:false,
    afterChange:function (change, source) {
        if (source === 'loadData') {

            return; //don't save this change
        }
        if ($parent.find('input[name=autosave]').is(':checked')) {
            clearTimeout(autosaveNotification);
            $.ajax({
                url:"../json/save.json",
                dataType:"json",
                type:"POST",
                data:change, //contains changed cells' data
                complete:function (data) {
                    $console.text('Autosaved (' + change.length + ' ' +
                            'cell' + (change.length > 1 ? 's' : '') + ')');
                    autosaveNotification = setTimeout(function () {
                        $console.text('Changes will be autosaved');
                    }, 1000);
                }
            });
        }

    }

});
var handsontable = $container.data('handsontable');

function tableG() {
	
    $.ajax({
        url:"../json/KpmgProject20_Kpmg20_KpmgType20_kpi14.csv",
        type:'GET',
        success:function (res) {
            handsontable.loadData($.csv.toArrays(res));
            $console.text('Data loaded');
        }
    });
}

Please help here.

**Comment by hash1492** [comment]
Please reply, same problem here. getSelected( ), getValue( ) methods not working

**Comment by AMBudnik** [comment]
Hi, it'll be appreciated if you could prepare a demo.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo. Please prepare one, and we'll reopen the issue.
