### ISSUE TITLE
Remove dependency on jQuery UI Datepicker

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1568]
jQuery UI Datepicker should be replaced with something that does not use jQuery.

One of the problems is that jQuery UI Datepicker does not work correctly in Web Components/Shadow DOM.

Possible replacements:

- our own datepicker based on HandsontableEditor
- http://dbushell.github.io/Pikaday/

**Comment by krzysztofspilka** [comment]
I have found a bunch of inaccuracies (e.g. `escape` key save content instead of cancel editing)

**Comment by jansiegel** [comment]
Released in version 0.12.6
