### ISSUE TITLE
Context menu sometimes appears off the table

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1573]
When the context menu does not fix below the selected cell, it opens above it.

For some reason, when it opens above the cell, there is a 100px offset between the menu and the cell.

![screenshot 2014-07-07 11 51 33](https://cloud.githubusercontent.com/assets/566463/3493815/51219dc0-05bc-11e4-9675-18c69dde4f68.png)

**Comment by warpech** [comment]
I will review this.

**Comment by warpech** [comment]
Fixed a problem with actual positioning. Needs tests (assigning back to development)

**Comment by krzysztofspilka** [comment]
Altough we've fixed the issue with displaying the menu 100px above the cell, now it's hiding beneath bottom edge of the browser.

After fix:
![screenclip 1](https://cloud.githubusercontent.com/assets/8048526/5668111/3b79e318-976d-11e4-8913-fd54bfa02cb6.png)

Should be:
![new-shot](https://cloud.githubusercontent.com/assets/8048526/5668121/59c53d7c-976d-11e4-85f6-082484635c28.png)
