### ISSUE TITLE
copy-paste problem with price formatted columns

### ISSUE THREAD

**Issue by hakanonal** [handsontable/handsontable#1579]
Hello when I load a data table and when I try to copy a numeric cell with price formatted and paste it to another cell in the same column the pasted value is the multiplied with 1000. Here is a screen shot.

![image](https://cloud.githubusercontent.com/assets/2088468/3512942/6ddc20c2-06be-11e4-966a-4013c748a2ed.png)

**Comment by AMBudnik** [comment]
It should work fine from [0.12.0](https://github.com/handsontable/handsontable/releases/tag/0.12.0) if you still face this issue, please reply.
