### ISSUE TITLE
Autocomplete revert to original when invalid (strict: true)?

### ISSUE THREAD

**Issue by anton164** [handsontable/handsontable#1581]
I was wondering if it's possible to have the AutoComplete editor revert to the original value when it fails to validate?

Clicking away (or hitting escape) is often meant to cancel the operation, and I feel that it's limiting when the user is being "forced" to focus on the cell before he manually corrects his mistake. In our application it's definitely more sensible to revert to the original value in the cell when the user clicks away (or hits escape).

This is a suggesition for handsontable in general, but as for a temporary workaround, I can't seem to find where the behavior could be changed, any tips?

Thanks for the great grid editor you've provided and any help is greatly appreciated!

**Comment by krzysztofspilka** [comment]
It's added to our feature request list: https://github.com/handsontable/handsontable/wiki/Feature-requests (no #58)
