### ISSUE TITLE
Using mouse wheel over row header scrolls the page

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1582]
When I use the mouse scroll wheel over scrollable table, only the table is scrolled.

But when I use the mouse wheel over the row header the page scrolls.

**Comment by AMBudnik** [comment]
With [0.14.1](https://github.com/handsontable/handsontable/releases/tag/0.14.1)

* Occurs in FF 37.0.1, but only if the first scroll was made when a mouse cursor was on the row's header.
* Doesn't occur on Chrome 41.0.2272.104 & Safari 8.0.4 (10600.4.10.7)

**Comment by swistach** [comment]
Scrolling on row headers works since 0.15.0-beta1. But scrolling is not working on the hot_clone_top_left_corner element, and this is another issue.
