### ISSUE TITLE
CopyPaste, copy range onPaste needed

### ISSUE THREAD

**Issue by zjazd** [handsontable/handsontable#1584]
I need information from where cells was copied, when I paste, how to do this in elegant way which method override or which event handle?

I need it to copy metadata that applies to specific cell range when I am copying cell range.

I can do this by modifying copyable and triggerPaste function and serialize and deserialize selection range to copyable string.

But i want to do this without source script modification.
```javascript
CopyPasteClass.prototype.triggerPaste = function (event, str) {
  var that = this;
  if (that.pasteCallbacks) {
    setTimeout(function () {
      var val = (str || that.elTextarea.value).replace(/\n$/, ''); //remove trailing newline
      var selection;
      if( !str )//textfrom selection
      {
          var pos = val.indexOf('#');
          selection = JSON.parse(val.substring(0, pos));
          val = val.substring(pos+1);
      }
      for (var i = 0, ilen = that.pasteCallbacks.length; i < ilen; i++) {
        that.pasteCallbacks[i](val, selection, event);
      }
    }, 50);
  }
};

CopyPasteClass.prototype.copyable = function (str, selection) {
  if (typeof str !== 'string' && str.toString === void 0) {
    throw new Error('copyable requires string parameter');
  }
  
  var selectionString = JSON.stringify(selection) + '#';
 
  this.elTextarea.value = selectionString + str;
}; 
```

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
