### ISSUE TITLE
Unify getting setting/cellProperty/cellMeta

### ISSUE THREAD

**Issue by kubak10** [handsontable/handsontable#1585]
Now you can reach get all those form few ways like getSettings().xxx or priv.xxx or instance....
It will be good to unify this

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
probably should be discussed with https://github.com/handsontable/handsontable/issues/3617
