### ISSUE TITLE
getting an array of arrays from a HOT 

### ISSUE THREAD

**Issue by hackula1** [handsontable/handsontable#1588]
I'm trying to export the data from handsontable to XLSX using https://github.com/SheetJS/js-xlsx, and they have a way of writing an array of arrays https://gist.github.com/SheetJSDev/88a3ca3533adf389d13c

Is there an easy way to get the data from the worksheet as an array of arrays?

**Comment by AMBudnik** [comment]
For topic including other libraries please write on our [SO](https://stackoverflow.com/questions/tagged/handsontable)
