### ISSUE TITLE
Autocomplete scrollbar is off

### ISSUE THREAD

**Issue by chandrewz** [handsontable/handsontable#1592]
When you have a list of autocomplete values, the scroll bar is too far on the right. Can be seen on demo example 3 (http://handsontable.com/demo/autocomplete.html).

**Comment by AMBudnik** [comment]
Please [update](https://github.com/handsontable/handsontable/releases/tag/0.14.1) and check your code now. In the [demo](https://jsfiddle.net/7qrcoz24/) we have a correct scroll position. (Change `Chassis color` for `Nissan`)

![zrzut ekranu 2015-04-10 o 14 59 33](https://cloud.githubusercontent.com/assets/10757813/7088252/93a330a4-df92-11e4-9cd0-ded171a82d7e.png)

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity.
