### ISSUE TITLE
Dropdown fails with numeric values

### ISSUE THREAD

**Issue by Garrett-** [handsontable/handsontable#1595]
If a value in the `source` array for a column with the type `'dropdown'` is a number the dropdown will fail.

Here is a example on CodePen http://codepen.io/Garrett-/pen/jFtEz

**Comment by AMBudnik** [comment]
It still occurs on 0.14.1 https://jsfiddle.net/03tz6gdw/

**Comment by jansiegel** [comment]
Should be fixed with merged @Garrett-'s changes: https://github.com/handsontable/handsontable/tree/Garrett--feature/issue-1595

**Comment by krzysztofspilka** [comment]
Released in https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
