### ISSUE TITLE
Implement drag and drop from Excel

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1608]
It should not be hard to implement a drag and drop selection from Excel to Handsontable using https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Drag_and_drop . It should be done as a plugin.

It has been done with ExtJS: http://www.vinylfox.com/datadrop-drag-grid-data-from-spreadsheet/

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
