### ISSUE TITLE
0.11beta1 new scroll problem

### ISSUE THREAD

**Issue by agershun** [handsontable/handsontable#1611]
Unfortunately, I received unexpected effect with new scroll in 0.11beta1 as you can see on the screenshot. The system shows off-screen cells and their css decoration while scrolling.

 We are actively overload Cell render function, probably this is a reason of the problem.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo. @agershun if you still have this issue, please provide a demo and we'll reopen the issue.
