### ISSUE TITLE
IE 10 Fixed Rows & Column issues

### ISSUE THREAD

**Issue by CarloDiGi** [handsontable/handsontable#1616]
http://handsontable.com/demo/fixed.html - Screenshots where taken from Page Viewed at 9:22am EST 7/15/14 a few minutes before this posting.

IE 10 is Unbearable to use with Fixed Rows and Columns.  The Performance is unusable and the rendering is not aligning correctly. Also the horizontal scroll does not keep the fixed column.

![handsontablefixedrowie10](https://cloud.githubusercontent.com/assets/1388661/3585134/feb691ae-0c22-11e4-8626-67c2be884a69.png)

 I did profile the page and found that by dragging the scroll to down to 75 took a while and even small moves were taxing on the browser.  Here are my results.

![profileofie10](https://cloud.githubusercontent.com/assets/1388661/3585198/c0564f84-0c23-11e4-9a37-0104103580e1.png)

**Comment by AMBudnik** [comment]
Hi @CarloDiGi can you confirm that it works correctly in 0.23.0?
