### ISSUE TITLE
Issues with IE11 and previuos versions

### ISSUE THREAD

**Issue by kritochin** [handsontable/handsontable#1624]
Im having several issues when using IE. Its not just previuos version, Im actually testing on IE11. I was looking at the demos on Chrome, but I finally decided to test them on IE11 and the scroll demo look like this when you scroll

![image](https://cloud.githubusercontent.com/assets/3598010/3618445/25f16172-0dea-11e4-8b0d-d915719a8347.png)

Also, this demo doesn't run in IE8

It gives me this error:

![image](https://cloud.githubusercontent.com/assets/3598010/3618456/52a7adc0-0dea-11e4-97c4-9cf3a35f1fd6.png)

Yesterday I had to download the latest version, because I find out that when I have some textboxes in a page that uses handsontable, you can not do copy paste from those textboxes.  But now with this version I'm having lots of problems. 

Please, can somebody help me? 
Thanks.

**Comment by AMBudnik** [comment]
IE11 performance isn't great but I tried to reproduce your issue in several ways and works fine. This issue has more than a year so I assume it's not a problem any more.
