### ISSUE TITLE
Add a hook to get the value to copy

### ISSUE THREAD

**Issue by zangan** [handsontable/handsontable#1626]
Hi,
I propose to add a new hook to allow the developer to set a value of a cell to be copied to the clipboard, instead the "this.get(row, prop)" value in the getCopyable function. (Handsontable.DataMap.prototype.getCopyable = function (row, prop) ).

Thanks

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
