### ISSUE TITLE
Investigate switching from SheetClip to Papa Parse

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1627]
Currently, Handsontable uses [sheetclip](https://github.com/warpech/sheetclip) to parse TSV data copied from Excel. It seems that the new library [Papa Parse](http://papaparse.com/) also does that and much more.

The file size is 10x bigger, but maybe it would fix some of the issues people had with data pasted from Excel

**Comment by warpech** [comment]
Seems that Papa Parse is still supporting only CSV, not TSV, so it is not a viable replacement for sheetclip.

Papa Parse could be perhaps a good solution for the CSV plugin in Handsontable Pro, but Pro has managed without it :) 

Closing

**Comment by mholt** [comment]
@warpech Is there any tangible difference between CSV and TSV other than delimiter? (I've used Papa Parse for tab-delimited files for years.)

**Comment by warpech** [comment]
There are many flavors of CSV, as well as of TSV, but you are right, essentially the difference should be the delimiter.

I don't remember what else did I had in mind when writing my previous comment.

If I understand correctly, you are suggesting that in case of TSV, it is proven to replace the tabs with commas and then use Papa Parse?

**Comment by mholt** [comment]
@warpech Well, I wrote Papa Parse. (It is now maintained by someone else, and yes, he is amazingly dedicated!) It lets you customize the delimiter. So it can be `\t` or `,`, doesn't matter.

**Comment by warpech** [comment]
> @warpech Well, I wrote Papa Parse.

Sorry, I overlooked that you are the author of the comment 🙈Thanks for the work and popping up here!

SheetClip, the piece of code that I wrote a while ago for Handsontable, is not meant to work with all kinds of TSV. It just needs to work with a specific quirky flavour of TSV that is produced by Excel's "Copy to clipboard" functionality.

As you can see in the file history, (https://github.com/handsontable/handsontable/commits/65dc03147e411df27e6c2699b93fdc7ade9bad67/lib/SheetClip/SheetClip.js), it is small and rather mature at this point, so I guess Handsontable will stick with it.
