### ISSUE TITLE
5 Walkontable tests not passing on Chrome/Windows

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1628]
5 Walkontable tests are not passing on Chrome/Windows:

* WalkontableScroll scroll scroll viewport to a cell on far right should make it visible on right edge.
* WalkontableScroll scroll scroll viewport to a cell on far left should make it visible on left edge.
* WalkontableScroll scroll scroll viewport to a cell on far left should make it visible on left edge (with row header).
* WalkontableTable should create as many rows as in `height` + maxOuts.
* WalkontableTable should use rowHeaders function to generate row headers.

**Comment by warpech** [comment]
I am sure this one is fixed by now and can be closed. @budnix can you confirm?

**Comment by budnix** [comment]
Yep, I confirm - all tests passed. Tested on Chrome and IE11 on Windows (VM).
