### ISSUE TITLE
[Custom borders] Support more border styles

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1633]
There should be a way to specify a double border or a dashed border, as in Excel (see screenshot):

![screenshot 2014-07-23 14 28 13](https://cloud.githubusercontent.com/assets/566463/3672814/2d875142-1265-11e4-8ac0-44457bbd2676.png)

To achieve this, I guess that WalkontableBorder needs to be changed to use SVG. For IE8 compatibility, we could use WalkontableBorder as a driver that decides whether to use WalkontableBorderDiv or WalkontableBorderSVG depending on the browser.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
