### ISSUE TITLE
Can't select cells in Merge cells demo

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1635]
When the two kinds of cells are selected (merged and single) I can't select those above them.

Steps to reproduce the problem:
- Go to http://handsontable.com/demo/merge_cells.html
- Starting from E1 hold shift and press left arrow
- Still holding shift press up arrow

![bug1](https://cloud.githubusercontent.com/assets/8048526/3675193/3c2b580c-127d-11e4-8aff-6224c15def5f.png)

**Comment by krzysztofspilka** [comment]
Merging cells needs to be refactored.

**Comment by AMBudnik** [comment]
Still in 0.24.1

**Comment by jansiegel** [comment]
Should work fine in `0.37.0`.
