### ISSUE TITLE
Shadowed Header broken when HOT within position:absolute container

### ISSUE THREAD

**Issue by RKlante** [handsontable/handsontable#1638]
Hi,

in my app using HOT i'm experiencing a problem where die Header of the Table is always rendered in one fixed place when scrolling the page.
This is new in 0.11.0-beta (was using 0.10.5 before) and only happens when i use a page-layout with a fixed-position (doesnt matter if fixed or absolute) content container and both top and bottom css attributes for it.

Here is a fiddle to display the problem: http://jsfiddle.net/7P9Lc/2/

Thanks for your help!

**Comment by AMBudnik** [comment]
For more information in this subject please check https://github.com/handsontable/handsontable/issues/1591 if this issue occurs in your code after updating - please open a new issue.
