### ISSUE TITLE
Context Menu Styling issue after multiple right clicks

### ISSUE THREAD

**Issue by cowls** [handsontable/handsontable#1642]
Seems to be some issues with the context menu styling in version 0.11.0-beta2

If you see this page:

http://handsontable.com/demo/comments.html

If you right click multiple times relatively quickly, you end up with this context menu and then it doesnt really come back until page refresh

![hotissue1](https://cloud.githubusercontent.com/assets/1536974/3699751/122c1c2e-13d8-11e4-9cb3-ef9018778b9f.jpg)

**Comment by AMBudnik** [comment]
I couldn't reproduce it. If you still have the same issue after updating to [0.13.1](https://github.com/handsontable/handsontable/releases) please write me back.
