### ISSUE TITLE
problem stretchH: 'all'

### ISSUE THREAD

**Issue by gbelmm** [handsontable/handsontable#1643]
demo in version  0.10.5
![10 b3](https://cloud.githubusercontent.com/assets/731936/3703415/92ca2ef8-1409-11e4-83e1-e6ee85d461de.png)

demo in version 0.11.0-beta3
![11 b3](https://cloud.githubusercontent.com/assets/731936/3703416/931ad06a-1409-11e4-95aa-d5751d7ad909.png)

code:

{
  data: $scope.asistencia,
  //colWidths: [ 80,140,100,100,150],
  colHeaders:$scope.headers, 
  columns: $scope.columnas,
  //fixedRowsTop: 1,
  rowHeaders:true,

  fixedColumnsLeft: 5,
   contextMenu: {
    callback: function (key, options) {
      if (key === 'PAGO') {
             var ht=$("#handasistencia").handsontable('getInstance');

            var seleccion= ht.getSelected();
            $scope.iraficha(seleccion[0],'PAGO');

      }else if (key === 'ficha') {
             var ht=$("#handasistencia").handsontable('getInstance');

            var seleccion= ht.getSelected();
            $scope.iraficha(seleccion[0],'FICHA');

      }else if (key === 'finiquitar') {
             var ht=$("#handasistencia").handsontable('getInstance');

            var seleccion= ht.getSelected();
            $scope.iraficha(seleccion[0],'FINIQUITAR');

      }else
      if (key === 'reliquidar') {
             var ht=$("#handasistencia").handsontable('getInstance');

            var seleccion= ht.getSelected();
            $scope.iraficha(seleccion[0],'RELIQUIDACION');
      }
      else
      if (key === 'trasladar') {
             var ht=$("#handasistencia").handsontable('getInstance');

            var seleccion= ht.getSelected();
            $scope.iraficha(seleccion[0],'TRASLADAR');
      }
      else
      if (key === 'timeline') {
             var ht=$("#handasistencia").handsontable('getInstance');

            var seleccion= ht.getSelected();
            $scope.iraficha(seleccion[0],'TIMELINE');
      }

    },
    items: {

      "PAGO": {name: 'Ficha Pago Trabajador',disabled: function() { var d=false;if ($scope.configuracionobra.psueldos=='false') d=true;if ($scope.configuracionobra.liquidacion=='false')  d=true; return d; }},
     "reliquidar": {name: 'Reliquidar Trabajador',disabled: function() { var d=false;if ($scope.configuracionobra.preliquidacion=='false') d=true;if ($scope.configuracionobra.reliquidacion=='false')  d=true; return d; }},
      "finiquitar": {name: 'Finiquitar Trabajador',disabled: function() { var d=false;if ($scope.configuracionobra.pfiniquito=='false') d=true;if ($scope.configuracionobra.finiquitos=='false')  d=true; return d; }},
      "trasladar": {name: 'Trasladar Trabajador',disabled: function() { var d=false;if ($scope.configuracionobra.ptraspasos=='false') d=true;if ($scope.configuracionobra.traspasos=='false')  d=true; return d; }},

      "ficha": {name: 'Ver Ficha Trabajador'},
      "timeline": {name: 'Historial Trabajador'}
    }
  },
 
  height:430,
  stretchH: 'all',
 

  currentRowClassName: 'currentRow',
  currentColClassName: 'currentCol',
     beforeChange: function (changes, source) {
    for (var i = changes.length - 1; i >= 0; i--) {
      changes[i][3]=changes[i][3].toUpperCase();
      if (changes[i][3] === "A"  || changes[i][3] === "L" || changes[i][3] === "T" || changes[i][3] === "X" || changes[i][3] === "a"  || changes[i][3] === "l" || changes[i][3] === "t" || changes[i][3] === "x") {
        changes.splice(i, 1); //gently don't accept the word "foo" (remove the change at index i)
      }

    }
  },
    afterChange: function(changes, source) {
            if (source == "loadData" ||  $scope.editando==true) return;
            var renderChanges = [];

        var ht=$("#handasistencia").handsontable('getInstance');
          var seleccion= ht.getSelected();
       $scope.editando=true;
        changes2=[];
       for(var i = 0; i < changes.length; i++){
           if (changes[i]!==null){
           var selecionado=$scope.asistencia[changes[i][0]];
           if (selecionado!==undefined)
           { changes[i][4]=selecionado.rut;

           }

       }

           }

        console.log(changes2);
        $http({ method: 'POST', url: Ruta+'sueldos/asistencia_grabar/'+$scope.mes+'/'+$scope.obra,data: { data:changes   }}).
            success(function(data, status, headers, config) {
                $scope.editando=false;
            })

                var i=0;

        }  ,
  cells: function (row, col, prop) {

    var cellProperties = {};
    var data;
    var dd=$("#handasistencia").handsontable('getData')[row][prop];
    if (dd=='F' || dd=='f' || dd=='P'  || dd=='PP'  || dd=='p'  || dd=='pp'){

    }
   if (dd === 'L' ||dd === 'A' || dd === 'T' || dd === 'X' ||dd === 'l' ||dd === 'a' || dd === 'r' || dd === 'x')  {
        cellProperties.readOnly = true;

      }

    if (row === 0) {

    }
    if ($scope.configuracionobra.pasistencia=='false')
      cellProperties.readOnly=true;

     if ($scope.configuracionobra.asistencia=='false')
      cellProperties.readOnly=true;

    if (col<$scope.diasasistencia  ){
     cellProperties.readOnly=true;
    }
    return cellProperties;
  }
}

**Comment by AMBudnik** [comment]
Hi, from 0.12.6 release everything should work fine. If you would have any other questions feel free to open another issue.
