### ISSUE TITLE
multiSelect does not work as expected

### ISSUE THREAD

**Issue by exilef** [handsontable/handsontable#1647]
When multiSelect is true, the following workflow does not work as expected: 

Select a cell (mouse)
Press and hold Ctrl
Select further cells or range to make non-contiguous selection of cells (mouse)

See demo http://handsontable.com/demo/options.html

**Comment by AMBudnik** [comment]
To be updated to this subject, please track changes to https://github.com/handsontable/handsontable/issues/2119
