### ISSUE TITLE
How to move focus out of the table

### ISSUE THREAD

**Issue by Dominik76** [handsontable/handsontable#1652]
Hi,
is there a way to set focus out of the table when press tab key on the last cell ?

I mean, if I enter into the table selecting a cell I would to move out of the table with keyboard (without mouse click)

thanks in advance
Dominik

**Comment by AMBudnik** [comment]
For issues not related to problems with HOT code, please create a [SO topic](https://stackoverflow.com/questions/tagged/handsontable)
