### ISSUE TITLE
Rows hide after resizing them over the colHeader

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1656]
When I drag the resize handle over or above the header it looks like getting negative height - it hides under the header.

This issue appears in the `column resize` demo: http://handsontable.com/demo/column_resize.html
- Step 1 (drag&drop)
  ![screenclip 1](https://cloud.githubusercontent.com/assets/8048526/3761459/9271b806-188a-11e4-8ed9-76c59c8f6e48.jpg)
- Step 2 (the result)
  ![screenclip 2](https://cloud.githubusercontent.com/assets/8048526/3761451/6e302cca-188a-11e4-8ab1-640e4a4d5205.png)

**Comment by AMBudnik** [comment]
Checked this with the latest version and row aren't hiding any more but the handle of the row can be triggered far out of the grid.

![mo_j_](https://cloud.githubusercontent.com/assets/10757813/7472179/f4e30c08-f32f-11e4-9aa1-3340e4307a24.gif)

**Comment by AMBudnik** [comment]
confirmed with 0.23.0 http://jsfiddle.net/Lsjexarj/

**Comment by AMBudnik** [comment]
In 0.31.0 it works like that

![example](https://cloud.githubusercontent.com/assets/10757813/23356512/6d358900-fcda-11e6-8373-982eb6baea45.gif)

I guess that we can close this issue.
