### ISSUE TITLE
Remove "prop"

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1657]
Currently, Handsontable supports two systems of coordinates: `row, col` and `row, prop`. To many people the distinction is not clear and there is no obvious benefit from having two competing systems supported in the API. Let's remove "prop" (but maintain argument compatibility with cell renderers and editors)

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
