### ISSUE TITLE
Handsontable integration in ADf application

### ISSUE THREAD

**Issue by bsJagadeesh** [handsontable/handsontable#1659]
Hi Team,
I am very much impressed with handsontable functionality.
I tried to integrate this in Oracle ADF application.This functionality is not working with .jspx file.  The data is not rendering in .jspx file. 
But the same functionality works fine in .jsp file.

Please Suggest how to integrate handsontable functionality in .jspx file/ ADF application.

Best Regards,
Jagadeesh Badri

**Comment by AMBudnik** [comment]
For integration issues that are not related with ones that we are providing please open a new issue on [stackoverflow](https://stackoverflow.com/search?q=handsontable) with a `handsontable` tag. We try to keep github a place to report bugs.
