### ISSUE TITLE
Adding extra columns on paste

### ISSUE THREAD

**Issue by gunn** [handsontable/handsontable#166]
If you set `minSpareCols` to 1 or above pasting data does add new columns nicely.
But, I'd like to have this without always having an empty column taking up space.

Perhaps differentiate between `minSpareCols: 0` and `minSpareCols: false`?

**Comment by AMBudnik** [comment]
Please try new version of HOT, like in [this demo](http://handsontable.com/) it smoothly pastes columns (creating new column) without a `minSpareCols`.
