### ISSUE TITLE
Can't set "mergeCells" using updateSettings()

### ISSUE THREAD

**Issue by jarben** [handsontable/handsontable#1665]
throws: Uncaught TypeError: Cannot read property 'mergedCellInfoCollection' of undefined 

demo: http://jsfiddle.net/jarben/37hJn/

**Comment by chetandoke** [comment]
Same issue Cannot read property 'mergedCellInfoCollection' of undefined looking forward tto solution.

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/1788

**Comment by csdpuneteam1** [comment]
Guys, I think I have fixed this.

Just before calling updateSettings of the HOT instance, update it's mergeCells attribute , with the new instance of Handsontable.MergeCells object by passing updated mergeCells array as an attribute.

```
hotOptions.mergeCells = [{row: 0, col: 0, rowspan: 2, colspan: 3} ];
hot.mergeCells = new Handsontable.MergeCells(hotOptions.mergeCells);
hot.updateSettings(hotOptions);
```
See it working here: http://jsfiddle.net/gncb55jp/3/
