### ISSUE TITLE
Columns not adding when pasting data

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#1668]
When pasting data into the table and the data doesn't fit (it requires more columns), additional columns should be created.
At the moment only rows are being added in an analogous situation (when the clipboard data requires more rows than available).

**Comment by lil25** [comment]
Hello

I've found issue. Columns are not added on pasting if "manualColumnMove" is true.
Here is demo http://jsfiddle.net/5u5vczcg/5/ try to set "manualColumnMove" to true and paste table data columns is not added.
