### ISSUE TITLE
Disable rendering

### ISSUE THREAD

**Issue by ferdinandbayard** [handsontable/handsontable#1672]
Hi to every one. 

I'm using Bootstrap nav tabs to get several worksheets on the same page, like a workbook in Excel. As I use a custom renderer, I discovered the renderer is always triggered, even for the non-focussed worksheets. Is there a way to disable rendering that to get better performance ? An alternate tool of Bootstrap nav tabs ? 

Thx for answering. 

            <ul class="nav nav-tabs" id="myTab">
              <li class="active"><a href="#params" data-toggle="tab">Parameters</a></li>
                
              <li><a href="#materials" data-toggle="tab">Materials</a></li>
            </ul>
            
            <div class="tab-content">

              <div class="tab-pane active" id="params">
                      <div class="handsontable" style="" id="paramsTab"></div>        
              </div>
              <div class="tab-pane" id="materials">
                      <div class="handsontable" style="" id="materialsTab"></div>        
              </div>
              </div>
            </div>

**Comment by armensg** [comment]
This question is very useful and I would love to hear some options. Thanks

**Comment by AMBudnik** [comment]
Hi @ferdinandbayard 
can you create a JSFiddle where we will be able to check how it renderer behaves?

**Comment by AMBudnik** [comment]
I'm closing this issue in lack of a reply for 2 weeks but feel free to leave a comment or share a demo if needed.
