### ISSUE TITLE
jquery draggable and ht_clone_top

### ISSUE THREAD

**Issue by aardeleanx** [handsontable/handsontable#1673]
I have a draggable div in which I render the handsontable grid. When I drag the container div to another point on screen, the handsontable div with class ht_clone_top does not follow the grid. Is there a way to correct this behavior or is this a bug? I use jQuery UI - v1.10.4 & jQuery v1.11.0
![draggable div with grid inside](https://cloud.githubusercontent.com/assets/8387015/3845560/f2c9fa00-1e53-11e4-86d9-729ecdbdc7c1.png)

**Comment by AMBudnik** [comment]
By the help of niente00 from [SO](http://stackoverflow.com/questions/9334084/moveable-draggable-div) - [here's](https://jsfiddle.net/LeLtja05/) the example of a HOT in draggable div.

**Comment by AMBudnik** [comment]
If there's no other questions or suggestions, I assume I can close this issue.
