### ISSUE TITLE
Column indexing

### ISSUE THREAD

**Issue by survik1** [handsontable/handsontable#1676]
Moving column wont update column index which fail to ajax save. Saving with persistentState on/off wont matter.

**Comment by AMBudnik** [comment]
Hi @survik1 
I guess this issue no longer occurs.
I made a demo:http://jsfiddle.net/4g7skduw/1/ when I'm logging whole data after column was moved. I get the expected results. Could you check it please?

Thanks in advance!

**Comment by survik1** [comment]
Hello,

that example you have posted is not even working for me (tested in the 
newest versions of FireFox and Chrome). I have to check that legacy code 
but we have made a workaround to make that code working.

Tomas Neumaier

Dne 21. 3. 2016 v 14:03 Aleksandra Budnik napsal(a):

**Comment by AMBudnik** [comment]
@survik1 
Could you create a demo? It's hard to advice without seeing the code.

**Comment by AMBudnik** [comment]
Issue will be reopened with a demo/reply for the Author.
