### ISSUE TITLE
Remove Row, Undo, afterChange change array should be an array of array but is just an array.

### ISSUE THREAD

**Issue by mvagnoni** [handsontable/handsontable#1678]
Usually the afterChange(change, source) has the change param as an array of array[4]'s.  However, when undoing a RemoveRow (deletion), the change array is instead just an array[4].  So I have to write a custom handler for this right now, but it should be [[row,col,null,object]] instead of [row,col,null,object].

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
