### ISSUE TITLE
Putting HoT in a dialog

### ISSUE THREAD

**Issue by davidt50** [handsontable/handsontable#1679]
Have been trying to add a jquery dialog filled with the configuration of the main table.  I can get the table to show up in the dialog but the context menu was showing up under the dialog.  I changed the z-index on the context Menu to default 10000 ( jquery is defaulted to 10000 ) and it appears in the correct spot now.  An has no effect it seems on the original table 

.htContextMenu {
  display: none;
  position: absolute;
  z-index:10000;
}

**Comment by AMBudnik** [comment]
Please provide a [JSFiddle](https://jsfiddle.net/api/post/library/pure/) in you still face this issue.

**Comment by AMBudnik** [comment]
Please follow https://github.com/handsontable/handsontable/issues/2324 issue for more information. If you would prepare a demo - please paste it also at #2324
