### ISSUE TITLE
Multiline header (with <br>) breaks top-left cell's height and row header vs. row alignment

### ISSUE THREAD

**Issue by pavkriz** [handsontable/handsontable#1681]
Handsontable is not able to render multi-line header (containing `<br>`) well. The top-left cell (the empty one) has small height (not corresponding with header's height) and so all row headers at not properly aligned with the (data) rows. See jsfiddle:
http://jsfiddle.net/pavkriz/re9yxmvw/
![image](https://cloud.githubusercontent.com/assets/6539456/3869999/95ff8a38-20b5-11e4-8f85-4c9001ead4e1.png)

When fixed columns contain the multi-line header cell (fixedColumnsLeft is set 1 in the jsfiddle example), everything works well: 
http://jsfiddle.net/pavkriz/99fh4Lu4/

**Comment by AMBudnik** [comment]
This issue should be solved. Please recheck the demos.

**Comment by AMBudnik** [comment]
[demo](https://jsfiddle.net/re9yxmvw/2/) updated to 0.14.1
