### ISSUE TITLE
table clone header shift when dialog drag

### ISSUE THREAD

**Issue by kyanite** [handsontable/handsontable#1685]
If put handsontable in jqueryui Dialog Widget, when drag the dialog, the clone header will be shift. I use the 0.11.0-beta3

**Comment by AMBudnik** [comment]
Hi @kyanite do you still face the same issue with [0.13.1](https://github.com/handsontable/handsontable/releases/tag/0.13.1)?

**Comment by AMBudnik** [comment]
issus closed in lack of author's reply for two months.
