### ISSUE TITLE
Cannot toggle checkboxes from a long multi-select using "space" when some of the checkboxes are not visible on screen due to a scrollbar.

### ISSUE THREAD

**Issue by gentr1** [handsontable/handsontable#1686]
Cannot do a multi-select using "space" when some of the checkboxes are not visible on screen inside long list scrollbar.
The system gives me a : "Uncaught TypeError: Cannot read property 'querySelectorAll' of null" and only change the status of check boxes visible on screen if only the selector cell is visible as well. If I scroll down to the bottom of the list of cells selected and I press space to toggle checkboxes, I get "Uncaught TypeError: Cannot read property 'querySelectorAll' of null" and nothing is toogled.
![pb1](https://cloud.githubusercontent.com/assets/2472051/3905289/af05dd7a-22e5-11e4-978b-cffbedd51d1b.png)

**Comment by AMBudnik** [comment]
Please provide a [demo](https://jsfiddle.net/api/post/library/pure/) of your code.

**Comment by gentr1** [comment]
Hi,

My code was just ordinary vanilla long list of checkboxes:
var $container8 = $("#tab8id");
$container8.handsontable({
  data: [],
  width: 1080,
  height:250,
  dataSchema: {name: null, rule: null, select: null},
  colWidths: [200, 800,40],
  startRows: 1,
  startCols: 3,
  columnSorting: false,
  colHeaders: ['Transition name','Rule','y'],
 
  currentRowClassName: 'currentRow',
  columns: [
    {data: "name"},//,readOnly: true
	{data: "rule"},
    {data: "select",type: "checkbox"}
  ],
  
  minSpareRows: 1
});

I changed the handsontable code to get read of the problem: 
if the handsontable js , at line 4586, I added a statement to check if the cell value return by the TD exists, if not, I just switch the boolean value of the cell:
if (cell){
	cell = instance.getCell(row, col);
	cellProperties = instance.getCellMeta(row, col);
	checkbox = cell.querySelectorAll('input[type=checkbox]');
	if(checkbox.length > 0 && !cellProperties.readOnly){
		if(!event.isImmediatePropagationStopped()){
			event.stopImmediatePropagation();
			event.preventDefault();
		}
		for(var i = 0, len = checkbox.length; i < len; i++){
			checkbox[i].checked = !checkbox[i].checked;
			$(checkbox[i]).trigger('change');
		}
	}
}
else{
	var status=instance.getDataAtCell (row, col);
	if (status == true){
		instance.setDataAtCell (row, col,false);
	}
	else{
		instance.setDataAtCell (row, col,true);
	}
}

**Comment by AMBudnik** [comment]
Hi, if you still face the same issue please provide a demo using [jsFiddle](https://jsfiddle.net/api/post/library/pure/) it would be easier to help working on full code

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply.

**Comment by pe4k** [comment]
Hi, let me ask for reopen this issue. Selecting all rows by checkbox column is working, but if you want to switch checkboxes value by space, it throws error in console. Look at the demo. If you are using less rows, ie. 15, it is working, but with many rows it is not.
http://jsfiddle.net/hbr6bqt5/

**Comment by AMBudnik** [comment]
Hi @pe4k here we have a similar issue https://github.com/handsontable/handsontable/issues/3554 if there's something that we're missing please share your comment at https://github.com/handsontable/handsontable/issues/3554

**Comment by pe4k** [comment]
Hi, thank you it looks that `renderAllRows: true` works like a charm

**Comment by AMBudnik** [comment]
great, thanks for an update @pe4k
