### ISSUE TITLE
Close Editor Event?

### ISSUE THREAD

**Issue by anton164** [handsontable/handsontable#1688]
Hi,

I'm using handsontable in a web-app where you can have two windows open and changes in either window should be updated real-time in the other.

Now for adding/deleting rows, it gets a bit problematic. If user A adds a new row, while user B is editing an existing row, if we add it instantly user B's editing is interrupted. To handle this I thought we could use the 'afterChange' hook, and defer the insertion/deletion of a row to when user B is done editing, however afterChange isn't triggered when you hit 'Esc'. 

I've checked out other hooks and there doesn't seem to be anything for when the editor is closed, so would the best approach be to extend the close method for all the cell editors and have it trigger a custom hook?

Any help is appreciated, thanks for developing this great plugin!
-Anton

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
