### ISSUE TITLE
need to capture beforeRowMove event

### ISSUE THREAD

**Issue by mapinales** [handsontable/handsontable#1689]
There is currently no beforeRowMove or beforeColumnMove event.  These events should be capturable in case the moving is condition based.  I'm trying to set up my sheet where the first 3 rows should not be movable.  Also, fixed rows and columns are currently movable and can have columns and rows moved in to them.  I thought that by fixing the first 3 rows I would be able to solve my issue, but that is not the case.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
