### ISSUE TITLE
Add New Sheet

### ISSUE THREAD

**Issue by khanhnam99** [handsontable/handsontable#1690]
how add tab multi sheet,multi tab spreadsheet ,this is function new

**Comment by AMBudnik** [comment]
I think this [demo](http://handsontable.com/demo/pagination.html) could help. If this isn't what you were looking for, please reply.

**Comment by gayancliyanage** [comment]
@khanhnam99 I assume you have mention something related spread sheets multiple instances in a single page with can be toggle like tabs but performance really low at moment with hands on table. Processing multiple sheet with 1000*26 takes considerable time to render with data.

**Comment by methnen** [comment]
@AMBudnik Just to be clear as someone who was looking for the info on the same thing. A link to a pagination demo does not help with how to add a new sheet at all. Simply stating that you'll need to build your own interface for this sort of thing is way more helpful.

**Comment by AMBudnik** [comment]
That is correct @methnen 
This is a solid demo that is not made to be extended as it does not load data page by page - it only serves parts of data.
When it comes to an original case of this issue you can use Bootstrap tabs to create something like Excel's sheets (demo: http://jsfiddle.net/jh37jd08/)

**Comment by khanhnam99** [comment]
thanks

Please call me :0169 7540 418  Gặp Nam
khanhnam99@gmail.com

2016-11-17 16:51 GMT+07:00 Aleksandra Budnik <notifications@github.com>:

**Comment by khanhnam99** [comment]
which way , create new tab sheet by ajax , button save a sheet by ajax ?
![capture](https://cloud.githubusercontent.com/assets/575720/20694422/9ea20194-b617-11e6-8667-50194a86e960.PNG)

please help me!

thanks

**Comment by AMBudnik** [comment]
hi @khanhnam99 we do not have any examples that interact with a database or any other back-end operations.

**Comment by free1227** [comment]
@AMBudnik  hi,I build a footbar as to imitate.Different sheets use the same handsontabel.When i change sheet, i will save the current data first in window,like
`changeSheet : function(index){
	var current = footbarButton.find(".sheetBar .current").index();
	if(current != index && current != -1){
		footbar.core.removeCurrent();
		footbar.core.setCurrent(footbarButton.find(".sheetBar .sheet").eq(index));
		footbar.core.saveData(footbar.core.getData(),current);
		footbar.core.showData(index);
	}
}`

when i show data, i write a function like
`showData : function(index){
	if(window.sheetLib[index]){
		footbar.core.setData(window.sheetLib[index]);
		//return window.sheetLib[index];
	}else{
		footbar.core.setData(footbar.core.genNewSheet());
		//return newSheet;
	}
}
setData : function(data){
	return footbar.handsontable.loadData(data);
}`

But when i use loadData, I can't restore the style of the cell.
Should i store the style in a variable?
Or use some other functions?
