### ISSUE TITLE
Scrolling & Resizing issue with internet explorer

### ISSUE THREAD

**Issue by sumit2chauhan** [handsontable/handsontable#1691]
I am facing scrolling issue with internet explorer
 The header under the overlay header is visible when i scroll up in internet explorer

Also,
when i resize the page in internet explorer, the overlay headers are completely out of sync

![dsc_2164](https://cloud.githubusercontent.com/assets/8424253/3916693/2702350a-237f-11e4-83b0-9996120fbea6.jpg)
![dsc_2161](https://cloud.githubusercontent.com/assets/8424253/3916692/2701c2c8-237f-11e4-85a3-28c1f2fdbb89.jpg)

**Comment by AMBudnik** [comment]
As far as I'm realising this is the issue we had some time ago it should work correct right now. Please update to 0.13.1 and give as a feedback of your observations. Till this happen issue will say closed.
