### ISSUE TITLE
Changing columnHeader

### ISSUE THREAD

**Issue by myisis** [handsontable/handsontable#1698]
Is it possible to change/update the column header once the table has been created? I've tried to use `$ht.handsontable('loadData', getData())` but this doesn't refresh the column headers. Same goes for the `rowHeader`...

**Comment by okahara** [comment]
I'm using updatesettings to change the column headers but then running my own validation that checks the column headers to the data in the cells of that column.
example: if column header is "xxxxx Date" than cell value should be "xx/xx/xxx".

I was able to change the headers before and still am but now each cell's prop does not update with it and therefore I can no longer run my validation.  Is there a reason why the prop is not changing now?

**Comment by clarissa123** [comment]
When I use updatesettings, why is there an uncaught error: the "runhooks" method cannot be called because this handsontable instance has been destroyed At Core.eval [as runHooks] ??

**Comment by AMBudnik** [comment]
Hey @clarissa123 please provide a code same and a project description - I'll be waiting on support@handsontable.com
