### ISSUE TITLE
Using Handsontable.Search.DEFAULT_QUERY_METHOD fails returning "TypeError: value is null" if you have cells with null data content

### ISSUE THREAD

**Issue by xiul** [handsontable/handsontable#1703]
Problem is located at
  Handsontable.Search.DEFAULT_QUERY_METHOD = function (query, value) {
...      return value.toString() .toLowerCase() .indexOf(query.toLowerCase()) != - 1;
    };

If content of the variable value is null then method fails with TypeError: value is null because cell is null, need to check if value variable content is null before calling toString method.

**Comment by AMBudnik** [comment]
Please update to 0.15.0-beta3 and leave us feedback if you still face this issue. Till it happens issue will stay closed.
