### ISSUE TITLE
Autocomplete cell type

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1706]
The autocomplete cell type does not work smooth. The layout is a bit messy in chrome when it contains many items. Why does it rely on twitter bootstrap typeahead (which is no longer active) and not just typeahead.js? The documentation says that the property 'options' overrides the defaults, but "options: {items: 3}" does seem to affect anything. The autocomplete cell type is a great option, but it could be even more useful if it was possible to store both an id and a visible cell value.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo and no ability to reproduce this issue.
