### ISSUE TITLE
Handsontable dropdown column marks space terminated entires as error

### ISSUE THREAD

**Issue by mohan8990** [handsontable/handsontable#1709]
Hi,

A sample handsontable column setting,

{
    data: 'department',
    type: 'dropdown',
    source: departmentNames
},

Assume my department names is an array

var deptNames = ('d1', 'd2 ', 'd3') // d2 has space as the last character

The department column really shows d2 as one of the choices, but when I select d2, it is marked red and invalid. 
Is this expected ?

**Comment by AMBudnik** [comment]
Thank you for that report - let us reconsider that subject.

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topic and uloading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Isuee will be reopene with first update.

**Comment by AMBudnik** [comment]
Whitespaces are trimmed by default. 

![image](https://user-images.githubusercontent.com/10757813/118809971-98f45580-b8ab-11eb-8ff0-0bc51bb8d0f1.png)

But when we use `trimWhitespace: false` within the table settings the value `d2 ` is no longer invalid. Updated demo https://jsfiddle.net/handsoncode/wu4g1fze/1/
