### ISSUE TITLE
"getSourceDataAtRow" after sorting doesnt work 0.11.0-beta3

### ISSUE THREAD

**Issue by thecaddy** [handsontable/handsontable#1710]
Hi guys, appreciate the great work you are doing on this project and love the progress being made in performance.  

I've found the new function getSourceDataAtRow to be extremely useful for tying various components to the table.  I recently came across that it does not check for the sort value and will return to you the original data in that row.

My solution was I exposed the sortIndex which was already generating the mapping for us as seen in the code below:

```
function HandsontableColumnSorting() {
  var plugin = this;
  this.init = function (source) {
...
this.sortIndex = function(){
    return this.sortIndex;
  };
```

Then check for its existence when getSourceDataAtRow is called and adjust the row according to the mapping.

```
this.getSourceDataAtRow = function (row) {
    if(this.sortIndex && this.sortIndex.length > 0){
      row = this.sortIndex[row][0];
    }
    return priv.settings.data[row];
};
```

Keep up the awesome work.

**Comment by angusdev** [comment]
Workaround:
row = instance.runHooksAndReturn('modifyRow', row);

**Comment by AMBudnik** [comment]
Hi `getSourceDataAtRow' returns source index. To get data after sorting use 'getDataAtRow` instead.

**Comment by marcossousa** [comment]
AMBudnik,

`getDataAtRow` returns always an array, if your row is an object, you will never get this object calling this method. I think this method should call modifyRow instead.

**Comment by thecaddy** [comment]
It has been a year and this code mod still exists in my branch on 0.19,  any chance to get "getSourceDataAtRow" to work as expected?

**Comment by morungos** [comment]
Hmmm. I'm caught on this and `runHooksAndReturn` doesn't actually exist, so it's not clear there even is a workaround for it. Which is something of a blocker.

**Comment by morungos** [comment]
Candidate fix appears to be a more brutal piece of logic:

```
      for entry, i in handsonTable.sortIndex
        if entry[0] == rowIndex
          rowIndex = i
          break
```

**Comment by jefferydutra** [comment]
my workaround is this
   ```
 getSourceData(handsOnTable, logicalIndex) {
        const physicalIndex = handsOnTable.sortOrder === undefined
            ? logicalIndex
            : handsOnTable.sortIndex[logicalIndex][0];

        return handsOnTable.getSourceDataAtRow(physicalIndex) || {};
    },
```

**Comment by AMBudnik** [comment]
Hi guys,
Can you check this please? http://jsfiddle.net/3odrwu2n/
I've updates the example to 0.26.0 and seems that it's working fine.

**Comment by tyschroed** [comment]
AMBudnik,

Your example doesn't have sorting turned on. Try this example: http://jsfiddle.net/zstpwto7/

getDataAtSource returns the data object for the source data at the selected row index (as it should) the issue is there is no way to get the row *object* for the logical row if sorting as re-ordered the source data - all you can get is the array of values.

**Comment by AMBudnik** [comment]
you're right @tyschroed I lost the `columnSorting`
The `getSourceDataAtRow` gives us always the object and the source (stays the same after sorting) and the `getDataAtRow` gives us changed data (after sorting) but it's not an object - it's an array.

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/3564

**Comment by seharri92** [comment]
I have been struggling with this for a while, and I think I found a solution. hot.sortIndex returns an array (in current sorted order) with the current sorted value AND the original row. So you can do something like hot.getSourceDataAtRow( hot.sortIndex[indexedRow][0] ) where indexedRow is the row that is being accessed/changed.

**Comment by swistach** [comment]
@tyschroed,
The `afterChange` hook contains visual cell coords. If you want to get sourceData, you have to translate visual indexes into logical indexes.
Here is an example: https://jsfiddle.net/s5mjdkqj/

@thecaddy, @mvagnoni, @angusdev, @marcossousa, @morungos, @jefferydutra, @seharri92,
You can use the same way to get sourceData: https://jsfiddle.net/dk7LehL5/

Unfortunately, `columnSorting` and `manualRowMove` should not to be used at the same time. There is bug with order of the logical indexes.
