### ISSUE TITLE
how insert math symbols in handsontable ?

### ISSUE THREAD

**Issue by khanhnam99** [handsontable/handsontable#1712]
how insert math symbols in handsontable ?i would like,please help me!

**Comment by a-x-** [comment]
btw, what about https://github.com/gurubenka/handsontable-excel
> This plugins enables Excel-like formula evaluation for Handsontable

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply.

**Comment by khanhnam99** [comment]
thank you very much!

Please call me :0169 7540 418  Gặp Nam
khanhnam99@gmail.com

2015-04-24 18:33 GMT+07:00 Aleksandra Budnik <notifications@github.com>:
