### ISSUE TITLE
ht_clone_top out of position when loading the document

### ISSUE THREAD

**Issue by xnsmark** [handsontable/handsontable#1713]
Hello.

When I'm trying to display a table, the header is out of position and duplicated.

![captura](https://cloud.githubusercontent.com/assets/4191026/4027399/15df5822-2c2e-11e4-9777-04269e2c1b19.JPG)

When I scroll up or down, or just click on the thead element, the ht_clone_top just put on top of the thead element, but it's not correctly aligned. Also you can still see the thead element behind the ht_clone_top.

![captura2](https://cloud.githubusercontent.com/assets/4191026/4027456/fad8b806-2c2e-11e4-9fb6-d0b5c2ff8622.JPG)

Here is the code of the thead:
```
<thead>
    <tr>
        <th class="">
            <div class="relative">
                <span class="colHeader">Descripción</span>
            </div>
        </th>
        <th class="fill">
    </tr>
</thead>

```

And here the code of the ht_clone_top:
```
<div class="ht_clone_top handsontable" style="position: fixed; overflow: hidden; top: 222px; left: 75px; width: 859px; height: 30px;">
    <div class="wtHolder" style="position: relative;">
        <div class="wtHider" style="position: relative;">
            <div class="wtSpreader" style="position: relative; width: auto; height: auto;">
                <table class="htCore">
                    <colgroup>
                    <thead>
                        <tr>
                            <th class="">
                                <div class="relative">
                                    <span class="colHeader">Descripción</span>
                                </div>
                            </th>
                            <th class="fill">
                                <div class="relative">
                                    <span class="colHeader">País</span>
                                </div>
                            </th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="htBorders">
            </div>
        </div>
    </div>

```

This problem started when I changed to the version 0.11.0-beta3. In the version 0.10.0 it was working fine.

Could someone tell me if there is any bug in the new version or I just have something wrong on my code?

Many thanks in advance.

**Comment by gstanislav** [comment]
I'm still experiencing this problem.

**Comment by krzysztofspilka** [comment]
@gstanislav could you create a JSFiddle for this case so we could see where the problem lies?

**Comment by AMBudnik** [comment]
Hi guys, there was no demo provided for a month so I'll close this issue. Please update to 0.14.1 and let us know if you still experience this issue.

**Comment by AMBudnik** [comment]
Hi @SaguruHakuba Can you send us a demo where the issue can be tested?
