### ISSUE TITLE
Deleting/Inserting rows shifts the data but not the attributes of the same.

### ISSUE THREAD

**Issue by sumitgupta99** [handsontable/handsontable#1715]
Please check below link:
http://jsfiddle.net/3szyqhb9/

If you try adding/deleting row by right clicking on say the second row, you can see two rows getting colored, which was initially only one.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
