### ISSUE TITLE
break statement in switch not reached

### ISSUE THREAD

**Issue by klemens-kunz** [handsontable/handsontable#1717]
There seems to be a bug in the switch statements that handle keydown events for select All, copy, cut and paste: the ```break``` statement in the respective ```case``` is never reached and the ```switch``` simply continues with the next ```case```. In my case this causes my CustomEditor that's using the [chosen plugin](http://harvesthq.github.io/chosen/) to close the editor if I put in an "a" into the chosen input field, because it interprets the key stroke as ARROW_DOWN.

Specifically, this code block (line 3373):

```javascript
case keyCodes.A:
  if (ctrlDown) {
    selection.selectAll(); //select all cells

    event.preventDefault();
    event.stopPropagation();
    break;
  }
```

needs to be replaced with this:

```javascript
case keyCodes.A:
  if (ctrlDown) {
    selection.selectAll(); //select all cells

    event.preventDefault();
    event.stopPropagation();
  }
  break;
```

I'm using 0.10.5, but the code is the same in 0.11.0-beta3. Similar code needs to be adapted on line 5297:

```javascript
case keyCodes.A:
case keyCodes.X:
case keyCodes.C:
case keyCodes.V:
  if(ctrlDown){
    event.stopImmediatePropagation(); //CTRL+A, CTRL+C, CTRL+V, CTRL+X should only work locally when cell is edited (not in table context)
    break;
  }
```

to

```javascript
case keyCodes.A:
case keyCodes.X:
case keyCodes.C:
case keyCodes.V:
  if(ctrlDown){
    event.stopImmediatePropagation(); //CTRL+A, CTRL+C, CTRL+V, CTRL+X should only work locally when cell is edited (not in table context)
  }
  break;
```

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
