### ISSUE TITLE
Fixed headers ht_clone_* do not move properly

### ISSUE THREAD

**Issue by DylanMoz** [handsontable/handsontable#1718]
I'm using handsontable inside widgets that can be dragged to different positions. When I do so the fixed duplicate headers do not move with the table as shown in the two pictures. I am using Handsontable 0.11.0-beta3, is there any workaround to fix this problem?
![hot1](https://cloud.githubusercontent.com/assets/4955191/4064104/2445b0f0-2e0e-11e4-9361-41ff93b43adc.png)
![hot2](https://cloud.githubusercontent.com/assets/4955191/4064107/26c2f482-2e0e-11e4-8a53-94e658c15e99.png)

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/1713
