### ISSUE TITLE
Cell alignment as an option

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1720]
Why is it not just an option to set the horizontal alignment in a column?

Right now I'm using a custom renderer to set className in the column, but I cannot reuse a renderer with different horizontal alignment in different columns.

Couldn't it be an option as

columns: [
    {
        type: 'checkbox',
        horizontalAlignment: 'center',
    },
]

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by Codearella** [comment]
Was this bug ever solved? It's not obvious where to find the info in the wiki section.

**Comment by AMBudnik** [comment]
@Codearella it's a feature request, it wasn't prepared yet.

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
