### ISSUE TITLE
Merge Cells not working properly

### ISSUE THREAD

**Issue by Mazzzy** [handsontable/handsontable#1722]
The merge cells functionality is not working properly, in below scenario:
1. Select two cells in a particular column, and merge them.
    It works fine and merge cells
2. Now select adjacent cells to merged one and apply "Merge Cells". 

Now issue occurs, it merges the selected collection but the previous merged ones get shifted to next adjacent column

**Comment by AMBudnik** [comment]
Confirmed with v0.16.1 with [this demo](https://jsfiddle.net/ruwr0b27/1/). Merge like @Mazzzy descibed in 2nd step.

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1

**Comment by jansiegel** [comment]
Should work fine in `0.37.0`.
