### ISSUE TITLE
FYI, TypeScript definitions available

### ISSUE THREAD

**Issue by IntelOrca** [handsontable/handsontable#1723]
I have created TypeScript definitions for jquery-handsontable, available here:
https://github.com/borisyankov/DefinitelyTyped/tree/master/jquery-handsontable

**Comment by AMBudnik** [comment]
Thank you very much for your support. Issue will stay closed till a question or a suggestion will appear.

**Comment by ichpuchtli** [comment]
@AMBudnik Would you consider maintaining a type definition. The definition above hasn't been updated in two years.
