### ISSUE TITLE
JSON scheme changes from particular line

### ISSUE THREAD

**Issue by TheCrafterXD** [handsontable/handsontable#1724]
When I add a lot of lines to my table at some point it just "forgets" the lines after saving. I've looked in the JSON String and noticed, that normally it is set up like this: data[ROW_ID][]
But from line 167 it changed to data[ROW_ID][COLUMN_ID]

For that reason my PHP Code doesn't perform it. It works like:
foreach($_POST['data'] as $datastring) {

I have a lot of Tables in this project and the Position of the "Limit" varies but is kinda random set to the table...
Heres a Screenshot of the JSON:

![capturfiles_9](https://cloud.githubusercontent.com/assets/8619563/4112083/0f5508e2-321b-11e4-88e3-3e726ca341a6.jpg)

**Comment by AMBudnik** [comment]
Hi @TheCrafterXD Github board is made to report bug related to pure Handsontable. I can recommend to check for answers at stackoverflow: https://stackoverflow.com/search?q=handsontable
