### ISSUE TITLE
horizontal scrollbar doesn't display comments inside div properly

### ISSUE THREAD

**Issue by tname** [handsontable/handsontable#1725]
In a table where there are many columns (i.e. 50) the width of the table can be very large (3000 px)
I would like to put a scrollbar around the table to make for a nicer interface for user interface (i.e. 1500 px), however when one hovers over a comment inside the scrollbar, the corrdinates in which the comment is displayed is based on the browser scrollbar (line 2621 Handsontable.Dom.offset = function (elem) {...}) which only shows the comment popup on mouseover as long as the .htComment fits in the window size. It does not account for the width of the inner scrollbar (not browser scrollbar) so once I scroll to the right on say column 30 for example the tooltip is way to the right off the screen. I need for it to be displayed inside the scrollbar div so figure out the window offset top and left utilizing the div handsontable is contained in instead of the browser scrollbar so my comments will display properly beside their respective column.

**Comment by friek108** [comment]
Actually, this applies to vertical scrolling as well - 
when using the normal scroll bars (not window scroll bars), the comment box doesn't display in the correct position unless you are scrolled all the way to the left and all the way to the top. 

Please refer to the JS fiddle to replicate the issue (tested in chrome + ie10). If you scroll just a tiny bit to the right and click on the comment box, it appears in the wrong position. Same for vertical scrolling.

http://jsfiddle.net/j8ue6b1k/

Opening a new issue as this refers to only horizontal scrolling (when it is actually vertical scrolling as well)

**Comment by AMBudnik** [comment]
Please track this issue https://github.com/handsontable/handsontable/issues/2278 for further information in this subject.
