### ISSUE TITLE
Issues with native scrollbars in IE10

### ISSUE THREAD

**Issue by MeerDev** [handsontable/handsontable#1732]
I am running latest version of IE10 and currently using jquery-1.8.3 (also used jquery-1.11.1 to confirm issues were still there).

I have noticed large performance issues when scrolling using the native scrollbars. This only happens in IE10 and not 9 or 11.

I have also noticed that fixedColumnsLeft setting does not work. Strangely fixedColumnsTop does work.

These issues only happen in IE10 and not 9 or 11. I am wondering if there is a known workaround I can do to use native scrollbars without these issues.

The issues are also in the handontable fixed column demo if you need to see exactly what I am talking about: http://handsontable.com/demo/fixed.html

**Comment by AMBudnik** [comment]
Hi @MeerDev please reply do you still face this issue after updating to 0.14.0?

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply.
