### ISSUE TITLE
minsparerows option to have spare row at top

### ISSUE THREAD

**Issue by pascoea** [handsontable/handsontable#1734]
What are the chances you could add an option to have the "minsparerows" have keep the spare row at the top of the table instead of the bottom?

**Comment by AMBudnik** [comment]
Currently there isn't a option that allows to have a minSpareRow at the top, but I can mark it as a feature candidate.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
