### ISSUE TITLE
No Add/Edit/Remove Comment in context menu with specific options

### ISSUE THREAD

**Issue by borg42** [handsontable/handsontable#1737]
Hi,

I would like to have a context menu that only shows Redo, Undo and Add/Edit/Remove Comment.

But there is no string available for comments, see http://handsontable.com/demo/contextmenu.html

At best i would like to use something like "contextMenu: ['redo', 'undo', 'comments']". Is that somehow possible with some kind of hack or similar?

Thanks!

**Comment by AMBudnik** [comment]
@mvagnoni great demo, it's still up to date if you remove jQuery which was dropped with 0.12.6 release.

**Comment by aravindgk47** [comment]
Hi, I am currently upgrading angular to 17 and hands on table to 14.i am encountering an issue with **checkSelectionCommentsConsistency()**. which is getting a console error as not a function . what's the latest implementation for this. i am not getting any proper understandable documentation online.

**Comment by AMBudnik** [comment]
Hi @aravindgk47 

Can you send us the demo for tests at support@handsontable.com?

**Comment by aravindgk47** [comment]
Hi @AMBudnik ,
unfortunately, it won't be possible. I am not able to understand **checkSelectionCommentsConsistency**() what this method does ?. it's not present in HandsOn table current version(V14). can you please explain to me what and how this function work and. what's is the relatable function in v14?

**Comment by AMBudnik** [comment]
@aravindgk47 the mentioned API was something used a few years back. The `checkSelectionCommentsConsistency` method is no longer used in Handsontable. So it might be easier to understand your requirements than to reconstruct the old method (since then we released many breaking changes).

**Comment by aravindgk47** [comment]
Hi @AMBudnik ,
the scenario is this. I need to check whether there is a comment in a cell when I right click, if there is something the menu will show as edit otherwise add

**Comment by aravindgk47** [comment]
@AMBudnik 
![image](https://github.com/handsontable/handsontable/assets/62371099/ff1fe7e2-7408-4f40-b17d-a233f5265f7e)
can you please look into it. i am basically stuck. the commented code is what causing the problem

**Comment by AMBudnik** [comment]
Hi @aravindgk47, please try this demo: https://jsfiddle.net/5zg6nkdy/ it uses the two official API methods
* `getSelectedLast()` to get the coordinates of the cell that has the menu opened
* `getCellMeta()` to check if the current cell has a comment (cell metadata property)
