### ISSUE TITLE
set cell value after 'afterCreateRow'

### ISSUE THREAD

**Issue by littleneotrix** [handsontable/handsontable#1740]
Hey guys,
I'm having a problem to achieve something here.
I'm trying to do that when a new row is being created, it'll automatically put a pre-defined value in a specific cell of this new row.

In the instance itself, when I'm creating it I'm adding those lines:
```javascript
                    afterCreateRow: function (index, amount) {
                        $('#table').handsontable('setDataAtCell', index, 0, 'new value');
                    }
```
I get in the console an error "too much recursion".
I tried few variations, like:
```javascript
$('#table').handsontable('setDataAtCell', 0, 0, 'new value');
```
And i got this error: "TypeError: instance.view is undefined".

BTW,
if I'm putting this command outside of the instance configuration and it's working fine,
but then I cannot place a value for every new row is being created.

Does someone have any idea of how to fix this issue or achieve it in other way?
Thanks!

**Comment by AMBudnik** [comment]
Here's a little [example](https://jsfiddle.net/AMBudnik/nfr31m9o/) how it can be achieved.

**Comment by littleneotrix** [comment]
@AMBudnik,
Thanks. Nice solution!

**Comment by zetwin** [comment]
Why pasting data more than 30 rows is to slooooow? hours.... If it will be 100 rows? is there solution?

**Comment by krzysztofspilka** [comment]
@zetwin I haven't spotted that. Could you show me some example (JSFiddle?)

**Comment by zetwin** [comment]
@krzysztofspilka Here is jsfiddle
https://jsfiddle.net/zetwin/9y421ay3/1/

**Comment by zetwin** [comment]
@krzysztofspilka here is jsfiddle
http://jsfiddle.net/zetwin/9y421ay3/1/

**Comment by Redleaf23477** [comment]
Hello everyone, 
What I hope to do is exactly the same as @littleneotrix .
But the problem I met was that the callback function will be called many times once a row was created?
My code looks like this:
```javascript
                hot.addHook("afterCreateRow", function(index){
                    console.log("Row Created");     // debug message
                    for(var i = 0; i < data[0]; i++){
                        hot.setDataAtCell(index, i, "new val" );
                    }
                });
```
In the console, the debug message was printed continuously and would't stop.
I've tried the solutions above but none of them worked...

Does anyone know why this is happening or  how to fix the bug?
Thanks!
