### ISSUE TITLE
z-index on dropdown box

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1741]
When I have
<div style="overflow: auto;">
<div id="handsontable"></div>
</div>
and I open a dropdown box from a cell (with dropdown as type) in the bottom of my grid the dropdown box is not visible because it lays under the horizontal scroll bar.

**Comment by AMBudnik** [comment]
I guess there is something missing after "I have" in your question. If you still have the same issue please provide more information, then we'll reopen the issue.

ps. I recommend updating to 0.13.0.
