### ISSUE TITLE
Blank option in dropdown

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1742]
Why is an empty cell invalid in cells with dropdown as type?

I know I can append blank as a element in my source list, but I don't want it as a clickable option. I don't see why it can't accept blank. If the user has to fill out the cell there could maybe be an "required" option instead of making the dropdown required by default without the option to disable this.

**Comment by tikitikifoofoo** [comment]
+1 on this feature. I've implemented a workaround that looks something like this:

```
cellProperties.renderer = (instance, td, row, col, prop, value, cellProperties) ->
   cellProperties.source = ["Option 1", "Option 2", "Option 3'"
   cellProperties.type = 'dropdown'
   cellProperties.strict = true
   cellProperties.validator = (value, callback) ->
     if cellProperties.source.indexOf(value) >= 0 or value is ""
       return callback(true)
     else
       return callback(false)
```

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
