### ISSUE TITLE
Fill handle and scrollbar

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1743]
When I load the handsontable with the options at http://jsfiddle.net/bjtj5pzx/ I can't select cells in the last row. Only when I have selected a cell in one of the two first rows I can move to the last row. But when I finally get to select a cell in the last row the fill handle is gone.

Sometimes it works, but then will the small fill handle icon in the lower right corner of the selected cell cause the vertical scrollbar to appear.

**Comment by AMBudnik** [comment]
I couldn't reproduce this issue wth your demo. If you still face this issue please reply, and we'll reopen this issue and try to solve it out.
