### ISSUE TITLE
Dropdown problem

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1744]
On http://jsfiddle.net/bjtj5pzx/1/ the dropdown doesn't work. I get a type error: "TypeError: element is undefined".
I cannot guess what I am doing wrong. It seems to work when I specify a data source, but shouldn't it work even without a data source?

**Comment by AMBudnik** [comment]
Here's your [example](https://jsfiddle.net/AMBudnik/jfhzrom6/). If you would have any other questions please, don't hesitate.
