### ISSUE TITLE
Centering checkbox cells

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1745]
When a cell has checkbox as type the checkbox input has a left horizontal alignment. Wouldn't it be better if they were located in center as default - or even better if there was an option to set horizontalAlignment and verticalAlignment without writing a custom cell renderer that adds a class to the cells.

**Comment by AMBudnik** [comment]
It is a good idea for a feature.

**Comment by AMBudnik** [comment]
For future information, please check https://github.com/handsontable/handsontable/issues/1720 issue.
