### ISSUE TITLE
Alignment on numeric and checkbox

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1746]
You can't change the alignment of checkboxes with the alignment menu in the context menu. It is also not possible to align numeric cells because they already has an alignment.

This could probably be solved by

.htCenter {
    text-align: center !important;
}

**Comment by YipYipX4** [comment]
I can also duplicate this issue.  Even if I set className to htCenter on a checkbox (or any non-text) column, it doesn't get applied to the cells.  If I use the browser's developer tools to manually add the htCenter class on a checkbox cell, then it works (until I scroll and the cell is rerendered).  I do not need the CSS style posted above -- I just need htCenter to be applied to the cell as it is for text cells.

**Comment by AMBudnik** [comment]
For further information about this subject, please keep track on https://github.com/handsontable/handsontable/issues/1720

**Comment by Codearella** [comment]
Is there a work-around for this issue yet?
