### ISSUE TITLE
Both value and text in autocomplete

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1747]
Is it possible to both have a value and a text in autocomplete cells? I can only see examples where the value of the cells has to be the same as the shown text.

In the demo there is a select editor, but I cannot find where to define the option values as in

```
<select name="select_name">
<option value="1">First option</option>
<option value="2">Second option</option>
</select>
```

**Comment by AMBudnik** [comment]
@mvagnoni is right, but add it as a feature candidate.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Duplicate of https://github.com/handsontable/handsontable/issues/535
