### ISSUE TITLE
Question for begginers

### ISSUE THREAD

**Issue by JustFound** [handsontable/handsontable#1749]
First of all: I'm begginer in html.

I don't know how to write simple program using this .

I want : 1. create table 2. create excell file with this information. 
Simple, right? :(

MY program is this:

<script src="../lib/jquery.min.js"></script>
<script src="dist/jquery.handsontable.full.js"></script>
<link rel="stylesheet" media="screen" href="dist/jquery.handsontable.full.css">
 <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>

<div id="dataTable"></div>
<script>
  var data = [
    ["", "Kia", "Nissan", "Toyota", "Honda"],
    ["2008", 10, 11, 12, 13],
    ["2009", 20, 11, 14, 13],
    ["2010", 30, 15, 12, 13]
  ];
  $("#dataTable").handsontable({
    data: data,
    startRows: 6,
    startCols: 8
  });
    
    
    handsontable();
</script>

Please tell me what I do wrong....

Thanks for the answer <3

**Comment by AMBudnik** [comment]
Hi @mvagnoni thanks for great piece of advice.
