### ISSUE TITLE
HOT merge cells incompatible with excel merge cells

### ISSUE THREAD

**Issue by merge-cells** [handsontable/handsontable#1754]
merge cells are not preserved when copying from HOT to excel (or vice versa).  In both cases, the cell shows up in the upper-left hand corner but the merge is lost.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
