### ISSUE TITLE
 fixedColumnsLeft doesn't work w/scroll in IE 10

### ISSUE THREAD

**Issue by GoingPostal** [handsontable/handsontable#1755]
The fixedColumnsLeft doesn't work in IE 10 with the latest update. Everything works well in Chrome and Firefox.

**Comment by AMBudnik** [comment]
Hi guys, this should be fixed with the newest [0.14.0](https://github.com/handsontable/handsontable/releases/tag/0.14.0) release - please update and leave us a feedback.

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/1616

**Comment by AMBudnik** [comment]
issue closed in lack of recent activity and feedback.
