### ISSUE TITLE
handsontable('getInstance') gives Uncaught TypeError

### ISSUE THREAD

**Issue by GitHubNub** [handsontable/handsontable#1759]
I am trying to use the search plugin for handsontable. However, in the 'keyup' function of the searchbox if I use an alert on $("#grid").handsontable('getData') I get values but on using $("#grid").handsontable('getInstance') I get the error Cannot call method 'apply' of undefined on lines
if( callback.call( obj[ i ], i, obj[ i++ ] ) === false ) {break;} of the jquery 1.8.3 js file.I am not able to figure out why that is happening.Plz help.

**Comment by AMBudnik** [comment]
Please provide a [demo](http://jsfiddle.net/api/post/library/pure/) for this issue if you still have this issue.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo for more than a month.
