### ISSUE TITLE
Multiple rows of column headers

### ISSUE THREAD

**Issue by cjameyson** [handsontable/handsontable#176]
I'm trying to add a second group of column headers above the 'real' column headers.  For example, my real headers are sports stats, but I want to be able to group them together under a top level grouping - like offensive and defense stats, etc.  See table below.

My approach was to simply generate them separately and insert them into the table like so:

`$('table.htCore thead').prepend('<tr><th colspan=3>OFFENSE</th><th colspan=3>DEFENSE</th></tr>');`

But, the table behaves strangely (duplicates the real header row instead of inserting my custom colspan'd headers).  

So then I tried adding it to both `.htCore` and `.htBlockedRows`
`$('table.htCore thead, table.htBlockedRows thead').prepend('<tr><th colspan=3>OFFENSE</th><th colspan=3>DEFENSE</th></tr>');`

But, all the clicks are 1 row off.  Any tips on how I can add this?  They don't need to be clickable or interact in any way.

```python
the goal...
---------------------------------
|  OFFENSE   |      DEFENSE     |    <--- group headers
---------------------------------
| K | E | TA | BS | BA | BE | D |    <--- the real headers
---------------------------------
| 8 | 1 | 9  | 5  | 2  | 1  | 9 |    <--- the data
---------------------------------
```

http://jsfiddle.net/Ckw9b/

**Comment by rizkyramadhan** [comment]
using latest handsontable, when we click any row the additional header is removed, so how to put it back ? 

See http://jsfiddle.net/erbronni/epsb6vct/ , click any row and you know what i mean.

**Comment by rizkyramadhan** [comment]
Ok, i fixed it, just remove 
            $('#header-grouping').remove();
inside beforeRender function, 

another bug: when we resize column using additional header, it miscalculated resulting width..

**Comment by japariciof** [comment]
any new about this feature?

**Comment by mydoom5** [comment]
I'm also really interested in a solution for this. 
The workaround above has too many issues to be used as a viable solution, unfortunately.

**Comment by shoji-k** [comment]
:+1: 

http://jsfiddle.net/rfalves/7qvqzosa/2/
When I resize window, this sample has a bug. Additional row replaces the original header.

**Comment by mydoom5** [comment]
If you get rid of the header-grouping in the ht_clone_top the resizing works, but a javascript error is thrown and I'm almost certain that if the handsontable has scroll there will be glitches when using the scrollbar... Besides, you can notice when the clone has been deleted, since there is a slight shadow under it (if you remove that style it is unnoticeable).
This is getting really hacky, but I didn't really find any other way around this :(

http://jsfiddle.net/rfalves/7qvqzosa/4/

If anyone can shed some light on this, we'll all be grateful. This issue is going on forever...

**Comment by shoji-k** [comment]
Great! :+1: 

Almost OK, but I'd like to sort.Column sorting does not work when I resize window.
http://jsfiddle.net/shojik/upzwfj79/1/

any Idea? I'm finding ..

**Comment by adityadineshsaxena** [comment]
For those like me who're still looking for a solution. Just do something of this sort and enjoy :+1: 

```
beforeRender: function() {
              $('.header-grouping').remove();
            },
afterRender: function() {
            var newHeaderRow = $('<tr>......</tr>');
            window.setTimeout(function() {
                $container.find('thead').find('tr').before('<tr class="header-grouping">' + newHeaderRow + '</tr>');
              }, 0);
            },
```

**Comment by shoji-k** [comment]
I avoid the resize probrem to use this code.

```
var resizeTimer;
var interval = Math.floor(1000 / 60 * 10);
window.addEventListener('resize', function (event) {
  if (resizeTimer !== false) {
    clearTimeout(resizeTimer);
  }
  resizeTimer = setTimeout(function () {
    $container.handsontable('render');
  }, interval);
});
```

This works well for now.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
This issue is added to the Handsontable PRO as [Nested Headers](https://docs.handsontable.com/pro/1.10.0/demo-nested-headers.html)

**Comment by deepthan** [comment]
I have implemented rowspan, which can be set in the same way as' nestedHeaders' and 'colspan', if you need it, please contact me at Github.
for example
```
nestedHeaders:  [
  [ { label: 'c', rowspan: 3}, { label: 'B', colspan: 9 }],
  ['', { label: 'E', colspan: 4 }, { label: 'F', colspan: 4 },  { label: 'G', rowspan: 3}],
  ['', { label: 'I', colspan: 2 }, { label: 'J', colspan: 2,  rowspan: 2 }, { label: 'K', colspan: 2 }, { label: 'L', colspan: 2 }, ''],
  ['N', { label: '2', colspan: 1 }, 'P', '', '', 'S', 'T', 'U', '22', '']
];

```

To render
![37818273a1cfa70243ff246937a0d9f](https://user-images.githubusercontent.com/22695767/158949613-993eae5d-83e6-497e-bd5e-40a05fde52ca.png)

**Comment by warpech** [comment]
Thank you @deepthan for your comment. For anyone who is looking for discussion about adding rowspan to nested headers, here it is: https://github.com/handsontable/handsontable/issues/191
