### ISSUE TITLE
Speed issue in handsontable in mozila

### ISSUE THREAD

**Issue by mukeshpromact** [handsontable/handsontable#1760]
I am facing speed issue problem in handsontable in mozilla browser. Whenever I am writing anything in cell then press "Enter" key to go to next cell then it is taking around 3-5 seconds to move to the next cell. I am facing this speed problem when there are so many records in a sheet.

Please help me out from this situation. To see this problem, you can go on following:

http://www.promact.semanticexcel.com/

And login with following details:

username: test password: test

and then open "LSA_Output_2nd.txt" sheet and then try to work with this sheet then you will notice speed issue. Please have a look and let me know if any solution you have. Thanks.

**Comment by AMBudnik** [comment]
I do not see this .txt file where you described but I went to 'testPlotCount' which works OK. If you still face the issue please reply nd we'll reopen this issue.
