### ISSUE TITLE
Delayed update of fixed/relative elements while scrolling - serious IE/FF issue

### ISSUE THREAD

**Issue by rbtbar** [handsontable/handsontable#1761]
Hello Everybody,

As many of you, I'm facing many of these vertical scroll issues... Basically, when using vertical scrollbar in IE or FF I can always see jumping column headers, misaligned rows and misplaced fixed columns. Believe me this makes really bad impression on the users... 
FF shows only short-living "1px" misalignments, IE is consistently broken and only Chrome is handling the vertical scrolling properly,.

Technically, the 'delayed update of a position' problem is clearly visible when the scroll handler is a relatively long running function (more than a couple of ms) and you've got a mixture of fixed/relative elements to be positioned... Unfortunately, HOT is drawing all elements from the scratch inside such a handler, so that it's not suprising that it takes 100-250ms to handle a single scroll event.

Please run the [jsfiddle demo][1] on different browsers to see different reactions on vertical scrolling. It takes 1 scroll handler, 1 sleep function and a couple of divs to complete the picture.

[1]:http://jsfiddle.net/rbtbar/1dudpeox/

All I can do now is to suggest to rework the internal structure of elements, so that either *wthider* is also 'fixed' (thus immune to the scrollbar position) or scrollbars are decoupled from the content and sit in a different branch of the DOM.

Best Regards,
Robert

**Comment by tikitikifoofoo** [comment]
I notice this issue in Chrome as well. The demos at handsontable.com are "flickering" as I scroll up and down.

**Comment by AMBudnik** [comment]
Related to https://github.com/handsontable/handsontable/issues/1962

**Comment by dimko1** [comment]
Any idea when this can be fixed?

**Comment by budnix** [comment]
Hi, In 0.15 version we moved internal elements from scrollable container. Additionally in 0.16 we improved performance in rendering system so this issue shouldn’t no longer exist.

**Comment by rbtbar** [comment]
Hi, apparently the issue still does exist in 0.16.1 (IE11, win7, i-7 3740QM at 2.7GHz, 16GB).

![hot-0 16 1](https://cloud.githubusercontent.com/assets/6705643/8925835/4860b4f8-350b-11e5-9b31-5197845ce5f6.gif)

Regards,
rb

**Comment by PassHours** [comment]
Yes the latest version of HOT has the same issue. Chrome is working good though.

**Comment by AMBudnik** [comment]
Thank you, we will take a closer look at this issue.

**Comment by alperenbelgic** [comment]
First of all, thanks for your efforts. It was hard to convince my manager to use this beautiful tool for our existing applications. But this issue makes harder defending the usage of HOT in our applications. Is there any thing I can help about this issue? Do you have any code written? Thanks a lot.

**Comment by mzagorny** [comment]
Hi, i have faced lags during scrolling on IE also. Behavior looks a bit different from rbtbar's 
PC configuration: Win7+IE10/11. 

You can check my 40 seconds screencast [here](https://drive.google.com/file/d/0B1o8jHzVT4-0ODZjN0NkUHpjNDg/view?usp=sharing)
**Video description**
I have used HOT's scrolling demo [page] (https://docs.handsontable.com/0.20.3/demo-scrolling.html)
At first I show how grid scrolling works in IE, after that I switch to Chrome and show how it works there. After that I switch to IE back

**Comment by krzysztofspilka** [comment]
@alperenbelgic  @mzagorny We haven't addressed this issue yet. Will look into it soon though. For some reason we are able to reproduce this bug when the table is being scrolled with a mouse wheel, in all other cases the delay is totally acceptable. I think that some kind of workaround could be increasing the offset in configuration, e.g.:

`viewportRowRenderingOffset: 20`

Notice: the above will be applied to all browsers.

**Comment by mzagorny** [comment]
@krzysztofspilka thanks for hint! We have tried it and UX in IE while scrolling becomes much better. And yes, it happens only in the case of using mouse wheel for scrolling

**Comment by krzysztofspilka** [comment]
@rbtbar @mzagorny @alperenbelgic guys, could you tell me if that works fine for you in the latest Handsontable version?

**Comment by ciffel** [comment]
The issue still does exist in v0.23.0.
Tested in IE11 (i5 3.1GHz, 8GB ram).
Scrolling up and down in [Handsontable performance test:
](http://jsfiddle.net/handsoncode/Lp4qn55v/)

![scroll](https://cloud.githubusercontent.com/assets/799624/13220346/ad782926-d9b0-11e5-9151-05032962440a.gif)

**Comment by rbtbar** [comment]
MS has recently informed they fixed the related [issue](https://connect.microsoft.com/IE/feedback/details/1001293/ie11-unable-to-synchronize-position-of-a-position-fixed-element-in-a-smooth-manner-while-scrolling-the-content-of-the-element-document)

I've tested it by myself and now scrolling up and down works fine in my [demo ](http://jsfiddle.net/rbtbar/1dudpeox/)as well as in the [performance test mentioned above](http://jsfiddle.net/handsoncode/Lp4qn55v/)

Tested in IE11.10310586.0 / Win10

**Comment by AMBudnik** [comment]
Thanks for sharing @rbtbar

**Comment by gtiguy92** [comment]
Can someone provide an update on this issue? It looks like it was kicked to several different milestones and then eventually placed on Backlog. The issue is still present in IE and Edge. Will all future progress be tracked against #3486?

**Comment by AMBudnik** [comment]
Hi @gtiguy92 
I think that this issue continues at https://github.com/handsontable/handsontable/issues/2350
