### ISSUE TITLE
Drag-down, how i tweaked incremential functionality

### ISSUE THREAD

**Issue by robiinho** [handsontable/handsontable#1762]
Hello everyone,

for a project i needed to have a drag-down which increment the next cell,

e.g.  a column with value : "10" when you drag down you want to have "11" , "12" , "13".

About that, I modified the file and I joined you the code: 
/dist/jquery.handsontable.full.js

It's an idea about a new functionality, also I had in mind if it might be possible to get the event if "CTRL" is pressed when there is a dragging-down, with that activate/deactivate the functionality.

And to copy and not increment just do as specify:
//if ctrl+enter and multiple cells selected, behave like Excel (finish editing and apply to all cells)

If someone had better idea, might be possible to play around line 1117

Thanks

Sources:
Line 884
  function applyChanges(changes, source) {
            var i = changes.length - 1;
            //tweak 1
            changes.reverse();
            var nbUnique = testUnique(changes);
            //fin tweak 1

            if (i < 0) {
                return;
            }

            for (; 0 <= i; i--) {
                if (changes[i] === null) {
                    changes.splice(i, 1);

                    continue;
                }

                if (changes[i][2] == null && changes[i][3] == null) {
                    continue;
                }

                if (priv.settings.minSpareRows) {
                    while (changes[i][0] > instance.countRows() - 1) {
                        datamap.createRow();
                    }
                }

                if (instance.dataType === 'array' && priv.settings.minSpareCols) {
                    while (datamap.propToCol(changes[i][1]) > instance.countCols() - 1) {
                        datamap.createCol();
                    }
                }

        
                //tweak 2
        donnees_add = changes[i][3];
                if (nbUnique == 1) {

                    if (source == "autofill") {
                        if (isNumeric(donnees_add)) {
                            if (iii) {
                                var iii = iii + 1;
                            } else {
                                var iii = 1;
                            }
                            var donnees_add = eval(donnees_add) + iii;

                        }

                    }
                }

        datamap.set(changes[i][0], changes[i][1], donnees_add);
//fin tweak 2		
        //        datamap.set(changes[i][0], changes[i][1],  changes[i][3]);
            }

            instance.forceFullRender = true; //used when data was changed
            grid.adjustRowsAndCols();
            Handsontable.hooks.run(instance, 'beforeChangeRender', changes, source);
            selection.refreshBorders(null, true);
            Handsontable.hooks.run(instance, 'afterChange', changes, source || 'edit');
        }

        this.validateCell = function(value, cellProperties, callback, source) {
            var validator = instance.getCellValidator(cellProperties);

            if (Object.prototype.toString.call(validator) === '[object RegExp]') {
                validator = (function(validator) {
                    return function(value, callback) {
                        callback(validator.test(value));
                    }
                })(validator);
            }

            if (typeof validator == 'function') {

                value = Handsontable.hooks.execute(instance, "beforeValidate", value, cellProperties.row, cellProperties.prop, source);

                // To provide consistent behaviour, validation should be always asynchronous
                instance._registerTimeout(setTimeout(function() {
                    validator.call(cellProperties, value, function(valid) {
                        cellProperties.valid = valid;

                        valid = Handsontable.hooks.execute(instance, "afterValidate", valid, value, cellProperties.row, cellProperties.prop, source);

                        callback(valid);
                    });

                    return value;
                }, 0));
            } else { //resolve callback even if validator function was not found
                cellProperties.valid = true;
                callback(true);
            }

        };
		
And put at the end 2 others functions:
//tweak 3

function isNumeric(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
}

function testUnique(array) {

    var i, j, len = array.length, out = [], obj = {};
    for (i = 0; i < len; i++) {
        obj[array[i][3]] = 0;
    }
    for (j in obj) {
        out.push(j);
    }
    if (out.length > 1) {
        return out.length;
    } else {
        return out.length;
    }
}		
// end tweak 3

**Comment by AMBudnik** [comment]
It will be faster if you could prepare us a [JSFiddle](http://jsfiddle.net/api/post/library/pure/) for that issue.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo for a month.
