### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by mazing** [handsontable/handsontable#1763]
If I click maximize HOT table in http://handsontable.com/demo/scroll.html in Firefox and selects a cell in the far-right column a horizontal scrollbar will appear

**Comment by AMBudnik** [comment]
Present in 0.24.1
Using `stretchH: all` and selecting any cel in last column displays scroll: http://jsfiddle.net/ad07d5rp/

**Comment by AMBudnik** [comment]
I wasn't able to replicate the same behavior in newest version, @mazing @rbtbar can you check it please?

**Comment by AMBudnik** [comment]
We've closed this issue as there are no additional requests. Again thanks for sharing.
