### ISSUE TITLE
How to retrieve merged cell info from handsontable?

### ISSUE THREAD

**Issue by jordanlev** [handsontable/handsontable#1765]
Really loving the new merge cells feature -- thank you so much for implementing that!

I see how to enable the feature, and how to set merged cells on initial data... but how exactly do I retrieve info about which cells are merged from the table when it comes time for me to save the user's input? The data structure that the handsontable is bound to (an array) just shows all the cell data -- no info about what is merged. And I couldn't find any kind of "getMergedCells" function in the docs or in the codebase itself.

Thanks.

**Comment by aloulygen** [comment]
Hi,
can u please, give an example of haw to use hotInstance.mergeCells.mergedCellInfoCollection.getInfo(row, col) ?

Thx

**Comment by JeromeLam** [comment]
@aloulygen, here's a jsFiddle I edited from the example taken on the [Merge Cells](http://handsontable.com/demo/merge_cells.html) demo page:  http://jsfiddle.net/veyx8Lz1/

I've hardwired the "Dump data to console button" to run *hot.mergeCells.mergedCellInfoCollection.getInfo(1,3)*, which checks if B4 is part of a merged group.  You will get *{"row":1,"col":1,"rowspan":3,"colspan":3}* as a response, which means B4 is part of a group that starts at B2 and is a 3x3 cell.

**Comment by aloulygen** [comment]
@JeromeLam, thank you.

**Comment by rasekar2000** [comment]
Hello @JeromeLam & Team,

  In this way, I can only get the static / predefined mergedCellInfoCollection only.

In this demo page, 
http://jsfiddle.net/veyx8Lz1/3/
 I have merged manually ( not in predefined mergedCellInfoCollection ) cell 4,1 and 4,2 and updated them as "Merged Cell" , 
    --> I could retrieve this value by calling , hot.getDataAtCell(4,1) as 

http://tinypic.com/r/almg7l/8

But when I merge some random cells, how do i get the mergedCellInfoCollection for the Cells (4,1)
 My expectation is that the response should be  {"row":4,"col":2,"rowspan":1,"colspan":2} for the attached use case.  Can you please let us know?
 
Thanks and Regards,
Raj
 PS: when i tried hot.mergeCells.mergedCellInfoCollection.getInfo(4,1), I got Undefined as expected

**Comment by swistach** [comment]
We are working on new version of the MergeCells plugin (#4214).
@jansiegiel - we shouldn't forget about tutorial with information about how to use the public API of the new plugin version.
