### ISSUE TITLE
fixedColumnsLeft bug?

### ISSUE THREAD

**Issue by hustcer** [handsontable/handsontable#1766]
It seems that there is a bug when fixedColumnsLeft was set. When add the option:
<code>fixedColumnsLeft: 3</code>
Only 3 columns were displayed. It works well in v0.10.5
BTW: Set table width also not work well like before.

**Comment by AMBudnik** [comment]
This issue is fixed, please see an example [demo](http://jsfiddle.net/82x8rjcb/). If you would experience the same or similar issue, please write us back. 

ps. I'm using lastest 0.13.0 HOT
