### ISSUE TITLE
Problem with iframe

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#1767]
I use HT_0.11.2 inside iframe but the floating colHeaders or rowHeaders appears unusual even if the colHeaders or rowHeaders set to false.

**Comment by AMBudnik** [comment]
Hi @douxlagithub please provide a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/) and if it's possible please update to 0.13.0

**Comment by AMBudnik** [comment]
Issue can be closed in lack of neede demo for more than a month.
