### ISSUE TITLE
Custom format for selection borders

### ISSUE THREAD

**Issue by TietoOliverKurowski** [handsontable/handsontable#1770]
I'd like to set the borders to a custom format (own color and border thickness).
Therefore I have added properties selectedCellBorderWidth/selectedCellBorderColor and selectedAreaBorderWidth/selectedAreaBorderColor for changing the area and current cell selections.
I hope you are fine with the changes.

**Comment by AMBudnik** [comment]
Thank you for that proposition.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
