### ISSUE TITLE
Slow in IE8 to IE 11

### ISSUE THREAD

**Issue by Cyr69** [handsontable/handsontable#1772]
Hello, 

I try to use HandsonTable with 20 columns and ~ 500 lines. 
Chrome and Firefox: it's ok.
IE8 11 horribly slow ... :( 

How to make fluid on IE? Thanks

Best Regard.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by sambsa** [comment]
This issue still persists. Not fixed. Kindly fix it. I am using latest handsontable-0.24.1. My table has 150 rows and 5 columns. In IE it is very slow to scroll down. Insert value in cell also taking lot of time. please fix it.

**Comment by AMBudnik** [comment]
Hi @sambsa Issue will stay closed till there's a developing update so it's not marked as 'fixed and working' it's still an improvement suggestion performance related.

**Comment by sambsa** [comment]
ok. When will it reflected buddy? I am working on mission critical task and it will need IE support.

**Comment by garypma** [comment]
Is someone looking into this issue? I'm still seeing major issues with IE11. Firefox works fine, but the performance in IE11 just plain sucks. In some cases it crashes for no apparent reason.

**Comment by tsukunen** [comment]
I also wish the immediate resolution!!
My environment, it is supposed to be ridiculous in the IE............

**Comment by AMBudnik** [comment]
This issue is closed as it refers to IE8 which we do nor support.
Please share your comments at: https://github.com/handsontable/handsontable/issues/3525

**Comment by sambsa** [comment]
Lot of people depend on IE, so it is not a good thing to neglect IE fix.

**Comment by AMBudnik** [comment]
Hi @sambsa 
We are referring only to IE8 - the IE9 and above versions are supported.

**Comment by AMBudnik** [comment]
Please continue this conversation in the following discussion https://github.com/handsontable/handsontable/discussions/8065
