### ISSUE TITLE
Unusable with overflow and no height

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1773]
There are critical problems when I am setting overflow: auto without a height on the container. I can't select cells and the console prints many errors.

See http://jsfiddle.net/kn29c51d/

**Comment by AMBudnik** [comment]
In I made un JSFiddle update for [your demo](http://jsfiddle.net/kn29c51d/1/) cause of jQuery (we dropped it on previous release), it has to work fine by now.

If you will face the same problem with 0.13.0 please reply.
