### ISSUE TITLE
Autoscroll demo page problem (see screenshots)

### ISSUE THREAD

**Issue by MrNikosia** [handsontable/handsontable#1774]
When scrolling down this demo-page:
http://handsontable.com/demo/autocomplete.html
The headers of all the handsontable get stuck on top op the browser.

And when i open the dropdown with the last table (ajax strict)
the dropdown shows the options dissapearing on top when scrolling fully down.
(see screenshots)

However after closing the dropdown and re-opening it seems to be solved,
although it seems not to be aligned a few pixels at the bottom

Firefox:

![knipsel](https://cloud.githubusercontent.com/assets/8783911/4278572/6ffc08e0-3d19-11e4-8e0e-4594d2a57a02.JPG)

Chrome:

![knipsel2](https://cloud.githubusercontent.com/assets/8783911/4278609/babdc850-3d19-11e4-8ef5-109a57f9b374.JPG)

Alignment problem when opening the dropdown for the second time in chrome:

![knipsel3](https://cloud.githubusercontent.com/assets/8783911/4278669/5f127946-3d1a-11e4-8ed9-6f3fc9429e5c.JPG)

**Comment by AMBudnik** [comment]
Thank you for that report.

**Comment by AMBudnik** [comment]
I couldn't reproduce it in:
* Chrome 41.0.2272.89 (64-bit)
* Firefox 36.0.4
on OS Yosemite

if you still experience that issue after updating to 0.13.1 please provide OS/browser information and we'll reopen this issue.
