### ISSUE TITLE
getCell() doesn't work correctly with fixed rows/columns

### ISSUE THREAD

**Issue by Estimable** [handsontable/handsontable#1775]
The getCell() function doesn't return the visible cell when fixed rows/columns are used if the cell in question falls within either the fixed rows or columns. See fiddle:

http://jsfiddle.net/4Lgsavww/

We are attempting to use getCell() to edit the CSS for particular cells that failed on the back end of our application (that is, separate from normal validation), but the CSS changes are applied to the wrong instance of the cell td.

**Comment by warpech** [comment]
Since version 0.12.2 it is possible using `true` as the third parameter to `getCell`

See the updated fiddle: http://jsfiddle.net/warpech/4Lgsavww/2/
