### ISSUE TITLE
Poor performance with large amount of columns in 0.11.x

### ISSUE THREAD

**Issue by alexyaseen** [handsontable/handsontable#1776]
Upon upgrading from 0.10.5 to 0.11.x, I noticed that performance was much worse. Upon further investigation, it seems that this is true only when there are a large amount of columns.

For example:
- In a table with 500 rows x 6 columns, performance is great (http://jsfiddle.net/68ygd2zf)
- In a table with 6 rows x 500 columns, performance is much worse (http://jsfiddle.net/p2op2ztu/1)

I am defining performance by how smoothly the table scrolls with the mousewheel or by holding the arrow key, as well as how responsive the table is to selecting and editing cells. I have tested this on both Chrome 35 and 38 on Mac and PC. To clarify, this issue did not exist in 0.10.5.

Am I missing something?

**Comment by krzysztofspilka** [comment]
This issue is fixed in the release 0.12.3, full note available here: https://github.com/handsontable/handsontable/releases/tag/0.12.3
