### ISSUE TITLE
Speed Issue when dynamically adding records through code

### ISSUE THREAD

**Issue by mukeshpromact** [handsontable/handsontable#1777]
I have tried to insert records dynamically in jquery handsontable. I have inserted 2500 rows with having 1 column through code. Following is the link. You will face speed problem when you will open below link. During the load of the url only it is adding records dynamically.

http://jsfiddle.net/hU6Kz/3032/

Please help me so that it become speed up when adding records dynamically.

**Comment by AMBudnik** [comment]
We are working on performance. For now you can try to load pure data and add options after rendering.
