### ISSUE TITLE
Performance issues for 700 x 60 table with renderer

### ISSUE THREAD

**Issue by myisis** [handsontable/handsontable#1778]
I thought handsontable only renders those table rows that are visible, but when I checked with Chrome developer tools, I found that all 700 rows of my tables are actually inserted into the DOM which makes scrolling very very slow. I'used this style `height: 200px; width:700px; overflow: scroll` in the wrapping container and version `0.11.2`.

**Comment by AMBudnik** [comment]
for more information in this subject please follow https://github.com/handsontable/handsontable/issues/1778
