### ISSUE TITLE
I'm sorry   The  method getSelected  can't  used in  0.11.2

### ISSUE THREAD

**Issue by kinggod** [handsontable/handsontable#1779]
var selection = $("#table").handsontable('getSelected');//returnd selected cell co.ordinates
//if single cell selected row and row1 will be same.
var row = selection[0];
var col = selection[1];
var row1 = selection[2];
var col1 = selection[3];
in 0.11.2

**Comment by AMBudnik** [comment]
I assume this isn't a problem anymore - if it is please reply and we'll reopen this issue.
