### ISSUE TITLE
Can't see bottom autocomplete dropdown when in overflow: scroll mode.

### ISSUE THREAD

**Issue by phyrisrose** [handsontable/handsontable#1781]
Here is a jsbin example: http://jsbin.com/xofab/2/edit

Notice that when you click on an autocomplete cell in the bottom row, the dropdown does get generated, but it's not at all obvious that it's there. So, if we had a table with just one row, there is no way a user would know that there are input suggestions available.

**Comment by donmccurdy** [comment]
Same issue here. Sometimes I'm able to fix it by adding a bit of CSS:

```css
.autocompleteEditor {
	position: fixed;
	margin-top: -90px;
}
```

... but that doesn't always seem to work, depending on the content and table size. The autocomplete dropdown may need to be appended to `<body/>` instead, if that's manageable.

**Comment by AMBudnik** [comment]
Please track changes on #2098 in this subject
