### ISSUE TITLE
How can   I get the fixedRows .fixedColumns and  the cell style

### ISSUE THREAD

**Issue by kinggod** [handsontable/handsontable#1783]
Hi there.

In which way do I should make to export the tables?

How Can fixed Rows,Columns  through the menu?

How can   I  collect  the fixedRows ,fixedColumns ,the cell style   and  so  on ?

Some suggestion may help me, thanks.
http://jsfiddle.net/wuw8w3sr/
http://jsfiddle.net/4zy3wjuL/

http://handsontable.com/demo/fixed.html    v0.11.2 too slowly

**Comment by AMBudnik** [comment]
Hi @kinggod 
Please check our [export to .csv](https://handsontable.com/examples.html?_ga=1.158769850.1420427662.1456872503&headers&csv-export) feature
