### ISSUE TITLE
Data Validation and Manual Column Move

### ISSUE THREAD

**Issue by barnamus** [handsontable/handsontable#1785]
In certain cases, when a column is manually moved and a datatype such as 'numeric' is used that attaches cell validation, when a user enters an incorrect value into the recently moved column, the cell in the column occupying the column's previous position displays as invalid, rather than the cell with the incorrect value.  To demonstrate, I created a new fiddle (http://jsfiddle.net/mzwbp2fz/) based on the numeric cell type example on the handsontable page.  The only change I made from the original example was to set the second column's (the Year column) type to 'numeric' and to set the 'manualColumnMove' option to true.  If you move the Year column in the table from the second column to the third column and type some letters into one of the Year column's cells, the corresponding cell in the Price column will be highlighted in red.  Any ideas?  I've witnessed this behavior in 0.11.beta3 through 0.11.2.

![image](https://cloud.githubusercontent.com/assets/8822179/4322550/74ac1fa6-3f49-11e4-90c8-e1c5949f9778.png)

**Comment by AMBudnik** [comment]
Very interesting, I reproduced this issue. Thanks for support.

**Comment by AMBudnik** [comment]
Confirmed with [updated demo](https://jsfiddle.net/mzwbp2fz/2/) using 0.17.0

**Comment by AMBudnik** [comment]
Updated to 0.24.1 works as expected. Demo: https://jsfiddle.net/mzwbp2fz/4/
