### ISSUE TITLE
Large number of rows in dropdown not displaying first time

### ISSUE THREAD

**Issue by sotomo** [handsontable/handsontable#1787]
I ran into some strange behavior when using a dropdown consisting of many rows.

Not all the rows appear the first time the dropdown is clicked. The second time it is clicked, it works. It does the same thing for me in Chrome, IE, Safari, and Firefox.

You can see the entire code in JSFiddle.

http://jsfiddle.net/nt001ymn/15/

**Comment by AMBudnik** [comment]
Hi @sotomo please update to 0.14.1 it works fine with [your demo](https://jsfiddle.net/nt001ymn/20/). We're open for your feedback.

**Comment by sotomo** [comment]
Thank you

Sent from Outlook




On Wed, Apr 8, 2015 at 1:48 AM -0700, "Aleksandra Budnik" <notifications@github.com> wrote:
Hi @sotomo please update to 0.14.1 it works fine with [your demo](https://jsfiddle.net/nt001ymn/20/). We're open for your feedback.

---
