### ISSUE TITLE
updateSettings not worked with mergeCells

### ISSUE THREAD

**Issue by HedCET** [handsontable/handsontable#1788]
var ht = $('#handsontable').handsontable('getInstance');
ht.updateSettings({mergeCells: [
    {row: 1, col: 1, rowspan: 3, colspan: 3},
    {row: 3, col: 4, rowspan: 2, colspan: 2}
  ]})

**Comment by winstars** [comment]
yes, i meet the same problem too.
I suggest providing an individual action for mergeCells, not in settings, plz.

**Comment by AMBudnik** [comment]
I made [this demo](https://jsfiddle.net/raar7wc3/) to study this problem.

 It seams that there is nothing you can do with `updateSetting` when you want to add/change merging **IF** you don't let `mergeCells: true` in settings loaded with hot.

Screetshot made from demo
![zrzut ekranu 2015-05-21 o 15 59 57](https://cloud.githubusercontent.com/assets/10757813/7750112/a7260fba-ffd2-11e4-9a27-b726f9aeb3aa.png)
(when `change hot` button is clicked nothing happens)

but if we let `mergeCells: true` in the first place

![zrzut ekranu 2015-05-21 o 16 02 36](https://cloud.githubusercontent.com/assets/10757813/7750236/50ef469c-ffd3-11e4-87ff-20bc8a36fc8c.png)
(cells aren't merged but `rowHeaders` are set to false as expected.

**Comment by csdpuneteam1** [comment]
Please fix this issue !

**Comment by computurus** [comment]
Also another option

```
var hotOptions = {};
//new merge data
hotOptions.mergeCells = [{row: rowStart, col: colStart, rowspan: rowspan, colspan: colspan} ];

for (var i=0; i<sp.handsOnTable.mergeCells.mergedCellInfoCollection.length; i++){
    hotOptions.mergeCells.push(sp.handsOnTable.mergeCells.mergedCellInfoCollection[i]);
};

sp.handsOnTable.updateSettings(hotOptions);
```

**Comment by Leobagua** [comment]
@computurus this works fine here! Thanks!

**Comment by codeh2o** [comment]
finally I found a  simple solution to fix this bug.enjoy

`
import { clone } from "lodash";
settings.mergeCells = clone(sourceCode.mergeCells)
hotInstance.updateSettings(settings);
`
