### ISSUE TITLE
selectCell(0,0,0,0,true) fails in afterCreateRow: - with empty dataset data: 

### ISSUE THREAD

**Issue by grahams777** [handsontable/handsontable#1789]
Like your work - thanks!
Version 11.2

getSelected fails when the table has a zero size dataset even with minSpareRows: 1,

works fine with dataset > 0 (note I moved the var selected ..... line outside the if statement to show the error

![image](https://cloud.githubusercontent.com/assets/8448393/4349042/3f6d7c0e-41a6-11e4-8740-fd904f8bb975.png)

Similarly selectCell fails

**Comment by jansiegel** [comment]
Seems to work fine with the latest HOT version.
