### ISSUE TITLE
Hovering over cells with comments causes lag and screen to freeze

### ISSUE THREAD

**Issue by DylanMoz** [handsontable/handsontable#1790]
When you hover over a cell with a comment, a small popup appears, showing the comment. The issue occurs when you hover over the cells with comments in quick succession. The result of doing so is the comment popups begin to lag behind and eventually the entire page becomes unresponsive.

Here is an example, simply move your mouse up and down along the column with comments: http://jsfiddle.net/9pjt985b/

**Comment by AMBudnik** [comment]
Hi @DylanMoz I couldn't reproduce it on Chrome 41 and Firefox 36. Comments are showing as fast as it's expected. If you'll still be having this issue after updating to 0.13.0 please reply and we'll reopen the issue.
