### ISSUE TITLE
updateTableSettings for fixedRowsTop

### ISSUE THREAD

**Issue by fano0001** [handsontable/handsontable#1791]
instance.updateSettings({fixedRowsTop : 0}) does not work.
The overlay is still present, but the table behavior is like no overlay is set.

I changed fixedRowsTop over the contextMenu from init value to 5 and than try set it back to 0 what causes the error behavior.

instance.updateSettings({fixedColumnsLeft : 0}) works fine

greets FaNo

**Comment by AMBudnik** [comment]
Can you please provide a demo for that issue?

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo for more than a month.
