### ISSUE TITLE
Cell Comments: z-Index and position Bootstrap Modal

### ISSUE THREAD

**Issue by imdadbahar** [handsontable/handsontable#1792]
When handsontable is used in Bootstrap Modal, comment box is not showing. If we increase the z-index, it shows. Also if we scroll down comment box is not showing at the correct position.

**Comment by krzysztofspilka** [comment]
https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5

**Comment by jdmcnair** [comment]
@krzysztofspilka it looks like this is an issue again in version 0.23.0... or at least the z-index problem in the modal is an issue. Haven't verified the position issue.

**Comment by AMBudnik** [comment]
Hi @jdmcnair I would really appreciate if you could create us a little demo where this issue can be replicable. May I count on you?

**Comment by jdmcnair** [comment]
Yes, I'll try to get together a jsfiddle for it.

**Comment by AMBudnik** [comment]
Thank you @jdmcnair

**Comment by jdmcnair** [comment]
Almost forgot... here's the jsfiddle for this issue: http://jsfiddle.net/101fegff/2/

Currently happening on version 0.24.2.

**Comment by AMBudnik** [comment]
Thanks for sharing @jdmcnair !
I'm reopening this issue.

**Comment by AMBudnik** [comment]
Hi @imdadbahar 
Thanks again for sharing - I hope that it works for you as well
