### ISSUE TITLE
First character typed in cell not capital when caps lock is pressed

### ISSUE THREAD

**Issue by ar3shadow** [handsontable/handsontable#1794]
When you begin typing in a cell it enters edit mode. The issue I'm having is that if caps lock is on the first character typed in a cell is entered as lowercase. If further characters are typed they are entered as uppercase as expected.

**Comment by AMBudnik** [comment]
I couldn't reproduce this issue. If you still have the same situation, please update your HOT to 0.13.0 and reply if it still occurs.
