### ISSUE TITLE
Handsontable with node/commonjs modules

### ISSUE THREAD

**Issue by bentedder** [handsontable/handsontable#1796]
Hi there. I'm having a bit of trouble getting the plugin to work as a node module. For a while I was dealing with getting a jQuery is undefined message, which was solved by adding `var jQuery = require("jquery");` in the head of the jquery.handsontable.js file. But now I'm getting a `Cannot set property 'isPrintableChar' of undefined ` message in the console. Here's my implementation:

```
var $ = require("jquery");
var handsontable = require("./jquery.handsontable");
var data = [
  ["", "Kia", "Nissan", "Toyota", "Honda"],
  ["2008", 10, 11, 12, 13],
  ["2009", 20, 11, 14, 13],
  ["2010", 30, 15, 12, 13]
];
$("#dataTable").handsontable({
  data: data,
  startRows: 6,
  startCols: 8
});
```

and just to be safe, as mentioned I have the following at the head of the handsontable.js file:

```
var jQuery = require("jquery");
/*!
 * Handsontable 0.11.3
 * Handsontable is a simple jQuery plugin for editable tables with basic copy-paste compatibility with Excel and Google Docs
 *
 * Copyrig....
```
If anybody has any insight, I'm all ears!

**Comment by AMBudnik** [comment]
Hi @bentedder we chaged HOT a little bit, we're jQuery free now. Please update to 0.14.1 and if you will face any issues - please provide a JSFiddle or any other demo and we'll reopne the issue and try to figure it out.
