### ISSUE TITLE
radio button cell type?

### ISSUE THREAD

**Issue by dpearl** [handsontable/handsontable#1797]
We have checkbox cell type, and how about radio button cell type? Can we set radio button type to cells

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by thakursagar** [comment]
@AMBudnik Any documentation/example on how to use the radio button cell type?

**Comment by AMBudnik** [comment]
@thakursagar issue is closed cause we keep feature requests in wiki section, `radio button` feature is not ready yet. As soon it's going to be ready this issue gets updated.

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
