### ISSUE TITLE
Silent mode for alter(...) methods

### ISSUE THREAD

**Issue by moniuch** [handsontable/handsontable#1802]
The `beforeRemoveRow` hooks (and probably many other hooks as well) requires `return false` to prevent the action to be carried out. In most cases that's fine, but in my case, where confirmation dialog has its own callback this requires a workaround and makes the code look ugly and not canonical, so to say.

The plugin I'm using to show confirmation dialog takes a `yesCallback` function argument, that is called when user's answer is `yes`. The usage goes along these lines:

```javascript
beforeRemoveRow: function(index, amount){
  mConfirm('Are you sure you want to delete this row?', function(){
     // delete row(s)
  });

  // whatever code follows here, is executed regardless of user answer, so:
  return false;
}
```

To work it around, I have to add `return false` right after `mConfirm` to globally prevent the hook from executing. Should user say `yes`, I have to programmaticaly remove the rows. You cannot do that via `alter('remove_row'...)` because it will trigger `beforeRemoveRow` over and over again and you will enter an endless loop. So the only way is through jQuery row manipulation, something like:

```javascript
beforeRemoveRow: function(index, amount){
  mConfirm('Are you sure you want to delete this row?', function(){
    $('#tableId').find('tr').eq(index).remove() 
    // the `amount` argument skipped here for sake of brevity
  });
}
```

I find it a very bad thing to do when, in the plugin's internal code, you try to access element from outer dom. It's not scalable. I haven't found a workaround for it.

### My votings
For better and more comfortable code I suggest:

1. Provide _silent mode_ by extending `alter('remove_row'...)` method (and all relevant other methods) with a boolean argument that would tell plugin to not trigger the hooks. Thus we would avoid endless loops mentioned above. Instead of above `tr.remove()` I could say:
```javascript
    this.alter('remove_row', ..., true) // true = keep silent, do not trigger hooks.
```
2. Provide an API way to acess the table element without reaching out to outer dom, say: `this.element`
3. I would opt for the hooks to be turned into true events, ones that you could actually stop (`e.preventDefault()`) and proceed with the rest of the code.

Sorry if I have overlooked something. Will be grateful for correction and pointing out a better way to address my problem.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
