### ISSUE TITLE
Unro Redo doesn't restore cell meta data

### ISSUE THREAD

**Issue by davidbin** [handsontable/handsontable#1807]
I removed  a column which I've set meta data in some cells by using setCellMeta method and after I undo (restore the removed column), only the cell value was restored, all the metadata was gone.

**Comment by AMBudnik** [comment]
Can you please provide a JSFiddle demo for that issue?

**Comment by AMBudnik** [comment]
Issue closed in lack of demo for more than a month. If you would still face this issue - feel free to reply.
