### ISSUE TITLE
Problem with loadData

### ISSUE THREAD

**Issue by mismej** [handsontable/handsontable#1809]
I have prepared page with handsontable like this:
https://www.vad.org.pl/user/?key=fda38f0ab55a0c333f4e6b9df90891&data=2014-09

I also want to make possible to reload data without refreshing page (function reload on my page). But when I try to use it I get in JS console error "Uncaught TypeError: undefined is not a function" and I have no idea why. Can you help me?

**Comment by AMBudnik** [comment]
Can you please provide a demo if you still face this issue? Link you typed requires logging.

**Comment by AMBudnik** [comment]
Closed in lack of recent activity or needed demo.
