### ISSUE TITLE
Merge Cells 

### ISSUE THREAD

**Issue by small-carbon** [handsontable/handsontable#181]
Merged cell function can provide it?

**Comment by niallrobinson** [comment]
Can anyone tell me if you can do the opposite? Split a cell in two?

**Comment by ping2anilsharma** [comment]
HI Niallrobinson,
You can use custom html for your task.

**Comment by ping2anilsharma** [comment]
Can any one suggest me how to add bootstrap chosen select in handosontable dropdown list in a cell.I have specified cell as html but it is not accepting it. My code is ---

![handosntable](https://cloud.githubusercontent.com/assets/7996025/6386874/d635df56-bda6-11e4-8bc5-04cce4941a6f.PNG)

var xd = [
                 {
                     type: 'text'
                 },
                 {
                     format: '0.00',
                     language: 'en',
                     type: 'numeric',
                     width: 70
                 },
                 {
                     type: 'numeric'
                 },
                 {
                     type: 'numeric'
                     //more locales available on numeraljs.com
                 }
        ];

        $(document).ready(function () {
            $(".chosen-select").chosen();
            var container = document.getElementById('example1');

            var $container2 = $("#example1");
            //var innerHTML = $('chosen-select').outerHTML;

            var bo  =[
                  ["<select class='chosen-select' style='width:200px;'><option value='value'>Test1</option><option value='value1'>Test2</option></select>", 1, 6999.99, 6999.99],
                  ["<select class='chosen-select' style='width:200px;'><option value='value'>Test1</option><option value='value1'>Test2</option></select></select>", null, 8330, 8330],
                  ["<select class='chosen-select' style='width:200px;'><option value='value'>Test1</option><option value='value1'>Test2</option></select>", 2011, 33900, 33900],
                  ["<select class='chosen-select' style='width:200px;'><option value='value'>Test1</option><option value='value1'>Test2</option></select>", 2004, 7000, 7000],
                  ["<select class='chosen-select' style='width:200px;'><option value='value'>Test1</option><option value='value1'>Test2</option></select>", '=SUM(B1:B4)', 30500, 30500]
            ];

            $container2.smartsheet({
                data: bo,
                columns: xd,
                startRows: 15,
                startCols: 16,
                rowHeaders: true,
                colHeaders: true,
                minSpareCols: 1,
                minSpareRows: 1,
                contextMenu: false,
                outsideClickDeselects: false,
                removeRowPlugin: true,
                cells: function (row, col, prop) {
                    var cellProperties = {}
                    if (col === 0) {
                        cellProperties.readOnly = false;
                        cellProperties.type = 'text';
                        cellProperties.renderer = "html";
                    }
                    
                    return cellProperties;
                }
            });
        });

**Comment by ping2anilsharma** [comment]
HI, How you have implemented the formula's with number formatting. Can you
please give me a sample demo link where I can see the handsontable with
formula's and formula's cell having number format's defined. See I have
implemented the formula's in handsontable but the number format are not
working. Waiting for fast reply....
