### ISSUE TITLE
minSpareCols don´t work with columns

### ISSUE THREAD

**Issue by skirgard** [handsontable/handsontable#1811]
When having diffrent column types like date, numerics etc minSpareCols dont work.
Here is a fiddle:
http://jsfiddle.net/4s4rf2g6/

Expacted behaviour should be one extra column.

**Comment by AMBudnik** [comment]
Thank you for support.

**Comment by AMBudnik** [comment]
Confirmed with 0.16.1 also.

**Comment by AMBudnik** [comment]
I guess it's actually the same issue as https://github.com/handsontable/handsontable/issues/2440
