### ISSUE TITLE
Problem with fixedColumnsLeft and custom html

### ISSUE THREAD

**Issue by Silenssi** [handsontable/handsontable#1814]
Hi,

having some issues with fixedColumnsLeft and custom html.

I have a table where the first  column left is fixed. On the last column I have checkboxes and in some cases also selects. 
![screenshot from 2014-10-07 15 00 13](https://cloud.githubusercontent.com/assets/6602489/4541806/dfce86fa-4e19-11e4-8b03-8e534fa9e6d7.png)

Due to subpixel stuff last columns' height might be for example 22.5px. And when the fixed column height is calculated, it's 23px. These differences add up further on the way down the table.
![screenshot from 2014-10-07 14 59 50](https://cloud.githubusercontent.com/assets/6602489/4541807/dfcf6cb4-4e19-11e4-8749-321eab3fb365.png)

I've experienced this on the newest Firefox and also on Android's Chrome. Zooming in fixes the problem most of the time. On other browsers zooming out shows the problem too.

Has anyone stumbled onto this problem before? Any ways around it? 

Sorry for the poor explanation, but I've had a long day trying to fix this.

**Comment by gstanislav** [comment]
Having this problem too. I need to have a fluid row height, so the above solution won't work for me.

**Comment by Laplandia** [comment]
I've been able to reproduce this problem on both Chrome and FF on Mac OS X without custom HTML.

**Comment by AMBudnik** [comment]
Please track changes to this subject in https://github.com/handsontable/handsontable/issues/2107 issue.
