### ISSUE TITLE
date type not working fine with bootstrap modal dialog

### ISSUE THREAD

**Issue by Suresh-Lakum** [handsontable/handsontable#1818]
Hi,

I have integrated handsontable into bootstrap modal dialog. I have one field of type date. When I open modal dialog and try to modify date it opens jquery.ui.date in background so i am not able to select date.
![demo](https://cloud.githubusercontent.com/assets/8993338/4571554/4bf383f2-4f79-11e4-91ce-46c207543dce.png)

**Comment by AMBudnik** [comment]
We had this issue some time ago, but it was fixed with previous release. If you would have same issue, please reply.
