### ISSUE TITLE
Handsontable beyond strings... interested? (native/complex datatypes)

### ISSUE THREAD

**Issue by thomasf1** [handsontable/handsontable#1819]
We´re using Handsontable on a Backbone-like framework and have some native and complex datatypes. 
Handsontable works surprisingly well for that with formatters and custom Editors... The two fields we put some work into where validators and copy&paste.

For example we store dates as dates and want to copy/paste them in a formatted way. Or we´ve got more complex things like multiple selections that are stored as arrays rather than strings.

The default at the moment seems to be to turn everything into strings though. Would you guys be interested in the changes to better support native/complex data?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
