### ISSUE TITLE
Column Sorting Deleting Comments

### ISSUE THREAD

**Issue by Svjard** [handsontable/handsontable#1826]
Seems that having the columnSorting enabled along with comments causes the comments to get rendered over, removing the htCommentCell class. Using the code below the latest version if I remove columnSorting all is well, but with columnSorting I see the comments for a split second, then a new rendering takes place and the comments are lost. Perhaps an ordering issue of what gets rendered when for each cell?

```
$("#example1").handsontable({
  data: data,
  rowHeaders: true,
  //columnSorting: true,
  minSpareRows: 2,
  colWidths: [255, 255, 255],
  colHeaders: ['Category', 'Name', 'Business Value'],
  comments: true,
  commentedCellClassName: 'htCommentCell',
  columns: [
    {data: 'category'},
    {data: 'name'},
    {data: 'businessValue'}
  ],
  cell: cells
});
````

**Comment by AMBudnik** [comment]
It might me related to https://github.com/handsontable/handsontable/issues/2003

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/2003
