### ISSUE TITLE
Logical index passed to afterChange instead of physical

### ISSUE THREAD

**Issue by 99williamsdav** [handsontable/handsontable#1827]
At the bottom of the page on understanding column sorting, there's a note on the afterChange event:
https://github.com/handsontable/jquery-handsontable/wiki/Understanding-column-sorting-plugin

Here it says the listener will receive the physical index of the modified row, therefore I would expect a row to be given a consistent index regardless of how the table has been sorted, but instead the logical index is passed.

See this jsFiddle: http://jsfiddle.net/wm1c7z1y/
We have a sortable table with what should match physical index in the first column. Any time you edit a cell, you will be alerted with the row index that was passed into afterChange. Edit a cell, see that the alerted value matches the first column. Now sort the table by descending index, and edit Barack Obama's name, you will be alerted with 0, which is clearly the logical index of the row, not the physical.

Have I overlooked something here or is this a bug/incorrect documentation?

Thanks.

**Comment by AMBudnik** [comment]
Thank you @hcs42, issue duplicate (#1501)
