### ISSUE TITLE
getSettings should return populated cell array with current cellMeta information

### ISSUE THREAD

**Issue by cocoanton** [handsontable/handsontable#1830]
In #1527 it was added the possibility to set meta for cells in the settings. But it should also be possible to get the populated cell array with all options, as I have tested it does not update this reference when using setCellMeta() and makes it hard to get all meta options.

**Comment by swistach** [comment]
Hi @cocoanton,
now is present method 'getCellsMeta()' which returns properties of the rendered cells. But if you want to get properties of each cell, you can iteratee on countRows() and countCols() with getCellMeta(row, column).
