### ISSUE TITLE
Multiple areas selection

### ISSUE THREAD

**Issue by ctsiot01** [handsontable/handsontable#1831]
It will be very helpful if the user is able to select more than one areas. E.g. after having selected one area, being able to hold ctrl and select a second area, a third etc. This is possible to do in excel so hopefully not too difficult to add.

![capture](https://cloud.githubusercontent.com/assets/9253085/4646759/2f8c1b0a-5476-11e4-857b-bcaaa979463e.PNG)

Many thanks!

**Comment by AMBudnik** [comment]
Hi, we have similar feature candidate to this one on #2119 issue. Please let be connect them.
