### ISSUE TITLE
Need a unique ID saved to database [from demo php.html]

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#1840]
Hi, I have learnt the php.html demo provided with handsontable to save data to sqlite server. I checked the inserted data ID was the same with row number. How to make database ID becomes unique. I mean we do not need to send ID from request as it will be automatically generated by sqlite ID record that has AUTOINCREMENT parameter. 

I tried some tricks but failed. May be Warpech or anybody who is master in PHP PDO could help solve my problem please..!

**Comment by AMBudnik** [comment]
Hi @douxlagithub 

I'd be happy to help if you're still looking for a solution.

**Comment by AMBudnik** [comment]
I assume that this lack of reply means that you've found a solution.
If not - please leave a comment.
