### ISSUE TITLE
Not sure y but I can see two headers overlapped over each other and on applying some padding on the page theaa

### ISSUE THREAD

**Issue by msganubhav** [handsontable/handsontable#1842]
Not sure y but I can see two headers overlapped over each other and on applying some padding on the page, these headers become visible one below the other. Any help would be appreciated.

**Comment by AMBudnik** [comment]
I guess I know where was the problem, and if so we made some changes to fix that. Can you please reply if you still have the same issue. If so, [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/) will be appreciated

**Comment by AMBudnik** [comment]
Issue will stay closed, but I still wait for you code if this issue still occurs.
