### ISSUE TITLE
Editor problems on Chrome

### ISSUE THREAD

**Issue by lucamaral** [handsontable/handsontable#1844]
I found an issue at [this example](http://handsontable.com/) on Chrome.

The editor textarea changes your size on user typing.
I recorded two videos to better explain the problem.

[On chrome](https://www.youtube.com/watch?v=MQJlu7wH0tI&feature=youtu.be)
[On firefox](https://www.youtube.com/watch?v=RaZ6AS9wVQo&feature=youtu.be)

**Comment by AMBudnik** [comment]
As I see solution is found and tested so I can close this issue. In case there'll be some other issue - please reply.
