### ISSUE TITLE
Add a 

### ISSUE THREAD

**Issue by pascoea** [handsontable/handsontable#1845]
I'm using your project as a CRUD.. one option that would be really helpful would be a "required" option in the column settings.

Something to this effect:

```
(function (Handsontable) {
	  'use strict';

	  /*
	    Adds appropriate CSS class to table cell, based on cellProperties
	   */
	  Handsontable.renderers.cellDecorator = function (instance, TD, row, col, prop, value, cellProperties) {
	    if (cellProperties.readOnly) {
	      instance.view.wt.wtDom.addClass(TD, cellProperties.readOnlyCellClassName);
	    }

	    if (cellProperties.valid === false && cellProperties.invalidCellClassName) {
	      instance.view.wt.wtDom.addClass(TD, cellProperties.invalidCellClassName);
	    }

	    if (!value && cellProperties.placeholder) {
	      instance.view.wt.wtDom.addClass(TD, cellProperties.placeholderCellClassName);
	    }
	    
	    //if the cell is empty and is required, highlight it.
	    if (cellProperties.required && !value) {
	        instance.view.wt.wtDom.addClass(TD, cellProperties.invalidCellClassName);
	      }
	    
	  }
})(Handsontable);
```

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
