### ISSUE TITLE
Custom Column Headings scroll issue

### ISSUE THREAD

**Issue by bommanapraveen** [handsontable/handsontable#1846]
My Page contains 2 tables with custom headings. If i scroll down to second table 1st table heading are scrolling down.

![image](https://cloud.githubusercontent.com/assets/9281302/4688917/8af634b4-569a-11e4-9de1-121e5314a587.png)

**Comment by AMBudnik** [comment]
Thank you for that issue. 

Actually [our demos](https://handsontable.com/demo/renderers_html.html) in second and third example act the same, and JSFiddle edit option prints:
 ```Uncaught TypeError: Cannot set property 'innerHTML' of null``` in the console.

**Comment by krzysztofspilka** [comment]
This is working fine in 0.17.0
