### ISSUE TITLE
How can i get "source" on a Handsontable cell type

### ISSUE THREAD

**Issue by radusl** [handsontable/handsontable#1848]
is it possible to get the "source" on Handsontable cell type just like in the Autocomplete cell type. something like this: 

type: "handsontable",
      source:  function(changes, source) { console.log(changes); },
      handsontable: {
        colHeaders: ['Marque', 'Country', 'Parent company'],
        data: manufacturerData,
      },

**Comment by AMBudnik** [comment]
You can set cell type like [here](http://handsontable.com/demo/numeric.html), if you do not set type by default it's always a `string`. If this was what you were looking for?

**Comment by AMBudnik** [comment]
Issue closed in lack of unsolved questions or recent activity.
