### ISSUE TITLE
#div.handsontable() does not work when integrated with ember.js (version 0.11.4)

### ISSUE THREAD

**Issue by ryanzyy** [handsontable/handsontable#1849]
Error Message:

Unhandled exception at line 1338, column 9 in jquery.handsontable.full.js
**0x800a138f - JavaScript runtime error: Unable to get property 'row' of undefined or null reference**
```
    if (typeof settings.cell !== 'undefined') {
      for(i in settings.cell) {
        var cell = settings.cell[i];
        instance.setCellMetaObject(cell.row, cell.col, cell);
      }
    }

    Handsontable.hooks.run(instance, 'afterCellMetaReset');
```

I got this error when I initialized handsontable on a didInsertElement hook of an ember view.

My Ember Code:
```
App.MyEmberView = Ember.View.extend({
  tagName: 'div',
  classNames: ['my-class-name'],
  insertTable: function(){
    var divElement = jQuery('.my-class-name');
    var data = [[1,2,3]];
    divElement.handsontable({ data: data });
  }.on('didInsertElement')
})
```

Version 0.10.5 works fine for me.

**Comment by karellm** [comment]
Any update on this issue? Installing the latest handsontable with Ember still throws the same error.

**Comment by chadtmiller** [comment]
@karellm setting the `cell` option to null works for now. If you need to customize cells you can use the `cells` option instead (ref [cell-options](https://github.com/handsontable/handsontable/wiki/Options#cell-options)).

See my comment here for more info: https://github.com/handsontable/handsontable/pull/2158

```javascript
import Ember from 'ember';

export default Ember.Component.extend({
  data: [],
  minSpareRows: null,
  colHeaders: false,
  contextMenu: false,

  didInsertElement: function() {
    new Handsontable(this.element, {
      data: this.get('data'),
      minSpareRows: this.get('minSpareRows'),
      colHeaders: this.get('colHeaders'),
      contextMenu: this.get('contextMenu'),
      cell: null
    });
  }
});
```

**Comment by archit** [comment]
Hey guys, please see https://github.com/handsontable/handsontable/pull/2317 this fixes the issue, when using with Ember.

**Comment by AMBudnik** [comment]
Issue close in lack of recent activity.

**Comment by karellm** [comment]
I confirm after upgrading to 0.15.0-beta3 that the error is gone. Thanks!

**Comment by archit** [comment]
:+1:

**Comment by AMBudnik** [comment]
Great to know. Thanks you for your support.
