### ISSUE TITLE
"Insert Row Below" and "Insert Row Above" context menu items disabled when only one row exists

### ISSUE THREAD

**Issue by LukeMurphey** [handsontable/handsontable#1853]
HandsOnTable disables the "Insert Row Below" and "Insert Row Above" context menus when a single row exists. This is confusing because users may not know how to add rows. The workaround is to highlight more than one cell or select the entire row.

This happens because the "row_above" and "row_below" handlers disable the row operations when the entire column is selected. Technically, selecting the header cell when only the header cell exists is selecting the entire row. However, I think this should be treated as a special case.

Note that older versions did allow adding rows when only one row existed (like 0.10.5).

**Steps to Reproduce:**

1. Remove all rows except for the header
2. Open context menu (right-click) on the header; note that the "Insert Row Below" and "Insert Row Above" items are disabled

**Comment by AMBudnik** [comment]
Hi @LukeMurphey, thanks for sharing.

**Comment by metaphalon** [comment]
Same Issue exists when only one column is available and the user want to add a new column.

**Comment by EsaMakinen** [comment]
Temporary fix for this problem is to check with afterRemoveRow if number of rows in table is 1 and add one extra row:

...
afterRemoveRow(index, amount) {
		if (yourdata.length=1) yourdata[1] = [];
		},
...

**Comment by adriennetacke** [comment]
Ran into this too. 

One option to consider (in my case, was the more optimal solution) is to automatically add another row for the user based on input. I implemented this by using the minSpareRows option:

...
{
minSpareRows: 1
}
...

In this way, another row is added as long as the user fills out part of the first row.
