### ISSUE TITLE
Column and row resizing not working in IE8

### ISSUE THREAD

**Issue by klinden** [handsontable/handsontable#1857]
I believe the problem at some level stems from IE8's imcomplete implementation of TextRectangle which is the return type of Element.getBoundingClientRect(). See https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIDOMClientRect for how it's supposed to work. The IE8 implementation does not include the width or height properties. These can be calculated easily enough, but their use is peppered throughout the library so my thought was to try to shim getBoundingClientRect to return an object with the additional properties. I haven't had much luck yet as IE8 will not allow me to add properties to TextRectangle. Will keep trying, but thought I'd log the issue in case anyone else had ideas.

**Comment by AMBudnik** [comment]
We do not support IE8 any longer, but feel free to make a reply if your issue will occur in newer versions.
