### ISSUE TITLE
Click event not firing after "afterChange"-event

### ISSUE THREAD

**Issue by frefal1** [handsontable/handsontable#1861]
Hi,
I am trying to implement a custom collapse/expand-function for rows with jQuery, simple divs inside a column with "+" and "-" signs, and accompanying click-events. 

Works fine until I trigger an "afterChange"-function which gets a cell-value, calculates and sets a another column cell-value. 
After that event, the table updates and I can no longer trigger the expand/collapse click events.

Please advice!
Best,
Fredrik

**Comment by PradeepGdr** [comment]
> Ah, solved it with event delegation!

can you send me 'afterchange' trigger code. 

var ht = $("#tblDetail");
$("#btnSave").on('click', function () {
ht.addHook.run(ht, 'afterChange');
});
here i'm trying to fire HandsonTbale 'afterchange' event from a button click in Jquery. but i'm running an error "Cannot read property 'run' of undefined". Thanks in Advance.

**Comment by PradeepGdr** [comment]
> > Ah, solved it with event delegation!
> 
> can you send me 'afterchange' trigger code.
> 
> var ht = $("#tblDetail");
> $("#btnSave").on('click', function () {
> ht.addHook.run(ht, 'afterChange');
> });
> here i'm trying to fire HandsonTbale 'afterchange' event from a button click in Jquery. but i'm running an error "Cannot read property 'run' of undefined". Thanks in Advance.

Maybe i have posted wrongly, here i'm asking for a solution
