### ISSUE TITLE
Once open cell editing can not be closed

### ISSUE THREAD

**Issue by imilic** [handsontable/handsontable#1862]
When you move column to right, and you try to edit cell belonging to other column that is between moved column old place and new place of new column once opened cell editing can not be closed

**Comment by AMBudnik** [comment]
I've tried to reproduce it with this [JSFiddle demo](http://jsfiddle.net/s9c3bwxt/) but seems that everything works as expected. Please prepare a demo, if this issue still occurs.

**Comment by AMBudnik** [comment]
issue closed in lack of demo.
