### ISSUE TITLE
Cursor goes left after first character entered for masked cells

### ISSUE THREAD

**Issue by micahhoover** [handsontable/handsontable#1863]
I have configured one of our table columns to have a mm:ss mask that looks like this:

__:__

If the user clicks the cell before the mask shows and then the user types a digit (e.g. "1") it looks like this:

1_:__

Which is good, but then the cursor moves to the beginning of the text, such that if the user then types "2" and then "3" they see:

23:1_

Is there something I can do to unconfigure this? I'm having some trouble narrowing down which line of code might be doing this.

**Comment by AMBudnik** [comment]
Hi @micahhoover please provide a demo for your idea, we'll see what we can do to help you.

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity and needed demo.
