### ISSUE TITLE
double border in edit mode

### ISSUE THREAD

**Issue by andyczerwonka** [handsontable/handsontable#1864]
I have a stock 11.4 version and I'm getting a strange double-border when I'm editing. Has anyone seen this before?

![selection_097](https://cloud.githubusercontent.com/assets/138898/4774864/bd683d40-5bb1-11e4-9845-b3e603ed9b16.png)

**Comment by pascoea** [comment]
Rock-on.  Thanks for the fix guys.  Me and style-sheets just don't get along very well.
