### ISSUE TITLE
copy/paste boolean values changes type

### ISSUE THREAD

**Issue by andyczerwonka** [handsontable/handsontable#1865]
When I copy a row that contains a boolean value and paste it into the next row, it take the boolean value and wraps it in quotes, effectively making it a string type.

Original Value
```
{myproperty: true}
```
becomes
```
{myproperty: "true"}
```

**Comment by AMBudnik** [comment]
Hi @andyczerwonka there's no boolean type of cell, so it converts it to a string.

ref: 
```type : String (default "text")```
```Shortcut to define combination of cell renderer and editor for the column. Possible values: text, numeric, date, checkbox, autocomplete, handsontable.```

**Comment by andyczerwonka** [comment]
What's the idiomatic way to deal with this?

**Comment by AMBudnik** [comment]
Hi @andyczerwonka 

how would you like the value to be rendered? As I assume you want it to be still a boolean in the `getData~` methods.

**Comment by andyczerwonka** [comment]
I just hooked up the `beforeChange` event and adjust in there.
