### ISSUE TITLE
Why doesn't className: "htCenter" does not get added to checkbox cells?

### ISSUE THREAD

**Issue by leikind** [handsontable/handsontable#1866]
Demo:  http://jsfiddle.net/2pssL3fr/1/

The class name just does not get added to the cell's td.
If I add htCenter manually via the Chrome inspector, it had the desired effect: the checkbox gets centered.

**Comment by AMBudnik** [comment]
The same issue as: https://github.com/handsontable/handsontable/issues/2925
Please track changes to https://github.com/handsontable/handsontable/issues/2925
