### ISSUE TITLE
Updatesettings not updating manualColumnResize

### ISSUE THREAD

**Issue by duranb** [handsontable/handsontable#1868]
If an instance of handsontable has "manualColumnResize" set to false, changing it to true does not actually allow one to resize a column.  The option is set correctly though.

My example is a modified version of the [Column Sorting](http://handsontable.com/demo/sorting.html) example:
http://jsfiddle.net/fpnr8k44/3/

Can this be done without completely destroying the table and reinitializing it?

Thanks for your time.

**Comment by AMBudnik** [comment]
Please check [it](https://jsfiddle.net/u26rahoo/) with the newest HOT version - works as expected.
