### ISSUE TITLE
[Select] Editor enhancement is required!

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#1873]
Hi, I am so excited using handsontable, It helped me a lot for my grid editing. I also made a big migration from conventional row editing through form into handsontable data grid editing [inspired by column mapping php.htm--warpech demo]. I missed just a little bit problem working with select editor. I need one thing that may be others also need. It is something like trebuchetty's select2 editor. The crucial thing I need is the 'text' is rendered based on the value id. select2 editor attempt is something like this: {editor:'select2', select2Options:[data:[{val:1,text:'Option 1'},{val:2,text:'Option 2'}]]}
But I found select2 doesn't work as it says. Hopes anybody have planned this issue to be realized.

**Comment by motin** [comment]
This seems to be reported against the wrong github project. Report here: https://github.com/trebuchetty/Handsontable-select2-editor/issues

And if you can, please send your enhancements as a pull request to that project. 

Thanks

**Comment by rajivseelam** [comment]
Hi,

Any comments on this issue with select2-editor

http://stackoverflow.com/questions/31239171/select2-dropown-in-handsontable-goes-out-of-layout-cell
