### ISSUE TITLE
something wrong with 0.11.4 with bootstrap 3.2.0

### ISSUE THREAD

**Issue by whuhenrylee** [handsontable/handsontable#1877]
when I use fix columns, the fixed columns moved too and the border of the fixed columns is ugly. the left position of the absolute div did not change where i scroll the horizontal bar,3ks
I change the bootstrap to 3.0 ,and the problem still exists

er..
when i follow into your code ,seem like that it's not the bootstrap's business ,i just config a horizontal fix , when  i scroll the vertical bar of the WINDOW,the WalkontableHorizontalScrollbarNative.resetFixedPosition method is called, but if I scroll the horizontal bar of the table container, it will not called , what's more I use backbone in my project, can you please help to fix this bug : )

**Comment by AMBudnik** [comment]
I had little changes in this matter, if you would have still this problem - please open a new ticket.
