### ISSUE TITLE
Validation beyond the first row when pasting into Dropdown cells

### ISSUE THREAD

**Issue by yuwong** [handsontable/handsontable#1879]
Referring to https://groups.google.com/forum/#!msg/handsontable/5374RiImnIQ/1hkogyCVjjsJ

The issue is this.strict in Handsontable.AutocompleteValidator is true for the first row, but undefined for all others, as this.cellProperties.strict = true; is only set in DropdownEditor.prototype.prepare, which only happened for the first one.

The workaround is setting strict: true explicitly when using type: 'dropdown' in the columns definition.

The fix is defining Handsontable.DropdownValidator, which will be the same as Handsontable.AutocompleteValidator but without this.strict in the if statement, as well as changing Handsontable.DropdownCell to use the new Handsontable.DropdownValidator for validator

**Comment by RKlante** [comment]
Sadly, the fix does not fix all scenarios.
When using a per-cell source for the dropdown choices' list, the "source"-property is also undefined for the new row(s) when pasting e.g. 3 rows in a table with only 1 or 2 existing rows.
I tried working around by calling validateCells an render after pasting, so at least the invalid cells would be highlighted - but then ran into the problem that the "nullable" property is also undefined at this point (my cells should allow null).

**Comment by yuwong** [comment]
Ah, I didn't expect the new rows would have undefined for source... sounds like a more considered fix is necessary, I thought it was solely down to the strict being set for only the first row, in which case the workaround would sort out the editing, obviously i've not tried this on new rows!

**Comment by AMBudnik** [comment]
I've reproduced it also in demo provided (https://jsfiddle.net/mzf3jsw0/)

Steps:
1. copy this code:
`invalid data`
`invalid data`
2.  paste into `Attribute Group` column at first cell

Result:
second row cell in `Attribute Group` should be heighlighted cause of invalid value.
