### ISSUE TITLE
Tabbing on handsontable cell does not move viewport inside iframe

### ISSUE THREAD

**Issue by MartinAntony** [handsontable/handsontable#1884]
We have handsonetable created inside iframe inside modal window. When initially we used beta version of handson table and the tabbing was working properly but after we upgraded our code to any of the stable version, tabbing on cell does not move the view(scroll bar not moving towards right).
Please let us know if you have any solution.

**Comment by AMBudnik** [comment]
Can you tell me if it still occurs?

**Comment by AMBudnik** [comment]
If you would have any new reports, please open an new issue.
