### ISSUE TITLE
Cell renderer getting fired many times with "undefined" as value

### ISSUE THREAD

**Issue by jasonhinkle** [handsontable/handsontable#1885]
Is there something that needs to be done to make cell renderers more efficient?  I have a table and putting a breakpoint on a basic cell renderer show that it fires a ton of times - initially with "undefined" as the value.  Is this happening to get measurements or something?

For example a table with only 14 columns and 2 rows, a single cell renderer fires 25 times on the initial table load!  I would think it should fire twice?

**Comment by AMBudnik** [comment]
same or very related to https://github.com/handsontable/handsontable/issues/2152
If any additional suggestions please add to https://github.com/handsontable/handsontable/issues/2152
