### ISSUE TITLE
method: updateSettings doesn`t work to merge cells programmatically

### ISSUE THREAD

**Issue by jeemworks** [handsontable/handsontable#1887]
code:

var $container = $('#example1');
var t = $container.handsontable('getInstance');
var s = t.getSettings();
var m = s.mergeCells;
m.push({ row:1, col:4, rowspan:2, colspan:2});
t.updateSettings({ mergeCells: m });
$container.handsontable('render');

**Comment by ericyang89** [comment]
can you please give me  a demo ,
 i meet the same problem ,but can not understand your solution
