### ISSUE TITLE
Remove column doesn't work

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1889]
In the context menu feature `Remove column` doesn't work on the 'column sorting' page. Actually nothing happens but throws an error in the console:

> Uncaught Error: cannot remove column with object data source or columns option specified 

**Steps to reproduce the problem:**

- Go to http://handsontable.com/demo/sorting.html
- Invoke context menu by right-click
- Select "Remove column"

:information_source:
> Handsontable v. 0.11.4
> Windows 8.1
> Chrome v. 38.0.2125.111 m

![remove-col](https://cloud.githubusercontent.com/assets/8048526/4978349/e7cd0b16-68ee-11e4-92ec-b041f7f0afb6.jpg)

**Comment by jansiegel** [comment]
It's actually a different bug:
After clicking the 'remove column' option, Handsontable throws a custom error: `cannot remove column with object data source or columns option specified`, which is self-explanatory.

However, Context Menu should recognise this situation and mark the unusable entries as disabled.
