### ISSUE TITLE
ALT+ENTER doesn't work properly

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1892]
Pressing `Alt` + `Enter` keyboard shortcut while editing the string doesn't break it into new line. Instead of forcing data onto multiple lines it just creates a new blank line.

**Steps to reproduce the problem:**

- Go to http://handsontable.com
- Edit cell B1 and set cursor in the middle of the string, e.g. between second and third character
- Press `Alt` + `Enter`

:information_source:
> Handsontable v. 0.11.4
> Windows 8.1
> Chrome v. 38.0.2125.111 m

![alt-enter](https://cloud.githubusercontent.com/assets/8048526/4979570/46babc28-68f8-11e4-9f3d-6aee18d85cba.jpg)

**Comment by jansiegel** [comment]
Released in version 0.12.6
