### ISSUE TITLE
What is the easiest way to populate a row with new data?

### ISSUE THREAD

**Issue by frefal1** [handsontable/handsontable#1893]
I have a "afterChange"-triggered function which takes a row(sourceData), sends it server side, calculates, and returns the result. Now I want to insert it, I've tried SetDataAtRowProp and
"changeSequence" on the original row, but nothing seems to work.
Any tips would be helpful!
/Fredrik

**Comment by AMBudnik** [comment]
Did you tried `updateSettings`? More about [methods](https://github.com/handsontable/handsontable/wiki/Methods)
