### ISSUE TITLE
ContextMenu width not rezisable

### ISSUE THREAD

**Issue by agucabral21** [handsontable/handsontable#1895]
I have created an item in the context menu that calls a function that get a variable value and shows it, but this variable (string) sometimes is longer than contextMenu width, so it doesn't show full value

![image](https://cloud.githubusercontent.com/assets/1836226/5028346/0a31f6ce-6b21-11e4-9b2c-19bd7da578f6.png)

i've found looking in  jquery.handsontable.full.js, in line 8736 the colWidth of context menu setted like this:

colWidths: [200]

The thing is that every time y rightClick in a diferrent column, the contextMenu variable changes and has different string lengths.

Is there any way to set context width manually beside modifying that line in handsontable.full.js?

**Comment by lostsnow** [comment]
+1

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
The current context menu stretches with the content https://jsfiddle.net/handsoncode/x3987zob/
Additionally, here http://jsfiddle.net/handsoncode/zryj9n1s/ is an example of how to set up a wider width for the context menu
