### ISSUE TITLE
Navigating with arrow keys is not compliant with MS Excel

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1898]
Maybe it's maybe just me but I got used to MS Excel navigation look&feel in which I can navigate between cells only if they aren't in the edit mode. In Handsontable when the cursor is positioned at the end of the content and I press right arrow key the selection moves to the next cell. I think this should be changed to maintain compliance with MS Excel, Google Spreadsheets etc. 

**Steps to reproduce the issue:**

- Go to http://handsontable.com
- Select any cell and press F2
- Press right arrow key

:information_source:
> Handsontable v. 0.11.4
> Windows 8.1
> Chrome v. 38.0.2125.111 m

![right-key](https://cloud.githubusercontent.com/assets/8048526/5029036/7cc38330-6b42-11e4-840c-b456c18380ee.jpg)

**Comment by krzysztofspilka** [comment]
Let's say it's not a bug, our opinions are divided.

**Comment by xasp** [comment]
I've implemented this functionality using the beforeKeyDown hook, for those interested : see http://tri-s.be/blog/2015/7/3/arrow-navigation-in-handsontable.aspx
