### ISSUE TITLE
Custom background color should be darker when a cell is selected

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1900]
In MS Excel when a cell with custom background color is selected its background becomes darker. In Handsontables it applies only to cells with white background.

**Steps to reproduce the issue:**

- Go to http://handsontable.com/demo/renderers.html
- Select the entire column with cells of different background color

:information_source:
> Handsontable v. 0.11.4
> Windows 8.1
> Chrome v. 38.0.2125.111 m

Select column in Handsontable:
![color-hot](https://cloud.githubusercontent.com/assets/8048526/5029613/d88b5b56-6b48-11e4-91f5-db14e3f7af49.png)

Select column in Excel:
![color-msexcel](https://cloud.githubusercontent.com/assets/8048526/5029612/d889f45a-6b48-11e4-8830-c75e59350f09.png)

**Comment by krzysztofspilka** [comment]
The scope to be discussed. We need to take into consideration rich content (images, html elements etc.).

**Comment by jansiegel** [comment]
After resolving this issue, check if #2183 is also fixed.
