### ISSUE TITLE
CTRL+Z reverses changes that weren't even done

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1901]
It happens when I fill cells with data and then try to reverse (redo) changes by pressing CTRL+Z. By pressing it more than one time I can remove all the data in a table.

**Steps to reproduce the problem:**

- Go to http://handsontable.com
- Select cells from F1:F5
- Fill cells F6:F10 using fill handle
- Press CTRL+Z six times

:information_source:
> Handsontable v. 0.11.4
> Windows 8.1
> Chrome v. 38.0.2125.111 m

![fill-handle](https://cloud.githubusercontent.com/assets/8048526/5030621/7387c42a-6b51-11e4-8f40-73f31d188cd2.jpg)

**Comment by jansiegel** [comment]
@krzysztofspilka Can you try to reproduce it with the current version? It seems to work fine for me with v. 0.12.3

**Comment by jansiegel** [comment]
Released in version 0.12.6
