### ISSUE TITLE
Horizontal scroll in 0.10.5

### ISSUE THREAD

**Issue by sriharisurendra4u** [handsontable/handsontable#1905]
Hi,

Horizontal scroll is not working when we have two header(means one with sub header).
When we scroll the horizontal scroll bar sub header columns are jumbling.
In the attachment A and B are Main headers and C,D,E,F and G are sub headers.
I want scroll after C. Means FixedColumn:1

Please help me out with the same version. because it got resolved in 0.11.4 beta, but, handsontable having poor performance.

Regards,
Srihari

**Comment by AMBudnik** [comment]
If you still have this issue, please provide a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/)

**Comment by sriharisurendra4u** [comment]
Hi @AMBudnik,

Please check JSFiddle http://jsfiddle.net/zv0noswL/1/

freezing columns is working here. but, In Handsontable 0.10.1 version im facing column headers jumbling Issue.

Thanks in advance

Regards,
Srihari

**Comment by AMBudnik** [comment]
OK, thank you.

**Comment by AMBudnik** [comment]
I tried it with 0.15.0-beta3 and it works fine. Please leave your feedback if it still occurs.
