### ISSUE TITLE
Collapsable relational table, suggestions for new features

### ISSUE THREAD

**Issue by Gonzalo2683** [handsontable/handsontable#1906]
Cheers, very good plugin.
Do not know if it's the place to post suggestions for new features.
It would form the plugin, do something like this?

http://dev.sencha.com/ext/5.0.1/examples/executive-dashboard/#!profitloss

The values are on the left has sub fields within each row ( fixed header and row toggable).

 It is possible?
I am sorry for my write english.
Thanks.

**Comment by AMBudnik** [comment]
Issue closed in lack of reply from an author or other questions in this issue.

**Comment by Gonzalo2683** [comment]
Thanks and sorry for the delay, I never got notice

**Comment by AMBudnik** [comment]
Callback added as [beforeRowMove](https://docs.handsontable.com/pro/1.10.0/Hooks.html#event:beforeRowMove)
