### ISSUE TITLE
Allow event handler to prevent autofill/drag-down

### ISSUE THREAD

**Issue by mattwigway** [handsontable/handsontable#1908]
It would be nice if it were possible for the beforeAutofill handler to prevent drag-down. This would be useful to keep invalid data from being created, as well as to implement custom autofill behavior.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
We are able to block the autofill action by returning '`false`' in the `beforeAutofill` hook. Example https://jsfiddle.net/handsoncode/8rxc4Lej/
