### ISSUE TITLE
Autofill: No events fired when dragging beyond table borders

### ISSUE THREAD

**Issue by RKlante** [handsontable/handsontable#1910]
Hi Devs,

when dragging the fillhandle beyond table borders, no event (at least none i could find, tested before/after change, autoFill, createRow, ...) gets fired leading to, in my case, inconsistency between client and server state.

Attached gif demonstrates what i mean by dragging beyond the borders.
![hot_aufofill_error](https://cloud.githubusercontent.com/assets/8253841/5070045/ccc0d13a-6e62-11e4-9c1a-c3d4b140be39.gif)

If i am not missing something here, i think this should either be handled by the existing callbacks - or prevented in the first place.

I am on 0.11.3 btw.

Edit: just discovered that, if you move the mouse back into the table, making the litte red autofill-frame appear, all events fire. Only if you do not return your cursor to the table before letting go of the mouse button, the error occurs.

To demonstrate, here's how the demo page behaves in both cases.
First, incorrect behavior:
![hot_aufofill_error_1](https://cloud.githubusercontent.com/assets/8253841/5070240/dcf60528-6e64-11e4-9f6d-71c267c0242f.gif)

And correct behavior (after returning mouse cursor into table):
![hot_aufofill_ok](https://cloud.githubusercontent.com/assets/8253841/5070242/f0b230fa-6e64-11e4-9e98-45a3e14217a5.gif)

Hope this helps!

**Comment by AMBudnik** [comment]
Related to @2110

**Comment by AMBudnik** [comment]
Since 0.23.0 you can allow or disallow creating new rows using:

`fillHandle: {`
     ` autoInsertRow: false`
    `}`

Issue: https://github.com/handsontable/handsontable/issues/2874
Release note: https://github.com/handsontable/handsontable/releases/tag/0.23.0
