### ISSUE TITLE
Validation not rendering after loadData

### ISSUE THREAD

**Issue by TheTruQ** [handsontable/handsontable#1912]
When loading data post instantiation, and calling the validateCells method, validation failures will only display after scrolling (if there are enough records) or editing a cell.  I also called the render method to attempt to force application of the validation class, but that didn't work either.

Could not find any other documentation mimicking this experience.

**Comment by ajgraham671** [comment]
I am experiencing the same exact issue using the validate method on the demo page. I'm also using the version 0.12.4.

**Comment by krzysztofspilka** [comment]
Thanks for reporting, it should be fixed asap. Stay tuned.

**Comment by budnix** [comment]
Bug should be fixed. It should be released in next version of Handsontable. 

For workaround you can try to rerender table after validation of cell/s process.
For all cells: `hot.validateCells(function() { 
    hot.render() 
});`
For single cell (eg: col: 1, row: 1): `hot.validateCell(hot.getDataAtCell(1, 1), hot.getCellMeta(1, 1), function(){ hot.render() });`
