### ISSUE TITLE
Use of mouse wheel to select the next/previous row

### ISSUE THREAD

**Issue by marpagu** [handsontable/handsontable#1913]
Good morning,

I would like to use the event triggered by the mouse wheel to select the next or previous row in a table. 

In previous versions of the library I captured the event of the html element and I manually select the appropriate row:

```javascript
... {
e.preventDefault();
if (e.originalEvent.deltaY < 0) {
		//select the previous row
}

if (e.originalEvent.deltaY > 0) {
		//select the nex row
}
...}
```

 In the new version (0.11.4) such event is not detected. Even more, the new callback "AfterScrollVertically" is executed but I have not found how to know if the wheel has been turned up or down.

Could anyone explain whether this functionality is possible with the new version?

Thanks in advance.

**Comment by AMBudnik** [comment]
If you still face this issue please update to 0.14.1 or newer, and prepare us a demo code. Since this issue in older than a half of month, it will stay closed till an author's reply.
