### ISSUE TITLE
Render used for change cell colour removes cell format

### ISSUE THREAD

**Issue by agucabral21** [handsontable/handsontable#1916]
I have a column with options type: numeric, format: $0,0.00 , and in cells options i call a render that changes cell color after i change the value of the cell.

this is the render:

var changedRenderer = function (instance, td, row, col, prop, value, cellProperties) {
        Handsontable.renderers.TextRenderer.apply(this, arguments); 
        td.style.background = '#B3D9D9';	   
};

But when i change a value of that column, the render does it work and change it color but removes the cell format like this

![image](https://cloud.githubusercontent.com/assets/1836226/5089669/ecc68bf2-6f23-11e4-859f-da6f6069d2ce.png)

![image](https://cloud.githubusercontent.com/assets/1836226/5089676/f8514d40-6f23-11e4-8302-81bcc2b84d17.png)

![image](https://cloud.githubusercontent.com/assets/1836226/5089701/1f362516-6f24-11e4-84ae-2f0664e730cf.png)

the format $0,0.00 has gone.

BTW , the column left to the one i modified has a formula, thats the reason why the third image shows a different value in that cell

**Comment by AMBudnik** [comment]
@steelstyle thanks for support

**Comment by ping2anilsharma** [comment]
HI agucabral21,

ow you have implemented the formula's with number formatting.
Can you please give me a sample demo link where I can see the handsontable with formula's and formula's cell having number format's defined.

See I have implemented the formula's in handsontable but the number format are not working.

Waiting for fast reply....

**Comment by ping2anilsharma** [comment]
HI,

How you have implemented the formula's with number formatting.
Can you please give me a sample demo link where I can see the handsontable
with formula's and formula's cell having number format's defined.

See I have implemented the formula's in handsontable but the number format
are not working.

Waiting for fast reply....

On Thu, Mar 12, 2015 at 3:27 PM, Aleksandra Budnik <notifications@github.com

**Comment by ping2anilsharma** [comment]
HI, How you have implemented the formula's with number formatting. Can you
please give me a sample demo link where I can see the handsontable with
formula's and formula's cell having number format's defined. See I have
implemented the formula's in handsontable but the number format are not
working. Waiting for fast reply....
