### ISSUE TITLE
Line height in edit mode is different than in static mode

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1918]
Line height is being changed (increased) after confirming multiple text in a cell.

**Steps to reproduce the problem:**

- Go to http://handsontable.com
- Edit any cell, type anything and press `ALT` + `ENTER`. Repeat this 3 times.
- Confirm changes by pressing `ENTER`

:information_source:
> Handsontable v. 0.11.4
> Windows 8.1
> Chrome v. 38.0.2125.111 m

![line-height](https://cloud.githubusercontent.com/assets/8048526/5105263/1f1849e8-6feb-11e4-994f-83f0c4ccb871.jpg)

**Comment by jansiegel** [comment]
Released in version 0.12.6
