### ISSUE TITLE
i don't understand what exactly load data is doing

### ISSUE THREAD

**Issue by mapinales** [handsontable/handsontable#1920]
Hello,

I am using handsontable and I am having an issue with row movement and sorting.  I created my own sorting function and i use the afterOnCellMouseDown event to trigger it.  At the end I recreate the array I'm using for the spreadsheet and call sheet.loadData(dataArray); then sheet.render(); to display my changes.  This is working fine.

However, when I move a row and then use my sort algorithm, the underlying data is being sorted correctly, but the spreadsheet is rendering the information out of order.  It seems like after the call to loadData and render the spreadsheet remembers the row ordering and puts things back in their original row and not their new row based on their actual order in the data.  

How is this possible?  How can I "clear" the changes to make a fresh table?  I can't call destroy from within its own events, that throws an error.  

Any help would be greatly appreciated.  Thank you.

Miguel

**Comment by AMBudnik** [comment]
If you're still looking for answer to this question, please prepare [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/) and we'll see what we can do.

**Comment by AMBudnik** [comment]
Issue closed in lack of a needed demo or any other response for more than a month.
