### ISSUE TITLE
Tree table support

### ISSUE THREAD

**Issue by pombredanne** [handsontable/handsontable#1924]
I wonder how we could have some tree table-like support.
This is somewhat related to grouping but the actual is quite different, looking more like Mac finder UI and not excelish like the grouping.
For an example in slickgrid: http://mleibman.github.io/SlickGrid/examples/example5-collapsing.html

**Comment by Narayanan12345** [comment]
Any development about the tree support.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
