### ISSUE TITLE
Copy Paste Image

### ISSUE THREAD

**Issue by vinothjaguva** [handsontable/handsontable#1925]
Unable to copy paste the image. This is most important feature, that needs to be included, to show the handsonetable into next level.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
