### ISSUE TITLE
Paste after copy from Excel doesn't work

### ISSUE THREAD

**Issue by Terpinator** [handsontable/handsontable#1928]
My apologies if this is noted in some documentation somewhere.  Since copying from Excel (i.e.) puts text in the system clipboard, the ZeroClipboard doesn't know about it, so Paste (from the context menu) will only paste the latest from ZeroClipboard's clipboard.

**Comment by servocoder** [comment]
I have just faced the same thing. The topic is old, is there any thoughts on this?

**Comment by AMBudnik** [comment]
I think that it is the same issue as https://github.com/handsontable/handsontable/issues/3496
If I'm wrong please leave a comment.
