### ISSUE TITLE
Merge Cell Details

### ISSUE THREAD

**Issue by debenndra** [handsontable/handsontable#1929]
I want to store merged cell details permanently so that i can access it later time may be from some file or database...so how can i get all merge cell details from handsontable

**Comment by AMBudnik** [comment]
Unfortunately we don't have an event that can be easily tracked for merged cells.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
