### ISSUE TITLE
 Not possible to insert new line within multiline text in text editor

### ISSUE THREAD

**Issue by ashishjai** [handsontable/handsontable#1931]
I am using handsontable and I am having an issue when I Click on editable cell and enter some multi line text e.g.
Line 1
Line 2
Line 3
and hit the enter to exit the cell
Double click the same cell to edit the text  and place the cursor at the end of Line 1. Hit alt+enter to insert new line after Line 1, new line is inserted at end of existing text and cursor is placed there instead of inserting new line after Line1

**Comment by AMBudnik** [comment]
For further information about this issue, please track #2182
