### ISSUE TITLE
Option values for select editor

### ISSUE THREAD

**Issue by hellovijayr** [handsontable/handsontable#1932]
http://handsontable.com/demo/dropdown.html

In the example above, the dropdown values are mentioned in the "source" parameter.  Is it possible to have both option value and text, the way we have it in the usual HTML select option?

Like "&lt;option value='kia_car'&gt; Kia &lt;/option&gt;"

**Comment by motin** [comment]
#1873 is not relevant, since it is an issue filed incorrectly against handsontable when it should have been filed against https://github.com/trebuchetty/Handsontable-select2-editor/

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by rajivseelam** [comment]
Any comments on issue with select2-editor which is posted here

http://stackoverflow.com/questions/31239171/select2-dropown-in-handsontable-goes-out-of-layout-cell
