### ISSUE TITLE
GenericRenderer for diferent types

### ISSUE THREAD

**Issue by agucabral21** [handsontable/handsontable#1933]
I'm working with handsontable using json as datasource. Each columns refeer to object.value and each json object looks like:
//
row:[
    {
        data1:{
                   value : "5"
                   changed : true/false
                   status : ###
        },
        data2:{
                   value : "7"
                   changed : true/false
                   status : ###
        }
     },...//and more like this one
]

I have created this renderer:
//
var gridRender = function (instance, td, row, col, prop, value, cellProperties) {	
		
	///here i hace made some code that basicaly for each row, col i get the specific:
       //data#:{
       //           value : "7"
       //            changed : true/false
       //            status : ###
       // }
       
      Handsontable.renderers.NumericRenderer.apply(this, arguments);

      //and from that y read
           //if status does not exist i set background empty
	    if(!cellToRenderDatasource["status"]){
	    	td.style.background = '';
	    }
	      //if changed = true then change the colour to green
	    if(cellToRenderDatasource.changed){
	    	td.style.background = '#B3D9D9';					    	
	    }
	    
            //if status= "formShow"  then change the colour to yellow
	    if(cellToRenderDatasource["status"] == "formShow"){
	    	td.style.background = '#FFFF75';	   						    	
	    }
	}	

};

But my problem is that i have some columns that are numeric with format, and others are text,  and i dont know how to set the render to works with al of them. Any ideas?

**Comment by AMBudnik** [comment]
Can you provide a demo of your code?

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.
