### ISSUE TITLE
Bootstrap on width change, expands but does not contract

### ISSUE THREAD

**Issue by yannisps** [handsontable/handsontable#1934]
The table expands and follows the parent container's width but when the window shrinks, the table remains intact.

Using bootstrap with 'row' container set to 'col-md-12'.

Handsontable 0.11.4
![image](https://cloud.githubusercontent.com/assets/5938098/5206352/675e8b56-7598-11e4-98c6-b1da0b3ff2af.png)

**Comment by AMBudnik** [comment]
@yannisps @josh18 could you please share a demo were we can replicate the issue (if it is still present in newest version)?
Thanks in advance!

**Comment by josh18** [comment]
Sorry this was such a long time ago I don't really remember anything about it. Free to close from my end.

**Comment by AMBudnik** [comment]
Thanks for prompt reply @yannisps 
I'm closing this issue.
