### ISSUE TITLE
how can i hidden primary key(id)

### ISSUE THREAD

**Issue by ldtec** [handsontable/handsontable#1937]
see title
$('#example td:nth-child(2),th:nth-child(2)').hide();
If I user this,the first column is hidden,but it's show Immediately！
What‘s wrong with this?

**Comment by budnix** [comment]
Hi, hiding/showing column feature actually doesn't exist in handsontable. To workaround this you can manipulate `colWidths` via `hot.updateSettings`. See demo http://plnkr.co/edit/lBmuxU?p=preview. Related issue https://github.com/handsontable/handsontable/issues/2020

**Comment by AMBudnik** [comment]
For further information, please track changes in #2020 issue.
