### ISSUE TITLE
Remove need for jQuery when validator and beforeChange is used

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1938]
In a rare but possible combination when developer uses call `validator` as well as `beforeChange` hook, the following code gets executed (core.js):

```
          $.when(result).then(function () {
            callback(); //called when async validators and async beforeChange are resolved
          });
```

Please use some other form of async code (maybe just callbacks) because jQuery is not a dependency for Handsontable anymore.

**Comment by jansiegel** [comment]
Released in 0.12.1
