### ISSUE TITLE
 0.12 display bug with bootstrap 3.3.1 css

### ISSUE THREAD

**Issue by jmariett** [handsontable/handsontable#1940]
Hi everyone,

when using handsontable 0.12 with bootstrap 3.3.1, there is a display bug. When editing a cell, instead of highlightning the cell, a small cell is created within the main one. Does anyone faced this probleme ?
there is a solution to have a clean display ?

thanks for your help,
jerome

**Comment by budnix** [comment]
@smitch88 Thanks for successful investigating. I added `box-sizing: content-box` to missing selectors. https://github.com/handsontable/handsontable/tree/feature/issue-1940

**Comment by okahara** [comment]
I'm still having this issue and when I use the suggested code to fix it

* {
box-sizing: content-box !important;
}

it changes all of my other inputs.  What selectors can I change or affect specifically so I do not have to use * ?
