### ISSUE TITLE
Cursor losses focus while scroll up and down using arrow up/down key in fixed column

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#1942]
Scroll up and down using keyboard arrow up/down key in fixed column loses cursor focus. Try the following action!:
1. Go to http://handsontable.com/demo/fixed.html 
2. Put your cursor in fixed column
3. Try to go up or down using keyboard arrow key up/down 
4. The first/last row could not be displayed and the cursor hides into that row
5. Everything is going well on the other unfixed columns 
Hopes this will be fixed in the future releases!

**Comment by jansiegel** [comment]
Fixed in ecc3cc4bf962fa5da5f051cc8fb2427e1d93b1ac and released in v.0.12.3.
