### ISSUE TITLE
repainting handsontable reculcates style several time (jagged behaviour on window.resize)

### ISSUE THREAD

**Issue by barneyRA** [handsontable/handsontable#1944]
![image](https://cloud.githubusercontent.com/assets/8241029/5242411/9157c916-7932-11e4-85fe-5c5439b1c17a.png).

there is an error or warning message when I profile the painting events in google chrome.
the time for repainting seems to be well over the 30ms / 60ms mark (which would be required to have a smooth user experience) resulting in a jagged behaviour when the window is resized.

Recalculate style and layout alternate in high frequencies. I think they should only be there once each (see printscreen).

this is my first post on github, so apologize if this should be in the wrong place for asking.

**Comment by AMBudnik** [comment]
Related #https://github.com/handsontable/handsontable/issues/1944

**Comment by swistach** [comment]
Hi @barneyRA,
In v7.0.0 we released improved refreshing of Handsontable after `resize` event.
I hope it'll help in your use case and sorry we didn't let you know before.
