### ISSUE TITLE
Horizontal scrolliing

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#1945]
Is there any way I can do the horizontal HOT scrolling by javascript.
I have 27 columns in my HOT and when the user press tab in col 11, I want the focus to shift to the 20th col by default.
Please advise.

**Comment by AMBudnik** [comment]
Please provide a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/)

**Comment by AMBudnik** [comment]
Issue closed - no reply for more than a month.
