### ISSUE TITLE
Invoking context menu throws errors

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1947]
When I try to invoke context menu by right-clicking between 1-3 pixels under the bottom border I see errors in the console:

> handsontable.full.js:9092 Uncaught TypeError: Cannot read property '1' of undefined
> handsontable.full.js:9595 Uncaught TypeError: Cannot read property 'destroy' of undefined

**Steps to reproduce the problem:**

- Go to http://handsontable.com
- Right-click slightly below the table (1-3 pixels)
- Check console logs

:information_source:
> Handsontable v. 0.12.0
> Windows 8.1
> Chrome v. 39.0.2171.65 m

![3px](https://cloud.githubusercontent.com/assets/8048526/5250509/17ac70f2-798d-11e4-8c67-eb270f4675e1.jpg)

**Comment by jansiegel** [comment]
Should be fixed with #1911
