### ISSUE TITLE
Memory leaks in the event manager

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1948]
There are some instances of EventManager which are not cleared in Handsontable `destroy()`. Thus, it is a serious memory leak.

I have added a test suite (MemoryLeakTest.js in `develop` branch). The test suite is launched as the last test in spec. According to the value, after the whole test suite is executed, there are 6640 not removed event listeners.

Potential candidates (may be wrong or incomplete):
- `plugins/removeRow/handsontable.removeRow.js` (`unbindMouseEvents` is only called on init, should also be called on `afterDestroy`)
- `src/editors/dateEditor.js` - `eventManager` is never cleared
- `src/editors/textEditor.js` - `eventManager` is never cleared
- `src/editors/mobileTextEditor.js` (on `feature/ply-59-merged` branch) - `eventManager` is never cleared

![screenshot 2014-12-01 22 35 43](https://cloud.githubusercontent.com/assets/566463/5253744/711e6c72-79aa-11e4-88bc-cb5c60379fbc.png)

Please uncomment test in `MemoryLeakTest.js` to reproduce the issue. 

**After fixing the problem, please keep this test uncommented so we can detect future memory leaks.**

**Comment by armensg** [comment]
I am using ngHandsontable and finding that there are many memory leaks still.
