### ISSUE TITLE
Firefox specific cell drag issue due to missing event param

### ISSUE THREAD

**Issue by smitch88** [handsontable/handsontable#1953]
The "afterInit" hook is missing an event param in the "mousemove" event listener which is throwing reference errors in firefox when I try to drag across cells. Chrome finds this automatically so its not throwing issues there.

@line 11919 in 0.12 unminified dist

eventManager.addEventListener(document,'mousemove', function ( *** MISSING event param *** ) {
      if (instance.dragToScrollListening) {
        dragToScroll.check( event.clientX, event.clientY);
      }
    });

**Comment by jansiegel** [comment]
@smitch88 You're right, thanks for reporting this!
