### ISSUE TITLE
Handsontbale drop down scroll issue

### ISSUE THREAD

**Issue by sindhushreeCELS** [handsontable/handsontable#1954]
![handson-dropdown-issue](https://cloud.githubusercontent.com/assets/10059419/5311390/3601d480-7c6b-11e4-9577-da1faa8bcd76.png)
![handson-dropdown-issue_1](https://cloud.githubusercontent.com/assets/10059419/5311391/360a844a-7c6b-11e4-8c1e-b64b46b4b2a9.png)

Hi,
I have dropdowns in table each gets data dynamically but the thing is am able to see list only when i scroll down because its hiding behind the container. Please find the screen shots that i have attached.

**Comment by krzysztofspilka** [comment]
@sindhushreeCELS Thanks for reporting, fix for that should be released on March 5.

**Comment by Niranjan24491** [comment]
Hello Chef, i guess the above mentioned issue by SindhushreeCELS hasn't been fixed yet in the latest release. Could you please let me know when i can expect a release?

**Comment by AMBudnik** [comment]
Please check [dropdown demo](http://handsontable.com/demo/dropdown.html). If your code acts different - please prepare a JSFiddle demo.

**Comment by ledjdm** [comment]
I made a demo with the problem and solution on #2483

**Comment by AMBudnik** [comment]
same issue as: https://github.com/handsontable/handsontable/issues/3435
