### ISSUE TITLE
Disable add new rows when dragging cells

### ISSUE THREAD

**Issue by andradobritoiu** [handsontable/handsontable#1955]
How can I disable the adding of new rows while dragging cells?

Tried setting  
           minSpareRows: 0,
            minSpareCols: 0,
            maxRows: 24,

But it doesn't work. Using version 0.12

**Comment by lucamaral** [comment]
Why did you close this issue?
Did you solve this problem?
Share with us your solution : )

**Comment by AMBudnik** [comment]
Oh... I can see that this issue is left unsolved.

For everyone seeking a solution for this case, I recommend the [`fillhandle` options](https://docs.handsontable.com/pro/Options.html#fillHandle). You just need to pass `false` for the `autoInsertRow` option.
