### ISSUE TITLE
Prevent new rows on paste?

### ISSUE THREAD

**Issue by paulo-raca** [handsontable/handsontable#1957]
I'm using handsontable to edit a table with a pre-determined number of rows.

Unfortunately, when I paste a number of rows larger than the number of rows, new rows are automatically added.

e.g.: Pasting a 15-line clipboard in a 10-line handsontable causes 5 new lines to be inserted

How can I disable this behavior and truncate the paste instead?

Thanks!

**Comment by cdeepak76** [comment]
maxRows: mydata.length worked liked a charm for me. Thanks donmccurdy.
