### ISSUE TITLE
Copying empty cells doesn't clear clipboard (Handsontable 0.12.0)

### ISSUE THREAD

**Issue by BryanMKramer** [handsontable/handsontable#1958]
Suppose cell B3 contains "some text". If I click on that, hit Ctl-C and then paste into notepad, "some paste" shows up. If I then select an empty cell, hit Ctl-C and then paste into notepad, "some text" is still pasted.

The expected behaviour is that a "copy" on an empty cell will replace the clipboard contents with an empty string. After all if I select several cells and copy, the change for the empty cells have a new value of "undefined" in JavaScript. 

Libre Office and Excel put an empty string in the clipboard when an empty cell is copied.

**Comment by budnix** [comment]
Hi,

This was fixed on the occasion of bug #1975
