### ISSUE TITLE
Context menu set width

### ISSUE THREAD

**Issue by giannis21kr** [handsontable/handsontable#1959]
I added the default context menu to my handsontable but the menu is deprecating some of the options that are too long. 
How can I set manually the contextMenu width to fit and show all elements properly?

**Comment by AMBudnik** [comment]
Please provide a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/), we'll see what we can do.

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/1895
