### ISSUE TITLE
Sorting arrows on Column headers

### ISSUE THREAD

**Issue by ashishg007** [handsontable/handsontable#1960]
The sorting arrows and the column highlighting when the column sorting is applied would be a nice feature and would help the user to easily figure out which column is used for the sorting of the table.

**Comment by aardeleanx** [comment]
Sorting arrows would be very useful to be included in the headers of columns.

**Comment by AMBudnik** [comment]
Please follow #2151 for further information, and as a issue for other suggestions related to appearance of sorted column header.
