### ISSUE TITLE
Truncation of column Headers not possible

### ISSUE THREAD

**Issue by ashishg007** [handsontable/handsontable#1961]
The current implementation of handsontable does not have truncation of column header text.

Please provide a solution for the same.

**Comment by AMBudnik** [comment]
If I got it right, you want to hide column header? If so, you can do it with ```colHeaders: false```. If that is not what you were looking for, please provide more info about this subject.

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply for more than a 1,5 month. If you would like to continue this issue - it's not a problem, we will reopen the issue after receiving a reply.
