### ISSUE TITLE
corner overlay misaligned when using only horizontal scrolling?

### ISSUE THREAD

**Issue by paulo-raca** [handsontable/handsontable#1963]
I want my  handsontable to have horizontal scrolling (I have lots of columns), but not on vertical (It can take as much vertical space as needed and use the page scrollbar)

I got it working: http://jsfiddle.net/4kd2dvmq/

Unfortunately, the corner overlay gets misaligned when I scroll to the right. How can I get it positioned properly?

**Comment by AMBudnik** [comment]
Can you provide information about your browser/system? I couldn't reproduce it on major browsers at mac.

**Comment by paulo-raca** [comment]
I couldn't reproduce it either. I guess it was fixed in the meantime?
