### ISSUE TITLE
Meteor.js and handsontable

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#1967]
Are there plans for a meteor (https://www.meteor.com/) implementation?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
