### ISSUE TITLE
"TypeError: obj is not an object" when sorting is enabled

### ISSUE THREAD

**Issue by miroslav-beranic** [handsontable/handsontable#1968]
Hi,

I get:
```
TypeError: obj is not an object
```
when I enable sorting:
```
 columnSorting: true,
```

It looks like sorting is working.

This error is shown in browser console after column is edited, selected, clicked, ... on all events I can tell.
Source:
```
function _generate(mirror, obj, patches, path) {
        var newKeys = _objectKeys(obj);
        var oldKeys = _objectKeys(mirror);
```

Stack:
```
_generate(mirror=[...] handson...full.js (line 8231)
generate(observer=Object { next=44, patches=[0], object=[19], more...})handson...full.js (line 8201)
observe/dirtyCheck()handson...full.js (line 8120)
observe/fastCheck/observer.next<()handson...full.js (line 8125)
```

On Version 39.0.2171.65, Ubuntu Linux 14.04 LTS, x64.

**Comment by AMBudnik** [comment]
Can you check if it still occurs? If so, we would realy appriciete a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/)

**Comment by AMBudnik** [comment]
issue closed in lack of an author's reply
