### ISSUE TITLE
Delay on reopening table v 0.12.1

### ISSUE THREAD

**Issue by andystat** [handsontable/handsontable#1969]
I'm having a problem when I paste into a handsontable, about 30 rows by 5 columns, with each cell saving as it is entered.
All seems well and I close the table but when I try to open it again there is a considerable delay, up to 30 seconds.
An error is reported "Cannot read property 'renderedToSource' of null" handsontable.full.js 17914 with further errors reported at 18297, WalkontableSelection.draw, 18268 WalkonTable.refreshSelections, etc down to callbackProxy at 3066.  It may be that this is not the cause of the delay.
![chrome_error](https://cloud.githubusercontent.com/assets/6353176/5339007/cf7d2dba-7f15-11e4-9b01-6f35c8280a08.png)

**Comment by AMBudnik** [comment]
We made some changes in Walkontable, can you please prepare a [JSFiddle](jsfiddle.net/api/post/library/pure/) for that issue?

**Comment by andystat** [comment]
HI.  Now I can¹t remember what the problem was and have rewritten my code so
that it doesn¹t seem to be an issue any more.  Sorry, I should have updated
this.

Thanks for letting me know.

Andy

From:  Aleksandra Budnik <notifications@github.com>
Reply-To:  handsontable/handsontable
<reply+0060f11861144fbdc544d3d3475ed62cf7d221d831c2552692cf00000001111ff9dc9
2a169ce030eb45e@reply.github.com>
Date:  Tuesday, 17 March, 2015 22:19
To:  handsontable/handsontable <handsontable@noreply.github.com>
Cc:  Andy Statham <andy@rapid36.com>
Subject:  Re: [handsontable] Delay on reopening table v 0.12.1 (#1969)


We made some changes in Walkontable, can you please prepare a JSFiddle
<jsfiddle.net/api/post/library/pure/>  for that issue?

‹
Reply to this email directly or view it on GitHub
<https://github.com/handsontable/handsontable/issues/1969#issuecomment-82377
351> .

**Comment by AMBudnik** [comment]
OK, thank you.
