### ISSUE TITLE
Add documentation to the source code (jsdoc)

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#1972]
Prepare source code to generate documentation based on jsdoc specification.

**Comment by warpech** [comment]
Review findings:

1 . Grunt script fails on Windows (tested with Git Bash):

```
$ grunt
Running "default" task

Running "exec:updateSrc" (exec) task
>> '[' is not recognized as an internal or external command,
>> operable program or batch file.
>> The syntax of the command is incorrect.
>> Cloning into 'src/handsontable'...

Running "less:dist" (less) task
File static/styles/jaguar.css created.

Running "clean:dist" (clean) task

Running "copy:css" (copy) task
Copied 1 files

Running "copy:js" (copy) task
Copied 1 files

Running "jsdoc:docs" (jsdoc) task
>> An error occurs in jsdoc process:
>> 'description' is not recognized as an internal or external command,
>> operable program or batch file.
Warning: jsdoc failure Use --force to continue.

Aborted due to warnings.
```

2 . I suggest to rename "Utils" nav section to "Internal"

3 . Actually I :heart_eyes: the outcome. My only problem is with `index.html`. You've put a lot of effort to create links to options and methods in JSDoc but still it is long, unreadable and unmaintainable. This page just needs some real design. 

The way I see it, the index page should be a 3-column layout, generated after JSDoc task. The outline of the design should be:

- Left nav *(copied from JSDoc)*
- Welcome message
- Handsontable API, grouped in 3 columns: 
  - Options *(here goes a list of links to Core options)*
  - Methods *(here goes a list of links to Core methods grouped into categories)*
    - General
    - Get data
    - Set data
    - Alter grid (create, remove rows and columns)
    - Cell
    - Selection
    - Grid information
    - Undo/redo *(shouldn't it be moved to plugin? then we reduce discoverability of these methods...)*
  - Hooks *(here goes a list of links to hooks)*

^ If you wish, I can draw a wireframe for the above outline

Now how do we populate the list of links to Options, Methods and Hooks? Of course with JavaScript, by reading from the left nav column! Thanks to that, it will automatically be up-to-date. It would be the best to do it server side (as grunt task, after grunt-jsdoc).

How do we know which methods belong to what category? The easiest would be to create a JSON file with a map of known method categories. Unmatched methods could be presented in an additional category called "Other".

4 . Once the above is done, I think that the static list of method links can be removed from `Handsontable.Core.html`

**Comment by krzysztofspilka** [comment]
Today we had a first internal meeting on this with @budnix , lots of conclusions!
