### ISSUE TITLE
Comments bugs

### ISSUE THREAD

**Issue by skibak** [handsontable/handsontable#1973]
1. I believe inside 
"DefaultSettings.prototype = {"
should be added "comments: false,"
otherwise this setting impossible to configure through ngHandsontable.

2. In last release comments are broken. It is reproducible in demo.
If you mouse over any cell with comment, tooltip with comment appear - this is ok. If you now in context menu click Add or Edit comment - nothing happens.
If after page load you don't mouse over cell with comment and select Add or Edit comment - edit comment popup will appear, but only once. If you try to click Add or Edit comment now - nothing happens.
This is probably because in line
eventManager.addEventListener(document, 'mousedown', Handsontable.helper.proxy(commentsMouseOverListener));
event should be changed to 'mouseover' (as it was in previous version).
But this doesn't completely solves the problem.

**Comment by AMBudnik** [comment]
Related to https://github.com/handsontable/handsontable/issues/2071

**Comment by AMBudnik** [comment]
Hi @skibak could you check how this steps relate with the newest version of Handsontable? There were some changes that might bring a different light on things.

**Comment by AMBudnik** [comment]
Issue do not occur in v0.28.3, demo: https://docs.handsontable.com/0.28.3/demo-comments_.html
