### ISSUE TITLE
How to save comments and formats?

### ISSUE THREAD

**Issue by haoting2000** [handsontable/handsontable#1974]
As some of other friends ask, I am confused on how to  save comments and cell formats to server database. 
If I merge 4 cells , how can save this action to database?  
If I add comments to A1, how to save it?

Thanks for helping me.  

Handsontable is a great products

**Comment by dharmender17** [comment]
I am still not able to find an answer.Can anyone help in this case.

**Comment by dp81** [comment]
Did you manage to find the solution?

**Comment by dellert** [comment]
So we still have no solution for that question?

**Comment by AMBudnik** [comment]
Most of the changes borders/merging/comments can be seen in the DOM that why it's possible to check which cell has a comment/border etc. and by that build a data base for specified cells although we don't provide an example how to do this.

**Comment by budnix** [comment]
This is the [solution](http://jsfiddle.net/77hfe50a/1/) that came to my mind now.

**Comment by dellert** [comment]
budnix, ya, but there are too many other factors: styles, colspans, rowspan etc. And problem not just in save all those data. After save I wanna load data back to pae and build same table.

P.S. sorry for my english)

**Comment by AMBudnik** [comment]
We have it on mind but it's an idea for further future.

**Comment by wuganzhi** [comment]
> We have it on mind but it's an idea for further future.

Has this need been addressed? I also need to store all operations (merge, background color, column width, etc.) in the database to ensure that every change is echoed.

**Comment by AMBudnik** [comment]
>Has this need been addressed?

Partially. We're working on a [Spreadviewer project](https://handsontable.com/spreadsheet-viewer/) which will also allow passing the comments and metadata but it will take some time to finish it and use the logic in Hansdontable itself.

**Comment by wuganzhi** [comment]
> > Has this need been addressed?
> 
> Partially. We're working on a [Spreadviewer project](https://handsontable.com/spreadsheet-viewer/) which will also allow passing the comments and metadata but it will take some time to finish it and use the logic in Hansdontable itself.

I am trying to use the existing API to complete the requirements, but this is very difficult, and I hope that the requirements saved in the database can be improved as soon as possible. Thank you very much for your answers!
