### ISSUE TITLE
Scroll Table Header Moving - Only in IE

### ISSUE THREAD

**Issue by prabhuish** [handsontable/handsontable#1976]
I am noticing the headers are moving (or flickering) in IE (v11), even with 0.12.2.. For an E.g... Please open http://handsontable.com/demo/scroll.html in IE and see "Single Srollbar - stretchH Columns" section... When I scroll the table the header is  flickering.. but it works perfect in Chrome (v39). Can you please advice me how to fix this issue in IE.

**Comment by AMBudnik** [comment]
Please track changes on https://github.com/handsontable/handsontable/issues/1761 in this subject
