### ISSUE TITLE
Column Order no work properly

### ISSUE THREAD

**Issue by guillermogallego** [handsontable/handsontable#1977]
In column with ascendent order show wrong order

87677
85907
3669
329329

The column is set to

columns:[
        {data:"id_producto",type:'numeric',readOnly:true}
]

**Comment by AMBudnik** [comment]
Can you please provide a demo for this issue? I've made everything like you wrote in this [JSFiddle](http://jsfiddle.net/ztoakp2g/) and it sorts as expected.

**Comment by AMBudnik** [comment]
There is a lack of reply recently so I deduce this issue was solved by author.
