### ISSUE TITLE
Disable table clone

### ISSUE THREAD

**Issue by duccoder** [handsontable/handsontable#1978]
I don't need sticky header top, left (`ht_clone_corner`, `ht_clone_top`, `ht_clone_left`). So how to not render it? 0.12.1

**Comment by AMBudnik** [comment]
Hi @bipholai if you still experience this issue, please prepare a little [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/) to let us know more.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
