### ISSUE TITLE
Merged Cells are not Shifting during insert/remove - row/col.

### ISSUE THREAD

**Issue by Mazzzy** [handsontable/handsontable#1983]
1. If you try to "insert row above" the merged Cell, then blank row gets added but the position of merged cell still remains the same. Expected Result: It need to shifted one row down as new blank row gets added.
2. Similarly, if you try to "insert col left" to the merged Cell, then blank col gets added but the position of merged cell still remains the same. Expected Result: It need to shifted one col left as new blank col gets added.

Steps for "insert row above"  issue : 

![insert_rowabove_step1](https://cloud.githubusercontent.com/assets/6522070/5434089/0e29d898-8474-11e4-8969-12f7d5063010.jpg)

![insert_rowabove_step2](https://cloud.githubusercontent.com/assets/6522070/5434091/14046544-8474-11e4-9db3-6a04015cf867.jpg)

Steps for "insert col left"  issue : 

![insert_colleft_step1](https://cloud.githubusercontent.com/assets/6522070/5434097/27a82d56-8474-11e4-9200-0afcd9370e9b.jpg)

![insert_colleft_step2](https://cloud.githubusercontent.com/assets/6522070/5434099/2cd833de-8474-11e4-88ba-c65661506603.jpg)

**Comment by AMBudnik** [comment]
Please follow this issue on #2080 as a milestone candidate
