### ISSUE TITLE
hidden long text on cell

### ISSUE THREAD

**Issue by hotboyconvoi** [handsontable/handsontable#1984]
i made a table more cell with long text, and set colWidths small when scrolling right. but text on cell didnt hidden, it toke more height?
i need a help.
thank you

**Comment by AMBudnik** [comment]
Hi @hotboyconvoi please provide a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/)

**Comment by AMBudnik** [comment]
issue closed in lack of needed demo
