### ISSUE TITLE
Add an option ScrollToCell

### ISSUE THREAD

**Issue by phcorp** [handsontable/handsontable#1986]
When a user clicks on a cell or starts to edit its content, the viewport scrolls to the cell's coordinates.
Sometimes (in my case), this behavior is not suitable.
Could you add an option to handsontable to disable this feature?
Thank you in advance,

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Feature added as a [scrollViewportTo](https://docs.handsontable.com/0.31.0/Core.html#scrollViewportTo) method
