### ISSUE TITLE
Add `Handsontable.version`

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#1988]
It should be possible to check the version of Handsontable in the browser console using `Handsontable.version`.

It works with other libraries, such as:
- `jQuery().jquery` ([jQuery](http://jquery.com/))
- `angular.version` ([AngularJS](https://angularjs.org/))
- `Highcharts.version` ([Highcharts](http://www.highcharts.com/demo))

**Comment by budnix** [comment]
Introduced together with the modularization.

**Comment by budnix** [comment]
https://github.com/handsontable/handsontable/issues/2072
