### ISSUE TITLE
getBoundingClientRect does not work in modal dialogs

### ISSUE THREAD

**Issue by Rouby** [handsontable/handsontable#1991]
I have a bootstrap3-dialog (https://github.com/nakupanda/bootstrap3-dialog) and inside of that a hot instance. The manual column movers and resizer do not get positioned correctly because it seems like getBoundingClientRect (used in refreshHandlePosition) does not get the offsets right,

is this an issue with hot, my layout, bootstrap3-dialog or general bug in getBoundingClientRect?

**Comment by alexyaseen** [comment]
They also don't seem to work when the handsontable instance is at some point inside of a div that scrolls

**Comment by AMBudnik** [comment]
For issues that does not describe Handsontable bugs, but relations with other libraries please create a topic at [stackoverflow](https://stackoverflow.com/search?q=handsontable) with a `handsontable` tag.
