### ISSUE TITLE
Fixed column header height causes row misalignment

### ISSUE THREAD

**Issue by davidity** [handsontable/handsontable#1992]
Handsontable 0.12.2

The problem occurs when the height of the header row for fixed columns differs from the height of the header row for non fixed columns. This includes the case when using row numbering which behaves like a fixed column.

Example, one fixed column with row height due to single line of text in header followed by non fixed columns with at least one header with two lines of text. The rows of the fixed vs unfixed columns will be off by a row.

![image](https://cloud.githubusercontent.com/assets/1062887/5480778/70f89686-85fe-11e4-927f-4b2a7b55b18c.png)

**Comment by AMBudnik** [comment]
For further information, please track changes in https://github.com/handsontable/handsontable/issues/1681 issue.
