### ISSUE TITLE
Wrong context menu position

### ISSUE THREAD

**Issue by rizkyramadhan** [handsontable/handsontable#1993]
In handsontable context menu demo page, when context menu show above cursor, its position is a little bit to high. see image below: 

![screen shot 2014-12-21 at 10 38 22 am](https://cloud.githubusercontent.com/assets/126301/5517082/97449acc-88fd-11e4-903e-d3fec10dc755.png)

But menu position is correct when it shows below cursor, 
Try it here: http://handsontable.com/demo/contextmenu.html

**Comment by AMBudnik** [comment]
I couldn't reproduce it in any browser. Please reply if it still occurs, and describe a browser versions also.

**Comment by johnSchnake** [comment]
https://github.com/handsontable/handsontable/pull/1999
I was able to reproduce this; and made a small fix to it. If no one else has the problem though I'll just close my PR.
