### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by danio7** [handsontable/handsontable#1997]
Hello,
 
I really like this widget! Very impressive. I just had a few questions.
 
1) I'd like to highlight a cell after it has been changed, but I run into 2 problems with the following code :
                1) it highlights the cell I click on to get out of an edit, and not the cell that was just edited.
                2) The highlighted cell color disappears if I move the table or perform any other commands.
 
            afterChange: function (changes, source) {
                if (source !== 'loadData' && changes[0][3] != changes[0][2]) {
                    var td = HOT.getCell(HOT.getSelected()[0], HOT.getSelected()[1]);
                    td.style.background = '#f0fff0';
                }
            },
 
2) Every time I perform a new search, I do : HOT.loadData(data). I noticed the event listeners keep going up and never reset. What is the proper way to clear the data and listeners to reload new data?
 
Thanks a lot!

**Comment by AMBudnik** [comment]
Please prepare a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/) for that issue.

**Comment by danio7** [comment]
I prepared a demo but I can't reach the handsontable variable in the console. But if you type the variable name of the current handsontable, you will see the number of events, the more you interact with the table, the more the events go up. Sorting for instance, has this effect.

**Comment by AMBudnik** [comment]
Hi @danio7 do you still face this issue after updating to 0.15.1?

**Comment by danio7** [comment]
I am not sure as I stopped using handsontable.

 

Thanks.

**Comment by AMBudnik** [comment]
If you would have any other questions, feel free to leave a feedback.
