### ISSUE TITLE
Navigate left/right with arrow keys

### ISSUE THREAD

**Issue by andreas-ku** [handsontable/handsontable#20]
Hi!

You really created an awesome plugin, thank you very much for hosting it on github.

I found a small usability issue: currently it is not possible to switch to the table cell left/right of the cell I am currently editing using the arrow keys. Of course this is a minor issue, but I guess people will expect that to work the same way it does in Google docs or Excel.

Cheers Andreas

**Comment by xasp** [comment]
I noticed this no longer works (Handsontable 0.15.1).
I've implemented this functionality using the beforeKeyDown hook, for those interested : see http://tri-s.be/blog/2015/7/3/arrow-navigation-in-handsontable.aspx
