### ISSUE TITLE
Callback for custom drag down autofill

### ISSUE THREAD

**Issue by Zauberfisch** [handsontable/handsontable#200]
when you have the cols 11, 12, 13 the autofill will repeat the pattern to 11, 12, 13, 11, 12, 13

it would be nice to be able to hand a callback to the table that overwrites the basic repeat behaviour

**Comment by felixhagspiel** [comment]
@warpech sorry for replying on this again, but I dont understand how that event gives us the ability to change the behaviour of the autofill. As I understand the 'beforeAutofill' callback gives us only information about the cells and the pattern, but it does not give us the ability to change it. Neither can we stop the autofill. So what we have to do is to read the pattern, then wait until the cells are filled by autofill, and then overwrite them manually. Is there a better way, i.e. returning a callback with the new values for the cells? Sorry if I have overseen something.

**Comment by sasuke37** [comment]
hi ,
i have a problem with the autofill :

![sans titre](https://cloud.githubusercontent.com/assets/6151318/13358005/5e8ddd38-dcad-11e5-9d1b-4b2c37452b84.png)

Anyone have a solution for my problem??

**Comment by AMBudnik** [comment]
Hi @sasuke37 you're using ngHandsontable and formulas? (as I can see in your console)
Can you share a demo where this issue is replicable?
