### ISSUE TITLE
How to prevent "stickiness" of the table header?

### ISSUE THREAD

**Issue by hellovijayr** [handsontable/handsontable#2000]
Looks like in the latest version, the table header "sticks" to the top of the page.  This is great when there is only one table, but not so great when we have more than one table.  For example, assume there are two hands on tables on a page, and the first one is bigger (in terms of width and number of columns) than the second one.  When the user scrolls down the page, the second table's header is going to stick to the top - since the second table is smaller than the first, part of the header of the first table also shows up.

Is there any way to prevent the stickiness altogether?

**Comment by hellovijayr** [comment]
Any updates on this? I was looking through the code, I can do some monkey patching - but would be nice to have a proper fix. Also, it looks like this feature was added in the recent release.

**Comment by moJiXiang** [comment]
Need a flag to turn on or turn off the header stick.

**Comment by jacksontong** [comment]
How could this mark as answered?

**Comment by AMBudnik** [comment]
Hi @jacksontong Author closed the issue and I marked it with a label as `answered`.

If you would like to discuss the case, please contact us at support@handsontable.com or open a new thread (as this one is from 2018).
