### ISSUE TITLE
Hiding and expanding div causes UI issues with handsontable

### ISSUE THREAD

**Issue by hellovijayr** [handsontable/handsontable#2001]
Assume a handsontable inside a div.  The user can collapse/expand the div (hide/show).  When the div expands, the table doesn't show up.  If I scroll up/down the page, then the table shows up.

This doesn't happen all the time though - but happens frequently enough.  This is on Chrome (not sure about other browsers)

**Comment by dbbbit** [comment]
#2062 this maybe the same problem?

**Comment by AMBudnik** [comment]
Yes, for further information please check #2062 issue.
