### ISSUE TITLE
Comments rendering breaks with columnSorting: true

### ISSUE THREAD

**Issue by mikesvk** [handsontable/handsontable#2003]
In latest version comments will not render if 'columnSorting' is set on 'true'. Reproducible with demo configuration, just add 'columnSorting: true'. For example:
```javascript
 ...
		columnSorting: true,
		comments: true,
		cell: [
			{row: 1, col: 1, comment: "Test comment" },
			{row: 2, col: 2, comment: "Sample" }
		]
 ...
```

**Comment by AMBudnik** [comment]
Thanks for reporting this issue.

**Comment by thbar** [comment]
Reproduced in [this fiddle](http://jsfiddle.net/thbar/7e6q5gwj/1/).

**Comment by thbar** [comment]
@mikesvk by any chance, did you find a work-around for this? Did you maybe used a custom tooltip instead of built-in comments etc? Thanks for your hints!

**Comment by thbar** [comment]
I was able to work-around the issue using the `cells` callback:

```coffeescript
@hot = new Handsontable(container,
{
  # snip
  columnSorting: true
  comments: true
  cells: (row, col, prop) =>
    props = {}
    if condition
      props.comment = "message"
    props
}
```

**Comment by AMBudnik** [comment]
works as expected in 0.24.1. Please check the demo: http://jsfiddle.net/7e6q5gwj/2/
