### ISSUE TITLE
Turn into webcomponent

### ISSUE THREAD

**Issue by aidanlister** [handsontable/handsontable#2004]
It would be cool if you could provide handsontable as a webcomponent (http://webcomponents.org/) using Polymer (https://www.polymer-project.org/) which is Google's library for web components.

I think there'd be some nice benefits as the handsontable would then be within a shadowdom node, meaning the site's styles aren't going to affect the handsontable.

You'd get some performance improvements as well as the shadowdom is encapsulated, so you're not leaking performance due to the site's CSS or JS matching on anything.

What do you think -- worthwhile? It certainly seems to be the direction the web is heading.

**Comment by warpech** [comment]
Thanks for the tip! It is already done :) https://github.com/handsontable/hot-table
