### ISSUE TITLE
rowHeaders keep fixed size when header or cell is more than one line.

### ISSUE THREAD

**Issue by majj** [handsontable/handsontable#2005]
if header or cell is more than one line, the upper rowHeaders didn't change accordingly

Handsontable 0.12.2

ngHandsontable 0.5.0

![handsontable03](https://cloud.githubusercontent.com/assets/543810/5555957/793338f8-8d04-11e4-848c-9586e89fdc31.png)

**Comment by AMBudnik** [comment]
For further information in this subject please follow https://github.com/handsontable/handsontable/issues/1681 issue.
