### ISSUE TITLE
Fixed column headers getting scrolled in Release 0.12.2

### ISSUE THREAD

**Issue by banwait-amarjeet** [handsontable/handsontable#2006]
I am using latest release 0.12.2 and I found top overlay is not fixed
I just clicked on column header and then scrolled, top overlay is getting scrolled.(should be fixed)

This bug can also be found in Handsontable demos
![fixed column headers are not fixed](https://cloud.githubusercontent.com/assets/4598234/5557349/1318cbfc-8d20-11e4-9610-ab995f780c5a.PNG)
Here I just clicked on column header and then performed scrolling.

**Comment by PassHours** [comment]
I am getting a feeling that this 0.12.2 release has more bugs than fixes...
Here there is another : https://github.com/handsontable/handsontable/issues/2013
 I am sure the HOT team will address these issues in the next releases and will give a more stable version..

**Comment by warpech** [comment]
I will review this.

**Comment by warpech** [comment]
Code review OK, ready to merge

**Comment by banwait-amarjeet** [comment]
Thanks Team,
Seems working fine at Handsontable demos. I will update my HOT version soon. :+1:
