### ISSUE TITLE
Can't use sortIndex map.

### ISSUE THREAD

**Issue by aschmois** [handsontable/handsontable#2007]
No matter what I do, sortIndex map is always undefined. Here are my settings:
```javascript
  hot = new Handsontable(container, {
    data: items,
    startRows: 1,
    minSpareRows: 1,
    colHeaders: COL_HEADERS,
    columns: columns,
    manualRowMove: true,
    columnSorting: true,
    currentRowClassName: 'currentRow',
    currentColClassName: 'currentCol',
    beforeChange: setBeforeChange(),
    afterChange: setAfterChange(),
    afterValidate: afterValidate(),
    comments: errors,
    autoWrapRow: true,
    enterBeginsEditing: true,
    search: {
      searchResultClass: 'customClass'
    },
    stretchH: "all",
    contextMenu: getContextMenu()
  });
```

Accessing sortIndex in customRender is always null, whether I've sorted a column or not.
```javascript
function getCustomRenderer() {
  return function(instance, td, logicalRow, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    var physicalIndex = logicalRow;
    if(this.sortIndex != null) {
      physicalIndex = this.sortIndex[logicalRow][0];
      console.log(physicalIndex);
    }
...
```
(I've tried using, instance, this, and the hot var itself, always null)

**Comment by budnix** [comment]
It looks like it works. I have created demo based on newest version of handsontable and `sortIndex` is exists in custom renderer (see http://plnkr.co/edit/nEY5um?p=preview).

**Comment by warpech** [comment]
@douxlagithub could you help us reproduce it issue? In the above plnkr it seems to work. Are you using the Handsontable 0.12.2?

**Comment by douxlagithub** [comment]
I used Handsontable 0.12.0 since then. I did not upgrade my handsontable to 0.12.2 because there isn't a specific description about row index changes in Change Log both in 0.12.1 and 0.12.2. I recently upgraded to 0.12.2 and It works great now. Thank you very much.
