### ISSUE TITLE
Column sorting issue: [Wrong data row index after column sorting]

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#2008]
Hi everybody. Big thanks to all handsontable developer team that has been supported me for years with this 
fantastic data grid. Again an issue comes up on top of my project. The problem is "Wrong data row index after column sorting"
Reproduce.
I tried the following steps:
1. Modify demo/html.php add [columnSorting: true] to handsontable setting
2. Go to http://your.localhost/handsontable/demo/php.html [or activate your php.html demo]
3. After your php.html demo is ready try to sort "Year" column. Make sure your Autosave is checked.
4. After sorted your Jaguar should be in the last row. Then change Jaguar Year to 2000
5. After it autosaved. Refresh your browser then check your Jaguar!
6. The year of Jaguar doesn't change
7. The row position of recently changed data [2000] doesn't change
8. The changed data saved into a wrong row
--------------- Help Please! -----------------------

**Comment by budnix** [comment]
This was demo/php.html bug. After row transform based on `sortIndex` was added, it saves into correct row (http://plnkr.co/edit/6rbSeT?p=preview). I updated the demo/php.html page (https://github.com/handsontable/handsontable/commit/b8c4a0d409f99dc113df48fe510ac4ea6f0ab2e3)

**Comment by douxlagithub** [comment]
The problem is now fixed in newest version of handsontable. Thanks a lot.! Cheers all...

**Comment by benjamin-meyers** [comment]
I have tried all the suggestions listed but still am seeing the wrong row index inside afterValidate.  After a column is sorted the row index returned cannot be interpreted.  I tried using sortIndex but this just returns another row index I cannot interpret.  

r = hot.sortIndex[r][0]; //Wrong index to start and after calling sortIndex
