### ISSUE TITLE
Cannot set property 'isPrintableChar' of undefined

### ISSUE THREAD

**Issue by HedCET** [handsontable/handsontable#2009]
currently i am using handsontable with meteorjs

it shows some error
handsontable.js:4388 => Uncaught TypeError: Cannot set property 'isPrintableChar' of undefined

but it works perfectly - Handsontable as global variable
/ *var * / Handsontable = function (rootElement, userSettings) { // line 18

is there any problem in this kind of edited usage (line 18) dist/handsontable.full.js ?

**Comment by HedCET** [comment]
https://github.com/meteor/meteor/issues/3454#issuecomment-69463592

**Comment by AMBudnik** [comment]
I saw you resolved this issue on [Meteor's issue](https://github.com/meteor/meteor/issues/3454#issuecomment-69463592) that's why I may close this issue, but feel free to write back with any questions.
