### ISSUE TITLE
Hide specific row

### ISSUE THREAD

**Issue by saji89** [handsontable/handsontable#2010]
I have checked the existing bugs, and discussions related to this feature. None of this was closed after a proper or official solution, but mostly workarounds or oneoff usages. It would be nice to have a feature to hide a row by specifying the row number, or an array of row numbers.

I was actually looking the possibility of any row renderers, or row walk, which will allow us to specify class or style to the row(s), we require.

**Comment by AMBudnik** [comment]
Related to #2020

**Comment by davidleroy** [comment]
+1

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Feature added to Handsontable PRO as [Hiding](https://docs.handsontable.com/pro/demo-hiding-rows.html) (also [available for columns](https://docs.handsontable.com/pro/demo-hiding-columns.html))
