### ISSUE TITLE
Window does not change focus when tabbing to a cell outside the viewport

### ISSUE THREAD

**Issue by dataqueen42** [handsontable/handsontable#2011]
This is related to issue [151](https://github.com/handsontable/handsontable/issues/151).

I have a very wide table that extends outside the viewport, and when I tab to those cells, the window does not refocus unless I press Enter to start editing the cell.

It seems that this was fixed per issue 151, but the desired behavior is broken again.

**Comment by AMBudnik** [comment]
If you would have any other questions or if this answer above doesn't solve your issue, we are open to help.
