### ISSUE TITLE
Bug: manualRowMove  and context menu options does not work together

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#2013]
Have anyone experienced that if any row gets added/removed (contextMenu: ['row_above', 'row_below', 'remove_row']) on the HOT then the manualRowMove option doesn't work any more for the entire HOT or behaves abnormally.

Please check this fiddle : http://jsfiddle.net/bcm3uk62/

I guess this is a bug that needs to be addressed or is there a workaround?

**Comment by PassHours** [comment]
Is this issue resolved in this 12.3 issue? OR is pending for next release?

**Comment by jansiegel** [comment]
This bug should be fixed in #2028 and will be released in the next version of Handsontable (0.12.4).

**Comment by AMBudnik** [comment]
Fixed with https://github.com/handsontable/handsontable/issues/2028
