### ISSUE TITLE
Add comment from Context Menu doesn't work

### ISSUE THREAD

**Issue by rizkyramadhan** [handsontable/handsontable#2014]
In handsontable comments demo page, When we click "Add Comment" in context menu nothing happens. "Delete Comment" works though..

Try it here: http://handsontable.com/demo/comments.html

This is handsontable basic feature, I think we should have an automated test to spot this kind of issue.

**Comment by bilogic** [comment]
Editing comments is also not persistent, it reverts back to the original comment

**Comment by AMBudnik** [comment]
Thanks for reporting, we're still in beta mode in merging so few issue can be related to this one, like #1973, so please track changes for this subject in mentioned issue.

**Comment by everlightmfg** [comment]
i didnt catch such thing <a href="http://www.everlightmfg.com/lighting/led-work-light/">LED work light</a>
