### ISSUE TITLE
documentation needs updating?

### ISSUE THREAD

**Issue by kc1** [handsontable/handsontable#2016]
On https://github.com/handsontable/handsontable/tree/master/dist. 

It refers to for example "jquery.handsontable.full.js" but the files are for example "handsontable.full.js" . I've run into a problem including these files locally ( http://stackoverflow.com/questions/27722514/paths-not-working-to-handsontable-js-and-css ), which may or may not be related.

**Comment by krzysztofspilka** [comment]
@kc1 Thanks for reporting, admittedly we need to update README file asap.
