### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by hqbobo** [handsontable/handsontable#2018]
this piece of code is actual from example .
i just put it on my web server.

any ideal how it happens?

![5nvh_ f y9b2gk8btg2ueu7](https://cloud.githubusercontent.com/assets/10349627/5591954/32f942a4-91de-11e4-9191-dd60004b4b43.jpg)

thx

**Comment by chris-vr** [comment]
I also had that double blue border in edit mode and it came right when I put `<!DOCTYPE html>` at the top of my page.

**Comment by hqbobo** [comment]
i fix it with change in source code..

**Comment by jansiegel** [comment]
@hqbobo Did @chris-vr suggestion helped? Leaving the doctype unspecified may cause some glitches - including font size changes, which probably caused the effect you provided.

**Comment by AMBudnik** [comment]
If you would have any other issues feel feel to write.
