### ISSUE TITLE
Hiding columns from javascript

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#2020]
Is there any way i can hide HOT columns from javascript?
The requirement is such that the column to hide will come as a parameter in javascript and based on that the respective column will show hide accordingly.

The HOT has rowHeaders and colHeaders and the data with 20 columns.

Please advise.

**Comment by budnix** [comment]
Hi, unfortunately this feature doesn't exist in handsontable but I think that it is good idea to implement this in near future. To solve this problem as workaround you can manipulate `colWidths` via `hot.updateSettings({colWidths: [100, 100]})`. I prepared working demo at http://plnkr.co/edit/lBmuxU?p=preview

**Comment by PassHours** [comment]
Thanks... it worked.

**Comment by mabd91** [comment]
It is worth mentioning that you can also use the 'columns' setting property to choose which columns are visible.
See this issue for more details: https://github.com/handsontable/handsontable/issues/653

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Feature added to Handsontable PRO as [Hiding](https://docs.handsontable.com/pro/demo-hiding-columns.html) (also [available for rows](https://docs.handsontable.com/pro/demo-hiding-rows.html))
