### ISSUE TITLE
Question/Enhancement: Tabbing into and out of HandsOnTable

### ISSUE THREAD

**Issue by RKlante** [handsontable/handsontable#2022]
Currently, HandsOnTable does not seem to be treated as a focusable or tabbable element.
Hence, the table is ignored while navigating through a page using the keyboard, specifically the tab key.

Is there any option or known way to accomplish tabbing into (and selecting the first cell/previously selected cell) or out of (selecting the next element in taborder, be it another HandsOnTable or some other element) a HandsOnTable?

I'm sure the second can be accomplished by some custom handling of the beforeKeyDown event and searching the next focusable element. But i'm really stuck with ideas concerning the first requirement.

Any help is greatly appreciated!

**Comment by AMBudnik** [comment]
Related to https://github.com/handsontable/handsontable/issues/1652
