### ISSUE TITLE
Simplify preCalculator/calculator

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#2023]
(Depends on HOT-61)

Currently it is not always clear what is the difference between `preCalculator` and `calculator` in Walkontable.

- `rowsPreCalculator`, `columnsPreCalculator ` -> rename to `rowsRenderCalculator`, `columnsRenderCalculator`
- `rowsCalculator`, `columnsCalculator ` -> rename to `rowsVisibleCalculator`, `columnsVisibleCalculator`
- `rowsRenderCalculator`, `columnsRenderCalculator`, `rowsVisibleCalculator`, `columnsVisibleCalculator` -> only have properties `start`, `end` (not renderStart, renderEnd, visibleStart, visibleEnd etc)

**Comment by warpech** [comment]
@kubak10 please review

**Comment by jansiegel** [comment]
Released in 0.12.3
