### ISSUE TITLE
Handsontable code assumes one table instance per page

### ISSUE THREAD

**Issue by rjansen72** [handsontable/handsontable#2025]
We are attempting to use multiple handsontable instances on a single page. For the most part this works, but we noticed that when resizing columns, or moving columns around, that other tables were being impacted. After diving through the code a bit, the following scopes are executed once per page and they utilize member variables that are shared across all table instances:

HandsontableManualColumnMove
HandsontableManualColumnResize
HandsontableManualRowResize
HandsontableManualRowMove

I'm hoping to work around this in my app, but would like to see this fixed natively inside this framework. I don't know if there are other parts of the code that make this same assumption.

**Comment by rjansen72** [comment]
I developed a fix for this issue in a side branch. I'll look into creating a pull request shortly.

**Comment by PassHours** [comment]
Can I expect this fix in the next HOT release. Multiple instance of HOT in a single page is one my requirement as well.

**Comment by PassHours** [comment]
Is this issue resolved in this 12.3 issue? OR is pending for next release?

**Comment by alexyaseen** [comment]
I'm also experiencing this issue. I'm considering embedding each instance in an iframe, but that shouldn't be necessary.

@warpech @jansiegel @krzysztofspilka plan to fix this or should we plan to work around it?

**Comment by AMBudnik** [comment]
Thank you all for support, let us take a closer look at this issue.

**Comment by AMBudnik** [comment]
It is possible to use those options with two tables like [here](https://jsfiddle.net/cmtrcdgm/) If that's not what you were looking for - give us a feedback.

**Comment by AMBudnik** [comment]
If you would have any other questions, please feel free to write us back. Till this would happen - issue will stay closed in lack of recent activity.

**Comment by stemcc** [comment]
Hey AMBudnik, the fiddle you provided on April 10 no longer works and I'd love to see it in action as I'm trying to figure out two tables on a single page as well.

**Comment by AMBudnik** [comment]
Hi @stemcc here's the code http://jsfiddle.net/srovptvg/
