### ISSUE TITLE
reconsider jquery

### ISSUE THREAD

**Issue by rjansen72** [handsontable/handsontable#2027]
I'm finding several issues related to element placement and scrolling; I've noticed others have reported similar problems (https://github.com/handsontable/handsontable/issues/1970)

comments in handsontable.dom claim this was done for performance reasons, but faster performance with incorrect results isn't helpful.

**Comment by warpech** [comment]
#1970 will be fixed in the upcoming release (0.12.3). 

Thanks for your opinion, but returning to jQuery is not an option. Compatibility with jQuery (through jQuery plugin API) will be continued though. See http://handsontable.com/demo/jquery.html
