### ISSUE TITLE
The context menu breaks the manualColumnResize

### ISSUE THREAD

**Issue by kkrusty1** [handsontable/handsontable#2028]
Check this fiddle:
http://jsfiddle.net/r879qc3p/

When the page loads, you can resize the columns as you wish. Right-click anywhere on the table to show the context menu (you don't have to choose an item) then left-click somewhere else to hide the context menu. The columns cannot be resized anymore.

**Comment by andres-b** [comment]
If you add manualColumnMove: true the same applies.

**Comment by PassHours** [comment]
https://github.com/handsontable/handsontable/issues/2015

**Comment by brentjulson** [comment]
I saw this same issue in latest release (12.2). In my case, I resolved it by moving back to 11.4 where this doesn't appear to be an issue.

**Comment by brentjulson** [comment]
I traced it back, the context menu is implemented as an instance of Handstontable. When the contextmenu is created, the init method for HandsontableManualRowResize and HandsontableManualColumnResize are invoked and this line of code executes "unbindEvents.call(this);". The eventmanager appears to be singleton, so this call removes the previously registered event listeners for this functionality on the main Handsontable instance. Just learning this library, so not sure the proper way to fix but figured I'd share. Commenting it out will resolve the issue, but I imagine introduces the potential for a leak of some sort.

**Comment by jansiegel** [comment]
Confirmed, thanks for reporting!
