### ISSUE TITLE
Not compatible with Angular Material CSS

### ISSUE THREAD

**Issue by PhilAndrew** [handsontable/handsontable#2031]
Hi there, I am using handsontable with Angular Material here https://material.angularjs.org/#/

I found that the edit box looks wrong size when editing a field in the table, its too small, the fix I added was.

```
hot-table * {
  box-sizing: content-box;
}
```

In the above, hot-table is my angular tag. Although, I am sure other CSS libraries cause problems with HandsOnTable, this fix is simple, maybe you could consider to add the box-sizing: content-box; to your CSS which would prevent this problem from happening to other people?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
This issue was created a long time ago. Currently, it seems that it works well (I've built a local app and tested most of the features).
If anyone finds it malfunctioning, please contact me at support@handsontable.com
