### ISSUE TITLE
duplication of headers when data is upadted from the backend

### ISSUE THREAD

**Issue by shilpa-sharma** [handsontable/handsontable#2032]
we are using multiple Handson table on a single webpage. Whenever the data is updated from the backend and rendered in the table there is duplication of headers below is the screenshot of the same.. the version of handson table used is 0.11.4
![error](https://cloud.githubusercontent.com/assets/10464417/5680823/810bebba-9812-11e4-9416-a2ff81f6e0da.PNG)

**Comment by AMBudnik** [comment]
Please reply if it still occurs after updating to 0.12.6 or newer?

**Comment by AMBudnik** [comment]
Could any one of you create a demo or just check if this issue still occurs in 0.24.1 
I was unable to test it. Thanks in advance!

**Comment by shilpa-sharma** [comment]
hey,

I am not getting this issue since version 0.12.6 and it wasn't replicated after further updates to newer version.  You can mark this issue as closed.

**Comment by AMBudnik** [comment]
thanks for feedback @shilpa-sharma
