### ISSUE TITLE
manualColumnResize causes numeric validation grid bug when column moved.

### ISSUE THREAD

**Issue by danio7** [handsontable/handsontable#2036]
Hello,

With manualColumnResize to true, I move a text column before another column of type numeric, then when I try and edit the numeric cell and leave, it won't let me leave no matter what value I put in that cell. 

My wild guess : It seems as though the internal column positioning of column types does not get reset when a column is moved to another location.

Numeric Column configuration : 
{ data: "TotalApples", type: "numeric", allowInvalid: false }

![handsontable bug](https://cloud.githubusercontent.com/assets/3340652/5683607/3b5e5870-97f7-11e4-97e8-56be6964bebe.png)

**Comment by danio7** [comment]
https://jsfiddle.net/h04cgqdL/13/

Just move the Number Column over in front of the column CCC and it stops working. You cannot change the value.

**Comment by AMBudnik** [comment]
I guess the new possition of 'Number Column' doesn't recieve ```type: "numeric", allowInvalid: false``` which you set there at the beggining.

**Comment by AMBudnik** [comment]
Confirmed with [0.17.0 version example](https://jsfiddle.net/buotqxrg/) 
* There are no console errors
* Can't exit edit mode

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/2678 and https://github.com/handsontable/handsontable/issues/1823

**Comment by AMBudnik** [comment]
Could be connected with https://github.com/handsontable/handsontable/issues/2389

**Comment by AMBudnik** [comment]
Confirmed with 0.23.0: https://jsfiddle.net/buotqxrg/1/

**Comment by AMBudnik** [comment]
Works as expected in 0.27.0, demo: https://jsfiddle.net/5fj3tqp3/
