### ISSUE TITLE
HandsontableObserveChanges fires inappropriate events when using Object-based data source

### ISSUE THREAD

**Issue by cr1ckt** [handsontable/handsontable#2037]
To reproduce:
1. Create a table with sorting enabled and Object-based data source.
2. Sort on some column to trigger the creation of a sortIndex.
3. Programmatically add a previously unknown property value on one of the Object records in the data source.
4. Observe that the sortIndex mapping logical rows to the source data becomes corrupted so that rendering is broken. (It seems that this affects any rows with a physical index after the record that was changed in step 3, due to the way the sorting plugin is shifting mapped indices.)

When using an Object-based data source, the plugin for observing changes fires afterCreateRow and afterRemoveRow events if the parsed column in the patch path is non-numeric. This is semantically incorrect, since a column based on an Object key is still a column, not a row. Anything observing those row hooks has ignore the invalid event being raised.

In my environment, this caused an issue because the sorting plugin was handling the afterCreateRow event with an undefined amount and attempting to add it to the existing sortIndex without checking that the amount was numeric. This results in NaN being assigned to the mapping, which corrupts the link back to the source data and breaks rendering.

While the sorting plugin could defensively check for a non-numeric amount to fix this specific bug, it seems that the root cause is this semantically incorrect event being raised by the data observer.

**Comment by cr1ckt** [comment]
As a workaround, it is possible to disable the change observer by configuring the table with 
`observeChanges: true`

This works as long as you make sure to use the API to set any data if you want the change to be reflected.

**Comment by AMBudnik** [comment]
Hi @cr1ckt 
Could you check if this occurs in 0.24.0 version also?
Thanks in advance.
