### ISSUE TITLE
manualresize and autocomplete

### ISSUE THREAD

**Issue by chowkh** [handsontable/handsontable#2039]
the problem : I cannot resize the column

The first column is an autocomplete. When I move the first autocomplete column to second column, I can perform column resize.

**Comment by AMBudnik** [comment]
I couldn't reproduce it. I've made [JSFiddle](http://jsfiddle.net/gzy5oz1y/) for that particular situation but it works as expected. Can you please prepare a demo if you still have this issue?

**Comment by chowkh** [comment]
Thank you for reviewing my case.

I am still having the problem.

Kindly visit our website.

demo.test.es2cloud.com/web3

Login id : root
Password : root

Go to File>Extra Service>Expense Log

The problem will appear.

When I am working on my development machine, it works fine. Until I deploy
it, then this problem happens.

Regards
Chow




On Fri, Mar 13, 2015 at 6:22 PM, Aleksandra Budnik <notifications@github.com

**Comment by AMBudnik** [comment]
I couldn't reproduce it with your site. Please provide you OS/browser information

**Comment by chowkh** [comment]
Hi Aleksandra,

I have change it therefore, you may not able to reproduce it.

My apologies, I was referring to a different issue. I believe it was
encoding issue which one of your team member recommended me to upgrade.
Which I do not have time to do it.

Thanks.

Regards
Chow


On Wed, Mar 25, 2015 at 8:10 PM, Aleksandra Budnik <notifications@github.com

**Comment by AMBudnik** [comment]
OK. Thank you for a quick response. If you would have any other questions please open a new issue.
