### ISSUE TITLE
Cannot rollback "column sort" action

### ISSUE THREAD

**Issue by XieShangxu** [handsontable/handsontable#2040]
Hi,

After sorting the column, I cannot use "Ctrl+Z" to rollback. And if I have some actions before sorting, there will be some data errors.

Best Regards,
Daniel

**Comment by krzysztofspilka** [comment]
@XieShangxu Thanks for letting us know, this issue is confirmed, to be fixed. http://handsontable.com/demo/sorting.html

**Comment by krzysztofspilka** [comment]
@XieShangxu planned to be fixed in 0.12.7 on March 5

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/2109

**Comment by krzysztofspilka** [comment]
@jansiegel that bug reported by @XieShangxu is not current any more but we have a problem with the sorting icon.

**Comment by krzysztofspilka** [comment]
We no longer need that sorting back action as the sorting itself has 3 levels and the last of it takes the order back to the initial state.
