### ISSUE TITLE
Allow user-defined names in context-menu commands which trigger comments

### ISSUE THREAD

**Issue by omd** [handsontable/handsontable#2042]
In the current version, the comment-plugin relies on the string 'Comment' to detect if the plugin is called by a context-menu command to add a new comment. When using user-defined context-menu strings without 'Comment' as a part of it (like e.g. 'Kommentar hinzufügen', the german translation for 'add comment'), the comment popup is immediately dismissed and the comment cannot be added.

There should be another way to detect whether the plugin was called by a context-menu item than a string comparison with the context-menu caption.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
