### ISSUE TITLE
Merged cells not being scrolled to their left, when appearing on the left edge of the container

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2045]
Known issue from v. 0.12.3:

Merged cells not being scrolled to their left after selection, when appearing on the left edge of the container.
See attached gif:

![Merged cells issue](http://i.imgur.com/h4Etyjw.gif)

**Comment by Wojciech-Swiderski** [comment]
Issue resolved:
https://jsfiddle.net/zd8q6s4L/1/
<img width="516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdvQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b6e49e2f060b2781e410531d4570d510625bb3d/image.png" alt="image.png" />
<img width="514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkRvQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d3892675fcf09cad7cd8ee29f4164173484c443/image.png" alt="image.png" />
