### ISSUE TITLE
manualColumnMove not updating the column width

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#2046]
Hi,

Have anyone faced this issue.
The manualColumnMove is moving the column alright, but not taking the column width along.

Please check : http://jsfiddle.net/fxfaxtz1/

The columns are getting moved correctly but the width are not getting refreshed resulting in a data wrap and messing up the entire HOT.

Please advise

**Comment by krzysztofspilka** [comment]
Thanks for reporting, this is a confirmed issue, to be fixed in one of the next releases, for now 0.12.5 but it can be changed over time.

**Comment by PassHours** [comment]
Thanks. Will appreciate if this fix is available in the next release itself as I am already using this.
Is there any kind of fix/workaround until the fix is available?

**Comment by krzysztofspilka** [comment]
@PassHours I can't promise you that it'll be fixed in the next version as it's not a severe bug. As for workaround, we have a commercial offer for cases like this, if you're interested please reach to us at hello@handsontable.com.

**Comment by PassHours** [comment]
Ok.. thanks.
What are the features for commercial version of HOT... is there any kind of link for me to read

**Comment by krzysztofspilka** [comment]
@PassHours the first version of Handsontable with commercial modules (and license) is expected to be released no sooner than in July 15'. It's going to be a parallel project so we'll keep providing a support for open source version.

**Comment by PassHours** [comment]
So the open source project with MIT license is going to stay along with the commercial product.
I guess the HOT team has no plan to take away the free open source version completely.

**Comment by krzysztofspilka** [comment]
@PassHours that's right, Handsontable (MIT) will stay where it belongs, on GitHub :)

**Comment by PassHours** [comment]
Is there any update on this fix. When are you targeting this release. 
If no plan to fix this issue then can you provide any workaround that can be applied as a temporary fix for this issue so that I can make my users happy.
Thanks for this awesome control.

**Comment by krzysztofspilka** [comment]
@PassHours we release new version every 2 weeks, I really hope to fix this with 0.12.7 on March 5. Can't promise that though.

**Comment by PassHours** [comment]
Thanks for the update @krzysztofspilka

**Comment by PassHours** [comment]
@krzysztofspilka  ... What about the support for the paid version. How long it will take to get the support back if I raise any issue in the paid version?

**Comment by PassHours** [comment]
@budnix, @jansiegel , @krzysztofspilka  Any update on this. It's a long time pending bug without getting addressed in any releases. The manualColumnMove  feature is useless without this bug getting fixed

**Comment by krzysztofspilka** [comment]
I think that would be an interesting feature to be able to move column and update its settings alongside. I'm moving this request to our list of feature requests (https://github.com/handsontable/handsontable/wiki/Feature-requests)
