### ISSUE TITLE
Floating table when mouse over context menu

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2047]
If the native horizontal scrollbar is visible then if you invoke context menu and hover a mouse cursor over any option of it the table floats to the left edge of the browser.

**Steps to reproduce the problem:**

- Go to http://handsontable.com/demo/scroll_window.html
- Invoke context menu by right-click
- Hover the mouse cursor over any menu option

:information_source:
> Handsontable v. 0.12.3
> Windows 8.1
> Chrome v. 39.0.2171.95 m

![left-float](https://cloud.githubusercontent.com/assets/8048526/5703061/aab7db6c-9a61-11e4-84ee-94badeb48e36.png)

**Comment by jansiegel** [comment]
closing as duplicate of #1897

**Comment by AMBudnik** [comment]
Released: v0.12.4
