### ISSUE TITLE
handsontable in an angularjs directive - render an anchor that has an ng-click

### ISSUE THREAD

**Issue by hobbyman** [handsontable/handsontable#2050]
I don't know if this is an issue or just my lack of understanding, so sorry in advance.

I'm using Handsontable to render a grid. (I am NOT using the ngHandsontable. I started out with that but ran into problems and so I went with just rendering a Handsontable from an angularjs directive.)

I want one column to hold an anchor tag.

I want the anchor tag to have the angularjs ng-click directive.

Everything renders correctly but the ng-click is **not called**.

[Here is my plnkr simple example](http://plnkr.co/edit/I5eWEg)

What am I doing wrong?

**Comment by pdemilly** [comment]
I think you could just create a renderer and use angular service $compile to create a dom of your template and append it to the td like this

Assuming you are in your controller and you have injected $scope

function angularRenderer (instance, td, row, col, value, cellProperties) {
   // These are 3 examples of different possible interpolation
   $scope.hello = 'Hello Word';
   $scope.title = 'Click me!';
   $scope.testButton = function (s) { alert (s); };

   var template = '<button ng-click="testButton(hello)">{{title}}</button>';
   var dom = $compile (template) ($scope);
   $(td).empty().append (dom);  // we need to empty it first so we can append our newly compiled dom
};

Hope that helps
