### ISSUE TITLE
Weird copy-paste in context menu behavior

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#2051]
Hi,
The copy paste functionality seems to be breaking in this current version of HOT. The context menu is all over the place and the copy/paste behavior is weird.

Please check : http://jsfiddle.net/k5q99auy/

Is it a bug or am I doing something wrong? Please advise.

**Comment by jansiegel** [comment]
Hi, @PassHours 

It looks like the issue you're facing might be related with [ZeroClipboard's problem with iframes with a 'sandbox' attribute](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#sandboxed-iframe-limitations) which jsfiddle (as well as codepen and other code playgrounds) uses.

However, using a little workaround provided by ZeroClipboard it is possible to use jsfiddle with Copy/Paste from ContextMenu plugin: http://fiddle.jshell.net/k5q99auy/1/show/
**Note, that it has to be viewed in fullscreen mode.**

You can view and modify the code here: http://fiddle.jshell.net/k5q99auy/1/

Thanks for reporting!

**Comment by PassHours** [comment]
Thanks will try....
Now is it possible to implement the same feature in HOT through javascript.  Actually I have a copy row and paste row button on screen and based on user click the same thing will happen in HOT (not as a context menu)
Kindly advise.
