### ISSUE TITLE
Numeric Cell Type Edit shows previous value

### ISSUE THREAD

**Issue by HandsTest** [handsontable/handsontable#2052]
Hi,

Try this scenario,

Change any numeric column in the last row and press enter.
Now press F2 or enter again, as you can see old value is displayed instead of the modified value.

http://jsfiddle.net/ucttc3tg/

This does not happen for other rows or if minSpareRows is enabled.

**Comment by budnix** [comment]
Hi,

This bug is actually fixed and it is related with https://github.com/handsontable/handsontable/issues/1941.

**Comment by HandsTest** [comment]
Thanks budnix. Is fix yet to be released ? as i tried with the latest version and it didn't work.

**Comment by budnix** [comment]
Actually fix is available only on branch https://github.com/handsontable/handsontable/tree/feature/issue-1941. I'm sure that fix will be included to the next release (0.12.4)

**Comment by HandsTest** [comment]
Thanks a lot budnix...

**Comment by krzysztofspilka** [comment]
Fixed in #1941, to be released in 0.12.4
