### ISSUE TITLE
Multiple instance of HOT taking the last custom renderer for all

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#2054]
Refer to: https://github.com/handsontable/handsontable/issues/1040

Is there any fix available in HOT inside its own infrastructure for this?
Actually I have custom renderer like this

cells: function (row, col, prop) {
var cellProperties = {};
if (col == 0) cellProperties.renderer = blueRendererCustom;
return cellProperties;
}

blueRendererCustom = function (instance, td, row, col, prop, value, cellProperties) { 
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    var id = instance.rootElement.id; 
//id always shows the last HOT div id. If there are 3 HOT instances then the id will show the id of the 
//last HOT div
    cellProperties.readOnly = true; 
}

Hence if there are more than 1 instance of HOT on the page then the last executed blueRendererCustom taking effect on every HOT.

Please advise.

**Comment by AMBudnik** [comment]
Hi @PassHours please prepare a demo for that issue.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo. If you would still face this issue feel free to write back.
