### ISSUE TITLE
HOT renders cells twice, when using fixedColumnsLeft

### ISSUE THREAD

**Issue by lucamaral** [handsontable/handsontable#2057]
I am upgrading my handsontable version(0.10.5) to the newest(0.12.3). 

When handsontable has the option "fixedColumnsLeft", the renderer function assigned in cellProperties, is called twice(for each cell, of course).

I created [this fiddle!](http://jsfiddle.net/bkmwyrtr/4/)

**Comment by AMBudnik** [comment]
Occurs in 0.24.1

**Comment by AMBudnik** [comment]
This process is actually an only way to show fixed rows and columns. We create a second layer on the top of the table.
