### ISSUE TITLE
Default options don't seem to be applied correctly when passing undefined

### ISSUE THREAD

**Issue by jarben** [handsontable/handsontable#2059]
This thing got me today, I've used this option with this value: 
{
    maxRows:this.maxRows
}

and couldn't figure out why there is no spare row. 

example: http://jsfiddle.net/2p9d7esz/

Than I found out that default for maxRow is Infinity and did something like this: 
{
maxRows: typeof this.maxRows == "undefined"?Infinity:this.maxRows
}

Shouldn't the defaults be picked when config property is undefined? 

I guess HT rather iterates through config properties and only applies defaults when there is no property with that name? 

Or is it actually intentional?

**Comment by AMBudnik** [comment]
Hi @jarben 
Are you still facing issues related to this case? Can you check it with the latest 0.24.1 version?
Thanks in advance!
