### ISSUE TITLE
Custom Copy Cells

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#2060]
This is an enhancement request...

I had a need for a copy to capture alternative data than what is really in a cell.  For example, copying what is seen by the rendered cell rather than the actual data it is representing.

To to this, I made it so the `copyable` column option (which is normally a boolean) can optionally be defined as a function which returns the text to be copied to the clipboard.

The `getCopyable` function is rewritten as so:

```java
Handsontable.DataMap.prototype.getCopyable = function (row, prop) {
  var copyable = copyableLookup.call(this.instance, row, this.propToCol(prop));
  if(typeof(copyable) === 'function') {
    return copyable(this.instance, row);
  } else if(copyable) {
    return this.get(row, prop);
  }
  return '';
};
```

Additionally, if there is a need to handle pasting of a different representation, like this, it is handled specifically by the `paste` source in the `afterChange` event.

**Comment by lucamaral** [comment]
[Check this out](https://github.com/handsontable/handsontable/pull/1856)

**Comment by krzysztofspilka** [comment]
Thanks @lucamaral

**Comment by lucamaral** [comment]
@krzysztofspilka Correct pull request made following Git-Flow steps: #2103
