### ISSUE TITLE
Cell type handsontable, autocomplete mix

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#2063]
Is there any way I can set the data of column type handsontable at runtime from javascript instead of hard coded it upfront. 
The requirement is such that based on user input on that cell I will fetch data from json (say) and will show up on that handsontable  type column. Its a kind of type "autocomplete" and type "handsontable" mix.

http://jsfiddle.net/vh0vnzxb/

Please advice

**Comment by PassHours** [comment]
Any update on this?.. Is there any plan to implement this feature or there's an workaround for this issue.
Please advise

**Comment by PassHours** [comment]
@krzysztofspilka ... Can you provide any update on this requirement. Is there any workaround for this?

**Comment by AMBudnik** [comment]
Can you provide more information how you would like to serve this data. Am I thinking right - you would like to change single cell `type` when user is filling this cell? If so, the trigger to change would be an edit or a specific data typed by the user?

**Comment by PassHours** [comment]
Hi,

You can check my jsfiddle : http://jsfiddle.net/vh0vnzxb/
In your example the json data is fixed. I want to dynamically bind the data in autocomplete based on user input. As the user goes on inputting the filter and autocomplete will change accordingly.

Please advise. Any working sample will be great. You an edit my jsfiddle too,

**Comment by AMBudnik** [comment]
@PassHours I think that this demo: http://codepen.io/js-ziggle/pen/vEwdKq?editors=001 might come in handy. Please select `Steve` to see results.
