### ISSUE TITLE
Question: There is an option to handsontable don't add new empty rows?

### ISSUE THREAD

**Issue by lucamaral** [handsontable/handsontable#2064]
For example: On drag-down/autofill.

![issue](https://cloud.githubusercontent.com/assets/3779622/5755982/c7e70a96-9c91-11e4-9a3f-333e36804f46.png)

**Comment by AMBudnik** [comment]
Hi @lucamaral maxRows option is made for that, but like it is written in [documentation](https://github.com/handsontable/handsontable/wiki/Options):

>columns : Array (default undefined)
Defines the cell properties and data binding for certain columns. Notice: Using this option sets a fixed number of columns (options startCols, minCols, maxCols will be ignored). 
See Options section below for more detailed explanation 
See demo/datasources.html for examples"
