### ISSUE TITLE
Internet Explorer 8 issue (with a fix)

### ISSUE THREAD

**Issue by bcavileer** [handsontable/handsontable#2067]
User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; SLCC1; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729)
Timestamp: Thu, 15 Jan 2015 18:26:42 UTC

Message: Object doesn't support this property or method
Line: 104
Char: 13
Code: 0
URI: /assets/handsontable.full.js

it seems this line is the culprit
```return toString.call(obj) == '[object Array]';```
so I replaced it with
```return Object.prototype.toString.call(obj) === '[object Array]';```

and now the table works in IE 8.

Can anyone suggest a proper solution?

**Comment by GitIntetics** [comment]
I have the same issue. I have to reapply this fix (thanks for it, btw) every time when I download a new version. Is it possible to fix it permanently, pls?

**Comment by AMBudnik** [comment]
As we dropped IE8 and 9 support with [0.12.0](https://github.com/handsontable/handsontable/releases/tag/0.12.0) issues related will be closed. Please check our [SO](https://stackoverflow.com/questions/tagged/handsontable) for more information about HOT.
