### ISSUE TITLE
Context Menu on Column Header not disabling Row options in some cases

### ISSUE THREAD

**Issue by yuwong** [handsontable/handsontable#2068]
From the demo page http://handsontable.com/demo/contextmenu.html the row options are disabled if you right-click the column header before doing anything else, but it doesn't work if you had selected any cell beforehand, say A1, after which, right-clicking the column header would show the row options as available.

**Comment by AMBudnik** [comment]
Can you provide more information in steps, how to reproduce the issue?

**Comment by yuwong** [comment]
Sure,
1: Go to http://handsontable.com/demo/contextmenu.html
2: Select the A1 cell normally (left click)
3: Right-click on column header A 

The key is step 2.

**Comment by AMBudnik** [comment]
OK I get it, thanks for report.

**Comment by AMBudnik** [comment]
Please check it with the latest version. I tried to reproduce it, and it works fine.

**Comment by yuwong** [comment]
Ok, it seems like it got around it by always assuming cell A1's Context Menu when the Column Header context was requested, which I suppose is okay to do...
