### ISSUE TITLE
Bug: Context menu has invisible area that causes errors when clicked.

### ISSUE THREAD

**Issue by jimmyh77** [handsontable/handsontable#2069]
When using the context menu, the div container is bigger than what is displayed.
![handsontable](https://cloud.githubusercontent.com/assets/6557262/5777058/0922e156-9d87-11e4-917d-c6bc6691cf13.png)

Clicking in this area causes problems both when you have a menu item highlighted and when an item is not highlighted.

Clicking in this area with a menu option highlighted will perform that action.

Clicking in this area with nothing highlighted causes errors in ContextMenu.prototype.performAction and also in the disabled function for each menu item that has a disabled function.

If the area is outside of handsontable just performAction gets an error.  If the area is within handsontable then each menu item with a disabled function causes an error.

getSelected() is returning undefined in both cases.

Regards.

**Comment by AMBudnik** [comment]
Issue does not occur. Please leave us your feedback in case you still face this issue after updating.
