### ISSUE TITLE
How to handle percentages the way Excel does it?

### ISSUE THREAD

**Issue by hellovijayr** [handsontable/handsontable#2070]
I set the data type of my cell to numeric and the data format to 0.00% 
The percentages work correctly, except when I edit it shows "1" instead of "100" - meaning, it shows the ratio instead of the percentage number itself.  This makes sense, but my users are used to Excel - and Excel shows the actual percentage number.

Is there a way to get around it?

**Comment by lucamaral** [comment]
You can create a [custom cell editor](https://github.com/handsontable/handsontable/wiki/Custom-cell-editor#overriding-editormanager-default-behaviour).

I created [this] (https://github.com/lucamaral/handsontable-numeric) repository that uses custom editors and renderers.

**Comment by AMBudnik** [comment]
Thank you @lucamaral for a good tip, glad you're deep into handsontable - we appreciate.
