### ISSUE TITLE
comment not work

### ISSUE THREAD

**Issue by usturoi** [handsontable/handsontable#2071]
Hy,

New second comment and modify comment not work in firefox 35

**Comment by AMBudnik** [comment]
Hi, you're right, this occurs and unfortunately not only in Firefox 35 but be sure that we know this issue. There are few bugs left in this option to fix, that is why we're still in beta mode for comments.

**Comment by krzysztofspilka** [comment]
https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
