### ISSUE TITLE
hyperlink with script functionality

### ISSUE THREAD

**Issue by everramansoul** [handsontable/handsontable#2074]
I want the handdsontable data in a cell to point to a hyperlink and write a javascript function to generate the hyperlink data based on the cell data. Is there a way to achieve it

**Comment by PassHours** [comment]
Not sure what exactly you are looking for but I guess you have seen the custom html renderer section of handsontable to get some idea.

http://handsontable.com/demo/renderers_html.html

**Comment by AMBudnik** [comment]
@PassHours is right, [renderers](http://handsontable.com/demo/renderers_html.html) in the best place to look for. If you would have any other question, please one a new issue.
