### ISSUE TITLE
afterMergecell event or callback

### ISSUE THREAD

**Issue by sujith3g** [handsontable/handsontable#2075]
I have used the `mergeCell` feature. Now I'm looking for an event which triggers after merging cells like `afterChange` event. I didn't found anything like that in wiki, Does `mergeCell` feature offers any callback or event?

**Comment by AMBudnik** [comment]
For further information please track #1929

**Comment by samiralajmovic** [comment]
You could make one yourself, it's not the semantically correct way to do it probably, but it works.

Use the event afterRender and keep track of number of merged cells yourself using hot.mergeCells.mergedCellInfoCollection, where hot is an instance of handsontable. Then in the afterRender callback, do something like:

      var numMergedCells = []; 
      hot instance {....
            afteRender: function () {
                 if (numMergedCells.length !== this.mergeCells.mergedCellInfoCollection.length) {
                     numMergedCells = this.mergeCells.mergedCellInfoCollection;
                     mergeCellCallback();
                 }
            }
    ...}

**Comment by docmattman** [comment]
It's a good workaround, but it seems there should be a hook for afterMerge or something similar.  It would help out a lot.

**Comment by jattyouth** [comment]
@samiralajmovic Thanks man, great fix.
