### ISSUE TITLE
Make handsontable available in npm

### ISSUE THREAD

**Issue by vdel26** [handsontable/handsontable#2076]
Would be really cool to be able to install handsontable from npm. I tried it since it already has a package.json but it fails when trying to load it.

**Comment by vdel26** [comment]
Here is the error I get when trying to load it:
```sh
> var handsontable = require('handsontable')
Error: Cannot find module 'handsontable'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:20
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
```

I installed it by doing:
```sh
npm install handsontable/handsontable
```

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by dcsan** [comment]
I installed it by doing:

    npm install handsontable/handsontable

I'm curious - how does this work? It installed something for me too, but there is [no actual listing of the package in NPM](https://www.npmjs.com/browse/keyword/handsontable).

Further, I'm having problems with the package that was installed as there's no `main` field defined

**Comment by tnrich** [comment]
+1

**Comment by blink1073** [comment]
@dcsan, installing that way actually installs it from the github repo.

**Comment by dcsan** [comment]
@blink1073 thanks for the tip, i didn't know about that. so npm install will default to looking in github if it can't find a module in it's own directory? interesting.

in that case [this package.json](https://github.com/handsontable/handsontable/blob/master/package.json) would be used.

the question we have is how does this package work if there is no main field or index.js ?
https://forums.meteor.com/t/meteor-1-3-early-beta-now-available/14723/125?u=dcsan

if we were to create an NPM module what would need to be defined?

**Comment by blink1073** [comment]
Normally there would be a `main` field in `package.json`, else it defaults to `index.js`.  I'm not sure about how to go about wrapping.

**Comment by dcsan** [comment]
exactly, but there's no index.js either...

**Comment by AMBudnik** [comment]
Feature added with [v0.24.2](https://github.com/handsontable/handsontable/releases/tag/0.24.2)
