### ISSUE TITLE
Undo/Redo not work for merged cells

### ISSUE THREAD

**Issue by D2Phoenix** [handsontable/handsontable#2079]
**Description:**
Undo/Redo not work for merged cells
**Steps to reproduce:**
1. Merge some cells few times
2. Try Undo/Redo
**Result:**
Undo/Redo not work for merged cells
**Expected:**
Undo/Redo works correct

**Comment by AMBudnik** [comment]
For further information please track changes to https://github.com/handsontable/handsontable/issues/2109
