### ISSUE TITLE
Merged cells not move on add/remove row/column

### ISSUE THREAD

**Issue by D2Phoenix** [handsontable/handsontable#2080]
**Description:**
Merged cells not move on add/remove row/column
**Steps to reproduce:**
1. Merge some cells few times
2. Try add/remove row/column
**Result:**
Merged cells not move
**Expected:**
Merged cells move
![merge_cells_not_move](https://cloud.githubusercontent.com/assets/6198982/5836162/a25bb290-a182-11e4-8853-5b7dd885b658.gif)

**Comment by AMBudnik** [comment]
Indeed it not acts like it should. Thank for sharing this bug.

**Comment by samiralajmovic** [comment]
Doesn't work removing the merged cells either.

**Comment by floribon** [comment]
Any news as to when this will be fixed?

**Comment by jansiegel** [comment]
@floribon The fix will be released with the next Handsontable version :)
