### ISSUE TITLE
Using summernote on the same page blocks copy/paste

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/handsontable#2081]
I use [summernote editor](https://github.com/summernote/summernote). Copy/paste does not work any more in this editor when using handsontable on the same page. Any ideas how to fix?

Summernote seems to lo lose it's focus when pressing `ctrl+v`.

**Comment by doczoidberg** [comment]
http://jsfiddle.net/n8dt4/147/

**Comment by AMBudnik** [comment]
For issues related with other libraries please create a topic at [stackoverflow](https://stackoverflow.com/search?q=handsontable) with `handsontable` tag.
