### ISSUE TITLE
After removing the fixed column, the nearest one takes it's place

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2083]
After removing a fixed column, the nearest one (next one to the right) becomes fixed. It should rather decrement the `fixedColumnsLeft` setting by `1`.

------

##### Steps to reproduce:
- Go to /demo/fixed.html
- Right-click on the `B` column header
- Choose the `Remove column` option

Result:
Column `C` becomes fixed.

**Comment by kubak10** [comment]
What about header letter.
I removed fixed column 'B' but I still have column 'B' with column's 'C' content.
Maybe another ticket for this.
But fixed column problem is fixed :)

**Comment by jansiegel** [comment]
@kubak10 That's actually the desired behaviour - if there are no column headers specified in the initial config, the default ones (`A`, `B`, `C` etc.) are consistent regardless of what changes are made in the table data. It looks strange with the test data being strictly connected with the default headers (eg., `A1`, `B2`), but with a 'real' data it makes sense.
Excel and Google Spreadsheets do this similarly.

**Comment by krzysztofspilka** [comment]
Tested and it works but the context menu invoked on the rows header have an option "Remove column", which applied is removing column "A". I'm not sure this option should be visible there as it may be a bit confusing...

**Comment by jansiegel** [comment]
Released in version 0.12.6
