### ISSUE TITLE
Cell loses selection when scrolling in the Merge Cells demo

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2084]
In the Merge Cells demo, when a cell is selected and the user starts scrolling using a scrollbar, the selection disappears.

------

##### Steps to reproduce:
- Go to /demo/merge_cells.html
- Select a cell
- Scroll the table by clicking on the scrollbar and dragging it

Result:
The cell is no longer selected.

**Comment by jansiegel** [comment]
Turns out, it's due to the `outsideClickDeselects` setting - in this demo the scrollbars are connected with Handsontable instance's parent container, not the instance container itselft. This makes HOT treat clicking those like outside clicks, resulting in cell deselection.

**Comment by krzysztofspilka** [comment]
Connected with #2351
