### ISSUE TITLE
Cursor goes left after first character entered for masked cells #1863

### ISSUE THREAD

**Issue by Vikrantj21** [handsontable/handsontable#2087]
I am facing issue same
please help it out asap

**Comment by AMBudnik** [comment]
Please provide a [JSFiddle](http://jsfiddle.net/api/post/library/pure/) demo for that issue.

**Comment by AMBudnik** [comment]
In lack of demo I assume it's not an issue anymore. If I'm wrong - please reply and we'll reopen your issue.
