### ISSUE TITLE
what cause this problem 1/4

### ISSUE THREAD

**Issue by chowkh** [handsontable/handsontable#2088]
![image](https://cloud.githubusercontent.com/assets/10473271/5858468/52c2664a-a28e-11e4-8ede-0a05cc988b4d.png)

**Comment by chowkh** [comment]
Can someone tell me what is the problem? The autocomplete is also not working correctly. It is not filtering the list for me but rather just show the matches in bold

**Comment by chowkh** [comment]
It was working fine on my local PC. When I deployed in Linux, I have this problem. No change in codes at all.

**Comment by AMBudnik** [comment]
Ok, we will check that as soon as possible.

**Comment by AMBudnik** [comment]
Can you provide more information? It looks like a coding issue. A demo would be appreciated.

**Comment by chowkh** [comment]
This is resolved. Encoding issue. I have upgraded my handsontable and this was solved. Thanks anyway

**Comment by AMBudnik** [comment]
OK, thanks for reply.
