### ISSUE TITLE
How to disable fixed (floating) header to increase scroll speed, without affecting autocomplete dropdown experience?

### ISSUE THREAD

**Issue by amrutraj** [handsontable/handsontable#2098]
Adding style to handsontable container div, as style='overflow:auto;' , disables floating headers. 
BUT 
It also forces the autocomplete dropdown to be shown only in the outer DIV area. 
MEANING, You need to scroll to view all dropdown values. (It confuses users to think that there are only a couple of values in dropdowns.) What should I do, to view the dropdowns,  as they look when I dont add style='overflow:auto;'.

DEMO fiddle is here.
http://jsfiddle.net/nvfx9ns6/1

PS - I WANT TO DISABLE floating headers because my app dynamically (AJAX) generates multiple HOTs (14 on avg. per page ) based of users previous entries. Scrolling on page is noticeably slow (esp on firefox.) if headers are floating.

**Comment by radusl** [comment]
i have exactly the same problem

**Comment by AMBudnik** [comment]
I tried to check this issue with the 0.24.1 example: http://jsfiddle.net/4g7skduw/
I guess it does not occur anymore, can you @amrutraj @radusl check it please?

**Comment by AMBudnik** [comment]
I hope that at this point, if anybody had any issue with this subject they would have spoken by now.

**Comment by helmutgranda** [comment]
I noticed by the example that altho the dropdowns are not hidden anymore the overflow:auto trick does not disable the fixed headers. Just FYI.

**Comment by AMBudnik** [comment]
Hi @helmutgranda 
Can you create a draft/video/demo or anything where we'll be able check what's wrong? I'm not sure if I have the same thing on my minds.

**Comment by helmutgranda** [comment]
Hi @AMBudnik,

I played around with the table and was able to disable the floating headers by adding a container:

http://jsfiddle.net/4g7skduw/4/

I will leave this here as reference since I think we see recommendations on adding "overflow:auto" but not a clear example of how.

Thanks!

**Comment by AMBudnik** [comment]
great, thank you @helmutgranda
