### ISSUE TITLE
Copy & paste of numeric price cells has not same format

### ISSUE THREAD

**Issue by zitniak** [handsontable/handsontable#2102]
When I copy my price numeric cell 229,36 € from handsontable to text editor I get 229.36

When I copy 229,36 € from MS Excel to text editor I get 229,36 € which I think is more correct behaviour. 

My workflow is I pasting data from handsontable to Excel but my price cells from handsontable are wrong copied to excel there are like text '229.36'. Then I need manual reformat it in Excel as price (Like replace '.' -> ',' within content and format as currency)

Copy & Paste feature of number should paste exactly like in form is displayed in cell so when I see 229,36 € in handsontable I get 229,36 € after copy & paste

**Comment by AMBudnik** [comment]
OK, thank you I'll write it down as a feature candidate.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
