### ISSUE TITLE
Pressing Delete or Backspace breaks checkbox

### ISSUE THREAD

**Issue by kevin-j-morse** [handsontable/handsontable#2106]
Pressing Delete or Backspace on a checkbox cell sets the cell to #bad value# and prevents the checkbox from being used anymore.

This can be reproduced on the demo page. http://handsontable.com/demo/checkbox.html

There are a few pull requests related to this which seem to have been ignored. #2033 and #1607

**Comment by AMBudnik** [comment]
Thank you @kevin-j-morse we will look at this.

**Comment by krzysztofspilka** [comment]
Released in https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
