### ISSUE TITLE
.htDimmed is not used with CheckboxRenderer

### ISSUE THREAD

**Issue by fescudie** [handsontable/handsontable#2108]
Hi,

When cells become readOnly they use the class htDimmed. I rewrited the properties of this class : 
.handsontable .htDimmed {
    color:#777;
    background-color:#F7F7F9;
}
This is ok for text cells but not for checkbox cells.
Why the checkbox cells doesn't use this class ? How can I do to change theirs CSS when they become readOnly ?

Thanks in advance.

**Comment by mauritsvanrees** [comment]
I see the same. (Version 0.11.4, but I see no relevant changes after that.)

Adding `Handsontable.renderers.cellDecorator.apply(this, arguments);` to the top of the `CheckboxRenderer` class fixes it for me.

I do not know if there is a reason for not including this, but I notice no ill effects of adding this.

Issue #1866 may have the same cause.

As workaround, you can override the renderer in your own javascript:

```
var CheckboxRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    // This is a workaround for issue
    // https://github.com/handsontable/handsontable/issues/2108
    // The original checkbox renderer does not apply the cellDecorator.
    Handsontable.renderers.cellDecorator.apply(this, arguments);
    Handsontable.CheckboxRenderer(instance, td, row, col, prop, value, cellProperties);
};
Handsontable.renderers.registerRenderer('checkbox', CheckboxRenderer);
```

**Comment by mauritsvanrees** [comment]
Well, I thought that workaround in own javascript worked, but that conclusion was wrong.

For the record a second try, also having no effect:

```
Handsontable.renderers.originalCheckboxRenderer = Handsontable.renderers.CheckboxRenderer;
var CheckboxRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.cellDecorator.apply(this, arguments);
    Handsontable.originalCheckboxRenderer(instance, td, row, col, prop, value, cellProperties);
};
Handsontable.CheckboxRenderer = CheckboxRenderer;
Handsontable.renderers.CheckboxRenderer = CheckboxRenderer;
Handsontable.renderers.registerRenderer('checkbox', CheckboxRenderer);
```

I could create a `mycheckbox` cellType and register my renderer for that, but that needs some more lines.

So I will simply put the `cellDecorator.apply` line in my downloaded handsontable code for now.

**Comment by fescudie** [comment]
This solution works for me.

Thank you.
