### ISSUE TITLE
Implement Undo/Redo for more features

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2109]
Quick run through the handsontable.com demos shows, that many of features don't support the Undo/Redo functionality.

For example:
- column sorting
- column/row resize
- column/row move
- column freeze
- merge cells
- custom borders
- grouping

**Comment by PassHours** [comment]
Good to have if possible

**Comment by docmattman** [comment]
Yes, it would be a huge help to have these available.  I got people using this that are confused why the undo/redo buttons don't do anything for these features.  Please add this.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by krzysztofspilka** [comment]
I'm reopening that. I think that is rather a drawback, not a feature request.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
