### ISSUE TITLE
Dragging fill handle until cell of last row, creates new empty row at the bottom while minSpareRows is zero.

### ISSUE THREAD

**Issue by Wizard13** [handsontable/handsontable#2110]
In v0.12.4, selecting a cell and then dragging its fill handle until the last row, creates a new empty row at the bottom. This didn't happen in v0.10.5 and I don't use minSpareRows option, so its value is zero.

EDIT: 0.11.0-beta1 works correctly, while 0.11.0-beta2 does not.

**Comment by lucamaral** [comment]
I created this pull request  #2105 to solve this issue.

**Comment by AMBudnik** [comment]
It still occurs, thank you for that information.

**Comment by lucamaral** [comment]
@AMBudnik Will you work to solve this issue? Tell me if I can help you.

**Comment by AMBudnik** [comment]
I will do my best is this case. We have to discuss some issues with the rest of rest crew.

**Comment by lucamaral** [comment]
@AMBudnik Ok, thank you!

**Comment by AMBudnik** [comment]
Since 0.23.0 you can allow or disallow creating new rows using:

`fillHandle: {`
     ` autoInsertRow: false`
    `}`

Issue: https://github.com/handsontable/handsontable/issues/2874
Release note: https://github.com/handsontable/handsontable/releases/tag/0.23.0
