### ISSUE TITLE
Handsontable column Hide & show

### ISSUE THREAD

**Issue by unnikrishnan-td** [handsontable/handsontable#2111]
hi,
in handsontable , is it possible to hide/show any columns dynamically.?
I could not find any functionalities to do this operation. can you  guys help me to find it out.?

**Comment by PassHours** [comment]
There is no inbuilt functionality to do so in HOT. This similar question and workaround might help:
https://github.com/handsontable/handsontable/issues/2020#issuecomment-69530673

**Comment by unnikrishnan-td** [comment]
Thanks..
