### ISSUE TITLE
Adding a row requires a refresh when the cells are of numeric type

### ISSUE THREAD

**Issue by kkrusty1** [handsontable/handsontable#2114]
Try this fiddle:
http://jsfiddle.net/tyjyq5jn/

Right-click on the red cell and choose "Insert row above". The row is inserted but the red cell is not pushed down with the other cells.

**Comment by AMBudnik** [comment]
Thanks for that suggestion, I've reproduced it on major browsers and got the same issue. It disappears when you click on that cell and then somewhere else in the table.

**Comment by AMBudnik** [comment]
Tested it with 0.15.0-beta2 and red background does not disappear now with a click.

**Comment by krzysztofspilka** [comment]
I think it was all connected with #1823 which was fixed and released today. @kkrusty1 @AMBudnik could you please confirm that it works fine with the latest version of Handsontable?

**Comment by kkrusty1** [comment]
@krzysztofspilka Yes, it seems to work now. I can't reproduce the problem anymore.

**Comment by AMBudnik** [comment]
It is fixed. I'm closing this issue.

**Comment by andorx** [comment]
Problem with adding a new row at bottom. The red cell also is moved to next row.
Try this: http://jsfiddle.net/cykf2px9/1/

**Comment by AMBudnik** [comment]
Hi @andorx Thanks for sharing. I guess that it's actually an issue related to `alter` method.
I made this demo: http://jsfiddle.net/8tz9866b/

The issue occurs when we add a row using only first parameter (in this case `insert_row`) there's a bug you described. Second parameter is index.

As written in the docs: 

>  If index is null or undefined, the new row will be added after the last row.

which is truth the row is added but the `htInvalid` class shifts down and my cell is missing a `htNumeric` class.
![bez tytulu](https://cloud.githubusercontent.com/assets/10757813/14170083/e3734fcc-f72b-11e5-8fc8-23fa462c97f4.png)

**Comment by AMBudnik** [comment]
updated example: http://jsfiddle.net/f0q2nfuf/
When we edit the same cell it gets proper classes.

**Comment by wszymanski** [comment]
Fixed in #3989.
