### ISSUE TITLE
Fixed column hides first column on unfixed column if scrolled by navigation arrow key [0.12.4]

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#2115]
Hello, I got a problem navigating HT columns on fixed column. Reproduce: 
1. Go to http://handsontable.com/demo/fixed.html 
2. Put your cursor on one of the cells 
3. Then try to navigate using arrow right key to column N or O
4. Press [Home] key 
5. Then navigate to the right column to D or E 
6. Now column C is hidden [Cannot be navigated] using arrow key, except by sliding horizontal scroll bar by using your mouse.
Hopes this will be fixed shortly!

**Comment by dhavalshelat** [comment]
Hi, 

I also had the same issue while using the frozen column, As the same doesn't happen in case of fixed  & unfixed row.

Would be great if a fix is added or a logic is shared.

**Comment by AMBudnik** [comment]
Hi guys, I couldn't reproduce it - everything works fine. Can you check if it's the same for you? If it isn't please provide your OS/Browser info.

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply
