### ISSUE TITLE
Cannot create new column. When data source in an object issue

### ISSUE THREAD

**Issue by MariappanGomathiraj** [handsontable/handsontable#2117]
When I clicked "Insert column on the left" and "Insert column on the left" option in any one of the column. But column haven't added and throws below error.

"Uncaught Error: Cannot create new column. When data source in an object, you can only have as much columns as defined in first data row, data schema or in the 'columns' setting.If you want to be able to add new columns, you have to use array datasource."

My example jsfiddle :
http://jsfiddle.net/pxr3L0sm/1/

Please help to resolve this issue.

**Comment by AMBudnik** [comment]
Solution is in a error's body - you can add a column only on array data actually.

**Comment by AMBudnik** [comment]
Hi @MariappanGomathiraj 
Can you confirm that it's working fine in 0.24.1 version?
I couldn't reproduce it.
