### ISSUE TITLE
Multirow (Discrete Rows) Select Option

### ISSUE THREAD

**Issue by prabhuish** [handsontable/handsontable#2119]
The current version allows to select multi-rows (only adjacent, say rows 1, 2, 3) but not discrete rows. say, row 1, 3, 5. Can you please guide me how to achieve this functionality, 

![image](https://cloud.githubusercontent.com/assets/9697338/5948470/faf2af4a-a712-11e4-8a2b-eefd14575963.png)

**Comment by AMBudnik** [comment]
Hi, @prabhuish in current version you can select only adjacent rows/columns.

**Comment by prabhuish** [comment]
Thanks. Is there any plan to implement the same in upcoming releases? 

I feel it is essential feature for an table where people use to select discrete rows to highlight or even remove from the table. 

In my opinion, the selection can be achieved with "Ctrl + Click" action on row header (even should possible with column header).

**Comment by AMBudnik** [comment]
I also think that 'Ctrl + LMB' it's best pick for that action. It is not excluded that this option can be released in farther future.

**Comment by AMBudnik** [comment]
Also allow #1831

**Comment by krzysztofspilka** [comment]
@prabhuish I'm closing this ticket and moving the idea to our wiki page on feature requests https://github.com/handsontable/handsontable/wiki/Feature-requests

**Comment by AMBudnik** [comment]
This is the same issue as the one that we are currently developing https://github.com/handsontable/handsontable/issues/2119

**Comment by AMBudnik** [comment]
This functionality is currently available.

It can be tested here https://handsontable.com/docs/8.3.2/demo-scrolling.html. Once a CTRL/CMD key is pressed you can select any number of discrete rows/columns or cells
