### ISSUE TITLE
manualColumnMove guide not showing up in the right spot

### ISSUE THREAD

**Issue by pascoea** [handsontable/handsontable#2120]
I guess the title sums it up...  =)

When using manualColumnMove, you are able to move the columns, but the guide DIV isn't showing up in the right location (or sometimes not at all).

Grab the handle for column "C" and slowly drag it to the right, the guide will show up directly over the "C".  As you drag further the guide appears on the far right side of the "D" column, etc.

Confirmed with 0.12.4 on IE, Chrome, and FF (Latest versions)

http://jsfiddle.net/pascoea/2m78hqyc/1/

**Comment by pascoea** [comment]
Btw, even with the little wrinkles like this, you guys still have an amazing product.  Keep up the good work.

**Comment by AMBudnik** [comment]
Thank you @pascoea, glad you like it. We'll take a closer look to that issue.

**Comment by pascoea** [comment]
I have no idea if I did it right, but I attempted to merge my fix into the develop branch:

https://github.com/handsontable/handsontable/pull/2673
