### ISSUE TITLE
manualColumnMove and manualRowMove does not working in handsontable

### ISSUE THREAD

**Issue by unnikrishnan-td** [handsontable/handsontable#2121]
hi all,
after editing any of the content in handsontable, manualColumnMove and manualRowMove properties will not work. 
before updating the content it working good. can you guys help me to solve this.?

**Comment by AMBudnik** [comment]
Hi @unnikrishnan-td please prepare a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/). It works fine in our [ColumnMove demo](http://handsontable.com/demo/column_move.html) so maybe there are some interferences.

**Comment by AMBudnik** [comment]
Without a demo it'll be hard to help. I'll reopen this issue when I get the demo.
