### ISSUE TITLE
Nicescroll prevents Handsontable to determine width

### ISSUE THREAD

**Issue by Bounz** [handsontable/handsontable#2123]
Hi! I'm using HoT on the page with jQuery Nicescroll plugin (https://github.com/inuyaksa/jquery.nicescroll).
This combination breaks ability to set HoT width: neither using *width* option during initialization neither defining with in container style.
I performed little debugging and found out that the problem is due to Nicescroll is setting horizontal scrollbar overflow to 'hidden' and function *WalkontableViewport.prototype.getWorkspaceWidth* returns full page width (https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js#L19774).

Here is a little demo. Setting HoT width to 200px is not working. http://jsfiddle.net/y9g5s2j0/1/ (try to toggle nicescroll initialization)

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by Dams591** [comment]
@Bounz 
Did you manage to implement nicescroll with handsontable after all ? 
Thanks for your help.

**Comment by Bounz** [comment]
@Dams591 As I remember - yes, but this was too long ago and now I don't have access to the source code of that project.

**Comment by AMBudnik** [comment]
The conversation about custom scrollbars is continued at https://github.com/handsontable/handsontable/discussions/7739
