### ISSUE TITLE
Add wrapHeaderText 

### ISSUE THREAD

**Issue by vo-va** [handsontable/handsontable#2124]
These three lines https://github.com/handsontable/handsontable/blob/develop/src/3rdparty/walkontable/src/tableRenderer.js#L51-53

set wrong height of table header if you have long text, set fixed width, and use  css like this

     .handsontable table th  {
       white-space: pre-line;
       word-wrap: break-word;
     } 

see example on [jsfiddle](http://jsfiddle.net/s59skt14/1/) 
Not exactly these two lines, the main problem by my tests is what oversizedColumnHeaders array filled with values before right width of column will be set.  

I.e 
1. render column with standard width;
2. Long text increase height of th cell;
3. oversized height of header of column saved to array oversizedColumnHeaders;
4. width from colWidths applied to column
5. height of th is decreased
6. calling function this.adjustColumnHeaderHeights() with old height
7 the result is the table header overlapping table;

Also it affects the manual resize of column width.  If we resize  column to width of one symbols and then increase column width, column height will not change (see example on jsfiddle)

**Comment by pascoea** [comment]
I have the same issue.  It appeared in 12.3

If the column width is set small enough that the header actually wraps, it renders correctly:

http://jsfiddle.net/pascoea/0fypeq6y/1/

In the same example, if you expand the first column the text header still renders too high.

**Comment by jonlachlan** [comment]
+1. I came across this issue too. I added the CSS indicated above by @vo-va (which worked nicely to word-wrap the text in my header), but it only worked correctly on the first page load. After reload, the calculated height was far too high. Handsontable added a style property in the html element for my first column header:
```html
<th class style="height:339">
```

When I commented out the line indicated above, it went back to working properly. (No added "style" element in html of column headers.)

Hope this helps.

**Comment by cyancdesign** [comment]
+1 here too. Can't find where the height is getting set. and forcing the height to auto messes up the spacing if the table rows are active.

**Comment by cyancdesign** [comment]
I found if I changed
```
this.instance.wtTable.THEAD.childNodes[i].childNodes[0].style.height = this.instance.wtViewport.oversizedColumnHeaders[i] + "px";
```
to
```
this.instance.wtTable.THEAD.childNodes[i].childNodes[0].style.height = this.instance.wtViewport.columnHeaderHeight + "px";
```
It seems to be work.

**Comment by vo-va** [comment]
Hi, @cyancdesign, `oversizedColumnHeaders[i]` is necessary it set correct height. The issue is time when array `oversizedColumnHeaders[i]` filled with values,  see the first message for this issue.

**Comment by morungos** [comment]
And another +1 from me. I'm also using fixed columns, and that's making it even worse, as the fixed columns are offset from the non-fixed ones. But even if I turn off fixed columns, I'm getting the headers pull down over the first row, hiding it. Whatever this calculation is doing (and I don't understand it) it's not working right, and I can't even overwrite with CSS as the added element height is overriding it.

**Comment by AMBudnik** [comment]
In your Fiddle there are two issues cause it takes one of `minSpareRows` for spare column header row. Thanks for sharing - we'll see what we can do in this matter.

**Comment by jonlachlan** [comment]
The code change specified by @cyancdesign resulted in exactly the behavior I'm looking for. The header row no longer gets "stuck" at a max height, the height adjusts fluidly with the word-wrapped text.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
