### ISSUE TITLE
Allow 'beforeOnCellMouseDown' hook to stop event propagation

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2127]
Allow 'beforeOnCellMouseDown' hook to stop event propagation, thus enable the possibility to, for example, disable select-a-whole-column feature after clicking the column header for chosen column.

**Comment by krzysztofspilka** [comment]
Fixed and released in v 0.12.5
See the release notes for it: https://github.com/handsontable/handsontable/releases/tag/0.12.5
