### ISSUE TITLE
Need to catch an event when the dropdown is opened

### ISSUE THREAD

**Issue by mapinales** [handsontable/handsontable#2128]
So I'm having an issue with styling and the dropdown menu.  When opened, the first option is highlighted in gray.  If I mouse over the other options, the highlight follows appropriately.  However, if I hit enter on the cell to open the menu and then use the arrow keys to make my choice, the highlight disappears.  I can see that the highlight is being applied through a class called "current."  My intention is to apply code to the keydown event for the tds to apply/remove the "current" class when the up and down arrows are pressed while that menu is up, but I need an event to use to find all of the tds holding the options when the menu appears.  Especially since the handsontableInputHolder div that holds the menu doesn't exist until a dropdown is used.  Is there an event that can be caught when the dropdown is created and shown?

**Comment by AMBudnik** [comment]
Please provide a demo of your code.

**Comment by AMBudnik** [comment]
Please provide a demo of your code.

**Comment by AMBudnik** [comment]
Issue will be closed in lack of needed demo.
