### ISSUE TITLE
want to save the table in database after editing

### ISSUE THREAD

**Issue by NadirBelhaj** [handsontable/handsontable#2129]
Hi, after editing the rows and cols I want to save the form shape and data inside it in a database can you please tell me if it's possible with handsontable ?? , Thanks

**Comment by Newwer21** [comment]
Hi @NadirBelhaj ,
There is a function *getdata()* . Look at this https://github.com/handsontable/handsontable/wiki/Methods#get-data-methods .
Here an example http://jsfiddle.net/t3fjj1de/

**Comment by NadirBelhaj** [comment]
Thanks a lot Newwer21

**Comment by AMBudnik** [comment]
Thank you @Newwer21 for your support
