### ISSUE TITLE
How to move multiple rows

### ISSUE THREAD

**Issue by WolfgangVonL** [handsontable/handsontable#2130]
Hi,
I'm using manualRowMove feature for rows reordering. I was wondering if it was possible to do the same with multiple rows ? Perhaps combining manualRowMove with another feature...

Thanks

Wolfgang

**Comment by AMBudnik** [comment]
We don't provide such a functionality although it's a interesting idea. Let me write it down as a proposition for a feature.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Now we are able to move multiple rows https://docs.handsontable.com/0.31.2/demo-moving.html However they need to be one after the other

**Comment by abhinavsarja** [comment]
Hi @AMBudnik ,

  I am finding difficulty in selecting the rows to move. 
By just highlighting multiple adjacent rows and dragging, it does not consistently select all rows.

Any suggestion on how to select the rows before moving??

**Comment by AMBudnik** [comment]
Hey @abhinavsarja 

Moving does not support moving non-adjacent rows yet. The list of limitations is posted here https://github.com/handsontable/handsontable/issues/4817

**Comment by abhinavsarja** [comment]
Hi @AMBudnik ,

  Yes I am aware of that. Even if adjacent rows can you please let me know if just highlight and drag should work? Currently even in your example , it does not consistently work

**Comment by AMBudnik** [comment]
Can you share a demo and a video that shows the issue? I've tried to replicate it using this demo https://handsontable.com/docs/7.1.1/demo-moving.html but it works well.
