### ISSUE TITLE
Editing 1 cell resets classes, styles on all cells?

### ISSUE THREAD

**Issue by ap87** [handsontable/handsontable#2131]
Why is it that when you are editing a cell, the 'after selected' or the 'after change' event or whatever it is, is resetting all cells classes and styles?
I have 'manually' styled some cells in the DOM and maybe its supposed to whipe every style when 1 cell is edited...

Is it posible to disable some events or something else that would solve my problem?

thx

**Comment by SnareHanger** [comment]
Agree with this.  I've got custom filter icons in the headers that are bound to events and the events get cleared every time an edit is made

**Comment by jansiegel** [comment]
@ap87 Handsontable re-renders the cells after making most of the changes to the table. To permanently assign classes to the cells, you can use the `cells` config option.

Take a look at this example: http://jsfiddle.net/js_ziggle/njdxjohn/

@SnareHanger, modifying the column headers requires a different approach. I think the *custom renderers* section of our docs might be helpful in this case: http://docs.handsontable.com/demo-custom-renderers.html#page-header
