### ISSUE TITLE
Cannot read property 'startColumn' of undefined

### ISSUE THREAD

**Issue by danio7** [handsontable/handsontable#2132]
Hello,

When I upgraded to 0.12.3, I started getting this issue upon page load. I have to clear all my cache and it goes away, but comes back again.

0.12.4 has the same problem.

"Cannot read property 'startColumn' of undefined"

If you need more information I will gladly provide it.

Thanks!
Daniel

**Comment by Berus** [comment]
@danio7 could you prepare some demo on jsfiddle or jsbin?

**Comment by marcok** [comment]
Same problem here. As soon as i sort a table and reload "startColumn' of undefined"
After clearing 
getProducersGrid__persistentStateKeys:["columnSorting"]
getProducersGrid_columnSorting: {"sortColumn":0,"sortOrder":false}
It works again.

Version 0.12.5

**Comment by danio7** [comment]
Did Marcok's explanation help? If not, I will try and assemble a demo.

Thanks

**Comment by danio7** [comment]
Still persisting in Version 0.12.6. Could this bug be looked at as it completely crashes the widget rendering it inoperational on page load.

**Comment by AMBudnik** [comment]
Please provide a [JSFiddle](http://jsfiddle.net/api/post/library/pure/) demo.

**Comment by marcok** [comment]
workaround: deactivate the sort storage

**Comment by AMBudnik** [comment]
I assume this is not an issue any more cause of more than a month without a demo or any other questions.
