### ISSUE TITLE
The row inside fixed columns not getting highlighted during row move

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#2133]
This is not a bug exactly ....but the effect is very confusing.
When trying to move row up and down, the part of that row outside the fixed column area gets highlighted whereas the effect should be such that the whole row needs to get highlighted irrespective of fixed or not..

Though the final result is not a problem but the highlight thing is very confusing as it gives a feeling that the row data withing the fixed section won't get moved but actually it does. 

The fiddle will help to understand: http://jsfiddle.net/461hfpgL/
Select any row and drag up/down. the rows within the fixed area won't get highlighted.

**Comment by AMBudnik** [comment]
You're right that doesn't look pleasant. Thanks for an issue.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
This behavior has changed. Currently, all rows are being highlighted while moving.
