### ISSUE TITLE
Drag and drop from the corner causes error

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2134]
When I drag from the corner and drop above the header then Handsontable throws error:
> Uncaught TypeError: Cannot set property 'to' of null

**Steps to reproduce the problem:**

- Go to http://handsontable.com/demo/scroll_window.html
- Click and drag the corner of handsontable to the left
- Drop the click above any column header

:information_source:
> Handsontable v. 0.12.4
> Windows 8.1
> Chrome v. 40.0.2214.93 m

![und1](https://cloud.githubusercontent.com/assets/8048526/6040191/445f820a-ac6f-11e4-88ce-378b847df49b.jpg)

**Comment by krzysztofspilka** [comment]
Connected with #2099

**Comment by jansiegel** [comment]
Released in version 0.12.6
