### ISSUE TITLE
How to create a readonly comment?

### ISSUE THREAD

**Issue by mburbea** [handsontable/handsontable#2136]
I have a column that is readonly with specific comments placed through the cells function. Since the content is readonly is there a way to specify that the comment itself should only be readonly?

Also, is there any reason that after sorting comments no longer work on hover, but only on clicking the cell?

**Comment by AMBudnik** [comment]
Our comment option is still in beta mode, so there could be a few bugs.

We do not have a read only comments right now, but I guess it's a good idea to have this kind of choice to make them not editable for users.

**Comment by phasjim** [comment]
Yes, I would very much appreciate readOnly comments too. Thank you :+1:

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
For all interested users. Here's a method you can use

```
cell: [
  {row: 1, col: 1, comment: {value: 'Some comment', readOnly: true}},
  {row: 2, col: 2, comment: {value: 'More comments', readOnly: true}}
]
```

**Comment by small75** [comment]
At runtime:
hot.getPlugin('comments').updateCommentMeta(row, col, {readOnly: true });
