### ISSUE TITLE
Sorting Header Classes

### ISSUE THREAD

**Issue by ronpsp** [handsontable/handsontable#2139]
This does not work:

```javascript
afterColumnSort: function (col, order) {
						
	var th = $('thead th', this.table)
					.removeClass('sort_asc sort_desc')
					.get(col + 1);
	
	$(th).addClass('sort_' + (this.sortOrder ? 'asc' : 'desc'));
	
},
```

I think every time a column header is clicked/sorted, it is being regenerated. Is there a way to retain the classes of the TH element? Or maybe provide an option to set class names for sorting (ascending and descending). My aim is to put an `:after` style to the currently sorted header to create an icon effect.

Let me know what you think. Thanks!

**Comment by jansiegel** [comment]
@ronpsp I believe it's not a case of headers 'regenerating', but rather an issue with class assignment.
In your callback you're referring to `TH`s in the `ht_master` table, which is visibly hidden under `ht_top` overlay. If you assign the classname to `TH`s in all 'overlays', this should work fine.

Try this snippet, hope it will help!
```javascript    
afterColumnSort: function (col, order) {
  var theads = this.rootElement.querySelectorAll('thead'),
    thead,
    th,
    ths;

// clear all the class leftovers
  for (var i = 0, theadsLength = theads.length; i < theadsLength; i++) {
    thead = theads[i];
    ths = theads[i].querySelectorAll('th');
    for (var j = 0, thsLength = ths.length; j < thsLength; j++) {
      Handsontable.Dom.removeClass(ths[j], 'sort_asc');
      Handsontable.Dom.removeClass(ths[j], 'sort_desc');
    }
  }

// assign the wanted classname
  for (var i = 0, theadsLength = theads.length; i < theadsLength; i++) {
    th = theads[i].querySelector('th:nth-child(' + parseInt(col + 2, 10) + ')');
    if (th) {
      Handsontable.Dom.addClass(th, 'sort_' + (order ? 'asc' : 'desc'));
    }
  }
}
```

**Comment by ronpsp** [comment]
Thanks, @jansiegel. That worked perfectly! However, it only takes effect *after* sorting even if I used the same function (with some modifications) in `beforeColumnSort` or `afterLoadData`. I'm trying to put the class before sorting (the `columnSorting` option is set).

```javascript
columnSorting: {
	column: 1,
	sortOrder: true
},
```

**Comment by rgsiverd** [comment]
@jansiegel This was perfect for what I needed.  You saved a lot of time.  Thank you!

**Comment by jansiegel** [comment]
@rgsiverd Glad I could help!
