### ISSUE TITLE
Text in cells is always trimmed

### ISSUE THREAD

**Issue by danelkhen** [handsontable/handsontable#2140]
Sometimes whitespace at the beginning / end is important, is there a way to disable the string trim and preserve whitespace as/is when entering/exiting a cell?

p.s. Great work, looks awesome!

**Comment by jansiegel** [comment]
@danelkhen Currently we don't support that functionality, but it's worth considering!

**Comment by danelkhen** [comment]
Thanks @jansiegel, great work!

**Comment by jansiegel** [comment]
@danelkhen With the release of the next (`0.12.6`) version of Handsontable, we will add a `trimWhitespace` option for columns/cells. By deafault it's set to `true`, to remain consistency with previous versions, but if you set it to `false`, no content whitespace will be trimmed.

**Comment by danelkhen** [comment]
Awesome! Thank you @jansiegel, great work you guys!

**Comment by krzysztofspilka** [comment]
@jansiegel let's add this to gh wiki, paste a reference link and then close the issue.

**Comment by jansiegel** [comment]
Released in version 0.12.6
