### ISSUE TITLE
When dragging a large cell selection, moving your cursor back inside the table will jump the viewport

### ISSUE THREAD

**Issue by adi-pjackson** [handsontable/handsontable#2142]
jsfiddle to demonstrate the issue: http://jsfiddle.net/6tsk1ef5/2/

As an example, say I want to make a selection from A1 to A50, I would:
- Mousedown in A1
- Move mouse below the table so drag-to-scroll starts
- Now you that you can see row 50, move your mouse back inside the table to complete your selection
At this point the scroll position jumps to make A1 visible again.

I can't think of a case where you'd want the viewport you created using drag-to-scroll to be destroyed like this.

**Comment by jansiegel** [comment]
Definitely a bug, thanks for reporting, @adi-pjackson!

**Comment by adi-pjackson** [comment]
Submitted a pull request with a potential fix: https://github.com/handsontable/handsontable/pull/2143

**Comment by jansiegel** [comment]
This issue seems to be fixed with the changes from #2147

**Comment by adi-pjackson** [comment]
Yes, the fix for https://github.com/handsontable/handsontable/issues/2147 has addressed this issue. Thanks!
