### ISSUE TITLE
Allow Custom Sorting

### ISSUE THREAD

**Issue by ronpsp** [handsontable/handsontable#2145]
Can you allow `beforeColumnSort` to `return false;` so that we can use custom sorting functions? Thanks!

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
The feature has been already added as the sortFunction - more at https://docs.handsontable.com/pro/1.15.0/Options.html#sortFunction

Thank you for the suggestion

**Comment by AMBudnik** [comment]
This functionality has been renamed to `compareFunctionFactory` (further explained at https://handsontable.com/docs/8.3.2/demo-sorting.html)
