### ISSUE TITLE
Auto Complete error

### ISSUE THREAD

**Issue by cyadriane08** [handsontable/handsontable#2146]
![capture8](https://cloud.githubusercontent.com/assets/8772241/6124176/2c34d348-b146-11e4-8a43-fcdc4f36b320.PNG)
![capture9](https://cloud.githubusercontent.com/assets/8772241/6124177/2c60f554-b146-11e4-99ca-323e76ff5b65.PNG)

According to the photo, "ABREEZA MALL EXPANSION" is in the list however, cell validation occurs and makes it highlighted in red indicating it as error or no value in the list. Is there any special case or special value to avoid where cell validation read it as error even though the value is in the source?

**Comment by krzysztofspilka** [comment]
@cyadriane08 could you prepare a JSFiddle on that?

**Comment by AMBudnik** [comment]
Issue had to be closed in lack of demo for more than a 2 months.
