### ISSUE TITLE
Multiple cells selection with shift doesn't scroll the table

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2147]
Selection hides 'under' the fixed headers when selecting multiple cells with SHIFT key. The entire table should be scrolled up when switching between e.g. A2 (fixed) > A3 (not fixed) and A3 is outside the viewport.

**Steps to reproduce the problem:**

- Go to http://handsontable.com/demo/fixed.html
- Scroll down the table slightly
- Select cell A2 (by mouse-click)
- Press and hold shift and start pressing down arrow key

:information_source:
> Handsontable v. 0.12.5
> Windows 8.1
> Chrome v. 40.0.2214.111 m

**Comment by krzysztofspilka** [comment]
@jansiegel Seems to be working fine but I've got double borders that didn't appear before.

![double-border](https://cloud.githubusercontent.com/assets/8048526/6265035/cd7f6f1c-b829-11e4-9fc8-5c57db8b6c84.png)

**Comment by jansiegel** [comment]
Released in version 0.12.6
