### ISSUE TITLE
Handsontable not working very well as CustomElement

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#2148]
Some of basic features don't work when Handsontable is used as web components (hot-table).

--------

##### Steps to reproduce:

* Go to http://handsontable.github.io/hot-table/
* First bug: Edit first name and try to delete string pressing `DELETE` key 
* Second bug: When we try to clone/copy the cell by grabbing her corner and stretching after mousedown event the selection disappears.

**Comment by budnix** [comment]
Associated with https://github.com/handsontable/hot-table/issues/3

**Comment by jansiegel** [comment]
Released in version 0.12.6
