### ISSUE TITLE
Multiple handsontable on a page causes comment rendering issues

### ISSUE THREAD

**Issue by mburbea** [handsontable/handsontable#2149]
![image](https://cloud.githubusercontent.com/assets/213233/6131912/43e1f788-b11d-11e4-86e2-398049c217f2.png)
I have a grid that appears on a page and when a button is clicked a modal will appear which contains another table. 

Once the second handsontable disappears the comments no longer render text, and appear far away from their correct position. The following error messages appear::
```
Uncaught TypeError: Cannot read property 'position' of undefined handsontable.full.js:2817
Uncaught TypeError: Cannot read property 'offsetLeft' of undefined
```
Looking it over it apears to be coming from this function `Handsontable.Dom.offset` which for whatever reason is expected a TD element but is actually getting a `-1`.

**Comment by AMBudnik** [comment]
If you still face this issue - please update to 0.14.1 and provide a demo of your code.

**Comment by krzysztofspilka** [comment]
https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
