### ISSUE TITLE
AutoComplete cell -  improper alignmnt 

### ISSUE THREAD

**Issue by kathiresn** [handsontable/handsontable#2150]
![handsontable](https://cloud.githubusercontent.com/assets/10954204/6143147/35aadf28-b1e9-11e4-83d8-4ff82b1db11b.png)

**Comment by krzysztofspilka** [comment]
@kathiresn works for me. Could you help me in reproducing this issue?

**Comment by kathiresn** [comment]
@krzysztofspilka    Type Nissanssssss in autocomplete cell and press backspace,you 'll face this.it's just a small issue.Really treat to use handsontable

**Comment by AMBudnik** [comment]
I couldn't reproduce it to, do you still have the same issue?
