### ISSUE TITLE
Column sorting highlights the entire column.

### ISSUE THREAD

**Issue by mburbea** [handsontable/handsontable#2151]
Using the sort feature causes the column to be highlighted this seems a bit bizarre and undesirable.
It could also be nice to have an indicator to show which col is sorted and direction.

**Comment by AMBudnik** [comment]
Thank you for suggestions.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Sorting indicator has been added in v0.15.0-beta3

https://docs.handsontable.com/pro/Options.html#sortIndicator

**Comment by swistach** [comment]
Hi @mburbea,
You can use `beforeOnCellMouseDown` hook to stop the selection mechanism.
Here is an example: http://jsfiddle.net/8xyh4bvq/
