### ISSUE TITLE
Simplify EventManager

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#2153]
Currently, EventManager follows a Multiton pattern. Some problems of this approach are discussed here: http://en.wikipedia.org/wiki/Multiton_pattern. For us, it means that the development of new plugins, editors and renderers is not as easy as it could be.

EventManager should be simplified by removing the `instance` parameter from the constructor. 

The code would become something like this then: 

```js
Handsontable.eventManager = function () {
  var
    addEvent,
    removeEvent,
    clearEvents,
    fireEvent;

  var eventListeners = [];

  //...
```

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
