### ISSUE TITLE
Change column header language

### ISSUE THREAD

**Issue by Nirhe** [handsontable/handsontable#2155]
Hi, Is it possible to change the language of the header? Not the ABC.. one,
i mean the second header with the sub column.
in the example it's:
 ['', 'Maserati', 'Mazda', 'Mercedes', 'Mini', 'Mitsubishi']
Is it possible to support other languages than english?

I've try and currently I get as what you see in the attachment
![handsontable gibrrish](https://cloud.githubusercontent.com/assets/3913475/6176543/6e21b8ac-b308-11e4-91b7-e09b3c793aee.JPG)

**Comment by krzysztofspilka** [comment]
@Nirhe it depends on the language you want to type in. Also make sure that character encoding is properly set. In case you still face the problem, prepare a JSFiddle demo.

**Comment by AMBudnik** [comment]
Issue has to be closed from lack of a demo. If you would have any other questions, please open a new issue.
