### ISSUE TITLE
Events at EventManager not properly cleaned

### ISSUE THREAD

**Issue by D2Phoenix** [handsontable/handsontable#2157]
After some use of handsontable, I have more than 200.000 events registered at EventManager.

**Comment by D2Phoenix** [comment]
As I can see, problem with checkboxRenderer. It's add events, but not remove them

**Comment by AMBudnik** [comment]
Hi @D2Phoenix could you represent the issue with a demo for easier understanding?
Thanks!

**Comment by AMBudnik** [comment]
Issue closed in lack of demo but I really appreciate any help you can provide if this issue still occurs.
