### ISSUE TITLE
Formulas

### ISSUE THREAD

**Issue by andystat** [handsontable/handsontable#2159]
I have cells which contain formulas, e.g. =A1+B1+C1.  

If I click on the column heading to sort the column is not sorted in order of the numeric data that appears in the cells.

I would like to export the table to CSV but it exports the formulas rather than the data.  Can I access the data in the cell rather than the underlying formula?  The images show the result of clicking on the 'total' column header.

![screen shot 2015-02-14 at 21 13 54](https://cloud.githubusercontent.com/assets/6353176/6199693/76f0858a-b48e-11e4-84d3-457970e12f10.png)
![screen shot 2015-02-14 at 21 13 43](https://cloud.githubusercontent.com/assets/6353176/6199694/82d1640a-b48e-11e4-963e-dcf4aab799ef.png)

**Comment by AMBudnik** [comment]
It would be so much easier to help with a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/) of your work.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.
