### ISSUE TITLE
merge cells fails when using fixedColumnsLeft

### ISSUE THREAD

**Issue by i255** [handsontable/handsontable#2162]
the first column is not rendered properly. see:
http://jsfiddle.net/j84390x1/

**Comment by AMBudnik** [comment]
When I added rowHeaders with 'true' value it works fine. Interesting bug, thanks for sharing.

**Comment by AMBudnik** [comment]
[Here's](https://jsfiddle.net/AMBudnik/j84390x1/1/) a little example on how it looks with 0.15.0-beta2

There are two scenarios:
One with `rowHeaders: true` 
One with commented 'rowHeaders' (equal to 'rowHeaders: false`)

![qq](https://cloud.githubusercontent.com/assets/10757813/7473050/525d099e-f338-11e4-9b71-40103ec344d0.gif)

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1

**Comment by lucamaral** [comment]
#2672

**Comment by AMBudnik** [comment]
The issue is still replicable. I've just tested it using v `2.0.0` here https://jsfiddle.net/v5q788nj/

**Comment by wojciechczerniak** [comment]
Duplicate of #2672
