### ISSUE TITLE
Please add documentation for afterChange source "external"

### ISSUE THREAD

**Issue by TheLudd** [handsontable/handsontable#2163]
I noticed today that the `afterChange` event is sometimes triggered with "external" as source. It is often triggered together with other change event which caused my callback, which saves the data to backend, to be called more times than it should. I would highly appreciate if the "external" source was documented.

**Comment by AMBudnik** [comment]
As @engenb wrote in https://github.com/handsontable/handsontable/issues/2527 in the docs there is a 2D array as a result, when it is only a single array as a result of `afterChange`

**Comment by benharrell** [comment]
I also see this issue when using a nested object datasource, found it chasing another issue.  Let me know if you would like more details.

**Comment by swistach** [comment]
Hi folks, predefined sources are described here: http://docs.handsontable.com/0.32.0-beta2/tutorial-using-callbacks.html#page-source-definition
Feel free to send suggestion, what else should be on list.
