### ISSUE TITLE
pleas add example how to add border-spacing

### ISSUE THREAD

**Issue by ZigGreen** [handsontable/handsontable#2164]
if apply css rule width of container calculates wrong way

**Comment by AMBudnik** [comment]
Hi, Did you chages ```border-spacing``` in ```.handsontable table.htCore``` class (60 line: ```handsontable.full.css```)?

**Comment by ZigGreen** [comment]
yeap
[I'll try it](http://jsfiddle.net/hU6Kz/3298/) but it looks kind of weird, and main point is that a table doesn't fits its container.

**Comment by AMBudnik** [comment]
I guess it could be a better idea how to achieve what you're looking for. Can you provide a example of a normal (static) table with the look that you desired?

**Comment by ZigGreen** [comment]
I actually want to achieve [the following result](http://jsfiddle.net/hU6Kz/3301/)

**Comment by AMBudnik** [comment]
OK, I see the row's and col's headers appear after a click into grid's body and it should not act like this.

For now you can comment 498-499 lines in `handsontable.full.js` which is `.handsontable .handsontable table` it holds shadows which appear after we set `border-spacing` to value > 0

**Comment by ZigGreen** [comment]
Row's and col's headers are not actually the point. Main issue that you can't place a table next to another table. Please look at [the example](http://jsfiddle.net/hU6Kz/3306/).

**Comment by AMBudnik** [comment]
Hm... only thing I can propose is:

1. Set `.handsontable` to `overflow: overlay` when you would like to have red bordered div like a static element, cause unfortunately when we set `height: 100%` it (like you said before) does not look as expected. 

or

2. Set everything after creating the table like [here](https://jsfiddle.net/hU6Kz/3307/)

none of this examples provide 'good practices' but I guess it's the only easy way to achieve your goal right now.

**Comment by ZigGreen** [comment]
I've found that the issue can be fixed by patching functions that performs row's and col's size computation. I've applied following changes:  
```javascript
WalkontableHorizontalScrollbarNative.prototype.sumCellSizes = function (from, length) {
  var sum = 0;
  // get a horizontal spacing
  var borderSpacing = ~~window.getComputedStyle(this.TABLE).borderSpacing.split(' ')[1].slice(0,-2); 
  sum += borderSpacing;
  while(from < length) {
    sum += this.instance.wtTable.getStretchedColumnWidth(from) || this.instance.wtSettings.defaultColumnWidth;
    sum += borderSpacing;
    from++;
  }
  return sum;
};
```

```javascript
WalkontableVerticalScrollbarNative.prototype.sumCellSizes = function (from, length) {
  var sum = 0;
  var borderSpacing = ~~window.getComputedStyle(this.TABLE).borderSpacing.split(' ')[0].slice(0,-2);

  while (from < length) {
    sum += this.instance.wtTable.getRowHeight(from) || this.instance.wtSettings.settings.defaultRowHeight; //TODO optimize getSetting, because this is MUCH faster then getSetting
    sum += borderSpacing;
    from++;
  }
  return sum;
};
```

And desired result was reached :smile:
