### ISSUE TITLE
Custom row grouping to display tree structure

### ISSUE THREAD

**Issue by Narayanan12345** [handsontable/handsontable#2165]
Hi,

Handsontable  is a great plugin for virtual rendering, I have used this plugin in my application, currently I have struggled in some issues in row and column grouping.

How to display the tree structure in handsontable..

ex:
Parent
     Child
        SubChild1
           SubChild11
           SubChild12
        SubChild2
           SubChild21
           SubChild22

When I have implemented tree structure using row grouping 

1.I need to hide the number in grouping.
2.The grouping button should be collapse when initially page load.
3.Group column header is broking.

Please guide me, how to fix the above issues in handsontable.
Kindly revert back if you need any other related things.

Regards
P.Narayanan

**Comment by AMBudnik** [comment]
We do not have a grouping option for cells yet, but please prepare a [JSFiddle](https://jsfiddle.net/api/post/library/pure/) and we'll try to help.

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply.
