### ISSUE TITLE
copy/paste doesn't work correctly with format de

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#2166]
Hi,
I reproduce the problem on http://handsontable.com/demo/numeric.html
on the column (Price (€)) and the row Mercedes A160, i type 22,10,
i click enter then have the correct value 22,10 €.
if i copy this cell (ctrl + c) an i paste (ctrl+v) for the row "Citroen C4 Coupe" 
and the column (Price (€)) i have the wrong value 221,00€ 

if i use the fill vertical action, i have the correct value
if i enter another value like 22,11 it works .

regards
jean marc

**Comment by jeanmarc78** [comment]
i fix the issue in handsontable.full.js for the function function validateChanges(changes, source, callback).

i replace
            // this input in format XXXX.XX is likely to come from paste. Let's parse it using international rules
            else if (changes[i][3]===len - 3 && changes[i][3].indexOf(",") === -1) { 

with
            // this input in format XXXX.XX is likely to come from paste. Let's parse it using international rules
            else if (changes[i][3].indexOf(".") != -1 && changes[i][3].indexOf(",") === -1) {

**Comment by jeanmarc78** [comment]
i continue my private discussion,
i found a better workaround , i think

i add 	     if (cellProperties.language == 'de')
			{
			   changes[i][3]=changes[i][3].replace('.',',');
			   changes[i][3]=changes[i][3].replace(' ','');
			}
for the function :

function validateChanges(changes, source, callback) {
    var waitingForValidator = new ValidatorsQueue();
    waitingForValidator.onQueueEmpty = resolve;

    for (var i = changes.length - 1; i >= 0; i--) {
      if (changes[i] === null) {
        changes.splice(i, 1);
      }
      else {
        var row = changes[i][0];
        var col = datamap.propToCol(changes[i][1]);
        // column order may have changes, so we need to translate physical col index (stored in datasource) to logical (displayed to user)
        var logicalCol = instance.runHooks('modifyCol', col);
        var cellProperties = instance.getCellMeta(row, logicalCol);

        if (cellProperties.type === 'numeric' && typeof changes[i][3] === 'string') {
          if (changes[i][3].length > 0 && (/^-?[\d\s]*(\.|\,)?\d*$/.test(changes[i][3]) || cellProperties.format )) {
            var len = changes[i][3].length;
		
			if (cellProperties.language == 'de')
			{
			   changes[i][3]=changes[i][3].replace('.',',');
			   changes[i][3]=changes[i][3].replace(' ','');
			}

**Comment by krzysztofspilka** [comment]
Hi @jeanmarc78, let me just mark this issue to be checked later. Thanks for reporting!

**Comment by ereboucas** [comment]
@jeanmarc78 thanks for your workaround. I applied it on 0.11.4 and worked like a charm.

**Comment by AMBudnik** [comment]
Confirmed. When you:

1. type as @jeanmarc78 described
2. edit other cell (no matter which)
3. click <kbd>enter</kbd> on our `22,10€` cell
4. `22,10€` cell becomes `221,00€`

**Comment by jeanmarc78** [comment]
hello, 
is it possible to increase the bug priority ?
  because each time a new release is out,
i have to put the workaround.

best regards
jm

**Comment by krzysztofspilka** [comment]
@jeanmarc78 will do. Just added to the milestone 0.18.1 so we don't loose it from our sight.

**Comment by AMBudnik** [comment]
might be related to https://github.com/handsontable/handsontable/issues/2617

**Comment by AMBudnik** [comment]
Still reproducible in 0.26.0 (switched to numbro)

**Comment by ClaudineiFernandes** [comment]
still reproducible in [https://docs.handsontable.com/pro/1.5.0/demo-numeric.html](url)

**Comment by AMBudnik** [comment]
@jeanmarc78 @ClaudineiFernandes 
This bug was tracking us like a shadow on every update and finally we fixed it. I hope it works fine in your projects as well. If you could fine a moment to test it I would be more than happy. 

Thanks in advance!

**Comment by AMBudnik** [comment]
After more testing I guess that this implementation solved our issue.
Glad it's working fine, thanks @swistach
