### ISSUE TITLE
ajax webpage sample not work in Firefox 35

### ISSUE THREAD

**Issue by eurrea** [handsontable/handsontable#2168]
The autosave and save button in the ajax demo you guys have in handsontable.com are not working in Firefox 35.  It's working fine in IE 11 and Chrome 40 though

**Comment by snkashis** [comment]
Seems to work fine for me in Firefox 36.0.1. You had an error thrown in console?

**Comment by eurrea** [comment]
HI there, I checked again this time in Firefox 36.0.1 and it's working!
