### ISSUE TITLE
Line height is being changed when editing cell

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2169]
Line height is being changed when the cell is in edit mode. It should be done with pixel perfect accuracy.

**Steps to reproduce the problem:**

- Go to http://handsontable.com/
- Edit any cell

:information_source:
> Handsontable v. 0.12.5
> Windows 8.1
> Chrome v. 40.0.2214.111 m

![line-h](https://cloud.githubusercontent.com/assets/8048526/6230773/9647e730-b6c2-11e4-8b33-8b3dc6af3444.gif)

**Comment by jansiegel** [comment]
Should be fixed with #1918

**Comment by AMBudnik** [comment]
Released: v0.12.6
