### ISSUE TITLE
Selecting cell when handsontable is in the scrollable container result in scroll to top

### ISSUE THREAD

**Issue by Hiwer** [handsontable/handsontable#2170]
When I have handsontables inside container with scroll and want to select cell in different row then first row it scrolls to top. Everything works if handsontable is not in the scrollable container or when 'window' is parent container for the table.

In previouse version of the handsontable it worked well and after update to version 0.12.5 it started behave strange. 

jsfiddle with issue: http://jsfiddle.net/6tsk1ef5/13/

**Comment by krzysztofspilka** [comment]
@Hiwer thanks for reporting & demo. We're working on this but probably we'll incorporate fix for this into v. 0.12.7, to be released on March 5.

**Comment by krzysztofspilka** [comment]
@Hiwer could you confirm that you're no longer facing that issue?

**Comment by Hiwer** [comment]
@krzysztofspilka 
In the newest version everything works as it should.

Thanks!
