### ISSUE TITLE
First column looses visibility when moving with keyboard arrows.

### ISSUE THREAD

**Issue by petheof** [handsontable/handsontable#2171]
When we have a table with fixed width and overflow scroll, if we navigate using keyboard arrow keys to the right and then back to the first column, although the cell is selected, it is not visible (the cell and the first column).

JsFiddle with instructions to reproduce the issue:
http://jsfiddle.net/6tsk1ef5/17/

**Comment by AMBudnik** [comment]
I couldn't reproduce this issue with your demo. I tried:
* Chrome 41.0.2272.89 (64-bit)
* Firefox 36.0.1

If you still have this issue, please provide information about browser/system that you are using, and we'll reopen the issue.
