### ISSUE TITLE
Text Editor enlarging by a few pixels vertically when starting typing

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2176]
Since `0.12.6` Text Editor is enlarging vertically (by about 2px) after starting typing.

![enlarging](https://cloud.githubusercontent.com/assets/7397134/6268900/3767ae8c-b850-11e4-95ce-0567c02a6aa7.gif)

**Comment by krzysztofspilka** [comment]
@jansiegel Ideally borders shouldn't be changed, we can keep this shadow though as it distinguishes Handsontable from other datagrids.

A screenshot from excel 2013:

![gif](https://cloud.githubusercontent.com/assets/8048526/6285279/127687ba-b8fa-11e4-8a3e-a8d4c24350dc.gif)

**Comment by warpech** [comment]
Beautiful! :heart_eyes:
