### ISSUE TITLE
DropDown Headers

### ISSUE THREAD

**Issue by okahara** [handsontable/handsontable#2177]
I am using Handsontable with SheetJS to turn Excel sheets into JSON data to make d3.js graphs.  I know there is a demo to change the cell types based on a dropdown in the header but is there a way to make the header dropdown be able to change the header value.

The header dropdown to change the header value will allow for better copy/paste to fit the formatting I need.  I have already implemented SheetJS and Handsontable to inherit the headers while drag and drop.

Thank you

**Comment by AMBudnik** [comment]
Hi @okahara can I help you with anything currenty?

**Comment by AMBudnik** [comment]
I'm closing this issue in lack of reply but if you'll need anything @okahara do not hesitate to leave a comment.
