### ISSUE TITLE
Issue with added show/hide buttons

### ISSUE THREAD

**Issue by sjp700** [handsontable/handsontable#2180]
The attached code works to show /hide the table, however, clicking inside a cell to edit moves the cell to a different location outside the table!
script
function myHideFunction() {
     document.getElementById("example1").style.display = "none";
 }

 function myShowFunction() {
     document.getElementById("example1").style.display = "initial";
 }

html
<button onclick="myShowFunction()">Show it</button>
<button onclick="myHideFunction()">Hide it</button>

**Comment by krzysztofspilka** [comment]
We'd need a JSFiddle to give it a closer look.

**Comment by sjp700** [comment]
Hi,
For some reason I can't get the buttons to work with JSFiddle.   I'm using Visual Studio Express and the ajax.html page from the latest release.  I added the the 2 functions above to the script and these 2 buttons before the load button:
button onclick="myShowFunction()">Show it</button
button onclick="myHideFunction()">Hide it</button

It works fine until you do a Hide then Show and try to edit a cell.

**Comment by AMBudnik** [comment]
Sorry, without a demo there is nothing we can do.

**Comment by AMBudnik** [comment]
We have to close this issue in lack of demo for more than a month, but we'll reopen it when you provide a demo.
