### ISSUE TITLE
Issues of datepicker in 0.12.6

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2181]
@Berus we need to fix some issues that came up while testing v. 0.12.6. All of them are connected with replacing jQuery datepicker with Pikaday (#1568). Please find the list below (regarding demo http://handsontable.com/demo/date.html):

- Select a cell with a date and start typing. Instead of replacing existing content the new text is being written at the end of it.

![screenclip 3](https://cloud.githubusercontent.com/assets/8048526/6285906/bcd99254-b901-11e4-9189-2e983935b1e1.png)

- Start editing a cell (write anything inside it), then press `ESC` key. Instead of cancel changes it saves them.
- Wrong position and order of a date picker, it hides under the cell.

![screenclip 4](https://cloud.githubusercontent.com/assets/8048526/6285927/20055890-b902-11e4-9524-72f557f59a74.png)

- Start editing a cell and press `ESC`. The fill handle is gone.
- Click on an arrow down in a cell A1 ("Mercedes"), just once. Now you should have opened a dropdown list. Now click on a cell A2 ("A160"). The fill handle is gone.

![screenclip 5](https://cloud.githubusercontent.com/assets/8048526/6285984/d71f53e6-b902-11e4-9adc-ebdbe8511c2d.jpg)

- Open a datepicker and click on the name of month. A selection of months appears only for a fraction of a second, then datepicker is being closed. If you click & hold then you should be able to see the entire list (at least on Chrome/Windows).

![screenclip 6](https://cloud.githubusercontent.com/assets/8048526/6286033/39e69228-b903-11e4-9abe-a1c828bb6343.png)

:information_source:
> Handsontable v. 0.12.6
> Windows 8.1
> Chrome v. 40.0.2214.111 m

**Comment by jansiegel** [comment]
Another issue reported in #2188.

**Comment by krzysztofspilka** [comment]
Still left to do:

> Select a cell with a date and start typing. Instead of replacing existing content the new text is being written at the end of it.

All other tasks confirmed as fixed and

> Click on an arrow down in a cell A1 ("Mercedes"), just once. Now you should have opened a dropdown list. Now click on a cell A2 ("A160"). The fill handle is gone.

turned out to be not connected with Pikaday so I opened a new task for it: #2230
