### ISSUE TITLE
Up-arrow key doesn't work properly while editing

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2182]
You can't navigate within a multiple lines of text inside a cell using `up-arrow` key.

**Steps to reproduce the problem:**

- Go to http://handsontable.com/
- Type in at least two lines of text into a cell (use `ALT+ENTER`)
- Place the cursor at the bottom of a cell
- Press `up-arrow` key to move to the line of text above

:information_source:
> Handsontable v. 0.12.5
> Windows 8.1
> Chrome v. 40.0.2214.111 m

![screenclip 7](https://cloud.githubusercontent.com/assets/8048526/6286299/50b2e292-b906-11e4-91f8-4aadaa4a7878.jpg)

**Comment by codingsteff** [comment]
Also it would be nice, if we could insert a new line with just hitting `ENTER`.
Maybe with a new column option `multline : true`

**Comment by homanchou** [comment]
I see the benefit of disabling arrow keys navigation for text editing.  What about re-enabling the previous behavior (turn on arrow keys for cell navigation), for numeric cell types?

**Comment by johnnychen** [comment]
autocomplete arrow selection doesn't work -_-
