### ISSUE TITLE
Applying validation right after change

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2183]
Validation should be applied right after change, not like currently when I need to focus on a different cell to see if the new content was validated.

**Steps to reproduce the problem:**

1. Go to http://handsontable.com/demo/validation.html
2. Using fill handle change the value of a cell in "IP" column
3. Select any other cell

:information_source:
> Handsontable v. 0.12.5
> Windows 8.1
> Chrome v. 40.0.2214.111 m

![validation-anim](https://cloud.githubusercontent.com/assets/8048526/6286480/21676d6c-b908-11e4-98a4-0f66fcbdfda8.gif)

**Comment by jansiegel** [comment]
This is not the issue of cell not validating, but rather validation styling being overwritten by the sell selection styling (red background becomes blue, although the `htInvalid` class is still applied).

This should be resolved along with #1900

**Comment by krzysztofspilka** [comment]
Fixed in #1900
