### ISSUE TITLE
pikaday z-index problem

### ISSUE THREAD

**Issue by surfncode** [handsontable/handsontable#2185]
pikaday is wrapped into a div with class htDatepickerHolder. This div has z-index 99. Although pikaday widget has z-index 9999, for some reasons (maybe the float trick in pikaday.css), it seems to be ignored by browser. In the end, the pikaday widget has a maximum z-index of 99.

As a dirty fix, I tried setting the z-index of htDatepickerHolder to 9999 and it worked.

**Comment by krzysztofspilka** [comment]
Connected with #2181 #2188

**Comment by Berus** [comment]
fixed in #2181
