### ISSUE TITLE
Moving between cells with keyboard is not synchronized with scrollbars if width and height is not set

### ISSUE THREAD

**Issue by stas-s** [handsontable/handsontable#2187]
http://jsfiddle.net/sjx54bpd/1/

**Comment by AMBudnik** [comment]
Thanks for noticing that, I've reproduced it on few browsers and it definitely occurs, when width is not defined.

**Comment by krzysztofspilka** [comment]
@stas-s I can't reproduce it in 0.15.0-beta3, could you confirm that works for you now?

**Comment by krzysztofspilka** [comment]
This is working fine in 0.17.0
