### ISSUE TITLE
Pikaday and custom date format

### ISSUE THREAD

**Issue by ollietreend** [handsontable/handsontable#2188]
Hi,

I am using a custom date format (DD/MM/YYYY) on a date column.

When I open the pikaday date picker, it interprets my dates as MM/DD/YYYY (default format) values, disregarding my custom date format. When choosing a date it reverts back to my custom format.

With dates in format DD/MM/YYYY, the date value "01/02/2015" should be represented as 1st February. However when you open the datepicker it loads it in as 2nd January.

## Steps to reproduce

1. Open this [example JSFiddle](http://jsfiddle.net/kdkszcyb/1/).
2. Click a cell to open the date picker. Notice that it has interpreted "01/02/2015" as 2nd January (i.e. MM/DD/YYYY).
3. Choose a new date. You can even pick the currently highlighted date.
4. The new date will be set in DD/MM/YYYY format.

This happens every time the pikaday calendar is opened.

**Comment by jansiegel** [comment]
Confirmed, we'll have to fix it along with with the other tweaks from #2181.

Thanks, @ollietreend!

**Comment by ollietreend** [comment]
@jansiegel Do you have an estimated time for this to be patched? I have a project that will need it by the end of this week. I'm happy to fork and tend to this myself to help speed things up – I'm hoping it'll be relatively straightforward to fix.

Do you have any tips on where I should start? A brief look at [/src/editors/dateEditor.js](https://github.com/handsontable/handsontable/blob/master/src/editors/dateEditor.js) suggests that it may hold they key to solving this. I can see that the default date format is configured here, but I can't seem to find where the column config is pulled in and merged in. And if the fact that this isn't happening is the problem, then I'm not sure how to access the column config and overwrite the defaults.

As an aside, I also don't see any reference to the `correctDate` config key. Perhaps that has been missed out of the pikaday integration too?

Thanks

**Comment by krzysztofspilka** [comment]
@ollietreend this will be released no sooner than March 5. To track progress in the current milestone please check https://github.com/handsontable/handsontable/milestones/0.12.7

**Comment by Berus** [comment]
fixed in #2181
