### ISSUE TITLE
Selecting a wide cell is moving the table

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2190]
When selecting a cell that is partly outside the viewport the table is aligning to the right edge of the cell. In MS Excel and Spredsheets table doesn't move. Maybe we should change default behavior and keep the current state as a configurable option?

**Steps to reproduce the problem:**

1. Go to http://handsontable.com/demo/column_resize.html
2. Resize column D so it exceeds the viewport
3. Select one of the cells in the column D

:information_source:
> Handsontable v. 0.12.6
> Windows 8.1
> Chrome v. 40.0.2214.111 m

![3f7b76dc0baa0d33ae5c32fdcb46c1a4](https://cloud.githubusercontent.com/assets/8048526/6327793/658211be-bb60-11e4-918a-b4f9d517e2d9.gif)

**Comment by krzysztofspilka** [comment]
We have two options here to consider:

1. Distinguish between clicking a cell and selecting using keyboard arrow keys
2. Add a new feature of setting smooth scroll as an option. By default it would behave just like MS Excel or Google Spreadsheets

**Comment by AMBudnik** [comment]
Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
