### ISSUE TITLE
Grouping scrollbar is not correctly modifying scrollbar height when a row is collapsed.

### ISSUE THREAD

**Issue by mburbea** [handsontable/handsontable#2192]
The grouping plugin has the following code in it. 
```
    modifyRowHeight: function (height, row) {
      if (instance.view.wt.wtTable.rowFilter && isCollapsed({row: row, col: null})) {
        return 0;
      }
```
https://github.com/handsontable/handsontable/blob/master/src/plugins/grouping/grouping.js#L1306

However, this does not work as intended as the scrollbar height is calculated using the following code:
```
WalkontableVerticalScrollbarNative.prototype.sumCellSizes = function (from, length) {
  var sum = 0;
  while (from < length) {
    sum += this.instance.wtTable.getRowHeight(from) || this.instance.wtSettings.settings.defaultRowHeight; //TODO optimize getSetting, because this is MUCH faster then getSetting
    from++;
  }
  return sum;
};
```
https://github.com/handsontable/handsontable/blob/master/src/3rdparty/walkontable/src/scrollbarNativeVertical.js#L65

Because `getRowHeight` returns 0, it is coalesced to the default of 23. Thus this code does not work as intended at all.

A simple quick fix is to change the return statement to `return Number.MIN_VALUE`. This will work as intended.

**Comment by AMBudnik** [comment]
Grouping abbanoded according to https://github.com/handsontable/handsontable/releases/tag/0.18.0
Instead, we're working on a very similiar functionality - Nested Rows

**Comment by AMBudnik** [comment]
Update: grouping will no longer be supported from 0.19.0
