### ISSUE TITLE
How can I exclude rows from copy and paste?

### ISSUE THREAD

**Issue by mburbea** [handsontable/handsontable#2193]
Is there anyway to remove rows from being copy and pasted? If I have selection from say
`[0,0,10,10]` is there a way for me to remove row 1-8 from the CnP value?

I can mark the cells not copyable, but that leaves a blank link in the copy buffer. Which looks very funny.

Is there anyway to remove the blank lines at minimum?

**Comment by AMBudnik** [comment]
We just added this feature in [0.13.1 release](https://github.com/handsontable/handsontable/releases/tag/0.13.1) maybe it would help.
