### ISSUE TITLE
Pikaday - default date 0/0/0000 issue

### ISSUE THREAD

**Issue by ohaucke** [handsontable/handsontable#2194]
Hi,
i'm not sure if this is an issue or just my fault and i hope you can help me.
I've created an HOT with four columns (ID: numeric, Name: text, Present: numeric, Birthday: date) and if set ID/Name/Present and select the arrow from the datefield, the default date is 0/0/0000.

http://jsbin.com/fuduvipeju/1/edit
Enter: ID, Name, Present Value and select the arrow for the datefield
![date](https://cloud.githubusercontent.com/assets/3750494/6357088/1b0b9bc0-bc62-11e4-950a-842685fc180b.png)

**Comment by TheLudd** [comment]
I have the same issue, although it can be a bit random. Would be great if the default date was configurable and defaulted to today.

**Comment by krzysztofspilka** [comment]
Connected with #2181

**Comment by Berus** [comment]
fixed in #2181
