### ISSUE TITLE
Date picker doesn't work in renderers demo

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2195]
In the renderers demo date picker doesn't work.

**Steps to reproduce the problem:**

1. Go to http://handsontable.com/demo/renderers.html
2. Try to invoke date picker

:information_source:
> Handsontable v. 0.12.6
> Windows 8.1
> Chrome v. 40.0.2214.115 m

Connected with #2181

**Comment by Berus** [comment]
fixed in #2181
