### ISSUE TITLE
ColumnSorting is sorting fixed rows also

### ISSUE THREAD

**Issue by iamrohitnigam** [handsontable/handsontable#2197]
I have used 3 fixed rows, but when I click on column header for sorting, it sort complete data along with fixed rows.

I want it should sort by leaving fixed rows.

Here is [jsfiddle](https://jsfiddle.net/iamrohit18/xmw7hy71/2/) of my code.

**Comment by AMBudnik** [comment]
Thank you for that suggestion, I also think that it can be useful.

**Comment by krzysztofspilka** [comment]
@iamrohitnigam this is how MS Excel works like. I'm sure we could allow to set it as an option but by default it should sort the entire column.

**Comment by krzysztofspilka** [comment]
Issue moved to https://github.com/handsontable/handsontable/wiki/Feature-requests

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
