### ISSUE TITLE
Autocomplete and Dropdown are overlapped by column header

### ISSUE THREAD

**Issue by abelharisov** [handsontable/handsontable#2198]
Example:
![16](https://cloud.githubusercontent.com/assets/6592868/6374637/2f6514d6-bd23-11e4-8535-0a31115010ee.png)

**Comment by krzysztofspilka** [comment]
@abelharisov could you describe the issue and, ideally, prepare JSFiddle on that?

**Comment by abelharisov** [comment]
@krzysztofspilka http://jsfiddle.net/gtbj7y7h/
Click on any dropdown cell of first table and one element of options list will be behind the header of second table

**Comment by krzysztofspilka** [comment]
@abelharisov Thanks for the demo, now I get it. I think we can change this behavior in the core but as a workaround just set a higher z-index value for tables with greater stack order.

http://jsfiddle.net/f0mdyurh/1/

**Comment by krzysztofspilka** [comment]
@abelharisov I'm closing this issue as I'm sure it's feasible to fix it using pure css patch.

**Comment by vacho** [comment]
I solved this in my code putting z-index = x to first div (contains handosntable) and z-index = x-1  to second div (contains handosontable).

**Comment by joaopiopedreira** [comment]
HI @vacho, could you elaborate on your previous answer? I'm trying to solve this with z-index too, but to no avail... thanks!
