### ISSUE TITLE
Broken column stretching & column sorting when width is set via flexbox self-align: stretch

### ISSUE THREAD

**Issue by mattkrick** [handsontable/handsontable#2199]
In a previous version, (0.12.3) Setting the container via `self-align: stretch` would cause the column & row headers to be offset & appear duplicates. In this version, that part works but now column stretching & sorting doesn't work.

**Comment by AMBudnik** [comment]
Please update to 0.14.1, here's the [demo](https://jsfiddle.net/srfLdh75/) with `columnSorting: true` and `stretchH: 'all'` which works as expected.
