### ISSUE TITLE
Cell Function and Math Formula

### ISSUE THREAD

**Issue by mojtabakaviani** [handsontable/handsontable#22]
if add cell function such as avg,sum,min,max,count and and can write formula for cell that result calculate form some cells is will bestest jquery excel plugin. you can use jquery.calculation plugin and suggest rename plugin to jquery.excel

**Comment by ping2anilsharma** [comment]
Can any one help to fix this bug :- when we fix freeze the number of column and scroll it horizontally, the freezed columns should not be move.In handsontable freezed columns are also moved when we scroll.
I really need to fix this bug in Internet Explorer.
Its working in all other browser but not in IE.

Please help me.....

**Comment by ping2anilsharma** [comment]
Hi Cabral,

Could you please tell me how to fix scrolling issue after freezing the columns in handsontable. The freezed columns should not be moved. 
Run the page in IE and check it:
http://handsontable.com/demo/column_freeze.html

i will appreciate your prompt response.
Regards
Anil Sharma

**Comment by krzysztofspilka** [comment]
@ping2anilsharma If you mean IE9 and below then note that we stopped supporting them as of Handsontable 0.12.0 (https://github.com/handsontable/handsontable/releases/tag/0.12.0).

**Comment by krzysztofspilka** [comment]
I think this discussion may be continued in https://github.com/handsontable/handsontable-RuleJS

**Comment by hemantmalpot** [comment]
Sorting is not working for formula column.
https://jsfiddle.net/hemantmalpote/vfa0oemp/
The third column do not get sort.
If i click on third column header,  it just sort the other two.

**Comment by AMBudnik** [comment]
Hi @hemantmalpot unfortunately your demo is broken (it doesn't load Handsontable)

**Comment by hemantmalpot** [comment]
@AMBudnik Please go to this  http://jsfiddle.net/api/post/library/pure/ and replace its javascript part from https://jsfiddle.net/hemantmalpote/vfa0oemp/ links javascript part.

**Comment by AMBudnik** [comment]
@hemantmalpot first link provides to an empty document,

**Comment by hemantmalpot** [comment]
@AMBudnik Please go to http://handsontable.github.io/handsontable-ruleJS/ link and click on 'Edit in js fiddle' then replace its javascript part from https://jsfiddle.net/hemantmalpote/vfa0oemp/ links javascript part.

**Comment by AMBudnik** [comment]
Hi @hemantmalpot I changed the demo: https://jsfiddle.net/s01wm1mv/ and I can see what you mean. I guess it depends on the type of an index and if you would have any suggestions/comments please write them here: https://github.com/handsontable/handsontable/issues/2949

**Comment by Kranthi32** [comment]
Hi I tried same as it is only like below but hot.getSourceData of eachrow propvalue is getting null while saving, 

export function sumCalculationRenderer(columnNames,targetColumnName,tableID) {
    return function(instance, td, row, col, prop, value, cellProperties) {
            var sum = 0;
            var isColValue = false;
            columnNames.forEach(function(colName) {
              var colIndex = instance.propToCol(colName);
              var colValue = instance.getDataAtCell(row, colIndex);
              if(parseInt(colValue)>=0){
                isColValue = true;
                  sum += colValue;
              }
              
            });
            if(isColValue){
                var targetColIndex = instance.propToCol(targetColumnName);
               // instance.setDataAtCell(row, targetColIndex, sum); 
               var hot = $('#' + tableID).handsontable('getInstance');
               td.innerHTML = sum; 
               var sourceData = hot.getSourceData()
            } else {
                // Clear the cell's inner HTML
                td.innerHTML = '';
              }
    };
  }   please find JS fiddle https://jsfiddle.net/kranthi2210/68ayj4xe/27/

**Comment by adrianszymanski89** [comment]
Hi @Kranthi32 

I think this issue should be checked with the newer version of Handsontable, as version 7 is no longer supported, and additionally, we introduced many changes with version 8 along with a whole new formulas engine (HyperFormula) with version 9, so I would highly recommend updating to the newest version (13). 

If you strictly need a sum of the values in chosen column, you can basically use the `columnSummary` plugin to handle this: https://handsontable.com/docs/javascript-data-grid/column-summary/
