### ISSUE TITLE
Focusing on a pikaday cell makes autocomplete cells unusable

### ISSUE THREAD

**Issue by TheLudd** [handsontable/handsontable#2200]
In a table with both autocomplete and pikaday cells, if the user focuses on a pikaday cell and then tries to use an autocomplete cell, the content in the autocomplete cell is erased for each key stroke.

This is noticed in Chromium on Ubuntu, and Firefox on Ubuntu

To reproduce: 
 1. Go to http://handsontable.com/demo/date.html
 2. Click on the first cell containing "Mercedes"
 3. Press right arrow twice, so that the date cell is highlighted
 4. Press left arrow twice so that you focus on "Mercedes" again
 5. Try entering something in the "Mercedes" cell. All autocomplete cells are now broken until the page is reloaded

A way to NOT get the behaviour:
 1. Go to http://handsontable.com/demo/date.html
 2. Click with the mouse on a date cell
 3. The behavior above is now impossible to reproduce

I have traced the bug here: https://github.com/handsontable/handsontable/blob/master/src/core.js#L983
If a date field has been focused as in reproduce step 3, the call to `document.activeElement.blur()` dispatches to pikaday and this causes the autocomplete field to be cleared.

**Comment by TheLudd** [comment]
Related to #2181

**Comment by krzysztofspilka** [comment]
+1

**Comment by alvarotrigo** [comment]
+1

**Comment by krzysztofspilka** [comment]
![image](https://cloud.githubusercontent.com/assets/8048526/6731566/fe6b876e-ce45-11e4-8cec-ea79ca31e96b.png)

It looks ugly, though works now.

**Comment by TheLudd** [comment]
@krzysztofspilka Does it look like that after a date cell has been focused on?

**Comment by krzysztofspilka** [comment]
@TheLudd yes, that's exactly how it looks now, though problems with scrollbars are probably not connected with this issue. We'll release that change in an hour.

**Comment by TheLudd** [comment]
Well, many thanks anyway. We will probably do testing today or tomorrow.

**Comment by krzysztofspilka** [comment]
@TheLudd  Good for you, please just open a new issue if you find something. Thanks!

**Comment by krzysztofspilka** [comment]
Released in ver. 0.13.1, full note available here: https://github.com/handsontable/handsontable/releases/tag/0.13.1

**Comment by TheLudd** [comment]
@krzysztofspilka FYI. I can not reproduce the graphical bug. Looks fine to me.

**Comment by alvarotrigo** [comment]
@TheLudd related with [this topic](https://github.com/handsontable/handsontable/issues/2252)
