### ISSUE TITLE
divider not work in context menu

### ISSUE THREAD

**Issue by HedCET** [handsontable/handsontable#2201]
http://jsfiddle.net/yvzhxf9z/

```contextMenu: ['row_above', 'row_below', 'hsep1', 'remove_row']``` don't show a separator between context menu items

**Comment by AMBudnik** [comment]
You're right this demo doesn't work with divider. Guess the only way now it so use [Context Menu with with fully custom configuration](http://handsontable.com/demo/contextmenu.html)

**Comment by AMBudnik** [comment]
The solution is presented in this issue https://github.com/handsontable/handsontable/issues/2827
