### ISSUE TITLE
Detect if there are invalid cells

### ISSUE THREAD

**Issue by ollietreend** [handsontable/handsontable#2203]
Hi,

I'd like to check whether invalid cells exist before allowing the user to save their changes. If invalid cells exist, I will show a message explaining that the errors must be fixed before saving.

I was hoping that the [`validateCells()`](https://github.com/handsontable/handsontable/wiki/Methods) method was going to help me out here. It fires off a callback, but unfortunately does not report on the validity of the cells. (Which seems almost pointless, since it doesn't update the view either!?)

Am I missing something obvious? Or is there currently no easy way to tell if there are invalid cells, short of diving into the DOM and checking for `hgInvalid` class names? (yuck!)

Perhaps the [`afterValidate`](https://github.com/handsontable/handsontable/wiki/Events) hook could be of some use? But I'm struggling to get my head round how I'd use it.

I'm sure this is a fairly common task, so I really feel like I'm missing something obvious.

Any advice would be great! Thanks.

**Comment by Lukazar** [comment]
Using the `afterValidate` event is your best bet.  You simply need to define it in your constructor.  Here is a simple example:  http://jsfiddle.net/mLq3jktv/

Try entering in a non-numeric value in the cell.

**Comment by AMBudnik** [comment]
Very good demo @Lukazar, it explains it all. Thanks for support.

**Comment by ollietreend** [comment]
Agreed. Thanks @Lukazar - I haven't had a chance to put it into action yet, but your suggestion & demo make sense.

**Comment by seanthebean** [comment]
I just ran into this as well. I see that either @Lukazar 's solution or the workaround I found on https://groups.google.com/forum/#!topic/handsontable/7zDV-KAVsd8 (checking for cells with the `htInvalid` class) would work for me, but I'm wondering if it would be possible to at least pass the result of validation into the callback? I think this would be incredibly handy to be able to just do

```js
hot.validateCells(function(valid) {
    if (valid) {
        saveData();
    }
})
```
rather than coming up with a hacky workaround. Can this be re-opened as an `improvement suggestion`?

**Comment by AMBudnik** [comment]
@seanthebean sure it can

**Comment by seanthebean** [comment]
Thanks!

**Comment by seanthebean** [comment]
The described change is implemented in pull request https://github.com/handsontable/handsontable/pull/2790.

**Comment by AMBudnik** [comment]
Closed with implemented https://github.com/handsontable/handsontable/pull/2790

**Comment by kirubz** [comment]
Hi Team,
Thanks for this wonderful plugin.
During validation I am facing some use while validateCells.

Issue Scenario: Last column not specified validator
http://jsfiddle.net/kirubz/bBShs/13/

Working Scenario: Last column have validator
http://jsfiddle.net/kirubz/bBShs/14/

Kindly let us know if anything I am doing wrong

Thanks

**Comment by troywweber7** [comment]
I've looked through the jsfiddle issues. The only issue I see with using `afterValidate` is that until a user edits a cell, the table with empty cells may be considered valid. And then say the user edits a single cell, it is invalid, and then fixes it so it is now valid. Well, `afterValidate` is only called on that one edited cell, so every other cell which is empty is a wildcard as to whether it is valid or not! So there is no way that I can see to block a user from proceeding with an empty sheet...

**Comment by pnowak** [comment]
Hi @troywweber7 

It's hard for me to fully understand your issue without demo.

Can you attach a demo where we can reproduce the issue?
Please describe all the steps to do so.

**Comment by troywweber7** [comment]
Thanks for your interest. I reported it as a new issue but with some digging I found a way to do what I wanted and I posted the Angular solution on that issue, so I'm fine now. Just took some digging to figure out how to access the core object so I could call `validateCells` when I needed to.

**Comment by pnowak** [comment]
Ok. So I glad to hear that you figured out how to achieve access to the core object.
