### ISSUE TITLE
Horizontal scrolling changing  left style property of "wtHider" element

### ISSUE THREAD

**Issue by agucabral21** [handsontable/handsontable#2204]
I have about 30 columns in my grid, when I scroll horizontally and i'm about to get to the last column the horizontal scroll bar changes it size and keeps showing me columns.
The thing is that, when I started scrolling, the size of the scroll bar must be wrong because the last columns it shows when I get to the end, aren't the real last columns, when I get to the end of the scrolling, the grid blinks and the horizontall scroll navbar gets narrow and I can keep scrolling horizontally and then get to the last column.

I've recorded a video about the problem, you can see it here:
http://take.ms/Z6wXS

![captura3](https://cloud.githubusercontent.com/assets/1836226/6398001/ca642f74-bdcf-11e4-8ba9-51ddb452dadd.png)

![captura4](https://cloud.githubusercontent.com/assets/1836226/6398147/a7e6f64c-bdd0-11e4-95ed-7712e59580eb.png)

I've noticed that this element is changing attributes when this happens, in first picture is:
```<div class="wtHider" style="position: relative; left: 0px; top: 0px;">...```
in the second picture is like this:
```<div class="wtHider" style="position: relative; left: 718px; top: 0px;">....```

**Comment by agucabral21** [comment]
I've realize that this only happens from version 0.12.3 , when I try it with 0.12.2 version it works fine

**Comment by AMBudnik** [comment]
Hi, @agucabral21 it will be very helpful to have a demo showing your issue. Image file doesn't always explains the problem. I can be realated to CSS.

**Comment by agucabral21** [comment]
but i recorded a demo, the link is in the first post, over the pictures:

http://take.ms/Z6wXS

**Comment by AMBudnik** [comment]
Yes, but it'll be better to have a demo of your code, for eg. in JSFiddle. If you can provide such demo, I'll be grateful.

**Comment by AMBudnik** [comment]
Hi @agucabral21 I made a [demo](https://jsfiddle.net/0tuy7f87/) similar to one you recorded and it works as expected. Can you update to 0.14.1 and leave us a feedback if this issue still occurs?

**Comment by agucabral21** [comment]
i cant see your demo working

**Comment by agucabral21** [comment]
I think it has something to do with 2 specific rows that don't get stretched the way they should, i used the strechH=all option in order to get dynamic columns width according to the longest value set in that column, but two rows dont get stretchched and so they have a "two row" size, and when i scroll to the right, to get to the end of the row, like in the video i posted, those rows get stretched in the grid rows but not in the fixed columns. I will make another video of it, i is hard for me to make a demo of my code because there are some data and code that im not allowed to share, i have not tried to reproduce this bug in a way that i can show it to you due to lack of time. I will try to do it someday but meanwhile i will post videos of it.

**Comment by agucabral21** [comment]
Here is the video, i dont know why the column with the value "GT-S....." don´t get stretched properly...

http://take.ms/6rH4r

**Comment by AMBudnik** [comment]
OK now I see. It's the same issue like [here](https://github.com/handsontable/handsontable/issues/493) working [demo](https://jsfiddle.net/4c82t0k6/). Can we agree to close this issue if it's duplicated to #493 or you have other experience?

**Comment by agucabral21** [comment]
no problem, close it, i will suscribe to # 493, thanks!
