### ISSUE TITLE
The horizontal scroll does not work with css width

### ISSUE THREAD

**Issue by fbrussa** [handsontable/handsontable#2206]
Hi, this may be a bug.

The horizontal scroll does not work when we specify the width and height by css
Vertical scroll is working properly

http://jsfiddle.net/8b6975mv/

**Comment by fbrussa** [comment]
I found a workaround for this. Initialize the html container with inline style="overflow:auto;"

**Comment by Lukazar** [comment]
Why not just specify the width and height through the constructor?  http://jsfiddle.net/8b6975mv/3/

**Comment by fbrussa** [comment]
Because it is drawn in a variable zone.
So before creating the table I run  $ ("mytable").css("width" ....)

Now adding the overflow style inline works right, thank you

**Comment by AMBudnik** [comment]
I'm glad you found a best way to resolve your issue. If you would have any other questions feel free to open new ticket.
