### ISSUE TITLE
loadData not redrawing table

### ISSUE THREAD

**Issue by okahara** [handsontable/handsontable#2208]
I am validating data and taking the rows that do not pass the validation and using .loadData(badData) to reload the table so they client can fix the data.  For some reason if there are more than 35 rows in the original table and you validate the table then on .loadData(badData) the table does not show automatically.  It provides a scroll bar and when you scroll a little the table appears.  Any suggestions on what I can do to make it automatically appear? 

It works fine for all amount of rows less than 35.

**Comment by okahara** [comment]
oh and the table headers show but not the table cells

**Comment by budnix** [comment]
Releated with https://github.com/handsontable/handsontable/issues/1912. Should be fixed in next version of Handsontable.

**Comment by okahara** [comment]
okay! Thank you budnix
