### ISSUE TITLE
Different Cell Types in the same column

### ISSUE THREAD

**Issue by akoskm** [handsontable/handsontable#2209]
Hello!

Is it possible to have different cell types for different rows in the same column, for instance:

Column 1 | Column 2
------------ | -------------
Server Type | type: autocomplete
Server Name | dataType: string

Thanks!

**Comment by Lukazar** [comment]
I think you're looking for the `cells` or `cell` constructor option.

You can find more information here:  https://github.com/handsontable/handsontable/wiki/Options#cell-options

**Comment by AMBudnik** [comment]
Thank you @Lukazar for correctly answering that question, in the same time we can all agree to close this issue.

**Comment by akoskm** [comment]
Thank you guys for answering this, this is the option I needed!
