### ISSUE TITLE
how to hide columns properly

### ISSUE THREAD

**Issue by renathy** [handsontable/handsontable#2210]
I am not able to hide some columns (with headers). I have a button-switch that should hide/show some columns. I have to do this without changing underlying data as some of the columns have custom renderers and data are computed using other columns. Basicly, col1+col2=col3; col4+col5=col6 etc. I have to show/hide col1,col2,col4,col5 etc.

In my custom renderer I tried to use td.style.display = 'none'/'auto', but this doesn't hide headers.

**Comment by zekedroid** [comment]
For developers, I assume this would need to be a feature since it isn't a bug. One simple way is to update the columns to hide/show but this doesn't keep order if a row was moved or if sorting happened so it would need to be taken care.

Example:
http://jsfiddle.net/LkLkd405/4/

**Comment by AMBudnik** [comment]
Thank you @zekedroid, very smooth solution. This issue is duplicated from #2020 please follow this issue for further information.

**Comment by AMBudnik** [comment]
Feature added in PRO version https://docs.handsontable.com/pro/1.18.1/demo-hiding-columns.html
