### ISSUE TITLE
Column Totals custom renderer and (Cells:) not working together.  Why?

### ISSUE THREAD

**Issue by tmacdonald01** [handsontable/handsontable#2211]
I'm using a custom renderer that I found on this site to give me a Column total.  At the same time I am wanting to have some of my cells be a different color (i.e. weekends and holidays).  I can get each to work separately but not together.  

So I guess the first question I need to ask is, can they work together or am I out of luck?

Here is the custom renderer that I am using for the column totals:
renderer: function(instance, td, row, col, prop, value){if(row === instance.countRows()){td.style.fontWeight = 'bold';value = parseFloat(document.getElementById("cellTotal").value);} else {setTotalValue).ToString + "(row,value);}Handsontable.NumericRenderer.apply(this, arguments);}

Here is the standard (Cells) string:
cells: function (row, col, prop) {row === 0 && col === 1) {this.renderer = BlueRenderer; }

Any assistance would be greatly welcomed.

**Comment by AMBudnik** [comment]
Please prepare a little demo in JSFiddle. It will definitely help us to solve this issue.

**Comment by tmacdonald01** [comment]
As it turns out the custom renderer that I was using wasn't doing what I thought it was.  While it was doing the column totals it was only firing on the last row with a value which didn't do me any good for my validation.  I decided to go with the HandsonTable-RuleJS formula parser instead.  

Just a FYI for anyone out there while the renderer in my initial comment won't work with "cells:".  RulesJS doesn't work with "columns:" but it does work with "cells:".
