### ISSUE TITLE
Merge cells with horizontal scroll

### ISSUE THREAD

**Issue by fbrussa** [handsontable/handsontable#2213]
Hello.
I'm using merged cells with horizontal scrolling.
When I move at the end of the table, this change the total height.

http://jsfiddle.net/c6LcLvyw/

**Comment by Lukazar** [comment]
Yeah, that is an oddity.  It looks like its happening because the the fixed column on the right isn't being accounted for when the render occurs. So as you scroll to the right, the table row values adjust to the visible area and since all the table cells are hidden, it acts as if there is no row.

This can be demonstrated by enabling the `rowHeaders`:  http://jsfiddle.net/6txws0ur/ which then preserve the row and hence the merge.

**Comment by fbrussa** [comment]
That's right. But I need to hide the rowHeader.
I'm writing a plugin for pivottable (http://nicolas.kruchten.com/pivottable/examples/) using handsontable to render the table.

**Comment by krzysztofspilka** [comment]
@fbrussa wow, that's impressive! Probably one of the most interesting implementations of Handsontable so far. We'll be happy to help you.

@Lukazar thanks for help in investigating this bug and your overall activity here on GitHub:)

**Comment by jansiegel** [comment]
@fbrussa It seems to be the problem with the `rowspan` attribute in general. In your very specific example (when all cells in a row have a `rowspan` property assigned) the html `table` element doesn't recognise the height of the rows properly.
Take a look at this pure html example:
When all cells in a row have the `rowspan` property (and the 'overlapped' cells are set to `display: none`, as they need to remain hidden), it ignores the second row completely:
http://jsfiddle.net/js_ziggle/4msyqzde/
But if we don't assign the `rowspan` to a single cell in the row (and remove the `display: none` property for the overlapped cell), it works as expected:
http://jsfiddle.net/js_ziggle/4msyqzde/1/

In your example you might want to try to assign (via CSS or JS) the heights of `tr` elements for both rows (the ones with `rowspan` assigned, and those with overlapped cells), it should work better.

**Comment by fbrussa** [comment]
Thanks you @jansiegel, good idea.

@krzysztofspilka: The plugin is under development and there is still work but looks great.
I will upload the code when it is stable. Thank you

**Comment by cbetech** [comment]
@fbrussa hey, can you show us the progress of your component?

**Comment by fbrussa** [comment]
Hello @cbetech, @krzysztofspilka  , my progress is rather poor.
In these days I hope to play with the plugin again.
You can see a preview here: http://liderafx.com/temp/pivotedit/

I need to improve the performace. Especially when you scroll.
Any comments will be welcome.

**Comment by fbrussa** [comment]
Hi @krzysztofspilka, here I leave the plugin repository that had told you.

https://github.com/fbrussa/NovixPivotJS

Cheers

**Comment by AMBudnik** [comment]
@fbrussa great job! Keep my fingers crossed for any updates.
