### ISSUE TITLE
Set a max-width and max-height for cells

### ISSUE THREAD

**Issue by donpinkus** [handsontable/handsontable#2216]
Is it possible to set a `max-width` and `max-height` for cells in Handsontable?

I've tried to set this via CSS on the `<th>` and `<td>` elements but this doesn't work. 

I saw in the docs that you can set the columns to particular widths, but not maximums.

**Comment by krzysztofspilka** [comment]
Answered in #2236

**Comment by AMBudnik** [comment]
Hey,

we've added an option in Handsontable 7.0.0 that can interest you https://github.com/handsontable/handsontable/issues/5749 
From now on we support a container with relative dimensions (%, vh, vw, rem, em)
