### ISSUE TITLE
row height doesnt match when using column freeze

### ISSUE THREAD

**Issue by davidjuntak** [handsontable/handsontable#2218]
![capture](https://cloud.githubusercontent.com/assets/8628874/6479496/c63506be-c278-11e4-9ba0-bc7d17918169.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8628874/6479499/cbc43d98-c278-11e4-8708-077c365e48a9.PNG)
when I used column freeze option I had this problem. Row height is okay when then cell only contain single line words like "Amy should look around for any last items, notice the surfboard and then move to it." but when the words become like this (have multiple line) the column freeze's row have different height :
"Amy should look around for any last items, notice the 
surfboard and then move to it."

**Comment by clauiordache** [comment]
I have this issue too! ...it looks like it makes a merge over the column near it, if you have a value in the cell on more than 1 line. This seems to happen starting with 0.12.5 version as I have observed.

**Comment by zekedroid** [comment]
I used to have this problem. There was some code overlapping with Bootstrap. Do this to check that it works: zoom the page in or out, the browser zoom. That fixes it for some reason.

**Comment by clauiordache** [comment]
@zekedroid : It didn't work..for me at least. What do you mean some code overlapping with Bootstrap?

**Comment by zekedroid** [comment]
I mean that, at least for me, Bootstrap seemed to be adding margins to checkboxes, 1px to be precise. So this was shifting every row in my HOT instance down by 1px. Now it's important to note that HOT uses two clones of the table to achieve the freezing and for some reason, this margin was only applied to one of the two, making the frozen clone get offset.

But this may not be the same bug.

**Comment by Lukazar** [comment]
Does the problem persist if you enable row headers?

**Comment by zekedroid** [comment]
Yes

**Comment by AMBudnik** [comment]
Hi @davidjuntak do you still face this issue?

**Comment by davidjuntak** [comment]
yeah I still face this issue

**Comment by AMBudnik** [comment]
In [this](https://jsfiddle.net/ob13cyxw/) example it's all about 1px which we know and definetely it'll be fixed but I see in @davidjuntak it's more than 1px. Can you please prepare a demo which shows this issue?

**Comment by ryanj-openquire** [comment]
I'm also seeing this issue and it looks like the height of the first column (which is the frozen one) is a bit off.
![screen shot 2015-05-27 at 10 55 52 am](https://cloud.githubusercontent.com/assets/12617476/7839334/dfb33966-045f-11e5-8de8-6b83bc774ccd.png)

**Comment by AMBudnik** [comment]
Please update to 0.16.1, issue no longer exsist.

**Comment by codenyc** [comment]
After upgrading to 0.16.1 and loading my application I get this error,

Uncaught Error: Module name "pikaday" has not been loaded yet for context: _. Use require([])

and then 
Uncaught Error: Load timeout for modules: mediaocean-handsontable

**Comment by AMBudnik** [comment]
@codenyc please prepare a sample code (it you can update to 0.17.0 also)

**Comment by AMBudnik** [comment]
Issue closed in lack of demo/recent activity.

**Comment by mitalikhundiwala** [comment]
I am facing similar issue, but I have found a more narrowed reason. In my case it only happens when I am using a custom renderer along with Fixed Columns and that too when we have nested objects for row data. Following is the fiddle demonstrating the scenario and the screenshot for reference.

JSFiddle : https://jsfiddle.net/mitali_JSfiddle/17kfdc6w/

![handsontable](https://cloud.githubusercontent.com/assets/1251508/13006061/473c0684-d1ac-11e5-9a1f-560b0d6378da.png)

**Comment by AMBudnik** [comment]
Hi @mitalikhundiwala can you simplify this example a little bit? It's hard to get though this amount of code.

**Comment by mitalikhundiwala** [comment]
Hi @AMBudnik, I've updated the fiddle and have removed extra comments and code from it. But since this issue occurs with large amount of text in a cell along with a custom renderer to render HTML text, I have not simplified data.

**Comment by AMBudnik** [comment]
hi @mitalikhundiwala in which browser you're experiencing this issue?

**Comment by hemantmalpot** [comment]
@AMBudnik : When the row height is little bigger, not able to see options on same window for drop down. 
Please check the below link :
https://jsfiddle.net/hemantmalpote/b73vvnnf/1/ 
Go to row one and click on 'D' cell's drop down.
Unable to see options in that page, as it appears on bottom of cell.

**Comment by AMBudnik** [comment]
@hemantmalpot Thank you for additional information but the important question is how you would like it to behave in this example.
I know that it might be inelegant and not so user-friendly but how to change it to be better.

**Comment by hemantmalpot** [comment]
![dropdownstyle](https://cloud.githubusercontent.com/assets/17879072/13815020/e51322f4-ebae-11e5-9c3b-6989ab3f2003.png)
Please check the above screen shot.

**Comment by AMBudnik** [comment]
Thanks for sharing @hemantmalpot I'm marking this issue as a improvement suggestiona to be discussed with team.

**Comment by AMBudnik** [comment]
Topic moved to [Improvement-suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

**Comment by AMBudnik** [comment]
The issue doesn't seem to be replicable in v8.4.0. Here is an updated demo https://jsfiddle.net/handsoncode/uvejdm3a/

Please contact me if you received a different result after updating to the newer version.
