### ISSUE TITLE
Bug #1881 never made it to released version of Handsontable. 

### ISSUE THREAD

**Issue by mcevikce** [handsontable/handsontable#2221]
Later last year we had an issue with handsontable where the issue was addressed wuth #1881. https://github.com/handsontable/handsontable/issues/1881
But this fix never made it to next release 0.12.0. As a matter of fact the method in question was totally removed from the released code but then later 0.12.1 release it was added back without the fix. So this is still a problem. Hovering over with a mouse over the page that doesn't have handsontable causes hundreds of JS errors.

**Comment by krzysztofspilka** [comment]
Hi @mcevikce , thanks for reporting this. We're aware of the fact that comments are buggy at the moment and should be refactored in the future. This work is not scheduled yet though.

As a company we offer commercial consulting services so I you'd like to sponsor the above please let us know at hello@handsontable.com

I'm closing this issue as it's already described in #1881
