### ISSUE TITLE
Cannot have two Handsontable instances on same page

### ISSUE THREAD

**Issue by Guillaume84** [handsontable/handsontable#2224]
I am not sure if this is a bug. I have read your documentation and also had a look at previous issues on Github and SO.

I need to have two instances of handsontable on a same page. I create two divs ('#example' and '#example2'). I then declare stuff as follows (initially the two tables have the same data source, but then can get manipulated independently -I nonetheless tried to segregate the data variables initially to make sure they don't have the same data source):

var experiment2 = experiment;

var example1 = document.getElementById('example'),
    hot1;
  
  hot1 = new Handsontable(example1, {
    data: experiment,
    colHeaders: ColHeaders,
    columns: ColType,
  afterChange: function() {
     }
  });

var example2 = document.getElementById('example2'),
    hot2;
  
  hot2 = new Handsontable(example2, {
    data: experiment2,
    colHeaders: ColHeaders,
    columns: ColType,
  afterChange: function() {
     }
  });

Now, if I make some edits to the tables and I try to retrieve their data in the console log as follows, I get the same data for both tables!

console.log(hot1.getData());
console.log(hot2.getData());

Is this a bug, or am I being really thick? Please let me know your thoughts and have a good day.

**Comment by budnix** [comment]
I thing that this is not a bug. This is happen because you probably pass into `data` property the same array. Event if you assign data into two other variables you still have one copy of this data into memory.

You can make deep copy of your data by eg: JSON stringify and parse:
```js
hot2 = new Handsontable(example2, {
    data: JSON.parse(JSON.stringify(experiment2)),
    colHeaders: ColHeaders,
    columns: ColType,
    afterChange: function() {}
});
```
Related article http://handsontable.com/demo/understanding_reference.html

**Comment by Guillaume84** [comment]
budnix, thank you Sir, you have taught me an interesting lesson. I didn't realise both experiment and experiment2 would be assigned the same memory.

What is a deep copy exactly?

**Comment by budnix** [comment]
Saying deep copy I mean that data must be copy recursively. The best explanation for that you can find at http://james.padolsey.com/javascript/deep-copying-of-objects-and-arrays/.

**Comment by Guillaume84** [comment]
Thank you Budnix -very helpful. Have a good day, and chat soon.
