### ISSUE TITLE
Datepicker disappears immidately after appearing on IE 11

### ISSUE THREAD

**Issue by alperenbelgic** [handsontable/handsontable#2226]
Hello,
When I click to the up arrow ( or double click ) in a date cell, date picker is shown for a while ( less than 500 ms ), and then disappears. I reproduce this issue on the page I am developing and on the sample usage here: http://handsontable.com/demo/date.html 
I added the moment.js and pikaday dependencies.
My local computer's OS is Windows 8.1. I cannot reproduce the issue on Google Chrome. 
I searched similar issues, but there was no issue specific to IE 11.
Thanks!

**Comment by krzysztofspilka** [comment]
Connected with #2181

**Comment by krzysztofspilka** [comment]
@alperenbelgic This should be fixed in version 0.13.0 which has been just released.

https://github.com/handsontable/handsontable/releases/tag/0.13.0

Please test it and let us know.

**Comment by alperenbelgic** [comment]
Hello @krzysztofspilka ,
I tested it. It works as I expect on my project and the demo page.
Thanks for fix.

**Comment by krzysztofspilka** [comment]
I'm glad we could help:)
