### ISSUE TITLE
When there are 30 columns and 100 rows of data in Handsontable, when switching cells in the IE browser is particularly slow

### ISSUE THREAD

**Issue by suyu00001** [handsontable/handsontable#2227]
When there are 30 columns and 100 rows of data in Handsontable, when switching cells in the IE browser is particularly slow

**Comment by krzysztofspilka** [comment]
Hi @suyu00001 which version of IE do you use? Could provide us JSFiddle demo on this?

**Comment by suyu00001** [comment]
When I used to run ie column_freeze Demo editing Cell after switching to other Cell slowly

**Comment by suyu00001** [comment]
@krzysztofspilka When I used to run ie column_freeze Demo editing Cell after switching to other Cell slowly

**Comment by suyu00001** [comment]
@krzysztofspilka 
![Uploading 6E78FA37-D_clip.gif . . .]()

**Comment by suyu00001** [comment]
@krzysztofspilka 

![Uploading 6E78FA37-D_clip.gif . . .]()

**Comment by suyu00001** [comment]
![6e78fa37-d_clip1](https://cloud.githubusercontent.com/assets/11344995/6682771/087b8f5e-ccb8-11e4-91cb-c871dde35227.gif)
@krzysztofspilka  In? Urgent!!! This is the picture, thank you

**Comment by suyu00001** [comment]
Pictured: 2 edit box in the editor when switching, in the IE browser, longer than about 15S, how to solve? I see the discovery of applyChanges method in the handsontable.full.js effect during handover. But do not know how to solve?

**Comment by AMBudnik** [comment]
@suyu00001 do you still face this issue? If so, please prepare a [JSFiddle](afterChange) demo for your example.

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity and needed demo.
