### ISSUE TITLE
How to get cellData from handsonatable on each keyPress at a particular cell?

### ISSUE THREAD

**Issue by krishsharma** [handsontable/handsontable#2232]
Hi All,
I am new to handsontable. Please help me to get out of the problem below:

How to get cellData in handsonatble on each keyPress event at a particular cell?

Thanks in advance.

**Comment by krzysztofspilka** [comment]
@krishsharma did you check our callbacks demo? http://handsontable.com/demo/callbacks.html together with list of available methods (e.g. getValue etc.): https://github.com/handsontable/handsontable/wiki/Methods

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity and unsolved questions.
