### ISSUE TITLE
setting fixedRowsTop = "3" causes obscure error: "Security brake: Too much TRs. Please define height for your table, which will enforce scrollbars."

### ISSUE THREAD

**Issue by abliss** [handsontable/handsontable#2233]
To reproduce:
1. Create a handsontable with more than 1000 rows.
2. call updateSettings with fixedRowsTop set to a string (not a number).

(Fiddle: http://jsfiddle.net/s3q1w2pj/2/   -- Push the button on the bottom.)

Expected: Either (a) use the numerical value of the string, or (b) throw an error about the value being the wrong type.

Actual: A very obscure error.

I was trying to populate fixedRowsTop from an HTML select.value, and I forgot that it was passing a string instead of a number. Okay, shame on me, but it shouldn't take half an hour to debug this!

**Comment by krzysztofspilka** [comment]
Hi @abliss thanks for reporting this, indeed the error being thrown should be changed in this case. Sorry for your half an hour:)

**Comment by zzunaid** [comment]
Hi I'm getting the same error.

**Comment by dizaina** [comment]
I am also getting the same error

**Comment by BrettMohr** [comment]
I'm also getting this error with Handsontable Pro. Any update on this?

**Comment by AMBudnik** [comment]
Hi @BrettMohr I made simpler example http://jsfiddle.net/ftz5vje7/1/ and I didn't get the errors and it works with string. Could you please take a look at this one and correct me what I'm missing?

**Comment by jtandrew** [comment]
I am seeing the same issue with a dropdown.  I have a dropdown/autocomplete that has thousands of items.  The pattern to make the behavior occur is a little odd.  Here are the steps to reproduce.

1. 
2. Go to an existing item/row above and select that same dropdown to attempt to modify that value
3. 

1. Add an item to the column using the dropdown

**Comment by AMBudnik** [comment]
hi @jtandrew can it be replicable with this demo? http://jsfiddle.net/5xuyqxtm/

**Comment by jtandrew** [comment]
Hi @AMBudnik I am able to reproduce if I make the options in the dropdown beyond 1000.  See my update.

http://jsfiddle.net/5xuyqxtm/1/

Change the chassis color on 2 items, then click out of the current cell.

**Comment by AMBudnik** [comment]
@jtandrew your example is the one to confirm this issue https://github.com/handsontable/handsontable/issues/3222 and I'm looking confirm or not the relation of `fixedRowsTop` and this console error. Can you check this one too?

**Comment by jtandrew** [comment]
@AMBudnik I just checked that one out and I see that is the same issue.  I will make a note of it one there.  Thanks

**Comment by AMBudnik** [comment]
I'm closing this issue as it does not occur in it's original description.
