### ISSUE TITLE
Set a max-height and max-width for cells.

### ISSUE THREAD

**Issue by donpinkus** [handsontable/handsontable#2236]
Is it possible to set a max-height and max-width for cells?

http://stackoverflow.com/questions/28846055/set-a-max-width-and-max-height-for-table-cells

**Comment by krzysztofspilka** [comment]
Hi @donpinkus , unfortunately at the moment it's not possible to set these properties straight from CSS.

**Comment by krzysztofspilka** [comment]
Connected with #2216

**Comment by donpinkus** [comment]
huzzah! (regarding this be reopened)

**Comment by anton-107** [comment]
+1 for this feature. I want to set a max column width for the column to prevent too wide columns when using dynamic column sizing

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by fengjac** [comment]
Any update? Thanks

**Comment by AMBudnik** [comment]
Sorry @fengjac this feature hasn't been scheduled for 2018. However, you can do the same via custom renderer a little bit of CSS. Here's an example https://codepen.io/anon/pen/aqvzoO

**Comment by AMBudnik** [comment]
You're right @micycle It looks like I've pasted the wrong demo. Here is a demo http://jsfiddle.net/handsoncode/421z3ru5/

**Comment by joparisot** [comment]
+1 for this feature. 
I would love to have the size automatically fit the content of a cell unless this content is really too long (in which case it impacts significantly user experience)

**Comment by AMBudnik** [comment]
Hey,

we've added an option in Handsontable 7.0.0 that can interest you https://github.com/handsontable/handsontable/issues/5749 
From now on we support a container with relative dimensions (%, vh, vw, rem, em)

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
