### ISSUE TITLE
Why drawing is disabled for hidden tables?

### ISSUE THREAD

**Issue by bpohoriletz** [handsontable/handsontable#2239]
Hello,

I have a question about the following method

``` javascript
17855 Walkontable.prototype.draw = function (fastDraw) {
17856   this.drawInterrupted = false;
17857   if (!fastDraw && !Handsontable.Dom.isVisible(this.wtTable.TABLE)) {
17858     this.drawInterrupted = true; //draw interrupted because TABLE is not visible
17859     return;
17860   }
17861 
17862   this.wtTable.draw(fastDraw);
17863 
17864   return this;
17865 };
```

is there a particular reason why drawing is disabled for hidden tables? I'm asking because I'm using accordion and sometimes grid is hidden and it seems to me that hidden tables are rendered fine.

Thank you!

**Comment by budnix** [comment]
Hi @bpohoriletz, I'm sorry for a late response. I believe that Handsontable is not drawing when table is hidden in one reason - performance. 

I think that your scenario shows (while following the new issue idea) that we can add a new option which can overwrite this default behaviour.

**Comment by swistach** [comment]
Example based on bootstrap: http://jsfiddle.net/bh7dfp8h/
Shows, how you can do it now.

**Comment by bpohoriletz** [comment]
Thank you @budnix @swistach!
