### ISSUE TITLE
stretchH to first column

### ISSUE THREAD

**Issue by Teo0uz** [handsontable/handsontable#2240]
Hello,
I was wondering if there is a way to apply "stretchH" to the first column or if there is a simple/clean way to achieve similar effect. It would be really useful as well if the width of the column adjusts when the parent div size changes.
Thank you in advance - any help will be highly appreciated.

**Comment by AMBudnik** [comment]
Hi, we're working on to make it more flexible but at this moment you can only choose to stretch: last, all or none columns(which is default). Only similar option that you can use is to try to cooperate with 'colWidths'.
About 'stretchH' I guess we will provide more complex solution in the near future.
