### ISSUE TITLE
Support for customized data source(sync/async) like https://github.com/fulmicoton/fattable

### ISSUE THREAD

**Issue by lygstate** [handsontable/handsontable#2243]
At the current time, the data is always a fixed data array, so I'd like to know if there is a way to 
provide data source that generated in customized way like IndexDB, WebSQL.

**Comment by AMBudnik** [comment]
Currently there are many ways to load and update data: https://docs.handsontable.com/0.24.1/tutorial-data-sources.html
I do not know is it desired solution @lygstate or maybe there was something else in your mind?
