### ISSUE TITLE
the manualRowMove can't set to an array

### ISSUE THREAD

**Issue by ericyang89** [handsontable/handsontable#2245]
the option can only set to true/false , 
if set it to an array like [1,3,5] , it is the same as set it to true！

hopely  it is my problem, 
can someone give me a demo

**Comment by AMBudnik** [comment]
Yes, you are right it can only has boolean values, because it is a permission to manually move a row up or down, and every value different than false, null, undefined  or an empty string will be translated as a value:true.

**Comment by ericyang89** [comment]
is there a  workaround for me to solve the problem
i want to let some rows can be moved(manualrowmove) some can not in my handsontable

**Comment by AMBudnik** [comment]
Unfortunately there's no option like this right now but as far as I'm concerned your request can be assign as a milestone candidate.

**Comment by ericyang89** [comment]
thanks for your work and your answer
I solved  this problem in a silly way
I added somecode in the event "afterRowMove"
1、change the dataSource
    dataSource.splice(newIndex, 0, dataSource.splice(oldIndex, 1)[0]);
2、destroy the     hot.destroy();
3、built a new hot use the dataSource;

this way do change the DOM!  I used the destroy/built method since the loadData(array) seems do not work there

**Comment by ericyang89** [comment]
the code just like that，focus on the "afterRowMove" Event~!

      var builtHot = function (example1) {
            hot = new Handsontable(example1, {
                data: dataSource,// JSON.parse(JSON.stringify(dataSource)), //Handsontable.helper.createSpreadsheetData(1000, 10)
                //afterChange: function () {
                //    var tmpData = dataSource;
                //    // now tmpData has a copy of data3 that can be manipulated
                //    // without breaking the Handsontable data source object
                //},
                rowHeaders: true,
                colHeaders: ["资源", "订单-工序", "3月01", "3月2", "3月3", "3月4", "3月5", "3月6", "3月7", "3月8"],
                colWidths: [55, 180, 80, 80, 80, 80, 80],
                fillHandle: "horizontal",
                manualRowMove: true,

                columns: [
                //{ data: 'ID' },
                { data: 'Resource', readOnly: true },
                { data: 'DocOp', readOnly: true },
                { data: 'Date.Day1' },
                { data: 'Date.Day2' },
                { data: 'Date.Day3' },
                { data: 'Date.Day4' },
                { data: 'Date.Day5' },
                { data: 'Date.Day6' },
                { data: 'Date.Day7' },
                { data: 'Date.Day8' }
                ],
                //minSpareRows: 1,
                //contextMenu: true,
                comments: true,

                // contextMenu: ['remove_row', 'undo', 'redo'],


                //单元格合并
                //mergeCells: [
                //            { row: 0, col: 0, rowspan: 4, colspan: 1 },
                //            { row: 4, col: 0, rowspan: 6, colspan: 1 }
                //],
                ////单元格对齐
                //cell: [

                //          { row: 0, col: 0, className: "htCenter htMiddle" },
                //          { row: 4, col: 0, className: "htCenter htMiddle" },
                //          { row: 3, col: 4, comment: 'test comment' }
                //],
                //persistentState: true,

                afterRowMove: function (oldIndex, newIndex) {
                    console.log(dataSource);
                    if (newIndex > 0 && dataSource[oldIndex]["DocOp"] !== "") {
                        dataSource.splice(newIndex, 0, dataSource.splice(oldIndex, 1)[0]);
                        dataSource[newIndex]["Resource"] = dataSource[newIndex - 1]["Resource"];
                        hot.destroy();
                        builtHot(example1);
                       
                    }
                    else {
                        hot.destroy();
                        builtHot(example1);
                    }

                    Droppable();

                },

                beforeChange: function (changes, source) {

                    //资源第一行，不允许填充
                    if (changes.length > 0) {

                        if (hot.getDataAtCell(changes[0][0], 1) === "" && source == "autofill") {
                            //alert("you can NOT do this!");
                            return false;
                        }
               
                        //自动求和
                        //1.对前两列不做处理
                        var changesCount = changes.length;
                        for (var i = 0; i < changesCount; i++) {
                            if (changes[i][1] == "Recource") continue;
                            else if (changes[i][1] == "DocOp" && source == "autofill") changes[i][3] = changes[i][2];
                            else {
                                
                                changes=CalcUsage(changes, i, dataSource);
                                if (i == changesCount)
                                    console.log(changes);
                            }
                        }
                    }

                    //hot.setDataAtCell(0, 2, hot.getDataAtCell(1, 2) + hot.getDataAtCell(2, 2) + hot.getDataAtCell(3, 2));


                }
                //, afterChange: function (changes, source) {
                //    if (source!="loadData") {
                //        hot.setDataAtCell(0, 2, hot.getDataAtCell(1, 2) + hot.getDataAtCell(2, 2) + hot.getDataAtCell(3, 2));
                //    }                     
                //}



            });

        };

**Comment by AMBudnik** [comment]
I'm glad you found a solution for your issue, it looks promising.
