### ISSUE TITLE
Using Handsontable with Redactor JS on the same page - CMD+V to redactor doesn't work

### ISSUE THREAD

**Issue by stas-s** [handsontable/handsontable#2246]
http://jsfiddle.net/s0s02dbd/

I understand that this issue is kind of problematic because it involves another plugin, but may be there is some easy fix for it
I would really appreciate if you can look into it

**Comment by AMBudnik** [comment]
For issues related to other libraries/plugins, please create a topic in our [stackoverflow](https://stackoverflow.com/questions/tagged/handsontable)
