### ISSUE TITLE
undo do not work after move the row(drag)

### ISSUE THREAD

**Issue by ericyang89** [handsontable/handsontable#2250]
undo do not work after move the row(drag), 
 
maybe  it is only for cell changes

**Comment by AMBudnik** [comment]
Actually manually moved rows or columns are immune to 'undo' option. Thanks for sharing this issue @ericyang89

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/2109

**Comment by AMBudnik** [comment]
Issue closed, as it is the same as https://github.com/handsontable/handsontable/issues/2109
