### ISSUE TITLE
Prevent generation of scrollbars on autocomplete cells

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2252]
I've noticed that now, in the latest version to date 0.13.0, besides having a worse visual style, it is not possible to scroll through the auto complete options by using arrows, like before (0.8.23)

Is there a way to enable it? And... I guess there's nothing that can be done with the new design? (which shows two scroll bars... instead of overflowing it)

![before-after](https://cloud.githubusercontent.com/assets/1706326/6618667/5ddd2980-c8bc-11e4-9e06-8986e0a7c4bf.jpg)

**Comment by AMBudnik** [comment]
Navigating through dropdown menu should work fine with up/down arrow, like in demo provided in [autocomplete demo](http://handsontable.com/demo/autocomplete.html). Can you prepare us a demo of your example?

**Comment by alvarotrigo** [comment]
My mistake, I was using this CSS in the previous version to remove the handsontable background from the latest column, and it was overriding the values in the new version of handsontable.js.

```css
#editOrders td:last-child,
#editOrders th:last-child{
	background: none;
	border:0;
}
```

I'll try to find another way.
In any case, is there anything to do with the visual design of the list? So it won't show the horizontal scroll bar at least?

**Comment by AMBudnik** [comment]
Please provide a demo it shouldn't act like this.

**Comment by alvarotrigo** [comment]
Here: http://jsfiddle.net/fws1vc5e/

**Comment by AMBudnik** [comment]
Thank you, let us look a little closer.

**Comment by alvarotrigo** [comment]
Another version here without the hidden SPAN element:
http://jsfiddle.net/fws1vc5e/1/

**Comment by AMBudnik** [comment]
OK, thank you.

**Comment by AMBudnik** [comment]
Still [occurs](https://jsfiddle.net/szh5mtaj/)

**Comment by AMBudnik** [comment]
Please update you code and send us feedback if you would still face this issue. 

Tested on:
* Firefox 37
* Chrome 42
* Safari 8

**Comment by alvarotrigo** [comment]
The horizontal scroll bar disappeared.

**Comment by AMBudnik** [comment]
Previously tested on OSX, on Win7 with IE11 it works also fine.
