### ISSUE TITLE
Version of Numeral.js

### ISSUE THREAD

**Issue by blueshed** [handsontable/handsontable#2253]
The version of numeral.js [1.5.3] does not match the version on https://github.com/adamwdraper/Numeral-js/commits/master/numeral.js

In particuar - your version has a validate function on line 482 and in the numeral.js project there is no validate function! Line 482 is a comment.

I have looked at the history of both source files and cannot tell when they lost or gained the validate function. Without it the 'numeric' field type cause an exception and the fields cannot be edited.

I'm using AMD to load both libraries.

**Comment by budnix** [comment]
Hi, 

We use numeral.js from develop branch (https://github.com/adamwdraper/Numeral-js/blob/develop/numeral.js). There is a problem with maintainer of this project who from almost a year hadn't merged develop (with `validate` function) into master.
