### ISSUE TITLE
Autocomplete doesn't show options when an invalid text is added

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2254]
You can reproduce it here: http://jsfiddle.net/fws1vc5e/3/

Before the click:
![state1](https://cloud.githubusercontent.com/assets/1706326/6622011/cd5e84e2-c8d1-11e4-965f-1a57c2a6927d.PNG)

After the click on the arrow it disappears and no options are shown.
![sat](https://cloud.githubusercontent.com/assets/1706326/6622021/dccaeed4-c8d1-11e4-9b42-86cf131919c2.PNG)

Wouldn't it be better to show all options when the inserted text doesn't match any possible autocomplete option? 
Like suggesting a change from the user although allowing the invalids?

**Comment by AMBudnik** [comment]
Thanks @alvarotrigo it's a good way to make HoT more interactive. Thank you for that suggestion.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
