### ISSUE TITLE
moment.js required with full version?

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2255]
I'm getting the console error: 

> Uncaught Error: You need to include moment.js to your project.

I though all dependencies were included in the full version of the plugin:

> handsontable.full.js and handsontable.full.css are compiled with all the needed dependencies.

**Comment by jansiegel** [comment]
If your Handsontable instance uses date-type cells, you need to additionally include `moment.js`, `pikaday.js` and `pikaday.css` files, as described in the date cells demo page: http://handsontable.com/demo/date.html

You're right, though - the description you provided might be a little misleading.

**Comment by krzysztofspilka** [comment]
@grz
