### ISSUE TITLE
Issue with multiple rows being generated with dynamic setDataAtCell()

### ISSUE THREAD

**Issue by SamHausmann** [handsontable/handsontable#2256]
I'm pretty new to both js and handsontable so please bear with me. If there is any more information I can include let me know. 

I would like to dynamically set data in a cell depending on the length of my grid. I have stepped through my program and found it to work as expected until the function provided below.

The function loadPartString() is supposed to display fullString in the bottom most grid by taking the total number of rows using countRows as the index, in column two. There is always a blank row generated below whatever row I am using which is why I subtract 1 from the total number of rows as to not skip any. 

	function loadPartString(fullString){

		var currentRow = hot.countRows() - 1;
		
		hot.setDataAtCell(currentRow,2,fullString);

	}

The function that sends fullString to loadPartString() uses getData and stores it in a temporary variable which is concatenated to a new string which needs to be added on to the previous value. For example if the bottom most cell in column 2 shows "123" and the new value is "4", the function will create "1234" and pass that as the fullString to be displayed in the same cell. What happens is entirely different and below is an image of the actual result. 

![examplehot](https://cloud.githubusercontent.com/assets/7482379/6624436/86e81134-c8bf-11e4-80b3-d60218a60ff4.PNG)

It is my understanding that countRows() will give me the "height" of my grid and setDataAtCell() will display data specified in the cell coordinates specified. I do not understand why my actual result varies from my actual. I have already stepped through my program up to this point and everything works fine. In my actual code I print pretty much every value to the console but I removed those statements to make the code as easy to read as possible.

Thanks for any help you can provide.

**Comment by AMBudnik** [comment]
Hi please update to 0.14.1 and if this issue will still occur - send us your [JSFiddle](https://jsfiddle.net/api/post/library/pure/)
