### ISSUE TITLE
copy paste issue in firefox for % value

### ISSUE THREAD

**Issue by sonamsdiwate** [handsontable/handsontable#2257]
For version 0.12 and 0.13 I am facing once issue which is specific to Firefox browser
When we copy percentage data from excel and paste firefox stop working and need to close browser

**Comment by AMBudnik** [comment]
I couldn't reproduce it, can you prepare a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/)?

**Comment by sonamsdiwate** [comment]
This is specific to Firefox and only for percentage values only

**Comment by AMBudnik** [comment]
Do you still face this issue after updating to 0.14.1?

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply.
