### ISSUE TITLE
Error 'Cannot read property 'isOpened' of undefined ' after set attributes to td and use keyups

### ISSUE THREAD

**Issue by ariocx** [handsontable/handsontable#2258]
Hi, i have some problem. 
After use :
```javascript
cells: function (row, col, prop) {
      return { type: { renderer: setTdAtrr } };
```
```javascript
function setTdAtrr(instance, td, row, col, prop, value, cellProperties) {
  Handsontable.TextCell.renderer.apply(this, arguments); 
  td.setAttribute('data', value);
}
```
Date attribute is assigned for td, but keys Up, Down, Left, Right stop working with error:
> handsontable.full.js?body=1:5412 Uncaught TypeError: Cannot read property 'isOpened' of undefined

and action click return error: 
> handsontable.full.js?body=1:5990 Uncaught Error: Cell type must be a string 

in what there can be a problem?

**Comment by AMBudnik** [comment]
Can you please provide a demo?

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity and provided demo.
