### ISSUE TITLE
What does the param `prop` in `cells` option contains?

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2259]
It doesn't seem to be specified very well in the docs:

> **cells:** Function(row, col, prop) (default undefined)
> Defines the cell properties for given row, col, prop coordinates 
> See Cells section below for more detailed explanation

And I so [no example of any usage of it in them](http://handsontable.com/demo/renderers.html).

**Comment by AMBudnik** [comment]
Thanks for adding the description @swistach
