### ISSUE TITLE
Does autofill with double clicking only support array??

### ISSUE THREAD

**Issue by hongz1** [handsontable/handsontable#2260]
I tested through all examples on http://handsontable.com/demo/datasources.html and only the first one worked. I am currently using object data source and looks like the issue is occurred from "countRows()" function.

Is there a way to enable this feature with object data?

Thanks.

**Comment by AMBudnik** [comment]
I do not know if [this](https://jsfiddle.net/e8y6j6ko/) is what you were looking for, cause it worls fine with an `object` data as good as with an `array`

**Comment by hongz1** [comment]
Dragging and dropping from top the top cell to bottom works well; however, auto filling feature by double clicking at the right bottom corner does not work for all other examples except array data source.
In http://docs.handsontable.com/0.15.0-beta2/tutorial-data-sources.html - "Array Data Source" example, if you remove from B3 to B6 cell values and double click at the right bottom corner of B2, B2 cell value will fill to column cells automatically. But, other examples such as "Array data source with hidden columns" and "Object data source", auto filling function does not work.

**Comment by AMBudnik** [comment]
Confimed with 0.17.0 it does not autofill with `Array data source with hidden columns` and with `object` source data like [here](https://jsfiddle.net/5Lu04b2u/)

**Comment by AMBudnik** [comment]
Still present in 0.24.1

**Comment by AMBudnik** [comment]
Currently you are able to auto fill values while dragging not by a dbl click for arrays and objects.
