### ISSUE TITLE
Input not allowed after pasting data in a row with a cell containing `date` type

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2261]
Reproduction of the error:
http://jsfiddle.net/fws1vc5e/5/
- Create a hansontable with two columns. First with type `autocomplete` and the other with `date`.
- Open Excel
- Create a row with two columsn ( London, 23/03)
- Copy those two columns by selecting both cells
- Paste them in hansontable by selecting the first cell at the top left.
- Try changing the value of the 1st cell in the first column and there you go. Any input text will be deleted and there's no way to type/select anything.

I noticed this behavior still taking place even when the 1st column is a `text` type, but in that case you can type until you click out, when the text suddenly disappears.

**Comment by AMBudnik** [comment]
Related with https://github.com/handsontable/handsontable/issues/2200

**Comment by alvarotrigo** [comment]
Do you have any estimate date for the next release?

**Comment by AMBudnik** [comment]
It's not specified, but I guess somewhere between 20th and the end of the month.

**Comment by alvarotrigo** [comment]
This was solved in 0.13.1 as you can see in [this reproduction](http://jsfiddle.net/fws1vc5e/16/).
