### ISSUE TITLE
How to use validateCells?

### ISSUE THREAD

**Issue by littleneotrix** [handsontable/handsontable#2262]
Hi,
I'm having a problem to understand how to use this function, couldn't find anything about it in plugin's Wiki, and not on Google results.

What I need to achieve is that when I'm trying to save a table into the database, it'll first validate it, and only if it's valid it'll save it, otherwise I must to display an error.

Anyway, as much as I understood this function should get a callback of an validator function.
Which I have one, because I used the cell validating options, here it is:
```javascript
        var nameValidator = function (value, callback) {
            var phoneCell = handsontable.getDataAtCell(this.row, 2);
            if (value != '') {
                callback(true);
            } else {
                if (phoneCell != '') {
                    callback(false);
                } else {
                    callback(true);
                }
            }
        }
```

No need to get into this deeply, because it's working when I'm using it like that:
```javascript
            columns: [
            { validator: nameValidator, allowInvalid: true }, {
                type: 'dropdown',
                source: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15']
            }, {}
        ]
```

But when I'm trying to call:
```javascript
handsontableInstance.validateCells(nameValidator);
```

I get an error, it points to 'nameValidator' function from above, and it says that 'callback' function is undefined.

Anyone used this function before? Hopefully someone has some insights on this matter,
or have other ways to accomplish what I need.

Thanks in advance!

**Comment by AMBudnik** [comment]
For issues that are not related straight to Handsontable bugs, please create a new topic at [stackoverflow](https://stackoverflow.com/search?q=handsontable) using `handsontable` tag.

**Comment by seanthebean** [comment]
The parameter passed into `validateCells` is simply a function that is executed once all cells have been validated. It does not pass in a callback when it executes this function (hence the error).

It appears you're trying to use `validateCells` to pass in a particular validator (which presumably you want executed against every cell in the table?), which isn't what the method is for. The desired validator needs to be specified in the table options (and/or in each column's/cell's options), as you did in the first example you provided. When you call `validateCells`, it will simply re-validate all cells, using whatever validator is already specified in the options.

@littleneotrix If you also asked this on SO, maybe you could provide a link as a helpful reference for others?
