### ISSUE TITLE
Add freeze_column to possible context menu options

### ISSUE THREAD

**Issue by mabd91** [handsontable/handsontable#2263]
Add 'freeze_column' to the possible options of the context menu 

You can add it to the context menu demo page:
http://handsontable.com/demo/contextmenu.html

Or add it to the demo page of the manualColumnFreeze page:
http://handsontable.com/demo/column_freeze.html

It really helps instead of looking for the key inside the plugin code.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
