### ISSUE TITLE
plugin directory in bower ignore list

### ISSUE THREAD

**Issue by loistaler** [handsontable/handsontable#2264]
Why is the plugin directory in the ignore list of bower.json
I want to use the removeRow plugin, which does not seem to be included in the dist directory

**Comment by filipstachura** [comment]
:+1: same here

**Comment by DamianRodziewicz** [comment]
+1

**Comment by przytu1** [comment]
+1

**Comment by marekrogala** [comment]
:+1: please fix this! :)

**Comment by budnix** [comment]
Released in 0.15.1
