### ISSUE TITLE
Doubleclick doesn't pass on events

### ISSUE THREAD

**Issue by bhaak** [handsontable/handsontable#2266]
In src/editorManager.js on line 220 in the function onDblClick(), openEditor is called without any argument.

The MouseEvent isn't passed on and is not available in a custom editor.

**Comment by alvarotrigo** [comment]
+1

**Comment by alvarotrigo** [comment]
Any estimate for when this feature will be available?

**Comment by pezon** [comment]
@alvarotrigo try this plug-in.  I'm doing something similar to capture double click events in my app.  warning: it's not a fleshed out plugin and there are probably some bugs.

https://gist.github.com/pezon/2b6ee291f1d286461d97

**Comment by alvarotrigo** [comment]
@pezon thanks, but I think I'll wait for the official solution for it. 
Don't manage to understand how there are event for almost everything, except this basic feature, which is the edition of a cell.

**Comment by pezon** [comment]
@alvarotrigo (shrug) it is what it is, and sometimes, you have to make do with what you've got. that's why i wrote my plugin - to handle double click events on column and row headers. there are a lot of events buried in walkontable, but i couldn't figure out how to surface them. 

the fastest workaround i can think of with what you're trying to do is something like this --

    var state = {};
    hotInstance.hooks.add('dblclickCell, function(row, col) {
        state = {row: row, col: col, data: this.getSourceDataAtCell(row, col);
    });

    hotInstance.hooks.add('afterChange', function(change, source) {
        if (source !== 'edit') return;
        //...
    });

**Comment by alvarotrigo** [comment]
@pezon I'm getting the following error with your script:

> Uncaught TypeError: Cannot read property 'add' of undefined

In the line `hot.hooks.add('dblclickCell', function(row, cell) {`.

I'm including the file `handsontable-observedblclick.js` just after the full version of handsontable 0.13.1

**Comment by alvarotrigo** [comment]
I am initializing the plugin like this:

```javascript
$("#editOrders").handsontable(options);
```

And using some other funtions in this way:

```javascript
var container = $("#editOrders");
var handsontable = container.data('handsontable');

handsontable.loadData([.........]);
```

**Comment by alvarotrigo** [comment]
@pezon which version of handsontables is the plugin for?

**Comment by alvarotrigo** [comment]
@pezon I managed to solve the problem using `addHook` instead of `hooks.add`. Still, whenever I double click nothing takes place. Not even the printed messages in the console that I have in my `dblclickCell` and `dblclickRowHeader` cells.

**Comment by pezon** [comment]
it's written for the jquery-free version.  I run it with ng-handsontable

**Comment by alvarotrigo** [comment]
@pezon, as far as I know [both versions are the same](https://github.com/handsontable/handsontable/tree/master/dist). (handsontable.full.min.js) jQuery is optional in case of using datepickers.

> (It may also require jQuery, if you're using the Datepicker for date input)

**Comment by alvarotrigo** [comment]
@pezon I've changed my initialization to the javascript way, but still having to replace `hot.hooks.add(` for `hot.addHook`.

```javascript
var pepe = new Handsontable(document.getElementById('editOrders'), options);
pepe.addHook('dblclickCell', function(row, cell) {
     console.log("double 1");
});
```

**Comment by alvarotrigo** [comment]
@pezon for you to see it clearly. [Here's a reproduction](http://jsfiddle.net/fws1vc5e/11/) of the error with your own gist code.

**Comment by alvarotrigo** [comment]
Well, just in case anybody want to have an edit callback, I managed to simulate it doing this:

```javascript
		//simulating the double click callback
		var focusId;
		$('#editOrders').on('focusin', '.handsontableInput', function(){
			clearTimeout(focusId);
			focusId = setTimeout(focusHandler, 200);
		});

		function focusHandler(){
			var cell = pepe.getSelected();
			var value =  pepe.getValue();
		}
```

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Please continue the conversation in the discussion at https://github.com/handsontable/handsontable/discussions/7926?converting=1
