### ISSUE TITLE
ValidateCells issue

### ISSUE THREAD

**Issue by yuwong** [handsontable/handsontable#2268]
After upgrading to 13.0 from 12.5, calling ValidationCells in the afterLoadData event throws the following errors:

TypeError: Cannot read property 'sourceToRendered' of null
    at WalkontableTable.isRowBeforeRenderedRows (lib.js:83384)
    at WalkontableTable.getCell (lib.js:83271)
    at Walkontable.getCell (lib.js:81854)
    at Handsontable.TableView.getCellAtCoords (lib.js:66838)
    at Handsontable.Core.getCell (lib.js:63711)
    at done (lib.js:63088)
    at Handsontable.Core.validateCell (lib.js:63122)
    at Handsontable.Core.validateCells (lib.js:64005)
    at afterLoadData (app.js:2561)
    at PluginHookClass.Handsontable.PluginHookClass.PluginHookClass._runBucket (lib.js:72762)

For some reason, this.rowFilter is null at this point. As a test, protecting against null stops the error, but also stops any validation on load.

Please advice on the issue above, or on a better way to show validation after loading data.

Thanks!

**Comment by AMBudnik** [comment]
We had some major changes since 0.12.5, can you prepare a demo for that issue?

**Comment by yuwong** [comment]
http://jsfiddle.net/k044xrdj/
The above calls validateCells on afterLoadData, error message is visible in the console.

**Comment by Lukazar** [comment]
Its because the internal view doesn't exist yet.  I think if you're gonna pass the data in the constructor, you can use `afterInit`.  See this fork of your example:  http://jsfiddle.net/z5a0vw9c/

Also, calling `this.render` inside the callback doesn't make sense to me.

If you're loading data outside the constructor using `instance.loadData`, then you could probably use `afterLoadData` callback correctly. I didn't test it though.

**Comment by yuwong** [comment]
Thanks Lukazar, I should have clarified that the data is loaded using `instance.loadData`. The JSFiddle is not totally representative of the situation I am in, however, there is a need to call `render` after calling `validateCells` in the callback, otherwise the result of the validation is simply not visible, as the documentation clearly states that calling `validateCells` does not render the table with the results.
 
I have, however, shamelessly made changes to the library code to get around this:

In `this.validateCell` the `done` function has been changed to:
```javascript
function done(valid) {
      var col = cellProperties.col,
        row = cellProperties.row,
        td = instance.getCell(row, col, true);

      if (td) {
    	var cp = instance.getCellMeta(row, col);
    	cp.valid = cellProperties.valid;
        instance.view.wt.wtSettings.settings.cellRenderer(row, col, td);
      }
      callback(valid);
    }
```
The reason is I believe the `.valid` property of the `cellMeta` is not preserved somehow, and adding the two extra line appears to solve this.

As well as:
```javascript
WalkontableTable.prototype.isRowBeforeRenderedRows = function (r) {
  return !this.rowFilter || (this.rowFilter.sourceToRendered(r) < 0 && r >= 0);
};
```
The `!this.rowFilter || ` was simply to bypass the exception of undefined.sourceToRendered() call.

With the above, I can continue to show validated result following a loadData call.

**Comment by AMBudnik** [comment]
If you would have any other questions please open a new issue.

**Comment by AMBudnik** [comment]
It appears that the issue is still there https://stackblitz.com/edit/hot-tab-demo51
I'm reopening the topic

**Comment by AMBudnik** [comment]
Simplier example https://jsfiddle.net/62don0uk/

When we call `validateCells()` alone it works well but when it is called inside the `afterLoadData` it doesn't. The `afterValidate` hook is not triggered. However, it is called when we use `afterChange` hook and use the `loadData` source of changes https://jsfiddle.net/62don0uk/1/

**Comment by AMBudnik** [comment]
Hi @yuwong @Lukazar 

the issue seem to be gone in 7.4.2. https://jsfiddle.net/AMBudnik/07phnjk9/
Can you check it, please?
