### ISSUE TITLE
IE 11 + jQuery 1.10.2 + Handsontable 0.10.5 issue

### ISSUE THREAD

**Issue by jorseijo** [handsontable/handsontable#2269]
Hello,
When creating my Handsontable object this way:

dataTableStr = "dataTable" + year + month;
    
var container = document.getElementById(dataTableStr);

var ht = new Handsontable(container, {...});

IE complains saying:

Object doesn't support property or method 'call'

Any ideas??

Jorge

**Comment by jansiegel** [comment]
Have you tried using the latest version? https://github.com/handsontable/handsontable/releases/latest
If you'd rather stick to v.0.10.5, you might want to initialise HOT using jQuery:
```javascript
$('#example').handsontable({
  data: data,
  minSpareRows: 1,
  colHeaders: true,
  contextMenu: true
});
```

**Comment by AMBudnik** [comment]
Issue closed in lack of further author's activity.
