### ISSUE TITLE
Functionality which we can disable cell editor to appear

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#2273]
This feature is similar to `readOnly: true` but with the difference that `readOnly` automaticaly disables copying this value (by copy/paste and autofill). When we want to keep same behavior as the rest of the cells but without editor we can set `editor` key to `false`.

```js
hot1 = new Handsontable(container, {
  data: data,
  colHeaders: true,
  contextMenu: false,
  columns: [
    {
      editor: false // Disable editor for this column
    },
    {
      editor: 'text'
    },
    {
      editor: 'numeric'
    }
  ]
});
```

This feature is usefull for nested tables in hot-table (http://handsontable.github.io/hot-table/examples/nested-tables.html)

**Comment by krzysztofspilka** [comment]
Released in ver. 0.13.1, full note available here: https://github.com/handsontable/handsontable/releases/tag/0.13.1
