### ISSUE TITLE
Context menu's default functions changes data but doesn't call 'afterChange' event

### ISSUE THREAD

**Issue by GitHubStig** [handsontable/handsontable#2275]
On http://handsontable.com/demo/callbacks.html, triggering context menu's Insert row above / Insert row below / Insert column on the left / Remove row / etc... changes the datagrid but doesn't trigger 'afterChange' event. Is this intentional?

Performing undo after context menu functions also doesn't trigger 'afterChange'.

**Comment by Lukazar** [comment]
I would think it was intentional.  The `afterChange` event to me is meant to aid in the post processing an existing cells data value having changed.  I don't think add / removing cells would have any data to modify that it would matter.

I do agree that it should fire after an undo though.

**Comment by AMBudnik** [comment]
@Lukazar is right. Please update to 0.14.1 `afterChange` in triggered after `undo`
