### ISSUE TITLE
Last column widths is set incorrectly.

### ISSUE THREAD

**Issue by 4YEO** [handsontable/handsontable#2276]
Hi.
We're using handsontable version 0.10.5 , support for ie8 required ;( . And it looks like that there is an issue setting last column widths(it's wider that it is supposed too) check last column in you demo here: http://old.handsontable.com/demo/sorting.html .
![image](https://cloud.githubusercontent.com/assets/10268052/6704995/cc8ea818-cd58-11e4-82c4-19a513319e9b.png)
Looks like you've fixed that in last version, could you provide details what have changed so I can change it on my side as well.

**Comment by AMBudnik** [comment]
Hi, we dropped support for IE8 since 0.12.0, but there's an issue ( https://github.com/handsontable/handsontable/issues/1018) you can track for further information about this subject, I assume it can be related.
