### ISSUE TITLE
Unable to sort the custom checkbox columns in handontable

### ISSUE THREAD

**Issue by alekhyakodam** [handsontable/handsontable#2277]
Hi,
I am unable to sort the custom checkbox column.could you please help me
Here the code
 $scope.defaultCheckbox.renderer = function (instance, td, row, col, prop, value,cellProperties) {
            //Handsontable.renderers.TextRenderer.apply(this, arguments);
            var rowData = cellProperties.instance.getDataAtRow(row);
            //Set CurrentUserId since it is read empty from service.
            rowData.CurrentUserId = $scope.loggedUserId;
            var $link = $('<input>');
            $link.attr('type', 'checkbox');
            if (rowData.isAdmin && col === 2) {
                $link.attr('checked','true');
            } else if (!rowData.isAdmin && col === 1)
            {
                $link.attr('checked', 'true');
            }
            $link.on('click', function () {
                //set both checkboxes to empty.
                $link[0].parentNode.parentNode.children[1].children[0].checked = false;
                $link[0].parentNode.parentNode.children[2].children[0].checked = false;
                $link[0].parentNode.parentNode.children[col].children[0].checked = true;
                var actionRow = $filter('filter')($scope.changes, { rowNumber: row })[0];
                rowData.isAdmin = false;
                if (actionRow !== undefined && row === actionRow.rowNumber) {
                    actionRow.columnNumber = col;
                    if (col === 2) {
                        rowData.isAdmin = true;
                    }
                } else {
                    if (col === 2) {
                        rowData.isAdmin = true;
                    }
                    $scope.changes.push({ rowNumber: row, columnNumber: col, rowData: rowData });
                    $scope.role.isChangesThere = true;
                }
                if ($scope.role.isChangesThere && $scope.changes.length === 1) {
                    if (!$scope.$$phase) {
                        $scope.$apply();
                    }
                }
            });
            $(td).empty().append($link);
        };
        $scope.hot = {
            columns: [
                { data: 'FullName', title: 'User Name', readOnly: true, width: 200 },
                { data: 'Tax User', title: 'Tax User', width: 100, renderer: $scope.defaultCheckbox.renderer },
                { data: 'Admin User', title: 'Admin User', width: 100, renderer: $scope.defaultCheckbox.renderer }
            ],
            calcHeight: [],
            calcWidth: [],
            myData: [],
            hotOffset: []
        };
        $scope.hot.height = 0;
        //$scope.hot.renderTable; //Will be defined by handsontable directive.
        /*
         * Sets the HandonTable Height
         */
        $scope.hot.calcHeight = function () {
            var border = 12;
            var topOffset = $scope.hot.hotOffset.top;
            var height = $window.innerHeight - topOffset - 2 * border - 80;
            if (height < 800) {
                return 800;
            }
            return height;
        };
        /*
         * Sets the HandonTable Width
         */
        $scope.hot.calcWidth = function () {
            var border = 12;
            var leftOffset = $scope.hot.hotOffset.left;
            var result = $window.innerWidth - leftOffset - 2 * border - 80;
            if (result < 250) {
                return 250;
            }
            return result;
        };

**Comment by AMBudnik** [comment]
It would be better to figure out with a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/), please prepare one.

**Comment by alekhyakodam** [comment]
Thank you! actually the issue has been resolved now.
Solution is to add few line of code in beforecolumnsort event and renderer respectively
1) $scope.isSort = true;
2) if (!$scope.isSort) {
                var rowData = cellProperties.instance.getDataAtRow(row);
            } else {
                var rowData = cellProperties.instance.getDataAtRow(instance.sortIndex[row][0]);
            }

**Comment by AMBudnik** [comment]
Great to know :-)
