### ISSUE TITLE
custom cell type

### ISSUE THREAD

**Issue by Angularjschile** [handsontable/handsontable#2279]
is posible custom cell type
example: http://www.guriddo.net/demo/guriddojs/

edittype:"text",
                        editoptions: {
                            // dataInit is the client-side event that fires upon initializing the toolbar search field for a column
                            // use it to place a third party control to customize the toolbar
                            dataInit: function (element) {
                                $(element).datepicker({
                                    id: 'orderDate_datePicker',
                                    dateFormat: 'M/d/yy',
                                    //minDate: new Date(2010, 0, 1),
                                    maxDate: new Date(2020, 0, 1),
                                    showOn: 'focus'
                                });
                            }
                        }

**Comment by zekedroid** [comment]
Is that a question or a statement? Yes to both.

**Comment by Angularjschile** [comment]
have some example of this?

**Comment by zekedroid** [comment]
http://handsontable.com/demo/date.html

**Comment by Angularjschile** [comment]
mi idea es :
{
      type: 'date',
      render: function(element){  $(element).otherPlugins() },
      correctFormat: true,
      defaultDate: '01/01/1900'
    }

**Comment by zekedroid** [comment]
No se puede leer ese codigo, puedes agregar formato? (para formatear, agrega 4 espacios en frente de cada linea, y 4 mas por cada "tab")

**Comment by Angularjschile** [comment]
la idea es:

{  
    type: 'custom',
    render: function(element){
                             $(element).datetimepicker(); or $(element).colorpicker() etc..
                                         }
}

**Comment by zekedroid** [comment]
{
         type: 'custom',
         render: function(element) {
             $(element).datetimepicker(); or $(element).colorpicker() etc..
         }
    }

**Comment by zekedroid** [comment]
I still don't understand (keep it in English so the rest can understand but ask in Spanish if you're having trouble). What's the problem with using the `columns` option in the definition? It lets you pick the renderer there as well as the type. If the type is `custom` it'll get ignored but your renderer can take in this type and you can modify it inside.

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply.
