### ISSUE TITLE
Editable handsontable in handsontable

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#2280]
I've found the cell type handsontable. I've specified column names and data for the column with

    columns: [
        {
            data: 'budget',
            readOnly: true,
            type: "handsontable",
            handsontable: {
                colHeaders: [
                    'Quantity',
                    'Price'
                ],
                data: myData,
            }
        },
    ]

I thought I could store 'nested data' for each cell but the above code makes a handsontable in the column cells but the rows in the handsontable is clickable but not editable.

Can I make the data editable?

**Comment by AMBudnik** [comment]
Hi, this feature is the same as https://github.com/handsontable/handsontable/issues/536. For further information, please track changes in 536 issue.
