### ISSUE TITLE
Save changes with ajax

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#2281]
The demo explaining how to save and load with ajax assumes that row number equals id. What if this is not the case? In my project I can edit items in different groups so an item's row number in a group does not equal the item's database id.

I guess I need to assign the database id to newly created rows in `afterCreateRow` and populate the `changes` attribute with an id in `afterChange`. It seems rather complicated to solve my problem, so I wonder if someone has got a good solution for this case? I'm really in need of a good solution.

**Comment by TheLudd** [comment]
The data you pass into the [constructor](https://github.com/handsontable/handsontable/wiki/Options#constructor-options) can be an array of objects. You can then get that object back, with things such as id with [getDataAtRow](https://github.com/handsontable/handsontable/wiki/Methods#get-data-methods). Configure how the object properties should map to the columns in the table with [column options](https://github.com/handsontable/handsontable/wiki/Options#column-options)

**Comment by AMBudnik** [comment]
Issue will be reopen after author reply.
