### ISSUE TITLE
Error after changing to 0.13.1 (Uncaught TypeError: object is not a function)

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2283]
[Reproduction of the error](http://jsfiddle.net/fws1vc5e/7/)

![error](https://cloud.githubusercontent.com/assets/1706326/6733398/ec045c78-ce49-11e4-9c91-4d77b6084d21.PNG)

It gets solved by just removing the `<div id="wrap">` wrapper. Which took a while to figure out.
It works with any other `id` name.

**Comment by AMBudnik** [comment]
Thank you very much @alvarotrigo

**Comment by budnix** [comment]
Fixed in 0.14.0
