### ISSUE TITLE
Styling handsontable

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2284]
I'm facing some difficulties trying to style handsontable.
I'm trying to remove the handontable background, shadow and border from the last column of the table and for it, I was using this:

```css
#edit td:last-child,
#edit th:last-child{
	background: none;
	border:0;
}
```
Which was working fine in version 8.

Now, in version 13, I've noticed that in autocomplete cells I can not see the highlighting of the current one or of the one with the mouse over it anymore. 

I've tried to see if I could use some of the classes applied in the different table elements to differentiate between the real table and the secondary tables (such as the one used in `autocomplete`), but it doesn't seem simple to find the proper way of using them (and probably not even reliable as those class names might change in future versions of handsontable)

The name of those classes is not very descriptive and that's also something that complicates it a bit more, as its difficult to see if they are exclusive or will be shared with other secondary tables.

I was wondering what approach you guys would suggest for such a basic style modification.

**Comment by AMBudnik** [comment]
Hi @alvarotrigo shadow is set to:
 ```.handsontable .handsontable table``` 
(498 line in handsontable.full.css), 

but if you'll comment this lines there'll be no shadow for all the header section, so when you want to have shadow below every header else than last-child, replace 498 line with:

```.handsontable .handsontable table th:not(:last-child)```

about table header's last child it's at 113 line  ``.handsontable th:last-child ``

**Comment by alvarotrigo** [comment]
@AMBudnik I know where are the styles defined. 
But as I explained previously, if I overwrite them:

> I've noticed that in autocomplete cells I can not see the highlighting of the current one or of the one with the mouse over it anymore.

**Comment by Lukazar** [comment]
I'm not be understanding 100%, but the secondary tables live within a wrapper with the class `handsontableInput`.  You could you use that to your advantage?

**Comment by jansiegel** [comment]
> I may not be understanding 100%, but the secondary tables live within a wrapper div with the class handsontableInput. You could you use that to your advantage?

The autocomplete dropdown has the same DOM structure as the 'original' Handsontable instance, so you can style it in the same manner you would style the main instance.
Just like @Lukazar noticed, the editors are stored in a separate wrapper, so you can use that fact to your advantage, and also, these editors usually have additional classes assigned. 
For example, autocomplete editor instance has the `autocompleteEditor` class assigned, so you can prepend your styles with `.handsontable.autocompleteEditor`, and it should work fine.
