### ISSUE TITLE
a row could not be moved correctly after sorting

### ISSUE THREAD

**Issue by CarlosLYT** [handsontable/handsontable#2285]
I transfer "columnSorting: true,manualRowMove: true,"these two items to the handsontable in my code.
When I move a row after sorting , it could not be move to the right position,and other row's position may be changed due to this operation.
I find that "hotInstance.sortIndex" and "hotInstance.manualRowPositions" both contain an array of physicalIndexs .The conflict between these two arrays may be the reason.

I just modify the code in : http://jsfiddle.net/api/post/library/pure/ 

here is the difference:
 hot = new Handsontable(container, {
    data: data,
    rowHeaders:true,
    columnSorting: true,
    manualRowMove: true,
    colHeaders: true,
    contextMenu: true
  });

The table is awesome and nice! Although it is not easy to be extended,but it help me a lot.Thank you very much!:)

**Comment by AMBudnik** [comment]
Hi, thanks for that report. You're right at [this demo](http://jsfiddle.net/a731yarL/) we can see that when:

1. we sort B column
2. move B5 (with value: 5)
3. to position B2
4. we recieve our B5 cell on B3 not B2.

**Comment by AMBudnik** [comment]
Demo is working fine with newest 0.16.1 version.

**Comment by CarlosLYT** [comment]
Thank you very much! ∩ˍ∩
