### ISSUE TITLE
Add support for settings specification as json 

### ISSUE THREAD

**Issue by jrowen** [handsontable/handsontable#2286]
This is a feature request.  Would it be possible to enhance the settings specification for `Handsontable` to fully support a json object.  There are a few table options, like `renderer` and `validator` that need to be specified as javascript and will throw an error if specified as strings.  [Here](http://handsontable.com/demo/heatmaps.html) is an example.

The benefit of this update would be to make it easier to use the library from other languages passing both settings and data as json.  This question originated from a [project]{https://github.com/jrowen/rhandsontable} to enable Handsontable as a visualization and input tool for R.  One of the challenges we ran into was building the table settings object in R as json, and then converting the json on the client to a format understood by Handsontable.

**Comment by AMBudnik** [comment]
Thank you @jrowen we'll take it under consideration.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
