### ISSUE TITLE
Add the ability to copy with headers

### ISSUE THREAD

**Issue by mburbea** [handsontable/handsontable#2288]
In excel it is common for the headers to be another row worth of data. In handsontable, it is more common for it to be set up as column headers.
It would be a useful enhancement to allow the copying of the data with column headers, like how SQL server allows it, either through a different key combination (e.g.  ctrl-shift-c) or with a context menu item.

**Comment by AMBudnik** [comment]
OK, thank you for that suggestion - it could be helpful.

**Comment by toresenneseth** [comment]
+ 1 for this feature

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by sushan05** [comment]
+1 for this feature from my side also

**Comment by sleepy-byte** [comment]
+1. I was looking for this.

**Comment by maurerke** [comment]
+1 
@AMBudnik Is that on the roadmap or possible in the near future?

**Comment by AMBudnik** [comment]
I have added the idea to Trello. You can vote for it at https://trello.com/c/aijnkmSc/86-add-an-ability-to-copy-data-with-headers-2288-gh

**Comment by totoSalad** [comment]
+1  Is there any ideas about how to implement instead of updating plugin ?

**Comment by tandang213** [comment]
+1

**Comment by tandang213** [comment]
Any update for this?

**Comment by AMBudnik** [comment]
@tandang213 sorry, we're having a stable 8.0.0 and 7.3.0 (with a new feature) versions on our Roadmap for December. In 2020, January we'll have a new planning meeting and decide what to do next. I will make sure to mention this feature.

**Comment by AMBudnik** [comment]
Hi @mburbea @toresenneseth @tandang213 @davidzhangran @totoSalad @lawrence-laz @sushan05 @maurerke 

I'm more than happy to announce that we're finally ready with this functionality.

I just posted a more extended introduction to this issue (and a small ask for translations 🙏 ) here https://github.com/handsontable/handsontable/issues/10112. 

I will update you all once we publish the version with the new feature.

**Comment by aninde** [comment]
This feature will be added with the upcoming v12.3. It works well with each wrapper.

**Comment by AMBudnik** [comment]
Hi @mburbea @toresenneseth @sushan05 @lawrence-laz @maurerke @totoSalad @tandang213 @davidzhangran

We just released Handsontable v12.3.0 with Copy with headers. Here https://jsfiddle.net/xmf5egjb/ you can do a quick test of the new functionality. And here https://handsontable.com/docs/javascript-data-grid/release-notes/#_12-3-0 is the full list of changes for this version.
