### ISSUE TITLE
Changing Cell Background

### ISSUE THREAD

**Issue by vnikiten01** [handsontable/handsontable#2289]
Hello,

Im changing a cell background color based on a data value that is not displayed on the table.  
If the value exists then certain cells backgrounds are changed.

The color is changing as expected.  The problem that I am encountering ->  those cells are no longer updating when their values are changed.  

cells: function(row, col, prop) {
          if(true) {
                cellProperties.renderer = function (instance, td, row, col, prop, value, cellProperties) {
                          td.style.background = '#F5ECCE';
                }
          };                            
}

Anyone idea why this is happening problem

**Comment by AMBudnik** [comment]
Please prepare a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/), it'll be better to check your code and find the best way to archieve your goal.

**Comment by vnikiten01** [comment]
I realized the error had to do me needing to rerender the cells to specific types like, text, numeric.  Too bad there isn't a dropdown option.  Thanks Anyway.
