### ISSUE TITLE
NO_MODIFICATION_ALLOWED_ERR: DOM Exception 7: An attempt was made to Safari

### ISSUE THREAD

**Issue by elioth010** [handsontable/handsontable#2290]
This error is showed when i try to use in Safari Browser

NO_MODIFICATION_ALLOWED_ERR: DOM Exception 7: An attempt was made to Safari

**Comment by AMBudnik** [comment]
Hi @elioth010 I've tried to reproduce this statement but on mac with Safari 8.0.4 (10600.4.10.7) I didn't get it. Please specify your HOT and browser's version.
