### ISSUE TITLE
Bower dependency ordering mismatch for Pikaday and moment.js

### ISSUE THREAD

**Issue by morungos** [handsontable/handsontable#2296]
Just struggled to get date editing right in my app, and poking through the layers, moment was being loaded after Pikaday, not before, as is needed to set the hasMoment flag it uses (on load) to detect that. I'm using Bower to manage dependencies, but it had got the ordering wrong. A small change to bower.json, putting moment.js before Pikaday in the dependency object, appears to resolve the issue -- at least when tested in an override. 

Made a pull request #2295 for this small fix.

**Comment by budnix** [comment]
Pull request was merged into develop and it's ready for next release. Thanks!
