### ISSUE TITLE
How to make grid width dynamic so it can resize itself  according to screen resolution

### ISSUE THREAD

**Issue by agucabral21** [handsontable/handsontable#2297]
I havent been able to achieve this without having some other problem with the grid, can anyone help me? the width option of the grid is for px and not %, how can i do this last one?

**Comment by AMBudnik** [comment]
Hi @agucabral21 please provide a demo or/and describe what you want to achieve, like you want the hot to be 100% of it's ```div``` and stretch or shrink when someone go mobile?

**Comment by agucabral21** [comment]
Yes, that is exactly what I want... but in my case is for different computer screen resoultions. Ive set the width option of the grid to 1400, and when i try it in a smaller resolution than the one i use, ex: 800*600, the grid doesnt fit on the screen and need to scroll horizontally the window to get to the end of it

**Comment by Lukazar** [comment]
You could try setting an event listener on the window resize event.  From there you can make whatever calculations you need and update the width and hight using `instance.updateSettings`. 

This is currently my approach.

**Comment by AMBudnik** [comment]
good approach @Lukazar - thank's for support.
