### ISSUE TITLE
Submenu in ContextMenu

### ISSUE THREAD

**Issue by gabiufrj** [handsontable/handsontable#2298]
Hello guys, kudos for making such an awesome grid!

I've been trying to use submenus in my handsOnTable grid contextMenu, using the specification provided in [jQuery-contextMenu](http://medialize.github.io/jQuery-contextMenu/docs.html), but it doesn't seem to work in the latest release version =(.

Searching the issues list, it looks like the issue was solved in version 0.11.0, but I've created a jsFiddle trying to create a sub-menu item [jsFiddle](http://jsfiddle.net/z8xqvod9/), but I can't seem to work it out.

Is there anything wrong in what I'm doing or the feature got removed?

Thanks in advance!

**Comment by AMBudnik** [comment]
Hi @gabiufrj I made some little changes in [your Fiddle](https://jsfiddle.net/z8xqvod9/1/). Please check if it's helpful.

**Comment by gabiufrj** [comment]
Thanks for your help, @AMBudnik! It sure helped!

Sorry for such simple issue, but I couldn't find it in the docs =/.

**Comment by AMBudnik** [comment]
No problem, glad I could help.

**Comment by gabiufrj** [comment]
Just for information: When a submenu is defined as in the fiddle you showed, you MUST define a callback for each item in the submenu, because the default callback isn't fired.

Is there a way I can contribute to the docs, creating an example/fiddle for this?

**Comment by AMBudnik** [comment]
Updated [example](http://jsfiddle.net/6k1vo0xs/) for 0.19.0 which does not work as expected. There's an `undefined` for submenu.

**Comment by lethunder** [comment]
i succeded to make this work by first making a  contextMenu: false in a hot.updateSettings then another hot.updateSettings with the real contextmenu a want :)

**Comment by samsonkhisty** [comment]
I succeeded to get the submenu working in this example: https://jsfiddle.net/fuggfuggfugg/qvfsk04f/

I had to debug and see how the alignment was working in the library.

**Comment by AMBudnik** [comment]
Thanks for sharing @samsonkhisty 
Don't know how I missed that!

**Comment by jonasespelita** [comment]
Can the docs be updated to have a multilevel example? Had to dig through here to get how the multi level works.

**Comment by AMBudnik** [comment]
You're right @jonasespelita 
there's no information about submenus in our docs. We should add it there, create a blog tutorial or share it via 'How to'.

**Comment by wszymanski** [comment]
Proposals for changes were written as comments to commit: https://github.com/handsontable/handsontable/commit/53bb90d3540b18050dad0e03d1388d76e1dc06e5

**Comment by AMBudnik** [comment]
Hi @gabiufrj we have finally made the change. Sorry for keeping you waiting so long. I'd be happy to hear your feedback about the changes

**Comment by AMBudnik** [comment]
I am closing this issue, however, feel free to leave any additional comments. Thanks in advance!
