### ISSUE TITLE
can't update the Option "Cell" but can only use cells:function() ?

### ISSUE THREAD

**Issue by ericyang89** [handsontable/handsontable#2299]
the code below do not work 
hot.updateSettings("cell", myArray);
hot.render();

I am wondering when and where   can I use the function "updateSettings" ?

Any reply will be highly appreciated!

**Comment by Lukazar** [comment]
If you can create a demo using http://jsfiddle.net/.  It will be easier to help you.

**Comment by AMBudnik** [comment]
Issue closed in lack of recent author's activity or/and needed demo.
