### ISSUE TITLE
Add copy/paste to the context menu

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#23]
That would be really cool to add copy/cut/paste in context menu, but I cannot find a good way to do it. I found resources that describe how to do it with Flash (which I would like to avoid):
- http://googlesystem.blogspot.com/2012/03/google-docs-and-clipboard-access.html
- http://brooknovak.wordpress.com/2009/07/28/accessing-the-system-clipboard-with-javascript/

I have tested Google Docs with Flash disabled (in Chrome and FF) and copy/paste from context menu worked like a charm. So there must be a way. Any ideas?

**Comment by AMBudnik** [comment]
@lil25 thanks for creating also a new issue for this request.
I have already marked it as a feature request.
