### ISSUE TITLE
comments demo Bug when use contextMenu to add comment

### ISSUE THREAD

**Issue by ericyang89** [handsontable/handsontable#2300]
http://handsontable.com/demo/comments.html

when use contextMenu to add comment it only work once ,whick means it do not work for the second times.

**Comment by ericyang89** [comment]
i also want to know how to save the comments to  DataBase or How to manually add comments

**Comment by AMBudnik** [comment]
About saving comments, there isn't an option for this right now, but after we ged rid of this issue you described (with ability to add only one comment), we'll definitely go further. So to track changes about this issue please follow https://github.com/handsontable/handsontable/issues/2071
