### ISSUE TITLE
dropdown key and value

### ISSUE THREAD

**Issue by c941010623** [handsontable/handsontable#2302]
how can i get the key and value in the dropdown ??

when i use .getData() , i want get the dropdown's id not text

how can i do it ??

**Comment by Lukazar** [comment]
The same question is asked here:  https://github.com/handsontable/handsontable/issues/2305

**Comment by c941010623** [comment]
i wish cellProperties.source=[{id:xxx, text:ooo}]

**Comment by AMBudnik** [comment]
For more information please track changes to https://github.com/handsontable/handsontable/issues/2293
