### ISSUE TITLE
Handsontable cell type

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#2304]
When a column has data type 'handsontable', the child handsontable disappears when you scroll which is a big problem if the child handsontable has many rows.

When scrolling with arrow keys it only highlights 1 cell instead of the entire row (which it does when hovering with mouse).

The bugs are also present at http://handsontable.com/demo/handsontable.html

The handsontable cell type could be a fantastic feature (both if it was editable and as it is now) if those things worked.

**Comment by AMBudnik** [comment]
I couldn't experience hiding after scroll - can you provide your OS/browser info? But the second thing about highlighting only 1 row is not quite a bug, but it can be misunderstood after the user isn't able to edit cells in the child element.

**Comment by AMBudnik** [comment]
Issue will stay closed till author's reply.
