### ISSUE TITLE
Entire Handsontable read only

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#2306]
Is it possible to make an entire handsontable instance readOnly (or editor=false)?

**Comment by AMBudnik** [comment]
Like in our wiki:

```readOnly : Boolean (default false)```

But remember, that it makes **cell** read only. Sorting, column resizing .etc are allowed and ablity to set ```readOnly : false``` from contextMenu also. 

like in this [demo](https://jsfiddle.net/gst1egoz/)
