### ISSUE TITLE
Copy nested table to another table by autofill

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#2307]
Actually copying nested table into another table by autofill is copied by reference. Must be copied by deep copy.

##### Screenshot:

![autofill](https://cloud.githubusercontent.com/assets/571316/6824675/9d111656-d2f4-11e4-876e-652ba107ac68.gif)

**Comment by jeanmarc78** [comment]
hello budnix,
how do you make this animated gif (tools ,tuto) ?
regards
jm

**Comment by budnix** [comment]
On my mac i use QickTime to record fragment of screen (https://support.apple.com/en-us/HT201066) and I export it as .mov file. Then convert it to .gif using gifrocket app (http://www.gifrocket.com/). On other OS I don't know how to do this :)

**Comment by jeanmarc78** [comment]
thanks, i  will try to find equivalent windows tools
regards
jm

**Comment by warpech** [comment]
For future reference, here's a similar working demo: http://jsfiddle.net/warpech/owh1ze7v/5/
