### ISSUE TITLE
Event when validateCells has ending ?

### ISSUE THREAD

**Issue by Klaitos** [handsontable/handsontable#2308]
Could we have an event when validateCells has ended ?
I need to show a loader when click on a "Validate handsontable" and then hide this loader when validateCells is over.

Thanks

**Comment by mabd91** [comment]
Check "afterValidate" in the events list https://github.com/handsontable/handsontable/wiki/events.

Also I think that validateCells takes a call-back function that is run after the validation is over.

**Comment by AMBudnik** [comment]
Good explanation @mabd91, thanks for support. I will close this issue, but feel free to write back if something's not clear, or open a new one in case of other questions.

**Comment by Klaitos** [comment]
afterValidate is called after EACH validation, i need an even when all validation are finished.
And when i'm calling    hot.validateCells(function () { console.log('validation is over'});
The console.log is called 2 times at the begining and 1 time at the very end :/

**Comment by AMBudnik** [comment]
Can you please prepare a [demo](jsfiddle.net/api/post/library/pure/) with your code?

**Comment by AMBudnik** [comment]
Issue will stay closed till a needed demo example or new activity.
