### ISSUE TITLE
Creating ContextMenu items on demand pr cell

### ISSUE THREAD

**Issue by toresenneseth** [handsontable/handsontable#2312]
Is there any way to dynamically set the items of a context menu based on the cell that is right clicked? I need to show a different set of context menu items for each column, and ideally for each cell. 

In my case, I need access to the underlying data of the current row and the column of the clicked cell to determine how to fill the context menu. Disabling any items that are invalid for the current context won't be a good solution for me, because it would mean that the context menu would contain a lot of disabled items.

If filling the context menu based on the clicked cell is not possible, would it be possible to fill it based on which column the clicked cell belongs to?

Thanks!

**Comment by AMBudnik** [comment]
I guess it could be possible by a callback related to a type of the cell, but we do not have that kind of option right now. Although great idea for an advanced feature.

**Comment by toresenneseth** [comment]
After some investigation, it seems I'm able to achieve what I want by adding a hook to the 'beforeOnCellMouseDown' event, and then using getSourceAtDataRow and optionally getCellMeta to obtain the context (row data / col info), and then (re)build the context menu before calling updateSettings. It seems to work, but I haven't tested it extensively, so this approach might cause some issues later...time will tell. 
It would be nice to be able to do this using a built-in feature (I'm new to using handsontable, so I'm not sure if updating the settings in a beforeOnCellMouseDown callback is a good idea), but I'll leave it up to you to decide the importance of this (and close the issue) since this approach seems to be working.

Anyway, here's a sample code (written in TypeScript) if anyone else wants to do the same thing;

// SAMPLE CODE START
this.hotInstance = new Handsontable(this.elem, settings);
this.hotInstance.addHook('beforeOnCellMouseDown',(event, coords, TD) => {
	if (event.button === 2) {		
		var dataRow = this.hotInstance.getSourceDataAtRow(coords.row);
		var cellMeta = this.hotInstance.getCellMeta(coords.row, coords.col);                                
		
		var prop = cellMeta.prop; // get the name of the object property bound to the cell
		var opts: ht.ContextMenuOptions = { items: {} };
		opts.items[prop] = {
			key: prop, name: 'Menu item for ' + prop, callback: (key: string, options: any) => {
				alert(key + ' clicked');
			}
		};

		var setting = this.hotInstance.getSettings();
		setting.contextMenu = opts;
		this.hotInstance.updateSettings(setting);
	}
});

// SAMPLE CODE END

**Comment by AMBudnik** [comment]
Thank you, it looks very promising - we'll take a closer look.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
It is currently available by excluding some options from the menu. Here's a working demo http://jsfiddle.net/handsoncode/m22wcxv7/
