### ISSUE TITLE
lastElem.style is undefined

### ISSUE THREAD

**Issue by tepaleguiojo** [handsontable/handsontable#2313]
I'm trying to set the width and height of the handsontable based on window size based on this [tutorial](http://handsontable.com/demo/scroll.html). But when I change the windows size, it throws an error on console ```lastElem.style is undefined``` on the condition ```if (lastElem && lastElem.style.position === 'fixed') { ... }```. 

What is the solution to this problem?

**Comment by AMBudnik** [comment]
Please prepare a [JSFiddle](https://jsfiddle.net/api/post/library/pure/) for that issue, it'll be much easier to see the rest of code also.

**Comment by tepaleguiojo** [comment]
I'm using Firefox 36.0.1 on Windows 7.

This is the [demo](https://jsfiddle.net/tepaleguiojo/a2v3ukr8/4/)

**Comment by AMBudnik** [comment]
Hi @tepaleguiojo I updated to 0.23.0 (https://jsfiddle.net/a2v3ukr8/5/) and didn't get any console errors. Can you confirm?

**Comment by AMBudnik** [comment]
I'm closing this issue as it wasn't recently updated but if you'll have any tips/investigation results please feel free to leave a comment.
