### ISSUE TITLE
First column as headers with custom html

### ISSUE THREAD

**Issue by WolkoDav** [handsontable/handsontable#2319]
The question is in the title.

**Comment by AMBudnik** [comment]
Hi @WolkoDav can you provide more information what you want to do? Using `html` in headers is described in [this demo](http://handsontable.com/demo/renderers_html.html)

**Comment by WolkoDav** [comment]
I see this, but I want to, what would the header was not the first row. I want first column.

**Comment by AMBudnik** [comment]
There is a example for header also named 'Rendering custom HTML in header'. You can use HTML to change column headers. If you want to make only a first column cells custom there is not a problem also.

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity or/and unsolved questions.
