### ISSUE TITLE
Security brake: Too much TRs...  on big mergecells

### ISSUE THREAD

**Issue by fbrussa** [handsontable/handsontable#2320]
Hello, when defining a large mergecell, this triggers the "Security brake: Too much TRs" Error

http://jsfiddle.net/3k3rq5vp/

**Comment by AMBudnik** [comment]
Hi, please track changes to https://github.com/handsontable/handsontable/issues/2233

**Comment by fbrussa** [comment]
Hi Aleksandra. That does not seem to be the same bug.

**Comment by AMBudnik** [comment]
OK, we're take a closer look at this subject.

**Comment by swistach** [comment]
This issue was resolved and now it works as expected: http://jsfiddle.net/3k3rq5vp/1/

**Comment by swistach** [comment]
I think we can close this issue. Feel free to reopen it, if this bug still occurs.
