### ISSUE TITLE
afterChange not triggered when clicked outside the table

### ISSUE THREAD

**Issue by Zukeh** [handsontable/handsontable#2322]
Example: http://jsfiddle.net/3a9o82pd/

Clicking on side of the table triggers autosave
Clicking below the table does not trigger autosave. Same behavior if table is loaded in an iframe.
This was working in previous versions (At least until 0.10.3).

**Comment by Zukeh** [comment]
Thank you for replying but I wouldn't say this is a feature request... more of a bug report. Clicking anywhere outside the cell that is being edited should trigger the autosave - that is the expected behavior. It was working before when HoT was still dependent on jQuery.

Thank you again.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
This behavior doesn't seem to be replicable using the latest version of Handsontable.
Please comment if it works for you differently.
