### ISSUE TITLE
Autofill with merged cells throws an error

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2323]
When using autofill (copying the cell content with the fill handle) with the merged cells, Handsontable throws an error:
`Uncaught TypeError: Cannot read property '0' of undefined`

---------

#### Steps to reproduce:
* Go to http://handsontable.com/demo/merge_cells.html
* Click the merged cell fill handle and drag it down
* See the error being thrown

**Comment by jansiegel** [comment]
It works fine after @budnix's fix, but the merge-autofill functionality is still pretty inconsistent, we will have to work on that.

**Comment by krzysztofspilka** [comment]
It works fine now (not throwing an error) but the fill handle disappears after dragging down.

**Comment by krzysztofspilka** [comment]
Released in https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
