### ISSUE TITLE
HandsOnTable is not working in Pop-up windows/Dialog windows

### ISSUE THREAD

**Issue by crazyjavatricks** [handsontable/handsontable#2324]
hi guys, 

I have an issue in handsontable while using its on a dialog window. the cells  will not be editable at that time. and the date picker plug-in will be crash. can anyone give me a solution for this. 
am using the latest(13.1) handsontable versions(both CSS and JS).

**Comment by jansiegel** [comment]
Hi, @crazyjavatricks! Can you make an example of your problem on [JSFiddle](http://jsfiddle.net/) or [CodePen](http://codepen.io/)? It would make it easier for us to narrow down the issue.

**Comment by malkstar** [comment]
I've also had problems with the edited cell input being all the way to the left in dialogs. Trying to recreate in JSFiddle because I thought it was the dialogs fault but seems not. Here's an ugly but working implementation: http://jsfiddle.net/hu4tdf6k/.

**Comment by AMBudnik** [comment]
Seems to work fine in v0.24.1. Can you confirm it @crazyjavatricks ?
