### ISSUE TITLE
[Question] Collapse column when init

### ISSUE THREAD

**Issue by dancingbee21** [handsontable/handsontable#2326]
Hello guys,
I already know that there is groups option in handsontable.
In my case, table width is wide...so I need to collapse columns when draw the table.
Can I create a table grouping header as shown below when loading...?
Any help would be appreciated. 

![20150331](https://cloud.githubusercontent.com/assets/11736914/6919341/1e3dc822-d7f1-11e4-8bd2-5b114797bf09.PNG)

**Comment by AMBudnik** [comment]
Grouping feature is deprecated
