### ISSUE TITLE
Suggesting adding change source as an optional parameter to a validator

### ISSUE THREAD

**Issue by morungos** [handsontable/handsontable#2327]
I'm finding a tricky problem with the current API for a validator, although I have a suggestion to fix and I'm happy to make PR if that'll help.

My app uses Handsontable with websockets to do synchronous editing, so I need to detect a change to a cell and propagate it to peers. However, the actual writing happens in a validator, so I basically use a PUT request and check status to see if a value was OK. That all works fine. The problem is with websockets, I send events to peers, and they have to make the same update. They do, and this triggers the validator and makes a second write to the same field, which is also successful, and triggers a cascade of updates.

The obvious solution is to avoid writing (and assume validity) for a value that was not the result of an edit, but the validator can never tell that, because the change source (which makes sense for this purpose) isn't passed. Or, maybe find some way to set a value bypassing the validator, although I can't find a way. The problem is in Core#validateCell:

```
      instance._registerTimeout(setTimeout(function () {
        validator.call(cellProperties, value, function (valid) {
          valid = Handsontable.hooks.run(instance, "afterValidate", valid, value, cellProperties.row, cellProperties.prop, source);
          cellProperties.valid = valid;

          done(valid);
          Handsontable.hooks.run(instance, "postAfterValidate", valid, value, cellProperties.row, cellProperties.prop, source);
        });
      }, 0));
```

I tried to use the hooks, but none of them are asynchronous, so I can't then validate, because the PUT response will arrive later.

I'd suggest making the source an optional extra argument to the validator, i.e., something like:

```
      instance._registerTimeout(setTimeout(function () {
       var hookFn = function (valid) {
         valid = Handsontable.hooks.run(instance, "afterValidate", valid, value, cellProperties.row, cellProperties.prop, source);
         cellProperties.valid = valid;

         done(valid);
         Handsontable.hooks.run(instance, "postAfterValidate", valid, value, cellProperties.row, cellProperties.prop, source);
       };
       if (validator.length == 3) {
         validator.call(cellProperties, value, source, hookFn);
       } else {
         validator.call(cellProperties, value, hookFn);
       }
      }, 0));
```

There may be another solution to this, but I can't think of one that isn't truly terrible.

**Comment by morungos** [comment]
I do have a workaround for this, but it's nasty. I use the `beforeValidate` hook to change the value to: `{$value: value, $source: source}` and then that gets passed to the main validator, allowing it to pick up the source. Of course, this binds the validator to fail without this hook, so I really don't like it even though it does work.

**Comment by AMBudnik** [comment]
Hi @morungos does it still occur? I'm not sure if I'm getting the idea.

**Comment by AMBudnik** [comment]
I assume that you could solve or abandon presented structure. I'm closing this issue.
