### ISSUE TITLE
Excel-like UI for manualColumnMove

### ISSUE THREAD

**Issue by mattkrick** [handsontable/handsontable#2328]
I've gotten some comments saying the `manualColumnMove` handler is not intuitive to find. Would it be possible to make this work like excel/google sheets where it is the whole length of the column? I haven't dug too much into the code but would be happy to write a PR.

**Comment by AMBudnik** [comment]
Thank you, it would be a helpful feature. We'll see what we can do.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
