### ISSUE TITLE
Documented method of scrolling to a cell

### ISSUE THREAD

**Issue by wolever** [handsontable/handsontable#2330]
Currently there is no public method available to scroll a cell into view.

I'd like to use this method with a search field so that I can scroll the first search match into view.

**Comment by krzysztofspilka** [comment]
Hi @wolever, actually there is a method for that, try this:

`hot.view.wt.wtScroll.scrollViewport(new WalkontableCellCoords(row,col))`

**Comment by krzysztofspilka** [comment]
And then to select a certain cell use a `selectCell` method, e.g.:
`hot1.selectCell(50, 40)`

https://github.com/handsontable/handsontable/wiki/Methods

**Comment by wolever** [comment]
Sorry, should have clarified in the original issue. Can this method be considered part of the public API? Or may it change in the future?

**Comment by krzysztofspilka** [comment]
@wolever `scrollViewport` is not considered as a public but it's not private neither. It won't be changed in the nearest future (take a look at https://trello.com/b/wMvdMvow/handsontable-roadmap-2015, I can't see there tasks that would require changing in that method).
