### ISSUE TITLE
Issue with rendering default values when upgrading handsontable js

### ISSUE THREAD

**Issue by tboeckmann** [handsontable/handsontable#2331]
I have recently upgraded from version 11.4 to 13.1 of handsontable and have an issue with default values begin rendered.

The issue traces back to the change from version 12.0 to 12.1:

Working 12.0
https://jsfiddle.net/2boeevcq/
![image](https://cloud.githubusercontent.com/assets/2022378/6930994/65086154-d800-11e4-8222-f05615d283e7.png)

Broken 12.1
https://jsfiddle.net/opccbcox/
![image](https://cloud.githubusercontent.com/assets/2022378/6931013/8863e8d0-d800-11e4-8f31-f6992166eaf6.png)

Since version 12.1, the wrong value in the "spare row" causes the option: 'minSpareRows' to trigger when the checkbox is ticked. This was not a problem before- what was changed to cause this?

**Comment by jansiegel** [comment]
@tboeckmann You might want to try to update directly to Handsontable 0.14.0, it seems that your example works fine with it: https://jsfiddle.net/9x07gm0q/

**Comment by tboeckmann** [comment]
Thanks @jansiegel - I have just upgraded and this does fix it.
