### ISSUE TITLE
Sorting issue with plain text and html in the same column

### ISSUE THREAD

**Issue by arthuryegiazaryan** [handsontable/handsontable#2333]
I'm having a problem sorting a column which contains plain text as well as html like an anchor tag. The sorting seems to be occurring on the value stored in the data source array rather than the displayed value. The cells containing an anchor tag are always sorted above the plain text cells.

Below is a JSFiddle with an example. What I would like is for the third column to sort alphabetically the names regardless of whether the cell contains an anchor tag or plain text.

<b>Example:</b> http://jsfiddle.net/5sL2jkqt/

{ data: 2, renderer: "html" }
I tried applying a custom cell renderer on the third column but that did not help. Any suggestions on how to get around this would be much appreciated!

This question is also on <a href="http://stackoverflow.com/questions/29394806/sorting-issue-with-plain-text-and-html-in-the-same-column-using-handsontable" target="_blank">stackoverflow</a>

**Comment by AMBudnik** [comment]
OK, I see what you mean. Sorting starts with a first sign which is a `<` in this example and it should ignore `html` and sort by a string value inside the `html`.

**Comment by arthuryegiazaryan** [comment]
I ended up adding a stripTags function and then called this function whenever <i>this.sortIndex.push([i, stripTags(instance.getDataAtCell(i, this.sortColumn + colOffset), "")]);</i> was invoked and changed it to: <i><b>this.sortIndex.push([i, stripTags(instance.getDataAtCell(i, this.sortColumn + colOffset), "")]);</i></b>  This works for what I need it to do until this feature/fix is applied in subsequent versions.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
updated demo: http://jsfiddle.net/5sL2jkqt/1/

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
