### ISSUE TITLE
afterRemoveRow corrupts the sort index with nasty side-effects

### ISSUE THREAD

**Issue by einarj** [handsontable/handsontable#2334]
The way the sort index was adjusted when rows were removed was incorrect
in some cases which caused various side-effects.

A demo of this behaviour can be seen in this fiddle:
http://jsfiddle.net/einarj/Lj3xagn3/

**Comment by AMBudnik** [comment]
Thank you for that report.

**Comment by AMBudnik** [comment]
Issue no longer exists. Please check update (0.24.1) demo: http://jsfiddle.net/Lj3xagn3/1/
