### ISSUE TITLE
Autocolumnsize should make room for autocomplete options

### ISSUE THREAD

**Issue by abliss** [handsontable/handsontable#2335]
Fiddle: http://jsfiddle.net/rbL773yv/1/
To reproduce: Click the down arrow in the empty cell.
Expected: see two options, "BMW" and "ChryslerNissanSuzukiToyotaVolvo"
Actual: see "BMW" and "Chry..."

ChromeOS	41.0.2272.102

**Comment by AMBudnik** [comment]
Duplicated. Please track changes to this issue https://github.com/handsontable/handsontable/issues/1255
