### ISSUE TITLE
Loads only 11 rows if style overflow-y auto is used

### ISSUE THREAD

**Issue by abecea** [handsontable/handsontable#2339]
The handsonetable component loads only 11 rows if a style like this is used: style="overflow-y: auto; width: 400px"
The remaining rows are loaded on grid click or on scroll click. Why 11 rows? Is this functionality by design?

Here is a jsfiddle demo:

http://jsfiddle.net/99jxLkc3/4/

Thanks,
Alin

**Comment by AMBudnik** [comment]
Hi, I tried your demo with 0.14.1 and it loads a table descibed in your code:
` $(scolllll).css('height', '400');` - which is 16,5 rows.
