### ISSUE TITLE
Resize handlers positioned incorrectly in containers with `translate3d` enabled

### ISSUE THREAD

**Issue by remko** [handsontable/handsontable#2340]
When a table is placed inside a container that has `translate3d` enabled, the row/column resize handlers are placed incorrectly. (I haven't checked if there are other issues yet).

For example, see: http://jsfiddle.net/ftnhd8jv/2/

This is probably due to: http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue

**Comment by AMBudnik** [comment]
Thank you very much for that report.

**Comment by alexyaseen** [comment]
Has anyone successfully found a workaround for this? I'm having the same issue when applying a `transform: scale` to a parent element.

**Comment by AMBudnik** [comment]
Confirmed with 0 24.1, updated demo:http://jsfiddle.net/ftnhd8jv/4/

**Comment by AMBudnik** [comment]
Still present in 0.30.1

**Comment by AMBudnik** [comment]
The issue is still replicable in v `2.0.0` and doesn't seem to work on any of previous versions.

![image](https://user-images.githubusercontent.com/10757813/38807863-53cee6fc-417e-11e8-8da4-028319b1959e.png)

**Comment by wojciechczerniak** [comment]
Housekeeping. We have few issues related to this one. I'm closing this one as a duplicate of #5050. Please track #5050 for further development.

**Comment by AMBudnik** [comment]
Hey @remko 

we've just published Handsontable v `7.0.0` were we fix a referred issue https://github.com/handsontable/handsontable/issues/5050
Please update and let me know if it works for you.
