### ISSUE TITLE
Changing the functionality of autocomplete cell type column

### ISSUE THREAD

**Issue by vshimpi** [handsontable/handsontable#2341]
Hi,
I have requirement of changing the default autocomplete cell type column functionality to the typeahead + dropdown same as that of selectize available in github. The requirement is as follows  -
1. Remove case sensitive validation on the auto complete options. For eg, The value in auto complete options id "USD" and user enters usd, it is throwing validation error after moving out from the selection.
2. On click of auto complete arrow for opening the options, should list down all the items present in the auto complete. Currently, we need to delete the selected value to see the list of the options available.
3. Increase the width of the auto complete options fly out displaying after clicking auto complete down arrow.
Please let me know if we can achieve the above requirements. If so, let me know the solution.

**Comment by AMBudnik** [comment]
Hi, about 3 point please track changes to https://github.com/handsontable/handsontable/issues/1255 issue. 

About point 1 and 2 we will take your advices into considerations, so really thank you for support.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by nitinrajan35** [comment]
Is there a way ( as mentioned by vshimpi  in Point 1) whether we can allow the user to paste the value on a dropdown column without case sensitivity validation? If so, an example would be great.

Thanks in Advance

**Comment by AMBudnik** [comment]
Hi @nitinrajan35 

You can create your own custom validator that will accept whatever you want. Here is an example of custom validators https://handsontable.com/docs/6.2.2/demo-data-validation.html
