### ISSUE TITLE
propToCol not working

### ISSUE THREAD

**Issue by erzamora** [handsontable/handsontable#2344]
As the title states, when I try to get the index value of a column using propToCol, it returns the column name.

See here http://jsfiddle.net/gb9hodb7/

**Comment by budnix** [comment]
I think that `propToCol` method only works (as expected) when you use data sources as array of objects. Like in your updated demo http://jsfiddle.net/gb9hodb7/2/.

**Comment by erzamora** [comment]
Oh I see, I assumed it used the column headers, my mistake. Thank you!
