### ISSUE TITLE
FR: expansion of comments on handsontable

### ISSUE THREAD

**Issue by smartinsightsfromdata** [handsontable/handsontable#2348]
This issue is related to my discussions with @jrowen and his excellent implementation of handsontable as a R htmlwidget.  See here: https://github.com/jrowen/rhandsontable/issues/4
I reproduce my comment with minor changes:

Based on my experience in systems that had the "comment" functionality (typically budgeting systems), this is what I would do:

- provide a method to pre-amble messages with a user name (leaving to the app the responsibility to pick the "right" name).
- a message could have different authors (i.e. same message, different pre-amble)
- messages should be stored somewhere and - at some point available on the server (different options here). Useful to store also cell (e.g. row by col) and row content at the time of the comment.
- what else? At times applications can print all the messages in a certain table (with the reference to the cell and cell content they referred to), but it is an app decision, provided that the bulk of messages are stored.
- To facilitate collaboration it is useful to have ways to save the visible table (with comments) as a pic, so that it can be attached in an email...

Some / most of the above can be done by additional software either on the client or server side.
As pointed out by @jrowen though this would require handsontable.js  supporting comment change events (as well as cell address - not sure it does now?)

**Comment by AMBudnik** [comment]
Thank you @smartinsightsfromdata it's a bunch of great ideas. We have a lot to do with comments to make them work better as a priority, but your ideas surely will help us to build a better grid.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
