### ISSUE TITLE
In nested table after removing rows right margin appears (spotted after 0.14 release)

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#2349]
Issue spotted after Handsontable 0.14 release (refactor overlays).

---
##### Steps to reproduce:
- go to http://handsontable.github.io/hot-table/examples/nested-tables.html
- remove country rows eg:. from last empty row to Denmark
- right margin appears
##### Screenshot:

![overlays](https://cloud.githubusercontent.com/assets/571316/7023689/6a8cb9cc-dd37-11e4-9e1c-33e3045e1e76.gif)

**Comment by AMBudnik** [comment]
@budnix the demo is no longer available via this address

**Comment by AMBudnik** [comment]
We both agreed to close the issue as the demo is no longer available and the project is suspended.
