### ISSUE TITLE
Scrolling is (still) messed up in IE9+

### ISSUE THREAD

**Issue by mburbea** [handsontable/handsontable#2350]
Just go to the scroll demo in IE and mouse wheel down. The Fixed columns can actually get out of sync with the content in the non-fixed scrolling region. (E.g. row B70 next to row C71)
http://handsontable.com/demo/scroll.html

In this demo, the column headers do not flicker which is nice but the rowheaders look awful and out of sync. And take some time to sync up with the content pane. A quick fix is obviously to remove them but they do serve a purpose.
http://handsontable.com/demo/column_resize.html

I lied. Scrolling down does not cause a flicker. Scrolling up does cause a ghosting flicker of the header bar. 
![image](https://cloud.githubusercontent.com/assets/213233/7026088/bc428764-dd15-11e4-9727-06b00292d1d9.png)

**Comment by yuwong** [comment]
Even in Chrome, going to http://handsontable.com/demo/column_resize.html selecting any cell on row 1001(last row), then scroll down with mouse wheel or touch pad, and the row headers will be misaligned with the row.

**Comment by jansiegel** [comment]
@mburbea, thank for reporting this.
We're aware, that scrolling on IE is far from perfect, we're still working on improving the overall performance.

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/2144

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/1272

**Comment by AMBudnik** [comment]
Thanks to everyone that has been working to make Handsontable work better on Internet Explorer. I hope that @mburbea, who has raised the issue some time ago, still uses the library and can agree that it works better in the latest version 0.32.0-beta1, can you confirm that @mburbea ?

**Comment by AMBudnik** [comment]
I am closing this issue as there are no other questions/concerns/related bugs but if someone has any please leave a comment.
The performance is not sharp yet but I hope that we are moving in the right direction.

**Comment by mbgit2015** [comment]
you can use a work around - use two tables instead of one. one table is row header only table and place the table with data below the header only table
