### ISSUE TITLE
This is BUG !??

### ISSUE THREAD

**Issue by c941010623** [handsontable/handsontable#2352]
Uncaught SyntaxError: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.

**Comment by 57even** [comment]
Happens when you enter a cell with autocomplete as cell type.

**Comment by jansiegel** [comment]
@c941010623, @57even can you prepare an example on jsfidlle/codepen, so we can narrow down the issue? Do you experience it on http://handsontable.com/demo/autocomplete.html?

**Comment by 57even** [comment]
@jansiegel yes I do.
![handsontable](https://cloud.githubusercontent.com/assets/4533204/7040683/0afcac2e-ddd2-11e4-9f8c-05b6a018bc4c.PNG)

**Comment by jansiegel** [comment]
You're right, autocomplete was working badly on platforms other than Mac.
We've released a [fixed version 0.14.1](https://github.com/handsontable/handsontable/releases/tag/0.14.1) with a fix concerning this issue.

Thanks!
