### ISSUE TITLE
Dealing with HTML custom headers

### ISSUE THREAD

**Issue by noopole** [handsontable/handsontable#2353]
When I set a custom header cell with HTML select element, selection is only possible from outside the table.

I tried to set preventDefault() et stopPropagation() on the onchange attribute but it doesn't seem to help.

Here is a JSFiddle with the behavior (bug ?) : https://jsfiddle.net/hU6Kz/3338/

**Comment by jansiegel** [comment]
It seems to work fine on Chrome and Firefox on Mac. What browser and OS are you experiencing it on?

**Comment by noopole** [comment]
Issue occurs on IE 11 and Firefox 37 on Windows 7. 
No problem on Chrome (41) for Windows.

**Comment by AMBudnik** [comment]
Checked it on FF 37/Win7 it does not work there if you choose other `<option>` than `A`.

**Comment by AMBudnik** [comment]
Seems to work fine with version 0.24.1, demo: https://jsfiddle.net/hU6Kz/4902/
Can you confirm it @noopole ?

**Comment by noopole** [comment]
No sorry. It's still buggy with IE 11 and Firefox 44 and 45 on Windows 7.

**Comment by AMBudnik** [comment]
Thanks for feedback @noopole and details - I reproduced it.

**Comment by AMBudnik** [comment]
Still replicable.

**Comment by dhunink** [comment]
Also running into the exact same issue. Placing a <select> element in the header works, but it's impossible to change the selected value.
Has there been a work-around proposed for this bug?

**Comment by AMBudnik** [comment]
updated demo (0.35.0) https://jsfiddle.net/handsoncode/tgc2297s/
The issue is still present. Unfortunately, I did not find any possible workaround. It has to do something with the focus though. Maybe playing with the DOM elements focus would help.

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/4759

**Comment by AMBudnik** [comment]
The issue is no longer replicable. We're able to select an option from the header.

![image](https://user-images.githubusercontent.com/10757813/38807801-0d762c6a-417e-11e8-94dc-f677032239ad.png)

Here's an updated example https://jsfiddle.net/2s1s6gq0/
