### ISSUE TITLE
Limit the amount of pasted cells on specific row(s).

### ISSUE THREAD

**Issue by tmacdonald01** [handsontable/handsontable#2355]
Is it possible to limit the amount of columns that can be pasted in a specific row(s)?

While the other rows can have all columns be pasted into if necessary.

In my Handsontable Gridview I have certain rows that if data is entered into a cell in that row, it causes another area to be visible. The new area must be completed before any other process can be attempted.  With the ability to paste multiple cells in this row it is causing major issues with my logic process.

**Comment by AMBudnik** [comment]
Can you please provide a demo with steps description what you want to achieve?

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
