### ISSUE TITLE
Issue 2204 new problems with 0.14.1

### ISSUE THREAD

**Issue by agucabral21** [handsontable/handsontable#2356]
I have made new comments in this issue 2204, do i make a new issue for this problems or you reopen the issue?

https://github.com/handsontable/handsontable/issues/2204

**Comment by AMBudnik** [comment]
Hi, issue #2204 wasn't closed - it's open. If the problem you want to describe is something else than in #2204 feel free to write it here. Please tell me what changes did 0.14.1 made for your code.
