### ISSUE TITLE
Remove column issue after Freeze column

### ISSUE THREAD

**Issue by yuwong** [handsontable/handsontable#2358]
1. go to http://handsontable.com/demo/column_freeze.html
2. right-click and freeze column with header E (with values E1, E2, etc)
3. right-click and delete column with header E (with values D1, D2, etc)
4. notice now the E1, E2 column is removed and replaced by the F1, F2 column

**Comment by AMBudnik** [comment]
Hm.. can you record what see? When I follow your steps everything works smooth. Data from column E is deleted so all data from column F is now a new Column E data.

**Comment by yuwong** [comment]
![freeze_remove](https://cloud.githubusercontent.com/assets/8896566/7085975/edf2ec30-df73-11e4-805d-405f7ad7b783.gif)

**Comment by AMBudnik** [comment]
Thank you very much, we'll take a closer look at this issue.

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1

**Comment by swistach** [comment]
It works properly from version: 0.28.0
Thank you @yuwong for your help!
