### ISSUE TITLE
manualRowMove option with an array value - data copied not moved

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#2360]
Here's the [demo](https://jsfiddle.net/0go633om/1/) for this issue.

Expected values with an array `[0,6]`:

 | A
------------ | -------------
1 | A1
2 | A7
3 | A2
4 | A3
5 | A4
6 | A5
7 | A6
8 | A8

Case 2) Result: Row 6 was copied into row 2 (not moved), lost data from 2 row
![zrzut ekranu 2015-04-10 o 13 15 21](https://cloud.githubusercontent.com/assets/10757813/7086655/d13811f0-df83-11e4-93fc-36dc64427c45.png)

**Comment by jansiegel** [comment]
Not sure if it's a bug, or a feature design decision - it's been working like this since a long time, see an example with v. 0.12.0: http://jsfiddle.net/m4uqfmnL/

I'll re-label it to `Change` and we'll discuss if we should change it.

**Comment by budnix** [comment]
I think that this is a bug which causes other plugins to disfunction when they're using row transformation. To discuss with team @swistach @krzysztofspilka. 

_Updated demo at http://jsfiddle.net/me9yonjo/._

**Comment by AMBudnik** [comment]
It's surely a bug.. I just found out that ( demo http://jsfiddle.net/5wfgxs0x/)

by adding a `manualRowMove: [3, 1]` we're getting

![first](https://cloud.githubusercontent.com/assets/10757813/15818156/fb803ec4-2bdb-11e6-94cf-2245c3da31f8.png)

then if we would like to delete first cell's content we'll get (<kbd> delete</kbd> / <kbd> backspace </kbd> key) the same result in 4th cell (the same is for editing).

![last](https://cloud.githubusercontent.com/assets/10757813/15818195/38fe5330-2bdc-11e6-87f6-780d8610c9d1.png)

**Comment by swistach** [comment]
This plugin was completely rewritten in v1.7.0. 
Current version works properly.
