### ISSUE TITLE
Selecting the last row in a fixed column causes a scrollbar to appear

### ISSUE THREAD

**Issue by ascendedguard** [handsontable/handsontable#2361]
Version: 0.14.1
Fiddle: http://jsfiddle.net/mam2ea82/1/

In a small table, when you're selecting the last cell in a fixed column, a scrollbar appears. It disappears when editting. Tested in both Chrome and IE11. I only added the following to the default fiddle:

```javascript
    fixedColumnsLeft: 1
```

![image](https://cloud.githubusercontent.com/assets/507305/7089704/cb81f0d6-df6b-11e4-95c7-da5207ba2d84.png)

**Comment by AMBudnik** [comment]
Confirmed. It occurs in every major browser in Windows 7 and OSX Yosemite.

**Comment by jansiegel** [comment]
Should be fixed with #2435 (to be released in the next version)
