### ISSUE TITLE
handsontable with J2EE

### ISSUE THREAD

**Issue by marc237** [handsontable/handsontable#2362]
Hello;
I wanna know how to send data from handsontable to the server , so I can save them in a database (I use J2EE as a platform and mysql as a Database ).
I found that I can send them as JSON , but I don't know how to do that , and how to receive that object and transform them into java object ...
Can you help me please ....

**Comment by AMBudnik** [comment]
Please check our [Load ans save](http://docs.handsontable.com/0.15.0-beta3/tutorial-load-and-save.html) for more information. If it will be less than you expected to solve your issue, please create a topic in [stackoverflow with handsontable tag](https://stackoverflow.com/search?q=handsontable)
