### ISSUE TITLE
When freezed, first column cells don't align with other cells.

### ISSUE THREAD

**Issue by surfncode** [handsontable/handsontable#2363]
![capture d ecran 2015-04-13 a 10 05 29](https://cloud.githubusercontent.com/assets/11091641/7108906/60f7eeba-e1bd-11e4-97bf-98100bdf6cc9.png)
If the first column is freezed and there is not enough rows to activate the scroll bars, the cells of the first column don't align well with the other cells of the table

**Comment by jansiegel** [comment]
Probably connected with #2354.

**Comment by AMBudnik** [comment]
@surfncode please update to 0.16.1 it should work fine, if you would have any issues please create a demo and we'll reopen this issue.

**Comment by surfncode** [comment]
Yes It does indeed, thanks
