### ISSUE TITLE
in version 0.14.1, is it possible to hide second scroll bar on freezed portion ?

### ISSUE THREAD

**Issue by surfncode** [handsontable/handsontable#2364]
If handson table is embedded in a fixed size div, when scrolling vertically, a second scrollbar appears over the first column (which is freezed). 

FYI, I did replace overflow: auto by overflow: hidden on the container, as instructed by the release note.

I understand from the release note that each freezed area has now its own container so this issue may be tricky. 
Is there a way to remove or hide the first scrollbar ?

**Comment by jansiegel** [comment]
Hi, @surfncode,
any additional scrollbars should be hidden by default, could you reproduce this issue on jsfiddle/codepen? Also, what browser and OS are you experiencing it on?

**Comment by surfncode** [comment]
Sure here is the fiddle: http://jsfiddle.net/wq5jjtxb/
It's an exact duplicate of the freeze column demo on handson table.com

My configuration is Mac os 10.8, firefox: 36.0.1
I also have the problem on safari 6.0 

The screenshot is
![double-scrollbar-handsontable](https://cloud.githubusercontent.com/assets/11091641/7111769/81d3a04a-e1ed-11e4-8756-dee412c826ab.png)
 on firefox with the fiddle I included

**Comment by jansiegel** [comment]
You're right, it seems to happen when OSX's scrollbar auto-hiding is enabled. We need to fix this as soon as possible!

**Comment by jansiegel** [comment]
Should be fixed with #2435 (to be released in the next version)
