### ISSUE TITLE
Copy/paste functionality in handsontable.js is not working 

### ISSUE THREAD

**Issue by ajinkyasingh27** [handsontable/handsontable#2365]
I am not able to copy the record in handsontable.js and I am checking by putting break point in after change event in handsontable.js,Here I am not getting the whole row data in changes parameter.Whatever I am able to see in the UI that much column's data I get in changes parameter.

**Comment by jansiegel** [comment]
Could you prepare a demo on jsfiddle and steps to reproduce this problem? It would make it much easier for us to investigate.

**Comment by halfnibble** [comment]
I don't know what this person's exact issue is, but I have a repeatable issue outlined below.

If I copy data from Excel, then right-click > "Paste" into Handsontable, nothing is displayed. However, if I hit Ctrl + V, then the data gets displayed. Once I use Ctrl-V, I am able to use right-click > "Paste" to paste data into Handsontable, but only after I've used Ctrl-V at least once.

**Comment by halfnibble** [comment]
I can replicate this with your website demo here:
http://handsontable.com/demo/contextmenucopypaste.html

**Comment by halfnibble** [comment]
Interestingly, Ctrl-C does not work at all with Handsontable. However, I am able to use right-click > "Copy" to copy data, and then paste it in Excel. 

Google Chrome:
41.0.2272.101 (64-bit)

On LinuxMint13 (64-bit)

**Comment by halfnibble** [comment]
Same exact issues with Firefox version 37.0

**Comment by skosch** [comment]
Same issue with Firefox 38 on Linux :( ... works in Chrome

**Comment by AMBudnik** [comment]
Agree, <kbd>CRTL</kbd> edits cell (on Ubuntu 14, FF 37) so it's impossible to use copy/paste functionality.

**Comment by skosch** [comment]
The solution for this is given in #2089.

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/2179
