### ISSUE TITLE
Issues on handsontable scroll bar,drag/drop and copy/paste

### ISSUE THREAD

**Issue by ajinkyasingh27** [handsontable/handsontable#2366]
Issue:
 1)If I don’t give height to the handsontable,horizontal Scroll bar has not shown and design gets disturbed.It takes scroll bar from browser window. I have 33 column in the table and it display only 25 columns and columns from 26 to 33 are not displayed.

2)If I do drag and drop to the selected row then some column values are not copied in the new row. (These are are dependent on other columns, where drop down in Column B has to be filled baed on the value selected from drop down of Column A).Same case with the copy and paste functionality.I have formats on the cell which are conditional.I have written code for the column like this:

{
 data: "Column7", type: 'numeric', language: 'en',
 renderer: function (instance, td, row, col, prop, value, cellProperties) {
 Handsontable.TextCell.renderer.apply(this, arguments);
                    if (arrCostType[row] == "xyz") {
                        cellProperties.format = '0,0.00';
                        cellProperties.readOnly = false;
                    }
                    else if (typeof arrCostType[row] != "undefined" && typeof value == "undefined") {
                       cellProperties.format = '0,0';
                        cellProperties.readOnly = false;
                        td.innerHTML = '';
                    }
                    else if (typeof arrCostType[row] != "undefined" && typeof value != "undefined") {
                        cellProperties.format = '0,0';
                        cellProperties.readOnly = false;
                        if (value != "" && value != null)
                            td.innerHTML = currencyformat(value);
                    }

                    else if (typeof arrCostType[row] == "undefined" || arrCostType[row] == "" || arrCostType[row] == null) {
                        td.innerHTML = '';
                        cellProperties.readOnly = true;

                    }

                    if (IsCostTypeChanged[row] == true || IsCostTypeChanged[row] == "true") {
                        td.innerHTML = '';
                        arrMonth7[row] = 0;
                        $('#handsOnTable').handsontable('setDataAtCell', row, col, '');
                    }

                },
            },

3)I have cascading dropdown in handsontable but whenever I do drag and drop or copy and paste then I don’t get the value of cascaded dropdown.

**Comment by AMBudnik** [comment]
Hi, for the: 

point 1) I made a little [demo](https://jsfiddle.net/sj5ay5am/) from your description and it shows all the data. Please check it and correct if this is not what you were looking for.

point 2) we would appreciate a demo of your code for this particular situation.

point 3) can you provide a screen.

**Comment by john-r-mcpherson** [comment]
Hi,

for the scroll bars demo (with v0.14.1 and using firefox 37 on linux), I only get the automatic scrollbars if the container's height is set in the html's "style" attribute, or set in javascript via $container.style.height - it doesn't work for me if the height is set via css (with overflow:hidden all the remaining rows never get rendered). Perhaps either document this or change the behaviour so it works with height set via css.

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity.
