### ISSUE TITLE
Dropdown Issue on handsontable js

### ISSUE THREAD

**Issue by ajinkyasingh27** [handsontable/handsontable#2367]
Drop down expansion list is hiding behind the horizontall scroll bar.
![handsontableimage](https://cloud.githubusercontent.com/assets/11055503/7131091/5dc2743c-e298-11e4-8fab-862041de99d6.png)

**Comment by AMBudnik** [comment]
Issue duplicated. Please follow https://github.com/handsontable/handsontable/issues/1954 issue for further information in this subject.
