### ISSUE TITLE
Renderer function of a column is not fired when sorting happens

### ISSUE THREAD

**Issue by ajinkyasingh27** [handsontable/handsontable#2368]
I have 23 column in my grid.so only 10 columns are visible to the user. I am using renderer function in every column to do the calculations. But when I do sorting on first column then renderer function of only 10 or 12 columns gets fired.Renderer function available in rest of the column won't fired due to which I am not able to do calculations.

**Comment by AMBudnik** [comment]
Can you please prepare a [JSFiddle](https://jsfiddle.net/api/post/library/pure/) demo of your code?

**Comment by ajinkyasingh27** [comment]
Hi,I made the demo of my code and go to http://jsfiddle.net/ajinkyasingh27/172jh3c0/3/If you want any information from my side.please let me know. Best regards 
Ajinkyasingh J Bais
(Software Developer)
8928366327,9096986660 


     On Tuesday, April 14, 2015 7:49 PM, Aleksandra Budnik <notifications@github.com> wrote:
   

 Can you please prepare a JSFiddle demo of your code?—

**Comment by krzysztofspilka** [comment]
@ajinkyasingh27 Hi, we are cleaning up our issue board. Can you please confirm that you still struggle with this problem?

**Comment by AMBudnik** [comment]
I'm closing this issue in lack of recent activity but @ajinkyasingh27 if you still experience issues in this matter - please do not hesitate to leave your comment.
