### ISSUE TITLE
Column Header widths not adjusting with data length

### ISSUE THREAD

**Issue by Robin-CT** [handsontable/handsontable#237]
If data at the cell is larger than the minimum width, initialized through colHeaders being specified, the width for the respective th cell in the absolutely postitioned table doesn't adjust to increase as well. This causes a distortion and the column headers and data columns don't align vertically. 

In particular, I'm pasting from excel. 

Is there a way to refresh (redraw) the initialized header after such a paste? and no, there's not many rows to cause a scroll either.

My set up is basically like so: 

var objectData = [{ col1: "", col2: "" ............}];

var container: $("#dataGrid");
container.handsontable({
    data: objectData,
    dataSchema: { col1: null, col2: null, .................},
    startRows: 5,
    startCols: 35,
    colHeaders: ['Column1', 'Column2', ................],
    minSpareCols: 0,
    minSpareRows: 1,
    rowHeaders: true,
    fillHandle: true
});

**Comment by uideveloper2015** [comment]
![issue](https://user-images.githubusercontent.com/43671056/50537559-1017da80-0b87-11e9-8bd7-aba431df715c.png)
how to solve fast pls

**Comment by AMBudnik** [comment]
Hey @uideveloper2015 

Can you share a demo where this issue can be replicable? This topic has a couple of years and since it's first post a lot of code has been changed.
