### ISSUE TITLE
Paste date from excel (in any format)

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2370]
I'm a bit lost in this regard. 
What would be the best way to paste a date (in any possible format provided by excel) into a date type of cell?

Although internally excel works with UTC, it seems that when copying and pasting the UTC value is not the one which gets transmitted.

**Comment by AMBudnik** [comment]
Hi @alvarotrigo you would like to paste data with a file? When I use a Google Docs + HOT it works fine with <kbd>ctrl</kbd> + </kbd>c</kbd> / <kbd>ctrl</kbd> + </kbd>v</kbd> like coping:

![zrzut ekranu 2015-04-20 o 14 06 14](https://cloud.githubusercontent.com/assets/10757813/7229681/d86f1f8c-e766-11e4-807f-f87539d7d8a4.png)

gives me

![zrzut ekranu 2015-04-20 o 14 10 18](https://cloud.githubusercontent.com/assets/10757813/7229708/0ffe265a-e767-11e4-8530-fd5f4ea95094.png)

**Comment by alvarotrigo** [comment]
I found a solution by using [datejs](https://github.com/abritinthebay/datejs) which parse any kind of string to date format.
