### ISSUE TITLE
`setDataAtCell` when cell is active in edit mode

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2372]
I'm trying to use the method `setDataAtCell` when I'm editing the cell, but it doesn't seem to work.

There's nothing naming this in the docs. But it seems there is a restriction there. 
Is there any way to change the value of a cell the user is editing? 

I'm trying to change the content of the cell when the user double clicks on a cell, but it seems impossible.

**Comment by alvarotrigo** [comment]
I managed to do some ugly fix, by using 
```javascript
$('.handsontableInput').val(myNewValue);`
```

But not sure about the implications of it...

**Comment by AMBudnik** [comment]
Hi,

Theoritically it should be done by creating a custom editor https://docs.handsontable.com/pro/1.3.4/tutorial-cell-editor.html but as I was never trying to perform an action as described it's hard to tell if it would be better than your workaround. 

ps. are you still using it?
