### ISSUE TITLE
Numeric type for a time without seconds?

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2374]
As mentioned in the docs, handsontable makes use of Numeral.js for the formating option of the numeric type of columns. 

I was wondering if I can specify a time format with no secons, like `09:30` but I couldn't find it int he [numeral.js docs](http://numeraljs.com/).

Then I went to their github account to ask a question but I found out there are tends of opened issues and pull requests without answer and it seems [the project is dead](https://github.com/adamwdraper/Numeral-js/issues/242) and no longer maintained.

This makes me wonder if there's any alternative to achieve what I'm looking for and also how handsontable will handle the format option in a future, as making use of a dead library is not a great approach to it.

**Comment by uniphil** [comment]
Not sure about time formatting, but there is now an [actively maintained](https://github.com/foretagsplatsen/numbro/commits/develop) (fork of numeral-js)[https://github.com/foretagsplatsen/numbro] that might be worth considering.
