### ISSUE TITLE
Zero based indexes vs 1 based indexes for columns

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2375]
I've noticed when using the method `getCell` the column have to be a zero based index.

Contrary to that, when using an event like `beforeChange`, the changes return and array which contain columns in a one based index.

This should be specified in the docs as might be quite confusing. 

I noticed the parameters are not very well documented usually, but things like this that can easily lead to mistakes should be at least clarified.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
