### ISSUE TITLE
setInvalidCell method?

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2376]
I would like to set a cell to invalid but I found no method to do so.
Searching a bit I found [what seems to be a valid solution for the issue](http://stackoverflow.com/questions/24595389/handsontable-how-to-set-cell-to-invalid-manually) but it implies rendering the whole table again. (with the performance penaly it implies)

I think providing a method to manually set a cell to invalid would be quite useful.

**Comment by AMBudnik** [comment]
Thank you for a suggestion.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
