### ISSUE TITLE
Specify meta data in documentation

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2377]
I can see the methods `getCellMeta` and `setCellMeta`, but there's nowhere in the documentation where the `meta` array is specified or explained.

Not even the possible values for the `key` parameter are specified in the `setCellMeta` docs. Is it some kind of mysterious secret?

[I've just discovered a way (not sure if its the proper one) to set a cell to invalid state](http://stackoverflow.com/questions/24595389/handsontable-how-to-set-cell-to-invalid-manually) but I found no reference to it in the docs and I couldn't guess it from the returned object from `getCellMeta`.

**Comment by AMBudnik** [comment]
Thank you @alvarotrigo for your support. We'll see what we can do.

**Comment by wojciechczerniak** [comment]
Moved to https://github.com/handsontable/docs/issues/9
