### ISSUE TITLE
Allow all pikaday options

### ISSUE THREAD

**Issue by TheLudd** [handsontable/handsontable#2378]
It would be great if it was possible to specify all [pikaday options](https://github.com/dbushell/Pikaday#configuration) that are available   when creating a date cell. Right now it seems like the options are [defined statically] (https://github.com/handsontable/handsontable/blob/master/src/editors/dateEditor.js#L41), correct? Only date format and container seems to be configurable.

**Comment by AMBudnik** [comment]
I agree, it would be great. We'll see what we can do.

**Comment by TheLudd** [comment]
I could perhaps supply a PR for this if that helps

**Comment by AMBudnik** [comment]
Sure, if you have an idea and some time - we're open for all PR, especially those which pass our tests :-)

**Comment by TheLudd** [comment]
How would the preferred way of specifying options be? I could imagine something like this:
```
    {
      type: 'date',
      correctFormat: true,
      options: {
        firstDay: 1,
        ...
      }
    },
```
There is a problem however since some options are already available at the "top level" such as date format. Should that be moved to the options element? Or should all options be on the top element?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Feature completed. More at https://github.com/handsontable/handsontable/issues/2378

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
