### ISSUE TITLE
Copy+paste not working with Safari

### ISSUE THREAD

**Issue by constantinotts** [handsontable/handsontable#2381]
It seems the copy event is never triggered, it is NOT possible to copy:
* one cell to another
* cells from a spreadsheet into the table
* content from the table to an external file

**Comment by AMBudnik** [comment]
You're right the <kbd>ctrl</kbd> + <kbd>C</kbd> does not trigger copying everytime. For more information in this subject please follow https://github.com/handsontable/handsontable/issues/2220
