### ISSUE TITLE
render method removes applied classes

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2382]
The documentation for the method `render` doesn't really explain much about what this method really does.

> **render ()**
> Rerender the table

I'm applying some classes over cells or even over rows and I'm finding out that after rendering the table again calling the `render` methods, those classes disappear. 

To reproduce it, edit any cell in the table (which will call the render function) and you'll see how the class disappears. 
[Reproduction of the problem](http://jsfiddle.net/fws1vc5e/17/)

This is a pretty basic example reproducing the problem. I'm not adding classes on table load, but after calling a restful API and getting some data which determines the color of the cell.

**Comment by AMBudnik** [comment]
Hi @alvarotrigo thank you for your suggestion.

**Comment by armensg** [comment]
Is there a way I can prevent this from happening? calling my afterRender callback is is extra compuational effort that I dont want to do every time data in my table changes (alot)

**Comment by AMBudnik** [comment]
Hi @armensg you mean the disappearance of classes?
Can you send me a Fiddle demo at support@handsontable.com? I'll check if something can be done.

**Comment by armensg** [comment]
hi @AMBudnik I got around this problem actually this morning by dynamically injecting css into the stylesheet as opposed applying styles with jquery (which seemed to disapear after render() was called)

**Comment by armensg** [comment]
Note that this is not ideal though

**Comment by swistach** [comment]
If you wanna add additional CSS classes, you have to do it by `setCellMeta` for `className` key. Ex.: http://jsfiddle.net/1n4z2tre/
In result of `render()` call, each cell which was created before, is render again by own renderer. That means, any changes in DOM, which are not from the Handsontable, are not rendered after re-render.
