### ISSUE TITLE
Conflict between editor and source?

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2384]
I'm trying [to use a custom `editor` for all my columns](http://stackoverflow.com/a/29708345/1081396) and I noticed the `autocomplete` column with the `source` attribute stop working when using the `editor` on it.

[Reproduction of the problem](http://jsfiddle.net/fws1vc5e/20/) (1st column)

This will crash the autocomplete
```javascript
{       data: 1,
        type: 'autocomplete',
        strict: true,
        editor: LoggingEditor,  //Editor DEFINED HERE
        source: function (query, process) {
            response = JSON.parse($('#start_array').val());
            process(response);
 },
```

This will work as expected:
```javascript
{       data: 1,
        type: 'autocomplete',
        strict: true,
        source: function (query, process) {
            response = JSON.parse($('#start_array').val());
            process(response);
 },
```

**Comment by jansiegel** [comment]
@alvarotrigo, in your jsfiddle you're extending the TextEditor class. Maybe extending the AutocompleteEditor would be enough to fix this problem? 
http://jsfiddle.net/fws1vc5e/42/
