### ISSUE TITLE
hot doesn't scroll horizontally when using the right arrow key to move the selected cell out of the right border

### ISSUE THREAD

**Issue by ln613** [handsontable/handsontable#2385]
1. set a width for the hot to create the horizontal scroll bar, make sure the total width of all columns are bigger than the hot div, so that some columns are out of sight and you need to scroll horizontally to see them

2. select a cell (do not go into edit mode)

3. keep pressing the right arrow key until the selected cell goes out of the right border of the hot div

expected result: the hot div should be scrolled to the right automatically so that we can see the currently selected cell

actual result: the hot div does scroll and we can not see the selected cell

**Comment by AMBudnik** [comment]
Hi, I tried it on Chrome 4, FF 37 and Safari 8 on mac and the cell in visible all the time as expected. Please check this [demo](https://jsfiddle.net/144Ldfas/) and provide your OS/Browser info if it doesn't work on your machine.

**Comment by ln613** [comment]
Thanks. I think I found the problem. I wrapped the hot div in another outer div which has a fixed width, but the hot div itself doesn't have a fixed width. So it's not a handsontable issue
