### ISSUE TITLE
afterSelectionEnd deselects another Grids Selection

### ISSUE THREAD

**Issue by cg3** [handsontable/handsontable#2386]
I use two Grids to edit the columns of one grid on the fly. For convenience reasons the users should click on the row / column to jump in both grids to the desired place. While beforeColumnSort works as expected, the same code fails with afterSelectionEnd.

Demo: http://jsfiddle.net/mohk/6btp38hn/

**Comment by cg3** [comment]
In which form is 'Assistance needed'? Should I clearify things?

**Comment by cg3** [comment]
To nail things a bit I traced the code to see which line deselects the manual selection:
```
Line 4657:
   if (event.target == void 0 && event.srcElement != void 0)
```
Here are the values in question
```
event = [mousemove,clientX=222, clientY=596]
event.target = html
event.srcElement is undefined
```

**Comment by AMBudnik** [comment]
Thanks for details, well see what we can do in this case.

**Comment by AMBudnik** [comment]
Seems to work fine with the latest 0.24.1 version. Could you check it please?

**Comment by cg3** [comment]
I am sorry, but I couldn't wait a year for this fix, so I switched to a commercial product.

If the bug is fixed, you can close the issue.
