### ISSUE TITLE
ENTER key doesn't move the selection down on read-only cells

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2387]
Hitting the `ENTER` key doesn't move the selection down, when applied to `readOnly` cells.

---------------------
##### Steps to reproduce:
1) Go to http://handsontable.com/demo/readonly.html
2) Select any `read-only` cell
3) Press the `ENTER` key

**Result:** Nothing happens
**Expected result:** Selection moves to the cell below

**Comment by krzysztofspilka** [comment]
Tested, bug found - double click triggers moving the selection to the cell below.
