### ISSUE TITLE
Horizontal scrolling resets row heights, when using fixed columns

### ISSUE THREAD

**Issue by pw123** [handsontable/handsontable#2388]
Steps to reproduce:
1) Go to http://handsontable.com/demo/fixed.html
2) Enter a multi-line value in a cell of an fixed colum, example: double-click on cell B4, enter an two-line text using ALT+RETURN
(after this step, height of row 4 is correctly adapted to heigth of two lines for all visible colums)
3) scroll horizontally to last colum

Result: During step 3, height of line 4 is reset to heigth of one line text for non fixed columns
Expected result: Height of rows for non fixed columns stays in sync to rows of fixed columns regardless of horizontal Scrolling state

**Comment by AMBudnik** [comment]
Hi, thanks for report. There's an https://github.com/handsontable/handsontable/issues/493 issue for that situation. Please follow it for more information.
