### ISSUE TITLE
combining features for real world usage - editing cells after column move causes error

### ISSUE THREAD

**Issue by hohwille** [handsontable/handsontable#2389]
Thanks for creating handsontable as it is quite cool.
I created a little showcase for a combination of features with multiple-selection via checkboxes that I was missing as a feature:
http://rawgit.com/hohwille/30c3d427d987ef48b962/raw/434ef520c51d42596dc66a76a9420138933dcd68/gistfile1.html

Now, when I first move the year column to the left and then edit it, the editor stalls and remains fixed at is position. This seems to be a bug in handsontable.

BTW: It would be lovely if you could provide multi-selection out of the box (maybe even without touching the actual data objects but keeping the selection state per row internal and offering a getSelectedRows method). I would also like to prevent the column with the selection checkboxes from resizing and moving. I currently do not see how this would be possible so actually move and resize should be a feature per column.

**Comment by hohwille** [comment]
![handsontable-bug](https://cloud.githubusercontent.com/assets/1923119/7255189/fc2fe834-e847-11e4-9c0b-678e82294b17.png)

**Comment by hohwille** [comment]
As you can see in the screenshot after the error ocurred the editor field (with 2008) remains fixed at its place and never goes away.

**Comment by hohwille** [comment]
BTW: Multiselection should IMHO actually modify the class attribute of the row (TR) to add and remove ```selected```. Then The user could actually define the highlighting color via CSS in a flexible way.

I created a new demo here:
rawgit.com/hohwille/4bfcc797a74f067aaa60/raw/e70b8486783c8be043bef69cef64d800ef336c98/gistfile1.html

However then the lazy rendering of columns is causing bugs so when you scroll down after doing "select all" via header then lazy rendered rows are missing the selection class and therefore rendered not as selected.

**Comment by AMBudnik** [comment]
Can you please provide a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/) for the second post (with a cell displacement)?

**Comment by hohwille** [comment]
Its nothing but a plain single HTML file with external resources.
I converted to JSFiddle but IMHO JSFiddle is currently broken.
https://jsfiddle.net/u8dxq75f/
I might have done something wrong, but also JSFiddle demos from other guys currently do not work for me.

**Comment by hohwille** [comment]
Even your own JSFiddles do not work:
https://jsfiddle.net/5yp3zogd/

**Comment by AMBudnik** [comment]
OK, I see in on one of our [demos](http://handsontable.com/demo/numeric.html) when 'year' column is pushed to to left it content and any other cells also can be changed if 'year' column's row is the first one that'll be edited.

**Comment by AMBudnik** [comment]
does not occur after the [demo](http://jsfiddle.net/7vLh1x7b/) got updated to 0.18.0
