### ISSUE TITLE
Handsontable - Wrong coords of the top-left corner header

### ISSUE THREAD

**Issue by vkum** [handsontable/handsontable#2391]
It's not possible to "select all" the entire Handsontable by clicking on the top-left corner header.

By using the afterOnCellMouseDown event as plugin hook:
var exampleContainer = document.getElementById('example');
var hot = new Handsontable(exampleContainer, {});
hot.addHook('afterOnCellMouseDown', function(event, coords, TD) {
	// Select all
});

coords are 0, 0 instead of -1, -1
(not possible to differentiate the top-left corner header from the first column/row cell which has the same coords 0, 0)

In an other issue (https://github.com/handsontable/handsontable/issues/951), warpech wrote:
"Currently, when you click on a column/row header, afterOnCellMouseDown plugin hook is triggered with negative index.
For example clicking on the row header of cell 0, 0 results with afterOnCellMouseDown called with coords 0, -1."

With version 0.14.1 (also checked with 0.13.0)

Thanks in advance

**Comment by AMBudnik** [comment]
Let me note this as a feature to let 'select all' by top-left corner.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by sonmunehiro** [comment]
When will it be implemented?

**Comment by AMBudnik** [comment]
Hi @sonmunehiro 

we do not have it in plans for January but I think that it is possible to do it with a workaround. You can try the [`afterOnCellMouseDown`](https://docs.handsontable.com/0.35.0/Hooks.html#event:afterOnCellMouseDown)

**Comment by sonmunehiro** [comment]
Hi @AMBudnik 

`afterOnCellMouseDown` returns `0, 0` instead of `-1, -1` when I click top-left corner header,
so I can not implement.

**Comment by AMBudnik** [comment]
That is the only element that has not been properly coordinated by this hook and this is the original feature request. Sorry, I forgot about that

**Comment by sonmunehiro** [comment]
Hi @AMBudnik 

Thank you for your reply! Is it hard to implement? :)

**Comment by AMBudnik** [comment]
It shouldn't but we are still preparing to change the layer structure so whatever we do know will have to be changed in the future.

**Comment by AMBudnik** [comment]
Hi @vkum @sonmunehiro

I’m glad to announce that Handsontable v8.0.0 that solves this issue is live!   

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback.
