### ISSUE TITLE
Question about behaviour on inserting/removing a row

### ISSUE THREAD

**Issue by xiad11** [handsontable/handsontable#2393]
Hi, thank you for creating this useful plugin.

I have a question about about inserting/removing rows function. Just created a simple demo:
http://jsfiddle.net/cpoud6te/3/

What I wanna do is to change background color on "afterChange" event and it is achieved.
My concern is the difference with position of colored cell on inserting a row against the case removing.
For example to reproduce;
  1. Change value on cell B4 into "300" or sometihng --> cell B4 turns yellow.
  2. Remove row 2 with context menu --> colored cell with updated value "300" moves to B3 as expected.
  3. Insert row under row 1 with context menu --> colored cell stays at B3 with value "20".

Is this behavior current spec with any restriction?
My expectation is colored cell moves down on inserting rows and is it realized with some additional codes?

Best Regards,

**Comment by AMBudnik** [comment]
Hi, thanks for reporting, I guess it can be related to https://github.com/handsontable/handsontable/issues/1715 but let us take a closer look.

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/1715, if any updates they'll be added to https://github.com/handsontable/handsontable/issues/1715
