### ISSUE TITLE
Cell background color is reset in edit mode

### ISSUE THREAD

**Issue by Subramanayamnvr** [handsontable/handsontable#2397]
I am changing the invalid cells background colors on "validate" button click and i am getting the "TD" value and setting the background color value .But when I edit another cell  the background color of  previous cell , it disappears or reverts back to the original state. 

Is there any property or event I need to check for?

Note: I cannot use renderer function as there are many ajax calls involved and data is dynamically generated.

**Comment by AMBudnik** [comment]
Please prepare a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/) and we'll see what we can do.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
