### ISSUE TITLE
Mouse Wheel scrolling in headers not working in IE11

### ISSUE THREAD

**Issue by HandsTest** [handsontable/handsontable#2398]
Open the Scroll demo page in IE11, move mouse over the header or fixed rows and try to scroll the page using mousewheel. Nothing happens.

**Comment by jansiegel** [comment]
@HandsTest You're right, the above commit should make it work in IE.

Thanks for reporting!

**Comment by krzysztofspilka** [comment]
Problem spotted and reported in #2422
