### ISSUE TITLE
Handsontable.renderers.registerRenderer runs twice when fixedColumnsLeft is used

### ISSUE THREAD

**Issue by glmonroe2001** [handsontable/handsontable#2399]
In the below code, when the fixedColumnsLeft is configured, then the validateNPI function will run twice for the first column. The other columns are unaffected.
			j$=jQuery.noConflict();
			
			var ErrorMsg = '';
			
			var runValidateNPI = false;
			var runValidateName = false;
			var runValidateColumnCount = false;

			var NPIData = {!npisJSON}, container, hot1;

			// maps function to lookup string
			Handsontable.renderers.registerRenderer('validateNPI', validateNPI);

			// maps function to lookup string
			Handsontable.renderers.registerRenderer('validateName', validateName);

			// maps function to lookup string
			Handsontable.renderers.registerRenderer('validateColumnCount', validateColumnCount);

			container = document.getElementById('dataTable');

			hot1 = new Handsontable(container, {
	    		data: NPIData,
	    		colHeaders: ['NPI', 'First Name', 'Last Name'],
	    		rowHeaders: true,
	    		contextMenu: true,
	    		columns: [
	    			{data: 'NPI__c'},
	    			{data: 'First_Name__c'},
	    			{data: 'Last_Name__c'}
	    		],
	    		minspareRows: 1,
	    		//////////////////////////////////////////////
	    		//////////////////////////////////////////////
	    		//////////////////////////////////////////////
	    		// If the fixedColumnsLeft line is uncommented, then the Handsontable.renderers.registerRenderer('validateNPI', validateNPI) function runs twice
	    		//////////////////////////////////////////////
	    		//////////////////////////////////////////////
	    		//////////////////////////////////////////////
				//fixedColumnsLeft: 1,
				contextMenu: true,
				manualColumnMove: true,
				manualRowMove: true,
				minSpareRows: 1,
				colWidths: [100, 800, 800],
				columnSorting: true,
				cells: function (row, col, prop)
				{
					var cellProperties = {};

					if (col == 0)
					{
						cellProperties.renderer = "validateNPI";
					}

					if (col == 1 || col == 2)
					{
						cellProperties.renderer = "validateName";
					}

					if (col >= 3)
					{
						cellProperties.rendered = "validateColumnCount";
					}

					return cellProperties;
				}
	  		});
	  		function saveNPI()
	  		{
	  			var myJsonString = JSON.stringify(NPIData);
	  		}

	  		function returnJSON()
	  		{
	  			var myJsonString = JSON.stringify(NPIData);
	  			return myJsonString;
	  		}

			function setJson()
			{
    			jQuery('[id$=myHiddenJsonField]').val(returnJSON());
    			//passJsonToController();
    			NPIData = JsonParam
			}

			//function validateNPI()
			function validateNPI(instance, td, row, col, prop, value, cellProperties)
			{
				//if (value != null && !runValidateNPI)
				if (value != null)
				{
					Handsontable.renderers.TextRenderer.apply(this, arguments);
	
					//var NPI = document.getElementById('{!$Component.NPIForm.NPIBlock.NPIField}');
					var NPI = value;
					//alert("NPI is " + NPI);
					var sAnticipatedNPI = '';
			        if(NPI.length !=10)
			        {
			        	//var d = new Date();
			            ErrorMsg += 'In Row ' + (row + 1) + ': NPI must be ten digits!!!<br/>';
			            //return false;
			            td.style.background = 'red';
			            td.style.color = 'white';
			        }
			
				}
				//alert("In NPI " + ErrorMsg);
				//runValidateNPI = true;
			}

			function validateName(instance, td, row, col, prop, value, cellProperties)
			{
				//if (value != null && !runValidateName)
				if (value != null)
				{
					Handsontable.renderers.TextRenderer.apply(this, arguments);
	
					var Name = value;

			        if(Name.length > 80)
			        {
			        	//var d = new Date();
			            ErrorMsg += 'In Row ' + (row + 1) + ': Name must be less than 80 digits!!!<br/>';
			            //return false;
			            td.style.background = 'red';
			            td.style.color = 'white';
			        }

				}
				
				//alert("In name " + ErrorMsg);
				//runValidateName = true;
			}

			function validateColumnCount(instance, td, row, col, prop, value, cellProperties)
			{
				//if (value != null  && !runValidateColumnCount)
				if (value != null)
				{
					Handsontable.renderers.TextRenderer.apply(this, arguments);
	
					var Name = value;

			        if(Name >= 3)
			        {
			        	//var d = new Date();
			            ErrorMsg += 'In Row ' + (row + 1) + ': Too many columns<br/>';
			            //return false;
			            td.style.background = 'red';
			            td.style.color = 'white';
			        }
				}
				
				//alert("In name " + ErrorMsg);
				//runValidateColumnCount = true;
			}

**Comment by AMBudnik** [comment]
Thanks, we'll take a closer look on this one.

**Comment by AMBudnik** [comment]
Hi @glmonroe2001 there was many changes since this idea. Could you create a pull request for this one?

**Comment by AMBudnik** [comment]
I assume that you could solve or abandon presented structure. I'm closing this issue but feel free to leave a comment if there's anything we should know about.
