### ISSUE TITLE
Scrolling with arrow keys not working

### ISSUE THREAD

**Issue by felixhagspiel** [handsontable/handsontable#2400]
I have a problem, on the latest version (14.1) the viewport is not scrolled to the current selected cell when navigating with arrow keys. I believe there is something wrong with the [`Handsontable.Dom.getScrollableElement`](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js#L4225) function. It always returns the window object, even when there is `overflow: scroll` set on the container. When I put `return el.parentNode.parentNode` [here](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js#L4233) at least the horizontal scrolling works. On which element exactly do I have to apply the overflow, width & height styles? It cannot be on the main container because in that case the function would always return the Window Object, or am I wrong? I havent found a clear answer to that yet. Also, is it enough to pass width & height as option via Javascript when creating the table rather than applying overflow, height & width via CSS?

**Comment by AMBudnik** [comment]
Hi @felixhagspiel please check this [demo](https://jsfiddle.net/pfyns2zr/) and write me back does this issue occur on this piece of code?

**Comment by felixhagspiel** [comment]
@AMBudnik thanks for fast reply, it works in this example

**Comment by AMBudnik** [comment]
Please provide a demo of your code, we'll see what we can do.

**Comment by felixhagspiel** [comment]
okay, could you please post your mailadress so I can send you the credentials?

**Comment by felixhagspiel** [comment]
@AMBudnik or you can send me an email to infoATfelixhagspielDOTde

**Comment by AMBudnik** [comment]
Hi @felixhagspiel you can email us at hello@handsontable.com

**Comment by felixhagspiel** [comment]
@AMBudnik alright, I have sent you a mail with credentials and instructions on how to use the demo site. thanks in advance!

**Comment by krzysztofspilka** [comment]
Hi @felixhagspiel, I've received you email, thanks for reaching out to us with this issue. Try to update your hot to the newest 0.15.0-beta2 version, then apply `overflow: hidden` to the div with 'handsontable' class. And for the sake of that test remove all the settings first to check whether your customization doesn't break anything. You can restore them later if you hot starts scrolling properly.

**Comment by felixhagspiel** [comment]
@krzysztofspilka thanks for your reply. I updated to the beta version and removed all my custom CSS and options. I tried setting the width & height params via CSS as well via JS, no success. When I set the width & height via the JS options, arrow movement does not work and the console shows me the following error: `handsontable.js:3277 Uncaught Error: Security brake: Too much TRs. Please define height for your table, which will enforce scrollbars.`. If I set width, height & overflow via CSS to the  ` .handsontable` container the scrollbars show up & the error in console disappears, but arrow-movement does not work as well. Also, only the first few rows are rendered, see here: http://screencast.com/t/KQDeql3Px (I think that is another problem, I fixed that before by setting  `renderAllRows: true `)

**Comment by AMBudnik** [comment]
Hi @felixhagspiel if you still face the same issue with the newest version (0.19.0) please create a demo (with for example [JSFiddle](http://jsfiddle.net/api/post/library/pure/)) and paste if here (in case anyone else has the same case). Thanks.
