### ISSUE TITLE
Decreased performance in newer releases

### ISSUE THREAD

**Issue by kevin-j-morse** [handsontable/handsontable#2404]
I've been using this project since version 0.9 and recently my customers have been complaining to me that the handsontable part of my application has been getting slower over time.

I didn't believe them until I loaded up a year old version of the library (10.4) and definitely felt that it was more responsive.

Is there any sort of performance testing that is being done with each new version? Comparing the two side by side by scrolling up and down with a large dataset I can definitely notice how much slower the new versions are.

Is anyone else experiencing the same thing? Are there new configuration options that should be used for better performance?

**Comment by jansiegel** [comment]
Hi @kevin-j-morse,
We're currently working on reliable measuring and improving performance of Handsontable. We hope to make some progress soon, so stay tuned!

**Comment by krzysztofspilka** [comment]
Performance has been improved a bit. The difference between script execution times to be checked out here: http://handsontable.github.io/performance-lab/benchmark/

**Comment by krzysztofspilka** [comment]
Released in https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
