### ISSUE TITLE
afterChange prevents cell drag working

### ISSUE THREAD

**Issue by simonjcarr** [handsontable/handsontable#2405]
After implementing the afterChange function the ability to drag values by using the handle in the bottom right corner no longer works. However, if I only define the function but add no code to it, the cell drag does work, as soon as I add code it does not work.
When I say does not work, I mean the handle still shows in the bottom right hand corner but it no longer functions. Cells can only be changed manually one at a time.

******Cell Drag works with this*******
```javascript
        afterChange: function (change, source) {
           //row = change[0][0];
       
           //var rowData = this.getDataAtCell(row,0);
           //alert(rowData);
        }
```
************Cell Drag Does not work with this************
```javascript
        afterChange: function (change, source) {
           row = change[0][0];
       
           var rowData = this.getDataAtCell(row,0);
           alert(rowData);
         }
```

**Comment by AMBudnik** [comment]
Hi @simonjcarr  `afterChange` should be used as an event, please try my [demo](https://jsfiddle.net/7cvddeLd/) - it does not block the handle.

**Comment by jansiegel** [comment]
@simonjcarr, your problem is caused by `afterChange` event triggering after the HOT initialization. At that time the `change` argument is empty (it equals `null` to be precise).
If you check the `source` parameter first, it should work fine.

Try this:
```javascript
      afterChange: function (change, source) {
          if(source === 'loadData') {
              return;
          }
          
          row = change[0][0];
          
          var rowData = this.getDataAtCell(row,0);
          alert(rowData);
      }
```

**Comment by simonjcarr** [comment]
Thankyou, works perfect.
