### ISSUE TITLE
Why subtract one pixel when calculating oversized row heights?

### ISSUE THREAD

**Issue by bengladwell** [handsontable/handsontable#2407]
https://github.com/handsontable/handsontable/blob/efdbe7536b8c10695e3946d4e628a9169bf1fc44/src/3rdparty/walkontable/src/tableRenderer.js#L172

Oversized row height is calculated by taking the TR's clientHeight and subtracting 1 pixel.

Those oversized row heights (each lacking one pixel) are used in calculating the wtHider height.
https://github.com/handsontable/handsontable/blob/efdbe7536b8c10695e3946d4e628a9169bf1fc44/src/3rdparty/walkontable/src/walkontableTopOverlay.js#L83

* why is one pixel subtracted from the clientHeight of the TRs?
* this seems to work fine, except in cases where the TR contains a TD with a newline in it. Each TR like that contributes to the wtHider being too short.
* should there be a way to disable vertical scrolling - i.e. not set a height on wtHider or not have wtHider at all? In my particular case, I don't need it.

**Comment by jansiegel** [comment]
Might be related to #2354
