### ISSUE TITLE
Handsontable.Dom.setCaretPosition() throws exception pasting data on "dropdown" column

### ISSUE THREAD

**Issue by pedrofsantoscom** [handsontable/handsontable#2408]
Handsontable.Dom.setCaretPosition() line 4444: "el.setSelectionRange(pos, endPos)" throws an "NS_ERROR_FAILURE" error on Firefox.

**System:**
Firefox 37.0.1
Windows 7 Pro 64bit

**To reproduce:**
1. http://codepen.io/anon/pen/eNYwre
2. Copy a value from a cell of column "C" (ex. "Kia")
3. Select "C" column, to select all cells from that column
4. Paste the value

**Comment by AMBudnik** [comment]
You're right everything's working OK, but console throws an error.

It reproduced it only on FF 37 on Win7 on mac FF 37 there's no errors. Chrome 42 on Win7 and OSX is not affected.

**Comment by budnix** [comment]
setSelectionRange on non-visible elements causes NS_ERROR_FAILURE in Firefox.

**Comment by AMBudnik** [comment]
Does not occur with newer (FF 38) on Win7.
