### ISSUE TITLE
Table not render when data reference is set to empty array and columns/dataScheme not configured

### ISSUE THREAD

**Issue by hippich** [handsontable/handsontable#2410]
Not sure if this is bug or feature, but following example shows issue I have. If this is correct behavior - it is fine with me as I always can initialize data array properly, but I thought it might behave better in this scenario - http://jsfiddle.net/dnnpgk25/2/

You will notice that `data` is empty array, and both `columns` and `dataScheme` not defined. If either `data` is not empty, or at least `columns` or `dataScheme` are defined, everything works as expected.

**Comment by AMBudnik** [comment]
It is right, when the `data` is an empty array you have to provide a schema to 'show' the grid.

**Comment by hippich** [comment]
I would still expect to show empty table with startRows and startCols rows and columns. Was this is something decided to happen on purpose?

**Comment by AMBudnik** [comment]
Currently it has to be at least one empty cells like `[[""]]`, demo: http://jsfiddle.net/g4ftwqkg/1/
