### ISSUE TITLE
renderer settings disappear after LOAD data

### ISSUE THREAD

**Issue by whistsky** [handsontable/handsontable#2412]
I'm trying to combine 2 demos (Load and Save  http://handsontable.com/demo/ajax.html   and Cell Renderers http://handsontable.com/demo/renderers.html).
 But After I Load data from Json, the cell renderers style seems to reset and  no cells will be render.
Should I update setting or render again after Load Data or something?

                var
                  $ = function(id) {
                      return document.getElementById(id);
                  },
                  container = $('example1'),
                  exampleConsole = $('example1console'),
                  autosave = $('autosave'),
                  load = $('load'),
                  save = $('save'),
                  autosaveNotification,
		  yellowRenderer,
                  hot;
		  yellowRenderer = function(instance, td, row, col, prop, value, cellProperties) {
					  Handsontable.renderers.TextRenderer.apply(this, arguments);
					  td.style.backgroundColor = 'yellow';};		
                hot = new Handsontable(container, {
                  startRows: 8,
                  startCols: 6,
                  rowHeaders: true,
                  colHeaders: true,
                  minSpareRows: 1,
                  contextMenu: true,
				   cell: [
    {row: 1, col: 0, renderer: yellowRenderer}
  ],
                 
               

                Handsontable.Dom.addEvent(load, 'click', function() {
                  ajax('json/load.json', 'GET', '', function(res) {
                    var data = JSON.parse(res.response);

                    hot.loadData(data.data);
                    exampleConsole.innerText = 'Data loaded';
                  });
                });

**Comment by AMBudnik** [comment]
For issues that are not related to handsontable bug reports, please create a topic with our [stackover tag](https://stackoverflow.com/questions/tagged/handsontable)
