### ISSUE TITLE
Revert back afterRowMove changes

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#2415]
Is there any way I can revert back the changes done on afterRowMove event.

Actually when the user moves the row to a certain position in the HOT then the row gets moved as expected. Now based on some validation logic I want to revert back that changes and present the grid in its original position.

Is that possible? Thank you.

**Comment by AMBudnik** [comment]
Please check this issue https://github.com/handsontable/handsontable/issues/1904 it can provide helpful information.

**Comment by AMBudnik** [comment]
If you have some questions, feel free to leave a feedback and issue will be reopen.
