### ISSUE TITLE
Get value of row after sorting by column

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2417]
Right now I have a button in each row and once I click it I get the value of the row in this way:

```javascript
$('#editOrders').on('click', '.saveRow, .deleteRow', function () {
	var cellProp = myHandsontable.getSelected();
	var row = cellProp[0];
	var rowData = myHandsontable.getSourceDataAtRow(row);
    
    console.log(rowData);
});
```

The problem is, if the user sorts the column and click over the same button for the same row, then I still getting the same old data instead of the new row data.

How should I deal with it?

**Comment by AMBudnik** [comment]
Hi @alvarotrigo can you please provide a full demo for this example?

**Comment by HandsTest** [comment]
Hi @alvarotrigo ,

You have to use 'getDataAtRow()' method for your purpose.
Example - http://jsfiddle.net/jmng161o/4/

**Comment by alvarotrigo** [comment]
@HandsTest I want to get the source data, not the visible one only...

**Comment by AMBudnik** [comment]
[here's](https://jsfiddle.net/AMBudnik/pb2prxk4/) and example how to get whole row data - if I'm getting the idea.

**Comment by alvarotrigo** [comment]
@AMBudnik @HandsTest you can reproduce what I'm saying [here](http://jsfiddle.net/fws1vc5e/28/)
Notice the hidden data in the last column.

To reproduce it:
- Click on any button and see how you correctly obtain all the data (included the hidden one)
- Click twice over the column header "Two" to sort desc.
- Click in the button at the exact same row as before. And you'll see how you get the old data for that row instead of the current one (after the sort)

**Comment by AMBudnik** [comment]
OK, [here's](https://jsfiddle.net/AMBudnik/fws1vc5e/29/) your example.

**Comment by alvarotrigo** [comment]
@AMBudnik as I said before:

>  I want to get the source data, not the visible one only...

And in my previous post: 

> Notice the hidden data in the last column.


> Click on any button and see how you correctly obtain all the data (**included the hidden one**)

**Comment by AMBudnik** [comment]
Sorry I missed that that one, unfortunately this methods 'works' only on visible data, like described in docs:

`getDataAtRow (row: Number)
Returns a single row of the data (array or object, depending on what you have). row is the visible index of the row.`

**Comment by alvarotrigo** [comment]
Yeah, I know that. So my question is:  isn't there any way to get the source data after a sorting ?

**Comment by AMBudnik** [comment]
After a little investigation I found a solution. Please check this [code](https://jsfiddle.net/AMBudnik/fws1vc5e/38/) I hope this will help, for more information please [read this](https://github.com/handsontable/handsontable/wiki/Understanding-column-sorting-plugin)

**Comment by alvarotrigo** [comment]
@AMBudnik thanks for it! But I couldn't see any reference to the hook `modifyRow` in the documentation link you provided. It seems to be a callback of handsontable. But not quite sure why are you using it in your code or why is it returning the visible data and hidden source data of the row after the sorting.

**Comment by alvarotrigo** [comment]
Ok, I got it working by using the logical and physical indexes as shown in the documentation link you provided:

```javascript
$('#editOrders').on('click', '.saveRow, .deleteRow', function () {
    var cellProp = myHandsontable.getSelected();
    var row = cellProp[0];
    var physicalIndex = row;
    
    if (isSorted(myHandsontable)) {
        physicalIndex = myHandsontable.sortIndex[row][0];
    }

    var rowData = myHandsontable.getSourceDataAtRow(physicalIndex );

    console.log(rowData);
});
```

[Reproduction of the solution](https://jsfiddle.net/fws1vc5e/39/)
