### ISSUE TITLE
Renderer depending on multiple columns

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2418]
I have a renderer that should highlight rows if the value of some of their columns have a specific value.

Therefore I need to check multiple columns before deciding to hightling the whole row or not.

What would be the way to go for it? Right now I was using a renderer in the the `cells `option, but it seems it only work randomly sometimes.

I was doing:

```javascript
cells: function (row, col, prop) {
    if (col == 0) {
        this.renderer = myRenderer;
    }
}
```

And in `myRenderer` I was checking the columns in this way:

```javascript
function myRenderer(instance, td, row, col, prop, value, cellProperties) {
    Handsontable.AutocompleteCell.renderer.apply(this, arguments);
    td.style.fontStyle = 'italic';
    td.title = 'Type to show the list of options';

    //lets check it only once per row (1st column, for example)
    if (col == 0) {
        //eq us zero based (row +1) or .next() needed.
        var currentRow = $('#editOrders.handsontable tr').eq(row).next();

        var type = instance.getDataAtCell(row, 14);
        var status = instance.getDataAtCell(row, 13);
        var eqpType = instance.getDataAtCell(row, 9);
        var line = instance.getDataAtCell(row, 3);

        if (type == 'import') {
            currentRow.addClass('importsRow').removeClass('exportsRow');
        }

        if (status == 'UNP' || line == '' || eqpType == '') {
            currentRow.addClass('unplanned');
        }
    }
}
```

**Comment by AMBudnik** [comment]
Hi @alvarotrigo can you give an example how it should work. You want to highlight whole row if a value of a column is 'something' or you want to change only cells in that column?

**Comment by alvarotrigo** [comment]
@AMBudnik imagine I have a table with 4 columns.

I want to highlight the rows (the whole row, add a class to `tr`, for example), when the value in the column 1 is `2`, the value in the column 3 is `a` and the one in the column 4 is `c` or `d`.

**Comment by AMBudnik** [comment]
[this demo](https://jsfiddle.net/AMBudnik/6e97hdew/) checks after `click` event, is there a cell with a value `2010` if so, it hightlights whole row. 

It only checks the first row, but if this was what you wanted it's not hard to apply it to the rest.

**Comment by alvarotrigo** [comment]
@AMBudnik besides the link you provided doesn't really render anything (included files won't load), I do not want to check it under any event, but on load of the table. Just after the table renders.
