### ISSUE TITLE
afterCreateCol is triggered before ColHeaders are updated

### ISSUE THREAD

**Issue by cg3** [handsontable/handsontable#2419]
The following method will not return the fresh inserted column name, but instead the traversed one:

```
afterCreateColFunc = function (index, amount) {
    alert(hot1.getColHeader(index));
};
```

**Comment by cg3** [comment]
I tested some more functions with very strange behaviour:
```
afterCreateColFunc = function (index, amount) {
    hot1.setDataAtCell(0, index, hot1.getColHeader(index));
    hot1.selectCell(0, index, 0, index);
};
```
setDataAtCell writes the data into the correct cell (with the wrong name)
selectCell selects the wrong cell (one off like getColHeader)

**Comment by AMBudnik** [comment]
I tested you first example [here](https://jsfiddle.net/AMBudnik/3pdd8sg6/1/) and you're right.

**Comment by AMBudnik** [comment]
When it comes to `selectCell` is acts like `getColHeaders` they are triggered before actually a new column in inserted - we'll take a closer look at this issue. Thank you for your support.

**Comment by AMBudnik** [comment]
Updated demo to 0.24.1 (serving latest) https://jsfiddle.net/AMBudnik/3pdd8sg6/1/

**Comment by cg3** [comment]
I am sorry, but I couldn't wait a year for this fix, so I switched to a commercial product.

If the bug is fixed, you can close the issue.

**Comment by AMBudnik** [comment]
I truly understand @cg3 
hope our paths will cross someday again.

Thank you for your feedback.

**Comment by AMBudnik** [comment]
The issue no longer occurs. Updated demo https://jsfiddle.net/btjhv6f5/
