### ISSUE TITLE
Select editor - Issue

### ISSUE THREAD

**Issue by pradeeppatro** [handsontable/handsontable#2421]
Hi Team,
Scenario:
When cell type is "select", and table has horizontal scrollbar. If you scroll right and clicked on “select cell” type, then the select items (dropdown) is not rendering properly, it is rendering in extremely right. Kindly find below html and javascript code to reproduce the issue. 

HTML:
div id="example1" class="handsontable"  style="width: 200px; height: 200px; overflow: hidden" data-originalstyle="width: 200px; height: 200px; overflow: hidden"></div>

Javascript:
var container = document.getElementById("example1"),
    hot1;
  
  hot1 = new Handsontable(container, {
    data: [
      ['2008', 'Nissan', 11,'2008', 'Nissan', 11,'2008', 'Nissan', 11],
      ['2009', 'Honda', 11,'2008', 'Nissan', 11,'2008', 'Nissan', 11],
      ['2010', 'Kia', 15,'2008', 'Nissan', 11,'2008', 'Nissan', 11],
        ['2010', 'Kia', 15,'2008', 'Nissan', 11,'2008', 'Nissan', 11],
        ['2010', 'Kia', 15,'2008', 'Nissan', 11,'2008', 'Nissan', 11],
        ['2010', 'Kia', 15,'2008', 'Nissan', 11,'2008', 'Nissan', 11]
        
    ],
    colHeaders: true,
    contextMenu: false,
    columns: [
      {},
      {
        editor: 'select',
        selectOptions: ['Kia', 'Nissan', 'Toyota', 'Honda']
      },
      {},
      {},
      {},
      {},
      {},
      {
      editor: 'select',
        selectOptions: ['Kia', 'Nissan', 'Toyota', 'Honda']
      },
      {}
    ]
  });

Please fix this asap.

Thanks,
Pradeep.

**Comment by pradeeppatro** [comment]
![selectcelltypeissue](https://cloud.githubusercontent.com/assets/6286255/7387772/8bd207f2-ee7d-11e4-8452-cd027514ddea.png)

**Comment by AMBudnik** [comment]
I made a [demo](https://jsfiddle.net/AMBudnik/1vrc6rtp/) of your example. I reproduced it (on OSX) on:
* Chrome 42
* Fiferox 37
* Safari 8

When we scroll to H column and click any of it's cells we'll get select displacement. Select acts similar when there is `overflow: scroll` instead of `overflow: hidden`

**Comment by pradeeppatro** [comment]
Thanks a lot. Please let me know the fix asap.

**Comment by Lukazar** [comment]
@pradeeppatro might I suggest using the cell type 'dropdown'.  What little I've looked at the select editor source code makes it seem like it was written early on in HOT development and has lagged behind more popular cell types such as dropdown and autocomplete. IMHO its a better user experience as well.

**Comment by pradeeppatro** [comment]
Thanks @Lukazar. Earlier I was using same, but due some restriction I should not allow to edit/enter and then select from this filed. It should select from the available options only. It would be very helpful if the fix can be given.

Issue noticed:
It is adding element style css   left: 358px; which fails on horizontal scrolling case.
