### ISSUE TITLE
Top header isn't updating smoothly when Handsontable reaches the screen's top edge

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2422]
When scrolling the handsontable past the screen's top edge, the header updates choppy, sometimes stopping in an unsynchronized position.

-----------
##### Steps to reproduce:
- go to http://localhost/demo/renderers_html.html
- scroll down until HOT instance reaches the top of the screen
- slowly scroll further

**Result:**
![image](https://cloud.githubusercontent.com/assets/7397134/7388869/2cf749e0-ee69-11e4-9c16-dabf6371ad60.png)

**Comment by YipYipX4** [comment]
I can totally reproduce this issue just by using the following jsFiddle (from "Scrolling Rows and Columns" in the documentation):

http://jsfiddle.net/72fw1nrb/

And, it isn't just the header.  Sometimes large portions of the grid are blank after scrolling.  It used to work great (prior to version 15.x).  I'm using the latest Chrome on Windows.
