### ISSUE TITLE
"Merge cells" option in custom context menu

### ISSUE THREAD

**Issue by eholin** [handsontable/handsontable#2423]
The default context menu there is an item "Merge cells". I need to make a context menu, which also is the "Merge cells" working by default. But "Merge cells" is not in the list of menu options http://handsontable.com/demo/contextmenu.html. Is in Handsontable this option for custom menu or do I need to write a custom callback for "Merge cells" in the custom menu?

**Comment by AMBudnik** [comment]
Hi, to have this ability in contextMenu type `mergeCells: true` into your `settings`, like in this [example](https://jsfiddle.net/AMBudnik/jmng161o/)

**Comment by FrankFang** [comment]
Hi, but the contextMenu in your example is not customized.

**Comment by duccoder** [comment]
@FrankFang you can define mergeCells in contextMenu like:

```javascript
new Handsontable(container, {
  mergeCells: true,
  contextMenu: ['row_above', 'row_below', 'remove_row', '---------', 'mergeCells'],
  ...
}
```

**Comment by FrankFang** [comment]
But I have to change the menu name from 'merge' to Chinese '合并'.
Finally I worked around:
```
  //   contextMenu.items:
  mergeCells:
    name: ()->
      sel = @getSelected()
      info = @mergeCells.mergedCellInfoCollection.getInfo sel[0], sel[1]
      if info
        return '取消合并单元格'
      else
        return '合并单元格'

```

**Comment by carlosaar** [comment]
Thank you @FrankFang, Handsontable should put this string "mergeCells" in options of documentation of contextMenu
