### ISSUE TITLE
Scroll very slow

### ISSUE THREAD

**Issue by TheKassaK** [handsontable/handsontable#2424]
Hi !

I have already read all your solution for the slowy scroll. Play with the option colWidth for example, but no way, my scrolling is very fuc**** slow..

Is there a fix ? I don't have many columns, just 10, and 30 lines...

thanks !

**Comment by jansiegel** [comment]
Hi!
What OS and browser are you experiencing it on? Also, how many plugins are you using in your implementation?

Can you make a demo of the problem on jsfiddle? It would help us look closer at your configuration.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
