### ISSUE TITLE
0.15 breaks programmatic assignments

### ISSUE THREAD

**Issue by mgincnj** [handsontable/handsontable#2427]
If you code the standard links, e.g.
src="http://handsontable.com/dist/handsontable.full.js"
does that always get you to the latest code?

I assume it's now linked to the 15.0 release, because code that was working just fine a few days ago is now broken.  I downloaded and linked 14.1.1 manually and that fixed the issues.  Code which was assigning values to cell tables programmatically had stopped working.

I'm happy to help you characterize the problems if you tell me what you need.

**Comment by AMBudnik** [comment]
Hi, it's the latest full.js code but the file structure can change, that it why we always encourage to update your code after new release.

**Comment by mgincnj** [comment]
Aleksandra...

Well, now it's a mystery.  On the 30th I came back from a couple of days away and discovered the code on my leaflet maps to edit placemarks (which is based on Handsontable) had stopped working.  I discovered that you'd done a new release on the 29th, and by reverting to 14.1, fixed the problem.  This morning I tried to reproduce the problem, by restoring the links to your new release.  However, the code now still works fine after I do that.  

In retrospect, I believe it was a css problem, because it's the same behavior I get when the css linkage is broken.  Could it have been a browser cache issue (e.g. new .js and old .css?)  In any event, I can't now reproduce the issue, so I think you can close it.

**Comment by AMBudnik** [comment]
OK, I'm glad it works fine now. If you would have any other questions - feel free to open new issue.
