### ISSUE TITLE
Auto-scroll for Window-based scrollbars

### ISSUE THREAD

**Issue by YipYipX4** [handsontable/handsontable#2428]
When dragging the selection down or dragging the fill-handle down, the table should scroll automatically when reaching the edge of the window.  This does occur correctly when using table-based scrollbars, however when using window-based scrollbars, the table will not auto-scroll.

I am able to duplicate the issue here using Chrome on Windows:
http://handsontable.com/demo/scroll_window.html

**Comment by AMBudnik** [comment]
Thank you for reporting @YipYipX4 I agree with you, we'll see what we can do with it.

**Comment by AMBudnik** [comment]
Issue no longer present. Please try 0.24.1 version: https://docs.handsontable.com/0.24.1/demo-scrolling.html
