### ISSUE TITLE
Column Resize Isssue

### ISSUE THREAD

**Issue by logeshkumars** [handsontable/handsontable#2431]
Hi Team,

When column resize means, the others columns width also changed that's why the over all layout having ui glich.

Please refer to the below url.
https://goo.gl/23PPcr

Thanks,
Logesh

**Comment by AMBudnik** [comment]
Please check our [resize demo](http://docs.handsontable.com/demo-resizing.html) it does not act the same as your example. Prepare a [JSFiddle](http://docs.handsontable.com/demo-resizing.html) demo and we'll take a look what is wrong.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo/recent activity.
