### ISSUE TITLE
alter(...) not pass param source to callback

### ISSUE THREAD

**Issue by ciffel** [handsontable/handsontable#2433]
There is a parameter "source" for [alter](http://docs.handsontable.com/Core.html#alter). But the event hooks like [afterCreateRow](http://docs.handsontable.com/Hooks.html#event:afterCreateRow) only get two parameter which are index and amount. I suggest that source should be added as third parameter.

**Comment by AMBudnik** [comment]
Thank you for that suggestion.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
