### ISSUE TITLE
HandsOnTable - destroy and re-create not working after upgrading from 0.11.0 to 0.15.0-beta 2

### ISSUE THREAD

**Issue by csdpuneteam1** [handsontable/handsontable#2436]
I have code like below:

HTML

    <div id="rangePricesGrid" class="handsontable" style="width: auto; overflow: auto"></div>

Javascript: 

                  var rangePriceGrid = $('#rangePricesGrid').handsontable('getInstance');
                    if (rangePriceGrid != undefined) {
                        rangePriceGrid.destroy();
                        if (setRangeGridOptions != undefined)
                            rangePriceGrid = $('#rangePricesGrid').handsontable(setRangeGridOptions);

                    } else {
                        if (setRangeGridOptions != undefined)
                            rangePriceGrid = $('#rangePricesGrid').handsontable(setRangeGridOptions);
                    }

On page load, it works fine and paints the HOT. But then when I update one of the properties (say Data, and number of columns also) of HOT and then calls above method, it fails at the below

    rangePriceGrid = $('#rangePricesGrid').handsontable(setRangeGridOptions);

with error

    Uncaught Error: This method cannot be called because this Handsontable instance has been destroyed

What am I doing wrong here ? I know the HOT table is destoryed, but I am trying to re-created it with updated options. I know I can use updateSettings method, but I have a requirement where I need to show HOT only when there is a data from server, so there are situations when there is either data from server or Null data. So I need to use destroy and re-create.

Please suggest

**Comment by Lukazar** [comment]
I'm not entirely sure what you're trying to do, but will `updateSettings` work? http://docs.handsontable.com/Core.html#updateSettings

**Comment by csdpuneteam1** [comment]
updateSetting works, but as I said, I need to destroy the HOT and re-create.

**Comment by Lukazar** [comment]
Ah I'm sorry, I missed that last paragraph!

**Comment by Lukazar** [comment]
It looks like the instance is hanging around attached to `rangePricesGrid` div.  I suspect if you inject a new parent div, it'll work.  I hacked this together really quick so apologies, but it demonstrates this.

**Comment by csdpuneteam1** [comment]
Got help from 

http://stackoverflow.com/questions/30054621/handsontable-destroy-and-re-create-not-working-after-upgrading-from-0-11-0-to

I think you understand that you're destroying the instance but you don't understand how to recreate the instance. To start it would be useful to see setRangeGridOptions and maybe also a jsfiddle. If you're instantiating handsontable using the jQuerySelector.handsontable(options) method, it may be the cause of your problems.

Have you considered manually erasing the reference to the previous HOT instance so you don't have this problem? Try instantiating HOT this way:

     var hot = new Handsontable($('#rangePricesGrid')[0], setRangeGridOptions)

This way, you should be able to destroy the hot instance and your code should start working. To destroy the hot instance you would simply do:

    hot.destroy()

And to recreate it, you reuse the line above.

**Comment by AMBudnik** [comment]
Great, we encourage to write in SO tagging [HOT](https://stackoverflow.com/questions/tagged/handsontable) in similar cases.

**Comment by csdpuneteam1** [comment]
So tagging ?
I am sorry, but can you guide me what is it ?

**Comment by AMBudnik** [comment]
When you create a stackoverflow topic it is recommended to use tags. There are 320 'handsontable' tags in stackoverflow and many users that are advanced in HOT are helping each other. Github issues are treated as a board for bug report and at SO you can ask whatever you want.

**Comment by csdpuneteam1** [comment]
and I did tag handsontable when i raised the question on stackoverflow.

Please let me know if I am missing something here.

**Comment by AMBudnik** [comment]
It is all OK, wrote that just to let other users know.
