### ISSUE TITLE
IE: Unable to get property 'length' of undefined or null reference.

### ISSUE THREAD

**Issue by alexandergs** [handsontable/handsontable#2437]
I am getting this error in IE, but not in Chrome:

"Unable to get property 'length' of undefined or null reference."

The error also shows in their demo page. You can F12 to see the error as you simply moves the mouse:

http://handsontable.github.io/ngHandsontable/

Regards!

**Comment by AMBudnik** [comment]
Please follow https://github.com/handsontable/ngHandsontable/issues/66 for changes
