### ISSUE TITLE
Equivalent to `getData` for source data? `getSourceData`?

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2441]
I was looking at the docs and I found no equivalent to `getData()` to retrieve all the table information (including the hidden columns).

I saw methods like `getSourceDataAtCol` or `getSourceDataAtRow`, but nothing like `getSourceData`.

It would be quite useful to have it instead of having to iterate row by row after doing a getData (or similar) to then use `getSourceDataAtRow`.

Right now this is what I have to do:

```javascript
var grid = hot.getData();
var sourceData = [];

$.each(grid, function (index, value) {
    sourceData.push(hot.getSourceDataAtRow(index));
});
```

**Comment by AMBudnik** [comment]
According to [0.20.0 release](https://github.com/handsontable/handsontable/releases/tag/0.20.0)

`getData() method now returns the data after all the transformations (including trimming the rows with the modifyRow hook, manual column/row moving etc.). The previous getData() functionality was moved to the getSourceData() method, which returns the data as it was passed to the Handsontable instance.`
