### ISSUE TITLE
A bug in the merged cell.

### ISSUE THREAD

**Issue by jaime-lee** [handsontable/handsontable#2443]
A bug in the merged cell.

Step 1. current cell select
![image](https://cloud.githubusercontent.com/assets/7699206/7528984/521ce0f4-f56c-11e4-8ab8-f6af04f231d6.png)

Step 2. Merge Cells - Select Move (area)
![image](https://cloud.githubusercontent.com/assets/7699206/7528994/7575f0ea-f56c-11e4-8c07-f3235f731174.png)

Step 3. Select Move Up (area)
![image](https://cloud.githubusercontent.com/assets/7699206/7529009/8d0fc884-f56c-11e4-977f-d556667e1c3e.png)

Bug occurrence of the selected area.

**Comment by AMBudnik** [comment]
Hi @jaime-lee which OS/Browser are you using? I don't see it at Chrome 42/OSX

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply for more than a month.
