### ISSUE TITLE
Include plugins in bower repository

### ISSUE THREAD

**Issue by davidgeary** [handsontable/handsontable#2444]
Having the plugins as separate modules that are loaded as required is a good idea.  But currently, the only way to get them appears to be to download them manually from Github.

Is there any reason why the plugins cannot be included in a folder within the bower repository, so they are available when the main package is imported into a project, without having to be downloaded separately?

Note: I see that there's a related issue - #2072 - though that seems to be referring to 'built-in' plugins, whereas I'm specifically interested in the ones in the [`plugins`](https://github.com/handsontable/handsontable/tree/master/plugins) folder.

**Comment by AMBudnik** [comment]
Currently plugin are more flexible to include/exclude https://docs.handsontable.com/0.23.0/tutorial-custom-build.html
