### ISSUE TITLE
Provide support for registering plugin settings

### ISSUE THREAD

**Issue by davidgeary** [handsontable/handsontable#2446]
There is an issue with the [ngHandsontable](https://github.com/handsontable/ngHandsontable) component (already logged under [#60](https://github.com/handsontable/ngHandsontable/issues/60)), where it is unable to load plugins if the controlling setting, e.g. `search` and `removeRowPlugin`, is not present in the default grid settings.

It seems like the `settingFactory` class (in ngHandsontable) is doing the correct thing by checking that each setting is valid before assigning it, but if this is good practice, does there need to be an 'official' way for each plugin to register the settings that it depends on?

**Comment by AMBudnik** [comment]
Please do not duplicate issue, issue https://github.com/handsontable/ngHandsontable/issues/60 is open so please write any other questions or suggestions on this topic.

**Comment by davidgeary** [comment]
Sorry - I duplicated it because they're separate projects and I wasn't sure which one was considered to be wrong (and anyone else having the same problem now knows the bug lies in ngHandsontable).
Thanks.
