### ISSUE TITLE
BUG when i use mouse right

### ISSUE THREAD

**Issue by c941010623** [handsontable/handsontable#2449]
when i use mouse right key in disable menu then it will show error

Uncaught TypeError: Cannot read property '1' of undefined

EX:

http://handsontable.com/examples.html#fndtn-basic

then use mouse right click Undo or Redo
you will see the error console.log .....

**Comment by AMBudnik** [comment]
That you for support, we will take care of this.

**Comment by AMBudnik** [comment]
Does not occur in 0.17.0
