### ISSUE TITLE
merge cells can not render again

### ISSUE THREAD

**Issue by linminchao** [handsontable/handsontable#2450]
Hello all,
     I use handsontable merge cells.
     I need merge 3 cells first ,when date change ,I will merge 4 cells in the same position  second ,the first merge successed ,but the second merge is not successed (merge 3).
     How can I Solve problems？

**Comment by AMBudnik** [comment]
Please check if you code is related to one of [this issues](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Plugin%3A+merge+cells%22) if not, please provide a [JSfiddle demo](https://jsfiddle.net/api/post/library/pure/)

**Comment by AMBudnik** [comment]
Issue closed in lack of demo and/or further details.
