### ISSUE TITLE
Handsontable: column sorting doesn't work with function datasource

### ISSUE THREAD

**Issue by nellymor** [handsontable/handsontable#2451]
Using JSFiddle for Handsontable Function data source and schema I've added columnSorting: true.
Now I an getting an error - unhandled exception - from handsontable.full.js function _generate(mirror, obj, patches, path) {}
line 836 :mirror[key] = JSON.parse(JSON.stringify(obj[key]));
key = "attr";
obj[key] is a function function (attr, val);
JSON.stringify(obj[key]) returns "undefined"
and JSON.parse(JSON.stringify(obj[key])) returns "Invalid character" error.
How can I fix this?
I need a lot of properties enabled in my handsontable and because of the error (I think) undo functionality is not working, and loaddata() is not working properly either.
Thank you very much for all suggestions!

**Comment by AMBudnik** [comment]
please prepare a full [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/)

**Comment by nellymor** [comment]
Hello, 
Here is a link to JS Bin file:
http://jsbin.com/wopewo/1/edit?html,css,js,output
It is based on tutorial example for Function data source.
http://docs.handsontable.com/tutorial-data-sources.html
You can see that Undo context menu is not working. If I run this example with 'Stop on unhadled exceptions' option I am getting an exception from handsontable.full.js function _generate(mirror, obj, patches, path) {}
line 836 :mirror[key] = JSON.parse(JSON.stringify(obj[key]));

Thank you!

**Comment by AMBudnik** [comment]
Tried with 0.17.0, please check it yourself also - it should work fine. If you would find any issues please leave us a feedback and we'll reopen the issue.

**Comment by jesjos** [comment]
I get this error in my app running 0.24.3, I also get the error when using the fiddle provided here. 
Has there been a regression?

**Comment by AMBudnik** [comment]
thanks for update @jesjos I'll share it with other team members.
ps. currently undo doesn't work for sorting (for any type of data).

**Comment by budnix** [comment]
Confirmed, Currently we don't fully support function as data source. I mark this as bug.

**Comment by AMBudnik** [comment]
The issue is still replicable in v 0.34.0

**Comment by garthk** [comment]
@budnix, if it's not fully supported, could you perhaps note that in the documentation?

**Comment by AMBudnik** [comment]
Hi @garthk the whole undo-redo plugin is something that has to be fixed. It has many issues so it's more like something to fix rather than a note in the docs. Docs is a place where we described the actions in a proper state.

**Comment by AMBudnik** [comment]
The issue is no longer replicable in the latest version v`2.0.0.` and there are no console errors

![gif](https://user-images.githubusercontent.com/10757813/38984805-fd640ae4-43c7-11e8-9b85-a989b163ccdf.gif)
