### ISSUE TITLE
Handsontable: data validation does not work in the new version

### ISSUE THREAD

**Issue by nellymor** [handsontable/handsontable#2452]
I was using the Fiddle for Data Validation before the latest release and it was working properly, now it does not. I can't make it work on my page based on this example either. 
If I enter lower case last name the cell content becomes underscored and none of the other cells are editable. the cell does not get modified to be proper case.
If I start with email and modify it to be invalid focus remains on this cell, but cell does not get highlighted  - 'htInvalid' class is not set for this cell.
Could please somebody help with resolving Data Validation issue?
Thank you so much!

**Comment by AMBudnik** [comment]
Hi, without an example there is nothing much we can do. Please prepare one, you can use [jsbin](http://jsbin.com/?html,js,output)

**Comment by nellymor** [comment]
Hello, 
This is a demo from Handsontable tutorial
http://docs.handsontable.com/demo-data-validation.html
It doesn't work properly now as it was before the latest release.
Thank you!

**Comment by jansiegel** [comment]
This might have been related with issues: #2432 and https://github.com/handsontable/docs/issues/7. 
@nellymor, can you check if it works fine for you now?

**Comment by nellymor** [comment]
Hi Jan, yes, I think it's related to the issue  #2432, Can I download a fix please?
Thank you!

**Comment by AMBudnik** [comment]
Hi @nellymor do you still face the same issue?

**Comment by AMBudnik** [comment]
I assume this issue can be closed cause of lack of recent activity, but If anyone has questions related to that issue, please leave us a feedback.

**Comment by mohithgm** [comment]
@AMBudnik I'm facing this issue

**Comment by nellymor** [comment]
I've checked the Data Validation demo for the latest release 0.28.4: http://jsfiddle.net/api/post/library/pure/ - behavior is the same as it was described in the original issue: for email field allowInvalid is set to false and cell s not highlighted when you enter invalid email, but the issue was closed. Is it possible to make the invalid cell highlighted when allowInvalid = false?
The demo exists - it's a demo from the tutorial.
Thank you,

**Comment by AMBudnik** [comment]
I'm sorry @nellymor but I cannot replicate the issue. Can you create a .gif or instruct me step-by-step what to do?

**Comment by nellymor** [comment]
Hi AMBudnik,
Here are my steps:
1. Go to http://docs.handsontable.com/0.28.4/demo-data-validation.html;
2. Click on Edit;
3. In the first row Email column change 'Joe.Fabiano@ex.com' to 'Joe.Fabiano' (invalid email);
4. Click in a different cell: cursor returns to the previous cell, but the cell is NOT highlighted in red;
5. If I do the same with IP column (allowInvalid: true) - enter invalid IP, change cell - the cell is highlighted in red;
If this is an expected behavior - is it possible to highlight the cell with setting allowInvalid: false when the value is invalid?
Thank you.

**Comment by AMBudnik** [comment]
Hi @nellymor 

I guess that you're right, `allowInvalid: false` do not allow us to leave the editor till we do not enter a valid content but it shouldn't allow us to highlight other cells.

I'll mark this as a `change` topic. Thanks for sharing additional details and for your effort to test it.

**Comment by nellymor** [comment]
HI Aleksandra, 
My problem actually is that the same cell (where allowInvalid: false) is not highlighted, so it's not clear to the user that he/she entered invalid value.
Thank you,

**Comment by AMBudnik** [comment]
that's right @nellymor 
we have to change it.

Thanks for your effort to investigate this subject.

**Comment by AMBudnik** [comment]
Issue still relicable in Handsontable version 0.31.0

**Comment by AMBudnik** [comment]
In the latest version we are able to select another cell but the selection is gone after a second, demo http://jsfiddle.net/4g51mmr0/

![gif](https://user-images.githubusercontent.com/10757813/28960034-530ee388-78fd-11e7-8710-06524bd92026.gif)

**Comment by buffchuck** [comment]
Facing the same issue here. It appears to only happen when I am referencing the table directly using ...

data[0][0] syntax

If I don't reference the table directly everything works like it's "suppose to". I need to be able to manipulate the table directly on the fly without using the handsontable methods for some of my more complex functions.
