### ISSUE TITLE
Vertical Scroll very slow IE for large number of columns and rows

### ISSUE THREAD

**Issue by deenairn** [handsontable/handsontable#2453]
Hello,

I have a dataset which has around 200 rows x 200 cols approximately, and some summation logic. However, I am finding that, particularly in IE, that the vertical scrolling performance is very poor, horizontal scrolling is just fine. 

Having profiled the JavaScript - I can't really see any obvious way to improve the performance, one of the things that is taking a long time is the cell renderer but I don't think there is anything that I can do about this - I need the numeric formatting as it is. I've trawled StackOverflow and the support tickets but there's nothing I haven't tried already.

Here is a JS Fiddle example. Any ideas?

https://jsfiddle.net/deenairn/mogzxo62/embedded/result/

**Comment by AMBudnik** [comment]
Hi, it is an issue from https://github.com/handsontable/handsontable/issues/1772. Please track changes to it for further information.
