### ISSUE TITLE
Dragging fillHandle horizontally (with fillHandle: "vertical"), throws exception

### ISSUE THREAD

**Issue by pedrofsantoscom** [handsontable/handsontable#2454]
Windows 7 Pro 64bit
Chrome 42.0.2311.135 m
Firefox 37.0.2

1. http://jsfiddle.net/3nsn5a9y/1/
2. Drag and drop the fill handle from cell 1,1 to cell 1,2 (to the right)
3. Console throws an error on "WalkontableSelection.prototype.getCorners() line 1"

**Options for the hot:**
fillHandle: "vertical"
1st column with readOnly: true (it seems its not relevant to the case)

**Comment by AMBudnik** [comment]
I got the:

`Uncaught TypeError: Cannot read property 'getTopLeftCorner' of null` on
* Chrome42/OSX
* Chrome42/Win7

and the `TypeError: this.cellRange ins null` on
* FF37/Win7
* IE11/Win7
* FF37/OSX

on this particular action.

**Comment by AMBudnik** [comment]
Confirmed with [0.17.0 version example](https://jsfiddle.net/3nsn5a9y/15/) 
Same statement with Chrome45/OSX
