### ISSUE TITLE
fb-comments

### ISSUE THREAD

**Issue by kubak10** [handsontable/handsontable#2455]
Main issues to fix:
1. Scroll problem (wrong position) 
2. Multiple HOT problem (displaying only in one - last one - instance)
3. Save problem (not saving at all)
4. Rewrite to ES6

**Comment by kubak10** [comment]
https://github.com/handsontable/handsontable/tree/feature/ht-comments

**Comment by krzysztofspilka** [comment]
Released in https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
