### ISSUE TITLE
dataSchema (callback or template object) for new rows doesn't work with array-based tables

### ISSUE THREAD

**Issue by YipYipX4** [handsontable/handsontable#2456]
I would like to set the dataSchema setting (to either a callback function or a template array) to initialize default values for new rows while using an array-based table.

I've already implemented a fix for this and I submitted a pull request here:
https://github.com/handsontable/handsontable/pull/2420

I can try to use git flow if necessary, but my fix is only 4 lines of code and only applies when using an array-based table and a dataSchema setting has been set, so I hope someone can accept the pull request.

Thanks.

**Comment by AMBudnik** [comment]
Hi @YipYipX4 I had problems with reproducing. Could you check it with Handsontable 0.23.0?

**Comment by YipYipX4** [comment]
Hi @AMBudnik, I don't have time to look into this right now, but if you look at my pull request and find the corresponding code in the current version, I think you should be able to see if your current version still forces new rows for array-based tables to have all null values.  I need to be able to provide some default values for the new row (and naturally, when using an array-based table, I will provide an array of values in the "dataSchema" property).  I only needed to change 4 lines of code to support this, but since this issue wasn't responded to until now, I have not been able to upgrade to any newer version for a long time.

See these changes to DataMap.prototype.createRow: 
https://github.com/handsontable/handsontable/pull/2420/files

I think you could just search DataMap for "row.push(null)" and see if there is any alternative logic in the current version.

**Comment by AMBudnik** [comment]
Thanks you details and prompt reply
We'll take a closer look at your code.

**Comment by budnix** [comment]
Hi @YipYipX4, Your [PR](https://github.com/handsontable/handsontable/pull/2420) was merged. Thanks for support.

**Comment by YipYipX4** [comment]
Thanks!
