### ISSUE TITLE
Bad sorting if there are void cells in column 

### ISSUE THREAD

**Issue by averdesca** [handsontable/handsontable#2457]
Trying to sort columns with void cells returns undefined results. Void cells appear in a not proper position. Maybe it's better to put the void cells in the tail of column.

**Comment by AMBudnik** [comment]
Please prepare a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/) for this example.

**Comment by averdesca** [comment]
Here it is an example: https://jsfiddle.net/xjqoh2z0/. If you try to sort a column with void cells, the relative rows are sorted in a strange order.

**Comment by AMBudnik** [comment]
I made a simplier [example](https://jsfiddle.net/8vtzosme/), can you provide more information what you would like to get instead of ordered data that is driven now?

**Comment by averdesca** [comment]
I understood the problem. The issue occurrs when in the data objects array there are objects without any property instantiated (here it is your sample modified: https://jsfiddle.net/dh2fwx1a - note the data objects array). When I try to order column C, the rows related to the void cells stand in the initial position and aren't ordered as last rows of the table. if you had problems to execute my demo, try to run the link without the last "/": https://jsfiddle.net/xjqoh2z0  (it works for me).

**Comment by AMBudnik** [comment]
This issue should not occur with 0.19.0 version. Please update if it's possible.
