### ISSUE TITLE
Empty empty rows with a delete button?

### ISSUE THREAD

**Issue by nd7141** [handsontable/handsontable#2459]
How can I remove empty rows, when a user press Delete button.

**Comment by AMBudnik** [comment]
Hi, you want to delete rows that have no data or ones created by `minSpareRow`?

**Comment by nd7141** [comment]
Actually, only those that are not created by `minSpareRow`. I have a table with empty rows between rows with some data and I want to delete them. 

Also, is there a quick way to understand if a row is completely empty?

**Comment by AMBudnik** [comment]
To check if there are empty rows you can use `hot.countEmptyRows()` but it will give you only a number, not cell coords. If your function will delete `minSpareRow` also, you can use `updateSettings`.
