### ISSUE TITLE
requesting api change to rowHeaders

### ISSUE THREAD

**Issue by engenb** [handsontable/handsontable#2461]
First off, I love this grid!  I can't even start to explain how much time this is saving me on my project.

rowHeaders as a function receives the row index as its only parameter.  I'm wondering if it would be a beneficial change to also pass the model data to this as well.  I have a need to display some contextual data about the row in it's row header.

For example, instead of an index, I may want to display a timestamp.  A timestamp describing when the row was created could, of course, be a normal data column, but I want it to look and act like a row header.  I'm open to suggestions if there is a better approach to achieve this.

Thanks!

**Comment by AMBudnik** [comment]
Currently we do not have this kind of option. Thank you for a suggestion. 
I encourage to visit our [stackoverflow](https://stackoverflow.com/questions/tagged/handsontable) for more examples and solutions.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
