### ISSUE TITLE
Pressing CTRL+"Any key" throws error on autocomplete cell

### ISSUE THREAD

**Issue by pedrofsantoscom** [handsontable/handsontable#2462]
**Caught on:**
Windows 7 Pro 64bit
Chrome 42.0.2311.135 m
Firefox 38
IE 11

**Reproduce:**
1. http://codepen.io/anon/pen/OVNeav (jsfiddle is down atm)
2. Press CTRL+"Any key"
3. Throws exception: (chrome ouput) "Uncaught TypeError: Cannot read property 'renderedToSource' of null. @WalkontableSelection.draw"

**Investigation:**
I followed the stack trace and it leads me to "AutocompleteEditor.onBeforeKeyDown". Seems that the condition on [line 7713](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js#L7713), only checks for CTRL+C and prevents it from continuing. I guess improving that condition solves the problem?

**Comment by AMBudnik** [comment]
I didn't reproduce it. Tried it on OSX (with <kbd>CTRL</kbd> and <kbd>CMD</kbd>). Which OS/Browser you are using?

**Comment by ledjdm** [comment]
It's on the 1st lines of the comment btw :smiley: I get the exception on Windows 7 Pro 64bit with Chrome 42.0.2311.135 m, Firefox 38 and IE 11.

**Comment by AMBudnik** [comment]
Oh yes.. it tried in on virtual Win7 on Chrome 42 but had no problems. We gonna try this in other device to be sure.
