### ISSUE TITLE
Multiple row selection like Excel in handsontable

### ISSUE THREAD

**Issue by crazyjavatricks** [handsontable/handsontable#2463]
Can we select multiple rows like in MS Excel using Ctrl or any other key in handsontable. I am able to select multiple consecutive rows using the Shift key or using the mouse drag option. 
My question is it possible to select different rows like Row 1, Row4 holding the Ctrl key like in the Excel. Please advise,
Thanks

**Comment by AMBudnik** [comment]
Hi. You can only select more than one row/column if they are adjacent by <kbd>shift</kbd> + arrow nav or a lmb + drag. 

This is a duplicate from other issue, so please track https://github.com/handsontable/handsontable/issues/2119 issue for more information in this subject.
