### ISSUE TITLE
Wrapping for dropdown / autocomplete behaviour not correct where column width fixed

### ISSUE THREAD

**Issue by deenairn** [handsontable/handsontable#2464]
In a scenario where the column width is fixed to a set amount and there is a dropdown or autocomplete cell type - the 'wordWrap: false' behaviour is not as expected. This is highlighted in the jsFiddle example below. The behaviour occurs because a div is added to incorporate the clickable arrow that changes colour on click and the wrapping behaviour is separate between the two. I've tried some CSS changes - but not being an expert - not entirely sure how / if this can be fixed using CSS.

http://jsfiddle.net/deenairn/8o1vt4zg/

**Comment by AMBudnik** [comment]
Can you provide more information about what you want to achieve?

**Comment by deenairn** [comment]
Hi Aleksandra,

What I would expect is that where nowrap and fixed column widths are applied - the cursor is at the end but the text is wrapped. I've been trying to think of ways around this myself but it's not been that easy. I will post an example of what I've done if I manage to achieve what I think is the correct behaviour.

Thanks,

D

**Comment by deenairn** [comment]
Hi Aleksandra,

Something like this would be what I would anticipate. Can't decide if the overflow:hidden is necessary or not.

Thanks,

Donald

https://jsfiddle.net/deenairn/8o1vt4zg/1/

**Comment by deenairn** [comment]
Hi Aleksandra,

Do you agree with the above fix in the JS fiddle contribution (as the default behaviour for handsontable)?

Thanks,

D

**Comment by AMBudnik** [comment]
Hi, yes your solution looks much better.

Thank you Donald.

**Comment by deenairn** [comment]
Hi Aleksandra,

Shall I checkout the repo and commit the change back into the repo so it can be reviewed?

Thanks,

D

**Comment by AMBudnik** [comment]
You can surely create a pull request and if it will pass our tests and it will be suitable with the rest of code it will be added, but I cannot guarantee that it will be in the next release cause as you can see ([here](https://github.com/handsontable/handsontable/milestones)) we have a lot to do for new version.

**Comment by armensg** [comment]
So swithced my table from using hot-column directives and using dynamic column and applied the cell renderer to fix the word wrap issue. The problem now is that it seems to work for some to not push the caret down and not for others?
 works:
![image](https://cloud.githubusercontent.com/assets/6030955/17486527/09b0499c-5d89-11e6-8592-7dc0f6e5a562.png)

doesnt work:
![image](https://cloud.githubusercontent.com/assets/6030955/17486546/199fb8ce-5d89-11e6-9c7b-fa0d40c70949.png)

**Comment by AMBudnik** [comment]
The issue has been already raised at https://github.com/handsontable/handsontable/issues/3698
with a solution http://jsfiddle.net/deenairn/8o1vt4zg/5/
