### ISSUE TITLE
Bug on columns moving.

### ISSUE THREAD

**Issue by dixso** [handsontable/handsontable#2465]
Hi,
Try the create a new column, then, move the new column and finally create a new column:
jsfiddle: http://jsfiddle.net/dixso/d9Lm7ade/
video: https://www.dropbox.com/s/ao8z51e5r2f65rh/handsontable_columns.mov?dl=0

Regards.

**Comment by AMBudnik** [comment]
I see what you mean. Thank you for support - very interesting case.

**Comment by AMBudnik** [comment]
Seems to work fine in 0.24.1, demo: http://jsfiddle.net/d9Lm7ade/1/
