### ISSUE TITLE
Bug in setDirection of WalkontableCellRange

### ISSUE THREAD

**Issue by ciffel** [handsontable/handsontable#2467]
In setDirection method, we should cache original topLeftCorner and bottomRightCorner before replace this.from and this.to

Here is a demo:
http://jsfiddle.net/s5560nq7/

**Comment by AMBudnik** [comment]
updated to 0.24.1: http://jsfiddle.net/s5560nq7/1/

**Comment by AMBudnik** [comment]
@ciffel 
Finally fixed. I hope that it is working for you as well. Isn't it?

**Comment by ciffel** [comment]
It works well. Thanks for your efforts

**Comment by AMBudnik** [comment]
Great! Thanks for a prompt reply @ciffel
