### ISSUE TITLE
Problem in saving handsontable with formula columns

### ISSUE THREAD

**Issue by HardikSheth1717** [handsontable/handsontable#2468]
I am trying to save data as per the method suggested on the official website of handsontable. But when i pass data in c# using ajax call, fields display formulas and not calculated answer.
            I have attached screenshots of displayed table and C# data table.
            I am using save method mentioned on : http://docs.handsontable.com/tutorial-load-and-save.html

Please give solution as soon as possible.
Thanking you.
1. Html view
![html view](https://cloud.githubusercontent.com/assets/12509977/7699188/b2ed0f1a-fe33-11e4-909d-f59830509532.JPG)
2. C# data table
![c data table](https://cloud.githubusercontent.com/assets/12509977/7699190/b4d1ba74-fe33-11e4-8c61-f31b438857c2.png)

As shown in above screenshots, Area and Perimeter are formula fields but when i pass this data to my c# webmethod it displays formulas and not calculated answers. how do i save calculated answers for area and perimeter.

This is my code for load handson table

![loaf function](https://cloud.githubusercontent.com/assets/12509977/7718376/15f48964-fecd-11e4-8dae-58d184f630b5.JPG)

This is my code to save table

![save function](https://cloud.githubusercontent.com/assets/12509977/7718380/278a3e44-fecd-11e4-8536-cdcfb8e1cdad.JPG)

**Comment by AMBudnik** [comment]
Hi @HardikSheth1717 
If you're still facing this issues please create a working demo (preferably in JSBin, JSFiddle or CodePen).

**Comment by AMBudnik** [comment]
Formulas are being refactored. Hope we will have a fresh new version in the end of May - beginning of June
