### ISSUE TITLE
Header ngHandsonTable dissapear in IE9

### ISSUE THREAD

**Issue by fmreina-vector** [handsontable/handsontable#2469]
When I insert a handsontable and make a scroll the header of the table dissapear, does anyone know why it's occurs and what can I do to fix it?

Thanks.

In the following image, as you can see, the header when we make a scroll lose its position at the top of the table.

I have observed that in the demo example at http://docs.handsontable.com/0.15.0-beta2/demo-scrollbars.html does it occurs.

This is my example http://jsfiddle.net/k496ennk/2

This is the code of my HOT

         function renderTable() {

            Utils.apply($scope,function(){
                $scope.updateVisualization();                   
            });
            $("#vestarce_table").handsontable({
                data: $scope.tableData,
                headers:'#vestarce_table_header',
                footers:'#vestarce_table_footer',
                colHeaders: [
                  i18n("common.HEADERLABELS.CENTER"),
                  i18n("common.TIME_STRINGS.PERIOD"),
                  i18n("common.TABLE.TPV"),
                  i18n("common.TABLE.CLIENT"),
                  i18n("common.TABLE.TOTAL"),
                  i18n("vestarce.TABLE.UNITS.CURRENT"),
                  i18n("vestarce.TABLE.UNITS.PERIOD"),
                  i18n("common.TABLE.TPV"),
                  i18n("common.TABLE.CLIENT"),
                  i18n("common.TABLE.TOTAL"),
                  i18n("vestarce.TABLE.DESTINATION.NA"),
                  i18n("vestarce.TABLE.DESTINATION.UE"),
                  i18n("vestarce.TABLE.DESTINATION.TP"),
                  i18n("vestarce.TABLE.DESTINATION.IN")
                ],
                colWidths: [40, 70, 49, 49, 49, 49, 49, 80, 80, 80, 70, 70, 70, 70],
                afterRender:function(){
                    updateHeaderGrouping();
                },
                height: 230,
                stretchH:'all',
                readOnly:true,
                className:'text-right',
                columns: [
                    {data: 'center', className:'text-left'}, 
                    {data: 'period', className:'text-left', renderer:periodRenderer},
                    {data: 'units.tpv', type: 'numeric', format: '0,0', renderer:unitRenderer},
                    {data: 'units.client', type: 'numeric', format: '0,0', renderer:unitRenderer},
                    {data: 'units.total', type: 'numeric', format: '0,0', renderer:unitRenderer},
                    {data: 'units.current', type: 'numeric', format: '0,0', renderer:unitRenderer},
                    {data: 'units.period', type: 'numeric', format: '0,0', renderer:unitRenderer},
                    {data: 'amount.tpv', type: 'numeric', format: '0,000.00'},
                    {data: 'amount.client', type: 'numeric', format: '0,000.00'},
                    {data: 'amount.total', type: 'numeric', format: '0,000.00'},
                    {data: 'destination.NA', type: 'numeric', format: '0,000.00'},
                    {data: 'destination.UE', type: 'numeric', format: '0,000.00'},
                    {data: 'destination.TP', type: 'numeric', format: '0,000.00'},
                    {data: 'destination.IN', type: 'numeric', format: '0,000.00'}
                ]
            });
            $scope.table = $('#vestarce_table').handsontable('getInstance');
            updateTableHeight();
            console.log($scope.tableData);
            return $scope.table;
        }

**Comment by AMBudnik** [comment]
Hi, from version [0.12.0](https://github.com/handsontable/handsontable/releases/tag/0.12.0) we dropped support for IE8 and 9 so this issue will be closed. If you experience the same behaviour in other browsers/versions, please reply.
