### ISSUE TITLE
Enter key never advances to the next row with a Checkbox

### ISSUE THREAD

**Issue by kevin-j-morse** [handsontable/handsontable#2476]
For all Cell Types except the Checkbox, the enter key advances to the next row every two presses.

The first press edits the current row
The second press closes the edit mode and goes to the next row

With a Checkbox Cell Type, the enter key keeps toggling the value of the checkbox. You can never advance to the next row.

A solution is to prevent the Enter key from toggling the checkbox as it doesn't in any other applications. It should be reserved for entering edit mode and moving to the next row only. The spacebar is already responsible for toggling the checkbox.

**Comment by AMBudnik** [comment]
We will take it under consider, thank you.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. (Currently <kbd>Enter</kbd> is used to change the state of the checkbox)

Please free to continue the conversation there. Thank you.
