### ISSUE TITLE
IE11: Gettting "Unable to get property 'length' of undefined or null reference" on event.path.length

### ISSUE THREAD

**Issue by vkirienko** [handsontable/handsontable#2478]
Hi,

In IE 11 I'm getting "Unable to get property 'length' of undefined or null reference" on event.path.length line in extendEvent function.

![capture](https://cloud.githubusercontent.com/assets/12551258/7759423/2cc28f3e-ffdf-11e4-82a4-87b9f585a99d.PNG)

Regards,
Vlad Kirienko

**Comment by budnix** [comment]
This bug should be fixed in next Handsontable release. Fixed in pull request https://github.com/handsontable/handsontable/pull/2448

**Comment by alexandergs** [comment]
I assume this is the same issue as:
#2437
IE: Unable to get property 'length' of undefined or null reference.

**Comment by budnix** [comment]
Fixed in 0.16.0
