### ISSUE TITLE
HandsonTable Pikaday OnOpen & On Draw event unavailable

### ISSUE THREAD

**Issue by techcreatifs** [handsontable/handsontable#2479]
I want to use Pikaday onOpen & onDraw event with Handsontable but it seems that Handsontable table has block these events. Can you please confirm. Please see below my code. 

{ data: 'StartDate', type: 'date', dateFormat: 'MM/DD/YYYY', defaultDate: new Date().formatDate('m/d/Y'), validator: isDateColumnEmpty, onOpen: createButtonsForDateControl } 

var createButtonsForDateControl = function (a) { a; }

**Comment by AMBudnik** [comment]
Can you please prepare a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/) for your example?

**Comment by techcreatifs** [comment]
here is it.

http://jsfiddle.net/owaiskath/ow1pv7ek/

**Comment by techcreatifs** [comment]
@AMBudnik is there any update regarding this. 

Thanks

**Comment by AMBudnik** [comment]
Unfortunately there is not an option to this right now.

**Comment by techcreatifs** [comment]
is there any chances for this option in near future ?

Thanks

**Comment by techcreatifs** [comment]
Hi @AMBudnik ,

I want to add Today button in date Control. Can you please guide me how to do this. 

thanks :)

**Comment by AMBudnik** [comment]
There's not an easy option to do this, unfortunately HOT does not support this kind of functionality. You can try to check [stackoverflow with a `handsontable` tag](https://stackoverflow.com/search?q=handsontable) for more information

**Comment by budnix** [comment]
Related with https://github.com/handsontable/handsontable/issues/2606

**Comment by budnix** [comment]
Released in 0.16.0 - http://jsfiddle.net/ow1pv7ek/1/

**Comment by jeanmarc78** [comment]
hello,
thanks for the feature implemented, but i don't find the way to translate my date picker

regards
jmarc

**Comment by budnix** [comment]
Hi, based on pikaday documentation (https://github.com/dbushell/Pikaday#internationalization) you can pass internationalization object like this http://jsfiddle.net/ow1pv7ek/5/

**Comment by jeanmarc78** [comment]
ok , thanks a lot
best regards
jmarc
