### ISSUE TITLE
Can't scrolling window.scrollY

### ISSUE THREAD

**Issue by a740122** [handsontable/handsontable#2481]
WalkontableTopOverlay.prototype.scrollTo
Can't scrolling window.scrollY

div tag have not scrollbar.
browser version chrome v42 and v45

**Comment by a740122** [comment]
sorry, a same.
https://github.com/handsontable/handsontable/issues/2428

**Comment by AMBudnik** [comment]
OK, so please track changes to #2428 and I close this duplicate.
