### ISSUE TITLE
Paste inserts column data in reverse order

### ISSUE THREAD

**Issue by marcovc** [handsontable/handsontable#2482]
Hi,
It seems that when I hit ctr-v to paste a previously copied row, the pasted contents are inserted in reverse order, that is, from right to left. This seems to be caused by the main reversed loop of function applyChanges. Is there any reason why this must be so? Can I safely reverse it in my copy of handsontable? I need contents to be inserted in left to right due to having a set of events hooked to the insertion which must be triggered in the correct order.
I'm using a function datasource, and handsontable 0.12.2. Thanks!

**Comment by AMBudnik** [comment]
Please provide a [demo code](https://jsfiddle.net/api/post/library/pure/) for this example.

**Comment by marcovc** [comment]
Steps to reproduce:
1. Go to http://jsfiddle.net/7xc17a3L/2/
2. Select first row and hit ctrl+c
3. Go to A1 and hit ctrl-v
4. Expected behaviour should be Col1 alert and Col2 altert.

Thanks

PS: please let me know in case the fiddle does not work (it is my first time).

**Comment by marcovc** [comment]
Just to say that reversing the main loop of function "applyChanges" solves this issue for me (although I have no idea of what other problems it might create).

**Comment by AMBudnik** [comment]
tested it with the latest version: http://jsfiddle.net/7xc17a3L/2/ Seems to work fine,
@marcovc If I'm missing something please leave a comment

**Comment by marcovc** [comment]
Not sure if this issue was solved or if there is a regression, but the problem is there again (also noticed that the code for applyChanges still uses a loop that goes backwards).

**Comment by AMBudnik** [comment]
You're right @marcovc 
I'm reopening the issue.

**Comment by marcovc** [comment]
Hi,
I keep on having to patch every version with the fix I have for this problem (applyChanges in forward direction instead of backwards). Is there any way I can help to get this fixed soon? I can provide code, but I have no clue if it breaks other stuff.
Thanks!
Marco

**Comment by AMBudnik** [comment]
Hi @marcovc 

You can create a Pull request to the developer branch, if it will pass the tests it should work without issues. However all the pull requests are always checked by our developers before a publication and this can take some time.

**Comment by swistach** [comment]
Hi @marcovc, we've discussed the `applyChanges` issue and we've decided to not change this method.
You can use this simple workaround: http://jsfiddle.net/5wmo1Lrb/
Now I'll close this issue. Feel free to share your comment, if you find any issue in our workaround.
