### ISSUE TITLE
Improving Autocomplete dropdown menu visibility

### ISSUE THREAD

**Issue by pedrofsantoscom** [handsontable/handsontable#2483]
**Problem:**

1. http://jsfiddle.net/3nsn5a9y/
2. Open dropdown on column 3, on the "last row" of the visible rows (not the last row of the table)
3. Autocomplete dropdown menu opens bellow container, staying hidden

**Possible solution:**

1. http://jsfiddle.net/3nsn5a9y/5/
2. The example is just to show how it is suppose to open the dropdown menu, see 3. for the possible solution
3. Add "that.htContainer.scrollIntoViewIfNeeded()" bellow [line 7701](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js#L7701), so that the menu is shown

Even with that fix, theres still the problem of opening the dropdown on the last row of the table, as the menu is shown below the scrollable area and the menu should be positioned above the cell and not bellow.

**Edit**: Just realized the "element.scrollIntoViewIfNeeded()" is a WebKit only method, so we could use "that.htContainer.scrollIntoView(false)" ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)).

**Comment by AMBudnik** [comment]
Thank you for that suggestion. Well have to discuss this issue.

**Comment by ledjdm** [comment]
Needed these 2 fixes done, so i got hands on the code and was able to do the solution, but only was able to get it working on the hot version i use atm (0.13.1).

To work on 0.13.1:

Add code (1) to "AutocompleteEditor.prototype.open" after the following:

```javascript
that.instance._registerTimeout(setTimeout(function () {
    that.queryChoices(that.TEXTAREA.value);
    that.htContainer.style.overflow = 'auto'; // small hack to prevent vertical scrollbar causing a horizontal scrollbar
```

(1):
```javascript
// total height of the dropdown container
var htContainerHeightPosition = that.htContainer.parentElement.offsetHeight + that.htContainer.parentElement.offsetTop;
var cssPosition = "";
var cssTop = "";
if (htContainerHeightPosition - that.instance.table.offsetHeight > 0)
{
  // opens the dropdown menu above the cell
  cssPosition = "absolute";
  cssTop = "-" + that.htContainer.getElementsByClassName("htCore")[0].offsetHeight + "px";
}
else
{
  // fix htContainer not visible
  that.instance.rootElement.scrollTop += htContainerHeightPosition - that.instance.rootElement.clientHeight;
}

that.htContainer.style.position = cssPosition;
that.htContainer.style.top = cssTop;
```

and the code (2) to "AutocompleteEditor.prototype.close" after the following:

```javascript
AutocompleteEditor.prototype.close = function () {
    Handsontable.editors.HandsontableEditor.prototype.close.apply(this, arguments);
```

(2):
```javascript
// reset dropdown menu position
this.htContainer.style.position = "";
this.htContainer.style.top = "";
```

For those trying to get this to work on 0.15.0-beta3, you can continue here: http://jsfiddle.net/3nsn5a9y/14/

**Comment by ledjdm** [comment]
Updated the code for 0.13.1, seems to be fully working now.

**Comment by YipYipX4** [comment]
Not sure if this issue is related, but I implemented a few CSS fixes for the AutoComplete in issue 2380.  I am still waiting for those fixes to be applied to handsontable.

**Comment by surfncode** [comment]
I know this issue must be discussed but just in case my pull request provides a simple solution. I just display the autocomplete list above when the space below selected cell is too limited.

**Comment by budnix** [comment]
Currently we do not accepts PR to editors. For now we gather the strength to refactor editors to newer architecture which should resolve all problems with editors overlapping by table wrapper. It should be done on the beginning of Q3.

**Comment by MuyBien** [comment]
Hi everyone!
I have exactly the same problem. What is the news for this. I see it's closed so it is done?

Thanks for the tips.
