### ISSUE TITLE
Shift between headers (cols & rows) and data (cols & rows)

### ISSUE THREAD

**Issue by MuyBien** [handsontable/handsontable#2484]
Hi everyone.
First of all, I used this plugin for the first time, 3 years ago, and I am impressed of the evolution of this plugin. It was amazing 3 years ago but now... Whaou !

I have a little graphic problem. Maybe I am not initializing the table properly.

Here, a JSFiddle of my configuration : http://jsfiddle.net/x8zd31gk/1/

As you can see (I hope), there is a little shift between the columns headers and the "tbody"... Some pixels. This shift disappears when you re-size the window or make an action on the table (click on checkbox). The same problem is present with the row header when you start scrolling.

Tested on Chrome 42 and FF 37.0.2

Thank you !

**Comment by AMBudnik** [comment]
Do you mean the misalignment of how like below:

![zrzut ekranu 2015-05-25 o 11 17 06](https://cloud.githubusercontent.com/assets/10757813/7794914/f98e7b16-02cf-11e5-800d-7188e08d5ce4.png)

if so there's an issue for that https://github.com/handsontable/handsontable/issues/2354

**Comment by MuyBien** [comment]
Hi AMBudnik !
Yes ! Sorry I didn't search any issue with the word misalignment (I am not English I didn't know this word ^^). But in addition I have a misalignment of columns too, just on initialization (it disappears one you click on a cell). Do you have it too ?

![image](https://cloud.githubusercontent.com/assets/1921522/7807765/80d8d4e0-038e-11e5-8eae-fcc63c1418f4.png)

**Comment by AMBudnik** [comment]
Hm.. I can see only row misalignment, on which Operating system/Browser you experience this issue with columns?

**Comment by MuyBien** [comment]
I am on Chrome 43 and Firefox 38 both on W8.1.
I saw that with stretchH: 'all' I have this misalignment and with stretchH: 'last' I don't, but I have a ghost column at the end that disappears when I do an action on the table.

![image](https://cloud.githubusercontent.com/assets/1921522/7831358/5f6df5ba-0456-11e5-8121-09501e7c211b.png)

**Comment by budnix** [comment]
I see shift between headers too.

![zrzut ekranu 2015-05-27 o 10 04 54](https://cloud.githubusercontent.com/assets/571316/7831550/f59baa0e-0457-11e5-905e-f4ffe3e05479.png)

**Comment by AMBudnik** [comment]
Ok thank you @MuyBien we'll see what we can do. Stay tuned.

**Comment by MuyBien** [comment]
OK Thanks. If you need more information, I will answer.
Thank you ! Great job !

**Comment by MuyBien** [comment]
The last version (0.15.0-beta5) seems to fix that !

**Comment by AMBudnik** [comment]
I updated [your're demo](https://jsfiddle.net/x8zd31gk/3/) to 0.17.0 and it works fine. If you would have any issues related to this subject please leave us a feedback.
