### ISSUE TITLE
more column/cell info in afterValidate

### ISSUE THREAD

**Issue by engenb** [handsontable/handsontable#2485]
my row models are complex objects.  basically, a row contains a collection of cells.  I'm using your suggested function approach to get my cell data

```
function property(attr) {
    return function (row, value) {
      return row.attr(attr, value);
    }
  }
```

this works great.  however, I need to record some additional metadata about a cell if it fails validation - particularly, an error message.

neither validator function nor afterValidate hook have apis that provide column/cell information so I'm unable to determine what cell model I just validated.  would it be possible to include column index, cellProperties, or both to the afterValidate api?

thanks

**Comment by M4urice** [comment]
+1

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topic and uloading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Isuee will be reopene with first update.

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. Please free to continue the conversation there. Thank you.
