### ISSUE TITLE
Column sort arrow overlaps column name when using custom column headers

### ISSUE THREAD

**Issue by kevin-j-morse** [handsontable/handsontable#2486]
When handsontable is provided with custom column headers in the form of `colHeaders : Array [A, B, C, ...]` the sorting arrows from `columnSorting: true,` overlap the column names.

http://jsfiddle.net/kevin_j_morse/31xfdycx/3/

This doesn't look very good although I'm not sure what's the best solution if there's no room for the arrow. The annoying part is that even when there is lots of room for the arrow it still appears to overlap the text.

**Comment by kevin-j-morse** [comment]
In Chrome's Inspect element I can make this look somewhat better by removing the

```
.handsontable .columnSorting {
  position: relative;
}
```

from the `<span>` which has the after element attached to it. This moves the up or down arrow to the front of the cell which means it doesn't overlap if the cell is big enough.

Default ![arrow on top](https://cloud.githubusercontent.com/assets/4412177/7789453/b76c925a-0215-11e5-96ff-4170553e8d33.PNG)
With position relative commented out ![arrow in front](https://cloud.githubusercontent.com/assets/4412177/7789454/b7801adc-0215-11e5-8657-0023a4fb61b1.PNG)

**Comment by AMBudnik** [comment]
Thank you very much, it will be fixed.

**Comment by jansiegel** [comment]
@kevin-j-morse, you're right, it messes up when you sort columns with custom header labels.
I've modified these css entries
```css
.handsontable .columnSorting.ascending::after
``` 
```css
.handsontable .columnSorting.descending::after
```
to position them at:
```css
  position: absolute;
  right: -15px;
```

Which should fix this problem.

**Also**, I modified the sorting feature that way that by default, **no indicator will be displayed** unless you enable it by setting a `sortIndicator: true` config option.
Note, that you can enable it for the entire table (by setting the `sortIndicator: true` in the HOT initialization config) or for a certain column(s) (by setting the option in the `columns: []` property in the HOT config).

This will be released with the next version.

**Comment by krzysztofspilka** [comment]
Released in https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
