### ISSUE TITLE
getSettings() not updated to reflect user changes

### ISSUE THREAD

**Issue by bilogic** [handsontable/handsontable#2488]
getSettings() does not reflect user interaction changes such as changing of column widths or merging of cells. getSettings() returns what was originally assigned to it.

Is this by design? How do we detect user merged columns?

**Comment by AMBudnik** [comment]
`getSettings()` is not supose to show user changes, only settings. You can chose `getCell` to recieve the `rowspan` and `colspan` of cell if you want to track merging. Currently there is no 'merge dedicated' hook but you can use `hot.mergeCells. mergedCellInfoCollection` to get merged cells info.

**Comment by bilogic** [comment]
ok, thanks!

**Comment by bilogic** [comment]
I'm able to save the info using hot.mergeCells.mergedCellInfoCollection
however .updateSettings(mergeCells: [......]); does not merge the cells.
How do I programmatically merge cells?

**Comment by AMBudnik** [comment]
You can do something like in [this example](https://jsfiddle.net/ydstadmv/) but you will have to include logic to allow erasing data inside merged cells (now it pushes the data to other cells).

**Comment by bilogic** [comment]
ok, thanks
