### ISSUE TITLE
Unused overlay removal feature needs some updating

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2489]
The 'do not render the unused overlays' feature needed some upgrading, as it failed in some situations on iPad.
Developed on: https://github.com/handsontable/handsontable/tree/feature/overlays-removal-fixes

**Comment by jansiegel** [comment]
TODO: Need to check if it still works after the 0.15.0-beta5 performance changes

**Comment by krzysztofspilka** [comment]
Released in https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
