### ISSUE TITLE
Datepicker automatically setting dates in the 1900s

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2490]
After manually entering a date in a wrong date format, even with `correctFormat` set to `true`, the next time the user opens the date editor, the datepicker displays dates from the 1900s.

------------
##### Steps to reproduce:
1. Go to http://jsfiddle.net/oLnnj3nL/
2. In the last non-empty row, double-click the date cell
3. Manually enter `11/11/15`
4. Confirm using the `ENTER` key
5. In the last (empty) row, click the "expand the datepicker" button/indicator
6. Select any day from the displayed calendar

**Result:** The calculated date is in the 1915.

**Comment by krzysztofspilka** [comment]
Released in https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
