### ISSUE TITLE
error: row 1 does not exist

### ISSUE THREAD

**Issue by grey580** [handsontable/handsontable#2491]
This might not be an error and just be my lousy code. 

However I'm running into an issue where after clicking on my submit button and try to click on the blank row. I get the error.

Error: row x does not exist
	

throw new Error('row ' + coords.row + ' does not exist');

Here's an example http://jsfiddle.net/f6h25u4w/6/

Now if I click in the first row and move around the cells in the first row. the table fixes itself everything works as expected.  is there a setting in my code that's messing things up? or is this a bug?

**Comment by AMBudnik** [comment]
Can you please provide more information what would you like to achieve in this example?

**Comment by grey580** [comment]
well I think I figured out the issue.

If you look at the example I'm removing the blank row at the end of the array. at line 74 http://jsfiddle.net/f6h25u4w/6/

However in doing so it would give me the error. 

And I can see why. so you can close out this ticket. 

Or maybe put in some error checking so it doesn't throw the error if someone pops off the blank value in the array for the table.

**Comment by AMBudnik** [comment]
OK, so I will close this issue. It will be available to write in (for future questions/suggestions).
