### ISSUE TITLE
Z-index on ht_clone_top/left/etc necessary?

### ISSUE THREAD

**Issue by holbrookab** [handsontable/handsontable#2494]
https://github.com/handsontable/handsontable/blob/e05ab12bfaaa85fc4a308bbcc2c59ac6bbc38638/dist/handsontable.css#L594

These cause errors when I try to position other elements over the sheet.  If I remove them, I see no loss of functionality (or appearance) in the application.  Any reason why they are there?

**Comment by YipYipX4** [comment]
See also: case 2380 where I added a z-index fix for the autocomplete which was showing **below** the sticky header for another table.  (I just fixed it with additional CSS in my site and the handsontable code has not been updated.)

**Comment by peller** [comment]
bump. FWIW, this seems to be the changeset which introduced them 0ca0582a20bc2d9a1b0f2878cbded4c8a29794cc

**Comment by Mohit-Ak** [comment]
@holbrookab  - I faced the same issue buddy,
I fixed the issue by replacing the following in handsontable.css -
######
.ht_clone_top {
  z-index: 101;
}

.ht_clone_left {
  z-index: 102;
}

with ######
.ht_clone_top {
  z-index: -1;
}

.ht_clone_left {
  z-index: -1;
}

**Comment by peller** [comment]
I removed the z-index rules entirely:

https://github.com/ibm-et/handsontable/commit/31951c62725bab95a10535478a31ef5e2909bc55

**Comment by peller** [comment]
[jsfiddle showing](http://jsfiddle.net/nw3ccst1/1/) the problem interacting with overlay dom objects, such as a popup widget

**Comment by tnrich** [comment]
Thanks for the solution @peller , I was fighting this bug for a bit just now and was not a happy camper..

**Comment by AMBudnik** [comment]
Thank you guys for all the suggestions.
Currently one of our developers is working on a new CSS structure for Handsontable and all your comments are welcome.

**Comment by swistach** [comment]
You have to set z-index position of container (.dataTable in your example). Here's the updated example: http://jsfiddle.net/nw3ccst1/2/

**Comment by slothdude** [comment]
Changing / removing the z-index in handsontable.css didn't change anything for me, and setting the z-index value of the container to -1 made the table disappear. Anyone have a different solution?

**Comment by AMBudnik** [comment]
@slothdude can you share a demo with your settings? Does it happen for all the browsers?

**Comment by slothdude** [comment]
@AMBudnik My issue was that the dropdown from a 'react-select' `Select` element was somehow getting positioned behind the handsontable table headers. Fixed by increasing the z-index of the div containing the `Select` element to 150

**Comment by AMBudnik** [comment]
Thank you for the update @slothdude

**Comment by shaddamalbz** [comment]
@slothdude, me too
in handsontable version 12.3.0
i fixed this issue by set z-index to 1
`
.ht_clone_top,
.ht_clone_left,
.ht_clone_top_inline_start_corner {
  z-index: 1 !important;
}
`
