### ISSUE TITLE
Column filtering/searching

### ISSUE THREAD

**Issue by realtebo** [handsontable/handsontable#2495]
I'm looking for an excel-like html/js grid and your project looks very well. 

I need a particualr feature, and I'm not able to find this infos on the doc.

Can handsontable provide a by-column search feature? I mean a box under column title where user can type in and the following rows disappear if the cell content of the searched column doesn't match using a "like" approach (text contained)

**Comment by AMBudnik** [comment]
Actually HOT provides [search functionality](http://docs.handsontable.com/0.15.0-beta3/demo-search-for-values.html) but without filtering. 

All our feature requests can be found [here](https://github.com/handsontable/handsontable/wiki/Feature-requests) (filtering is at #1101 ).

If you would like to track changes to filtering issue please track changes to #1101 or if you need this functionality for a dead-line project you can choose our [support service](http://handsontable.com/support-services.html)
