### ISSUE TITLE
text-overflow: ellipsis and textarea

### ISSUE THREAD

**Issue by Velmir** [handsontable/handsontable#2496]
Hi. i dont know if it is a bug (but seems like), so please give an advice how to fix such behavior

01) Create table with text renderer, which adds some class to each textArea
02) Add 'text-overflow: ellipsis;' to this class, so long text in text area will be truncated as 'Text....'
03) Now select this cell and click 'Enter'. You can see that textbox is not been opened correctly. You should press any button (i.e Ctrl) to expand it in the full size

here is the screenshot : http://imgur.com/Nr0cuwQ
So, first picture -> default text-area with overflow. Second picture -> this textbox after 'Enter' click. Third -> after any button click.

Currently i'm trying to create my own editor an i'm sure there is some function to call from '....prototype.open()) to fix this bug. Do you have any ideas ?!

**Comment by AMBudnik** [comment]
Please prepare a demo code for this example. [JSfiddle](https://jsfiddle.net/api/post/library/pure/) would be appreciated.

**Comment by Velmir** [comment]
Here you go : http://jsfiddle.net/wweLfgu6/
So steps : 
01)Select first (and alone :( ) cell.
02)Click 'Enter'
03)Click 'Ctrl'
Textarea will expand at the full size. This is an effect i would like to reach

**Comment by AMBudnik** [comment]
This is not actually a bug, so I can write it down as a feature request.

**Comment by Velmir** [comment]
Ok, thank you. Is there any possibility to fix it by myself ?!

**Comment by AMBudnik** [comment]
You can pull a request. We always appreciate support from our users.

**Comment by AMBudnik** [comment]
Feature was added to our list. It is at our [wiki](https://github.com/handsontable/handsontable/wiki/Feature-requests). 

This issue will be reopened with changes made related to this feature request.
