### ISSUE TITLE
Checkbox issues

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2497]
I got it from Charles who asked us to fix some issues that he struggled with considering checkboxes in Handsontable:

**Severe:** When HOT  checkbox data is copied to Excel,  Excel converts the checkbox values to 0 or,   all caps and centered text “TRUE”.   Not sure what Excel is doing but   It is very difficult to convert those centered “TRUE” back to left aligned, lower case “true”.    You can not just type over them or they remain all caps and centered .     And if you don’t convert them, and  then copy the excel data and paste back into HOT, all the same checkboxes now appear in error with  #bad value#.   

**Let me give a clear example:**

1.   Here is the HOT sheet data I selected and copy into clipboard:

![1](https://cloud.githubusercontent.com/assets/8048526/7837815/ad165f04-0489-11e5-9f6c-a1db9cb418e5.png)

2. Then I paste that clipboard data I into Excel 2013:

![2](https://cloud.githubusercontent.com/assets/8048526/7837818/b4fe7828-0489-11e5-935b-f0dd9aeccdc5.png)

C) If I select the data I just pasted into Excel, and then copy and paste this back to HOT,  here are the results:

![3](https://cloud.githubusercontent.com/assets/8048526/7837822/c03718b2-0489-11e5-9801-290fe5bde598.png)

**Medium:**  The only two values I can use to initialize a checkbox is “0” or “true”.   The natural pair would be the strings  “0” and “1” or “false” and “true” or numeric 0 or 1.   Upper case letters and the numeric 1 fails with #bad value#.    It may not seem like a big issue except that special code (very unnatural and awkward code) must be implemented both ways when reading from or saving data to  a server.  Whats more,  when there are have many rows the extra logic needed for conversion causes delays.   Since most  servers return numeric  0 or  1; or they return True or False -  it’s quite awkward to deal when using HOT.

**Comment by YipYipX4** [comment]
FYI, I can duplicate this issue in my own site and also simply using the checkbox demo here:
http://docs.handsontable.com/0.15.0-beta3/demo-checkbox.html

Just copy the whole table to Excel and then copy back and you will see "#bad value#" in all checkbox cells.  Happens in at least Excel 2010 and Excel 2013.

**Comment by firechicago** [comment]
I have the same issue using Numbers in OSX. This has me seriously considering switching to using dropdowns for boolean values in my current project.
