### ISSUE TITLE
Keyboard navigation issues when renderAllRows = true, 

### ISSUE THREAD

**Issue by MrVila** [handsontable/handsontable#2499]
When I put renderAllRows = true, the keyboard navigation don't works when i press bottom arrow.

Here is an example:
http://jsfiddle.net/kndzzkza/

**Comment by AMBudnik** [comment]
Reproduced (Chrome/OSX). I got key nav working but scrolling does not work. Cell can be edited (screen below)

![zrzut ekranu 2015-05-29 o 15 26 25](https://cloud.githubusercontent.com/assets/10757813/7883498/4044ebd6-0617-11e5-85c5-8358a7d284f4.png)

**Comment by AMBudnik** [comment]
Confirmed with [0.17.0 version example](https://jsfiddle.net/kndzzkza/1/)
* no console errors

**Comment by AMBudnik** [comment]
Confirmed with 0.23.0

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1

**Comment by swistach** [comment]
It's the same issue: #3866
