### ISSUE TITLE
Make all save operations 'POST' instead of 'GET' in all examples!

### ISSUE THREAD

**Issue by hansgru** [handsontable/handsontable#2500]
Make all save operations 'POST' instead of 'GET' in all examples!

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
