### ISSUE TITLE
columnSorting and manualColumnResize options not working

### ISSUE THREAD

**Issue by engenb** [handsontable/handsontable#2502]
here's a fiddle that recreates the issue
http://jsfiddle.net/ds95omww/2/

my project dynamically builds a grid from a collection of column definitions loaded from the database.  the example illustrates the resulting config hashes for columns, colHeaders, and data generated after processing such definitions.

neither columnSorting nor manualColumnResize are functioning properly.  I don't want to speculate, but I'm curious if this has to do with my column data property being a function rather than a property key.

**Comment by budnix** [comment]
This is bug but releated with update handsontable settings via `.updateSettings` method. If you pass settings in constructor then it works as expected - http://jsfiddle.net/ds95omww/3/.
