### ISSUE TITLE
Expected Behavior When Toggling Multiple Checkboxes

### ISSUE THREAD

**Issue by YipYipX4** [handsontable/handsontable#2503]
If a user selects multiple checkbox cells with a mix of checked and unchecked values and hits the spacebar, I strongly suspect that they would expect all checkboxes to be checked (if any are unchecked) and if they hit the spacebar again (with all checkboxes checked), then everything would be unchecked.

The current behavior is to simply toggle all states (so if you start with a mix of checked and unchecked, then you will still have a mix after pressing the spacebar). This can be duplicated with the checkbox demo page:
http://docs.handsontable.com/0.15.0-beta3/demo-checkbox.html

If you think the toggle behavior has value, then maybe it could be assigned to a different key (such as T), but I think that the behavior when pressing the spacebar should be as described above.

Thanks!

**Comment by AMBudnik** [comment]
Thank you for that suggestion, we will have to discuss this behavior.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
