### ISSUE TITLE
Default cell value property - Request

### ISSUE THREAD

**Issue by halfnibble** [handsontable/handsontable#2504]
**Request**
I am requesting a Handsontable property that lets you assign a simple JSON object with the property name and default value. This would automatically show in the displayed cell and form_data when a new row is created that isn't provided a value for said property.

**Rationale**
Googling around, there are several use cases for supplying default cell values. While I appreciate the flexibility the current pre-populate method allows, it seems extreme to have to write a custom render method and custom beforeChange method to parse all this out just to have cells with default data.

**Comment by YipYipX4** [comment]
I think what you need is the dataSchema setting.

FYI, I wrote a fix for dataSchema that makes it work when using an array of arrays for the data source. and I submitted a pull request, but it hasn't been accepted yet.  See https://github.com/handsontable/handsontable/issues/2456

**Comment by halfnibble** [comment]
@YipYipX4 that would be nice if the solution turns out to be so simple.

So, say I have a Handsontable with 3 columns:
1. `id`: Salesman ID
2. `name`: Salesman Name
3. `sales`: Salesman Sales

When I copy a new salesman into the Handsontable instance, I want column # 3 to always be `$ 0.00` *unless* the data I paste in already has a value for column # 3. 

Would I do something like this?
```javascript
var blahblah = new Handsontable({
    ...
    dataSchema: {
        'id': '',
        'name': '',
        'sales': '$ 0.00'
    },
    ...
});
```

**Comment by YipYipX4** [comment]
I think that should work for you.  You should try it and check the documentation if it doesn't work (FYI: you can also provide a callback function that returns the object if you need it to be dynamic).

Note: I don't work on the handsontable team -- I just saw your issue and thought it might be related to my fix.

**Comment by AMBudnik** [comment]
@halfnibble if you would have problems with code, create a demo and we'll see what we can do
@YipYipX4 thanks for support

**Comment by AMBudnik** [comment]
Issue will stay closed, but if there are some other questions related to this issue don't hesitate to leave a feedback.
