### ISSUE TITLE
Autocomplete Only Shows First Half of Items on First Click

### ISSUE THREAD

**Issue by YipYipX4** [handsontable/handsontable#2505]
In https://github.com/handsontable/handsontable/issues/2380 I came up with many CSS fixes for the autocomplete UI, but I also noticed that only the first half of the items render on the first click.  If you close the autocomplete and reopen it, then all of the items render.

Here's a jsfiddle without any of my CSS fixes.  Click one of the "Car" autocompletes and immediately scroll down to the bottom.  About half of the items will be missing.  Close the autocomplete and try again and then all of the items will be shown.  I'm using the latest regular release of Chrome on Windows.

http://jsfiddle.net/wz60bf0a/3/

**Comment by AMBudnik** [comment]
Thanks for that report. In [this example](https://jsfiddle.net/LsbkjL71/) with first open we get 35 items, and with second there are all of them. 

I tried it on Win7 and OSX (reproducible in both).

In Win7 on IE it looks like this.

![untitled](https://cloud.githubusercontent.com/assets/10757813/7878339/07ac0876-05e6-11e5-9f2a-3adf1f4ea897.png)

**Comment by YipYipX4** [comment]
FYI, this issue still occurs in version 15.0.

Here's an updated jsFiddle:
http://jsfiddle.net/wz60bf0a/7/

**Comment by AMBudnik** [comment]
Issue no longer exist with 0.18.0 changes, please look at [example demo](https://jsfiddle.net/LsbkjL71/1/)
