### ISSUE TITLE
Dropdown id/text support ?

### ISSUE THREAD

**Issue by hansgru** [handsontable/handsontable#2506]
Hi is it possible for Dropdown  cells to work internally with a key of the data (load/save), but render/display another property (in the grid and in the dropdown box too)?
This is typical for most scenarios where HTML Dropdowns are used. E.g. something like this:
```javascript
....
var dropdownSource = [
  {id:10,text:'label1'},
  {id:11,text:'label2'},
  {id:12,text:'label3'}
];
....
data: [
  {col1:1,col2:10,col3:'simple text 1'},
  {col1:2,col2:11,col3:'simple text 1'},
  {col1:3,col2:12,col3:'simple text 2'},
],
columns: [
  {data:'col1', type:'numeric'},
  {data:'col2',type:'dropdown'},
  {data:'col3'}
],
....
```
to Have in column 2 ```label1```,```label2``` and ```label3``` and also in the dropdown, but loading and sending to server to work with the ```IDs``` : ```10,11,12```?

Thank you.

**Comment by AMBudnik** [comment]
Hi @hansgru 
did you made any progress in this case?

**Comment by AMBudnik** [comment]
Closed in lack of recent activity,
