### ISSUE TITLE
Can't freeze the just unfrozen column

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2507]
Once I unfreeze the column I can't find an option in the context menu to freeze it again.

**Steps to reproduce the problem:**

1. Go to http://docs.handsontable.com/0.15.0-beta3/demo-freezing.html
2. Invoke context menu for column B
3. Select "Unfreeze this column"
4. Invoke context menu for column B again. Try to freeze it.

:information_source:
> Handsontable v. 0.15.0-beta3
> Windows 8.1
> Chrome v. 43.0.2357.81 m

![screenclip](https://cloud.githubusercontent.com/assets/8048526/7858804/b4206440-053b-11e5-9973-f5de0ff146cf.png)

**Comment by jansiegel** [comment]
Seems to work fine for me (Mac, Chrome)

![column_unfreeze](https://cloud.githubusercontent.com/assets/7397134/7859037/8cc64aac-053d-11e5-91b9-f01fa615bd4a.gif)

**Comment by krzysztofspilka** [comment]
Removed the freezed column B first and invoke context menu for new column B (formerly column C).

**Comment by jansiegel** [comment]
Released in [0.17.0](https://github.com/handsontable/handsontable/releases/tag/0.17.0)
