### ISSUE TITLE
Column Sorting Issues

### ISSUE THREAD

**Issue by MaruthiGitHub** [handsontable/handsontable#2508]
Hello,

I am trying to use the column sorting option in HandsOnTable. The sorting is working fine, but the sorting is getting applied to all columns. I have set the configObj as

columnSorting: {
        	    column: 2,
        	    sortOrder: true
}

Also when the column headers are clicked for sorting, the arrow appears on the Column Header Name as seen the screenshot below. The arrow should place itself beside the Column Header Name.
![image](https://cloud.githubusercontent.com/assets/5886000/7859034/d972a392-055a-11e5-88b4-037e931499e3.png)
 Please help me know the solution.

**Comment by budnix** [comment]
Releated with https://github.com/handsontable/handsontable/issues/2486.

**Comment by realtebo** [comment]
Sorry, I opended a new one for the same problem, see #2510 . 
In the #2510, I've added a jsFiddle to demonstare the 100% reproducibility of the bug

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/2486 it is the same issue and it will be fixed in newer release.
