### ISSUE TITLE
Hook for double click on handson table cell

### ISSUE THREAD

**Issue by ashishkumarbatra** [handsontable/handsontable#2509]
We could not find a hook for double click on hands on cell.It would be nice to have one.Please let me know if there is one or there is any work around.

**Comment by AMBudnik** [comment]
Thank you for that suggestion.

**Comment by vlados** [comment]
Why this hook was removed? (dblclickCell)

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
Duplicate of https://github.com/handsontable/handsontable/issues/2266
