### ISSUE TITLE
Suggestion: deploy as a composer package

### ISSUE THREAD

**Issue by realtebo** [handsontable/handsontable#2511]
Thanks for using bower, but, could you add also composer as a deploy option?

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
