### ISSUE TITLE
Example in the docs throws an error

### ISSUE THREAD

**Issue by realtebo** [handsontable/handsontable#2512]
I'am in this page: http://docs.handsontable.com/0.15.0-beta3/demo-custom-renderers.html#page-header at the subtitle _Changing cell type from a dropdown menu in cell header_ 

Watch at the example code into this function

    afterGetColHeader: function (col, TH) {
    ....
    menu = buildMenu(columns[col].type)

When the execution reaches `buildMenu(...)` it generates an error. This is caused because for some reason I don't know, and _I suppose it's a bug_, the `col` value is set to `-1`. Of course, it's not possible that we have an index like this.

This error is demostrated in this jsFiddle: http://jsfiddle.net/realtebo/wru8bjcv/ 

Here you can see the `console.log (col)`. 
Of course you'll see in your console that sequence, (repeated some times !)

    1
    0
    -1

This fiddle is not the example's full code, but it's enough to prove that the example is not working due to a call with `col` set as `-1`. 

also: the `console.log` shows a LOT of call to the function `afterGetColHeader` and I think it's not a good thing

**Comment by AMBudnik** [comment]
Hi @realtebo it is intentional. Dataset is started with 0,0 so col has to have `-1` Please see the [example](https://jsfiddle.net/wru8bjcv/1/)

**Comment by realtebo** [comment]
Ok, but the fiddle it's the demonstation that example code throws an error due to this -1

**Comment by AMBudnik** [comment]
Hi @realtebo 
I tried to reproduce it with 0.24.1 and it seems to work fine. Could you check it please?

Thanks in advance!

**Comment by AMBudnik** [comment]
I assume it doesn't occur anymore but if I'm wrong please share your opinion.

**Comment by Wojciech-Swiderski** [comment]
issue no longer persists
