### ISSUE TITLE
before/afterChange changes arg contains prop, not col index

### ISSUE THREAD

**Issue by engenb** [handsontable/handsontable#2513]
another request that's kind of a big need for me right now, so maybe I'll get to work on a pull request.  thought I'd still raise the issue and/or start a conversation about this.

regarding the arguments these hooks each pass, changes and source - the values for each change in the changes array arg are row index, column property, old value, new value.  the value in question here is column property.  I suspect this is typically the name of the property on the row model for that column.  unfortunately, I'm using a function to get my column value from a complex row model, so my column property value is a function, which tells me nothing about which column was changed.  a column index would be much more useful here, at least for the scenario when the column is configured with a function for its data property.

**Comment by engenb** [comment]
to update, I'm unable to use propToCol to get my column index.  I'd still like to suggest the following from setDataAtCell
```javascript
prop = datamap.colToProp(input[i][1]);
      changes.push([input[i][0], prop, datamap.get(input[i][0], prop), input[i][2]]);
```

just becomes

```javascript
prop = datamap.colToProp(input[i][1]);
      changes.push([input[i][0], col, datamap.get(input[i][0], prop), input[i][2]]);
```

as the col index is the common denominator regardless of a column's data prop being a string or function.  however, I realize this would be a possibly breaking change so I would understand hesitation

**Comment by AMBudnik** [comment]
thank you for this suggestion.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
