### ISSUE TITLE
DropDown, when selecting the first time the scroll bar is missing

### ISSUE THREAD

**Issue by schierme** [handsontable/handsontable#2514]
When you select a dropdown cell in a table for the first time for a longer list of items, the scroll bars are being omitted. Version 0.14.1.

Here's a JSFiddle of the issue.
http://jsfiddle.net/3g9fk3f2/3/

**Comment by AMBudnik** [comment]
Hi @schierme with 0.15.0-beta3 it works fine. Please update to newest version.
