### ISSUE TITLE
Context Menu Crashes when Table Has No Data

### ISSUE THREAD

**Issue by YipYipX4** [handsontable/handsontable#2515]
Here's a JSFiddle that duplicates the issue:
http://jsfiddle.net/rdawfppa/

1. Try right-clicking anywhere on the first table (including the headers).  It works OK.
2. Try right-clicking on the headers of the second table, **which has no data**.  The console will show the following error:
  * Uncaught TypeError: Cannot read property '1' of undefined

**Comment by AMBudnik** [comment]
You are right it has to have at least one row.

**Comment by YipYipX4** [comment]
Can this be fixed so that the error will not be thrown?  In my project, I have a global error handler and users will see a dialog with this error when right-clicking on an empty table.
