### ISSUE TITLE
jsfiddle examples broken due to broken links

### ISSUE THREAD

**Issue by jlsalmon** [handsontable/handsontable#2516]
Hi,

Multiple jsfiddle examples I have come across are broken due to the fact that the links to the handsontable source are broken (e.g. https://jsfiddle.net/re9yxmvw/2/). The sources used to be hosted at e.g. http://handsontable.com/dist/handsontable.full.js but must have been moved or removed.

It would be great if those links could be fixed, or perhaps symlinked to their new locations?

**Comment by AMBudnik** [comment]
Thank you for that report.

**Comment by AMBudnik** [comment]
All broken examples are now at https://github.com/handsontable/docs/issues
