### ISSUE TITLE
Dialog getting overlapped by handsontable of previous screen

### ISSUE THREAD

**Issue by vivekgaurav** [handsontable/handsontable#2518]
Hi All,
            I am using Handsontable with SAP UI5.

           When i dialog box open handsontable header and side serial no comes over dialog.

            Kindly look into this issue

Thanks
Vivek

**Comment by AMBudnik** [comment]
Could you please prepare a demo showing this example?

**Comment by vivekgaurav** [comment]
Hi ,
     I had uploaded the screen shot.

    You can see how handstable getting overlapped on dialog.

![handsontableissu](https://cloud.githubusercontent.com/assets/12694595/7933829/aad79aae-093f-11e5-8d3a-3a400608e0b6.JPG)

Regards
Vivek

**Comment by AMBudnik** [comment]
without your code there is not much what we can do. In [this example](https://jsfiddle.net/secz5b78/) HOT doesn't interact with dialog window.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo or a code sample.
