### ISSUE TITLE
All to tab into grid

### ISSUE THREAD

**Issue by dmfRain4** [handsontable/handsontable#2519]
When "tabbing" through the eligible elements on the page, I am having trouble tabbing into a handsontable filled with data. It appears that the table is not an eligible element for "tabbing" in the browser. How might I enable it so that it can be tabbed into, through, and out of?

The issue is in concern for a user that does not have a mouse or simply cannot use one for accessibility reasons and/or must use a screen reader.

**Comment by AMBudnik** [comment]
Now when you are tabbing HOT is bypassed. [Example](https://jsfiddle.net/0g0f7r32/)
We will discuss this issue.

Thank you for reporting.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
example update to 0.29.0 https://jsfiddle.net/dw6fjqc3/

**Comment by AMBudnik** [comment]
Thanks to @swistach 
we have a working example https://github.com/handsontable/handsontable/issues/2519
I'm removing this issue from the `improvement suggestion` list as it is more like a outside solution rather than something that should be a part of Handsontable code.

**Comment by HageMaster3108** [comment]
Thanks a lot @AMBudnik and @swistach!

I found two problems though:
* Your beforeKeyDown handler wasn't checking whether it actually was the TAB key. This resulted in any keypress in the last cell to unselect the cell
* If the user didn't tab INTO the table, but clicked a cell, tabbing out did not work. 

I have fixed both issues in a new jsfiddle:
https://jsfiddle.net/uu01qajn/10/

Basically what I changed is:
* Added a check for the TAB key
* The "hotActivator" button is now focused before unselecting the cell and calling "unlisten". This causes the browser to skip to the next element even if the user has clicked into the table initially.

Thanks again!

**Comment by HageMaster3108** [comment]
On top of my last comment, even though I now know how to make handsontable tabbable and enable "tabbing out":
I do not agree that this isn't something which would be a valuable improvement to be done inside handsontable.

Using handsontable in a form is very common in my eyes.
So whenever you want to construct a keyboard-navigation friendly form, this will be a problem.
Why would all users have to implement this handling on their own if it could be a simple option?
