### ISSUE TITLE
Copy/Paste doesn't work on Bootstrap dialog on IE

### ISSUE THREAD

**Issue by Gabriel-Lahyani** [handsontable/handsontable#2521]
## Description
The feature Copy/Paste works well on Bootstrap dialog both on Chrome and Firefox.
But fails on IE. (checked on IE9, IE10, IE11on Windows 7).
Handsontable 0.14.1

## How to fix
Copy the CopyPasteDiv tag within the bootstrap modal dialog.

       <div style="left: -10000px; top: -10000px; position: fixed;" id="CopyPasteDiv"><textarea    style="width: 10000px; height: 10000px; overflow: hidden; opacity: 0;" class="copyPaste"></textarea>
       </div> 

And, when you copy the CopyPasteTag, pay attention to not return to the line before the tag 'textarea'.
For instance, copying the CopyPasteDiv tag like this will fail for all browsers:

       <div style="left: -10000px; top: -10000px; position: fixed;" id="CopyPasteDiv">
              <textarea    style="width: 10000px; height: 10000px; overflow: hidden; opacity: 0;" class="copyPaste"></textarea>
       </div> 

Reason:
handsontable.full.js, Line 9678:

         if (document.getElementById('CopyPasteDiv')) {
            this.elDiv = document.getElementById('CopyPasteDiv');
            this.elTextarea = this.elDiv.firstChild;
        }

If there is space or line return between 'div id="CopyPasteDiv"' and 'textarea', this space or line return will be interpreted as the firstChild and will fail for all Browsers.

Note: easy to check this, regarding the IE debug mode:
         Text - Empty Text Node

## Proposed Solution

         if (document.getElementById('CopyPasteDiv')) {
              this.elDiv = document.getElementById('CopyPasteDiv');
              // this.elTextarea = this.elDiv.firstChild;
              var textareas = this.elDiv.getElementsByTagName('textarea');
              this.elTextarea = textareas.length ? textareas[0] : null;
         }

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by burnash** [comment]
Had similar issue in Chrome 50.0.2661.94, Handsontable 0.15.1, and Bootstrap 3.3.5. @Gabriel-Lahyani solution fixed the problem.
