### ISSUE TITLE
Fix comments plugin issues

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#2522]
Increase stability (refactor) and fix this issues:

https://github.com/handsontable/handsontable/issues/2196
https://github.com/handsontable/handsontable/issues/2149
https://github.com/handsontable/handsontable/issues/2071
https://github.com/handsontable/handsontable/issues/1881
https://github.com/handsontable/handsontable/issues/1795
https://github.com/handsontable/handsontable/issues/1792

**Comment by krzysztofspilka** [comment]
Check for 0.15.0-beta4:

#2196 ok
#2149 ok
#2071 ok
#1881 ok
#1795 ok
#1792 ok

**Comment by krzysztofspilka** [comment]
Released in https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
