### ISSUE TITLE
Clicking a Dropdown in Rightmost Cell Adds Horizontal Scroll when stretchH: 'all'/'last'

### ISSUE THREAD

**Issue by kglaspey** [handsontable/handsontable#2523]
When the rightmost cell is a dropdown and stretchH is in use (either 'all' or 'last'), clicking on that dropdown adds an undesirable horizontal scroll bar. This scroll bar then disappears again when the dropdown is no longer expanded. 

This same issue also occurs for autocomplete cells.

Here's a JSFiddle (click on one of the "Bumper color" dropdowns to get the scroll bar): http://jsfiddle.net/v3pfpm1t/

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/1763 it describes the same behaviour. If you would like to describe it more, please write there.
