### ISSUE TITLE
LoadData doesn't work for single values

### ISSUE THREAD

**Issue by Codeguyross** [handsontable/handsontable#2524]
When I call loadData for two or more values then the table is reassigned properly. If I only have one value in the table and I call loadData then nothing happens. 

my table can have one or more cells but I need this case when it only has one cell to work.

Thanks!

**Comment by AMBudnik** [comment]
Please prepare a [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/) and we'll see wat we can do.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo.
