### ISSUE TITLE
[Help needed] Data source as object

### ISSUE THREAD

**Issue by MuyBien** [handsontable/handsontable#2525]
Hi,
I can't find the solution. It seems to be possible but I can't find. So I ask for some help.

I have my data like this
```
[[{"value":"246148"},
{"value":"value1","id":265,"otherData":246148,"lastData":"Sample"},
{"value":"1","id":266,"otherData":246148,"lastData":"Sample"},
{"value":"Non","id":261,"otherData":246148,"lastData":"Sample"},
{"value":"Positif","id":272,"otherData":246148,"lastData":"Sample"}],
[{"value":"246252"},
{"value":"value2","id":265,"otherData":246252,"lastData":"Sample"},
{"value":"1","id":266,"otherData":246252,"lastData":"Sample"},
{"value":"Non","id":261,"otherData":246252,"lastData":"Sample"},
{"value":"Positif","id":272,"otherData":246252,"lastData":"Sample"}]]
```

and my columns definition like this 
```
[{"data":0,"type":"text","readOnly":true},
{"data":1,"type":"text"},
{"data":2,"type":"dropdown","source":["0","1","2","3","4"]},
{"data":3,"type":"dropdown","source":["Non","Oui"]},
{"data":4,"type":"dropdown","source":["En cours","Positif","Négatif","Douteux","Echec"]}]
```

I would like to make a renderer (TDrenderer ?) that put in the cell the value as a string and id, otherData and lastData as data-attributes on the TD to be able to get them later.

I did a renderer like this :
```
tdRenderer : function(instance, td, row, col, prop, value, cellProperties) {
			Handsontable.TextCell.renderer.apply(this, instance, td, row, col, prop, value.value, cellProperties); 
			td.setAttribute('data-id', value.id);
			td.setAttribute('data-otherData', value.otherData);
			td.setAttribute('data-lastData', value.lastData);
		}
```
But the value in the renderer is a String "[Object object]"...
What I am doing wrong ?

Thanks to any help.

**Comment by AMBudnik** [comment]
Hi, give it a try with this

```js
renderer: function(instance, td, row, col, prop, value, cellProperties) {
  //Handsontable.TextCell.renderer.apply(this, instance, td, row, col, prop, value.value, cellProperties);
  td.setAttribute('data-id', value.id);
  td.setAttribute('data-otherData', value.otherData);
  td.setAttribute('data-lastData', value.lastData);
} 
```

You have to use custom renderer in this case cause text renderer forces all data to be parsed into string.

**Comment by MuyBien** [comment]
Hi !
My problem it's I want to keep the different type renderer. I have text, numeric, dropdown and checkbox but for all those types I want to add those data-attributes.
I saw a BaseRenderer but I can't figure out how it's working and if it will help me.
Another point I can't get value as an object. Without defining any type I get it in string. What type I need to specify to get an object ?

Thanks for your help.

**Comment by AMBudnik** [comment]
Hi @MuyBien do your still face the same issue? Sorry for a delayed answer.

**Comment by MuyBien** [comment]
Hi @AMBudnik I think yes but I just made something different for the moment, I can't remember how now...

**Comment by AMBudnik** [comment]
OK, thanks for your quick answer @MuyBien 
If there will be some other issues please create a new issue.
