### ISSUE TITLE
Copy/Paste doesn't work for multiple tables on the same page

### ISSUE THREAD

**Issue by Yaroslav-F** [handsontable/handsontable#2526]
Hi, thanks for your awesome plugin!

I've implemented handsontable in my current project, and on most of the pages (where there is only one table on the page) copy/pasting using Ctrl+C & Ctrl+V works just fine. But when it comes to multiple tables on the same page it just doesn't work :(
My code for creating tables in coffeescript is below:

    numericValidator = /^[0-9]{0,5}$/
    $('.excel_like_tables').each ->
      $table = $(this)

      headers = $table.data("headers")
      headers.push("Total")

      final_data = [$table.data("query")]
      final_data[0][final_data[0].length] = sumValues(final_data[0])

      columns_amount = $table.data("headers").length-1
      columns = []

      for n in [0..columns_amount-1]
        columns.push({ type: 'numeric', format: "0.[00000]", validator: numericValidator})
      columns.push({ type: 'text', readOnly: true })

      $table.handsontable({
        colHeaders: headers,
        data: final_data,
        stretchH: 'all',
        height: 100,
        copyPaste: true,
        # fillHandle: false,
        columns: columns,
        afterChange: (changes) ->
          if changes
            vals = $table.handsontable("getDataAtRow", 0)
            if changes[0][1] == (vals.length - 1)
              return
            vals.pop()
            total = sumValues(vals)
            $table.handsontable("setDataAtCell", 0, vals.length, total)
      })

PS: in coffeescript code I'm creating Total column dynamically, and change it dynamically when values in the table change, don't be confused with that :)

Can you provide a demo where there are multiple tables and copy/paste using ctrl+C / ctrl + V works fine?

**Comment by AMBudnik** [comment]
Hi @Yaroslav-F please update to 0.15.0-beta6 cause there was a little issue with copying in previous version. If you will still face the same issue with your code - please prepare a [JSFiddle](https://jsfiddle.net/api/post/library/pure/) demo for this topic.

**Comment by Yaroslav-F** [comment]
Thanks, @AMBudnik , this helped!
