### ISSUE TITLE
afterChange hook args are inconsistent for "external" source

### ISSUE THREAD

**Issue by engenb** [handsontable/handsontable#2527]
My afterChange hook callback is being invoked with arguments changes and source, where changes is an array [rowIndex, prop, oldVal, newVal] and source "external"

this does not follow the documented api where changes would be a 2D array and "external" is not a documented source.

**Comment by AMBudnik** [comment]
Hi, we have an issue for 'external' data source here https://github.com/handsontable/handsontable/issues/2163 Please track changes to this issue. We will add the information about only one array instead of two.
