### ISSUE TITLE
Copy/paste 1000

### ISSUE THREAD

**Issue by brivazac** [handsontable/handsontable#2528]
I select a whole colum and then i copy the content on the next column. 
Only the 1000 first rows have been copied.

**Comment by budnix** [comment]
Hi, maximum number of columns/rows than can be copied to clipboard is 1000. You can change this value in settings. See http://docs.handsontable.com/0.15.0-beta5/Options.html#copyColsLimit.

**Comment by brivazac** [comment]
Thanks a lot for this information.
