### ISSUE TITLE
Numeric type does not recognize numbers without leading zero

### ISSUE THREAD

**Issue by skalb** [handsontable/handsontable#2529]
See simple example here: http://jsfiddle.net/qxjasghh/

- 'a' is correctly recognized as invalid
- 0.5 works
- .5 is ignored

It looks like this is due to the isNumeric helper function:

Handsontable.helper.isNumeric("0.5") -> true
Handsontable.helper.isNumeric(".5") -> false

**Comment by AMBudnik** [comment]
You are right, it even does not work when `format: '.00',`

**Comment by deenairn** [comment]
This is also the source of my issue https://github.com/handsontable/handsontable/issues/2430. I've prepared a fix locally which is essentially a change to the regular expression within isNumeric. I won't be able to commit this to the repo for a couple of weeks so it will miss the next release.

**Comment by tikitikifoofoo** [comment]
+1 on this issue

**Comment by skalb** [comment]
As a workaround, I'm using a beforeChange hook to 'normalize' the input values

```coffeescript
beforeChange: (changes, sources) ->
  for change in changes
    if change[1] in [] # your numeric columns
      n = parseFloat(change[3])
      change[3] = n.toString() if n != NaN
```

**Comment by tikitikifoofoo** [comment]
Thanks @skalb
