### ISSUE TITLE
Ctrl+X/C/V regression since 0.15.0-beta3

### ISSUE THREAD

**Issue by mh2** [handsontable/handsontable#2530]
In Firefox (38.0.1) and Chrome (43.0.2357.81) on Windows 7, Copy-Paste using keyboard shortcuts (Ctrl-X, Ctrl-C and Ctrl-V) does not seem to work in 0.15.0-beta5. It works in 0.15.0-beta3.

**Comment by AMBudnik** [comment]
Hi @mh2 I tested this commands on http://handsontable.com/ (which has 0.15.0-beta5) (on Win7 and OSX) and it works fine. Do you face the same issue with http://handsontable.com/ ?

**Comment by ciffel** [comment]
I also faced the same issue with handsontable official website. (Chrome 43 on OSX)
When pressing ctrl-x at any cell, debug console will show `Uncaught ReferenceError: helper is not defined`.

It caused by `lib/copyPaste/copyPaste.js` line 137.
The helper need to be removed.
``` javascript
if (event.keyCode === helper.keyCode.X) {
      setTimeout(function () {
        _this.triggerCut(event);
      }, 0);

    } else if (event.keyCode === helper.keyCode.V) {
      setTimeout(function () {
        _this.triggerPaste(event);
      }, 0);
    }
```

**Comment by AMBudnik** [comment]
OK, we'll take a closer look at this one.

**Comment by MuyBien** [comment]
I have the same problem with Chrome 43 on W8.1. I go back to beta3 and works fine.

**Comment by AMBudnik** [comment]
On Chrome 42/OSX worked fine on my device with Chrome 43 it does not.

**Comment by jansiegel** [comment]
@mh2, @ciffel, @MuyBien, thanks a lot for reporting this - we've just released a fix for this as [0.15.0-beta6](https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta6)

**Comment by MuyBien** [comment]
Thanks it's working again with the beta6 ;)

**Comment by jansiegel** [comment]
Muy bien! :)

**Comment by mh2** [comment]
Latest build is working again on my side too. Thank you for fixing this so quickly! :-)

**Comment by MuyBien** [comment]
;)
