### ISSUE TITLE
Issue with fixed row and rowspan when rowheader and colHeader is set to false ( demo link included )

### ISSUE THREAD

**Issue by Atulchirame** [handsontable/handsontable#2531]
I have scenario where

    rowHeaders: false,
    colHeaders: false,
    fixedRowsTop: 2,
    fixedColumnsLeft: 2,
    mergeCells: [
      {row: 0, col: 0, rowspan: 2, colspan:2},
     
    ]

There is issue with this setting for fixed rows and merge cells.
Fixed rows and merge cells are messed up.

live examle - 
http://jsfiddle.net/atulchirame/uth6122m/

Scroll vertical scroll-bar and observe cells at 0,0 position( it should be rowspan: 2, colspan:2)

Any idea why this is happening ? 
Any suggestions will be greatly helpful.

**Comment by AMBudnik** [comment]
Indeed the A1 has not taken the `rowspan: 2` settings and fixed rows aren't fixed in right way. 
Thank you for that report @Atulchirame

**Comment by AMBudnik** [comment]
Confirmed with [simplified 0.17.0 version example](https://jsfiddle.net/x19muu8g/) 
* works fine when where are `rowHeaders` turned on

**Comment by AMBudnik** [comment]
Same issue as https://github.com/handsontable/handsontable/issues/2672#issuecomment-197368098 just for other axis.

**Comment by Fei-Fly** [comment]
Is this bug fixed now?  we can't set the rowheaders true!

**Comment by AMBudnik** [comment]
Hi @Fei-Fly 

we have merged the issue with https://github.com/handsontable/handsontable/issues/2672
