### ISSUE TITLE
minimum column header width doesn't allow space for sort inidcator

### ISSUE THREAD

**Issue by engenb** [handsontable/handsontable#2533]
the th class needs to account for space to render the sort indicator

http://jsfiddle.net/x6akp8rn/1/

**Comment by AMBudnik** [comment]
As far as you typed `sortIndicator: true` the indicator should appear. Thank you for support.

**Comment by jregan** [comment]
Not sure if it's clear but if you look at the first table in the fiddle, once the Column header is selected to sort, the sort indicator to the right of the text is cut off due to the minimum column header sizing.

**Comment by JacobEvelyn** [comment]
I'm running into this issue as well.

**Comment by AMBudnik** [comment]
This issue is not yet released so please stay tuned for more information.

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1.

**Comment by AMBudnik** [comment]
works as expected in 0.26.0 http://jsfiddle.net/fo7ss9bo/
Can you check it @engenb @jregan @JacobEvelyn ?

**Comment by zbjornson** [comment]
@AMBudnik this doesn't appear to be fixed. In the fiddle that you posted, it looks like you've manually set the `colWidths` to 100 on line 7. If you remove that (as in the original fiddle), the issue remains.

**Comment by AMBudnik** [comment]
Thanks for spotting that @zbjornson 
I'm reopening the issue, here's an updated example: http://jsfiddle.net/p9wafmbk/

**Comment by AMBudnik** [comment]
Still replicable in v0.34.0

**Comment by swistach** [comment]
Hi @engenb, @jregan, @JacobEvelyn, @zbjornson,
I've prepared a temporary solution: http://jsfiddle.net/h2Lsa6p4/
A final solution is not scheduled in the near future, because it is related to rewrite a big part of the plugin (ColumnSorting).

**Comment by AMBudnik** [comment]
Thanks @swistach

**Comment by AMBudnik** [comment]
Still looks the same in version 0.35.1

**Comment by AMBudnik** [comment]
The issue is still replicable in v `2.0.0.`. Updated and simplified demo http://jsfiddle.net/7xwjgwrx/. This issue is old. It doesn't seem to work in any of previous versions of Handsontable.

**Comment by phoenix-down** [comment]
It appears that this is still an issue in v3.0.0.

**Comment by AMBudnik** [comment]
Hi @engenb please update to v`6.0.1`. Now it should work as expected. We've refactored the columnSorting, added some new method and functionalities.

@phoenix-down @zbjornson @JacobEvelyn @jregan
