### ISSUE TITLE
value formatting in cells

### ISSUE THREAD

**Issue by debarko** [handsontable/handsontable#2536]
Hi, I just wanted to know if it is possible to format a value before showing in a cell. For eg: I have Male and Female gender and I store them in db in 0 and 1. In the front end I would like to replace them with the the text like Male, Female. Also I have dob which is a datetime in mysql. I want to format it in some more pleasant format before showing in the table. Also these values can get modified so need to store them back in 0,1 or datetime format. Any easy way to do this other than using a renderer and changing the value itself.

**Comment by AMBudnik** [comment]
Hi @debarko for questions that are not related to Handsontable bugs, please create a topic with a `handsontable` tag in [stackoverflow](https://stackoverflow.com/search?q=handsontable)
