### ISSUE TITLE
Problem copy/paste with comma separator

### ISSUE THREAD

**Issue by Hazepusik** [handsontable/handsontable#2539]
In version v0.15.b6 with columns setings like:

columns: [
      {
        data: 'data',
        type: 'numeric',
        format: '0.00',
        language: 'de'
      }
]

where 'de' uses comma as separator i have problems with copy/paste values in format like 0,1234.

After pasting value '0,1234' it converts to '1234,00'.

There is no problem with pasting data with two or less signs after comma (values like '0,12').

UPD: same problems with numbers greater 1 (1,23 -> 123,00)

Any idea about reasons?

I look forward to your reply.

**Comment by AMBudnik** [comment]
Can you try [this example](https://jsfiddle.net/4m8z3vfj/). I made the same settings as you described but after copying `0,1234` i get `0,12` as I should with `format: '0.00'`.

**Comment by Hazepusik** [comment]
The same example:

![dec_sep](https://cloud.githubusercontent.com/assets/1913529/8053495/ece6f278-0e99-11e5-829d-6835a695086f.gif)

**Comment by AMBudnik** [comment]
Yes, you are right. Coma changes it's position after copying. Thank you for that report.

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/2166
