### ISSUE TITLE
getting read only status

### ISSUE THREAD

**Issue by ruipedromachado** [handsontable/handsontable#2541]
Hi guys,

I cant find anywhere how to get which cells are currently read only.
demos show how to set them, but if I give user option to mark has read only in the content menu, I need to save the user choosing's.

thanks in advanced
rui

**Comment by AMBudnik** [comment]
Hi @ruipedromachado you are looking for `getCellMeta`, please look at [this example](https://jsfiddle.net/amj22a0m/)

**Comment by ruipedromachado** [comment]
fantastic, exactly what I needed.
