### ISSUE TITLE
Examples are not working on Android and iOS

### ISSUE THREAD

**Issue by slavap** [handsontable/handsontable#2542]
I'm looking at http://handsontable.com/examples.html
Scroll is not working on tablets (Android 4.4 and iOS 8.3). So I've got an impression that handsontable is not designed/usable for touch devices. Though I see few closed issues related to touch devices problems.
The question is: is it problem of examples page only or it's global/unresolvable problem of handsontable itself?

**Comment by AMBudnik** [comment]
Hi @slavap other issue related to Android and iOS devices was https://github.com/handsontable/handsontable/issues/3 which was closed as a feature request.
I'm on my iPad mini with 8.3 and examples are working fine.
Touch support is described in https://github.com/handsontable/handsontable/issues/1455 issue which is also a feature request. All feature requests are now at our wiki: [wiki/Feature-requests](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by slavap** [comment]
What do you mean by working fine? Try to scroll down and you cannot go any further than line 27, though there are many more lines. And behavior is the SAME on iOS 8.3 and Android 4.4, so examples are not working for sure.

**Comment by AMBudnik** [comment]
OK, we have to check it on other devices.

**Comment by averdesca** [comment]
I have similar issues with Android (I have tested in various devices with different os versions).  When I try to scroll, I see a partial number of rows. If I click on a cell of the last row shown, the table loads some other rows.

**Comment by surfer26th** [comment]
I have the same problem in horizontal scroll on ipad (ios 8.4) with Safari when number of columns is greater than around 20. I also observe the same behavior as described by slavap and AMBudnik when viewing the handsontable examples (Basic, Advanced, etc) and doing a vertical scroll and suing Safari. Using Chrome on ios 8.4 seems to work fine.

**Comment by Gaya** [comment]
:+1: Would love to see support for Android devices. iOS seems to be working though.

**Comment by surfer26th** [comment]
As averdesca commented back in June of 2015, changing your mobile browser settings to "Request Desktop Site" works in Safari, Chrome, and Firefox on my iPad (verified using ios 10.2). This seems to be an unacceptable workaround for the scrolling issue, at least for me, and should be highlighted to users.

**Comment by AlbinoDrought** [comment]
I've come across this same issue myself and was surprised when it started working with "Request Desktop Site" enabled.

It seems to be related to this area of code (specifically, return if isMobileBrowser):

```
  onTableScroll: function(event) {
    if (isMobileBrowser()) {
      return;
    }
    var masterHorizontal = this.leftOverlay.mainTableScrollableElement;
    var masterVertical = this.topOverlay.mainTableScrollableElement;
    var target = event.target;
    if (this.keyPressed) {
      if ((masterVertical !== window && target !== window && !event.target.contains(masterVertical)) || (masterHorizontal !== window && target !== window && !event.target.contains(masterHorizontal))) {
        return;
      }
    }
    if (event.type === 'scroll') {
      this.syncScrollPositions(event);
    } else {
      this.translateMouseWheelToScroll(event);
    }
  },
```

**Comment by minipai** [comment]
Just want to add a note that this problem can replicate by using mobile mode in Chrome.
<img width="528" alt="screen shot 2017-05-27 at 3 53 38 pm" src="https://cloud.githubusercontent.com/assets/239570/26518491/f747e394-42f4-11e7-8031-7f948c546c81.png">

**Comment by AMBudnik** [comment]
The issue will be reopened with #3
