### ISSUE TITLE
Question: Knockout.js support?

### ISSUE THREAD

**Issue by showdep** [handsontable/handsontable#2544]
HI, I couldn't find any implementation of Knockout.js binding that works with recent versions of HT. 

The idea is to use KO data-bind in the markup as follows:
<_div id="data_grid" data-bind="handsontable: data" style="overflow-y:visible;"></_div>'
and the "handsontable" binding for KO added like this:
$(document).ready(function() {
        ko.bindingHandlers.handsontable = {...}
});

A while ago, this hack (http://jsfiddle.net/NHpEH/) worked for me, but, apparently, a lot of things has changed in HT.

Before I dig deeper into that and spend time creating the KO binding for HT myself, I would like to make sure I am not re-inventing the wheel. Could you please point me in the right direction? Any plans to include the KO binding in the HT distribution?

UPDATE: Ok, it looks like this snippet - http://jsfiddle.net/x3ejL/98/ - works (basic functionality at least) with the latest HT after fixing the obvious issue with non-existing reference to http://handsontable.com/lib/jquery.min.js. Still, are you guys planing to develop an "official" KO binding?
 
Thanks a lot,
s

**Comment by AMBudnik** [comment]
For questions that are not strict related to Handsontable bugs, please create a topic at [stackoverflow](https://stackoverflow.com/search?q=handsontable) with a `handsontable` tag.
We try to keep github as a place where user's can report a bug.
