### ISSUE TITLE
Copy/Paste doesn't work with Ruby on Rails Turbolinks

### ISSUE THREAD

**Issue by Yaroslav-F** [handsontable/handsontable#2545]
Hey, guys,

So, I'm using beta 6 version, the copy/paste works fine except one case - the Rails Turbolinks. If I was navigated to the page with handsontable table through the turbolinks the table works fine, but copy/paste feature doesn't work. Copy/Paste feature will work only after page refresh (without turbolinks).

Is there any chance to see this fixed?

**Comment by shaun27stars** [comment]
+1 

The copy paste plugin needs to be reinitialised after page load, I think.

I've worked around it by commenting out the conditional block on lines 17326 - 17331, instead just initialising a new instance every time

    // if (!instance) {
      instance = new CopyPasteClass();
    // } else if (instance.hasBeenDestroyed()) {
    //   instance.init();
    // }

I can paste into multiple tables before and after triggering a Turbolinks page load, so it works well enough for my purposes.

**Comment by Yaroslav-F** [comment]
Thanks, @shaun27stars , works like a charm!
