### ISSUE TITLE
Can't use Ctrl + cmd  in a cell edit box.

### ISSUE THREAD

**Issue by kquinn45** [handsontable/handsontable#2546]
Can't use Ctrl + cmd  in a cell edit box.

**Comment by AMBudnik** [comment]
Can you specify what this shortcut should be doing?

**Comment by kquinn45** [comment]
I need to append text to cells.

**Comment by AMBudnik** [comment]
Please update o 0.15.0, it should work fine now.

**Comment by kquinn45** [comment]
Thanks!  This works great!

**Comment by AMBudnik** [comment]
Great. Thanks for feedback.
