### ISSUE TITLE
Sorting with fixedRows and merged

### ISSUE THREAD

**Issue by cbetech** [handsontable/handsontable#2547]
Hey, im sorting a table with fixedRows and fixedCols (2 and 2, in my case), and this issue is ok, i changed it manually, but there is another problem, when the sort is done, the merged cells still in the same position.

Look at my table (ignore the row Totales, it doesn'
![original](https://cloud.githubusercontent.com/assets/4923475/8139680/33482f9c-111b-11e5-85b6-875cf1e8c11e.png)
![sorted](https://cloud.githubusercontent.com/assets/4923475/8139681/335b7750-111b-11e5-8b16-91a63f85f66d.png)

t change)

**Comment by AMBudnik** [comment]
Can you please prepare an example showing this situation? Thanks in advance.

**Comment by cbetech** [comment]
https://jsfiddle.net/baqmp5eL/ let me know if there's a problem with the link please :)

**Comment by AMBudnik** [comment]
I see what you mean but unfortunately there's not an option to sort data with rowspan included at [2197](https://github.com/handsontable/handsontable/issues/2197) was a similar topic with sorting data in fixed rows. Only thing I can do is add this proposition as a feature request.

**Comment by cbetech** [comment]
the only thing you need to do is unmerge that cell (country cell), how can I do that? Thanks

**Comment by AMBudnik** [comment]
Hi, if you still face this problem kindly leave me a feedback with your updated code.

**Comment by cbetech** [comment]
Hi, you can check the code in the fiddle, please let me know, thanks

**Comment by AMBudnik** [comment]
We will have to take a closer look at this issue.

**Comment by AMBudnik** [comment]
Hi @cbetech could you check it with the latest version? I should not occur since 0.23.0
