### ISSUE TITLE
Please expose translateRow and untranslateRow

### ISSUE THREAD

**Issue by belg4mit** [handsontable/handsontable#2548]
There are lots of tests that must be done in addition to simply using the index table, to verify that a lookup should be performed. Since this and other code already exists in the toolkit, it seems silly to require users to replicate it.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
