### ISSUE TITLE
Select row with checkbox without affecting undo/redo

### ISSUE THREAD

**Issue by richtier** [handsontable/handsontable#2549]
There is a [demo](https://github.com/handsontable/handsontable/wiki/FAQ#how-to-put-a-master-checkbox-in-the-column-header) for adding a "checkbox column". I'm using this to allow users to select multiple columns, and perform an action on these selected rows.

However, the undo/redo functionality kicks in when the user ticks the box because the datastructure is changed when the checkbox is ticked.

I had a look in the source code and I can't see how prevent undo/redo from being triggered when the checkboxes are ticked.

Is there a built-in way to do this?

**Comment by AMBudnik** [comment]
Unfortunately there is not an built-in option for this functionality.
