### ISSUE TITLE
Alt key not working

### ISSUE THREAD

**Issue by Remo** [handsontable/handsontable#2550]
I searched through all issues as I thought this would have caused problem to others but I haven't found anything, maybe I just searched in the wrong way.

On my Swiss keyboard the character `#` can be written using `Alt + Ctrl + 3` or `AltGr + 3`. However, anything with Alt in it can't be typed, nothing happens. Tested using  15.0-beta6.

**Comment by AMBudnik** [comment]
In polish language there are few letters that need <kbd>alt</kbd> and they can be typed, but we we'll take a closer look at keycodes.

**Comment by Remo** [comment]
This is strange, it works from time to time, but then it suddenly stops working. Maybe a timing issue? I can reproduce this with chrome and firefox, haven't tested other browsers.

**Comment by budnix** [comment]
I can reproduce similar issue (maybe the same). When I go to the [example](https://handsontable.com/examples.html?headers) page and try to directly enter value (eg <kbd>ALT</kbd>+<kbd>o</kbd> - polish `ó`) into selected cell then only first letter is appears. It seams like after entering first letter editor loosing focus.

This issue occurs only in Windows machine (OSX and Linux is fine).

**Comment by budnix** [comment]
Still present in 0.27.0. Occurs only on Windows machine (vm).

**Comment by AMBudnik** [comment]
After updating to v0.30.1 this issue is gone.
