### ISSUE TITLE
What is the release date of 0.15.0 stable version ?

### ISSUE THREAD

**Issue by csdpuneteam1** [handsontable/handsontable#2551]
I did not find any other place to ask this question , sorry about that

**Comment by AMBudnik** [comment]
Please track changes to our milestones [handsontable/milestones](https://github.com/handsontable/handsontable/milestones). Estimated date for 0.15.0 is 18th of June. Please remember that the date can vary depending on amount and weight of issues.

**Comment by csdpuneteam1** [comment]
Thank you !
