### ISSUE TITLE
Autocomplete cells inside grouped rows issue

### ISSUE THREAD

**Issue by dasaevc** [handsontable/handsontable#2552]
Using the version 0.14.1

I need to use the autocomplete feaure inside some cells, those cells belong to rows that are grouped. When the rows are grouped and I click in the dropdown for editing the value of an autocomplete cell, the list is shown but the group columns are displayed messy and then the spreadsheet is freezed and stop to work.

Sample of this issue can be found here: http://jsfiddle.net/9e0zog7w/2/

The debugger of chrome shows the error:
Uncaught TypeError: Cannot read property 'modifyRowHeight' of undefined

The issue is thrown in the file handsontable.full.js, line 18366, which basically is trying to execute the Method modifyRowHeight of Handsontable.Grouping, but before, the line 18353 of the same file is executed and then property Handsontable.Grouping is set to null.

**Comment by qualdevankit** [comment]
I have the same issue  with Autocomplete cell using grouping in handsontable.

**Comment by dasaevc** [comment]
Because I'm using a CDN, I cannot modify directly the code; so, what I did was to extend the Handsontable.editors.AutocompleteEditor in order to send the groups in the settings, this solved my issue.

You can see an example here: http://jsfiddle.net/9e0zog7w/6/

**Comment by ankitddit** [comment]
Thank you very much this helps a lot. 

Do you know How to fix the row height ? the problem I am facing is that If I have a long text in Autocomplete cell , it increases the cell height and my freeze column panel misaligned with rest of the other column..

**Comment by gjoshevski** [comment]
+1 Thank you!

**Comment by AMBudnik** [comment]
Grouping abbanoded according to https://github.com/handsontable/handsontable/releases/tag/0.18.0
Instead, we're working on a very similiar functionality - Nested Rows

**Comment by AMBudnik** [comment]
Update: grouping will no longer be supported from 0.19.0
