### ISSUE TITLE
Insert/remove row context menu commands are unavailable when table has only one row

### ISSUE THREAD

**Issue by dchekanov** [handsontable/handsontable#2555]
Demo: http://jsfiddle.net/keleran/txr6r17h/ , plugin is linked from http://handsontable.com/bower_components/handsontable/dist/handsontable.full.js.

There is only one row in the table. Right click on that row will bring up context menu, where 'Insert row above/below' and 'Remove row' are unavailable. After adding another row in the 'data' property, those commands become available. I believe those command should be available when there is only one row as well.

**Comment by AMBudnik** [comment]
Thank you @dchekanov for support but this issue is duplicated in https://github.com/handsontable/handsontable/issues/1853 so please track changes to https://github.com/handsontable/handsontable/issues/1853
