### ISSUE TITLE
Cannot Pass Data From HandsOnTable in View to Controller

### ISSUE THREAD

**Issue by JDarling87** [handsontable/handsontable#2556]
I am having an issue getting my data in my table in my View to my Controller (I am using Razor in the view and ASP.NET in the Controller). This is my HTML with Razor:

    <script src="http://handsontable.com/dist/handsontable.full.js"></script>
    <link rel="stylesheet" media="screen" href="http://handsontable.com/dist/handsontable.full.css">
    <div id="example"></div>

    <script>

        var defaultTable = [
          ["Origin Label", "Origin Zip", "Origin Point Shape", "Origin Point Color", "Destination Label", "Destination Zip",
              "Destination Point Shape", "Destination Point Color", "Line Color", "Line Width"]
        ];

        for (i = 0; i < 9; i++) {
            defaultTable.push([" ", " ", " ", " ", " ", " ", " ", " ", " ", " "]);
        }

        var container = document.getElementById('example');
        var userInput = new Handsontable(container, {
            data: defaultTable,
            minSpareRows: 1,
            rowHeaders: true,
            colHeaders: true,
            contextMenu: true
        });

        function compile() {
            var userInputsJS =[];
            for (i = 1; i < 25; i++) {
                for (k = 1; k < 12; k++) {
                    if (userInput.getDataAtCell(i, k) == null) {
                        userInputsJS.push(0);
                    }
                    else {
                        userInputsJS.push(userInput.getDataAtCell(i));
                    }
                }
            }

        };
    </script>

    <div>
        <br /><br/>
        <input type="hidden" id="userINputJS" name="userInputJS" value='<%this.userInputJS%>'/>
        <input type="button" value="Compile" onclick="javascript:compile()">
        <input type="button" value="Submit" onclick="location.href='@Url.Action("TableTest")'">
    </div>

And this is my Controller:

        public void TableTest()
        {
            List<char> tableData = new List<char>();
            tableData = (Request.Form["userInputJS"]).ToList();
        }

The controller is a little incomplete, but I'm really just looking for a way to get my data into the controller so I can manipulate. Any help would be greatly appreciated!

**Comment by AMBudnik** [comment]
As long as your issue has nothing to do with a Handsontable bug, please create a topic at [stackoverflow with `handsontable` tag](https://stackoverflow.com/search?q=handsontable).
We are trying to keep github a place to report code issues.
