### ISSUE TITLE
Can't resize column smaller than column header

### ISSUE THREAD

**Issue by docmattman** [handsontable/handsontable#2557]
My column headers are alphabetical (A, B, C, D, etc...).  I am trying to resize the column to be smaller than the header letter.  I can drag it smaller, but when I let the drag handle go, it resizes itself to fit the column header letter width.  Is there a way to allow a smaller column width than the header letter?

**Comment by AMBudnik** [comment]
You can use `colWidths` like in [this example](https://jsfiddle.net/869c0agg/) where there are (A, B, C, D) headers also.

**Comment by docmattman** [comment]
The fiddle doesn't work.  However, even if it did, the colWidths wouldn't help me.  I am using the column resizeable feature and I want the user to be able to drag the column width smaller than the header.  I don't want to predefine the width for them.  They need to be able to adjust the width by themselves.

**Comment by docmattman** [comment]
This same issue applies to row heights.  The user can't drag to make the height of the row smaller than the header number.

Any advice on fixing this?  Sometimes I want the columns and rows to only be a few pixels in size (i.e. when using as a spacer).  As I mentioned previously, I want the user to be able to resize the columns/rows to be smaller, not just predefine the sizes.

**Comment by budnix** [comment]
I think that can be a bug. Conflict beetwen AutoResize and ManualColumnResize/ManualRowResize plugin.

**Comment by budnix** [comment]
In released version (0.16.0) you can now shrink column smaler then header size (but no smaller then 25px). See updated demo at https://jsfiddle.net/869c0agg/1/
