### ISSUE TITLE
Vertical scroll bar at bottom of the table

### ISSUE THREAD

**Issue by manig84** [handsontable/handsontable#2558]
We need while Initially handsontable loaded vertical scroll should be at end of the table. Because we have large number of records. So we can't scroll to see the last records.

Please help me ASAP.

**Comment by AMBudnik** [comment]
Maybe you could try to use `selectCell` for the last cell in your data

**Comment by manig84** [comment]
$('#myGridID').handsontable('selectCell', row1, col1, row2, col2, scrollToSelection = true)

It's working, Thanks for your quick response.
