### ISSUE TITLE
Can't scroll to the left/top when row headers are enabled

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2560]
It should be easy to scroll within the table using mouse pointer just like in MS Excel of Google Spreadsheet. At the moment it works badly if the mouse pointer is being moved over the row/col header or beyond the viewport.

**Steps to reproduce the problem:**
1. Scroll to the middle of relatively big table
2. Select any cell and hold mouse down
3. Try to enlarge the selection using mouse movement

:information_source:

> Handsontable v. 0.15.0-beta6
> Windows 8.1
> Chrome (latest)

![94c958f32488823789919f4c39ef476c](https://cloud.githubusercontent.com/assets/8048526/8195785/989e2c76-1485-11e5-99f6-a269d038bcd8.gif)

![top](https://cloud.githubusercontent.com/assets/8048526/8195832/eb9d3d9a-1485-11e5-9d88-807dac884f0b.gif)

**Comment by jansiegel** [comment]
The scrolling seems to work fine, the glitches concerning the selection being misplaced while scrolling need fixing, though.

**Comment by krzysztofspilka** [comment]
It seems that the selection doesn't scroll the table at all now

**Comment by krzysztofspilka** [comment]
Excluded from the release 0.18.0

**Comment by jansiegel** [comment]
> numerous bugs found there

@krzysztofspilka, could you list them?

**Comment by AMBudnik** [comment]
Currently when we only use mouse movements it's doesn't work as expected.
![o6](https://cloud.githubusercontent.com/assets/10757813/22145058/1f6a6878-df00-11e6-99ac-98c38a66bc44.gif)

 however if we use scroll and <kbd>SHIFT</kbd> + scroll it works perfectly
![o8](https://cloud.githubusercontent.com/assets/10757813/22145063/21779a14-df00-11e6-9802-e02b7b0eba19.gif)

**Comment by AMBudnik** [comment]
In the v0.35.0 the behavior remains pretty much the same as shown in my last post

**Comment by AMBudnik** [comment]
The issue is no longer replicable in the original scenario in the latest version. A demo for tests https://docs.handsontable.com/pro/2.0.0/demo-scrolling.html (v`2.0.0`)
