### ISSUE TITLE
TypeError while using event.x/y

### ISSUE THREAD

**Issue by Maxi7** [handsontable/handsontable#2561]
in Firefox when I activate Firebug, I got following error message:

on line 34 in handsontable.full.min.js (version:"0.15.0-beta6):
TypeError: Argument 1 of Document.elementFromPoint is not a finite floating-point value.                 
(it's the line 16656 in the non-min version)

This eror message does not occurs if I replace event.x and event.y with event.clientX and event.clientY . 
You can check this on the "officially" [Handsontable page](http://handsontable.com/examples.html#fndtn-basic) 
You can provoke this error by clicking on the scroll bar.

**Comment by Maxi7** [comment]
PS: you can provoke this error by clicking on the scroll bar.

**Comment by AMBudnik** [comment]
Thank you for that report.
