### ISSUE TITLE
Using handson table in asp.net MVC5

### ISSUE THREAD

**Issue by brinegjr** [handsontable/handsontable#2562]
I am currently trying to use handsontable in a project in Visual Studio under the asp.net MVC5 framework.  The table is fine when it does not have any fixed columns  or rows, but once added, the part of the table that is not fixed is not aligned properly with the fixed portion of the table.  All row heights and column widths are set to fixed values and it does not fix the problem if the heights and widths are changed, it just appears as if the non-fixed portion is not in the proper place.
![fixed_column_problem](https://cloud.githubusercontent.com/assets/11012036/8215150/283054a6-14fc-11e5-8d80-6895a24058ed.png)

It is only after I entered the code into Visual Studio that it started to do this.  As a static HTML document it worked fine.  Has anyone encountered this problem before and know how to fix it?

**Comment by AMBudnik** [comment]
If it only occurs with Visual Studio I encourage you to try create a new topic at [stackoverflow with `handsontable` tag](https://stackoverflow.com/search?q=handsontable). Github is more a place to report Handsontable code issues.
