### ISSUE TITLE
Need to integrate After change on the code below please help

### ISSUE THREAD

**Issue by kvnandini** [handsontable/handsontable#2565]
$(document).ready(function () {

 var container = document.getElementById('personal_example');
  
  var headerRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
   // td.style.backgroundColor = '#BDD7EE';
    td.style.fontWeight = 'bold';
    td.style.textAlign = 'center';
  };
  
  var diffRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.cellTypes['formula'].renderer.apply(this, arguments);
    td.style.backgroundColor = '#BDD7EE';
    td.style.fontWeight = (col === 11 ? 'bold' : 'normal');
  };
  
  var incomeOrExpensesRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.fontWeight = 'bold';
    td.style.textAlign = 'left';
    td.style.backgroundColor = '#BDD7EE'
  };
  
  var boldAndAlignRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.fontWeight = 'bold';
    td.style.verticalAlign = 'middle';
    td.style.textAlign = 'left';
  };
  
  
  var personalData = [
    ["INNOVATION YEAR","","","","","","","","","",""],//ROW 0
    ["","","","","","","","","","","",""],//ROW 1
    ["","GROSS P&L","","","","","INCREMENTAL P&L","","","",""],//ROW 2
    ["Y0","Y1","Y2","Y3","Y4","Y5","Y1","Y2","Y3","Y4","Y5"],//ROW 3
    ["","","","","","","","","","","",""],// ROW 4
    ["","","","","","","","","","","",""],// ROW 5
    ["","","","","","","","","","","",""],//ROW 6
    ["","","","","","","","","","","",""],//ROW 7
    ["","","","","","","","","","","",""],//ROW 8
    ["","","","","","","","","","","",""],//ROW 9
    ["","","","","","","","","","","",""],//ROW 10
    ["","","","","","","","","","","",""],//ROW 11
    ["","","","","","","","","","","",""],//ROW 12
    ["","","","","","","","","","","",""],//ROW 13
    ["","","","","","","","","","","",""],//ROW 14
    ["","","","","","","","","","","",""],//ROW 15
    ["","","","","","","","","","","",""],//ROW 16
    ["","","","","","","","","","","",""],//ROW 17
    ["","","","","","","","","","","",""],//ROW 18
    ["","","","CAPEX","","","","","","","",""],//ROW 19
    ["","","","BIC","","","","","","","",""],//ROW 20
    ["","","","","","","","","","","",""],//ROW 21
    ["","","","","","","","","","","",""],//ROW 22
    ["","","","","","","","","","",""],//ROW 23
    ["CALENDAR YEAR","","","","","","","","","","",""],//ROW 24
    ["","","","","","","","","","",""],// ROW 25
    ["","GROSS P&L","","","","","INCREMENTAL P&L","","","",""],//ROW 26
    ["Y0","Y1","Y2","Y3","Y4","Y5","Y1","Y2","Y3","Y4","Y5"],//ROW 27
    ["","","","","","","","","","","",""],//ROW 28
    ["","","","","","","","","","","",""],//ROW 29
    ["","","","","","","","","","","",""],//R0W 30
    ["","","","","","","","","","","",""],//ROW 31
    ["","","","","","","","","","","",""],//ROW 32
    ["","","","","","","","","","","",""],//ROW 33
    ["","","","","","","","","","","",""],//ROW 34
    ["","","","","","","","","","","",""],//ROW 35
    ["","","","","","","","","","","",""],//ROW 36
    ["","","","","","","","","","","",""],//ROW 37
    ["","","","","","","","","","","",""],//ROW 38
    ["","","","","","","","","","","",""],//ROW 39
    ["","","","","","","","","","","",""],//ROW 40
    ["","","","","","","","","","","",""]//ROW 41
    ];
  
var hot = new Handsontable(container, {
    data: personalData,    
    height: 1000,
    fixedRowsTop: 1,
    colHeaders: false,
    rowHeaders: false,
    maxCols: 11,
    maxRows:42,
    formulas: true,
    comments: true,
    colWidths: [65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65],
    
    cells: function (row, col, prop) {
      var cellProperties = {};
      
      if (row === 0) {
        cellProperties.renderer = headerRenderer;
      } else if (row === 2) {
        cellProperties.renderer = headerRenderer;
      }else if (row === 3) {
        cellProperties.renderer = headerRenderer;
      }else if (row === 24) {
        cellProperties.renderer = headerRenderer;
      }else if (row === 26) {
        cellProperties.renderer = headerRenderer;
      }/*else if (row === 12) {
        cellProperties.renderer = diffRenderer;
      } else if (row === 12) {
        cellProperties.renderer = incomeOrExpensesRenderer; }*/
      else if (row === 14) {
        cellProperties.renderer = boldAndAlignRenderer;
      } else if (row === 21) {
        cellProperties.renderer = boldAndAlignRenderer;
      } else if (row === 27) {
        cellProperties.renderer = boldAndAlignRenderer;
      } else if (row === 36) {
        cellProperties.renderer = boldAndAlignRenderer;
      }
      
      if ([0,1, 2, 3, 14,18,22,23,24,25,26,27,38].indexOf(row) !== -1 && col >= 0) {
        cellProperties.readOnly = true;
      }
      
      
      
     /* if ([1, 2, 3, 6, 7, 8, 9, 10, 11, 16, 17, 18, 19, 20, 23, 24, 25, 26, 29, 30, 31, 32, 33, 34, 35, 38, 39, 40, 41, 42].indexOf(row) !== -1 && col >= 1) {
        cellProperties.type = 'numeric';
        cellProperties.format = '$0,0.00';
      }*/
      
      return cellProperties;
    },
    mergeCells: [
      {row: 0, col: 0, rowspan: 1, colspan: 11},
      {row: 1, col: 0, rowspan: 1, colspan: 11},
      {row: 2, col: 1, rowspan: 1, colspan: 5},
      {row: 2, col: 6, rowspan: 1, colspan: 5},
      {row: 14, col: 0, rowspan: 1, colspan: 11},
      {row: 18, col: 0, rowspan: 1, colspan: 11},      
      {row: 19, col: 5, rowspan: 1, colspan: 6},      
      {row: 20, col: 5, rowspan: 1, colspan: 6},
      {row: 21, col: 3, rowspan: 1, colspan: 8},
      {row: 22, col: 0, rowspan: 2, colspan: 11},
      {row: 23, col: 0, rowspan: 1, colspan: 11},
      {row: 24, col: 0, rowspan: 1, colspan: 11},
      {row: 25, col: 0, rowspan: 1, colspan: 11},
      {row: 26, col: 1, rowspan: 1, colspan: 5},
      {row: 26, col: 6, rowspan: 1, colspan: 5},
      {row: 38, col: 0, rowspan: 1, colspan: 11},
    ]
  });
  
 
  
});

**Comment by AMBudnik** [comment]
Please prepare a demo and describe what afterChange should do.

**Comment by kvnandini** [comment]
AMBudnik, thanks for the reply here is my demo AMBudnik, when user pastes or edit i need to capture each cell value. Can you please help me with this. Changes is a 2D array [row,prop,oldVal,newVal]
I am looking for a way to get newVal from the changes array based on the row and column.
I need to match each cell to a field in my CRM system,
