### ISSUE TITLE
grunt-hot-builder has disappeared from git

### ISSUE THREAD

**Issue by deenairn** [handsontable/handsontable#2566]
It appears that the grunt-hot-builder has disappeared from git making it impossible to build the latest version of the project.

	npm WARN addRemoteGit Error: not found: git
	npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:72:28)
	npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:75:29)
	npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:83:16
	npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:95:15)
	npm WARN addRemoteGit  git://github.com/handsontable/handsontable.git resetting	remote C:\Users\XXX\AppData\Roaming\npm-cache\_git-remotes\git-github-com-handsontable-handsontable-git-3fe9b850 because of error: { [Error: not found:	 git] code: 'ENOGIT' }
	npm ERR! git clone --template=C:\Users\XXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/handsontable/handsontable.git C:
	\Users\XXX\AppData\Roaming\npm-cache\_git-remotes\git-github-com-handsontable-handsontable-git-3fe9b850: undefined
	npm ERR! git clone --template=C:\Users\XXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/handsontable/handsontable.git C:
	\Users\XXX\AppData\Roaming\npm-cache\_git-remotes\git-github-com-handsontable-handsontable-git-3fe9b850: undefined
	npm ERR! Windows_NT 6.1.7601
	npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-hot-builder" "-g"
	npm ERR! node v0.12.4
	npm ERR! npm  v2.10.1
	npm ERR! code ENOGIT

	npm ERR! not found: git
	npm ERR!
	npm ERR! Failed using git.
	npm ERR! This is most likely not a problem with npm itself.
	npm ERR! Please check if you have git installed and in your PATH.

	npm ERR! Please include the following file with any support request:
	npm ERR!     handsontable\npm-debug.log

Would appear to be accurate if you search for the project on GitHub:

https://github.com/handsontable/grunt-hot-builder

**Comment by budnix** [comment]
Repository was restored.
