### ISSUE TITLE
Collapsed groups don't show first rows

### ISSUE THREAD

**Issue by skosch** [handsontable/handsontable#2571]
This could be optional, but I feel that the first row of a collapsed group should not be hidden. Excel doesn't do it, and showing the first row would also sidestep the problem of expander buttons overlapping each other.

If you're interested, I can figure out where to make those changes and submit a PR.

**Comment by AMBudnik** [comment]
Hi @skosch thank you for this idea, pull requests are always welcome. I will add your idea to our feature requests.

**Comment by AMBudnik** [comment]
Since [0.19.0](https://github.com/handsontable/handsontable/releases/tag/0.19.0) grouping was removed.
