### ISSUE TITLE
Column type checkbox is not center

### ISSUE THREAD

**Issue by metalfox6383** [handsontable/handsontable#2573]
Hi: A set 'className' property to 'htCenter' in a column of type "checkbox", but the checkboxes is not center align. Thanks.

**Comment by afbruno** [comment]
This should work!
//Call a custom render on HT options.
		cells: function(row, col, prop) {
			var cellProperties = {};
			cellProperties.renderer = that.cellRenderer;
			return cellProperties;
		}
//Define a custom render.
		function cellRenderer(instance, td, row, col, prop, value, cellProperties) {
			if (cellProperties.type === 'checkbox') {
				td.style['text-align'] = 'center'; //  !!Center align here!!
				Handsontable.renderers.CheckboxRenderer.apply(this, arguments);
			} else {
				Handsontable.renderers.TextRenderer.apply(this, arguments);
			}
		}

**Comment by AMBudnik** [comment]
please follow: https://github.com/handsontable/handsontable/issues/2925 for updates
