### ISSUE TITLE
Copy/paste fails since 0.15.0

### ISSUE THREAD

**Issue by ggaughan** [handsontable/handsontable#2574]
I was using http://handsontable.com/dist/handsontable.full.js for the last two weeks and copy/paste (via Ctrl+C and Ctrl+V) was working fine, then it seemed to stop a few days ago. I guessed this coincided with the 0.15.0 release. I've since downloaded 0.15.0-beta6 and it's working again (in Chrome and Firefox).

I didn't see any console errors with the breaking version, it just seemed to copy ok once and then further copies did nothing (in Chrome 43.0.2357.125). Also in Firefox 38.0, the breaking version seemed to do even less when copy/pasting (and it also edited and blanked out a cell's data when pressing the Ctrl key - may be a separate issue?)

See: http://jsfiddle.net/czcxnymj/1/ (the Firefox Ctrl-blanking issue can be seen in column B).

**Comment by AMBudnik** [comment]
Checked on Chrome 43 on OSX. Indeed there is only one ability to copy, after that <kbd>CTRL</kbd> + <kbd>C</kbd> seems broken. 

I tested it a little and I found that `editor: false` makes a column copy/paste issues without this line it works as expected.

**Comment by Maxi7** [comment]
I have the same problem (0.15.0, actual versions of FF and IE) and it does not work even if I set editor:true (and also readonly:false) ctrl-C does not copy the content of the selected cell.
(is there a possibility to add a context-menü entry for at least the copy function?)
