### ISSUE TITLE
Too thin left border when columns are frozen

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2575]
If the column is frozen then the selection of the cell in the column next to it has too thin left border.

**Steps to reproduce the problem:**

1. Freeze column A
2. Select any cell from the column B

:information_source:
> Handsontable v. 0.15.0
> Windows 8.1
> Chrome v. latest

![border](https://cloud.githubusercontent.com/assets/8048526/8279264/49696a2e-18d3-11e5-9210-5fef4feb2dd4.gif)

**Comment by swistach** [comment]
This can't be fixed as it is the expected behavior.
