### ISSUE TITLE
HandsOnTable JS crashing

### ISSUE THREAD

**Issue by crazyjavatricks** [handsontable/handsontable#2576]
hi,
Getting an error in HOT while setting values to a cell using renderer property. like,

 
![hot_error](https://cloud.githubusercontent.com/assets/11722540/8283456/1dff085c-1915-11e5-908a-6e811dceccb3.JPG)

![hot_error1](https://cloud.githubusercontent.com/assets/11722540/8283477/318f3914-1915-11e5-81b9-eb5d88e436c9.JPG)

(Note: In renderer function i am passing Collection of java models)

I am using Mozilla Firefox V31.0, the same issue in IE 11. 
but its getting fine on Google Chrome V38

can you guys help to solve this.

**Comment by AMBudnik** [comment]
Can you provide a demo code?
