### ISSUE TITLE
Undo Remove row should fire an 'AfterCreateRow' callback

### ISSUE THREAD

**Issue by sarahquigley** [handsontable/handsontable#2577]
I've been playing around with this: http://docs.handsontable.com/0.15.0/tutorial-callbacks.html

I noted that when I undid a remove row (executed with the right click menu), an 'afterCreateRow' event was not fired as I expected. This seems like a bug. Is this a known issue? Any plans to resolve this.

**Comment by AMBudnik** [comment]
You are right `afterCreateRow` does not fire after undo the `removeRow`. Thanks for your suggestion.

**Comment by sarahquigley** [comment]
@AMBudnik No problem. Thanks for your prompt response and all your great work on handsontable. The new website is looking great.

**Comment by budnix** [comment]
Confirmed. Bug still exists in v0.23.0.

**Comment by rakeljane** [comment]
It'd be nice to have afterCreateCol be called after the removeCol undo as well.

**Comment by AMBudnik** [comment]
The issue does not occur in version 0.35.0
Please try it at https://docs.handsontable.com/0.35.0/tutorial-using-callbacks.html
