### ISSUE TITLE
Support cell backed by custom object with autocomplete

### ISSUE THREAD

**Issue by jlsalmon** [handsontable/handsontable#2578]
I am looking to be able to have the data behind a cell be an object, but use a specific property of the object as the display value. 

I also want that Autocomplete columns (which retrieve data in the same format as the data behind the cell) behave the same way, i.e. that I can process a list of objects in the `source` function and have Handsontable automatically display the sub-property designated as the property to be displayed.

I am looking for something like this:

```
var data = [
  {id: 1, name: {first: "Ted", last: "Right"}},
  {id: 3, name: {first: "Joan", last: "Well"}}
]

var hot = new Handsontable(container, {
    data: data,
    columns: [{
       data: 'name',

       // Specify a sub-property of the cell object to be displayed
       viewModel: 'first',

       source: function(query, process) {

           // Return list of objects. Handsontable should display the property specified in
           // 'propertyToDisplay', inside Editor and dropdown list
           process([data[0].name, data[1].name]);
       }
    }],
  });
```

This feature request is similar to #584, which remains unresolved. Using Handsontable in Handsontable, as suggested in that issue, would probably not be suitable for me in this case.

I am currently trying to make a custom editor/renderer to do this, but as I am not very familiar with the Handsontable source at the moment, would it be possible for a core developer to implement something like this or at least give a few clues as to what I might need to change/implement?

**Comment by jlsalmon** [comment]
Update: I have implemented a custom editor for this (see [this gist](https://gist.github.com/jlsalmon/396813e4e41176a7bd3a)) but it requires several modifications to the source (I'm using `v0.15.0`).

Source changes:
* `autocompleteEditor.js:80`: check if `viewModel` property exists in cell meta and return the object instead of stringifying it;
* `autoColumnSize.js:103`: check if `viewModel` property exists in cell meta and stringify it to prevent displaying `[object Object]`
* `textRenderer:30`: check if `viewModel` property exists in cell meta and stringify it to prevent displaying `[object Object]`
 
Things that don't work properly yet:

* Copy/paste: pasting a cell with an object behind causes `[object Object]` to be displayed. This is because when copying, the cell is stringified (`dataMap.js:582`). That would require a different approach.

If anyone thinks this is a good approach and a worthwhile feature, I can make a pull request. The custom editor could also be integrated into the existing AutocompleteEditor (or maybe into the base editor to allow this behaviour for all cell types).

**Comment by jlsalmon** [comment]
This is also similar to #535, which I see was approved as a feature request [here](https://github.com/handsontable/handsontable/wiki/Feature-requests) in 2013. Is there any news on this? This is a necessary feature for me, and a dealbreaker if I don't find a workaround.

**Comment by AMBudnik** [comment]
Hi @jlsalmon all feature requests are on [our wiki](https://github.com/handsontable/handsontable/wiki/Feature-requests) so they are closed in github. Issue is reopened if it is under development, so please track changes to #535

**Comment by jlsalmon** [comment]
Any update on this? This is a highly desirable feature. I would be happy to contribute to this.

**Comment by elgubenis** [comment]
+1
