### ISSUE TITLE
Custom multilevel menus

### ISSUE THREAD

**Issue by sirmartymoose** [handsontable/handsontable#2579]
This is a follow up on #1649.

Here is my syntax, but the submenu does not show up. I am using the 0.15.0 release.

contextMenu: {
                callback: function (key, options) {
                            if (key === 'above') {
                                //Do something
                            }else if (key === 'below') {
                                //Do something
                            }
                        },
                        items:{
                            "copy":{},
                            "hotspot_ave": {
                                "name": "Highlight 20%",
                                "items":{
                                        "above": {"name": "Above average"},
                                        "below": {"name": "Below average"}
                                }
                            }
                        }

                },

**Comment by AMBudnik** [comment]
please prepare a full demo for this example.

**Comment by sirmartymoose** [comment]
Thanks for your reply. Here's a demo: http://jsfiddle.net/akothari/nawtez1y/

**Comment by sirmartymoose** [comment]
Any thoughts on this?

**Comment by AMBudnik** [comment]
Hi, I hope this [submenu example](https://jsfiddle.net/jx6ayh9m/) will help.

**Comment by sirmartymoose** [comment]
thank you

**Comment by 1vmattila** [comment]
Hi,

it seems that the previous submenu example only works up to version 0.16.0. From 0.17.0 upwards it seems to show either "null" or "undefined". Should we reopen this ticket or create a new one?

**Comment by AMBudnik** [comment]
@1vmattila we have a separate issue for submenu bug at https://github.com/handsontable/handsontable/issues/2298

**Comment by 1vmattila** [comment]
Ok, good to know. Sorry for the trouble :)

0.16.0 works for me so far, so no panic here. Pretty nice component all-in-all, documentation too! :+1:
