### ISSUE TITLE
Double click on the resize handle call cell renderer with string value

### ISSUE THREAD

**Issue by lucamaral** [handsontable/handsontable#2580]
Hi!
I was looking to use manual column resize but I found some kind of issue with my custom cell renderer.

```javascript
var data = [
			[
				{label : 'Kia', otherImportantProperties : {} }, 
				{label : 'Nissan', otherImportantProperties : {} }, 
				{label : 'Toyota', otherImportantProperties : {} }
			],
			[-5, 12, 13],
			[-11, 14, 13],
		        [15, -12, 15]
		],
		container,
		hot1;
		  
	container = document.getElementById('example1');
	hot1 = new Handsontable(container, {
		data: data,
        colHeaders : true,
        manualColumnResize : true,
		cells: function (row, col, prop) {
			var cellProperties = {};	
				if(row === 0){
					cellProperties.readOnly = true;
					cellProperties.renderer = function (instance, td, row, col, prop, value, cellProperties){
						// business logic using value.otherImportantProperties
						// rendering only label text
						Handsontable.renderers.TextRenderer.apply(this, [instance, td, row, col, prop, value.label, cellProperties] );
					};
				}
					
			return cellProperties;
		}
	});

```

When user double click on the resize handle, my custom renderer function is called with a stringify "value" parameter not my {label : ..., otherImportantProperties : .... } object.

Looking through handsontable code, I discovered a function called `` determineColumnWidth``(line 9229)  that stringify the value before call cell renderer:

```javascript
var value = instance.getDataAtCell(r, col);
if (!Array.isArray(value)) {
    value = helper.stringify(value);
}
```

**Comment by AMBudnik** [comment]
hi @lucamaral please prepare a JSFiddle demo of your code.

**Comment by lucamaral** [comment]
http://jsfiddle.net/on8kc3c3/

**Comment by lucamaral** [comment]
hey @AMBudnik !

I am updating my handsontable version and this issue still remains
Will you work on this issue soon?

Thanks!

**Comment by AMBudnik** [comment]
I wasn't able to reproduce it with the latest version. Please check it with 0.24.1.

**Comment by AMBudnik** [comment]
Also couldn't reproduce in 0.24.2
I assume this issue is solved. If I'm wrong please leave a comment.
