### ISSUE TITLE
HandsOnTable - updateSettings with updated mergeCells option is not working

### ISSUE THREAD

**Issue by csdpuneteam1** [handsontable/handsontable#2581]
I have HandsOnTable with mergeCells option, on particular event I make a server call which gives me updated data and hence merge cells options also need to be updated. For e.g. before server call, grouping was for every 5 rows, but after its for 4 rows.

I used hot.updateSettings(hotOptions) in which mergeCells of hotOptions is updated, but it does not update the setting.

Before server call:
```
    var hotOptions =
            {
        data: Handsontable.helper.createSpreadsheetData(5,5),
        colWidths: [47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47],
        rowHeaders: true,
        colHeaders: true,
        contextMenu: true,
        mergeCells: [
          {row: 0, col: 0, rowspan: 2, colspan: 2},
            {row: 3, col: 3, rowspan: 2, colspan: 2}
        ]
          };
    hot = new Handsontable(container, hotOptions);
```
After server call:

```
  hotOptions.mergeCells = [
      {row: 0, col: 0, rowspan: 3, colspan: 3},
        {row: 0, col: 3, rowspan: 2, colspan: 1}
    ];
    //just to prove that data is updating
    hotOptions.colWidths= [100, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47];
   hot.updateSettings(hotOptions);
```
I can destroy earlier HOT instance and create new one with new options(attached fiddle does this), but I want to achieve the same with updateSettings.

 More details : http://jsfiddle.net/ru53zo3o/1/

**Comment by AMBudnik** [comment]
unfortunately this can't be achieved right now, please track changes to this issue https://github.com/handsontable/handsontable/issues/1788

**Comment by sohansoni** [comment]
Guys, I think I have fixed this.

Just before calling updateSettings of the HOT instance, update it's mergeCells attribute , with the new instance of Handsontable.MergeCells object by passing updated mergeCells array as an attribute.

```
hotOptions.mergeCells = [{row: 0, col: 0, rowspan: 2, colspan: 3} ];
hot.mergeCells = new Handsontable.MergeCells(hotOptions.mergeCells);
hot.updateSettings(hotOptions);
```
See it working here: http://jsfiddle.net/gncb55jp/3/
