### ISSUE TITLE
Conditional formatting on event

### ISSUE THREAD

**Issue by arkothari** [handsontable/handsontable#2584]
Hello,

I am facing an issue where i have a large set of records in the grid and on a user action, I need to highlight certain columns. When i do that, only the columns visible to the user are highlighted. As I scroll down, the highlighted columns loose the changes and the newer ones also do not have the highlighting.

A demo is available here:http://jsfiddle.net/akothari/yp458rg4/ 

Is there a way to force handsontable to render the entire grid. Alternatively, what other options can be used?

Thanks in advance.

**Comment by budnix** [comment]
Hi, I think that you can use in this case custom renderers. Updated demo: http://jsfiddle.net/yp458rg4/1/

**Comment by sirmartymoose** [comment]
thank you budnix

**Comment by arkothari** [comment]
thank you KB
