### ISSUE TITLE
Formulas option not working with "renderer: 'html'"

### ISSUE THREAD

**Issue by kovalevskyartur** [handsontable/handsontable#2586]
```
// ...
var hot = new Handsontable(container, {
    formulas: true,
    renderer: 'html'
});
```

with html renderer formulas still raw text, like "=SUM(A1,B1)"

**Comment by AMBudnik** [comment]
Thank you for that suggestion. This issue will be moved ro https://github.com/handsontable/handsontable-ruleJS
