### ISSUE TITLE
The height of the vertical scrollbar is not correctly modified after a column with heights > 1 text line is removed.

### ISSUE THREAD

**Issue by Maxi7** [handsontable/handsontable#2587]
see demo on http://jsfiddle.net/vsueeh97/

Column D contains values which are spread over 2 text lines. This gives the rows also a height of 2 lines each.
This is not a problem for the scrollbar, you can scroll to the button to see the last row.

Now scroll to top again and select a cell in column D. Then remove this column using the context menu.
You see that the rows have a height of 1 line now (as expected).

But if you use the scrollbar to inspect the last rows you see a blank page. 
It is not an easy task now to find the last row.

As a counter example you can remove an other column which does not effect the row heights.
(The wording of the titel is my interpretation only of this behaviour.)

**Comment by AMBudnik** [comment]
Thank you for that report, at the first glance I cannot find the issue case, so stay tuned. We will take a closer look at this one.

**Comment by budnix** [comment]
HI @Maxi7 this feature was released in 0.16.0 (`autoRowSize: true`). See updated demo at http://jsfiddle.net/vsueeh97/2/

**Comment by Maxi7** [comment]
thank you. I just tested it with 0.17.0 on my environment. it works!
sorry for answering late.
