### ISSUE TITLE
Hook for afterMerge

### ISSUE THREAD

**Issue by docmattman** [handsontable/handsontable#2588]
Is there an "afterMerge" hook or something similar that is called when cells are merged?  I'm trying to save all changes to a database in a remote server, so I need to know when merges have been made.  I can't find any references in the docs for a hook like this.

**Comment by AMBudnik** [comment]
there is not an `afterMerge` callback, but it is a good idea - I will add it to our feature request list.

**Comment by serenasara** [comment]
I use this below to solve.


 var ht = $(orderhandsontableDivId).handsontable('getInstance');
        ht.updateSettings({
            contextMenu:true,
            contextMenu: {
                callback: function (key, options) {
                },
                items: {
                    "mergeCells":{
                        name: '合并单元格',
                        callback:function(key, options){
                            alert(JSON.stringify(options));
                        }
                    },
                }
            }

        });
        ht.render();

**Comment by computurus** [comment]
The workaround is nice, but then all the other options from the context menu are gone...

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
The hook has been added. Here's documentation https://docs.handsontable.com/pro/Hooks.html#event:afterMergeCells
