### ISSUE TITLE
Saving all table info (data, columns, borders, merges, etc)

### ISSUE THREAD

**Issue by docmattman** [handsontable/handsontable#2589]
I'm saving table changes to a remote server in a database.  Is there a way to "serialize" the table and get all its information to save everything remotely at once?  Right now, I have an "afterChange" hook that listens for changes to cell data.  I have "afterColumnResize" and "afterRowResize" hooks set to listen for column changes.  There is no "afterMerge" hook that I can see, but I use a workaround inside the "afterRender" hook.  I haven't dealt with borders yet, but I'll need to save changes to those as well.

I guess what I'm looking for is a way to listen to ANY change made to the table (cell data, columns, borders, merges, undo, redo, etc).  Anything that affects the table at all.  Then be able to take a "snapshot" or serialize the entire table, send it to the server to save in a database, then load the serialized version on the next page view.  Is there a way to easily do all this?

**Comment by dellert** [comment]
I have same question. Can anybody help?

**Comment by AMBudnik** [comment]
Hi, we already have the same issue at https://github.com/handsontable/handsontable/issues/1974 please track changes to https://github.com/handsontable/handsontable/issues/1974 for further information
