### ISSUE TITLE
Cell selection not working when defining merged cells

### ISSUE THREAD

**Issue by docmattman** [handsontable/handsontable#2590]
http://jsfiddle.net/qgwz6m48/

Try selecting from R1 to R10.  It selects R3, but R3 is in the "T" column.  Anything that can be done to fix this?

**Comment by docmattman** [comment]
Also, choosing "Insert row above" in the context menu on row A doesn't work right either.  It seems to push all the cell content down 1 row and adds a new row at the end or something.  The merged cells seem to stay in row 1 instead of following adding a new row at the top and shifting the merged cells down to row 1.

**Comment by AMBudnik** [comment]
Hi, this issue is already here https://github.com/handsontable/handsontable/issues/2443, please track changes to https://github.com/handsontable/handsontable/issues/2443 for more information.

**Comment by docmattman** [comment]
Ok, thanks.  Also note the strange issue above when adding rows when there are merged cells.

**Comment by AMBudnik** [comment]
Yes, unfortunately there is more to do with merging cells.

**Comment by AMBudnik** [comment]
Updated to 0.24.1: http://jsfiddle.net/qgwz6m48/1/ still present

**Comment by jansiegel** [comment]
This issue is caused mostly by improper merge cells  declaration - some of them overlap, which is unsupported. I suppose it should be checked after initialization and displayed as a warning in the console.

**Comment by jansiegel** [comment]
Should work fine in `0.37.0`.

**Comment by AMBudnik** [comment]
Hi @docmattman 

Can you confirm that the issue is gone after updating to v0.37.0?
