### ISSUE TITLE
Sort direction not shown after sorting

### ISSUE THREAD

**Issue by Maxi7** [handsontable/handsontable#2591]
In my application the sort direction glyphs (arrow up and down) in the respective column header are not shown (any more?) in my application.
Trying to learn from the HOT examples:

In the basic example (http://handsontable.com/examples.html#fndtn-basic) you can sort the table, but NO glyphs are shown.

In the advanced example (http://handsontable.com/examples.html#fndtn-advanced) you can sort the table, and the glyphs ARE shown.   

Now I try to learn from the advanced example by "Edit in jsFiddle"
But: after sorting NO sort glyphs are shown.

**Comment by mburbea** [comment]
It seems that the jsFiddle lies:
The actual js used is different it looks like this:
```javascript
settings: {
            width: 900,
            height: 396,
            colHeaders: ["Country", "Level", "Units", "As Of", "1Y Chg", "5Y Ago", "10Y Ago", "25Y Ago"],
            rowHeaders: true,
            stretchH: 'all',
            columnSorting: true,
            sortIndicator: true,
            contextMenu: true,
            className: "htCenter htMiddle",
            readOnly: true,
            columns: [
              {data: 0, type: 'text'},
              {data: 1, type: 'numeric', format: '0,0.00[0000]'},
              {data: 2, type: 'text'},
              {data: 3, type: 'numeric', format: '0'},
              {data: 4, type: 'numeric', format: '0.00%', renderer: percentRenderer},
              {data: 5, type: 'numeric', format: '0,0.00[0000]'},
              {data: 6, type: 'numeric', format: '0,0.00[0000]'}
            ]
        },
        getData: function () {
          return advancedData;
        }
      }
```
The main takeaway is you need to add this `sortIndicator: true,` to make the sort glyphs show up.

**Comment by Maxi7** [comment]
Thank you! It works now! Great!
