### ISSUE TITLE
'paste' event not triggered when `pasteMode` set

### ISSUE THREAD

**Issue by jlsalmon** [handsontable/handsontable#2592]
When pasting, a callback to `afterChange()` should be made with the source set to `paste`, as suggested by [the docs](https://github.com/handsontable/handsontable/blob/master/src/pluginHooks.js#L67). This doesn't happen when the `pasteMode` setting is given as anything other than `overwrite`.

See [this jsfiddle](http://jsfiddle.net/mvfjajvw/4/) for an example. Copy and paste any cell and see that the alert is never called.

I can see that `CopyPastePlugin.onPaste()` calls `Handsontable.Core.populateFromArray()` with `paste` as the source, but when `pasteMode` is set to anything other than `overwrite` then nothing happens.

I think that this is a bug. It should be pretty easy to fix, though. If you like, I can fix it and make a pull request.

**Comment by AMBudnik** [comment]
Thank you for that suggestion.

**Comment by krzysztofspilka** [comment]
@jlsalmon thanks for letting us know about it. Can you still make a pull request for that one?

**Comment by jlsalmon** [comment]
@krzysztofspilka I would love to, but I probably wont have time anywhere in the near future...

**Comment by AMBudnik** [comment]
Currently (v.0.35.0) it seems to log data correctly. We get `CopyPaste.paste` in the console
