### ISSUE TITLE
observeChanges seems to be true by default (doc says false)

### ISSUE THREAD

**Issue by bourbest** [handsontable/handsontable#2593]
I have an HT with over 4000 rows. When I first call loadData with my array, everything is fine.
When I call loadData a second time (my user can filter the table, for which I generate another array with only the data that should be displayed) with a smaller array (size 6) , it hangs forever. Debuging in Chrome shows its lost in some observer class. 

To solved this by fixing the observeChanges : false
which makes me presume that this property is not set to false as the documentation suggests.
Thanks for this awesome control
Steph

**Comment by AMBudnik** [comment]
Could you share a demo where this issue is replicable @bourbest 
Thanks in advance!

**Comment by bourbest** [comment]
Hi
This was with an old version of handsontable that i don't use anymore. I
remember fixing it by editing the code, but haven't encountered the problem
with newer versions.
Might as well close the issue
Thanks
Steph

2016-03-21 11:45 GMT-04:00 Aleksandra Budnik <notifications@github.com>:

**Comment by AMBudnik** [comment]
Thanks for prompt reply @bourbest
