### ISSUE TITLE
Using backspace while editing a cell often breaks the cell editor

### ISSUE THREAD

**Issue by yohcop** [handsontable/handsontable#2594]
This happens 99% of the time I use backspace while editing cells in my table.
This results in having a hard time closing the editor for a cell (I can even open other cell editors sometimes), and essentially backspace doesn't work.

Occasionally I manage to close the editor by mad-clicking around, using F2 to open/close editors in other cells, etc, but it doesn't always work.

On this screenshot, 2 editors are open: https://goo.gl/rKYpLh.
This is using latest chrome as well.

I see the following errors in the js console:

```
handsontable.full.js:11863 Uncaught TypeError: Cannot read property 'check' of undefined
```

And sometimes:

```
handsontable.full.js:7335 Uncaught TypeError: Cannot read property 'getInstance' of undefined
```

Edit: I'm using HOT in a custom element with shadow dom, could be related?

Thanks,
Let me know if you need anything else.

**Comment by AMBudnik** [comment]
I couldn't reproduce it with http://handsontable.com/. Can you please prepare a demo code?

**Comment by yohcop** [comment]
Hi,
Here is as small as I could make it quickly: http://jsfiddle.net/fnpg7x2f/3/

**Comment by budnix** [comment]
Yes, this is definitely issue related with custom elements.

**Comment by AMBudnik** [comment]
Still occuring in 0.24.1

**Comment by yohcop** [comment]
"Still occurring", then close the issue??

**Comment by AMBudnik** [comment]
My bad! Thanks for feedback @yohcop

**Comment by sgammon** [comment]
hey, we are hitting this issue with Polymer. can't use `<hot-table>` either because it's in beta, even though it seems to correctly handle this stuff just fine :(

**Comment by wszymanski** [comment]
Currently Handsontable don't support Custom Elements. We'll back to this ticket when Web Components functionality will be handled.
