### ISSUE TITLE
Upgrading from 0.12.6 to 0.15.1: Many things no longer work

### ISSUE THREAD

**Issue by lrtherond** [handsontable/handsontable#2595]
After upgrading to 0.15.1 from 0.12.6, many things stopped working as they did before...

![handsontable_exception1](https://cloud.githubusercontent.com/assets/1578548/8385985/d7c2356a-1c09-11e5-8135-3ffddadc08db.PNG)

![validator](https://cloud.githubusercontent.com/assets/1578548/8385990/e0bc72ca-1c09-11e5-966f-a8a72d8eaef9.PNG)

In addition, I have a custom cell editor that uses the following open function:

![custom_editor](https://cloud.githubusercontent.com/assets/1578548/8386180/8ed72854-1c0b-11e5-8e0d-94e96e3139b6.PNG)

This code no longer works either, it seems, because the editor is never opened.

So, is there something I am doing wrong or does upgrading require rewriting significant portions of the code?

**Comment by AMBudnik** [comment]
Hi, could you prepare a demo, we'll see what we can do.

**Comment by lrtherond** [comment]
The code has too many dependencies to be extracted in a demo.
I guess the way custom editors are positioned and set up has changed in some way...may have to rewrite mine.

**Comment by lrtherond** [comment]
Is the information at the bottom of this page still valid?

http://docs.handsontable.com/0.15.1/tutorial-cell-editor.html

I am referring to this:

> Additionally, due to the recent change in the positioning of the overlays (fixed columns, rows, headers etc.) we need to set the css transform property. We'll use the Handsontable.Dom's getCssTransform and resetCssTransform to get the correct values:

open in selectEditor.js does not agree:

```
SelectEditor.prototype.open = function() {
  var width = dom.outerWidth(this.TD); //important - group layout reads together for better performance
  var height = dom.outerHeight(this.TD);
  var rootOffset = dom.offset(this.instance.rootElement);
  var tdOffset = dom.offset(this.TD);
  var editorSection = this.checkEditorSection();
  var cssTransformOffset;

  switch (editorSection) {
    case 'top':
      cssTransformOffset = dom.getCssTransform(this.instance.view.wt.wtOverlays.topOverlay.clone.wtTable.holder.parentNode);
      break;
    case 'left':
      cssTransformOffset = dom.getCssTransform(this.instance.view.wt.wtOverlays.leftOverlay.clone.wtTable.holder.parentNode);
      break;
    case 'corner':
      cssTransformOffset = dom.getCssTransform(this.instance.view.wt.wtOverlays.topLeftCornerOverlay.clone.wtTable.holder.parentNode);
      break;
  }

  var selectStyle = this.select.style;

  if (cssTransformOffset && cssTransformOffset != -1) {
    selectStyle[cssTransformOffset[0]] = cssTransformOffset[1];
  } else {
    dom.resetCssTransform(this.select);
  }

  selectStyle.height = height + 'px';
  selectStyle.minWidth = width + 'px';
  selectStyle.top = tdOffset.top - rootOffset.top + 'px';
  selectStyle.left = tdOffset.left - rootOffset.left + 'px';
  selectStyle.margin = '0px';
  selectStyle.display = '';

  this.instance.addHook('beforeKeyDown', onBeforeKeyDown);
};
```

**Comment by AMBudnik** [comment]
Hi @lrtherond sorry for a such a delay. There was some changes according to cell editors. If you're still looking for some answers, please let me know.
