### ISSUE TITLE
Callback for submenu context items

### ISSUE THREAD

**Issue by arkothari** [handsontable/handsontable#2596]
I have a sub menu in my context menu. The sub menu renders fine, but the callback function is not called when I click any of the sub menu items.
Heres a demo: http://jsfiddle.net/o2tmpnok/

Do i need to change the way the submenu is defined?

**Comment by arkothari** [comment]
Any thoughts?

**Comment by AMBudnik** [comment]
Hi @arkothari 
Is there anything else I can currently help you with? I assume you made a huge progress since this post was made.

**Comment by AMBudnik** [comment]
I'm closing this issue in lack of reply but @arkothari leave a comment if you'll need anything
