### ISSUE TITLE
Context Menu: add icons to menu items

### ISSUE THREAD

**Issue by sarahquigley** [handsontable/handsontable#2597]
Though JQuery-contextMenu supports custom icons for menu items, the Handsontable context menu does not appear to support the addition of icons to menu items. I am working on a project where this is a requirement. It would be great if support could be added for this customisation of the context menu.

Many thanks.

**Comment by AMBudnik** [comment]
Thanks for suggestion. I think it's an interesting idea.

**Comment by sarahquigley** [comment]
Thanks @AMBudnik! Hope it makes it in as a feature at some point.

**Comment by samsonkhisty** [comment]
@sarahquigley, @AMBudnik   This works for me

     name: function() {
        return " <i class= 'fa fa-fw fa-columns ' > </i> Menu Item";
      }

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.
