### ISSUE TITLE
Meteor and Handsontable

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#2598]
I guess Handsontable would work perfect with Meteor or Derby. Are there any plans of maintaining a Meteor package with Handsontable and demos of how to integrate it?

Has anyone figured out how to make these play along?

**Comment by skosch** [comment]
Any luck with the example given at http://stackoverflow.com/questions/27701527/meteor-handsontable-example?

**Comment by AMBudnik** [comment]
Thank you @skosch for support. We try to keep github as a place to report bugs & feature requests and SO for others questions so @57even please track changes to SO topic that @skosch presented.
