### ISSUE TITLE
Make autocomplete dropdown width optional

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2599]
In some cases the autocomplete suggestions don't fit in the dropdown, and there's no way (except from applying them) to preview their actual contents.

There should be an option to either keep the current situation (dropdown width = cell width) or make the dropdown scale according to its contents.

**Comment by jansiegel** [comment]
Added a `trimDropdown` property (defaults to `true`). 
If set to `false`, the autocomplete dropdown doesn't resize to the cell's width.

**Comment by husayt** [comment]
I have tried this with latest 0.16.0 version and can't get it to work.
This is how I specify the cell:
```
cellCfg.push(
{
  row: 0,
  col: i,
  type: 'dropdown',
  trimDropdown: false,
  source: fieldsNames
});
             
```

What do I miss?

**Comment by AMBudnik** [comment]
Thanks @husayt we will take care of it. Please stay tuned for further information.

**Comment by jaredbaszler** [comment]
Any update on this bug?

**Comment by AMBudnik** [comment]
Hi @jaredbaszler our team is working on this issue, please stay tuned. Currently there is no tests for this issue, but when the correct solution will be tested new label will appear.

**Comment by jansiegel** [comment]
@jaredbaszler Fix for this issue will be released with the next version on Handsontable
