### ISSUE TITLE
Frozen column prevents dropdown from closing

### ISSUE THREAD

**Issue by rscummings** [handsontable/handsontable#2600]
Freezing a read-only column next to a dropdown column sometimes prevents the dropdown from closing.

Here is a demo, along with steps to reproduce: http://jsfiddle.net/rscummings/hU6Kz/3690/

This is part of a deeper issue with the management of frozen columns. Handsontable maintains a mapping between visible column positions and actual column positions. This map is an array exposed on a Handsontable.Core instance (`[Handsontable.Core].manualColumnPositions`).

The problem is that this mapping happens twice, but it should only happen once. In the validateChanges function of `core.js`, it is happening on [this line](https://github.com/handsontable/handsontable/blob/8d83c71884bd8617727444de713d43e8e3d5eda2/src/core.js#L876):

``` javascript
var logicalCol = instance.runHooks('modifyCol', col);
```

and again on [this line](https://github.com/handsontable/handsontable/blob/8d83c71884bd8617727444de713d43e8e3d5eda2/src/core.js#L877), right below:

``` javascript
var cellProperties = instance.getCellMeta(row, logicalCol);
```

`.getCellMeta` calls `.colToProp`, which in turn runs the `modifyCol` hook from `manualColumnFreeze.js` that does the mapping.

In the demo, the first mapping takes us from column 0 to column 1. Then the second mapping takes us from column 1 back to column 0. Handsontable understands column 0 to be the car column, which is read-only. Thus Handsontable treats the Year column as read-only. For read-only columns, the `postAfterValidate` hook does not run. Because `postAfterValidate` is where dropdowns get destroy()'d (i.e. closed), the dropdown stays visible.

To fix this issue, I think we need to remove one of the mappings. I would prefer removing the `logicalCol` line. This would mean that `.getCellMeta` (and deeper down, `.colToProp`) is in charge of the mapping.

I've tried removing the `logicalCol` line locally, and it seems to fix the issue.

**Comment by AMBudnik** [comment]
Interesting issue, thank you for reporting this and for a fix suggestion.

**Comment by rscummings** [comment]
I've been playing around with it a bit more, and it seems that removing the `logicalCol` line isn't enough to fix it. The issue might actually have more to do with the `colToProp` / `propToCol` mappings, similar to #2292.

I think there is a design decision here - should `colToProp` and `propToCol` be aware of manually rearranged columns, or should they not be? I'd be open to either approach.

**Comment by rscummings** [comment]
I think I've fixed the issue for release 0.12.6 in [this commit](https://github.com/rscummings/handsontable/commit/fac48804c607145c66e292e886a131a8b1b7ad96?diff=unified) - in particular, see the files changed in the `src/` directory. 

I am thinking about creating a pull request, but two of the Walkontable jasmine tests are failing on the `master` branch at the latest commit (before any of my changes are applied). Is this normal?

**Comment by edallen** [comment]
One of my users just showed me a bug that might be this issue (Handsontable is currently at 0.12.2 in our app) so I'm watching the linked fix to track this.

**Comment by AMBudnik** [comment]
Bug still occurs in 0.24.1

**Comment by AMBudnik** [comment]
Still in 0.26.0 http://jsfiddle.net/pLrqzmjx/

**Comment by AMBudnik** [comment]
Hi @rscummings 
I've tested it in v0.30.1 and it works as expected. We have fixed some meta data issues it the last two versions I guess that this issue got fixed as well.

I am closing it however if you still experience similar behavior please leave a comment.
