### ISSUE TITLE
an issue about autocomplete,help!!!!

### ISSUE THREAD

**Issue by cmhjjosso** [handsontable/handsontable#2601]
I used autocomplete widget today but it turns out that autocomplete is unable to load the whole source at first time.It shows 31 items at most.Then I checked it again,it worked well.But in the early version this   problem doesn't exist.(ps my version is 0.15.1

**Comment by AMBudnik** [comment]
Hi unfortunately this issue was reported earlier at https://github.com/handsontable/handsontable/issues/2505 please track changes to https://github.com/handsontable/handsontable/issues/2505 when this issue will be under development there be an adnotation.

**Comment by cmhjjosso** [comment]
I've change it to version 0.13 . it's an awnsome plug-in anyway and I wish this would be fixed ASAP ^_^
