### ISSUE TITLE
function duckSchema does not preserve prototypes of objects

### ISSUE THREAD

**Issue by rjansen72** [handsontable/handsontable#2602]
In our integration with handsontable we utilize objects for our row data that we feed to the table. Most properties are of scalar types, so they are fine. However, we have some properties that are custom JS classes, and the function duckSchema converts those all to plain objects, so the methods they once had are no longer callable.
Working on a fix in our fork.

**Comment by rjansen72** [comment]
Closing this as I ended up fixing it in our integration by implementing a custom dataSchema option.

**Comment by pdemilly** [comment]
@rjansen72 I am having the same issue. Care about sharing how you implemented your own dataSchema option. Thx
