### ISSUE TITLE
How to show default value of dropdown in a cell when new row is added to the handsontable grid??

### ISSUE THREAD

**Issue by ajinkyasingh27** [handsontable/handsontable#2604]
Hi,
I have a cell in the grid which is of dropdown type editor.Whenever a new row is added into the grid, default value in a dropdown type ediitor.I want to display the default value in a dropdown type cell.

**Comment by AMBudnik** [comment]
Hi @ajinkyasingh27 data shown in dropdown is from your data set. You can use `updateSettings` after adding row. If you would have any problems - create a [demo](https://jsfiddle.net/api/post/library/pure/) and we'll help.

You can also check [stackoverflow with and `handsontable` tag](https://stackoverflow.com/search?q=handsontable) there are many topics that can help you.
