### ISSUE TITLE
Memory Leak in Editor Instance Cache

### ISSUE THREAD

**Issue by baac0** [handsontable/handsontable#2605]
While creating and deleting many instances of Handsontable we've stumbled upon a possible memory leak:

![editor_memory_leak](https://cloud.githubusercontent.com/assets/13137666/8477208/b6fc086a-20c8-11e5-9883-32c210cab958.PNG)

It appears the culprit is the instance cache of editors in file editors.js: for each instance of Handsontable a reference is kept in variable `instances` which does not get cleaned up when the table's `destroy` method is called.

We've detected this problem while testing on 0.12.4 but looking at the code I suspect it's still present in the latest version as well.

**Comment by AMBudnik** [comment]
Thank you for that report. We will take a closer look at this.

**Comment by tympollack** [comment]
I think I've also stumbled onto this issue. I've created a fiddle here: https://jsfiddle.net/vatexx36/2/

The issue seems to be that if the handsontable instance is destroyed while an editor exists, the entire instance detaches from the DOM. If the instance is destroyed while no editor exists, there is no issue.

I've tried destroying the editor any way I can, but it always gets put back into it's prepared state in the end, which means the whole table gets detached.

If this isn't the same issue and a workaround exists, please let me know.

**Comment by tympollack** [comment]
I think I might have made a breakthrough for this.  In EventManager's clearEvents and removeEventListener functions, the events are cycled through and assigned to a temp variable that's reused without ever getting nulled out. It keeps the referenced event in memory, which stops the collection of the event and detaches the DOM.  I changed the two methods below so that the temp variables are nulled out, which seems to have fixed my issue.

`removeEventListener: function(element, eventName, callback) {
    var len = this.context.eventListeners.length;
    var tmpEvent;
    while (len--) {
      tmpEvent = this.context.eventListeners[len];
      if (tmpEvent.event == eventName && tmpEvent.element == element) {
        if (callback && callback != tmpEvent.callback) {
          continue;
        }
        this.context.eventListeners.splice(len, 1);
        if (tmpEvent.element.removeEventListener) {
          tmpEvent.element.removeEventListener(tmpEvent.event, tmpEvent.callbackProxy, false);
        } else {
          tmpEvent.element.detachEvent('on' + tmpEvent.event, tmpEvent.callbackProxy);
        }
        Handsontable.countEventManagerListeners--;
      }
      tmpEvent = null;
    }
  },
  clearEvents: function() {
    if (!this.context) {
      return;
    }
    var len = this.context.eventListeners.length;
    var event;
    while (len--) {
      event = this.context.eventListeners[len];
      if (event) {
        this.removeEventListener(event.element, event.event, event.callback);
        event = null;
      }
    }
  },`

**Comment by tympollack** [comment]
As an addendum I forgot to mention I also have to clear out the editor manually before destroying the table, otherwise the memory leak is still there. The above code was simply the only changes I had to make in handsontable.js

```
if (hot && !keepTable) {
            editor = hot.getActiveEditor();
            if (editor) {
                keys = Object.keys(editor);
                for (i = 0, len = keys.length; i < len; i++) {
                    key = keys[i];
                    if (['eventManager', 'eventListeners'].indexOf(key) < 0) {
                        delete editor[key];
                    }
                }
                editor = null;
            }
            hot.destroy();
            hot = null;
        }
```

**Comment by AMBudnik** [comment]
Thank you for your effort and the investigation @tympollack

**Comment by armensg** [comment]
I am also running into issue of too many events being registered when creating many tables (anuglar ui-router app). I tried writing an angular directive to add to my ngHandsontable to destroy my instances but sometimes I get a "post mortem" error that the table is already destroyed - without events being removed. 

```
// https://github.com/handsontable/ngHandsontable/issues/157
angular.module('dealer.directives').directive('hotAutoDestroy',["hotRegisterer",function(hotRegisterer) {
    return {
        restrict: 'A',
        link: function (scope, element, attr){
            element.on("$destroy", function() {
                try{
                    console.debug("Going to destroy hot instance");
                    var hotInstance = hotRegisterer.getInstance(attr.hotId);
                    if(!isNaN(hotInstance)){
                       hotInstance.destroy(); 
                    }
					else{
						// this is when post mortem message is thrown.
						console.log("Failed to destroy hot-instance");
					}
                }
                catch(er){
                    console.log(er);
                }
            });
        }
    };
}]);

```

**Comment by swistach** [comment]
Hi @baac0 and @tympollack 
We checked this issue, but in our opinion everything works as we expected (in 0.28.4).

**Comment by AMBudnik** [comment]
@baac0 can you confirm that it works better now?

**Comment by baac0** [comment]
Unfortunately, the issue is still present; I took the liberty to adapt @tympollack 's fiddle a little to clearly demonstrate the issue: https://jsfiddle.net/ee1Le2h6/2/
Just press the "reload table" button a few times, then create a heap dump.

**Problem analysis**;
When _hot.selectCell(1, 1)_ is called in the sample code, ultimately function _getEditor(editorName, hotInstance)_ in file **editor.js** is invoked. This in turn calls _RegisteredEditor.getInstance(hotInstance)_ which adds an editor instance to the _instances_ array once per Handsontable instance. Unfortunately, this array element is not removed when the corresponding Handsontable instance is destroyed; thus, when multiple tables are created (and also destroyed), this array keeps on growing. See heap dump:

![image](https://cloud.githubusercontent.com/assets/13137666/19436025/397e23da-946e-11e6-936a-0e87f51e7d2c.png)


**Proposed solution**:
Remove corresponding editor instances from _instances_ array when a table instance is destroyed.

**Comment by AMBudnik** [comment]
Thanks for sharing additional information. I will mark this issue to be discussed.

**Comment by benjamingarcia** [comment]
Hye! 

I have the same issue on my app. We can't clean correctly handsontable.

**Comment by jansiegel** [comment]
Thanks @baac0, it looks like your diagnosis was correct!

**Comment by AMBudnik** [comment]
@baac0 thanks again for sharing.

Can you test if it works without "leaking" in v0.31.1?

**Comment by baac0** [comment]
Checking the fiddle with the new version of handsontable confirms that the memory leak is fixed. Thanks a lot!

**Comment by AMBudnik** [comment]
No, thank for spotting it in the first place :-)

**Comment by tympollack** [comment]
Good job!
