### ISSUE TITLE
datepicker locale

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#2606]
hello,
i don't find a way to translate the date picker in fr , i try to use the fr.js in moment\locale,
but the date picker is always in english
i use the latest version 
any helps would be appreciate.
jmarc

**Comment by AMBudnik** [comment]
Hi maybe [this topic](https://stackoverflow.com/questions/1865091/jquery-datepicker-language) will help.

**Comment by jeanmarc78** [comment]
hi,
handsontable works with pikaday not datepicker, so your answer is not appropriate
jm

**Comment by AMBudnik** [comment]
Sorry, my bad - when it comes to HOT unfortunately there is not an option to change this settings.

**Comment by jeanmarc78** [comment]
no problem aleksandra, maybie in a future version
