### ISSUE TITLE
Strange behavior with custom data

### ISSUE THREAD

**Issue by deedoc** [handsontable/handsontable#2607]
Hello friends.
Could you have a look at this fiddle http://jsfiddle.net/kbwc0g6y/
Here i have to display custom data in cell - i use a custom cellRenderer.
But for 4 values in my table cellRendered called 8 times - first 4 times i have an "[object Object]" string instead of actual value in data table. Last 4 times everything seems ok - i have my objects as value passed in cellRenderer.
Thank you

**Comment by AMBudnik** [comment]
Hi @deedoc if you type `autoColumnSize: false` instead of `true` value you only get data you wanted. It's a autoColumnSize plugin issue.

**Comment by AMBudnik** [comment]
Hi @deedoc I checked that with latest version 0.24.1 and it seems that it works fine. Can you check that please?

**Comment by deedoc** [comment]
Checked my demo - [](http://jsfiddle.net/kbwc0g6y/)
Almost everything seems ok - a normal object passes every time
But a have noticed that with `autoColumnSize: true` renderer called 8 times. I dare to suggest that it called twice for each cell because of autosizing

**Comment by AMBudnik** [comment]
Thanks for a prompt feedback @deedoc so maybe it's more like this issue https://github.com/handsontable/handsontable/issues/2152?

**Comment by deedoc** [comment]
In http://jsfiddle.net/tw9ec3bx/ from #2152 i can see situation, that worse then mine. Checked:

- `autoColumnSize: false` - everything is ok - one renderer call per one cell
- `autoColumnSize: true` - 3 (three!) calls per cell

**Comment by AMBudnik** [comment]
so if you would have any additional information/suggestions or tips related to this issue please comment at https://github.com/handsontable/handsontable/issues/2152
