### ISSUE TITLE
Finance demo sort is alphabetical on currency

### ISSUE THREAD

**Issue by JasonDalton** [handsontable/handsontable#2610]
In the online demo, the Finance portion shows a table of NBA teams and some stats on each.   Looks like it's using alphabetical sort on the Operating Income column.

**Comment by AMBudnik** [comment]
Indeed this sorting does not work correctly. Thank you for reporting.

**Comment by AMBudnik** [comment]
Sorting broken for http://handsontable.com/examples.html#fndtn-finance column `Vol BTC`

**Comment by AMBudnik** [comment]
Issue closed in lack of a replacement example
