### ISSUE TITLE
Dropdown doesn't allow more than 33 items

### ISSUE THREAD

**Issue by husayt** [handsontable/handsontable#2612]
See example below. There are more than 60 elements in array and yet you can only see 33 of them in dropdown

http://jsfiddle.net/haqog901/1/

**Comment by AMBudnik** [comment]
Thanks for reporting @husayt 

Related to https://github.com/handsontable/handsontable/issues/2505

**Comment by jeanmarc78** [comment]
hello ,
we're also affected by this issue, our users cannot select item if there is not in the "33" first.
i don't find any workaround
is it possible to consider it as a bug with the priority high ?

best regards
jmarc
