### ISSUE TITLE
Sorting merged cells

### ISSUE THREAD

**Issue by jackred** [handsontable/handsontable#2614]
Hi,

I have a problem when merging cells on a column in handsontable and then sorting any other column. On a case where a row has 2 rowspans, and the next one has 3 or a different number, the merged cells don't follow the sorted rows..

**Comment by AMBudnik** [comment]
Could you please prepare a demo showing this example?

**Comment by jackred** [comment]
Here's a JSFiddle https://jsfiddle.net/saidelimam/4Lozhx57/
As you can see, when we sort the first column, the data on the second one is not correct.
I guess when sorting, merged cells should be separated to show correct data.

Also when we sort the second column, the data displayed isn't correct.
There's only 2 cells to be sorted, and other rows from the first column should follow the cell. Instead now it sorts the column as if there still are 5 rows, and then displays it with the same merge configuration.

We tried updating manually the merge configuration on sort to correct it, but there's also another issue with dynamically updating mergeCells..

Please correct this, we're using handsontable for a production application.

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/2547
