### ISSUE TITLE
Keyboard Up/Down does not scroll through options in autocomplete

### ISSUE THREAD

**Issue by Zerseu** [handsontable/handsontable#2616]
http://docs.handsontable.com/0.15.1/demo-autocomplete.html

Happens in the "Autocomplete strict mode (Ajax)" example.
To reproduce the behaviour, first edit the "Year" or "Chassis color" fields and afterwards try editing the "Car" autocomplete. Pressing the Up/Down keys does not scroll through the options. If on the other hand, you begin editing the table with the autocomplete field, it works fine.

Thank you

**Comment by AMBudnik** [comment]
You're right keybord nav does not work after editing other cell. Thanks for reporting @Zerseu
