### ISSUE TITLE
Comma separator changes to dot after pasting values

### ISSUE THREAD

**Issue by Hazepusik** [handsontable/handsontable#2617]
In latest version after copying numeric values with comma separator they pasted with dot separator to Excel or any other text field. For example, copying 1,234 from HOT to Excel gives 1.234 as a result.

**Comment by AMBudnik** [comment]
You're right. Data that is copied is like data that is in editing mode.

![zrzut ekranu 2015-07-08 o 11 20 00](https://cloud.githubusercontent.com/assets/10757813/8567208/c34e5d76-2563-11e5-977e-9da52573ac23.png)
![zrzut ekranu 2015-07-08 o 11 19 57](https://cloud.githubusercontent.com/assets/10757813/8567209/c34f2472-2563-11e5-835c-03221a547137.png)
([example code](https://jsfiddle.net/23jpLgff/1/))
result: 7000

**Comment by Hazepusik** [comment]
I'm not sure whether you understand me right, and so here is an example:
![comma-dot](https://cloud.githubusercontent.com/assets/1913529/8571190/dcf1ff38-258d-11e5-935a-6ecec1b3b35d.gif)

**Comment by AMBudnik** [comment]
Could you check it with the latest 0.24.1 version please?
Here's the demo: http://jsfiddle.net/s5560nq7/2/

Thanks in advance!

**Comment by AMBudnik** [comment]
After some testing I came to an conclusion that it is not a bug, as the data is copied from the source and not after formatting.
