### ISSUE TITLE
destroy doesnt free the data array

### ISSUE THREAD

**Issue by surfncode** [handsontable/handsontable#2618]
After struggling to find a memory leak in my app. I applied the three snapshot technique using chrome dev tools (http://stackoverflow.com/questions/19621074/finding-javascript-memory-leaks-with-chrome). It appears that the data array passed in HandsonTable is never freed so for single page apps that need to re-create handson table many times that's a real problem. 

Here is a screenshot of my test using jsfiddle:

![capture d ecran 2015-07-08 a 10 41 20](https://cloud.githubusercontent.com/assets/11091641/8566518/d3112066-2588-11e5-894c-adff1a044901.png)

And here is the jsfiddle: http://jsfiddle.net/6nn6dxrs/1/

Step to reproduce:
-open http://jsfiddle.net/6nn6dxrs/1/
-launch chrome dev tools
-in profiles select take head snaphshot
-click the take head snapshot (record button)
-now click the init button in the page
-click the take head snapshot (record button)
-click the init button again
-click the take head snapshot (record button)
-click on snapshot 3
-select "Objects allocated between snapshot 1 and 2" as a filter 
-click on Array (the capitalized one) under Constructor
-put your mouse over the first array under it
-the preview should appear

You can see that it is data array in the first initialisation of handson table(because there is no "bis" suffix) It should have been freed by the call to destroy but somewhat it is retained in memory.

**Comment by AMBudnik** [comment]
Related to https://github.com/handsontable/handsontable/issues/2618

Thanks for sharing @surfncode
