### ISSUE TITLE
Export to Excel - Feature request 420

### ISSUE THREAD

**Issue by sohansoni** [handsontable/handsontable#2619]
Hello, any approximate date when feature request 420 from https://github.com/handsontable/handsontable/wiki/Feature-requests
 will be completed ?

**Comment by AMBudnik** [comment]
Hi @csdpuneteam1 you can track what we are working on tracking [milestone list](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.16.0) it is not identical with the final version, but it gives a lot of hints.

**Comment by csdpuneteam1** [comment]
Thanks for the link, but I dont see export to excel requirement listed there, may i know when will it be taken for development ?

**Comment by AMBudnik** [comment]
It is not planned for the nearest future because we are trying to fix some issues in the first place and then get back to expanding HOT functionalities.
If your project needs this functionality in a deadline you can request for [support services](https://jsfiddle.net/vzzn6w3p/4/).

**Comment by csdpuneteam1** [comment]
I see and totally understand that.
Tthe above link i.e. support services point to the jsfiddle, can you please send the correct link ? :)

**Comment by AMBudnik** [comment]
You right! Here it is http://handsontable.com/support-services.html
