### ISSUE TITLE
Pressing down key (or any navigation arrow) in cell edit mode doesn't navigate to next cell

### ISSUE THREAD

**Issue by homanchou** [handsontable/handsontable#2620]
In excel or open office or google docs (google drive spreadsheet) you can type a value in the cell and press any arrow key and the cell will save (exit edit mode) and navigate to the next cell per the arrow key.

Currently in handsontable if you are in edit mode, hitting any of the arrow keys does nothing, except for the left arrow key which moves the cursor to the left by one character.

My expectation is that the arrow keys always navigate cells, exiting edit mode for you.

**Comment by homanchou** [comment]
I see now that the documentation and code have diverged:

Documentation says that pressing navigation arrows will close the editor and navigate to the active cell.  
http://docs.handsontable.com/0.15.1/tutorial-cell-editor.html

However it looks like this feature was disabled with a recent commit: 

SHA: 3d87486896eaa27e2e9f083748ec2e954e7ae661
Regarding issue:  #2182

Disabling for text makes sense: you would want to turn off arrow navigation if editing a large textarea with multiple lines because without a separate formula bar like excel, honoring the arrow keys navigation means there is no way to navigate the cursor within the text body.

However, can we allow arrow keys for simple numeric cell types?  I feel like it's common behavior or expectation to be able to enter a number and arrow key down or to the right quickly and in succession (editing all my prices).

**Comment by AMBudnik** [comment]
Indeed we decided to use this kind of navigation, but we're planning to let it work (maybe by changing settings) like you described also. I will mark your idea as a feature request.

**Comment by homanchou** [comment]
For now, would this callback serve as a work around to re-enable the arrow keys navigation?  It appears to work for me:
```
hot.updateSettings({
      beforeKeyDown: function (e) {
        var selection = hot.getSelected();
        switch (e.keyCode) {
          //each of the 4 arrow key codes
          case 37:
          case 38:
          case 39:
          case 40:
            hot.selectCell(selection[0], selection[1]);
            break;

        }

      }
```

**Comment by karellm** [comment]
@homanchou I'm a little bit confused with what happened here. As of `0.18.0` pressing up/down arrow while editing a cell doesn't move the selection up/down. Did you reintroduce this feature somewhere? I couldn't find anything in the documentation. 

Thanks

**Comment by AMBudnik** [comment]
Hi @karellm here's the full introduction to what has been changed https://github.com/handsontable/handsontable/releases/tag/0.16.1
