### ISSUE TITLE
After search and reload data, "comments" are gone from cells

### ISSUE THREAD

**Issue by mira67** [handsontable/handsontable#2621]
I followed the comments example for handsontable by following the demo, but after I search the table and reload the results data to handsontable, the comments disappeared (the red small flags are gone), for search operation, I used the code from here: http://my-waking-dream.blogspot.com/2013/12/live-search-filter-for-jquery.html

Any clues? 
Thanks.

**Comment by AMBudnik** [comment]
Thank you @mira67 for reporting. I made a [demo](https://jsfiddle.net/t01na2me/) for this example and `loadData` is not returning comments as it should.

**Comment by mira67** [comment]
What I figured out is, I have to update the "comments" and "cells" setting explicitly after searching. 
Also, if the "columnSorting : true" property is set, the comments won't show up also.

**Comment by AMBudnik** [comment]
I took a second look to this issue and rethink its state again. I guess that using `loadData()` as decribed in the [docs](https://docs.handsontable.com/0.23.0/Core.html#loadData) should erase all additional changes which includes the comments.

I'm closing it but if you would have any suggestions please do not hesitate to leave feedback.
