### ISSUE TITLE
Autocomplete not working in v 0.15.1

### ISSUE THREAD

**Issue by pillaiv** [handsontable/handsontable#2622]
I have spent quite a bit of time and below does not work.

```html
 <hot-column data="Currency" title="'Currency'" type="'autocomplete'">
                    <hot-autocomplete datarows="USD,EUR,TRY,TWO"></hot-autocomplete>
                </hot-column>

or 

assiging the values to scope also does not work either.

    $scope.currencyList = "USD, EUR, TRY, TWO";

"  <hot-column data="Currency" title="'Currency'" type="'autocomplete'">
                    <hot-autocomplete datarows=""></hot-autocomplete>
                </hot-column>"


```
I get the below error for both 

Uncaught TypeError: Cannot read property '1' of undefined

![image](https://cloud.githubusercontent.com/assets/7011974/8593929/287e4ac8-2634-11e5-859f-6d663c5eb55d.png)

**Comment by AMBudnik** [comment]
This issue should be at https://github.com/handsontable/ngHandsontable (angular version of HOT). Please paste your issue at ngHOT.

**Comment by pillaiv** [comment]
Ok. Done
