### ISSUE TITLE
Column and row header click selects all rows in grid

### ISSUE THREAD

**Issue by jregan** [handsontable/handsontable#2623]
Clicking on a row or column header selects all of the rows in the grid, changing the current selection state. This is in addition to the selected row or column highlighting which is fine.

This behavior causes display issues for us since there really isn't a reason to select more than one row in the table in our use case. Plus we believe our users may be likely to select the column headers by mistake, expecting that that will trigger the sort feature.

I've added a fiddle that's just a modified version of the highlighting current row example to really emphasize the grid selection status.

http://docs.handsontable.com/0.15.1/demo-highlighting-current.html (original)
http://jsfiddle.net/vr95pt6p/

**Comment by AMBudnik** [comment]
Thank you very much @jregan we will definitely take it under consider.

**Comment by AMBudnik** [comment]
highly related to https://github.com/handsontable/handsontable/issues/2709
