### ISSUE TITLE
More callbacks - beforeCreateRow and beforeCreateCol

### ISSUE THREAD

**Issue by miyconst** [handsontable/handsontable#2624]
There is `afterCreateRow` callback: http://docs.handsontable.com/0.15.1/tutorial-callbacks.html.

Another `beforeCreateRow` callback with ability to cancel would be really useful.

**Comment by AMBudnik** [comment]
I will mark your idea as a feature request. Thank you for improvement suggestion.

**Comment by AMBudnik** [comment]
we can extend that to `More callbacks - beforeCreateRow and beforeCreateCol`

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
Currently both callbacks are available

1) [beforeCreateRow](https://docs.handsontable.com/pro/1.10.0/Hooks.html#event:beforeCreateRow)
2) [beforeCreateCol](https://docs.handsontable.com/pro/1.10.0/Hooks.html#event:beforeCreateCol)
