### ISSUE TITLE
Feature Request - Select All cells similar to Excel?

### ISSUE THREAD

**Issue by HandsTest** [handsontable/handsontable#2625]
Would it be possible to implement Select all functionality by clicking the small gray square at the intersection of the row and column labels similar to Excel?

**Comment by krzysztofspilka** [comment]
@HandsTest In short, yes:) not sure when, but we plan to do that in the PRO edition. Subscribe to our newsletter http://handsontable.com/sign-up.html to be informed as soon as it is released!
