### ISSUE TITLE
how work persistentState

### ISSUE THREAD

**Issue by trippo** [handsontable/handsontable#2627]
Hi i'm interested to use persistentState but i can't understand if i need only to set persistentState: true or i must define the 3 hooks myself. I tried to set only persistentState:true, but don't work.

Is possible to have a working example of use persistentState.

Thank you

**Comment by AMBudnik** [comment]
Hi @trippo here's a [demo](https://jsfiddle.net/ox9cmhhL/) you have to only set 'persistentState: true' hooks let you play more with settings.

**Comment by trippo** [comment]
Yes but  what do "persistentState: true"? activate only the 3 hooks? because i tried and there isn't anything in localstorage or cookie vars...

**Comment by AMBudnik** [comment]
Hi, you can check directly the [`persistantState` src file](https://github.com/handsontable/handsontable/blob/be8654f78ca84efc982047ca6b399e6c6d99f893/src/plugins/persistentState/persistentState.js)
