### ISSUE TITLE
Reference a cell by clicking it?

### ISSUE THREAD

**Issue by bryanbraun** [handsontable/handsontable#2628]
I can't get handsontable to reference other cells when clicking them. This is a common workflow for spreadsheet tools like Google Sheets & Excel (Online and Desktop).
 
**Google Sheets (& Excel)**
![reference_2](https://cloud.githubusercontent.com/assets/1256329/8640319/02997694-28c2-11e5-9dbd-90c1498f6a0f.gif)

**Handsontable (with formulas = true):**
![reference](https://cloud.githubusercontent.com/assets/1256329/8640320/093a8dda-28c2-11e5-8158-8df15ddfb396.gif)

Is there a setting to enable, or does this feature not exist yet?

**Comment by krzysztofspilka** [comment]
@bryanbraun this feature is currently not available in the formula plugin.

**Comment by bryanbraun** [comment]
Thanks for the response. Are you open to reviewing a pull request that introduces this feature? I may be interested in working on it at some point, but I don't know if you would be willing to bring in the feature or not.

I think it would need to be introduced as a part of https://github.com/handsontable/handsontable-ruleJS, right?

**Comment by AMBudnik** [comment]
Hi @bryanbraun we are always open for pull requests and if your code will pass all tests it can be merged, but if the code is heavier it can take some time to double check it before merging.

**Comment by materliu** [comment]
any update ?

**Comment by AMBudnik** [comment]
Hi @materliu 
This feature is not currently available. If you would like to track our formula project you can check this repository: https://github.com/handsontable/formula-parser/commits/develop

**Comment by materliu** [comment]
Hi @AMBudnik
formula-parser is one great project.
this feature is not currently available, by designed, or it's difficult to achieve ？

**Comment by AMBudnik** [comment]
@materliu we would need to refactor selection mechanism cause now we do not have a multi select option that works in similar matter. It's on our to-do list but it won't be easy to develop.

**Comment by materliu** [comment]
@AMBudnik  do you have one schedule,  when will this feature be added in the future ?  It seems like that you have very little developers.  hard & great work.

**Comment by AMBudnik** [comment]
hi @materliu 
that's right, our team is not big but we're doing our best to deliver best that's possible :)
As there's no stage 1 published yet for the formulas we're not adding any dead-lines for extra features like the one above.

**Comment by materliu** [comment]
@AMBudnik  so thx.

**Comment by AMBudnik** [comment]
Oh..  and here's a list of features that we would like to add before the end of the year:

- Copy-paste (paste only values, formulas, without styling etc.)
- Fill-handle better propagating formulas (variables and constant values/addresses)
- Copy-paste formulas from Excel
- Point-and-click (non-consecutive selection of cells)
- Abstract syntax tree required for a better performance, highlighting the syntax and formula autocomplete
- Look-up type formulas
- Custom formulas like CHILDREN (useful in nested rows - the upcoming feature)
- Array formulas
- Localization of formulas (for different countries)
- Performance improvement: memoization for our parser

**Comment by materliu** [comment]
@AMBudnik  so thx for share,  maybe we can make a pull request in the future.

**Comment by Rex90** [comment]
Hello - any updates on point-and-click formulas?

**Comment by AMBudnik** [comment]
Hi @Rex90 
We'd be more than happy to add it, but the plugin hasn't been pumped up to beta yet so the first step is to fix [some bugs with the logic](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22PRO%3A+formulas%22).

**Comment by jared-deremer** [comment]
@AMBudnik @krzysztofspilka 
Hello, any updates on this feature?

**Comment by AMBudnik** [comment]
Hi @jared-deremer 

I have good and bad news. 

The good news is that we are partly working on it on our side project right now. But the bad news is that this project is massive and it will definitely take us more than a year to get any working version of the software.

**Comment by piloos** [comment]
Hi @AMBudnik ,

Any update on this?  It seems not to be present in v10 yet.  For our company, this is a crucial feature to chose for Handsontable since all our users are spoiled by this behavior in Excel & Google Sheets and they will feel friction when our product using Handsontable won't have this behavior.

**Comment by AMBudnik** [comment]
Hi @piloos 

The Point and Click functionality is planned to be added in the next phase of the Formulas plugin enchantments. However, we do not have any slots available in this or the upcoming sprint. We may get back to the subject of adding new functionalities to the Formulas plugin in 2022. I will make sure to keep you updated.

**Comment by cel-edward** [comment]
Hello - was there ever any update on this? Many thanks!

**Comment by AMBudnik** [comment]
Hi @cel-edward this functionality is not on the roadmap for Q4/25. The next feature we plan to introduce (besides new border styles, empty data state, and new filtering mode - released yesterday in [v16.2.0](https://handsontable.com/docs/16.2/javascript-data-grid/changelog/#_16-2-0)) is Export to Excel. We will then re-review other reported needs.
