### ISSUE TITLE
Autocomplete: only first value is shown

### ISSUE THREAD

**Issue by dev1909** [handsontable/handsontable#2629]
Hi guys,

I look at the autocomplete demo page (http://docs.handsontable.com/0.15.0/demo-autocomplete.html) and can't get it how the dropdown value selection is supposed to work. As long as no value is selected you can choose any one from the list of possible values. But if you have already selected one of them only this one value is shown in the list of possible values. Please, help me out!

![autocomplete](https://cloud.githubusercontent.com/assets/13312601/8647384/d22a57b2-2957-11e5-9986-1d98d6644ac4.png)

**Comment by AMBudnik** [comment]
Hi, `autocomplete` shows values that has a string with typed data, that is why to have all values shown cell has to be erased (empty). 

When you have two-word data like "`Nissan Red`" the "`Nissan`" and "`Nissan Red`" will be shown in this example https://jsfiddle.net/xbhhoz94/

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply.
