### ISSUE TITLE
Default value of observeChanges in handsontable

### ISSUE THREAD

**Issue by mpusarla** [handsontable/handsontable#2630]
The documentation says the default value of observeChanges is false. But it seems to be setting the value to true. Is the default value applicable only when the sort plugin is disabled?

We are the noticing the rendering is invoked multiple times due to this and are wondering if it can be set to false explicitly.

Here is the jsfiddle: http://jsfiddle.net/mpusarla/nva6b8e8/1/

**Comment by AMBudnik** [comment]
Hi, `observeChanges` in default is set to `false` but when sorting plugin is turned on `observeChanges` is set to `true`

**Comment by mpusarla** [comment]
Thanks!

**Comment by MaryElizabethWatson** [comment]
Hi, we are the noticing the rendering is invoked multiple times, too. We set observeChanges to false and didn't find any issue in way we use your grid. Sorting work good as expected, and changes owned to correct row even if we change, when use sorting. observeChanges is required for using sorting? Can you describe some bad scenarious that we can get, when observeChanges set to false and sorting set to true?
