### ISSUE TITLE
When scrolling, editors do not follow the cell being edited.

### ISSUE THREAD

**Issue by lrtherond** [handsontable/handsontable#2631]
![snapshot](https://cloud.githubusercontent.com/assets/1578548/8659702/c7c85e06-2969-11e5-9ff0-aa982297e524.PNG)

On this screenshot, I doubleclicked on the cell with the blue border and then I scrolled down a bit.

You can see that the editor stayed in the same place, while the entire table scrolled as intended.

**Comment by AMBudnik** [comment]
Please prepare a demo showing this issue.

**Comment by drockot** [comment]
http://jsfiddle.net/4wzxL168/1/

The above is a quick extension of the "select" editor demo that has been increased in length and placed in div with a fixed height.  The select list for column B works until you need to scroll the list, then the display position of the list seems to be offset by the amount of scrolling that was done.  This happens for both vertical and horizontal scrolling.

**Comment by drockot** [comment]
I may have misinterpreted the the original bug, but the demo is still valid.  At the top of the list, open the dropdown for one of the rows.  While the select list is displayed, use the mouse wheel to scroll the grid contents.  The grid data moves but the select list remains at it's original location.

**Comment by lrtherond** [comment]
@drockot No, you got it right. We experience exactly the same thing. No amount of CSS tweaking seems to fix it either.

In general, Handsontable messes with CSS behind the scenes way to much. It makes each new release very risky.

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/2421

**Comment by lrtherond** [comment]
This is not fixed in 0.16.1.

**Comment by krzysztofspilka** [comment]
@lrtherond could you provide us with the scenario you follow in 0.16.1? I can't reproduce it.

**Comment by drockot** [comment]
I have to agree with the handsontable developers on this one.  I've created a larger example that included both horizontal and vertical scrolling.  The placement of the dropdown list seems to work as expected, and the control no longer floats over the grid while the grid is being scrolled.

Here is my example.
http://jsfiddle.net/4wzxL168/6/

**Comment by drockot** [comment]
Sorry.  Wrong example.  Please look at
http://jsfiddle.net/8mjcu2hx/

**Comment by drockot** [comment]
Noticed one VERY small issue.  While scrolling with the dropdown editor displayed, the control will display over the scrollbars in both the horizontal and vertical direction.

![image](https://cloud.githubusercontent.com/assets/13333210/9064559/1fcf4ad2-3a9b-11e5-893d-256468828302.png)

Personally, I can live with that.
