### ISSUE TITLE
Column Resizing - handsontable not contained within the container

### ISSUE THREAD

**Issue by mpusarla** [handsontable/handsontable#2632]
Hi,

When I resize a column, handsontable expands beyond the container. Is there a way I can contain the handsontable to within the container so that the horizontabel scroll bar displays and user can scroll to view the columns.

Here is the jsfiddle: http://jsfiddle.net/mpusarla/xnuzkLyL/

**Comment by AMBudnik** [comment]
Hi. HOT doesn't have this functionality but you can choose css to do the work by adding `overflow: scroll;` to your container. Unfortunately you have to add `height` in css also.
