### ISSUE TITLE
CustomBorders - handsontbale becomes too slow

### ISSUE THREAD

**Issue by dev1909** [handsontable/handsontable#2634]
Hi guys,

in our ASP.NET MVC project we use handsontable with custom borders, which are stored in the array that comes from controller. Seems like this works fine only for small tables, for scrollable ones with ~20 rows it gets very slow. As soon as I remove borders at all table gets as quick as that in scrollable tables example.

How can I fix it? Unfortunately, we can't waive custom borders.

Thank you for your support!

**Comment by krzysztofspilka** [comment]
http://jsfiddle.net/dev1909/4mk5kbjh/

**Comment by amcastror** [comment]
Same here in a PHP + symfony project.

**Comment by krzysztofspilka** [comment]
Why not using CSS? By creating custom borders we adding new divs, hence it may work slow. For changing the layout of the entire table use CSS, like in this example: http://jsfiddle.net/4mk5kbjh/2/

**Comment by dev1909** [comment]
Thank you! We solved the problem by using css styling.
