### ISSUE TITLE
How to Call AfterChange method from a button and not on keydown.

### ISSUE THREAD

**Issue by kvnandini** [handsontable/handsontable#2635]
I am a Salesforce developer, I need to call afterchange at once not when everycell is modified i want to  process the complete changes at the controller level.

Please help

**Comment by AMBudnik** [comment]
Hi @kvnandini, you want to change/modify something only once after a button click? Which action you want to achieve?

**Comment by kvnandini** [comment]
I want call afterChange on a button click and not when cell is edited.

**Comment by kvnandini** [comment]
I want afterChange to fire only when I click a button not when i put a value or edit.

**Comment by AMBudnik** [comment]
You can manually call hook like `Handsontable.hooks.run(‚afterChange’, hotInstance, changes, source);` You have to be aware that it can cause issues (other parts of code can listen to this hooks) it's a small posibility but always it's good to know.

**Comment by kvnandini** [comment]
@AMBudnik  thanks for the reply, Can you also tell me how Do I call this from <button onclick=""> submit</button>

**Comment by kvnandini** [comment]
@AMBudnik 
          $(document).ready(function () {
        
    var container = document.getElementById('personal_example');
   
    var customValidator = function (value, callback) {
         setTimeout(function () {
             if (/.+@.+/.test(value)) {
                 alert("true");
                 callback(true);
             } else {
                 alert("failed");
                 callback(false);
             }
         }, 1000);
     };
     
     var copyData;
  
  var headerRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.backgroundColor = '#dceefa';
    td.style.fontWeight = 'bold';
    td.style.textAlign = 'center';
  };
  
  var dropdownstyle = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);    
    td.style.fontWeight = 'normal';
    td.style.fontsize = '50%' ;
    td.style.textAlign = 'center';
  };
  
    var headerRenderer2 = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.backgroundColor = '#F6FAFE';
    td.style.fontWeight = 'bold';
    td.style.textAlign = 'center';
  };
  
  var ReadOnlyRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.backgroundColor = '#FBFBF9';
  };
  
  var diffRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.cellTypes['formula'].renderer.apply(this, arguments);
    td.style.backgroundColor = '#BDD7EE';
    td.style.fontWeight = (col === 11 ? 'bold' : 'normal');
  };
  
  var incomeOrExpensesRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.fontWeight = 'bold';
    td.style.textAlign = 'left';
    td.style.backgroundColor = '#BDD7EE'
  };
  
  var boldAndAlignRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.fontWeight = 'bold';
    td.style.verticalAlign = 'middle';
    td.style.textAlign = 'left';
  };
  
  
 
var personalData;
  
   personalData = [
		 ["INNOVATION YEAR", "", "", "", "  ", "", "", "", "", "", "", "", "", "", ""], //ROW 0
         ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 1
         ["", "", "", "", "", "GROSS P&L", "", "", "", "", "INCREMENTAL P&L", "", "", ""], //ROW 2
         ["", "", "", "", "Y0", "Y1", "Y2", "Y3", "Y4", "Y5", "Y1", "Y2", "Y3", "Y4", "Y5"], //ROW 3
         ["Value Market Share ", " % ", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 4
         ["Value Growth ", " % ", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 5
         ["Volume Growth ", " % ", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 6
         ["Volume ", "", " + ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 7
         ["GSV ", " € '000 ", " + ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 8
         ["Turnover ", " € '000 ", " + ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 9
         ["Supply Chain Cost ", " € '000 ", " - ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 10
         ["Gross Profit ", " € '000 ", " + ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 11
         ["Advertising & Promotions ", " € '000 ", " - ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 12
         ["Profit Before Overheads ", " € '000 ", " + ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 13
         ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 14
         ["GM (% of T/O)", "%", "+", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 15
         ["A&P (% of T/O)", "%", "-", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 16
         ["PBO (% of T/O)", "%", "+", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 17
         ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 18
         ["NPV ", " € '000 ", "", "", "", "", "", "CAPEX ", "", "", "", "", "", "", ""], //ROW 19
         ["IRR", " % ", "", "", "", "", "", "BIC", "", "", "", "", "", "", ""], //ROW 20
         ["Payback ", " Years ", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 21
         ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 22
         ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 23
         ["CALENDAR YEAR ", "", "", "", " ", "", "", "", "", "", "", "", "", "", ""], //ROW 24
         ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 25
         ["", "", "", "", "", "GROSS P&L", "", "", "", "", "INCREMENTAL P&L", "", "", "", ""], //ROW 26
         ["", "", "", "", "Y0", "Y1", "Y2", "Y3", "Y4", "Y5", "Y1", "Y2", "Y3", "Y4", "Y5"], //ROW 27
         ["Value Market Share ", " % ", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 28
         ["Value Growth ", " % ", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 29
         ["Volume Growth ", " % ", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 30
         ["Volume ", "", " + ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 31
         ["GSV ", " € '000 ", " + ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 32
         ["Turnover ", " € '000 ", " + ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 33
         ["Supply Chain Cost ", " € '000 ", " - ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 34
         ["Gross Profit ", " € '000 ", " + ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 35
         ["Advertising & Promotions ", " € '000 ", " - ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 36
         ["Profit Before Overheads ", " € '000 ", " + ", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 37
         ["", "  ", "", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 38
         ["GM (% ofT/O)", "%", "+", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 39
         ["A&P (% of T/O)", "%", "-", "", "", "", "", "", "", "", "", "", "", "", ""], //ROW 40
         ["PBO (% of T/O)", "%", "+", "", "", "", "", "", "", "", "", "", "", "", ""] //ROW 41
    ];
      
      var hot = new Handsontable(container, {
    data: personalData,    
    height: 600,
    fixedRowsTop: 1,
    colHeaders: false,
    rowHeaders: false,
    maxCols: 15,
    maxRows:42,
    formulas: true,
    comments: true,
    colWidths: [195, 62, 35, 1, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62],
    
        cells: function (row, col, prop) {
      var cellProperties = {};
            
      if ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26,28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42].indexOf(row) !== -1 && col >= 0) {
        cellProperties.type = 'numeric';
        cellProperties.format = '£0,0.00';
       // cellProperties.validator = customValidator;
      }
       if ([0,1, 2, 3, 14,18,22,23,24,25,26,27,38].indexOf(row) !== -1 && col >= 0) {
        cellProperties.readOnly = true;
        cellProperties.renderer = ReadOnlyRenderer;
      }else if([19,20].indexOf(row) != -1 && [4, 6, 7,9].indexOf(col) != -1){
        cellProperties.readOnly = true;
        cellProperties.renderer = ReadOnlyRenderer;
      }else if([21].indexOf(row) != -1 && [4,6,7,8,9].indexOf(col) != -1){
        cellProperties.readOnly = true;
        cellProperties.renderer = ReadOnlyRenderer;
      }else if( [8,9,13,14].indexOf(col) != -1 && [19,20].indexOf(row) == -1){
        cellProperties.readOnly = true;
        cellProperties.renderer = ReadOnlyRenderer;
      }else if([0, 1, 2, 3].indexOf(col) != -1 ){
        cellProperties.readOnly = true;
        cellProperties.renderer = headerRenderer2;
      }
      
      if (row === 0) {
        cellProperties.renderer = headerRenderer;
      } else if (row === 1) {
        cellProperties.renderer = headerRenderer2;
      }else if (row === 2) {
        cellProperties.renderer = headerRenderer2;
      }else if (row === 3) {
        cellProperties.renderer = headerRenderer2;
      }else if (row === 24) {
        cellProperties.renderer = headerRenderer;
      }else if (row === 25) {
        cellProperties.renderer = headerRenderer2;
      }else if (row === 26) {
        cellProperties.renderer = headerRenderer2;
      }  else if (row === 27) {
        cellProperties.renderer = headerRenderer2;
      }else if (row === 19 && col === 7) {
        cellProperties.renderer = headerRenderer2;
      } else if (row === 20 && col === 7) {
        cellProperties.renderer = headerRenderer2; 
      } else if (row === 27) {
        cellProperties.renderer = boldAndAlignRenderer;
      } else if (row === 7 && col === 1){
          cellProperties.editor = 'select';
          cellProperties.selectOptions = ['Total Tons', 'Total 000 Tons'];
          cellProperties.readOnly = false;
          cellProperties.type = 'text';
          cellProperties.renderer = dropdownstyle;
      }
      
      return cellProperties;
    },
    mergeCells: [
      {row: 0, col: 0, rowspan: 1, colspan: 15},
      {row: 1, col: 0, rowspan: 1, colspan: 15}, 
      {row: 2, col: 0, rowspan: 1, colspan: 5},
      {row: 2, col: 5, rowspan: 1, colspan: 5},
      {row: 2, col: 10, rowspan: 1, colspan: 5},
      {row: 3, col: 0, rowspan: 1, colspan: 4},      
      {row: 14, col: 0, rowspan: 1, colspan: 15},
      {row: 18, col: 0, rowspan: 1, colspan: 15},    
      {row: 19, col: 9, rowspan: 1, colspan: 6},      
      {row: 20, col: 9, rowspan: 1, colspan: 6},
      {row: 21, col: 6, rowspan: 1, colspan: 9},
      {row: 22, col: 0, rowspan: 2, colspan: 15},
      {row: 23, col: 0, rowspan: 1, colspan: 15},      
      {row: 24, col: 0, rowspan: 1, colspan: 15},
      {row: 25, col: 0, rowspan: 1, colspan: 15},
      {row: 26, col: 5, rowspan: 1, colspan: 5},
      {row: 26, col: 10, rowspan: 1, colspan: 5},
      {row: 26, col: 0, rowspan: 1, colspan: 5},
      {row: 27, col: 0, rowspan: 1, colspan: 4},
      {row: 38, col: 0, rowspan: 1, colspan: 15}
    ],
    
    afterChange: function (changes, source, isValid) {
                        
			 var h = new Object(); 
			 console.log('Changes'+changes);
			 var changesJson = JSON.stringify(changes);
			 console.log('ChangesJson'+changesJson);
             if ((source == "edit" || source == "paste") ) {
                  
             
               for(var i=0; i< changes.length ; i++) {
				console.log('row,column'+ changes[i][0]+changes[i][1]);
                 console.log('new value'+ changes[i][3]); 
                 var str1 = changes[i][0].toString();
				  var str2 = changes[i][1].toString();
				  
				  // var x = new Array(10);
                  //for (var i = 0; i < 10; i++) {
                  //x[i] = new Array(20);
                  // }
                 // x[5][12] = 3.0;
				  
				  var res = str1+str2;
			      h[res] = changes[i][3];
			  }
			 		
				// show the values stored
				for (var k in h) {
				    // use hasOwnProperty to filter out keys from the Object.prototype
				    if (h.hasOwnProperty(k)) {
				       // console.log('key is: ' + k + ', value is: ' + h[k]);
				       console.log('key is: ' + h);
				    }
				}
			// console.log('what is this: '+document.getElementById("C"));
			/* Visualforce.remoting.Manager.invokeAction(
            '{!$RemoteAction.IPM_CustomPickListCountries.getFinancialyear}',
            changesJson, 
            function(result, event){
                if (event.status) {
                   
                } else if (event.type === 'exception') {
                    document.getElementById("responseErrors").innerHTML = 
                        event.message + "<br/>\n<pre>" + event.where + "</pre>";
                } else {
                    document.getElementById("responseErrors").innerHTML = event.message;
                }
            }, 
            {escape: true}
        );*/
             //   copyData = JSON.stringify(changes);
              //  alert(copyData);
                 //[row, prop, oldVal, newVal] ;                
               
                 
                 //getcellValue();
                // alert('after function call');
                                
                //jQuery('[id$=myPlaceholder]').text(copyData) ; 
                
             }
           // }
         },
         
               

         afterValidate: function (isValid, value, row, prop, source) { 
            var errorflag = "false";                   
             if (source == "paste") {                
                 if (!isValid){
                   if(errorflag == "false") { 
                     alert("clearing data, PLease wait Invalid Data Entry.");
                     errorflag = "true"; 
                     hot.clear();                
                    }						                      
                 }

             }else if (source == "edit" ) {
                 if (!isValid){
                     alert("clearing data, PLease wait Invalid Data Entry."); 
                     hot.clear();                  						                      
                 }

             }
         }
         
         
    
  });
});
function getcellValue(){
    alert('in the function');
  // var firstRowValue = $("#personal_example").handsontable('getCell', 4, 0);
    var firstRowValue = hot.getCell(4, 0);
    alert(firstRowValue);
}   

  
		
}

**Comment by kvnandini** [comment]
@AMBudnik even if I am able to persist the data on screen I think my issue will be resolved. is there a way where i can persist data.

**Comment by PradeepGdr** [comment]
var ht = $("#tblDetail");
 $("#btnSave").on('click', function () {
        ht.addHook.run(ht, 'afterChange');
});
here i'm trying to fire HandsonTbale 'afterchange' event from a button click in Jquery. but i'm running an error "Cannot read property 'run' of undefined". appreciate any help.

**Comment by AMBudnik** [comment]
@PradeepGdr I see that you've already figured it out https://github.com/handsontable/handsontable/issues/1861#issuecomment-617607417
