### ISSUE TITLE
After HandsonTable is in DOM event

### ISSUE THREAD

**Issue by JordanSinko** [handsontable/handsontable#2636]
Hi,

I am looking for a way to get a callback after the handsontable has entered the DOM. I have tried using afterInit() and afterRender() but neither are working for me. I need to set the height of the parent container to that of the Handsontable. Any help would be greatly appreciated. Thanks!

**Comment by budnix** [comment]
Hi, maybe `beforeInit` (fired before table created) or `construct` (fired on object initialization - `new Handsontable`) event will be usefull for you? But this events are fired only once during initialization.

**Comment by polevaultweb** [comment]
@JordanSinko did you get this working at all?
