### ISSUE TITLE
in After Change event how can i get all the cell values everytime it is fired. changes gives me only the cell modified, what I need is all the cells.

### ISSUE THREAD

**Issue by kvnandini** [handsontable/handsontable#2637]

**Comment by AMBudnik** [comment]
`afterChange` is fired after every single change. To recieve all cells you can do for each with `getDataAtCell`

**Comment by kvnandini** [comment]
thanks @AMBudnik you are awesome

**Comment by AMBudnik** [comment]
Thanks also. I assume this issue can be closed.
