### ISSUE TITLE
Copy/Paste with Multiple HT Instances

### ISSUE THREAD

**Issue by JordanSinko** [handsontable/handsontable#2638]
With our current system, we have multiple HT instances that contain data. The client would like the functionality to update different tables with other tables data. I have included a JSFiddle of yours where it isn't working in the way we would think - http://jsfiddle.net/01xqbco6/. 

I go to the first instance and copy all data in row 3. I then paste the data in row 2 (works perfect). If I then go to the second instance and try to paste the data in row 4, it pastes the data there AND in row 2. Let me know if there is something that I should be doing differently. By the way, I am using Ctrl + C.

**Comment by JordanSinko** [comment]
Anyone have an idea what is going on? Is it how I am doing it?

**Comment by budnix** [comment]
This is happen because in this demo you pass the same data into different instances. If you try to deep copy data sources then you will see that every think is ok. Fixed demo http://jsfiddle.net/01xqbco6/1/.

**Comment by JordanSinko** [comment]
Okay perfect. Thank you.
