### ISSUE TITLE
How to stop hot.clear() from firing afterChange, what would be the source in this case if someone could help it will be great. 

### ISSUE THREAD

**Issue by kvnandini** [handsontable/handsontable#2642]
@AMBudnik  Can you please help me here?

**Comment by AMBudnik** [comment]
It was not meant to be stopped, because it can cause some issues. Can I ask why you want to do this, what you want to achieve?

**Comment by kvnandini** [comment]
I am now collecting all the changes in a array. Mean to say global array is holding all the changes together, number of times the afterchange is call it just append the changes. and I don't want hot.clear() update to be added to this.

**Comment by AMBudnik** [comment]
Maybe this will help
```js
...
// Some variable
var cleanCalled = false;
...
afterChange: function(changes, source) {
  if (cleanCalled) {
    // detected clear call so we skip it
    cleanCalled = false;
    return;
  }
  // Your code to collect changes
}
...
// after Handsontable initialize we apply 'Monkey patch' to detect clear call
var origClear = hot.clear;
hot.clear = function() {
  cleanCalled = true;
  hot.clear();
};
...
```

**Comment by kvnandini** [comment]
Thanks @AMBudnik This really helped, what i am doing now is that I am call a function function clearAll(){
      cleanCalled = true;
      selection.selectAll();
      selection.empty();
    } which has same code as hot.clear(); this is working for me.

thanks a lot.

**Comment by rohit0662012** [comment]
Hi kvnandini can you provide me a solution where adding new rows to table shouldnt create a event but updating a row should

**Comment by kvnandini** [comment]
Rohit, this technique worked for me.. try setting the variable.. and also
in the afterchange i have created a global array to add only changes i want
to capture..

Some variable
var cleanCalled = false;
...
afterChange: function(changes, source) {
  if (cleanCalled) {
    // detected clear call so we skip it
    cleanCalled = false;
    return;
  }
  // Your code to collect changes
}
...
// after Handsontable initialize we apply 'Monkey patch' to detect clear
call
var origClear = hot.clear;
hot.clear = function() {
  cleanCalled = true;
  hot.clear();
};
...
