### ISSUE TITLE
Broken scrolling on the grouping example.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [handsontable/handsontable#2643]
Scrolling with shift + mouse wheel can cause sheet to go off the screen.

http://docs.handsontable.com/0.16.0/demo-grouping-and-ungrouping.html?_ga=1.181662767.981730759.1437017583

It also works here
http://docs.handsontable.com/0.16.0/demo-scrollbars.html
http://imgur.com/v4GWthl

![image](https://cloud.githubusercontent.com/assets/1968109/8715284/3ff01296-2bd3-11e5-9184-fc760e699ef6.png)

To Reproduce: 

* Click in a cell eg A2
* Hold Shift + Mouse wheel down to scroll right.
* Let go of shift whilst scrolling down still.
* Hold shift and scroll the mouse wheel up (to scroll to the left) it will go out of bounds.

**Comment by AMBudnik** [comment]
I see what you mean, I got 

![zrzut ekranu 2015-07-16 o 12 50 18](https://cloud.githubusercontent.com/assets/10757813/8721253/5a0c067c-2bb9-11e5-85ae-064f2222a190.png)
(in Chrome 43/ OSX)

Thanks for sharing

**Comment by AMBudnik** [comment]
I've tested http://docs.handsontable.com/0.18.0/demo-scrollbars.html with 0.18.0 with provided steps to reproduce an issue - works fine with 0.18.0.

Grouping is unavaiable with 0.18.0

**Comment by LiamKarlMitchell** [comment]
Thanks :)

But wait, grouping (with levels) rows/columns is no longer available? I was planning to use that feature.
Darn...

Doc still links to group demo.
http://docs.handsontable.com/0.18.0/Options.html#groups
Would be nice to support groups if possible...

**Comment by AMBudnik** [comment]
My bad :-) in 0.19.0 it will be unavaiable
