### ISSUE TITLE
Too much recursion error when using custom renderers on handsontable 0.16.0

### ISSUE THREAD

**Issue by darkmavis1980** [handsontable/handsontable#2644]
I have a problem using custom renderers with the new version of handsontable, essentially I extend all the renderers with a custom function that set the entire row as invalid if one of the fields is empty (in my project each rows have to be filled).
I have a function that simple function called BaseRendered inside a class (it's a factory in AngularJS)
```javascript
this.BaseRenderer = function (instance, TD, row, col, prop, value, cellProperties) {
      var afterChange = function(change, source){
        var rowData = instance.getSourceDataAtRow(row);
        if(instance.isEmptyRow(row)){
          _.each(instance.getSettings().columns, function(column){
             //some code to be executed each row
          });
         }// end if
      }; // end afterChange

    // this is a function that simply add the afterChange function to the cellProperties hooks
    hotHelpers.addRendererHook(cellProperties, 'base', 'afterChange', afterChange);
}; // end BaseRendered
```
And after that I simply extend the renderers:
```javascript
Handsontable.BaseRenderer = this.BaseRenderer;
Handsontable.renderers.BaseRenderer = this.BaseRenderer;
Handsontable.renderers.registerRenderer('base', this.BaseRenderer);
```

Again, this code work perfectly on 0.14.1, but I get a "too much recursion" error from the browser.
Any idea what could be the cause of it? Maybe there are some bugs in the handsontable renderers? Or maybe something has been changed in the meanwhile and my code is using deprecated functions?

**Comment by darkmavis1980** [comment]
Tested with Handsontable 0.16.1 and ngHandsontable 0.6.0 and I still have the same issue.
Also I get this warning from Firefox:
`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`

**Comment by AMBudnik** [comment]
Hi @darkmavis1980 I wasn't able to reproduce it. Could you check it with the latest (0.24.1) version?

Thanks in advance!

**Comment by darkmavis1980** [comment]
Hi @AMBudnik it's fixed, it was caused by some code we wrote and that was working fine with previous versions of HOT.

**Comment by AMBudnik** [comment]
Thanks for sharing update @darkmavis1980
