### ISSUE TITLE
how to get value for a cell with formula ?

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#2645]
hi,
i work with handsontable 16 and RuleJS .
i put formula on a cell, i would like to get the formula result,
 i don't find any method to achieve that.
i try with getDataAtCell but it give me the formula not the formula result.

regards 
jmarc

**Comment by AMBudnik** [comment]
Hi, did you typed `formulas: true` to your HOT settings? Maybe create a demo of your code and we'll see what we can do.

**Comment by jeanmarc78** [comment]
hello,
i make a demo analog to http://handsontable.com/examples.html#fndtn-personal
http://jsfiddle.net/jeanmarc/1uqztjmm/2/
jmarc

**Comment by AMBudnik** [comment]
Unfortunately it's not that easy, cause `getDataAtCell` returns the string you typed in you data source. I can only mark this issue as a feature requests.

**Comment by jeanmarc78** [comment]
in examining the handsontable.formula.js
i think, i find a way
http://jsfiddle.net/jeanmarc/1uqztjmm/3/

    	var cellId=hot.plugin.utils.translateCellCoords({row: 1, col: 1});
		
			var formula=hot.getDataAtCell(1, 1);
			formula = formula.substr(1).toUpperCase();
			var newValue = hot.plugin.parse(formula, {row: 1, col: 1, id: cellId});			

				alert(newValue.result);

**Comment by budnix** [comment]
I thing that this is the shortest way to retrieve compiled value by formula from cell `value = hotInstance.plugin.matrix.getItem(hotInstance.plugin.utils.translateCellCoords({row: 1, col: 1})).value`

**Comment by jeanmarc78** [comment]
the shortest is the best,
thanks a lot
jmarc

**Comment by deekshitha-indegene** [comment]
hi i am trying to get the formula values when i am posting the handsontable data by using 
hot.plugin.helper.cellValue(F1);
but hot.plugin is giving undefined value because of this i am getting following error
Uncaught TypeError: Cannot read property 'helper' of undefined
please suggest what is the mistake

**Comment by AMBudnik** [comment]
Hi @deekshitha-indegene 

Can you share a demo with your example?

**Comment by rianran1993** [comment]
in  new version 3.0.0

plguing doesnt have matrix ande utils?
```
 this.hotInstance.getPlugin('matrix')
 this.hotInstance.getPlugin('utils')
```
RETURN UNDEFINED

**Comment by AMBudnik** [comment]
Hi @rianran1993 we do not have plugins with that names. What you would like to achieve?

**Comment by jnitika93** [comment]
I am still not able to fetch the computed cell value, or maybe I am not able to use the code correctly. please help
`
					  data: data,
					  cells: function(row, col, prop){
					    	var cellProperties = {};
					    	if(col%2==0){
					      	cellProperties.readOnly = 'true'
					      }
					      return cellProperties
					    },
					    afterChange: function (change, source) {
					    	if(change!=null){
					    	//alert(change,source)
					    	var row = change.toString().split(",")[0]
					    	var col = change.toString().split(",")[1]
					    	var val = change.toString().split(",")[3]
					    	var s = val+hashmap[row]
					    	

					    	alert("row:"+row+" col:"+col+" val:"+val + " error:"+map.errormap[row].split("@@")[0]  +"score:"+s)
					    	}
					        if (source === 'loadData') {
					          return; //don't save this change
					        }
					      
					        alert(hot.getDataAtRow(1))
					      
					      }
					    
					    
					`
I want the value inside the afterchange function .Also please let me know which other plugins have been used for the same

**Comment by AMBudnik** [comment]
Hi @jnitika93 

what is an exact scenario that you'd like to cover? Can we work on this demo https://jsfiddle.net/handsoncode/xa97Ldey/?

**Comment by jnitika93** [comment]
@AMBudnik Hi
Thanks for creating the demo, my requirement is as simple as getting the value of the computed column (C2 in this case) as and when I change the value of either of the parameters. I need to store both the entered and the calculated values in the database and my table is a big one having many formula cells!
Any help would be appreciated!

**Comment by jnitika93** [comment]
I see @budnix  solution being liked, but I am not able to use it in my code.

**Comment by AMBudnik** [comment]
Hi @jnitika93 

this issue is old, we have introduced two data method where one serves you the formula and the second the result. Here's a demo https://jsfiddle.net/handsoncode/67xzty5L/
Let me know if it meets your requirements.

**Comment by jnitika93** [comment]
@AMBudnik  all I want is to get the computed value of  cell B5 when I change the value of either of the cells(A2 or A5)

**Comment by jnitika93** [comment]
What u have given will get me the computed value after the whole table is rendered.with predefined data, But it won't fetch me the dynamic value for the formula cell, every time I change the values of parent cells

**Comment by AMBudnik** [comment]
If you want to make it dynamic you can use the `afterChange` hook like here https://jsfiddle.net/handsoncode/dwk1ectu/
