### ISSUE TITLE
Customisation of active cell in a range of cells

### ISSUE THREAD

**Issue by Sweet-Bob** [handsontable/handsontable#2646]
Hi,    
I want change active cell in range, like on screenshot:    
![Alt text](https://monosnap.com/file/aYGayatJosNfzPgLgDlihXcLYIgfPu.png)

Now selected B2, but i want select D4 cell as active (How i think, it must will be processing with hook afterSelectionEnd)

For example:   
```javascript
afterSelectionEnd: function(r, c, re, ce){
                var selectedCells = this.getSelectedRange();
                this.selectCell(selectedCells.to.row, selectedCells.to.col);
},
```

But i get recursion.    
Maybe have a complete solution?

**Comment by AMBudnik** [comment]
Unfortunately there's no functionality and simple workaround that will not cause issue. I will mark your idea as a feature request.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
