### ISSUE TITLE
Getting " TypeError: object is not an object - return removeSymbolKeys($keys(object)); "

### ISSUE THREAD

**Issue by crazyjavatricks** [handsontable/handsontable#2648]
Hi,
I am using HOT 0.12V. When i tried 0.16V the below error is getting in console while doing operations in HOT. This results in unexpected behaviours also.

TypeError: object is not an object
return removeSymbolKeys($keys(object));

removeSymbolKeys is not there in 0.12V. What should I do?

**Comment by AMBudnik** [comment]
Please create a demo of your code showing this behaviour.

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply.
