### ISSUE TITLE
Multiline column headers  ,bugs can not fix by myself

### ISSUE THREAD

**Issue by myflash163** [handsontable/handsontable#2650]
I had used your web excel for period of time ,but I could not resolve a problem.
   I need the function like the pictures follow.(the follow pictures were completed by handsontable of version 9)

![image](https://cloud.githubusercontent.com/assets/13382818/8750474/22ea32aa-2cda-11e5-9d4f-a668c718262a.png)
![image](https://cloud.githubusercontent.com/assets/13382818/8750495/3e47adac-2cda-11e5-8214-af0b4e7e6ce7.png)

![image](https://cloud.githubusercontent.com/assets/13382818/8750498/453e96de-2cda-11e5-88ab-99e00d9708f4.png)

I need Multiline column headers,every header need a link(<a></a>) to execute a  method for other functions .
every header need a checkbox to tell me which column the users has select .
I had realize this function ,the method has two.
The first one:
I add a method in jquery.handsontable.helper.js .The code like the picture follow
![image](https://cloud.githubusercontent.com/assets/13382818/8750508/5b69364e-2cda-11e5-9ece-a2ccbe752798.png)

i execute the method in jsp like       tab.handsontable("setMcolHeaders", colHeaders);  
--------------------------------------------------------------------------------------------------------------------------------------
The second method like the picture follow
![image](https://cloud.githubusercontent.com/assets/13382818/8750516/71854b84-2cda-11e5-8af1-cb2508e852a9.png)

I replace the thead after the handsontable finished!
I want the Multiline column headers like the follow picture,
but picture was completed  by easyui datagrid.(but  easyui datagrid could not support ctrl+c,ctrl +v,or big data).
![image](https://cloud.githubusercontent.com/assets/13382818/8750529/7f5a47fa-2cda-11e5-9df0-f76298ba822d.png)
![image](https://cloud.githubusercontent.com/assets/13382818/8750533/8462f49a-2cda-11e5-912b-90a31c1c50f3.png)

I know the two methods are wrong.But the  bug could not solved by myself.
After I finished this,I find that I could not adjust the column width auto  by the length of data.I had to set a fixed width .
the second bug is when the width over screen,the column head does not scroll with horizontal scroll bar.
there is another problem ,that is  the web program must support the  ie8.
so I would not choose the handsontable of version 11 or later.(the version10 or 11 has some bug in  ie8 or firfox).so I use the version 9 now.

**Comment by AMBudnik** [comment]
Hi @myflash163 are you still having issues with this one?

**Comment by myflash163** [comment]
SomeOne from Korean have solve the problem since I raise the question in goolge team

**Comment by AMBudnik** [comment]
Thanks for your feedback
