### ISSUE TITLE
Allow selection of text in read-only cells

### ISSUE THREAD

**Issue by zekedroid** [handsontable/handsontable#2651]
When making a cell readOnly in Handsontable (0.16), it no longer brings up the editor. Because of this, selecting/highlighting the text on that cell becomes disabled as well; this feature is enabled in the editor, of course.

Is there a way to re-enable user-select so that a user could highlight and copy text from these cells? Or any cell, even editable cells. 

It's clear that this is the intended behavior since the double click or click events get shorted out to allow for the editor to render. This is why I'm making the case that read-only cells should not have the click events halted.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by dgwyer** [comment]
I've only just started using HOT and this is one of the first things I came across. I want to use HOT as the editor in a backend web app, and then display this table on the front end styled as a 'static' read only table in various styles.

When the table is read only it's a bit of an issue that you can select the text as you can for a normal HTML table.

I'd really like HOT to allow you to select text like a normal HTML table when disabled. I'm using this code to make the table read only.

`
var hot = new Handsontable(container, {
  data: data,
	readOnly: true, // make table cells read-only
  contextMenu: false, // disable context menu to change things
  disableVisualSelection: true, // prevent user from visually selecting
  manualColumnResize: false, // prevent dragging to resize columns
  manualRowResize: false, // prevent dragging to resize rows
  comments: false // prevent editing of comments
});
`

**Comment by AMBudnik** [comment]
Hi @dgwyer 

maybe these settings will meet your requirements http://jsfiddle.net/Ljt6w8w5/?

ps. `manualRowResize`, `comments` and `contextMenu` and disabled by default, so you do not need to add it to the settings.

**Comment by dgwyer** [comment]
Hi @AMBudnik, Thanks. That works great!

**Comment by dgwyer** [comment]
By the way is it also possible to add a setting to not show any highlight on column, or row headers?

On the example below the table cells are disabled from all interaction but the column and row headers still show highlighting when you click on a cell (or header): https://codepen.io/dgwyer/pen/347b8f5b1ddcc167ebf66f2af43bbcf1?editors=0010

Is there a setting to disable this too?

**Comment by AMBudnik** [comment]
There's o official way @dgwyer but you can overwrite the `ht__highlight` class like so

```
.handsontable .ht__highlight{
	background-color: #f3f3f3 !important;
}
```

**Comment by dgwyer** [comment]
Thanks again, that worked. :)

https://codepen.io/dgwyer/pen/347b8f5b1ddcc167ebf66f2af43bbcf1?editors=0110

**Comment by AMBudnik** [comment]
You're welcome @dgwyer

**Comment by AMBudnik** [comment]
Hi all,

As we currently use Github Discussions to discuss new functionalities and changes, please refer to this topic using the new address.

I also encourage everyone interested in the subject to leave their comments.

Thanks!
