### ISSUE TITLE
pikaday should display above selected cell when there is no space below

### ISSUE THREAD

**Issue by surfncode** [handsontable/handsontable#2652]
Currently it can be partially hidden if the selected cell is in the last visible rows.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
The following issue is reported and continued at https://github.com/handsontable/handsontable/issues/3483
