### ISSUE TITLE
manualColumnMove option causes unexpected behavior on column freezing

### ISSUE THREAD

**Issue by 2slow** [handsontable/handsontable#2655]
When the manualColumnMove option is set to true, the column freezing doesn't have the expected behavior: on freezing a column, it's now the first non freezed column which is frozen in place of the selected one.

JSFiddle: 
http://jsfiddle.net/yxpsz2wy/

Column A and B are fixed. Try to free Column H, it's the column C which is frozen. Try again and it's now column D.

**Comment by AMBudnik** [comment]
Confirmed. Thank you for reporting @2slow

**Comment by AMBudnik** [comment]
Issue no longer exists. Updated demo to 0.24.1: http://jsfiddle.net/yxpsz2wy/6/
