### ISSUE TITLE
Bootstrap integration example missing actual bootstrap CSS

### ISSUE THREAD

**Issue by zekedroid** [handsontable/handsontable#2656]
Trying out the Bootstrap integration example. The code kind of works, with the exception of clone tables (used for freezing cells). It looks like it adds the CSS correctly to the clones but the scrolling (virtual?) gets thrown off and scrolls faster than the real table. I made a fiddle with an example. Also, as for the example on the documentation page, it has the bootstrap JS file but not the CSS so it wasn't actually doing anything :)

http://jsfiddle.net/zekedroid/8hk8tgth/

**Comment by krzysztofspilka** [comment]
@zekedroid that is definitely a bug, it shouldn't work like that. And thanks for letting us know about the docs.

**Comment by zekedroid** [comment]
Yeah the scrolling issue makes me think it has to do with how the virtual scroller calculates heights of rows? Since bootstrap changes the height, it must be throwing it off somewhere. It gets a little messier if there are checkboxes in the frozen rows because that adds height to the rows if bootstrap is setup that way, throwing off the alignment of that clone table.

**Comment by jansiegel** [comment]
@zekedroid, to make Handsontable work correctly with Bootstrap, you will need to add a separate css file from our `plugins/bootstrap` directory:
https://github.com/handsontable/handsontable/tree/master/plugins/bootstrap

This should fix most of the glitches
