### ISSUE TITLE
comments not displayed correctly at the right position

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#2657]
hi,
when i scroll , the comments are not displayed correctly 
in the following example , i put a comment at row 30
http://jsfiddle.net/jeanmarc/9mc4ccyc/

regards
jm

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 thanks for sharing. Please track changes to https://github.com/handsontable/handsontable/issues/2196 it's about the same issue.
