### ISSUE TITLE
Scrollbar demo not working in Chrome, Firefox, Safari

### ISSUE THREAD

**Issue by javajosh** [handsontable/handsontable#2658]
Starting state looks good:

http://docs.handsontable.com/0.15.0-beta6/demo-scrollbars.html

![image](https://cloud.githubusercontent.com/assets/18854/8783095/8983a97e-2ece-11e5-99ce-908d7e73f0e3.png)

Click "Maximize Table"

![image](https://cloud.githubusercontent.com/assets/18854/8783083/7033227e-2ece-11e5-9e7a-5da3e6ba69c5.png)

Problem 1: The the table isn't maximized
Problem 2: There is a chunk missing from the right-hand side of the table.

Tested with Chrome 43, Firefox 39, Safari 8 on OSX 10.10.4.

**Comment by AMBudnik** [comment]
Thank you for reporting.

**Comment by javajosh** [comment]
Thank you for maintaining a useful library :+1:

**Comment by AMBudnik** [comment]
`maximize` button abandoned 0.18.0 (http://docs.handsontable.com/0.18.0/demo-scrollbars.html)
