### ISSUE TITLE
There are many image 404's showing up on scroll

### ISSUE THREAD

**Issue by javajosh** [handsontable/handsontable#2659]
I have a table with HTML renderers rendering img tags. When I scroll, I see a lot of 404 messages in the console. This concerns me because it implies that Handsontable is dynamically reloading images when you scroll to them (and unloading them when you scroll away). 

This is a brilliant idea for huge tables where not all images can be kept in RAM - but for smaller tables up to say 1000 rows, it's actually better to keep images in memory.

**Comment by AMBudnik** [comment]
Please create a demo of your code showing this issue.

**Comment by AMBudnik** [comment]
Closed in lack of needed demo.
