### ISSUE TITLE
Tooltips in column neaders ?

### ISSUE THREAD

**Issue by hansgru** [handsontable/handsontable#2661]
How to render tooltips in the column headers too? e.g. in case the user is using the ```columnHeaders``` property ?
Is this supported at all?

Thank you.

**Comment by AMBudnik** [comment]
There is no functionality for tooltips only comments but they aren't able to use with headers.

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/2707 for updates related to tooltips
