### ISSUE TITLE
Problem validation for empty date

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#2662]
hello,
i use the 
http://docs.handsontable.com/0.16.0/demo-date.html

i click on a cell date and i click "backspace", the cell is empty but seems to be invalid(background red).

regards
jm

**Comment by AMBudnik** [comment]
Thank you @jeanmarc78 but `date` type cell ought to act like this after erasing it's content cause the valid type for this sell is `date`. What it should look like in your opinion?

**Comment by rjansen72** [comment]
It appears that recent changes to the DateValidator require a valid date value, with empty string being invalid. 
To work around this I added a simple custom validator for our date cells. This is a snippet of what it looks like:
          validator: function(value, callback) {
            if (!value) {
              callback(true);
            } else {
              Handsontable.DateValidator.call(this, value, callback);
            }
          }

**Comment by budnix** [comment]
Maybe this is good opportunity to add new options like `allowEmpty: true` in the feature? Similar to [allowInvalid](http://docs.handsontable.com/0.16.0/Options.html#allowInvalid)

**Comment by jeanmarc78** [comment]
for numeric cells, it's possible to have empty cells, i don't understand why the behavior would change between numeric validator and date validator.
best regards
jm

**Comment by IgorShch** [comment]
+1

**Comment by krzysztofspilka** [comment]
It works now. allowEmpty: true is turned on by default. I set it to false here:http://jsfiddle.net/0c6c939m/ with my locally built package and it indicates the incorrect value properly both in date and numeric cells.
