### ISSUE TITLE
need more context when handling paste operation

### ISSUE THREAD

**Issue by rjansen72** [handsontable/handsontable#2663]
In our integration with HoT we have a custom column type which is essentially a key/value pair edited via a dropdown. The backend stores just the key, while our custom renderer displays the value associated with the key. When copying a value from a cell in this column to other cells in the same column, it works as expected, since the underlying key value is actually copied. However, if the user pastes the value into a different column (plain text for example) then the key value is rendered. It all makes sense, but it would be great to have some context in the afterChanges callback (or perhaps new hooks into copy/paste) so that we could tell which column the data was copied from and provide the display value when needed.

**Comment by AMBudnik** [comment]
Thanks for suggestion, we will take it under consider while planning new functionalities.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
