### ISSUE TITLE
how to paste the data from clipboard by selection all cells, using button.

### ISSUE THREAD

**Issue by kvnandini** [handsontable/handsontable#2665]
I want to create button called Paste, on click of it i want to select all the cells from the handsontable and paste the clipboard data to the selection.

@AMBudnik any suggestions? How can i do this?

Thanks,

**Comment by AMBudnik** [comment]
Hi @kvnandini to paste data into cells you can use `setDataAtCell` after using `getSelectedRange` if you want to paste data for a range of cells that your instance has. In this case you can cut your clipboard data   depending on hot instance dimentions. 
If the data in clipboard can be wider or smaller than data in hot instance you don't have to use `getSelectedRange` only use `hot.selectCell(0,0);` to paste data from the beggining of the table.

**Comment by kvnandini** [comment]
@AMBudnik 
 function PasteAll(){
      hot.selectCell(0, 0, 41, 14, 0, true);
      hot.pasteMode();
    }
the above function is selection the range of cell but not pasting the data. Is there a way to do it . I am using Chrome browser will that be a problem?

**Comment by kvnandini** [comment]
@AMBudnik 
function PasteAll(){
       var clipText = window.clipboardData.getData('Text');
       // hot.selectCell(0,0); 
        alert(clipText);
      hot.copyPaste.triggerPaste(null, clipText);      
     
    }this is working only in IE but clipboard data is not copied properly in IE but it is pasting in the grid only in IE.. and not in chrome or firefox, can you please help me achieve this.

**Comment by AMBudnik** [comment]
`hot.copyPaste.triggerPaste()` is meant to work in/ between HOT instances. It can work outside the grid (at the same website) but it's not for sure.

**Comment by kvnandini** [comment]
yes PasteAll is outside the grid which is call on click of a button.

**Comment by alvarotrigo** [comment]
+1

**Comment by kvnandini** [comment]
@AMBudnik : the functionlity i am trying to achieve is to paste the data on the grid which is already in the clipboard. this is not working i had got my client postpone the paste functionality for further release now its time for me to work on this .. none of ways i have tried is working

**Comment by AMBudnik** [comment]
Hi @kvnandini 
I think that we are missing the solution of this issue https://github.com/handsontable/handsontable/issues/3496 but maybe I'm wrong.
Did you made any progress or created a workaround?

**Comment by AMBudnik** [comment]
I think we'll have to stick to #3496. I'm closing this issue.
