### ISSUE TITLE
Cell highlighted as invalid when trying to enter invalid data when allowInvalid set to false

### ISSUE THREAD

**Issue by stirlingpoon** [handsontable/handsontable#2666]
If the user tries to type in data when allowInvalid is false, the cell will maintain editor state even when the user presses Enter. However, when the user presses the Esc key and the cell reverts in its original content, the cell is still highlighted as invalid. This is confusing to the user as the original content of the cell is valid.

Demo: https://jsfiddle.net/o2uap438/

**Comment by AMBudnik** [comment]
Hi @stirlingpoon I've tried to reproduce the behavior in FF 38 and Chrome 44 and couldn't reproduce it. Which OS/Browser are you using?

**Comment by stirlingpoon** [comment]
Tested on Mac OS X 10.10.4: Chrome 44.0.2403.89 (64-bit), Chrome Canary 46.0.2462.0 canary (64-bit) and FF 39.0

The steps to reproduce are:
1. Click on cell A1 and type 'e'
2. Press enter key
3. Editor does not disappear and waits for correct input, press escape key
4. Cell A1 shows 1 but it is highlighted as invalid

**Comment by AMBudnik** [comment]
Please update to [0.19.0](https://github.com/handsontable/handsontable/releases/tag/0.19.0) this issue does not occur with this version.
