### ISSUE TITLE
autoColumnSize does not take into account merged cells

### ISSUE THREAD

**Issue by stirlingpoon** [handsontable/handsontable#2667]
When cells are merged the contents of one flow into other cells but autoColumnSize does not seem to take that into account. In the demo before column one takes the width of the long text content even though it is merged with its neighbouring cell.

Demo: https://jsfiddle.net/hwxy018f/

**Comment by AMBudnik** [comment]
This happens cause table width is counted when it's created and not after merging. 
Thank you for feedback. I guess it could be an option to change table dimensions in cases like this.

**Comment by AMBudnik** [comment]
After a second look at this issue I assume it should be marked more as a bug than a feature.

**Comment by kunnix** [comment]
Super ugly workaround for those in need (by using a custom renderer): https://jsfiddle.net/afpbymp2/1/

Note: if your text width exceeds the cell width, it'll be truncated.

**Comment by mattmccutchen** [comment]
I needed this for the Object Spreadsheets project and have what I think is a reasonable implementation in [our fork](https://bitbucket.org/objsheets/handsontable/); I might be persuaded to spend some time helping to upstream it if the Handsontable maintainers are interested.  Our code chooses the column sizes greedily from left to right; each column is sized to fit all cells whose span ends in that column, based on the previously chosen sizes for the previous columns.  (The behavior should be analogous for rows, but I haven't tested it.)  This made sense for our use cases; I don't know what the default browser layout of `<table>` does.

**Comment by jansiegel** [comment]
Probably related to #4083.

**Comment by AMBudnik** [comment]
Current situation in v `2.0.0`

![image](https://user-images.githubusercontent.com/10757813/39356673-eab51740-4a10-11e8-88d8-09d2b764be3b.png)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **MergeCells grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
