### ISSUE TITLE
Viewport shrinks if column groups are collapsed

### ISSUE THREAD

**Issue by stirlingpoon** [handsontable/handsontable#2668]
If some columns are not visible in the viewport before collapsing groups and then the groups are collapsed, the viewport shrinks.

In the demo below, if all of the groups are collapsed then only 3-5 columns are shown without the user scrolling, while before collapsing 9 are shown. From observation it appears that the last column pre and post collapsing are the same if the last column is not in a group. Furthermore, row groups seem to be unaffected.

Demo: https://jsfiddle.net/1e8hqyLj/

**Comment by AMBudnik** [comment]
Grouping feature is deprecated. We do not support it in newer versions.
