### ISSUE TITLE
Table does not follow cursor if column groups are collapsed then expanded

### ISSUE THREAD

**Issue by stirlingpoon** [handsontable/handsontable#2669]
If the table has columns outside the viewport, after collapsing column groups and then expanding them, the table does not move along with the cursor if the cursor move offscreen to the right.

Demo: https://jsfiddle.net/1e8hqyLj/
Steps to reproduce:
1. Select cell A1 and press the left arrow key continuously until the table moves along with the cursor, then continuously press the right arrow key to return to A1.
2. Press the groups 1 button to collapse all column groups, then 2 to expand them.
3. Do step 1 again but now the table does not move along with the cursor.

It has been observed that if the table is allowed to re-render between steps 2 and 3 (eg. switching tabs) then step 3 may work. Furthermore row groups does not appear to be affected.

**Comment by AMBudnik** [comment]
Confirmed.

**Comment by AMBudnik** [comment]
Grouping abbanoded according to https://github.com/handsontable/handsontable/releases/tag/0.18.0
Instead, we're working on a very similiar functionality - Nested Rows

**Comment by AMBudnik** [comment]
Update: grouping will no longer be supported from 0.19.0
