### ISSUE TITLE
Improvement of fill handle down and right.

### ISSUE THREAD

**Issue by iDevSK** [handsontable/handsontable#267]
This fill handle function is pretty good. but, there's one things i think sad.

I used to MS Excel, i feel it's something different.

In Ms Excel, i drag down fill handle control, the handle going down, and drag-right (keep mouse-y position) then the handle going right. 
(i think if mouse x-position(x-axis length) greater than (y-axis length), it's going right.) 

I think fill handle function of ms excel is more comportable, so plz consider improvement of fill handle function.

Thank you

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topic and uloading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Isuee will be reopene with first update.

**Comment by AMBudnik** [comment]
This behavior seems to be correct in the newer version of Handsontable.

If there's something left to be improved please leave a comment.
