### ISSUE TITLE
Bootstrap integration breaks column grouping functionality

### ISSUE THREAD

**Issue by stirlingpoon** [handsontable/handsontable#2670]
When Bootstrap integration is used, column groups do not collapse when the collapse button is clicked. Furthermore, there are visual issues before and after the collapse button is clicked, including the fragmented grouping indicator and the extra expand buttons that appear when the collapse button is clicked. Note that row groups are not affected. 

Demo: https://jsfiddle.net/xeocyjx8/

**Comment by AMBudnik** [comment]
Grouping feature is deprecated. We do not support it in newer versions.
