### ISSUE TITLE
After some horizontal scroll, the cells shift up and misalign with the row headers

### ISSUE THREAD

**Issue by pangard** [handsontable/handsontable#2671]
This issue can be found for example in this fiddle used in another issue:

https://jsfiddle.net/xeocyjx8/

Simply scroll down to the bottom, then scroll right, and by the middle of the table the cells shift up and misalign with the row headers:

![handsontable_error](https://cloud.githubusercontent.com/assets/286625/8835746/a156bd94-30bc-11e5-96be-22fb37c0fe2f.png)

This is from my own experiments:

![handsontable_error_2](https://cloud.githubusercontent.com/assets/286625/8835789/e5be38ae-30bc-11e5-97f4-1c4ce31d9ba4.png)

I've been trying different widths, heights, and viewport sizes. I don't get why it happens sometimes but not always.
I'm pretty interested in generating tables that may be bigger than the viewport, so that scroll is required, or not, so that no scroll is required. This happens both horizontally and vertically. Having to set the width and height is a problem, because if I set the width too big, the scroll bar is far from the table.

Thanks for reading so far!

**Comment by AMBudnik** [comment]
Indeed the rows are misaligned in this example (screen below) headers are few pixels higher but data seams to be misaligned to headers also.
![zrzut ekranu 2015-07-23 o 09 30 19](https://cloud.githubusercontent.com/assets/10757813/8845263/b9980d52-311d-11e5-82c0-782dc8ec194c.png)

**Comment by AMBudnik** [comment]
Grouping abbanoded according to https://github.com/handsontable/handsontable/releases/tag/0.18.0
Instead, we're working on a very similiar functionality - Nested Rows

**Comment by pangard** [comment]
The example in the fiddle gets fixed indeed if grouping is removed. In my example there was no grouping, so I've been researching a bit more. I'm only getting the error for some screen resolutions, it only happens some times, and the jump happens at different positions of the table.

I couldn't reproduce it as a fiddle, it's not critical and I cannot spend more time in this superfishy bug that affects only cell phone users. Too bad.

Thanks for your attention.

**Comment by AMBudnik** [comment]
Update: grouping will no longer be supported from 0.19.0
