### ISSUE TITLE
merging cells freezing issue 

### ISSUE THREAD

**Issue by vancan1ty** [handsontable/handsontable#2672]
Spanning the leftmost table cell across rows while the left column is fixed results in incorrect behavior.

See this JSFiddle for an example of the incorrect behavior.
https://jsfiddle.net/vancan1ty/3cuqs02t/1/

Note that the rows are NOT being spanned in accordance with mergeCells, and also left column is NOT properly "fixed" when you scroll.
(Testing in Chrome 43)

If I remove the column freezing but leave everything else the same, row spanning then works correctly.
See this fiddle for the correct behavior (sans column freezing).
https://jsfiddle.net/vancan1ty/aje1p9nk/2/

Thanks.

**Comment by vancan1ty** [comment]
corrected second jsfiddle link.

**Comment by AMBudnik** [comment]
Thanks for reporting.

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1 and related with https://github.com/handsontable/handsontable/issues/2162 as the issue occurs where there are no colHeaders

**Comment by AMBudnik** [comment]
Confirmed with freezing columns and rows as mentioned in https://github.com/handsontable/handsontable/issues/2531

**Comment by fmoyses** [comment]
We're facing this same problem. 
@vancan1ty, did you find any workaround?

We've disable the fixed rows/cols, but that's kind of a bummer.

**Comment by AMBudnik** [comment]
Hi,

 just wanted to say that one of our developers will refactor the code of mergeCells in this quarter so hopefully none of above issues would appear after update.

**Comment by lucamaral** [comment]
Hi,

I handled this issue using `rowHeaders: true` and `rowHeaderWidth : 0`.

[Fiddle](https://jsfiddle.net/urhytL7b/)

**Comment by AMBudnik** [comment]
thanks for sharing the tip @lucamaral

**Comment by AMBudnik** [comment]
Remains the same on v 7.0.0 https://jsfiddle.net/AMBudnik/jua5czoe/

**Comment by AMBudnik** [comment]
@wojciechczerniak I think that it can be caused be the same issue as this one https://github.com/handsontable/handsontable/issues/2473

**Comment by AMBudnik** [comment]
This issue is still replicable in v 8.0.0 https://jsfiddle.net/AMBudnik/gjnsL6do/ but as this issue is the same https://github.com/handsontable/handsontable/issues/4016 I'm closing this as a duplicate. 

I will make sure to update this issue after fixing https://github.com/handsontable/handsontable/issues/4016
