### ISSUE TITLE
Programmatically open the editor for a cell

### ISSUE THREAD

**Issue by klikstermkd** [handsontable/handsontable#2675]
Is there a way i can programmatically open the editor for a particular cell? I need this, because i am formatting the text in the cell (e.g. bold), and i want to keep the editor open for that cell so i can apply multiple formats at once, without losing the focus of the cell after applying the first format. Because the library exits the editor if you click somewhere else other than the current cell (e.g. a format button in a toolbar).

Thanks!

**Comment by motin** [comment]
Try this, assuming you have the active editor object (`var activeEditor = instance.getActiveEditor()` or similar). This is modeled after the internal openEditor function (0.16.1)

    // Set initial value for editor
    var initialValue = instance.getDataAtCell(td, row);
    // Prepare a fake keyboard event, as if you had initiated the editor by pressing F2
    var keyCodes = Handsontable.helper.keyCode;
    var event = jQuery.Event('keydown');
    event.keyCode = event.which = keyCodes.F2;
    activeEditor.beginEditing(initialValue, event);
    // Not sure if necessary
    event.preventDefault();

I too am interested in cleaner ways of doing this, but at least this works for now.

**Comment by klikstermkd** [comment]
I already solved it few weeks ago, by taking a similar approach as yours. Here's my solution:
```
// Get the active editor object
var activeEditor = instance.getActiveEditor();
// Select the cell that we want to edit. "hot" is the instance of Handsontable
hot.selectCell(row, col);
activeEditor.beginEditing();
activeEditor.enableFullEditoMode();
```

**Comment by motin** [comment]
Good that you are set. Remember to answer your own questions as soon as you have solved them, for future reference.

**Comment by klikstermkd** [comment]
Ok will do!
