### ISSUE TITLE
Sort indicator is wrong with columnSorting object

### ISSUE THREAD

**Issue by JacobEvelyn** [handsontable/handsontable#2676]
When I initialize a Handsontable with these properties:

```JavaScript
columnSorting: {
  column: 0,
  sortOrder: true
},
sortIndicator: true
```

with a data set that looks like this originally:

Letters  |Foo
------|-------
B|...
C|...
A|...

I get this odd behavior (v indicates a down sort indicator, ^ indicates up, and neither indicates none is showing):

### Initial
Letters  |Foo
------|-------
A|...
B|...
C|...

### After clicking "Letters" once
Letters ^|Foo
------|-------
C|...
B|...
A|...

### After clicking "Letters" again
Letters  |Foo
------|-------
B|...
C|...
A|...

### After clicking "Letters" again
Letters ^|Foo
------|-------
A|...
B|...
C|...

### After clicking "Letters" again
Letters v|Foo
------|-------
C|...
B|...
A|...

...now sort behavior is normal.

**Comment by AMBudnik** [comment]
You're right after clicking once data is sorted incorrectly.

**Comment by rjansen72** [comment]
I am also just hitting this now in our integration. The problem is that the columnSorting property "sortOrderClass" is only set as part of the click handler. I'm fixing this in our local fork.

**Comment by AMBudnik** [comment]
Sorting has been changed since that issue. [Here's](http://jsfiddle.net/gsc4my7s/) the demo for 0.18.0 version which works fine.

**Comment by JacobEvelyn** [comment]
The demo you linked to is exhibiting the same behavior. The ordering is (where each `-->` indicates a click of the header of the Letters column):

```
[ ] --> [^] --> [ ] --> [^] --> [v] --> [ ]
```

In other words, it takes me four clicks to get to one of the sort states (descending) when it should take at most two.

**Comment by AMBudnik** [comment]
When we type only `columnSorting: true` we get 

```[   ] --> [ ^ ] --> [ v ] --> [   ]```

it this example we have `sortOrder: true` which is equal to `[ ^ ]` so after few steps of sorting this data we actually have

```[ ^ ] --> [ v ] --> [   ] --> [ ^ ] --> [ v ] --> [  ]```

**Comment by JacobEvelyn** [comment]
Yep that's correct, but this GitHub Issue (I definitely could have named it something more descriptive) is about the initial "few steps of sorting this data" that you've glossed over.

My point is that as a user, if I want to sort a column in descending order:

1. I click the heading and the column goes from unsorted to ascending, I think, "Great! Now if I click it again it will be descending."
2. I click it again and it goes back to being unsorted. Now I think, "Darn! I guess I can only sort in ascending order." At this point many users will give up.
3. But let's say I don't give up. I'm a very hopeful user and I think, "Well, perhaps there's a small chance that I can sort in either ascending or descending order, but the column goes back to unsorted between *each*, so I'll try clicking one more time." I click it again and once again it's in ascending order. At this point I give up, certain that there's no way to sort it in descending order.

(This user story may seem arbitrary but it's actually the thought process I followed.) Does that make sense?

**Comment by AMBudnik** [comment]
Thank you @JacobEvelyn for full explanation. We'll have to take in under consider.

**Comment by JacobEvelyn** [comment]
Thanks!
