### ISSUE TITLE
Sorting and Conditional Cell Styling

### ISSUE THREAD

**Issue by tsmith14** [handsontable/handsontable#2677]
I'm running into an issue when I'm sorting a table that has different styled cells in a column. When sorting any column, the ascending and descending sorting works fine. But on the third click, when the sorting is essentially cancelled, the data in the table correctly displays but the styling doesn't update correctly.

I tweaked one of the sorting examples to show the problem: http://jsfiddle.net/926Lc7eg/
* I added a basic cell renderer that colors the names of all presidents with an ID greater than 10. 

1. Sort the presidents ids once (nothing happens because they're already in order)
2. Sort again and the ids sort in descending order and the cell styling correctly updates.
3. Sort a third time and the data returns to the original state, but the colored cells are now not highlighting the correct presidents. (The colored cells stay in place. You can replicate this by sorting any column)

As a quick fix, I have disabled the cancelled sorting state altogether. (i.e. once you start sorting you can only go from ascending and descending and vice versa). I couldn't figure out, though, what was causing the issue. 

Thanks!

**Comment by AMBudnik** [comment]
Confirmed. Thanks for sharing @tsmith14

**Comment by AMBudnik** [comment]
Hi @tsmith14 could you please check it with the latest Handsontable 0.24.0 version?

**Comment by AMBudnik** [comment]
works as expected in 0.26.0: http://jsfiddle.net/rmd5ggx5/
