### ISSUE TITLE
setCellMeta() does not set appropriate cell after moving a column

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#2678]
If you move a column then call setCellMeta on one of the cells in that newly moved column, it sets the meta data on the wrong cell.  For example:

1. Move the first column (we'll call it `fieldA`) to the right by 1.  It should now have a `colId` of 1.
2. Make the following calls after the move reveals some issues (pointed out by the comments):

```javascript
var rowId = 0;
var colId = $table.propToCol('fieldA');  // colId === 1
var cellProperties = $table.getCellMeta(rowId, colId);  // Contains `fieldA` cell properties; however, cellProperties.col === 0 instead of an expected 1
$table.setCellMeta(rowId, colId, 'propA', 'valueA');  // This property does not get set on the correct cell.  I suspect it is getting set on the new cell that is now at colId 0 after the move.
```

I suspect `setCellMeta()` is not behaving correctly because it is not doing a `colToProp()` and `translateColIndex()` like `getCellMeta()` is.  Although, there could be more to it than that.

**Comment by AMBudnik** [comment]
Thank you @cgatesman we will take a closer look at this issue.

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/1823

**Comment by AMBudnik** [comment]
Hi @cgatesman could you please try it with your example updated to 0.23.0? We made some changes to related issue.

**Comment by AMBudnik** [comment]
@cgatesman 
can you check it with the latest version?We made a similar fix at 0.26.0 https://github.com/handsontable/handsontable/issues/3551

**Comment by AMBudnik** [comment]
demo for the example: http://jsfiddle.net/qsfLwbvL/

Steps: 
1. Switch column `A` with column `B`.
2. Select second column
3. Click the <kbd>blue</kbd> button

Result: First column got the blue background instead of second.

![row-translate](https://cloud.githubusercontent.com/assets/10757813/18664500/1a52db50-7f23-11e6-8fcd-dc440585e21a.png)

**Comment by AMBudnik** [comment]
update demo to 1.7.3, http://jsfiddle.net/3ztc7h8d/ issue still exists.

**Comment by swistach** [comment]
If original order of columns was changed, you have to add .runHooks('modifyCol', col) to get true logical index of the column. Here's updated demo: http://jsfiddle.net/3ztc7h8d/7/
