### ISSUE TITLE
Dynamically increasing fixedColumnsLeft does not update on the table correctly

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#2679]
In 0.16.0, I'm seeing that if I dynamically increase the `fixedColumnsLeft` using `updateSettings()` (is there a better way?), the table does not make the update until you start scrolling down on the table.  This doesn't appear to be a problem when you decrease the `fixedColumnsLeft`.

```javascript
$table.updateSettings({fixedColumnsLeft: currentFixedColumn + 1});
```

**Comment by AMBudnik** [comment]
Hi @cgatesman 
Using `updateSettings` is the best and easiest way.
I tried it with 0.24.1 example: http://jsfiddle.net/qofgrx0h/ and seems to work fine now.

I'm closing this issue but if I'm missing something and you can see any odd behaviours or bugs here we'll reopen the topic.
