### ISSUE TITLE
First column misaligned with fixed columns and no rowHeaders

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#2680]
You can see in this jsfiddle and the screenshot, below, the right border of the first column is misaligned the the header:

http://jsfiddle.net/ba27jxga/

<img width="519" alt="screen shot 2015-07-23 at 3 21 53 pm" src="https://cloud.githubusercontent.com/assets/6276072/8859963/99c41260-314e-11e5-8ca9-ece14dbfaed6.png">

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/2640

**Comment by budnix** [comment]
Hi, this bug was fixed in 0.16.1. You can find updated demo at http://jsfiddle.net/ba27jxga/1/.
