### ISSUE TITLE
Consider removing all attributes from TD before resuing cells

### ISSUE THREAD

**Issue by rjansen72** [handsontable/handsontable#2681]
We implemented a custom renderer to support "header" rows - rows that consume the entire width of the table. We simply just set the colspan attribute of the appropriate column. This works great, until there are enough rows that require the table to scroll. Since the TD cells are just reused, the colspan property is left behind. I worked around this by hooking afterRenderer to remove the colspan attribute for rows that were not header rows.

**Comment by AMBudnik** [comment]
Hi @rjansen72 can you share a demo or more details? I'm not sure if I understand it correctly.

**Comment by jongunter** [comment]
I'm having a similar issue, as well. 
I have an angular single page app with a handsontable grid. Many cells in the grid have a custom `data-grid-path="value"` attribute. Based on events happening elsewhere on the page (outside of the grid), the application highlights certain fields in the grid,  using `[data-grid-path]` as a selector. When the user scrolls, handsontable re-renders things, but `data-grid-path` gets stuck to some old cells where it should not be present, making our application erroneously highlight some cells.

**Comment by jongunter** [comment]
To work around this, I've just added a td.removeAttribute('data-grid-path') at the beginning of every single renderer (we only use custom renderers).

**Comment by budnix** [comment]
Indeed Handsontable currently removes only classes when reusing TD elements. It's definitely a bug.

**Comment by swistach** [comment]
Hi @rjansen72 and @jongunter 
We don't recommend manipulate with data-attr. You can use cellMeta to storing additional informations. Of course solution which was presented by @jongunters is a good workaround.
If we add to the baseRender, mechanism to manage of the data-attr, then we've performance decrease on each render action.
