### ISSUE TITLE
Find back the original cell during fillhandle or copy/paste

### ISSUE THREAD

**Issue by Iosis555** [handsontable/handsontable#2682]
Hi there, and thanks for your work.

I'm looking for a way to find the "original cell" when you perform a fillhandle or a copy/paste. OnChange and afterChange gives you the original and final values for all cells affected but you can't find the coordinates of your first selected cell (the one you copied).
Have I missed something ?

**Comment by AMBudnik** [comment]
Did you tried [`getCopyableData`](http://docs.handsontable.com/0.16.1/Core.html#getCopyableData)?
