### ISSUE TITLE
Resize fixed rows/columns

### ISSUE THREAD

**Issue by KodjoSuprem** [handsontable/handsontable#2683]
resizing frozen rows is not possible.

Exemple:
http://jsfiddle.net/6c5854ty/

**Comment by AMBudnik** [comment]
Hi @KodjoSuprem which OS/Browser you're using? I tried in on Chrome 44, FF 38 and Safari - all worked fine. The same for Win 7 with IE11 (and Chrome, FF).

**Comment by KodjoSuprem** [comment]
Hello,
I am using Chrome  43.0.2357.134 m

To be more precise, 
it is not possible to resize rows of the frozen pane once you have scrolled down the table.

**Comment by AMBudnik** [comment]
I got it with Chrome 44 also.

Steps: 
1) Scroll down
2) Shorthen 3 row

without scrolling down or scrolling right it works fine.

Thanks for sharing @KodjoSuprem

**Comment by AMBudnik** [comment]
Sometimes it can cause this behaviour
![new](https://cloud.githubusercontent.com/assets/10757813/8874982/2473192a-3216-11e5-8e2f-25f947a2210f.gif)

**Comment by KodjoSuprem** [comment]
I reproduce this easily with JsFiddle (And with my own integration of Hot)
Here what I have on screen:
![bug _hot_2](https://cloud.githubusercontent.com/assets/4376260/8875071/a0716f86-3216-11e5-87df-bf156a89ffd9.gif)

**Comment by KodjoSuprem** [comment]
Hello,
I still have the issue with HoT 0.20.1

tested on Google Chrome 46.0.2490.86 m and IE 11.0.9600

http://jsfiddle.net/2zu1yh1m/1/

![animation](https://cloud.githubusercontent.com/assets/4376260/11472792/221e342a-976f-11e5-9e53-924af282ad4e.gif)

**Comment by AMBudnik** [comment]
Confirmed @KodjoSuprem

**Comment by jansiegel** [comment]
For some reason the fix for this issue was reverted in https://github.com/handsontable/handsontable/commit/4ce1943dc03e7f93cca51fa0cf0d91148f7a2061 and was actually never released. 
Thanks @KodjoSuprem for pointing that out.
