### ISSUE TITLE
When using fixed columns with multiline rows, horizontal scrolling resets row heights

### ISSUE THREAD

**Issue by pw123** [handsontable/handsontable#2686]
Steps to reproduce:
1) Go to http://docs.handsontable.com/0.16.1/demo-freezing.html
2) Enter a multi-line value in a cell of an fixed colum, example: double-click on cell B4, enter an two-line text using ALT+RETURN
(after this step, height of row 4 is correctly adapted to heigth of two lines for all visible colums)
3) scroll horizontally to last colum

Result: During step 3, height of line 4 is reset to heigth of one line text for non fixed columns
Expected result: Height of rows for non fixed columns stays in sync to rows of fixed columns regardless of horizontal scrolling state

**Comment by AMBudnik** [comment]
Thank you @pw123 , issue related to https://github.com/handsontable/handsontable/issues/493

**Comment by budnix** [comment]
Hi, this option is ready to use (since 0.16.0) but for performance reason it is disabled by default. You can enable this via settings `autoRowSize: true`.

**Comment by budnix** [comment]
Demo http://jsfiddle.net/vhs20skm/ :)

**Comment by pw123** [comment]
Thank you for the info on 'autoRowSize: true' and for the jsfiddle demo, with that this issue is solved.
