### ISSUE TITLE
Comments not coming up in case, 2 handsontable  present in the same page and it does not appear for the first row

### ISSUE THREAD

**Issue by Ankitha** [handsontable/handsontable#2687]
I have 2 handson table in my page the comments that I have given is displayed only for the top handson table and for the bottom handson table the comments does not come up for the first row. I am using v0.15.1 version

**Comment by AMBudnik** [comment]
Could you please prepare a demo for this example? Comments are broken only in the first row?

**Comment by AMBudnik** [comment]
Issue will stay closed cause of month without activity, but feel free to add a demo if you'll notice the same issue with recent HOT version.
