### ISSUE TITLE
Marking changed cells' bg

### ISSUE THREAD

**Issue by jiteshvassa** [handsontable/handsontable#2689]
When making programmatic changes to a data structure.  Is it possible to highlight cells that have changed in a given colour for a fixed time period before reverting back to the normal colour?

e.g. for a numeric field, it would be great to be able to highlight a cell in green if the new value is higher than the old value and in red for the opposite case.  Then after a short period of time allow the highlighting to disappear.

**Comment by jiteshvassa** [comment]
This has been answered here:

http://stackoverflow.com/questions/31659276/can-you-highlight-a-handsontable-table-cell-whose-value-has-been-changed-for-a-f

However, it would be great if some support was added to Handsontable to allow this sort of thing to work out of the box with some configuration.

**Comment by AMBudnik** [comment]
Thanks for an idea. I will mark it as a feature request.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.
