### ISSUE TITLE
Double clicking column resizer no longer auto resizes

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#2690]
There seems to be a regression between 0.14.1 and 0.16.1 (versions I had worked with).  In 0.16.1, I'm seeing that when you double click on a column resize handle, it doesn't auto resize the column to fit all cells in the column.  Instead, it is resizing down to just about 20px.

You can even see this incorrect behavior, here: http://docs.handsontable.com/0.16.1/demo-resizing.html

**Comment by krzysztofspilka** [comment]
Fixed in #2683 to be released in version 0.18.0
