### ISSUE TITLE
Sorting Date column

### ISSUE THREAD

**Issue by selvakumar79** [handsontable/handsontable#2691]
Hi sorting date column with empty values not working properly in handson table.
For date column having values without empty, its working fine.

**Comment by AMBudnik** [comment]
I made a [simple example](https://jsfiddle.net/f9orn629/) for this situation. By saying 'not working properly' you mean that the empty value is never first?

**Comment by selvakumar79** [comment]
Yes. The empty value is coming in first cell as well as in between the cells in the rows also.
So the sorting is not proper.

**Comment by AMBudnik** [comment]
OK, this is a [date example](https://jsfiddle.net/wujqjujd/). You're right sorting is not working as it should. Thank you for reporting @selvakumar79

**Comment by selvakumar79** [comment]
Hi .. is there any update on date sorting?

**Comment by krzysztofspilka** [comment]
@selvakumar79 we confirmed that is a bug and it's designed to be fixed, not sure when exactly.

**Comment by selvakumar79** [comment]
Thanks for your reply.Just let me know once its fixed...
