### ISSUE TITLE
Comments mouseover processing fails if cell content contains children elements

### ISSUE THREAD

**Issue by rjansen72** [handsontable/handsontable#2692]
In our implementation of handsontable we added a custom editor for rich text cell content. For the most part everything is working very well. One issue we have is with comments. The mouseover event assumes the content of the TD cell doesn't contain child elements. However, for rich text the content of the cell is more html. When the mouse passes over these types of cells the comment for the cell appears and disappears quickly. Working on a fix now was curious if others have seen this?

**Comment by AMBudnik** [comment]
Could you please prepare a demo for this issue?

**Comment by rjansen72** [comment]
you bet: http://jsfiddle.net/enszpxvw/

I have already fixed this in our fork FWIW.

**Comment by krzysztofspilka** [comment]
@rjansen72 I guess we haven't spotted that before. Comments and the context menu aren't the child elements of the particular cell. However, in your demo comments behaves badly and we definitely need to give it a closer look (not sure when though:( ) Thanks for reporting!

**Comment by AMBudnik** [comment]
In the 0.28.3 there's also a jumpy behavior: http://jsfiddle.net/qskskxoy/

**Comment by AMBudnik** [comment]
Hi @rjansen72 
2692 finally fixed! Thanks for sharing :)
