### ISSUE TITLE
Handsontable over HTTPS

### ISSUE THREAD

**Issue by MJHath** [handsontable/handsontable#2693]
I am trying to run Handsontable over a HTTPS connection

The usual method of doing this, is to call the file without the "http:" part of the address
So, the call to the HoT script ("http://handsontable.com/dist/handsontable.full.js") would become "//handsontable.com/dist/handsontable.full.js" (simply meaning that the call will use the same transport method as the page itself)
So, if the page is loaded over http, then so will the script src.
If the page is loaded over https, then the script will also be loaded over https

However, when I try and run it this way (or by explicitly setting it to use https) I am presented with a warning saying and the only way of getting it to load, is to have mixed security (i.e. http and https) on the same page - which is classed as a security risk by most browsers, hence the warning

Could you have a look at get Handsontable working correctly over https?

It looks like it may be a hardcoded (tut!) call to http://handsontable.com/bower_components/handsontable/dist/handsontable.full.js and http://handsontable.com/bower_components/handsontable/dist/handsontable.full.css that are causing the problems.

Many thanks

**Comment by MJHath** [comment]
Update:
Have been doing a bit of testing and it looks like, if I call the Handsontable .js and .css using the following, it does seem to Work

```javascript
  <script src="//handsontable.com/bower_components/handsontable/dist/handsontable.full.js"></script> 
  <link rel="stylesheet" media="screen" href="//handsontable.com/bower_components/handsontable/dist/handsontable.full.css">
```

So, it is actually more probable that it is the redirect / rewrite rule, that is being used to redirect /dist/handsontable.full.js to the latest version that is the problem.

Would be good if the standard calls (http://handsontable.com/dist/handsontable.full.js) worked properly though!  :)

Many thanks

**Comment by budnix** [comment]
The best solution for you is using CDN servers like http://cdnjs.com/libraries/handsontable. This servers are better optimised (cache control, gzip etc.) for serving static files and usually supports HTTPS.

**Comment by MJHath** [comment]
Thanks, will take a look into that
As I say, I have managed to get it to work using the statements specified in my earlier update

Out of interest, is there a way of using the cdjns option but to always have the latest version?
It looks like, as part of the URL, you have to specify the version of code
Using http://handsontable.com/dist/handsontable.full.js (I believe) redirects to the latest version

Just asking out of interest, as I realise *always* running the latest version can, sometimes, cause issues (look at MS and their issue with Windows 10 updates and nVidia!!!!)

Many thanks

**Comment by budnix** [comment]
Yes, it’s a little risky using always the latest version. In your project you should decide what version you want to use and nothing can change without you knowledge :) I propose for you to use [bower](http://docs.handsontable.com/0.16.1/tutorial-quick-start.html#page-install) as package manager or include handsontable from CDN proper version. After releasing new version of Handsontable you can update project via bower, update and test on local machine and if everything is ok deploy to production.
