### ISSUE TITLE
Getting column information when moving a column position in the grid

### ISSUE THREAD

**Issue by squaretabledev** [handsontable/handsontable#2694]
Hi 

I am trying to do some extra logic on the grid when a column changes position. 

What I need is to be able to track when a column is moved and what it's new position is.

How is this done in handsontable?

**Comment by AMBudnik** [comment]
Hi @squaretabledev 
Are you still facing any difficulties or need feedback on this subject?
Sorry for a delay.

**Comment by AMBudnik** [comment]
I'm closing this issue @squaretabledev 
but if you'd have any questions to ask - I'm here to help.
