### ISSUE TITLE
Drop down Language validation  

### ISSUE THREAD

**Issue by MahmoudFawzy** [handsontable/handsontable#2695]
I write drop down list when I choose Arabic I show column has error.

![1](https://cloud.githubusercontent.com/assets/6429762/8986817/4bc933b6-36de-11e5-8693-4036381bb6da.png)
![2](https://cloud.githubusercontent.com/assets/6429762/8986818/4bd0f434-36de-11e5-83c2-bbbff9bd4a3c.png)

**Comment by AMBudnik** [comment]
Could you please create a demo for your code? I made [one example](https://jsfiddle.net/mcg78zj9/) with a dropdown and it works as expected. Dropdown list in our example has `string` values and they suit every letter. 

When it comes to writting from right to left we already have an issue at https://github.com/handsontable/handsontable/issues/83

**Comment by AMBudnik** [comment]
Closed in lack of demo for a month. Please add one if you still face the same issue.
