### ISSUE TITLE
problem with formula

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#2696]
hello,
i have an issue when i use a simple sum of 2 cells,
if one cell  has no value, i have the error  #VALUE!
in the
http://handsontable.com/examples.html#fndtn-personal
i put in C9 the formula
=B8+B9

i have the error  #VALUE!, it seems to be related to the fact that B9 has no value.

regards
jm

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 this [formula examples](https://handsontable.github.io/ruleJS/) may help and remember to type `formulas: true` into your instance's settings.

**Comment by jeanmarc78** [comment]
hello,
i create a testcase 
1) open http://handsontable.com/examples.html#fndtn-personal
2) put in C9 the formula =B8+B9

error
===> #VALUE!

regards
jean marc

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 please try [RuleJS demo](https://handsontable.github.io/ruleJS/) if you type directly a sum formula it works fine. 
We are planning to add better formula support on Handsontable (you can [vote](http://feathub.com/handsontable/handsontable) for this feature).

**Comment by jeanmarc78** [comment]
sorry AMBudnik,
but i don't speak about SUM function but simple addition ,
i regive you a testcase based on RuleJS demo


![picture1](https://cloud.githubusercontent.com/assets/11042160/10427750/7b4c7ac4-70ec-11e5-80c9-8fbe4f0e6935.png)
![picture2](https://cloud.githubusercontent.com/assets/11042160/10427751/7b4d170e-70ec-11e5-87cb-5f8967cae303.png)
![picture3](https://cloud.githubusercontent.com/assets/11042160/10427753/7b4ddf72-70ec-11e5-9bb1-f828e298c0f0.png)
![picture4](https://cloud.githubusercontent.com/assets/11042160/10427752/7b4d9242-70ec-11e5-81a9-614f0ea2668d.png)

**Comment by AMBudnik** [comment]
I shouldn't add the example above cause it's not functioning in 100% percent. [Here's](http://jsfiddle.net/663sr199/2/) a simple example using `/ruleJS.all.full.js` in a small project.

It has all the available options: `=SUM(cell1:cell2)`, `=cell1+cell2` and `numeric'`, `text` and `formula` data sources.

The issue with the first example can be in reference, where there are few formulas corresponding to each other.

**Comment by jeanmarc78** [comment]
Empty B1 --> issue
![picture5](https://cloud.githubusercontent.com/assets/11042160/10429220/68beb236-70f7-11e5-8f05-41ab54d0714f.png)

**Comment by AMBudnik** [comment]
Yes, actually it has to be `null` rather than an empty string. Thanks for noticing. I'll add it to our To-Do

**Comment by jeanmarc78** [comment]
it concerns also basic arithmetics
subtraction -
multiplication *
division /

regards
jm

**Comment by AMBudnik** [comment]
OK, thank you very much for feedback.

**Comment by anarabanana** [comment]
Hello @AMBudnik .
I am wondering if you know the wayhow to traverse this issue?
![screenshot from 2016-02-27 16 58 17](https://cloud.githubusercontent.com/assets/12660427/13374115/5b69932e-dd73-11e5-92cf-955967241224.png)
![screenshot from 2016-02-27 16 59 02](https://cloud.githubusercontent.com/assets/12660427/13374119/6dbc436e-dd73-11e5-804b-70343a4e6ba9.png)

**Comment by AMBudnik** [comment]
Hi @anarabanana are you thinking about values of cells `C5` and `D5` or is there anything else I should look at?

**Comment by anarabanana** [comment]
@AMBudnik , as it was mentioned earlier in forum to get formula result we need to use var servers_total  = hot.plugin.matrix.getItem(hot.plugin.utils.translateCellCoords({row : 62,col : 2})).value 
But when the value on that cell is changed (so the formula result is changed), var servers_total still holds an old value. Is there a way to traverse it?
Thank you for your help.

**Comment by AMBudnik** [comment]
Hi @anarabanana currently not. Formula features is in its beta mode and we are aware that some functions can be buggy.

**Comment by anarabanana** [comment]
For those who faced the problem with formatting calculated formula result precision with type:'"numeric" , format:"0.0", it is possible just to use like "=CEILING(SUM(C63:C68),1)" and value will be rounded.

**Comment by AMBudnik** [comment]
Hi @anarabanana have you tried the same code using PRO formula plugin (src: https://docs.handsontable.com/pro/1.10.2/demo-formula-support.html)?
