### ISSUE TITLE
Column Dragging/Reordering: Headers Move with Columns

### ISSUE THREAD

**Issue by AggieCridmus** [handsontable/handsontable#2697]
First, thanks for creating and maintaining this library. Would it be possible to include an options flag that will allow column headers to reorder with the column when using the 'manualColumnMove' feature with custom column headers? Right now, I have to put my "real" column headers on row zero so that the headers can move with the column when manually dragging the column to another position. Because of this, I am unable to use some functions such as a 'getColHeader'. Thanks!

**Comment by AMBudnik** [comment]
Hi @AggieCridmus I'm not sure but maybe this [example](https://jsfiddle.net/fkLvek7t/) is the one you're looking for - if not, please give an example.

**Comment by AggieCridmus** [comment]
Wow I will admit fault on this one. I did not know that behavior existed. I initially formed my conclusions from playing with the example [here](http://docs.handsontable.com/0.16.1/demo-moving-rows-and-columns.html). I think it may be worth mentioning in the documentation that if custom headers are used then the headers will move with the column. The example given is using the default A,B,... headers where they stay fixed but the column data moves. 

Anyways, thanks for replying. I'm loving the library and the support your team provides.
