### ISSUE TITLE
row header doubles when scrolling

### ISSUE THREAD

**Issue by andradobritoiu** [handsontable/handsontable#2702]
When I scroll to the right and focus on a cell or edit it, then scroll back to the left the row headers seem to double like this: http://i.imgur.com/PIr4Ufn.gif

I'm using handsontable 12.0. Any solutions for this problem?

**Comment by rjansen72** [comment]
scrolling is something the handsontable team has been making improvements in. I strongly recommend upgrading to the latest (0.16.1 or higher).

**Comment by krzysztofspilka** [comment]
@andradobritoiu please update to the latest version and check again. Also, I've spotted some CSS problems in your animation. If you stumble across the same problem after the upgrade, please check if that's not your CSS that messes up there.

**Comment by andradobritoiu** [comment]
Thank you for pointing me in the right direction. The problem was actually with my CSS.

**Comment by AMBudnik** [comment]
If you would have any other questions, please create a new issue I assume this one can be closed.
