### ISSUE TITLE
The verticall scroll speed in Iceweasel 39.0 on Linux (i.e. Firefox) is very slow

### ISSUE THREAD

**Issue by basvandenberg** [handsontable/handsontable#2703]
In Iceweasel 39.0 (on Linux) a single scroll with my mouse wheel moves a table down only one or two rows. For example in the table on: 

http://docs.handsontable.com/0.16.1/demo-scrollbars.html

While in Chrome 44.0 (also on Linux) about ten rows are traversed with a single scroll of the mouse wheel (which 'feels' much more 'natural').

I also noticed that if you scroll up and you approach the top of the table, than the scroll speed seems to slow down exponentially. It takes quit some effort to reach the top of the table with the scroll wheel.

**Comment by krzysztofspilka** [comment]
Connected with #2520

**Comment by AMBudnik** [comment]
Hi @basvandenberg we made some changes in related https://github.com/handsontable/handsontable/issues/2520 issue. Could you check it there's a progress?

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply.
