### ISSUE TITLE
document.activeElement causing error

### ISSUE THREAD

**Issue by dakal-oleksandr** [handsontable/handsontable#2705]
Under IE exist cases when document.activeElement is null that cause error in mouseup handler.
``` javascript
this.eventManager.addEventListener(document.documentElement, 'mouseup', function(event) {
    if (instance.selection.isInProgress() && event.which === 1) {
      instance.selection.finish();
    }
    isMouseDown = false;
    if (helper.isOutsideInput(document.activeElement)) {
      instance.unlisten();
    }
  });
```
isInput function that used in helper.isOutsideInput don't check if element exist and refer to element property that cause error.
```javascript
function isInput(element) {
  var inputs = ['INPUT', 'SELECT', 'TEXTAREA'];
  return inputs.indexOf(element.nodeName) > -1 || element.contentEditable === 'true';
}
```

**Comment by Scuzzle** [comment]
same here

**Comment by jansiegel** [comment]
@dakal-oleksandr I'm having trouble reproducing this issue, but based on your description i think https://github.com/handsontable/handsontable/commit/834bda7c5d37ba23afc665b59ad579655e36b9f9 should fix it.
