### ISSUE TITLE
White space in handsontable while moving horizontal scroll in IE when Fixed columns are used

### ISSUE THREAD

**Issue by aurelialeo** [handsontable/handsontable#2706]
Hi,
I have used fixed columns in my application and have issues with horizontal scroll in IE11. 

Issue #1: When moving the horizontal scroll right and left , a big white space is seen in between the last fixed column and the adjacent column. The issue is very clear in the below demo link. Please use IE11 to open the link as I work with it.

http://docs.handsontable.com/0.16.0/demo-fixed-rows-and-columns.html

Issue #2: In my application, all the modules open in tabs using jquery display : block/none. After loading data, I scrolled towards right end and took another module which opened as a second tab. When i click the first tab containing handsontable, the scroll suddenly shifts to the left end and white space is seen.

![image](https://cloud.githubusercontent.com/assets/12795736/9060030/6c327732-3acd-11e5-8c96-4b738606e6fd.png)

Could you please provide a solution?

**Comment by aurelialeo** [comment]
Could you please provide an update?

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/1389#issuecomment-149911903 
Do you still face the same issue @aurelialeo ?

**Comment by AMBudnik** [comment]
I hope that at this point, if anybody really had any objections or major concerns with this issue they would have spoken by now. I'm closing this closing topic.
