### ISSUE TITLE
How to change cell color in after change.

### ISSUE THREAD

**Issue by kvnandini** [handsontable/handsontable#2708]
@AMBudnik, I have to change the color of certain cell based on data pasted only if the cell is null, basically my cell are nothing but fields on CRM, so i need to make some of them mandatory.

 afterChange: function (changes, source, isValid) { 
			     
				 if (cleanCalled) {
					// detected clear call so we skip it
					cleanCalled = false;
					return;
				  }else{
					  var changesJson = JSON.stringify(changes);
					  if ((source == "edit" || source == "paste") ) { 
						for(var i=0; i< changes.length ; i++) {
							for(var j = 0; j < globalchanges.length; j++){
                                                           console.log(changes[i][0].toString()+changes[i][1].toString());
                    if(changes[i][0].toString()+changes[i][1].toString() === "44" && changes[i][3].toString() === ''){
                       console.log('RED--- @AMBudnik --- I NEED TO CHANGE HERE.. HOW CAN I DO THIS');
                       console.log('did it');
                    } 
							   if(changes[i][0].toString()+','+changes[i][1].toString() === globalchanges[j][0].toString()+','+globalchanges[j][1].toString()){
									globalchanges.splice(j,1);                            
								} 
													 
							 }
							 globalchanges.push([changes[i][0],changes[i][1],changes[i][2],changes[i][3]]);
						 }
						 console.log('Changes'+JSON.stringify(changes)); 
						 console.log('GlobalChanges'+JSON.stringify(globalchanges));
					   }  
				   } 
			 },
			 afterValidate: function (isValid, value, row, prop, source) {
				 if (source == "paste") {                
					 if (!isValid){
					   alert(isValid);
					   if(errorflag == "false") { 
						 alert('{!$Label.IPM_FinancialGrid_MSG3}');
						 errorflag = "true"; 
						 document.getElementById("btn13").click();             
						}                                             
					 }

				 }else if (source == "edit" ) {
					 if (!isValid){
						 alert('{!$Label.IPM_FinancialGrid_MSG3}'); 
						 document.getElementById("btn13").click();                                                            
					 }

				 }
			 }

**Comment by AMBudnik** [comment]
Hi @kvnandini sorry for a delay.
Are you still facing any difficulties related to this issue?

**Comment by AMBudnik** [comment]
Closed in lack of author's reply.

If you're still facing any difficulties @kvnandini please leave a comment.
