### ISSUE TITLE
Not selecting column by clicking its header

### ISSUE THREAD

**Issue by khazhoyan** [handsontable/handsontable#2709]
I have some button stuff in column headers and clicking these guys should not select columns.
Looks like there's no suitable option or method. Unbinding some events seems to be not very elegant solution (and maybe not working one). So I'm kinda stuck here.

**Comment by AMBudnik** [comment]
Hi @khazhoyan Thank you for this suggestion.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by mhkeller** [comment]
What's the process for upvoting this? I see this issue is six years old and is listed as "approved." This behavior is a blocker for me since I would like to sort columns without selecting all rows... Is there a workaround?

**Comment by AMBudnik** [comment]
Hi @mhkeller 

If you do not connect any logic to selection I can recommend using the `deselectCell()` method in the `afterColumnSort()` hook. Here is the outcome https://jsfiddle.net/yoqcf462/3/

![sorting](https://user-images.githubusercontent.com/10757813/160831525-f51d549a-e2e6-4d62-952c-9dda01062623.gif)

**Comment by mhkeller** [comment]
Thanks for the workaround idea @AMBudnik. I'd lose any existing selection in that case, though. Would it be possible to add an option to disable column selection and within [`selectColumns`](https://github.com/handsontable/handsontable/blob/22121087cb57d99f08e3105d20a0fb4de953877a/handsontable/src/selection/selection.js#L622) do something like:

```js
if (disableColumnSelection === true) return;
```

**Comment by mhkeller** [comment]
Or another way may be to not call it from the mouse handler [here](https://github.com/handsontable/handsontable/blob/22121087cb57d99f08e3105d20a0fb4de953877a/handsontable/src/selection/mouseEventHandler.js#L40) and [here](https://github.com/handsontable/handsontable/blob/22121087cb57d99f08e3105d20a0fb4de953877a/handsontable/src/selection/mouseEventHandler.js#L50).

**Comment by AMBudnik** [comment]
>Thanks for the workaround idea @AMBudnik. I'd lose any existing selection in that case, though.

so that means that in your use case you select a column, sort, and still want to have a cell selected? (even if it was in a different column)? If (again) you do not base your logic on that selected cell, you can read the coordinates of that cell in `beforeColumnSort` via `getSelected()` method. And the reattach the selection via `selectCell()` in the `afterColumnSort` hook. At the moment, it seems to be the only way (besides changing the source code).
