### ISSUE TITLE
Double header when press Home and Page Up keyboard

### ISSUE THREAD

**Issue by ariefsam** [handsontable/handsontable#2710]
This is my Javascript

http://jsfiddle.net/ariefsam/u4b2qL2t/

Click on result panel, then scroll down. Then press pageup keyboard, this is my screen:

![Image of screen]
(http://ariefsam.github.io/images/strange.png)

**Comment by krzysztofspilka** [comment]
@ariefsam I've just reproduced it and marked as to be fixed within the next milestone. Thanks for letting us know.

**Comment by ariefsam** [comment]
You are welcome. Thank You

**Comment by budnix** [comment]
Related with https://github.com/handsontable/handsontable/issues/2089
