### ISSUE TITLE
Mousewheel scrolling

### ISSUE THREAD

**Issue by klikstermkd** [handsontable/handsontable#2713]
For some reason, when you scroll with the mousewheel up/down in the table, the container moves very slow. Scrolling with the scrollbars is fine no problem there. As far as I tested, this is only an issue in Chrome and Firefox, other browsers are fine. 

I am using version 0.16.1

**Comment by krzysztofspilka** [comment]
@klikstermkd What OS are you using? Could you provide us with a screencast?

**Comment by klikstermkd** [comment]
Tested on Windows 7. I just tested it on Windows 10 on Chrome and it's fine, works fine on Edge as well. So it probably has something to do with the OS I guess.

**Comment by krzysztofspilka** [comment]
It shouldn't have. Can you confirm that on some other machine?

**Comment by klikstermkd** [comment]
Yes, I tested on my friend's machine which has Windows 7 as well, same issue. Also, on Windows 8 works fine.

**Comment by krzysztofspilka** [comment]
Alright, will check that out.

**Comment by klikstermkd** [comment]
Hi,

I just found out that if I set "rowHeaders" to false in the options, the scrolling is ok on all browsers and OS's.

**Comment by klikstermkd** [comment]
The issue is still present on Windows 10 on Chrome and Firefox.

**Comment by AMBudnik** [comment]
related https://github.com/handsontable/handsontable/issues/2520

**Comment by kquinn45** [comment]
This just started happening again with the newest Chrome update on 3/16/2016.

**Comment by klikstermkd** [comment]
@kquinn45 They enabled smooth scrolling by default in Chrome, that's why it started happening again.

**Comment by kquinn45** [comment]
Anyway to fix it or should I just wait for an update to the Handsontable?

**Comment by lizavolkova** [comment]
Any updates on this issue?

**Comment by AMBudnik** [comment]
Hi @lizavolkova unfortunately that's a bigger case and with a current schedule I do not see any changes related to scrolling performance in 2016.

**Comment by AMBudnik** [comment]
Please continue the conversation at https://github.com/handsontable/handsontable/issues/3486
