### ISSUE TITLE
Sorting on hidden data

### ISSUE THREAD

**Issue by jiteshvassa** [handsontable/handsontable#2714]
Is it possible to have data in a table sorted by a field that is not displayed?  I have a grid of data which I would like to display that contains a column called "sort order", but I don't want to display this.  The sorting needs to be done client side because events are coming in over web sockets and need to be reflected in the table.

I see a related issue here: https://github.com/handsontable/handsontable/issues/146

Ideally when defining the columns, it would be great if you could have a 'hidden: true' attribute to hide a column.  Since I think you need to have the hidden data defined as a column to be able to use the columnSorting against it.

**Comment by zekedroid** [comment]
From SO:

If you're not showing the column then I assume you're not expecting the user to be able to manually sort by this hidden column. Therefore, why don't you simply sort your data array with native JS? At any point during execution you could have a function which sorts by this hidden column and then just don't render this in your Handson definition.

So yes, the answer is it is possible. The not showing of a column is as simple as defining the columns option and not including a column for this hidden value.

see http://stackoverflow.com/questions/31875116/sorting-on-hidden-data for full post

**Comment by jiteshvassa** [comment]
For my use case, sorting the underlying data has some additional complexity around it.  I'm having to keep a mapping of 'primary key' to index of the row in the original data array so that I can update those items when notifications from a server are received.  Therefore sorting the underlying data array would also require rebuilding the mapping after the sort.

Ideally given that Handsontable can provide an abstraction layer for sorting above the underlying data, it would be great if sorting could do done on a non displayed column.
