### ISSUE TITLE
WTF is a Walkontable?

### ISSUE THREAD

**Issue by avilaton** [handsontable/handsontable#2716]
It is the return value of many methods but not mentioned in the docs!

Great library you are cooking.

**Comment by AMBudnik** [comment]
Hi @avilaton Walkontable is for internal use only. It used to be a separate library, but now it is included to HOT repository and it's core functionality is to render HTML table.

**Comment by avilaton** [comment]
Hi @AMBudnik, thanks for your quick response.

I'm trying to do things with the selection, like adding a class to the selected range, and found useful to use the Walkontable to iterate over selected cells. I'm trying to let a user mark certain ranges as selected, and I do this by attaching metadata to the selected cells. 

I think that is Walkontable is the return value of so many methods in the API, then it might need to be documented in the site or somewhere. I went and read the SPECS.

**Comment by krzysztofspilka** [comment]
@AMBudnik shouldn't you be taking rest on your vacation now?:)
