### ISSUE TITLE
afterChange event not fired when removing Row

### ISSUE THREAD

**Issue by hippich** [handsontable/handsontable#2717]
Not sure if this is correct behavior. I am using 0.16.1 version and when I remove row (using context menu) - afterChange event is not fired. From reading Wiki it sounds like afterChange really should be called afterCellChange, since it react right now only on cell changes.

**Comment by basvandenberg** [comment]
After removing a row the [afterRemoveRow](http://docs.handsontable.com/0.16.1/Hooks.html#event:afterRemoveRow) is fired.

You have similar events that are fired before/after creating/removing rows/columns.

**Comment by krzysztofspilka** [comment]
@basvandenberg thanks for help
