### ISSUE TITLE
translateRowIndex function does not work

### ISSUE THREAD

**Issue by jiteshvassa** [handsontable/handsontable#2718]
The documentation mentions the translateRowIndex function: http://docs.handsontable.com/0.16.1/Core.html#translateRowIndex

However this doesn't appear to be exposed in the actual API (which is currently at v0.16.1)

**Comment by jiteshvassa** [comment]
Just found that you can use table.sortIndex[visibleRowIndex][0] to obtain the physical index. See: https://github.com/handsontable/handsontable/wiki/Understanding-column-sorting-plugin

**Comment by jiteshvassa** [comment]
It would be good to get the docs updated to reflect that translateRowIndex isn't publicly visible and that sortIndex can be used.  Although it be better to expose this using a function rather than exposing internal handson state via sortIndex.

**Comment by toresenneseth** [comment]
Adding to this, looking at the source code, it seems you can also execute 
```
var row = Handsontable.hooks.run(hotInstance, 'modifyRow', rowIndex);
```
to achieve the same result.

**Comment by thbar** [comment]
@toresenneseth this is super useful, thanks (especially since when no sorting is applied, apparently `sortIndex` can be empty).

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
The following topic is no longer a representation of Handsontable API for tracking indexes please check 

* https://handsontable.com/docs/Core.html#columnIndexMapper
* https://handsontable.com/docs/Core.html#rowIndexMapper
