### ISSUE TITLE
Updating `stretchH` setting does not work

### ISSUE THREAD

**Issue by jlsalmon** [handsontable/handsontable#2719]
I am trying to enable a setting to dynamically expand or collapse the table to either fill the screen or collapse to minimum width with a button.

However, when I try `hot.updateSettings({ stretchH: 'none' })` it doesn't work. See [this fiddle](http://jsfiddle.net/kcsonafz/1/) for a demo.

**Comment by AMBudnik** [comment]
Confirmed. Thanks for reporting @jlsalmon
