### ISSUE TITLE
Scroll bar styling

### ISSUE THREAD

**Issue by tddrmllr** [handsontable/handsontable#272]
It would sweet if there were some kind of scroll bar styling built into the plugin.  I know there are plugins out there, but at first glance it seems like it will be a pain to try and integrate them given all the custom scrolling functionality already being used.

**Comment by chrilehner90** [comment]
@warpech I cannot figure out how to style scroll bars with your link. are there already docs about how to style the table's scrollbars?

**Comment by MMTLukas** [comment]
+1

**Comment by kotmatpockuh** [comment]
@warpech how to style it?

**Comment by AMBudnik** [comment]
Hi @kotmatpockuh here's more in the docs: https://docs.handsontable.com/0.24.1/Options.html#viewportColumnRenderingOffset this styling relates to the amount of columns/rows to be rendered outside of the visible part of the table.

**Comment by kotmatpockuh** [comment]
@AMBudnik but it doesn't rely to custom scrollbar. I mean to implement custom scrollbar like this: http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/complete_examples.html

**Comment by AMBudnik** [comment]
@kotmatpockuh Unfortunately we do not support custom scrollbar styling but I guess it won't be hard to implent it via other libraries as Handsontable uses browser settings in this case.

**Comment by Dams591** [comment]
Hey guys, 
I'm also wondering how can I change the scrollbar to be http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/complete_examples.html

Is there anyone here that made it work ? 
Also is there a way to change the scrollbar position in handsontable ? I'd like the vertical scrollbar to start after the header is that position ?

**Comment by AMBudnik** [comment]
Hi @Dams591 
do you mean something like this http://jsfiddle.net/handsoncode/qwwt6qyb/ ?

**Comment by Dams591** [comment]
Hi @AMBudnik 
Yeah some kind of custom styled scrollbars to fit with the rest of our application.
We use mcustomscrollbar all over the place and I'd love to have it with handson too

I don't think that a CSS crossbrowser solution works when it comes to style scrollbars which why we use a custom js plugin.

My attempt to make it work with handson looks good but breaks the table functionnalities :(

http://jsfiddle.net/handsoncode/qwwt6qyb/

**Comment by Dams591** [comment]
@AMBudnik 
It seems someone had an issue with nicescroll (https://github.com/handsontable/handsontable/issues/2123)
I don't mind changing scrollbar plugin if you know how to integrate this one with handson.

Thanks

**Comment by AMBudnik** [comment]
I can imagine that it can look little odd when all the scrolls are in the same design besides Hot. I have to say that we have never tested it more than just using some basic CSS settings but it would definitely be something great to have.
