### ISSUE TITLE
using getDataAtCell in last table row in afterRemoveRow returns undefined

### ISSUE THREAD

**Issue by dbishai** [handsontable/handsontable#2720]
http://jsfiddle.net/YpaR7/6/

Using the context menu to remove the last row of a table will cause getDataAtCell to return undefined in the afterRemoveRow callback. This only happens in the last row of the table.

**Comment by budnix** [comment]
Hi, I think that for this proposes you should use beforeRemoveRow hook. Like in this [updated demo](http://jsfiddle.net/YpaR7/8/).
