### ISSUE TITLE
Rendering does not work properly when using shift + scroll to scroll horizontally

### ISSUE THREAD

**Issue by nip3o** [handsontable/handsontable#2723]
![scroll 1](https://cloud.githubusercontent.com/assets/1380307/9192121/3d2f2b52-4008-11e5-9441-4c612ac9ca0b.gif)

Horizontal scrolling using the scrollbars works fine, so does dragging, but when using shift + scroll columns are not rendered properly and whitespace appears. Vetical scroll works fine.

Tested at the demo page (http://docs.handsontable.com/0.16.1/demo-scrollbars.html) in Firefox, Chrome and Safari on OS X on multiple computers.

**Comment by krzysztofspilka** [comment]
@nip3o why would you keep shift down during the scroll?

**Comment by nip3o** [comment]
@krzysztofspilka on Mac OS you can always scroll horizontally in a window by pressing shift while scrolling. So if you just use the scroll wheel, windows scrolls vertically. If you press shift and scroll, windows scrolls horizontally.

**Comment by ciuncan** [comment]
@krzysztofspilka just as rolling mouse wheel scrolls vertically, rolling with shift down scrolls horizontally. I can confirm this issue, too, on Ubuntu (15.04) with Chrome (46.0.2471.2 dev). I guess that shortcut bound to browsing history navigation (back and forward) on Firefox (40.0).

**Comment by budnix** [comment]
Fixed in 0.18.0
