### ISSUE TITLE
Editor size wrong when using a flexbox container.

### ISSUE THREAD

**Issue by ciuncan** [handsontable/handsontable#2724]
Hi,

I saw a relevant issue but it was closed. 
https://github.com/handsontable/handsontable/issues/1815

I am using ngHandsontable with angular-material and it uses css flexbox extensively. When I remove angular-material.css, editor size looks just fine, same size as the cell. With trial-and-error, I found out that using a container with flexbox (probably with some other cases, too) causes this issue. The `<span.autoResize>` put to measure text size of edited value in "autoResize.js" covers whole body instead of wrapping the text content. But I managed to get it measure correctly by changing `span.style.display` to `'inline-table'` from `'inline-block'` at the end of `extendDefaults` function, again with trial-and-error.

Could this be a permanent fix, if I am not missing a point? Just wanted to report this.

**Comment by AMBudnik** [comment]
I wasn't able to reproduce it.
Could you share a demo @ciuncan if this issue is still replicable with the latest version?

**Comment by ciuncan** [comment]
@AMBudnik Hi sorry for late response. I haven't been looking into handsontable for a while. But now with the latests version (0.24.1) it no longer seems to be an issue. I don't use above mentioned workaround. Please feel free to close this issue as far as I am concerned.

**Comment by AMBudnik** [comment]
Thanks for your reply @ciuncan

**Comment by Sjark** [comment]
Adding this to the css fixed it for us:

```css
body > span { position:absolute; }
```
