### ISSUE TITLE
Mobile scroll - not refreshing

### ISSUE THREAD

**Issue by snuuve** [handsontable/handsontable#2726]
When i scroll in mobile device - new rows (rows which are hidden) are not showed. I need to unfocus table ( touch other DOM) to refresh and show new scrolled rows.

Refresh stuck : 
<a href="http://pl.tinypic.com?ref=51ud5f" target="_blank"><img src="http://i59.tinypic.com/2nlsguw.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

After unfocus: 
<a href="http://pl.tinypic.com?ref=51ud5f" target="_blank"><img src="http://i58.tinypic.com/51ud5f.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Tested on Chrome Dev / iPhone / Samsung Galaxy S2+   with   Chrome/Safari on both.

EDIT: 

I added this : 
afterMomentumScroll: function(){
              this.render();
}

It looks like a solution.

**Comment by yurevich1** [comment]
@snuuve , thanks. It really works, but hardy diffiicult to find. It is very importaint to add it into manuals.

**Comment by AMBudnik** [comment]
same topic as https://github.com/handsontable/handsontable/issues/3, please track changes to https://github.com/handsontable/handsontable/issues/3
