### ISSUE TITLE
updateSettings - fixed rows and columns

### ISSUE THREAD

**Issue by ricardo84** [handsontable/handsontable#2728]
Table get's messed up some kind of fragment on top or something.
If i have time will try to see wath is wrong. If possible check please.
P.S: If it doesn't get messed up just change the update to a diferent amount of fixed columns and rows and it will get messed up when you run again.
http://jsfiddle.net/713L7b9g/

**Comment by AMBudnik** [comment]
Thank you @ricardo84 I got this:

![zrzut ekranu 2015-08-14 o 11 39 48](https://cloud.githubusercontent.com/assets/10757813/9271336/58c3e6fa-4279-11e5-8f66-d535fc2a9ef6.png)

and countless issues at the console

![zrzut ekranu 2015-08-14 o 11 41 36](https://cloud.githubusercontent.com/assets/10757813/9271371/951bffa2-4279-11e5-8352-f8b0da28c2f8.png)
