### ISSUE TITLE
Programmatically merge cells 

### ISSUE THREAD

**Issue by klikstermkd** [handsontable/handsontable#2729]
I am trying to programmatically merge cells with updating the settings with this code:

```javascript
hot.updateSettings({
    mergeCells: [
         {row: 1, col: 1, rowspan: 3, colspan: 3},
    ]
)};
```

but it doesn't work. It works only if I set it in the constructor.

**Comment by AMBudnik** [comment]
Hi @klikstermkd unfortunately mergecells doesn't work with updatesettings, there's an issue for this already https://github.com/handsontable/handsontable/issues/1788. Please track changes to it if you would like to be up to date with this subject.
