### ISSUE TITLE
Context menu and Copy custom value

### ISSUE THREAD

**Issue by hippich** [handsontable/handsontable#2730]
I am trying to customize value copied into clipboard when using 'Copy' from context menu, but not sure where to start. Any pointers?

**Comment by AMBudnik** [comment]
Hi @hippich what you would like to achieve? Maybe customizing this value will be easiest on `beforeChange`

**Comment by hippich** [comment]
it is really simple as that - I want to give user option to Copy from context menu, but also to "generate X" where value of currently selected cell will be used to generate X (in my case it is URL)

**Comment by AMBudnik** [comment]
Hi, if you're still searching for solution, please create a demo. Maybe the case is only to use `getDataAtCell`/`setDataAtCell`
