### ISSUE TITLE
ManualColumnResize fails at checkColumnHeader when handson is within a Polymer element

### ISSUE THREAD

**Issue by lbustelo** [handsontable/handsontable#2732]
https://github.com/handsontable/handsontable/blob/b59808fea3b07a8ae11e46476b53c21316fb697b/src/plugins/manualColumnResize/manualColumnResize.js#L85

It is doing a check up to 'BODY'. The problem is that when using Handson table inside a Polymer 1.0 element, there is no Body tag, rather it is a document fragment. Eventually, the recusion gets to the document fragment node and the following error shows in the console...

`Uncaught TypeError: Cannot read property 'tagName' of null`

Why not check if the search gets to `instance.rootElement`?

BTW... the same problem seems to be in https://github.com/handsontable/handsontable/blob/b59808fea3b07a8ae11e46476b53c21316fb697b/src/plugins/manualColumnMove/manualColumnMove.js#L91

**Comment by peller** [comment]
Pull request is here: https://github.com/handsontable/handsontable/pull/2815

**Comment by peller** [comment]
bump. let me know if there's anything else I can do to help get this merged.

**Comment by peller** [comment]
@AMBudnik @budnix  See the [demonstration](http://jsfiddle.net/seq26zw1/3/) of handsontable in shadow DOM using Polymer.  Please run in Chrome.  Mouseover the main table or the splitters and you will see exceptions when the code tries to traverse the DOM all the way up to `BODY`

**Comment by AMBudnik** [comment]
thanks, got it.

**Comment by budnix** [comment]
PR #2815 merged.
