### ISSUE TITLE
how create multi tab sheet like excel ?

### ISSUE THREAD

**Issue by khanhnam99** [handsontable/handsontable#2733]
i love handsontable , how create multi tab sheet like excel ? i need this, to code php + mysql, pls help me

**Comment by AMBudnik** [comment]
Hi @khanhnam99 maybe this [subject](http://docs.handsontable.com/0.16.1/demo-pagination.html#1) will help.

**Comment by AMBudnik** [comment]
You could use a simple HTML list with a js clicable tabs. [Here's](http://www.htmldog.com/articles/tabs/) a good example how to do this. Then you only insert new HOT instance inside the tab.

**Comment by AMBudnik** [comment]
Issue closed in lack of new questions/propositions.
