### ISSUE TITLE
What's the right way to override the default row height?

### ISSUE THREAD

**Issue by tikitikifoofoo** [handsontable/handsontable#2734]
Is there an option to set the default row height for HOT? I've tried a couple ways to do it, the first is by simply overriding the css for HOT cells like so:
```
table.htCore {
  td, th {
    height: 29px !important;
  }
}
```

However, that results in misaligned rows and row headers when the content of a cell exceeds one line:
<img width="930" alt="screen shot 2015-08-15 at 3 49 41 pm" src="https://cloud.githubusercontent.com/assets/841079/9290999/5012a11c-4365-11e5-8f6d-9c1172f2ab3b.png">

So I then ditched the `!important` and modified the source code (lines 2452 - 2455) like so:
```
rowHeight: function(row) {
  return 30;
},
defaultRowHeight: 30,
```
This seems to work better, but there must be a better way to do this through the API, right? I've looked through the docs, issues, and StackOverflow, but I just can't find a way to do it.

(This if for version 0.16.1)

**Comment by tikitikifoofoo** [comment]
Actually, my solution above doesn't seem to work so well. For some reason the sheet jumps when selecting cells toward the bottom. Don't know what's causing that yet.

**Comment by AMBudnik** [comment]
Hi @tikitikifoofoo you can use `rowHeights` like [here](https://jsfiddle.net/ymu95708/)

**Comment by tikitikifoofoo** [comment]
Awesome. Thanks @AMBudnik.

**Comment by budnix** [comment]
Or you can try to turn on AutoRowSize plugin which can fix row heights issues (`autoRowSize: true`).

**Comment by geins** [comment]
BTW is there an explanation why the option 'rowHeights' is not documented in the list of options on http://docs.handsontable.com/0.20.0/tutorial-quick-start.html
?

**Comment by AMBudnik** [comment]
@geins you're right it should.

**Comment by AMBudnik** [comment]
`rowHeights` added to the docs: https://docs.handsontable.com/0.24.1/Options.html#rowHeights
