### ISSUE TITLE
Internal table $('.ht_master .wtHolder) sets height & width % relative to its container

### ISSUE THREAD

**Issue by DChau10** [handsontable/handsontable#2738]
I've been fighting this one for a while now under Internet Explorer 11. Chrome and Firefox have not had this issue for me. While traditionally, one might decide to set height & width on their table container to a pixel value, I have been using percentage values. As a result, if I say that my container is going to have the following dimensions:

`<div id="table-container" style="width:50%; height:80%; overflow:auto"></div>`

Then the DOM element $('.ht_master .wtHolder) which Handsontable creates inside my table-container also sets its width to 50% of my table-container's width and its height to 80% of my table's height. I would expect that instead, Handsontable would determine the pixel values of these percentage values and set them, otherwise simply use 100% of the width and height of my table container.

Am I misunderstanding something regarding the way that Handsontable utilizes my container?

Additionally, could I get some clarification as to why scrollbars are supposed to use `overflow:auto` instead of `overflow:hidden` as of v0.15.1? There were no comment in the commits for this critical change.

**Comment by AMBudnik** [comment]
This should not be an issue in 0.23.0. Could you check it also?

**Comment by omayhemo** [comment]
I have this problem, today, in PRO v1.5.1
Any solutions?

**Comment by AMBudnik** [comment]
Hi @omayhemo 
Can you share a demo where this issue can be reproducible?
