### ISSUE TITLE
Handsontable 0.16.01 not working on IE 8 and 9

### ISSUE THREAD

**Issue by pushpasaji** [handsontable/handsontable#2739]
I have just downloaded the latest version 0.16.01 from http://handsontable.com/

But none of the example script works on IE 8 and 9. It gives me below javascript error

<snip>
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; Tablet PC 2.0; .NET CLR 1.1.4322; .NET4.0C; .NET4.0E)
Timestamp: Thu, 13 Aug 2015 11:08:51 UTC

Message: Expected identifier, string or number
Line: 125
Char: 269
Code: 0
URI: *****

</snip>

Is this plugin supported in IE. What is the workaround for this issue? 
Please help

**Comment by AMBudnik** [comment]
We do not support IE8 and 9 since 0.12.0 version, but if you would have any questions about newer versions of IE (and not only), please give us a feedback. 

You could also check [Stackoverflow](https://stackoverflow.com/search?q=handsontable) for ideas.
