### ISSUE TITLE
Render limits of multiple HoT on one page

### ISSUE THREAD

**Issue by cyancdesign** [handsontable/handsontable#2740]
Hello,
I'm trying to create a page that has 9 dynamic HoTs.
Each HoT has 35 columns and 10 rows.

Typically each HoT will only render the first 30 columns and not render any cells after that, but it is allotting the space for them to exist.
Though sometimes the cells will render after waiting a minute.
But usually only one HoT of the nine.
Or, if I make the browser ridiculously wide, the columns will display. Or if I manually resize all of the columns to not be very wide.

This is happening on all browers for me.
Am I going beyond memory limits?
Is it just too much for multiple HoTs on one page?

**Comment by AMBudnik** [comment]
Hi @cyancdesign could you create a demo for this issue for better understanding and flexibility of future code ideas?

**Comment by cyancdesign** [comment]
@AMBudnik 
I was able to replicate the issue in jfiddle
https://jsfiddle.net/cyancscoutrfp/d9m6L9yb/

**make sure the browser window is small when you run the page.**

**Comment by AMBudnik** [comment]
Thanks for demo @cyancdesign I think it can be related to https://github.com/handsontable/handsontable/issues/2505. I made a little simplier [example](https://jsfiddle.net/w3w0eqa5/) with only two HOT's and the second HOT has few columns missing.

**Comment by krzysztofspilka** [comment]
It is only partly done, will be released today in 0.17.0.
To be continued in #2766
