### ISSUE TITLE
Add new row to table with hidden data new array to short

### ISSUE THREAD

**Issue by Mattyzero** [handsontable/handsontable#2741]
If I add a new row to the table, the new data array has 6 instead of 7 fields.

hiddenData
[Array[7], Array[7], Array[7], Array[7], Array[7], Array[7], Array[6], Array[6]]

http://docs.handsontable.com/0.16.1/tutorial-data-sources.html#page-array-hidden

1. Open this Link ^
2. Write something in the last row
3. open the console and check the hiddenData variable

**Comment by AMBudnik** [comment]
Thanks for reporting.

**Comment by AMBudnik** [comment]
Works as expected after updating to 0.24.1, demo: http://jsfiddle.net/91r1rx7x/
