### ISSUE TITLE
how create multi tab sheet like excel ? multi tab :  tab 1, tab 2 , tab 3 ,this is my picture

### ISSUE THREAD

**Issue by khanhnam99** [handsontable/handsontable#2742]
![tab](https://cloud.githubusercontent.com/assets/575720/9351900/351242c6-4687-11e5-837c-d4cfce9561ad.PNG)

pls help me! multi tab :  tab 1, tab 2 , tab 3........

**Comment by AMBudnik** [comment]
@khanhnam99 you created the same issue [here](https://github.com/handsontable/handsontable/issues/2733) 5 days ago. We do not duplicate issues. Please track changes to https://github.com/handsontable/handsontable/issues/2733
