### ISSUE TITLE
afterOnCellMouseOver callback is not very useful without a corresponding afterOnCellMouseLeave hook

### ISSUE THREAD

**Issue by KaterynaKateryna** [handsontable/handsontable#2744]
If I need to show something like a tooltip while hovering over a cell it's not enough to have an afterOnCellMouseOver callback. There should be a callback for leaving the cell to hide the tooltip. As a workaround a custom html renderer may be used, but callbacks would look cleaner.

**Comment by AMBudnik** [comment]
I will note adding `afterOnCellMouseLeave` for callbacks as a feature request.

**Comment by KaterynaKateryna** [comment]
Thanks!

**Comment by Scentus** [comment]
Would like to point out that the fact that afterOnCellMouseOver doesn't re-fire if you take your mouse off the cell then move it back onto it without touching another cell (it keeps track of the last cell it was fired on). This alone means that all sorts of workarounds are needed to get any use out of this feature.

**Comment by swistach** [comment]
We've added hooks which contains event, cell coords and reference to DOM Element of the cell:
- `beforeOnCellMouseOut(event, coords, TD)`
- `afterOnCellMouseOut(event, coords, TD)`

----
To-do:
- [x] tests
- [x] documentation

**Comment by AMBudnik** [comment]
@KaterynaKateryna 
thanks again for sharing @swistach have added two additional callbacks. Hope it will be helpful.
