### ISSUE TITLE
how can i represent data horizantalyy and vertically together like matrix

### ISSUE THREAD

**Issue by Mubusher87** [handsontable/handsontable#2745]
![_handsontable](https://cloud.githubusercontent.com/assets/8829789/9384681/20eaa888-4763-11e5-9da6-75bdb36965d2.PNG)
can anybody please guide me how can i display data and how can i save the data as it is

**Comment by AMBudnik** [comment]
I'm not sure if I fully get the idea, but if you would like to have vertically align text maybe [this tut](http://davidwalsh.name/css-vertical-text) will help (it's only CSS). If this is not what you were looking for, please add some examples.

**Comment by Mubusher87** [comment]
@AMBudnik  thanks for your response
its not all about the alignment its about data representation, verticall table data representation in rows take a look the above image we have table in the right side and representation in the left page. i want the same thing

**Comment by AMBudnik** [comment]
I guess you would like to achieve something like a pivot table. If this is what you are looking for it's more like a data source issue than a HOT functionality. I made a [simple example](https://jsfiddle.net/3ed0udqn/) - hope this would help.

**Comment by Dams591** [comment]
@AMBudnik Also looking to achieve a pivot table with HOT, anywhere I could find a working example ? 
Thanks.
