### ISSUE TITLE
Editing cell in IE11 takes 3-5 secs to update its value

### ISSUE THREAD

**Issue by Chnxo** [handsontable/handsontable#2747]
Hi,

I'm trying to edit a table of 180 rows with formulas and a few user rules for editing. The problem is when the user edits a cell in IE11 it takes arround 3-5 secs to update its value. I have followed the "scroll" example (http://docs.handsontable.com/0.16.1/demo-scrollbars.html) which only renders the visible rows but that didn't work. here is the jsfliddle: http://jsfiddle.net/lordchnxo/gtb565wa/ (only the "P/T" columns from August onwards are editable)

Thanks in advance.

**Comment by AMBudnik** [comment]
Hi. You have a loop on `beforeChange` and an `if` `onChange` with the custom renderers it has to take a while to complete editing a cell. That is why even at Chrome it does not work smoothly. When it comes to being slow at IE, [here's](https://github.com/handsontable/handsontable/issues/1772) the issue to follow to for more information.
