### ISSUE TITLE
Autocomplete: Allow mismatch between entered text and matched data (with AJAX source)

### ISSUE THREAD

**Issue by M4urice** [handsontable/handsontable#2749]
Let's say we have columns like this:
````
    columns:[{

        type: 'autocomplete',
        validator: ingredientValidator,
        allowInvalid:true,
        source: function (query, process) {
          $.ajax({
            url: '/search/ingredient/multi',
            dataType: 'json',
            data: {
            'query': query
            },
            success: function (response) {
              process(response.data);
            }
          });
        },
        strict: false
      },
````

My remote source returns a list of ingredients as autocomplete suggestions, but may also include some synonyms for the entered query.  Now the problem is that handsontable "autocomplete shows values that has a string with typed data" (as mentioned here: https://github.com/handsontable/handsontable/issues/2629#issuecomment-120972052).

**Example:**
- The input is "Water"
- Remote source suggest the synonym Aqua as response
- Handsontable doesn't show any suggestion since "Aqua" does not match the input "Water"

How can I ignore the mismatch between query and reponse data?

**Comment by AMBudnik** [comment]
Unfortunately HOT doesn't have this functionality, but you can try to search related topic at [stackoverflow](https://stackoverflow.com/search?q=handsontable).

**Comment by M4urice** [comment]
Thank you. I checked Stackoverflow already. There are quite a few posts about changing the way autocomplete works in HOT. So this could be a possible improvement?

In the end I implemented the desired behaviour with [Select2](https://github.com/select2/select2) and [Handsontable-select2-editor](https://github.com/trebuchetty/Handsontable-select2-editor). 

This can be closed now.

**Comment by AMBudnik** [comment]
We'll keep this in mind for future ideas. I'm closing this issue but if you will have any other suggestions, feel free to leave a feedback.
