### ISSUE TITLE
fixedRowBottom

### ISSUE THREAD

**Issue by TheBlackReverand** [handsontable/handsontable#2750]
Hi,

I need to fixed rows in bottom of table, how can I do it?

Thanks for help & work,

**Comment by AMBudnik** [comment]
Currently it can't be achieved by any of existing functions, but it will be avaiable in PRO version which will be released in few months. You can track it [here](http://handsontable.com/sign-up.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button)

**Comment by TheBlackReverand** [comment]
Ok thanks, wait & see for Pro version (and her cost...)
