### ISSUE TITLE
How to override ManualColumnFreeze plugin?

### ISSUE THREAD

**Issue by macksfield** [handsontable/handsontable#2751]
I'm looking to make some customization to the ManualColumnFreeze plugin without modifying the plugin file itself, so that I can update to newer versions of handsontable and have my custom functionality layered on top. 

It's not clear how that to best accomplish this, or if it's possible.

**Comment by AMBudnik** [comment]
It depends on what you want to achieve. `ManualColumnFreeze` uses `true`/`false` values or a function, but you have to know there's currently an issue with ManualColumnFreeze - you can find it [here](https://github.com/handsontable/handsontable/issues/2760)

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply
