### ISSUE TITLE
Dropdown UI Issue

### ISSUE THREAD

**Issue by jagmeet181** [handsontable/handsontable#2752]
Hi ,

I have implemented the handson tables in one of our major application ,everything seems working fine and ,but the only issue i have with the dropdown user interface ,i have 2-3 Grids on every page with data ,But When there is more items in the dropdown list it does not display all the items and scroll is also not working.
Can you please help me ,its really very urgent we have to launch the application.

![issuedropdown](https://cloud.githubusercontent.com/assets/10523850/9459635/6834e3a0-4b1b-11e5-842d-9fc2a9f889e9.png)

**Comment by jagmeet181** [comment]
Let me know in case if you need any other information.

thanks

**Comment by AMBudnik** [comment]
Hi @jagmeet181 This issue is the same as https://github.com/handsontable/handsontable/issues/1954 please track changes to https://github.com/handsontable/handsontable/issues/1954

**Comment by jagmeet181** [comment]
Hi @AMBudnik  i did the same changes ,but still its causing the issues

**Comment by AMBudnik** [comment]
@jagmeet181 https://github.com/handsontable/handsontable/issues/1954 issue is with a `high` priority for 0.17.1 I guess it won't take a while to solve this issue.

**Comment by jagmeet181** [comment]
@AMBudnik  When it will be released ,as we need this asap ,we have our system live and users are experiencing lot more issues with this.

**Comment by AMBudnik** [comment]
@jagmeet181 I really would like to say it'll be ready with next release but unfortunately it's a bigger project. If this issue stops your user from using your project I can recommend looking at our [support services](http://handsontable.com/support-services.html)
