### ISSUE TITLE
Handsontable context menu repeats

### ISSUE THREAD

**Issue by raduiacobescu** [handsontable/handsontable#2753]
Hello, 
I am currently facing an issue with the HoT regarding the context menu.

I use AJAX requests to update the HoT table, and currently it can be updated with a different period of time, which downloads another set of data, the update flow is as follows:

1. download data
2.update
    hot = document.getElementById('HoT')
    while (hot .hasChildNodes()) {
            hot .removeChild(hot .firstChild);
        }
   var settings = {
            data: data,
            colHeaders: columnHeaders,
            columns: columns,
            contextMenu: true,
            contextMenuCopyPaste: true,
            maxRows: maximumRows
        };
   instance = new Handsontable(hot , settings);

So for each data source update the context menu duplicates itself: http://i.imgur.com/VSijby7.png

Is there any way to clear the context menu from the DOM ? 

The error is Uncaught TypeError: Cannot read property 'destroy' of undefined in handsontable.full.js?ln=js:11612

**Comment by AMBudnik** [comment]
Could you please create a demo for this example, `contextMenu` shouldn't be duplicated while updating source data.

**Comment by raduiacobescu** [comment]
Ok I will try to simulate it.

**Comment by raduiacobescu** [comment]
SOLVED, it was an issue because of HoT.destroy() was no called. So this was not an issue.
Thank you for your help!

**Comment by primeO** [comment]
Can u share the code once iam also facing the issue with ver 3.0

**Comment by NDDC** [comment]
any updates on this please?

**Comment by AMBudnik** [comment]
Sorry, I haven't been scheduled yet

**Comment by primeO** [comment]
Can you please share the code , for me when i try to implement under
dynamic tabs i got this issue !!
