### ISSUE TITLE
countCols function return incorrect value

### ISSUE THREAD

**Issue by AndreyFedotov** [handsontable/handsontable#2754]
I'm using an [example](http://docs.handsontable.com/0.16.1/tutorial-data-sources.html#page-array-hidden) with hidden columns.

From the afterChange method I need to get an ItemId which stored in a last HIDDEN COLUMN:
  hot.getDataAtCell(change[0][0], hot.countCols()-1)

Problem: countCols, countRenderedCols, countVisibleCols return the same value - visible columns count! But a need a real count of columns in a data array (NOT from   setting.columns.length).

**Comment by AMBudnik** [comment]
Ideas:
1. Create a new method for all columns (with hidden)
2. Change `countCols` to count all columns (with hidden)

**Comment by budnix** [comment]
Or you can directly call your source data (untuched by Handsontable) e.q `hot.getSettings().data[row][col]`.
