### ISSUE TITLE
Bug with fixedColumnsLeft set and manulColumnResize enabled

### ISSUE THREAD

**Issue by squaretabledev** [handsontable/handsontable#2757]
Hi

Found strange bug with fixedColunnsLeft and column resize enabled.

If you look at the following jsFiddle http://jsfiddle.net/2jg1xjvr/

1. Load the example.2
2. Try resize columns A, B, C, D, E
- All columns resize correctly.
4. Scroll horizontally, until column I disappears behind E.
5. Now try resize columns A, B, C, D, E
- Resizing does not work. Behavior inconsistent, but it appears to be trying to resize a different column to the one actually modified by the user.

**Comment by AMBudnik** [comment]
This issue is already described in https://github.com/handsontable/handsontable/issues/2683, if you have  new ideas or observation results please write them there.
