### ISSUE TITLE
The tutorial/demo for the beforeKeyDown callback does not behave as advertised

### ISSUE THREAD

**Issue by motin** [handsontable/handsontable#2761]
On http://docs.handsontable.com/0.16.1/tutorial-callbacks.html#page-beforeKeyDown it says "Pressing DELETE or BACKSPACE on a cell deletes the cell and shifts all cells beneath it in the column up resulting in the cursor (which doesn't move) having the value previously beneath it, now in the current cell."

... but instead pressing BACKSPACE on a cell deletes the cell and shifts all cells except the one directly underneath it in the column resulting in the cursor (which doesn't move) having an empty value in the current cell.

Also, it says: "Pressing ENTER in a cell (not changing the value) results in pushing all the cells in the column beneath this cell down one row (including current cell) resulting in a blank cell under the cursor (which hasn't moved)."

... but instead pressing ENTER once simply begins editing mode and ENTER a second time simply stops editing-mode, with no blank cell under the cursor (which has moved down one step).

On Chrome 44, OSX Yosemite.

**Comment by AMBudnik** [comment]
Thank you @motin, I confirm this two situations.

**Comment by AMBudnik** [comment]
First issue no longer occurs but there's still unsolved case with the second <kbd>ENTER</kbd> example

**Comment by AMBudnik** [comment]
I am moving this issue to the Docs board at https://github.com/handsontable/docs/issues/43
