### ISSUE TITLE
handsontable-0.16.1 does not work on IE11

### ISSUE THREAD

**Issue by ericdevg** [handsontable/handsontable#2763]
Works well on Chrome and Microsoft Edge(Win10), however it does not seem to work on IE11, version below, on both win10 and win8.1.
![capture](https://cloud.githubusercontent.com/assets/10081101/9501745/ed359588-4be1-11e5-8dda-316162b3a455.PNG)

**Comment by AMBudnik** [comment]
Hi @EricMSFT I tried http://handsontable.com/ main table and it works fine in IE11 (on virtual machine). Could you please provide more information what you recieve at our main page?

**Comment by EricMSFT** [comment]
Below is the simple test html page I used:

`
<html>
<head>
   <title>Handsontable</title>
    <script src="handsontable-0.16.1/dist/handsontable.full.js"></script>
    <link rel="stylesheet" href="handsontable-0.16.1/dist/handsontable.full.css" />
</head>
<body>
    <div id="example"> </div>
    <script>
        var data = [
            ["", "Kia", "Nissan", "Toyota", "Honda"],
            ["2008", 10, 11, 12, 13],
            ["2009", 20, 11, 14, 13],
            ["2010", 30, 15, 12, 13]
        ];
        var container = document.getElementById("example");
        var hot = new Handsontable(container, {
        data: data
        });
    </script>
</body>
</html>
`

**Comment by AMBudnik** [comment]
Thanks for code, I tried it also with 0.16.1 and newest 0.17.0 (with external links). Could you please tell me if you have some browser extensions or if not, what functionality isn't working (table does not render, edit mode, etc.).

**Comment by EricMSFT** [comment]
Table does not render. I don't actually install any browser extension as I m aware of, all comes default from OS. Did you repro the issue on your end?

**Comment by AMBudnik** [comment]
I tried 0.16.1 and 0.17.0 on virtual win8.1 and Vista (with IE 11) got the same results - working fine. Of Course I got a dialog asking about a permission to run scripts, but after confirming HOT got rendered. I'll have to try it on other devices.
