### ISSUE TITLE
Typescript .d.ts file

### ISSUE THREAD

**Issue by deenairn** [handsontable/handsontable#2765]
This is a feature request rather than a defect.

TypeScript is a very popular language that adds type safety to JavaScript. Currently there is a jquery-handsontable.d.ts file provided for jquery-handsontable by GitHub user intelorca.

https://github.com/borisyankov/DefinitelyTyped/blob/master/jquery-handsontable/jquery-handsontable.d.ts

It would be very useful if a .d.ts could be provided for Handsontable alongside new releases. It is possible to use the above .d.ts file with the current version of Handsontable but it requires the addition of some addition structures. The above file could be used as the basis of the beginnings of a new d.ts file.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.
