### ISSUE TITLE
Limited columns rendering if the viewport is being resized

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2766]
A continuation of the issue reported in #2740 

Head to http://jsfiddle.net/cyancscoutrfp/d9m6L9yb/ and run it in a narrow window. Then resize it to the maximum width. Not all the columns are being rendered at first, only after scroll it loads all the remaining cols.

**Steps to reproduce the problem:**
1. Go to http://jsfiddle.net/cyancscoutrfp/d9m6L9yb/
2. Run it in a small window
3. Maximize the window

:information_source:

> Handsontable v. 0.17.0
> Windows 8.1
> Chrome v. 44.0.2403.157 m

**Comment by AMBudnik** [comment]
Still present in 0.30.1

**Comment by AMBudnik** [comment]
The issue is still replicable suing v0.38.1

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0` and did not have an origin in any of previous releases/code changes.

**Comment by wojciechczerniak** [comment]
Should be fixed in v7.0.0-rc: http://jsfiddle.net/1czv8ak2/
