### ISSUE TITLE
Grouping and hiding rows

### ISSUE THREAD

**Issue by sfabriece** [handsontable/handsontable#2767]
Is there any sensible way to get row groups to expand and collapse as shown in the image? The tutorial in the documentation did not explain properly how modify the handles that collapse and expand the rows.

And is there any way to remove the extra columns that appear to the left of the table when grouping is enabled? [1, 2]

![groupingissue](https://cloud.githubusercontent.com/assets/3108592/9520241/b7ed08f4-4cc5-11e5-9179-9596af032190.jpg)

**Comment by AMBudnik** [comment]
Hi @sfabriece HOT doesn't have this kind of functionality, but you use example from [this issue](https://jsfiddle.net/xn8gfawv/) using `updateSettings` with specific list of rows.
