### ISSUE TITLE
how to make handsontable support olap like?

### ISSUE THREAD

**Issue by yozawiratama** [handsontable/handsontable#2768]
Hi i just curious, how to make handsontable support olap like?

for example i drag a field, and every data sort by that field or group by that field.

may be this can be next feature or may be i didnt know if handson table have this feature now.

thanks

i really love handsontable

**Comment by AMBudnik** [comment]
Hi @yozawiratama it would be great to use this kind of modeling but currently there is only 2D option available. You can try to search some ideas at [stackoverflow](https://stackoverflow.com/search?q=handsontable)
