### ISSUE TITLE
Set cell metadata in bulk

### ISSUE THREAD

**Issue by JacobEvelyn** [handsontable/handsontable#2769]
Our server sends down an array of data and a corresponding array of cell metadata. Setting cell metadata for all cells is a cumbersome process right now. We have to:

1. Load all the data for the table (we do this via `updateSettings`, but the mechanism shouldn't matter). This triggers a table render.
2. Manually loop through all cells and use the `setCellMeta` method.
3. Manually trigger another table render (since for us, metadata influences how cells should be rendered with our custom renderer) with `hot.render()`.

Ideally, we would be able to do this:

```
hot.updateSettings({
  data: data, // This is a 2D array.
  meta: metadata // This is a 2D array.
});
```

Does that sound possible? Is there another way to accomplish this?

**Comment by AMBudnik** [comment]
Only thing I can think of is ['cell'](http://docs.handsontable.com/0.17.0/Options.html#cell) both ways are good.
