### ISSUE TITLE
Handsontable with Rule.JS

### ISSUE THREAD

**Issue by ankitddit** [handsontable/handsontable#2771]
I have a problem when using formula with Handsontable. I am using container with the following setting:
" <div id="proj" style="width:600px; height:600px;overflow:hidden;" ></div>"
and we dump our handsontable object into this container. As you guys mentioned , if we use fix width and height , we will gain the performance with large data set. I do see the perfomance.

I am using  Rule.JS plugin to apply excel like formula here. I am using this formula to get total row:  but some how due to fix width and height of container , handsontable does not render all rows and columns and thus this formula does not calculate correctly as it does not find the cell value which are not rendered .

Do you guys have any idea how I can fix this ? so I dont have to compromise with handsontable performance.

**Comment by AMBudnik** [comment]
Please fill the settings or if you can please create a working demo.

**Comment by ankitddit** [comment]
HI ,

I will prepare this demo for you in some time. meanwhile would you help me with other issue ( Row height) misaligned when I have huge text for Autocomplet cell type. I have fixed panel as well. 

when i scroll to right , the rowheight misaligned . it seems the fixedpanel row height set according to the Autocomplete cell height but the movable panel set to different row height.
![image](https://cloud.githubusercontent.com/assets/13998736/9582850/e0ca46a2-4fd5-11e5-8cf2-04a54fcc357c.png)

**Comment by AMBudnik** [comment]
I assume this issue can be closed in lack of demo since few months. If you still face the same situation please create a demo and we'll reopen this issue.
