### ISSUE TITLE
how load multi sheet

### ISSUE THREAD

**Issue by khanhnam99** [handsontable/handsontable#2772]
i love handsontable, i problem , i see it has loaded a sheet 

example1 = document.getElementById('example1'); for sheet 1
example2 = document.getElementById('example2'); for sheet 2

var
    data = [
      ['', 'Kia', 'Nissan', 'Toyota', 'Honda'],
      ['2012', 10, 11, 12, 13],
      ['2013', 20, 11, 14, 13],
      ['2014', 30, 15, 12, 13],
      ['2015', '', '', '', ''],
      ['2016', '', '', '', '']
    ],
    container = document.getElementById('example1'),
    hot1;

  hot1 = new Handsontable(container, {
    rowHeaders: true,
    colHeaders: true,
    fillHandle: true // possible values: true, false, "horizontal", "vertical"
  });
  hot1.loadData(data);

var
    data2 = [
      ['', 'Kia', 'Nissan', 'Toyota', 'Honda'],
      ['2012', 10, 11, 12, 13],
      ['2013', 20, 11, 14, 13],
      ['2014', 30, 15, 12, 13],
      ['2015', '', '', '', ''],
      ['2016', '', '', '', '']
    ],
    container2 = document.getElementById('example2'),
    hot2;

  hot2 = new Handsontable(container, {
    rowHeaders: true,
    colHeaders: true,
    fillHandle: true // possible values: true, false, "horizontal", "vertical"
  });
  hot2.loadData(data2);

both this sheet only sheet, when click sheet 1 ,show sheet 1, when sheet 2 , show sheet 1.....
![capture](https://cloud.githubusercontent.com/assets/575720/9559995/c6f77350-4e2a-11e5-8e38-6deafd2f8606.PNG)

how create a new sheet  ? 

![capture](https://cloud.githubusercontent.com/assets/575720/9560250/36706e22-4e34-11e5-8ec6-3974729a07c7.PNG)

**Comment by AMBudnik** [comment]
You should use `conteiner2` in `hot2`, in code above you use the same container for both HOTs. If that won't work, please create a working demo (JSFiddle, JS Bin).

**Comment by AMBudnik** [comment]
Issue will stay closed till author's reply
