### ISSUE TITLE
double focus - one follow keyboard and another follows arrow key

### ISSUE THREAD

**Issue by chowkh** [handsontable/handsontable#2773]
I have a demo website where you can simulate the problem.
1. Go to http://privatedemo8.test.es2cloud.com/web3
2. login as root and password is root
3. Type the following url  http://privatedemo8.test.es2cloud.com/web3/AccInvoiceFormEngine?formid=test
4. Use the mouse to point to "Invoice No" 2nd column to highlight the cell.
5. Press "F2" key
6. Press "Tab" key
7. Then press the up or down arrow key.

You would notice that there is two focus. Up and down arrow keys has its own highlight.
Please let me know what mistake did we do and how to solve it.

**Comment by chowkh** [comment]
It seems that when it is a blank value, it will have the problem

**Comment by krzysztofspilka** [comment]
@chowkh it seems that the problems exists only with multiple instances of Handsontable. We will take a closer look at it.

**Comment by budnix** [comment]
Hi, After investigation I saw that you have wrong textValidator. Try this validator:
```js
function textvalidator (value, cb) {
    var prop = this.instance.getCellMeta(this.row, this.col);

    if (value === '' && prop.required) {
        cb(true);
    } else {
        cb((value.length > parseInt(prop.maxlen, 10)) ? false : true);
    }
}
```

**Comment by chowkh** [comment]
Yup. it seems to address the issue.
TQ
