### ISSUE TITLE
Handsontable's column header does not adapt to the master table in a dialog

### ISSUE THREAD

**Issue by pengbomuzzy** [handsontable/handsontable#2774]
![image](https://cloud.githubusercontent.com/assets/6486720/9582146/9c04ddec-4fd1-11e5-8cea-e614d2ea8432.png)

As the picture tells, I do not know what happens...

**Comment by pengbomuzzy** [comment]
I really tend to think that the clone top header is above the layer of the table, which has the scroll bar also.... How can I solve it? Thanks guys!

**Comment by AMBudnik** [comment]
Scroll bars are visible all the time or only when you want move beyond visible area?

**Comment by pengbomuzzy** [comment]
Hi, thanks for your reply. Because this is a 100*100 table, so the scroll bars are visible all the time. And the column header and the row header always looks like this...

**Comment by pengbomuzzy** [comment]
Hi, thanks for your reply. Because this is a 100*100 table, so the scroll
bars are visible all the time. And the column header and the row header
always looks like this...

On Tue, Sep 1, 2015 at 10:19 AM, Aleksandra Budnik <notifications@github.com

**Comment by pengbomuzzy** [comment]
BTW, I assign the dialog 'overflow' -> auto, so the scroll-bar is from
handsontable.

Thanks!

**Comment by AMBudnik** [comment]
Could you please provide more information of which dialog are you using in this project? Simple `html` or some kind of external library?

**Comment by pengbomuzzy** [comment]
Hi Aleksandra,

I am so glad that you reply to me. I have solved it just a moment ago. It
is because the CSS stuff, the dialog has padding which maybe a conflict. I
change to padding to (0 0) and the problem is gone. BTW, do you know why
the context menu sometimes is below the table, so that I cannot see the
context menu...?

Appreciated!

**Comment by AMBudnik** [comment]
There are some issues with `contextMenu` when there are two instances at the same page one under another. Did you observed any other odd behaviors of `contextMenu`? It should be visible even when the grid is partly hidden like in [this example](https://jsfiddle.net/u7wte7sL/)

**Comment by pengbomuzzy** [comment]
but there is nothing showing up in the result panel... What happened...

**Comment by AMBudnik** [comment]
Did you accepted scripts?

**Comment by pengbomuzzy** [comment]
[image: Inline image 1]after I run, there is nothing...
