### ISSUE TITLE
row misalign

### ISSUE THREAD

**Issue by ankitddit** [handsontable/handsontable#2775]
HI ,

I will prepare this demo for you in some time. meanwhile would you help me with other issue ( Row height) misaligned when I have huge text for Autocomplet cell type. I have fixed panel as well.

when i scroll to right , the rowheight misaligned . it seems the fixedpanel row height set according to the Autocomplete cell height but the movable panel set to different row height.

![image](https://cloud.githubusercontent.com/assets/13998736/9582924/3d4aee7c-4fd6-11e5-8faf-13af3cd75cd7.png)

**Comment by budnix** [comment]
To fix this rows misalignment please try to enable AutoRowSize plugin (autoRowSize: true).

**Comment by ankitddit** [comment]
I tried to using this setting . but this slows down the performance .. 

also notice another problem with grouping and fixedcolumn .

look at this screenshot . I do have grouping . 
![image](https://cloud.githubusercontent.com/assets/13998736/9587482/c12b02d0-4ff0-11e5-92e2-f2f855769988.png)

when I click on last grouping column to collapse. It still shows the column and the expand button disappears..

![image](https://cloud.githubusercontent.com/assets/13998736/9587546/1228fef8-4ff1-11e5-9681-fdb2edd5206e.png)

**Comment by AMBudnik** [comment]
Hi @ankitddit `AutoRowSize` is little bit slower cause it has to count row size, that it why it's `false` at default. 

About grouping there are few things that can be done, but what I can recommend is to use hidden columns](http://docs.handsontable.com/0.17.0/tutorial-data-sources.html) with custom buttons instead.

**Comment by ankitddit** [comment]
Hi, Thanks for you update. Can you tell me is there any way to get cell value inside beforechange event ?

I am using  the below method call inside beforechange event to get new inserted cell value. but somehow it returns old value.. 


this.getDataAtCell = function (row, col) {
                return datamap.get(row, datamap.colToProp(col));
            };
