### ISSUE TITLE
Custom Cell Renderer HTML Being Replaced with Other Column's Data

### ISSUE THREAD

**Issue by AggieCridmus** [handsontable/handsontable#2776]
I'm currently experiencing an interesting issue with one of my custom renderers with Handsontable 0.16.1. The following plunk shows this issue: http://plnkr.co/edit/BZITgHgCWFXIe3f8MLuZ

**Requirement:** I have the requirement of having a dropdown and a button in a cell for specific columns (Middleware Required and Database Required in the plunk). After the user chooses a dropdown value and clicks the button next to the dropdown, a modal with data specific to that dropdown option is displayed. 

**Issue:** With the Database Required column, sometimes choosing a value in the dropdown causes all of the HTML in that column of cells to be cleared and data from other columns replace it. Also, simply scrolling horizontally causes this issue as well. Of course, after scrolling the column out of the view and back in, it resets back to normal but then the issue is reproducible again. I also see this issue depending on the position of the column within the view, e.g. I can change the dropdown value and everything is fine but if I scroll the grid a bit to the left or right and change the dropdown value the issue occurs.

Am I correctly performing cell rendering or am I missing something here? What would be the best way to have a dropdown and button in the cell at the same time and is it possible to have the value changed through click-and-drag on the fill handle? 

**Note:** I apologize ahead of time for the ugly code. I'm pulling it from a large project and tried to include only parts that were necessary to reproduce the problem. Also, thanks!

**Comment by AggieCridmus** [comment]
Any chance someone has had a look at the plunk I provided? To reproduce the issue:
* Scroll to the right in the table until you see the Database Required column (it should have a select dropdown and a button in the cell).
* Change the dropdown value. Sometimes this is enough to cause the issue if the column is in a certain "postion" on the screen after scrolling.
* Also try scrolling horizontally slowly while this column is in view.
It seems like any time the renderer is called there is a potential for the issue to happen.

**Comment by AggieCridmus** [comment]
Closing issue due to no responses and I decided to go in a different direction. I still believe there is an issue here that's worth looking into.

**Comment by IgorShch** [comment]
Had the exactly same problem and also went for a different solution.
