### ISSUE TITLE
Would like to have table headers text wrap and scalable live

### ISSUE THREAD

**Issue by cyancdesign** [handsontable/handsontable#2778]
We would like to be able to have headers where the text wraps and the column widths are adustable on the fly. But there are issues.

![image](https://cloud.githubusercontent.com/assets/220064/9615123/49e83858-50c4-11e5-8070-6391dc8e3473.png)

expand width: header's height doesn't scale down.
![image](https://cloud.githubusercontent.com/assets/220064/9615141/5d837008-50c4-11e5-9818-01489956be3d.png)

contract width: row titles do not realign properly
![image](https://cloud.githubusercontent.com/assets/220064/9615163/7545fbd4-50c4-11e5-9979-9635c9afb49f.png)

http://jsfiddle.net/cyancscoutrfp/hqLbg3rt/

**Comment by AMBudnik** [comment]
Thank you @cyancdesign confirmed with the latest HOT version.

**Comment by cyancdesign** [comment]
@AMBudnik any projected fix for this?

**Comment by AMBudnik** [comment]
@cyancdesign I would really want to say yes but currently all over focus is at PRO. As long as we'll have any updates about this bug, issue gets updated.

**Comment by AMBudnik** [comment]
still occurring with 0.23.0 - http://jsfiddle.net/hqLbg3rt/1/

**Comment by AMBudnik** [comment]
Issue no longer occurs. Currently adding `autoRowSize: true` to spreadsheet settings works also for headers, demo: http://jsfiddle.net/6tjdqokg/
