### ISSUE TITLE
Can't render all columns in Bootstrap 3.x Modal Dialog

### ISSUE THREAD

**Issue by nothingmi** [handsontable/handsontable#2779]
SUGGESTION:

I created a handsontable object in a Bootstrap Modal Dialog, like $("#somediv").handsontable({ ... }),  and created  a button to toggle the dialog. When I click the button, the dialog display, but I found the handsontable was incorrect in appearance, only ONE column was rendered besides its row header.

It's no matter what the settings are.

I found a man face the same problem, http://jsfiddle.net/5Zv8h/4/light/

Then I tried to find out what the problem is, and the conclusion is that handsontable can't calculate the width of its container which is invisible (P.S. I mean display:none;).

However, I have found the solution, that get data in document.ready and generate handsontable after the dialog appearance.

So, I think it maybe a trouble to others, could you make a topic in your Documents to help any other people? Thanks. :)

**Comment by tshort** [comment]
I have this issue, too. Thanks for the tip on the work-around.

**Comment by AMBudnik** [comment]
Hi @nothingmi and @tshort could you check it with the latest version?

Thanks in advance!

**Comment by usnjoker** [comment]
i have same issue, too. but i found working solution.

`
$modal.on('shown.bs.modal', function() {
            $(document).off('focusin.bs.modal');
            setTimeout(function() {
                $excelTable.handsontable("selectCell", 0, 0);
            }, 10);
        });
`

**Comment by AMBudnik** [comment]
thanks for sharing your code @usnjoker

**Comment by opodecano** [comment]
Same problem Inside a modal
the working solution:
	  $("#lista").on("show.bs.modal", function (e) {
            setTimeout(function() {
                $('#example1').handsontable('render');
            }, 200);
});

**Comment by nothingmi** [comment]
I contribute a handsontable in the event 'shown.bs.modal', and it works.
The same solution as 'shown.bs.tab' and so on:)

**Comment by Mrinal9024** [comment]
can anyone provide provide sample for this. I am also facing the same issue and I am using 
`$('data-target').on('shown.bs.modal', function() {					
				    $(document).off('focusin.bs.modal');
				});	`

`document.addEventListener("DOMContentLoaded", function() { //some code});`

and inside above listner

`Handsontable.dom.addEvent(document.body, 'click', function (e) {});`

I am not getting how to use above example.

**Comment by AMBudnik** [comment]
I think that we can close the issue. It has been mentioned is a few reports before but the only reason why the table is not fully loaded is the CSS settings that it reads to calculate its size. If we do not pass height/width, use `display: none` or any settings that have a similar effect the table is not able to count how big it can display.

Please check if adding an extra rendering solves the issue. In some cases, you would need a slight delay (~10ms) to get the full table.
