### ISSUE TITLE
After moving a column, the width of the column change.

### ISSUE THREAD

**Issue by hilxm** [handsontable/handsontable#2780]
Hi, could you please fix it?
When move  a column, it's width change. 
But, if i resize the column before, it's width will not change.

**Comment by AMBudnik** [comment]
Confirmed with [this example](https://jsfiddle.net/jou99uyx/1/) (0.17.0 version) 
Column width stays the same after `manualColumnMove` only data migrates between cells, but if before doing `manualColumnMove` `manualColumnResize` is used data migrates between cells with it's column width value.

**Comment by AMBudnik** [comment]
Hi @hilxm 
I was trying to replicate this issue but I'm not sure of expected results. Can you check if the latest version (v0.31.0) works well https://jsfiddle.net/handsoncode/jbmuygsk/ ?
Do we need to change the width each time or don't change it at all.

**Comment by AMBudnik** [comment]
Confirmed in 0.31.2. I have misunderstood it before.

**Comment by mkolmogorov** [comment]
Bug still appears in 0.33.0 version

**Comment by AMBudnik** [comment]
I've made this example using v `2.0.0.` https://jsfiddle.net/t7ug3kag/
but I do not think that it's an issue as above we used the `colWidths` so the width of a column did not change (it couldn't).

I am closing this issue but let me know if I've missed something.
