### ISSUE TITLE
Add an option about : row : { RowRender , RowID ..  }

### ISSUE THREAD

**Issue by hilxm** [handsontable/handsontable#2781]
As below：
row:{ 
    render: function( tr(Element), rowId(custom ID), rowIndex, rowData(array or Object) ){
         // deal like clumns.render .... 
    }
}

the param of " rowId(custom ID)" will be very usefull.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
Will be added with https://github.com/handsontable/handsontable/issues/4055
