### ISSUE TITLE
Move/Resize options for specified columns/rows

### ISSUE THREAD

**Issue by hilxm** [handsontable/handsontable#2782]
As bellow:
columns:[
    {
        moveable: boolean,
        resizeable: boolean,
        hidden: boolean,
    }
]

^_~

**Comment by AMBudnik** [comment]
I guess it would more look like:

`columns: [
    	{},
        {
      		manualColumnMove: true
    	}
    ]`

but it's a good idea. Now you can only set this settings for whole grid.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
