### ISSUE TITLE
muli select rows

### ISSUE THREAD

**Issue by hilxm** [handsontable/handsontable#2783]
select rows by :
Ctrl + mouseClick rowHeader,
Shift + mouseClick rowHeader,

the selected rows can be discontinuous, jus like excel~

And add a method:
hot.getSlectedRows()

**Comment by AMBudnik** [comment]
@hilxm we have the same issue at https://github.com/handsontable/handsontable/issues/2119 it's closed till it'll get under development so please track changes to https://github.com/handsontable/handsontable/issues/2119 for fresh information in this subject,
