### ISSUE TITLE
Handson table Infinite Scroll to load data

### ISSUE THREAD

**Issue by vikashait** [handsontable/handsontable#2784]
Hi Guys, 

I would like to make ajax call to load data when user vertical scroll to bottom. I cannot afford to load all the data upfront, I mean thats not the requirement at all.

I tried using afterScrollVertically() event but it is getting called as soon as user starts scrolling, I want event to get fired only if user scrolled to bottom

Can you please advise how to implement this?

**Comment by AMBudnik** [comment]
It's the programming championship kind of solution, but maybe it will give you an idea how to achieve your goal, [here's](https://jsfiddle.net/hwjsstq1/) the example.

**Comment by christian-heath** [comment]
The above solution commented by @AMBudnik is broken in jsfiddle. Could you please post an updated version or update the fiddle? Thanks

**Comment by AMBudnik** [comment]
Here you go @christian-heath https://jsfiddle.net/ke60pzbd/

However, looking at the reactions I can see that it did not meet all user requirements.
Please treat this as a rough idea and officially we do not support infinite scroll. It should add new rows, while the code above after scroll reloads the data to load a bigger set of rows.
