### ISSUE TITLE
Number column values display worng result.

### ISSUE THREAD

**Issue by logeshkumars** [handsontable/handsontable#2785]
Hi Team,

"numeric" columns values having large number means it will display wrong result.
Actual value = 469864000010470003 , display value = 469864000010470016

example  : http://jsfiddle.net/0acobjxL/1/

Thanks,
Logesh

**Comment by AMBudnik** [comment]
@logeshkumars thanks for sharing

When there is a value around 1 * 10(15) everything works fine, 

With 1 * 10(16) data source value is changed at 1 * 10(0) part. 

In case where the value is (3 * 10(1)) values at the 1 * 10(0) part less than `5` is showing as `2` and while editing as `0` and if the 1 * 10(0) part is grater than `5` value changes like (1 * 10(1)) + (10(1)) with 1 * 10(0)) part as `0` (also while editing). 

When the value is different than (3 * 10(1)) value is changed differently.

**Comment by logeshkumars** [comment]
@AMBudnik Thanks for the detailed explanation.

Then what is the solution for this use case ?

Thanks,
Logesh

**Comment by AMBudnik** [comment]
I was looking for an answer and I found interesting issue at numeral.js's github issue board (which we are using in HOT for `numeric` type cell) like [here](https://github.com/adamwdraper/Numeral-js/issues/205)

**Comment by logeshkumars** [comment]
@AMBudnik Thanks
