### ISSUE TITLE
Error when add a new column

### ISSUE THREAD

**Issue by neomede** [handsontable/handsontable#2786]
Hi, I found a bug when you add a new column to a table, i've created a [jsfiddle](http://jsfiddle.net/mgrtgqLz/) to show the error, you should scroll over the table until you see the last column, then you add a new column and this throw the following error:
> Uncaught TypeError: Cannot read property 'contains' of undefined

This error only happens if you add validation to the column.

**Comment by AMBudnik** [comment]
Confirmed. While adding new columns there are some rendering issues and a console log error.
When we comment `//height: 396,` line everythings works fine.

**Comment by neomede** [comment]
I commented the line with "height" but still happening the same error, I updated the jsfiddle https://jsfiddle.net/sjecjecc/1/. I think is a problem with "rowHeaders", if I commented that line everything works fine.

**Comment by AMBudnik** [comment]
You're right, when we comment `rowHeaders` code works fine but when (in the same time) `height: 396` is active the 'Add Column' button goes too far on the right.

**Comment by neomede** [comment]
Yes, but this is because the css of that div, I put "width: 1600px" to be able to add new columns and see the error of handsontable.

**Comment by neomede** [comment]
To temporarily fix this error, I do the next:

```javascript
    
    hot.updateSettings({
        colHeaders: colHeaders,
        rowHeaders: false, //Set rowHeaders to false
        columns: columns
    });
      
    hot.validateCells(function() {
        //Set rowHeaders to true again after validateCells
        hot.updateSettings({
            rowHeaders: true
        });
    
        hot.render();
    });
```
