### ISSUE TITLE
Add a load condition in cells option

### ISSUE THREAD

**Issue by Erlaunis** [handsontable/handsontable#2787]
Hi, I have a grid with this folowing parameters : 

    cells:function(row,col,prop){ 
						
			                    var cellProperties = {};
			                    
			                    if ([0].indexOf(row) !== -1 && col >= 0)  
			                    {
			                        cellProperties.readOnly = true;
			                        cellProperties.renderer = firstRowRenderer;
			                    }

			                    if(([0].indexOf(col) == 0) && (data_itk_pro_update[row][0]) && flag==true) //Here is the function to block the first column
			                    {
			                        cellProperties.readOnly = true;
			                    }

			                    if(([1].indexOf(col) == 0) && (data_itk_pro_update[row][1]) && flag==true)
			                    {
			                        cellProperties.readOnly = true;
			                    }

			                    if (readOnlyCellsITKPROU[[row,col]]) { 
			                        cellProperties.readOnly = true;
			                    }

			                    return cellProperties;
			                    },

I just want to add a load condition like "if(window.onload){" or "$(window).load(function () {" but it doesn't work. I didn't find anything on the doc. 
If there is an other solution, I just want to run this code only once, when the grid is created. Because if the user add some values, this code works for the new values too, and I don't want that.

**Comment by AMBudnik** [comment]
You could use [`once`](http://docs.handsontable.com/0.17.0/Hooks.html#once) like written in the docs it runs once and then it's gone.

**Comment by Erlaunis** [comment]
Thanks ! But I don't understand how to use it :/ Because I'm using the parameters `row,col` of `Cells`. Can I combine the two events ?

**Comment by Erlaunis** [comment]
After checking this doc, can I use {hot.addHookOnce('cells');' in my case ? But if I understand, it will apply the event on the entire `cells` whereas I have a condition ... this one : 

    if (readOnlyCellsITKPROU[[row,col]]) { 
                                cellProperties.readOnly = true;
                            }

That I want to run several times :/ So I don't what to run one time the entire `cells`

**Comment by AMBudnik** [comment]
Hi @Erlaunis if you still face problems with the code, please create a demo.

**Comment by Erlaunis** [comment]
Hi @AMBudnik ! I do not own this code anymore, the project is done for me ! Thanks !

**Comment by AMBudnik** [comment]
OK, thanks for reply @Erlaunis
