### ISSUE TITLE
Render rows at rowsNumber

### ISSUE THREAD

**Issue by marc-antoinepelletier** [handsontable/handsontable#2791]
I have a set of data which contain the row number of each rows, is there is a way to use this value to render each row where they belong ?

e.g :  
rows = [
{ rowNumber: 0, value: 'hello'},
{ rowNumber: 1, value: 'world'},
{ rowNumber: 5, value: 'GoodBye'},
{ rowNumber: 123, value: 'Farewell'},
]

When I load my table it set the rows on the first 4 lines, instead of setting the two first on the row 1 and 2, and the other further down. Can I do that in the renderer or somewhere else ?

**Comment by AMBudnik** [comment]
If you don't have a lot of this special headers you can try to use a function to create custom `rowHeaders`, [example](https://jsfiddle.net/jcbro272/1/).

Like you see, the rest of them are default values (integers).

Remember that this headers are not bounded with data, if row gets deleted custom Header will stay at the same position. To avoid it you would have to create a callback and change `rowHeaders` also.
