### ISSUE TITLE
How to check if row is valid or not? (Validation)

### ISSUE THREAD

**Issue by RaghavPro** [handsontable/handsontable#2792]
Is there's a way to check if a row contains valid data or not?
I want to send only valid data to the server. 
Right now I'm sending rows which are not empty using the `isEmptyRow`. Couldn't find anything like `isRowValid`.

**Comment by AMBudnik** [comment]
Hi @RaghavPro [here's](https://github.com/handsontable/handsontable/issues/2262) the same issue. Please track changes to https://github.com/handsontable/handsontable/issues/2262, we do not replicate issues.
