### ISSUE TITLE
how to get row by rowindex?

### ISSUE THREAD

**Issue by AlexJake** [handsontable/handsontable#2793]
i want to add custom column to remove current row button in every row,when a new row was created。but i can't find an event can work that .so i use `afterCreateRow` event ;
```
afterCreateRow:function(index, amount){
//change the row object 
}

```
my question is how to get the row by rowindex?

**Comment by AMBudnik** [comment]
to remove a specific row you can use `alter` like so: https://docs.handsontable.com/0.23.0/Core.html#alter
