### ISSUE TITLE
Add option `visibleRows` for Autocomplete cells.

### ISSUE THREAD

**Issue by vo-va** [handsontable/handsontable#2794]
In current code scrollbar of dropdown list of choices for autocomplete cell will be visible if number of choices will be greater than 10, and it's hardcoded 
https://github.com/handsontable/handsontable/blob/master/src/editors/autocompleteEditor.js#L295
Add option `visibleRows` for Autocomplete cells to control number of choices after exceeding it scrollbar will be visible.

**Comment by krzysztofspilka** [comment]
Tested and working http://jsfiddle.net/hnyL7L25/1/ (third column now has visibleRows set to 3)
