### ISSUE TITLE
Autocomplete position in relation to the browser window.

### ISSUE THREAD

**Issue by afbruno** [handsontable/handsontable#2798]
When the table occupies the entire screen, the autocomplete menu does not appear for the last line. It should appear on top of the cell.
It will be nice to position the autocomplete (menu) properly in relation to the browser window. That is, when the autocomplete is at the top of the page get the menu going down and if at the bottom of the page get the menu going up (even if we have some vertical scrollbar).
Thank you

**Comment by AMBudnik** [comment]
Could you please prepare a sample code? I tried with `data: Handsontable.helper.createSpreadsheetData(30,20)` which covers the visible area, but the last cell with `autocomplete` type works fine, options can be opened it only makes the scroll appear.

**Comment by afbruno** [comment]
I just loaded handsontable with height = windows();
The autocomplete element opens always from the bottom of the cell. Thus, it can be hidden if the last cell (located on the bottom edge of the window) is selected. The ideal is that in this case, above the autocomplete open cell.
See the attached images.

**Comment by AMBudnik** [comment]
Unfortunately there are no images, but I guess you mean something like this

![zrzut ekranu 2015-09-09 o 18 28 49](https://cloud.githubusercontent.com/assets/10757813/9768069/a61fdbd6-5721-11e5-95a1-b813cfb33fef.png)

This behavior will be changed but we don't have actual date when.

**Comment by afbruno** [comment]
Exactly. ummmm =/ I will wait..Any expecting date for the PRO version?
Thank you anyway. 

---------------------------------------------------------------------------------------------------------------------------------Bruno Aquino Filardi FilhoMestre em Engenharia Elétrica - UFMGGraduado em Engenharia Elétrica - UFMGbruno_aquino@hotmail.com - (31)8744-7494

Date: Wed, 9 Sep 2015 09:38:59 -0700

**Comment by AMBudnik** [comment]
We are planning to reveal HOT PRO in November
