### ISSUE TITLE
Why I have element.addEventListener is not a function?

### ISSUE THREAD

**Issue by teoSalvetti** [handsontable/handsontable#2799]
I'm trying to implement handsontable into my webapp, so I imported `handsontable.full.js` and `.css`, then I  insert this simple example:

```
var data = [
  ["", "Ford", "Volvo", "Toyota", "Honda"],
  ["2014", 10, 11, 12, 13],
  ["2015", 20, 11, 14, 13],
  ["2016", 30, 15, 12, 13]
];

var container = document.getElementById('example');
var hot = new Handsontable(container, {
  data: data,
  minSpareRows: 1,
  rowHeaders: true,
  colHeaders: true,
  contextMenu: true
});
```

But I obtain this error, and nothing appear:
`element.addEventListener is not a function`

I'm using jQuery 1.11.

How can I solve it??

**Comment by samuelstein** [comment]
any solution here? i have the same problem

**Comment by AMBudnik** [comment]
Hi @samuelstein 
could you share a demo where we can replicate the issue?
I sounds like there the are some issues with scripts order but it's hard to say without a demo the example above uses vanilla js and looks as expected

**Comment by samuelstein** [comment]
i experienced this bug when optaining the handsontable instance via jquery. for example: var container = $("#sheetContainer");

**Comment by AMBudnik** [comment]
@samuelstein 
Please take a minute to check this tutorial: https://docs.handsontable.com/pro/1.4.0/demo-jquery.html
I think that it will come in handy.

**Comment by samuelstein** [comment]
thanks for the tip. now i'm getting the error when calling: 
` Handsontable.Dom.addEvent($('#searchField'), 'keyup', function(event) {
        var queryResult = hotInstance.search.query(this.value);

        console.log(queryResult);
        hotInstance.render();
    });`

**Comment by AMBudnik** [comment]
Can you try to load your script into the jQuery example here: http://jsfiddle.net/L8uz82wv/?

**Comment by AMBudnik** [comment]
Issue will be reopened with a new update.
