### ISSUE TITLE
Scrolling to the left and right when groups exist causes JS crash

### ISSUE THREAD

**Issue by dasaevc** [handsontable/handsontable#2801]
Version: 0.17.0

When I have scroll in a grouped table, and I do scroll to the right or left, a crash happens and then my HOT stops to work properly.

The error is happenning on the line 8635 of handsontable.full.js. The error message says:
Uncaught TypeError: Cannot read property 'firstChild' of null

The same error occurs on the demo page: 
http://docs.handsontable.com/0.17.0/demo-grouping-and-ungrouping.html

But the sample HOT doesn't stop to work.

**Comment by AMBudnik** [comment]
Thank you @dasaevc I confirm this issue.

**Comment by AMBudnik** [comment]
Grouping abbanoded according to https://github.com/handsontable/handsontable/releases/tag/0.18.0
Instead, we're working on a very similiar functionality - Nested Rows

**Comment by AMBudnik** [comment]
Update: grouping will no longer be supported from 0.19.0
