### ISSUE TITLE
this is a question not  an issue, Is there any way to select a row depending on the row index passed.

### ISSUE THREAD

**Issue by sandeepmsr** [handsontable/handsontable#2802]
Say i have a textbox and in the textbox I pass row index then it should select the row. I will be very glad if you can guide me through this. thank u :)

**Comment by motin** [comment]
https://github.com/handsontable/handsontable#questions

**Comment by AMBudnik** [comment]
Thank you @motin 
@sandeepmsr please use [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/handsontable) or [Stackoverflow](https://stackoverflow.com/search?q=handsontable) for subjects that are not strictly HOT issues.
