### ISSUE TITLE
getCoords not returning correct column when using fixedColumnsLeft

### ISSUE THREAD

**Issue by squaretabledev** [handsontable/handsontable#2803]
I have functionality in the grid where the user is required to click cell that brings up a popup for them to add more information. 

The grid has fixedColumnLeft set. When I don't scroll horizontally the getCoords returns the correct column. As soon as I scroll horizontally the getCoords returns the wrong column for any of the fixed columns on the left of the splitter. This seems to always be out of sync with the value of the colOffset() function. So if I take getCoords().col - colOffset() I get the correct value. The cells on the right of the splitter appears to be working as expected. Is this a bug or am I missing something here?

I don't have time to create a sample for this at the moment but will attempt to build one later if needed.

**Comment by AMBudnik** [comment]
Please create a demo in your time, there could be many this related to this issue.

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply/demo.
