### ISSUE TITLE
Browserify compile error : Cannot find module '../browser' 

### ISSUE THREAD

**Issue by Jolg42** [handsontable/handsontable#2804]
Hi,

I was using the full.js without any problem but now for performance and avoiding librairies duplicates I am trying to use the 'light' dist/handsontable.js.

I'm using the latest version 0.17.0

Here is the log from our browserify :
```
Error: Cannot find module '../browser' from '/Users/user/site/node_modules/handsontable/dist'
at /Users/user/site/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
at load (/Users/user/site/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
at onex (/Users/user/site/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
at /Users/user/site/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
at FSReqWrap.oncomplete (fs.js:95:15)
change:admin/client/src/js/vendor.js
```

It looks like there is a problem with browser.js, there are references to 2 differents 'browser' libs one relative  '../browser' and the other 'helpers/browser' but their number is the same : 42 !

**Comment by frode-carlsen** [comment]
I get the same issue with 0.0.18.  Any update ?

**Comment by timwis** [comment]
I'm running into this as well on 0.20.2

**Comment by timwis** [comment]
I've got it! The problem was that browserify parses handsontable.js and replaces its `require()` calls with its own module loader logic. Use browserify's `noParse` option on handsontable to have it just pull it in without parsing it. For example:
```javascript
browserify({
  noParse: [require.resolve('handsontable/dist/handsontable.full')]
})
```

**Comment by jpravetz** [comment]
Thanks for sharing, Tim. I've just been loading handsontable with it's own script tag (along with one or two other mischief files), leaving them out of my vendor and app bundles until I could spend time looking for a solution.
