### ISSUE TITLE
HOT messed up when updating groups

### ISSUE THREAD

**Issue by dasaevc** [handsontable/handsontable#2805]
Version tested: 0.16.1 (Also happens on v 0.17.0)

I have a HOT that has to refresh the groups by Ajax, when those groups are updated using 
updateSettings, this refreshes the HOT instance but all the UI appears very messi.

See an example here: http://jsfiddle.net/njoe51sf/, although this is not using ajax, the principle is the same.

Regards.

**Comment by AMBudnik** [comment]
Curretly there are few issues with grouping. Thanks for sharing the code.

**Comment by AMBudnik** [comment]
Grouping abbanoded according to https://github.com/handsontable/handsontable/releases/tag/0.18.0
Instead, we're working on a very similiar functionality - Nested Rows

**Comment by AMBudnik** [comment]
Update: grouping will no longer be supported from 0.19.0
