### ISSUE TITLE
Programmatically changing manualColumnMove breaks the grid functionality

### ISSUE THREAD

**Issue by vbankov** [handsontable/handsontable#2807]
When I change the manualColumnMove to false using

hot.updateSettings({manualColumnMove: false})

after a column has been moved, the table returns to its previous state and switching back to true is impossible.

Here's a fiddle with the problem jsfiddle.net/n9bL1vLx/4/

**Comment by toresenneseth** [comment]
The same applies to column sorting. If updateSettings is executed, column sorting is reset.

**Comment by AMBudnik** [comment]
Confirmed both examples:
1. with `manualColumnMove`
2. with `columnSorting`

**Comment by krzysztofspilka** [comment]
@toresenneseth can you confirm that it works properly with the latest version of Handsontable?

**Comment by AMBudnik** [comment]
@krzysztofspilka unfortunately still present. 

Updated demo (0.23.0): http://jsfiddle.net/n9bL1vLx/5/  
tip: `manualRowMove` is not reflected only `manualColumnMove`

**Comment by AMBudnik** [comment]
Still reproducible
`manualColumnMove`(0.26.0) http://jsfiddle.net/zo57uosv/1/
`columnSorting` (0.26.0) http://jsfiddle.net/ecko3y6a/

**Comment by swistach** [comment]
`manualColumnMove` works properly since 0.24.0: http://jsfiddle.net/n9bL1vLx/6/

`columnsSorting` I think we should continue this issue in #3434
