### ISSUE TITLE
Set the offset for rows

### ISSUE THREAD

**Issue by darkmavis1980** [handsontable/handsontable#2808]
In one of the projects I'm working at the moment, we use handsontable to view/edit huge dataset (millions of rows), and because of the huge number of rows, if the user want to jump to row 10000 (for example) now I have to render all the 10000 rows, which is rather bad, and what I would like to do is a function to jump to a specific row and render, for example, the 50 rows before and 50 after, which my API allows for that.
My only problem is, if I jump to the 10000th row, and get the data from row 9900 and 10100, the row counter will start from 1 and not 9900. 
There's any way for me to load some data and set the offset for the row counter to 9900 instead of 1?

**Comment by AMBudnik** [comment]
Hi @darkmavis1980 did you saw our stackoverflow topics? It's the best place to search for usage examples of HOT while github is more like a place to report issues.

Here's the [SO topic](https://stackoverflow.com/questions/30478550/handling-big-data-with-angular-meteor-and-handsontable) that can be helpfull in your case.

**Comment by darkmavis1980** [comment]
@AMBudnik no I didn't know about that, thanks

**Comment by darkmavis1980** [comment]
Uhm, yeah I read the topic, but it's not exactly my case

**Comment by AMBudnik** [comment]
Yes I agree it's not the same, but maybe there's a good idea to split data and serve packages of it depending on the user's choice.

We're very into performance and HOT will definitely go in this direction but there are things that has to be done first so maybe in your case scenario above would work faster as a temporary workaround.
