### ISSUE TITLE
Opera Selects correctly online, but not offline

### ISSUE THREAD

**Issue by lope** [handsontable/handsontable#281]
Selecting a few cells works as expected online

Downloaded master branch 0.7.5.
Tested index.html in opera from hard drive and the selection doesn't work properly.
(the first cell is not selected and following cells look funny but will get copied when Ctrl-C)
Chrome works fine online and from hard disk.

Running opera 12.01 x64 on W7 build 1532

**Comment by AMBudnik** [comment]
Checked on Opera 28.0.1750.51. Since it's a very old issue @lope please check is it still occur and if so, we'll reopen the issue.
