### ISSUE TITLE
Possible Chrome Bug with DatePicker in versions later than 15.1

### ISSUE THREAD

**Issue by jaredbaszler** [handsontable/handsontable#2812]
I posted a possible bug with the Chrome browser here.  Please take a look.  

http://stackoverflow.com/questions/32552248/handsontable-chrome-bug-with-datepicker

**Comment by AMBudnik** [comment]
I tried it with Win7/Chrome45 and OSX/Chrome45 and I didn't get the odd behavior with 0.18.0
Could you please provide more information about you soft (OS/Browser addons). Thanks in advance.

**Comment by jaredbaszler** [comment]
I'm running Windows 10, Chrome v.45.0.2454.85 and I disabled all my Chrome Exensions and I got the same behavior.  I tried it on my other machine in the house (Win 7/Chrome) and it worked fine there.  Let me know if there is any other dubugging steps I can take to track down the issue.

**Comment by jaredbaszler** [comment]
I did some more digging tonight and found out what the problem likely is.  The machine I listed above is a Lenovo Yoga Pro 2 (hybrid/tablet) so it won't work to select the date with my touch pad but if I use the touch screen it works as expected.

**Comment by AMBudnik** [comment]
Thank you @jaredbaszler it is a valuable information.

**Comment by jaredbaszler** [comment]
Looks like there is already a solution to this in the Pickaday repository:

https://github.com/dbushell/Pikaday/issues/276

**Comment by AMBudnik** [comment]
Thank you @jaredbaszler for further details and investigation of this issue. We will take a closer look at this subject.

**Comment by jaredbaszler** [comment]
This actually looks like a better solution to me. 

https://github.com/dbushell/Pikaday/issues/374
