### ISSUE TITLE
Multiple selection rendering like google spreadsheet

### ISSUE THREAD

**Issue by avilaton** [handsontable/handsontable#2813]
Hi all,

We are using handsontable to get a user's selection of a cell ranges. We would like to render these selections like it is done in spreadsheets (see attachment) and we have hacked a way to do so by messing with the renderers and adding a custom class name to each selection. 
I understand we should be able to create a plugin that uses WalkontableSelection to get this into a better shape so we can submit it to you as a contribution. Have you got anything planned along these lines? do you have any suggestions?
![screenshot from 2015-09-14 12 51 32](https://cloud.githubusercontent.com/assets/2209022/9854512/82ecbaaa-5adf-11e5-875f-6e336cff6ad6.png)

**Comment by AMBudnik** [comment]
Hi, this could be great @avilaton 
Currently we're into Handsontable PRO but formulas and related topics are one of our priorities for 2016

**Comment by krzysztofspilka** [comment]
@avilaton you can vote on this feature on FeatHub http://feathub.com/handsontable/handsontable/+18

Namely, for non-consecutive but this will include selecting ranges as well.

**Comment by avilaton** [comment]
Thanks!

**Comment by sudofix** [comment]
any updates on how to achieve something like this in the current versions?

**Comment by AMBudnik** [comment]
Hi @sudofix since the creation of this issue we replaces the old formula engine and now we use [HyperFormula](https://github.com/handsontable/hyperformula). The point and click feature is not yet applied. I will make sure to inform you as soon as we add it.
