### ISSUE TITLE
renderer: 'html' and minSpareRows is inserting 'null' into new cells.

### ISSUE THREAD

**Issue by djseng** [handsontable/handsontable#2816]
Here is a fiddle that reproduces the issue. http://jsfiddle.net/ao26oekz/14/

**Comment by AMBudnik** [comment]
Thank you @djseng confirmed 
`null` values are gone partly where we type something into the cell like `<a href="#">a</a>`
![zrzut ekranu 2015-09-16 o 17 03 57](https://cloud.githubusercontent.com/assets/10757813/9908684/0ce1a336-5c95-11e5-990e-a6b1db22ca3d.png)

**Comment by djseng** [comment]
I'm using the following renderer temporarily:

    function cleanHtmlRenderer(instance, td, row, col, prop, value, cellProperties){
        Handsontable.renderers.HtmlRenderer.apply(this, arguments);
        if (td.innerHTML === 'null') {
            td.innerHTML = '';
        }
    }
