### ISSUE TITLE
Autocomplete Sorting 

### ISSUE THREAD

**Issue by Gorfaal** [handsontable/handsontable#2817]
Is there a function available to override the way autocomplete drop downs get sorted? Right now it seems that if you start filtering it reorders the autocomplete select randomly (perhaps based on index of filter in the string?) -- this needs to remain alphabetically sorted at all times in my application.

Was hoping I could set the source of the autocomplete to a function that sorted the list.

Thanks!

**Comment by AMBudnik** [comment]
Hi @Gorfaal 
[Here's](http://jsfiddle.net/62cgs7ua/1/) the example you were looking for. Autocomplete does not only accept arrays, you can use a function also. This function takes two arguments: query string and callback. 

Using function as a source for your autocomplete requires custom made filter and sorting (like in example above).

**Comment by Gorfaal** [comment]
Thanks!!
