### ISSUE TITLE
handsontableInput doesn't show on selected cell position while it's scrollable in div

### ISSUE THREAD

**Issue by DhavalGPatel** [handsontable/handsontable#2818]
Hello Aleksandra,

I have more than 20 columns which can bee seen using scrolling horizontally.for that i have given inline css in div. problem is i have used autocomplete in last column. when i clicked on it the autocomplete option doesn't show at correct position. Can you help me on this please ?

When i clicked on State auto complete option dons't show.Sometimes it show but not at at correct position. Here i have attached issue demo
![autocomplete cell 2015-09-17 12-21-11](https://cloud.githubusercontent.com/assets/14308243/9926837/b522fb98-5d36-11e5-95ea-257a14222866.png)

**Comment by AMBudnik** [comment]
Hi @DhavalGPatel I made this little example code at http://jsfiddle.net/u096mwch/ for this issue
I used only css for `container` to pack it into `height: 200px; width: 400px;` and `overflow: scroll` like in your example.

I think that it could be other css settings that corresponds with autocomplete list.
In the `samples.css` you gave me I couldn't find the case of this misalignment, but it can be bounded with something else. 

You could try to change css settings by developer tools at Chrome and observe changes.

**Comment by DhavalGPatel** [comment]
Thank you very much for your help it worked for me..

Only on thing is left still that it displays two scrolls both side. Even it can be seen in your given fiddle demo. Can you please give me any suggestion regarding this..?

**Comment by AMBudnik** [comment]
I can see - at OSX it works perfectly but at Windows it shows double bottom scroll bar

![untitled](https://cloud.githubusercontent.com/assets/10757813/9934713/49f88bcc-5d53-11e5-8ced-35cea24bac39.png) 

I think this topic can help http://stackoverflow.com/questions/2758732/how-to-get-rid-of-the-double-scroll-bar-problem-when-using-an-iframe
