### ISSUE TITLE
Move Selection

### ISSUE THREAD

**Issue by lope** [handsontable/handsontable#282]
One of the basic features Excel or google docs provides is the ability to select a rectangle of cells, and then move the mouse to the edge of the selection, grab them and move them all to a different place on the grid.

Thats the only thing missing!
Otherwise its absolutely awesome.
Thank you

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
