### ISSUE TITLE
event afterSelectionEnd fires before mouse up when clicking and holding on col header

### ISSUE THREAD

**Issue by avilaton** [handsontable/handsontable#2820]
The event `afterSelectionEnd` fires before the user releases the mouse button when clicking and holding on a column header. After draging (while holding) over other column headers, and then releasing, the `afterSelectionEnd` event fires again.

**Comment by AMBudnik** [comment]
Confirmed. [Example](http://jsfiddle.net/kvfwbuvk/) to test this case

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1: http://jsfiddle.net/kvfwbuvk/1/

**Comment by AMBudnik** [comment]
Issue doesn't occur in version 0.30.1, demo: http://jsfiddle.net/handsoncode/z5vx4xLm/
Thanks for sharing @avilaton
