### ISSUE TITLE
setCellMeta() does not update cellProperties

### ISSUE THREAD

**Issue by hristod** [handsontable/handsontable#2823]
I'm setting the meta for each cell from an external object in the `cells:` function, but when I try to update some of the settings via the setCellMeta or setCellMetaObject, it just does not update meta. Also, the removeMeta does not work.

**Comment by AMBudnik** [comment]
Could you please provide a demo showing this example?

**Comment by hristod** [comment]
I found the problem, it had nothing to do with HOT :)

**Comment by AMBudnik** [comment]
Glad to heard that. Thanks for info.
