### ISSUE TITLE
Limit cell's dimentions regardless the content

### ISSUE THREAD

**Issue by morungos** [handsontable/handsontable#2824]
One of my users asked for rows to be clipped in height, but I can't seem to make that work. Any long text in a fixed-width column seems to force wrapping and increase the row height, sometimes even while scrolling (if the column is off screen).

Is there any way to allow people to resize the row height but still allowing wrapping to work in fixed-width columns, by clipping?

**Comment by AMBudnik** [comment]
Like in the example below (source: http://jsfiddle.net/zqps6tdz/1/) 
`colWidths` and `rowHeights` correspond only to those cells which content is shorter than typed dimentions. 

![zrzut ekranu 2015-09-21 o 09 50 24](https://cloud.githubusercontent.com/assets/10757813/9987257/6aa003d2-6046-11e5-876e-bf5d69a995cf.png)

You could use CSS to shorten this cell like here http://jsfiddle.net/0n4zsesa/ just add 

`.htCore td {
    white-space:nowrap
}`

result

![zrzut ekranu 2015-09-21 o 10 12 14](https://cloud.githubusercontent.com/assets/10757813/9987574/57f73df6-6049-11e5-8070-826303286bcf.png)

**Comment by morungos** [comment]
Sorry, should have been clearer: "allow people to resize" referred to the handles in row headers, not to developer CSS. I actually need people to have a (first example) type display (i.e., wrapped) while clipping at the bottom as in (second example). That's how Excel does it, and it's what my users have asked for. I just can't seem to make that happen.

**Comment by AMBudnik** [comment]
For clipping we currently only have `fixedRowsTop` but we'll bring fixing rows at bottom in Handsontable PRO. You can track changes at http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button
When it comes to resizing rows it can only be achieved till the cell's border hit the content, so the cell can't be smaller that it's content. If it's not what you have on your mind, please provide a Excel screenshot.

**Comment by morungos** [comment]
Thanks @AMBudnik. Here's an example from Excel. My users have cells with text that spans lines as in (1) -- although whether this is done with line breaks or not doesn't matter and wrapped text behaves just the same. They'd like to be able to collapse them as shown under (2), and then resize a row to show full text as in (3). The problem is users cannot do both (2) and (3), as the cells grow to full height as per (3). The only way to get (2) is to CSS with `white-space:nowrap` and an overflow as you suggested, but then (3) is impossible. 

![image](https://cloud.githubusercontent.com/assets/442090/10112433/19f2b0c2-63a9-11e5-97c4-eb0e4480ea4c.png)

**Comment by AMBudnik** [comment]
Thanks, now everything's clear. I guess you could try to build custom `contextMenu` that gives a choice to unable or disable `white-space:nowrap` ([about contextMenu](http://docs.handsontable.com/0.18.0/demo-context-menu.html))

**Comment by morungos** [comment]
Yes, that'd do something, but it's a bit hacky. I'll talk to the users and give them a choice, see if they have any ideas. 

Or I could wade in and see if it's fixable, as plain CSS can do the clipping with, e.g. `max-height: 200px; width: 100px; overflow: hidden; white-space: pre-line` -- something in the Handsontable context makes this not work.

**Comment by AMBudnik** [comment]
OK. I'm pretty curious what your users will say. Can you leave us feedback? Maybe it'll give us a little trigger to discuss this subject in the future.

**Comment by morungos** [comment]
Will do

**Comment by andrewleith** [comment]
An excel user would expect to be able to set the height of a row smaller or larger.  

Having rows go to the maximum height possible based on the tallest cell's content is very annoying when you have a couple of cells with large amounts of data.  It makes the table very heard to read and hard to use.

I think the row size handles should let a user set whatever height they choose.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by tympollack** [comment]
My users are also wanting the same.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
