### ISSUE TITLE
event afterOnCellMouseOver not firing when moving from cell to contiguous cell header 

### ISSUE THREAD

**Issue by avilaton** [handsontable/handsontable#2825]
The event `afterOnCellMouseOver` is not firing after the first time on move from a cell to a header. Steps to reproduce:
- move mouse over col A header, see event fire for (row:-1, col: 0),
- move into cell A1, see event fire for (row:0, col: 0),
- move back into col A header, see nothing happen.

**Comment by avilaton** [comment]
This is really hitting me so I'm trying to find out if I can help fix it. I see it probably boils down to this line
https://github.com/handsontable/handsontable/blob/master/src/3rdparty/walkontable/src/event.js#L126
where the var lastMouseOver is not what we expect it to be when the mouse moves from the header cell to an adjacent cell. Any ideas?

**Comment by swistach** [comment]
Works properly since version: 0.20.3
