### ISSUE TITLE
Paste and autofill formula

### ISSUE THREAD

**Issue by dnprock** [handsontable/handsontable#2826]
Current paste functionality only put in the exact value of copy. If I copy "=A2+B2" in C2 and paste to C3, the formula is still "=A2+B2". It should be autofill in this case and increment to "=A3+B3". This is how Google spreadsheet works.

**Comment by AMBudnik** [comment]
Thank you @dnprock for your improvement proposition. 

I will move this topic to https://github.com/handsontable/ruleJS which uses formulas. Exact issue is: https://github.com/handsontable/ruleJS/issues/6 so please track changes to https://github.com/handsontable/ruleJS/issues/6 and this one I'm closing.

**Comment by ludsoft** [comment]
Hi, I'm still having the same question and https://github.com/handsontable/ruleJS/issues/6 is raising a 404 as ruleJS has been archived. Would you have any pointer so that I can know if the update of the formula reference can be done for copy past as well as for Autofill?

**Comment by AMBudnik** [comment]
Hi @ludsoft 

RuleJS is no longer maintained. Can I ask you to share more details about your project (along with the chosen version of Handsontable) on emails? You can reach me at support@handsontable.com
