### ISSUE TITLE
Cannot include horizontal separators in custom context menu when passing list of strings

### ISSUE THREAD

**Issue by jlsalmon** [handsontable/handsontable#2827]
The [docs] (http://docs.handsontable.com/0.18.0/demo-context-menu.html) suggest that you can add  horizontal separators (`hsep1`, `hsep2`, `hsep3`) when customising the `contextMenu` with a list of strings. 

However, when trying this, instead of getting a horizontal separator I get the actual string `hsep1` as a context menu item. See [this fiddle](http://jsfiddle.net/vta6sjrm/) for a demo.

I know I could go for a fully custom config, but I don't want to redefine any behaviour and I'd prefer the shorter syntax.

Thanks in advance!

**Comment by budnix** [comment]
Hi, `hsep{\d+}` actually works as objects keys where value is '`---------`'. For arrays you can change this keys into '`---------`'. See [updated](http://jsfiddle.net/vta6sjrm/1/) demo.

**Comment by jlsalmon** [comment]
Perfect, thanks @budnix for the fast response!
