### ISSUE TITLE
Is it possible to group headers?

### ISSUE THREAD

**Issue by rmilesson** [handsontable/handsontable#2828]
I'm after something [like what Fixed Data Table does](https://facebook.github.io/fixed-data-table/example-column-groups.html).

We're in the process of checking out alternatives to Fixed Data Table and Handsontable seems to have the best performance and the Excel interface matches what our users expects but being able to use group headers are a must.

**Comment by AMBudnik** [comment]
Hi @rmilesson it will be a part of Handsontable PRO. You can track changes to PRO at http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button
