### ISSUE TITLE
Custom renderer needs access to the whole row data object

### ISSUE THREAD

**Issue by rmilesson** [handsontable/handsontable#2829]
This would be important to use cases where the developer needs to display a value from one column (a name for example), but needs to access another property (like an ID) to render differently in certain cases.

I can explain our use case;

We want to render a React component in a cell. The cell will show the name of the user and then fetch meta data about the user by ID to create a link to the users profile.

If someone could point me in the right direction I could add it add it myself and do a PR. I could not find where custom renderers are called upon :)

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
Hi. As we currently use Github Discussions to discuss new functionalities and changes, please refer to this topic using the new address.

I also encourage everyone interested in the subject to leave their comments.

Thanks!
