### ISSUE TITLE
Is custom renderers running on columns it should not run on?

### ISSUE THREAD

**Issue by rmilesson** [handsontable/handsontable#2830]
I was fiddling around a bit and something confused me. It seems like custom renderers are running for columns they're not assigned to.

See fiddle and check console output: http://jsfiddle.net/zma13ogr/

Something weird is going on, but I can't narrow it down. It seems like the prop-argument to the renderer changes quite a bit. But the value seems to stay almost the same (it changes type from string to number from time to time).

What's going on?

**Comment by AMBudnik** [comment]
Thank you @rmilesson it is a `prop` bug.

**Comment by rmilesson** [comment]
The type of the value changes as well. May I assume that's intended?

**Comment by jansiegel** [comment]
@rmilesson good catch, thanks for reporting! 

As for the value type changing - yes, it's intended ;) While rendering the cells, value type is not changed, however, when the renderer is called while rendering the *ghost table* (an invisible table used to determine the column widths in the auto column size plugin), all values are converted into strings to estimate their widths after rendering.

Hope that explained something :)

**Comment by rmilesson** [comment]
It does explain some things, though I don't agree with it. Data changing types should be nothing I should have to safeguard against. I provide the data, the data has it's type and that should not change, not for me as a consumer at least.

Though thanks for fixing this!
