### ISSUE TITLE
Different space between input element and dropdown list

### ISSUE THREAD

**Issue by vo-va** [handsontable/handsontable#2832]
Why Chrome and Firefox render drowdown list in different ways?

Firefox:
![screenshot from 2015-09-21 23 10 59](https://cloud.githubusercontent.com/assets/2452627/9999075/3467d720-60b6-11e5-9e20-275dd3133b32.png)

Chrome add some space between input element and dropwdown list
![screenshot from 2015-09-21 23 10 28](https://cloud.githubusercontent.com/assets/2452627/9999074/3466eb6c-60b6-11e5-8abf-e433d338e466.png)

Is this a feature or a bug?

**Comment by AMBudnik** [comment]
Hi, checking on Chrome, Firefox and Safari at OSX and Windows 7 - all have a space between dropdown list and it's cell. In Windows Firefox this space is maybe a 1px and in Firefox at mac there are 2-3px.

**Comment by vo-va** [comment]
So, this is not a bug, but just a different render behavior like for scrollbar? But why? I asking because dropdown list it is just a instance of Handosntable, not native browser element like input or checkbox. And also, I can't find in css or in inline styles any property what make this space, I mean margin or padding.

**Comment by nicolashenry** [comment]
The textarea has a "display: inline-block" style instead of "display: block" (why ?), so it displays the textarea aligned to the text baseline by default.

**Comment by mamapitufo** [comment]
This is a legitimate issue, the drop down is not correctly positioned. I see that the `display: inline-block` was added a couple of years ago in https://github.com/handsontable/handsontable/commit/1c409ca24b9a9eb07e55c1e4ed21f47ea55b2a08, is this still necessary? Setting it to `block` fixes the issue, as @nicolashenry stated.

**Comment by AMBudnik** [comment]
I'm leaving this issue to be checked, but as far as I'm concerned it should be the same for all browsers.

**Comment by swistach** [comment]
We have two options here:
1. Change `display: inline-block` to `display: block`
2. Setting `font-size: 0` on wrapper of inline elements

**Comment by AMBudnik** [comment]
Hi @vo-va sorry for keeping the issue opened for so long. I am happy to announce that it has been fixed it the latest version.
Can you check if it looks fine in your project as well?

**Comment by vo-va** [comment]
Hi @AMBudnik I'm glad that you fixed this. Checked in the demos, everything works fine. Thank you.

**Comment by AMBudnik** [comment]
Great! Thanks for a quick update @vo-va

**Comment by AMBudnik** [comment]
I couldn't replicate it @Fewthlix Both lists look the same and there's no free space between a cell and it's dropdown list.
I am using Chrome 69 and FF 62 on Windows 10
