### ISSUE TITLE
Multipledefined between Dojo Loader and Handsontable

### ISSUE THREAD

**Issue by pengbomuzzy** [handsontable/handsontable#2833]
As the pic tells, 
![image](https://cloud.githubusercontent.com/assets/6486720/10001350/571e7766-606f-11e5-8807-ea21a171489a.png)

If I use Dojo loader for the ArcGIS as well as handsontable, it happens, seems like Circle object is calling the Handsontable constructor...

Could you guys help me?
Appreciated!

**Comment by AMBudnik** [comment]
Hi, for questions that are not related to Handsontable bugs, please create a topic with a `handsontable` tag in [stackoverflow](https://stackoverflow.com/search?q=handsontable)
