### ISSUE TITLE
Bigger text in a cell not properly rendered?

### ISSUE THREAD

**Issue by klikstermkd** [handsontable/handsontable#2834]
Hi,

I use HOT in conjunction with a rich text cell editor. So if I make the size of the text bigger it does not properly render in the cell. 

![hot](https://cloud.githubusercontent.com/assets/520213/10046208/9baf9bdc-6207-11e5-9a9e-864c56c9279d.png)

**Comment by AMBudnik** [comment]
Thanks, I see what you mean.
You could try to change `rowHeights` if the `font-size` gets beyond what fits but the text is not aligned vertically.

![zrzut ekranu 2015-09-23 o 16 17 18](https://cloud.githubusercontent.com/assets/10757813/10047570/2024edb6-620f-11e5-871d-b5693d529c1e.png)

For Handsontable PRO we're preparing rich text editor.

**Comment by klikstermkd** [comment]
The problem here besides the height is regardless how much you change the height, the text is still fixed. The solution here is to apply a margin-top on the element inside the <td> element so that it will come lower in the cell. But I don't think this is a good solution. And I don't know if this is something that should be handled automatically by HOT or by our end.

**Comment by AMBudnik** [comment]
Replicable in 0.23.0, demo: http://jsfiddle.net/putechur/
Cells doesn't allow to use bigger letters (they do not expand).

**Comment by AMBudnik** [comment]
updated example: http://jsfiddle.net/7wtchpq8/

**Comment by AMBudnik** [comment]
Issue still present in 0.31.0

![image](https://cloud.githubusercontent.com/assets/10757813/23357868/fac3fd7e-fcdf-11e6-9dfe-53dc5f8ac6e4.png)

**Comment by AMBudnik** [comment]
The issue is fixed when we add `line-height` attribute ti the `.handsontable td` elements, like in the following demo http://jsfiddle.net/nzcLvoja/
