### ISSUE TITLE
Prevent selecting when sorting with `multiSelect: false`

### ISSUE THREAD

**Issue by JacobEvelyn** [handsontable/handsontable#2836]
When sorting a column with `multiSelect: false`, a single cell in that column becomes selected, which is somewhat weird and unexpected and in particular looks bad when the selected row is highlighted as in http://docs.handsontable.com/0.18.0/demo-highlighting-current.html. (Using `multiSelect: true` and `disableVisualSelection: "area"` doesn't work either as then every row is highlighted.) Preventing cell selection when sorting with `multiSelect: false` would be a great fix for this.

**Comment by AMBudnik** [comment]
You're right.

This is the example for highlighting with `multiSelect: true`(default) after sorting column `C'
http://jsfiddle.net/15hsuczx/
![zrzut ekranu 2015-09-23 o 22 22 04](https://cloud.githubusercontent.com/assets/10757813/10057656/b37b85fc-6241-11e5-8a3b-e2dad1ce68e9.png)

and below is the same demo with  `multiSelect: false` after sorting column `C'
![zrzut ekranu 2015-09-23 o 22 24 16](https://cloud.githubusercontent.com/assets/10757813/10057704/ee057282-6241-11e5-93fb-bea5ed53eff1.png)

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
This issue is outdated due to API changes.
