### ISSUE TITLE
multiple row/column selection by shift+clicking row/column header

### ISSUE THREAD

**Issue by artsince** [handsontable/handsontable#2837]
I like that I can select the entire row by clicking the row header. I also think it is very natural to select a range of successive rows by shift clicking another row header. (supported by Google spreadsheets)

I would appreciate it if you could let me know if there is a way to activate such a feature if it already exists. or if you could suggest a programmatic work around.

best

**Comment by AMBudnik** [comment]
Hi, it's the one of the features that you can vote for at http://feathub.com/handsontable/handsontable

**Comment by samsonkhisty** [comment]
@artsince 

I just implemented this in our own fork. You just need to add another condition for column and row in the [onCellMouseDown](https://github.com/handsontable/handsontable/blob/128f649a9fc4c4d370892168476239cd0d44b716/src/tableView.js#L299) method. 

I just wanted the shift+row click so I added this

    else if (event.shiftKey) {
          if (coords.row >= 0 && coords.col >= 0) {
            instance.selection.setRangeEnd(coords);
          } else if (coords.col < 0) {
            coords.col = instance.countCols() - 1
            instance.selection.setRangeEnd(coords);
          }
    }

Hope it helps
