### ISSUE TITLE
dropdown cell type and scrolling HOT

### ISSUE THREAD

**Issue by gillius** [handsontable/handsontable#2838]
I have not found any combination of configuration that allows dropdown cell types and scrolling HOT to work.

http://jsfiddle.net/h6cb3djx/
<img width="158" alt="zfwpv" src="https://cloud.githubusercontent.com/assets/1524332/10063785/761ae196-623f-11e5-8892-484d125e33dc.png">

The problem is that the dropdown is a div within the table, and scrolling requires some form of overflow (the docs says overflow: auto but the actual example code is using overflow:hidden). In either overflow case, the dropdown will not appear outside of the table, making dropdowns near the bottom completely unusable, and dropdowns on the right can cause extra scrollbars to appear.

**Comment by AMBudnik** [comment]
so as I assume you would like dropdown to appear at the top of the html structure? If so you can type `position: fixed` to `handsontableInputHolder` class. This solution (after some `top` and `left` retouches) would look like this

![zrzut ekranu 2015-09-25 o 13 54 57](https://cloud.githubusercontent.com/assets/10757813/10099810/77e1c18a-638d-11e5-8b52-7cd269ff0d7e.png)

 but it has it's disadventages, cause if no option is picked, after scroll this dropdown follows down the page.

![zrzut ekranu 2015-09-25 o 13 59 39](https://cloud.githubusercontent.com/assets/10757813/10099849/d1d60016-638d-11e5-8538-793b2573d714.png)

**Comment by gillius** [comment]
Thanks for a quick response.

I didn't realize there was any way at all to break out of an overflow such that an element shows outside of its containing element, but position: fixed does appear to do that. Considering that dropdowns are 100% unusable in current context as there is no way to see the dropdown (because clicking on the scrollbar blurs the control and hides it), fixed position is a plenty good enough compromise.

I do have issue that now left and top are wrong. You mentioned fixing it -- how do I get the proper top and left to be calculated?

**Comment by AMBudnik** [comment]
The easiest way is to use developer's tools

![zrzut ekranu 2015-09-28 o 11 44 48](https://cloud.githubusercontent.com/assets/10757813/10132395/86e40f12-65d6-11e5-8546-343180c07372.png)

`top: 74px` and `left:112px` seems to work fine

**Comment by gillius** [comment]
I'm sorry, I still don't get it. I can observe the top and left in dev console of course and modify them there to be right, but every time a dropdown is opened the coordinates are calculated by HOT somehow. It also depends on where the user has scrolled the page and HOT window. So somehow I have to configure HOT to generate the right coordinates or implement some hook or (hopefully not) patch HOT to do it. If you think I'm missing something and it's simpler than that, then can you fix it in the jsfiddle then it will be completely clear? I'm OK if the user scrolls after opening dropdown that it doesn't line up right if needed. Or, any other solution where dropdowns and scrollable HOT can be used at the same time.

**Comment by AMBudnik** [comment]
Hi @gillius after long investigation every solution I found wasn't good enough. Handsontable recalculates dropdown position and fixing dropdown causes misalignment on every step of the way, that's why unfortunately it can't be done with conventional methods.

You could try to search more at [SO](https://stackoverflow.com/search?q=handsontable) but without changing HOT's source code it could be realy tough.

**Comment by gillius** [comment]
I actually started with SO thinking that it was a problem with how I was setting up HOT: http://stackoverflow.com/questions/32593414/handsontable-dropdowns-hidden-in-overflowauto-div

Unfortunately, my team has invested a lot in integrating HOT and I haven't really seen a good alternative yet. So right now my options are dropping scrolling, losing fixed column headers, or updating the source code. I'll look to see if there is a way that I can put the absolute positioned dropdown on body, like what is done with Bootstrap tooltips.

**Comment by emanuallan** [comment]
Is there any update on this issue? I am having the exact same issue? Has a batter solution been made?

**Comment by pnowak** [comment]
Please @emanuallan follow response in one place in this issue - https://github.com/handsontable/handsontable/issues/7069#issuecomment-662404024
