### ISSUE TITLE
error use handsontable from npm with reactjs

### ISSUE THREAD

**Issue by xblue55** [handsontable/handsontable#2839]
Hi. I build application used handsontable npm with reactjs and node version v0.12.2 failure

ERROR in ./~/handsontable/src/browser.js
Module parse failed: /Volumes/Data/Web/5giay/lase/fivevn/frontend/node_modules/handsontable/src/browser.js Line 16: Unexpected token
You may need an appropriate loader to handle this file type.
| Handsontable.buildDate = buildDate;
| 
| import './shims/classes';
| import 'es6collections';
| 
 @ ./app/pages/product-result.jsx 33:20-43

Please help me. Thank you handsontable.

**Comment by AMBudnik** [comment]
Hi @xblue55 
How is your progress in this matter?
I hope that you already solved this one out but if not, please leave a comment and we'll reopen this issue.
