### ISSUE TITLE
Type Error: samples.forEach is not a function

### ISSUE THREAD

**Issue by onia** [handsontable/handsontable#2840]
Since Firefox 24 ESR does not support Map.prototype.forEach(), it will throw above error. Handsontable does not support Firefox 24 ESR?

**Comment by onia** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser compatibility

**Comment by jansiegel** [comment]
@onia, it seems like you might be right. Although, Firefox 24 was released in 2013, if I'm not mistaken. 
Maybe you can consider an update, as there are more recent ESR versions?

**Comment by budnix** [comment]
We support Firefox since v25. I'll close this issue.
