### ISSUE TITLE
Use without pikaday

### ISSUE THREAD

**Issue by Hacktivista** [handsontable/handsontable#2841]
In README file it is presumed that I can use the bare distribution without Pikaday, ```It may also require Pikaday and moment.js, if you're using the Datepicker for date input``` but I get the following error in console ```Error: Cannot find module 'pikaday'``` when I do include the handsontable.js file, inclusively if I don't use handsontable at all.

**Comment by AMBudnik** [comment]
Could you please prepare a demo code which causes this error to appear?

**Comment by budnix** [comment]
I confirmed that handsontable must have Pikaday and moment.js included as a dependency, included externally (as separate script tag) or internally (as handsontable.full.js).
