### ISSUE TITLE
During column resizing outside table the pointer position stays outide table

### ISSUE THREAD

**Issue by yuvaraj1391** [handsontable/handsontable#2842]
![columnresize](https://cloud.githubusercontent.com/assets/14774344/10093580/129c05d0-6372-11e5-8c39-1f59544286f4.png)
when a column gets resized outside table its pointer position stays at the same point where it was left for resizing.

**Comment by AMBudnik** [comment]
I couldn't reproduceit with Win7 and OSX with major browsers. Please provide your OS/Browser information (versions).

**Comment by yuvaraj1391** [comment]
I am using windows 7 and Firefox 30.0 and chrome Version 45.0

**Comment by yuvaraj1391** [comment]
![untitled recording 2](https://cloud.githubusercontent.com/assets/14774344/10098927/c92fe00c-63a2-11e5-92eb-89bfe907a040.gif)

**Comment by yuvaraj1391** [comment]
Please find the demo Its the latest version of handsontable

**Comment by AMBudnik** [comment]
OK, thank you I can see what you mean. I confirm it also at the OSX

**Comment by AMBudnik** [comment]
Still present.

**Comment by AMBudnik** [comment]
Still replicable for columns and rows.

**Comment by yuvaraj1391** [comment]
Yes still replicable

On Mon, Feb 27, 2017 at 3:50 PM, Aleksandra Budnik <notifications@github.com

**Comment by AMBudnik** [comment]
Issue is still replicable in 0.34.0/1.13.0 at https://docs.handsontable.com/pro/1.13.0/demo-resizing.html

**Comment by AMBudnik** [comment]
The issue is still replicable. (v0.35.0)

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by wojciechczerniak** [comment]
Duplicate of #3346
