### ISSUE TITLE
wrong @charset directive in full CSS

### ISSUE THREAD

**Issue by splitbrain** [handsontable/handsontable#2843]
See https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.css#L1168 there's a charset directive in the middle of the file.

According to http://www.w3.org/International/questions/qa-css-charset
> Only one @charset byte sequence may appear in an external style sheet and it must appear at the very start of the document. It must not be preceded by any characters, not even comments.

This is probably a problem within the build process. However the default charset for CSS ist UTF-8 anyway, so the charset directive could be skipped alltogether.

**Comment by AMBudnik** [comment]
I'm closing this issue as #3406 is highly related. If you would have any suggestions please write them there.

ps. thanks for your effort.
