### ISSUE TITLE
Context menu is under the table

### ISSUE THREAD

**Issue by pengbomuzzy** [handsontable/handsontable#2844]
![image](https://cloud.githubusercontent.com/assets/6486720/10138388/4060e038-65cc-11e5-9c10-e8a4d810e14f.png)

When I right click the table, the context menu is under the table... How could I solve that? Thanks!

**Comment by AMBudnik** [comment]
It's not the behavior I got with our simplier [demo](http://jsfiddle.net/ar8uhxy1/) (with 0.18.0). Could you prepare a demo where this issue can be reproducible?

Thanks in advance.

**Comment by pengbomuzzy** [comment]
Hi Aleksandra,

I solved the problem. However, I noticed that when I use 'undo' and 'redo',
 it does not trigger the 'afterchange', here is my snippet of code:

[image: Inline image 2]

Why would that happen?

Thanks!

**Comment by pengbomuzzy** [comment]
I just solved this by increasing the 'z-index' of the htContextMenu (in .css file) to put the menu on the top...

**Comment by AMBudnik** [comment]
Great, glad you solved that out! 

When it comes to `undo` unfortunately I can't see the image.
Here's a little [demo](http://jsfiddle.net/j015teL6/) where tested few examples of behavior that can trigger `afterChange` at they seems to work fine. Although we have few issues related to `undo`, maybe it is one of them?

**Comment by pengbomuzzy** [comment]
Hi Alex,

I am so glad you are caring about my question. Attached is my code snippet
to achieve "undo" function. I have noticed that "edit" and "paste" works
very well but "undo" and "redo" does not. I am wondering why..

Thanks!
Bo Peng

On Mon, Sep 28, 2015 at 3:26 PM, Aleksandra Budnik <notifications@github.com

**Comment by AMBudnik** [comment]
There are few things that curretly does not trigger `afterChange` like insert/remove row/column and `undo`/`redo` for that actions also.

When it comes to `edit` and `paste` I tried it also and it worked fine with `undo` and `redo`. 
Could you please specify with action causes `afterChange` not to appear and it's related with 'edit' or 'paste' change?

**Comment by pengbomuzzy** [comment]
Hi Alek,

Yes, the implementation I did was removing one whole column and undo it,
then, it does not trigger the afterchange... So, any updates are able to
solve this problem or the team is trying to work on it?

Best,
Bo Peng

**Comment by AMBudnik** [comment]
We actually have a pull request for that issue but it has some parts we have to reconsider so as far as we will achieve our priorities, we're definitely going back to that subject.

**Comment by pengbomuzzy** [comment]
Hi Aleks,

Thanks for the effort. I found that handsontable is a very good tool that I
am using. However, I think you guys could fix these little bugs to make it
better. Actually, I am a big fan of handson.

Thanks!
Bo Peng

**Comment by pengbomuzzy** [comment]
Hi Aleks,

How is everything going? I am writing to know whether you guys figured out
the undo/redo things or not? Sounds like that you guys are in HandsonCode,
which deals with handsontable, is that correct?

Thanks!
Bo Peng

**Comment by AMBudnik** [comment]
Thanks. We're currently into Handsontable PRO which is the top priority with a short deadline.
Handsontable is our main project and yes, we're Handsoncode.

**Comment by pengbomuzzy** [comment]
Ok, then, is this Handsontable Pro the 0.19.0v?

On Thu, Oct 15, 2015 at 5:10 PM, Aleksandra Budnik <notifications@github.com

**Comment by pengbomuzzy** [comment]
Oh..Seems like I misunderstood what you mean.. The handsontable pro is
another project different from handsontable 0.19, 0.18, 0.17 ... What I am
concerned is could we get perfect undo-redo stuff from the new Handsontable
Pro?

Thanks!

**Comment by AMBudnik** [comment]
Handsontable and Handsontable PRO are indeeed two separate projects. 

The to-do list for Handsontable PRO can be found [here](http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button) and you can vote for other ideas/features [here](http://feathub.com/handsontable/handsontable)
