### ISSUE TITLE
Constrain width but not height of table

### ISSUE THREAD

**Issue by mlms13** [handsontable/handsontable#2845]
I'm wondering if it's possible to limit the width of a handsontable, and scroll horizontally, but to also allow the height to be flexible.

Here is an example of my attempt (which I shamelessly hijacked from someone else's unrelated example). http://jsfiddle.net/29o6tsjL/2/

The rendered output looks something like this:

![screen shot 2015-09-28 at 3 43 44 pm](https://cloud.githubusercontent.com/assets/1105543/10149619/0f3415ee-65f8-11e5-8890-426b46e653a0.png)

On the element that is targeted by handsontable, I've set the following styles:

```css
#editorTable {
  min-height: 200px;
  width: 200px;
  overflow-x: auto;
}
```

`min-height` is only in there because if I leave it out, the table doesn't render at all. If I let overflow default to `visible`, I don't get either scrollbar, and I really do want to scroll horizontally. I assumed that `overflow-x` would allow me to control the scrollbar only for the x-axis, but it seems like this causes handsontable to also set a fixed height for the y-axis and enable scrolling there as well.

Is it possible to keep the height flexible if I scroll horizontally?

**Comment by AMBudnik** [comment]
I packed `example1` div (which is my HOT container) to another div with css below at I assume this will present desired look

![zrzut ekranu 2015-09-29 o 13 54 51](https://cloud.githubusercontent.com/assets/10757813/10163263/f308853e-66b1-11e5-9d60-e80e2a496b38.png)

**Comment by mlms13** [comment]
Awesome, that was indeed exactly what I was looking for! However, I have to say it's a bit weird that:

- height seems to be required for the table to show up at all, and
- setting `overflow-x` causes vertical scrollbars

**Comment by AMBudnik** [comment]
It's on our to-do list to simplify it a little bit and add more flexibility to HOT, so keep tracking our updates.
