### ISSUE TITLE
Different behavior autocompleteEditor with breakpoint and without

### ISSUE THREAD

**Issue by vo-va** [handsontable/handsontable#2846]
When  key pressed in cell with type `autocomplete` symbol is appear in cell, but if breakpoint set at `6391` line in handsontable.full.js and after these steps:

1. press key cell.
2. stop at breakpoint
3. continue program, 

symbol will not appear in cell.

![screenshot from 2015-09-29 12 13 49](https://cloud.githubusercontent.com/assets/2452627/10157032/42d580b2-66a8-11e5-80cb-1fea67c8c6ab.png)

Why this is happening?

**Comment by AMBudnik** [comment]
Hi @vo-va 

I'm not sure what we would like to achieve here. Could you please check it is still occurs in v0.24.1? I have different code at `6391`
