### ISSUE TITLE
after change did not fire consistently

### ISSUE THREAD

**Issue by chowkh** [handsontable/handsontable#2849]
Please visit
privatedemo8.test.es2cloud.com/web3
Login id : root
Password : root

The issue : Inconsistent behavior. The ajax call for data source is not refreshed when there is a change in the value

Follow the following sequence closely.
1. Go to Supplier>Invoice Template>Purchase Invoice. Click on Create Purchase Invoice
2. Click on Row 1 on Account column. Type 5 then 0 and 0 and 0 and finally 0. (50000 in full). Notice that the drop down list do not change.
3. Then remove the 50000 value in Account Row 1
4. Move the mouse to Code Row 1. Hit Enter. Then hit Enter again
5. It will move the Account column. Then type 5 and then 0 and 0 and so on. You would notice that the drop down list will be narrowed down.

Observation: afterchange event was not called when first editing the account column.
Thank you

**Comment by AMBudnik** [comment]
Hi @chowkh if you still face the same issues please create a demo (preferably in JSFiddle/JSBin/CodePen).

**Comment by chowkh** [comment]
Yes, I am still facing the issue.
This happens only when I call deselectCell from afterSelection. If I call deselectCell from outside, I do not have this problem.
My application code is complex and large and time consuming for me to replicate it in the JSFiddle.
I have left some features out that call deselectcell from afterselection and I do not have this issue at the moment.

**Comment by AMBudnik** [comment]
OK, so I will close this issue but if you would like to come back to this with a demo issue gets reopened.
