### ISSUE TITLE
How to add column dynamically if dataschema is in object form ?

### ISSUE THREAD

**Issue by parthaaptuz** [handsontable/handsontable#2851]
It is saying that "Error: Cannot create new column. When data source in an object, you can only have as much columns as defined in first data row, data schema or in the 'columns' setting.If you want to be able to add new columns, you have to use array datasource."

Is there any alternative for this ?

dataSchema: {
                          Name: {'S':null},
                          first_name: {'S':null}, 
                          last_name:{'S':null}, 
                          mobile_no: {'S':null}, 
                          interests: {'S':null},
                        },
            colHeaders: ['Username', 'First Name', 'Last Name', 'Mobile No', 'Interests'],
            columns: [
              {data: 'Name.S'},
              {data: 'first_name.S'},
              {data: 'last_name.S'},
              {data: 'mobile_no.S'},
              {data: 'interests.S'}
            ],

The above is part of the code...

**Comment by AMBudnik** [comment]
Could you please create a full demo with [JSFiddle](http://jsfiddle.net/api/post/library/pure/) or [JSBin](http://jsbin.com/?html,js,output)
It would be much easier to figure out what's causing errors.

**Comment by naushadkm** [comment]
Please have a look in this Plunker Demo: 
http://plnkr.co/edit/g5CLwxMGHvdVBGPdU1ed?p=preview

Even if the context menu true. It shows disabled for the Object data source.

**Comment by parthaaptuz** [comment]
Hey, 

My code is like this...
http://pastebin.com/BBVw6bJe

**Comment by parthaaptuz** [comment]
If you call the addColumn then it is saying that 
"Cannot create new column. When data source in an object, you can only have as much columns as defined in first data row, data schema or in the 'columns' setting.If you want to be able to add new columns, you have to use array datasource."

**Comment by AMBudnik** [comment]
There are actually few things that has be be changed. Here's the example http://jsfiddle.net/96j6r9mz/
If this was not what you wanted to achieve please let me know.
