### ISSUE TITLE
How to get real column width before render?

### ISSUE THREAD

**Issue by Xozin** [handsontable/handsontable#2852]
Hello. 
I wanna get information about width of columns before it will be rendered. (Actually i need an opportunity to detect will at rendered table be a horizontal scroll or not)

**Comment by AMBudnik** [comment]
Hi @Xozin 
You can access column's width before table gets rendered.

As I was informed by on of our developers you'll need to use:
`instance.getPlugin(‚autoColumnSize’).calculateColumnsWidth()`
and then
`instance.getPlugin(‚autoColumnSize’).getColumnWidth(2)`

**Comment by cgatesman** [comment]
This didn't work for me.  I'm trying to get the all actual column widths within an `afterColumnResize`.  For example getting all actual proportional sized columns when resizing a column in a `stretchH='all'` table.  Is there a way to do this?

**Comment by cgatesman** [comment]
I see my problem may be related to https://github.com/handsontable/handsontable/issues/2090

**Comment by AMBudnik** [comment]
We will get back to this issue after #2090 gets updated.
