### ISSUE TITLE
Copy/Paste ZeroClipboard context menu not showing [Custom Context Menu]

### ISSUE THREAD

**Issue by kameelyan** [handsontable/handsontable#2853]
contextMenuCopyPaste: {
            swfPath: "/swf/ZeroClipboard.swf"
        },
        contextMenu: {
            callback: function (key, options) {
            },
            items: {
                "hsep0": "---------",
                "row_above": {},
                "row_below": {},
                "hsep1": "---------",
                "col_left": {},
                "col_right": {},
                "hsep2": "---------",
                "remove_row": {},
                "remove_col": {},
                "hsep3": "---------",
                "undo": {},
                "redo": {},
                "make_read_only": {},
                "alignment": {},
                "hsep4": "---------",
                "mergeCells": {},

I am using the above code in my handsontable settings, but the copy/paste context menu items are not being added. I looked into the .js file and saw the key values "copy" and "paste". I tried adding them to my custom context menu, but the labels come back as "undefined" and the plugin isn't working.

I was using 0.16 and this was working fine (with "copy": {}, "paste":{} in my menu), but now that I've upgraded to 0.18, it's not working.

Any ideas?

**Comment by blacksmoke26** [comment]
I also tried by triggering Copy/Paste manually it doesn't work anymore.

**Comment by kameelyan** [comment]
Any word on this?

**Comment by joaoricardorm** [comment]
Same problem here.

**Comment by casmith** [comment]
Using the following works for me to make copy work: 

'copy': {name: 'Copy'},

Doing the same with paste does not work. I am on 0.19.0. Any hints?

**Comment by kameelyan** [comment]
So I've been able to manually update the context menu matching what's in your .js file:

    "copy": {name: "Copy"},
        "paste": {
            name: 'Paste',
            callback: function () {
                  this.copyPaste.triggerPaste();
             }
      },

From there, I started adding console.logs into your .js file to see where it was failing. The function "onAfterContextMenuShow" is properly firing, but I believe there's some type of error with the zeroClipboardInstance setting when using a custom context menu. I can't figure out why, but that's one step closer I think.

**Comment by kameelyan** [comment]
I don't think the copy/paste is working at all in the latest version. if you go to the demo page:
http://docs.handsontable.com/0.20.2/demo-context-menu.html#page-copy-paste

It works fine. But if you click "Edit in jsFiddle" and then try and use it, it fails.
http://jsfiddle.net/kdyt9a5x/

**Comment by kameelyan** [comment]
In order to debug, I went ahead and stopped using the handsontable.full.js file, and instead included the files in the following order:
1) moment.js
2) pikaday.js
3) ZeroClipboard.js
4) handsontable.js

After splitting out the files, everything is working fine for me, including using a custom context menu with the following values:

                "copy": {name: "Copy"},
                "paste": {
                    name: 'Paste',
                    callback: function () {
                        this.copyPaste.triggerPaste();
                    }
                },

**Comment by AMBudnik** [comment]
Hi. Can you confirm that it is working fine in 0.23.0? If not, please let me know .

**Comment by kameelyan** [comment]
I don't believe it is working when you use the full.js file.
http://jsfiddle.net/kdyt9a5x/1/

**Comment by AMBudnik** [comment]
Thanks for feedback @kameelyan
