### ISSUE TITLE
Editing a cell with large text in it.

### ISSUE THREAD

**Issue by klikstermkd** [handsontable/handsontable#2855]
If I write large text in a cell, and I try to edit it, the editor misbehaves, i.e. the vertical scrollbar disappears and the text hides somewhere. Here're screenshots of this use case:

Large text in the cell:

![1](https://cloud.githubusercontent.com/assets/520213/10218187/30415f1e-6835-11e5-9497-183d829f2f1b.png)

And here's the after affect when double clicking the cell to edit it:

![2](https://cloud.githubusercontent.com/assets/520213/10218203/4ba51494-6835-11e5-835d-e2e52a6c6286.png)

**Comment by AMBudnik** [comment]
Could you please prepare a demo for this case? I made a [demo](http://jsfiddle.net/7obquafs/) but I don't experience the same issues. 
Text can seem to be gone when there is a lot of text and you have very narrow `colWidths`.

**Comment by klikstermkd** [comment]
Try it on the main HOT page http://handsontable.com/

**Comment by klikstermkd** [comment]
Also, here's a demo http://jsfiddle.net/6poh16kp/

**Comment by klikstermkd** [comment]
So as far as I can see, the issue happens if you set width and height of the container and overflow to hidden to show the scrollbars.

**Comment by AMBudnik** [comment]
Confirmed, thanks @klikstermkd scrolling seems to be impossible and cursor is not visible

![zrzut ekranu 2015-10-01 o 15 16 24](https://cloud.githubusercontent.com/assets/10757813/10221569/8212750c-684f-11e5-9b72-3e0aa1b4219a.png)
