### ISSUE TITLE
Use sortOrder instead of sortColumn to check if table is sorted in documentation

### ISSUE THREAD

**Issue by strickc** [handsontable/handsontable#2856]
In the documentation for Sorting Data (http://docs.handsontable.com/0.18.0/demo-sorting-data.html) it states:
>To check whether a table has been sorted you can check the sortColumn property. If table instance has this property defined then it has been sorted. The value of sortColumn is the index of a column by which the table has been sorted. Additionally, you can check sorting order using sortOrder property. If sortOrder is true, then the order is ascending, otherwise, the order is descending.

and also supplies an example function ```isSorted``` that checks if this property is undefined.  However, if a column has been sorted in the past and is returned to unsorted by the user, the ```sortColumn``` property will remain set, leading to a false positive for the ```isSorted``` function.  

The solution is instead to use the sortOrder property to check if the table is currently sorted.  This can be seen on the following jsFiddle: https://jsfiddle.net/3jk8g589/

The documentation should be updated to read:
>To check whether a table has been sorted you can check the sortOrder property.  If sortOrder is true, then the order is ascending, if false, the order is descending, and if undefined, the table is not sorted.  Additionally, you can check the column last sorted using the sortColumn property.
A simple function, which checks whether the table has been sorted could look like this:
```function isSorted(hotInstance) {
  return hotInstance.sortingEnabled && typeof hotInstance.sortOrder !== 'undefined';
}```

**Comment by AMBudnik** [comment]
Thank you @strickc it's a good idea. I think it can be helpful. I added it to our [docs issue board](https://github.com/handsontable/docs/issues/19) 

This issue will be closed so please track changes to https://github.com/handsontable/docs/issues/19 for further info.
