### ISSUE TITLE
issue with formula not evaluated

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#2857]
hello,
we have an evaluation problem for a formula.
if seems to be related to the scroll position.
i try to explain step by step.
http://jsfiddle.net/mod495Lm/

![image1](https://cloud.githubusercontent.com/assets/11042160/10246934/949b5cc2-6915-11e5-8d24-2c323ef37e5b.png)

1) Scroll to the right, we have
![image2](https://cloud.githubusercontent.com/assets/11042160/10246955/c21ef65e-6915-11e5-95c1-6d3403ec7884.png)
2) scroll to the bottom, we have
![image3](https://cloud.githubusercontent.com/assets/11042160/10246978/eaaab978-6915-11e5-9868-4e9f900de258.png)

In Z-43, i have the formula =B43 * 2 and not the result.

3)If i scroll to the left like
![image4](https://cloud.githubusercontent.com/assets/11042160/10247010/1517cff2-6916-11e5-89d0-538cdfed1f63.png)

4)And scroll again to the right, i have the correct result

![image5](https://cloud.githubusercontent.com/assets/11042160/10247034/37fb5caa-6916-11e5-9848-d0920754a297.png)

any help would be appreciate, we have a customer that goes to production in one week.

best regards

 jean marc

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 does it still occur?

**Comment by jeanmarc78** [comment]
hello ,
yes it still occurs.

jm

**Comment by AMBudnik** [comment]
@jeanmarc78 thanks for feedback,
Could you please guide what we have here? This example from demo looks different than one on your screens?

**Comment by jeanmarc78** [comment]
the problem is the fiddle was based on the older handsontable web site with the "personal finance" example and there are now maybie some link broken

**Comment by AMBudnik** [comment]
OK, I see. Is there another way we can check this issue?

**Comment by jeanmarc78** [comment]
hello
do you have a primary example with handsontable.formula.js and ruleJS.all.full.js ?


Jean Marc

**Comment by jeanmarc78** [comment]
i create a new demo
https://jsfiddle.net/jeanmarc/76z48m98/4/

**Comment by AMBudnik** [comment]
Thanks for sharing demo @jeanmarc78 
I added `renderAllRows: true` and it seams it does the work: https://jsfiddle.net/76z48m98/5/
Can you confirm?

**Comment by jeanmarc78** [comment]
Hi alexandra ,
yes i confirm the good behavior , but when i have more than 1000 rows, i have the console error log
Security brake: Too much TRs. Please define height for your table, which will enforce scrollbars.renderRows @ handsontable.full.js:3509

regards
jean marc

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 please check [this list of issue](https://github.com/handsontable/handsontable/search?q=Too+much+TRs&state=open&type=Issues&utf8=%E2%9C%93) is it related to one of them?

**Comment by jeanmarc78** [comment]
hello,
i think exactly the same https://github.com/handsontable/handsontable/issues/3036

regards
jean marc

**Comment by AMBudnik** [comment]
OK, good to know. Thanks for feedback @jeanmarc78
