### ISSUE TITLE
jQuery contextMenu API not working expect disabled, callback

### ISSUE THREAD

**Issue by blacksmoke26** [handsontable/handsontable#2858]
is it bug or what? jQuery contextMenu API on that page http://swisnl.github.io/jQuery-contextMenu/docs.html is not working for me. Maybe some sort of bug or written the following line by mistake:

http://docs.handsontable.com/0.15.0/demo-context-menu.html

**Context menu with fully custom configuration**

For greatest configurability, you use contextMenu option as a configuration object as described in jQuery contextMenu documentation.

**Comment by AChusuei** [comment]
Same, I can't get the show and hide events to trigger.

**Comment by AMBudnik** [comment]
Hi @blacksmoke26 can you confirm that now it's working as expected in 0.23.0?

**Comment by AMBudnik** [comment]
Closed till and author's reply or new comment.
