### ISSUE TITLE
Infinite horizontal lazy table

### ISSUE THREAD

**Issue by bledari** [handsontable/handsontable#2859]
Don't now if you provide vertical lazy scroll.

What about horizontal? 

Is it supported?

If not how much time and effort do you need to provide this feature?

Thanks!

**Comment by AMBudnik** [comment]
Unfortunately HOT does not provide this functionality yet. Here's the simpliest example how can you achieve it https://github.com/handsontable/handsontable/issues/2784 but it's rather workaround than solution.

We have an infinite scroll on our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests) and [here](http://feathub.com/handsontable/handsontable) you can vote for this feature.
