### ISSUE TITLE
Programmatically triggering TAB press on Handsontable

### ISSUE THREAD

**Issue by stevemck** [handsontable/handsontable#2861]
I'm trying to get test coverage on my custom implementation of tabMoves() but I can't seem to trigger a TAB key press programmatically.

I have tried the following without luck

    var e = jQuery.Event("keydown");
	e.which = 9;
	$(".handsontableInputHolder").trigger(e);

AND
    Handsontable.hooks.run(component.hot, 'tabMoves');

Please help,
Thanks

**Comment by AMBudnik** [comment]
You can try [this code](http://jsfiddle.net/4zcgyw7u/). Hope it helps.
