### ISSUE TITLE
Column Hide/Show in contextmenu

### ISSUE THREAD

**Issue by crazyjavatricks** [handsontable/handsontable#2862]
Hi guys,

Is there any way to use a hide/show column feature in handsontable using context menu.
if handsontable have already a feature like this , please let me know it. I have a requirement for the same. hope you guys will help me to solve this.

Thanks,

**Comment by AMBudnik** [comment]
Hi @crazyjavatricks show/hide columns will be the part of Handsontable PRO ([information source](http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button))

**Comment by crazyjavatricks** [comment]
thanks AMBudnik , waiting for the Handsontable PRO release.
