### ISSUE TITLE
Numeral-js source included in final build, overwrites global

### ISSUE THREAD

**Issue by visby** [handsontable/handsontable#2863]
It seems that the [numeraljs](https://github.com/adamwdraper/Numeral-js) source gets included in the final build of handsontable, both in [handsontable.js](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.js), as well as [handsontable.full.js](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js).

Moreover it seems to overwrite the global **numeral** reference, even if it's already defined.

**Comment by AMBudnik** [comment]
Please take a look at this issue: https://github.com/handsontable/handsontable/issues/2253

**Comment by alexanderby** [comment]
I need to add a custom language to numeral.js but seems like bundled numeral.js version overrides installed one.

**Comment by visby** [comment]
Yes, it's very frustrating. Also, I'm not sure how the linked issue #2253 explains why handsontable needs to override numeraljs with its own embedded version.

**Comment by AMBudnik** [comment]
@alexanderby @visby 
as we've changed the structure of handling numbers (Numeral > Numbro) you should not get the same issue.
