### ISSUE TITLE
Examples for new features of 0.19.0

### ISSUE THREAD

**Issue by jromero-onclick** [handsontable/handsontable#2864]
We would like to see some examples of the new features of 0.19.0:

"Added new Handsontable Pro features, such as Fixed Rows Bottom, a Column Summary Plugin (providing simple calculations and summary functions), Nested Headers Plugin (allows to create a multiple column headers) and Collapsible Columns Plugin (allows to collapse headers)."

Thank you!

**Comment by AMBudnik** [comment]
Hi @jromero-onclick they're a part of Handsontable PRO which is not released as a full project yet. All needed examples will be avaiable as soon as we'll reveal the PRO. You can sign up to [our newsletter](http://handsontable.com/sign-up.html) to get notified when it's ready.

**Comment by jromero-onclick** [comment]
Ok good job guys!
