### ISSUE TITLE
Invalid cell does not move with row when inserting row

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#2865]
If you have an invalid cell, then insert a row above it, the RED invalid background does not move down with the row.

You can reproduce this with this JSFiddle example: http://jsfiddle.net/cgatesman/cvc29ohj/

1. Change one of the number cells to a letter (e.g. `A`).  It will become invalid (RED).
2. Right click on that row, and select insert row above.  The RED cell will be on the newly inserted row instead of the invalid field.

**Comment by AMBudnik** [comment]
Thank you @cgatesman but we have the same issue at https://github.com/handsontable/handsontable/issues/2114 please track changes to that one
