### ISSUE TITLE
Handsontable homepage mislabel

### ISSUE THREAD

**Issue by zekedroid** [handsontable/handsontable#2866]
Looking at the button "Load 100 000 cells", I realized that when you click it really only loads 10 000.

**Comment by krzysztofspilka** [comment]
Hi Zeke, it's 10 000 rows multiplied by 10 columns. That's why we wrote "10 000 cells" not "rows".

**Comment by zekedroid** [comment]
Haha nice, and here I was all focused on rows for some optimization reasons. Sorry about that, it's great as is.
