### ISSUE TITLE
Resize automatically column/row header

### ISSUE THREAD

**Issue by LoveOfLava** [handsontable/handsontable#2867]
Hi,

I have made an modification in order to the user can change the header name with select who appears on a modal.

The header didn't automatically resize when the text are too long.
There is an method to do that ?

Regards

**Comment by LoveOfLava** [comment]
Hi,

After 
        hot.updateSettings({
            rowHeaders: headers
        });

I call the render method on hot and it seems to work.
There is another solution ?

Regards

**Comment by AMBudnik** [comment]
As far as I get the idea it's not the same issue as you added [here](https://github.com/handsontable/handsontable/issues/2868)?

**Comment by LoveOfLava** [comment]
Hi,

It the end it's the same issue. When I update the rowHeaders, their width aren't automatically resize. I need to call the render method like hot.render()

Regards

**Comment by AMBudnik** [comment]
OK, so please write down anything you think that might be related to this issue at https://github.com/handsontable/handsontable/issues/2868 

As long as this issue is about the same case as that one it has to be closed.
