### ISSUE TITLE
Can't resize the row header

### ISSUE THREAD

**Issue by LoveOfLava** [handsontable/handsontable#2868]
Hi,

I cannot resize the row header. The content is hidden

![image](https://cloud.githubusercontent.com/assets/15012754/10343393/e7581cf0-6d1d-11e5-944c-7a10596c2337.png)

Regards

**Comment by AMBudnik** [comment]
Thank you @LoveOfLava Confirmed

**Comment by LoveOfLava** [comment]
HI,

Thank you. Did you know when the bug will be fix ?

Regards

**Comment by AMBudnik** [comment]
I really would like to give you date but now our priority is to release Handsontable PRO and we're working very hard to reveal it in November. 

Our programmers are familiar with this bug so as soon as they'll get to the part of code that's responsible for that issue we'll get back to this case.

**Comment by LoveOfLava** [comment]
Hi,


Thank you for your answer.

I'm impatient to get the release of handsontable PRO.


I see on roadmap

  1.  Better formula support

There is already handsontable-ruleJS but you want to include formula on handsontable core ?

Regards

________________________________
De : Aleksandra Budnik <notifications@github.com>
Envoyé : jeudi 8 octobre 2015 12:14
À : handsontable/handsontable
Cc : Lucas Galasso
Objet : Re: [handsontable] Can't resize the row header (#2868)


I really would like to give you date but now our priority is to release Handsontable PRO and we're working very hard to reveal it in November.

Our programmers are familiar with this bug so as soon as they'll get to the part of code that's responsible for that issue we'll get back to this case.

-

**Comment by AMBudnik** [comment]
It a wide subject right now, but we want HOT to be able to manage formulas.

**Comment by jongunter** [comment]
I second this issue for being fixed. Also, it would be really nice if row headers could respond to the `stretchH` option.  Then, the row heading column would spread equally across the table with the rest of the columns.

**Comment by jongunter** [comment]
Is there a CSS-based workaround here to re-size the header? I can't seem to get it to work. Extra points for a JS Fiddle.

**Comment by DHoffm** [comment]
I thought the question was about resizing. What I need is to be able to manually resize the header (like normal rows). Because the labels differ in length and its not sure on the first start what the perfect width should be. So setting a fixed width via "rowHeaderWidth" isn't the perfect solution.

**Comment by AMBudnik** [comment]
@DHoffm I added you idea here: https://github.com/handsontable/handsontable/issues/3327
If you would have any other questions/suggestions or tips relates to that subject please comment at https://github.com/handsontable/handsontable/issues/3327

**Comment by mchilicki** [comment]
For anyone who is still struggling with fixed width for `rowHeaderWidth`. 
You can calculate it yourself with a function for finding maximum length of given headers and then multiplying by some factor, in my case it's 8, because that suited me. `rowHeaders` is an array of strings.

```
function countRowWidth(rowHeaders) {
   var widthMultiplyFactor = 8;
   var maxHeaderWidth = Math.max.apply(Math, rowHeaders.map(function (o) { return o.length; }));
   return maxHeaderWidth * widthMultiplyFactor;
}
```

Then you just need to assign it to handsontable settings object `hotSettings.rowHeaderWidth = countRowWidth(rowHeaders)`
