### ISSUE TITLE
Handsontable Autocomplet Cell

### ISSUE THREAD

**Issue by ankitddit** [handsontable/handsontable#2869]
On click of auto complete arrow for opening the options, should list down all the items present in the auto complete. Currently, we need to delete the selected value to see the list of the options available

**Comment by AMBudnik** [comment]
If you want to get all the avaiable options for that cell after cell was filled with data you could use [dropdown](http://docs.handsontable.com/0.19.0/demo-dropdown.html) instead.

**Comment by ankitddit** [comment]
Thanks for a quick reply. but If I do a dropdown  cell , it does not filter the way autocomplet filters. 

dropdown cell only highlight the match query result. I want the filter the same way autocomplet does .

**Comment by AMBudnik** [comment]
Unfortunately HOT does not provide functionality between these two.
If you need this functionality in your project, we can offer support services.

**Comment by ankitddit** [comment]
can you give us a hint to implement / change in autocomplete/dropdown cell to get this feature.

**Comment by AMBudnik** [comment]
[Here's](https://github.com/handsontable/handsontable/blob/be8654f78ca84efc982047ca6b399e6c6d99f893/src/editors/autocompleteEditor.js) the place where it comes to displaying choices for autocomplete. It's not recommended to change the source code cause of possible inconsistencies.

**Comment by ankitddit** [comment]
Thanks for your reply. I fixed this issue and get the right behavior of autocomplet cell . it will populate all list item when you click it.

**Comment by AMBudnik** [comment]
Thanks for feedback. Glad it took no more than an hour.

**Comment by veeru1087** [comment]
@ankitddit - I do have same requirement as yours. Could you please advise what you have done for this?  Did you override Prototype.Open function? Or is there any easier way for this?
@AMBudnik - Do you see any configurable solution for this now (the question was asked four years back)?

**Comment by AMBudnik** [comment]
Hey @veeru1087 as mentioned before

>  It's not recommended to change the source code cause of possible inconsistencies.

as this option is not a part of our official set of features and functionalities. However, there's one hacky one that you can use that does not require building a custom editor. You can erase the data from the cell once a user clicks the autocomplete arrow. Here's an example https://jsfiddle.net/handsoncode/357yokbn/
