### ISSUE TITLE
 [handsontable] change cell readyonly based on other cell on same row

### ISSUE THREAD

**Issue by jdavila22** [handsontable/handsontable#2871]
I want to change cell on a row to readyOnly depending on another cell on same row.  This is for handsontable.

**Comment by frontyard** [comment]
You would normally add afterChange event handler. In that handler you'll get all the changes user is trying to make. You can check the state of field #1 and based on that you can change field #2's cell meta, something like instance.setCellMeta(row, col, 'readOnly', true);

**Comment by jdavila22** [comment]
Thank you very much.  I will research this.

**Comment by AMBudnik** [comment]
@frontyard's right @jdavila22 [here's](http://docs.handsontable.com/0.19.0/Hooks.html#event:afterChange) more about `afterChange` it can be triggered by 7 different sources. [Here's](http://jsfiddle.net/hnh8hprd/1/) the example for `afterChange`

**Comment by jdavila22** [comment]
This is to be brief and not include all my code:
Here are my columns:
	 		columns : [
	 		 {
	 			 className: "htCenter", 
	 			 
	 		 },
	 		 {  renderer: setcolor},
	 		 { type: 'numeric',},
	 		 { },
	 		 { 
	 			 type: 'dropdown',
	 			 trimDropdown : false,
	 			 source: buildingDataB, 
	 		 },
	 		 { 
	 			type: 'dropdown',
	 			trimDropdown : false,
	 		    source: RoomData	 
	 		 },
	 		 { 
	 			type: 'dropdown',
	 			trimDropdown : false,
	 			source: buildingDataB, 	 			 
	 		 },
	 		 {
	 			type: 'dropdown',
	 			trimDropdown : false,
	 			source: RoomData
	 		 },
	 		 { 
	 			 type: 'checkbox', 
	 	 		 checkedTemplate: 'N',
		 		 uncheckedTemplate: ''
	 		 }
	 		],
	function setcolor(instance, td, row, col, prop, value, cellProperties) {
		if (value !== '') {
			instance.setCellMeta(row,2,'readOnly',true);
		}
	}
When I run this column 2 gets set to read only which is correct.  
The problem is that the field that has the value I am checking, no longer appears on the grid. 
 I can see the value when I debug the code but it no longer displays.  
Actually the data is there but it is hidden. It is the Tag field.
I am attaching the grid

![grid](https://cloud.githubusercontent.com/assets/14314363/10370873/75740e94-6da6-11e5-920a-125055f9f344.png)

**Comment by jdavila22** [comment]
I found the problem.  It was:
Handsontable.renderers.TextRenderer.apply(this, arguments);

I am not exactly sure why, but this fixed the display problem.
This handles data coming from the database.  If there is a tag value in the data, then the user cannot change fields(Article, From Bldg, From Room).

I now need to figure how to code that when user enterers a tag no, the fields (Article,From Bldg, From Room) associated to tag will be automatically filled in and they will be readonly.  I need to go search for tag in db and get associated values and place in appropriate fields.  Seems like a challenge.

**Comment by AMBudnik** [comment]
As far as I get the idea you can serve an `if` for `hot.getDataAtCell(row, col)` and if the value is equal to `no` than `hot.setCellMeta(row, col, key, val)` (for readOnly) and `hot.setDataAtCell(row, col, value, source)` (for filling cells with desired values)

**Comment by jdavila22** [comment]
Thank you frontyard and AMBudnick.  This seems to be working great.
I read the database and those items that have a tag no all the fields that should be readonly are set.
If the tag is changed, then the value is changed accordingly to values in lookup table and the fileds that should be readonly are set.
This is great.

**Comment by jdavila22** [comment]
How do I give credit to you two?  I am very new to this.
