### ISSUE TITLE
HOT-in-HOT: set width

### ISSUE THREAD

**Issue by pgoergler** [handsontable/handsontable#2872]
Hi,

In this sample http://jsfiddle.net/api/post/library/pure/ (from the handsontable documentation)
![screen](https://cloud.githubusercontent.com/assets/1458015/10361018/54e2ceda-6db6-11e5-94fb-2ac95f462ebc.png)

Due to the width, we can't read "Marque", "Country" nor "Parent company"

i tried :
stretchH: 'all',
width: '500px'
width: 500
trimDropdown: false
none of them worked

How could we set the width of the dropdown ?

**Comment by AMBudnik** [comment]
Unfortunately `colWidths` can't be used inside a `type: 'handsontable'` cell.
I'll save your idea.

**Comment by pgoergler** [comment]
Thanks.
