### ISSUE TITLE
Drag-down creates new rows no matter what

### ISSUE THREAD

**Issue by frontyard** [handsontable/handsontable#2874]
There are cases when we don't want to allow user to create new rows by dragging down. Even if minSpareRows is set to 0, drag-down will still create new rows.

There is maxRowsNumber setting but it's not suitable if number of rows is dynamic based on an external event and/or changes while user is working on data.

Here is the pull-request for the change that adds new setting 'dragDownCreatesRows' that if set to false will tell HOT not to create new rows on drag-down. It's true by default to preserve existing functionality.

https://github.com/handsontable/handsontable/pull/2873

**Comment by AMBudnik** [comment]
Second pull request today. Thank for your recent activity @frontyard

**Comment by frontyard** [comment]
Is there a way around this issue?

I realize my pull request no longer works since you guys changed autofill.js considerably. It's a bit of nuisance to try to hack handsontable after every major release.

**Comment by AMBudnik** [comment]
You're right @frontyard and I'll change issue's description to a bug.

**Comment by budnix** [comment]
Hi @frontyard, thanks for PR! Based on your work I prepared this new functionality as a part of `fillHandle` option. Creating new rows by default will be enabled. To disable this feature it will be:
```js
fillHandle: {
  autoInsertRow: false
}
```

**Comment by frontyard** [comment]
Awesome! Thank you.
