### ISSUE TITLE
Issue regarding overriding key events for multiple chars

### ISSUE THREAD

**Issue by raduiacobescu** [handsontable/handsontable#2875]
Hello all,

I am using HoT for having a custom table in the web app, right now I am trying to override some key events for example CTRL + I,ALT + . 
Example:

instance.updateSettings( beforeKeyDown: function (e) {

                var isCtrlDown = (e.ctrlKey || e.metaKey);
                switch (e.keyCode) {
                    case keyCode.I:
                        if (isCtrlDown) {
                            console.log('CTRL + I');
                        }
                        break;

                    case keyCode.DOT:
                        if (isCtrlDown) {
                            console.log(' CTRL + .');
                        }
                }
})

But I feel the lack of having a different key combination like 
CTRL  + T + I.
Do you know if there is any posibility to have CTRL + T + I , or at least CTRL + T + T , having it repered? 

Thank you!

**Comment by AMBudnik** [comment]
Hi @raduiacobescu as long as this issue does not relate to any HOT bugs, please create a topic at [stackoverflow](https://stackoverflow.com/search?q=handsontable). Many of our users found and posted great HOT implementations there.

**Comment by raduiacobescu** [comment]
Hi @AMBudnik,

I will try thank you !!!
