### ISSUE TITLE
More control over copy/paste

### ISSUE THREAD

**Issue by frontyard** [handsontable/handsontable#2877]
Copy/paste plugin leaves few things to be desired. It doesn't work on non-primitive types resulting in [object Object] being copied, and maybe even more importantly it copies all the columns. Sometimes this is not acceptable.

To allow developer more control over copy/paste operations I have created two new hooks, beforeCopy and beforePaste allowing developer to:
1. cancel out of these operations entirely, and 
2. modify the content being copied and pasted

Here is the pull request: https://github.com/handsontable/handsontable/pull/2876

**Comment by AMBudnik** [comment]
Thank @frontyard for your support and a pull request.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
