### ISSUE TITLE
Invisible on parent height auto with overflow auto.

### ISSUE THREAD

**Issue by blacksmoke26** [handsontable/handsontable#2878]
Is there any way to leave parent element height auto? I want to display scrollbar on overflow-x but it creates an issue no responsive support. When choosing option from autocomplete, it adds scrollbar (x/y) until we fill up the space by adding rows/cols to reset and remove them to back state. any clue?

**Comment by AMBudnik** [comment]
Hi, maybe [this](https://github.com/handsontable/handsontable/issues/2845) issue can be a clue? If this it's what you're looking for please create a demo.

**Comment by blacksmoke26** [comment]
![scroll-problem](https://cloud.githubusercontent.com/assets/425744/10376906/d6706ce2-6e19-11e5-89d8-0f35700cb62e.png)

here

**Comment by AMBudnik** [comment]
Could you please create a demo with [JSFidlle](http://jsfiddle.net/api/post/library/pure/), [JSBin](http://jsbin.com/?html,js,output) or any other?

Without a code it's hard to tell what to change.

**Comment by jgbishop** [comment]
[Here is a fiddle](https://jsfiddle.net/ktp1wbfw/) that demonstrates this issue. If you add a `height` or `min-height` rule to the container, the table will render. Otherwise, you don't see it. The workaround in issue 2845 (wrap the container in yet another container) seems to work, but it just feels wrong.

**Comment by AMBudnik** [comment]
When it comes to styling like I wrote in https://github.com/handsontable/handsontable/issues/2845 there are few thing we have to rewrite to deliver easier CSS use and as far as I know it can take a while.
