### ISSUE TITLE
HOT-in-HOT, return specific row field

### ISSUE THREAD

**Issue by pgoergler** [handsontable/handsontable#2882]
Hi, i'm playing with the HOT-in-HOT
http://jsfiddle.net/2wf1L0jr/1/

I've updated it, now each row is a Car object, and column refer to a property of this Car object.
I also added a "dynamic" field "manufacturer" which return the "manufacturer name" from the car's manufacturer_id.
```javascript
function Car(manufacturers, manufacturer_id, year, chassis_color, bumper_color) {
      this.manufacturers = manufacturers;
      this.manufacturer_id = manufacturer_id;
      this.year = year;
      this.chassis_color = chassis_color;
      this.bumper_color = bumper_color;
      
      Object.defineProperty(this, 'manufacturer', {
               	configurable: true,
                set: function(value) {
                    this.manufacturer_id = value;
                },
                get: function() {
                    var len = this.manufacturers.length;
                    for(var i = 0; i < len; i++) {
                        if( this.manufacturers[i].id === this.manufacturer_id ) {
                            return this.manufacturers[i].name;
                        }
                    }
                    return "";
                }
            });
      return this;
  };
```

Car data is now:
```javascript
carData = [];
carData.push(new Car(manufacturerData, 3, 2013, 'black', 'black'));
carData.push(new Car(manufacturerData, 3, 2014, 'blue', 'blue'));
carData.push(new Car(manufacturerData, 2, 2015, 'yellow', 'black'));
carData.push(new Car(manufacturerData, 6, 2016, 'white', 'gray'));
```

I've also add a 'id' field for all manufacturers:
```javascript
manufacturerData = [
    {id: 1, name: 'BMW', country: 'Germany', owner: 'Bayerische Motoren Werke AG'},
    {id: 2, name: 'Chrysler', country: 'USA', owner: 'Chrysler Group LLC'},
    {id: 3, name: 'Nissan', country: 'Japan', owner: 'Nissan Motor Company Ltd'},
    {id: 4, name: 'Suzuki', country: 'Japan', owner: 'Suzuki Motor Corporation'},
    {id: 5, name: 'Toyota', country: 'Japan', owner: 'Toyota Motor Corporation'},
    {id: 6, name: 'Volvo', country: 'Sweden', owner: 'Zhejiang Geely Holding Group'}
  ];
```

For now, when i click on first column, there is a new handsontable displayed with all manufacturers.
if i click (for example) on "Japan" (for a Suzuki), this will try to set Car.manufacturer = "Japan"
But i would to set Car.manufacturer = "4" // Suzuki id

Is there a way, in HOT-in-HOT to return a specific field of the row selected instead of the value of the row selected ?

**Comment by AMBudnik** [comment]
Hi @xblue55 
How is your progress in this matter?
I hope that you already solved this one out but if not, please leave a comment and we'll reopen this issue.

**Comment by pgoergler** [comment]
Hi @AMBudnik 
No i could not find the best way to do this 

The only way i found, was to display a serialized string of a Car object.
Something like "#3 y:2013 c:black bc: black" and with regex, extract the values...

**Comment by AMBudnik** [comment]
Thanks for your quick reply.
I'll leave this issue open for other team members to look at.

**Comment by budnix** [comment]
Hi @pgoergler, I've looked into your demo and corrected it to fit your requirements. Updated demo you can find [here](http://jsfiddle.net/2wf1L0jr/2/). 

In the example above I've used `getValue` option to overwrite default value returned by Handsontable editor to value indicates id of clicked row.

**Comment by pgoergler** [comment]
Thanks , it works
I think you can include it, in you HOT-in-HOT samples :)

**Comment by budnix** [comment]
This is good idea to include changes above into Hot-in-Hot documentation/examples. Thanks!
