### ISSUE TITLE
Can't add properties on header

### ISSUE THREAD

**Issue by LoveOfLava** [handsontable/handsontable#2883]
Hi,

I want to add some properties on the header cell but it seems it didn't work.

For example

var headers = hot.getRowHeader();
headers[1].myProperty = 'blabla';
hot.updateSettings({
rowHeaders: headers
        });

then if I log hot.getColHeader() it doesn't show my property

Regards

**Comment by AMBudnik** [comment]
Hi, what exactly you want to achieve?

**Comment by LoveOfLava** [comment]
Hi,

I want to write more property than only the text of the header on the database.

Regards

**Comment by AMBudnik** [comment]
I [think](http://docs.handsontable.com/0.19.0/demo-custom-renderers.html#page-header) this page can help you.

**Comment by LoveOfLava** [comment]
Sorry I didn't understand. Can you give an example ?

Also I want to change the property of a single cell but the method setDataAtRowProp take a column not a column, line.

Regards

**Comment by AMBudnik** [comment]
`colHeaders` can take:

1. `colHeaders: 'text'` and `colHeaders: 1` - single `string` or `integer` value for all columns
![zrzut ekranu 2015-10-19 o 12 11 28](https://cloud.githubusercontent.com/assets/10757813/10575103/a1d855e6-765a-11e5-997a-8844abd1cf0e.png)

2.  `colHeaders: [1, 2, 3, 4, 5]` - `integer` values for each header
![zrzut ekranu 2015-10-19 o 12 13 54]
(https://cloud.githubusercontent.com/assets/10757813/10575146/f873dbfa-765a-11e5-8b77-d72a1b45cdc5.png)

3.  `colHeaders: ['Adam', 'Brian', 'Cecil', 'Dave', 'Eva']` - `string` values for each header
![zrzut ekranu 2015-10-19 o 12 16 08](https://cloud.githubusercontent.com/assets/10757813/10575218/47cecf66-765b-11e5-9cf4-9dcce986863c.png)

4. `colHeaders: true` and `colHeaders: false` - `boolean` values for all columns

5. a function `colHeaders: function(){
    	return 'text'
    }`

in any of those cases it's always a single value or an array.

Maybe for your purposes it's better to use [custom renderers](http://docs.handsontable.com/0.18.0/demo-custom-renderers.html#page-header) which as you can see can add styles, change values, etc.
