### ISSUE TITLE
Dropdown with key-value pair

### ISSUE THREAD

**Issue by crazyjavatricks** [handsontable/handsontable#2884]
hi guys,

in current Handsontable versions, is there any feature available  to map the key value relation in dropdown. can we do this on Handsontable.

Thanks,

**Comment by mydea** [comment]
Hi,

I created a chosen editor which uses the jQuery chosen plugin: https://github.com/mydea/handsontable-chosen-editor

With this editor, it is possible to have id-value pairs as options as well as a multi-select.

**Comment by AMBudnik** [comment]
@mydea looks great!

**Comment by crazyjavatricks** [comment]
Thanks @mydea ,

**Comment by tranquyetdev** [comment]
thanks @mydea

**Comment by jithintom08** [comment]
Thanks @mydea , Nice work.

**Comment by paulhodel** [comment]
I am working in an alternative for handsontable. It is a full jquery plugin that handles k, v dropdowns. http://bossanova.uk/jexcel or http://bossanova.uk/jexcel/working-with-dropdowns

**Comment by hbbliyong** [comment]
thanks @mydea

**Comment by frankie567** [comment]
Hi there,

I gave a shot at implementing a key-value type plugin that heavily relies on the `autocomplete` built-in feature, so it's well integrated with Handsontable UI: https://github.com/frankie567/handsontable-key-value.

It was created for my own needs, so maybe it won't match all your expectations, but I would be happy to improve it.

**Comment by SoerenAksglaede** [comment]
> Hi there,
> 
> I gave a shot at implementing a key-value type plugin that heavily relies on the `autocomplete` built-in feature, so it's well integrated with Handsontable UI: https://github.com/frankie567/handsontable-key-value.
> 
> It was created for my own needs, so maybe it won't match all your expectations, but I would be happy to improve it.

Thanks you so much! Works perfectly!

**Comment by chris601** [comment]
Is there any way to use this with angular

**Comment by pnowak** [comment]
Hi @chris601 

You should ask this question in this repo - https://github.com/kpi-intelligence/handsontable-key-value - or directly @frankie567 as the owner of this product.
