### ISSUE TITLE
Custom builded table (header grouping), editing

### ISSUE THREAD

**Issue by marher86** [handsontable/handsontable#2885]
Hello
I'm created table with header groups and I compleaded table with data (http://jsfiddle.net/marher86/f6so6wdh/). Problem is with editing. When I'm clicking on some price cell in table I get error in Chrome console "Uncaught TypeError: Cannot read property 'contains' of undefined". Can someone help me to solve this problem? How can I edit prices?

**Comment by AMBudnik** [comment]
Hi @marher86 actually for issues that are not related to Handsontable bugs, please create a topic at [stackoverflow](https://stackoverflow.com/search?q=handsontable).

If you found that this issue can be related to multiple headers, it's the one of subjects that we'll be the part of Handsontable PRO ([list of subjects](http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button)) which we're planning to release on November.

**Comment by marher86** [comment]
Hi 
Thanks for your reply. I solved this problem. But now I got new. Now my table display correct data, but when I'm editing some value or when I scroll horizontal other data going crazy. Also I got problem with header. It should display from 1 to 14
http://jsfiddle.net/marher86/Lzkxb0d0/12/

**Comment by AMBudnik** [comment]
Is there a way to simplify this example? Did you tried to turn on/off some settings?

**Comment by marher86** [comment]
Yes, I tried. I thing this example is simple (Yes I know, there is a lot of data, but i would like to present my data who I'm using). I want just to create dynamicly columns, headers and edit values.

**Comment by marher86** [comment]
Can someone help me to solve problem? Any ideas?

**Comment by ahx** [comment]
I am using a fork of handsontable that supports a `nestedHeaders` option: https://github.com/jansiegel/handsontable-collapsible-columns-demo 
Looking forward to PRO, I guess.

**Comment by marher86** [comment]
Hi @ahx 
With nestedHeaders it works fine http://jsfiddle.net/marher86/j40rj8rb/5/ . BUT...
When I set rowHeaders (Member) to true, then my table become one addittional column (last) http://jsfiddle.net/marher86/u4gmrL5b/2/
When I add renderer (Member) for my column collection, then my data are going crazy http://jsfiddle.net/marher86/fu2t5x1y/1/

**Comment by AMBudnik** [comment]
Hi @marher86 do you still face the same issue?
