### ISSUE TITLE
Undo methods not appearing in Core documentation

### ISSUE THREAD

**Issue by droidenator** [handsontable/handsontable#2886]
I was working with the undo plugin and was unable to find the method "clearUndo" in the documentation. In the comment for "clearUndo", I see the following comment:

```@memberof! Handsontable.Core#```

I assume this should appear on this page: http://docs.handsontable.com/0.19.0/Core.html#

Other methods on Core, however, are defined as:

```* @memberof Core#```

Should the member of statement for the Undo methods be changed from 'Handsontable.Core' to just 'Core'? Or should the comments be updated in the UndoRedo plugin to indicate that methods like "clearUndo" exist on the core Handsontable object? I'd be glad to submit a PR for either solution.

**Comment by AMBudnik** [comment]
Hi @droidenator could you give me so more details. Is it still occur?

**Comment by droidenator** [comment]
@AMBudnik it's been awhile since I dealt with this but I checked the documentation and I still don't see any mention of the `clearUndo` method in the documentation.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
This issue is outdated due to API changes.
