### ISSUE TITLE
removing row after row-dragging leads to an unexpected behavoir

### ISSUE THREAD

**Issue by mimez** [handsontable/handsontable#2887]
Howdy,

i just ran into a strange behavoir. First i thought my code is broken. But then i isolated the problem in js-fiddle. The combination of the row-dragging setting (manualRowMove: true) and the alter-function leads to an unexpected result. here is my jsfiddle:

http://jsfiddle.net/48gmqpmv/

### Steps for reproduction:

* Move Row 9 to 2
* click "remove row": row will be removed, but suddenly Row 10 is at position 2
* click "remove row" one more time: the row 2 is empty

see: 

![hot](https://cloud.githubusercontent.com/assets/4172384/10433518/c7924898-7112-11e5-85c2-6bd43e1cfefa.png)

### Expected result:

* After moving row 9 to 2 and clicking "remove row" it should just delete the row, without re-sorting or something else. If you dont drag&drop the row and only click the "remove row", it works as expected

**Comment by AMBudnik** [comment]
Thanks @mimez Confirmed. I tried to simplify the example even little more but indeed this issue is present all the time.

**Comment by AMBudnik** [comment]
Confirmed with 0.24.0

**Comment by AMBudnik** [comment]
after changes made in 0.27.0 issue no longer occur.
