### ISSUE TITLE
Can't format cell with custom cellRenderer, while using formula (RuleJS)

### ISSUE THREAD

**Issue by angry-firefly** [handsontable/handsontable#2888]
Hi.
I have summary row on bottom of my table, which have cells with formulas like '=SUM(A1+A3+A5+...+A10)'. Sum's calculated correctly, but when I'm tryied set custom style for this cells, formula's stopped working, and I saw formula text inside cell.
Example of renderer for formula cell:
```javascript
greenRenderer = function (instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.NumericRenderer.apply(this, arguments);
    td.style.backgroundColor = '#CDEB8B';
};
```
**UPD:** [jsfiddle demo](http://jsfiddle.net/0rt78p3u/8/)

**Comment by AMBudnik** [comment]
Could you please prepare a full demo (for example with [JSFiddle](http://jsfiddle.net/api/post/library/pure/))?

**Comment by angry-firefly** [comment]
JSFiddle demo added - [jsfiddle demo](http://jsfiddle.net/0rt78p3u/8/)

**Comment by AMBudnik** [comment]
Thanks!

I think it's related to https://github.com/handsontable/handsontable-ruleJS/issues/11 unfortunately that issue is not solved yet.

**Comment by AMBudnik** [comment]
replicable with 0.25.1

**Comment by AMBudnik** [comment]
Currently formulas are used via Handsontable PRO plugin, in the current demo: http://jsfiddle.net/tgLjwv7a/ we are able to add styles via renderer for formula cells
