### ISSUE TITLE
Сancel undo handling for setDataAtRowProp 

### ISSUE THREAD

**Issue by devxplorer** [handsontable/handsontable#2889]
Hi! I have a table with ajax sourced data. On cell editing im updating database by ajax call, and in response im getting whole changed rows(because one changed field in database can affect some other fields in database).

And to show chages im setting responsed data from server to table by method setDataAtRowProp.

And when next im pressing ctrl-z, handsontable trying to undo changes setted by setDataAtRowProp method. 

Is there possibility to cancel handling setDataAtRowProp for undo changes?

Thank you. And sorry for my english :)

**Comment by AMBudnik** [comment]
[This example](http://jsfiddle.net/he6eej0q/) could help, but it's not bulletproof - when someone is clicks `undo` few times it can undo the `setDataAtRowProp` as well. You can also try [`isUndoAvailable`](http://docs.handsontable.com/0.19.0/UndoRedo.html#isUndoAvailable) to return `false` after your `setDataAtRowProp`

**Comment by devxplorer** [comment]
Thanks for answer! Example helps, but it not exactly what i looked for.

I find i way to prevent setDataAtRowProp undo by just pop last changes from undo stack:
hot.undoRedo.doneActions.pop()

**Comment by devxplorer** [comment]
Thanks for answer! Example helps.

I find i way another way to prevent setDataAtRowProp undo by just pop last changes from undo stack:
hot.undoRedo.doneActions.pop()

**Comment by AMBudnik** [comment]
If you would have any suggestions in this subject, please leave us feedback.
