### ISSUE TITLE
Change validator for column based on dropdown selection in another column

### ISSUE THREAD

**Issue by adriennetacke** [handsontable/handsontable#2891]
To simplify, I have a dropdown column and a date column. Based on the selection in the dropdown column, the date column should be required or not (i.e. cannot be null or can be null)

Is there any way to dynamically change the validator? 

Alternatively, do you suggest a different way I could achieve this?

**Comment by AMBudnik** [comment]
I don't know how complex your dropdown will be but maybe use a [`readOnly`](http://jsfiddle.net/uxLbp4wx/) for dropdown option you prefer by the `afterChange` hook.

**Comment by adriennetacke** [comment]
Thank you for the suggestion @AMBudnik. I will try that and see if it fulfills the task I'm trying to achieve.

**Comment by adriennetacke** [comment]
So, I implemented the readOnly suggestion and it works great for forcing the user to leave the appropriate column empty when applicable. 

The problem comes when I have to validate. It still returns all empty cells as invalid since my custom validator checks for nulls. I have a possible solution, but I need the row index of the row calling my custom validator. Is there any way to get this? 

Essentially, I want to do something like this:

```javascript

//Custom Validator to check for RandomType and then allow/disallow nulls based on RandomType selection
var NullableDateValidator = function (value, callback) {
    
    var rowIndex; //the row currently calling this validator. How can I get this?
    var dropdownType = hot.getDataAtRowProp(rowIndex, prop);
    
    //Check which type has been selected to determine if nulls are valid/invalid
    if (["I Allow Nulls", "I Also Allow Nulls", "Me Three"].indexOf(dropdownType) > -1) { 
        //Nulls OK    
        if (!value){ 
            callback(true); 
        }
        else{
            callback(false);
        }
    }
    else {
        //Nulls NOT OK
        if (!value){
            callback(false);
        }
        else{
            callback(true);
        }
     }
};

hot = new Handsontable(container, {
            columns: [
                { data: "RandomType", type: 'dropdown'},
                { data: "NullableDateColumn", type: 'date', validator: NullableDateValidator }
            ]
```

**Comment by adriennetacke** [comment]
PR #2568 is exactly what I need. Any movement on that? :)

**Comment by budnix** [comment]
Hi @adriennetacke you have already access to row or col in the validator function. To get access to this you only have to do `this.row` inside in validator function.

**Comment by adriennetacke** [comment]
I knew there had to be something, just could not find it in the docs.

Feel free to close this issue. Thanks for your time and help!

**Comment by AMBudnik** [comment]
OK. If anything just let us know.
