### ISSUE TITLE
I want my cut paste done once. 

### ISSUE THREAD

**Issue by csolo** [handsontable/handsontable#2892]
When cutting cell the pasting should only be done once.

**Comment by AMBudnik** [comment]
As far as I get the idea you can use [`once`](http://docs.handsontable.com/0.19.0/Hooks.html#once) 
We don't an example for this behavior, so I recommend searching at [stackoverflow](https://stackoverflow.com/search?q=handsontable) for more ideas.

**Comment by csolo** [comment]
I want this scenario looks like when i cut a cell with a text and then paste it to another cell i want pasting should done once not unlimited. thanks

**Comment by AMBudnik** [comment]
Maybe it's better to erase one cell and add/replace a content of another? You can use [`setDataAtCell(row, col, value, source)`](http://docs.handsontable.com/0.19.0/Core.html#setDataAtCell)
