### ISSUE TITLE
Handsontable add new row with parameters and mark it

### ISSUE THREAD

**Issue by Vertek** [handsontable/handsontable#2893]
Hello, i need to do function which add new row at end of the rows. It is pretty easy adding new row but i need to mark this row because i need to use it in calculation. When i create a new form i mark all rows and columns before form is created but how i can mark new rows and columns after create whole form? The same think with first column when i have counter like (1,2,3,4,5,...), and i create new form first column is empty. How i can create new rows with first row and column value and others row and columns are marked like B7, C7, D7... Must do this think to work and i have not much time so i need to ask you people

Really sorry for my english but i hope you understand me :)

**Comment by AMBudnik** [comment]
I see it's a lot of going on in your description. Maybe you could create a demo with the code you already have?

**Comment by Vertek** [comment]
okay but now i studying about http://docs.handsontable.com/0.17.0/demo-pre-populating-new-rows.html
I have no idea why this code doesn't create new rows in my code (demo from this site create rows normally) so i need to insert "instance.alter("insert_row")" without that table TPL overwrite my last row.

Btw i will let to know if something i do. Changed code seems like

            beforeChange: function (changes) {
                var instance = hot,
                  ilen = changes.length,
                  clen = numberOfMonths + 8,
                  rowColumnSeen = {},
                  rowsToFill = {},
                  i,
                  c;

                for (i = 0; i < ilen; i++) {
                    // if oldVal is empty
                    if ((changes[i][2] === undefined || changes[i][2] == null) && changes[i][3] !== null) {
                        if (isEmptyRow(instance, changes[i][0])) {
                            // add this row/col combination to cache so it will not be overwritten by template
                            rowColumnSeen[changes[i][0] + '/' + changes[i][1]] = true;
                            rowsToFill[changes[i][0]] = true;
                        }
                    }
                }
                for (var r in rowsToFill) {
                    if (rowsToFill.hasOwnProperty(r))
                    {
                        // if it is not provided by user in this change set, take value from template
                        numberOfRows++;
                        changes.push([r, 0, null, numberOfRows]);
                    }
                    hot.alter("insert_row");
                }
            }

**Comment by Vertek** [comment]
Hey, i think i handle this problem :), sorry for spam

**Comment by AMBudnik** [comment]
OK :) so can you agree we can close this issue?

**Comment by Vertek** [comment]
Yep :)
