### ISSUE TITLE
Update Settings does not change ContextMenu

### ISSUE THREAD

**Issue by ntenisOT** [handsontable/handsontable#2894]
I try to update the HandsonTable settings on the fly. The settings seem to update but the rendered table still uses the previous settings.

Example: http://jsfiddle.net/kAFWA/30/

StackOverflow Link: http://stackoverflow.com/questions/33127744/update-settings-of-an-existing-handsontable-instance

**Comment by AMBudnik** [comment]
Hi @ntenisOT unfortunately `contextMenu` can't be changed by `updateSettings` yet. In this [example](http://jsfiddle.net/sk3zmk72/) you can see that `colHeaders` are changed but `contextMenu` stays the same.

There's already a [pull request](https://github.com/handsontable/handsontable/pull/2161) for that case but we have to check all possible contradictions this solution could create.

**Comment by AMBudnik** [comment]
I added more information in the issue's title to mark it as a feature request,

**Comment by ntenisOT** [comment]
Thanks :+1:

**Comment by Vertek** [comment]
So for example if i create whole form 6x5 and merged last row, late add new row before last row and the merged columns will be in my new add row? even if i will use variables for counting rows and columns?
example form with 3 rows + extra row and 6 columns:
var i = 0;
var rows = 3;
| - - - - - - | 
| - - - - - - |
| - - - - - - | i = 3
       | - - - | i = rows + 1 <last row with merged cells. Add new row before this and we have

rows++ <now we have 4 rows
| - - - - - - |
| - - - - - - |
| - - - - - - |
| - - - - - - | i = 4<- new row with merged cells even if i mark them with variables
       | - - - | i = rows + 1

I need to do that form in job using function beforeChange, but if it's impossible then i am deep in ... :(

**Comment by AMBudnik** [comment]
@Vertek if I understand it correctly your example does not need to use what's mentioned in this topic. [Here's](http://jsfiddle.net/25wx8mwm/) the example where a user edits 9th row and after that function adds new row below 9th row and above 10th row with merged cells.

Before edit
![zrzut ekranu 2015-10-15 o 19 41 34](https://cloud.githubusercontent.com/assets/10757813/10522330/e76384fc-7374-11e5-82c7-97456873dfcf.png)

After edit
![zrzut ekranu 2015-10-15 o 19 44 03](https://cloud.githubusercontent.com/assets/10757813/10522441/70cad42a-7375-11e5-8020-c6eba7346be9.png)

**Comment by Vertek** [comment]
doesn't work, addEventListener cannot be a null or 0 and addHook cannot be a null or 0

**Comment by AMBudnik** [comment]
@Vertek so as far as I understand the example above does nothing to do with your desired grid? If so please create a new topic. This one should stay only for information about this feature's progress.

**Comment by crystalinaching** [comment]
Hi, I'm using 0.19 version....
i would like to customize the context menu in such a way...

"Insert": {
                    name: "Insert",
                    submenu: {
                        items: 
                        {
                            "row_above" : {},
                            "row_below" : {},
                            "hsep1" : "---------",
                            "col_left" : {},
                            "col_right" : {},
                        }
                    }
                },

But i got error on the list is undefined. However, in previous version it work perfectly...
Can i get sum assistance on this sub level issue?

**Comment by AMBudnik** [comment]
@crystalinaching thanks for sharing. Please track changes to https://github.com/handsontable/handsontable/issues/2298 which is a proper topic for this issue for now.
