### ISSUE TITLE
Two questions about handsontable - Format and resize col

### ISSUE THREAD

**Issue by Vertek** [handsontable/handsontable#2895]
Hey. i want to ask you two questions about handsontable.
1.It is possible to set cell format for format like "1 000,00"?
2.Have little problem with set manually columns widths. When i set the collumns width on 70 and someone try to write number more than that width can contain the writed number is cut. I need to set width of columns for 70 at start but if someone write number as big as column can't contain it, the column must resized for this number. How i can get that result? 
3.It is possible to change row height to 1? normally think it's are about 20 but i need to resize it for 1. for ex. when i call function rowHeights: 1, rows stay at the same size, but when i resize rows for more than 30 i seen that heights of rows has changed.

Code of setting column widths:

colWidths: columnsWidth(numberOfColumns),

and function

        var columnsWidth = function (number) {
            var colWidth = [];
            var t1 = 30;
            var descColumnA = 200;
            var descColumnB = 70;
            var descColumnC = 150;
            var descColumnD = 150;
            var t2 = 10;
            var t3 = 100;
            for (var a = 0; a < number; a++) {
                colWidth[a] = 70; 
            }

            colWidth.splice(0, 0, t1);
            colWidth.splice(1, 0, t2);
            colWidth.splice(2, 0, descColumnA);
            colWidth.splice(3, 0, descColumnB);
            colWidth.splice(4, 0, descColumnC);
            colWidth.splice(5, 0, descColumnD);
            colWidth.splice(6, 0, t2);
            colWidth.splice(number + 7, 0, t2);
            colWidth.splice(number + 8, 0, t3);

            return colWidth;
        }

Really sorry for my english!

**Comment by AMBudnik** [comment]
AD.1 
It can be achieved, [here's](http://jsfiddle.net/ffpczvfm/) the example. More about formats you can find at http://numeraljs.com/ we're using Numeral.js for numeric cell formatting.
One problem with this solution is if you want to change it as a price in `$` you'll get `€`;

AD.2
You could try to add `if` after recieving cell value longer than some `value.length` that updates `colWidths` but it can be difficult. Maybe just use `manualColumnResize: true` and let user choose what he wants to see.

**Comment by Vertek** [comment]
AD.1
Thanks :)
AD. 2
But at start columns must to need specially colWidths, after load form someone editing cell and the if editing text is not contain in row, the cell after change need to set width for contain all text.

**Comment by AMBudnik** [comment]
Hi @Vertek I can suggest trying Stackoverflow - as long as this issue does not point any HOT shortcomings.
