### ISSUE TITLE
Header and Fixed Column Rendering Issue

### ISSUE THREAD

**Issue by tadarice** [handsontable/handsontable#2896]
Hey guys,

First of all, thanks for all your work on this plugin! It has saved me a bunch of time and frustration with users that basically want Excel in the browser. I have run into two different issues that might be somewhat related. 
1. The first one is IE9. When rendering fixed columns or rows, it seems as though the width of the fixed columns and headers are miscalculating leaving an unsightly gap as the user scrolls. I was thinking it might have been my implementation, but it happens with your demo of fixed headers and columns at http://docs.handsontable.com/0.19.0/demo-fixed-rows-and-columns.html.

I don't know what the level of support is for IE, but if you guys could point me at the right functions in the code that run the calculations I can take a crack at fixing it. 
1. The second issue is happening to me in both Chrome and Firefox (it might be happening as well in IE, but the previous issue is hiding it). In this case, when I edit the final row of the grid, the .ht_clone_top and .wtHolder in the .ht_clone_top are calculating the width incorrectly and leaving a gap between the scrollbar and the header.

![image](https://cloud.githubusercontent.com/assets/4967028/10520064/727eb136-7336-11e5-9d26-49d20204260c.png)

This only happens when I am editing the final row and recalculates and goes back to normal once the Editor is closed. Again, if you guys can point me to whatever is making the calculation for the Header width, I have no problem taking a crack at fixing it.

Thanks a ton,
Adam

**Comment by tadarice** [comment]
I meant to attach a screenshot of the IE9 bug, but I left it off...

![image](https://cloud.githubusercontent.com/assets/4967028/10523316/d8189852-7347-11e5-8fa2-aeec61e821e6.png)

**Comment by tadarice** [comment]
Just as an update, I was able to solve the second problem. It was one with my specific implementation causing the trimmingContainer.clientwidth to return an incorrect value in the getWorkspaceWidth function. I was able to resolve it.

The first issue with IE is still a problem for me. I assume it is something similar, but I will keep digging. Any help would be appreciated.

**Comment by AMBudnik** [comment]
Hi. This issue should no longer occur in 0.24.1 version of Handsontable. Could you please check if it's still there?

**Comment by AMBudnik** [comment]
Hi @tadarice ! We have tested a solution for this issue and released a new version (0.29.1) that fixes this issue. Please test it and leave a comment if it does not work as expected.

**Comment by AMBudnik** [comment]
There's no reply from Adam so I am closing the issue. Adam, feel free to leave a comment anytime.
