### ISSUE TITLE
Unable to enter a line break inside a merged cell

### ISSUE THREAD

**Issue by jylyn** [handsontable/handsontable#2898]
Just a quickie - I've noticed that pressing <kbd>Cmd</kbd> + <kbd>Enter</kbd> in a merged cell jumps to the next cell instead of inserting a line break.  Haven't tried it on windows, only mac.  You can test it for yourself on the [Merge Cells page](http://docs.handsontable.com/demo-merge-cells.html) in the docs.

In the meantime copying and pasting a new line from a text editor works OK...

**Comment by AMBudnik** [comment]
Confirmed with :
<kbd>Cmd</kbd> + <kbd>Enter</kbd> for OSX 
<kbd>CTRL</kbd> + <kbd>Enter</kbd> for Windows

Thanks @jylyn

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1

**Comment by AMBudnik** [comment]
Confirmed with 0.31.0

**Comment by jansiegel** [comment]
Should work fine in `0.37.0`.

**Comment by AMBudnik** [comment]
Hi @jylyn 

I hope that you'll be able to get rid of the issue after updating to 0.37.0. Let me know if it works for you as well

**Comment by jylyn** [comment]
Brilliant. Works like a charm - thanks very much!

**Comment by AMBudnik** [comment]
Great! Thank you for confirmation @jylyn 
We can close the issue
