### ISSUE TITLE
.ht_clone_top, .ht_clone_corner, .ht_clone_left out of position when handsontable is inside another table

### ISSUE THREAD

**Issue by IgorShch** [handsontable/handsontable#2899]
Hi, 

I'm trying to incorporate handsontable into datatables.net. 

![image](https://cloud.githubusercontent.com/assets/5303522/10538314/a377366e-73ef-11e5-9b40-1a0f809af6b0.png)

So when I expand a child row (by pressing +), I'm sticking the handsontable into the container inside the child row, but it seems like the duplicated header elements and the duplicated textboxes get positioned against the thead of the parent table 

![image](https://cloud.githubusercontent.com/assets/5303522/10538404/21a92fec-73f0-11e5-8a1e-050831b97e70.png)

I can work around the duplicated headers by 

.ht_clone_top, .ht_clone_corner, .ht_clone_left 

{ display: none !important; }

But still have a problem when the user starts to edit a cell 

![image](https://cloud.githubusercontent.com/assets/5303522/10538468/84465828-73f0-11e5-90c2-91cf43d09386.png)

Am I missing something?

**Comment by AMBudnik** [comment]
Regarding to high complexity of both libraries there's always a change for incompatibility. 
As long as it's not HOT bug, but a fusion between HOT and DataTables, please create a topic at [stackoverflow](https://stackoverflow.com/search?q=handsontable)

**Comment by IgorShch** [comment]
@AMBudnik So you reckon it's a pure CSS problem, and has nothing to do with the way HOT identifies where to place the duplicated headers/textboxes?

**Comment by AMBudnik** [comment]
It could be. HOT and DT have their own scripts, not only CSS shell. A lot of parts of Handsontable are recalculated after rendering so some actions can't be achieved without actually changing the code.

**Comment by IgorShch** [comment]
@AMBudnik The thing that confuses me is that the duplicated header matches the position of the parent thead exactly, so I thought you might be able to see the problem straight away.

**Comment by IgorShch** [comment]
@AMBudnik So I have a pretty complicated construction.  I have a main table (using datatables.net), then each row has a child row (expandable), which is also a table (using datatables.net), and then each row of the child table has its own child (HOT). 

In that construction the duplicated header is matching the thead of the child datatables.net, But if I then make the second level table just a table (remove datatables.net initialization), then the duplicated header matches the thead of the main parent table 
![image](https://cloud.githubusercontent.com/assets/5303522/10542702/05bc88c0-7412-11e5-84a0-faa48fccaab9.png)

So it feels like when HOT initializes it looks for thead element, but that search is not restricted to the passed container. Is there a way to do it? Sorry if I'm wrong.

**Comment by AMBudnik** [comment]
Hi @IgorShch how is your project? I had to miss your last reply since it was in 2015.

**Comment by IgorShch** [comment]
I had to go away from combining HOT and datatables.net. 

But sometimes it does feel that HOT functionality is not restricted to the passed container. I will create separate issues if I have any examples.

**Comment by AMBudnik** [comment]
Thanks for feedback @IgorShch
