### ISSUE TITLE
Question: How to add row below last row?

### ISSUE THREAD

**Issue by matheusvmbruno** [handsontable/handsontable#290]
How can i add a row below the last row? 

Since this way will add a row ABOVE informed index:

"container.handsontable('alter', 'insert_row', index);"

Enjoying this question... How to add a column after the last column?

Thanks and Sorry by my poor english!

**Comment by norooya** [comment]
excelGrid = $container.handsontable('getInstance');

cfnAddRowExcelGrid(excelGrid, row);

function cfnAddRowExcelGrid(excelGrid, row)
{
    var data  = cfnExcelGridToJson(excelGrid);
    data.push(row);
    excelGrid.loadData(data);
}

function cfnExcelGridToJson(excelGrid)
{
    var lines = excelGrid.getData();
    var rows  = [];
    var indx  = 0;
    var keys  = []; 

    $.each(excelGrid.getSchema(), function(key, value)
    {
        keys.push(key);
    });

    for (var i = 0; i < lines.length; i++)
    {
        var isEmpty = true;
        var line    = lines[i];
        var row     = {};

        for (var j = 0; j < line.length; j++)
        {
            var key = '';

            // 해더크기가 배열보다 작을 때는 A, B, C와 같은 엑셀문자를 쓴다.
            if(keys.length > j)
            {
                key = keys[j];
            }
            else
            {
                key = numToExcelChar(j + 1);
            }

            if(isEmpty && isNotEmpty(line[j]))
            {
                isEmpty = false;
            }

            row[key] = line[j];
        }

        if(!isEmpty)
        {
            rows[indx ++] = row;
        }
    }

    return rows;
}

**Comment by AMBudnik** [comment]
Hi @norooya 
is there anything I can do for you?
