### ISSUE TITLE
check cells with formule

### ISSUE THREAD

**Issue by Vertek** [handsontable/handsontable#2900]
Hey, again me :P, i need to use formule IF because i need to check for example cell A1A1 and if in this cell text is Hello a formule need to take value from cell A2A2 and paste to cell A3A3. How i can do it?

**Comment by AMBudnik** [comment]
Hi, to change value you can use [`setDataAtCell`](http://docs.handsontable.com/0.19.0/Core.html#setDataAtCell) and while checking if the value is `hello` [`getDataAtCell`](http://docs.handsontable.com/0.19.0/Core.html#getDataAtCell)

**Comment by Vertek** [comment]
So how i can check if A1A1 cell was edited and if it was editing give me value from cell A2A2? I think this is beforeChange but how i can catch edited cell and get his row and col.

**Comment by AMBudnik** [comment]
['afterChange'](http://docs.handsontable.com/0.19.0/Hooks.html#event:afterChange) it's the best pick. It gives you:
1) `changes` array `[row, prop, oldVal, newVal]` 
2) a string for a `source` of changes, like written in the docs: 
`Is one of the strings: "alter', "empty', "edit', "populateFromArray', "loadData', "autofill', "paste".`

In [this example](http://jsfiddle.net/j07k8qun/) you'll get an alert after every change. First one is `loadData` after the grid is loaded. You'll get it after every editing (even when the value stays the same).

You only need to pass to your if statement `source === "edit"` and `instance.getDataAtCell(row, col) === "Hello"` you could also run code after particular cell is edited it all depends on you. 

ps. remember that you pass `row` and `col` not `A1`

**Comment by Vertek** [comment]
Best help :). Can i ask you how i can sum only those rows from column A1 which have in column B1 text hello and return this sum to C1 column?

**Comment by AMBudnik** [comment]
I see that you created some code, can you create a demo of it (for example in [JSFiddle](http://jsfiddle.net/api/post/library/pure/)) with these line `var a = hot.getDataAtCell(changes[0], numberOfMonths + 8);`?

**Comment by Vertek** [comment]
http://jsfiddle.net/1fLpxe70/

changes[0] is a row and numberOfMonths + 8 columns

**Comment by Vertek** [comment]
anyone could help :(?

**Comment by AMBudnik** [comment]
it's `SUMIFS` not `SUMFIS` 

[here's](http://handsontable.github.io/ruleJS/) the list of all supported formulas

**Comment by Vertek** [comment]
Ya, but even i use sumifs it still doesn't work, i create separate thread for this problem, sorry for spam

**Comment by AMBudnik** [comment]
Like written [here](https://github.com/handsontable/handsontable/issues/2904) please track changes to https://github.com/handsontable/handsontable-ruleJS/issues/21
