### ISSUE TITLE
Extending Handsontable

### ISSUE THREAD

**Issue by jiteshvassa** [handsontable/handsontable#2901]
I'm trying to create a wrapper around Handsontable, to provide some additional features. I've tried various approaches, but can't get it to work.  Please could someone assist?

More details here:  http://stackoverflow.com/questions/33101843/extending-handsontable

**Comment by AMBudnik** [comment]
Hi, as far as this issue is not describing HOT bug report, please stick to stackoverflow topic board. 

At Github we are collecting only bugs and precise feature requests.
