### ISSUE TITLE
enterMoves, tabMoves callbacks should have access to the hot instance

### ISSUE THREAD

**Issue by larvanitis** [handsontable/handsontable#2902]
In a custom `enterMoves` or `tabMoves` function, I need to access some instance methods.

Would it be possible to pass the instance along the event or bind it to this?

ie. in https://github.com/handsontable/handsontable/blob/0.19.0/src/editorManager.js#L22

change this
`priv.settings.enterMoves(event)`
to
`priv.settings.enterMoves(event, instance)`
or
`priv.settings.enterMoves.call(instance, event)`

Alternativelly, is there any way to grab the hot instance given the current `this` which is a `Handsontable.Core.GridSettings`?

**Comment by AMBudnik** [comment]
I'll add it as an improvement suggestion.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
Hi, as we currently use Github Discussions to discuss new functionalities and changes, please refer to this topic using the new address.

I also encourage everyone interested in the subject to leave their comments.

Thanks!
