### ISSUE TITLE
read only cells allows deletion

### ISSUE THREAD

**Issue by mimez** [handsontable/handsontable#2903]
Hey! I want to create a table in that neither removing of rows nor the deletion of read-only cells is allowed. I wonder how to do that. 

This doc-page describes the disabling of the cell editing feature: 

http://docs.handsontable.com/0.19.0/demo-disable-cell-editing.html

But in any example on this page, you can hit your DEL-Key and a disabled cell gets deleted. Is this behavior intended? 

And how to prevent the deletion of a row? If i select the whole row and hit DELETE the row will be removed.

**Comment by AMBudnik** [comment]
Hi,

with this example http://jsfiddle.net/z9vyq0fo/ you can't use <kbd>DELETE</kbd> to delete `readOnly` cells.

Also in the `contextMenu` option insert/remove row/col was deleted.
