### ISSUE TITLE
Formula SUMIFS doesn't work correctly

### ISSUE THREAD

**Issue by Vertek** [handsontable/handsontable#2904]
hello, i want to use this formula =SUMIFS(N8:N12;D8:D12;C2) in my table but it doesn't work, it return #ERROR. 
For example we have table
|||A  B 
1 a  3
2 a  7
3 b  8
4 b  2
5
6 a (sum a)
7 b (sum b)

I need to calc all columns but group result in a: and b: so i use this formula like this SUMIFS(B1:B4;A1:A4;A6) <= For a values
SUMIFS(B1:B4;A1:A4;A7) <= For b values

Thanks!

**Comment by AMBudnik** [comment]
Confirmed, but please track the [new issue](https://github.com/handsontable/handsontable-ruleJS/issues/21) for that case at RuleJS board. 

This issue will be closed.
