### ISSUE TITLE
Dynamically reducing fixedColumnsLeft to zero breaks sorting

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#2907]
If you have `fixedColumnsLeft` > 0 then reduce it to 0 dynamically, sorting will no longer work on the first column.

This can be reproduced using this [JSFiddle](http://jsfiddle.net/cgatesman/smprt0p1/).
1. Note first column is fixed when scrolling to the right.
2. Note sorting works on first column.
3. Click on "Turn off fixed column 0".
4. Note first column is no longer fixed when scrolling to the right.
5. Note, you cannot sort the first column (blocked by `.ht_clone_left`).

**Comment by AMBudnik** [comment]
I tried to simplify [the code](http://jsfiddle.net/smprt0p1/4/) as much as I could (thought maybe `persistentState` is blocking) but with minimum settings required for this example to work it loses it's ability to be sorted. 

Other cases:
1. When we have `fixedColumnsLeft: 2` at the beginning after setting `fixedColumnsLeft: 0` both columns lose `sorting` ability
2. `fixedColumnsLeft: 0`  acts the same as `fixedColumnsLeft: null`, `fixedColumnsLeft: false`

**Comment by AMBudnik** [comment]
Confirmed with 0.24.0

**Comment by AMBudnik** [comment]
http://jsfiddle.net/j8bknvdp/ Confirmed with 0.26.0

**Comment by AMBudnik** [comment]
Issue still replicable in 0.30.1

**Comment by AMBudnik** [comment]
It's replicable in v`2.0.0` and any version doesn't seem to support it.

**Comment by AMBudnik** [comment]
The issue is no longer replicable. Here's `6.0.1` http://jsfiddle.net/j8bknvdp/

@cgatesman let me know it it works for you as well
