### ISSUE TITLE
Set column size on event

### ISSUE THREAD

**Issue by vallieresc** [handsontable/handsontable#2908]
I use HOT in many pages and some instances have many columns which can make it hard to work with. Full screen view would be ideal but it's not supported it looks like. I am thinking of another solution, making the table position absolute with a backdrop and stretching the columns or setting a width based on a click of a button.

Would this work? 
Do you have a better solution?

**Comment by AMBudnik** [comment]
UpdateSettings does not correspond to all instance settings but changing `colWidths` after a click is a simple as a few lines extra. [Here's](http://jsfiddle.net/4dmmfphm/) the example

**Comment by vallieresc** [comment]
Answered thank you
