### ISSUE TITLE
Row borders out of alignment when using fixedColumnsLeft > 0

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#2909]
I'm not quite sure if this is the same issue as #2354.  When rows wrap and you're using fixedColumnsLeft > 0, the row borders come out of alignment.  I prepared a simple JSFiddle demonstrating it:

http://jsfiddle.net/cgatesman/138vbo89/

![screen shot 2015-10-19 at 3 04 59 pm](https://cloud.githubusercontent.com/assets/6276072/10588187/d0ed684a-7672-11e5-8941-ca5a201e8d3f.png)

You can click on the button to toggle the fixed/frozen column on and off and see that the rows will come into alignment when fixedColumnsLeft === 0.

**Comment by AMBudnik** [comment]
I guess it could be related but it looks little different. Thank you @cgatesman I reproduced it with Firefox (OSX) at Chrome with the same OS it works fine.

**Comment by cgatesman** [comment]
Ah.  Thank you narrowing that down a bit more.  I didn't think to try Chrome at the time (I'm a Firefox guy).

**Comment by kunnix** [comment]
Note that the table renders properly when using `rowHeaders: true`: https://jsfiddle.net/138vbo89/4/

(Tested with Firefox and Chrome on Linux)

**Comment by AMBudnik** [comment]
Thanks for investigating @kunnix

**Comment by AMBudnik** [comment]
still present in 0.27.0, demo: https://jsfiddle.net/LaofLg5q/

**Comment by AMBudnik** [comment]
Still replicable in 0.30.1, demo: http://jsfiddle.net/handsoncode/u43zL8sb/

**Comment by AMBudnik** [comment]
It works the same in v `5.0.1`

**Comment by AMBudnik** [comment]
Issue evolved. Better description at https://github.com/handsontable/handsontable/issues/5735

**Comment by ElixirMike** [comment]
This isn't solved for me. I just downloaded v 8.1.0 and I still have same issue as the original poster did, which is the row alignment . See pic, when first row is frozen, the alignment is slightly off.

![image](https://user-images.githubusercontent.com/34098742/94959217-cfb56100-04be-11eb-8b89-872c63db8772.png)
