### ISSUE TITLE
how can I judge created row through loadData and contextmenu

### ISSUE THREAD

**Issue by sfp12** [handsontable/handsontable#2910]
As the title;

afterCreateRow only has argument about index and amount.

**Comment by AMBudnik** [comment]
Hi, what exactly you would like to know more?
It'll be great if you could show it in [this example](http://jsfiddle.net/2oc2hb3e/)

**Comment by sfp12** [comment]
@AMBudnik  Thank you for your attention. 
In http://jsfiddle.net/2oc2hb3e/12/ , I add afterCreateRow as  option; add minCols and minRows; you can find some output in the console when load page. Actually, the same things will happen when insert row through contextmenu;

how can I listen insert row?

**Comment by AMBudnik** [comment]
Unfortunately as you can see if we have `minCols: value` and a object data source it's not working together - you should use data schema instead. 

When it comes to `afterCreateRow` I tried few ways of showing what you expected but none of them provides desired results. This hook is fired only for contextMenu and hot.alter 

To stay tuned with changing amount of rows (with does from you starting data set) you can choose `countRows()` with `afterRender` but it can lower performance, [example](http://jsfiddle.net/2oc2hb3e/13/)

**Comment by sfp12** [comment]
@AMBudnik  my results is http://jsfiddle.net/2oc2hb3e/16/ . add a variable flag=false, flag=true when afterRender.
we can achive desired results through other ways.
Thanks!

**Comment by AMBudnik** [comment]
Very creative. Glad you worked it out.
