### ISSUE TITLE
Dynamically change size of column

### ISSUE THREAD

**Issue by Vertek** [handsontable/handsontable#2911]
Hello, i need to do some job with table, at start i set colWidths with function, after table is created the columns doesn't resize automatically when text in cell doesn't comparise. I have idea that afterChange event check for me what cell are edited and how long text is it and when i have this information i need to set colWidths again without refresh or create new table. There is something like hot.LOADDATA for loadColWidths? Thanks!

**Comment by Vertek** [comment]
Think i got it at #2908, say if i'm wrong

**Comment by AMBudnik** [comment]
You can try this solution, `colWidths` also uses variables as values like [here](http://jsfiddle.net/4dmmfphm/1/) so it could be easy to manage.

**Comment by Vertek** [comment]
Yep, thanks a lot :)
