### ISSUE TITLE
Issue in Handsontable Horizontal scroll in IE 11

### ISSUE THREAD

**Issue by aurelialeo** [handsontable/handsontable#2912]
Sometimes in IE 11, the horizontal scroll is not working when we scroll clicking the scroll potion under the freezed columns. Also the arrow buttons of scroll also does not work. When we click the scroll area outside the freezed columns, scroll is working fine

**Comment by AMBudnik** [comment]
Could you please provide your OS information? I tried to reproduce it with http://docs.handsontable.com/0.19.0/demo-fixed-rows-and-columns.html under Windows 7 and it works as expected.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.

**Comment by aurelialeo** [comment]
Sorry for the delay. Please take your demo link in internet explorer and scroll horizontally in medium speed. You can see some white spaces. after some time it displays correctly. I am using Win 7 and win 8. In chrome it is not showing any issue.
 I tried with IE8 and IE11

**Comment by AMBudnik** [comment]
Hi @aurelialeo, actually I think it's the same issue as https://github.com/handsontable/handsontable/issues/1761 Am I right?

**Comment by aurelialeo** [comment]
Yes AMBudnik it is the same. I am using 0.16 version. Please give a solution for this as the application is agreed to work with IE11, FF and Chrome

**Comment by AMBudnik** [comment]
When there will be any solution provided https://github.com/handsontable/handsontable/issues/1761 gets updated. 

If you would like to add solution to your v0.16.0 project without updating (it does not guarantee success) you can track changes made with the newest version. For example for [0.20.2](https://github.com/handsontable/handsontable/releases/tag/0.20.2) it's https://github.com/handsontable/handsontable/commit/5a8dc8c1b903a9a8be84f2da25c7b6a85bc1fee5
