### ISSUE TITLE
Horizontal scroll of handsontable is displayed just under the header when there is no data in the table

### ISSUE THREAD

**Issue by aurelialeo** [handsontable/handsontable#2913]
Horizontal scroll of handsontable is displayed just under the header when there is no data. I am using HOT 0.16 version. The scroll was at the bottom of the grid  when i was using 0.12 version. 

Can anybody please confirm whether it is a feature in 0.16v or this is showing for me due to some other css property?

**Comment by AMBudnik** [comment]
Hello @aurelialeo do you use [this kind of code](http://jsfiddle.net/rfge7h5d/) for displaying cols/rows without data? Can you create a demo where this issue occurs?

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.
