### ISSUE TITLE
getLastVisibleColumn() returns last column index and not last visible column index

### ISSUE THREAD

**Issue by nithinmichael** [handsontable/handsontable#2914]
I am having an issue with the scrollToCell functionality of selectCell(). The vertical scroll works as expected but the horizontal scroll does not. On further investigation, it appears that the trouble is that the getLastVisibleColumn() function returns the last column index instead of the last visible column index. Please advise.

**Comment by AMBudnik** [comment]
Could you create a little demo where is issue can be reproducible? Thanks in advance.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.
