### ISSUE TITLE
How can I update the css styling on an entire row/column?

### ISSUE THREAD

**Issue by nithinmichael** [handsontable/handsontable#2915]
Right now, I am able to select a cell and modify the className but I would like to be able to select a row/column at a time.

**Comment by AMBudnik** [comment]
If you can modify a className for `cell(row, col)` you can also do this with a loop for all rows in a column 
`for(var i = 0; i < instance.countCols(); i++) {`
`cell(row, i)`
`}`
or for a column
`for(var i = 0; i < instance.countRows(); i++) {`
`cell(i, col)`
`}`

**Comment by nithinmichael** [comment]
Thank you. I was wondering more whether there was a method I could use instead of writing a loop. Right now, I am using a loop just as you suggested.

**Comment by AMBudnik** [comment]
We're working on making Handsontable more dev and user-friendly so maybe in the future, but now it's the simplest way.
