### ISSUE TITLE
0.10.5 on IE 11

### ISSUE THREAD

**Issue by aprhandson** [handsontable/handsontable#2916]
I am using 0.10.5 on IE 9 which works fine but when I try to launch the page using IE 11 the table is not displayed. Is handsontable 0.10.5 compatible with IE 11? Where can I find a compatibility matrix that shows handsontable versions and browser support?

**Comment by AMBudnik** [comment]
We always encourage to update if possible. Currently we have 0.19.0 version. [Here](https://github.com/handsontable/handsontable/releases) you can check what have been changed and how it can interact with your project.

Do you get any console statements?

**Comment by aprhandson** [comment]
I updated to 0.19.0 version. Below is the code that I am using:

<script src="lib/jquery.min.js"></script>
<script src="dist/handsontable.full.js"></script>
<link rel="stylesheet" media="screen" href="dist/handsontable.full.css">

var origContainer = $('#originalTable');
var origTable = origContainer.handsontable({
        data: originalData
});

The debugger throws below error:
Object doesn't support property or method 'handsontable'

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply for a month.
