### ISSUE TITLE
AutocompleteEditor.sortByRelevance should be overridable

### ISSUE THREAD

**Issue by larvanitis** [handsontable/handsontable#2917]
Hi. I was wondering if there is some reason `sortByRelevance` is not a member of `AutocompleteEditor.prototype` instead of `AutocompleteEditor` itself.

I ask because I am creating a custom editor (extending Autocomplete) and I want to override `sortByRelevance` with a custom function.

Thanks.

**Comment by tdjun** [comment]
I made new cell type which was customized autocomplete.
https://github.com/tdjun/Handsontable-autocomplete2

**Comment by larvanitis** [comment]
I solved this by setting `filter = false` to skip the upstream sorting and I implemented my custom sorting inside my `source` function.

**Comment by AMBudnik** [comment]
@larvanitis this issue can be closed or we could help you with something related to this issue?

**Comment by larvanitis** [comment]
I believe the issue still stands.

IMHO `sortByRelevance` should be overridable so that extending AutocompleteEditor behaviour is easier.

**Comment by yurevich1** [comment]
Unpredictable right now. 
For example, I've sorted countries by my own sort, handsontable resorts the list to non-obvious chain.
if .cellProperties.filter = false, I can see ALL elements of my very long list. It is more usefull if I can see a part of list of my original order.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by AMBudnik** [comment]
Hi all,

As we currently use Github Discussions to discuss new functionalities and changes, please refer to this topic using the new address.

I also encourage everyone interested in the subject to leave their comments.

Thanks!
