### ISSUE TITLE
Copy/Paste ZeroClipboard does not show when used with specific options contextMenu 

### ISSUE THREAD

**Issue by adriennetacke** [handsontable/handsontable#2919]
Please see attached fiddle: 
http://jsfiddle.net/qscyhxk3/

Works as expected when passing default contextMenu option (`contextMenu: true`).

However, once you pass specific options (`contextMenu: ['row_above', 'row_below', 'remove_row']`), Copy/Paste does not show; only the specified options are available.

**Comment by AMBudnik** [comment]
Hi @adriennetacke please track changes to https://github.com/handsontable/handsontable/issues/2853
