### ISSUE TITLE
Bootstrap integration breaks cell alignment

### ISSUE THREAD

**Issue by vinaynaikpro** [handsontable/handsontable#2921]
Whenever you try to integrate handsontable with bootstrap it looses the top heading row alignment as can be seen in  the fiddle. This is near column A
https://jsfiddle.net/Vinay_Naik/p9L05h71/1/

A quick workaround this is to add this line of jquery after you populate the data.

`$('.ht_clone_top').css('left', '');`

**Comment by AMBudnik** [comment]
Hi @vinaynaikpro did you saw our [Bootstrap tutorial](http://docs.handsontable.com/0.19.0/demo-bootstrap.html) with the provided JSFiddle? It has an [example](http://jsfiddle.net/jx4myuye/4/light/) with no misalignment.
