### ISSUE TITLE
Wrapped text with scroll right

### ISSUE THREAD

**Issue by gstenson** [handsontable/handsontable#2922]
There is an issue with wrapped text and scrolling right. If you keep scrolling then row height reverts to single from double.

If you look at the attached fiddle. Highlight wrapped cell and scroll forward a few pages. It will revert to single row height. Tested in FF & Chrome

http://jsfiddle.net/z8f0mrw8/3/

**Comment by AMBudnik** [comment]
Hi @gstenson we have the same issue at https://github.com/handsontable/handsontable/issues/2686 the solution is to use `autoRowSize: true`
