### ISSUE TITLE
Cannot center align checkboxes

### ISSUE THREAD

**Issue by thakursagar** [handsontable/handsontable#2925]
I tried putting className:"htCenter htMiddle" on the checkbox column but it does not center align. When I use my dev tools and put the class on the <td> then it works. Is there any other way to set the alignment for non text columns?

**Comment by AMBudnik** [comment]
Hi @thakursagar HOT get's recalculated after rendering so you should use a custom renderer. [Here](http://docs.handsontable.com/0.19.0/demo-custom-renderers.html) you can read about them.

**Comment by thakursagar** [comment]
So I should not use the existing CheckboxRenderer and should I remove type:"checkbox" from the columns array as I am using a custom renderer? I think there should be a feature which would allow us to use className:"htCenter htMiddle" on checkboxes. Because if I use a custom renderer I would first have to create <input type=checkbox> and then bind the value to my data and then put the styling.

**Comment by AMBudnik** [comment]
Hi, [here's](http://docs.handsontable.com/0.19.0/demo-custom-renderers.html) the place to read about renderers. At https://github.com/handsontable/handsontable/issues/2573 is an issue about this subject.

**Comment by mamapitufo** [comment]
It looks like the `className` property is handled by [`handsontable/src/renderers/_cellDecorator`](https://github.com/handsontable/handsontable/blob/master/src/renderers/_cellDecorator.js#L16-L22), which is used by the text and html renderers. The check box renderer does not use this base functionality provider, nor (as far as I can see) provide its own handler for `className`. This looks like an issue.

**Comment by AMBudnik** [comment]
We will take a closer look, thanks.

**Comment by jianyi0115** [comment]
I meet the same issue:
 http://jsfiddle.net/2ujz42y6/5/

**Comment by AMBudnik** [comment]
As a workaround - like provided here http://jsfiddle.net/9jazk4nu/ - you can access the `CheckboxRenderer` and inject styles directly to `TD` elements handled by this renderer.

**Comment by AMBudnik** [comment]
should be fixed with: https://github.com/handsontable/handsontable/issues/3532

**Comment by AMBudnik** [comment]
fixed with #3532 in Handsontable [0.25.1](https://docs.handsontable.com/0.25.1/tutorial-release-notes.html)
demo: http://jsfiddle.net/fa9zx8mn/
