### ISSUE TITLE
Handsontable --> Checkboxes

### ISSUE THREAD

**Issue by dbergonzi** [handsontable/handsontable#2926]
Hi guys...
I have a Handsontable list ..... On header i have opened (checkBox) with 
 ..."<input type='checkbox' class='selectAll' "...

you can tell me some ideas on how to develop the event that sets the value of "true" of all records of the table?

Many thnks!

**Comment by AMBudnik** [comment]
Hi, [here's](http://jsfiddle.net/qubkt6rz/) an example how it can be achieved.

**Comment by dbergonzi** [comment]
Well.........Very Good solution. 
With your answer i have solved the problem!
I don't understand WHY i can't use solution with ChechBoxes on header of handsontable........but....Ok for Now!

Many Thanks!
