### ISSUE TITLE
Footer?

### ISSUE THREAD

**Issue by cyancdesign** [handsontable/handsontable#2927]
Could there be a handsontable footer?
Something we can use to show totals, but not have to force it into the data set.
Something similar to the header.

We do it now by creating a fake table with totals that aligns with handsontable, but when we want to order, freeze, resize columns on the fly, all the alignments are difficult to control.

**Comment by AMBudnik** [comment]
Hi @cyancdesign Handsontable PRO will provide fixing rows at the bottom. Please check our [to-do list](http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button)

**Comment by cyancdesign** [comment]
When is the projected release of the PRO version?

**Comment by AMBudnik** [comment]
We are planning to release PRO in November. You can be informed by a [subscribe list](http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button#subscribe).
