### ISSUE TITLE
Column Sorting problem

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#2930]
Hello handsontable experts, I just want to sort my column to follow what so called a "Natural Sorting". Like below: 
1
1.1
1.2
1.3
...
1.10
1.11
1.2
1.2.1
1.2.2
...
1.2.10
1.2.11
etc...

Currently sorting is not natural. I found it like the following 
1
1.1
1.10
1.2

Where the 10 comes before 2. helps would be appreciated.....! :)

**Comment by AMBudnik** [comment]
Unfortunately HOT does not provide this type of sorting and it can't be achieved without changing the actual source code.

**Comment by douxlagithub** [comment]
Thank you very much for reply. Actually  I did it in MySQL by utilizing SUBSTRING_INDEX to manipulate the dotted number. But later I had to use SQLite which was not support SUBSTRING_INDEX. So I thought, the final solution was HOT sorting, but no way. thanks again....!
