### ISSUE TITLE
Use input method editor to edit cell and lost first letter.

### ISSUE THREAD

**Issue by billdc** [handsontable/handsontable#2935]
i really love handsontable. i hope someone can help me with this problem.
handsontable cell editor listen the keyboard and when i type a letter , it will trigger the editor.
but when i use an input method , the first letter was lost and captured by the editor.
![image](https://cloud.githubusercontent.com/assets/2860995/10778064/c95aa516-7d5c-11e5-95ca-13caa596c04d.png)
i type "hello" but the ime only captured "ello"

**Comment by AMBudnik** [comment]
Could you please create a demo where this issue is reproducible?

**Comment by billdc** [comment]
thanks for reply.
this picture was captured at http://handsontable.com/
i have to use an input method editor to type Chinese words.
maybe you need to install a Chinese IME.
here is google Chinese IME http://www.google.com/intl/zh-CN/ime/pinyin/

**Comment by AMBudnik** [comment]
OK, this has to be the same issue as https://github.com/handsontable/handsontable/issues/839

**Comment by AMBudnik** [comment]
Please follow #839 for further details.

**Comment by AMBudnik** [comment]
The issue should be solved with #839 in version 0.35.0
