### ISSUE TITLE
Context menu submenu doesn't work

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#2936]
Hi, I tried a solution from HOT contributors on issue #2298 which was implemented like below: 
items: {
      "menu1": { "name": "Display Name" },
      "menu2": { "name": "Display Name2" },
      "menu": { 
             "name": "Submenu Group" 
             "submenu": {
                      "items": {
                              "sub1": {  "name": "Display Sub1 Name" },
                              "sub2": {  "name": "Display Sub2 Name" }
                       }
              }
      },
} 
I don't get it work in HOT 0.19.0 Help please

**Comment by AMBudnik** [comment]
Please do not duplicate issues, issue https://github.com/handsontable/handsontable/issues/2298 is not yet repaired so it's still the main issue for that subject.
