### ISSUE TITLE
Manual column resize does not work when handsontable is loaded inside Bootstrap 3.0 Modal

### ISSUE THREAD

**Issue by rvunnava** [handsontable/handsontable#2937]
Manual column resize does not show the handle on  hover when Handsontable is loaded inside boottsrap 3.0 modal

Note: When Bootsrap Modal is set to 'Show ' then it works fine, but  when it is set to fade and modal loaded on button click or using code the column resize handle does not appear.

JSFiidle for the issue,
http://jsfiddle.net/f0tLzd85/

**Comment by AMBudnik** [comment]
Thanks for sharing.

**Comment by parin95** [comment]
Any fixes or updates?

**Comment by AMBudnik** [comment]
hi @parin95 I really would like to give you any date but now our priority is to fix high priority bugs.

**Comment by parin95** [comment]
@rvunnava Can you perhaps guide me to fix this? My current project relies on this, so I need this. I can submit a pull request if I do manage to fix it.

**Comment by isublimity** [comment]
If change color - can see where "manualColumnResizer"

http://jsfiddle.net/09uh2ysj/3/

**Comment by AMBudnik** [comment]
Currently I do not see any proper workaround however the row movement works as expected so I guess we should check if resizing can be handled the same way.

TIP: the .`manualColumnResizer` element would need to have a `z-index` 100+

**Comment by vicvget** [comment]
To prevent this bug you should override transform: translate to transform: none in css class .modal.in .modal-dialog {}

**Comment by AMBudnik** [comment]
Thank you for the tip @vicvget

**Comment by oyshan** [comment]
Same issue here. Using [react-grid-layout](https://github.com/STRML/react-grid-layout) which positions its tiles using transform-translate. I can't override to transform: none as this will result in my tile being placed wrong.
Any suggestions? Without a fix I can't use manual column/row resize at all, making the component unusable for my case..

**Comment by pmunin** [comment]
still facing this issue, also with React-grid-layout. any updates on that?

**Comment by pmunin** [comment]
I noticed it was working first at react-grid-layout, but stopped when I made a panel display:flex, and the grid's div flex-grow:1

**Comment by AMBudnik** [comment]
Sorry but the issue has not been scheduled yet.

**Comment by mauricionarcizo** [comment]
@oyshan @pmunin try override the ManualColumnResizePlugin.
Just change behavior of function setupHandlePosition and change with the code below:

` this.handle.style.top = ${this.hot.rootElement.offsetTop}px`;
`this.handle.style.left = ${this.hot.rootElement.offsetLeft + this.currentTH.offsetLeft + this.currentTH.offsetWidth - 6}px`;

Tested with grid-layout e worked fine;

I create a gist with this example:
https://gist.github.com/mauricionarcizo/00a7997a15d73eeee1cd8f5729877907

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment]
It works the same in v `6.2.0`

![resize-column](https://user-images.githubusercontent.com/10757813/49723826-17bf2000-fc68-11e8-9dcd-01487d33acc8.png)
![resize-row](https://user-images.githubusercontent.com/10757813/49723828-1857b680-fc68-11e8-9ce1-0ebbd0acbe6c.png)

**Comment by dmaevsky** [comment]
> It works the same in v `6.2.0`
As in "it does _not_ work" ? :)
Having the same exact issue with v6.2.0 trying to use HOT inside a SemanticUI Sidebar.Pusher, most probably for the same reason.

**Comment by AMBudnik** [comment]
> As in "it does not work" ? :)

exactly.

**Comment by wojciechczerniak** [comment]
Housekeeping. We have few issues related to this one. I'm closing this one as a duplicate of #5050. Please track #5050 for further development.

**Comment by AMBudnik** [comment]
Hey @rvunnava @dmaevsky @mauricionarcizo @pmunin @vicvget 

we've just published Handsontable v `7.0.0` were he fix a referred issue https://github.com/handsontable/handsontable/issues/5050
Please update and let me know if it works for you.
