### ISSUE TITLE
duplicate handsontable

### ISSUE THREAD

**Issue by crystalinaching** [handsontable/handsontable#2938]
Hi, I would like to ask, I have found that the plugin handsontable on initiate will auto create multiple table with the class 
 - ht_clone_left handsontable
 - ht_clone_top handsontable

Can i know what do the above table serve as? is it a need?

**Comment by AMBudnik** [comment]
Hi @crystalinaching 
Currently this has to be a part of Handsontable but we are working on a new structure so please stay tuned.
