### ISSUE TITLE
column width after input long text when use an array of objects as a data source

### ISSUE THREAD

**Issue by vit46** [handsontable/handsontable#2944]
Let's see this latest version example, wich is not works like expected:
http://docs.handsontable.com/0.19.0/tutorial-data-sources.html#page-object
In compare to this old 0.15.1 version, which works fine.
http://docs.handsontable.com/0.15.1/tutorial-data-sources.html#page-object

Issue: When use array of objects as a data source, column width is not changing in reflecting the input text length. It's a bug, not a new feature, because when we use array data source, it works like expected.
Thank you!

**Comment by AMBudnik** [comment]
Confirmed. Thanks for sharing @vit46

**Comment by AMBudnik** [comment]
Issue no longer effects the width of columns in v0.24.1
