### ISSUE TITLE
Need context menu position just like PowerTip

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#2946]
Hi, everybody, I implemented custom context menu in my HOT, I made many options that should be listed in the context menu. The problem is when I scroll down the table and then fire up context menu, some of the options I need is disappearing because of the end of the row is not possible to reach the end of the context menu. To get a better uunderstanding, let's  see the following: 
![image](https://cloud.githubusercontent.com/assets/4103210/10872878/5497fca4-8146-11e5-9e81-2a97c65de351.png)
I personally recommend the HOT experts to adopt what [a href="http://stevenbenner.github.io/jquery-powertip/"] PowerTip [/a]  or another Tip jQuery plugins do to make the HOT context menu more accessible.

**Comment by AMBudnik** [comment]
Hi @douxlagithub Can you create a demo for this issue?
I made an [example](http://jsfiddle.net/g0ptnzt0/) with `contextMenu` and a `overflow: scroll` for a big data table and the menu is completely visible.

**Comment by douxlagithub** [comment]
I mean the position of the context menu when it rises up, just to follow the way PowerTip do. Like the following: 
![context_menu_example](https://cloud.githubusercontent.com/assets/4103210/10897367/99f67c70-81fb-11e5-9576-8300454887d5.png)
For example: when we right click on the bottom edge of the HOT. It rises up from bottom, if right clicked on the right edge it rises from the right, and so on...! I'm so Sorry for this, Just to propose idea.

**Comment by AMBudnik** [comment]
I see what you mean. Thanks for idea.

**Comment by darkmavis1980** [comment]
+1
And it was working on older versions (0.14.1), so it would be nice to have this back

**Comment by jansiegel** [comment]
It should be fixed with #3015.

**Comment by douxlagithub** [comment]
Absolutely.... Thank you very much.
