### ISSUE TITLE
Rendering extra (hidden) cells in a resizable container

### ISSUE THREAD

**Issue by chriddyp** [handsontable/handsontable#2947]
My handsontable is in a resizable container. [Here is a demo on Code Pen](http://codepen.io/chriddyp/pen/JYBPQZ).

```html
<div style="resize: vertical; height: 300px; overflow: scroll; width: 300px;">
	<div style="height: calc(100% - 10px); overflow: auto;">
		<div id="table"></div>
	</div>
	<div style="height: 10px;"></div>
</div>
```

When I drag I make my container taller, by dragging, I don't see any of the cells until I release the drag handle:

![image](https://cloud.githubusercontent.com/assets/1280389/10873620/5c5a7e50-80e5-11e5-8cc8-f9009cae2790.png)

Is there anyway to force HOT to render extra, hidden rows so that when you drag-resize the container you see the rows that were previously hidden? It's a bit jarring to resize the container and have to release the drag-handle and wait for an HOT re-render to view the new rows that the resized container contains.

Thanks!

**Comment by AMBudnik** [comment]
codepen example can't handle CSS calc, I get only 13 first rows. After you change the width to px size table shows while dragging the fill handle.

**Comment by chriddyp** [comment]
Hey @AMBudnik - I just changed the height to a `%`: http://codepen.io/chriddyp/pen/JYBPQZ.
The issue that I'm seeing is that resizing the height of the grid container doesn't `rerender` the cells to the new container's size. As a workaround, I was hoping to have the HOT render more (hidden) rows so that expanding the container will show rendered rows. In this example, after expanding, you need to click on the HOT in order for the HOT to re-render.

**Comment by AMBudnik** [comment]
Hi @chriddyp I tried your example with 0.21.0 version where (if I'm getting it right) works as expected. Can you confirm?
