### ISSUE TITLE
Single click on a dropdown fires "onDblClick" function. Is this normal?

### ISSUE THREAD

**Issue by hristod** [handsontable/handsontable#2948]
When double clicking on a cell, I have disabled the editor showing by overriding the "onDblClick" function. This is a project requirement, not my choice :) It all works fine, except on when I single click on a dropdown. Then it fires the event and does stuff it's not supposed to. Is there a reason for this? And if yes - does anyone have an idea how to override this behaviour?

Cheers,
H.

**Comment by AMBudnik** [comment]
Hi @hristod 
Could you create a demo were we can reproduce tis issue?

**Comment by AMBudnik** [comment]
Issue will stay closed till an authors reply.

**Comment by westwingpl** [comment]
Hello i have similiar problem, when i have dropdown field and onCellDblClick hook i can't expand dropdow, even when i click only once.

**Comment by AMBudnik** [comment]
Hi @westwingpl 

I could not replicate the issue. I have tried this demo http://jsfiddle.net/pc7n5fqy/

Can you guide me on how to replicate it (where exactly are you clicking)?
