### ISSUE TITLE
column sorting and formula

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#2949]
hello,
i have an handsontable with columnsorting to yes and  formula.
if i sort the column A, the column B is not sorted, 
http://jsfiddle.net/jeanmarc/663sr199/5/

regards
jm

**Comment by AMBudnik** [comment]
Thanks for sharing @jeanmarc78 Confirmed

**Comment by AMBudnik** [comment]
Here a little different demo: https://jsfiddle.net/s01wm1mv/ provided by @hemantmalpot at #22

**Comment by AMBudnik** [comment]
This issue does not appear in PRO formula plugin http://jsfiddle.net/handsoncode/xt95tedh/
