### ISSUE TITLE
Header content re-render all the time

### ISSUE THREAD

**Issue by marc-antoinepelletier** [handsontable/handsontable#2951]
Hey,

Is there is a way to stop the headers content being re-rendered for every update in the table ? I am using handsontable with angularJS and I am injecting a directive in each header and then compiling it inside the 'afterInit' callback and it works fine.

But the problem is that when you update a cell in the table, the table get re-render (as long as the header) and then I need to compile it again and again to ensure the directive will works which make it terribly slow.. and that is not an option.

Is there a solution somewhere ?

EDIT : Is there is a way to create a custom renderer for the header ? so I can cancel the rendering for some action..

**Comment by AMBudnik** [comment]
We do not recommend stoping rendering in any case, but you can create a custom renderer for header - please check [this example](http://docs.handsontable.com/0.20.2/demo-custom-renderers.html)
