### ISSUE TITLE
how to set first sort order?

### ISSUE THREAD

**Issue by sfp12** [handsontable/handsontable#2952]
when I click column header for sorting. the sort order is true. how to set the false?

Thanks!

**Comment by AMBudnik** [comment]
Hi http://jsfiddle.net/5q653wmj/ on this example you can see that `columnSorting: true` is commented which disables sorting - it's the same as setting `columnSorting: false` in your settings.
When colHeader is clicked once with `columnSorting: true` you get ascending order, and clicked twice descending. With the third click there's no sorting.

More about sorting can be found [here](http://docs.handsontable.com/0.20.0/demo-sorting-data.html)

**Comment by sfp12** [comment]
@AMBudnik  I understand your mean.

my data is mix string and number, so sort by custome function : sort and refresh data. Is there other better way?
I forbid defaultsort : Commented out code：this.sort();    this.hot.render();    this.saveSortingState();
but I want sort marking：triangle top or down.
how could I set sort order that is beforeColumnSort 2th argument ?

**Comment by AMBudnik** [comment]
If you could create a demo of your code, I guess we'll figure it out.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.
