### ISSUE TITLE
sorting column with a local date format

### ISSUE THREAD

**Issue by Scuzzle** [handsontable/handsontable#2953]
Hello,

I want to sort a handsontable with date columns. I'm using Moment.js to set the database-dateformat to the german locale dateformat.

Do you have any idea why it doesn't work in this fiddle:
http://jsfiddle.net/d4dkrhve/

Thank you!
Frank

**Comment by molnij** [comment]
See frediche comment [there](https://github.com/handsontable/handsontable/issues/720)

**Comment by AMBudnik** [comment]
Confirmed with 0.24.0

**Comment by AMBudnik** [comment]
Confirmed with 0.26.0

**Comment by budnix** [comment]
Connected with #3588 and should be fixed with its release.

**Comment by AMBudnik** [comment]
Hi @Scuzzle 
can you check if this issue is still present? 
After fixing the https://github.com/handsontable/handsontable/issues/3588 it should not occur anymore.

**Comment by AMBudnik** [comment]
I am closing this issue as there is no answer for more than 20 days. However if you'd spot something please let us know @Scuzzle
