### ISSUE TITLE
Is it possible to save cell customisations as well as data?

### ISSUE THREAD

**Issue by hellopablo** [handsontable/handsontable#2954]
I know I can get cell data using `getData()` but I'm struggling to find a method which allows me to get that as well as the cell customisations such as alignment, width, etc. 

Is there a method for this? Even if it means having to loop through each and every cell to get meta data? (The `getCellMeta` didn't seem to return the meta I was interested in).

Thanks!

**Comment by AMBudnik** [comment]
Maybe [this example](http://jsfiddle.net/d1fwouz6/) would help. With width it's pretty easy with alignment there could be more than two lines. Every cell that is aligned was given a class:

[`Horizontal: htLeft, htCenter, htRight, htJustify`
`Vertical: htTop, htMiddle, htBottom.`](http://docs.handsontable.com/0.20.0/demo-alignment.html)

now it gives only number or cells with specified class but I guess it won't be a problem to serve it for a specified cell.

**Comment by hellopablo** [comment]
Thanks, I could do something like that but it feels very manual.

Is there not an out of the box way to store the entire state of the table, so I, for example, could save it in a database and then build an HTML table else where?

**Comment by AMBudnik** [comment]
The widths of cols can be served through a function, so it can be brought from a data base as well. 

When it comes to alignment you can try to add a function to overwrite grid's tds but it's more like a workaround than a HOT functionality.
