### ISSUE TITLE
Modifying cell height in dropdown

### ISSUE THREAD

**Issue by WinnieK** [handsontable/handsontable#2955]
Hi.

Experiencing a wrong calculation of dropdown cell height, if i change table cell line height and height. I have changed default <code>22px</code> values to <code>30px</code>

<pre>
.handsontable th,
.handsontable td {
    height: 30px;
    line-height: 30px;
}
</pre>

All good with cells and rows. But when i open dropdown with 2 items, it adds a scrollbar to it and calculates the height as for 22px cell height. Is there any way to fix it?

Here is jsfiddle - http://jsfiddle.net/8tyt7q1k/

Thanks

**Comment by AMBudnik** [comment]
It's better to use `rowHeights` like [`rowHeights: 30`](http://jsfiddle.net/8tyt7q1k/1/) for all cells.

**Comment by WinnieK** [comment]
This is not a solution unfortunately, because i want to increase height of all cells, in dropdown as well.
I found out that library ignores CSS styles for calculating the height and uses static <code>23px</code> inside JS code. Would be nice to have CSS-only dependency.

Second issue - is there any point in width difference of dropdown table and dropdown container? There is a <code>4px</code> difference, which is bigger than original cell width. There is a quick fix in JS code, just want to be sure it is really needed.

Thanks

**Comment by AMBudnik** [comment]
We are aware of hard work that has to be done with styling Handsontable. It'll take a long time while the code associated with widths, heights and alignment is seen in nearly every .js file.

As a solution I can offer [this example](http://jsfiddle.net/7Lgm6gsn/1/) it does not use dropdown but a handsontable cell type (more about this cell type [here](http://docs.handsontable.com/0.20.0/demo-handsontable.html))

**Comment by WinnieK** [comment]
Thanks, i got it. Although i believe would be great if you can add an option like 'cell_width' and 'cell_height' if it can't be done via CSS. I've changed a couple of default values ("23") in the library code and all good for now. Please consider it in future updates.

Thanks for such a great library!
