### ISSUE TITLE
Cell editor on Android devices

### ISSUE THREAD

**Issue by yurevich1** [handsontable/handsontable#2956]
This is hardly difficult to edit any data into a cell on mobile Android device.
As I found , the editor appears after double click on an item, but after that the device keyboard occurs on the screen, and the editor dissapears (and keyboard after that). How to fix it?

**Comment by AMBudnik** [comment]
Hi @yurevich1 we already have a similar issue https://github.com/handsontable/handsontable/issues/3 it's a feature request. Currently HOT is not full mobile-friendly which we are aware of.

For more information about when and how it will be solved, please follow https://github.com/handsontable/handsontable/issues/3
