### ISSUE TITLE
Merged cells and getData()

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#2958]
getData() should serve merged cells data.

Steps:
1. Go to http://jsfiddle.net/o6uos0wn/
2. Use contextMenu to merge cells (doesn't matter which ones)
3. Click `check` button to see getData() result

Result:
Source data insteadofo merged cells data.

**Comment by YakovL** [comment]
What is expected behaviour? If I merge A1 and B1? I'd say it should be `[["A1","","C1",...]...]`, but I may imagine another way of handling this: `[["A1","C1",...]...]`. The first approch looks safer for backward compability, what would you say?

**Comment by AMBudnik** [comment]
Hi @YakovL 

If you merge `A1` and `B1` 

![image](https://user-images.githubusercontent.com/10757813/28258842-a7d84c16-6ad3-11e7-894a-d6ed2a4a2e99.png)

you are giving the `A1` value for both cells, so I would see the data as `['A1', 'A1', 'C1', 'D1', ...]`

The first option `[["A1","","C1",...]...]` may be acceptable as well but skipping the value like in the second case  `[["A1","C1",...]...]` will mean the same as returning nine cells in the first row while having ten in the rest of the rows, which could end up being a cause of some serious calculating issues.

**Comment by YakovL** [comment]
Yeap, I was asking only because `[["A1","C1",...]...]` rang a bell of possible issues to me. `[["A1","A1","C1",...]...]` is totally acceptable, it is fine for calculations in a direction perpendicular to the merging (if it's in one dimension) but one have to watch out while calculating (say, a sum) in the direction of merging, which seems a lesser evel.

**Comment by jansiegel** [comment]
After the changes in #4214, in this case:
![image](https://user-images.githubusercontent.com/7397134/31660292-45da41c0-b337-11e7-9043-2c08184cc8f4.png)
`hot.getData()` returns `null` for the cells cleared by the merge, so:
```js
[
   ["A1",null,"C1","D1","E1","F1","G1","H1","I1","J1"]],
   // (...)
]
```

**Comment by jansiegel** [comment]
Should work fine in `0.37.0`.
