### ISSUE TITLE
Invalid cell not shown as invalid on load

### ISSUE THREAD

**Issue by thbar** [handsontable/handsontable#2959]
If I provide invalid data when instantiating Handsontable, the cell won't paint in red. I wrote a small reproduction here:

http://jsfiddle.net/q92om1w2/3/

I have to either edit the invalid cell manually once, or force a refresh using the programmatic trick provided in #1912 (see [comment](https://github.com/handsontable/handsontable/issues/1912#issuecomment-76401810)).

Another technique which I found to apparently work is to do:

```coffeescript
    setTimeout ( =>
      @hot.validateCells () => @hot.render()
    ), 0
```

Is this a bug? Is there a recommended work-around to make sure the validation will occur? (maybe using a proper hook? I tried `afterInit` but it didn't seem to work).

**Comment by AMBudnik** [comment]
We decided it should work this way. If you would like to validate cells after loading data, [here's](http://jsfiddle.net/q92om1w2/4/) the example you can use. 

ps. we use `dateFormat` not `format`

**Comment by thbar** [comment]
@AMBudnik I tried applying your fiddle but in my case it still didn't work (unlike in your fiddle!). I investigated a bit more and apparently, the technique does not work because I'm using `columnSorting: true`.

I [updated my fiddle here](http://jsfiddle.net/thbar/0a3wcsu6/2/) to show a new reproduction.

Is there a recommended way to make this work together with `columnSorting`?

Re: `dateFormat` good catch! This is what I was using in my own code, I made an error writing the fiddle.

**Comment by AMBudnik** [comment]
It a bug. `columnSorting` should not block cell validation.

Steps to reproduce:
1. Go to http://jsfiddle.net/q92om1w2/6/
2. Result panel, data is wrong (370 days) but it's NOT highlighted,
3. Comment `columnSorting`
4. Refresh code
5. Validation works, 370days is not a valid value and it's highlighted.

**Comment by thbar** [comment]
Thanks for the quick update! I'll use my work-around for now.

**Comment by wham12** [comment]
I was just fighting with this bug - glad to see somebody else has stumbled across it as well.
@thbar can you explain better (or add to the fiddle) your workaround with the setTimeout? I would like to implement that one, but have not been able to get it working for me.

**Comment by thbar** [comment]
@wham12 I [forked my fiddle](http://jsfiddle.net/thbar/zvdujxzt/1/) and added the work-around at the bottom with a comment.

**Comment by wham12** [comment]
@thbar Thanks, that's exactly what I needed!

**Comment by AMBudnik** [comment]
works as expected in v0.24.1, demo: http://jsfiddle.net/q92om1w2/7/
