### ISSUE TITLE
rowHeights bug

### ISSUE THREAD

**Issue by nicebro** [handsontable/handsontable#2964]
Hello, i found a bug when setting height for the rows, if specified value zero or null then after 1000 rows occurs Security brake: Too much TRs.... but when value set to undefined everything is fine.
Demo: http://jsfiddle.net/mrj6z35j/

**Comment by AMBudnik** [comment]
@nicebro thanks for sharing. We have to take a closer look at these one.

**Comment by AMBudnik** [comment]
updated to 0.23.0: http://jsfiddle.net/mrj6z35j/2/

**Comment by AMBudnik** [comment]
Issue can be closed.
Currently we are only showing a performance tip - not an error:
Demo: http://jsfiddle.net/aLn734nu/
