### ISSUE TITLE
"Non-editable specific cells" feature doesn't work anymore

### ISSUE THREAD

**Issue by WinnieK** [handsontable/handsontable#2965]
Hi.

Just want to report <a href="http://docs.handsontable.com/0.20.0/demo-disable-cell-editing.html#page-cells">Non-editable specific cells</a> example doesn't work in 0.20.0 version (cells with "Nissan" are still editable), but works in 0.19.0. The same is for read only cells.

[Update] Figured out - need to use <code>getSourceData()</code> instead of <code>getData()</code>

Thanks

**Comment by AMBudnik** [comment]
Thanks for sharing @WinnieK

**Comment by budnix** [comment]
Fixed. [Docs](http://docs.handsontable.com/0.20.0/demo-disable-cell-editing.html#page-cells) have been updated.
