### ISSUE TITLE
Handsontable column overlapping with the footer

### ISSUE THREAD

**Issue by aleramesh** [handsontable/handsontable#2967]
![selection_035](https://cloud.githubusercontent.com/assets/11079913/11039029/cf1eee14-86d3-11e5-8c86-4df216fd68a6.png)

I know there are so many overlapping issues reported by other users but mine looks bit different as the first column of the table is overlapping with the footer.

Could somebody help me on fixing this?

**Note:** I am using the latest version.

Thanks

**Comment by AMBudnik** [comment]
@aleramesh please create a demo that provides the issue shown above. What's yours OS/Browser? (It looks like a IE for me.)

**Comment by deterdangler** [comment]
@AMBudnik Thanks for the response. 

I was able to resolve it by adding z-index for the footer. For now it looks fine. Thanks!

**Comment by AMBudnik** [comment]
So it was a CSS issue with other elements on your page? I'm asking to be sure, it's not a Handsontable issue.
