### ISSUE TITLE
Handsontable v0.20.0 has 'SCRIPT1028: Expected identifier, string or number' error on Internet Explorer 11

### ISSUE THREAD

**Issue by jborelli** [handsontable/handsontable#2968]
Handsontable v0.20.0 has 'SCRIPT1028: Expected identifier, string or number' error
! on Internet Explorer 11:
JavaScript critical error at line 127, column 336 in http://localhost:52847/FonteSAP2/Entire.Schneider.Web/Scripts/handsontable/handsontable.full.js\n\nSCRIPT1028: Expected identifier, string or number

On Mozila Firefox and Google Chrome I dont have this error.

![githubhandsontable](https://cloud.githubusercontent.com/assets/15739909/11043172/8f0eba3c-8702-11e5-80bb-1bf6ff172c6f.jpg)

**Comment by AMBudnik** [comment]
Hi @jborelli can you create a demo where this issue is reproducible? I couldn't reproduce it with handsontable.com and on my localhost.
