### ISSUE TITLE
computing formulas with `plugin.matrix.getItem` are sometimes returns an undefined value

### ISSUE THREAD

**Issue by chriddyp** [handsontable/handsontable#2969]
I'm using formulas and from https://github.com/handsontable/handsontable/issues/2645#issuecomment-122220500, I compute the value of the cell with:

```
computedCell = hotInstance.plugin.matrix.getItem(hotInstance.plugin.utils.translateCellCoords({row: 1, col: 1}))
```

Sometimes, `computedCell` is undefined. In particular, when I use the `fillHandle` to drag `~20` cells:

``` javascript
var container = document.getElementById('table');

var hot = new Handsontable(container, {
    data: [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15]],
    minCols: 10,
    formulas: true,
  fillHandle: true, 
    contextMenu: false,
    colHeaders: true,
    rowHeaders: true,
    fixedRowsTop: 0,minRows: 200,
    afterChange: function(changedCells, source) {
            console.warn(source, 'changedCells: ', changedCells);
            if(source === 'alter' || source === 'edit' || source === 'autofill') {
                changedCells = JSON.parse(JSON.stringify(changedCells));
                var rowi, coli, newVal, computedVal;for(var i=0; i<changedCells.length; i++) {
                        rowi = changedCells[i][0];
                        coli = changedCells[i][1];
                        newVal = changedCells[i][3];
                        if(newVal.toString().indexOf('=') > -1) {
                                computedVal = this.plugin.matrix.getItem(
                                        this.plugin.utils.translateCellCoords({row: rowi, col: coli})
                                );
                                if(computedVal) {
                                        console.log('computedVal.value: ', computedVal.value);
                                } else {
                                        console.error('computedVal is undefined!? newVal: ', newVal);
                                }
                        }
                }
            }
    }});
```

Is this still the recommended way to evaluate the computed cells?

**Comment by chriddyp** [comment]
here is a screenshot of the console: 
![image](https://cloud.githubusercontent.com/assets/1280389/11048081/cad50dd6-8703-11e5-9e39-4f13900750df.png)
and the accompanying codepen: http://codepen.io/chriddyp/pen/ojQNXG

**Comment by AMBudnik** [comment]
Hi @chriddyp what are exact steps to reproduce this behaviour?

**Comment by chriddyp** [comment]
Hi @AMBudnik :

1 - Open up the code pen
2 - Open up the console
3 - Drag column A down to 200 cells
4 - Enter a formula in column B1, like "=A1*5"
5 - Drag B1 down to row 200.
6 - Observe the console for errors: You should see messages like `computedVal is undefined!? newVal:  =A199*5` which demonstrate this bug.

Here is a youtube video screencast going through steps 1-6: https://www.youtube.com/watch?v=IstOqnqhzLs

**Comment by AMBudnik** [comment]
Hi, it has something to do with your `afterChange`, in [this example](http://jsfiddle.net/5vdgjsp8/) just removed `afterChange` and added few Rule-JS sources and it does not provide an error.

**Comment by chriddyp** [comment]
Hi @AMBudnik - Got it. Is there some alternative to `afterChange` that I can use to extract the computed data from the table after the user has made an input change? Or, am I using `afterChange` in the wrong way?

**Comment by AMBudnik** [comment]
You can use `getData()` or `getDataAtCell(row, col)` anytime you want but for changes it's only `beforeChange` to prevent some action and `afterChange` to do something what depends on the result.

**Comment by chriddyp** [comment]
Thanks @AMBudnik ! OK, that's I'm doing: using `afterChange` to compute the formula to do something that depends on the result. So, it seems like this is a bug with `afterChange` or formulas? Sorry if I'm missing something here!

**Comment by AMBudnik** [comment]
It can be, I'll mark it for other team members to look at in spare time.

**Comment by chriddyp** [comment]
Thank you @AMBudnik !

**Comment by krzysztofspilka** [comment]
@chriddyp something's wrong with the lazy loading, haven't checked it yet. Try using the latest version of Handsontable (0.20.2) plus add to the config: renderAllRows: true. An ugly workaround, true, but for the development process it should do the job (at least for small data sets).

**Comment by jackparmer** [comment]
Hey @krzysztofspilka ! Any chance this one can get bumped up in priority? We'd really *love* to get Handsontable formulas on our production version of Plotly but this is holding us back at the moment. Let me know how we can help!

**Comment by AMBudnik** [comment]
Currently we are refactoring formulas. Take a minute to check our roadmap: 
https://trello.com/c/z0QvwlNj/11-full-formula-support-as-a-plugin

**Comment by jackparmer** [comment]
Can we leave this open until the refactor is done and we can confirm it does indeed fix this?

**Comment by AMBudnik** [comment]
sure @jackparmer

**Comment by wojciechczerniak** [comment]
Since this issue was created we've changed the formula plugin. Not relevant anymore.
