### ISSUE TITLE
Double scroll on resize

### ISSUE THREAD

**Issue by fbrussa** [handsontable/handsontable#2970]
Hi, this occurs when you resize the table in chrome. It seems to be a bug.

http://jsfiddle.net/0xdnwf82/2/

**Comment by AMBudnik** [comment]
Hi, what exactly you would like to achieve? I think that we can find a solution.

**Comment by fbrussa** [comment]
Hello.
I use handsontable within a resizable area. So when resizing the container, I need to adjust the size of the table.

Look at this picture so you see better.
http://share.pho.to/9rr8b

Thank you

**Comment by AMBudnik** [comment]
Hi @fbrussa did you tried to add another div with `overflow: hidden`?

**Comment by fbrussa** [comment]
Hi, I tried this: http://jsfiddle.net/0xdnwf82/4/

But I still see strange behavior, especially in chrome.

**Comment by AMBudnik** [comment]
Yes, when the area for instance is too small it's impossible to use scroll. It occurs on Windows (OSX not affected). There is only a ability to move by arrow navigation.

**Comment by fbrussa** [comment]
It does not happen only with small area. This occurs also in a big area
http://jsfiddle.net/0xdnwf82/5/
This resize action working fine in version 0.13 (my prior version). 
I update to 0.20 and look this strange behavior,

**Comment by AMBudnik** [comment]
confirmed with 0.24.1 http://jsfiddle.net/0xdnwf82/6/
There's an extra vertical transparent scroll after choosing `resize 2` button

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by wojciechczerniak** [comment]
@AMBudnik Can you replicate this issue in `v7.0.0` http://jsfiddle.net/p0Lc9nfa/ ?

**Comment by AMBudnik** [comment]
Works well for me in 7.0.0 @wojciechczerniak 
I think that we can close the issue.

@fbrussa please update and let us know if it works for you. If not, we'll reopen the ticket.
