### ISSUE TITLE
Using the "data" attribute in the "columns" config of a handsontable instance

### ISSUE THREAD

**Issue by chiman24** [handsontable/handsontable#2971]
There seems to be a problem when using the "data" attribute in the "columns" config of a handsontable instance.

I've written some code that changes the background color of a cell when its value has been edited and changed.  The program works as expected when the data source is an array of arrays and columns are defined like this:

columns [
 {type: text}
]

However, when the datasource is an array of objects and columns are defined like this:

columns [
 {data: "id"}
]

it doesn't work.  Is this a bug, or am I doing something wrong?  Please see the jsfiddles below

Working example:
http://jsfiddle.net/chiman24/3o2c3c7m/

Not working:
http://jsfiddle.net/chiman24/24mpavga/

**Comment by budnix** [comment]
Hi, when you use data source as an array of objects then in afterChange hook you got column index as property not as index. In this case you must translate it to numerical column index like this `hot.getCellMeta(2, hot.propToCol(columnIndex));`. Updated [demo](http://jsfiddle.net/24mpavga/8/).

**Comment by chiman24** [comment]
@AMBudnik Thanks so much!

**Comment by AMBudnik** [comment]
@chiman24, @budnix did the great demo, but I'll share him your answer :-)

**Comment by chiman24** [comment]
Oops... sorry :-) Thanks @budnix

**Comment by chiman24** [comment]
Issue resolved.  Closing.
