### ISSUE TITLE
validation after insert

### ISSUE THREAD

**Issue by molnij** [handsontable/handsontable#2972]
Goto http://docs.handsontable.com/0.20.0/demo-data-validation.html
Enter invalid ip-address to first line. E.g. "0.0.d.1"
Open console, add new row: hot.alter('insert_row',0)

Row added, validation still on first line. 
![image](https://img-fotki.yandex.ru/get/16159/10911953.22/0_d649a_9dc112ec_orig.png)
It's normal?

**Comment by AMBudnik** [comment]
related to https://github.com/handsontable/handsontable/issues/2114
