### ISSUE TITLE
Paste does not work after using updateSettings

### ISSUE THREAD

**Issue by bwyss** [handsontable/handsontable#2973]
Possibly related to issue #2919

Paste does not work after using updateSettings

Working workflow:
1. Render a table.
2. Single click a cell and paste tab separated values.

Brocken workflow:
1. Render a table
2. Update the column headers with updateSettings eg:
        hot.updateSettings({
            colHeaders: myNewHeader
        });
3. Single click a cell and paste tab separated values (NOT WORKING)

**Comment by AMBudnik** [comment]
Hi, correct me if I'm wrong. I made [an exmple](http://jsfiddle.net/39q1kb32/) for this case and it seems to work the same before and after headers update.

**Comment by bwyss** [comment]
Thanks for the prompt reply, you are right it works.
I modified your example to include a dropdown selection menu (to match more closely my application) 
[Updated Example]
(http://jsfiddle.net/48cwtL4q/)
So now the workflow in the example is:

1. Make a selection from a dropdown menu (in my app, this is used to select an element to be used in the table header)
2. Listen for a change event and generate a table
3. Paste values into the table (NOT WORKING)

**Comment by AMBudnik** [comment]
I changed this code a bit, updated [demo here](http://jsfiddle.net/48cwtL4q/1/) it works with `tab` but you have to unfocus the dropdown and paste with first click (without entering the edit mode)

**Comment by bwyss** [comment]
Thanks for the help with this. I decided to implement a button event after the user makes a selection from the dropdown menu, not idea but ok for now.
Do you have any idea what's causing this?

**Comment by AMBudnik** [comment]
I guess that maybe it has something to do with https://github.com/handsontable/handsontable/issues/2961
