### ISSUE TITLE
Remove Pikaday and Moment dependencies when not using included dateEditor

### ISSUE THREAD

**Issue by gregriley** [handsontable/handsontable#2974]
I saw the answer to issue #2841 and I was wondering if you can update handsontable to not require pikaday and moment when the dateEditor is not being used?

**Comment by AMBudnik** [comment]
Currently code construction does not allow to remove above scripts from dependencies

**Comment by istarnx** [comment]
You guys have an awesome library--thank you! I just want to add that I second this motion. It might increase your adoption rate to refactor such that the code that uses these dependencies are plugins to Handsontable.

**Comment by AMBudnik** [comment]
Thanks for reply @istarnx

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by WorldMaker** [comment]
A related suggestion would be to use a smaller, easier to tree-shake, date library dependency such as [date-fns](https://date-fns.org/) or [Luxon](http://moment.github.io/luxon/).
