### ISSUE TITLE
remove row undo, remove column undo

### ISSUE THREAD

**Issue by vit46** [handsontable/handsontable#2975]
http://docs.handsontable.com/0.20.0/tutorial-callbacks.html
1. afterCreateRow - not fires when ctrl+z or undo when row was removed.
2. afterCreateCol - not fires when ctrl+z or undo when column was removed.
afterChange is not fires too in both circumstances, though data is actually changed, i.e. there is no way to handle such events.

**Comment by AMBudnik** [comment]
Hi, we have the same issue at https://github.com/handsontable/handsontable/issues/2577. 

Please follow https://github.com/handsontable/handsontable/issues/2577 for updates and if needed add suggestions.

Thanks in advance!
