### ISSUE TITLE
Change regex for numeric validator

### ISSUE THREAD

**Issue by molnij** [handsontable/handsontable#2976]
Current numeric validator is regexp /^-?\d*(\.|\,)?\d*$/
try in console:
/^-?\d*(\.|\,)?\d*$/.test('-')
true
/^-?\d*(\.|\,)?\d*$/.test(',')
true
/^-?\d*(\.|\,)?\d*$/.test('.')
true
/^-?\d*(\.|\,)?\d*$/.test('+2')
false

oops..

I use /^(-|\+)?((\d+((\.|,)\d*)?)|((\.|,)\d+))$/ ,but not garantee 100% correctly

**Comment by AMBudnik** [comment]
Thanks for suggestion @molnij

**Comment by molnij** [comment]
in first comment markdown parser break regex (remove backslash)
correct: /^(-|\\+)?((\d+((\\.|,)\d*)?)|((\\.|,)\d+))$/

**Comment by jansiegel** [comment]
@molnij, Your regex accepts `1.` for example, I'm not sure if we want that.
I simplified it a little bit to `^(-|\+)?(\d*(\.|,)?\d+)$`

What do you think @molnij, @budnix?

**Comment by budnix** [comment]
@jansiegel first regex is a better option (^(-|\+)?(\d*(\.|,)?\d+)$). Evaluating `var foo = +5;` or `var foo = +.9` gives you still a valid numbers so I think it's correct approach.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
