### ISSUE TITLE
Copy and pasting % data from excel causes formatting issues

### ISSUE THREAD

**Issue by mburbea** [handsontable/handsontable#2977]
If I have a cell set up with format `0.00%`, and I paste a value from excel like `3.5%`, the cell is highlighted red and the value is considered invalid.

However, if I change the value to be `0.035` then I can paste the value and is correctly understood.
This is problematic as my users would like to paste data directly in from excel without having to change the format.

**Comment by AMBudnik** [comment]
Hi, your can choose to use `text` cell type. It won't highlight.

**Comment by mburbea** [comment]
I disagree that this is a satisfying answer as then the value is saved as a string, and isn't saved as a number with value `0.035`, but as the value `'3.5%'`. This means that if I want to do math with the value entered, I have to convert it to a number myself.

**Comment by AMBudnik** [comment]
Hi @mburbea this label 'answered' it's only to let anyone know it's been picked by someone.

Percent is not a number and we don't provide calculations for it, but I can add it as a feature request.

**Comment by AMBudnik** [comment]
This issue is strongly related to https://github.com/handsontable/handsontable/issues/3067
Please track changes to https://github.com/handsontable/handsontable/issues/3067 for updates.
