### ISSUE TITLE
Getting Uncaught Error: row 8 does not exist while trying to access a element in the handsontable

### ISSUE THREAD

**Issue by rohit0662012** [handsontable/handsontable#2978]
When i fill Data in handsontable and click the button Getdata in the attachment then i will get the data of the handsontable in Json Format and prints in console after that if i try to access any cell in the handsontable i am getting above error

the  ScrollViewport	@	handsontable.full.js:2436 is pointing to code

if (coords.row < 0 || coords.row > totalRows - 1) {
      throw new Error('row ' + coords.row + ' does not exist');
    }

I am using the latest version of handsontable,the error is  a bug ?

My java script code:
jQuery(document).ready(function(){
                
                var data = [];
                var container = document.querySelector('#exampleGrid');
                
                var han ;
                
                    
                       
                han = new Handsontable(container, {
                    data : data,
                   
                    colHeaders: ['SourceIP_Type','Source Ip','DestinationIP_Type','Destination Ip'],
                    
                    

                    
                    columns: [
                    {type: 'dropdown',
                     source: ['IP_Address','IP_Range']},
                    {data:'SourceIP'},
                    {type: 'dropdown',
                     source: ['IP_Address','IP_Range']},
                    {data:'DestinationIP'}],
                    
                    
                    minSpareRows: 1,
                    
                    
                    rowHeaders: true,
                    
                    contextMenu: true,
                   
                    manualColumnResize: true,
                    manualRowResize: true,
                    mergeCells : true

                });

           

                jQuery('button').on('click',function(e){
                    
                    
                    
                    var arr = han.getData();
                    
                    for(k=arr.length-1;k>-1;k--)
                    {
                        if((Object.keys(arr[k]).length)==0)
                        {
                            arr.pop();
                        }else
                        {
                            break;
                        }
                        
                    }
                    
                     
                    console.log(JSON.stringify(arr));
                    
                    
                    
                    
                });
            });

my html code:

<div id="exampleGrid" class="dataTable"></div>
	<button>Get Data</button>

**Comment by rohit0662012** [comment]
If you want a demo i am having a jsFiddle link but  i am  new to jsFiddle and i dont know how to include Handsontable js and css files so if any one can edit please 

https://jsfiddle.net/rk6612/qcezcdhu/

**Comment by AMBudnik** [comment]
I updated your demo [here](https://jsfiddle.net/qcezcdhu/1/) and I can't get the console errors.

Please guide me how I can reproduct this behaviour step by step.

**Comment by rohit0662012** [comment]
There is error in console 
Uncaught ReferenceError: Handsontable is not defined

are you able to see table after edit?

**Comment by rohit0662012** [comment]
So after fixing it write some data in Handsontable and click on get data button after that try to access(or edit or touch) any cell in handsontable then you will get this error
Uncaught Error: row 8(or any number) does not exist

**Comment by AMBudnik** [comment]
Hi, [here's](http://jsfiddle.net/qcezcdhu/1/) the same code without https protocol. Can't get `Uncaught ReferenceError: Handsontable is not defined` now.

**Comment by rohit0662012** [comment]
But in my browser i am getting the error i mentioned but i am not getting the error now in jsFiddle

**Comment by AMBudnik** [comment]
@rohit0662012 so please update the demo, that I can get the same console error that you have. Without this it will be hard to say anything.

**Comment by rohit0662012** [comment]
So i got the reason for error if you include the Handsontable js files and css files via url's you dont get the error but if you include the as a files in the local directory files then you will get that error 

Actually i am including Js and css files from my local directory i downloaded using brew

**Comment by AMBudnik** [comment]
Only thing I can recommend is to download files from server and again and check your file paths.

**Comment by rohit0662012** [comment]
File paths are correct as it is working till i use han.getData();

**Comment by AMBudnik** [comment]
Unfortunately I am not able to help you if it does not work only at your local

**Comment by rohit0662012** [comment]
If i type bower -v handsontable
i am getting  - 1.6.5

is this version

**Comment by rohit0662012** [comment]
The bug is in v 0.19 its been removed in 0.20

**Comment by AMBudnik** [comment]
Thanks for sharing the update @rohit0662012 can we close this one or you have any related issue updates?

**Comment by rohit0662012** [comment]
https://github.com/handsontable/handsontable/issues/2983

**Comment by rohit0662012** [comment]
Can i know when will this issue will be  resolved in v-0.19 as v-0.20 is having so many bugs not working as of v-0.19

**Comment by AMBudnik** [comment]
After investigation `hot.getData()` in your code worked in 0.20.0 and not in 0.19.0 cause it changed it's returned values. 

Why you want to use `pop`? It causes `Uncaught Error: row 0 does not exist` 
If you want to use it call `hot.render()` like [here](https://jsfiddle.net/qcezcdhu/4/)

**Comment by rohit0662012** [comment]
no i was asking when will this issue get resolved in v-0.19  please see the error in js fiddle given

http://jsfiddle.net/rk6612/qcezcdhu/6/

in v - 0.19 once ie i click get data button and after that if i try to access any row i am getting below error 

Uncaught Error: row 1 does not exist

when will this bug get resolved in v - 0.19

**Comment by AMBudnik** [comment]
@rohit0662012 we do not fix versions that are older. We fix issues while releasing new version.
