### ISSUE TITLE
Sort and scroll

### ISSUE THREAD

**Issue by molnij** [handsontable/handsontable#2979]
(sorry for my english)
Demo:
goto [demo sample](http://jsfiddle.net/1vgm0L1a/)  (your advanced sample with activate sorting)
set width around 400px to frame with table (to show horizontal scroll)
Scroll to max right position. Click "1YChg" column header to sort it. 
Scroll to left slight. Click again to header "1YChg". 
Is see next incorect sort
![screen](https://img-fotki.yandex.ru/get/6210/10911953.22/0_d65e1_16e53638_orig.png)
(engine make sort at column "Level")

Solution:
bug in [columnSorting.js](https://github.com/handsontable/handsontable/blob/master/src/plugins/columnSorting/columnSorting.js)

sort function fill sort array: (line 339 at now)
	this.hot.sortIndex.push([i, this.hot.getDataAtCell(i, this.hot.sortColumn + colOffset)]);

but up to stack in event listener (line 201) define sort column:
  let col = getColumn(e.target);

early version getColumn:
return dom.index(TH) - countRowHeaders();

at now getColumn:
return _this.hot.view.wt.wtTable.getFirstRenderedColumn() + index(TH) - countRowHeaders();

Now is not needed adding colOffset in filling sort array.

**Comment by stesix** [comment]
This is the fix: https://github.com/handsontable/handsontable/pull/2890
This is the original issue: https://github.com/handsontable/handsontable/issues/542

**Comment by AMBudnik** [comment]
Thank you @stesix 
@molnij please track changes to https://github.com/handsontable/handsontable/issues/542
