### ISSUE TITLE
NPM support?

### ISSUE THREAD

**Issue by aft-luke** [handsontable/handsontable#2980]
I'm so confused as to how to get this into my application without manually inserting a script into index.html like it's 2005. Can this be published to NPM in a pre-compiled, no-transforms-required, commonjs friendly module?

I can't use use browserify because there is es6 code inside the `/dist` that hasn't been transpiled. I can't use babelify to transpile that es6 code to standard ECMA code because the transpilation doesn't happen unless the `package.json` has a `"browserify": { "transforms": [] }`. I can't even manually modify the `package.json` to add my own transform directive because it *still* fails out with `Error: Cannot find module '../browser' from 'handsontable'`. I can't use `hot-builder` to make my own build because I get `Module zeroclipboard not found`. I can't download the full zip, `npm install`, install `grunt-cli`, and run a full dist build locally because `Module zeroclipboard not found`. At this point I'm just not going to use this library, despite its rich feature-set that is better than a lot of alternatives...

It would be great if this library could play nicely with the module systems of modern web development and avoid embedding other libraries in its distribution. A simple NPM module with `peerDependencies` would solve all of these problems.

**Comment by AMBudnik** [comment]
Hi @aft-luke we have this on our to-do list. For further information please track changes to https://github.com/handsontable/handsontable/issues/2906

**Comment by budnix** [comment]
@jansiegel To test this issue please use this branch https://github.com/handsontable/hot-builder/issues/16.

**Comment by krzysztofspilka** [comment]
Difficult to test it before the release. I think we should mark it as "tested" and open a new issue if any new problems pop up.
