### ISSUE TITLE
Hide a column but have the data in the background for accessing

### ISSUE THREAD

**Issue by rameshkarunakaran** [handsontable/handsontable#2981]
I have 10 columns (C1, C2...C10) in the data array. What I want is to have all the columns in the background but display only C1 to C5 to the user. The reason: In the validations part, I need to have these hidden fields to find whether the values typed in visible columns are valid or not. I am using javascript on a buttonclick outside the handsontable definition for these validation.

What I did currently is to define the data array with values for ALL 10 columns and while defining the new handsontable statement, used columns [ ] tag to display only the columns to be visible. (In the columns section, I have inserted only C1 to C5 and did not include C6 to C10). Now the problem is that, when In used .getData() to get the dataset, the hidden columns (on other words the columns not included in the columns [ ] tag of the handsontable definition) are coming as undefined, when accessing using 

var gettablearray = handsontable1.getData();
window.alert(gettablearray[rowindex][columnindex]);
I am able to get the values for the visible columns.

Is this is achievable though an existing straight forward official way? Or please advice what could be a work around.
Thanks in advance.

**Comment by rohit0662012** [comment]
In v.20 .getData() is changed to .getSourceData() try it

**Comment by AMBudnik** [comment]
Hi,
Check [this example](http://jsfiddle.net/7u1kxjLe/1/).
`instance.getData()` prints 'seen' data and `instance.getSourceData()` prints you data from instance's settings.

**Comment by rameshkarunakaran** [comment]
Many thanks rohit0662012 and AMBudnik!! Simple replacement of getData with getSourceData did the job!! I am able to proceed now.
