### ISSUE TITLE
Object data is return as Array since the update to 0.20.0

### ISSUE THREAD

**Issue by migueltapia** [handsontable/handsontable#2982]
When I do getData() and I have defined it as an Object it returns it as an array.  It did not use to do this in 0.19.0, my app is no longer working.

A perfect example of what I'm talking about:
Clicking "Dump data to console" returns different results

http://docs.handsontable.com/0.19.0/tutorial-data-sources.html#page-object
result:  data of #example3 [Object, Object, Object, Object, Object, Object]

http://docs.handsontable.com/0.20.0/tutorial-data-sources.html#page-object
result:  data of #example3 [Array[3], Array[3], Array[3], Array[3], Array[3], Array[3]]

Is this a bug or is this simply no longer part of 0.20.0, if so how can I downgrade to 0.19.0.

**Comment by rohit0662012** [comment]
try .getSourceData();  in v.20 the .getData() is changed to .getSourceData();

**Comment by migueltapia** [comment]
Thank you so much, it worked!!
