### ISSUE TITLE
hot.setDataAtCell(j,col,data) is not working fine in v.20

### ISSUE THREAD

**Issue by rohit0662012** [handsontable/handsontable#2983]
I am trying to set data in handsontable in javascript code but the data is not getting effected in handsontable.

I am enabling merge cell option in handsontable and after that i am filling the empty cells in merged region with the data of the merged cell region, but the data is not getting reflected in table.

to see the error have some value in the cell and try to merge the rows in the same colomn and click get data see in console we will not get data effected

if i click the button twice the data is getting effected

Refernce : http://jsfiddle.net/rk6612/qcezcdhu/3/

**Comment by AMBudnik** [comment]
Hi,

`getDataAtCell` for merged cells does not provide expected values, that's why you `setDataAtCell` for merged cells is not working as expected either.

**Comment by rohit0662012** [comment]
Its working fine in v - 0.19.0  so what should i do now?

**Comment by AMBudnik** [comment]
You are using `getSourceData` which was added in 0.20.0 you had to made some changes after 0.20.0, the exact code couldn't work at 0.19.0

You can easily download older version just changing the number of the version (example: 18, 19, 20)
"http://docs.handsontable.com/0.18.0/bower_components/handsontable/dist/handsontable.full.js"
"http://docs.handsontable.com/0.19.0/bower_components/handsontable/dist/handsontable.full.min.css"
"http://docs.handsontable.com/0.20.0/bower_components/numeraljs/languages/de.js"

**Comment by rohit0662012** [comment]
No i am saying that getDataAtCell for merged cells , setDataAtCell for merged cells is working fine in v-0.19 so why is there a problem in v-0.20

**Comment by AMBudnik** [comment]
@rohit0662012 I marked it as a change and as soon as we find out what is causing it this issue we'll update this subject.

**Comment by rohit0662012** [comment]
Yeah i got it but getdataatcell shoudnt work differently for v0.19 and v0.20 for merged cells

**Comment by rohit0662012** [comment]
And also if i click the get data button second time the data gets effected in the table please see that behavior also

**Comment by rohit0662012** [comment]
Is it a bug or what you guys can confirm?

**Comment by AMBudnik** [comment]
Hi @rohit0662012 

I was going to test the example with the latest version but I got lost with the translation of the bug.

Can you please check if it still occurs in version 0.31.0? 

Thanks in advance

**Comment by rohit0662012** [comment]
Its almost more than a year. I am not working on the product right now. You
can close the ticket for now.

On Mon, Feb 27, 2017 at 3:11 PM, Aleksandra Budnik <notifications@github.com

**Comment by AMBudnik** [comment]
Ohh OK, I understand.

Thank you for your prompt reply.
