### ISSUE TITLE
Virtual DOM

### ISSUE THREAD

**Issue by vlados** [handsontable/handsontable#2984]
Hi,
I already saw that you are thinking for PRO version that will include this feature. How is it going with it, what is the status? We need something like this for our software and I am very interested of something like this :)

**Comment by AMBudnik** [comment]
Hi,

Currently we have [8 features](http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button) completed and 7 left to go. We are planning to release Handsontable PRO 11th of January 2016.
