### ISSUE TITLE
"Access is denied" exception on IE 11

### ISSUE THREAD

**Issue by GabiAxel** [handsontable/handsontable#2986]
Can be reproduced on handsontable.com with IE developer tools open.
Exception source is getOwnPropertyNames()

**Comment by AMBudnik** [comment]
Confirmed (Win 7)

![zrzut ekranu 2015-11-16 o 15 29 56](https://cloud.githubusercontent.com/assets/10757813/11184307/18e05670-8c77-11e5-88fa-fb890545ab64.png)

**Comment by krzysztofspilka** [comment]
Confirmed and assigned to a milestone.

**Comment by jansiegel** [comment]
This should be resolved after implementing #3059.

This issue is connected with Handsontable overriding the Object properties + IE iframe issues. Basically, if any iframe is present on the page, IE uses the Handsontable's `getOwnPropertyNames` shim, which causes the `Access is denied` error.
