### ISSUE TITLE
Invalid date + datePickerConfig

### ISSUE THREAD

**Issue by IgorShch** [handsontable/handsontable#2987]
When I have invalid value in column with type = "date" and use datePickerConfig feature, I get an error when the calendar control is used for the first time. I.e. if the calendar is used on the valid cell for the first time, there is no error, but if the calendar is used on the invalid cell for the first time, then it throws an error at the following line: 

     for (var c = 0; c < opts.numberOfMonths; c++) {
                html += '<div class="pika-lendar">' + renderTitle(this, c, this.calendars[c].year, this.calendars[c].month, this.calendars[0].year) + this.render(this.calendars[c].year, this.calendars[c].month) + '</div>';
            }

Here is my datePickerConfig object: 

    .datePickerConfig = {
                    // First day of the week (0: Sunday, 1: Monday, etc)
                    firstDay: 1,
                    showWeekNumber: true,
                    numberOfMonths: 3
                    ,
                    disableDayFn: function(date) {
                        // Disable Sunday and Saturday
                        return date.getDay() === 0 || date.getDay() === 6;
                    }
                };

It seem to only happen when the numberOfMonths option is more than 1. 

Here is the demo http://jsfiddle.net/igorshch/18yoev21/1/

**Comment by AMBudnik** [comment]
Hi, can you provide step-by-step guide how to reproduce this behaviour? As far as I can deduce it can be more Datapicker's bug than Handsontable's.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo or further details/questions.
