### ISSUE TITLE
Is there away to get updated data from handsontable

### ISSUE THREAD

**Issue by rohit0662012** [handsontable/handsontable#2988]
I am already having some data in handsontable now if the user edits it and tries to save in the db the changes, is there a way(method ) to track the changes made to the table data and gives an array of data containing which values are changed and what  are the values(all the changes not every change triggered by afterChange) 

and also Can we keep an option to trigger change events not to occur while creating the table like when table is empty

**Comment by AMBudnik** [comment]
HI, you can create an array of `afterChange` results, it has all that you need. You can also use `getData()` and 'getSourceData()` to compare grids, like in [this example](http://jsfiddle.net/motcg69c/) it does the steps only for an `edit` and 'paste' source of change.

**Comment by rohit0662012** [comment]
but thee after change also updates when the data is being entered in table so if i dont want this feature then?

**Comment by AMBudnik** [comment]
I guess you can try to send `false` like [here](https://github.com/handsontable/handsontable/issues/2642) but it's not a good idea to disallow `afterChange` it can cause errors.

**Comment by rohit0662012** [comment]
If we delete a row like remove row option that is not working in aftercange

**Comment by AMBudnik** [comment]
Yes, you're right. According to docs `afterChange` should be triggered by:

` "alter', "empty', "edit', "populateFromArray', "loadData', "autofill', "paste"` sources

and please check other issues, [here](https://github.com/handsontable/handsontable/issues/2717) we have an issue about `removeRow` and `afterChange` working together.
