### ISSUE TITLE
Context menu always positioned on the left side of the mouse click

### ISSUE THREAD

**Issue by darkmavis1980** [handsontable/handsontable#2989]
I recently upgraded the version of Handsontable on my AngularJS app, previously I was stuck with 0.14.1 and finally I've upgraded to 0.20.0.
One thing I found is the fact that the context menu now always align on the left side of mouse click, which is fine until you click on the last cells of the dataset, where the context menu goes partially outside the viewport and it becomes unusable as shown in the picture below
![screen shot 2015-11-17 at 10 39 27 a m](https://cloud.githubusercontent.com/assets/2980681/11209274/12054a76-8d18-11e5-9ccb-229051dab285.png)

On 0.14.1 it used to work correctly, as it was detecting the fact that it was on the right edge of the viewport and it position the context menu on the right side, as you would expect

![screen shot 2015-11-17 at 10 39 15 a m](https://cloud.githubusercontent.com/assets/2980681/11209326/4da8ae6a-8d18-11e5-8495-d78b28a37d54.png)

Is there's something new to be passed to the context menu configuration that I'm not aware of or it's an actual bug?

**Comment by AMBudnik** [comment]
Hi @darkmavis1980 we already have the same case at https://github.com/handsontable/handsontable/issues/2946

**Comment by darkmavis1980** [comment]
@AMBudnik ah cool, I did a search but I didn't see that

**Comment by jansiegel** [comment]
This should be fixed with #3015.
