### ISSUE TITLE
Not all lines visible at first display (.wtHolder height too small)

### ISSUE THREAD

**Issue by MuyBien** [handsontable/handsontable#2990]
Hi,
it's the first time I have such a problem in Handsontable.
When I create a Handsontable, I get only the header and half of the first line. Then a click make everything displayed.
Looking at the HTML, it appears that the .wtHider have the good height but the .wtHolder have a height < 100px and an overflow to auto. When I click a header for example, the .wtHolder overflow property change to visible and everything is displayed.

I cannot see any CSS mine that could break this. How the height of .wtHolder is calculated ?

Thanks for any help.

**Comment by AMBudnik** [comment]
Hi @MuyBien please create a demo where this issue is reproducible.

**Comment by MuyBien** [comment]
Hi @AMBudnik 
The problem, and I am aware of it, is that I think is dependent of my application architecture. But I can't post the thousand lines of CSS and I think you don't want to go throught ^^

Is for that, I was wondering how the .WtHolder was calculated. Is that because of a position relative/absolute of a child/parent that this can occurs ? 

![handsontable-problem](https://cloud.githubusercontent.com/assets/1921522/11238027/52c3cd5a-8de3-11e5-959e-f5752d51d6b4.PNG)
In this screenshot I have 20 lines in reality...

I have another problem of height and overflow for another element in my handsontable. I will create another issue but maybe it's related (I managed to make a -not- working demo for this one).

**Comment by AMBudnik** [comment]
Code investigation could take a while in this case. Did you tried to lock your grid in another grid with fixed height/width?

**Comment by MuyBien** [comment]
What do you mean by "lock your grid in another grid with fixed height/width" ?
Putting the grid in a container with ```min-height``` for example ? Yes, in the screenshot the container have a ```min-height = 500px```

**Comment by AMBudnik** [comment]
Yes, that was my idea. Without code it's really hard to tell what's causing this state.

**Comment by MuyBien** [comment]
Sorry!!!
I just figured out what was happening!

The container is ```display:none``` when the handsontable is called -_-'
The beginner error... Sorry. It's displayed so fast that I forgot this.

I close this one.
Thanks for your help.
