### ISSUE TITLE
Prevent (or undo) remove_row based on validation

### ISSUE THREAD

**Issue by rameshkarunakaran** [handsontable/handsontable#2991]
I have some records and wanted to give context menu for the user to delete record(s) using remove_row option in the context menu.The issue is that based on value of another column in the same row, I need to prevent user from deleting/removing the row (or undo the remove row event after validation catch that this row cannot be deleted). Please advice....

**Comment by AMBudnik** [comment]
Hi, you can use [`beforeRemoveRow`](http://docs.handsontable.com/0.20.1/Hooks.html#event:beforeRemoveRow)
