### ISSUE TITLE
Proper way to align multiple tables?

### ISSUE THREAD

**Issue by aft-luke** [handsontable/handsontable#2992]
I'm trying to figure out the best way to align multiple instances of a HOT, but it's proving rather difficult. I don't know if the problem has to do with my container layouts (floats, fixed widths, fixed heights, and clears), or perhaps improper column / height settings, or something else internal to the library.

![screen shot 2015-11-17 at 5 33 48 pm](https://cloud.githubusercontent.com/assets/13787895/11226995/670ad4c6-8d51-11e5-9b6f-63c73f32fd07.png)

If you look at this image, what I have going is three HOT instances. The top left is a HOT with a set height (column height * 3) and floating left. The top right is a float-right with a set-height (same as top left height) and set-width of 1 column width. The bottom is a block with margin-left the width of one column, and the height of 1 row. 

Notice these problems:
1. Although my row-heights are set to 22px, and the height of my top-left and top-right is exlicitly set to (22 px * 3), there's a little overflow that's preventing the bottom border from showing up. This happens *everywhere* on borders that `overflow: auto` and is incredibly annoying.
2. The top-left has some weird behavior where all columns past the first are clipped by something? This seems to only happen if my columns exceed a certain number. Perhaps it has to do with `fixedColumnsLeft: 1`?

What can I do to address these problems? To make things worse, this only seems to be an issue on Chrome (currently using `Version 46.0.2490.86 (64-bit)`)

**Comment by AMBudnik** [comment]
Hi @aft-luke without a demo code it will be difficult to say anything. Please prepare one.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.
