### ISSUE TITLE
Cell Header input text is not retained on re rendering

### ISSUE THREAD

**Issue by kishoreinvits** [handsontable/handsontable#2993]
I am trying to add custom text boxes into each cell header and filter based on user input. But when I do a horizontal scroll(My grid has one) previous user input is not retained.

Is there any workAround for this?

**Comment by AMBudnik** [comment]
Could you create a demo @kishoreinvits we'll have a better view to know what we are talking about.

**Comment by kishoreinvits** [comment]
Came to know that the version of hanson we are using is modified and not original Handsontable. Unable to repro with your latest version.
