### ISSUE TITLE
Scrollbars in a small dropdown type column

### ISSUE THREAD

**Issue by MuyBien** [handsontable/handsontable#2994]
Hi!
I have a column with a type dropdown and only 2 small words as sources (ul and ml). But when displayed I have a vertical and a horizontal scrollbar. How can I remove that?

Here a demo : http://codepen.io/MuyBien/full/rORLKB/

Thanks!

**Comment by AMBudnik** [comment]
It's cause of `main-style-grid.css`. Try to check what can cause it in this file. When I turn it off it works.

**Comment by MuyBien** [comment]
Oh yes!
OK thank you. It was a general rule on table element. Thanks!
