### ISSUE TITLE
handsontable  archive record issue

### ISSUE THREAD

**Issue by spicephp** [handsontable/handsontable#2998]
Hello,
I am using handsontable javascript component with php script for making a grid view and added a checkbox when we check checkbox then record is hide due to we use in mysql pdo query where condition archive = no but table grid view editing into a singal textbox is not working do you have any idea please share with me.

**Comment by AMBudnik** [comment]
Hi @spicephp without a demo code it's really hard to say anything. Please create one using JSBin or JSFiddle.

**Comment by spicephp** [comment]
its mixup javascript or php script  main issue is that when we archive or delete any record in table grid then next row edding issue create so do you hava any idea please share with me i am using this reference url.
http://past.handsontable.com/demo/php.html

**Comment by AMBudnik** [comment]
Hi @spicephp unfortunately I would need a step-by-step guide how to get the error. I'm trying to add/delete and edit rows but I don't get any bugs.

**Comment by spicephp** [comment]
can you share with me you'r javascript or php code that you are trying.

**Comment by AMBudnik** [comment]
Hi @spicephp I'm working with the example you provided http://past.handsontable.com/demo/php.html

**Comment by spicephp** [comment]
main issue is that in this component when we archive first 3 record using mysql  query i mean change the value of archive field Yes and add where condition in select record that show correct output in json formate but in table grid generate extra three rows.

**Comment by AMBudnik** [comment]
Unfortunately I can't reproduce the behaviour you saw.

**Comment by spicephp** [comment]
json output is: {"cars":[{"id":"1","manufacturer":"sss","year":"11","price":"11111","archive":"No"},{"id":"3","manufacturer"
:"vvvv","year":"66","price":"ggg","archive":"No"},{"id":"4","manufacturer":"cccc","year":"bbb","price"
:"bbb","archive":"No"},{"id":"5","manufacturer":"fff","year":"","price":"","archive":"No"}]}  
resource://jid0-gxjllfbcoax0lcltedfrekqdqpi-at-jetpack/as-ff/data/edit.html 
 
 $parent.find('button[name=load]').click(function () {
              $.ajax({
                url: 'php/load.php',
                dataType: 'json',
                type: 'GET',
                success: function (res) {
                  var data = [], row;
				 var ilen = res.cars.length;
                  for (var i =0; i < ilen; i++) {
                    row = [];
                    row[0] = res.cars[i].manufacturer;
                    row[1] = res.cars[i].year;
                    row[2] = res.cars[i].price;
                    data[res.cars[i].id - 1] = row;
                  }
				  
                  $console.text('Data loaded');
                  hot.loadData(data);
                }
              });
            }).click(); // execute immediately
 I think issue in loop please suggest me what issue is here.

**Comment by AMBudnik** [comment]
Please prepare whole demo with http://jsfiddle.net/api/post/library/pure/

**Comment by spicephp** [comment]
Please this code.

On Wed, Nov 25, 2015 at 2:54 PM, Aleksandra Budnik <notifications@github.com

**Comment by spicephp** [comment]
please share you email Id .

**Comment by AMBudnik** [comment]
Please remember that we accept only live demos (example: [`JSBin`](http://jsbin.com/), [`JSFiddle`](http://jsfiddle.net/api/post/library/pure/)) not files.

**Comment by spicephp** [comment]
I have mixup javascript and php code that are not run on JSBin or JSFiddle.so please suggest any other resouce.

**Comment by AMBudnik** [comment]
You can try to implement your code into one of [`those sandboxes`](http://stackoverflow.com/questions/4616159/is-there-a-php-sandbox-something-like-jsfiddle-is-to-js)

**Comment by spicephp** [comment]
Is there any way to hide empty row in table grid view.
![php example - handsontable 2015-11-28 15-31-41](https://cloud.githubusercontent.com/assets/5320200/11451294/3029435e-95e7-11e5-9886-08560f88b0b8.png)

**Comment by AMBudnik** [comment]
Hide/show rows will be a part of Handsontable PRO. About about PRO freatures [`here`](http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button)
