### ISSUE TITLE
Sort icon

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#2999]
hello ,
if i go to http://handsontable.com/examples.html#fndtn-finance
i see the sort icon
![sort](https://cloud.githubusercontent.com/assets/11042160/11266766/4a7850d4-8ea7-11e5-901e-740be880837d.png)

but if  open the corresponding jsfiddle
http://jsfiddle.net/api/post/library/pure/

the icon doesnt appear when i sort a column

regards
jm

**Comment by budnix** [comment]
Fixed. Thanks for reporting!

**Comment by jeanmarc78** [comment]
ah i understand now that the option sortIndicator: true display the icon.
thanks
