### ISSUE TITLE
Should work on Android and iOS

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#3]
Currently it is not usable in Android and iOS. We should try to find a way to make it usable there.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by Sune1337** [comment]
Using the viewport*Offset suggestions from #4103 the Handsontable experience om smartphone is alright imo.

There are however scrolling issues with the headers:
 * Headers reset after momentum-scroll is done
 * Headers do not show after fixed scrolling

[jsbin demo](https://jsbin.com/gekuzok/edit?html,js,output)

![handsontable header-bugs when scrolling on smartphone](https://cloud.githubusercontent.com/assets/7024113/23463074/916cd758-fe90-11e6-83b3-76d65fdc4582.gif)

**Comment by AMBudnik** [comment]
Thanks for sharing @Sune1337

**Comment by AMBudnik** [comment]
By adding mobile support we should also check
https://github.com/handsontable/handsontable/issues/2471
https://github.com/handsontable/handsontable/issues/2542

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues so we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change. This issue is very old and it surely needs some updates.
