### ISSUE TITLE
Undo error

### ISSUE THREAD

**Issue by Nyikelo** [handsontable/handsontable#3001]
When I make two changes and Undo then, the first change does Undo, but the second Undo gives an error saying
Uncaught TypeError: n[i].splice is not a function
E.g. I delete row number 5, then delete row number 7, then delete row number 30. I can Undo row number 30 delete, but not the other two.
It looks like it only "Undo" the latest changes.

**Comment by AMBudnik** [comment]
I tried to get the same error as you with [this example](http://jsfiddle.net/7uge54ru/) but I cannot reproduce it. How can I get the same result?

**Comment by Nyikelo** [comment]
Try the one on HOT website.

-----Original Message-----

**Comment by AMBudnik** [comment]
What steps you did to get it? I changed `A1` to `b` than `c` and after two <kbd>CTRL</kbd> + <kbd>Z</kbd> I got `A1` like I wanted.

Which OS/Browser are you using, maybe some addons? I tried OSX with Chrome, Safari and FF and for Windows 7 Chrome, FF and IE.

**Comment by Nyikelo** [comment]
Try the right click undo
I use win7 bad latest chrome.

-----Original Message-----

**Comment by AMBudnik** [comment]
Sorry I tried to undo changes with an `edit` source and you are mixing them with remove/add row. 

We already have issues that raise a subject of undo errors [here](https://github.com/handsontable/handsontable/issues/2577) and [here](https://github.com/handsontable/handsontable/issues/2743) and few related in our [browser for: 'undo', 'remove' keywords](https://github.com/handsontable/handsontable/search?q=undo+remove&type=Issues&utf8=%E2%9C%93)

**Comment by Nyikelo** [comment]
Hi Alekrandra,

Noted.

-----Original Message-----
