### ISSUE TITLE
Can we have more than one handsontable on a single web page

### ISSUE THREAD

**Issue by rohit0662012** [handsontable/handsontable#3002]
So is there a way to dynamically have more than one handsontable on a singe web page

so i will have a button when ever a user clicks on it a new table gets created below the one that  already exists, so how many times the user clicks the button that many times a table need to be created is there a way to have make this thing possible

**Comment by AMBudnik** [comment]
yes, you can. This [example](http://jsfiddle.net/d8Lu4ecf/3/) shows two separate instances, you can work with one like there isn't anything else on the page. They have separate space and settings.
