### ISSUE TITLE
handsontable.bootstrap.css  td background color

### ISSUE THREAD

**Issue by thip** [handsontable/handsontable#3003]
The css file [provided](https://github.com/handsontable/handsontable/blob/master/plugins/bootstrap/handsontable.bootstrap.css)  for use with bootstrap contains the following:

```
.handsontable td {
  background-color: inherit !important;
}
```

I'm just wondering why this is there? it seems to prevent me from setting cell background colors in custom renderers.

**Comment by AMBudnik** [comment]
Topic moved to [Improvement-suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)
