### ISSUE TITLE
Rerender of table with fixed rows and columns - hidden scrollbar

### ISSUE THREAD

**Issue by castlese** [handsontable/handsontable#3004]
When I re-render a table that has fixed rows and columns, the top of the vertical scrollbar is hidden behind the fixed rows on the top of the table. 

http://jsfiddle.net/1ts9bjvk/2/ - click on Comments button to see it in action.

**Comment by AMBudnik** [comment]
Hi, this example is very complicated, can you separate only the code that has a real impact on this behaviour? I saw that you get many console errors also.

**Comment by castlese** [comment]
Hi, I've simplified the example here:
http://jsfiddle.net/9rfyy3f6/
The scroll bar is missing at the top when 'Trigger' is first clicked

(That original jsfiddle was based on an example from the [handsontable documentation](http://docs.handsontable.com/0.20.1/demo-fixed-rows-and-columns.html). It has the same console errors FYI)

**Comment by AMBudnik** [comment]
HI @castlese I couldn't reproduce the issue with the last version of Handsontable. Can you check it?

**Comment by AMBudnik** [comment]
Issue will stay closed till it gets updated.

**Comment by castlese** [comment]
Hey -  I'm no longer working on the project that is using HOT and having this issue. @gstenson, you might still have an interest in this though?
