### ISSUE TITLE
startCols interferes with colHeaders option

### ISSUE THREAD

**Issue by enzeart** [handsontable/handsontable#3005]
The default value of startCols interferes with the rendering of the header names specified in colHeaders when the number of values colHeaders is greater than the startCols value.

**Comment by AMBudnik** [comment]
Could you please create an example code where we can see how they're interfering?

**Comment by enzeart** [comment]
I can't seem to reproduce this issue. After trying to reproduce this issue it seems as though the problem was with something I was doing at that time. Closing this issue, thanks for your time.
