### ISSUE TITLE
All columns are not rendered

### ISSUE THREAD

**Issue by shivrajsa** [handsontable/handsontable#3008]
Consider below array
var data =[
[1,2],
[1,2,3,4,5],
[1,2,3,4,5,6],
];
when I render this data in handsontable, it shows columns equal to array index having minimum number i.e. 2. so I get below result in excel.
1 2
1 2
1 2
rest of the values from 2nd & 3rd are not displayed. Is there way to solve this problem without modifying array?

**Comment by AMBudnik** [comment]
Hi @shivrajsa you can use `minCols` like in [this example](http://jsfiddle.net/rLbv2tnn/)
