### ISSUE TITLE
Programmatically insert/remove row/column

### ISSUE THREAD

**Issue by klikstermkd** [handsontable/handsontable#3009]
Is there a way to programmatically insert and remove rows and columns? 

There are two methods, ```spliceCol``` and ```spliceRow``` but they basically remove data, and not the entire row or column.

**Comment by AMBudnik** [comment]
Hi, currently the best way is to use [`alter`](http://docs.handsontable.com/0.20.1/Core.html#alter)

**Comment by klikstermkd** [comment]
This is what I was looking for. Thanks a lot!

**Comment by mvergelop** [comment]
i know that this its old, but its there a way to do it, from a click of a button?

**Comment by AMBudnik** [comment]
Hi @mvergelop as proposed 2 comments above - you can use the `alter` method. The method hasn't been changed since v.0.20.1 when I posted the reply.
If you need any further guidance please let me know.
