### ISSUE TITLE
I want to disable the ctrl + x of beforekeydown.

### ISSUE THREAD

**Issue by IDLOCKED** [handsontable/handsontable#3011]
I want  ctrl + x(cut) this function disable.
Disabling Deletekey and BackSpacekey In this [code](http://jsfiddle.net/8Leuff5r/) I was able, but could not be disabled ctrl + x (cut).
Help me.
Thank you for your attention.

EX:http://jsfiddle.net/8Leuff5r/

**Comment by AMBudnik** [comment]
Hi @IDLOCKED 
did you made progress, is there anything I can help you with currently?

**Comment by IDLOCKED** [comment]
@AMBudnik 
Thank you for your reply.

A cell is cut even if I update it in the latest version.
Is this a specification?
Or is it a bug?

http://jsfiddle.net/8Leuff5r/1/

**Comment by AMBudnik** [comment]
I'll inform our developers to check this issue.
At the first glance it should be working as expected but it's not. I thought that maybe combination with a <kbd> CTRL</kbd> is blocked so I tried <kbd>CTRL</kbd> + <kbd>a</kbd> combination (select all) and it's blocked (there's no extra selection).

**Comment by AMBudnik** [comment]
added in [0.24.2](https://github.com/handsontable/handsontable/releases/tag/0.24.2)
