### ISSUE TITLE
modifyRow hook not trimming a row when returns null

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3012]
The `modifyRow` hook doesn't *trim* a row, when it returns `null` for the row.

For example, this:
```js
modifyRow: function (row) {
        if (row === 1) {
            return null;
        }
        return row;
}
```
should not render the second row at all. It seems that it clears the data from the row, but renders it anyway: http://jsfiddle.net/d6nz0y01/

**Comment by budnix** [comment]
Actually trimming rows work :) But it's not as simple as previously was thought. To trim rows you must implement own shifting algorithm to achieve valid results. Here you are an [example](https://jsfiddle.net/handsoncode/81ewbapL/).
