### ISSUE TITLE
Handonstable wtHolder Height calculation

### ISSUE THREAD

**Issue by mznj21** [handsontable/handsontable#3013]
I am trying to render a handsontable inside of a node on a tree but when I do the wtHolder height calculation is huge ~400000px.  I tried wrapping the hot inside a div but it kind of defeats the purpose since I can no longer grow the rows in the grid and automatically re-size it.  Any ideas on how i can force the hot to correctly calculate the size?

**Comment by rtaft** [comment]
Same issue here, I just upgraded from 0.13.1 to 0.20.2 and I have this issue now.  Every time I select an item in the combo box cell, the size gets bigger and bigger.

**Comment by rtaft** [comment]
Comment out lines ~2859-2860:
this.holder.style.width = getStyle(trimmingElement, 'width');
this.holder.style.height = getStyle(trimmingElement, 'height');
I have not seen any adverse side effects from it in my usage.

**Comment by rtaft** [comment]
This is caused in alignOverlaysWithTrimmingContainer when the trimming element ends up being one of the outer divs of the page.  getStyle returns the size of the page, which increases the size of wtHolder, which in turn increases the size of the page.  Disabling the setting of the size breaks drop downs.  removing the computed style in getStyle works for me, but may break other things.  I used this workaround:

```javascript
alignOverlaysWithTrimmingContainer: function() {
    var trimmingElement = getTrimmingContainer(this.wtRootElement);
    if (!this.isWorkingOnClone()) {
      this.holder.parentNode.style.position = 'relative';
      if (trimmingElement === window) {
        this.holder.style.overflow = 'visible';
        this.wtRootElement.style.overflow = 'visible';
      } else {
        this.holder.style.width = getStyle(trimmingElement, 'width');
        this.holder.style.height = getStyle(trimmingElement, 'height');
        this.holder.style.overflow = '';
      }
    }
  },
```
Add to the else clause a check to see if the trimming element is a handsontable class:
```javascript
alignOverlaysWithTrimmingContainer: function() {
    var trimmingElement = getTrimmingContainer(this.wtRootElement);
    if (!this.isWorkingOnClone()) {
      this.holder.parentNode.style.position = 'relative';
      if (trimmingElement === window) {
        this.holder.style.overflow = 'visible';
        this.wtRootElement.style.overflow = 'visible';
      } else if (trimmingElement.className.indexOf("handsontable") != -1) {
        this.holder.style.width = getStyle(trimmingElement, 'width');
        this.holder.style.height = getStyle(trimmingElement, 'height');
        this.holder.style.overflow = '';
      }
    }
  },
```

**Comment by nidhityagi46** [comment]
I had the same issue, empty blank space below the rows as wtholder was calculating wrong height. I tried this fix, and the container is now fitting the data well. however, the row header is hidden/missing after the height that was previously calculated for wtHolder before the hack.
![image](https://user-images.githubusercontent.com/26898947/40838261-05af16a2-65bb-11e8-8eb5-4f62919b8534.png)

Please help.

**Comment by AMBudnik** [comment]
Hi @nidhityagi46 if you still are facing this issue please create a demo where this issue can be replicable.

**Comment by CANopenNode** [comment]
I have the same issue when I include handsontable into dokuwiki. Large blank space after the table, which is getting larger on each table change.

Here is the demo:
https://wiki.paternoster.biz/doku.php?id=public:open

**Comment by AMBudnik** [comment]
Hey @CANopenNode 

do you get the same behavior when you add a fixed height?

**Comment by CANopenNode** [comment]
Hi, 
if I use the height option, it seems to behave OK.

I added another div into the page, so it is possible to generate handsontable on it from javascript console, for example:
`var hot2 = new Handsontable(document.getElementById('example2'), {data: [ ['Tesla', 'Nissan'], [10, 11] ]});`

I'm using firefox and latest handsontable.full.js, which can be debugged.
