### ISSUE TITLE
Sorting bug for columns grater than 29

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3014]
Actually https://github.com/handsontable/docs/issues/23 bug relates to sorting for columns grater than 29.

Simplified demo: [`JSFiddle example`](http://jsfiddle.net/yz25z1x8/3/)

To reproduce:
sort few times one of the columns grater than 29.

Result: 
after few clicks only two first rows get sorted.

**Comment by krzysztofspilka** [comment]
@AMBudnik should be fixed tomorrow
