### ISSUE TITLE
Column resize bug on sheet with large row

### ISSUE THREAD

**Issue by arammkrtchyan** [handsontable/handsontable#3016]
Hi guys,
After resizing the width of the first column by double clicking on the resize handle, there is only one row rendered (only visible rows before).
Here is the demo:
  http://jsfiddle.net/a8ts8w2q/

And here is the result after resizing.
![screen shot 2015-11-29 at 2 33 41 pm](https://cloud.githubusercontent.com/assets/5568286/11456563/ef027eec-969d-11e5-9a4e-1fb716507a12.png)

**Comment by AMBudnik** [comment]
Confirmed with Firefox 42 & Chrome 46
Table has to be scrolled to trigger other rows to be rendered.

**Comment by AMBudnik** [comment]
Still present in 0.24.1, updated demo: http://jsfiddle.net/a8ts8w2q/1/

**Comment by AMBudnik** [comment]
Issue can be closed.
It works as expected when we add `autoRowSize: true`, demo: http://jsfiddle.net/handsoncode/t318egn6/
