### ISSUE TITLE
Enhancement: Option to automatically adjust container's height with max limit

### ISSUE THREAD

**Issue by YasserHassan** [handsontable/handsontable#3017]
The benefit of this option (`autoContainerHeight`) is when the table is filled with a few records that do not fully occupy the container's height, leaving a space between the last records int he container's bottom. In this case, the user wouldn't know that there's a horizontal scroll bar unless he scrolls down.

Another option `maxContainerHeight` could be used to specify the maximum height the container could be expanded to.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
Hey,

we've added an option in Handsontable 7.0.0 that can interest you https://github.com/handsontable/handsontable/issues/5749 
From now on we support a container with relative dimensions (%, vh, vw, rem, em)
