### ISSUE TITLE
Performance Warning From Firefox

### ISSUE THREAD

**Issue by opticyclic** [handsontable/handsontable#3018]
I constantly see the following warning in the Firefox console when using Handsontable (0.19.0).

    mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

It is line 17796 in handsontable.full.js but is probably this in the source code
https://github.com/handsontable/handsontable/blob/3e8ca2e17a0fdad65b66ca21f9192a3a55e57292/src/shims/classes.js#L349

Is this something to be concerned about?

**Comment by AMBudnik** [comment]
Hi @opticyclic 
Could you update to 0.24.1 and see if there are any new warning? I couldn't reproduce the case on my PC.

**Comment by AMBudnik** [comment]
Couldn't reproduce.
