### ISSUE TITLE
Calculate from bottom to top

### ISSUE THREAD

**Issue by oceanapplications** [handsontable/handsontable#3019]
I have a spreadsheet that uses calculated values from the row below it to calculate a value in an upper row.  As far as I can tell, this fails because the value is required from the lower row before it has been calculated.

Is it possible to calculate everything from bottom to top?

**Comment by AMBudnik** [comment]
It depends on what does calculate means in your example. If you're adding/multiplying etc. you can use formulas.

**Comment by oceanapplications** [comment]
The formula used is E(n+1)+Dn-(Bn+Cn) where n is the current row.  This formula is placed in the E column.  The last row's formula in the E column is Dn-(Bn+Cn).  Every row will error except the last row which doesn't use a computed value in its formula.

**Comment by AMBudnik** [comment]
please create a demo with this example

**Comment by oceanapplications** [comment]
http://jsfiddle.net/xa048cc8/7/ Here's the demo.

Thanks

**Comment by AMBudnik** [comment]
Hi @oceanapplications sorry for a delay. Do you still looking for an answer/solution?

**Comment by oceanapplications** [comment]
Yeah, as it stands right now the important data ends up at the bottom of the sheet since that seems to be the only way for the calculation to work.

Thanks

**Comment by AMBudnik** [comment]
Glad it works, this case was really tough.

**Comment by NikitaParab** [comment]
Hey,

In my case also ,there are some cells which depend on a cell below it . So i get a #Value in my cell.

Is there any solution for this ?
