### ISSUE TITLE
header on multiple lines

### ISSUE THREAD

**Issue by lethunder** [handsontable/handsontable#3020]
I'm not able to set header multilines with <br/>. 
the <br/> displays in the column title

this is my source file
============================
  var header_title_array = [];

    header_title_array.push("索引号&lt;br/&gt;Index No.");
    header_title_array.push("厂别&lt;br/&gt;Factory Name");
    header_title_array.push("项目号&lt;br/&gt;Project No.");
  $.each({"2":{"type":"text"},"3":{"type":"text"},"4":{"type":"text"}}, function (i, j) {
      var o = {};
      o.type = j.type;
      o.editor = j.editor;
      o.selectOptions = j.selectOptions;
      a.push(o);
  });
  var hot = new Handsontable(container, {
      data: data,
      colHeaders: function (index) {
          return header_title_array[index];
      },
      columns: a,
      height: $(window).height() - $(".top-bar").height() - $(".tab-bar").height(),
      stretchH: 'all',
      columnSorting: false,
      minSpareRows: 0,
      rowHeaders: true,
      fixedColumnsLeft: 0,
      fixedRowsTop: 0,
      manualColumnFreeze: true,
      manualColumnResize: true,
      manualColumnMove: false,
      manualRowMove: false,
      currentRowClassName: 'currentRow',
      currentColClassName: 'currentCol',
      copyPaste: true,
      persistentState: true,
      renderAllRows: true,
      undo: true,
      cells: function (row, col, prop) {
          return {renderer: myRenderer};
      },
      search: {
          callback: searchResultCounter
      }
}
..................................
==================================================
![capture](https://cloud.githubusercontent.com/assets/6217812/11465007/72898534-9735-11e5-80d4-a255346b339c.PNG)

**Comment by AMBudnik** [comment]
Hi, [`here's`](http://jsfiddle.net/Ckw9b/1137/) an example you can use.

**Comment by lethunder** [comment]
thanks AMBudnik. It works :)
