### ISSUE TITLE
How to set focus in the first row of the handsontable on tabs from keyboard

### ISSUE THREAD

**Issue by kuradabhaskar** [handsontable/handsontable#3021]
Tried setting tabindex specifically for HOT but it didn't work

<hot-table tabindex="0" settings="model.tableSettings" col-headers="true" columns="model.tableColumns"
                                            data="model.tableItems" min-spare-rows="5">
                                </hot-table>

**Comment by AMBudnik** [comment]
You would like to focus (select) whole first row, after a <kbd>TAB</kbd> click?

**Comment by kuradabhaskar** [comment]
Yes. rather the first cell first row first column to be precise

**Comment by AMBudnik** [comment]
Hi, [`this example`](http://jsfiddle.net/qvzwrp4q/) should be helpful but <kbd>TAB</kbd> selects row: 0, col: 1 while he gets `hot.selectCell(0,0);` while this code written into a button selects right cell `(0,0)`

**Comment by kuradabhaskar** [comment]
Thanks for the pointer, but how to add hooks in angular controller I am unable to add them, do you have any example for the same.

**Comment by AMBudnik** [comment]
Here you go - [`angular version`](http://jsbin.com/tutoqevigu/1/edit?html,js,output) in the version above I forgot to add a line which prevents <kbd>TAB</kbd> to actually tab to another cell, in angular version it's added.

**Comment by kuradabhaskar** [comment]
Hi, the above example works only when the HOT is manually selected and that example helps to reselect the first cell when the keypress was a tab on the HOT. 
My bad if there was any ambiguity in my earlier question. 
I have a input screen to get some details (few text boxes and a HOT to collect some tabular data). On the page load when tab is clicked the focus is getting shifted to the remaining controls in order based on the placement/tabindex of the HTML control whereas when the tab comes to the HOT the first cell is not getting highlighted.

**Comment by AMBudnik** [comment]
If you face some issues, please create a demo at https://github.com/handsontable/ngHandsontable where we discuss angular version.

**Comment by kuradabhaskar** [comment]
Hi, 
As provided in the snapshot below I have couple of input controls one normal text box and the other Handsontable. 
After pageload on first click of tab the focus gets shifted to the text input up on the next tab ideally the handsontable first cell should be selected but is not getting selected.  Tried setting tabindex explicitly but didn't work.

Whereas the above solution onBeforeKeyDown works after the handsontable is manually selected with a mouse click event and on clicking tab the first cell is selected.
![tabcapture](https://cloud.githubusercontent.com/assets/16083580/11558690/1a4d381e-99da-11e5-8637-80e5ed246420.PNG)

I hope this explains the issue that I was referring to,

**Comment by AMBudnik** [comment]
Currently it can't be achieved through the Handsontable itself but you can try to listen to <kbd>tab</kbd> and after it leaves input do `instance.selectCell(0,0)` in Handsontable.

**Comment by kuradabhaskar** [comment]
Which hook need to be used to listen to tab, because onBeforeKeyDown hook will work after Handsontable is selected ?

Or you are suggesting to try write keydown event on the input control and set focus to the first cell of the handsontable

**Comment by AMBudnik** [comment]
Handsontable keyDown hook will work only in the range of Handsontable so it has to be written as a separate event.

**Comment by kuradabhaskar** [comment]
Thanks for the pointer. A separate key down event on the leaving control and using instance.selectcell as well as the Handsontable.dom.stopImmediatePropagation did the trick

Appreciate your help.

**Comment by kuradabhaskar** [comment]
Any known reason why Handsontable.dom.stopImmediatePropagation(event) doesn't work on Firefox

**Comment by kuradabhaskar** [comment]
Figured out that need to use a separate route of event.stopimmediatepropagation for firefox
