### ISSUE TITLE
Problem with copying a cell containing a JSON (solved).

### ISSUE THREAD

**Issue by dixso** [handsontable/handsontable#3022]
Hi,
Consider this pull request for inclusion in their libraries:
https://github.com/warpech/sheetclip/pull/6

Regards.

**Comment by AMBudnik** [comment]
Thanks @dixso we'll check it

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
