### ISSUE TITLE
JavaScript error in _addClass() IE9

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#3024]
I was debugging an issue in IE9 and found that I was getting these JavaScript errors in IE9 from Handsontable:

```
SCRIPT5007: Unable to get value of the property 'join': object is null or undefined 
handsontable-0.18.0.full.js, line 8637 character 7
```

This is happening due to the fact that I have set `readOnlyCellClassName` to null, and it's trying to call `join()` on it.  This is not a problem with modern browsers which have class list support.

**Comment by cgatesman** [comment]
As a workaround, I have set my `readOnlyCellClassName` to an empty string which also works.  But the Handsontable _addClass() implementation should probably check for null or undefined in this case as it works in the classListSupport implementation.

**Comment by AMBudnik** [comment]
Hi @cgatesman could you check if it still occurs for 0.23.0?

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topic and uloading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Isuee will be reopene with first update.

**Comment by AMBudnik** [comment]
This issue should no longer be replicable using Handsontable v8.4.0.
If anyone has experienced the same issue, please leave a comment.
