### ISSUE TITLE
Column sorting lost when setting table to readOnly

### ISSUE THREAD

**Issue by thbar** [handsontable/handsontable#3026]
If I update the settings using this:

```coffeescript
@hot.updateSettings({readOnly: true})
```

and a sort was in place (`columnSorting: true` then click on one header of the table to change the order), then the sorting settings are lost. The table goes back to unsorted mode.

I managed to work around this using the following code:

```coffeescript
options = { readOnly: readOnly }
if @hot.sortColumn?
  options = _.extend(options, {
    columnSorting: {
      column: @hot.sortColumn,
      sortOrder: @hot.sortOrder
    }})
@hot.updateSettings(options)
```

This seems fragile though, since it makes me wonder if the `updateSettings` call may also override other settings initially passed to the constructor.

Is this confirmed to be a bug, or by design?

Is the work-around provided going to make it on the long run?

Thanks!

**Comment by AMBudnik** [comment]
Thanks for sharing @thbar, it's a bug
Example [`demo`](http://jsfiddle.net/x342f6kj/)

**Comment by thbar** [comment]
@AMBudnik thanks for the acknowledgement. I'll monitor this issue and will keep my work-around for now.

**Comment by AMBudnik** [comment]
Issue doesn't occur in 0.24.0
Updated demo: http://jsfiddle.net/handsoncode/x342f6kj/1/
