### ISSUE TITLE
Broken link to comments demo

### ISSUE THREAD

**Issue by thbar** [handsontable/handsontable#3027]
The link to the "Comments" demo [in this section](http://docs.handsontable.com/0.20.1/Options.html#comments) leads me to the homepage, it appears to be broken, I thought you'd want to know so opening this issue :smile:

Is the demo still available somewhere, by the way?

**Comment by AMBudnik** [comment]
Thanks @thbar indeed it's broken
Here's the landing page for this one http://docs.handsontable.com/0.15.0-beta6/demo-comments.html
I moved this issue to https://github.com/handsontable/docs/issues/24 cause everything wrong with the docs gets there.

**Comment by thbar** [comment]
@AMBudnik, great, good to know! Thanks.
