### ISSUE TITLE
Exort scrolldown when dropdown list was used

### ISSUE THREAD

**Issue by Vertek** [handsontable/handsontable#3029]
Hello, i have one problem with dropdown list. When div element with handsontable table have 400px height and handsontable table in this div have near 400px height and in last row i will use dropdown list then dropdown will work but i need to scroll down, after click any item on dropdown list height of handsontable table back to normal. Is there any resolve that i can extort scrolldown table when dropdown list was clicked?

![handsontable scroll](https://cloud.githubusercontent.com/assets/13697724/11527901/dc8b32ca-98e3-11e5-8a1d-558a29a4e326.png)

**Comment by AMBudnik** [comment]
Hi @Vertek we have the same issue (with a workaround) [`here`](https://github.com/handsontable/handsontable/issues/2483)
