### ISSUE TITLE
Handsontable clone helper bug

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3030]
There is a bug in Handsontable.helper.clone function where we try to clone object with values which returns an `false`-like value (eq. `0`, `''`, `null`...) then clone loop is interrupted.

To reproduce it try to call this code `Handsontable.helper.clone({foo: 'aaa', bar: false, baz: 123})` in the developer tool. In the cloned object `baz` property is missing.

**Comment by krzysztofspilka** [comment]
Released in 0.20.2
