### ISSUE TITLE
Drag-down and allowInsertRow

### ISSUE THREAD

**Issue by fbrussa** [handsontable/handsontable#3032]
Hi. this seems to be an error.
I want to allow "drag-down" and prevent create new rows.

http://jsfiddle.net/s3abm2cn/2/

If I select a cell and make "drag-down", this creates new rows.
This occurs on Windows with Chrome and IE
thank you

**Comment by casmith** [comment]
+1 This is bugging me, too. In fact, if you drag down to the last row, it creates a new empty row even when minSpareRows is 0.

**Comment by AMBudnik** [comment]
Hi, please track changes to https://github.com/handsontable/handsontable/issues/2874
