### ISSUE TITLE
Adding columns with renderers

### ISSUE THREAD

**Issue by vrmerlin** [handsontable/handsontable#3034]
I'd like to be able to add a column dynamically, and have a renderer set for the column. In this example:

http://jsfiddle.net/88ufsmze/1/

it seems that all values in column F should be yellow when the button is clicked, but they aren't. Is there another "refresh" call that I need to do beside render()?

Thanks,
John

**Comment by AMBudnik** [comment]
Hi @vrmerlin 
Is there anything I can help you with currently?

**Comment by AMBudnik** [comment]
I'm closing this issue in lack of reply but if there's something I can help you with just drop me a line.
