### ISSUE TITLE
grouping?

### ISSUE THREAD

**Issue by vrmerlin** [handsontable/handsontable#3035]
The grouping feature was apparently deprecated:
http://docs.handsontable.com/0.18.0/demo-grouping-and-ungrouping.html

Will it be returning in some other form, in the pro version? I really need to the ability to grouping by certain row values.

Thanks,
John

**Comment by AMBudnik** [comment]
Hi, in Handsontable PRO will be an ability to [show/hide row/cols](http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button)

**Comment by vrmerlin** [comment]
I'm not clear we are saying the same thing... I mean this sort of functionality:

http://www.ag-grid.com/angular-grid-grouping/index.php

https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxgrid/jquery-grid-grouping.htm

Is that what is in the PRO version?

John

**Comment by AMBudnik** [comment]
Similar functionality will be a part of PRO as a 'Collapsible headers of columns' (just for columns)

**Comment by vrmerlin** [comment]
Great! I look forward to the new release!

**Comment by AMBudnik** [comment]
It will be ready for 11th of January 2016. 

If you'd like to be informed as soon as it's ready you can subscribe to our [PRO notifier](http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button#subscribe)

**Comment by varun-dev** [comment]
I know that this is closed and the feature is no more available but is there any recommended way to achieve grouping of rows ??

**Comment by AMBudnik** [comment]
Hi @vrmerlin 
Actually we're working on this now. The feature will be called nestedRows and the mechanism will be similar to [Collapsible Columns](https://docs.handsontable.com/pro/1.3.2/demo-collapsing-columns.html).

I highly encourage to sign in to our newsletter at https://handsontable.com/ (at the bottom of the page) and track [release notes](https://docs.handsontable.com/pro/1.3.2/tutorial-release-notes.html)
