### ISSUE TITLE
Security brake: Too much TRs

### ISSUE THREAD

**Issue by dev1909** [handsontable/handsontable#3036]
Hello,

I get following error message when I try to create handsontable with 1000 rows:

"Security brake: Too much TRs. Please define height for your table, which will enforce scrollbars."

I defined height for the table but it didn't help. I've figured out that it only happens if I have renderAllRows: true in the table definition. We need this attribute in our tool, so I'm wondering if there is any other way to solve the problem without removing this attribute?

We use handsontable version 0.15.1.

**Comment by AMBudnik** [comment]
Hi @dev1909 please correct me if I'm missing something. 

In [this demo](http://jsfiddle.net/jhjg3ddd/) i have 1000 rows and `renderAllRows: true` with `v0.15.1` and I don't get the error.

I tried it with OSX (Chrome, FF, Safari)

**Comment by dev1909** [comment]
Thanks for your reply! I'll check again, if something else can cause this issue.

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply.

**Comment by dev1909** [comment]
Hi @AMBudnik, it appears to work fine with 1000 rows, but if I change 1000 to 1002 even in this simple example I become this error. In our project we don't have an upper limit, the user must be able to add as many rows as he needs.

**Comment by AMBudnik** [comment]
Thanks for sharing. I tried it with more than 1000 rows and got the same message. It throws the same error for newest version 0.20.3 also. (updated to 0.20.3 demo http://jsfiddle.net/jhjg3ddd/1/).

**Comment by AMBudnik** [comment]
Confirmed with 0.23.0

**Comment by dev1909** [comment]
We need it to be fixed as soon as possible. Can you please publish the newest version where it's already fixed as a NuGet package?

**Comment by AMBudnik** [comment]
Hi @dev1909 actually as we were investigating this case it is related to few parts of code and it will take little longer to be fixed.

**Comment by AMBudnik** [comment]
The same issue at: https://github.com/handsontable/handsontable/issues/2320
