### ISSUE TITLE
onchange of external event I want to set the handsontable dropdown list

### ISSUE THREAD

**Issue by saharjadoa** [handsontable/handsontable#3037]
onchange of external event I want to set the handsontable dropdown list, I have cities dropdown list. and I have also country list out of the handsontable. I want when change the country, set the cities of that country in the column of the cities in the handsontable.

**Comment by AMBudnik** [comment]
Hi, we have the same issue at https://github.com/handsontable/handsontable/issues/1066 maybe demo there could bright a little light on your project.

**Comment by saharjadoa** [comment]
Thank you for responding, What I really want is to get the cities from database on each country change and reset the all columns cells to have the right city. I dont have two handsontable dropdown, just one, the cities. the country list is out of the handsontable structure. Would you help please.

**Comment by AMBudnik** [comment]
Do you have a demo of your recent progress? Your `country` is a `text` type cell, `autocomplete` or an outside input or a button?

**Comment by saharjadoa** [comment]
yes it is an outside input, and it is a select input, once the user select a country, the city list which is inside the handsontable will be reset and changed.

javascript:
function getCitiesByCountry(countryDiv) {
            var data = hot.getData();alert(data);
            var address_id =  $(countryDiv).attr('value');
            $.ajax({
                type: "POST",
                url: "/order/countrycities",
                data:"address_id="+address_id,
                dataType: "json",
                success: function(cities){
                    city = [cities[0].city_name,cities[1].city_name];
                    setCitiesOnTable(data,city);              
                }
            });
            
        }

Html:
                                                   <select name="location" onchange="getCitiesByCountry(this)"> 
                                                            <option value="1">USA</option> 
                                                                <option value="2">UAE</option>
                                                                <option value="3">Canada</option>
   
                                                        </select>

hansontable creation:
hot = new Handsontable(container, {
              minSpareRows: 25,
             // contextMenu: ['row_above', 'row_below', 'remove_row'],
              rowHeaders: true,
              fixedColumnsLeft: 1,
              fixedRowsTop: 0,
              
               
              colWidths: [150, 150, 150, 180,180, 150,150,180,150,150],
                  colHeaders: ['Customer Name', 'City', 'Phone','Street', 'Client E-mail',
                        'Product Description','Note','Payment Type','Client Order Reference','Unit Price'],
              columns: [
                {data: 'customer_name',validator: emptyValidator,allowInvalid: true},
                {class:'city', type: 'dropdown',validator: emptyValidator},
                {data: 'street',validator: emptyValidator},
                {data: 'phone',validator: emptyValidator},
                {data: 'email',validator: emailValidator, allowInvalid: true},
		
                {data: 'desc',validator: emptyValidator},
                {data: 'note',validator: emptyValidator},
                {data: 'payment_type',validator: emptyValidator,
                 "type": "dropdown", "strict": "true",
            "source": ["Shipper Account", "Cheque","CD", "COD", "CCOD", "Credit Card" ]
        },
                {data: 'c_o_ref',validator: emptyValidator},
                {data: 'unit_price',type: 'numeric'}
              ],
              
              

            
    });

**Comment by saharjadoa** [comment]
Hello again, I used loadData() function, but the problem is when I load the cities they listed comma seperated as a text, not list in dropdown list.
![cities](https://cloud.githubusercontent.com/assets/14069708/11612887/4a9d3802-9c14-11e5-8231-f0fb0240c2bc.png)

**Comment by saharjadoa** [comment]
I solved it using ajax on source of autocomplete: 
```
columns: [
                
{       type: 'autocomplete',
        source: function (query, process) {
            
        var country =  $("#country").val();
          $.ajax({
            //url: 'php/cars.php', // commented out because our website is hosted as a set of static pages
            type: "POST",
            url: '/order/countrycitiesbykeyword',
            
            dataType: 'json',
            data: {
              keyword: query,
             country_id:country
            },
            success: function (data) {
              var values = [];
              for (i in data['data']) values.push((data['data'][i]['city_name']));
              process(values);

            }
          });
        },
        strict: true
      }, ....
```

Thanks anyway :)
