### ISSUE TITLE
Sum row values

### ISSUE THREAD

**Issue by FilAntunes** [handsontable/handsontable#3038]
Hello,
I'm calculating a row total (sum values of all cells in a row) using a renderer for the total cell. Is this the best way of doing it? I'm asking it, because i can see that the total value is always updated on every  value change, which is the expected behavior, but isn't it a heavy operation rendering the whole grid (doing the sum) every time any cell changes? is there a more efficient way to accomplish this ?
Thanks.

**Comment by AMBudnik** [comment]
You don't like to use formulas? 

[Here's](http://jsfiddle.net/45a8L9b1/) a simple code using formulas to serve a sum of previous cells in the same row.

**Comment by FilAntunes** [comment]
Using formulas would be interesting, however we need to do some text processing before adding up to the total. We would need the LEFT, RIGHT and LEN functions and those don't seem to be available according to:
http://handsontable.github.io/ruleJS/

They are available on formula.js though:
https://github.com/sutoiku/formula.js/blob/master/lib/text.js#L120

Any way to use these functions in Handsontable?

**Comment by AMBudnik** [comment]
Currently we are not adding new formulas to RuleJS, but we'll probably rewrite some code in 2016.
