### ISSUE TITLE
CurrentRowClassName marker with multiple HOT

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#3040]
Hello, HOT experts.....! I want a little bit enhancement to HOT when working with multiple HOT in one page. Let's see the following picture for best describe the things I want and may be others also want.
![image](https://cloud.githubusercontent.com/assets/4103210/11581457/2a727986-9a7d-11e5-8a69-f3790b45f0f8.png)

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
The following issue has been already reported at https://github.com/handsontable/handsontable/issues/487
