### ISSUE TITLE
CONTEXTUAL MENU NOT ACCESSIBLE ON LAST ROWS

### ISSUE THREAD

**Issue by lethunder** [handsontable/handsontable#3041]
hello,
i have a big issue with contextual menu. ON last lines, actions are no more accessible. The contextual menu in not responsive. It always stand below the selected row
![sans-titre-1](https://cloud.githubusercontent.com/assets/6217812/11583315/b46ce04c-9a58-11e5-864a-88074bfc40a3.png)

**Comment by lethunder** [comment]
Does anyone know how to override context menu default position please?

**Comment by lethunder** [comment]
according to documentation i tried this
      contextMenu: {
          position: function (opt, x, y) {
              opt.$menu.css({top: 123, left: 123});
          },
..........
but it's not working

**Comment by AMBudnik** [comment]
Hi, we have a issue for that at https://github.com/handsontable/handsontable/issues/3015
