### ISSUE TITLE
Suggestion: Option to format column header container dynamically

### ISSUE THREAD

**Issue by YasserHassan** [handsontable/handsontable#3042]
This feature would enable controlling the column container tag the same way the `cells` option works by passing TD to the handling function. For example, for column headers with checkboxes, it could be used to set the background color for the ones that have their checkboxes checked, or mark certain columns for any reason, by using a class other than `colHeader`.

**Comment by SamMousa** [comment]
Note that the current behavior actually creates invalid HTML markup when adding input tags, since they are not allowed inside `<span>` afaik.

**Comment by AMBudnik** [comment]
Hi @YasserHassan and @SamMousa could you share more information how actually it should be configured to be clear? Do you have any ideas?

**Comment by YasserHassan** [comment]
Cells properties could by defined by configuring the `cells` option like this:
```
cells: function (row, col, prop) {
  ...
},
```
Likewise, column header properties could be defined by adding the `prop` argument to the 'colHeaders' options function like this:
```
colHeaders: function(index, prop) {
  ...
},
```

**Comment by AMBudnik** [comment]
Thanks for sharing details @YasserHassan 
I'll mark your idea as a feature request

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
Hi All.

We are moving feature ideas and improvements to Github Discussions to gather all the ideas on UI and API. That will help us to continue the development of the functionality in the future.

Please feel welcome to share your feedback via the Github Discussions panel if you have any additional ideas.
