### ISSUE TITLE
Upside-down Spreadsheet

### ISSUE THREAD

**Issue by jjjrmy** [handsontable/handsontable#3043]
I made a spreadsheet with a column of calculated values that uses the row below to calculate it's value. It doesn't seem to be working because it does all the equations from top to bottom. Is there a way to switch so the calculations are done bottom to top?

Here is an example: http://jsfiddle.net/Lhp4y3q3/

**Comment by AMBudnik** [comment]
HI, we have the exact demo example from different Github account at https://github.com/handsontable/handsontable/issues/3019#issuecomment-161515844

**Comment by jjjrmy** [comment]
So there is no solution?
