### ISSUE TITLE
using walkontable scrollVertical alternative to selectCell with true option

### ISSUE THREAD

**Issue by artsince** [handsontable/handsontable#3046]
Hi, 
I am having issues with scrolling to the selected cell by using selectCell with scrollToCell option set to true. I think other people are having similar problems. (#2572)
One thing I found is to call the scrollVertical method walkontable instance like this:

```js
$hot.selectCell(i, 0, i, $hot.countCols() - 1); // select row
$hot.view.activeWt.scrollVertical(Math.max(0, i - 5)); // scroll to row with some offset
```

Is this a viable workaround? The method is very deep down in the object and I don't know if this path is likely to change. If it doesn't look very solid, is there anything else I can use?

Thank you,

**Comment by AMBudnik** [comment]
Hi @artsince sorry for a delay. I just wanted to ask did you made any progress related to this case?

**Comment by AMBudnik** [comment]
I assume that you made a huge progree since this issue was  released but feel free to leave a comment even after closing issue.
