### ISSUE TITLE
Empty space at the bottom of the table after changing height of several rows at once (programmatically or using autofilling)

### ISSUE THREAD

**Issue by Ivetta** [handsontable/handsontable#3048]
Steps to reproduce:
1. On http://handsontable.com/ change the text of the first cell so row is  stretched vertically.
![1](https://cloud.githubusercontent.com/assets/1774164/11627689/ab0afadc-9cfd-11e5-94bf-461d6d6d09db.png)
2. Copy the text of the first cell by dragging cell to **4** row.
![2](https://cloud.githubusercontent.com/assets/1774164/11627722/e44007d4-9cfd-11e5-851c-15f5988037c8.png)
3. Press  Ctrl + Z. You see only 7 rows instead of 10;
![3](https://cloud.githubusercontent.com/assets/1774164/11627770/21b38d84-9cfe-11e5-9073-de578fde740b.png)

It happens 100% times  in my project. When``selection.refreshBorders(null, true);`` is invoked in ``render`` method, I get empty space at the bottom of the table. If I invoke ``render`` method second time or scroll vertically, it helps. 
Is there any way to fix it?

**Comment by AMBudnik** [comment]
Thanks for sharing @Ivetta 
related to https://github.com/handsontable/handsontable/issues/3016

**Comment by AMBudnik** [comment]
I've tried to reproduce it with this demo: http://jsfiddle.net/ms1dtsgn/ - as the main Handsontable page was changed and there's no longer a demo at the start - and I guess it's not affected.

I'm closing this issue but if you would have any examples where this issue is replicable please let me know.
