### ISSUE TITLE
Readonly rows

### ISSUE THREAD

**Issue by selvakumar79** [handsontable/handsontable#3049]
Using the below code i have made row as read only for some condition.
cells: function (row, col, prop) {
	        var cellProperties = {};           
	        var ht = $('#dataTable').handsontable('getInstance');       
	        if( ht.getDataAtCell(row, 31) != "" || ht.getDataAtCell(row, 32) == true)
	        var rowindex = row; 
	        if(rowindex == row)
	        {
	        cellProperties.readOnly = true;
	        }
	        return cellProperties;
        }
After apply sorting in any columns its randomly made rows as readonly.

**Comment by AMBudnik** [comment]
Hi,

I made an example of your code at http://jsfiddle.net/1gkmbgp1/

I can't see 'randomly made readOnly' cells but looking at the rest of code maybe you have dynamically changed data in cells described in `if` statement?

**Comment by AMBudnik** [comment]
Issue closed cause of lack of recent activity and an author's reply.
