### ISSUE TITLE
Handsontable Performance Issue

### ISSUE THREAD

**Issue by orrihariprasad** [handsontable/handsontable#3051]
I am using handsontable 0.18.0 version in my application. In the handsontable we are loading collection of data in tree view form, We can expands their childs. If we expand the childs and update any particular cell, we are facing performance issue (it takes almost 20-30 secs) in IE browser, but in chrome it is 3-6 seconds. Without expanding nodes it will take around 3-5 Secs., only.

Can anyone suggest how to overcome this issue?

Thanks in advance.

**Comment by AMBudnik** [comment]
Hi @orrihariprasad ,
We are trying to keep Github board as a place to report bug and while we are not offering tree table (it's only in our [`feathub`](http://feathub.com/handsontable/handsontable)) I recommend searching for clues at https://stackoverflow.com/search?q=handsontable
