### ISSUE TITLE
menu button not rendering inside a column header

### ISSUE THREAD

**Issue by vrmerlin** [handsontable/handsontable#3052]
I need to provide the user with a pulldown menu inside of a column header. It's easy enough to add basic HTML through colHeaders. But, if I use JQuery and Kendo to insert a menu, it doesn't behave properly:

http://jsfiddle.net/b1k4x4qu/1/

You'll see I've made three menus. The first is outside of Handsontable, just to show the Kendo mechanics. The second is created immediately after the Handsontable is created. The third is created three seconds after the Handsontable is created. 

Both the first menu (outside the grid) and the third menu (second column header) are partially displaying underneath the table. If I resize the window, the third menu disappears entirely. The second menu (first column header) doesn't show up at all.

Handsontable doesn't appear to behave well with other libraries. I need something more sophisticated in in the Handsontable headers than basic HTML.

Thanks,
John

**Comment by vrmerlin** [comment]
My coworker made an alteration that gets a bit closer:

http://jsfiddle.net/p3zhkedw/

The menus now are at least fully showing, but the pulldowns hide under the table, and when we resize the screen, the menus disappear entirely.

**Comment by AMBudnik** [comment]
Hi @vrmerlin, as it works without outside libraries (like in the example on the bottom of the [`page`](http://docs.handsontable.com/0.17.0/demo-custom-renderers.html)) I would suggest checking topics at [`stackoverflow`](https://stackoverflow.com/search?q=handsontable). 

Handsontable's Github board is used to report bugs and feature requests that are strictly in Handsontable.
