### ISSUE TITLE
Sorting and row index

### ISSUE THREAD

**Issue by parissge** [handsontable/handsontable#3054]
I copy from the official documentation
<quote>
The indices of displayed rows are called logical indices and the indices in datasource array are called physical indices.
</quote>

A paragraph below it also says
<quote>
For example, if the cell value changes, the afterChange event is triggered. All event listeners will receive a row index of the row, where the change took place. This will be the physical index of the modified row. Same scheme applies to other events. 
</quote>

I have version 0.20.0 and I ensure you that what I get is not the physical index but the logical. I believe or the documentation is wrong or there is a bug here. What do you think?

**Comment by AMBudnik** [comment]
Hi @parissge we actually had a similar conversation (with a sorting demo) at https://github.com/handsontable/handsontable/issues/3025#issuecomment-163157791 Please take  a look at it.

**Comment by parissge** [comment]
Thank you for your response.
