### ISSUE TITLE
Incorrect param created for "replace" case in runHookForOperation

### ISSUE THREAD

**Issue by scottadmi** [handsontable/handsontable#3056]
While handling a call to custom afterChange() method I had on a table, I went to iterate over the 2-dimensional array of the changes parameter as per the spec. However, I noticed that because the change came in externally, it was only a single dimensional array representing a single change. As iterate over the list of change arrays, this broke my expected behavior by instead iterating over the 4 values of a single change.

Tracing the call in debug, I noticed this parameter originated in the "replace" case statement inside runHookForOperation() specifically the line: 
        instance.runHooks('afterChange', [parsedPath.row, parsedPath.col, null, patch.value], 'external');

To conform to the spec for afterChange(), this seems to need to be wrapped as 2-D array like:
        instance.runHooks('afterChange', [[parsedPath.row, parsedPath.col, null, patch.value]], 'external');

**Comment by AMBudnik** [comment]
issue already shared at https://github.com/handsontable/handsontable/issues/1678
