### ISSUE TITLE
CountRows() return nothing but Undefined !

### ISSUE THREAD

**Issue by max223** [handsontable/handsontable#3057]
Hello everyone :) Thank's for your time,reading my issue. 
I'm using the handsontable library since a week and i have some troubles using a couples of methods.

I have the following code in a function :

    count = $('#tableur').handsontable('countRows');
It appears that count = "undefined" when i try to print it.

My handsontable is build this way :

    var container1 = document.getElementById('tableur');

    var settings1 = {
    data: mydata,
    // colHeaders: Headers,
    minRows: 28,
    minCols: 10,
    rowHeights: 40,
    colWidths: 110,
    formulas: true,
    cells: function(row, col, prop) {
      var cellProperties = {};
      if ((~rowBigPhase.indexOf(row)) || row === 0) {
        cellProperties.renderer = bigPhasesRender;
      }
      return cellProperties;
    },
    columns: columns
    };

    var hot1 = new Handsontable(container1, settings1);

I did'nt include in the code the var Headers,mydata,columns, and the part when i get the data  via ajax or the updateSetting and the context menu, because it's useleless of course. But if you need the all code i can give it to you.

Someone on stackoverflow told me to do the counting in an after change function, i tried to do this :
thx for your answer ! Unfortunately, it didnt work, i tried to do this : 

      var afterChange = function(change,source) {
      count = $('#tableur').handsontable('countRows');
      str1 = "=SUM(E2:E"+count+")";
      str2 = "=SUM(H2:H"+count+")";
      Headers[4] = str1;
      Headers[7] = str2;
      alert(count);
     }

Or even this :

     var afterChange = function(change,source) {
     do_Ajax();
     }

    
    count = $('#tableur').handsontable('countRows');
    alert(count);

And i always getting a 
> Undefined

for the return of countRows. Starting to desperate, if i didnt do the afterChange properly can you please explain it to me ? i have read the docs ! 

Thanks much again, if anyone can help me i will be thankfull :)

**EDIT : **
Here is the fiddle :) http://jsfiddle.net/1uqztjmm/6/ :tada:

Thanks again for the support @AMBudnik

**Comment by AMBudnik** [comment]
Hi, can you put it all together in [`JSFiddle`](http://jsfiddle.net/api/post/library/pure/) of [`JSBin`](http://jsbin.com/?html,js,output)?

**Comment by max223** [comment]
I will update in 15mn with the fiddle, i'm trying to get it to work

**Comment by max223** [comment]
Here is the fiddle :) http://jsfiddle.net/1uqztjmm/6/ :tada: 

Thanks again for the support @AMBudnik

**Comment by max223** [comment]
Anyone ?

**Comment by budnix** [comment]
Hi, after investigating your demo I saw that you used `new Handsontable` to table initialization, that it is why `$('#tableur').handsontable('countRows');` expression not working. If you want to call methods in jQuery style you must initialize table in the same style. Updated demo http://jsfiddle.net/1uqztjmm/8/.

**Comment by max223** [comment]
Thanks so much @budnix , now the count rows is working, but my  hot.updateSetting {}; is not working anymore, can you indicate me how to write in the correct style  ? (or if you have a tutoriel/course about that) It will be awesome !

**Comment by budnix** [comment]
Updated demo http://jsfiddle.net/1uqztjmm/9/. `updateSettings` now working.

**Comment by max223** [comment]
Thank you so much :) !
