### ISSUE TITLE
When autoRowSize is made effective, there is a case that the height of the cell slips.

### ISSUE THREAD

**Issue by IDLOCKED** [handsontable/handsontable#3058]
This option is effective as the premise.
`autoRowSize = true`　AND　`fixedColumnsLeft : 3` is Enabled.

When autoRowSize is made effective, there is a case that the height of the cell slips.
![2015-12-10_17h48_44](https://cloud.githubusercontent.com/assets/11012887/11711045/10881b7c-9f67-11e5-9980-85f8b2600750.png)
But it's no problem under clone.
![2015-12-10_17h50_01](https://cloud.githubusercontent.com/assets/11012887/11711069/3ec6c2ae-9f67-11e5-9068-cdfb3b9bad5b.png)
Then`autoRowSize = false` doesn't occur to this problem.

How should it be done?

**Comment by AMBudnik** [comment]
Hi @IDLOCKED can you create a demo where this issue is reproducible? 

You can also use [this demo](http://jsfiddle.net/kLc5vzpg/1/) cause I assume (by the pic) that you have different widths of columns (according to content?)

**Comment by IDLOCKED** [comment]
>>You can also use this demo cause I assume (by the pic) that you have different widths of columns (according to content?)

Exactly.
The height of the cell is different in each row.
I'm sorry, I've trying to reproduce in the demo, it was not possible.



Situation
・ Version is 20.2.
・ Contains html is is in the cell.
・ Basically also enable autoRowSize does not occur.
・ But, it only occurs in a particular row.
What you want or information there is to know.
In addition, the source code for security reasons can not be published.
However, if there are the code which you want to try, I try it and can tell you about a result.

**Comment by AMBudnik** [comment]
I do understand that you don't want to publish your data but maybe you can change the content itself. I do believe that issue can be hidden in settings or maybe you use other libraries that could interfere with Handsontable?
