### ISSUE TITLE
Handsontable extends global Object prototype

### ISSUE THREAD

**Issue by floribon** [handsontable/handsontable#3059]
Hi,

I noticed that Handsontable redefines a lot of the `Object` prototype properties, such as `Object.keys`, `Object.hasOwnProperty`, etc., via the call to `polyfillObject(global.Object)`.

This should be avoided as it will collide with any other library or code trying to do the same, plus it's generally agreed it is a bad idea. Could we setup it in a mode where it would use its own private methods without messing with `Object`?

Another side effect is that any code with something like `Object.keys(null)` in a page that embeds handsontable will have a stack trace involving it, while it is absolutely not related.

**Comment by AMBudnik** [comment]
Thank you for all suggestions.

**Comment by budnix** [comment]
Confirmed.

**Comment by budnix** [comment]
Need to change Traceur runtime class shim at https://github.com/handsontable/handsontable/blob/master/src/shims/classes.js.

**Comment by jansiegel** [comment]
After implementing this we need to check if #2986 is resolved. (`iframe` IE issue)
