### ISSUE TITLE
demo-chromajs broken

### ISSUE THREAD

**Issue by xuyang2** [handsontable/handsontable#3060]
http://docs.handsontable.com/0.20.2/demo-chromajs.html
http://docs.handsontable.com/0.20.1/demo-chromajs.html

Uncaught TypeError: Cannot read property '1' of undefined
at `demo-chromajs.html:2088`

```
function updateHeatmap(change, source) { 
  // arguments: [true, undefined, undefined, undefined, undefined, undefined]
  if (change) {
	heatmap[change[0][1]] = generateHeatmapData.call(this, change[0][1]);
  } else {
```

**Comment by AMBudnik** [comment]
Thanks @xuyang2 I confirm, but I have to move this issue to the `docs` section at https://github.com/handsontable/docs/issues/25, on that board we are reporting issues that are related to ``docs.handsontable.com`` site
