### ISSUE TITLE
Update columns and data via updateSettings

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3061]
When we try to update columns and data calling `updateSettings` method then after horizontally scroll the table does not want to render the added columns.

This situation only occurs when the table was initialized with `data: []` and `columns: []`. Workaround for this bug is set `colHeaders` to `true` while first table initialization.

Demo http://jsfiddle.net/va2wffke/6/.

**Comment by AMBudnik** [comment]
updated demo (0.24.1), http://jsfiddle.net/va2wffke/11/

**Comment by AMBudnik** [comment]
Issue no longer occurs.
