### ISSUE TITLE
Cascading Dropdowns 

### ISSUE THREAD

**Issue by rajivseelam** [handsontable/handsontable#3064]
Hi,

Please check the issue at http://stackoverflow.com/questions/34243048/handsontable-select2-dropdown-options-change-for-next-row

Any solutions on how to tackle this problem? Without solving this, it's not possible to proceed. And I've not found any other solutions better than HOT. It fits perfectly for in all other scenarios, except in cascading dropdowns.

**Comment by AMBudnik** [comment]
https://github.com/handsontable/handsontable/issues/567 duplicate
