### ISSUE TITLE
Javascript error "Cannot read property 'ClassList' of undefined' with validateCells()

### ISSUE THREAD

**Issue by bpmckee** [handsontable/handsontable#3066]
If you have a table with `rowHeaders`, have scrolled horizontally, and then called `validateCells()` it throws a javascript error.

The error is in the following code:
```
_hasClass = function _hasClass(element, className) {
    if (className === '') {
      return false;
    }
    return element.classList.contains(className);
  }
```

The element exists but does not have a classList property.
My temporary workaround is by changing the return statement to `return element.classList && element.classList.contains(className);`

**Comment by AMBudnik** [comment]
Hi, please create a demo where we can experience this error. Maybe it has something to do with https://github.com/handsontable/handsontable/issues/933?

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.

**Comment by bpmckee** [comment]
Sorry, didn't see this notification until just now.  I'll try to come up with a demo in the next couple days.

**Comment by AMBudnik** [comment]
OK. I'll reopen this issue with your reply.

**Comment by bpmckee** [comment]
https://jsfiddle.net/1phsmpwg/

Here's the demo I promised.
To reproduce the error do the following:

1. Scroll over to the "Favorite Animal" column.
2. Set a dropdown
3. Click the Validate Cells button
4. Scroll back over to the start of the table.

There are two errors that happen on number 4.

1. In chrome you get the JS error I described above
2. In the few browsers that I tested, the rows that were not visible when you hit Validate Cells will no longer re-appear in the table.

**Comment by AMBudnik** [comment]
Thanks for sharing demo @bpmckee It looks definitely incorrect and after scrolling `age` column became a rowHeader.

**Comment by IgorShch** [comment]
I have the same issue.

**Comment by AMBudnik** [comment]
Issues no longer occur in 0.27.0, updated demo: http://jsfiddle.net/rv0u93mk/
Thank you for your effort to share the details.
