### ISSUE TITLE
Percentage Numeric Format

### ISSUE THREAD

**Issue by deenairn** [handsontable/handsontable#3067]
It would be good for our clients to be able to have a numeric text box that accepts a percentage using the syntax "20%" accepted as 0.2. This currently does not work (or at least I have not configured it correctly) with the current numeric text box.

**Comment by AMBudnik** [comment]
Marked as a feature request.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.
