### ISSUE TITLE
Handsontable move and resize

### ISSUE THREAD

**Issue by vallieresc** [handsontable/handsontable#3068]
I have a Handsontable in my content area where only some of the columns can be shown at a time because there are too many. What I'd like to do is, with CSS, have the table moved to the center of the screen with a backdrop overlay and have its height and width increased.

I have it mostly working except when centered and filling up rows to screen height, I get a weird behavior where the bottom rows become invisible and only the editing cell is visible. I also have the table header row repeated. What am I missing?

```
// enlarge button click
Handsontable.Dom.addEvent(enlarge, 'click', function(e) {
	e.preventDefault();

	//update hot
	hot.updateSettings({
		width: window.innerWidth - 100,
		height: window.innerHeight - 100
	});

	//backdrop
	$('body').addClass('modal-open').append('<div class="mfp-bg mfp-ready"></div>');
	
	//new position
	$('.scroll-container').css({
		position: 'absolute',
		top: '-50%',
		left: '-50%',
		'margin-top': '-50px',
		'margin-left': '-50px',
		overflow: 'hidden',
		'z-index': 10000,
		'height': (window.innerHeight - 100) + 'px',
		width: (window.innerWidth - 100) + 'px'
	});

	$('#close').show();
	$('#enlarge').hide();
});

![handsontable](https://cloud.githubusercontent.com/assets/1838943/11792548/9ea64360-a274-11e5-86c6-43e605826a3a.png)

**Comment by AMBudnik** [comment]
Hi.

Can you create a simplified example (demo code)?

**Comment by vallieresc** [comment]
Got it working.
