### ISSUE TITLE
header row z-index obscures other items

### ISSUE THREAD

**Issue by dcsan** [handsontable/handsontable#3069]
related #1591 maybe?

I'm using a table with some material-UI elements, and the hot header row always renders on top of these elements.

![image](https://cloud.githubusercontent.com/assets/514002/11797146/f773bf1c-a275-11e5-8146-cf47be8e6399.png)

![image](https://cloud.githubusercontent.com/assets/514002/11797396/7a7e282e-a277-11e5-8ca7-3fc4d48e2e14.png)

I've tried putting the HOT and the react components in container divs and setting the z-index of each, but that doesn't seem to work - unless I use absolute positioning.

I tried to dig through the styles applied to the header row but can't see any mention of z-index
so not sure where this artifact is coming from ...

![image](https://cloud.githubusercontent.com/assets/514002/11797437/b9a4a1c2-a277-11e5-9ef0-4fc60c518794.png)

![image](https://cloud.githubusercontent.com/assets/514002/11797458/dda74642-a277-11e5-8529-0532886217a1.png)

**Comment by dcsan** [comment]
also the header row will obscure this type of side navigation bar

![image](https://cloud.githubusercontent.com/assets/514002/11797780/4a8b4c2a-a27a-11e5-975d-5cfc1b629140.png)

**Comment by AMBudnik** [comment]
Hi issue https://github.com/handsontable/handsontable/issues/1591 is described for pure Handsontable instance. Your example uses another library. 

It would be great if you could create a demo where this issue is replicable.

**Comment by dcsan** [comment]
phew, OK I'll try to create a new app with this effect.

**Comment by dcsan** [comment]
OK i made a quick demo repo. 

source
https://github.com/dcsan/react-hot

demo
https://react-hot.meteor.com

note this is using meteor. to run the app locally
```
cd app
meteor
```

One thing I noticed is that there seem to be two header rows.
I added a style to the container div with `padding: 10px` and this seems to offset one copy of the header row:

![image](https://cloud.githubusercontent.com/assets/514002/11832678/a6359f80-a36f-11e5-9dbf-9716d8faf82d.png)

but the layering works fine for the row in the background (the other UI widgets go over the top of it)

![image](https://cloud.githubusercontent.com/assets/514002/11832685/b58f47e2-a36f-11e5-9a2d-84bf115ac5e9.png)

![image](https://cloud.githubusercontent.com/assets/514002/11832713/395cd1ca-a370-11e5-9b7f-e9857caffcfc.png)

**Comment by dcsan** [comment]
I noticed there are a few 3D transforms in the CSS, but removing them didn't seem to resolve the problem.

I assume this is because of trying to ensure the header row is in front of all other content when a table is scrolled, like a "sticky header". but the layering is a bit over-eager...

when I look at the computed position of the `tr` there's nothign to indicate a weird z-index

![image](https://cloud.githubusercontent.com/assets/514002/11832984/1d135d88-a373-11e5-8342-cb27da14d811.png)

![image](https://cloud.githubusercontent.com/assets/514002/11832994/2c3c88fc-a373-11e5-8fc2-4314a571c099.png)

so not sure where this translation is coming from.

however the material-ui elements do have a matrix transform applied, as part of the animation reveal effects:

![image](https://cloud.githubusercontent.com/assets/514002/11833013/7551177e-a373-11e5-8806-b1b56cb3c03f.png)

so maybe that's the problem.

**Comment by dcsan** [comment]
```html
<div style="transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; box-sizing: border-box; font-family: Roboto, sans-serif; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); box-shadow: rgba(0, 0, 0, 0.156863) 0px 3px 10px, rgba(0, 0, 0, 0.227451) 0px 3px 10px; border-radius: 0px; height: 100%; width: 256px; position: fixed; z-index: 10; left: 0px; top: 0px; transform: translate3d(0px, 0px, 0px); overflow: hidden; background-color: rgb(255, 255, 255);" data-reactid=".0.0.1"><div tabindex="0" style="transition: height 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; box-sizing: border-box; font-family: Roboto, sans-serif; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); border-radius: 0px; padding-top: 8px; padding-bottom: 8px; overflow-y: auto; overflow-x: hidden; height: 100%; outline: none !important; width: 256px; background-color: rgb(255, 255, 255);" data-reactid=".0.0.1.1"><div style="cursor: pointer; line-height: 48px; padding-left: 24px; padding-right: 24px; color: rgba(0, 0, 0, 0.870588); height: 48px; -webkit-user-select: none;" data-reactid=".0.0.1.1.$0"><span data-reactid=".0.0.1.1.$0.1">Home</span></div><div style="cursor: pointer; line-height: 48px; padding-left: 24px; padding-right: 24px; color: rgba(0, 0, 0, 0.870588); height: 48px; -webkit-user-select: none; background-color: rgba(0, 0, 0, 0.0313726);" data-reactid=".0.0.1.1.$1"><span data-reactid=".0.0.1.1.$1.1">Table</span></div></div></div>
```

**Comment by AMBudnik** [comment]
I would need my colleges to look at this case.

Currently what I found is when you take focus outside of picked div for a HOT instance (in this case `#hot`) and erase `.wtHider` width double header disappears till `#hot` get focused again.

**Comment by peller** [comment]
see also #2494

**Comment by dcsan** [comment]
the layering is fixed now, but there still seem to be double instances of the header row, however that only is noticeable if the 'padding' in CSS is used.

demo 
https://react-hot.meteor.com

![image](https://cloud.githubusercontent.com/assets/514002/11857890/26df5dd2-a411-11e5-8774-6df16be3a5f3.png)

**Comment by peller** [comment]
@dcsan try removing these z-index rules

https://github.com/ibm-et/handsontable/commit/31951c62725bab95a10535478a31ef5e2909bc55

**Comment by yash-jain** [comment]
use z-index as -1 will solve the issue for rowHeaders..Search for z-index in handsontable.full.css file and change the z-index value of ht-clone to -1 ..Some 4 values for z-index you have to change from z-index:101 or 102 or 103 to z-index:-1

**Comment by dcsan** [comment]
changing z-index to "hide" it maybe fine, but wondering why there are two copies of everything - surely that's not great for performance?
