### ISSUE TITLE
Table scrolling bug when scrollable element is window

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3070]
When we try to scroll table by selecting cell and pressing arrow key then scroll is not applied to the scrollable element. This occurs only if table has scrollable element as window object.

![scrolling](https://cloud.githubusercontent.com/assets/571316/11838879/0a89acb8-a3ea-11e5-96c4-9d4bd5f9d2b0.gif)

**Comment by krzysztofspilka** [comment]
Works like a charm now, thanks @budnix !
