### ISSUE TITLE
New feature proposal called preventOverflow

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3071]
Currently Handsontable behavior is similar to HTML/CSS. In situation when table is wider then parent element and this element has overflow: visible (or initial) style then table is overlapping parent element.

New option `preventOverflow: 'horizontal'` switches table to different behavior. In this behavior table's checking width of its parent element and if table content is wider then Handsontable creates horizontal scroll.

Connecting this new option with `stretchH: 'all'` switches table to more responsible solution.

Default option for this feature for compatibility reason should be set as `false`.

**Comment by krzysztofspilka** [comment]
Tested, by one bug added in #3108

**Comment by randyyaj** [comment]
Another bug with columnSorting: [#4303](https://github.com/handsontable/handsontable/issues/4303)
