### ISSUE TITLE
Filling the first  Drop down with data from db in handontable, and second dropdown should fill depending  on the selected value of first dropdown 

### ISSUE THREAD

**Issue by nis92009** [handsontable/handsontable#3072]

**Comment by AMBudnik** [comment]
Hi @nis92009 should I mark it as a feature request or you would like me to give you some tips how to achieve it with your code?

**Comment by nis92009** [comment]
please send me a complete code snippet ,,from ajax call to data  loading in the dropdown

**Comment by AMBudnik** [comment]
If you would like to develop this feature by your own we would be happy to help with this but the support services are a part of our commercial offer. The basic support includes help in all the issues connected with Handsontable (like preparing recipes for typical use cases, fixing bugs, etc.), but doesn't cover development on-demand like custom integrations, implementations in specific systems etc.
