### ISSUE TITLE
External stylesheets with TD border can cause word wrap

### ISSUE THREAD

**Issue by peller** [handsontable/handsontable#3074]
[demonstration](http://jsfiddle.net/w2Lzmhwd/1/)

Not sure where the measurements occur, but explicitly overriding top- and left- border widths to 0 fixes the problem: see PR #3073.

**Comment by AMBudnik** [comment]
merged with: https://github.com/handsontable/handsontable/commit/1023b3c356bbe35fac0a00a8efd0631214b381e7
