### ISSUE TITLE
Cell background color css issue.

### ISSUE THREAD

**Issue by SamMousa** [handsontable/handsontable#3075]
The background-color for css is defined as `!important` which makes it difficult to override from a renderer.

https://github.com/handsontable/handsontable/blob/master/plugins/bootstrap/handsontable.bootstrap.css#L11

There are only very few cases where using `!important` in a library is the right choice.

**Comment by rkait** [comment]
Agreed, having similar frustrations.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
