### ISSUE TITLE
This method cannot be called because this Handsontable instance has been destroyed

### ISSUE THREAD

**Issue by parissge** [handsontable/handsontable#3076]
I have a HandsOnTable with various built in editors. For all the editors that the column is setup like this
{ data: 'xxx', type: 'dropdown', strict: true, validator: xxxValidator, source: xxs } when i press enter to see the drop down i receive this exception.

With the mouse everything seems to work fine, but everything i press the Enter key in column with drop down editor i receive this error. 

Can anyone point me to the right direction to solve this issue?

Thank you.

**Comment by AMBudnik** [comment]
Hi, without a demo it would be hard to tell. Create one in your earliest convenience.

**Comment by AMBudnik** [comment]
Issue closed in lack of demo.
