### ISSUE TITLE
Date correctFormat: true has no effect

### ISSUE THREAD

**Issue by dcsan** [handsontable/handsontable#3079]
Date `correctFormat: true` formatting doesn't seem to make any difference:

```
  {
            data: 'createdAt',
            type: 'date',
            dateFormat: 'MM/DD/YYYY',
            correctFormat: true,
            defaultDate: '01/01/1900'
          }
```

![image](https://cloud.githubusercontent.com/assets/514002/11902395/5090511c-a566-11e5-8e78-2aed7ea717d4.png)

maybe related #3055

**Comment by AMBudnik** [comment]
I'm closing this issue. Please share additional information if needed at https://github.com/handsontable/handsontable/issues/1492
