### ISSUE TITLE
compatibility with immutable.js

### ISSUE THREAD

**Issue by sandys** [handsontable/handsontable#3082]
https://github.com/facebook/immutable-js/wiki/Upgrading-to-Immutable-v3

Immutablejs tries to mirror ES6 specifications. However, passing a Immutable List to handsontable does not work. 
One of the errors is handsontable using length instead of size()/count

**Comment by AMBudnik** [comment]
Hi @sandys we do not support immutable.js
Please try to check Stackoverflow topics for further tips. At Github we're trying to write only about feature requests and bugs strictly with Handsontable itself.

**Comment by sandys** [comment]
hi @AMBudnik  
thanks for replying. The bug report was to change the code to be more compliant of the direction that all other libraries are taking . For example changing size()/count. If that gets fixed, Immutable will start working automatically.
thanks

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
