### ISSUE TITLE
Skip calculateColumnsWidth if colWidths is set

### ISSUE THREAD

**Issue by azhu716** [handsontable/handsontable#3083]
Hi there,

It's cool that Handsontable only renders visible cells, just like [SlickGrid](https://github.com/mleibman/SlickGrid) does, which enables it to render large amount of data.

However when loading 500K rows of data, I found it slowed down a lot compared with 5K rows, that should not happen given the render algorithm.

After investigating a little bit, I found that Handsontable calls _calculateColumnsWidth_ before each render, which will iterate through the whole dataset to calculate a proper column width. The worse is, by setting _colWidth_, I cannot skip the step, even it's not useful anymore.

My suggestion is that we can skip _calculateColumnsWidth_ if _colWidth_ is set, which will significantly boost the performance when loading big data.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by kokhoor** [comment]
Is this issue fixed or it is still pending?

**Comment by aarondfrancis** [comment]
May be related to https://github.com/handsontable/handsontable/issues/6676
