### ISSUE TITLE
Why not use splice in removeRow?

### ISSUE THREAD

**Issue by timwis** [handsontable/handsontable#3084]
In DataMap's [removeRow](https://github.com/handsontable/handsontable/blob/master/src/dataMap.js#L269) method, why not just use `data.splice(index, amount)`?

I'm implementing handsontable with AmpersandJS (a newer, modular spin on backbone) and ran into the same issues described in the Backbone demo: adding and removing rows throws an error. Adding can be solved by simply delegating the `hackedSplice` function to `Array.prototype.slice` ([example](https://gist.github.com/timwis/a76d9c2d438bd06021cd#file-handsontable-ampersand-js-L24-L26)) but removing rows fails because you can't set `.length = 0` on a collection. But it seems like the `removeRow` method is implementing its own form of `splice` plus events/hooks. Or is there more going on than I'm realizing?

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
