### ISSUE TITLE
Virtual rendering/Scrolling - multiple custom group header is not working when scroll the Horizontally

### ISSUE THREAD

**Issue by Narayanan12345** [handsontable/handsontable#3085]
We are facing below issues in handsontable.
In my table having the two custom group header.  We are handling large sets of data(120 columns * X rows), when scroll horizontally - invisible column group header is not displaying(but data displaying correctly) instead of visible column group header only displaying.
Ex:

     A         |      B          |      C        |     D              ----> Group header 1
    A1|A2|A3   |   B1|B2|B3      |   C1|C2|C3    | D1|D2|D3     ----> Group header 2
      Col1     |     Col2        |   Col3        |  Col4            ----> Handson col header 
    Data's 1   |    Data's 2     |  Data's 3     |  Data's 4          ----> Array of data's

In my initial view, A and B section(Group header 1 and header 2) only displaying, when scroll the horizontally C and D section(Group header 1 and header 2) are not displaying(but C and D data's are displaying correctly) instead of A and B section(Group header 1 and header 2) only displaying .

This issues exists in latest Version also(v0.20.2)

Below is my sample code snippet

$(document).ready(function () {
    PopulateData();
});

function PopulateData() {
var example = document.getElementById('divContainer'),
hot1;

    var groupHeader ="tr class="top-groupheader" style="background-color:white"><th style="background-color:white" colspan=3></th><th style="font-size: 0.875rem !important;background-color:#6AA2CC;  color:white" colspan=11 data-colgroup="Fios"><div class="relative"><span class="colHeader"> A </span></div></th><th style="font-size: 0.875rem !important;background-color:#6AA2CC; color:white" colspan=11 data-colgroup="Core"><div class="relative"><span class="colHeader"> B </span></div></th><th style="font-size: 0.875rem !important;background-color:#6AA2CC; color:white" colspan=11 data-colgroup="HSI"><div class="relative" ><span class="colHeader"> C </span></div></th><th style="font-size: 0.875rem !important;background-color:#6AA2CC; color:white" colspan=11 data-colgroup="Cable"><div class="relative"><span class="colHeader"> D </span></div></th><th style="font-size: 0.875rem !important;background-color:#A77E90;  color:white" colspan=2 data-colgroup="programWork"> <div class="relative" ><span class="colHeader"> E </span></div></th><th colspan=3 style="font-size: 0.875rem !important;background-color:#729E9A;  color:white" data-colgroup="programWork"><div class="relative" ><span class="colHeader"> F </span></div></th></tr";

    var headerRow = "<tr class="header-grouping" style="background-color:white"><th style="background-color:white" ></th><th colspan="2"></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2" colspan=5  data-colgroup="jobgroup"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section A1 </span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2"  colspan= 4  data-colgroup="FIOSTechInfo" ><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader">Section A2 </span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2" colspan=2   data-colgroup="FIOSWorkLoad"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section A3 </span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2" colspan=5  data-colgroup="COREJPT"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section B1 </span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2" colspan= 4  data-colgroup="CORETechInfo" ><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section B2 </span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2" colspan=2   data-colgroup="CoreWorkLoad"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section B3 </span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2" colspan=5  data-colgroup="HSIJPT"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section C1 </span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2"  colspan= 4  data-colgroup="HSITechInfo" ><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section C2 </span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2"  colspan=2   data-colgroup="HSIWorkLoad"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section C3 </span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2" colspan=5  data-colgroup="cableJPT"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section D1</span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2"  colspan= 4  data-colgroup="CableTechInfo"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader">Section D2 </span></div></th><th style="font-size: 0.875rem !important;background-color:#c5e1f2"  colspan=2   data-colgroup="CableWorkLoad"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader">Section D3</span></div></th><th colspan= 2 style="font-size: 0.875rem !important;background-color:#e9d5da" data-colgroup="programmableTechInfo"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader">Section E1 </span></div></th><th colspan= 2 style="font-size: 0.875rem !important;background-color:#cbe1dd" data-colgroup="discretionaryTechInfo"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section E2 </span></div></th><th colspan=1 style="font-size: 0.875rem !important;background-color:#cbe1dd" data-colgroup="discretionaryWorkLoad"><div class="relative" style="color: rgb(106, 162, 204);"><span class="colHeader"> Section E3 </span></div></th></tr>";
	
	
    hot1 = new Handsontable(example, {
        data: Handsontable.helper.createSpreadsheetData(26, 50),
        colHeaders: true,
        cells: function (row, col, prop) {
            this.renderer = CustomCellRenderer;
        },
        beforeRender: function () {
            $('.header-grouping').remove();
            $('.top-groupheader').remove();
        },
        afterRender: function () {
            $('#divContainer').find('thead').find('tr').before(groupHeader).before(headerRow);
        },
        fixedColumnsLeft: 3,
        fixedRowsTop: 0,
        height: 350,
        width: 750,
        manualColumnFreeze: true,
        viewportRowRenderingOffset: 'auto',
        viewportColumnRenderingOffset: 'auto',
    });
}

function CustomCellRenderer(instance, td, row, col, prop, value, cellProperties) {
    td.innerHTML = value;
    // doing some calculation
}

Can you please help for this issues.

**Comment by AMBudnik** [comment]
Hi @Narayanan12345 can you create a live demo (using for example JSBin or JSFiddle)? It would be much easier to say anything.

**Comment by Narayanan12345** [comment]
Hi Ambudnik,

Could you please check the this issues in  jsfiddle

https://jsfiddle.net/Narayanan19/qLf3ukat/1/

Kindly let me know if you need any other information.

Thanks,
P.Narayanan

**Comment by AMBudnik** [comment]
Issue closed. Please check nested headers feature: https://docs.handsontable.com/pro/1.2.0/demo-nested-headers.html
