### ISSUE TITLE
Expend columns and rows 

### ISSUE THREAD

**Issue by palvors** [handsontable/handsontable#3086]
is it possible to get option to expend or retrect rows and columns header ?

**Comment by AMBudnik** [comment]
If we are talking about a width of a column/row you can set `manualRowMove: true` and `manualColumnMove: true`like here http://docs.handsontable.com/0.20.2/demo-moving-rows-and-columns.html

**Comment by palvors** [comment]
Hi, no I talking about collapse... i try to find option handsontable like orb  (http://orbjs.net/) , . Orb put option to rows ans colos header to expend or collapse.

Do you think that will be avaible in the next version ? Because, if handsontable compare itself to "excel webbs apps"... Excel Webbs apps can expend and collapse .

**Comment by Codearella** [comment]
Agreed. I think the collapse would be a nice feature.

**Comment by AMBudnik** [comment]
Collapsible headers of columns will be a part of Handsontable PRO. Here's the [full list](http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button) of PRO features.
