### ISSUE TITLE
Changing alignment via context menu doesn't calls afterSetCellMeta

### ISSUE THREAD

**Issue by eholin** [handsontable/handsontable#3087]
Hello!
I've update your awesome Handsontable in my project from 0.14.0 to 0.20.2 and noted that the event afterSetCellMeta no longer be triggered after change cell aligment. In your documentation (http://docs.handsontable.com/0.20.2/demo-alignment.html) this event is described as working, but as I could determine, it doesn't work, starting with version 0.17.0
This is a bug or a feature?

**Comment by AMBudnik** [comment]
Confirmed. In 0.16.0 afterSetCellMeta is trigger after a change and in 0.17.0 and newer versions it's not.

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1 http://jsfiddle.net/qtavsvd5/
Changes made by user doesn't trigger `afterSetCellMeta `

**Comment by swistach** [comment]
It's bug of contextMenu.
Methods setCellMeta & setCellMetaObject are working properly: http://jsfiddle.net/z6xcL2sc/
The same problem was with read-only #3907

**Comment by AMBudnik** [comment]
Hi @eholin 
This issue should be fixed in v0.31.1. Can you test it and let us know?

**Comment by AMBudnik** [comment]
I guess we can close this issue however if you would find anything suspicious please let us know.
