### ISSUE TITLE
UpdateSettings - Not keeping customized settings

### ISSUE THREAD

**Issue by lubianm** [handsontable/handsontable#3088]
Documentation states, about **updateSettings** method: *"Note, that although the updateSettings method doesn't overwrite the previously declared settings, it might reset the settings made post-initialization"*.
Actually this can be a big limitation because if users perform many modifications on cells settings (like read-only, text alignment, etc...) there's no way of keeping them (obviously, I mean, without saving previously those settings "manually" and restoring them after application of updateSettings method).
Do you think it would be possible to add a parameter on 'updateSettings' to enable/disable an automatic restoring of previous cells metadata ? Maybe I'm missing something ?

**Comment by AMBudnik** [comment]
Hi, which customized settings you would like to keep regardless of updateSettings?

**Comment by lubianm** [comment]
For example the 'readonly' cell setting. Anyway, more generally, all standard/custom settings defined on cells metadata. My idea is that 'updateSettings' method should do what the name suggests, that is to say *update only those settings defined on method's parameters*, but not overwrite the existing ones (despite if they've been initialized or modified after initialization).

**Comment by AMBudnik** [comment]
OK, I'll mark this idea as a feature request.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.
