### ISSUE TITLE
no main field in the package.json

### ISSUE THREAD

**Issue by dcsan** [handsontable/handsontable#3089]
a package.json should have a main field defined
https://docs.npmjs.com/files/package.json#main

> main
> The main field is a module ID that is the primary entry point to your program. That is, if your package is named foo, and a user installs it, and then does require("foo"), then your main module's exports object will be returned.
> This should be a module ID relative to the root of your package folder.

I'm having trouble getting HOT to work with meteor's package system which seems to require main to be defined. 

https://github.com/awsp/handsontable-meteor/issues/23#issuecomment-167172674

I did also look at the [custom builder](https://github.com/handsontable/hot-builder) you have but that doesn't seem to define a main field either.

I was looking at the [exports in the main /dist src](https://raw.githubusercontent.com/handsontable/handsontable/master/dist/handsontable.full.js) and still unclear what to use.

what is the entry point to the HOT code base?

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topic and uloading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Isuee will be reopene with first update.
