### ISSUE TITLE
Using mouse wheel over row header doesn't scroll the page even when it should

### ISSUE THREAD

**Issue by gstanislav** [handsontable/handsontable#3090]
http://jsfiddle.net/8prty3uw/

This example contains a handsontable in a very high page. 

Hover over a non-header cell and scroll the table down. After the end is reached, the table stops scrolling, and the page starts scrolling. This is expected behaviour.

Now reload the page, hover over a top header and scroll the table down. After the end is reached, the table stops scrolling, **but the page does not start scrolling.**

I expect it to scroll, still, because that's how scrolling elements usually behave in browsers.

---

Additional info:
1. There's a #1582, which is no longer valid, in my opinion.
2. Here's [the problematic piece of code](https://github.com/handsontable/handsontable/blob/5a8dc8c1b903a9a8be84f2da25c7b6a85bc1fee5/src/3rdparty/walkontable/src/overlays.js#L161). Instead of always cancelling the event, it should perhaps check whether it's possible to scroll table down, and only then cancel the event. 
3. In my opinion, it's actually OK for the page to scroll when hovering over headers. It feels to me as if headers are not part of the scrollable content of the table (seeing as how they don't scroll).
4. This problem is very apparent if you put several handsontables one after another, if they have non-window trimming containers. Scrolling with mouse wheel stops on each table header.

**Comment by gstanislav** [comment]
Umm, should I perhaps provide more info? Please tell me if any important details are missing.

**Comment by alexgann** [comment]
Couldn't agree more on this one.  #1582 is concerned about scrolling over **row headers**, which should work.  But preventDefault when mouse is over column headers is broken, especially when you have a dynamic table width and aren't using stretchH (because the top overlay extends to the right of the table in this case and blocks scrolling even when not over the table).

**Comment by alexgann** [comment]
I see now the condition on trimmingContainer.  In my use case handsOnTables are being used with collapsible elements (overflow: hidden), but within those elements are always full height and are not being "trimmed" to that container.  Would be nice to have a core option scrollColHeaders: true/false (default to true if you like) that is also checked in the trimmingContainer condition.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
This behavior is still replicable and it is not consistent with other spreadsheets (like GS).

While keeping the cursor on a column header, holding <kbd>SHIFT</kbd>, and scrolling we should scroll columns horizontally.
This can be tested at https://handsontable.com/docs/8.3.2/demo-scrolling.html

**Comment by AMBudnik** [comment]
This issue is no longer replicable http://jsfiddle.net/1z5eyLu4/
I checked it on Chrome 106 using the Handsontable v12.1.3.
I'm closing this issue as solved. However, if it still does not work for you, please let me know.
