### ISSUE TITLE
propToCol return wrong values after manual move of column.

### ISSUE THREAD

**Issue by lielran** [handsontable/handsontable#3091]
when manualColumnMove set to true and moving some column - propToCol return the old value of the column. 

e.g. if "email" is a column number 2 ,after manual move of email to column 7 propToCol still return index 2(even after rerender the table).

**Comment by AMBudnik** [comment]
Hi,

we will take a closer look at this subject. You have to use `columns` to prevent this bug. Example http://jsfiddle.net/jzf4pf7x/

**Comment by lielran** [comment]
I do have ```columns``` in my code.
the bug is reproduced also in the example link 
<img width="825" alt="screen shot 2016-01-12 at 4 02 17 pm" src="https://cloud.githubusercontent.com/assets/1004667/12265496/017be408-b946-11e5-98df-5857738570c7.png">

**Comment by lielran** [comment]
:+1: Thanks
