### ISSUE TITLE
Handsontable.plugins.registerPlugin does not work

### ISSUE THREAD

**Issue by zblust** [handsontable/handsontable#3093]
Using Handsontable 0.20.2, the call to Handsontable.plugins.registerPlugin (as referenced in the external plugin skeleton at https://github.com/handsontable/handsontable-skeleton/blob/master/plugins/external/externalPluginSkeleton.js) does not work.

See fiddle http://jsfiddle.net/wsv6L8fv/1/

**Comment by AMBudnik** [comment]
Confirmed, table crashes from 0.20.1 (0.20.0 is fine).

**Comment by AMBudnik** [comment]
works fine with latest version: 0.24.1, updated demo: http://jsfiddle.net/wsv6L8fv/2/
