### ISSUE TITLE
Issue after removing columns or rows

### ISSUE THREAD

**Issue by lubianm** [handsontable/handsontable#3095]
I think there's a bug when removing columns or rows on grid (through context menu):
* if you remove ALL columns but one, it won't be possible to add other new columns (instead, I think that the item in context menu should be enabled in this case, not disabled...)
* if you remove ALL columns or all rows, it won't be possible to perform any other action on the resulting grid. Here I do not know actually which solution could be the best one... Not allowing to remove ALL columns/rows ? Allow to do it but leave a couple of context menu items available ("insert new row" / "insert new column") on the only remaining grid (meta)cell (the top-left corner pseudo-cell).

You can test both behaviors on 'examples' page:
http://handsontable.com/examples.html

**Comment by AMBudnik** [comment]
Hi @lubianm 
ad.1.
It is enabled with one column. If you click <kbd>RMB</kbd> on the one left column adding new columns in available. I tested it with http://jsfiddle.net/urqgj1qf/ if I'm missing something please let me know.

ad.2.
I agree, it should be available to use context menu to add new columns.

**Comment by lubianm** [comment]
Hi @AMBudnik 
ad.1.
I tested on your jsFiddle example, but I experience the same issue: if you remove all columns from second one to the last one, the context menu items "Insert column on the left" and "Insert column on the right" are both disabled...
