### ISSUE TITLE
Editor does not set value if value is an object and the cell was empty before

### ISSUE THREAD

**Issue by timwis** [handsontable/handsontable#3096]
I'm building a key/value dropdown editor because all of the existing options (built-in select editor, select2 community editor, chosen community editor) either don't work or fall short (ie. once the editor disappears, the renderer only displays the key instead of the value).

My `data` array has an object for the column that contains the dropdown (ie. `{id: 3, value: "Foo"}`). I managed to get this to work by [overriding](https://github.com/timwis/handsontable-postgrest/blob/relationships/src/keyvalselect-editor.js) the select editor's:

1. `beginEditing` method and replacing `this.setValue(stringify(newValue))` with `this.setValue(newValue)` (remove `stringify()`)
2. `setValue` method and setting the value to `value.id` instead of just `value`
3. `getValue` method and returning an object containing the selected option's `id` and `value` properties

I noticed a few quirks that I've traced back to [this section](https://github.com/handsontable/handsontable/blob/master/src/core.js#L471-L485) of `populateArray` in core, and I'm hoping you might be able to explain why that section does what it does so I don't just hack around it unknowingly.

Namely, I noticed that if `getValue` returns an object, the object's schema must match the schema of the cell's original value. I can work around this by using `_.extend()` I imagine but I'm not sure why it's a requirement in the first place.

Second, and it's really the same issue, if the cell was empty or null prior to it being edited, `populateArray` doesn't update it at all (L472). Not sure how to get around this one because sometimes my data will be `null` for that cell.

Thanks for your guidance.

**Comment by AMBudnik** [comment]
Hi, there is one project left that is worth to look at - https://github.com/mydea/handsontable-chosen-editor
If it isn't what you are looking for, maybe it would bring you some clues.

**Comment by timwis** [comment]
Thanks @AMBudnik but if you look at my first paragraph, I've already seen that editor and dove into the code. Any thoughts on the `populateArray` logic?

**Comment by timwis** [comment]
Forgive me for being a pest, but I'm hesitant to continue my project before hearing back on this. Do you anticipate I might be able to hear from an author on what the logic was in `populateArray`? Or should I look for another approach?

**Comment by AMBudnik** [comment]
Hi @timwis sorry for a delay. I had a little chat with one of our programmers and we concluded that editor wasn't made to return object type of data.

**Comment by timwis** [comment]
Interesting @AMBudnik, the code I linked reads like it was. Well thanks for looking into it.

**Comment by AMBudnik** [comment]
hi @pflaumingo yes, unfortunately, their simple construction cannot return objects.

**Comment by swistach** [comment]
Demo: http://jsfiddle.net/ny7zm97o/
In an example you can find how to edit object property within cell.

**Comment by AMBudnik** [comment]
Hi @timwis @pflaumingo 

We just launched Handsontable v16.1.0, where you can set up your key-value dropdown/autocomplete cell.

Here is the corresponding pull request https://github.com/handsontable/handsontable/pull/11773 that also adds two new methods: valueGetter and valueSetter.

In this guide, you can test it out https://handsontable.com/docs/react-data-grid/autocomplete-cell-type/#array-of-objects, and here is the full list of changes https://handsontable.com/docs/react-data-grid/changelog/#_16-1-0 - we also added LTS support, Pagination, and a Loading screen.

Hope you'll like it.
