### ISSUE TITLE
Problem on edit number with comma decimal

### ISSUE THREAD

**Issue by carletto** [handsontable/handsontable#3097]
Hi, 

in this jsfiddle exampe: http://jsfiddle.net/bzuryajr/

if you insert in column price Euro 7000,345 and  it's ok!

but after if you select this cell end press enter for editing (number is 7000.345) and press enter for save cell value, its result is 7000345,00 

What's Wrong

thanks

**Comment by AMBudnik** [comment]
thanks for sharing @carletto we have the same issue at https://github.com/handsontable/handsontable/issues/2166 please track changes to that one for further details.
