### ISSUE TITLE
Editor scroll jumps to first column when scrolling to the last column using the arrow key

### ISSUE THREAD

**Issue by PedroTRX** [handsontable/handsontable#3098]
with stretchH property set to "last" on a large table when scrolling to the last column using keyboard right arrow the scroll jumps to the first column

this happens to me on mac with chrome (47)

I've added an example:
http://jsfiddle.net/a1Lzwho2/1/

looking in the code I see that getStretchedColumnWidth function the calculated stretchedWidth is negative and this is causing the bug.

getStretchedColumnWidth: function(sourceColumn) {
    var columnWidth = this.getColumnWidth(sourceColumn);
    var width = [void 0, null].indexOf(columnWidth) === -1 ? columnWidth : this.instance.wtSettings.settings.defaultColumnWidth;
    var calculator = this.wot.wtViewport.columnsRenderCalculator;
    if (calculator) {
      var stretchedWidth = calculator.getStretchedColumnWidth(sourceColumn, width);
        // TREX: PATCH - fix HT not to scroll when stretchedWidth is negative
      if (stretchedWidth && stretchedWidth>0 ) {
        width = stretchedWidth;
      }
    }
    return width;
  }
}, {});

**Comment by AMBudnik** [comment]
Confirmed. [Simplified example](http://jsfiddle.net/06zsjpw8/)

**Comment by AMBudnik** [comment]
Hi @PedroTRX 
I tried it with 0.24.1 and it seems to work fine.

Could you check it please? 
Here's the updated demo: http://jsfiddle.net/06zsjpw8/1/

**Comment by PedroTRX** [comment]
Yes, it seems to be fixed.

thanks!

**Comment by AMBudnik** [comment]
Thanks for feedback @PedroTRX 
Closing this issue.
