### ISSUE TITLE
Manually Trigger Handontable cell validation on external event

### ISSUE THREAD

**Issue by gauravdurgule** [handsontable/handsontable#3101]
Currently validate method gets invoked when cell is edited.
Validation of one of my columns is dependent on external input (dropdown outside of handsontable).
I want to re-validate all values in that column when external input gets changed.
Is there any way to trigger validate method manually??

**Comment by AMBudnik** [comment]
You can use [`validateCells()`](http://docs.handsontable.com/0.20.2/Core.html#validateCells) as long as I'm getting the idea of what you want to achieve.

**Comment by michailw** [comment]
Hello, I want to reopen this ticket. When I use method `populateFromArray`, handsontable doesn't mark columns with option `allowEmpty: false` as invalid.
I've tried to call `validateCells` and `render`, without positive result. Can you help me with it?

I'm using Handsontable 0.24.

Here is Video: https://youtu.be/yJi_0OrmHlw
Here is jsFiddle demo: http://jsfiddle.net/deqbgpcq/1/

**Comment by AMBudnik** [comment]
Hi @michailw 
Please take a look at this example: http://jsfiddle.net/p6f08ygr/

I guess that all cells were red as the table was validated before the data got populated.
I will leave this issue opened to check it.

**Comment by michailw** [comment]
It works, thank you.

**Comment by AMBudnik** [comment]
You're welcome Michał.
Thanks for sharing the example.

**Comment by AMBudnik** [comment]
As mentioned before the `allowEmpty` option doesn't work when we do not call the validation method inside the `afterRender `hook. 
I am marking this issue as a bug.

**Comment by AMBudnik** [comment]
Still the same behavior for version 0.35.0

**Comment by AMBudnik** [comment]
Here's `7.4.2` http://jsfiddle.net/qxr0gjzm/

The issue seems to be gone. Hey @michailw can you check?
