### ISSUE TITLE
Validate unique values within column

### ISSUE THREAD

**Issue by tnrich** [handsontable/handsontable#3102]
Hey there, 

I'm trying to create a validation function such that every value in a given column must be unique. Here's what I've done so far:
```
var hot = new Handsontable(container, {
  data: data,
  columns: [{
    validator: function validateId(value, callback) {
      var data = this.instance.getDataAtCol(this.col);
      var index = data.indexOf(value);
      var valid = true;
      if (index > -1 && this.row !== index) {
        valid = false;
      }
      return callback(valid);
    }
  }]
});
```
This solution works well if I'm editing one cell at a time, but unfortunately doesn't work well if copy/pasting multiple values at once because it only checks against data that is **already** within the column, not against the other new data that's coming in. 

Does anyone have a recommendation for fixing this? It seems like this must be a super common validation use-case.

Thanks for the awesome tool!

**Comment by AMBudnik** [comment]
Hi, did you tried rerenderind data after pasting? It should trigger your validator.

**Comment by tnrich** [comment]
I haven't tried re-rendering after pasting, but I did get it to work using this code: 
```
var hot = new Handsontable(container, {
      data: data,
      comments: true,
      columns: [{
      }, {
      }, {
      }, {
      },{},{}],
      contextMenu: true
    });
  
    hot.addHook('afterChange', function(changes, source) {
      //after every change, run validation on the "0 column"
      var instance = this;
      var column = instance.getDataAtCol(0);
      column.forEach(function(value, row) {
        var data = extend([], column);

        var index = data.indexOf(value);
        data.splice(index, 1);
        var second_index = data.indexOf(value);
        var cell = instance.getCellMeta(row, 0);
        if (index > -1 && second_index > -1 && !(value == null || value === '')) {
          cell.valid = false
          cell.comment = 'Error: Duplicates not allowed'
        } else {
          cell.valid = true
          cell.comment = ''
        }
      });
      //force a re-render so the new cell properties show up
      hot.render()

    });
```

**Comment by the-affy** [comment]
comment feature don't work with above code. after some tweaking i found a solution 

instead of using 
cell.comment = 'Error: Duplicates not allowed'

using

cell.comment ={value: 'Error: No Duplicate Value allowed !!!'}
 fixes it.


complete code:

var hot = new Handsontable(container, {
      data: data,
      comments: true,
      columns: [{
      }, {
      }, {
      }, {
      },{},{}],
      contextMenu: true
    });

hot.addHook('afterChange', function(changes, source) {
    //after every change, run validation on the "0 column"
    var instance = this;
    var column = instance.getDataAtCol(0);
    column.forEach(function(value, row) {
        var data = $.extend([], column);

        var index = data.indexOf(value);
        data.splice(index, 1);
        var second_index = data.indexOf(value);
        var cell= instance.getCellMeta(row, 0);
        if (index > -1 && second_index > -1 && !(value == null || value === '')) {
            cell.valid = false
            comments ='true'
            cell.comment ={value: 'Error: No Duplicate Value allowed !!!'}
        } else {
            cell.valid = true
            cell.comment = ''
        }
    });
    //force a re-render so the new cell properties show up
    hot.render()

});

**Comment by the-affy** [comment]
comment feature don't work with above code. after some tweaking i found a solution

instead of using
`cell.comment = 'Error: Duplicates not allowed'`

using

`cell.comment ={value: 'Error: No Duplicate Value allowed !!!'}`
fixes it.

complete code:

```
var hot = new Handsontable(container, {
data: data,
comments: true,
columns: [{
}, {
}, {
}, {
},{},{}],
contextMenu: true
});

hot.addHook('afterChange', function(changes, source) {
//after every change, run validation on the "0 column"
var instance = this;
var column = instance.getDataAtCol(0);
column.forEach(function(value, row) {
var data = $.extend([], column);

    var index = data.indexOf(value);
    data.splice(index, 1);
    var second_index = data.indexOf(value);
    var cell= instance.getCellMeta(row, 0);
    if (index > -1 && second_index > -1 && !(value == null || value === '')) {
        cell.valid = false
        comments ='true'
        cell.comment ={value: 'Error: No Duplicate Value allowed !!!'}
    } else {
        cell.valid = true
        cell.comment = ''
    }
});
//force a re-render so the new cell properties show up
hot.render()
});
```

**Comment by AMBudnik** [comment]
Hi @the-affy 

that is correct. The comment value has to be an object 

[`cell: [
  {row: 1, col: 1, comment: {value: 'Hello world!'}}
]`](https://docs.handsontable.com/pro/1.15.0/demo-comments_.html)
