### ISSUE TITLE
add attribute to cell

### ISSUE THREAD

**Issue by lethunder** [handsontable/handsontable#3103]
Hello everyone,
i want to know what is the best way to manage cell with custom attribute. I need to have the id with my td. What i did is to use 2 arrays:
1- data: the array with data
2- dataIds: array with cells' IDs from database

So to get id of cell in DB
data[3][2] => dataIds[3][2]

I create also a custom render ... 

when user delete third row for instance i have to delete third row in dataIds.

Do some one have a better solution? THANKS IN ADVANCE AND HAPPY NEW YEAR TO EVERYONE

**Comment by AMBudnik** [comment]
Hi @lethunder did you tried to use ['conditional formating'](http://docs.handsontable.com/0.20.2/demo-conditional-formatting.html)?

**Comment by lethunder** [comment]
hello AMBudnik
you mean in a custom render?

**Comment by AMBudnik** [comment]
Wherever you want a cell or group of cells to act or look as you want. Maybe you can create a demo and explain in steps what you want to achieve?
