### ISSUE TITLE
afterRender not working as expected

### ISSUE THREAD

**Issue by vrmerlin** [handsontable/handsontable#3104]
I need to add some arbitrary HTML elements (input boxes, etc) to the header in several columns. See the following example:

http://jsfiddle.net/8dnxwe2v/1/

You'll see that if I refer to a div with a header by class, I can add a button to it, but not if I refer to it by id. Why is that? It seems more appropriate to use the id, not the class, for this type of thing.

Thanks,
John

**Comment by AMBudnik** [comment]
Hi @vrmerlin 
Sorry for a delay.
Are you still looking for an answer or I can help you with something?

I'm closing this issue but feel free to leave a comment.
