### ISSUE TITLE
After column sort afterValidate logical vs physical index return wrong value

### ISSUE THREAD

**Issue by benjamin-meyers** [handsontable/handsontable#3107]
I have tried most of the suggestions about getting the physical row index, but I am still having issues.  Below is my code which continues to return the wrong row index after sorting.  

afterValidate: function (isValid, value, r, prop, source) {
   if (isSorted(hot)) {
      r = hot.sortIndex[r][0];
   }
}

function isSorted(hotInstance) {
   return hotInstance.sortingEnabled && typeof hotInstance.sortColumn != 'undefined';
}

**Comment by AMBudnik** [comment]
Hi @benjamin-meyers we have the same discussion at https://github.com/handsontable/handsontable/issues/1501
