### ISSUE TITLE
pickadate minDate not working

### ISSUE THREAD

**Issue by cskiwi** [handsontable/handsontable#3109]
I'm trying to set the minDate of a handsontable datepicker to today;

But this doesn't seem to work, all other options it picks up just fine

    document.addEventListener("DOMContentLoaded", function() {

      var container6 = document.getElementById('example');
      var hot;

      hot = new Handsontable(container6, {
        data: [
          ["30/09/2015"]
        ],
        colHeaders: ['Date'],
        columns: [{
          type: 'date',
          datePickerConfig: {
            // First day of the week (0: Sunday, 1: Monday, etc)
            firstDay: 1,
            showWeekNumber: true,
            numberOfMonths: 3,
            minDate: new Date()
          }

        }]
      });

    });

    <script src="http://docs.handsontable.com/0.20.0/bower_components/handsontable/dist/handsontable.full.js"></script> <link type="text/css" rel="stylesheet" href="http://docs.handsontable.com/0.20.0/bower_components/handsontable/dist/handsontable.full.min.css">
    <div id="example" class="hot handsontable htColumnHeaders"></div>

Any clue what I might be doing wrong?

jsFiddle: http://jsfiddle.net/mxn0fesq/

**Comment by AMBudnik** [comment]
Hi @cskiwi according to what I found in the SO phorum, to set a date for a present day you have to use `minDate: 0, // 0 days offset = today`

**Comment by cskiwi** [comment]
Seting minDate to 0 doesn't work either, you can test that in the jsFiddle

**Comment by AMBudnik** [comment]
Hi,

after some investigation I can confirm that it does not work. I made two simple examples using HOT. One with blank data and filled data and they both does not accept `minDate`.

Working demo: http://jsfiddle.net/q9b512c2/23/
Simplified hot demo: http://jsfiddle.net/mxn0fesq/1/

Thanks for sharing.

**Comment by AggieCridmus** [comment]
Hi, Is there an ETA on the fix for this bug yet? I have a production application utilizing HoT Pro and would really like to use the 'minDate' option. Thanks!

**Comment by jeanmarc78** [comment]
also interested by fix the issue
regards

**Comment by swistach** [comment]
It seems that works properly (since 0.23.0): http://jsfiddle.net/mxn0fesq/6/
@cskiwi can you confirm that works?

**Comment by AggieCridmus** [comment]
@swistach, it appears to work correctly. Possibly the missing link, at least for me, is utilizing the `datePickerConfig` property. I haven't developed any code with HoT in a while but I don't think I was aware of this property at the time and I'm not sure any Fiddle examples utilized that property as well.

**Comment by cskiwi** [comment]
@swistach it's been a while since I needed this. But by looking at your fiddle it seems to work just fine!

**Comment by 1997827** [comment]
MinDate not working , Is anyone can help this case ?

![image](https://user-images.githubusercontent.com/26776584/121502327-b07fb380-c9fd-11eb-8426-d34b9e574232.png)

**Comment by AMBudnik** [comment]
Hi @1997827 What version of Handsontable do you use?

Here's the newest one - Handsontable v9.0.0 http://jsfiddle.net/bqds4gyn/1/

Where minDate set up for today works as expected (we cannot pick any older date)

![image](https://user-images.githubusercontent.com/10757813/121515060-05ff9480-c9ed-11eb-972d-949f66d86bb8.png)

**Comment by 1997827** [comment]
Hi @AMBudnik 

1. I am using v 9.0.0 and Is there any possibility we can set come previous date as mindate  ?

2. Maxdate value also not passing as expected

Eg:  var to ='2021-12-01'

![image](https://user-images.githubusercontent.com/26776584/121520207-491f2f00-ca10-11eb-8549-6b4b36e6c135.png)

**Comment by AMBudnik** [comment]
Hi @1997827 

Here's a tip https://stackoverflow.com/questions/5511323/calculate-the-date-yesterday-in-javascript
And here's how it works in Handsontable http://jsfiddle.net/2zb45xdp/

**Comment by 1997827** [comment]
> Hi @1997827
> 
> Here's a tip https://stackoverflow.com/questions/5511323/calculate-the-date-yesterday-in-javascript
> And here's how it works in Handsontable http://jsfiddle.net/2zb45xdp/

Thank you it works fine!

For setting the Mindate for startdate and MaxDate of EndDate this concept works 

 I need to set Max date of StartDate cell with respect to Selected Date of EndDate cell

How can we set the mindate or maxdate with respect to next column of same row ? 

I saw some content related to ecofriend render but I couldn't find any solution as I expect , please help me in this case

![image](https://user-images.githubusercontent.com/26776584/121568139-fa3bbe80-ca3c-11eb-882f-ba4ff74c5d15.png)

**Comment by AMBudnik** [comment]
@1997827 he's a corresponding blog post with demos https://handsontable.com/blog/articles/2016/4/expand-your-app-with-cell-dependencies
You would need to set up a dependency between those columns and change the `minDate` via `beforeChange` for the `EndDate` column.
