### ISSUE TITLE
Row height with fixedColumnsLeft and custom HTML

### ISSUE THREAD

**Issue by AnthonyPeron** [handsontable/handsontable#3110]
Hi, I have a table with some fixed columns on left. In first column I put a number and add with a custom renderer a button to delete the line.
But the global rendering make the row height of my fixed columns different from the row height of other columns.
Here is an example : http://jsfiddle.net/rp6vwgjh/
Maybe I don't do it the right way ?

**Comment by AMBudnik** [comment]
Hi @AnthonyPeron are you still working on this one and need help?
