### ISSUE TITLE
Wrong cell height when merging cells in fixed column

### ISSUE THREAD

**Issue by Laplandia** [handsontable/handsontable#3112]
If I merge two cells in fixed row, they have single cell height.
See http://jsfiddle.net/6habsbux/. A1 cell should be twice as high. If you comment out fixedColumnsLeft option it will be the right height.

**Comment by AMBudnik** [comment]
Hi @Laplandia 
Please track changes to https://github.com/handsontable/handsontable/issues/2672 it describes the same issue.
