### ISSUE TITLE
When using several handsontable tables on one page, scrolling becomes janky (0.20.3)

### ISSUE THREAD

**Issue by gstanislav** [handsontable/handsontable#3113]
At my company, we heavily rely on handsontable and displaying several handsontable instances on one scrollable page. Update 0.20.3 made scroll on such pages very janky.

Example fiddle: http://jsfiddle.net/s6t768pq/9/

On my Macbook Pro 2012 page scroll is janky. FPS meter is about 40-45.

**Comment by AMBudnik** [comment]
Hi. We are always trying to boost performance in Handsontable but I guess 40 fps is not a bad score. Can you tell if 0.20.3 is working slower than it's previous version?
