### ISSUE TITLE
parsePath throws Exception dereferencing null match

### ISSUE THREAD

**Issue by garthgoodson** [handsontable/handsontable#3114]
The function parsePath, is being passed a path = '/filterMask'.  The match is returning null, thus parseInt(match[1]), is dereferencing null throwing an exception.  Seems like a simple check for match === null should be sufficient.

Triggered from a loadData() call after data has changed.

version 0.20.3 (using search, columnSorting)

Stack trace:
parsePath (handsontable.full.js:16928)
(anonymous function) (handsontable.full.js:16909)
removeMultipleAddOrRemoveColPatches (handsontable.full.js:16908)
cleanPatches (handsontable.full.js:16903)
runHookForOperation (handsontable.full.js:16875)
(anonymous function) (handsontable.full.js:16867)
jsonpatch.observer (handsontable.full.js:20223)

function parsePath(path) {
    var match = path.match(/^\/(\d+)\/?(.*)?$/);
    return {
      row: parseInt(match[1], 10),
      col: /^\d*$/.test(match[2]) ? parseInt(match[2], 10) : match[2]
    };
  }

**Comment by AMBudnik** [comment]
Hi @garthgoodson 
I was unable to check it. Could you share a demo (JSBin, JSFiddle)?

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo
