### ISSUE TITLE
header scroll up

### ISSUE THREAD

**Issue by chowkh** [handsontable/handsontable#3115]
Please find the header move up. I can simulate this issue quite easily. However, there are instances, where the header move up entirely. This creates confusion when user sees them and also question our data. Not a very comfortable feeling.

To simulate the below, please login to this website
demo.test.es2cloud.com/web3
login id = root, password = root
Then go to this link
http://demo.test.es2cloud.com/web3/JournalMaster?par_cmd=openform

fill in two lines or more.
Then use the middle scroll bar of the mouse to scroll down. And you should be able to simulate the problem.

![image](https://cloud.githubusercontent.com/assets/10473271/12261286/0773ffd4-b95b-11e5-80a5-e2675dde1672.png)

**Comment by AMBudnik** [comment]
Hi @chowkh can you share your code? (in example JSBin or JSFiddle)

**Comment by chowkh** [comment]
It is in servlet.

<%@page import="util.MsgPackager"%>
<%@page import="app.acc.msg.JournalMasterMsg"%>
<%@page import="app.acc.AccGLAccountTab"%>
<%@page import="app.acc.tx.GstControlMtnTS"%>
<%@page import="app.inv.InvProductDefinitionTab"%>
<%@page import="app.inv.InvUoMDefinitionTab"%>
<%@page import="util.Blank"%>
<%@page import="util.DateTimeObj"%>
<%@page import="db.DbColumn"%>
<%@page import="app.acc.AccExpenseLogTab"%>
<%@page import="java.util.ArrayList"%>
<%@page import="app.acc.tx.AccSetupInfoMsg"%>
<%@page import="app.acc.AccSetupTab"%>
<%@page import="msgbus.MsgBus"%>
<%@page import="dbschema.CodeCodeTab"%>
<%@page import="dbschema.CodeValueTab"%>
<%@page import="app.acc.tx.GstControlMtnTS"%>
<%@page import="app.acc.AccGLAccountTab"%>
<%@page import="util.Blank"%>
<%@page import="util.DateTimeObj"%>
<%@page import="db.DbColumn"%>
<%@page import="app.acc.AccExpenseLogTab"%>
<%@page import="java.util.ArrayList"%>
<%@page import="app.acc.tx.AccSetupInfoMsg"%>
<%@page import="app.acc.AccSetupTab"%>
<%@page import="msgbus.MsgBus"%>
<jsp:include page="/controlpage.jsp"/>
<jsp:include page="/login_header.jsp"/>
<%!
public String toString (String[] arr) {
    if (arr == null) return "";
    int len = arr.length;
    StringBuilder buf = new StringBuilder ();
    buf.append ("[");
    for (int i = 0; i < len; i++) {
        if (i > 0) buf.append (",");
        buf.append ("\'").append (arr[i]).append ("\'");
    }
    buf.append ("]");
    return buf.toString ();
}
%>
<script>
<%
    MsgBus mb = (MsgBus)session.getAttribute("mb");
    JournalMasterMsg jmm = (JournalMasterMsg)mb.getValue ("data");
    boolean taxinclusive = "Y".equals (jmm.inclusiveflag) ? true : false;
    ArrayList<String[]> explist = new ArrayList<String[]> ();
    StringBuilder buf = new StringBuilder ();
    buf.setLength(0);
    int len = jmm.gltlist.size ();
    for (int i = 0; i < len; i++) {
        if (i > 0) buf.append (",");
        String[] rec = jmm.gltlist.get (i);
        if (rec[1].indexOf ("'") >= 0) {
            rec[1] = rec[1].replaceAll ("'", "\\\\'");
        }
        buf.append ("'").append (rec[1]).append ("'");
    }
    String gllist = buf.toString ();

    ArrayList<String[]> list = jmm.taxcodes;
    len = list.size ();
    buf.setLength (0);
    for (int i = 0; i < len; i++) {
        if (i > 0) buf.append (",");
        String[] rec = list.get (i);
        buf.append ("'").append (rec[0]).append ("'");
    }
    String tc = buf.toString ();

    buf.setLength(0);
    list = jmm.dept;
    len = list.size ();
    for (int i = 0; i < len; i++) {
        if (i > 0) buf.append (",");
        String[] rec = list.get (i);
        buf.append ("'").append (rec[0]).append ("'");
    }
    String dept = buf.toString ();

    len = jmm.taxcodes.size ();
    // tax code, rule, type (S,P)
    buf.setLength(0);
    buf.append ("var taxcodetable = [");
    String[] rec = null;
    for (int i = 0; i < len; i++) {
        if (i > 0) buf.append (",\n");
        rec = jmm.taxcodes.get (i);
        if (rec[2].indexOf ("'") >= 0) rec[2] = rec[2].replaceAll ("'", "\\\\'");

        buf.append ("[\"").append (rec[0]).append ("\",\"").append (rec[1]).append ("\",\"").append (rec[2]).append ("\"]");
    }
    buf.append ("];");
    out.write (buf.toString ());
%>
function build (comptype, str) {
    if (isBlank (str)) return null;
    var arr = str.split (":");
    var arrobj = new Array ();
    var len = arr.length;
    for (var i = 0; i < len; i++) {
        var arr2 = arr[i].split ("|");
        var len2 = arr2.length;
        var ro = new Object ();
        for (var j = 0; j < len2; j++) {
            var arr3 = arr2[j].split ("=");
            if (arr3.length < 2) continue;
            if ("compid" == arr3[0]) ro.compid = arr3[1];
            else if ("quantum" == arr3[0]) ro.quantum = parseFloat (arr3[1]);
            else if ("subtaxtype" == arr3[0]) ro.subtaxtype = arr3[1];  // G - gst
        }
        arrobj[i] = ro;
    }
    var obj = new Object ();
    obj.rule = arrobj;
    obj.comptype = comptype;
    return obj;
}

function gettaxmethod () {
    return document.getElementById("taxinclusive").checked ? "TI" : "TE";
}
function gettaxrate (taxcode, quantity) {
    if (isBlank (taxcode)) return 0;
    var len = taxcodetable.length;
    var comptype = null;
    var tm = gettaxmethod ();
    var ruleobj = null;
    for (var i = 0; i < len; i++) {
        if (taxcode != taxcodetable[i][0]) continue;
        comptype = taxcodetable[i][2];
        ruleobj = build (comptype, taxcodetable[i][1]);
        break;
    }
    var totalwogst = 100;
    var totalamtpayable = totalwogst;
    var taxamt = 0;
    if (ruleobj == null) return 0;
    var count = ruleobj.rule.length;
    var dblvalue = totalwogst;
    var taxrate = 0;
    for (var i = 0; i < count; i++) {
        taxrate = "TI" == tm ? ruleobj.rule[i].quantum * 100/(100 + ruleobj.rule[i].quantum ) : ruleobj.rule[i].quantum;
        if ("A" == comptype) taxamt += dblvalue * taxrate/100.0;
        else if ("C" == comptype) taxamt += (totalamtpayable + taxamt) * taxrate/100.0;
        else if ("F" == comptype) taxamt += quantity * taxrate/100.0;
        else taxamt += dblvalue * taxrate/100.0;
    }
    totalamtpayable += taxamt;
    return (totalamtpayable - totalwogst)/totalwogst;
}

$(document).keyup(function(e) {
  $("input:text").focus(function() { $(this).select(); } );
  if (e.keyCode == 27)    clearform();
  else if (e.keyCode == 119) savejournal ();
});

</script>

<script data-jsfiddle="common" src="handsontable.full.min.js"></script>
<link data-jsfiddle="common" rel="stylesheet" media="screen" href="handsontable.full.min.css">
<input type="hidden" value="save" name="par_cmd" id="par_cmd">
<input type="hidden" value="<%= jmm.linkno %>" name="linkno" id="linkno">
<table border="0" width="95%"><tr><td>
<table border="0" width="100%">
    <tr><td valign="top">
        <table border="0" width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td colspan="2"><b><font size="5">Journal Maintenance</font></b></td>
                <td colspan="2" align="center"><input type="button" value="Save (F8)" name="B2" id="savebutton" onclick="savejournal ()"></td>
                <td colspan="2" align="center"><input type="button" value="Clear (ESC)" name="B2" onclick="clearform ()"></td>
            </tr>
            <tr>
                <td align="right">Journal No.</td>
                <td><input type="text" value="<%= jmm.refcode %>" name="refcode" id="refcode"></td>
                <td align="right">Date</td>
                <td><input type="text" value="<%= jmm.txdate %>" name="txdate" id="txdate" class="datepicker"></td>
                <td align="right">Job Code</td>
                <td><input type="text" value="<%= jmm.jobcode %>" name="jobcode" id="jobcode"></td>
            </tr>
            <tr>
                <td><label><input type="checkbox" name="taxinclusive" id="taxinclusive" value="ON" onchange="recalculate ()" <%= taxinclusive ? "checked" : "" %>> Tax Inclusive</label></td>
                <td><label><input type="checkbox" name="allowunbalance" id="allowunbalance" value="ON"> Allow Unbalance Posting</label></td>
                <td align="center" colspan="2"><a href="JournalMaster?par_cmd=report&linkno=<%= jmm.linkno %>">Print Journal Report</a></td>
                <td align="right">Description</td>
                <td><input type="text" name="description" id="description" value="<%= jmm.description %>"></td>
            </tr>
        </table>
        <div id="excelinput" style="width: 1100px; height: 400px; overflow: auto"></div>
        <table width="100%">
            <tr>
                <td>Total Debit</td>
                <td id="totaldebit"></td>
                <td>Total Credit</td>
                <td id="totalcredit"></td>
                <td>Difference</td>
                <td id="diff"></td>
            </tr>
            <tr>
                <td>Net Amount</td>
                <td id="netamount"></td>
                <td>Tax Amount</td>
                <td id="taxamount"></td>
                <td>Total Amount</td>
                <td id="totalamount"></td>
            </tr>
        </table>
    </td></tr>
    <tr><td valign="top"><b><font size="4"></font></b><br>
        <font color="#FF0000"><div  id="errorlist"></div></font>
    </td></tr>
</table>
        </td>
    </tr>
</table>
<script data-jsfiddle="excelinput">
function clearform () {
    allowsubmit = true;
    document.getElementById ("savebutton").disabled = false;
    document.getElementById ("txdate").value = "";
    document.getElementById("allowunbalance").value = "";
    document.getElementById("jobcode").value = "";
    document.getElementById("description").value = "";
    document.getElementById ("linkno").value = "";
    document.getElementById ("refcode").value = "";
    var data = hot.getData ();
    var len = data.length;
    data.splice (0, len);
    data[0] = ["","","","","",""];
    hot.render ();
}
function recalculate () {
    var totaldebit = 0;
    var totalcredit = 0;
    var netamount = 0;
    var taxamount = 0;
    var data = hot.getData ();
    var rowlen = data.length;
    var inclusive = document.getElementById("taxinclusive").checked;
    var amt = 0;
    var tamt = 0;
    var rate = 0;

    for (var i = 0; i < rowlen; i++) {
        if (isBlank (data[i][2]) || data[i][8]) {
            data[i][6] = "";
            data[i][7] = "";
            amt = parseFloat (data[i][4]);
            if (!isNaN (amt)) {
                totaldebit += amt;
                data[i][6] = "0.00";
                data[i][7] = amt.toFixed (2);
                netamount += amt;
            }
            amt = parseFloat (data[i][5]);
            if (!isNaN (amt)) {
                totalcredit += amt;
//console.log ("a " + i + " " + totalcredit + " " + amt);
                data[i][6] = "0.00";
                data[i][7] = amt.toFixed (2);
                netamount += amt;
            }
        } else {
            if (inclusive) {
                rate = gettaxrate (data[i][2], 0);
                amt = parseFloat (data[i][4]);
                if (!isNaN(amt)) {
                    tamt = Math.round (amt * 100.0 * rate)/100.0;
                    totaldebit += amt;
                    taxamount += tamt ;
                    netamount += amt - tamt;
                    data[i][6] = tamt.toFixed (2);
                    data[i][7] = amt.toFixed (2);
                }
                amt = parseFloat (data[i][5]);
                if (!isNaN(amt)) {
                    tamt = Math.round (amt * 100.0 * rate)/100.0;
                    totalcredit += amt;
//console.log ("b " + i + " " + totalcredit + " " + amt);
                    taxamount += tamt ;
                    netamount += amt - tamt;
                    data[i][6] = tamt.toFixed (2);
                    data[i][7] = amt.toFixed (2);
                }
            } else {
                rate = gettaxrate (data[i][2], 0);
                amt = parseFloat (data[i][4]);
                if (!isNaN(amt)) {
//                    tamt = Math.round (amt * rate * 100.0)/100.0;
                    tamt = Math.round (amt * 100.0 * rate)/100.0;
//                    tamt = amt * rate;
                    totaldebit += amt + tamt;
                    taxamount += tamt ;
                    netamount += amt;
                    data[i][6] = tamt.toFixed (2);
                    data[i][7] = (amt+tamt).toFixed (2);
                }
                amt = parseFloat (data[i][5]);
                if (!isNaN(amt)) {
                    tamt = Math.round (amt * 100.0 * rate)/100.0;
                    totalcredit += amt + tamt;
console.log ("c " + i + " " + totalcredit + " " + (amt + tamt));
                    taxamount += tamt ;
                    netamount += amt;
                    data[i][6] = tamt.toFixed (2);
                    data[i][7] = (amt+tamt).toFixed (2);
                }
            }
        }
    }
    hot.render ();
    document.getElementById("netamount").innerHTML = netamount.toFixed (2);
    document.getElementById("taxamount").innerHTML = taxamount.toFixed (2);
    document.getElementById("totaldebit").innerHTML = totaldebit.toFixed (2);
    document.getElementById("totalcredit").innerHTML = totalcredit.toFixed (2);
    document.getElementById("totalamount").innerHTML = (netamount + taxamount).toFixed (2);
    document.getElementById("diff").innerHTML = (totaldebit - totalcredit).toFixed (2);

    if (!document.getElementById ("allowunbalance").checked) {
        if (Math.round ((totaldebit - totalcredit)*100.0) != 0)  {
            validinput = false;
            document.getElementById("errorlist").innerHTML = "Amount do not balance. Difference by " + (totaldebit - totalcredit);
        }
    }
}
var allowsubmit = true;
function savejournal () {
    if (!allowsubmit) {
        alert ("Not allowed to RESAVE again as you have save it already. If you want to reedit, right click to reload");
        return;
    }
    validateall (false);
    if (!validinput) {
        alert ("Cannot save as there are errors in the data entry. " + errmsg);
        return;
    }
    var data =  hot.getData();
    var rowlen = data.length;
    var str = "";
    var amt = 0;
    for (var i = 0; i < rowlen; i++) {
        if (isBlank (data[i][0]) && isBlank (data[i][1])  && isBlank (data[i][2]) && isBlank (data[i][3])) continue;
        if (i > 0)   str += "\n";
        msgpackager.content = "";
        msgpackager.add("an", data[i][0]);
        msgpackager.add("ds", data[i][1]);
        msgpackager.add("tc", data[i][2]);
        msgpackager.add("dp", data[i][3]);
        amt = parseFloat (data[i][4]);
        msgpackager.add("dr", (!isNaN (amt)) ? Math.round (parseFloat (amt)*100.0) : "");
        amt = parseFloat (data[i][5]);
        msgpackager.add("cr", (!isNaN (amt)) ? Math.round (parseFloat (amt)*100.0) : "");
        amt = parseFloat (data[i][6]);
        msgpackager.add("tax", (!isNaN (amt)) ? Math.round (parseFloat (amt)*100.0) : "");
        amt = parseFloat (data[i][7]);
        if (isNaN(amt)) {
            alert ("Cannot save because total INVALID total amount at line " +(i+1) + " , " + data[i][7]);
            return;
        }
        msgpackager.add("tot", isNaN (amt) ? "" : Math.round (parseFloat (amt)*100.0));
        msgpackager.add("adj", data[i][8] ? "Y" : "N");
        msgpackager.add("brtsn", data[i][9]);
        str += msgpackager.content;
    }
    var url = "&par_cmd=save&txdate=" + document.getElementById ("txdate").value;
    url += "&linkno=" + document.getElementById("linkno").value;
    url += "&taxinclusive=" + (document.getElementById("taxinclusive").checked ? "Y" : "N");
    url += "&allowunbalance=" + (document.getElementById("allowunbalance").checked ? "Y" :"N");
    url += "&refcode=" + document.getElementById("refcode").value;
    url += "&jobcode=" + document.getElementById("jobcode").value;
    url += "&entries=" + encodeURIComponent (str);
    url += "&description=" + encodeURIComponent (document.getElementById("description").value);
    ajaxpostservlet ("JournalMaster", url, savetrap);
}
function savetrap (str) {
    allowsubmit = false;
    var arr = msgPackager (str);
    document.getElementById ("linkno").value = arr["linkno"];
    document.getElementById ("refcode").value = arr["refcode"];
    alert ("Successfully post journal entries");
    document.getElementById ("savebutton").disabled = true;
}

var descriptionvalidator = function (value, callback) {
  setTimeout(function(){
      if (isBlank (value)) {
          callback (true);
      } else if (value.length > 250) {
          callback (false);
      } else callback (true);
  }, 0);
};
var moneyvalidator = function (value, callback) {
  setTimeout(function(){
      if (isBlank (value)) callback (true);
      var amt = parseFloat (value);
      if (amt < 0) callback (false);
      callback (true);
  }, 0);
};

var validinput = false;
var errmsg = "";
function validateall (val) {
    validinput = true;
    errmsg = "";
    var data =  hot.getData();
    var rowlen = data.length;
    var found = false;
    msgpackager.content = "";
    for (var i = 0; i < rowlen; i++) {
        if (i > 0) {
            if (dle) errmsg += "\n";
        }
        var dle = false;    // detect line error
        if (i == rowlen - 1) continue;  // ignore last line
        if (isBlank (data[i][0]) && isBlank (data[i][1]) && isBlank (data[i][2]) &&
            isBlank (data[i][3]) && isBlank (data[i][4]) && isBlank (data[i][5]) && isBlank (data[i][2])) continue;
        msgpackager.add("" + i, data[i][0]);
        if (isBlank (data[i][0])) {
            validinput = false;
            dle = true;
            errmsg += "Line " + (i+1) + " Account cannot be blank.";
        } else {
            var xlen = gltable.length;
            found = false;
            for (var xi = 0; xi < xlen; xi++) {
                if (gltable[xi] == data[i][0]) found = true;
            }
            if (!found) {
                errmsg += "Invalid account at line " + (i+1);
                validinput = false;
            }
        }
        if (data[i][4] == null && data[i][5] == null) {
            errmsg += (dle ? "." : "Line " + (i+1)) + " Amount cannot be zero.";
            validinput = false;
        } else if (data[i][4] != null && data[i][5] == null) {
            if (data[i][4] == 0) {
                errmsg += (dle ? "." : "Line " + (i+1)) + " Not allowed to have both debit and credit entry in the same transaction.";
                validinput = false;
            }
        } else if (data[i][4] == null && data[i][5] != null) {
            if (data[i][5] == 0) {
                errmsg += (dle ? "." : "Line " + (i+1)) + " Not allowed to have both debit and credit entry in the same transaction.";
                validinput = false;
            }
        } else {
            if (isBlank (data[i][4]) && isBlank (data[i][5])) {
                errmsg += (dle ? "." : "Line " + (i+1)) + " Not allowed blank in both debit and credit entry.";
                validinput = false;
            }
            if (data[i][5] != 0 && data[i][4] != 0) {
                errmsg += (dle ? "." : "Line " + (i+1)) + " Not allowed to have both debit and credit entry in the same transaction.";
                validinput = false;
            }
        }
        if (!isBlank (data[i][2])) {
            var xlen = tctable.length;
            found = false;
            for (var xi = 0; xi < xlen; xi++) {
                if (tctable[xi] == data[i][2]) {
                    found = true;
                }
            }
            if (!found) {
                errmsg += "Invalid tax code at line " + (i+1);
                validinput = false;
            }
        }
        if (!isBlank (data[i][3])) {
            var xlen = depttable.length;
            found = false;
            for (var xi = 0; xi < xlen; xi++) {
                if (depttable[xi] == data[i][3]) {
                    found = true;
                }
            }
            if (!found) {
                errmsg += "Invalid tax code at line " + (i+1);
                validinput = false;
            }
        }
    }
    if (val) ajaxpostservlet ("JournalMaster", "par_cmd=gettaxcode&data=" + encodeURIComponent (msgpackager.content), taxcodetrap);
    document.getElementById("errorlist").innerHTML = errmsg;
    recalculate ();
}
function taxcodetrap (str) {
    if (isBlank (str)) return;
    var arr = str.split ("\n");
    var len = arr.length;
    var data =  hot.getData();
    for (var i = 0; i < len; i++) {
        var rec = arr[i];
        var arr2 = rec.split ("=");
        if (arr2.length != 2) continue;
        if (!isBlank (data[arr2[0]][2])) continue;
        data[arr2[0]][2] = arr2[1];
    }
    hot.render ();
}

<%
    buf.setLength (0);
    if (!Blank.isblank (jmm.entries)) {
        String[] arr = jmm.entries.split ("\n");
        len = arr.length;
        MsgPackager mp = new MsgPackager ();
        String s = "";
        for (int i = 0; i < len; i++) {
            if (Blank.isblank (arr[i])) continue;
            mp.clear();
            mp.setExpression(arr[i]);
            if (i > 0) buf.append (",");
            s = mp.getValueWNE ("an");
            if (Blank.isblank (s)) s = "";
            else {
                if (s.indexOf ("'") > 0) {
                    s = s.replaceAll ("'", "\\\\'");
                }
            }
            buf.append ("[\'").append (s).append ("\',");
            s = mp.getValueWNE("ds");
            if (s.indexOf ("'") > 0) {
                s = s.replaceAll ("'", "\\\\'");
            }
            buf.append ("\'").append (s).append ("\',");
            buf.append ("\'").append (mp.getValueWNE("tc")).append ("\',");
            buf.append ("\'").append (mp.getValueWNE("dp")).append ("\',");
            s = mp.getValueWNE ("dr");
            if (Blank.isblank (s)) buf.append ("\'\',");
            else  buf.append ("\'").append (Double.parseDouble (s)/100.0).append ("\',");
            s = mp.getValueWNE ("cr");
            if (Blank.isblank (s)) buf.append ("\'\',");
            else  buf.append ("\'").append (Double.parseDouble (s)/100.0).append ("\',");
            buf.append ("'','',");
            s = mp.getValueWNE("adj");
            buf.append ( "Y".equals (s) ? "true" : "false");
            buf.append (",'").append (mp.getValueWNE("txseqnoval")).append ("\'");
            buf.append ("]");
        }
    } else {
        buf.append ("['','','','','','','','',false]");
    }
    String ss = buf.toString ();
%>
var excelinput = document.getElementById('excelinput');
var tctable = [<%= tc %>];
var depttable = [<%= dept %>];
var gltable = [<%= gllist %>];
var settings1 = {
    data: [ <%= ss %>  ],
    minSpareRows: 1,
    contextMenu: true,
    rowHeaders: true,
    colHeaders: true,
    colWidths: [200, 250,50,80,100,100,80,100,50],
    manualColumnResize: true,
    manualRowResize: false,
    removeRowPlugin: true,
    outsideClickDeselects: false,
    enterMoves: {row: 0, col: 1},
    autoWrapRow: true,
    autoWrapCol: true,
    enterBeginsEditing: false,

    beforeChange: function (changes, source) {  },
    afterChange: function (changes, source) {
        if (source !== 'loadData') {
            validateall (true);
        }},
        colHeaders: ['Account Name','Description', 'Tax Code', 'Dept', 'Debit', 'Credit', 'Tax Amt', 'Amount', 'Adj', "txseqno"],
        columns: [{data : 0,
                type : 'autocomplete',
                strict : true,
                filter : true,
                source : [ <%= gllist %> ] },
            {data : 1,validator: descriptionvalidator, allowInvalid: true},
            {data : 2,type : 'autocomplete', strict : true, source : ["", <%= tc %>]},
            {data : 3,type : 'autocomplete', strict : true, source : [ "", <%= dept %>]},
            {data : 4,type : 'numeric', format : '$ 0,0.00', validator: moneyvalidator, allowInvalid: true},
            {data : 5,type : 'numeric', format : '$ 0,0.00', validator: moneyvalidator, allowInvalid: true},
            {data : 6,type : 'numeric', format : '$ 0,0.00', readOnly: true},
            {data : 7,type : 'numeric', format : '$ 0,0.00', readOnly: true},
            {data : 8,type: 'checkbox'},
            ]
    };

    var hot = new Handsontable(excelinput,settings1);

    function showvalue () {
        var data =  hot.getData();
    }
    $(function() {
        initjquery ();
        hot.selectCell(0,0);
        recalculate ();
    });
$("#my-div-frame-wrapper").resizable({
    alsoResize : '#myframe'
});

</script>

<jsp:include page="/login_trailer.jsp"/>

**Comment by AMBudnik** [comment]
There's not much I can do with this part of code. Please take this Handsontable example http://jsfiddle.net/7rn3xcac/ and fill it with your code that way to reproduce the same issue.
