### ISSUE TITLE
Specifying maxRows less then data length breaks autocomplete

### ISSUE THREAD

**Issue by Laplandia** [handsontable/handsontable#3117]
See http://jsfiddle.net/s1p64741/2/
If I delete the value in C10 and try to select a new value from the autocomplete dropdown, autocomplete dropdown does not close and I cannot continue working on the table.

Expected behaviour: I would expect to see only first maxRows rows.

**Comment by AMBudnik** [comment]
Confirmed. Editor should let user to continue his work. When we comment `maxRows` in instance's settings it works fine.

**Comment by AMBudnik** [comment]
still present in 0.24.1

**Comment by AMBudnik** [comment]
Still present in 0.27.0

**Comment by swistach** [comment]
Hi @Laplandia,
In 0.29.2 we fixed `maxRows`. Could you verify this issue with 0.29.2?

**Comment by Laplandia** [comment]
Yes, it works now. Thanks.
