### ISSUE TITLE
Missaligned rows with row headers after zooming

### ISSUE THREAD

**Issue by azyubin** [handsontable/handsontable#3118]
Hello,

I am attempting to create a custom column that holds actions for each row such as delete action. I am using custom renderers to create a button element and associate an appropriate action. However, after the column is added I noticed that if you change zoom on your browser you row headers and rows themselves become miss aligned. I was wondering if any one know how I can solve this problem.
![imageofmissalignement](https://cloud.githubusercontent.com/assets/7719152/12272628/561077ca-b916-11e5-9b44-bc0dfaacf510.PNG)

Here is JSFiddle with sample of the code: http://jsfiddle.net/26gLz0zf/

Thank you.

**Comment by AMBudnik** [comment]
Thanks for sharing @azyubin. Confirmed with zoom in and out on all major browsers.

**Comment by AMBudnik** [comment]
still reproducible, v 0.27.0: http://jsfiddle.net/v6oqbda4/

**Comment by twitchax** [comment]
Looks like rendering while scrolling is also similarly affected: there are artifacts at the edges (especially noticeable when scrolling up).

https://1drv.ms/v/s!AkVm727CuAMs5q1n8UZ2wCazxEaTHw

In my case, the zoom level of the browser is unchanged, but I have a 4K monitor set to 150% scaling (in Windows).  Setting to 100% scaling (in Windows) _completely resolves_ the issue.

**Comment by dctucker** [comment]
This page is linked from here https://forum.handsontable.com/t/scroll-problem-in-chrome-with-zooming/643/10 ...

It's been mentioned that it's a pixels vs ems vs percent issue. I'd like to jump in and try to solve this problem, even if it's a huge rewrite — I'd appreciate any advise on what section of code to begin looking at and tweaking to alter this unusual behavior when zoomed.

**Comment by AMBudnik** [comment]
Hi @dctucker
The fixed pixel values are all around the entire handsontable.full.js file and it also does not mean that using more responsive values will fix the issue. Please remember that we are working on TD elements.
I'd be more than happy to see a table that stretches without any issues while we zoom in and out but that is a huge project you're planning.

**Comment by dctucker** [comment]
I've noticed this problem occurs when scrolling on certain zoom ratios. For example, if I zoom to 67%, the error persists, but when loading the page at 50% zoom everything works as it does at 100% zoom. Might this be a problem related to integer division?

Regarding getting a table that stretches without any issues while zooming in and out, Datatables is a good example of this without spreadsheet functionality, which that leads me to believe the problem is solvable in this plugin and a bug in the browser's rendering engine.

**Comment by AMBudnik** [comment]
I really would like to suggest anything but the issue has been raised a long time ago and we did not test any solutions yet. I really would like to avoid giving false tips.

**Comment by dctucker** [comment]
Hit me offline then. I'm motivated. casey.tucker@brax.io

**Comment by AMBudnik** [comment]
Hi @dctucker 

sorry for keeping you waiting for so long. I know that you have a lot of will power to fix the issue and as I have spoken with one of our devs your approach sounds like a good path.
I have been told that we are using `parseInt` to set up heights via Walkontable and that why after some time we get the misaligned cells. 

ps. I'd be more than happy to get a pull request from you.
ps.2. Please delete your email from the last comment. Spammers are everywhere just waiting to harvest some juicy emails ;-)

**Comment by dctucker** [comment]
No worries. I got around to debugging a little bit today and found that `Overlays.onTableScroll()` is not getting called when it's supposed to, when Chrome is zoomed to 67%.

**Comment by AMBudnik** [comment]
I really appreciate your effort to share the results and investigate this issue @dctucker

**Comment by AMBudnik** [comment]
The issue is still[ replicable in v `2.0.0.`](http://jsfiddle.net/36ukhyze/) zoom `+175%`

![image](https://user-images.githubusercontent.com/10757813/38810181-3a1bd47e-4186-11e8-9427-ea5a823e8622.png)

**Comment by AMBudnik** [comment]
Hi @larvanitis 
Wouldn't you like to create a pull request? By adding tests we will be able to verify if the proposed solution works better than what we have now. You've done a lot of work with investigating this issue so it would be great to see you among our official contributors.

**Comment by yashu321** [comment]
Hi @AMBudnik 
When I made my handsontable with fit to screen changes (using plugin stretcH:all) ,it was acting weird for different monitors. Working properly for "acer"/"HP" but not for "ViewSonic" monitors. Is there any solution for this issue? Can you provide any suggestion that how it can be made all monitors compatible when all monitors are at default zoom level.

**Comment by AMBudnik** [comment]
Hi @azyubin 
the issue with zoom is also associated with the screen resolution so it may not work for all the monitors. It is really hard to check if we do not own this kind of devices.

**Comment by brianxautumn** [comment]
I tried the mod from @larvanitis and it is so far working for me, but there are still other scaling artifacts, but at least the rows are aligned.

**Comment by brianxautumn** [comment]
It also works if you set the height on a div inside the td, like in the case with the row header, but its messy if there is no row header.

**Comment by AMBudnik** [comment]
I guess that we need to do something here sooner than later, as there are more examples where the table is misaligned or misses borders with 125% zoom.
The scale of this issue can raise with time as newer devices working on Windows set 125% zoom as the default value.

**Comment by kyle-msm** [comment]
Bumping this thread as it's still an issue (and an annoying one too :stuck_out_tongue:)

http://jsfiddle.net/vpabm0y7/4/

**Comment by niketjsh** [comment]
Hey i am having an similar issue like if i zoom the browser from 125% to 175% the fixedColumnLeft and unfixed right columns are mismatching, last row is repeating can you please help to fix this issue

**Comment by AMBudnik** [comment]
@niketjsh we do not have this topic on our Roadmap for July but I'll update you once we get any news on that subject.

**Comment by oskrd** [comment]
> Hi @larvanitis
> Wouldn't you like to create a pull request? By adding tests we will be able to verify if the proposed solution works better than what we have now. You've done a lot of work with investigating this issue so it would be great to see you among our official contributors.

Hi, was a PR created related to that suggestion? 
I see @larvanitis is now a contributor, perhaps due to another issue.

**Comment by AMBudnik** [comment]
Hi @oskrd zooming issue hasn't been solved yet. There are no open/pending pull requests/commits related to this subject.

**Comment by oskrd** [comment]
I adapted the proposed change to the current code structure in HoT 8.0.0 and it fixed two of my issues.
The thing here is I have no idea how to write a test (e2e) to zooming cases, have you ever wrote something related to guide me?

**Comment by larvanitis** [comment]
@oskrd Unfortunately, I no longer use HOT and no PR was ever created.

**Comment by oskrd** [comment]
@larvanitis could you please write me an email? I would like to ask you something.

**Comment by swistach** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of Interoperability problems using zoom/system UI scaling and some core features task reported at #7527 

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behaviour feel free to contact me at

**Comment by AMBudnik** [comment]
While testing please use the following setup as well

* zoom level of the browser : issue replicable in all zoom level. We mainly use 80%
* zoom level of the device: 150%
* 64-bit operating system, x64-based processor. V- 22H2
* Chrome browser Version 109.0.5414.120
* Screen resolution 1920 x 1080

**Comment by AMBudnik** [comment]
Hi @azyubin @oskrd @larvanitis @astuppad @kyle-msm @yashu321 @brianxautumn @dctucker @twitchax 

I was testing Handsontable v14.1.0 (latest version) on Chrome 121 and it seems that the only issue with zoom is a cut row/column header next to the scrollbar. But rows are not misaligned.

### 80%
![80](https://github.com/handsontable/handsontable/assets/10757813/78a184b1-d53d-4002-a7aa-cf7e00a9eba2)

### 50%
![50](https://github.com/handsontable/handsontable/assets/10757813/acce5568-b0f7-45fa-9496-d1fbf4ed875d)

Did you also experience improvement in this matter on newer browsers? 

It seems that misalignment may happen with some custom renderers and `fixedColumnsLeft` + zoom.

**Comment by AMBudnik** [comment]
Hi @azCodeShayper @twitchax @dctucker @oskrd 

We identified that this issue is no longer replicable using modern browsers (even in older versions like v14).

Could you please confirm?
