### ISSUE TITLE
Custom fixed rows/columns

### ISSUE THREAD

**Issue by tikitikifoofoo** [handsontable/handsontable#312]
It would be nice to able to fix a row or column besides just the headers. For example, maybe I want to fix the bottom row so that everything scrolls in between the top and bottom rows, or fix the far right column so that everything scrolls in between the far left and right columns.

**Comment by AMBudnik** [comment]
Totals are mentioned in https://github.com/handsontable/handsontable/issues/414 issue.

**Comment by qetr1ck-op** [comment]
+1 for fixed right option

**Comment by munkh-altai** [comment]
+ right option

**Comment by AMBudnik** [comment]
Hi guys,

This option is available in Handsontable PRO: https://docs.handsontable.com/pro/1.7.4/Options.html#fixedRowsBottom

**Comment by Freemahn** [comment]
Still, is there a way to make a right column(s) fixed?

**Comment by AMBudnik** [comment]
Hi @Freemahn 
unfortunately not, you can fix column left, top and bottom.

**Comment by afiq92** [comment]
Hi,
Is there any ways to make multiple columnFreeze at once?

**Comment by AMBudnik** [comment]
Hi @afiq92 

yes, [manualColumnMove](https://docs.handsontable.com/pro/1.13.0/Options.html#manualColumnFreeze) can take an array of indexes as well.

**Comment by afiq92** [comment]
Hi @AMBudnik 

thanks for that, but i still cannot understand how to loop in handsontable

**Comment by AMBudnik** [comment]
Hi @afiq92 

I am sorry. I have written you about moving, not freezing.

Here is how we can freeze columns http://jsfiddle.net/2wz6cz9s/ via `ManualColumnFreeze` plugin with the `freezeColumn` method. The following method freezes a single column (we pass an index of it).

However it seems to work with an issue, it doesn't take the correct column index. It always takes the first column.

**Comment by afiq92** [comment]
Hi @AMBudnik 
Thanks for that idea. The idea that i want is like fixed column dynamically . e.g : column A,B,C,D,E,F,G,H,I,J ( 10 columns), a text box on top of the table, if i type 3 and click on the button, 3 column(A,B and C) will be freeze.
Btw, thanks for giving me those great idea
