### ISSUE TITLE
Object Cell value structure comparer too strict

### ISSUE THREAD

**Issue by ohadb1** [handsontable/handsontable#3120]
In v 0.20.3, populateFromArray(), a cell change is not rendered if the object value doesn't have the same property structure as the old value. The property structure is tested by parsing a stringified JSON.
This causes us problem when the property value is an object of its own (we use quite complex objects). I wonder why it has to be so strict.
1. you can always compare the toString() of the old value to the new string.
2. you can check that both objects are of the same class by instanceof.

**Comment by AMBudnik** [comment]
Hi @ohadb1 I made an example with object type data http://jsfiddle.net/zp3vrcoh/ can you please guide me how to check this behaviour?

**Comment by ohadb1** [comment]
In your example, let's say that we look at a more complex object such as in:
{car: {name:"Mercedes A 160", manf:"Mercedes", model:"A 160", detail:{a:1, b:2}, toString:function() {return "Mercedes A 160";}}, year: 2011, price_usd: 7000, price_eur: 7000}

And the structure of the detail property is ambiguous, and it can have any number of key-value pairs of details about the car object. The previous version allowed me to change the string in the cell, and I could do with it whatever I wanted in afterChange to generate a real Car object, or build a Car editor that will return a Car object and will update the car name, but what if I want to update the detail field in this process, in a way the detail field will have a different set of key-value pairs?

I agree that there is a lot of sense in making the value type-strict if it would respect instanceof, but the less strict version was actually very flexible and comfortable to work with (was somewhat inconsistent and messy in points whether you get the value as string or as an object, but that's another issue and easily worked around).

**Comment by AMBudnik** [comment]
OK, first of all please take a look at our last changes https://github.com/handsontable/handsontable/releases
we did not change anything related to this subject in previous versions so if that was somehow changed we have to find the reason.

I tried to work with you data but it will be best solution to provide us a live example of code where this issue is replicable. Could you please create a demo where step by step we could find what's causing the change and see what has been changed exactly?

**Comment by ohadb1** [comment]
Aleksandra, you’re absolutely right.  I will provide an elaborate example. Will take some time to create it. I’ll post when ready.

**Comment by AMBudnik** [comment]
Issue closed till an author's reply.
