### ISSUE TITLE
Using wrong value of prop during column measurement

### ISSUE THREAD

**Issue by aaronbrowder** [handsontable/handsontable#3121]
When Handsontable is rendering, it calls each cell's render function twice: once for measuring the cell and a second time for actually rendering it. Here is an example of my rendering function:

dropdownRenderer = function(instance, td, row, col, prop) {
    ...
}

I have noticed that during the first pass, the "prop" parameter is incorrect. This is because of the following line in handsontable.js:

renderer($__5.hot, td, row, column, $__5.hot.**colToProp(row)**, string.value, cellProperties);

See, it is calculating prop based on the row instead of the column.

**Comment by AMBudnik** [comment]
Hi @aaronbrowder can you provide a line number or a `src` catalog directions? The provided line above is from a compiled file as far as I am aware.

**Comment by aaronbrowder** [comment]
Looks like it's src/utils/ghostTable.js line 214

**Comment by jansiegel** [comment]
@aaronbrowder you're right, this was definitely not intended :) Thanks for reporting!

Also, related to #2830 (the fix is pushed under that issue number).

**Comment by AMBudnik** [comment]
fixed with https://github.com/handsontable/handsontable/releases/tag/0.21.0
