### ISSUE TITLE
getCell() return th

### ISSUE THREAD

**Issue by ciffel** [handsontable/handsontable#3122]
Please refer this demo: http://jsfiddle.net/mingc/js7akmex/

hot.getCell() with col equals to (first rendered column - 1) returns a th.

**Comment by krzysztofspilka** [comment]
@ciffel and that's correct. In Handsontable's architecture all negative indices returns "th" which refers to the particular header of a column or a row. Just like in the plain html table in which you can have the following structure:

```
<thead><tr><th></th></tr></thead>
<tbody><tr><td></td></tr></tbody>
```
