### ISSUE TITLE
Getting 2 rows of data when pasting to one row in Chrome.

### ISSUE THREAD

**Issue by nicam** [handsontable/handsontable#3123]
Hi There

There's an issue in Handsontable when it's used inside an Angular2 application.
When you copy a row and paste it into a different row on Chrome, 2 rows are inserted instead of one.

![Gif Showing the Error](http://g.recordit.co/ibpy9VgiT2.gif)

It only happens when Handsontable is running inside Angular2. I think this is somehow related to ZoneJS since this issue seems also be happening in MeteorJS when the ZoneJS Bundle is used there (https://github.com/awsp/handsontable-meteor/issues/17).

You can reproduce it here: https://valor-software.github.io/ng2-handsontable/

**Steps to reproduce:**
- Open example page in Chrome (47.0.2526.111)
- Click on a single row
- CMD+C (on Mac)
- Click on a different row (has to be writable)
- CMD+V

Two rows are inserted.

Any idea why ZoneJS might cause this issue on Chrome?

Best regards

Pascal Helfenstein

**Comment by nicam** [comment]
Any news on this?

**Comment by budnix** [comment]
Hi @nicam Handsontable for Angular2 (https://valor-software.github.io/ng2-handsontable/) is not supported by our team. It's an external library wrote by someone else. 

But looking into code I saw that they using older version of Handsontable (0.18.0). This bug what you mentioned above I assume that no longer exists in the latest version. You can try to overwrite older version by executing `bower install handsontable#0.21.0` but this solution can brake compatibility with ng2-handsontable.

**Comment by nicam** [comment]
Hi @budnix, the issue still persists with #0.21.0. I'm not using ng2-handsontable. I just posted the ng2-handsontable for you to be able to reproduce it.

I implemented handsontable into my Angular2 application myself. The issue seems to happen as soon as handsontable is running in an Angular2 Application.

**Comment by budnix** [comment]
Yes you are right after upgrade [demo](https://valor-software.github.io/ng2-handsontable/) to hot v0.21.0 I have the same issue. We need more time to investigate this.

**Comment by nicam** [comment]
@budnix ok, thanks for your help :)

**Comment by poxrud** [comment]
This is an issue with Zone.js in Angular2. I have sent a PR and am just waiting for it to be approved. 
Another option is I can send a 1 line PR to Hansontable that will fix it.

**Comment by nicam** [comment]
Thanks for your help. @poxrud could you tell me what 1liner fixed it in handsontable so I can monkey patch it until ZoneJs is updated?

**Comment by poxrud** [comment]
@nicam take a look at my PR #3195.

**Comment by nicam** [comment]
@poxrud Thank you very much! <img src="https://i.imgur.com/uStmTKe.gif">
