### ISSUE TITLE
Hover in a dropdown/context doesn't work precisely

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3125]
In an dropdown/context menu option having a submenu the area near the inside edge reacts badly when hovered.

This is easy to reproduce in an Examples page on https://handsontable.com/examples.html but hard in docs or JSFiddle.

**Comment by budnix** [comment]
Some ideas on how to improve opening/closing submenu menu.

- If there is a inactive position in a menu (like "Insert column") then when I click it, the menu should not get closed.
- If I open the submenu/filter menu and click anywhere in the main menu then the submenu/filter menu should get closed.
- If I click in the menu option that has a child submenu (for example "Alignment") then the menu should not get closed.

**Comment by krzysztofspilka** [comment]
Holey Smokey, it works:) However, I've added a new issue considering the submenu overlapping the context menu here: #3251
