### ISSUE TITLE
The column header is not floating properly

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3127]
In this official "Performance test" demo when you scroll down through the table, the column header suddenly hides. It may be a problem with headers as you can see when you add row headers:

http://jsfiddle.net/mkw6gyoh/

**Steps to reproduce the main problem:**
1. Go to http://jsfiddle.net/handsoncode/b5rvw5zk/
2. Scroll down the table
3. After the mid-height the header will unexpectedly disappear

Preview:
https://gyazo.com/18a6d89b61a4da37e9471bf970f3b319

:information_source:

> Handsontable - latest
> Windows 8.1
> Chrome - latest

**Comment by AMBudnik** [comment]
Still present in 0.30.1

**Comment by AMBudnik** [comment]
The issue in v0.35.0 remains the same 
Update demo http://jsfiddle.net/f139nhmr/

**Comment by AMBudnik** [comment]
The issue is no longer replicable in version 0.38.1
