### ISSUE TITLE
Cancel cell edit does not revert htInvalid

### ISSUE THREAD

**Issue by vmlf01** [handsontable/handsontable#3128]
If I type an invalid value into a cell and press ENTER, the cell gets marked with `htInvalid` class. So far so good.

But if I then revert the change by pressing ESC, the value gets reverted but the `htInvalid` class is left in place.

http://jsfiddle.net/xuntad6z/

**Comment by AMBudnik** [comment]
Hi @vmlf01 can you provide step by step scenario hot to check this issue? 
<kbd>esc</kbd> cancels the edit mode.

**Comment by vmlf01** [comment]
Using the jsfiddle link above:
1. select any cell on the table
2. Press letter <kbd>q</kbd> on the keyboard
3. Press <kbd>ENTER</kbd> to confirm input
4. Input is not accepted as expected because it is invalid
5. Press <kbd>ESC</kbd> to cancel input
6. Cell should have a red background, indicating invalid input, which is wrong

**Comment by AMBudnik** [comment]
Thanks for scenario. I got the same incorrect behaviour.

**Comment by AMBudnik** [comment]
Hi @vmlf01 
I checked it with 0.24.1 and it seems it's working fine now.

**Comment by phoenix-down** [comment]
Hi @AMBudnik . I found this thread via Google. I'm having the exact same problem as @vmlf01 . I'm running 0.24.3. Are you sure it's been fixed?

**Comment by AMBudnik** [comment]
Thanks for sharing @phoenix-down I got the same result (invalid cell).
I guess that we're missing one rendering there. When I've added one extra the `thInvalid` c;lass is gone: http://jsfiddle.net/AMBudnik/x4hbczc5/

**Comment by phoenix-down** [comment]
Thanks for the workaround @AMBudnik ! That worked.

**Comment by phoenix-down** [comment]
@AMBudnik , tried to implement your workaround but ran into another issue that's related to this. Perhaps you have some advice. I have two tables, both with "afterDocumentKeyDown" set to call render() when the table object is instantiated. However, doesn't matter what table I'm actually in, the keyboard event is registered by both tables. Is this intentional? For example, both tables are declared like this:

var hot = new Handsontable(container1, {
  // some settings,
  afterDocumentKeyDown: function(event) {
    if (event.code='Escape') {
      hot.render();
      // does some more stuff
    }   
  }
});

var hot2 = new Handsontable(container2, {
  // some settings,
  afterDocumentKeyDown: function(event) {
    if (event.code='Escape') {
      hot2.render();
      // does some more stuff
    }   
  }
});

Essentially, regardless of which table I'm focused on, when I press ESC, it's registered by both tables and triggers the actions defined in both.

**Comment by AMBudnik** [comment]
Hi @phoenix-down 
The key events are tracked by all instances at the same page as it's an external action. 
I'm not sure about the intention  - you would like to rerender both tables after the <kbd>ESC</kbd>key or only one?
Maybe you could provide me a demo - I'd be happy to check what may be wrong.

**Comment by phoenix-down** [comment]
Hi @AMBudnik , I'm trying to apply your workaround for the cell remaining red after pressing ESC (by calling render() manually). I only want to do it for the table that I'm working on. How do I know (programmatically) which table I'm currently on? If I can do that, then I can do something like:

if (ESC pressed) {

  if (in table1) {
    table1.render();
  } else {
    table2.render();
  }

}

**Comment by ankurbajaj9** [comment]
Adding an extra render stops the validation function from being called in my code. Is there any other workaround ?

**Comment by AMBudnik** [comment]
Hi @phoenix-down 
sorry for a late response? Have you already managed to find a solution?

**Comment by phoenix-down** [comment]
Yes and no. My two tables are in two different Bootstrap tabs, so I'm able to tell which table I'm on by knowing which tab I'm on. However, is there a better way? What if both of my tables are on a single table (not in different tabs)? Is there some kind of method to tell if you are currently focused on one table? For example, something like this:

`
if (ESC pressed) {

  if (table1.has_focus() == 1) {
    table1.render();
  } else {
    table2.render();
  }

}
`

**Comment by AMBudnik** [comment]
hm.. maybe it sounds pretty complicated but if you would combine the `outsideClickDeselects: true` (default option) with the `instance.getSelected()` method you'd be able to check if the current instance is being focused. Like in this example: http://jsfiddle.net/oeduxbe3/ but there will be a need to erase the variable after clicking on any other element. 
I'm not sure if I'm still getting the goal here or just going some other direction :)

**Comment by phoenix-down** [comment]
I think your example would work great. Thanks @AMBudnik !

**Comment by GMNGeoffrey** [comment]
It seems like overkill to rerender the entire table every time a key is pressed, no? I ended up solving this issue by writing my own renderer that doesn't include the red highlighting. Is there an easier way to turn off the red, but still use the rest of the features of the built-in renderers?

**Comment by AMBudnik** [comment]
Hi @GMNGeoffrey 

here

>  doesn't include the red highlighting

you mean the incorrect values? 

If so you can just overwrite the CSS settings of `htInvalid` class. The highlighting appears after validation. 
Validation in Handsontable currently cannot be stopped but it can be 'fooled' by passing valid value via `beforeValidate` instead of a current cell value.

**Comment by GMNGeoffrey** [comment]
Ok I change the css instead of changing the renderer. It would be great if this bug were fixed though

**Comment by GMNGeoffrey** [comment]
As a simple fix, couldn't you add another condition in the base cell renderer for adding the invalidCell class?

  if (cellProperties.allowInvalid && cellProperties.valid === false && cellProperties.invalidCellClassName) {
    addClass(TD, cellProperties.invalidCellClassName);
  } else {
    removeClass(TD, cellProperties.invalidCellClassName);
  }

**Comment by GMNGeoffrey** [comment]
For someone who doesn't want to override the css globally, but only do it on a per-cell basis, here's a jsfiddle showing another work around http://jsfiddle.net/tutpyavc/

**Comment by AMBudnik** [comment]
Thanks for fixing @wszymanski I've tested it in 0.31.0 and works as expected.

Can you test it please @vmlf01 we would like to be sure that it's fixed.

**Comment by krzysztofspilka** [comment]
Ok, @AMBudnik, I guess we can close this issue now. Thanks!
