### ISSUE TITLE
The height calculation works bad with HTML elements

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3129]
See this demo:

http://jsfiddle.net/s9wqf94a/

There are custom HTML elements width set fixed height (width='100' in img element). When you scroll once all the way down the table with row headers turned on, you should see how much misaligned they are. If you continue to scroll through the table, the problem vanishes.

Also, I think we should update our docs here:
https://docs.handsontable.com/0.20.3/demo-custom-renderers.html
by adding some details on how to make the row headers work properly with elements with custom height (like loaded via AJAX or simply put as HTML). There are two ways to do that:
1. Set the constant height of the custom elements so the table knows the height before rendering,
2. Re-render table after its initialization.

**Comment by AMBudnik** [comment]
I still got this issue on FF, Chrome seems to work fine.

FF screen

![abc](https://cloud.githubusercontent.com/assets/10757813/22110187/16bce80e-de5b-11e6-9158-7a84ff925727.png)

related or even duplicated: https://github.com/handsontable/handsontable/issues/3981

**Comment by AMBudnik** [comment]
Still replicable in Firefox. The faster we scroll the messier headers we get.
![image](https://user-images.githubusercontent.com/10757813/35220288-0d2da6ec-ff76-11e7-84cc-2780cf3ca204.png)

**Comment by AMBudnik** [comment]
I've tried to replicate the bug using this demo http://jsfiddle.net/s9wqf94a/ but it looks OK now.

![gif22](https://user-images.githubusercontent.com/10757813/38809949-90d8bdc8-4185-11e8-9f4d-1469ac488952.gif)

I'm closing this issue but if you still face any similar issues please leave a comment.
