### ISSUE TITLE
Make a new row with autoincrement value 1.2.3.4.5....and so on as the row header without using the row header

### ISSUE THREAD

**Issue by yash-jain** [handsontable/handsontable#3130]
want to make a new autoincrement row without using row header as row header is coming on top of my sidebar when opened up

**Comment by AMBudnik** [comment]
Hi, maybe this example http://jsfiddle.net/cv5wop1c/ will help.

**Comment by yash-jain** [comment]
thanks a lot :) ..appreciated

**Comment by AMBudnik** [comment]
For this one the best way I suppose is to use custom renderer, please check this example http://jsfiddle.net/5x9mxbbb/
