### ISSUE TITLE
ContextMenu scroll jumping

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3135]
After releasing Handsontable 0.20.3 context menu behaviour was changed.

[This fix](https://github.com/handsontable/handsontable/issues/3070) added undesirable behavior to contextMenu where table’s trying to adjust window scrollbar to correctly position selected cell. There’s a need to add an option to Handsontable to disable this bahavior and apply to menu.

##### Screenshot:
![menu-selection-bug](https://cloud.githubusercontent.com/assets/571316/12390949/91716aea-bde4-11e5-8be3-60a9718583a1.gif)

**Comment by krzysztofspilka** [comment]
Confirmed for 0.21.0, moved to the next release
