### ISSUE TITLE
Sorting not working properly when horizontal scroll available with large number of columns, 

### ISSUE THREAD

**Issue by ravindrakhokharia** [handsontable/handsontable#3137]
I have found one of the issue, for sorting when there is horizontal scrolling, 
Sorting is not working on the columns which are inside horizontal scroll
Here is the js fiddle link for the demo on sorting, 

Please try sorting on the A column first, and then any of the column after Z
http://jsfiddle.net/ubajutqL/

**Comment by AMBudnik** [comment]
Hi @ravindrakhokharia please correct me if I'm wrong - is it the same issue as https://github.com/handsontable/handsontable/issues/3014?

**Comment by krzysztofspilka** [comment]
@ravindrakhokharia it's already fixed in the release 0.21.0

**Comment by ravindrakhokharia** [comment]
@AMBudnik Sorry for late reply, but yes, it looks the same issue as #3014 
While @krzysztofspilka Thanks for informing, will check for the updated version. 

Thanks for your replies
