### ISSUE TITLE
Attempting to check checkboxes using spacebar fails when the number of rows are greater than the height of the table

### ISSUE THREAD

**Issue by Estimable** [handsontable/handsontable#3138]
See fiddle (modified only slightly from the checkbox example):

http://jsfiddle.net/m95brvuz/

Steps to reproduce:

1. Click the first checkbox cell.
2. Scroll to a location near the bottom of the table.
2. Hold down Shift and click a cell.
3. Press the spacebar.
4. An error is shown in the console:

Uncaught TypeError: Cannot read property 'querySelectorAll' of null

**Comment by AMBudnik** [comment]
Confirmed.

This few step should reverse checkboxes' states but it appears that non-visible checkboxes are causing this message.

**Comment by swistach** [comment]
That works properly since 0.27.0
