### ISSUE TITLE
Incorrect contextMenu position while page resizing

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3139]
Reproduced with our [contextMenu demo](https://docs.handsontable.com/0.21.0/demo-context-menu.html)

Steps to reproduce:
1. <kbd>RMB</kbd> on the table's body to open contextMenu
2. Grab a browser's window to resize

![contextmenu](https://cloud.githubusercontent.com/assets/10757813/12460832/09daf4ce-bfb6-11e5-9483-e59f4597b35e.gif)

**Comment by krzysztofspilka** [comment]
@AMBudnik Handsontable is still not a responsive library, it works like this since the very beginning. Admittedly, that is a thing to do.

**Comment by AMBudnik** [comment]
I'm moving all the improvement suggestions to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Please feel free to leave any additional comments and reflections.

Thanks in advance!

**Comment by AMBudnik** [comment]
Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
