### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isOpened' of null

### ISSUE THREAD

**Issue by servocoder** [handsontable/handsontable#3140]
Handsontable 0.21.0

Initially my config of HOT set with `contextMenu = true`
After I execute `hotIstance.getPlugin('contextMenu').disablePlugin();` and move the mouse cursor inside and outside browser window I get the following errors in console (Chrome browser):

```
Uncaught TypeError: Cannot read property 'isOpened' of null handsontable.full.js:14317
Uncaught TypeError: Cannot read property 'isOpened' of null handsontable.full.js:14306
```

**Comment by krzysztofspilka** [comment]
@servocoder thanks for reporting, we're on it.

**Comment by jansiegel** [comment]
Hi, @servocoder 

I'm having trouble reproducing this problem. I made a simple demo on JSFiddle, do you experience this issue here? http://jsfiddle.net/js_ziggle/8rza816w/

If not, can you modify it, so I can see what's going on?

Thanks!

**Comment by servocoder** [comment]
You are right, it happens when `contextMenuCopyPaste` is set, check it here:
http://jsfiddle.net/8rza816w/2/

**Comment by jansiegel** [comment]
True, it throws an error now, thanks for reporting!

**Comment by AMBudnik** [comment]
Hi @servocoder 
It should work as expected in 0.29.0 Can you confirm that it does?

**Comment by servocoder** [comment]
Hi unfortunately I'm not able to test it. Hope it's really fixed. I think this issue may be closed. Thanks.

**Comment by AMBudnik** [comment]
Thanks for your prompt reply @servocoder 
I'm closing this issue.
