### ISSUE TITLE
Specify the column properties options in the documentation

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3143]
I haven't seen anywhere [in the documentation](https://docs.handsontable.com/0.21.0/Options.html#columns) where the properties for each column are explained properly:

Properties like the following:

```javascript
{     
    data:14,
    type: 'text',
    strict: true,
    readOnly: true,
}
```

**Comment by AMBudnik** [comment]
Thank you @alvarotrigo I saved your idea.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
