### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTopLeftCorner' of undefined

### ISSUE THREAD

**Issue by lubianm** [handsontable/handsontable#3144]
When you have a grid with at least one checkbox cell, if you click inside a grid cell and then click on any other DOM element (for example a paragraph) then hit backspace from keyboard, you get the error (you can see it on  browser's console):

**Uncaught TypeError: Cannot read property 'getTopLeftCorner' of undefined**

Here http://jsfiddle.net/m6tv5b07/ the jsfiddle with an example of this issue

**Comment by AMBudnik** [comment]
Confirmed. It does not throw an error where there's no checkbox in the grid. 
Thanks for sharing @lubianm

**Comment by AMBudnik** [comment]
still present in 0.24.1

**Comment by budnix** [comment]
Connected with this branch https://github.com/handsontable/handsontable/tree/feature/checkbox-empty-selection (commit https://github.com/handsontable/handsontable/commit/6d44a9adb7710308fb29194e61217ee36ae70b9a)

**Comment by AMBudnik** [comment]
The issue is not replicable in version 0.35.0
Please leave a comment if there is anything that I am missing or you are still able to replicate the same behavior.
