### ISSUE TITLE
Can't edit column for field named "length"

### ISSUE THREAD

**Issue by arosequist** [handsontable/handsontable#3145]
If you bind a column to a field named `length` and try to edit it, it fails with: **Uncaught TypeError: Cannot assign to read only property 'row' of 9**

Example: http://jsfiddle.net/qaL1yczr/13/

**Comment by AMBudnik** [comment]
Confirmed, this name can't be used.

**Comment by budnix** [comment]
This is a bug. All property names and methods which exist in Array.prototype for now are buggy (eq. `length`, `map`, `filter` etc.). In this case `length` has the most side effects.

**Comment by krzysztofspilka** [comment]
@jansiegel couldn't test. Could you confirm it is now fixed and apply a right label to this issue? Thanks!

**Comment by krzysztofspilka** [comment]
@arosequist finally released!
