### ISSUE TITLE
Cascading configuration for contextMenu

### ISSUE THREAD

**Issue by epernice** [handsontable/handsontable#3148]
Is it possible to configure contextMenus per cell with cascading configurations?  I need each cell to be able to define its own context menu items, but it doesn't seem to be working.  Here's a simple [fiddle](http://jsfiddle.net/cdpnjqyw/).

```javascript
hot = new Handsontable(container, {
	data: getCarData(),
	// contextMenu: true, // THIS WORKS
	cells: function(row, col, prop) {
		return {
			contextMenu: true // DOES NOT WORK
		};
	}
});
```

**Comment by AMBudnik** [comment]
@epernice unfortunately it's not possible.
