### ISSUE TITLE
Double rowHeaders: manualColumnResize conflict with rowHeaders after updateSettings

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3149]
Demo: http://jsfiddle.net/p73o5Lnu/9/

Steps to reproduce:
1. Resize first column to be much wider
2. Click button <kbd>update row headers</kbd>

Before update result
![zrzut ekranu 2016-01-25 o 11 24 58](https://cloud.githubusercontent.com/assets/10757813/12548781/0afbca76-c359-11e5-93da-262ea8e09079.png)

After update result
![zrzut ekranu 2016-01-25 o 11 25 03](https://cloud.githubusercontent.com/assets/10757813/12548785/10685f74-c359-11e5-97b7-972337055808.png)

**Comment by alexpls** [comment]
:+1: this affect me too. Trying to find a workaround but no luck yet.

**Comment by AMBudnik** [comment]
doesn't occur in it's original description.

**Comment by alexpls** [comment]
Hopefully this GIF shows the issue better. I can replicate using the JSFiddle linked above on OS X Safari 9.0.3 and Chrome 48.0.2564.116.
![u499kwn1w4-1](https://cloud.githubusercontent.com/assets/301630/13528905/da4f0de0-e264-11e5-875b-9af9f877eb45.gif)

**Comment by jansiegel** [comment]
Looks like a bug to me.

**Comment by AMBudnik** [comment]
thanks for feedback @alexpls

**Comment by AMBudnik** [comment]
Still replicable.

**Comment by AMBudnik** [comment]
Hi @alexpls 
Can you check it with 0.29.2?
I am using this demo: http://jsfiddle.net/p73o5Lnu/9/
and it looks like the issue is gone. 

![working](https://cloud.githubusercontent.com/assets/10757813/21609152/19267c64-d1c1-11e6-93e0-950547580e7f.gif)

Can you confirm?

**Comment by AMBudnik** [comment]
I am closing this issue but feel free to leave a comment.

**Comment by alexpls** [comment]
Hi @AMBudnik. Great - I can confirm that the issue is fixed now!

**Comment by AMBudnik** [comment]
Great, thanks for confirming @alexpls
