### ISSUE TITLE
Adding a checkbox cell in a column prevents row deletion 

### ISSUE THREAD

**Issue by wbrekel** [handsontable/handsontable#3151]
When a checkbox column is part of a grid, rows cannot be "emptied" using the delete button.
The delete button only leads to the checkbox being set to False, instead of deleting all cell contents in a row. 
I guess this is caused by the resolution of https://github.com/handsontable/handsontable/issues/2106

**Comment by AMBudnik** [comment]
Confirmed. If you select all cells and use <kbd>backspace</kbd> checkboxes get unchecked while other cells stay the same.

Reproducible with [checkbox demo](https://docs.handsontable.com/0.21.0/demo-checkbox.html).

**Comment by AMBudnik** [comment]
Still present in 0.24.1

**Comment by wbrekel** [comment]
Will this be fixed anytime soon? Thanks!

**Comment by AMBudnik** [comment]
Hi @wbrekel 
Unfortunately we do not have this issue on the next milestone.

**Comment by AMBudnik** [comment]
I guess that now we're getting expected result . IMHO `#bad-value#` should apprear as data can be `true` or `false` and when we delete it it's an empty string. Demo: http://jsfiddle.net/handsoncode/fv7dhnpL/

![wn](https://cloud.githubusercontent.com/assets/10757813/22146513/30448e80-df05-11e6-89ae-bad50eb355a3.gif)

What do you think @wbrekel ?

**Comment by wbrekel** [comment]
thanks!
