### ISSUE TITLE
Selecting a full row leads to an error when columns are hidden (PRO Version) 

### ISSUE THREAD

**Issue by wbrekel** [handsontable/handsontable#3152]
I have hidden columns:
hot.getPlugin('hiddenColumns').hideColumns([21])

When I now select a full row (by clicking the row number), an error shows in the console that column 21 is missing.
"Uncaught Error: column 21 does not exist".

**Comment by AMBudnik** [comment]
Hi @wbrekel 

I got the same issue at our Handsontable PRO forum at https://forum.handsontable.com/t/selecting-a-full-row-leads-to-an-error-when-columns-are-hidden-pro-version/112 
we will be continuing this conversation there.

Thanks for feedback.
