### ISSUE TITLE
Misalign editor border in the first row

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3153]
The border around active cell in the first row is misaligned. This bug only occurs when column headers are defined in `columns` setting as `title` key.

Demo: http://jsfiddle.net/gwjv9j7k/

**Comment by budnix** [comment]
Related with https://github.com/handsoncode-apps/InvoiceDemo/issues/36

**Comment by krzysztofspilka** [comment]
@budnix can't mark it as tested because when there's no header at all this issue still occurs: http://docs.handsontable.com/0.21.0/demo-pre-populating.html

**Comment by krzysztofspilka** [comment]
To be continued in #3185
