### ISSUE TITLE
Selecting a full row leads to an error when columns are hidden (PRO Version) 

### ISSUE THREAD

**Issue by wbrekel** [handsontable/handsontable#3154]
I have hidden columns:
hot.getPlugin('hiddenColumns').hideColumns([21])

When I now select a full row (by clicking the row number), an error shows in the console that column 21 is missing, if column 21 is the last column.
"Uncaught Error: column 21 does not exist".

**Comment by anton-107** [comment]
@budnix: there is an issue in `getNextColumn` method, which will return non-existent column index if the last column on the spreadsheet is hidden with the hiddenColumns plugin

**Comment by AMBudnik** [comment]
Hi @wbrekel 

Please track changes to https://forum.handsontable.com/t/selecting-a-full-row-leads-to-an-error-when-columns-are-hidden-pro-version/112 (exact issue at Handsontable PRO forum).

There is a demo request from our programmer.
