### ISSUE TITLE
Modifying hidden cells (data sources)

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3155]
As [the only way to hide columns is by not adding them in the `columns` array](https://github.com/handsontable/handsontable/issues/2981) and therefore treating them as "data sources", it seems the plugin doesn't allow to modify those columns when they are not visible.

The javascript console throws the following exception:

> Uncaught Error: Cannot create new column. When data source in an object, you can only have as much columns as defined in first data row, data schema or in the 'columns' setting.If you want to be able to add new columns, you have to use array datasource.

But of course, I don't want to change my array of objects to an array of arrays... Seems like there's no need for it when the columns are visible and I would expect it to work the same way when they are hidden.

[Reproduction online](http://jsfiddle.net/7u1kxjLe/2/)

```javascript
document.addEventListener("DOMContentLoaded", function() {

    var
    container = document.getElementById('example1'),
    hot;
  
  hot = new Handsontable(container, {
    data: Handsontable.helper.createSpreadsheetData(3, 10),
    colHeaders: true,
    columns: [
      {},{},{},{}
    ],
    
  });
  
    console.log('getData ' + hot.getData());
    console.log('getSourceData ' + hot.getSourceData());
    
    //here's the problem
    hot.setDataAtCell(1, 4, 'demo');
});
```

**Comment by AMBudnik** [comment]
Hi @alvarotrigo 

[Hiding columns](https://docs.handsontable.com/pro/1.0.0/demo-hiding-columns.html) / [rows](https://docs.handsontable.com/pro/1.0.0/demo-hiding-rows.html) is a part of Handsontable PRO which works as expected with `setDataAtCell()`. Please take a look at this example http://jsfiddle.net/fkz9qLo8/1/

**Comment by alvarotrigo** [comment]
Thanks for the answer.
