### ISSUE TITLE
Adding new column dynamically using object data source

### ISSUE THREAD

**Issue by mpusarla** [handsontable/handsontable#3156]
We are trying to add new columns dynamically but the insert column is disabled when the underlying data is in JSON format instead of array.

Here is the jsFiddle:
http://jsfiddle.net/mpusarla/vkj3Len6/

We can't convert the columns data to array and am wondering what options we have.

Thanks,
Madhu.

**Comment by AMBudnik** [comment]
Hi @mpusarla If you're still looking for a solution I'd be happy to help.
Just please provide me more information on how you would like to add new columns (dev/user size)

**Comment by mpusarla** [comment]
Hi, we found a way around this. We are updating the original json columns object with the new condition and are calling update settings with the new columns. It works.

**Comment by mudassir0909** [comment]
@mpusarla I'm having the same issue, would love to know how you guys solved it, when you said 

> We are updating the original json columns object with the new condition and are calling update settings with the new columns

When do you update the original json column object? Did you add a custom context menu action ?
