### ISSUE TITLE
Using Custom Button to add below/delete a selected row

### ISSUE THREAD

**Issue by samsonkhisty** [handsontable/handsontable#3157]
Greetings,
I am looking to create a toolbar outside the table to simplify some actions for users who aren't aware of the context menu. Simple options like "Add below selected" and "Delete selected". 

The custom example doesn't address this need. When I tried implementing the custom button the getSelectedMethod returns null. Looked into the [alter](http://docs.handsontable.com/0.19.0/Core.html#alter) method which will help but how do I get the index of the selected cell. 

Thanks in advance

edit: One option I can think of is to have a hidden text that tracks the selected cell, and use the selectCell method before performing the action.

**Comment by AMBudnik** [comment]
Hi @samsonkhisty I think `outsideClickDeselects` is the one you're missing. In default it's `true` so when someone clicks a button outside Handsontable instance selection is not counted.

Please take a look at this example http://jsfiddle.net/rbvpL9eq/ Works only with single columns / rows but I hope it will help.

**Comment by samsonkhisty** [comment]
Exactly what I was looking for. Cheers.
