### ISSUE TITLE
Column Freeze does not work properly when Column Move is activated

### ISSUE THREAD

**Issue by imed-bh** [handsontable/handsontable#3161]
When activating both column freeze and column move, then trying to freeze any column, the first column is freezed instead of the selected column.
When i disable column move, freezing works properly.
Here is an example which reproduces the problem:
http://jsfiddle.net/imed_bh/3q1a6yy8/4/

**Comment by AMBudnik** [comment]
Hi @imed-bh I think it is the same issue as https://github.com/handsontable/handsontable/issues/2655. If you would have any other tips or observations please write them at https://github.com/handsontable/handsontable/issues/2655.

Thanks in advance!
