### ISSUE TITLE
Missing version number in the JS/CSS credits

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3164]
Since version 0.21.0 the version number is missed in the Javascript and CSS dist files.

```javascript
/*!
 * Handsontable 0.20.0
 * Handsontable is a JavaScript library for editable tables with basic copy-paste compatibility with Excel and Google Docs
 *
...
*/
```
vs

```javsacript
/*!
(The MIT License)

Copyright (c) 2012-2014 Marcin Warpechowski
Copyright (c) 2015 Handsoncode sp. z o.o. <hello@handsoncode.net>
...
*/
```
It would be nice to have it again. It is a very quick way to check the version of those files.

**Comment by AMBudnik** [comment]
It is a pertinent comment. Thanks for feedback @alvarotrigo

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
