### ISSUE TITLE
Retrieve object from `getSourceDataAtRow` instead of an array

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3165]
Is it possible to retrieve an object from `getSourceDataAtRow` instead of an array **when the original data source is an array?**

I've seen objects are returned when using an object as an input source data, but isn't there a way to change from an array to an object provided some column names? 

Also, when having an empty table to be filled by users, this would come in handy.

[The column properties are not very well documented](https://github.com/handsontable/handsontable/issues/3143) but I would expect that using a name for each column would provide a way to get the data as an Object of with those names as properties of it.

For example:
```javascript
//column definition using a name
    columns: [
      {
      	data: 'name'
      },
      {
        data: 'surname'
      },
      {
      	data: 'phone'
      },
      {
      	data: 'address'
      }
    ],
```

Expected result:
```javascript
{
    name: 'Steve',
    surname: 'Jobs',
    phone: '3434343434',
    address: '5th Avenue'
},
{
    name: 'Steve',
    surname: 'Wozniack',
    phone: '111143434',
    address: '6th Avenue'
}
```

Instead of the current array of arrays:
```javascript
[
    ['Steve', 'Jobs', '3434343434', '5th Avenue'],
    ['Steve', 'Wozniack', '111143434', '6th Avenue'],
]
```

**Comment by AMBudnik** [comment]
Hi @alvarotrigo we do not provide a method to achieve your goal but it's not impossible either.

In my head it takes a lot of step but it should work. I would iterate thru every row from `0` to `hot.countCols()` and set the value of each cell like `variable.name = hot.getDataAtCell(row, col)` and then continue with all the rows that are left.

I have to say I'm pretty curious of what you can achieve and how much code it's going to take.

**Comment by alvarotrigo** [comment]
Yep ok, then I guess the easiest way is to convert the array to an object, as I did [in this example](http://jsfiddle.net/7u1kxjLe/8/).

Basically:
```javascript
function rowObject(data){
	var self = this;
    
    self.name = data[0];
    self.surname = data[1];
    self.phone = data[2];
    self.address = data[3];
};

var gridObjects = [];

data.forEach(function(row, rowIndex){
	gridObjects.push(new rowObject(row));
});
```

> Also, when having an empty table to be filled by users, this would come in handy.

What I found quite interesting is that pasting or typing in an empty table will return an object based array. But with some `null` mysterious properties!

```javascript
[null, null, null, null, null, surname: "adfa", phone: "afsad", address: "fasdfa", name: "fasf"]
```

**Comment by AMBudnik** [comment]
Hm... yup like there are few cols more. I thought that `dataSchema` could help but it's not changing anything.
