### ISSUE TITLE
StretchH 'all' with manual column resize issue

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3166]
Column resizing doesn't work precisely when `stretchH: 'all'` is enabled.

---
##### Steps to reproduce:
- Go to http://jsfiddle.net/gps8nsr9/;
- Try to shrink column B;

**Comment by budnix** [comment]
@jansiegel Ready to review :relieved:

**Comment by jansiegel** [comment]
@budnix Looks good to me!
