### ISSUE TITLE
fillHandle: true breaks the cell's meta

### ISSUE THREAD

**Issue by KodjoSuprem** [handsontable/handsontable#3168]
When I use updateSettings() my cell properties are cleared, even those passed at construction time.

They are cleared when calling the function (core.js 1522)

Check this exemple
http://jsfiddle.net/n15nrt0c/9/

Even if they are cleared they should be reconstructed with the cell property (if exist) of settings passed to the constructor

**Comment by AMBudnik** [comment]
Hi @KodjoSuprem please take a look at this example http://jsfiddle.net/n15nrt0c/10/ it uses conditional formatting and it does not get cleared after rendering.

Here's more about conditional formatting: https://docs.handsontable.com/0.21.0/demo-conditional-formatting.html

**Comment by KodjoSuprem** [comment]
i dont want to use the Cells callback wich is called too many time (and for each cell)
I expected the Cell property more performant because I set cells properties only once.

Tell me if i'm wrong.

**Comment by AMBudnik** [comment]
I can see that this line: 
`hot1.updateSettings({fillHandle : true})` 
is causing this odd behaviour. 

Please use one of the following options for [`fillHandle`](https://docs.handsontable.com/0.21.0/Options.html#fillHandle) a `horizontal` or `vertical`

**Comment by AMBudnik** [comment]
I marked it as a bug cause of influences that's causing a `fillHandle: true` value in different types of updates while `true` is an option to pick from listed in the [docs](https://docs.handsontable.com/0.21.0/Options.html#fillHandle)

**Comment by AMBudnik** [comment]
Hi @KodjoSuprem 
I checked it with wth 0.24.1 version and it seem sto work fine. Could you check it please?

**Comment by KodjoSuprem** [comment]
Look like 0.24 fixed this issue.Thank you.

**Comment by AMBudnik** [comment]
great! Thanks for feedback @KodjoSuprem
