### ISSUE TITLE
Documentation: setDataAtCell column parameter

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3169]
In [the documentation](https://docs.handsontable.com/0.21.0/Core.html#setDataAtCell) it sas the `col` parameter can be of type `Number | String`:

> Column index or source string.

But when trying to use it with the name of the column I get the following message:

>Uncaught Error: Method `setDataAtCell` accepts row and column number as its parameters. If you want to use object property name, use method `setDataAtRowProp` 

[Reproduction online](http://jsfiddle.net/7u1kxjLe/11/)

**Comment by krzysztofspilka** [comment]
@alvarotrigo thanks, will be released with the next version!
