### ISSUE TITLE
Documentation: colWidths 

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3170]
[The documentation](https://docs.handsontable.com/0.21.0/Options.html#colWidths) for the option `colWidths` doesn't specify how to use it as a function.

[Looking at the github wiki](https://github.com/handsontable/handsontable/wiki/Options) I found out there's an `index` as a parameter, but otherwise it's not simple to figure out unless you do: `options.colWidths.length`, which is far from ideal.

Also, it would be nice to be able to use there the source column name instead of the column index.

**Comment by AMBudnik** [comment]
An example how to use `colWidths` as a function was already shown at https://github.com/handsontable/handsontable/issues/3171 so I will mark this issue as a proposition for adding more information in docs.

**Comment by krzysztofspilka** [comment]
@budnix can we prepare a simple demo on using the source column name instead of its index?

**Comment by budnix** [comment]
I have prepared demo at http://jsfiddle.net/w8cxqq45/1/ and you can find related documentation at http://docs.handsontable.com/0.21.0/Options.html#colHeaders.

**Comment by AMBudnik** [comment]
Hi @alvarotrigo 
I am happy to ping you up with changes to the docs.
Thank you for sharing
