### ISSUE TITLE
Using `colWidths` for a single column changes the size of others

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3171]
[Reproduction online](http://jsfiddle.net/7u1kxjLe/14/)

See how the column `C` loses its original size and forces the content of those cells to be displayed in multiple lines instead of in a single one [as when not using the option `colWidths` for the last column of the table](http://jsfiddle.net/7u1kxjLe/15/).

**Comment by krzysztofspilka** [comment]
@alvarotrigo, this is actually a lack of a feature. By default Handsontable sets http://docs.handsontable.com/0.21.0/Options.html#autoColumnSize to `true`. If you define a fixed width of a column (one or more), then it's being turned to `false`, therefore you'd need to define the size of all other columns too. It would look like this: http://jsfiddle.net/L9Lftuko/

As a workaround you may use our API to change the size of a particular column: http://jsfiddle.net/7u1kxjLe/16/ - be careful though, there's a chance it slows down the grid.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
