### ISSUE TITLE
Column sorting improvments

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3173]
This changes are addressed to:
 * Server-side sorting. Ability to disable sorting on the frontend.
 * Disappearing column sorting state after calling `updateSettings`.

**Comment by budnix** [comment]
Related with https://github.com/handsoncode-apps/InvoiceDemo/issues/34#issuecomment-173146578

**Comment by krzysztofspilka** [comment]
I can't test it properly. Please do that for me @jansiegel
