### ISSUE TITLE
How to add new columns manually

### ISSUE THREAD

**Issue by Mehtabali** [handsontable/handsontable#3176]
How to Add New columns manually if the columns are customized by code. for example https://docs.handsontable.com/0.21.0/demo-custom-renderers.html has customized columns. I am unable to add column by following this example. I have already tried https://github.com/handsontable/handsontable/issues/599 solution but nothing is working for me. Please help

**Comment by AMBudnik** [comment]
Hi @Mehtabali using [`columns`] according to docs: 
'`sets a fixed number of columns (options startCols, minCols, maxCols will be ignored).`'

using `alter` won't change the behaviour. Although you can use `updateSettings` like so http://jsfiddle.net/obk9rjmr/
