### ISSUE TITLE
best practice: mapping of cell coordinates to application-relevant ids

### ISSUE THREAD

**Issue by markusp72** [handsontable/handsontable#3177]
use case:
A customer wants to edit specific parameters of an application.
For this, a dynamically generated (potentially large) HOT is delivered with all editable parmeters, current settings etc. 
The customer changes data in a cell. An ajax call is triggered on change which results in a corresponding update of the database.

Question: 
Was is the best practice to map / annotate cell coordinates (row + col) of a HOT to meaningful application-related ids?
I would like, e.g., to set custom attributes ("id") for (header-) rows, (header-) columns, and / or specific cells.

What I tried so far:
* setting a custom attribute to a cell (result: attribute gets lost).
* setting the cell value to an object containing an id and the value, with a renderer which splits this information. Problem: On edit, the cell shows the non-rendered "object". Also, on export, the <object> is exported instead of the cell value.
* same: setting the cell renderer to "html" and putting the content <span id="1">MyValue</span>. 
* setting an independent array for the application IDs and mapping them on change does not seem to be a very elegant way.

**Comment by budnix** [comment]
Hi @markusp72, if I clearly understand your needs you want to track changes in specified cells and save it to DB via ajax? If you want to track changes knowing for what record it is changed you can click on [this demo](http://jsfiddle.net/1rj7r4pp/1/) and see how it works.

**Comment by markusp72** [comment]
Hi Krzysztof,
thanks for the helpful demo. 
In my specific case, I would like to determine the id of a modified cell using data stored in the row header and column header cells.
Is it possible to set IDs for (nested) header rows / columns?
i.e., store rowID = 'device_12' in a header row cell, 
and colID='parameter_23' in a column header row, and retrieve these data when a cell content is changed.

My current workaround is putting a <span> element into the Header row cells containing my ids as attributes - not really elegant, and also problematic upon printing / exporting...

Regards,
Markus

**Comment by AMBudnik** [comment]
Hi Markus,
How is your progress?
