### ISSUE TITLE
Problem in using autocomplete  Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by yash-jain** [handsontable/handsontable#3178]
Getting a problem using autocomplete feature from database connectivity.I am using List<String> to retrieve value from SpringMvc controller and Dynamodb (If any other better method is available please mention).Some screenshots of console and my code.Please update soon.
Console 
<img width="936" alt="consle" src="https://cloud.githubusercontent.com/assets/11359447/12746860/dcbcb4d0-c9c6-11e5-9bc5-dde914f45490.PNG">

Controller
<img width="503" alt="control" src="https://cloud.githubusercontent.com/assets/11359447/12746861/dcc2a098-c9c6-11e5-8b0e-afa9fcfd3929.PNG">

Database to arraylist
<img width="527" alt="db" src="https://cloud.githubusercontent.com/assets/11359447/12746862/dcc69ec8-c9c6-11e5-8f87-b830ab4f053e.PNG">

Handsontable column to autocomplete dynamically
<img width="336" alt="ht" src="https://cloud.githubusercontent.com/assets/11359447/12746863/dcec4114-c9c6-11e5-87be-b9ca1c65a576.PNG">

**Comment by krzysztofspilka** [comment]
@yash-jain @AMBudnik We'd need a demo or an access to some test environment on your side, especially due to the fact you have an error 500 displayed in the console.

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo for more than 2 weeks.
