### ISSUE TITLE
how to prevent a particular column to be sorted ?

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#3179]
hello,
i try to search a way to prevent one column to be sorted..
i try this with no success
    beforeColumnSort: function (column, order) {
      if (column==1)
    	return false;
	
    }
any idea would be appreciated
regards
jm

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 currently it's not available but @budnix is working on a server-side sorting and disabling particular columns to be sorted.

Please take a look at https://github.com/handsontable/handsontable/issues/3173

**Comment by jeanmarc78** [comment]
ah ok, thanks alexandra
