### ISSUE TITLE
Validation ignoring beforeChange

### ISSUE THREAD

**Issue by ascendedguard** [handsontable/handsontable#3181]
My goal here is in a percent field, if the user types in a number with a percent sign, remove the percent and divide by 100. Should be simple, and `beforeChange` hook works fine, however the field still turns red as if it's invalid (although the number still formats correctly).

Reproducing Fiddle: http://jsfiddle.net/33pr61hy/

In the final percent column, enter a number like "5%". The `beforeChange` hook changes the value to 0.05, and the number correctly appears as 5.00%. The issue is that it still colors it red and marks it invalid.

From what I can tell, `beforeValidation` and `afterValidation` are both happening before `beforeChange`. Additionally, fixing the format in `beforeValidation` hook has no effect.

**Edit:** The only way I've figured out to workaround the problem is by setting the data to a valid value in the afterValidate method (although you see it flash red temporarily). If you know a better solution, I'd appreciate it.

```javascript
    afterValidate: function(isValid, value, row, prop, source) {
        if (isValid === false && typeof (value) === "string" && value.indexOf('%') > 0) {
            value = parseFloat(value) / 100.0;
            this.setDataAtCell(row, prop, value, 'autofill');
        }
    },
```

**Comment by AMBudnik** [comment]
Hi @ascendedguard 

The basic support - which we deliver on Github - includes help in all the issues connected with Handsontable (like preparing recipes for typical use cases, fixing bugs, etc.), but doesn't cover development on-demand like custom integrations, implementations in specific systems etc. I tried to provide a solid solution, but it would take longer than an hour with testing.

If you would like to use our development on-demand please send your request to hello@handsontable.com

**Comment by ascendedguard** [comment]
I've figured out the issue, it's not obvious from the documentation how to use beforeValidate (since there's no example).

BeforeValidate: http://docs.handsontable.com/0.22.0/Hooks.html#event:beforeValidate

Originally, I was changing the `value` variable, while I needed to `return` the value for the validator (this isn't mentioned in the doc). Here was a beforeValidate example that fixed the above fiddle:

```javascript
beforeValidate: function (value,row,prop,source) {
      if (prop === "onedChng") {
        // Allow percent signs to validate
        if (typeof (value) === "string" && value.indexOf('%') > 0) {
          return parseFloat(value) / 100.0;
        }
      }
    },
```
