### ISSUE TITLE
Best way to get a row or cell by sourcedata

### ISSUE THREAD

**Issue by samsonkhisty** [handsontable/handsontable#3182]
I need to manually select a cell but all I have is property name and the id which is not a visible column. The id is part of the source data. 

Thanks in advance.

**Comment by AMBudnik** [comment]
Hi @samsonkhisty you can use [`getSourceDataAtCell`](https://docs.handsontable.com/0.21.0/Core.html#getSourceDataAtCell) which takes `row` and `col` combined with [`propToCol`](https://docs.handsontable.com/0.21.0/Core.html#propToCol) to get the column by a property.

**Comment by samsonkhisty** [comment]
Let me elaborate, This is part of the collaboration feature (#3183) where I'm tracking the cell of a user that is working on the same table. 

Say 2 users are working on the same table. Now the views may not the same, some rows/cols may be hidden for the user based on permissions. So the value on row,col [3,5] for user1 may not be the same as user2. Simply using the co-ordinates to select a cell will select the wrong cell. 

**My solution**: I then pass the id (uniqueid) or the record and the column name that user1 has clicked on. 
If **I can locate the cell based on the unique id and the column name** in user2's table, then I add customBorder. how do I find the cell based on the unique id which is part of the sourceData and the column. 

The `propToCol` is handy. 

Thanks for looking at all my queries and replying them.
