### ISSUE TITLE
Select Range programmatically removes current selection

### ISSUE THREAD

**Issue by samsonkhisty** [handsontable/handsontable#3183]
JsFiddle: http://jsfiddle.net/fuggfuggfugg/25uzy9ww/12/

I am trying to build a feature where it will track a cell if another user is working on the same table. I am trying to implement it using the customBorder feature. I encounter a couple of issues.

1: In the fiddle above, if I have a cell in selection and click on the button above, it removes my selection, the init() re-renders the whole table. Unfortunately that is the only way I can make it work.
2: Is there any other way to add custom borders (wtBorders) without affecting the table.

**Comment by AMBudnik** [comment]
I saw that you're using `outsideClickDeselects` which keeps the selection after a button click. You are also using `hot.init()` which enables cell to be selected (but without that borders won't work). The only thing that came up to me is to set current selected cell to a variable and use `hot.selectCell(row, col)` after initialization.

I have to say it's really interesting feature that you're working on. I'll be happy to see end results.

**Comment by samsonkhisty** [comment]
Thanks for the reply. 

`hot.init()` is the only way that draws the customBorders. I tried `updateSettings({..},true)` and also the `render()` method but nothing else works. 

Is there any way to add only the customBorders without using `.init()`. The init redraws the whole table on cell selection and it is taxing. I have loads renderers for each cell, my CPU usage is through the roof.

My other option is to add my own custom border logic that tracks the cell co-ordinates and draws cells but then I'd also have to sync the positions on scrolling.

**Comment by AMBudnik** [comment]
Hi @samsonkhisty how is your progress in the matter?

**Comment by samsonkhisty** [comment]
Hi Alexandra, thanks for asking. I actually made it work but moving away from customborders are use CSS instead. I use outline and outline-offset and it looks just as dandy. That way I don't have to worry about adding my customborder and tracking the scrolling and all that. 

<img width="292" alt="screen shot 2016-02-26 at 3 05 11 pm" src="https://cloud.githubusercontent.com/assets/3254606/13363979/607a98b0-dc9a-11e5-9b0b-c87b6b3827a0.png">

**Comment by AMBudnik** [comment]
Hi @samsonkhisty clever solution and your grid looks great!
