### ISSUE TITLE
Json data now showing in the cells

### ISSUE THREAD

**Issue by RaviMudalige** [handsontable/handsontable#3184]
In my Handsontable, I have dynamically generated columns (around 100) and only in the first two columns it is showing Json data. But when I  "console.log(data)" it has data for other columns.

Here is my Stored Proc in SQL Server,

`BEGIN
	DECLARE @cols AS NVARCHAR(MAX),
    @query  AS NVARCHAR(MAX)

	select @cols = STUFF((SELECT distinct ',' + QUOTENAME(UserName) 
						from AspNetUsers
						where EmploymentStatusId = 1
				FOR XML PATH(''), TYPE
				).value('.', 'NVARCHAR(MAX)') 
			,1,1,'')

	set @query = 'SELECT distinct CONVERT(VARCHAR(10), DateWorked, 103) as Date, LEFT(DATENAME(weekday,DateWorked),3) as Day, ' + @cols + ' from 
				 (SELECT distinct a.UserName, r.DateWorked, r.EmployeeTask
					FROM Rosters r left join AspNetUsers a on a.Id = r.EmployeeId
					) x
				pivot 
				(
					min(EmployeeTask)
					for UserName in (' + @cols + ')
				) p '

	execute(@query)
END`

Above Stored Proc generate fixed columns "Date" and "Day". All other columns are dynamic starting from "Username1", Username2", "Username3", "Username4" etc ...  

When I console log "data" it shows like this,

`[Object { Date="15/01/2016",  Day="Fri",  Username1="MMM",  Username2="DDD", Username3="VVV"}]`

My issue is it shows only the Date and Day. It's not showing the data for Usernames which are dynamic generating from the Stored Proc.

Here is how I render Handsontable,

`$.ajax({
                async: false,   
                type: "GET",
                url: '@Url.Action("LoadData")',  
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                success: function (data) {                   
                    
                    var columnsList = new Array();
                    for( var column in data )
                    {
                        jQuery.each(data[column], function(i, row) {
                            columnsList.push(i);
                        });
                    }
                    
                    $("#dvhandson").handsontable({
                        data: data,                                         
                        renderAllRows: true,
                        autoWrapRow: true,                       
                        rowHeaders: true,
                        colHeaders: true,                       
                        className: "htCenter",                        
                        colHeaders: columnsList    
                    });
                }
            });`

Where did I go wrong? Could someone please help out? 
Cheers!

**Comment by budnix** [comment]
Can you prepare a demo on JSFiddle? It will be very helpful for investigating your issue.

**Comment by RaviMudalige** [comment]
I can generate Handsontable with data if I replace the above stored procedure with a basic "select * from employee" statement. The problem is it's a PIVOT SQL Query and only the first two columns ("Date", "Day") are actual columns and the rest of the columns created dynamically like ("Username1", "Username2", "Username3" etc.) These Usernames are stored in "Users" table. 

Is there any sample a Handsontable generated with a PIVOT query? It will be a great help.

**Comment by RaviMudalige** [comment]
I fixed this problem by myself. The problem was in my PIVOT SQL Server Query I get "Names" like "Thomas.Cook", "John.Carter" as columns. For some reason the dot between the First Name and the Last Name cause the problem when it render into Handsontable even though it output correct results in my stored procedure. So I fixed it by replacing the dot with a space in my Stored Procedure query. Now Handsontable render it properly. 

Hope this might help someone ...
Thanks guyz.

**Comment by RaviMudalige** [comment]
Hi,

I have fixed this issue by myself and updated the ticket in GitHub. Thanks
mate.

I do have another issue. I have dropdown cells and I want to color each
cell background by it's selected text. Let's say we have a dropdown cell
with 4 different options. Blue, Green, Red and Yellow. If I select blue
from the dropdown cell it has to color blue, likewise. Could you please
send me a sample to do this.

Cheers!
Ravi

**Comment by RaviMudalige** [comment]
G'day mate,

Is there any update on this mate?

Cheers!
Ravi

**Comment by RaviMudalige** [comment]
I fix this issue after went through this document,
https://docs.handsontable.com/0.22.0/demo-conditional-formatting.html

Thanks.
