### ISSUE TITLE
Column header height doesn't work with update settings

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3186]
Connected with #2868

`columnHeaderHeight` doesn't work properly with `update.settings`.

**Comment by AMBudnik** [comment]
demo: http://jsfiddle.net/handsoncode/b4bcqjnk/
Still not working in 0.30.1

**Comment by AMBudnik** [comment]
The issue is no longer replicable in version 0.35.0
Updated example http://jsfiddle.net/rrjxa7fb/

![zrzut ekranu 2018-01-19 o 12 03 48](https://user-images.githubusercontent.com/10757813/35147979-d742c498-fd10-11e7-9753-ef78619c4bd6.png)
