### ISSUE TITLE
Adding multiple classes per cell

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3187]
As suggested [in this post](https://github.com/handsontable/handsontable/issues/3180) using the function `setCellMeta` we can add a class to a cell. 

But... how can we add multiple classes at different times to the same cell? 
Using `hot1.setCellMeta(0, i, 'className', 'jobs-style');`  will force the removal of any previous one.

**Comment by AMBudnik** [comment]
Hi @alvarotrigo simply add two classes separated by a space, example: http://jsfiddle.net/7u1kxjLe/22/

**Comment by alvarotrigo** [comment]
Yep, that's what I ended up doing, but it just gets a bit more complicated when trying to add new classes to an existent one or removing specific classes and so on. 

Adding to an existent one:
```javascript
//we need to retrieve the cell meta first in order to get the current class
var cellMeta = myHandsontable.getCellMeta(rowIndex, columnIndex);

//now we have to apply the new one by adding it to the existent one
hot1.setCellMeta(rowIndex, columnIndex, 'className', cellMeta.className + ' demo');
```

Removing specific class:
```javascript
//we need to retrieve the cell meta first in order to get the current class
var cellMeta = myHandsontable.getCellMeta(rowIndex, columnIndex);

var newClass = removeClass(cellMeta.className, 'demo');

//now we have to apply the new one by adding it to the existent one
hot1.setCellMeta(rowIndex, columnIndex, 'className', newClass);

function removeClass(currentClasses, toRemove) {
        if (currentClasses) {
            var reg = new RegExp('(\\s|^)'+toRemove+'(\\s|$)');
            currentClasses=currentClasses.replace(reg,'');
        }
        return currentClasses;
}
```

**Comment by AMBudnik** [comment]
If you have an idea how to achieve it faster/better/easier - here's the best place to report it. We're always open for new ideas - sometimes it just has to take some time to be implemented.

**Comment by alvarotrigo** [comment]
I don't really understand how handsontable works internally. That's why I got surprised to find out that applied CSS classes got removed when changing a cell value.
Therefore I might not be in a position of suggesting how to implement some features. 

On the other hand, I can show the struggles I'm finding on the way of using the library in case they can be solved in a more easy way in an attempt to improve the library and the developers experience with it. 

I could only suggest something like this:

``javascript
//adding a class
hot1.addCellClass(rowIndex, columnIndex,newClass);

//removing a class
hot1.removeCellClass(rowIndex, columnIndex,newClass);
```

Maybe having the following under the hood:
```javascript

function addCellClass(row, column, newClass){
    var cellMeta = myHandsontable.getCellMeta(rowIndex, columnIndex);
    hot1.setCellMeta(row, column, 'className', cellMeta.className + ' ' +  newClass);
}


function removeCellClass(row, column, classToRemove){
    var cellMeta = myHandsontable.getCellMeta(row, column);
    var newClass = removeClass(cellMeta.className, classToRemove);

    hot1.setCellMeta(row, column, 'className', newClass);
}

function removeClass(currentClasses, toRemove) {
    if (currentClasses) {
        var reg = new RegExp('(\\s|^)'+toRemove+'(\\s|$)');
        currentClasses=currentClasses.replace(reg,'');
    }
    return currentClasses;
}
```

This way at least developers won't have to deal with the `removeClass` function and they provide a shortcut for those actions.

**Comment by alvarotrigo** [comment]
Although I understand this happens as well with any other `meta` property the cells might have (which I didn't find in the docs). 
So maybe something more generic could be done:

```javascript
//adding a class
hot1.addCellMeta(rowIndex, columnIndex, 'className', newClass);

//removing a class
hot1.removeCellMeta(rowIndex, columnIndex, 'className', classToRemove);
```

**Comment by AMBudnik** [comment]
It's actually a good idea and one thing I can ensure you in is that we're open for any ideas cause developers are the one who will use Handsontable. 

I'll mark this issue as a feature request,

**Comment by alvarotrigo** [comment]
This is what I ended up using in my project, which is basically the javascript implementation of `addClass`, `removeClass` and `hasClass` of jQuery, but in this time, regarding a property of the cell:

```javascript
//http://jaketrent.com/post/addremove-classes-raw-javascript/
self.hasProp = function(cellMeta, prop, value) {
    return !!cellMeta[prop].match(new RegExp('(\\s|^)' + value + '(\\s|$)'));
}

self.addCellMeta = function(row, column, property, newProperty) {
    var cellMeta = myHandsontable.getCellMeta(row, column);

    if (!self.hasProp(cellMeta, property, newProperty)) {
        myHandsontable.setCellMeta(row, column, property, cellMeta[property] + ' ' + newProperty);
    }
};

self.removeCellMeta = function(row, column, property, propertyToRemove) {
    var cellMeta = myHandsontable.getCellMeta(row, column);
    var newClass = self.removeFromString(cellMeta[property], propertyToRemove);

    myHandsontable.setCellMeta(row, column, 'className', newClass);
};

self.removeFromString = function(currentString, toRemove) {
    if (currentString) {
        var reg = new RegExp('(\\s|^)' + toRemove + '(\\s|$)');
        currentString = currentString.replace(reg, '');
    }
    return currentString;
};
```

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.
