### ISSUE TITLE
Sort, remove a row and undo turns out an unexpected result

### ISSUE THREAD

**Issue by dayer3** [handsontable/handsontable#3188]
I haven't found this behaviour in these issues.

The actions are: refresh, sort by _code_, select EUR from _country_, _remove row_ and _undo_.
I've done the test in the [examples section](https://handsontable.com/examples.html?headers&context-menu&sorting):

![load-sort-remove-undo](https://cloud.githubusercontent.com/assets/243047/12786810/f0449a46-ca92-11e5-9fc1-fe3e42bacb71.gif)

And after undo the order disappears and I can't find the row for the Euro.

Browser: Google Chrome 48.0.2564.82 (64-bit) over Linux.

**Comment by AMBudnik** [comment]
Confirmed. Sorting is erased and there's no 'EUR' row.
Thanks fir sharing!

**Comment by AMBudnik** [comment]
Confirmed with 0.24.0

**Comment by AMBudnik** [comment]
Confirmed in 0.26.0

**Comment by AMBudnik** [comment]
Issue still replicable in v0.30.1 we have 2 x Swedish krona when we sort `Code` once and delete Euro.

**Comment by AMBudnik** [comment]
I still get `SEK` instead of `EUR` when I undo.

I've just tested it here https://jsfiddle.net/ym0nprvL/ v `2.0.0.`

**Comment by AMBudnik** [comment]
Hi @dayer3 

thank you for sharing. The issue got solved in version 6.1.0
