### ISSUE TITLE
Is it possible to allow 15 digit after decimal in Handson Table ?

### ISSUE THREAD

**Issue by ranjan653** [handsontable/handsontable#3189]
Is it possible to allow 15 digit after decimal in Handsone Table ?

Like:- 5.123456789012345  (will allow)
but when 0.5 it will simply show 0.5 not 0.500000000000000

Thanks
Ranjan

**Comment by AMBudnik** [comment]
Hi @ranjan653 
You would need to use `format`. 
Take a minute to look at this example: http://jsfiddle.net/kw4x9ta1/

**Comment by ranjan653** [comment]
Hi @AMBudnik , Thanks for your quick response. But if the value is 0.5
then its coming as 0.500000000000000 (how to do 0.5 )

**Comment by AMBudnik** [comment]
We are using [numericjs](http://numericjs.com/documentation.html) to coupe with numbers so I guess you should look for an answer there.

What I can recommend is to use a function like [that](http://jsfiddle.net/kw4x9ta1/) and add `case` with desired scenarios.
