### ISSUE TITLE
Returning incorrect array when introducing info into a an object formatted grid

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3190]
I treated this same issue on an answer [in this topic](https://github.com/handsontable/handsontable/issues/3165).

This happens when having a table with an object source like the following:

``` javascript
var globalColumns = [
    { 
        data: 'name',
    },
    {
        data: 'surname',
    }, 
    {
        data: 'phone',
    },
    {
        data: 'address',
    }
];

var container = document.getElementById("example1");
var hot1 = new Handsontable(container, {
    startRows: 5,
    minSpareRows: 1,
    colHeaders: true,
    columns: globalColumns

});
```

When  pasting or typing in an empty table, an object based array will be returned, **but with some `null` mysterious properties!**

``` javascript
[null, null, null, null, null, surname: "adfa", phone: "afsad", address: "fasdfa", name: "fasf"]
```

[Example online](http://jsfiddle.net/7u1kxjLe/21/)

I would expect `console.log(dataSource.length);` to return 9, but it only counts 4. 

I don't know which kind of structure is that. Is that an array? Is that an object? Why it only counts 4 instead of 9?

This is preventing me to iterate through the object.

**Comment by AMBudnik** [comment]
Confirmed. Thanks for a full scope of information. I will close https://github.com/handsontable/handsontable/issues/3165 cause any result here would trigger your project in https://github.com/handsontable/handsontable/issues/3165 case.

**Comment by mburbea** [comment]
It appears that if you initialize the data attribute in this case with an empty array you do not get this strange result.

**Comment by AMBudnik** [comment]
Hi @alvarotrigo 
I wanted to investigate this case but I see that in 0.27.0 it works better.
Can you check it please?

**Comment by AMBudnik** [comment]
I think that we can close this issue as there are no additional complaints and the example works fine.
