### ISSUE TITLE
Comments editor position wrong when comments on cell in first row

### ISSUE THREAD

**Issue by scandox** [handsontable/handsontable#3194]
You can see an example of this here: http://jsfiddle.net/e1dfzcr3/

Basically if the comment is on a cell in the first row then the editor displays in its last known position. This will be at the bottom of the document initially and afterwards at the last displayed location of any other comment. As far as I can see the problem exists in `refreshEditorPosition`.

**Comment by AMBudnik** [comment]
Confirmed.
I thought that maybe it's a correlation between `comments` and `mergeCells` but it's not.
I left only:

`colHeaders: false,`
`comments: true`

and `comments` section and got the same results.

**Comment by AMBudnik** [comment]
It seams to work fine in 0.24.1
Could you check it @scandox ?

Thanks in advance!

**Comment by scandox** [comment]
Yep: http://jsfiddle.net/Lf9zrbqo/2/

Thanks
