### ISSUE TITLE
After sorting when we go to add row, it adding two rows in Handson Table?

### ISSUE THREAD

**Issue by ranjan653** [handsontable/handsontable#3196]
After sorting when we go to add row, it adding two rows in Handson Table?

**Comment by AMBudnik** [comment]
Hi @ranjan653 

Can you guide me how to reproduce the issue?

I created a simple demo: http://jsfiddle.net/n4zLg9q2/ and sorted by `B` column, then clicked a <kbd>RMB</kbd> to `insert row above` by a context menu the James' Monroe cell and got only one empty row.

**Comment by ranjan653** [comment]
Actually I have customize your library. May be for that the issue is coming.So I am doing R&D on that how to remove.I thought there is some library issue, so I have raised the issue.If I am not able to solve , will contact you.Thanks a lot for your valuable response.

**Comment by AMBudnik** [comment]
If you would need a development on-demand please write us back at: hello@handsontable.com

**Comment by ranjan653** [comment]
Hi, I am using Handson Table Pro version. I found numeric sorting is
working like string. How to avoid it. How to make my own format.

Suppose my format is like format:'00.0000000000'
if my data is like 5.8 then its coming as 5.8000000000 (I need 5.8)
How to do it.

**Comment by AMBudnik** [comment]
@ranjan653 so you would like to change the format for different values?

**Comment by ranjan653** [comment]
yes

**Comment by ranjan653** [comment]
Hi Also numeric sort not working

**Comment by AMBudnik** [comment]
Hi @ranjan653 I guess you would need an `if` clause or change this numbers to strings to let them display in your conditions.

**Comment by ranjan653** [comment]
k lets see

**Comment by ranjan653** [comment]
Hi @AMBudnik could you please provide your contact no so that i can contact you.
I can fetch data from DB and able to show, but when click on cell to edit and save not working for first time, second time click on save working. Suggest please

**Comment by AMBudnik** [comment]
Hi @ranjan653 we only provide basic support by a Github board or with a support email.

This feature you're wanting to create could take some time. If you would like us to help you in the development process you can choose to use our development on-demand. If so please write to us at hello@handsontable.com
