### ISSUE TITLE
Add properties on cell

### ISSUE THREAD

**Issue by LoveOfLava** [handsontable/handsontable#3197]
Hi,

I would like to add properties on cell and keep them in order then I call the function getSourceData I retrieve them.

Example : 

            hot.updateSettings({
                cells: function (row, col, prop) {
                    var cellProperties = {};
                    if (row == 1&& col == 2) {
                         cellProperties.myattribute = 'myattributes';
                    }
                    //
                    return cellProperties;
                }
            });

hot.getSourceData(); //it will retrieve the myattribute properties

Thanks
Regards

**Comment by LoveOfLava** [comment]
https://bitnami.com/stack/redmine
![image](https://cloud.githubusercontent.com/assets/15012754/12844368/297f39d4-cbff-11e5-8df3-216f39a4010f.png)

**Comment by AMBudnik** [comment]
Hi @LoveOfLava what exactly you would like to get?

**Comment by LoveOfLava** [comment]
Hi,

I would only get simple properties like 'row','col' or 'typeCellule'

**Comment by AMBudnik** [comment]
Please take a minute to check this example http://jsfiddle.net/kw0L4bcL/. It there anything else you would like to get?

**Comment by LoveOfLava** [comment]
It's okay 

Thanks
