### ISSUE TITLE
(How) can the validation result be accessed in BeforeChange?

### ISSUE THREAD

**Issue by markusp72** [handsontable/handsontable#3198]
Probably a noob question:

After a **validated** change of a cell value, the change should be persisted in the backend using an ajax call located in *BeforeChange* Event Handler. 
Is there a way to obtain the result of the Validator - call from within the *BeforeChange* Function, or a possibility to block the *BeforeChange* Event if a value was invalidated?

Thanks in advance!
Markus

**Comment by AMBudnik** [comment]
Hi @markusp72 maybe this demo will help : http://jsfiddle.net/k271wLue/

**Comment by markusp72** [comment]
Hey AMBudnik,
Thanks for the quick response.
Adding another hook to the *BeforeChange* Event unfortunately does not solve my problem (check the console output):

http://jsfiddle.net/vfLLmkak/1/

**Comment by AMBudnik** [comment]
Hi @markusp72 I'm not sure what you would like to achieve here but it looks like you would have to create your own editor. Please take a look at this tutorial https://docs.handsontable.com/0.22.0/tutorial-cell-editor.html you can set your own behaviour for `validationResult` and then choose to `revertToOriginal` or save the values. If that's not it - please share with me more details.
