### ISSUE TITLE
setCellMeta with custom properties

### ISSUE THREAD

**Issue by LoveOfLava** [handsontable/handsontable#3200]
Hi,

It seems setCellMeta didn't work with custom properties

Example : 

hot.setCellMeta(1,1,'mycustomproperty','myvalue')

Thnaks

**Comment by AMBudnik** [comment]
Confirmed.
Demo to test: http://jsfiddle.net/kw0L4bcL/3/
It changes a custom property named `myattribute` and `readOnly` to have a comparison.

**Comment by LoveOfLava** [comment]
Hi,

So how can I changed an custom properties ?

Thanks

**Comment by AMBudnik** [comment]
There's no workaround currently. I'll mark this issue as a bug to be reviewed.

**Comment by markusp72** [comment]
Hi, if I may add my 2 cents...
There seems to be something quite wrong with setting/getting cell properties. Have a look here:

http://jsfiddle.net/ocj97fjh/1/

**Comment by AMBudnik** [comment]
so the `(1, 1)` cell takes the property dedicated to `(0, 0)` cell - thanks for sharing @markusp72

**Comment by AMBudnik** [comment]
same for 0.24.1, update demo: http://jsfiddle.net/kw0L4bcL/5/

**Comment by AMBudnik** [comment]
Still undone, demo http://jsfiddle.net/handsoncode/fmrcs3fm/ (0.30.1)

**Comment by AMBudnik** [comment]
I just got additional details from Piotr that this actually is not a bug as cells are always rewritten in another cycle. I am closing this issue.
