### ISSUE TITLE
Documentation for render()

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3201]
I'm finding some performance problems when working with the library and it seems to be due to the use of `render()` when probably it is not necessary. 

[I didn't find a very elaborated explanation](https://docs.handsontable.com/0.22.0/Core.html#render) of why this function is here and in which cases we should make use of it. 

A better documentation would make things easier: 

> render()
> Rerender the table.

**Comment by alvarotrigo** [comment]
I opened a topic [like a year ago](https://github.com/handsontable/handsontable/issues/2382) about a very similar request.

**Comment by AMBudnik** [comment]
Hi @alvarotrigo 

Can you share what performance problems you experienced with the `render()`? Also I would really appreciate for any questions that came up to you while writting this issue (what information can come handy when it comes to `render()`).

**Comment by alvarotrigo** [comment]
> Can you share what performance problems you experienced with the render()?

When pasting hundreds of cells or validating them I perform cell modifications (meta info, classes added for each cell, change of cell content...) if every time I perform one  of those actions I call the `render` method, the process becomes very slow delaying for seconds.

I managed to get rid of that delay by just adding a `setTimeout` like so:
```javascript
var renderTableDelayedId;

function delayedRender(){
    clearTimeout(renderTableDelayedId);
    renderTableDelayedId = setTimeout(renderTable, 250);
}

function renderTable(){
     hot1.render()
}

//call to render 
delayedRender();
```

But that can carry other side effects when dealing with some callback such as `afterChange` and so on. And I would have to carry the delay all along my functions. 

Also, i wonder what's a good value for that delay. Maybe 250 milliseconds is a lot. Maybe it would be enough with 50? 

> what information can come handy when it comes to render()

Mainly. When should we make use of it. Every time we change a cell property? 
Also, what does it exactly do? Will it render the whole table? Is it a performance expensive method? Those are good things to know. 
Ideally we would have a render per cell or even per row, the topic was treated [in the past](https://github.com/handsontable/handsontable/issues/478) like more than a year ago, but it was closed, marked as "Approved" in the [Feature Requets](https://github.com/handsontable/handsontable/wiki/Feature-requests) list with number 11, and never merged?

**Comment by AMBudnik** [comment]
It that case 'Approved' is used to check it the feature isn't duplicated or added. https://github.com/handsontable/handsontable/issues/478 is going to be reopened as soon as it's feature is ready to develop.

Thank you for a solid piece of information. It'll be easier to fill `render()` docs now when we're more aware of what questions it might create while developing.

**Comment by wojciechczerniak** [comment]
Moved to https://github.com/handsontable/docs/issues/5
