### ISSUE TITLE
Columns as rows

### ISSUE THREAD

**Issue by vlados** [handsontable/handsontable#3203]
How I can change the columns to be different rows?

**Comment by AMBudnik** [comment]
Hi @vlados if you're thinking of pivot table, currently we do not provide this feature but you can try to rewrite your table data to another array.

**Comment by vlados** [comment]
I can return the data to be in rows and to have cols [name,value] but then the problem is that I cannot set different editors for the different rows

**Comment by AMBudnik** [comment]
Hi, take a minute to check this demo: http://jsfiddle.net/moLLzu2m/ it sets `numeric` type of cell to all the cells in 3rd row. Is this was what you wanted to achieve?

**Comment by vlados** [comment]
Yes, perfect :))))
