### ISSUE TITLE
Table "flickering" when scrolling (mostly seen on Safari)

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3204]
Sometimes, when scrolling Handsontable, the table "flickers" (the scrollbar goes back a few pixels and immediately scrolls back to it's right position).

-----------
#### Steps to reproduce:
* Go to http://codepen.io/js-ziggle/pen/xZQGZd (preferably on Safari)
* Scroll to the far right
* Scroll left and right for a while

**Result:** The "flickering" effect should be clearly visible.

**Comment by jansiegel** [comment]
Developed on branch: [feature/scrollCallbacks](https://github.com/handsontable/handsontable/tree/feature/scrollCallbacks).

This modifies the scroll propagation mechanism, so thorough testing is advised.

**Comment by krzysztofspilka** [comment]
Tested on @budnix machine
