### ISSUE TITLE
outsideClickDeselects : false disables all focus in other inputs outside the table

### ISSUE THREAD

**Issue by samsonkhisty** [handsontable/handsontable#3205]
Also referencing #408  & #401 

There is an example provided (outsideClickDeselects:false)
https://github.com/handsontable/handsontable/issues/401#issuecomment-162988326

gif included; 
![bug](https://cloud.githubusercontent.com/assets/3254606/12900703/b44ef044-ce85-11e5-9d92-9530315186e1.gif)

**Comment by AMBudnik** [comment]
Hi @samsonkhisty please add any additional suggestions/comments to #401 as it is marked as a bug already.
We're trying to not duplicate issues.
