### ISSUE TITLE
ContextMenu height calculation incorrect for separators for div.wtHider

### ISSUE THREAD

**Issue by samsonkhisty** [handsontable/handsontable#3207]
If I open context menu for rows that are at the bottom of my viewport, the height calculation of the wtHider is way more than the height of the context menu, this adds a scrollbar to my window and causes pixel shifts and weird behaviour. 

gif of the issue: 
![bug](https://cloud.githubusercontent.com/assets/3254606/12924351/91db78c8-cf27-11e5-9218-e38e8576747a.gif)

screenshot: 
![screen shot 2016-02-09 at 12 17 45 pm](https://cloud.githubusercontent.com/assets/3254606/12924415/e17c5ff0-cf27-11e5-90ef-aa5f6892bee7.png)

On further debugging, I noticed that the [markOversizedRows](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js#L3523) method will not insert an entry for the context menu row for `htSeparator` class since the height is 2px.

Thus while calculating the height in [adjustElementsSize](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js#L2493) it returns a default height instead. 

Hope this helps

**Comment by AMBudnik** [comment]
Thanks for sharing a full introduction of this issue.

**Comment by AMBudnik** [comment]
Still occurs if menu has a submenu.

**Comment by budnix** [comment]
This issue was fixed in the newest version. Can you confirm @samsonkhisty if this works for you?

**Comment by AMBudnik** [comment]
I will leave the issue closed as the issue does not occur anymore but if you're still facing any similar difficulties please leave a comment @samsonkhisty
