### ISSUE TITLE
Autosize comment box to fit content

### ISSUE THREAD

**Issue by tnrich** [handsontable/handsontable#3208]
Hey there,

Thanks for the great tool. I was wondering if someone knew of a way to get the comment boxes to scale to fit their content.

Is there some sort of hook/event I could use to respond to comments being rendered?

Any help would be appreciated. Thanks!

**Comment by AMBudnik** [comment]
Hi @tnrich 
it depends on [`CommentEditor`](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js#L12261) but we do not provide customization of comment box. You can of course try to use CSS like: http://jsfiddle.net/1yb3rg72/1/ Unfortunately there have to be a fixed height (% aren't accepted).
