### ISSUE TITLE
Handsontable - Formula field retrieval issue

### ISSUE THREAD

**Issue by karthikcsridhar** [handsontable/handsontable#3209]
I have formula fields that reference other formula fields in my handsontable. While retrieving some of the formula fields I have issues, where I am getting the formula instead of the calculated value.

I have tried 2 ways of retrieving the formula fields as below,

Method One:

```
var cellId2 = myht.plugin.utils.translateCellCoords({row: rowNum,col: colNum});
var res1 = myht.plugin.helper.cellValue(cellId2);
```

When above fails, it returns the formula itself instead of the value.

Method Two:

```
var formula = myht.getDataAtCell(rowNum, colNum);
formula = formula.substr(1).toUpperCase();
var newValue = myht.plugin.parse(formula, {row: rowNum, col: colNum, id: cellId2 });
```

When above fails, newValue object has errors as shown below,
`
{error: "#VALUE!", result: null}`

Following is a jsfiddle that shows the problem. https://jsfiddle.net/76z48m98/3/

View the problematic retrievals in the console after clicking the button in the fiddle. If it works fine without issues, probably try 2-4 times clicking button or refresh jsfiddle & try, you can see the issue happen, as sometimes(rarely) everything works fine.

As I understand it, when the libraries calculate the formula, sometimes if the referenced cells are formula cells again, it sometimes retrieves the formula itself of the referenced cells instead of the actual value, leading to isNaN and it fails.

I could see that the function mathMatch: function (type, number1, number2) in ruleJS.js, either one of the number arguments is a formula instead of a number and hence it throws an 'VALUE' error for isNaN.

**Comment by AMBudnik** [comment]
Hi @karthikcsridhar I'm marking this issue as a formula bug, but I have to say that formula support is currently an experimental feature and it will be probably be refactored.

**Comment by karthikcsridhar** [comment]
Thanks, I wish this is resolved soon as calculating formulas manually with onChange event and using eval() is causing serious performance issues. I am forced to do everything manually now without using the plugin. I really hope this is fixed soon so that I can make use of this great plugin.

**Comment by AMBudnik** [comment]
Hi @karthikcsridhar 
some time ago we have added a PRO Formula plugin. Can you check if the issue is gone? I have tried to replicate it here https://jsfiddle.net/handsoncode/xtshcL6v/ but it's missing something in your code. Between the version in this topic and 1.10.2 there are some breaking changes so larger demos can experience some issues.
