### ISSUE TITLE
Too much listeners for checkbox renderer

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3211]
Currently checkbox renderer adds listener to input element for every cell. Additionally every new listener is added with every table render which drastically increase number of listeners. This behavior unnecessary increase memory usage and extends Handsontable destructing.

Needs to implement event delegation.

**Comment by krzysztofspilka** [comment]
@budnix couldn't test it, can you confirm the 'tested' status?

**Comment by budnix** [comment]
Yes, I confirm it. Works as expected.
