### ISSUE TITLE
Setting cell to invalid value - documentation

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3214]
As seen in [this answer](http://stackoverflow.com/questions/24595389/handsontable-how-to-set-cell-to-invalid-manually) one can set the state of a cell to `invalid` by just changing the meta data property `valid`.

It is interesting to see how the invalid class `htInvalid` is also added to the cell. But there's nowhere in the documentation when this behavior is detailed. The association between the meta data `valid` and the class added to the cell. 

Also, this class (`htInvalid`) won't get added in the `className` meta data.

**Comment by budnix** [comment]
Hi @alvarotrigo, class `htInvalid` is grabbed from [`invalidCellClassName`](http://docs.handsontable.com/0.24.1/Options.html#invalidCellClassName) settings (default value is `htInvalid`). 

Yes, you are right. This class (`htInvalid`) is not added to the `className` property of cell meta object it is grabbed directly from the `invalidCellClassName` meta data. Here you can see proper condition https://github.com/handsontable/handsontable/blob/master/src/renderers/_cellDecorator.js#L28.

**Comment by budnix** [comment]
I've updated docs at http://docs.handsontable.com/demo-data-validation.html (https://github.com/handsontable/docs/commit/7bb0bb9246df694f4d0a4d38dae55a0510212d69).

**Comment by alvarotrigo** [comment]
Thanks!

**Comment by vaidyasaurabh08** [comment]
So, how do we add custom css class. I tried adding invalidCellClassName:'mycssclass' and added the class in my .css. The styles do not apply.
Please guide.

**Comment by AMBudnik** [comment]
Hi @vaidyasaurabh08 here is a live example http://jsfiddle.net/2394ufjx/
Some CSS settings (like background) are overwritten if you do not precise the class to `.handsontable .your-class`

**Comment by vaidyasaurabh08** [comment]
Hi @AMBudnik .

I am using Angular 6 with Handsontable.
Here is a stackblitz, where I am trying to follow the API for invalidCellClassName.
Can you please help me understand what am I doing incorrectly.

https://stackblitz.com/edit/handsontable-angular-st3nrw

**Comment by AMBudnik** [comment]
Hi @vaidyasaurabh08 
it looks like it's the only way to do it properly. We're pushing the settings to styles (main CSS file) as it respects encapsulation rules. [Here's](https://angular.io/guide/component-styles) more about it.
