### ISSUE TITLE
Manual Column Resizing behaves incorrectly?

### ISSUE THREAD

**Issue by aluu317** [handsontable/handsontable#3216]
Not sure if this is intentional, but I noticed that the manual column resizing only works correctly if I start the column resizing from the left most column and work my way out to the right. See the first attached.

![handsontablemanualcolumnresizecorrect](https://cloud.githubusercontent.com/assets/1454122/12961002/dd5da938-d003-11e5-88e1-2fec390d99a6.gif)

However, in the case when I start with a column that is not the first, nor the closest to one that has been manually resized, all the columns seem to shift together and the handle doesn't drop where it's supposed to. Then resizing from left to right fixes it. See following attached gif.

![handsontablemanualcolumnresizeincorrect](https://cloud.githubusercontent.com/assets/1454122/12961061/2cacb678-d004-11e5-9c96-d7f65a22b09b.gif)

Here is the jsfiddle: http://jsfiddle.net/dneqyzn9/4/

**Comment by AMBudnik** [comment]
Hi @aluu317 I think it's behaviour is very subjective when it comes to correctness. I was looking at this demo few times as it was repeating itself and I couldn't find a better way to resize these columns.
Can you share more detailed information when are how you desired it to resize?

**Comment by aluu317** [comment]
Hi. Thanks so much for your speedy response! And sorry the gif loops and it's hard to tell when it actually starts.

To explain what I meant again, referring to http://jsfiddle.net/dneqyzn9/4/. If you Run the code, then start by grabbing the handle between columns D and E, then drag it to somewhere, say right on top of the letter D, then release it. Notice how that handle/column divider doesn't stay where you dropped it, but rather got moved a little bit to the right. 

I understand that the table tries to adjust all of its columns to fit everything in its width. But my expectation is that the handle should stay exactly where I drop it, and the columns to either side of the handle could adjust their sizes accordingly. If you move the handle to the left, the left side columns should shrink and right side columns expand. And if you move the handle to the right, the right side columns shrink and left side columns expand. 

Another way that I think would also make sense is to only change the sizes of the two adjacent columns to the handle, in this case columns D and E, the rest of the columns is left untouched.

I hope this makes more sense. The original logic was probably intentional to fit all the columns in the table, but I just thought it'd be more user friendly if we leave the handle where user drops it because it could cause confusion if we place the handle somewhere else.

**Comment by AMBudnik** [comment]
Thanks for detailed explanation. I'll mark this topic to be discussed with the team. It sounds reasonably but in other hand there are many users who want it to behave as it's doing it now.

**Comment by krzysztofspilka** [comment]
I think that's to be added to the improvement ideas. @aluu317 is right at this point.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
