### ISSUE TITLE
Render all columns for excel export - turn off virtual rendering for columns too

### ISSUE THREAD

**Issue by karthikcsridhar** [handsontable/handsontable#3217]
Hi, renderAllRows work fine for me. But all columns are not rendering and there seem to be no renderAllCols or something like that ? 

I need to render all rows and columns because of 2 reasons:
1. I only have a 30 cols x 100 rows table and really do not want the virtual rendering that slows down scrolling.
2. Most important thing is I am exporting the html table as an excel file. In the exported excel file I see all rows but only 5-6 columns of the total 30, which ever is in the viewport currently. 

I know I can export the json data into excel instead of the html table, but I would like to export it from handsontable(html table) as it maintains the currency formatting in the excel. I am using a html table to excel export approach.

Could you please suggest a way to render all columns, even a hacky way is sufficient for me for the time being.

**Comment by sandys** [comment]
@karthikcsridhar can you describe how you are implementing the excel export ? I'm struggling with using https://github.com/SheetJS/js-xlsx to get it work.

**Comment by karthikcsridhar** [comment]
@sandys you can use this: http://w3lessons.info/2015/07/13/export-html-table-to-excel-csv-json-pdf-png-using-jquery/

just download & include the 3 js scrips and use:
$('#tableID').tableExport({type:'excel',escape:'false'});

as simple as that.

**Comment by karthikcsridhar** [comment]
@AMBudnik Hi AMBudnik. The original question was from me. The answer I gave is for another question from @sandys that wasn't relevant to my actual question. So this question is still unanswered. Could you please open it back ? Or can someone help with it ?

**Comment by AMBudnik** [comment]
Hi @karthikcsridhar yup, there's one subject left - sorry for a delay but unfortunately I didn't find any way to render all columns.

**Comment by atul-bhosale** [comment]
Work around is, set **viewportRowRenderingOffset** to total columns in grid. It will render all columns.
https://docs.handsontable.com/pro/1.10.0/Options.html#viewportColumnRenderingOffset
