### ISSUE TITLE
Getting row (tr element) 

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3219]
Is there an easy way of getting the row element itself, the `tr` element, by giving its row index?

In my case, I want to check whether any cell within a row contains a specific class. 
Rather than having to iterate through all the cells, extract its meta data and check the class, I find it much easier to just use jquery for it.

The problem is, I'm getting the `tr` element this way, which doesn't seem very right:

```javascript
var container = $('#example1');
var tbody = container.find('table').first().find('tbody').first();
var tr = tbody.find('tr').eq(rowIndex);
```

This way I can simple do:
```javascript
var grid = myHandsontable.getData();

$.each(grid, function(index, rowData){
    if ( $(tr).find('.demo').length)
});
```

vs the handsontable way: 

```javascript
var grid = myHandsontable.getData();

$.each(grid, function(index, rowData){
    if(rowhasClass(rowIndex, '.demo');
});

function rowhasClass(rowIndex, toSearch) {
    var hasClass = false;
    for (var i = 0; i < myHandsontable.countCols(); i++) {
        var cellMeta = hot1.getCellMeta(rowIndex, i, 'className');

        hasClass = hasProp(cellMeta, 'className', toSearch);
        if(hasClass){
        	return true;
        }
    }
    
    return false;
}

function hasProp(element, prop, value) {
    return typeof element[prop] !== 'undefined' && !!element[prop].match(new RegExp('(\\s|^)' + value + '(\\s|$)'));
};
```

**Comment by AMBudnik** [comment]
Hi @alvarotrigo it would be very hard to do not iterate trough every cell in a row cause every cell can have its own classes. There could something like `getRowMeta(row)` or `getColMeta(col)` but we only have `getCellMeta(row, col)`

I'll mark this issue as a feature to add `getRowMeta(row)` and `getColMeta(col)`

**Comment by alvarotrigo** [comment]
> it would be very hard to do not iterate trough every cell in a row cause every cell can have its own classes.

Maybe I didn't express myself properly.
What I meant is that, although you still have to iterate, having a way to get the `tr` element based on a cell would be of great help.

Something like:

```
var tr = hot1.getRowFromCell(rowIndex, colIndex);
```

This would allow me to do things such as:

```javascript
$(tr).find('.whatever'); 
```

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
