### ISSUE TITLE
tables loses comments after updateSettings call

### ISSUE THREAD

**Issue by jrowen** [handsontable/handsontable#3221]
I think [this jsfiddle](http://jsfiddle.net/n9L6ahwa/) should demonstrate the issue.  The table loses cell comments after a call to `updateSettings`.  Issue originally arose [here](https://github.com/jrowen/rhandsontable/issues/66).

**Comment by AMBudnik** [comment]
Confirmed. 
Related: https://github.com/handsontable/handsontable/issues/2621

**Comment by AMBudnik** [comment]
I couldn't reproduce it with the latest version 0.24.1. Can you confirm it @jrowen ?

**Comment by jrowen** [comment]
I updated to 0.24.1 but am still seeing the alignment issue.

**Comment by AMBudnik** [comment]
Thanks for feedback @jrowen

**Comment by AMBudnik** [comment]
I wasn't able to replicate the issue in the latest version: http://jsfiddle.net/uh6geLbk/
