### ISSUE TITLE
Security break: Too much TRs. With dropdowns.

### ISSUE THREAD

**Issue by mariusk** [handsontable/handsontable#3222]
I have a dropdown with 1000+ items in a cell. After selecting something from the dropdown, and THEN clicking anywhere else in the table, the warning is triggered. The table is initially empty, except the one row showing (because of minSpareRows set to 1). Looks like some limit is being triggered due to the number of items in the dropdown. Any ideas on workarounds, except reducing the number of items in the dropdown of course?

**Comment by AMBudnik** [comment]
Hi @mariusk please create a demo for this case.

**Comment by mariusk** [comment]
You can find a demo here:

http://jsfiddle.net/Lvp5skfs/

**Comment by AMBudnik** [comment]
Yes, it's fine, thank for sharing @mariusk 
Indeed there's an error.

**Comment by jtandrew** [comment]
I see the same issue and here is my jsfiddle

http://jsfiddle.net/5xuyqxtm/1/

Thanks @AMBudnik

**Comment by jtandrew** [comment]
Any updates on this?  We have recently purchase Handsontable Pro and we are seeing it there also.

**Comment by AMBudnik** [comment]
Unfortunately not yet @jtandrew

**Comment by AMBudnik** [comment]
same issue at: https://github.com/handsontable/handsontable/issues/2320
