### ISSUE TITLE
AutoColumnSize not working when pasting excel data on version >=0.16.0

### ISSUE THREAD

**Issue by pedrofsantoscom** [handsontable/handsontable#3223]
Hi there,

From version 0.15.1 to 0.16.0, something changed in option "autoColumnSize" that prevented from working anymore.

### **Test cases**

**System:**
Windows 10
Chrome 47.0.2526.111 m
Firefox 42.0

**Grab 1 row of data from excel, and paste in the demos below (can't add example data as github converts \t to spaces)**

**Demos:**
**Working - 0.15.1**
http://jsfiddle.net/hU6Kz/4831/

**Not working - 0.16.0**
http://jsfiddle.net/hU6Kz/4832/
http://jsfiddle.net/hU6Kz/4833/ - tried messing around with "syncLimit" values, with no success.

**Comment by AMBudnik** [comment]
Hi @pedrofsantoscom I can only test it with numbers for OSX and Google Sheets. Can you check it for the newest version of Handsontable which is currently [0.22.0](https://github.com/handsontable/handsontable/releases/tag/0.22.0)

**Comment by pedrofsantoscom** [comment]
Doesn't work also on the newest version 0.22.0 (see below). I found this problem using this version  on my app.

http://jsfiddle.net/hU6Kz/4834/

![image](https://cloud.githubusercontent.com/assets/2325978/13007219/a4d8316c-d186-11e5-8cdd-a512aada919e.png)

**Comment by AMBudnik** [comment]
OK, I got it working. It's an interaction with `columns`. We made some changes related to `autoColumnSize ` at [0.16.0](https://github.com/handsontable/handsontable/releases/tag/0.16.0) maybe it's related. Can you check it in you spare time @jansiegel ?
