### ISSUE TITLE
Paste more rows than those available

### ISSUE THREAD

**Issue by Skyback** [handsontable/handsontable#3224]
Hi!

If I paste 300 rows but only have 25 available, it doesn't do anything. Is this a bug or a feature? 

My settings are:
```
contextMenu:         false,
minSpareRows:        25,
maxRows:             1000,
stretchH:            'all',
fillHandle:          'vertical',
tableClassName:      ['table'],
currentRowClassName: 'hotSelectedRow',
colWidths:           null,
search:              true,
rowHeaders:          true
```

Scenario:

Table is empty, with the 25 spare rows. What I want to do is:
- paste 300 rows, use the 25 available and create 275 with the data and create another 25 spare rows if they don't break the maxRows limit.

**Comment by AMBudnik** [comment]
Hi @Skyback 

Hi `minSpareRows` with always create as many empty rows as you force it to add. If you have 25 rows and `minSpareRows: 25` if you fill `25` row you'll end up with `50` row table. If you fill `10` row you'll get `35` (10 filled + 25 empty) row table. 

I made an example with 25 spare rows and no data - where it gave me 25 empty rows total. Then pasted 300 rows and got 325 rows total, so it sounds like the scenario is the same as the result. You experienced something else?

**Comment by Skyback** [comment]
I experience something else... With 25 spare rows and no data, if I paste 300 rows it doesn't do anything. The scenario you described is exactly the kind of behavior I want. I will try to find out more about this...

**Comment by Skyback** [comment]
I'm sorry, this was reported to me by a team member and I tested it on [a demo page of yours](https://docs.handsontable.com/0.22.0/demo-pre-populating.html).

And there I got this behaviour (if I copy all the rows to the empty row, it doesn't do anything). I know tested this on my app (chrome and firefox) and it seems to have the correct behaviour.

**Comment by AMBudnik** [comment]
Yes, this case: https://docs.handsontable.com/0.22.0/demo-pre-populating.html is a little bit for different purposes. 

I made this demo: http://jsfiddle.net/5dpp66dk/ where you only have to copy cells from the first instance to the second
