### ISSUE TITLE
Drop Down is Clipped in Scrolling Handsontable

### ISSUE THREAD

**Issue by llimz** [handsontable/handsontable#3228]
I have a Handsontable that is horizontally scrolling. The width is explicitly fixed, the height is auto and the containing DIV has auto overflow.

When a drop down cell is activated, i.e. the drop down container with items is shown, the items list is clipped. I have to scroll down to view all of the items. How can I style the drop down items list such that it appears above the scrollable area?

Here is an example of the clipped drop down: http://jsfiddle.net/ehLeur99/

Here is the DIV styling:

<div id="example1" class="hot handsontable" style="width: 210px; height: auto; overflow: auto;"></div>

**Comment by AMBudnik** [comment]
Hi @llimz 
We have the same issue at https://github.com/handsontable/handsontable/issues/3210
Please track changes to that one for further information.
