### ISSUE TITLE
Feature request: countSourceCols

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3230]
There's a `countSourceRows` function but there isn't any countSourceCols.

Related with https://github.com/handsontable/handsontable/issues/3190 as there's no way to count the data source columns with `length` even when using `getSourceDataAtRow` when the returned array is not really an array but **an object**.

**Comment by alvarotrigo** [comment]
The only workaround I found to deal with it is iterating over the object properties.
```javascript
var rowData = hot1.getSourceDataAtRow(rowIndex);

for (var property in rowData) {
     if (rowData.hasOwnProperty(property)) {
         console.warn("index: " + property + " value: " + rowData[property]);
     }
}
```

**Comment by AMBudnik** [comment]
Agree, if there are `countSourceRows` we could add `countSourceCols`
Thanks for an idea.

**Comment by AMBudnik** [comment]
Hi again,
I just had a chat with one of our programmers and I was told that this feature won't do anything more than  `countCols` as long as there's no `trimCols` (only a `trimRows` in PRO).

**Comment by alvarotrigo** [comment]
I don't know the concept of `trimCols` or `trimRows`, but if by that you mean, hidden rows or columns that are not actually represented in the grid (and therefore can not be extracted with `getData`), yep, there is.

Whenever we do `setDataAtRowProp` using a property name of a column which is not being used in the `columns` object.
