### ISSUE TITLE
Question: Removing row by an index no longer exist?

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3231]
I'm not quite sure if there's anything that can be done in this case. 

Having the following scenario:
- We have a table with, lets say 50 rows.
- The user removes the content of the last 30 rows
- Before saving the grid with a button I want to remove the empty rows.
- Clicking the save button checks the rows one by one from top to bottom to see if there's any data on them, if there's no data in any column, the row will get removed. 

The problem:
- After removing rows 20 to 35 (50 - 30 + 30/2), when trying to remove row 36, the row with index 35 doesn't exist anymore. As now the table only contains 35 rows with indexes from 0 to 35.

[Example online](http://jsfiddle.net/7u1kxjLe/28/)

``` javascript
$('#removeEmptyRows').click(function() {
    var grid = hot1.getData();

    $.each(grid, function(rowIndex, rowData){
        console.log(rowIndex);
        var numColumns = countColumns(rowData);

        //no data in the row ?
        if(!numColumns){
            if(rowIndex < hot1.countRows()){
                hot1.alter("remove_row", rowIndex);
            }
        }
    });
});
```

The solution I found was to iterate the table in the inverse order first to do the validation and remove them from the bottom up.

``` javascript
            //we remove rows 
            for(var i = grid.length-1; i >= 0; i--){
                var rowData = grid[i];
                var numColumns = self.countColumns(rowData);

                //are all columns empty?
                if(!numColumns){
                    hot1.alter("remove_row", i);
                }
            }
```

I was wondering if there's a way to deal with this situations which might be more suitable.

**Comment by AMBudnik** [comment]
I guess I would rewrite data without empty rows. What do you think about this tip?

**Comment by alvarotrigo** [comment]
Not quite sure what you mean by that. Can you explain it in another way?

**Comment by AMBudnik** [comment]
I was thinking about rewriting the table instead of removing rows but I guess your solution is better. I came across the same issue when I wanted to remove rows: http://jsfiddle.net/072q1130/1/

**Comment by jansiegel** [comment]
@alvarotrigo I think your 'reversed' method is a good way to do this. It's probably similar to your approach, but I made this simple demo: http://jsfiddle.net/js_ziggle/8f2r59Ld/
