### ISSUE TITLE
ManualColumnMove / ManualRowMove does not work for multiple instances.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3233]
Demo: http://jsfiddle.net/dz6jrr24/11/

You can only move cols/rows in second instance.

(Reported at: https://forum.handsontable.com/t/manual-row-move-only-works-with-last-created-table/163)

**Comment by DHoffm** [comment]
Hi any updates on this topic? Is there a quickfix solution which I can integrate on my own until a final fix.

**Comment by AMBudnik** [comment]
I was trying to share a quick workaround but only thing that I've found is that `resize` and `move` are similar and `resize` (which works) takes a `hotInstance` as an argument and `move` does not but I didn't want to change the source code.

**Comment by DHoffm** [comment]
Can you share your workaround here?

**Comment by budnix** [comment]
One of our programmers currently rewrites `ManualColumnMove` and `ManualRowMove` to a newer plugin structure. When an update this bug should automatically be solved. Probably fix will be ready for the next release.

**Comment by DHoffm** [comment]
Thanks for the info...much appreciated. Is there any fixed date when the next release is ready?

**Comment by budnix** [comment]
@DHoffm Release probably will be in the middle of the next week.

**Comment by DHoffm** [comment]
Sounds good to me.

**Comment by IntegerMan** [comment]
I'm also seeing an issue with this - not with multiple instances, but with HoT simply refusing to respond to manualRowMove or manualColumnResize. I'm trying to isolate steps for this so that it can be JSFiddle-ized, but so far no luck. Any chance this fix will help my issue? Also has this been deployed yet?

**Comment by IntegerMan** [comment]
An update on my non-sequitur issue. I've determined that my problem was unrelated to the issue reported in this thread and was a subtle issue caused by not including zeroClipboard.js. Don't worry about my prior statement.

**Comment by DHoffm** [comment]
Any updates on this topic? Will the rewrite also fix to this bug aswell: https://github.com/handsontable/handsontable/issues/2868

**Comment by AMBudnik** [comment]
Example updated to 0.24.0 http://jsfiddle.net/handsoncode/dz6jrr24/12/ Confimed working.
Could you test it @DHoffm @IntegerMan ?

**Comment by DHoffm** [comment]
Thx seems to work for me!

**Comment by IntegerMan** [comment]
Everything looks fine to me, but @DHoffm's issue was different than mine it turns out - mine wound up being on my side as a subtle side effect of us not including zeroClipboard, so he's definitely the person to judged resolved status.

**Comment by AMBudnik** [comment]
Thanks for feedback @IntegerMan 
@DHoffm #2868 was closed as we added [rowHeaderWidth](https://docs.handsontable.com/0.24.0/Options.html#rowHeaderWidth)

Thanks again for you feedback and time. I assume I can close this issue.

**Comment by DHoffm** [comment]
I recognized something. In the following fiddle I used a fixed width and height: and called afterRowMove so set a height: http://jsfiddle.net/61vb7rko/

Somehow is scaled larger than the specified width and height.

**Comment by AMBudnik** [comment]
I can see what you mean @DHoffm 
I'm reopening this issue as this bug was found while updating to 0.24.0

[0.23.0](http://jsfiddle.net/handsoncode/61vb7rko/1/) 
Scenario: Resize any row
Result: Table `width` and `height` stays the same

[0.24.0](http://jsfiddle.net/handsoncode/61vb7rko/2/)
Scenario the same as above.
Result: table ignores `width` and `height` settings

**Comment by AMBudnik** [comment]
fixed with https://github.com/handsontable/handsontable/issues/3329

**Comment by jansiegel** [comment]
@DHoffm Thanks for reporting this! As @AMBudnik mentioned, fix for this issue was just released as version `0.24.1`.
