### ISSUE TITLE
Callback beforeDatePicker 

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3235]
I would like to change the data before a cell with the `date` type opens calendar.

I checked the pikaday.js library used by handsontable but [it seems there's no callback](https://github.com/dbushell/Pikaday/issues/488) to do anything to the data before it gets open.

Having a callback in handsontable would solve the problem.

**Comment by alvarotrigo** [comment]
My dates looks like this: `14/02/2016 [INVALID]`.
Which means I need to treat somehow the date before opening the datepicker, or tell `moment.js` that the format is valid and it should still parse it.

I found out handsontable forces the format to be strictly the same as the one provided in the datepickerconfig format, which in my case would be `DD-MM-YYYY`.
But that wouldn't allow `DD-MM-YYY string`.

Another way to solve this issue would be if handsontable provided a way to specify if the format should be strict or not.

Right now handsontable uses in line [7497](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.js#L7497) and 7506: 

```javascript
if (moment(dateStr, dateFormat, true).isValid()) {
```

Instead of 
```javascript
if (moment(dateStr, dateFormat).isValid()) {
```

I ended up modifying the plugin to accomplish my purpose, but adding an option in handsontable would be great.

**Comment by jansiegel** [comment]
@alvarotrigo, Adding a `strict` option seems like a good idea (especially that `moment.js` seems to handle it pretty well).

Note for future reference: needs to be added for both `Date` and `Time` validators.

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
