### ISSUE TITLE
Is triggerPaste not working?

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3236]
Trying to trigger copyPaste but It doesn't paste anything at all. 
What am I doing wrong?

[Reproduction online](http://jsfiddle.net/7u1kxjLe/31/)

```javascript
$('#paste').click(function() {
   hot1.copyPaste().triggerPaste();
});
```

**Comment by Nao-K** [comment]
Please add following property:
outsideClickDeselects: false

And use this:
hot1.copyPaste.triggerPaste();

http://jsfiddle.net/nao_k/7u1kxjLe/37/
