### ISSUE TITLE
Problem with validateCells

### ISSUE THREAD

**Issue by mfandre** [handsontable/handsontable#3237]
I saw this issue "validateCells() calls the callback incorrectly #933" but I think it was still not fixed. I'm having the same problem, look this http://jsfiddle.net/3zeess0m/2/

When I put correct data (numeric data at first column) on my utgGrid (first one) and then validate, Im getting two alerts of success (why two???)...

When I put a wrong data I'm receiving one alert of success.... Thats something wrong...

**Comment by AMBudnik** [comment]
Hi @mfandre Can you simplify this example a little bit and add an `alert` or `console.log` to inform about the issue you've reported?
Thanks in advance!

**Comment by mfandre** [comment]
AMBudnik, see if better now:
http://jsfiddle.net/3zeess0m/3/

**Comment by AMBudnik** [comment]
Hi @mfandre 
Sorry for a delay. I couldn't reproduce it with the latest 0.24.1 version. If it still doesn't work correctly could you guide me how to reproduce the issue?

In the meantime, thank you so much for your attention and demos.

**Comment by mfandre** [comment]
This was fix in 0.24.1. Thx!

**Comment by AMBudnik** [comment]
Great to hear that @mfandre 
Thanks for feedback.
