### ISSUE TITLE
Rows misaligned when fixed column is used with cells that contain wrapped text

### ISSUE THREAD

**Issue by thip** [handsontable/handsontable#3239]
See this jsfiddle: [http://jsfiddle.net/t12hct3c/9](http://jsfiddle.net/t12hct3c/9/)

If you look between columns 2 and 3 (between the fixed column and the rest of the table) you will see that the rows are out of alignment by about 1 pixel (Although in the application I am working on this can grow to the point where rows don't align at all). As far as I can tell, this is cause by the text wrapping in the 6th column. It's not too bad when you only have small amounts of data but when the tables get long and the alignment gets worse it becomes unusable as you can see in this (censored) image of our application!

![](http://oi68.tinypic.com/25z2y2o.jpg)

**Comment by thip** [comment]
Turning on row headers seems to fix this (Although it's not a solution I am able to use in this application as we don't want them!)

**Comment by AMBudnik** [comment]
Hi @thip it looks as expected at Safari and Chrome on OSX. Can you provide your OS/Browser information?

**Comment by thip** [comment]
I'm seeing it on Windows 7 using chrome 48 and IE11. I also tried chrome on OSX a second ago at home and was seeing the same issue. It's very subtle in the jsfiddle as it's only out by about 1px but dragging a selection over the second row makes it more obvious, as does increasing the browser zoom level.

**Comment by AMBudnik** [comment]
Yes, I got it. 
I guess it's related to https://github.com/handsontable/handsontable/issues/2354

**Comment by AMBudnik** [comment]
Issue is gone after adding [autoRowSize: true](https://docs.handsontable.com/pro/1.6.0/Options.html#autoRowSize), demo: http://jsfiddle.net/Ljd2jng9/
