### ISSUE TITLE
ReadOnly Clear Values

### ISSUE THREAD

**Issue by NJDave71** [handsontable/handsontable#324]
I am using 2 columns to provide feedback.   How do you clear the values?   handsontable('clear') doesn't clear these columns.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by markusp72** [comment]
+1

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
