### ISSUE TITLE
Formulas are not recalculated when values are copied from excel and pasted to HandsOntable.

### ISSUE THREAD

**Issue by satyAltera** [handsontable/handsontable#3241]
When I copy and paste cell with initialized values from HandsOnTable to another set of cells, it copies the values into the cells and recalculates cells that have formulas which refer to the cells with copied value. This is good and as expected.

When I copy and paste code from excel to a hands on table row, the values are copied into cells but  cells that have formulas or equations which refer to the cells with copied value are not recalculated.

When I manually enter values into cells and copy those manually entered values into other cells, the values are copied but cells with formulas refering to the cells with copied value are not recalculated.

**Comment by AMBudnik** [comment]
Hi @satyAltera formula support is still a experimental feature so there could be some issue related. Could you please share with me a scenario with a demo where it will be easily to check what's happening and what should happen instead?

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo for more than 2 weeks.
