### ISSUE TITLE
Can't Test Handsontable With PhantomJS

### ISSUE THREAD

**Issue by opticyclic** [handsontable/handsontable#3242]
The use of the word 'name' [here](https://github.com/handsontable/handsontable/blob/3e8ca2e17a0fdad65b66ca21f9192a3a55e57292/src/shims/classes.js#L173-L179) appear to be causing tests to fail when running with [PhantomJS](https://github.com/ariya/phantomjs/issues/13895)

    [ERROR - 2016-02-18T03:49:25.393Z] Session [9323b160-d5f2-11e5-8264-a37925c9b5cd] - page.onError - msg: TypeError: Attempting to configurable attribute of unconfigurable property.
    
      phantomjs://platform/console++.js:263 in error
    [ERROR - 2016-02-18T03:49:25.393Z] Session [9323b160-d5f2-11e5-8264-a37925c9b5cd] - page.onError - stack:
      defineProperty (http://localhost:32241/web/webjars/handsontable/0.19.0/dist/handsontable.full.js:17625)
      defineProperty (http://localhost:32241/web/webjars/handsontable/0.19.0/dist/handsontable.full.js:17625)
      extendEvent (http://localhost:32241/web/webjars/handsontable/0.19.0/dist/handsontable.full.js:8301)
      callbackProxy (http://localhost:32241/web/webjars/handsontable/0.19.0/dist/handsontable.full.js:8169)
      sendEvent (:0)

**Comment by AMBudnik** [comment]
Hi @opticyclic 
we usually use GitHub to resolve issues reported by Handsontable developers related to strictly Handsontable. For issues/questions related to other libraries please open new topic at stackoverflow: https://stackoverflow.com/search?q=handsontable

**Comment by andrewmorgan** [comment]
Asked here then
https://stackoverflow.com/questions/36127290/cant-test-handsontable-with-phantomjs
