### ISSUE TITLE
Allow preventOverflow: true

### ISSUE THREAD

**Issue by gstanislav** [handsontable/handsontable#3243]
http://jsfiddle.net/e0jsgxv4/

Column headers are misaligned from the start. After some scrolling this happened: 

![image](https://cloud.githubusercontent.com/assets/7578355/13137513/83ffdd04-d632-11e5-954a-7fe3e90e3f2c.png)

Chrome 48 on OSX Yosemite.

**Comment by budnix** [comment]
Hi @gstanislav, currently `preventOverflow` works in one axis in `'horizontal'`mode. I've updated [demo](http://jsfiddle.net/e0jsgxv4/1/).

**Comment by gstanislav** [comment]
Ah, right. Still, I think doing `preventOverflow: true` should either be a noop or throw an error.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
