### ISSUE TITLE
Calling sort method doesn't reflect on sort indicator

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3245]
When we call `sort(1, true)` method or try to sort column calling `updateSettings({columnSorting: {column: 1, sortOrder: true}})` sorting indicator doesn't indicate current sorting state.

--------

##### Steps to reproduce:

* Go to http://jsfiddle.net/rq36sape/1/;
* Click 'sort' button;
* **Sorting indicator should change the state.**

**Comment by budnix** [comment]
Related with https://github.com/handsontable/handsontable/issues/2676.

**Comment by krzysztofspilka** [comment]
Looks good on localhost
