### ISSUE TITLE
Auto col resize doesn't work when using property names 

### ISSUE THREAD

**Issue by grizzlydev** [handsontable/handsontable#3247]
Hi,

When configured with 

```
{ ...,
columns: [ { "data" : "prop_name", ... } ]
...}
```

Problem appears to be [here] (https://github.com/handsontable/handsontable/blob/master/src/plugins/autoColumnSize/autoColumnSize.js#L375) in `autoColumnSize.js`. It looks like this code is supposed to set the relevant width (`this.widths[col]`) to `undefined`. However, with prop names, `changes` array contains a string at index `1`, not col index value. 

Consequently the later change detection on `this.widths[col]` doesn't work and column widths don't update.

Or am I missing something - can `this.widths` be string indexed?

Thanks

**Comment by budnix** [comment]
You are right `this.widths` is an array and should have only number indexes. I've good news for you, this bug was fixed and it's waiting for release. 

Connected with https://github.com/handsontable/handsontable/issues/3223.

**Comment by grizzlydev** [comment]
@budnix - great news - thanks for speedy reply
