### ISSUE TITLE
multiSelect:false selecting issue

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3250]
Demo: http://jsfiddle.net/rmv414xp/1/

It appears randomly and there's no console errors.
reported at: https://forum.handsontable.com/t/issues-on-multiselect-false/166

Steps: 
1. Select any cell that it's not on the border of the table.
2. Try to drag it to be border.

Video:
![multiselect](https://cloud.githubusercontent.com/assets/10757813/13170096/f2f231fa-d6e9-11e5-991f-842933ac442e.gif)

`[G #561]`

**Comment by abhilash503001** [comment]
**Note For Author** : Please make necessary changes as per your logic for "multiselect=false", here i resolved the issue, same you can implement as per you logic in next version.

I made some changes on plugin **handsome.js**: 
:20 line:
1st Step :  at line number 20th at handsome.js add a global variable "var multiSelectAdded = true;"

than goto :5037 line :
2nd step : at this finction setRangeEnd: function(coords, scrollToCell, keepEditorOpened).
assign "multiSelectAdded = priv.settings.multiSelect;"

than made a condition for prewrriten code ::::
if(multiSelectAdded){
		priv.selRange.to = new WalkontableCellCoords(newRangeCoords.row, newRangeCoords.col);
					  if (!priv.settings.multiSelect) {
						priv.selRange.from = coords;                
					  }
				  }//End

than goto :1415 line :
inside function :::"var onMouseOver = function(event) {",

Make changes

if(multiSelectAdded){that.instance.getSetting('onCellMouseOver', event, that.instance.wtTable.getCoords(td), td, that.instance);}


for the same i attached image for better understanding
![step1](https://cloud.githubusercontent.com/assets/8927084/13520621/f1a78f7e-e207-11e5-9016-188eda91ff2b.JPG)

![step3](https://cloud.githubusercontent.com/assets/8927084/13520624/f2753adc-e207-11e5-8bf7-41533adbb07c.JPG)
![step4](https://cloud.githubusercontent.com/assets/8927084/13520623/f22dada2-e207-11e5-9cd4-938478b977e0.JPG)



:

**Comment by abhilash503001** [comment]
![step2](https://cloud.githubusercontent.com/assets/8927084/13520689/7b84a164-e208-11e5-942e-eb3bdc1769c8.JPG)

**Comment by AMBudnik** [comment]
Thanks for feedback @abhilash503001 could you create a pull request with our solution?

**Comment by AMBudnik** [comment]
Issue still replicable in 0.29.2

**Comment by AMBudnik** [comment]
The issue is still replicable in v0.35.1

**Comment by AMBudnik** [comment]
It looks like the https://github.com/handsontable/handsontable/issues/4711
