### ISSUE TITLE
Does it have the features I need?

### ISSUE THREAD

**Issue by PhpSriptKiddie** [handsontable/handsontable#3252]
Hey there.

I am currently in the process of webifying a collection of excel-based tools for online use. Before I get too far in the process, I would like to verify that I am actually able to build what I need. I have been looking through old posts and examples, but I'm still not 100 % certain. Hopefully someone is able to clarify the following aspects for me:

1. I need the user to be able to color cells, merge cells and other types of styling. Are saving and later loading of these metadata supported?

2. In my Excel sheets, conditional replacement of icons is used. For example, if I type 1 in specific fields, the number is replaced with a little icon representing 1. Can I listen for specific numbers/words and have them replace with icons? I know imagerenderer is supported, but I'm not sure that the replacement is.

3. In some of the demos i've seen, I am able to right click and see a point named merge cells. However, my selection disappears as soon as I right click and the merging doesn't seem to work. I suppose it is possible to get it to work somehow?

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 

about 1 question we discussed it at https://github.com/handsontable/handsontable/issues/3259,
2. Interesting question, I've never tried but I guess it can be changed with a custom renderer.
3. Could you bring me more details about that? Maybe a demo.

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 
If you're still looking for an answer please create a demo that will bring some light to 3rd point of your last comment.
I'm closing this issue till it gets updated.
