### ISSUE TITLE
Can't paste more columns than defined in the array

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3253]
In some cases when I paste the data from Excel to Handsontable, it doesn't get pasted - at least not visually. Validation, on the other hand, works fine in such cases. See the example below:

**Steps to reproduce the issue:**
- Open this Excel (or import it to Google Sheets), select and copy all the values https://db.tt/xrm7WP59
- Paste the clipboard's contents in cell A1 in the Date Cell Type demo: http://docs.handsontable.com/0.23.0/demo-date.html

https://i.gyazo.com/f15f184bd2ad9e9c99d1600f74d19a9e.gif

Notice: the above works fine with this demo: http://docs.handsontable.com/0.23.0/demo-drag-down.html but I couldn't find the pattern to determine what is causing the issue.

Bug exists: at least since 0.15.0
OS: Windows 8.1
Browser: Chrome (latest)

**Comment by swistach** [comment]
That's works properly in actual version of Handsontable (0.24.3).
