### ISSUE TITLE
Updating height of table breaks frozen column

### ISSUE THREAD

**Issue by gstanislav** [handsontable/handsontable#3255]
Create a Handsontable instance without set height. Then, use `updateSettings` to set height and scroll around a bit. Result:

![image](https://cloud.githubusercontent.com/assets/7578355/13177829/9b8e4b68-d72c-11e5-8c89-2ab3c6c84378.png)

http://jsfiddle.net/s6t768pq/78/

**Comment by krzysztofspilka** [comment]
@gstanislav I'm just curious, what is your application doing that requires changing the height via updateSettings?

**Comment by gstanislav** [comment]
I want to set max height. 

If the window becomes too short to accommodate the whole table, including the bottom scrollbar, I want it to become constrained to the height that allows the bottom scrollbar to be visible.

**Comment by jansiegel** [comment]
There seems to be some issues with `width` and `height` that need some investigation, too.
