### ISSUE TITLE
Restrict dropdown to individual cells?

### ISSUE THREAD

**Issue by mikeptweet** [handsontable/handsontable#3258]
Is it possible to use the various cell types (i.e. drowndowns, autocomplete,etc) in individual cells as opposed to use a column type?

I want to add a dropdown on just individual cells in separate columns

**Comment by AMBudnik** [comment]
Hi @mikeptweet Here's a demo where it is one one dropdown cell in a grid, at `1, 1`: http://jsfiddle.net/2bpjcxgo/ There's the same renderer for dropdown and an autocomplete.

**Comment by mikeptweet** [comment]
Awesome ... exactly what I was looking for. Thanks for the prompt response!
