### ISSUE TITLE
Save colored cells

### ISSUE THREAD

**Issue by PhpSriptKiddie** [handsontable/handsontable#3259]
Hey there.

I am trying to create a solution where the user is possible to color cells and save information about the colored cells along with the data of the table, so everything can be loaded again at a later timer.

I have found this JSFiddle that supports coloring of cells. However, I have no idead how to save this metadata afterwards. Can someone please point me in the right direction?

http://jsfiddle.net/McCroskey42/n3eoeqLd/7/

PS: No matter what example I find, my selection of cells is removed when I right click. This means I cant merge cells or color a selection of cells. Why is this happening?

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie this seams to be a more complicated example. To color cells permanently we use custom renderers/conditional formatting like in this example: http://jsfiddle.net/ozvL8v7n/ 

If you would like to color all cells in different colors maybe create a checkbox and depending on it's state pass the color to renderer.
