### ISSUE TITLE
selectCell issue with a key value with quotation marks

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3260]
Working demo: http://jsfiddle.net/o66gxxay/1/
Issue demo: http://jsfiddle.net/o66gxxay/2/

SelectCell does not select a cell represented as: `{'key': 'value'}` 
key value has to be `{key: 'value'}` represented without quotation marks.

There are no console errors.

**Comment by krzysztofspilka** [comment]
@budnix can't prioritize it, pls help:)

**Comment by AMBudnik** [comment]
@krzysztofspilka my bad. It http://jsfiddle.net/o66gxxay/3/ works fine
