### ISSUE TITLE
Handsontable stealing keystrokes when setting focus outside of table

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#3262]
I am seeing an issue with Handsontable stealing keystrokes if you programmatically set focus to an input control outside of the Handsontable.  For example, if you have a modal dialog popup over the Handsontable which contains form controls.

I have a simple sample which demonstrates this with the latest version (0.23.0):  http://jsfiddle.net/cgatesman/f0cwcgbz/

**Comment by AMBudnik** [comment]
Hi @cgatesman this one https://github.com/handsontable/handsontable/issues/401 seams to be the same case. Can you take a minute to check it?

**Comment by cgatesman** [comment]
It seems to be, but I don't think `outsideClickDeselects` has anything to do with the actual problem.  I am not setting that to `false` in my example.  The title and initial description of #401 may be a bit misleading to the real problem.

**Comment by jansiegel** [comment]
@cgatesman, you might want to try using the `unlisten` method in your input-focusing callback.
I included it in your demo: http://jsfiddle.net/js_ziggle/921yp9b7/1/.

Does that help?

**Comment by pdemilly** [comment]
@jansiegel What about a method for handsontable instance to stop listening to mouse events while in a custom editor. Right now in the open phase of my custom editor I am doing this

               document.documentElement.addEventListener('mousedown', stopEvent, true);
              documentMouseDownListener = function () {
                        document.documentElement.removeEventListener ('mousedown', stopEvent, true);
                };

**Comment by cgatesman** [comment]
> @cgatesman, you might want to try using the unlisten method in your input-focusing callback.
I included it in your demo: http://jsfiddle.net/js_ziggle/921yp9b7/1/.

> Does that help?

This looks like it may work for me.  I'll have to try it out on my project to see if it works in my full app environment.  I don't know if this is something Handsontable can take care of automatically, or not, but this manual method should work in my different cases.
