### ISSUE TITLE
RenderAllRows conflict with selectCell

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3263]
Demo: http://jsfiddle.net/o66gxxay/6/

Settings:
`height:500,`
`renderAllRows: true`

Under the button we have `hot.selectCell(50,10)` that should scroll the table to `50, 10` cell but with those settings configuration it scrolls about 30 rows less.

Tips:
Commenting any on those settings solves the issue.

**Comment by ltoews** [comment]
"Commenting any on those settings solves the issue."

Could you explain what you mean by this?

**Comment by AMBudnik** [comment]
@ltoews I meant that it's a correlation between those two `height` and `renderAllRows` and when you use only one of them in your settings this issue doesn't occur.

**Comment by ltoews** [comment]
Ah! I see what you mean. I was hoping this would solve I problem I have, but unfortunately not.

Perhaps you can help...

I have two handsontables side by side on the same page (both divs are height:100%, overflow: hidden, and the first div is float:left), and when a user clicks in a column in the first table I want to scroll to and highlight the corresponding row in the second table. (e.g., user clicks on any cell in **column** 30 of table #1, I want to highlight (by setting the bg color) all of **row** 30 in table #2, and scroll it into view if necessary.) Highlighting the row in table #2 works OK, but the row won't scroll into view.

I've tried to create a fiddle to demo this, but I can't get two handsontables to exist side by side (or even one above the other!).

Any suggestions?

**Comment by AMBudnik** [comment]
Hi @ltoews I made a simple demo with two instances side by side with a class to highlight hot2's rows: http://jsfiddle.net/e99s76ox/ can you share your recent progress with this demo? 

If so, please create a **new** issue. I would like to leave this one only for updates related to fixing/updating this bug.

**Comment by ltoews** [comment]
Aleksandra,

Thanks for setting up the fiddle. I've modified it to duplicate the functionality that I need. I've commented out a bit of your code and inserted the code I've been using.  Click anywhere in column x in table 1, and row x is highlighted in table 2. The scrolling works as it should.

I've added column headers in table 1, and row headers in table 2 so it's easier to see that clicking in column 20 of table 1 causes table 2 to scroll to row 20 and highlight it.

Now I just need to look at my own code to figure out what I'm doing differently.

I've made a copy of the fiddle for future testing. 

Thanks again for helping set up the fiddle.

Lorin

**Comment by AMBudnik** [comment]
@ltoews could you please share the demo that you made a progress at?

**Comment by ltoews** [comment]
https://jsfiddle.net/ltoews/e76h6he8/ <https://jsfiddle.net/ltoews/e76h6he8/>

**Comment by AMBudnik** [comment]
Looks promising @ltoews keep the good work going. If anything else will came to you - please create a new topic.

**Comment by Adelor** [comment]
I have the same issue. The selectCell function doesn't scroll vertically if renderAllRows: true
Upon debugging, I found that the scrolling logic is located in the 
`scrollViewport: function(coords) { `
...
function. The table is scrolled vertically here:
`    if (coords.row >= fixedRowsTop && coords.row < this.getFirstVisibleRow()) {
      topOverlay.scrollTo(coords.row);
    } else if (coords.row > this.getLastVisibleRow() && coords.row < totalRows - fixedRowsBottom) {
      topOverlay.scrollTo(coords.row, true);
    }`
None of these is executed, because this.getFirstVisibleRow() is always 0 and this.getLastVisibleRow() is equal to rows length with renderAllRows:true.


If you ever provide the renderAllColumns property, the horizontal scrolling logic should be patched as well.

**Comment by AMBudnik** [comment]
Update: Selection is made properly but the were not getting correct scrolling

![selectcell](https://cloud.githubusercontent.com/assets/10757813/17059297/c6a7ae04-5024-11e6-92e0-d83191afa15c.gif)

**Comment by AMBudnik** [comment]
The issue does not occur in version 0.35.1. Updated demo http://jsfiddle.net/725orfa9/

![gif](https://user-images.githubusercontent.com/10757813/35667945-c805dc4e-072f-11e8-8dce-a8f24395946e.gif)
