### ISSUE TITLE
Multiple dropdown

### ISSUE THREAD

**Issue by lesonunique** [handsontable/handsontable#3264]
Hello,

I would use the `Dropdown` function but by allowing the selection of several parameters and as well as for adding a parameter is not present in the list.

A system like this would be perfect:
https://www.zellerda.com/projects/tokenize

Is it possible to integrate it with the `Rendering custom` ? If so, how do I do this?
Is it otherwise another way to have a similar system? (Dropdown with several settings and adding custom parameters)

Thank you in advance.

Cordially.

Vincent LEVEQUE

**Comment by AMBudnik** [comment]
Hi @lesonunique 
This feature request is already in our board at https://github.com/handsontable/handsontable/issues/2498
Please track changes to https://github.com/handsontable/handsontable/issues/2498 for more information.

**Comment by lesonunique** [comment]
And is not possible to integrate a rendering custom of this : https://www.zellerda.com/projects/tokenize ?

Because the last news of #2498 are in June 2015 so this feature not going to happen soon..

**Comment by AMBudnik** [comment]
Hi @AMBudnik 

 I'm happy to announce that the issue is solved! You can test the multi-select cell type here https://handsontable.com/docs/javascript-data-grid/multiselect-cell-type/
