### ISSUE TITLE
add/remove row/colmn programmatically

### ISSUE THREAD

**Issue by computurus** [handsontable/handsontable#3265]
I want to bind row/column adding to buttons inside my webapp. Searching the documentation, I did not found any useful functions. Are there any workarounds or did I miss something?

**Comment by AMBudnik** [comment]
Hi @computurus you can find `alter` useful. Here's more information https://docs.handsontable.com/0.23.0/Core.html#alter

**Comment by computurus** [comment]
That is what I need thanks
