### ISSUE TITLE
Select cell type nav issue

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3269]
Demo: https://docs.handsontable.com/0.23.0/demo-select.html
1. Choose an option in select cell type (any at column `B`) and press `enter` to accept.
2. Try to navigate to other cell using `TAB` or arrow navigation.

Using tab doesn't allow to move between cells and arrow navigation opens select one more time to navigate through its options.

`[G #604]`

**Comment by jdpagley** [comment]
@AMBudnik Any idea when this is going to be fixed?

**Comment by AMBudnik** [comment]
Hi @jdpagley 

I am sorry but I do not have any news about this issue

**Comment by AMBudnik** [comment]
The issue is no longer replicable in v `2.0.0`/ Please check that @jdpagley and let me know if you're still using the product.

**Comment by AMBudnik** [comment]
The issue is still replicable https://handsontable.com/docs/7.4.2/demo-select.html

**Comment by AMBudnik** [comment]
Tested using the latest (v12.1.3) select demo at https://handsontable.com/docs/javascript-data-grid/select-cell-type/#usage and it still works the same. Once a user confirms the choice with the <kbd>ENTER</kbd> key the list of choices is closed but tab doesn't seem to do anything. Tabbing again exits the table. While using a `dropdown` once we use <kbd>ENTER</kbd> key to confirm the dropdown choice we can use <kbd>TAB</kbd> key to move between cells. That's definitely an `Accessibility` type issue.

**Comment by AMBudnik** [comment]
Hi @jdpagley We were able to improve the navigation of a `select` cell type in Handsontable v14.1.0 with this pull request https://github.com/handsontable/handsontable/pull/10673

We also verified that it's not possible to implement cell tab navigation when the dropdown list is opened due to the limitation of the native HTML select element. So at this point we can call this issue resolved.
