### ISSUE TITLE
How to remove default sorting from handsonTable. I need only ascending and descending order sorting ?

### ISSUE THREAD

**Issue by ranjan653** [handsontable/handsontable#3270]
How to remove default sorting from handsonTable. I need only ascending and descending order sorting

**Comment by AMBudnik** [comment]
Currently it's not available, but you can forcefully set sorting order with [`setSortingColumn(col, order)`](https://docs.handsontable.com/0.23.0/ColumnSorting.html#setSortingColumn).

**Comment by ranjan653** [comment]
hI @AMBudnik  at a time how many rows you can select to delete ? Here I am facing the problem that i have 99 rows I want to delete all but the remove row option is not coming.

**Comment by AMBudnik** [comment]
Hi @ranjan653 can you create a demo with the code?

**Comment by ranjan653** [comment]
Hi @AMBudnik , Please have a look into the example. It has ascending sorting,then descending sorting, then default sorting, then ascending ...so on..I want to remove default sorting

**Comment by AMBudnik** [comment]
Hi @ranjan653 you have asked me before and using only ascending and descending sorting (without default) is not available at the moment.

**Comment by vk-sourcefuse** [comment]
Hi @AMBudnik  , I also need same thing, is it somehow possible ?

**Comment by AMBudnik** [comment]
Hi @vk-sourcefuse 

using only ascending and descending sorting is not available at the moment. But you can force to sort the table when a user clicks a column header via [afterOnCellMouseDown ](https://handsontable.com/docs/6.1.0/Hooks.html#event:afterOnCellMouseDown)hook.

**Comment by vk-sourcefuse** [comment]
@AMBudnik , thanks for your help, but in this event how to know that what is next order, means ..
It first sort in ascending order,then descending, then default sorting, then ascending ...so on. 
I want to remove default sorting.
Means, It should be - **ascending** ,then **descending**, then **ascending**, then **descending** ....

afterOnCellMouseDown just tell us on which cell we clicked, how to know that when should we force to 'asc' after 'dsc', ? Should I get any cell-property to know previous order of that cell ?

I tried :
`beforeColumnSort: function (column, order){
            if(typeof order == "undefined") {
                objGridContainer.sort( column, 'asc' );
            }
        },`
That does work, but icon does not change to asc after desc .

**Comment by AMBudnik** [comment]
A little update here @vk-sourcefuse 

it is possible in you use the callback.

Here's a demo that I got from our developer https://jsfiddle.net/wojciech/pzn6bqj5

**Comment by vk-sourcefuse** [comment]
Thanks a lot @AMBudnik  , 

It worked with v6.1.0 , but I was using :
 * Version: 1.14.2
 * Release date: 13/09/2017 (built at 13/09/2017 11:34:49)

older version of handsontable was passing strings in beforeColumnSort as parameter, but this new version rocks ..

@AMBudnik  I want to upgrade from this version to latest (I've purchased PRO licence) , I want to know which things can break, and what all was changed after that version .
