### ISSUE TITLE
Dropdown with custom html

### ISSUE THREAD

**Issue by tnrich** [handsontable/handsontable#3272]
Hey there, I've got a button I'd like to put alongside one of my options in a handsontable dropdown field. Here's what the relevant code looks like:
```js
columns: [
{
  data: 'custom_vector',
  source: [
    '<button id="addCustomVector">+</button>Add custom vector', 'Custom Vector 2'
  ],
  type: 'dropdown',
}
]
```
This looks great the first time it renders: 
![image](https://cloud.githubusercontent.com/assets/2730609/13338437/46119024-dbd6-11e5-91e3-74646eb62974.png)

But unfortunately, when I click Option 2:
![image](https://cloud.githubusercontent.com/assets/2730609/13338450/568c462e-dbd6-11e5-8d2c-a70506524055.png)

And then go back to the dropdown, my html button no longer shows up correctly:
![image](https://cloud.githubusercontent.com/assets/2730609/13338471/6f9224ea-dbd6-11e5-9b87-5f0a09049011.png)

Other dropdowns still render the button correctly, but do the same thing if I make a selection with them.
![image](https://cloud.githubusercontent.com/assets/2730609/13338499/98a52d0a-dbd6-11e5-8552-f4c18964f583.png)

Has anyone else experienced this issue or have ideas for getting around it?

Thanks!
Thomas

**Comment by AMBudnik** [comment]
Hi @tnrich it looks interesting unfortunately we do not provide example nearly to what you would like to achieve here.

Did you tried a custom renderer? In this case you would need a autocompleteRenderer cause it's the same for an autocomplete and a dropdown so you can access it by `Handsontable.renderers.AutocompleteRenderer`
