### ISSUE TITLE
Handsontable Checkbox true/false firing on all the keys

### ISSUE THREAD

**Issue by vishumca** [handsontable/handsontable#3273]
Hi,

We are using checkboxs in our handsontable. However we found that the checkbox gets clicked on any keyboard key. This can also be seen from the example shown in handsontable documentation:
https://docs.handsontable.com/0.23.0/demo-checkbox.html#template

Is there a way we can restrict the checkbox check/uncheck event only on "SPACE" press and not on any key press.

**Comment by AMBudnik** [comment]
Hi @vishumca you can try to inject `if keycode is space` to [`beforeChange`](https://docs.handsontable.com/0.23.0/Hooks.html#event:beforeChange)
