### ISSUE TITLE
table width flickers when using stretchH+column-widths and then entering a value longer than the cell width

### ISSUE THREAD

**Issue by Sune1337** [handsontable/handsontable#3274]
I'm using stretchH: 'all' to make the table fill the container width.
I also use column-widths because i want one of the columns to be wider than the others.

Steps to reproduce: (see https://jsfiddle.net/qszoLgmk/2/for an example table)
1) Enter a value in any cell that is longer than the cell width.
    The value will wrap to multiple lines, and the table width is decreased about 30px or so.

To get the table to 100% again:
1) Enter a value in another cell that does not wrap into multiple lines.
    The table width is restored to 100%

2) Enter a value in another cell on the same line that does not wrap into more lines than the other cell
    The table width is restored to 100%
    If i enter a value on the same line that wraps to more lines than the first cell the table width remains decreased.

**Comment by AMBudnik** [comment]
Sorry I couldn't reproduce it. Could you share more strict steps like enter `long string text` value at `A1` cell and also you OS/Browser information?

Thanks in advance.

**Comment by Sune1337** [comment]
I am running Windows 10, and i have reproduced the problem in:
* Chrome 48.0.2564.116 m
* IE 11.103.10586.0
* Firefox 44.0.2

The screenshots are taken while using Chrome.

Exact steps to reproduce:
1) Make your browser width 1260 px wide (this is just what i happened to use atm)
2) Open https://jsfiddle.net/qszoLgmk/2/for
3) In cell A1, enter: I am a long string. So long that it is longer than the column width!
    (See screenshot http://i.imgur.com/QM09i4C.png)
4) Press enter
    (See screenshot http://i.imgur.com/JilDYu6.png)
5) The table should now have had it's width reduced about 30px.

**Comment by AMBudnik** [comment]
OK,
after I've entered more text the column is narrower than before - this was the case, right? Or there's someting more that I'm missing.

![1](https://cloud.githubusercontent.com/assets/10757813/13461986/473fa9d2-e085-11e5-976f-2a85c9a2e785.png)

**Comment by Sune1337** [comment]
Your screenshots describe the problem in a clear fashion. 
But i don't think the issue is that the cell became narrower. I think that is just a result of the entire table becoming narrower.

If you edit the column again, and then exit edit-mode you will notice that the table goes back to 100% width.

**Comment by AMBudnik** [comment]
Thanks for sharing additional information @Sune1337 
I got the same width changing behavior. After editing it the second time it looks as expected.

**Comment by AMBudnik** [comment]
Still occurs in 0.24.3

**Comment by AMBudnik** [comment]
The issue did not change in v `2.0.0` and it doesn't seem to be working in any of the previous versions of Handsontable.

**Comment by AMBudnik** [comment]
It works the same in v `7.4.2` https://jsfiddle.net/9ho6cu8y/
and `8.0.0-beta1`.

It looks like it always a `n + 2px` difference counting from the right.
![pixels](https://user-images.githubusercontent.com/10757813/77057512-5cda1200-69d4-11ea-96ac-027dd487fd60.png)

**Comment by AMBudnik** [comment]
Hi @Sune1337 

It's been a while, but it seems that the issue has finally been fixed. Please update to v15.0.0 if possible to benefit from the fix.
