### ISSUE TITLE
Horizontal scrollbar is displaying on cell edit  - Win7/Chrome Only

### ISSUE THREAD

**Issue by mpusarla** [handsontable/handsontable#3279]
Selecting any cell in the last column is enabling horizontal scrollbar. I configured the three column widths to be 100 each and the width of the container to be 350. By default horizontal scrollbar is not  visible. On select of any cell in the last column is enabling horizontal scrollbar.

Here is the jsFiddle:
http://jsfiddle.net/mpusarla/sk0xLLuh/

Thanks,
Madhu.

**Comment by AMBudnik** [comment]
Hi @mpusarla I'm not sure if I understand it correctly. You would like to get scroll when table is fully visible?

**Comment by mpusarla** [comment]
My question is, why is the horizontal scrollbar showing up when none of the columns are resized?

I configured the width of table to 350 and I have three columns 100 each. By default, when the table is initially rendered the horizontal scrollbar is not visible. When you select any cell in the last column, horizntal scrollbar shows up. I think it should not show up because I did not resize any of the columns.

**Comment by AMBudnik** [comment]
I do not have the same behavior. Can you share with me your OS/Browser information?

**Comment by mpusarla** [comment]
@AMBudnik Looks like it happens only in chrome. Firefox works good.
My chrome version is 45.0.2454.101 m. Just typing something in the last row and selecting any cell in the last column will trigger the horizontal scrollbar.

**Comment by AMBudnik** [comment]
Thanks for sharing details. It helped.
I was at the OSX and there's no browser to replicate that. When I moved to Windows 7 the Chrome 45 was the only one that couldn't handle the case properly.

**Comment by AMBudnik** [comment]
Still present in 0.24.3: http://jsfiddle.net/05gfz4za/

**Comment by AMBudnik** [comment]
Issue does not occur in version 0.31.0
demo: http://jsfiddle.net/handsoncode/Lx3yx8he/

thanks for sharing @mpusarla
