### ISSUE TITLE
Set width on rowHeaders 0.8.0-beta3

### ISSUE THREAD

**Issue by stevebooks** [handsontable/handsontable#328]
Using Vertical Scroll on 0.8.0-beta3 with row headers of various sizes. When scrolling vertically, the table is constantly resizing the width of the table.

It appears it is resizing based on the row headers that are visible. This works fine if the length of the text is gradually going up, however, if the data has various text lengths, it looks really choppy.

Is there a way to set a min-width of the row-header to avoid the resize?

Thanks!

**Comment by jansiegel** [comment]
If I'm not mistaken, it shouldn't be an issue anymore.
