### ISSUE TITLE
destroy can't remove contentmenu

### ISSUE THREAD

**Issue by shornikov** [handsontable/handsontable#3280]
second create handsontable obj show menu items twice

need $(".htContextMenu").remove()

**Comment by AMBudnik** [comment]
Hi,

to enable contextMenu on the instance where it was added just use:

[`instance.updateSetting({ contextMenu: false })'](http://jsfiddle.net/LqucLd29/)

If this was not helpful please create a demo and we'll try to figure it out.

**Comment by shornikov** [comment]
No :)
i use handsontable in modai dialog.
On modalShow -  create table with contextMenu, on ModalClose - destroy table.
If i open dialog again - items in contextMenu show twice, 3,4,5.

**Comment by AMBudnik** [comment]
Oh, ok. 

Could you share a demo code to portray this behavior?

**Comment by AMBudnik** [comment]
As there's no reply after more than 2 weeks I assume that you found a solution or a workaround but if I'm wrong - please comment below and I'll reopen this issue.
