### ISSUE TITLE
Comment not visible for the first row.

### ISSUE THREAD

**Issue by saishnakumar** [handsontable/handsontable#3282]
I have created a handsontable instance with the settings  rowHeaders: false,  colHeaders: false,
On mouse over on a  cell in first row  with comment  comment editor is not getting displayed.
It is working fine for all the other rows.

**Comment by AMBudnik** [comment]
Hi @saishnakumar 
We have the same issue at https://github.com/handsontable/handsontable/issues/3194
Please track changes to that one for further information.
