### ISSUE TITLE
row header height and row columns height alignment issue.

### ISSUE THREAD

**Issue by basrita** [handsontable/handsontable#3284]
Hi guys,

I am facing alignment issue when the row header is present.Here i am attaching the screenshot.
Even i am specifying height also same issue.the difference 1px is coming for me for any height.
![screenshot](https://cloud.githubusercontent.com/assets/7194256/13422479/14684c78-dfbb-11e5-9d34-f093c4fa1d4a.png)

Thanks.

**Comment by AMBudnik** [comment]
Hi @basrita 
I guess it is caused by this issue https://github.com/handsontable/handsontable/issues/2354. You can try to check workaround proposed at https://github.com/handsontable/handsontable/issues/2354 (last comment).
