### ISSUE TITLE
Copy-paste plugin, getting 10 times bigger values on paste

### ISSUE THREAD

**Issue by iliavolyova** [handsontable/handsontable#3285]
Hello.

We are using Handsontable 0.23. The issue comes up in numeric cells with the German ('de') locale (in which case the comma is used as a decimal splitter, and dot is used as a thousands splitter). 

If you take such a cell and type in a number with one digit after the decimal separator, eg 33,3 - when you try to copy and paste such a number with the keyboard, you get 333,00 on paste. 

This only happens when there is one digit after the comma. If you try with 33,33 it pastes correctly. This can be reproduced in the [official numeric demo](https://docs.handsontable.com/0.23.0/demo-numeric.html) Try putting 33,3 in the last column (where the euro prices are) and then copy-pasting it down into the next row using the keyboard.

**Comment by AMBudnik** [comment]
Hi @iliavolyova thanks for sharing
I think that it is the same issue as https://github.com/handsontable/handsontable/issues/3261 if not it is strongly connected.

If you could share any additional suggestions/investigation results there at https://github.com/handsontable/handsontable/issues/3261 I would be grateful.

**Comment by iliavolyova** [comment]
This is actually more similar to [#2166](https://github.com/handsontable/handsontable/issues/2166) which is referenced in [#3261](https://github.com/handsontable/handsontable/issues/3261). There's also hotfix there. Thanks!
