### ISSUE TITLE
RowHeader not updated on move

### ISSUE THREAD

**Issue by DHoffm** [handsontable/handsontable#3286]
When a row header is dragged (via manualRowMove setting) the header stays and only the row cells are updated.

I created a Fiddle: http://jsfiddle.net/n6gbsooo/

**Comment by AMBudnik** [comment]
Hi @DHoffm it is an option called [bindRowsWithHeaders](https://docs.handsontable.com/pro/1.2.0/Options.html#bindRowsWithHeaders) that you are looking for. 

It is available on Handsontable [PRO](https://handsontable.com/pricing.html?_ga=1.136076465.1270603665.1430732719). Please take a minute to check this demo where it is used: http://jsfiddle.net/guv3p72n/

**Comment by DHoffm** [comment]
That makes absolutely no sense! Why would I use the manualRowMove Setting without this.

**Comment by AMBudnik** [comment]
hi again @DHoffm 
most of our users are using `rowHeaders` as an indicator for rows that is why it is not included in regular version of Handsontable. 

`ColHeaders` are mostly used with custom names and that is why column headers are triggered with columns content (demo: http://jsfiddle.net/42w04nzq/) in regular version.

**Comment by DHoffm** [comment]
Sorry to hear that. So far everything worked great in the basic version accept this tiny bit. Not to sure about a 800$ purchase for this feature.

**Comment by AMBudnik** [comment]
If your project is based on subscription $799 it is (if not then $99). 

I'm aware that if there are no other PRO features that could come handy in your case that $799 could sound a bit too high but Handsontable PRO is more that `bindRowsWithHeaders` (nested headers, hiding rows/column, filters etc.)

**Comment by DHoffm** [comment]
Is there any chance to get that feature into the open source version?

**Comment by AMBudnik** [comment]
As it was added to PRO it will most likely stay PRO, but there's an option left. It's not fully developed yet but we will offer a marketplace for PRO features where you would have an ability to choose features that you're intersted in.

I do not have a precise date when it will be ready but you can sign to our notifier.

**Comment by DHoffm** [comment]
THX for your anwser. Where do i find the notifier.

**Comment by AMBudnik** [comment]
Just share your e-mail, first name and company name (if none leave blank) with form that's provided at https://handsontable.com/directory.html

**Comment by IntegerMan** [comment]
Thanks for the information on the pro features / marketplace. That's interesting. My organization is also evaluating your component. It's definitely hard to pull the trigger and justify a larger license for subscriptions without being able to test out the professional features. This is important as there are many little 'gotchas' that need to be discovered and worked around and we need to be responsible in our investments. Many companies offer development or trial versions of components for evaluation purposes with either a built in function that nags users to purchase or the component itself becomes unusable without a license (admittedly this is harder to do in JavaScript). Hopefully the marketplace can address some of these concerns and fears preventing others from buying a license.

**Comment by AMBudnik** [comment]
Hi @IntegerMan 
Using Handsontbale PRO on you test/dev enviroment is for free.
If you would like to test it before use just write to us at hello@handsontable.com
