### ISSUE TITLE
manualRowMove trigger doesn't resize with rowHeaderWidth applied

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3287]
Demo: http://jsfiddle.net/tx88mt0a/

Trigger used to move rows is not responding to changes made with `rowHeaderWidth`

Result (before dragging row)
![zrzut ekranu 2016-03-01 o 15 59 56](https://cloud.githubusercontent.com/assets/10757813/13430865/228d3c08-dfc7-11e5-9a6d-8cd1cc082353.png)

![zrzut ekranu 2016-03-01 o 16 04 00](https://cloud.githubusercontent.com/assets/10757813/13430896/5b224130-dfc7-11e5-8b1f-be8ac742668d.png)

**Comment by DHoffm** [comment]
I tried the following: http://jsfiddle.net/jrtsepwj/ which didn't work. I thought the afterRender event is the right point to manipulate the width of the resizer...but somehow its not.

**Comment by jansiegel** [comment]
Analogous changes for the columns were made in #3480.
