### ISSUE TITLE
Is there a calculation engine without the grid UI?

### ISSUE THREAD

**Issue by sandzone** [handsontable/handsontable#3289]
I am working on a project that needs an excel like calculation engine in the browser. But, it doesn't need the grid UI. 

Currently, I am hiding the div element (style="visibility:hidden") of Handsontable and pulling the computed values using the hack at [#2645](https://github.com/handsontable/handsontable/issues/2645)

Is there a calculation engine only component in Handsontable? I guess rulejs works for parsing excel formulae and computing the value of a single cell. What I am looking for is the entire calculation engine that evaluates the inter-dependencies and gives me the matrix of computed values.

Something like this:
x = [ [1, 2, "=A1+B1"],
        [2, "=SUM(A1,A2"),3] ];

y = CalculateJS(x);
##############
y: [[1, 2, 3], 
     [2,3,3]]

**Comment by AMBudnik** [comment]
Hi @sandzone 
Unfortunately formulas are currently in beta mode and we do not provide the requestet feature.

**Comment by sandzone** [comment]
I managed to do this using bacon.js. It accounts for cell interdependencies. As of now, it calculates values for javascript formula instead of excel formula by using an eval function. To make it work for excel formulae, all one has to do is replace eval with Handsontable's ruleJS library. I couldn't find a URI for that library... hence eval.

https://jsfiddle.net/sandeep_muthangi/3src81n3/56/

**Comment by AMBudnik** [comment]
Thanks for sharing and provided feedback @sandzone
