### ISSUE TITLE
Loader during pasting

### ISSUE THREAD

**Issue by brivazac** [handsontable/handsontable#329]
Is it possible to add a loader during the pasting time ? 
I did a test with 2000 rows and 4 columns, and it took 3 minutes to come on the screen. 

So i think animated loader is necessary for people who will use it this feature but don't know it well.

**Comment by AMBudnik** [comment]
Please update to 0.13.1 and check if this issue still occurs. 

When I use [this demo](http://handsontable.com/demo/scroll_window.html) and select columns A:D (there are exacly 4008 cells) and paste them in E column it takes like 2-3s.

If you would have the same inssue, please reply and we'll reopen this issue.
