### ISSUE TITLE
afterSelectionEnd not work with dropdown

### ISSUE THREAD

**Issue by fgalvan19** [handsontable/handsontable#3291]
I've four columns, the last two are dropdowns. When I change the row in the last dropdown (I changed the code, when Enter key is pressed, it moves to the next column, if it is in the last column, it moves to next row), I try to fetch row data with getDataAtRow, but the last value don't appear in this event.
I need this to do an insert in my db, but the last value is null (nullable=false in my db).

**Comment by AMBudnik** [comment]
Hi @fgalvan19 can you create a demo where we can interact with this issue?

**Comment by fgalvan19** [comment]
This is the demo http://jsfiddle.net/Lsev6kjq/10/

**Comment by AMBudnik** [comment]
Hi @fgalvan19 thank for sharing demo. It looks pretty complex so I made a simple demo with dropdowns where `afterSelectionEnd` triggers console to print `selectionEnd` value. It works with for cells so I guess the problem lays somewhere else. demo: http://jsfiddle.net/u1tgk1nn/

You could try to comment line by line and check if something is changing in this matter.

**Comment by AMBudnik** [comment]
I assume that issue got solved by now but If it's not please leave a comment and I'll reopen the topic.
