### ISSUE TITLE
Programmatically blur selected column

### ISSUE THREAD

**Issue by samdenicola** [handsontable/handsontable#3292]
Hi there,

We have added two clickable buttons to the header of a handsontable column which trigger both the opening of a modal, and the switching of a page. This is done with an event listener of clicks on the two specific classnames. 

The issue is that in clicking on either of these buttons, the handsontable column becomes selected. Thus the user can "enter" content into the first row of the selected handsontable column while he/she is visually seeing a modal or new page. We haven't been able to figure out how to either a) disable that selection, or b) programmatically unselect the column. 

Here is a screenshot of the column header with buttons:
<img width="468" alt="screen shot 2016-03-03 at 12 57 29 pm" src="https://cloud.githubusercontent.com/assets/13247167/13509297/924af250-e13f-11e5-8f3e-9ff7cd5157f4.png">

Here is the code with our attempts at solving the problem: 
```js
Handsontable.Dom.addEvent(container, 'click', function (event) {
  /*Things we have tried*/
    document.getElementById('basePairTotal').click()
    document.elementFromPoint(100, 100).click();
    document.activeElement.blur();
    $(':focus').blur()
    var e = $.Event("keyup"); // or keypress/keydown
    e.keyCode = 27; // for Esc
    $(document).trigger(e);
  /*-----------------*/
  if (event.target.className == 'seeMapLink') {
    handleOpen()
  }    
  if (event.target.className == 'hint--left handsonAddCustomButton') {
    changePage(pages.AddCustomVectorsPage);
  }
});
```

Thanks for the help!

**Comment by AMBudnik** [comment]
Hi @samdenicola it's not currently available. Actually this feature is at our feature request list at : https://github.com/handsontable/handsontable/wiki/Feature-requests

**Comment by samdenicola** [comment]
We were actually able to resolve this issue by using the deselectCell method of HOT:

```js
  Handsontable.Dom.addEvent(container, 'mousedown', function (event) {

    if (event.target.className == 'seeMapLink') {
      AppSingletons.Hot.deselectCell()
      handleOpen()
    }    
    if (event.target.className == 'hint--left handsonAddCustomButton') {
      AppSingletons.Hot.deselectCell()
      changePage(pages.AddCustomVectorsPage);
    }

  });
```
