### ISSUE TITLE
validateCells() should optionally ignore the spare rows

### ISSUE THREAD

**Issue by tarehart** [handsontable/handsontable#3293]
Hello,

I have my table configured with `minSpareRows`, and a column validator which fails on blank cells (i.e. a required column).

When I call `validateCells()`, my spare rows have that column flagged as invalid. I would prefer that my spare rows be excluded from validation.

http://jsfiddle.net/s3L8hm3b/2/

**Comment by AMBudnik** [comment]
Hi @tarehart 
There's not a streight solution for this one but please take a minute to check my demo: http://jsfiddle.net/s3L8hm3b/5/ 

`MinSpareRows` gives cells a `null` value so if you will fill the new created row with an empty string you could compose your validation condition as:
`value === null || value !== ""`
so after a cell is added (trough a contextMenu) it would not past the validation but your `null` value `minSpareRows` will. 

I'm not sure if it is a best solution but surely easy to manage.

**Comment by tarehart** [comment]
Hi @AMBudnik 

Thanks for making the demo. Unfortunately it doesn't seem to solve the problem. If I click validate immediately after loading the fiddle, row 2 column 1 is marked invalid. If I fill in that cell, row 7 column 1 is marked invalid. If I type in row 3, column 2 and click validate, row 3 column 1 should be marked invalid but it is not.

My current workaround is to not bother with validateCells, and instead rely on a hook like this:

```
Handsontable.hooks.add('afterRender', function() {
    setTimeout(function() {
        self.isValid = !$(".htInvalid").length;
    });
}, hot);
```

Hopefully you consider .htInvalid to be part of your documented API so I can rely on it in future versions.

Thanks!

**Comment by AMBudnik** [comment]
Indeed when we fill the table another spare rows are marked as invalid.

**Comment by AMBudnik** [comment]
I will add this idea as an improvement suggestion.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by dehim** [comment]
Insert into handsontable.full.js below and the problem could be solved
![image](https://cloud.githubusercontent.com/assets/9805228/15982584/de3b1dee-2fbd-11e6-8ac8-4fcff40dddc6.png)

**Comment by AMBudnik** [comment]
thanks for share your proposition @dehim

**Comment by kvadd** [comment]
I did an update on the solution provided by @dehim 

![code_2016-06-23_15-50-59](https://cloud.githubusercontent.com/assets/1159479/16305526/84fd7460-395a-11e6-8695-38df20de73ad.png)

This way it only checks the last row, and still validates empty rows in the middle of the table. This only works if you have 1 minSpareRows though.

**Comment by deviloflaplace** [comment]
Hi,
It's interesting that this is still a problem as of Feb 2017. The issue stems from validateChanges method doing validation **before** applying changes. Hence any check at isEmptyRow() returns false.

So I got the row index from changes array, get data, check each cell manually as well as change to determine is row is empty. 

Just a quick hack to make it work for us. If anyone's interested, I'd be happy to do a pull request.

<img width="811" alt="screen shot 2017-02-12 at 20 26 08" src="https://cloud.githubusercontent.com/assets/2039519/22870974/8a805eec-f161-11e6-9ae6-e4e4f12762b9.png">

**Comment by AMBudnik** [comment]
Hi @deviloflaplace feel free to create a pull request but please remember that we accept only PR made on develop branch with tests and demo example on how to replicate the situation they are fixing.

**Comment by HDaghash** [comment]
Hey guys 
any update on this ?

**Comment by AMBudnik** [comment]
@HDaghash we will be checking the way that spare rows and fixed rows are treated. In our plans, they are not considered as a part of the dataset. Here's a Trello card for it https://trello.com/c/elpfSXXr/64-improvement%3A-fixed-bottom-rows

**Comment by HDaghash** [comment]
@AMBudnik Thanks for the fast response 

anyway i'm using custom validation now , and i'm setting the non valid rows using some custom functions .

Thanks !

**Comment by Gaardsholt** [comment]
A workaround could be doing like this
`afterValidate: function (isValid, value, row, prop, source) {
	if (row == hot.countRows() - hot.getSettings().minSpareRows)
		return true;
}`

**Comment by dkwebtec** [comment]
fix of Gaardsholt's workaround

 ```js
 afterValidate: function (isValid, value, row, prop, source) {
 	if (row >= hot.countRows() - hot.getSettings().minSpareRows)
 		return true;
 }
 ```

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. 
Please free to continue the conversation there. Thank you.
