### ISSUE TITLE
Handsontable gets refreshed the entire column except the editing cell after edit

### ISSUE THREAD

**Issue by sambsa** [handsontable/handsontable#3294]
I have a Handsontable as follows:
I have a `Handsontable` as follows:

    ordertable = new Handsontable(container, {
        data: data,
        colHeaders: ['Customer', 'Mode', 'Remarks', 'Due', 'Recieved'],
        columns: [{
            data: 2,
            readOnly: true
        }, {
            data: 6,
            type: 'autocomplete',
            source: collectionmethod,
            validator: collectionmethod_validations,
            strict: true
        }, {
            data: 5,
            readOnly: false
        }, {
            data: 4,
            readOnly: true,
            type: 'numeric',
            format: '0.00'
        }, {
            data: 3,
            type: 'numeric',
            format: '0.00',
            validator: amt_validations,
            allowInvalid: true
        }],
        minSpareRows: 0,
        rowHeaders: true,
        contextMenu: ['row_above', 'row_below', 'remove_row', 'undo', 'redo'],
        colWidths: [150, 100, rest, 100, 100],
        autoWrapRow: true,
        autoWrapCol: true,
        beforeRemoveRow: removerow_validation
    
    });

I have a checkbox. And when I click checkbox the value of `Due`(4th column) should be populated to the 'Recieved'(column). If I uncheck it then the `Received` should be blank which is same as table onload.

What I do is as follows:

    $("#sel_prefill").click(function() {
        if ($("#sel_prefill:checked").val()) {
            var g = $('.htCore').find('tbody tr td:nth-child(5)'); //Due
            var f = $('.htCore').find('tbody tr td:nth-child(6)') // Recieved
            g.each(function(i, v) {
                f.eq(i).text(g.eq(i).text());
                $(v).css({
                    'text-align': 'right'
                });
            });
        } else {
            var g = $('.htCore').find('tbody tr td:nth-child(5)'); //Due
            var f = $('.htCore').find('tbody tr td:nth-child(6)') // Recieved
            g.each(function(i, v) {
                f.eq(i).text("");
                //$container.handsontable('setDataAtCell', 1, 4, 5);
                $(v).css({
                    'text-align': 'right'
                });
            });
        }
    });

It is working fine.

But the problem is that  after checking checbox the value the value of 4the column is populated to 5th. But `if I edit any cell from 5th column, then the entire column except editted cell gets refreshed and 5th column becomes blank.`.

How can I avoid it.

Please refer the pics for step by step details:

![1](https://cloud.githubusercontent.com/assets/4330791/13519328/adc756fa-e1fc-11e5-8fc7-a79374d40b44.png)
![2](https://cloud.githubusercontent.com/assets/4330791/13519329/af2a5830-e1fc-11e5-8f89-5e83962f9bd3.png)
![3](https://cloud.githubusercontent.com/assets/4330791/13519332/b2c0149e-e1fc-11e5-9608-010972cabd07.png)

How can I avoid refresh the cells after editing?

**Comment by sambsa** [comment]
I tried using `$('#tableorder').handsontable('setDataAtCell', 0, 3, 'new value'); ` for checking. But setDataAtCell  method itself is not working at all.

**Comment by AMBudnik** [comment]
Hi @sambsa Could you create a demo where we can interact with this issue? I would appreciate.

**Comment by sambsa** [comment]
please refer the fiddle http://jsfiddle.net/hU6Kz/4864/. You can check using this fiddle

**Comment by sambsa** [comment]
Problem solved. The main data array need to be updated while I am assigning value of one row to another.

`g.each(function(i, v) {
            f.eq(i).text(g.eq(i).text());
             data[i][3] = g.eq(i).text(); //Need to add the changes to the data array
            });`

**Comment by AMBudnik** [comment]
great to hear that everything's working as expected @sambsa 
I'm closing this issue.

**Comment by sambsa** [comment]
ok buddy, cheers!!


Thanks&Regards
Santhosh Samban

On Thu, Mar 10, 2016 at 2:02 PM, Aleksandra Budnik <notifications@github.com
