### ISSUE TITLE
manual column freeze is not working when manual column move is set true.

### ISSUE THREAD

**Issue by basrita** [handsontable/handsontable#3295]
Hi guys,
When manual column move is enabled,manual column freeze is freezing the particular column,It's freezing left most unfreezed column.

Please help me in this regards.

Thanks,
Asrita

**Comment by AMBudnik** [comment]
Hi @basrita 
I couln't reproduce this behavior. I made a demo: http://jsfiddle.net/g4ftwqkg/2/ with those two settings and did:

1. Freezed `D` column
2. Got `D` freezed - as expected
3. Freezed `G` column
4. Got `D` and `G` columns freezed - as expected

Could you check this one again and guide me how to reproduce this behavior?

Thanks in advance!

**Comment by basrita** [comment]
Hi @AMBudnik 
I think problem with handsontable version i guess.currently i am using handsontable pro.I don't know whether the problem is with pro or not.

**Comment by AMBudnik** [comment]
Hi @basrita 
I updated the example to use Handsontable PRO
http://jsfiddle.net/g4ftwqkg/3/ and the result is the same
Should I add any other settings?

**Comment by basrita** [comment]
Hi @AMBudnik 

Thanks for response.when i am using the js file which you referenced in above example it is working but with my js file it is not working,

Thanks.

**Comment by AMBudnik** [comment]
@basrita you should check other settings and comment them line by line - maybe there are some influences between them.

Maybe some other script are injected to Handsontable?

**Comment by basrita** [comment]
ok thanks @AMBudnik .

**Comment by kashesandr** [comment]
Hey! 
I forked the jsfiddle above and replaced version to `0.34.5`
So, there is a bug in 0.34.5 - the columns freezing doesn't work with `{ manualColumMove: true, manualColumnFreeze: true }`
http://jsfiddle.net/kashesandr/ngzj83ea/
Any ideas how to fix?

**Comment by AMBudnik** [comment]
Hi @kashesandr 

Did you use the same scenario as in my 1 post?

The scenario was tested on the 0.34.5 version.
