### ISSUE TITLE
npm install handsontable >>> 404 error

### ISSUE THREAD

**Issue by supersteves** [handsontable/handsontable#3298]
https://www.npmjs.com/package/handsontable

it says:

```npm install handsontable```

but
```
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/handsoncode
npm ERR! 404
npm ERR! 404  'handsoncode' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

also if fixed it needs something in the readme

**Comment by budnix** [comment]
Hi @supersteves, Handsontable is already registered in npm registry. Currently it is only registered without browserify support (https://github.com/handsontable/handsontable/issues/2980) but this should be done in the next release (probably 0.25.0).
