### ISSUE TITLE
Min width and height

### ISSUE THREAD

**Issue by DHoffm** [handsontable/handsontable#3301]
Hi is there an option for the minimum column width and the minimum row height?

**Comment by AMBudnik** [comment]
Hi @DHoffm you can use `rowHeights` to add minimum and default width for rows http://jsfiddle.net/bn3x5L0d/

As you can check `manualRowResize` isn't able to shrink row height to narrower than the value implemented with `rowHeights`

**Comment by DHoffm** [comment]
But in your example I can still resize the columns to a smaller value by using the handle.

**Comment by AMBudnik** [comment]
You're right.

If we're fixing minimum height of a row with `rowHeights` we should also get fixed minimum width of a column with `colWidths` (or just add separate option to both to disable shinking). 

These two options should have the same privileges.

**Comment by DHoffm** [comment]
So this might get added in the future? Is there a css fix for this, via min-width/min-height?

**Comment by AMBudnik** [comment]
I'll open a disscusion about his subject at Friday with our programming team.

When it comes to a workaround I was trying to update `colWidths` via `updateSettings` using `afterColumnResize` (demo: http://jsfiddle.net/bn3x5L0d/2/) but it does not correspond to changed column.

Please stay tuned to this issue for updates

**Comment by jansiegel** [comment]
@DHoffm, @AMBudnik That's true, this behaviour should be consistent in `colWidths` and `rowHeights`.

Until they are, the workaround for this can be using the `modifyColWidth` hook, checking if the manually changed column width is more narrow the the width in the settings. 
I've modified the jsfiddle with an example implementation: http://jsfiddle.net/js_ziggle/xxa8an7h/

**Comment by DHoffm** [comment]
Hi, thank you for the fiddle. How would I utilize this in the angular directive?

**Comment by DHoffm** [comment]
Nevermind...found it myself. Via:

<hot-table settings="{modifyColWidth:modifyColWidth}"></hot-table>

**Comment by jbrunette** [comment]
Ran into #3301 and found this.  Are rowHeights and colWidths intended to be treated as minimums?  The documentation doesn't suggest that.

I'd expect there would be companion minRowHeights/minColWidths options or something similar, to allow the developer the option of specifying minimums if desired.

If I wanted to set heights for certain rows upon instantiation but allow the user to adjust the row heights to any value afterword, how would I do that?

**Comment by AMBudnik** [comment]
Hi @jbrunette 
if you'd use `colWidths` with `rowHights`, like in this example: http://jsfiddle.net/fdnuakw8/
the table is set with defined row heights but with gaining more content it stretches to show all of it.

**Comment by lil25** [comment]
I've got the same situation, I need initialize table with some initial row height and allow user to decrease it manually, is it possible to achieve?

**Comment by lil25** [comment]
if it helps for someone, i created the hook for this

`afterRowResize: function(currentRow, newSize) {
						rowHeights[currentRow] = Math.max(minRowHeight, newSize);
						handsontableElement.updateSettings({
							rowHeights: rowHeights
						});
}`

**Comment by AMBudnik** [comment]
I'm moving all the feature requests to our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests). Please feel free to leave any additional comments and reflections.

Thanks in advance!

**Comment by AMBudnik** [comment]
Hey,

we've added an option in Handsontable 7.0.0 that can interest you https://github.com/handsontable/handsontable/issues/5749 
From now on we support a container with relative dimensions (%, vh, vw, rem, em)

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
