### ISSUE TITLE
Removing fixed columns makes part of the table unclickable.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3302]
After removing the fixed columns from the table, the space where they used to be doesn't shrink, which makes the _main_ part of the table unreachable.
This happens only when row headers are not enabled.

---
#### Steps to reproduce:
- Go to http://jsfiddle.net/js_ziggle/k06a2nb3/
- Click the button
- Try to select any cell in the first or second column

**Result:** The previously-fixed columns are non-selectable.

**Comment by AMBudnik** [comment]
Still present in 0.27.0

**Comment by AMBudnik** [comment]
@jansiegel 
I wasn't able to replicate with 0.30.1. Can you check that please?

**Comment by AMBudnik** [comment]
The issue is nt replicable in v0.35.0.
Updated demo http://jsfiddle.net/gnqnpkw9/
