### ISSUE TITLE
Handsontable validation issue.

### ISSUE THREAD

**Issue by chandujha** [handsontable/handsontable#3303]
Hi I'm using the below function to validate, after validation i'm calling that function to store the excle data in db. I have 27 coloumns and it is in db its gettinng inserted by 26 times. please look in to this below code.

        $('#HSTable').handsontable('validateCells', function (isPass) {
            if (isPass) {

                SaveData();
                alert("Saving data");
            }
            else {
                alert("Please enter the data in correctformat");
            }
        });
        $('#HSTable').handsontable('render');
    });

    })

**Comment by AMBudnik** [comment]
Please stick to https://github.com/handsontable/handsontable/issues/3307
