### ISSUE TITLE
How to Enable Formulas in Handsontable Pro

### ISSUE THREAD

**Issue by finmt** [handsontable/handsontable#3304]
How do you enable formulas in Handsontable Pro with ngHandsontable?

I included the "handsontable.full.js" and set: "formulas: true" in the grid settings... but formulas aren't evaluated when I enter them in grid cells.

Is there any other dependencies I need to include?

**Comment by AMBudnik** [comment]
Hi @finmt I see that you would like to have all-in-one here which I surely understand.

What's the case? Formulas are still in beta mode (they are on our Roadmap for Q4). Currently we're working on providing support of PRO features using Angular version of Handsontable and it should be ready soon - I guess the best way here is to stay tuned with our release notes.

**Comment by xfight0** [comment]
In ngHandsontable ,I used these js file, but  formula feature doen't woking
```
ruleJS.all.full.min.js
handsontable.formula.js 
```

**Comment by AMBudnik** [comment]
Hi @xfight0 
I'm back with good news. Our Roadmap was changed and we're starting to work on formulas. 
I'm aware that it's a huge project but hopefully it'll be ready in May.

When it comes to formula issue I saw that you made a separate topic at https://github.com/handsontable/handsontable/issues/3335 so I'll reply there.
