### ISSUE TITLE
HOT does more rendering after the "afterRender" event fires

### ISSUE THREAD

**Issue by gstanislav** [handsontable/handsontable#3306]
Docs for `afterRender` hook state that it is "fired after the Handsontable table is rendered". However, after this hook the `alignOverlaysWithTrimmingContainer` function is called, which performs more rendering stuff. Styles are overriden and cleared, `scrollTop` of overlays is modified, etc.

I see 2 issues:
1. `afterRender` hook name is misleading: more rendering is being done afterwards. 
2. There is no way to hook into HOT lifecycle after `alignOverlaysWithTrimmingContainer` fires.

**Comment by budnix** [comment]
Hi @gstanislav, I think that you are right. `afterRender` hook should fire like its name says after table renders (after all calculations applied to the DOM). I marking this issue as a bug.
