### ISSUE TITLE
Handsontable validation issue.

### ISSUE THREAD

**Issue by chandujha** [handsontable/handsontable#3307]
Hi, i'm having 27 column and i need to validate later i need to save. I have written the below code.

but issue is that it is iterating 27-1 time, so if give alert msg to its taking 26 time. here is the below code.

  $('button[name=validate]').on('click', function () {
            $('#example1').handsontable('validateCells', function (isPass) {
                debugger;
                if (isPass) {

                    //SaveData();
                    alert("Saving data");
                }
                else {
                    alert("Please enter the data in correctformat");
                }
            });
            $('#example1').handsontable('render');
        });

**Comment by AMBudnik** [comment]
Hi @chandujha Please create a demo using JSFiddle/JSBin or CodePen it would be much easier to understand the goal and find a way to achieve it.

**Comment by chandujha** [comment]
https://jsfiddle.net/chandan_jha/k3gg839k/

please find the link, please some one help me on this issue

**Comment by AMBudnik** [comment]
@chandujha could you provide steps how to manage the demo? (what should I download as there's no grid at the beginning) I've updated the demo https://jsfiddle.net/k3gg839k/3/ (jQuery was missing)

**Comment by AMBudnik** [comment]
I'm also closing https://github.com/handsontable/handsontable/issues/3303 as it refers to the same case.

**Comment by chandujha** [comment]
i'm using it through MVC, so some of the code was working through MVC. i will post you soon

**Comment by AMBudnik** [comment]
alright @chandujha take your time

**Comment by AMBudnik** [comment]
Hi @chandujha how is progress?

**Comment by chandujha** [comment]
I ll share u 2day that.. As now I implemented manual process

-----Original Message-----

**Comment by AMBudnik** [comment]
Great, thanks.

**Comment by AMBudnik** [comment]
Hi @chandujha I'm closing this issue in lack of reply but if you're working on it just let me know.

**Comment by chandujha** [comment]
You can close this issue.. We had planned to use handsone table in our
application. But due to that issue.. We had achived with. Net tool only.
