### ISSUE TITLE
Scrolling with huge data

### ISSUE THREAD

**Issue by mainstream95** [handsontable/handsontable#3309]
Why the more scrolling the worse it work, with more data.

for example at area of 0-30k  all is ok, but after 50 k it get worse and worse to edit and scrolling too.

http://jsfiddle.net/co9tscsk/

it mean that i can't use table with 500k data? i just saw this post and cant understand how
https://groups.google.com/forum/#!topic/handsontable/c0nUX4ckrSA

**Comment by AMBudnik** [comment]
Thanks for sharing demo and the details @mainstream95

**Comment by AMBudnik** [comment]
It is possible to load more than 500k rows. In this example http://jsfiddle.net/handsoncode/g4ftwqkg/6/ we have 1kk rows it does not work smoothly but you can edit or save data.

**Comment by mainstream95** [comment]
Ok)i hope this issue will be solved soon

**Comment by krzysztofspilka** [comment]
@mainstream95 could you please share the details on your system, namely a browser ver., OS and the machine details (RAM, processor)? By the way, in your demo you have 8.5 mln cells so the object itself is huge enough to slow things down as Handsontable doesn't cache source data.

**Comment by mainstream95** [comment]
Chrome Version 49.0.2623.87 m
OS Windows 7.

Ram 4GB

Core i3 M 380 2.53 GHz

maybe.but as i say virtual rendering first 20 k and virtual rendering last 20k is very different.last is slow. If i could understand why, maybe its help me about some optimizations

**Comment by nickleach** [comment]
Any status on this? Trying to load over 200k records

**Comment by AMBudnik** [comment]
Hi @nickleach 

have you considered using server-side pagination? If you are not using filters it would be the best pick.

**Comment by AMBudnik** [comment]
The issue is no longer replicable. We can change the value of a cell with the same speed in any part of the table.  

![gif](https://user-images.githubusercontent.com/10757813/35222596-b90410ac-ff7e-11e7-938f-7c19abd3bdb7.gif)
(Used Chrome 63 on Windows 10)
