### ISSUE TITLE
Format column header with data object field?

### ISSUE THREAD

**Issue by darkguy2008** [handsontable/handsontable#3310]
Hello, I'm trying to evaluate HOT in order to buy a license but I'm having some issues with the nested headers plugin:

I have a dynamic sequence of columns I need to add, which come in a "yearly" basis data type. I need to make some columns children of a nested header which needs to display the current year of the data underneath.

For instance, something like this:
```
|      As of 2012/05/12       |
| col1 | col2 | col3 |  col4  |
```
Where 2012/05/12 is a field in my object, `myobject.asOfYear` or something like that. I know there are renderers for columns (which end up changing the value instead of the column text which makes no sense) but I have not seen anything for the nested headers.

Any assistance is greatly appreciated!

**Comment by AMBudnik** [comment]
Hi @darkguy2008 if you could share a demo with your recent progress I'd be happy to help. It would bring me more light on your goal.

**Comment by AMBudnik** [comment]
Hi @darkguy2008 is there currently anything I can help you with?
