### ISSUE TITLE
HOT breaking scroll when resizing fixed columns

### ISSUE THREAD

**Issue by PredatoryPlatanus** [handsontable/handsontable#3311]
Using manual column resize and fixed columns is buggy: when enlarging fixed column in a way so total fixed columns width is bigger than container (i.e. allowed space on screen) it will break scrolling and you wouldn't be able to scroll past fixed columns.
Also setting this width on load also breaks scroll.

[jsFiddle](http://jsfiddle.net/21vuwpkk/)
[webm demo](http://webmshare.com/44x3B)

**Comment by AMBudnik** [comment]
Thanks for sharing @PredatoryPlatanus 
Indeed it flickers and does not display anything after scrolling (OSX) when fixed column are wider than the window.

**Comment by AMBudnik** [comment]
Hi @PredatoryPlatanus 
Can you test the newest 0.27.0 version with this issue?
I think that now it works as expected. Here's an updated demo: http://jsfiddle.net/t2bjt3en/

**Comment by AMBudnik** [comment]
I’m sure that at this point, if anybody really had any objections or major concerns with this approach, they would have spoken by now.
