### ISSUE TITLE
Is it possible to change the default datepicker to a bootstrap datepicker?

### ISSUE THREAD

**Issue by samsonkhisty** [handsontable/handsontable#3314]
I use bootstrap datepicker in my app and would like to keep it consistent.

Thanks in advance.

**Comment by AMBudnik** [comment]
Hi @samsonkhisty 
I guess we've never tried but I can't see that happening without actually changing the code.

**Comment by samsonkhisty** [comment]
Hi @AMBudnik, 
Thanks for quick reply. I am currently looking into the possibility to extend DateEditor and replace pickaday with bootstrap and see how it goes.

**Comment by AMBudnik** [comment]
I have to say that it's an interesting case. 
I would appreciate if you could share your investigation results. 
Keep my fingers crossed for progress.

**Comment by samsonkhisty** [comment]
@AMBudnik  Yup! :)

![bs datepicker](https://cloud.githubusercontent.com/assets/3254606/13688819/4dffe8cc-e6f2-11e5-81af-22be1525364f.gif)

I've a small bug yet to figure out maybe  you can shed some light. In the pikaday, if one datepicker is open and you click of the dropdown arrow of another date, the behaviour is such that it closes the datepicker that was open. This isn't the case in the bootstrap,  when I try to perform the same. When I click on the dropdownarrow of another cell, I shows the datepicker for the new cell for a brief second before hiding it back again. I notice that in the earlier case, the instance.acArrowListener isn't hit while in my bootstrap implementation it hits arrowListener the second time so it shows the datepicker but then its hides again due to refreshBorders.

**Comment by samsonkhisty** [comment]
attaching gif of the bug

![bug](https://cloud.githubusercontent.com/assets/3254606/13689208/5861227e-e6f5-11e5-98d1-d71e66ee0dc3.gif)

**Comment by AMBudnik** [comment]
Presents great with Bootstrap!

When it comes to the second case it looks like a bug. I'll mark this one for our programmers to look at.

**Comment by samsonkhisty** [comment]
hi @AMBudnik 

Here's my code for bootstrap datepicker. I hope it helps the programmer to replicate the issue.

https://gist.github.com/samsonkhisty/5ce9750a1f5c268a7d09

Thanks again.
