### ISSUE TITLE
manual resize row height problem

### ISSUE THREAD

**Issue by ds009** [handsontable/handsontable#3316]
When rowHeights are given, I can't decrease rowheights( by handles on rowheaders) to a value less than initial value. I think it's caused by these:

at row 16197, in function **onModifyRowHeight**,in the file** handsontable.full.js**
`if (manualRowHeight !== void 0 && (manualRowHeight === autoRowHeightResult || manualRowHeight > (height || 0))) {
        return manualRowHeight;
      }`

**Comment by AMBudnik** [comment]
Hi @ds009 am I thinking correctly that this is the same issue as described in https://github.com/handsontable/handsontable/issues/3301?

**Comment by krzysztofspilka** [comment]
@ds009 the minimum row height is 23px. To which value is the height decreased in your case?

**Comment by ds009** [comment]
@AMBudnik Thanks, I didn't see that issue.
