### ISSUE TITLE
Alignment disables undo functionality

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3319]
When I do some changes in the dataset and then change the alignment from the context menu then it's impossible to revert the changes using `ctrl+z`.

http://jsfiddle.net/328cooz7/
## 

Handsontable v. 0.24.0
Windows 8.1
Chrome (latest)

**Comment by krzysztofspilka** [comment]
It's even worse. Steps to reproduce the problem:

1. Head to http://jsfiddle.net/328cooz7/
2. Set a different alignment for the first column
3. Press `ctrl+z` (nothings happens)
4. Now make any change, for example select all the cells and press `ctrl+z` - it doesn't work anymore

**Comment by AMBudnik** [comment]
Still replicable in 1.9.1/0.30.1, demo: http://jsfiddle.net/handsoncode/fy6kbszx/

**Comment by AMBudnik** [comment]
The issue is still replicable in v0.35.0
It has to be related to context menu as when we enable it the undo works fine 
Updated example http://jsfiddle.net/7jo5vtrk/ (uncomment the `contextMenu: true` to make it work as expected)

**Comment by krzysztofspilka** [comment]
@pnowak looks good to me
