### ISSUE TITLE
Last row wrapping with Date column

### ISSUE THREAD

**Issue by jrowen** [handsontable/handsontable#3320]
See the first table at http://jrowen.github.io/rhandsontable/.  You'll notice that the last row height is larger than the rest, and this only occurs when a Date column (with date picker) occurs in the table.  This is a difficult issue to reproduce outside of this situation, so I'm looking for some guidance.  Thanks.

**Comment by AMBudnik** [comment]
Hi @jrowen 
please take a minute to check this demo: http://jsfiddle.net/handsoncode/b9f4evx0/
It's hard to say anything if you didn't provide us code that is used to build the instance.Could you try to replicate the same issue with provided demo?

**Comment by jrowen** [comment]
I think I was able to put together a demo: http://jsfiddle.net/jrowen/b9f4evx0/2/.  The issue appears to be related to the font settings.

**Comment by AMBudnik** [comment]
Yes, it's the font.
Thanks for sharing additional info @jrowen 

I'm marking this issue as a bug.

**Comment by budnix** [comment]
Hi @jrowen, increasing `sampleRatio` to `10` is a solution, see [demo](http://jsfiddle.net/b9f4evx0/4/). This occurs because `AutoColumnSize` plugin tries to calculate width not for all rows but for rows where cell data has different length. Plugin collects by default 3 samples of cells value of the same length. In the demo you use font which has different width for every alphanumeric symbol so in this case plugin should calculate almost every row so that's why I increased `sampleRatio` property.

Increasing `sampleRatio` has a negative impact on performance.

**Comment by jrowen** [comment]
Thanks for the solution. In this case, it seems the simpler solution will be to switch to a more appropriate font.

**Comment by jrowen** [comment]
I switched to a new font, and the row wrap problem went away.  Unfortunately, I'm now seeing a row header miss-alignment (see http://jrowen.github.io/rhandsontable/).  It appears to be related to the checkbox column, as everything looks good if I exclude that column.

**Comment by AMBudnik** [comment]
@jrowen do you use any additional styling or a styling framework? 

After I changed the font to `Arial` in you demo above http://jsfiddle.net/b9f4evx0/5/ I didn't get the same misalignment.

**Comment by jrowen** [comment]
I'm using the [rmarkdown](http://rmarkdown.rstudio.com/) library with a [custom template](https://github.com/jrowen/rhandsontable/blob/gh-pages/index.Rmd) that [uses](http://rmarkdown.rstudio.com/html_document_format.html#appearance_and_style) the [bootswtach](http://bootswatch.com/) styling framework.

**Comment by AMBudnik** [comment]
so I guess there is a conflict between Handsontable styles and bootswatch template

**Comment by jrowen** [comment]
I believe you're correct, as setting the theme to `null` in the template fixes the problem.

**Comment by AMBudnik** [comment]
@jrowen maybe there's a solution to overwrite one of few lines instead of disabling whole template as it's surely wanted to have one.

**Comment by jrowen** [comment]
I think it has something to do with `position: absolute` in `ht_clone_left handsontable`.  If I disable on (goes back to relative), the table looks better (you can try it on the first table at http://jrowen.github.io/rhandsontable/).  Do I need to override the css in the R library or is this something that should be handled by handsontable?  Thanks again for all the help here.

**Comment by AMBudnik** [comment]
http://rmarkdown.rstudio.com/ adds additonal styling to tables or it was added by you? It's always better to add few lines more than to change a library source code.

**Comment by jrowen** [comment]
I created a [template](https://raw.githubusercontent.com/jrowen/rhandsontable/gh-pages/index.Rmd?_sm_au_=iVVPVNwHsgD0sSwf) and the rmarkdown library used it to create a [html](https://github.com/jrowen/rhandsontable/blob/gh-pages/index.html) file.  I added a bit of [custom css](https://github.com/jrowen/rhandsontable/blob/gh-pages/custom.css) to the process.  The rhandsontable R library also adds a bit of [custom css](https://github.com/jrowen/rhandsontable/blob/gh-pages/custom.css).

I can easily update both custom css files but would need to file a bug with the rmarkdown project if there's a proposed change there.  There is also an intermediate library called [htmlwidgets](https://github.com/ramnathv/htmlwidgets) that facilitates the interface between R and JS.  There are two primary ways an R user will interact with rhandsontable/handsontable: via a rmarkdown document or via an interactive shiny app ([example](https://jrowen.shinyapps.io/rhandsontable_datafile/), might be a bit dated).

Thanks again for all of your work here.  You can see from the stars on the rhandsontable project that many R users also find the library very useful.

**Comment by AMBudnik** [comment]
Thanks for proving investigation results.

**Comment by AMBudnik** [comment]
Hi @jrowen 

I am trying to solve this ticket but I have to say that I am a little bit lost. Is there anything in Handsontable that we need to fix according to this report?

**Comment by AMBudnik** [comment]
I guess that I can close the issue as there is no reply since 19'th of January. Anybody, feel free to let me know if you face any issues that may sound like this one.
