### ISSUE TITLE
performance issue with my expand collapse logic

### ISSUE THREAD

**Issue by samsonkhisty** [handsontable/handsontable#3321]
Hi @AMBudnik 
   I implement expand collapse on the table, I have a weird performance issue that I have trouble figuring out. FYI I have 1 fixed row and custom renderers for each column. However, expanding and rendering the table is 3 times faster than collapsing the table. Look at the gif and notice the values in the console. 

![bug4](https://cloud.githubusercontent.com/assets/3254606/13717488/e728b39a-e7af-11e5-82c1-81de77c4bf34.gif)

I have a simple click handler on the +/- icons, that updates property (hidden:true/false) on the row and its children and then re-render the table. Its the same function for expand or collapse, all it does is toggle the property and render the table. Here's my logic for the simple expand collapse row

      expandCollapseRow: function(e) {
         var hidden, hiddenCount, icon, selectedItem;
         icon = $(e.currentTarget);
         console.time("expandCollapseRow");
         
         //if icon has the minus icon then
         //   hidden = true
         //else 
         //   hidden = false
         
         // update all the rows that need to be hidden or shown return the count
         // use the count to update the rendering offset and then render the table.
         this.mainTable.handsontable("updateSettings", {
           viewportRowRenderingOffset: this.hiddenCount + 8
         });

         this.mainTable.handsontable("render");
         console.timeEnd("expandCollapseRow");
         return 
       }

**Comment by krzysztofspilka** [comment]
@samsonkhisty how big is your data set?

**Comment by samsonkhisty** [comment]
@krzysztofspilka 
I've got around 600 rows, 15 columns, 1 fixed column.

**Comment by AMBudnik** [comment]
Hi @samsonkhisty Could you create a demo where this issue can replicable?
It's hard to say anything without a source code.

**Comment by samsonkhisty** [comment]
@AMBudnik we already figured out. We spend some time going some profiling and optimizations. We also had an older version of the library. Updating it to the latest also improved the performance.

**Comment by AMBudnik** [comment]
Thanks for sharing feedback @samsonkhisty 
I'm glad that updating to newest version helped.
