### ISSUE TITLE
Can't get handsontable object

### ISSUE THREAD

**Issue by tranvietha** [handsontable/handsontable#3322]
Dear all,
I have used handsontable for my project but I have a problem with get handsonable object. Pls help me.

In my document.ready, I created handsontable with data like this:

var $container = $("#example1grid");
$container.handsontable({
				  	data: data,
				  	// disable drag-down cell
				  	//fillHandle: false,
				  	// render lai header cua spreedsheet
		  			afterRender: function () {
				  		$('.htCore > thead').html(str);
				  		$('.wtHider').removeAttr("style");
		  			}
			        cells: function (row, col, prop) {
						var cellProperties = {};
						if (col == 0) {
						  cellProperties.renderer = firstColRenderer; // uses function directly
						}

						return cellProperties;
				    }
				});

It work very good. Now, I want to create javascript function to add new row and do other works. But I can't get handsontable object.

var hotInstance = $("#example1grid").handsontable('getInstance');

if I put code above in document.ready, it works but if i create function, it not works. Pls help me.

Many tks

**Comment by AMBudnik** [comment]
Hi @tranvietha It would be very helpful if you could share your demo using [JSFiddle](http://jsfiddle.net/api/post/library/pure/)

Please take a minute also to check our Data Sources tutorial: https://docs.handsontable.com/0.23.0/tutorial-data-sources.html

**Comment by tranvietha** [comment]
Dear AMBudnik,

Tks for your response. I create global variable to save handsonable object and now I pass this issue. 

However I meet other issue: in my project, i load 30 record from database pertime, in page 1, every thing is perfect. But in page 2, when i scroll from left to right, handsontable only have several column (I check in fire bug and they also have several column).

Thank you,

**Comment by tranvietha** [comment]
I have found solution for my issue:

https://github.com/handsontable/handsontable/issues/941#issuecomment-65611971

Thank for your help AMBudnik
:+1:
