### ISSUE TITLE
Sorting of fixed column actually sorts another column

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3323]
reported at: https://forum.handsontable.com/t/sorting-of-fixed-column-actually-sorts-another-column/217

as said:

> Hi,
> When i try to apply sorting to fixed column, it often sorts column that is "covered" by fixed area.
> 
> On the demo i sort column "Phone2" column and it works fine first, but after scroll table horizontally - sorting of "Phone2" causes sorting of "Email1" column instead.
> 
> [jsfiddle demo](https://jsfiddle.net/mikhail_zagorny/gnLLox4a/)

**Comment by AMBudnik** [comment]
while testing I also got missing indicator.

**Comment by mzagorny** [comment]
Here is the demo of jsfiddle above.

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/3679134/13743766/c57dee26-e9f4-11e5-9eed-7272087f7e18.gif)

**Comment by woyuditan26** [comment]
same question

**Comment by zallax** [comment]
It's a problem with getColumn(target) function.

This is working for me.
```
    function getColumn(target) {
      var TH = closest(target, 'TH');
      if ($(TH).parents('.ht_clone_top_left_corner').length > 0) {
        return index(TH) - countRowHeaders();
      }
      else {
        return _this.hot.view.wt.wtTable.getFirstRenderedColumn() + index(TH) - countRowHeaders();
      }      
    }
```

**Comment by AMBudnik** [comment]
thanks for sharing your investigation results @zallax 
I'm sure they will be helpful for our devs

**Comment by harryganz** [comment]
I noticed this problem as well, I was going to post an issue and then found this. Here is a JSFiddle demonstrating the issue: https://jsfiddle.net/hganz/ro4q2t35/

How to reproduce bug:
1. Scroll table horizontally past the last rendered column
2. Click on the header for column A to sort it

The sorting gets applied to the wrong column.

**Comment by harryganz** [comment]
I found a workaround. If you change the viewRendering option offset to a number equal to or greater than the number of columns in the table, it will keep the sortingIndex and the column index in the getColumn function the same.

This will turn off column rendering optimization, but shouldn't be too bad if you don't have many columns.

Example: https://jsfiddle.net/pusejjtp/

**Comment by AMBudnik** [comment]
thanks for the tip @harryganz !

**Comment by harryganz** [comment]
@AMBudnik it appears you are correct. If someone could link to the pull request that fixed it that would be great.

**Comment by AMBudnik** [comment]
Sorry for a long delay. It will be pretty hard to find it now. We are working on commits - occasionally on PR.
