### ISSUE TITLE
Misalignment when columnHeaderHeight and fixedColumnsLeft are used together

### ISSUE THREAD

**Issue by ChristinaTech** [handsontable/handsontable#3324]
When a custom value for columnHeaderHeight and a non-zero fixedColumnsLeft are specified all the non-fixed columns go out of alignment. Tested on Chrome.

JSFiddle:
http://jsfiddle.net/hU6Kz/4883/

**Comment by AMBudnik** [comment]
Thanks for sharing @Scentus Confirmed

**Comment by AMBudnik** [comment]
result
![bez tytulu](https://cloud.githubusercontent.com/assets/10757813/13771760/68bd3420-ea90-11e5-8e11-2ae2995c0edc.png)

**Comment by AMBudnik** [comment]
Issue no longer occur.
