### ISSUE TITLE
dataSchema not working after version 0.19.0

### ISSUE THREAD

**Issue by kristianlm** [handsontable/handsontable#3326]
Hi and great work on this easy-to-use-online-table-editing! I think I may have found a bug.

1. Go here: http://docs.handsontable.com/0.23.0/tutorial-data-sources.html#page-data-schema
2. Click the 'edit in JSFiddle' button
3. It takes you to a 0.16.0-version of the example
4. It works (`hot5.getData()` returns array of objects based off of the schema, good)
5. Change the version to anything between 0.20.0 - 0.23.0
6. It no longer works (`hot.getData()` now always returns array of arrays, bad)

http://jsfiddle.net/kp5hxg5a/

Is this a bug?
Thanks!

**Comment by AMBudnik** [comment]
Hi @kristianlm 
Please check this example:http://jsfiddle.net/handsoncode/g047w42m/
In [0.20.0](https://github.com/handsontable/handsontable/releases/tag/0.20.0) we made some changes with `getData()` and `getSourceData()` which should be typed to get the same result as `getData()` in version below 0.20.0

**Comment by kristianlm** [comment]
My bad! I missed `getSourceData()`, it's even mentioned in the docs for [`getData()`](http://docs.handsontable.com/0.24.0/Core.html#getData).

Thanks @AMBudnik for your swift response!
