### ISSUE TITLE
Resizable row/col headers

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3327]
As we have an ability to resize columns and rows this idea will extend this ability to resize row/col headers.

Currently we can only set fixed values via [columnHeaderHeight](http://docs.handsontable.com/0.24.0/Options.html#columnHeaderHeight) and [rowHeaderWidth](http://docs.handsontable.com/0.24.0/Options.html#rowHeaderWidth)

**Comment by DHoffm** [comment]
For anyone needing this, here is a workaround:

Calculate the textWidth for each rowHeader with:

`
// found via: http://stackoverflow.com/a/15302051/3298029
$.fn.textWidth = function(text, font) {
    if (!$.fn.textWidth.fakeEl) $.fn.textWidth.fakeEl = $('<span>').hide().appendTo(document.body);
    $.fn.textWidth.fakeEl.text(text || this.val() || this.text()).css('font', font || this.css('font'));
    return $.fn.textWidth.fakeEl.width();
};`

And check which one is the largest. Afterwards set it with rowHeaderWidth

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
