### ISSUE TITLE
Inconsistent behavior between Shift+Tab and Shift+Enter

### ISSUE THREAD

**Issue by desertdev** [handsontable/handsontable#3332]
When using custom functions for tabMoves and enterMoves, the returned object coordinates are automatically negated afterwards when Shift+Tab were pressed, but not when Shift+Enter were pressed.

Personally I would prefer if there was no automatic negation when custom functions are defined, but either way the two cases should behave consistently.

**Comment by desertdev** [comment]
Clarification:

I'm actually only seeing this inconsistency when the the table is readonly. In this scenario, I want tab and enter keypresses to go up and down through through the rows. 

For example, for a regular keypress without the Shift key my function returns { row: 1, col: 0 } to advance forward one row. Doing a Shift+Tab I can return the same result and it moves back one row. But for Shift+Enter I must return { row: -1, col: 0 } to get the same result.

But for some reason when I'm moving between selected cells that are not readonly with Shift+Tab and Shift+Enter, the results are consistent without needing to alter the return object for Shift+Enter.

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topic and uloading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Isuee will be reopene with first update.
