### ISSUE TITLE
afterSelection should fire also when cell is programatically selected

### ISSUE THREAD

**Issue by gstanislav** [handsontable/handsontable#3333]
...or, in the interest of backwards-compatibility, a hook `afterProgrammaticSelection` can be added.

**Comment by AMBudnik** [comment]
Hi @gstanislav 
Please take a minute to check this demo http://jsfiddle.net/8jvbr66d/
I'm injecting `hot.selectCell(0.0)` into a `select` button and I'm receiving a log from `afterSelection`
