### ISSUE TITLE
Latest versions doen't support formula 

### ISSUE THREAD

**Issue by happyhero0** [handsontable/handsontable#3335]
Dear developers, I found latest versions like 0.24 etc. can't support formula.
I have to use the very old version 0.14.
When dragging the cell right-bottom border to bottom,  it can't set right value using formula.
I found in the hook `beforeAutofillInsidePopulate`, the `iterators` is empty object.
And if the column has `type` and `formula`,  the formula feature doen't work ,why ?

```
columnObj.type = 'numeric';
columnObj.format =  '0,0.[00]';
// then the formula in the column not working
```

Thank you. Handsontable is great, but the formula feature has many problem....

**Comment by AMBudnik** [comment]
Hi @xfight0 
I made a demo using v0.24.1 and formulas support: http://jsfiddle.net/5y2xm08d/
Please guide me how to reproduce the issue

**Comment by xfight0** [comment]
@AMBudnik  Thank you for the example and responsibility.
After calculate a cell value using formula( for example: `=c2+d2`), in the jsfiddle example, the value is 7244, then I put cursor to the cell right-bottom corner and drag it down, arising a error: 
```
handsontable.formula.js:176 Uncaught TypeError: Cannot read property '0' of undefined
```

This is a general operation in excel / mac numbers / google spreadsheets, after caculating a value with a formula, dragging the cell border to down or up,  
grid will calculate related value. 
For example, the first cell formula is `=c2+d2`, when dragging down, other cell will calculate value with `=c3+d3`, `=c4+d4`....

In  v0.14 , the feature is working well, but v0.24.1 not.
One more question is:  if a column set type and formula,  the formula feature doen't work, the operation make cell background alert red.

**Comment by AMBudnik** [comment]
I reproduced the error - thank you for detailed reply. The issue seams to be older as it occurs using v0.24.0 also. I'm setting a bug label for this one.

When it comes to question - in the example above we're using default `text` cell type. 
in example provided here http://jsfiddle.net/5y2xm08d/1/ I'm using `numeric` cell type for the first column and then if we type a formula `= C2 + D2` in `0, 0` cell which in result is a number we'll get a validation false cause its source is a `string`.

**Comment by xfight0** [comment]
About the bug - column has `numeric` type doen't support formula, in example provided [here](https://jsfiddle.net/xfight9/v210mu8a/9/)

I used ngHandsontable, perhaps is there a bug in ngHandsontable?

**Comment by AMBudnik** [comment]
@xfight0 actually the base of this issue is here https://github.com/handsontable/ngHandsontable/issues/76 but I hope that refactoring formulas will help in this case.

**Comment by xfight0** [comment]
Hello @AMBudnik,  When are you going to refactor formulas, is there a roadmap?

**Comment by AMBudnik** [comment]
Hi @xfight0 
We'll start next week. We already did some research how to handle things and it looks promising.

**Comment by jackparmer** [comment]
Hey @AMBudnik - Is there a PR or commit history for this that we could check out? I haven't been able to find anything.

**Comment by AMBudnik** [comment]
Hi @jackparmer that's right - there's no commit for formulas yet. Last 2 weeks were very busy cause we had to work on the _my.handsontable.com_ but from June there will be more time for formulas.

**Comment by AMBudnik** [comment]
Hi @happyhero0 

sorry for bringing up old issues but I wanted to test it with the PRO version of formulas. Can you check if everything works now?

**Comment by AMBudnik** [comment]
I think that we can close this issue as it is 1 y old and there wasn't any new reply.

**Comment by JerryYangJin** [comment]
sorry for updating old ticket, this issue is still there in `0.31.2`, old version `0.14.1` used in [handsontable-ruleJS](http://handsontable.github.io/handsontable-ruleJS/) works fine

**Comment by AMBudnik** [comment]
@JerryYangJin Can you create a new ticket with a demo where we'd be able to replicate the issue? Thanks in advance!
