### ISSUE TITLE
autoInsertRow doesn't work with multiple instances

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3336]
as written at https://forum.handsontable.com/t/multiple-instances-of-table-on-same-page/225

> Hi, team.
> 
> If the page contains multiple copies of the table with different settings 'fillHandle', the Autofill is not working properly.
> 
> I've created a jsfiddle to demonstrate the problem:
> http://jsfiddle.net/0y8p0bey/
> 
> Just try drag row down for each of tables.
> Expected result: Only the second table should create new rows till it reaches the last row. 
> Actual result: But first table is also capable.
> 
> Please let me know when you can fix this issue.
> Thank you in advance.

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/3257.
