### ISSUE TITLE
Pasting an ISO 8601 formatted date into a date cell causes wrong date to persist

### ISSUE THREAD

**Issue by jdmcnair** [handsontable/handsontable#3338]
Due to the issues with parsing ISO 8601 dates using new Date('') (discussed in depth here: http://stackoverflow.com/a/20463521/956150), pasting a text value like '2016-03-18' into a date column causes the corrected date string to show up on the previous day's date (i.e. '3/17/2016'). This is due to the `new Date('')` constructor being used to parse the date string. Momentjs has better handling of ISO 8601 strings, so it alone should be used to parse the date instead of passing the string to the date constructor before the corrupted result is given to momentjs.

Created a pull request for this issue here: https://github.com/handsontable/handsontable/pull/3337

**Comment by AMBudnik** [comment]
Thank you for detailed information @jdmcnair

**Comment by jdmcnair** [comment]
Certainly. Let me know if any changes are required on the pull request. It's a small change, and I've included an accompanying unit test.

**Comment by jansiegel** [comment]
@jdmcnair Does this happen on any specific browsers? It seems to work fine for me on Chrome, Firefox and Safari. Can you maybe prepare a simple demo on jsfiddle of this not working properly?

The problem with your fix is, in some cases `moment.js` throws a warning, that this constructor is deprecated and will be removed in the next major release, while `moment(new Date())` will still be valid.
![image](https://cloud.githubusercontent.com/assets/7397134/14040470/c4e47248-f267-11e5-8a2b-838c87f1c34b.png)

**Comment by jdmcnair** [comment]
Hmm, I didn't see the deprecation warning. Interesting thing about that deprecation, it appears that you don't get the warning if it is an ISO8601 date (i.e. `moment('2016-02-02')` doesn't get the warning, but `moment('02/02/2016')` does). I'm not sure if that's an indication that they'll continue to support the string constructor for ISO8601 dates, or if the messaging is just inconsistent.

I can create a jsfiddle if need be, but the underlying issue is extremely easy to recreate *if* you happen to be sitting in a UTC *minus* x timezone (the Americas, etc). I'm guessing the fact that you're not seeing it may mean that you're somewhere in Europe, or UTC/UTC *plus* X. If you are in a UTC-x timezone, you can just create a moment date object like so: `moment(new Date('2016-02-02'))`. You'll see the resulting moment object is created at UTC midnight, then converted to local time, which in my case is `Mon Feb 01 2016 19:00:00 GMT-0500`. The unit test I included in the PR demonstrates the problem, but I guess it's only if you're in certain timezones.

Considering the deprecation, I'm not sure what's the best way to handle it... maybe first check to see if it's an ISO8601 date, then give it special handling? I'd be glad to update my pull request. What do you think is the best approach?

**Comment by jdmcnair** [comment]
BTW, I'm seeing this in chrome. I guess it's also happening in whichever browser engine you guys are using to run your unit tests.

**Comment by jdmcnair** [comment]
@jansiegel, have you had a chance to reproduce given the specifics on timezone that I mentioned above?

**Comment by jansiegel** [comment]
Sorry for the delay, @jdmcnair.

> I'm not sure if that's an indication that they'll continue to support the string constructor for ISO8601 dates

I'd think so, but I'm not really sure either.

And - you're right, it seems to happen on the UTC *minus* x timezones exclusively. Unfortunately, I'm afraid that even when I'm not using the `Date` constructor, `momentjs` doesn't handle the non-iso dates properly. For example:

![image](https://cloud.githubusercontent.com/assets/7397134/14204271/5e1ceb52-f803-11e5-81d8-eb0e2e0859f6.png)

We will have to think about a reasonable workaround for this. When we figure something out, I'll let you know in this thread :)

**Comment by jansiegel** [comment]
I've made a helper function which compensates the timezone offset, when date is provided in a ISO8601-compliant format. I hope this fixes that problem completely :)
Also, I've used your test case, @jdmcnair, it seems to recognize and test this problem nicely.

**Comment by jdmcnair** [comment]
Great Thanks @jansiegel

**Comment by AMBudnik** [comment]
fixed with 0.24.2.
