### ISSUE TITLE
Dulicate headers while exporting

### ISSUE THREAD

**Issue by ramankaushik008** [handsontable/handsontable#3340]
when i am exporting table content headers are coming twice please suggest.

![errorinhandsontable](https://cloud.githubusercontent.com/assets/7859479/13914052/f2daa4c2-ef71-11e5-92e4-976a4c0b3d57.PNG)

**Comment by AMBudnik** [comment]
Hi @ramankaushik008 
I couldn't reproduce it. Could you share a demo (JSFiddle/JSBin/CodePen) were we can track the issue?

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo. 
If you'll still having this issue @ramankaushik008 do not hesitate to comment. Thanks!
