### ISSUE TITLE
Handsontbale scroll down too slow when using fixedColumns property

### ISSUE THREAD

**Issue by msrikant32** [handsontable/handsontable#3341]
Handsontbale vertical scroll bar is too slow when scrolled using mouse scroll,however it is normal while dragging through scroll bar. The issue is present only when using fixedColumns property in the Handsontbale settings. 

Noticed this issue while working on some application,came back to Handsontbale website for fixedColumns examples in documentation. Can see the issue in Handsontable website but not in JSFiddle . Here is the link

[](http://docs.handsontable.com/0.18.0/demo-fixed-rows-and-columns.html)
Can anyone throw some light on this issue.

**Comment by AMBudnik** [comment]
Hi @msrikant32 there's a missing link (to an example).
I made a simple table 5000 x 50 using `fixedColumnsLeft: 2` http://jsfiddle.net/nk6dxuo3/ Does it present the issue described in this topic?

**Comment by msrikant32** [comment]
Hi AMBudnik,
In jffiddle example it's work fine but in online application(html page) "fixedColumnsLeft" is present scoll bar is not working.
U can refer this link http://docs.handsontable.com/0.15.0-beta6/demo-scrollbars.html

**Comment by AMBudnik** [comment]
You're using 0.15.0-beta6 version in this example. In latest 0.24.1 it's working faster: http://docs.handsontable.com/0.24.1/demo-scrolling.html

**Comment by msrikant32** [comment]
@AMBudnik,

Thanks for the answer. It really helped a lot.

**Comment by AMBudnik** [comment]
Glad I helped. 
If you would have any other issues please create a new topic. I'm closing this one.
