### ISSUE TITLE
Table with merged cells gets broken on validation

### ISSUE THREAD

**Issue by Laplandia** [handsontable/handsontable#3342]
http://jsfiddle.net/y35aqgsa/

Merged cells are hidden on validation. They will reappear again on next render.

**Comment by AMBudnik** [comment]
Thanks for sharing @Laplandia I'll mark this issue as a comments bug

**Comment by Laplandia** [comment]
Technical details: 
MergeCells.prototype.applySpanProperties hides cells on validation that should not be hidden, because it is called with TD that should be visible, and row and col of the cell that is already hidden.

**Comment by AMBudnik** [comment]
Thanks for additional details @Laplandia

**Comment by AMBudnik** [comment]
Workaround:
http://jsfiddle.net/y35aqgsa/1/

Adds a validate function that triggers rendering again.
```
 hot.validateCells(function() {
  	hot.render();
  });
```

**Comment by Laplandia** [comment]
Thanks, Alexandra. 
We actually tried this already, but validation takes very long time for our table due to a number of server requests. So when validation is still working, cells would move erratically.

**Comment by AMBudnik** [comment]
Thanks for a prompt reply @Laplandia 
I'll remove it then to not share a inelegant solution.

**Comment by Laplandia** [comment]
Is there any chance of the pull request being reviewed?

**Comment by AMBudnik** [comment]
Hi @Laplandia 
Our programmers are working now on formulas, nested rows and fixing bugs. When it comes to the `merging` plugin there are some other heavy issues related to it and it will definitely take more time for the pull request to be reviewed.

I hope that the recent release didn't had a negative impact on this solutions compatibility and you could easily use the solution and update to 0.24.3.

**Comment by hjdarnel** [comment]
Is there a workaround to this for now?

**Comment by AMBudnik** [comment]
Hi @hjdarnel 

our develop is working on a mergeCells refactor. I think that the issue will be gone after the release of [the following milestone](https://github.com/handsontable/handsontable/milestone/84).

**Comment by jansiegel** [comment]
Should work fine in `0.37.0`.

**Comment by AMBudnik** [comment]
Hi @Laplandia @hjdarnel 

Please update to version 0.37.0 and let us know if it solves the issue on your side
