### ISSUE TITLE
afterChange fired multiple times

### ISSUE THREAD

**Issue by renathy** [handsontable/handsontable#3343]
Can you explain why afterChange event fires multiple times if I update value of once cell and lick outside it?

 config.afterChange = function (changes, source) {
            if (changes != null) {
                console.log('htch'); // ->>> this is fired multiple times
                var tableData = $container.handsontable("getData");
                config.observableData(tableData);
            }
        };

P.S. Unofurtunately we are using old handsontable source (version 0.10 or similar).

**Comment by AMBudnik** [comment]
Hi @renathy 
I would ready appreciate a demo where we can check what's going on and create some conclusions.

**Comment by renathy** [comment]
I would try to check fi afterChange event also fires multiple time on some of your examples.

**Comment by AMBudnik** [comment]
@renathy ok, I'll be waiting.

**Comment by AMBudnik** [comment]
Hi @renathy 
How is your progress with this example? 
Is there anything I can help you with?

**Comment by AMBudnik** [comment]
Issue will stay closed till an authors reply.
Please take your time @renathy Issue will get reopened after you create a demo.

**Comment by jrowen** [comment]
I'm also seeing this behavior.  

You can see this by going to https://jrowen.shinyapps.io/rhandsontable_output/ and watching the activity in the Javascript console while updating the table (I added some console logging; alternately you can set a breakpoint in the afterChangeCallback function in the rhandsontable source).  The afterChange event appears to fire more frequently after each update.

Issue originated at https://github.com/jrowen/rhandsontable/issues/98.

**Comment by AMBudnik** [comment]
Hi @jrowen 
can you create a simple JSFiddle demo where we'll be able to see the code?

**Comment by jrowen** [comment]
Unfortunately, I can't create a simple demo for this example, but with the Chrome debugger (or similar), I think you should be able to see what's going on.

The table is created through an interface between R and Javascript, and the Javascript code to create the table can be seen at https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js.

I'm sorry I can't simplify debugging this (I'm open to ideas).  It could be problem lies in the implementation of the interface, but the debugging I've done seems to point to the table logic.  I'm wondering if it could be related to some type of data caching (maybe for undo, which doesn't seem to be working in this example).

**Comment by AMBudnik** [comment]
Hi @jrowen 
unfortunately now I'm getting the console error:
`sockjs-0.3.min.js:27 POST https://jrowen.shinyapps.io/rhandsontable_output/__sockjs__/n=ta34DnMHHBYaw…I4/t=c2f7212a109c13c3359676ff29f7f56a/w=a2121bfc/s=0/656/ddpnah14/xhr_send net::ERR_NETWORK_CHANGED`
from your example. 
Without a demo code it will be very hard to replicate the bug and to fix as well.
I've created an example with similar data but the `afterChange` hook works as expected there. Demo: http://jsfiddle.net/k06tw3aL/

**Comment by jrowen** [comment]
Here's an animation that I hope helps.  The console output is coming from logging [in these lines](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js#L81-L111) and the [table is created here](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js#L15-L61).

![pic](https://cloud.githubusercontent.com/assets/1530030/18168831/30eefffc-701d-11e6-8928-61d1a5592ca6.gif)

**Comment by AMBudnik** [comment]
Do you use any additional hooks or renderers?

**Comment by jrowen** [comment]
The columns in the example above are using a [customRenderer](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js#L259-L271) that handles some data type mapping between R and handsontable.  The customRenderer ultimately calls the appropriate handsontable renderer.

There are a [few additional hooks](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js#L113-L200) used to pass data back into the R (shiny) app: afterSetCellMeta, afterSelectionEnd, afterCreateRow, afterRemoveRow, afterCreateCol, afterRemoveCol.

**Comment by AMBudnik** [comment]
thank you for the details @jrowen

**Comment by budnix** [comment]
Confirmed, after investigating this issue I found that there is a problem with updateSettings. When developer passes the same listeners to the updateSettings over and over again then this listener is added to the collection of listeners instead of overwriting previous one.

Workaround for this could be to pass listeners only once while Handsontable initialization.

**Comment by masato-io** [comment]
I'm experiencing similar issue on react-handsontable as well. submitted issue here:
https://github.com/handsontable/react-handsontable/issues/7

**Comment by AMBudnik** [comment]
Hi @masato-io 
React version uses the same logic so if this issue will be solved here (for community edition) it will also for from the React version (after updating it)

**Comment by masato-io** [comment]
Hey @AMBudnik,
Thank you for your reply. Is there any difference between community edition and paid edition in terms of this issue?

**Comment by AMBudnik** [comment]
Hi @masato-io nope, this part of code is equal for both versions.

**Comment by masato-io** [comment]
@AMBudnik sounds good, thanks!

**Comment by AMBudnik** [comment]
Hi @renathy, Can you check the updates in v0.31.1?

**Comment by masato-io** [comment]
for my use case, confirmed v0.31.1 is working as expected now 👍

**Comment by AMBudnik** [comment]
Thank you for confirmation @masato-io 
I guess we can close this issue.
