### ISSUE TITLE
Contextmenu not closing in Modaldialog

### ISSUE THREAD

**Issue by LeoLerch** [handsontable/handsontable#3344]
I am trying to use handsontable in a Modaldialog (in special in Sharepoint). I use a context menu but it is not disappearing if I click outside the menu. (if I click on a menu entry it does). 

It seems to have something to do with the registered eventlistener which is registered for 

`document.documentElement, "mousedown"`

it works, when I register it for the hot-Element itself or on the mouseup event. However, "mousedown" and "mouseclick" seem to be not propagated up from the document-element when using a modaldialog.

**Comment by AMBudnik** [comment]
Hi @LeoLerch 
Could you create a demo where we can replicate the issue?

**Comment by LeoLerch** [comment]
It has something to do how Sharepoint handles its modaldialog. It prevents the bubbling of the events. I disabled it and now it works fine

thanks anyway

**Comment by AMBudnik** [comment]
Thanks for feedback @LeoLerch 
I'm closing this issue.
