### ISSUE TITLE
Select to last row creates new one

### ISSUE THREAD

**Issue by illuusio** [handsontable/handsontable#3345]
If select is until last row that creates new row a the bottom and launches event 'afterCreateRow'. This happens with basic example in fiddle. Even turning of:
<pre>
    allowInsertRow: false,
    allowInsertCol: false,
</pre>
doesn't change anything. Tested in newest Firefox and Chrome. for testing 

https://docs.handsontable.com/0.24.1/demo-scrolling.html

go scroll bottom at the grid and select something below until last row and there is new one.

**Comment by AMBudnik** [comment]
Hi @illuusio 

Please check this demo:http://jsfiddle.net/5dyuo6hv/
`allowInsertRow` is used to allow/disallow showing an option to insert row via contextMenu.

To disallow creating new rows after dragging cells you would need to add

`fillHandle: {`
 ` autoInsertRow: false`
`}`

to your instance's settings.

**Comment by illuusio** [comment]
Ok does the trick and work like before. Should be the default (I don't know how many wants it to work like this?). But can be closed.. thanks for the quick response!
