### ISSUE TITLE
Undo is count rows and cols at the end ,performance

### ISSUE THREAD

**Issue by mainstream95** [handsontable/handsontable#3347]
countEmptyRows and Cols func

      var i = instance.countRows() - 1,
          empty = 0,
          row;
      while (i >= 0) {
        row = Handsontable.hooks.run(this, 'modifyRow', i);
        if (instance.isEmptyRow(row)) {
          empty++;
        } else if (ending) {
          break;
        }
        i--;
      }

Maybe it should be so, but i cant understand. **minsparecols is off**  i have 100k data (**take into acc that server side fetching at scroll**) and 2 columns at the end is empty. howewer counting empty rows   needed for this 

    for (var i = 0,
        len = data.length; i < len; i++) {
      if (instance.getSettings().minSpareRows && data[i][0] + 1 + instance.getSettings().minSpareRows === instance.countRows() && emptyRowsAtTheEnd == instance.getSettings().minSpareRows) {
        instance.alter('remove_row', parseInt(data[i][0] + 1, 10), instance.getSettings().minSpareRows);
        instance.undoRedo.doneActions.pop();
      }
      if (instance.getSettings().minSpareCols && data[i][1] + 1 + instance.getSettings().minSpareCols === instance.countCols() && emptyColsAtTheEnd == instance.getSettings().minSpareCols) {
        instance.alter('remove_col', parseInt(data[i][1] + 1, 10), instance.getSettings().minSpareCols);
        instance.undoRedo.doneActions.pop();
      }
    }

counting **cols** (and rows in my situation horroble too)  is wasted
with my features i have wait for seconds in undo action

anyway 
http://jsfiddle.net/co9tscsk/3/
delete  last 7-8 columns and see difference

**Comment by AMBudnik** [comment]
Hi @mainstream95 
You say that if we add `minSpareCols` or `minSpareRows` to our instance's settings we'll be provided with lower performance? 
I tried it with your example but I can't see the difference. Can you guide me on how to reproduce it?

**Comment by AMBudnik** [comment]
Issue closed in lack of Author's reply
