### ISSUE TITLE
Edit long value in IE11 with comment present

### ISSUE THREAD

**Issue by ikhramtsov** [handsontable/handsontable#3348]
When start editing a long value in table's cell and there is a comment already shown, caret displays above comment (see screenshot for example)
![hot_issue](https://cloud.githubusercontent.com/assets/14012005/13979929/ad0288c6-f0ec-11e5-90aa-9c45fdd34845.png).

This happens in IE only and comment div hides once you move mouse.

**Comment by AMBudnik** [comment]
Confirmed. Thanks for sharing @ikhramtsov 
Comment doesn't move right with typed characters and it's overlapping edited cell.
![bez tytulu](https://cloud.githubusercontent.com/assets/10757813/13980523/6226abdc-f0df-11e5-967f-45ebf1b1a969.png)

**Comment by ikhramtsov** [comment]
That's corect - comments shouldn't move depending on cell width, but at the same time I wouldn't expect comment to display between cell and caret of that cell like in my screenshot. Caret relies to input cell, so I would expect to see both of them (input and caret) or none of them, meanwhile in IE11 I can see caret but I do not see the input.

Can you please tell me if it is going to be fixed?

Thanks in advance, Igor

**Comment by AMBudnik** [comment]
I really would like to give you any date but now our priority is to fix high priority bugs and we're working very hard to fix them as soon as possible.

The second thing is that comments plugin will be refactored so it's a huge case we'd need to arrange. I think it'll be in Q3 or Q4 this year.

**Comment by ikhramtsov** [comment]
I appreciate your effort! Thanks, Aleksandra!

**Comment by AMBudnik** [comment]
Currently comment is hiding when cell editor opens.
