### ISSUE TITLE
After filtering, dropdown filtering options are not retained

### ISSUE THREAD

**Issue by BrettMohr** [handsontable/handsontable#3349]
After you've filtered a column's data and there are no matches (the visible table is empty), the dropdown filter options for that column are not retained.

For example, I have a column with the date type, I'm filtering that column's data, and everything is filtered out because there are no matches to that criteria. Then I'm opening the dropdown menu to filter the column data using a new value, but the selection options that are specific to the date type are no longer available (i.e. "after", "before", "tomorrow", "today").

**Comment by BrettMohr** [comment]
This appears to be fixed by updating to the latest version of handsontable-pro, which I was not aware was released.

**Comment by krzysztofspilka** [comment]
@BrettMohr I'm glad we could help:)
