### ISSUE TITLE
Insert row above = insert row below

### ISSUE THREAD

**Issue by LoveOfLava** [handsontable/handsontable#3352]
Hi,

I'm currently facing an bug, when I click on "insert row above" it insert a row below.
I work under the last chrome explorer.

Regards

**Comment by AMBudnik** [comment]
Hi @LoveOfLava 
I've checked if above actions are allowed with this demo http://jsfiddle.net/o35p68ed/ and they are.

Can you reproduce the issue with the demo I provided?

**Comment by LoveOfLava** [comment]
Hi,

I check the behavior on my instance.
When I modify the row header, my custom header isn't moved.

Regards

**Comment by AMBudnik** [comment]
Could you provide those custom settings?

**Comment by LoveOfLava** [comment]
http://jsfiddle.net/dmfd0tkd/

**Comment by AMBudnik** [comment]
Thanks for sharing @LoveOfLava 
Actually in Handsontable  PRO there's an `bindRowsWithHeaders` option that if pasted with `strict` value allows you to achieve your goal.

Here's a demo: http://jsfiddle.net/w7ys613c/1/

As this option is not documented I'm marking this issue to remind us about it.

**Comment by LoveOfLava** [comment]
Hi,

You will fix the bug in next update ?

Regards

**Comment by AMBudnik** [comment]
Hi @LoveOfLava 
It is not a bug. It is a lack of a feature that is provided by Handsontable PRO.
I'm sure this issue explains it's all: https://github.com/handsontable/handsontable/issues/3286

**Comment by LoveOfLava** [comment]
Hi,

Yes but on your pro demo the number are not following like the col header.

Regards

**Comment by AMBudnik** [comment]
This is how `bindRowsWithHeaders` works

Starting table
![1a](https://cloud.githubusercontent.com/assets/10757813/14022391/e4103932-f1df-11e5-9b40-4954e91748f2.png)

Added a row between first and second row.
![1](https://cloud.githubusercontent.com/assets/10757813/14022403/f1d0f35e-f1df-11e5-94c3-af3fe4ca3fce.png)

Adding new row gives it first available number name basing on other rows headers **BUT** as you rightly discovered it's not consistent with the bahavior of columns.

Starting table
![lu](https://cloud.githubusercontent.com/assets/10757813/14022833/e99c5262-f1e1-11e5-8b34-9361fbcacce3.png)

Added a column between first and second column.
![bez tytulu](https://cloud.githubusercontent.com/assets/10757813/14022607/d52a466e-f1e0-11e5-9c5e-22947f506127.png)

If they would in this case our new added column header will be named `H`. What we got is a `B` column and and extra `H` column at the end of the table.

**Comment by budnix** [comment]
@AMBudnik In your case you compare two different shifting algorithms. `BindRowsWithHeaders` plugin uses strict mode and column shifting (core) has its own approach to do this so that is why they are not working the same.

This issue should be discussed with team. Issue here is a unification in behavior of a row and column header.

**Comment by LoveOfLava** [comment]
Hi,

Why on my example 

https://jsfiddle.net/Hun7er/Lkpfq3jc/

all rowheaders is 1 ?

**Comment by jansiegel** [comment]
@LoveOfLava, it seems to be a `bindRowsWithHeaders`-related bug. I also found another example of a weird behaviour: https://jsfiddle.net/Lkpfq3jc/1/

I've created a separate issue for this problems, as they're not really related with inserting new rows: #3367.
