### ISSUE TITLE
Before autofill start/end points ambiguous for getting the copied or starting cell.

### ISSUE THREAD

**Issue by tympollack** [handsontable/handsontable#3353]
I'm trying to use the beforeAuofill hook to determine what cells are getting filled.  The issue I have is that start and end give me coords for what cells are to be filled, but there's nothing about what the original fill cell is.  While I can tell which way it's going most of the time (horiz vs vert), if you're only filling 1 cell, start and end are the same, so there's no way to tell which way it's going.  Further, if you drag up instead of down, the start/end still go from smallest row to highest row, so that doesn't help as much either.

My current solution is to get all selected cells and compare what's in start/end to see which cell is the "copied" cell, but it seems unintuitive, and there could be a better way?

Let me know if something else already exists to determine that information.

**Comment by AMBudnik** [comment]
Hi @tympollack 
`beforeAutofill` should return as written in the [docs](https://docs.handsontable.com/0.24.1/Hooks.html#event:beforeAutofill)

1. Object containing information about first filled cell: {row: 2, col: 0}.
2. Object containing information about last filled cell: {row: 4, col: 1}.
3. 2D array containing information about fill pattern: [["1', "Ted"], ["1', "John"]].

There are information that presents the cell that's a source of an autofill. If you'd like to get more info about what exactly was changed I recommend using `afterChange`. Please check this demo: http://jsfiddle.net/nt6fdfd5/

It logs the changes and there's a separate change type 'autofill' that you can track.

**Comment by tympollack** [comment]
I understand what's written in the docs.  I'm stating that it feels inadequate.  I used your demo for afterChange, and it only provides the same information - the filled cells, and then the data from the copied cell.  However, it does not provide table coords for the copied cell.  That's what I'm trying to find.

**Comment by AMBudnik** [comment]
OK, I can see what you mean. I'll add your idea to our feature requests. 
We have two options here:
a ) provide additional information in the same callback
b ) create a new method to return extra information

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
Currently (v9.0.2) `afterChange` logs coordinates of all changes cells via `Autofill.fill` source of change

![image](https://user-images.githubusercontent.com/10757813/129565804-d0209fb5-c27d-4cac-8a2b-7e27b939e425.png)
http://jsfiddle.net/bfzsk9nr/
