### ISSUE TITLE
Clicking on fixed column header causes exception when there is a positive colOffset()

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#3354]
If you have fixed columns, and you scroll far to the right causing a positive `colOffset()`, you will get an exception if you click in one of the fixed column headers:

```
TypeError: TR.childNodes[offsettedColIndex] is undefined
Core/this.getHeaderColspan() handsontable.full.js:5828
TableView/walkontableConfig.onCellMouseDown() handsontable.full.js:19644
[19]</<.getSetting() handsontable.full.js:3019
[7]</<.getSetting() handsontable.full.js:1253
WalkontableEvent/onMouseDown() handsontable.full.js:1294
callbackProxy() handsontable.full.js:8908
```

You can reproduce this from the example in the docs: https://docs.handsontable.com/0.24.1/demo-fixing.html

**Comment by AMBudnik** [comment]
Hi @cgatesman 
I tried to to get the logs using this demo: http://jsfiddle.net/ebjsz8mf/ on latest Chrome and FF in Windows8 but with no luck.
Am I missing something?

**Comment by cgatesman** [comment]
Weird.  I just reproduced it no problem in both Firefox Developer Edition and latest Chrome using your jsfiddle--although I'm on OS X.  I scroll all the way to the right on the table, then click on the A in the first column's header.

<img width="448" alt="screen shot 2016-03-25 at 10 32 45 pm" src="https://cloud.githubusercontent.com/assets/6276072/14057546/a44864d2-f2d9-11e5-8fa7-b236cb2f6ed9.png">

<img width="525" alt="screen shot 2016-03-25 at 10 32 34 pm" src="https://cloud.githubusercontent.com/assets/6276072/14057545/a4413338-f2d9-11e5-847d-1ea12ff61fef.png">

**Comment by cgatesman** [comment]
To be complete, I even tried Safari:

<img width="594" alt="screen shot 2016-03-25 at 10 38 34 pm" src="https://cloud.githubusercontent.com/assets/6276072/14057577/5fc2246e-f2da-11e5-8042-325f0bf49575.png">

**Comment by AMBudnik** [comment]
@cgatesman thanks for feedback and details
