### ISSUE TITLE
update settings - afterScrollVertically not overrided(changed) ,but added

### ISSUE THREAD

**Issue by mainstream95** [handsontable/handsontable#3357]
when update settings each time, old callback stays the same and new function called also

http://jsfiddle.net/co9tscsk/5/

or i miss something?

**Comment by AMBudnik** [comment]
Thanks for sharing @mainstream95 
Confirmed.

**Comment by AMBudnik** [comment]
Still replicable, demo http://jsfiddle.net/handsoncode/oLgv3czb/
1. `readOnly` state stays the same
2. `afterScrollVertically` is not changed

**Comment by AMBudnik** [comment]
Hi @mainstream95 
It looks like now the scoll calls only the second log (updated version).
Can you check if the `afterScrollVertically` is gone in your project after updating to `2.0.0`?

**Comment by AMBudnik** [comment]
I think that we can close this issue as there's no reply for more than 2 weeks
