### ISSUE TITLE
Object data sources no longer working?

### ISSUE THREAD

**Issue by callunity** [handsontable/handsontable#3358]
The latest version doesn't seem to support Object data sources any more -- the Handsontable website's [Object data source (custom data schema)](http://past.handsontable.com/demo/datasources.html#dataschema) example shows an Array data source, not an Object data source, when data is dumped to console.

**Comment by krzysztofspilka** [comment]
Hi @callunity, did you try this one? http://docs.handsontable.com/0.24.1/tutorial-data-sources.html#page-object

**Comment by callunity** [comment]
Hi @krzysztofspilka , that one does it too -- it dumps an array of Arrays, not an array of Objects like I was expecting.

**Comment by LeoLerch** [comment]
It still does support object sources. Just the api changed

Use getSourceData instead as mentioned in the API

http://docs.handsontable.com/0.24.1/Core.html#getData

**Comment by jansiegel** [comment]
@callunity, thanks for noticing that! @LeoLerch is right, the API changed a few versions ago:
`getData` returns the *visual* data from the grid using an array of arrays, while `getSourceData` returns the data as it was passed to HOT.

We will change the `Dump data to console` button callback to use `getSourceData`, it seems to make more sense.

**Comment by krzysztofspilka** [comment]
@callunity indeed, here you can find the full release note of that change: https://github.com/handsontable/handsontable/releases/tag/0.20.0

**Comment by callunity** [comment]
Thanks @LeoLerch , @jansiegel and @krzysztofspilka !
