### ISSUE TITLE
Set class to row (or cell)

### ISSUE THREAD

**Issue by lesonunique** [handsontable/handsontable#3359]
Hello,

I would like to modify ( add or remove ) a class to a row or a cell once the table was created .

Is it the ability to make a function like the `setDataAtCell(row, col, value, source)` for set a class ?

Thank you in advance.

Cordially.

Vincent LEVEQUE

**Comment by AMBudnik** [comment]
Hi @lesonunique 
Please take a minute to this short tutorial of conditional formatting: https://docs.handsontable.com/0.24.1/demo-conditional-formatting.html

There's an example how to add a class with a table renderer.

**Comment by lesonunique** [comment]
Thank you for your reply.

But this tutorial is for the renderer table, but is it possible to do this later ? Changing class of this or that existing row ?

Thank you.

**Comment by AMBudnik** [comment]
Hi @lesonunique 
You can also add classes using metaData like described in this post: https://github.com/handsontable/handsontable/issues/3187
