### ISSUE TITLE
Wrong time in date cell type

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3360]
Demo: http://jsfiddle.net/9ortuod5/
Time in date cell is replaced by `12:00` after a double click.

**Comment by manjits1991** [comment]
I have removed the following code from the js file and its working fine now.

this.originalValue ? (t = this.originalValue, _(t, o, !0).isValid() && this.$datePicker.setMoment(_(t, o), !0), s || i || this.setValue("")) : this.cellProperties.defaultDate ?
                    (t = this.cellProperties.defaultDate, r.defaultDate = t, _(t, o, !0).isValid() && this.$datePicker.setMoment(_(t, o), !0), s || i || this.setValue("")) : this.$datePicker.gotoToday();

**Comment by jansiegel** [comment]
This problem was caused by Pikaday, which replaced the time from the cell with `12:00 AM` in their `setToStartOfDay` method when opening the editor.
The workaround was to replace their changes with the initial cell value.
