### ISSUE TITLE
Resize handle becomes Move handle after move and updateSettings()

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#3361]
I am doing something very specific, and I wish I could narrow it down to something more simple, but it does seem to be a bug within Handsontable as I don't think a move handle should ever appear on the left side of a column border:

![screen shot 2016-03-30 at 4 46 19 pm](https://cloud.githubusercontent.com/assets/6276072/14157325/83abea9c-f698-11e5-91a3-d78c2b1fe218.png)

I have a specific (historical) need in my application to maintain the columns and order visible in the table.  This means when a column is moved by the user, I am reordering the column data to match that manual move and resetting them on the table with `updateSettings()`.  Along with that I am also resetting the `manualColumnMove` and `manualColumnResize` properties in the `updateSettings()` call.

However, now I am seeing a problem where after a manual move by the user, the user cannot resize that moved column.  The resize handle on that column unexpectedly becomes a move handle, and that column has two move handles (one on left border and one on right).

Here is a jsfiddle to demonstrate what I am doing, and the problem that occurs: http://jsfiddle.net/cgatesman/kp5va97e/

**Comment by krzysztofspilka** [comment]
Hi @cgatesman, I tried to reproduce the problem but without success.

https://i.gyazo.com/49553388e86068476fd8fd5b6572a7ac.gif

What am I doing wrong? In my case the resize handle is always on the right hand side.

**Comment by AMBudnik** [comment]
I reproduced the issue.

What I did @krzysztofspilka
1. Moved the column `B` after column `C` 
2. Tried to expand column `B`

result: missing resize handle.

**Comment by AMBudnik** [comment]
Hi @cgatesman 
As we've changed some parts of code related to `manualColumnMove` in 0.28.1 can I ask you to check how this code behaves now? I've tried to replicate the same behavior as before but I'm not even able to do the first step with moving the column `B`

**Comment by AMBudnik** [comment]
I have simplified the demo http://jsfiddle.net/tva87psh/ and still was not able to replicable the issue.
I am closing this topic as there is no additional feedback for a long time.

**Comment by cgatesman** [comment]
It took me a while to find where this was a problem in my project since this is so old.  After tracking it down, I found that it doesn't appear to be a problem anymore with the newer HOT we're using.  Ok to close this.  Thanks.

**Comment by AMBudnik** [comment]
Thank you for the feedback @cgatesman
