### ISSUE TITLE
.htInvalid stays after data is deleted

### ISSUE THREAD

**Issue by FrankFang** [handsontable/handsontable#3362]
Steps to reproduce:
1. Generate a invalid cell, which has a className 'htInvalid'
2. Active the cell, and press `DELETE`
3. The 'htInvalid' class stays there but not be removed.

**Comment by AMBudnik** [comment]
Hi @FrankFang 
I couldn't reproduce it. I used http://jsfiddle.net/75vnvxn2/ and typed `a` into `year` column and 2nd line so the cell is `current` (as it's selected) and `htInvalid` 
![invalid](https://cloud.githubusercontent.com/assets/10757813/14169338/74626270-f727-11e5-9a06-57418de2050a.png)



When the cell is selected as shown above and i use <kbd>Delete</kbd> there's no `htInvalid` class and no content - as expected.
![deleted](https://cloud.githubusercontent.com/assets/10757813/14169334/6fcde856-f727-11e5-9861-4c7c3e822d53.png)

**Comment by FrankFang** [comment]
Yeah, you are right. Let me make a jsfiddle

**Comment by FrankFang** [comment]
You could reproduce it on this page: https://docs.handsontable.com/0.23.0/demo-dropdown.html

<img width="518" alt="screen shot 2016-04-04 at 15 59 40" src="https://cloud.githubusercontent.com/assets/839559/14241539/5a3c654e-fa7e-11e5-901f-9bbbde85d871.png">

**Comment by FrankFang** [comment]
Soory, I see why.  Empty string is invalid here.

**Comment by FrankFang** [comment]
BTW, how to make a dropdown cell, which accepts an empty string as valid?

**Comment by AMBudnik** [comment]
Hi @FrankFang I think that the easiest way is to add an empty string to your dropdown source like here http://jsfiddle.net/rgcLat0s/
