### ISSUE TITLE
Add possibility for overflow:hidden without adding scrollbar

### ISSUE THREAD

**Issue by kotmatpockuh** [handsontable/handsontable#3363]
If i set overflow:hidden to the parent element, my table will add a scrollbar. Is it possible to switch it off?

Btw: I want to implement custom scrollbar...

**Comment by AMBudnik** [comment]
Hi @kotmatpockuh 
I think that our new blog post could come handy: https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable please take a minute to check it. There are also tips how to implement the solution to your grid.

**Comment by kotmatpockuh** [comment]
@AMBudnik, thank you

**Comment by kotmatpockuh** [comment]
_"2. Fixed height only (Coming soon)"_ - @AMBudnik any planed date?

**Comment by AMBudnik** [comment]
Unfortunately there's no precise date yet. 
If you would like to track our current tasks please check our [trello](https://trello.com/b/PztR4hpj/handsontable-roadmap-2016)
