### ISSUE TITLE
Virtual rendering for columns doesn't seem to work

### ISSUE THREAD

**Issue by samsonkhisty** [handsontable/handsontable#3364]
Inspect element shows all the columns are still added in the DOM. 
https://jsfiddle.net/fuggfuggfugg/jsbamwfd/

**Comment by AMBudnik** [comment]
Hi @samsonkhisty 
Handsontable triggers virtual rendering if there are more columns than visible + defined by [viewportColumnRenderingOffset](https://docs.handsontable.com/0.24.1/Options.html#viewportColumnRenderingOffset). When I changed your grid's width to `200px` it worked.

**Comment by samsonkhisty** [comment]
That's correct. I think I have just enough columns outside the viewport so it is rendered as extra columns.
