### ISSUE TITLE
Handsontable does not rerender upon resize

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#3365]
If you have a Handsontable defined with `stretchH='none'` within an `overflow: auto;` div, it will not rerender as that div grows showing the columns which had overflowed and should now be visible.  Both `stretchH='last'` and `stretchH='all'` will.

This is easily demonstrated in this jsfiddle by increasing the width of the pane where the Handsontables are shown:  http://jsfiddle.net/cgatesman/xc57sdcq/

**Comment by AMBudnik** [comment]
Hi @cgatesman 
As I'm assuming that we are both thinking about the state where we resize a window and the first instance stays the same until it is dbl-clicked? (Making it cut when shrinking the window and making it too narrow while extending the window's body)

**Comment by cgatesman** [comment]
Yes, I believe so.  I'm not sure about the double click part.  It appears different things will trigger it to render back out to the correct width--like scrolling up and down.

**Comment by AMBudnik** [comment]
The fact is that when we comment `stretchH='none'` we get the same behavior - if I'm wrong here please correct me - and like Krzysztof wrote here https://github.com/handsontable/handsontable/issues/3139 it's very likely a responsivity issue.

**Comment by cgatesman** [comment]
You get the same behavior if you comment out `stretchH='none'`, because `stretchH='none'` is the default setting for Handsontable.

**Comment by AMBudnik** [comment]
Yes, that is correct @cgatesman and that's why I allow myself to change the title to:
`Handsontable does not rerender upon resize`

**Comment by nadim** [comment]
Any update? 

We are currently using stretchH='all' to skirt this issue but I really want the default (stretchH='none'). I see that this is low priority but this type of behaviour looks broken to an end-user.

**Comment by AMBudnik** [comment]
Hi @nadim it has a low priority as we do not consider Handsontable as a responsive library. Currently, it uses fixed pixel values to calculate its size.

**Comment by nadim** [comment]
Is there an event I can listen for and tell the hot instance to redraw as opposed to using stretchH='all'?

This normally works fine but when there are only a few columns (or even 1 column) things get too stretched.

**Comment by AMBudnik** [comment]
I would recommend using [resize ](https://developer.mozilla.org/en-US/docs/Web/Events/resize) event.

**Comment by nadim** [comment]
In case this helps anyone else:
We keep stretchH to the default value and then call the render() method in the browser resize event handler. Throttled as described here:
https://developer.mozilla.org/en-US/docs/Web/Events/resize

**Comment by AMBudnik** [comment]
Behavior stays the same in v0.35.0

**Comment by swistach** [comment]
Hi @karellm,
An issues #3365, #3433 and #3869 are related to each other.
I think the fix for #3433 will solve this issue too.
