### ISSUE TITLE
HTML renderer if data contains an HTML table cell selection does not work

### ISSUE THREAD

**Issue by barelyfitz** [handsontable/handsontable#3366]
When using renderer:'html', if the data contains an HTML table element, it displays correctly in the handsontable cell. However, when you attempt to select the cell, if you click on one of the table's TD elements, it messes up the handsontable logic for selecting the cell, and the row/column numbers are incorrect, leading to the wrong cell being selected (or a javascript error occurring).

As shown in the following fiddle:
http://jsfiddle.net/patmfitz/5yag8c1m/24/

![handsontable](https://cloud.githubusercontent.com/assets/185461/14188654/b0f1c4ee-f757-11e5-9a59-818da3aaadeb.png)

**Comment by AMBudnik** [comment]
It seams that it's using your table created inside of a `1, 0` cell as it was actually equal to Handsontable's cells. That's an interesting case. Thanks for sharing @barelyfitz

**Comment by barelyfitz** [comment]
Yes, it looks like it gets the click event then tries to find the closest parent that is a table cell, and gets the cell coordinates from that by mistake. Probably just needs to check that it actually found the table cell used by handsontable and keep on moving up if not.

**Comment by AMBudnik** [comment]
Also please check this demo: http://jsfiddle.net/2wfyLvch/
If we we add new child to Handsontable's parent element table loses it's abilities (like selection/sorting etc)

**Comment by krzysztofspilka** [comment]
Connected with #3565
