### ISSUE TITLE
bindRowsWithHeaders generates inconsistent row headers

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3367]
When using the `bindRowsWithHeaders` plugin with no data source defined, all the row headers contain `1`, or `NaN` and `1` in a different scenario.
- https://jsfiddle.net/Lkpfq3jc/
- https://jsfiddle.net/Lkpfq3jc/1/

**Comment by AMBudnik** [comment]
Still present in 1.9.1 https://jsfiddle.net/handsoncode/dtLjo12L/

**Comment by AMBudnik** [comment]
Works the same in version 1.15.1

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by adamdehaven** [comment]
Issue is still present in version `7.0.3`

**Comment by swistach** [comment]
Fixed in v8.

**Comment by swistach** [comment]
Hi @adamdehaven,
we fixed this issue in v8: https://jsfiddle.net/e35sbokt/
