### ISSUE TITLE
Cannot change data in hidden table

### ISSUE THREAD

**Issue by jbthomps** [handsontable/handsontable#3369]
I have a process where the data in a table can be replaced (from uploading a new file with data) while it is invisible.  It works as I would expect if I am looking at the grid's initial visible area, but when I scroll off of the initial start area and leave my view in another part of the grid, then hide the grid and replace data, I get 'Cannot read property 'contains' of undefined' in the _hasClass function.

If I make the grid visible at all times, I never receive this error, even when I navigate from the starting visual area.

My solution to a problem like this before was to forcibly navigate the grid to 0,0 before I replaced the data, but even this is not working.  

I am placing and manipulating the grid through [nghandsontable](https://github.com/handsontable/ngHandsontable) if this has any impact.

**Comment by AMBudnik** [comment]
Hi @jbthomps 
Please create a demo (using for example JSFiddle/JSBin/CodePen). It's hard to understand and investigate the issue without a source code.

**Comment by AMBudnik** [comment]
Issue will stay closed till an authors reply.
