### ISSUE TITLE
colHeaders in 0.7.5 and row selection in 0.8.1

### ISSUE THREAD

**Issue by frvade** [handsontable/handsontable#337]
Hi.

First of all, I want to say that you made a great job, this awesome plugin helped me a lot in my project. And thank you that you continue to work on it and improve it.

I used 0.7.5 during all my development and only one feature I missed was reordering rows. So I made it based on default row selection functionality and it worked fine. But when I tried to use custom header renderer I realized that it doesn't work and I couldn't find it in source. So then I found out that new stable version was released and downloaded it. Custom html worked well but now I can't select row by clicking on row header or column by clicking on column header.
So my question is either how to make custom header renderer functionality work on 0.7.5 or how to get back row and column selection functionality in 0.8.1?
Thanks in advance.

**Comment by AMBudnik** [comment]
Hi @provegard 
Could you check the latest version? I'm not sure if I understand the concept here.

**Comment by provegard** [comment]
The thing is that prior to some version, it was possible to select an entire column by clicking on the column header, and similarly for rows, but that behavior was subsequently removed. I can confirm that it works in the latest version though, so I suppose this issue can be closed.

**Comment by AMBudnik** [comment]
Thanks for prompt reply and confirmation.
I'm closing this issue.
