### ISSUE TITLE
Improve forced reflow and layout

### ISSUE THREAD

**Issue by samsonkhisty** [handsontable/handsontable#3370]
![screen shot 2016-04-01 at 4 27 44 pm](https://cloud.githubusercontent.com/assets/3254606/14219234/3445c2f8-f827-11e5-8791-078a4aca4ea0.png)

**Comment by jansiegel** [comment]
Hi, @samsonkhisty. Do you experience performance problems while doing anything specific? If you could help us pinpoint a specific usecase, it would be easier for us to work on optimizing the code in that areas.

**Comment by toroc** [comment]
I'm experiencing the same thing with HOT 0.31.2. I have two data grids in separate tabs, and as I switch between the grids, I am seeing a delay.

![screen shot 2017-08-01 at 12 06 41 pm](https://user-images.githubusercontent.com/9097432/28842347-29903f68-76b2-11e7-8952-4dd9e5dae479.png)
![screen shot 2017-08-01 at 12 07 10 pm](https://user-images.githubusercontent.com/9097432/28842350-2eee6390-76b2-11e7-8c62-b68f01dce2f1.png)

**Comment by swistach** [comment]
Calculations in viewport.js definitely needs to be improved. Currently in one cycle we run many times the same part of code. Maybe is possible to cache them partially.

**Comment by AMBudnik** [comment]
The issue has been redirected to the [Wiki section / Improvement suggestions(https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

**Comment by AMBudnik** [comment]
Since the report, we have significantly enhanced the library and the following issue should not continue to happen.

@samsonkhisty, have you switched to Handsontable v8+, and can you confirm?

**Comment by AMBudnik** [comment]
I'm closing the issue as there is no additional feedback. But I'm opened to a discussion on https://github.com/handsontable/handsontable/discussions or by email at support@handsontable.com
