### ISSUE TITLE
When the number of columns is different, data is not displayed all.

### ISSUE THREAD

**Issue by IDLOCKED** [handsontable/handsontable#3372]
The number of the biggest columns seems to be fixed to a top rows.
[sample1](http://jsfiddle.net/wnv17dxL/)
However, data is not displayed all when there was a row with the number of the biggest columns on the way.
[sample2](http://jsfiddle.net/wnv17dxL/1/)
Even if my hope varies in the number of the columns, I want to display all data.

Is this a specification?
Or is it a bug?

**Comment by wojciechczerniak** [comment]
We've discussed this and we're not going to change the logic. Works as intended.

You can set the array length for the first row or configure `columns`. Those are the most efficient options and recommended by us.
