### ISSUE TITLE
Autocomplete not working properly after selecting value in dropdown inside other handsontable

### ISSUE THREAD

**Issue by arekdygas** [handsontable/handsontable#3374]
Hello,

I have two handsontable instances with dropdown cell in the first one and autocomplete in second.

After selecting a value in dropdown, and then clicking on autocomplete and typing some text, autocomplete values are not filtered after first character. If, between using dropdown and autocomplete, I click another cell, everything works as expected. If both cells are inside the same handsontable, everything works correctly as well.

I did some research, and I believe the problem is related to an order of event resolving. When clicking autocomplete cell, _beforeKeyDown_ event handler has _skip_ property set to _false_, but then closing event of dropdown editor is being fired, which sets _skip_ to _true_.

JSFiddle sample: http://jsfiddle.net/j3yjua55/

Way to reproduce:
1. Select any value from A1 in first table.
2. Click on A1 in second table.
3. Type _aa_

Expected: only values containing _aa_ should be displayed in dropdown.
Actual: all values containg _a_ (first entered letter) are displayed

Best regards,
Arek

**Comment by AMBudnik** [comment]
Thank you @arekdygas I reproduced the issue.
When we open an autocomplete before typing `aa` autocomple's wotking as expected.

**Comment by arekdygas** [comment]
When in above example I change first cell type to autocomplete, then another problem occurs: after entering some text into 1st autocomplete, I'm unable to type at all in 2nd one.

**Comment by phoenix-down** [comment]
I'm running into the same problem. Any updates on this?

**Comment by AMBudnik** [comment]
@phoenix-down we do not have any updates on this issue yet.

**Comment by AMBudnik** [comment]
It works the same in [v 5.0.1](http://jsfiddle.net/abczq17L/)

**Comment by wojciechczerniak** [comment]
5.0.2-RC demo: http://jsfiddle.net/sv1okjqr/ 👍

**Comment by AMBudnik** [comment]
@arekdygas @phoenix-down please update to 5.0.2
The issue got solved
