### ISSUE TITLE
ISO8601 test does not work if you in another time zone

### ISSUE THREAD

**Issue by Laplandia** [handsontable/handsontable#3375]
```
timeValidator:: correctFormat:: should rewrite the string to the correct format if a time in ISO8601 format is provided: failed
  Expected '15:40:04' to equal '13:40:04'. (2)

```

**Comment by AMBudnik** [comment]
Hi @Laplandia 
Please track changes to https://github.com/handsontable/handsontable/issues/3338 as it's about the same case.
The mentioned issue is ready to be merged so it is highly possible it gets to next release.

**Comment by Laplandia** [comment]
This problem is still reproducible in the new release (0.24.2) where #3383 is fixed.

**Comment by AMBudnik** [comment]
Oh sorry, my bad. I'll reopen this issue.

Thanks for a pull request.

**Comment by Laplandia** [comment]
I have mentioned wrong pull request here. I meant issue 3338. https://github.com/handsontable/handsontable/issues/3338

This pull request is actually for another issue. But yes, the problem is still reproduced.

**Comment by jansiegel** [comment]
@Laplandia Correct me if I'm wrong - it's a problem with the tests only, the functionality works fine?
When we're providing a timestamp, it points to a specific moment in time, so the resulting time value will be different depending on the timezone. Similarly when we provide a full ISO date-time.

**Comment by Laplandia** [comment]
@jansiegel sorry for the late reply. Yes, you are right.
