### ISSUE TITLE
Slow in IE8 to IE 11 #1772 it is not fixed but showing closed

### ISSUE THREAD

**Issue by sambsa** [handsontable/handsontable#3376]
This issue still persists. Not fixed. Kindly fix it. **I am using latest handsontable-0.24.1**. My table has 150 rows and 5 columns. In IE it is very slow to scroll down. Insert value in cell also taking lot of time. please fix it.

If fixed please suggest me how to fix it.

**Comment by AMBudnik** [comment]
Hi @sambsa 
Please do not duplicate issues.
I just post a new comment on the same issue (where you left yours) at https://github.com/handsontable/handsontable/issues/1772

**Comment by sambsa** [comment]
ok. When will it reflected buddy? I am working on mission critical task and it will need IE support.

**Comment by AMBudnik** [comment]
Did you already tried tips from https://docs.handsontable.com/0.24.1/tutorial-performance-tips.html?
Can you share a code where I can replicate the performance issue?

**Comment by sambsa** [comment]
will try it thanks for the suggestion.
