### ISSUE TITLE
Is there any way to add custom button below the table?

### ISSUE THREAD

**Issue by ishara** [handsontable/handsontable#3377]
I am going to create custom widget using handsontable, is there any way to add custom button panel to the component?
thank you.

**Comment by AMBudnik** [comment]
Hi @ishara 
You want to add a button panel below Handsontable container or inside of it?
First case is easy - second could be little tricky.

When you're creating a panel outside of the container be sure to add `outsideClickDeselects: false` to your instance's settings if you would like to perform an action for selected cells.
