### ISSUE TITLE
How to get comments from handsontable throught API

### ISSUE THREAD

**Issue by menes127** [handsontable/handsontable#3378]
Hi, when I add some comments in handsome table, how to get the comments through API. I cannot find any api about getting the comments. please give me some advice.
refer to https://docs.handsontable.com/0.24.1/demo-comments_.html

**Comment by AMBudnik** [comment]
Hi @menes127 
Please check this issue: https://github.com/handsontable/handsontable/issues/1974
If you would have any other questions/suggestions please also share then via https://github.com/handsontable/handsontable/issues/1974 topic
