### ISSUE TITLE
isImmediatePropagationEnabled in beforeKeyDown hook doesn't work, when using IE11 and multiple HOT setup

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3379]
When using IE11, and there are multiple HOT instances on the page, this code:

``` js
beforeKeyDown: function(e) {
    if (e.ctrlKey && e.keyCode === 88) {
        e.isImmediatePropagationEnabled = false;
        e.preventDefault();
    }
},
```

doesn't prevent cutting from the tables.

**Comment by AMBudnik** [comment]
Demo: http://jsfiddle.net/handsoncode/ttg7mun5/

<kbd>CTRL</kbd> + <kbd>X</kbd> is blocked for the first instance, but it's not blocked for the second.

**Comment by AMBudnik** [comment]
Still present in 0.31.1 - we are not able to stop checkbox from being checked with an <kbd>ENTER</kbd> key.

Example: http://jsfiddle.net/handsoncode/wh1mvr9b/

**Comment by AMBudnik** [comment]
The issue is still replicable in v `2.0.0` and seems to work this way from the beginning.

**Comment by AMBudnik** [comment]
I've tested version 8.0.0-beta2-rev18 using native Internet Explorer 11 on Windows 10 and Chrome 83 for comparison.

a single instance
* Chrome - cut blocked - OK
* IE - cut blocked - OK

two instances
* Chrome - cut blocked - OK
* IE - cut blocked - OK

but it is also working well in 7.4.2 so we can close the issue as solved.
