### ISSUE TITLE
Problem with dropdown on IE

### ISSUE THREAD

**Issue by mfandre** [handsontable/handsontable#3380]
Look this https://jsfiddle.net/0whe7d89/4/

Drag some rows to create more items. In a new row, select the dropdown column (C), not open the dropdown just mark as selected. Now press key 'H' (key for an existing item for autocomplete). You will see in Developer Console the error "This method cannot be called because this Handsontable instance has been destroyed".

I dont understand why this probelm occurs, and happens only in IE I cant reproduce in Chrome.

I think this is related with #3076 .

Thx in advance!

**Comment by AMBudnik** [comment]
Hi @mfandre 
I was working on IE 11/ Win 8 and did get the console errow. What's your system?

**Comment by mfandre** [comment]
IE11 windows 7!

You need to press H or ENTER in a new row created by drag items...

**Comment by AMBudnik** [comment]
OK, thanks for details. We'll check it.

**Comment by mfandre** [comment]
Look this video https://www.youtube.com/watch?v=S0wmcOk2aUg , Im simulating the problem...

**Comment by AMBudnik** [comment]
Thank you for your effort but It's hard to see anything. I can recommend using a lightweight [liceCap](http://www.cockos.com/licecap/) software which serves a .gif file that can be easily served via Github.

ps. I shared this post with our developers - they will check it tomorrow.

**Comment by mfandre** [comment]
Check in 1080p.

**Comment by swistach** [comment]
Hi @mfandre 
I confirmed tat there is a bug.
Thanks for reporting this issue.

**Comment by mfandre** [comment]
Can you send me the commit for I alter my JS when you finish?

**Comment by AMBudnik** [comment]
Hi @mfandre 
We'll share the solution as soon as it's ready.

**Comment by jaredbaszler** [comment]
I just ran into the same bug.  Win10, IE11.212.10586, HOT v.24.3.  FYI - Our current live website is running HOT v.16.1 and the bug is showing up there as well.

**Comment by sanalkr** [comment]
I am also facing the same issue with autocomplete and dropdown types. Win7 IE 11, HOT 0.24.3

**Comment by AMBudnik** [comment]
Hi @sanalkr 
Can you guide on how to reproduce this bug? I tried Win8 /IE11 like below (with no success)
![bug](https://cloud.githubusercontent.com/assets/10757813/16408467/36350a42-3d19-11e6-8213-fbc0e4f12265.gif)

**Comment by sanalkr** [comment]
Hi @AMBudnik ,

Steps to reproduce the bug

1. Click on the cell and open dropdown
2. Press Esc to cancel the dropdown
3. Now type something in the cell
![bug](https://cloud.githubusercontent.com/assets/20180412/16409942/b569f68c-3d3d-11e6-8061-f3e1cfc05a85.gif)

**Comment by AMBudnik** [comment]
thank you @sanalkr 
I've reproduced the bug.

**Comment by sanalkr** [comment]
welcome @AMBudnik 
Hope we get a solution soon.

**Comment by AMBudnik** [comment]
Hi @mfandre after a long investigation we have finally fixed the this bug.
It works for you as well?

**Comment by mfandre** [comment]
I Will check!

A ter, 8/11/2016, 12:19, Aleksandra Budnik <notifications@github.com>
escreveu:

**Comment by AMBudnik** [comment]
Thanks mate. I appreciate.

**Comment by AMBudnik** [comment]
@mfandre I'm closing this issue but feel free to leave a comment if still something ain't right.
Thanks!
