### ISSUE TITLE
is there any AngularJS2 directive for Handsontable?

### ISSUE THREAD

**Issue by ishara** [handsontable/handsontable#3382]
Hi 
I am looking for directive or component to work with angular2 project.

Is there any project going on?
Is there any DefinitelyTyped reference for Handsontable?

Thank you

**Comment by AMBudnik** [comment]
Hi @ishara 
Angular 2 support is one of our ideas for Q3 and Q4
Please track our ngHandsontable release notes: https://github.com/handsontable/ngHandsontable/releases for updates.

**Comment by renehamburger** [comment]
@AMBudnik, FYI: I've just update https://github.com/valor-software/ng2-handsontable to Angular 2.4.

**Comment by AMBudnik** [comment]
Thanks for sharing @renehamburger 
we are still planning to add an official Angular 2 wrapper, [maybe in Q2 2017](https://trello.com/c/CYZ6jqrQ/105-new-wrapper-angular-2).
