### ISSUE TITLE
Browser crashes when pasting rows from Google Sheets

### ISSUE THREAD

**Issue by dixso** [handsontable/handsontable#3385]
Hi,
Browser crashes when pasting rows with a large number of columns but only when "manualColumnMove" is enabled.

Example:
http://jsfiddle.net/dixso/Lp4qn55v/152/

Demo:
https://www.dropbox.com/s/xzccj8gz0yj55fv/excel_to_handsontable.mov?dl=0

**Comment by AMBudnik** [comment]
Confirmed, my Chrome got jammed.
Thanks for sharing @dixso

**Comment by krzysztofspilka** [comment]
@dixso @AMBudnik Definitely a bug, but it works fine if you focus on cell A2 instead of selecting the whole row. I would say it's important to fix it in the next release (April 20).

**Comment by swistach** [comment]
commit: https://github.com/handsontable/handsontable/commit/8ed4e56c1e72fc49304c6c09785ac30c3bc25dbb
