### ISSUE TITLE
Unable to reset columns widths after manual column resize

### ISSUE THREAD

**Issue by lubianm** [handsontable/handsontable#3386]
I'm experiencing an issue (I think starting from version 0.22.0, but I'm not sure) when trying to programmatically reset columns' widths AFTER having manually changed columns' widths (because on my instance I have _manualColumnResize_ plugin enabled). The only way I've managed to achieve the expected result is to disable the _manualColumnResize_ plugin before launching the _updateSettings_ (that changes _colWidths_), and re-enable it after _updateSettings_ execution. Anyway:
1. Is this the (new) expected behavior ?
2. Is there a simpler way to achieve the same result ? I have seen, for example, that there is a new method called `clearManualSize(column)` that could fit my needs, but as I can see it is not available at hot instance level, is it possible to access it in some ways ?
Here https://jsfiddle.net/kh7u3mgr/ is a jsfiddle with an example of my issue

**Comment by AMBudnik** [comment]
Hi @lubianm 
I have to admit that I'm not fully aware of what you would like to achieve here.

You would like to reset columns widths after some column gets resized?
Please check this demo: https://jsfiddle.net/kh7u3mgr/2/ - I think it'll suit your needs.

**Comment by lubianm** [comment]
Hi, no, actually what I want to achieve is to set columns widths to a specific value (in my example, I want to set second column's width to 50 pixels) also AFTER having manually resized it.

**Comment by AMBudnik** [comment]
Then you can use `colWidths: [array of widths]` like `colWidths: [100, 50]` performed inside an [afterColumnResize](https://docs.handsontable.com/pro/1.3.3/Hooks.html#event:afterColumnResize) hook.

**Comment by lubianm** [comment]
No, maybe I did not explain well... The two actions (manually resizing the column and resetting its width to a specific value), are not executed in sequence (one following the other), but in 2 different moments. So, FIRST I need (users to be able) to manually resize column and then (when users decide to restore initial value) to trigger a width restore.

**Comment by AMBudnik** [comment]
I see. So the best way as far as I'm concerned is the one you are already using in the first provided demo.

**Comment by lubianm** [comment]
Ok, are you going to include some shorter way to obtain the same result (an ad-hoc function for example), or let _updateSettings_ on colWidths to set widths to specific values without the need of disabling/enabling manualColumnResize (as it was on previous Handsontable versions) ?

**Comment by AMBudnik** [comment]
I think it's a good idea to reconsider. I will leave this subject for the future planning.

**Comment by budnix** [comment]
Hi @lubianm, I think that Handsontable already supports resetting `ManualColumnResize` state. You should pass an empty array to reset state of that plugin like in this updated demo https://jsfiddle.net/kh7u3mgr/3/.

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/3594

**Comment by Alex-ley-scrub** [comment]
seems like this is the best way to do it:
```ts
const plugin = hotInstance.getPlugin("manualColumnResize");
// plugin.clearManualSize(idx);
if (plugin.isEnabled()) {
    plugin.setManualSize(idx, 80);
} else {
    hotInstance.updateSettings({ colWidths: [80, 100] });
}
```

**Comment by adrianszymanski89** [comment]
Hi @Alex-ley-scrub 

I checked your proposed solution, but it seems that it's not working: https://jsfiddle.net/handsoncode/xwa6d0bj/. Can you modify this example to show how it should be implemented?
