### ISSUE TITLE
Pasting two or more rows with filters enabled [PRO]

### ISSUE THREAD

**Issue by dixso** [handsontable/handsontable#3387]
Hi,
Pasting two or more rows with filters enabled (Handsontable PRO)

Note:
- First row with readonly 
- Second row without readonly

Example:
http://jsfiddle.net/dixso/duL6rpyp/1/

Demo:
https://www.dropbox.com/s/qg73io2zkvws7qj/paste_filters.mov?dl=0

**Comment by AMBudnik** [comment]
Hi @dixso 

we have tested the example but the demo doesn't work (from the dropbox). We have changed the readOnly handling via meta data so maybe the issue doesn't occur any more.

Please update to 0.31.0 and let me know if it's still there.

**Comment by AMBudnik** [comment]
I am closing this issue as the description in not precise and the video link is deprecated
