### ISSUE TITLE
Contextmenu item.visible is not implemented

### ISSUE THREAD

**Issue by frankhommers** [handsontable/handsontable#3388]
In the docs ( https://docs.handsontable.com/0.24.1/demo-context-menu.html ) there is a link to the jQuery context menu ( http://medialize.github.com/jQuery-contextMenu/docs.html ).

I was hoping that therefore I could use the .visible property of a menu item, but that doesn't seem to be available. Are there other ways?

**Comment by noahtaylor** [comment]
@frankhommers did you find a solution to this?  I am also seeing the same issue.

**Comment by jansiegel** [comment]
You're probably looking for the `hidden` property. You're right though, I don't think the link to the jQuery context menu should be there anymore, as I don't think we're 100% compatible with their API.

As for the `hidden` property, take a look at this example and let me know if that's what you're looking for: http://jsfiddle.net/js_ziggle/xx58hha6/

**Comment by frankhommers** [comment]
Yes that's what I was looking for. I ultimately solved it by using different context menu's and calling the one I needed ;-)

**Comment by frankhommers** [comment]
I still think that you need to remove the link to the jQuery Context Menu. As @jansiegel suggested.
