### ISSUE TITLE
Missing 'beforeRenderer' hook

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3389]
Just like title says there is a missing `beforeRenderer` hook which can by helpful for preparing (adding/removing) cell meta properties or other actions before cell is being rendered.

**Comment by krzysztofspilka** [comment]
@budnix just don't forget to check if that appeared in the final docs.

**Comment by toburger** [comment]
It would be nice if there exists the possibility to cancel a rerendering.
For example if the function would return a boolean value to indicate that no rendering is required. This would speed up large tables, especially with custom rendering logic.
If you consider the following (very naive) example: http://jsfiddle.net/s7c22knw/1/ every cell rerenders its content, even if the value doesn't change.
The render function in this example is very simple, but if the functions involves a more complicated rendering it can take some time to render the full table.

**Comment by AMBudnik** [comment]
@toburger [here ](https://github.com/handsontable/handsontable/issues/2152)we discussed the case when we want to change a single cell and call the renderer only for this cell (not for a whole table)
That issue is marked as an improvement suggestion.

**Comment by toburger** [comment]
Oh, thanks for the hint!
