### ISSUE TITLE
Disable auto-scrolling after using fill-handle on multiple selection

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3390]
It's more an annoying behavior than a bug. The table shouldn't take us to the first column when using auto-fill on multiple cells.

**Steps to reproduce:**
1. Go to http://jsfiddle.net/js_ziggle/t08mbs0s/
2. Select A1:T1 (or the entire first row by clicking on a header)
3. Scroll to the last column and use a column fill handle to propagate the data.
   Result: the table is being automatically scrolled to the first column. Start from column B2 and the table will work fine.
## 

Chrome (latest)
Windows 8.1

**Comment by AMBudnik** [comment]
Still present in 0.31.0

**Comment by AMBudnik** [comment]
Issue seems to be fixed in version 0.35.0
Updated demo http://jsfiddle.net/2vthf0ut/
