### ISSUE TITLE
i want to set cell background color.

### ISSUE THREAD

**Issue by wayne-kim** [handsontable/handsontable#3392]
user input data at handsontable and if the Mytable has the same data then i want to set cell background color.
--------------------My code-----------------------------------------------------
var test = $("#exampleGrid").handsontable("getCell", i, k, false);
$(test).css("background-color","#ec3341");
$(test).css("color","#ffffff");
------------------------------------------------------------------------------------
it is work but has a fault. if i click other cell, The to be changed color cells are to be original color.
....
i want to keep color. how can i keep background color of cells?

**Comment by AMBudnik** [comment]
Hi @wayne-kim 
Currently the best way to style Handsontable is to use custom renderers. Here's https://docs.handsontable.com/pro/1.3.3/demo-conditional-formatting.html a freat tutorial how to style values.
