### ISSUE TITLE
ManualColumnFreeze crashes dropdown cell

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3393]
Demo: http://jsfiddle.net/fcr4dw92/4/

Scenario:
1. Freeze dropdown column (`D` column)
2. Try to choose an option from a drodown menu

Result:
Dropdown list is not closing..

**Comment by swistach** [comment]
In latest (0.28.0 / 1.7.0) version this bug isn't present.
http://jsfiddle.net/fcr4dw92/6/
