### ISSUE TITLE
Autocomplete focus onkeydown doesn't work after migrating from 0.24.1 to 0.24.2

### ISSUE THREAD

**Issue by ignaciomdominguez** [handsontable/handsontable#3396]
Up to version 0.24.1,in autocomplete columns, after writing some letters if I press the down arrow key the focus was set on the drop-down list. After migrating to version 0.24.2 this is no longer possible.
Thanks. Martin

**Comment by AMBudnik** [comment]
Hi Martin,

I wasn't able to reproduce the issue with https://docs.handsontable.com/0.24.2/demo-autocomplete.html
Do you experience it there? If so please provide your OS/Browser information

**Comment by ignaciomdominguez** [comment]
I found why this happend. I use a custom renderer instead default AutocompleteRenderer.
Custom renderer is used to change background style.
