### ISSUE TITLE
typescript typings error

### ISSUE THREAD

**Issue by dcsan** [handsontable/handsontable#3397]
It looks like maybe the typings file is out of date? Or at least some options havent been added, speciailly the `dropdownMenu`

![image](https://cloud.githubusercontent.com/assets/514002/14479678/b406e0d2-0153-11e6-8711-f03f35d16da0.png)

**Comment by krzysztofspilka** [comment]
@dcsan thanks for the heads up. We've just added the definitions file, apparently it needs our further attention.

**Comment by dcsan** [comment]
let me know here when/if you update it, very useful to have.

**Comment by dcsan** [comment]
if you tell me @krzysztofspilka where to find the file maybe I could make the mod and send you a PR...

**Comment by swistach** [comment]
Hi @dcsan,
We've updated definitions in DefinitelyTyped repo (https://github.com/swistach/DefinitelyTyped/tree/master/handsontable). We've added options and methods of pro version.

**Comment by dcsan** [comment]
hi I updated typings for this (I think, though their `--ambient` system is pretty confusing)
and still getting an error.

```
[~/dev/rikai/boteditor]$ typings ls                                                                                                        [master] 
typings WARN deprecated 4/19/2016, 11:39:17 AM: "registry:npm/universal-analytics#0.3.10+20160305201939" has been deprecated
typings WARN deprecated 5/6/2016, 1:29:21 AM: "registry:dt/node#4.0.0+20160412142033" has been deprecated

├── universal-analytics@^0.3.10
├── handsontable (ambient)
├── mocha (ambient)
└── node (ambient)

[~/dev/rikai/boteditor]$ typings install handsontable                                                                                      [master] 
typings ERR! message Unable to find "handsontable" for "npm" in the registry. Did you want to install ambient typings with the ambient flag? If you can contribute these typings, please help us: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/npm/handsontable/versions/latest responded with 404, expected it to equal 200

typings ERR! cwd /Users/dc/dev/rikai/boteditor
typings ERR! system Darwin 15.4.0
typings ERR! command "/usr/local/bin/node" "/usr/local/bin/typings" "install" "handsontable"
typings ERR! node -v v5.9.1
typings ERR! typings -v 0.7.12

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
[~/dev/rikai/boteditor]$ typings install handsontable --ambient                                                                            [master] 
handsontable
└── (No dependencies)

[~/dev/rikai/boteditor]$ tsc                                                                                                               [master] 
public/components/training.ts(69,7): error TS2345: Argument of type '{ data: any; minSpareRows: number; rowHeaders: boolean; dropdownMenu: boolean; colHeaders: string...' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and 'afterChange' does not exist in type 'Options'.
```

**Comment by dcsan** [comment]
https://github.com/typings/typings/issues/485

I dunno if this is your bug, typings, or the procedure. submitted an issue there as well.

**Comment by dcsan** [comment]
still seems some properties are missing the 

public/components/training.ts(69,7): error TS2345: Argument of type '{ data: any; minSpareRows: number; rowHeaders: boolean; dropdownMenu: boolean; colHeaders: string...' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and 'afterChange' does not exist in type 'Options'.

**Comment by swistach** [comment]
I've added all hooks to 'Options' interface.
You can follow the merge progress on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9325
