### ISSUE TITLE
Floating (clone) headers not scrolling on certain dimensions

### ISSUE THREAD

**Issue by jperasmus** [handsontable/handsontable#3399]
Hey guys,

I've got a bit of a strange bug and it took me a while to reproduce, but have managed to reproduce now. The problem is that both the floating (cloned) column and row headers go out of sync with the master grid's scrolling. This seems to be related to specific grid heights + browser zoom level. 
- I know it sounds crazy, but that is what I have to deal with now for a client.

Attached is a quick screen recording to show the problem in action or you can view it [here](http://cl.ly/1u1w2T1P1g22)

![handsontable fixed headers problem](https://cloud.githubusercontent.com/assets/6787452/14490401/eaf344fe-0172-11e6-8d93-80e2ff248217.gif)

Here is the [jsfiddle](http://jsfiddle.net/1vqkf28x/) that I used to reproduce the problem on my MacBook Pro.

**My troubleshooting so far:**
- very difficult to consistently determine when it will work and when not; it is a combination of the grid height + the browser zoom level (on the jsfiddle screen recording I set the height specifically to 428 and zoomed my browser to 67%). Zoom browser first and then run the code.
- The heights that aren't working on Chrome seemed to work fine on Firefox (up until now I haven't reproduced the issue successfully on Firefox).
- Reproducable on Safari as well
- it seems like similar functionality like the mobile headers functionally is happening, but not 100% the same.
- I've had hit-and-miss success by forcing the update settings and then the headers would work again, but this doesn't work consistently, otherwise I would've just done that for now.
- reproducable on latest (0.24.2) and also defintely from 0.23.x I haven't tried it with previous releases.

**Possible workaround?**
Any suggestion for a possible workaround will be greatly appreciated. If there is a way for me to detect whether the scrolling isn't working, then I could update the height with 1px until it works. The way the scrolling actually works seems like voodoo magic to me, so without understanding 100% how it works I'm finding it hard to programmatically tell when it is not.

If there is any more info I can provide to help get this bug squashed I'd be more than willing to help.

**Comment by AMBudnik** [comment]
I guess it could something to do with this issue: https://github.com/handsontable/handsontable/issues/3118

**Comment by tedcurrent** [comment]
Any updates on this? I also noticed that when zooming, the fixed columns also get their own, very small, scrollbars. Can be easily produced with http://docs.handsontable.com/0.29.0/demo-fixing.html by simply zooming out. I'm on Windows 7 and Chrome if that makes a difference.

Any workaround for the said issues would also be ok.

**Comment by AMBudnik** [comment]
@tedcurrent 
unfortunately not yet. However there are few issues related

**Comment by swistach** [comment]
Hi @jperasmus, @tedcurrent.
Currently, headers follow scroll from the main table correctly. There is another problem, related to misalignment after zoom.
That issue is requested here: #3118.
Feel free to reopen, if you have still a problem with headers.
