### ISSUE TITLE
removing rows does not resize wtHolder

### ISSUE THREAD

**Issue by cfdude** [handsontable/handsontable#3401]
We use a button to 'Add Row' to a HOT instance which increases the row and the wtHolder, however when we right-click and 'remove row' the wtHolder remains at the same size calculation.  

This is especially troublesome on a long page with multiple HOT instances.

**Comment by AMBudnik** [comment]
Hi @cfdude 
Please create a demo where this issue can be replicable.

**Comment by AMBudnik** [comment]
Issue will be reopened with a demo/reply for the Author.
