### ISSUE TITLE
jQuery noConflict bug

### ISSUE THREAD

**Issue by nicebro** [handsontable/handsontable#3403]
Hi, i found issue in 0.24.2 version when using jquery in no conflict mode it throw Uncaught TypeError
http://jsbin.com/warujotaku

**Comment by AMBudnik** [comment]
Thanks for sharing @nicebro

**Comment by brendonlamb** [comment]
Great to find the bug report already made!

Same problem here in 0.24.3

![image](https://cloud.githubusercontent.com/assets/1816511/15074639/13f1c170-136e-11e6-97e1-1f9835ca046a.png)


I'm loading Handson to the admin area of WordPress using an enqueue and with jquery and jquery-migrate as dependencies. No problems with 0.24.1 or lower.

**Comment by TobiasBg** [comment]
#3511 deals with same problem. I contains a suggestion for a fix, basically simply replace `$` with `jQuery`.

**Comment by budnix** [comment]
This bug should be fixed in the upcoming release. [Patch](https://github.com/handsontable/handsontable/pull/3553) contributed by **@rkrx** was merged into develop.
