### ISSUE TITLE
How to get the row(rowIndex) which I have edited data

### ISSUE THREAD

**Issue by duskqlso** [handsontable/handsontable#3404]
![edited](https://cloud.githubusercontent.com/assets/18479179/14554908/442dc976-0322-11e6-9b60-298b26c9c2fa.png)
As the picture above
If I have to update data at certain row
How can I get the row(rowindex) ?

**Comment by AMBudnik** [comment]
Hi @duskqlso 
You can use a `beforeChange`/`afterChange` hook. They return a type of change and an array of changes.

To access changed row index you would need to refer to first element of a `source` array
Example: http://jsfiddle.net/handsoncode/hatjuu5s/

**Comment by duskqlso** [comment]
@AMBudnik 
According to the example you offered,I have solved my problem.
Thank you very much for helping~

**Comment by AMBudnik** [comment]
Great @duskqlso!
Glad I could help.
