### ISSUE TITLE
Unnecessary charset declaration in `handsontable.full.css`

### ISSUE THREAD

**Issue by wspurgin** [handsontable/handsontable#3406]
In version 0.24.2 (and since version 0.15.0-beta1), the charset declaration in the Pickaday plugin 
has existed. As @splitbrain pointed out in #2843, this is an unnecessary declaration as the default charset is UTF-8.

#2843 was opened in September of 2015, but no action was taken because no actual *problem* was ever reported due to the charset. Here I'll explain my use case where it **is** a problem to have this charset declaration.

Normally, Handson table css is imported at a the root level (like other external sass/css) like so:

```sass
// application.sass
@import handsontable.full

.custom-style
  ...
```

The charset declaration, however, **must** appear at the root level. In the above use case, because of where the `@import` appears, it *does* appear at the root level.

## My use case

I have an app that uses a few other frameworks in conjunction with Handson table. These other frameworks have styles that can conflict with Handson table. As such, I've typically imported Handson table under a specific containing class like so:

```sass
body.handson-table-enabled
  @import "handsontable.full"
...
```

In this way, the "selector specificity" of Handson table styles will take precedence\*. However, due to the charset declaration, the above import will produce an error (because the declaration will no longer be at the root level). While it could be argued that this approach is hackish to start with, I'd argue that using non-specific HTML tags instead of specific classes as part of styles is "lazy" to start with, but everybody does it anyway.... likewise, in every app I've ever worked on where there were multiple frameworks with multiple styles, this approach was used to increase the precedence of specific frameworks' styles.

Since the charset declaration is declaring the default charset anyway, it's superfluous. The only way I've solved this issue is by removing the charset declaration. You can always add a note in the readme instructions for anybody whose using something other than charset UTF-8 for stylesheets that UTF-8 charset is required.... though I've never encountered that myself.

\* This is not universally true, but in situations where styles reference HTML tags (like `th` or `.some-class table th` for instance) this method usually increase those styles' specificity enough to take precedence.

**Comment by wspurgin** [comment]
This might be more of a bone to pick with David Bushell than with Handson table, but as his plugin is included with the `dist` and `full` css I figured it was worth mentioning here.

Additionally as of v0.24.2 [here's the offending line in `handsontable.full.css`](https://github.com/handsontable/handsontable/blob/0.24.2/dist/handsontable.full.css#L1175)

**Comment by AMBudnik** [comment]
Thank you for very details explanation. I will allow myself to mark your request as an improvement suggestion.

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topic and uloading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Isuee will be reopene with first update.

**Comment by wspurgin** [comment]
@AMBudnik fair enough, but I don't see this suggestion on that wiki page... is it elsewhere?

**Comment by AMBudnik** [comment]
Hi @wspurgin under [no 53](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

**Comment by bah99** [comment]
Hi, I fixed the post-css @charset issue by importing **handsontable.full.min.css** (which contan one charset at the first line) instead of **handsontable.full.css**
