### ISSUE TITLE
Uncaught Error: Cannot find module 'moment'

### ISSUE THREAD

**Issue by hyperh** [handsontable/handsontable#3407]
I'm using the handsontable npm distribution (with Meteor 1.3.2), but when I try to import it, console says `Uncaught Error: Cannot find module 'moment'`.

**Comment by krzysztofspilka** [comment]
@budnix can we identify the problem?

**Comment by hyperh** [comment]
Here's a sample project you can clone that gives me this error
https://github.com/awsp/handsontable-meteor-1.3-react

**Comment by budnix** [comment]
Hi @hyperh, Handsontable has 3 more libraries which you must include to your project to sucesfully build it. Update your imports in `foo.jsx` file to something like:
```
import React from 'react';
import moment from 'moment';
import pikaday from 'pikaday';
import Zeroclipboard from 'zeroclipboard';
import Handsontable from 'handsontable';
```

I've checked this with your app at https://github.com/awsp/handsontable-meteor-1.3-react and it works like a charm :)

**Comment by hyperh** [comment]
@budnix Looks like that worked! Thanks a lot!

**Comment by kaplanov** [comment]
Tried to add Handsontable to simple react-webpack boilerplate (available here - https://github.com/kaplanov/react-hot-boilerplate)
To reproduce:
1) checkout
2) run `npm install`
3) run `npm run`
4) navigate to localhost:3000
I got `handsontable.js:53 Uncaught Error: Cannot find module 'numbro'`

**Comment by budnix** [comment]
Hi @kaplanov, Did you looked into my webpack config file (https://github.com/budnix/react-hot-boilerplate/blob/master/webpack.config.js)? As already you update your webpack config file add necessary imports to [HoT.js](https://github.com/budnix/react-hot-boilerplate/blob/master/src/HoT.js) and react-hot-boilerplate should run without errors.
