### ISSUE TITLE
Prior fix for wtHolder height bug not included

### ISSUE THREAD

**Issue by adrianmcli** [handsontable/handsontable#3408]
In reference to issue #3013, it seems that there was originally a fix that changed this:

``` js
if (trimmingElement === window) {
  ...
} else {
  ...
}
```

to this:

``` js
if (trimmingElement === window) {
  ...
} else if (trimmingElement.className.indexOf('handsontable') != -1) {
  ...
}
```

This is the specific commit that fixes the issue: https://github.com/casestack/handsontable/commit/c603ce279c97aabf1e6a197a94e3ee0ef2c1fc6e

Someone else also incorporated the fix into their own fork: https://github.com/hwbllmnn/handsontable/commit/7e294e58f9affbf65fe4f8393dbc39250d287f4c

Unfortunately, the issue was closed by @AMBudnik without having the change merged into the _real_ repo (probably because there was no pull request).

Should I make a fork w/ the same fix and do a PR to get this fix into the official Handsontable repo?

**Comment by AMBudnik** [comment]
Hi @adrianmc 
If you could create a demo where there are measurable issues I'd more that happy to share this pull request with our developer.

**Comment by adrianmc** [comment]
@AMBudnik I'll take some time to do this, although it might take a couple weeks as I am quite busy at the moment. That being said, it doesn't seem to be an isolated problem and @rtaft seems to have a good explanation of the issue:

> This is caused in alignOverlaysWithTrimmingContainer when the trimming element ends up being one of the outer divs of the page. getStyle returns the size of the page, which increases the size of wtHolder, which in turn increases the size of the page. Disabling the setting of the size breaks drop downs. removing the computed style in getStyle works for me, but may break other things. I used this workaround:

_You may go to the [original issue](https://github.com/handsontable/handsontable/issues/3013) to see the rest of this comment._

**Comment by AMBudnik** [comment]
Thank you @adrianmc 
I will mark you request as an improvement suggestion.
Please take your time to create a demo.

**Comment by AMBudnik** [comment]
Hi,

Thanks again for sharing this Feature Request. I am moving it to our Wiki Section at https://github.com/handsontable/handsontable/wiki/Feature-requests
The issue will stay closed until it'll get picked by our developer.

You can leave your comments anytime you want.

**Comment by mikro45** [comment]
This issue is also connected with issue #4141, which was also never fixed. And which could be fixed by implementing suggestion in this issue from @adrianmcli.

Here's a proof that it is still present.
https://jsfiddle.net/2hy8qp31/
