### ISSUE TITLE
Add option for virtual rendering

### ISSUE THREAD

**Issue by stevebooks** [handsontable/handsontable#341]
I can understand how the virtual rendering makes sense when dealing with huge tables. However, having an option to render the entire table during load would help in the following ways:
1. Scroll would be faster/more responsive (sense we are not re-rendering things while scrolling)
2. I would know the max width of the table after the initial load.

**Comment by volodymyr-kushnir** [comment]
Hi, I second that. Usually I have up to 200 rows so I don't need virtual rendering at all, but I do need those other awesome features. Something like **height: auto;** to render everything at once and hide vertical scrollbar. I'll try to modify the source to fit my needs, but I would be very grateful if anyone could point me where exactly to look.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for sharing. I hope that we'll be able to publish it soon.

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
