### ISSUE TITLE
Formulas not working

### ISSUE THREAD

**Issue by hyperh** [handsontable/handsontable#3410]
I can't seem to get the formulas plugins to work. I looked at some jsFiddles (http://handsontable.github.io/handsontable-ruleJS/, click edit in fiddle) and it seems like it's just a one liner, but it's not working for me.

I have a repo here, just set `formulas: true`, and try typing in a simple formula. Nothing happens, it looks like it just renders as text.
https://github.com/awsp/handsontable-meteor-1.3-react

**Comment by AMBudnik** [comment]
Hi @hyperh 
Currently you need to download few more .js files 
Here's an example: http://jsfiddle.net/handsoncode/wbk26Lyo/


A week ago we started to work on formulas, hopefully we would be able to share new version of them in May. 

Please stay tuned to our [Roadmap ](https://trello.com/b/PztR4hpj/handsontable-roadmap-2016-you-can-vote-for-features) for updates.

**Comment by hyperh** [comment]
Thanks, I assume you meant all the files at https://github.com/handsontable/ruleJS/? That's most of the files I see in the `<script>...</script>` calls. Can I just point my npm to https://github.com/handsontable/ruleJS/?

**Comment by AMBudnik** [comment]
Yes, you can, but if you would like to use newest Handsontable version or any above 0.14.1 you should overwrite `http://handsontable.github.io/handsontable-ruleJS/lib/handsontable/handsontable.full.js` as it uses Handsontable v0.14.1
