### ISSUE TITLE
Add styling and functionality to a certain table header column

### ISSUE THREAD

**Issue by fbatz** [handsontable/handsontable#3413]
following problem:
i'd like to set a css class and event listener to a certain table header column.
as soon as the table gets scrolled horizontally, handsontable removes the first columns from the table(and DOM), the css class also moves and the cellIndex does not match any more. 

Before scrolling
![image](https://cloud.githubusercontent.com/assets/9460915/14669602/db0b7b8e-06e9-11e6-8678-1da9c54ccd74.png)

After scrolling
![image](https://cloud.githubusercontent.com/assets/9460915/14669557/bb8affe6-06e9-11e6-8e3c-1f5b637118e9.png)

Is there a way to add styling and functionality to a certain table header column without losing the index on the header?

**Comment by AMBudnik** [comment]
Hi @fbatz 

Currently styling Handsontable is very hard but we're working on it.

Please take a minute to check this quick demo made one of our developers: http://codepen.io/js-ziggle/pen/pjpNWZ
