### ISSUE TITLE
how use changeColumnPositions

### ISSUE THREAD

**Issue by gbelmm** [handsontable/handsontable#3417]
how use 

hot.changeColumnPositions(3,2) 
hot.addFixedColumn();
hot.updateSettings({fixedColumnsLeft: 2});

**Comment by AMBudnik** [comment]
Hi @gbelmm 
Are we talking about a specific example or in general?
When it comes to for example `hot.updateSettings({fixedColumnsLeft: 2});` it's a full code that you can inject for example to a button like in this example: http://jsfiddle.net/8ctnw6yo/

**Comment by gbelmm** [comment]
I need to leave a column and as said example column 4 as fixed

**Comment by AMBudnik** [comment]
This questions followed me to [`freezeColumn(column)`](https://docs.handsontable.com/pro/1.3.3/ManualColumnFreeze.html#freezeColumn) method which actually seams to be buggy.

Other way to achieve your goal is to definie [`columns`](https://docs.handsontable.com/pro/1.3.3/Options.html#columns). When your data is an object you can pick which columns should be first so you can set index `4` column as first and then use `fixedColumnsLeft: 1`. Here's an example: http://jsfiddle.net/hu7Lw2fh/

**Comment by gbelmm** [comment]
i need hot.getPlugin('manualColumnFreeze').freezeColumn(hot.getPlugin('manualColumnFreeze').getVisibleColumnIndex(4));

tnk
