### ISSUE TITLE
Cannot read property 'tagName' of null at ManualRowMover.checkRowHeader

### ISSUE THREAD

**Issue by IntegerMan** [handsontable/handsontable#3421]
When I focus a cell in HoT when using the ManualRowMover plugin, I've observed that sometimes I encounter a "Cannot read property 'tagName' of null at ManualRowMover.checkRowHeader" error 2 - 4 times in rapid succession. This seems to be more prevalent for columns that I have to scroll into view in order to click and seems to mostly happen on the first time you click a cell, but I don't have 100% accurate repro steps on this.

Looking over the codebase, it looks like checkRowHeader should probably be defined as:

```
checkRowHeader: function(element) {
  if (element != this.hot.rootElement) {
    var parent = element.parentNode;

    /* This line is new and addresses the null ref encountered */
    if (parent === null || parent === undefined) return false;

    if (parent.tagName === 'TBODY') {
      return true;
    }
    return this.checkRowHeader(parent);
  }
  return false;
}
```

**Comment by AMBudnik** [comment]
Hi @IntegerMan 
Thank you for sharing. Could you create a demo to present the whole issue when it's appearing?

**Comment by IntegerMan** [comment]
In order to do that I'd need 100% reproable steps and I'd need to spend a day scrubbing our logic out of the application, unless you mean a video demo. In that case, we might be able to find time to rip out the fix and try to catch the virtualization bug on video.

**Comment by AMBudnik** [comment]
it is always better to work on code as the video won't share needed information how to reproduce the issue. 

I understand that by writing `sometimes I encounter` you're telling that this issue it tricky and it shows randomly and that's why it is hard to reproduce. In the other hand now I know that there is something that has to be fixed but I am not able to emulate it. I think that our developers should take a look at this topic. Surely they will connect the dots faster.

Thanks for sharing @IntegerMan 
Have a nice day.

**Comment by IntegerMan** [comment]
I'm also seeing this in checkIfColumnHeader. With that, I can tell that the event.target being passed in to that method is null and that method (as with the one listed earlier) does not properly check for nulls. I can't tell you *why* event.target is sometimes null, but I can get at the symptoms at least. Incidentally, this always happens on or after cell click / mouse move and never on a column header.

**Comment by budnix** [comment]
Hi @IntegerMan, few versions before we've refactored ManualRowMove and ManualColumnMove plugin. Can you check if any of issues described above still exist in the newest version?

**Comment by AMBudnik** [comment]
I am closing this issue as there's no reply for some time.
However if someone has any important piece of information in this subject please leave a comment.
