### ISSUE TITLE
afterChange event doesn't provide correct row to match internal data when filtering.

### ISSUE THREAD

**Issue by garypma** [handsontable/handsontable#3422]
**I'm posting this in the regular handsontable issues as there seems to be no response in the ngHandsontable issues section. Anyway, it may actual be an issue with the pro version of handsontable.
**
I have attached an afterChange event to my table. When the event fires after changing any cell the row provided in the charge argument is correct if I'm not filtering. While sorting I use the sortIndex to translate the sorted row to the correct data row. However, if I'm just filtering the table, there is no sortIndex and no other translation to map the row provided in the change param to the real row in my data. Here is my code:

$scope.itemChanged = function (change, source) {

            if (change === undefined || change === null)
                return;

            var row = change[0][0];
            if ($scope.participants !== undefined && $scope.participants.length > row) {
                var table = hotRegisterer.getInstance('compTable');
                var dataIndex = row;
                if (table.sortIndex.length > row) {
                    dataIndex = table.sortIndex[row][0];
                }

                var part = $scope.participants[dataIndex];
                console.log("row = " + row + ", calculating bonus for " + part.fullName);
                compGridService.calculateBonus(part);
            }
        };

Under normal sorting or not sorting that row is mapped correctly, but when filtering the row returned is the row shown on the table not the ACTUAL row in my data. This is a major issue and may cause us to look for another solution if not resolved quickly. Maybe there is a translate feature, if so, any help would be great.

Thanks

**Comment by AMBudnik** [comment]
Thanks for sharing @garypma 
Could you find a moment to create a demo where this issue can be replicable? It would definitely help to check what's wrong.

**Comment by garypma** [comment]
I have added a demo here:

http://jsbin.com/rikuhi/367/edit?html,js,output

First edit any cell in the "amount" column. You will see an alert that shows the correct person being edited and then it will change the value in the "calc" column corresponding to the same person. Next filter by first or last name so that the first person in the list is no longer showing. Edit several of the "amount" columns and you will notice that the alert doesn't match the row.

**Comment by AMBudnik** [comment]
Hi @garypma 

as it's an issue board for a pure js version I made the same example: http://jsfiddle.net/kegodzvh/ which works as expected.

Can you also test it?

**Comment by garypma** [comment]
@AMBudnik That really doesn't address my issue. Even though your example works for that kind of implementation, it doesn't work for mine. I don't have an array of arrays. I have an array of objects (hash values). In your getDataAtCell or getDataAtRow returns an array of objects. Why is the a sortIndex that allows me to remap to the array, but not a filterIndex? I need to do calculations on multiple columns, and on data that ISN'T shown in the grid. I need the exact index of my internal array. If you really don't have a solution, then we may be forced to go with a different table. I find it hard to believe I can't get back the exact row that is being manipulated in my data when filtering, this is a serious oversight if that is really true. Please see my example again and see how I'm using data NOT in the grid to do some calculations. 

http://jsbin.com/rikuhi/401/edit?html,js,output

**Comment by AMBudnik** [comment]
there is definitely an issue in your example. Angular version has it's own issue board but I will leave this topic for programmers to look at.

**Comment by seeley60** [comment]
From your example 

            var table = hotRegisterer.getInstance('compTable');
            var dataIndex = row;

you have something like this 

    table.getPlugin('Filters').trimRowsPlugin.rowsMapper.__arrayMap[row] 

it give you the row index you can use with getSourceDataAtRow() for exemple.

Hope that help and sorry for my poor english....

**Comment by AMBudnik** [comment]
thanks you @seeley60 for feedback.
@garypma are you are still seeking for a solution?

**Comment by garypma** [comment]
Let me check that solution now.

 

Gary Barker

(Mountain Time)

c: (801) 616-0915

o: (801) 489-0504

**Comment by garypma** [comment]
That seems to fix the first problem. The second problem, which is related, is how to determine which row is being addressed when a dropdown is being invoked. For example I have the following column defined:

 

{ data: 'tmoption', type: 'dropdown', source: loadOptions, width: 70 }

 

 

The controller code looks like this:

 

 

var loadOptions = function (query, process) {

            var table = hotRegisterer.getInstance('compTable');

            // Where do we get the row???

 

            compGridService.getList('usa').then(function (data) {

                process(data);

            }, onPoListError);

        };

 

I need to know the data of the row so I can pass in the correct parameter into my api. Right now it’s hard coded to ‘usa’, but it is variable based upon the data in the row.

 

 

Gary Barker

(Mountain Time)

c: (801) 616-0915

o: (801) 489-0504

**Comment by AMBudnik** [comment]
@garypma 
I'm closing this issue as the base case was solved and the second has already it's own issue at https://github.com/handsontable/handsontable/issues/3479
