### ISSUE TITLE
freezeColumn() doesn't work

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3423]
demo: http://jsfiddle.net/198vg2p6/2/

according to the docs

> **freezeColumn(column)** Freeze the given column (add it to fixed columns).

where column is a 

> Column index

If so in the example above we would have `A` (from `fixedColumnsLeft: 1`) and `E` columns fixed and we have `A` and `B`.

**Comment by jansiegel** [comment]
It doesn't seem like a bug - it doesn't work properly, because the `manualColumnFreeze` plugin is not enabled.
When I set it to `true`, it works fine: http://jsfiddle.net/js_ziggle/198vg2p6/3/

**Comment by AMBudnik** [comment]
Thanks @jansiegel you're right, with `manualColumnFreeze` enabled it's working as a charm. I guess the only thing we can do is add a line about it in the docs.
