### ISSUE TITLE
beforeChange and afterValidate - which one should be fired first?

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3424]
@AMBudnik said:
"Example demo: http://jsfiddle.net/handsoncode/mxrr9jh7/
In the example above when we change a '2011' value to 'xyz' (and press enter) we can see that console logs `beforeValidate`, `afterValidate` and `beforeChange` as expected it does not print `afterChange` as we returned `false` in `beforeChange` hook.

The case is that the content wasn't changed but we already got a `htInvalid` class bound to this cell (with a red bg color) while validation.

I would expect `beforeValidate` to fire after I perform anything inside a `beforeChange`. If I'm wrong - what exactly triggers the `beforeValidate` if not a change? And what I would have to do to completely block an unwanted change?

Question 2. If a change and a validation is a process what should be the last step - cell was changed or the same cell got validated?"

To be discussed @jansiegel, @swistach, @krzysztofspilka.

**Comment by AMBudnik** [comment]
updated example: http://jsfiddle.net/handsoncode/azd0gruv/

**Comment by swistach** [comment]
I think that should be in that order:
```
beforeChange
   if (beforeChange !== false)
      beforeValidate
          if (beforeValidate !== false)
             afterValidate
      afterChange
```

**Comment by AMBudnik** [comment]
So now when we type 'xyz' in a numeric cell we get

```
(index):108 beforeValidate
(index):111 afterValidate
(index):104 beforeChange
```

http://jsfiddle.net/m990ma8b/
We can't validate something without an information that someone wants to change the value.

**Comment by AMBudnik** [comment]
Same situation v `2.0.0.` and all versions before.

**Comment by AMBudnik** [comment]
In 7.1.0 we get only `beforeChange` as there we return false the next hook (for the validation) is not called http://jsfiddle.net/handsoncode/nh35jze9/

**Comment by wojciechczerniak** [comment]
> In 7.1.0 we get only `beforeChange` as there we return false the next hook (for the validation) is not called http://jsfiddle.net/handsoncode/nh35jze9/

@AMBudnik This is the correct behavior proposed by @swistach and @budnix. Looks like this is fixed for at least a year now. Can you check when exactly and close it?

![Screenshot 2020-07-02 at 01 10 52](https://user-images.githubusercontent.com/4718998/86299665-1d40da00-bc01-11ea-8046-19783e8827f3.png)

**Comment by AMBudnik** [comment]
@wojciechczerniak 

You're right. Swistach's scheme

```
beforeChange
   if (beforeChange !== false)
      beforeValidate
          if (beforeValidate !== false)
             afterValidate
      afterChange
```

is the one that is currently executed. Meaning, if we pass `false` in the `beforeChange` hook, the rest of the hooks are skipped.

#### Version check
* works like this from `7.0.0` http://jsfiddle.net/dpn0c4j7/ 
* last broken version `6.2.2` http://jsfiddle.net/93ojg4eh/

I'm closing this issue as solved.
