### ISSUE TITLE
export plugin

### ISSUE THREAD

**Issue by pramodsvidyarthi** [handsontable/handsontable#3425]
In the pro version, when we export to csv and open the file in msexcel it display the html tags in columns which had the renderer as 'html' in hot settings. is there a setting to the export plugin that will handle this or any workaround that can display cells as a string.

**Comment by swistach** [comment]
Hi @pramodsvidyarthi,
Sadly, now plugin doesn't support this feature, but in near future we want add hook 'modifyRowData' to ease work with getData. (Probably after release nestedRows).
This workaround (http://jsfiddle.net/5h5a37uL/) shows, how you can solve problem.

**Comment by pramodsvidyarthi** [comment]
Hi @swistach thanks for the workaround, much appreciated.
