### ISSUE TITLE
Checkbox template features not working in 0.24.2

### ISSUE THREAD

**Issue by warrior107** [handsontable/handsontable#3426]
checkedTemplate and uncheckedTemplate properties in checkboxes not wokring properly in version 1.3.3. They were working fine in 1.3.2
Even in the documentation of checkbox in version 1.3.3; example 2, the cell shows invalid-data after clicking on the checkbox cells.

Please fix this soon.

**Comment by AMBudnik** [comment]
Hi @warrior107 
This seems to work as expected in newest version, here's  demo: http://jsfiddle.net/tjujmkf9/
Am I missing something?

**Comment by warrior107** [comment]
In the demo provided by you, when the unchecked check-box is clicked, it shows "#bad-value#. Please see the image below 
![image](https://cloud.githubusercontent.com/assets/8248598/14774560/fb96cac2-0ad4-11e6-8250-bae34b98d1dd.png)

**Comment by AMBudnik** [comment]
That's right! Thanks for sharing @warrior107 
We need two clicks for checked and one click for an unchecked to turn `#bad-value#`

**Comment by AMBudnik** [comment]
Issue is replicable for free version also: http://jsfiddle.net/rm3ca0u1/

**Comment by AMBudnik** [comment]
@swistach can you take a look at this?

**Comment by warrior107** [comment]
@AMBudnik and @swistach thanks for taking this up quickly.
