### ISSUE TITLE
horizontal scrolling issues in Safari

### ISSUE THREAD

**Issue by edeyoung** [handsontable/handsontable#3427]
Referenced issue: https://github.com/handsontable/handsontable/issues/3204

I've just updated to 0.24.2. It appears there are still some horizontal scrolling issues in safari. Here's an example: http://jsfiddle.net/hU6Kz/4939/
If you scroll quickly enough, the fixed rows on top get misaligned with the main table.

I'm using Safari v9.1

**Comment by AMBudnik** [comment]
Currently I can only test it with the Safari on Windows (v5.1.7) and it works little slower but there's no flickering.

I will test it with OSX later today.

**Comment by swistach** [comment]
I saw the same problem.
Example:
![issue-safari-3427](https://cloud.githubusercontent.com/assets/11849621/14887333/9f774784-0d55-11e6-9a8b-dea735d22f7d.gif)

Tested on version: 9.1 (11601.5.17.1)

**Comment by AMBudnik** [comment]
Still replicable in Safari 9.1.2 with Handsontable version 0.30.1

**Comment by toroc** [comment]
Seeing the same issue with Handsontable version 0.31.2 for both horizontal and vertical scrolling.
Chrome/56.0.2924.87
Intel Mac OS X 10_12_5

**Comment by wenzowski** [comment]
Still replicable in Handsontable `0.33.0` with Chrome `62.0.3202.94`.

This is related to elastic scroll mouse events: everything works fine if you click and drag the horizontal scroll handle. Disabling elastic scroll by setting `html { overflow: hidden }` fixes horizontal scrolling but breaks the row loader (vertical scrolling) and must be combined with`renderAllRows=true` to be functional.

**Comment by swistach** [comment]
Hi @edeyoung, @toroc, @wenzowski,
We've changed the scrolling mechanism in v0.38.0.

Feel free to reopen if you have still incorrect scroll experience.
