### ISSUE TITLE
FillHandle not working with if formula plugin is enable 

### ISSUE THREAD

**Issue by saurabhkumarvaish** [handsontable/handsontable#3429]
fillHandle: true,
 formulas: true,

fillHandle stops working if i use formulas, 

When i drag the cell down or verticals, cells data not copy.
please see the screenshots.

PFA

![fillhandle_error](https://cloud.githubusercontent.com/assets/463091/14776896/0c0c7afc-0ae7-11e6-8c0e-e60c8e036a76.png)

![fillhandle_error_02](https://cloud.githubusercontent.com/assets/463091/14776895/0bfb99a8-0ae7-11e6-8fb4-180e02ebbf3c.png)

**Comment by AMBudnik** [comment]
Hi @saurabhkumarvaish 
I made a simple example: http://jsfiddle.net/ve9deyt9/ where it does work. Can you guide me how to reproduce the above error?

**Comment by saurabhkumarvaish** [comment]
Hello Aleksandra,

I sending you the sample script in which i am facing the problem.
kindly resolve the issue ASAP


On Mon, Apr 25, 2016 at 1:55 PM, Aleksandra Budnik <notifications@github.com
> wrote:

> Hi @saurabhkumarvaish <https://github.com/saurabhkumarvaish>
> I made a simple example: http://jsfiddle.net/ve9deyt9/ where it does
> work. Can you guide me how to reproduce the above error?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/handsontable/handsontable/issues/3429#issuecomment-214203925>
>



-- 
regards
Saurabh Kumar Vaish

**Comment by AMBudnik** [comment]
@saurabhkumarvaish you face the same issue with the code I provided?
Can you share your OS/Browser information?

**Comment by saurabhkumarvaish** [comment]
your code is working fine, but if i implement on my code then there is a
problem.

I am using PRO version JS files handsome for ColumnSummary.

On Mon, Apr 25, 2016 at 2:45 PM, Aleksandra Budnik <notifications@github.com
> wrote:

> @saurabhkumarvaish <https://github.com/saurabhkumarvaish> you face the
> same issue with the code I provided?
> Can you share your OS/Browser information?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/handsontable/handsontable/issues/3429#issuecomment-214222659>
>



-- 
regards
Saurabh Kumar Vaish

**Comment by AMBudnik** [comment]
Then I would need you to create a Fiddle where this issue can be replicable. 
Without that there's no possibility to fix the issue.

**Comment by saurabhkumarvaish** [comment]
You can the run the file locally, its a HTML file. Error is clearly coming.

On Mon, Apr 25, 2016 at 2:58 PM, Aleksandra Budnik <notifications@github.com
> wrote:

> Then I would need you to create a Fiddle where this issue can be
> replicable.
> Without that there's no possibility to fix the issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/handsontable/handsontable/issues/3429#issuecomment-214229436>
>



-- 
regards
Saurabh Kumar Vaish

**Comment by AMBudnik** [comment]
there is no file in any of your comments @saurabhkumarvaish 
can you upload it?

**Comment by saurabhkumarvaish14** [comment]
I uploaded the zip file
Plz check it.

[sample.zip](https://github.com/handsontable/handsontable/files/234311/sample.zip)

**Comment by AMBudnik** [comment]
Hi @saurabhkumarvaish 
we do not operate of .zip - we share the code via JSFiddle.
I made an exception for you but please share all future issues via JSFiddle.

I did not check every file line by line, but you should download all scripts in this order (then your code works and there's no console errors).

```
<script src="http://handsontable.github.io/handsontable-ruleJS/lib/jquery/jquery-1.10.2.js"></script>
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/handsontable/handsontable.full.js"></script>
      <link rel="stylesheet" media="screen" href="http://handsontable.github.io/handsontable-ruleJS/lib/handsontable/handsontable.full.css">
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/lodash/lodash.js"></script>
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/underscore.string/underscore.string.js"></script>
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/moment/moment.js"></script>
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/numeral/numeral.js"></script>
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/numericjs/numeric.js"></script>
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/js-md5/md5.js"></script>
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/jstat/jstat.js"></script>
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/lib/formulajs/formula.js"></script>
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/js/parser.js"></script>
      <script src="http://handsontable.github.io/handsontable-ruleJS/lib/RuleJS/js/ruleJS.js"></script>
```

**Comment by saurabhkumarvaish14** [comment]
As per you said - i created a Fiddle - https://jsfiddle.net/saurabhkumarvaish/ajo3od5s/ 

The SUM of Total rows showing - #ERROR 
and FillHandle is not working

**Comment by saurabhkumarvaish** [comment]
As per you said - i created a Fiddle -
https://jsfiddle.net/saurabhkumarvaish/ajo3od5s/

The SUM of Total rows showing - #ERROR
and FillHandle is not working



On Mon, Apr 25, 2016 at 9:06 PM, saurabhkumarvaish14 <
notifications@github.com> wrote:

> As per you said - i created a Fiddle -
> https://jsfiddle.net/saurabhkumarvaish/ajo3od5s/
>
> The SUM of Total rows showing - #ERROR
> and FillHandle is not working
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/handsontable/handsontable/issues/3429#issuecomment-214398701>
>



-- 
regards
Saurabh Kumar Vaish

**Comment by saurabhkumarvaish14** [comment]
waiting for reply

**Comment by AMBudnik** [comment]
Hi @saurabhkumarvaish 
Here's http://jsfiddle.net/ve9deyt9/5/ the working (without '#error') example with your data but as you righly noticed the fillhandle does not work.

Thanks for sharing. This example is complex and I would need to isolate the problem but will mark this as a bug.

**Comment by saurabhkumarvaish14** [comment]
Hi AMBudnik, 

Still waiting for your reply, Bug still not resolved, is there any alternate for this solution.

**Comment by AMBudnik** [comment]
@saurabhkumarvaish 
We will have to wait till it get's pulled into milestone.
Unfortunately there are still some other bugs that have higher priority.

**Comment by rexchujie** [comment]
Hi AMBudnik,
In another page I see you've created a Fiddle: http://jsfiddle.net/5y2xm08d/ , and actually in this Fiddle the drag down problem occurs. You can only drag down for one row. If more than one rows, it failed.

**Comment by AMBudnik** [comment]
@rexchujie I think that it would work as expected if we could use newest version of Hot but formulas currently are using RuleJS with older version of Hot. 
Better formula support is on our [Roadmap ](https://trello.com/b/PztR4hpj/handsontable-roadmap-2016-login-to-vote-for-features) but it's a huge task and it will take some time. Will planning to add it as a plugin.

**Comment by AMBudnik** [comment]
The issue do not occur for the newest version of Handsontable, demo: http://jsfiddle.net/98sow066/
(PRO version, as the formula plugin was added to 1.7.0)
