### ISSUE TITLE
fixedColumnLeft bug with selection by header

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3431]
If colHeaders is true and fixedColumnsLeft is set, after scrolling horizontally, try click into header of fixed column. Result in devtools: `Uncaught TypeError: Cannot read property 'hasAttribute' of undefined`

Demo: http://jsfiddle.net/jgp7sr3g/

![fixedcolumnsheader-issue](https://cloud.githubusercontent.com/assets/11849621/14784083/1b2cb33c-0af4-11e6-9535-5268709d5d79.gif)

**Comment by AMBudnik** [comment]
May it be related https://github.com/handsontable/handsontable/issues/3354 ?

**Comment by swistach** [comment]
Yes, is the same bug.

**Comment by AMBudnik** [comment]
Released: v0.25.0
