### ISSUE TITLE
Table height increases every time the browser is resized

### ISSUE THREAD

**Issue by Sune1337** [handsontable/handsontable#3433]
If a handsontable has a parent at any level that has the 'overflow: auto' css style set, and that container also has other content than the handsontable, the handsontable height will increase every time the browser is resizing/resized.

Example: https://jsfiddle.net/4ecg5L1o/4/
(After you have opened the example, resize the browser window and watch the table height increase.)

I think this may be related to #3432

**Comment by xfight0** [comment]
I got into the trouble too...

**Comment by jerradpatch** [comment]
I got into this issue as well when I was trying to make the table have a horizontal scroll bar for columns overflowing page width.

**Comment by AMBudnik** [comment]
Issue still replicable in 0.34.0/1.13.0
Updated demo http://jsfiddle.net/v7brdr0b/ (latest)

**Comment by AMBudnik** [comment]
Hey @Sune1337 

it just got fixed in v `7.1.1`
@xufuhero @jerradpatch
