### ISSUE TITLE
Click event swallowed after redraw of custom cell renderer

### ISSUE THREAD

**Issue by baac0** [handsontable/handsontable#3436]
Hello, 

we're facing an issue with the Handsontable with respect to custom cell renderers. Under certain circumstances click events are swallowed and not delegated to the custom element.

Our analysis suggests this is related to Handsontable forcing a redraw of the element on mousedown so that the corresponding mouseup (completing the sequence defining a click event) does not occur on the same element instance.

We believe the forced redraw to be triggered erroneously e. g. in cases where the scroll position of the viewport coincides with the top of a row; in this cases function _areAllProposedVisibleRowsAlreadyRendered_ in _WalkontableViewport_ forces a redraw even if the scroll position hasn't changed.

The problem is demonstrated in the following fiddle: http://jsfiddle.net/wbn6hmoj/1/

Clicking the 'Click to Scroll' button moves the scroll position to the top of a row; subsequent clicks on the buttons in the table no longer trigger an alert.

We tested this with the latest version of Handsontable (0.24.2), but the problem is already present in version 0.16.X.

One possible fix would be to remove the conditions
 _|| (proposedRowsVisibleCalculator.startRow === this.rowsRenderCalculator.startRow && proposedRowsVisibleCalculator.startRow > 0)_ 

and

_|| (proposedRowsVisibleCalculator.endRow === this.rowsRenderCalculator.endRow && proposedRowsVisibleCalculator.endRow < this.wot.getSetting('totalRows') - 1)_

from the aforementioned function, the rationale behind which is not clear to us anyway. This fix does not break the tests; however, we wonder what other negative side effects it might have.

Another probably relevant piece of information: we use the settings

   _outsideClickDeselects : false,_
    _viewportRowRenderingOffset : 0,_

in our code.

**Comment by AMBudnik** [comment]
Thank you @baac0 for your detailed explanation and an effort of your team to check this case for us.
I will definitely share this issue with the rest of the team.

**Comment by AMBudnik** [comment]
The issue is still replicable in v0.34.3

**Comment by swistach** [comment]
Hi @baac0,
I recommend you to use renderer only to render elements.
If you would like to add any logic to elements from the renderer, you can use `beforeOnCellMouseDown`: http://jsfiddle.net/2tbr1g4a/

Feel free to reopen if it's still a problem.
