### ISSUE TITLE
Clicking outside dropdown area should behave like pressing Esc

### ISSUE THREAD

**Issue by mariusk** [handsontable/handsontable#3438]
When activating a dropdown list and pressing outside the list, the action still generates an edit event for the cell, even if the content of the cell does not change. When pressing Esc, the dropdown is closed and no edit event gets generated.

This inconsistency typically causes all sorts of trouble in applications where a dropdown selection in one cell can have consequences for contents in other cells. If nothing actually gets (actively) selected, no edit events should ever be generated. IMHO.

**Comment by AMBudnik** [comment]
Hi @mariusk 
I checked the dropdown demo at our Dropdown section: https://docs.handsontable.com/pro/1.3.4/demo-dropdown.html and it works as it should (the same for an outside click as for the <kbd>ESC</kbd>).

Can you guide me on how to get the odd behavior when the dropdown is not closing with an outside click? I think it can only happen when you use `outsideClickDeselects: false`

**Comment by mariusk** [comment]
I made a demo here:

http://jsfiddle.net/y1v49Ler/

Make sure you have the console open. Open any dropdown, press Esc, nothing happens. Open any dropdown, press outside, and see the edit event being generated.

**Comment by AMBudnik** [comment]
Hi,

Thanks for sharing. Now I'm sure what we are talking about.
The example behavior is intended. Please go to: https://docs.handsontable.com/pro/1.3.4/tutorial-cell-editor.html and check `Closing editor` section.

**Comment by mariusk** [comment]
Thanks, assuming the `beforeKeyDown` can catch the click outside, it should be fairly simple to modify it to my liking. The documentation with example at https://docs.handsontable.com/0.21.0/tutorial-using-callbacks.html reads the keycode, but a click outside doesn't have a keycode I expect? Any docs on how to separate a click inside the dropdown and outside from the passed event, or by calling back into the API inside the `beforeKeyDown` handler?

**Comment by AMBudnik** [comment]
Unfortunately there's no easy way how to manage it.

**Comment by mariusk** [comment]
Thank you for clearing that up. I'll rest my case by stating that if the current behaviour is as designed, it's an example of poor design. Any action that doesn't change the cell content shouldn't trigger a callback to the change handler. In my use case, the selection from the dropdown auto-fills other cells that can still be overwritten by the user if he wants to. Now if the user accidentally presses the dropdown the only way to avoid messing up the overwritten values is to press Esc. Pressing anywhere - even outside the dropdown  - triggers the change handler, which again overwrites certain other cells (on the assumption that a selection was actually made). IMHO.

**Comment by AMBudnik** [comment]
I think we shouldn't close this issue. I will reopen it add mark as an improvement suggestions for the dropdown/autocomplete cell types.

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topic and uloading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Isuee will be reopene with first update.

**Comment by eitanhy** [comment]
@AMBudnik -> how should we address a solution for this, is there any update on it ? we have used handsontable and implemented a custom multi-select auto complete controller, unfortunately the only thing stopping us from full functionality is this issue

**Comment by AMBudnik** [comment]
Hey @eitanhy 

please share more details about your project (current use of options + additional requirements) with me via email support@handsontable.com

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. Please free to continue the conversation there. Thank you.
