### ISSUE TITLE
Copy and paste bug with pasting text value as table value

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3439]
The problem occurs when more than one cell was copied and pasted into editor. 

**Steps to reproduce the problem:**
1. Go to demo: http://jsfiddle.net/9c5rfdnb/
2. copy/cut A1:B2 and past into editor of A3,
3. copy/cut A3:B4 and past into selected A5

:information_source:

> Handsontable - 0.24.2

**Comment by swistach** [comment]
This issue will be fixed in #4234

**Comment by swistach** [comment]
It's the same issue as #4308

**Comment by AMBudnik** [comment]
Released: v6.1.0
