### ISSUE TITLE
Drag down near read only cells causes inadvertent behavior

### ISSUE THREAD

**Issue by wkuehler** [handsontable/handsontable#3441]
Dragging down near read only cells causes other cells that should not be read only to have the read only attribute applied.  Example can be found  [here](http://jsfiddle.net/wkuehler/wpmL599p/2/)

In this example, only cells that contain A should be read only.  To see the bad behavior, select the cell with the letter B.  Using the drag handle, drag down to the R and release.  Notice that the cell with the T is now read only.

**Comment by wkuehler** [comment]
Interestingly, adding the following seems to address the issue as a workaround:

`fillHandle: {autoInsertRow: false},`

**Comment by AMBudnik** [comment]
You're right. I slowly moved the handle line by line and when I drag down creating new row the `htDimmed` (readOnly class) is shifted down with the handle.

**Comment by AMBudnik** [comment]
Read-only still shifted down, updated example (0.28.3): http://jsfiddle.net/gw0fxo6w/

**Comment by AMBudnik** [comment]
I am no longer able to replicable this issue. @wkuehler can you check if this demo works for you http://jsfiddle.net/gw0fxo6w/?

**Comment by AMBudnik** [comment]
I'm closing this issue as solved. If anyone would have the same experience in 7.4.2 please share a comment.
