### ISSUE TITLE
Check version

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#3444]
hello,
how i can get the version handsontable with a javascript function ?

regards
jm

**Comment by AMBudnik** [comment]
Hi,

you should use `Handsontable.version`

**Comment by jeanmarc78** [comment]
so easily,
thanks a lot
jm

**Comment by sessaji** [comment]
How to know the version of HOT from instance object created?

**Comment by AMBudnik** [comment]
Hi @sessaji , the library stores the details about the version, not an instance of Handsontable. That is why you need to call `Handsontable.version`, where Handsontable is the library (not an instance).
