### ISSUE TITLE
Context menu plugin optimisation of behavior

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3446]
First thing is blocking native context menu on opened context menu from plugin.
![issue-nativecontextmenu-on-contextmenu](https://cloud.githubusercontent.com/assets/11849621/14913912/830fe482-0e06-11e6-84b7-512571c59e1c.gif)

Second thing is blocking clicks positions in context menu from plugin by right click.
![issue-contextmenu-right-click-on-contextmenu](https://cloud.githubusercontent.com/assets/11849621/14914075/7f6e0df8-0e07-11e6-922e-6c15cd88e325.gif)

**Comment by AMBudnik** [comment]
Both still replicable.

**Comment by AMBudnik** [comment]
I was not able to replicate the second scenario with the latest [version 0.35.0](https://handsontable.com/examples.html?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers&_ga=2.250650116.323454457.1516001775-808623146.1459241209)

In the first scenario are you clicking the <kbd>RMB</kbd> on the inactivated option of the context menu?

**Comment by swistach** [comment]
Yes, you have to use <kbd>RMB</kbd> to reproduce this behaviour.
Below up-to-date gif (green circle is a visual presentation of right-clicking): 
![rmb-contextmenu](https://user-images.githubusercontent.com/11849621/35142144-b485da8e-fcfd-11e7-9194-5b3aa217e83b.gif)

**Comment by AMBudnik** [comment]
Thanks for a quick update.

**Comment by aninde** [comment]
This bug will be fixed in `7.3.0 v` It works even in `iframe`

![cointextMenu7 3 0](https://user-images.githubusercontent.com/30186818/68952569-65210700-07c0-11ea-871d-290599a19384.gif)

**Demo**
`7.3.0 v` https://jsfiddle.net/aninde/zLq2dwgv/

**Comment by AMBudnik** [comment]
Tested for the latest build (6.12) https://jsfiddle.net/AMBudnik/3pb1rnzg/

The system menu is not visible with the <kbd>RMB</kbd> for enabled nor disabled options.

Tested with Catalina on Chrome 78, FF 70 and Safari.

**Comment by aninde** [comment]
Confirmed, like @AMBudnik  wrote it still works good during testing `7.3.0 v.` (6.12) on Chrome 78, Firefox 70, Safari 13, Microsoft Dev Edge / Mac OS Catalina and IE, Edge, Edge Dev / Windows 11
https://jsfiddle.net/aninde/h6ktomdf/1/ `7.3.0 v.` ( 6.12.19 build)
https://jsfiddle.net/aninde/x4cLohk2/ iframe `7.3.0 v.` ( 6.12.19 build)
