### ISSUE TITLE
Virtual rendering mechanism doesn't work properly if cell is wider and/or higher than table.

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#3448]
After scroll vertically or horizontally we can see only background.

*\* Steps to reproduce **
1. Go to http://jsfiddle.net/e8s3vxdn/
2. Scroll horizontally/vertically

**Comment by krzysztofspilka** [comment]
Luckily this is rather a marginal issue, but true - it works badly.

**Comment by AMBudnik** [comment]
Still replicable in 0.30.1 http://jsfiddle.net/handsoncode/yahatLpa/

**Comment by AMBudnik** [comment]
The table still looks the same in version 0.35.0

**Comment by wojciechczerniak** [comment]
Issues that may have more details and examples: #2731 #4173

**Comment by wojciechczerniak** [comment]
Another one with a nice demo:  #5165

**Comment by adrianszymanski89** [comment]
This issue is no longer replicable with version 12.1.3: http://jsfiddle.net/aszymanski/oep624st/1/
