### ISSUE TITLE
Clipped column header tooltips - difference between 0.7.5 and 0.8

### ISSUE THREAD

**Issue by ianhk** [handsontable/handsontable#345]
I have a few bootstrap tooltips that can be shown from the column header (like help text or mandatory indication). Previously the tooltip would show spanning the table and containing element.

Now it's clipped. In the screenshot below you can just see the bottom of the tooltip.

![Screen Shot 2013-01-08 at 11 41 51](https://f.cloud.github.com/assets/3003415/49972/bc92f964-5988-11e2-9f23-f6333d86ac1e.png)

I'll try to fix by attaching the tooltip to something outside the grid.

**Comment by robincwillis** [comment]
I managed to fix this by setting the container option to something outside of the grid on tooltips.
  $('[data-toggle="tooltip"]').tooltip({
  	container : 'body'
  });

**Comment by phasjim** [comment]
I agree, could someone please post code snippets? I am trying to get tooltips to work within the cells and have not been able to get them to work. Thank you in advance!
