### ISSUE TITLE
handsontableInput is too wide

### ISSUE THREAD

**Issue by happyhero0** [handsontable/handsontable#3450]
This is a screenshot:
![bug](https://cloud.githubusercontent.com/assets/5730147/14972821/eb51f1f2-1112-11e6-88cc-bb17ef9b54cf.png)

I used handsontable-pro 1.3.3,
It is strange, which line code set the width of handsontableInput?

**Comment by AMBudnik** [comment]
Hi @xfight0 
It shouldn't look like this. 
Can you share a JSFiddle demo where we can experience this behavior?

**Comment by AMBudnik** [comment]
I'm closing this issue as there were to new posts withing last 2 weeks but If you would need help with that please leave a comment.

**Comment by chrisvanhill** [comment]
I could reproduce this issue. See this fiddle: [http://jsfiddle.net/e5mt4cgq/
](http://jsfiddle.net/e5mt4cgq/
)

Set body tag in HTML settings as follows:
`<body style="display: flex; flex-direction: column;">`

When you calculate `handsontableInput` with `autoResize`, it appends a span to the body tag and stretches it to the windows width.

**Comment by AMBudnik** [comment]
Thank you for demo @chrisvanhill 

related https://github.com/handsontable/handsontable/issues/3815

**Comment by wojciechczerniak** [comment]
Duplicate of #3815
