### ISSUE TITLE
`keydown` event does not propagate correctly

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#3451]
On some occasions, `keydown` event does not propagate correctly out of Handsontable.

See the fiddle: http://jsfiddle.net/838w3ptz/

Steps to reproduce:
1. double click on A1 to begin editing
2. press ENTER on keyboard to stop editing

Actual console output:

```
mousedown
mouseup
mousedown
mouseup
keyup
```

Expected console output:

```
mousedown
mouseup
mousedown
mouseup
keydown
keyup
```

**Comment by AMBudnik** [comment]
Still we're missing the `keydown` event before `keyup` for <kbd>ENTER</kbd>

![keydown](https://cloud.githubusercontent.com/assets/10757813/22146235/3b76a0f0-df04-11e6-9a7f-b772420769af.gif)

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0`. I haven't found any previous version that supported it.

**Comment by AMBudnik** [comment]
Demo updated to v8.0.0 http://jsfiddle.net/AMBudnik/8v2gscdb/ works the same (`keydown` is not triggered).

**Comment by warpech** [comment]
Related: https://github.com/handsontable/handsontable/issues/5528

**Comment by AMBudnik** [comment]
This issue is no longer replicable using the latest version of Handsontable http://jsfiddle.net/b9pounk8/1/

The `keydown` is triggered just like in the expected scenario. Testes on Chrome 105 / macOS Monterey.

<img width="291" alt="Screenshot 2022-10-11 at 14 05 36" src="https://user-images.githubusercontent.com/10757813/195084973-aeb609f6-3ff6-4ebd-bd42-fcaafc30fc86.png">

**Comment by AMBudnik** [comment]
@manuelfuchs could you please share your system/browser settings? On my Chrome 109 / macOS Vetura I get `keyDown` and then `keyUp`.

**Comment by manuelfuchs** [comment]
@AMBudnik I am also using Chrome 109 but on Windows 11.
Do you get every event and not only every other one? Very strange.

**Comment by AMBudnik** [comment]
I tested the same scenario (as the original posted in the first post) and on a VM with Windows 11 and Chrome 109 I get the same result

![Zrzut ekranu 2023-02-1 o 14 04 05](https://user-images.githubusercontent.com/10757813/216051047-34644fc6-ad31-41eb-861b-e5fe1c33e328.png)
