### ISSUE TITLE
Cell text is copied to another cell on inserting a row or column

### ISSUE THREAD

**Issue by klikstermkd** [handsontable/handsontable#3452]
When a cell is in editing mode (the cursor is blinking) and if I right click on it, to bring up the context menu, if I choose the option to "Insert row above" or "Insert column on the left", the text that's in the cell, is copied to the newly inserted row or column.

Here's a demo to try it out: http://jsfiddle.net/s292j1ns/

**Comment by krzysztofspilka** [comment]
Actually, you shouldn't be able to invoke the context menu in an edit mode. That's a bug, thanks for reporting.

**Comment by swistach** [comment]
I think it's releted with #3445

**Comment by budnix** [comment]
This bug is already fixed in `1.7.1/0.28.4`. I've updated demo at http://jsfiddle.net/s292j1ns/2/.
