### ISSUE TITLE
custom renderer cell formatting is not being updated after column sorting

### ISSUE THREAD

**Issue by ahlunju** [handsontable/handsontable#3453]
http://jsfiddle.net/ng0d93m8/2/

I used the custom renderer example from the documentation as my base template, what I did was I added columnSorting: true and sortIndicator: true, and change the cover property to a object containing the images link and color.

In the coverRenderer, I use the cover.color value to style the TD element's backgroundColor. on image click I update the cover.color value and update the TD background and you can see the background color is being updated to yellow.

the problem comes when I sort, the row gets sorted but the TD style does not get updated with the data.

I am quite new to handsontable, is there a way to trigger a refresh when I sort?

Thanks

**Comment by seeley60** [comment]
If you sort you can't reference directly with the row parameter passed in the function.
I work like this :

row = (instance.sortIndex.length ? instance.sortIndex[row][0] : row);

and after I used row like before ...

**Comment by ahlunju** [comment]
Wow never thought it would just take one line of code to get it work. Thanks!
