### ISSUE TITLE
Backbone is not working with filters in the pro version

### ISSUE THREAD

**Issue by beturs** [handsontable/handsontable#3454]
Hello, I am developing an app with handsontable. Its being almost 5 months in develop. After my boss saw the features with the pro version, he decided to buy it.
The feature he is most interested in right now is the filters.

In the app we use backbone and marionette.
When we switched to the pro version everything was working as expected. But when we activated the filter plugin (we added the filters: true, dropdownMenu: true) it started to break our tests.

I did the same modification in the backbone example you provide, changing to the pro version and add the filter options and i get the same error, 
```
Uncaught TypeError: Cannot read property 'function (car, value) {
                if (_.isUndefined(value)) {
                  return car.get(attr);
   ...<omitted>... }' of undefined
```
on line handsontable.pro.js:6705

I dont know if you have a migration guide or something

Thank you

**Comment by AMBudnik** [comment]
Hi @beturs 
I have already replied to you by email. Please share a full demo where this issue can be replicable.
