### ISSUE TITLE
The feature that export as file does not work in Safari browser

### ISSUE THREAD

**Issue by xfight0** [handsontable/handsontable#3456]
Dear developers,
In the [Demo-export-file](http://docs.handsontable.com/pro/1.3.4/demo-export-file.html),
I used safari 9.0.2 (10601.3.9), when you click the button "Export as a file", nothing happen.
on the other hand, in latest chrome, the feature work but the file content show some garbled charts if the table contains Chinese.

**Comment by AMBudnik** [comment]
Thanks for sharing @xfight0 
I tried it with Safari for Windows and you are right - it does not work. 
As I turned with this issue to our developers they informed me that it's cause of Safari's limitations which disallow us to use this option.
