### ISSUE TITLE
Sort plugin processes wrong column

### ISSUE THREAD

**Issue by zoladkow** [handsontable/handsontable#3457]
With data empty and no row headers, the sort plugin always selects actual column index - 1

With following settings:

```
    rowHeaders: false
    columnSorting: true
    sortIndicator: true
    data: []
```

the beforeColumnSort hook gets -1 as first parameter.

Fiddle showing the issue on latest release: http://jsfiddle.net/unjhctk3/

--- edit: forgot to add possible culprit: https://github.com/handsontable/handsontable/blob/master/src/plugins/columnSorting/columnSorting.js#L261 return value defaults to 1, hence the -1 columnIndex when sorting first column.

**Comment by AMBudnik** [comment]
thanks for sharing @zoladkow 
To easily reproduce try to sort `B` column. In result you get sort indicator moving within `A` column.

**Comment by swistach** [comment]
Hi @zoladkow 
In new version (0.28.4) it works as you expected.
