### ISSUE TITLE
CSS class settings are being overridden by HOT .css file

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3459]
**demo**: http://jsfiddle.net/7xj7mhjy/

**scenario**: we are adding a `test`class to all cells in the grid by a `testRenderer`.

**result**: our:
1. `background`
2. `padding`
3. `height`
4. `border`
5. `empty-cells` 
6. `outline`
7. `line-height`
settings are being overridden by `handsontable.full.min.css`

**tip:** While passing the above inside a renderer (passing value directly to `td`element) like [here](http://jsfiddle.net/qg6qv0j7/) it works as expected.

**Comment by jansiegel** [comment]
I think it's a desired behaviour, this way we can be relatively sure that the table looks as we'd expect when something like
```css
body {
    line-height: 4em;
}
```
is declared.

If the developer wants to overwrite the default css, he or she has to declare the styles using more precise selectors, for example: http://jsfiddle.net/js_ziggle/tv4dgzfp/1/

All add the 'To be discussed' label to this, if that's alright.

**Comment by AMBudnik** [comment]
I am closing the issue. As mentioned by Jan, we should keep more precise style declaration.
