### ISSUE TITLE
row header renderer

### ISSUE THREAD

**Issue by ianhk** [handsontable/handsontable#346]
I use the row header as a substitute for fixed columns. To do this I put a summary of the row in the header - such as firstname+lastname. This needs updating if those columns change.

The current interface only supports setting all row headers in one go - which will get expensive with deep grids. If there was a renderer for headers as there is for fields I could 'paint' when required.

Apologies for bombarding the issues list :)

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
