### ISSUE TITLE
Validation question

### ISSUE THREAD

**Issue by mugsisme** [handsontable/handsontable#3460]
Hi, working on a simple table, 3 columns,  first row defaults to these values:  1, 121, $0
lets say user modifies column2 to be 50, on adding a new row, I want column1 on row 2 to default to 51, and not be editable.  How can I do this?  Thanks.

**Comment by AMBudnik** [comment]
If I understand correctly, here's http://jsfiddle.net/45eyp06m/ how it can be achieved.

**Comment by mugsisme** [comment]
Thank you for the reply, unfortunately jsfiddle is blocked at my company, so I cannot see if this is what I need.  I will have to check it when I get home.

**Comment by AMBudnik** [comment]
Hi @mugsisme 
Did you already had an opportunity to check the code?

**Comment by AMBudnik** [comment]
I'm closing this issue as it was recently updated 29 days ago but if there are some issues left feel free to leave a comment.
