### ISSUE TITLE
numeric range

### ISSUE THREAD

**Issue by mugsisme** [handsontable/handsontable#3461]
Hi, new to handsontable, how do I limit a numeric field to  a range, say 1-100?  Thanks.

**Comment by AMBudnik** [comment]
Hi @mugsisme 
Currently we do not support limiting the content, butbut you can use a `afterChange` callback to get data like here http://jsfiddle.net/ngoh0nng/ and then (for example) rewrite the data or change cell meta data.

**Comment by mugsisme** [comment]
Thank you, but I am having difficulty figuring out how to rewrite the data.

**Comment by AMBudnik** [comment]
you can write a base value from the `beforeChange `hook and check it with the `afterChange `hook value from the same cell.
I'm sure there are easiest way but this just came to my mind.
