### ISSUE TITLE
performance issue with 15 000 rows

### ISSUE THREAD

**Issue by scorsed** [handsontable/handsontable#3462]
Hi everyone!

I want to display of 15 000 lines, and I use your component. but when I start to scroll down the page, I Seeking some delay.

[testHandonTAble_justfiles.zip](https://github.com/handsontable/handsontable/files/253171/testHandonTAble_justfiles.zip)
asp.net solution you can run it with 100 1000 and 15000 rows. just change data.json to data100.json or data1000.json
[testHandsonTable.zip](https://github.com/handsontable/handsontable/files/253172/testHandsonTable.zip)

**Comment by AMBudnik** [comment]
Hi @scorsed 
Can you isolate the issue? In your .zip file there are a lot of files that surely has no impact on our investigation.
It would be a best help if you could create a JSFiddle example.

**Comment by krzysztofspilka** [comment]
@scorsed we have this discussion over email.
