### ISSUE TITLE
Handsontable using Tab key from last cell control going to next row but it is not seeing -Need to row should move up

### ISSUE THREAD

**Issue by sambsa** [handsontable/handsontable#3463]
I am using handsontable and I have a table with more than 100 entries. In my page it shows almost 23 rows of handsontable as you can see in image. 

![images](https://cloud.githubusercontent.com/assets/4330791/15090243/d2333116-143e-11e6-9d20-b3f2c42e55fc.png)

In my page I am using keyboard only to enter in my page. So I am using Tab key to move one cell to another. As you can see in my image I am marked the last cell which can be visible. If I use tab from last visible cell the control is going to start of next cell, But my page shows only 23 cells. I want the next cell to move up on Tab key from last editable cell.

It is coming up smoothly if I use Enter key I need same control in Tab key if it is from last editable cell.
So that I can see the next row. Please guide me how I do that?

**Comment by AMBudnik** [comment]
Hi @sambsa 
<kbd>TAB</kbd> should skip the next cell moving left in the same row. It doesn't skip to next row if selected cell is the last in a column.

When it comes to <kbd>enter</kbd> please check the docs for [enterMoves ](https://docs.handsontable.com/pro/1.3.4/Options.html#enterMoves) option

**Comment by sambsa** [comment]
I know that. The TAB is moving fine. It reaches the maximum visible point of user, From the image you can knew that. Is it possible that the table should move little up just like the same in Enter so the user can see the next row. In current scenario, user need to Scroll up the page to see next row. I think you got my point.

**Comment by AMBudnik** [comment]
Could you take a minute to use this demo http://jsfiddle.net/j0jkychb/ to share an image (ideally) presentation of what you see now and what you would like to see? 
I'm just not sure if we share the same vision and this will definitely help.

**Comment by sambsa** [comment]
@AMBudnik buddy your demo works on Enter from last cell of row and it is perfect. I want the same stuff on TAB, Suppose when I have reached the last visible row and last cell of that particular row, If I press TAB key, in my case it is going to the starting cell of next row it is perfect, but the user can not see it, in order see that he/she needs to scroll up. Can we move the row up so that user can see the row.

**Comment by AMBudnik** [comment]
Hi @sambsa 
How is your progress with this subject? Is there anything I can do for you now?

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply.
