### ISSUE TITLE
Handsontable firstrow misaligned

### ISSUE THREAD

**Issue by jmtolibas** [handsontable/handsontable#3464]
I use the latest version but still got stuck in this problem. Each time the table render, the firstrow is always misaligned and hide under the header. 

<img width="773" alt="capture" src="https://cloud.githubusercontent.com/assets/11639583/15092196/7911ffca-1495-11e6-93b8-abce4937ff59.PNG">

**Comment by AMBudnik** [comment]
Hi @jmtolibas 
Can you share a demo where we can duplicate it?
It looks like a styling issue. Do you use custom styles for colHeaders?

**Comment by jmtolibas** [comment]
Hi @AMBudnik , this is now okay. I just added css on the headers. Thank you.

**Comment by AMBudnik** [comment]
thanks for your feedback @jmtolibas
