### ISSUE TITLE
Undoing a row/col removal does not trigger an event

### ISSUE THREAD

**Issue by timwis** [handsontable/handsontable#3465]
Demo: http://codepen.io/timwis/pen/dMaOJw?editors=0011
Steps to reproduce:
1. Right-click on a row and click "Remove row". Notice the `removeRow` event is logged.
2. Press CMD-Z/CTRL-Z (undo). Notice no `createRow` event is logged

You'll notice that if you do the inverse, _creating_ a row via the context menu and then pressing undo, it _does_ trigger a `removeRow` event.

Is this intended functionality? How can I capture this event?

**Comment by AMBudnik** [comment]
Hi @timwis 
I think that's the same issue as https://github.com/handsontable/handsontable/issues/2577
