### ISSUE TITLE
An error occurs when I use the sort function.

### ISSUE THREAD

**Issue by IDLOCKED** [handsontable/handsontable#3466]
The following error occurs.

> Uncaught TypeError: Cannot read property 'hasAttribute' of undefined

AND　
When I click a header and sort it, the column of the right neighbor is sorted.
However, I discovered the method that a bug did not produce.
It is fixedColumnsLeft: It is to set it to 0.
![2016-05-08 18h51_13](https://cloud.githubusercontent.com/assets/11012887/15097181/7050597c-154e-11e6-96d0-969ab75e3d4d.gif)

This is a sample:https://jsfiddle.net/f0a6uL28/
The point that an error produces is to let you greatly display the window that a table is displayed.
![2016-05-08_19h12_45](https://cloud.githubusercontent.com/assets/11012887/15097261/ef876792-1550-11e6-9014-5524318217db.png)

**Comment by AMBudnik** [comment]
Hi @IDLOCKED 
It's not the same issue as https://github.com/handsontable/handsontable/issues/3354?
If so, it's merged and ready for release.

**Comment by IDLOCKED** [comment]
@AMBudnik 
Thank you for your reply.
It may be the same problem.
I inspect a bug again after I was released first of all.

**Comment by IDLOCKED** [comment]
@AMBudnik 
Hello.
I tried today's update.
As a result, a different error was given.
Uncaught TypeError: Cannot read property 'parentNode' of null
https://jsfiddle.net/2w2438y3/

What should this do?

**Comment by AMBudnik** [comment]
May I suggest to simplify the example? It will be much easier to investigate.

**Comment by IDLOCKED** [comment]
Thank you for a reply.
According to indication, I simplified it.
Should I simplify it than this?

https://jsfiddle.net/107oLgdv/

**Comment by AMBudnik** [comment]
You're right!
I get the same log:

![bug](https://cloud.githubusercontent.com/assets/10757813/15647242/aeb0dbe0-2662-11e6-9929-1f03c34db52b.png)

and the grid won't show at all.

Demo: https://jsfiddle.net/t4382j2n/ (Vanilla https://jsfiddle.net/ujq9x75d/)
If we comment any on these settings (besides `data`) example works as expected.

**Comment by AMBudnik** [comment]
@IDLOCKED 
it works in the newest version, here's an updated fiddle to 0.26.0 https://jsfiddle.net/k5wur4e5/

**Comment by IDLOCKED** [comment]
@AMBudnik
Thank you for fix.
[https://jsfiddle.net/enz6q361/](https://jsfiddle.net/enz6q361/)
However, sortIndicator does not seem to be displayed well.
Please roll the second header from the last.
▲ it will be displayed in a single shift in the header.

Thank you.

**Comment by AMBudnik** [comment]
wow.. @IDLOCKED you're right - it's not working as expected. I'm reopening this issue.

**Comment by swistach** [comment]
Related with: #3323

**Comment by AMBudnik** [comment]
Hi @IDLOCKED 
Can you check if it works for you after updating to 0.30.1? We have fixed the sibling issue https://github.com/handsontable/handsontable/issues/3323

**Comment by IDLOCKED** [comment]
Hi @AMBudnik 
Thank you for contacting me!
Great!
The problem was recovered wonderfully!
Thank you!
https://jsfiddle.net/56azeL9p/

**Comment by AMBudnik** [comment]
Thanks for a quick update @IDLOCKED 
I'm glad that it works for you as well :)
