### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by snuuve** [handsontable/handsontable#3467]
I have no idea what is the problem. Earlier i haven't this issue.

![error handsotable](https://cloud.githubusercontent.com/assets/9519759/15111486/9e346d4e-15e7-11e6-934d-a10a6b508c32.PNG)

Also every mouse click in document occur this error.

**Comment by AMBudnik** [comment]
Hi @snuuve 
I have found a similar issue https://github.com/handsontable/handsontable/issues/1429
May it be the same?

**Comment by snuuve** [comment]
Yea, kinda same. Disabling ColumnSorting fix problem. But i need ColumnSorting.

**Comment by AMBudnik** [comment]
As it's the same I'm closing this issue.
https://github.com/handsontable/handsontable/issues/1429 is marked as a bug and surely should be fixed, and I agree that switching `columnSorting` off is more a tip on how to fix the bug rather than a solution.
