### ISSUE TITLE
Unwanted space between the context menu and it's submenus

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3468]
On Mac, if the "Show scrollbars (only) when scrolling" is enabled, there is an empty space between the Context Menu and it's submenus.
---
#### Steps to reproduce:
1.  Go to http://past.handsontable.com/
2.  Downsize the browser window
3.  Right-click the last cell

**Result:** 
![image](https://cloud.githubusercontent.com/assets/7397134/15114011/0a0f8d72-15f8-11e6-8b62-2a08774a9544.png)

**Comment by budnix** [comment]
This issue no longer occurs in the latest version of Handsontable.
