### ISSUE TITLE
fixed cells comment positioning issue

### ISSUE THREAD

**Issue by hyou357** [handsontable/handsontable#3470]
I am using handsontable's comment and fixed cell,but it results in wrong positioning of comment.

 Here is  http://jsfiddle.net/q335577/76jom4ne/ the code .

**Comment by AMBudnik** [comment]
Hi @hyou357 
This issue is already here: https://github.com/handsontable/handsontable/issues/2608
Please track changes to it.

**Comment by hyou357** [comment]
thank for your answer @AMBudnik 
but when i scrolled ,the comments can't be show.
var. 0.24.0

**Comment by AMBudnik** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/10757813/15141389/10ffff6a-16a0-11e6-9d45-f5956f6e8781.png)
here's what I'm getting. I guess it the same issue. It is already related by Github so if fixing https://github.com/handsontable/handsontable/issues/2608 won't do the job we'll reopen it.
