### ISSUE TITLE
Date: 31th of February becomes 2nd of March

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3471]
demo: http://jsfiddle.net/qhjqoLno/

To reproduce copy date on the yellow background to the Hot date cell.

Expected:
Cell should be marked as invalid and shouldn't change it's value to other than pasted, like in this example: http://jsfiddle.net/ubae1pvd/

**Comment by jhwetstone** [comment]
We've also noticed that the date "35/07/16" becomes July 16, 2035.  Should we open a new issue, or can this be resolved as part of the same effort?

**Comment by AMBudnik** [comment]
Thanks for sharing @jhwetstone 
I think that this is the same issue, even if it's not surely both cases will be tested.

**Comment by LeoLerch** [comment]
Also using German Formats like "DD.MM.YYYY". If one types "5.3.2016" it becomes "03.05.2016", basically switching month and Day

**Comment by AMBudnik** [comment]
Thank you for your feedback @LeoLerch 
I've also reproduced the behavior you've described.

![date-german](https://cloud.githubusercontent.com/assets/10757813/18269417/6e713318-7428-11e6-88a3-814632001193.gif)

you should also test this case while reviewing the code.

**Comment by LeoLerch** [comment]
would be nice if it would make it to one of the next updates. It´s quite annoying (and of course a source for errors) for some of my users

**Comment by AMBudnik** [comment]
I fully understand why this can be frustrating. I'll discuss the ability to fix this issue sooner with the team.
Meanwhile, thanks again @LeoLerch and wish you a productive day.

**Comment by LeoLerch** [comment]
Any news about when this issue can be fixed? or is there a workaround?

**Comment by AMBudnik** [comment]
Hi @LeoLerch 
I think that this issue can be related to this one https://github.com/handsontable/handsontable/issues/3792 as the values are not read correctly but there's no fix date yet as well as a workaround

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/3471

**Comment by swistach** [comment]
We've discussed issues concerning the date.
Our idea is adding new parametr: 'inputFormat' which should resolve problems with date formatting.
If you wanna share your ideas about date formatting, here is url: #3854

**Comment by AMBudnik** [comment]
hi @jhwetstone 
We've made some changes related to this issue. The case that you've reported is something different as there can be a date when days are 31+

@LeoLerch 
Can you confirm that after updating it works in your project?

**Comment by AMBudnik** [comment]
Hi again guys.
As there was no additional concerns and tips I'm closing this issue.
