### ISSUE TITLE
Warning about overwriting __proto__ property on FF

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3472]
In our [runtime.js](https://github.com/handsontable/handsontable/blob/master/src/shims/runtime.js#L370) file there is a line where internal `__proto__` property is overwriting which causes warnings in FF. 

![zrzut ekranu 2016-05-10 o 11 10 34](https://cloud.githubusercontent.com/assets/571316/15141332/e136827c-169f-11e6-800a-fae8de501c2f.png)

**Comment by swistach** [comment]
Currently, this problem doesn't occur.
