### ISSUE TITLE
Fixed columns headers missing when rowHeaders = false

### ISSUE THREAD

**Issue by Aerial94** [handsontable/handsontable#3474]
http://jsfiddle.net/7u58htkm/1/

After updateSettings for changing fixedColumnsLeft header for fixed columns does not stay in place. There is no element with class ht_clone_top_left_corner 

![image](https://cloud.githubusercontent.com/assets/9079074/15142357/f07ae39a-16a4-11e6-8282-55959e919ed4.png)

**Comment by AMBudnik** [comment]
Confirmed. Thanks for sharing @Aerial94 
It occurs when we have `fixedColumnsLeft` set to `0` or not declared in the grid settings.

**Comment by krissenden** [comment]
Any idea when this issue will be fixed?

**Comment by AMBudnik** [comment]
unfortunately there's no dead-line for this issue yet @krissenden

**Comment by AMBudnik** [comment]
updated demo: http://jsfiddle.net/yeu0dbn9/
Issue still occurs

**Comment by swistach** [comment]
This should be resolved in: #3857

**Comment by AMBudnik** [comment]
Hi @Aerial94 
Can you check if after updating to 0.29.0 it works for you?

Thanks in advance!

**Comment by AMBudnik** [comment]
I guess that this issue can be closed. However if you are still facing any difficulties regarding this issue please leave a comment.
