### ISSUE TITLE
Column headers height behaves erroneously 

### ISSUE THREAD

**Issue by zoladkow** [handsontable/handsontable#3476]
With having following settings:

```
    rowHeaders: true,
    rowHeaderWidth: 0,
```

and following style for headers (wrapping enabled)

```
.handsontable table th  {
  word-wrap: break-word;
  white-space: pre-line;
}
```

and scrolling right, at some point col header height gets really huge. Somehow this is related to rowHeaderWidth - larger the value, smaller the anomaly. 
This was supposed to be a nice workaround for #3474, but well, we also like to have wrapped column headers and no row headers.

![image](https://cloud.githubusercontent.com/assets/11553616/15148649/8972149e-16c6-11e6-8423-34988f154cff.png)

![image](https://cloud.githubusercontent.com/assets/11553616/15148755/013464d2-16c7-11e6-842d-48495ca2c299.png)

Sample code:
http://jsfiddle.net/b6py1jxt/

**Comment by AMBudnik** [comment]
Thanks for sharing @zoladkow 
I replicated the same with a simple 100 x 5000 table

![table](https://cloud.githubusercontent.com/assets/10757813/15149937/beb8e04c-16cb-11e6-8c94-3b28a12f9375.png)

Cells are getting heigher even when there's only a one line of data in each cell.

**Comment by AMBudnik** [comment]
updated example: http://jsfiddle.net/hn2ca308/

**Comment by AMBudnik** [comment]
Hi again @zoladkow 
some time we've changed that the `autoRowSize` works for column headers as well so by adding this option you your code should fix it.

Can you update to 0.30.0 and check it it works for you?

Here with @wszymanski we prepared a simplified demo which works as expected: http://jsfiddle.net/x9xv6efk/

I will close this issue but if we're missing something please leave a comment and we'll investigate it.
