### ISSUE TITLE
Can delete cell contents if editor==false

### ISSUE THREAD

**Issue by mudam** [handsontable/handsontable#3477]
Related to this: https://github.com/handsontable/handsontable/issues/2701

Having set `cellProperties.editor = false` the cell can not be edited but (at least on Mac system) I can hit 'delete/backspace' key and the cell contents gets cleared.

For demonstration use the same example http://jsfiddle.net/cou1oxju/2/ :

1. Key in some data
2. Hit 'update'
3. Try to edit 1st column - locked. Good!
4. Select cell in 1st column, hit backspace. Not good.

I can not use `readOnly` for the reason outlined in the linked issue.

**Comment by AMBudnik** [comment]
Hi @mudam 
I don't think that the editor should block the operation made on cell (we are using the <kbd>backspace</kbd> on cell not inside of an editor).
Please check this demo http://jsfiddle.net/vrv9pbaj/ you can add a `beforeKeyDown` callback to block the <kbd>backspace</kbd> button.
