### ISSUE TITLE
add a manualRowFreeze option

### ISSUE THREAD

**Issue by ahlunju** [handsontable/handsontable#3478]
Hi,

I've been digging through the documentation, I only found **fix columns/rows** and **manualColumnFreeze**, but there is no "**manualRowFreeze**". Is this feature currently available? If not, is there a way to implement it on my own?

Thanks

**Comment by AMBudnik** [comment]
Hi @ahlunju 
You're right, we do not have a `manualRowFreeze` option. Currently it would be very hard to create this feature from a scratch as we do not have any `freezeRow()`/`unfreezeRow(`) methods

**Comment by ahlunju** [comment]
Thanks AMBudnik. It would be nice to have this feature. Is there a plan for releasing this feature in the future?

**Comment by AMBudnik** [comment]
I'll rename the issue for 'add a `manualRowFreeze` option` and keep it as a feature request.

If you would like to know what we are doing currently, please visit our roadmap: https://trello.com/b/PztR4hpj/handsontable-roadmap-2016-login-to-vote-for-features If you can create a Trello account you'd be able to vote for features.

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
