### ISSUE TITLE
Unable to determine the row of a cell dropdown when source option of a column is specified.

### ISSUE THREAD

**Issue by garypma** [handsontable/handsontable#3479]
How can you determine which row is being addressed when a dropdown is being invoked. For example I have the following column defined in a hansontable:

{ data: 'tmoption', type: 'dropdown', source: loadOptions, width: 70 }

The javascript for the function looks like this:

     var loadOptions = function (query, process) {
            var table = hotRegisterer.getInstance('compTable');
            // Where do I get the row from???
            compGridService.getList('usa').then(function (data) {
                process(data);
            }, onPoListError);
        };

The getList returns a list of options based upon the parameter specified, the data returned isn't relevant to this issue.

I need to know the data of the row so I can pass in the correct parameter into my api. Right now it’s hard coded to ‘usa’, but it's variable based upon the data in the row. I believe someone tried to answer this issue before, but it wasn't ever really answered.

**Comment by AMBudnik** [comment]
Hi @garypma 
You can use a getSelected() method. Selected row is first of the selection array - getSelected()[0]
Does it solve the issue?

**Comment by garypma** [comment]
Yes, that solves the problem. Thank you.

**Comment by AMBudnik** [comment]
Great. Have a nice day.
