### ISSUE TITLE
autoRowSize should work also for the column headers

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3480]
When column headers content has different lengths, scrolling horizontally causes the headers to change height along the way. `autoRowSize` should take care of this, the same way as it does with regular rows.

----------

#### Steps to reproduce:
1. Go to http://jsfiddle.net/js_ziggle/usq6eeoy/
2. Scroll to the right

**Result:** The column headers change their height while scrolling.

Possibly connected issues: #3476, #2778

**Comment by zoladkow** [comment]
Hi, 
One thing to note in regard to #3476 - in our use-case we actually want to have `autoRowSize: false` to disable wrapping in data cells while also having column headers wrapped and resized in height if necessary. 
Other possibly related settings we use: 
```
colWidths: 200,
autoColumnSize: false,
manualColumnResize: true
```
With this we have a nice and consistently looking table with easily identifiable columns, even if header is very long (like: 'blabla_num_bla_item_123_val_bla')

So, if having  `autoRowSize` work on column headers would eliminate the "jumpiness" of header heights but still allow dynamic wrapping, this would be great :)

**Comment by krzysztofspilka** [comment]
Set autoRowSize: true to make it work.
_Still on branch develop._
