### ISSUE TITLE
Unable to close cell editor on the last col position after changes

### ISSUE THREAD

**Issue by 3cL1p5e7** [handsontable/handsontable#3481]
Bug in methods onModifyCol and onUnmodifyCol of file "handsontable.full.js":
Condition "typeof this.getVisibleColumnIndex(col) == -1" not performed.
Result of function "this.getVisibleColumnIndex(col)" is number, "typeof" is excess

**Comment by AMBudnik** [comment]
Hi @3cL1p5e7 
Could you also include a demo where we can reproduce the bug?

**Comment by 3cL1p5e7** [comment]
https://jsfiddle.net/ud6Lx536/22/
very ugly example, but this is shows my bug.
Sequencing:
1. DoubleClick on the any cell, but not cell in last column
2. in Editor set new value
3. Click on the another place for closing Editor.
It is worked.

But if repeat this sequence for any cell in LAST column - step 3 not worked.

**Comment by AMBudnik** [comment]
It seams that the issue lays in `manualColumnMove: true` settings if the last column is one of the following: 
* `numeric` type
* an `autocomplete`
* `date` type
There's no console errors.

Simplified demo: https://jsfiddle.net/n78muo1o/

**Comment by 3cL1p5e7** [comment]
Yes, because "typeof this.getVisibleColumnIndex(col) == -1" fires after validation. Thanks.

**Comment by AMBudnik** [comment]
Hi @3cL1p5e7 
I tried to replicate the issue in the latest version however the demo is pretty complicated. Can you check if it still occur in 0.30.1?

**Comment by AMBudnik** [comment]
I assume we can close this issue as there is no reply.
