### ISSUE TITLE
Merge cells - detect a change in merged cells collection

### ISSUE THREAD

**Issue by martinkotula** [handsontable/handsontable#3482]
Is there any easy way to detect change in merged cells collection?

I can't see any callback similar to `afterCreateCol/afterRemoveCol`. Merge/unmerge operation isn't also added to `hot.undoRedo.doneActions`, see [Merged cells demo](https://docs.handsontable.com/0.24.3/demo-merged-cells.html) and the undo operation is not available.

So the only workaround I can think of now is to look for a change in `hotInstance.mergeCells.mergedCellInfoCollection` between `afterContextMenuShow` and `afterContextMenuHide` events. Am I missing something?

**Comment by AMBudnik** [comment]
Unfortunately currently accessing the `mergedCellInfoCollection` is the best solution to get the collection of merged cells.
And you're right we should add more actions that can use a undo/redo option. This idea was already written in our feature requests https://github.com/handsontable/handsontable/wiki/Feature-requests at pos.96

**Comment by martinkotula** [comment]
Right, thanks for the answer
