### ISSUE TITLE
Handsontable: Context menu disabling in case of single row in the table

### ISSUE THREAD

**Issue by ravi590** [handsontable/handsontable#3484]
When trying to add a new row(row_below)/delete row, the options in the context menu are disabled when there is only one row in the table
![contextmenu_disabled_issue](https://cloud.githubusercontent.com/assets/7116448/15178384/d9909794-1792-11e6-8ea3-a9fbcb71fdac.png)

**Comment by AMBudnik** [comment]
Hi,

I made a demo with a single row also http://jsfiddle.net/vg45pcmg/ and it works as expected. Can you share your grid's settings?

**Comment by ravi590** [comment]
Hi @AMBudnik ,Please find the fiddle below

http://jsfiddle.net/eh4uor0g/

**Comment by AMBudnik** [comment]
you are using 0.16.1 version of Handsontable. If you'll update to newest version this bug is gone.
