### ISSUE TITLE
Handsontable: Insert new row at specific index in case of sorting

### ISSUE THREAD

**Issue by ravi590** [handsontable/handsontable#3485]
I am trying to insert a new row in sorted table using "row_below" option in Context Menu, Currently the new row is creating at the bottom of the page.I want sorting to retain and where ever i click on insert row_below option i want to create new row instead of at bottom.Is it possible?

**Comment by AMBudnik** [comment]
If you would like to pick where to add an empty row you can use an `alter` method, here's an example: http://jsfiddle.net/xLe0n9vb/

**Comment by ravi590** [comment]
Hi @AMBudnik , The example you provide is for adding row using external button, instead of that can we achieve the same using context menu("row_below") option, because we don't know at what index user will open context menu.

**Comment by AMBudnik** [comment]
We do not provide such option but you can pass a function to a context menu to achieve that. In this case your function would have to take a row as an argument (you can take it from `instance.getSelected()[0]` ) and if the row is `x` the [`alter()`](https://docs.handsontable.com/pro/1.3.4/Core.html#alter) method will add a row at `x + 1`.

Here's a tutorial how to pass a function inside a contextMenu: https://docs.handsontable.com/pro/1.3.4/demo-context-menu.html
