### ISSUE TITLE
Overlay scrolling visibly lagging on Edge

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3486]
When scrolling the main overlay on Microsoft Edge, it hides outside the viewport and takes a long time to re-sync.

---
#### Steps to reproduce:
1. Go to http://past.handsontable.com/demo/scroll.html using Edge
2. Scroll the main part of the table

**Result:** The table is hardly usable.

**Comment by swistach** [comment]
Related with: #1761

**Comment by swistach** [comment]
The scrolling mechanism was changed in v0.38.0+. Currently, it works better.
