### ISSUE TITLE
Fixed columns are misaligned when they contain additional elements

### ISSUE THREAD

**Issue by nulayuhz** [handsontable/handsontable#3488]
Hi, demo: http://jsfiddle.net/wbn6hmoj/4/

The problem I am having is that I have a custom renderer which displays two button when I select on the <TD>. this is done through the event callback **afterSelection**. The callback loops through all the <td>s to remove the "hide" class on the <td> that I selected. 
![capture2](https://cloud.githubusercontent.com/assets/3287446/15197487/ae06ce7e-179f-11e6-920b-064dcf2f24b1.PNG)

But when selecting on the cell in the frozen column, the hidden element does not get revealed, and after some investigation on the HTML, I found that the freeze column is a cloned <tbody> layed on top of the actual column, selecting the clone will trigger an afterSelection on the actual cell. In the screenshot, I changed the absolute position of the clone reveals the actual cell being does display the hidden buttons.

![capture](https://cloud.githubusercontent.com/assets/3287446/15197402/474030fe-179f-11e6-88e2-e1ab14b818a8.PNG)

What I really want is the have the afterSelection work on the clone as well, so I can access the buttons when the column is frozen.

**Comment by AMBudnik** [comment]
I wasn't able to reproduce the same effect as shown above but in this example you're loading 0.24.3 version of .js file and 0.15.0-beta1 version of .css
Please check this example (updated .js and .css to 0.24.3) http://jsfiddle.net/uwh0jzmn/ - does it work as expected?

**Comment by ahlunju** [comment]
In your example http://jsfiddle.net/uwh0jzmn/

The freeze column is not displaying the custom buttons, only the actual cell behind it is displaying.

Screenshot: Car Model column is froze, when selecting on it, the actual cell behind does display the custom buttons (you can notice the height of the row expanded because the buttons are displayed)
![capture3](https://cloud.githubusercontent.com/assets/3287446/15215978/148e9126-1823-11e6-9dee-97639de0d011.PNG)

**Comment by AMBudnik** [comment]
You right, I didn't freeze the column.
I tested this code and it's not the best solution but maybe you could stretch rows a little bit, for example give them `rowHeights: 50`, like here: http://jsfiddle.net/c7r3eunq/

**Comment by ahlunju** [comment]
The problem is I can't make the freeze column to display the buttons.

**Comment by AMBudnik** [comment]
I'll leave this issue for testing. It looks like a bug. Like not the whole content is being moved to the top of the table while fixing the columns.

I got this when I added buttons the `position: fixed`
![fix](https://cloud.githubusercontent.com/assets/10757813/15249746/85f5c934-1921-11e6-85d4-e49eb70ed621.png)
 so it's there but under the duplicated column.

The button inside has to get `position: fixed` and `z-index` above `102` as `102` is the `z-index` for the fixed column. I can't say it's a workaround but definitely a clue.

**Comment by AMBudnik** [comment]
Still replicable in 0.30.1. If we fix a column button doesn't appear

We can see that the right part of the table is resizing in height so it means that we should rebuild the whole structure of the column and update it if needed, Currently I guess that we are only adding a layer filled with getData() values so in many cases rows gets mialigned

![image](https://cloud.githubusercontent.com/assets/10757813/22146892/9c4a3426-df06-11e6-986b-74b2e650796b.png)

**Comment by AMBudnik** [comment]
It looks like the same in v `7.1.0` http://jsfiddle.net/handsoncode/tur240b3/ (simplified demo)

![image](https://user-images.githubusercontent.com/10757813/61376168-ee6f0e00-a8a0-11e9-8871-66702c56d4f2.png)

**Comment by wojciechczerniak** [comment]
Works as expected.

Handsontable uses `renderers` to generate innerHTML for cells. If it needs to duplicate the content on fixed column layer it can. The example shown above travels the DOM, modifies it and breaks Handsontable logic. Sorry, but it won't work like that.

All DOM manipulation on TD and its content should take place in the renderer. 
Something like: https://jsfiddle.net/Lync7bja/
