### ISSUE TITLE
Handsontable problem inside angular bootstrap tab

### ISSUE THREAD

**Issue by cssahu** [handsontable/handsontable#3489]
I have two tabs in angular ui bootstrap.Inside one tab-container i implemented handsontable. When for the first time the page is loading the handsontable is rendered properly but when I click on the 2nd tab and come back to the first tab which contains the handsontable grid, it is not rendered.When I double click on the tab it is rendered and the width of the grid is also squeezed.

**Comment by AMBudnik** [comment]
Hi @cssahu 
Could you check if it relates to one of those issues?
https://github.com/handsontable/handsontable/issues/2779 or https://github.com/handsontable/handsontable/issues/2937?

**Comment by ddehghan** [comment]
I see the same problem. Actually this is not the same as Modal dialog. 

When tab  with a handsontable inside is first opened it will have a rendering problem. Only the first column of the table is rendered. When you click on the table it expands to the correct size. 

I could not work around it. So I changed my design to bring the table outside of tabs and then it works correctly.

**Comment by cssahu** [comment]
This is not same as the modal dialog issue, Please check thes plunker code
http://plnkr.co/edit/CzQV4I75S5auk5G7DZM8?p=preview

**Comment by AMBudnik** [comment]
Thanks for sharing demo @cssahu and for your feedback @ddehghan 
Indeed we're missing two columns which are shown after a button click.

**Comment by rodolfosouza** [comment]
I fixed my issue including **viewportColumnRenderingOffset:(number of columns)**

**Comment by AMBudnik** [comment]
Thank you for your effort @rodolfosouza 
@cssahu is this solution works for you as well?

**Comment by AlexanderArmua** [comment]
I had this problem using typescript, the next function waits for the modal to load and then with the timeout in 0 like parameter, waits to be executed at the end of the execution to execute the function that brings all the elements to the table.

```javascript
$('#modalid').on('shown.bs.modal',  () => {
    this.$timeout( () => {
        this.getTableInfo();
    }, 0);
});
```
Sorry if you can't understand my english XD

**Comment by AMBudnik** [comment]
I think that we can close this subject as most of the subject has been already covered and one most important thing to remember is to try to rerender the table when it is placed in an element with the `display: none` settings or an element without height/width defined.
