### ISSUE TITLE
How to persistent the handsontable meta? Like merged cells

### ISSUE THREAD

**Issue by pinkdawn** [handsontable/handsontable#3490]
I have a question, how to persistent the 
- merged cells
- cell alignment
- setCellMeta

I understand that, by manually put `mergeCells` and `alignment` into `setting options`, I can use that setting to re-generate it. However, if the alignment and merge are change from context menu, how do I re-play this operation?

My other question is, `is there any the context menu called by code`? Now it can only trigger by manually cilck.

In my case, I want to implement a report designer using handsontable. At design page, we make custom configurations to cells (color, font, alignment, borders, merged some cell), set the data source, and finally we export the report page.

At the finally page, besides the data source, we also need to re-generate the cells that we designed in previous step.

**Comment by jansiegel** [comment]
@pinkdawn Unfortunately, Handsontable doesn't support this out of the box. You can, however, achieve it with some additional effort.

1. Sure, you can open the context menu using our API. To do that, you’ll need to select a cell (using `hot.selectCell(1,1)`), then call:
```js
hot.getPlugin('contextMenu').menu.open();
hot.getPlugin('contextMenu').menu.setPosition({
	top: topCoords,
	left: leftCoords
});
```
where `topCoords` and `leftCoords` define where to context menu will be displayed.

2. The `mergeCells` plugin stores its settings under `hot.mergeCells.mergedCellInfoCollection` array. To recreate the table using those hand-made settings, you'd need to utilize it.

Please take a look at this example: http://codepen.io/js-ziggle/pen/vXagRp/ 

When you merge some cells, click the `Destroy` button and then the `Recreate` button, the merged cells should also be applied.

3. Cell alignment is stored as a cell meta. This time we'll need to use the `hot.getCellsMeta()` method. It returns an array of the cell meta objects of all cells in the table. When you have those, you can reapply them to the newly created table.

Take a look at this: http://codepen.io/js-ziggle/pen/pEkZEy/

This demo contains some additional logic to filter the cell meta object which don't consist any additional information except for the standard stuff.

Of course you'll probably need to tweak these examples to fit your needs, but I hope they'll give you some general direction to do that.
