### ISSUE TITLE
minSpareRows: 1 but showing 5

### ISSUE THREAD

**Issue by sambsa** [handsontable/handsontable#3491]
I have a handsontable as follows in my fiddle. [http://jsfiddle.net/7c5dD/146/](http://jsfiddle.net/7c5dD/146/). I have given minSpareRows: 1. But I am getting 5 rows. Please clarify this issue.

**Comment by sambsa** [comment]
I had added data:[] and updated the fiddle , now working fine. You can close this issue.

**Comment by AMBudnik** [comment]
Hi @sambsa 
That's right! `data` settings even if - at the beginning - it's an empty array of arrays `data: [[ ]]` has to be provided.

When Handsontable does not have a `data` settings passed it's using defaults, which as you can see here: http://jsfiddle.net/qdrfo8gz/ has `5` rows and `5` columns.

**Comment by sambsa** [comment]
Thanks buddy, I tried a lot and finally found it myself. Thanks for the detail explanation.
