### ISSUE TITLE
Max column width 

### ISSUE THREAD

**Issue by aaronclawrence** [handsontable/handsontable#3492]
Hello,
We have a somewhat strange use case where people are typing long paragraphs into HOT.
This results in incredibly wide columns - wider than the grid itself - which are really hard to edit.

I was trying to figure out how to apply a max column width so this situation is more usable.
I couldn't tell what was the appropriate place to do this - or how.
I thought getStretchedColumnWidth might do it, but that doesn't seem to fully work for editing.

At least, it would be good to limit the column width to the same as the grid...

Can anyone give me some tips on where to start?
Thanks
Aaron

**Comment by AMBudnik** [comment]
Hi @aaronclawrence 
Currently you can set a fixed width of a column, like here: http://jsfiddle.net/0abq6vxp/ or change the `colWidths `accordingly to the length of a value, like here: http://jsfiddle.net/1omqtr3L/

**Comment by aaronclawrence** [comment]
Hello AM, thank you. I realise that HOT doesn't currently have the feature I need.
I want to enhance the source code of HOT to do max column width. I was hoping someone could suggest where in the source code to start doing this.

**Comment by AMBudnik** [comment]
You are right @aaronclawrence we do not support this feature yet. It is currently marked as a feature request: https://github.com/handsontable/handsontable/issues/2216

**Comment by aaronclawrence** [comment]
I don't understand.#2216 has been closed, as has the one it refers to #2236. So there is no open issue to add this?

**Comment by AMBudnik** [comment]
sorry @aaronclawrence I forgot to reopne https://github.com/handsontable/handsontable/issues/2236
I'll mark it as a feature request.
