### ISSUE TITLE
clone header position when fixed content on page

### ISSUE THREAD

**Issue by pramodsvidyarthi** [handsontable/handsontable#3493]
If we do not specify the height of the table the normal behaviour when we scroll the page is the header gets fixed at the top till entire table is scrolled. which is an awesome feature. Just in case we happen to have a fixed section on our page is there a way we can go about and till the hot grid to fix the clone header below to the fixed header.

Consider the following 

In the below fiddle link the header or hot grid gets frozen to the top on scroll.
http://jsfiddle.net/26gLz0zf/

And in this fiddle http://jsfiddle.net/61z3d9v6/ there a frozen section on top but we what is expected is the header should freeze below the fixed section on top.

**Comment by AMBudnik** [comment]
Thanks for sharing @pramodsvidyarthi

**Comment by AMBudnik** [comment]
Hi,

Thanks again for sharing this Feature Request. I am moving it to our Wiki Section at https://github.com/handsontable/handsontable/wiki/Feature-requests
The issue will stay closed until it'll get picked by our developer.

**Comment by andrey-semenov** [comment]
Would like this feature implemented as well.. currently customers are complaining that the header is never visible on their smaller screens after they scroll due to a fixed navigation menu at the top of the page. Any hack or temporary workaround would also be welcome!

**Comment by AMBudnik** [comment]
Hi @Raphael007123 The bottom row has `position: fixed` for the bottom of the container. For shorter tables, you'd need to shorten the container as well.

**Comment by AMBudnik** [comment]
Hi @Raphael007123 
currently, you would need to use an extra wrapper for Handsontable element and set a fixed dimensions (in pixels) to make it work http://jsfiddle.net/pdrtkj09/

**Comment by Raphael007123** [comment]
Hi @AMBudnik 
Thanks for the update. I need the table header get fixed in my window scroll. At that time its making conflicts with the page header.  you can check at http://plnkr.co/edit/wFyBiwxRN9En0VdgHeMj?p=preview

**Comment by AMBudnik** [comment]
Then in your case, it would be something like this http://plnkr.co/edit/sX0971Ein7Fm6PaN8D3s?p=preview @Raphael007123

**Comment by Raphael007123** [comment]
@AMBudnik I'm expecting the scroll on the window not in the table. on scrolling, table header should get fixed under the page header (note: page header is also fixed)

**Comment by AMBudnik** [comment]
I understand but currently, it is not possible @Raphael007123

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. Please free to continue the conversation there. Thank you.
