### ISSUE TITLE
Custom cell editors

### ISSUE THREAD

**Issue by martinkotula** [handsontable/handsontable#3494]
Are there any plans for allowing to create custom cell editors?

I'm using an object like: 
`{ 
value: "cell value", 
... // some other properties needed by my custom renderer
}`

Combined with a custom renderer to format each relevant cell individually. I tried to keep this cell metadata separate, in a structure indexed by rows and columns, but then I had to keep it in sync with the changing structure of the table - row additions etc.

So I ended up storing an object as cell value and a custom renderer to display it. Everything seems to work fine except for the editors, haven't also noticed any downgrade in performance.

Ideally what I would need is to have the ability to create a custom editor based on the built in text editor  which would know how to edit the object - in my case by getting/setting the `value` property of the cell.

Is there any potential pitfall in the approach I'm using? Storing objects as cell values?

Sorry for the long description. I'm really impressed by your product ;)

**Comment by AMBudnik** [comment]
Hi @martinkotula 

Thank you for the kind words.

Actually there is a very helpful tutorial one of our colleges wrote about how to create a custom editor. Here it is: https://docs.handsontable.com/pro/1.3.4/tutorial-cell-editor.html

There's no demos there but a lot of code examples and if you'd have any difficulties with methods presented there just drop us a line.

**Comment by martinkotula** [comment]
Thanks! Don't know how I could miss that ;)
