### ISSUE TITLE
Is there any event handler in case of select dropdown open?

### ISSUE THREAD

**Issue by ravi590** [handsontable/handsontable#3495]
Hi @AMBudnik , Can you help me on this? I am using select dropdown for cells  in rows  of handsontable. Until i don't scroll the table, the select dropdown is rendering on the cell where i have double clicked.Once i scroll down, and double click on new row, the select dropdown is rendering far away from the cell where i double clicked.

**Comment by AMBudnik** [comment]
Hi @ravi590 
Sure, I'll do my best to help. 
Please share the following example using JSFIddle. It sounds like a bug. You can use this example http://jsfiddle.net/pzuea6nb/ as a base if you want.

**Comment by AMBudnik** [comment]
Hi Ravi, how is your progress with this case?
I'm closing it as we didn't got a demo for more than a month but feel free to leave a comment.
