### ISSUE TITLE
Paste option in context menu does not work

### ISSUE THREAD

**Issue by Laplandia** [handsontable/handsontable#3496]
Steps to reproduce:
1. Copy some data from excel table.
2. Open http://docs.handsontable.com/0.24.3/demo-context-menu.html#page-copy-paste
3. Try pasting using context menu

Nothing happens.

Bonus:
4. Paste using cmd+v (ctrl+v)
5. Try pasting again using context menu

It works now.

**Comment by AMBudnik** [comment]
Hi @Laplandia 
Unfortunately you're demo is empty.
Can we test it on http://jsfiddle.net/d4kh3hor/?
ps. default context menu doesn't allow to simply paste the data. Please add the option to test it.

**Comment by Laplandia** [comment]
Sorry. Here is the right link: http://docs.handsontable.com/0.24.3/demo-context-menu.html#page-copy-paste

**Comment by AMBudnik** [comment]
Thanks for sharing. You're right - it's not pasting with the context menu.

**Comment by AMBudnik** [comment]
Works as expected (data is copied) in 0.30.1, demo: http://docs.handsontable.com/0.30.1/demo-context-menu.html#page-copy-paste
Again thanks for sharing.
