### ISSUE TITLE
Can't have less than 5 columns

### ISSUE THREAD

**Issue by pricejt** [handsontable/handsontable#3498]
If you specify less than 5 columns than it uses letters. 

`var container = document.getElementById('TestCasesImport');
                var hot = new Handsontable(container,
                 {
                     colHeaders: ["Name", "Value", "DataType"],
                     height: 300`

This will display Name, Value, DataType, D, E
I just want 3 columns displayed.

**Comment by AMBudnik** [comment]
Hi @pricejt 
If you want to display only fixed amount of columns while your data has more of them you should use `columns` option like in this example http://jsfiddle.net/ohazyn0o/ 
In this example data provides 4 columns and I'm displaying only first two of them.
