### ISSUE TITLE
Feature request: support cell styling as part of the model

### ISSUE THREAD

**Issue by GabiAxel** [handsontable/handsontable#3499]
Currently the way to style cells is with conditional rendering. This way everyone implements their own way of storing, editing and rendering styles, and since styling is not really part of the cell model, it is not included when copying cells between Handsontable instances or between Handsontable and external spreadsheet programs.

I propose adding a few basic styles to the cell model (I would suggest text color, background color, font family, size, weight, style and decoration) which would be included in the cell content when copying and pasting it.

**Comment by AMBudnik** [comment]
Thanks for sharing your proposition @GabiAxel

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
Hi All.

We are moving feature ideas and improvements to Github Discussions to gather all the ideas on UI and API. That will help us to continue the development of the functionality in the future.

Please feel welcome to share your feedback via the Github Discussions panel if you have any additional ideas.
