### ISSUE TITLE
Cannot edit cells continuously if using ime

### ISSUE THREAD

**Issue by tsujio** [handsontable/handsontable#3500]
I use Japanese ime to edit cells. In my environment, the following behavior is occurred.

1. Click a cell and select it
2. Type 'a' key (or any other key) and start editing (editor is opened)
3. Toggle ime to Japanese mode
4. Type enter, tab, or escape to exit editor
5. Type 'a' key (or any other key) to start editing with Japanese, but no action occurred.

It seems to be because the textarea is still focused after editor closed. I will send pull request.

**Comment by AMBudnik** [comment]
Thanks for your effort and the pull request @tsujio

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topics and uploading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Issue will be reopened with the first update.
All comments, investigation results or suggestions are welcome.

**Comment by AMBudnik** [comment]
We have improved IME handing and this issue should no longer occur.

Please send me an email to support@handsontable.com it still occurs in your project after updating to the newest version.
