### ISSUE TITLE
get cell value on right click

### ISSUE THREAD

**Issue by jmtolibas** [handsontable/handsontable#3503]
Hi, i've created my custom context menu. May I know how to get the cell value when I right click the cell?

**Comment by AMBudnik** [comment]
Hi @jmtolibas 
This code prints you a cells value in the console after the <kbd>RMB</kbd> was clicked

```js
 afterOnCellMouseDown: function(event, coords, TD) {
	if(event.button === 2){ // '2' stands for the RMB
           console.log(TD.innerHTML)
     }
 }
```

Demo: http://jsfiddle.net/handsoncode/0t4crqb9/

**Comment by jmtolibas** [comment]
Hi @AMBudnik , thank you so much!

**Comment by AMBudnik** [comment]
You're welcome @jmtolibas 
Keep my fingers crossed for your progress.
