### ISSUE TITLE
removeRow fails after using loadData

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#3504]
Hi, 

I update my grid with `hot.loadData` method and it works fine, but when I am trying to remove row using context menu I am getting the following error: `handsontable.full.js?67d7:6438 Uncaught TypeError: Cannot set property 'forceFullRender' of null`. The problem is in the last row of `removeRow` method;
`this.instance.forceFullRender = true;`, for some reason `this.instance` is null.
If I don't use `hot.loadData` - row removal works correctly.
What am I doing wrong?

**Comment by AMBudnik** [comment]
Hi @andrewQwer 
Can you share your instance's settings? 

I made a simple example where we can check the above http://jsfiddle.net/handsoncode/rh43Lbkf/ but I'm not getting any logs and row can be removed after I add `newData` (array od arrays) or `objectData` (array of objects) using `instance.loadData()` method.

**Comment by andrewQwer** [comment]
Hi @AMBudnik 

I found out the reason of this issue. Check out this fiddle: http://jsfiddle.net/andrewQwer/rh43Lbkf/4/
The problem is that I trigger `loadData()` inside `afterRemoveRow` event handler. Is it an expected behavior?

Thanks,
Andrey

**Comment by AMBudnik** [comment]
Thanks for demo Andrey.
You're right the bahavior is not intended. If the hook is called `afterRemoveRow` the data should be loaded after the action and we get data without one row cause it's deleted in the meanwhile.
The second case it's the error in the console and the case with the blocked `removeRow` action.

**Comment by andrewQwer** [comment]
Ok, got it! Thank you for the explanation. This issue can be closed.

**Comment by AMBudnik** [comment]
@andrewQwer I think that we should keep this opened as there are some things that have to be fixed.

**Comment by swistach** [comment]
In this case, situation is as like:

1. DataMap.prototype.removeRow launches afterRemoveRow (this instance of DataMap is our X),
2. afterRemoveRow launches hot.loadData(...),
2.2. loadData has instance X, but to load new data properly, instance X have to be destroy,
2.3. loadData creates new DataMap (our Y), sets new data and launches afterChange hook
2.3. loadData back to DataMap.prototype.removeRow
3. Unfortunately, "this.instance" has reference to instance X (now X returns null, becouse not exist)
It's simple example of this lifecycle, unfortunately, this's not easy to change.

That's can be discussed in dev team, how we can avoid problem with reference to destroyed instance.

**Comment by AMBudnik** [comment]
Issue still replicable in v0.35.0. Update demo http://jsfiddle.net/a6rm2o8q/

**Comment by AMBudnik** [comment]
Hi @andrewQwer 

It looks like it's no longer an issue in v `2.0.0`, updated demo: http://jsfiddle.net/w65339h5/
Can you check that, please? If it still doesn't work for you I'll reopen the ticket.

**Comment by SCollinA** [comment]
Thanks @AMBudnik and others for their contributions to this discussion so far. However, I am still able to reproduce this issue.

I forked the fiddle mentioned in the previous response and updated it to demonstrate the issue.

http://jsfiddle.net/Lqkojewz/

Wrapping `loadData` in a `setTimeout` resolves the error but presents concurrency issues where I can't _guarantee_ that code has executed before other code such as `afterChange` hook callbacks.

**Comment by AMBudnik** [comment]
Hi @SCollinA please follow this issue for updates https://github.com/handsontable/handsontable/issues/5525 The issue is not only related to the `afterRemoveRow` hook.
