### ISSUE TITLE
Add or create a date-time picker

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3505]
One of our friendly developers wrote:

> I wish you have option or change from pikaday to this http://xdsoft.net/jqplugins/datetimepicker/ as its also free but have date and time in one shot.

This is how Datatimepicker looks like

![date-and-time](https://cloud.githubusercontent.com/assets/10757813/15292374/2c8dc284-1b83-11e6-9470-535806a61d62.png)

I personally would add options to show:
* half an hour
* quarters
* full time with minutes

**Comment by maengkom** [comment]
Thank you for add the issue as a feature.

I use that plugin and it have great options and configuration such as : can be as timepicker or datepicker only, and also display format. It would be great if you can integrate it into handsontable.

Yes option to show half and hour, quarters, etc will be nice. For the first step, if you just only integrate it, that's initial big step I think.

**Comment by artbels** [comment]
+1 for datetime picker. I have a problem with sync between handsontable data type and JS data type in my https://www.npmjs.com/package/mongo-table-admin

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by Kylar182** [comment]
I'm a paid sub, let me know when this is released if you could please

**Comment by AMBudnik** [comment]
I will update you once we add it @Kylar182

**Comment by Kylar182** [comment]
> I will update you once we add it @Kylar182

Thanks, my interest is primarily to have a column 'type' of datetime instead of just 'date' so as to set sorting and string view config. While the date-time picker would be nice, it's not my primary motivation

**Comment by nethore** [comment]
Hi,
Any update on that?

**Comment by AMBudnik** [comment]
It hasn't been added to the milestone yet @nethore

**Comment by marcelosanchez** [comment]
Hi,
Any update?

**Comment by AMBudnik** [comment]
Hi @marcelosanchez when we plan to add a feature we reopen the topic and add a milestone. I will surely update you once we push the first commit.

**Comment by eduardoalvara2** [comment]
+1 for datetime picker

**Comment by RanaOsamaAwadallah** [comment]
Need this too, hope we see it soon

**Comment by AMBudnik** [comment]
I'm moving this topic into Github Discussions where we will be able to share our ideas for UI and UX.
See you there!
