### ISSUE TITLE
'afterCreateRow' hook should call callback only once with pasting data

### ISSUE THREAD

**Issue by HaroldStruwig** [handsontable/handsontable#3507]
When there are more rows in data to paste than what is currently available, it automatically creates rows. This is great.

An improvement needs to be made to only call the 'afterCreateRow' hook callback once with the amount of rows created. Currently it calls it multiple times with the 'amount' argument remaining 1 for each new row created.

**Comment by AMBudnik** [comment]
Thank you for your suggestion @HaroldStruwig 
I personally think that it is expected that it returns a single row rather than a range of rows. I will leave this subject for other team members to check.

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topic and uploading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Issue will be reopened with first update.

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. Please free to continue the conversation there. Thank you.
