### ISSUE TITLE
Incorrect handler size in Manual{Column,Row}{Resize,Move} plugins

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3508]
The handler is not adjusting its size according to column header height. The same situation occurs for the row headers.

--------

##### Steps to reproduce:

* Go to http://jsfiddle.net/v16v6tow/2/;
* Bug 1: Column resize handler height was not adjusted.
* Bug 2: Handler fence is disappearing after was dragged under left or top overlay.

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/3287

**Comment by jansiegel** [comment]
Fixed in #3480

**Comment by krzysztofspilka** [comment]
Indeed, all tasks are put together all the connected tasks in #3287

**Comment by AMBudnik** [comment]
Released: 0.25.0
