### ISSUE TITLE
afterValidate with Undo do not work

### ISSUE THREAD

**Issue by anagas** [handsontable/handsontable#3509]
Hello,

 i try to use undo in afterValidate function. 

        afterValidate: function (isValid, value, row, prop, source) {
            if (!isValid) {
                hot.undo();
            }
        }

Is it possible that they dont work togather?

**Comment by AMBudnik** [comment]
Hi @anagas 
`instance.undo()` doesn't work for this action.
Here we have an issue https://github.com/handsontable/handsontable/issues/2109 that suggests to add `undo()` for more actions. Currently it is available for less actions than expected.
