### ISSUE TITLE
Custom Editors: Cannot create new cells with object values.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [handsontable/handsontable#3513]
Suppose you're using the [editor I linked](http://jsfiddle.net/9p9khk3j/2/) to [Issue 3510](https://github.com/handsontable/handsontable/issues/3510)  to edit this data:

```
 var data = [['one','two','three',[['a','b']]]];
```

For the sake of precision, suppose you're using the following `hot_config` (the same one from the [JSFiddle demo](http://jsfiddle.net/9p9khk3j/2/)):

```

var hot_config = {
     contextMenu: true,
     data: data,     
     columns: [ {},{},{},{ 
                                   editor: InnerSpreadsheetEditor,
                                   data_ctor: function() {
                                       return [[null,null]];
                                   },
                                   innerHOTConfig: { contextMenu: true }
                                  }]
}
```

You can freely edit column 'D' using this editor. When you click it, a 1x2 spreadsheet pops
up, and it works properly, in spite of the hack required to work around Issue 3510. The inner
context menu even works as expected, and you can add rows and columns to the inner spreadsheet until it becomes larger than the parent spreadsheet.

 (note: The inner context menu isn't working in the JSFiddle demo, but it's irrelevant to this issue, since `InnerSpreadsheetEditor` will invoke the `data_ctor` function from `hot_config` to create a spreadsheet data object that already has enough cells to reproduce the bug.)

However, if you create a new row in the outer editor's context menu, you will not be able to
make changes to the fourth column because it's `null`:

```
 [['one','two','three',[['a','b']]],
  [null,null,null,null]]
```

This problem seems to stem from a few lines of code found in `core.js` line 498 in the source distribution:

```
                           if (value !== null && typeof value === 'object') {
                               if (orgValue === null || typeof orgValue !== 'object') {
                                   pushData = false;
                               } 
```

If you tried to edit the fourth column so that the inner spreadsheet attempts to save the value `[['b','c']]`, to the outer cell, the change eventually becomes the `value` variable in the lines of code above.

Since arrays in JavaScript are objects, that means `pushData` gets set to `false`, which in turn means that your change never gets added to the `setData` local variable, and never makes it to the call to `setDataAtCell`. As a result, no matter how much you edit the cell, its value refuses to change.

It
may be possible to work around this issue by calling `setDataAtCell` directly from one of the methods of my `InnerSpreadsheetEditor`, perhaps wrapping
the `populateFromArray` closure somehow. I'll try that tomorrow.

**Comment by swistach** [comment]
Hi @heegaiximephoomeeghahyaiseekh 
Thanks for sharing ideas and PR.
Fragment of the code which was removed in PR was created to support of Polymer-hot-table (currently we don't support the polymer version).
Data storing is really important part of the Handsontable and (as it is described in [CONTRIBUTION.md](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md)) pull request has to contain tests.
If you want, you can take vote on '[New cell types](https://trello.com/c/zxbU4oGc/22-new-cell-types)' on our Trello roadmap.
