### ISSUE TITLE
Difference in AutocompleteEditor.prototype.queryChoices since 0.24.2

### ISSUE THREAD

**Issue by ahlunju** [handsontable/handsontable#3514]
Hi,

I was developing using 0.24.0, since I upgraded to 1.4.3 (based on 0.24.3), my dropdown/autocomplete source function does not work as before.

My use case of dropdown source is to set the source function in the columns,
when `source` is called, I have it look up the options through `this.instance.getSourceDataAtRow`
that way I can just have one source function in the columns definition to retrieve the dropdown options for each cell dynamically.

```
{
	columns: [
	{
		source: function(query, process) {
			var instance = this.instance;
			var rowObj = instance.getSourceDataAtRow(this.row);
			var key = this.prop.split('.')[0];
			var cellObj = rowObj[key];
			process(cellObj.dropdownOptions);
		};
	},
	{
		...
	}
	]
}
```
it is working because in the older version (up until 0.24.1), `source` is called from the cellProperties directly, I can have the `this` reference the Core

```
AutocompleteEditor.prototype.queryChoices = function(query) {
  this.query = query;
  if (typeof this.cellProperties.source == 'function') {
    var that = this;
    this.cellProperties.source(query, function(choices) {
      that.updateChoicesList(choices);
    });
  }
  ...

```
since 0.24.2
```
AutocompleteEditor.prototype.queryChoices = function(query) {
  this.query = query;
  var source = this.cellProperties.source;
  var hasFilter = this.cellProperties.filter;
  var filteringCaseSensitive = this.cellProperties.filteringCaseSensitive;
  if (typeof source == 'function') {
    var _this = this;
    source(query, function(choices) {
      _this.updateChoicesList(choices);
    });
```

I am not sure if this change is done intentionally to hide the cellProperties for outside reference, if so, what other ways I can do to get back the cell object.

Thanks.

**Comment by budnix** [comment]
Definitely this is a bug. Thanks for sharing @ahlunju.
