### ISSUE TITLE
How to clear comments in handsontable without table refresh?

### ISSUE THREAD

**Issue by ravi590** [handsontable/handsontable#3515]
@AMBudnik ,I have added comments dynamically based on ajax response using hot.getCellMeta() method.Now again i want to remove previous comments dynamically and add new comments on each ajax response.
Without refreshing the entire table, is there any way to remove the comments dynamically?

**Comment by AMBudnik** [comment]
Hi @ravi590 as far as I'm concerned currently it can't be done by Handsontable without rerendering the table.

**Comment by ravi590** [comment]
Thanks @AMBudnik, We have an option to remove comments at specific indexes using hot.getPlugin('comments').removeCommentAtCell(row,col) method, but i don't know the indexes(not tracking the indexes) and want to remove all existing comments without reloading the table.

**Comment by AMBudnik** [comment]
Hi @ravi590 
If I understand you need something more related to this issue?
