### ISSUE TITLE
Customize filtering feature column by column

### ISSUE THREAD

**Issue by thomascoquet** [handsontable/handsontable#3518]
Hello,

We are using the pro version of Handsontable to display large data frame structures such as in R/python (pandas)/etc.

We would love to provide our users with a filtering feature, however we want to enable filtering on specific columns only: 
- for "factor columns", only let the "filter by value"
- for date/time columns, only let the conditional filtering,
- etc. etc.

If we have more than 1 million rows, we do not see the point of having a "filter by value" on the time column for example (also w.r.t. performance).

Could it be possible to customize filters on a column-by-column basis such as types, renderers, etc. ?

Thank you !

Thomas

**Comment by AMBudnik** [comment]
Hi @thomascoquet 
Thanks for sharing.
We have this feature request already here https://forum.handsontable.com/t/define-filter-conditions-for-a-custom-column-cell/310 at our PRO forum.

Please track changes there.
