### ISSUE TITLE
Can I get only changed row data for save

### ISSUE THREAD

**Issue by YozhEzhi** [handsontable/handsontable#3520]
I didn't find solution for my case.
I want to trigger `afterChange` method manually.
I.e. user changes lot of cells and then saves changes by click on button manually.
I've tried this:
```
afterChange: function(changes, source) {
  if (source !== 'loadData') {
    var changedData = JSON.stringify(changes);
    console.log(changedData);

    $.post('some_url', changedData);
  }
},
```
```
el.addEventListener('click', function() {
  handsonInstance.runHooks('afterChange');
});
```

But I got `undefined`.

**Comment by AMBudnik** [comment]
Hi @YozhEzhi 
`afterChange` will fire anyway but to gather changes you can create something like this  http://jsfiddle.net/handsoncode/uchtuybs/

**Comment by YozhEzhi** [comment]
@AMBudnik That's kind a workaround but I'll try it.

Thanks for instant reply!
