### ISSUE TITLE
How to retrieve meta data

### ISSUE THREAD

**Issue by Yimiprod** [handsontable/handsontable#3521]
Hi

Is there a way to get the params applied on an handsontable.
My use case:

> I display an handsontable in a form with 5 cols and 5 row, the user set some data in each cells, then merge 3 cells and set a column with text centered, and another with text aligned to the right.
> Then he save the form
> The user come back on the form the table he defined is displayed like he entered it

At the moment, i know how to get the object from `hotInstance.mergeCells.mergedCellInfoCollection`.
But how to get the `alignment` parameters ?

**Comment by AMBudnik** [comment]
Hi @Yimiprod 
When it comes to aligment you can use added class names, like in this example: http://jsfiddle.net/handsoncode/9jLgadLf/
