### ISSUE TITLE
Add severals filters to one column [Handsontable PRO]

### ISSUE THREAD

**Issue by joelmora** [handsontable/handsontable#3522]
Hi! I am trying to add severals filters to one column with the filter plugin, but It doesn't work

Here is my code:
```
hot.getPlugin('filters').addFormula(1, 'eq', ['et']);
hot.getPlugin('filters').addFormula(1, 'eq', ['elit']);
hot.getPlugin('filters').filter();
```
the previous code only filter the _**'elit'**_ rows, but what I wanna do is **_'et'_ OR _'elit'_**, is this posible with the current version?

Here is a [jsfiddle](http://jsfiddle.net/eur0yvt1/1/)

**Comment by AMBudnik** [comment]
Hi @joelmora 
Thanks for sharing, but as I was informed by one of our devs we are using only "AND" and we are not opened to add "OR" before we will change filters plugin to be more flexible.

**Comment by budnix** [comment]
Another way to achieve OR is using filter by value formula:
```js
hot.getPlugin('filters').addFormula(1, 'by_value', [['et', 'elit']]);
hot.getPlugin('filters').filter();
```

**Comment by joelmora** [comment]
Thanks @budnix it works that way, I tried to do the same thing but instead of `[['et', 'elit']]` I was using `['et', 'elit']` that is why wasn't working

Thank for the help!
