### ISSUE TITLE
Only can copy 1000 rows?

### ISSUE THREAD

**Issue by WindzCUHK** [handsontable/handsontable#3524]
https://docs.handsontable.com/pro/1.3.4/demo-scrolling.html
I modify the fiddle in demo to use 2000*2000.
http://jsfiddle.net/xkmf4bhf/

When I select a column and press `Ctrl+C`,
only content of the first 1000 columns can be pasted out.
I expect to have the column values of all the rows.

I use chrome on Windows 7. Can any one help?

**Comment by seeley60** [comment]
See the docs :

https://docs.handsontable.com/0.24.3/Options.html#copyRowsLimit

**Comment by AMBudnik** [comment]
Thanks for your feedback @seeley60

**Comment by WindzCUHK** [comment]
oh, I over-looked.
However, is there ways that I can set it to **unlimited**?

**Comment by AMBudnik** [comment]
Hi @WindzCUHK 
`copyRowsLimit` takes a number as an argument but I think we can create some kind of workaround.

If we are talking about an ability to copy unlimited number of rows in your grid we are talking about the whole table, right? 

If so you can pass a number of rows in your grid, like this

```js
 hot1.updateSettings({
 	copyRowsLimit: hot1.countRows()
 })
```
and just manipulate the `afterCreateRow `hook to pump up the `copyRowsLimit` as it can pass the amount of new created rows.

**Comment by cuongurus** [comment]
I can't find option copyRowsLimit in docs version 0.38.1, and it doesn't work in version 0.38.1 too. Please show me how. Thanks!

**Comment by AMBudnik** [comment]
Hi @cuongurus 

we have changed the plugin some time ago and the following option does not work anymore. But you should be able to use[ `beforeCopy` hook ](https://docs.handsontable.com/pro/1.18.1/Hooks.html#event:beforeCopy)to perform the same actions. Can you share your use case? We can check if that will work as well or you need something else.

**Comment by cuongurus** [comment]
Hi @AMBudnik 

Like the title of this issue, I want to copy more than 1000 rows. I just checked beforeCopy hook but data from beforeCopy function only has first 1000 rows of copy range.

**Comment by pnowak** [comment]
Hi @cuongurus 

To increase the limit, please enter the plugin settings: 
```copyPaste: {
      columnsLimit: 2000,
      rowsLimit: 2000
    }```

http://jsfiddle.net/Lpz4o5hj/

**Comment by AMBudnik** [comment]
Thanks @pnowak 

I am reopening the issue as we have agreed that this subject has to be added to the docs.

**Comment by swistach** [comment]
Hi @WindzCUHK, @cuongurus,
we've added information about `rowsLimit` and `columnsLimit`: https://docs.handsontable.com/pro/5.0.1/CopyPaste.html
