### ISSUE TITLE
Boost the performance IE11 (solution)

### ISSUE THREAD

**Issue by garypma** [handsontable/handsontable#3525]
I'm seeing a lot of lag in the latest version of handsontable with IE 11. I launch the same application in fire fox and it seems ok. I have about 35+ columns and 1800 rows. I have also noticed that if I link from the table using an imbedded anchor tag to an angular view, the handsontable hangs and causes the javascript to crash in IE 11. In fire fox the transition is a little slow, but workable. Any idea what is going on?
Could really use a fix on this one, the company I work for only allows IE and fire fox, but they prefer IE.

**Comment by AMBudnik** [comment]
Hi @garypma 
you wrote that "I'm seeing a lot of lag in the latest version of handsontable". Was it OK with the 0.24.2 version?

**Comment by garypma** [comment]
No, that's why I downloaded the latest version. In fact if I try to link directly from the grid using just a simple angular link like "#/details/1" the table tries to clean up something while angular is making the transition and unless I'm in fire fox, the browser hands stating a "long running script". The more results in the table, the longer the wait after the link. If I just right click on the link and open it up in a new tab, no problems. If I link to the detail page from a different angular page that has a very simple non handsontalbe table it works fine as well. Something in handsontable is trying to clean up resources during the angular view change and it is causing all sorts of issues. But, either way, the load and rendering time in IE is significantly slower than fire fox.

**Comment by AMBudnik** [comment]
It doesn't sound great. I can see why you reported it.
Could you create a demo? I have to have something as a test base.

**Comment by AMBudnik** [comment]
That's a clever workaround @garypma 
I'll share it with our devs. Hopefully it will bring some light to the performance issue.

**Comment by garypma** [comment]
I will try to get a Demo together, but it may take awhile as the application I have created is very complex with multiple angular controllers, views and is completely in Angular.

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topics and uploading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Issue will be reopened with the first update.
All comments, investigation results or suggestions are welcome.

**Comment by AMBudnik** [comment]
The following downgrade should no longer occur in Handsontable v8.4.0.
If anything on this subject still should be done or discussed, please leave a comment.
