### ISSUE TITLE
issue with formula "if function"

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#3526]
hello,
when i  test a if condition on a string, the if function doesn't give the correct result, 
it seems to occur when the string contains lower case character

https://jsfiddle.net/jeanmarc/s01wm1mv/2/

regards
jean marc

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 
we are currently refactoring formulas. It can take a while but thanks for sharing. 
We will test it with new plugin version

**Comment by jackparmer** [comment]
> we are currently refactoring formulas

@AMBudnik Is there somewhere we can find a roadmaps for this?

**Comment by AMBudnik** [comment]
sure @jackparmer 
here it is https://trello.com/c/z0QvwlNj/11-full-formula-support-as-a-plugin

**Comment by AMBudnik** [comment]
After switching to Formulas PRO plugin this example works as expected http://jsfiddle.net/handsoncode/gfy8ec74/
