### ISSUE TITLE
check-boxes can be edited even if the cell is marked as readOnly

### ISSUE THREAD

**Issue by warrior107** [handsontable/handsontable#3527]
In the version 1.3.4, a cell of type check-box can be checked or unchecked even if the cell is marked as "Read Only".
In the version 1.3.2, it is working fine.

Example: 
version 1.3.2 : http://jsfiddle.net/w4whfm7d/3/
version 1.3.4 : http://jsfiddle.net/e46pxpxr/2/

The "available" column has readOnly false but the "Comes in Black" column has readOnly true.
In the 1.3.2, the "Comes in Black" cannot be changed, but in 1.3.4, the "Comes in Black" column can be changed.

**Comment by AMBudnik** [comment]
Hi @warrior107 
It has changed in 1.3.3 whith the base of Handsontable 0.24.2
Maybe it has something to do with this issue: https://github.com/handsontable/handsontable/issues/3211

thanks for sharing @warrior107

**Comment by budnix** [comment]
I've checked the issue with the newest version of Handsontable and it seams to work now. I've prepared demo at http://jsfiddle.net/e46pxpxr/3/.
