### ISSUE TITLE
i want contextmenu options should be different for different column based on column type

### ISSUE THREAD

**Issue by basrita** [handsontable/handsontable#3528]
Hi,

I want different contextmenu options for different column.
for example : column type numeric should have only have freeze-column option and not numeric should have all options.
please suggest any thing.

Thanx in advance.

**Comment by AMBudnik** [comment]
Hi @basrita 
Currently we do not offer a straight option how to do that.

**Comment by basrita** [comment]
Hi @AMBudnik ,

is there any other option for this as for column type of numeric alignement is not working.
that's why i need it badly.

thanks.

**Comment by AMBudnik** [comment]
You can overwrite the `htNumeric` class when all that you need in this case is to align left the numeric values

```css
.handsontable .htNumeric {
  text-align: left !important
}
```

**Comment by basrita** [comment]
is there a way to remove alignment option for specfic column

**Comment by AMBudnik** [comment]
you can add a class to certain columns that will overwrite the CSS settings like in the example above but using your custom class.

**Comment by basrita** [comment]
@AMBudnik 

no actually we will specify

contextMenu[alignment,and all other options what we want ] like this .
so drop down will come when we right click on column in that i want to cutomize options for particular column.

**Comment by AMBudnik** [comment]
Currently we do not offer a contextMenu settings for different columns. If you have something else on your mind please create a demo or a draft.

**Comment by basrita** [comment]
ok thanks.
