### ISSUE TITLE
Flag icon mistake

### ISSUE THREAD

**Issue by YozhEzhi** [handsontable/handsontable#3530]
Why Russia has Norway's flag?
![Screen](http://dl2.joxi.net/drive/2016/05/23/0001/1889/128865/65/b5232f5a6f.jpg)

**Comment by AMBudnik** [comment]
Our bad! That's a bug (wrong .svg file). Thanks for noticing @YozhEzhi 
It should be a ru.svg file

**Comment by krzysztofspilka** [comment]
To be released in the week 30.05-03.06.
