### ISSUE TITLE
Cell Validation on initial data load

### ISSUE THREAD

**Issue by deenairn** [handsontable/handsontable#3531]
I have a scenario where I am loading some data into a HoT and I cannot be certain that the initially loaded data (which could be loaded from an API endpoint) - is valid. Therefore I would like to force the validator to be loaded each time the data is loaded - including the initial data load. Could you provide guidance on the best way to do this via the "validateCells" callback - as I cannot quite get the behaviour right.

**Comment by AMBudnik** [comment]
Hi @deenairn 
Certainly the `validateCells` method should be one to pick in this case.
You would have to trigger it `youInstance.validateCells()` when you load the data.

Could you share an example in a Fiddle?

**Comment by AMBudnik** [comment]
issue closed in lack of needed demo but feel free to add one if you're still seeking for an answer/tip

**Comment by vk-sourcefuse** [comment]
Hey, it does not work for select dropdown items ..

**Comment by AMBudnik** [comment]
Hi @vk-sourcefuse 

please share a demo and a step-by-step replication scenario
