### ISSUE TITLE
Multi-level submenus don't work

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3533]
demo: https://jsfiddle.net/yk387anr/
We are not getting logs after the second submenu is clicked.

`[G #1293]`

**Comment by AMBudnik** [comment]
Check: https://forum.handsontable.com/t/contextmenu-not-close-when-i-click/645/3 as well

**Comment by AMBudnik** [comment]
Still replicable in 1.15.0/0.35.0

**Comment by Rex90** [comment]
any chance this gets fixed?

**Comment by AMBudnik** [comment]
Hi @Rex90 
I think that we should fix this issue first https://github.com/handsontable/handsontable/issues/3807
Maybe it would even fix this one as well

**Comment by marcospaulobarretoSTA** [comment]
I had the same issue in 1.16.0
I used a older community version where this worked and migrated to the Pro version.
I had to use only 2 levels and my context menu is way bigger.
Solving this whould really help

**Comment by AMBudnik** [comment]
Hi @marcospaulobarretoSTA 

thank you for your feedback

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by iaminvictus1993** [comment]
@AMBudnik  The issue is replicable in v 6.2.0

**Comment by AMBudnik** [comment]
Thank you for checking @iaminvictus1993

**Comment by AMBudnik** [comment]
Thanks for sending it over @aaronbeall

**Comment by AMBudnik** [comment]
It looks like we get the logs now

![image](https://user-images.githubusercontent.com/10757813/66563717-ae958b00-eb5e-11e9-99f0-e6d4d34d02bc.png)

Tested on Chrome 77 / Windows 10 using the `7.1.1.` https://jsfiddle.net/yk387anr/
