### ISSUE TITLE
how to remove sequence number

### ISSUE THREAD

**Issue by gaurav93** [handsontable/handsontable#3534]
Hi,
how we can remove sequence number from starting in handson table

**Comment by krzysztofspilka** [comment]
Hi @gaurav93 what do you mean by that? Could you provide a more detailed description?

**Comment by gaurav93** [comment]
Actually i want to remove sequence number which comes starting in grid e.g.
1,2,3,4 for each row..

**Comment by krzysztofspilka** [comment]
To do that just remove from the configuration:

  colHeaders: true,
  rowHeaders: true,

or set them to `false`.

**Comment by gaurav93** [comment]
That's great ,its works for me.
Thanks man...

**Comment by gaurav93** [comment]
One more thing i need to ask how to set focus on cell in afterValidate
function

**Comment by AMBudnik** [comment]
Hi @gaurav93 
You can use a `selectCell(row, col)` method.
Docs: https://docs.handsontable.com/pro/1.4.0/Core.html#selectCell
