### ISSUE TITLE
Row getting deleted before confirmation message

### ISSUE THREAD

**Issue by ravi590** [handsontable/handsontable#3535]
Hi @AMBudnik, I want to provide a confirmation pop-up before deleting the row in handsontable.
Before selecting yes or no the row is getting deleted from handsontable UI,
Can you help me on this?

**Comment by AMBudnik** [comment]
Hi @ravi590 
You can use a `beforeRemoveRow `callback to achieve your goal. 

Here's a simple example with the `prompt `http://jsfiddle.net/xheodvj3/ it will remove a row only when user types `yes`

**Comment by ravi590** [comment]
Hi @AMBudnik ,I have gone through the fiddle,  I am using angular material dialog in "beforeRemoveRow" method, for confirmation on selection of delete option, the dialog will be loaded with in no time, meanwhile the row is getting deleted in UI.

**Comment by AMBudnik** [comment]
Hm.. could you create a demo where we can replicate the bahavior?

**Comment by AMBudnik** [comment]
issue closed in lack of needed demo.

**Comment by maryjuano** [comment]
Same problem here. I'm using bootstrap modal to show a confirmation dialog but it already deletes the rows before I could click the delete button inside the modal.

**Comment by maryjuano** [comment]
the suggested solution from  @AMBudnik  only works with javascript's Confrim(); anyone has an idea to solve this?

**Comment by AMBudnik** [comment]
Hi @maryjuano 
If you can create a demo where it's not working I'd be happy to take a look.

**Comment by maryjuano** [comment]
Thanks for the reply @AMBudnik  here's the [http://jsfiddle.net/maryjuano/2w3aLddp/7/](url) fiddle. tell me if it's working

**Comment by AMBudnik** [comment]
I get 404 @maryjuano

**Comment by maryjuano** [comment]
hi @AMBudnik  sorry for late reply. I was off to work, Kindly copy paste the url to your browser's address bar, thnks.

**Comment by maryjuano** [comment]
I found a  workaround, I woudn't say this is the best sol. I hope this helps [](http://jsfiddle.net/tx28vpx9/), paste it to the address bar or you'll get 404.

**Comment by AMBudnik** [comment]
thank you @maryjuano I'll reopen this issue
