### ISSUE TITLE
Need to call one custom method in filter ok button in handsontable pro.

### ISSUE THREAD

**Issue by basrita** [handsontable/handsontable#3536]
Hi,

I am having a requirement that i need to call a service when clicking on ok button in filter dropdown menu. how to get the entered value and selected column and call my method.

Thanks in advance.

**Comment by AMBudnik** [comment]
Hi @basrita 
Please check if the `beforeFilter` callback is the one you're seeking.
Here's an example: http://jsfiddle.net/hgLxuLpd/

**Comment by basrita** [comment]
Thanks Budnik,

Is there any link to see all these call backs.

On Wed, May 25, 2016 at 4:44 PM, Aleksandra Budnik <notifications@github.com

**Comment by AMBudnik** [comment]
Yup, you can check all of them 'in action' at: https://docs.handsontable.com/pro/1.4.0/tutorial-using-callbacks.html
