### ISSUE TITLE
Checkbox/beforeChange: define a change source

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3539]
Checkbox checking/unchecking returns 
1. `edit` source in `afterChange` callback and 
2. `undefined` in `beforeChange` callback

Demo: http://jsfiddle.net/zajxagm3/
I guess that we have to add a source for `beforeChange` when a user uses checkbox.

**Comment by AMBudnik** [comment]
the same case relates to an action when you delete a content from a cell. http://jsfiddle.net/njr3tcx0/

![change](https://cloud.githubusercontent.com/assets/10757813/16838222/6c32b55c-49c8-11e6-823a-38811c828dbf.png)

**Comment by AMBudnik** [comment]
Still `underfined` in v0.30.1, demo: http://jsfiddle.net/handsoncode/cLn0pzhg/

**Comment by gmanoj26** [comment]
we have facing similar issue while migrating handson library version from 0.10.5 to 0.35.1 
making below change in handsontable.full.js (line no: 15150) solved the issue.code change is similar to the existing code of after change event
![image](https://user-images.githubusercontent.com/8793282/36251632-d821070a-1267-11e8-892a-e3495fdcc8b5.png)

 note: before change is returning correct source value for below events
"CopyPaste.paste"
"UndoRedo.undo"
"UndoRedo.redo"

i hope this solves the bug....

**Comment by AMBudnik** [comment]
Thank you for sharingthe tips @gmanoj26

**Comment by AMBudnik** [comment]
Hi @gmanoj26 

We have done some fixes. Please update the code to 0.38.0 and check if it works for you.
