### ISSUE TITLE
remove_row context option is disabled when there is only one row

### ISSUE THREAD

**Issue by jrmurad** [handsontable/handsontable#3541]
http://jsfiddle.net/39e4LLxm/

To reproduce: Select all but the last row, right click, and choose "Remove row".

Now right-click the remaining row. "Remove row" is disabled.

**Comment by jrmurad** [comment]
Seems to work if I define my own remove_row function:

    contextMenu: {
      items: {
        remove_row: {
          disabled: function () { return false }
        }
      }
    }

**Comment by AMBudnik** [comment]
Hi @jrmurad 
I took the same example but left only 3 rows (http://jsfiddle.net/y8c1eskj/) -  there was no issues to remove all rows.

**Comment by jrmurad** [comment]
I took your fiddle:

1. right-click Euro -> Remove row
2. right-click Sheqel -> Remove row
3. right-click Peso -> *** Remove row is disabled ***

**Comment by AMBudnik** [comment]
Hm.. I'm doing exactly the same (Chrome 50, Win8)

**Comment by budnix** [comment]
Additionally there is a second bug. After removing second row context menu doesn't want to disappear.

**Comment by jrmurad** [comment]
Yes, @budnix . This gif shows both issues. I am using Mac, Chrome 50.0.2661.102 (64-bit).

![hot](https://cloud.githubusercontent.com/assets/172669/15544989/c56f69ee-2268-11e6-8c1f-b0a2dd518a87.gif)

**Comment by krzysztofspilka** [comment]
@jrmurad confirmed, thanks.

**Comment by swistach** [comment]
First bug exist since 0.15.0-beta1 - perhaps that was the plan
Second bug exist since 0.23.0
