### ISSUE TITLE
Problem with range selection after click right mouse button on header

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3543]
When I select multiple columns and then invoke the context menu by clicking on a header, the selection is being reduced to only one column.

##### Steps to reproduce
1. Go to: https://docs.handsontable.com/pro/1.4.0/demo-hiding-rows.html
2. Select B:D by headers
3. Click right mouse button on header "D"

Handsontable: 0.25.0
Any browser

**Comment by VeraZab** [comment]
I think I'm still seeing this issue: http://jsfiddle.net/cjkz8jne/1/
could you take another look please?

**Comment by AMBudnik** [comment]
Hi @VeraZab 

Can you guide me on how to replicate the issue? I used your demo and it seems to work fine

![gif](https://user-images.githubusercontent.com/10757813/32658395-18f9059c-c61a-11e7-95b5-432d1bd21c64.gif)

**Comment by VeraZab** [comment]
oh maybe it's browser related, this exact action's not working for me:
I'm on chrome Version 61.0.3163.100

![ex](https://user-images.githubusercontent.com/4257572/32658538-1349b52a-c623-11e7-9129-49b4757b326e.gif)

**Comment by AMBudnik** [comment]
I'm on Windows 10 and Chrome 62. If you update the browser it works?

**Comment by VeraZab** [comment]
Just updated and retried on Chrome 62, on mac. It's still not working for me...

**Comment by VeraZab** [comment]
Oh, on mac, firefox 56.0.2 it works with right click, but not on dropdown click

**Comment by AMBudnik** [comment]
Why system you're using and do you use a mouse, magic-mouse or a touch pad?

**Comment by VeraZab** [comment]
I'm on mac os sierra 10.12.6, and I'm using my mac's touch pad

**Comment by AMBudnik** [comment]
Hi @VeraZab 

Can you share a demo where I'll be able to track 'clicks'?

Also please let me know if you're using any additional software that may be related like the one used to make the mouse more smooth.

**Comment by VeraZab** [comment]
I'm not using any particular software, I'm using the trackpad of my macbook air.
Here's the best recording I could do. 

![ex](https://user-images.githubusercontent.com/4257572/32666576-89a11138-c640-11e7-8fd9-5411bd11cc99.gif)

To do a right click on mac I'm pressing the control key, and clicking on the trackpad, that's what makes the contextMenu appear.

**Comment by VeraZab** [comment]
alright, looks like it works on a mac with a mouse, didn't have one to test previously.

and it looks like on a mac trackpad, holding the shift key while doing control+click or clicking the dropdown, also works.

thanks for looking!

**Comment by AMBudnik** [comment]
We have left a lot of comments to solve this one out @VeraZab 
Thank you for your investigation.
Summarizing the multi-column selection does not work only on Mac, using the trackpad?

**Comment by VeraZab** [comment]
yes, correct

**Comment by VeraZab** [comment]
well, don't know what to say..
I've asked 2 colleagues with Macs to replicate as well, and they were both having trouble to keep column selection..

Usually on mac to do a right click, you press control + click, that's what we were doing..

We later realized that pressing shift + control + click works on mac with a trackpad. And mac + a mouse right click works too. 

Anyway, l'll just be using shift + control + click

Thanks for looking!

**Comment by vcerberusv** [comment]
Hi @AMBudnik, I believe I have discovered an issue related to this where when the first column of the handsontable is hidden, range selecting the rows by the header and then right clicking on the header to bring up the context menu will only select the row that is being clicked on.

This is used in an angular project.

JsFiddle fore reference: https://jsfiddle.net/xe6n7mp8/9/

**Comment by AMBudnik** [comment]
Hey @vcerberusv this issue sounds like this one https://github.com/handsontable/handsontable/issues/5999
