### ISSUE TITLE
Row height vs. merged cell's view (autoRowSize: true behavior)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3545]
I was just provided with an example: http://jsfiddle.net/p71rr0pt/
There are 9 columns. Eight of them are very narrow and merged.

This is how the example looks when we are using `autoRowSize: true`
![1](https://cloud.githubusercontent.com/assets/10757813/15612748/5c3968e8-2430-11e6-9e21-3e6c48ee2dda.png)

and this is how it looks when we change it to `autoRowSize: false`
![2](https://cloud.githubusercontent.com/assets/10757813/15612879/e2083da0-2430-11e6-82a6-667290fe478b.png)

This is how the table looks before it gets `mergeCells` settings (for both: `autoRowSize: true` and `autoRowSize: false`)
![3](https://cloud.githubusercontent.com/assets/10757813/15612943/310a14a0-2431-11e6-9255-abfb960a712d.png)

I leave this subject to be discussed with the team. Please share your option. 
If you ask me I would prefer to get one-line data if I set `autoRowSize: true` in my instance.

`[G #1293]`

**Comment by nikolasethore** [comment]
Hi, Any news on this issue? I'm facing it with the latest Handsontable version.

**Comment by pnowak** [comment]
To be honest this subject is labelled as `To be discussed` so it's still not clear in which direction we should go.

Can you tell me what would be an expected result in this situation?
Maybe do you attach a demo where we can reproduce the issue?

**Comment by nikolasethore** [comment]
In my opinion, the correct behavior would be to calculate the row size after merging cells.

So it would look like that : 
![](https://cloud.githubusercontent.com/assets/10757813/15612879/e2083da0-2430-11e6-82a6-667290fe478b.png)

Even with autoRowSize: true

Do you know if there is any kind of workaround? This is really a problem for us.
Is there any way to force the height of a row calculated with autoRowSize with a value we provide?

Thanks for your quick feedback ;)

**Comment by pnowak** [comment]
Thank you for your input.

As I said above this issue needs a discuss. So this is not my decision.

You could determine a row height by the `rowHeights` option. 
If you this option why you still needed `autoRowSize`?

If I may ask, what are the requirements for your project?

**Comment by nikolasethore** [comment]
My strategy was to calculate by hand only the cells that return bad height values, but we do need autoRowSize.

Requirements are that we create a "Group" of grids inside one instance of Handsontable.
And we need to display titles in the grid, so what I'm doing is adding a cell without borders and merged horizontally to the number of columns of this "sub-grid". But unfortunately, as the first cell is smaller and the text of title quite long, it is setting a big height to this row.

![Uploading Capture d’écran 2020-07-23 à 15.15.59.png…]()

Here is a screenshot of the issue.

**Comment by pnowak** [comment]
I see.

So without `autoRowSize: true` your complicated grid better fit? 
I mean, this change will make your issue go away?

**Comment by nikolasethore** [comment]
Sorry, was out of town last week.
Indeed this change makes my issue go away.

**Comment by nikolasethore** [comment]
Hi,
Any news on this issue?

**Comment by AMBudnik** [comment]
Hi @nikolasethore 

I should be able to share some updates around the 1st of September. I will leave myself a notification to get back to you regarding our Roadmap.

**Comment by nikolasethore** [comment]
Hi @AMBudnik 
Is there any news on this subject with the release of v8?

Thanks a lot and congrats on the new version!

**Comment by AMBudnik** [comment]
@nikolasethore the Roadmap is not finished yet. So rest assured I will notify you on the Roadmap as soon as it appears.

**Comment by AMBudnik** [comment]
Updating this subject.

* the most accurate behavior is when we disable `autoRowSize` http://jsfiddle.net/bk48fezo/ 
![GIF](https://user-images.githubusercontent.com/10757813/95062657-90c11e80-06fd-11eb-8361-708183a05549.gif)
as we previously had a 2-line cell inside a narrow column and we got a 1-line cell cause of the column space extension (merging)
* the `autoRowSize` should not change this behavior. It means that in my opinion, the state of rowHeights should not change between enabling and disabling the `autoRowSize` plugin.

**Comment by nikolasethore** [comment]
@AMBudnik Yeah would be perfect like that! Is it already in your roadmap?

**Comment by AMBudnik** [comment]
Not yet, but I would really want to move this subject forward, that is why I made an update and provided the demo for the latest version where this issue still exists.

**Comment by nikolasethore** [comment]
Hi @AMBudnik , any news on this subject?

**Comment by warpech** [comment]
The problem is connected to with https://github.com/handsontable/handsontable/issues/7274 and related issues, such as https://github.com/handsontable/handsontable/issues/7164. Our immediate roadmap includes working on performance improvements, which pave the way to fixing this but I can't promise any dates.

👷‍♀️ Workaround: The problem in topic can be avoided if your merged cells are single line. See this fiddle for a workaround that uses 3 lines of CSS to eliminate the impact of MergeCells on AutoRowSize: https://jsfiddle.net/warpech/56zcvfnx/1/

```css
.handsontable td[colspan] {
  white-space: nowrap;
}
```

**Comment by nikolasethore** [comment]
Hi @warpech 

Your workaroud was working fine with v7 but just updated to 8.2.0 and now facing a problem with fixedColumnsLeft.
Here is a reproduction, based on your jsfiddle: https://jsfiddle.net/h9gnmu64/

Is there a workaround of the workaround 😅 ?

Thanks in advance !

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **MergeCells grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by nikolasethore** [comment]
> The problem is connected to with #7274 and related issues, such as #7164. Our immediate roadmap includes working on performance improvements, which pave the way to fixing this but I can't promise any dates.
> 
> 👷‍♀️ Workaround: The problem in topic can be avoided if you use a custom renderer presented here: https://jsfiddle.net/376xc0vr/ . This workaround works by running the side effects of the MergeCells in the "ghost table" that is used for measurements by AutoRowHeight.
> 
> Edit: an earlier version of this comment showed a different, wrong workaround

Hi everyone,

We just migrated to the latest version of Handsontable (8.4.0) and this workaround is not working anymore (it is correctly applying it to ht_clone_left but not to ht_master cells). It is really a key feature for us. Is there any news about the bug resolution?

Thanks a lot in advance.

**Comment by AMBudnik** [comment]
Hi @nikolasethore 

The last update I saw was

>EDIT : Ok my example is not relevant, let me find a way to reproduce it better...

Have you maybe created an example that shows your use case?

**Comment by nikolasethore** [comment]
Hi,

Unfortunately, I never succeeded to create a simple example reproducing the issue. But I figured out how to solve it I guess.

By simply adding an `instance.refreshDimensions()` within a Timeout of a few milliseconds, I was able to refresh the table and fix my display glitch.

Thanks again.

**Comment by AMBudnik** [comment]
Thank you for the update @nikolasethore

**Comment by hero9** [comment]
@AMBudnik Hey,
Is there any updates on this issue?

FYI @nikolasethore your last workaround doesn't work.

**Comment by AMBudnik** [comment]
Hi @hero9 @nikolasethore 

I am happy to announce that this issue is solved in v14.0.0. Updated demo https://jsfiddle.net/z438njuf/

List of changes to v14.0.0 https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-0-0
