### ISSUE TITLE
Adding 1px border misaligns rowHeaders.

### ISSUE THREAD

**Issue by computurus** [handsontable/handsontable#3546]
Cells not aligned with line numbers. 

See attached picture:
http://shrani.si/f/3s/WS/1OAyLq5A/1/problem.png

**Comment by AMBudnik** [comment]
Hi @computurus 
Can you provide more details? It looks as expected at the first glance.

**Comment by computurus** [comment]
If you look at the picture you can see that the cell which is selected(highlighted) is not aligned with the cell containing the row number.

**Comment by AMBudnik** [comment]
Can you also share a demo where we'll be able to replicate the issue?

**Comment by computurus** [comment]
Can you give me your eMail. Do not want to share my demo public.

**Comment by AMBudnik** [comment]
Sure @computurus you can send it to support@handsontable.com. I'm the main Support Manager so I will assign it to myself.

**Comment by computurus** [comment]
Also happens with the use of css classes.

http://jsfiddle.net/084q1out/1/

**Comment by AMBudnik** [comment]
I'm marking this issue as a bug.
When we add 1px border to cells the rows become misaligned with rowHeaders.
It works as expected when we load 2px border.

**Comment by AMBudnik** [comment]
### Workaround 1:
You can use the `box-shadow` as below:
`box-shadow: inset 0 0 1px 1px blue !important;`
to mark appearance of
`border: 1px solid blue !important;` 
**demo**: http://jsfiddle.net/ezoyu8ue/

### Workaround 2:
set `rowHeights` to a value bigger than 22 + 1 (default 22px + 1px of border)
**demo**: http://jsfiddle.net/n5a00dfn/
(this one can be related to genesis of this bug)

**Comment by swistach** [comment]
Hi @computurus,
Best solution is: http://jsfiddle.net/ezoyu8ue/1/

Present, construction of the Handsontable is based on the `table` (HTMLElement). Unfortunately this solution have many restrictions.
