### ISSUE TITLE
Double selection appears if I click the scrollbar

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3547]
If you edit a value within a selected range and then use scrollbars (with a mouse pointer) and then use <bkd>Backspace</kbd> to delete the data, the double selector appears.

**Steps to reproduce the problem:**
1. Go to https://docs.handsontable.com/0.25.0/demo-scrolling.html
2. Select B2:C3
3. Use <kbd>F2</kbd> to edit the first cell
4. Click somewhere in the scrollbar
5. Use <kbd>Backspace</kbd> to remove the data
6. Click anywhere within the grid to see the second selection

Screencast: https://gyazo.com/18fab1b4ff20ed79723db83c164747f0

:information_source:

> Handsontable 0.25.0
> Windows 8.1
> Chrome

**Comment by AMBudnik** [comment]
Seems to be fixed in v0.35.0. Updated demo http://jsfiddle.net/z7yaqndm/

![video](https://user-images.githubusercontent.com/10757813/35143941-54061bd2-fd03-11e7-9641-3dd907dbce08.gif)
