### ISSUE TITLE
Jumping selection in the first row

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3548]
If you scroll the grid just to hide a first row and then navigate to the top using arrow keys, the selection will "jump" for a few pixels before you reach that top. Before the last move the cell's top border is doubled.

![scrolling-problem](https://cloud.githubusercontent.com/assets/8048526/15654802/78b652c4-2697-11e6-80fe-116173711990.gif)

:information_source:

> Handsontable 0.25.0
> Windows 8.1
> Chrome

**Comment by AMBudnik** [comment]
I am not able to replicate this issue using v0.35.0. I have tried it on https://docs.handsontable.com/0.35.0/demo-scrolling.html.
Can you check this one, please?

**Comment by AMBudnik** [comment]
The issue is no longer replicable in version 0.38.1
