### ISSUE TITLE
need to show alert message after cell validation fails and also set focus on same

### ISSUE THREAD

**Issue by gaurav93** [handsontable/handsontable#3549]
Hi,
i created custom validator function for numeric cell for validation bcz i need to show alert after validation fails,but by this i am not able to set focus on the cell .

my code is
 {data: 'Salary', type: 'numeric', format: currencyFormat, language: currentLanguage ,validator: numericValidator}
-------------

var numericValidator = function (value, callback) {
  
    if (value.length == 0 || !isNaN(parseFloat(value)) && isFinite(value)) {
        callback(true);

    } else {
        alert("The value you have entered isn't valid for this field")
        callback(false);
    }
};

this wil show alert message but focus is disappeared from cell.

**Comment by AMBudnik** [comment]
Hi @gaurav93 
I would be much easier if you could create a demo based on this code. Can you take a minute to create one?

**Comment by AMBudnik** [comment]
issue closed in lack of needed demo.
