### ISSUE TITLE
propToCol / unmodifyCol bug

### ISSUE THREAD

**Issue by zoladkow** [handsontable/handsontable#3551]
If I want to fetch column number for a given property I would use `grid.propToCol(prop)`. With `manualColumnMove`, internally propToCol will run the `unmodifyCol` hook. Now, this one works funny with the last column. I end up always getting the -1 return value.

I belive the faulty code is this:

![image](https://cloud.githubusercontent.com/assets/11553616/15677932/a5147214-274c-11e6-90e0-2a04f55ea3d0.png)

The positionArr entry for last column is never created.

Found on 0.24.3, retested also on 0.25.0 with same result.

**Comment by AMBudnik** [comment]
Thanks for sharing @zoladkow

**Comment by krzysztofspilka** [comment]
@zoladkow it will be released within the next version
