### ISSUE TITLE
can't input small floating numbers between 0 to 1

### ISSUE THREAD

**Issue by PedroTRX** [handsontable/handsontable#3552]
Trying to enter a small value as '0.0000001' for numeric inputs results a cell validation error.
when trying to edit the cell the value shown in edit mode is '1-e7' which may be the cause for the validation error.

**Comment by AMBudnik** [comment]
Hi @PedroTRX 
This issue is already reported at https://github.com/handsontable/handsontable/issues/2030
If you would have any suggestions, additional info or investigation results please report them at https://github.com/handsontable/handsontable/issues/2030
