### ISSUE TITLE
Uncaught TypeError when try toggle checkbox after scroll

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3554]
##### Steps to reproduce:
1. Go to: http://jsfiddle.net/fr1hyLw2/
2. Select `A50`
3. Scroll to `A1`
4. Press `SPACE`

Result:
`Uncaught TypeError: Cannot read property 'querySelectorAll' of null` in dev console.

**Comment by AMBudnik** [comment]
**hint**: it works when we add `renderAllRows: true`

**Comment by gentr1** [comment]
I am having that problem at the moment too. It would be nice to allow that feature to work without renderAllRows: true . If you have many many rows, the user will just click on the first row, then shift+ the last row to select all, and then press space to mass select all check boxes or many of them...
Now, I hope this suggestion might perhaps help a bit.
The bottom of the handsontable.js , at line 19276 the function that regulate selection/deselection seems to be the problem.

`instance.setDataAtCell(row, col, event.target.checked ? (cellProperties.checkedTemplate || true) : (cellProperties.uncheckedTemplate || false));`
It would make sense to change it slightly.
perhaps replace  instance.setDataAtCell by something like 
`var status=instance.getDataAtCell (row, col);
if (status==true){
instance.setDataAtCell (row, col,(cellProperties.uncheckedTemplate || false));
}
else{
instance.setDataAtCell (row, col,(cellProperties.checkedTemplate || true));
}`

**Comment by AMBudnik** [comment]
Thanks for sharing your suggestion @gentr1 We'll check it.

**Comment by gentr1** [comment]
Apologies for wasting your time. My suggestion did not really fix the problem.
At line 19243 in handsontable.full.js , I added an if statement, checking if the value of cell is present, and if not, get the data at cell and then swap checkbox values. Unfortunately, even if the queryselector null value message disappeared, only a portion of the selection was toggled.
'var cell = instance.getCell(row, col);
if (cell){
  var cellProperties$__6 = instance.getCellMeta(row, col);
        var checkboxes = cell.querySelectorAll('input[type=checkbox]');
        if (checkboxes.length > 0 && !cellProperties$__6.readOnly) {
          callback(checkboxes);
        }
}
else{
   var status=instance.getDataAtCell (row, col);
	if (status == true){
		instance.setDataAtCell (row, col,false);
	}
	else{
		instance.setDataAtCell (row, col,true);
	}
}'

**Comment by AMBudnik** [comment]
Oh, that's OK - thank you for an effort to investigate the case.

**Comment by AMBudnik** [comment]
@swistach 
I guess that it works as expected now. I've tested it with v0.30.1, demo: http://jsfiddle.net/5L8xvvzf/

**Comment by gentr1** [comment]
Hi,

Sorry. It still does not work!
On your demo, if I select all the table row with the mouse like I would
select a long bit of column in excel by scrolling down and keeping the left
mouse button down , and then once the whole column is highlighted, I press
space, then, only a portion of the checkboxes change. Not the whole
selection.
Cheers.
Mehdi

**Comment by AMBudnik** [comment]
Thanks for noticing @gentr1 I can see that when you add `renderAllRows: true` it works as expected.
@swistach should it be working without `renderAllRows` when in visible there are only 12 rows.
