### ISSUE TITLE
clicking on html select inside colHeader does not work in Firefox/IE

### ISSUE THREAD

**Issue by mrobideau** [handsontable/handsontable#3555]
see: http://jsfiddle.net/snx6oqm4/2/

What this demonstrates is that if you add a select to the colHeader so that the user can define the name of the header, clicking on one of the select options does nothing in Firefox/IE.  

Works correctly in Chrome.  Using a key press to select an option works in all browsers.

**Comment by AMBudnik** [comment]
Hi @mrobideau 

it should work as expected. Can you check it please? I will appreciate any feedback.

**Comment by AMBudnik** [comment]
@mrobideau 
I think that we can close this issue now. 
Feel free to share details if you still experience any difficulties in this subject.
