### ISSUE TITLE
Pressing space button scrolls viewport, when active cell is 'readOnly'

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3556]
##### Steps to reproduce:
1. Go to: http://jsfiddle.net/oL4gLnLr/
2. Select `A1`
3. Press `SPACE`

**Comment by AMBudnik** [comment]
Still present in v0.31.0

![example2](https://cloud.githubusercontent.com/assets/10757813/23358046/a3ffb9b4-fce0-11e6-8438-b66b57a0ca50.gif)

**Comment by AMBudnik** [comment]
The issue is gone in v0.35.0 
Updated demo http://jsfiddle.net/8p6cxd7j/
