### ISSUE TITLE
Bugs in Opera

### ISSUE THREAD

**Issue by m-burst** [handsontable/handsontable#356]
I am using Opera 12.12 under Windows 7.

The bugs are:

1. Text in the table is selectable:
![bug_1](https://f.cloud.github.com/assets/3243475/60301/48aadf22-5c07-11e2-893a-f73633ec2044.PNG)

2. Pasting works incorrectly. The cells that were selected at the moment of pasting are cleared.
This is what I copy:
![bug_2_1](https://f.cloud.github.com/assets/3243475/60332/72e03c46-5c08-11e2-82bd-f3ce51413684.PNG)
This is what I get if I select one cell and press Ctrl+V:
![bug_2_2](https://f.cloud.github.com/assets/3243475/60337/87bd87ae-5c08-11e2-92a8-7f8977567d10.PNG)
This is what I get if I select two cells in column F and press Ctrl+V:
![bug_2_3](https://f.cloud.github.com/assets/3243475/60347/ede3b224-5c08-11e2-8354-be53364c67be.PNG)
It seems like the table does something else after normal pasting, because after I try to undo paste (press Ctrl+Z after paste), this is what I get:
![bug_2_4](https://f.cloud.github.com/assets/3243475/60363/96e76b72-5c09-11e2-92a3-6ba0cb50fac2.PNG)

I've been doing all of this on the main page of http://handsontable.com

**Comment by AMBudnik** [comment]
Tried to reproduce this issues with Opera 28.0 on mac and every of this listed issues works as expected. Please update your HOT to 0.13.1 and reply if you'll get the same results.
