### ISSUE TITLE
Can't set read only on multiple check box columns.

### ISSUE THREAD

**Issue by garypma** [handsontable/handsontable#3562]
If you setup a angular ngHandsontable and setup two different check box columns, you can't set one to read only and the other to not. They will both still allow edits. Both have to be set to read-only or it doesn't work. I need a fix for this asap. Just change you basic angular example to have the following code and you will see the error right off:

hot-column data="isActive" title="'Is active'" type="'checkbox'"  checked-template="'Yes'"
                unchecked-template="'No'"></hot-column>
hot-column data="isActive2" title="'Is active'" type="'checkbox'" read-only checked-template="'Yes'"
                unchecked-template="'No'"></hot-column>

I would appreciate some kind of response. I have left several bugs and never seem to get any kind of response, or if I do it's not helpful.

**Comment by AMBudnik** [comment]
Thanks for sharing @garypma 
It's a Vanilla version bug also

Buggy case:
1. If we would like to set `readOnly = true` value for second checkbox column ([index 3](http://jsfiddle.net/86mqzf7n/1/)) both checkbox columns are available to edit. 
2. If we set the `readOnly = true` value for first checkbox column ([index 2](http://jsfiddle.net/ohfwgaL0/)) both checkbox columns becomes readOnly.
