### ISSUE TITLE
bug on data validation

### ISSUE THREAD

**Issue by truongngoctuan** [handsontable/handsontable#3563]
https://docs.handsontable.com/0.25.0/demo-data-validation.html

in the link above, if I type something incorrect, then enter, the validator won't allow me to move to other cells. But if I press esc button, it keep the old data but still has a red hightlight (I expect it to become normal). After I modify other cell, it's back to normal. Is it consider as a handsontable's bug, or just haven't cover all use cases in the tutorial ?

please check this link:
http://imgur.com/lpySobm

**Comment by AMBudnik** [comment]
Thanks for sharing @truongngoctuan 
I think that if it's not the same issue as described here:https://github.com/handsontable/handsontable/issues/3381 (and https://github.com/handsontable/handsontable/issues/3402) it is strongly related.

If you'd have any additional information please share them via #3381 post
