### ISSUE TITLE
How to getSourceData after transformations

### ISSUE THREAD

**Issue by duccoder** [handsontable/handsontable#3564]
After transformations (http://docs.handsontable.com/0.25.0/demo-moving.html), how to **getSourceData** with order?

**getData** will response array with order but I can't use because objects data has many hidden field more than array receive by **getData**

**Comment by AMBudnik** [comment]
Hi @duccoder 

What do you mean by saying 

> has many hidden field more 

Here's a sample demo I've made http://jsfiddle.net/x17ytz3n/ it logs a 5 x 5 array in both cases.

**Comment by duccoder** [comment]
@AMBudnik Hi, I have been modify your sample here, with `getSourceData` it response not order

http://jsfiddle.net/duccoder/rbse44kc/1/

**Comment by AMBudnik** [comment]
Thanks for additional information.
I can see what you mean. It's not the same case.

`getSourceData` returns array of objects and `getData` array of arrays.

**Comment by AMBudnik** [comment]
an example of desired behavior for `getData` for objects: http://jsfiddle.net/epmxzpt9/

**Comment by dbujold** [comment]
Hi AMBudnik, in your example, the object will only contain properties that are being displayed in the grid.
If you have a look here: http://jsfiddle.net/nok06dvu/
I removed "price_eur" from the list of columns in the grid, and your visualObjectRow(0) doesn't include "price_eur" anymore either. The original object with all properties is what should be returned.

**Comment by AMBudnik** [comment]
Hi @duccoder 
you are right the `price_eur` is not returned at it refers to a visible object. 

The `getSourceDataAtRow` is responsible for returning the source object - with all columns and changed data (though reference) like here http://jsfiddle.net/handsoncode/znezqxrc/. Sorry for misleading you before.
If you would like to get an object with data changes you would need to create a copy, like here http://jsfiddle.net/handsoncode/00syxpo0/

Is it the solution you were looking for?

**Comment by dbujold** [comment]
Hi AMBudnik, thank you for the answer. However, this doesn't work if the grid has been sorted, as row 0 is not the same anymore.

What would be the best way to obtain the data object currently represented by row 0? Currently, the only way I see is to display a unique ID in the grid, and use this ID to get the object.

Please see: http://jsfiddle.net/gwf572eo/

**Comment by AMBudnik** [comment]
Hi @dbujold 
sorry I guess that I am a bit lost here with the requirements, but I guess that the last log (added by you) does just what you described. Returns visible row with all columns.

**Comment by dbujold** [comment]
Hi @AMBudnik, you're right that it works, just that I had to do it manually with a filter. :-)
And it forces me to display the ID field in my grid, which I don't want to do. The ID is irrelevant to the user, but I'm forced to display it in order to have it with getDataAtRow(), and be able to filter.

What I was wondering is, is there a better way to do this? Requirement would be, I sort my grid, and I want the full data object at row 0, instead of just an array of visible columns.

**Comment by AMBudnik** [comment]
You could use a custom renderer to display something else than actually is held in a cell but it won't work for filters. I think it will be possible when we'll open filters code or just add an ability to define options visible in the filters. However, I do not see any similar task on our to-do list for May.

**Comment by dbujold** [comment]
Thank you @AMBudnik. However, the feature that is really desirable here is something similar to hot.getDataAtRow(0), but that returns the full source data object instead of an array of visible columns. Is that something being considered for future releases?

**Comment by AMBudnik** [comment]
@duccoder 
we can create a `feature request` topic if you wish (a new one as this has a lot of information). We usually pick new features to do by the number of people who are interested and our ability to develop the feature. Now we are preparing to deliver a new website and after that, we'll add a new wrapper, eco-rendering and will try to boost the performance of scrolling on IE and Firefox as those are the tasks that most our customers were looking for.

**Comment by dbujold** [comment]
It sounds good, thank you!

**Comment by AMBudnik** [comment]
@dbujold Can I ask you to create a topic with this feature request? I think that you'll be the best men for this job as you have tried few approaches before and are able to describe what it should have.

**Comment by dbujold** [comment]
OK, will do. Thanks!
