### ISSUE TITLE
update is slow with many columns and huge viewport

### ISSUE THREAD

**Issue by johnnliu** [handsontable/handsontable#3570]
Hi guys

We really like HOT :-)

We have a scenario where we have about 200-250 rows but about 100 columns.  The users scroll left and right repeatedly to check numbers, and they update two cells right at the end (these two cells will probably might end up being fixed/pinned on the left).  

Because the way the users use the grid - currently in separate excel documents, we have to take the hit upfront and load everything (data takes about 5 seconds to get rendered which isn't too bad), 250 rows isn't too much work - so we set renderAllRows to true.  But to prevent the sluggishness when scrolling left/right, we set the viewportColumnRenderingOffset to 100.  So essentially keeping all columns in memory.  I'm not sure, but I think there's no renderAllColumns setting.

See http://jsfiddle.net/4v3t9tmb/5/

Scrolling is now perfect.  Very happy with this speed.

But updating a cell is now completely horrible.  It seems viewportColumnRenderingOffset is just too much.  I think the entire table (250x100) is being re-rendered on each cell update.  

In this particular example, since 98 of the columns never change data and is readonly, we are thinking we should just be able to tell them not to update.  Is this something that might work?  Can this be done via a renderer?  Open to hear your suggestions.

**Comment by AMBudnik** [comment]
Hi @johnnliu 
You're right - we don't have renderAllColumns yet and you're also right with the update delay.

The renderer is called many times, here's a log for it http://jsfiddle.net/h29v2ty5/. It's 25k times for a 250 x 100 table while loading it and another 25k each time some cell is changed (in the demo it's working even slower as it takes additional time to log all actions).

Here's an improvement suggestion that will speed up this process https://github.com/handsontable/handsontable/issues/2152 (it's closed cause we're keeping all ideas in our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)).
