### ISSUE TITLE
afterChange from dateValidator using wrong row

### ISSUE THREAD

**Issue by creinkin** [handsontable/handsontable#3573]
After updating to v0.25.1(pro version), I noticed an interesting bug in my app. I can't say whether or not this bug also existed prior to 0.25.1 but I have never encountered this until the update.

Anyway, the bug is that if there is row sorting in effect, the afterChange callback being fired after completing the dateValidator function is grabbing the wrong row number (maybe the unordered row number from the data array??), causing the date to be updated on the wrong row after correcting the format! This is very bad indeed when the user intends to change row 1's value and row 5 gets updated instead. To reproduce the issue, go to this working demo: http://jsfiddle.net/0k0m0n4c/2/ and simply type in a start date in M/D/YY format in the first row, and notice that instead of that date correcting format to MM/DD/YYYY, row 5 is updated to reflect the correctFormat fix to the date (notice that the data for row 1 when sorted actually comes from the 5th element in the data array). 

This is causing erroneous AJAX calls in my app and causing other records to be updated in an unintentional way.

**Comment by AMBudnik** [comment]
Got the same result. Thanks for sharing this bug @creinkin 
It has to be an old bug as I was testing it with 0.20.0 version also.

I simplified this example a little bit here http://jsfiddle.net/q1uv5yno/ but I take some cut some rows off or display less columns the code is working fine.

**Comment by creinkin** [comment]
Thanks for verifying, @AMBudnik and also thanks for modifying the fiddle to be more understandable. Apologies for the extra bloat in mine as I was originally chasing the issue with a broad net 😄

**Comment by AMBudnik** [comment]
That's OK - I'm here to make life a little simpler ;-)

**Comment by zbjornson** [comment]
I think this is the same issue as #1501 -- it's not limited to "date" cell types.

**Comment by AMBudnik** [comment]
Thanks for your input @zbjornson 
I guess you're right. We should investigate this subject more. I think that it will be a task for January, still we are planning to unify the way that indexes are passed and used.

**Comment by swistach** [comment]
This should be fixed in #3953

**Comment by AMBudnik** [comment]
Hi @creinkin 
We've made some changes and know all seams to work fine in version 0.30.0. Can you test it please?

**Comment by creinkin** [comment]
@AMBudnik , I will try to take a look at using the 0.30.0 code soon and verify that I experience proper behavior. I will hopefully get to it before end of next week!

Thanks for putting the fix in place!

**Comment by AMBudnik** [comment]
Thanks from your prompt reply @creinkin 
I will than close the issue and if you would find anything suspicious please leave a comment.

**Comment by creinkin** [comment]
Functionality in the problematic fiddle is working correctly after changing script versions to 0.30.0

**Comment by AMBudnik** [comment]
Thanks for confirming @creinkin
