### ISSUE TITLE
Hook for getting and modifying copied (clipboard) cell context

### ISSUE THREAD

**Issue by derdani** [handsontable/handsontable#3576]
As https://github.com/handsontable/handsontable/pull/2103 suggested more than a year ago, I would love to see a "(on-)copy" hook which allows to modify e.g. html-rendered content from a cell when copy/paste-ing it into excel or other applications.

**Comment by AMBudnik** [comment]
Thanks for sharing @derdani Althought there's already an exact issue at https://github.com/handsontable/handsontable/issues/2877
If you have any additional suggestions please share them via https://github.com/handsontable/handsontable/issues/2877
