### ISSUE TITLE
filter for particular columns in handsontable

### ISSUE THREAD

**Issue by basrita** [handsontable/handsontable#3577]
Hi guys,

I have a requirement like handsontable filter shouls be enabled for particular column.

Is there any way to do.

Thanks.

**Comment by AMBudnik** [comment]
Hi @basrita 
Currently filters can be turned on/off _only_ for all columns in the same time.

**Comment by basrita** [comment]
ok thanks. @AMBudnik .
If it is there it will be good

**Comment by seeley60** [comment]
I change source code like this to provide this functionality (not really clean but I need it).
In the onAfterGetColHeader original code :

onAfterGetColHeader: function(col, TH) {
    var headerRow = TH.parentNode;
    if (!headerRow) {
      return;
    }
    var headerRowList = headerRow.parentNode.childNodes;
    var level = Array.prototype.indexOf.call(headerRowList, headerRow);
    if (col < 0 || level !== headerRowList.length - 1) {
      return;
    }
    var existingButton = TH.querySelector('.' + BUTTON_CLASS_NAME);

and I add this just before var existingButton ...

    if (Object.prototype.toString.call( this.hot.getSettings().filters ) === '[object Array]' && this.hot.getSettings().filters.indexOf(col) === -1) {
        return;
    }

And after that you can initialize filters: [0, 2, 4] for example and you have filter button only on columns 0, 2 and 4 ...

**Comment by AMBudnik** [comment]
didn't tested it yet but looks like a clever piece of code @seeley60 
thanks for sharing :+1:

**Comment by rpalcolea** [comment]
Any plans to include @seeley60 solution soon or do you suggest another approach? I think it's a common usage

**Comment by rpalcolea** [comment]
@AMBudnik @krzysztofspilka Any plans to include @seeley60 solution soon or do you suggest another approach? I think it's a common usage

**Comment by AMBudnik** [comment]
I can confirm that this solution works as expected. I've tested it and seems that there are no issues.

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
We can also add the idea for showing or hiding dropdown menu button for some particular columns as suggested here https://github.com/handsontable/handsontable/issues/4253

**Comment by MarcoAbi** [comment]
Meanwhile the feature request will be processed, you can ad an hook into settings and avoid to modify the library itself:
```
hot1 = new Handsontable(table,{  
    data: Handsontable.helper.createSpreadsheetData(100, 5),  
    filters : [2,3,4],
    afterGetColHeader: function(col, TH) {  
    	var BUTTON_CLASS_NAME = 'changeType';
        var existingButton = TH.querySelector('.' + BUTTON_CLASS_NAME);
        if (!this.enabled) {
          if (existingButton) {
            if (Object.prototype.toString.call( scope.settings.filters ) === '[object Array]' && scope.settings.filters.indexOf(col) === -1) {
              existingButton.parentNode.removeChild(existingButton);
            }
          }
          return;
        }
     }
});
```

hope it helps

**Comment by rushi** [comment]
@MarcoAbi good solution but there's one bug, `scope` is not defined. So you can replace that with `this.getSettings()`, so the final code looks like

```js
hot1 = new Handsontable(table,{  
    data: Handsontable.helper.createSpreadsheetData(100, 5),  
    filters : [2,3,4],
    afterGetColHeader: function(col, TH) {  
    	var BUTTON_CLASS_NAME = 'changeType';
        var existingButton = TH.querySelector('.' + BUTTON_CLASS_NAME);
        if (!this.enabled) {
          if (existingButton) {
            if (Object.prototype.toString.call( this.getSettings().filters ) === '[object Array]' && this.getSettings().filters.indexOf(col) === -1) {
              existingButton.parentNode.removeChild(existingButton);
            }
          }
          return;
        }
     }
});
```

**Comment by MarcoAbi** [comment]
Oh Man!
thanks @rushi ! I forgot to clean the code!

**Comment by krzysztofspilka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Filter for particular columns in Handsontable #3577](https://trello.com/c/qaT21L22/106-filter-for-particular-columns-in-handsontable-3577)

**Comment by Campoy10** [comment]
@rushi @MarcoAbi What exactly indicates the condition if (!this.enabled)?

**Comment by MarcoAbi** [comment]
@Campoy10, it should be a parameter you place into HOT settings "this." refers to it.
you can simply remove the check if you always want this "selective filter" behaviour.
BTW, i've experienced some problems with sorting when this "selective filtering" is active. (I've used v1.14.3) if you experience the same error and you find a solution, please let me know!

Best
Marco

**Comment by Campoy10** [comment]
@MarcoAbi, Thank you very much, the doubt was because I am implementing your solution for a handsontable with the Angular framework and I wanted to understand that condition. The solution has helped me a lot because it works perfectly and I'm not having that problem.

Alex Campoy

**Comment by rodolfosouza** [comment]
workaround

`	  afterGetColHeader: function(col, TH) {  
	      var filter = TH.querySelector('.changeType');
	      if (!this.enabled && filter) {
	        if(hasString(this.getCellMeta(0,col).className,'c_no_filter')) {filter.parentNode.removeChild(filter);} return;
	      }
	  },`
and my column param
```
...
columns:[{dfcode:'001',	data: 'code',    								title: _i18n('gn.export.it.code'),className:'c_no_filter'}]
....
```

**Comment by PradeepGdr** [comment]
i'm trying to filter my data in dropdown but on typing the exact value it is pointing to some other values and hides the exact value. not sure if i miss anything.

**Comment by AMBudnik** [comment]
Hi @PradeepGdr 

Can you share your demo with me on support@handsontable.com?

**Comment by PradeepGdr** [comment]
> Hi @PradeepGdr
> 
> Can you share your demo with me on [support@handsontable.com](mailto:support@handsontable.com)?

var container = document.getElementById('tblConfigurableDataTable'); var hotConfigurableDataTable = new Handsontable(container, { data: parsedData, licenseKey: licenseKey, colHeaders: colHeaders,// ex. Name,Company... columns: columns, dataSchema: dataschema,// this is my list of data rowHeaders: true, headerTooltips: true, viewportColumnRenderingOffset: 100, width: $(window).width() - 120, height: height, contextMenu: ['row_above', 'row_below','remove_row', '---------', 'undo', 'redo', '---------', 'copy'], columnSorting: true, sortIndicator: true, filters: true, dropdownMenu: ['filter_by_condition', 'filter_action_bar'],
outsideClickDeselects: false, minSpareRows: 1, manualRowMove: true, }

**Comment by AMBudnik** [comment]
Hi All.

We are moving feature ideas and improvements to Github Discussions to gather all the ideas on UI and API. That will help us to continue the development of the functionality in the future.

Please feel welcome to share your feedback via the Github Discussions panel if you have any additional ideas.
