### ISSUE TITLE
Cursor type is text when not in edit mode

### ISSUE THREAD

**Issue by danielmathiesen** [handsontable/handsontable#3578]
While user testing our solution which uses handsontable I found a issues which i think may be a bit confusing for users. When I hover the cursor over text in handsontable when NOT in edit mode, the text cursor is shown. Which indicates that the user can select/edit text. But in reality this is not possible until user double tap to get into edit mode. This can lead to confusion for users who are NOT in edit mode, but intuitively expecting to be able to edit/select text because the cursor is in text mode.

I checked Excel and Google Docs and both of these applications shows some kind of default cursor or crosshair when NOT in edit mode. This communications that the user is NOT in text edit mode. When user double tap cell in Excel or Google Docs so they get into edit mode the cursor changes to text mode.

In our implementation of Handsontable we have now manually adjusted the CSS so the cursor is NOT in text mode until has double tapped a cell and is in edit mode. We hope this will help our users more easily understand that they need to double tap to select/edit text. Maybe this should be the default cursor behaviour in Handsontable? :)

Note that we have no conducted any comprehensive user testing to prove that changing the cursor behaviour will increase the quailty of the user experience. But from our limited testing and how Google Docs and Excel work I think it would make sense. But there could be cases or situations I have not thought about?

Added screenshot to show the differences between Excel, Google Docs and Handsontable.
![cursor](https://cloud.githubusercontent.com/assets/3049284/16074135/66cf0958-32e9-11e6-8513-1823db6a7dd7.jpg)

**Comment by AMBudnik** [comment]
Thanks for sharing this proposition @danielmathiesen 

We're having an arrow cursor when we mouse over an empty cell or a space between data in a non-empty cell but as you already discovered other big players are doing it differently.
I think that we should reconsider this change.

**Comment by AMBudnik** [comment]
Currently you are able to start writing (if a cell is selected) by just typing any character.
