### ISSUE TITLE
readOnly state copied with dragging

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3581]
Demo: http://jsfiddle.net/d2gyskz2/

Case 1
Drag `0, 0` cell down to 3rd row
![1](https://cloud.githubusercontent.com/assets/10757813/16080303/66641e76-3308-11e6-9180-b21d6c52479c.png)
![2](https://cloud.githubusercontent.com/assets/10757813/16080304/676684ee-3308-11e6-911b-0cb7e724c9da.png)
result: All fine, only 3rd row is duplicated.
![a1](https://cloud.githubusercontent.com/assets/10757813/16080825/ecbd812c-330a-11e6-8a37-0dee71e53a11.png)

Case 2
Drag `0, 0` cell down to last row (by creating new row)
![1](https://cloud.githubusercontent.com/assets/10757813/16080303/66641e76-3308-11e6-9180-b21d6c52479c.png)
![3](https://cloud.githubusercontent.com/assets/10757813/16080378/d92e1bb4-3308-11e6-8e8c-bbf0d854a1a9.png)
result: before you release a <kbd>LMB</kbd> readOnly state is copied to the cell in 3rd row. Dragging the selection even lower (producing more empty rows) will add readOnly state to row: 4th, 5th, 6th and so on.
![a2](https://cloud.githubusercontent.com/assets/10757813/16080829/f1793da0-330a-11e6-9ca1-b9fab0eefe8f.png)
![a3](https://cloud.githubusercontent.com/assets/10757813/16080910/4edcbf58-330b-11e6-890a-aace449eef5a.png)

**Comment by AMBudnik** [comment]
Additionally you can see at the last image that the extra readOnly state disallows to paste copied (by dragging) data so the cells in few rows remains the same.

**Comment by AMBudnik** [comment]
Still present in 0.29.2, demo: http://jsfiddle.net/handsoncode/w6mwLm7w/

**Comment by wszymanski** [comment]
Fixed in #3989.
