### ISSUE TITLE
sortIndicator stays after columnSorting: false

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#3582]
hello,
i try to find a method to clear the user manual sort order but it seems that the method sort accept only
true or false (ascending or descending).

any idea would be appreciate 
jeanmarc

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 
`hot.sortColumn` allows you to check if data was sorted, it returns `undefined`if sorting wasn't made, demo: http://jsfiddle.net/pm3hro1a/
Currently only changing sorting to `false` disables any sorting changes that were made on the data,

**Comment by jeanmarc78** [comment]
ok , thanks a lot

 if (hot.sortColumn !== undefined)
  {
hot.updateSettings({
  columnSorting: false
});
hot.updateSettings({
  columnSorting: true
});

}

**Comment by varun-dev** [comment]
@AMBudnik,

This looks like a good way to clear the sorting but there is a bug. When you updateSettings to set columnSorting to false, the sort indicator stays there. @jeanmarc78. did you get any workaround for that?

**Comment by AMBudnik** [comment]
Varun is right. I made a demo where we can replicate it: http://jsfiddle.net/jcaksrnq/
I tried to set `sortIndicator: false` and add some extra rendering but it did help. 
Turning off and then on the `colHeaders` didn't help as well.

**Comment by varun-dev** [comment]
@AMBudnik 

It looks like there are more issues. After we clear the sorting, following two options are also not reset
`hot.sortingEnabled`,`hot.sortColumn`

Demo - http://jsfiddle.net/varun_dev/jcaksrnq/2/

Is there any hope for a fix soon?

Thanks

**Comment by AMBudnik** [comment]
Thank you for your investigation @varun-dev 
even when we disable the plugin we still get the sorting results: http://jsfiddle.net/AMBudnik/ukdnj3kL/

I found a related issue: https://github.com/handsontable/handsontable/issues/3434 (`columnSorting` cannot be updated via `updateSettings`), but...
in our demo we disable the plugin as well and it won't help.

**Comment by AMBudnik** [comment]
The issue still replicable in v0.35.0

![issue](https://user-images.githubusercontent.com/10757813/35147414-ca72794a-fd0e-11e7-99f4-792be17f507e.gif)

**Comment by AMBudnik** [comment]
The plugin has been rewritten. Here is a new implementation that solved this issue http://jsfiddle.net/handsoncode/xL6w7a3v/
