### ISSUE TITLE
Automatic adjust height according to row count

### ISSUE THREAD

**Issue by jmtolibas** [handsontable/handsontable#3583]
Hi, is there a way to adjust the handonstable height according to row count?

**Comment by AMBudnik** [comment]
Hi @jmtolibas 
height option can be a function so you can pass anything you want. 
By default Handsontable adjust its height to number of rows (http://jsfiddle.net/f3ts5pef/). Can you tell me what you exactly would like to get?

**Comment by AMBudnik** [comment]
Issue closed in lack of Author's reply
