### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentNode' of null, on after moving the horizontally scrolled colum

### ISSUE THREAD

**Issue by naushadkm** [handsontable/handsontable#3584]
@AMBudnik 
@jansiegel 
@krzysztofspilka

Column move throws exception in the console.

If Handsontable container is horizontally scrollable and once you scroll to the rightside end and try to move the last column to its previous column index (move column F to E's position). the framework throws an error: Uncaught TypeError: Cannot read property 'parentNode' of null in the console.

Please refer the filddle created: [http://jsfiddle.net/nkm/gxrxa6ns/1/](http://jsfiddle.net/nkm/gxrxa6ns/1/)

**Comment by AMBudnik** [comment]
Reproduced (Chrome 51/Win8)
Thanks for sharing @naushadkm !

**Comment by swistach** [comment]
Hi @naushadkm 
Currently looks as it works properly. (version: 0.28.4)

**Comment by Aden-Kurmanov** [comment]
I had this error

Normal:
![image](https://user-images.githubusercontent.com/65890928/174725257-588a53b6-1ec6-4f15-8686-109dfc9f3f56.png)


while editing cell:
![image](https://user-images.githubusercontent.com/65890928/174725296-f36a401a-471b-4be3-8241-4ddda8cd9cd7.png)

after edition cell:
![image](https://user-images.githubusercontent.com/65890928/174725361-6a28ab39-2ba1-44c8-8c88-4a950624ac1b.png)

and error:
![image](https://user-images.githubusercontent.com/65890928/174725140-de7637df-3588-4e08-8602-9e41952d223c.png)

It happened in angular
version of handsontable 8.2.0
