### ISSUE TITLE
how to set autocomplete source for all cells?

### ISSUE THREAD

**Issue by aokaywe** [handsontable/handsontable#3586]
I find only set autocomplete source for fix columns.  it have any way set global source?

**Comment by AMBudnik** [comment]
Hi @aokaywe 
You can set your source as a variable and then pass it. http://jsfiddle.net/30ob0you/
Although every time you create an autocompelete column you have to define a source for it.

**Comment by aokaywe** [comment]
Thanks for a quick reply.  but i want use "autocomplete" and "allowInsertColumn" at the same time, what should I do?

**Comment by AMBudnik** [comment]
you would need to overwrite the context menu `insert_column` option as it is currently unavailable for fixed amount of columns (provided by `columns` settings) 

At the 'Context menu with fully custom configuration' section of https://docs.handsontable.com/pro/1.4.1/demo-context-menu.html you can find a demo how to define a custom context menu.

**Comment by aokaywe** [comment]
Thanks again. I get fllow error when use custom insert_column
`Uncaught Error: Cannot create new column. When data source in an object, you can only have as much columns as defined in first data row, data schema or in the 'columns' setting.If you want to be able to add new columns, you have to use array datasource. `

my code:
` javascript
var autocompleteArray = [
        "11",
        "22",
        "33"
    ];
kwtable = new Handsontable(
        container.getElementById(elementId),
        {
            minRows: 10,
            colHeaders: true,
            rowHeaders: true,
            colWidths: 150,
            manualColumnResize: true,
            manualRowResize: true,
            fixedColumnsLeft:10,
            contextMenu: {
                callback: function (key, options) {
                    selection = this.getSelected();
                    if (key === 'insertRow'){
                        this.alter('insert_row', selection[0]);
                    } else if (key === 'removeRow') {
                        var amount = selection[1] - selection[0] + 1;
                        this.alter('remove_row', selection[0], amount);
                    } else if (key === 'insertCol') {
                        this.alter('insert_col', selection[3]);
                    } else if (key === 'removeCol') {
                        var amount = selection[4] - selection[3] + 1;
                        this.alter('remove_col', selection[3], amount);
                    }
                },
                items:{
                    'insertRow':{
                        name:"插入行",
                        disabled: function () {
                            return this.getSelected()[0] === 0;
                        }
                    },
                    'removeRow':{
                        name:"删除行",
                        disabled: function () {
                            return this.getSelected()[0] === 0;
                        }
                    },
                    "hsep1": "---------",
                    'insertCol':{
                        name:"插入列",
                        disabled: function () {
                            return this.getSelected()[1] === 0;
                        }
                    },
                    'removeCol':{
                        name:"删除列",
                        disabled: function () {
                            return this.getSelected()[1] === 0;
                        }
                    }
                }
            },
            columns: [
                {
                    type: 'autocomplete',
                    source: autocompleteArray,
                    language: 'zh-CN',
                    strict: false,
                    trimDropdown: false
                },
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ]
        });`

**Comment by AMBudnik** [comment]
That's right. You need to add a new column into `columns`.  To do so via the context menu you would need to call the `updateSettings`. 

I guess that the best solution would be to share columns via function. There you'll be able to track the selected column (`instance.getSelected()[1]`) and push the new column into expected place.

**Comment by aokaywe** [comment]
I update my code, if i insert a col, the col will append to the end, not expected place, how to improve it ? 

```
callback: function (key, options) {
    selection = this.getSelected();
    if (key === 'insertRow'){
        this.alter('insert_row', selection[0]);
    } else if (key === 'removeRow') {
        this.alter('remove_row', selection[0], selection[2]);
    } else if (key === 'insertCol') {
        var cols = this.getSettings().columns;
        cols.splice(selection[1],0,{});
        this.updateSettings({columns:cols});
    } else if (key === 'removeCol') {
        var cols = this.getSettings().columns;
        cols.splice(selection[1],selection[3]);
        this.updateSettings({columns:cols});
    }
}
```

**Comment by AMBudnik** [comment]
Hi @aokaywe 
I made some example here: http://jsfiddle.net/1my0pct0/
It adds an empty column via context menu for both sides: left and right.

**Comment by aokaywe** [comment]
@AMBudnik  Thanks a lot, my problem was solved!

**Comment by AMBudnik** [comment]
great @aokaywe 
thanks for keeping me updated.
