### ISSUE TITLE
Hansontable SortIndex is not updating on each ajax load

### ISSUE THREAD

**Issue by ravi590** [handsontable/handsontable#3587]
Hi @AMBudnik , I am loading batch of recorts into handsontable using ajax call, so that when user scrolls down another 20 records(batch) will be pulled using ajax and added to handsontable.Once i get new set of records in UI,I'm pushing each object into "handsonInstance.getData()" and i'm using "handsonInstance.render()" to show the new set(new batch) of records in the UI.

When user edits a cell,i'm getting the physical index of the cell using "handsonInstance.sortIndex", but in "handsonInstance.sortIndex", I'm able to see only records that are loaded initially in the handsontable, the latest records pulled using ajax are not getting reflected in "handsontable.sortIndex".

Can you let me know how to update "handsontableInstance.sortIndex" on each ajax batch load?

**Comment by budnix** [comment]
Hi @ravi590, could you prepare demo on jsfiddle or codepen? It will be easier for us to fix it working on your code snippet.

**Comment by AMBudnik** [comment]
Sine there was no reply for more than 3 weeks I'm closing this issue
