### ISSUE TITLE
addFormula doesn't hide rows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3589]
demo: http://jsfiddle.net/gqz1m8xm/1/

If we add `begins with 'o'` for this data in the first column...

![1](https://cloud.githubusercontent.com/assets/10757813/16196017/74b062bc-36fc-11e6-8cef-fa9161d8bdaa.png)

we should get only one row but we're getting 1 row with data and 4 empty rows.

![2](https://cloud.githubusercontent.com/assets/10757813/16196022/78c31584-36fc-11e6-85ef-d9f77b05cf62.png)

**Comment by budnix** [comment]
Probably related with https://github.com/handsontable/handsontable/issues/3808

**Comment by wszymanski** [comment]
Fixed within @4131
