### ISSUE TITLE
Add TFOOT to grid

### ISSUE THREAD

**Issue by groc426** [handsontable/handsontable#359]
I've been attempting for hours to implement a tfoot at the bottom of the grid.  Unfortunately, my attempts have all pretty much failed.  I was hoping to total individual columns at the bottom of the grid.  If something like colHeaders could be implemented but for a footer, I think that would be awesome!!

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by larvanitis** [comment]
Any news? Where are you going to track the "fixed footer" feature progress so I can monitor it?

Is subscribing to this issue relevant?

**Comment by AMBudnik** [comment]
Feature already added in Handsontable PRO as [Fixed Rows Bottom](https://docs.handsontable.com/pro/1.10.0/Options.html#fixedRowsBottom)
