### ISSUE TITLE
Mouse wheel scrolling weird behavior

### ISSUE THREAD

**Issue by samsonkhisty** [handsontable/handsontable#3590]
Browser: Chrome 51, 
OS: Mac El Capitan 10.11.5
Issue is the same with an external mouse or using the trackpad.  
smoothscrolling - flag unavailable in chrome 51

**Mouse wheel scrolling** is smooth in jsfiddle but the same code in a local HTML file is very janky/jumpy/choppy. This does not happen in jsfiddle example (same browser). Even a slow scroll shows a pixel alignment mismatch in the row header trying to sync with the data row. 

**Video for comparison:** 
jsfiddle video:  https://www.dropbox.com/s/r56oi1ucwfylc1j/jsfiddle.mov?dl=0
local HTML video: https://www.dropbox.com/s/0c3azzn0vm0e0r5/localhost.mov?dl=0

jsfiddle example: https://jsfiddle.net/fuggfuggfugg/n6v4rvja/3/ 
localhost example: [datatable.html.zip](https://github.com/handsontable/handsontable/files/323964/datatable.html.zip)

**Comment by AMBudnik** [comment]
Hi @samsonkhisty 

Thanks for sharing. Can you also share you OS and (if there are) the browser addons?

I get the same result with the fiddle and on the localhost.

**Comment by samsonkhisty** [comment]
@AMBudnik 
OS: Mac El Capitan 10.11.5 (15F34)

However when testing I [disable all the extensions](https://chrome.google.com/webstore/detail/disable-extensions-tempor/lcfdefmogcogicollfebhgjiiakbjdje) to make ensure there's no interference.

Browser Add-ons list:
- Application Launcher for Drive (by Google) 3.2 | Enabled 

- Awesome Screenshot App 1.0.5 | Enabled 

- Awesome Screenshot: Screen capture, Annotate 3.9.8 | Enabled 

- ColorZilla 0.5.6 | Enabled 

- Dimensions 2.0.3 | Enabled 

- Ghostery 5.4.11 | Enabled 

- Google Docs 0.9 | Enabled 

- Google Docs Offline 1.4 | Enabled 

- HTTPS Everywhere 2016.6.9 | Enabled 

- LastPass: Free Password Manager 4.1.16 | Enabled 

- LiveReload 2.1.0 | Disabled
  
- PageSpeed Insights (by Google) 2.0.4.3 | Disabled
  
- PageSpeed Insights (with PNaCl) 0.0.1.2 | Enabled 

- Panda 4 | News & Inspiration Dashboard 4.14.2 | Enabled 

- Postman 4.3.3 | Enabled 

- Reddit Enhancement Suite 4.6.1 | Enabled 

- Super Browse for Netflix 1.4 | Enabled

**Comment by AMBudnik** [comment]
I've just checked twice on Win 8 and OSX. My colleague said that there's a slight lagging on Safari. Here'll send us a video how it's working.

I'll mark this issue as related to performance.

**Comment by amoghmalik** [comment]
Here is the video of the issue in Safari 9.1.1: 

http://sendvid.com/p73jhi7t

**Comment by samsonkhisty** [comment]
@amoghmalik That is a perfect example. Also what are you using for recording?

**Comment by amoghmalik** [comment]
@samsonkhisty I'm using QuickTime

**Comment by swistach** [comment]
Hi @samsonkhisty, 
We've changed a scroll mechanism in v0.38.1. Currently, the table should be scrolled smoothly.
Please check out the updated demo: https://jsfiddle.net/1z7sk4qw/

Feel free to reopen, if this problem is still occurring.
