### ISSUE TITLE
Checkbox cells not working correctly when readOnly property is set through cells function

### ISSUE THREAD

**Issue by ben-bialobrzycki** [handsontable/handsontable#3593]
example 
http://jsfiddle.net/eytqjo80/1/

if readOnly flag is set through cells function other celltypes e.g text work ok, but checkbox does not. Changing from initial readOnly:true to false results in checkbox that cannot be clicked but can still toggle on/off by space key, but corresponding onChange events do not fire.

Noticed problem when trying to upgrade from version 0.18 to version 0.24 or 0.25
[checkboxbug.zip](https://github.com/handsontable/handsontable/files/326042/checkboxbug.zip)

**Comment by AMBudnik** [comment]
thanks for sharing Ben.
We already have very similar issue at https://github.com/handsontable/handsontable/issues/3562
If you think that we're missing some crucial details please leave a comment at https://github.com/handsontable/handsontable/issues/3562
