### ISSUE TITLE
Column width is not applied to the table after 'updateSettings' is completed

### ISSUE THREAD

**Issue by IgorVM** [handsontable/handsontable#3594]
If I'm trying to do 'updateSettings' with updating columns and columnHeaders, new width of the columns will be recalculated, but it will not be applied to the table.
It was working in version 0.15.0-beta2 and it's not working since it was completely moved to the plugin

Example: http://jsfiddle.net/Ufie/rf97ps5h/

**Comment by AMBudnik** [comment]
Thanks for sharing @IgorVM 
I simplified a demo a little bit: http://jsfiddle.net/esg12cyx/ but you're right - `updateSettings `doesn't update `colWidths`.

**Comment by swistach** [comment]
Hi @IgorVM,
Since v2 updating settings for `colWidths` and `colHeaders` works correctly: https://jsfiddle.net/o9gz17xr/
Thank you for your involvement!
