### ISSUE TITLE
select cell renderer?

### ISSUE THREAD

**Issue by pjt1024** [handsontable/handsontable#3595]
hi,is there any  'select' cell renderer in cell renderers?I want to display innerHTML  prop of  an option ,save value prop of an option?can we do this?

**Comment by AMBudnik** [comment]
Hi @pjt1024

**Comment by AMBudnik** [comment]
I'm not sure if I fully understand the concept. Can you share a draft/video of it?

**Comment by pjt1024** [comment]
hi,
AMBudnik,thank you for your reply.My English is poor.I am sorry.
My Problem just like this:

here is  one column of handsontable  

{data: "DBType", editor: 'select', selectOptions: ['varchar', 'char', 'datetime', 'binary'] }

i have two buttons:

 <button onclick="getData1()">GetData</button>  
 <button onclick="loadData1()">LoadData</button>  

javascript function:

function loadData1() {
                hot.loadData(data1);
 }

Question 1:
when I click the first button,the cell of DBType cannot display anything,but 'varchar' should be displayed,

Question 2:
I want to define a column like this:
{data: "DBType", editor: 'select', selectOptions: [{value:"varchar",text:"varchar1"}, 'char', 'datetime', 'binary'] },

so the editor's HTML will be like this 
<select>
<option value="varchar">varchar1</option>
...
</select>

when I click the first button,'varchar1' should be displayed,
when I run  getData function,varchar should be read instead of varchar1

can you understand?

**Comment by AMBudnik** [comment]
No.. it's not the English, It's more the ability to share the same vision about the end results. Like they say - let the code share our needs and goals.

> Question 1:
> when I click the first button,the cell of DBType cannot display anything,but 'varchar' should be displayed,

For the first case please check this demo: http://jsfiddle.net/r5df3bva/. If you want to display some value in the select field you need to fill the cell with data. Select doesn't get any default value. The second example uses `setDataAtCell` method to get the same result.http://jsfiddle.net/uk4c06rr/


> Question 2:
> I want to define a column like this:
> {data: "DBType", editor: 'select', selectOptions: [{value:"varchar",text:"varchar1"}, 'char', 'datetime', 'binary'] },
> 
> so the editor's HTML will be like this 
> varchar1 ...
> 
> when I click the first button,'varchar1' should be displayed,
> when I run getData function,varchar should be read instead of varchar1

This option is currently unavailable. .

**Comment by pjt1024** [comment]
thank you.
AMBudnik,you are a good man!!!

**Comment by AMBudnik** [comment]
Thank you :-) 
Glad i could help
