### ISSUE TITLE
Add borders dynamically through Context Menu

### ISSUE THREAD

**Issue by evalle012006** [handsontable/handsontable#3596]
Hi, 

I would like to add an event in my context menu in which when I clicked it will change the border of the selected area cells. Is there a way to do it? I tried the following:

hot.render();
hot.view.wt.draw(true);
hot.customBorders = myNewCustomBorders;

But still there's no changes after this.

By the way I put the event in the callback function of that context menu.

Any help will be appreciated. Thank you

**Comment by AMBudnik** [comment]
If I understand correctly it should be something like this: http://jsfiddle.net/ra0qmvwh/

**Comment by evalle012006** [comment]
Oh thank you for the answer. But I want to add border in all sides :)

**Comment by AMBudnik** [comment]
This will take more effort and we cannot change what's in the submenu (bug) you would need to create an option to add borders and add it to context menu.
