### ISSUE TITLE
Table Functionality breaks when adding a div to the containers parentElement

### ISSUE THREAD

**Issue by seharri92** [handsontable/handsontable#3598]
After a table is created and rendered, if a div is added to the parent of the table container (for example a popup window) all the functionality of the table is lost. You must remove and construct the table again for the functionality to come back.
Demo: http://jsfiddle.net/cddt6k03/

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/3366

**Comment by AMBudnik** [comment]
As we already discussed on support channel and at https://github.com/handsontable/handsontable/issues/3366 we should not use `innerHTML` to add elements to the HOT's parent. Changing to `createElement` and appending the new child to the parent solves the issue.
