### ISSUE TITLE
deleting rows without shifting rows in the viewport

### ISSUE THREAD

**Issue by varun-dev** [handsontable/handsontable#3599]
Is it possible to delete rows which are outside the viewport without shifting the viewport ??

My use case :

- I have 100 rows
- I am looking at row 20 - 50
- Now I want to delete row 1 - 5 without shifting the rows in the viewport

I am trying to achieve pagination by scrolling so I need to add rows and delete rows. Any tips would be appreciated.

**Comment by varun-dev** [comment]
#2859 #2784

**Comment by varun-dev** [comment]
#2859 #2784 #607

**Comment by AMBudnik** [comment]
Hi @varun-dev 
You can use `alter` method. Here's an example: http://jsfiddle.net/9a8vzbrz/
and here's a docs description: https://docs.handsontable.com/pro/1.4.1/Core.html#alter

**Comment by varun-dev** [comment]
Hi @AMBudnik,

Thanks for your response. Yes I already tried that, you will notice in your example that if you scroll down to let say row 30 and then you delete records 1-5, your viewport will shift by 5 records. And that is blocking me from implementing infinite scroll.

Looking forward to your response.

Varun

**Comment by AMBudnik** [comment]
You're right!

Hm.. I think that maybe you can chose `scrollToViewport` but you would need to track the current visible rows.

**Comment by varun-dev** [comment]
Yes, that's what I am doing a the moment, but a bit flaky.

Considering forking and sending you guys a PR for infinite scrolling but my company ICAP's legal team is still sorting out some policies around open source.

**Comment by AMBudnik** [comment]
Oh, that's OK - thanks for the effort :-)
