### ISSUE TITLE
afterScrollVertically called twice on scrollViewportTo

### ISSUE THREAD

**Issue by varun-dev** [handsontable/handsontable#3601]
`afterScrollVertically` is called twice when we call `scrollViewportTo`
Once before scroll and once after scroll.

**Comment by AMBudnik** [comment]
Thanks for sharing @varun-dev 
here's a demo: http://jsfiddle.net/1pf9d1kq/

**Comment by swistach** [comment]
Hi @varun-dev,
I've prepared small change for `scrollViewportTo`, but it not resolve a global problem with too many calls of callbacks after scrolling.
Unfortunately, present mechanism of the scroll synchronization doesn't works in  perfect way.
We have to discuss about it in core-team.

**Comment by AMBudnik** [comment]
Hi @varun-dev 
Can you check the newest version? I really would like to know if it works for you.

**Comment by AMBudnik** [comment]
@varun-dev 
I'm closing this issue but if you still experience any issues please do not hesitate to write me back.
