### ISSUE TITLE
minSpareRows is duplicated if dataSource contains nested objects

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#3602]
Hi guys,

I have a problem with `minSpareRows` option. Simple example:

``` javascript
var data = [1, 2, 3].map(item=> ({
            id: item,
            name: 'John',
            data: {address: ['USA', 'Washington']}
        }));

var columns = [
            {data: 'id'},
            {data: 'name'},
            {data: 'data.address'}
        ];
```

These options provides the following output:
![image](https://cloud.githubusercontent.com/assets/710513/16305203/8230287a-3961-11e6-9521-9266c768f059.png)
The last empty row is duplicated. If I specify `minSpareRows: 2` then I see 4 empty rows

But if I remove nesting, then it looks like this:

``` javascript
var data = [1, 2, 3].map(item=> ({
            id: item,
            name: 'John',
            address: ['USA', 'Washington']
        }));
var columns = [
            {data: 'id'},
            {data: 'name'},
            {data: 'address'}
        ];
```

![image](https://cloud.githubusercontent.com/assets/710513/16305315/f35ca2ee-3961-11e6-96dd-0f32e04a1e17.png)

This looks fine.

**Comment by AMBudnik** [comment]
Confirmed. Here's a demo for this example: http://jsfiddle.net/cjvhqLcz/
Thanks for sharing the issue and for the screen shots @andrewQwer

**Comment by andrewQwer** [comment]
You are welcome :wink:

**Comment by AMBudnik** [comment]
Still present in v0.30.1

**Comment by andrewQwer** [comment]
Also found strange behavior regarding this bug. If you start clicking on any cells then extra cells are created. See an example: https://www.screencast.com/t/VeLqjgodlqL
@AMBudnik , any chance this bug will be fixed soon?

**Comment by andrewQwer** [comment]
Found the problem of this issue. Looks like `dataSchema` property is calculated incorrectly if not passed.
If I pass `dataSchema` explicitly then problem goes away. See an example: http://jsfiddle.net/cjvhqLcz/1/

**Comment by AMBudnik** [comment]
Thank you @andrewQwer 
we have been reported an issue related to using the wrong schema here https://github.com/handsontable/handsontable/issues/4175 however I do not know if fixing any of the issues will fix the second one as well.

**Comment by AMBudnik** [comment]
This issue is no longer replicable in `7.4.2` http://jsfiddle.net/kej81wua/
Thank you for sharing. I hope that you can still benefit from this fix.
