### ISSUE TITLE
on sorting, all data is selected

### ISSUE THREAD

**Issue by varun-dev** [handsontable/handsontable#3603]
Hi, 

is there a way to avoid this? 
My colleagues and I can't event think of any use case to have all the data selected if I sort :)

Thanks

**Comment by budnix** [comment]
Hi @varun-dev,

Handsontable currently doesn't have any official option for disabling selection while sorting. But using hook you can prevent this behavior. I've created demo at http://jsfiddle.net/62ch3oe3/.
