### ISSUE TITLE
vertical fillHandle with autoInsertRow: false

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#3604]
Hi guys,

Is there any way I can specify `fillHandle: 'vertical'` with `autoInsertRow: false`?
From documentation:
```
fillHandle: { // enable plugin in both directions and with autoInsertRow as false
  autoInsertRow: false,
}
```
But I don't want **both** directions.

**Comment by budnix** [comment]
Hi @andrewQwer, Yes sure it's possible by adding `direction` property. I've created demo at http://jsfiddle.net/qcba7csy/.

BTW: I saw that this property is not described in our docs so I'll do it now.

**Comment by andrewQwer** [comment]
Thank you! That is what I was looking for
