### ISSUE TITLE
Cell renderer

### ISSUE THREAD

**Issue by michailw** [handsontable/handsontable#3605]
I have one idea. I've discovered that I have to run `setDataAtCell` if I want to run cell renderer.
But this is unneccesarry, when I want only to add cell with some buttons. Is there possibility to allow cell renderer beeing called, even if there is no data at this column?

**Comment by AMBudnik** [comment]
Hi @michailw 
Can you describe more details about what you would like to get? 
Cell renderer is called :
* when table is initialized
* every time data has been changed
* you can call it manually by `instance.render()`

**Comment by AMBudnik** [comment]
Issue closed in lack of Author's reply
