### ISSUE TITLE
Sorting can be unstable (we use browser Array.sort function)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3606]
demo: http://jsfiddle.net/dr6w8jc4/

I tried to reproduce it with less data but it's not working for short tables.

Scenario:
1. Set a filter `contains` in the last column for value `true`
2. Sort the second (middle) column
3. Repeat step 2 few times

You'll see that data gets sorted within first two rows.

**Comment by wszymanski** [comment]
> I tried to reproduce it with less data but it's not working for short tables.

This sentence is crucial. @AMBudnik you probably tested that on **Google Chrome**, didn't you?

We use standard **Array.sort** for sorting. In Google Chrome (tested on Chrome 56) should work as expected for end user when Handsontable has up to 10 rows: http://jsfiddle.net/wojciech/fe70bp1f/4, but it shouldn't for more than 10 rows: http://jsfiddle.net/wojciech/fe70bp1f/3

Behavior of the **Array.sort** depends on the browser.

> The sort is not necessarily stable.
[Source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)

> Chrome’s v8 uses a combination of InsertionSort and QuickSort. That is, if the array is less than 10 elements in length, it uses an InsertionSort.
[Source]( https://www.quora.com/What-is-the-sorting-algorithm-behind-a-Javascript-Array-sort-method)

**Comment by budnix** [comment]
Corresponding changes were made in documentation at https://github.com/handsontable/docs-pro/commit/7848cc84503928b7a0420ac42fff78feb0bc3cfd and https://github.com/handsontable/docs/commit/e90416dd5d432496a89ee6a9bfc8754d8d1cc7da

**Comment by AMBudnik** [comment]
Great, it works as expected now.
