### ISSUE TITLE
demo pre populating not working correctly ?

### ISSUE THREAD

**Issue by koenhandekyn** [handsontable/handsontable#3608]
the demo on the documents page about pre population of data does not seem to work as advertised. on edit the default vaues are not taken from the template row.

https://docs.handsontable.com/pro/1.4.1/demo-pre-populating.html

**Comment by AMBudnik** [comment]
Hi @koenhandekyn 
When the empty row is added it get's the schema from the `tpl` array and if you type anything in the row the values are gone.
Do you experience any bugs?

**Comment by koenhandekyn** [comment]
thanks for the reaction. i'm probably misunderstanding the demo. from a functional point of view it would make sense that as soon as something is entered the default values are taken over from the template row for the current row being edited. in the current demo, the whole row turns blank on edit and the new empty row get's the defaults but that doesn't seem to really make sense for me from a functional point of view.

**Comment by AMBudnik** [comment]
So I guess that you would want to get only one cell blank and the rest should stay?
If so you could check if new action created a row, like here: http://jsfiddle.net/uahbrapr/1/ and if so look for the empty row with `isEmptyRow(row)` method and for example use `setDataAtCell` to add values.
