### ISSUE TITLE
External/internal copied data

### ISSUE THREAD

**Issue by klikstermkd** [handsontable/handsontable#3610]
Is there a way to find out when you paste some text, and check whether that text has been copied from the spreadsheet itself, or somewhere else, i.e. another website, excel etc.

**Comment by AMBudnik** [comment]
unfortunately there are no callbacks for paste (which can add this information).
In the worst scenario you can check suing `beforeChange` hook if the data that will be pasted is present somewhere in the table.

**Comment by klikstermkd** [comment]
> In the worst scenario you can check suing beforeChange hook if the data that will be pasted is present somewhere in the table.

This won't be an option because maybe the external data is the same as the one already in the table.

**Comment by klikstermkd** [comment]
I need this functionality because I am using rich text data inside the cells, and when I copy data from the table I want to preserve the data formats, but if I copy from somewhere else, it should paste as a plain text.

**Comment by AMBudnik** [comment]
Hm.. it's a hard case I have to say. I was thinking something about to add a class to every cell by the `cells` method and then track if data copied === the div with the `hot` class but we do not have similar functionalities in Handsontable. Guess it can be made with pure JavaScript but it can take some extra actions.
