### ISSUE TITLE
Firefox issue with Cell input

### ISSUE THREAD

**Issue by aliirz** [handsontable/handsontable#3611]
Hi All

I am having some trouble using hot in a modal. I have lots of rows so generally my handson table is able to scroll. When i select a cell for input I get this weird behavior:

<img width="443" alt="screenshot 2016-06-28 11 10 00" src="https://cloud.githubusercontent.com/assets/743962/16405726/4f97d79e-3d23-11e6-8add-f9f2fab5c9df.png">

As you can see my input area is far right from the selected cell. This happens only on firefox. Any help will be appreciated

**Comment by AMBudnik** [comment]
Hi @aliirz 
Without a demo it'd be hard to say anything but I think it can have something to to with the CSS

**Comment by AMBudnik** [comment]
Issue closed in lack of Author's reply
