### ISSUE TITLE
Comments added while initalizing handsontable are disappearing after handsontable loaded

### ISSUE THREAD

**Issue by ravi590** [handsontable/handsontable#3613]
Hi @AMBudnik , I am adding comments in the following way
/****************************/
hot = new Handsontable(containerRef, hotOptionsConfig);
var ajaxData = hot.getAjaxData();
		  for(var d=0, lent = ajaxData.length; d<lent; d++ ){
			  if( (ajaxData[d].errorComments != undefined) && (ajaxData[d].errorComments != null)) {
				  hot.getCellMeta(d,0).comment = ajaxData[d].errorComments;
			  }
		  }
		  hot.render();

/***************************/

After hot.render() the comments are getting disappeared.
While debugging, found that hot.render() is fine, but handsontable is calling internally another function ("enableObserveChanges" in handsontable.min.js) which is making the issue.

Can you help me on this?

Thanks,
Ravi

**Comment by AMBudnik** [comment]
Can you use the updateSettings to load comments, like in this example? http://jsfiddle.net/0vsf25ah/ there you can also add the `if`statement for error checking.

**Comment by ravi590** [comment]
Hi @AMBudnik , Can i use it for updating the comments dynamically to the cell like the way i specified above?,

Other than "afterInit" event Is there any event in handsontable so that it will be triggered as the last event after the handsontable is completely loaded?

**Comment by AMBudnik** [comment]
I would need to see your code but as far as I understand you can use it.
