### ISSUE TITLE
Hot-in-hot cell type is covering too much space

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3614]
Handsontable-in-Handsontable when expanded it covers all the available space to the right and bottom of the table. It results in lack of possibility to close the editor by clicking below (or on the right) to the opened table.

**Steps to reproduce the problem:**
1. Go to http://jsfiddle.net/76x455ve/
2. Open A1 editor
3. Click anywhere to the right or bottom of the opened table to close it

Result: you can't close the editor.

![cantclick](https://cloud.githubusercontent.com/assets/8048526/16416131/16259d2a-3d41-11e6-89a1-2b65cd441fe0.jpg)

:information_source:

> Handsontable - 0.26.0
> Windows 8.1
> Chrome

**Comment by AMBudnik** [comment]
The behavior in version 0.35.0/PRO 1.15.0 remained the same.
Here's an updated demo http://jsfiddle.net/r3zqcftx/

**Comment by AMBudnik** [comment]
I've mentioned the same subject here https://github.com/handsontable/handsontable/issues/6605 

Before (when Krzysztof made the post) and now we're also not able to close the table once a user clicks `2014` and `blue`.

Updated demo to `7.3.0` https://jsfiddle.net/5tcyhje9/

**Comment by swistach** [comment]
Solution should help also for `autocompleteEditor` and `dropdownEditor`. We should use #3758 as a test case.

**Comment by krzysztofspilka** [comment]
Won't be fixed.
