### ISSUE TITLE
Can't delete data from a column with mixed data types

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3615]
I can't wipe out data from a certain column when there is a checkbox among other data types.

**Steps to reproduce the problem:**

1. Go to http://jsfiddle.net/f9c1a7xs/
2. Select column A
3. Use <kbd>Backspace</kbd> or <kbd>Delete</kbd> to remove the data

Result: only a checkbox is being unchecked.

:information_source:
> Handsontable 0.26.0
> Windows 8.1
> Chrome

**Comment by swistach** [comment]
It works since version: 0.26.0
Demo: http://jsfiddle.net/f9c1a7xs/1/
