### ISSUE TITLE
Removing data in the checkbox-type column throws an exception

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3616]
I created a simple table with relatively large number of rows and last column containing checkboxes only. Then tried to remove the data from the last column and got an exception:

> Uncaught TypeError: Cannot read property 'querySelectorAll' of null

**Steps to reproduce the problem:**

1. Go to http://jsfiddle.net/ymyqgz45/1/
2. Select last column "Available" by clicking in its header
3. Press <kbd>Backspace</kbd> or <kbd>Delete</kbd> or <kbd>Enter</kbd> or <kbd>Space</kbd>

Result: an exception being thrown

:information_source:
> Handsontable 0.26.0
> Windows 8.1
> Chrome

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/3554

**Comment by AMBudnik** [comment]
and if we reduce the amount of rows (like: http://jsfiddle.net/zndv2wb4/) we can see that this issue is strongly related (or the same as) https://github.com/handsontable/handsontable/issues/3138
