### ISSUE TITLE
How to hide column when column headers are defined

### ISSUE THREAD

**Issue by pkacha** [handsontable/handsontable#362]
Hi All,

I am trying to find a a solution, can anyone please help me. I have created a jsFiddle at http://jsfiddle.net/warpech/hU6Kz/. 

1) Currently when i try to hide the columns only the data in the columns get hidden not the header of the columns. Please refer to the image for current functionality

![hidden_columns](https://f.cloud.github.com/assets/3293643/74099/d69a9a58-607a-11e2-9921-8d7c882bfe30.gif)

I want to hide first column i.e."id" along with header and third column i.e. "Last Name" with header. Please refer to the below image as to what i want to achieve.

![hidden_columns_expected](https://f.cloud.github.com/assets/3293643/74121/bd1aa5a4-607b-11e2-9937-d3329bd1c2ae.gif)

2) When i click a button or link the two above hidden columns should be visible so the grid appears same as in jsFiddle at http://jsfiddle.net/warpech/hU6Kz/.  

Please advice / suggest solution for the same

**Comment by dsignr** [comment]
This bug still exists and this feature is still missing :'( The only workarounds are mentioned by @groc426 and I don't think they are confidence inspiring. Any updates on this yet? 

Thanks for an otherwise excellent library!

**Comment by AMBudnik** [comment]
Hi @dsignr 
Can you share information on how you would like to hide you columns? Currently we added a new hiding feature, you can check it here https://docs.handsontable.com/pro/1.5.0/demo-hiding-columns.html

**Comment by dsignr** [comment]
@AMBudnik Thanks for the info, is this feature available only to the pro version?
Thanks for the fast response 👍

**Comment by AMBudnik** [comment]
yes @dsignr it's only in the PRO version.

**Comment by cahumada** [comment]
I could hide it with:
`$('td:nth-child(1),th:nth-child(1)').addClass('hidden');
$('col:nth-child(1),col:nth-child(1)').addClass('hidden');`
In the event after the data load.
Thks
