### ISSUE TITLE
NumeralJS remove

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3620]
After switching from NumeralJS to NumbroJS (https://github.com/handsontable/handsontable/issues/3487) NumeralJS still exists in the source code. It needs to be removed from `lib/` directory.

**Comment by AMBudnik** [comment]
related: #2863

**Comment by budnix** [comment]
To test this commit https://github.com/handsontable/handsontable/commit/bac97a775718ee9fb93b0e99c6ea567beae4d551 please update `hot-builder` to `^0.5.2`.
