### ISSUE TITLE
Performance issue when multiple instances per page are used

### ISSUE THREAD

**Issue by harunurhan** [handsontable/handsontable#3621]
I have a single page where I have 10 instances of hot-table, all of them have 3-7 columns and 5-12 rows. Unfortunately page and cell editing becomes slow.

Do you have any idea how to optimize handsontable for this usecase?

**Comment by AMBudnik** [comment]
Hi @harunurhan 
Have you already checked our performance tips: https://docs.handsontable.com/pro/1.5.0/tutorial-performance-tips.html?

ps. please create a demo where we can test this case.

**Comment by AMBudnik** [comment]
Issue closed in lack of Author's reply and needed demo.

**Comment by nadim** [comment]
The link above is 404ing. What's the 2019 version of this guide?

**Comment by AMBudnik** [comment]
Hey @nadim 

Here's a demo that you can test https://jsfiddle.net/L2s4q5eg/
you can change `(1000, 1000)` to any `row` /column` numeric values. (line 3)
src: https://handsontable.com/docs/6.2.2/demo-scrolling.html

And a performance guide https://handsontable.com/docs/6.2.2/tutorial-performance-tips.html
