### ISSUE TITLE
afterChange is not working at all!

### ISSUE THREAD

**Issue by mhhg** [handsontable/handsontable#3622]
hot.addHook('afterChange', function () {
            func();
        });
        func = function () {
            hot.setDataAtCell(0, 0, 'new value');
            $('#variable-view').handsontable('setDataAtCell', 0, 0, 'new data');
            hot.updateSettings({
                colHeaders: ['header'],
            });
        };
nothing in func function works at all. why?

**Comment by AMBudnik** [comment]
Hi @mhhg 
Here's an example: http://jsfiddle.net/a5cb9tha/1/
I deleted the `setDataAtCell` method it triggers the `afterChange` callbacks again and again for his code.

**Comment by mhhg** [comment]
sorry its working, my fault was the object, but it fall into a loop, i can stop the loop
        afterChange = false;
        variableView.addHook('afterChange', function ( ) {
            console.log("afterChange is called");
            if (!afterChange) {
                variableView.setDataAtCell(0, 0, 'new value');
            }
        });
