### ISSUE TITLE
IE: Object doesn't support property or method 'blur'

### ISSUE THREAD

**Issue by tstar** [handsontable/handsontable#3623]
In IE 11, when clicking from one cell to another, we can get error "Object doesn't support property or method 'blur'" in file "handsontable.full.js" on line 9079 in code:

```
if (this.instance.view.isMouseDown() && document.activeElement && document.activeElement !== document.body) {
  document.activeElement.blur();
} else if (!document.activeElement) {
  document.body.focus();
}
```

or in line 9074 in demo page with checked "Headers" and "Fixed rows/columns" options.

**Comment by AMBudnik** [comment]
Hi @tstar 
How can I replicate the error?
I'm using numeric demo: https://docs.handsontable.com/pro/1.5.0/demo-numeric.html in IE 11 for Win8.

**Comment by tstar** [comment]
I can not make a special demo. I went to the page of examples [https://handsontable.com/examples.html?headers&fixed](https://handsontable.com/examples.html?headers&fixed) in IE 114 debug mode and began clicking and double clicking the cells. The error occurs after a few clicks. I made a screenshot of the error [http://prntscr.com/bn7ibp](http://prntscr.com/bn7ibp)
Try to set/remove the checkboxes in "Popular basic features", after this error occurs even after the first click.

**Comment by AMBudnik** [comment]
Thank you @tstar 
I couldn't replicate it with the examples but when I got to the [checkbox example](http://jsfiddle.net/hvLatc73/) and double-click one of the checkboxes I got the same issue

![bug-ie11](https://cloud.githubusercontent.com/assets/10757813/16518312/75f831ca-3f82-11e6-87ef-471d32514db1.png)

**Comment by AMBudnik** [comment]
Can this issue be related https://forum.handsontable.com/t/javascript-runtime-error-in-internet-explorer/476/2?

**Comment by tstar** [comment]
I'm not sure it's the same problem. Here there is a completely different error.
SCRIPT606: Could not complete the operation due to error 800a025e.
File: handsontable.full.min.js, Line: 257, Column: 15198
See screenshot http://prntscr.com/brfrlp

**Comment by swistach** [comment]
That error occurs when HOT is running into iframe.
More about it [here](https://www.tjvantoll.com/2013/08/30/bugs-with-document-activeelement-in-internet-explorer/).

**Comment by jakefreeberg** [comment]
👍

**Comment by AMBudnik** [comment]
@tstar 
Can you check if none of the above issues exist in 0.29.0?

Thanks in advance!

**Comment by AMBudnik** [comment]
I'm closing this issue but if there's anything we're missing here please leave a comment.

**Comment by cgatesman** [comment]
I am seeing the following error in IE11 with 0.29.0:

```
SCRIPT5007: Unable to get property 'nodeName' of undefined or null reference
File: handsontable-0.29.0.full.js, Line: 7652, Column: 3
```

I believe this is a problem that it needs to test if `document.activeElement` exists before:

```javascript
  var ieIframeDocument = document.activeElement.nodeName === void 0;
```

**Comment by AMBudnik** [comment]
Hi @cgatesman can you replicate the same behavior in JSFiddle?

**Comment by cgatesman** [comment]
That's not going to be very easy for me as I work and develop on MacOS.  I was reported this issue with our Handsontable implementations from our QA team after upgrading to the latest version of Handsontable.

I don't think a JSFiddle is really necessary.  To me, it seems common sense that you need to check for the existence of `document.activeElement` before you can attempt to look at `document.activeElement.nodeName`.

**Comment by swistach** [comment]
Hi @cgatesman, you're right. We should fix it in the next release.
Thank you @cgatesman!
