### ISSUE TITLE
How to get currently edited cell, row and col index?

### ISSUE THREAD

**Issue by mhhg** [handsontable/handsontable#3624]

**Comment by AMBudnik** [comment]
you can use access `beforeChange` hook like this http://jsfiddle.net/zsr3uw9a/ 

I don't know what you would like to do next or when you what to access this element but the `beforeChange` hook is the one to pick if you ask me.

**Comment by mhhg** [comment]
Thanks a lot it's working fine now, but i have an other question.
why afterChange if not working when it's defined inside the hot object?
it works fine when it's defined as a hook

it works fine

        variableView.addHook('afterChange', function (a, b, c) {

        }  


it log an error

    var variableView = new Handsontable(container, {
     afterChange: function() {

      }

**Comment by AMBudnik** [comment]
Hi @mhhg 
I should work in both cases - my example above works inside the the Handsontable instance settings.
You need to remember that the `afterChange` takes 2 arguments: source and changes ([docs](https://docs.handsontable.com/pro/1.5.0/Hooks.html#event:afterChange))

**Comment by mhhg** [comment]
Thanks a lot AMBudnik

i have another question again!!!

how to avoid sticking the spreadsheet to the top of page?
i have a spreadsheet which it has height and width full page, i want to have a menu at top of it, at top of the page, i mean. i set margin-top or top in CSS to have a bit of margin there, but when i scroll down, spreadsheet comes up and stick to the top of page. how to avoid this?

Thanks.

**Comment by AMBudnik** [comment]
Hey @mhhg 
It's not an easy task currently. Here's an example that may be helpful http://jsfiddle.net/553rdh40/1/

**Comment by mhhg** [comment]
is it possible to do this on the left side instead of top?

**Comment by AMBudnik** [comment]
Yes, I think that it's even working better in this configuration: http://jsfiddle.net/5z8svjqk/

**Comment by mhhg** [comment]
i got that, it works on afterChange too. thanks.

**Comment by AMBudnik** [comment]
Great. Thanks for update.
