### ISSUE TITLE
Adding support in 'manualRowMove' for moving group of the consecutive rows

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3626]
It's new feature, which adds support for moving the rows group.

Thanks @jansiegel 👍 
The to-do list has been moved here. Now progress bar is available on issues list :)

Refactor should contain:
- [x] Ability to move multiple, consecutive rows

New moving UI:
- [x] Different mouse cursor
- [x] Ability to start dragging anywhere in the row headers
- [x] Snapping guide-line (while moving)
- [x] A larger guide representing the moved rows (while moving)

**Comment by jansiegel** [comment]
Refactor should contain:

- [ ] Ability to move multiple, consecutive rows

New moving UI:
- [ ] Different mouse cursor
- [ ] Ability to start dragging anywhere in the row headers
- [ ] Snapping guide-line (while moving)
- [ ] A larger guide representing the moved rows (while moving)
