### ISSUE TITLE
Performance issue when changing multiple checkboxes 

### ISSUE THREAD

**Issue by viqtor1** [handsontable/handsontable#3628]
Hello

I noticed that there is a significant delay when changing multiple cells with the type checkbox, by selecting them and pressing either Space, Enter, or Backspace. This can be tested [here](http://jsfiddle.net/viqtor91/tc94zkg4/). This is only valid for checkboxes, if I change the type of the cells to text, you can edit them much faster.
Does anybody has any idea why is it this way?

**Comment by AMBudnik** [comment]
Can you share your OS/Browser settings @viqtor1 
It works as expected for me - maybe I'm doing something wrong. You select them each one by one and this actions is lacking performance?

**Comment by viqtor1** [comment]
@AMBudnik 
OS: Windows 8.1, Browser: Chrome Version 51.0.2704.106 m (64-bit), IE v11.09, Firefox v47.
When selecting one by one, they work fine, there is no lag.
But when I select more than one, something like 5x5 cells, and press Space, Enter, or Backspace, I have to wait for quite a while to see the effect.

**Comment by AMBudnik** [comment]
OK,

I can see what you mean @viqtor1 
thank for sharing

![example](https://cloud.githubusercontent.com/assets/10757813/16558595/f0a01922-41e6-11e6-96a5-e2d74cbd1bb4.gif)

**Comment by swistach** [comment]
Hi @viqtor1,
This issue was fixed in #3881 (0.31.0+ / 1.10.0+). If it doesn't work as you expected, feel free to send your comment here.
