### ISSUE TITLE
Incorrect header height

### ISSUE THREAD

**Issue by tstar** [handsontable/handsontable#3629]
In "Headers" demo [https://handsontable.com/examples.html?headers](https://handsontable.com/examples.html?headers) you can see incorrect header height. This is best seen in the screenshot [http://prntscr.com/bolsyx](http://prntscr.com/bolsyx). In the green zone, we have a "dead zone" in which we can not select the cell. It is also very strange seems very large "wtHolder" div height [http://prntscr.com/bolwdt](http://prntscr.com/bolwdt).

**Comment by AMBudnik** [comment]
Thanks for sharing @tstar 
That's right - we cannot select a cell when the cursor is in the 'green zone'.

**Comment by AMBudnik** [comment]
Still replicable in version 0.31.0

**Comment by wojciechczerniak** [comment]
![Screenshot 2020-09-08 at 13 05 26](https://user-images.githubusercontent.com/4718998/92468764-fb9d3980-f1d3-11ea-8ca9-03eef731630a.png)

Fixed in v8. Green (padding) is no longer there
