### ISSUE TITLE
Wider dropdown when using autocomplete

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3630]
Is it possible to force the dropdown to show the full text of its content? 
Or to set up a with for an autocomplete for each column? 

![bbb](https://cloud.githubusercontent.com/assets/1706326/16560549/227970e2-41ec-11e6-89dd-84a324e82416.png)

**Comment by AMBudnik** [comment]
Hi @alvarotrigo 
Unfortunately this issue was already marked as a change suggestion at https://github.com/handsontable/handsontable/issues/1255
Please follow https://github.com/handsontable/handsontable/issues/1255 for updates and if you would like to add a comments there please feel free to do so.

**Comment by alvarotrigo** [comment]
+1
