### ISSUE TITLE
Conditional column source

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3632]
Not quite sure if this is possible at the moment.

I have a column with autocomplete. I would like this column to show a different list depending on the value of another column. 

The column is currently returned by an ajax call:

```javascript
{
    data: 'location',
    type: 'autocomplete',
    source: function(query, process) {
        $.ajax({
            url: HOST_URL + "/tables/getLocations.json",
            data: { query: query },
            type: "POST",
            success: function(response) {
                process(response['result']);
            }
        });
    },
    strict: false,
    allowInvalid: true,
    editor: handGlobals.LoggingEditor,
},
```

So basically I need a way to change the `source` or to add logic regarding rows and columns within the `source` property.

It seems to be related with https://github.com/handsontable/handsontable/issues/1500 but no solution was provided there.

**Comment by AMBudnik** [comment]
Hi @alvarotrigo 
Recently we added a post blog that provides examples on how to set dependencies between cells - there's also an example with the dropdown - https://handsontable.com/blog/articles/expand-your-app-with-cell-dependencies. Hope it helps.

**Comment by alvarotrigo** [comment]
Thanks for the answer, but the blog post doesn't deal with a change in the `source` data but keeps the same source and just uses `setDataAtRowProp` to set a different one depending on another cell.

I do not need to set any specific value, I need to set the `source` of the possible values from where the user can choose from.

**Comment by alvarotrigo** [comment]
@AMBudnik would you say it is possible to do what I'm looking for?

**Comment by AMBudnik** [comment]
I'm afraid it's not @alvarotrigo 
I tried to do it like this: https://jsfiddle.net/7m293etL/ but i get a Handsontable issue.

**Comment by budnix** [comment]
I've modified demo made by @AMBudnik at https://jsfiddle.net/7m293etL/1/. My fix shows how to achieve different dropdown values based on another column value.

**Comment by alvarotrigo** [comment]
@AMBudnik, @budnix thanks for that!
@budnix I [modified your fiddle](https://jsfiddle.net/7m293etL/4/) as the returning value for the year is not a `number` but a `string` and therefore the `===` didn't match. 

In any case, what's the `cb` function you are using? What does it do ?

**Comment by budnix** [comment]
`cb` as a shortcut of `callback`. You can see description [here](http://docs.handsontable.com/pro/1.5.0/Options.html#source).

**Comment by alvarotrigo** [comment]
@budnix is it the same as the `process` I have in my question script?

**Comment by budnix** [comment]
Yes, it's the same argument but in different name :)

**Comment by alvarotrigo** [comment]
Thanks for everything! I'll close the issue then.

**Comment by alvarotrigo** [comment]
@budnix just realized the stupidity o my last question :D Didn't see `cb` or `process` are just function parameters :)
