### ISSUE TITLE
The strange behavior after cell cleaning

### ISSUE THREAD

**Issue by tstar** [handsontable/handsontable#3633]
Open main demo [https://handsontable.com/examples.html?headers](https://handsontable.com/examples.html?headers), 

select any cell in "ID" row, 
press "Delete" key - cell is cleared, 
press "Enter" key - the old value again in the cell, but the expected result was an empty cell in edit mode. 

This does not happen when you double-clicked. 
This does not occur at "ID", "Country", "Code", "Currency", "Units" cells, but it occurs on cells "Level", "Date", "Change".

**Comment by AMBudnik** [comment]
thanks for sharing @tstar 
This issue occurs in the free version as well.

Demo:http://jsfiddle.net/fjom301a/
Tested on: Win8/Chrome 51
HOT version: 0.26.0 and PRO 1.5.1

**Comment by tstar** [comment]
This occurs not only with numeric cell type, but also with date cell type from this demo. This error I see in my custom editor that inherited from BaseEditor.

**Comment by AMBudnik** [comment]
they share the same rending options and I think that it this will be fixed for numbers it will also work for date cell type. 

I can be wrong but we will test it - thanks for additional information @tstar

**Comment by AMBudnik** [comment]
Hi @tstar I tried to replicate it in v0.30.1 and it seems like it works now.
Can you test it. Maybe there's something that I'm missing.

**Comment by AMBudnik** [comment]
I guess that we can close this issue as there are no additional questions.
