### ISSUE TITLE
The editor can fly above the scroll bar

### ISSUE THREAD

**Issue by tstar** [handsontable/handsontable#3634]
Hi,
open demo from [https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable](https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable), select cell in row 1, column "T" in edit mode in the first table, easy scroll to left. As a result, you will see that the editor is over the scroll bar. It looks ugly. Also, if you reduce the browser window, the scroll bars appear double in the demonstration. See my screenshot [http://prntscr.com/bozj4f](http://prntscr.com/bozj4f).

**Comment by tstar** [comment]
It is observed on the latest version of IE, Chrome, Firefox on windows 7 x64. You really turned the cell into edit mode? Problems in that the editor layer "handsontableInputHolder" is in "parentContainer" after "ht_master handsontable, but I think, it should be in ht_master -> wtHolder.

**Comment by AMBudnik** [comment]
Ok. I can see what you mean. I replicated this issue.
Thanks for sharing @tstar and for your recent activity
![example](https://cloud.githubusercontent.com/assets/10757813/16589231/845ba3c0-42d2-11e6-91d2-36d68e61a5b2.gif)

**Comment by AMBudnik** [comment]
Still replicable in v0.30.1

**Comment by AMBudnik** [comment]
The same issue has been reported at https://github.com/handsontable/handsontable/issues/4832
