### ISSUE TITLE
backgroundcolor header column

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#3635]
hello,
i search a way to change the header background color of one column.
i try with http://jsfiddle.net/ct6r42gv/ but the render become slower
any help would be appreciate
best regards
jeanmarc

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 
Here's a great demo that one of our developers have made: http://codepen.io/js-ziggle/pen/pjpNWZ It will definitely come in handy

**Comment by jeanmarc78** [comment]
ok , it works .
thanks a lot

**Comment by AMBudnik** [comment]
you're welcome
