### ISSUE TITLE
Object doesn't support property or method 'handsontable' in IE

### ISSUE THREAD

**Issue by jorseijo** [handsontable/handsontable#3636]
Hello,
I just deployed version 0.26.0 and I'm getting the error "Object doesn't support property or method 'handsontable'" in IE. Specifically, it breaks in the line where I create the grid:

`$("#gridItems").handsontable({
...
});`

When I open the Developer tools of IE (F12) and I change to IE9+, everything works fine, but it comes back to compatibility mode when I close it. Any ideas? How do you disable quirks mode in IE?

Thanks,
J

**Comment by AMBudnik** [comment]
Hi @jorseijo 
Can you replicate the same error in the JSFiddle?

**Comment by jorseijo** [comment]
That's going to be hard because the script file is huge. 
In any case the problem I have is that I used version 0.11.4, which is the last one that supports IE8 and 9, and I started using the latest version. So now when I use IE (in my case IE11), somehow it still goes in compatibility mode with IE8 and therefore it doesn't render the grid.

**Comment by AMBudnik** [comment]
You do not need to share all the code. You can include only your static data (numbers, checkboxes, dropdowns etc.). Skip all the back-end side connections, validators etc.

**Comment by AMBudnik** [comment]
Issue will stay closed until we get a demo or any other response.
