### ISSUE TITLE
Refactoring of the columnSorting plugin

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3637]
Refactoring should contain:
- [ ] exclusion of the observeChanges manipulation from the plugin level
- [ ] exclusion of the plugin methods from the instance of Handsontable
- [ ] arrayMapper inside the plugin
- [ ] sorting by defined rows ranges
- [ ] properly sorting of the datatype 'date'
- [ ] properly work of the disablePlugin method
- [ ] transfer sortFunction and sortIndicator into 'column' properties

**Comment by wojciechczerniak** [comment]
This issue is outdated. We've refactored sorting some time ago.
