### ISSUE TITLE
nestedHeaders misalign when scrolling

### ISSUE THREAD

**Issue by wkuehler** [handsontable/handsontable#3638]
Scrolling to the right on wide tables seems to result in the top level nested headers becoming misaligned.  If you look in this simple [jsfiddle](http://jsfiddle.net/wkuehler/phnfnfca/) example, scroll all the way to the right then click on the top level header labeled '8'.  Notice that the header itself is shifted somewhat from the cells that are highlighted.

![nestedheader issue](https://cloud.githubusercontent.com/assets/1509672/16633109/a5d256de-4395-11e6-9b7b-0b9ffcd9903a.png)

**Comment by toms-dev** [comment]
+1 i'm running into the same issue. Look at the column DefaultName_6
![bug-step1](https://cloud.githubusercontent.com/assets/2982905/16651891/2422a01e-4447-11e6-8b63-1544ae88df4d.png)

Then after scrolling horizontally:
![bug-step2](https://cloud.githubusercontent.com/assets/2982905/16651895/2ce33434-4447-11e6-9af4-46e7dda4b649.png)

The column is offset after the *render* event is triggered. The issue might be caused by the offscreen rendering.

**Comment by AMBudnik** [comment]
I think that's a rendering issue. Can you try to add a [`viewportColumnRenderingOffset](https://docs.handsontable.com/pro/1.5.0/Options.html#viewportColumnRenderingOffset)` option to your grid settings?

**Comment by toms-dev** [comment]
Getting the same issue with *viewportColumnRenderingOffset: 100*
Now, the problem only shows up when the columns after 100 are being rendered ;)
![bug-stillhere](https://cloud.githubusercontent.com/assets/2982905/16652419/d6cb2d14-444a-11e6-8a1a-e1efb06c9a51.png)

**Comment by AMBudnik** [comment]
so I guess that we're on the right track Tom.
Thanks for your prompt reply.
I'll mark this issue as a bug.

**Comment by wkuehler** [comment]
viewportColumnRenderingOffset seems to work for me as we know the max number of columns that can be displayed at any one time.  That said, are there any negatives to this solution if we have 20 columns but our viewportColumnRenderingOffset is set to 200?

**Comment by AMBudnik** [comment]
That's a good question @wkuehler 
I think that the best way would be to check how long it takes to run it via timeline tab in the Chrome Dev tools.
It surely works as expected and doesn't produce any additional issues or console logs when your `viewportColumnRenderingOffsetNumber` is greater than the actual number of columns.

**Comment by toms-dev** [comment]
@wkuehler depending on the number of columns, we might not be able to afford the computation of all the columns! This workaround is only valid for "small" tables ;)

**Comment by AMBudnik** [comment]
that's unfortunately right @wkuehler 
That's why I've marked this issue as a bug. It's always better to find a solution than a workaround.

**Comment by toms-dev** [comment]
Any news about this issue ?

**Comment by AMBudnik** [comment]
Hi @wkuehler @toms-dev we've made some changes in 1.6.0 that removed the unwanted behavior. Here's na updated demo: http://jsfiddle.net/pfbtogjt/ Can you please confirm?
