### ISSUE TITLE
Summary Calculations and Column Sorting

### ISSUE THREAD

**Issue by wkuehler** [handsontable/handsontable#3639]
Summary calculations do not behave as expected when using column sorting.

Behavior 1:  Before even clicking on a column header to sort, sum seems to act strangely.  In the example fiddle, look at column F where the sum is showing as 36 instead of 9.

Behavior 2:  After clicking sort, the summary calculations row is sorted with everything else and does not remain at the bottom.

[Example](http://jsfiddle.net/wkuehler/b1ws44hf/)

**Comment by AMBudnik** [comment]
Thanks for sharing @wkuehler 
I think that it's related to this issue https://github.com/handsontable/handsontable/issues/3600

**Comment by wkuehler** [comment]
Agreed.  Sorry I missed that; when i searched i used the term 'summary calculation' (with a space).

**Comment by AMBudnik** [comment]
I am closing this issue. We will stick to https://github.com/handsontable/handsontable/issues/3600 and check this issue while testing solution.
