### ISSUE TITLE
Need insert row/column hooks

### ISSUE THREAD

**Issue by xfight0** [handsontable/handsontable#3640]
Hello developers: 
Is there a hook for insert row or column(in context menu: left column, right row column).
like below
```
afterInsertRow()
afterInsertColumn()
```

What should I do if I want to do something after inserting row or column

**Comment by AMBudnik** [comment]
Hi @xfight0 
There are [`afterCreateRow`](https://docs.handsontable.com/pro/1.5.0/Hooks.html#event:afterCreateRow) and [`afterCreateCol`](https://docs.handsontable.com/pro/1.5.0/Hooks.html#event:afterCreateCol)

**Comment by xfight0** [comment]
@AMBudnik  thank you buddy

**Comment by AMBudnik** [comment]
you're welcome @xfight0
