### ISSUE TITLE
columnSorting on 'text' columns

### ISSUE THREAD

**Issue by timberswrx** [handsontable/handsontable#3644]
When using column sorting on text columns everything javascript thinks is a number gets sorted to the top of the column. A text column should treat everything as text, as it does in Excel. I have a column of part numbers in a text column. Some of the part numbers such as 45E2775 get seen by the sorting algorithm as a number, and moved to the top of the column ahead of other part numbers such as 00AR056. My users were very confused, since Excel sorts the column correctly as text. I modified my copy of 0.26.0's defaultSort by commenting out the checks of isNaN and it corrects the issue. Is there some reason to check for numbers when sorting a text column?

**Comment by AMBudnik** [comment]
Hi @timberswrx 
can you provide an example of expected and actual sorting? (it can be only a 5th elements table).

**Comment by timberswrx** [comment]
Here is a column of part numbers after sorting by handsontable. You'll see that all the 45E items are moved to the top because they are recognized as numbers. They shouldn't be treated as numbers but as text since this is a text column. If you sort this same row in Excel all the 00AR items are before the 
45E items as you would expect.

45E0071
45E2114
45E3349
45E3673
45E6178
45E6809
45E6809
45E6809
45E8707
45E9335
45E9335
00AR032
00AR323
00AR323
00AR323
00AR327
00AR327
00AR331
00AR331

**Comment by AMBudnik** [comment]
hm... when I wanted to check how it's working in the Excel I got "4,5E+72" instead of "45E0071" but besides that... when we declare those options as `numeric` we got all the values starting with 45e as infinity so only way to sort them is to mark them as a `text` cell type like here: http://jsfiddle.net/g5g33t97/ but I can agree that `0` should be before `4` in this situation.

**Comment by timberswrx** [comment]
Yes, my column is set to text but I get the results as shown above. As I said in the first post, I've fixed the issue in my copy by modifying the defaultSort method in the columnSorting plugin.

Thanks for taking the time to look at this.

**Comment by AMBudnik** [comment]
Updated demo v0.35.0: http://jsfiddle.net/at88yd0j/
