### ISSUE TITLE
Memory Leak in TouchScroll.onAfterUpdateSettings method

### ISSUE THREAD

**Issue by baac0** [handsontable/handsontable#3646]
In our application we repeatedly call HOT's _updateSettings_ method which in turn causes method _onAfterUpdateSettings_ in class _TouchScroll_ to be called.
In there, a callback function is added to the '_afterRender_' hook; obviously, it's intended to add this callback only once per instance (hence the use of _addHookOnce_), however since a new callback is created for each invocation of _onAfterUpdateSettings_ this does not work. 
As a consequence, the '_afterRender_' hook becomes populated with obsolete callback instances causing a memory leak.

**Proposed solution:**
Take care to create only one callback function instance per _TouchScroll_ instance which gets registered to the '_afterRender_' hook. 

Regards
Achim

**Comment by AMBudnik** [comment]
Thanks for sharing @baac0

**Comment by AMBudnik** [comment]
Hi @baac0 
Can you check if you still experience memory leaking after updating to 0.31.0?
Thanks in advance!

**Comment by baac0** [comment]
Looks good now. Thanks a lot!

**Comment by AMBudnik** [comment]
Great! Thanks for a prompt replay.
