### ISSUE TITLE
Various resize & move (eg, manualColumnResize, manualColumnMove) options don't work inside a twitter bootstrap modal

### ISSUE THREAD

**Issue by jsomara** [handsontable/handsontable#3647]
Various resize & move (eg, manualColumnResize, manualColumnMove, manualRowResize, manualRowMove) options don't work inside a Twitter Bootstrap 3 modal.

I have a JSFiddle that should explain everything. It's reproducible every time, and it doesn't seem to matter if you update the settings after the modal is created, or on original table instantiation

https://jsfiddle.net/ech07yfe/2/

The table outside the modal has the correct functionality (columns can be moved and resized), whereas the table inside the modal does not. Most other table behaviors appear to act normally. No errors make it to the console.

**Comment by AMBudnik** [comment]
Thanks for sharing @jsomara 
I can see that the move handlers are not well positioned

![table](https://cloud.githubusercontent.com/assets/10757813/16724175/b2d53e4a-4751-11e6-9f97-f73bf59e9382.png)

**Comment by rodolfosouza** [comment]
the same issue, any update?

**Comment by AMBudnik** [comment]
Hi @rodolfosouza 
unfortunately not yet.
Please check our Roadmap if you would like to track our work: https://trello.com/b/PztR4hpj/handsontable-roadmap-2016-login-to-vote-for-features

**Comment by ngoclinh15994** [comment]
any update for this issue ?

**Comment by AMBudnik** [comment]
Hi @ngoclinh15994 

Sorry to say but we do not have this issue scheduled for Q2, 2017.

**Comment by AMBudnik** [comment]
It looks like the https://github.com/handsontable/handsontable/issues/2937 report is made to describe the same issue so please track https://github.com/handsontable/handsontable/issues/2937 for updates

**Comment by AMBudnik** [comment]
@jsomara @ngoclinh15994 @rodolfosouza 

we've just published Handsontable v `7.0.0` were we fix a referred issue https://github.com/handsontable/handsontable/issues/5050
Please update and let me know if it works for you.
