### ISSUE TITLE
Backbone.Js not updating when using render()

### ISSUE THREAD

**Issue by Lunat1q** [handsontable/handsontable#3649]
Greetings, i have next code:
` hot = new Handsontable(container, {

```
    data: getData(),
    dataSchema: makeData,
    rowHeaders: true,
    colHeaders: true,
    readOnly: true,
    fillHandle: false,
    manualColumnResize: true,
    manualRowResize: true,
    autoWrapRow: true,
    stretchH: 'all',
    contextMenu: true,

    columns: [
        attr('Procedure'),
        attr('Num'),
        attr('Name'),
    ],

    colWidths: [50, 25, 25],

    colHeaders: [
        'Col1',
        'Col2',
        'Col3'
    ],

    beforeRemoveRow: function (index, amount) {

        var ids = new Array();
        for (var i = index; i < index + amount; i++) {
            ids.push(hotData.models[i].attributes.Id);
            console.log('Removing id: ' + hotData.models[i].attributes.Id);

        }

        deleteRow(ids);

    },

});
```

`

as u can see i have data binded for handsontable
and i have Ajax success code:
`hotData= new DataCollection();

```
            for (var i = 0; i < jsondata.data.length; i++) {
                hotData.add(jsondata.data[i]);
            }  

            hot.render();`
```

but on hot.render() - nothing happend. If i put initial data to hotData - it works, but all changes, reloading - doesn't

**Comment by AMBudnik** [comment]
thanks for sharing @Lunat1q

**Comment by Lunat1q** [comment]
Update: if i user loadData() method - it loadup new data, but render() still not working.

**Comment by AMBudnik** [comment]
We officially dropped support for Backbone.

**Comment by jperasmus** [comment]
Hi @AMBudnik, can you please tell me which version of HOT was the last to support Backbone? Not finding it anywhere yet.

**Comment by AMBudnik** [comment]
Hi @jperasmus 
here's a demo http://past.handsontable.com/demo/backbone.html it started from `0.8.14` but it has never been fully supported so we have deleted it from our docs.
