### ISSUE TITLE
Scrolling - row headers not aligned and custom renderers not executed

### ISSUE THREAD

**Issue by T1KK3S** [handsontable/handsontable#3650]
So I'm having a set of date ~150 rows (will grow still) in my Handsontable but when I scroll, from line 120-ish the row headers get messed up and not aligned anymore.
Also my custom renderer which changes the color of a cell do not get executed anymore.

Code:

`this.rte = new Handsontable(document.getElementById('ExportCustomerOrderDataTable'), {
                data: tableData,
                rowHeaders: true,
                colHeaders: self.state.colHeaders,
                afterGetColHeader: function (col, TH) {
                    var that = this;
                    if (["Period", "--"]
                        .filter(function (b) {
                            return b == that.getColHeader(col);
                        }).length == 0) {
                        TH.classList.add('disableFilter');
                    }
                },
                columns: [
                    {
                        data: 'workingCalendarId',
                        readonly: true
                    },
                    {
                        data: 'periodName',
                        readonly: true
                    },
                    {
                        data: 'date',
                        readonly: true
                    },
                    {
                        data: 'isWorking',
                        readonly: true
                    }
                ],
                hiddenColumns: {
                    columns: [0],
                    indicators: false
                },
                cells: function (row, col, prop) {
                    if (prop == 'isWorking') {
                        var cellProperties = {
                            renderer: isWorking
                        }
                        return cellProperties;
                    }
                },
                filters: true,
                dropdownMenu: ['filter_by_value', 'filter_action_bar'],
                afterUpdateSettings: function () {
                    self.renderTable();
                },
                afterChange: self.onChange
            });
            self.renderTable();
        }`

self is a declared "this".
Also, I am using ReactJs together with Handsontable.
Note that this does work correctly when setting the option **renderAllRows** but this is a workaround and gives me some lag on the DOM and is also not what I want to do since HandsOnTable is designed to not need that in the first place I suppose.

As a sidenote, I can scroll the row headers separately so it seems that they are rendered twice, just once not correct.
Might this be linked to the filter too?

Screenshots:
![capture2](https://cloud.githubusercontent.com/assets/20314637/16732536/f923b4cc-477d-11e6-9fb3-0ab9140f6cf2.PNG)
![capture](https://cloud.githubusercontent.com/assets/20314637/16732535/f923818c-477d-11e6-8730-65dc23e90915.PNG)

**Comment by AMBudnik** [comment]
Hi @T1KK3S 
It's hard to say anything without a code (I'd be glad if you could create a Fiddle demo) and I have to say that it's a first time I see that happening to the _rowHeaders_ (or headers at all).
In some cases caused by the rowHeights adding the _`autoRowSize: true`_ to your instance's settings helps. If this won't help please create a demo.

**Comment by T1KK3S** [comment]
I have been able to find that the issue was putting a padding on the different cells using css and not the `rowheights` property op HandsOnTable itself. The row header issue is no longer there when not using custom css which resizes the cells.

However I still have my custom renderer not being executed on the last few items when I scroll down.
Is this a known issue?

**Comment by AMBudnik** [comment]
It should work for all defined cells. If you could create a JSFiddle demo I'd be happy to check if there's something that you're missing or maybe there's a andsontable's bug.

**Comment by nothingmi** [comment]
This is maybe useful @AMBudnik @T1KK3S http://jsfiddle.net/1qrnhbz7/1/

**Comment by AMBudnik** [comment]
thanks for sharing the demo @nothingmi 
@T1KK3S are you still facing any difficulties?

**Comment by AMBudnik** [comment]
I will leave this issue closed till it gets picked by the author.
