### ISSUE TITLE
Uncaught Error: Cannot find module 'numbro'

### ISSUE THREAD

**Issue by Vaccano** [handsontable/handsontable#3651]
I wanted to try to use hands on table in my web app, but when I added it in, I got this error:

> Uncaught Error: Cannot find module 'numbro'

This is the code that seems to be relevant to this (handsontable.js:4243):

     var numbro = ($__numbro__ = _dereq_("numbro"), $__numbro__ && $__numbro__.__esModule && $__numbro__ || {default: $__numbro__}).default;

It seems that hands on table tries to bundle this in, but it is not being seen in my app.  I tried to npm install numbro and I still get the same error.

My guess is that Hands On Table does not work out of the box with Webpack, but I have found no docs on how to make it work with Webpack.

Is this a known issue?  If so, is there a workaround?

**Comment by AMBudnik** [comment]
Hi,
Please check this issue for answer: https://github.com/handsontable/handsontable/issues/3627
[duplicate]

**Comment by kaplanov** [comment]
Issue stil exists. I reproduced it on Dan Abramov's react-webpack boilerplate. 
Just added Handsontable from npm, and is still cannot find nubmro.
here is the configuration: https://github.com/kaplanov/react-hot-boilerplate

**Comment by AMBudnik** [comment]
thanks for sharing @kaplanov 
I saw that you've already added a new issue at https://github.com/handsontable/handsontable/issues/3673
which is already reviewed by one of our developers.

**Comment by budnix** [comment]
Hi @kaplanov, I've found some time to look at your configuration and applied fixes to my fork. Commit with my changes you can find at https://github.com/budnix/react-hot-boilerplate/commit/db52685c8472ca0f85f361b91e33bbbaaf33c3d4. 

The problem with Handsontable was that it needs dependencies defined as a global variables, so I configured webpack to do it.
