### ISSUE TITLE
Best way to switch column and rows of table

### ISSUE THREAD

**Issue by stanleyxu2005** [handsontable/handsontable#3652]
Hi Folks, I'm new to this community. 

I have a question: Usually records are rendered row by row. Sometimes if there are too many columns, but the number of records (rows) are very less, people might want to rotate the table. I'm wondering, whether handson table supports swap/rotate column and rows. 

Any hints are highly appreciated.

**Comment by AMBudnik** [comment]
Hi @stanleyxu2005 

Unfortunately we do not have an option to reverse the data. You would need to rewrite the table.

**Comment by stanleyxu2005** [comment]
Very sorry to hear that. It's okay, if it is still possible to do that with Handson table. I will dig more into it.

**Comment by AMBudnik** [comment]
Hi again @stanleyxu2005 
I think that the best hint will be to check the `translateRowsToColumns` - it's a helper and it reverses the data only once but works, so I'm sharing a demo: http://jsfiddle.net/Lth7q5xd/

**Comment by stanleyxu2005** [comment]
Thanks a lot. I think your answer [(click to see detail)](https://github.com/handsontable/handsontable/issues/3653) is pretty much reasonable and doable, I'm going to close this issue.
