### ISSUE TITLE
Can we render a single cell?

### ISSUE THREAD

**Issue by zhouiscc** [handsontable/handsontable#3653]
hi Team,
Can we render a single cell, not entire column?
or can we render a row?
thanks

regards,
Vivi

**Comment by zhouiscc** [comment]
For eg,  i would like to achieve:  have cell A1 in date format, and B1 be a  dropfownlist.

**Comment by AMBudnik** [comment]
Hi @zhouiscc 
You can do it. Please check this example http://jsfiddle.net/7ge0wLgz/

**Comment by stanleyxu2005** [comment]
This is exactly I'm looking for. I'd suggest you add this code snippet also to example page. By the way, I'd like to ask, whether we can choose to copy value, copy format/renderer or value+format from cell A to cell B.

**Comment by AMBudnik** [comment]
Hi again @stanleyxu2005 
I was provided with a much better solution :http://jsfiddle.net/L8f4agh9/1/
We can only define a type and source for a particular cell.

**Comment by zhouiscc** [comment]
Thank you very much , it helps!

**Comment by HardRock4Life** [comment]
Hello everyone! I opened this thread, hoping to understand how to choose and render a single row on a mouse click. Both JSFiddle examples are not opening, putting 404 error out. Are there any similar working examples, please?

**Comment by AMBudnik** [comment]
Hey @HardRock4Life 
Here's an example https://jsfiddle.net/1o3tgzbj/ on how to add a custom renderer to a single cell (`cells` method). You can also use the [setCellMeta](https://handsontable.com/docs/7.1.1/Core.html#setCellMeta) method.
