### ISSUE TITLE
Fixed column headers makes row headers break on scroll

### ISSUE THREAD

**Issue by helmutgranda** [handsontable/handsontable#3654]
This may be an edge case but if you scroll down the table then left the row headers loose track on position.  

![image](https://cloud.githubusercontent.com/assets/82293/16808771/6f7ab614-48e3-11e6-86ae-72cf4388f8e3.png)

I was able to get it to  partially work by scrolling down, stop, then scroll right. The Row headers would work as expected but the behavior would remain. 

In our case we need the first two columns frozen but the headers fixed. We may be able to get around this issue by creating a custom row with header data which would break away from the default functionality.

Fiddle: http://jsfiddle.net/4g7skduw/4/

**Comment by AMBudnik** [comment]
Can't see it on IE, Chrome or Safari. I'll test it with Edge and come back with investigation results.

**Comment by AMBudnik** [comment]
Hi @helmutgranda 
I finally had a chance to test it on Edge and I cannot replicate that. Can you share more information our you device and or any settings that may reflect on how the websites are loaded?
Or maybe you can create a quick vid on how to replicate it (maybe I'm doing something wrong).
Any help would be appreciated :-)

**Comment by AMBudnik** [comment]
Hi again @helmutgranda 
with a help of @swistach we replicate and fixed the bug http://jsfiddle.net/a018nqko/
It was caused by styling. Please check if the above demo works good for you.

**Comment by helmutgranda** [comment]
Hi @AMBudnik & @swistach,

Thanks so much for working on this bug, however I think that there is still an issue when the headers need to scroll with the content. I created a fiddle with the updated code and the issue remains, that is unless making the headers stick is being done in a wrong way: 
![image](https://cloud.githubusercontent.com/assets/82293/16987727/68a013aa-4e53-11e6-966d-d1f1a90222ee.png)

fiddle: http://jsfiddle.net/t28gwnx0/

**Comment by AMBudnik** [comment]
Hi @helmutgranda 
After some investigation I unfortunately have to say that your goal can't be achieve easily & without breaking any functionalities as you would need to delete overlapping headers via cell renderers.

**Comment by helmutgranda** [comment]
Hi @AMBudnik, we were able to find a work around by making all the cells display (displayAllRows) and by hidding the overlapping headers when not needed. Not as elegant but meets our requirements. Thanks for trying to get this to work and welcome back.

**Comment by AMBudnik** [comment]
I'm so glad that you've found a workaround and you've shared the information here @helmutgranda . 
I'm sure that other users searching for the same case will appreciate :)

**Comment by uideveloper2015** [comment]
![issue](https://user-images.githubusercontent.com/43671056/50536099-eeaef280-0b76-11e9-9e12-5b515a149b62.png)
scroll x axis i will face this issue

**Comment by uideveloper2015** [comment]
how to fix this issue

**Comment by uideveloper2015** [comment]
i need help 
AMBudnik

**Comment by AMBudnik** [comment]
Hey @uideveloper2015 I have just replied to your second post with the same content. Please create a demo where the issue is present. I will test it.
