### ISSUE TITLE
Use Typescript in favour of ECMAScript 2015 (ES6)

### ISSUE THREAD

**Issue by rkrx** [handsontable/handsontable#3655]
On your [homepage](https://docs.handsontable.com/pro/1.5.0/tutorial-introduction.html) you state that "in the future the most important parts of the library will be rewritten to ES6 provide a better control over the code". Wouldn't it make more sense to rewrite the core in the upcoming [Typescript 2.1](https://github.com/Microsoft/TypeScript/wiki/Roadmap) instead, since it can target ES5 and ES3 using ES6+-Features like async-await for example?

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topics and uploading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Issue will be reopened with the first update.
All comments, investigation results or suggestions are welcome.

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. 

Please free to continue the conversation there. Thank you.
