### ISSUE TITLE
The editor is closed after scrolling

### ISSUE THREAD

**Issue by tstar** [handsontable/handsontable#3656]
Hi.
If you enter a cell in edit mode and scroll through the page and come back, then the cell is not in edit mode. This occurs in the code:

```
TextEditor.prototype.refreshDimensions = function() {
  if (this.state !== Handsontable.EditorState.EDITING) {
    return;
  }
  this.TD = this.getEditedCell();
  if (!this.TD)
  {
    this.close(true); // <= here comes close
    return;
  }
```

When you scroll, at some moment the function getEditedCell() no longer return any value, which leads to the closure of the editor. I found out that in fact the function this.instance.getCell(this.row, this.col) does not return a value.
An example can be reproduced at any table on page [https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable](https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable). Choose any top cell, go to the edit mode, scroll down and back. In the edited cell is no longer the focus.

Why the function this.instance.getCell(this.row, this.col) does not return the value of the cell being edited?

**Comment by AMBudnik** [comment]
Thanks for sharing @tstar 
I got the same result.

**Comment by tstar** [comment]
I think this happens because virtual rendering used when a row is goes beyond the virtual window. But it is very bother you when it is necessary to change the cell, while the look in another row, which is available only after scrolling.

**Comment by AMBudnik** [comment]
as a workaround you can add `renderAllRows: true` to your settings: http://jsfiddle.net/raL7hafs/

**Comment by tstar** [comment]
I tried, but in my case, in Chrome table from 2000 lines to appear after 5 minutes, and IE 11 proposed to close the page.

**Comment by AMBudnik** [comment]
@swistach Can we do something about that? 

As I assume that when user opens editor and we scroll the table rerenders and that's why editor is being closed each time we scroll many rows/columns. Am I right?

**Comment by swistach** [comment]
Present, the only way to workaround this problem is create the custom editor.
We should discuss this issue.

**Comment by AMBudnik** [comment]
This behavior is no longer replicable in v [8.1.0](https://handsontable.com/docs/8.1.0/demo-scrolling.html)

![GIF](https://user-images.githubusercontent.com/10757813/95067378-0e882880-0704-11eb-9762-f8aace1043a0.gif)
