### ISSUE TITLE
How to insert a linebreak programatically

### ISSUE THREAD

**Issue by g0nP** [handsontable/handsontable#3657]
I'm using a handsontable with ReadOnly data (emulating a Gridview) to show information from a DB.

There is a column of type string which should show text as follows:

Text1 (linebreak)
Text2 (linebreak)
etc.

If I use a Gridview, I can accomplish this by setting the Datafield of the column as "Text1 \<br/> Text2 \<br/> etc.". When the Gridview renders, the tag \<br/> produces a linebreak.

When using handsontable, the tag \<br/> renders al simple text and the result is a plain string  "Text1 \<br/> Text2 \<br/> etc.". I also tried using "\n" without success.

Is there a way to add a linebreak programatically?

**Comment by g0nP** [comment]
Problem solved. 

Using a customRenderer and setting the innerHTML of the cell as "Text1 \<br/> Text2 \<br/> etc." was the way to go. :)

**Comment by AMBudnik** [comment]
That's right @g0nP 
You can also add a `renderer: 'html` in particular cell/s it should run faster.
