### ISSUE TITLE
Placement problem when using MasterPage

### ISSUE THREAD

**Issue by g0nP** [handsontable/handsontable#3659]
I am working on an ASP.NET 4.5 application with a master page file.

I am getting the error "Cannot read property 'insertBefore' of undefined" and I think it has to do with where I place the handsontable script reference:

\<script` type="text/javascript" `src="../Scripts/handsontable/handsontable.full.js"></script>

I have tried placing it in the master page in the head section and in the body section before and after the ContentPlaceHolder without result.
I also tried placing it in the child page with no effect.

Any ideas?

**Comment by AMBudnik** [comment]
You've tried the master page within the head tag and it does not work?

**Comment by g0nP** [comment]
This is kind of embarrassing. :$

I was placing the tag correctly. I placed them in the MasterPage, in the body section, before the ContentPlaceHolder.

The actual problem was when trying to instantiate the handonstable. Apparently it was not recognising the div id. I added clientidmode="static" to the div and now it works fine.
