### ISSUE TITLE
Dropdown list disappears behind bottom of table

### ISSUE THREAD

**Issue by Zay2k** [handsontable/handsontable#3661]
If I define height of the table in handsontable initialization dropdown lists at the bottom of the table disappears outside the table div. 

Example: http://jsfiddle.net/n07wvh74/

As you see in the example, this does not happen with datepicker popup. 

Possible connection to [#2098](https://github.com/handsontable/handsontable/issues/2098)

**Comment by AMBudnik** [comment]
Hi @Zay2k 
Thanks for sharing.
We have the same case at https://github.com/handsontable/handsontable/issues/3435 so please share any other/additional comments at https://github.com/handsontable/handsontable/issues/3435
