### ISSUE TITLE
beforeColumnResize hook chaining problem

### ISSUE THREAD

**Issue by gresspav** [handsontable/handsontable#3662]
Wanted to add new hook for event beforeColumnResize. 
Handsontable.hooks.add("beforeColumnResize", ....);
public static beforeColumnResize(currentColumn: number, newSize: number, isDoubleClick: boolean)

There were already added two beforeColumnResize hooks by plugin when I run the application. 
I expected that my method will be called as the last one, however, there is a bug because input arguments does not contain correct currentColumn value.
Problem is in function run which overwrites values p1 (originaly currentColumn ) with newSize.

Temporary solution could be remove other hooks or put condition into the  run function
run: function(context, key, p1, p2, p3, p4, p5, p6) {
               if (key !== 'beforeColumnResize') {
                   p1 = res$__6;
               } else {
                   p2 = res$__6;
               }

**Comment by AMBudnik** [comment]
Can you create a demo with step-by-step scenario how to replicate this issue? It would be very helpful.

**Comment by gresspav** [comment]
Hello, finally I found that the problem was already reported.
https://github.com/handsontable/handsontable/issues/3328
https://jsfiddle.net/handsoncode/3gpe2qq5/
As I already mentioned the problem is in function run which always overwrites value p1 (originaly currentColumn ) with newSize.
run: function(context, key, p1, p2, p3, p4, p5, p6) {
....
p1 = res$__6;
....
}
Code works fine if there is only single beforeColumnResize hook function. The second beforeColumnResize hook function is called with overwriten argument currentColumn = newSize (in demo).

**Comment by AMBudnik** [comment]
Thanks for an update and your investigation @gresspav 
I guess that we can close this issue as it's the same as https://github.com/handsontable/handsontable/issues/3328
If you would have any other investigation results please share them at https://github.com/handsontable/handsontable/issues/3328

**Comment by AMBudnik** [comment]
Hi @gresspav 

The referenced issue https://github.com/handsontable/handsontable/issues/3328 just has been closed as solved in v 8.0.0
