### ISSUE TITLE
Stretch colWidths except a specified column

### ISSUE THREAD

**Issue by varun-dev** [handsontable/handsontable#3665]
Hi,

Is it possible to specify fixed width to a column and stretch others ?
I did try to read through other posts here but did not find any solution.

Thanks
Varun

**Comment by AMBudnik** [comment]
Hi @varun-dev 
You can set a minimum width of a column and left others, like here:  http://jsfiddle.net/34grf5qs/
Currently [`stretchH`](https://docs.handsontable.com/pro/1.5.0/demo-stretching.html) option takes only 3 possible options: `none`, `all` and `last`

**Comment by varun-dev** [comment]
Hi @AMBudnik
Thanks for your response. I need a fixed width hence I am only left with an option to hack the column width by doing something like 
```
.handsontable col:nth-child(1){
  width:100px !important;
}
```

however I need to be able to add a class on the col tags in the colgroup. 

```
.handsontable col.fixed{
  width:100px !important;
}
```

Can you think of a way to do that?

**Comment by AMBudnik** [comment]
Can you share a Fiddle with the example that you already got?

**Comment by varun-dev** [comment]
I was thinking of doing something like this
http://jsfiddle.net/34grf5qs/1/
Its kinda working with the first column but overall width of the table to getting wrongly calculated.

**Comment by AMBudnik** [comment]
Hi @varun-dev 
I think that you may have the a 'fixed height only' on your mind. This will allow the table to get the 100% width of the parent container.

Like described in our blog post: https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable
it is currently unavailable.

**Comment by stanleyxu2005** [comment]
This is a wonderful feature. I'd have read the doc more carefully.
