### ISSUE TITLE
fixedColumnsLeft horizontal scroll with keyboard

### ISSUE THREAD

**Issue by avivenzio** [handsontable/handsontable#3666]
When adding a margin-top style to the Handsontable container div the horizontal scrolling is affected. I am adding the style to display the table below my fixed header. The fixed columns on the left do not return to their original position when scrolling from right to left using the arrow keys. They are displayed on top of the first unfixed column to the right. There is no issue when using the scroll bar. 

I have included a JsFiddle where I was able to reproduce: [http://jsfiddle.net/4obmxsc7/](http://jsfiddle.net/4obmxsc7/)

Steps:
1) click a cell
2) use the right arrow key to scroll to the rightmost column
3) use the left arrow key to return to initial position
4) the fifth column from the left should be hidden by the fourth column

My users love to use the keyboard for navigation, thanks for taking a look.

**Comment by AMBudnik** [comment]
Hi @avivenzio 

Thanks for sharing. I've reproduce the odd behavior of hiding the 5th column (`E`).

![bug](https://cloud.githubusercontent.com/assets/10757813/16948722/97b29b9c-4db6-11e6-9dbb-ccccbcfb0d23.gif)

Additionally the selection is lost when I want to select last cell in the column.

**Comment by AMBudnik** [comment]
The issue is no longer replicable while using v `2.0.0` Updated demo http://jsfiddle.net/138nw1bb/
