### ISSUE TITLE
Does currentRowClassName work for the angular version?

### ISSUE THREAD

**Issue by garypma** [handsontable/handsontable#3667]
I'm unable to get it working (it doesn't do anything at all). Currently I have it set like this:

currentRowClassName= "currentSelectedRowClass" in the hot table definition. I have tried multiple things, but the class never gets pulled in. Any help would be appreciated. The html looks llie:

hot-table hot-id="compTable"
               datarows="participants"
               settings="{afterChange: itemChanged, afterOnCellMouseDown: cellMouseDown}"
               row-headers="false"
               col-headers="columnHeaders"
               height="550"
               column-sorting
               dropdown-menu="dropdownMenu"
               columns="columns"
               nested-headers="nestedHeaders"
               collapsible-columns="collapsibleColumns"
               hidden-columns="hiddenColumns"
               currentRowClassName= "currentSelectedRowClass"
               filters>
    </hot-table>

And in the controller I have:

$scope.currentSelectedRowClass = "currentSelectedRow";

In css I have defined:

.currentSelectedRow {
    background-color: lightblue !important;
}

**Comment by AMBudnik** [comment]
@garypma 
Please send all requests about Angular version of Handsontable at its issue board:
https://github.com/handsontable/ngHandsontable/issues

ps. http://jsbin.com/feqana/2/edit?html,css,js,output hope this demo will come in handy

**Comment by garypma** [comment]
Thanks. I found another way to do it as well. It would be nice if you updated your documentation to include angular examples and additional documentation for the angular version.

**Comment by AMBudnik** [comment]
I guess we would make some huge docs changes with [Angular 2 support](https://trello.com/b/PztR4hpj/handsontable-roadmap-2016-login-to-vote-for-features).
