### ISSUE TITLE
Allow for time type input of 1300

### ISSUE THREAD

**Issue by mscreenie** [handsontable/handsontable#3668]
When using the data type 'time' it formats an entry of 14 as 14:00 correctly. However when typing 1430 it will not format it as 14:30. May I kindly request this as a feature?

**Comment by AMBudnik** [comment]
Hi @mscreenie 
We should provide more information in this matter what we can define and what we will get as a result. Currently this information is 3 clicks away in the momentJS docs.

Here's an example: http://jsfiddle.net/8n8ns0cp/1/
If we have a format as `h:mm` if we stick to it and type `14:30` it works but if we type `1430` we won't get what we wanted - `1:00 am`. But... we can also type `14,30` at it works as expected.

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
