### ISSUE TITLE
min value for rowHeights

### ISSUE THREAD

**Issue by zhouiscc** [handsontable/handsontable#3669]
Hi, I tried to modify rowHeights to very small value
rowHeights:function(row){
                  		return 5;
                  },

but looks like the min value of rowHeights is 22?  may I modify it to a very small value?
Thanks

**Comment by AMBudnik** [comment]
Hi @zhouiscc 
You can overwrite the default settings by adding `cells` and additional class. Here's an example: http://jsfiddle.net/pfgy02e5/1/

**Comment by zhouiscc** [comment]
![capture](https://cloud.githubusercontent.com/assets/8252613/16944239/2f456a3c-4dd2-11e6-9e88-35d782034fa8.JPG)

see above picture. so if I use narrow class, the empty row would be narrow, but if you input any value (even if I set the font size to x-small) , the cell back to normal again.

is there any padding by default?

**Comment by zhouiscc** [comment]
![capture](https://cloud.githubusercontent.com/assets/8252613/16944499/800116f0-4dd3-11e6-82ef-2fea69a99d56.JPG)

also you can see, the cell is not aligned.

**Comment by AMBudnik** [comment]
Hi @zhouiscc 
Yes, unfortunately the height of the cell cannot truncate the text inside by using `cells` method but you can overwrite the cell renderer to do so. Here's an example: http://jsfiddle.net/tv4dgzfp/5/ 

It's easy for text type cells but for other cell types that actually have their logic inside the renderer it can block their abilities making them useless.

**Comment by zhouiscc** [comment]
I see! thank you very much for you reply.! it helps
