### ISSUE TITLE
max Json Length error in HandsOnTable

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#3670]
I am getting a max json length error during sending data to web server from the browser
What I am doing is below:
1. creating a HOT with 30 rows and 45 columns --  no issue
2. fetching the data and holding it in a variable (var Alldata = HOT.getData()) -- no issue
3. making a $.ajax call to pass it to the web server as below --  issue here
$.ajax({
url: "<<server url>>", cache: false, type: "POST", data: JSON.stringify({ data: Alldata }), contentType: 'application/json', success : function() {......}, error : function() {.......}

I am getting the subject error.

Please advise.

**Comment by AMBudnik** [comment]
Hi @PassHours 
Handsontable is a frond-end library we do not provide examples of how to manage data with the server. Here's the only example of load & save options for Handsontable http://docs.handsontable.com/0.17.0/tutorial-load-and-save.html
