### ISSUE TITLE
Add 'afterKeyDown' hook

### ISSUE THREAD

**Issue by steloh** [handsontable/handsontable#3671]
with the version 0.26.0 I will give the user the information, on which position to proceed the input – only digits – of a digit-string divided with slashes. 
For example, after four digits a 9-digit-string should look like `123/4__/___`. 
With `stopImmediatePropagation()` nothing will be displayed. On the `console.log()` I see the right value with the pattern set. Without `stopImmediatePropagation()` the last input is added behind the pattern. How can this be solved? 

`beforeKeyDown: function (event) {`
`var editor = this.getActiveEditor();`
`event.stopImmediatePropagation();`
`if (/\d/.test(event.key)) { // the input can only be a digit`
`var value = pattern(editor.getValue() + event.key);    // function "pattern" sets the slashes`
`// and the pattern`
`editor.setValue(value);`
`this.destroyEditor();   // doesn't help`
`this.render(); // doesn't help`
`}`
`console.log('output ' + editor.getValue()); // here I see the correct output`
`},`

PS: If there would be a event like `afterKeyDown` it would be easier, because I could do this:

`afterKeyDown: function (event) {`
`var editor = this.getActiveEditor();`
`var value = pattern(editor.getValue().replace(/\D/g,'')); // "replace" will be`
`// inside the function "pattern"`
`editor.setValue(value);`
`this.render();`
`},`

**Comment by AMBudnik** [comment]
Hi @steloh 
` event.stopImmediatePropagation();` to stop anything.
I guess that in your case you would need to create a custom editor and maybe a renderer as well.
Here's a complete tutorial about cell editors: https://docs.handsontable.com/pro/1.5.0/tutorial-cell-editor.html

**Comment by steloh** [comment]
Hi @AMBudnik 

thank you for your reply! I must be admitted the solution with a custom renderer was my first idea, but I failed. I just begun with JS 3 month ago because Handsontable an so I don't have enough experience to translate the examples in the tutorial – I tried to understand this for a few times – to my problem. 

The solution with the active editor was quite simpler and would work very well, if the result would be displayed in the cell. I don't understand, why the string not appear though the cell has the exact content. Is there another chance how I can solve this problem? This task is the last hurdle to build a user interface for a psql-DBMS, the other parts works very nice and very fast.

**Comment by steloh** [comment]
Hi @AMBudnik

For the moment I found not a elegant but a usable solution (and maybe faster then a custom editor) 

`beforeKeyDown: function (event) {`
`var editor = this.getActiveEditor();`
`event.stopImmediatePropagation();`
`if (/\d/.test(event.key)) {`
`var value = pattern(this.getDataAtCell(this.getSelected()[0],this.getSelected()[1]) + event.key);`
`this.setDataAtCell(this.getSelected()[0],this.getSelected()[1],value);`
`editor.open();`
`}`
`},`

In spite of this, a `afterKeyDown`-event in the future would be nice. Thank you for your time and for the information!

**Comment by AMBudnik** [comment]
Hi @steloh 
Thank you as well for your time and effort to share this case.
ps. I'm reopening this issue and chaning the title to mark this as a feature request for the `afterKeyDown` hook.

**Comment by AMBudnik** [comment]
it is literally the same as We're moving this topic to our [Feature-requests section](https://github.com/handsontable/handsontable/wiki/Feature-requests) but more specified

**Comment by douxlagithub** [comment]
I think the feature of afterKeyDown is a basic feature. I really need this feature. I'm working with HT table that uses Key Up (38) Key Down (40) to call loadProperties() of each row based on selected row (rowId) to display corresponding properties from properties table, then displaying it on the bottom of my table. I tried beforeKeyDown Hook, then the problem came up. The data returned from database is for previous row not for selected row. This because the loadProperties() method called before key down.

**Comment by AMBudnik** [comment]
Hey @douxlagithub have you tried [`afterDocumentKeyDown`](https://handsontable.com/docs/7.0.2/Hooks.html#event:afterDocumentKeyDown)?

**Comment by douxlagithub** [comment]
@AMbudnik, I have tried it and gave me the same result.

**Comment by AMBudnik** [comment]
Hey @douxlagithub please send over a demo with your implementation to support@handsontable.com

**Comment by douxlagithub** [comment]
https://jsfiddle.net/douxmaster/1o8bztka/1/

**Comment by AMBudnik** [comment]
Hey @douxlagithub I can recommend the `afterSelectionEnd` hook for you use case https://jsfiddle.net/handsoncode/gtpn45ae/

**Comment by douxlagithub** [comment]
Hey! It works. Thanks for awesome help!

**Comment by AMBudnik** [comment]
You're welcome :)
