### ISSUE TITLE
Cannot find finde module 'nubmro' error with react-webpack hot-reload boilerplate

### ISSUE THREAD

**Issue by kaplanov** [handsontable/handsontable#3673]
Maybe problem is caused by hot reloading, but it is a de-facto standard in react community.
Below are project configuration where issue was encountered.

Tried to add Handsontable to simple react-webpack boilerplate without any success (available here - https://github.com/kaplanov/react-hot-boilerplate). 
To reproduce:
1) checkout
2) run npm install
3) run npm run
4) navigate to localhost:3000
I got handsontable.js:53 Uncaught Error: Cannot find module 'numbro'

**Comment by AMBudnik** [comment]
Hi,

I think that this can be the case https://github.com/foretagsplatsen/numbro/issues/188
I guess that you can try to change

import React, {Component} from 'react';
import numbro from 'numbro';
import moment from 'moment';
import pikaday from 'pikaday';
import Zeroclipboard from 'zeroclipboard';
import Handsontable from 'handsontable';

to

import React, {Component} from 'react';
import Handsontable from './../node_modules/handsontable/dist/handsontable.full';

in your HoT.js file

**Comment by Primajin** [comment]
Is it maybe just a typo?

`Cannot find finde module 'nubmro'` this module here is called `numbro` ... 😉

**Comment by AMBudnik** [comment]
closed with: https://github.com/handsontable/handsontable/issues/3651

**Comment by volkandkaya** [comment]
I created this https://gist.github.com/volkandkaya/172785a30b6bea5bb57d20fd9e9e9424, I think it will save people a lot of time.
