### ISSUE TITLE
What's the best way to hide gridlines?

### ISSUE THREAD

**Issue by zhouiscc** [handsontable/handsontable#3674]
Hi what would be the best way to hide gridlines?
also for customBorder, can we use function?
thanks

**Comment by AMBudnik** [comment]
Hi @zhouiscc 
I would overwrite a `.handsontable td` class like this http://jsfiddle.net/gu1pdv51/ (in this case I changed the color to whote but you can also add the `border: 0` instead.
Another option is to use `cells()` method to add a new class that will do the same as the code above.

When it comes to borders you would like to change borders grammatically or allow users to change borders via context menu?

**Comment by zhouiscc** [comment]
Thanks. Data cell border will be gone after setting `border:0`  but the header will still have 1px gray border. I debugged, it is somewhere in `thead`. Any idea to remove that as well?

**Comment by AMBudnik** [comment]
Maybe that's not an ideal solution to use `!important` but the borders of headers are rerendered so to erase them you would need to (like said before) add the new class via `cells()` method or add the `!important` tag to the `border` (example: http://jsfiddle.net/u3d8j4gj/)

**Comment by zhouiscc** [comment]
Thanks looks good.   btw, in custom render,  i saw ur sample to do conditional formatting.  but how i can do this , if one cell value == "A" , the whole row background color = "yellow".

**Comment by AMBudnik** [comment]
Hi @zhouiscc 
If a value in the first cell is `A` whole column should be yellow, right?
If so here's the demo http://jsfiddle.net/4nry59j2/

**Comment by zhouiscc** [comment]
nice  lemme have a try
