### ISSUE TITLE
Add 'renderAllColumns' setting

### ISSUE THREAD

**Issue by susanne-envoy** [handsontable/handsontable#3675]
Hi guys,

Thanks for your all your work on such an awesome library.

In my use case I needed to turn off virtual rendering for columns as well as rows. I found that there wasn't an option in the settings to do that, however upon looking at the source code it seems that it can be accomplished in the same manner as is done for disabling virtual rendering for rows.

For now I have hacked a line in to `createColumnsCalculator` where I set the `width` to `Infinity`, however I do not have time to build this out myself with tests and submit a PR.

It seems to be a straightforward change so if possible it would be amazing to get this setting included.

Thanks!

Susanne

**Comment by AMBudnik** [comment]
Hi @susanne-envoy 
thanks for sharing this idea. I'll add it to our feature request list.

ps. you can render all needs columns using this method https://docs.handsontable.com/pro/1.5.0/Options.html#viewportColumnRenderingOffset

**Comment by AMBudnik** [comment]
We're moving this topic to our [Feature-requests section](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
