### ISSUE TITLE
validateCells rerenders the view

### ISSUE THREAD

**Issue by gstanislav** [handsontable/handsontable#3676]
The docs describe the `validateCells` function like this: "Validates all cells using their validator functions and calls callback when finished. **Does not render the view."**

I assume this means that after the cell was validated and turned out to be invalid, it is not rerendered as "invalid".

This is not, however, the case. See fiddle: http://jsfiddle.net/076sLo3x/

In this fiddle a HOT is rendered, and the `validateCells` is run afterwards. Expected result: "invalid!" cell in the first column is not marked as invalid visually. Actual result: it is marked in red.

This happens because `validateCell` rerenders the cell: https://github.com/handsontable/handsontable/blob/master/src/core.js#L1084

Which leads to another, more pressing problem. Since `validateCells` works asynchronously, each cell is also rendered asynchronously. This means that instead of a single batch rerender, we get huge amount of small rerenders, which is much, much slower (10x at least). This is the reason, I think, for slow validation problem: https://github.com/handsontable/handsontable/issues/3276

Suggested solution: do not render cell in `validateCell`.

**Comment by AMBudnik** [comment]
Thank you very much @gstanislav for the effort 
related: https://github.com/handsontable/handsontable/issues/3276

**Comment by AMBudnik** [comment]
also this line **'Does not render the view'** corresponds to the old documentation where this line was correct. In the current `validateCells()` method (as you rightly discovered) this line is no longer correct as the table is being rerendered.

We have to change this description in our docs.

**Comment by gstanislav** [comment]
Please note that there's still the performance problem caused by asynchronous rerendering. Maybe `validateCells` really shouldn't rerender the table?

**Comment by AMBudnik** [comment]
'Does not render the view' is deleted

**Comment by AMBudnik** [comment]
I'm moving all the improvement suggestions to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Please feel free to leave any additional comments and reflections.

Thanks in advance!

**Comment by gstanislav** [comment]
**Please note that there's still the performance problem caused by asynchronous rerendering.**

**Comment by AMBudnik** [comment]
@gstanislav could you create a separate topic for this issue? It will be better to separate those two ideas.

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. Please free to continue the conversation there. Thank you.
