### ISSUE TITLE
Suggestion to add borders for all sides as default 

### ISSUE THREAD

**Issue by amoghmalik** [handsontable/handsontable#3678]
It would look more aesthetic to have borders for all the sides of the table constantly visible, rather than only being able to see them at the end of a scroll.
As in the picture below: 
![screen shot 2016-07-22 at 15 32 32](https://cloud.githubusercontent.com/assets/15077731/17058929/f3bfd7b0-5022-11e6-98ce-8aec9874a0a1.png)

Demo: (Table without right and bottom borders)
http://jsfiddle.net/api/post/library/pure/

**Comment by AMBudnik** [comment]
Topic moved to [Improvement-suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)
