### ISSUE TITLE
Select multiple cell on editing formula

### ISSUE THREAD

**Issue by hariskhalique** [handsontable/handsontable#3679]
Hi Guys,
I am new to Handsontable. What I am trying to achieve is keep editing and when I click on other cell get column number and append to formula. 

Like we did on google excel sheet. Starting edit cell with "=" and click on other cell it add clicked cell number eg "B1" to cell on which I start editing.

Any help will be highly appreciated.

Thanks

**Comment by AMBudnik** [comment]
Hi @hariskhalique 
This option is currently unavailable but we have this one in our Formula to-do list.

**Comment by hariskhalique** [comment]
How can I get current value for current Active Editor

**Comment by hariskhalique** [comment]
How can I destroy editor editing on current cell I try with
var activeEditor = $hot.getActiveEditor();
activeEditor.isOpened()  // return true in all case

please help

**Comment by AMBudnik** [comment]
You can't get a value of the cell before the editor gets closed - the only would be to use `beforeChange` it will send you information before the change is made and then you'll be able to get the data or block a change but the editor will close.

To destroy an active editor you can use 
`instanceName.destroyEditor()` ([docs](https://docs.handsontable.com/pro/1.5.1/Core.html#destroyEditor))

**Comment by hariskhalique** [comment]
I found workaround for formula and implemented desire functionality. Looking forward to have this in default functionality ( Free Version ) :)

**Comment by hariskhalique** [comment]
editor_instance.foucs() not working I have to click on cell to start editing.
I try editor_instance.enableFullEditMode() no success

**Comment by AMBudnik** [comment]
thanks for sharing @hariskhalique 
I'll leave this issue to be reviewed by our devs.

**Comment by jansiegel** [comment]
This indeed doesn't seem to work properly. I'll label it as a bug, so we could investigate it further.

**Comment by wojciechczerniak** [comment]
The original post is about new feature: formula point&click editor. We will cover it elsewhere.
