### ISSUE TITLE
Call hook event

### ISSUE THREAD

**Issue by Schnurtle** [handsontable/handsontable#3680]
I have the following hook event:

```javascript
myhandsontable.addHook("afterChange", function(changes){
   myhandsontable.updateSettings({
     ... <many lines> ...
   });
 });
```

It works fine after every change but I want it to run once after my handsontable loaded. There are many lines inside the updateSettings function and I don't like to write this code twice (that's my temporary solution, which works fine) :

```javascript
var onlyonce = true;
if(onlyonce){
myhandsontable.updateSettings({
     ... <many lines> ...
   });
onlyonce = false;
}
```
Is there a way to call this hook-event manually? Like `Handsontable.afterChange()`?
(Perhaps this is a generally JavaScript-related question, but I don't know)

**Comment by AMBudnik** [comment]
Hi @Schnurtle 
I'm not sure if I understand it correctly.
You want to run a function after initialization and after each type of change in the table?

**Comment by Schnurtle** [comment]
Yes, exactly. But it would be the same function for both situations

**Comment by AMBudnik** [comment]
`afterChange` hook takes two arguments, one of them `source` informs you which type of change was made, you can determine if you want to proceed with an operation after `init`, `edit` or any other options from this list: https://docs.handsontable.com/pro/1.5.0/Hooks.html#event:afterChange

**Comment by Schnurtle** [comment]
I think I didn't express myself well - the problem is simpler. I have just found a better solution as mentioned before (though I'm not sure if there is still a shorter way).
I declared the following function:

```javascript
function myFunction(){
  myhandsontable.updateSettings({
     ... <many lines> ...
   });
}
```
and call it after my handsontable-table is rendered and after every change:

```javascript
myhandsontable.addHook("afterRender", function(){
myFunction();
});

myhandsontable.addHook("afterChange", function(changes,source){
myFunction();
});
```

Anyway - thanks for your post - I misunderstood the use of parameters for hook events (thought there is always one `changes` parameter).
I'm sorry, I guess it doesn't necessarily have anything to do with handsontable...
Or is there still a better way to do this?

**Comment by AMBudnik** [comment]
I guess I just would do this if you want to run `myFunction()` after initialization and after every `edit` change.

```js
myhandsontable.addHook("afterChange", function(changes, source){
 if(source === 'init' || source === 'edit'){
    myFunction();
  }
});
```

**Comment by Schnurtle** [comment]
Ah, now I know why you told me about these arguments. Thank you for your fast support! :+1:

**Comment by Schnurtle** [comment]
I tried your code but the function is not called on initialization. Here is a working [JSFiddle](https://jsfiddle.net/cvhc9tLm/2/)

**Comment by AMBudnik** [comment]
hm... I should than recheck this example then.
You can use `loadData` instead, here's an updated example: https://jsfiddle.net/xvzgqo11/
I had to place the code inside the table starting settings as the first `loadData` won't be triggered if the code was added as above (by adding the hook outside the settings)

**Comment by budnix** [comment]
Hi @Schnurtle, 

On initialization this code never executes because in your case it is to late. If you want the hook to be called while initialization you need init Handsontable manually (https://jsfiddle.net/budnix/a4jygqfe/) or move hook listeners to constructor (https://jsfiddle.net/budnix/b3nj0912/).

**Comment by Schnurtle** [comment]
@AMBudnik  No problem - `loadData` works fine!
Thanks for your detailed information @budnix
