### ISSUE TITLE
Prevent cellProperties-update from looping through whole table

### ISSUE THREAD

**Issue by Schnurtle** [handsontable/handsontable#3682]
I have a handsontable-table and want to do stuff (e.g. update renderer of other cells in the same row) after every change of one specific column-cell. My updateSettings-function looks like this:

```javascript
myhandsontable.addHook("afterChange", function(changes,source){
  myhandsontable.updateSettings({
     cells: function (row, col, prop){
        var cellProperties = {};
        if(col === myhandsontable.propToCol("team")){
                ... <my code> ...
         }
     return cellProperties;
     }
  })
}
```

It does work, of course. But it is very slow, because the `cells:`-function (I think) is looping through the whole table and checks, if the `col` is equal to `myhandsontable.propToCol("team")`. And this isn't only happening once after I change a cell. When the first cell is changed, this `cells:`-function is called every click or scroll on my table.
I could use the `changes` argument, to find out, if the changed cell is from col "team". I could easily check this before the `updateSettings`-function. But is there a way to call `updateSettings` or at least `cells:` for only specific cells? I imagine something like that:

```javascript

//don't use this - it won't work
myhandsontable.getCell(1,4).updateSettings({
...
})
```

I know it is possible to write the `cells:`-function in the handsontable-constructor but I think I can't use it (though I tried) because I need information from the table, like the column-name, which is at the moment inside the constructor not available (undefined).

**Comment by AMBudnik** [comment]
Hi @Schnurtle 
If your code needs to look for the cell with defined property it will do some extra operations and it's not a secret but in the Handsontable you can access a cell by giving its direct place in the table (row, col). 
The `getCell` method actually works but you will get the DOM element. With it you can change for example a filling (innerHTML) or change a `className`. 
You can only use the `getCellMeta()` mehod where you'll be able to set/change each part of this list: http://jsfiddle.net/6673763j/

**Comment by Schnurtle** [comment]
So in other words: It is possible to **change the DOM element** properties for one specific cell without looping through the whole table but it isn't currently possible to **update** the `cellProperties` for one specific cell without looping through the whole table?

**Comment by AMBudnik** [comment]
I guess that it will always need to loop through the whole table when you define an exception that can be true for more than just one cell. If you type `row === 0 && col === 8` there's only one cell that can meet this requirements but when you type `prop === 'something'` there can be more than just one cell so the loop has to reach every cell.
I'm not sure if I do not digress from the subject - you were talking about the performance issues with this solution. How big was your data? I think we should replicate this situation and focus on the performance.

**Comment by Schnurtle** [comment]
I understand it has to loop through the whole table when there are more than one affected cells. But when I have the specific cell as you mentioned - is there no way to avoid the loop and change its `cellProperties`?

My data depends on the user's chosen columns (the Handsontable gets generated and filled from an Oracle PL/SQL statement). It can range from about a few cells to nearly 150.000 cells (in the "worst" case) but I expect an average of about 1.000 - 5.000 cells, which is the amount of cells I use for developing. Even if I use thousands of cells, scrolling works smooth (thanks to virtual scrolling) - as long as I don't call a `updateSettings`-function...

**Comment by AMBudnik** [comment]
Ok... I think that we're missing a strict example here @Schnurtle. Can you create one?
It will be much better to have a live demo and work on it than to serve a pure theory.

**Comment by Schnurtle** [comment]
I created a simple [fiddle](http://jsfiddle.net/j59heyrq/2/)
When you change some cell and open your console you can see, that the `cells:`-function is called very often, not only after changes - while scrolling, clicking,...
I simply want to change the `cellProperties` of this one specific cell I clicked on (it doesn't matter the green background is gone after a new change), it's useless the function loops through all other cells

**Comment by AMBudnik** [comment]
OK, so the case is that the renderer is called when you change a cell, and currently cell renderer is called :
* when table is initialized
* every time data has been changed
* you can call it manually by instance.render()

and... it's called for all the cells even if only one cell was changed. We have talked about this case and we will be adding an ability to rerender a single cell but there's no release date for this task yet.

**Comment by Schnurtle** [comment]
I understand. Thanks for your clear answer - I look forward to this new feature :+1:

**Comment by prakashbist** [comment]
Is this feature is added to the revision or still pending. It would be so wonderful if we can tell the cells:function when to loop through the whole table and when not to by passing an extra parameter from caller method to identify where it is called from. Hope you guys make it very soon.

**Comment by prakashbist** [comment]
Thank You @AMBudnik  it would be helpful to see any example on it.

Actually i need it due to this problem https://stackoverflow.com/questions/47327609/handsontable-formula-value-error-even-the-formula-for-the-cell-is-correct

So to avoid that thing i  reset the value of the cell which are throwing #VALUE! error 
                   
```
  for (i = 0; i<rowToRefresh.length; i++)\
              {
		 for(column=0; column &lt; columns; column++)
                      {
			 var row=rowToRefresh[i]-1;
			  var value= table1.getDataAtCell(row,column);
			  table1.setDataAtCell(row,column,"");
			  table1.setDataAtCell(row,column,value);
	          }
     }
Here:
**rowToRefresh** is the array which consist of row number i want to reset value of and **columns** is the number of column that sheet contains. Above code loop through the rowToRefresh and goes up to each column of that row/table. 
                          var value= table1.getDataAtCell(row,column); //get the value of  cell
			  table1.setDataAtCell(row,column,""); //set something else to cell
			  table1.setDataAtCell(row,column,value); //reset the same old value of cell

Then above 3 line of code reset the value of cell i want. Its works fine but it is taking very long time almost 2sec for 1 specific cell because it loop on whole table which really getting overhead.

Will you please explain how can i do that. But if you guys have solution to this problem https://stackoverflow.com/questions/47327609/handsontable-formula-value-error-even-the-formula-for-the-cell-is-correct then i think i don't have to take this approach.

**Comment by AMBudnik** [comment]
Hi @prakashbist it looks like an issue at https://github.com/handsontable/handsontable-pro/issues/15
It has been already fixed but wasn't released. We are waiting for a few fixes from our dev team to push the new version online.
