### ISSUE TITLE
autocomplete breaks removeRow plugin

### ISSUE THREAD

**Issue by YourDeveloperFriend** [handsontable/handsontable#3683]
You can check out an example of this bug [here](http://jsfiddle.net/wuwnw2xs/).

Essentially, the removeRow button appears properly at the beginning, but then when you interact with the handsontable, the removeRow button stops working.

Let me know if you have any questions.

**Comment by AMBudnik** [comment]
Hi @YourDeveloperFriend,

What exactly you would like to achieve?

**Comment by YourDeveloperFriend** [comment]
Did you try the jsfiddle? I would like the removeRow button to work consistently. Walk through these steps and you'll see what I'm talking about:

1. Go to the JSFiddle here: http://jsfiddle.net/wuwnw2xs/
2. Hover over any row header and observe that the removeRow button displays properly.
3. Interact with any cell's autocomplete (click on the autocomplete arrow, and select an option).
4. Hover over any row header and observe that the removeRow button _doesn't_ appear.

I would expect that in step 4, the removeRow button would appear after hovering over the row header.

The problem code seems to be [here](https://github.com/handsontable/handsontable/blob/master/plugins/removeRow/handsontable.removeRow.js#L72), in your `unbindMouseEvents` function, where you call `eventManager.clear();`. The eventManager that you're calling only refers to the first handsontable that was created, not the eventManager of the `this` instance.

I was able to fix the issue by creating a new `removeRow` instance for each handsontable. You can check out my fix [here](http://jsfiddle.net/wuwnw2xs/1/).

**Comment by AMBudnik** [comment]
Thank you very much for additional information. I got the same result that you described.
I'll mark this issue to be reviewed by our developers. 

Thank you for sharing the demo and for your effort @YourDeveloperFriend

**Comment by budnix** [comment]
Confirmed, this is a bug. After editing some values in Handsontable external plugin RemoveRow stop working.

**Comment by AMBudnik** [comment]
The issue is still replicable.

Here is an updated demo (0.38.1/1.18.1) http://jsfiddle.net/rvmuuaar/

**Comment by AMBudnik** [comment]
Since the v1.11.0 removeRow plugin has been deleted
