### ISSUE TITLE
Mousewheel scrolling on fixed columns not working

### ISSUE THREAD

**Issue by LarsVonQualen** [handsontable/handsontable#3686]
Hi, i've noticed that vertical scrolling doesn't work when you target a fixed column, but fixed rows works great.

I'm using Chrome on OS X, haven't checked if this is a general issue yet, but it should nevertheless still work in Chrome on OS X.

The issue is present in the latest demos: https://docs.handsontable.com/0.26.1/demo-fixing.html

Move the cursor over the upper left cells and try scrolling, it doesn't scroll the HOT viewport, but the entire viewport instead. Now move the cursor over column C through AX, now it works as intended.

**Comment by AMBudnik** [comment]
Thank you for sharing this issue and for your effort to report it @LarsVonQualen 
I think that we can relate this issue to this one https://github.com/handsontable/handsontable/issues/3579

**Comment by LarsVonQualen** [comment]
Do you have an idea when we can expect a fix?

**Comment by AMBudnik** [comment]
The issue have to be reviewed by our developer first and then it can be added to the milestone. 

Currently the issues that will be in the next milestone are kept in the Backlog (at: https://github.com/handsontable/handsontable/milestone/61)
As you can see there are few `high priority` bugs that have to be fixed first. That's why it's really hard to tell when this issue will be fixed. 

You can track the Backlog and and Roadmap (at: https://trello.com/b/PztR4hpj/handsontable-roadmap-2016-login-to-vote-for-features) for fresh information.

**Comment by LarsVonQualen** [comment]
Have your developer had a chance to review this yet?

**Comment by AMBudnik** [comment]
Hi @LarsVonQualen 
Our devs have already read the issue but there are few other issues that they have to finish fixing before they can get into this one.

**Comment by AMBudnik** [comment]
hi @LarsVonQualen 
we're currently checking this case. Can you please share you grid settings? We just checked that without settings like `height` and `width` this issue doesn't occur.

**Comment by LarsVonQualen** [comment]
Sure, i've excluded my data and columns, as they hold sensitive information, and they are just dumb objects. We also haven't updated to the latest 1.7.x because of breaking changes, so we are stil at 1.6.0.

```javascript
{
   "data":[

   ],
   "startRows":5,
   "startCols":5,
   "rowHeights":37,
   "columns":[

   ],
   "cell":[

   ],
   "comments":false,
   "customBorders":false,
   "minRows":0,
   "minCols":0,
   "maxRows":null,
   "maxCols":null,
   "minSpareRows":0,
   "minSpareCols":0,
   "allowInsertRow":true,
   "allowInsertColumn":true,
   "allowRemoveRow":true,
   "allowRemoveColumn":true,
   "multiSelect":true,
   "fillHandle":true,
   "fixedRowsTop":0,
   "fixedRowsBottom":0,
   "fixedColumnsLeft":7,
   "outsideClickDeselects":true,
   "enterBeginsEditing":true,
   "enterMoves":{
      "row":1,
      "col":0
   },
   "tabMoves":{
      "row":0,
      "col":1
   },
   "autoWrapRow":false,
   "autoWrapCol":false,
   "copyRowsLimit":1000,
   "copyColsLimit":1000,
   "pasteMode":"overwrite",
   "currentRowClassName":"currentRow",
   "currentHeaderClassName":"ht__highlight",
   "className":"htMiddle",
   "stretchH":"none",
   "observeDOMVisibility":true,
   "allowInvalid":true,
   "allowEmpty":true,
   "invalidCellClassName":"error",
   "placeholder":false,
   "placeholderCellClassName":"htPlaceholder",
   "readOnlyCellClassName":"htDimmed",
   "commentedCellClassName":"htCommentCell",
   "fragmentSelection":false,
   "readOnly":false,
   "skipColumnOnPaste":false,
   "search":false,
   "type":"text",
   "copyable":true,
   "visibleRows":10,
   "trimDropdown":true,
   "debug":false,
   "wordWrap":true,
   "noWordWrapClassName":"htNoWrap",
   "columnSorting":true,
   "manualColumnResize":true,
   "mergeCells":false,
   "viewportRowRenderingOffset":"auto",
   "viewportColumnRenderingOffset":"auto",
   "disableVisualSelection":false,
   "trimWhitespace":true,
   "correctFormat":false,
   "preventOverflow":false,
   "observeChanges":true,
   "sortByRelevance":true,
   "filter":true,
   "filteringCaseSensitive":false
}
```

**Comment by AMBudnik** [comment]
Thanks @LarsVonQualen 

As we checked multiple examples this issue only occur for tables with set `width` and `height` and only for the following part of the table

![row-mis](https://cloud.githubusercontent.com/assets/10757813/19073933/efd0e388-8a3d-11e6-93fd-e8ac7f2d4dda.png)

Can you agree?

**Comment by LarsVonQualen** [comment]
Yes, exactly. It becomes a problem for us because our entire left side is fixed, which means that it's quite unfortunate that the user can't scroll in that area :-)

**Comment by jansiegel** [comment]
@swistach, when reviewing this issue you can also test if it works fine with the bottom corner overlay in the pro version.

**Comment by AMBudnik** [comment]
Hi @LarsVonQualen 
It was a lot of testing and fixing but finally we've released a fix. Can you check if it works for you?

**Comment by AMBudnik** [comment]
@LarsVonQualen 
I assume that it works fine now. If you would have any concerns or doubts please feel free to leave a comment.

**Comment by LarsVonQualen** [comment]
We're currently locked at v1.6.0, but i assume it will work fine once we upgrade to the newest version.

**Comment by AMBudnik** [comment]
OK, I understand. Hope that the update will be smooth and will fix all your issues.
Have a great day @LarsVonQualen
