### ISSUE TITLE
Issue with pasting data (Urgent)

### ISSUE THREAD

**Issue by varun-dev** [handsontable/handsontable#3687]
Hi,

If I have editor config false, pasting stops working if the table looses focus.

Here is a fiddle - 
http://jsfiddle.net/varun_dev/a54bgr6g/

Steps -
1. Paste some text in any cell
2. Focus on the input box below the table
3. Come back to the table
4. Try pasting some text in any cell

Please advise any temporary fix, this is really urgent for me.

Thanks
Varun

**Comment by AMBudnik** [comment]
thanks for sharing @varun-dev 
I can see that the data is pasted occasionally after we focus the input.

I tested the `instance.render()` with the `afterSelection` hook and the `outsideClickDeselects: false` with no success. 

I can see that there are some hooks triggered as the table sometimes is changing in the column widths but I have to investigate this case a little more. I'll be back with any investigation results.

**Comment by AMBudnik** [comment]
I can see that when we click the input we are no triggering the `beforeKeyDown` any more. It does not happen when we click any other non-Handsontable element on the site. Tried to add the hook manually but it doesn't do any favors.

**Comment by varun-dev** [comment]
@AMBudnik: really hoping that you guys can suggest some quick fix soon.

**Comment by swistach** [comment]
It'll be done in #4234

**Comment by swistach** [comment]
Hi @varun-dev,
Now this should work properly. Could you check it using new version of the Handsontable (0.33.0/1.12.0)? .

**Comment by varun-dev** [comment]
Unfortunately our team gave up on handsontable, it did not meet our performance targets :(

**Comment by AMBudnik** [comment]
Thank you for your feedback @varun-dev I hope we'd be able to meet your requirements in the future.
