### ISSUE TITLE
select all cells, then execute delete, if you have afterChange setting, the page will freeze at least 5s.

### ISSUE THREAD

**Issue by materliu** [handsontable/handsontable#3688]
as empty cell, if it's necessary to trigger afterChange?

**Comment by AMBudnik** [comment]
Hi @materliu 
Can you share a demo where we'll be able to replicate this situation?
I made a demo with a 100 x 100 table and I'm logging something in the console with an `afterChange` hook and it does not take so long.
Demo: http://jsfiddle.net/53L8w3un/

**Comment by materliu** [comment]
thx for reply,  @AMBudnik 
this occurs when we do some calc work in the afterChange method. We are developing an excel-as demo depending on Handsontable, and without RuleJS, we use formula-parser instead, so we detect = and calc =xxx input in the afterChange method.
you can see the demo:  http://p.dingfudata.com:89/s/n77veMn 
sorry to trouble you.

**Comment by materliu** [comment]
I feel confused with 'it's necessary to contain empty cell in the afterChange method'

**Comment by AMBudnik** [comment]
I have to say that your spreadsheet looks great!

I can see that it takes a while to get the result of a change but there's not much I can do without a live demo. 
At the Handsontable support we are working on online resource so if you could create a live demo in one of the following: JSFiddle, JSBin, CodePen I'd be happy to check if we can boost the performance.

When it comes to hooks, `afterChange` triggers the renderer which currently is called for each cell. Can can find it here http://jsfiddle.net/rs04aj47/ by opening the console. We are planning to add an ability to rerender only changed cell but there's no precise date for this task yet.

**Comment by materliu** [comment]
so thx, @AMBudnik 
I will try to do the calc in Web Worker, then to see if things get better.
Live demo is a little difficult，because we put so many business logic in afterChange callbacks.

**Comment by materliu** [comment]
I finally found where goes wrong, I new one Promise object for every change, and Promise's performance is bad as we all know. so thx @AMBudnik
