### ISSUE TITLE
Sorting only API enabled

### ISSUE THREAD

**Issue by helmutgranda** [handsontable/handsontable#3689]
There is no way to have sorting only through API only. I have additional functionality in each  header which becomes blocked once sorting is enabled due to header wrapping all the content and blocking any other interactivity.

**Comment by helmutgranda** [comment]
Although I would like to know if there is a method to fully disable the headers from sorting without having to add custom code I found an example of how to add listeners for elements on the headers:

http://docs.handsontable.com/0.26.1/demo-custom-renderers.html#page-header

**Comment by AMBudnik** [comment]
Hi @helmutgranda 
I saw that this questions were already added at: https://forum.handsontable.com/t/sorting-with-api-only/536 so I'm closing this issue and if anyone else is interested in this subject please leave your comments at the same address as well.
