### ISSUE TITLE
Hidden columns bug.

### ISSUE THREAD

**Issue by dstrozynski** [handsontable/handsontable#369]
When we hide some column: 

getDataAtCell method works on "visible" data
setDataAtCell works on "hidden" data
getData          works on "hidden" data

This is a bit inconsistent and leads to a nasty issue with column value reading. You can see it for example if you double-click any cell in the second column here: http://handsontable.com/demo/datasources.html#array-hidden Because of the reading error, your action will copy data from the third column instead of displaying the proper value from the second one.

Another thing is that when you hide the column, its header stays visible.

**Comment by AMBudnik** [comment]
Please try the updated [demo](http://handsontable.com/demo/datasources.html#array-hidden).
