### ISSUE TITLE
Render the existed cells during scrolling

### ISSUE THREAD

**Issue by Ginhing** [handsontable/handsontable#3690]
Can we have an option to skip the existed “<td>” rendering (in the renderCells method ) when user scroll table since these cells don't be modifyed ?

Say more,  in this situation: WalkontableOverlays#onTableScroll() --> … --> WalkontableViewport#createRenderCalculators() --> WalkontableTableRenderer#renderCells(), don't all the cells need to pass to the cellRenderer ?

**Comment by jansiegel** [comment]
Currently it's not possible. As Handsontable is really extendable, you can make any cell value depend on multiple different parameters. To be able to do that, we need to render all cells really freaquently.

We have, however, an "eco renderer" (or however you want to call it) in our backlog - it would make rendering single cells possible and should probably help you with this issue.
You can vote for this feature in our roadmap: https://trello.com/c/tD8qABSS/48-new-renderers-lazy-rendering-eco-rendering
