### ISSUE TITLE
Issue with manualColumnMover within modal windows (e.g. mdDialog)

### ISSUE THREAD

**Issue by maurerke** [handsontable/handsontable#3691]
There seems to be an issue with the setting "**manualColumnMove: true**" within modal windows. In our case, it is mdDialog (Angular Material Dialog). However, it seems that the same issue exists in a bootstrap modal.
The manualColumnMover-Div is not at the right position.
So unfortunately the user can not move a column.

See the fiddle (simple example with mdDialog) and the screenshot below:
http://jsfiddle.net/zd97ttpo/

![image](https://cloud.githubusercontent.com/assets/7819576/17374503/37af0e9e-59ad-11e6-92ce-fbf3615b52ff.png)

**Comment by AMBudnik** [comment]
Thanks for sharing @maurerke 
You're right - I was not able to find the columnHandler

**Comment by maurerke** [comment]
Fixed with Version 1.7.1 @AMBudnik

**Comment by AMBudnik** [comment]
Thank you very much for an update @maurerke
