### ISSUE TITLE
Handsontable edit on mobile device

### ISSUE THREAD

**Issue by anagas** [handsontable/handsontable#3694]
Hello,

i know that handsontable is not mobile friendly but is there a workaround that we can edit on mobile devices? 

Regards

**Comment by AMBudnik** [comment]
Hi @anagas 
We did not test and investigate events on mobile devices and tablets yet.
You could try to search for the same subject at [Stackoverflow](http://stackoverflow.com/questions/tagged/handsontable).

**Comment by anagas** [comment]
Hello,

thanks. Handsontable works on mobile devices in the version 0.24.3. If we switch now from 0.25 to 0.24.3 do you know some big issues?

**Comment by AMBudnik** [comment]
That's really interesting. I've tested in on iPhone 6 and you're right. I've tested: https://docs.handsontable.com/0.24.3/demo-scrolling.html and there we are able to edit a cell and in 0.25.0 (as in the newest 0.26.1) not.

Thanks for sharing @anagas 
We did not made any backward incompatible changes but no one was testing mobiles as well.

**Comment by anagas** [comment]
Hello,

i tried to degrade my handsontable pro version but i found no way. How do i degrade handsontable pro to version 1.3.4?

Thanks.

**Comment by AMBudnik** [comment]
Hi @anagas 
You can download an older version of Hadsontable PRO via _install_ tab on your _my.handsontable.com_ account.

![install-older-versions](https://cloud.githubusercontent.com/assets/10757813/17474489/669e3f7a-5d56-11e6-9604-ec673c165aed.png)

**Comment by AMBudnik** [comment]
issue fixed in 0.28.1 (https://github.com/handsontable/handsontable/issues/3750)
