### ISSUE TITLE
Disable numeric cell formatting

### ISSUE THREAD

**Issue by marc-antoinepelletier** [handsontable/handsontable#3695]
Hey,

I need to disable the numeric cell formatting, but I don't know how... I need to display the number exactly how the user enter them.

Handsontable apply by default a formatting === '0', and I can have number going with like 10 decimal or more..
I looked at numbrojs but I can't find a way to completely disable the formatting for a column..

Anyone has an idea ?

**Comment by AMBudnik** [comment]
Hi @marc-antoinepelletier 
Unfortunately this option is not supported yet.
This case was already mentioned at: https://github.com/handsontable/handsontable/issues/3645

If you would have any additional requests regarding this subject or any suggestions please share them at https://github.com/handsontable/handsontable/issues/3645

**Comment by eshivakumar878** [comment]
is this issue fixed or still open?

**Comment by AMBudnik** [comment]
Hi @eshivakumar878 
can you open a new ticket and provide more details about your request?
