### ISSUE TITLE
Vertical scrollbar missing in IE11 when using absolute positioning

### ISSUE THREAD

**Issue by Vaccano** [handsontable/handsontable#3696]
When I create a handsontable grid using absolute positioning the vertical scrollbar will not appear in IE11.

**Here is the JsFiddle that shows the issue:** 

>http://jsfiddle.net/Vaccano/uubL5azk/

If you run that in Chrome or Firefox you get a vertical scrollbar off to the side.

If you run in it IE11, there is no scrollbar.

**Comment by Vaccano** [comment]
I tried it with a flexbox and it fails in IE11 there as well:

> http://jsfiddle.net/449pL3jo/

Looks like if you don't set a fixed height, it will not work in IE11 :(

**Comment by AMBudnik** [comment]
Hi @Vaccano 
This issue has been already described here: https://github.com/handsontable/handsontable/issues/2924
where the author also provided a workaround (it was some versions before the newest but maybe it will help).
I'm closing this issue but if you would like to share any additional information please add them at https://github.com/handsontable/handsontable/issues/2924

**Comment by Vaccano** [comment]
The pull request fixed the issue.  Thank you pointing me to that!

Just out of curiosity, are there plans to accept that pull request?  I am asking because it has been open for 6 months and there have been two releases since then.

I lost a day and a half looking into this issue, and I hate to see others have the same issues.

**Comment by AMBudnik** [comment]
Our devs have to double check every line before they can push the changes but I will definitely suggest them to take a closer look at this pull request.
