### ISSUE TITLE
wordWrap=false doesn't prevent drop-down caret wrapping onto next row

### ISSUE THREAD

**Issue by armensg** [handsontable/handsontable#3698]
I'm using the word-wrap=false on the ngHandsontable directive. I can see that this correctly adds the 'htNoWrap' class onto all my table TD elements and the cells don't wrap. However this doesnt seem to apply to the dropdown caret arrow for cells with automcomplete/dropdown. The arrow wraps around expanding the entire row of the table. Is this a bug or a setting ??

![image](https://cloud.githubusercontent.com/assets/6030955/17477249/0feffeba-5d5c-11e6-96ea-8b76e4795381.png)

**Comment by AMBudnik** [comment]
Hi @armensg 
We already talked about this subject at https://github.com/handsontable/handsontable/issues/2464
and the author provided a workaround for this issue. You can find it at: http://jsfiddle.net/deenairn/8o1vt4zg/5/
If it won't come in handy in your project. Please leave additional request at https://github.com/handsontable/handsontable/issues/2464
