### ISSUE TITLE
Dynamically set the column, row as read only 

### ISSUE THREAD

**Issue by ram8reddi** [handsontable/handsontable#3703]
I am dealing with 50+ columns and in each column header there must be a button for lock/unlock(read only) column. Can you recommend a best way to set the column as read only without refreshing the grid, when a button in the header is clicked.
Similarly set the row as read only on click of the button present in the last/first column in each row.

**Comment by Nagle** [comment]
This may be helpful:
```js
// hot: main config
dropdownMenu: [ 'make_read_only',]
```

[demo-dropdown-menu.html](https://docs.handsontable.com/pro/1.5.1/demo-dropdown-menu.html)[...](https://github.com/handsontable/handsontable/blob/0d90e68560ac25aa82aa004e11f4717f30850325/src/plugins/contextMenu/predefinedItems/readOnly.js)

💯

**Comment by AMBudnik** [comment]
Hi @ram8reddi 

@Nagle gave a really good example.

I can just add that the `readOnly` state is added via meta data and you can modify it via `getCellMeta`/`setCellMeta` like in this example: http://jsfiddle.net/AMBudnik/b8cf0Lmr/
(extra tip: this will not rerender the table so to see the gray color for the `readOnly` cell you need to trigger the rendering manually via `instance.render()`).
