### ISSUE TITLE
mergeCells alignment/values issue

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3704]
**Demo**
http://jsfiddle.net/6ft786nr/1/

**Expected behavior**
When we merge the whole row we would expected to have only one value in the 2nd row.

**What we get**
Currently when the alignment is set to right or center we get 2 values for the same row (one in the fixed area and one in the rest of the table).

**Image**
![merge](https://cloud.githubusercontent.com/assets/10757813/17553247/24d6c2f0-5f05-11e6-94b5-de67951c7d25.png)

Zen 23899

**Comment by jansiegel** [comment]
I think it was made this way purposely. I'll remove the **Bug** label and add **To be discussed** instead.

**Comment by AMBudnik** [comment]
OK, thanks @jansiegel

**Comment by wojciechczerniak** [comment]
From #6543

---

Comment by @wojciechczerniak: The expected result is to display the content in both. But fixed overlay should trim it and the rest is visible in the main area:

![Screenshot 2020-07-07 at 14 04 35](https://user-images.githubusercontent.com/4718998/86778563-d0bf2980-c05a-11ea-9773-b6916766535d.png)

---

Use case by @AMBudnik 


When we fix columns and merge cells at the same time we may end up with ambiguous cell rendering.

![image](https://user-images.githubusercontent.com/10757813/70430334-ddef4800-1a7a-11ea-85a9-c2240a29a4c0.png)

Might it be better to remove (hide) the content under the `B` column and leave it like this

![image](https://user-images.githubusercontent.com/10757813/70430394-0119f780-1a7b-11ea-9fa9-9dbca9e4ebd5.png)


### Steps to reproduce

1. Just check the demo

### Demo

https://jsfiddle.net/bqn3Lxau/ 

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 78
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **MergeCells grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
