### ISSUE TITLE
beforeRowResize and beforeColumnResize currentRow param issue

### ISSUE THREAD

**Issue by jbrunette** [handsontable/handsontable#3705]
beforeRowResize and beforeColumnResize should return the index of the column being resized, the new size, and whether it was done via double-click.

However, instead of the column index, the first param is the new size (as is the second param).

 https://jsfiddle.net/5anoq2pd/

**Comment by AMBudnik** [comment]
Thanks for sharing @jbrunette 
I got the same result. The `after` hooks are working fine for this operation but `before` are showing size instead of an index.

**Comment by gresspav** [comment]
Already reported :-)
https://github.com/handsontable/handsontable/issues/3328
https://github.com/handsontable/handsontable/issues/3662

**Comment by AMBudnik** [comment]
that's correct. Thanks for your investigation @gresspav 
@jbrunette please track changes to https://github.com/handsontable/handsontable/issues/3328 for updates

**Comment by imageslr** [comment]
Hi @AMBudnik  , in version 7.1.0 and "@handsontable/react": "^3.0.0" still have this problem. The `after` hooks are working fine but `before` are providing size as first param instead of index.

**Comment by AMBudnik** [comment]
Hey @imageslr 

this issue can be trackable here https://github.com/handsontable/handsontable/issues/3328 (still opened).

**Comment by AMBudnik** [comment]
Hi @jbrunette @imageslr @gresspav the referenced issue has been reported as solved in v 8.0.0
