### ISSUE TITLE
Handsontable inside JQuery Modal - Double Scrollbars

### ISSUE THREAD

**Issue by g0nP** [handsontable/handsontable#3706]
I have a handsontable inside a JQuery modal dialog with fixed height.

When the handsontable has enough records, I want to scroll through it using ONLY the JQuery scrollbar.
Here is my table:

$("#tblPlayers").handsontable({
data: Array,
maxCols: 3,
maxRows: Array.length,                             
renderAllRows: true,
columnSorting: true
});

If I use  $("#tblPlayers").css("overflow", "hidden") the table doesn't appear. If I inspect the page with F12 it's there, but somehow it isn't displayed.

Any ideas on how can I get to render the whole handsontable without scrollbars so as to only use the scrollbars of its parent container (the JQuery dialog)?

**Comment by AMBudnik** [comment]
Hi @g0nP 

Can you create a JSfiddle? It would be much easier to test.

**Comment by AMBudnik** [comment]
I'm closing this issue as there was no reply for more than 2 weeks but if you're still seeking for a solution just give me a hint and we'll reopen the ticket.
