### ISSUE TITLE
Question: Is it possible to temporarily disable events?

### ISSUE THREAD

**Issue by armensg** [handsontable/handsontable#3707]
Hi - I am trying to programatically populate my table using setDataAtCell() after a change event. This function seems to fire off the event again so I want to know if its possible to temporarily disable table events while data is being set. I couldnt find anything in the api docs relating to this :(

Thanks
Armen

**Comment by AMBudnik** [comment]
Hi @armensg 
Unfortunately it's not recommended to pause the events as they are triggering in cascade mode. If you would like to load more data at once maybe you could use the [`loadData`](https://docs.handsontable.com/pro/1.5.1/Core.html#loadData) method.
If you could share more details about the project I'd be happy to help.

**Comment by armensg** [comment]
Hi Aleksandra - thanks for letting me know. The main objective is to populate an entire/partial row given inputs in 1 or more columns in that row. All cells/most cells will have a callback that fires whenever a cell changes to retrieve default values for the rest of the columns in that row. Currently I am using setDataAtCell() to populate an entire row but this fires all the events for the cells being populated which should only really fire if changed by the user. In any case right now I am using the check to avoid running redundant code


```
            var onAfterChange =  function(changes, source){
                //console.log(changes, source);
                if (!changes)  return;
                if (source !== "edit" && source !== "autofill")  return; // fired because of another event so dont process.
```

**Comment by AMBudnik** [comment]
Thanks for sharing details Armen.
I was thinking about your example and I guess that using the attributes of `afterChange` is the only decent way. I didn't saw any demo (which would be helpful) but as I wrote before pausing events doesn't always end with desired results.

**Comment by ChandraAdapa10** [comment]
Hi AMBudnik,

Can we stop the mouse event while edit in progress.
Below is the issue description we are facing 
we need to highlight a cell with color when the value has changed in a cell, we are trying to apply color using setCellmeta but before this triggers if a user a click on other cell, the color is applying for latest selected cell, instead of this we need to apply the color for the value change cell. can you please suggest us, how we can handle this in handsontable.

Thanks.

**Comment by AMBudnik** [comment]
Hi @ChandraAdapa10 

you may need to create a custom editor. Any of our current built-in editors do not have this functionality.
If you'd like to continue this conversation please send me an email support@handsontable.com as this topic releases to a different task and it is 4 y.o.
