### ISSUE TITLE
export to csv with header

### ISSUE THREAD

**Issue by tonylinyy** [handsontable/handsontable#3709]
hi,I am using handsontable pro,is it possible to export to csv with header?
I read the doc,but not found,thanks~~~

**Comment by tonylinyy** [comment]
sorry,the problem is webpack not handsontable
handsontable has the function
close the issue!

**Comment by aRealCat** [comment]
exportPlugin.downloadFile('csv', {filename: 'MyFile',columnHeaders: true});
