### ISSUE TITLE
copy cell issue when fragementSelection: 'cell'

### ISSUE THREAD

**Issue by yuwong** [handsontable/handsontable#3710]
Please note the copy cell feature only works once if fragementSelection is set to 'cell'.
(essentially your Example JSFiddle but with fragementSelection: 'cell')

http://jsfiddle.net/qpmtbzgb/

Test case:
Copy the cell containing 'Euro', paste into 'Japanese Yen' works
Then copy 'Pound Sterling', paste into 'Swiss Franc', it is still pasting in 'Euro'
- repeat if necessary, it seems it works again if you "leave" the grid by clicking outside or switching to different tab.

Issue observed on OSX Chrome + Firefox

**Comment by AMBudnik** [comment]
Thanks for share demo and the details @yuwong 
I got the same result. I'm marking this issue as a bug.
ps. I was testing it little more and here's a simplified example: http://jsfiddle.net/b6fmsf8q/

**Comment by swistach** [comment]
It'll be done in #4234

**Comment by yuwong** [comment]
cheers!

**Comment by swistach** [comment]
Hi @yuwong, could you check this issue using new version of the Handsontable?

**Comment by swistach** [comment]
I think we can close this issue. 
If you notice this bug, feel free to reopen.

**Comment by yuwong** [comment]
Thanks, looks good
