### ISSUE TITLE
Autofill doesn't follow minSpareRows

### ISSUE THREAD

**Issue by jrowen** [handsontable/handsontable#3711]
You can see this in the example table here: http://docs.handsontable.com/0.26.1/tutorial-quick-start.html.  Highlight the last row and drag down; new spare rows are added to the end of the table.  Also see https://github.com/jrowen/rhandsontable/issues/95.

**Comment by AMBudnik** [comment]
Hi @jrowen 
Can you share more details about this request?
I'm not sure if I'm thinking about the same behavior. You would like the fill handle not to add new rows?

**Comment by jrowen** [comment]
Adding new rows is fine, but the spare rows are not desired.  The fill handle doesn't seem to follow the `minSpareRowsNumber`.

**Comment by AMBudnik** [comment]
Hm... I've tried it with the `minSpareRows: 3` with this demo: http://jsfiddle.net/Lnp4btfz/ and got desired result

![min-spare-rows-example](https://cloud.githubusercontent.com/assets/10757813/18127341/2068e2d0-6f80-11e6-99ef-ae0653eb52c2.gif)

I'm not sure how to replicate the behavior that you had.

**Comment by jrowen** [comment]
In your demo, change to `minSpareRows: 0`, highlight the last row, and then drag it down (to add a new row, same as the last row).  When I do this, the table automatically adds a spare row to the end, and in this case, I don't want the spare row to be added.

**Comment by AMBudnik** [comment]
Ok so now I understand. Thanks for sharing additional details @jrowen

**Comment by AMBudnik** [comment]
The following issue is no longer replicable. Please update your Handsontable version.
