### ISSUE TITLE
Mark thread as "passive"?

### ISSUE THREAD

**Issue by halfnibble** [handsontable/handsontable#3712]
Chrome Warning:

> Handling of 'wheel' input event was delayed for 181 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.

Despite the spelling error, is this an optimization that handsontable must make, or can we implement passive event handlers on our end?

**Comment by HolgerJeromin** [comment]
BTW the spelling error was [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=623769)

**Comment by samsonkhisty** [comment]
@AMBudnik Any update on the above. I was also interested in enhancing the scroll experience for handsontable in my projects.

**Comment by lobosan** [comment]
Same here, please give us some guidance on how to improve this. Thanks

**Comment by AMBudnik** [comment]
Hi guys, sorry for the late response!
When it comes to this statement @halfnibble it's only a browser suggestion (not actually an error).
@samsonkhisty @lobosan there are few issues already marked as a perfomanance related and if you are experiencing lagging in [any other browsers than IE and Edge](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Core%3A+performance%22) please create a demo.

**Comment by AMBudnik** [comment]
I'm closing this issue cause the lack of reply for 2 weeks but feel free to leave any suggestion.
