### ISSUE TITLE
Support Class Factory Pattern

### ISSUE THREAD

**Issue by Vaccano** [handsontable/handsontable#3715]
The entities that I want to show in the datagrid cannot be just created.  I need to create them in a special way.

It would be nice if the grid had a callback like `beforeRowCreate` that will allow me to create the entity that is the row and return it.

**Comment by AMBudnik** [comment]
thank you for that suggestion @Vaccano 
the same case was already added to https://github.com/handsontable/handsontable/issues/2624 so if you would like to track updates regarding this issue please check the following.
