### ISSUE TITLE
ZeroClipboard always required

### ISSUE THREAD

**Issue by pawelhalasa** [handsontable/handsontable#3719]
According to the documentation, HOT requires contextMenuCopyPaste config item in order to use ZeroClipboard plugin. However, if I don't want to use it and don't include ZeroClipboard.js file to my app, HOT anyway displays the following error in the console: 
`Uncaught Error: Cannot find module 'zeroclipboard'`

Is there any simple way to exclude this not needed dependency in a way that it doesn't display any error?

**Comment by AMBudnik** [comment]
Hi @pawelhalasa 
unfortunately if you want to use the contextMenuCopyPaste the ZeroClipboard has to be included.

**Comment by pawelhalasa** [comment]
Sorry for late reply. I'm not using contextMenuCopyPaste feature, yet I still get the above error.

**Comment by AMBudnik** [comment]
Hi again @pawelhalasa 
Even if you're not using it but it was included into your build you still need to have it. Please take a minute to check this tutorial: https://docs.handsontable.com/pro/1.7.0/tutorial-custom-build.html
