### ISSUE TITLE
Manual Column Move handle position is not correct when opened in bootstrap modal

### ISSUE THREAD

**Issue by tanveerrafiqueIVL** [handsontable/handsontable#3720]
Manual Column Move handle's position is not correct when you try to open it in modal. Please see the fiddle.
http://jsfiddle.net/09uh2ysj/

**Comment by AMBudnik** [comment]
thanks for sharing the description and the demo @tanveerrafiqueIVL

**Comment by swistach** [comment]
Hi @tanveerrafiqueIVL 
With new `manualColumnMove` moving seems ok. Can you confirm this?
Updated demo: http://jsfiddle.net/09uh2ysj/2/

**Comment by AMBudnik** [comment]
Seems fine now.
I'm closing this issue @tanveerrafiqueIVL but feel free to leave your feedback.

Thanks again for sharing.
