### ISSUE TITLE
Comments on fixed rows are not displayed

### ISSUE THREAD

**Issue by KodjoSuprem** [handsontable/handsontable#3721]
Comments on fixed rows are not displayed or displayed at a wrong place.

I mentioned this problem in [#2278](https://github.com/handsontable/handsontable/issues/2278)
The issue is closed but the bug still exists

Check this jsfiddle using HoT 0.26.1 [https://jsfiddle.net/6cgtyx3q/2/](https://jsfiddle.net/6cgtyx3q/2/)

**Comment by AMBudnik** [comment]
thanks for sharing @KodjoSuprem 
I think that we should relate this issue to this one: https://github.com/handsontable/handsontable/issues/3081

**Comment by AMBudnik** [comment]
same issue continued at: https://github.com/handsontable/handsontable/issues/2608
