### ISSUE TITLE
selection area gradiant image overrides current cell background image

### ISSUE THREAD

**Issue by KodjoSuprem** [handsontable/handsontable#3722]
Selecting cells add the "area" class to td elements wich adds a background image (a gradient).
This background overrides any background image already added with custom cell formaters

Exemple:

![image](https://cloud.githubusercontent.com/assets/4376260/17860149/aae0061e-688c-11e6-81af-a7c2ff2b1c09.png)

I think the selection area background should be added more carefully and take in account the existing cell style.
For exemple by appending the background gradiant to the existing cell's background image list

**Comment by AMBudnik** [comment]
Hi @KodjoSuprem 
I've made an example with `cells` method that adds the new class to 2nd row with a yellow background: http://jsfiddle.net/bgm9dye3/ and after selection it's still yellow. Can you share a demo that shows your example?

video:
![new-class-selection](https://cloud.githubusercontent.com/assets/10757813/18123729/7d3a5248-6f6f-11e6-8dad-79cf5940eb27.gif)

ps. I've added the background color to the new class by using the `!important` hack.

**Comment by KodjoSuprem** [comment]
@AMBudnik 
Thank your helping.

In your exemple 

```css
.newClass {
  background: yellow !important
}
```
will override 

```css
.handsontable td.area {
  background: linear-gradient(to bottom,  rgba(181,209,255,0.34) 0%,rgba(181,209,255,0.34) 100%);
}
```
And it is not what I want.

(check this demo : http://jsfiddle.net/3dejepop/)
![image](https://cloud.githubusercontent.com/assets/4376260/18125554/179c59a6-6f77-11e6-8b9e-c0d787310bb9.png)

The selected area should always **overlay** any cell background.

Since, I have made a workaround by overrideing the `draw()` method from `WalkontableSelection`.
The tricky thing is that the selection css is reset in src/3rdparty/walkontable/src/table.js :285 with `this.removeClassFromCells()`.
In my opinion removing selection css classes for td elements should be managed by the `WalkontableSelection` class, just like the adding not outside from it.
Would make things more consistent and also in my case make the hack easier to write.

Maybe I will do a pull request when I got time.

Here the workaround code.

[https://gist.github.com/KodjoSuprem/61d07701bc9cd8cd1fea9993ffe96903](https://gist.github.com/KodjoSuprem/61d07701bc9cd8cd1fea9993ffe96903)

```javascript
Handsontable.hooks.add('beforeInitWalkontable', function (walkontableConfig) {
    var areaSelection = walkontableConfig.selections.area;
    var oldDraw = areaSelection.draw;
    var olAddClassAtCoords = areaSelection.addClassAtCoords;
    areaSelection.draw = function (wotInstance) {
        var nodes = wotInstance.wtTable.TABLE.querySelectorAll('.custarea');
        for (var i = 0, len = nodes.length; i < len; i++) {
            var TD = nodes[i];
            TD.removeAttribute("style"); //use this for IE
            wotInstance.wtTable.removeClassFromCells("custarea");
        }
        oldDraw.call(this, wotInstance);
    };

    areaSelection.addClassAtCoords = function (wotInstance, sourceRow, sourceColumn, className) {
        var TD = wotInstance.wtTable.getCell(new WalkontableCellCoords(sourceRow, sourceColumn));
        var FF = "-moz-linear-gradient(top,  rgba(181,209,255,0.34) 0%, rgba(181,209,255,0.34) 100%)"; /* FF3.6+ */
        var chrome = "-webkit-linear-gradient(top,  rgba(181,209,255,0.34) 0%,rgba(181,209,255,0.34) 100%)"; /* Chrome10+,Safari5.1+ */
        var opera =  "-o-linear-gradient(top,  rgba(181,209,255,0.34) 0%,rgba(181,209,255,0.34) 100%)"; /* Opera 11.10+ */
        var ie  = "-ms-linear-gradient(top,  rgba(181,209,255,0.34) 0%,rgba(181,209,255,0.34) 100%)"; /* IE10+ */
        var w3c_selection_gradient_css = "linear-gradient(to bottom,  rgba(181,209,255,0.34) 0%,rgba(181,209,255,0.34) 100%)"; /* W3C */
   
        if (typeof TD === 'object') {
            var TDcomputedStyle = document.defaultView.getComputedStyle(TD, null);
            if (TDcomputedStyle.backgroundImage.indexOf("linear-gradient") < 0) {
                TD.style.backgroundImage = TDcomputedStyle.backgroundImage + ", " + w3c_selection_gradient_css;
            }
        }

        olAddClassAtCoords.call(this, wotInstance, sourceRow, sourceColumn, "custarea"); // add a custom class to track selected sells (because selection.className will be erased before calling draw())
    };

});
```

**Comment by AMBudnik** [comment]
OK, I understand now. 
ps. if you would like to create a pull request please remember to add it to the `develop` cause we are not merging changes directly from `master`.
