### ISSUE TITLE
Context Menu Odd Behavior When Handsontable is at Bottom of Page

### ISSUE THREAD

**Issue by gtiguy92** [handsontable/handsontable#3725]
See [video](https://db.tt/eo5skEyb). Opening the context menu at the bottom of a table when the table is at the bottom of a page produces some strange results. It looks like the container for the context menu is sized larger than the context menu itself, which causes the vertical scrollbar to display. Scrolling down and then trying to close the context menu by clicking on a cell causes a strange multi-selection effect, which can be seen in the video.

**Comment by samsonkhisty** [comment]
#3207

**Comment by AMBudnik** [comment]
thanks for sharing @gtiguy92

**Comment by gtiguy92** [comment]
Thanks @samsonkhisty ! Your workaround worked like a charm and also solved another issue that I've reported. I'll paste your snippet on the other issue as well.

**Comment by AMBudnik** [comment]
hi @gtiguy92 
what was the other issue that you've mentioned?

**Comment by gtiguy92** [comment]
Hi @AMBudnik 
Yep, #3724 is the other issue I mentioned in my previous post.

**Comment by AMBudnik** [comment]
thanks for your feedback @gtiguy92 
I'm closing https://github.com/handsontable/handsontable/issues/3724

**Comment by AMBudnik** [comment]
I'm moving all the improvement suggestions to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Please feel free to leave any additional comments and reflections.

Thanks in advance!

**Comment by AMBudnik** [comment]
This issue should no longer be replicable using Handsontable v8.4.0. However, if it does, please leave a comment or contact me at support@handsontable.com
