### ISSUE TITLE
ATAN2 should have number_y first, then number_x

### ISSUE THREAD

**Issue by charliema07** [handsontable/handsontable#3727]
to comply with Excel and original Math.atan2 standards, y variable should be passed first and x variable should be passed second.
Refer to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2.

Thank you

**Comment by AMBudnik** [comment]
thank you for a suggestion @charliema07

**Comment by AMBudnik** [comment]
The issue has been redirected to the [Wiki section / Improvement suggestions(https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

**Comment by AMBudnik** [comment]
The new formula plugin defines the order to X, then Y as proposed
> https://github.com/handsontable/hyperformula/blob/7ff3ab7888b7bab7aec9555620c3edf16f5b148d/docs/guide/built-in-functions.md
