### ISSUE TITLE
click Event for button in colheaders is not triggering in angular 2

### ISSUE THREAD

**Issue by JayasreeKiran** [handsontable/handsontable#3728]
Need to implement some functionality on click of button in headers of handson table. 
I am able to place button in header but click event is not triggering. if nay one came across this issue please provide solution

**Comment by AMBudnik** [comment]
Hi @JayasreeKiran 
We did not switched to Angular 2 yet. 
If you would like us to focus on this task in next quarter please vote for this idea: https://trello.com/c/k0jNZPHv/25-nghandsontable-angular-2-0-support

**Comment by JayasreeKiran** [comment]
can we achieve this in angular 1??

**Comment by AMBudnik** [comment]
the demo was already added at: https://github.com/handsontable/handsontable/issues/3738
