### ISSUE TITLE
Formatting table when using the  removeRow plugin

### ISSUE THREAD

**Issue by janekolszak** [handsontable/handsontable#3729]
How can I remove/format one cell in the header of the table when using _removeRow_ plugin?

I mean this one cell in the top-left of the table:
http://docs.handsontable.com/0.26.1/demo-custom-buttons.html

**Comment by AMBudnik** [comment]
Hi @janekolszak 
You can overwrite the styling for the first element (first header). Here's an example: http://jsfiddle.net/wetw6cjs/
Maybe it's not the most elegant solution but it doesn't interfere with the js code - it's safe to use.
