### ISSUE TITLE
FF dateFormat formatting issue

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3731]
**Demo**: https://jsfiddle.net/roxanalupu1981/4bz6st1w/3/

**Checked with**: Chrome 51, FF 48 and Edge, reproducible only on FF.

**Description**:
In FF incorrect date is not formatted, according to docs:
`If you enable the correctFormat config item, the dates will be automatically formatted to match the desired format.`
_src: https://docs.handsontable.com/pro/1.5.1/demo-date.html_

**How to replicate**:
1. Copy the string `09-16-2016` that represents a date in incorrect format.
2. Paste it to any cell in the last column

**Expected behavior**:
![good](https://cloud.githubusercontent.com/assets/10757813/18051618/f1c76eb4-6df5-11e6-844a-a17b6333dcdd.png)

**Behavior in FF**:
![bad](https://cloud.githubusercontent.com/assets/10757813/18051653/356b39ac-6df6-11e6-8cdb-0b89dabd3998.png)

**Comment by AMBudnik** [comment]
The issue remains the same for Handsontable version 0.35.1 using Firefox 58

**Comment by AMBudnik** [comment]
Still works the same in v 5.0.1

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/6085

**Comment by swistach** [comment]
It's a piece of #6085. I think we can close this one to not duplicate the same issue.
