### ISSUE TITLE
Improper column stretching.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3732]
In some cases the column stretching results in mismatched column headers and the table. 
It happens when a vertical scrollbar is present at the start of the rendering process, but it's no longer needed after rendering the stretched table.

For example: http://jsfiddle.net/js_ziggle/ue0czxeh/3/

**Comment by varun-dev** [comment]
I am still seeing this bug in 0.29.0

http://jsfiddle.net/varun_dev/40d33crc/

In the demo, please click on the button at the top to change data from 1000 rows to 5 rows and you will notice the header issue.

**Comment by AMBudnik** [comment]
Hi @varun-dev 
thanks for sharing, I can see what you mean.

As this issue has already been merged with some commits and it's closed I've added your Fiddle to a new issue https://github.com/handsontable/handsontable/issues/3925
