### ISSUE TITLE
Clear() before first render breaks v0.26.0

### ISSUE THREAD

**Issue by ichpuchtli** [handsontable/handsontable#3733]
Version 0.26.0 (free version)

Calling clear breaks before the table is first rendered or interacted with breaks. 

I'm using `loadData([])` to get around it at the moment. 

```
Uncaught TypeError: Cannot read property 'startRow' of null(…) 
getFirstVisibleRow  @   handsontable.full.js:5181 
setRangeEnd @   handsontable.full.js:6714
setRangeStart   @   handsontable.full.js:6701
selectAll   @   handsontable.full.js:6889
Core.clear  @   handsontable.full.js:7384
```

**Comment by AMBudnik** [comment]
Hi @ichpuchtli 
Can you guide me on how to get the console errors?
I've made this example: http://jsfiddle.net/xvdf5ko1/ but it works as expected.

**Comment by jsiali** [comment]
Hi @AMBudnik 

I've made this JSFiddle to see these errors : http://jsfiddle.net/xvdf5ko1/1/

**Comment by AMBudnik** [comment]
thanks @jsiali 
I think that we're getting this error cause there's no data loaded yet when we want to access it to erase.
I'm leaving this issue to be checked by other team members.

**Comment by swistach** [comment]
Hi @ichpuchtli,
If I understand you correctly, you would like to clear each cell after calling `beforeRender`? `beforeRender` is running after any change made on a cell as well when a rendering of virtual cells is triggered.
