### ISSUE TITLE
Add numeric limitations to docs

### ISSUE THREAD

**Issue by bungcip** [handsontable/handsontable#3734]
Step to reproduce:
1) open https://docs.handsontable.com/pro/1.5.1/demo-numeric.html
2) copy this number: 9117060812420001
3) paste it on year column.
4) I expected 9117060812420001, but it got 9117060812420000 instead.
<img width="290" alt="a" src="https://cloud.githubusercontent.com/assets/72723/18083694/5c09e76a-6ece-11e6-952b-573683c3d2d0.png">

**Comment by passionke** [comment]
+1  

another example: we input 422202199007181356, but got 422,202,199,007,181,376

**Comment by AMBudnik** [comment]
thanks for sharing @bungcip  @passionke

**Comment by AMBudnik** [comment]
Hi @bungcip @passionke I was just provided with a tip from @swistach and actually we are not able to handle this kind of operations cause of the language limitations. Here's more information about this subject: http://www.w3schools.com/js/js_numbers.asp
If we're missing some crucial information in this subject please leave a comment. Till it happens the issue will stay closed.

**Comment by bungcip** [comment]
I think adding documention about javascript number limitation in https://docs.handsontable.com/pro/1.5.1/demo-numeric.html is the right way.
Also the documentation must add warning to not use 'numeric' type if you just want to limit column value to digit only. ( yes, I already bitten by this bug in our website. )

**Comment by AMBudnik** [comment]
I surely agree with @bungcip 
We should add this information.

**Comment by budnix** [comment]
Documentation was updated, thanks!
