### ISSUE TITLE
handsontable performance issue in large data.

### ISSUE THREAD

**Issue by KennethanCeyer** [handsontable/handsontable#3735]
I need to handle large data (more than 100,000 rows) on handsontable.

but this is cruelly slow, i think the reason is that handsontable deal all of data after is is loaded.

we need more optimized vesion for  better performance. (it has to be able to handle data more than 1000000 rows ).

other solutions solve this problem by making users to handle only scrolled data.

any similar feature on this? or do pro version support it?

thank you for your time.

**Comment by AMBudnik** [comment]
Hi @KennethanCeyer 
have you already checked our [performance tips](https://docs.handsontable.com/pro/1.5.1/tutorial-performance-tips.html)?

Here's a basic table with 100 000 rows and 10 columns: http://jsfiddle.net/o5ovx2ct/ 
Does your table load/work slower than this one? If so, please create a demo and I'd be happy to take a look at it and maybe speed up the performance.

**Comment by KennethanCeyer** [comment]
Awesome!

I could solve this problem

by changing handsontable version included in jsfiddle what you give.

Thank you for your help!

**Comment by AMBudnik** [comment]
you're welcome @KennethanCeyer
