### ISSUE TITLE
Allow multiple OR values for contains?

### ISSUE THREAD

**Issue by helmutgranda** [handsontable/handsontable#3737]
I believe this will be a clone of issue #3660 but may already be implemented or in the works. 

Basically we need the same filter functionality as `by_value` but for `contains`. Currently we can only filter by one value in `contains` unless there is a work around which I will gladly take.

**Comment by AMBudnik** [comment]
That's a good idea @helmutgranda 
I'm adding it to the `feature` list. Thanks!

**Comment by AMBudnik** [comment]
We're moving this topic to our [Feature-requests section](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by helmutgranda** [comment]
Hi @AMBudnik,

What is the priority on the Feature-request section? I was able to develop an internal filtering solution that supports multiple OR values for contains and standard filtering, however if we can use what you all develop as part of the platform that would be best.

**Comment by AMBudnik** [comment]
The higher priority is always meant to [HP bugs](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+high%22) but sometimes those bugs can be fixed via some new solutions (from feature-request or improvement-suggestion section). Usually we firstly fix the bugs and then continue with proving new solutions.

**Comment by wszymanski** [comment]
@helmutgranda Please check out [this comment](https://github.com/handsontable/handsontable/issues/3660#issuecomment-314442875).
