### ISSUE TITLE
click Event for button in colheaders is not triggering

### ISSUE THREAD

**Issue by JayasreeKiran** [handsontable/handsontable#3738]
with reference to #3728 issue(click Event for button in colheaders is not triggering in angular 2), can we achieve the same in angular 1??

If we can achieve this angular 1 please let me know the how can we do it.

Thanks in advance

**Comment by AMBudnik** [comment]
hi @JayasreeKiran 
currently we do not have a similar example but I should be able to come back to you with one before the end of this week. We just need to test some solutions first.

**Comment by AMBudnik** [comment]
hi again @JayasreeKiran 
thanks to @swistach I was able to deliver you this demo: http://jsbin.com/voqodon/1/edit?js,console,output
Each button logs a different message in the console.
