### ISSUE TITLE
[Improvement suggestion] Add a minimum custom column width for each column

### ISSUE THREAD

**Issue by viqtor1** [handsontable/handsontable#3739]
In my application I wanted the ability to set a minimum value for stretch for individual columns when stretching the table. The option stretch: 'all' does not offer the desired behavior - sometimes you want some columns to not shrink below a certain point, while others can shrink with no problem. 
In order to achieve this, I set the width of the table based on the parent div of the table (and recalculate this on the window resize event) and recalculate the width for each column based on their minimum column width. You can check my code here: [link](http://jsfiddle.net/viqtor91/ue0ckzcg/1/)
The only issue I'm having with this is that stretch:"all" version is more flexible because you can dynamically resize the container, and the table will update the width itself.
Can you guys insert this into the framework, and work your magic to optimize it and make sure that the width is adjusted dynamically based on the parent div?
Thank you, and let me know what you think.

**Comment by AMBudnik** [comment]
Pretty cool idea @viqtor1 
thanks for sharing!

**Comment by AMBudnik** [comment]
Topic moved to [Improvement-suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

**Comment by AMBudnik** [comment]
I am moving this conversation to Github Discussions and welcome everyone to discuss an expected behavior for that use case.
