### ISSUE TITLE
Emptying cells removes rows and columns

### ISSUE THREAD

**Issue by provegard** [handsontable/handsontable#374]
I'm trying out 0.8.3, and found that when I empty all cells in the table by pressing Delete, the table is reduced to a single cell. 

I can reproduce it using the "default" fiddle in both Firefox and Chrome: http://jsfiddle.net/warpech/hU6Kz/

Just press Ctrl-A and then Delete.

Is this expected behavior? Or is it configurable in some way?

**Comment by dmpatel-bca** [comment]
I did something like this:

var gridData = hot1.getData();
var cleanedGridData = {};

$.each( gridData, function( rowKey, object) {
    if (!hot1.isEmptyRow(rowKey)) cleanedGridData[rowKey] = object;
});
