### ISSUE TITLE
Fill-handle disappears for dropdown-type cells

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3741]
Fill-handle disappears for dropdown/autocomplete cells when you navigate down through them using <kbd>Enter</kbd> key.

**Steps to reproduce the problem:**

1. Go to http://jsfiddle.net/nv5cxhb2/
2. Focus on C1 ("black")
3. Press <kbd>Enter</kbd> twice (or more)

Result:
Lack of fill handle: https://gyazo.com/bf5b5d77850ea91d80d2e31d2e20e622

:information_source:
> Handsontable 0.26.1
> Windows 8.1
> Chrome

**Comment by swistach** [comment]
It's duplicate of #2230

**Comment by AMBudnik** [comment]
Released: 0.28.4
