### ISSUE TITLE
Uncaught TypeError: numeral.validate is not a function

### ISSUE THREAD

**Issue by AmorimJ** [handsontable/handsontable#3743]
Some times Chrome gives this error when I try to change values in Handsontable numeric cells.
Someone knows the solution for this?
Best regards

**Comment by AMBudnik** [comment]
Hi @AmorimJ 
Can you provide us a live example (for example in the JSFiddle) where we will be able to replicate the same log?

**Comment by AmorimJ** [comment]
Hi @AMBudnik unfortunately i can't replicate it in JSFiddle.
I'm using handsontable integrated in a tool called Splunk, and in the past in Splunk version 6.2 I didn't have this problem but after updating Splunk to version 6.4 this problem started to occur but only with type numeric.
I will try other options and I will check if the problem can be caused by other thing.
Best regards

**Comment by AMBudnik** [comment]
I do not know this tool but it looks like the data distribution may have been changed. You can try to log some data to check if the types are correct.

**Comment by AmorimJ** [comment]
Yes it's what I will do. Thanks
