### ISSUE TITLE
Combine date cell type with another validator

### ISSUE THREAD

**Issue by armensg** [handsontable/handsontable#3745]
I want to have a date cell type that provides the user with the date picker. But I also want to be able to enter a certain type of string (eg "1Y" or "1M") and do some custom validation on that. Can anyone give some pointers on how to achieve this; is it even possible? Not sure how to use a custom cell renderer with the date picker.

Thanks

**Comment by AMBudnik** [comment]
Hi @armensg 
With the current structure it won't be easy. Formatting is done by the moment.js: http://momentjs.com/docs/#/parsing/ so you would need to overwrite it
