### ISSUE TITLE
Position of pikaday not working with HOT

### ISSUE THREAD

**Issue by nitz88** [handsontable/handsontable#3747]
Hi,

Please check this [fiddle](http://jsfiddle.net/nitz_88/23pwdytz/1/).
Like

```
{
        type: 'date',
        dateFormat: 'MM/DD/YYYY',
        correctFormat: true,
        defaultDate: '01/01/1900',
        // datePicker additional options (see https://github.com/dbushell/Pikaday#configuration)
        datePickerConfig: {
            // First day of the week (0: Sunday, 1: Monday, etc)
             position : 'top right',
             reposition : false
        }
}
```

I have given some position which is not taken. Am I doing something wrong or i am passing wrongly ?

Thanks.

**Comment by AMBudnik** [comment]
as far as I can see we are not passing the `position` option in the `getDatePickerConfig` function (but I may be wrong).

Thanks for sharing @nitz88

**Comment by nitz88** [comment]
Thanks for response.
After posting here, i thought of same so checked lib code then found out same.

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/3957

**Comment by jgbishop** [comment]
Is there any outlook on this being fixed? This is an annoyance that would be great to resolve.

**Comment by AMBudnik** [comment]
The issue has been redirected to the[ Wiki section / feature requests](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
