### ISSUE TITLE
afterChange doesn't tell you which table is firing the event

### ISSUE THREAD

**Issue by armensg** [handsontable/handsontable#3748]
I have multiple HO tables on my page. I need to do specific logic depending on the table being modified. i can see from afterChange docs the parameters to the event dont have the table name or id or anyhthing like that. Am i missing something? this seems like a basic use case?

http://docs.handsontable.com/0.15.0-beta3/Hooks.html#event:afterChange

Name	Type	Description
changes	Array	
2D array containing information about each of the edited cells [[row, prop, oldVal, newVal], ...]

**Comment by AMBudnik** [comment]
You're right @armensg 
as a result of the `afterChange` you are able to get this values `[[row, prop, oldVal, newVal], ...]` but it doesn't mean that you can make some extra operations like referring to the [core element.](http://jsfiddle.net/18kf6fan/). If you could share more details about your request I'd be happy to help.

**Comment by armensg** [comment]
Thanks AB. Doing extra operations on the table ( core element) like setting values in othe cells based on the input is exactly the types of operations I need to do.

**Comment by AMBudnik** [comment]
when it comes to dependencies like you wrote 

>  setting values in othe cells based on the input

[here's](http://jsfiddle.net/pqebfy2b/) a cute little demo that I've made today. It also tracks the content of one cell and adds something to another. Maybe it will come in handy :)
