### ISSUE TITLE
Add Image to other Column when I changed/edited a Column

### ISSUE THREAD

**Issue by chaucv93** [handsontable/handsontable#3749]
Ex: I have a table like this. I want when I change or edit in a ID/First Name Col => isEdited Col have a image. Can anyone help me or give me idea ?  Thank you very much !

```
  | Id | First Name | isEdited |
  |----------------------------|
  | 1  | Isaac      |          |
  | 2  | Robert     |          |
```

**Comment by AMBudnik** [comment]
Hi @chaucv93 
You can - for example - use the `afterChange` with `setDataAtCell`, here's an example: http://jsfiddle.net/4sxfgqyr/
and in this demo I'm also adding a code that erases the image if the name is erased as well: http://jsfiddle.net/m2k9cx4g/

**Comment by chaucv93** [comment]
Thank you so much @AMBudnik  <3

**Comment by chaucv93** [comment]
Hello @AMBudnik 

Can you explain for me why I must use : 
```
afterChange: function (changes, source) {
        if (source !== 'loadData') {
            hot.setDataAtCell(changes[0][0], 8, isEdited, 'loadData');
        }
    },
```

if I use ` hot.setDataAtCell(changes[0][0], 8, isEdited);` =>Error !

**Comment by AMBudnik** [comment]
Hi @chaucv93 

`hot.render()` is a method that rerenders the table view. Sometimes the logic made via some method require an extra rerendering to display results.
____________________________

The `afterChange` callback allows us to easily access two attributes: `source` which is a string representation of what happened that the value is changed, it can return:

`one of the strings: "alter', "empty', "edit', "populateFromArray', "loadData', "autofill', "paste".`

The second attribute is `changes`, that represents an array of 4 records.
1) Row of the cell that has been changed
2) Column of the cell that has been changed
3) Value that was before change
4) Value after change

In the example I added an exception to run the code for all the changes that were lot made while loading the data into the table:

`source !== 'loadData'`

The `setDataAtCell()` method is used to change data in a single cell. It takes 3 required and 1 additional arguments. The arguments are: (row, column, data_to_put, source_of_change).

When it comes to this line of code:

`hot.setDataAtCell(changes[0][0], 8, isEdited);`

I do not know that is the `isEdited`. If you could share a JSFiddle demo with this error it would be easier to spot what's causing this error.
