### ISSUE TITLE
Can't edit cells on mobile devices

### ISSUE THREAD

**Issue by Jaibles** [handsontable/handsontable#3750]
In Chrome, on any mobile device I can't edit any cell in the handsontable.
(Can replicate if I toggle the Toggle Device toolbar on Chrome developer tools too).

I'm also experiencing this issue on the handsontable website: https://handsontable.com/examples.html

Is anyone having similar issues?

_The only clue I've found is that if I remove the `ht_master` class using the dev tools it resolves the issue. http://upload.visible.vc/2S1u0c0N3L1h_

**Comment by AMBudnik** [comment]
Hi @Jaibles 
Unfortunately Handsontable is not mobile friendly yet, please check the [known limitations](https://docs.handsontable.com/pro/1.6.0/tutorial-known-limitations.html)

**Comment by krzysztofspilka** [comment]
@swistach I'm reopening this issue due to the problems with the backwards compatibility, especially seen on mobile devices.

**Comment by AMBudnik** [comment]
Hi @Jaibles 
We've been testing new fix a lot and it seems that it's working fine however I would really appreciate your opinion as well.

Thanks in advance!

**Comment by Jaibles** [comment]
@AMBudnik all seems to be working perfectly like it did before! thanks :)

**Comment by AMBudnik** [comment]
Great! Thanks for your prompt reply and wish you a wonderful weekend.
