### ISSUE TITLE
Suggestion required: Conditional rendering massive cell performance 

### ISSUE THREAD

**Issue by stanleyxu2005** [handsontable/handsontable#3751]
I'm using 0.27 to render a table. The number of rows are fixed, but table cells will be updated, when data is updated (like a plane time table). I am using customer renderer to do that. The performance is fine, until I tried to render more than 1000 rows.

Here is my code (simplified)

```
var columnSchema = [
    {data: 'name', title: 'Name'},
    {data: 'value', title: 'Value', renderer: 'myValueRenderer', format: '0.00'},
    {data: 'status', 'title: 'Status', renderer: 'myStatusRenderer'},
    {data: 'date', title: 'Date'}
];

function MyValueRenderer(instance, td, row, col, prop, value, meta) {
  if (meta.hasOwnProperty('previousValue')) {
    if (meta.previousValue > value) {
      $(td).addClass('value-down-animation');
    }
    else if (meta.previousValue < value) {
      $(td).addClass('value-up-animation');
    }
  }
  meta.previousValue = value;
  return Handsontable.renderers.NumericRenderer.apply(this, arguments);
}

function MyStatusRenderer(instance, td, row, col, prop, value, meta) {
  switch (value) {
    case 'ok':
      $(td).removeClass('not-ok-td').toggleClass('ok-td', true); 
      break;
    case 'not-ok':
      $(td).removeClass('ok-td').toggleClass('not-ok-td', true); 
      break;
  }
  return Handsontable.renderers.TextRenderer.apply(this, arguments);
}

Handsontable.renderers.registerRenderer('myValueRenderer', MyValueRenderer);
Handsontable.renderers.registerRenderer('myStatusRenderer', MyStatusRenderer);

var container = document.getElementById('table');
var table = new Handsontable(container, {
    data: tableData, // array of json data
    manualColumnResize: false,
    readOnly: true,
    columns: columnSchema,
    copyable: true,
    renderAllRows: false
});

setTimeout(function() {
    var diff = getChangedCells(table.getData(), newTableData);
    if (diff.length > 0) {
      table.setDataAtRowProp(diff);
    }
}, 2000);
```

I think the code is okay. I dont know, whether my code is the right way to do conditional formatting. Could you please advise?

I tried to set `renderAllRows:false; height:500`. This will help to improve performance, but I have some problem to calculate the accurate height of the table (fit client area) dynamically, so I give up this solution.

**Comment by AMBudnik** [comment]
Hi @stanleyxu2005 
Unfortunately the 1000 rows is currently a max value for fast performance operations. You should be able to take more rows but in most cases it's better to split the rows and call the same methods for packages of data.

**Comment by stanleyxu2005** [comment]
Okay. I'm trying to redesign the table to be a paginated table. Thanks.

**Comment by stanleyxu2005** [comment]
Using a fixed height is a smart solution,, but I still have some issue with that. 

I use animation (fade in fade out) for rowl background color. When table uses fixed height, and I scroll the table. The fade in fade out effect will randomly applied to wrong row. 

For instance row #2 is expected to turn red, during the animation period, I scroll down to row 100, the row s around 100 will turned red and then becomes normal. I'm thinking disable animation during scrolling. But it is a bit complicated. Am I doing wrong?

**Comment by AMBudnik** [comment]
Hi @stanleyxu2005 
Can you share a demo with your recent progress?

**Comment by stanleyxu2005** [comment]
@AMBudnik Sorry for the late reply. I managed to increase performance by specifying a table height.

**Comment by AMBudnik** [comment]
Great! Thanks fr sharing an update @stanleyxu2005 
I guess we can close this issue.
