### ISSUE TITLE
"Filter by value" behavior works opposite from what is expected

### ISSUE THREAD

**Issue by drywolf** [handsontable/handsontable#3752]
Hi,

When I go to the [filter demo site](https://docs.handsontable.com/pro/1.3.3/demo-filtering.html), the default behavior when filtering for text values did not match what i was expecting to get.

For example if I filter for "e" in the first column like that and press `Ok`...
![image](https://cloud.githubusercontent.com/assets/394294/18387257/df8d7352-769b-11e6-8915-c46b97bc29ce.png)

nothing will be filtered in the table...
![image](https://cloud.githubusercontent.com/assets/394294/18387324/48c02086-769c-11e6-9973-cc494c7f310a.png)

I would have expected that only the rows containing the elements from the first screenshot will be displayed after the filtering.

I guess handsontable currently does in a way the oppositve behavior from what I would have expected. Namely it allows to search for elements that match the entered text-pattern, and then the user has to explicitely disable the elements that he does not want (via the `checkboxes`).
So he has to actually search for the elements that he wants to be **excluded**, not search for the ones that he is looking for (which is the more standard behavior for text searching anywhere else IMO).

Is this a missunderstanding of the filtering concept on my side ? Is there a configuration that allows to achieve the opposite behavior that I explained above ? Or is this a change / new feature that would yet have to be integrated ?

PS: Is there currently also no button/action to reset all checkboxes for the custom/value filter ?

Thanks

**Comment by AMBudnik** [comment]
Hi @drywolf 
We wanted to create the same behavior as it is in Google Docs, that's why you firstly need to `clear` the content of the options that are currently selected (all are by default).

![clear](https://cloud.githubusercontent.com/assets/10757813/18387653/20fc7c96-769e-11e6-833d-04514cd088fa.png)

ps. It was gone in the version that you have linked, please choose the 1.6.0 - https://docs.handsontable.com/pro/1.6.0/demo-filtering.html

**Comment by drywolf** [comment]
Thanks for the quick reply.

I didn't recognize that the docs were of a previous version :laughing: Thanks for pointing that out.

About the text-filter experience ... is there a way that I could customize the behavior to be in line with what I want ?

e.g. 3 user actions

    --> click column filter button
    --> enter filter text
    --> click ok
    --> grid is filtered


instead of 5 user actions

    --> click column filter button
    --> click 'clear'
    --> enter filter text
    --> click 'select all'
    --> click ok
    --> grid is filtered

**Comment by AMBudnik** [comment]
As far as I'm concerned you still will need to click on the desired filtered option, but you can clear automatically all the values, http://jsfiddle.net/zxu70kr4/

**Comment by drywolf** [comment]
I guess what this issue really is about is the customizability of the filter menu for columns.
I'm looking into the pros/cons of transitioning from Kendo Grids to HandsOnTable and therefore I am comparing the features.

And as far as I can tell Kendo Grid has more options for customizing the Column Filter menus (e.g. [see their demo](http://demos.telerik.com/kendo-ui/grid/filter-menu-customization) --> `filterable` options in the grid column configs)

Could such custom filter behavior (as described above) also be done in HandsOnTable with reasonable effort ? If so, how would I approach that ?

Thanks

**Comment by AMBudnik** [comment]
Hi @drywolf 
Currently for the dropdown menu there's an ability to pick preferred items but the filtering by condition is a package

![condition](https://cloud.githubusercontent.com/assets/10757813/18543677/4f1fca5a-7b31-11e6-8200-00a536eef095.png)

Of course that there is always a workaround but the ability to easily set only (for example) `begins with` filter and `ends with` is not available yet.

**Comment by chethan1095** [comment]
Hi all can we filter the data based on dates for ex: i want to filter data between two dates only between these two dates what and all data are present should display it

**Comment by AMBudnik** [comment]
Hi @chethan1095 
here is a set of filters for date column http://jsfiddle.net/d8phbq2r/

As I assume the default `before`/`after` filters is what you need

![image](https://user-images.githubusercontent.com/10757813/35095035-6eb14b08-fc47-11e7-9ef8-4b785ffc64d8.png)

**Comment by chethan1095** [comment]
Thank you @AMBudnik

**Comment by AMBudnik** [comment]
You're welcome :)

**Comment by mayanksaurabh** [comment]
Hi,
Can we have a feature in the filter(filter_by_value) in which we can define which values should be selected in the dropdown? By default, all the values are selected, but in my case, I wanted only some value to be selected. 
![handson](https://user-images.githubusercontent.com/19463877/89524212-c9c63b00-d801-11ea-81df-4d68446a7f84.png)
In this pic, I want that "In-ReExpression" should not be selected by default and its values only appear when I select it.
Will really appreciate the help .
Thanks

**Comment by AMBudnik** [comment]
Hi @mayanksaurabh I guess that we have spoken on the emails yesterday but if anyone else is also looking for the same functionality let me paste my reply.

Currently, there are two options

- all are selected (default)
- none are selected http://jsfiddle.net/wy133cgy/6/

The filtering plugin does not provide any public API to modify the list of values or to change their state (checkbox).
