### ISSUE TITLE
afterSelection doesn't tell me which table is being selected

### ISSUE THREAD

**Issue by armensg** [handsontable/handsontable#3753]
afterSelection event (And other table events in general) have some very important missing functionilty which is to include the instance (or id) of the firing table in the callback parameters. I think this is a huge limitation with regards to having multiple tables on 1 page; I'm sure many users will find this helpful. =D Thanks

**Comment by budnix** [comment]
Hi @armensg, In Handsontable you can detect which instance has fired an event using one of two approaches:

1. You can add listeners to the separate Handsontable instances. [Demo](http://jsfiddle.net/v7593xjg/).
2. You can add listeners once (globally) and then check which instance has fired the hook using function context (`this.`). [Demo](http://jsfiddle.net/72uoqbcg/2/).

This works with any hook you defined.
