### ISSUE TITLE
Rowspan and select headers?

### ISSUE THREAD

**Issue by PhpSriptKiddie** [handsontable/handsontable#3754]
Thank you for a fantastic project.

I can't figure out how to merge rowheaders/set rowspan. How would I merge the rowheaders in the following?

[Example](http://rallen.dk/newtable2.php)

Also - what's the small line in the bottom of the rowheaders, and why can I only select the first colheader (Header1) and not the second one (Header2)?

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 
Currently you cannot merge headers of rows. This feature will appear in the alpha version (planned to tomorrow). Now you can only merge headers of columns, demo: http://jsfiddle.net/nLqohj5z/

**Comment by PhpSriptKiddie** [comment]
Thankes. What about the fact that I can only select first colheader (header1) and not header2 in my example?

**Comment by AMBudnik** [comment]
The ability to select only the top most level of the table is actually a bug.

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 
we just changed the behavior we've been talking about. Please check if now it works as expected.

**Comment by AMBudnik** [comment]
I'm closing this issue due to lack of additional bug reports regarding this fix but feel free to leave a comment or create a new topic if needed.
