### ISSUE TITLE
Custom renderer doesn't always get called

### ISSUE THREAD

**Issue by armensg** [handsontable/handsontable#3756]
I have defined a custom cell renderer for ngHandsontable dynamic columns. I am generating the table object in a an angular service and then storing it in local storage. 

When the table is generated renders are applied to the columns with dropdown type. The service returns the table info and the table is rendered as expected. If I then refresh the page, the table is resolved into the controller from localStorage. When this table is rendered it works exactly as expected but for some reason the renderer on the cells doesnt fire... Please let me know if the explanation is not clear ill try to clariffy. Any thoughts appreciated.

```
var dropdownRenderer = function(instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.AutocompleteRenderer(instance, td, row, col, prop, value, cellProperties);
    $(td).children(".htAutocompleteArrow").remove();
};
```

`
$scope.blotter = blotter; // comes from router resolve
`

  ```
                      <hot-table
                            hot-auto-destroy
                            hot-id="blotter" 
                            settings="{colHeaders: colHeaders, className: 'htCenter', contextMenu: ['row_above', 'row_below', 'remove_row'], afterChange: blotter.afterChange, afterRender: blotter.afterRender, afterInit: blotter.afterInit, afterSelection: blotter.afterSelection, afterOnCellMouseOver: blotter.afterOnCellMouseOver}" 
                            row-headers="false" 
                            min-spare-rows="minSpareRows"
                            columns="blotter.columns" 
                            datarows="blotter.rows" 
                            word-wrap="false">
                                <!-- use dynamic columns so we can use custom cell renderers ... -->
                        </hot-table>
  ```

**Comment by armensg** [comment]
So i realised that the 'renderer' field attached to the column was being lost. Does it get removed after the column renders?

**Comment by motin** [comment]
@armensg My bet is that this issue should be reported to https://github.com/handsontable/ngHandsontable
Or, if you can re-create the issue without using ngHandsontable, update this issue with such information.

**Comment by AMBudnik** [comment]
Thanks for your help @motin 
That is correct, please share the issue at https://github.com/handsontable/ngHandsontable

**Comment by motin** [comment]
As a side note, an alternative to ngHandsontable is https://github.com/neam/angular-simple-handsontable which is a simpler wrapper aimed to allow inclusion of Handsontable in angular projects while not introducing wrapper-specific bugs nor performance issues.

**Comment by AMBudnik** [comment]
Hi @motin 
We'd be happy to see how it works. Do you have any demo? (the one from readme is broken)

**Comment by motin** [comment]
The URL from the readme works: http://jsbin.com/vareba/edit?html,js,output
However, I see that the link was wrong in the readme, fixed now.

Med vänliga hälsningar,
Fredrik Wollsén
Neam AB <http://neam.se/>

*Email*: fredrik@neam.se
*Web*: http://neam.se
*LinkedIn*: http://www.linkedin.com/in/fredrikwollsen
*Mobile*: +46 (0) 70 40 50 930
*Skype*: fredrik_motin
*Twitter*: @fredrik_motin <https://twitter.com/#!/fredrik_motin>

On Fri, Oct 7, 2016 at 11:46 AM, Aleksandra Budnik <notifications@github.com
