### ISSUE TITLE
Undo/redo in active editor modifies value of the previous cell which was edited

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3757]
#### Steps to reproduce:
1. Go to: http://jsfiddle.net/a0v73og3/
2. Open editor in A2
3. Enter `222` at the end and press <kbd>ENTER</kbd>
4. Open editor in A3
5. Enter `333` at the end and press <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd>
#### Result:
- Value of A2 is changed to `A2` - bug
- Value of active editor is changed to `A333`

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by swistach** [comment]
Solved in #6017
