### ISSUE TITLE
Opening dropdown editor reverts previous value

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3759]
#### Steps to reproduce:
1. Go to: http://jsfiddle.net/0mo2b9do/
2. Select `C1`
3. Press <kbd>DELETE</kbd> or <kbd>BACKSPACE</kbd>
4. Press <kbd>ENTER</kbd>
#### Result:

Removed value is set in the editor.

**Comment by PYYuriy** [comment]
have the same problem

**Comment by AMBudnik** [comment]
@PYYuriy 
This should be fixed. Can you check that please?

**Comment by AMBudnik** [comment]
As there is no reply for a week I guess we can close this issue.
@PYYuriy feel free to leave a comment if something isn't working right. Thanks!
