### ISSUE TITLE
autocomplete editor XSS vulnerability

### ISSUE THREAD

**Issue by jeffrey-martin-92** [handsontable/handsontable#3761]
There's an XSS vulnerability (and general usability issue) in the "autocomplete" editor when the supplied list to autocomplete contains user-provided inputs. Steps to reproduce:
1) set the metadata on a cell to include:

```
editor = "autocomplete"
source = ["AA<img src=\"sdfsdf\" onerror=\"alert(1)\">AA"]
```

2) The error will fire when the editor is used.

This represents a usability issue even when XSS is not a problem because `<b>Foo</b>` will show up as `Foo` bolded in the autocomplete but as `<b>Foo</b>` in the cell when the autocomplete is used.

**Comment by AMBudnik** [comment]
thank you for sharing @jeffrey-martin-92 
I leave this issue open for our devs to look at

**Comment by budnix** [comment]
Confirmed, autocomplete editor has an XSS vulnerability. I've prepared demo at https://jsbin.com/qavixaqive/2/edit?html,js,output. 

I suggest to add new options for an autocomplete and dropdown editor such as `stripHtml/stripTags` which will be enabled by default.

**Comment by budnix** [comment]
Fixed in this [commit](https://github.com/handsontable/handsontable/commit/06ba00530ea309f2ef448bfee17f7f230afeddd4). It will be a **breaking change**, all autocomplete/dropdown source items are stripped from HTML tags by default. It can be changed by passing `allowHtml: true` option into handsontable settings.

**Comment by AMBudnik** [comment]
Glad we've added this issue to our newest release.
Again thanks for sharing @jeffrey-martin-92
