### ISSUE TITLE
dist files still include numbro language configurations, contrary to bac97a7

### ISSUE THREAD

**Issue by mattmccutchen** [handsontable/handsontable#3762]
In preparation for making modifications to Handsontable, I rebuilt the `dist/` files for Handsontable 0.28.0 myself and saw unexpected diffs:

1. My `handsontable.full.js` does not include the numbro language configurations, consistent with bac97a7, but [the original one](https://github.com/handsontable/handsontable/blob/0.28.0/dist/handsontable.full.js) does.  I'm pretty sure this is a mistake.  The only way I can imagine it happening is if the person who did the release failed to update hot-builder to 0.5.2 in their working tree as required by `package.json`.
2. My `handsontable.full.js` includes the latest versions of numbro (1.9.3) and moment (2.15.0), consistent with normal `npm install` behavior based on the version ranges in `package.json`, but the original one includes numbro 1.8.0 and moment 2.13.0.  I thought this might be intentional, especially because the versions used match the lower bounds in `package.json`, but given that at least one thing definitely went unexpectedly with the release process, I thought it would be worth mentioning here.

You may want to make sure these issues are corrected in the next release.

**Comment by jansiegel** [comment]
Hi @mattmccutchen,

you're right, these are some thing I must have overlooked during the release of this version. They will be definitely updated with the next released version.
Thanks a lot for noticing it!

**Comment by AMBudnik** [comment]
Hi @mattmccutchen 
we've yet released a new version were the issue no longer occur.
Thanks again for your effort.
