### ISSUE TITLE
manualRowMove function has a bug

### ISSUE THREAD

**Issue by xfliu138** [handsontable/handsontable#3763]
If I am a row for the color processing, when I drag a row up and down, this feature is no problem.
`if (row === 4) {
                  cellProperties.renderer = greenRenderer; // uses function directly
                }`
![image](https://cloud.githubusercontent.com/assets/18605877/18621171/19b598c6-7e52-11e6-86eb-b633650cfaf6.png)
But if I set up the following conditions after, when I drag a row up and down, this function will appear the following questions
`var tempCellValue=hot.getDataAtCell(row, 0);
						if(tempCellValue=="A8"){
							cellProperties.renderer = greenRenderer; // uses function directly
						}`
![image](https://cloud.githubusercontent.com/assets/18605877/18621209/8aa1af0c-7e52-11e6-86fb-2aff064cf291.png)

**Comment by AMBudnik** [comment]
Hi @xfliu138 
I've made a similar demo: http://jsfiddle.net/L9031re8/
Can you guide me please how to replicate the issue step by step?

**Comment by xfliu138** [comment]
I have modified the code of this page, you can try to drag the row to try,the following code is my add

var tempCellValue=this.instance.getDataAtCell(row, 0);
      if(tempCellValue==="A5"){
      		cellProperties.renderer = greenRenderer;
      }

**Comment by AMBudnik** [comment]
Thanks for sharing @xfliu138 
It's definitely something regarding renderers as when I've passed another renderer via `else` statement moving works as expected, example: http://jsfiddle.net/406rcdat/

**Comment by AMBudnik** [comment]
hi again @xfliu138 
our developers checked above demos and they came to the conclusion that we were missing an action of resetting the cell meta value. In this updated demo http://jsfiddle.net/882nn12m/2/ non of reported issue occur.

**Comment by xfliu138** [comment]
@AMBudnik Thank you, help me to perfect solved this problem。
