### ISSUE TITLE
Wrong validation with separators other than dot and comma

### ISSUE THREAD

**Issue by sirhaplo** [handsontable/handsontable#3765]
In italian the dot for thousands is rarely used.
Dot and Comma are often interchangeable for numeric immission, so 2,3 or 2.3 is ok.
But if i input 2.3 numbro take out my dot cause is considered thousand delimitator.

So i changed italian thousand delimitator with " " so it dont interfere with my immision.

But handsome ignore that.
In handsometable.full.js there is a validation wrong :

`if (!val.match(/[^\d.,]/g)) {`

it should be something like that : 
```
var _delimitersRegEx = new RegExp("[^\d" + _thousandSep + _decimalSep + "]","g");	
if (!val.match(_delimitersRegEx)) {
```

But also that is prone to errors in case of separators that become part of the regexp ( like '-' ).
I dont know how to write a correct regexp, but i think this should be implemented

**Comment by AMBudnik** [comment]
Thank you for your suggestion @sirhaplo 
I will mark it as an improvement suggestion and as a subject for our developers to look at.

**Comment by jansiegel** [comment]
@sirhaplo, We've had some numbro-related adjustments in the last releases, I'm guessing it might have fixed it.
Could you take a look at this demo? http://jsfiddle.net/js_ziggle/LLq9fzta/

Regardless if I enter `10.5` or `10,5` into the editor, the result is always `10,5`. Is this what you're trying to achieve?

**Comment by sirhaplo** [comment]
It seems to work properly.
I input with point or comma and it visualize always with comma.
And it save all data with point ( before that patch it used to save as you digited ) 
Nice work. 
Thank you all.

**Comment by AMBudnik** [comment]
Thanks for help @jansiegel and @sirhaplo for sharing this interesting example.
As everything works fine now I'll allow myself to close the ticket.
