### ISSUE TITLE
Disable render to improve setDataAtCell() performance

### ISSUE THREAD

**Issue by armensg** [handsontable/handsontable#3766]
I have a small table (15 by 20) that gets populated programatically when user inputs values in certain cells. I use the setDataAtCell() and I'm experiencing some serious delay between that function being called and the cells actually rendering. I get the sense that this is because there is a core.render() call every time setDataAtCell() i used. Any chance we can add a flag to setDataAtCell() to disable rendering or any other proposed method until all cells are renderered? I see that there is a populateFromArray() function but this is painful to use as it seems that the arrya needs to be contigious and my inputs are not.

**Comment by AMBudnik** [comment]
Hi @armensg 
Please check the latest comment at https://github.com/handsontable/handsontable/issues/1061#issuecomment-248358274
