### ISSUE TITLE
Handsontable move row functions in IE have this bug

### ISSUE THREAD

**Issue by xfliu138** [handsontable/handsontable#3771]
I will be embedded into HTML page in the iframe, then move the row operation function, the shadow position is wrong
![image](https://cloud.githubusercontent.com/assets/18605877/18776089/5e05b6c4-8199-11e6-8e2e-d9d53b4d4257.png)
The html code is
`<body>
 <br /><br />
  <iframe id="btmFrm" width="100%" height="700px" name="bottom" src="column_move.html" scrolling="auto" frameborder="0"></iframe>
 </body>`
Other browser(chrome, firefox) environment is ok,Only under the IE has this bug

**Comment by AMBudnik** [comment]
Hi @xfliu138 
Can you also create a Fiddle? It would be much easier to test the case.

**Comment by xfliu138** [comment]
Hi @AMBudnik 
This situation requires two pages would appear, so I don't know how to create this test case on the Fiddle.
Home page is very simple, only one iframe element, nested demo column_move.html.And demo column_move.html I don't have any changes on it.
You can copy the following code in your local is can see again


`<html>
<head>
  <title>Document</title>
 </head>
 <body>
 <br />
 <br />
  <iframe id="btmFrm" width="100%" height="700px" name="bottom" src="column_move.html" scrolling="auto" frameborder="0"></iframe>
 </body>
</html>`

**Comment by AMBudnik** [comment]
Hi @xfliu138 
and what is your column_move.html?

**Comment by xfliu138** [comment]
Hi @AMBudnik 
Column_move.html is from handsontable download the sample code
https://docs.handsontable.com/0.28.0/demo-moving.html?_ga=1.82300127.834438728.1463729944

**Comment by AMBudnik** [comment]
I've tried to replicate the following case but I wasn't able to get the issue.
Could you maybe share a .gif that will show the issue?

**Comment by xfliu138** [comment]
Hi @AMBudnik 
Under the IE11 open the following url
http://jsfiddle.net/api/post/library/pure/
Before clicking the first column for drag and drop operation,The effectiveness of dislocation in can see below
![image](https://cloud.githubusercontent.com/assets/18605877/18866081/d0731adc-84d0-11e6-9a37-12e2b737fff5.png)

**Comment by AMBudnik** [comment]
Hi @xfliu138 
unfortunately your Fiddle is empty.

**Comment by xfliu138** [comment]
Hi @AMBudnik 
Sorry, the url is wrong, can from this url to enter
https://docs.handsontable.com/0.28.0/demo-moving.html?_ga=1.82300127.834438728.1463729944
Then click the edit button in a web page, you can enter the page Fiddle

![image](https://cloud.githubusercontent.com/assets/18605877/18866319/014b5d6c-84d2-11e6-9c9a-1f6fb6b255fe.png)

**Comment by xfliu138** [comment]
Hi @AMBudnik 
Access to this URl also can see the effect
http://jsfiddle.net/hdqf3x4p/

**Comment by AMBudnik** [comment]
Thank you very much @xfliu138 
I was able to replicate the issue. 

It is IE11 (the same for Edge). Working as expected on Chrome and FF.

![row_move](https://cloud.githubusercontent.com/assets/10757813/18869560/1ba4495a-84ad-11e6-83aa-bc6cac3dc4bd.gif)

**Comment by xfliu138** [comment]
Hi @AMBudnik 
So I hope you can help to solve this problem, thank you very much

**Comment by AMBudnik** [comment]
Still replicable in v 0.34.3 in IE 11 (Win 10) and Edge. It happens using minimal settings. We need to fix it soon.

**Comment by AMBudnik** [comment]
This issue has been produced with the moveRow UI change in v `0.27.0`. In [v `0.26.1`](http://jsfiddle.net/n0xym84r/) where we used a handle to move rows the issue did not occur.

**Comment by AMBudnik** [comment]
Hi @xfliu138 

As [support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

This issue works as expected for the 8.0.0-beta2-rev15 on Windows 10 and the latest Edge so we can call it closed as fixed.

<img width="370" alt="correct" src="https://user-images.githubusercontent.com/10757813/85008105-c9dc7f80-b15c-11ea-8cbe-c948097042a9.png">
