### ISSUE TITLE
updateSetting resets column/row order in the manualColumnMove/manualRowMove

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3774]
#### Steps to reproduce:
1. Go to: http://jsfiddle.net/bbcvs8ah/
2. Change column/row order.
3. Click on `UpdateSettingsBtn`.

#### Result:
`updateSettings` resets column/row order.

**Comment by abhinavsarja** [comment]
Hi , This fix is there in which version?
I am facing this issue now

**Comment by wojciechczerniak** [comment]
Hi @abhinavsarja. Please, create a new issue. Thanks

**Comment by AMBudnik** [comment]
Hey @abhinavsarja that is a really old version - `0.28.1`. 
If you're using a newer version please create a new issue with a demo or send it to me at support@handsontable.com

**Comment by abhinavsarja** [comment]
@AMBudnik ,

New issue #6349 is raised for the same.
https://github.com/handsontable/handsontable/issues/6349

**Comment by AMBudnik** [comment]
Thank you @abhinavsarja
