### ISSUE TITLE
Date column width not adjusting

### ISSUE THREAD

**Issue by juanmas07** [handsontable/handsontable#3775]
Trying to auto adjust the width of all date columns, but it breaks the content in two rows. I look with no luck for a way to auto adjust this width
 
<img width="319" alt="screen shot 2016-09-26 at 2 14 58 pm" src="https://cloud.githubusercontent.com/assets/2141907/18844460/b0e0acd0-83f3-11e6-825a-b4ac1d9ae2c4.png">

also, double click on the column resizer, does this same issue

**Comment by AMBudnik** [comment]
Hi @juanmas07 
I've made a similar example: http://jsfiddle.net/v6n79d58/ and when I click the resize handler table adjusts its widths accordingly to the content.

![column-date](https://cloud.githubusercontent.com/assets/10757813/18863706/082180e2-8493-11e6-8367-6b6f113b2372.gif)

Do you have any additional styling in your table?

**Comment by AMBudnik** [comment]
I'm closing this issue as there was no additional information or a demo for 2 weeks.
