### ISSUE TITLE
Can I set an Object data to cell ?

### ISSUE THREAD

**Issue by liy-cn** [handsontable/handsontable#3776]
well, I need set an Map Object to cell, when I access the cell ,I can retrieve the Map and get some values. 
now ,I use the `var cell = hot.getCell(row,col)` then use `jQuery(cell).data("k","v");`to set and get data. 
Can I use some more convenient api such as `hot.setCellDataObject(row,col,obj)`? Will you do it in next version of handsontalbe ?
thank you ~

**Comment by AMBudnik** [comment]
Hi @liy-cn 
You can pass any content inside a cell for example via `setDatAtCell` or `loadData` the case can be only how to read the data afterwards. 
If you could create a simple JSFiddle with the code to give me more details about how you're processing data I'll be able to understand the case more.

**Comment by AMBudnik** [comment]
I'm closing this issue as there was no reply for 2 weeks but if you still need some help @liy-cn 
please create a new ticket.
