### ISSUE TITLE
Get current handsontable instance in contextmenu

### ISSUE THREAD

**Issue by PhpSriptKiddie** [handsontable/handsontable#3777]
I am currently implementing a custom contextmenu for a case where I have multiple different handsontable instances.

In my contextmenu, I don't want to allow removing the top 3 rows, so I am checking whether any of these are selected before removing (this line: return hot.getSelected()[0] < 3). 

However, since I have multiple table instances (hot[0], hot[1] etc..), I would like to check in the function which instance has been clicked and make the check for this table. As it is now, it only works for the first one:

```
contextMenu: {
      callback: function (key, options) {
		if (key === 'about') {
          setTimeout(function () {
            // timeout is used to make sure the menu collapsed before alert is shown
            alert("This is a context menu with default and custom options mixed");
          }, 100);
        }
      },
      items: {
        "remove_row": {
          name: 'Remove row',
          disabled: function () {
            return hot.getSelected()[0] < 3
          }
        },	
        "about": {name: 'About this menu'}
      }
    },
```

How can I do something like that?

**Comment by PhpSriptKiddie** [comment]
Also - can I have different contextmenus depending on the clicked cell?

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 
Please check this example for the first case: http://jsfiddle.net/kg6ezsfz/ (3 instances)
and here's a demo for different contextMenu based on column index http://jsfiddle.net/mLy9k607/

**Comment by PhpSriptKiddie** [comment]
Thanks. That makes sense. What if I want to get the caller instance in the callback as well?

```
      callback: function (key, option) {
		if (key === 'about') {
          setTimeout(function () {
            // timeout is used to make sure the menu collapsed before alert is shown
            alert("This is a context menu with default and custom options mixed");
            console.log('this was called by:  ' + instance);
          }, 100);
        }
```

**Comment by AMBudnik** [comment]
Sorry for a late response @PhpSriptKiddie have you already managed to handle this code?

**Comment by PhpSriptKiddie** [comment]
Yes, I figured it out. Thanks for getting back to me :-)

**Comment by ChandraAdapa10** [comment]
HI AMBudnik,

can we have a callback function for default context menu options like row_above and row_below
we tried to add this its not working as expected. after adding call back function the row is not created in handsontable, here is the code snippet for the same 
  // app.component.ts
  import { Component } from '@angular/core';
  import * as Handsontable from 'handsontable';
  
  @Component({
    selector: 'app-root',
    template: `
    <div class="hot">
      <hot-table [settings]="hotSettings"></hot-table>
    </div>
    `,
  })
  class AppComponent {
    hotSettings: Handsontable.GridSettings = {
      data: Handsontable.helper.createSpreadsheetData(5, 5),
      colHeaders: true,
      contextMenu: {
        items: {
          'row_above': {
            name: 'Insert row above this one (custom name)',
            callback: function() {
            }
          },
          'row_below': {},
          'separator': Handsontable.plugins.ContextMenu.SEPARATOR,
          'clear_custom': {
            name: 'Clear all cells (custom)',
            callback: function() {
              this.clear();
            }
          }
        }
      }
    };
  }
  
  // app.module.ts
  import { NgModule } from '@angular/core';
  import { BrowserModule } from '@angular/platform-browser';
  import { HotTableModule } from '@handsontable/angular';
  
  @NgModule({
    imports:      [ BrowserModule, HotTableModule ],
    declarations: [ AppComponent ],
    bootstrap:    [ AppComponent ]
  })
  class AppModule { }
  
  // bootstrap
  import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
  
  platformBrowserDynamic().bootstrapModule(AppModule).catch(err => { console.error(err) });

you can find the link here https://jsfiddle.net/opvshekj/

Thanks

**Comment by AMBudnik** [comment]
As the original issue relates to a case from 2016 can you send me over a demo on support@handsontable.com? It will be easier to share examples and users who created this topic in 2016 won't get notifications.
