### ISSUE TITLE
[PRO] Version 1.7.0 broken

### ISSUE THREAD

**Issue by maurerke** [handsontable/handsontable#3781]
Hi!

With the newest pro version 1.7.0 seems to be a problem:
`Uncaught Error: Cannot find module 'hot-formula-parser'`

I am using bower, so a look into the bower.json file shows,
that only the following dependencies are listed:
```
"dependencies": {
    "moment": "^2.13.0",
    "numbro": "^1.8.0",
    "pikaday": "^1.4.0",
    "zeroclipboard": "2.2.0"
  }
```

Could be the problem the missing hot-formula-parser dependency?
This issue occured from jumping from v1.5.1 to v1.7.0

**Comment by budnix** [comment]
In did, there are missing `formula-parser` dependency. This is definitely a bug.
