### ISSUE TITLE
Autocomplete items filtering on FF

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3783]
On FF (49) autocomplete items filtering doesn't work precisely.

---
##### Steps to reproduce:
- Go to http://jsfiddle.net/tts22es1/;
- Edit `C1` cell by deleting its content via <kbd>DELETE</kbd> key. You should set the cursor at the end of the value and delete the chars until you'll get an empty string;
- Result: Autocomplete should render all available items but instead it shows only options that are matching the last char that was visible.
##### Screenshot:

![wrz-28-2016 12-33-09](https://cloud.githubusercontent.com/assets/571316/18910327/cbf38be8-8577-11e6-8b0d-8263e94478d6.gif)

**Comment by AMBudnik** [comment]
The issue seems to be gone in the latest FF. I did not change the HoT version. Can you check it on Mac?

**Comment by budnix** [comment]
I cannot reproduce the issue using the latest FF.

**Comment by AMBudnik** [comment]
Thanks for confirming.
I am closing the issue.
