### ISSUE TITLE
Edit and save value from custom multidimentional data

### ISSUE THREAD

**Issue by provodok** [handsontable/handsontable#3784]
Hello. I work with custom multidimentional data in my project ([click for example](https://jsfiddle.net/38fLqydk/2/)). I whant to edit each cell value and after that, using `afterChange` callback, send the changes to the server, handle it and update modified data in the selected cell. Is there a way to implement it? The data created dynamically (rows and cells count) every time we reset page.

**Comment by AMBudnik** [comment]
Hi @provodok 
sorry for a late reply. Can you specify your request? In which step of this task you're facing some difficulties?

**Comment by AMBudnik** [comment]
I'm closing this issue but if you still facing any difficulties please let me know.
