### ISSUE TITLE
Touch screen compatibility?

### ISSUE THREAD

**Issue by PhpSriptKiddie** [handsontable/handsontable#3785]
I know this has been discussed before, and I've found lots of different ideas and code changes that could possibly allow touch screen (Android/iOS) compatibility. However, it also seems to be marked as a fixed milestone after these discussions.

For me it doesnt work though. SHould I do anything in particular to get touch screen devices working?

Thanks

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 
we fixed editing in the latest version but still most advanced options are not working as expected also there's a problem with scrolling.

**Comment by PhpSriptKiddie** [comment]
Thanks. However, I can't edit my table on my Android Phone at all (OnePlus2, Google Chrome)
http://tiny.cc/dwpify

Have I got some settings wrong? The table in question: http://tiny.cc/fmqify

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 
unfortunately we are not able to provide support for Android devices.
The exact issue was reported at: https://github.com/handsontable/handsontable/issues/3
