### ISSUE TITLE
Editing cell with nested column mapping (nested) 

### ISSUE THREAD

**Issue by johnayoub** [handsontable/handsontable#3786]
When trying to edit a cell with a nested column mapping (e.g name.first) the editor shows the edit value as blank.

Issue is present in latest release: http://docs.handsontable.com/0.28.1/tutorial-data-sources.html#page-nested

**Comment by AMBudnik** [comment]
Data is indeed erased. Thanks for sharing @johnayoub

**Comment by budnix** [comment]
It seams to be broken since 0.28.0.

**Comment by AMBudnik** [comment]
Hi @johnayoub 
can you check if the following fix works for you?

**Comment by johnayoub** [comment]
hi @AMBudnik ,

Yes the fix works. Thanks for the quick turn around!

**Comment by AMBudnik** [comment]
Great! Thank you for your effort to share the bug and test a solution. Take care :)
