### ISSUE TITLE
custom editor that sets multiple cells

### ISSUE THREAD

**Issue by brzzi** [handsontable/handsontable#3787]
Is it possible to extend numeric or text editor to have popup with two input fields? It should update two table cells after editing is done(cell on which editing is triggered and another one in same row).

Any suggestion of how my editor's finishEditing(), saveValue or getValue should look like.
Or there's better approach using before/after change hooks?
Thanks!

**Comment by AMBudnik** [comment]
Hi @brzzi 
Unfortunately we do not have a similar example in our docs but surely it would be better to create a custom editor (here's a tutorial: https://docs.handsontable.com/pro/1.7.1/tutorial-cell-editor.html)
