### ISSUE TITLE
Incorrect formula results

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#3788]
hello,
i find an issue for a calculated cell in D5, it gives the formula and not the result
http://jsfiddle.net/jeanmarc/kns3n244/

regards
jeanmarc

**Comment by AMBudnik** [comment]
Thank you for sharing this issue @jeanmarc78

**Comment by AMBudnik** [comment]
It works the same in v 5.0.0

**Comment by AMBudnik** [comment]
The issue is no longer replicable (v 7.0.0 http://jsfiddle.net/je1vmpf3/) 
We get a valid value in `D5` cell.
