### ISSUE TITLE
reposition of pikaday not working with HOT 

### ISSUE THREAD

**Issue by bhosaleatul-syn** [handsontable/handsontable#3789]
Hi,

If cell is at bottom of page, pikaday reposition did not work and it always open at bottom.

![pickaday](https://cloud.githubusercontent.com/assets/22061282/18997195/49331526-8701-11e6-8082-767b25d656b6.png)

[Fiddle](http://jsfiddle.net/o3e65pbd/3/)

```

{
        type: 'date',
        dateFormat: 'YYYY-MM-DD',
        // datePicker additional options (see https://github.com/dbushell/Pikaday#configuration)
        datePickerConfig: {
                numberOfMonths: 2,
                reposition : true
        }
}
```

Also I checked the code, **reposition** option is passed in  **getDatePickerConfig** 

File: handsontable.full.js
Version: 1.7.1
Line: 8156

Thanks.

**Comment by jromero-onclick** [comment]
it is really strange but also there are other pikaday options that do not work too...
For example, theme option and position option

**Comment by jromero-onclick** [comment]
I have added an example that reproduce the error:
As you can see, some options work and others not

http://jsfiddle.net/4or9jqz2/1/

**Comment by AMBudnik** [comment]
hi @jromero-onclick 
you are right, we do not support all the options.
Here's the exact issue: https://github.com/handsontable/handsontable/issues/3747
