### ISSUE TITLE
bug with pasting double quotation marks to cell

### ISSUE THREAD

**Issue by codename-** [handsontable/handsontable#379]
When I type "" (double quotation marks) everything is fine, but when I try to paste that marks - I've got only single one pasted... 

This bug exists in 0.7.5 and 0.8.3.

**Comment by AMBudnik** [comment]
Please update to [0.13.1](https://github.com/handsontable/handsontable/releases/tag/0.13.1), it should work fine, example [demo](http://handsontable.com/)

**Comment by wck821829906** [comment]
@AMBudnik the bug seems still exists in version 0.35.0

**Comment by AMBudnik** [comment]
Hi @wck821829906 
Can you share an example?
