### ISSUE TITLE
Data is not correct while editing cells after moving columns

### ISSUE THREAD

**Issue by asw-sanjay** [handsontable/handsontable#3791]
Hi,

I was testing one of the fiddles of handsontable and found the issue while moving columns.
Please go to the following fiddle and perform the mentioned steps.
http://jsfiddle.net/5u5vczcg/

1. Move the column Price in place of date.
2. Double Click on any price cell and you will see that the value in cell is of date only.
3. Also when you double click on date cells they will also not displaying data correctly.

Could you please check and resolve.

**Comment by AMBudnik** [comment]
Thaks for sharing @asw-sanjay 
I've replicated the issue with the following demo.
![table-move](https://cloud.githubusercontent.com/assets/10757813/19075528/8fb49b5e-8a45-11e6-8bcf-cc5c8e4a614a.gif)

**Comment by AMBudnik** [comment]
Hi @asw-sanjay 
Can you please take a minute to check current fix? We've tested it but as you're the one who've spotted it maybe you will find something important regarding this case.

**Comment by AMBudnik** [comment]
I assume that we can close this issue as it was tested and there's no reply form the author.
If anyone still experience the behavior after updating to 0.28.3 please create a new topic.
