### ISSUE TITLE
Sorting on date not working when date format is DD/MM/YYYY

### ISSUE THREAD

**Issue by asw-sanjay** [handsontable/handsontable#3792]
Hi,

When we have a column with type date with date format is DD/MM/YYYY and we sort on this column the result is not correct.

Please find the fiddle below.
http://jsfiddle.net/3nwhsm7v/

Regards
Sanjay

**Comment by AMBudnik** [comment]
Thanks for sharing @asw-sanjay

**Comment by AMBudnik** [comment]
The exact issue was reported at: https://github.com/handsontable/handsontable/issues/3588
