### ISSUE TITLE
Row misalignement on IE and Edge

### ISSUE THREAD

**Issue by KodjoSuprem** [handsontable/handsontable#3793]
I have misalignement issues only with IE (11.589 ) and Edge ( 25.10586) but **NOT with Chrome (53.0)** 

The problem is solved on every browser when using the autoRowSize plugin like advisable in #2775

Is it the only solution to those alignment issues ? Like I said Everything is fine on chrome.

the autoRowSize plugin slows down large tables that are already very slow on IE (and Edge)

Step to reproduce (HoT version "0.26.1"):
- Have fixed rows and cols
- Resize a column to have its inner text wrapped on multiple lines
- Scroll down the table.

![image](https://cloud.githubusercontent.com/assets/4376260/19040487/8abd8032-8984-11e6-9641-18dcbff0e8b5.png)
(On Edge  25.10586)

![issue_ht](https://cloud.githubusercontent.com/assets/4376260/19040712/8b1d82ec-8985-11e6-8dc8-bfe88236dd26.gif)
(On Edge  25.10586)

**Comment by AMBudnik** [comment]
Hi @KodjoSuprem 
I've saw a similar issue. Try to delete `autoRowSize` from initialization settings and add it via `updateSettings`
