### ISSUE TITLE
Allow beforeAutofill to be blocked via returning false

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3794]
Currently we are not able to block [`beforeAutofill`](https://docs.handsontable.com/pro/1.7.1/Hooks.html#event:beforeAutofill) by returning `false`.

**Comment by AMBudnik** [comment]
We're moving this topic to our [Feature-requests section](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by pnowak** [comment]
Duplicate - https://github.com/handsontable/handsontable/issues/1908
