### ISSUE TITLE
ManualColumnResize guide with context menu

### ISSUE THREAD

**Issue by jsiali** [handsontable/handsontable#3796]
**Demo:** http://jsfiddle.net/s87mcaa2/

**Steps to reproduce:**
1. Display the resize guide in column header
2. Click RIGHT to open context menu

In the web console you can see this error :
`Uncaught TypeError: Cannot read property '0' of undefined`

For this code :
```
"row_above": {
    disabled: function () {
        // if first row, disable this option
        return hot3.getSelected()[0] === 0;
    }
},
```

**Comment by AMBudnik** [comment]
Thanks for sharing @jsiali 
As a tip: this issue does not occur if firstly we select any cell (http://jsfiddle.net/62k0L0no/).

**Comment by swistach** [comment]
It's not a bug.
In default contextMenu configuration (http://jsfiddle.net/dhofqa01/ ) an error doesn't occurs.
`getSelected()` returns `undefined` when any cells are not selected. First you should check what returns `getSelected()`.
Updated demo: http://jsfiddle.net/s87mcaa2/1/

**Comment by jsiali** [comment]
Thanks you for this feedback, i already have check getSelected() in my function ;)
