### ISSUE TITLE
Support Command-Up/Down shortcuts

### ISSUE THREAD

**Issue by danvk** [handsontable/handsontable#3797]
### Description

On a Mac, Command-Up Arrow / Command-Down Arrow go to the top / bottom values in a column in Excel and Google Sheets. handsontable supports Command-Home/End to do this, but not Command-Up/Down.
### Demo

http://jsfiddle.net/handsoncode/s6t768pq/
### Your environment
- Version: 0.28.2
- Browser Name and version: Chrome 53
- Operating System: Mac OS X

**Comment by AMBudnik** [comment]
Thank you for that suggestion @danvk We should add those shortcuts as well.
Currently you are allowed to move within the same row or a column via <kbd>CMD</kbd> + <kbd>Home</kbd> and <kbd>CMD</kbd> + <kbd>End</kbd>

**Comment by AMBudnik** [comment]
We're moving this topic to our [Feature-requests section](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by AMBudnik** [comment]
Currently, `CMD` + Arrow takes part in the multiple cell selection.
More keyboard shortcuts can be found at https://handsontable.com/docs/keyboard-navigation/
