### ISSUE TITLE
loadData does not refresh table

### ISSUE THREAD

**Issue by adamt06** [handsontable/handsontable#3799]
### Description

The loadData function doesn't seem to properly rerender the table in case trimrows is used and the new dataset is larger than before. The table height does not seem to properly adjust, but only for increases. Any interaction with the table afterwards or scrolling/resizing the viewport does result in a proper refresh.
### Steps to reproduce
1. Create a handsontable instance with some data and filtering or trimrows enabled.
2. Load a bigger dataset in it with loadData. No change visible.
3. Interact with the table in some way. New records will show up.
### Demo

http://jsfiddle.net/qhzpd098/1/
1. click add button, this adds more data (no visible change)
2. click one of the cells, this initiates refresh
### Your environment
- Version: pro 1.7.3
- Browser Name and version: Google Chrome 53.0.2785.143 with no extensions
- Operating System: Windows 10 64 bit with all updates installed as of 2016-10-05

**Comment by AMBudnik** [comment]
Thanks for sharing @adamt06 
You're right we need to double click the button or click inside the table.

**Comment by budnix** [comment]
Related with https://github.com/handsontable/handsontable/issues/3808.

**Comment by AMBudnik** [comment]
Fixed with https://github.com/handsontable/handsontable/issues/4131 in v0.31.2

Can you confirm that @adamt06 ?
