### ISSUE TITLE
manualColumnMove conflict with updateSettings()

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3800]
### Description

In this demo we should be able to load new row, one new column and show `id` columns as well. All options work besides filling new column with data.

### Additional details
Issue does not occur if we comment `manualColumnMove: true`

### Steps to reproduce

1. Click the <kbd>add column</kbd> button

### Demo

http://jsfiddle.net/LbysnL3e/

### Your environment
* Version: 1.7.3
* Browser Name and version: Chrome 53
* Operating System: Win10

**Comment by AMBudnik** [comment]
broken in 0.28.0, in 0.27.0 works as expected: http://jsfiddle.net/nejkydw4/

**Comment by jsiali** [comment]
Hope it will be resolved soon.
This bug prevents me to advance in my development because i need the manualColumnMove.

**Comment by AMBudnik** [comment]
Hi again @jsiali 
One of our devs has already investigated the issue but unfortunately it won't be easy to fix. We need some more time to check it.

**Comment by krzysztofspilka** [comment]
Depends on #3811 3811

**Comment by AMBudnik** [comment]
@jsiali 
a week after we've made a fix. Can you help me to check if everything works fine in v0.28.4?

**Comment by jsiali** [comment]
Hi @AMBudnik,
Sorry for my late reply.

It works :) Thanks you very much for your quick fix @swistach ;)

**Comment by AMBudnik** [comment]
Great, thanks mate!
