### ISSUE TITLE
100% CPU on Examples Page with dropdown/filters on

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3802]
Hey, I was just provided with an issue reported by Jonas (thanks mate!).

### Description

This causes the browser to freeze at 100% CPU usage and eventually crash. 

### Steps to reproduce

- Open example table at https://handsontable.com/examples.html?headers&filters with activated filters and dropdown menu 
- Open the dropdown menu for column "Code" and deselect "ILS" and "PHP" (the last two rows in the table) and hit OK 
- Select & copy 3 values from the level column and paste them into the second to last row 
- CPU usage increases to 100% and the browser tab is basically dead 

### Demo

https://handsontable.com/examples.html?headers&filters

### Your environment
* Version: 1.7.3.
* Browser Name and version: Chrome 53
* Operating System: Win10 (also tested on OSX and Linux)

**Comment by krzysztofspilka** [comment]
Actually, after you activate the filters and then paste any value to the last row, it will crash the table.

**Comment by jansiegel** [comment]
The real issue behind this is a problem with `trimRows` + `maxRows`.
Simplified example: http://jsfiddle.net/js_ziggle/8qpt72yz/
#### Steps to reproduce:
1. Copy a few rows
2. Paste them into the last row

**Comment by AMBudnik** [comment]
I just got a reply from Jonas that now everything works as expected. Thanks @jansiegel
