### ISSUE TITLE
Editor is stuck for rows > maxRows

### ISSUE THREAD

**Issue by negm** [handsontable/handsontable#3803]
### Description

If maxRows is set to any value, after data binding, for all rows greater than maxRows the editor gets stuck. I know this could be considered a "bad use of maxRows" but it took me a while to figure out the problem so I thought to pass it by you
### Steps to reproduce

1. Go to http://jsfiddle.net/t547puyh/
2. maxRows is set to 10
3. try editing any row > 10
### Demo

http://jsfiddle.net/t547puyh/
### Your environment
- Version: 
- Browser Name and version: Chrome 53.0.2785.116 m & IE11
- Operating System: Windows 7 Pro - 64bit

**Comment by AMBudnik** [comment]
Hi @negm 
That's right it is surely unusual use of `maxRows` but still thanks for sharing as the editor shouldn't just freeze like that.

**Comment by AMBudnik** [comment]
Hi @negm Our devs completed the task and it should work as a charm in 0.29.2
Can you confirm that please?

**Comment by negm** [comment]
I confirm issue is solved and the new behaviour follows the syntax :100:

**Comment by AMBudnik** [comment]
Great! Thanks for a quick update on that.
