### ISSUE TITLE
Feature request: drag & drop to set fixed column/row headers

### ISSUE THREAD

**Issue by danvk** [handsontable/handsontable#3804]
Excel and Google Sheets let you fix a number of rows or columns by dragging a little handle:

![header](https://cloud.githubusercontent.com/assets/98301/19223329/1ea7d3dc-8e3b-11e6-89d6-1c6e39ee4d98.gif)

It would be great if handsontable had a similar feature or, at the very least, a way to indicate visually how many rows were fixed via `fixedRowsTop` and `fixedColumnsLeft`.

**Comment by AMBudnik** [comment]
That's a really cool idea. Thanks for sharing @danvk

**Comment by AMBudnik** [comment]
We're moving this topic to our [Feature-requests section](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
