### ISSUE TITLE
Can I bind an object to cell and auto update cell value when the object was changed.

### ISSUE THREAD

**Issue by aokaywe** [handsontable/handsontable#3805]
### Description
I want bind an object to cell, the object id won't be change, but the value will change. 
and let cell value auto update when object value changed.

### Steps to reproduce
1. Save an object to cell, like:
```
var cellData = {'id': '82743c17-b78c-4f4f-9589-775482d3828a', value: '1'}
htable.setDataAtCell(1,1,cellData}
```
2. cell(1,1) show value 1
3. change cellData value to 2, like:   cellData.value = 2
4. cell(1,1) auto update the value to 2

### Your environment
* Version: Mon Jun 27 2016 09:59:46 GMT+0200 (CEST)
* Browser Name and version: chrome
* Operating System: windows 7

**Comment by AMBudnik** [comment]
Hi @aokaywe 
I think that this example is what you're looking for http://jsfiddle.net/reh8qpzv/ but if not just give me a hint what I'm missing.

**Comment by aokaywe** [comment]
Thanks for your reply. @AMBudnik 
I want save the object id in cell.  when I change the object value in other system, or when handsontable instance reload, it can be update the cell value by object id.
The object id binding to the cell, if I insert column before the cell, the id will not change.

**Comment by AMBudnik** [comment]
OK, so if in this demo http://jsfiddle.net/reh8qpzv/1/ you click a button (to load value from `id` key) and you add a column before the `B` col the value stays in the same place. This is what you wanted? Sorry if I'm not getting the idea - it's always better with a draft.

**Comment by aokaywe** [comment]
I find a way to slove my problem : )
