### ISSUE TITLE
Viewport Scrollbar Oddities When Using TrimRows Plugin

### ISSUE THREAD

**Issue by gtiguy92** [handsontable/handsontable#3808]
### Description

I have observed some oddities regarding the viewport scrollbar when working with the TrimRows plugin. When you trim rows and rerender without having scrolled the handsontable, the column header alignment is off. When you trim rows and rerender after having scrolled, the viewport scrollbard does not auto adjust until after you start scrolling again.
### Steps to reproduce

1. Open the JSFiddle provided below.
2. Click the Trim button and notice that the column headers are misaligned.
3. Re-run the JSFiddle.
4. Click the Scroll button.
5. Click the Trim button and notice that the viewport scrollbar is not auto adjusted.
6. Scroll in the viewport and notice that the viewport scrollbar adjusts while scrolling.
### Demo

http://jsfiddle.net/chris_neiger/seewd4c0/10/
### Your environment
- Version: 1.7.3
- Browser Name and version: Chrome Version 53.0.2785.143 m
- Operating System: Windows 10 - Version 1607 (OS Build 14393.222)

**Comment by AMBudnik** [comment]
Thanks for sharing @gtiguy92 
I though that we may miss some rendering but I can see that you added a `render()` method after each click.

**Comment by ankushgoel** [comment]
Hi @gtiguy92, 
I think you can use the  `scrollViewportTo` method at the time of trimming.
This will resolve your viewport issue.
Updated Fiddle : http://jsfiddle.net/seewd4c0/13/

**Comment by AMBudnik** [comment]
Hi @gtiguy92 
I have tried to replicate the issue with the latest version (just used your demo) and the issue seems to be gone.
I am closing the issue but feel free to leave a comment if you still get the same behavior.
