### ISSUE TITLE
Columns not adding when pasting data (reopened #1668)

### ISSUE THREAD

**Issue by lil25** [handsontable/handsontable#3811]
Hello

I've found issue. Columns are not added on pasting if "manualColumnMove" is true.
Here is demo http://jsfiddle.net/5u5vczcg/5/ try to set "manualColumnMove" to true and paste table data columns is not added. (version 0.28.3)

Thanks in advance.

**Comment by jsiali** [comment]
Related issue : https://github.com/handsontable/handsontable/issues/3800 ?

**Comment by lil25** [comment]
I'm not sure, but maybe they are connected

**Comment by jsiali** [comment]
Maybe wait the next release, i see the https://github.com/handsontable/handsontable/issues/3800 is fixed.

**Comment by swistach** [comment]
Thanks for sharing @jsiali,
Unfortunately is another bug. I'll try to fix it before today's release

**Comment by AMBudnik** [comment]
Hi @lil25 
We already made an update on this issue and hopefully it works fine now. Can you take a minute to check it?

**Comment by lil25** [comment]
Now it is working thanks a lot

**Comment by AMBudnik** [comment]
Great! Thanks for a prompt reply and wish you a wonderful day.
