### ISSUE TITLE
Load more data from other data

### ISSUE THREAD

**Issue by chaucv93** [handsontable/handsontable#3812]
My demo : http://jsbin.com/vewatuqogu/edit?html,js,output
I have 2 data : dataPro and dataCate. 

I load dataPro -> table (ProductID, ProductName, CategoryID). And I want [CategoryName] column also have data (get from dataCate). But I don't know how to do that.

Can anyone help me? 

Tks verymuch :heart: 

ps : I dont know my tittle right or wrong @@ My english skill is not good.

**Comment by AMBudnik** [comment]
Hi @chaucv93 
as `CategoryName` is not a part of data set served via `data` option you could 
a) concat both datasets and then load the data while initialization
b) load data after initialization using for example a `setDataAtCell`

Is there any particular reason why `dataCate` is outside of `dataPro` set?

**Comment by chaucv93** [comment]
Hi @AMBudnik 
Because I used 2 table from database, Products and Categories table. Products contain CategoryId, and Categories table have CategoryId and CategoryName. 

Can you example for me how to use : a) concat both datasets and then load the data while initialization

**Comment by AMBudnik** [comment]
Hi @chaucv93 
Sorry it took so long. Here's an example that may help: http://jsfiddle.net/ezj6j29z/
It's something that you were looking for?
