### ISSUE TITLE
Editor line takes 100% width of the container

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#3815]
Hi, do you have any idea why I got this behavior:
![image](https://cloud.githubusercontent.com/assets/710513/19389748/d1e02094-922d-11e6-9866-9f466dba32dd.png)
I declare the following properties:

```
                          data={...}
                          dataSchema={...}
                          columns={...}
                          colHeaders={...}
                          cells={...}
                          rowHeaders={true}
                          comments={true}
                          fillHandle={{
                              autoInsertRow: true,
                              direction    : 'vertical'
                          }}
                          contextMenu={['remove_row']}
                          afterSelection={this.handleSelection}
                          beforeRemoveRow={this.handleRemoveRow}
                          afterChange={this.handleAfterChange}
```

**Comment by krzysztofspilka** [comment]
Hi @andrewQwer , do you have a working jsfiddle demo maybe?

**Comment by andrewQwer** [comment]
Hi @krzysztofspilka.
Check out this fiddle: http://jsfiddle.net/andrewQwer/t18z8m7d/2/
If you remove classes from `body` then it works correctly

**Comment by swistach** [comment]
That's bug in calculations of maxWidth in .refreshDimension(), only when container of the Handsontable is set as flexbox element.

**Comment by AMBudnik** [comment]
Replicable using 0.34.0

**Comment by AMBudnik** [comment]
The same in 03.50

**Comment by setWan** [comment]
@AMBudnik Can the table be adaptive to the width of the parent element?

**Comment by AMBudnik** [comment]
Hi @setWan 

Handsontable has to have fixed height like here http://jsfiddle.net/mojLc50r/
It does to accept percentage values so if you want to change its width or height you need to use pixels. 
Here's more about it https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable

**Comment by Sjark** [comment]
Adding this to the css fixed it for us:

```css
body > span { position:absolute; }
```

**Comment by aninde** [comment]
I'm glad to see that this issue will be fixed by the upcoming v12.2 http://jsfiddle.net/aninde/Latxrg72/

**Comment by AMBudnik** [comment]
Hi @andrewQwer 
@Sjark @setWan 

I'm more than happy to announce that we fixed this issue in Handsontable v12.2.0 that was released just a couple of hours ago. I'm closing the issues as done. But if you'd have any questions or concerns, please feel free to leave a comment.

**Comment by daattali** [comment]
@Sjark for someone who cannot upgrade to newer versions of handsontable and is still stuck on a version that has this issue: is there a more specific CSS selector I can use instead of `span`? I'm worried such a generic selector can have unintended consequences. But I can't seem to see the span in the DOM so I don't know how else to reference it.

**Comment by Sjark** [comment]
> [@Sjark](https://github.com/Sjark) for someone who cannot upgrade to newer versions of handsontable and is still stuck on a version that has this issue: is there a more specific CSS selector I can use instead of `span`? I'm worried such a generic selector can have unintended consequences. But I can't seem to see the span in the DOM so I don't know how else to reference it.

Hi, I can't really remember this specific case, since it was 8 years ago, but if that css "hack" actually works I would not be too afraid to use it, since it should only target span's that are direct descendants of body, and normally you don't have many of those.

**Comment by daattali** [comment]
Thanks for the reply. After looking at the commit that fixed it https://github.com/handsontable/handsontable/blob/fe3629b5cda9c5d52e584798645db7a5fb198516/handsontable/src/3rdparty/autoResize/autoResize.js#L18-L49 I can see that the span doesn't have any identifying information.

I found another solution: 

```
.handsontable textarea {
  width: 0 !important;
}
```
