### ISSUE TITLE
ManualRowMove(ManualColumnMove) initialization using given map array option

### ISSUE THREAD

**Issue by gresspav** [handsontable/handsontable#3816]
Initialization of manual row plugin using given map array option is internally solved with call of function moveRows.

initialSettings: function() {
    var pluginSettings = this.hot.getSettings().manualRowMove;

```
if (Array.isArray(pluginSettings)) {

  this.moveRows(pluginSettings, 0);
}
```

It works fine if you do not add hook beforeRowMove which controls rows which could be moved. 

`moveRows: function(rows, target) {
   var beforeMoveHook = this.hot.runHooks('beforeRowMove', rows, target);

```
if (beforeMoveHook ) {

      code for movement

}

this.hot.runHooks('afterRowMove', rows, target);`
```

If you have such a hook it causes you troubles because you must handle exceptional initialization case.

`HandsontableDataHandler.prototype.beforeRowMove = function (rows, target) {

```
// hack -which allows intialization of mapping in manualRow(Column)Move plugin

if (rows.length == totalRowsCount) {

    return true;

}

......
```

`
Another problem I see that afterRowMove hook is called even if the movement was not allowed and the passed argument rows is not the same as for beforeRowMove. It returns original row indexes.
### Steps to reproduce
1. Enable ManualRowMove(ManualColumnMove) plugin with given map array option.

e.g.ManualRowMove = [1,4,3,2]

2.Add hook for beforeRowMove event which controls movement of rows

3.Add hook for afterRowMove event which should be called when rows were  moved.

-> Initialization of rowsMapper is not done unless you add above mentioned hack into beforeRowMove function

-> afterRowMove event is called even the movement was not done.
### Your environment
- Version: 0.28.4
- Browser Name and version: any
- Operating System:

**Comment by gresspav** [comment]
Hi
Do not know if it was clear what I wanted to report.
Expected behavior:
If the ManualRowMove(ManualColumnMove) plugin is intialized with given map array option
![image](https://cloud.githubusercontent.com/assets/20515049/19589801/ae06f512-976e-11e6-9d88-fc8a55aefcc4.png)
I expect that initialization is done internally and hook beforeRowMove (beforeColumnMove) is not called.
Otherwise I have to somehow allow it in my callback.
![image](https://cloud.githubusercontent.com/assets/20515049/19589929/6caab49a-976f-11e6-8739-e64fd44c0bb2.png)

**Comment by gresspav** [comment]
Possible solution could also be add additional argument initialization
beforeRowMove (columns, target, initialization)
beforeColumnMove (columns, target, initialization)

**Comment by AMBudnik** [comment]
Hi @gresspav you did a lot of work to describe this topic but I guess that we're missing a demo here as you've already share some steps to reproduce what we are talking about.
Can you create one?

**Comment by gresspav** [comment]
created http://jsfiddle.net/gresspav/dz6jrr24/13/

**Comment by AMBudnik** [comment]
Thanks for sharing @gresspav 
I will ask our developers to take a look at this case.

**Comment by AMBudnik** [comment]
I will mark your topic as an improvement suggestion for `ManualColumnMove`
again, thanks for sharing Pavel

**Comment by AMBudnik** [comment]
Topic moved to [Improvement-suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

**Comment by AMBudnik** [comment]
I am moving this conversation to Github Discussions and welcome everyone to discuss an expected behavior for that use case.
