### ISSUE TITLE
manualRowMove - misalignment of shown target line when dragging selection down

### ISSUE THREAD

**Issue by gresspav** [handsontable/handsontable#3817]
### Description

ManualRowMove plugin - row movement action
There occures some misalignment of shown target line with border of cells when dragging selected row(s)  down. 
Misalignment is visible in chrome or firefox. Internet explorer is ok.
![image](https://cloud.githubusercontent.com/assets/20515049/19431500/fadb1bac-9458-11e6-923f-b713fe957da1.png)
### Steps to reproduce

1.Have enabled manualRowMove plugin
2.Select some row(s)
3.Drag the selection down several rows
-> You can see misalignment of shown target line with the border of row cell
-> It works fine for up direction or for column movement.
### Demo

http://docs.handsontable.com/0.28.4/demo-moving.html
### Your environment
- Version :0.28.4
- Browser Name and version:
  Chrome Version 53.0.2785.143 m
  FireFox 49.0.1
- Operating System:windows 7 64

**Comment by AMBudnik** [comment]
Hi @gresspav 
Did you set a zoom-in in your browser? I got the same result when I made 100% zoom.

**Comment by gresspav** [comment]
Hi Aleksandra
Now I see that it is dependent on the zoom.
for me in chrome
   100% zoom is aligned,
    > 100% not
In firefox it is not aligned always
Pavel

2016-10-17 13:16 GMT+02:00 Aleksandra Budnik <notifications@github.com>:

**Comment by AMBudnik** [comment]
Can you share a .gif that provides more information about `In firefox it is not aligned always` 
When exactly it does  not align (with zoom or in other cases)?

**Comment by gresspav** [comment]
Hi Aleksandra
http://docs.handsontable.com/0.28.4/demo-moving.html
some examples of dragging row in firefox
[image: Vložený obrázek 1]
down
[image: Vložený obrázek 2]
up
[image: Vložený obrázek 7]
[image: Vložený obrázek 3]
down
[image: Vložený obrázek 4]
up
[image: Vložený obrázek 6]
Pavel



2016-10-17 14:09 GMT+02:00 Aleksandra Budnik <notifications@github.com>:

**Comment by AMBudnik** [comment]
Hi @gresspav, images didn't get attached.

**Comment by gresspav** [comment]
2016-10-17 16:08 GMT+02:00 Aleksandra Budnik <notifications@github.com>:

**Comment by AMBudnik** [comment]
Hi again @gresspav 
please take your time to load images. Still they're not attaching.

**Comment by gresspav** [comment]
Hi Images are already attached to the comment from yesterday. It was edited.


2016-10-18 9:32 GMT+02:00 Aleksandra Budnik <notifications@github.com>:

**Comment by AMBudnik** [comment]
Oh yes, thank you.

You are right - they are misaligned. I will mark this issue as a change but with a current Handsontable structure we can't do a lot while zooming the window.

**Comment by AMBudnik** [comment]
I'm marking this issue as an improvement suggestion as we currently do not support fully zooming in/out.

**Comment by AMBudnik** [comment]
I'm moving all the improvement suggestions to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Please feel free to leave any additional comments and reflections.

Thanks in advance!
