### ISSUE TITLE
Render scrollbar and table when hideColumn

### ISSUE THREAD

**Issue by jsiali** [handsontable/handsontable#3818]
### Description

When hide the last column of handsontable the scrollbar and the view don't updated.

And the second bug is an error : `column 12 does not exist`
### Steps to reproduce
1. Click the <kbd>hide last column</kbd> button for first step
2. Hide up to G column not included for second step
3. Try to go on right with arrow command and see the error message in web console
### Demo

http://jsfiddle.net/bpLe05c4/
### Your environment
- Version: 0.28.4
- Browser Name and version: Google Chrome - Version 54.0.2840.59 m (64-bit)
- Operating System: Windows 10 ver. 1607

**Comment by jsiali** [comment]
@AMBudnik Is anyone can help me, please ?

**Comment by AMBudnik** [comment]
Hi @jsiali 
I've tried this example two times yesterday and again checked it today but I cannot find any workaround.
I'll mark it as a bug.

Thanks for sharing.

**Comment by jsiali** [comment]
Hi @AMBudnik,
Thanks you for trying to find a workaround ;)

If any dev can check possibility or can estimate time to resolve it ;)

Regards

**Comment by AMBudnik** [comment]
The issue doesn't occur in version 1.13.0 

Updated demo http://jsfiddle.net/handsoncode/2rgnxu5g/
