### ISSUE TITLE
Can't trigger afterInit callback from external plugin

### ISSUE THREAD

**Issue by marc-antoinepelletier** [handsontable/handsontable#3819]
I've setup a custom external plugin for Handsontable to try to add a hook to the `afterInit` event, but it's not being triggered. Neither `beforeInit` or `init`. The plugin it working as expected for other callback such as `afterChange` but not for those 3 above.

The only place where I can setup a function to the `afterInit` is within the settings passed to hot.

Is this has been made on purpose or is it a bug ?

**Comment by AMBudnik** [comment]
Hi @marc-antoinepelletier 
`beforeInit` won't work inside hot settings but this one you already know and as you're using external solution.
Can you share a code for better understanding?

**Comment by marc-antoinepelletier** [comment]
@AMBudnik I am trying to setup an example in fiddle but I have some issue to create a plugin in there..

In the meantime; I used this https://github.com/handsontable/handsontable-skeleton/blob/master/plugins/external/externalPluginSkeleton.js to create a custom external plugin. I created a hook on the `afterInit` callback but it's never being called. But then now that I am writting this, I wonder if it's because I enable the plugin when the hotInstance is setup which mean `afterInit` has been triggered already...

**Comment by budnix** [comment]
Hi @marc-antoinepelletier, You actually answered the question by yourself. Depends on where you add `afterInit` hook listener it can be situation that this event has been triggered already or not. If you still not getting callbacks I suggest to add listeners to class constructor or to `init()` method which is called on [`beforeInit`](https://github.com/handsontable/handsontable/blob/master/src/plugins/_base.js#L44) hook

**Comment by marc-antoinepelletier** [comment]
Hi @budnix, yes I just figured this out when I was writing my other comment... I had to enable my external plugin once the hotInstance has been setup otherwise it wouldn't work for some reason. At least I understand now the problem!

I am going to close the issue, thank you and sorry for taking your time :)
