### ISSUE TITLE
Row header set width causes stretchH to overflow 

### ISSUE THREAD

**Issue by yawlhead91** [handsontable/handsontable#3820]
Hi there I am using handsontables with meteorJs, I have set the the row header with because the text was over flowing .

`.handsontable col.rowHeader {
    width: 165px;
}`

or with 

`rowHeaderWidth: 165`

this works all good but when I use stretchH  the table overflows the container until I click in and out of a cell the table seem to correct it self. 

Before clicking into a cell. 
![image](https://cloud.githubusercontent.com/assets/15271739/19436720/c6c4af20-9469-11e6-92a3-5f188b41f8f3.png)

After clicking in and out of cell. 
![image](https://cloud.githubusercontent.com/assets/15271739/19436746/e0431e78-9469-11e6-8774-f345238c3eeb.png)

**Comment by AMBudnik** [comment]
Hi @yawlhead91 
I guess that I've seen this issue before. Can you create a JSFiddle where we'll be able to replicate the issue?

Thanks in advance!

**Comment by yawlhead91** [comment]
Hey @AMBudnik I figgured it out I set the header width in the table arguments and it worked fine thanks for your help.

**Comment by AMBudnik** [comment]
Oh, ok - glad you've solved it. Thanks for an update @yawlhead91
