### ISSUE TITLE
Bug with cell editing - content is cleared

### ISSUE THREAD

**Issue by suricactus** [handsontable/handsontable#3821]
### Description

When editing starts, the content of the cell is cleared. It should not, as of any version prior 28.0.0 .
### Steps to reproduce

Just run the example with version 28.0.0+ . I have tried with any version of 28.0.\* and the result was the same.
### Demo

not working: http://jsfiddle.net/qmjpfvfm/
working: http://jsfiddle.net/64gwtozg/
### Your environment
- Version: 28.0.0+
- Browser Name and version: any browser
- Operating System: Linux

**Comment by AMBudnik** [comment]
We have decided to drop support for Backbone.
