### ISSUE TITLE
Wrong column order for 'updateSettings' method after manual moving

### ISSUE THREAD

**Issue by lil25** [handsontable/handsontable#3822]
Hello

After manual moving columns order is not changed for 'manualColumnResize' option in 'updateSettings' method

Here is demo http://jsfiddle.net/5u5vczcg/12/
Try to move first column, then click 'Set width' button.
Increased "old" first column, but should increase current first column.

Thanks in advance.

**Comment by AMBudnik** [comment]
Thanks for sharing @lil25 
related: https://github.com/handsontable/handsontable/issues/3594

**Comment by wszymanski** [comment]
#3983

**Comment by wszymanski** [comment]
@lil25 manualColumnResize plugin operates on logical indexes. I’ve prepared example showing how to change width of proper column by it’s visual index: http://jsfiddle.net/wojciech/74ynru20/2/

**Comment by AMBudnik** [comment]
For everyone interested in issue related to a wrong index being used by a plugin we highly recommend updating to v 8.0.0 that provide a long list of fixes for related topics

Release Notes https://github.com/handsontable/handsontable/releases
