### ISSUE TITLE
Backbone: it can not hold the value of the pre-edit

### ISSUE THREAD

**Issue by Kurom96** [handsontable/handsontable#3823]
When editing the cell, now clears the value of the pre-editing.
This problem has been occurred from 0.28.0.

It occurs in the demo.
https://docs.handsontable.com/0.28.0/demo-backbonejs.html

Has something changed?

**Comment by AMBudnik** [comment]
Hi @Kurom96 
I guess that the following issue https://github.com/handsontable/handsontable/issues/3821 relates to the same subject. Am I right?

**Comment by Kurom96** [comment]
Hi @AMBudnik 
Ahh, it is the same.
Thank you.
