### ISSUE TITLE
Nothing happens when custom editor returns array or object

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#3825]
I am trying to implement some custom editor that returns array of integer values. But in this case `afterChange`  handler of Handsontable doesn't trigger. It only works when I return plain values like strings or pure integers. Is there any limitation on return value in `getValue` method of custom editor? What if I want to return some complex object or array?

**Comment by andrewQwer** [comment]
This is required to implement select2 editor with multiple options

**Comment by AMBudnik** [comment]
hi @andrewQwer 
when it comes to `getValue()` method as written in the docs:
`Method should act return the current editor value, that is value that should be saved as a new cell value.`
Currently the structure is not prepared to take complex objects/arrays

**Comment by andrewQwer** [comment]
Ok, got it! Thank you!

**Comment by AMBudnik** [comment]
You're welcome. Have a nice day

**Comment by andrewQwer** [comment]
Sorry for posting to the closed issue, but maybe you can point me out to the best solution when my custom editor should return some complex object? As I mentioned above, I would like to return multiple values selected in select2 component, but cell should display text. At the same moment I need to have access to selected ids to send them to the backend.

**Comment by AMBudnik** [comment]
hi @andrewQwer 
have you already took some steps to accomplish this goal? Your questions is very general. We've been talking about the same feature some time ago but couldn't find a best solution as without testing there's not much we can say.

**Comment by andrewQwer** [comment]
Yes, I created select2 custom editor. From the backend I received object that looks like
```
 {id: 1, name: 'Some option in select'}
```
When I display this object in Handsontable I use `name` property to display text in the cell. When I switch to the editor mode I display select2 component to show available options and pass `id` as value for select2. Options are {id, name} objects and when I select some option in select2 I can't return `id` in `getValue` method because in this case cell will display it instead of text, I have to return selected text,  but what should I do with `id` from select2? I need it to send it back to the backend.
Does it help?

**Comment by AMBudnik** [comment]
So I assume that you're using this solution https://github.com/trebuchetty/Handsontable-select2-editor as a base?
To be honest I didn't test it yet and while creating a custom editor there are always few questions to answer before doing anything:
1. How to handle change callbacks
2. What should be shown via `getData()`/`getSourceData()`
3. How to validate cells
also there could be a problem with renderers and other plugins like: autofill, copy-paste, moving columns (meta data related).
I really do not want to point any direction as we (as a team) didn't choose any of possible paths to check what can be done.

**Comment by andrewQwer** [comment]
Thank you for the explanation!
I created my own select2 editor inherited from BaseEditor, but it doesn't matter, mentioned component has the same problem - it displays selected id instead of text.
On my opinion if you provide concept of renderers and editors it would be usefull to create some custom renderer/editor that processes such complex objects. So I can pass {id, name, etc..} object as value to the cell and my custom renderer/editor would know how to handle it correctly. Default renderers may ignore such values or throw errors or whatever.
But anyway, Handsontable is awesome component! Thanks again.
