### ISSUE TITLE
Zeroclipboard and Google Chrome 55+

### ISSUE THREAD

**Issue by KodjoSuprem** [handsontable/handsontable#3826]
Zeroclipboard use a hidden flash object to access the system clipboard.
From Google Blogs. It is said Chrome 55 will block Flash completely.
(https://chrome.googleblog.com/2016/08/flash-and-chrome.html)

Will HT be updated with a flash-less clipboard solution?

**Comment by AMBudnik** [comment]
You're right @KodjoSuprem we should be ready for this change.
Thank you very much for sharing.

**Comment by AMBudnik** [comment]
@KodjoSuprem 
We have tested our code and I guess that it works as expected in Chrome 55.
Can you confirm that @KodjoSuprem ?

**Comment by AMBudnik** [comment]
I am closing this issue but feel free to leave any comment if needed.

**Comment by mhuggins7278** [comment]
Chrome 59

ZeroClipboard.isFlashUnusable()
true

**Comment by AMBudnik** [comment]
Hi @mhuggins7278 

Thank for sharing. Our developer Piotr [is working on it ](https://trello.com/c/vN4fjZOZ/78-release-candidate-replace-zeroclipboard-with-clipboard-api)
