### ISSUE TITLE
afterChangesObserved is triggering after observer has been paused

### ISSUE THREAD

**Issue by minchopm** [handsontable/handsontable#3827]
### Description

When I pause the observer, the callback function afterChangesObserved has been triggered on every mouse click over the handsontable grid.
### Steps to reproduce

...
beforeInit: function () {
    this.getPlugin('observeChanges').enablePlugin();
},
...
afterChangesObserved: function () {
    this.pauseObservingChanges();
    console.log('trigger on every click');
},
...
### Your environment
- Version: node v6.7.0 npm v3.10.7
- Browser Name and version: Chrome 55
- Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @minchopm 
I'm not sure if I'm getting the idea. I've made a demo from your settings: http://jsfiddle.net/xbwkrnkg/
and it doesn't log the :

`console.log('trigger on every click');`

I'm using Chrome 53/ Win 10 as well
