### ISSUE TITLE
preventOverflow and dropdown, autocomplete render bug

### ISSUE THREAD

**Issue by vkomphasouk** [handsontable/handsontable#3828]
### Description

When you expand the dropdown or autocomplete list, only a small part of the list is rendered with a vertical scrollbar instead of the full list. It seems the height calculation is of when using preventOverflow = 'horizontal'
### Steps to reproduce

...
preventOverflow: 'horizontal'
columns: [
  {
    type: 'autocomplete',
    filter: false,
    source: ...
  },
  {
    type: 'dropdown',
    source: ...
  }
]
...
### Demo

[jsfiddle](http://jsfiddle.net/csjnsftz/)

### Related issue

- #8688

### Your environment
- Version: 
- Browser Name and version: IE 11 & Chrome
- Operating System: Win 10

**Comment by AMBudnik** [comment]
Thanks for sharing @vkomphasouk 
It doesn't look as desired.

**Comment by AMBudnik** [comment]
Still replicable in version 0.31.0

![example23](https://cloud.githubusercontent.com/assets/10757813/23359343/1f374034-fce6-11e6-9b3a-ef18052579b6.gif)

**Comment by krzysztofspilka** [comment]
Also, according to the information shared in the support channel, it's reproducible when one instance of Handsontable is placed right below the other.

**Comment by AMBudnik** [comment]
Hi @vkomphasouk 
I have pumped the version to 1.15.1 and it seems to work better. Can you check it, please?

**Comment by AMBudnik** [comment]
Please take a look at https://github.com/handsontable/handsontable/issues/5032
Where @djcooke provides a workaround

**Comment by ynte** [comment]
The workaround still gives undesirable results when you're working with multiple rows: [https://jsfiddle.net/7c1fqrto/](https://jsfiddle.net/7c1fqrto/). The dropdown does not open in the right place.

**Comment by AMBudnik** [comment]
inform [forum](https://forum.handsontable.com/t/gh-4172-3828-dropdown-not-showing-all-values-due-of-last-record-due-to-scroll-bar/3821)

**Comment by aninde** [comment]
This issue will be fixed by the upcoming v12.1.0 http://jsfiddle.net/3otc524p/

**Comment by AMBudnik** [comment]
Hi @vkomphasouk 

I have great news! We just released Handsontable v12.1.0 where this issue is solved.

If it won't work for you after the update please let me know at support@handsontable.com
