### ISSUE TITLE
 Horizontal scrolling and rendering issues for columns

### ISSUE THREAD

**Issue by gresspav** [handsontable/handsontable#3829]
### Description

There is some big problem with the rendering of columns when horizontal scrolling. It looks that there is some missing event which refreshes table.
I have created demo on https://jsfiddle.net/gresspav/fp69dsum/2/
We initialize data dynamically using columns mapping which define cellAccessor. In real code we do it in plugin but in demo we simply call initTable() which updates settings. 
The table in demo has 40 columns (3 are left fixed).
Mapping works fine as you can see from console.
![image](https://cloud.githubusercontent.com/assets/20515049/19559691/584dfcda-96d1-11e6-82a4-e31e4ff21b55.png)
Steps to reproduce
1.run demo on https://jsfiddle.net/gresspav/fp69dsum/2/
2.table is shown
![image](https://cloud.githubusercontent.com/assets/20515049/19559636/0be28636-96d1-11e6-8bed-4243b26125c1.png)
3.drag the scrollbar to the right.
![image](https://cloud.githubusercontent.com/assets/20515049/19559764/bac2ddb8-96d1-11e6-8aa3-28efcca9e4e5.png)
You can see that only 22 columns were rendered, however the scrollbar counts with all columns because there is empty space.
4. Click on the cell 22/0. The columns are corrupted. We can see header X twice.
![image](https://cloud.githubusercontent.com/assets/20515049/19559884/306c0652-96d2-11e6-9b1a-7b5f01b1ae84.png)
5. If you scroll to the left it is somehow refreshed
![image](https://cloud.githubusercontent.com/assets/20515049/19559931/6d6a131e-96d2-11e6-9c72-5bb35d341d96.png)
6. And if you scroll to the right again you can see 32 columns now!!
![image](https://cloud.githubusercontent.com/assets/20515049/19559948/8d061042-96d2-11e6-8dd0-cd998b66f3e7.png)
7.Of course it depends on zoom. We can see all columns but corrupted if we zoom out.
![image](https://cloud.githubusercontent.com/assets/20515049/19559990/c777464c-96d2-11e6-8b0a-98c144e4a6cd.png)
8.When you click into table it little bit refreshes.
![image](https://cloud.githubusercontent.com/assets/20515049/19560038/08bf8894-96d3-11e6-92eb-dfa70cd3bae7.png)
### Your environment
- Version: 0.28.4
- Browser Name and version: Any
- Operating System: Windows 7

**Comment by krzysztofspilka** [comment]
Something goes wrong while rendering fixed parts of the grid: https://jsfiddle.net/fp69dsum/3/

**Comment by gresspav** [comment]
I agree.

**Comment by gresspav** [comment]
By the way there is another issue with fixed area settings e.g. fixedColumnsLeft. 
It does not work if you set them to some value and then try to update with another value.
Hot is not able to handle this update. Only possible solution in such case is to construct hot again.
![image](https://cloud.githubusercontent.com/assets/20515049/19589514/d4cd9c66-976c-11e6-9fdf-0b97a479b5ca.png)

![image](https://cloud.githubusercontent.com/assets/20515049/19589539/f3e66024-976c-11e6-83a3-664116dd61f3.png)

**Comment by gresspav** [comment]
Hi
Any idea how to fix this bug and priority?
Created updated fiddle which shows problems for both horizontal and vertical scrolling https://jsfiddle.net/gresspav/fp69dsum/4/
fixed area borders are highlighted
![image](https://cloud.githubusercontent.com/assets/20515049/19637409/398a171a-99cf-11e6-81a8-b62e8321a170.png)
After scrolling you can see for example this:
![image](https://cloud.githubusercontent.com/assets/20515049/19637388/1badd466-99cf-11e6-8ba3-0844f6e50c5e.png)
There are also visible some strange internal scrolls bar if you zoom out. See example:
![image](https://cloud.githubusercontent.com/assets/20515049/19637444/7482a1de-99cf-11e6-82ba-07c1af456604.png)

**Comment by AMBudnik** [comment]
Hi @gresspav 

If you would add `viewportColumnRenderingOffset` for the amount of columns that you own the issue with missing content won't appear.

updated code: https://jsfiddle.net/o56ax23r/

**Comment by gresspav** [comment]
Hi @AMBudnik 
Thank you for investigation. Problem of hidden rows/columns was solved, however,  there is still problem with the fixed area rendering. 
I have created another issues 
https://github.com/handsontable/handsontable/issues/3846

**Comment by AMBudnik** [comment]
OK, so we will close this issue then.

I've already added a reply to https://github.com/handsontable/handsontable/issues/3846

**Comment by gresspav** [comment]
In my eyes it is bug. viewportColumnRenderingOffset is about the performance. 
-viewportColumnRenderingOffset- 
Number of rows to be prerendered before and after the viewport is changed. Default value is 'auto' which means that Handsontable tries to calculates offset for best performance.
Default Value: 'auto'

**Comment by gresspav** [comment]
In issue https://github.com/handsontable/handsontable/issues/3846 I mentioned that the origin of the problem with hidden cells is incorrect handling of the fixed area settings (fixedRowsTop,fixedColumnsLeft) after hot.updateSettings
You do not need to set viewportColumnRenderingOffset
https://jsfiddle.net/gresspav/fp69dsum/9/

**Comment by gresspav** [comment]
Now I checked workarounds in my application with real data and I have to use both:
1. dummy fixed area definition in constructor
2.viewportColumn(Row)RenderingOffset definition in update

var hot = new Handsontable(example1, {
fixedRowsTop: dummyFixedRowsTop,
fixedColumnsLeft: dummyFixedColumnsLeft,
});
hot.updateSettings({
fixedRowsTop: fixedRowsTop,
fixedColumnsLeft: fixedColumnsLeft,
viewportColumnRenderingOffset: totalColumnsCount,
viewportRowRenderingOffset: totalRowsCount,
