### ISSUE TITLE
Custom buttons and dropdowns

### ISSUE THREAD

**Issue by helmutgranda** [handsontable/handsontable#3831]
### Description

We have created custom dropdowns and custom buttons across the table. They work great on Desktop but on mobile I believe the touchevents are taking over the basic click events.
### Steps to reproduce

Currently it is an internal project but if you were to add a button to a table the button would not respond. 
### Demo

I can create a super minified demo if it is imperative.
### Your environment
- Version: latest
- Browser Name and version: Safari, Chrome
- Operating System: iOS, Android

**Comment by AMBudnik** [comment]
Hi @helmutgranda 
Unfortunately as written in our docs at [known limitations](https://docs.handsontable.com/pro/1.7.4/tutorial-known-limitations.html) we're not fully mobile-friendly. We only offer basic operations:

`Only the basic functionality works with mobile devices, which means you should be able to display, edit and scroll the grid. We can't guarantee that all the plugins will work as we don't test Handsontable in mobile browsers.`

**Comment by Ehme** [comment]
Von meinem iPad gesendet
