### ISSUE TITLE
Backlight misaligned when moving colulmns if fixedColumnsLeft defined

### ISSUE THREAD

**Issue by lizavolkova** [handsontable/handsontable#3832]
### Description

I set fixedColumnsLeft to 4 and manualColumnMove to true. When dragging around the columns, the backlight element is offset from the actual column. 
### Demo

http://jsfiddle.net/b48na9e7/
### Your environment
- Version: 0.24.8
- Browser Name and version: Chrome latest
- Operating System: Windows

**Comment by gresspav** [comment]
In your demo we can see also very clear misalignment when dragging rows (reported in https://github.com/handsontable/handsontable/issues/3817)
![image](https://cloud.githubusercontent.com/assets/20515049/19577354/4d17ee84-9717-11e6-8efb-3207c439951e.png)

**Comment by AMBudnik** [comment]
thanks for sharing guys @lizavolkova @gresspav 
I'll back this issue as a something to be changed

**Comment by lizavolkova** [comment]
Thanks!

**Comment by AMBudnik** [comment]
same issue as https://github.com/handsontable/handsontable/issues/3817
Please share any additional comments at https://github.com/handsontable/handsontable/issues/3817
