### ISSUE TITLE
Table not rendering

### ISSUE THREAD

**Issue by rodrigokinamic** [handsontable/handsontable#3833]
### Description

Hi,

I am having some trouble with a table. After an Ajax post, all the rows are rendered but only the first column of the table. Whenever I click the table or scroll it, the rest of the columns are rendered. Is this a known issue? Is there any walkthrough?

Thanks in advanced!

**Comment by AMBudnik** [comment]
You're using Handsontable or any wrapper (there is a same issue at ngHandsontable) and any additional solutions? (iframe, modal, etc)
It would be great if you could create a JSFiddle example.

**Comment by rodrigokinamic** [comment]
<table class="adminContent">
            <tr>
                <td class="adminData">
                    <div id="prices-grid" style="overflow: hidden"></div>
                </td>
            </tr>
        </table>

        <script>
            $(document).ready(function () {
                function toggleList() {
                    jQuery.ajax({
                        url: '/ManageEntities/ListChanged',
                        type: "POST",
                        dataType: "json",
                        contentType: 'application/json; charset=utf-8',
                        data: JSON.stringify({ entityId: 2, listId: 1 }),
                        async: true,
                        processData: false,
                        cache: false,
                        success: function (data) {
                            hot.updateSettings({ 
                                // Table titles
                                colHeaders: data.ColumnHeaders, rowHeaders: data.RowHeaders,
                                // Table max size
                                maxColumns: data.ColumnHeaders.length, maxRows: data.RowHeaders.length 
                            });

                            hot.loadData(data.GridData);
                        },
                        error: function (error) { }
                    });
                }

                var container = document.getElementById('prices-grid');
                var hot = new Handsontable(container, {
                    colHeaders: model.ColumnHeaders,
                    rowHeaders: model.RowHeaders,
                    autoColumnSize: false,
                    autoRowSize: false,
                    colWidths: 50
                });
            });
        </script>

**Comment by swistach** [comment]
Hi @rodrigokinamic 
If you are loading data as an array of objects, then you should define `dataSchema`.
Here is small example, how you can do it: http://jsfiddle.net/11hcjxma/
