### ISSUE TITLE
Click on the custom contextmenu of copy and paste no response

### ISSUE THREAD

**Issue by xfliu138** [handsontable/handsontable#3835]
If is the sample of copy and paste is ok,but if click on the custom contextmenu of copy and paste no response,here is the url
http://jsfiddle.net/atL9dekj/1/
![image](https://cloud.githubusercontent.com/assets/18605877/19631805/df52ca40-99d2-11e6-807e-e01c9b23a268.png)

**Comment by AMBudnik** [comment]
Thanks for sharing @xfliu138 
related https://github.com/handsontable/handsontable/issues/3078

**Comment by xfliu138** [comment]
@AMBudnik I understand this bug in the latest version has not yet been solved, all right？

**Comment by AMBudnik** [comment]
That it correct @xfliu138 
we didn't found a solution for this issue yet

**Comment by renehamburger** [comment]
@xfliu138, copy & paste via the context menu should work. See https://docs.handsontable.com/pro/1.9.1/demo-context-menu.html#page-copy-paste. The problem in jsfiddle is that the preview runs in a sandboxed iframe, so the clipboard flash plugin can't be loaded. You should see an error in the console.

**Comment by AMBudnik** [comment]
Thanks @renehamburger you're right. I've asked our developer to take a look.
