### ISSUE TITLE
Automatic row height calculation is done only for visible area so table rows 'jumps' when scrolling

### ISSUE THREAD

**Issue by gresspav** [handsontable/handsontable#3836]
Hi, created demo for version 28.3 https://jsfiddle.net/gresspav/fp69dsum/5/ ,because 28.4 has rendering bug (https://github.com/handsontable/handsontable/issues/3829) and it is hard to demonstrate problem 
### Steps to reproduce
1. Has created table with setting manualColumnResize: true and have some cell with longer text.
   ![image](https://cloud.githubusercontent.com/assets/20515049/19640576/a834cd50-99dd-11e6-9d7c-92d575ea05ed.png)
2. Reduce the size of the cell manually. -> Row is then higher.
   ![image](https://cloud.githubusercontent.com/assets/20515049/19640599/c0370fee-99dd-11e6-9693-5cee48ac01c6.png)
3. Now scroll to the target coords 0,0. (at first use left/down direction and at the end use left/up direction).
   During this action you can see misalignment between fixed left area and fixed top area  (which is another bug),
   ![image](https://cloud.githubusercontent.com/assets/20515049/19640641/f4ed859c-99dd-11e6-93e1-514ca11ccef4.png)
   however, expected result is this:
   ![image](https://cloud.githubusercontent.com/assets/20515049/19640809/b393c7a4-99de-11e6-81d6-b732f1ef7d81.png)
   Now scroll to the right using arrow or mouse and row height is suddenly increased:
   ![image](https://cloud.githubusercontent.com/assets/20515049/19640857/f75d6864-99de-11e6-9896-c20b0059f698.png)
   ![image](https://cloud.githubusercontent.com/assets/20515049/19640875/0c3524c0-99df-11e6-8b94-77765a404814.png)
- Version: 28.3/28.4 
- Browser Name and version:
- Operating System:

**Comment by gresspav** [comment]
Sometimes you are able to see greater height even in left top corner.
 ![image](https://cloud.githubusercontent.com/assets/20515049/19642467/b7a1e37e-99e5-11e6-9482-90b632d03073.png)

**Comment by AMBudnik** [comment]
thanks for sharing @gresspav 
I think that it is related to https://github.com/handsontable/handsontable/issues/3474

**Comment by gresspav** [comment]
Hi  
Main message of this task is that row's height unexpectedly jumps according to currently visible data, so it is hard for user to follow the selected line(s) when scrolling through the table.

It is related to https://github.com/handsontable/handsontable/issues/3474 only partly for the mentioned misalignment between fixed left area and fixed top area.

**Comment by budnix** [comment]
Hi @gresspav, Did you try to use the `autoRowSize: true` setting?

**Comment by AMBudnik** [comment]
Hi @gresspav 
Are you still experiencing the same issues?

**Comment by gresspav** [comment]
Unfortunately we do not yet use the latest version 29.0.
I tried your proposal  autoRowSize: true but I it crashed for me.
I did not have time to create demo because it is little bit complex case.
I will inform you if I have something to show.
Thanks

**Comment by AMBudnik** [comment]
OK, I closing the issue and we will reopen it if needed.
The best way would be to update to 0.29.0
Still feel free to leave any additional feedback.
