### ISSUE TITLE
Merge cells heigh with RowHeaders: false

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3837]
### Description

Issue posted at:  https://forum.handsontable.com/t/the-rowheights-is-unwork/731

`When I merge the first column, the rowHeights I set is unwork for the height is always set to the first cell in handsontable.`
### Steps to reproduce

1. Open a demo and check row heights.
   They all should be 100 high.
### Tip

Demo for `rowHeaders` enabled (working as expected): http://jsfiddle.net/vbuv6qso/1/
### Demo

http://jsfiddle.net/vbuv6qso/
### Your environment
- Version: 0.28.4
- Browser Name and version: Chrome 53
- Operating System: Win 10

**Comment by AMBudnik** [comment]
Workaround: http://jsfiddle.net/handsoncode/r3xzadwj/

When we add `rowHeaders: true` but we set their width to `0` via `rowHeaderWidth`

**Comment by AMBudnik** [comment]
Behavior is the same in version 0.35.1

**Comment by AMBudnik** [comment]
The issue remains the same in v `2.0.0` and there is no version that supported it before.

**Comment by DongShi** [comment]
Hope this can be fixed soon, as other vendors can handle this well.

**Comment by ejubkadric94** [comment]
Is there any ETA on when could we expect the real fix?
Workaround works in a way, but produces other major issues regarding accessibility. Screen readers still read hidden table headers, and include them in counting the table size - which makes the workaround unacceptable.

**Comment by AMBudnik** [comment]
Sorry @ejubkadric94 the last milestone this year has beeen already closed. 
We did not get the green light to plan tasks for January but will consider taking this issue to the next milestone.

**Comment by AMBudnik** [comment]
Please also check this case while fixing http://jsfiddle.net/akr2evu4/ (`7.1.1`).

Both of these cases are fixed while adding `rowHeaders`.

In this scenario, we need to select any cell to see the odd behavior happening.

![bug_1](https://user-images.githubusercontent.com/10757813/65691068-842cd380-e070-11e9-985e-ae4cd7ad8047.gif)

Suddenly the bottom part of the table shifts and hides under fixed rows.

**Comment by AMBudnik** [comment]
https://github.com/handsontable/handsontable/issues/3545 might be related

**Comment by AMBudnik** [comment]
This issue remains the same in v 8.0.0 http://jsfiddle.net/AMBudnik/5gvc39jx/

**Comment by AMBudnik** [comment]
This issue is also reported here https://github.com/handsontable/handsontable/issues/2473

I'm closing this issue as a duplicate but will update anyone interested after fixing https://github.com/handsontable/handsontable/issues/2473
