### ISSUE TITLE
"hiddenColumns" and "stretchH" don't work well together

### ISSUE THREAD

**Issue by jlsalmon** [handsontable/handsontable#3838]
### Description

When using `hiddenColumns` and `stretchH`, if the _last_ column is set to hidden, it is in fact erroneously displayed (with empty values).
### Demo

http://jsfiddle.net/j_lewis/zpcctrLs/
### Your environment
- Version: handsontable-pro 1.7.4
- Browser Name and version: Chrome 54
- Operating System: Ubuntu 16.10

**Comment by jsiali** [comment]
Related issue : #3818

**Comment by AMBudnik** [comment]
thanks for sharing @jlsalmon 
looks like a bug to me

**Comment by HaroldStruwig** [comment]
This should be high priority I think - I am also stuck with this issue.

**Comment by AMBudnik** [comment]
After looking for a workaround I have found a really strange behavior here http://jsfiddle.net/handsoncode/g6s3v14d/

When I added one column via `alter` and updated `hiddenColumns` I got the right colHeaders but data is shifted. I should get `Kx` data in the last column but I get `Jx` (from a column before it).

**Comment by AMBudnik** [comment]
Possibly the same bug as https://github.com/handsontable/handsontable/issues/4370
