### ISSUE TITLE
Backbone integration editor clearing on edit

### ISSUE THREAD

**Issue by lizavolkova** [handsontable/handsontable#3839]
### Description
If using Handsontable with Backbone, when double clicking on a cell to edit, the editor clears out the value and on clicking enter submits an empty value.

### Steps to reproduce
Reproducible in demo page: http://docs.handsontable.com/0.28.4/demo-backbonejs.html

### Your environment
Latest Chrome and FF at least

**Comment by AMBudnik** [comment]
thanks for sharing @lizavolkova 
related: https://github.com/handsontable/handsontable/issues/3649
