### ISSUE TITLE
Add Version Numbers in comments at top of files in /dist

### ISSUE THREAD

**Issue by jongunter** [handsontable/handsontable#3844]
I've inherited a code base with `handsontable.full.js` and `handsontable.full.css` files in it. A few minor HOT features aren't working an I have no clue if its a version issue (though I suspect it is) or something else, because there are no version numbers at the top of the JS/CSS libraries.  Many other open source JS libraries on GitHub follow this convention...would it be possible for HOT to do the same from now on?

Thanks so much!

**Comment by AMBudnik** [comment]
Hi @jongunter 
we've changed the order of shared information in newest versions of code (legal requirement). Currently you can check a version by searching the following line: `Handsontable.version` or directly from your code via `console.log(instance_name.version)`

**Comment by jongunter** [comment]
Thanks for the response. Still confused about why the version number can't go below the license, at the top of the compile code, then?  I can point you to lots of other JS libraries on GitHub with an MIT license that do this just fine.

**Comment by krzysztofspilka** [comment]
You are right, @jongunter - that should be put on top of the code. Definitely something #todo

**Comment by AMBudnik** [comment]
I'm moving all the improvement suggestions to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Please feel free to leave any additional comments and reflections.

Thanks in advance!
