### ISSUE TITLE
Fixed area rendering problem 

### ISSUE THREAD

**Issue by gresspav** [handsontable/handsontable#3846]
Hi, there is a problem with the fixed area rendering. 
Please check https://jsfiddle.net/gresspav/fp69dsum/6/
1.Open the table
2.Scroll using scrollbar to the left
3.Scroll using scrollbar to the bottom
![image](https://cloud.githubusercontent.com/assets/20515049/19806625/676ca922-9d1c-11e6-87a1-4931d8a99e54.png)
4.Now you can see the misalignment in the leftbottom corner:
![image](https://cloud.githubusercontent.com/assets/20515049/19806707/e7ba4990-9d1c-11e6-8bc9-dd97aa31a33b.png)
5. Now drag the horizontal scrollbar, move it little bit the left and drop it.
![image](https://cloud.githubusercontent.com/assets/20515049/19806791/541e8736-9d1d-11e6-9e93-429638b1b6bc.png)
6. You can repeat this step with the same result
![image](https://cloud.githubusercontent.com/assets/20515049/19806843/9089e558-9d1d-11e6-8558-a9af85cb7571.png)
7. The same problem occurs if you scroll up
![image](https://cloud.githubusercontent.com/assets/20515049/19806893/ced014ae-9d1d-11e6-96bf-d8ad0cb14eee.png)

Your environment
Version: 0.28.4
Browser Name and version: Any
Operating System: Windows 7

**Comment by gresspav** [comment]
Hi I played a little bit with the fiddle and find out that the problem is partly solved if you define any fixed area in the hot constructor. I must check this workround because the update of fixed area caused another hot problems in the past. 
https://jsfiddle.net/gresspav/fp69dsum/7/
There is still misalignment in the leftbottom corner
![image](https://cloud.githubusercontent.com/assets/20515049/19807554/e55a8cd8-9d20-11e6-81bb-0d53dece7f91.png)
You can scroll this sub-area using the mouse wheel.
![image](https://cloud.githubusercontent.com/assets/20515049/19807705/a2d457e4-9d21-11e6-9cf9-1bbbb0071d5e.png)

**Comment by gresspav** [comment]
Hi 
Problem is caused by inconsistent height calculation for fixed and data area.
It was improved after removal of option rowHeights: 22 
https://jsfiddle.net/gresspav/fp69dsum/8/
If you zoom out there is still visible significant misalignment. 
![image](https://cloud.githubusercontent.com/assets/20515049/19829307/2cdf9c30-9ddd-11e6-9edb-6b2ca517a740.png)

**Comment by AMBudnik** [comment]
Hi @gresspav 
I'm not sure if we didn't discussed the same subject before. This is a different case?

**Comment by gresspav** [comment]
I have reported rendering problem #3829 with hidden cells and misaligned headers. You proposed me some workaround for hidden cells so I created this new ticket 3846 for the rest of problems in 3829.

For bugs reported in this issue 3846 I found some workarounds by myself. 
1.
There is bug in handling of the fixed area settings (fixedRowsTop,fixedColumnsLeft) after hot.updateSettings. 
https://jsfiddle.net/gresspav/fp69dsum/6/
solution is to define any fixed area in the hot constructor.
https://jsfiddle.net/gresspav/fp69dsum/7/

2.
There is an inconsistent height calculation for fixed and data area.
It was improved after removal of option rowHeights: 22 
https://jsfiddle.net/gresspav/fp69dsum/8/

**Comment by gresspav** [comment]
By the way, now I found that the origin of the problem with hidden cells is as well 
incorrect handling of the fixed area settings (fixedRowsTop,fixedColumnsLeft) after hot.updateSettings
You do not need to set viewportColumnRenderingOffset
https://jsfiddle.net/gresspav/fp69dsum/9/

**Comment by gresspav** [comment]
Now I checked workarounds in my application with real data and I have to use both:
1. dummy fixed area definition in constructor
2.viewportColumn(Row)RenderingOffset definition in update

  var hot = new Handsontable(example1, {
        fixedRowsTop: dummyFixedRowsTop,
        fixedColumnsLeft: dummyFixedColumnsLeft,
   });
    hot.updateSettings({
        fixedRowsTop: fixedRowsTop,
        fixedColumnsLeft: fixedColumnsLeft,
       viewportColumnRenderingOffset: totalColumnsCount,
       viewportRowRenderingOffset: totalRowsCount,

**Comment by swistach** [comment]
Is related with: #3857

**Comment by AMBudnik** [comment]
Hi @gresspav 
Does updating to 0.29.0 solves the issue?

**Comment by teh** [comment]
A random related gotcha for other readers: If the column height changes during load (I had an `img` without height specified) then everything breaks. I recommend setting `height=...`.

**Comment by AMBudnik** [comment]
OK, I guess that we can close this issue as there were no information from the author.
ps. thanks for sharing your tip @teh

**Comment by gresspav** [comment]
I am sorry but I have to wait for update of handsontable on our dev
environment. I will let you now.

Dne 18. 11. 2016 4:14 PM napsal uživatel "Aleksandra Budnik" <
notifications@github.com>:

**Comment by AMBudnik** [comment]
That's OK @gresspav 
We can always reopen the ticket.

I keep my fingers crossed for progress.
