### ISSUE TITLE
loadData and manualRowMove issue

### ISSUE THREAD

**Issue by errrken** [handsontable/handsontable#3849]
### Description
loadData does not extend the rows when manualRowMove is enabled. It works perfect when extending columns and manualColumnMove is enabled.

### Demo
http://jsfiddle.net/uap5Lc3u/

### Environment
Version: 0.28.4
Browser Name and version: Chrome 53.0.2785.143 (64-bit)
Operating System: OS X 10.10.2

**Comment by AMBudnik** [comment]
Hi @errrken 

Can you guide me on how to replicate the issue. In your example the `manualColumnMove` is enabled and new data is loading as expected.

**Comment by errrken** [comment]
Hi @AMBudnik 

After the table is created (with 5 rows and 5 cols), it runs loadData with 10 rows and 10 columns. For me it loads the 10 columns, but still only show the 5 rows.

**Comment by AMBudnik** [comment]
Oh yes, you're right @errrken 

The new source is `10x10` 
Thanks for sharing @errrken !

**Comment by Curious-programmer** [comment]
Stucked with same issue, please let me know if you have any update on this.

Thanks

**Comment by AMBudnik** [comment]
Hi @errrken 
We have fixed the issue in 0.31.0. Demo: http://jsfiddle.net/handsoncode/ppd8jo37/

Please update your code and let me know if it works in your project as well.

Again thanks for sharing.
