### ISSUE TITLE
Question: Click Event on Autocompletes

### ISSUE THREAD

**Issue by paulhodel** [handsontable/handsontable#3852]
After the autocomplete ajax request returns the response the Process(response.data) will be called showing the options in the dropdown. How do I get which option was clicked by the user? Not the text, but which option in the array 0, 1, 2 or 3...? I would like to avoid mapping since I can have same labels in my array.

Thanks in advance.

Paul Hodel

**Comment by AMBudnik** [comment]
Hi @paulhodel 
currently our autocomplete does not take an index of the user choice but it reads and pass the content so we are not able to access which element was picked. 
We can only check it by the content: http://jsfiddle.net/dbm53e0z/

Alternatively you can add different classes for autocomplete elements and check if an element with defined class was clicked but it's a lot of code and it's more like a workaround for a workaround...
