### ISSUE TITLE
Documentation: beforeStretchingColumnWidth return value has no effect, modifyColWidth does though

### ISSUE THREAD

**Issue by groetzi** [handsontable/handsontable#3853]
### Description
Hi, I just tried limiting the width of columns to a certain value e.g. let handsontable determine column width but limit it when it becomes too big. From the documentation I assumed that *beforeStretchingColumnWidth* would help me out as it says in the docs 'Returns new width which will be applied to the column element.' (http://docs.handsontable.com/0.28.4/Hooks.html#event:beforeStretchingColumnWidth). Returning a value in *beforeStretchingColumnWidth* didn't have any effect, playing around with *modifyColWidth* lead to the desired behavior though. Documentation doesn't say anything about a return value for *modifyColWidth*. Am I missing something or could the documentation be wrong here?

### Steps to reproduce

1. Return a value in *beforeStretchingColumnWidth* e.g. 200 => no effect
2. Return a value in *modifyColWidth* e.g. 200 => columns get width of 200

### Your environment
* Version: 0.28.4
* Browser Name and version: 54.0.2840.71
* Operating System: Win10

**Comment by AMBudnik** [comment]
Hi @groetzi 
`beforeStretchingColumnWidth` refers to [`stretchH`](https://docs.handsontable.com/pro/1.7.4/demo-stretching.html) option.
demo: http://jsfiddle.net/1pLkjak7/

**Comment by groetzi** [comment]
nice, thanks for clarification @AMBudnik btw, as return value in *modifyColWidth* is not explicitly mentioned in the documentation, is it ok to return a width or is it considered unofficial api?

**Comment by AMBudnik** [comment]
You're right (and it doesn't only refer to `modifyColWidth`). For many options and callbacks we should add detailed information are some of them are currently confusing. 

`modifyColWidth` runs after each rendering what we can see here: http://jsfiddle.net/handsoncode/pqpkvgad/

and if we resize a column it's triggered many times: http://jsfiddle.net/handsoncode/w3jpj2xk/ (only 6 cells in 3 cols)
* 12 times if we resize column`A` or `B`
* 6 times when we resize column `C`

**Comment by groetzi** [comment]
ok, thanks for clarification!
