### ISSUE TITLE
Horizontal scroll bar on the top of handsontable

### ISSUE THREAD

**Issue by byblik** [handsontable/handsontable#3855]
Hello.
Is it possible to add horizontal scroll bar on the top of handsontable? 
Handonstable has fixed width and big height so I have to scroll to the bottom and drag the bar with mouse.

**Comment by byblik** [comment]
Implemented workaround myself here http://jsfiddle.net/wg3ssqdb/. 
Btw it is irritating that bottom scrollbar is too far from table. Is it a bug?

**Comment by AMBudnik** [comment]
Hi @byblik 
the scroll bar is where you added it - you've set `height: 100` that's why it's far under the table

**Comment by a1n1k1u1r1** [comment]
I tried replicating this using angular v12 ! 
However I am getting a compilation error for window.TopScrollBar ! Any suggestions ?

**Comment by a1n1k1u1r1** [comment]
Hi @AMBudnik - Tried the same fiddle. 
window.TopScrollBar gives me the following compilation error :- 
Property 'TopScrollbar' does not exist on type 'Window & typeof globalThis'. Did you mean 'scrollbars'?

**Comment by AMBudnik** [comment]
I would like to help with that task @a1n1k1u1r1 but that exceeds the basic support in general meaning. If you could tell me a bit more about your implementation maybe I'll be able to help more. Please share the details at support@handsontable.com
