### ISSUE TITLE
How can I to override right click event in handsontable

### ISSUE THREAD

**Issue by minteliuwm** [handsontable/handsontable#3856]
Now, I want to override right click event in handsontable , but I don't know how to do it , can you help me ?

**Comment by AMBudnik** [comment]
Hi @minteliuwm 
you can use `beforeOnCellMouseDown`, here's an example when I load a `alert()` for a right click http://jsfiddle.net/6e0rd80j/

**Comment by talamaska** [comment]
@AMBudnik beforeOnCellMouseDown doesn't give any information of the click was right click or left click, so either you can prevent all or nothing. I wan to prevent only right click.

**Comment by AMBudnik** [comment]
hey @talamaska  

it returns an event, so you can call `event.button`. If it returns `2` it's RMB and `0` for LMB

**Comment by talamaska** [comment]
oh? @AMBudnik  thanks for that I was struggling here.

**Comment by talamaska** [comment]
but how exactly
```
beforeOnCellMouseDown =(event: any, coords: any, TD: any) => {
    console.log('beforeOnCellMouseDown', event, coords);
    
    if ((coords.col < 0 || coords.row < 0) && event.button === 2) {
      console.log('should disable propagation');
      event.preventDefault();
      event.stopImmediatePropagation();
    }
  }
```

**Comment by talamaska** [comment]
@AMBudnik I want to disable the context menu if clicked on header row or col

**Comment by AMBudnik** [comment]
@talamaska I've just left a comment at https://github.com/handsontable/handsontable/issues/6055 ;)
