### ISSUE TITLE
How can I access the cell content from a callback on the contextmenu?

### ISSUE THREAD

**Issue by viperfx** [handsontable/handsontable#3859]
How can I access the cell content from a callback on the contextmenu?

Coords, content, anything would be good. 

```
     contextMenu: {
      callback: function (key, options, test) {
        if (key === 'trace') {
          // get cell content here
        }
      },
      items: {
        "trace": {name: 'Download report trace'}
      }
     },

```

**Comment by AMBudnik** [comment]
Hi @viperfx 

you can call the `getSelected()` method. Here's an example http://jsfiddle.net/3nmqv949/

**Comment by viperfx** [comment]
I get an error `handsontable.full.min.js:28 Uncaught Error: Cell type must be a string (…)`

I set the cell type to a custom renderer. Is this wrong?
```
     cells: function (row, col, prop) {
       var cellProperties = {};
       cellProperties.type = {
          renderer: daff.diffRenderer
       }
       cellProperties.readOnly = true;
       return cellProperties;
     }
```

**Comment by AMBudnik** [comment]
hi @viperfx 
it is not the same issue, right?
Can you share a full demo with the renderer structure?

**Comment by viperfx** [comment]
You can see a full demo of the renderer here:

https://paulfitz.github.io/daff/

Data diff, initialisation - source of https://paulfitz.github.io/daff/, line 309.
renderer: https://paulfitz.github.io/daff/daff_handsontable.js

**Comment by viperfx** [comment]
@AMBudnik Let me know if you need more info.

**Comment by viperfx** [comment]
@AMBudnik Any update on this?

**Comment by AMBudnik** [comment]
Hi @viperfx 
sorry, I've missed a last update on this topic.
I do not think that the presented code via my Fiddle causes the direct console.log 
Can you add only your instance settings to the Fiddle I've added?
It's hard to find anything in the whole repo

Here's a basic custom renderer declaration: http://jsfiddle.net/AMBudnik/xh54h62s/ you can also try to add your logic into this structure and check the differences. 
Maybe the issue refers to lack of basic renderer, which is 

`Handsontable.renderers.TextRenderer.apply(this, arguments);` for text

**Comment by viperfx** [comment]
Ah yes, I was able to get the renders set correctly. After that the error message went away but I still could not see the dropdown menu. Then I matched up the CSS file with the JS version and it shows up! 

Cheers

**Comment by AMBudnik** [comment]
Great! Thanks for an update @viperfx 
Glad it works now.
