### ISSUE TITLE
Shrinking headers while scrolling a stretched table

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3861]
### Description

If I scroll the horizontally stretched table to the bottom and then back to top, the headers are getting shrinked somewhere in the halfway.

### Steps to reproduce

1. Go to http://jsfiddle.net/ox13g54z/
2. Scroll all the way to the bottom
3. Scroll slowly to the top

### Demo

http://jsfiddle.net/ox13g54z/

![image](https://cloud.githubusercontent.com/assets/8048526/20053509/308147e6-a4d9-11e6-94c3-c2c39d563e09.png)

### Your environment
* Version of Handsontable: 0.28.4
* Browser Name and version: Chrome 54
* Operating System: Windows 8.1

**Comment by AMBudnik** [comment]
Still replicable in v0.34.0

**Comment by AMBudnik** [comment]
The same behavior as in v0.35.0

**Comment by AMBudnik** [comment]
Still replicable in 0.38.1

**Comment by AMBudnik** [comment]
Still works the same in v `5.0.1`. It works OK when we scroll fast but breaks down on slow scrolling.

**Comment by AMBudnik** [comment]
This works well in v `7.1.0` http://jsfiddle.net/handsoncode/oyphdvz1/ even when we scroll really slow.

Tested on Windows/ Chrome 75 and FF 67.
