### ISSUE TITLE
Uncaught TypeError on copy-paste on the demo page

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3862]
### Description

There is an error "Uncaught TypeError: Cannot read property '0' of undefined(…)" being thrown on copy-paste in a demo about conditional formatting.

### Steps to reproduce

1. Go to https://docs.handsontable.com/demo-conditional-formatting.html
2. Copy everything
3. Paste anywhere below a first row

### Demo

https://gyazo.com/2d912511298f88fb37566fb81de83d05

### Your environment
* Version: 0.28.4
* Browser Name and version: Chrome 54
* Operating System: Windows 8.1

**Comment by swistach** [comment]
In line #55 of example should be:
```javascript
var getData = this.instance.getData();

if (row === 0 || (getData[row] && getData[row][col] === 'readOnly')) {
   ...
```

**Comment by swistach** [comment]
Moved to: [docs issue board](https://github.com/handsontable/docs/issues/48)
