### ISSUE TITLE
Disable highlighting columns when sorting

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3863]
### Description

A column is being highlighted during sorting if a manualColumnMove is turned to `true`.

### Steps to reproduce

1. Go to http://jsfiddle.net/6z43rpuz/
2. Sort a column

### Demo

https://gyazo.com/3c4fa3d0c12120bb27517e470c656619

### Your environment
* Version: 0.28.4
* Browser Name and version: Chrome 54
* Operating System: Windows 8.1

**Comment by AMBudnik** [comment]
Tested and now we do not experience the flashing while sorting caused by `manualColumnMove `
