### ISSUE TITLE
Setting renderAllRows to True Breaks Viewport Vertical Scroll When Selection Changes via Keyboard Navigation

### ISSUE THREAD

**Issue by gtiguy92** [handsontable/handsontable#3866]
### Description
Vertical scrolling via keyboard up and down arrows breaks when renderAllRows is set to true.

### Steps to reproduce
1. Set renderAllRows to true
2. Select a cell
3. Move selection down below the viewport using the keyboard down button
4. Selection will change, but the viewport will not scroll with the selection

### Demo
http://jsfiddle.net/chris_neiger/mqduojec/2/

### Your environment
* Version: 1.7.4
* Browser Name and version: Chrome Version 54.0.2840.87 m
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thanks for sharing @gtiguy92 
As a workaround you can use the `viewportRowRenderingOffset` instead, demo: http://jsfiddle.net/AMBudnik/xrjoqjnh/ that literally does the same job in that example.

**Comment by AMBudnik** [comment]
Simplified example http://jsfiddle.net/handsoncode/4q842u03/
v0.34.0

**Comment by swistach** [comment]
Hi @gtiguy92,
This issue was solved in v1.15.0/0.35.0.
Demo: http://jsfiddle.net/s7cy3tLp/

Feel free to reopen if you have still a problem with `renderAllRows`.
