### ISSUE TITLE
Placeholder logic not equivalent to other empty logic for TextRenderer

### ISSUE THREAD

**Issue by colinbrownec** [handsontable/handsontable#3867]
### Description
In TextRenderer, placeholders are drawn if `!value && cellProperties.placeholder`, but this check is insufficient as it casts value before making this comparison.

If you are using something other than strings in the HoT data array, this can trigger whenever `!value` evaluates to true. Some examples include `0`, `NaN`, `""`, `undefined`, `false`.

I propose to use the same logic used in `isEmptyCol` and `isEmptyRow`. 

These functions determine if a cell **is not** empty if 
`value !== '' && value !== null && typeof value !== 'undefined'`. 

So conversely, a cell **is** empty if 
`value === '' || value === null || typeof value === 'undefined'`

### Steps to reproduce

1. provide a placeholder to cell
2. set the value of this cell to be the Number 0
3. observe that the placeholder is rendered instead of the value

### Demo
http://jsfiddle.net/h5oqpuan/

### Your environment
* Version: Pro 1.7.4
* Browser Name and version: Chrome 54.0.2840.87 m
* Operating System: Windows

**Comment by AMBudnik** [comment]
Thanks for sharing your proposition @colinbrownec

**Comment by AMBudnik** [comment]
Hi,

Thanks again for sharing this Feature Request. I am moving it to our Wiki Section at https://github.com/handsontable/handsontable/wiki/Feature-requests
The issue will stay closed until it'll get picked by our developer.

**Comment by AMBudnik** [comment]
I'm moving the conversation to Github Discussions. 
Also here's an updated demo (v8.3.2) http://jsfiddle.net/handsoncode/ebhz4m72/
