### ISSUE TITLE
Please stop adding scrollbars randomly!

### ISSUE THREAD

**Issue by karellm** [handsontable/handsontable#3869]
### Description
A component or library should be agnostic of where it will live. It should NOT care if the parent is `overflow: hidden` or `overflow: auto`. It especially shouldn't try to be smart about it.

You have no idea how mad this has been driving our team for the last couple months. It is almost impossible for us to render handsontable properly and consistently. Our use cases may be a little unusual (aka scrollable modal) but that shouldn't matter.

If I want scrollbars, I should tell HOT so. Please stop guessing. Please stop looking if the parent is `hidden`. Or at least for backward compability, let me disable any magic positioning or sizing.

### Steps to reproduce
1. Parent container with `overflow: auto` and a defined `height`
2. Content that should be accessible before and after the HOT table
3. HOT table with enough data to be higher than the `height` defined on the container

> we end up with 2 nested scrollbars

### Demo
https://jsfiddle.net/nqmfyokw/

### Your environment
* Version: 0.29.0
* Browser Name and version: Chrome (latest)
* Operating System: Mac OS X 10.11.6

**Comment by AMBudnik** [comment]
Thank you for sharing your concerns @karellm 

related: https://github.com/handsontable/handsontable/issues/3432

**Comment by karellm** [comment]
@AMBudnik I looked at that issue and indeed they are related. Basically in #3432, it is equivalent to `height: 0`. 

I created a separate issue to provide some higher level discussion about good API design rather than fixing the specific issue of `height: 0`. I think HOT is trying to be too smart when it comes to rendering scrollbars and sizing.

**Comment by AMBudnik** [comment]
That's correct @karellm 
also we do not have a responsive library yet (it in subject is it much to do)

**Comment by karellm** [comment]
@AMBudnik We've had some issues recently with the indeed and you were great at addressing them! I'm happy to assist in any way with this issue; it is currently blocking us I would love to avoid adding one more workaround this time. Thanks!

**Comment by AMBudnik** [comment]
I've just asked our developer Piotr what can be done regarding this case and he told me that the issue lays in the Walkontable and it a 'to be discussed' topic. I will mention this ticket in a first dev meeting but I guess it will take a while.
Maybe you have any suggestions on what can be changed (not sure if you saw Walkontable)?

**Comment by karellm** [comment]
This is an assumption since I don't know the codebase well enough, but I would say that the easiest would be to add an option to disable the feature. It would provide backward compatibility with current users while offering an opt-out.


If you are willing to consider a bigger change in behaviour, I would highly recommend that HOT renders "in the flow" of the page. Again, I might be overlooking many things here (eg fixed headers). 

I know it is a very complex matter to get right. That's why I would turn HOT stupid and agnostic. Some features might require a certain layout option to work but that should be opt-in at this point.

**Comment by AMBudnik** [comment]
In the subject http://jsfiddle.net/sdt5h2fb/

A middle table doesn't display at all.

**Comment by swistach** [comment]
Hi @karellm,
#3365, #3433 and #3869 are related each other.
I think that fix for #3433 will solve also this issue.
