### ISSUE TITLE
Fixed Columns doesn't work properly in Bootstrap Tabs

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3871]
### Description

While using fixed columns inside Bootstrap tabs fixed area does not correspond properly to other cells content.
**TIP**: It works as expected without tabs and the layer under fixed area has proper heights.

### Steps to reproduce

1. Click any cell in fixed area

![bug-fixed-cols-bootstrap](https://cloud.githubusercontent.com/assets/10757813/20174710/92b8c37c-a73f-11e6-9a2f-a37e0eb0c0d0.gif)

### Demo

https://jsfiddle.net/handsoncode/gxz6nsbz/

### Your environment
* Version: 1.8.0 (base 0.29.0)
* Browser Name and version: Chrome 54
* Operating System: Win 10

`[G #3669]`

**Comment by AMBudnik** [comment]
The issue is still replicable in v0.34.0.

**Comment by AMBudnik** [comment]
The issue has been already mentioned at https://github.com/handsontable/handsontable/issues/2779

**Comment by swistach** [comment]
It works as expected with Handsontable v7+ and the most recent Bootstrap v4.5.2: https://jsfiddle.net/fjkr01uo/
