### ISSUE TITLE
Browser is frozen during cell selection because of CopyPastePlugin

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3872]
### Description
The browser is frozen during cell selection because of `CopyPastePlugin`
In result of selection of all cells is browser freezing for a while. It's not visible for small datasets, but beginning from 400x400, the delay is noticeable.

### Steps to reproduce
1. Go to demo
2. Try select all cells in table (CTRL+A / CMD+A)
3. Directly after that try click on B1

### Demo
http://jsfiddle.net/8o65pj5j/

### Screenshot
![screen shot 2016-11-10 at 12 44 10](https://cloud.githubusercontent.com/assets/11849621/20175539/93b393a2-a743-11e6-8a3b-914f6f6dd335.png)

### Your environment
* Version: 0.29.0
* Browser Name and version: Chrome 54.0.2840.98
* Operating System: macOS Sierra 10.12.1

**Comment by swistach** [comment]
With `copyPaste: false`, selection of cells lasts <0.014s (~1000x faster).

**Comment by AMBudnik** [comment]
Hi @swistach 

I've used the 0.29.0 version (your demo) and it has frozen my browser for a couple of seconds. Then I updated to 0.35.0 and was able to select `B1` without lags. 
Here's an updated demo http://jsfiddle.net/oy7fe6jk/
I think that we can close the issue report.
