### ISSUE TITLE
Incorrect size of `wtHider`and `wtHolder` in overlays

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3873]
### Description
Overlays have improper dimensions.
But it applies only to:
- [x] topOverlay
- [x] leftOverlay
- [x] topLeftOverlay

These should be verified:
- [x] bottom
- [x] bottomLeft

### Steps to reproduce
1. Go to demo
2. Highlight overlays' containers using dev tools

### Demo
http://jsfiddle.net/3dcafdvf/

### Your environment
* Version: 1.8.0
* Browser Name and version: any
* Operating System: any

**Comment by swistach** [comment]
Exactly :)
`.wtHider` for topOverlay:
![screen shot 2018-01-19 at 11 49 51](https://user-images.githubusercontent.com/11849621/35147575-65825ef0-fd0f-11e7-9616-cf1605cb8765.png)

`.wtHider` for leftOverlay:
![screen shot 2018-01-19 at 11 50 25](https://user-images.githubusercontent.com/11849621/35147597-72e030f4-fd0f-11e7-881b-8f720ca65488.png)

In both of above overlays, size is not properly calculated.

But for bottomLeftCorner is ok:
![screen shot 2018-01-19 at 11 50 51](https://user-images.githubusercontent.com/11849621/35147647-9ed5c6e2-fd0f-11e7-90ee-c8113cfccc3a.png)

**Comment by AMBudnik** [comment]
OK, thanks for an update!

**Comment by swistach** [comment]
@wojciechczerniak suggested to verify is here something that we can improve for browser's `zoom` support: https://github.com/handsontable/handsontable/issues/4767

**Comment by aninde** [comment]
This issue will be fixed by `v8` http://jsfiddle.net/aninde/57hdbouy/
![Screenshot 2020-08-05 at 09 20 13](https://user-images.githubusercontent.com/30186818/89383636-1ecc5900-d6fd-11ea-8ffb-73ce4c095ed8.png)
![Screenshot 2020-08-05 at 09 19 04](https://user-images.githubusercontent.com/30186818/89383642-20961c80-d6fd-11ea-8881-f1e9d8e7eee0.png)

**Comment by wojciechczerniak** [comment]
It's smaller but no fully fixed.

**Comment by aninde** [comment]
> It's smaller but no fully fixed.

In that case, I put it back to tag `Issues`.

**Comment by scarletfog** [comment]
As discussed with @wojciechczerniak and @budnix - I can close this issue as done. If some further development is needed please open a new ticket.
