### ISSUE TITLE
CTRL + X causes #bad-value# in checkbox

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3875]
### Description

CTRL + X causes `#bad-value#` in checkbox

### Steps to reproduce

1. perform CRTL+X on a checkbox field.
2. , `#bad-value#` appears

![checkbox-issue](https://cloud.githubusercontent.com/assets/10757813/20179649/85cb00b8-a757-11e6-9e6d-3bfcbb73e4d6.png)

### Demo

http://docs.handsontable.com/0.29.0/demo-checkbox.html

### Your environment
* Version: 0.29.0
* Browser Name and version: Chrome 54
* Operating System: Win 10

### Related
We had a similar issue at: https://github.com/handsontable/handsontable/issues/3616
which is already fixed for <kbd>Backspace</kbd> ,<kbd>Delete</kbd> ,<kbd>Enter</kbd> and <kbd>Space</kbd>

`[G #3693]`

**Comment by dehim** [comment]
![image](https://cloud.githubusercontent.com/assets/9805228/20295801/289869f0-ab42-11e6-9338-4b0c57be8b92.png)

**Comment by AMBudnik** [comment]
The issue still occurs. I guess that we should block it from the keycode combination. Here is a primitive example for blocking the code http://jsfiddle.net/j7gcmwj4/

**Comment by AMBudnik** [comment]
The same issue as https://github.com/handsontable/handsontable/issues/4106
