### ISSUE TITLE
Fill handle is gone after closing editor of numeric cells.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3877]
### Description
After closing of numeric cell editor, the fill handle isn't visible.

### Steps to reproduce
1. Go to http://jsfiddle.net/3rfxprwm/
2. Open editor of B1
3. Select another cell

### Demo
http://jsfiddle.net/3rfxprwm/

### Your environment
* Version: 0.15.0+
* Browser Name and version: Chrome 54.0.2840.98
* Operating System: macOS Sierra 10.12.1

**Comment by AMBudnik** [comment]
Works as expected in v0.30.0, Demo: http://jsfiddle.net/d6tvpwbx/
Thanks!
