### ISSUE TITLE
Add 'afterContextMenuExecute'

### ISSUE THREAD

**Issue by renehamburger** [handsontable/handsontable#3878]
It seems that the 'afterContextMenuExecute' is meant for exactly that, but it's not implemented yet. Apart from a custom menu or checking the DOM after 'afterContextMenuHide', is there any other way of achieving that?

I'm using handsontable-pro, 1.8.0.

**Comment by AMBudnik** [comment]
Hi Rene,

You would like to get a column that just got hidden via context menu? Maybe use the `afterContextMenuHide` to track changes in length of `instance.getPlugin('hiddenColumns').hiddenColumns`

You're right there's no `afterColumnHide` callback. I can add it as an feature request.

**Comment by renehamburger** [comment]
Thanks, that should work. But please add a feature request for  'afterContextMenuExecute' to be able to capture execution of any menu item.

**Comment by AMBudnik** [comment]
I will then open this topic to change the title and labels.

**Comment by AMBudnik** [comment]
Hi,

Thanks for sharing this Feature Request. I am moving it to our Wiki Section at https://github.com/handsontable/handsontable/wiki/Feature-requests
The issue will stay closed until it'll get picked by our developer.
