### ISSUE TITLE
Reducing fixed rows/columns by `updateSettings` don't work properly

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3879]
### Description
When you try to hide fixed rows/columns then the selection works strange on the previous fixed elements.

### Steps to reproduce
1. Go to demo
2. Try to select `A1`

### Demo
http://jsfiddle.net/m8do40oj/

### Your environment
* Version: 0.29.0
* Browser Name and version:  Chrome 54.0.2840.98
* Operating System: macOS Sierra 10.12.1

**Comment by AMBudnik** [comment]
inform `[G #6122]`

**Comment by AMBudnik** [comment]
The same in v0.34.3

**Comment by AMBudnik** [comment]
Replicable in v0.35.0

**Comment by AMBudnik** [comment]
The issue is still replicable in v `2.0.0`. We can edit the cell but cannot select it.

**Comment by AMBudnik** [comment]
It works the same in v `5.0.0`

**Comment by wojciechczerniak** [comment]
There were some changes in selection `z-index` in `v7.0.0`: https://jsfiddle.net/j7fsbdxw/

Please check this issue with v7+ @AMBudnik @aninde . Looks like it's fixed already

**Comment by AMBudnik** [comment]
Agree, works well with `7.0.0` (@wojciechczerniak demo) and it doesn't break [in `8.0.0.-rc1`](https://jsfiddle.net/handsoncode/91m0c5vp/) so we're good.
