### ISSUE TITLE
Assigning a default value to my column  cells and making datatype validation

### ISSUE THREAD

**Issue by korssane** [handsontable/handsontable#388]
Hi Guys, 

iam wondering how we can assign a default value to a column cells.
Also, how we can make data type validation

thank peers.

**Comment by halfnibble** [comment]
This to me is hardly acceptable. Googling around, there are several use cases for supplying default values. While I appreciate the flexibility this method allows, it seems extreme to have to write a custom render method and custom beforeChange method that parses all this out just to produce new rows with default data.

I envision a Handsontable property that lets you assign a simple JSON object with the property name and default value. I will make a feature request.

**Comment by mringler** [comment]
In case someone stumbles over this old thread, like I did:
The best solution to achieve default values for new rows is to use the [dataSchema configuration option](https://docs.handsontable.com/0.15.0/tutorial-data-sources.html#page-data-schema).

**Comment by JonKernPA** [comment]
In case someone stumbles over the stumble over above...

Search documentation for "schema" as the version changes in the URL ;-)

Here is the current link:

https://handsontable.com/docs/8.3.2/tutorial-data-sources.html#page-data-schema
