### ISSUE TITLE
Numeric cells - removes value if isn't number

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3880]
### Description
Issue happen only when cell is configured as numeric cell with defined format.
It's related with changes in #2166.

### Steps to reproduce
1. Go to demo
2. Paste `example` into B1
3. Paste `example` into C1

In result: cell is colored properly, but not contains value.

### Demo
http://jsfiddle.net/at19o4d8/

### Your environment
* Version: 0.28.4+
* Browser Name and version: Chrome 54.0.2840.98
* Operating System: macOS Sierra 10.12.1

**Comment by AMBudnik** [comment]
Value is not erased in 0.30.0
Working demo: http://jsfiddle.net/at19o4d8/1/
