### ISSUE TITLE
Checkbox cells - toggle many of cells is really slow

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3881]
### Description
We have a functionality which give us possibility to toggle selected cells by pressing an <kbd>SPACE</kbd>. But when is selected >200 cells is noticeable slow down on toggle.

### Steps to reproduce
1. Go to demo
2. Select column `A`
3. Press <kbd>SPACE</kbd>

In result: you have to waiting for end of toggle.

### Demo
http://jsfiddle.net/vm7ttp31/

### Your environment
* Version: 0.27.0+
* Browser Name and version: Chrome 54.0.2840.98
* Operating System: macOS Sierra 10.12.1

**Comment by swistach** [comment]
Comparison between 'text' and 'checkbox': http://jsfiddle.net/hb8r0667/
1. Open dev console
2. Select column `text`
3. Press <kbd>DEL</kbd>
5. Select column `checkbox`
6. Press <kbd>DEL</kbd>

Result: checkboxes runs `setDataAtCell` on each cell.

That's the reason of browser freezing.

**Comment by AMBudnik** [comment]
It works so much faster. Thanks for fixing @swistach 

Updated demo: http://jsfiddle.net/handsoncode/mn49vwL1/

**Comment by Sheetal1289** [comment]
Hi AMBudnik

I have handsontable with Header checkbox and each row contain checkbox. when user click on header checkbox, all  row level checkbox get selected. we are facing performance issue when more than 3000 or 4000 records in handsontable. It takes time checked. It takes more time when your are using filters.
we are using setDataAtRowProp to check the checkbox.

**Comment by AMBudnik** [comment]
Hi @Sheetal1289 
the performance issues are caused by the `afterChange` hook that is called for each of the cells after a single change (check/uncheck of a checkbox). How do you change the state of the checkboxes (`setDataAtCell`, `loadData`, `alter`)?

**Comment by AMBudnik** [comment]
You can try to detach the column with the checkboxes and attach it again with changed values - it should work faster.

**Comment by Sheetal1289** [comment]
Hi @AMBudnik 

can you please tell me how to detach the checkbox column in handsontable

**Comment by AMBudnik** [comment]
Hi @Sheetal1289 
You can use [`alter`](https://docs.handsontable.com/pro/4.0.0/Core.html#alter) method

**Comment by Sheetal1289** [comment]
Hi @AMBudnik 

Do you have any alternate solution for this ?

**Comment by AMBudnik** [comment]
Hi @Sheetal1289 

I've just got a cool and super fast demo from @swistach 
Here it is http://jsfiddle.net/aoc7yzgw/

**Comment by Sheetal1289** [comment]
Hi @AMBudnik 

I am using Handsontable Pro version in which if i try to implement this logic,when i unchecked the checkbox  then i am getting following error, can you please look into this 
Error message : Uncaught TypeError: Invalid attempt to destructure non iterable instance. Handsontable.full.min.pro.js 
Line Number :45

**Comment by AMBudnik** [comment]
Hi @Sheetal1289 

can you share a demo with this code?

**Comment by AMBudnik** [comment]
@Sheetal1289 

JSFiddle has some issues with the resources. If you refresh it a couple of times it should establish a connection to the CDN and load the Handsontable script.

**Comment by Sheetal1289** [comment]
Hi @AMBudnik 

Just wanted to know , do you have any updates regarding the issue which i am facing.

**Comment by AMBudnik** [comment]
Hi @Sheetal1289 Can we open a new issue with a working demo and a bug scenario? We shouldn't continue the conversation on an already closed issue.
