### ISSUE TITLE
How do I can make the page jump to a row？

### ISSUE THREAD

**Issue by xfliu138** [handsontable/handsontable#3884]
I currently use selectCell method to jump to a specified line, but this approach is sometimes inaccurate, is there other ways to realize the jump to a specified line effect? The following is the sample
http://jsfiddle.net/o794rfLs/1/
You can try to modify jumpToRow method in row parameters, if more than 10 positioning is not accurate

**Comment by AMBudnik** [comment]
Hi @xfliu138 
the following Fiddle does not load the table. even after changing the `localhost` to 

```
<script src="http://docs.handsontable.com/0.29.0/bower_components/handsontable/dist/handsontable.full.js"></script>
<link type="text/css" rel="stylesheet" href="http://docs.handsontable.com/0.29.0/bower_components/handsontable/dist/handsontable.full.min.css">

```
and adding jQuery lib.

I guess that `selectCell()` works as expected, example: http://jsfiddle.net/handsoncode/L1b1bLq7/
Can you update your example and show me the inaccuracy?

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply
