### ISSUE TITLE
I have problems with version 0.29.0 in IE11

### ISSUE THREAD

**Issue by jorseijo** [handsontable/handsontable#3885]
I get this exception in the console when loading the grid:

SCRIPT1028: Expected identifier, string or number
File: handsontable.full.js, Line: 144, Column: 336

Here is my code:

`$("#gridItems").handsontable({
        data: getItems(),
        autoColumnSize: true,
        autoWrapCol: true,
        autoWrapRow: true,
        afterRender: hideTHeadTBody,
        afterChange: afterChangeGrid,
        afterSelection: checkBoxAvoidSorting,
        afterOnCellMouseDown: getSelectedItem,
        afterColumnResize: resizeGrid,
        renderAllRows: true,
        colHeaders: function (index) {
...
        },
        columns: columnsGrid,
        colWidths: columnsGridWidths,
        contextMenu: {
           ...
        },
        columnSorting: true,
        copyPaste: (roleList == "Full" || roleList == "Owner" || roleList == "Ct") ? true : false,
        currentRowClassName: 'currentRow',
        currentColClassName: 'currentCol',
        enterBeginsEditing: (roleList == "Full" || roleList == "Owner" || roleList == "Ct") ? true : false,
        fillHandle: false,
        manualColumnMove: false,
        manualColumnResize: true,
        manualRowResize: true,
        manualRowMove: true,
        minSpareRows: (roleList == "Full" || roleList == "Owner" || roleList == "Ct") ? 1 : 0,
        mergeCells: true,
        multiSelect: true,
        observeChanges: false,
        outsideClickDeselects: true,
        rowHeaders: true,
        search: true,
        undo: true,
        readOnly: false,
        wordWrap: false,
        sortIndicator: true
    });
`

* Version: 0.29.0
* Browser Name and version: Internet Explorer 11
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
Hi @jorseijo 
Can you add the code to a working JSFiddle? It is really hard to read. You can work on this example http://jsfiddle.net/handsoncode/0qk44q8f/

**Comment by AMBudnik** [comment]
Issue will stay closed as there was to reply for a week.
