### ISSUE TITLE
[PRO] 1.8.0 Missing npm dependencies

### ISSUE THREAD

**Issue by groetzi** [handsontable/handsontable#3887]
### Description
Hi there, I installed handsontable-pro (v1.8.0) via npm. Seems like there are some dependencies missing (moment, pikaday, zeroclipboard, numbro) in package.json compared to bower.json. Is this intended? package.json in public repository seems fine though: https://github.com/handsontable/handsontable/blob/master/package.json
Thanks!

### Steps to reproduce
1. install pro version via npm or download zip file in account page
2. package.json defines following dependencies:
`"dependencies": {
    "hot-formula-parser": "^1.0.19"
  }`
3. bower.json defines following dependencies:
```"dependencies": {
    "hot-formula-parser": "^1.0.18",
    "moment": "^2.13.0",
    "numbro": "^1.8.0",
    "pikaday": "^1.4.0",
    "zeroclipboard": "2.2.0"
  }
```

**Comment by jansiegel** [comment]
You're right - we'll add those dependencies to `package.json`.
Thanks for noticing, @groetzi!

**Comment by AMBudnik** [comment]
Thanks again for spotting this case @groetzi 
It was added to the new version.
