### ISSUE TITLE
Validation doesn't work when use handsontable in angular2

### ISSUE THREAD

**Issue by liubiggun** [handsontable/handsontable#3888]
### Description
I use handsontable in angular2. I specify a column which is dropdown type, but the cells in that column are rendered like text editor.In addition, when I type in wrong data diffrent from source, the cell didn't have invalid class style.May there is some problem in initialization?Thanks for help.

### Steps to reproduce

1. ng new handsontable-issue --style=scss
2. npm i -S handsontable
3. paste the code:

app.component.html: 
```
<div class="params-table">

</div>

```

app.component.ts:

```javascript
import {
  Component,
  AfterViewInit,
  ElementRef,
  Input
} from '@angular/core'

declare var Handsontable

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {
  readOnly: boolean = false

  container: HTMLElement
  hotTable: any
  constructor (private hostElem: ElementRef) {
    
  }

  ngAfterViewInit () {
    this._initHotTable()
    this._setColWidths()
  }

  /*
   * HandsonTable
   */

  private _initHotTable () {
    const data = [
      ['Jack', 'male', 'yes', '123'],
      ['rose', 'female', 'yes', '123'],
      ['Jim', 'null', 'yes', '123'],
    ]

    this.container = this.hostElem.nativeElement.querySelector('.params-table')

    this.hotTable = new Handsontable(this.container, {
      readOnly: this.readOnly,
      data: data,
      undo: true,
      fillHandle: false, 
      minSpareRows: this.readOnly ? 0 : 1, 
      minSpareCols: 0,
      enterBeginsEditing: false,
      autoWrapRow: true,
      autoWrapCol: false,
      enterMoves: {row: 0, col: 1}, 
      invalidCellClassName: 'htInvalid',
      colHeaders: ['name', 'sex', 'colA', 'colB'],
      className: "htLeft htMiddle",
      columns: [
        {},
        {
          editor: 'dropdown',
          source: ['male', 'female', 'null'],
          allowInvalid: false,
        },
        {
          editor: 'dropdown',
          source: ['yes', 'no'],
          allowInvalid: false,
        },
        {}
      ],
      rowHeights: 28,
    })
  }

  private _setColWidths () {
    const containerWidth = this.container.clientWidth
    const weight = containerWidth / 25
    this.hotTable.updateSettings({
      colWidths: [weight * 11, weight * 3, weight * 2, weight * 9],
    })
  }

}
```

4. npm run

### Your environment
* Version: 0.29.0
* angular-cli: 1.0.0-beta.19-3
* angula2r: 2.1.0
* Browser Name and version:  chrome 54.0.2840.71 m (64-bit)
* Operating System: win7 64-bit

**Comment by AMBudnik** [comment]
Hi @liubiggun 
All Angular related issues should be added at https://github.com/handsontable/ngHandsontable/issues

**Comment by liubiggun** [comment]
@AMBudnik Thanks! However, the ngHandsontable is for angular1 instead of angular2

**Comment by AMBudnik** [comment]
Yes @liubiggun 
we do not support Angular 2 yet

**Comment by liubiggun** [comment]
OK, thanks for your patience, but one more question, is there a method I can hold manually ever validation of a cell?

**Comment by AMBudnik** [comment]
@liubiggun You can pass a `validator: false` in a column, like in this example: http://jsfiddle.net/handsoncode/t54g2qLs/
Although there's one issue - when you pass a string into a numeric cell type value gets erased (it's a bug that will be fixed as soon as possible).

**Comment by liubiggun** [comment]
Thanks a lot!
