### ISSUE TITLE
FixedRowsTop only can fix the loaded page

### ISSUE THREAD

**Issue by wangq228** [handsontable/handsontable#3889]
### Description
Hi.
When I use "FixedRowsTop", it can only fix the loaded page.

### Steps to reproduce

1.
2.
3.

### Your environment
* Version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @wangq228 
Can you share more details, especially by saying 

> loaded page

You mean the viewport?

**Comment by wangq228** [comment]
Yes.
For example, If the excel has A B C D E F G, 7 columns,  If viewport  only can see A B C D E F, 6 columns.
When I drag the scroll bar, only can fix A B C D E F this 6 columns, F column can not be fixed

**Comment by AMBudnik** [comment]
Currently you can freeze only one column at a time, but if you would like to scroll to a non-visible column you can hold <kbd>shift</kbd> while scrolling.

**Comment by wangq228** [comment]
You mean I need press "Shift" while scrolling?
But it can not work.
I add fixedRowsTop :2, It can only fix the visible column.

**Comment by AMBudnik** [comment]
Could you create a step by step tutorial or/and a short recording? I guess that I misunderstood this issue.

**Comment by AMBudnik** [comment]
I guess that if there were no answer for 20 days the issue can be closed.
