### ISSUE TITLE
columnSorting: true, Clearing Data from Header Input Elements

### ISSUE THREAD

**Issue by KirsteenJewell** [handsontable/handsontable#3890]
### Description

What happens:
Load list data. Enter a search term into any search box and hit return. Returns data successfully. The previous Handsontable instance is destroyed before setting the new Handsontable data/formatting load
Search terms are populated into the fields by my javascript and then the search term are cleared.

What should happen:
The search terms should not be cleared. If I remove `columnSorting: true` then the input fields are not cleared.

Background on how I got here:
Previously I was not using destroy before setting the new data/formatting. I ran into an issue where I got an error 

> row does not exist

I believe this was due to mergeCell rules (for colspan) from the previous data clashing with the new data and its mergeCell rules. Using destroy avoided these errors . Note I have not produced a jsfiddle for this "row does not exist" issue, but thought the background may help. 

### Steps to reproduce

1. Enter any search term followed by return
2. Note search term is cleared

1. Comment out `columnSorting: true,` 
2. Enter any search term followed by return
3. Note search term is not cleared

### Demo

[http://jsfiddle.net/Jewell/x21ggd6j/](http://jsfiddle.net/Jewell/x21ggd6j/)

### Your environment
* Version: 0.29.0
* Browser Name and version: Chrome Version 53.0.2785.143 (64-bit)
* Operating System: Linux Mint 17 Qiana

**Comment by AMBudnik** [comment]
Hi @KirsteenJewell 
I think that it gets erased cause `columnSorting` calls `afterGetColHeader`. You can track values added to an input and then pass them via `afterGetColHeader` after clicking <kbd>return</kbd>

**Comment by KirsteenJewell** [comment]
@AMBudnik thanks so much for your help and for coming back to me so quickly!

**Comment by AMBudnik** [comment]
@KirsteenJewell the pleasure's all mine, especially when my suggested 'trick' works. 
Give me a hint if it will.

**Comment by KirsteenJewell** [comment]
@AMBudnik yes I added:

`Handsontable.hooks.add('afterGetColHeader', function(){
        searchHandlers(); //my function to handle input values
      });
`
This does work, however it results in multitple callbacks, presumably for each ColHeader. Is there a subsequent event that I could use, that would avoid this?

Thanks again.

**Comment by AMBudnik** [comment]
Yes, `afterGetColHeader` runs for each header.
If you would like to run `searchHandlers()` function only for some headers you can use `afterGetColHeader` parameter `TH` to search for a previously defined class name
