### ISSUE TITLE
Custom cell editor documentation / use case 

### ISSUE THREAD

**Issue by jarben** [handsontable/handsontable#3891]
### Description
Adding custom cell renderer as a function is pretty well documented: 
http://docs.handsontable.com/0.29.0/Options.html#renderer

Where documentation of cell editor provided as a function is missing: 
http://docs.handsontable.com/0.29.0/Options.html#editor

I'm interested in the function case so I can add custom logic when checkbox renderer/editor are used. Renderer is pretty easy as per docs: 
```
renderer: function() {
    return Handsontable.renderers.getRenderer('checkbox').apply(this, arguments);
}
```

where editor doesn't work this way: 
```
editor: function() {
    return Handsontable.editors.getEditor('checkbox').apply(this, arguments);
}
```

Is it possible to suggest how to use custom editor and ideally add it to the docs? 

Note: I'm aware of using editor:"checkbox" directly but I'm interested in using logic to choose which editor to use. 

Thanks heaps!

### Your environment
* Version: 0.29.0
* Browser Name and version: Chrome
* Operating System: W10

**Comment by marc-antoinepelletier** [comment]
Did you have a look at http://docs.handsontable.com/0.29.0/tutorial-cell-editor.html ?

**Comment by jarben** [comment]
Thanks for your reply Marc, this tutorial deals with how to create a custom editor, including how to register it and use for the **whole column**. However, it doesn't answer my question regarding how to change an editor for one **cell** only.

[This documentation says](http://docs.handsontable.com/0.29.0/Options.html#editor): 
![image](https://cloud.githubusercontent.com/assets/561365/20596108/14b0e8a2-b23d-11e6-8f7b-1b2000cee2db.png)

Which means that it should be possible to decide which **editor** to use for a **single cell** inside **provided function**. However, there is no documentation around how to do this and it seems to be a different mechanism than how renderers work. 

My uses case is that I'd like to render checkbox cell only if value is true or false. It works with cell renderers [as per this documentation](http://docs.handsontable.com/0.29.0/Options.html#renderer), however, I can't find a way how to achive this with editor. What happens is that the cell renders as checkbox but when double clicked, it shows as value. I'd like to achieve the same behaviour as if checkbox column is used, but only for a single cell which is decided in code inside given function.. 

I hope it makes sense..

Thanks!
Jaro

**Comment by marc-antoinepelletier** [comment]
@jarben It does make sense and I am curious to know how to do that myself!

**Comment by jansiegel** [comment]
If you want to define a custom editor for a single cell, you can utilise the `cells` config option.

Take a look at this example: http://jsfiddle.net/y67tpmvn/

It's basically a simple editor (you can create it using the documentation @marc-antoinepelletier provided) assigned to cell at `(5, 5)`.

**Comment by jarben** [comment]
Thanks @jansiegel for sharing this sample, I looks like it could be used to solve this use case. 

However, what I like about renderer:function(){} is that it also provides value as a parameter which makes it easy to customize renderer based on value. 

With cells:function(){}, it only provides cell and row index. It's not a big issue as cell value can be easily obtained, however, it's not clear when the cells:function(){} is being called so it may not be guaranteed that it's called when value is changed. 

Wouldn't it be better if the editor:function(){} is same as render:function(){}?

Anyway, thanks again for your solution!
