### ISSUE TITLE
How to set the max column width?

### ISSUE THREAD

**Issue by xfliu138** [handsontable/handsontable#3892]
I want to use afterColumnResize method to control the max column width should not exceed 150 pixels.
But failed, please refer to the sample, once triggered (drag and drop a column width of more than 150 pixels), web pages, there is no response
http://jsfiddle.net/hvm5d3cc/

**Comment by AMBudnik** [comment]
You can call `modifyColWidth` like here: http://jsfiddle.net/handsoncode/e72wjaz2/

```
modifyColWidth: function(width, col){
      if(width > 150){
      	return 100
      }
    }
```

it sets the column width to `100` if user exceeds `150` px while resizing or when data is longer than the cell's body

**Comment by xfliu138** [comment]
@AMBudnik Thank you for your help, this problem has been solved

**Comment by AMBudnik** [comment]
great!

Thanks for an update

**Comment by alexon1234** [comment]
I have the same problem and I try this solution, but it has a bug when you are resizing the columns a bit and a bit. 
If you resize the column slowly, you can move it until some point when the column realised that it out of the limit and works good

**Comment by AMBudnik** [comment]
Hi @alexon1234 

Can I ask you to share a .gif/video of the behavior, please?

**Comment by omid265** [comment]
td.style.width = "50px";

**Comment by AMBudnik** [comment]
Hi @omid265 

Please create a new issue and add a description if it's a bug report.
