### ISSUE TITLE
ManualColumnFreeze breaks when columns update unless ManualColumnMove is enabled

### ISSUE THREAD

**Issue by hannahhoward** [handsontable/handsontable#3897]
### Description
Since ManualColumnMove refactor, if I have only ManualColumnFreeze on, when I change the number of columns (specifically if I increase them), then freezing columns freezes the wrong column.

The reason I believe is onAfterPluginsInitialized is only called once when grid is initialized. If manualColumnMove is set to true, it's called again every time updateSettings is called, so the underlying columns mapper array updates. However, if manualColumnMove is set to false, changing the number of columns via update settings does not call onAfterPluginsInitialized

### Steps to reproduce

1. Create a table with 4 columns, with manualColumnFreeze set to true and manualColumnMove set to false
2. Update the table to 6 columns via update settings
3. Attempt to freeze the sixth column -- likely the first column will freeze instead.

### Your environment
* Version: HOT 0.29.0 / HOT-PRO 0.18.0
* Browser Name and version: Chrome 52
* Operating System: Mac OS X

**Comment by hannahhoward** [comment]
possibly related to #3641

**Comment by AMBudnik** [comment]
connected to https://github.com/handsontable/handsontable/issues/3822

**Comment by AMBudnik** [comment]
Still an issue in v 0.31.2/1.10.2

Demo: http://jsfiddle.net/9ca6foLr/

We get `An` column frozen when we should get the `Fn` column.

**Comment by AMBudnik** [comment]
I was not able to replicate this issue in v `2.0.0`. Can you confirm that @hannahhoward ?

**Comment by AMBudnik** [comment]
I am closing this issue but if anyone has the same bug in v `2.0.0` please leave a comment

**Comment by AMBudnik** [comment]
Hi @hannahhoward 

We just fixed an issue related to yours. Please update to 8.0.0-beta1 and check if it solved for you as well.

Below are the resources

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```

And this is how you can download the beta from NPM

`npm i handsontable@beta`
