### ISSUE TITLE
Add support (CTRL left-click) Select Multiple Cells

### ISSUE THREAD

**Issue by jrt324** [handsontable/handsontable#39]
I just tested it dose not support CTRL + click Select Multiple Cells,
press the “CTRL” key and hold. While pressing “CTRL,” left-click on the cells that you wish to select. 
if support this feature, that will be greate!

**Comment by ottosson** [comment]
Any motivation as to why you won't support selection of non consecutive cells? This would be a really nice feature to have.

**Comment by AMBudnik** [comment]
Hi @ottosson 
I wouldn't want to promise anything but we are preparing to test some solutions to allow the nonconsecutive cells selection. At the first glance it sounds like an easy task, however, we also need to plan the logic for further actions that will happen in the separate areas of cells

**Comment by ottosson** [comment]
I'm sure it's not as easy as it sound, as you say. But I'll cross my fingers and look forward to this feature if it's ever implemented. =) Thank you for the answer!

**Comment by AMBudnik** [comment]
@ottosson I'd be more than happy to spread the good news as soon as it is implemented

**Comment by nadim** [comment]
Any update? I'm trying cmd-click on Mac and realized this doesn't work. Is it expected to work?

**Comment by AMBudnik** [comment]
Hi @nadim 
sorry but there's no official roadmap for 2018 yet.

**Comment by AMBudnik** [comment]
Hi guys, the feature has been just released in v 0.36.0
Here is more about it https://docs.handsontable.com/pro/1.16.0/demo-selecting-ranges.html
