### ISSUE TITLE
Incorrect documentation for Comments

### ISSUE THREAD

**Issue by nidu** [handsontable/handsontable#3905]
### Description
Documentation states [here](http://docs.handsontable.com/0.29.0/Comments.html) that to add comments programmatically you should call `commentsPlugin.editor.setCommentAtCell(1, 6, 'Comment contents');` but [this fiddle](http://jsfiddle.net/zav3ct3g/) says in console window that `editor` has no method `setCommentAtCell` and just writing `commentsPlugin.setCommentAtCell(1, 6, 'Comment contents');` works. I suppose that's an error in docs.

**Comment by AMBudnik** [comment]
@nidu is right.

It works without accessing editor of the plugin:

`http://jsfiddle.net/handsoncode/kzmm4ogd/`

We should change that in the docs.
Thanks for sharing Nikolay

**Comment by AMBudnik** [comment]
It works in the newest version.
Thanks for sharing @nidu
