### ISSUE TITLE
Accessibility support for Handsontable

### ISSUE THREAD

**Issue by nagavitalp** [handsontable/handsontable#3906]
Do you have any plan to support accessibility  (https://www.w3.org/standards/webdesign/accessibility)

**Comment by AMBudnik** [comment]
We did not discuss this topic more but I think we should.
I will add this idea as a improvement suggestion.

Thanks for sharing @nagavitalp

**Comment by AMBudnik** [comment]
Hi,

Thanks again for sharing this Feature Request. I am moving it to our Wiki Section at https://github.com/handsontable/handsontable/wiki/Feature-requests
The issue will stay closed until it'll get picked by our developer.
