### ISSUE TITLE
Unable to render formats and types for numeric in ngHandsontable

### ISSUE THREAD

**Issue by ganeshkbhat** [handsontable/handsontable#3909]
I am trying to render a single column as a numeric and unable to do it. I am using this to no effect.

`<hot-table data="myCtrl.items">
<hot-column data="percentPoints" type="'numeric'" format="'00.00 %'"  on-after-init="ceCtrl.onAfterInit" width="ceCtrl.capShow.width/11" ></hot-column>
<hot-column data="price" type="'numeric'" format="'00,000.00'"  on-after-init="ceCtrl.onAfterInit" width="ceCtrl.capShow.width/11" ></hot-column>
</hot-table>`

### Demo
NA, not other issues. Its a simple implementation

### Your environment
* Version: Recent downloaded from github
* Browser Name and version: IE 11, Chrome latest, Firefox
* Operating System: Win7, Windows latest

**Comment by AMBudnik** [comment]
Closing this issue as it is a duplicate from: https://github.com/handsontable/ngHandsontable/issues/195

ps. here's a demo that uses types of cells via column settings:
http://handsontable.github.io/ngHandsontable/demo/index.html#/intro-full-featured-demo
