### ISSUE TITLE
<select> in cell / custom cell editor

### ISSUE THREAD

**Issue by matkus** [handsontable/handsontable#391]
Hello

I want to have in one cell only numeric values, that is ID of something.
So i've decided to make custom renderer and print < select > insted of cell value.
But there is one big problem - i can't select anything. Select is rendered correctly as closed, but i can't expand it, and even if i do, it is closes imediately. 

Any idea how to bypass it?
Or maybe better, maybe there is way to show this < select > insted of default <input> when editing?

**Comment by motin** [comment]
Afaik, this is not possible currently without a plugin like https://github.com/trebuchetty/Handsontable-select2-editor/

**Comment by tdjun** [comment]
I made new cell type which was customized autocomplete.
https://github.com/tdjun/Handsontable-autocomplete2

**Comment by AMBudnik** [comment]
Hi, can you share a final conclusions about this subject?
