### ISSUE TITLE
[PRO] hot-formula-parser missing bower.json

### ISSUE THREAD

**Issue by marc-antoinepelletier** [handsontable/handsontable#3910]
I was trying to setup the pro version of Handsontable using grunt as a task runner. I am also using `grunt-wiredep` package to inject my bower components into my html file.
The issue here is that there is no `bower.json` in the `hot-formula-parser` package. We have a `.bower.json` but even so there is no `main` property inside.

I've copied the `.bower.json` into `bower.json` added the `main` property with `dist/formula-parser.js` and it works as intended.

Maybe it has been forgotten ? 

Forgot to say that I am using the latest version 1.8.0 of Handsontable-pro

**Comment by marc-antoinepelletier** [comment]
@AMBudnik Any news about this issue ?

**Comment by AMBudnik** [comment]
I just tested it and you're right. Building a package like this is pretty problematic. I will ask our devs to take a look at it.

**Comment by AMBudnik** [comment]
@marc-antoinepelletier 
Thanks for reminding. We've added the bower package manager.
https://github.com/handsontable/formula-parser/releases/tag/1.0.20

**Comment by marc-antoinepelletier** [comment]
Thank you for the fix ! :)
