### ISSUE TITLE
Which version support ie8

### ISSUE THREAD

**Issue by Superman379** [handsontable/handsontable#3911]
### Steps to reproduce

im so sorry about that im not good at english -^-
1.please is which branch support ie8?
2.How can I assign each cell individually editor?
  like this
  
![image](https://cloud.githubusercontent.com/assets/13028187/20592892/e4e8005a-b26a-11e6-8418-43460a21bb24.png)

I just want to set the Units column the second cell to select type.

**Comment by AMBudnik** [comment]
Hi @Superman379 

We dropped support for IE8 some time ago, in version 0.12.0 ([release note](https://github.com/handsontable/handsontable/releases/tag/0.12.0)) so all versions below should work in IE8.

When it comes to your second question you could use the [`cells`](https://docs.handsontable.com/pro/1.8.0/Options.html#cells)method. Here's a similar example for dropdown cell type: http://jsfiddle.net/L8f4agh9/1/ so in your example the statement will be
`
if (row === 1 && col === 1) {}`

**Comment by Superman379** [comment]
@AMBudnik 
Thank you so much.
