### ISSUE TITLE
Handsontable whether can run in Linux environment firefox browser

### ISSUE THREAD

**Issue by xfliu138** [handsontable/handsontable#3913]
Present handsontable version can be run in Linux environment firefox browser?
I tried (test environment: Red Hat Enterprise Linux Server release 5.4), but the page shows a blank

**Comment by AMBudnik** [comment]
Hi @xfliu138 
It should, however I can also use only a virtual machine to test it.

**Comment by budnix** [comment]
Hi @xfliu138, Can you check which Firefox version do you use?

**Comment by xfliu138** [comment]
![image](https://cloud.githubusercontent.com/assets/18605877/20618775/e911fee4-b32b-11e6-8ed2-2d8a9f92523d.png)

**Comment by xfliu138** [comment]
Thank you, I  try to install the latest version of firefox
