### ISSUE TITLE
The render method is called each time the selected cell goes beyond leftmost column 

### ISSUE THREAD

**Issue by Adelor** [handsontable/handsontable#3915]
### Description
If the [viewportColumnRenderingOffset](http://docs.handsontable.com/0.29.0/Options.html#viewportColumnRenderingOffset) property is not set, then it will be set to 'auto' by default. This leads to the error in the viewportColumnCalculatorOverride method:

~~~~
   viewportColumnCalculatorOverride: function(calc) {
      var cols = instance.countCols();
      var viewportOffset = that.settings.viewportColumnRenderingOffset;
      if (viewportOffset === 'auto' && that.settings.fixedColumnsLeft) {
        viewportOffset = 10;
      }
      if (typeof viewportOffset === 'number') {
        calc.startColumn = Math.max(calc.startColumn - viewportOffset, 0);
        calc.endColumn = Math.min(calc.endColumn + viewportOffset, cols - 1);
      }
      if (viewportOffset === 'auto') {
        var center = calc.startColumn + calc.endColumn - calc.startColumn;
        var offset = Math.ceil(center / cols * 12);
        calc.startRow = Math.max(calc.startColumn - offset, 0);
        calc.endColumn = Math.min(calc.endColumn + offset, cols - 1);
      }
      instance.runHooks('afterViewportColumnCalculatorOverride', calc);
    },
~~~~

It should be calc.startColumn instead of calc.startRow like in the typeof viewportOffset === 'number' condition.
Also the following line is strange:
`var center = calc.startColumn + calc.endColumn - calc.startColumn;`
The center cant be equal to the end column.

Because of the typo above, the render mechanism doesn't render any offset columns on the left.

### Steps to reproduce
1. Open the [scrolling demo](https://docs.handsontable.com/0.29.0/demo-scrolling.html)
2. Scroll right till the end with scrollbar
3. Select any cell
4. Press and hold the left arrow key
You will see performance issues right away

### Demo
[scrolling demo](https://docs.handsontable.com/0.29.0/demo-scrolling.html)

### Your environment
* Version: 0.29.0

**Comment by AMBudnik** [comment]
Hi @Adelor 
You're using IE or Edge?
I've tested in on Chrome 54 (Win 10) and it works fast.

![scrolling](https://cloud.githubusercontent.com/assets/10757813/20665221/06a03158-b55f-11e6-85ba-f07a2f7abf6c.gif)

**Comment by Adelor** [comment]
I use Chrome 54.0.2840.99 m on Win8
I don't think the environment has to do anything with it, since there's clearly a bug in code: it uses startColumn and endColumn if typeof viewportOffset === 'number', but **startRow** and endColumn if viewportOffset === 'auto'

Here's a screencast:
![screencast 2016-11-28](https://cloud.githubusercontent.com/assets/779544/20667459/6528c404-b57a-11e6-853a-f599198d2523.gif)

**Comment by AMBudnik** [comment]
I'm not getting it with Chrome but got it with FF 50 (same poor performance).
Thanks for sharing - we should investigate this issue.

**Comment by AMBudnik** [comment]
Still replicable in some browsers with v0.31.0

**Comment by AMBudnik** [comment]
Using version 7.4.2 does not differ between Chrome and FF https://handsontable.com/docs/7.4.2/demo-scrolling.html 

As there's already a topic regarding performance on Firefox https://github.com/handsontable/handsontable/issues/6576 so I'm closing this issue.
