### ISSUE TITLE
Backspace / Delete keyboard event has undefined source in beforeChange.

### ISSUE THREAD

**Issue by theengineear** [handsontable/handsontable#3916]
### Description
Source for *delete* events in the table is `undefined` in `beforeChange`.

### Steps to reproduce
1. Define a `beforeChange` function.
2. Load up a `new Handsontable` with the `beforeChange` setting set to the above function.
3. Note that on `delete` keyboard events, the source is `undefined` in before change.

### Demo
http://jsfiddle.net/theengineear/mh6hvjaq/1/

### Your environment
* Version: Latest.
* Browser Name and version: Chrome 54.0.2840.98 (64-bit)
* Operating System: OSX 10.11.6

**Comment by theengineear** [comment]
The workaround I'm going to use for now is to allow `undefined` as a source (with a defined `changes` array) and assume it's happening because of a *delete* event.

Thanks for the product! Let me know if you need more info from me.

**Comment by AMBudnik** [comment]
Thanks for spotting this issue. It should be marked as `edit`

**Comment by krzysztofspilka** [comment]
@pnowak looks good to me http://jsfiddle.net/j3jn0str/

**Comment by AMBudnik** [comment]
Hi @theengineear 

I am happy to announce that this issue has been solved in version CE 0.38.0 /PRO 1.18.0

Again thanks for sharing 

ps. @aacampillo @exytab @chriddyp
