### ISSUE TITLE
When the bottom cell is reached after enter to go back at the top of the next column

### ISSUE THREAD

**Issue by m7vm7v** [handsontable/handsontable#3917]
### Description
Hi, is there any way to auto change the cell when you hit the enter on the bottom cell so after it will go to the top of the next column

### Steps to reproduce

1.You have reached the bottom of all the cells in the column
2.Hit Enter 
3.Goes to the top of the next column

Thanks fot helping me

**Comment by AMBudnik** [comment]
Hi @m7vm7v 
I think that this may come in handy: https://docs.handsontable.com/pro/1.8.0/Options.html#enterMoves
Here's a working example: http://jsfiddle.net/0manL13r/
