### ISSUE TITLE
Rendering tables withing collapsible div's

### ISSUE THREAD

**Issue by yawlhead91** [handsontable/handsontable#3918]
Hi I am using this package with  MeteorJs I am trying to have tables within collapsible divs using Materialize as my framework. I am having issues with the render . When the divs are first opened the tables are all out badly rendered like so .   

![capture](https://cloud.githubusercontent.com/assets/15271739/20642945/67a519ba-b414-11e6-84db-87d16a3a6c22.PNG)

But when I click into the tables they seem to fix them self's, like so 

![capt3ure](https://cloud.githubusercontent.com/assets/15271739/20642948/7c11ca6a-b414-11e6-97e4-1152927f3851.PNG)

I have created simpler version here on  js fiddle
http://jsfiddle.net/yawlhead91/9xpo0ccp/3/

I have two table in one div just to show that in some cases i will have more than one table within a div ..  

So if any one could help with this because i have been stuck for quiet sometime now . 

Thanks 👯

**Comment by AMBudnik** [comment]
I can see that firstly tables are bounded together and when we scroll they part from each other. It is really hard to tell what option does the change when it comes to Materialize as it changes nearly all HTML element styles: `table`, `th`, `tr`, `td`

**Comment by yawlhead91** [comment]
Thanks for the reply @AMBudnik . What would you recommend. Maybe using another third party for the collapsible.

**Comment by AMBudnik** [comment]
Are you loading Materialize before or after loading Handsontable CSS? You could check in the developer tools what styles are overwritten by Materialize.

**Comment by yawlhead91** [comment]
Handsontables is loaded after Materialize . I went through every style , it is not the materialize. I recreated a example again with just jquery same things happens. 

http://jsfiddle.net/yawlhead91/qfth2vbp/1/

If you see inside the second drop down div the table must be clicked on again to get the full body to show. Since materialize in not involved here would you think it must be something to do the handsontables ? Thanks for you help again

**Comment by AMBudnik** [comment]
Thank you for sharing this demo @yawlhead91 
I will mark this issue as a bug

**Comment by yawlhead91** [comment]
@AMBudnik  Thanks :D keep up the good work . The package is great.

**Comment by yawlhead91** [comment]
Hi Is there any new on this issue. We are coming to the end of our current project, with this issue being the only one left. 

Thanks for your time

**Comment by AMBudnik** [comment]
Hi @yawlhead91 
I have investigated the case and it looks like setting `height` for the second table solves the issue: http://jsfiddle.net/ns05300w/

**Comment by yawlhead91** [comment]
Hey thanks @AMBudnik , You guys have been great. 

Thanks a million

**Comment by AMBudnik** [comment]
Thank you for your kind words Alex. We're always happy to help :)
