### ISSUE TITLE
nested rows and column sorting doesn't work together as expected

### ISSUE THREAD

**Issue by mpetris** [handsontable/handsontable#3919]
### Description
With nested rows and column sorting enabled, sorting a column breaks up the hierarchy of the nested rows. While this may be a desired special case behaviour the default behaviour should respect the row hierarchy and keep nested rows close to its parent rows. 

### Steps to reproduce

1. Use the jsfiddle demo for nested rows
2. Enable column sorting 
3. Sort column 'Category' or 'Artist'

### Demo
http://jsfiddle.net/7pu442t2/

### Your environment
* Version: 1.7.5
* Browser Name and version: Firefox 50.0
* Operating System: Windows 10 Home

**Comment by AMBudnik** [comment]
Hi @mpetris 

We are aware that it does work this way but still we should add an option to sort data inside parent.

**Comment by AMBudnik** [comment]
Hi,

Thanks for sharing this Feature Request. I am moving it to our Wiki Section at https://github.com/handsontable/handsontable/wiki/Feature-requests
The issue will stay closed untill it'll get picked by our developer.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
