### ISSUE TITLE
How do I modify option value attribute about select editor

### ISSUE THREAD

**Issue by Superman379** [handsontable/handsontable#3920]
### Steps to reproduce

hello @AMBudnik
1.can i contorl select editor property ,like this : `<option value = '1'>apple</option>`
2.And my project run very slowly when it on ie,but chrome has no problems.

**Comment by AMBudnik** [comment]
Hi @Superman379 
I'm not sure if that is what you wanted but here: https://docs.handsontable.com/pro/1.8.0/demo-select.html is an example of use and the `value` is always the same as the text inside an option. Currently it cannot be changed.
