### ISSUE TITLE
rowsPreCalculator is undefined

### ISSUE THREAD

**Issue by Superman379** [handsontable/handsontable#3921]
### Description

1.debug info is that rowsPreCalculator is undefined

 ` var visibleColIndex`
 `, totalRows = this.instance.getSetting('totalRows')`
   ` , totalColumns = this.instance.getSetting('totalColumns')`
    `, displayTds`
    `, adjusted = false`
   ` , workspaceWidth`
   ` , cloneLimit = this.instance.wtViewport.rowsPreCalculator.countRendered;`

![image](https://cloud.githubusercontent.com/assets/13028187/20778949/57e73058-b7ac-11e6-89d1-71667b6b60e4.png)

See it , wtViewport doesnot have rowsPreCalulator prop.

**Comment by AMBudnik** [comment]
Hi @Superman379 
Please send us a working JSFiddle demo.

**Comment by Superman379** [comment]
Hi @AMBudnik 
First, I am sorry about that project code classified.
Then, It only happend on ie8 environment ,chrome has no problem, and it looks like that  it happen when i use setDataAtCell method.
Last, tables are normal rendering although there are some errors.

**Comment by AMBudnik** [comment]
I am sorry but we do not support IE8 anymore, as we already disscussed here: https://github.com/handsontable/handsontable/issues/3911
