### ISSUE TITLE
Handsontable run very slowly on ie.

### ISSUE THREAD

**Issue by Superman379** [handsontable/handsontable#3922]
### Description

1.why handsontable run very slowly on ie. I just draw six tables and 10 rows of data;
  On the other hand,it run very well on chrome;
CPU%
![image](https://cloud.githubusercontent.com/assets/13028187/20784073/f268a50a-b7d2-11e6-8e3a-b9a2aa5c51f4.png)
FPS
![image](https://cloud.githubusercontent.com/assets/13028187/20784115/36c91f90-b7d3-11e6-9b53-a2f165d31614.png)

**Comment by AMBudnik** [comment]
Hi @Superman379 

We have already an issue related to lower performance on IE at https://github.com/handsontable/handsontable/issues/2350

If you found any other clues please share them at https://github.com/handsontable/handsontable/issues/2350

Thanks!
