### ISSUE TITLE
Reverse Selecting Cells Doesn't Apply Changes To Borders Or Alignment

### ISSUE THREAD

**Issue by JohnTendik** [handsontable/handsontable#3923]
### Description

If you select cells (range) going from left-right:top-bottom, the context menu options work as expected, but if you select in the opposite direction, right-left or bottom-top, the options do not apply for both alignment and custom borders. 

First selection method works:
![selection1](https://cloud.githubusercontent.com/assets/4714913/20809100/d08fc346-b7b9-11e6-9c75-c64c558ccfd5.jpg)

Second selection method (backwards) does not work for alignment or borders
![selection2](https://cloud.githubusercontent.com/assets/4714913/20809119/defac048-b7b9-11e6-834d-d0e19b889167.jpg)

### Steps to reproduce

1. Select cells in reverse order
2. Try to apply custom borders or alignment to cells
3. Cry 

### Demo

Here is a fiddle (this is yours from the site)
http://jsfiddle.net/pkzLf0ys/

### Your environment
* Version: 0.29.0 or latest
* Browser Name and version: Chrome 54 I believe
* Operating System: Windows/Mac

I may be completely off on my assumption here so forgive me if I am but I did a little bit of digging around I believe the issue may reside somewhere here or similar area: This is in the align(range, type, alignment, cellDescriptor) function / Context menu / utils.js

`
for (let row = range.from.row; row <= range.to.row; row++) {
      for (let col = range.from.col; col <= range.to.col; col++) {
        applyAlignClassName(row, col, type, alignment, cellDescriptor);
      }
}
`
If you select in reverse order, range.from.row is not less than range.to.row, so therefore this function will not run :/ I believe the same issue is with the custom borders. 

I hope this helps, and thank you for the awesome work and effort you put into Handsontable!

**Comment by AMBudnik** [comment]
Hi @JohnTendik 
Thanks for sharing this issue and for your investigation. This is an interesting bug.

**Comment by AMBudnik** [comment]
I'm not able to replicate this issue. Also tried it here - with a simplified example v`2.0.0` at http://jsfiddle.net/dcLo34qy/

![gif](https://user-images.githubusercontent.com/10757813/39115713-d70afb50-46e2-11e8-9345-49568a85dcbe.gif)
