### ISSUE TITLE
Improper column stretching with column misalignment - StretchH

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3925]
### Description

> In some cases the column stretching results in mismatched column headers and the table.

continued from: https://github.com/handsontable/handsontable/issues/3732, reported by @varun-dev 

![stretchh](https://cloud.githubusercontent.com/assets/10757813/20826913/a7c17f4e-b86e-11e6-8fa2-0a0660e96330.gif)

### Steps to reproduce

> In the demo, please click on the button at the top to change data from 1000 rows to 5 rows and you will notice the header issue.

### Demo

http://jsfiddle.net/5hqo46w9/

### Solution
It seems that after calling the table renderer columns are aligned properly. Demo: http://jsfiddle.net/yL0125vj/

### Your environment
* Version: 0.32.0
* Browser Name and version: Chrome 54
* Operating System: Windows 10

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/2349

**Comment by JohnTendik** [comment]
Hey I don't want to butt in but while working with Handsontable I noticed this as well. What I did was to call the hot.render() method after significant changes to the table like removing/adding rows or columns, loading in new data, etc. If you call the hot.render() method after the alteration of the table it seems to fix itself, however sometimes it doesn't work so I included a custom trigger for a window resize. Instead of calling ,render all the time, I'm calling a window.resize method which also seems to fix the issue. Try it out here :

http://jsfiddle.net/pp9dpLqy/

**Comment by varun-dev** [comment]
@JohnTendik - this is a workaround, and if you have a fairly large table with lot of data, renders are very expensive. On top of that rendering in latest IE is 3 times slower than Chrome.

**Comment by PavelStefanov** [comment]
Please fix it

**Comment by AMBudnik** [comment]
Hi @PavelStefanov seems that adding a `render()` method does the job. Here's a demo http://jsfiddle.net/o6aqnkqa/

Please test it in your project and let me know.

**Comment by PavelStefanov** [comment]
Hi @AMBudnik. Yes, `render()` solves issue. After `loadData` already fire render. But call it second time it's hack

**Comment by AMBudnik** [comment]
Thanks for the confirmation.

Yes, it is a workaround, not a fix :)

**Comment by AMBudnik** [comment]
Works the same in v0.34.3

**Comment by JohnTendik** [comment]
Does calling window.resize automatically re-render the table?

**Comment by AMBudnik** [comment]
@JohnTendik yes it is re-rendering the table.

**Comment by AMBudnik** [comment]
The issue remains the same in version 0.35.1

**Comment by AMBudnik** [comment]
works the same using v `7.1.0` http://jsfiddle.net/handsoncode/bpfwqxok/

**Comment by AMBudnik** [comment]
http://jsfiddle.net/handsoncode/gbux2L9t/ (updated to `7.1.2` works the same)

**Comment by AMBudnik** [comment]
This issue works the same in v8.0.0. http://jsfiddle.net/AMBudnik/rg7kmL23/

I've also wanted to share **case 2** that seems to be related to the length of the 5th-columns data while using `loadData()` method.

Demo https://jsfiddle.net/AMBudnik/zmoqcges/ (v8.0.0)
Result
![Zrzut ekranu 2020-08-27 o 11 03 02](https://user-images.githubusercontent.com/10757813/91420366-e67bee80-e854-11ea-8427-07e87e4bafdf.png)

**Comment by AMBudnik** [comment]
### Case 3
#### Larger content in a cell
Previosuly reported separately here https://github.com/handsontable/handsontable/issues/5701 
https://jsfiddle.net/ne6xbwv1/ (v8.2.0) - enable `autoRowSize` to see the misalignment.

`autoRowSize` off
![image](https://user-images.githubusercontent.com/10757813/104913265-a1846000-598d-11eb-854a-d685b9172453.png)

`autoRowSize` on
![image](https://user-images.githubusercontent.com/10757813/104913332-bcef6b00-598d-11eb-9d1c-9a85bf43d2a6.png)

**Comment by budnix** [comment]
Still not working with 9.0 http://jsfiddle.net/budnix/jrbL6c8f/. The same happens when you try to add/remove the row using the context menu.

**Comment by AMBudnik** [comment]
Hi @JohnTendik @PavelStefanov @varun-dev  

This issue is no longer replicable. Please update to v15.0.0 to test it. Here's the updated demo https://jsfiddle.net/ejyhkLs3/.
