### ISSUE TITLE
Formula Pro handsontable

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#3926]
hello,
for the moment, we use the free handsontable version with old plugin formula.
we think to migrate to the pro version , but the formula plugin seems to be in alpha step.
do you have an estimated date for a stable formula new plugin ?

best regards
jean marc

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 
it is one of our priorities for 2017 but we do not have a specified dead-line yet.
