### ISSUE TITLE
Undo/redo doesn't work with sorting

### ISSUE THREAD

**Issue by raethlo** [handsontable/handsontable#3929]
### Description
An undo/redo after sorting the table causes updates on a wrong position in the table.

### Steps to reproduce
1. https://docs.handsontable.com/0.29.0/demo-sorting.html
2. edit a cell (for example in the last row)
3. sort the table so that the position of the edited cell would change
4. undo (incorrectly changes the value on the original position)
5. sort again
6. redo (incorrectly changes the value on the original position)

### Environment
* Version: 0.29.0
* Chrome Version 54.0.2840.98 (64-bit)
* macOS Sierra 10.12.1

**Comment by AMBudnik** [comment]
Hi @raethlo 
thanks for sharing.

We have already 3 related issue:
https://github.com/handsontable/handsontable/issues/1520
https://github.com/handsontable/handsontable/issues/1516
https://github.com/handsontable/handsontable/issues/3188

Do you think that any of mentioned subject could relate to the same genesis of the bug?

**Comment by AMBudnik** [comment]
Further conversation and bug fixes should be made at https://github.com/handsontable/handsontable/issues/3188

**Comment by AMBudnik** [comment]
### Case 2 - `autofill`
https://jsfiddle.net/gtrkhcao/2/ (v8.4.0, it is not a regression)
1. Autofill `mercedes` from `A1` to `B1` Year column)
2. Sort Year column
3. Click <kbd>CMD/CTRL</kbd> + <kbd>Z</kbd> to undo


**Result**
The wrong value is reverted (Citroen value changes) and `mercedes` value still stays in the Year column.

![bug](https://user-images.githubusercontent.com/10757813/119959206-11da6800-bfa4-11eb-9529-fdf07985fd34.gif)
