### ISSUE TITLE
Handstable runs very slowly when I draw some table with a page.

### ISSUE THREAD

**Issue by Superman379** [handsontable/handsontable#3931]
### Description
 Environment is ie.
 I draw a dozen tables at the same time with a page,then Handsontable run very slowly.
 I dont need all features,in fact I just need to display and simple edit.
 Is there any way which  use to optimize?
 Thank you.

### Demo

`<div id="grid1"></div>`
`<div id="grid2" style="margin-top: 50px"></div>`
`<div id="grid3" style="margin-top: 50px"></div>`
`<div id="grid4" style="margin-top: 50px"></div>`
`<div id="grid5" style="margin-top: 50px"></div>`
`<div id="grid6" style="margin-top: 50px"></div>`
`<div id="grid7" style="margin-top: 50px"></div>`
`<div id="grid8" style="margin-top: 50px"></div>`
`<div id="grid9" style="margin-top: 50px"></div>`
`<div id="grid10" style="margin-top: 50px"></div>`
`<div id="grid11" style="margin-top: 50px"></div>`
`<div id="grid12" style="margin-top: 50px"></div>`
`<div id="grid13" style="margin-top: 50px"></div>`
`<div id="grid14" style="margin-top: 50px"></div>`
`<script>`
 `   window.onload=function () {`
  `      for(var i = 1; i < 15; i++){`
   `         new Handsontable(document.getElementById('grid'+i), {`
    `            data:[[1,1,1,1,1,1,1],`
     `               [1,1,1,1,1,1,1],`
      `              [1,1,1,1,1,1,1],`
       `             [1,1,1,1,1,1,1],`
        `            [1,1,1,1,1,1,1],`
         `           [1,1,1,1,1,1,1],`
          `          [1,1,1,1,1,1,1],`
           `         [1,1,1,1,1,1,1],`
            `        [1,1,1,1,1,1,1],`
             `       [1,1,1,1,1,1,1],`
              `      [1,1,1,1,1,1,1],`
               `     [1,1,1,1,1,1,1],`
                `    [1,1,1,1,1,1,1]]`
`            })`
 `       }`
  `  }`
`</script>`

### Your environment
* Version: 0.20.0+
* Browser Name and version: IE
* Operating System: Windows 10

**Comment by Superman379** [comment]
I remove resive,scroll,mousemove eventListen ,then it run well.
Is that right?

**Comment by AMBudnik** [comment]
Hi @Superman379 
It would be so much better if you could create a JSFiddle/JSBin or CodePen demo. If it still does not work as expected.

**Comment by Superman379** [comment]
Hi @AMBudnik 
demo link:
[http://jsfiddle.net/xgLzuk3c/](url)
it scroll slowly in ie.

**Comment by AMBudnik** [comment]
Hi @Superman379 
Thanks for sharing the example.

I've tested in on Internet Explorer 11 on Windows 10 and on my PC it looks as expected.

![ie-browser-example](https://cloud.githubusercontent.com/assets/10757813/20961338/e66ff3de-bc64-11e6-8b52-d81c2e4ace22.gif)

Do you get the same performance? If not please share a video and more details about your device.

**Comment by Superman379** [comment]
![gif](https://cloud.githubusercontent.com/assets/13028187/21035480/6068704e-bdfa-11e6-8e74-401b53a75982.gif)

Like this, Fast roll several times,then stop roll ,but brower doesnt stop roll .
And when u roll multi-line ,browser alaways can only rollling line.

This is my computer.
![image](https://cloud.githubusercontent.com/assets/13028187/21035630/5b0d25e4-bdfb-11e6-9bf2-fb3080192fdd.png)
OS is window 10.
Lenovo think centre.

**Comment by Superman379** [comment]
Another problem,can u tell me where Handsontable call event 'afterValidation'.
I read the source code,I find code like :

      `this.state = Handsontable.EditorState.WAITING;`
      `this.saveValue(val, ctrlDown);`          // Here, I find some code looks like method which used to verify ,but I dont understand why put it before  `this.instance.addHookOnce('afterValidate'`
      `if(this.instance.getCellValidator(this.cellProperties)){`
        `var that = this;`
        `this.instance.addHookOnce('afterValidate', function (result) {`//Here, I dont understand how to trigger events.
          `that.state = Handsontable.EditorState.FINISHED;`
          `that.discardEditor(result);`
        `});`
      `} else {`
        `this.state = Handsontable.EditorState.FINISHED;`
        `this.discardEditor(true);`
     ` }`

**Comment by AMBudnik** [comment]
Hi @Superman379 
I guess that we can't do anything that will boost this behavior now.

Answering your second question, we do not have a callbacks named `afterValidation` maybe you were thinking about [`afterValidate`](https://docs.handsontable.com/pro/1.8.0/Hooks.html#event:afterValidate)

**Comment by Superman379** [comment]
@AMBudnik
That's unfortunate.

In the second question ,I think I already understand the process,and still very thank you for your answer.

At last ,I find handsontable redraw table when I setDataAtCell although the data doesnt change(I set same data at cell or I just open the editor and close it ), U know draw table is very slowly(in some old browser like ie) ,so do you have the relevant optimization plan.

**Comment by AMBudnik** [comment]
Today we will have a Planning Roadmap meeting so I do not know yet what will come. However I know that the performance as a general subject will be one of our priorities. 

ps. There's already an [IE related section in our Github board](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3AIE%2FEdge ) also stating issues with performance. As I was informed it is a pretty tough subject as most of boosting technics that work for all the other browsers do not work in IE cause of its limitations.

**Comment by Superman379** [comment]
Thank you.
I know it is hard for IE optimization,but many people are still using ie.It is very helpless.Anyway, I hope that if you have a plan please let me know.thank you. @AMBudnik

**Comment by AMBudnik** [comment]
I'm closing this issue as generally it is very similar to https://github.com/handsontable/handsontable/issues/2350
