### ISSUE TITLE
Instead of overrding the existing data ,paste data with new inserted row.

### ISSUE THREAD

**Issue by SuhasiniD** [handsontable/handsontable#3932]
### Description

I have a requirement like I need to select more than one rows and then copied, while pasting the data, create news rows(how many i have selected) and then paste the data accordingly.
### Steps to reproduce

1.  
2.
3.

### Your environment
* Version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @SuhasiniD 
You can use `alter()` method to add new rows like `instance.alter('insert_row', index, amount)`
However I'm not sure where and how you would like to paste data and where the new rows should appear.
If you could share a draft or an image it will be much easier to help.

**Comment by SuhasiniD** [comment]
![hot](https://cloud.githubusercontent.com/assets/24251679/20924238/83af2258-bbd6-11e6-9658-2f7d920ef699.png)


Let us take above example , i have selected 3 rd and 4th rows and right click choose the copy option, then my cursor in the  5th row and right click and choose the paste option, Now my result would be create new two rows under 5th row and paste the (3rd and 4th rows) data .(6th row data would be like that only it wont be overridden while pasting).

**Comment by AMBudnik** [comment]
Hi @SuhasiniD 
In this example you can see how to add as many rows at the end of the table as there were selected: http://jsfiddle.net/6vxysbyz/
If you would like to paste the data automatically you would need to use `loadData()` with an array of selected cells.

**Comment by SuhasiniD** [comment]
Hi AMBudnik,
Thanks you for your response.
Here my requirement is not adding the new row at the end, please find the detailed explanation below.

1) How can get the number of rows copied(after selecting the rows then right click and copy), Find the below image  for reference.
![copypaste1](https://cloud.githubusercontent.com/assets/24251679/20963887/4e2610aa-bc95-11e6-9567-1ae95d95a380.JPG)

2) See the below image, my cursor potion is in 5th row, then right click and choose the paste option, then my result would be data would be pasted with new two rows at a time.(Between 5th and 6th row).

![image](https://cloud.githubusercontent.com/assets/24251679/20964024/de3e329e-bc95-11e6-9ee4-5579f2a3c05a.png)
                     
                        callback: function (key, options) {
                           
                            if  (key === 'paste')
                            {
//NEED LOGIC HERE
                           }
                        }

**Comment by AMBudnik** [comment]
Hi @SuhasiniD 

Thank you for detailed explanation. Unfortunately we do not have a copy callbacks. However you can track selected rows and then hold their values. Here's an example: http://jsfiddle.net/h6hvhf47/

And then you just need the paste option that will just run `loadData()` or `setDataAtCell()` to load your `dataToHold` array of arrays after using `alter()` method to load new blank rows.
