### ISSUE TITLE
How to get the column header position

### ISSUE THREAD

**Issue by SuhasiniD** [handsontable/handsontable#3933]
### Description

Lets take below table,My initial screen columns are shown below.
![image](https://cloud.githubusercontent.com/assets/24251679/20964550/039b55ec-bc98-11e6-95c4-eb6b3de2d174.png)
Now i have moved the columns
![image](https://cloud.githubusercontent.com/assets/24251679/20964497/c9d03dfa-bc97-11e6-8d4f-23d6753fd6f0.png)

Can we get the position of the columns, because i need to save the data accordingly to database and fetch it as it is. (i.e when the same user  run the program again he can able to see the second image not the first one).
### Steps to reproduce

1.
2.
3.

### Your environment
* Version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @SuhasiniD 
You can use the `afterColumnMove` callback to track which column/s has been moved. This callback will return a start and end index.

Here's a demo: http://jsfiddle.net/7g2ehaxh/
