### ISSUE TITLE
afterRowMove

### ISSUE THREAD

**Issue by stachg** [handsontable/handsontable#3934]
### Description
for #3845 fiddle example if we change afterRowMove: function(){console.log('moved')} to afterRowMove: function(a, b){console.log('moved a,b:", a, b)} and move a row multiple times between different location the 'a' remains the same. I would expect it to be changing. For instance if I move row 2 to 4 and then from 4 to 0 I would expect getting 2,4 and 4,0, What I am getting instead is 2,4 and 2,0. Is it an expected behaviour? 

### Steps to reproduce
1. 
2. 
3.

### Demo

http://jsfiddle.net/eLobx8sm/1/

### Your environment
* Version:
* Browser Name and version: firefox 45.5.1
* Operating System: slackware 14.2

**Comment by AMBudnik** [comment]
You're right @stachg 
the docs is mixing `visual` and `logical` terms.
`a` is a logical index, that is why it is not changing.

**Comment by stachg** [comment]
But logical index ("a" in my example) gets eventually updated. When does it happen? Can I do it programatically? I couldn't find anything in the docs.

--------------------------------------------
On Thu, 12/8/16, Aleksandra Budnik <notifications@github.com> wrote:

 Subject: Re: [handsontable/handsontable] afterRowMove (#3934)
 To: "handsontable/handsontable" <handsontable@noreply.github.com>
 Cc: "stachg" <stanislaw.grygiel@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Thursday, December 8, 2016, 12:44 AM
 
 You're right @stachg
 
 the docs is mixing visual and
 logical terms.
 
 a is a logical index, that is why it is not
 changing.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by AMBudnik** [comment]
The issue is no longer up-to-date. Currently the `a` (first) parameter represents a visual index 

src: http://docs.handsontable.com/0.32.0/Hooks.html#event:afterRowMove


Name | Type | Description
-- | -- | --
rows | Array | Array of visual row indexes that were moved.
target | Number | Visual row index being a target for moved rows.
