### ISSUE TITLE
giving console errors while mouse over on a cell which has comments.

### ISSUE THREAD

**Issue by syamdanda** [handsontable/handsontable#3935]
### Description
I have a cell which has comments enabled. When I mouse over on the cell to see the comments, the comments are displayed properly but I am also having below errors in console.

handsontable.full.min.js:251 Uncaught TypeError: Cannot read property 'position' of undefined(…)y @ handsontable.full.min.js:251refreshEditorPosition @ handsontable.full.min.js:253show @ handsontable.full.min.js:253onMouseOver @ handsontable.full.min.js:253(anonymous function) @ handsontable.full.min.js:253r @ handsontable.full.min.js:251
handsontable.full.min.js:251 Uncaught TypeError: Cannot read property 'offsetLeft' of undefined(…)

### Steps to reproduce

1.
2.
3.

### Your environment
* Version: 1.15
* Browser Name and version: Google Chrome 
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hi @syamdanda 
I am not sure if we are familiar with this bug.
Can you share a demo where we will be able to replicate the same console logs?

**Comment by AMBudnik** [comment]
Hi @syamdanda 
We did some changes to comes in the latest release (0.29.2) and I wasn't able to get the same errors.
I am closing this issue. Please share a demo if it still occurs.
