### ISSUE TITLE
How to edit  data source and re-assign to handsontable  :Render() is not firing

### ISSUE THREAD

**Issue by praveshmmm** [handsontable/handsontable#3936]
### Description
I am using handsontable in MVC 4.
I am loading data into handsontable from JQuery then after I want to edit data source on re-assign to handsontable by using JQuery. 

Data should be loaded and reflected but not reflecting.

Kindly share your views.

### Steps to reproduce

1. Load data into handsontable using JQuery.
2. Now load another same type data  to handsontable using JQuery.
3. Data should be loaded and reflected but not reflecting.

### Your environment
* Version: handsontable version 0.20.1
* Browser Name and version: IE-7
* Operating System: Windows 7 64 bit

**Comment by AMBudnik** [comment]
Hi @praveshmmm 
It would be much easier to investigate the case if you could create a JSFiddle.
If you load new data via `loadData()` method it should instantly load into the table and rerender the view.

**Comment by AMBudnik** [comment]
I wasn't able to replicate the issue. As there is no reply for 2 weeks I am closing this issue. However please leave a comment if you'd want to share any related information.
