### ISSUE TITLE
Blank Rows in Middle of Grid [PRO]

### ISSUE THREAD

**Issue by WefNET** [handsontable/handsontable#3937]
### Description

When data is loaded after the grid is instanced, blank rows appear in the middle of the grid. This is due to the combination of loading data after the grid is instanced and the minSpareRows property.

### Steps to reproduce

1.  Setup a HOT to load data after the grid is instanced.
2.  Set minSpareRows to 1 or more.
3.  Observe blank rows.

### Demo

http://jsfiddle.net/thewef/rbmn1ry4/4/

### Your environment
* Version: 1.4.1 and 1.8.0 PRO
* Browser Name and version:  IE Edge and FF
* Operating System: Win8

**Comment by AMBudnik** [comment]
Thanks for sharing @WefNET 
I've update the demo http://jsfiddle.net/d4jbrr1h/ as it was calling `getDate` not `getData` and data wasn't loading.

In the result we have 2 extra empty rows at indexes `2` and `3` and (as expected) two empty (spare) rows at the end of the table.

**Comment by krzysztofspilka** [comment]
Interesting. It looks as if minSpareRows were conflicted with Filters. See this demo: http://jsfiddle.net/d4jbrr1h/3/

**Comment by AMBudnik** [comment]
Here's a simplified example: http://jsfiddle.net/fj0nhztj/
When we comment filters however there's a pretty unexpected behavior when we comment `columnSorting`. You get only 4 rows and more when you click inside the table.

**Comment by jayasimha-c** [comment]
Dear support,

Please fix this as soon as possible. We are also facing issue with empty row when we enable filters.

![image](https://user-images.githubusercontent.com/5837489/27259038-934156a2-5427-11e7-8199-48bf6e15a807.png)

Regards,
jay

**Comment by AMBudnik** [comment]
Issue still replicable in v1.14.2

**Comment by KrYpTeD974** [comment]
+1 on 1.14.2

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment]
The issue is still replicable in v 4.0.0

**Comment by AMBudnik** [comment]
Issue is still replicable in v `6.2.2` http://jsfiddle.net/1v39znxm/1/

**Comment by rupesh-verma** [comment]
i'm also facing the same .when the page is loading for time the table containing 1 blank row in middle of rows .if we increase the minSpareRows value the blank row also increase in same ratio.can i use both filter and minsparerow together if it possible please tell me solution

**Comment by AMBudnik** [comment]
Sorry @rupesh-verma there is still no official fix, but each case is different and something other may work for you. Can you send me over the demo at support@handsontable.com?

**Comment by Qasim002** [comment]
#Solved
When data is loaded after the grid is instanced, blank rows appear in the middle of the grid. This is due to the combination of loading data after the grid is instanced and the minSpareRows property.

**Comment by khalilgharbaoui** [comment]
> #Solved
> When data is loaded after the grid is instanced, blank rows appear in the middle of the grid. This is due to the combination of loading data after the grid is instanced and the minSpareRows property.

Tnx @Qasim002 I can confirm that initializing with `data` and `minSpareRows` in one go works, 
but initializing and adding the data after does not work.
Once initialized the right way updating the data seems to work fine.

**Comment by Kappyh** [comment]
I have this issue on my handsontable pro, someone have any workaround for this?
I already removed the minSpareRows from the table, and the problem still happening.

**Comment by AMBudnik** [comment]
Hey @Kappyh 

This issue will be solved in the next version `8.0.0.-rc1`. You can test it here http://jsfiddle.net/handsoncode/tbyqn081/

@WefNET @khalilgharbaoui @Qasim002 @rupesh-verma @KrYpTeD974 @jayasimha-c 
Please also check the resources in your projects

**Comment by AMBudnik** [comment]
Hey guys

here's the fixed demo http://jsfiddle.net/w87rjc0b/ (8.0.0-beta1 released yesterday)

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```
`npm i handsontable@beta`

**Comment by AMBudnik** [comment]
Still works well in 8.0.0-beta2-rev6 http://jsfiddle.net/AMBudnik/j6f7e0cg/

**Comment by AMBudnik** [comment]
Hi @WefNET 

I’m glad to announce that Handsontable v8.0.0 that solves this issue is live!   

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. I hope that the amount of work that we put on the v8 will help you to improve your project.

Updated demo http://jsfiddle.net/ankL3qe6/

@khalilgharbaoui @Kappyh @Qasim002 @rupesh-verma @KrYpTeD974 @jayasimha-c
