### ISSUE TITLE
alteration

### ISSUE THREAD

**Issue by Stanols** [handsontable/handsontable#3939]
### Description
I wrote custom render  for all cells and it works perfectly for me, but it doesn't affect on list in filter by value dropDown menu (filtering) 
It would be great if you provide some custom render feature for this list. Thank you!

**Comment by AMBudnik** [comment]
Hi @Stanols 
Thanks for your post. Is they are chance to share a demo of your custom renderers?

**Comment by Stanols** [comment]
Hi,
this render function just parses the value like '~class-name1(~class-name2(cellValue))' and add all classes to cell to make it formatted. Currently I have **bold** and highlight with color features. Also I wrote custom editor for formatting edit, where override setValue/getValue functions with the same logic. The issue is in cell value. When I open filter_by_value menu, I see that values aren't formatted. I tried to override checkbox renderer of this menu, but it calls 'reset' function inside of the library and then this.hot.getDataAtCol(lastSelectedColumn) which returns not formatted values for select list. May be there is another way to apply highlighting for cell through cellMetaObject, but I have no idea how to make cell value bold and highlighted at the same time. Any ideas?

function formatterRenderer(hot, TD, row, col, prop, value, cellProperties) {
        var text = value;
        if (formatter.isFormatted(value)) {
            var data = formatter.parse(value);
            text = data.value;
            var $td = $(TD);
            $td.removeClass();
            $td.addClass(data.classes.join(' '));
        }
        Handsontable.renderers.TextRenderer.call(this, hot, TD, row, col, prop, text, cellProperties);
    }

override f function:
    function filterFormatterRenderer(hot, wrapper, row, col, prop, value) {
        var container = this;

        var $parent = $(wrapper.parentNode);
        $parent.addClass('htFiltersMenuValue');
        var label = document.createElement('div');
        var $label = $(label);
        $label.addClass('htFiltersMenuLabel');
        $label.text('Filter by value:');
        wrapper.append(_.first($label));

        container.elements.forEach(function (ui) {
            $(ui.element).find('.htCheckboxRendererLabel').each(function () {
                var data = $(this).text();
                var cell = formatter.parse(data);
                $(this).text(cell.value);
            });
            return wrapper.appendChild(ui.element);
        });
        
        return wrapper;
    }

**Comment by Stanols** [comment]
I have tried to use cellProperties, but it doesn't work for me =\ and I have found the save issue here: https://github.com/handsontable/handsontable/issues/3200

**Comment by AMBudnik** [comment]
Sorry for a late reply. Unfortunately that's right, adding custom cell properties is not available at the moment and I do not see any similar way to do it. However I will come back to you if I'' found any.

**Comment by Stanols** [comment]
Thank you for response!

**Comment by AMBudnik** [comment]
You're welcome and sorry that I couldn't share any tip here.
