### ISSUE TITLE
onChange resets row data

### ISSUE THREAD

**Issue by tedlin182** [handsontable/handsontable#394]
Hi,

This may not be an issue per se, but more of info about how onChange works, but when I change the data in a cell, I have a callback in place to update a 'status' cell in the same row.

This works fine, but when I update the same cell type in another row, it resets the previous row and places in the original data and wipes out any new class names I added in.

How can I override this "reset" functionality?

Ted

**Comment by okahara** [comment]
using a renderer it seems like I can only apply the affects before the table is created.  

I have a table that goes through each row and validates the cells in the row.  If the row is valid the first (blank) cell on the left the background is set to green if it is invalid the background is red.  This works but when I (a client) edits a row that is not valid all of the green and red changes disappear.  I've been playing with renderers but I cannot seem to get them be implemented after the handsontable is created.
