### ISSUE TITLE
Bug: Either spare row or data row disappears if you send empty value to the cell.

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#3943]
Hi guys. I have a trouble sending empty string as cell value. For some reason either spare row disappears or row for the last object is not rendered.

1) This example works fine: http://jsfiddle.net/andrewQwer/s6t768pq/392/
2) This one removes spare row http://jsfiddle.net/andrewQwer/s6t768pq/391/
3) If you set empty string for the first object - it works correctly: http://jsfiddle.net/andrewQwer/s6t768pq/401/
More complex example with 2 properties doesn't work either
http://jsfiddle.net/andrewQwer/s6t768pq/402/

**Comment by AMBudnik** [comment]
Very interesting examples. Thanks for sharing @andrewQwer 
You're right there's something with `minSpareRows` logic going wrong.

**Comment by AMBudnik** [comment]
Replicable in v0.34.3

**Comment by andrewQwer** [comment]
Works the same way in 6.2.0 😢

**Comment by AMBudnik** [comment]
Hey @andrewQwer 
did you try(as a workaround) to add `2` empty rows after the `loadData` is called http://jsfiddle.net/rfuzgs10/ or your case is more complicated = the amount of spare rows change over the time

**Comment by andrewQwer** [comment]
No, amount of spare rows is either 1 or 0 (if user doesn't have permisisons for adding new row), but it would be tricky to check whether the last row is empty as I use complex data model that may look like this `data.<someid>.value`. You solution should work I believe but I would like to avoid calculations for checking whether the last item in the data set contains empty  items (null/undefined/empty string) in every column. Do you know when it is planned to fix this issue?

**Comment by AMBudnik** [comment]
Main issue with missing spare rows is **fixed** in 7.4.2 http://jsfiddle.net/vjpqed3y/

Again, @andrewQwer thank you for sharing. I'm glad to see this issue solved.
