### ISSUE TITLE
Can't set comments using Cells property

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#3944]
Previously I could set comments using Cells property (0.26.1):  
http://jsfiddle.net/andrewQwer/s6t768pq/408/
But now it doesn't work (0.29.1):   
http://jsfiddle.net/andrewQwer/s6t768pq/406/

**Comment by AMBudnik** [comment]
thanks for @andrewQwer

**Comment by wszymanski** [comment]
@andrewQwer API changed and one part of documentation has not been updated so far. It will be changed soon.

Please change following part of code

```javascript
let cellProps = { comment: 'test'}; 
```

to:

```javascript
let cellProps = { comment: { value: 'test' } }; 
```

Working example: http://jsfiddle.net/wojciech/s6t768pq/425/

**Comment by andrewQwer** [comment]
Hi, @wszymanski 

Thank you for the details. 
Can I get full list of API changes to fix all possible issues upgrading to 0.29.x?

**Comment by wszymanski** [comment]
@andrewQwer So detailed changes haven't been written down.

Please check out the breaking changes section in the release notes for [0.29.0](https://github.com/handsontable/handsontable/releases/tag/0.29.0). Every API modification
 should be applied in documentation.

**Comment by andrewQwer** [comment]
Ok, got it. Thank you!

**Comment by AMBudnik** [comment]
Thanks again for sharing @andrewQwer 
Docs are updated.
