### ISSUE TITLE
Manual column resize does not position correctly when Handsontable is shown with transition animation

### ISSUE THREAD

**Issue by orb3b** [handsontable/handsontable#3947]
### Description
Manual column resizer does not position correctly when Handsontable is shown with transition animation. In most cases it can't even be found to resize a column. If the transition classes are removed from the handsontable, everything works correctly.

### Demo
http://jsfiddle.net/jnponcc7/2/

![issue](https://cloud.githubusercontent.com/assets/1257418/21256186/eccab86c-c381-11e6-8c80-f2309466196b.png)

### Your environment
* Handsontable version: 0.29.1
* Browser Name and version: Google Chrome 55.0.2883.87

**Comment by AMBudnik** [comment]
Thanks for sharing @orb3b

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment]
It works the same in [v `5.0.1`](http://jsfiddle.net/59zm2grs/)
![image](https://user-images.githubusercontent.com/10757813/45145879-fe6a8b80-b1c1-11e8-9421-adf5dfab7862.png)

**Comment by wojciechczerniak** [comment]
Housekeeping. We have few issues related to this one. I'm closing this one as a duplicate of #5050. Please track #5050 for further development.

**Comment by AMBudnik** [comment]
Hey @orb3b 

we've just published Handsontable v `7.0.0` were we fix a referred issue https://github.com/handsontable/handsontable/issues/5050
Please update and let me know if it works for you.
