### ISSUE TITLE
Event 'afterSelectionEnd' doesn't fire if 'contextMenu' option is set 'true'

### ISSUE THREAD

**Issue by lil25** [handsontable/handsontable#3948]
### Description

Event 'afterSelectionEnd' doesn't fire if context menu is enabled. For left click everything is working fine.

### Steps to reproduce

1. Open console
2. Make right click on the cell
3. Event 'afterSelectionEnd' doesn't fire

### Demo

http://jsfiddle.net/yz1ue6b2/6/

### Your environment
* Handsontable version: 0.28.4
* Browser Name and version: Chrome Latest, Firefox Latest
* Operating System: Mac OS Sierra, Windows 10

**Comment by AMBudnik** [comment]
Thanks for sharing this issue @lil25 
You're right, the callback is not fired. I thought that maybe the opening of a content menu window is stopping the callback but when we pick `make read only` from the menu we won't get the log as well.

**Comment by AMBudnik** [comment]
The behavior has slightly changed in version 0.35.1
Now when we open a menu we get `afterSelection` and when we close it we get `afterSelectionEnd`. Updated demo http://jsfiddle.net/yhb1xcz0/
