### ISSUE TITLE
Chinese character input bug？

### ISSUE THREAD

**Issue by chauvetxiao** [handsontable/handsontable#3955]
### Description
when  I focus one cell before editing, if I want to input an Chinese character,the first letter will show on cell directly,then the second character can call typewriting up, what I want is typewriting can be called up when the first letter being input. It seems that the first input letter being prevent because of the textarea not displayed and focused,so is there any way to display and focus the textarea when 
afterSelectionEnd hook being called?

### Steps to reproduce
1.focus any cell
2.switch typewriting to any Chinese typewriting
3.input any letter

### Your environment
* Handsontable version:  0.29
* Browser Name and version: chrome 54
* Operating System: MAC 10.11.6

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/839

**Comment by AMBudnik** [comment]
Thanks for sharing @chauvetxiao

**Comment by chauvetxiao** [comment]
Tanks @AMBudnik，This solved through a hack #839
