### ISSUE TITLE
Fix the positioning of a data picker

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3957]
### Description

The date picker should be opened in direction allowing it to fill more space. That is true especially when you open it near to the bottom/right edge of the window.

### Current behavior

![image](https://cloud.githubusercontent.com/assets/8048526/21405723/f7b9270a-c7c7-11e6-8fe8-922807217d78.png)

### The behavior after change

**We have at least 4 cases here:**

1. A cell is at the bottom of the grid
2. A cell is to the right of the grid (last column for instance)
3. A cell is to the right of the grid (last column) and at the bottom of the grid at the same time
4. A cell is in the middle of the grid and has a lot of space in every direction

**In each case the date dicker should behave differently:**

1. It opens to the top. It is aligned to the left border of a cell.
![image](https://cloud.githubusercontent.com/assets/8048526/21405791/65f1798e-c7c8-11e6-9c45-4d9e907e6730.png)

2. It opens to the bottom. It is aligned to the right border of a cell.
![image](https://cloud.githubusercontent.com/assets/8048526/21405794/6919ac12-c7c8-11e6-9254-056e122e3040.png)

3. It opens to the top. It is aligned to the right border of a cell.
![image](https://cloud.githubusercontent.com/assets/8048526/21405800/6cf1d0b2-c7c8-11e6-8aea-9b6c81334564.png)

4. It opens to the bottom. It is aligned to the left border of a cell.
![image](https://cloud.githubusercontent.com/assets/8048526/21405801/700db5c2-c7c8-11e6-8ef5-fbad43a05b90.png)

The solution should assume that both rows and columns can be of different size.

**Comment by AMBudnik** [comment]
I'm moving all the improvement suggestions to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Please feel free to leave any additional comments and reflections.

Thanks in advance!

**Comment by krzysztofspilka** [comment]
Most probably the change should be universal so we can reuse it in other editors (such as dropdown, autocomplete, etc.).
