### ISSUE TITLE
Question: how to read/pass first letter that opened custom editor

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#3960]
Hi guys, 

I use custom editor for my grid that have input area for searching items. When I click on a cell and start typing editor mode is activated and custom editor input is displayed, but I loose first letter because custom editor is opened after the first letter is pressed. Is there any way I can get information about keycode that opened editor?
See a short video, I am trying to type `asdf` combination, but only `sdf` is applied for custom editor as `a` opens it: http://screencast.com/t/ZyNdRQEo3WcO

**Comment by AMBudnik** [comment]
That was a bug, currently you are able to get the first letter as well.
