### ISSUE TITLE
Autocomplete cell type doesn't work properly in strict mode

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3962]
### Description
After pasting data into the autocomplete cell in strict mode, the validator marks this cell as a valid even when a value differs in case-sensitivity.

### Steps to reproduce
1. Go to the demo: http://jsfiddle.net/cv6184dq/1
2. Paste `nissan` into `A1`
3. `nissan` != `Nissan`, but validation has passed

### Demo
http://jsfiddle.net/cv6184dq/1

### Your environment
* Handsontable version: 1.8.2
* Browser Name and version: Chrome v55
* Operating System: macOS Sierra 10.12.2

**Comment by AMBudnik** [comment]
Confirmed, thanks for fixing.
Updated demo: http://jsfiddle.net/6tt2hp5q/
