### ISSUE TITLE
filters: true scrolls to top of page

### ISSUE THREAD

**Issue by 9mm** [handsontable/handsontable#3963]
### Description

There seems to be a bug where if you enable `filters: true` as well as the `dropdownMenu` with a specific configuration: `['filter_by_value', 'filter_action_bar']`.

The first time you click on anything in the filter dialog box, the dialog closes immediately (instead of staying open, if you click 'clear' for instance) and the browser will scroll away from your current position. You have to re-open the same filter dialog a second time, and after that, all the options will work properly.

I notice it only does this if you set specific `dropdownMenu` options. If you simply do `dropdownMenu: true` it seems to work fine.

Version `1.8.1`, Chrome 55

**Comment by AMBudnik** [comment]
thanks for sharing @9mm 
We have the same issue reported in our internal ticketing system #102
I left there a note to comment here as well.

**Comment by hrkim28** [comment]
yes, i have same problem.
@9mm told that is true, when 'dropdownMenu: true' set, this works a little well.
But anyway... 'dorpdownMenu: true' set, scroll down. Then user should click one more.
How can i do ?

**Comment by AMBudnik** [comment]
The issue seems to be gone in v `2.0.0` Demo http://jsfiddle.net/y5k0wwbg/
Please leave a comment if there's still anything wrong with this operation
