### ISSUE TITLE
When scrolling horizontally columns misalign.

### ISSUE THREAD

**Issue by marcosnc08** [handsontable/handsontable#3964]
### Description
When scrolling horizontally columns misalign.

![screen shot 2016-12-26 at 17 08 06](https://cloud.githubusercontent.com/assets/5439902/21486176/36c941e0-cb8e-11e6-98b2-f4874bead225.png)

### Environment
* Handsontable version: 0.24.1
* Browser Name and version: 55.0.2883
* Operating System: Windows 7
* Extra things I use: Cell blocking, select2.js

**Comment by AMBudnik** [comment]
Hi @marcosnc08 
Can you replicate the same issue via JSFiddle?
Are you using any additional styling (Bootstrap, Materialize)?

Can you check if adding [`autoColumnSize: true`](https://docs.handsontable.com/0.29.2/Options.html#autoColumnSize) or [`viewportColumnRenderingOffset`](https://docs.handsontable.com/0.29.2/Options.html#viewportColumnRenderingOffset) to maximum number of columns in your spreadsheet changes anything?

**Comment by AMBudnik** [comment]
I am closing this issue as there is no reply for more than a week but feel free to leave a comment and a needed demo if this issue still occurs.

**Comment by ShirishResilinc** [comment]
Hi @AMBudnik,
I have also been running through same problem. 
Please find details below,
**Enviroment:**
Handsontable version: 0.31.2
Browser Name and version: Chrome 

![image](https://user-images.githubusercontent.com/19300498/35664323-9062dd74-0747-11e8-91e9-053c5fb254c7.png)

Configuration: 
{
            columns: [{
            title: "Name",
            data: "name",
            type: "text",
            readOnly: true,
            renderer: function (instance, td, row, col, prop, value, cellProperties, types) {

                let args = arguments;
                td = args[1];
                const $td = $(td);
                args[5] = (args[5] || "").toUpperCase();
                value = value ? Handsontable.helper.encodeHtml(value) : value;
                let content = value;
                if (!instance.isEmptyRow(row) && !cellProperties.valid) {

                    if (!!cellProperties.errorMsg) {

                        let divElement = document.createElement('div');
                        $td.addClass('datasheet-error-red');
                        divElement.className = 'error-tooltip';
                        content = '<div/>' + (value || '');
                        divElement.innerHTML = cellProperties.errorMsg;
                        $td.tooltip({
                            tooltip: divElement,
                            html: true
                        });
                    }
                } else {

                    $td.tooltip('remove');
                }
                $td.html(Handsontable.helper.stringify(content));
                return $td[0];
            }
        }, {}],
            minRows: 20,
            minSpareRows: 10,
            allowInsertRow: true,
            allowInsertColumn: false,
            rowHeaders: [],
            allowEmptyRow: true,
            stretchH: 'all',
            renderAllRows: false,
            fixedColumnsLeft: 1,
            manualColumnResize: true,
            viewportColumnRenderingOffset: 100,
            viewportRowRenderingOffset: 100
}
I have added configuration of grid i am using.
Extra things i have added are tooltip provided by materilizecss.
Note: Not using any material css under handsontable table.
I have written a handsontable plugin for hiding(Triming) columns where i have used modifyCol hook to hide the column.

**Comment by AMBudnik** [comment]
Hi @ShirishResilinc 

Please create a JSFiddle/JSBin demo. I will test it.
