### ISSUE TITLE
Remove row event not working 

### ISSUE THREAD

**Issue by surendrakandira93** [handsontable/handsontable#3965]
### Description
When we remove one row on the  grid and using  beforeRemoveRow: function (start, end) {
var removeRow= handsontable.getDataAtCell(changes, 0);

}
but it not return correct row.
how we are get the remove row data for remove these row in db.

**Comment by krzysztofspilka** [comment]
@surendrakandira93 Do you make any changes within a grid before trying to remove a row? Can you prepare a simplified demo on JSFiddle or Codepen?

**Comment by surendrakandira93** [comment]
Thanks
I have found solution
