### ISSUE TITLE
Firefox and afterOnCellMouseDown "use strict" error

### ISSUE THREAD

**Issue by vkomphasouk** [handsontable/handsontable#3966]
### Description
The issue i'm having is i'm using the hook **afterOnCellMouseDown** to trigger a page post back. This works fine on IE and Chrome, however in Firefox i get an error **TypeError: access to strict mode caller function is censored**. Since **afterOnCellMouseDown** is an event that allows custom JavaScript to be run, I would assume it would allow for non "strict" JavaScript code to be used.

I understand that this is caused from "use strict" that is set in the start of the hook's callback method and asp.net's __doPostBack() method, which is not strict, that this error is getting thrown. For a production release, shouldn't "use strict" not be included?

### Steps to reproduce
1. Given the Handonstable object with a hook

        var hot = new Handsontable(...);
        hot.addHook('afterOnCellMouseDown', function () {  __doPostBack(); });
2. Click on a cell in Firefox. The postback will not occur, only a JavaScript error

### Your environment
* Handsontable version: 0.28.0
* Browser Name and version:  Firefox 50.1.0
* Operating System: Windows 10 + IIS8 + asp.net 4.6.2

**Comment by AMBudnik** [comment]
I have tested this Fiddle http://jsfiddle.net/handsoncode/8dhvvb6b/ on Windows 10/ FF 51 and I do not get the issue.

As this post is pretty old I guess that you have already found a solution and made it work as well. However if you'd have any additional questions please create a new ticket.
