### ISSUE TITLE
setDataAtCell in validator,how to break the Infinite loop?

### ISSUE THREAD

**Issue by zzzzxiao** [handsontable/handsontable#3967]
### Description

when setDataAtCell triggered in validator, then the validator function will be triggered again; It will be a Infinite loop;
### Steps to reproduce

1.My code : 
   validator()=>{
          //do somthings
          setDataAtCell(row,col,value);
   }
2.
3.

### Your environment
* Handsontable version:0.26.0
* Browser Name and version: chrome
* Operating System:windows10

**Comment by surendrakandira93** [comment]
Same problem i got
 When set new value in cell using setDataAtCell methos " handsontableInstance.setDataAtCell(index, 2, 'new value')" It  Infinite loop; and browse not working 

using my code
 function getDataObject(handsontableInstance, index, action) {
        var rawData = handsontableInstance.getDataAtRow(index);
            handsontableInstance.setCellMeta(index, 2, 'readOnly', true);           
            handsontableInstance.setDataAtCell(index, 2, 'new value')  
      rawData[1][[2] =''		
        return rawData;
    }

**Comment by AMBudnik** [comment]
Hi @zzzzxiao @surendrakandira93 
I guess that you can try to set more specified conditions for your validation.

Please check this example: http://jsfiddle.net/handsoncode/xjw4qdp9/

Here I am using `setDataAtCell` to show a result of a validation for a dropdown cell type. If user picks an option from the dropdown the last cell will show `OK` in the other way it will return `ERROR`.

**Comment by AndreyBespamyatnov** [comment]
I still has the same issue, I don;t think this question has been answered

**Comment by AMBudnik** [comment]
Hi @AndreyBespamyatnov the issue has been closed as no one left a feedback after my answer but if you still face difficulties please share your use case and I'll reopen it.
