### ISSUE TITLE
dropdown cell type does not convert HTML.

### ISSUE THREAD

**Issue by aokaywe** [handsontable/handsontable#3969]
### Description
1. set columns：
```
type: 'autocomplete',
source: ['$<default>', ‘$<test>']
```

### Steps to reproduce
1. click dropdown arrow
2. menu only show $ items
3.

### Bug
AutocompleteEditor afterRenderer function:
TD.innerHTML = value.replace(match, '<strong>' + match + '</strong>');

-- The "value" should be converted to html

**Comment by AMBudnik** [comment]
Yes, you are right @aokaywe. Currently dropdown cell type does not convert HTML.
demo: http://jsfiddle.net/handsoncode/L5wtw6tz/

Thank you for sharing this improvement suggestion.

**Comment by AMBudnik** [comment]
Hi,

Thanks again for sharing this Feature Request. I am moving it to our Wiki Section at https://github.com/handsontable/handsontable/wiki/Feature-requests
The issue will stay closed until it'll get picked by our developer.
