### ISSUE TITLE
Prepare * (star) CSS margin: 0 auto table settings

### ISSUE THREAD

**Issue by mateuszs** [handsontable/handsontable#3972]
### Description
![capture](https://cloud.githubusercontent.com/assets/6123336/21590038/7700025c-d0f8-11e6-9071-00c1feab577f.JPG)

### Steps to reproduce
It happens all the time

### Demo
Look at screen

### Your environment
* Handsontable version: 
* Browser Name and version: All browsers (ie, chrome, firefox)
* Operating System: (windows)

I did not change any css or js. On previous layout it worked fine. I think it may be a problem with my css:
http://pastebin.com/6pgQrt6b

Regards

**Comment by AMBudnik** [comment]
Hi @mateuszs 
Can you share a JSFiddle demo where this issue can be replicable?
Even with your CSS code still I do not now the class/id for the Handsontable container.
Does this happen only when you scroll horizontally or just appears after initialization?
Also are you using any additional libraries or frameworks that changes styles, like Bootstrap?

**Comment by mateuszs** [comment]
Hmm... I cannot give you a demo because it is our internal company website. But what I noticed, the responsible part of this issue is "margin" in style.css:
* {
    margin: 0 auto;  <- this
    ...
}

I cannot remove it because my layout crashes but without it, handsontable works :/

**Comment by AMBudnik** [comment]
Thanks for sharing your investigation results.

I've asked our developer to check the settings. He came to the same conclusion but also said that he do not recommend settings margin auto for * (star). Even big frameworks as Bootstrap aren't handling this properly.


I will add your idea to improvement suggestions.

**Comment by AMBudnik** [comment]
Hi,

Thanks again for sharing this Feature Request. I am moving it to our Wiki Section at https://github.com/handsontable/handsontable/wiki/Feature-requests
The issue will stay closed until it'll get picked by our developer.
