### ISSUE TITLE
"mouseover" event not destroyed after destroying handsontable [with comments]

### ISSUE THREAD

**Issue by sinhavartika** [handsontable/handsontable#3974]
### Description
This happens with handsontable with comments.

This error is intermittent. But can be replicated after trying for 3-4 times. 

handsontable.full.min.js:30 Uncaught TypeError: Cannot read property 'getInputElement' of null
    at j.value [as targetIsCommentTextArea] (handsontable.full.min.js:30)
    at handsontable.full.min.js:30
    at handsontable.full.min.js:28

### Steps to reproduce

1. Create a table with comments.
2. destroy the table and trigger "mouseover" event

### Demo
steps to replicate in fiddle
1. Click on button "click me". (with console open)
2. If issue is not replicate. Run fiddle again and try again.
Can be replicated after 3-4 times.

http://jsfiddle.net/ozegrcyu/

### screenshot
![handsontable_issue](https://cloud.githubusercontent.com/assets/11784445/21636514/07f90ec0-d289-11e6-8526-5485dc3e6593.png)

### Environment
* Handsontable version: 
can be replicated in 0.29.0
* Browser Name and version:
chrome 55.0.2883.87
* Operating System:
windows, mac

**Comment by gresspav** [comment]
Hi 
I wanted to report the same issue :-). There is probably problem with debounce. It delays the OnMouseOver event and the editor is meanwhile released.
![image](https://cloud.githubusercontent.com/assets/20515049/21638347/41808218-d26b-11e6-9360-791202663a1c.png)

![image](https://cloud.githubusercontent.com/assets/20515049/21638286/0792f194-d26b-11e6-8b12-46448b106fe3.png)

![image](https://cloud.githubusercontent.com/assets/20515049/21638468/c79b40ae-d26b-11e6-981f-ba4c33c51b67.png)

**Comment by AMBudnik** [comment]
Thank you for reporting @sinhavartika and for the investigation @gresspav 
I am marking this issue as a bug.

**Comment by AMBudnik** [comment]
Hi @sinhavartika 

Thanks again for sharing this issue.

It should be solved in v0.30.0. Can you confirm?

**Comment by gresspav** [comment]
It works now. Thanks

2017-01-11 12:24 GMT+01:00 Aleksandra Budnik <notifications@github.com>:

**Comment by AMBudnik** [comment]
Great! Thanks for a prompt reply @gresspav
