### ISSUE TITLE
New rows created when drag down dropdown cells (autoInsertRow: false)

### ISSUE THREAD

**Issue by jsiali** [handsontable/handsontable#3976]
### Description
When i am trying to block Drag down inserting new rows, i can't.

### Steps to reproduce
1. Drag down the cell B1 in the last row cell and try to go down.
2. New rows are created despite `autoInsertRow: false`

### Demo
Example : [JSFiddle](http://jsfiddle.net/yhLt7vLc/)
Documentation : [Link](https://docs.handsontable.com/pro/1.7.4/demo-drag-down.html)

### Your environment
* Handsontable version: 28.4+
* Browser Name and version: Google Chrome Version 55.0.2883.87 m (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @jsiali 
Can you create a video on how to replicate this? I am also using Windows 10 and tried in in all major browsers.

**Comment by jsiali** [comment]
Hi @AMBudnik :)

You can look in this video : [Vimeo](https://vimeo.com/198170744)

**Comment by AMBudnik** [comment]
Oh.. I didn't choose a option from the dropdown. 

That is definitely a bug. If this is set

[fillHandle: {
      autoInsertRow: false,
}](url)

no rows should be created via fillhandle.

Thanks for sharing @jsiali

**Comment by jsiali** [comment]
Hi @AMBudnik any update for this subject ?

Maybe in 0.30.4 ? :)

**Comment by AMBudnik** [comment]
We do not have even 0.30.3 planned yet but I will mention this issue on our dev meeting.

**Comment by jsiali** [comment]
Thanks you very much @AMBudnik :) You're the best !

**Comment by AMBudnik** [comment]
I don't want to promise anything so please do not take it as granted but I will promote this issue on our meeting.

**Comment by AMBudnik** [comment]
Hi @jsiali 

are you able to replicate the issue on latest Chrome? I've tried the same old demo but on newer Chrome (67) and it doesn't create new rows.

**Comment by AMBudnik** [comment]
I am closing the issue as I am not able to replicate the issue, however, if you still happen to have it @jsiali please leave a comment
