### ISSUE TITLE
Virtual keyboard does not appear below cell when there are multiple tables on page

### ISSUE THREAD

**Issue by shivrajsa** [handsontable/handsontable#3977]
### Description
I am using [https://github.com/Mottie/Keyboard](https://github.com/Mottie/Keyboard) to enter inputs in the cell. I call keyboard on 'afterSelectionEnd' on text editor element which has class 'handsontableInput' and it appears just below cell.
Here is code 
Code of Keyboard

    function keyboard() 
    {
     $('.handsontableInput').keyboard
    ({
    layout: 'custom',
    customLayout: {
    'default' : [
     //keys
    ],	
    },
    })
    .addTyping()
    .getkeyboard().reveal();
    }

    afterSelectionEnd : function (instance,col,row,td){
		this.getActiveEditor().beginEditing();
		keyboard();
    }, 

When I have single table on page, it works perfectly.
But when there are multiple tables on page, result is different

### Steps to reproduce

1. Click on the cell of first table, keyboard appears below cell which is good
2. Click on the cell of second table.
Result :  keyboard appears in left top of page 
3. Again click in the same cell of second table
Result : Keyboard appears just below cell which is good

Expected behavior : When user clicks on cell of second table first time ( step 2 ), it should appear immediately below it.
Please guide to solve this problem.

**Comment by AMBudnik** [comment]
Hi @shivrajsa 
Maybe all instances are using the same hook. Can you create a simplified JSFiddle where we will be able to replicate the same behavior?

**Comment by shivrajsa** [comment]
Hi @AMBudnik Please refer jsfiddle [http://jsfiddle.net/yd0fucct/5/](http://jsfiddle.net/yd0fucct/5/)

**Comment by shivrajsa** [comment]
Hi @AMBudnik could you please help me to solve this problem ?

**Comment by AMBudnik** [comment]
I think that it can be a different issue as when we click the second table first the issue does not occur. It happens only when we click the above table first.

**Comment by shivrajsa** [comment]
@AMBudnik do you have any solution for this issue, I also posted same on [stackoverflow](http://stackoverflow.com/questions/41820815/virtual-keyboard-does-not-appear-below-cell-when-there-are-multiple-instances-of) but there is no response

**Comment by AMBudnik** [comment]
Hi @shivrajsa with the current version both keyboards are visible however they are misaligned with the corresponding cell

![image](https://cloud.githubusercontent.com/assets/10757813/22781821/9aefda90-eec4-11e6-806b-5891edab3b25.png)

Can you tell me if you experience the same behavior? I am testing it on Chrome 55, Windows 10

Unfortunately I do not know the keybord library and their CSS. It looks like there's a `position` mismatch.

**Comment by AMBudnik** [comment]
It looks like the issue lay in the second library so for now we can close this issue.
