### ISSUE TITLE
adding new row ruins the 'sum' caclulation

### ISSUE THREAD

**Issue by LeonidProkopets** [handsontable/handsontable#3979]
### Description

Summary of the column  columnSummary: [								
      {
        destinationRow: 1,
        destinationColumn: 5,
        type: 'sum',
        reversedRowCoords: true,
       forceNumeric: true
      }
    ]
works well until a new row is inserted with the context menu. After this it gets wrong.

### Steps to reproduce
  var example1 = document.getElementById('example1');
  
  var hot = new Handsontable(example1, {
    data: generateDataObj(),
    colHeaders: true,
    rowHeaders: true,
    contextMenu: true, // context menu ON
    columnSummary: [								
      {
        destinationRow: 1,
        destinationColumn: 5,
        type: 'sum',
        reversedRowCoords: true, // last row cell is the summary of the column
       forceNumeric: true
      }
    ]
  });
 
### Demo

http://jsfiddle.net/52f0e1j5/

### Your environment
* Handsontable version: https://docs.handsontable.com/pro/1.4.1/demo-summary-calculations.html
* Browser Name and version: Firefox 50.1
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Hi @LeonidProkopets 
I saw the bug in version 1.4.1 which you've used to create a demo. However it works as expected in 1.8.2 (http://jsfiddle.net/e7h3k5ke/).

Can you confirm that?

**Comment by AMBudnik** [comment]
I guess that it works as expected now but feel free to leave a comment if you're still experiencing any bugs.
