### ISSUE TITLE
1px height difference when multiple lines of content

### ISSUE THREAD

**Issue by PhpSriptKiddie** [handsontable/handsontable#3981]
I've seen this problem mentioned other places, but I haven't been able to find a solution. Was it ever fixed?

When I have a cell with multiple lines of text, the following cells are not aligning correctly. Seems to be caused by the cell with multiple lines being 1px higher than the rest.

![multiplelines](https://cloud.githubusercontent.com/assets/15359478/21760055/67e1e208-d649-11e6-8be1-148690ae33f9.PNG)

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 
Are you using zoom in/out to get the 1px misalignment or it happens on 100% zoom as well?

I have created a demo at: http://jsfiddle.net/7pxc3g2b/

and got the misalignment only after zooming in after using the fixed width for columns to get second row. The same situation is while using the `<br>`attribute.

**Comment by PhpSriptKiddie** [comment]
I think I have found a solution for now. Will verify and get back.

**Comment by AMBudnik** [comment]
Thanks for checking, let's stay in touch.

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 

do you have any update on this issue?

**Comment by AMBudnik** [comment]
As there is no reply for some time I am closing this issue. However if you have any new piece of information about this subject please comment.

**Comment by aRealCat** [comment]
I have the same problem

-solve  :  add 'autoRowSize: true,'
