### ISSUE TITLE
How can I do to select multiple columns

### ISSUE THREAD

**Issue by minteliuwm** [handsontable/handsontable#3982]
I have a table with columns col1,col2,col3,col4,col5
And now I want to select col1 and col4  at the same time , can you tell me how to do it?

**Comment by AMBudnik** [comment]
Hi @minteliuwm 

Currently in Handsontable you can only select adjacent columns/rows or cells.

**Comment by minteliuwm** [comment]
I see , and I want to know Do you have plans to change this?

**Comment by AMBudnik** [comment]
Sure, It's in our Feature Request list at: https://github.com/handsontable/handsontable/wiki/Feature-requests (no #97). 

We already made some steps to create a step-by-step scenario to accomplish this goal however we do not have a set Roadmap for 2017 so we are currently fixing major and minor issues reported at Github.

**Comment by minteliuwm** [comment]
I'm glad to see it , thank you very much.

**Comment by AMBudnik** [comment]
You're welcome. I also thank you for giving your vote for this feature. We are gathering all ideas to pick features that are most needed.

Have a great day @minteliuwm

**Comment by AMBudnik** [comment]
ps. now you can officially vote for new feature at our [Roadmap for 2017](https://trello.com/b/PztR4hpj/handsontable-roadmap-2017-login-to-vote-currently-in-development).

**Comment by Alex-ley-scrub** [comment]
@AMBudnik no https://github.com/handsontable/handsontable/issues/97 does not seem related to selecting multiple columns? Is there another ticket/issue for that?

**Comment by AMBudnik** [comment]
Hi @Alex-ley-scrub 

the `97` was referring to a website where we garnered feedback, but that was a couple of years ago. Now this page is unavailable. 

When it comes to columns' selection we have the following method called `selectColumns()`

Example API

```js
// Select column using visual index.
hot.selectColumns(1);
// Select column using column property.
hot.selectColumns('id');
// Select range of columns using visual indexes.
hot.selectColumns(1, 4);
// Select range of columns using visual indexes and mark the first header as highlighted.
hot.selectColumns(1, 2, -1);
// Select range of columns using visual indexes and mark the second cell as highlighted.
hot.selectColumns(2, 1, 1);
// Select range of columns using visual indexes and move the focus position somewhere in the middle of the range.
hot.selectColumns(2, 5, { row: 2, col: 3 });
// Select range of columns using column properties.
hot.selectColumns('id', 'last_name');
```
Ref: https://handsontable.com/docs/javascript-data-grid/api/core/#selectcolumns

Now, if you need to select non-adjacent columns, you can use the `selectCells()` method: Ref: https://handsontable.com/docs/javascript-data-grid/api/core/#selectcells

Example API

```js
let endRowIndex = hot.countRows() - 1; // index of a last row 
hot.selectCells([[0, 0, endRowIndex, 3], [0, 6, endRowIndex, 8]]);
```

![Zrzut ekranu 2024-07-10 o 10 39 54](https://github.com/handsontable/handsontable/assets/10757813/b7f9daec-0f6c-476b-b474-4993d52f08e2)


Here, https://github.com/handsontable/handsontable/issues/4811 is a dedicated PR if you'd like to read more about the changes.
Demo: https://jsfiddle.net/ugqf3vxr/

**Comment by Alex-ley-scrub** [comment]
Thanks @AMBudnik - isn't it a bit odd that something that is possible with the UI is not possible with the API?
i.e. I can select A, C, E, ..., M sequentially by just holding down the Command button on MacOS and clicking the column headers A, C, E, ..., M one after another. Can we replicate this behaviour with the API anyway?
<img width="865" alt="image" src="https://github.com/user-attachments/assets/cc0e37d1-f943-4576-a56f-6e5399246919">

**Comment by AMBudnik** [comment]
Hey @Alex-ley-scrub 

Let me share a bit more details about the case. I understand that it might be a bit weird at first glance.

The behavior to hold `command` and to click non-neighboring columns was added by the [introduction to selection layers](https://github.com/handsontable/handsontable/pull/4904) and can be tracked via [the `afterSelectionEnd` hook](https://jsfiddle.net/h08opuz5/1/) (the last, 5th parameter, defines the layer of the selection). We can see that once we use the `command` key to select multiple columns the 5th parameter is increased.

Currently, the `selectColumns()` method doesn't support the layering (as it only accepts 2 column indexes - start and end). At the same time `selectCells()` selects only cells without headers. Changing the `selectCells()` to support the header or changing the structure of `selectColumns()` to be an array of arrays would be a breaking change. So, to allow this behavior to happen, we could agree on a breaking change (which we tend to avoid) or create a new method. I can internally open a new feature request as currently (as mentioned above, there's no official API for this action).

**Comment by Alex-ley-scrub** [comment]
@AMBudnik - thanks a lot for the response!

I can think of 2 ways to make the api changes without being breaking changes though:

1st - Changing the selectCells() to support the header indexes:
before:
```ts
// current workaround is to forget about trying to highlight the header cells themselves and just highlight the cells
const cellsToSelect: number[][] = [ [1,1, 10,2], [1,4, 10,5] ]; // assume we have 10 rows in our table

// selectCells(coords: Array<[number, number | string, number, number | string]> | CellRange[], scrollToCell?: boolean, changeListener?: boolean): boolean;
hotInstance.selectCells(cellsToSelect);
```
after:
```ts
// it would be better if we could also choose to select the -1 row, which is the header row (as seen in other apis)
const cellsToSelect: number[][] = [ [-1,1, 10,2], [-1,4, 10,5] ]; // assume we have 10 rows in our table

// selectCells(coords: Array<[number, number | string, number, number | string]> | CellRange[], scrollToCell?: boolean, changeListener?: boolean): boolean;
hotInstance.selectCells(cellsToSelect);
```
Supporting -1 indexing (to indicate the header row) doesn't break any previous code? All previous code will continue to work fine as before?


2nd - Changing the selectColumns() to support multiple non-adjacent columns:
before:
```ts
selectColumns(startColumn: number | string, endColumn?: number | string): boolean;
hotInstance.selectColumns(1, 2); // will select columns 1 and 2
hotInstance.selectColumns(4, 5); // will lose selection of columns 1 and 2 and just select 4 and 5
```
after:
```ts
selectColumns(startColumn: number | string, endColumn?: number | string, extendCurrentSelection?: bool): boolean;
hotInstance.selectColumns(1, 2, false); // remove any current selection and overwrite it with this one
hotInstance.selectColumns(4, 5, true); // extend current selection, don't overwrite it (i.e. in the end have 1,2,4,5 selected)
```
Since it is a optional function argument, it doesn't break any previous code? Since the new argument is not required, all old/existing code will continue to work fine as before?
these two lines would be equivalent as you can treat undefined arg to be the same as false (i.e. both falsey):
```ts
hotInstance.selectColumns(1, 2);
hotInstance.selectColumns(1, 2, false);
```

**Comment by AMBudnik** [comment]
Thank you for doing the research and posting those ideas. It's valuable to see how our community is using Handsontable and what their expectations are.

I will create an internal report about those ideas and notify you as soon as we get any updates.
