### ISSUE TITLE
Change renderer for single cells

### ISSUE THREAD

**Issue by PhpSriptKiddie** [handsontable/handsontable#3985]
I am working with some pretty big tables, where I have different renderers in the same column. For instance, I have a column of type checkbox, where the first 2 cells are changed to text instead of checkbox. 

Currently, I am doing this in a custom renderer which checks the col and row, and changes cellproperties, if needed. However, this seems to use a lot of ressources for big tables when having to check everytime it is rendered.

Can't I just setCellMeta properties per cell basis once and for all?

Hope it makes sense..

Thanks,

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 
Unfortunately now the cell meta data is called many times. It should be optimized:

http://www.google.com/url?q=http%3A%2F%2Fjsfiddle.net%2FLdcfcuhr%2F&sa=D&sntz=1&usg=AFQjCNHCzlqysYKDfohHMJpXyYz3o2kbeA

For a table like this the `afterGetCellMeta` was called 102 times

**Comment by AMBudnik** [comment]
I'm moving all the feature requests to our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests). Please feel free to leave any additional comments and reflections.

Thanks in advance!

**Comment by AMBudnik** [comment]
This topic is continued at https://github.com/handsontable/handsontable/issues/6303
