### ISSUE TITLE
Showing context menu on a cell doesn't trigger "afterSelectionEnd"

### ISSUE THREAD

**Issue by pbadenski** [handsontable/handsontable#3988]
### Description
If a cell is being selected through right clicking and showing context menu "afterSelectionEnd" event is not being triggered.

### Steps to reproduce
Context menu for table needs to be configured. "afterSelectionEnd" event should be logged.
1. Select some cell A.
2. "afterSelectionEnd" event will be triggered.
3. Right click on a different cell B to display a context menu.
4. "afterSelectionEnd" event will *not* be triggered.

### Demo
http://jsfiddle.net/L9s6e9yk/

### Your environment
* Handsontable version: 0.29.2
* Browser Name and version: Chrome: 55.0.2883.95 (64-bit)
* Operating System: macOS Sierra, 10.2.2

**Comment by AMBudnik** [comment]
Thanks for sharing @pbadenski 
I think that the same issue have been already reported here https://github.com/handsontable/handsontable/issues/3948
Am I right?

**Comment by pbadenski** [comment]
You're correct. Sorry for the duplicate.

**Comment by AMBudnik** [comment]
That's OK. Feel free to share anything that you will find :)
Have a great day @pbadenski
