### ISSUE TITLE
Cell background is replicated for other cells while dragging down

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3989]
### Description

We experience a cell meta data expansion.
Result: Background color is copied while dragging down the cell.
Expected result: The content of a cell should have been copied without background changes. 

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.8.2/tutorial-cell-types.html
2. Run the first demo
3. Select cell `0, 0`
4. Drag down the first cell

![background-copied](https://cloud.githubusercontent.com/assets/10757813/21808804/3497df04-d745-11e6-86e7-94be49c15e20.gif)

### Demo

Demo from our website > [Cell Types](https://docs.handsontable.com/pro/1.8.2/tutorial-cell-types.html)

### Your environment
* Handsontable version: 0.29.2
* Browser Name and version: Chrome 55
* Operating System: Windows 10

### Possible related issues
1. https://github.com/handsontable/handsontable/issues/3581

**Comment by wszymanski** [comment]
#2114 connected

**Comment by AMBudnik** [comment]
Thanks guys, it works as expected now in v0.30.1. I am closing this issue.
