### ISSUE TITLE
can this project export as '.xls' file?

### ISSUE THREAD

**Issue by JesterCheung** [handsontable/handsontable#3990]
### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @JesterCheung 
currently we are only able to export data as a .csv file.

**Comment by AMBudnik** [comment]
For everyone interested in this feature: Please leave your vote on our Trello: https://trello.com/b/PztR4hpj/handsontable-roadmap-2017-login-to-vote
