### ISSUE TITLE
manualColumnMove param bug

### ISSUE THREAD

**Issue by nope7777** [handsontable/handsontable#3993]
### Description
"manualColumnMove" parameter don't work properly when using it with "columns" param.

### Steps to reproduce
Create table with "manualColumnMove" and "columns" params.

### Demo
http://jsfiddle.net/kzvarpdn/

**Comment by AMBudnik** [comment]
Thanks for sharing @nope7777 
I got a problem to move column at the right side of the grid (#10+)

**Comment by AMBudnik** [comment]
It works fine when we have some data defined, like here http://jsfiddle.net/yr1cnbq7/ (`v 5.0.1`).

What is used in the example in the line `6` is this
`columns.push({data: 'column_' + i});`
which is not an array of data (as expected) so it does not appear in the table and moving of columns gets corrupted. As the required type of data hasn't been pushed into the table I think that we should not consider this as a bug.
