### ISSUE TITLE
the function getCommentAtCell is empty

### ISSUE THREAD

**Issue by stla** [handsontable/handsontable#3994]
https://github.com/handsontable/handsontable/blob/87d0df04b113023f49d5456379fb64d9de622d8b/src/plugins/comments/comments.js#L307

Is it normal ? I want the comments :(

**Comment by AMBudnik** [comment]
You're right @stla 
there's a missing code for this method: https://github.com/handsontable/handsontable/blob/master/src/plugins/comments/comments.js#L294

ps. I got a demo from @swistach http://jsfiddle.net/ytjrfwyv/1/
there's a different way that you can get comments.

**Comment by jansiegel** [comment]
It should work fine now.

I think it's worth noticing, that the `getComment` method returns the comment value for either the last viewed comment, or a comment value from a previously declared cell (using the `setRange` method).

As this is not the most user friendly way to do this, I'd suggest using the `getCommentAtCell` method, which returns the comment value for the provided `row` and `column` arguments.

**Comment by AMBudnik** [comment]
@jansiegel I'd be more than happy to see it all in the docs 👍

**Comment by AMBudnik** [comment]
Thanks for adding @jansiegel 
@stla now you should be able to use `getCommentAtCell`. Please update to 0.31.0 and let me know if it works for you.

**Comment by stla** [comment]
Hello,
 I've just tested. It works fine. Thanks !

**Comment by AMBudnik** [comment]
That's great! Thanks for testing/.
