### ISSUE TITLE
Custom menu items in a context menu

### ISSUE THREAD

**Issue by madoar** [handsontable/handsontable#3996]
Is it possible to create custom menu items in a context menu? 
If yes, how do I create a custom menu item and how can I bind a listener to it?

**Comment by AMBudnik** [comment]
Hi @madoar 
Yes, you can create custom context menu with your own functions. Here's a working example: http://jsfiddle.net/4rhesb6b/

**Comment by madoar** [comment]
Thanks for your answer!
I think that answers my question. I also read your tutorial about context menus, but in my opinion it wasn't clear what the callback function does, I think it would be more clear if you add a sentence to the tutorial after "Context menu with fully custom configuration", that tells the reader that the custom menu item creates an alert showing some text.

In addition I would like to ask if it's possible to rename existing menu items.

**Comment by AMBudnik** [comment]
Thanks for sharing your idea @madoar 
Yes, I guess we could add some more details to make it more clear.

ps. you can change a name for a default option by adding a `name` key. I have changed it for the last option in the menu: http://jsfiddle.net/Luo5utw6/

**Comment by madoar** [comment]
Thanks for your help, this answered the question
