### ISSUE TITLE
Handsontable column dropdown menu is not working when name contains forward slash "/".

### ISSUE THREAD

**Issue by nileshpore** [handsontable/handsontable#3999]
### Description
Handsontable column dropdwon menu is not working when name contains forward slash "/".
I have created two jsfiddle example, in first example dropdown menu  "Collpase/Freez" is not showing its submenu 
and in second context menu with name "Collpase-Freez" is working as expected.
### Demo
Context menu working : http://jsfiddle.net/30xprgof/5/

Not working with "/": http://jsfiddle.net/30xprgof/2/

### Your environment
* Handsontable version: 1.7.0
* Chrome:
* Windows 8.1:

**Comment by AMBudnik** [comment]
Thanks for sharing, that's a really interesting case. 

I have tried to put the slash as a char by the code `&#47;` however it fails to open the sub-menu as well.

**Comment by AMBudnik** [comment]
Hi @nileshpore 

We have updated the code and in v0.31.2 it should work as expected. Can you confirm it?

**Comment by AMBudnik** [comment]
I'm closing this issue but @nileshpore feel free to leave your comment any time
