### ISSUE TITLE
CheckboxRenderer overwriting changes made to td by custom renderer

### ISSUE THREAD

**Issue by jakubbares** [handsontable/handsontable#4001]
### Description
I have a custom renderer that adds background color to the checkbox cell when it is in particular state.
When I dont use CheckboxRenderer the cell shows a number instead of checked checkbox, but has background color as needed. 
I tried changing the order of applying renderer so that the CheckboxRenderer is used before the background color is added, but this caused errors (TypeError: Cannot read property 'classList' of undefined)

### Steps to reproduce
1. Create custom renderer which changes background color
2. Place the custom renderer before HT.CheckboxRenderer
3. The checkbox cell doesnt have background color when it should

**Comment by jakubbares** [comment]
I solved it by using td.className instead of td.innerHTML

**Comment by AMBudnik** [comment]
Glad that you've already figured it out so quickly!
ps. if you do not have to change a renderer I suggest using `cells` method instead for higher performance.
