### ISSUE TITLE
Consecutive double quotes are not  pasted correctly 

### ISSUE THREAD

**Issue by ghost** [handsontable/handsontable#4003]
### Description

When there are consecutive double quotes, copy and paste does not work correctly.
1. One double quote is missing on single line cell.
2. One double quote at first line is missing on multiline cell.

### Steps to reproduce

1. Copy cells there are consecutive double quotes.
2. Paste it.

### Demo

https://jsfiddle.net/ossar/y7sfg3tq/

### Your environment
* Handsontable version: 0.30.1
* Browser Name and version: Google Chrome 55.0.2883.87 m (64-bit)
* Operating System: Windows 7 Professional Service Pack 1

**Comment by AMBudnik** [comment]
Thanks for sharing @osada-interWave 
That's definitely a bug.

**Comment by martin88l** [comment]
Hi,

My team also encountered this issue. Is there a recommended workaround or is it not possible since the clipboard parsing is done before any hooks are invoked?

Thanks!

**Comment by AMBudnik** [comment]
I am really sorry but we do not have any updates on this issue.

**Comment by swistach** [comment]
This issue will be solved within #4931
