### ISSUE TITLE
wtHider is way too high

### ISSUE THREAD

**Issue by PhpSriptKiddie** [handsontable/handsontable#4004]
For some reason, my wtHider is always getting way more height than the table itself, rendering some weird scroll issues. Please see this screenshot:

![wthider](https://cloud.githubusercontent.com/assets/15359478/22055242/7e8221b8-dd5a-11e6-9072-a65d79142d42.PNG)

Any idea what might be causing this?

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 
some of Handsontable elements are known to take too much space. Can you share a demo where we will be able to get the same result?
I guess when you set fixed value `height` and `width` via instance settings the mentioned element get's those settings and doesn't exceed them: http://jsfiddle.net/qha1svzd/

**Comment by AMBudnik** [comment]
same issue as https://github.com/handsontable/handsontable/issues/4141
