### ISSUE TITLE
Bug: autoRowSize option breaks row numbers alignment

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4009]
Just look at this example: http://jsfiddle.net/andrewQwer/s6t768pq/465/
Row numbers are misplaced. If you turn off `autoRowSize` it works correctly

**Comment by AMBudnik** [comment]
Hi @andrewQwer 
Can you share your OS/Browser settings? 
I've tested the example (`autoRowSize` on and off) on Chrome, FF and Edge and both examples looks the same.

**Comment by andrewQwer** [comment]
Hi @AMBudnik 

Handsontable v0.28.4
Windows 7 Enterprise
Chrome 55.0.2883.87 

![image](https://cloud.githubusercontent.com/assets/710513/22140109/725888a8-defb-11e6-9ae1-830f58e8db0e.png)

**Comment by andrewQwer** [comment]
Strange, I made some page refreshes and now it is displayed correctly.

**Comment by andrewQwer** [comment]
Ok, got it. It is reproduced if I zoom content.

**Comment by AMBudnik** [comment]
Unfortunately Handsontable doesn't work correctly when you zoom in. We are already familiar with this bug. It was reported some time ago here: https://github.com/handsontable/handsontable/issues/3118
I've discussed the issue with our programmers and it won't be easy to achieve as most of dimensions in Handsontable are hardcoded.

As it is the same issue as #3118 I am closing this one, but if you would like to share any investigation results or concerns please leave a comment at #3118

**Comment by andrewQwer** [comment]
Thanks @AMBudnik. It's clear now
