### ISSUE TITLE
Issue with setDataAtRowProp (v0.30.0)

### ISSUE THREAD

**Issue by lubianm** [handsontable/handsontable#4010]
Since version 0.30.0 I'm having an issue with function setDataAtRowProp (and, in cascade, with recently modified function getAtCell). I'll try to explain my issue, but it's not simple...
First of all, I'm invoking setDataAtRowProp in this way:

`self.hot.setDataAtRowProp(datain, null, null, 'loadData');`

where _self.hot_ is my HandsOnTable instance and _datain_ is the following array:

`[[0,"notifier","temp_insert"],[0,"sort",1]]`

**The problem (long story short) is with field (or prop/column) "sort" existing on my HOT instance, because "sort" is a key-word function of Prototype Array.**

The long story is the following: setDataAtRowProp invokes 

`dataSource.getAtCell(recordTranslator.toPhysicalRow(input[i][0]), input[i][1]), input[i][2]]);`

and then getAtCell (when arrives to "sort" property) is called as 

`getAtCell(0, 'sort')`

Since version 0.30.0, code of getAtCell is:

```
getAtCell: function(row, column) {
    var result = null;
    var modifyRowData = this.hot.runHooks('modifyRowData', row);
    var dataRow = isNaN(modifyRowData) ? modifyRowData : this.data[row];
    if (dataRow) {
      var prop = this.colToProp(column);
      if (typeof prop === 'string') {
        result = getProperty(dataRow, prop);
      } else if (typeof prop === 'function') {
        result = prop(this.data.slice(row, row + 1)[0]);
      } else {
        result = dataRow[prop];
      }
    }
    return result;
  }
```

and when the code arrives to this.colToProp(column), function "colToProp":

```
DataMap.prototype.colToProp = function(col) {
  col = Handsontable.hooks.run(this.instance, 'modifyCol', col);
  if (this.colToPropCache && typeof this.colToPropCache[col] !== 'undefined') {
    return this.colToPropCache[col];
  }
  return col;
};
```

returns (this.colToPropCache[col]) that is Array prototype function "sort" for array this.colToPropCache instead of returning, simply, "sort"... therefore, when returning to getAtCell function, the code arrives here (these lines were not present on previous version 0.29.0):

```
else if (typeof prop === 'function') {
        result = prop(this.data.slice(row, row + 1)[0]);
} 
```

resulting in unpredictable results... (a JS error in my case). 

The point, in my opinion, is that DataMap.prototype.colToProp should not return Array prototype functions (like "sort" in my case) or properties (if, let's suppose, I have a "length" column) but return the property itself... I think that on previous versions this was not causing issues because getAtCell function returned "this.data[row][prop]" instead of "prop(this.data.slice(row, row + 1)[0]);"

Let me know... meanwhile, I'm replacing my "sort" table column name with something else.

**Comment by AMBudnik** [comment]
Thanks for sharing. I can't see any changes related to `setDataAtRowProp`. I will leave this issue for our developers to check.

**Comment by lubianm** [comment]
Changes have been done on `getAtCell` function (used by `setDataAtRowProp`)
