### ISSUE TITLE
Incorrect position of the selector

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4011]
### Description

First I select a cell and then scroll down to 'hide' it beneath the top edge of the table. Then I scroll back to see that cell again in the viewport and as a result the blue selector is misaligned by 1px down.

### Steps to reproduce

1. Go to https://handsontable.com/examples.html?headers
2. Select any cell in row 2
3. Scroll all the way down and up again
4. The selector is misaligned

### Demo

https://handsontable.com/examples.html?headers
![image](https://cloud.githubusercontent.com/assets/8048526/22148895/090bee10-df11-11e6-826e-f294bb84b9a5.png)

### Your environment
* Handsontable version: 0.30.1
* Browser Name and version: Chrome 55
* Operating System: Windows 8.1

**Comment by wszymanski** [comment]
Problem occurs when we manipulate with table header `innerBorderTop` class (we add / remove 1px from header).

![adding class](https://cloud.githubusercontent.com/assets/141330/23120519/eb495cb4-f75c-11e6-9171-573090563922.gif)

**Comment by wszymanski** [comment]
It was also fixed for Handsontable with `fixedColumnsLeft` option set.
