### ISSUE TITLE
Handsontable direct animation support

### ISSUE THREAD

**Issue by LeRoi** [handsontable/handsontable#4013]
Is there any plan to provide direct support for animations (say for collapsing columns) in handsontable? I'm not sure this is the right place/way to make a feature request, but it'd be great to get this on the docket. My mid-sized team utilizes handsontable and we'd love to see this supported somehow.

**Comment by AMBudnik** [comment]
It sounds like a really cool idea. However currently we do not have a similar option to add animations. Code is pretty solid and without making changes directly in the code it will be hard to force any other behavior.

Have you tried to implement it by yourself? Any tips here are highly appreciated.

**Comment by LeRoi** [comment]
Haven't tried to implement it myself, sorry to say. To be honest, don't know the first thing about web animations. Will update this if I do end up fiddling with it / find results. Thanks for the quick response :)

**Comment by AMBudnik** [comment]
Surely I will let you know. However our schedule is pretty tight for next two quarters of 2017 and I don't know when we'll have time to add something new.

**Comment by LeRoi** [comment]
SGTM, a dev's schedule is always busy. I'll keep an eye on this, hope you find some time for it perhaps late 2017 :) Thanks!!

**Comment by AMBudnik** [comment]
I'm moving all the feature requests to our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests). Please feel free to leave any additional comments and reflections.

Thanks in advance!

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
