### ISSUE TITLE
Scrollbar length is calculated properly only when autoRowSize plugin is enabled

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4014]
### Description
As title say we need adotation in documentation which will inform that scrollbar will have proper size **only** when  `autoRowSize` option is set to `true`

**Comment by scarletfog** [comment]
@wszymanski is this issue still valid? If so, should I mention this additional information inside the scrolling demo? https://handsontable.com/docs/8.0.0/demo-scrolling.html I looked at different places but this one still looks the most appropriate.

**Comment by wszymanski** [comment]
Yes, it is. I agree with you that scrolling demo may be good for that. Maybe extra information in the demo section for the [AutoRowSize plugin](https://handsontable.com/docs/8.0.0/AutoRowSize.html) and [`autoRowSize` key](https://handsontable.com/docs/8.0.0/Options.html#autoRowSize) would be also useful? WDYT? If you prepare documentation for these sections as well, I will put changes in the code 🙂
