### ISSUE TITLE
Misalignment of the overlays after change colHeaders by updateSettings

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4015]
### Description
When `colHeaders` was changed by `updateSettings({...})` and one of headers has more lines than before, then overlays have incorrect size.

### Steps to reproduce
1. Go to the demo.

### Demo
http://jsfiddle.net/a1uo55o7/

### Your environment
* Handsontable version: 0.30.1
* Browser Name and version: Chrome 55
* Operating System: macOS Sierra 10.12.2

**Comment by swistach** [comment]
Related: #3186

**Comment by AMBudnik** [comment]
Looks good! Now the header is correctly aligned. Demo: http://jsfiddle.net/handsoncode/ubg0seat/

**Comment by minteliuwm** [comment]
I have found a bug in this.
First, I update the colheaders like "a<br/>a"
Then,I update the colheaders like "a"
and the height of colheaders not change the second time.

**Comment by AMBudnik** [comment]
@minteliuwm that you for creating a new issue at https://github.com/handsontable/handsontable/issues/4201
we will continue the investigation at the above address
