### ISSUE TITLE
Missing source value for some hooks triggered by plugins

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4017]
### Description
There's a missing source value (last argument) for some hooks triggered by plugins. It can be helpful for developer who works with Handsontable to know about who triggered the action. Currently some hooks are better described as `afterChange` and some need more attention like `afterCreateRow`. Generally all hooks should be checked.

### Steps to reproduce
1. Go to http://jsfiddle.net/budnix/qb3tq9c6/;
2. Try to perform any action that will triggers adding new rows (eq. via context menu, autofill);
3. In DevTool you will see logged hooks with source as `undefined`.

### Demo
http://jsfiddle.net/budnix/qb3tq9c6/

### Your environment
* Handsontable version: 0.30.0
* Browser Name and version: any
* Operating System: any

**Comment by budnix** [comment]
Corresponding documentation was updated at https://github.com/handsontable/docs-pro/commits/1.10.0 and https://github.com/handsontable/docs/commits/0.31.0

**Comment by budnix** [comment]
As it's a Breaking Change fix (as label states) here's a list of changed sources:

Renamed:
- `'autofill'` => `'Autofill.fill'`;
- `'external'` => `'ObserveChanges.change'`;
- `'paste'` => `'CopyPaste.paste'`;
- `'undo'` => `'UndoRedo.undo'`;
- `'redo'` => `'UndoRedo.redo'`;
- `'gantChart'` => `'GantChart.loadData'`;
- `'columnSummary'` => `'ColumnSummary.reset'`;
- `'columnSummary'` => `'ColumnSummary.set'`;

New:
- `'ContextMenu.clearColumns'`;
- `'ContextMenu.columnLeft'`;
- `'ContextMenu.columnRight'`;
- `'ContextMenu.removeColumn'`;
- `'ContextMenu.removeRow'`;
- `'ContextMenu.rowAbove'`;
- `'ContextMenu.rowBelow'`;
- `'ContextMenu.rowBelow'`;

Unchanged:
- `'spliceCol'`;
- `'spliceRow'`;
- `'edit'`;
- `'auto'`;
- `'loadData'`;
- `'populateFromArray'`;
- `'dateValidator'`;
- `'timeValidator'`;
- `'validateCells'`;

**Comment by AMBudnik** [comment]
Thanks for adding @budnix
