### ISSUE TITLE
In filter mode , modifying cell and undoing the changes with ctrl z shows wrong result.

### ISSUE THREAD

**Issue by nileshpore** [handsontable/handsontable#4019]
### Description
When I apply filter on column and change some value of any cell. After changing value if I try to undo changes by ctrl+z then it shows wrong result.
### Steps to reproduce

1. Please refer jsfiddle "http://jsfiddle.net/qc3tLrp2/12/"
2. Apply filter on column B, select only value "2" and click on Ok, Filterd result will be displayed.
3. Now change value from column A, row 3 i.e. 5 to some other value.
4. Stay on same cell and Press ctrl+z, now it clears the filter and undo not happened.

### Demo

http://jsfiddle.net/qc3tLrp2/12/

### Your environment
* Handsontable version: 1.9.1
* Browser Name and version: Chrome
* Operating System: Windows 8

**Comment by AMBudnik** [comment]
Thank you for your effort to share this bug @nileshpore 
There are few related issues to undo/redo plugin. I guess that it needs a refactoring.

**Comment by AMBudnik** [comment]
Hi @nileshpore 

I am not able to replicate this issue using version `2.0.0`. Can you check that, please?

**Comment by AMBudnik** [comment]
There are more than 2 weeks without response so I believe that it works fine in v `2.0.0.`
