### ISSUE TITLE
AfterChange - order of calling

### ISSUE THREAD

**Issue by IonPopescu** [handsontable/handsontable#4020]
### Description
In my app, I have columns B and C, each with their "sum" Summary cell (B1 and C1 respectively). When I change a value in B2, I'd like to re-calculate the value in C2 based on it, and then have Summary values in B1 and C1 re-calculated. 

This works fine here: http://jsfiddle.net/rc8gfogt/3/ - console output is:
```
Called by: columnSummary
Called by: edit
```

However, when implementing this in my app (a slightly more complicated model), I get a different console output:
```
Called by: edit
Called by: columnSummary
```

As a result, the Summary cell (C1) in my actual app does not get updated when B2 is changed. 
What could be the reason why the "afterchange" event would be triggered by "edit" first, and "columnSummary" second?

### Demo
http://jsfiddle.net/rc8gfogt/2/

### Your environment
* Handsontable version: 1.9.1 Pro

**Comment by AMBudnik** [comment]
Thanks for sharing @IonPopescu however I get the same order as required with the following demo.

**Comment by AMBudnik** [comment]
I am closing this issue as there is no reply for more than 10 days however feel free to share a demo or more details about this case if you're still experiencing any difficulties with this part of code.
