### ISSUE TITLE
Row and column information of the field being currently validated

### ISSUE THREAD

**Issue by madoar** [handsontable/handsontable#4023]
I'm writing a validator function that checks, if a value appears at most once in a specific row. 
I want to do this by using the following function (written in typescript):
```typescript
        validator: (value: string, callback: any) => {
          const result =
            value != null &&
            value.length > 0 &&
            processedData.filter((row, index, array) => row.sid === value).length == 0;

          callback(result);
        }
```

The value processedData is the data array behind the visible handsontable. It contains json objects, with an attribute `sid` among other attributes.
In addition to validating the field after a change was done to it I also want to validate the complete table after populating it.
My problem is, that the validator doesn't work for the validation of the handsontable directly after populating it, because every value, that will be validated, is contained inside the array once at this time, even if it's invalid.
When I change the comparison to `processedData.filter((row, index, array) => row.sid === value).length == 1` I would fix the previously stated problem, but then the validator doesn't work correctly anymore in all validations, after the validation of the initially populated handsontable.

I believe the best way to solve my problem, or other similar problems, would be to pass the column and row informations of the currently validated field to the validator function. Is this possible?
I'm not sure how to solve my problem otherwise.

**Comment by madoar** [comment]
I think this issue went under in the flood of newer issues.
Do you have any ideas on how to solve this issue? It's one of the core problems of my applications :)
In addition to the suggested row and column parameters for the validator function it would also be useful to pass the handsontable object, to which the validator belongs, to the validator function. 
This is needed to enable an easy access to the handsontable for the validator function, because at least in my case I'm going to create the validators in another file/class, where I don't have direct access to the handsontable object. Therefore it would be useful if the handsontable object passes itself together with the to be validated row and column to the validator function.

**Comment by AMBudnik** [comment]
Hi @madoar and sorry for a long delay. We have written on your second issue and I totally forgot about this one.
 
As they are both related and I left you a comment there about the validation of single cells etc. is there anything else here that I can propose? As I found out in some cases you need to add a slight delay for a **validateCells()** method to work and it will check all checks in your spreadsheet (even those that haven't been changed).

**Comment by madoar** [comment]
Hi @AMBudnik no problem because of the delay, the many issues tell me you're busy ;)

Back to my problem:
I believe we talk about two different things.
To illustrate what I meant I've made a [jsfiddle](https://jsfiddle.net/47cLd6g7/2/) that show what I want to do and where I fail:

The jsfiddle contains a small table with a "no duplicate" validator for the first "id" column. Like you'll see, directly after loading the table already contains an invalid id which appears twice (the "1"), which is shown correctly.
Now if you do the following: Change id "5" in row 5 into a 4 and press enter.
You'll see that the field isn't marked red as invalid, which is wrong. The reason in my eyes for this is, that the data array is updated AFTER the validator call finished. This means that when the validator is called the table contains only one id "4".

Can you give me a show fiddle that shows me how to write a validator that prevents duplicate entries?

**Comment by AMBudnik** [comment]
Hi @madoar 
sorry for a delay but I have found a solution.

Please check this demo: https://jsfiddle.net/handsoncode/bodep20m/

I have checked that the `afterValidate` hook runs for the single cell so it does not compare other values. That is why I've added the `validateCells` method after every change. Of course it'll be wiser to use it only for the first column.
