### ISSUE TITLE
SetCellMeta JS Error

### ISSUE THREAD

**Issue by kameelyan** [handsontable/handsontable#4024]
### Description
![columnsettingsnotconstructor](https://cloud.githubusercontent.com/assets/590274/22312256/bbc0dc8c-e31c-11e6-936d-aad3e41d5995.png)

We were getting this error (and have for awhile now) occasionally, and I couldn't figure out why it's happening. Eventually we figured out that the constructor isn't being created in columsettings. We went ahead and added these three lines of code (similar to getCellMeta) and it fixed it.

```
  this.setCellMeta = function(row, col, key, val) {
...
    if (!priv.columnSettings[col]) {
        priv.columnSettings[col] = columnFactory(GridSettings, priv.columnsSettingConflicts);
    }
...
```

### Steps to reproduce
We honestly can't figure out how to fully reproduce it as it wasn't happening consistently.

**Comment by AMBudnik** [comment]
Hi @kameelyan 
That's a pretty mysterious case. I will leave your suggestion for our developers to check.
Thanks for sharing.

**Comment by AMBudnik** [comment]
Hi @kameelyan 

I am just checking by to ask if you may have an opportunity to check this bug again?

**Comment by kameelyan** [comment]
Since the fix I provided, we haven't had the error come up one time. I haven't updated handsontable since, so I haven't been able to test any versions since this bug was opened.

**Comment by AMBudnik** [comment]
Thank you for a quick reply @kameelyan 
I guess that I will ask our devs to check the following fix and if it won't break anything to include it in the source code.

**Comment by swistach** [comment]
It's definitely bug. Occurs when someone used setCellMeta for column, which not exist.
Demo: http://jsfiddle.net/9medd3cm/

Note: exception with 'offsetLeft' it's only a result of setCellMeta bug.

**Comment by AMBudnik** [comment]
Hi @kameelyan 

Thank you again for sharing this issue. I can happily announce that is has been fixed in the latest version. Can you check hat on your side?

**Comment by AMBudnik** [comment]
I assume that as there are no additional questions or issue we can close the topic.
