### ISSUE TITLE
scrollOffset calculation breaks when column width is 0

### ISSUE THREAD

**Issue by twjacobsen** [handsontable/handsontable#4026]
### Description
I'm working on manually implementing column hiding, but I can't set the column width to `0`.

This is because of a check in the method `getColumnWidth`, which checks for `width || defaultColumnWidth`.

It should be something like `isNumber(width) ? width : defaultColumnWidth`

The result of this bug is, that when selecting a column with the mouse, the grid will scroll way more than it needs to

### Steps to reproduce
I guess, that the steps to reproduce would be to modify the value in the hiddenColumnsPlugin from `0.1` to `0`, and see that selecting a cell is acting weird when some columns are hidden.

### Your environment
* Handsontable version: 1.6.0
* Browser Name and version: Chrome latest
* Operating System: macOS latest

**Comment by AMBudnik** [comment]
Thank you for your suggestion. I will mark this issue for our developers to take a look at.

**Comment by AMBudnik** [comment]
Hiding columns in currently available in the PRO version: https://docs.handsontable.com/pro/1.10.2/demo-hiding-columns.html
