### ISSUE TITLE
Viewport and scrollOffset gets skewed on wide tables

### ISSUE THREAD

**Issue by twjacobsen** [handsontable/handsontable#4027]
### Description
Having a table with 200 wide columns (table is 45000px wide), if I scroll to the far right and try to edit a cell that is only partially visible in the left of the table (hidden behind fixed columns), the editor will open over the fixed columns

![image](https://cloud.githubusercontent.com/assets/555812/22328060/91bc09f4-e3ba-11e6-9a08-575120f3457f.png)

The overlap gets worse the further I scroll to the right, so I'm guessing there's some offset somewhere, that gets more and more wrong.

### Your environment
* Handsontable version: 1.6.0
* Browser Name and version: Chrome latest
* Operating System: macOS latest

**Comment by AMBudnik** [comment]
Hi @twjacobsen 
Can you create a demo where I will be able to replicate the same effect?

**Comment by twjacobsen** [comment]
Hi,

I'm unable to reproduce the issue in a fiddle.
Using the bare-bones handsontable, when selecting a cell the view scrolls to have that entire cell in focus.
This does not happing in our application, which is probably why the editor overlaps the fixed columns.

I will try and see, what's going on in our end, and return to you afterwards.

**Comment by AMBudnik** [comment]
OK, thank you @twjacobsen as it is hard to say anything without seeing the code.

**Comment by AMBudnik** [comment]
I guess I can close the issue as there is no demo since 31th of January
