### ISSUE TITLE
[Question:] How to populate a column with values from an array?

### ISSUE THREAD

**Issue by tonyvince** [handsontable/handsontable#4028]
I want to populates all cells from `(row = 8 && col = 2)` to `(row = n && col = 2)` with an array of values `[value-1, value-2, value-3,.,...........,value-n]`. How to do this ?

**Comment by AMBudnik** [comment]
I don't know your table dimensions however you can do 2 thing:
1. Iterate this cells with [`setDataAtCell`](https://docs.handsontable.com/0.30.1/Core.html#setDataAtCell) method
2. Use `slice()` with [`loadData`](https://docs.handsontable.com/0.30.1/Core.html#loadData) method
