### ISSUE TITLE
How to group Undo / Redo Actions

### ISSUE THREAD

**Issue by msaqibansari** [handsontable/handsontable#4030]
### Description
When I remove column or row and there are already some formulas and after deleting row/column, each change is separately stored in done stack for undo. Supposed, when I delete column B and there are 3 formulas on column E, G and M, all 3 formulas will be modified and stored in done stack separately and also RemoveColumn action will be stored in done stack. In this case, i removed 1 column and 4 done actions stored for undo. When I press Ctrl+Z, only last action which was formula modification of M will be undo. 

### Expected Result
Whereas at first undo it should revert whole last change which is column removing and formula should show the accurate result.

**Comment by msaqibansari** [comment]
Demo available at 
http://jsfiddle.net/wvz6uvnr/1/

**Comment by AMBudnik** [comment]
Hi @msaqibansari 
Currently we do not have an option to group changes. We would need to change the undo/redo plugin to make it work. However I think that this is a great idea and I will mark it as a feature request.
Thank you for sharing.

**Comment by AMBudnik** [comment]
I'm moving all the feature requests to our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests). Please feel free to leave any additional comments and reflections.

Thanks in advance!

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
