### ISSUE TITLE
Updating both the columns and data of an initialized handsontable

### ISSUE THREAD

**Issue by madoar** [handsontable/handsontable#4032]
I want to be able to change the content of a handsontable after it is initialized.
Therefore I need to be able to change the column information and the data of a handsontable.
To change both things separately I would use `loadData(data)` to change the data of the table and `updateSettings(settings, init)` to change the column information of the table. 

Now my question is, if I need to call both methods in a specific order to make them work correctly without the user seeing a table in an unstable/incorrect state (which could appear when the columns are changed and the new data corresponding to the columns is not yet updated, or the other way).

In addition I can't find any information about the `init` parameter of the `updateSettings(settings, init)` method in the API documentation. It would be quite nice to learn what difference it makes if I use `true` or `false` and what default state of `init` is assumed when I pass no `init` parameter to `updateSettings`.

**Comment by AMBudnik** [comment]
Hi @madoar 
loading works synchronized so it's better (in my opinion) to load data first and then update headers (pick the heavier task first).
When it comes to docs, you are right there's no information of what the `init` stands for. It is our internal information. When it is used for the first time it returns true.

**Comment by madoar** [comment]
I've just rediscovered, that it should be also possible to update the data of a table by using the `updateSettings` method. To update both the columns and the data in my understanding it should work by using:
```typescript
hot.updateSettings({
  data: dataArray,
  columns: columnArray
});
``` 

Is this approach better than using a combination of `updateSettings` and `loadData`?

**Comment by AMBudnik** [comment]
Yes, it is possible and I guess that it actually can be better as you can easily see what you're updating in the same time. When it comes to performance there shouldn't be any difference.
