### ISSUE TITLE
Column header width is not adjusted after an update of a text within

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4034]
### Description
Column header width is not adjusted after an update of a text within.

### Steps to reproduce

1. Go to http://jsfiddle.net/tsugurL3/;
2. After using `colHeaders` via `.updateSettings` column headers' widths aren't getting adjusted.

### Demo
http://jsfiddle.net/tsugurL3/

### Your environment
* Handsontable version: 0.30.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Working as expected in 0.31.0. Demo: http://jsfiddle.net/handsoncode/x0781b94/
