### ISSUE TITLE
Autofill broken on merged cells

### ISSUE THREAD

**Issue by floribon** [handsontable/handsontable#4035]
### Description
What happens: an error in the console
What should happen: autofill of the selected area, as before

### Steps to reproduce
1. Merge two cells horizontally, for instance A1 and A2
2. Drag the little square from this merged cell to one cell above
3. It crashes and nothing happens.

### Your environment
* Handsontable version: 0.30.1
* Browser Name and version: Chrome
* Operating System: OSX

### Notes
- Cause of the error: the direction of autofill is detected as `right` in the `getDeltas` function, although it should be `down`.
- Even when it works, all this code is broken on strings as parseInt return `NaN` and because of some JS permissive magic it does seem to work.
- Please add a way to do custom action when dragging the autofill square and override the default behavior

**Comment by AMBudnik** [comment]
Hi @floribon 
Can you share a gif? I am not sure what to merge. If I merge A1 & A2 the I got the first cell so I can't use the fill handle to drag it to a cell above cause it's header. The same situation is when we merge horizontally A1 & B1.

**Comment by floribon** [comment]
Hi @AMBudnik sorry, select anything *but* header cells. Let's say B2 and B3.
I don't think a gif is necessary and I don't have the tools to make one.

**Comment by AMBudnik** [comment]
OK, I've made this example: http://jsfiddle.net/handsoncode/Lp56pdxh/

What I'm doing is merging `B2` and `B3` and the handle to drag the cell is gone (this is surely a bug) but if I click it again I can perform the action and it works as expected without any console logs.

![example12](https://cloud.githubusercontent.com/assets/10757813/22502729/810fddc0-e86e-11e6-9a9c-e89dfcb2a102.gif)

I've used v1.9.1 which is the PRO for v0.30.1 on Chrome 55 on Windows 10 so I guess we should get the same results. Also I've checked the same on Chrome 56 on Mac and got the same result.

Please check if my demo produces the same issue. If not maybe you have other settings that are causing it.

**Comment by floribon** [comment]
@AMBudnik thanks for checking. I am testing on the example page of handsontable and I don't see your problem of disappearing handle. However it turns out the problem I have reported only occurs with horizontal merging and not vertical, so please merge `B2` and `C2` and then drag the handle to the bottom.

This is directly reproducible here: https://handsontable.com/examples.html?headers&merge-cells&context-menu

**Comment by AMBudnik** [comment]
Hi @floribon 

I have tested the demo from our examples page and merged corresponding cells horizontally

![example31](https://cloud.githubusercontent.com/assets/10757813/22734342/a26c8cca-edf5-11e6-8657-ff1a1f68fbb1.gif)

but the browser is not crushing and there are no additional console logs.

**Comment by floribon** [comment]
Hi @AMBudnik, please do exactly the same but move the little square *down* instead of *up*, and you'll get the errors. (Sorry I realize I said "above" in my first post)

**Comment by AMBudnik** [comment]
Ohh OK :) now we're home @floribon ! I've got the effect.

![example31](https://cloud.githubusercontent.com/assets/10757813/22735458/15194a66-edfa-11e6-8578-27b87072e817.gif)


It's good to have an ability to add a video. Without that I guess I would be asking you some technical details of your browser settings. I marking this issue as a bug.

**Comment by floribon** [comment]
Hello, I was just wondering if there is any ETA on when this will be addressed? It should be a quick fix for a good value :)

**Comment by AMBudnik** [comment]
Sorry @floribon however, there's still no fix for the issue.

**Comment by floribon** [comment]
@AMBudnik just preventing the error to happen with a simple
```js
if (!data[row]) { continue; }
```
Fixes the issue and let me work on the rest. I had to fork handsontable just for this little fix. You can then spend more time if necessary to understand the root cause of the issue: obviously what this code is trying to do does not apply when the parent cell is merged.

I would be grateful if you could at least make the code not break with uncaught error.

![screen shot 2017-03-20 at 3 48 21 pm](https://cloud.githubusercontent.com/assets/2934743/24105363/e4d94842-0d84-11e7-915d-d44ae65db718.png)

**Comment by AMBudnik** [comment]
Thank you for your effort to test it @floribon 
our Support developer have checked the issue and found out that there's also one glitch with tracking directions so the fix is fine but it's more than that.

**Comment by jansiegel** [comment]
Should work fine in `0.37.0`.

**Comment by AMBudnik** [comment]
Hi @floribon 

Thank you for sharing the bug report. As @jansiegel said the issue has been fixed in the official 0.37.0 (PRO 1.17.0) version.

Please update and let me know if it works for you.
