### ISSUE TITLE
Checkbox state don't toggle properly in specific situation

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4037]
### Description
Checkboxes below the viewport don't change state properly for Handsontable initialized by `startRows` attribute (cell data is set to `null`).

### Steps to reproduce

1. Open demo: http://jsfiddle.net/wojciech/hb8r0667/7.
2. Click on the header.
3. Trigger space button.
4. Scroll down below the viewport.

### Demo

![bug](https://cloud.githubusercontent.com/assets/141330/22466561/1b8ac65c-e7c1-11e6-9701-62c3a3eb9bdb.gif)

http://jsfiddle.net/wojciech/hb8r0667/7

### Your environment
* Handsontable version: 28.4
* Browser Name and version: Chrome 56.0.2924.76 (64-bit)
* Operating System: macOS Sierra 10.12.2

**Comment by wszymanski** [comment]
Will be fixed in #3881

**Comment by AMBudnik** [comment]
Releases: v0.31.0
