### ISSUE TITLE
Nested context menus

### ISSUE THREAD

**Issue by madoar** [handsontable/handsontable#4038]
Is it possible to create nested context menu entries? 
An example for this is the normally present "alignment" menu item, which itself is a menu that contains multiple sub menu items.

**Comment by AMBudnik** [comment]
Hi @madoar 
Here's how to create a submenu: https://jsfiddle.net/yk387anr/
However there's currently an issue related to [using a second lever of a submenu](https://github.com/handsontable/handsontable/issues/3533). If you are building a `menu > submenu` structure it should work fine.

**Comment by madoar** [comment]
@AMBudnik Thanks for your help!
I couldn't find a description how to do this in the handsontable documentation. Is it possible that there is no section in the documentation that describes how to create context sub menus?

In addition to this I wanted to ask if it's possible to query the handsontable object if a single cell or a complete row/column is currently selected?
Depending on this information I want to display different context menu items.

**Comment by AMBudnik** [comment]
You're right I guess we should add more ideas on how to create a submenu in our docs. We are planning to add a How to section with examples like that however it is only a plan for the future,

When it comes to custom context menus for cells here's a demo that uses is: http://jsfiddle.net/handsoncode/m22wcxv7/ In this process it is more as adding an option for a whole menu and disabling it for some cells.

**Comment by swistach** [comment]
It's the same issue as #2298.
