### ISSUE TITLE
Corner element is gone when we merge cells

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4040]
### Description

_A separate issue made from: https://github.com/handsontable/handsontable/issues/4035_
When we merge any cells' area the corner element is gone (the one that allows us to drag the cell's value.
We need to click another cell and get back to merged one to get the element.

### Steps to reproduce

1. Merge any area of cells

![example17](https://cloud.githubusercontent.com/assets/10757813/22503086/4f482d4a-e870-11e6-83bc-e378ffa96336.gif)

### Demo

http://jsfiddle.net/handsoncode/9ohbshve/

### Your environment
* Handsontable version: 0.30.1/1.9.1
* Browser Name and version: Chrome 55
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
The issue is still replicable in v0.35.1. We need to unfocus the cell first.

**Comment by jansiegel** [comment]
Should work fine in `0.37.0`.

**Comment by AMBudnik** [comment]
Yes, it is. Thanks for spotting that @jansiegel 

Here's an updated demo http://jsfiddle.net/handsoncode/mk4p2Lae/
