### ISSUE TITLE
[Question:] onchange event on a particlular cell

### ISSUE THREAD

**Issue by tonyvince** [handsontable/handsontable#4041]
Is there a way to listen to the `onchange` event for a particular cell, say `row = 1 col = 1`? The cell is of `type: 'date'`

**Comment by AMBudnik** [comment]
The change hooks are listening all cells however you can perform an action for desired cell. You should just specify a condition based on the second parameter - source. 
Here's an example: http://jsfiddle.net/handsoncode/2zswwvs9/
