### ISSUE TITLE
Compare functions passed to sort function don't work as expected

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4042]
### Description
Empty cells (`null`, `undefined`, empty string value inside) are not sorted now, but their position isn't mapped properly after executing sorting. They should be stacked at bottom of table with order like in unsorted table (as sorting effect first empty row from unsorted table should have first position at bottom of table, second empty row from unsorted table should have second position at bottom of table etc.).

**edit: This ticket may not fix mapping empty cells completely** (i.e. for larger datasets in Google Chrome). I will focus here on comparing function (more information in comment below). Result of the test depends already on implemented by web browser **Array.sort** function.

### Steps to reproduce

1. Open demo: http://jsfiddle.net/wojciech/xknmzun8/7
3. Click on the first column header (A) to sort data.

### Demo

![sort](https://cloud.githubusercontent.com/assets/141330/22585040/032357c8-e9f6-11e6-87d3-4793f28f0d6d.gif)

http://jsfiddle.net/wojciech/xknmzun8/7

### Your environment
* Handsontable version: 0.30.1
* Browser Name and version:  Chrome 56.0.2924.76
* Operating System: macOS Sierra 10.12.2

**Comment by wszymanski** [comment]
Within this ticket will be fixed situation that **comparing function** handled by sorting function can change position of `null` or empty string objects. Within ticket #3606 will be changed situation that we use Web browser implementation of **Array.sort** which can be unstable.

**Comment by AMBudnik** [comment]
It's all clear now! Thanks for fixing @wszymanski
