### ISSUE TITLE
Add a validateCell/row/column method

### ISSUE THREAD

**Issue by madoar** [handsontable/handsontable#4048]
I believe that it would be quite helpful if the options object, that must be passed to the handsontable constructor, contains an optional `validateAfterInitialisation` field that automatically performs a `hot.validateCells()` call after the data of the table is initialised.

In addition to the addition of such a field, I would suggest to add a short description to the validator documentation that explains, after which actions a validator function is called. 
I know of at least 5 cases, where it would be useful to call a validator function, but I don't know if the handsontable instance calls the validator in these cases:

1. A new handsontable is created. (In this case I know that the validator is currently not automatically called and must be called manually via `hot.validateCells`)
2. A field inside the handsontable is edited. (In this case I know that the validator is automatically called for the edited field)
3. A row gets inserted inside the handsontable. (not sure if the validator is automatically called here)
4. A column gets inserted inside the handsontable. (not sure if the validator is automatically called here)
5. The data inside a handsontable is updated via a `loadData` method call. (not sure if the validator is automatically called here)

**Comment by AMBudnik** [comment]
Hi @madoar 
Thank you for your suggestion.

Regarding your points

1. That's right
2. That's right
3. Validator is not called automatically.
Here's a demo: http://jsfiddle.net/handsoncode/1ewjk1hv/, comment `hot2.validateCells()` to see that the cell doesn't get marked.
4. Validator is not called automatically.
Here's a demo: http://jsfiddle.net/handsoncode/2uq7hLb2/, comment `hot.validateCells()` to see that the cell doesn't get marked.
5. As above here we do not call validator automatically. Demo: http://jsfiddle.net/handsoncode/4L5wsdd4/ comment `hot.validateCells()` to see that the cell doesn't get marked.

**Comment by madoar** [comment]
Hi @AMBudnik 
If I understand you correctly I need to add a hook to the handsontable object that call `hot.validateCells()` every time a row or a column was added to the table, if I want to have the added row or column validated?

I believe that this approach is kind of inefficient, because every call of `hot.validateCells()` validates the whole table, instead of only the single added row or column. 
I believe it would be quite useful to have an additional command that validates a given row or column maybe: `hot.validateRow(rowIndex)` and `hot.validateColumn(columnIndex)`. 
Alternatively or additionally it would be a good choice to add an optional parameter to `hot.validateCells()` called `validateOnlyChanges` or something similar. 
This parameter tells the `validateCells` method to only validate the cells that were not validated previously, like added rows or columns. This would require the addition of a state to each cell that contains if the cell was previously validated.

To build onto this idea, I could imagine other clever parameters for `validateCells` like `validateInvalidFields` which revalidates all invalid fields in the table.

**Comment by AMBudnik** [comment]
Hi @madoar 

Yes, you would need to add a `validateCells` method inside a hook. Here's http://jsfiddle.net/handsoncode/2xaa62eo/ an example for `afterCreateCol`. What I have spotted is that you need to add a small delay (added 50ms) to make cell marked as invalid.

When it comes to efficiency I agree that there will be a lot of excess operations involved. It is a good idea to an an option to validate a single cell/row or a column however I do not know if this would be possible before adding the eco-rendering. I will mark this topic as a feature request and will allow myself to change the title.

When it comes to the second idea

> Alternatively or additionally it would be a good choice to add an optional parameter to hot.validateCells() called validateOnlyChanges or something similar.
> This parameter tells the validateCells method to only validate the cells that were not validated previously, like added rows or columns. This would require the addition of a state to each cell that contains if the cell was previously validated.

I can understand the main idea and the purpose of having this kind of method. However it will be hard to define a change here. Is change an action after table initialization or change is an action after we edit data or maybe when we load data? Currently there is a [afterChange ](https://docs.handsontable.com/0.30.1/Hooks.html#event:afterChange)callback that triggers data validation but it runs for all the cells in the data set. With the previously mentioned eco-rendering it will be triggered only for changed cell/row or column.

**Comment by AMBudnik** [comment]
I'm moving all the feature requests to our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests). Please feel free to leave any additional comments and reflections.

Thanks in advance!

**Comment by masato-io** [comment]
Any update on this feature by any chance?

**Comment by AMBudnik** [comment]
Hi @masato-io 

currently for validation we have 2 hooks https://docs.handsontable.com/pro/1.14.3/Hooks.html#event:afterValidate and https://docs.handsontable.com/pro/1.14.3/Hooks.html#event:beforeValidate

**Comment by AMBudnik** [comment]
Done with https://github.com/handsontable/handsontable/pull/4583
