### ISSUE TITLE
How to treat new numeric cell value as numeric type?

### ISSUE THREAD

**Issue by chengtie** [handsontable/handsontable#4049]
I have a piece of code which stringifies a handsontable: [JSBin](https://jsbin.com/zopicu/3/edit?html,js,output). Changing a cell value in the handsontable will change its corresponding string.

However, if we put a new **numeric** cell value in the table, it will be considered as **string** in the array, which does not align with other value format of the array.

I don't know why handsontbale treats all cell values as string type by default. Is there a way of setting up such that new **numeric** cell value is treated as **numeric** type?

Besides, if I want to adjust afterwards the value myself (i.e., from "string" to "numeric") in `$watch`, is there an easy way to find out which cell has been changed, rather than comparing all the cells of `newValue` and `oldValue`?

**Comment by stla** [comment]
Hello. If you want an entire column of numbers, you can use the column option `type="numeric"` (see the fiddle given [here](https://github.com/handsontable/handsontable/issues/4054) for an example).

**Comment by AMBudnik** [comment]
Thanks for your help @stla
