### ISSUE TITLE
Reflect the modification of a handsontable without changing the focus

### ISSUE THREAD

**Issue by chengtie** [handsontable/handsontable#4050]
I have a piece of code which stringifies a handsontable: [plnkr](https://plnkr.co/edit/znySzmSsJ3kV7smT34Js?p=preview).

When we modify a cell value, and click outside, its corresponding string will change systematically. However, I am wondering if it is possible to reflect the modification while modifying the cell value without having to clicking outside and change the focus.

**Comment by AMBudnik** [comment]
Hi @chengtie 
If I understand the case correctly did you try to load the logic inside the [beforeChange ](https://docs.handsontable.com/pro/1.9.1/Hooks.html#event:beforeChange) callback?

**Comment by AMBudnik** [comment]
I assume that we can close this issue as there is no reply. If you are still experiencing any difficulties please leave a comment @chengtie
