### ISSUE TITLE
version :0.30.1 , the cell commten don't show , it's bug?

### ISSUE THREAD

**Issue by stone512** [handsontable/handsontable#4051]
the demo :
http://jsfiddle.net/e9r6gxjy/5/

with version 0.30.1 don't show the comment, 

what can i do for it

code by offical :

 cell: [
      {row: 1, col: 1, comment: 'Some comment'},
      {row: 2, col: 2, comment: 'More comments'}
    ]

the is not  comment with row 1,col 1
![image](https://cloud.githubusercontent.com/assets/936938/22617256/39c2599a-eafb-11e6-981f-e6f46a1fc155.png)

**Comment by AMBudnik** [comment]
Hi @stone512 
Please define comment via `value` parameter like: `{row: 1, col: 1, comment: {value: 'Some comment'}}`

Demo: http://jsfiddle.net/handsoncode/oos9h7mx/

**Comment by stone512** [comment]
thank you ,@AMBudnik
