### ISSUE TITLE
reactively update border cell properties handsontable

### ISSUE THREAD

**Issue by yawlhead91** [handsontable/handsontable#4052]
Hi there ,

I am having some issues trying to get the custom border to load dynamically with a reactive source .
Instead of having it the normal way like so 

```
customBorders: [
      {
        range: {
          from: {
            row: 1,
            col: 1
          },
          to: {
            row: 3,
            col: 4
          }
        },
        top: {
          width: 2,
          color: '#5292F7'
        },
        left: {
          width: 2,
          color: 'orange'
        },
        bottom: {
          width: 2,
          color: 'red'
        },
        right: {
          width: 2,
          color: 'magenta'
        }
      },
      {
        row: 2,
        col: 2,
        left: {
          width: 2,
          color: 'red'
        },
        right: {
          width: 1,
          color: 'green'
        }
      }]
```

I have it firing a function like so 
```
customBorders: function(){

}
```

I have tried this but it never-fired and then if i gave it a few combinations of arguments but I get a error.

Cannot read property 'range' of undefined

The reason I am doing this is because I am using meteor js and I want to use a variable to set the widths and height, and from previous experience with the rowHeaders attribute I had to use a function. 

This is probably quiet an easy thing but I can not figure it out.

Thanks

**Comment by AMBudnik** [comment]
Yup, I can agree it is pretty complicated as we have a lot of nested objects here and if you would like to pack it all in a function you would need to have many parameters:

1. Staring row  (as a part of a `range` object)
2. Staring column (as a part of a `range` object)
3. Ending row (as a part of a `range` object)
4. Ending column (as a part of a `range` object)
5. Width for a left border (as a part of a `left` object)
6. Color for a left border (as a part of a `left` object)
7. Width for a right border (as a part of a `right` object)
8. Color for a right border (as a part of a `right` object)
9. Width for a top border (as a part of a `top` object)
10. Color for a top border (as a part of a `top` object)
11. Width for a bottom border (as a part of a `bottom` object)
12. Color for a bottom border (as a part of a `bottom` object)

but you can also make it smaller if you would like to define single cells, like

```
 customBorders: [{
      row: 2,
      col: 2,
      left: {
        width: 3,
        color: 'blue'
      }
    }]
```

Demo: http://jsfiddle.net/handsoncode/a3m763ch/

**Comment by yawlhead91** [comment]
@AMBudnik  Thanks again you have been great help again. Supper fast reply , Thanks

**Comment by AMBudnik** [comment]
You're welcome :) not sure how much this will help however I'm here if you'd need any help.

**Comment by AMBudnik** [comment]
Hope the project is going well. I assume that we can close this issue as there is no reply.

**Comment by yawlhead91** [comment]
Oh Sorry no you answer previously was perfect thanks

**Comment by AMBudnik** [comment]
Thanks for confirming @yawlhead91 
have a great day :)
