### ISSUE TITLE
Webpack reports that it cannot find module 'handsontable'

### ISSUE THREAD

**Issue by focher** [handsontable/handsontable#4053]
I have attempted to use the solution in [Issue #3718](https://github.com/handsontable/handsontable/issues/3718). It didn't work for me but have attempted to adjust per below.

### Description

When attempting to import Handsontable, I receive the error:

`error TS2307: Cannot find module 'handsontable'.`

### My configuration

`index.module.ts`
```
import Handsontable from 'handsontable';
import 'handsontable.css';
```
`webpack-common-config.js`
```
noParse: [path.resolve(__dirname, '../node_modules/handsontable/dist/handsontable.full.js')],

alias: {
'handsontable': path.resolve(__dirname, '../node_modules/handsontable/dist/handsontable.full.js'),
'handsontable.css': path.resolve(__dirname, '../node_modules/handsontable/dist/handsontable.full.css')
}
```

### Kinda Sorta Workaround

I can force it to work with `npm start` (`webpack-dev-server -d --inline --progress --host 0.0.0.0 --port 8080 --hot`) if I insert the `<script>` tag in `index.html`

`index.html`
```
<script src="node_modules/handsontable/dist/handsontable.full.js"></script>
```

However, when I attempt to create the build with `npm run build` (`rimraf dist && webpack --config config/webpack-prod.config.js --progress --profile --bail`) then the `handsontable.full.js` is not incorporated into the bundle. I get no webpack error in this scenario, but the application will not start with the following browser console errors:

```
ReferenceError: Can't find variable: Handsontable
Error: [$injector:modulerr] Failed to instantiate module inplan due to:
[$injector:nomod] Module 'myApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. 
```

**Comment by AMBudnik** [comment]
Thanks for sharing @focher 
I will ask our developer to take a look at it.

**Comment by madoar** [comment]
Hi @focher I guess you're writing an angular 2 application? Did you add a dependency to the handsontable types library? 

In my angular 2 project (created with angular-cli) it worked by adding the js and css files to the `angular-cli.json` file and either declaring the variable `Handsontable` or by adding a development dependency to the type library for handsontable (@types/handsontable).

**Comment by focher** [comment]
Hi @madoar I'm actually using TypeScript in an Angular 1 app. For most packages, it's as simple as an `npm install --save <<package>>` then add an `import <<package>>` in the index.module.ts file. For Handsontable, there's also the `ng-handsontable` package which I import and also specify in `angular.module`.

As I mention above, I can leave the `import Handsontable` out of index.module.ts and just use a `<script src="node_modules/handsontable/dist/handsontable.full.js"></script>` reference. This isn't my preference because when I deploy it, Webpack isn't bundling the handsontable.full.js and rewriting the `<script>`. Then ng-handsontable doesn't see the handsontable.full.js because it wasn't bundled.

I'm ok with my bad workaround, but mostly opened the issue to let others know that the solution offered to this very problem in #3718 doesn't seem to always work.

**Comment by kryft** [comment]
@focher Note that the error you're getting comes from the TypeScript compiler ("TS2307"); it's not really a webpack problem.

I had the same issue six months ago. The TypeScript type declarations for handsontable declared a global variable called `Handsontable`; I don't remember if they declared a module at all, but in any case I couldn't get importing to work. Eventually I gave up and just used handsontable as a global variable in my TS code without importing anything, as you did.

You can use webpack.ProvidePlugin to make webpack provide handsontable as a global variable, which will also make sure that it gets included in the bundle:

```
// webpack.config.js
var providePlugin = new webpack.ProvidePlugin({
  "Handsontable": "handsontable/dist/handsontable.full.js"
});

module.exports = {
  module: {
    noParse: [path.join(__dirname, "node_modules/handsontable/dist/handsontable.full.js")]
  },
  plugins: [providePlugin],
}
```

**Comment by focher** [comment]
That is awesome and worked great! Cannot thank you enough as this has been a source of frustration as every time I deploy, I need to manually perform those steps to make the Handsontable.js file available.
