### ISSUE TITLE
Formula support in handsontable

### ISSUE THREAD

**Issue by bimcio** [handsontable/handsontable#4056]
Hi, 
I started evaluating handsontable (currently playing around with PRO version). I am especially interested in support for excel-like formulas but I am a bit confused about the information I found in the documentation and on your site (some of them seem to be outdated?). Thus I would like to ask for clarification what is the current status of this support (in regard to free and PRO versions) as well as what are the plans for near future (I seen you have some plans to improve formula support in this year). What external libraries are used/supported now? Do you plan to change it when working on new features next months?

greetings,
Bartek

**Comment by AMBudnik** [comment]
Hi @bimcio 

I have to admit that the Formula subject is pretty complicated. 

Currently we support only Formulas in the PRO version but the plugin that does that is in [alpha version](https://docs.handsontable.com/pro/1.9.1/demo-formula-support.html). We are planning to create a stable version in 2017 however without any specified date yet. We are also planning to support formulas in a free version however we nee to make them stable first.
