### ISSUE TITLE
Undo doesn't work with column functions

### ISSUE THREAD

**Issue by GMNGeoffrey** [handsontable/handsontable#4057]
### Description
Normally hitting ctrl+z triggers an undo. Nothing seems to happen with column functions.

### Steps to reproduce
Have the column as a function.
Make an edit
Hit ctrl+z

### Demo
Compare undo behavior in the documentation jsfiddle for array data source and function data source: ~~http://docs.handsontable.com/0.16.1/tutorial-data-sources.html~~

Edit: Link to the latest version, http://docs.handsontable.com/0.30.1/tutorial-data-sources.html

### Your environment
* Handsontable version: Whatever is running in the documentation examples
* Operating System: Chrome OS 55.0.2883.105 (64-bit)

**Comment by AMBudnik** [comment]
Thanks for sharing @GMNGeoffrey 

I wasn't able to undo any change in the last demo on that page. Here's the mentioned demo in v0.30.1 (newest): http://jsfiddle.net/handsoncode/edkohurv/

**Comment by GMNGeoffrey** [comment]
My apologies for linking to the wrong version. Not sure how that happened. Undo does not appear to work in the latest version either.

**Comment by AMBudnik** [comment]
That's not a problem @GMNGeoffrey especially if it does not work for both versions. 
I've added the demo above separately as you can see the code in one click without scrolling to the mentioned example.

**Comment by zoladkow** [comment]
Hi 

Adding a new demo to this, to not start another issue.

http://jsfiddle.net/zoladkow/aLfg3tq4/

1. Open F12, 
2. type 'a' in first cell, save. Result -> edit: [[0,2,"Nissan","a"]]
3. use undo (ctrl+z). Result -> UndoRedo.undo: [[0,2,"Honda","Nissan"]]


Sometimes the undo doesn't work, but most of the time UndoRedo.undo afterChange() callback gets the wrong oldVal value.

We are working on a workaround now (well also a functionality to preserve change history even inbetween data reload - like paging etc.), but would be nice this could work right again :)

**Comment by AMBudnik** [comment]
Thank you for sharing @zoladkow 

`[[0,2,"Honda","Nissan"]]` is not exactly what we would expect to get.

**Comment by emnajaoua** [comment]
what's the status of this MR ? 
For me, when I add a column manually. The column that I add is by default has a row with 2 headers. Then, when I undo the first time, it doesn't remove the column. Only when I do it two times, it removes the column.
I tried to make my header nested using the nestedHeaders option but still no luck!

**Comment by AMBudnik** [comment]
Hi @emnajaoua Can you share a demo that describes the issue you're experiencing?

**Comment by pedig** [comment]
Hi, what is the status of this issue? After some debug I found that after a deep clone in function UndoRedo.ChangeAction.prototype.undo the column function disappears from the changes.

**Comment by AMBudnik** [comment]
Hi @pedig the issue hasn't been scheduled yet.

I highly encourage to share a pull request.

**Comment by pnowak** [comment]
Good news! This issue got solved v8.0.0. Here's an updated demo - https://jsfiddle.net/bcdx8nm9/

**Comment by AMBudnik** [comment]
I'm glad to hear that this issue is gone. @GMNGeoffrey @pedig @emnajaoua @zoladkow please let us know if it works for you as well.
