### ISSUE TITLE
HandsOnTable

### ISSUE THREAD

**Issue by ArditKurti** [handsontable/handsontable#4058]
### Description
Hi guys first of all good job.
I have a problem with handsontable.
So i want to parse an object from an csv file i convert with papaparse.
The problem is the data doesnt show when i try to use the pagination

### Steps to reproduce
So this is my code.
I hope u help me

### Demo
$(document).ready(function() {

    $("#csv-file").click(function () {
        $("#csv-file").change(handleFileSelect);
    })

});

function handleFileSelect() {
    var files = $('#csv-file')[0].files;
    var config = buildConfig();

    $('#csv-file').parse({
        config: config,
        before: function (files , inputElem) {
            console.log("Parsing file:", files);
        },
        complete: function()
        {
            console.log("Done with all files.");
        }
    });
}

function buildConfig() {
    return {
        header: true,
        dynamicTyping: false,
        complete: completeFn
    }
}

function completeFn()
{

    var container = document.getElementById('csv-table');

    var getData = (function () {
        if (arguments[0] === undefined) {
            return;
        }
        var csvData = arguments[0].data;

        return function () {
            var page = parseInt(window.location.hash.replace('#', ''), 10) || 1;
            var limit = 10;
            var row = (page - 1) * limit;
            var count = page * limit;
            var part = [];

            for (; row < count; row++) {
                part.push(csvData[row]);
            }

            return part;
        };
    });

    var hot = new Handsontable(container, {
        data: getData(),
        colHeaders: arguments[0].meta.fields,
        fixedRowsTop: 0,
        columnSorting: true,
        sortIndicator: true,
        contextMenu: true
    });

    console.log(arguments);
}

**Comment by AMBudnik** [comment]
Hi @ArditKurti 

If you're using the pagination example from here: https://docs.handsontable.com/pro/1.9.1/demo-paginating.html you will always get only data that is visible in your current page.
Sample demo: http://jsfiddle.net/handsoncode/5w7bw7ea/ This happens cause in this demo you are loading parts of data and do not refer to the `data` array (whole data set).
