### ISSUE TITLE
"updateSettings" doesn't update classes

### ISSUE THREAD

**Issue by pbadenski** [handsontable/handsontable#4059]
### Description
"updateSettings" doesn't update classes

### Steps to reproduce & Demo
See here for working example: http://jsfiddle.net/qh6a3Lvx/

Table should be green.

### Your environment
* Handsontable version: Latest
* Browser Name and version: Chrome 56.0.2924.87 (64-bit)
* Operating System: Mac Sierra (10.12.3)

**Comment by AMBudnik** [comment]
Thanks for sharing @pbadenski 
You're right - it's a bug.

**Comment by wojciechczerniak** [comment]
Duplicate of #6295. The fix is on its way #6425
