### ISSUE TITLE
manualRowMove moves rows even when it's not needed

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4060]
### Description
The plugin trying to change rows order, even when a visual order of rows was not changed.

### Steps to reproduce
1. Go to the demo.
2. Select `5:7`
3. Click in some header of the selected rows.
Result: Rows was moved to the same position.

### Demo
http://jsfiddle.net/phm2zbhh/

### Your environment
* Handsontable version: 0.30.1
* Browser Name and version: Any
* Operating System: Any

**Comment by AMBudnik** [comment]
Can we also check if the docs aren't misleading when it comes to indexes (logical/physical)? 
There's an issue here https://github.com/handsontable/handsontable/issues/3934 where we were reported about it.

**Comment by swistach** [comment]
I think, we should resolve these issues separately :)

**Comment by AMBudnik** [comment]
Checked. Thanks for fixing @swistach 
Updated example: http://jsfiddle.net/handsoncode/2sh9gdur/
