### ISSUE TITLE
inconsistency in beforeKeyDown between text cells and other cells, or cells with and without validation

### ISSUE THREAD

**Issue by koenhandekyn** [handsontable/handsontable#4064]
### Description

i'm trying to read the current cell value inside a beforeKeyDown event (e.g. when tab is pressed). when the cell is of any type except text or it has a validator on it, we read the actually value with the below code, except when the cell of type text and there is no validator on it, than the value reads 'null'. this behaviour is quite inconsistent. 

current work around is to add a validator that always returns true. 

### Steps to reproduce

any hot with the following event handler

    beforeKeyDown: function(event) { 
      if (event.key == "Tab") {
        var selected = parts_hot.getSelected();
        var startRow = selected[0];
        var startCol = selected[1];
        var current = parts_hot.getDataAtCell(startRow, startCol);
        console.log(current);
      }
    }

### Your environment
* Handsontable version: 0.30.1
* Browser Name and version: chrome
* Operating System: mac

**Comment by AMBudnik** [comment]
Hi @koenhandekyn 
I put your code in a Fiddle at: http://jsfiddle.net/handsoncode/wfgkvwqc/ and I am getting correct values (tested with `string` and `number`).

Here's what I got.

![example](https://cloud.githubusercontent.com/assets/10757813/22778822/8cc2c54c-eeb8-11e6-8a32-d2544fe8ede8.gif)

Do you get `null` when you use <kbd>TAB</kbd> on `2012` from my example? The `2012` cells defined as a number and it uses NumericValidator.

**Comment by koenhandekyn** [comment]
i have to confirm the behaviour in isolation !
indeed it’s consistent the old value and adding validators doesn’t seem to have real impact (also tested). 

what i was actually expecting as behaviour was reading the ‘current’ value. 
how would one be able to read the ‘current’ (new) value ?

kind regards
koen

**Comment by AMBudnik** [comment]
Oh, yes you're right - we're getting old value. I looks like the key event is fired before the change. You can get new value by adding a micro delay: http://jsfiddle.net/sxs2e1hz/

I will check callbacks involved in this process. Thanks for sharing!

**Comment by AMBudnik** [comment]
This issue is solved http://jsfiddle.net/AMBudnik/zeycatnL/
Please update to the latest version.
