### ISSUE TITLE
Custom renderer not work with validators

### ISSUE THREAD

**Issue by minchopm** [handsontable/handsontable#4065]
### Description
I am trying to validate cells with custom renderer but without success.
The validator function is triggered correctly but there are no classes append to the cells.
Is there a way to define validator for the renderer or how to make both to work together?

### Your environment
* Handsontable version: 0.30.1
* Browser Name and version: chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hi @minchopm 

Here's an example with a custom renderer and working (validatable) numeric cells: http://jsfiddle.net/9b18v3x0/

**Comment by minchopm** [comment]
Not the correct answer

**Comment by AMBudnik** [comment]
Hi @minchopm 
If I did not understood the example please share more details or if you can share your own demo. I guess it will be the best way to get the idea.

**Comment by AMBudnik** [comment]
@minchopm 
can you share more details about this request?

**Comment by AMBudnik** [comment]
I am closing this issue in lack of needed information.

Please leave a comment if you still have any issues regarding this topic.
