### ISSUE TITLE
Formula does not get initially evaluated with column mapping

### ISSUE THREAD

**Issue by Ubersteinn** [handsontable/handsontable#4066]
### Description
Formulas are not initially evaluated when a column uses data mapping.
Editing the cell fixes the issue.

### Demo
Cell A1 is not evaluated as a formula since its column is using data mapping.
The cells in other columns with formulas are not effected.
https://jsfiddle.net/Ubersteinn/xf28qLqo/

### Your environment
* Handsontable version: pro 1.9.1

Any workaround would be greatly appreciated!

**Comment by Ubersteinn** [comment]
Thank you for your quick response!
I have looked a little into the code. 

The recalculateFull() and recalculateOptimized() methods in sheet.js get the source data object but do not take into account the mapping.
This may be the root cause.
I hope this helps!

**Comment by gstenson** [comment]
Have noticed this too. Any update on this? 

This renders formulae unusable in anything bar simple applications in the PRO version, as if you are loading and binding them to/from an external source then they need to evaluated on initialisation.

**Comment by AMBudnik** [comment]
Hi guys,

Formula plugin is in an alpha stage. We have stopped our work on a more stable version but we will hopefully get back to it in Q3 or Q4.

**Comment by rohitjoshi1990** [comment]
Would really like an update on this ?

Evaluating formulas on data initialization is crucial, since currently `Object data source with column mapping` is used to render entire Handsontable Matrix & changing data representation just to use formulas does not seem right.

**Comment by AMBudnik** [comment]
Hi @rohitjoshi1990 

we are working on a calculating engine that will allow handling all the operations bugless and super-fast, however, this is an innovative approach and it will definitely take us a couple of weeks.

**Comment by AMBudnik** [comment]
Updated to `7.1.1` https://jsfiddle.net/mujLfc3w/
The issue stays the same `A1`'s formula is not evaluated.

![Zrzut ekranu 2019-09-27 o 10 33 11](https://user-images.githubusercontent.com/10757813/65754851-38cb0180-e112-11e9-9580-ac247731b14c.png)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by aninde** [comment]
This issue works different with HyperFormula. 
There is an console error with v9.0.0 that we should address and the table doesn't renderer.
https://jsfiddle.net/aninde/xt9gqbpk/
```
handsontable.full.js:4685 Uncaught Error: Unable to parse value: {
    "value": "=$B$2"
```

**Comment by hihhhello** [comment]
Was it fixed?

**Comment by AMBudnik** [comment]
Hi @hihhhello 

The issue is temporarily closed but not fixed yet. I will inform you after the fix.
