### ISSUE TITLE
New hooks to control the data during cut/copy/paste.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4068]
### Description
We should give possibility to control over the data, during `copy` and `paste` actions.

- [x] beforeCut
- [x] afterCut
- [x] beforeCopy
- [x] afterCopy
- [x] beforePaste
- [x] afterPaste
+ [x] tests
+ [x] documentation

Partially based on #2877.

**Comment by brandond** [comment]
Related copy/paste behavior issue: https://github.com/handsontable/handsontable/issues/3538
