### ISSUE TITLE
Maximum column limit 

### ISSUE THREAD

**Issue by sir21** [handsontable/handsontable#4069]
### Description
I need to make a table with 200+ columns. All the data is saved in JSON file. When I load the table Maximum number columns is 195. Is 195 is the maximum limit of the columns?

**Comment by AMBudnik** [comment]
Hi @sir21 
There is no limit for amount of columns you can have in your data set. Maybe they are just not rendered? They do not appear after scrolling or editing the sibling column?

**Comment by sir21** [comment]
They were not rendered. I found the issue and fix it. Thanks for your help.
