### ISSUE TITLE
Migration to babel

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4070]
### Description
About two years ago Handsontable was modularized. Main goal of this project was support for ES6 features and allow building Handsontable without unnecessary plugins. When it was under development we had two choices - we could use either Traceur or 5to6 (now babel). After several tests about transpiling time and about size of the generated source code we have chosen Traceur. We created a tool called hot-builder to handle this job and replaced most of the grunt tasks with it.

Today, modern browsers have better support of ES6 that we can use when developing code. So, basically now it is the perfect time to make some changes. Below you can find tasks which should be done with some explanations based on my experience related to work on this stack:

1. Get rid of [hot-builder](https://github.com/handsontable/hot-table) connections from Handsontable.
    Why? Because it is hard to maintain. It should be as simple as it can to correct stack configuration for any developer (in the same repository where code exists).
2. Babel has grown up, so it is a great time to check how it can cope with Handsontable source code.
    Why? Because it is the most popular transpiler.
3. Make possible to write tests using ES6.
    Why? Better experience for developers.
4. It is necessary to compare bundle size, transpiling time and Handsontable performance after migration to babel.

**Comment by budnix** [comment]
The first stage of migration was completed. Branch [feature/issue-4070](https://github.com/handsontable/handsontable/tree/feature/issue-4070) was merged into develop. The next necessary changes will be committed into [feature/issue-4070-part1](https://github.com/handsontable/handsontable/tree/feature/issue-4070-part1).

These changes are:
 - Update demos located into `/demo` directory.

**Comment by budnix** [comment]
The next changes will be committed into feature/issue-4070-part2.

These changes are:
 - New npm tasks for testing `npm run test:e2e.watch` and `npm run test:unit.watch`.

**Comment by budnix** [comment]
The part2 was merged into develop.

**Comment by budnix** [comment]
The part3 was created. It includes:

 - Fix for tests ran into phantomjs. For now, grunt tasks always exists with code `0` even tests are not passed.

**Comment by budnix** [comment]
The part4 branch was created. It includes:

 - Excludes webpack node polyfills from generated bundles.

**Comment by budnix** [comment]
The part4 was merged into develop.

**Comment by AMBudnik** [comment]
It is big step forward which hopefully will help us work faster and more efficient.
Thanks for your input @budnix
