### ISSUE TITLE
Disable undo if change wasn't made

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4072]
### Description

Currently when we hit <kbd>ENTER</kbd> to turn cell into edit mode without changing its content we add it to the undo stock. In the result when we want to undo changes we undo unchanged cell.

### Steps to reproduce

1. Type anything in `B2`
2. Hit <kbd>ENTER</kbd> (to confirm)
3. Hit <kbd>ENTER</kbd> twice (this will open and close cell `B3`
4. Use context menu (or <kbd>CTRL</kbd> + <kbd>Z</kbd>) to undo changes

As you can see you have to use the undo twice to undo changing `B2`.

![example2](https://cloud.githubusercontent.com/assets/10757813/22886450/3dcbae56-f1fe-11e6-9f8e-d36fef1ccf64.gif)

### Demo

http://jsfiddle.net/handsoncode/o7erkndt/

### Your environment
* Handsontable version: 0.30.1
* Browser Name and version: Chrome 55
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Works the same in 0.35.0. Updated demo http://jsfiddle.net/46kwyg1e/

**Comment by AMBudnik** [comment]
The same issue is reported at https://github.com/handsontable/handsontable/issues/4866

**Comment by wojciechczerniak** [comment]
Not exactly the same as #4866. We might have a fix without changing `afterChange` hook.

**Comment by AMBudnik** [comment]
Thank would be cool

**Comment by AMBudnik** [comment]
Glad to see this issue gone. Thanks guys!
