### ISSUE TITLE
Error on helpers/dom/elements.js#L44 call

### ISSUE THREAD

**Issue by webmcheck** [handsontable/handsontable#4074]
### Description 
I've got error message: `Uncaught TypeError: Cannot read property 'parentNode' of null`

### Steps to reproduce
1. Enable contextMenu and comments 
<s>2. Add some tag without any attributes to the document</s>
2. Add `a` tag without `href` attribute
3. Click on it!

### Demo
https://jsfiddle.net/wdt2m1Lu/2/
https://jsfiddle.net/1hjfyL6g/1/

### Where is the problem
Check this line: https://github.com/handsontable/handsontable/blob/master/src/helpers/dom/element.js#L44

This part of code always returns `true` if element is `a` and <s>haven't attributes</s> haven't href: `nodes.indexOf(element) > -1`
It happens because `element.toString()` return empty string. 

### Environment
* Handsontable version: 0.31.0
* Browser Name and version: Chrome 56.0.2924.87
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Mhm... OK, that an interesting issue. Thanks for sharing @webmcheck

**Comment by swistach** [comment]
This should be priority hight, because `onMouseDown` is mounted to the `document`.
https://github.com/handsontable/handsontable/blob/master/src/plugins/comments/comments.js#L469

**Comment by AMBudnik** [comment]
thanks for checking @swistach

**Comment by AMBudnik** [comment]
Hi @webmcheck 

the issue should not longer exist in v0.32.0. Thanks for sharing. I hope it works for you as well. Please let me know.
