### ISSUE TITLE
sortIndicator is cut when header content is longer 

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4075]
### Description

sortIndicator is cut when header's content is longer than cell's content underneath. It looks like it was working like this since the beginning.

### Steps to reproduce

1. Click any header to activate sorting

### Demo

http://jsfiddle.net/handsoncode/jkrkkm7u/

![example2](https://cloud.githubusercontent.com/assets/10757813/22974257/c7f9a568-f381-11e6-80d5-5323d06045e7.gif)
here we see only few pixels

...and in the example below we can see a half of it.

![example3](https://cloud.githubusercontent.com/assets/10757813/22974308/fe03e3bc-f381-11e6-9ac4-d76e1d58ea32.gif)

demo: http://jsfiddle.net/handsoncode/58w8crhu/

### Your environment
* Handsontable version: 0.31.0
* Browser Name and version: Chrome 55 / FF 51
* Operating System: Windows 10

**Comment by PavelStefanov** [comment]
+1
It's small but unpleasant issue. Please fix=)

**Comment by AMBudnik** [comment]
Already reported at https://github.com/handsontable/handsontable/issues/2533
