### ISSUE TITLE
(doc) click on "search" option does not direct to the "search" option

### ISSUE THREAD

**Issue by stla** [handsontable/handsontable#4076]
A detail: when we click on the "search" option on docs.handsontable.com (in the left pane, below "rowHeights") then we are not directed to the "search" paragraph but to the "Search" input box.

![capture](https://cloud.githubusercontent.com/assets/4466543/22990937/145ab332-f3bb-11e6-9803-d3e543689a8e.PNG)

**Comment by AMBudnik** [comment]
Thanks for sharing @stla 
you're right. I have moved this issue to our docs repository as it is not a bug of the software. It is at: https://github.com/handsontable/docs-pro/issues/9

Thanks again!
