### ISSUE TITLE
Scrolling is laggy in Internet explorer

### ISSUE THREAD

**Issue by Sune1337** [handsontable/handsontable#4077]
### Description
Scrolling is laggy in Internet Explorer.
The issue occurs if I do not set the 'height' option.
I do not want to set the height option because i want Handsontable to display all available rows.

ps. I'm referring to the scrollbar that the browser is displaying. Not the scrollbar Handsontable creates.

### Demo
Laggy scrolling (not setting height): http://jsfiddle.net/kswrq4eh/2/
Smooth scrolling (setting height): http://jsfiddle.net/kswrq4eh/3/

### Your environment
* Handsontable version: 0.31
* Browser Name and version: IE 11.576.14393.0
* Operating System: Windows 10 Home

**Comment by Sune1337** [comment]
I actually see a small difference in scrolling performance in Chrome too; its just barely noticable.

**Comment by AMBudnik** [comment]
Hi @Sune1337 
this issue has been already reported at https://github.com/handsontable/handsontable/issues/2350
If you have any other thought please leave a comment at https://github.com/handsontable/handsontable/issues/2350

**Comment by Sune1337** [comment]
ah, thanks
