### ISSUE TITLE
Get data from row when changed

### ISSUE THREAD

**Issue by sebastiendecraene** [handsontable/handsontable#4078]
I want to get the cell value directly when I edit some cell and then excecute a method, is there any possible way to do this? And also I want to run a method when I double click on a cell, is this possible?

**Comment by AMBudnik** [comment]
If you want to get data at row **after** some cell was changed you can use the [afterChange ](https://docs.handsontable.com/pro/1.10.0/Hooks.html#event:afterChange) hook.

Here's an example for object data: http://jsfiddle.net/handsoncode/y7nogq28/
