### ISSUE TITLE
how can I selection another cells when in editing state

### ISSUE THREAD

**Issue by chauvetxiao** [handsontable/handsontable#4079]
### Description
I'm doing a feature about formula,when the table is in editing state, I want to make a range with highlight and borders to automatic get user selections,so this range can give to formula to make a calculation.

### Steps to reproduce
1.when click a menu,the target cell shows a custom editor with content like '=SUM( )'
2.then use mouse to select a range, the cell which in edit state will lose focus
3.I trid use the hooks about mouseevent,but it does't work

### Your environment
* Handsontable version:0.29.0
* Browser Name and version: chrome
* Operating System: OS X 10.11.6

**Comment by AMBudnik** [comment]
Hi @chauvetxiao 

currently you cannot select any cell while having an active cell editor.

**Comment by chauvetxiao** [comment]
OK，thanks @AMBudnik ,I find a way to modify the source code where to control the variable keepEditorOpened,so I can select another selection while having an active cell editor.

**Comment by AMBudnik** [comment]
Thanks for keeping me updated @chauvetxiao 
we will be definitely adding this feature while adding the ability to click & add a cell via formulas.

**Comment by sudofix** [comment]
any updates on how to achieve something like this in the current versions? basically selecting a range of cells to add to the formula while editing the formula in some other cell

**Comment by AMBudnik** [comment]
@sudofix this issue seems to be the duplicate of the issue https://github.com/handsontable/handsontable/issues/2813 . Thank you for spotting that. I will connect those issues so everyone interested in this issue gets an update upon feature introduction.
