### ISSUE TITLE
How can I get All table property or table object

### ISSUE THREAD

**Issue by tjdah13** [handsontable/handsontable#4080]
### Description

I want to save on changed handsontable data my Data base after modify working.
but I can't find any way to get current whole table data.
even though handontable instanse give table object (instance.table), but it just has limited informations.
(ex.  my actual table : 100 cols by 200 rows but return table has only rendered data. like 11cols by 9 rows)

I tried set hotsetting renderAllRows : true, but it works only on row, not column.

my expectation : two ways to slove my problem
1) renderAllColums and get instance table
2) just get virtual rendered table if it is exist somewhere.

If there is anyone who know how to solve my problem, please reply.
Thank you.

### Your environment
* Handsontable version: lastest version on github
* Browser Name and version: IE / crome
* Operating System: windows7

**Comment by Sune1337** [comment]
If you're passing a data object to Handsontable when you create it, you can just save a reference to that and post to your server.

See example: https://jsfiddle.net/dkq1wrLu/

**Comment by Sune1337** [comment]
And if you don't want to post the data that is initially loaded you can filter that out.

See example: https://jsfiddle.net/dkq1wrLu/1/

**Comment by AMBudnik** [comment]
thank you for help @Sune1337 

@tjdah13 if you need anything else please let us know

**Comment by tjdah13** [comment]
thank u Sune1337. I actually need not only all data set but also 'td' tag properties of table.
I solved my problem use re-rendering my handsontable after updating setting;
like this..

hot.updateSettings({ height : 1/0, width : 50000 });
hot.render();
var ins = hot.getInstance();
var table = ins.table;
...

then finally, I got all table properties.
