### ISSUE TITLE
Handsontable steals focus from input elements in column headers

### ISSUE THREAD

**Issue by orb3b** [handsontable/handsontable#4082]
### Description
I want to place an html text input element into column headers of handsontable.
I took one of the examples from here
http://docs.handsontable.com/0.31.0/demo-custom-renderers.html
as a start and built a simple demo in jsfiddle
http://jsfiddle.net/p8Lzc3n4/4/

Everything seems to work perfectly, but when I want to select the text in
input text box from the end to the beginning, right after the cursor crosses the left edge of the input,
the text gets deselected. It seems that handsontable steals focus from the input to implement its own selection.

I recorded the cursor movement on a video. You can look at or download it from here
https://drive.google.com/open?id=0B-os4riCz4cSMGVUWm9RejNWOVE

Is there any way to configure handsontable to **not** steal focus from the input elements inside column headers?

### My environment
* Handsontable version: 0.31.0
* Browser Name and version: Google Chrome 56.0.2924.87

**Comment by AMBudnik** [comment]
Hi @orb3b 

hm... I was able to get the text selected

![example355](https://cloud.githubusercontent.com/assets/10757813/23072056/af16824a-f530-11e6-85c6-abfa5360fd6f.gif)

I'm testing it on Chrome 55 / Windows 10. Can you send me your Os/Browser settings?

However as you can see the value is gone after table is rerendered so if you would like to keep it you should set it as a value inside the header.

**Comment by orb3b** [comment]
Hi @AMBudnik,

Sorry, it seems I forgot to mention that the left mouse button is pressed during the movement.

Deselection happens when you start selecting the text in textbox in the second column from right to left,
and after the whole text gets selected, move the cursor to the first column. It is important that you don't release the mouse button after you have selected the text, and start moving the cursor to the first column while the button is still pressed.

My OS/Browser settings are:
Windows 7 (64-bit)
Google chrome 56.0.2924.87 (64-bit)

**Comment by AMBudnik** [comment]
OK, now I get it. The next is deselected when the cursor is placed on the first column.

**Comment by AMBudnik** [comment]
Demo updated to 0.35.0 http://jsfiddle.net/Lkpq9zdo/

Type anything in the input and use a mouse to select the text. If you move the mouse too far to left the text gets unselected.
![gif](https://user-images.githubusercontent.com/10757813/35044384-7ba0a7da-fb90-11e7-8d6b-a56e46aecad7.gif)
We can try to check if keeping the text selected while leaving the input is a doable and suitable solution.

**Comment by nightsource** [comment]
Hi,

I have the same problem. Any solution?

**Comment by nightsource** [comment]
Just found the solution https://forum.handsontable.com/t/html-content-loses-focus-in-version-1-15-1/1882

**Comment by AMBudnik** [comment]
Hey @orb3b @nightsource 
we've fixed an issue with a very similar description here https://github.com/handsontable/handsontable/issues/5541 in v `7.0.0`. Can you update and check if it works for you?

**Comment by AMBudnik** [comment]
I'm closing the issue as there's no reply. If we're missing anything please let me know.
