### ISSUE TITLE
autoColumnSize does not respect merged cells

### ISSUE THREAD

**Issue by AfflatusX** [handsontable/handsontable#4083]
### Description
What happens:
If autoColumnSize is turned on and I have two cell's that are merged, the width was only calculated based on the left cell. The result is that the column becomes much wider than it should be.

What should happen:
autoColumnSize should calculate the min width of the cell based on non-merged cells plus the right most cell of the merged ones.

Demo:

http://jsfiddle.net/fe91wefu/2/

**Comment by AMBudnik** [comment]
Hi @AfflatusX 

Can you resend a demo? I see that you've added steps but there's no demo.

**Comment by AfflatusX** [comment]
Hi @AMBudnik , here is the demo: http://jsfiddle.net/fe91wefu/1/

As you can see, B0 is longer than it should be.

**Comment by AMBudnik** [comment]
Hi @AfflatusX 
I am not sure if we get the same result (which cell is `B0`?). Can you check if adding row or column headers solves the issue?
It may be related to https://github.com/handsontable/handsontable/issues/3837

**Comment by AfflatusX** [comment]
ah my bad - updated the demo: http://jsfiddle.net/fe91wefu/2/

and I was talking about cell A2 - as you can see, it's the same width as A1 before the merge. Column 'A' should have the width equal to A2, instead of A1 (that's the behavior if you have the same table in Excel and try to auto-size A column)

**Comment by AMBudnik** [comment]
OK,

I have the demo

![image](https://cloud.githubusercontent.com/assets/10757813/23203687/ea05c10c-f8e3-11e6-978e-11a6a282e2eb.png)

and...

> and I was talking about cell A2 - as you can see, it's the same width as A1 before the merge.  Column 'A' should have the width equal to A2, instead of A1 

this is right, I also get the same result which is intended. So I guess here everything's fine.

I have tried to make all the steps from your first description.

1) type in a long string in cell A1, merge it with B1 (empty).

![example1](https://cloud.githubusercontent.com/assets/10757813/23203830/835ad180-f8e4-11e6-8d59-52d436b2fdfc.gif)

2) type in a short string in cell A2 and a long string in B2

![example2](https://cloud.githubusercontent.com/assets/10757813/23203875/a2924394-f8e4-11e6-88b6-23262e8fb8d1.gif)


3) set autoColumnSize to true.

![example3](https://cloud.githubusercontent.com/assets/10757813/23203889/b5338fd0-f8e4-11e6-9d49-8b7613c12ba2.gif)

4) notice that column A becomes as wide as A1 and column B gets as wide as B2.

![image](https://cloud.githubusercontent.com/assets/10757813/23203916/d72f4778-f8e4-11e6-88e8-d9fbf09f2d8c.png)

In my example the `A` column is as wide as `A2` cell and `B` column as `B2` cells. Can you share an image or a video (and you OS/Broswer/Handsontable version) where the column `A` is as wide as cell `A1`?

**Comment by AfflatusX** [comment]
Ah, okay, please ignore the steps (it was more complicated than what is needed to repro the problem)

So looking at the demo (which you mentioned it's intended), isn't it weird that A2 is the same size as A1? I was more expecting something like 
![image](https://cloud.githubusercontent.com/assets/2074990/23216508/3298475a-f8e4-11e6-9686-647a206e3958.png)

this is the behavior in Excel - you merge A1 and B1, then when you auto resize column A, it respects A2's size instead of A1.

**Comment by AMBudnik** [comment]
yes, it does @AfflatusX 
you just want the cells to be more equal in size. I thought that adding `stretchH: 'all'` will helps but is doesn't. I'll mark this issue as a change to `mergeCells` plugin. Thanks for sharing @AfflatusX

**Comment by kosiakk** [comment]
The problem was already reported as #2667 in year 2015 :-/
I think, `calculateColumnsWidth` can be updated to simply ignore cells with `colSpan` (exclude them from samples).
A related problem exists for automatically calculated row height, if `rowSpan` is specified.

**Comment by AMBudnik** [comment]
Related subject https://github.com/handsontable/handsontable/issues/3545

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **MergeCells grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
This issue is no longer replicable using v14.0.0. Update demo https://jsfiddle.net/fe91wefu/1/

**Result**
<img width="180" alt="Zrzut ekranu 2023-12-1 o 15 09 07" src="https://github.com/handsontable/handsontable/assets/10757813/b2859313-f81c-4c2a-80a2-8b551a19905f">

CC @AfflatusX @kosiakk
