### ISSUE TITLE
Cell on double click event

### ISSUE THREAD

**Issue by sebastiendecraene** [handsontable/handsontable#4087]
Is there any possible way to execute a method when you double click on a cell?

**Comment by AMBudnik** [comment]
Hi @sebastiendecraene you could track [afterOnCellMouseDown ](http://docs.handsontable.com/0.31.0/Hooks.html#event:afterOnCellMouseDown) event. Write down the last clicked element and check the time between clicks.
We do not provide any Handsontable double click event.

**Comment by mewalig** [comment]
afterOnCellMouseDown: function(event, coords, td) {
      var now = new Date().getTime();
       // check if dbl-clicked within 1/5th of a second. change 200 (milliseconds) to other value if you want
      if(!(td.lastClick && now - td.lastClick < 200)) {
        td.lastClick = now;
        return; // no double-click detected
      }

      // double-click code goes here
      console.log('double clicked');
    }
