### ISSUE TITLE
Table doesn't rerender while scrolling with arrows.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4089]
### Description

Table doesn't rerender while scrolling with arrows. It appears again when we use scroll.

### Steps to reproduce

1. Use scroll to get to the right most column
2. use left arrow <kbd><</kbd> to get to the first column

While scrolling you can see that the table is gone.

![example](https://cloud.githubusercontent.com/assets/10757813/23154857/24ef7972-f810-11e6-92d3-faa0b749cf2a.gif)

### Demo

http://jsfiddle.net/handsoncode/jrdekcv7/

### Your environment
* Handsontable version: 0.31.0
* Browser Name and version: Chrome 55
* Operating System: Windows 10

### Workaround
We can select any cell and keep focus inside the table with `outsideClickDeselects: false`

Demo: http://jsfiddle.net/handsoncode/mnhou4wf/

`[G #3025]`

**Comment by AMBudnik** [comment]
Works the same using Handsontable v0.35.1 and Chrome 63 on Windows 10.

**Comment by swistach** [comment]
Hi @AMBudnik,
That issue was resolved in v2.0.0: http://jsfiddle.net/hkngwcr9/
