### ISSUE TITLE
Is there any way to get modified row data on a button click?

### ISSUE THREAD

**Issue by prasatharumugam** [handsontable/handsontable#4094]
### Description
I am populating a handsontable spreadsheet. I need  a functionality where i could send all the modified rows to my api. Is there a way to get all modified rows on a button click?

### Your environment
* Handsontable version: 0.25.0
* Browser Name and version: Chrome
* Operating System:Windows 7

**Comment by AMBudnik** [comment]
Hi @prasatharumugam 

You can track what beforeChange/afterChange callbacks are returning. In this example: http://jsfiddle.net/handsoncode/6jhchwer/ you have some useful information about changes made in a cell. You can store this changes in an array and then send/read them on a button click.
You can also pass the new table using getData() method like here http://jsfiddle.net/handsoncode/xjhgs6qh/ and compare it with the source table.
