### ISSUE TITLE
"afterSelection" is not called if changes to columns/rows through "updateSettings" may change selection "semantically"

### ISSUE THREAD

**Issue by pbadenski** [handsontable/handsontable#4095]
### Description
If a cell is selected and columns are adjusted through updateSettings "afterSelection" hook is not fired. (same behaviour for rows)

### Steps to reproduce

1. Run http://jsfiddle.net/y80vy39g/
2. Notice that when "selectCell" is called programmatically both "afterSelection" and "afterSelection" is fired.
3. After "updateSettings" is called contents of the table change - neither of the "afterSelection" hooks get called.

I can see the rationale of not having it called (the numbers behind selection position do not change). However, conceptually a different cell is selected now. To make it more tangible: I have code that displays a panel that operates contextually based on what is selected. After I change "columns" from a conceptual perspective a different column/row is selected, but I'm not being informed of that. Would it make sense to call "afterSelection" in this situation? Or possibly add another method of being informed different contents are selected even though selection "numbers" remain the same.

### Demo
 http://jsfiddle.net/y80vy39g/

### Your environment
* Handsontable version: 0.31.0
* Browser Name and version:  56.0.2924.87 (64-bit)
* Operating System: MacOS 10.12.3

**Comment by AMBudnik** [comment]
Hi @pbadenski 

Thank you for sharing your opinion.

The selection hooks are called only when a physical selection occurred. In this case the selection is still on a single cell `(0, 1)`. 

To track situation with data changes there are [beforeChange ](https://docs.handsontable.com/pro/1.10.0/Hooks.html#event:beforeChange) and [afterChange](https://docs.handsontable.com/pro/1.10.0/Hooks.html#event:afterChange).

**Comment by pbadenski** [comment]
That could work... will "afterChange" also be fired when columns settings are changed?

**Comment by AMBudnik** [comment]
You are right, the afterChange should be triggered in this action. 
The callback that it triggered for this action is` afterRenderer` http://jsfiddle.net/handsoncode/x10keta7/ 
You can see that it's called 3 times (2 times while initialization + 1 for updateSettings).
