### ISSUE TITLE
horizontal scroll render problem on mobile

### ISSUE THREAD

**Issue by chauvetxiao** [handsontable/handsontable#4096]
hello:
        I get a problem, When I use handsontable on mobile phones,such as iPhone 6 plus. I have set renderAllRows option to true , but when I make a horizontal scroll, the colums after F colum won't render any more. Although I kown handsontable is not friendly to mobile platform, but is there any way to solve this?
![image](https://cloud.githubusercontent.com/assets/1027789/23339982/9dbe3fb2-fc68-11e6-8ece-8f06974efb5b.png)

**Comment by AMBudnik** [comment]
Hi @chauvetxiao 
You can try [viewportColumnRenderingOffset ](https://docs.handsontable.com/pro/1.10.0/Options.html#viewportColumnRenderingOffset) option. If you set it to the number of columns in your data set all column should be visible.

**Comment by chauvetxiao** [comment]
Thanks, I had trid this option before but it does't work,after all I had trid modify the method onTableScroll in overlay.js to inogre the mobile ua check. Although it's not a good way to modify the source code, But I have no another way.  
And there is  a new problem  I want to provent the touchmove event when table had scroll to minimum left position,like this
![image](https://cloud.githubusercontent.com/assets/1027789/23360233/3ccda31a-fd25-11e6-870e-29a877d46322.png)

**Comment by AMBudnik** [comment]
Can you share a demo where I'd be able to replicate it? I was testing our example https://handsontable.com/examples.html on iPhone 6 and I do not get the headers like this.

**Comment by chauvetxiao** [comment]
[http://jsfiddle.net/7sjne0sm/#&togetherjs=TyNuzdCHDQ
](http://jsfiddle.net/7sjne0sm/#&togetherjs=TyNuzdCHDQ
)
I trid this example,if you remove the width option and run in mobile phone,the left side row headers would fixed,then if  you scroll right,it would get the headers like that.

**Comment by AMBudnik** [comment]
Hi @chauvetxiao 

I think that you're getting the same effect as Sune in his last comment at https://github.com/handsontable/handsontable/issues/3
Am I right?

**Comment by AMBudnik** [comment]
I assume that if there is no reply for the issue and it seems to be the same as #3 I can close it now.
