### ISSUE TITLE
Mark current deselected row

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#4097]
Need help on how to mark current deselected row as I am focusing on other extended hot on the same page. I don't want to loose focus on my main tablet's current row.

**Comment by AMBudnik** [comment]
Hi @douxlagithub 

you can add the `outsideClickDeselects: false` to your table settings. [
Docs](https://docs.handsontable.com/pro/1.10.0/Options.html#outsideClickDeselects)

**Comment by douxlagithub** [comment]
Awesome. 5 stars for Fast Response.
