### ISSUE TITLE
We cannot scroll vertically and horizontally at the same time on Mac

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4098]
### Description

As in the title we cannot scroll vertically and horizontally at the same time on Mac. It works for Windows but doesn't work for OSX.

### Steps to reproduce

1. Go to the demo and try to scroll the table vertically and horizontally at the same time

### Demo

http://jsfiddle.net/handsoncode/qgL6tycr/

### Your environment
* Handsontable version: 0.31.0
* Browser Name and version: Chrome 56
* Operating System: OSX

**Comment by swistach** [comment]
We fixed it in v2 🎉
