### ISSUE TITLE
getting row index of  newly added row

### ISSUE THREAD

**Issue by deekshitha-indegene** [handsontable/handsontable#4099]
### Description
after i add a new row using the below code which will add a row after the last row
 $("#ListData").handsontable('getInstance').alter('insert_row');
i need to get the particular row index

**Comment by AMBudnik** [comment]
Hi @deekshitha-indegene 

We have a callback that returns index, amount and source for adding rows. It's `afterCreateRow`, here is the documentation for this callback: https://docs.handsontable.com/pro/1.10.0/Hooks.html#event:afterCreateRow
