### ISSUE TITLE
Handsontable triggers alot of change-detection runs in Angular2

### ISSUE THREAD

**Issue by Sune1337** [handsontable/handsontable#4100]
### Description
When i'm using handsontable.addHook("modifyRow") something happens in Handsontable that does a lot of calls to getAnimationFrame().

When getAnimationFrame is invoked, Angular2 does a change-detection run (by means of ZoneJS callbacks).

This can cause serious performance-issues in an Angular2 app since we wanna keep change-detection runs to a minimum; or at least not run them when there is no need.

In my case i was experiencing an issue which caused the browser to eat 100% CPU.

The solution to this problem for me was to only touch handsontable inside a ngZone.runOutsideAngular() function; which causes Angular2 to ignore whatever happens in that function.

I'm not really sure where i'm going with this:) I realize this is not a bug in Handsontable; it works as it works.

Since i'm using multiple Handsontables in a project there is n*FPS functions calls constantly in the browser and it just does not seem efficient.

Are there any general recommendation for using Handsontable in an Angular2 app?
I'm specifically looking for a way to guarantee that Handsontable does not call any functions that would cause ZoneJS to trigger a callback to Angular2.

### Steps to reproduce
Use something in Handsontable that in turn uses getAnimationFrame internally from an Angular2 app.

**Comment by AMBudnik** [comment]
Hi @Sune1337 

Thank you for sharing but currently Handsontable does not support Angular 2. However we are planning to create a wrapper for it in Q1 2017. Roadmap: https://trello.com/c/k0jNZPHv/25-new-wrapper-angular-2

**Comment by Sune1337** [comment]
maybe something to keep in mind then when implementing it :)

thanks

**Comment by Sune1337** [comment]
ps; i'm using the 'npm install handsontable' version inside Angular2 app, and it seems to be working allright.

**Comment by AMBudnik** [comment]
Sure, I think that we should check if this will happen for the wrapper as well. Hopefully it won't :)

**Comment by swistach** [comment]
Hi @Sune1337, thanks for your advice.
The [`angular-handsontable`](https://github.com/handsontable/angular-handsontable) will be running inside ngZone.runOutsideAngular().

**Comment by salcio** [comment]
I seem to have this problem when `data` property on `hot-table `component is reassigned. 

I've created [jsFiddle](http://jsfiddle.net/salcio/pj28uc4y/) that show the behavior. 

Steps: 

- click 'clickMe' button. It will initialize the table with data. 
- monitor console output. When you move the mouse nothing new should be reported in console. 
- click 'clickMe' button again. That will reset `dataset` property which is bound to `data` property on the component. 
- monitor console output. As you move mouse new messages will appear - reported by ngDoCheck method.
