### ISSUE TITLE
Scrolling on a smartphone does not work

### ISSUE THREAD

**Issue by Sune1337** [handsontable/handsontable#4103]
### Description
* Headers sometimes are stuck and does not scroll
* Headers sometimes scroll but does not match the cells
* Headers sometimes disappear and reappear when scrolling is done
* Cells that are scrolled into view are invisible

### Steps to reproduce
Scroll on a smartphone.
In the demo below i'm using "Device toolbar" in Chrome dev-tools (shift+ctrl+m when dev-tools are open), but i get the same behavior if i'm opening the demo-url on my smartphone.

I've also tried various examples out there and they all have issues when scrolling.
For example [A Complete Guide to Changing Size of Handsontable](https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable)

### Demo
[jsbin demo](https://jsbin.com/funagukure/2)
[screencast](https://vid.me/3Ixe)

### Your environment
* Handsontable version: 0.31.0
* Browser Name and version: Chrome 56.0.2924.87 / Firefox newest according to store
* Operating System: Android 5.1.1

**Comment by AMBudnik** [comment]
Hi @Sune1337 

Handsontable is not fully mobile-friendly yet as written in the docs

> It is not mobile-friendly (yet)
> Only the basic functionality works with mobile devices, which means you should be able to display, edit and scroll the grid. We can't guarantee that all the plugins will work as we don't test Handsontable in mobile browsers. 
> _at [known limitations](https://docs.handsontable.com/pro/1.10.0/tutorial-known-limitations.html)

To make scrolling better for mobile devices you would need to add the viewport rendering options: [viewportColumnRenderingOffset ](https://docs.handsontable.com/pro/1.10.0/Options.html#viewportColumnRenderingOffset) and [viewportRowRenderingOffset](https://docs.handsontable.com/pro/1.10.0/Options.html#viewportRowRenderingOffset). 

By setting these options to maximum number of columns and rows in your table you allow your user to get fully rendered table. This slows the performance but displays all data.

**Comment by Sune1337** [comment]
Somehow I've missed that statment.
I'll test the options you suggested.
I don't display a lot of data and hopefully this is good enough for me.

Thanks for your suggestions!

**Comment by Sune1337** [comment]
Your suggestion worked; i now see all the cells when i scroll.
There is still an issue with scrolling and the headers; do you want me to register an issue for that or just leave it at that Handsontable does not fully support mobile devices?

**Comment by AMBudnik** [comment]
Great. Glad it works as desired.

Can you please leave a comment at the main mobile ticket here https://github.com/handsontable/handsontable/issues/3?

It is closed cause it's more a feature than a bug but will be opened when we'll start to work on the mobile version.

**Comment by Sune1337** [comment]
I will do that.
