### ISSUE TITLE
Can't count custom rendered cell data

### ISSUE THREAD

**Issue by douxlagithub** [handsontable/handsontable#4104]
I want to count data on custom rendered cell but failed to get the data array through hot.getDataAtCol(). Please help.
![failed_get_data](https://cloud.githubusercontent.com/assets/4103210/23450229/0942f150-fe95-11e6-96e7-b424a5c2c374.png)

**Comment by AMBudnik** [comment]
Can you @douxlagithub share a Fiddle where I'll be able to replicate it?

**Comment by douxlagithub** [comment]
Here is the fiddle. http://jsfiddle.net/Lp4qn55v/563/

**Comment by AMBudnik** [comment]
hi @douxlagithub 

`d1` variable returns `[", ", ", "]` (array of empty cells). It is correct as you do not pass the values to cells, you just force them to render some values. To use the `getDataAtCol` method you'd need to pass data into cells.

**Comment by douxlagithub** [comment]
I think values are there. I mean the column is filled with data calculated by renderer. Or is there any other way to get the data array of such condition. Sorry, I m new to HOT.

**Comment by AMBudnik** [comment]
Render is only responsible for showing something but it does not save data into the dataset. That is why it would be better to just pass an array or arrays/objects and skip the renderer. 

Usually custom renderer are used to display data in a way that types of cells or formats aren't able to achieve, for example to add an image inside a cell. In your case I would just use the type 'numeric' with desired format if you're loading data with decimal places.

**Comment by douxlagithub** [comment]
O.. I see. Thanks a lot.

**Comment by AMBudnik** [comment]
You're welcome.
