### ISSUE TITLE
Handsontable doesn't render correclty in Bootstrap Tabs

### ISSUE THREAD

**Issue by KirillRyzhkov** [handsontable/handsontable#4105]
Handsontable works correctly only on the first tabs with strechH: "all", but if the table is hidden under second tab stretchH not working. Here is a jsfiddle example. 
Only if you double click cell or resize the column the table becomes normal.

http://jsfiddle.net/3bt289j1/

* Handsontable version: 1.10.0
* Browser Name and version: Chrome
* Operating System: Debian

**Comment by AMBudnik** [comment]
Hi @KirillRyzhkov 

Can you guide me on how to replicate the issue?

What I'm doing is resizing the window then Tab 1 is focused and then choose the Handsontable tab and I get the table stretched. I was trying it on Windows 10 on the same browser.

**Comment by KirillRyzhkov** [comment]
Hi @AMBudnik.

Check this demo http://jsfiddle.net/3bt289j1/ . When you click on 2nd tab the table is stretched outside of the tab container. If you resize the table or double click the cell it renders correctly.

**Comment by AMBudnik** [comment]
Hi @KirillRyzhkov 

sorry for a delay. Have you tried to add a fixed width value? Here's a demo http://jsfiddle.net/handsoncode/o4ftsmza/

**Comment by AMBudnik** [comment]
I assume that my last demo fixed the issue.
If I'm wrong please leave your comment.

**Comment by KirillRyzhkov** [comment]
Hi @AMBudnik.

No, fixed width doesn't fix this issue. I need to have stretchH: "all",. When you click on 2nd tab where table is. Table is stretched outside of the tab container. If you double click on any cell the table becomes fixed width. Actually, I had to use jQuery popup and panels instead bootstrap tabs. Inside jQuery popup table is displayed more or less correctly.

**Comment by AMBudnik** [comment]
Thank you for your comment.

It looks like the `stretchH` option counts the area for table from the full page width. I will mark it as a bug.

**Comment by ericcch** [comment]
@AMBudnik try re-rendering the table on shown.bs.tab: http://jsfiddle.net/o4ftsmza/1/

**Comment by AMBudnik** [comment]
Thanks for sharing @ericcch it actually does the job!

**Comment by Zenoware** [comment]
@ericcch that does work but a bit hacky.  Regardless, I am fine with it, but the headers now do not align with the cells.
![badalignment](https://user-images.githubusercontent.com/7259610/28352747-cfef9e7a-6c1d-11e7-9ff7-05ea591c9bdb.jpg)

**Comment by AMBudnik** [comment]
Hi @Zenoware maybe the `autoColumnSize: true` will help

**Comment by Zenoware** [comment]
@AMBudnik the autoColumnSize: true did not seem to fix the problem.  Looks the exact same until I edit a cell.  Then it renders correctly.

**Comment by matejsvajger** [comment]
I got around this issue with MutationObserver, by listening on the tab navigation class attribute, when it receives `active` class, and on the first tab show, I init the HOT. Something like this:

```
let observer = new MutationObserver((mutations) => {

  mutations.forEach(mutation => {
    if (this.shouldInit(mutation)) {
      this.hot = this.createHot();
      this.initalized = true;
      observer.disconnect();
    }
  });

});

observer.observe(
  document.querySelector('*[data-step="2"]'),
  { attributes:true }
);
```

and shouldInit() function:
```
function shouldInit ( mutation ) {
  return (
    mutation.attributeName == 'class' &&
    mutation.target.classList.contains('active') && 
    !this.initalized
  );
}
```

**Comment by AMBudnik** [comment]
For everyone interested in the subject please check https://github.com/handsontable/handsontable/issues/2779
