### ISSUE TITLE
Cut the content of the cell (checkbox)

### ISSUE THREAD

**Issue by dtslvr** [handsontable/handsontable#4106]
### Description
Cut the cell with type checkbox leads to #bad-value#.

### Steps to reproduce
1. Select cell with the checkbox
2. Press cmd + x (or CTRL + x)
3. The cell content is #bad-value# (without the checkbox)

### Demo
https://docs.handsontable.com/0.31.0/demo-checkbox.html

### My environment
* Handsontable version: 0.31.0
* Browser Name and version: Google Chrome 56.0.2924.87 (64-bit)
* Operating System: Mac OSX 10.11.6

**Comment by AMBudnik** [comment]
Thanks for sharing @dtslvr 

I got the same result

**Comment by dtslvr** [comment]
Thanks, @AMBudnik.

There is a releated issue:
1. Select row on the number (with rowHeaders)
2. Press BACKSPACE (or DELETE)
3. The cell content of type checkbox is #bad-value#

**Comment by AMBudnik** [comment]
Thanks for sharing @dtslvr 

![val](https://cloud.githubusercontent.com/assets/10757813/24035554/52421cb0-0af6-11e7-9aa6-e210a285f035.gif)

**Comment by superpig** [comment]
same problem +1

**Comment by BeneCollyridam** [comment]
This is a big problem for us so +1

**Comment by AMBudnik** [comment]
Hey @dtslvr 

I'm happy to ping you up on that subject. The fix is available from v `7.1.1.`.

@superpig @BeneCollyridam
