### ISSUE TITLE
While scrolling empty space occur

### ISSUE THREAD

**Issue by logeshkumars** [handsontable/handsontable#4107]
Hi Team,

We are facing issue in scroll data, while empty space has been occur rendering the data, scroll to top means header also getting UI glitch.
I have attached the sample html file, Please check it.

Above issue occur in MacBook Pro (Retina, 15-inch, Mid 2015), Google Chrome - Version 56.0.2924.87 (64-bit)

[Handsontable.zip](https://github.com/handsontable/handsontable/files/815852/Handsontable.zip)

![Handson issue](https://cloud.githubusercontent.com/assets/4850738/23692035/43e4759c-03f2-11e7-9429-de78e4c9bb1e.gif)

Thanks
Logesh

**Comment by rayokao** [comment]
I have noticed the same. I think you could try to fix this using the configuration options: https://docs.handsontable.com/pro/1.0.0/demo-scrolling.html

**Comment by AMBudnik** [comment]
Hi @rayokao 

do you get the same issues with the newest version?

**Comment by rayokao** [comment]
@AMBudnik 

Good point! I remembered seeing this but it doesn't seem to be happening in the newest version anymore.

**Comment by AMBudnik** [comment]
Thank you for your investigation @rayokao 
I think that the issue you're getting now is the same as described here https://github.com/handsontable/handsontable/issues/3590
Am I right?

**Comment by logeshkumars** [comment]
@AMBudnik 

I am using latest Handsontable Pro Version 1.10.0, but still issue there, pls check the same.

![handsontable-gif](https://cloud.githubusercontent.com/assets/4850738/23854330/01610482-0817-11e7-86b1-df892a60645a.gif)

Thanks,
Logesh

**Comment by rayokao** [comment]
@AMBudnik 

Yes.

**Comment by AMBudnik** [comment]
Unfortunately, I am not able to get the same result. Can you share an information about the loading time for the table? I have tried the same demo/browser/system but it doesn't work as shown in the video.

**Comment by rayokao** [comment]
@AMBudnik 

The flickering effect happens mostly in Internet Explorer and heavy tables. First scroll down and then use the mouse wheel to scroll up. You should also see the headers being duplicated.

http://jsfiddle.net/hc4zb1qL/

**Comment by AMBudnik** [comment]
Ohh the IE? Yup, we have already been informed by this issue at https://github.com/handsontable/handsontable/issues/2350

**Comment by AMBudnik** [comment]
OK, as this issues strongly relates to #2350  guess we can close it and check the updates after #2350 is fixed.
