### ISSUE TITLE
How can I override hotkeys for handsontable?

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4108]
Hi,

Is there any way of overriding predefined hotkeys? I would like to use Excel hotkeys for navigation and didn't find any option of doing this.

Thanks

**Comment by AMBudnik** [comment]
Hi @andrewQwer 

you can use [beforeKeyDown](https://docs.handsontable.com/pro/1.10.1/Hooks.html#event:beforeKeyDown) and pass `event.stopImmediatePropagation()` to stop the default behavior.

And here's an example how to load your custom keycode combination http://jsfiddle.net/handsoncode/k39rmbgt/ in this case it's <kbd>CTRL</kbd> and <kbd>B</kbd> that saves a file.

**Comment by andrewQwer** [comment]
Hi @AMBudnik,
Am I right saying that I have to stop propogation for all predefined hotkeys and then check whether desired hotkey is pressed by user and call .... what? Let say I want to replace `Shift + End` hotkey with `Ctrl + End`. I can stop propogation for `Shift + End` combination but I don't know what methods/plugins I should use to call the same functionality on `Ctrl + End` :( And the same for other hotkeys.  Where can I see what code is executed on current hotkeys so I can reuse the same for my custom hotkeys?

**Comment by AMBudnik** [comment]
Firstly you need to block the default action so you need to hold the previously pressed key `shift` and check if another one is `End`, you can do it via `afterDocumentKeyDown`

In your case it will be something like this

```
  var lastKey;
  hot.updateSettings({
    afterDocumentKeyDown: function(e) {
      if (lastKey === 'Shift' && e.key === 'End') {
        //this code will be executed for Shift + End
      } else if(lastKey === 'Control' && e.key === 'End'){
      	//this code will be executed for Control + End
      }
      lastKey = e.key;
    }
  });
```

where `hot` stands for the instance of Handsontable.

This code is able to overwrite both, CTRL + END and SHIFT + END, but you can just block the default action for SHIFT + END via the line mentioned before

```
 var lastKey;
  hot.updateSettings({
    afterDocumentKeyDown: function(e) {
      if (lastKey === 'Shift' && e.key === 'End') {
        	e.stopImmediatePropagation();
      } else if(lastKey === 'Control' && e.key === 'End'){
      	//this code will be executed for Control + End
      }
      lastKey = e.key;
    }
  });
```

I am not familiar with this shortcut but you can do whatever you want.

Here you can check what keyboard shortcuts are used in Handsontable: https://docs.handsontable.com/tutorial-keyboard-navigation.html

Additionally there are only shortcuts used by browsers.

**Comment by andrewQwer** [comment]
Hi @AMBudnik,

The problem is that I don't know what to call in this line: `//this code will be executed for Control + End`
I don't know what methods or plugins handsontable executes  when `Shift+End` is pressed so I have no idea what plugins/methods I should call to do the same  when `Ctrl+End` is pressed. In general I am looking for a way to do something like this:
```
 afterDocumentKeyDown: function(e) {
      if(lastKey === 'Control' && e.key === 'End'){
      	call_the_same_method_that_is_called_for_shift_end(); //
      }
      lastKey = e.key;
    }
```
`Shift+End` and `Ctrl+End` are just examples, I would like to override another combinations as well, but I don't know what default handlers does.
Does it help?

**Comment by AMBudnik** [comment]
Hi @andrewQwer 

According to https://docs.handsontable.com/0.31.1/tutorial-keyboard-navigation.html

> Shift + End – select all cells in the row to the right including the current cell

you can find it by the `case KEY_CODES.END` in the source code.

**Comment by andrewQwer** [comment]
Ok, got it. So the only way to know what happens on hotkey clicked is to find this combination in source code, right?

**Comment by AMBudnik** [comment]
Besides the above tutorial, yes - the best way is to look for them in the source code.

**Comment by andrewQwer** [comment]
Thanks for help, @AMBudnik!

**Comment by AMBudnik** [comment]
You're welcome. I assume that we can close this issue.
