### ISSUE TITLE
Non-editable cells are also allowing me to paste content.

### ISSUE THREAD

**Issue by syamdanda** [handsontable/handsontable#4109]
### Description
I have made some cells as non editable, this makes those cells not accepting any content by manually writing. but if I copy pasted some data it is allowing.

### Demo
<script>
document.addEventListener("DOMContentLoaded", function() {

  function getCarData() {
    return [
      {car: 'Nissan', year: 2012, chassis: 'black', bumper: 'black'},
      {car: 'Nissan', year: 2013, chassis: 'blue', bumper: 'blue'},
      {car: 'Chrysler', year: 2014, chassis: 'yellow', bumper: 'black'},
      {car: 'Volvo', year: 2015, chassis: 'white', bumper: 'gray'}
    ];
  }
  
  var
    container2 = document.getElementById('example2'),
    hot2;
  
  hot2 = new Handsontable(container2, {
    data: getCarData(),
    colHeaders: ['Car', 'Year', 'Chassis color', 'Bumper color']
  });
  hot2.updateSettings({
    cells: function (row, col, prop) {
      var cellProperties = {};
  
      if (hot2.getData()[row][prop] === 'Nissan') {
        cellProperties.editor = false;
      } else {
        cellProperties.editor = 'text';
      }
  
      return cellProperties;
    }
  })
  
  function bindDumpButton() {
      if (typeof Handsontable === "undefined") {
        return;
      }
  
      Handsontable.Dom.addEvent(document.body, 'click', function (e) {
  
        var element = e.target || e.srcElement;
  
        if (element.nodeName == "BUTTON" && element.name == 'dump') {
          var name = element.getAttribute('data-dump');
          var instance = element.getAttribute('data-instance');
          var hot = window[instance];
          console.log('data of ' + name, hot.getData());
        }
      });
    }
  bindDumpButton();

});
</script>
<html>
<div id="example2" class="hot handsontable"></div>
</html>

<style>

<script src="https://docs.handsontable.com/0.16.0/scripts/jquery.min.js"></script>
<script src="https://docs.handsontable.com/0.16.0/bower_components/handsontable/dist/handsontable.full.js"></script>
<link type="text/css" rel="stylesheet" href="https://docs.handsontable.co

</style>

**Comment by AMBudnik** [comment]
Hi @syamdanda 

if you want the cells not to accept paste actions you need to mark them as [read-only](https://docs.handsontable.com/pro/1.10.1/demo-read-only.html).

Here's a demo where you can test it: http://jsfiddle.net/handsoncode/vvg0s087/

**Comment by syamdanda** [comment]
Thank You.

**Comment by AMBudnik** [comment]
You're welcome @syamdanda
