### ISSUE TITLE
how to comstom context menu on the bottom of the table

### ISSUE THREAD

**Issue by mudenglong** [handsontable/handsontable#4110]
### Description
https://jsfiddle.net/root_rm/hcfm85kv/

I put "undo" and "alignment:right" button  out of the table ;

when click undo button, It works;

but  "alignment:right"  couldn't work;  I think maybe lost the section info;

If so: what is the best way to do it? 

### Steps to reproduce

1. click a cell in the table
2. click the button "alignment:right"
3. expect the cell will align right, but not work;

### Demo
https://jsfiddle.net/root_rm/hcfm85kv/

### Your environment
* Handsontable version: latest
* Browser Name and version: chrome
* Operating System: windows

**Comment by AMBudnik** [comment]
Hi @mudenglong 

To make the align button to work you need to keep a focus on a cell/cells when a user clicks outside the table. This can be achieved by adding [`outsideClickDeselects`](https://docs.handsontable.com/pro/1.10.0/Options.html#outsideClickDeselects). You should set it to `false`

**Comment by mudenglong** [comment]
Thank you, it works !

**Comment by AMBudnik** [comment]
Great! Thanks for confirmation.
