### ISSUE TITLE
[HELP] How to show dropdown when table have one line and is in scrolled parent

### ISSUE THREAD

**Issue by MuyBien** [handsontable/handsontable#4117]
### Description
I want to show a handsontable in a DIV that have a specific width. 
It happens to have only one line in this table. Here appears my problem.
Because Handsontable calculate the height remaining available to show the dropdown and there is not, I cannot see the dropdown...

What I have yo modify, adapt?

### Steps to reproduce

1. Fix the width of handsontable parent element
2. Fix the overflow-y to `auto` of handsontable parent element
3. Fix the height of handsontable element
4. Open a dropdown

### Demo
The demo seems ridiculous but I fixed little width to show the problem. In fact my width is 1200px...
https://jsfiddle.net/azd0gruv/4/

### Your environment
* Handsontable version: 0.29

**Comment by AMBudnik** [comment]
Hi @MuyBien 

I guess you should take a look at this issue https://github.com/handsontable/handsontable/issues/3435 is describes the same situation.

**Comment by MuyBien** [comment]
Thanks AMBudnik!
I followed this topic but because it was closed and the solution given doesn't resolve the issue on my side, I thought it was another problem. I will post in the other post ;)
