### ISSUE TITLE
AutoColumnResize is disabled when colWidths is specified

### ISSUE THREAD

**Issue by huangqiz** [handsontable/handsontable#4122]
### Description
I just noticed when colWidths is specified and manualColumnResize is true, AutoColumn Resize will not be enabled according to the source code. 
![image](https://cloud.githubusercontent.com/assets/7144380/23778724/fdb42e2e-0576-11e7-9010-4f78d3ad2a49.png)

As a result, when we double click the column header, the column will shrink to column's header's width. 
![image](https://cloud.githubusercontent.com/assets/7144380/23778728/0776b54e-0577-11e7-8596-031d7c2fc9b9.png)

Is it an expected behavior? For myself, I'd like to use the 'auto column size' feature even if colWidths is specified.

### Your environment
* Handsontable version: 1.10.0
* Browser Name and version: Chrome 56.0.2924.87
* Operating System: Windows 10

**Comment by Maxoudela** [comment]
Check solution offered in #7507

**Comment by swistach** [comment]
Hi @huangqiz,
This behaviour is by design. To overwrite this, you can follow a suggestion from this [comment](https://github.com/handsontable/handsontable/issues/7507#issuecomment-773949470).

I close this issue but feel free to join and comment #7507.

**Comment by AMBudnik** [comment]
Referenced issue https://github.com/handsontable/handsontable/issues/7507 has been solved in v8.3.2
