### ISSUE TITLE
maxRowHeight option?

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4123]
Hi,

Does handsontable have any option for setting max row height?
[rowHeights](https://docs.handsontable.com/pro/1.10.1/Options.html#rowHeights) works like min height, but what I want to do is to allow rows to shrink to a certain height and then cut it's content.

Is it possible via options or css?

Thanks,
Andrey

**Comment by AMBudnik** [comment]
Hi @andrewQwer 

Unfortunately it is not available at the moment. 

We have already been reported by this feature request in this post: https://github.com/handsontable/handsontable/issues/2236
