### ISSUE TITLE
Q: How to use mergeCells plugin from code

### ISSUE THREAD

**Issue by twjacobsen** [handsontable/handsontable#4125]
### Description
I would like to be able to merge cells runtime, based on user actions.
From what I can see, I currently only have the option to either provide the list of cells to merge when initializing Handsontable, or by using the context menu (which we have disabled).

Is there, or do you plan to add, an API for the MergeCells plugin, that allows me to pass (topLeftX, topLeftY, bottomRightX, bottomRightY) coords to be merged?

**Comment by AMBudnik** [comment]
[issue reply on the email]
