### ISSUE TITLE
Add afterColumnsResize Events

### ISSUE THREAD

**Issue by apo11on** [handsontable/handsontable#4126]
### Description
If multiple columnheaders are selected and width is resized at once, for each column the before/afterColumnResize event is fired. So selecting e.g. 10 columns and then resizing, i get ten times the event.
I would prefer to have the event behaving e.g. like afterChange. I think the event should only be fired once if multiple columns are selected during resize and deliver: 1. An array of objects with columnIndex and newWidth and 2. Information if isDoubleClick.
 

### Steps to reproduce
1. Create handsontable with manualColumnResize on true
2. add a Hook for beforeColumnResize or afterColumnResize, e.g. writing colIndex, newWitdh in the console
3. Select multiple Columnheaders
4. Click the resize handle of one column  and resize
5. You will see the afterColumnResize or beforeColumnResize event been called as many times as columns are selected

### Demo
http://jsfiddle.net/22b7fstq/
Select multiple columns and resize, look in console

### Your environment
* Handsontable version: 0.31.0 Free edition
* Browser Name and version: IE11
* Operating System: Win10 Professional

**Comment by AMBudnik** [comment]
Thank you for your suggestion @apo11on 

I am not sure if we would like to change the hook behavior but we can add an alternative.

**Comment by apo11on** [comment]
Hello AMBudnik,

i agree - changing the hook might be a bad idea since people are using it already...
Maybe for Information, i would like to have such a hook because i want to save columnwidths once changed in a database with only one call and not for each column a separate call. So if multiple columns are resized and before/afterColumnResize is triggered for each column, i need to figure out if multiple columns where selected and therefore saving to db one time is good enough or if really different single columnresizes took place. I suppose i am not a good programmer to figure out how to do that by my own - therefore the hook;-)

**Comment by AMBudnik** [comment]
Yes, I agree. It sounds like a useful hook.

Thanks for sharing.

**Comment by AMBudnik** [comment]
I am moving this feature request to our [wiki section > feature requests](https://github.com/handsontable/handsontable/wiki/Feature-requests).

Again thanks for sharing :)
