### ISSUE TITLE
Custom editor doesn't follow to cell position.

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [handsontable/handsontable#4128]
### Description

Editor doesn't follow to cell position during scrolling.

### Steps to reproduce

1. Using custom editor on cells. (For example: SelectEditor on docs)
2. Giving a fixed height to table
3. Double click cell for editing. Scroll table while editor shown.

### Demo

http://jsfiddle.net/iboylmz/5hk2bxys/3/

### Your environment
* Handsontable version: 1.10.1
* Browser Name and version: Chrome 56.0.2924.87
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @ibrahimyilmaz7 

isn't this an issue that we have already discussed by emails around 3 weeks ago?

**Comment by AMBudnik** [comment]
I think that we did and as I did not receive any reply I am closing the issue.
