### ISSUE TITLE
afterSelection doesn't differ the header from a first column/row.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4129]
### Description

`afterSelection` should return `-1` values if we click a row or column header.

### Steps to reproduce

1. Click a column or row header. You will get `0` for a first row/column and the same for headers.

### Demo

http://jsfiddle.net/handsoncode/mxw707Lf/

### Your environment
* Handsontable version: 0.31.0
* Browser Name and version: Chrome 56
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
I am moving this feature request to our [wiki section > feature requests](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by JuanjoArmellino** [comment]
Any news on this request ? i think its important to diferentiate this. Im making an update of the page when the user clicks a row, but if the user clicks a header the page gets updates as if the user had clicked row zero. is it possible to fix please ?

thanks in advance

**Comment by AMBudnik** [comment]
Hey @JuanjoArmellino can you share a demo with your implementation (can have fake data and only Handsontable settings) at support@handsontable.com?

**Comment by JuanjoArmellino** [comment]
Hi, thanks for answering. You can see here jsfiddle.net/ueznL7mb . Clicking
I na cell alerts the row number. When you click the header you get zero as
if you had clicked the row zero. I understand it's due to the single cell
selection setting, so clicking the header does not select the whole column.
The problem is that we cannot tell if the user clicked the header or the
cell.

Thanks
Juanjo

**Comment by AMBudnik** [comment]
So if it is more a case of clicking then the selection you will get the indexes of negative values for headers in this hook https://handsontable.com/docs/7.0.0/Hooks.html#event:afterOnCellMouseDown

> For example clicking on the row header of cell (0, 0) results with afterOnCellMouseDown called
> with coordinates {row: 0, col: -1}.

**Comment by AMBudnik** [comment]
Feature added. Here's an updated demo http://jsfiddle.net/handsoncode/duv8gwj1/
