### ISSUE TITLE
Bug when dragging down (Autofill.fill) merged cells

### ISSUE THREAD

**Issue by guireg** [handsontable/handsontable#4130]
### Description
Hi,

I'm working a lot with merged cells and we have an issue with Autofill-in , dragging down, a group of merged cells. When I'm dragging them left, right or up, it's working but when I'm dragging then down, I have this error :

handsontable.full.js:13440 Uncaught TypeError: Cannot read property '0' of undefined
    at getDeltas (handsontable.full.js:13440)
    at Autofill.fillIn (handsontable.full.js:13213)
    at Autofill.onMouseUp (handsontable.full.js:13358)

It's coming from the fact that the wrong direction is executing on getDragDirectionAndRange function.

When I debug-mode this function and see variables value, the direction calculated and pass to getDeltas function is "right" and not "down".

Can you check this ? I put a little demo on jsfiddle : https://jsfiddle.net/dwaaqzc3/

### Demo
https://jsfiddle.net/dwaaqzc3/

### Your environment
* Handsontable version: 0.31.1 - Last version
* Browser Name and version: Chrome 56.0.2924.87 64bit
* Operating System: Mac OS Sierra 10.12.3

**Comment by AMBudnik** [comment]
Thank you for sharing @guireg 

Can it be the same issue as already reported by @floribon at https://github.com/handsontable/handsontable/issues/4035 ?

**Comment by floribon** [comment]
I confirm it is, failing exactly at the same line for the same reason.

**Comment by AMBudnik** [comment]
Thank you for confirmation @floribon 
I will then close this issue as we should keep only one ticket for a single case.

When it comes to merged cells there are many things to fix. Here I highly encourage to leave your vote for [`Refactor of Merged Cells` in our Trello Roadmap for 2017.](https://trello.com/c/q3CPCJeD/103-refactor-of-merged-cells)
