### ISSUE TITLE
Skipping DataMap cache at creation

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4131]
### Description
DataMap will skip cache for 500ms at creation from now. We added part of code which change `skipCache` flag in constructor.

**Note**: It will also fix problems with loading new data by `loadData` when `trimRows` plugin is enabled.

### Steps to reproduce
We can't reproduce functionality on community version of Handsontable.

### Corresponding changes
https://github.com/handsontable/handsontable/tree/feature/skippingDataMapCache

**Comment by swistach** [comment]
Related commit: https://github.com/handsontable/handsontable/commit/ea30ee1621fdc852750f028179c222c2a9a5ffae
