### ISSUE TITLE
beforeChange handler causing the next edit to highlight the wrong cell

### ISSUE THREAD

**Issue by yixunx** [handsontable/handsontable#4133]
### Description
If the beforeChange hook clears the `changes` array during a paste, then after the next edit, the highlight will jump to the cell below the last pasted cell, instead of below the edited cell.

### Steps to reproduce
1. Add a beforeChange handler that clears the `changes` array when `source == "CopyPaste.paste"`. 
2. Copy and paste some cells in the spreadsheet.
3. Edit a cell out of the pasted region, and press enter. The highlight does not move to the cell below the edited cell, but to the cell below the first pasted cell.

### Demo
https://jsfiddle.net/yixunx/y7e3n019/

### Your environment
* Handsontable version: 0.31.1
* Browser Name and version: Chrome 56.0.2924.87
* Operating System: Mac OS X 10.11.6 (El Capitan)

**Comment by yixunx** [comment]
Using `beforeChangeRender` instead of `beforeChange` seems to fix this, but this behavior of `beforeChange` is still unintuitive.

**Comment by yixunx** [comment]
Using `beforeChangeRender` seems to fix this, but the behavior of `beforeChange` is still unintuitive.

**Comment by AMBudnik** [comment]
Thanks for sharing @yixunx 

I got the same result.

**Comment by raiju** [comment]
The repro still works on Handsontable 0.34.0: https://jsfiddle.net/y7e3n019/8/

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0` and it seems to be present since we can block the `beforeChange`

**Comment by AMBudnik** [comment]
It works the same in[ v`5.0.1`.](https://jsfiddle.net/t3nm79qf/)

We should be moved to cell `A3` not `B2`.

![ddddgif](https://user-images.githubusercontent.com/10757813/44716132-c379a100-aab9-11e8-93f4-034b16db640c.gif)

**Comment by AMBudnik** [comment]
This issue is no longer replicable in v8.0.0 https://jsfiddle.net/AMBudnik/hsxze5tj/
Now when we edit A2 we are moved to A3 (as expected)
