### ISSUE TITLE
After Change event server side update ajax call not working properly

### ISSUE THREAD

**Issue by udhayavanan** [handsontable/handsontable#4134]
### Description
  I used server side update on afterchange event. When i am changing continuously more than 1 cell, after first cell ajax call second ajax call not working.
### Your environment
* Handsontable version: 0.31
* Browser Name and version: chrome latest
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Hi @udhayavanan 
Can you share any demo?
Have you also tried to add a slight delay using setTimeout()?

**Comment by AMBudnik** [comment]
I assume that there is no problem left as there is no reply for nearly 3 weeks. However, if you still encounter any problems with the software please share a demo.
