### ISSUE TITLE
`updateSettings` breaks scrolling when updating height and fixedRowsTop.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4135]
### Description
When using the `updateSetings` method to update the `height` and `fixedRowsTop` or `fixedColumnsLeft` property, the table doesn't load the out-of-view columns (with `fixedRowsTop`) or rows (with `fixedColumnsLeft`) when scrolling.

### Steps to reproduce
1. Go to http://jsfiddle.net/js_ziggle/d1paovyv/
2. Scroll horizontally

**Result:** The columns outside of the viewport are not being loaded. (They refresh only when you scroll vertically)

### Your environment
* Handsontable version: 0.31.1
* Browser Name and version: Chrome 56.0.2924.87
* Operating System: OSX El Capitan

**Comment by ibrahimyilmaz7** [comment]
Same on:

Handsontable version: 1.10.1
Browser Name and version: Chrome 57.0.2987.98
Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thanks for checking @ibrahimyilmaz7

**Comment by AMBudnik** [comment]
Works the same in 0.35.0
Updated demo http://jsfiddle.net/ntLyuntk/

**Comment by AMBudnik** [comment]
The issue is no longer replicable in v 5.0.1. Updated demo http://jsfiddle.net/ajpgqork/
@ibrahimyilmaz7 again, thanks for feedback
