### ISSUE TITLE
[0.31.0+] Disabling the `colHeaders` property using `updateSettings` doesn't work.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4136]
### Description
When trying to disable the `colHeaders` property by using the `updateSettings` method, the column headers don't get removed. Instead, we're left with a non-functional, not scrollable header bar at the top of the table, covering the first data row.

### Steps to reproduce
1. Go to http://jsfiddle.net/js_ziggle/ukkk3c1L/
2. Scroll the table to see, that the column headers are broken

### Your environment
* Handsontable version: 0.31.1
* Browser Name and version: Chrome 56.0.2924.87
* Operating System: OSX El Capitan

**Comment by swistach** [comment]
I think header management doesn't work properly since 0.29.0: http://jsfiddle.net/k2gdhdcy/

**Comment by AMBudnik** [comment]
The issue is replicable in v0.35.0 as well

**Comment by AMBudnik** [comment]
v`0.30.1` disabled the headers completely.

from v`0.31.0` headers are buggy
![31](https://user-images.githubusercontent.com/10757813/44714362-6976dc80-aab5-11e8-92e8-07a97aa56fcf.gif)

from [v`2.0.0` ](http://jsfiddle.net/k6cjmp09/) to present (v`5.0.1`) - Headers are partially gone 
![2](https://user-images.githubusercontent.com/10757813/44714668-2d904700-aab6-11e8-999a-85b9e108bbcf.gif)
