### ISSUE TITLE
Currency conversion

### ISSUE THREAD

**Issue by lesterjanpearson** [handsontable/handsontable#4137]
is there a way to convert currency? or should I do it on the backend?
like from USD to EURO/GBP.

**Comment by AMBudnik** [comment]
Hi @lesterjanpearson 

It depends on what you would like to do. Can you provide a scenario?

**Comment by lesterjanpearson** [comment]
for example column1. Price USD. when I type in the amount. it will update the converted to column2 (EUR).

is there some kind of converter within handsontable?

**Comment by AMBudnik** [comment]
We do not have any similar functionality but you just can keep the current euro value in a variable and load it via setDataAtCell into the euro column.

Here's what I mean: http://jsfiddle.net/6pgtvz1d/
