### ISSUE TITLE
Cells get confused when merging already merged cells

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [handsontable/handsontable#4138]
### Description
Cells get confused when merging already merged cells.

### Steps to reproduce
1.Try merging from B1 to C21 on demo.

### Demo
http://jsfiddle.net/iboylmz/g5yknq9s/

### Your environment
* Handsontable version: 1.10.1
* Browser Name and version:  Chrome 57.0.2987.98
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thanks for sharing @ibrahimyilmaz7 

It is definitely not an intended behavior.

![merge-issue](https://cloud.githubusercontent.com/assets/10757813/24002011/defb8e8a-0a5f-11e7-84b8-da6c55e3f4cd.gif)

**Comment by jansiegel** [comment]
Probably related to #1722

**Comment by jansiegel** [comment]
Should work fine in `0.37.0`.

**Comment by AMBudnik** [comment]
Hi @ibrahimyilmaz7 

Can you update the code to version 0.37.0 and let me know if it solves the issue that you've reported?

**Comment by ibrahimyilmaz7** [comment]
Hi @AMBudnik 

[https://jsfiddle.net/iboylmz/g5yknq9s/2/](jsFiddle)

It is working as expected now. Thank you.

**Comment by AMBudnik** [comment]
Happy to hear that @ibrahimyilmaz7 

Thank you for the prompt reply
