### ISSUE TITLE
colWidths() callback doesn't have HOT instance as 'this'

### ISSUE THREAD

**Issue by Rex90** [handsontable/handsontable#4139]
### Description
I am trying to use the colWidths property on the table specified as a function. I set a function but it appears that the callback doesn't get passed the table instance into 'this'. Is this expected?

What I am trying to achieve is round up the calculated column width to nearest 10px? is there any advise on this?

**Comment by ibrahimyilmaz7** [comment]
In my opinion widths are calculated before table instance creation. You can use updateSettings method in table afterInit event. 

```
afterInit: function() {
var tableInstance = this;
 this.updateSettings({
    mergeCells: tableInstance.mergeCells.mergedCellInfoCollection, //updateSettings method have some bugs. (for merged cells bug on updateSettings)
    colWidths: function() {
        //you can access tableInstance
    }
});
}
```

> Ps: Code not tested. Maybe you need rerender table after updating colWidths

**Comment by Rex90** [comment]
I will try this out - will I be able to set the col widths before the table is displayed?

**Comment by AMBudnik** [comment]
Hi @Rex90 
You can set column widths while initialization but the table have to be renderer to get a value to be rounded up. So as @ibrahimyilmaz7 mentioned you would need to use updateSettings.
