### ISSUE TITLE
Totals

### ISSUE THREAD

**Issue by ghost** [handsontable/handsontable#414]
It would be a nice feature to include footer row with totals.

**Comment by 57even** [comment]
+1

**Comment by qetr1ck-op** [comment]
+1

**Comment by toresenneseth** [comment]
Any update on this issue? I would also very much like this feature. I need to fix a row at the bottom, doing custom summaries for each column (not just a sum of all cells in the column). My data set contains values that should not be included when calculating the sum.

Besides that, love the work you guys are doing!

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Feature already added in Handsontable PRO as [Summary calculation](https://docs.handsontable.com/pro/1.10.0/demo-summary-calculations.html) and [Fixed Rows Bottom](https://docs.handsontable.com/pro/1.10.0/Options.html#fixedRowsBottom)
