### ISSUE TITLE
Prevent Autofill to add some rows

### ISSUE THREAD

**Issue by stla** [handsontable/handsontable#4145]
Hello, 

 Is there a way to prevent adding new rows when we "autofill" with the mouse ?

![capture](https://cloud.githubusercontent.com/assets/4466543/24145359/1867635e-0e31-11e7-9676-f4f145ff31f2.PNG)

**Comment by AMBudnik** [comment]
Hi @stla 

if you have fixed number of rows or are able to change it by a variable you can use `maxRows`, like proposed here: https://github.com/handsontable/handsontable/issues/1998

**Comment by stla** [comment]
Looks good, I'll try that soon. Thanks @AMBudnik !

**Comment by AMBudnik** [comment]
You're welcome. Let me know if that solved the issue.

**Comment by stla** [comment]
Yes, perfect. Thanks again.

**Comment by budnix** [comment]
Or if you haven't a fixed number of rows you can prevent adding new rows by setting `autoInsertRow` to `false`. Please refer to [http://docs.handsontable.com/pro/1.10.1/Options.html#fillHandle](http://docs.handsontable.com/pro/1.10.1/Options.html#fillHandle)

**Comment by stla** [comment]
Thank you @budnix 
Good option. But when I set it, some scrollbars appear when I remove one row. Weird.

![capture](https://cloud.githubusercontent.com/assets/4466543/24152063/d9f5792a-0e4a-11e7-81b1-1bab4417d96e.PNG)

**Comment by AMBudnik** [comment]
Can you share the above example via Fiddle @stla ?
I have tried with one of our demos and did not get the scrolls.

**Comment by stla** [comment]
@AMBudnik 
My app is huge, with a lot of custom code. This could be due to my code. But I can try later to reproduce it with a minimal example (it will not be easy).

**Comment by AMBudnik** [comment]
It looks like the styling connected with height (for the Handsontable container or a parent) is causing the issue.

**Comment by stla** [comment]
Quite possible. My app automatically resizes the height and the width when a change occurs. But I have this issue only with this option.
