### ISSUE TITLE
Unexpected paste area size when using beforePaste hook to alter data

### ISSUE THREAD

**Issue by AlexKasaku** [handsontable/handsontable#4147]
### Description
I am trying to use the _beforePaste_ hook to strip out the first row of data before it is pasted in. It just so happens that this is the example used in the docs: http://docs.handsontable.com/0.31.1/Hooks.html#event:beforePaste

However, the behaviour seems to be that if you alter the size of the data before the paste occurs, the destination paste _area_ on the sheet remains the same and the data is then looped over in an attempt to fill this same size. e.g. If you are pasting 4 rows of data and your hook method removes the first, 4 rows will still get pasted in, but the 4th row will be a duplicate of the 1st.

It seems like the data area size needs to be reevaluated after the hook method is called so that the destination area size reflects the manipulated data?

### Steps to reproduce
1. Create a hook method for beforePaste and use it to remove a row of data before pasting occurs.
2. Copy multiple rows of data
3. Paste into the sheet, just selecting a single destination celll rather than an area.
4. The data will be pasted in with the row you removed missing, but the 1st row will be duplicated at the end.

### Demo
https://jsfiddle.net/7w09f9tp/

### Your environment
* Handsontable version: 0.31.1
* Browser Name and version: Chrome 57
* Operating System: Windows

**Comment by AMBudnik** [comment]
I have replicated the situation. Thanks for sharing @AlexKasaku 

![gif2](https://cloud.githubusercontent.com/assets/10757813/24244182/282afcf4-0fbe-11e7-9649-6031727675c7.gif)

updated demo (as Fiddle requires `https` for file src): https://jsfiddle.net/handsoncode/ve38kLLg/

What we **expect**

![image](https://cloud.githubusercontent.com/assets/10757813/24244399/f711abd0-0fbe-11e7-847f-cf613e29ea38.png)

What **we get** (excess copied row, as Alex wrote)

![image](https://cloud.githubusercontent.com/assets/10757813/24244372/d4e15010-0fbe-11e7-87d1-1a3a89f527ae.png)

**Comment by shendriks** [comment]
A similar problem occurs if additional rows or columns are added to the data array in the `beforePaste` handler. The data area isn't updated accordingly and so any excess data is stripped when being pasted.

**Comment by elubin** [comment]
+1

**Comment by swistach** [comment]
This issue will be fixed in #4234

**Comment by swistach** [comment]
Hi @AlexKasaku,`beforePaste` should work properly in v0.33.0/v1.12.0.
Could you check it out?
Demo (v1.12.0): http://jsfiddle.net/0he1u64m/

**Comment by AMBudnik** [comment]
I am closing this issue as there's no reply since last week, but @AlexKasaku feel free to leave your feedback.

**Comment by AlexKasaku** [comment]
Looks great to me, have tested using the same sample as before but with the updated scripts and it's working fine - https://jsfiddle.net/xf4fcyos/

Thanks for fixing!

**Comment by AMBudnik** [comment]
Great, thanks for an update @AlexKasaku
