### ISSUE TITLE
Slowness on instantiation - prevent re-instnatiation

### ISSUE THREAD

**Issue by Rex90** [handsontable/handsontable#4148]
### Description
I have a angular ui-router app with various tabs. When switching between tabs I create 5-10 instances of handsontable like this:

`xx = new Handsontable($item[0], options);`

Each one of these takes about 50-150ms depending on the size of the table. This means that switching between tabs can take >1s very often.

I would like to try and improve on that. I keep track of my HOT instances in an angular service. I am trying to see if I can avoid calling `new Handsontable() `by retrieving the instance (previously created) when the controller is loading. However, how do i then go about instering/rendering the table into the DOM without calling `new Handsontable()`. Is there a core method I could use to attach the table instance to dom element?

```
TimerService.start("SETTINGINSTANCE", groupName)
var xx = HotRegister.getInstance(groupName)
if(xx === undefined){
	xx = new Handsontable($item[0], options);
}
else{
        xx.render();
}
TimerService.stop("SETTINGINSTANCE")
```

> timer-service.js:16 [SETTINGINSTANCE] took 145.4150 milliseconds. 
> timer-service.js:16 [SETTINGINSTANCE] took 75.3900 milliseconds.
> timer-service.js:16 [SETTINGINSTANCE] took 84.9900 milliseconds.
> timer-service.js:16 [SETTINGINSTANCE] took 96.6700 milliseconds.
> timer-service.js:16 [SETTINGINSTANCE] took 53.8250 milliseconds. 
> timer-service.js:16 [SETTINGINSTANCE] took 67.8200 milliseconds.
> timer-service.js:16 [SETTINGINSTANCE] took 75.5000 milliseconds. 
> timer-service.js:16 [SETTINGINSTANCE] took 63.4000 milliseconds. 
> timer-service.js:16 [SETTINGINSTANCE] took 80.5600 milliseconds.
> timer-service.js:16 [SETTINGINSTANCE] took 63.4200 milliseconds. 
> timer-service.js:16 [SETTINGINSTANCE] took 96.6050 milliseconds. 
> timer-service.js:16 [SETTINGINSTANCE] took 96.1700 milliseconds.
> timer-service.js:16 [SETTINGINSTANCE] took 73.7650 milliseconds.
> timer-service.js:16 [SETTINGINSTANCE] took 95.0700 milliseconds. 
> 
> 
>

**Comment by AMBudnik** [comment]
Hi @Rex90 

I have asked our head developer and he told be that as far as he knows there's no core method you can choose but if I'll get any news I'll be back to share.

**Comment by Rex90** [comment]
Hi @AMBudnik thank you for following up; can you please elaborate on the edit as I am not entirely sure how to proceed.

Thanks
Armen

**Comment by AMBudnik** [comment]
Sorry for a delay @Rex90 I guess you might have figured it out already but I will post the description anyway. His tip was about creating the instances for DIV with a `display: none` settings added. It will make you skip the rendering which takes most of the time right now.

**Comment by mx2323** [comment]
is this still the best way to do this? 

i also notice that it can take 1 second to load data. makes it tough to toggle going back and froth when my components are mounting and unmounting (im using react wrappers) 

![image](https://user-images.githubusercontent.com/528124/78459945-1219f480-767a-11ea-92ff-a4a86c8a100b.png)

**Comment by AMBudnik** [comment]
Hey @mx2323 that's a case from 2017. I would suggest creating a demo for tests. You can fork this demo https://codesandbox.io/s/fetch-data-1bk6y if that helps.

**Comment by mx2323** [comment]
looks like setting colWidths makes a big difference
