### ISSUE TITLE
Totals row

### ISSUE THREAD

**Issue by ghost** [handsontable/handsontable#415]
It would be a nice feature to include a footer row with totals

**Comment by AMBudnik** [comment]
For everyone looking for this feature, I recommend adding[ summary-calculations](https://docs.handsontable.com/pro/1.18.1/demo-summary-calculations.html) to [fixed bottom rows](https://docs.handsontable.com/pro/1.18.1/demo-fixing-bottom.html) (both features are in Handsontable PRO).
