### ISSUE TITLE
Wrong behavior of before/afterChange for multiple checkbox cells selected

### ISSUE THREAD

**Issue by apo11on** [handsontable/handsontable#4151]
Description
IMHO the callback for before/afterChange have a not consistent behaviour for checkbox cells compared to other celltypes. 
Example: 
If multiple cells are selected and TAB/DELETE/ENTER is pressed for all selected cells the check/uncheck state changes (this is good for fast multi-edit).
Nevertheless, in such a case for each selected cell a separate before/afterChange Event is triggered, giving the changes only for one cell when triggered.
For e.g. paste there is a different behavior, if multiple checkbox-cells are overwritten e.g. by pasting in multiple true  at once, only on afterChange Event is triggered which contains an Array of all changed cells with [row,col,oldVal, newVal].

This in my opinion not conistent behavior is bad because e.g. if you want to save changes in a DB, you need to transfer data for each Change-Event. So e.g for a table with hundreds of rows, if you get one change event containing all changes (like with pasting text in normal cells), just one time communication with a server is necessary. 
But for checkbox-cells, one TAB e.g. when the whole column is selected, will trigger hundreds of change events and for each event i need to communicate with the server the changes (unless there is an easy way to figure out which changes where triggered by just one keypress?)

Steps to reproduce

1. Create simple Handsontable, with one checkbox-column and one text-column and at least two rows, enable paste
2. Add afterChange hook, putting something in the console
3. Copy a range in Excel and paste it in the  text-column
4. As expected: Only one afterChange is triggered Container the changes for each cell that was selected
5. Do the same with the Checkbox column, e.g. paste a range with 'true' values in the checkbox-column
6. As expected: Only one afterChange is triggered containing the changes for each cell that was selected
7. Select all cells in the checkbox-column, press TAB
8. In the console, the afterChange hook is triggered as often as cells are selected, this is different.

Fiddle will follow if needed.

### Your environment
* Handsontable version: 0.31.0
* Browser Name and version: Firefox latest, IE11
* Operating System: Win 10 64bit

**Comment by AMBudnik** [comment]
OK, so what I did is till point 6 here

![image](https://cloud.githubusercontent.com/assets/10757813/24358218/bdbff608-1300-11e7-9679-639129078a2c.png)

but pressing <kbd>TAB</kbd> did not change anything. It just selected the first cell in the column. So I have checked <kbd>ENTER</kbd> and <kbd>SPACE</kbd> but also got only single log, but found other bug.

![gif2](https://cloud.githubusercontent.com/assets/10757813/24358377/382482ec-1301-11e7-89ff-87d16c0cce5f.gif)

Here I suppose to get all checkboxes switching on/off or at least all unchecked but `Citroen..` doesn't switch. 

I'll create a separate issue for this behavior but firstly I would like to know what is the issue you are experiencing. Can you record that as well?

**Comment by AMBudnik** [comment]
Hi again @apo11on 

can you guide me how to replicate the issue you are spotted in the first place?

**Comment by apo11on** [comment]
Hello AMBudnik,

i double checked now with 0.31.2 and obviously i had something wrong in my own code only that i didn't figure it out. I created a pure fiddle with the old version, that worked also correctly. So i am very sorry to bothering you with this because of my own mistake!! Shame on me, Topic can be closed.

**Comment by AMBudnik** [comment]
That's OK - very often it is hard to find the creepy crawly that breaks the code. It is a one step forward that you already know when it is working so I keep my fingers crossed for the fix :)
