### ISSUE TITLE
Nested headers don't update dynamically

### ISSUE THREAD

**Issue by allanelder** [handsontable/handsontable#4152]
Hi

I'm evaluating Handsontable PRO for a project; the project requires that I have 2 features.

The ability to add columns dynamically
The ability to drag / drop columns

### Steps to reproduce

1.Open the codepen
2.Click "Update Cols", the cols don't update with the new column added, but the correct cols are output to the console.

### Demo
http://codepen.io/robroy72/pen/GWGJdy

### Your environment
Handsontable version: 1.10.1
Browser Name and version: Chrome 56.0.2924.87
Operating System: Windows 7

**Comment by AMBudnik** [comment]
The issue seems to be gone. Please check this demo https://codepen.io/anon/pen/NXJagP?editors=1111
I cannot replicate the mentioned behavior but if you do please leave a comment.
