### ISSUE TITLE
Why getDataAtCell() returns old value?

### ISSUE THREAD

**Issue by petrovic-ivan** [handsontable/handsontable#4153]
If I programmatically set value to table cell like this:

`t.setDataAtCell(0, 0, 10);`

and read like this:

`var value= t.getDataAtCell(0, 0);`

Now value will be old cell value, not new value which I inserted programmatically.

Why is that happened? I am guessing that `t.setDataAtCell(0, 0, 10);` will set value asynchronously but do we have some option to pass callback or something?

**Comment by AMBudnik** [comment]
Hi @petrovic-ivan 

Can you guide on how to replicate it? I have a demo here http://jsfiddle.net/handsoncode/khdt18Lo/ suing `setDataAtCell(0,0, 'EXAMPLE')` and then `getDataAtCell(0,0)` but it works without issues

![gif](https://cloud.githubusercontent.com/assets/10757813/24355113/fc97a080-12f4-11e7-9bb6-855f82644708.gif)

I have tried the same scenario without `setTimeout` and et the same result.

**Comment by AMBudnik** [comment]
Hi @petrovic-ivan 

I'm just dropping by to ask you how is the progress with the issue? Personally, I can't replicate the same example but I'm here to help if you still have any issues with implementation.

**Comment by petrovic-ivan** [comment]
Hi @AMBudnik 

Thanks for replying and sorry for delay. I cannot reproduce on your example, it works properly. We are using version 0.30.1 but cannot verify is it related to version. 

I will close this item now and reopen if I can provide forking example with steps.

**Comment by AMBudnik** [comment]
OK, thanks for an update @petrovic-ivan
