### ISSUE TITLE
invalid cell display disappered after removing row.

### ISSUE THREAD

**Issue by scratch-takagi** [handsontable/handsontable#4155]
### Description

on the Demo site(https://handsontable.com/examples.html)
When I removed row, invalid cell display disappeared.

### Steps to reproduce

1. I enabled 'headers', 'sorting' and 'context menu'.
2. I sorted at 'Country' column in ascending order.
3.  I removed top row(of 'Argentinian Peso') using context-menu.

### Your environment
* Handsontable version: 0.31.0
* Browser Name and version: chrome 56.0.2924.87
* Operating System: windows7 pro service pack 1

**Comment by scratch-takagi** [comment]
I have a problem seem to be based on the same reason.
My problem is that invaid cell display doesn't move after removing a row above the row invalid cell is on.

**Comment by scratch-takagi** [comment]
I invesitaged lightly.
When 'alter' method is called with 'action' argument as 'remove_row', at first, 'datamap.removeRow' is called. this seems to be one of reason of this problem. 
The 2nd reason is that visible row index is given to 'priv.cellSettings.splice'. In case of after column sorting, this is wrong because  visible row index is different than physical(on source) index.

**Comment by AMBudnik** [comment]
Hi @scratch-takagi 

Sorry for a delay. I think that it is the same issue as reported here https://github.com/handsontable/handsontable/issues/3188 so I am closing the issue. However if I'm missing something please leave a comment

**Comment by scratch-takagi** [comment]
Thanks. I also think this issue is same as #3188 
I watch there.

**Comment by AMBudnik** [comment]
Thank you for confirmation @scratch-takagi
