### ISSUE TITLE
`maxCols` doesn't seem to work properly.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4156]
### Description
When the dataset is larger than declared in the `maxCols` property, `maxCols` doesn't trim the displayed dataset (while `maxRows` does).

### Steps to reproduce
1. Set the dataset to be 100x100 entries, for example
2. Set the `maxRows` to `2`
3. Set the `maxCols` to `2`

**Result:** The displayed data has two rows, but 100 columns.

### Demo
http://jsfiddle.net/js_ziggle/hhgdkbp5/

-----------

### Note:
The `maxRows` option was fixed in `0.29.2` (#3803), probably the same has to be done with `maxCols`.

**Comment by AMBudnik** [comment]
Thanks @jansiegel 

that

![image](https://cloud.githubusercontent.com/assets/10757813/26200637/5c10356a-3bcf-11e7-92e8-00aa256f758e.png)

looks so much better.
