### ISSUE TITLE
Delay for user input

### ISSUE THREAD

**Issue by Rex90** [handsontable/handsontable#4157]
### Description
I am seeing a delay between when the user types a character and it appears in the table. I want to figure out if this is an issue in my implementation (is there anyhting I could do to affect this perforemance).

Below is a timeline from chrome for a single key input (with some CPU throttling to accentuate the effec). Are those bottom "recalcualte events" avoidable? they seem to ake the most time?

![image](https://cloud.githubusercontent.com/assets/6030955/24403485/073ac0d8-13b5-11e7-99a3-1f66fb6dc842.png)

**Comment by Rex90** [comment]
Bit more info - this is what I see when i type 1 character into a cell:

![image](https://cloud.githubusercontent.com/assets/6030955/24506288/e5451c20-1554-11e7-86a9-8353d568376d.png)

**Comment by AMBudnik** [comment]
Hi @Rex90 

Can you send me a demo that generates those values?

**Comment by Rex90** [comment]
Sorry @AMBudnik; I am unable to recreate this in a demo but I have identified the issue to be the "resize" function for the cell thats causing the violation.

**Comment by AMBudnik** [comment]
It will be very hard for our developers to recreate the same issue on their site when a result of loading on a normal table does not share the same results.
Can you, maybe, share any other information about the dataset, used renderers or amount of data?

**Comment by AMBudnik** [comment]
hi @Rex90 I am just checking by to ask about the progress? I am very curious about this issue and be happy to test any demo you can send.

**Comment by Rex90** [comment]
Hi Aleksandra -

As mentioned we don't currently feel the time needed to recreate this issue in a fiddle is worth it ( we tried and it didn't work so probably needs a lot more work to reproduce other aspects of our app).

We are sticking to our workaround to the resize function for the moment.

Thanks



On 18 Apr 2017, at 09:59, Aleksandra Budnik <notifications@github.com<mailto:notifications@github.com>> wrote:


hi @Rex90<https://github.com/Rex90> I am just checking by to ask about the progress? I am very curious about this issue and be happy to test any demo you can send.

**Comment by AMBudnik** [comment]
I understand @Rex90 Thank you for your prompt reply.

I think that as we are not able to replicate it we can close the issue.
