### ISSUE TITLE
Render removes applied cell classes

### ISSUE THREAD

**Issue by Rex90** [handsontable/handsontable#4158]
### Description

I apply cell classses to my cells using jquery. These are removed when the .render() function is called.

### Demo
Here is a demo, press AddClass to add the class to a random cell and Render to run the render() fn.
http://jsfiddle.net/armensg/oh6goLqh/3/

**Comment by AMBudnik** [comment]
To avoid erasing class I recommend using [`cells` ](https://docs.handsontable.com/pro/1.10.1/Options.html#cells)option. Here's an example: http://jsfiddle.net/wc3zrL18/
