### ISSUE TITLE
In the Meteor ,error：Handsontable is not defined  

### ISSUE THREAD

**Issue by huancaixin** [handsontable/handsontable#4160]
### Description

We develop with Meteor and React .
Before we use handonstable 0.16.1 everything is ok,
we recently purchased V1.10.1, replaced V0.16.1,
Console error：
   Uncaught ReferenceError: Handsontable is not defined  
   at jQuery.fn.init.$.fn.handsontable

Code：
import React, { PropTypes, Component } from 'react';
import './handsontable.full.js';
class FormQuery_RM_Edit extends React.Component {
  constructor(props) {
    super(props);
 }
componentDidMount(){
    var $container = $("#hot");
    $container.handsontable({
      data:[],
      stretchH: "all",
      startRows: 1,
      manualColumnResize: false,
      manualColumnMove: false,
      columnSorting: true,
 });
}

### Your environment
* Handsontable version:
1.10.1
* Browser Name and version:
chrome 56.0
* Operating System:
macOS 10.12.3

**Comment by AMBudnik** [comment]
Hi @huancaixin 

between those versions, we have switched to the jQuery-free solution (v 0.12.6). Please take a minute to check release notes for those versions: https://github.com/handsontable/handsontable/releases?after=0.15.0-beta2

**Comment by huancaixin** [comment]
@AMBudnik 
thanks for your answer.
After read the doc，i did it by the different way.
I download the package by command "npm install git+https://{username}:{password}@my.handsontable.com/handsontable/handsontable-pro.git".
now another error:
Uncaught Error: Cannot find module 'numbro'
    at require (modules-runtime.js?hash=637cb12…:119)
    at newRequire (modules.js?hash=da8667d…:193650)
    at modules.js?hash=da8667d…:193670
    at Object.23.cellTypes (modules.js?hash=da8667d…:198089)
    at newRequire (modules.js?hash=da8667d…:193668)
    at modules.js?hash=da8667d…:193670
    at Object.140.../node_modules/hot-builder/node_modules/**handsontable**/src/browser (modules.js?hash=da8667d…:217991)
    at newRequire (modules.js?hash=da8667d…:193668)
    at outer (modules.js?hash=da8667d…:193676)
    at modules.js?hash=da8667d…:193681

**Comment by AMBudnik** [comment]
Hi @huancaixin 

Yes, I can see that you have updated the code to a version where we moved to using Numbro instead of Numeral. As I assume you are trying to load the newest PRO version. 

Please send me a direct message to support@handsontable.com as this conversation may need some sensitive account data to be mentioned.

**Comment by huancaixin** [comment]
Hi @AMBudnik
I get the V1.10.2,but the same error still appears.
error code:
**at Object.140.../node_modules/hot-builder/node_modules/handsontable/src/browser (modules.js?hash=da8667d…:217991)**
The path  is not exist.

**Comment by AMBudnik** [comment]
Hi @huancaixin 

It is hard to say anything without seeing it, however, please try to [create a custom build](https://handsontable.com/blog/articles/how-to-build-a-custom-version-of-handsontable) (if you're using Windows I recommend Git Bash).

**Comment by huancaixin** [comment]
Hi @AMBudnik 
sorry,i get another method to use the hansontable.
i have no problem. thanks very much.

**Comment by AMBudnik** [comment]
OK, I see. Thank you for an update.

I guess that we can close the issue then.
