### ISSUE TITLE
Wrong row calculation if custom renderer applied data bigger than row height

### ISSUE THREAD

**Issue by minchopm** [handsontable/handsontable#4161]
If you know how to solve this issue will be great because I can't load images with custom render if their height is bigger than row height. I am providing a demo cloned from your example of custom renderers,

[http://jsfiddle.net/minchopm/xcsf71wu/1/](http://jsfiddle.net/minchopm/xcsf71wu/1/)

When you scroll few rows, renderer and before renderer are triggered multiple times for each pixel that you move the scrollbar. And just when the visible row is near to the top of the page the rows are rerendered actually it is moving the just hidden row into the position of the row that you are looking, and if you have more complex content into the grid it is flickering and it is rendering wrong content. So if I clear the data into TD cells the renderer is called too many times and the content has been showed and cleared immediately and infinitely. Playing with viewportRowRenderingOffset has no effect - just the performance is going bad.
autoRowSize - sometimes is rendering the contnet into ghostTable

**Comment by minchopm** [comment]
Also I found that if I attach something to the TD element with a little delay it is appear at the last row

**Comment by AMBudnik** [comment]
Thanks for sharing @minchopm 

This issue may be related to https://github.com/handsontable/handsontable/issues/3215

**Comment by AMBudnik** [comment]
It seems to work fine in the latest version. Demo http://jsfiddle.net/d7tm0qoz/

@minchopm I am closing the issue but if you are still having any difficulties with the code please let me know.
