### ISSUE TITLE
Disallow enterBeginsEditing: false to toggle checkbox state

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4162]
### Description

As previously mentioned with @swistach we should block an ability to change a checkbox state via <kbd>ENTER</kbd> key when `enterBeginsEditing` option is set to `false`.

### Steps to reproduce

1. Use <kbd>ENTER</kbd> key on any checkbox cell.

### Demo

http://jsfiddle.net/handsoncode/p5vyj3ku/

### Your environment
* Handsontable version: 0.31.1
* Browser Name and version: Chrome 56
* Operating System: Windows 10

`[G #5528]`

**Comment by AMBudnik** [comment]
Changing the label from `change` to `bug`

**Comment by AMBudnik** [comment]
Works the same in v`5.0.1`. Demo http://jsfiddle.net/zx2ocbtk/

**Comment by wojciechczerniak** [comment]
Released in `v6.2.1`.
