### ISSUE TITLE
Async setValue

### ISSUE THREAD

**Issue by SergeyShablenko** [handsontable/handsontable#4163]
How to call finishEditing only after setValue finished?
In my realization, i have some async code in setValue, and i need to save changes only after value set.

**Comment by swistach** [comment]
Hi @SergeyShablenko 
I'm not sure what exactly is your goal. Could you prepare simple demo on jsfiddle (with setTimeouts instead of ajax callbacks)?
You can use this example as starting point: http://jsfiddle.net/697tm1x8/

**Comment by AMBudnik** [comment]
I assume that we can close the issue as there is no reply for more than 20 days.

Please leave a comment if you are still facing the same or any other issue.
