### ISSUE TITLE
Is it possible to limit filter options as well as adding custom filter options?

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4165]
Hi, I didn't find a way to limit filter options to `Is empty` and `Is not empty` only. Is there any way to limit it?
Currently all available predefined options are visible:
![image](https://cloud.githubusercontent.com/assets/710513/24654277/a1e1a250-1941-11e7-9ee7-ff4a7a27d787.png)

Also is there any way to add custom options like 'Show cells with errors' where I will define what  data/rows to show?

**Comment by AMBudnik** [comment]
Hi @andrewQwer 

Unfortunately, both functionalities are currently unavailable.

**Comment by andrewQwer** [comment]
Hi @AMBudnik,

So the only way to define custom funcitonality like this is to add custom options directly to `dropdownMenu` and apply my custom filtering logic in `callback` method ?
```
                                          dropdownMenu={{
                                              callback: (key, options) => {
                                              },
                                              items: {
                                                  'filter_1': {
                                                      name: 'None'
                                                  },
                                                  'filter_2': {
                                                      name: 'Is empty'
                                                  },
                                                  'filter_3': {
                                                      name: 'Is not empty'
                                                  }
                                              }
                                          }}
```

**Comment by AMBudnik** [comment]
Exactly @andrewQwer 

you would need to create a custom option for the `dropdownMenu`, not the Filters.

Here's a simple example http://jsfiddle.net/handsoncode/qqust6nc/

**Comment by andrewQwer** [comment]
Thanks @AMBudnik. Hope to see filter customization soon :)
