### ISSUE TITLE
Is there an event triggered before calculating a formula? 

### ISSUE THREAD

**Issue by royosherove** [handsontable/handsontable#4166]
### Description
I'd like to be able to do a custom calculation on cells (for example, is someone writes '=bad' i want to turn the cell calculation formula to return the value 1. if someone sets the cell value as '=someurltoimage' i'd like to set the calculated formulate to display an image.

### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @royosherove 

I think that you should check[ `beforeChange`](https://docs.handsontable.com/pro/1.10.2/Hooks.html#event:beforeChange) callback. 

It allows you to change a value before it is calculated.
