### ISSUE TITLE
updateSettings method set the 'paste' property of contextMenu to '{}', it will display 'null' on the contextMemu.

### ISSUE THREAD

**Issue by jakever** [handsontable/handsontable#4167]
### Steps to reproduce

1.use updateSettings set contextMenu property
2.set the paste to a empty object like {}.
3.check the contextMenu, the paste menu on contentMenu display with 'null', and it doesn't work for copy.

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @jakever 

I assume that you want to disable the 'contextMenu' in 'updateSettings', right?

**Comment by jakever** [comment]
Hi @AMBudnik 
No, i just want to render the contextMenu by using 'updateSetting' method, but not in default config, like this as below:
    hot.updateSettings({
                        contextMenu: {
                            items: {
                                'copy': {},
                                'paste': {},
                                'row_above': {}
                            }
                        }
                    })
 as above, all functions are ok except 'paste' on the contextMenu.

**Comment by AMBudnik** [comment]
Thank you for additional information, I also got "null" even if in the code it's written that the `key` is `paste`.

Demo: http://jsfiddle.net/handsoncode/c8tpuvca/

**Comment by AMBudnik** [comment]
`(`[`related issue of forum`](https://forum.handsontable.com/t/gh-4167-copy-cut-and-paste-in-custom-context-menu/1059)`)`

**Comment by swistach** [comment]
This issue will be fixed in #4234

**Comment by swistach** [comment]
Hi @jakever, in new version of the Handsontable you have to create your own implementation of 'Paste' in the context menu.
Here you can find a tutorial: https://docs.handsontable.com/0.33.0/demo-copy-paste.html#paste-in-context-menu
