### ISSUE TITLE
Sorting doesn't work when filtering is applied

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4170]
### Description
Sorting doesn't work when filtering is applied (in specific situations)

### Steps to reproduce

1. Go to http://jsfiddle.net/zgrry4ap/.
2. Filter "Currency" column using the filter "Begins with" condition with "a" value.
3. Try to sort any column. In the result, nothing happens.

### Demo

http://jsfiddle.net/zgrry4ap/.

### Your environment
* Handsontable version: 0.31.2
* Browser Name and version: Chrome
* Operating System: macOS

**Comment by AMBudnik** [comment]
![gif](https://cloud.githubusercontent.com/assets/10757813/24740505/d4f80b6e-1aa1-11e7-9f5a-6b23f3d8488b.gif)

**Related** situation. 

When we filter any column first and then try to sort it multiple times some of the rows are immune to sorting and stay at the same position.

**Comment by budnix** [comment]
Thanks, @AMBudnik! I believe that your scenario can be caused by the same bug.

**Comment by GanjuV** [comment]
Issue exist when sorting and persistentState is true and we are calling untrimAll() and trimRows() simultaneously.
PFB the link for details for your reference.
https://jsfiddle.net/Vaibhav34/b2buhp6u/2/
#4312

**Comment by sergionegri** [comment]
Any news on this? Given the estimation of "a day or more" I was hoping in a quick resolution ;)

**Comment by AMBudnik** [comment]
We have been little busy building a new website and a licence-key system but we'll be fixing all 'high' priority bugs in the Q4 this year.

**Comment by travisraghib** [comment]
Q4 is over. Any updates on this?

**Comment by AMBudnik** [comment]
I hope that within next 2 weeks we'll have a new Roadmap - for 2018. Currently, there is a very long list of ideas/changes/bugs without any date on our private Trello board.

**Comment by krzysztofspilka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix sorting when used with filtering](https://trello.com/c/v3YT5CTs/107-fix-sorting-when-used-with-filtering)

**Comment by AMBudnik** [comment]
Still replicable in version 0.35.1

**Comment by briancaldass** [comment]
some solution to this issue ?, the same thing happens to me

**Comment by AMBudnik** [comment]
Sorry @briancaldass we did not find any fix/workaround yet

**Comment by briancaldass** [comment]
@AMBudnik  
So what can I do for the moment? to sort ascendingly with filter

**Comment by AMBudnik** [comment]
I really would like to give you some other options. However, the only thing I can do (as we do not have a workaround for this issue) is to find a way to review this issue soon and try to fix it. 
I can understand why this is confusing - the filtering and sorting are main functionalities of a spreadsheet. This should work without flaws.

**Comment by AMBudnik** [comment]
Replicable in version 1.18.1

**Comment by wszymanski** [comment]
It's probably related to `trimRows`, `maxRows` and `columnSorting` plugins. The minimum demo showing the problem: http://jsfiddle.net/6aoyx6aL.

**Comment by wszymanski** [comment]
With commit https://github.com/handsontable/handsontable/commit/a0e41c07336956573fd3bba485df27c3a6028415#diff-4f1c7d0a16af316d64e21a77d4c3fb61R364, there was added an extra hook for purpose of translating from visual index to physical index. For me, it's unnecessary. Function `countEmptyRows` hasn't worked properly.

**Comment by wszymanski** [comment]
Function `countEmptyRows` hasn't worked properly. It has passed physical index to `isEmptyRow` function while it works on visual indexes. Analogous, `countEmptyCols` doesn’t work like that and it should work properly.

**Comment by krzysztofspilka** [comment]
@wszymanski looks good to me

**Comment by AMBudnik** [comment]
Hi @briancaldass @travisraghib @sergionegri @GanjuV 

the issue has been solved in v 2.0.0. (CE and PRO).

Feel free to comment if it doesn't work for you or you have any concerns and we'll reopen the ticket.

**Comment by rayokao** [comment]
Seems like there's an issue if you're using minSpareRows, uncheck the blank cells from the filter and then sort:

[http://jsfiddle.net/rayokao/r0ujLb4h/](http://jsfiddle.net/rayokao/r0ujLb4h/)

**Comment by AMBudnik** [comment]
Thank you for sharing the issue. I have replicated it with `7.1.1.`

It looks like the issue is still replicable in the latest build of `8.0.0`. http://jsfiddle.net/handsoncode/h2gfmc97/

![GIF](https://user-images.githubusercontent.com/10757813/65960213-32ab8c80-e454-11e9-9ffe-328b1ffb20d5.gif)

Can you check it out @aninde ? Not sure if I have the latest changes (those are from 26/09)

**Comment by AMBudnik** [comment]
Hey @rayokao 

It looks like the exact issue has been already tested with the newest build here https://github.com/handsontable/handsontable/issues/5983 so please track changes to https://github.com/handsontable/handsontable/issues/5983 for more updates.

**Comment by aninde** [comment]
@AMBudnik, https://github.com/handsontable/handsontable/issues/4170#issuecomment-537004622 you tested it on the latest build. You're right, this bug is duplicate of https://github.com/handsontable/handsontable/issues/5983.

**Comment by dkwebtec** [comment]
after 3 years still not fixed in 8.0

https://forum.handsontable.com/t/sorting-after-filtering-with-minsparerows-set/1411

**Comment by AMBudnik** [comment]
@dkwebtec forum ticket related to use of the `minSpareRows` and this topic does not code a case with `minSpareRows`. In the end, the spare row issue was moved to https://github.com/handsontable/handsontable/issues/5983 and true, it is still replicable in v 8.0.0.
