### ISSUE TITLE
'afterValidate' gets called before data changed

### ISSUE THREAD

**Issue by HaroldStruwig** [handsontable/handsontable#4171]
### Description
by editing a cell and pressing ENTER, ```afterValidate``` was always called after ```data``` changed but is now called before ```data``` change

this is not ideal as I need to get the row entry (with the new value) using ```data[row]``` in ```afterValidate```

### Your environment
* Handsontable version: handsontable-pro1.10.2

**Comment by AMBudnik** [comment]
Hi @HaroldStruwig 

I think this subject was already mentioned here https://github.com/handsontable/handsontable/issues/3424

If you wish the order to be changed please share a comment at https://github.com/handsontable/handsontable/issues/3424
