### ISSUE TITLE
rowspan in the header and filling data by programmatically 

### ISSUE THREAD

**Issue by maxotov** [handsontable/handsontable#4174]
hello! i read previous issues that rowspan in the header not yet implemented. When you going to add this functionality? how implement this feature himself?

second question: can i fill programmatically table rows (tr, td)? Is this possible?

**Comment by AMBudnik** [comment]
Hi @maxotov 

we did not test possible solutions for nesting cells vertically inside headers so it would be really hard to give you any tips. This is our Roadmap for Q2 of 2017 https://trello.com/b/PztR4hpj/handsontable-roadmap-2017-login-to-vote. Unfortunately, we do not have this feature on our task list for this quarter.

When it comes to changing cells' body programmatically you can use all **setData** methods or **loadData**() if yo need to check how data set, you can also use **data** settings while using **updateSettings** plugin. when it comes to headers if it only relates to data you can use **colHeaders** and if something more then **afterGetColHeader** callback. It all depends on what you would like to achieve.

**Comment by deepthan** [comment]
I have implemented rowspan, which can be set in the same way as' nestedHeaders' and 'colspan', if you need it, please contact me at Github.
for example
```
nestedHeaders:  [
  [ { label: 'c', rowspan: 3}, { label: 'B', colspan: 9 }],
  ['', { label: 'E', colspan: 4 }, { label: 'F', colspan: 4 },  { label: 'G', rowspan: 3}],
  ['', { label: 'I', colspan: 2 }, { label: 'J', colspan: 2,  rowspan: 2 }, { label: 'K', colspan: 2 }, { label: 'L', colspan: 2 }, ''],
  ['N', { label: '2', colspan: 1 }, 'P', '', '', 'S', 'T', 'U', '22', '']
];

```

To render
![37818273a1cfa70243ff246937a0d9f](https://user-images.githubusercontent.com/22695767/158949613-993eae5d-83e6-497e-bd5e-40a05fde52ca.png)
