### ISSUE TITLE
can't remove rows when there is 'dropdown' cell type in the table ?!

### ISSUE THREAD

**Issue by Kotmawi** [handsontable/handsontable#4178]
I am trying to modify [this](http://docs.handsontable.com/0.16.1/demo-custom-buttons.html) example to make the first column cell types as 'dropdown'. 

when ever I have  'dropdown' cell type the logic in that example never works!
here is the code : 

```
<!DOCTYPE html>
<html>
<head>
	<title>editor</title>
<link rel="stylesheet" media="screen" href="http://handsontable.com/dist/handsontable.full.css">
</head>
<body>
<div id="example"></div>
<script src="http://docs.handsontable.com/0.16.1/scripts/jquery.min.js"></script>
<script src="http://docs.handsontable.com/0.16.1/bower_components/handsontable/dist/handsontable.full.js"></script>
<link type="text/css" rel="stylesheet" href="http://docs.handsontable.com/0.16.1/bower_components/handsontable/dist/handsontable.full.min.css">
<script src="http://docs.handsontable.com/0.16.1/scripts/removeRow-demo/handsontable.removeRow.js"></script>
<link rel="stylesheet" href="http://docs.handsontable.com/0.16.1/scripts/removeRow-demo/handsontable.removeRow.css">

<script type="text/javascript">
var
    data = [],
    container = document.getElementById('example'),
    hot;

  hot = new Handsontable(container, {
      outsideClickDeselects: false,
    removeRowPlugin: true,
    colHeaders: ['type', 'name', 'required','D','E','F'],
    columns: [
      
        {
        	type: 'dropdown',
                 source: ['c','a']
    }
        ,{},{},{},{},{}
    ],
    minSpareRows: 1
  });
  hot.loadData(data);

</script>
</body>
</html>
```

any idea ?

**Comment by AMBudnik** [comment]
Hi @Kotmawi 

you were testing an old version of Handsontable.

Please check this example: http://jsfiddle.net/handsoncode/zmak0jht/ I have added the `dropdown` as a first column and updated the example to v0.31.2 (latest)

**Comment by Kotmawi** [comment]
many thanks !

**Comment by Kotmawi** [comment]
hello @AMBudnik  

it still doesn't work !!

try to select a value from the list ! after that the delete button will not appear again !!

**Comment by AMBudnik** [comment]
You're right. We are getting a console log 

![image](https://cloud.githubusercontent.com/assets/10757813/24853885/cbbdd31a-1ddc-11e7-93b6-0edee4d92c3f.png)

and `x` elements are disappearing. I will move this issue to the docs as it related to the demo on the page rather that to the Handsontable logic.

**Comment by AMBudnik** [comment]
and here http://jsfiddle.net/handsoncode/gugkhLp4/ is a similar feature if you would ned it in your project

**Comment by Kotmawi** [comment]
when I try to delete the last row only all rows are deleted automatically !!

**Comment by AMBudnik** [comment]
@Kotmawi thanks for spotting that.
I guess that we should then just wait for the official fix.
