### ISSUE TITLE
`maxRows` doesn't seem to work properly.

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4180]
### Description
Work of option should be changed. Functions `getDataAtCol` and `getDataAtRow` doesn't work properly. It should be refactored based on changes in #4156.

### Steps to reproduce

1. Open demo: http://jsfiddle.net/wojciech/erb942ty
2. Click on the `getDataAtCol(0)` button. `getDataAtCol` return 1000 rows, but should return only `10`.
3. Click on the `getDataAtRow(20)` button. `getDataAtRow` return 10 rows, but should return empty set.

### Demo

http://jsfiddle.net/wojciech/erb942ty/

### Your environment
* Handsontable version: 0.31.2
* Browser Name and version: 57.0.2987.98
* Operating System: macOS Sierra 10.12.3

**Comment by AMBudnik** [comment]
Fixed, thanks!
