### ISSUE TITLE
Conditional formatting rows/cols as read only with sorting enabled causes wrong matches

### ISSUE THREAD

**Issue by seharri92** [handsontable/handsontable#4182]
Using cells to decide which rows and columns should be read only works on the render, but not if the table is sorted. I am trying to make an entire row read only if a certain condition is met, there may be a better solution than using cells for rendering as it goes through every column on every row (looks like multiple times) when I only need to go through just the rows.

Taking the conditional formatting example and adding colHeaders and columnSorting causes the readOnly checks to react unexpectedly. Sorting the E and D columns does not cause any other rows in E to become read only, but Sorting on A will cause all rows in E to become read only if sorted a few times, Sorting on B and C causes one of the 13's to become read only. The if row === 0 then make readOnly fails if the table is sorted in any fashion.

Demo: http://jsfiddle.net/seharri/9tbdwarL/

### Your environment
* Handsontable version: 1.10.2
* Browser Name and version: Chrome 57.0.2987.133
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing @seharri92 

I have replicated the issue. 

When we sort column `D` and `E` in the last column there is only one read-only cell (value `readOnly)`. In other cases, we get two read-only cells (values `readOnly` and `13`).

![gif](https://cloud.githubusercontent.com/assets/10757813/24895450/c237efd8-1e90-11e7-93d4-76f765213cec.gif)

**Comment by AMBudnik** [comment]
Thanks for sharing and sorry for misleading with the label I have misunderstood the example.

@wszymanski has already raised an issue to add an explanation about handling types of indexes by `cells` option. The reason behind an actual behavior is the choice of logical indexes. If you would like to change the indexes you can use the `toVisualColumn` and `toVisualRow` methods, like in the following demo http://jsfiddle.net/wojciech/gfe7bxrt/

Information will be added with mentioned issue https://github.com/handsontable/handsontable/issues/4185 so I'm closing this one.
Again thanks for sharing. You're right - it may look pretty complicated at the first glance.

**Comment by seharri92** [comment]
I don't understand what the demo is showing? Everything is readOnly due to the lines 
if (visualRowIndex === 0 || dataAtCell === 'readOnly') {
       cellProperties.readOnly = true; // make cell read-only if it is first row or the text reads 'readOnly'
} else {
      cellProperties.readOnly = true;
}

If you remove the else block, making only the first row and 'readOnly' text readOnly, as in the original, then the exact same bug exists.

**Comment by seharri92** [comment]
Oh that looks like a mistake in the code, change the else block to cellProperties.readOnly = false; it appears to work.

**Comment by AMBudnik** [comment]
@seharri92 thanks for confirmation

**Comment by wszymanski** [comment]
@seharri92 Sorry for the mistake. Of course you are right. I've edited example.
