### ISSUE TITLE
Undo/Redo is enabled by default

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4183]
Hi,

Documenation says the following (http://docs.handsontable.com/0.31.2/Options.html#undo):
```
If true, undo/redo functionality is enabled.

Default Value:
undefined
```

But undo/redo works even if I don't initialize `undo` option on initialization. It becomes disabled only if I set `undo: false` manually. Should the documenation say `Default value: true`?

Short example: http://jsfiddle.net/s6t768pq/609/

**Comment by AMBudnik** [comment]
It is set to `undefined` but it looks like that some other hook (maybe the change hook) is enabling it.

Thanks for sharing. This one should be checked.

**Comment by AMBudnik** [comment]
Did not change in `2.0.0`

**Comment by AMBudnik** [comment]
There is actually a note in the _handsontable.full.js_ file that says

>  @description
>  * Handsontable UndoRedo plugin allows to undo and redo certain actions done in the table.
>  *
>  * __Note__, that not all actions are currently undo-able. The UndoRedo plugin is **enabled by default.**

We should add an information in the docs that even when [`Default Value: undefined`](http://jsfiddle.net/rpg67khe/) the undo action is enabled by default.

**Comment by wojciechczerniak** [comment]
Moved to https://github.com/handsontable/docs/issues/8
