### ISSUE TITLE
Add hooks: beforeRowsHide / aferRowsHide

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4187]
### Description

We can add this hooks beforeRowsHide / aferRowsHide. Especially because this actions don't trigger beforeChange/afterChange.

### Your environment
* Handsontable version: 1.10.2
`#GL 141`

**Comment by AMBudnik** [comment]
The idea has been added to our [wiki section for the Feature Requests](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
We should also add the same callback for columns.

**Comment by wojciechczerniak** [comment]
Just one note, different hook names to be more in line with our current naming convention: beforeHideRows, afterHideRows, beforeHideColumns, afterHideColumns

**Comment by jansiegel** [comment]
Issue moved to [handsontable/handsontable-pro #163](https://github.com/handsontable/handsontable-pro/issues/163) via [**ZenHub**](https://www.zenhub.com/)

**Comment by AMBudnik** [comment]
For all the users who are checking this topic. We've added the hooks in v `7.0.0` with https://github.com/handsontable/handsontable/issues/5522
