### ISSUE TITLE
default cell values on row insert

### ISSUE THREAD

**Issue by HaroldStruwig** [handsontable/handsontable#4189]
it will be a nice feature to be able to specify a default value for a cell in the ```columns``` definition which will be applied when a row is inserted and the cell is empty

**Comment by AMBudnik** [comment]
Hi @HaroldStruwig 

We already can do it via `dataSchema` like here http://jsfiddle.net/handsoncode/asx2Loz2/ but you are right - maybe it will be easier to add this functionality for `columns`.

Thank you for sharing this idea.

**Comment by AMBudnik** [comment]
The idea has been added to our [wiki section for the Feature Requests](https://github.com/handsontable/handsontable/wiki/Feature-requests). 
Again thanks for sharing.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
