### ISSUE TITLE
Editor doesn't consider available space

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4190]
Hi,

Is it possible to adjust editor's position according to cell clicked? If I open the last cell for edit and my container doesn't allow scrollbars then it's not possible to select date. See an example: http://jsfiddle.net/s6t768pq/615/ 
Some kind of position calculation would help a lot.

**Comment by AMBudnik** [comment]
Hi @andrewQwer 

I think that the issue is related to the one I have added here https://github.com/handsontable/handsontable/issues/4184

It is unavailable but surely will boost UX

**Comment by andrewQwer** [comment]
Yeah, comment box has the same issue.

**Comment by andrewQwer** [comment]
Could you please also add the same feature request for editors? Datetime editor, dropdowns should consider available space and should be expanded upwards if there are no enough space to show it completely.

**Comment by AMBudnik** [comment]
Yes, I think that when we will be adding the feature we will consider all cell types.

**Comment by AMBudnik** [comment]
The idea has been approved added to our [wiki section for the Feature Requests](https://github.com/handsontable/handsontable/wiki/Feature-requests). 
Again thanks for sharing.

**Comment by AMBudnik** [comment]
Linked conversation is continued in the discussions panel https://github.com/handsontable/handsontable/discussions/7923
