### ISSUE TITLE
getSourceData is returning data in updated ordering 

### ISSUE THREAD

**Issue by haroonob** [handsontable/handsontable#4194]
### Description
getSourceData is returning data in updated ordering 

### Steps to reproduce

1. reorder rows 
2. click get Source data 
3. in console logs get Source data method is returing objects array in updated order 

### Demo
http://jsfiddle.net/duccoder/rbse44kc/1/

**Comment by AMBudnik** [comment]
Hi @haroonob 

I am not able to replicate the bug.

When I am moving row with values `3` to the top in `getSourceData()` I still have `1` as a first value - as intended.

Please guide on what you get and what you would like to get

**Comment by haroonob** [comment]
Mybad, If intended, how can I get data objects in updated ordering.

**Comment by AMBudnik** [comment]
Here ( I guess) are all methods for object type data: http://jsfiddle.net/handsoncode/r7roepu3/
Let me know if you need anything else

**Comment by haroonob** [comment]
Thanks AMBudnik for your help

**Comment by AMBudnik** [comment]
You're welcome @haroonob
