### ISSUE TITLE
 Facing columns disappearing issue while scroll enabled

### ISSUE THREAD

**Issue by ramesh586** [handsontable/handsontable#4198]
Hello,

Please help me out, I'm facing following issue while having more columns than window . Please watch the video for reference

https://www.useloom.com/share/a4f4812e54d841a8bf2bd70cdd1e7999

**Comment by AMBudnik** [comment]
Hi @ramesh586 
please check id adding [`autoColumnSize`](https://docs.handsontable.com/pro/1.10.2/Options.html#autoColumnSize) fixes the issue with misaligned columns. It may also be a styling issue as normally table scrolls to view a full cell and in your case when you click the checkbox cell table does not scroll.

Please check `autoColumnSize` and let me know if it changed anything

**Comment by ramesh586** [comment]
@AMBudnik thanks for the quick reply 
I added **autoColumnSize: {useHeaders: true}** Still getting same issue . In video you can see after changing any editable field or checking checkbox , columns which are out of focus disappearing . Please help me in this.

**Comment by AMBudnik** [comment]
It looks like there ca be some excess CSS settings that causes the issue. You can also try to use `viewportColumnRenderingOffset` where the `numeric` value is max number of columns in your table.

If that won't help please try to paste the spreadsheet to a JSFiddle where I will be able to test it.

**Comment by ramesh586** [comment]
@AMBudnik  ohhhh.. It's got solved . Thanks a lot.  Small doubt can i set more than number of columns for the **viewportColumnRenderingOffset** param?

**Comment by AMBudnik** [comment]
@ramesh586 great :)

Yes, theoretically you can set larger number to `viewportColumnRenderingOffset` that a maximum number of columns and nothing should be broken. Here is a sample demo where I have `100` columns but add `110` to `viewportColumnRenderingOffset`

**Comment by ramesh586** [comment]
@AMBudnik 
Hello,
The issue of columns disappearing is fixed but still the another issue existed
please see the video. If i selected one readonly cell its changing focus few cells based no of invisible columns. Please help me in this to solve problem
https://www.useloom.com/share/bbdd1b8a6da74fc4949e56bddafbe7c3

**Comment by AMBudnik** [comment]
Hi @ramesh586 

I think that I won't be able to fix it before I get a demo. I have no idea what can cause the issue.
Please create a JSFiddle/JSBin/CodePen demo and I'll do my best to test it.

**Comment by AMBudnik** [comment]
Issue closed for lack of a demo.
