### ISSUE TITLE
dynamic change data source of nested Attribute

### ISSUE THREAD

**Issue by huancaixin** [handsontable/handsontable#4199]
Hi.
I created a hotInstacne of handsontable.
set attribute {nestedRows: true}
set data source like [{categoryOne:  "xxx", __children: [......]}......]
click icon "+", datas nested.
dynamic change data source like [{categoryTwo:  "bbb", __children: [......]}......]
The handsontable display exception: the number of rows changed less。

**Comment by huancaixin** [comment]
sry. I solved.
before change the data source i re create the hot.

**Comment by AMBudnik** [comment]
OK, thank you for an update. Have a great day :)
