### ISSUE TITLE
Copy Paste of muliple rows calling only one OnChange event for the control

### ISSUE THREAD

**Issue by prabhat007** [handsontable/handsontable#42]
Hi,

First of all thanks for this nice control. Its really very great excel like web tool.

Actually I was exploring this nice tool and in the process I came through that when we copy multiple rows from one MS Excel sheet and paste those into this control only one hit to the OnChange defined event raised. Will you please guide me how this can be achived in this control. Actually I want to raise this event for the all rows that I am going to paste there. Thanks in advance.

Thanks

**Comment by dishant8** [comment]
@prabhat007  how did you manage your use case.? still it hits afterChange for only one row.

**Comment by mohithg** [comment]
I too have this use case. How to get afterChange/beforeChange fired for all rows that I paste?
