### ISSUE TITLE
I hope to add a new method ' insert_cell '

### ISSUE THREAD

**Issue by chengaomin** [handsontable/handsontable#4200]
http://docs.handsontable.com/0.20.1/Core.html#alter

```alter for possible values: "insert_row", "insert_col", "remove_row", "remove_col" ```

I hope to add a new method ' insert_cell '.

can you tell me how to code this method ?

**Comment by AMBudnik** [comment]
Hi @chengaomin 

Can you share any draft / image where we will be able to imagine how this should work?

A cell is a part of a bigger structure row/col and a table itself so usually when you add a single cell it would need to impact some rows/columns as well.

**Comment by chengaomin** [comment]
It is my idea , like this two images. @AMBudnik 

![image](https://cloud.githubusercontent.com/assets/4586906/25132662/daa1bd64-247c-11e7-9c0e-06bf3d5615d5.png)
![image](https://cloud.githubusercontent.com/assets/4586906/25132689/f26bf8ce-247c-11e7-8750-819b29c3da8c.png)

**Comment by AMBudnik** [comment]
Ohhh I see, so what we do here is shifting data from a cell on the right. Great idea.

**Comment by AMBudnik** [comment]
The idea has been approved added to our [wiki section for the Feature Requests](https://github.com/handsontable/handsontable/wiki/Feature-requests). 
Again thanks for sharing.

**Comment by lql0ve** [comment]
Good idea. When can this be done?

**Comment by AMBudnik** [comment]
I think that this will be possible after we manage to add the eco-rendering.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
