### ISSUE TITLE
Misalignment of the overlays after change colHeaders by updatesettings several times

### ISSUE THREAD

**Issue by minteliuwm** [handsontable/handsontable#4201]
### Description
First,  chang `colHeaders ` by `updateSettings({...})` and one of headers has more lines than before,
Then, chang `colHeaders` by `updateSettings({...})` and all headers has less lines than before.
You can see the height of colHeader is not change the second time.

### Steps to reproduce
1. Go to the demo

### Demo
https://jsfiddle.net/MinteLiu/hw2yneg7/1/

### Your environment
* Handsontable version: 0.31.2
* Browser Name and version: Chrome 56.0.2924.87
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @minteliuwm 

the demo above doesn't load - I guess that there may be a script issue. I have loaded the same settings here http://jsfiddle.net/hty4k5yx/ but did not get any misalignment and I am using the same OS and Browser as you are. Do you have the browser viewport set to 100% zoom? Also please share a screen or video where I'd be able to see how it look on your side.

A fix for some misalign issues is to use [`autoColumnSize`](https://docs.handsontable.com/pro/1.10.2/Options.html#autoColumnSize) and [`autoRowSize`](https://docs.handsontable.com/pro/1.10.2/Options.html#autoRowSize). Can you check if that solves the issue?

**Comment by AMBudnik** [comment]
If you still experience the same issue please let me know.
