### ISSUE TITLE
In the Firefox browser and with the easyUI tab, will cause the display bug

### ISSUE THREAD

**Issue by xfliu138** [handsontable/handsontable#4203]
### Steps to reproduce

1.Using easyUI tabs function to achieve multi window display
![default](https://cloud.githubusercontent.com/assets/18605877/25118601/880a808c-2449-11e7-8d3c-41ea429b05ee.png)
2.At that time, when given to the overflow: hidden DIV attribute, 
Then move the scroll bar，
![default](https://cloud.githubusercontent.com/assets/18605877/25120001/f8d35b22-244e-11e7-84ff-ded6438fc9f3.png)

3、Then click different tab switch will cause this display bug. 
![default](https://cloud.githubusercontent.com/assets/18605877/25120060/31d7b2ce-244f-11e7-9d6c-61313cff2de6.png)

Either the table shows a mistake or jumps back to the first line

4.But this bug is normal in IE and chrome

### Demo

http://jsfiddle.net/kwV9G/242/
You can modify the code http://localhost:8000/handsontable-master3/demo/fixed.html URL to reproduce
### Your environment
* Handsontable version: 0.31.2
* Browser Name and version: Firefox 52.0.1 
* Operating System: Win 7

**Comment by AMBudnik** [comment]
Hi @xfliu138 

sorry but I wasn't able to replicate the issue. I have changed the `localhost` to https://docs.handsontable.com/pro/1.10.2/demo-scrolling.html (demo http://jsfiddle.net/9m0o8q3p/) but got few connection errors.

It is hard to propose any fix without a working demo but you can use viewport options ([viewportRowRenderingOffset ](https://docs.handsontable.com/pro/1.10.2/Options.html#viewportRowRenderingOffset) and [viewportColumnRenderingOffset](https://docs.handsontable.com/pro/1.10.2/Options.html#viewportColumnRenderingOffset)) to check if it helps. Currently, we do not support easyUI

**Comment by xfliu138** [comment]
Hi @AMBudnik Please use fixed page demo to test, you can use this url to see the effect

http://jsfiddle.net/kwV9G/243/

The test steps as follows (This problem appears in Firefox)
1. Scrolling the contents of the test2 tab
2. Click on the test1 tab
3. Finally click on the test2 tab, you can see what I call Bug

**Comment by AMBudnik** [comment]
That's an interesting case. I see what you mean. In Chrome it looks fine, but crashes in Firefox. However, I do not think that we can do much about it as we do not have any control over easyui. For example when we use Bootstrap tabs it works fine http://jsfiddle.net/handsoncode/a7cz4796/

**Comment by xfliu138** [comment]
@AMBudnik So this is an awkward and helpless problem, because it involves handsontable, Firefox and easyUI three party, and only when the overflow: hidden attribute will occur

**Comment by AMBudnik** [comment]
The table doesn't show even when we stretch the container. I can mark this topic as a bug but as it relates to other library that we do not support its priority is lower.

**Comment by wojciechczerniak** [comment]
We're doing our best but we can't be compatible with every third party lib. This should go through support@handsontable.com as a custom development. Sorry, I have to close this issue as 3rd party problem.
