### ISSUE TITLE
Scrolling with renderAllRows:true

### ISSUE THREAD

**Issue by KSandweb** [handsontable/handsontable#4205]
### Description
When you create table with option "renderAllRows: true", table won`t scroll at the cursor position.
![captured screen](https://goo.gl/mLggQ2)

### Steps to reproduce
1. Create table with option renderAllRows: true
2. Select cell in the table
3. Move selection out of the viewport using keyboard 

### Demo
http://jsfiddle.net/7symxz6L/3/

### Your environment
* Handsontable version: 1.10.1
* Browser Name and version:  IE 11, Chrome 57, Safari 10.1
* Operating System: Windows 10, OS X

**Comment by AMBudnik** [comment]
Hi @KSandweb  Can you resend the demo? It returns `404`

**Comment by KSandweb** [comment]
Sorry, my bad.

http://jsfiddle.net/7symxz6L/

**Comment by KSandweb** [comment]
@AMBudnik, demo link is fixed.

**Comment by AMBudnik** [comment]
Hi @KSandweb 

Thank you.

I have tested it using Chrome 57 on Windows 10. But I do not have the same result

![2gif](https://cloud.githubusercontent.com/assets/10757813/25277811/7c05291e-26a0-11e7-92d4-96187763d82a.gif)

and it works the same for Firefox and IE.

**Comment by KSandweb** [comment]
@AMBudnik my bad again. I forgot to paste last part of the link. The original link led to version without renderAllRows:true setting.

http://jsfiddle.net/7symxz6L/3/

**Comment by AMBudnik** [comment]
Thank you @KSandweb 

now I got the same result. I am marking the topic as a bug.

**Comment by shaludhaka** [comment]
HI AMBudnik,


Please let us know when will this be resolved.

**Comment by AMBudnik** [comment]
Of course, I will send you a note as soon as the topic will get updated.

**Comment by AMBudnik** [comment]
Hi @KSandweb 

the issue should be solved by version 0.35.0. Please update and let me know if it works for you as well.

**Comment by swistach** [comment]
I am closing this issue as there are no other questions or concerns, but if someone has any, please leave a comment.
