### ISSUE TITLE
TriggerCut not working on 1.10.x

### ISSUE THREAD

**Issue by darkmavis1980** [handsontable/handsontable#4207]
### Description
I manually trigger the cut event from my code, but while it works fine until version `1.9.1`, it does nothing on version `1.10.1` and `1.10.2`.
I simply call the method in this way:
```
hotInstance.copyPaste.triggerCut();
```

### Your environment
* Handsontable 1.10.1 and 1.10.2
* Firefox 52.0.2/53.0 and Chrome 57.0.2987.133
* Mac OS

**Comment by AMBudnik** [comment]
Thanks for sharing @darkmavis1980 
I have replicated the issue with the following demo http://jsfiddle.net/handsoncode/7w2Luoos/
When we change the version to 1.9.1 button cuts the value.

In v0.31.1 we made [some changes in the plugin](https://github.com/handsontable/handsontable/commit/e5ad4761c61f3edae416b075c043387c7e51c196) but as far as I can see only some hooks were added. We were given a new hook `afterCut` which does not trigger after we call `triggerCut();` I guess that something went wrong in this piece of change.

**Comment by darkmavis1980** [comment]
Are you using an external plugin to handle the cut/copy? Or it's managed internally?

**Comment by AMBudnik** [comment]
@darkmavis1980 It is an [external plugin](http://docs.handsontable.com/0.31.2/plugins_copyPaste_copyPaste.js.html)

**Comment by swistach** [comment]
This issue will be fixed in #4234

**Comment by swistach** [comment]
Hi @darkmavis1980, 
I've prepared demo to show you, how you can do cut manually: http://jsfiddle.net/bjdxhz4h/
More about the new CopyPaste plugin you can find here: https://docs.handsontable.com/0.33.0/demo-copy-paste.html
Feel free to reopen this issue if you find any problems with new version.

**Comment by darkmavis1980** [comment]
Thanks
