### ISSUE TITLE
Wrong number format in 0.31.2

### ISSUE THREAD

**Issue by Jampie85** [handsontable/handsontable#4208]
### Description
Wrong number format in 0.31.2
30500.90 Becomes 3.050.090,00
see euro prices on jsfiddle.

### Steps to reproduce
update to 0.31.2

### Demo
v 0.31.1 (good) http://jsfiddle.net/xz1Lppt9/2/
v 0.31.2 (bad) http://jsfiddle.net/ck02cg3u/

### Your environment
* Handsontable version: 0.31.2

**Comment by AMBudnik** [comment]
Thank you for sharing @Jampie85 

I have replicated the issue. 

**TIP**: it is gone when we re-edit the cell.

**Comment by AMBudnik** [comment]
Another example http://jsfiddle.net/xxnao9gg/ (v 1.12.0/0.33.0)

**Comment by AMBudnik** [comment]
This should work by now. The updated demo 5.0.1 http://jsfiddle.net/sbh8pf3v/
