### ISSUE TITLE
IE - scrolling when edit enabled - textbox scrolls late

### ISSUE THREAD

**Issue by JamesAshok** [handsontable/handsontable#4209]
### Description
In IE (v11 too), when editor is enabled, and when you scroll through the table, the **textbox is not scrolling along with the td element**, but scrolls a little late....
It should scroll along with td, like as though the textbox element is inside the td..

### Steps to reproduce
1. Create a handsontable with large data (just large enough for scrolling) and open it in IE
2. Enable edit on an editable cell (Press F2 or double click)
3. Without losing focus on the element, scroll thorugh the records
4. The textbox scrolls a little later than the td element.. So it is kind of awkward (just like IE itself)

### Demo
https://docs.handsontable.com/pro/1.10.2/demo-scrolling.html
Open this link in IE and do the above steps..

### Your environment
* Handsontable version: 1.9.1
* Browser Name and version: IE v11
* Operating System: Windows 10

![scroll issue](https://cloud.githubusercontent.com/assets/20744017/25324449/9505ef30-28e3-11e7-8337-1e56c8e4ce33.png)

**Comment by AMBudnik** [comment]
Thank you for sharing @JamesAshok 

Issue related to https://github.com/handsontable/handsontable/issues/2350

**Comment by swistach** [comment]
Fix in #2350 should helps.

**Comment by AMBudnik** [comment]
Great! We'll check that after release.

**Comment by AMBudnik** [comment]
Hi @JamesAshok I wasn't able to get this bug in the latest version 0.32.0-beta1. Can you test it please?

**Comment by AMBudnik** [comment]
I am closing this issue as this behavior was tested in v0.32.0-beta1 and should not occur anymore.
