### ISSUE TITLE
The `mergeCells` plugin needs refactoring.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4214]
### Description
The `mergeCells` plugin needs refactoring. It has to be rewritten in ES6, there are some tests and documentation missing, etc.

**Comment by AMBudnik** [comment]
@jansiegel please remember to add a hook before/afterMerge
related: https://github.com/handsontable/handsontable/issues/4406

**Comment by jansiegel** [comment]
Should be fixed so far:
- #3949
- #4035
- #4138
- #1722
- #4040
- #2898
- #3903
- #3342
- #4022
- #2590
- #1635
- #2958

**Comment by krzysztofspilka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Re-write of Merge Cells #4214](https://trello.com/c/SPxx77h0/85-re-write-of-merge-cells-4214)

**Comment by krzysztofspilka** [comment]
Just added a non-blocking issue: #4861

**Comment by jansiegel** [comment]
Released with `0.37.0`.
