### ISSUE TITLE
Set max-height for the table

### ISSUE THREAD

**Issue by minteliuwm** [handsontable/handsontable#4215]
Hi,
I have two problems:
first, I want to set max-height of table
second, I want to set the table auto height

My needs are as follows：
I need to implement a table , the height automatically become larger when the row of table increase .

Is it possible to solve it?
Thanks

**Comment by AMBudnik** [comment]
Hi @minteliuwm 

as mentioned here https://github.com/handsontable/handsontable/issues/487 you cannot set max width and height for the container. Currently, you can only set fixed height and width set in pixels.

**Comment by minteliuwm** [comment]
I see, and have you plan to do it ?

**Comment by AMBudnik** [comment]
We would be able to add it if we would decide to switch from TDs to DIVs but currently, it is only an idea so I cannot guarantee anything. 
However, you can check our Roadmap to see what we are doing and planning to do in nearest future https://trello.com/b/PztR4hpj/handsontable-roadmap-2017-login-to-vote

**Comment by AMBudnik** [comment]
Hey,

we've added an option in Handsontable 7.0.0 that can interest you https://github.com/handsontable/handsontable/issues/5749 
From now on we support a container with relative dimensions (%, vh, vw, rem, em)
