### ISSUE TITLE
Handsontable writes named properties that overlap with Array.prototype methods

### ISSUE THREAD

**Issue by mwojtul** [handsontable/handsontable#4217]
### Description

Handsontable is using the selections array to write named properties that overlap with built in array methods, specifically `Array.prototype.fill`:
```
selections.current = selections[0];
selections.area = selections[1];
selections.highlight = selections[2];
selections.fill = selections[3];
```
### Steps to reproduce

1. Polyfill `Array.prototype.fill`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill?v=example
2. Attempt to test HOT using a test suite such as Jasmine

### Your environment
* Handsontable version: 1.10.2
* Browser Name and version: N/A
* Operating System: N/A

**Comment by AMBudnik** [comment]
Thank you for your suggestion @mwojtul 

We have discussed the subject and as it happens only for this defined array we do not think that the behavior should be changed.

**Comment by thgh** [comment]
IE11 on Windows 7 complained about assignment to readOnly property fill.

Add `writable: true` to fix this issue:
```
if (!Array.prototype.fill) {
  Object.defineProperty(Array.prototype, 'fill', {
    writable: true,
    value: function(value) { ...
```

**Comment by AMBudnik** [comment]
Sorry I have missed the context @thgh 
when you're getting this error?

**Comment by thgh** [comment]
1. Polyfill `Array.prototype.fill`
2. Load handsontable in IE11
3. `SCRIPT5045: Assignment to read-only properties is not allowed in strict mode` https://github.com/handsontable/handsontable/blob/4a900a75ef8eba9c38dd7f4c0feca43ff495e1a4/src/tableView.js#L212

**Comment by AMBudnik** [comment]
Thank you for sharing additional details. I have to ask for help from our developers.

**Comment by wojciechczerniak** [comment]
The line was removed during our Selection refactor in February. Closing as fixed.
https://github.com/handsontable/handsontable/commit/592eae36ad331b2861f63db7ce91f074360fc96b#diff-24033f033992c272cc008ff988b20046L212
