### ISSUE TITLE
How to change row color in the afterchange event?

### ISSUE THREAD

**Issue by js321** [handsontable/handsontable#4218]
Hello,

How can I change the color of the entire row on the afterchange event? Basically, I want to make the entire row red color if the data of the cell has changed?

Thanks

**Comment by AMBudnik** [comment]
Hi @js321 

yes, you can. You need to set metadata for those cells. Here is an example http://jsfiddle.net/qgbusfcx/

**tip**: remember to call `instance_name.render()` after adding new class.

**Comment by js321** [comment]
Thanks @AMBudnik
