### ISSUE TITLE
How to hide rows if at least 1 cell is empty with checkbox?

### ISSUE THREAD

**Issue by KirillRyzhkov** [handsontable/handsontable#4219]
I want to hide rows on checkbox click.
I found the [article](https://handsontable.com/blog/articles/3-ways-to-hide-rows-in-handsontable) on how to hide rows and for the test I put the code into checkbox change event.
```
// HTML
<input id="hideEmptyRows" type="checkbox">
//JS
	$('#hideEmptyRows').change(function() {
        if($(this).is(":checked")) {
        	var countSourceRows = hotFinTable.countSourceRows() - 1;

        	hotFinTable.addHook('modifyRow', function(row) {
        		var rowOffset = 0;
        		
        		//console.log(row);
        	  
        		if (row >= 2) { // hide two rows starting at index 2 (so ID 3 and 4 are excluded)
        			rowOffset = rowOffset + 2;
        		}
        		if (row >= 7) { // hide one row starting at index 7 (so ID 10 is excluded)
        			rowOffset = rowOffset + 1;
        		}
        		row = row + rowOffset;

        		return row <= countSourceRows ? row : null;
        	});
        }    
    });

```
And doesn't seem to be working on checkbox click. The above example is just a code from the article to test it in the checkbox event.

But can you give me an idea how to check if any row has at least 1 empty cell and if this condtion applies I need to hide this row and on unchecking I need to show this row.

Maybe another option is to use customRenderer to apply CSS class for such rows and show/hide these row on checkbox click?

**Comment by AMBudnik** [comment]
Hi @KirillRyzhkov 
I have a question to this line

> But can you give me an idea how to check if any row has at least 1 empty cell and if this condition applies I need to hide this row and on unchecking I need to show this row.

Can you share more details about the checkbox placement? It is in another cell or outside the table?

**Comment by KirillRyzhkov** [comment]
Hi @AMBudnik . Checkbox is outside of the table. I managed to show/hide columns on checkbox click with hot.updateSettings({}); but can't figure out how to show/hide if the Handsontable row has at least 1 empty cell in a row.

**Comment by AMBudnik** [comment]
I guess that you would need to iterate after each cell and check, for example 

if(instance.getDataAtCell(row, col) === "")

this will return a boolean value for cell being empty or not

**Comment by KirillRyzhkov** [comment]
Thanks. But **console.log(row);** not working although **console.log(countSourceRows);**
works.
```
	$('#hideEmptyRows').change(function() { 
            if($(this).is(":checked")) {
        	var countSourceRows = hotFinTable.countSourceRows() - 1;
        	
        	console.log(countSourceRows);

        	hotFinTable.addHook('modifyRow', function(row) {
        		console.log(row);
        	});
        }    
    });
```

**Comment by AMBudnik** [comment]
@KirillRyzhkov 

could you share the code via JSFiddle? It'll be easier to test

**Comment by KirillRyzhkov** [comment]
@AMBudnik . Here is a JSFiddle https://jsfiddle.net/hawkish/z2yofoLn/ .
I need to show/hide 2nd row as it has empty value on #hideEmpty change event

**Comment by KirillRyzhkov** [comment]
I tried this
```
 $('#hideEmpty').change(function() {
        if($(this).is(":checked")) {

        	var countSourceRows = hot.countSourceRows() - 1;
          
        	hot.addHook('modifyRow', function(row) {
        		var rowOffset = 0;
           
            if(hot.getDataAtCell(row, 1) === "") {
            	rowOffset++;
            }
            
        		row = row + rowOffset;
        		return row <= countSourceRows ? row : null;
        	});
          
        }   
        hot.render();
   });
```
But got this error: **Uncaught RangeError: Maximum call stack size exceeded**

**Comment by AMBudnik** [comment]
Hi @KirillRyzhkov 

sorry for a delay. 

I'll check the code and be back to you on Monday.

**Comment by KirillRyzhkov** [comment]
Hi @AMBudnik. You can close the issue. 
```
	$('#hideEmptyRows').change(function() {
        if($(this).is(":checked")) {
        	var data = hotTable.table.getSourceData();
        	var new_data = [];
        	for(var i = 0; i < data.length; i++){
    			if(!(data[i].position_id_1=='' &&
    					data[i].value_1=='' && 
    					data[i].position_id_2=='' && 
    					data[i].value_2=='' && 
    					data[i].position_id_3=='' && 
    					data[i].value_3=='' && 
    					data[i].display_anyway==false) || i < 5){
        			new_data[new_data.length] = data[i];
    			}
        	}
        	hotTable.table.loadData(new_data);
        }
        else {
        	$.ajax({
        		url: '/en/editor/get-initial-data',
        		type: 'POST',
        		data: {
        			id: id,
        		},
        		dataType: 'json',
        		beforeSend: function(){
        		},
        		success: function (data){
                	var isset_data = hotTable.table.getSourceData();
                	json_data = {};
                	for(var i = 5; i < isset_data.length; i ++){
                		// your custom logic
                	}
        			
        			var new_data = data.data;
                	for(var i = 0; i < new_data.length; i ++){
                		// your custom logic
                	}
        			
        			hotTable.table.loadData(new_data);
        		}
        	});
        }
    });
```
I removed some custom code. But the main idea is to get initial array from server side array.

**Comment by AMBudnik** [comment]
Ohh, ok @KirillRyzhkov 

I am glad that you have solved it. I am closing the issue.
