### ISSUE TITLE
Is there an option to automatically create columns when trying to go right from the rightmost column? (or down from the bottom row)

### ISSUE THREAD

**Issue by YakovL** [handsontable/handsontable#4220]
There are `minSpareRows` and `minSpareCols` which ease adding new rows/columns when editing. However, sometimes it's convenient to create new column when just trying to move right ("right" is pressed, but not in the F2 edit mode) from the rightmost column (and automatically delete the rightmost column if it's empty and we move back to the left from it). Practically, it's excel-like experience: when we need another column, we just move to the right and start typing.

Is there an option for workflow like this or I have to implement the keypress handlers myself?

**Comment by YakovL** [comment]
PS I've almost implemented this but got [an issue](http://stackoverflow.com/questions/43721402/how-to-prevent-key-events-from-propagating-from-handsontable-after-using-stopimm) about arrow key event handling. Any help regarding it is appreciated.

**Comment by AMBudnik** [comment]
Hi @YakovL 

you mean something like this http://jsfiddle.net/6cLf9Lnx/ ?
When we reach with a selected cell to the bottom of the table it adds rows and when we reach right most column it adds columns.
If you are using object data it would need to be done by updating cells/columns option.

**Comment by YakovL** [comment]
Hi @AMBudnik, yes, I've succeeded with automatic adding (actually in a better manner: there's no empty row/column) but got an issue with automatic removing of empty columns (see stackoverflow question). Em.. I should probably rename this thread since the issue now is actually about keydown event handling/propagation. Or should I create a separate one instead?

**Comment by YakovL** [comment]
PS here's a [fiddle](http://jsfiddle.net/6cLf9Lnx/1/) with the corresponding code: just go down to create several rows and then go up: with `Handsontable.Dom.stopImmediatePropagation(event);` it also scrolls the page; without `Handsontable.Dom.stopImmediatePropagation(event);` selection jumps through a row.

**Comment by AMBudnik** [comment]
Hi @YakovL 

I have spoken with @swistach and he created a demo where there's no half-cell scrolling that was visible before. You can test it at http://jsfiddle.net/6cLf9Lnx/2/
