### ISSUE TITLE
Horizontal scroll only

### ISSUE THREAD

**Issue by PhpSriptKiddie** [handsontable/handsontable#4221]
Hey there,

How can I enable horizontal scroll without vertical scroll? When fixing the width and hiding overflow, I automatically get both scrollbars.

Thanks

**Comment by AMBudnik** [comment]
Hi @PhpSriptKiddie 

Can you tell me more about the case?

You have a fixed width/height parent and you do not want Handsontable as a child to create a vertical scroll where there's more data/rows than the parent height?

**Comment by PhpSriptKiddie** [comment]
What I would like is to set a maximum width but no maximum height.

When rows is added, the handsontable should just grow horizontally, but I would like to have a fixed width, so that a vertical scrollbar is added when table gets wider than the specified width.
