### ISSUE TITLE
[PRO] Version 1.10.2 / missing 'hot-formula-parser'

### ISSUE THREAD

**Issue by masato-io** [handsontable/handsontable#4223]
Hey guys,

Just installed pro version 1.10.2 via recommended npm install method and there seems to be a problem:
Uncaught Error: Cannot find module 'hot-formula-parser'

Any way to fix this bug by any chance?

**Comment by AMBudnik** [comment]
As mentioned in an email, if you or any developer wants for use Handsontable.js file on the project you need to load some additional scripts before the one from Handsontable. You can load handsontable.full.js to avoid it or create a custom package using hot-builder if you do not need some of the functionalities.

For all of you who would like to create a custom package I highly recommend reading this short post that we've created for hot-builder: https://handsontable.com/blog/articles/how-to-build-a-custom-version-of-handsontable

**Comment by masato-io** [comment]
Thank you for your response. To give you a full context, I was originally using non-pro version of handsontable by loading some additional scripts you mentioned with react-handsontable and  it was working perfectly. My question is, why simply replacing "handsontable" to "handsontable-pro" gives me this error which was not happening before.

**Comment by masato-io** [comment]
okay I noticed there is a separate documentation for how to use react-handsontable with handsontalbe-pro here:
https://github.com/handsontable/react-handsontable/wiki/Installation-guide#handsontable-community-edition

I followed steps, and I added:

```
module : {
    loaders : [
      // ... all the loaders from HOT CE tutorial ...
      {
        test: require.resolve('hot-formula-parser/dist/formula-parser.js'),
        loader: 'expose-loader?formulaParser'
      }
    ]
  }
```
and
```
module.exports = {
  // ...
  resolve: {
    alias: {
      handsontable: path.resolve(__dirname, 'node_modules/handsontable-pro')
    }
  },
  // ...
}
```
to my webpack, but it gives me an error:

> Error: Cannot find module 'hot-formula-parser/dist/formula-parser.js'

Any way I can resolve this?

**Comment by AMBudnik** [comment]
Yes, it may happen when you switch to PRO as CE version does not have Formulas (formula-parser is not a part of the library). Have you checked the script order on your page? Maybe you could share the code with me?

**Comment by masato-io** [comment]
Thank you @AMBudnik, I invited you as a collaborator to my repo.

**Comment by AMBudnik** [comment]
Thank you, I will check it.

**Comment by AMBudnik** [comment]
@masato-io I can see that you are using Boilerplate. We officially do not support it and I have heard from two Clients that table may not appear is some cases.

**Comment by masato-io** [comment]
hmm okay, I guess I'll try to use:
https://handsontable.com/blog/articles/how-to-build-a-custom-version-of-handsontable
and remove Formulas as it seems like the only problem.
Thanks for the help!

**Comment by masato-io** [comment]
hmm okay, thanks for the help!
