### ISSUE TITLE
Numeric formatter shows '0%'

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4224]
Hi,

I use Numeric type for cell with format equals to `0%`  http://jsfiddle.net/andrewQwer/s6t768pq/667/
Here a short summary of what I type in editor and what I get when editor is closed:
 1 - 100% - ok
1% - 1% - ok
0 - 0% - ok
0% - 0% - red cell, validation error!!

This is strange as 0% should show 0%, but not validation error.

**Comment by andrewQwer** [comment]
I found the issue,  the problem is in function `validateChanges` , row:
`changes[i][3] = numbro().unformat(changes[i][3]) || changes[i][3];`
This statement `numbro().unformat(changes[i][3])` returns 0 when user enters 0% that is treated as `false` and statement after `||` is used that returns original `0%` input.

**Comment by AMBudnik** [comment]
Hi @andrewQwer 

sorry for a delay. I am happy that you have found a solution.

Is there anything else I can do for you?
