### ISSUE TITLE
Filter the data-source of 2nd grid based on the 1st grid

### ISSUE THREAD

**Issue by js321** [handsontable/handsontable#4225]
I have two grids on a page and I want the datasource of the 2nd grid to be determined based on the 1st grid. 

Can you please suggest how can that be done?

Thank you.

**Comment by AMBudnik** [comment]
Hi @js321 

here an example I have made some time ago http://jsfiddle.net/handsoncode/kqbwpc8j/
It may come in handy. 

If you would need any other tips let me know.

**Comment by js321** [comment]
That's great - thank you @AMBudnik

**Comment by AMBudnik** [comment]
you're welcome @js321
