### ISSUE TITLE
Autocomplete not working in AngularJS 1.x

### ISSUE THREAD

**Issue by js321** [handsontable/handsontable#4229]
Hello,

I am trying to include an autocomplete on my grid in angular js. The autocomplete is working but the rest of the grid data is not showing. I've seen the example on your website - link below.

http://jsfiddle.net/28phe12e/

But still doesn't work. I tried using the data in the markup file `datarows="myDataRows"` and in the controller by using the `data` in the settings. none worked.

Please can you suggest what could I be missing?

Thanks

**Comment by AMBudnik** [comment]
Hi @js321 

I would need to see the demo with a bug to test it.

**Comment by js321** [comment]
Hi @AMBudnik 

Can't seem to reproduce this in jsfiddle. 

Do you know if the cells in Handsontable support key value pairs? i.e. if in Auto Complete I want the display to be the name but when selected the value should be the id? See example below.

```
    var nameList = [
        { id: 1001, name: "John Smith" }
    ];

```
Please let me know.

Thanks

**Comment by AMBudnik** [comment]
Unfortunately, not. We do not support key-value dropdowns yet.

**Comment by js321** [comment]
Thanks for the rapid response. Any idea if this will included anytime soon? Or are there any alternatives?

Thanks

**Comment by AMBudnik** [comment]
currently, we are fixing some issues related to performance and adding a new wrapper. I do not see any new feature on our Roadmap in May.

**Comment by js321** [comment]
Thanks @AMBudnik. Would you recommend any other alternatives?

**Comment by AMBudnik** [comment]
You could try to create a custom renderer, however, if you use filtering it may not work as the labels could show different data.

**Comment by js321** [comment]
sure - thank you.
