### ISSUE TITLE
Cells Linkage

### ISSUE THREAD

**Issue by zzzyting** [handsontable/handsontable#4231]
### Description

Hello,
I want to make two cells becoming linkage ,just like two dropdownlist.
 how could I do???

Thanks
### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @zzzyting 

I am not sure if I get the idea. Do you want to add links inside cells, like here http://jsfiddle.net/ognnLud4/? If not please share any draft, image or a demo that does what you want to achieve

**Comment by zzzyting** [comment]
@AMBudnik ,No,that is not what I need, just like the follow pictures,
when I choose "boy", the other cell become"0",  and I choose "gril",  it becomes "1",
So, how  could I do??? 

Thanks!

![11](https://cloud.githubusercontent.com/assets/25153242/25798033/2efd3d80-3412-11e7-8252-d6f329937711.GIF)
![33](https://cloud.githubusercontent.com/assets/25153242/25798095/6ae1750a-3412-11e7-8bc8-39abc2403c89.GIF)

**Comment by AMBudnik** [comment]
If you would like to set cell dependencies here is a comprehensive blog post about it https://handsontable.com/blog/articles/expand-your-app-with-cell-dependencies

When it comes to the exact example here you can test it http://jsfiddle.net/4vaa76nb/
I use `afterChange` callback to track if a user changed the first dropdown cell. Then, like in your image, if a user chooses `boy` option from the first dropdown, the second dropdown is set to `0`. But if he chooses `girl` from the first dropdown the second dropdown will set itself to `1`.

**Comment by zzzyting** [comment]
@AMBudnik ,oh well，It solved my problem！Thanks!

**Comment by AMBudnik** [comment]
you're welcome.
