### ISSUE TITLE
Table does not scroll properly when fixed area is too wide

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4232]
### Description

Table does not scroll properly when fixed area is too wide

### Steps to reproduce

1. Scroll table horizontally and vertically to see misalignment

![gif](https://cloud.githubusercontent.com/assets/10757813/25802061/ff085cca-33f0-11e7-95b4-8f1c1f739694.gif)

### Demo

http://jsfiddle.net/j1y66ssc/

### Your environment
* Handsontable version: 0.31.2
* Browser Name and version:  Chrome 58
* Operating System: Windows 10

`[issue reported at https://forum.handsontable.com/t/ui-breaking-with-fixedcolumnsleft-and-different-colwidths/848/17]`

**Comment by jakever** [comment]
I also have this problem.

**Comment by AMBudnik** [comment]
It acts differently when we comment `white-space` from the `TD` elements http://jsfiddle.net/k3ydwk8L/

**Comment by AMBudnik** [comment]
The issue has been made by ` white-space: normal;` in the `.handsontable th` element.
