### ISSUE TITLE
Rewrite plugin: CopyPaste

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4234]
### Description
We've decided to rewrite our `CopyPaste` plugin. 
New solution should work without *Flash* and for this reason, we've chosen [clipboard.js](https://github.com/zenorocha/clipboard.js)

What should be done on this issue:
- ~implement clipboardjs to support ClipboardAPI,~
- [x] remove unnecessary `lib/copyPaste` (this should be a part of plugin)
- [x] remove unnecessary `plugins/contextMenuCopyPaste` (this should be a part of plugin)
- [x] tests, tests, tests
- [x] change documentation / tutorials if would be necessary

---- update 19.05.2017 ----
We can prepare clipboard support by ourself. The one dependence less.

---- update 12.06.2017 ----
Releted issues:
- [x] #3687 
- [x] #3710 
- [x] #4281

**Comment by wszymanski** [comment]
I can see `CopyPaste` div at top of browser window after `ctrl+c` key press. JavaScript & CSS files were built by `npm run build` command. I've done also Chrome's `Empty Cache and Hard Reload` action without result. Can you reproduce it, @swistach?

![copy paste](https://user-images.githubusercontent.com/141330/27485063-965a16a0-582b-11e7-9b1f-06586eac6e2f.gif)

**Comment by krzysztofspilka** [comment]
@swistach I cannot test it in demos included in the repo. It just does't work (like I copy the data but can only paste a single blank cell).
