### ISSUE TITLE
Uncaught TypeError coming in onAfterChange Function

### ISSUE THREAD

**Issue by ankushgoel** [handsontable/handsontable#4235]
After running `hot.updateSettings` following error comes in console which breaks other functions and scripts : -

> Uncaught TypeError: Cannot read property '2' of null at handsontable.full.js:27073

Handsontable version: 1.10.2

**Comment by AMBudnik** [comment]
Hi @ankushgoel 

Can you share a demo where this can be replicable?

ps. since few versions before `onAfterChange` was replaced by `afterChange` (if you are using Vanilla version).

**Comment by ankushgoel** [comment]
https://docs.handsontable.com/pro/1.10.2/bower_components/handsontable-pro/dist/handsontable.full.js
Please check line no. 27073 where we are trying to read the value of `change[1]` without checking that if `change` is array or not

**Comment by AMBudnik** [comment]
Thank you for your suggestion. I will mark this topic as an improvement suggestion.

**Comment by AMBudnik** [comment]
Hi @ankushgoel 

I have tried to check the following case but wasn't able to replicate the issue. Do you still experience it and if so please let me know how to get the same error.

**Comment by ankushgoel** [comment]
Hey @AMBudnik 
Thanks for considering. I couldn't find it anymore, I think this has been resolved in the latest update
