### ISSUE TITLE
How to get CellB's 'Dropdown' source after CellA's value changed?

### ISSUE THREAD

**Issue by cumtwwei** [handsontable/handsontable#4236]
How to get CellB's 'Dropdown' source after CellA's value changed?

As below: 
1.CellA is a 'Dropdown' too, and his source is ['AAA','BBB'].
2.When select the CellA's value with 'AAA'.
3.Then CellB's source will change to ['AAA-1','AAA-2', 'AAA-3']; when CellA change to 'BBB', then CellB's source would change to  ['BBB-1','BBB-2', 'BBB-3', 'BBB-4']

**Comment by cumtwwei** [comment]
Help! Help! Help!
Thanks a lot.

The CellB's source is  dynamic by using ajax from Java-ServerSide with CellA's value.

**Comment by AMBudnik** [comment]
Hi @cumtwwei 

you can use `afterChange` hook and `setDataAtCell`/`cells` methods to set cell dependencies.

In our [blog post](https://handsontable.com/blog/articles/expand-your-app-with-cell-dependencies) at `Select-dependent cells` you have an exact example, where we pick a date in second columns and the dropdown in 3rd column gets changed.

**Comment by cumtwwei** [comment]
Thanks a lot. I'll try it.

**Comment by AMBudnik** [comment]
OK, give me a hint if you'd need anything else

**Comment by cumtwwei** [comment]
Hi AMBudnik,
i have seen the example: 'Select-dependent cells'. but it do not fit my problem. in my case, when change the column 'Year of production', then the column 'Owner' s source should be changed, not only change his selected value.
like this: 
1. 'Year of production'' s  source is: ['2015', '2016', '2017']
2. 'Owner' s source are: ['Jack', 'Bob', 'Same'], ['WW', 'Saddy', 'Caven'], ['VC', 'Pob', 'DJ', 'Saro']. (May be this tree array is fetched by ajax from Server-Side.)
3. when 'Year' is 2015, then 'Owner' s source is ['Jack', 'Bob', 'Same'];
    when 'Year' is 2016, then 'Owner' s source is ['WW', 'Saddy', 'Caven'];
    when 'Year' is 2017, then 'Owner' s source is ['VC', 'Pob', 'DJ', 'Saro'].

Please Help me. @AMBudnik

**Comment by AMBudnik** [comment]
@cumtwwei 

Please send me a demo (preferably in a JSFiddle) with your current progress and I'll help you to add this functionality.

**Comment by cumtwwei** [comment]
@AMBudnik 

Please see: [https://jsfiddle.net/cumtwwei/2nym49dy/4/](url)
Thanks very much.

**Comment by AMBudnik** [comment]
Hi @cumtwwei 

here it is https://jsfiddle.net/handsoncode/vsx72nL3/

I am using it in a little different way, I have added the source array like

```
  var pick2015 = ['Jack', 'Bob', 'Same'],
        pick2016 =  ['WW', 'Saddy', 'Caven'],
        pick2017 = ['VC', 'Pob', 'DJ', 'Saro'];
```
 
and then by checking `value` I use `setCellMeta` to access `source` parameter and then add `setDataAtRowProp` to get the first option from each of the arrays/sources.

**Comment by cumtwwei** [comment]
@AMBudnik 

Thanks a lot! Using your way, my problem is solved. Thanks! Thanks! Thanks!
By the way, yesterday i have read the doc carefully. but can not found the arguments's detail. just like: [setCellMeta(row, col, key, val)](http://docs.handsontable.com/pro/1.10.2/Core.html#setCellMeta), the 'key''s values(like 'source') that i coun' found. Where they are?

**Comment by AMBudnik** [comment]
Hi @cumtwwei 
I am happy that it solved the issue. 
When it comes to the docs I guess you're right I cannot find it as well.

ps. to get all `keys` you can use a console to print all value via `getCellMeta(row, col)` method, like http://jsfiddle.net/handsoncode/1zj4ohnd/
Still, it is not obvious that you can call `hot.getCellMeta(1,1).type` this way.

We should gather all available options in one place as mentioned in this topic https://github.com/handsontable/handsontable/issues/2377
