### ISSUE TITLE
Trim row plugin initialization

### ISSUE THREAD

**Issue by ankushgoel** [handsontable/handsontable#4237]
Description
Trim row plugin doesn't work without initialization in hotsettings

Steps to reproduce

1. Open first demo link, Click on Trim button
2. You will notice rows will not be trimmed
3. Now open second demo and click on the trim button
4. Row will be removed.

Demo
http://jsfiddle.net/ankushgoel/bhrc65jh/1/

http://jsfiddle.net/ankushgoel/bhrc65jh/3/

**Comment by AMBudnik** [comment]
Hi @ankushgoel 

you need to enable the plugin to use it.

You can send an empty array like here http://jsfiddle.net/handsoncode/s0rodevL/ and then proceed with your calculations.

**Comment by ankushgoel** [comment]
I guess I am enabling the plugin by using this `var trimRowsPlugin = hot.getPlugin('trimRows')`

**Comment by AMBudnik** [comment]
Hi @ankushgoel 

By the following line

`var trimRowsPlugin = hot.getPlugin('trimRows')` 

you are only calling a plugin but not enabling it. By calling a method that belongs to a plugin, like the line below

`trimRowsPlugin.trimRows([1, 2, 5]);`

you are also not enabling the plugin, so as mentioned before you need to pass an empty array or [`true`](http://jsfiddle.net/handsoncode/cktu8c39/) via `trimRows` option in table initialization settings.

**Comment by ankushgoel** [comment]
hi @AMBudnik ,

I am sorry for troubling you, but I was unable to find this in documentation that's why I asked.
Thanks for your help, I know it now, but maybe some users might still be unaware.

**Comment by AMBudnik** [comment]
That's OK @ankushgoel the board is here to help and report some issues :)

**Comment by ankushgoel** [comment]
@AMBudnik I guess it's lacking documentation, If you could add it documentation that would be great.

**Comment by AMBudnik** [comment]
@ankushgoel 
thank you for your suggestion.
Currently, our documentation has a lot of data but the structure and browsing need some reorganization. We are planning to change how you browse in the docs section this year. After changes, you 'll be able to get related topics, not only the exact query.
