### ISSUE TITLE
Flickering in Safari under larger table (40 cols x 100 rows) when scrolling

### ISSUE THREAD

**Issue by mmucklo** [handsontable/handsontable#4238]
When a table is loaded with 40 columns and 100rows in Safari, there's a noticeable flicker of the header when scrolling:

http://codepen.io/travisraghib/pen/aWLrxN

Sometimes it seems as if the header is rendering half-way down the grid for a split second or so.

**Comment by AMBudnik** [comment]
Hi @mmucklo 

if we are talking about a table with `40` columns and `100` rows you can use offset options. Please try adding

`viewportRowRenderingOffset: 100, viewportColumnRenderingOffset: 40`

and let me know if it helps.

**Comment by AMBudnik** [comment]
I am closing this issue as there are no additional questions. If you'd find anything concerning @mmucklo  please let me know.

**Comment by mmucklo** [comment]
We're actually still seeing issues with the top and side headers jumping around...

https://codepen.io/travisraghib/pen/aWLrxN

When running this on Safari 10.1.2 the top header and the left "row" header column jumps a lot and is quite disconcerting from a usability standpoint...

Please advise,

--Matt

**Comment by AMBudnik** [comment]
You are right @mmucklo 
I am reopening the issue

**Comment by wojciechczerniak** [comment]
The flickering header which was rendering half way down the grid was addressed in #4994 an released with v2.0.0.
