### ISSUE TITLE
Freeze unfreeze unusable for soooo many versions now due to every time other bugs

### ISSUE THREAD

**Issue by perfectum2k** [handsontable/handsontable#4239]
### Description
When you freeze a column the indexes change (1st column will get 2nd and so on). Sadly the 1st column will now also recieve the width of the 2nd column, regardless of its size before. Also the header of the column does not get updated and column A is now called column B.

I would use an older version as in 31.1 it actually worked... but there the unfreeze function messes up the column titles if I remember correctly (no entirely certain but there was something why I couldn't use unfreeze with v31.1)

The freeze function seems to be in handsontable for ages (v15 I think) and I tried many different versions, but none worked usable for me sadly (funny thing is that each version has it's own bugs that were different to the ones from previous versions).

### Steps to reproduce
Explained and visible easily in the demo

### Demo
I created an example where column A and C (with contents '1' and '3') are small while the rest are wider. If you freeze column C you will see that the titles still remain the same (the frozen column C should be at the start but is still shown at the old position. As well the content of column B is now stuck in a way too small column as it moved one column to the right which is still having the same small size as before...

See jsfiddle here:
<a href='http://jsfiddle.net/uwwfz60p/3/' target='blank'>fiddle</a>

### Your environment
* Handsontable version: 31.2
* Browser Name and version: Chrome v57.0.2987.133 
* Operating System: Windows 10 pro 64bit

**Comment by AMBudnik** [comment]
Hi @perfectum2k 
If you set `colHeaders: true` the grid will always show headers automatically (they do not bound to the data beneath). If you share any array via `colHeaders` the headers will bind to data.
Here http://jsfiddle.net/handsoncode/w7cx3nLq/ I have made an example where the headers are exactly the same visually (`A`, `B`, `C`, ...) but as they are passed via array they move with fixed data.

Please let me know if this solves the issue and if I understood the request correctly.

**Comment by perfectum2k** [comment]
Thanlk you very much for your reply. Sadly this does not solve the issue that the column widths are not bound to the columns.

E.g. If i freeze column C in your example, indeed now the header of column C is now as well in the front, but still Column A is wide and C is small while it was different at the start (and usually you want the cell width fitting to the content) ;)

Handsontable is a great piece of work and I really do not want to make it any worse than it is, but this is a function that just seem to be bugged through a loooong dynasty of versions and someone really needs to take the time to make it usable and solve all the (admittingly nasty) details - otherwise you can as well scratch the feature from the list and could have saved tons of wasted time ;)

**Comment by AMBudnik** [comment]
Yes, now I get it! It is all about keeping the width of moved or fixed column. We already have the issue at https://github.com/handsontable/handsontable/issues/2780 I have changed the label from `change` to `bug`.

You're right, to get it working you would need to work on the `colWidths` array via `afterColumnMove` hook (which also is triggered after freezing columns). Then replace the value at certain index and then move other indexes to left or right. It is pretty much complicated.
