### ISSUE TITLE
Feature request: Error highlight when entering/pasting wrong data when strict autocomplete is enabled

### ISSUE THREAD

**Issue by ravio** [handsontable/handsontable#424]
When user pastes large set of data and there is auto complete in strict mode enabled for multiple columns the data does not set. Here the user may be largely unaware as where the error might be.
Here error highlighting in the cells can be useful. 

I saw a workaround in one of the topics (only works in strict mode with ajax calls) but would like this to be at the heart of handsontable.

**Comment by AMBudnik** [comment]
Issue closed in lack of reply from the author.
