### ISSUE TITLE
why 'minSpareRows' can not work with 'afterCreateRow' ?

### ISSUE THREAD

**Issue by cumtwwei** [handsontable/handsontable#4240]
### Description
i want to set a default value for first cell with the row index, just like '1#','2#','3#','row#'
when i set 'minSpareRows: 1'. then there got some error.
the code is:[jsfiddle](https://jsfiddle.net/cumtwwei/dcsx5w0g/)

Thanks a lot!

**Comment by AMBudnik** [comment]
Hi @cumtwwei 

Is this the demo you wanted to share? I do not see any data populating methods or `minSpareRows` settings.

ps. What type of errors do you get?

**Comment by cumtwwei** [comment]
@AMBudnik 

sorry, i have copy an wrong url. but now, i have solved by other way by using 'afterCreateRow' to set the first cell'value.
thanks.
