### ISSUE TITLE
It will occur repeated data after copying data using 'select all'

### ISSUE THREAD

**Issue by jakever** [handsontable/handsontable#4241]
### Description
Repeated data will appear after copying some data with select all the handsontable instance;

### Steps to reproduce

1. Copy some data from the excel using 'Ctrl + C',  make sure your copy data is less then default rows of handsontable;
2. Select all the handsontable instance using 'Ctrl + A', now all cells has been selected;
3. paste the data using 'Ctrl + V';
4. Check the data, will appear repeated data;

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @jakever 

It is an intended behavior. Pasting, in this case, works the same as you can experience in Google Spreadsheet.

**Comment by jakever** [comment]
I tried it on Google Spreadsheet, it doesn't occurred this problem, suppose that you has copy two rows data, and enter 'ctrl+A', then paste the data, that two rows data will repeated until the spreadsheet is full-filled.

**Comment by AMBudnik** [comment]
Sorry, I wrote it wrong, when you copy data between the sheets it pastes data in all selected cells but when you copy data from Excel to another program you get only copied cells.
We will discuss the subject as it may be used by some users as a feature. In some cases when you select a range of data you are expecting to get data populated in this area, however, that you for sharing this subject.

**Comment by abhijeet2083** [comment]
It will be nice to make this feature configurable.

**Comment by AMBudnik** [comment]
I am changing the issue label from `change` to `feature` as I am not sure if the behavior is something that you would not expect. Like @abhijeet2083 wrote - it should be configurable

**Comment by AMBudnik** [comment]
The issue has been redirected to the[ Wiki section / feature requests](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by jakever** [comment]
Got it! Thanks!

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
