### ISSUE TITLE
Increase height automatically when insert row

### ISSUE THREAD

**Issue by pkaminiv** [handsontable/handsontable#4242]
### Description
I want to increase height of handsontable automatically when insert row. I have tried to applied max-height of div and set overflow:hidden but still not working. let me know how i increase height of table automatically.

### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @pkaminiv 

currently, we have only a fixed [height ](https://docs.handsontable.com/pro/1.10.2/Options.html#height)value for a Handsontable instance. You may update the value via `afterCreateRow` hook, however, you would need to track how height is the cell - if the data gets longer and cells content will split into two lines then the workaround won't work.

**Comment by AMBudnik** [comment]
Hey,

we've added an option in Handsontable 7.0.0 that can interest you https://github.com/handsontable/handsontable/issues/5749 
From now on we support a container with relative dimensions (%, vh, vw, rem, em)
