### ISSUE TITLE
Can not set cell'source by using 'beforeCreateRow' event. Please Help.

### ISSUE THREAD

**Issue by cumtwwei** [handsontable/handsontable#4243]
at the begin, the cell's source value is empty array.
then, get the source value by using ajax from server-side.
so, try to use 'beforeCreateRow' event to reset the cell's source value.
but, can not set it.
the demo is here: [http://jsfiddle.net/cumtwwei/1w1438kL/3/](http://jsfiddle.net/cumtwwei/1w1438kL/3/)

Help！Help！Help！

@AMBudnik

**Comment by AMBudnik** [comment]
Hi @cumtwwei 
I am not sure if I get the idea. You want to have an empty `select` cell and after an operation x change the list of options for this `select` cell?

**Comment by cumtwwei** [comment]
@AMBudnik  
not all, when init the hottable, the select's option is empty which is set by an ajax request. when the ajax return datas, then use the data to  set the select's option.

**Comment by AMBudnik** [comment]
OK, so maybe something like this http://jsfiddle.net/handsoncode/0d1yymow/ ?

**Comment by cumtwwei** [comment]
@AMBudnik 
Nice Job！
It's OK now.
Thanks a lot.

**Comment by AMBudnik** [comment]
@cumtwwei you're welcome
