### ISSUE TITLE
Manual resizing by cell, not by header

### ISSUE THREAD

**Issue by YakovL** [handsontable/handsontable#4244]
So, currently, as far as I understand, manual resizing may only be enabled by using `manualColumnResize` (or `manualRowResize`) option which makes handsontable behave like another spreadsheets: the resize bar is shown on hover of a column header.

Now, I need a table without column headers but still I would like to be able to manually change their widths. As far as I understand, there's currently no such option. If I'm wrong, please show how to enable it. If I'm right, it's a feature request.

What's expected: I'd say the resizing bar shoudn't appear (be visible) in a cell, but rather be transparent and cursor should become `col-resize` when it's close to a vertical cell border (and "drag-and-drop" should lead to resizing).

**Comment by AMBudnik** [comment]
Hi @YakovL 

resizing is bound to column headers so you cannot use the resizing option with disabled headers.

**Comment by YakovL** [comment]
Right, so in this case it's a feature request.

**Comment by AMBudnik** [comment]
Sure, we can mark it as a feature request.

**Comment by AMBudnik** [comment]
The idea has been approved added to our [wiki section for the Feature Requests](https://github.com/handsontable/handsontable/wiki/Feature-requests). 
Again thanks for sharing.

**Comment by challakoushik** [comment]
Any updates on this?

**Comment by AMBudnik** [comment]
Sorry, no updates yet @challakoushik 

That feature will be very challenging as currently (as I wrote above) this feature relates on headers (mostly on UI).

**Comment by craigbenstock** [comment]
+1 - we require the same functionality!

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
