### ISSUE TITLE
Misalignment of the overlays after change colHeaders by updatesettings several times

### ISSUE THREAD

**Issue by minteliuwm** [handsontable/handsontable#4245]
### Description
First, chang colHeaders by updateSettings({...}) and one of headers has more lines than before,
Then, chang colHeaders by updateSettings({...}) and all headers has less lines than before.
You can see the height of colHeader is not change the second time.

### Steps to reproduce

1.Go to the demo

### Demo
https://jsbin.com/fifabob/edit?html,js,output

### Your environment
* Handsontable version:0.31.2
* Browser Name and version:Chrome 56.0.2924.87
* Operating System:Windows 10

I am sorry for so long to come back，and [this ](https://github.com/handsontable/handsontable/issues/4201) is a similar post has been closed.
This problem has always existed, and I don't know how to solve it.

**Comment by AMBudnik** [comment]
Thank you for sharing the demo @minteliuwm 

I think that it is strongly connected to https://github.com/handsontable/handsontable/issues/3186

**Comment by minteliuwm** [comment]
I don't think so, see demo https://jsbin.com/ciwesuf/1/edit?html,js,output
columnHeaderHeight can be right with updateSettings

**Comment by AMBudnik** [comment]
They are both connected as when Handsontable makes header higher it does not shrink it no matter which operations we have chosen to widen it up. It is always wise to gather some tips and suggestions for devs to consider while checking the issue, so if you have any please share @minteliuwm

**Comment by minteliuwm** [comment]
I have a switch button, and I have a two status to show in my ColHeaders, so I want to set the colHeaders height resizable.Now I only calc the height of colHeaders, and updatesettings to modify the height of colHeaders. I think it's not a good idea.

**Comment by swistach** [comment]
Hi @minteliuwm, 
Although you use other steps to reproduce this bug, #4648 is the same issue - related to incorrect work of `oversizedColumnHeaders` in WalkOnTable.

I close this issue but feel free to join the discussion in #4648. There you can also track work progress.
Thank you for your help in improving Handsontable!
