### ISSUE TITLE
Trouble mapping data in beforeCopy

### ISSUE THREAD

**Issue by judemoutiez** [handsontable/handsontable#4247]
### Description
I would like to copy cells from my Handsontable to Excel and modify the copied data to replace all points by commas.

I am using the beforeCopy hook ([https://docs.handsontable.com/0.31.2/Hooks.html#event:beforeCopy]()) which allows me to access the data I'm about to copy.

I've managed to push new elements or splice the array, but when I try to map the data, the modifications are not taken into account.

Here is the hook I am using

`    beforeCopy: function(data, coords){
         data.map(function(row){return ...})
      }
`

### Steps to reproduce

1. Copy data
2. Apply a splice function to return data within the hook, and also a map function
3. Paste in Excel. The splice works but not the mapping

### Your environment
* Handsontable version: 0.31.1
* Browser Name and version: Chrome 58.0.3029.110
* Operating System: Max OS Sierra 10.12.3

Thanks for your help !

**Comment by ryanj-openquire** [comment]
I believe the problem is because data.map returns a new array, where you really need to update the 'data' input array passed in.

**Comment by judemoutiez** [comment]
Thanks a lot !

**Comment by AMBudnik** [comment]
Sorry for a delay. However, I can see that you have already managed to find an answer
