### ISSUE TITLE
I want to hide the context menu containing freeze/unfreeze from the first column...

### ISSUE THREAD

**Issue by apanigr** [handsontable/handsontable#4248]
I want to hide the context menu containing freeze/unfreeze from the first column.I have tried hiding the freeze /unfreeze menu but the header is still populating in the first column .please let me know to hide the complete context menu from the first column in the hot table?
### Your environment
* Handsontable version:
* Browser Name and version:chrome
* Operating System:windows10

**Comment by AMBudnik** [comment]
Hi @apanigr 

you can use the `hidden` function for contextMenu. Here http://jsfiddle.net/handsoncode/m22wcxv7/ is an example that uses this option.
