### ISSUE TITLE
How to make horizontal scroll bar appear in handsontable

### ISSUE THREAD

**Issue by dolly-bansal9** [handsontable/handsontable#4249]
### Description
I am using handsontable to show data with multiple columns and rows, I don't want to fix the height of handsontable , but I have a fixed width of the columns in handsontable, I am getting vertical scroll bar without any issues , but not able to get horizontal scroll bar. due to which when the user minimizes the window , half of the table appears before him and half is gone which is not good as a user experience. 
could you please help me to fix this issue ? 

### Steps to reproduce

1.  take handsontable with following settings
data: $.parseJSON(ganttData),
                    minRows: 0,
                    colWidths: [150, 0.01, 50],
                    minSpareRows: 0,
                    autoWrapRow: false,
                    colHeaders: true,
                    manualColumnResize: true,
                    contextMenu: true,
                    stretchH: 'all',
                    readOnly: true,

in this case the number of rows appear before user are around 50 and can vary for different screens. 

but when the user minimizes the window he  can only see half of the table and other half is not visible , also horizontal scroll bar doesn't appear , if the horizontal scroll bar could appear the user can scroll horizontally to see the entire table. 

Can some one help here ? 
2.
3.

### Your environment
* Handsontable version:Handsontable 0.8.15
* Browser Name and version: IE 11
* Operating System: windows 7

**Comment by AMBudnik** [comment]
Hi @dolly-bansal9 

Currently, we do not work on percentage values so if a user changes the width or height of the window the table will look the same as before. The only way to make it follow in width with the window size is to use `stretchH` option. Here is an example https://docs.handsontable.com/pro/1.11.0-beta1/demo-stretching.html
