### ISSUE TITLE
Rows heights get staggered/offset when multi-line on 4k resolution

### ISSUE THREAD

**Issue by JakeGrice** [handsontable/handsontable#4252]
### Description
The "row number" column on the left should be perfectly aligned row-for-row with the "content" area of each row. However, with a 4k resolution (3840x2160) which uses 150% ui scaling as standard (1.5 pixel ratio in the browser), when contents of a cell wraps or is multi-line, it causes the height of the first column to be offset with the rest of the cells in that row. The effect then stacks causing more and more offset for each subsequent multi-line row.

### Steps to reproduce
1. Use 3840x2160 resolution with 150% ui scaling in Windows 10.
2. Go to a handsontable demo site (i.e. https://handsontable.com/examples.html?headers)
3. Populate one or more rows with multi-line content

### Demo
Screenshot attached
<img width="638" alt="handsontable-4k" src="https://cloud.githubusercontent.com/assets/3504661/26170014/de3f3954-3b0d-11e7-9dc9-59cfa25cd46b.PNG">
Note in the above screenshot, the very first column.

### Your environment
* Handsontable version: 0.32.2
* Browser Name and version: Chrome 58
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing. This is what I got on Windows 10 / Chrome 58
version: 0.32.0-beta2 (but I got the same with 0.31.2)
![image](https://cloud.githubusercontent.com/assets/10757813/26442597/82693fd4-4135-11e7-9191-727521ba03c8.png)

**Comment by AMBudnik** [comment]
related https://github.com/handsontable/handsontable/issues/3118

**Comment by AMBudnik** [comment]
I still get the same result in v 5.0.1

**Comment by swistach** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of Interoperability problems using zoom/system UI scaling and some core features task reported at #7527 

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behaviour feel free to contact me at
