### ISSUE TITLE
configure 'dropdown menu' per column

### ISSUE THREAD

**Issue by HaroldStruwig** [handsontable/handsontable#4253]
1. Is it possible to have a different dropdown menu for different columns?
2. Is it possible to only have a dropdown menu on specific columns?

**Comment by AMBudnik** [comment]
Hi @HaroldStruwig 

Yes, it is possible to have some options only visible for some columns. Please take a minute to check this demo http://jsfiddle.net/handsoncode/nrxknn4q/
To do this you just need to pass index for a column via `hidden` option. You can also make some options disabled http://jsfiddle.net/handsoncode/qx6tfkx6/

However, if you **cannot** hide all options for some columns (hide dropdown menu for the columns). You could try `hidden` option mentioned before but that loads a gray line (reported as a bug, relates to the context menu as well) which is possibly a an empty div with border.

![image](https://cloud.githubusercontent.com/assets/10757813/26200257/9748da26-3bcd-11e7-80f0-6b63933f68a2.png)

**Comment by HaroldStruwig** [comment]
@AMBudnik - Thanks for the answer. 

For question 1 it seems to be a valid way of doing it - it could be easier to use if one could specify it as part of the ```columns``` property for each column. For question 2 I wanted a solution to not even show the arrow icon for some columns.

**Comment by AMBudnik** [comment]
Hm... I guess that actually there's one really hacky way to hide the dropdownMenu button for some columns. You could use the `afterGetColHeader` to modify the header's body.

Here's a basic example http://jsfiddle.net/handsoncode/Lf6orc36/
However, it will break sorting if you are using it. I did not test it with sorting, but as far as I have checked something similar before you would need to slice some parts of the header's content. So, if you're not using sorting this should work fine.

When it comes to declaring the options via `columns` I have to say that this is an interesting idea.

**Comment by AMBudnik** [comment]
Hi @HaroldStruwig 

did you manage to test the following case with disabling some dropdownMenu buttons?

**Comment by HaroldStruwig** [comment]
Hi @AMBudnik - it works but it is a very hacky approach as you stated - I think a feature to do this built into HOT would be useful.

**Comment by AMBudnik** [comment]
Yes, definitely.
I will mark this post as a `feature request`.

**Comment by ericcch** [comment]
For interim solution, I made some modification on the example shared by @AMBudnik to support column headers. http://jsfiddle.net/Lf6orc36/2/

**Comment by AMBudnik** [comment]
Thanks for sharing @ericcch

**Comment by AMBudnik** [comment]
The issue has been redirected to the[ Wiki section / feature requests](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by AMBudnik** [comment]
Here https://jsfiddle.net/handsoncode/fwma1t7L/ is an example of setting up a dropdown menu per column.

**Comment by HaroldStruwig** [comment]
@AMBudnik Is it still not possible to have different dropdown menu features available for different columns? For instance for column 1 I want to use `'filter_by_condition'` and for column 2 use `'filter_action_bar'`

**Comment by AMBudnik** [comment]
Hi @HaroldStruwig Here https://handsontable.com/docs/context-menu/#context-menu-with-specific-options are the possible keys to be used in context-menu and dropdown-menu (with some slight changes). 

It is not well explained in the documentation yet I made a small draft of what do keys do.

![Zrzut ekranu 2022-03-30 o 13 29 40](https://user-images.githubusercontent.com/10757813/160824714-2680f4a4-3e6f-4cc5-836f-34face146524.png)

The `filter_action_bar` is required as without it the user will not be able to confirm the choice of filter.

When it comes to the key declaration for different columns at the moment you can choose options to be hidden for certain columns based on their index. Here http://jsfiddle.net/ou8wmby6/3/ is the simplest form where we have 2 options and one of them is hidden via `hidden` key for index `0`.
