### ISSUE TITLE
Writing custom editor (change the way in which custom cell types are being registered)

### ISSUE THREAD

**Issue by SergeyShablenko** [handsontable/handsontable#4254]
After update it became impossible to write custom editor, i have an error 
```
'handsontable.full.min.js:273 Uncaught (in promise) Error: You declared cell type "autocomplete2" as a string that is not mapped to a known object. Cell type must be an object or a string mapped to an object in Handsontable.cellTypes'
``` 

```js
function autocomplete2(Handsontable) {
  const AutocompleteEditor = Handsontable.editors.AutocompleteEditor;
  const Autocomplete2Editor = AutocompleteEditor.prototype.extend();

  Handsontable.editors.Autocomplete2Editor = Autocomplete2Editor;
  Handsontable.editors.registerEditor('autocomplete2', Autocomplete2Editor);
  Handsontable.renderers.Autocomplete2Renderer = function Autocomplete2Renderer(instance, TD, row, col, prop, value, cellProperties) {
    // some code
  };
  Handsontable.renderers.registerRenderer('autocomplete2', Handsontable.renderers.Autocomplete2Renderer);

  Handsontable.Autocomplete2 = {
    editor: Handsontable.editors.Autocomplete2Editor,
    renderer: Handsontable.renderers.Autocomplete2Renderer,
    validator: function autocomplete2Validator(value, callback) {
       //some code
    }
  };

  Handsontable.cellTypes.autocomplete2 = Handsontable.Autocomplete2;
}(Handsontable);
```

### My environment
* Handsontable version: 0.32.0-beta1
* Browser Name and version: Google Chrome Version 58.0.3029.110 (64-bit)
* Operating System: Ubuntu 16.04 LTS

**Comment by pdemilly** [comment]
Same problem here. It seems that expandType has changed and now instead of looking at handsonTable.cellTypes it is looking at a private variable _cellTypes2 (I guess from an import of CellTypes) which only contains the default cellTypes. So no way to add new cellTypes.

If you pass an object to type in the column definition you can go a little further but then it breaks further down as it requires types to be a string.

**Comment by AMBudnik** [comment]
Thank you for sharing guys.
I am marking this issue with the `high` priority.

**Comment by krzysztofspilka** [comment]
We plan to update Handsontable to beta2(?) on Monday, May 22, with this fix included.

**Comment by AMBudnik** [comment]
@SergeyShablenko @pdemilly 

Thank you for sharing this issue. I hope that the version 0.32.0-beta2 will meet your requirements. Can you check that one, please?

**Comment by budnix** [comment]
Hi guys,

We've released a fix in 0.32.0-beta2. In that release, we improved the API which gives you an ability to register a new custom cell type in the following way:
```js
Handsontable.cellTypes.registerCellType('my-custom-select', {
  editor: MyCustomSelectEditor,
  renderer: MyCustomSelectRenderer,
  validator: MyCustomSelectValidator,
});
```

and that's it. In Handsontable configuration it will be available as:
```js
new Handsontable(element, {
  data: data,
  columns: [{
    data: 'id',
    type: 'my-custom-select'
  }, {
    data: 'id2',
    editor: 'my-custom-select' // An alias for editor is automatically registered
  }, {
    data: 'id3',
    renderer: 'my-custom-select' // An alias for renderer is automatically registered
  }, {
    data: 'id4',
    validator: 'my-custom-select' // An alias for validator is automatically registered
  }, {
  }],
});
```

Can you confirm that everything works as expected with your codebase?

**Comment by SergeyShablenko** [comment]
Bug with editor fixed, but i have now next error, i assume it`s because my editor extends AutocompleteEditor
![image](https://cloud.githubusercontent.com/assets/13334277/26501956/bd8a152a-4243-11e7-91d7-2c62c6dc2c79.png)

**Comment by AMBudnik** [comment]
Hi @SergeyShablenko 

thank you for a quick reply.

Could you send a demo or anything that will allow us to replicate the issue?

**Comment by AMBudnik** [comment]
@SergeyShablenko 

Please let me know about the issue or create a new topic.
