### ISSUE TITLE
Wrong variable in listener of the mouse wheel event.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4255]
### Description
In #2350 was added a tiny workaround for scrolling in other browsers than Chrome and Safari. Unfortunately, instead of `this.view...` I've used `hot.view...` and it is a cause of exceptions when someone tries to use a mouse wheel.

### Steps to reproduce
1. Try to use mouse wheel to scroll

### Demo
https://docs.handsontable.com/0.32.0-beta1/demo-scrolling.html

### Your environment
* Handsontable version: 0.32.0-beta1
* Browser Name and version: others than Chrome/Safari

**Comment by swistach** [comment]
Many thanks 🕵️‍♀️ @AMBudnik for your vigilance!

**Comment by AMBudnik** [comment]
It works! Thanks @swistach

**Comment by michaelchiche** [comment]
@swistach @AMBudnik  the fix works for vertical scrolling. But in IE 11 on Windows 7, the horizontal scroll is still broken: https://docs.handsontable.com/0.32.0-beta2/demo-scrolling.html

**Comment by AMBudnik** [comment]
@michaelchiche can you share more details (we will open a new issue). Do you experience lagging, jumping or any other issues?

I have checked the demo you've sent with <kbd>SHIFT</kbd> + mouse scroll and I got unusual result - table scrolls vertically on IE but horizontally on other browsers. [I've raised an issue](https://github.com/handsontable/handsontable/issues/4276) for that as well.

**Comment by michaelchiche** [comment]
@AMBudnik the horizontal scrolling simply does not work when using the mouse scroll on IE 11 in Windows 7 as said in my previous comment.

The issue happens with or without pressing `SHIFT `. When I try to scroll to the right of the sheet/table, nothing happens in the environment (E 11 in Windows 7)
