### ISSUE TITLE
Handsontable cell is focusing, when focus in another input 

### ISSUE THREAD

**Issue by minteliuwm** [handsontable/handsontable#4257]
### Description
I have a handsontable with outsideClickDeselects: false (I really need this option is set to false), and jquery ui dialog. When I select any cell in handsontable and showing my dialog (by pressing button) and trying to press in my input on dialog by mouse focus is setting to selected cell in handsontalbe.

### Steps to reproduce
1.Go to the demo

### Demo
https://jsbin.com/jutosu/edit?html,js,output

### Your environment
* Handsontable version: 0.31.2
* Browser Name and version: Chrome 58.0.3029.110
* Operating System: Operating System:Windows 10

**Comment by AMBudnik** [comment]
Hi @minteliuwm 

Can you confirm that this issue relates to the following issue that was posted at https://github.com/handsontable/handsontable/issues/401

**Comment by minteliuwm** [comment]
yeah, and I want to know how to solve it.

**Comment by AMBudnik** [comment]
As this issue relates to the same subject as @401 I need to close. Unfortunately, I see that we did not prepare a fix for this issue yet.
