### ISSUE TITLE
change cell colors Conditional

### ISSUE THREAD

**Issue by zzzyting** [handsontable/handsontable#4258]
following pictures ,
when  the cell editing ,the other cell 'backgroundcolor  should  be change

![2](https://cloud.githubusercontent.com/assets/25153242/26300828/da5a75d0-3f11-11e7-9609-771de40020f7.png)
![3](https://cloud.githubusercontent.com/assets/25153242/26300834/e0055982-3f11-11e7-8066-0a2b6e4558cb.png)

thanks!

**Comment by AMBudnik** [comment]
Hi @zzzyting 

I am not sure if I get the idea. Normally when you edit a cell the background is white even if you have added the background to a different color, example: http://jsfiddle.net/handsoncode/rvunhszx/ Currently we do not have callbacks for opening an editor.
