### ISSUE TITLE
Formulas not working for Formatted Cells

### ISSUE THREAD

**Issue by chirag-compro** [handsontable/handsontable#4260]
### Description

When a formula is applied to a cell whose formatting type is set to numeric, the formula doesnot get apllied, instead the value stored for the cell is changed to numeral part of the formula
### Steps to reproduce

1. Run this Fiddle http://jsfiddle.net/0jcddp6v/ 
2. Apply formula "=C1" to any Cell under column check
3. Double click the edit cell on which the formula is applied.
4. We can see that only the numeral part of the formula i.e "1" is present in the cell.
5. Perform action 2 and 3 for any cell under column Year, we can see the value for the referred cell (C1) i.e 7000 is set for the cell 

### Demo

http://jsfiddle.net/0jcddp6v/

### Your environment
* Handsontable version: pro/1.11.0-beta1
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Thank you for sharing @chirag-compro 

I have replicated the issue

**Comment by chirag-compro** [comment]
@AMBudnik how can I move further to solve this bug. I have a solution for it. Should I share it with you so that you can review it and I can integrate it locally or should I generate a pull request for the same.

**Comment by AMBudnik** [comment]
Hi @chirag-compro 

I am afraid that you would need to fix it only in your project as we cannot accept pull request/code reviews for the PRO version. However, we would appreciate all tips that will help us solve it on our side.

**Comment by AMBudnik** [comment]
Hi @chirag-compro 

I want to make an update on this issue.

I have an updated demo (v 5.0.0) http://jsfiddle.net/ju8ws6bd/
When I copy the `=C1` inside the column `A` it copies the value but doesn't copy formatting. Was that the issue or I forgot about something important?

**Comment by chirag-compro** [comment]
Hi @AMBudnik 
The issue was not regarding the formatting not being applied for the copied value. But instead was regarding the issue for numeric format. i.e When formula is applied to any cell havinf numeric format. the formula is not applied correctly. However currently I am not able to replicate the issue in fiddle. As the provided version pro/1.11.0-beta1 is not available and the current v50 is being provided instead.
I believe the issue has been fixed in hte version pro v5.0. 
In case of any clarification you can contact me at chirag94.ck@gmail.com

**Comment by AMBudnik** [comment]
Thank you for checking that @chirag-compro 
The most important is the fact that we both cannot replicate the issue on v 5.0.0 so I believe that we can close the issue.
