### ISSUE TITLE
Allow dynamic hide elements in contextMenu

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4262]
### Description
At the moment we can dynamically add `disabled` parameter for `contextMenu` items which effect to disabling the menu options. We should have an opportunity to hide and show elements from the menu by handling items `hidden` parameter.

**Note**: It will be used for handling visibility of components which are inside `dropownMenu` (within task #3660) 

### Steps to reproduce

1. Open demo: http://jsfiddle.net/wojciech/507q126a
2. Open contextMenu by right click.
3. Wait for hiding menu elements (timeout fire action).

### Demo

http://jsfiddle.net/wojciech/507q126a

**Comment by wszymanski** [comment]
We stopped to add this functionality. 

What was done:

- rewritten renderer (named `menuItemRenderer` - removed some unnecessary DOM operations)
- rewritten hooks (now we don't add a new hook at each rendering)
- rewritten keyboard navigation (we don't check DOM elements to determine if selecting the menu item is possible)

What need to be changed:

- new `updateItems` function - `hot.loadData` override `cellMeta` so a change of menu data is not that easy although new hot's `cell` and `data` properties were calculated.

**Comment by VenubabuSunkara** [comment]
How to add cell edit mode(textarea.handsontableInput) right click show context menu. Please help me how can i implement this feature.

I Excel we have this feature

**Comment by AMBudnik** [comment]
Hi @VenubabuSunkara 
this request doesn't seem to be related to the issue subject. Can you write me at support@handsontable.com and share the issue description?

**Comment by AMBudnik** [comment]
I am reopening this topic as it has a rich history of comments and at the same time, it hasn't been released yet.

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
