### ISSUE TITLE
setDataAtCell() in custom renderer with AutoColumnSize plugin enabled causes exception

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4263]
### Description

Using a custom renderer to set the data for a cell using the setDataAtCell() method with the AutoColumnSize plugin enabled causes an exception.

### Steps to reproduce

1. Use a custom renderer for a table with AutoColumnSize plugin enabled (is enabled by default)
2. Try and use the setDataAtCell() method to change the data for a cell
3. Exception occurs 

### Demo

http://jsfiddle.net/sj52q0zy/2/

### Your environment
* Handsontable version: 1.10.2
* Browser Name and version: Google Chrome: Version 58.0.3029.110 (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @jeremy-smith-maco 

in the demo, you have been calling a `setCellMeta()` method inside table initialization settings. When I put the `valueRenderer` in `updateSettings` it works as expected http://jsfiddle.net/8dgnfw2m/
