### ISSUE TITLE
Add a method that returns the data object for a given row.

### ISSUE THREAD

**Issue by dbujold** [handsontable/handsontable#4265]
### Description
Right now, there is no direct way to obtain the data object behind a given HOT row. This is a problem when column sorting is enabled, as getSourceDataAtRow() will return the object at a given row before sorting happened. It'd be nice to have something similar to hot.getDataAtRow() that returns a data object instead of an array of values.

Discussion on this topic happened here: https://github.com/handsontable/handsontable/issues/3564

Thank you!

**Comment by AMBudnik** [comment]
Thank you for sharing @dbujold

**Comment by AMBudnik** [comment]
The idea has been approved added to our [wiki section for the Feature Requests](https://github.com/handsontable/handsontable/wiki/Feature-requests). 
Again thanks for sharing.

**Comment by AMBudnik** [comment]
I can see it like `getDataAtRow` but with an information about keys as actually (0.38.1) we get an array of values (for object data the same).
