### ISSUE TITLE
How can the strict attribute be applied to dropdown?

### ISSUE THREAD

**Issue by xfliu138** [handsontable/handsontable#4266]
### Description

Because the contents in the cell are inconsistent with the contents in the dropdown, so how can the strict attribute be applied to dropdown?
I set strict to false, but it doesn't work in dropdown type cell

Refer to the following demo, I want to in the dropdown cell input 'or' the third column of the cell,But failed, after the mouse left the cell will automatically match ‘orange‘ filled in

### Demo
http://jsfiddle.net/favve1uw/

### Your environment
* Handsontable version:
* Browser Name and version: Firefox
* Operating System: Windows

**Comment by xfliu138** [comment]
I have solved it，thanks

**Comment by AMBudnik** [comment]
Thanks for an update.
