### ISSUE TITLE
how to forbid one column to copy?  i need this function

### ISSUE THREAD

**Issue by lwjmzla** [handsontable/handsontable#4268]
### Description
how to forbid one column to copy?  i need this function

**Comment by AMBudnik** [comment]
Hi @lwjmzla 

you can pass `false` via the [`copyable`](https://docs.handsontable.com/pro/Options.html#copyable) option.

Here is an example: http://jsfiddle.net/handsoncode/dfa35tgk/ as you can see if we try to paste the new values are empty.
