### ISSUE TITLE
Auto create columns feature?

### ISSUE THREAD

**Issue by jwillmer** [handsontable/handsontable#4269]
Is it possible to load a json/csv/etc file/object and let handsontable automatically recognize the columns? I have not find a entry in the documentation about this.

**Comment by AMBudnik** [comment]
Hi @jwillmer 

In Handsontable from the following options, you can only load a .json file. If you do not define columns Handsontable takes all the objects in their default order. Here is an example http://jsfiddle.net/handsoncode/98k30bny/

**Comment by jwillmer** [comment]
O.K., thx
