### ISSUE TITLE
Add custom rowBody in Handsontable

### ISSUE THREAD

**Issue by krgsoft** [handsontable/handsontable#4270]
I am recently using Handsontable in my project. I have to append custom rowBody in each row.
Please share your idea, how it can be done.

**Comment by AMBudnik** [comment]
Hi @krgsoft 

Can you describe what exactly you would like to get? I am not familiar with this term.

**Comment by krgsoft** [comment]
Hi @AMBudnik,

Sorry for late reply, 

Actually I have to append additional custom body for each row as in attached image.
![image](https://cloud.githubusercontent.com/assets/11477002/26728996/cffbb686-47cb-11e7-8de3-2f4d5f2bdf6b.png)

**Comment by krgsoft** [comment]
Hi AMBudnik,

Is there any possibilities in handsontable to address the requirement? If you have any idea please share.

**Comment by AMBudnik** [comment]
We do not have an exact example for the following case but you can use two options

1) hot in hot - http://jsfiddle.net/handsoncode/2dwvuqvg/
You create a separate table for a cell.

2) table inside a cell - http://jsfiddle.net/handsoncode/59dz92jh/
but this solution is not collapsible.

You can also change styling for cells by disabling borders of cells using normals nested structure as shown here https://docs.handsontable.com/pro/1.11.0/demo-nested-rows.html
