### ISSUE TITLE
Copy pasting not working in first paste

### ISSUE THREAD

**Issue by ShirishResilinc** [handsontable/handsontable#4271]
### Description
Hi all,  
Whenever i am pasting whole row data from excel only columns which are visible are getting pasted. Columns which are not visible in scroll are not populating but when i paste whole data on same row 2nd time it gets pasted.

### Your environment
* Handsontable version: 0.31.0
* Browser Name and version: Google Chrome 58.0.3029.110 
* Operating System: Windows

**Comment by AMBudnik** [comment]
I think that the issue may be related to https://github.com/handsontable/handsontable/issues/3078
Can you confirm that @ShirishResilinc ?

**Comment by ShirishResilinc** [comment]
Thanks @AMBudnik for response, i had seen #3078 but in my case same scenario happens both times i.e using context menu as well as ctrl + v. both fails to paste at first attempt, but if i paste it at same row 2nd time in both cases it pastes whole row.

**Comment by AMBudnik** [comment]
Can you share a step0by-step scenario which will help us to replicate the issue?
