### ISSUE TITLE
Custom renderer not work with validators

### ISSUE THREAD

**Issue by minchopm** [handsontable/handsontable#4273]
Description
So I am opening this issue again because I was waiting for some changes about validators. Unfortunately validators are not adding invalid class name to the cell with combination of custom renderer. 
this is an example in jsfidle with latest version of HOT.

[http://jsfiddle.net/rh5jwj4h/1/](http://jsfiddle.net/rh5jwj4h/1/)

Your environment

Handsontable version: 0.32.0-beta2
Browser Name and version: chrome
Operating System: Windows

**Comment by AMBudnik** [comment]
Hi @minchopm 

Can you check if the following solution works for you http://jsfiddle.net/budnix/rh5jwj4h/2/?

**Comment by minchopm** [comment]
It is working perfect thanks

**Comment by AMBudnik** [comment]
Great :) thanks for the confirmation.
