### ISSUE TITLE
Insufficient Documentation

### ISSUE THREAD

**Issue by jwillmer** [handsontable/handsontable#4274]
While I was evaluating the table I found the following problem:

- no site about all options that can be set in init Handsontable
- properties that can be used in column definition are all over the place and have no central place
- many properties have no proper description of what they are doing 
- missing description if a property is optional or required (data key in column!)
- missing description of valid property values (properties can be true or object)
- no documentation on how to hook up a button/toggle/etc to interact (for example: read only on/off) with the table

Eventually I found out how to do it or found the needed information on another place (examples). This list represents only points that made it annoying to integrate Handsontable but no deal breakers.

**Comment by AMBudnik** [comment]
Hi @jwillmer 

Can you specify
> no site about all options that can be set in init Handsontable

Does it relate to the options in general? If so you can find it at and if you mean the metadata options then the issue has been already raised at https://github.com/handsontable/handsontable/issues/2377

To the 2nd point, we could add this information while adding https://github.com/handsontable/handsontable/issues/3876

> many properties have no proper description of what they are doing

Can you point a few? We will be adding some changes to the documentation in July as I was informed so if you could specify where's a lack of information or clarification. 

> missing description if a property is optional or required (data key in column!)

I agree

> missing description of valid property values (properties can be true or object)

Can you share an example, please?

> no documentation on how to hook up a button/toggle/etc to interact (for example: read only on/off) with the table

we have something similar here https://docs.handsontable.com/0.32.0/demo-custom-buttons.html. Please let me know what we should add to this tutorial to make it better.

Thank you.

**Comment by jwillmer** [comment]
The options are every there but not collected in one place. Below is a init example there properties can have multiple data types but the description of it is in separate places.

```
this.hot = new Handsontable(container, {
    data: data,
    columns: columns,
    rowHeaders: true,     // true or obj?
    colHeaders: headers,
    dropdownMenu: [ .. ], // options?
    hiddenColumns: {      // properties
        ...
    },
	...
}
```

**Comment by AMBudnik** [comment]
Basically now we are keeping all the options here https://docs.handsontable.com/pro/Options.html

and as for the `rowHeaders` I think it looks pretty much OK

![image](https://cloud.githubusercontent.com/assets/10757813/26668911/1a8abb3c-46ac-11e7-81d7-b9ef0db56d78.png)

then the `dropdownMenu` description could share more examples and the options that we cause pick 

![image](https://cloud.githubusercontent.com/assets/10757813/26668963/49333f22-46ac-11e7-9bf4-de66a6910aeb.png)

**Comment by AMBudnik** [comment]
I am closing the issue as similar (more detailed) issues can be found at https://github.com/handsontable/handsontable/issues/2377
