### ISSUE TITLE
Table Header Over Lap My DOM

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#4275]
### Description

Hai am using HOT for rendering large Number of cells while rendering It loads the data perfectly.
but my problem is when  vertically scroll the Web Page .Header of the Table Overlaps my Page DOM(navigation Bar and TOP menu Bar).

![handson](https://cloud.githubusercontent.com/assets/29049117/26561361/58ed95f2-44db-11e7-8d68-b0bf659171c9.png)

can anyone help me to resolve this?

Thanks in Advance

**Comment by AMBudnik** [comment]
Hi @Sundarcj 

The header of Handsontable uses the `fixed` option for the `position` parameter and a significantly large `z-index` so if you want to have a bigger control over this element you should wrap it with a parent element and add higher `z-index` to other elements in your website.


If you won't be able to get it done please create a demo where we'd be able to replicate it.

**Comment by Sundarcj** [comment]
thanks i fixed it.
