### ISSUE TITLE
Scrolling with mouse scroll + SHIFT is inconsistent on all browsers

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4276]
### Steps to reproduce

1. Place the cursor on the table
2. Hold <kbd>shift</kbd> key and use the mouse scroll

**Result:**
Content moves vertically

**Expected:**
Content should move horizontally

### Demo

https://docs.handsontable.com/0.32.0-beta2/demo-scrolling.html

### Your environment
* Handsontable version: 0.32.0-beta2
* Browser Name and version: IE 11
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
The behavior remains the same in 0.35.1. We still can scroll only vertically

**Comment by swistach** [comment]
To be honest, I think is nothing to do on our side :)
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14286074/ - this shortcut is used by IE / Edge to navigate the history.

**Comment by zzliux** [comment]
I think it is in line with the user's habit of using shift and scroll wheel for horizontal scrolling of tables, such as Microsoft Office Excel and Kinsoft WPS tables. And can future versions support shortcut keys for horizontal scrolling?

**Comment by AMBudnik** [comment]
Hi @zzliux 

There are no scroll-related shortcuts. However, the new API of ShortcutManager allows for the quick addition of new shortcuts. 

Here's the main API https://handsontable.com/docs/javascript-data-grid/api/shortcut-manager/ of the Shortcut Manager. Then when the context is created you can use the `addShortcut()` method mentioned at https://handsontable.com/docs/javascript-data-grid/api/shortcut-context/#addshortcut

And to be sure that you are not trying to overwrite an existing shortcut please check the list at https://handsontable.com/docs/javascript-data-grid/keyboard-shortcuts/.
