### ISSUE TITLE
Way to Prevent Cells from Being Re-Rendered

### ISSUE THREAD

**Issue by jongunter** [handsontable/handsontable#4277]
My HandsOnTable has a column of read-only cells that are quite (computationally) expensive to render. Once they are rendered, their content doesn't change. 

Unfortunately, every time I edit a cell, it seems that every cell visible in the table is re-rendered. This results in sluggish performance, as these cells in question take so long to render. I tried to use a flyweight-type strategy in my custom renderer here, actually building the cell's DOM node on the first render and storing it, and returning the same DOM node on subsequent renders.

This seemed to work, but I realized that Handsontable was removing the cell's contents from the DOM (likely before a re-render), thus detaching all the event handlers on that cell's HTML. Thus,  click/tap/drag/mouseover events on my custom cell content don't work after it has been re-rendered.

I know this is pretty "edge case", but would it be possible to have a `cellProperties.renderOnlyOnce` setting where you could prevent any re-renders of the cell after the initial one? Then, HOT could detach (not remove) the DOM node when it gets scrolled out of view, and reattach it when the cell is in view. 

I'm no JS/DOM profiling expert, but wouldn't this boost performance either, since you're not removing and adding DOM elements to as many cells?

Thanks so much. I will add a demo plunker when I have a spare moment this week. Also, just wanna say...this is an awesome library!

**Comment by jongunter** [comment]
Reading other issues and thinking more about this, maybe there could (also) be a setting called `renderAllCellsOnEdit`. Some tables (like the one I'm implementing) don't have any calculations/conditional formatting. In that case, after a user edits a cell, the only cell that would need to get re-rendered is the one they just changed. I can imagine this would be a major performance boost in some situations.

**Comment by AMBudnik** [comment]
Hi @jongunter 

we will be adding an option that will allow you to only rerender the set of cells that has been changed and yes, you are right it will definitely boost the performance. 

The following feature is named `eco rendering`. I think that we will be able to start the work in the second half of June.

To check the progress you can follow our Roadmap https://trello.com/c/m9KTygSV/80-refactor-re-write-of-renderers-eco-rendering

ps.
> Also, just wanna say...this is an awesome library!

Thanks! :)

**Comment by jongunter** [comment]
Thanks. I'll look forward to seeing eco-rendering.

I was able to get a workaround with my issue by:
1) keeping track of the cells in question (which I was already doing with my flyweight-lazy-renderer-thing)
2) hook into `beforeRender` and **detach** (not remove) the contents of those cells from the DOM. This keeps the event handlers in place.
3) hook into `afterRenderer` and re-attach those cell contents to the DOM in specific places (I was already doing this before)

**Comment by AMBudnik** [comment]
That sounds like a very clever workaround. Thanks for sharing!

**Comment by AMBudnik** [comment]
Hey @plamenkoyovchev 

One of our developers started to optimize this process
> how to prevent cells from being re-rendered after cell value change ?

but this is a matter of research so it can take some time.

**Comment by jkyadav** [comment]
@AMBudnik Any update on this?

**Comment by AMBudnik** [comment]
@jkyadav as the topic is complex we created a couple of issues and are closing them but the main topic to follow is here https://github.com/handsontable/handsontable/issues/5769
We needed to pass all our hands to help with 8.0.0 but will surely continue the subject after releasing the stable 8.0.0.

**Comment by krishamatya** [comment]
I am still facing this issue. I have 100 record in handsontable, and when i update one cell, the cell render of whole table cells gets called in CustomRenderer. this is disaster from the performance point of view

**Comment by krishamatya** [comment]
> Thanks. I'll look forward to seeing eco-rendering.
> 
> I was able to get a workaround with my issue by:
> 
> 1. keeping track of the cells in question (which I was already doing with my flyweight-lazy-renderer-thing)
> 2. hook into `beforeRender` and **detach** (not remove) the contents of those cells from the DOM. This keeps the event handlers in place.
> 3. hook into `afterRenderer` and re-attach those cell contents to the DOM in specific places (I was already doing this before)

Hi there,

Can I have some example on this one. I am really suffering performance issue and not finding any proper way to do.
