### ISSUE TITLE
Uncaught TypeError while drag merged cell

### ISSUE THREAD

**Issue by turnerguo** [handsontable/handsontable#4279]
### Description
got uncaught typeerror while drag merged cell.

### Steps to reproduce

1. open: https://handsontable.com/examples.html?_ga=2.77629524.1743596653.1496196907-1518068113.1496196907&headers&fixed&sorting&merge-cells
2. merge some cells.
3. drag the right-bottom corner, then open the DevTools see errors in console.

### Your environment
* Handsontable version:
* Browser Name and version: Chrome lastest
* Operating System: Mac lastest.

**Comment by AMBudnik** [comment]
Thank you for sharing @turnerguo 

I got the same error on the website but not in the Fiddle.

**Comment by AMBudnik** [comment]
The same issue as https://github.com/handsontable/handsontable/issues/4560
