### ISSUE TITLE
 The parameter "coords" of the `beforePaste` handler is wrong.

### ISSUE THREAD

**Issue by matsushita-nagatoshi** [handsontable/handsontable#4281]
### Description

I think, The parameter "coords" of the `beforePaste` handler is wrong.

For example, suppose that there is a 3 × 3 table.

With 2x2 data on the clipboard, focus on the 2nd row and 1st cell of the table and paste it.

The result is as follows.

Expected value::

    {
      startRow: 1
      endRow:   2
      startCol: 0
      endCol:   1
    }

Actual value::

    {
      startRow: 1
      endRow:   1
      startCol: 0
      endCol:   0
    }

The document is described as follows.

> An array of objects with ranges of the visual indexes (startRow, startCol, endRow, endCol)
> where changes will be inserted.

http://docs.handsontable.com/0.31.1/Hooks.html#event:beforePaste

### Steps to reproduce

none

### Demo

none

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: chromium 58.0.3029.81 (64-bit)
* Operating System: gentoo linux

**Comment by AMBudnik** [comment]
@matsushita-nagatoshi 

I agree we should get 

```
{
  startRow: 1
  endRow:   2
  startCol: 0
  endCol:   1
}
```

currently, if we would track the hook's result it looks like we have pasted one cell instead of four.

**Comment by AMBudnik** [comment]
Hi again @matsushita-nagatoshi 

I have talked with our developer @swistach who told me that actually, the `coords` is should work this way to tell us what range of cells has been selected, so if we want to get 

```
{
  startRow: 1
  endRow:   2
  startCol: 0
  endCol:   1
}

```
coords we should select cells from `A2` to `B3`

![image](https://cloud.githubusercontent.com/assets/10757813/26627474/ed983f16-45fa-11e7-98a9-157146e310bd.png)

**Comment by matsushita-nagatoshi** [comment]
Thank you for answering!

Is it OK in understanding that the current implementation means that the coords on the currently selected cell pass to the handler?

If it is, it contradicts what is written in the document, so I think that you should modify the document.

http://docs.handsontable.com/0.31.1/Hooks.html#event:beforePaste

**Comment by AMBudnik** [comment]
Definitely!

> An array of objects with ranges of the visual indexes (startRow, startCol, endRow, endCol)
> where changes will be inserted.

should be rewritten to something like:

> An array of objects with ranges of the visual indexes (startRow, startCol, endRow, endCol)
> that correspond to the previously selected area.

**Comment by matsushita-nagatoshi** [comment]
OK, Thank you for your kind response.
@AMBudnik

**Comment by AMBudnik** [comment]
and I thank you for your effort to investigate the subject. The subject can surely produce some question marks :)

**Comment by swistach** [comment]
Thanks @matsushita-nagatoshi and @AMBudnik,
Changed description is available here: https://docs.handsontable.com/0.33.0/Hooks.html#event:beforePaste

**Comment by VirajBhatt** [comment]
Hi, i'd like to know if there is a work aorund for getting the coords of finally where the changes are made instead of the selected area. Please reply asap? Thanks!

**Comment by AMBudnik** [comment]
Hi @matsushita-nagatoshi 
> coords of finally where the changes are made

have you tried `afterChange` hook? Docs https://handsontable.com/docs/7.4.2/Hooks.html#event:afterChange
