### ISSUE TITLE
Button click event on ipad

### ISSUE THREAD

**Issue by pkaminiv** [handsontable/handsontable#4282]
Hi i have problem with click event on button. it is not fire the click event in ipad. 

here i have attached view of grid. i have anchor tag right now. but i have tried to put button and also button click event not fire. 
 
![image](https://cloud.githubusercontent.com/assets/28708204/26628372/7093db62-461b-11e7-880e-2c8177474ef8.png)

**Comment by AMBudnik** [comment]
Thank you for sharing this issue @pkaminiv 

I have replicated the issue with a simple `alert()` which does not work when we tap the cell.

**Comment by swistach** [comment]
Hi @pkaminiv,
I close this issue due to the problem you reported is much more general.
If you would like to stay up-to-date on work progress, please track #8414.
