### ISSUE TITLE
It is not possible to manually reduce row height after table initialization

### ISSUE THREAD

**Issue by haydave** [handsontable/handsontable#4283]
### Description
It is not possible to manually reduce row height after initialization step

### Steps to reproduce
1. Set **rowHeights** with the following values: [50, 40, 100]
2. Try to reduce row height manually
3. Row height remains the same

### Demo
We see example in https://docs.handsontable.com/0.19.0/demo-resizing.html

As we understand **onModifyRowHeight** function is responsive for this behavior.

Is there any workaround? 
Actually we can achieve that by removing **manualRowHeight > (height || 0)** part from **onModifyRowHeight** function. But we don't think that changing library is a correct solution.

### Environment
* Handsontable version: 0.31.1
* Browser Name and version: Chrome Version 54.0.2840.90 (64-bit)
* Operating System: Ubuntu 14.04

**Comment by AMBudnik** [comment]
I think that we could add this as an option as currently if you use `colWidths` or `rowHeights` there's nothing more you can do to resize the cell (besides when you'll get more content that doesn't fit).

**Comment by haydave** [comment]
Thanks, it will be great.

**Comment by TRManderson** [comment]
I've got a PR to update the docs in #4343, to mention that they enforce minimums. Some time this week I might end up doing col width/row height minimums, so there's a chance you'll be able to grab a test implementation.

**Comment by AMBudnik** [comment]
Already reported as a feature request at https://github.com/handsontable/handsontable/issues/3301
