### ISSUE TITLE
Upgrading from 28.4 to 29+

### ISSUE THREAD

**Issue by kag341** [handsontable/handsontable#4284]
### Description
The comments have been completely overhauled after version 28.4, and I'm having a difficult time determining exactly how my system needs to be updated to use the new comments.  

Can you provide any examples or documentation for conversion?

**Comment by AMBudnik** [comment]
Hi @kag341 

That is right, we have changed how comments work. Please let me know where exactly you have found difficulties to handle comments.

**Comment by andrewQwer** [comment]
I had the same problem. Due to API changes you have to set comments like this:
```
cell: [
  {row: 1, col: 1, comment: {value: 'Hello world!'}}
]
```
`comment property became an object with `value` property inside.

**Comment by AMBudnik** [comment]
Thank you for your input @andrewQwer
