### ISSUE TITLE
Add Filter Resize possibility

### ISSUE THREAD

**Issue by michaelkrnac** [handsontable/handsontable#4285]
### Description
For allmost any of my filters the filterbox is to small.
The user should be able to resize it like it is in MS Excel.
The fonts of filters should be smaller by default too.

![2017-06-01 10_05_04-cert xlsm - excel](https://cloud.githubusercontent.com/assets/3944657/26670502/31a4ed64-46b2-11e7-8b7f-8fe36abd057e.png)

**Comment by AMBudnik** [comment]
Thank you for sharing the idea. It would be more user-friendly with an ability to change the window width.

**Comment by AMBudnik** [comment]
The idea has been approved added to our [wiki section for the Feature Requests](https://github.com/handsontable/handsontable/wiki/Feature-requests). 
Again thanks for sharing.

**Comment by ottosson** [comment]
I know you've been hard at work getting v8 ready. But I would like to add my vote to this feature request :)

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
