### ISSUE TITLE
Editor on freezed cell is opened in background cell

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4286]
Hi,

I use my own implementation of Select2 editor and when I open it on non freeze column it shows like this:
![image](https://cloud.githubusercontent.com/assets/710513/26671230/63f89ad0-46bd-11e7-8c09-d39abd56fc01.png)
But if I open it on freezed cell, then cell with editor is selected incorrectly.

Freezed cell looks like if it is not in edit mode, and `<select>` element is not attached to this cell.

![image](https://cloud.githubusercontent.com/assets/710513/26671519/77a0af36-46be-11e7-8852-f730b84b75d7.png)

 Instead it is attached to the background cell, that belongs to `ht_master handsontable` `div`

![image](https://cloud.githubusercontent.com/assets/710513/26671573/a7412c2a-46be-11e7-8082-eca43c36f019.png)

I use this code to move `<select>` into edited cell in editor's `open` method
```
 let $select = this.$select.clone();
    Handsontable.Dom.empty(this.TD);
    $(this.TD).append($select);
```
So questions are:
1) Why `this.TD` points to incorrect cell? What should I do to open editor exactly in freezed cell?
2) How to synchronize height of freezed cell and cells on the same row in `ht_master` table while editing?

**Comment by andrewQwer** [comment]
Any update on this?

**Comment by AMBudnik** [comment]
Hi @andrewQwer 

sorry for a delay. I see that you are using some kind of custom renderer or a 3rd library. We can't assure that it will work, however, could you share a demo where we'd be able to test it?

**Comment by andrewQwer** [comment]
Hi @AMBudnik 

Yes, I use my custom editor based on Select2, but the problem is that internally editor is opened not on a cell I clicked on the fixed column, but on the cell behind the fixed column.  Looks like that all your built-in editors are absolutely positioned and you don't place them directly to the cell user clicked. 

Look at this example: http://jsfiddle.net/andrewQwer/n8a0agLo/17/
Open developer tools and click on any cell on column B. You'll see that mouse down occurs on the same cell as `prepare` method is called.
But click on any cell on column A. Mouse down occurs on cell that belongs to table `ht_clone_left` but `prepare` occurs on `ht_master` table and my editor attached to this cell is not visible.

https://www.screencast.com/t/gQjNLlvemFQQ

**Comment by AMBudnik** [comment]
Thank you for sharing additional details @andrewQwer  I can see that you have made a serious research. Unfortunately, this topic exceeds my capability to help. I will ask for a help from one of our developer.

**Comment by andrewQwer** [comment]
Just say them that for fixed column the pass wrong `td` parameter :wink:

**Comment by swistach** [comment]
Hi @andrewQwer,
you should use a similar solution, as is implemented in the TextEditor. There is a `getEditedCell` method, which returns proper TD element.
Code: https://github.com/handsontable/handsontable/blob/master/src/editors/textEditor.js#L194

**Comment by andrewQwer** [comment]
Hi @swistach. 

Good to know that such method exists. But anyway if you pass `td` parameter it should point to correct cell, otherwise it is useless.
