### ISSUE TITLE
Only horizontal scroll

### ISSUE THREAD

**Issue by megamuf** [handsontable/handsontable#4288]
### Description
Hello,
I need add only horizontal scroll without vertical scroll.
In issue Horizontal scroll only #4221 I saw that this can not be done.
I really need this functionality(fixed width but no height).
At the same time add rows and change rows height.
Is there any way to do this?

### Your environment
* Handsontable version: Handsontable 1.10.2 pro

**Comment by AMBudnik** [comment]
Hi @megamuf 

I think that this blog post can come in handy https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable
Let me know if you would need anything else.
