### ISSUE TITLE
Deleting row containing checkbox causes #bad-value#

### ISSUE THREAD

**Issue by unknown-git** [handsontable/handsontable#4290]
### Description
Deleting row containing checkbox causes `#bad-value#`

### Steps to reproduce
1. Select row/s press delete or backspace
2. `#bad-value#` appears in checkbox cell

### Demo
http://jsfiddle.net/ymyqgz45/3/

### Environment
* Handsontable version: 0.32.0
* Browser Name and version: Google Chrome Version 58.0.3029.110 (64-bit)
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
Hi @unknown-git 

that you for sharing.

This issue has been already reported under this topic: https://github.com/handsontable/handsontable/issues/4106
Please share https://github.com/handsontable/handsontable/issues/4106 for updates.
