### ISSUE TITLE
Add sample JSFiddle or Plunker link to Issue Template

### ISSUE THREAD

**Issue by jongunter** [handsontable/handsontable#4292]
There should a link to a minimum JSFiddle on the issue template. The less friction needed to get someone to reproduce an issue, the more people that will provide good repros, and you guys will get more useful bug reports.

**Comment by AMBudnik** [comment]
That actually is a good idea. A sample instance could only help. A user can always delete it if he already made one.

Thanks for sharing @jongunter!

**Comment by AMBudnik** [comment]
The change has been added.

Thank you for the suggestion.
