### ISSUE TITLE
outsideClickDeselects : false steals all keystrokes

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#4293]
Handsontable 0.32.0

If you use `outsideClickDeselects: false`, once you make a selection in the Handsontable, it will steal all keystrokes (focus?).  For example, once a cell is selected, you cannot select text outside of the table and hit Ctrl/Cmd+C to copy it, because as soon as you press the Ctrl/Cmd key, the text selection goes away.

Here is a CodePen to demonstrate.  I could not reproduce with jsfiddle--assuming it does some out of the ordinary handling of events to prevent it from happening.  However, the problem happens in real world and in CodePen:

https://codepen.io/anon/pen/owNxvN

**Comment by AMBudnik** [comment]
Thank you for sharing @cgatesman 

Firstly I think that I am not able to replicate it but then realized that if you copy something for the first time it works but after that, the selection is gone (as you described) and we keep the first copied value.

**Comment by cgatesman** [comment]
I'm not exactly sure what you mean.  Maybe you are not taking the correct steps to reproduce it.

1. Use my codepen example.
2. Select a cell in the Handsontable.
3. Select some text in the sentence above the Handsontable.
4. Press and hold the Control/Command key.  Notice the selection goes away.  This prevents you from doing Control/Command+C to copy.

Note, I am doing this on macOS.  Perhaps it doesn't behave exactly the same on Windows?

**Comment by AMBudnik** [comment]
I did not select the cell first and if I don't it works for once and then as described.
ps. Yes, I'm on Windows 10 (tested on Chrome 59)

**Comment by toroc** [comment]
I am experiencing the exact same issue on HOT 0.31.2 using chrome:"58.0.3029.110". OSX 10.12.6.
Handsontable is hijacking the focus of other inputs that exist outside of the grid.

**Comment by AMBudnik** [comment]
Hi @cgatesman can you check if this issue still occur? I've tried it with the latest Chrome and Firefox and it works well.

**Comment by cgatesman** [comment]
It appears to be working for me on latest browsers as well. 👍

**Comment by AMBudnik** [comment]
Thank you for checking. We can close this issue report.
