### ISSUE TITLE
How do I Freeze Specific Columns? 

### ISSUE THREAD

**Issue by ahlunju** [handsontable/handsontable#4294]
I went through the freezing https://docs.handsontable.com/0.32.0/demo-freezing.html and the manualColumnFreeze tutorials https://docs.handsontable.com/0.32.0/demo-fixing.html and it is looking nice and simple. 

However, instead of knowing how many columns need to frozen and that all the freeze columns are at the beginning of the array, the real use case would be when I have, for example 10 columns, I want HOT to automatically freeze, let's say the 3rd, 5th, and 9th column to the left.

**Comment by AMBudnik** [comment]
Hi @ahlunju 

If you have few columns to freeze and you know their indexes you can use the `freezeColumn` method of the `ManualColumnFreeze` plugin. Here's an example http://jsfiddle.net/8gff9y4d/
Currently, there's only one method that takes a single value so if you'd want to freeze more than one column you'd need to call it a few times.
