### ISSUE TITLE
Autofill doesn't work properly, when used with a group of cells, moving upwards.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4298]
### Description
The autofill feature doesn't work properly, when you use it on multi-cell selection, and drag it upwards (or towards left).

### Steps to reproduce
1. Select a group of cells (for example, 3 rows)
2. Use the fill handle to copy cells upwards (or to the left) by 2 rows

#### At the beginning:
![image](https://user-images.githubusercontent.com/7397134/26867628-6633e374-4b66-11e7-8512-79d1e85fbdaf.png)

### Result:
**Handsontable**:

![image](https://user-images.githubusercontent.com/7397134/26867723-cee65c6c-4b66-11e7-8611-7b1d24252666.png)
-----

 **Google Sheets**:
![image](https://user-images.githubusercontent.com/7397134/26867742-e2435288-4b66-11e7-9b8e-e3e97d5cac76.png)

**Excel**:
![image](https://user-images.githubusercontent.com/7397134/26868583-c948da3e-4b69-11e7-8809-06d38d3aca22.png)

**The same thing when filling to the left:**
![image](https://user-images.githubusercontent.com/7397134/26868971-04d274ba-4b6b-11e7-8e01-ca66dae8703a.png)
![image](https://user-images.githubusercontent.com/7397134/26868983-12382ece-4b6b-11e7-9ecd-9e11cee74d36.png)

**Comment by AMBudnik** [comment]
Thanks for fixing @jansiegel works fine now.
