### ISSUE TITLE
Can't scroll all the way horizontally

### ISSUE THREAD

**Issue by tedlin182** [handsontable/handsontable#430]
Hi,

I'm not sure if anybody else has encountered this, but I just upgraded to the latest version 0.8.5 and I'm unable to scroll all the way to the end of my table, which has around 30 columns.

It stops maybe 80% or the way.

I'm not sure if I'm missing a setting or something, but if you have any issue on this, that would help.

**Comment by michailw** [comment]
@warpech This issue still exists in version 0.24

**Comment by AMBudnik** [comment]
Hi @michailw can you share a scenario how to reproduce the issue?

**Comment by michailw** [comment]
Sorry for music, I had to replace microphone scream by random (mute it if you don't like). https://youtu.be/wZYh5fyTGUg

This is config for Handsontable constructor. I've ommited only columns declaration.

```
fillHandle:false
fixedColumnsLeft:1
fixedRowsTop:1
formulas:true
manualColumnFreeze:true
startCols:8
startRows:2
```

Is it enough?

**Comment by AMBudnik** [comment]
Thank you Michał.
It was one of the best scenario I got.

I made a demo: http://jsfiddle.net/70h6mh1y/ where I tried to reproduce the issue but I guess that your example has more styling and this can be a cause of our issue. Can you replicate the same behavior on a Fiddle?

**Comment by michailw** [comment]
Hello @AMBudnik,
I can't replicate this issue on jsfiddle. Can I give you access to service which is currently developed by me on any private channel, to show you my problem?  Here is my email: michal.wojtowicz@quantoo.pl

**Comment by AMBudnik** [comment]
unfortunately working on customer's data is a part of our commercial offer and I'm not able to perform this action but I can help you to check most common cases of bugs.

* CSS frameworks (please try to comment them and check again)
* parent styling

I do not think that it has to do something to do with your other js files and as it's not replicable in the Fiddle I'd say it has to relate to styling.
