### ISSUE TITLE
Fourth level references formulas not propagating right values on load.

### ISSUE THREAD

**Issue by daveonsoftware** [handsontable/handsontable#4301]
### Description
Using handsontable with rule js.
When formulas are referenced in more than 3 nested levels, cell value results are not propagating properly on page loading.

### Steps to reproduce
1. Load demo page. There is implemented a simple 4 level aggregation summatory tree.
   The TOTAL Value cell (B11) contains '4' when it should be 6 .
2. Once you edit a referenced cell value like (B10), the cells are refreshed and correct values are propagated along all formulas nested levels.
3.- Is there any workaround who allows to force formula refresh? Thank you.

### Demo
http://jsfiddle.net/999u3r2t/23/

### Your environment
* Handsontable version:
Handsontable.buildDate = 'Mon Jun 27 2016 10:10:40 GMT+0200 (CEST)';
Handsontable.packageName = 'handsontable-pro';
Handsontable.version = '1.5.0';
RuleJS = 0.0.1;
* Browser Name and version: InternetExplorer 11, Chrome 58.0.3029, Firefox 53.0.3
* Operating System: Windows 8.1 Pro

Thank you.

**Comment by airstrike** [comment]
For the record, editing cell `B11` and pressing Enter correctly recalculates it to 6

**Comment by AMBudnik** [comment]
Please notice that we do not handle Formulas via RuleJS anymore. We have managed to create a separate Handsontable PRO called the [Formula Support](https://docs.handsontable.com/pro/1.11.0/demo-formula-support.html). We do not commit to RuleJS for some time and as Formula Support is in an alpha stage we will try to create a stable version later this year (depending on the Roadmap list). 

If you already own a Handsontable PRO Formula Support won't cost anything more. Can you check if doing the same calculations using the plugin works?

**Comment by daveonsoftware** [comment]
Hi Aleksandra, thank you for your reply.

Right now I'm affraid we can afford to switch to Formula Support since we
are in production and yesterday I could finally make a simple but effective
workaround. (Simply re-set one header cell text value once HandsOnTable has
rendered).

I'll take into acount for further deployments.


Thank you very much.

Regards.

David.

2017-06-20 13:57 GMT+02:00 Aleksandra Budnik <notifications@github.com>:

**Comment by AMBudnik** [comment]
I am really glad that you have found a workaround.

I keep my fingers crossed for the project.
