### ISSUE TITLE
Handsontable missing rows when using preventOverflow with updateSettings

### ISSUE THREAD

**Issue by randyyaj** [handsontable/handsontable#4303]
### Description

Should see 100 rows in example. I have enabled preventOverflow: horizontal and columnSorting: true. If you remove the columnSorting property it will display all 100 rows.

### Steps to reproduce
https://jsfiddle.net/v364ow5o/1/

### Demo
https://jsfiddle.net/v364ow5o/1/

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Chrome
* Operating System: Mac,Linux,Windows

**Comment by AMBudnik** [comment]
Thank you for sharing this issue. I have replicated the bug.

**Comment by fengkaijia** [comment]
+1 on 0.34.1. Break down parameters one-by-one and found only ```preventOverflow``` and ```columnSorting``` cannot co-exist.

**Comment by AMBudnik** [comment]
I've just replicated it with v `2.0.0.` It looks like the issue is as old as `preventOverflow` itself.

**Comment by AMBudnik** [comment]
Works the same in v `6.0.1.`

**Comment by wojciechczerniak** [comment]
As noted in #4507 rendering breaks on `updateSettings`, another example here: https://jsfiddle.net/sw7aryjo/

ColumnSorting have to call `updateSettings` to enable `observeChanges` plugin. We will remove `observeChanges` from ColumnSorting in #5649. But the problem with `updateSettings` will exist.

**Comment by AMBudnik** [comment]
Hi @randyyaj 

this demo https://jsfiddle.net/auqb2dr5/ loads the latest version of Handsontable - v8.0.0 which allows us to see all the 100 rows and use `columnSorting`. I'm glad to call this issue solved.

ps. It did not work in v 7.4.2 https://jsfiddle.net/jo6p502q/
