### ISSUE TITLE
Using wrong row/col indexes for validation

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4304]
### Description

When using a sorted table with the "allowInvalid" option set to false and validation set for a column, entering an invalid value whilst the physical index for that row is not visible causes an error. The issue is that the line for getting the cell element uses the row and col values from "cellProperties" which is using the physical indexes when it should be using the visual indexes for the "getCell()" method.

The exact code block causing this issue is here: [core.js Line 1038](https://github.com/handsontable/handsontable/blob/33dcdf5bb81cad36b1705ec502eef84b899849c4/src/core.js#L1038)
The exact line is: [core.js Line 1041](https://github.com/handsontable/handsontable/blob/33dcdf5bb81cad36b1705ec502eef84b899849c4/src/core.js#L1041)

So to fix it this line:
```
const cell = instance.getCell(cellProperties.row, cellProperties.col);
```
should become:
```
const cell = instance.getCell(cellProperties.visualRow, cellProperties.visualCol);
```

### Steps to reproduce

1. Disable "allowInvalid" in a table and add validation to a column.
2. Sort the table so that the physical row index matching the visual row index is not visible (null).
3. Enter an invalid value.

### Demo

http://jsfiddle.net/Lp4qn55v/691/
Enter a letter into any cell which will cause validation to fail and an error to occur.

### Your environment
* Handsontable version: 1.10.2
* Browser Name and version: Google Chrome: Version 58.0.3029.110 (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the issue (I have replicated it) and the solution as well.
