### ISSUE TITLE
Merged Cell Range retains when a column is removed

### ISSUE THREAD

**Issue by chirag-compro** [handsontable/handsontable#4309]
### Description
When a column which is previously merged for a particular row is removed,the data in the table shifts accordingly but empty column sustains (i.e -  An empty column for rest of the rows, other than the merge row sustains).
As per Excel when a column which is previously merged, when removed, the merge range decreases

### Steps to reproduce

1. Remove column **E** using context menu.
2. Observe the spreadsheet for column **E**.

### Demo

http://jsfiddle.net/55Lccocv/1/
### Your environment
* Handsontable version: pro-1.11.0
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hi @chirag-compro 

I think that your demo is missing some setting as you wrote that it relates to merged cells. Can you check that please?

**Comment by AMBudnik** [comment]
I am closing this issue as there is no reply since 23th of June
