### ISSUE TITLE
While sorting and hiding rows handsonetable not behaving properly.

### ISSUE THREAD

**Issue by GanjuV** [handsontable/handsontable#4312]
### Description
I am new to handsonetable, i have implemented sorting and showing/hiding of rows.
But when i do a sorting on any column and after this hide some rows using "trimRows" functionality.
The output is not as expected. Please let me know if i am doing something wrong.
### Steps to reproduce
1. Sort for any column.
2. Click on hide button.
3. Some of the table rows have become blank.

### Demo
https://jsfiddle.net/Vaibhav34/2rr7xeLm/2/

### Your environment
* Handsontable version: 1.11.0
* Browser Name and version: Chrome, Version 55.0.2883.95 (64-bit) 
* Operating System: Mac 10.12.5

Before Sorting :-
![image](https://user-images.githubusercontent.com/24271789/27115354-b211f9da-50e7-11e7-9854-d601a03284fa.png)

When sorting is done and hide button is clicked 

![image](https://user-images.githubusercontent.com/24271789/27115383-d90b7390-50e7-11e7-8613-4bc76e07dc16.png)

![image](https://user-images.githubusercontent.com/24271789/27115370-c4327216-50e7-11e7-919d-d60d963ff3ff.png)

**Comment by AMBudnik** [comment]
Hi @GanjuV 

Thank you for sharing. 

We are aware of this issue and it has been marked with the highest priority by our senior developer at https://github.com/handsontable/handsontable/issues/4170. If we have missed anything at https://github.com/handsontable/handsontable/issues/4170 please share your comment

**Comment by GanjuV** [comment]
Issue exist when sorting and persistentState is true and we are calling untrimAll() and tromRows() simultaneously.

**Comment by AMBudnik** [comment]
Hi @GanjuV 
please leave your comment at #4170 as it is a proper opened issue for this subject

**Comment by GanjuV** [comment]
thanks @AMBudnik
