### ISSUE TITLE
Handsontable overwrites bootstrap tables styles

### ISSUE THREAD

**Issue by ChristianKohler** [handsontable/handsontable#4313]
### Description
Handsontable overwrites bootstrap tables styles even for non handsontable grids.

Expected: If i use a normal html table (not handsontable) on a page, I want the normal bootstrap styles.

### Steps to reproduce

1. Open Demo
2. Remove handsontable css
3. See difference in padding

### Demo
http://jsfiddle.net/hq1e0hnm/

### Your environment
* Handsontable version: 1.11.0

**Comment by tilowestermann** [comment]
Not sure if this is related, but this issue exists even for Handsontable Bootstrap grids:

### Steps to reproduce
1. Run example (rows are not striped)
2. Open inspector, disable `background-color: #FFF` for `.handsontable td`
3. Rerun example (rows are striped)

### Demo
http://jsfiddle.net/w45gepfv/

**Comment by AMBudnik** [comment]
Thank you for sharing. As you are adding that classes via `tableClassName` they should be more important than the `.handsontable td` settings.

**Comment by ChristianKohler** [comment]
The problem is that the handsontable css sets some global styles for tables. They should be scoped to .handsontable:

```
.table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
  line-height: 21px;
  padding: 0 4px;
}

.table-striped > tbody > tr:nth-of-type(even) {
  background-color: #FFF;
}
```

**Comment by AMBudnik** [comment]
Yes, you're right. We shouldn't change the `table` CSS settings, just the `.handsontable table`.

**Comment by AMBudnik** [comment]
The issue will be solved with https://github.com/handsontable/handsontable/pull/4337 in v0.35.0

**Comment by AMBudnik** [comment]
Hi @ChristianKohler 
Please update the version to 0.36.0 and let me know if it works for you.
I have checked your demo using the same version and it does not change the Bootstrap styling

**Comment by samiakbar123** [comment]
I am facing the same issue.` "handsontable": "^7.0.3",  "react-handsontable": "^0.3.2"` please help

**Comment by AMBudnik** [comment]
Hey @samiakbar123 can you send a demo where the issue can be visible (replicable) on support@handsontable.com?
