### ISSUE TITLE
Copy formula between cells (PRO)

### ISSUE THREAD

**Issue by gstenson** [handsontable/handsontable#4315]
Not sure if this is linked to #4300 but doesn't exactly seem like it.
### Steps to reproduce
1.Open demo below
2. Put formula into cell =2+2
3. Drag to right to copy. Value 4 goes into cell not =2+2 so formula lost.

### Demo
http://jsfiddle.net/api/post/library/pure/

### Environment
* PRO 1.11.0
* Chrome Version 57.0.2987.110 (64-bit)
* Operating System: Ubuntu 16.04

**Comment by airstrike** [comment]
Demo link is broken

**Comment by AMBudnik** [comment]
Hi @gstenson 

We do not support dragging/populating formulas yet.

**Comment by AMBudnik** [comment]
Thank you for sharing the idea We have accepted it and copied to our feature request list at [Wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
