### ISSUE TITLE
unable to set the column heading text alignment. 

### ISSUE THREAD

**Issue by bcowgill** [handsontable/handsontable#4316]
### Description
I don't see any way to configure a className of htLeft/htRight htTop/htBottom etc on the column headers or the row headers.

### Steps to reproduce
n/a

### Demo
n/a

### Your environment
* Handsontable version: handsontable-pro@1.10.0
* Browser Name and version: 
* Operating System:

**Comment by bcowgill** [comment]
There is a jsfiddle indicating how to accomplish this, so there's a workaround
http://jsfiddle.net/1qrnhbz7/

**Comment by AMBudnik** [comment]
Hi @bcowgill 

It will be easier and more efficient to just share the alignment via `anyClass` like here http://jsfiddle.net/s3jtpx3u/ and if you would like to do it for all headers in the spreadsheet you can overwrite `th` elements for `.handsontable` class, like
```
.handsontable th {
  text-align: left
}
```
demo: http://jsfiddle.net/pLdcsn3x/
