### ISSUE TITLE
Drag Down doesn't copy the formula down rather copy values computed by the formula in the other cells

### ISSUE THREAD

**Issue by shaludhaka** [handsontable/handsontable#4318]
### Description

I applied formula =SUM(A12,B12)  and drag it down ,the value computed by this formula is copied but not the formula.

### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version:every version
* Browser Name and version:chrome
* Operating System:mac

**Comment by AMBudnik** [comment]
Hi @shaludhaka 

as mentioned here https://github.com/handsontable/handsontable/issues/4315 we do not support populating formulas yet. The plugin is still in an alpha stage.

**Comment by shaludhaka** [comment]
Hi AMBudnik,

Please let us know by when the support will be available for formula drag down as well.

**Comment by AMBudnik** [comment]
Of course @shaludhaka 

as soon as the issue will be opened again I will let you know.

**Comment by shaludhaka** [comment]
Hi AMBudnik,

I want to know that when will the beta version will be launced with formula drag down support so that i can use it in my project.

**Comment by AMBudnik** [comment]
Unfortunately, we do not have it scheduled yet. Also, I did not hear about it being scheduled for Q4 this year. I hope it will be published in 2018 though.

**Comment by iaminvictus1993** [comment]
@AMBudnik  is this scheduled?

**Comment by AMBudnik** [comment]
Hi @iaminvictus1993 we do not work on the formula plugin now as we already started a project for a new formula engine. After we finish that task we'll add the remaining features.

**Comment by Koushikphy** [comment]
any update on this?

**Comment by AMBudnik** [comment]
Hey @Koushikphy 

as the new formula engine is funded externally we need to follow some procedures that take time. However, we're doing great progress and already have the core created. We should be able to publish an official report before the end of 2019.
