### ISSUE TITLE
Provide options for filtering by value

### ISSUE THREAD

**Issue by tilowestermann** [handsontable/handsontable#4319]
### Description
I'm loading chunks of data from a remote server for pagination. Thus, Handsontable is only able to  determine distinct values that exist for a column for the given page. For example, given a table with a column showing booleans (false, true), the first page might only show false for this column, which results in the filter showing "false" as the only option to filter this column. 
Here I would like to provide options to filter this column by value: true, false. Is this possible with Handsontable?

This question was originally asked on StackOverflow: https://stackoverflow.com/questions/44515938/providing-custom-options-to-handsontable-filter-by-value

### Steps to reproduce
1. Enable filters
2. Load data from a remote source using pagination
3. See that a column is only filterable by the values given on that page.

### Demo
- 

### Your environment
* Handsontable version: Pro 1.11.0
* Browser Name and version: Chrome 58.0.3029.110 (64-bit)
* Operating System: macOS 10.12.5

**Comment by AMBudnik** [comment]
Hi @tilowestermann 

as pagination (used in the way described in [this tutorial](https://docs.handsontable.com/pro/1.11.0/demo-paginating.html)) loads only chunks of data on a button click (where a button is a numeric representation of a page) actually what we have defined as a filter database is this one single page. 

Currently, we are not able to open an ability to add an external source for Filters.  You could try to use `hiddenRows` to change which part (page) of results you want to display and then you'll have all the results in `filter_by_value` section like here http://jsfiddle.net/9kujxmqf/ However, it is only a start as pages still hold the same indexes after filtering etc.
