### ISSUE TITLE
Scrolling in Microsoft Edge is broken

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4320]
### Description

So when using Microsoft Edge (I don't know why you would want to though) and trying to scroll it doesn't scroll. If the table has a fixed height, the scrolling is inverted for some reason.

### Steps to reproduce

1. Having table that requires scrolling in Microsoft Edge.
2. Try and scroll.

### Demo

Without fixed height (doesn't scroll at all): http://jsfiddle.net/Lp4qn55v/
With fixed height (inverted scroll): http://jsfiddle.net/Lp4qn55v/711/

### Your environment
* Handsontable version: handsontable-pro@1.11.0
* Browser Name and version: Microsoft Edge 38.14393.1066.0
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing @jeremy-smith-maco 

we should also take a look at https://github.com/handsontable/handsontable/issues/4276 while fixing

**Comment by professorplops** [comment]
Hey also having this problem in EDGE, vertical scrolling on any table is inverted [example](https://handsontable.com/examples.html)

**Comment by AMBudnik** [comment]
`inform Gr 11494`

**Comment by AMBudnik** [comment]
Hi @jeremy-smith-maco 

I was able to get the scrolling working on IE in the last example using v0.36.0

> With fixed height (inverted scroll): http://jsfiddle.net/Lp4qn55v/711/

Can you check that, please?

**Comment by jeremy-smith-maco** [comment]
The scrolling does work in that example but it is inverted which is the issue with that one.

**Comment by AMBudnik** [comment]
Thank you for checking. We should definitely check this issue. As soon as one of the developers will have at least half of the day unlocked I'll ask them to check this issue.

**Comment by watnab** [comment]
We checked the code however we don't know the manner to fix it.
### Test case for the wheel event
1. `window.addEventListener("wheel", function (ev) { console.log([ev.wheelDeltaY, ev.deltaY]); });`
2. Try wheeling UP.
### Results(in my environment)
- Edge -> `[120, -116.8...]`
- IE11 -> `[undefined, -53.7...]`
- Firefox -> `[undefined, -3...]`
- Opera, Chrome -> `[120, -100]`
### In the sources of HOT CE 0.36.0
- tableView.js
`let deltaY = event.wheelDeltaY || event.deltaY;`
- overlays.js
`let deltaY = event.wheelDeltaY || event.deltaY;`
`let deltaY = event.wheelDeltaY || (-1) * event.deltaY;`

Applying `-1` to `event.deltaY` may **solve** the issue.
#### tableView.js
    if (!isChrome() && !isSafari()) {
        let deltaY = event.wheelDeltaY || event.deltaY;
This issue occurs only in Edge, even though the wheel event of Edge looks like that of Chrome.
#### helpers\browser.js
    var _isChrome = (/Chrome/.test(navigator.userAgent) &&
        /Google/.test(navigator.vendor));
Not only Chrome but also Opera returns true however Edge returns false. 

We could not find the reason why the code in tableView.js is needed even though Chrome can work without it. Anyway, `-1` may solve the issue.

**Comment by watnab** [comment]
> Applying -1 to event.deltaY may solve the issue.

In tableView.js, `-1` may have to be applyed to `wheelDeltaY` instead of `deltaY`.
- Chrome, Opera(and Safari?) ignore the code.
- IE11 and Firefox work with `deltaY` because `wheelDeltaY` is undefined.
- In Edge, `wheelDeltaY` may cause this issue.

**Comment by watnab** [comment]
#### overlays.js
    let deltaY = event.wheelDeltaY || event.deltaY;
    deltaY !== 0
The sign does not matter when you check whether the value is equal to zero or not.

    let deltaY = event.wheelDeltaY || (-1) * event.deltaY;
    syncScrollPositions(...);
- Anyway, `wheelDeltaY` and `deltaY` are opposite directions.
- The code decides which value should be inverted. `syncScrollPositions` may expect the sign of `wheelDeltaY`.

**Comment by AMBudnik** [comment]
That you so much for your feedback.

**Comment by AMBudnik** [comment]
Hi @jeremy-smith-maco, @watnab 

we have made some fixes on that issue in version CE 0.38.0/ PRO 1.18.0

Thank you for the feedback
