### ISSUE TITLE
Unknown culture : en

### ISSUE THREAD

**Issue by jmtolibas** [handsontable/handsontable#4321]
### Description
I updated my handsontable version, but got an unknown culture error.

![image](https://user-images.githubusercontent.com/11639583/27217099-c3f0bc62-5278-11e7-8105-4ffdc9c1975f.png)

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Chome
* Operating System: Linux Mint Serena

**Comment by AMBudnik** [comment]
Hi @jmtolibas 

Please check if you have the proper Numbro file included. Here is a working example http://jsfiddle.net/z8pysr6y/ using `en` language.
