### ISSUE TITLE
Customization of delay after which comment is showed

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4323]
### Description
We need to add an extra option to Comment plugin settings which will effect in customizing time after which comments appear.

**Comment by swistach** [comment]
Two things after review:
1. [ ] `updateSettings` should change settings of the comments plugin
2. [ ] unexpected behaviour of the comments after `mouseover` (example below)
![comments_displaydelay](https://user-images.githubusercontent.com/11849621/27426960-8b9e5efe-573d-11e7-8170-69bbe3462da7.gif)

**Comment by AMBudnik** [comment]
Thanks for adding :)
