### ISSUE TITLE
Table not fully rendered

### ISSUE THREAD

**Issue by marcosnc08** [handsontable/handsontable#4324]
### Description
**Table stops rendering and not all the data is shown on screen.**

![untitled-1](https://user-images.githubusercontent.com/5439902/27231119-f472b980-5287-11e7-8799-a1eb5a39d154.jpg)

As you can see, no error is shown on chrome console.

When you reload de page, its not necessarily stoping always in the same row. So, is not a problem with data in a particular row.

Also happened on Firefox.

### Steps to reproduce
I don´t have steps to reproduce.

### Demo
Only happening in some computers.

### Your environment
* Handsontable version: 0.24.1
* Browser Name and version: Google Chrome 58.0.3029.110
* Operating System: Windows 7
* Others: Backbone plugin, select2.js on some cells, custom renderer on cells, html on some cells

Thanks !

**Comment by AMBudnik** [comment]
Hi @marcosnc08 

Thank you for your effort to share this issue. However, if you cannot provide a demo or some steps to reproduce the issue there is not much what we can do. Additionally, we do not support Backbone anymore and select2 is a 3rd part library.
