### ISSUE TITLE
Common methods of editors are not working in a renderer

### ISSUE THREAD

**Issue by YakovL** [handsontable/handsontable#4325]
My intention is to add opening editor on clicking a cell. The idea is to create a custom renderer which sets a click handler like this:

    renderer: function (instance, td, row, col, prop, value, cellProperties)
	{
		var result = Handsontable.renderers.TextRenderer.apply(this,arguments);
		jQuery(td).click(function(){
			console.log("how dare you to click this cell?"); // works
			//# start editor
		});
		return result;
	}

According to [docs](http://docs.handsontable.com/0.25.0/tutorial-cell-editor.html), it is `EditorManager` which is responsible for selecting/preparing/displaying editors, but

    Handsontable.EditorManager.beginEditing();

in the place of "//# start editor" causes an error and

    Handsontable.editors.TextEditor. beginEditing();

or

    Handsontable.editors.TextEditor.prepare(row, col, prop, td, cellProperties);
    Handsontable.editors.TextEditor.beginEditing();

in that place also bring an error (`TypeError: Handsontable.editors.TextEditor.prepare is not a function`).

Here's [a demo](http://jsfiddle.net/s6t768pq/780/) (although it's for the up-to-date Hot v0.32.0 and I'm using 0.31.0; the issue stays there).

How do I call an editor from a renderer? Is there another way to open an editor on click? The proposed ways are the only ones I've found in docs..

**Comment by swistach** [comment]
Hi @YakovL 
I think you can use this solution to open an editor after cell selection:
http://jsfiddle.net/n9wxm5ng/

and here example, how to open an editor on click:
http://jsfiddle.net/Lb2Lg9vp/

**Comment by YakovL** [comment]
Thanks @swistach, both solutions work for me with the `afterSelectionEnd` approach being faster (less delay before opening the editor). Closing for now until any issues rise.
