### ISSUE TITLE
Classes defined in handsontable.d.ts cannot be extended

### ISSUE THREAD

**Issue by jennielynshapiro** [handsontable/handsontable#4326]
### Description
While trying to create a custom editor using Typescript I discovered that classes such as BaseEditor cannot be extended as they are currently defined in handsontable.d.ts. 

### Steps to reproduce
1. Install Handsontable 0.32.0 via npm
2. create TS file with
 `import Handsontable from "handsontable";`
and define a class
```
export class MyEditor extends Handsontable.editors.BaseEditor {
  constructor (hotInstance: Handsontable, row: number, col: number, prop: string | number, TD: HTMLElement, cellProperties: object) {
    super(hotInstance, row, col, prop, TD, cellProperties);
  }
}
```

You will get an error 

> Type 'Base' is not a constructor function type.

As a workaround i have added `typeof` to the declarations. For example:

```
  interface Editors {
    AutocompleteEditor: typeof editors.Autocomplete;
    BaseEditor: typeof editors.Base;
    CheckboxEditor: typeof editors.Checkbox;
    DateEditor: typeof editors.Date;
    DropdownEditor: typeof editors.Dropdown;
    HandsontableEditor: typeof editors.Handsontable;
    MobileEditor: typeof editors.Mobile;
    NumericEditor: typeof editors.Numeric;
    PasswordEditor: typeof editors.Password;
    SelectEditor: typeof editors.Select;
    TextEditor: typeof editors.Text | editors.Mobile;
    getEditor: (editorName: string, hotInstance: Core) => any;
    registerEditor: (editorName: string, editorClass: any) => void;
  }
```

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Google Chrome 59
* Operating System: Mac Os X

**Comment by AMBudnik** [comment]
@jennielynshapiro thank you very much for your effort to share the issue.
Can you take a look at this issue @swistach I think that it is related to the subject we've discussed a few hours ago?

**Comment by jennielynshapiro** [comment]
Just one additional note. In handsontable.d.ts where properties or return types are typed as "object"  , it may be better to type them as "any". 

For example while attempting to use TypeScript to implement the custom editor tutorial "SelectEditor - creating editor from scratch" section of http://docs.handsontable.com/0.32.0/tutorial-cell-editor.html

I am getting the error

> Property 'selectOptions' does not exist on type 'object'.

at the line 

`    var selectOptions:any = this.cellProperties.selectOptions;`

This is because cellProperties is typed to the restrictive object type instead of the any type

**Comment by astegmaier** [comment]
I hit the same issue as @jennielynshapiro, and the workaround she provided was super helpful and seemed to solve the problem of being unable to use the `extends` keyword in typescript to create an editor.

On exception is that if I try to create a typescript class that derives from `textEditor`...
```
export class xlEditorTs extends Handsontable.editors.TextEditor {...}
```
...I still get a compile error:
```
[ts] Type 'Mobile | typeof Text' is not a constructor function type.
(property) _Handsontable.Editors.TextEditor: typeof _Handsontable.editors.Text | _Handsontable.editors.Mobile
```
@AMBudnik or @swistach - would you be open to a PR along the lines of @jennielynshapiro's change? There might be deeper issues here, so I was curious if you thought a different fix would be necessary.

**Comment by astegmaier** [comment]
I created PR #4519 to attempt to address this issue.

**Comment by AMBudnik** [comment]
As the PR is merged we can close the issue.

Thanks again @astegmaier

**Comment by imageslr** [comment]
Hello @jennielynshapiro , I encountered same issue with you while I importing `Handsontable.plugins.BasePlugin`. The error is "Type 'Base' is not a constructor function type.". But I have already modified handontable.d.ts just like you:
```ts
// line 2287
  interface Plugins {
    AutoColumnSize: plugins.AutoColumnSize;
    Autofill: plugins.Autofill;
    AutoRowSize: plugins.AutoRowSize;
    BasePlugin: typeof plugins.Base; // here
  //...
}
```

But I still have the same issue. Could you please tell me how to do the **workaround** you mentioned? Thanks!
