### ISSUE TITLE
HTML Links not clickable

### ISSUE THREAD

**Issue by rosano** [handsontable/handsontable#4327]
### Description
HTML links (or even with type: html) should take you to their URL, but they do not. (Note that the problem is not that the link does not open in JSFiddle because of blocking, but that the link is basically not clickable even to receive javascript events)

### Steps to reproduce

1. use the columnSorting setting

### Demo
https://jsfiddle.net/rosano/1a1L4zr3/

### Your environment
* Handsontable version: 0.31.1 (but the fiddle is using the latest)
* Browser Name and version: Safari/Chrome latest
* Operating System: MacOS 10.12.4

**Comment by jeremy-smith-maco** [comment]
You could add **target="_blank"** to the <a> element.

**Comment by AMBudnik** [comment]
thank you for your suggestion @jeremy-smith-maco this actually solves the issue as JSFiddle block an attempt to open a new site inside the same window.

**Comment by rosano** [comment]
It's true that this does allow the link to open in a new window when using JSFiddle, but when running this locally where there are no attempts to block new sites, even target="_blank" does not seem to open the link. There is no error in the console, but I notice that if I try to inspect the element in Safari, the inspector is not able to take me to the element in the DOM. I also notice that if I find it manually and observe the CSS classes dynamically applied, there is a quick "fluttering" of classes as the mouse is pressed down.

I have a temporary fix by stopping event propagation in beforeOnCellMouseDown:

`
{
	columnSorting: {
		column: 0,
		sortOrder: true,
	},
	beforeOnCellMouseDown: function(event, coords, row) {
		if (coords.row !== 0 && coords.col !== 0) {
			return;
		};

		event.stopImmediatePropagation();
	},
}
`

**Comment by AMBudnik** [comment]
Yes, it may be the thing - stealing a focus from another element by the cell events. Thank you for sharing your workaround @rosano

**Comment by AMBudnik** [comment]
The redirection has been blocked by JSFiddle, the link opens correctly.
