### ISSUE TITLE
Copy-paste a column creates extra row

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4328]
Hi,

Default `copyRowsLimit` is 1000. When column has more than 1000 items then copying a whole column and pasting it to another column or to the same column leads to the following issues:
1) If I have 1300 rows, then when pasting 1000 items are pasted correctly, but items from 1001-1300 duplicates first 300 items of copied values.  So I have values from 1-1000 and from 1 to 300. Is it possible to turn off this behavior?
2) If I selected a whole column as paste source then 1001 item is copied, where 1001st item duplicates the very 1st item. If I select only 1 cell as paste source then it works correctly.

All these issues you can see in this demo video: https://www.screencast.com/t/CiD42wWknWt
JSFiddle: http://jsfiddle.net/o4rwf84j/12/

**Comment by AMBudnik** [comment]
Thank you very much for sharing. It is definitely a bug.

**Comment by AMBudnik** [comment]
The issue has changed.

Now we have the copy limit provided by the `copyPaste` plugin so the demo is http://jsfiddle.net/1x385kjk/

but now we are not able to paste data by selecting headers like we did it before. This would need to be a new issue. However the main issue is not replicable.
