### ISSUE TITLE
export csv,  can the exported CSV be rendered

### ISSUE THREAD

**Issue by aRealCat** [handsontable/handsontable#4329]
### Description

![csvStyle](https://github.com/aRealCat/gitskills/blob/master/csvStyle.png)

i  want to keep some html style like color or bold , for example ,i need the tableHeader keep  bold, 
 when i  export scv
 

### Steps to reproduce

-

**Comment by AMBudnik** [comment]
Hi @aRealCat 

.csv file can hold only data, we cannot export data with cell metadata

**Comment by aRealCat** [comment]
Thanks @AMBudnik 
 can i get the export data(.csv) and modify them before export .csv?

**Comment by AMBudnik** [comment]
If we are talking still about the styling it is not possible. Please check[ this article ](https://www.sitepoint.com/community/t/csv-file-and-applying-styles/3731)for more information.
