### ISSUE TITLE
Can't remove column if there is a type on the column

### ISSUE THREAD

**Issue by tlebreton** [handsontable/handsontable#4330]
### Description
If you put type on columns you can't remove column.
If you don't put type you can remove it

### Demo
http://jsfiddle.net/o3gshfpq/

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Chrome 59 Firefox 56
* Operating System: Debian 9

**Comment by AMBudnik** [comment]
@tlebreton 

if you use `columns` to define fixed number of columns you/user is not allowed to add or remove columns. This is intended. If you wish to allow it, I can create a demo for you.

**Comment by tlebreton** [comment]
in my case i need to define a type for the first column with the datetimepicker so i need to define a type for the column type . Is there an other way?
See this fiddle
http://jsfiddle.net/uvLk9p36/

**Comment by AMBudnik** [comment]
In this case, it will be better to use `cells` method. It allows you to define particular cells with ty[es and also give an ability to add and delete columns.

Here's a demo http://jsfiddle.net/1jye6naL/

**Comment by tlebreton** [comment]
Nice one dont read the doc enough thank you for the quick answer and keep up the good work
