### ISSUE TITLE
Handsontable, wrong formula evaluation and rendering

### ISSUE THREAD

**Issue by nicoraV** [handsontable/handsontable#4332]
In a **Handsontable**, in parent/child structure where on `parent rows` I have formulas and on `children values`.

```
var data2 = [
    ['4709', '=B$2', '=C$2', '=D$2', '=E$2', '=F$2'],
    ['4709-001', '=B$3', '=C$3', '=D$3', '=E$3', '=F$3'],
    ['4709-001-02', '=B$4+B$8', '=C$4+C$8', '=D$4+D$8', '=E$4+E$8', '=F$4+F$8'],
    ['4709-001-02-02', '=SUM(B5;B7)', '=SUM(C5;C7)', '=SUM(D5;D7)', '=SUM(E5;E7)', '=SUM(F5;F7)'],
    ['4709-001-02-02-01', 1, 2, 3, 4, 5],
    ['4709-001-02-02-02', 6, 7, 8, 9, 10],
    ['4709-001-02-02-03', 11, 12, 13, 14, 15],
    ['4709-001-02-03', '=SUM(B9;B12)', '=SUM(C9;C12)', '=SUM(D9;D12)', '=SUM(E9;E12)', '=SUM(F9;F12)'],
    ['4709-001-02-03-01', 1, 2, 3, 4, 5],
    ['4709-001-02-03-02', 6, 7, 8, 9, 10],
    ['4709-001-02-03-03', 11, 12, 13, 14, 15],
    ['4709-001-02-03-04', 16, 17, 18, 19, 20]
];

var container1 = $('#example1');

container1.handsontable({
    data: data2,
    minSpareRows: 1,
    colHeaders: true,
    rowHeaders: true,
    contextMenu: true,
    manualColumnResize: true,
    formulas: true
});
```

The problem is that on handsontable load the **formulas on higher parents are not rendered**. I have to click or edit some cells in order to get it rendered.
This problems appears on handsontable free version (which use formula.js and rule.js) and even on handsontable pro.
For a complete example see the jsfiddle.

Here is a jsfiddle of free version: http://jsfiddle.net/4g23e6px/2/ and this for pro version: http://jsfiddle.net/gmoe28km/3/.

Thanks.

**Comment by AMBudnik** [comment]
Thank you for sharing @nicoraV I have marked the issue as a bug.

We have published Formula Support on HAndsontable PRO but please remember that it is an alpha stage plugin and we do not recommend using more complicated calculations on production.

**Comment by AMBudnik** [comment]
The issue does not happen if we use the formulas plugin instead of RuleJS

http://jsfiddle.net/p3ode7uq/ (`7.1.1`)

![Zrzut ekranu 2019-09-27 o 10 31 31](https://user-images.githubusercontent.com/10757813/65754747-fdc8ce00-e111-11e9-8ef6-e1e97c6f274e.png)
