### ISSUE TITLE
Scroll bars should follow handsontable size, not its container

### ISSUE THREAD

**Issue by snaplemouton** [handsontable/handsontable#4333]
### Description
I have a dynamic table which data will change depending on filters. The table has enough columns to have horizontal scrolling and depending on the data from the filtering, may or may not have vertical scrolling. The problem appears when we go from a lot of rows to less rows than the "set" height of the container holding the handsontable.

See below image for example:

![image](https://user-images.githubusercontent.com/4615537/27387415-aa20fefe-5666-11e7-9954-0b3e88156dbd.png) ![image](https://user-images.githubusercontent.com/4615537/27387464-cbc0ce18-5666-11e7-8de5-e3333aa078ab.png)

This is bad for UX. The scroll bar should be next to the 20th line in the second screenshot, not at the bottom of the container holding handsontable.

### Steps to reproduce

1. Create a table with scrolling like shown in this [tutorial](https://docs.handsontable.com/0.25.1/demo-scrolling.html).
2. Dynamically change the data to have more rows than the height allows or less rows than the height allows.

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Chrome 58
* Operating System: Windows 10

**Comment by KMASubhani** [comment]
If you scroll up and cannot see the gap anymore, are you able to scroll back down?

**Comment by AMBudnik** [comment]
Hi @snaplemouton 

Currently, Handsontable is not responsive so if you would like to have a fixed height for larger datasets and accordingly smaller height for less data you would need to change the `height` of the instance. It the change corresponds to filtering you can push the `height` changes via `afterFilter` callback.
