### ISSUE TITLE
Checkbox Cell Type - Support of indeterminate state ?

### ISSUE THREAD

**Issue by marc-antoinepelletier** [handsontable/handsontable#4334]
Hi,

I was wondering if you will support the indeterminate state of a checkbox at some point ?

Use case : 
- Nested Rows with checkbox column type
- Children rows are selected programmatically if you select the parent
- Parent become indeterminate if not all the children rows are selected

**Comment by AMBudnik** [comment]
Hi @marc-antoinepelletier 

we do not have a similar feature but you can do it programmatically. Here's a great article written by one of our devs about setting custom cell dependencies: https://handsontable.com/blog/articles/expand-your-app-with-cell-dependencies.

NestedRows is still a plugin in an early stage of development so some options may be harder to develop but it all depends on your expectations. Here http://jsfiddle.net/thyv93m3/ is a pretty simple example on how it can be done. I even did not use any FOR loops just to show how it is all done. I call an `afterChange` hook to tell me if a parent checkbox has been unchecked and if it was I uncheck all its children.
