### ISSUE TITLE
Rendering different objects type in different row

### ISSUE THREAD

**Issue by loup-kreidl** [handsontable/handsontable#4339]
Hello,

I'm posting here for two reasons, the first one is that i'm having an issue with my custom renderer, and I also could use some tips!

I have an object which looks like this:
![screenobjecthandson](https://user-images.githubusercontent.com/24678300/27489044-6619105a-5839-11e7-8c8b-d045f0fb03f9.png)

It can be resumed this way: an user has a list of projects, those projects have a weeks dict, in which I store weeks (WoW!), and the key is their starting day's date. In those weeks I got days, for which the key is also their dates. In the days we can find my two interesting informations the 'payroll', and the 'timelogs' those are integers.

I want to display those informations this way:

empty | empty | date1 | date2 | date3 
------------ | ------------- | ------------- | ------------- | -------------
username | empty | pr1-tl1 | pr2-tl2 | pr3-tl3 
project1 | timelogs | tl1 | tl2 | tl3
project2 | payroll | pr1 | pr2 | pr3
project2 | timelogs | tl1 |  tl2 | tl3 

Content in the first column | Content in the second column

I use 3 custom renderers to obtain this, but not in a very good looking way, my hot.data looks like this:

```javascript
[
    ['', '', date1, date2, date3,...],
    [{user{name, projects}}],
    [user.projects[0]],
    [user.projects[2]],
]
```

And I process the datas by looking into which line we currently are, the type of object wich is in it, if it's a user I use a UserRenderer, if it's a project I look if the object in the precedent line is the same project, if it is then, I go for a Timelog line if it isn't it's a Payroll line.

I'm not really sure this is the best way to do it, does someone have an advice?
Plus this causes a strange bug when I scroll left to right then right to left: the data's are moving between the cells.

Here it's ok:
![screenokmi](https://user-images.githubusercontent.com/24678300/27490031-14610854-583d-11e7-9a38-17b93c5d8db3.png)

Then it's kind of messed up:
![screennotokmi](https://user-images.githubusercontent.com/24678300/27490053-2896bb34-583d-11e7-8e67-38a0340a601e.png)

**Comment by AMBudnik** [comment]
Hi @loup-kreidl 

First of all, I have to admit that I am not sure if I understood the case. You have posted a lot of information I but got lost a little bit. As I assume you are using some kind of renderer for predefined cell type, right?

If you could share the custom renderer logic and the nested object in a demo (JSFiddle, JSBin) I can check what is causing the misalignment.

**Comment by loup-kreidl** [comment]
Yeah it's a whole project, and a little bit complex to be resumed in a simple post, or to recreate in a JsFiddle, I hope I can explain this here, because making a demo of this doesn't seems really simple.

My HandsonTable instance:

```javascript
this.hot = new Handsontable(container, {
    data: this.data,
    rowHeaders: false,
    colHeaders: false,
    dropdownMenu: false,
    cells:function (row, col, prop) {
        const cellProperties = {};
        if ( row ===0 ) {
            cellProperties.renderer = handsontableHandler.renderer.datesRenderer;
        }
        else if ( row >= 2 ) {
            if(handsontableHandler.data[row].type === 'user'){
                cellProperties.renderer = handsontableHandler.renderer.userRenderer;
            }
            else if ( handsontableHandler.data[row].type === 'project' ) {
                cellProperties.renderer = handsontableHandler.renderer.projectRenderer;
            }
        }
        return cellProperties;
    }
});
```

I'm trying to display three different thing: 
    - dates (in the first two row). To obtain this, I Store an array of dates. The dateRenderer:

```javascript
datesRenderer: function (instance, td, row, col, prop, value, cellProperties) {
    if ( typeof value === 'object' ) {
        value = new Date(value);
        value = value.getDate()+' - '+calendar.monthsList[value.getMonth()];
    }
    $(td).empty();
    // I want the date to be rotated (but even without this modification I still got the render problem)
    $(td).append('<span><p>'+value+'</p></span>');
    $(td).addClass("rotated-text");
    $('span', td).addClass('rotated-text__inner');
    return td;
}
```

 - project: There is two crucial information stored in the project: the payroll and the timelogs. Those two are indexed by their date, and have to be displayed in two different lines. Here is my project renderer:

```javascript
projectRenderer: function (instance, td, row, col, prop, value, cellProperties) {
    if ( col === 0 ){
        $(td).text(handsontableHandler.data[row].name);
    } else if ( col === 1 ) {
        if( handsontableHandler.data[row-1].type === 'project'
            && handsontableHandler.data[row-1].name === handsontableHandler.data[row].name) {
            $(td).text('TimeLog');
        } else {
            $(td).text('PayRoll');
        }
    }else {
        let categ = '';
        const date = handsontableHandler.data[0][col];
        if( handsontableHandler.data[row-1].type === 'project'
            && handsontableHandler.data[row-1].name === handsontableHandler.data[row].name) {
            categ = 'TimeLog';
        } else {
            categ = 'PayRoll';
        }
        const value = handsontableHandler.data[row].getValueFromDate(date, categ);
        $(td).text(value);
    }
}
```

 - user: in the user are stored the projects (each user has his own projects, and in those the user's payroll and timelogs)  later i'll have to display the difference between the payroll and timelog value for each date. And the UserRenderer:

```javascript
userRenderer: function (instance, td, row, col, prop, value, cellProperties) {
    $(td).empty();
    if ( col ===0 ) {
        $(td).text(handsontableHandler.data[row].name);
    }
    return td;
}
```

My original object looks like this:

![objectuser](https://user-images.githubusercontent.com/24678300/27546050-e1692d6c-5a91-11e7-9e39-f1dc9a159185.png)

But I store it in a different way to display it with handsonTable:

![handsonobject](https://user-images.githubusercontent.com/24678300/27546077-fa7312aa-5a91-11e7-9a4d-85798fcbd187.png)

I think there is a better way to obtain what I want... I hope it's a little bit clearer (first time on something this complex and first time I had to explain what I'm doing on github)? 
Regarding to the rendering issue, I could record it on a YouTube clip or something if it help to see what's going on?

**Comment by loup-kreidl** [comment]
In fact I'd like to declare for each user i've got, 1+(2*user.projects.length) rows and bind the data by row by date

**Comment by AMBudnik** [comment]
Unfortunately, this subject exceeds my ability to help but I will ask our developers to take a look at this ticket.

ps. yes, if you think that the video will come in handy we'll appreciate,

**Comment by loup-kreidl** [comment]
I find a different way to obtain what I want, by storing references to my object's data into a classic data array. But if you find a way to answer the original issue it would be interesting!
The rendering issue seems to vanish if I put an 300% width and an important padding on the left for my html and body. 
Thanks for your support!
I'll try to capture the issue as soon as possible!

**Comment by loup-kreidl** [comment]
I solved my issue by adding `renderAllRows: true`. The data aren't moving around any more
