### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by ShirishResilinc** [handsontable/handsontable#4340]
### Description
I have requirement of changing a cell's value depending on edited cell or vice versa. in which i have used before change hook where i change the dependent cell's value and push it to changes. In this process if content is greater than column width then it wraps up. So i cleared cache of changed columns which disturbs scrolling functionality 
i tried idea from blog mentioned below:
https://handsontable.com/blog/articles/expand-your-app-with-cell-dependencies 
but it affects undo functionality

### Steps to reproduce
1. Edit in 2nd last cell then it will scroll to first column
2. Again edit in 2nd last column
3. Scroll will move to empty area
4. Now move the horizontal scroll again. it will disturb the headers

### Demo
http://jsfiddle.net/08ds2khs/

### Your environment
* Handsontable version: 0.31.2
* Browser Name and version: Chrome
* Operating System: Win 10

**Comment by AMBudnik** [comment]
Hi @ShirishResilinc as it is a pretty much custom option I just recommend adding `scrollViewportTo` option to scroll back to cell `(0, 0)`. Here is a working demo http://jsfiddle.net/5pnnumr9/
