### ISSUE TITLE
Shim for WalkontableTableRenderer#renderColumnHeader

### ISSUE THREAD

**Issue by 2chen** [handsontable/handsontable#4344]
### Description
We are currently shimming `WalkontableTableRenderer#renderColumnHeader` on Handsontable 0.24.2. This is not ideal (and not possible to do on 0.32.0) and I would love to work out a way to get rid of this shim.

Why the shim? We are rendering React elements inside custom column headers. The proper way to do this via hooks is to use the `afterRenderColHeader` hook, but by the time that hook runs, Handsontable has already redrawn new headers. This interacts poorly with what we are trying to do.

The solution we arrived at is shimming `WalkontableTableRenderer#renderColumnHeader` (accessing it via `window.WalkontableTableRenderer`), which works well but is blocking us from upgrading. It would be much more preferable to us if there were a configurable way to change how column headers are rendered further up the rendering process than `afterRenderColHeader`

Maybe this already exists? Am I missing anything?

### Your environment
* Handsontable version: 0.24.2
* Browser Name and version: Chrome 58.0
* Operating System: OS X 10.12

**Comment by AMBudnik** [comment]
Hi @2chen 

sorry for a delay. Have you managed to skip the shim?

Have you tried our React wrapper?
