### ISSUE TITLE
[1.10.2+] Cell edit corrupts filter formulas

### ISSUE THREAD

**Issue by arrdev** [handsontable/handsontable#4345]
### Description

After any cell is edited, the filter that was applied previously to another column changes arguments to the values of the edited column.

### Steps to reproduce

1. Create a table with at least 2 columns with values.
2. Open filter on the first column, uncheck some of the values from and filter.
3. Check the formulaCollection of the filter plugin - the arguments of the filter are correct.
4. Edit any cell in second column.
5. Check formulaCollection again.
Actual result: the arguments of the previously added filter are corrupted and now equal to the values of the edited column.
Expected: formulaCollection should stay the same since it wasn't changed.

### Your environment
* Handsontable version: latest handsontable pro
* Browser Name and version: Chrome 58.0.3029.110 (64-bit)
* Operating System: Windows 7 Enterprise

**Comment by arrdev** [comment]
Update: this issue can even be seen via UI.
1. Apply some filters by value on any column.
2. Edit any value in any other column.
3. Open the original filter.
Result: all values are deselected.

Js fiddle:
https://jsfiddle.net/8qz0hb3a/

**Comment by AMBudnik** [comment]
Thank you for sharing this issue @arrdev 
I have replicated the same result.

The corresponding internal ticketing issue no # 162.

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/4780

**Comment by AMBudnik** [comment]
The issue is no longer replicable in  v 5.0.0
