### ISSUE TITLE
Horizontal Scroll missing inside filter

### ISSUE THREAD

**Issue by s1a2t3y4** [handsontable/handsontable#4346]
### Description
For allmost any of my filters the filterbox is to small.
The user should be able to scroll it horizontally to see full name.

### Steps to reproduce

1.Open the JSFiddle attached below
2.click on C column filter
3.text is hidden under scrollbar.there is no horizontal scrollbar

### Demo
http://jsfiddle.net/satyavulisetti/08rzry3L/8/

### Your environment
* Handsontable version:1.10.2
* Browser Name and version:chrome Version 58.0.3029.110 (64-bit)
* Operating System:ubuntu 14.04

**Comment by AMBudnik** [comment]
Hi @s1a2t3y4 

we have been reported a similar feature request some time ago at https://github.com/handsontable/handsontable/issues/4285
Do you also think that it's a good choice to go with a resize handler?

**Comment by AMBudnik** [comment]
We take a look at this issue while adding #4285

**Comment by PradeepNP** [comment]
here is the demo where the first column's data are lengthy and not able to see the data completely. Is there any way to enable the horizontal scroll on the filter.

http://jsfiddle.net/paddunp/6svw5mq7/2/

**Comment by AMBudnik** [comment]
Hey @PradeepNP
You can change the width of the dropdown menu container > lines `49 -55`
demo http://jsfiddle.net/y1po2md0/
but there is no API-way to add a scroll.

**Comment by PradeepNP** [comment]
Thank you @AMBudnik 
The problem is here, the column content length is dynamic. Some time is very huge. In that case it still the above-fixed length won't help. I got that there is no API to add scroll.

**Comment by AMBudnik** [comment]
It looks like if you add `overflow: 'scroll' `to the `htCheckboxRendererLabel` class you can scroll right/left on the option. The scrollbar is not visible but the action is available.
Demo http://jsfiddle.net/AMBudnik/72fozvst/

**Comment by PradeepNP** [comment]
Sorry, that looks very bad.
