### ISSUE TITLE
afterSetDataAtCell reverting data set programatically

### ISSUE THREAD

**Issue by graemeharnish** [handsontable/handsontable#4347]
### Description
Hello.  After calling afterSetDataAtCell I set data in my data structure programatically.  It's set in the data object, but the data gets reverted (this only happens to the cell that is being changed, other altered cells changed programmatically are fine)
### Steps to reproduce

1.  Call afterSetDataAtCell.  Set data[0].currentCell = 'new'
2.  Set data[0].otherCell = 'new data'
3.  Observe results.  The currentCell reverts to what was entered by the user.  The otherCell is not reverted

### Your environment
* Handsontable version:  1.11.0
* Browser Name and version:  Chrome Latest
* Operating System: Mac OSX

**Comment by graemeharnish** [comment]
Ah, looks like if you set changes[0] = null it stops the propagation of data and fixes the error.

**Comment by AMBudnik** [comment]
I can see that you've found the case. Thank you for a quick update. I am closing the issue.
