### ISSUE TITLE
Feature request: Add an option to init collapsible columns collapsed

### ISSUE THREAD

**Issue by ChristianKohler** [handsontable/handsontable#4349]
### Description
We need to have some columns collapsed by default. Currently we initialize the grid and the call:

```
const plugin = this.hot.getPlugin('collapsibleColumns');
plugin.collapseSection(coords);
```

This works buts it looks ugly since the grid first initializes expanded and then collapses visible.

### Feature request
Add option to init columns collapsed.

**Comment by AMBudnik** [comment]
Thank you for sharing the idea @ChristianKohler 
You're right, this will save us some coding and excessive operations like opening and then closing the sections.

**Comment by AMBudnik** [comment]
Thank you for sharing the idea We have accepted it and copied to our feature request list at [Wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by Rex90** [comment]
@ChristianKohler after which callback do use that function? afterInit, afterRender? etc? 

cheers

**Comment by AMBudnik** [comment]
Hi @Rex90 

this example should help http://jsfiddle.net/handsoncode/cLvyr997/

**Comment by Rex90** [comment]
Hi @AMBudnik  -  This appears to work but for some reason on my end I am unable to get it to work for 'some' of my tables because I'm trying to do the following and the plugin settings are not always available..

```
		if (self.hot.getPlugin("collapsibleColumns").settings) {
			self.hot.getPlugin("collapsibleColumns").settings.forEach(function(stng) {
				if (stng.collapsedOnInit === true) {
					self.hot.getPlugin("collapsibleColumns").collapseSection({
						row: stng.row,
						col: stng.col
					})
				}
			})
		}
		else{
			console.error("settings not defined");
		}
```

**Comment by Rex90** [comment]
@AMBudnik thank you - the example works but for some reason when I run it on my table instance the collapseSection function only changes the icon of the collapse button but doesnt actually collapse the table =[

```
			self.hot.getPlugin("collapsibleColumns").collapseSection({
				row: -2,
				col: 12
			})
```

**Comment by AMBudnik** [comment]
Hi @Rex90 

can you send me the app via JSFiddle? Maybe there are some other settings that are blocking it.
You can also try adding `hot.render` after `collapseSection` or the same thing in a `setTimeout` with ~10ms delay.

**Comment by AMBudnik** [comment]
I'm transferring this issue into a discussion.
Please feel free to leave your comment and suggestion for this change.
