### ISSUE TITLE
Misalignment when table data did change.

### ISSUE THREAD

**Issue by bellcliff** [handsontable/handsontable#4350]
### Description
Update table data cause misalignment.

### Steps to reproduce

1. demo link: http://jsfiddle.net/bellcliff/1uj4mw7g/
2. scroll to the right bottom corner
3. click button "add B1"

### Demo

http://jsfiddle.net/bellcliff/1uj4mw7g/

### Your environment
* Handsontable version: 0.31.0 and 1.11.0
* Browser Name and version: Chrome 58
* Operating System: Windows 10

**Comment by bellcliff** [comment]
![capture](https://user-images.githubusercontent.com/535209/27611659-17d53a9c-5b61-11e7-864e-5ac2ab8c5586.PNG)

**Comment by AMBudnik** [comment]
Hi @bellcliff It doesn't look the same on Chrome 59/Win 10 

![gif](https://user-images.githubusercontent.com/10757813/27636779-6fb9db1c-5c0d-11e7-9071-4c0abcac5df6.gif)
but I also got the misalignment that should be handled by `autoRowSize`, while it's not.

Thank you for your effort to share and investigate this issue.

**Comment by bellcliff** [comment]
Hi @AMBudnik , do we have a plan on this, and how long do we suppose to get it fix?

**Comment by AMBudnik** [comment]
@bellcliff currently not, but I can truly understand why this can be frustrating. The table does not look pleasant and it is hard to guess which row corresponds to the higher cell.

I will mention this issue on our next team meeting and we will see if it can be a part of our next to-do list. As soon as we will be able to fix the issue me or one of my colleagues will update the issue.

**Comment by AMBudnik** [comment]
ps. till the issue gets fixed you can use the following workaround http://jsfiddle.net/1uj4mw7g/7/ where we clear the cache by `clearCacheByRange` method from the `autoRowSize` plugin.

**Comment by bellcliff** [comment]
Thanks for the quick response! And the perfect solution for now.

**Comment by AMBudnik** [comment]
Issue is still replicable in version 0.35.0

![image](https://user-images.githubusercontent.com/10757813/35222737-2a5a6472-ff7f-11e7-91e9-d3d39c904d5a.png)

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by wojciechczerniak** [comment]
Please do not modify `data` outside of Handsontable. We have an API for that: http://jsfiddle.net/rw29mng0/1/

We have to know what has changed so we can redraw Handsontable correctly.
