### ISSUE TITLE
Clean NPM package

### ISSUE THREAD

**Issue by CedricMalfreytBL** [handsontable/handsontable#4351]
### Description
The NPM package includes folders and files that are not needed like the demo, src and test folders.
Maybe other folders or files are not needed too.
Please, can you clean the package ?

Thank you !

### Steps to reproduce
Install the npm package via
```
npm install handsontable
```

### Demo
This is the screenshot of the package content :
![image](https://user-images.githubusercontent.com/8135706/27640641-1e137f0e-5c1a-11e7-8981-e10516985456.png)

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Chrome 59.0.3071.115
* Operating System: Windows 7 Enterprise SP1

**Comment by AMBudnik** [comment]
Hi @CedricMalfreytBL 
Thank you for sharing your opinion.

`commonjs` is used by Node, which supports only native system of loading (CommonJS), `dist` is made for the browser, `es` also for Node for handling `import/export` actions, `lib` and `src` for buiding Handsontable PRO and `test` for testing PRO.
I guess that we could remove `demo`, however, for less experienced Clients I think that it should stay. I will mark the topic an as improvement suggestion.

**Comment by AMBudnik** [comment]
Thank you for sharing the idea. It has been approved and moved to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions).

As soon as the idea gets picked by a developer the issue is reopened and updated.

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. Please free to continue the conversation there. Thank you.
