### ISSUE TITLE
When the cell type is numeric, the formula does not work properly.

### ISSUE THREAD

**Issue by ssbunny** [handsontable/handsontable#4353]
### Description

When the cell type is numeric, the formula does not work properly.

### Steps to reproduce

1. set `formulas` to `true`;
2. set cell `A2` type to `numeric` , value `=A1+B1`;
3. double click `A2`, click other place, double click `A2` again.

### Demo

https://jsfiddle.net/6r3bse4L/2/

### Your environment
* Handsontable version:  pro-1.11.0
* Browser Name and version: Safari 9.0.2 / Chrome 58.0.3029.110 (64-bit)
* Operating System: OS X 10.11.2

**Comment by ssbunny** [comment]
It looks like the number is treated as a string.

**Comment by ssbunny** [comment]
![8668c4a0-83d6-4833-9868-54b95a100fe0](https://user-images.githubusercontent.com/2247291/27676764-cb14478e-5ce1-11e7-88e8-543f79c6bbe8.png)
![1a8266fd-310e-468f-a5d2-c70ed0f935bd](https://user-images.githubusercontent.com/2247291/27676766-cb54581a-5ce1-11e7-8682-693aea61dc34.png)
`A1` + `B1` = 11
`B2` + `A1` = 21

**Comment by AMBudnik** [comment]
Thank you for sharing the issue. I have replicated the same result.

**Comment by ssbunny** [comment]
I found the problem:
https://github.com/handsontable/handsontable/blob/master/src/core.js 
function `validateChanges`
![2748cd72-efff-4410-b559-3c7cbb3eba1c](https://user-images.githubusercontent.com/2247291/27682503-61c62fd6-5cf5-11e7-8e2a-9df6e692fc54.png)

**Comment by AMBudnik** [comment]
Thank you for your investigation. It looks like you found a very important clue. When it comes to the Formula Support plugin we have a lot of work to do to make it work correctly. That's why it was set as an alpha stage plugin in the first place.

Thanks again and wish you a great day.

**Comment by pnowak** [comment]
Now work well - https://codesandbox.io/s/intelligent-firefly-diley

**Comment by AMBudnik** [comment]
@pnowak is right. Works well (just tried it with 7.4.2 https://jsfiddle.net/AMBudnik/1n9d4hz2/)
I'm closing this topic.
