### ISSUE TITLE
handsontable.d.ts is broken

### ISSUE THREAD

**Issue by Narazaka** [handsontable/handsontable#4355]
### Description
https://github.com/handsontable/handsontable/commit/9535a33c1998ec9f34cd47397e3d52257024ebd3 has broken handsontable.d.ts.

Current handsontable.d.ts says that

```typescript
export default class Handsontable extends _Handsontable.Core {
  ...
}
```

then import in TypeScript should be wrote as below.

```typescript
import Handsontable from "handsontable";

const ht = new Handsontable();
```

this script will be transpiled as below.

```javascript
var Handsontable = require("handsontable").default;

var ht = new Handsontable();
```

but `require("handsontable").default` is undefined!

Previous handsontable.d.ts was correct.

```typescript
declare class Handsontable extends hot.Core {
  ...
}

export = Handsontable;		
export as namespace Handsontable;
```

then import in TypeScript should be wrote as below.

```typescript
import Handsontable = require("handsontable");

const ht = new Handsontable();
```

this script will be transpiled as below.

```javascript
var Handsontable = require("handsontable");

var ht = new Handsontable();
```

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Chrome
* Operating System: Windows
* TypeScript version: 2.4.1

**Comment by AMBudnik** [comment]
@swistach can you check it please?

@Narazaka thank you for sharing.

**Comment by Zenoware** [comment]
Is there any plans to update the current d.ts?  It appears to be a few versions behind.  Current version is 0.33 for handsontable.js but the handsontable.d.ts is referencing 0.31.

Some things would be very nice to have like validateCells returning valid, etc.

**Comment by swistach** [comment]
@Narazaka: I'll try to make possible, to run properly Handsontable using `import` and `require`.

@Zenoware: we will update current d.ts file. Referencing to v0.31.0 is just a mistake. We forgot to change it. @jansiegel We should remember about this one in the future.

**Comment by Zenoware** [comment]
@swistach does that mean what is currently in typings is up to date?  If so, I noticed validateCells should return a boolean on the callback if I am reading the handsontable documentation correctly.

**Comment by astegmaier** [comment]
I created PR #4519 to attempt to address this issue.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/pull/4519
