### ISSUE TITLE
Changes related to new naming policy inside Filters plugin

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4358]
### Description
We will change the name of filter expressions by which column are filtered. As far filtering conditions have been called `formulas`. From now we will call them just `conditions`. It's related to clarifying naming convention (connected with the fact that already exists `Formulas` plugin).

API will change. For example from function `addFormula` to `addCondition` as shown in examples below.

From:

```js
hot.getPlugin('filters').addFormula(1, 'begins_with', ['de']);
```

to:

```js
hot.getPlugin('filters').addCondition(1, 'begins_with', ['de']);
```
 
From:

```js
hot.getPlugin('filters').removeFormulas();
```

to:

```js
hot.getPlugin('filters').removeConditions();
```

From:

```js
hot.getPlugin('filters').clearFormulas();
```

to:

```js
hot.getPlugin('filters').clearConditions();
```

Within this task will be done all needed changes to Community Edition of Handsontable.

**Comment by AMBudnik** [comment]
Happy to see updated docs as well. Thanks.
