### ISSUE TITLE
Custom cell editor

### ISSUE THREAD

**Issue by myisis** [handsontable/handsontable#436]
This is not exactly a bug, but more of a question. How can I add a custom cell editor? I followed the Handsontable.AutocompleteEditor, but it's very difficult for me to figure out what's typeahead related and what's generic for other editors. I figured out that the first point of entrance seems to be `onDblClick()` from which the editor is started, but things like ` texteditor.beginEditing(instance, null, row, col, prop, keyboardProxy, true);` aren't really accessible from outside of the jquery.handsontable.js file in a require.js environment which causes my custom editor to fail (this call may not be needed).

Anyway, some help on this would be appreciated.

Thanks.

**Comment by AMBudnik** [comment]
For more information, please track changes to https://github.com/handsontable/handsontable/issues/391 issue.
