### ISSUE TITLE
when I copy/paste a cell data to a new cell handsontable not take it as change. How will I resolve it?

### ISSUE THREAD

**Issue by dinkar2010** [handsontable/handsontable#4361]
### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @dinkar2010 

Can you share more details?

If you copy any cell and paste it you should get a response from `afterChange` hook. Here's an example: http://jsfiddle.net/ej9wr509/

**Comment by dinkar2010** [comment]
thanks AMBundik.
I have resolved the issue. 
The problem was when I copy a row data and pasting in new row afterchange() doesn't detect changes. By usijng if (source == 'edit' || source == "CopyPaste.paste") I can get the pasted data.

**Comment by AMBudnik** [comment]
OK, thank you for a quick update.
