### ISSUE TITLE
Press tab to go to the next row when a user has tabbed to the end of a row

### ISSUE THREAD

**Issue by jongunter** [handsontable/handsontable#4364]
When a user presses the `tab` key to move horizontally across the grid and they reach the end of the row, the tab key no longer does anything. This is fine, as it matches the behavior of Google Docs/excel. 

However, it would certainly be nice if there was option to continue to the next row if the user presses `tab` on the last cell in a row.  I've discovered that some users apparently expect this behavior (I guess because it's how some other HTML form grids work).

**Comment by AMBudnik** [comment]
Hi @jongunter 

you can accomplish pretty similar goal via `afterDocumentKeyDown` event.
Here's a demo that does that http://jsfiddle.net/8c4xt3a8/
