### ISSUE TITLE
Add Input Mask Cell Type

### ISSUE THREAD

**Issue by jongunter** [handsontable/handsontable#4365]
It would be helpful if there could be a "mask" cell type that works like a text input, but with an input mask, using a library like: https://github.com/RobinHerbots/Inputmask

**Comment by jongunter** [comment]
If anyone is interested in this use case, here's the code I used that worked. I hope this will one day be officially supported, as input masks are incredibly useful across many different types of applications
```
// This example creates a date editor that will show MM/YYYY
const SpecialDateEditor = Handsontable.editors.TextEditor.prototype.extend();

SpecialDateEditor.prototype.createElements = function () {
    Handsontable.editors.TextEditor.prototype.createElements.apply(this, arguments);

    var im = new Inputmask('99/9999');

    // Create password input and update relevant properties
    this.TEXTAREA = document.createElement('input');
    this.TEXTAREA.setAttribute('type', 'text');
    this.TEXTAREA.className = 'handsontableInput';
    im.mask(this.TEXTAREA);
    this.textareaStyle = this.TEXTAREA.style;
    this.textareaStyle.width = 0;
    this.textareaStyle.height = 0;

    // Replace textarea with password input
    Handsontable.dom.empty(this.TEXTAREA_PARENT);
    this.TEXTAREA_PARENT.appendChild(this.TEXTAREA);

};
```

**Comment by AMBudnik** [comment]
Thank you for sharing your suggestion @jongunter

**Comment by AMBudnik** [comment]
Thank you for sharing the idea. It has been approved and moved to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions).

As soon as the idea gets picked by a developer the issue is reopened and updated.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
