### ISSUE TITLE
ESlint rules update

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4366]
### Description

To [prevent this bug](https://github.com/handsontable/handsontable/pull/4359) I suggest adding a rule to the ESLint. This rule will be responsible for checking if any of commits does not contain code which directly touches a `Handsontable` variable.

### Steps to reproduce

1. Build Handsontable example using browserify (or webpack etc.).
2. Open a `dropdown` editor.
3. There will be an error about trying to access to `Handsontable` variable which does not exist.

### Your environment
* Handsontable version: 0.32.0

**Comment by AMBudnik** [comment]
Thanks for adding @budnix

**Comment by budnix** [comment]
No problem, it was a pleasure 😄
