### ISSUE TITLE
"isObjectEquals is not defined"

### ISSUE THREAD

**Issue by mohithg** [handsontable/handsontable#4367]
### Description

On clicking a column in the table the sorting should happen, but it throws an error saying "isObjectEquals is not defined" since it is not imported

### Steps to reproduce

1. Click on any column with sorting enabled

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Chrome 59
* Operating System: Mac OS Sierra

**Comment by mohithg** [comment]
Fixed in https://github.com/handsontable/handsontable/pull/4368

**Comment by AMBudnik** [comment]
Hi @mohithg 
thank you for sharing. The changes have been added to the newest version of Handsontable.
