### ISSUE TITLE
performance slow

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#4373]
Hi,
   what is the maximum number of rows  and cols handsontable can supports?.
because when i using with 38k rows and 10 cols ,it get slow while rendering last 5000+ records.
how can i improve the performance?

**Comment by AMBudnik** [comment]
Hi @Sundarcj 

Here https://docs.handsontable.com/pro/1.11.0/tutorial-performance-tips.html you can find our performance tips. Usually, the more rows you have the performance of loading data is lower. We do not have any magic barrier as the feeling or something being too slow is subjective. 

When you feel that the performance is getting lower you can use pagination (ideally server-side one) to load parts of data.

Please also notice that using custom renderers and complex data structures also have a big influence of rendering and scrolling.
