### ISSUE TITLE
How to bind multiple events in same hooks

### ISSUE THREAD

**Issue by amarlearning** [handsontable/handsontable#4374]
### Description
How can I bind multiple events into the same hook?

Suppose I have a function named `updateDataDump`, now every time when any of these events occur `afterChange`, `afterColumnMove`, `afterRemoveRow` or `afterRemoveCol`. I want that function to be executed.

```javascript
Handsontable.hooks.add('afterChange', () => {
    updateDataDump();
});

Handsontable.hooks.add('afterColumnMove', () => {
    updateDataDump();
});

Handsontable.hooks.add('afterRemoveRow', () => {
    updateDataDump();
});

Handsontable.hooks.add('afterRemoveCol', () => {
    updateDataDump();
});
```
Is there any way by which I can combine all functions into one?

### Your environment
* Handsontable version: Version: 0.32.0
* Browser Name and Version: Google Chrome 57.0.2987.110 (64-bit)
* Operating System: Ubuntu 14.04

**Comment by AMBudnik** [comment]
Hi @amarlearning 
unfortunately, there's no built-in option to add a logic to a few hooks at once.

With the solutions that you can choose from is also calling the `updateSettings`

```
hot.updateSettings({
  afterChange: function(){
    updateDataDump()
  }, 
  afterColumnMove: function(){
    updateDataDump()
  }, 
  afterRemoveRow: function(){
    updateDataDump()
  }, 
  afterRemoveCol: function(){
    updateDataDump()
  }, 
});


function updateDataDump(){

}
```

or just use the hook name as the `addHook` method uses a string representation of a hook.

```
var hooks = ['afterChange', 'afterColumnMove', 'afterRemoveRow', 'afterRemoveCol'];

for(var i = 0; i < hooks.length; i++){
	hot.addHook(hooks[i], updateDataDump);
}

function updateDataDump(){

}
```

**Comment by amarlearning** [comment]
@AMBudnik Thanks for the help!

**Comment by AMBudnik** [comment]
You're welcome. Let me know if you'd need anything else ;-)
