### ISSUE TITLE
Why should you trigger the 'modifyColWidth' event in getColWidth ()? What is its design intent?

### ISSUE THREAD

**Issue by ssbunny** [handsontable/handsontable#4376]
Why should you trigger the 'modifyColWidth' event in getColWidth ()? What is its design intent?

As in the source code:

```js
this.getColWidth = function (col) {
    let width = instance._getColWidthFromSettings(col);

    width = instance.runHooks('modifyColWidth', width, col);

    if (width === void 0) {
      width = ViewportColumnsCalculator.DEFAULT_WIDTH;
    }

    return width;
  };
```
hansontable run the hook 'modifyColWidth' when I call the `getColWidth` method. If I try to 

```js
hot.addHook('modifyColWidth', function (width, col) {
    console.log(hot.getColWidth(col + 1))
});
```

it causes `Maximum call stack size exceeded`.

**Comment by AMBudnik** [comment]
I am not the one to propose a solution but definitely logging this data shouldn't produce an infinite loop. Thanks for sharing @ssbunny

**Comment by AMBudnik** [comment]
Hi again,

sorry for the delay. Now I can confirm that the infinite loop is caused by calling the `modifyColWidth` the `getColWidth` is called which (again) calls the `modifyColWidth`.
If you like to get the column width you can use the `hot.view.wt.wtTable.getStretchedColumnWidth()` instead.
