### ISSUE TITLE
afterRowMove hook returns improper target parameter

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4377]
### Description

The `target` parameter doesn't return a valid index

### Steps to reproduce (`target` values)
1. Drag any row below the table.

### Demo
![moving rows](https://user-images.githubusercontent.com/141330/30108933-a42398f6-9304-11e7-9cf4-01bbc66294b9.gif)

http://jsfiddle.net/rzs1Lcom

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Chrome 59
* Operating System: Windows 10

`[Gr #7220, forum #1192, Gr #7188, Gr #7535]`

**Comment by wszymanski** [comment]
I divide this problem to two smaller. I change the ticket name and description.

**Comment by wszymanski** [comment]
Second part will be fixed within #4444.

**Comment by krzysztofspilka** [comment]
@wszymanski Failed test results (based on visual indices on the front-end and values printed in the web console in result):

1. Move 3 before 1 => index 0 (Correct)
2. Move 3 before 2 => index 1 (Correct)
3. Move 2 after 3 => index 3 (Wrong)

![screen shot 2017-09-06 at 11 49 27](https://user-images.githubusercontent.com/8048526/30105617-748e5f3c-92f9-11e7-9777-e78ae3e4c4ae.png)

**Comment by wszymanski** [comment]
Seems that moving rows from top to bottom doesn't work. Will be fixed within: #4501

**Comment by wszymanski** [comment]
Inside #5751 was introduced a new method `dragRows` which works as `moveRows` earlier. The `moveRows` function has `finalIndex` parameter from now which works as in the description. More about changes in the PR https://github.com/handsontable/handsontable/pull/5945.
