### ISSUE TITLE
Comment plugin documentation

### ISSUE THREAD

**Issue by ankushgoel** [handsontable/handsontable#4379]
### Description
Type error in `setCommentAtCell` due to wrong documentaion at
https://docs.handsontable.com/pro/1.11.0/Comments.html
`commentsPlugin.editor.setCommentAtCell(1, 6, 'Comment contents');`
should be `commentsPlugin.setCommentAtCell(1, 6, 'Comment contents');`
Please update the documentation and remove `.editor`

### Environment
* Handsontable version: 1.11.0
* Browser Name and version: Chrome
* Operating System: Linux

**Comment by AMBudnik** [comment]
Thanks for spotting @ankushgoel

**Comment by AMBudnik** [comment]
Thanks again for sharing @ankushgoel 
the change has been merged to version 0.34.0
