### ISSUE TITLE
cannot switch from PRO to FREE version on docs.handsontable.com 

### ISSUE THREAD

**Issue by KodjoSuprem** [handsontable/handsontable#4382]
https://docs.handsontable.com/

cannot switch from PRO to FREE version of handsontable

**Comment by AMBudnik** [comment]
Hi @KodjoSuprem 

You can switch between versions by a button near the search box

![image](https://user-images.githubusercontent.com/10757813/27959606-6c424010-6328-11e7-976a-9b7d925fa046.png)

**Comment by KodjoSuprem** [comment]
to be precise. The dropdown doesn show up when the browser is not maximised. Works fine when maximized or full screen.
(reproduced on IE 11 and chrome) works well on Edge

**Comment by AMBudnik** [comment]
Oh, ok - thanks for sharing. As I can see the window has to be 1058px or wider to get the dropdown.

**Comment by AMBudnik** [comment]
We have changed the UI. Now the PRO/CE version switch is on the right side of the menu

![image](https://user-images.githubusercontent.com/10757813/35221224-b0d34b28-ff79-11e7-8c25-40685837abdd.png)
