### ISSUE TITLE
How to copy all table data to clipboard

### ISSUE THREAD

**Issue by happyhero0** [handsontable/handsontable#4384]
### Description
Dear all, I want to copy entire table data to clipboard by click a button. 
The next step is to paste the data directly to Excel which should show same as handsontable 
But I can't find the way. Can you help me?

**Comment by AMBudnik** [comment]
Hi @happyhero0 
on the Handsontable side you just ned to call [`getData()`](http://docs.handsontable.com/pro/1.11.0/Core.html#getData) method. It will return the whole dataset.

**Comment by happyhero0** [comment]
@AMBudnik Thank you, I understand. But I want to click a button to copy all data to clipboard.
The next step is to paste the data directly to Excel which should show same as handsontable

**Comment by AMBudnik** [comment]
Hi @happyhero0 

I think that you could use the export plugin. Have you tested it before? Here's a demo http://jsfiddle.net/3yyto8ef/
It does actually a very similar task to what you want

**Comment by happyhero0** [comment]
@AMBudnik Thank you. This help me to solve the problem 😃   👍

**Comment by AMBudnik** [comment]
Great to hear that :)
I am closing the issue
