### ISSUE TITLE
Checking window.attachEvent instead of element.attachEvent in autoresize

### ISSUE THREAD

**Issue by MattCBowman** [handsontable/handsontable#4386]
### Description
If another library modifies window to have an 'attachEvent' method, but the rest of the elements on the page don't have the method, this will lead to a false positive, causing an exception to be thrown when the autoResize method tries to access the 'attachEvent' method on the element. Erring on the side of caution, the code should validate that the element has the attachEvent method before invoking it.

### Steps to reproduce
1. Set window.attachEvent = window.addEventListener
2. Try to type something into a cell
3. Exception is thrown because element.attachEvent is undefined

### Demo
http://jsfiddle.net/eab6n7yy/

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Chrome 59.0.3071.115
* Operating System: Mac OSX Yosemite

**Comment by AMBudnik** [comment]
Thank you for sharing @MattCBowman 
I have replicated the issue.
