### ISSUE TITLE
Comments are moved while scrolling with fixedColumnLeft turned on.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4389]
### Description

As mentioned by @gaoyuan121 at https://github.com/handsontable/handsontable/issues/2608 the issue is still present in the latest version

### Steps to reproduce

1. Hover over cell `0,0`
2. Scroll a few 1-3 cells right
3. Again hover over cell `0,0`

![gif](https://user-images.githubusercontent.com/10757813/28060197-c9d305d8-6626-11e7-8054-b0b84f3ec504.gif)

**Result**: Comment is moving with cells, which in the end, makes is half visible.

### Demo

https://jsfiddle.net/6drvsdz7/

### Your environment
* Handsontable version: 1.11.0/0.32.0
* Browser Name and version: Chrome 59
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
The comment is placed in the same way in version 0.35.1

**Comment by swistach** [comment]
Still occurs in v6.2.2

**Comment by AMBudnik** [comment]
Still replicable in v 7.0.3 https://jsfiddle.net/y4qkevof/

**Comment by AMBudnik** [comment]
The issue is still replicable using v 8.0.0 https://jsfiddle.net/AMBudnik/o2c9y4xu/

![issue](https://user-images.githubusercontent.com/10757813/91306073-597d5a80-e7ac-11ea-99e1-4ac2f47ba721.gif)

**Comment by swistach** [comment]
I merge this issue into #6744 as one of the results of improper comment's box positioning.
