### ISSUE TITLE
setCopyableText throws an exception when the table is not selected

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4390]
### Description

Calling the `setCopyableText` method of `CopyPaste` plugin throws an exception when the table is not selected. This causes an error when we try to copy or cut content using the context menu.

### Steps to reproduce

1. Go to https://docs.handsontable.com/0.33.0/demo-context-menu.html#page-copy-paste.
2. Trigger the Handsontable context menu without triggering cell selection.
3. Click on the "Copy" command.

### Demo

![kapture 2017-07-11 at 15 34 00](https://user-images.githubusercontent.com/571316/28071487-61d27dfe-6650-11e7-834f-eb8b047aed7e.gif)
<img width="522" alt="zrzut ekranu 2017-07-11 o 15 34 13" src="https://user-images.githubusercontent.com/571316/28071516-72a9ba2a-6650-11e7-9546-ece525840a73.png">

### Your environment
* Handsontable version: 0.33.0
* Browser Name and version: The latest Chrome
* Operating System: macOS

**Comment by AMBudnik** [comment]
thanks @budnix 
now the options are blocked when we have a cursor outside the cells area
