### ISSUE TITLE
Handson Render more rows when the row count increases

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#4393]
hi ,
   i have one problem in HandsonTable.while i try to load large data ( 1 million records),at first it renders ~23 rows when reaching 10k row it renders ~25rows ,20k rows it renders ~27rows..while reach 50k rows it renders ~30+rows which impact performanc slow,

can anyone help me to fix it
![screen shot 2017-07-12 at 12 07 09 pm](https://user-images.githubusercontent.com/29049117/28105249-51d68ad8-66fc-11e7-9f42-c2e359b22d10.png)
![screen shot 2017-07-12 at 12 08 39 pm](https://user-images.githubusercontent.com/29049117/28105267-6452794c-66fc-11e7-87d4-a3503b84bbfc.png)
![screen shot 2017-07-12 at 12 12 54 pm](https://user-images.githubusercontent.com/29049117/28105285-6f9ac688-66fc-11e7-85ae-0ea8a3b22c44.png)
![screen shot 2017-07-12 at 12 13 05 pm](https://user-images.githubusercontent.com/29049117/28105291-73bff418-66fc-11e7-8dcd-83b14e0db000.png)

thanks in advance

**Comment by Sundarcj** [comment]
am also tried with visibleRows option ,but it wont restrict the number of rendering

**Comment by AMBudnik** [comment]
Hi @Sundarcj 

1mln rows is a very big dataset. Handsontable won;t be able to show all the rows at once. Have you tried server-side pagination?

**Comment by AMBudnik** [comment]
Hi @Sundarcj 

I am closing this issue as there is no reply since the last week, however, if you still have any questions please let me know.
