### ISSUE TITLE
Manual column/row move not working with transform-translate-positioned tables

### ISSUE THREAD

**Issue by oyshan** [handsontable/handsontable#4394]
Hi!

When  positioning tables using transform:translate, manual row/column move is not working as affected. See fiddle.

It seems the calculation of the drag move position does not take into account the the transform:translate-positioning, and as such is shifted to the right/down, selecting the last column/row even though the active drag/move is over another column.

E.g. a transform:translate(500px,0px) shifts the table 500px to the right. When moving a column, the "drop" guideline (ht__manualColumnMove--guideline) "runs" to the right, selecting the last column, even though the mouse is positioned over e.g. the second column.
E.g. a transform:translate(0px,500px) shifts the table 500px down. When moving a row, the "drop" guideline (ht__manualRowMove--guideline) "runs" to the bottom, selecting the last row, even though the mouse is positioned over e.g. the second row.

### Demo
http://jsfiddle.net/u91h19h2/1/

### Environment
I'm using the latest Handsontable version and Chrome

Note: As I'm using a third part-app ([react-grid-layout](https://github.com/STRML/react-grid-layout)), which uses transform:translate-positioning, I cannot solve the problem by using another positioning method.

**Comment by AMBudnik** [comment]
Thank you for sharing @oyshan 

related https://github.com/handsontable/handsontable/issues/3946

**Comment by rajeshnagendra** [comment]
+1

**Comment by rajeshnagendra** [comment]
+1

**Comment by DongShi** [comment]
Hi @oyshan 
Do you have a workaround for this?  We happen to use react-grid-layout as well and is now suffering from this problem....

**Comment by oyshan** [comment]
@DongShi unfortunately, no. I had to disable the d&d functionality and use context menu to move cols/rows

**Comment by wojciechczerniak** [comment]
Housekeeping. We have few issues related to this one. I'm closing this one as a duplicate of #5050. Please track #5050 for further development.

**Comment by AMBudnik** [comment]
Good morning @oyshan @DongShi @rajeshnagendra 

we've just published Handsontable v `7.0.0` were he fix a referred issue https://github.com/handsontable/handsontable/issues/5050
Please update and let me know if it works for you.
