### ISSUE TITLE
AND/OR filters: Missing documentation for custom items

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4395]
### Description

We should add a description and possibly a demo to show how to add the `AND/OR` filters to a custom dropdown menu.

- [ ]  Array http://jsfiddle.net/s08gnk1r/
- [ ] Object http://jsfiddle.net/L6u9dzzd/

### Your environment
* Handsontable version: 1,12,0
* Browser Name and version: Chrome 59
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
Moved to https://github.com/handsontable/docs/issues/6
