### ISSUE TITLE
Hiding the contextmenu when clicked outside the handsontable

### ISSUE THREAD

**Issue by apanigr** [handsontable/handsontable#4397]
### Description
When i clicked outside the handsontable the contextmenu populates but ideally it should populate inside the handsontable itself.

### Steps to reproduce

1.Right click outside the handsontable
2.context menu would appears.
3.

### Your environment
* Handsontable version:2
* Browser Name and version:chrome
* Operating System:windows 10

export const CLICK_HANDLER_LOCATION_ATTR = "data-location-number";

// extracted type aliases to reduce noise in stream construction

type T1 = [
    Array<HotTableRow>, [
        Array<HotColumnConfig>,
        Array<ColumnHeader>
    ]
];

type T2 = [
    Array<HotTableRow>,
    Array<HotColumnConfig>,
    Array<ColumnHeader>
];

interface CellCoordinates {
    col: number;
    row: number;
}

interface TableSelection {
    start: CellCoordinates;
    end: CellCoordinates;
}

const getColumnFilters = (data: Array<HotTableRow>): HotFilters => {
    const columns: Array<string> = [
        "division",
        "department",
        "class",
        "ccNumber",
        "styleDescription",
        "colorDescription",
        "inStoreDate",
        "markdownDate",
        "seasonCode",
        "distro",
    ];

    const filters: HotFilters = {};

return _.reduce(columns, (acc: HotFilters, column: keyof HotTableRowData) => {
        const options = _.uniq(_.map(data, (row) => {
            return row.data[column] as string;
        }));
        if(options.length === 0) {
            acc["data." + column] = [""];
        }else {
            acc["data." + column] = options;
        }
        return acc;
    }, filters);
};

export class HotTableComponent extends BaseStorePlanningComponent implements ng.IComponentController {

    // tslint:disable-next-line:no-any
    private hot: any;

    private renderHotTable: EventListener;

    constructor(
        private ActiveHandsontableColumnHeaders: Observable<Array<ColumnHeader>>,
        private ActiveHandsontableColumnConfigurations: Observable<Array<HotColumnConfig>>,
        private ActiveHandsontableRows: Observable<Array<HotTableRow>>,
        private PlanningGridSelectedCcNumbers: Subject<Array<CcNumber>>,
        private PlanningGridManualEditTi: Subject<ManualEditData>,
        private PlanningGridFilters: Subject<HotActiveFilters>,
        private ModalManager: ModalManager,
        private $element: ng.IAugmentedJQuery,
        private $window: ng.IWindowService,
        private $document: ng.IDocumentService,
        private $rootScope: ng.IRootScopeService,
        private $scope: ng.IScope,
    ) {
        super();
    }

    // tslint:disable-next-line:no-any
    private isSelectedEvent(changes: Array<any>, source: string) {
        return (changes !== null && changes[0][1] === "data.selected" && (source === "edit" || source === "populateFromArray"));
    }

    private refreshSelectedCcNumbers = (data: Array<HotTableRow>) => {
        this.PlanningGridSelectedCcNumbers.next(
            _.filter(data, (row: HotTableRow) => row.data.selected).map((r) => r.data.ccNumber)
        );
    };

    private afterChangeForData = (data: Array<HotTableRow>) => {
        // tslint:disable-next-line:no-any
        return (changes: Array<any>, source: string) => {
            if (this.isSelectedEvent(changes, source)){
                this.refreshSelectedCcNumbers(data);

                this.$scope.$apply();
            }
        };
    };

    private afterOnCellMouseDownToObservable = (instance: Object): Observable<CellCoordinates> => {
        // tslint:disable-next-line:no-any
        return Observable.create((observer: any) => {
            Handsontable.hooks.add("afterOnCellMouseDown", (_e: MouseEvent, coords: CellCoordinates) => {
                observer.next(coords);

                this.$scope.$apply();
            }, instance);
        });
    };

    $postLink(): void {
        const el: HTMLElement = this.$document[0].createElement("div");

        this.hot = new Handsontable(el, {
            "autoColumnSize": true,
            "autoRowSize": false,
            "colHeaders": true,
            "columnFilterDefaultLabel": "- ALL -",
            "disableVisualSelection": true,
            "fillHandle": false,
            "fixedColumnsLeft": 1,
            "manualColumnFreeze": true,
            "manualColumnMove": true,
            "peteRowClasses": true,
            "renderAllRows": false,
            "rowHeaders": true,
            "rowHeights": 50,
            "wordWrap": false,
            "beforeColumnMove": this.onBeforeColumnMove,
            "columnSorting": true,
            "sortIndicator": true,
            "onFilterChange": this.onFilterChange.bind(this),
            "contextMenu": {
                "callback": this.onContextMenuItemSelected,
                "items": {
                    "freeze": {
                        "name": "freeze",
                        "disabled": _.negate(this.isFreezeContextMenuItemEnabled)
                    },
                    "unfreeze": {
                        "name": "unfreeze",
                        "disabled": _.negate(this.isUnfreezeContextMenuItemEnabled)
                    }
                }
            }
        });

        this.$element[0].appendChild(el);
        this.renderHotTable = () => this.hot.render();
        this.$window.addEventListener("resize", this.renderHotTable);

        const gridConfig: Observable<T2> = this.ActiveHandsontableRows
            .withLatestFrom(Observable.zip(
                this.ActiveHandsontableColumnConfigurations,
                this.ActiveHandsontableColumnHeaders
            )).map(([x, vals]: T1) => {
                const [y, z] = vals;
                return [x, y, z];
            });

        const cellMouseDown = this.afterOnCellMouseDownToObservable(this.hot);

        const manualEditInitiated: Observable<ManualEditData> = cellMouseDown.flatMap((coords) => {
            const rowData: HotTableRowData = this.hot.getDataAtCell(coords.row, coords.col);
            const cell = this.hot.getCell(coords.row, coords.col);
            const locationNumberEl = cell && cell.querySelector(`[${CLICK_HANDLER_LOCATION_ATTR}]`);
            const locationNumber = locationNumberEl && locationNumberEl.getAttribute(CLICK_HANDLER_LOCATION_ATTR);

            if (!rowData || !locationNumber) {
                return Observable.empty();
            }

            return Observable.of({
                "ccNumber": rowData.ccNumber,
                "skuNumber": rowData.skuNumber,
                "locationNumber": locationNumber,
            });
        });

        this.subscriptions.push(manualEditInitiated.subscribe((manualEditTiData) => {
            this.ModalManager.open({
                "modalTitle": "Adjust TI",
                "template": "<edit-ti-modal on-canceled='modalInstance.dismiss()' on-success='modalInstance.accept()'></edit-ti-modal>",
            });

            this.PlanningGridManualEditTi.next(manualEditTiData);
        }));

        // bind the Handsontable-renders to events flowing through the data-pipeline
        this.subscriptions.push(gridConfig.subscribe((vals) => {
            const [data, columns, headers] = vals;
            const settings = this.hot.getSettings();

            settings.columnHeaders = headers;
            settings.columnFilters = getColumnFilters(data);
            settings.data = data;
            settings.columns = columns;
            settings.nestedRows = true;
            settings.afterChange = this.afterChangeForData(data);
            this.hot.updateSettings(settings);
        }));

        this.subscriptions.push(this.ActiveHandsontableRows.subscribe((data) => {
            this.refreshSelectedCcNumbers(data);

            this.$rootScope.$applyAsync();
        }));
    }

    $onDestroy() : void {
        this.hot.destroy();
        this.$window.removeEventListener("resize", this.renderHotTable);
    }

    onFilterChange(filters: HotActiveFilters) {
        const trimmedFilters = _.reduce(_.keys(filters), (acc: HotActiveFilters, prop: string) => {
            acc[prop.slice(5)] = filters[prop];
            return acc;
        }, {});
        this.PlanningGridFilters.next(trimmedFilters);
    }

    onContextMenuItemSelected(key: string, selection: TableSelection): void {
        // tslint:disable-next-line:no-any
        const hot: any = this;

        if (key === "freeze") {
            hot.getPlugin("manualColumnFreeze").freezeColumn(selection.start.col);
            hot.render();
        } else if (key === "unfreeze") {
            hot.getPlugin("manualColumnFreeze").unfreezeColumn(selection.start.col);
            hot.render();
        } else {
            throw new Error(`ContextMenu key not recognized: ${key}`);
        }
    }

    onBeforeColumnMove(indexesOfColumnsToBeMoved: Array<number>, indexOfTargetPosition: number): boolean {
        const length     = indexesOfColumnsToBeMoved && indexesOfColumnsToBeMoved.length;

        if (!length) {
            return false;
        }

        const firstIndex = indexesOfColumnsToBeMoved[0];
        const lastIndex  = indexesOfColumnsToBeMoved[length - 1];

        return !(indexOfTargetPosition > LOCATION_NONSPECIFIC_COL_CONFIGS.length
            || firstIndex >= LOCATION_NONSPECIFIC_COL_CONFIGS.length
            || lastIndex >= LOCATION_NONSPECIFIC_COL_CONFIGS.length);
    }

        isFreezeContextMenuItemEnabled(): boolean {
               // tslint:disable-next-line:no-any
               const hot: any = this;

                   if(typeof(hot.getSelected())!=="undefined"){
                   const startX: number = hot.getSelected()[1];
                   return _.isFinite(startX) && startX > 0 && startX < LOCATION_NONSPECIFIC_COL_CONFIGS.length;
                   }else {
                  this.$element.hide;
               return false;
              }
       }

           isUnfreezeContextMenuItemEnabled(): boolean {
               // tslint:disable-next-line:no-any
               const hot: any = this;

               if(typeof(hot.getSelected())!=="undefined"){
                   const startX: number = hot.getSelected()[1];
                   return _.isFinite(startX) && startX > 0 && startX < LOCATION_NONSPECIFIC_COL_CONFIGS.length;
                   }else {
               return false;
              }

          }
   }

});

**Comment by AMBudnik** [comment]
Hi @apanigr 

could you share the code via JSFiddle or JSBin?

**Comment by AMBudnik** [comment]
I am closing this issue in lack of recent activity (for 2 weeks). However, @apanigr feel free to leave your feedback if needed.
