### ISSUE TITLE
Cannot work with add comments to a cell

### ISSUE THREAD

**Issue by annieforever21** [handsontable/handsontable#4402]
### Description
Referenced the tutorial book while adds comment to cells but it didn't work:
https://docs.handsontable.com/pro/1.11.0/Comments.html

### Here is my codding 1

function cellValueCheckHt(rowPos, colPos, val) {
	var commentsPlugin = chkHt.hot.getPlugin('comments');
	var setHtComment = function(comment) {
		// Manage comments programmatically:
		commentsPlugin.editor.setCommentAtCell(rowPos, colPos, comment);
		commentsPlugin.showAtCell(rowPos, colPos);
	};

	if (chkHt.data[colPos].hissu) {
		if (val == "") {
			setHtComment('Please input something');
			return;
		}
	};

};

Codding 1 ends up with error of this ↓
Uncaught TypeError: commentsPlugin.editor.setCommentAtCell is not a function

### Here is my codding 2

function cellValueCheckHt(rowPos, colPos, val) {
	var commentsPlugin = chkHt.hot.getPlugin('comments');
	var setHtComment = function(comment) {
		// You can also set range once and use proper methods:
		commentsPlugin.setRange({row: rowPos, col: colPos});
		commentsPlugin.setComment(comment);
		commentsPlugin.show();
	};

	if (chkHt.data[colPos].hissu) {
		if (val == "") {
			setHtComment('Please input something');
			return;
		}
	};

};

Codding 2 ends up with error of this ↓
Uncaught Error: Before using this method, first set cell range (hot.getPlugin("comment").setRange())

Finally I found the resolution of this issue which may work properly but I don't know why (Please see the Fianl codding).
Could you please help me to figure this issue out in the next version or update your tutorial ?

### Final codding

function cellValueCheckHt(rowPos, colPos, val) {
	var commentsPlugin = chkHt.hot.getPlugin('comments');
	var setHtComment = function(comment) {
		commentsPlugin.setRange({
			from: {
				row: rowPos,
				col: colPos
			}
		});
		commentsPlugin.setComment(comment);
		commentsPlugin.show();
	};

	if (chkHt.data[colPos].hissu) {
		if (val == "") {
			setHtComment('Please input something');
			return;
		}
	};

};

### Your environment
* Handsontable version: 0.29.1
* Browser Name and version: Chrome 55.0.2883.87 m
* Operating System: Windows 7 Professional

**Comment by AMBudnik** [comment]
Hi @annieforever21 

the `editor` is an excess code here. Please check this issue https://github.com/handsontable/handsontable/issues/4379

Here is a working demo http://jsfiddle.net/de78dbr6/

**Comment by annieforever21** [comment]
Hi @AMBudnik 
Thanks for your answer. 
But it still have error with when doing 'setRange' before useing 'setComment'.
'commentsPlugin.setRange({row: rowPos, col: colPos});' should be 'commentsPlugin.setRange(from: {{row: rowPos, col: colPos}|);'.

**Comment by AMBudnik** [comment]
Hi @annieforever21 

I think that there's an issue with defining the range. [According to documentation](https://docs.handsontable.com/pro/1.12.0/Comments.html#setRange), 

> Object with from and to properties, each with row and col properties

it could be something like that

```
{
  from : {row: index, col: index},  
  to: {row: index, col: index}
}
```

but it doesn't work as well.

I am marking this issue as a bug, and the developers will check if it is a bug or we are missing a proper example in the documentation.

**Comment by annieforever21** [comment]
Hi @AMBudnik 
Thank you very much for your following.
It's working properly now with this so I won't do any change before the bug is fixed.
If there is any updating here pls let me know :-)

commentsPlugin.setRange({
    from: {
        row: rowPos,
        col: colPos
    }
});

**Comment by wojciechczerniak** [comment]
Documentation was updated with correct `setRange` argument in #5193
