### ISSUE TITLE
Question: Is there an event that fires on cell merging?

### ISSUE THREAD

**Issue by YakovL** [handsontable/handsontable#4406]
Haven't found in [docs](http://docs.handsontable.com/0.32.0/Hooks.html) if there's such an event. There's lots of events (hook names) about which I'm not sure, could you please help me out? Those which may fire (if any)..

afterCellMetaReset
afterContextMenuDefaultOptions
afterContextMenuHide // not likely, but may be useful for a workaround
afterGetCellMeta
afterInit
afterModifyTransformEnd
afterModifyTransformStart
afterRender
afterRenderer
afterSetCellMeta
afterSetDataAtCell
afterSetDataAtRowProp
afterUpdateSettings
afterValidate
beforeAutofill
beforeAutofillInsidePopulate
beforeCellAlignment
beforeChangeRender
beforeContextMenuSetItems
beforeDrawBorders
beforeGetCellMeta
beforeInit
beforeInitWalkontable
beforeRender
beforeRenderer
beforeValidate
beforeValueRender
beforeValueRender

My goal is to save settings once merging/unmerging is done (externalize them from handsontable, presumably by getting from `hotInstance.mergeCells.mergedCellInfoCollection`).

**Comment by AMBudnik** [comment]
Hi @YakovL 

we are currently[ rewriting mergeCells plugin](https://trello.com/c/SPxx77h0/85-in-progress-re-write-of-merge-cells). It should be ready for a next release where we'll add a hook to track merging.

related https://github.com/handsontable/handsontable/issues/2588

**Comment by YakovL** [comment]
Right, thanks. Is the release date scheduled or predictable approximately?

**Comment by AMBudnik** [comment]
The [next milestone is set for 2nd of August](https://github.com/handsontable/handsontable/milestones), however, the mergeCells refactor is placed on another milestone so it could be released sooner or later. It is hard to tell when it will get published as we did not finish all the work yet.

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/2588

**Comment by AMBudnik** [comment]
The [`afterMergeCells`](https://docs.handsontable.com/pro/1.18.1/Hooks.html#event:afterMergeCells) has been added.

**Comment by YakovL** [comment]
Cool! Is it available in CE since 0.38.0?

**Comment by AMBudnik** [comment]
Hi @YakovL Yes, it is available from 0.37.0
