### ISSUE TITLE
Copy, cut, and paste do not work on first attempt in Safari

### ISSUE THREAD

**Issue by joelhoover** [handsontable/handsontable#4407]
### Description
If the user selects a cell or group of cells and then presses a copy, cut, or paste (CCP) keyboard combination (<kbd>CMD</kbd><kbd>C</kbd>, <kbd>CMD</kbd><kbd>X</kbd> or <kbd>CMD</kbd><kbd>V</kbd>), the CCP command fails and the computer makes the "error" beep. After the initial attempt, CCP attempts will now function correctly. However, once the user further interacts with the spreadsheet – such as by selecting another cell, moving with the arrow keys, or even clicking on the already selected cell – the situation then repeats itself.

Additionally, the File > Copy/Cut/Paste entries in the menu bar mirror the above: when the user selects a cell, the menu items are initially grayed out and cannot be triggered. However, after the user enters a CCP keyboard combination, the menu items become available until the user then moves to a different cell or otherwise interacts with the spreadsheet.

Finally, if the user performs the initial copy/paste attempt, and then enters a key (such as <kbd>d</kbd>) as if to enter data into the cell, the cell will be opened for editing as normal, but the character will not be in the input cell. Upon further inspection, it seems the missing character is instead placed into the the `textarea#HandsontableCopyPaste` element.

Note: This issue only occurs with the new CopyPaste plugin (#4234) and thus is only present in Handsontable 0.33, not any earlier version.

### Your environment
* Handsontable version: 0.33.0
* Browser Name and version: Safari 10.1.1 (11603.2.5)
* Operating System: macOS 10.11.6

**Comment by AMBudnik** [comment]
Thank you @joelhoover 
I have replicated the issue and it only happens after our copy/paste refactor.
@swistach do you have any ideas what happened here?

**Comment by AMBudnik** [comment]
OK, we just got a confirmation that the issue can be replicable only on macOS ElCapitan 10.11.4+

**Comment by swistach** [comment]
Hi @joelhoover.
After our changes, copy/cut/paste operations should work well.
But if you still have this issue, just open it again.
