### ISSUE TITLE
about to import

### ISSUE THREAD

**Issue by caihua1** [handsontable/handsontable#4416]
Can the Handsontable import the Excel of file ？ How to use it.

**Comment by AMBudnik** [comment]
Hi @caihua1 

we are currently working on a side project where you will be able to inject an Excel file into Handsontable but there's much work left and there's no deadline.
I'll inform you as soon as I'll get any news about the project.

**Comment by caihua1** [comment]
oh !  THX!

**Comment by AMBudnik** [comment]
The same issue as https://github.com/handsontable/handsontable/issues/420
