### ISSUE TITLE
Autocomplete/dropdown close Bootstrap 3.x Modal Dialog after choosing item

### ISSUE THREAD

**Issue by mdekalka** [handsontable/handsontable#4418]
### Description
I created a Handsontable table with autocomplete/dropdown in a Bootstrap modal dialog. When I click the autocomplete/dropdown cells and try to choose any option - the modal dialog closes.
Note: It happens only when autocomplete/dropdown goes beyond the boundaries of modal dialog)

![handson](https://user-images.githubusercontent.com/5993559/28366997-b203ea5e-6c97-11e7-84c7-97fb05ce2b1d.gif)
Please see `console.log` with `e.target` in jsfiddle.

### Steps to reproduce

1. Click the button to open modal dialog
2. Chose the autocomplete/dropdown options which renders beyond the boundaries of modal dialog.

### Question:
Is there are any options to avoid this using Handsontable options?
Thank you.

### Environment
* Handsontable version: 0.33.0
* Browser Name and version: Google Chrome  59.0.3071.115
* Operating System: Win10

**Comment by mdekalka** [comment]
Hi @AMBudnik .
Any updates on this? Is this a bug and will it be fixed in future?

**Comment by AMBudnik** [comment]
Hi @mdekalka 

We did not schedule the issue yet. Here is a list of issue for the next release https://github.com/handsontable/handsontable/milestone/85

**Comment by mdekalka** [comment]
Got it. Thank you.

**Comment by AMBudnik** [comment]
I think that this issue has been olready solved in another issue report on Github.  @mdekalka Please try to add a delay (can be 10ms) to the event that draws a table inside the window when it's opened.
