### ISSUE TITLE
Copying data causes Safari to scroll up.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4425]
## Description
Since version `0.33.0`, copying data from the table causes the browser to scroll up on Safari 9.
On Safari 10 the browser scrolls after pasting.

### Steps to reproduce

1. Open Safari
2. Go to http://docs.handsontable.com/0.33.0/demo-stretching.html#page-none
3. Select some cells
4. Press <kbd>Ctrl/Cmd</kbd>+<kbd>C</kbd>
5. *If on Safari 10, press <kbd>Ctrl/Cmd</kbd>+<kbd>V</kbd>*

### Your environment
* Handsontable version: 0.33.0
* Browser Name and version: Safari 9, Safari 10

**Comment by jansiegel** [comment]
Possible fix:

Changing 
```css
bottom: 100% !important;
```
to
```css
bottom: 50% !important;
```

for the copy/paste's textarea.

**Comment by swistach** [comment]
That issue was resolved in #4407

**Comment by AMBudnik** [comment]
Released: v0.34.5
