### ISSUE TITLE
HandsOnTable columns get misaligned when scrolling horizontal bar to the end on IE/Edge browser

### ISSUE THREAD

**Issue by CraigAndrew1** [handsontable/handsontable#4426]
### Description
The HandsOnTable columns get misaligned with the table header as you scroll horizontally to the end. This is an IE/Edge only issue. I've tested on IE v11 and Edge browsers and the issue occurs on both. What I perceive to be the issue is that the table header is overlapping the vertical scrollbar (this does not occur on Firefox and Chrome).

### Steps to reproduce
1. Scroll horizontally on IE browser to the end
2. Observe column alignment has gone off

### Your environment
* Handsontable version: "handsontable": "^0.24.3",
* Browser Name and version: IE v11 & Edge
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
Hi @CraigAndrew1 

in the current version, we are not able to scroll using a mouse reported at https://github.com/handsontable/handsontable/issues/4276 and https://github.com/handsontable/handsontable/issues/4320. But when we do it via scroll bar it should work as expected. Can you share a demo where this will be replicable?

**Comment by CraigAndrew1** [comment]
Hi Aleksandra,

Please find the attached images:

1. Columns are aligned in IE just before issue happens (as long as you don’t scroll to the right fully)

2. Columns are NOT aligned in IE as issue occurs when scrolling to the right of the table fully.

Kind Regards
Craig

**Comment by AMBudnik** [comment]
@CraigAndrew1 sorry, but the images did not attach. Please resend in your earliest convenience

**Comment by CraigAndrew1** [comment]
Link1: https://drive.google.com/file/d/0B6SUIlyrUR98TUl2M1ZJM1NPcEk/view?usp=sharing

Link2:
https://drive.google.com/file/d/0B6SUIlyrUR98RXYzOTI2c3pIX00/view?usp=sharing

**Comment by AMBudnik** [comment]
Hi @CraigAndrew1 

thank you for sharing the screenshots. Please check if adding `autoColumnSize: true` to your isntance settings fixes the issue.

**Comment by CraigAndrew1** [comment]
Hi @AMBudnik 

I've tried setting `autoColumnSize: true` to the instance settings but the issue still prevails - Please check this animation illustrating it further: https://drive.google.com/open?id=0B6SUIlyrUR98MS1tUHc3U0w4cGs

Please let me know if you have any other advice/ideas to try out...

**Comment by AMBudnik** [comment]
Can you share a demo for me to test some approaches?

**Comment by AMBudnik** [comment]
I am closing this issue as there is no reply for 10 days. @CraigAndrew1 if you are still experiencing any issues with the library please let me know

**Comment by CraigAndrew1** [comment]
I had a style issue that was causing this on IE, my fix was to change "-ms-overflow-style: none;" to "-ms-overflow-style: auto;"

**Comment by AMBudnik** [comment]
Thank you for sharing the tip @CraigAndrew1
