### ISSUE TITLE
Error in editing

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#4427]
Hi,
am using HandsonTable 1.12.0 while i trying to edit the cell i got some errors,can anyone help me to fix it.
here i attached the screen shot

![screen shot 2017-07-25 at 12 15 17 pm](https://user-images.githubusercontent.com/29049117/28559174-04eb88d6-7133-11e7-985f-bcba8cfa9ed3.png)

**Comment by AMBudnik** [comment]
Hi @Sundarcj 

please share a demo where this issue can be replicable.

**Comment by Sundarcj** [comment]
I just create the Handson Table , and double click the cell,it shows error

**Comment by AMBudnik** [comment]
@Sundarcj this issue is not replicable on our site where we have dozens of demos. It may be related to a missing file, wrong resource order or your environment

**Comment by AMBudnik** [comment]
I assume that you have found a solution as the issue hasn't been updated since 25th of July
