### ISSUE TITLE
How to maintain different dropdown values for different rows.

### ISSUE THREAD

**Issue by GanjuV** [handsontable/handsontable#4428]
### Description
I want to maintain a separate dropdown values for all rows of a table.
Currently in handsontable same dropdown values are maintained for all rows.

In the below fiddle I have try to demonstrate the problem.
The Bus and Network dropdown shouldn't have same value.
Example :-
`Bus` dropdown should have :- `['Bus', 'Data']`
`Network` dropdown should have :- `['Network', 'Design']`
http://jsfiddle.net/Vaibhav34/fsvakoLa/5/

**Comment by AMBudnik** [comment]
Hi @GanjuV 

Here's http://jsfiddle.net/handsoncode/wp7ynbng/1/ an example where I have built a separate dropdown in a few configurations. It uses the `cells` option with `type` and `source` parameters to pass a different set of values to the dropdown cell type.

**Comment by GanjuV** [comment]
Hi @AMBudnik 
First of all thanks for a quick response.
I am looking for a code which can handle 10K records.
And one column which will have N attributes, based on these attributes i will have dropdown values.
I am looking for a way to maintain the state of Handsontable as current code contain lot of `if` and `else` and will not be a good coding practice.
Is there any api written in handson to maintain state or change the state ?

**Comment by AMBudnik** [comment]
If you have prepared a list of the dropdown arrays you can just use the loop. Here's an example http://jsfiddle.net/fgrmtxb2/ If the list of dropdowns is index-to-index with your data set then you do not need any other conditions.

**Comment by GanjuV** [comment]
Thanks for the solution but we are using fixed dropdown values what happens when I change the first row first column value and based on the value selected the second column should also change,  with out changing the values of second row's second column?
Ex on changing `NetDesign` to `InfDesign` only the `Network` dropdown should update with `InfDesign` and `Bus` dropdown should'nt change and should have values of `DataAcq` drop down.

**Comment by AMBudnik** [comment]
If you are using dependencies you can also use the following code, combined with this `afterChange` http://jsfiddle.net/3z7m1yrz/ event

**Comment by GanjuV** [comment]
Thanks for the solution.
In the provided example the dropdown data corresponding to `Fruits` is not populated in `Your Pick` column. Can you please show a way to initialise It on first load.

**Comment by mmucklo** [comment]
@AMBudnik - any update?

**Comment by AMBudnik** [comment]
Hi @GanjuV 
In our case the last column was set to the `Candy` (`line: 33`).  It is fine for the first row as `Candy` is the value in cell `0,0 `, however, in the second row there's a `Fruit` in the `Type` column. That is why the validation is failed http://jsfiddle.net/3z7m1yrz/1/

If we would like to run the correct dropdown placement we should pick a method that differentiates the rows as well - the `cells` method. Like in the following example http://jsfiddle.net/e2rxvkb0/
