### ISSUE TITLE
How to allow dropdown to extend beyond div when scrolling is enabled?

### ISSUE THREAD

**Issue by pflaumingo** [handsontable/handsontable#4431]
@AMBudnik I've created a new issue here following our conversation in issue #3435. I realized that my comment was potentially human error, but there are also some inconsistent behaviours that I am seeing. A JSFiddle [here](https://jsfiddle.net/pflaumingo/614eda23/) can be used to follow along with the following scenarios:

1. When scrolling is **not** enabled and the height is specified within the containing div, the dropdown works the first time, but on subsequent clicks it is clipped, but not clipped at the height of the div.

2.  When scrolling is **not** enabled and the height is specified at the parent div, but not the containing div, the dropdown works fine all the time.

3. When scrolling is enabled as specified in the docs (by using overflow:hidden), the dropdown is clipped at the height specified at either the parent div or containing div.

As you can see, there are some inconsistent behaviours going on. What I'm trying to get at, is for a parent container with a fixed height and width where scrolling is needed, is there a recommended way to allow for the dropdown to extend beyond the height of the parent div as it does in scenario 2 above. In short, I'd like the scrolling of scenario 3 with the dropdown effects of scenario 2.

**Comment by AMBudnik** [comment]
Thank you so much for fully describing the issue.

**Comment by pflaumingo** [comment]
@AMBudnik, I've updated the JSFiddle to contain a date field as the date picker works as expected with scrolling enabled.

**Comment by AMBudnik** [comment]
Yes, you're right. The date window is visible all the time and we should get the same result for a dropdown cell type.

**Comment by wesleywong** [comment]
same issue here. i think dropdown menu should stick to body instead of cell in order to solve this.

**Comment by bigbharatjain** [comment]
I am facing the same issue. Any update or information, how to fix that?
Dropdown is hiding behind the horizontal dropdown.

**Comment by AMBudnik** [comment]
It should work fine for dropdown @bigbharatjain 
Can you share your code example?

**Comment by bigbharatjain** [comment]
```
var employees = [<?php echo '"'.implode('","', $employees->pluck('name_emp_code','name_emp_code')->toArray()).'"' ?>];
// emptyValidator
emptyValidator = function (value, callback) {
                  if (value == null) {
                    value = '';
                  }
                  if (value === '') {
                    callback(false);  
                  } else {
                    callback(true);
                  }
                };             
function userValidation(instance, td, row, col, prop, value, cellProperties) {
  Handsontable.renderers.TextRenderer.apply(this, arguments);
  if(prop=="NAME" && !employees.inArray(value)) {
    if(value!=null){
      td.style.background = '#f0ad4e';
    }
  }
}
var
    $$ = function(id) {
      return document.getElementById(id);
    },
    container = $$('hot'),
    save = $$('save'),
    add = $$('add'),
    hot;


@if(!empty($template->template_data))
var dataObject = {!! $template->template_data !!};
@else
var dataObject = [
    @foreach($employees as $employee)
      {
        NAME: '{{ $employee->name_emp_code }}',
        @foreach($template->template->templatefields as $field)
            {{$field->slug_name}}: '{{ (!empty($field->default_value) || $field->default_value==0) ? $field->default_value : ''}}',          
        @endforeach        
      },
    @endforeach
];
@endif
var valid = true;
var hotElement = document.querySelector('#hot');
var hotElementContainer = hotElement.parentNode;
var hotSettings = {
  data: dataObject,
  columns: [ 
    {
        data: 'NAME',
        type: 'dropdown',
        allowInvalid: true,
        source: employees,
        validator: emptyValidator,
    },
    @foreach($template->template->templatefields as $field)
    {
      data: '{{ $field->slug_name }}',
      type: '{{ $field->field_type }}', 
      @if($field->is_required=='true')
        @if($field->field_type=='date')
          allowEmpty: false
        @else
          validator: emptyValidator
        @endif
      @endif
    },
    @endforeach
  ],
  colHeaders: [ 
    'Name',
    @foreach($template->template->templatefields as $field)
    '{{ $field->field_name }}',
    @endforeach
  ],
  colWidths:100,
  manualRowResize: true,
  manualColumnResize: true,
  stretchH: 'all',
  minSpareRows:0,
  contextMenu: true,
  cells: function (row, col, prop) {
      var cellProperties = {};
      cellProperties.renderer = userValidation; // uses lookup map
      return cellProperties;
  }
};

var hot = new Handsontable(hotElement, hotSettings);
```

Please see the behaviour of dropdown in attached Screencast.
[handsontable.webm.zip](https://github.com/handsontable/handsontable/files/1599473/handsontable.webm.zip)

**Comment by AMBudnik** [comment]
Thank you for sharing the example @bigbharatjain 
I do not see any issues with your code. It is properly constructed. I guess that we need to investigate this issue little closer.

**Comment by bigbharatjain** [comment]
@AMBudnik Thanks for the quick response.
Please investigate and let me know how can I fix this.

**Comment by AMBudnik** [comment]
Hi @bigbharatjain 
I've been updated with a change that is going to happen for the next version of Hot. We will be changing the way dropdowns are hiding/showing. Currently, we are hiding the element and after the update, only the z-index will be changed.

**Comment by Melanie-M** [comment]
Any updates on this issue? It has been closed but not resolved.

I still have the problem of dropdowns being cut off at the bottom of the table (see this fiddle: https://jsfiddle.net/ksao8h9c/)

How can I have a table with fixed width and height (and scrolling), and use dropdowns?
Having the dropdowns open upwards is not a solution, as my table only has very few rows.

**Comment by AMBudnik** [comment]
Hey @pflaumingo 

I am sorry but

>We can get back to this issue while changing the layer structure but for now, [...]

did not happen yet.

**Comment by l-wagner** [comment]
I'm also having trouble with this exact issue,

**Comment by emanuallan** [comment]
same issue

**Comment by pnowak** [comment]
Please @emanuallan follow response in one place in this issue - https://github.com/handsontable/handsontable/issues/7069#issuecomment-662404024
