### ISSUE TITLE
Unwanted characters in downloaded CSV file

### ISSUE THREAD

**Issue by GanjuV** [handsontable/handsontable#4432]
### Description
Hi am using exportFile plugin to export my grid data.
PFB the issue image -
<img width="657" alt="screen shot 2017-07-28 at 10 25 58 am" src="https://user-images.githubusercontent.com/24271789/28703159-d5d2568e-737f-11e7-8aab-6552ba61ae69.png">

### Steps to reproduce
1. Just open the link http://jsfiddle.net/Vaibhav34/nrnebad9/1/
2. Click on download "Export as a file"
3. Check the CSV file.

**Comment by AMBudnik** [comment]
Hi @GanjuV 

I do not have this result. I must be related to the language settings

![image](https://user-images.githubusercontent.com/10757813/28707950-98183e8a-737a-11e7-94db-c39fe24784f3.png)

**Comment by AMBudnik** [comment]
I think that[ this topic](https://superuser.com/questions/280603/how-to-set-character-encoding-when-opening-excel) may help.

**Comment by mmucklo** [comment]
@AMBudnik seeing this for only CSV files generated by Handsontable - does it export in a non-standard encoding by default?  Is there a way to change the encoding on the file it exports?

**Comment by AMBudnik** [comment]
Hi @mmucklo 

by using the plugin, we do not have any control over encoding.

**Comment by primaryobjects** [comment]
I believe this is a [Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) (BOM) character that is being output as the first character from the `exportAsString` method. It's not clear why this character is being exported at the front of the csv.

You can strip this character out with the following regex:
```js
csv = csv.replace(/^\uFEFF/, '')
```

If you examine the first character in the Chrome inspector without using the regex, you can see the following:

```text
csv.charCodeAt(0)
65279
```

See also [Unicode Character 'ZERO WIDTH NO-BREAK SPACE' (U+FEFF)](http://www.fileformat.info/info/unicode/char/feff/index.htm).

**Comment by wojciechczerniak** [comment]
Can be tracked with: handsontable/handsontable-pro#85
