### ISSUE TITLE
New hooks for editor

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4433]
### Description
We should add new hooks for an editor. An event when the editor was opened, closed and the value was changed should be added.

**Comment by AMBudnik** [comment]
Hey. 
According to our recent policy, I am closing this proposition of a change as we are not currently working on the piece of code that it relates to.
Once we open an issue we check all pinned issues and pull requests even if they are closed so please keep track of updates to this issue. All additional comments are also highly appreciated.
