### ISSUE TITLE
Table can be scrolled by arrow keys, but it never calls afterScrollHorizontally hook

### ISSUE THREAD

**Issue by vp9920** [handsontable/handsontable#4434]
### Steps to reproduce

1. Create a table with horizontal scroll;
2. Select the rightmost visible cell and press Arrow Right

**Comment by AMBudnik** [comment]
Thanks for sharing @vp9920 

you're right. The callback does not get called each time we are actually scrolling.

**Comment by swistach** [comment]
Hi @vp9920 
We fixed this issue: http://jsfiddle.net/mjqz7yux/
