### ISSUE TITLE
observeChanges firing afterChange bug

### ISSUE THREAD

**Issue by faameunier** [handsontable/handsontable#4435]
Hi,
### Description
_ObserveChanges_ plugin can fire _afterChange_ hook when data is replaced.
Unfortunately, when doing so, the _changes_ argument is a 1D array instead of 2D array (as described in the documentation [here](https://docs.handsontable.com/pro/1.12.0/Hooks.html#event:afterChange)) which can lead to errors afterwards.
This is on line 109 of the plugin ([here](https://github.com/handsontable/handsontable/blob/master/src/plugins/observeChanges/observeChanges.js#L109)).

I believe the line 
`this.hot.runHooks('afterChange', [patch.row, patch.col, null, patch.value], sourceName);`

should be 
`this.hot.runHooks('afterChange',[[patch.row, patch.col, null, patch.value]], sourceName);`

### Your environment
* Handsontable version: 0.33

Please let me know if this is intended and I misunderstood something.

**Comment by AMBudnik** [comment]
Thank is correct. According to docs we need to pass a 2D array

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/pull/4638

**Comment by swistach** [comment]
Fixed in v4.0.0
