### ISSUE TITLE
Can i store an object in cell and show only part of the object's property

### ISSUE THREAD

**Issue by aokaywe** [handsontable/handsontable#4436]
Can i make a plugin that can store an object in cell and show only part of the object's property

### Steps to reproduce

1.   There is an object like {id: 'erw234e', name: 'keyword1'}
2.  Save the object in cell(1,1)
3.  I only want show the name 'keyword' in cell, and hide the id 'erw234e'
4.  Custom renderers can't support this feature, because when the cell enter into edit state, it will show     the whole object  {id: 'erw234e', name: 'keyword1'}. I don‘t want someone to modify the object id.
5. The object will move with the cell when insert column or insert row

**Comment by AMBudnik** [comment]
Hi @aokaywe 

you can refer to only one key inside an object. Here's a demo I've made http://jsfiddle.net/ambLw52z/
Let me know if I am missing any crucial settings.

**Comment by aokaywe** [comment]
Thank  you @AMBudnik 
1. I want the object id can move with the cell when insert column or insert row, like comments plugin for comment. When i  insert a column before cell(1,1)，the whole object {id: 'erw234e', name: 'keyword1'} will move to the cell(2,1). So the best way is store the whole object in the cell
2. And i want to do bi-directional data binding. For example:
The source data is
[
[null, null, null]
[null, {id: 'terttet', name: 'keyword1'}, null]
]
when insert a column before cell(1,1), the source data change into:
[
[null, null, null, null]
[null, null, {id: 'terttet', name: 'keyword1'}, null]
]

**Comment by AMBudnik** [comment]
Hi @aokaywe 

Sorry for a delay. Have you already managed to add needed details or I can help you with anything? Currently in my demo when you add a line the new line takes the data of previous one and we add a new record at the end of the dataset.

**Comment by aokaywe** [comment]
But in your demo, I can't inert a column before column B. Is there any way to do this ?
![2017-08-13 1 55 22](https://user-images.githubusercontent.com/19823829/29246505-3e52113e-802f-11e7-91c2-8ec65f39a44f.png)

**Comment by AMBudnik** [comment]
Hi @aokaywe 

The `Insert column on the right` and  `Insert column on the left` are disabled as we have used the `columns` method to set our table schema (amount and type of columns). To avoid it you can use the [`cells`](https://docs.handsontable.com/pro/1.13.0/Options.html#cells) method to enter the data. Then you operate on `row` and `column` parameters.
