### ISSUE TITLE
setBorder (right border) improvement with custom borders

### ISSUE THREAD

**Issue by 22140505** [handsontable/handsontable#4437]
in prepareBorder(){
...
      case 'top':
        for (var topCol = range.from.col; topCol <= range.to.col; topCol++) {
          setBorder.call(this, range.from.row, topCol, place, remove);
        }
        break;
      case 'right':
        for (var rowRight = range.from.row; rowRight <= range.to.row; rowRight++) {
          **setBorder.call(this, rowRight, range.to.col, place);  //one parameter is missing**
        }
...
}

**Comment by AMBudnik** [comment]
Thanks for sharing @22140505 
I am not able to tell if it's missing but I have tested adding and removing right cell border and it works as expected. I will leave the issue opened for our developers to check.

**Comment by 22140505** [comment]
If you do not add that parameter, when the merged cells with border, no effect

**Comment by AMBudnik** [comment]
Could you please create a pull request for the following code?

**Comment by AMBudnik** [comment]
The issue has been redirected to the [Wiki section / Improvement suggestions(https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

**Comment by AMBudnik** [comment]
The following code changed https://github.com/handsontable/handsontable/blob/fa685dc8c194c0269b893d202580ce7091ed8322/src/plugins/customBorders/customBorders.js#L485
