### ISSUE TITLE
ColumnSummary on change cell

### ISSUE THREAD

**Issue by d-aven** [handsontable/handsontable#4438]
I use columnSummary plugin and I need to add manualy some rows.
I decided to use summaryPlugin as function and I noticed after each cell change fires funtion columnSummary (TotalEndpoints - 1) times
In my case I have over 600 endpoints (but it is planned to have much more) and after each change I wait for 3 seconds,

I tried to use columnSummary as array, but in that case I get much more problems such as how to set new endpoints.
In case of inserting more than 1 row I have got an errors
   ```
 instance.alter('insert_row', firstNewRow, amount, 'InsertNewRow');
 instance.getPlugin('ColumnSummary').endpoints.endpoints  = newColumnSummaryArray;
```
it cause (number of errors = columns count )
```Uncaught TypeError: Cannot read property 'classList' of null
    at _removeClass (3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:670)
    at removeClass (3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:754)
    at 3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:37009
    at done (3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:37115)
    at 3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:37136
    at ColumnSettings.numericValidator [as validator] (3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:74953)
    at 3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:37132```

### Steps to reproduce
1. Run demo
2. change any cell
3. look at the console

### Demo
http://jsfiddle.net/74v7f2ht/6/

### Your environment
* Handsontable version: 1.12
* Browser Name and version: Chrome 60

**Comment by AMBudnik** [comment]
Hi @d-aven 

Thanks for sharing

Unfortuantely I cannot replicate the issue

```
at _removeClass (3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:670)
    at removeClass (3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:754)
    at 3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:37009
    at done (3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:37115)
    at 3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:37136
    at ColumnSettings.numericValidator [as validator] (3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:74953)
    at 3851a5d-87cdf14_handsontable.full_1-9b1a8f4.js:37132
```

I am also using Chrome 60 on Win10.

ps. please remember that the calls are made because the value change has been made And currently in Handsontable each change triggers a renderer for each cell.

**Comment by d-aven** [comment]
The problem is:
Why one change of one cell cause running columnSummary function (TotalEndpoints - 1) times but not only one?

The console errors is another story.

**Comment by AMBudnik** [comment]
Currently, a single cell change calls a renderer for all the table and that calls a renderer for each cell as well.
