### ISSUE TITLE
How to insert many cells , custom number 

### ISSUE THREAD

**Issue by aRealCat** [handsontable/handsontable#4440]
i want to  insert  many cells , not only one cell.
can it achieve ?   Thanks .

**Comment by KMASubhani** [comment]
1. Select the are to fill
2. Type in a value (it will only fill the upper left corner
3. Press `Ctrl` + `Enter`

**Comment by AMBudnik** [comment]
Hi @aRealCat 
if you need any more tips or more details please let me know.
