### ISSUE TITLE
Allow cancelling of autofill in the beforeAutofill hook

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4441]
### Description

It would be a nice feature to be able to return `false` in the `beforeAutofill` callback to prevent autofill from occurring similar to the `beforePaste` callback. We are wanting to run our own autofill callback when a user uses the autofill feature and don't want the original one to fire which is what we currently do for the CopyPaste functionality so it would be nice to be able to return `false` to prevent propagation of the autofill plugin.

**Comment by AMBudnik** [comment]
Hi @jeremy-smith-maco 

thanks for sharing the idea. You can also block the `autofill` via `beforeChange` hook http://jsfiddle.net/tr2Lfomv/
However, I am not sure if `beforeAutofill` should run before `beforeChange`

**Comment by jeremy-smith-maco** [comment]
Thanks for the suggestion.

**Comment by AMBudnik** [comment]
Thank you again for sharing the idea We have accepted it and copied to our feature request list at [Wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Thanks for reopening @wojciechczerniak

**Comment by AMBudnik** [comment]
Hi Jeremy,

I have good news! We've just released 8.0.0-beta2 introduces the following feature. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment]
@jeremy-smith-maco another issue closed as solved with v 8.0.0 :-) Demo https://jsfiddle.net/8eymzv2u/
