### ISSUE TITLE
Handsontable thows and error when we move the cursor in and out of the table

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4443]
### Description

Handsontable trows an error when we enable `comments` and move a cursor in and out of the table

![image](https://user-images.githubusercontent.com/10757813/28866413-2b3b9da0-7773-11e7-8cdc-a8865bf0535b.png)

### Steps to reproduce

1. Open a dropdown menu
2. Move the mouse cursor between the dropdown menu window and the scrollbar

I have tested few versions before but the result is the same for all.

![gif2](https://user-images.githubusercontent.com/10757813/28867796-a02fb476-7777-11e7-90ea-aea555e95319.gif)

### Demo

https://jsfiddle.net/mz569ss7/

### Your environment
* Handsontable version: 1.13.0 
* Browser Name and version: Chrome 60
* Operating System: Windows 10

**Comment by krzysztofspilka** [comment]
Looks good to me!
