### ISSUE TITLE
Handsontable --footer

### ISSUE THREAD

**Issue by apanigr** [handsontable/handsontable#4447]
### Description
Is there is any option to add footer for handsontable.
I have a requirement to add footer to handson table and it contains totals of only few rows. attached mocktable i need to add totals row as footer.

![image](https://user-images.githubusercontent.com/28731389/28922774-1a971a36-7879-11e7-9ad3-f5f5dc77a027.png)

### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version:handsontable-pro.git#1.10.0
* Browser Name and version: chrome
* Operating System: windows

**Comment by AMBudnik** [comment]
Hi @apanigr 

as mentioned at https://forum.handsontable.com/t/handsontable-footer/1268
You can try using  [fixedRowsBottom](https://docs.handsontable.com/pro/1.13.0/Options.html#fixedRowsBottom). Here is a simple example that adds a single fixed row at the bottom of the table http://jsfiddle.net/fet1928r/
