### ISSUE TITLE
registerRenderer not working after version 0.32.0

### ISSUE THREAD

**Issue by darkmavis1980** [handsontable/handsontable#4450]
### Description
Hi, I have some custom renderers that were working absolutely fine until version 0.31.0, using the `Handsontable.renderers.registerRenderer` method to extend the current renderers array, but from version `0.32.0` onward they don't seem to be registered anymore, as at the moment I associate the renderer to the celltype, my custom renderer is not there, I tried to console.log the `Handsontable.renderers` array right after I push the new renderers to it, and I still get the default renderers, like the `registerRenderer` never happened.
Any idea of what it could be?

### Your environment
* Handsontable version: 0.33.0
* Browser Name and version: Any
* Operating System: Any

**Comment by AMBudnik** [comment]
Hi @darkmavis1980 

Have you tried the [tips from the release notes for 0.32.0](https://docs.handsontable.com/0.34.0/tutorial-release-notes.html)?

**Comment by darkmavis1980** [comment]
Yes, already seen that, but still there's no mention on the `registerRenderer` method and I presume it supposed to work as originally intended

**Comment by AMBudnik** [comment]
I am sorry. This issue is the continuation for the renderers registering https://github.com/handsontable/handsontable/issues/4254
