### ISSUE TITLE
V0.34 is not working with Angular 4

### ISSUE THREAD

**Issue by mnolanjr98** [handsontable/handsontable#4452]
### Description
Handsontable v0.34.0 is not working with Angular v4.3.2 built from Angular CLI v1.2.6.  When adding a table into a component, the application hangs on the default "Loading..." screen with the following error message being logged in the browser - "Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten. Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. ..."

If I go back to v0.31.0 the table renders.

### Steps to reproduce
1. Create new application with Angular CLI (or use the attached Angular project)
-- If using attached --
1.1 In project root, run "npm install"
1.2 Run ng serve (you will need the Angular CLI globally installed)
--
2. Add new component into the application
3. Add table into the new component, populating some data
4. Reference component tag in the application component html template
5. Lauch browser and open console window in browser

### Your environment
* Handsontable version: 0.34.0
* Browser Name and version: Safari & Chrome
* Operating System: Mac El Capitan

[TBTodoApp.zip](https://github.com/handsontable/handsontable/files/1201754/TBTodoApp.zip)

**Comment by swistach** [comment]
Hi @mnolanjr98, 
try to add `import 'handsontable/dist/handsontable';`
before `import 'zone.js/dist/zone';`
in your `polyfills.ts` file.

**Comment by mnolanjr98** [comment]
This worked, thank you.  Did I miss this in the documentation?

**Comment by swistach** [comment]
Your welcome. No, it's just a incompatibility between `Handsontable` and `zone.js`.
This information will be in the [`angular-handsontable`](/hangsontable/angular-handsontable) documentation.

**Comment by turnerguo** [comment]
can not wait angular-handsontable project!! :D

**Comment by amily4555** [comment]
@swistach thk, cool

**Comment by renehamburger** [comment]
Thanks for the workaround, @swistach. This isn't great from the point of the user of your Angular wrapper.  Also, it makes it impossible to load Handsontable in a lazy module. Can you elaborate why Handsontable decided to wrap the global Promise object and whether it's likely to stay like that?

**Comment by bleuscyther** [comment]
In my case i da to move 
``` typeScript
import 'zone.js/dist/zone';  // Included with Angular CLI.`
```
to `main.ts` in addition to the workarround

**Comment by tauinbox** [comment]
@bleuscyther, ng tests won't run in that case

**Comment by eitland** [comment]
See my comment here: https://github.com/handsontable/angular-handsontable/issues/17#issuecomment-329746327

The solution I outlined in that comment fixes tests as well and IMO is _somewhat_ cleaner. Still waiting for a real fix for the underlying problem though.

**Comment by tauinbox** [comment]
@eitland, I'm using handsontable-pro which has its own handsontable lib dependency
