### ISSUE TITLE
CellProperties type missing in handsontable.d.ts from npm

### ISSUE THREAD

**Issue by astegmaier** [handsontable/handsontable#4453]
I'm moving from a typescript project that leveraged `@types/handsontable` to one that uses the `handsontable.d.ts` file included in the handsontable npm package, and I'm hitting an area where `@types/handsontable` appears to have some useful type definitions that are missing from `handsontable.d.ts`. Specifically, there is no type in `handsontable.d.ts` for `CellProperties`. For example, when I use types from `@types/handsontable` I'm able to write a cell renderer function that has a strongly-typed `cellProperties` parameter:
```
function customCellRender(instance, TD, row, col, prop, value, cellProperties: Handsontable.CellProperties) {
...
}
```
But writing the same function in the context of a project that uses `handsontable.d.ts` from the npm package will produce an error: `cannot find namespace 'Handsontable`.

Taking a look at `handsontable.d.ts`, it appears that the places where cellProperties might be used are actually defined as `object` (see [here](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L76-L78), [here](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L94), [here](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L927), [here](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1382), [here](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1403), [here](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1440), and [here](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1452))

This might be a specific case of a more general issue that @panesofglass noted [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18358#issuecomment-319474454)--namely `handsontable.d.ts` is "difficult to use due to its not matching up namespaces, etc. with the names used in the code or docs." Are there any plans to clean up  `handsontable.d.ts` to incorporate some of the goodness from `@types/handsontable`? If not, would you be open to PRs that address this issue in particular or the general problems that @panesofglass was talking about?

**Comment by AMBudnik** [comment]
Thank you for sharing @astegmaier 

have to be checked with https://github.com/handsontable/handsontable/issues/4355

**Comment by panesofglass** [comment]
@astegmaier the team seemed open to PRs when I spoke with them previously in #4112. @swistach and @AMBudnik, I still haven't upgraded to the latest with the included `handsontable.d.ts` due to inconsistencies in naming between the JS library and the TS definitions, as well as my inability to determine how to define cell validators or create a custom cell editor. Using the `handsontable.d.ts` from DefinitelyTyped, I was able to use:

```
const cellValidator: Handsontable.Validator = (value, callback) =>
    validateInjectionRate(value) ? callback(true) : callback(false)

// https://docs.handsontable.com/pro/1.10.1/tutorial-cell-editor.html
const InjectionRateEditor = (function () {
    const ctor = Handsontable.editors.TextEditor.prototype.extend()
    ctor.prototype.createElements = function () {
        // Call the original createElements method
        Handsontable.editors.TextEditor.prototype.createElements.apply(this, arguments)

        // Create input and update relevant properties
        const input = document.createElement("input")
        input.setAttribute("type", "text")
        input.setAttribute("height", "0")
        input.setAttribute("width", "0")
        input.classList.add("handsontableInput")

        // Update editor properties
        this.TEXTAREA = input
        this.textareaStyle = input.style

        // Replace textarea with text input
        Handsontable.Dom.empty(this.TEXTAREA_PARENT)
        this.TEXTAREA_PARENT.appendChild(this.TEXTAREA)
    }
    return ctor
})()
```

Would you be open to PRs including breaking changes to the `.d.ts` file, or at least multiple paths to the same thing?

**Comment by astegmaier** [comment]
I created PR #4519 to attempt to address this issue.

**Comment by AMBudnik** [comment]
Thank you very much @astegmaier

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/pull/4519
