### ISSUE TITLE
freezeColumn takes wrong column indexes

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4455]
### Description

According to docs via `freezeColumn` we can pick which columns we want to freeze. Currently, the method ignores the index inside the method and fixed columns one by one.

![image](https://user-images.githubusercontent.com/10757813/29060222-23da324c-7c19-11e7-9218-9ed33c2b03ed.png)

### Steps to reproduce

1. Scroll horizontally to check which columns have been fixed

We get columns with indexes `0` and `1` while the columns `0` and `8` should get fixed.

### Demo
http://jsfiddle.net/2wz6cz9s/

### Your environment
* Handsontable version: 0.34.0/1.13.0
* Browser Name and version: Chrome 60
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
The issue remains the same for version 0.35.1. Updated demo http://jsfiddle.net/ojhn1bno/

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment]
I've just got a tip from Joel, who says that

> It seems like manualColumnFreeze has to be set to true and columnSorting set to false for freezeColumn() to work as expected. Otherwise freezeColumn will always freeze the first column.

which has been tested here http://jsfiddle.net/handsoncode/2p7upmv6/ and it's a true thoery.

**Comment by AMBudnik** [comment]
The issue stays the same for v5.0.1 http://jsfiddle.net/3zstyrL5/

**Comment by wojciechczerniak** [comment]
`manualColumnFreeze` has to be enabled first with `manualColumnFreeze: true`: http://jsfiddle.net/xvwt813b/ (on init it enables `manualColumnMove` which is responsible for the column move).

Also your example has `columnSorting` enabled which is disabling `manualColumnMove` but it's a different issue: #4601.

I think we can close this issue as not a bug and remove the label. @AMBudnik please confirm if that solves your issue.

**Comment by AMBudnik** [comment]
You're right @wojciechczerniak 
thanks. We can close it.

**Comment by AMBudnik** [comment]
For everyone interested in this topic

We just fixed an issue related to this one. Please update to 8.0.0-beta1 and check if it solved for you as well.

Below are the resources

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```

And this is how you can download the beta from NPM

`npm i handsontable@beta`

**Comment by AMBudnik** [comment]
Referenced issue closed https://github.com/handsontable/handsontable/issues/4601 as solved
