### ISSUE TITLE
alter('inset_row', null) shifts getSelected() values

### ISSUE THREAD

**Issue by micgro42** [handsontable/handsontable#4458]
### Description
Calling `alter('inset_row', null,...)` with `null` as second argument shifts the values returned by `getSelected()` down by the number of inserted rows. However [the documentation](https://docs.handsontable.com/0.34.0/Core.html#alter) says:
> Insert new row(s) above the row with a given index. If index is null or undefined, the new row will be
added after the last row.

Using `alter('inset_row', undefined,...)` instead of `alter('inset_row', null,...)` resolved the problem

### Steps to reproduce
See Demos below
1. click in table
2. press Control
3. press Alt
==> both should show the same behavior

### Demo
PRO: https://jsfiddle.net/micgro42/t5f5tzcc/1/
Free: https://jsfiddle.net/micgro42/t5f5tzcc/2/

### Your environment
* Free: 0.34.0
* Pro: 1.13
* Firefox/Chrome on Linux

This might be related to #4448

**Comment by YakovL** [comment]
Looks related: #4448

**Comment by AMBudnik** [comment]
Thanks for sharing @micgro42 

you're right the result is not the same for both. As we state in the docs that the `null` and `undefined` values are equal this is surely a case to investigate.

**Comment by AMBudnik** [comment]
The issue is not replicable in v 5.0.1
PRO https://jsfiddle.net/f2u15oe3/
CE https://jsfiddle.net/gwLpskho/
