### ISSUE TITLE
Programmatically updating any cell disrupts user input

### ISSUE THREAD

**Issue by pbadenski** [handsontable/handsontable#4459]
### Description
While user is editing the table, if any cell is programmatically changed the value of user's input is discarded and brought back to what it was when they started.

Seems like this commit is the culprit: 8b80a22b94453dcf9e35b0bd5b841574da512429

### Steps to reproduce
Please visit: http://jsfiddle.net/s6t768pq/885/
1. Try to edit any cell - different than A1 which is being changed programmatically.

### Demo
http://jsfiddle.net/s6t768pq/885/

### Your environment
* Handsontable version: 34.0
* Browser Name and version: Chrome 60
* Operating System: MacOS 10.12

**Comment by d-aven** [comment]
Try to change A1 directly in sourceData and then render when you need.
```
var sourceData = hot.getSourceData();
sourceData[row][prop] = newValue;
```

then
`hot.render();`

**Comment by krzysztofspilka** [comment]
Hi @pbadenski , thanks for reporting this. This problem has a long history and the only quick solution is to work around it. See this demo, hope it will ease your pain somehow. http://jsfiddle.net/bksuz7kr/2/
