### ISSUE TITLE
dataSchema with non-null values

### ISSUE THREAD

**Issue by optilude** [handsontable/handsontable#446]
I had hoped to use dataSchema to initialise new rows with a default schema, e.g.

    dataSchema: {name: null, age: 0, hobbies: []}

I can see in the code that it uses a deep copy, but really weird things happen when I pass anything other than ``null`` as a value for an item in ``dataSchema``: I end up with lots of spurious extra rows when the table is first rendered, all filled with nothing.

I also tried to use ``onCreateRow`` to alter the newly created row to set a default value, but it has the same result.

**Comment by AMBudnik** [comment]
Could you please leave us feedback about this subject, I made a [little demo](https://jsfiddle.net/gsbgubw6/1/) for your example and it seems like it behave as expected.

**Comment by dkwebtec** [comment]
This is still not fixed in the last version. Changing value in cell causes adding a new spare row which is not needed

https://jsfiddle.net/8rn5mfpL/

**Comment by wojciechczerniak** [comment]
@dkwebtec This is controlled by [isEmptyRow callback](https://handsontable.com/docs/7.4.2/Core.html#isEmptyRow) in settings object. Maybe you can use it to customize behavior to your requirements: https://jsfiddle.net/a3brg1tp/

You can use our default as a starting point: https://github.com/handsontable/handsontable/blob/88d78a5be5e37ad703c11914c86690d2436d3024/src/defaultSettings.js#L1045-L1065
