### ISSUE TITLE
How to trigger event for custom buttons

### ISSUE THREAD

**Issue by d-aven** [handsontable/handsontable#4460]
How to click programmatically on the custom button?

### Demo
https://docs.handsontable.com/0.34.0/demo-custom-buttons.html

**Comment by AMBudnik** [comment]
Hi @d-aven 

I am not sure what you would like to accomplish. Can you share more details? You want to run the function behind the button or allow user to click the button and then perform an action (demo http://jsfiddle.net/mx18v4zx/) ?

**Comment by d-aven** [comment]
I wanted to run the function somehow like that $(div).trigger('mousedown') or using Handsontable EventManager (method fireEvent).

I've run it directly.

Thank you!
