### ISSUE TITLE
When a cell is copied, is anything copied aside data? Any attributes?

### ISSUE THREAD

**Issue by YakovL** [handsontable/handsontable#4461]
My issue is the following:

- I'd like to set different representations for different bits of content ("list level" for emulating a multilevel list inside HOT; "don't save" for special rows used for editing content bits that is not represented in the `options.data` array itself)
- the representation details should be copied with a cell when it is copied from such HOT and pasted to a HOT with similar options
- the representation details should not create "artifacts" when some content is copied from a HOT and pasted into another spreadsheet (office, google docs etc), hence I don't want to store that stuff inside cells (inside the `options.data` array)

So I wonder, are there some attributes that are copied when a cell is copied (aside `.data[row][col]` itself)? Is there one that can be used to store arbitrary metadata?

**Comment by AMBudnik** [comment]
Hi @YakovL 

we copy only the value (without metadata). If you would like to store metadata I recommend passing it to a helper via `beforePaste` hook.
