### ISSUE TITLE
How do I move (rearrange) rows programmatically?

### ISSUE THREAD

**Issue by YakovL** [handsontable/handsontable#4462]
So there's [`manualRowMove` param](http://docs.handsontable.com/0.34.0/demo-moving.html) that allows to move rows by drag&drop; I'd like to introduce moving them with hotkeys. What's the best way to do this?

I think manipulating the original `options.data` array and using `.render` may be an ok solution; however, firing `afterChange`/`afterRowMove` would be helpful and I also keep in mind the other issue I've shared (#4461 – moving other attributes would be very helpful, if they are copyable).

**Comment by AMBudnik** [comment]
Hi @YakovL 

I have to say that I found it really hard to imagine. Could you share a scenario? Basically, when we move rows via mouse we pick which row we want and its destination position. Do you want to create a key map for all possible options? 

Whatever you would like to do there are two hooks to look at `beforeKeyDown` and `afterDocumentKeyDown`

**Comment by YakovL** [comment]
What I want is when a cell (or a range of cells) is selected to be able to press ctrl+down (or another hotkey) to shift the rows with the selected cells by one row (when this happens, the row that was below the selected cells becomes above them)

**Comment by AMBudnik** [comment]
An interesting option. Here http://jsfiddle.net/handsoncode/a49efd1f/ I have done something pretty similar.

**Comment by YakovL** [comment]
Thanks, here's a simplified piece of code that also doesn't have that "only once" problem:
http://jsfiddle.net/a49efd1f/1/
I've also made it move multiple rows and keep "proper" selection:
http://jsfiddle.net/a49efd1f/2/
I wonder why it is `plugin.moveRow(row, row + 2);`, not `plugin.moveRow(row, row + 1);`...

**Comment by AMBudnik** [comment]
Hi @YakovL 

do you get any console errors? The following code works with 0.34.0 (latest CE version) as well http://jsfiddle.net/6smudwcy/

**Comment by YakovL** [comment]
Ah, I see, I missed the `manualRowMove: true` bit. Thanks!
