### ISSUE TITLE
Handsontable throws an error when validate after filter

### ISSUE THREAD

**Issue by hung-nguyen89** [handsontable/handsontable#4463]
### Description
Handsontable throws an error when validate after filter
![image](https://user-images.githubusercontent.com/30921090/29203184-34dcc668-7e99-11e7-977d-6e4ab2b90f25.png)

`Handsontable.getCell` parameters are visual row and col, but

```javascript
  function validateChanges(changes, source, callback) {
    ...
        /* eslint-disable no-loop-func */
        if (instance.getCellValidator(cellProperties)) {
          waitingForValidator.addValidatorToQueue();
          instance.validateCell(changes[i][3], cellProperties, function (i, cellProperties) {
            return function (result) {
              if (typeof result !== 'boolean') {
                throw new Error('Validation error: result is not boolean');
              }
              if (result === false && cellProperties.allowInvalid === false) {
                changes.splice(i, 1); // cancel the change
                cellProperties.valid = true; // we cancelled the change, so cell value is still valid
                var cell = instance.getCell(cellProperties.row, cellProperties.col);
                (0, _element.removeClass)(cell, instance.getSettings().invalidCellClassName);
                --i;
              }
              waitingForValidator.removeValidatorFormQueue();
            };
          }(i, cellProperties), source);
        }
      }
    }
   ...
  }
```
In `validateChanges`, `instance.getCell` is using physical row & col, is it the reason?
### Steps to reproduce

1. Filter a column
2. Input invalid value for a cell

### Your environment
* Handsontable version: 1.12.0

**Comment by AMBudnik** [comment]
Hi @hung-nguyen89 

can you tell me how to replicate the issue?

I have created a demo with numeric columns and filters at http://jsfiddle.net/krph4w6x/

and What I do is
1. Filter column 'Year' unselecting '2011'
2. Enter 'u' in the first cell of the column

and I do not get any logs.

**Comment by hung-nguyen89** [comment]
Hi @AMBudnik 
I have used your demo and got same error.

1. Set 'allowInvalid' = false for 'Year' column
2. Filter column 'Year' unselecting '2011', '2012', '2013'
3. Enter 'u' for '2015' cell
4. Select any cell of first row
5. Check the log

**Comment by AMBudnik** [comment]
Thank you for sharing the scenario. I have replicated the issue

**Comment by AMBudnik** [comment]
I am not able to replicate the issue in v 5.0.1. Demo http://jsfiddle.net/7Lru391o/
If you are still having any issues with the code @hung-nguyen89 please leave a comment
