### ISSUE TITLE
Unit Test Helpers for Custom Renderers and Editors

### ISSUE THREAD

**Issue by jongunter** [handsontable/handsontable#4464]
I'm working on a project with a bunch of custom cell types, renderers, and editors.  The are separated into different files and I would like to be able to unit test these individual components in my Jasmine/Karma setup.  Renderers are kind of easy because they are just functions (I just have to mock out a `<td>`) .However, the work to set up a Handsontable full of testing data and then stub/mock/spy on various dependencies for testing editors seems like it would be a lot of work. Are there any testing helper classes I can use here?

I can follow up in a bit with some examples of scenarios where a Handsontable unit test harness/helper would be time-saving.

**Comment by AMBudnik** [comment]
Sorry for a late reply. Unfortunately, we do not have any API for tests.

**Comment by jperasmus** [comment]
Hi @jongunter 

Did you make any headway with this? I'm in a very similar situation. Do you perhaps have any examples of how you got it working?
