### ISSUE TITLE
Set color of cell using x and y coordinates

### ISSUE THREAD

**Issue by bhismalab** [handsontable/handsontable#4467]
### Description
I want to set the background color of a cell by using x and y coordinates. The solutions I have found so far require changing the cell based on preset rules, but I ideally want something that is similar to the "setDataAtCell" structure rule - except for style. I'm hoping I've overlooked the documentation for it. Is there code analagous to:

handsOnTable_TableName.setDataAtCell(x_coord,y_coord,content); 

except for style?

**Comment by AMBudnik** [comment]
Hi @bhismalab 

you can use `setCellMeta` like `setCellMeta(0,0, 'className', 'myClass)`

demo: http://jsfiddle.net/handsoncode/qhduhd98/
