### ISSUE TITLE
Feature Request - Ability to add custom key name for nested rows

### ISSUE THREAD

**Issue by ovation22** [handsontable/handsontable#4468]
Would it be possible to provide a custom key name property for custom rows so as not force data to adhere to __children?

**Comment by AMBudnik** [comment]
It is currently not possible but surely it is an interesting idea. Thank you for sharing @ovation22

**Comment by AMBudnik** [comment]
Thank you for sharing the idea We have accepted it and copied to our feature request list at [Wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
