### ISSUE TITLE
Define HOT vars for es environment

### ISSUE THREAD

**Issue by exytab** [handsontable/handsontable#4471]
### Description
`__HOT_BUILD_DATE__`, `__HOT_PACKAGE_NAME__`, `__HOT_VERSION__`, `__HOT_BASE_VERSION__` are unresolved in `es/index.js`

When you build `es` folder, you can define variables using `babel-plugin-transform-define` or `babel-plugin-define`

**Comment by AMBudnik** [comment]
Thank you for sharing @exytab

**Comment by budnix** [comment]
Thanks, @exytab for the suggestion. We've fixed all global variables and replaced them with `transform-inline-environment-variables` babel plugin. The newest version of The Handsontable contains all the necessary fixes.
