### ISSUE TITLE
Copy/Paste changes numeric data datatype to string

### ISSUE THREAD

**Issue by ankushgoel** [handsontable/handsontable#4474]
### Description
Pasting data from excel to Handson, converts numeric data to string even if `type` is set to `numeric` in 

### Steps to reproduce
1. Just copy data from excel and paste into HOT
2. Console `hot.getSourceData()`
3. You will see that the data has been converted to string.

**Comment by AMBudnik** [comment]
Thank you for sharing the issue @ankushgoel 

Related to https://github.com/handsontable/handsontable/issues/4111

**Comment by AMBudnik** [comment]
Still replicable in v `2.0.0` http://jsfiddle.net/r1xbgq3e/

**Comment by AMBudnik** [comment]
I think that it is not a bug, as we have defined the cell type as `text`. If I change it to `numeric` I got the correct result. It is something that we should discuss.

**Comment by swistach** [comment]
With defined cell's type everything works as expected: https://jsfiddle.net/yj0bcLqp/
