### ISSUE TITLE
does SetDataAtCell() accept full objects?

### ISSUE THREAD

**Issue by astegmaier** [handsontable/handsontable#4475]
In my tests, calling `SetDataAtCell(rowNum, colNum, object)` where `object` is a full JavaScript `object` or class instance appears to work fine - the full `object `is saved at that location in the data source.  (This is great for my scenario, because I'd like to store extra metadata on peice of data rendered, but also have this be available in the clean data array, rather than stuffed into cellmetadata)

However, the [documentation](https://docs.handsontable.com/0.34.0/Core.html#setDataAtCell) and [handsontable.d.ts](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1600) both say that the third parameter has to be a `string`. Is there something I'm missing that will come back to bite me down the line? Or should the documentation and TypeScript definition be updated?

**Comment by AMBudnik** [comment]
Hi @astegmaier 

Let's take a look at the example

 ```
var myObject = {
    names: ['John', 'Mark'],
    surname: 'Smith',
    address: {
      country: 'United States',
      state: 'OH',
      city: 'Lancaster',
      street: 'Slearcreek Rd SW 1'
    }
  }

hot.setDataAtCell(0, 0, myObject.address.city)
```

the result is a string and it is displayed correctly

![image](https://user-images.githubusercontent.com/10757813/29616539-26b86510-8812-11e7-9e0a-784947376cd5.png)


but when we would like to refer to an object (let's say the whole `address`, then rendering fails.

![image](https://user-images.githubusercontent.com/10757813/29616597-56dbc8c2-8812-11e7-830a-d4be87ee8e82.png)

so it's more like the result of what we put in the 3rd parameter has to be a string. You're able to [use a function](http://jsfiddle.net/handsoncode/r1g3mznn/) as long as it returns a single value (can be a `string`, `boolean` or a `number`).

ps. if you have an idea on how we could change the description I'd love to hear it.
As you rightly spotted there could be a slight misconception in this subject.

**Comment by astegmaier** [comment]
Thanks for the response @AMBudnik!

If you use a custom renderer that knows how to handle an object (or, override the `toString()` method of the object that you pass into `SetDataAtCell`), it would be easy to get the renderer to display something useful. That's what I'm doing in my scenario.

I guess I'm wondering if there would be bad side-effects if I use `SetDataAtCell`. If I read your response correctly, it sounds like the answer is "no, as long as you do something to make sure the rendering will work with the object you provide)."

If this is the case, would you be open to a PR that updates the  [documentation](https://docs.handsontable.com/0.34.0/Core.html#setDataAtCell) and [handsontable.d.ts](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1600) to make it clear that this `SetDataAtCell` accepts `string`, `boolean`, `number`, _or_ `object`? (With a small note that _if_ you pass an object, it's also up to you to handle rendering correctly)?

**Comment by AMBudnik** [comment]
Hi @astegmaier 

> "no, as long as you do something to make sure the rendering will work with the object you provide)."

I can agree. In some cases, you would need to push some custom code to the validator as well.

ps. we're open for PRs (as long as it follows the [Contributing guidelines](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) :))

**Comment by astegmaier** [comment]
@AMBudnik - Great!

I went ahead and created PR #4481 to make this change to `handsontable.d.ts`, and a simple test. This is my first PR to handsontable so please let me know if I messed anything up--I tried to follow the contributing guidelines and signed the contributor license agreement.

**Comment by AMBudnik** [comment]
Thank you very much @astegmaier 

Everything is fine and I can see that our developer has already merged the PR.
I suppose that we can close this issue.
