### ISSUE TITLE
Row position in sourceData

### ISSUE THREAD

**Issue by d-aven** [handsontable/handsontable#4476]
I have table with trimmed rows and after inserting new row it gets position of visual row (not physical).
It is impossible to refer to data directly now.

### Steps to reproduce
1. Click "insert row" button
2. Click "Console" button
3. You will see 
![image](https://user-images.githubusercontent.com/19648531/29569716-043d4d76-875d-11e7-9ab0-8b449d853a55.png)

Row is placed between "A8" and "A9", but in sourceData it's between "A6" and "A7".
I was very convenient to refer to sourceData directly to retrieve data from trimmed rows.
Is there any method to convert real row index to index in sourceData?

### Demo
http://jsfiddle.net/wxah3zg3/1/

### My environment
* Handsontable version: 1.13
* Browser Name and version: Chrome (latest)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @d-aven 

Correct me if I'm wrong, you would like to get a new row between `A6` and `A7`?

**Comment by d-aven** [comment]
I would like to have this row on position between "A8" and "A9" in sourceData.

**Comment by AMBudnik** [comment]
I am afraid that the only way is to untrim the rows, add the row and trim rows again. We can't add a row visually in the other index than physically.

**Comment by d-aven** [comment]
if I just use Array.prototype.splice for sourceData instead of alter('insert_row'), I will have problems in future?

**Comment by AMBudnik** [comment]
Without testing, I cannot predict if it would work either cause any problems in the future.
