### ISSUE TITLE
Handsontable throws an error after mouse leave

### ISSUE THREAD

**Issue by hung-nguyen89** [handsontable/handsontable#4477]
### Description
Handsontable throws an error after mouse leave.

### Steps to reproduce
I have used this handsontable's example
https://docs.handsontable.com/pro/1.13.0/demo-comments_.html#example

1. Select any cell.
2. Move the mouse to scroll bar.
3. Check the log.

![image](https://user-images.githubusercontent.com/30921090/29596564-efcf4c32-87e7-11e7-961e-91205d61c010.png)

**Comment by AMBudnik** [comment]
Thank you @hung-nguyen89 

the issue has been already added at https://github.com/handsontable/handsontable/issues/4443
Please add anything if needed to https://github.com/handsontable/handsontable/issues/4443
