### ISSUE TITLE
Memory leak in Json Patch if using handsontable in single page application

### ISSUE THREAD

**Issue by vidyapati** [handsontable/handsontable#4479]
### Description
If you are using handsontable in single app aplication with node (in my situation Electron with Angular 4), you are getting memory leak if you switch between other components and component with populated handsontable.

[Snapshot 1](http://imgur.com/a/RTbkv)
[Snapshot 2](http://imgur.com/a/D7eUX)

### Probable Cause
node cache handsontable library, so if you are switching between components with populated handsontable, Json Patch library beforeDict keeps growing.

### Steps to reproduce
1. Create Single Application App (Electron + Angular 4) with 2 components, one with populated handsontable
2. Switch between two components
3. Memory leak in json patch beforeDict

### Your environment
* Handsontable version: 0.31.2
* Node version: 6.11.0
* Browser Name and version: Electron 1.6.11
* Operating System: Win 10 64 bit

**Comment by AMBudnik** [comment]
@swistach can you check if that relates to hot or the specified environment?
thank you for your effort to investigate the case @vidyapati

**Comment by swistach** [comment]
Hi @vidyapati,
it's the same issue like #4400. You can set `observeChanges: false`, then the table should work correctly.
