### ISSUE TITLE
mergeCells, customBorders, colWidths setting don't change after they're changed in the UI

### ISSUE THREAD

**Issue by lab4quant** [handsontable/handsontable#4482]
### Description

We're trying to save the configuration to file, which can be loaded to re-create the handsontable
some settings like `data`, `cell`, when changing in the front end, those settings are changed too.
But some settings like `mergeCells`, `customBorders`, `colWidths` are not in sync with UI.

e.g. after adjusting column with, the `colWidths` is still the same value as it was passed to create handsontable.

merging cells, changing cell borders have the same issue.

### Steps to reproduce

1. drag to change column width
2. merge some cells
3. changing cells border
4. see setting printed in console, they're the same value passed to created handsontable

### Demo

http://jsfiddle.net/quantlab/y9fkzpe8/
### Your environment
* Handsontable version: latest
* Browser Name and version: Chrome latest
* Operating System: windows 7

**Comment by AMBudnik** [comment]
Hi @lab4quant 

Can you please take a look at the .gif below and let me know what I am doing wrong to replicate the issue?

![4gif](https://user-images.githubusercontent.com/10757813/29705811-f85b5244-897f-11e7-97ef-3c6f37d42410.gif)

(I'm testing on Chrome 60/ Win 10)

**Comment by lab4quant** [comment]
@AMBudnik , thanks for the update, the handsontable column width can be adjusted in the front end.
But after that, the setting doesn't change, I'm trying to get the updated setting and save it to a file.
Please check the browser console log, after changing column width, the setting.colWidth is still the same

**Comment by AMBudnik** [comment]
I have found two issues that sound related 

https://github.com/handsontable/handsontable/issues/4375
https://github.com/handsontable/handsontable/issues/3594

Does any of those relate to your scenario?

**Comment by lab4quant** [comment]
@AMBudnik , yeah, that sounds like same issue, beside colWidth, some other settings are not updated too, like mergeCells, customBorders
Will this be fixed in future release?

**Comment by AMBudnik** [comment]
I think that the nearest task related is the `updateSettings `refactor. It's on our to-do list https://trello.com/c/GPIcskO9/88-rewrite-updatesettings-to-unlock-more-features however there is no deadline for this task yet

**Comment by lab4quant** [comment]
@AMBudnik , thank you!
