### ISSUE TITLE
Please consider adding flipDatePickerIfNeeded()

### ISSUE THREAD

**Issue by yuwong** [handsontable/handsontable#4483]
As you have created function `flipDropdownIfNeeded` in response to #3210.

Please consider the equivalent for the date picker as well :)

**Comment by AMBudnik** [comment]
Hi @yuwong 

thank you for sharing your proposition.

It has been already set as a bug at https://github.com/handsontable/handsontable/issues/3483
Please share the progress about the issue at https://github.com/handsontable/handsontable/issues/3483

**Comment by yuwong** [comment]
Thanks @AMBudnik! Will follow the progress there instead, meantime I'll continue with the bit of hacky code I'm using to address this.
