### ISSUE TITLE
Joomla SqueezeBox modal window call problem with Handsontable

### ISSUE THREAD

**Issue by marcleimvs** [handsontable/handsontable#4485]
### Description
I have a form with a button in it to call a modal window  for item selection using Joomla and SqueezeBox.
This operation miss behave when I add a handsontable in the form.
When a hit the button the black overlay of SqueezeBox shows up, but the selection form does not.
Without the handsontable object and scripts, the operation works fine.
Probably something to do with Handsontable Overlay Object, not sure.
Used trial versions pro 12 and 13 and the problem persists, but does not happen with trial pro version 11.

### Steps to reproduce
1. added a button: 
<a class="btn modal hasTooltip" title="" href="index.php?option=com_sadpess&amp;view=contatos&amp;layout=modal&amp;tmpl=component&amp;function=jSelectContato_jform_contato_id&amp;8f92c13d98af341175ca519f6fd0aec3=1" rel="{handler: 'iframe', size: {x: 1024, y: 450}}" data-original-title="Select a Contact"><i class="icon-search"></i></a>
2. added a handsontable component
3. when i hit the button, only a black screen shows up, no selection form. 

### Your environment
* Joomla 3.4.7, SqueezeBox 1.3
* Chrome 60.0.3112.90 32bits
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
Hi @marcleimvs 

To check what is the cause we would need to replicate the issue. Do you have any possibility of sharing a demo?

If it worked using 1.11.0 there has to be something related to [v1.12.0](https://docs.handsontable.com/pro/1.12.0/tutorial-release-notes.html). Do you get any console errors?

**Comment by marcleimvs** [comment]
Cannot share a demo once my website is hosted on a military facility intranet, but a can share pictures below:
![picture-01](https://user-images.githubusercontent.com/13579165/29784154-66d8a516-8bf9-11e7-9410-f98f16ca83d7.jpg)
![picture-02](https://user-images.githubusercontent.com/13579165/29784164-6c1ab384-8bf9-11e7-8906-44bc6dae3b37.jpg)
![picture-03](https://user-images.githubusercontent.com/13579165/29784169-70688376-8bf9-11e7-9368-318cc0eb89de.jpg)
![picture-04](https://user-images.githubusercontent.com/13579165/29784174-75855abe-8bf9-11e7-8071-93d5b67c036e.jpg)
![picture-05](https://user-images.githubusercontent.com/13579165/29784177-79082b80-8bf9-11e7-8d32-33e27fad7ab7.jpg)

**Comment by AMBudnik** [comment]
Without a demo, I won't be able to help you much. Can you check if the Handsontable is visible in the DOM and if it is does adding

`instance.render()` or `setTimeout()` for `instance.loadData()` solves the issue?

**Comment by AMBudnik** [comment]
I guess that the issue has been solved as there is no reply for more than 2 weeks

**Comment by marcleimvs** [comment]
After debugging the code i find out that mootools library have the function "Array.from" which is also present in handsontable library, but with different arguments and return object, that´s what was crashing the popup window from coming up. I have changed the function "Array.from" to "Array.fromht" and the references in the handsontable library code and this fixed my problem!

**Comment by AMBudnik** [comment]
Thanks for the tip.
It will surely help other devs that will find this issue.
