### ISSUE TITLE
Uncaught TypeError: Invalid attempt to destructure non-iterable instance

### ISSUE THREAD

**Issue by ankushgoel** [handsontable/handsontable#4486]
### Description
```
Uncaught TypeError: Invalid attempt to destructure non-iterable instance at handsontable.full.js:83336 
	at handsontable.full.js:83336:585
	at handsontable.full.js:83854:25
	at arrayEach (handsontable.full.js:257:9)
	at Filters.onAfterChange (handsontable.full.js:83853:30)
	at Core.<anonymous> (handsontable.full.js:83577:23)
	at Hooks.run (handsontable.full.js:4517:46)
	at Core.runHooks (handsontable.full.js:41901:49)
	at Object.replace (handsontable.full.js:74001:24)
	at handsontable.full.js:74007:30
	at arrayEach (handsontable.full.js:257:9)
```
This error comes in console on scroll when handson is loaded with 2-5k rows with filter plugin

### Your environment
* Handsontable version: 1.13.0
* Browser Name and version: Chrome 59.0.3071.86
* Operating System: Ubuntu 16.04

**Comment by AMBudnik** [comment]
Hi @ankushgoel 

I have tried to replicate the issue using this Fiddle http://jsfiddle.net/handsoncode/xabsaqax/ but did not get the error.

Can you share a demo where this issue occurs?

Thanks!

**Comment by ankushgoel** [comment]
`createSpreadsheetData` helper tool puts dynamic data in hot which doesnot create this error
This error can be replicated by loading static data in hot

**Comment by ankushgoel** [comment]
And I am also using Semantic js with hot, maybe they have conflicting codes!

**Comment by AMBudnik** [comment]
I think it might be the Semantic
I have tested it with static data (more than 4k) http://jsfiddle.net/handsoncode/L7dnhvs5/ but did not get the issue

**Comment by ankushgoel** [comment]
When I set `filters: false`, this error gets resolved.

**Comment by AMBudnik** [comment]
Please check if enabling filters and disabling semantic.js also solves the issue

**Comment by ankushgoel** [comment]
The error still persists.

**Comment by AMBudnik** [comment]
Please share a demo where I will be able to replicate the issue. I have tried a helper and a static dataset without any luck

**Comment by ankushgoel** [comment]
Issue is coming due to custom renderer.
Because when I remove all the custom renderers, again the error gets resolved.

**Comment by AMBudnik** [comment]
And what is the code for the renderer?

**Comment by ankushgoel** [comment]
I am still figuring out which renderer is creating this issue.
As soon as I get to know, i will definitely share the problem.

**Comment by AMBudnik** [comment]
the `setDataAtCell` always calls `afterChange` and re-renders the whole table (that's why it's slow).

**Comment by ankushgoel** [comment]
can I use this `hotData[row]type = value` without getting error.

**Comment by AMBudnik** [comment]
Sorry but I do not know what is the `hotData` in your case.

**Comment by ankushgoel** [comment]
`hotData` is the array of objects which I loaded(using `hot.loadData(hotData)`) into Hot at the time of initialization.

**Comment by AMBudnik** [comment]
I guess that without a demo there is not much that I can do. It looks like the issue is related to internal `_slicedToArray` but it also doesn't tell us much why you are getting this error.
