### ISSUE TITLE
Changing numeric format of a single cell or whole row

### ISSUE THREAD

**Issue by leekranefuss** [handsontable/handsontable#4488]
This is pretty simple, but I can't figure out what to set...

My data is row (not column) oriented.  I also have some cells that are unique.  They are numeric and need to show as %.

In both cases, I can easily get the cells individually and set look and feel programatically, like so:

var row=1;
 var col=2;
 var cell = hot.getCell(row,col);
 cell.style.fontWeight = 'bold';

But what would seem to be the likely candidate, cell.style.format="0%" or cell.format="0%" does not work.  Presumably, I am missing an intermediate layer, something like cell.foo.format="0%".

How do I do this?

**Comment by AMBudnik** [comment]
Hi @leekranefuss 

have you been adding `type: numeric` as well?

Here is a working example for rows and `0%` format http://jsfiddle.net/handsoncode/17tzx282/
