### ISSUE TITLE
Show current hidden columns only unhiding every other column

### ISSUE THREAD

**Issue by ankushgoel** [handsontable/handsontable#4489]
### Description
hiddenColumns plugin issue
```
var hiddenPlugin = hot.getPlugin('hiddenColumns');
var currentHidden = hiddenPlugin.hiddenColumns;
hiddenPlugin.showColumns(currentHidden);
hot.render();
```
Instead of showing all of the currently hidden columns, its only showing every other column.
There's also another issue with hiddenColumns plugin #4251 

### Steps to reproduce
Just open the fiddle and click on Show All button

### Demo
https://jsfiddle.net/ankushgoel/46jxapkp/

### Environment
* Handsontable version: 1.13.0

**Comment by AMBudnik** [comment]
Hi @ankushgoel 

I think that this issue is strongly related (if not the same) as the one we have already marked as a bug (the one from the link). Am I missing something different is this case?

**Comment by AMBudnik** [comment]
I assume that (as I thought) the issue has been solved with the previously opened.
