### ISSUE TITLE
custom renderer got called even after scrolling or adjust colum width

### ISSUE THREAD

**Issue by lab4quant** [handsontable/handsontable#4490]
### Description

I'm using custom renderer, inside which I call my own function, which is not supposed to be called multiple times unless the data is changed

I found my custom renderer gets called too frequently, I debug into it and found the renderer got called even after scrolling, adjusting colun with, etc, which doesn't trigger 'afterchange'

Is this per design?

If yes, how can I prevent my code inside renderer getting called when there's no change in the data?

thanks!

### Steps to reproduce

1. drag to change column width
2. double click cell
3. scroll up/down
4. check web browser console, you'll see renderer gets call everytime, when data is not changed

### Demo

http://jsfiddle.net/quantlab/k2cn6e93/4/

### Your environment
* Handsontable version: 0.33.0
* Browser Name and version: chrome, latest
* Operating System: windows

**Comment by AMBudnik** [comment]
Hi @lab4quant 

the renderer is called each time the table needs to be rerenderer so not only after changes but also when the table scrolls as it needs to load additional data to be viewed.
Does your custom renderer does exactly the same thing that the one from the demo?

**Comment by lab4quant** [comment]
@AMBudnik , thanks, I changed my custom renderer
