### ISSUE TITLE
Undoing remove row action does not bring back read only values

### ISSUE THREAD

**Issue by efeker** [handsontable/handsontable#4491]
### Description

When handsontable has read only columns and user undoes remove row action, read only values do not come back.

### Steps to reproduce

1. Ensure you have at least one read only column.
2. Remove a row.
3. Undo.
4. Notice that read only columns don't have values

### Demo
http://jsfiddle.net/c47tbo90/

### Your environment
* 31.1
* Version 60.0.3112.113 (Official Build) (64-bit)
* Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing @efeker !

I have replicated the issue and simplified the example http://jsfiddle.net/handsoncode/191f0abw/ and it acts the same with minimal settings.

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/4754
