### ISSUE TITLE
After manual column width increase, some rows aren't rendered

### ISSUE THREAD

**Issue by gumanoid** [handsontable/handsontable#4492]
Demo: http://jsfiddle.net/2e8j4jyp/

Preconditioins:
- HOT free 0.34
- manual column resize enabled
- row auto-wrap enabled
- table height is not enough to display all data, there's horizontal scroll bar
- some column has text longer than column width, so that text is auto-wrapped and thus occupies more than one line

Steps to reproduce:
- increase height of column with wrapped text so that the text fits into single line

Expected: all the rows that now fit into viewport are rendered

Actual: only those rows that were previously visible are rendered; there's blank space below them. Missing rows show up only after something that forces re-rendering, e. g. scroll event.

**Comment by AMBudnik** [comment]
Hi @gumanoid 

Sorry but I am not sure how to replicate the issue. Can you please record it?
Also please share your os/browser details.

**Comment by gumanoid** [comment]
Maybe some screenshots can clarify.
1. Table just loaded, dates in column A are wrapped, everything is correct so far: http://imgur.com/a/lwrRa
2. After increasing with of column A, there is blank space below row 23: http://imgur.com/3mtIEoa
3. But if I, for example, click on any row, it turns out that there are more rows: http://imgur.com/jtTyyJf

In the fiddle mentioned, there's workaround that helps:
`Handsontable.hooks.add('afterColumnResize', hot3.render, hot3);`

This WA doesn't work for my real code though. I haven't figured out why yet.

**Comment by AMBudnik** [comment]
Have you tried to add a slight delay to the `render()` (let's say 10ms)?

**Comment by gumanoid** [comment]
What worked for me is:
`Handsontable.hooks.add(
            'afterColumnResize',
             function(currentColumn, newSize, isDoubleClick) {
                setTimeout(hot3.render, 0);
             },
             hot3);`

**Comment by AMBudnik** [comment]
ok, great!

I have marked the issue as something that needs a `change`.

**Comment by gumanoid** [comment]
Nice, thanks :)

**Comment by gumanoid** [comment]
Even with the WA in place, and 1000 ms delay, there's still unwanted blank space: https://imgur.com/DsZ1hEu. With 1 second delay, after resizing, I see big blank space, then smaller blank space, and, if I click on any row, blank space is finally filled with data (re-rendered).

I guess there's a bug in recalculating row height or viewport height. This time it's Firefox 41 (plz don't ask why I use version that old, it's just customer's requirements)

**Comment by AMBudnik** [comment]
The same issue as https://github.com/handsontable/handsontable/issues/4653

**Comment by yansern** [comment]
Even with setTimeout delays it didn't work for me, but what I found working was to manually trigger the scroll event (and I had to do it multiple times). It's an ugly fix but it works.

```
var x = 5;
while (x--) {
	$(".ht_master .wtHolder")[0].dispatchEvent(new Event('scroll'));
}
```

**Comment by IgorFIE** [comment]
In my case this happens when I create a extra row and hide it, that causes the table to update it rows to have a different size, showing less rows in the table like the https://github.com/handsontable/handsontable/issues/4653 issue.

To solve it I needed to add 2 timeouts, but this is not the best solution.

`setTimeout(handsontableInstance.render,0);
setTimeout(handsontableInstance.render,0);`
