### ISSUE TITLE
Default export Hansdontable

### ISSUE THREAD

**Issue by jornare** [handsontable/handsontable#4495]
https://github.com/handsontable/handsontable/blob/14cd919b1c902a22ac57456349a6862be058aca8/src/index.js#L169

Please add a default export as such:
```
Handsontable.default = Handsontable;
module.exports = Handsontable; 
```
It solves an issue when imported in Webpack test scenario, maybe others.

**Comment by AMBudnik** [comment]
Thank you for sharing your proposition.

**Comment by budnix** [comment]
@wszymanski similar changes added into https://github.com/handsontable/handsontable-pro/commits/feature/issue-ce/4495 branch.

**Comment by swistach** [comment]
Hi @jornare, could you check this issue out with the latest version (0.34.2)?

**Comment by jornare** [comment]
We are relying on it through angular-handsontable, which currently has a hard dependency to 0.34.1. I'll let you know if we get the time to hack our way around. If you are planning a new release of angular-handsontable with this new dependency anytime soon we may wait with the test.

**Comment by swistach** [comment]
New version is released.
More details: https://github.com/handsontable/angular-handsontable/releases/tag/1.0.0-beta2

**Comment by jornare** [comment]
Just noticed, we will check it out tomorrow morning.

**Comment by jornare** [comment]
I see there are a few more changes to the package.
Just updating the references now yields these errors in the browser console:
```
handsontable.js:30180 Uncaught ReferenceError: Handsontable is not defined
    at Object.exports.__esModule (handsontable.js:30180)
    at __webpack_require__ (handsontable.js:58)
    at Object.exports.__esModule (handsontable.js:9083)
    at __webpack_require__ (handsontable.js:58)
    at Object.<anonymous> (handsontable.js:25731)
    at __webpack_require__ (handsontable.js:58)
    at exports.__esModule (handsontable.js:101)
    at handsontable.js:104
    at webpackUniversalModuleDefinition (handsontable.js:31)
    at Object.map../af (handsontable.js:38)
exports.__esModule @ handsontable.js:30180
__webpack_require__ @ handsontable.js:58
exports.__esModule @ handsontable.js:9083
__webpack_require__ @ handsontable.js:58
(anonymous) @ handsontable.js:25731
__webpack_require__ @ handsontable.js:58
exports.__esModule @ handsontable.js:101
(anonymous) @ handsontable.js:104
webpackUniversalModuleDefinition @ handsontable.js:31
map../af @ handsontable.js:38
__webpack_require__ @ bootstrap 46ffbdc17c59e870ff9f:19
(anonymous) @ polyfills.browser.ts:1
__webpack_require__ @ bootstrap 46ffbdc17c59e870ff9f:19
Object.defineProperty.value @ zh-tw.js:104
__webpack_require__ @ bootstrap 46ffbdc17c59e870ff9f:19
(anonymous) @ bootstrap 46ffbdc17c59e870ff9f:62
(anonymous) @ polyfills.bundle.js:67
main.browser.ts:40 Error: Angular requires Zone.js prolyfill.
    at new NgZone (core.es5.js:3773)
    at PlatformRef_._bootstrapModuleFactoryWithZone (core.es5.js:4492)
    at core.es5.js:4537
    at <anonymous>
```

**Comment by jornare** [comment]
BTW, we are using an angular-webpack-starter project from Angularclass. I see you also updated your webpack from 2.x to 3.x before building the new release. I am into if that may have caused any new issues. I  have now moved on from the previous error, but I'm struggling to get webpack to not include the polyfills twice.
I have also updated my webpack.common.js with
```
      new CommonsChunkPlugin({
        names: ['main', 'polyfills']
      }),
```

**Comment by jornare** [comment]
We have resolved the issue by importing angular-handsontable instead of handsontable in polyfills.js/ts

polyfills before:
```
import 'handsontable';
import 'zone.js';
```

polyfills now:
```
import 'angular-handsontable';
import 'zone.js';
```
-In addition to the CommonChunkPlugin configuration to resolve the dual Promise import.

**Comment by AMBudnik** [comment]
As the changes are already released please create a new ticket if there is anything that we have skipped or did not fix. Thanks in advance.

**Comment by alexandr2134** [comment]
import * as Handsontable from 'handsontable';
fixed this issues for me
