### ISSUE TITLE
Reorganization of settings connected with formatting numeric cells

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4497]
### Description
We should rename keys which are handled by [numbro](http://numbrojs.com). At now we have got `language` and `format` setting which are responsible for formatting numeric cells. These names aren't  the best for purpose of the work.

A proposition of new settings keys is shown below.

```js
...
{
  numericFormat: {
    pattern: '0,0.00 $',
    culture: 'de-DE'
  }
}
...
```

**Comment by wszymanski** [comment]
Should be changed yet:

- [ ] New Handsontable website with my.handsontable.com
- [ ] docs and docs-pro
- [ ] Demos (@AMBudnik) 
- [ ] Wrappers

**Comment by wszymanski** [comment]
Connected with introducing locale in Handsontable (#4457).

**Comment by krzysztofspilka** [comment]
Should be changed with release:

@wszymanski
- [ ] docs and docs-pro
- [ ] Examples / Features handsontable.com

@budnix
- [ ] New Handsontable website with my.handsontable.com
- [ ] hot-builder
- [ ] formula.js

@AMBudnik
- [ ] Demos
- [ ] Blog posts
- [ ] GitHub Wiki
- [ ] /demo in handsontable repository

@jansiegel
- [ ] Customers

@swistach
- [ ] typescript
- [ ] Wrappers

**Comment by wszymanski** [comment]
Was:

```
{
  format: '0,0.00 $',
  language: 'de-DE'
}
```

will be:

```
{
  numericFormat: {
    pattern: '0,0.00 $',
    culture: 'de-DE'
  }
}
```

Note: from now, `language` key will be used for changing a language of Handsontable's UI.

**Comment by wszymanski** [comment]
Merged to develop.
