### ISSUE TITLE
Scrolling creates empty space in Chrome on retina MacBook

### ISSUE THREAD

**Issue by yixunx** [handsontable/handsontable#4498]
### Description
Saw empty space while scrolling in Chrome on a retina MacBook. This is similar to https://github.com/handsontable/handsontable/issues/2350 and https://github.com/handsontable/handsontable/issues/4107. 

### Steps to reproduce
1. Go to https://docs.handsontable.com/0.34.0/demo-scrolling.html and try scrolling the example table.
2. The repro only works in Chrome with a retina screen. I did not hit the problem when using Firefox or when using Chrome with an external non-retina display. 

### Demo
![ezgif com-crop 5](https://user-images.githubusercontent.com/12816762/30076868-4ee88be2-9248-11e7-82e9-0bc426e853c2.gif)

### Your environment
* Handsontable version: 0.34.0
* Browser Name and version: Chrome 60.0.3112.113
* Operating System: MacOS Sierra 10.12.6

**Comment by AMBudnik** [comment]
Thak you for sharing @yixunx

**Comment by mohithg** [comment]
I can see the same behaviour in Chrome 61.0.3163.100 too.

**Comment by Luiz-N** [comment]
+1

**Comment by jamesckemp** [comment]
I'm seeing this too on Retina/Chrome Version 64.0.3282.186 - Any idea what causes it?

Note: I have a non retina screen too and if I drag the browser window over to it the scrolling issue disappears.

I note that the header and sidebar numbers lag too. They get to the right position milliseconds after you stop scrolling.

**Comment by AMBudnik** [comment]
Thank you for the feedback @jamesckemp 

we haven't solved the issue yet

**Comment by jamesckemp** [comment]
Do you think this could be a pixel calculation issue? I.e. 1px on retina = 2px? So scrolling gets ahead of itself.

**Comment by AMBudnik** [comment]
It can be a thing. We would need to check that

**Comment by jamesckemp** [comment]
I'm happy to look into it too if you know the function I should be looking at?

**Comment by AMBudnik** [comment]
The dimensions are calculated in the GhostTable class so I guess that's the place to look for answers

**Comment by AMBudnik** [comment]
Hi @yixunx @jamesckemp @Luiz-N @mohithg 

Thank you for your input. I hope that you'll find this fix useful.
