### ISSUE TITLE
Go to last cell with content - ctrl + arrow

### ISSUE THREAD

**Issue by ghost** [handsontable/handsontable#450]
I miss the feature to go to the last cell with content with ctrl + arrow just like Excel's End(xlDown/xlUp/...) function.

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
