### ISSUE TITLE
Zoomed out Chrome breaks the table's scrolling.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4502]
### Description
With Chrome zoomed out to 67% in some cases the table doesn't load additional rows and columns when scrolling.

### Steps to reproduce

1. Go to http://docs.handsontable.com/pro/1.13.1/demo-scrolling.html **on Chrome**
2. Zoom out the browser to `67%` (by pressing <kbd>ctrl/cmd</kbd> + <kbd>-</kbd> four times)
3. Refresh the page
4. Try scrolling the table.

### Your environment
* Browser Name and version: Chrome
* Operating System: OS X

**Comment by AMBudnik** [comment]
It may be related to the following issue https://github.com/handsontable/handsontable/issues/3399 there is also the magical `67%` and problems with loading data.

And here https://github.com/handsontable/handsontable/issues/3118 is a @dctucker reply about the ratios in the issue with the same base (zooming in and out). But here we get misaligned row headers for higher cells. Have you tried to change the cell height @jansiegel ?
