### ISSUE TITLE
afterChange behaves different between event hook and plugin

### ISSUE THREAD

**Issue by lab4quant** [handsontable/handsontable#4504]
### Description

I have  a custom plugin:

```js
   enablePlugin() {
     this.addHook('afterChange', (changes, source) => this.afterChange(changes, source));
     super.enablePlugin();
   }
```

If the cell is numeric, after double click, `afterChange` is triggered, `oldVal` and `newVal` in `changes` are different, with `oldVal` being the numeric value, and `newVal` being stringify value

If I disable the plugin and use event hook instead, both `oldVal` and `newVal` are stringify value.

```js
Handsontable.hooks.add('afterChange', function(changes, source) {
      if (source === 'edit' || source === 'undo' || source === 'autofill'){
        changes.forEach(function(item) {
          console.log('oldVal:'+item[2]+',newVal:'+item[3]);
        });
      }
});
```

This looks like a bug, as I need to check if `oldVal` and `newVal` is the same

### Steps to reproduce

1. double click a numeric cell
2. check browser console output
3.

### Demo

http://jsfiddle.net/b89yuobg/2/

### Your environment
* Handsontable version: 0.33.0
* Browser Name and version: chrome
* Operating System: windows 7

**Comment by AMBudnik** [comment]
Hi @lab4quant 

I am not sure how to replicate the issue.

The `afterChange` is fired when we close the editor. What have you found as an odd behavior/result?

**Comment by lab4quant** [comment]
@AMBudnik , sorry I don't know how to post my plugin code in jsfiddle, in the demo link there's only hook event code

the issue is that if afterChange is fired in plugin code, and data is numeric like in demo, the oldVal is numeric number while newVal is string value

and if you check the code in the demo, which is using hook event, both oldVal and newVal is string value

**Comment by AMBudnik** [comment]
Sorry for a delay @lab4quant 

are we able to replicate the issue using this demo http://jsfiddle.net/wnpsnh5j/?
