### ISSUE TITLE
numeric data rendered as text

### ISSUE THREAD

**Issue by lab4quant** [handsontable/handsontable#4505]
### Description

I passed numeric array of array as data to handsontable, the numbers are all rendered as text.
I checked numbericRender source code, if it's rendered as number, the cell is supposed to have class `htNumeric`

How would I let handsontable to know which cells are numeric which are text? thanks!

### Steps to reproduce

1. open demo link
2. open browser inspector, and navigate to any numeric cell
3. check TD class, it's empty

### Demo

http://jsfiddle.net/b89yuobg/2/

### Your environment
* Handsontable version: 0.33.0
* Browser Name and version: chrome
* Operating System: windows

**Comment by AMBudnik** [comment]
You have to specify the `type` of the cell. By default, all cells are the `text` type.

In your case, I would also [add a format](http://jsfiddle.net/handsoncode/3fgv9tkm/) as with this data all cells will become `1`.

**Comment by lab4quant** [comment]
@AMBudnik , thank you!

Is there anyway that I can specify type and format at cell level?

**Comment by AMBudnik** [comment]
Sure, you can use [`cells`](https://docs.handsontable.com/pro/1.13.0/Options.html#cells) method, like


```
cells: function (row, col, prop) {
  var cellProperties = {};

  if (row == 0 && col === 0) {
    cellProperties.type = 'numeric';
    cellProperties.format = '0.000';
  }

  return cellProperties;
},
```

**Comment by lab4quant** [comment]
@AMBudnik , thanks a lot!
