### ISSUE TITLE
Editing cell is too slow when renderAllRows: true

### ISSUE THREAD

**Issue by electrikaLaszlo** [handsontable/handsontable#4506]
### Description
I would like to use the option renderAllRows. I don't mind if the initial loading is slower but I want it fast after that point. Unfortunately, it is really slow when I edit a cell. Is there any option that I can turn in/off and makes it faster ? 

Thank you!

### Demo
1. Go to the page: http://jsfiddle.net/Lp4qn55v/834/
2. Edit any cell.

**Comment by AMBudnik** [comment]
Hi @electrikaLaszlo 

each change triggers the cell renderer, so if you close the editor again you have to wait till 10'000x100 cells get re-rendered. We do not recommend using `renderAllRows: true` with larger datasets.

Is there any particular reason why you want to use `renderAllRows`?

**Comment by electrikaLaszlo** [comment]
Hi AMBudnik,

Yes, the reason is the #4507 .

**Comment by AMBudnik** [comment]
Oh, I see. I saw the topic and marked as an issue. Have you tried using the `viewportRowRenderingOffset` option? Or just add a server-side pagination.

**Comment by electrikaLaszlo** [comment]
If the virtual rendering does not work viewportRowRenderingOffset does not work neither. I have put the handsontable into an angular directive to avoid using updateSettings and use the ngSwitch to render the related directive. It works until you have just 1-2 condition to choose the proper handsontable but I am pretty sure I can't do this so long. How long does it take to fix this problem ?

**Comment by AMBudnik** [comment]
It is really hard to say when it will be fixed. The issue has been reported today and none of the developers have checked it yet.
