### ISSUE TITLE
afterScrollHorizontally is triggered on vertical scroll action 

### ISSUE THREAD

**Issue by LuisCarlosBarahona** [handsontable/handsontable#4512]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/3gas9z6q/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Thank you for spotting that

Updated demo https://jsfiddle.net/rssp5a41/

**Comment by AMBudnik** [comment]
Hi @LuisCarlosBarahona 

again thanks for reporting. The issue is solved in version 0.35.0. Can you confirm that?

**Comment by swistach** [comment]
I am closing this issue as there are no other questions or concerns, but if someone has any, please leave a comment.
