### ISSUE TITLE
Comment box on fixed cell columns is not fixed

### ISSUE THREAD

**Issue by ryankennedyio** [handsontable/handsontable#4513]
### Description
When a column have been set as 'fixedColumnsLeft' and comments are enabled, the comment popup box position is mapped to where the column would be.

Visually, I expect this regardless of where my horizontal scrollbar is:
![image](https://user-images.githubusercontent.com/11158006/30362221-5dee3388-989e-11e7-9ead-6a287a9d61fd.png)

However, when I scroll to the right, I get:
![image](https://user-images.githubusercontent.com/11158006/30362258-8628c05c-989e-11e7-9e8b-499aae91963c.png)

### Steps to reproduce
1. Add a comment to one of the two fixed columns in the JSFiddle
2. Scroll to the right
3. Hover over the cell that was commented on.

### Demo

http://jsfiddle.net/0bc3k4oL/

### Your environment
* Handsontable version: 0.34.3
* Browser Name and version: Chrome 60.0.3112.113 
* Operating System: Windows 8

**Comment by AMBudnik** [comment]
Hi @ryankennedyio 

Thank you for sharing.

I think that this is exactly the same issue as this one https://github.com/handsontable/handsontable/issues/4389

Can you confirm?

**Comment by ryankennedyio** [comment]
Hi @AMBudnik  -- you are right, this looks exactly the same. I must have been searching for the wrong keywords, thanks for the link.

**Comment by AMBudnik** [comment]
That's OK. Thanks for your effort to report it in the first place.
