### ISSUE TITLE
( about freezing issue ) how to freeze from any row to any row rather than any row to top

### ISSUE THREAD

**Issue by yang123guo** [handsontable/handsontable#4515]
### Description

happens: 
     In you doc there is an option  named "fixedRowsTop" , which can fix the choosen row to the first/top row, but I have many rows,  before freeze the row I should scroll , then fixed the choosen row. For example I just freeze row 15th to row 20th

### Steps to reproduce

1. scroll and find  row 21th
2. freeze 
3.we can see row 15th and 20th in the table ,1th -- 14th is hidden.  How do I realize it.

### Demo

![freeze](https://user-images.githubusercontent.com/17383237/30370896-81aa26f8-98ab-11e7-95ea-f9d983e270fa.png)

### Your environment
* V-0.26.1 
* chorme 58+
* win10

**Comment by AMBudnik** [comment]
Hi @yang123guo 

please share a demo where this issue can be replicable.

**Comment by yang123guo** [comment]
Hi @AMBudnik ;
   Thanks for your reply. I donot hava a demo, but have you ever used Microsoft Excel ?  In Excel, you can scroll to any row then do freeze.
![animation](https://user-images.githubusercontent.com/17383237/30417200-8388c856-9961-11e7-965f-08e955c36c8e.gif)

**Comment by yang123guo** [comment]
In the gif , we can see 13th -- 18th row is fixed rather than 1th -- 18th row.  So is there an API 
 like  (fixedRowsTop:  Number)  
 fixedFromRowsToRows(Number1 , Number2)
 fixedFromColumnToColumn(Number1 , Number2)

**Comment by AMBudnik** [comment]
I can see what you mean @yang123guo 
You would like to have a one click option (button or menu) to freeze a range of rows. Am I right?

**Comment by yang123guo** [comment]
Yes!! that was my purpose! not only rows but also column.  And the range of rows/column fiexd the top/left. Less than it is invisible。 
how can I realize it?

**Comment by AMBudnik** [comment]
I did not test it entirely but something like this should work http://jsfiddle.net/kj5p29cs/

ps. we can only select adjacent rows/columns so it will always fix row and columns starting from index `0`. This unfortunately, cannot be skipped

**Comment by yang123guo** [comment]
I have got your demo, but I think there is a problem.you know , If your screen can only display 30 rows,  your scroll to 40th row and then  `updateSettings({fixedRowsTop: 40})`,  unfortunately, the height of the range of  40 rows cause you can't see the below（Is there a bug?）

**Comment by AMBudnik** [comment]
Yes, @yang123guo it is a bug. It has been reported at https://github.com/handsontable/handsontable/issues/4259

**Comment by yang123guo** [comment]
Thank you for your contribution！！

**Comment by AMBudnik** [comment]
You're welcome @yang123guo 

have a great day
