### ISSUE TITLE
how to add event on click and count all rows 

### ISSUE THREAD

**Issue by hecate021196** [handsontable/handsontable#4516]
i want to know how much line in my table and show it with alert, but it didnt work.
this is my script
`<script data-jsfiddle="example">
              var
              data = [
                ['No', 'Jenis Kegiatan', 'Volume', 'Satuan', 'Harga', 'Jumlah'],

              ],
              container = document.getElementById('example'),
              hot;

              hot = new Handsontable(container, {
                data: data,
                rowHeaders: true,
                colHeaders: true,
                contextMenu: true,
                manualColumnResize: true,
                manualRowResize: true,
                fixedRowsTop: 1,
                minSpareRows:20
              });
            
              Handsontable.dom.addEvent(save, 'click', function() {
                  alert($('#example').handsontable('countRows'));
                });
              </script>`

**Comment by AMBudnik** [comment]
Hi @hecate021196 

here is a working demo http://jsfiddle.net/77e3w475/

**Comment by hecate021196** [comment]
@AMBudnik  ty very much

**Comment by Arawipacha** [comment]
Si lo haces en angular puedes provar a usar esto

htmlButton=(instance, td, row, col, prop, value, cellProperties) =>{
      var escaped = Handsontable.helper.stringify(value),
      button;

      button = document.createElement('BUTTON');
      button.setAttribute("name","Edit");
      
      //button.onclick = this.edit(value);
      button.value=value;
      let call:any=(e) => {       
        this.edit(e.target.value);
      }

      Handsontable.dom.addEvent(button, 'click',  call);
      

      Handsontable.dom.empty(td);
      td.appendChild(button);
      return td;
    }


columns

{ data:'documento_id',  title: 'documento_id',   width:80 ,renderer: this.htmlButton},
