### ISSUE TITLE
Get Original Source from Column

### ISSUE THREAD

**Issue by wesleywong** [handsontable/handsontable#4517]
I was looking at the docs to find solution to get the original source data from **COLUMN**. I can able to get the original source from **ROW** by getSourceDataAtRow(row), this will return the original row data including hidden fields. I noticed similar function called "getSourceDataAtCol(col)", but this only return value instead of source column. Please advise.

```
var data = [
	{
		"id": {
			"value": "1",
			"is_valid": true
		},
		"name": {
			"value": "name",
			"is_valid": true
		},
		"address": {
			"value": "address",
			"is_valid": false
		}
	},
	{
		"id": {
			"value": "2",
			"is_valid": true
		},
		"name": {
			"value": "Frank Honest",
			"is_valid": true
		},
		"address": {
			"value": "address",
			"is_valid": false
		}
	},
	{
		"id": {
			"value": "3",
			"is_valid": true
		},
		"name": {
			"value": "Joan Well",
			"is_valid": false
		},
		"address": {
			"value": "address",
			"is_valid": false
		}
	}
];
```
I used key "is_valid" to formatting in cell, but couldn't find a good solution to get a return from 

```
cells: function (row, col, prop) {
 //need to get col's original source data in order to get hidden field "is_valid"
}
```

### environment
* Version: 1.14.1

**Comment by AMBudnik** [comment]
Hi @wesleywong 

Here is an example of what we are talking about http://jsfiddle.net/ckdb9p1b/

At line `44` I am calling `hot.getSourceDataAtRow(0)` and get

`{car: "Mercedes A 160", year: 2017, price_usd: 7000, price_eur: 7000}`

and at line `45` I am doing the same operation for columns `hot.getSourceDataAtCol(0)` and get

`[2017, 2018, 2019, 2020, 2021]`

The `getSourceDataAtCol` returns an array of values as they all share the same `key`.

Can you give me an example of what you would like to get in a result?

**Comment by wesleywong** [comment]
Hi @AMBudnik 

Please see this example [http://jsfiddle.net/wesleywong/rn4zs5a9/4/]

-> hot.getSourceDataAtRow(0)
`{"id":{"value":"1","is_valid":true},"name":{"value":"Mario","is_valid":true},"address":{"value":"address 3","is_valid":false}}`

_this is good. which i can get original row data that no display in view_

-> hot.getSourceDataAtCol(0)
`["1","2","3"]`

_i expected result below_
`{"value":"1","is_valid":true}`

Please advise how can achieved this.

**Comment by AMBudnik** [comment]
I think that this method wasn't made for this case.

Here is an updated demo http://jsfiddle.net/1LgLqv49/

and as you mentioned

> -> hot.getSourceDataAtCol(0)
> ["1","2","3"]

cause we get what we have in the first column

![image](https://user-images.githubusercontent.com/10757813/30422243-a9faaf62-993f-11e7-95df-b27586fd21ca.png)

What you are actually looking for is the full object under a certain index in your `data` object [(`data[0].id`)](http://jsfiddle.net/psdobe7v/)

**Comment by wesleywong** [comment]
how about getSourceDataAtCell(0, 0) ? currently this only getting the value from cell not the source. it should be same as getSourceDataAtRow(0) to getting "source" not value.

**Comment by wesleywong** [comment]
i need those extra data (hidden in table) to do some filtering work in "cells" function

```
hot = new Handsontable(container, {
    data: getUserData(),
    colHeaders: ["ID","Name","Address"],
    columns:[{"data":"id.value"},{"data":"name.value"},{"data":"address.value"}],
    columnSorting: true,
    manualColumnMove: true,
    cells: function (row, col, prop) {
    	//need to do some styling if !is_valid 
    }
  });
```

**Comment by AMBudnik** [comment]
With your `columns` structure, it looks like this should work http://jsfiddle.net/dsww208e/

**Comment by wesleywong** [comment]
@AMBudnik thanks for the quick response. appreciated. 

I understand i can do this way with hardcoded key. but in my system all the keys is randomly output. unless i can get the return "key" in cells or any other function. 

`data[row][xxx].is_valid`

**Comment by AMBudnik** [comment]
I truly understand that but it looks like it's an only option right now. There is one thing that was on my mind (adding a custom class or metadata via `setCellMeta`) but I am not sure if that will meet your project requirements.

**Comment by wesleywong** [comment]
any sample for setCellMeta? Not sure how to use this to fulfil my project requirement.

**Comment by AMBudnik** [comment]
Hi @wesleywong 

Sure. Here is a working demo http://jsfiddle.net/2je1wmzw/
I have added comes to the code. 

Let me know if you'd need anything else.
