### ISSUE TITLE
Mouse scroll not working in Firefox when heigh is not set

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#4518]
### Description
I can't scroll a large table in Firefox when height is not set. I like that the table stretches to fill the window when no height/width is set and would like to keep it like this if possible.

### Demo
Using Firefox: https://jsfiddle.net/2ts3cchb/

### Your environment
* Handsontable version: 0.34.3
* Browser Name and version: Firefox 55/57
* Operating System: MacOS Sierra

**Comment by AMBudnik** [comment]
Thank you for sharing @ottosson 

I have replicated it in FF 55 / Win 10. It works fine on Chrome 61

**Comment by NiLSPACE** [comment]
This still is a problem in Firefox 58 and I could also replicate it in Internet Explorer and Microsoft Edge.

**Comment by swistach** [comment]
Hi @ottosson, @NiLSPACE 
You can scroll this element since v.0.38.0: https://jsfiddle.net/q951fsdg/
I know, the table is flickering but is scrollable.
