### ISSUE TITLE
Providing custom cell stuff

### ISSUE THREAD

**Issue by Morgenhund** [handsontable/handsontable#452]
Hello, I'm trying to realize a cell editor consisting of, say, two input fields:

```javascript
var blueRenderer = function (instance, td, row, col, prop, value, cellProperties) {
            td.innerHTML = '<input type="checkbox"><input><br /><input>';
}
<here comes data variable definition>
$container.handsontable({
            data: data,
            columns: [
              { data: 1 },
              { data: 3, type: {renderer: blueRenderer}, readOnly: true },
            ]
          });
```
However, I cannot set focus to either of these two input boxes (independent of 'readOnly' column setting). Is that doible, at all?

I need this feature to provide a "multi-dimensional" row behaviour (when each row has to have some "sub-values" input fields that I want to provide "on demand" whan a cell-checkbox is checked.)

Thank you in advance!

**Comment by AMBudnik** [comment]
If you would have any other questions, feel free to open a new issue.
