### ISSUE TITLE
A column is not rendered if the top cell is empty

### ISSUE THREAD

**Issue by alarm9k** [handsontable/handsontable#4520]
### Description
Only the columns with non-empty top cells are rendered.

### Steps to reproduce
1. Use the data where some of the top cells (B1, D1, E1 etc) are empty.
2. Columns with non-empty top cells are displayed. 
3. Columns with empty top cells are _not_ displayed.

### Demo
Not displayed:
https://drive.google.com/file/d/0B3HznrSgcbg4SnBiTjFxWXprb0k/view?usp=sharing

Displayed (note that the top cells are filled this time):
https://drive.google.com/open?id=0B3HznrSgcbg4TjdCQUJoMzRMMFU

### Your environment
* Handsontable version: 0.34.4
* Browser Name and version: Chrome 60.0.3112.113
* Operating System: Fedora 25

**Comment by AMBudnik** [comment]
Hi @alarm9k 

unfortunately, it is a known bug. To make it work you can use the `columns` attribute to show all columns.

**Comment by alarm9k** [comment]
Okay thanks, was able to circumvent the issue by
```
hot.updateSettings({
      columns: Array(longestRow)
});
```
