### ISSUE TITLE
Column Freeze with wordWrap issue

### ISSUE THREAD

**Issue by yuwong** [handsontable/handsontable#4522]
### Steps to reproduce
1. Go to [JSFiddle](http://jsfiddle.net/47mzcsdx) (based on the Freezing columns demo from 1.14.2 doc)
2. Enter "Testing word wrap with freeze columns" in A4, B7 and D3
3. Scroll all the way to column Z

Please note the misalignments.

**Comment by AMBudnik** [comment]
Hi @yuwong 

if you have more columns that the viewport is loading you can use the `autoRowSize` plugin to keep the heights equal after scrolling. Here is an updated demo http://jsfiddle.net/k3m02y13/

**Comment by yuwong** [comment]
Thanks @AMBudnik, I guess it's either increase the `viewportColumnRenderingOffset` or use the plugin
