### ISSUE TITLE
Copy Paste not working with electron in MAC

### ISSUE THREAD

**Issue by sumanparia** [handsontable/handsontable#4523]
### Description
Copy paste not working using electron only in MAC.

### Your environment
* Handsontable version: latest
* Browser Name and version: Electron
* Operating System: OSX

**Comment by AMBudnik** [comment]
Hi @sumanparia 

Can you share more details about your environment? I haven't heard about Electron browser.

**Comment by sumanparia** [comment]
Sorry my bad. It is a electron issue. Solution is here https://github.com/sumanparia/electron-handsontable
