### ISSUE TITLE
Make allowEmpty work with `text` type

### ISSUE THREAD

**Issue by wesleywong** [handsontable/handsontable#4524]
allowEmpty: false 
No problem in "dropdown", library will prevent value to be empty but this doesn't work in "text". Please advise.

```
[
  {
    "data": "id.value",
    "allowInvalid": false,
    "allowEmpty": false
  },
  {
    "data": "name.value",
    "allowInvalid": false,
    "allowEmpty": false
  },
  {
    "data": "condition.value",
    "allowInvalid": false,
    "allowEmpty": false
  },
  {
    "data": "address.value",
    "allowInvalid": false,
    "allowEmpty": false
  }
]
```

Version: 1.14.1

**Comment by AMBudnik** [comment]
Hi @wesleywong 

the option works only if a cell has a validator. Text cell type doesn't have one. You would need to add additional logic that checks if a cell is empty.

**Comment by koolmoo** [comment]
Hi,

I've come across the same issue with cell types that do have default validators. It seems that most of the default validators are not checking whether `allowEmpty = false` and `value === ""`. This results in empty values being valid for all cell types except numeric when allowEmpty is set to false.

I understand we can add our own custom validators, but it doesn't make sense for some of the defaults to ignore this setting and some to follow it. Perhaps they could all perform the following check before doing any further validation:

```
if (value === '' || value == null) {
  callback(this.allowEmpty);

  return;
}
```

Please let me know what you think. I can post a separate issue if needed. Thanks!

**Comment by AMBudnik** [comment]
Hi @koolmoo 

we decided that in default an empty string should be valid for all cell types. That is why the `allowEmpty: false` has been added as a separate setting.

**Comment by koolmoo** [comment]
Hi @AMBudnik 

I'm not sure I understand fully. Currently, the allowEmpty flag defaults to true, which means by default empty values are valid for all cell types.

What I am wondering is why setting it to false does not have a consistent behavior between the cell types. It works on numeric and date/time cells but not on normal or dropdown/autocomplete cells. Also, in the documentation for allowEmpty it states:

> If set to false, Handsontable will not accept the empty values and mark cell as invalid.

I understand if it's not a high priority, but I do believe either the behavior should be made consistent, or the documentation should be updated to accurately reflect the behavior. Thanks.

**Comment by aaronbeall** [comment]
I ran into this and was a bit confused as well. I think @koolmoo makes a good point, even though `text` doesn't have a validator it doesn't make sense that `allowEmpty: false` doesn't do anything with text cells. Perhaps `text` needs a default validator that just considered `allowEmpty`.

**Comment by AMBudnik** [comment]
Agree @aaronbeall 

opened the issue and changed a title
