### ISSUE TITLE
manualRowMove doesn't work with new data

### ISSUE THREAD

**Issue by lulezi** [handsontable/handsontable#4525]
### Description
The `manualRowMove: true` setting works fine after the initial rendering. However, after adding more data and rerendering the hot instance, moving rows manually glitches.

### Steps to reproduce
1. Render table with some data and set `manualRowMove: true`
2. Add some more data
3. Rerender
4. Move the newly added data rows around

### Demo
http://jsbin.com/cuxupagake/edit?html,js,output

### Your environment
* Handsontable version: 0.34.4
* Browser Name and version: Chrome 60.0.3150.1
* Operating System: macOS Sierra (10.12.6)

**Comment by AMBudnik** [comment]
Hi @lulezi 

Please use the `alter` method to add rows http://jsfiddle.net/0ydms0z0/

**Comment by lulezi** [comment]
Thanks for your quick answer @AMBudnik . We are using ngHandsontable and the data is given to handsontable via the `datarows`-binding. What is the correct way with ngHandsontable to insert/remove rows?

**Comment by lulezi** [comment]
http://jsfiddle.net/od9e3t5p/2/

**Comment by AMBudnik** [comment]
I have to say that I am not an expert in AngularJS but I have been provided with a demo some time ago that may come in handy http://jsbin.com/defamibuha/edit?html,js,output

**Comment by lulezi** [comment]
Awesome, thank you!
