### ISSUE TITLE
Passive Event Listeners

### ISSUE THREAD

**Issue by nadim** [handsontable/handsontable#4526]
Hi,

We are wondering if there are any plans to implement passive event listeners:
https://developers.google.com/web/updates/2016/06/passive-event-listeners

Recently we enabled this globally and while there are some bugs with this, the handsontable scroll performance shows a noticeable improvement.

**Comment by AMBudnik** [comment]
Hi @nadim 

thank you for sharing. 

Actually, I have a good news. We have tested the solution a few days ago and you're right it is a great approach to boost the scrolling performance. We are preparing to create a working example.

**Comment by MobileAppVault** [comment]
Hi @AMBudnik 

could you please tell me the status about this enhancement?
Many Thanks!

**Comment by AMBudnik** [comment]
It's hard to tell as the person behind the project is currently on the vacation but I hope that we will be able to start the work in October.

**Comment by MobileAppVault** [comment]
thanks for the update. Appreciate it!

**Comment by jtrees** [comment]
Any news on this?

**Comment by AMBudnik** [comment]
Sorry. Our Roadmap is changing very rapidly. [Here is a link to our ZenHub board.](https://app.zenhub.com/workspace/o/handsontable/handsontable/boards?repos=1790564,85198294) You'll find there anything that we are working now.

**Comment by wojciechczerniak** [comment]
While we were fixing #5904 we took it a little bit further and added support for passive event listeners  in https://github.com/handsontable/handsontable/commit/927707cc7e45939f1fcee841d3b8548e7d5fd3d4. Will be released in v7.0.1

**Comment by AMBudnik** [comment]
Hey @nadim @MobileAppVault @jtrees I'm happy to announce that we've just released Handsontable v`7.0.0` where we've made the change.
