### ISSUE TITLE
Programatically copy data to clipboard

### ISSUE THREAD

**Issue by nadim** [handsontable/handsontable#4527]
I saw this addressed in another thread but not exactly what we are looking for.

I have a button and when the user clicks it, I execute the following code:
```  
processCopyClick () {
    ...
      const copyPastePlugin = hotInstance.getPlugin('CopyPaste')
      copyPastePlugin.copy(true);
    }
  }
```
I have tried variations of the argument to copy(). I have also looked at setCopyable(). No luck with either of these.

I have two questions:
1. Is it possible to programatically copy?
2. How?

**Comment by AMBudnik** [comment]
Hi @nadim 

you would like to copy the values that are in the selected area/ a single cell or a whole grid? I guess that it might be easier to pass the data via `getData`/`getDataAtCell` to the clipboard.

**Comment by nadim** [comment]
I'd like to copy both selected cells and the whole grid, using a separate button for each. Would it be possible for you to provide a code sample? This is what I was trying to accomplish in the code I shared above, but it isn't copying anything.

**Comment by AMBudnik** [comment]
If you would like to have an array of arrays, as a result, you can use the following code http://jsfiddle.net/jo6fn42t/

and here's a little bit more about passing a variable to the clipboard https://stackoverflow.com/questions/33855641/copy-output-of-javascript-variable-to-clipboard

**Comment by nadim** [comment]
I can look into these. So you are suggesting that I don't use the CopyPaste plugin that is built into handsontable?

**Comment by darkmavis1980** [comment]
I have the same issue, I was using the hotInstance.copyPaste methods and they worked fine (ish) until version 1.9.1, but now after refactoring the code to use the `getPlugin` to get the `copyPaste` plugin, it works only the cut, but no way to have the paste working.
Is that plugin working at all?

**Comment by darkmavis1980** [comment]
I also found a bit confusing the fact that [here](https://docs.handsontable.com/pro/1.14.2/demo-copy-paste.html) it states to use the **SheetClip** library, which btw has no support for legacy bower or npm, and last update was more than 2 years ago, and if I include that my code just break.
Why copy/paste is so messed up in handsontable?

**Comment by darkmavis1980** [comment]
So I did some more digging, and apparently the cut does work and the `afterCut` method receives the data, but when I trigger the CopyPaste `paste` or `triggerPaste` methods, the `afterPaste` does nothing, so I feel like those methods are doing nothing at the moment.

**Comment by nadim** [comment]
It would be nice if there was an official answer from Handsontable on this. Is it recommended to use the plugin (and if so, what is the expected browser compatibility)? Or should I be finding my own way of implementing copy (of the currently selected rows as well as the entire table).

+Nadim

**Comment by AMBudnik** [comment]
Hi @nadim @darkmavis1980 
The only thing I can say now is that we have decided to disconnect ZeroClipboard as it is using flash. I guess that @swistach will be able to tell you more about the plugin as he has made the last changes to it. He'll be back on Monday.

**Comment by swistach** [comment]
Hi @nadim @darkmavis1980,
we have here a few issues:
1. How to use plugin API: http://jsfiddle.net/jo6fn42t/1/
2. How to paste data from system clipboard: CTRL+V or custom extension (Chrome, Firefox)
3. SheetClip - @warpech built it, because that was a requirement to parse / encode array to CSV-like format.

**Comment by nadim** [comment]
Thank you @swistach #1 is what I was looking for.
