### ISSUE TITLE
CallCheck Error

### ISSUE THREAD

**Issue by gupinheiro** [handsontable/handsontable#4528]
Hi,

We are trying to update our application developed in HandsonTable version 0.24.3 to 0.34.4 and occurs the following error "TypeError: Cannot call a class as a function" triggered on "function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }"  at file handsontable.full. Could you help us to solve this?

**Comment by AMBudnik** [comment]
Hi @gupinheiro 

Unfortunately, the following error doesn't tell me much.

There is a huge gap between the versions with a few backward incompatible changes. Please take a look at https://docs.handsontable.com/0.34.4/tutorial-release-notes.html and try to update the library to the first breaking change version. And if that will work move the versions one by one until you'll get the error again.

You can also try to comment some parts of the code and check which part causes the issue.

**Comment by AMBudnik** [comment]
I am sure that this process can take a while so I am closing the issue but feel free to contact me as soon as you'll get any new thoughts or encounter issues
