### ISSUE TITLE
Custom renderers - selectpicker

### ISSUE THREAD

**Issue by wesleywong** [handsontable/handsontable#4530]
currently tried to implemented selectpicker in column by using custom renderers instead of default type as "dropdown", is there a example for triggering afterChange method when select/change value from selectpicker.

```
function customRender(instance, td, row, col, prop, value, cellProperties){
	var opt = ["1","2","3"];
	var html = "<select class='selectpicker form-control' data-container='body'>";
	for(var i=0, len=opt.length; i<len; i++){
		html += "<option value='"+opt[i]+"'>"+opt[i]+"</option>";
	}
	html += "</select>";
	$(td).html(html);
}
```

**Comment by AMBudnik** [comment]
Hi @wesleywong 

the select cell type triggers `afterChange` hook after the value is accepted - so not after picking anything from the list of options but after clicking outside the cell (when arrows disappear). You can test it at http://jsfiddle.net/w6msy67t/

**Comment by wesleywong** [comment]
Hi @AMBudnik 

Thanks for the reply. the reason i need to use custom renderers is because current default type "select" or "dropdown" doesn't support selection dropdown stick to body, the existing dropdown selection will hidden https://github.com/handsontable/handsontable/issues/3432

![screen shot 2017-09-21 at 3 53 47 pm](https://user-images.githubusercontent.com/3807686/30690564-38da5dba-9ef7-11e7-8ccb-a80ba4ed1021.png)


Hope thats a way can use custom renderers to triggers `afterChange`

**Comment by AMBudnik** [comment]
Oh my. That doesn't look as expected. HAve you tried @jerradpatch solution from https://github.com/handsontable/handsontable/issues/3432?

**Comment by wesleywong** [comment]
I commented in that issue. Actually this is known bug as I browse thru the all issues. As long as table set the fix height or set preventOverflow: 'horizontal  . If your drop down is higher than table, it will become like that, even worst that in the event that you only have 3 rows then middle row unable to see the drop down menu at all.

**Comment by AMBudnik** [comment]
Thank you for sharing your concerns. I have reopened the https://github.com/handsontable/handsontable/issues/3432
Please share all your investigate results there as we will be able to address all users in the same time about future fixes.
