### ISSUE TITLE
Jumping to the start of the next row when a row is completed

### ISSUE THREAD

**Issue by RubbelDieKatz** [handsontable/handsontable#4531]
### Demo
[Here's a JSFiddle with my code.][2]

I'm using Handsontable in order to allow people to input data. I want them to either use tab or enter when they are done with a cell, hitting these keys whenever they are done filling a cell.

When a row is completed, they would obviously use enter too, kind of like a typewriter. However, they don't jump to the first cell in the next row.

I can configure this with the `enterMoves` option:

        minSpareCols: 0,
        minSpareRows: 1,
        enterMoves: {row: 0, col: 1}

According to one person on GitHub, [this feature should be in the main code][1]:

> I implemented your suggestion into core :) Please use the following
> set of params and let me know what you think:
> 
> 
>
>     minSpareCols: 0, 
>     enterMoves: {row: 0, col: 1}

I filled a row with data and pressing enter does nothing.

[![handsontable image][3]][3]

Is there any way to enable this feature?

-------------------------------------

I've copypasted this from [my Stackoverflow question](https://stackoverflow.com/q/46339456/6203984). Maybe some of you can help me with this.

* Handsontable version: 0.34.4  
* Browser Name and version: Chrome 55.0.2883.87 m
* Operating System: Windows 7 Professional

  [1]: https://github.com/handsontable/handsontable/issues/68
  [2]: http://jsfiddle.net/s6t768pq/971/
  [3]: https://i.stack.imgur.com/sf44Y.png

**Comment by AMBudnik** [comment]
Hi @RubbelDieKatz 

I just saw your comment at #68 has been moved here so I am also moving my comment :)

`enterMoves` can be a functions as well, so you can determine how to move when selection reaches the last column.

Here is a demo http://jsfiddle.net/qtfam5v1/ where I move the selection one column right and after we reach the last column we pick the first cell in the next row.

**Comment by RubbelDieKatz** [comment]
Thanks a lot, @AMBudnik! Yeah, I moved it, since I thought it would fit to make a new post about it.
