### ISSUE TITLE
Copy pasting cells into one cell then copying that cell and pasting to another cell creates not expected behavior

### ISSUE THREAD

**Issue by superfille** [handsontable/handsontable#4533]
When copying two cells in a row and pasting them into another cell by double clicking that cell (ie, writing in the cells textarea). And then copying that cell and pasting it normally (not double clicking) on another cell, will overwrite the cell to the right with data from the second cell from the first copy.
A bit confusing.

Use the fiddle with the steps below to see the behavior
http://jsfiddle.net/fze7gbkw/1/

1. Copy R1C1 and R1C2 by selecting them with the mouse and copying with CTRL+C

2. Paste to R2C1 by double clicking on the cell and then pasting at the end. Paste with CTRL+V
Result: R2C1R1C1(tab)R1C2

3. Select the cell (don't double click) you just pasted to and copy it with CTRL+C

4. Paste to R3C1 by selecting it (not double clicking)
Result: R3C1 will become: R2C1R1C1 AND R3C2 will become R1C2
This is not the behavior I would expect.
Should be: R2C1R1C1 R1C2 in R3C1

### Your environment
* Handsontable version:  Dunno, the fiddle was taken from your first example https://handsontable.com/examples.html?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers
I've just modified it to remove the flags etc
* Browser Name and version: Chrome 58.0.3029.96 
* Operating System: Windows

**Comment by AMBudnik** [comment]
Thank you for sharing your concerns @superfille 

I will discuss the subject with our developer who has made the last changes to the copy-paste plugin and be back after the weekend with updates.

**Comment by swistach** [comment]
Hi @superfille,
It is the same problem as here: #4308
