### ISSUE TITLE
Addition of maxCols and maxRows attributes

### ISSUE THREAD

**Issue by deenairn** [handsontable/handsontable#4537]
### Description
Occasionally there are scenarios where you do not want the size of the HoT grid to grow when copy and pasting data into it. Currently this is handled by using events and stripping out the unwanted changes. I feel it would be desirable to have a parameters that specify the maximum number of rows and columns as a part of the HoT settings. The same could be said for the minimum number of rows and columns.

### Steps to reproduce
N/A - Feature Request

### Demo
N/A - Feature Request

### Your environment
N/A - Feature Request

**Comment by AMBudnik** [comment]
Hi @deenairn 

Actually, we have [`maxRows` ](https://docs.handsontable.com/pro/1.14.2/Options.html#maxRows )and [`maxCols`](https://docs.handsontable.com/pro/1.14.2/Options.html#maxCols) working like that. Here is a working example http://jsfiddle.net/28eqxuvp/

In the example the array is `[5, 5]` and we define to get max `[6, 6]` cells. 

![gif](https://user-images.githubusercontent.com/10757813/30956644-428d27c0-a438-11e7-9408-d3540980ecd8.gif)

As you can see above no matter how I copy I still get a `[6, 6]` array.

**Comment by deenairn** [comment]
Thanks - obviously had managed to overlook this. Is it from a specific version of HoT?

**Comment by AMBudnik** [comment]
It has been for a long time but till v1.11.0 there were some issues related
