### ISSUE TITLE
No minHeight plus fixedRowsBottom creates row duplication

### ISSUE THREAD

**Issue by tgmweb** [handsontable/handsontable#4539]
### Description
Because there is no way to use a maxHeight on the table you have to have a fixed height. If you're using fixedRowsBottom and if there aren't enough rows in your table to create a table as tall as your fixed height, you get row duplication at the bottom of the table, and at the bottom of the container.

### Steps to reproduce
1. Create a table with a fixed height of 500;
2. Add fixedRowsBottom:1
3. Add 3 rows to your table.
4. You'll get a duplicate of the last row - once in the correct place, the second at 500 pixels.

Ideally, a way to adjust the height of the table on afterRender(), or to remove the fixedRows if the height of the table isn't 500 pixels.

I can't see a way of doing either of these things...

**Comment by AMBudnik** [comment]
Hi @tgmweb 

thank you very much for sharing, but I guess that we already had this reported at https://github.com/handsontable/handsontable/issues/4454

Can you confirm?

**Comment by tgmweb** [comment]
Yep, sorry didn't see that ticket and the workaround has worked for me.

Thanks!
