### ISSUE TITLE
Example for getting data on selected row.

### ISSUE THREAD

**Issue by carlskii** [handsontable/handsontable#4540]
### Description
Please could you provide a simple example for selecting the data (cell values) from a row. I'm in the process of evaluating the pro version and will need to be able to do this. The docs don't seem to be that clear and are the examples for adding hooks seems to be somewhat overwhelming.

**Comment by AMBudnik** [comment]
Hi @carlskii 

sure, no problem.

the [`getSelected`](https://docs.handsontable.com/pro/1.14.2/Core.html#getSelected) method returns a range of selected cells (coordinates). You can also use the selection callback - the [`afterSelectionEnd`](https://docs.handsontable.com/pro/1.14.2/Hooks.html#event:afterSelectionEnd) if you wish to get the data as soon as the user selects a new range of rows.

If you wish to get data from whole rows, you can use the [`getDataAtRow`](https://docs.handsontable.com/pro/1.14.2/Core.html#getDataAtRow)method.

Here's how we can use it http://jsfiddle.net/cjkz8jne/

**Comment by carlskii** [comment]
Very nice - and thanks for the example.

**Comment by carlskii** [comment]
One more thing here. Is it possible to disable firing the event if a column is selected? I only need the rows.

**Comment by AMBudnik** [comment]
Hi @carlskii 

we do not have any 'before selection events'. However, you can add the `IF` statement to exclude unwanted scenarios line

`c !== c2` - run the code if user selected more than one column
`!(r === 0 && r2 === (hot.countRows() - 1))` - if user did not clicked the header

**Comment by carlskii** [comment]
Thanks for this - any chance you can add it to the fiddle. I'm having trouble getting this to work.

**Comment by AMBudnik** [comment]
Sure, just let me know exactly when you do not want the data to be printed.

**Comment by carlskii** [comment]
So currently if the column header is selected it grabs all of the column data that really slows (blocks)  my electron app until its finished. Basically, I just want to grab the data for the selected row only when the first cell in the row is clicked on.

**Comment by AMBudnik** [comment]
In this demo http://jsfiddle.net/sa1bywpg/

I have blocked to data to be shown when a user clicks the column header and added the exception to log it only when a selected cell is the first one in the row.

**Comment by carlskii** [comment]
Perfect - exactly what I need. Thank you.

**Comment by AMBudnik** [comment]
You're welcome @carlskii
