### ISSUE TITLE
CheckBox and HandsonTable

### ISSUE THREAD

**Issue by Sam184** [handsontable/handsontable#4541]
I have a checkbox that is outside of my Handsontable. My Handsontable is populated through ajax. I want to hide and show Handsontable columns based on the value of checkbox. This is how my code looks like

  Handsontable.dom.addEvent(mycheckbox, 'change', function () {
            var hot = $container.data('handsontable');
            if (mycheckbox.checked) {
                hot.updateSettings({
                    hiddenColumns: {
                        columns: [0],
                        indicators: true
                    }
                })
            }
            else {
                hot.updateSettings({
                    hiddenColumns: {
                        columns: [0,1,2],
                        indicators: true
                    }
                })
            }
        });
This code only executes when you check or uncheck the checkbox and it works fine, but I want to use this code on the page load event also, or when the Handsontable loads.

**Comment by AMBudnik** [comment]
Please follow the topic at https://forum.handsontable.com/t/show-hide-handsontable-columns-based-on-a-value/1435/8
