### ISSUE TITLE
Highlighting rows within electron app.

### ISSUE THREAD

**Issue by carlskii** [handsontable/handsontable#4542]
### Description
Hi I'm trying to run this example within an electron app, however the column highlighting is not working. 

https://docs.handsontable.com/0.20.3/demo-highlighting-selection.html

Is there any reason why this might happen? 

Regards,

Carl

**Comment by AMBudnik** [comment]
Hi @carlskii 

have you used the latest version? The one from the demo is 0.20.3.

In the example we are using two new classes
```
currentRowClassName: 'currentRow',
currentColClassName: 'currentCol',
```

have them been properly added and included in the code? If so, you can check the Developer tools if the class is not being overwtitten by any other .css settings.
