### ISSUE TITLE
Add onCellMouseMove hook

### ISSUE THREAD

**Issue by williamboman** [handsontable/handsontable#4547]
I'd like to know when the mouse pointer is moved within a cell.

The use case is: when a user hovers a cell I initiate a timeout on 1s that, when invoked, will highlight the cell. However, I want to cancel this timeout if the user moves the mouse - I want to require the mouse to be *completely* still for 1s in order to highlight the cell.

**Comment by AMBudnik** [comment]
Thank you for the suggestion.

**Comment by AMBudnik** [comment]
The issue has been redirected to the[ Wiki section / feature requests](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.

**Comment by AMBudnik** [comment]
We can call this feature added.
We have all the states of the mouse events

- afterOnCellCornerMouseDown
- afterOnCellMouseDown
- afterOnCellMouseOut
- afterOnCellMouseOver
- afterOnCellMouseUp
- beforeOnCellMouseDown
- beforeOnCellMouseOut
- beforeOnCellMouseOver
- beforeOnCellMouseUp
