### ISSUE TITLE
Read-only cells are cleaned when I select a column and press delete

### ISSUE THREAD

**Issue by fbrussa** [handsontable/handsontable#4548]
### Description
When I select a column and press delete, read-only cells are cleaned.
This also happens if I copy a value and paste it along many rows.

### Steps to reproduce
1. Set cellProperties.readOnly=true for some cells
2. Click on header column
3. Press DELETE

Other:
1. Set cellProperties.readOnly=true for some cells
2. Copy a value
3. Select many rows
4. Paste value

### Demo:
http://jsfiddle.net/g0v5yuu4/1/

### Your environment
* Handsontable version: 0.34.4 in my server, Pro in jsfiddle
* Browser Name and version: Crome 61.0.3163.100 
* Operating System: Windows 7, Windows 10 ,MacOs 10

**Comment by AMBudnik** [comment]
Hi @fbrussa 

thank you for sharing the example.

It looks like the behavior is associated with `afterRenderer` hook. When we add the `readOnly: true` to a column, whole grid or [use the `cells` method](http://jsfiddle.net/xpqe9q30/) issues doesn't occur.

Additionally, only the cells that haven't been rendered while initialization are deleted. And as we are doing the action via `afterRenderer `I am not sure if that's a bug.  The `afterRenderer` hook can only guarantee that the conditions you have given

```
 if (row % 2 == 0) {
        cellProperties.readOnly = true;
        TD.style.backgroundColor = '#d0d0d0';
}
```

will be applied for rendered cells. I highly recommend using cells method instead.

**Comment by fbrussa** [comment]
Hi Aleksandra,

using it in the cell method solves the problem.

Thank you so much !
