### ISSUE TITLE
Returning false in the beforeChange handler causes the next paste to have wrong value

### ISSUE THREAD

**Issue by yixunx** [handsontable/handsontable#4549]
### Description
Quickly pasting the same content into the same cell several times can make the cell contain the pasted value repeated several times. This can happen when the `beforeChange` handler performs expensive operations, sometimes returns false, and sometimes returns normally. 

### Steps to reproduce

1. Create a Handsontable instance with a `beforeChange` handler like the following:
    ```
    if (source === "CopyPaste.paste") {
        console.log(counter, changes);
        counter++;

        /* Do some work that takes, say, 500ms */

        if (counter % 5 != 0) {
            return false;
        } 
    }
    ```
2. Copy a cell.
3. Select another cell and hit Ctrl-V at least 5 times quickly. 
4. Suppose the copied value was "1". The pasted cell sometimes ends up with "1111" instead of "1".

### Demo

https://jsfiddle.net/zxejoq2b/2/

### Your environment
* Handsontable version: 0.34.0
* Browser Name and version: Chrome 61.0.3163.100
* Operating System: Mac OSX 10.12.6

**Comment by AMBudnik** [comment]
Hi @yixunx 

Thank you for sharing. You are right - sometimes the pasted value is `11`. However, I was only able to replicate it on OSX Chrome 61. Windows version seems working fine.

**Comment by AMBudnik** [comment]
The issue is no longer replicable on both Windows and OSX under v `2.0.0`.
