### ISSUE TITLE
[0.31.1+] In certain circumstances it is possible to edit another cell even if input is invalid and allowInvalid: false

### ISSUE THREAD

**Issue by eitland** [handsontable/handsontable#4551]
### Description

A way to break the allowInvalid option for autocomple strict mode cell.

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.14.2/demo-autocomplete.html
2. Find example for "Autocomplete strict mode".
3. Double click in a cell in 3. column ("Chassis color (allowInvalid false)").
4. Double click in a cell in 2. column ("Year").
5. Double click on the same cell you clicked on in step 3.
6. Type an invalid value.
7. Double click on the same cell you clicked on in step 4. This cell is now editable even if there is an invalid value in the previous cell.

### Demo
https://docs.handsontable.com/pro/1.14.2/demo-autocomplete.html

### Your environment
* Handsontable version:  pro/1.14.2
* Browser Name and version:  Chrome 61.0.3163.100, Microsoft Edge 40.15063.0.0, Firefox Nightly 58.0a1 (2017-10-09)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the scenario.

I have replicated the issue

![bug](https://user-images.githubusercontent.com/10757813/31433240-fe2fc1d2-ae78-11e7-80b1-37f50c692fe6.gif)

**Comment by aaronbeall** [comment]
I've run into what appears to be the same problem, in my case I'm using a `dropdown` column type with `allowInvalid=false` and if I try to enter an invalid value and press ENTER in a cell after a few attempts I get the error (`Cannot read property 'getInstance' of undefined`) and the table is in an unrecoverable state:

![img](http://g.recordit.co/vBZ808FvK1.gif)

**Comment by AMBudnik** [comment]
Thank you for sharing that issue with a video @aaronbeall 
I ran into this issue yesterday as well. 

I am raising the priority.

**Comment by AMBudnik** [comment]
The issue is replicable[ from v `0.31.1`](https://docs.handsontable.com/0.31.1/demo-autocomplete.html) the same as https://github.com/handsontable/handsontable/issues/4834
[Works well on `0.31.0`](https://docs.handsontable.com/0.31.0/demo-autocomplete.html)

**Comment by AMBudnik** [comment]
Hi @eitland @aaronbeall please update to 4.0.0 The issue should be solved in this version.

**Comment by aaronbeall** [comment]
@AMBudnik Awesome thanks for the ping! We'll be upgrading ASAP.
