### ISSUE TITLE
Autocomplete strict mode breaks after leaving cell with invalid input

### ISSUE THREAD

**Issue by eitland** [handsontable/handsontable#4552]
### Description

After leaving a cell that is supposed to be allowInvalid: false (like described in #4551) the autocomplete feature breaks and validation fails to accept any input.

### Steps to reproduce

Note: The first 7 steps are the same as in issue #4551 

1. Go to https://docs.handsontable.com/pro/1.14.2/demo-autocomplete.html
2. Find example for "Autocomplete strict mode".
3. Double click in a cell in 3. column ("Chassis color (allowInvalid false)").
4. Double click in a cell in 2. column ("Year").
5. Double click on the same cell you clicked on in step 3.
6. Type an invalid value.
7. Double click on the same cell you clicked on in step 4. This cell is now editable even if there is an invalid value in the previous cell.
8. Double click on the same cell you clicked in step 3. (and 5. )
9. Observe:
9.1 There are now two focused cells 
9.2 The dropdown list for the cell you are editing has disappeared
9.3 The cell does not accept a valid value even if you type it in manually.

### Demo
https://docs.handsontable.com/pro/1.14.2/demo-autocomplete.html

### Your environment
* Handsontable version:  pro/1.14.2
* Browser Name and version:  Chrome 61.0.3163.100, Microsoft Edge 40.15063.0.0, Firefox Nightly 58.0a1 (2017-10-09)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for being so precise when it comes to bug reports and for the investigation that you had to do. 
I think that after fixing the https://github.com/handsontable/handsontable/issues/4551 the following issue won't occur. However, I might be wrong.

**Comment by eitland** [comment]
> Thank you for being so precise when it comes to bug reports and for the investigation that you had to do.

Thanks for the kind words. Happy to be able to contribute something back to open source.

> I think that after fixing the #4551 the following issue won't occur

My thoughts as well, I just wanted to report it anyway in case it somehow fit into a bigger picture that you see. I don't expect any action on this as long as #4551 gets solved.

**Comment by AMBudnik** [comment]
I have been reported about a very similar issue that may help us to solve the issue. Here are the steps

> 1. Click the cell with data "yellow" in column Chassis color (allowInvalid false) 
> 2. Enter some text that is not valid, for example "test" 
> 3. Press Esc 
> 4. Enter "test" again 
> 5. Press Tab 
> 6. Press Tab again 

The demo and the result are the same. Additionally, we get a console log

```
Uncaught TypeError: Cannot read property 'getInstance' of undefined 
at i.c (handsontable.full.min.js:400) 
at e.value (handsontable.full.min.js:26) 
at i.runHooks (handsontable.full.min.js:400) 
at i.p (handsontable.full.min.js:405) 
at e.value (handsontable.full.min.js:26) 
at i.runHooks (handsontable.full.min.js:400) 
at HTMLHtmlElement. (handsontable.full.min.js:405) 
at HTMLHtmlElement.r (handsontable.full.min.js:26) 
```

`[inform G# 9270]`

**Comment by phoenix-down** [comment]
@AMBudnik , I'm glad I found this thread. Because I'm running into this EXACT same issue that you mentioned on Oct 18, 2017. I've repeated this experiment using Handsontable Pro v2.0.0 with both my own app, and your demo page:

https://docs.handsontable.com/pro/2.0.0/demo-autocomplete.html#strict

> 1. Click on any cell in column 3 (allowInvalid false)
> 2. Enter invalid text (i.e. "test")
> 3. Press Esc
> 4. Enter "test" again
> 5. Press Esc

The steps above triggers the same error in both my app and your demo page:

```
handsontable.full.min.js:33 Uncaught TypeError: Cannot read property 'getInstance' of undefined
    at i.c (handsontable.full.min.js:33)
    at e.value (handsontable.full.min.js:26)
    at i.runHooks (handsontable.full.min.js:33)
    at i.p (handsontable.full.min.js:45)
    at e.value (handsontable.full.min.js:26)
    at i.runHooks (handsontable.full.min.js:33)
    at HTMLHtmlElement.<anonymous> (handsontable.full.min.js:45)
    at HTMLHtmlElement.r (handsontable.full.min.js:26)
c @ handsontable.full.min.js:33
value @ handsontable.full.min.js:26
runHooks @ handsontable.full.min.js:33
p @ handsontable.full.min.js:45
value @ handsontable.full.min.js:26
runHooks @ handsontable.full.min.js:33
(anonymous) @ handsontable.full.min.js:45
r @ handsontable.full.min.js:26
```

Is this a bug? Any workarounds? Please advise. Thanks!

**Comment by AMBudnik** [comment]
Thank you for investigating this issue @phoenix-down I believe that it will help us to solve the issue faster. We already have a full list of tasks for June, but will surely check your findings when we finish current to-do list.

**Comment by swistach** [comment]
Hi @eitland,
This was fixed in v4 https://docs.handsontable.com/pro/4.0.0/demo-autocomplete.html
