### ISSUE TITLE
manualColumnFreeze enables manualColumnMove

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4553]
### Description

`manualColumnFreeze `enables `manualColumnMove `even when `manualColumnMove `is set to `false`.

### Steps to reproduce

1. Try to switch positions of the columns.

### Demo

http://jsfiddle.net/ywoh08u5/

### Your environment
* Handsontable version: 1.14.2
* Browser Name and version: Chrome 61
* Operating System: Windows 10

[inform [forum](https://forum.handsontable.com/t/gh-4553-unable-to-disable-manualcolumnmove/1459)]

**Comment by pnowak** [comment]
Until we fix arrayMapper - until there will be a central table instead of each plugin have their own arrayMapper  - we can't fix this issue.

**Comment by AMBudnik** [comment]
The behavior remains the same in Handsontable v0.35.1

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment]
Works the same in v 5.0.1

**Comment by aninde** [comment]
Works the same in v 7.1.1 
demo http://jsfiddle.net/aninde/fsj2qpd9/

**Comment by AMBudnik** [comment]
Thank you for fixing.
Updated demo http://jsfiddle.net/45xg32cu/ (8.0.0.-beta1 official)

**Comment by AMBudnik** [comment]
That's a really long list of updates for this issue 🚶 so I'm more than happy to close it as solved! 🥳 

Updated demo http://jsfiddle.net/cnmxfp0r/
