### ISSUE TITLE
Pasting data with a checkbox-typed column displays #bad-value# in minSpareRows.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4554]
### Description
When pasting data containing checkbox-typed information into a table with a checkbox-typed column and `minSpareRows` enabled, the checkbox column inside the spare row display `#bad-value#`.

### Steps to reproduce
1. Go to http://jsfiddle.net/knf6mufx/
2. Select any cell
3. Press <kbd>Cmd/Ctrl</kbd> + <kbd>A</kbd>
4. Copy the data by pressing <kbd>Cmd/Ctrl</kbd> + <kbd>C</kbd>
5. Select the first cell in the spare, last row
6. Paste the data by pressing <kbd>Cmd/Ctrl</kbd> + <kbd>V</kbd>

**Result:**
![image =20x](https://user-images.githubusercontent.com/7397134/31435497-0199c3fc-ae80-11e7-85dd-155b27cb141d.png)

**Comment by AMBudnik** [comment]
Works the same in v0.35.0. Updated demo http://jsfiddle.net/n8dvre9x/

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0`.[ In v `0.24.3` ](http://jsfiddle.net/xey1pdf9/)it became possible to paste the data (step 6) as before `0.24.3`  the data haven't been pasted.

**Comment by AMBudnik** [comment]
It works the same in v 5.0.1

**Comment by AMBudnik** [comment]
Works the same in 8.0.0-beta1 http://jsfiddle.net/jb0u8265/

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/zs47trqx/

**Comment by AMBudnik** [comment]
This issue is no longer replicable in Handsontable v10. Updated demo http://jsfiddle.net/85mf3y02/


![Kapture 2021-10-11 at 14 40 20](https://user-images.githubusercontent.com/10757813/136791596-4bf5d76e-90cf-40f3-8147-da4bd997d09d.gif)

**Comment by AMBudnik** [comment]
I'm reopening this ticket. We have to make sure this regression does not come back so let's add some tests.
