### ISSUE TITLE
Incomplete method signature for validateCells in handsontable.d.ts

### ISSUE THREAD

**Issue by madoar** [handsontable/handsontable#4556]
Your `handsontable.d.ts` is missing a method signature in https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1610.
Starting from https://github.com/handsontable/handsontable/pull/2790 it's also possible to call `validateCells` with a `callback` taking a `boolean` value.

**Comment by AMBudnik** [comment]
Thank you for sharing @madoar 

@swistach can you please check that at the earliest convenience?

**Comment by swistach** [comment]
Hi @madoar,
you are right, we should change this definition.
Current url: https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L86

**Comment by AMBudnik** [comment]
The issue has been redirected to the [Wiki section / Improvement suggestions(https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)
