### ISSUE TITLE
Stenciljs Support

### ISSUE THREAD

**Issue by gbelmm** [handsontable/handsontable#4557]
### Description
could you create the web component with stenciljs?
https://github.com/ionic-team/stencil

**Comment by AMBudnik** [comment]
Thank you for sharing the idea. 

I am marking the topic as a `feature request`

**Comment by AMBudnik** [comment]
The issue has been redirected to the[ Wiki section / feature requests](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
