### ISSUE TITLE
How to get into the Hands on Table and out of the Hands on Table without using a mouse?

### ISSUE THREAD

**Issue by kag341** [handsontable/handsontable#4558]
### Description
Your Keyboard Navigation Instructions work for when you're already in a Hands on Table.  

How do I get into the Hands on Table with the keyboard only?  (no mouse)
And, how do I get out of Hands on Table with the keyboard only?

### Steps to reproduce

1. Tab through a page with a Hands on Table.  The entire table is skipped.  
2.
3.

### Demo

https://jsfiddle.net/handsoncode/3gas9z6q/

### Your environment
* Handsontable version: 28.4
* Browser Name and version: chrome Version 61.0.3163.100
* Operating System: Windows

**Comment by swistach** [comment]
Hi @kag341,
as you can see in #3906 and in #2519 we have not plan any accessibility improvements in the nearest future.
Here you can find simple example: https://jsfiddle.net/d4fnuqe6/
