### ISSUE TITLE
Feature request: Allow finer configuration of Autofill plugin

### ISSUE THREAD

**Issue by twjacobsen** [handsontable/handsontable#4559]
### Description
When using the Autofill plugin, the only config options are wether or not to insert new rows when filling, and to limit the directionality of the fill.

In our team, we'd like to see some finer configuration options.

Ideally, we'd love to see the option to configure directionality separately for copy-down and drag-down. The case is, that in our application, the user will *never* want to auto-fill (copy-down) horizontally - but would like to drag horizontally.

Optionally, and probably easier to implement, simply disabling the "copy-down" part of the plugin would also be an option.

### Your environment
* Handsontable version: 1.11.0

**Comment by AMBudnik** [comment]
The issue has been redirected to the[ Wiki section / feature requests](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
