### ISSUE TITLE
Error occurred during drag from a merged cell to copy data

### ISSUE THREAD

**Issue by ndq809** [handsontable/handsontable#4560]
When i try to drag a merged cell to copy data from it a error occurred and data can't be copy successfully.
What can i do to fix it?

This is DEMO 
I just want to copy data from A6 to A7 and A8 cell by drag it but it can't be done.
http://jsfiddle.net/2hyvq2q8/

Sorry for my bad english .

**Comment by AMBudnik** [comment]
Sorry, but I wasn't able to replicate the issue. What I did:

1. Select `A7` with a `A6` value and copy it via <kbd>CTRL/CMD</kbd> + <kbd>C</kbd>
2. Select `A7` with a `A7` value and paste data using <kbd>CTRL/CMD</kbd> + <kbd>V</kbd>

In the result, the data is pasted and there is no console log.
Maybe you can share a video?

**Comment by ndq809** [comment]
@AMBudnik Thank for reply
But the error just occurred when i drag the cell to copy data like excel it isn't  CTRL/CMD + C and CTRL/CMD + V, copy via  CTRL/CMD + C and CTRL/CMD + V worked perfect.
The error like this 
![error](https://user-images.githubusercontent.com/29438842/31748332-5945253c-b4ad-11e7-8fa7-2af29b116e08.png)

**Comment by AMBudnik** [comment]
Thank you. I have replicated the issue.

![gif](https://user-images.githubusercontent.com/10757813/31765680-831841d8-b4c5-11e7-9dd7-7607c1106c33.gif)

**Comment by ndq809** [comment]
@AMBudnik thank you for reply
I'll wait until this error was fixed :)
