### ISSUE TITLE
Current Version not compatible with ngHandsontable

### ISSUE THREAD

**Issue by maurerke** [handsontable/handsontable#4561]
### Description
We are using the Handsontable Pro Version with ngHandsontable within an Angular project.
Since the breaking changes of 0.32.0 (normal version) its not compatible anymore with ngHandsontable!
For example, the context menu (right click) does not work anymore because within the code the api is out of date: 
`Handsontable.eventManager.isHotTableEnv = false;` (throws exception because of eventManager!)

We are now facing a big issue because of this. Would be very very good if you could keep the other dependencies in sync. Thank you!

### Steps to reproduce
1. Use current handsontable version with ngHandsontable
2. Right-click into any table
3. Context-menu does NOT open and console errors are getting thrown

### Demo
Can be tested with your own demo if you would update the depdencies to the current version.

### Your environment
* Handsontable version: 1.14.3 / 0.13.0
* Browser Name and version:  Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hi @maurerke 

I am sorry but this is not the correct issue board. Please add the issue at the [ngHandsontable issue board](https://github.com/handsontable/ngHandsontable).

ps. it looks like a similar has been already posted at https://github.com/handsontable/ngHandsontable/issues/219
