### ISSUE TITLE
Setting cell color and cell comment with loadData

### ISSUE THREAD

**Issue by apo11on** [handsontable/handsontable#4562]
This is a question or feature request.
I am confused with loading comments or colors for cells. I wonder if there is any way to put colors and comments in the data that is given to loadData?
I am currently loading all the data and after that i iterate over each cell to set the comment and the color.
For the colors, i set a cellProperty color and have a custom renderer for each cell type i use that colors the background based on the property. For comments, i do the same - i iterate over each cell and use the setComment.
This sounds like a big ugly hack (or simply totally missing programming knowledge?)
Isn't there a way to load comments and cells with the data? E.g. having some {cellvalue/color/comment} in the data that is loaded (without a need for custom renderers)?

**Comment by AMBudnik** [comment]
Hi @apo11on 

I would see it working like that http://jsfiddle.net/x8ra22ro/

There is something wrong with the comments so I would need to check that as well. We should be able to pass the comment via cellProperties as well. Currently, it is the easiest way to pass metadata in Handsontable.

**Comment by apo11on** [comment]
Hi @AMBudnik 

Wow, that was a fast answer!

That looks nice. Just one additional question:
In case i want to set different colors for each cell in a row (or also different comments), i probably would like to set up the data like this (would i?).

Assuming i have a css for colors:

 var getData = [{
    model: 'Opel Astra',
    year: '2004',
    **comments: {model: 'Hello there'},
    colors: {model:'green'}**
  }, {
    model: 'Fiat Panda',
    year: '2000',
    **comment: {model: 'Hello there', year: 'uncertain'},
    colors: {model:'red', year: 'blue'}**
  }];

But i am totally lost then how to set up the cells function for that.

Or is that a bad idea to acommodate like this for different colors/comments for each cell in a row?

**Comment by AMBudnik** [comment]
Yes, I guess that passing the object with classes will still be the quickest way. Here's a complete example http://jsfiddle.net/04r5cgsb/

**Comment by apo11on** [comment]
Thank you very much for the explanation!
Regarding comments, you mentioned it should work via cell properties as well:
Do you mean that something like cellProp.comment = 'Hello there' should work?
Or should it work differently, via the Comments-plugin since you put this in the fiddle already:
var plugin = hot.getPlugin('Comments');

**Comment by AMBudnik** [comment]
I got it working directly by the cell properties. Here's a full example http://jsfiddle.net/04r5cgsb/1/

**Comment by apo11on** [comment]
Thank you so much - i really had problems understanding the cells function and how it can be used. 
Quite clear now!
I close the "issue"

**Comment by AMBudnik** [comment]
Happy to hear that it's clear now.
Feel free to post a new topic if needed.

**Comment by peterdolan** [comment]
Hey @AMBudnik, follow up question here: is there a way to do this such that each cell can have metadata passed in dynamically, without needing to format entire rows?

I'm imagining something along the lines of the following:
`var getData = [[{ data: 5, color: red}, { data: 7, color: blue}], [ {data:3, color: green}, {data:2}]]`

Is this possible? I've been wrangling with it and can't seem to get it to work properly.

Thanks,

Peter

**Comment by AMBudnik** [comment]
Hi Peter!

That's OK, we can continue in the same topic. We usually need a new one when we're reporting bugs (to attach commits/PRs). 

We have tried to create a structure like that but put the idea on hold. The closest thing is the [cells ](https://docs.handsontable.com/Options.html#cells)method. Still, it handles only metadata so the data has to be added separately.
If you attach the color value to a class you can use it like this http://jsfiddle.net/s940q7zt/ but the `IF`s or `FOR`s can get complicated when you have more data.

**Comment by peterdolan** [comment]
Hey @AMBudnik, thanks for the prompt response!

That's too bad, but I should be able to work around it.

Thanks!

Peter

**Comment by AMBudnik** [comment]
Let me know about the progress. That's an interesting project.
Also, I am here if you'd need anything.

**Comment by RahulBadenkal** [comment]
Hey @peterdolan, Were you able to find a way to work with attributes directly attached to the cell?
Like 
var data = 
  [
    [ { data: 5, color: red }, { data: 7, color: blue} ], 
    [ { data: 3, color: green}, { data: 2 } ] 
  ];
hot.loadData(data);

I can't seem to find an elegant way to handle it.
