### ISSUE TITLE
Problem with editor in case there are several instances in container with scrolling

### ISSUE THREAD

**Issue by abondarenko** [handsontable/handsontable#4564]
### Description
We've experienced a problems with editing on mobile platform.
We use handsontable plugin in Cordova application.
We have several instances of handsontable on a page in container with scrolling.
And when we try to edit cells at bottom of the page editor has incorrect 
behaviour:
1. It seems plugin calculates position of editor incorrectly.
2. We can't edit cell values in some circumstances

### Steps to reproduce
1.1 Open provided jsfiddle on mobile Safari
1.2 Scroll to bottom.
1.3 Try to edit cell value
2.1 In case there are several instances of handsontable on the page, 
enter value in the first one.
2.2  Enter value in the second one. There is strange thing (I suppose 
it's related to this bug somehow). After entering of the first symbol 
input just loses focus. Then you should move focus to input again and continue.
2.3 Finish editing.
2.3 Enter in Editing mode again for the previous edited cell and try to delete some symbol.

### Demo
http://jsfiddle.net/axkx3gp8/16/

### Your environment
* Handsontable version: 0.34.4 (both free and pro)
* Browser Name and version: Cordova app, mobile Safari
* Operating System: iOS 11.0.3

P.S. We've read that handsontable is not very mobile friendly, but in the most
simple cases (showing/editing) it should work well. So we've decided to use it.

**Comment by AMBudnik** [comment]
Hi @abondarenko 

I am happy that you have read the [known limitations](https://docs.handsontable.com/pro/1.14.3/tutorial-known-limitations.html) and you're right - editing should work. It is a bug even if we give it a lower priority as we do not consider Handsontable as a mobile library.

**Comment by abondarenko** [comment]
Thanks for a reply.

**Comment by abondarenko** [comment]
Do you have an ETA for resolving this issue?

**Comment by AMBudnik** [comment]
Sorry but the issue hasn't been scheduled yet.

**Comment by badass-icon** [comment]
@AMBudnik we have "Developer Plus" license and want this to be fixed asap. 
Bug was registered more than one month ago and still no fix for it.
How can we contact you to prioritise the bug fixing?

**Comment by abondarenko** [comment]
I've looked at the source code and found the following.
Release version of `handsontable`-pro contains bug

handsontable.full.js:60962
(0, _event.stopImmediatePropagation)(event); // backspace, delete, home, end should only work locally when cell is edited (not in table context)      break;

There is commented break-keyword.

And handsontable v.0.34.5 is correct.
Definitely they must be the same.

**Comment by AMBudnik** [comment]
Hi @badass-icon 

if you wish to speed up the process you can mail me to support@handsontable.com

@abondarenko Thank you for your investigation

**Comment by abondarenko** [comment]
I've already opened ticket on Support page at October, 19.
Isn't it enough?

**Comment by abondarenko** [comment]
One more thing. I've continued investigation about the following

> It seems plugin calculates position of editor incorrectly.

I believe the next line of code works incorrectly

mobileTextEditor.js:187
```var selectedCellOffset = offset(selectedCell),```

I changed it to
```var selectedCellOffset = selectedCell.getBoundingClientRect()```
and it works fine.

Should I create pull request with fix?

**Comment by AMBudnik** [comment]
Hi @abondarenko 

if you wish you can create a pull request. Thank you for your effort to investigate this subject.

**Comment by abondarenko** [comment]
After further investigation I can clarify steps to reproduce.
I have updated description and steps to reproduce in start topic.

**Comment by AMBudnik** [comment]
Thank you very much for your effort

**Comment by badass-icon** [comment]
Any updates on the issue?

**Comment by AMBudnik** [comment]
Hi @badass-icon 

sorry. We do not have an official Roadmap for 2018 yet.

**Comment by abondarenko** [comment]
It seems issue is fixed in the last version (0.38/0.18)

**Comment by AMBudnik** [comment]
Thank you for the confirmation @abondarenko

**Comment by AMBudnik** [comment]
Hi @badass-icon Please update the version and let me know if it works for you as well
