### ISSUE TITLE
Change cell background color dynamically 

### ISSUE THREAD

**Issue by noninyo** [handsontable/handsontable#4565]
Hi,

I would like to color cell that was change, so it will be mark as not yet saved.
And after I get a success result to change the color back to white

http://jsfiddle.net/zf1oe5Lt/9/

* Handsontable version:  vue-handsontable-official (proversion - if it change anything)

Thanks!

**Comment by AMBudnik** [comment]
Hi @noninyo 

What do you think about this code http://jsfiddle.net/handsoncode/fdzwpotz/?

I have used the <kbd>Save</kbd> button to erase the class that marks the cells as changed via `afterChange` hook.

**Comment by noninyo** [comment]
Hi @AMBudnik ,
Thanks for the replay. I would like the  user to work with the table with no need to stop and save.
Is it possible to add attribute to the meta because I tried use it in the cells but render  it these cells with different color

**Comment by AMBudnik** [comment]
Hi @noninyo 
I have tried with the autosave like here http://jsfiddle.net/handsoncode/nj3y4tmo/ but something is not right, as the class is not added if we call the `updateSettings` via autosave system. 
I have to take check the mechanism little closer.

**Comment by noninyo** [comment]
Hi @AMBudnik ,
For now I am using comment to give the user indication that his data was not saved yet.
But I will be happy if you let me know when you find more elegant why 
Thanks!

**Comment by AMBudnik** [comment]
Hi @noninyo 

I am happy that you have found a decent way to handle the action. Unfortunately, I did not find any other suitable solution.

**Comment by noninyo** [comment]
OK, Thanks for trying
