### ISSUE TITLE
Limitations of the context menu code

### ISSUE THREAD

**Issue by madoar** [handsontable/handsontable#4566]
I'm using `handsontable` in combination with `angular 2+` and `angular-handsontable`.
Both is working well for me!

During coding I've stumbled over a few limitations, when implementing a custom context menu.
To add a custom context menu, you need to provide an object containing the content of your context menu to the `contextMenu` field in the settings.
An example how this can be done, can be found on your homepage: 

```javascript
hot3.updateSettings({
    contextMenu: {
      callback: function (key, options) {
        if (key === 'about') {
          setTimeout(function () {
            // timeout is used to make sure the menu collapsed before alert is shown
            alert("This is a context menu with default and custom options mixed");
          }, 100);
        }
      },
      items: {
        "row_above": {
          disabled: function () {
            // if first row, disable this option
            return hot3.getSelected()[0] === 0;
          }
        },
        "row_below": {},
        "hsep1": "---------",
        "remove_row": {
          name: 'Remove this row, ok?',
          disabled: function () {
            // if first row, disable this option
            return hot3.getSelected()[0] === 0
          }
        },
        "hsep2": "---------",
        "about": {name: 'About this menu'}
      }
    }
  });
```

I believe the current syntax has some disadvantages, which could need some improvements:
- for one it's quite unintuitive to specify the order of the elements in the context menu via the order of the fields in a json object. I believe a more natural and intuitive way would be to specify it via an array:
    ```javascript
    hot3.updateSettings({
        contextMenu: {
          callback: function (key, options) {
            if (key === 'about') {
              setTimeout(function () {
                // timeout is used to make sure the menu collapsed before alert is shown
                alert("This is a context menu with default and custom options mixed");
              }, 100);
            }
          },
          items: [
            {
              functionName: "row_above",
              disabled: function () {
                // if first row, disable this option
                return hot3.getSelected()[0] === 0;
              }
            },
            {
              functionName: "row_below"
            },
            "hsep1",
            {
              functionName: "remove_row",
              name: 'Remove this row, ok?',
              disabled: function () {
                // if first row, disable this option
                return hot3.getSelected()[0] === 0
              }
            },
            "hsep2",
            {
              functionName: "about",
              name: 'About this menu'
            }
          ]
        }
      });
    ```
    Here I've moved the keys of the json object into the context menu items.
    This syntax has the benefit, that it's more intuitive and it's easier to add or remove menu items during runtime.
- Another limitation is, that you receive no handle to the handsontable instance in the `callback` method.
    Especially when using a modular design, like you use in angular, you often have no direct access to the handsontable for which you're providing a `callback` method, because you're implementing it in another component/class, than where the handsontable is located.
    In such cases it would be good to add a new parameter, which is passed to the `callback` function, that contains the handsontable instance. Such a parameter should also be added to the other functions that can be added to the context menu, like the `disabled` function:
    ```javascript
    hot3.updateSettings({
        contextMenu: {
          callback: function (key, options, handsontableInstance) {
            if (key === 'about') {
              setTimeout(function () {
                // timeout is used to make sure the menu collapsed before alert is shown
                alert("This is a context menu with default and custom options mixed");
              }, 100);
            }
          },
          items: {
            "row_above": {
              disabled: function (handsontableInstance) {
                // if first row, disable this option
                return handsontableInstance.getSelected()[0] === 0;
              }
            },
            "row_below": {},
            "hsep1": "---------",
            "remove_row": {
              name: 'Remove this row, ok?',
              disabled: function (handsontableInstance) {
                // if first row, disable this option
                return handsontableInstance.getSelected()[0] === 0
              }
            },
            "hsep2": "---------",
            "about": {name: 'About this menu'}
          }
        }
      });
    ```
    This would allow the user to use handsontable in a more modular way.

**Comment by AMBudnik** [comment]
Thank you for sharing your suggestions.

It is definitely something that we can consider as a good tip.

**Comment by AMBudnik** [comment]
The issue has been redirected to the [Wiki section / Improvement suggestions(https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

ps. I highly encourage to create a PR if you have some time. It will be much easier for us to pull the changes

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. Please free to continue the conversation there. Thank you.
