### ISSUE TITLE
Column and row headers not shown properly in jquery ui dialog

### ISSUE THREAD

**Issue by ycopturion** [handsontable/handsontable#4569]
### Description
As the title. See the screenshot.
![handsontable](https://user-images.githubusercontent.com/33045022/31920454-d083a85c-b8b4-11e7-99ae-cdce631d53a2.png)

### Your environment
* Handsontable version: Download Handsontable CE Version 0.34.5
* Browser Name and version: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @ycopturion 

it looks like an issue with `position` in CSS. The headers are an extra layer for the Handsontable and they use their own styling. You can try to put the table inside a wrapper element.

**Comment by ycopturion** [comment]
Thanks @AMBudnik. Your suggestion of adding a wrapper element for the table works.

**Comment by AMBudnik** [comment]
Great. Happy to hear that and thanks for an update.

**Comment by vroyer** [comment]
I face the same issue. What do you mean by adding a wrapper ?

**Comment by AMBudnik** [comment]
Hi @vroyer 

Add a parent div element and then place Handsontable inside it

```
<div class="parent">
	<div id="hot"></div>
</div>
```
