### ISSUE TITLE
Cannot click on hyperlinks in a cell on a mobile device

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#4570]
Handsontable v34.5

If a HOT cell is rendered out as HTML with a hyperlink, clicking on it through a mobile device does nothing.  I've tracked it down to the main `touchend` handler on HOT (`onTouchEnd`) is doing a `preventDefault()` which ultimately prevents all touches from registering a click event to any anchor elements.

As a workaround, I have registered my own `touchend` handler to trigger a click event in these cases.  Please excuse the jQuery 😄 

```javascript
$hot.on('touchend', function(event) {
  if (event.isDefaultPrevented() && event.target.tagName.toLowerCase() === 'a') {
    event.target.click();
  }
});
```

**Comment by AMBudnik** [comment]
Hi @cgatesman which demo and device you've tested?

I tried https://docs.handsontable.com/pro/1.14.3/demo-custom-renderers.html on iPhone 6 and the first tap is selecting the cell and the second one is opening the link.

**Comment by cgatesman** [comment]
Several iOS devices including an iPad Pro.  I don't know what it is about that demo page you sent, but that is the only place it works.  Perhaps that page has another touchend handler?

If you copy that demo code and serve it from another location (which I've tried), it will not work.

**Comment by cgatesman** [comment]
I threw the demo up on S3.  This demonstrates the problem if you go to this link with an iOS device:

http://chads-landscaping.s3-website-us-east-1.amazonaws.com/hot.html

**Comment by AMBudnik** [comment]
Thank you for the link. I've tested it on iPhone 6 and 5s and you're right the link is not working.

I am marking this issue as a bug.

**Comment by AMBudnik** [comment]
Hi @cgatesman 

the issue has been solved in v 2.0.0. (CE and PRO).

Feel free to comment if it doesn't work for you or you have any concerns and we'll reopen the ticket.

**Comment by cgatesman** [comment]
@AMBudnik, I will validate when we are able to move our project up to 2.0.0.  Thank you! 👍

**Comment by ShaheedHaque** [comment]
For me, on 6.2.0, this works on Android but not on iOS.

**Comment by AMBudnik** [comment]
Hi @ShaheedHaque 

I've tried the demo with Book Titles at https://handsontable.com/docs/6.2.0/demo-custom-renderers.html and I had no issues with the links.

Tried it on: Safari for iOS 12.1

**Comment by ShaheedHaque** [comment]
I was not aware of that demo,and you are right, the demo works just fine on both Android (G930FXXU3ERJE and variants) and iOS 12.0.1. "Fine" here means that a single click directly on a link in a cell navigates to the link, with no need to pre-select the cell.

However, my code does not work in the same way:
- On Android (version as above), the first click selects the cell, whether the click is on the link or elsewhere in the cell. The selected cell renders with "bubbles" on the top left and bottom right corners and the selection rectangle in blue. A second click on the link navigates to the link.
- On iOS (version as above), the first click selects the cell, whether the click is on the link or elsewhere in the cell. The selected cell renders *without* "bubbles" on the top left and bottom right corners and the selection rectangle in blue. A second click on the link *does not* navigate to the link. I can provide a video of this if required (about 11MB).
- On iOS (version 10.0.2) things work exactly as I described in the previous paragraph.

I have double checked I am running 6.2.0, and compared the `renderer` setting with the demo. My code sets the columns like this:
```
            columns: [{renderer: 'html', readOnly: true}, {renderer: 'html', readOnly: true}],
```
I tried taking out the `readOnly: true` and the main difference was that the first click brings up the keyboard...nothing else seemed to change.

What else can I do to determine the differences which might cause this? (The debug environment on the mobiles is unknown to me, but I can obviously look at the desktop - our code does not deliberately do things differently to the Handsontable in any event).

**Comment by AMBudnik** [comment]
Are you able (by adding your settings) replicate the same issue in [the JSFiddle](https://jsfiddle.net/3km90yeb/)? What technology/frameworks do you use?

**Comment by ShaheedHaque** [comment]
> Are you able (by adding your settings) replicate the same issue in [the JSFiddle](https://jsfiddle.net/3km90yeb/)? 

I will try and get back to you.

> What technology/frameworks do you use?

No frameworks, just Django and JS with Bootstrap V4. I'm not consciously doing anything "clever":
- with Bootstrap, I see beyond what htDimmed does, just some colour and text-decoration
- with JS, nothing that shoudl be relevant

While I work on the JSFiddle, here is the call to the Handsontable constructor:
![image](https://user-images.githubusercontent.com/4881193/49013000-3525c180-f173-11e8-9a76-c8635c6b96d8.png)
Again, nothing unusual to my eye at least.

**Comment by AMBudnik** [comment]
I am wondering if it may be related to this issue https://github.com/handsontable/handsontable/issues/5479
Can you check if using version `6.1.1` solves the issue?

**Comment by ShaheedHaque** [comment]
This [fiddle](https://jsfiddle.net/ShaheedHaque/Lnwrbm17/4/) repros the problems with 6.2.0:
- On Android, first click selects the cell, a second click is needed to follow the link
- On iOS (now upgraded to 12.1), first click selects the cell, a second click does nothing

I will try 6.1.1 and report back.

**Comment by ShaheedHaque** [comment]
I downloaded 6.1.1, reset my static files, restarted Django, but it did not seem to make a difference on Android at least. (I don't see a way to flush the cache on Android....).

**Comment by AMBudnik** [comment]
I have replicated the issue on my iPhone but it is gone when you add `target='_blank'` to the link. But it [doesn't seem to be related to Handsontable.](https://stackoverflow.com/questions/42839716/ios-tel-and-mailto-links-only-work-with-target-blank)

**Comment by markp2** [comment]
I have added your suggested ` target='_blank' `and now the link works.
However, it still requires 2 clicks to actually open the link. See the new fiddle on https://jsfiddle.net/onpjawrL/ 

This is consistent on iOS Chrome and Safari, and Android Chrome.
