### ISSUE TITLE
Cell tooltip

### ISSUE THREAD

**Issue by morantal** [handsontable/handsontable#4573]
I'm using handsontable with VueJS, is there a way to create a tooltip (and not a comment) for each cell (in the same way theres a header tooltip) ?
many thanks!

**Comment by AMBudnik** [comment]
Hi @morantal 

there's no built-in system, but you can use the `html` renderer and the `title` attribute to create a cell tooltip. Here's an example http://jsfiddle.net/handsoncode/apgL6r9d/
