### ISSUE TITLE
Cell value object with nested headers

### ISSUE THREAD

**Issue by BadiuAlexandru** [handsontable/handsontable#4575]
### Description
I want to create a table with an object in every cell value. This object should look like this {id: '', value: '', status: '' }. My problem is that I cannot create a table with nested headers and in columns to show only the value property. Is there any way to achive this?

### Steps to reproduce
Go into my fiddle and replace data with data2 

### Demo
http://fiddle.jshell.net/AlexandruAlin/1z67cvwL/6/

### Your environment
* Handsontable version: handson pro 1.14.2
* Browser Name and version: Chrome latest
* Operating System: Windows 10

**Comment by BadiuAlexandru** [comment]
can somebody help me with this please?

**Comment by AMBudnik** [comment]
Hi @BadiuAlexandru 

I think that this is a very similar example http://jsfiddle.net/handsoncode/8ff1wryz/

However, the only way to get the data appear is to parse the data.

**Comment by BadiuAlexandru** [comment]
Thank you, I could reproduce this for my issue and make it work. But if I do this, I will lose the reference to main object and on select-copy-paste event I need to update the main object as well. Is there any way to catch the paste event with cell index and all other stuffs?

**Comment by AMBudnik** [comment]
Hi @BadiuAlexandru 

yes, there is a `beforePaste` hook. Here's an updated demo http://jsfiddle.net/handsoncode/ukmwkyh8/
It takes 2 parameters: data that will be copied and the coords: `{startRow: 0, startCol: 0, endRow: 0, endCol: 0}`
