### ISSUE TITLE
Remove the bottom margin of the table

### ISSUE THREAD

**Issue by chengtie** [handsontable/handsontable#4577]
![screen shot 2017-10-27 at 09 41 43](https://user-images.githubusercontent.com/774409/32094297-91141038-baff-11e7-8cf4-5fb9638dcbb9.png)
I am using Chrome Version 61.0.3163.100 (Official Build) (64-bit) or Safari Version 11.0 (12604.1.38.1.7) under Mac OS Sierra 10.12.6.

I want to create a handsontable, whose height may exceeds the height of the screen:

https://jsbin.com/bobevafana/edit?html,output

I realize that there is always a bottom margin below the table, does anyone know how to remove it?

**Comment by AMBudnik** [comment]
Hi @chengtie 

have you tried to cut the container via overflow of parent container?

**Comment by chengtie** [comment]
@AMBudnik 

Thanks for your answer. But could you please be precise? Do you mean add `style="overflow:hidden"` somewhere, I tried to add it to several places, but it did not work.

Cheers

**Comment by AMBudnik** [comment]
Yes, that was my first guess. Hm... I think that as you're using PRO version it might be the 'evaluation version' part space. It has been secured to not be deleted.

**Comment by chengtie** [comment]
@AMBudnik 

What do you mean? I tried to use `https://cdnjs.cloudflare.com/ajax/libs/handsontable/0.34.5/handsontable.js` and `https://cdnjs.cloudflare.com/ajax/libs/handsontable/0.34.5/handsontable.css`, and added `style="overflow:hidden"` to <hot-table>, the space is still there...

**Comment by AMBudnik** [comment]
OH, OK. Cause the Fiddle runs the PRO version - 1.8.2

**Comment by chengtie** [comment]
@AMBudnik 

I know, my original fiddle runs the pro version - 1.8.2. Here is 0.34.5:

https://jsbin.com/qofizuc/1/edit?html,output

Both of them have that space...

**Comment by AMBudnik** [comment]
I am afraid that without changing the source code we won't be able to change it. I have tried to overwrite the CSS of all container of the master table so the gap has to be generated by a script

**Comment by chengtie** [comment]
@AMBudnik 

So do you recognise that it is a bug?

Actually, i have post the same question on [StackOverflow](https://stackoverflow.com/questions/46969450/remove-the-bottom-margin-of-a-handsontable), it is very odd that many people don't see this space on their side. Do you know why?

**Comment by AMBudnik** [comment]
Thanks for posting. 

`I chatted with Rahul Arora, he was using Windows, and had not this issue. It's possible that this problem is Mac-only
--` -- that's an interesting comment

and here

`There is no margin properties declared on the table but there is the default user-agent margin declared on the containing body tag.
--` -- is also correct as the `<body>` is given a `8px` margin in all sides. 

I think that it may be related to JSBin, as when we put any table in JSFiddle and erase `<body>` margins we get no gap. Here's an example in JSFiddle http://jsfiddle.net/uw51zncq/ where an input is just right below the table.
I am testing this one on Windows 10/ Chrome 62

**Comment by chengtie** [comment]
Here is the screenshot of your JSFiddle on my side, I am using Chrome in Mac. Is it the same as what you see?

![screen shot 2017-11-07 at 14 06 10](https://user-images.githubusercontent.com/774409/32495205-fe51e6ca-c3c4-11e7-9b6b-70ae9f8efd45.png)

Here is a plunker with the same code as my JSBin, it has also a space:

https://plnkr.co/edit/igqvIO6EUhi0YTK4pyNL?p=preview

**Comment by AMBudnik** [comment]
Here's what I see on Windows 10 / Chrome 62

![image](https://user-images.githubusercontent.com/10757813/32495543-5c46d028-c3c6-11e7-82ad-a75ecd58af10.png)
There's no gap on FF and Edge as well.

On Mac
![screen shot 2017-11-07 at 2 19 30 pm](https://user-images.githubusercontent.com/10757813/32495681-e06564d2-c3c6-11e7-974f-e93c45b1d973.png)
Chrome on the left (v 61) and Safari on the right

**Comment by chengtie** [comment]
So we see different things. I am using Chrome Version 61.0.3163.100 (Official Build) (64-bit) or Safari Version 11.0 (12604.1.38.1.7) under Mac OS Sierra 10.12.6. Besides my screenshot of Chrome posted before, here is my screenshot of Safari, i think there is still a space.

![screen shot 2017-11-07 at 14 25 39](https://user-images.githubusercontent.com/774409/32495855-9efb44e8-c3c7-11e7-901e-649cf52eb031.png)

So is it a bug? What could we do?

**Comment by AMBudnik** [comment]
Do you get the same space after updating your Chrome? We've tested it on Chrome 62 on Mac and there's no space.

**Comment by chengtie** [comment]
I just updated my Chrome to Version 62.0.3202.89 (Official Build) (64-bit), i still see the space under Mac OS Sierra 10.12.6.

**Comment by AMBudnik** [comment]
It has to be something with your custom settings @chengtie Maybe you have some custom settings turned on? For some devices, it can vary.

I have tested 2 Sierra devices on Chrome 62 and they both show a 2px gap.

**Comment by chengtie** [comment]
In my screen settings, i can only tune `resolution`, and changing it does not remove the space.

**Comment by AMBudnik** [comment]
I am sorry but as I cannot replicate the issue I am not able to help.
