### ISSUE TITLE
Initial width of handsontable is not well set in a flexbox

### ISSUE THREAD

**Issue by chengtie** [handsontable/handsontable#4579]
I have a handsontable in a flex box.

https://jsbin.com/rikufelosi/1/edit?html,output

The behaviour is very odd: at least in Chrome or Safari under Mac, after loading the page, the width of the handsontable is not correct. If we scroll it to the right, then we see the width is extended correctly.

Does anyone know what's happening? and how to fix it?

**Comment by AMBudnik** [comment]
Hi @chengtie 

Have you tried to rerender the table after initialization?

**Comment by chengtie** [comment]
Hi @AMBudnik ,

How could we rerender that table? Could you make that JSBin work?

Cheers

Tie

**Comment by AMBudnik** [comment]
Hi @chengtie 

sorry for a delay.

You just call the [render()](https://docs.handsontable.com/pro/1.14.3/Core.html#render) method. It's a core method, so you refer it to the instance.

**Comment by ksidibe** [comment]
I'm having the same problem within a flex div (Bootstrap 4). Any solution?

**Comment by AMBudnik** [comment]
Hi @ksidibe 

if you have attached the Hot's CSS at the end of the resources list try the `render` method with a 10ms delay.
