### ISSUE TITLE
Nested header table is slow with large number of columns 

### ISSUE THREAD

**Issue by eric-chong-acl** [handsontable/handsontable#4581]
### Description
When having a nested header table with lots of columns, table becomes very slow.  Scrolling is very difficult.

### Steps to reproduce
1. Try add 500+ columns to a nested header table.

### Demo
http://jsfiddle.net/oz3puwr7/3/

**Comment by AMBudnik** [comment]
Thank you for sharing. We would need to look for a faster solution later in the future.

**Comment by AMBudnik** [comment]
I think that we just need to check nested Headers while adding performance improvements.
