### ISSUE TITLE
loadData render not correct 

### ISSUE THREAD

**Issue by gamevnlc** [handsontable/handsontable#4584]
### Description
I'm not sure it is bug or not

When use loadData method and setting is 
filters: true
minSpareRows: 1

Table render data not correct, one blank row was added when loadData method was call. 

### Demo
http://jsfiddle.net/L2qgL4bh/

### Your environment
Handsontable version: 1.14.3 pro
Browser Name and version: Chrome 62.0.3202.62
Operating System: Windows 10 64 bit

**Comment by AMBudnik** [comment]
Hi @gamevnlc 

thank you for sharing. It looks like it's the same issue as https://github.com/handsontable/handsontable/issues/3937 as when we comment `filters` it works as expected.

**Comment by AMBudnik** [comment]
Hi again @gamevnlc 

this bug also should be gone in 8.0.0-beta1

**Comment by AMBudnik** [comment]
Hi @gamevnlc referenced issue https://github.com/handsontable/handsontable/issues/3937 has just been closed as solved in v 8.0.0
