### ISSUE TITLE
Closing menu by `esc` key down doesn't work

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4585]
### Description
Since Handsontable `0.33.0` we can't close menu by `esc` key. It worked properly on previous version of Handsontable ([0.32.0](https://docs.handsontable.com/0.33.0/demo-context-menu.html))

### Steps to reproduce

1. Open context menu.
2. Press `esc` key.
3. Context menu doesn't close.

### Demo

https://docs.handsontable.com/0.33.0/demo-context-menu.html

### Your environment
* Handsontable version: >= 0.33.0
* Browser Name and version: Chrome 61.0.3163.100
* Operating System: macOS Sierra 10.12.6

**Comment by krzysztofspilka** [comment]
Works like a charm!
