### ISSUE TITLE
filter and html render

### ISSUE THREAD

**Issue by noninyo** [handsontable/handsontable#4586]
I would like to filter cells rendered by html but the value in the list appear as html tags
Is there a way to show only the value?

http://jsfiddle.net/noninyo/9ttcnz6m/
you can see it in the title filter

Thanks,

**Comment by AMBudnik** [comment]
Hi @noninyo 

you would need to wrap the text with an `<a>` tag via custom renderer to avoid getting the HTML inside filters.

**Comment by noninyo** [comment]
Thanks!
