### ISSUE TITLE
Handsontable > Borders > Creating Multiple Borders

### ISSUE THREAD

**Issue by ObviousAnswers** [handsontable/handsontable#4587]
I am currently using Handsontable and am saving out information related to borders. I have multiple borders on a document and I have it saving the rows columns and if it has a top left right or bottom border. I currently and looping over this array and doing the following.
if it should have a left border it does the following 
 hot.getPlugin("ContextMenu").executeCommand("borders:left"); 
if it has one of the others it does the same just replace left with right bottom or top. This is working as intended however it takes 15 seconds just to load one document with very few borders as it has to wait for the context menu. I can build an array of rows and columns along with the changes that need applied but I have no idea how to actually apply borders in bulk. I have looked into custom borders, however, and it is possible to set a range and I dont want to set a range as i want to (in theory) have an infinite amount of borders on the document. I can't use the other feature of custom borders either as it requires you to specify only one row and column. There has to be a faster way of doing this.

**Comment by AMBudnik** [comment]
If I understand it correctly. You have an array of comments that are loaded into the table. You also want the cells with comments to have a border.
Wouldn't t be just easier create a coordinates table/object that is used for commenting purposes and for borders?
If I am missing something just let me know.

**Comment by ObviousAnswers** [comment]
Thay may be what I am looking for but am not sure. Do you have an example of this anywhere on the handsontable website?

**Comment by AMBudnik** [comment]
I was thinking about something like this http://jsfiddle.net/g018eqfm/1/

**Comment by ObviousAnswers** [comment]
Ah  no. Its not that I want comments enabled. Its more that I am building tables with the borders. I also want my users to have the ability to put as many borders as they want and anywhere that they want. Its just that I need to be able to bulk load borders. Look at the following image.  Just loading that the aforementioned way takes 15-50 seconds waiting for the context menu. I have all of the rows/columns/sides that the borders are on. I just need a fast way to loop through these and set them. 
![image](https://user-images.githubusercontent.com/33263749/32443345-ac55e8ce-c2cc-11e7-8099-7a15639019a1.png)

**Comment by AMBudnik** [comment]
Can you share the code? I'd be happy to test some approaches.

**Comment by ObviousAnswers** [comment]
data contains all information saved out from whatever spreadsheet the user was working on. data.borders contains [row,col,top,bottom,left,right]. I then on the load iterate through data as the following code shows. I wont be able to proffer much more than that but knowing what parameters I am working with I am surprised there isnt already something capable of doing this process. As I am saving out a lot of data for the spreadsheet and am doing setDataAtCell and passing that an array and it sets it all and would think that borders would have a similar function. My next approach was going to be to look at how you add all those tiny divs and just do the DOM Manipulation myself. 
-------------------------------------------------------------------------------------------------------------------
                data.borders.forEach(function (el) {
                    hot.selectCell(el.row, el.col, el.row, el.col, false);
                    if (el.top) {
                        hot.getPlugin("ContextMenu").executeCommand("borders:top");
                    }
                    if (el.bottom) {
                        hot.getPlugin("ContextMenu").executeCommand("borders:bottom");
                    }
                    if (el.left) {
                        hot.getPlugin("ContextMenu").executeCommand("borders:left");
                    }
                    if (el.right) {
                        hot.getPlugin("ContextMenu").executeCommand("borders:right");
                    }
                })
-------------------------------------------------------------------------------------------------------------------

**Comment by AMBudnik** [comment]
That's an interesting idea. And have to say that there isn't any easy and quick way to set all 4 borders with different colors. It all needs a lot of coding.
