### ISSUE TITLE
Cell not hold input after specific loadData

### ISSUE THREAD

**Issue by 57ar7up** [handsontable/handsontable#4589]
### Description
After loading cell value as array instead of string it's showing correctly, editable, but not changeable (not holding input)

### Steps to reproduce
1.
```
hot.loadData([
  [
    ["try to change me"],
    "I will change normally"
  ]
])
```

### Demo
Any HoT instance

### Your environment
* Handsontable version: 0.34.5—1.14.3_Pro
* Browser Name and version: (latest) Google Chrome 62.0.3202.75 official 64-bit
* Operating System: Windows (10, Server 2012)

**Comment by AMBudnik** [comment]
Hi @57ar7up 

the data has a wrong structure. It has to be an array of objects or array of arrays. The first cell (that did not want to change) is held as 3rd nested element.
