### ISSUE TITLE
Sub sorting support

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4590]
### Description

`columnSorting: { column: [0,3] }` as a table option should sort a table by the column index 0 and then within that sort, sort it by the column index 3.

**Comment by AMBudnik** [comment]
That's a cool option. Thanks for sharing @jeremy-smith-maco

**Comment by AMBudnik** [comment]
The issue has been redirected to the[ Wiki section / feature requests](https://github.com/handsontable/handsontable/wiki/Feature-requests)
