### ISSUE TITLE
(freeze issue)Select a cell which position is more than the init viewport's then freeze it.It can't  scroll normal.

### ISSUE THREAD

**Issue by pensula** [handsontable/handsontable#4591]
### Description

Select a cell which position is more than the init viewport's then freeze (fixedRowsTop) it.The issue shows.It can't  scroll normal.
### Steps to reproduce

1.I have set  the value of fixedRowsTop a larger number
2.Try to scroll the right scroll bar
You get only the cells visible in the viewport or an empty space.Is the same issue as #4259 ?

### Demo

http://jsfiddle.net/3bn30mLq/11/

### Your environment
* Handsontable version: 1.10.2/0.31.2
* Browser Name and version: Chrome 62
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
Thank you for reporting. I have also replicated it in the latest version.
The example is really extreme and we would need to think about the best solution.

**Comment by pensula** [comment]
Ok, thanks.

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

![gif](https://user-images.githubusercontent.com/10757813/39125770-729eea32-4700-11e8-9680-d9afb699d029.gif)

**Comment by swistach** [comment]
Hi @pensula.
You're right it's the same issue.
Please follow this thread in #4259.

**Comment by pensula** [comment]
Thanks a lot.
