### ISSUE TITLE
Dropdown editor bolds values containing substrings of currently selected option

### ISSUE THREAD

**Issue by einr** [handsontable/handsontable#4596]
### Description
When a cell with `type: 'dropdown'` contains a selected value which is a substring of another possible value in the dropdown, the substring will be bolded in the other options.

For example, suppose "blue" and "light blue" both are options in a dropdown. Selecting `blue` and then looking in the dropdown again will then show as "**blue** " and "light **blue**"

I don't think this is intended behaviour? It feels weird and wrong. Only the explicitly selected value should be bolded.

### Steps to reproduce
1. Click jsfiddle below
2. Select `blue` from color dropdown
3. Click dropdown again and observe that the word "blue" is bolded not only in the selected option, but also in the options "light blue" as well as "dark blue"

### Demo
http://jsfiddle.net/ehjuhydm/2/

### Your environment
* Handsontable version: 0.34.5
* Browser Name and version: Firefox 56.0 (also confirmed in Chrome and Edge)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @einr 
the behavior is intended as the string to compare is the same one in `blue` as in the `light blue` or even `eblue`.

If you would like to strict the values to exact match you would need to overwrite the `AutocompleteEditor`

**Comment by einr** [comment]
Thanks for replying and for letting me know that this is intended. However, for the record, it seems to me that while this behaviour is correct for an autocomplete box, it doesn't seem appropriate for a dropdown select with fixed values.

**Comment by AMBudnik** [comment]
dropdown and autocomplete differ from each other with the fact that when you type 'blue' the dropdown still shows all options and autocomplete is cutting the phrases without the string 'blue'.

I think that we can use this topic as a feature request to add this kind of functionality.

**Comment by group131** [comment]
One relevant question using same example (http://jsfiddle.net/ehjuhydm/2/).
How can you add value 'light' to the drop-down? If you type 'light', 'light blue' is selected and you cannot add the value you want...

**Comment by AMBudnik** [comment]
Hi @group131 
It looks like a bug. Clicking anywhere outside the cell and the list should allow you to type `light`.

**Comment by AMBudnik** [comment]
The issue stays the same in v0.35.0. Updated demo http://jsfiddle.net/3vygwohb/

**Comment by AMBudnik** [comment]
The original issue is not an issue so I have created a new topic for the @group131 idea at https://github.com/handsontable/handsontable/issues/5346
