### ISSUE TITLE
Flexbox containing a handsontable cannot scroll in IE

### ISSUE THREAD

**Issue by chengtie** [handsontable/handsontable#4598]
I want to make 2 panels side by side by `flexbox`, and one panel contains a handsontable.

For the following code, in Chrome under Mac, the left panel with handsontable scrolls well. However, in IE, it cannot scroll.

https://jsbin.com/toxali/3/edit?html,output

Could anyone help?

PS: in my Chrome under Mac, I also see the space mentioned in [Remove the bottom margin of the table](https://github.com/handsontable/handsontable/issues/4577).

**Comment by chengtie** [comment]
Does anyone have any comment about this?

**Comment by AMBudnik** [comment]
Thank you for sharing the issue @chengtie 
I have replicated in on IE11, Windows 10.
It looks like the issue is related to https://github.com/handsontable/handsontable/issues/4320

**Comment by AMBudnik** [comment]
The issue's still replicable on 1.18.1/0.38.1

**Comment by AMBudnik** [comment]
Hi @chengtie 

I've tested this issue locally on my Windows 10 and Edge
<img width="153" alt="edge_ver" src="https://user-images.githubusercontent.com/10757813/85012794-da442880-b163-11ea-8edd-d863d70c1b6e.png">

using this demo https://www.w3schools.com/css/tryit.asp?filename=trycss3_flexbox_flex-wrap_nowrap8

and I got
![image](https://user-images.githubusercontent.com/10757813/85012811-e29c6380-b163-11ea-8303-c60dd23a387f.png)

which is a working version build on Handsontable 8.0.0-beta2-rev15

The issue hasn't been tested on IE as [support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser.
