### ISSUE TITLE
Editable column names

### ISSUE THREAD

**Issue by go1dfish** [handsontable/handsontable#460]
It should be possible to allow the editing of column headers, with their own change event and a way to get the current header values.

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
Hi. Closed issues rarely get new comments, so I hope that this issue will get more attention as a discussion.

See you there for updates and new ideas.
