### ISSUE TITLE
Nested rows and columns + collapse expand fonctionnaly

### ISSUE THREAD

**Issue by Dams591** [handsontable/handsontable#4603]
Hey guys,
We're testing handsontable at the moment and we're almost ready to buy it, however I could not find a proper example where I have both nested rows and columns.
I would love to be able to achieve this and also collapsing of rows/columns at the same time, to be honest we're trying to see if we could built a pivot table using handsontable.

Ideally we'd like to have something like this

http://nagarajanchinnasamy.com/subtotal/examples/110_collapse_rowscols.html

If it is possible I'd also love to know how to format my data array.
Thanks for the feedback
Damien

**Comment by AMBudnik** [comment]
Hi Damien,

maybe it's not the most interesting example, but I hope you'll find it useful http://jsfiddle.net/wf8yq1tc/

**Comment by Dams591** [comment]
That look really good ! thank you very much !

**Comment by AMBudnik** [comment]
You're welcome 👍

**Comment by xeoshow** [comment]
Great, thanks!

**Comment by xeoshow** [comment]
If using the open source community edition, is there any workaround? 

Thanks!

**Comment by AMBudnik** [comment]
Hi @xeoshow nestedRows is a PRO feature. Do you have the same example as @Dams591? If not, please create a separate topic with a demo attached. I'll try to help.

**Comment by Dams591** [comment]
Hi @AMBudnik 
Currently working on the fiddle you provided a few months ago, do you know how I can achieve the following

Let's take this image for example

![image](https://user-images.githubusercontent.com/12731716/36785249-7a0fe4f4-1c82-11e8-9be2-f7cf53d799c5.png)

If I collapse J, Column R Will be hidden leaving only the column Q visble

![image](https://user-images.githubusercontent.com/12731716/36785261-8b8c68f6-1c82-11e8-99f4-bbe4f502191c.png)

Is there a way to hide both J and Q and display another column which is either in the data set or not and that would be the sum of J and Q. So this new column would be a total and when expanding the parents column you would see the details values.

Thanks in advance,

**Comment by AMBudnik** [comment]
I think that you can try to use [`moveColumn `](https://docs.handsontable.com/pro/1.16.0/ManualColumnMove.html#moveColumn)method but there's no callback for collapsing so this can be a little bit tricky to move the column right after the parent gets collapsed.

**Comment by Dams591** [comment]
@AMBudnik  Hum yeah tricky and not easy its seems, is it possible to display the last column instead of the first ? In my example 'R' instead of 'Q'

**Comment by AMBudnik** [comment]
I think that we should add an `afterColumnCollapse` hook. I've added it to our board at https://github.com/handsontable/handsontable/issues/4873
Currently, the best hook to handle it would be the `afterRender` http://jsfiddle.net/z7ew4Lj3/ but it also changes with the `afterChange` (changing of data). But this we can ignore if we use a flag to let us know if data has been changed

**Comment by Dams591** [comment]
Right and what would be the code to implement inside the hook ? Still unclear on this.

**Comment by AMBudnik** [comment]
I will check that and if the code will work I am back with the demo.

**Comment by AMBudnik** [comment]
After checking the list of hooks that are triggered (assuming that you did not block the functionalities) is really long. Here's a scheme http://jsfiddle.net/LLtewt0L/
