### ISSUE TITLE
after filter, how to get the Filtered data source.

### ISSUE THREAD

**Issue by aRealCat** [handsontable/handsontable#4606]
### Description
What I want is not '.getSourceData',
i want the new dataSource after filter,
Can this be done?
thanks  : )

**Comment by AMBudnik** [comment]
Hi @aRealCat 

Is [`getData`](https://docs.handsontable.com/pro/1.14.3/Core.html#getData) what you need? Here's a demo to test http://jsfiddle.net/1bbvgncs/

**Comment by aRealCat** [comment]
Thanks @AMBudnik 
My problem has been solved
Use   .getPlugin('filters').trimRowsPlugin.rowsMapper.__arrayMap[changes[0][0]]

**Comment by AMBudnik** [comment]
Ohh OK. Thanks for an update then. I assume that we can close the issue.

**Comment by WeiLi-TW** [comment]
@AMBudnik hello, we also need get source data after filter, does @aRealCat method always work? can you provide method like getSourceData(), but get filtered data?

**Comment by AMBudnik** [comment]
Hi @WeiLi-TW 

The `getSourceData` returns an array with all the values (does not include filtering). Here is an example http://jsfiddle.net/1bbvgncs/1/

**Comment by WeiLi-TW** [comment]
Thanks @AMBudnik 
```getSourceData``` will get all source data, i want to get source data which be filtered, for example, source data is [{id: 1, content: "a"}, {id: 2, content: "b"}], after use id = 1 filter, i want to get [{id: 1, content: "a"}], but ```getData``` return [1,"a"], ```getSourceData``` return [{id: 1, content: "a"}, {id: 2, content: "b"}], both not my wanted.

**Comment by AMBudnik** [comment]
Hi @WeiLi-TW 
Maybe something like this http://jsfiddle.net/handsoncode/r7roepu3/?

**Comment by WeiLi-TW** [comment]
Hi @AMBudnik, Thanks supply this demo,
```Handsontable.hooks.add('afterFilter', x => {
  const afterFilterSourceData = _.map(instance.getPlugin('trimRows').rowsMapper._arrayMap, r => instance.getSourceDataAtRow(r));}, hot);
this afterFilterSourceData is i want, but i don't want depend on internal implement detail like _arrayMap, so i want to a standard api way to get this data.

**Comment by AMBudnik** [comment]
Currently, as far as I know, it is an only way, but it is a good idea to create API for this operation. Thank you for sharing your suggestion. I will double check it and let know if I find anything that is more suitable.

**Comment by RanaOsamaAwadallah** [comment]
@AMBudnik I'd like to get the count of rows after filtering as well but I can't use the above solution as I'm using V8.0.0beta (The filters plugin doesn't use the trimRows plugin anymore). Any idea what I can do instead?

**Comment by RanaOsamaAwadallah** [comment]
@AMBudnik I'm using v8.0.0beta in which the filters plugin doesn't use the trimRows plugin anymore.
Is there any other way I can get the count of rows after filteration?

**Comment by wszymanski** [comment]
In the callback to the `afterFilter` hook you can run the `getData` method. You may also use `instance.rowIndexMapper.isSkipped` (soon `.instancerowIndexMapper.isTrimmed`) for determining whether a particular row is trimmed.

**Comment by RanaOsamaAwadallah** [comment]
@wszymanski yes that's exactly it, thank you!
