### ISSUE TITLE
Twitter Bootstrap collapsible div height-related conflict with wordWrap handsontable

### ISSUE THREAD

**Issue by dborisog** [handsontable/handsontable#4607]
### Description

I have a handsontablee in a div collapsible by Twitter Bootsrap means. If wrapping is switched on and cells have multiple lines of text, the un-collapsed table covers the content  below. The tables height is bigger than the wtHider wrappers. Please see the image below.

I have two rows in the table. The wtHider has height of 47, which most likely comes from the default heights 23+1+23 (which excludes the table headers). In reality the table height is 113 pixels (26 for head, and 87 (44 + 43) for body)

![table-height-related-bug](https://user-images.githubusercontent.com/4368019/32712668-adc60148-c7fa-11e7-85c3-7b87fe05daa6.png)

### Steps to reproduce

1. have a collapsible bootstrap div https://getbootstrap.com/docs/3.3/javascript/#collapse set to collapsed state at the page loading
2. have handsontable with "wordWrap: true" inside the collapsible div, and 2+ lines of text inside each cells
3. have a content below the collapsible div
4. see the uncollapsed div 

### Your environment
* Handsontable version:  Version: 1.14.2
* Browser Name and version: Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)
* Operating System: Ubuntu Desktop 17.10

**Comment by AMBudnik** [comment]
@dborisog could you send us a demo?
I'll be much easier to track the progress.

**Comment by dborisog** [comment]
@AMBudnik , please have a look at the JSFiddle below, I have rowHeights parameter excluded in this version.

https://jsfiddle.net/dborisog/qL44xm9c/7/

**Comment by dborisog** [comment]
@AMBudnik, have you had a chance to check whether the JSFiddle from the previous comment can be considered as a demo for this ticket?

**Comment by AMBudnik** [comment]
Hi @dborisog 

I will try to share my thoughts on Monday

**Comment by dborisog** [comment]
@AMBudnik could you please have a look at the JSFiddle illustrating the issue?

**Comment by AMBudnik** [comment]
Hi @dborisog 

I am sorry for a delay. I think that the only way to overcome this situation is to add a fix height for the table https://jsfiddle.net/handsoncode/726dho59/

**Comment by dborisog** [comment]
Thank you, for the suggestion. Unfortunately, this case is not suitable for me because I deliver HTML presentation of multiple tables having different heights, in some cases with the content below the table. The height is dependent on the number of rows and height of the rows, which differs from table to table and from row to row. Because both of these parameters vary, I cannot use the fixed height, and I don't know how to calculate the proper height dynamically.

Looking at the behaviour I assumed the height is somehow calculated. Unfortunately, it seems the handsontable is designed with an assumption that cells in one column have the same height, which is not the case in my example.

In my comment with the link to my JSFiddle I've mentioned a temporal solution I've utilised, -- I've used rowHeights set to the presumed height for two-row cell (I think 43 pixels or so). The problem is that in big tables with few long values it would result in a poor utilization of the screen space. In addition to that, I cannot exclude that some cells would have values to be fit in three rows and more, and thus with the current rowHeights=43 usage it would result that some potentially critical information would be cut off from the user.

**Comment by dborisog** [comment]
If the JSFiddle is fitting, and by your response it is, could you please move it up the process, e.g. set as feature required label, provide a solution and thus mark as solved, or cancel the issue if you would find it irrelevant?

**Comment by AMBudnik** [comment]
We officially do not support Bootstrap, so I cannot mark this as a bug. However, I think that fixing this issue https://github.com/handsontable/handsontable/issues/4141 can have a positive impact on the issue with Bootstrap.

**Comment by dborisog** [comment]
Thank you, I've subscribed to the issue you have mentioned.

Looking at the handsontable.min.css having .htCore class for <table>, it seems to me Bootstrap is mostly irrelevant to the 4607 issue. However, if not collapsible, there handsontable works perfectly by not covering the content below the handontable, very much unlike if Bootstrap collapsible. In my eyes, it means that for one case of these two the height processing is done right, maybe at initialization of the table, and in the second bootstrap case the processing is done somehow differently. 

I'm however a novice in front-end development and do not understand CSS processing specifics, meaning that the non-collapsible case working right is not the handsontable JS doing, but the browser's doing.
