### ISSUE TITLE
Icon in DropDown Menu

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#4609]
Hi ,
 
             Can we allowed to insert HTML Element in Dropdown Menu Bar. for example
in this image sort Option have Icons which explain the functionality very easily.
Can anyone help me to do that
<img width="1440" alt="screen shot 2017-11-13 at 6 32 50 pm" src="https://user-images.githubusercontent.com/29049117/32727038-173b24c2-c8a1-11e7-9c18-2a5f75c4e390.png">

**Comment by AMBudnik** [comment]
Sure, here's an example https://jsfiddle.net/rgm2rgoy/

I have used a Google graphics alert example inside a dropdown option. It only sends an alert. However, you also have two options with checkboxes that changes the column cell type.
