### ISSUE TITLE
How to identify the row is Checked or unchecked in Handsontable

### ISSUE THREAD

**Issue by Prasadu112** [handsontable/handsontable#4610]
Hello,
Can anyone help me with  how to get the data which is checked in handsontable

**Comment by AMBudnik** [comment]
Hi @Prasadu112 


do you mean the checkbox cell type or validation process?

**Comment by Prasadu112** [comment]
hi @AMBudnik 

for validation process

**Comment by Prasadu112** [comment]
when i click on the check box for select rows i just want a message or to display saying this many rows are selected and this all the row data is selected.

**Comment by AMBudnik** [comment]
Do you mean something like this http://jsfiddle.net/handsoncode/0593qa58/?

**Comment by Prasadu112** [comment]
It is working thank you

**Comment by AMBudnik** [comment]
Great! Thanks for an update.
