### ISSUE TITLE
column width & text wrapping

### ISSUE THREAD

**Issue by davidh71** [handsontable/handsontable#4612]
Hi,
I have a table with very long strings in certain columns.  I am trying to determine how to implement a class by column name that allows me to wrap these.

In attempting to solve this i added a max-width to my css and that seems to break my table with fixed headers and column. - if you scroll to the right, then down, you will see the rows change their vertical height and not align.

https://jsfiddle.net/creffdcz/

What's the proper way to manage setting a maxium width that one, or all columns should obey and wrap the content within??

Many thanks!

**Comment by AMBudnik** [comment]
Hi @davidh71 

I have added `autoRowSize: true`, which fixed the issue. Here's an updated code https://jsfiddle.net/epjettq1/  (line 48)

**Comment by davidh71** [comment]
Awesome.  Thank you.
Is there a way to supply a classname to the column so this isn't applied to all columns / tables?

**Comment by AMBudnik** [comment]
Sure @davidh71 

you can use [columns](https://docs.handsontable.com/pro/1.14.3/Options.html#columns) options o [cells](https://docs.handsontable.com/pro/1.14.3/Options.html#cells). Here's an example with `cells` http://jsfiddle.net/d8yqewo6/
