### ISSUE TITLE
contextMenu doesn't add / remove the updated entries 

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#4614]
### Description
When changed the settings using the updateSettings in contextMenu doesn't appear the appropriate command.

### Steps to reproduce
![updatefalse](https://user-images.githubusercontent.com/1555809/32946359-7ac0b4a0-cb97-11e7-88f0-5128ef112e65.gif)
![updatetrue](https://user-images.githubusercontent.com/1555809/32946366-7f686764-cb97-11e7-8cd7-06fa264f1a79.gif)

### Demo
http://jsfiddle.net/ywoh08u5/2/

### Your environment
* Handsontable version: 0.34.5
* Browser Name and version: Chrome 62.0.3202.94
* Operating System: macOS Sierra 10.12.6

**Comment by pnowak** [comment]
Related to this issue #4553.

**Comment by AMBudnik** [comment]
Works fine now. Thanks!
