### ISSUE TITLE
Events are not working in Chrome version above than chrome version 59

### ISSUE THREAD

**Issue by Mrinal9024** [handsontable/handsontable#4615]
### Description
In my javaScript I have below code. Its a sample. 
while using Chrome Version 59.0.3071.109 (Official Build) (64-bit) it is working. 

But in other versions it is not working. 
Problem : Click event is not working (Handsontable.Dom.addEvent(document.body, 'click', function (e)) in browsers. 

Please tell us possible fix. 

My application is JAVA spring application. We are using Handson JS file and CSS file in our code.  

Please if i need to replace code what should i write. document.addEventListener("DOMContentLoaded", function() is working properly.

### Steps to reproduce

1.Click event any where in the page call "Handsontable.Dom.addEvent(document.body, 'click', function (e)"
2. than method executes according to logic

### Demo

document.addEventListener("DOMContentLoaded", function() {	
	  var hotElement = document.querySelector('#ID');
	  var hotElementContainer = hotElement.parentNode;
	  var hotSettings;
	  var dataArrayAll = [ /*ARRAY elemetns are declared*/ ];
	  var dataArray = [ /*ARRAY elemetns are declared*/];
		    
	hotSettings = gethotSettings(dataArray);
	var hot = new Handsontable(hotElement, hotSettings);
	
	function bindDumpButton() {
	    if (typeof Handsontable === "undefined") {
	      return;
	    }
	    Handsontable.Dom.addEvent(document.body, 'click', function (e) {
	      var element = e.target || e.srcElement;
	      //some code
	      
	    });
	}
	bindDumpButton();

});

function gethotSettings(){
//some code
}

### Your environment
* Handsontable version: Not sure but CSS version is Handsontable 0.15.0-beta6
* Browser Name and version: Chrome and Above that version 60
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hi @Mrinal9024 

it's very hard for us to replicate the issue on Java environment. 

Can you check if updating no newer version helps? 0.15.0 is one of the oldest versions where no one even thought about Chrome 59. 

Now we are in version 0.34.5. However, I do not recommend updating to the newest version as there were many backward incompatible changes. Here are our release notes to check what has been changed https://docs.handsontable.com/pro/1.14.3/tutorial-release-notes.html

**Comment by Mrinal9024** [comment]
We have use 4 Handsontable files in our code: 
1. Handsontable.js
2. Handsontable.formula.js
3. Handsontable.full.js
4. Handsontable.css
5. Handsontable.full.min.css


Please let me know possible way to replace these version. 
And let me know what version is compatible with latest browser like IE, FireFox, Chrome.

**Comment by AMBudnik** [comment]
I am not sure how deep with the versions you can go to support all current version of browsers. We do not note it anywhere.

But you can start by testing these two files (main .css and .js file) 
https://docs.handsontable.com/0.25.0/bower_components/handsontable/dist/handsontable.full.js
https://docs.handsontable.com/0.25.0/bower_components/handsontable/dist/handsontable.full.css

and the `Handsontable.formula.js` is a RuleJS file? Can you share it with me?

**Comment by Mrinal9024** [comment]
Can you tell me what to use in place of 
`Handsontable.Dom.addEvent(document.body, 'click', function (e) { }`
in above line i am getting error on addEvent in Version: 0.34.2. 
I want a mouse click event to trigger. 

We are getting below error while page load in latest chrome browsers with version:'0.15.0-beta6': 

handsontable.full.js:889 Uncaught Error: To be able to use the Copy/Paste feature from the context menu, your browser needs to have Flash Plugin installed.

 at ContextMenuCopyPaste.afterInit (handsontable.full.js:889)
    at Core.<anonymous> (handsontable.full.js:887)
    at Hooks.run (handsontable.full.js:730)
    at Core.init (handsontable.full.js:303)
    at new window.Handsontable (handsontable.full.js:248)
    at HTMLDocument.<anonymous> (filename)

I want to make my code multiple browser compatible.

**Comment by AMBudnik** [comment]
Hi @Mrinal9024 its an event tracking line. If you already have this somewhere else you can skip it.

**Comment by Mrinal9024** [comment]
I am able to solve above issue. 
I was using  `Handsontable.Dom.addEvent(document.body, 'click', function (e) { }` 
but in new version it should be `Handsontable.dom.addEvent(document.body,` 'click', function (e) { }`. 

Now I have another problem. for that i am logging new issues.
