### ISSUE TITLE
Merged area is shifted when we delete a column

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4616]
### Description

Merged area is shifted when we delete a column with merged cells.
It looks like the issue is not related to any particular version/commit.
(inform Gr # 9999)

### Steps to reproduce

1. Delete column `G`
![image](https://user-images.githubusercontent.com/10757813/33008197-6cdae616-cdd2-11e7-8fb5-c0d5842ddf0e.png)

2. The merged area from column `G` is shifted to column `F`.
![image](https://user-images.githubusercontent.com/10757813/33008220-8827ac56-cdd2-11e7-99c3-117b33b2ca8c.png)

### Demo

https://jsfiddle.net/arjunjayaraj/q6mnujub/1/

### Your environment
* Handsontable version: 0.34.5
* Browser Name and version: Chrome 62
* Operating System: Windows 10

**Comment by arjunjayaraj** [comment]
Will this be fixed in the next release.

**Comment by AMBudnik** [comment]
Hi @arjunjayaraj 

one of our developers is currently working on the Merge Cells plugin but I do not know if this issue will be fixed as well. The final version of our new milestone is nearly closed.

**Comment by arjunjayaraj** [comment]
Hi @AMBudnik 
This is bit critical for our project. I will really appreciate it, if this can be fixed in the next release

**Comment by arjunjayaraj** [comment]
Hi @AMBudnik

Is this issue fixed ?

**Comment by AMBudnik** [comment]
Sorry @arjunjayaraj it's still replicable.

I have just removed the label to alert that the problem needs to be reviewed by a developer. We are nearly finished with the first stage of mergeCells refactor + fixes. It will be available in the next release after the one planned for the next week.  Then we can start to plan the stage 2 fixes.

**Comment by AMBudnik** [comment]
Hi @arjunjayaraj The issue is no longer replicable in v `2.0.0` - demo https://jsfiddle.net/a43phwjq/
