### ISSUE TITLE
Problems with auto-complete cells and Japanese IME

### ISSUE THREAD

**Issue by ghost** [handsontable/handsontable#4617]
### Description

Handsontable auto-complete cells have problems with japanese characters since release 0.33.0 

### Steps to reproduce

1. Access to https://docs.handsontable.com/0.33.0/demo-autocomplete.html 
2. Click on an autocomplete field 
3. Type japanese characters

### Demo
https://streamable.com/0ueja

### Your environment
* Handsontable version: 0.33.0 or above
* Browser Name and version: Chrome Ver 62.0.3202.94（Official Build）（64bit）
* Operating System: Windows 7 64bit

**Comment by AMBudnik** [comment]
Thank you for sharing @pk-tmm 

Related https://github.com/handsontable/handsontable/issues/839

**Comment by AMBudnik** [comment]
Hi. The issue should be solved in v 4.0.0
Please update and let me know if it works for you.
https://github.com/handsontable/handsontable/issues/4662
