### ISSUE TITLE
Handsontable Issue : callback event after updatesettings 

### ISSUE THREAD

**Issue by Sheetal1289** [handsontable/handsontable#4619]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/3gas9z6q/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @Sheetal1289 

Can you share more details about this request?

**Comment by AMBudnik** [comment]
I am closing the issue as there aren't any additional details that could help me to understand this request.

Feel free to leave a comment if you still experience the same issue.
