### ISSUE TITLE
Issue with content of the cells rendered by html renderer on mobiles

### ISSUE THREAD

**Issue by d-aven** [handsontable/handsontable#4622]
On mobiles it is imposible to click on link inside the cell which is rendered by html renderer.
It is possible on desktops with latest version of library and it is possible on mobile with old versions (for example 0.17.0)

By the way, as I said above it is possible to follow the link on desktops with latest version, but all javascipt listeners are detached from the link by handsontable. 
For instance, the code below will not work with links inside the hansontable cell. Why?
`$(document).on('click', '.dynamic-popup', function (e) {`

### Demo
https://jsfiddle.net/jqb3nefy/2/

### Your environment
* Handsontable version: 1.14.3
* Browser Name and version: Chrome
* Operating System: Android 7

**Comment by AMBudnik** [comment]
Hi @d-aven 

thank you for sharing the issue. However, is it not the same case as mentioned by @cgatesman at https://github.com/handsontable/handsontable/issues/4570 ?

**Comment by AMBudnik** [comment]
I am closing this issue as it looks the same as #4570 
If I'm wrong please feel free to correct me.
