### ISSUE TITLE
Highlighted cell moves to a different cell when scrolling

### ISSUE THREAD

**Issue by marvinbables** [handsontable/handsontable#4623]
### Description

I made a table where edited cells are highlighted (to see which ones are altered). When I scroll horizontally, the highlight moves to a different cell.

### Steps to reproduce

1. Make a table with many columns such that a horizontal scroll appears
2. Scroll somewhere on the right
3. Edit a cell so that it gets highlighted
4. Move the scroll and see that the highlight moves to a different cell

### Demo

https://jsfiddle.net/4arLgy5g/
I also asked this in stackoverflow: 
https://stackoverflow.com/questions/47429932/handsontable-cell-highlight-css-moves-when-scrolling

### Your environment
* Handsontable version: 0.34.5
* Browser Name and version: Electron 1.6.12 or Google Chrome 62.0.3202.94
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
I personally recommend using `setCellMeta` to add a class for this kind of operations. Here's a working demo http://jsfiddle.net/handsoncode/jtpfs8av/

**Comment by marvinbables** [comment]
That fixed the problem, thanks!!
