### ISSUE TITLE
Scrolling issue on mobiles

### ISSUE THREAD

**Issue by igor-tvardyi** [handsontable/handsontable#4624]
Misalignment of header and table content when tap on header and move it.

### Steps to reproduce
1. Go to the demo on mobile.
2. Make frame with table smaller in order to have horizontall scroll bar.
3. Try to slide header

### Demo
https://jsfiddle.net/jqb3nefy/3/

### Your environment
* Handsontable version: 1.14.3
* Browser Name and version: Chome
* Operating System: Android 7.0

**Comment by AMBudnik** [comment]
Hi @d-aven

unfortunately, Handsontable is not mobile friendly yet, so to trigger the rest of rows to render you need to use [`viewportColumnRenderingOffset`](https://docs.handsontable.com/pro/1.14.3/Options.html#viewportColumnRenderingOffset) and [`viewportRowRenderingOffset`](https://docs.handsontable.com/pro/1.14.3/Options.html#viewportRowRenderingOffset)

**Comment by d-aven** [comment]
I cannot imagine how viewportColumnRenderingOffset and viewportRowRenderingOffset may help.
Here you can see the video:
http://dropmefiles.com/QuEh1

**Comment by AMBudnik** [comment]
The `offset~` settings are expanding the number of rows and columns to render as moving the table in mobile version does not trigger the table to load them automatically.
If you do not have a lot of data you can set the  `offset~` settings to the maximum amount of your rows and columns and in the result will allow the table to render entirely and recalculate the headers. 

However, I have tested it on iPhone and it did not work. I have also tried autoColumnSize it but did not help as well.

I am marking this issue as a bug.

**Comment by Dong-Qiu-Long** [comment]
苹果手机数据大时会导致浏览器刷新

**Comment by Dong-Qiu-Long** [comment]
ColumnRenderingOffset和viewportRowRenderingOffset   设置这两个属性数据比较大的时候会导致苹果手机浏览器不断刷新

**Comment by Dong-Qiu-Long** [comment]
Setting these two properties will cause the iPhone to refresh

**Comment by Dong-Qiu-Long** [comment]
当列有几百条         或者 行有1000条

**Comment by Dong-Qiu-Long** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/70185294/155259046-ae05fae2-2722-498f-be0e-e3d2c3627dad.png">

**Comment by Dong-Qiu-Long** [comment]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/70185294/155259183-04e21e51-a4f3-4998-8cf8-4a80c667610e.png">

**Comment by Dong-Qiu-Long** [comment]
Try the case with more attributes

**Comment by AMBudnik** [comment]
@Dong-Qiu-Long still no luck with reproduction. Could you share a demo where this issue is replicable?
