### ISSUE TITLE
Iterate POJO as single row in handsontable

### ISSUE THREAD

**Issue by dasguptahirak** [handsontable/handsontable#4627]
I have a requirement where I have a ArrayList of a POJO bean. And I want to display that arraylist as a single row in handsontable. It contains nested header also.

I have made success by displaying the nested header, but couldn't able to display that arraylist in handsontable. Please find below screenshot:

![image](https://user-images.githubusercontent.com/7932509/33266385-7257d53a-d39b-11e7-9fae-046353ba302b.png)

**Comment by AMBudnik** [comment]
I have to say that it's the first time I hear about `POJO bean`.

Can you share the code you use to generate your instance?

**Comment by dasguptahirak** [comment]
I mean to say that I have a java bean which is converted to javascript object like this:
var person1 = {firstName:"John", lastName:"Doe", age:46};
var person2 = {firstName:"Max", lastName:"Stalling", age:26};

And I have a javascript object array (say var persons=[] )that contains above js objects

Now I want to iterate javascript object array and populate handsontable in a single row.
![image](https://user-images.githubusercontent.com/7932509/33314875-f3bc147e-d454-11e7-9e89-5854873dc8a9.png)

**Comment by AMBudnik** [comment]
Can you share the object or only its structure or it's just like that 

```
var person1 = {firstName:"John", lastName:"Doe", age:46};
var person2 = {firstName:"Max", lastName:"Stalling", age:26};
....
var person100 = {firstName:"Ann", lastName:"Smith", age:52};
```

and you need to create an array of this objects [`[{person1}, {person2}, ...]`](http://jsfiddle.net/handsoncode/zpz4xqbz/)

**Comment by dasguptahirak** [comment]
Thanks
I forgot to write here that this problem was solved by first creating a js array and then pushing same to another js array and then assigning it like

data: secondjsarray

Handsontable is an amazing plugin 👍👍👍

**Comment by AMBudnik** [comment]
Cool! Thank you for an update. 

I am closing this issue. Feel free to open a new one if needed.
