### ISSUE TITLE
Disable drag and copy to specified cells

### ISSUE THREAD

**Issue by zawmyohtet1** [handsontable/handsontable#4630]
Hello,

Pls, help me how to disable drag and copy to specified cells.

Thank you.

**Comment by AMBudnik** [comment]
Hi @zawmyohtet1 

do you mean the `autofill` that is made when we use the cell right-bottom rectangle?

![gif](https://user-images.githubusercontent.com/10757813/33488064-bdabe76c-d6af-11e7-99b7-b3c18fbd355c.gif)

If that is the case you can block it via `beforeChange` hook like here http://jsfiddle.net/handsoncode/gkuaq0dv/

**Comment by zawmyohtet1** [comment]
Hi @AMBudnik ,

Yes, it is working well.
To disable "copy", I set cell option"[copyable](https://docs.handsontable.com/pro/1.14.3/Options.html#copyable)" to false.
Thank you :)

**Comment by davestewart** [comment]
Brilliant @ AMBudnik! That approach works great.
