### ISSUE TITLE
Scrolling improvement

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4632]
### Description
The major idea is to improve scroll mechanism of Handsontable (internally we call it `Walkontable`).
Current mechanism is relatively slow on IE/Edge/FF/Safari.

[Issues related to scrolling](https://github.com/handsontable/handsontable/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+scroll)

What should be done:

- [x] New, additional scroll element under overlays - master would be just an another overlay
- [x] A whole grid scrolled by one custom wheel listener (the same scroll position, at the same time, in each overlay)
- [x] Handsontable without CSS workarounds
- [ ] Handsontable.css based on walkontable.css (Can Walkontable exist without Handsontable?)
- [ ] Virtual rendering (virtualCalculators) called only if needed (not on each 1px change of the scroll position)
- [ ] New default cell size - unified heights and widths to be returned from API (no 'undefined' values which sometimes mean 23px, sometimes less/more - even when `autoRowSize` is enabled)
- [ ] Support for RWD
- [ ] Documentation adjustment (both, CE and PRO)
- [ ] Describe the new scrolling mechanism
- [ ] Improve the coverage of test for `Walkontable`

Known issues to be resolved before the release:

- [ ] Improper scroll behaviour during cell selection,
+ Editors are rendered improperly:
   + [ ] handsontable
   + [ ] autocomplete
   + [ ] dropdown
   + [ ] date
   + [ ] select
- Wrong dimensions of the following UI elements:
   - [ ] fixedColumnsLeft + fixedRowsTop + fixedRowsBottom
   - [ ] manualColumnMove + manualRowMove
   - [ ] manualColumnResize + manualRowResize
   - [ ] contextMenu
   - [ ] dropdownMenu
   - [ ] hiddenColumns + hiddenRows
   - [ ] nestedHeaders

**Comment by swistach** [comment]
Preliminary commits:
- ca27505
- ab815c9
- 9b3a56d
- bc9d773
- d1651ef
- 323c4b4
- 13644a7

**Comment by krzysztofspilka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rewrite layers to improve scrolling #4632](https://trello.com/c/Dldqj6AT/87-rewrite-layers-to-improve-scrolling-4632)

**Comment by Luiz-N** [comment]
Could issue #4498 be added to this list as well?

**Comment by AMBudnik** [comment]
Hi @Luiz-N 
we are only adding features/improvement on the Trello Whistlist. However, we should surely check what causes #4498 and fix it.

**Comment by swistach** [comment]
The board decided to freeze this project. Some parts of this project will be improved here: #4947
