### ISSUE TITLE
Wrong scroll position when user is editing selected but not visible cell

### ISSUE THREAD

**Issue by JJertok** [handsontable/handsontable#4633]
### Description
Hello

When I'm editing cell in last row I get unexpected result. How I can solve this problem?

### Steps to reproduce
1. Select cell in last row to edit
2. Scroll up
3. Type something
4. Scroll up
5. Type something

Actual result: table has a wrong scroll position
Expected result: table scroll to selected cell

### Demo
https://jsfiddle.net/api/post/library/pure/

https://screenpresso.com/=ArfZb

### Your environment
* Handsontable version:  1.14.3
* Browser Name and version: Chrome  62.0.3202.94
* Operating System: Windows 10

I am glad to get possible workaround.

Thank you.

**Comment by AMBudnik** [comment]
Thank you for sharing the issue @JJertok 

It seem like it is related to https://github.com/handsontable/handsontable/issues/3634

**Comment by swistach** [comment]
Hi @JJertok,
Unfortunately, your screencast and demo are not available. But, if it's related to #3634, then has to be related to #4832. So, that means we can continue this thread over there.
