### ISSUE TITLE
Mouse scrolling doesn't work with IE 11 and Edge

### ISSUE THREAD

**Issue by pirobox** [handsontable/handsontable#4635]
### Description
With the last version of the handsontable scroll doesn't work in IE11.

### Steps to reproduce
See Demo paragraph.

### Demo
1. not working
This jsfiddle uses the 0.34.5 version of the library
http://jsfiddle.net/atc9oemp/
Open it with IE11. try using a Mouse Wheel to scroll the frame with the grid. Result: nothing happens

2. working
This jsfiddle uses the 0.31.2 version of the library.
http://jsfiddle.net/hn5ztwe7/1/
Open it with IE11. try using a Mouse Wheel to scroll the frame with the grid. Result: The frame scrolls correctly

NOTES:
the same examples works perfectly fine with the latest version of chrome.
the same examples DON'T work with the latest version of Microsoft Edge

### Your environment
* Handsontable version: 0.34.5
* Browser Name and version: IE11
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @pirobox 

Thank you for sharing the issue and for your time to investigate it.
I think that I saw this issue somewhere before.
Can you check please if any of these topic https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3AIE%2FEdge cover your investigation resulsts?

**Comment by AMBudnik** [comment]
I assume that the issue is the same as https://github.com/handsontable/handsontable/issues/4320 but if there is anything we need to add please feel free to leave a comment.
