### ISSUE TITLE
Unable to call onclick from in-cell button

### ISSUE THREAD

**Issue by johnothetree** [handsontable/handsontable#4639]
### Description
I'm attempting to run an onclick function from a button that is within a cell of a table. Each button should be specific for each row, and run a function related to that specific row. Whenever I add the `onclick` attribute to the button, something breaks and the table doesn't show up. 

- Note: i'm really attempting to do an ng-click function with ngHandsontable, but i'm posing the question here because it's fundamentally an issue I'm having with Handsontable itself, and the ngHandsontable team is generally unresponsive to issues. 

### Steps to reproduce
1. jsfiddle from before adding the `onclick`: https://jsfiddle.net/t99Lc83L/3/
2. jsfiddle from after adding the `onclick`: https://jsfiddle.net/t99Lc83L/4/

### Your environment
* Handsontable version: current version
* Browser Name and version: Chrome 54
* Operating System: Win7

**Comment by AMBudnik** [comment]
Hi @johnothetree 

I hope that this demo will help http://jsfiddle.net/handsoncode/zram5uaL/ However feel free to let me know if we should explain anything

**Comment by johnothetree** [comment]
@AMBudnik thanks for the fiddle, that definitely helps me out. My one issue I'm still having is that when the `myBtn` function is called, I get an Uncaught TypeError on the TextRenderer line. 

In Angular1.6, the settings and function look like this: 
```
this.tableSettings = {
        colHeaders: ['Params', 'Pct', 'ID', 'Options'],
        columnSorting: true,
        sortIndicator: true,
        // afterOnCellMouseDown: (event, coords, TD) => {
        //   this.tableRow = coords.row;
        // }
        cells: function(row, col){
          const cellPrp = {};
          if(col===3){
            cellPrp.renderer = $scope.buttonCell();
            cellPrp.readOnly = true;
          }
          return cellPrp;
        }
      };

      $scope.buttonCell = function(instance, td, row, col, prop, value, cellProperties){
        Handsontable.renderers.TextRenderer.apply(this, arguments);
        td.innerHTML = '<button onclick="doTheThing()">"' + value + '</button>';
      };
```
I feel like it's something that's Angular specific, but i don't know what it would be...

**Comment by AMBudnik** [comment]
Hi @johnothetree 

here is another approach that may help http://jsbin.com/digupecame/edit?html,js,output (using ngHandsontable)

**Comment by johnothetree** [comment]
@AMBudnik that works for a button outside the table, but i'm trying to get the HTML button working within a cell in the table with ngHandsontable. 

Using your original suggestion, i tried adapting it to ngHandsontable, but something doesn't work and i think it's related to the scope necessity for anonymous inner functions (unless i'm fundamentally missing something, which is possible) http://jsbin.com/takuxalaju/edit?html,js,output

**Comment by AMBudnik** [comment]
Hi @johnothetree 

I have just spotted that even if we disable the plugin to get the correct column order and enable it again - we get the same order. Also, there is no function that resets the order. I allowed myself to change the title.

**Comment by AMBudnik** [comment]
Sorry for the title change. I had 2 issues opened and reset the wrong one.

When it comes to the demo I have two examples
https://jsbin.com/wayajekuti/1/edit?html,js,output
https://jsbin.com/heqijexeci/1/edit?html,js,output
with a help from @swistach 

Let me know if you'd need anything else.

**Comment by johnothetree** [comment]
the second example worked perfectly! A+ help @AMBudnik!
