### ISSUE TITLE
Numeric type does not show the same format after edit the decimal part with comma

### ISSUE THREAD

**Issue by jkancio** [handsontable/handsontable#464]
It does not show the same format if you edit one cell at Price colum in the example 
http://handsontable.com/demo/numeric.html and change the decimal part with comma (for example: change from 7000 to 7000,50) the euro symbol will disapear.

**Comment by arturgspb** [comment]
Hello!

What is the status of the problem? I got a problem when you copy cell data after entering.

1) Set the locale ru
2) Set the format: format: "0,0.00" (All data: {data: "adv_ctr", title: "CTR", type: "numeric", format: "0,0.00", language: "ru", renderer : fn_render_clicks})
3) Enter in the "1,1"
4) See "1.1"
5) Copy and paste the data into another cell
6) See the "11"

**Comment by AMBudnik** [comment]
Hi @arturgspb 
Could you please take a minute to create a demo where we can replicate the issue?
