### ISSUE TITLE
nested header column width and alignment between row and header

### ISSUE THREAD

**Issue by dasguptahirak** [handsontable/handsontable#4641]
I must say that handsontable is an excellent tool to work with.
I am using the same for a very wide table.
At present i am facing two issues:

1. i want to auto-resize header width according to content. I have tried following style but its not working:
```
<style>
.handsontable col.rowHeader {
    width: 180px;
}
</style>
```
2. Alignment issue between data row and header (screenshot below)
![image](https://user-images.githubusercontent.com/7932509/33419730-c782b01a-d5d1-11e7-9ac5-64395b0737f8.png)

**Comment by AMBudnik** [comment]
Hi @dasguptahirak 

I have already replied at the same issue at https://forum.handsontable.com/t/nested-header-column-width-and-alignment-between-row-and-header/1610
Can we discuss it there?
