### ISSUE TITLE
Unfreezing the last column freeze the browser

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4642]
### Description

When 'column freeze' plugin is enabled and you freeze the last column and then try to **unfreeze** it, it kills the browser.

### Steps to reproduce
1. Go to https://docs.handsontable.com/pro/1.14.3/demo-freezing.html
2. Freeze last column (Z)
3. Unfreeze it

### Demo

https://docs.handsontable.com/0.34.5/tutorial-introduction.html

### Your environment
* Handsontable version: 1.14.3 / 0.34.5
* Browser Name and version: Chrome 61
* Operating System: MacOS

**Comment by krzysztofspilka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unfreezing the last column freeze the browser #4642](https://trello.com/c/DaFJYX3m/207-unfreezing-the-last-column-freeze-the-browser-4642)

**Comment by AMBudnik** [comment]
Great! Works fine now.
