### ISSUE TITLE
Rendering functions are called for all visible cells after any change

### ISSUE THREAD

**Issue by sportfort** [handsontable/handsontable#4645]
### Description
After change in any cells, rendering functions are called for each visible cell in the table. These behavior causes rendering to be very slow and it's kinda weird and useless from my perspective.

### Steps to reproduce
1. Open http://jsfiddle.net/tw9ec3bx/ - here I implemented custom renderer which calls alert on every cell render
2. You will see multiple alerts from the browser (more than 5)
3. Change any value in the D column (date)
4. You will see 5 alert messages, which indicates that yellowRenderer was called 5 times

### Demo
http://jsfiddle.net/tw9ec3bx/ 

### Your environment
* Handsontable version: latest
* Browser Chrome and Edge
* Operating System: Windows

**Comment by sportfort** [comment]
I proposed a solution for this, but it was ignored:
https://github.com/handsontable/handsontable/issues/2152#issuecomment-255871990

**Comment by AMBudnik** [comment]
Hi @sportfort 

we will be changing this behavior via eco-rendering.

The project should start in January.

(related: https://github.com/handsontable/handsontable/issues/3276)

**Comment by sportfort** [comment]
@AMBudnik thank you!

So, you will start it in January, it will take at least 3 months. 
Could you, please, consider my suggestion? I tested it and it works properly for my use case. You could add an option "ExperimentalEcoRendering", so that users could enable it before you will complete your new project.

**Comment by AMBudnik** [comment]
Sure, we will consider it. That is why I have added the `improvement suggestion` label.
We just can't start it until January as the developer who is set to do it needs to finish his current task.

**Comment by AMBudnik** [comment]
I am closing this issue at it will be totally covered after https://github.com/handsontable/handsontable/issues/3276 gets implemented
