### ISSUE TITLE
Using manualColumnResize to make the header row bigger can misalign row headers

### ISSUE THREAD

**Issue by snelson3** [handsontable/handsontable#4647]
### Description

I am applying css to make my column headers word-wrap. As a result, when I use the resizePlugin to change a columns width from being wide enough that it can fit on one line, to having to work wrap, it messes up the row headers so some of them are duplicated/misaligned If I then manually adjust a columns width (doesn't matter which one or how much), the problem fixes itself.

![screen shot 2017-12-01 at 2 19 26 pm](https://user-images.githubusercontent.com/7496193/33506007-a87f8838-d6a2-11e7-9f9b-450a0bcaf47c.png)

### Steps to reproduce
1. See the description and the JSFiddle

### Demo
http://jsfiddle.net/s6t768pq/1080/

### Your environment
* Handsontable version: Whatever is being used for the example jsfiddle
* Browser Name and version: Google Chrome (newest version)
* Operating System: Mac OSX El Capitan

**Comment by AMBudnik** [comment]
v 5.0.1

![image](https://user-images.githubusercontent.com/10757813/44582715-cb2c0380-a7a2-11e8-9da6-564db69739ba.png)

**Comment by AMBudnik** [comment]
The issue seem to be gone http://jsfiddle.net/xfcybuta/ in `7.3.0`. Now when we resize column `this is a long name` we get 

![Zrzut ekranu 2019-12-30 o 15 03 18](https://user-images.githubusercontent.com/10757813/71585044-8b52fa00-2b15-11ea-8be1-719116d2d93e.png)


and when we resize it more

![Zrzut ekranu 2019-12-30 o 15 02 32](https://user-images.githubusercontent.com/10757813/71585024-6c546800-2b15-11ea-84e3-1f7c7eabe79b.png)

**Comment by AMBudnik** [comment]
Still works well,  I'm closing this topic.
