### ISSUE TITLE
Issue: Scrolling Issue In Firefox

### ISSUE THREAD

**Issue by CoryGH** [handsontable/handsontable#4649]
I have a HandsOnTable defined by:

let t = new Handsontable(document.getElementById(tid), {
columns: columns,
data: data,
colWidths: 100,
rowHeights: 23,
rowHeaders: true,
colHeaders: true,
renderAllRows: true,
currentHeaderClassName: 'ht_highlighted',
currentColClassName: 'ht_highlightedcol',
currentRowClassName: 'ht_highlightedrow'
});

And it renders pretty well (fills out the page for the size of the contents as desired,) however when using the mousewheel to scroll it seems to intercept and block the mousewheel event without letting it pass to the page and do the actual scrolling. Is there a way to shut off the HandsOnTable intercept of the mousewheel event until this is fixed?

This appears to be limited to Firefox, Palemoon, Waterfox, etc - in Chrome it works as expected, I haven't tested in Opera, Safari or IE.

**Comment by AMBudnik** [comment]
Hi @CoryGH 

please track changes to https://github.com/handsontable/handsontable/issues/4632
The IE/Edge is also affected by this bug
