### ISSUE TITLE
custorm header with colspan

### ISSUE THREAD

**Issue by ledt** [handsontable/handsontable#465]
Data_Headers : [['Group 1','Group 2'], // header name
[3,4]]     // cols span of header

I need this

```
----------------------------------------------------
|  Group 1        |    Group 2             |    <--- headers row 0
----------------------------------------------------
| 1-1 | 1-2 | 1.-3 | 2-1 | 2-2 | 2-3 | 2-4 |    <--- headers row 1 
----------------------------------------------------
| A   |   B |  C    |  D  | E   |  F   | G   |   <--- the real headers
```

i add it via jquery 

``` javascript
$('table.htCore thead').prepend('<tr><th colspan=1>.</th><th colspan=5> Group 1</th><th colspan=5> Group 2</th></tr>');
```

![Handson Table](https://f.cloud.github.com/assets/2200636/213937/26fc8aec-83d0-11e2-90a9-1de595d33fb3.png)

**Comment by manoharareddy** [comment]
this is not working in jsfiddle. can you please give me working copy of header groupings and multiple header columns

**Comment by AMBudnik** [comment]
@manoharareddy this would be a part of Handsontable PRO (release date: 11th of January 2016)

**Comment by ping2anilsharma** [comment]
HI manoharareddy,

http://docs.handsontable.com/0.15.1/demo-grouping-and-ungrouping.html

Try this. 

Let me if you need any further clearance on the same.
