### ISSUE TITLE
Firefox: The lastest version has scroll problem when scrolling a dropdown inside a scrollable table

### ISSUE THREAD

**Issue by MengtiSun** [handsontable/handsontable#4651]
### Description

Hi there,
I am using Handsontable version 0.34.5 on firefox and find this problem: 
when I scroll a dropdown inside of a scrollable table (a table with height), the table will scroll together with the dropdown
This does not happen on some old versions, like 0.29.2
This does not happen on Chrome

### Steps to reproduce

1. Go to the jsfiddle: http://jsfiddle.net/5r51hyq8/2/
2. Click the last column, which is a dropdown
3. Scroll this dropdown, and you will see the table scroll together with the dropdown

### Demo

http://jsfiddle.net/5r51hyq8/2/

### Your environment
* Handsontable version: 0.34.5. This does not happen on some old versions, like 0.29.2
* Browser Name and version: Firefox 57.0.1 (64-bit)
* Operating System: Mac

**Comment by AMBudnik** [comment]
I am not sure what you mean. Can you record it, please?

**Comment by AMBudnik** [comment]
I assume that we can close the issue as there is no reply for more than 20 days.

Please leave a comment if you are still facing the same or any other issue.

**Comment by toneb** [comment]
I'm facing the same problem in IE 11 and Firefox. It works as expected in Chrome.

![handsontable bug](https://user-images.githubusercontent.com/616279/40530358-be20677c-5ff8-11e8-8350-3e385b62cec8.gif)

Please re-open the task.

**Comment by AMBudnik** [comment]
Hi @toneb 

Thank you for sharing the tip. I've replicated it using the latest `3.0.0` version of Handsontable on IE 11
Chrome doesn't seem to be effected with that issue.

**Comment by AMBudnik** [comment]
Works the same with Handsontable v5.0.1. Chrome doesn't scroll the table.

**Comment by wojciechczerniak** [comment]
Wasn't that fixed in ##5921 ? We need to retest this issue @AMBudnik @aninde

**Comment by AMBudnik** [comment]
That i correct. We can close this issue report as it works well with the newest FireFox with v `7.1.1`

#### Before the PR that's what we got
![old](https://user-images.githubusercontent.com/10757813/65753059-70d04580-e10e-11e9-87de-1de1c7efe2fc.gif)

#### And with `7.1.1`
![new](https://user-images.githubusercontent.com/10757813/65753076-762d9000-e10e-11e9-9678-eece8604157d.gif)
