### ISSUE TITLE
Make it possible to configure root node of context menu

### ISSUE THREAD

**Issue by williamboman** [handsontable/handsontable#4652]
[From the looks of it](https://github.com/handsontable/handsontable/blob/97f2406d932e3f03fda3b11cce40f78c5b155884/src/plugins/contextMenu/menu.js#L523), the root node of the context menu DOM tree is hardcoded to be `document.body`. I'd like to be able to configure this (to make it play nicely with the fullscreen API).

**Comment by AMBudnik** [comment]
Hi @williamboman 

I've asked one of our devs and unfortunately, as you spotted, it's hardcoded and cannot be changed without touching the source code.
