### ISSUE TITLE
Missing rows after using resize handler

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4653]
### Description

When we use a resize handler and the row's width changes it causes rendering issues. The table doesn't load new rows to fill the empty space.

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.14.3/demo-sorting.html
2. Shrink column `B`
3. Widen column `B`

An empty space appears below the table.

![gif](https://user-images.githubusercontent.com/10757813/33607690-31510a84-d9c2-11e7-8cc5-8214ca175755.gif)

### Demo

https://docs.handsontable.com/pro/1.14.3/demo-sorting.html

The issue does not seem to be related to any version.

### Your environment
* Handsontable version: 0.34.5
* Browser Name and version: Chrome 62
* Operating System: Windows 10

**Comment by swistach** [comment]
It's strictly related to: https://github.com/handsontable/handsontable/issues/2822
Temporary solution is to use `autoRowSize`: http://jsfiddle.net/8gq75pk1/
