### ISSUE TITLE
After inserting a row, an auto-updated formula displays incorrect value

### ISSUE THREAD

**Issue by bknoles** [handsontable/handsontable#4654]
### Description
When inserting rows into a range within a formula, the formula should update and display the correct result.

For example, if a cell has this formula `=SUM(A1:A4)` and you insert a row at row 2 via `hotInstance.alter('insert_row', 2)`, then the formula should update to `=SUM(A1:A5)` and display the correct summed value.

In Pro version `1.14.3`, the formula updates properly, but the value does not always correctly update.

I haven't dug into the source at all to see if I can figure out where this might happening. 

### Steps to reproduce
In the linked demo below:

* Click 'insert row'
* Type a value in column B2
* Click 'insert a row' again
* Value in B7 is incorrect

The actual formula for B7 is correct, which is super cool. However, the displayed value is wrong.

If you edit any cell in the summed range, then the total recalculates correctly.

I have tried calling `recalculateFull()` on the formulas plugin to no avail.

### Demo
https://jsfiddle.net/bknoles/h1aofack/

![image](https://user-images.githubusercontent.com/1313383/33635815-1e57ab8c-d9df-11e7-9467-1065eafcfdb5.png)

### Your environment
* Handsontable version: Pro 1.14.3
* Browser Name and version: Chrome 62.0.3202.94 
* Operating System: MacOS 10.12.6

**Comment by AMBudnik** [comment]
Thank you for sharing the issue with the full description and for your effort to investigate it.

I have replicated the issue.

**Comment by bknoles** [comment]
@AMBudnik I just noticed you guys have a separate repo for "pro"... should I report this issue over there instead or is it ok to have it here?

https://github.com/handsontable/handsontable-pro/

**Comment by AMBudnik** [comment]
Hi @bknoles 

No, that's OK - it can stay here. Usually, devs are copying the issues to PRO repository after they start to fix it.

**Comment by aninde** [comment]
Works the same with a new version of cell meta []( https://github.com/handsontable/handsontable/pull/6254) demo - 7.2.2-feature/issue-6233 https://jsfiddle.net/aninde/e83hnzjL/ - no fixed

**Comment by warpech** [comment]
Notify https://forum.handsontable.com/t/refreshing-formulas-after-adding-new-rows/4887 when done

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by aninde** [comment]
v8.4.0 without minSpareRows - bug exist https://jsfiddle.net/aninde/jn0qgad8/

Currently under tests v9.0.0 + new formulas engine [HyperFormula](https://handsontable.github.io/hyperformula/) https://jsfiddle.net/aninde/e2ax45mu/
seems to solve this issue.

![Kapture 2021-05-21 at 11 59 20](https://user-images.githubusercontent.com/30186818/119120064-21016900-ba2c-11eb-89e2-bdb0f3f1431d.gif)

**Comment by aninde** [comment]
Still works well with v9.0.0 https://jsfiddle.net/aninde/pmdbg31z/.

**Comment by AMBudnik** [comment]
@aninde the scenario **works well** using the freeze build 
![image](https://user-images.githubusercontent.com/10757813/120283470-83bff380-c2bb-11eb-837d-60e85add950a.png)

https://jsfiddle.net/r76Lsekz/

**Comment by AMBudnik** [comment]
Hi @bknoles 

I'm more than happy to say that closing this issue as **fixed** for v9.0.0. I hope that it will also work well in your project.

For everyone interested, here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
