### ISSUE TITLE
Cell Value Modified

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#4655]
Hi,
Handson table removes cell Data when opening console.
Bug Can be reprouce By following steps:
1.click on any cell
2.open web console .
can anyone help me to fix it?

**Comment by AMBudnik** [comment]
Hi @Sundarcj 

I am not sure if we think about the same scenario. Can you record it, please? 

ps. if you think about closing the editor when someone opens a console - it's intended. We always close the editor if any other click has been made.

**Comment by Sundarcj** [comment]
vimeo.com/246789250


here is the demo .. i pressed (cmnd+optn+j) only for open console

**Comment by AMBudnik** [comment]
Thank you for sharing the video. I am trying the same one at the latest Chrome using this demo https://docs.handsontable.com/pro/1.15.0/demo-numeric.html but the value is not erased.

Can you share your settings and OS/Browser details?

**Comment by Sundarcj** [comment]
Browser:Google Chrome 
Version 63.0.3239.84 (Official Build) (64-bit)

OS: macOS sierra
version 10.12.6
MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by Sundarcj** [comment]
even  i got same issue in the link.that u gave.

**Comment by AMBudnik** [comment]
Hi @Sundarcj 

sorry. I have missed the scenario. I have replicated it on a Mac. However, the behavior is intended as the Handsontable erases the cell as it gets the `j` key from the key combination. If you edit a cell and open a console the value does not get erased
