### ISSUE TITLE
Clicking on cell in scroll-able region scrolls to top

### ISSUE THREAD

**Issue by lewisjb** [handsontable/handsontable#4656]
### Description
If you have a HT in a div with overflow-y set to scroll, and you click on a cell, it scrolls to the top of the div. 

### Steps to reproduce
1. Open JSFiddle
2. Scroll down to see the table
3. Click on a cell in 2nd or 3rd row

### Demo
http://jsfiddle.net/swLs6m4m/1/

### Your environment
* Handsontable version: 35.0
* Browser Name and version: Chrome 62 and Firefox Quantum 57
* Operating System: Ubuntu 17.02 and Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing @lewisjb 

I have replicated this odd behavior.

**Comment by lewisjb** [comment]
What does the removal of the 'priority' tag mean for this ticket?

**Comment by AMBudnik** [comment]
Hi @lewisjb 

we have decided that only a developer after bug review can add a priority label. That's how we will be able to pick the issues that haven't been checked yet.

I am also doing a bigger issue check on all our issues on Github. Some of them may have been already fixed or the behavior has changed.

**Comment by CoArrow** [comment]
I have the same issue, and I am using pro edition.

**Comment by AMBudnik** [comment]
Hi @CoArrow 

thank you for your feedback.

Most of the issues that are happening for CE is also visible in PRO.
As soon as the ix is made on the CE version it is merged to PRO.

**Comment by CoArrow** [comment]
@AMBudnik ，Got that, Thanks.

**Comment by dymafr** [comment]
I have the same behavior. Any update on this issue? Thanks a lot

**Comment by AMBudnik** [comment]
We are currently working on a fast and efficient way to scroll the table. Before that, we do not want to fix issues that are related to scrolling as after the changes they might not be applicable.

**Comment by lewisjb** [comment]
@AMBudnik is there a timeline on that?

**Comment by AMBudnik** [comment]
It will be discussed today as we need to set some mini-goals that will allow us to track progress. 

The task will surely be mentioned in our [ZenHub board](https://app.zenhub.com/workspace/o/handsontable/handsontable/boards?repos=1790564,85198294)

**Comment by nosir** [comment]
Hey, any update for this? It only appears in Pro

**Comment by AMBudnik** [comment]
I am sorry but there is no milestone attached to this issue yet.

**Comment by melloware** [comment]
I also have this [issue ](https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/611)using Community version 5.0.1.

**Comment by lucasncne** [comment]
I've been searching for a solution and this helped me: [https://github.com/handsontable/handsontable/issues/7](url)

Maybe it can help you as well.

**Comment by melloware** [comment]
You mean this link: https://github.com/handsontable/handsontable/issues/7

**Comment by melloware** [comment]
Looks like its fixed in the upcoming release: https://github.com/handsontable/handsontable/issues/5220

**Comment by wojciechczerniak** [comment]
You're right @melloware, I can't replicate the issue in 5.0.2-RC: http://jsfiddle.net/m0e5y3qg/

Can someone confirm?

**Comment by melloware** [comment]
I just tested it with Firefox and Chrome and both are working properly for me on Windows 10.  Firefox was the one having problems before.

**Comment by melloware** [comment]
**More testing:**
Chrome 68.0.3440.106 (_works fine_)
Firefox 62.0 (_works fine_)
Microsoft Edge 42.17134.1.0 (**fails by jumping to the top**)

**Comment by AMBudnik** [comment]
Hi @melloware.

Can you check it with v 5.0.2 and let me know how it works for you?

**Comment by melloware** [comment]
OK just checked using this JSFiddle: http://jsfiddle.net/m0e5y3qg/4/

Looks like Microsoft Edge 42.17134.1.0 still has the issue.

**Comment by AMBudnik** [comment]
Can I ask you to record it @melloware ?

**Comment by melloware** [comment]
I have never recorded anything before do you have a recommended tool to screen record?

**Comment by AMBudnik** [comment]
I am using a small free tool called GifCam

**Comment by wojciechczerniak** [comment]
@melloware JSDeliver in http://jsfiddle.net/m0e5y3qg/4/ demo loads Handsontable 5.0.1 as the latest version. 

I had to add version number to jsdelivr links for 5.0.2: http://jsfiddle.net/m0e5y3qg/6/

**Comment by lucasncne** [comment]
Works fine on Firefox with version 5.0.2, but the issue still persists on the mobile version of chrome.

**Comment by AMBudnik** [comment]
@wojciechczerniak maybe we should add the `mobile` label?

**Comment by melloware** [comment]
OK I used the fiddle from @wojciechczerniak using 5.0.2 and here is the capture of MS Edge.

![cam](https://user-images.githubusercontent.com/4399574/45427221-5430af00-b66c-11e8-9243-ca5640e34a52.gif)

**Comment by AMBudnik** [comment]
Welcome everyone.

I am happy to inform that this issue should be gone in version 6.1.0

Thank you again for all the effort and investigation that you have made to help us solve this issue.

**Comment by sejcudet** [comment]
Hello!

I have similar issue now in version 6.2.2. I can't provide demo. 
When click button with scrollIntoView function handsontable fired hook 'afterScrollVertically' and my window leave on the same point.
How can I prevent the hook?
