### ISSUE TITLE
Handsontable  show previous values of changed cells as commends

### ISSUE THREAD

**Issue by iriniapid** [handsontable/handsontable#4660]
I want to show the previous values of cell after it is changed to the user as a reference, like a comment but i have no ideas on how to do that. Can somebody help?

**Comment by AMBudnik** [comment]
Hi @iriniapid 

I would use the [`beforeChange`](https://docs.handsontable.com/pro/1.15.0/Hooks.html#event:beforeChange) hook and add its 3rd parameter (old_value) to a variable that is used by [`afterChange`](https://docs.handsontable.com/pro/1.15.0/Hooks.html#event:afterChange) to add a comment via [`setCommentAtCell`](setCommentAtCell) method.
