### ISSUE TITLE
Missing first character using IME API on Safari

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4661]
### Description

The first character entered into editor disappears. It occurs for Asia users when using IME API.

### Steps to reproduce

1. Select Chinse (pinyin) keyboard layout;
2. Go to https://docs.handsontable.com/pro/1.15.0/demo-scrolling.html and select cell A1;
3. Press 'c' key;

In result, editor becomes editable but without an entered key.

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: Safari 11
* Operating System: macOS

**Comment by budnix** [comment]
Duplicated with #4662

**Comment by AMBudnik** [comment]
Released: v4.0.0
