### ISSUE TITLE
Tooltip on some cells

### ISSUE THREAD

**Issue by chengtie** [handsontable/handsontable#4663]
I want to add tooltips to some cells: when we hover on a cell, we see a block of text appearing above. Does anyone know how to do this?

**Comment by AMBudnik** [comment]
Hi @chengtie 

I can propose a solution like this http://jsfiddle.net/handsoncode/37kwzxwz/

It uses `cells` method to define which cell we want to enhance by adding an HTML renderer. I am using the HTML `title` attribute to add a tooltip.
