### ISSUE TITLE
How can I develop the plugin of handsontable

### ISSUE THREAD

**Issue by nonownonow** [handsontable/handsontable#4667]
### Description
Because I need to develop a plugin of handsontable, I downloaded your official plugin skeleton repository. But that didn't work. is there any repository I referenced? Or is there any documents I referenced? 

### Demo
https://github.com/handsontable/handsontable-skeleton

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: chrome 63.0.3239.84
* Operating System: mac osx sierra

**Comment by AMBudnik** [comment]
Hi @nonownonow 

we have just had the exact conversation at https://github.com/handsontable/handsontable-skeleton/issues/3 so to keep consistency let's use a single channel of communication
