### ISSUE TITLE
HELP NEEDED: Confirm German translation

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4671]
## Welcome community!
We have just received a translation for the **German** language at the https://github.com/handsontable/handsontable/pull/4669.

Please help us to confirm it. 
**5 votes+** will allow us to confirm the translation and pull the changes.

Thanks!

**Comment by ckruhs** [comment]
Translation looks good for me 👍

**Comment by AMBudnik** [comment]
Thanks for your feedback @ckruhs

**Comment by AMBudnik** [comment]
Thank you for help. The German translation has been added to the official version of Handsontable and will be available with the next release.
