### ISSUE TITLE
Unable to stretch the handsontable to fit the page with a hidden ID column.

### ISSUE THREAD

**Issue by gustavollg** [handsontable/handsontable#4672]
Is there anyway that I can add the ID value to the handsontable data without adding an ID colum? (that column could be hidden though). What I want is to get the ID value when I retrieve the data from the table without a visible ID column. The function that I use is **handsontableInstance.getDataAtRow(i)**. If I don't create a column with the ID data I can't retrieve its value. If I create the ID column and then hide it with css, the **stretch: 'all'** option counts with the ID column, so the table doesn't fit the page. 

How could I stretch the table to fit the page with an invisible ID column (or retrieve the ID data without adding a column)?

**Comment by AMBudnik** [comment]
Hi @gustavollg 

if you use `columns` settings you can just skip it from the list. You can also pick the [`hideColumns`](https://docs.handsontable.com/pro/1.15.0/demo-hiding-columns.html) if you use PRO features.

**Comment by gustavollg** [comment]
If I skip it from the list, I can't get the ID value. I use the **getDataAtRow(i)** function.

**Comment by AMBudnik** [comment]
Have you tried `getSourceDataAtRow`? Here's an example to try it out
updated demo http://jsfiddle.net/Ltbuo5w6/
It shows all the columns and current data

**Comment by gustavollg** [comment]
It worked. Thank's a lot!

**Comment by AMBudnik** [comment]
You're welcome @gustavollg
