### ISSUE TITLE
Grid with hardcoded height and cells with "hot-in-hot" - nested handsontable not shown correct!

### ISSUE THREAD

**Issue by MobileAppVault** [handsontable/handsontable#4673]
### Description
Hi,

when I add a "hot-in-hot" and setup a specific height in the grid. The handsontable inside a cell will not show with all values. Please follow my demo and steps to reproduce.

**We expected the same behavior like the type: "combobox"* Which will show the list on top of the cell if the screen size not enough.

*Note: We need to set the height value dynamic because we want to resize the grid if the user resize the browser window.*

### Steps to reproduce
1. create handson table with one column "hot-in-hot"
2. setup specific height for the grid.
3. last "hot-in-hot" will not shown correctly

### Demo
http://jsfiddle.net/Mrumbohm/87rf56r7/2/

1. initial load without specific height works!
2. click button "set height"
3. now the last "hot-in-hot" tables not shown in the right way

### Your environment
* CE 0.35.0  ( next week the enterprise version :+1: ) 
* Chrome
* Windows 7

Many thanks!

**Comment by AMBudnik** [comment]
Hi @MobileAppVault 

The example is pretty complex but I think that the table does not appear as it does not know the exact size of the container. If we add `height` settings (like here http://jsfiddle.net/handsoncode/0oo1Lnmu/) it shows itself.

**Comment by MobileAppVault** [comment]
Hi @AMBudnik,

yes thats right but what would you recommend in case i need to specify the height of the table?

I already tried to set the z-Index for the handsontableInput but this also doesn't work. :|

**Comment by AMBudnik** [comment]
I think that it will be possible to resize with by listening to the `window` events. Have you tried that before?

**Comment by MobileAppVault** [comment]
Could you please explain it in more detail?

Currently I listening to the window events and resize the table with `updateSetting` but this will destroy the ability to see the full "hot-in-hot" table on a cell.

```
$(document).ready(function () {
    $(window).resize(function () {
            hotProductTable.updateSettings({
                height: getDynamicGridHeight()
            });
    });
});
```

**Comment by AMBudnik** [comment]
Oh yes, I was thinking about the same approach. 
I am really sorry but as the Handsontable responsiveness is still really low I do not think that we can overcome this issue in a different way.
