### ISSUE TITLE
handsontable('getInstance') undefined

### ISSUE THREAD

**Issue by krajcovic46** [handsontable/handsontable#4674]
### Description

I am trying to getSelected() of an Handsontable table. This gives me undefined and it shouldn't.

### Steps to reproduce
Just run the jsfiddle demo with console open.

### Demo

https://jsfiddle.net/Lyso5bh0/1/

### Your environment
* Handsontable version: 0.35.0 community version
* Browser Name and version: Chrome 63
* Operating System: Win 10

**Comment by AMBudnik** [comment]
Sorry but I do not know what you like to achieve with line `20`. Here is a demo that returns a selected cell row https://jsfiddle.net/Lb281fLx/

**Comment by gmanriqueUy** [comment]
Hi @AMBudnik. Actually, that demo is throwing `Cannot read property 'getSelected' of undefined`. :worried:

**Comment by AMBudnik** [comment]
OK, that's interesting... What browser and system do you use to test it? Is it the Chrome 63/Win 10 as written in the first post? I am using the same one and the demo is working fine. 

Please check below video.
![gif](https://user-images.githubusercontent.com/10757813/34713914-fb9f505e-f527-11e7-8f6f-4e460a9e2978.gif)

I get an alert with `0` value, which is the selected cell's row index.

**Comment by krajcovic46** [comment]
Hello,

the demo [here](https://github.com/handsontable/handsontable/issues/4674#issuecomment-351322208) works for me. 

The solution for me was to use global variable with the table instead of getting it with jQuery.

@AMBudnik , if you change your demo like so - https://jsfiddle.net/Lb281fLx/3/ you can reproduce what I was trying to achieve. However, I found another way of doing it and have no idea whether this approach (the one with jQuery getting the instance of handsontable) should work or not.

**Comment by AMBudnik** [comment]
Thank you for an update. I am happy that you've found the solution.

I guess that we can close the issue.
