### ISSUE TITLE
Formulas recalculates when we block a change via beforeChange

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4678]
### Description

Formulas recalculates when we block a change via `beforeChange`

### Steps to reproduce

1. Change `A1` to `5`

*Expected*:
The value in `C2` should be `1` but it shows `6`.

### Demo

http://jsfiddle.net/85yp65e6/2/

### Your environment
* Handsontable version: 1.15.0
* Browser Name and version: Chrome 63
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Works the same in version 1.15.1 (0.35.1). Updated demo http://jsfiddle.net/jk7fqn05/

**Comment by AMBudnik** [comment]
Still works the same in v 5.0.1. http://jsfiddle.net/a4pv8r9k/

**Comment by AMBudnik** [comment]
This issue is still replicable in v 8.2.0 http://jsfiddle.net/handsoncode/78sna2pu/

**Comment by AMBudnik** [comment]
### Case 2 (equals)

> The Formulas doesn't get calculated properly on load. but when i change something or just double click on the source cell, it gets calculated properly. i tried this on a jsfiddle that i found in the formulas demo page: https://jsfiddle.net/minalkumar2893/Ltvk9zqb/7/
> Also attaching a loom video: https://www.loom.com/share/600d948db42f44dfa73202256c3cd3b5

reported at https://github.com/handsontable/handsontable/issues/7522

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Works the same in the v9 http://jsfiddle.net/d8hvzcu0/
Might be related to https://github.com/handsontable/handsontable/issues/8107

**Comment by AMBudnik** [comment]
http://jsfiddle.net/dagvn1ec/ The issue did not change in v10
Cell `C2` still shows `6` instead of `1`.

**Comment by aninde** [comment]
https://github.com/handsontable/dev-handsontable/issues/935#issuecomment-1597116706

**Comment by AMBudnik** [comment]
This issue is solved in v13.0.0. Updated demo with the released version http://jsfiddle.net/mu85qwkx/
