### ISSUE TITLE
BOM  in the `export to .csv` feature

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4679]
### Description

Add an ability to configure what byte order mark (BOM) is placed in the exported CSV file

related to
_(line 41-42 of handsontable-pro/src/plugins/exportFile/types/csv.js):_
```
// Starts with utf-8 BOM 
let result = '\ufeff'; ```

```
`[inform Gr # 10671]`

**Comment by swistach** [comment]
It will be added in handsontable/handsontable-pro#85
