### ISSUE TITLE
how can I disable the row when the  value contains ‘M’

### ISSUE THREAD

**Issue by zzzyting** [handsontable/handsontable#4680]
### Steps to reproduce

1.if input value like '1504M'
2.check the valueif it contains ‘M’，
3.then this row,  disable
![qq 20171215163102](https://user-images.githubusercontent.com/25153242/34033503-6c887ec0-e1b5-11e7-8f2f-0b7a4dadcd51.png)

### Demo

https://jsfiddle.net/handsoncode/3gas9z6q/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @zzzyting 

You can use a custom validator with a regex condition. Here's a demo that may help http://jsfiddle.net/handsoncode/L7u49ngk/
