### ISSUE TITLE
copy paste is not working and column are not visible untill click

### ISSUE THREAD

**Issue by Mrinal9024** [handsontable/handsontable#4681]
### Description:
I have table inside modal. 
Only first column of table is showing and copy paste is not working. After first click on header or in modal all get populated. I ma loading table in 
`document.addEventListener("DOMContentLoaded", function() { //code for table}`
if i use `$().click(function () { code}` , all columns shows up. 
But copy paste is not working in any case. In JSfiddle copy/paste is working. 

When click on modal button, one popup open with table appears in which you can do entries or copy/paste as well. 
whole thing was working with 0.15 beta6 version, but that is not supported in new browser. 
Table size is 4 column and 25 rows. 
Now i am using 0.34.2 version. 
### Steps to reproduce

1. create one modal and button
2. on button click modal opens, Inside modal table gets populated 
3. inside modal, submit button provided which closes the model and submit data for further process. 

### Demo
I don't have working example as creating modal in JSfiddle needs lot of rework. 
Below is the code: 

Scripts added: 
1.pikaday.js
2.sheetclip.js(version 0.3)
3.handsontable.full.js(0.34.2)

```
document.addEventListener("DOMContentLoaded", function() {
  //code
var clipboardCache = '';
var container2 = document.getElementById('example');
var container2_1 = document.createElement('div');
	  container2_1.id = 'handsOnTableDiv';
	  container2_1.className = 'hot';
	  container2.appendChild(container2_1);
var sheetclip = new SheetClip();
var hot2_1 = new Handsontable(container2_1, getConfiguration());
function tableFunction() {
   Handsontable.dom.addEvent(document.body, 'click', function (e) {
           if (element.nodeName == "BUTTON" && (element.name == 'handontable' || element.name == 'handontable' || element.name == 'handontable') ){
                          //code-operation on submit
                                     }
}
tableFunction();

function getConfiguration() {
	    return {
	      data: dataObject,
	      columns: [
                    {
                         data: 'col1',
                         type: 'dropdown',
                         source:  dataArray
                    },
                    {
                         data: 'col2',
                         type: 'text'
                    },
                    {
                        data: 'col3',
                        type: 'numeric'
                    },
                    { 
                        data: 'col4'
                    }
                ],
                stretchH: "all",
                columnSorting: true,
                rowHeaders: true,
                colWidths: [185, 185, 185, 185],
                height: 350,
                overflow: scroll,
                maxRows: 25,
                manualColumnResize: true,
                manualRowResize: true,
                comments: true,
                contextMenu: true,
                contextMenuCopyPaste: true,
                fillHandle: true,
                colHeaders: [
                    'col1',
                    'col2',
                    'col3',
                    'col4'
                ],
	      afterCopy: function(changes) {
	        clipboardCache = sheetclip.stringify(changes);
	      },
	      afterCut: function(changes) {
	        clipboardCache = sheetclip.stringify(changes);
	      },
	      afterPaste: function(changes) {
	        // we want to be sure that our cache is up to date, even if someone pastes data from another source than our tables.
	        clipboardCache = sheetclip.stringify(changes);
	      },
	      contextMenu: [
	        'copy',
	        'cut',
	        {
	          key: 'paste',
	          name: 'Paste',
	          disabled: function() {
	            return clipboardCache.length === 0;
	          },
	          callback: function() {
	            var plugin = this.getPlugin('copyPaste');
	  
	            this.listen();
	            plugin.paste(clipboardCache);
	          }
	        }
	      ]

	    }
	  }

)};


$( document ).ready(function() {
		   $("#modal").on("show.bs.modal", function (e) {
				$(document).off('focusin.bs.modal');
			   $("#modal").css("display","block");
		});


```

Please help me to know where i am going wrong. 
Note:  Now modal showing all column But Copy/Paste is not working. Also above work-around is not working in all browser version. 
Copy/paste is not working in any browser. 
 
### Your environment
* Handsontable version:0.34.2 version
* Browser Name and version: Chrome/FireFox
* Operating System: Windows 10

Please help me out here. I want to make table and need to use a version which will support all kind of browsers. 
In 0.15 beta6 version 
`var hot = new Handsontable( division , configuration) `
was not working . So no click event triggering.

**Comment by AMBudnik** [comment]
Hi @Mrinal9024 

thank you very much for reporting.

Could you add it to a JSFiddle/JSBin or CodePen? It is really hard to read the code and even harder to test it.

**Comment by Mrinal9024** [comment]
I can not add it create JSFiddle. In fiddle copy paste is working. 
Please provide me possible reason Why copy paste not work in 0.34.2 version. What are the file i should use.

**Comment by Mrinal9024** [comment]
Also right mouse click is also not showing any options.

**Comment by AMBudnik** [comment]
Maybe it can replicable in any of our demos? https://docs.handsontable.com/pro/1.15.0/demo-scrolling.html

**Comment by Mrinal9024** [comment]
http://jsfiddle.net/em14fvw1/ 

In this demo right click working but in my code right click is not enabled. I used same configuration of HOTsetting in my code. 

Other all thing working. 

Is this possible that copy/paste not working because 
`$( document ).ready(function() {
		   $("#modalId").on("show.bs.modal", function (e) {
			   $("#modalId").css("display","block");
		setTimeout(function() {
		$('#divId').handsontable('render');
		$('#divId> td').trigger('click');

		console.log("timeout alert 1");
		}, 200);
		}); 
		}); `

**Comment by Mrinal9024** [comment]
I did more analysis: 

```
afterCopy: function(changes) {
                	alert("copy");
                    clipboardCache = sheetclip.stringify(changes);
                  },
                  afterCut: function(changes) {
                	  alert("cut");
                    clipboardCache = sheetclip.stringify(changes);
                  },
                  afterPaste: function(changes) {
                    // we want to be sure that our cache is up to date, even if someone pastes data from another source than our tables.
                    alert("paste");
                    clipboardCache = sheetclip.stringify(changes);
                  },
                contextMenu: [
                  	        'copy',
                  	        'cut',
                  	        {
                  	          key: 'paste',
                  	          name: 'Paste',
                  	          disabled: function() {
                                    alert("inside paste");
                  	            return clipboardCache.length === 0;
                  	          },
                  	        callback: function() {
                  	            var plugin = this.getPlugin('copyPaste');
                  	          	alert("paste callback");
                  	            this.listen();
                  	            plugin.paste(clipboardCache);
                  	          }
                  	        }
                  	      ],
```

For above code "paste callback" and "paste", never called and no alert came. also mouse-right click shows "inside paste" but no menu is shown. I am populating handontable inside modal.
results for above code: Right click is desabled. I am using latest Chrome browser.  
1. copy(using only keyboard shortcut): shows "copy" but not able to paste anywhere
2. cut(using only keyboard shortcut): shows "cut" but not able to paste anywhere
3. paste (using only keyboard shortcut): nothing comes up. 


I suspect that problem is with `ContextMenu`.

**Comment by AMBudnik** [comment]
Sorry for a delay @Mrinal9024 

Have you managed to push the project further? If not please let me know what are the exact steps to replicate the latest issue.

**Comment by AMBudnik** [comment]
I am closing this issue as there is no reply for nearly 2 weeks.

**Comment by jfeng21** [comment]
@AMBudnik  I'm having the exactly issue with @Mrinal9024 .http://jsfiddle.net/api/post/library/pure/ ```afterCopy: (changes) => {
				clipboardCache = sheetclip.stringify(changes);
			},
			afterCut: (changes) => {
				clipboardCache = sheetclip.stringify(changes);
			},
			afterPaste: (changes) => {
				clipboardCache = sheetclip.stringify(changes);
			},```
The 'copy', 'cut', 'paste' is not triggered even we click the option, can you please provide a solution?

**Comment by AMBudnik** [comment]
Hi @jfeng21 
Can you please resend the demo? The example did not save.

**Comment by jfeng21** [comment]
@AMBudnik, Thanks for the quick reply. Can you please try this demo? http://jsfiddle.net/jfeng21/0pxazpev/3/,  'Copy' and 'Paste' are working, but 'Cut' seems not be triggered. And I also saw this might be a known issue: https://github.com/handsontable/handsontable/issues/4207. 
Please let me know if any updates! Really appreciated ;)

**Comment by AMBudnik** [comment]
Hi @jfeng21 

unfortunately, the plugin has changed. Here is an updated demo http://jsfiddle.net/neaqqLc0/

**Comment by jfeng21** [comment]
@AMBudnik Thanks for the update! We are going to switch to HandsonTable Pro, just wondering will anything change for CopyPaste Plugin?

**Comment by AMBudnik** [comment]
PRO does not add/change anything in the copy/paste plugin. But please check the [release notes](https://docs.handsontable.com/pro/1.16.0/tutorial-release-notes.html) before updating the version.

**Comment by jfeng21** [comment]
@AMBudnik Thanks! Its very helpful!  One more question: does HandsonTable support sorting for a specific row? I only found columnsSorting.

**Comment by AMBudnik** [comment]
I am not sure how this should work @jfeng21 
do you have any draft/drawing or saw the feature anywhere?

**Comment by Mrinal9024** [comment]
@AMBudnik 
Hi yes some how i managed to push my project to production. I have used an older version of HOT to achieve my goals. 
Table was not appearing so i inserted delay in this function.but this was just workaround. 
I used 0.20.2.  In this version copy paste is working.

**Comment by AMBudnik** [comment]
Great. I am happy to hear that.
