### ISSUE TITLE
Microsoft EDGE does not load handsontable ( due to file size) how to build a custom version that is smaller in file size?

### ISSUE THREAD

**Issue by voordev** [handsontable/handsontable#4682]
### Steps to reproduce
1. Use handsontable (not full ) in Microsoft edge 

### Your environment
* Handsontable version:  Handsontable latest 
* Browser Name and version: Microsoft edge latest
* Operating System: Windows 10

Microsoft EDGE had an issue with handsontable not loading the JS file ( nginx gzip compression enabled ) it seems the file size of 512KB takes around 1 minute to load or does not load at all.
Can we build a custom version of handsontable that is say 200kb max? 
removing parts of the plugin not needed?
We only need the very basic functionality like copy paste from excel, we use no external plugins only some custom validators.

**Comment by AMBudnik** [comment]
Please check an answer to the same issue at https://forum.handsontable.com/t/problems-edge-file-size-handsontable/1649
