### ISSUE TITLE
Closing the cell editor scrolls the viewport

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4684]
### Description
After saving changes done in the editor, Handsontable should not to scroll the viewport if the edited cell is within a range of the current viewport (when it "fits").

Unfortunately, since 0.16.0, occurs a bug with unexpected scrolling after edition. It occurs only if colHeaders are wider than default column width. Additionally, if you change cell in last column, then `colHeaders` are misaligned.

### Steps to reproduce
1. Scroll to the last column
2. Select `AC1`
3. Open editor with <kbd>Enter</kbd>
4. Close editor with <kbd>Enter</kbd>

### Demo
https://jsfiddle.net/r3rxkjd9/

### Your environment
* Handsontable version: 0.16.0+
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
`[inform Gr# 10079]`

**Comment by swistach** [comment]
Currently, this issue doesn't occur: https://jsfiddle.net/6vuw1eg2/
There is another problem to request, related to misalignment of the column headers after a change.

**Comment by AMBudnik** [comment]
Thanks @swistach 
I've contacted a Client who also had this issue
