### ISSUE TITLE
Language key of settings object is present as own object property

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4686]
### Description
By default `language` key of setting object isn't set at `Object.prototype`. It's present "at top" of the `Object`.

### Steps to reproduce

1. Use `getSettings` function.
2. Watch the result.

![screen shot 2017-12-21 at 11 46 35](https://user-images.githubusercontent.com/141330/34252614-ad0e2060-e644-11e7-9d72-ca00550168ca.png)

### Your environment
* Handsontable version: 0.35.0

**Comment by krzysztofspilka** [comment]
Beautiful
![screen shot 2018-01-19 at 19 02 24](https://user-images.githubusercontent.com/8048526/35164612-56707d98-fd4b-11e7-909f-d858980b3383.png)

#tested
