### ISSUE TITLE
Percentages not rendered in pro

### ISSUE THREAD

**Issue by andrewwwooster** [handsontable/handsontable#4687]
### Description
Percentage formats render correctly in community edition v0.15, but not in pro v1.15

### Steps to reproduce

1. Goto http://jsfiddle.net/ggprrd23/3/.  I format both price columns as percentages.
      {
        data: 'price_eur',
        type: 'numeric',
        format: '0%'
      }

2. With pro libraries, percentages do not render
3. With community edition, percentages do render correctly.

### Demo
http://jsfiddle.net/ggprrd23/3/

### Your environment
* Handsontable version: pro 1.15
* Browser Name and version: IE and Chrome  61.0.3163.100 
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hi @andrewwwooster

From 0.35.0 we are defining numeric cells in a different way. The new syntax is

 ```
data: 'price_eur',
      type: 'numeric',
      numericFormat: {
        pattern: '0%'
      }
```
demo: http://jsfiddle.net/mphvyaoe/

Here https://docs.handsontable.com/pro/1.15.0/Options.html#numericFormat you can read more about it. Also I highly encourage to check all the changes in the latest version. The release notes are available at https://docs.handsontable.com/pro/1.15.0/tutorial-release-notes.html
