### ISSUE TITLE
Column headers scroll in Firefox, but won't in Chrome

### ISSUE THREAD

**Issue by quantillaproject** [handsontable/handsontable#4688]
I have a fairly complex web app where I am trying to use HOT.  

In one of my pages which has a worksheet that allows entry, I have a scrollable horizontal worksheet.  
Under Firefox it works right.  I have column headers that scroll with the cells beneath them.
In Chrome I am getting bizarre behavior.  (1) the headers don't scroll along with the cells beneath them when the HOT scrollbar us used; (2) the header columns shrink and resize when the browser window scrollbar is used; (3) Unless I do a lot of manipulation, with things like viewPortColumnRenderingOffset, I can't even see the columns further out in Chrome.

The problem is clearly an implementation issue since the performance is completely browser dependent.

**Comment by quantillaproject** [comment]
A bit more info...
It seems to work OK so long as the HOT table and its container fit entirely within the displayed page. Then there is no horizontal scrollbar for the browser, since all the content is on the page.

After a lot of trial and error, this seems important.  In fact, if the HOT table does not fully fit on the web page, then there is another piece of bizarre behavior: as I scroll right in the browser window, the width of the headers changes as they get scrolled, destroying even alignment.

As I can't guarantee my users will always scale to fit the worksheet into the window, this is a problem for the UI.

**Comment by quantillaproject** [comment]
here is an example of what it looks like:
![image](https://user-images.githubusercontent.com/33078648/34329206-cc3bce9e-e8b3-11e7-9b56-74350492aef4.png)

**Comment by AMBudnik** [comment]
Hi @quantillaproject please share a demo where I will be able to replicate this issue.

To be honest it's the first time I see a table where data is being 'eaten' by a row header.

**Comment by AMBudnik** [comment]
I am closing this issue as there is no reply for nearly 2 weeks.
