### ISSUE TITLE
Not working getCellMeta in afterChange 

### ISSUE THREAD

**Issue by sonrakiyazilimci** [handsontable/handsontable#4690]
### Description
 I want to use getCellMeta function in afterChange hook but not working. I when use function out afterChange hook, function is working. But not working in afterChange hook.

### Demo 
https://jsfiddle.net/3gas9z6q/6/

### environment
* Handsontable version: 0.35.0
* Browser Name and version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @sonrakiyazilimci 

Please take a look at this subject https://forum.handsontable.com/t/how-add-data-attr-to-cell/1666/5
I've also attached a sample demo.
