### ISSUE TITLE
How to select any cells ?

### ISSUE THREAD

**Issue by GreenMelon** [handsontable/handsontable#4691]
### Description
Can you please tell me how to select any cells ? I refer to your documentation but got nothing useful .

### Steps to reproduce
1. my data is like this 
![image](https://user-images.githubusercontent.com/13148281/34466959-7d9ac02a-ef1f-11e7-96d2-dab5e65efb7b.png)
2. what i want to select is 
![image](https://user-images.githubusercontent.com/13148281/34466965-99fc4a22-ef1f-11e7-8773-98efcd14cc7d.png)
3. waiting for your reply. Besh wishes 

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: Chrome
* Operating System: Mac OS

**Comment by GreenMelon** [comment]
It seems as handsontable only in favor of selecting cells in range, but not cells in separate。

**Comment by AMBudnik** [comment]
Hi @GreenMelon 

that is correct. You can only select a single cell or area at a time.

If you do not want to process the data further you can use a false selection. It is possible by changing border or background color of cells. Here's an example http://jsfiddle.net/hd86u2th/ where holding SHIFT key allows you to change a cell background.

**Comment by GreenMelon** [comment]
Thank you very much for your reply ! I will try someway to deal with this problem! thanks!!

**Comment by AMBudnik** [comment]
You're welcome @GreenMelon
