### ISSUE TITLE
where can set  'remove_col'  Chinese alias ?

### ISSUE THREAD

**Issue by daishiqi** [handsontable/handsontable#4692]
### Your environment
* code:
hot.updateSettings({
        columnSorting:true,
        contextMenu: ['remove_col', 'remove_row']
    });

where can set  'remove_col'    Chinese alias ?

**Comment by AMBudnik** [comment]
Hi @daishiqi 

we have added an ability to translate the context menu (and more) via internationalization. You can read more at https://docs.handsontable.com/0.35.0/tutorial-internationalization.html

Additionally, I highly encourage to send a pull request with the translation. We are just[ pulling the German version](https://github.com/handsontable/handsontable/pull/4669) and be happy to pull Chinese as well.
