### ISSUE TITLE
Help needed: Translating Handsontable into various languages

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4696]
Hi guys, 

we would like to make Handsontable as open as possible. To do that, we want to translate all the notifications and labels. The most needed languages are Japanese, French, Chinese, Italian, Spanish, Swedish and Russian.

**Translating process is quite simple:**

- Go to [/src/i18n/languages](//github.com/handsontable/handsontable/tree/master/src/i18n/languages)
- Clone one of the language files
- Translate the content
- Make a pull request following this instruction: https://docs.handsontable.com/0.35.0/tutorial-contributing.html

[Read full guide](https://docs.handsontable.com/tutorial-internationalization.html#custom-languages)

_We really appreciate your help!_

**Comment by slidertom** [comment]
NL translation.

[nl-NL.zip](https://github.com/handsontable/handsontable/files/1973074/nl-NL.zip)

**Comment by AMBudnik** [comment]
Thanks @slidertom! Can I ask you to create a pull-request with the translation? We still need the [CLA ](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)to be signed to get any of the code published.

**Comment by slidertom** [comment]
Hi,
CLA signed.  slidertom/handsontable nl_lang branch created with the NL language support.

**Comment by AMBudnik** [comment]
Thank you for signing the CLA @slidertom 
Can you also post a PR with the NL translation to Handsontable (`develop` branch)?
