### ISSUE TITLE
ContextMenu doesn't reuse editor holder element

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4697]
### Description

ContextMenu doesn't reuse editor holder element instead it creates the new element on every submenu appear.

### Steps to reproduce

1. Open context menu and toggle "Alignment" submenu several times;
2. In the Developer Tools look into `class="htMenu htContextMenu handsontable"` element you'll find several `class="handsontableInputHolder"` elements instead one.

### Demo
![sweet](https://user-images.githubusercontent.com/571316/34518185-9940262a-f07e-11e7-8893-33f8c2ea5fcf.gif)

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: any
* Operating System: any

**Comment by budnix** [comment]
Apparently, the same bug occurs for `dropdown`, `autocomplete` and `handsontable` editors.

![sweet2](https://user-images.githubusercontent.com/571316/34520077-71669338-f087-11e7-845e-828265b51c90.gif)

Changing priority to normal.

**Comment by swistach** [comment]
Related: #4503

**Comment by AMBudnik** [comment]
The issue is still replicable in v `2.0.0`

**Comment by AMBudnik** [comment]
The issue is no longer replicable in v 5.0.1
