### ISSUE TITLE
Bug: Copying of merged cells by dragging they on the last table row throw an error

### ISSUE THREAD

**Issue by yauhenihrabun** [handsontable/handsontable#4698]
### Description
Merged cells copying isn't work for last rows.

### Steps to reproduce
1. Enable cells merging and copying by dragging the square in right bottom corner
2. Merge cells in penultimate row
3. Drag merged cells by square to the last row
4. See error in console

### Demo
It reproducible on the main example if cells merging are enabled.
https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers&merge-cells
Also you can see the video: http://take.ms/3rjoh

### Your environment
* Handsontable version: version from example
* Browser Name and version: all

Are there any workarounds?
Thanks

**Comment by AMBudnik** [comment]
Hi @yauhenihrabun 

Thank you for reporting.

The following issue has been already reported some time ago here https://github.com/handsontable/handsontable/issues/4560

If you have any other tips/questions about this issue please add them to https://github.com/handsontable/handsontable/issues/4560
