### ISSUE TITLE
After double clicking select cell it doesn't disappear when using keyboard actions (Tab or Enter)

### ISSUE THREAD

**Issue by jdpagley** [handsontable/handsontable#4700]
### Description
Double clicking inside of a cell with the type `select` (double clicking gives the select element focus) and then hitting TAB, ENTER, or arrow keys doesn't do anything. If you only click the cell once and then the select cell performs as expected with keyboard actions (tab and enter). 

I think that the double click sets the focus on the select element that appears and then handsontable doesn't know what to do with it after that. 

### Steps to reproduce
1. Double click a cell with type select so that the select element appears and has focus
2. Try hitting tab, enter, or arrow keys to move the selection to a new cell
3. Select element doesn't do anything and other cells never receive the selection state.

### Demo
I was able to reproduce it using your select demo from your documentation https://docs.handsontable.com/pro/1.15.0/demo-select.html . I used the middle column that had the car manufacturers 

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: IE 11 & Chrome 63.0.3239.84
* Operating System: macOS Sierra

**Comment by AMBudnik** [comment]
Hi @jdpagley 

thank you for your effort to investigate and share this issue.
I have already reported it some time ago here https://github.com/handsontable/handsontable/issues/3269 but feel free to add anything else if I've missed something important.

Thanks!

**Comment by krzysztofspilka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rewrite layers to improve scrolling #4632](https://trello.com/c/Dldqj6AT/87-rewrite-layers-to-improve-scrolling-4632)
