### ISSUE TITLE
how to setborder with js? thanks

### ISSUE THREAD

**Issue by Comup-X** [handsontable/handsontable#4701]
I use updateSettings but it is not work.My version is 0.35.0

**Comment by AMBudnik** [comment]
Hi @Comup-X 

Yes, we are experiencing [some issues with `customBorders `and `updateSettings `working together](https://github.com/handsontable/handsontable/issues/2002).

If that meets your project requirements you can test adding outline via classes. Here is an example http://jsfiddle.net/wobrrrac/
