### ISSUE TITLE
How to get the selected row data with attributes

### ISSUE THREAD

**Issue by Prasadu112** [handsontable/handsontable#4702]
hello,
I'm new to this handsontable.. Can any one tell me how to get the values and the attribute from the selected rows..
Can anyone please help me this problem..

**Comment by AMBudnik** [comment]
Hi @Prasadu112 

Sure, that's not a problem.

**METADATA**
In Handsontable to get data and metadata you have a few methods:
1. [`getCellMeta`](https://docs.handsontable.com/pro/1.15.0/Core.html#getCellMeta) It takes all the metadata on a cell. You need to share row, col parameters to make it return a value.
2. [`getCellMetaAtRow`](https://docs.handsontable.com/pro/1.15.0/Core.html#getCellMetaAtRow) The same method for a whole row. It takes a row index as an attribute.

**DATA**
1. [`getData`](https://docs.handsontable.com/pro/1.15.0/Core.html#getData) It returns the visual representation of the whole table. 
2. [`getDataAtCell`](https://docs.handsontable.com/pro/1.15.0/Core.html#getDataAtCell) the same method for a single cell. You need to share row, col parameters to make it return a value.
3. [`getDataAtCol`](https://docs.handsontable.com/pro/1.15.0/Core.html#getDataAtCol) The same method for a whole column. It takes a column index as an attribute.
4. [`getDataAtRow`](https://docs.handsontable.com/pro/1.15.0/Core.html#getDataAtRow) The same method for a whole row. It takes a row index as an attribute.
5. [`getDataAtProp`](https://docs.handsontable.com/pro/1.15.0/Core.html#getDataAtProp)A method that return data (with an array) of defined property
5. [`getDataAtRowProp`](https://docs.handsontable.com/pro/1.15.0/Core.html#getDataAtRowProp)A method that return data (with an array) of defined property for a single row. Parameters are property name and row index.

Additionally, when you want to get data from a selected cell you use the [`getSelected`](https://docs.handsontable.com/pro/1.15.0/Core.html#getSelected)method that returns an array of coordinates that can be used in one of the above methods.

**Comment by Prasadu112** [comment]
Thank u so much @AMBudnik.

**Comment by AMBudnik** [comment]
You're welcome.

**Comment by AbdulKather2025** [comment]
how to get the row index when doing oninsertrow?
