### ISSUE TITLE
Not able to delete content while editing and leave it blank after editor gets closed

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4703]
### Description

We are not able to delete the content while editing and leave it blank after the editor gets closed. 

### Steps to reproduce

1. Open dropdown editor
2. Delete the content with <kbd>Backspace</kbd>
3. use <kbd>Enter</kbd> to confirm the new value

**Result:**
last value is reverted

**Expected:**
cell should stay empty

![gif](https://user-images.githubusercontent.com/10757813/34558515-be54f060-f13e-11e7-9260-a3d5780aed87.gif)

The result is the same when we want to click somewhere outside the cell to close it.

### Demo

https://handsontable.com/docs/dropdown-cell-type/#overview

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: Chrome 63
* Operating System: Windows 10

inform [forum](https://forum.handsontable.com/t/gh-4703-disable-choice-in-dropdown-cell-type-by-outside-click/4967)

**Comment by jangrahul** [comment]
hi, tahnks for the great library, any progress on the fix.. ?

**Comment by AMBudnik** [comment]
Works the same in v5.0.1

**Comment by caseahr** [comment]
Would really like this fixed, if possible.  It seems to me that it just needs to have an option to NOT select the first item by default when the dropdown is opened while the table cell associated with it is blank.  The dropdown editor in a blank cell should force the user to select intentionally by either keying down to the first option or clicking with the mouse.  this should be specific to blank cells.  If a value exists in the cell, then by all means auto-select.

**Comment by vmagalhaes** [comment]
Any updated of that?

**Comment by AMBudnik** [comment]
Sorry, the issue hasn't been scheduled yet

**Comment by oguzhankahyaoglu** [comment]
Any progress about this issue?

**Comment by AMBudnik** [comment]
Here is our Roadmap for this and next month https://github.com/handsontable/handsontable/milestone/111

**Comment by mpeula-pe** [comment]
Any update on this issue?

**Comment by AMBudnik** [comment]
@mpeula-pe not yet. You can partially solve the issue by checking if the editor is empty https://jsfiddle.net/handsoncode/jrg7d1ch/ but then it does not work when you have an empty editor and want to select a value from the list.
A temporary workaround would be to overwrite the DropdownEditor

**Comment by swistach** [comment]
Hi @jangrahul, @caseahr, @vmagalhaes @oguzhankahyaoglu, @mpeula-pe,
there is one more workaround: https://jsfiddle.net/mue5y863/

**Comment by aninde** [comment]
Still valid on latest v12 build https://jsfiddle.net/cL3snu24/.

**Comment by budnix** [comment]
I think that it works that way by design. A dropdown editor once triggered is obligated to choose one of the values provided in the `source` array. To implement such behavior I would recommend adding an empty string to the `source` array or using the Autocomplete editor with the `filter: false` option https://jsfiddle.net/97knwbxh/2/.

**Comment by AMBudnik** [comment]
As mentioned above by @budnix if we would like to have the ability to select an empty cell we should either use the `autocomplete` with `filter: false` option or add an empty string to the list of choices. We will make sure that this information is also mentioned in the documentation.

Thank you all for sharing your feedback.
