### ISSUE TITLE
IME donot convert 1st character with copyPaste false option 

### ISSUE THREAD

**Issue by tacnoma** [handsontable/handsontable#4704]
### Description

Hi guys, I tried ver. 0.35.0 to solve #839  and it seems working well.
I am so grateful for the many efforts.

But unfortunately, I found that this issue reproduced with `copyPaste: false` option.
This is just a report, and I have not found the cause of this problem, sorry.

(this is almost copy of https://github.com/handsontable/handsontable/issues/839#issuecomment-353860303)

### Steps to reproduce
1. initialize Handsontable with copyPaste false option
2. start Japanese IME
3. select a cell by one click or arrow keys
4. type a word what should be converted by multi characters

### Demo
To confirm, try this jsfiddle with IME for multi-byte languages(like Japanese) https://jsfiddle.net/tacnoma/ux9at5wx

The upper table is reproducing the bug.

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: Chrome 63
* Operating System: Mac OS X 10.12.6

IME: Google Japanese Input 2.20

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/4662

**Comment by AMBudnik** [comment]
Thank you @tacnoma

**Comment by AMBudnik** [comment]
Hi @tacnoma 

the issue should be solved in v 4.0.0
Please update and let me know if it works for you.
https://github.com/handsontable/handsontable/issues/4662

**Comment by tacnoma** [comment]
I confirmed it works very well with 4.0.0! Thanks a lot.

**Comment by AMBudnik** [comment]
I'm so happy to hear that, thanks @tacnoma
