### ISSUE TITLE
Support react server side rendering

### ISSUE THREAD

**Issue by nvqchau** [handsontable/handsontable#4705]
### Description
Hi,
I develop a website application by using MERN stack. But there is an error (document is not defined) and I guess this library does not support SSR (Server Side Rendering), am I right? If true, do you have any plan for this. Or else, please guide me.

Thank you,

### My environment
* Handsontable version: Latest
* React: MERN stack with SSR

**Comment by AMBudnik** [comment]
Hi @nvqchau 

we did not test it with MERN but I suppose that it may have some issues.
I am just not sure if https://github.com/handsontable/react-handsontable is not a better place for this feature request.
