### ISSUE TITLE
Property `numericFormat` should be used only for formatting displayed cell values

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4706]
### Description
We should definitely use `numericFormat` for formatting **only** displayed data. 

Within #4396 @jacob-s-son described very well how part of `Core` parsing numeric data works. It treats some of input data by `numbro`, otherwise use `parseFloat`. As the result differences occur when we:

* use various types of formatting
* open an editor by pressing enter key and double click

Some times ago team decided that numbers added to a table by editor should be written in "float like" format. We should consequently remove residues of formatting inside editors and it’s effects. Every change should be tested with `copy & paste` and `autofill` feature.

### Steps to reproduce case 1
**Double click on cell containing data**

- default formatted numeric cell

1. Open cell with index `0, 1` (displayed `7001`) by double click.
2. Press enter or just click anywhere.
3. As the result value of cell will change to `70005`.

**Note**: After double click you can see comma as a separator. After enter press you can see dot as a separator.

- specific formatted numeric cell (culture `en-US`)

1. As described above, just starting with double click on cell with index `0, 2` (displayed `$7,000.50`).

### Steps to reproduce case 2
**Double click on an empty cell**

- default formatted numeric cell

1. Open an empty cell at column with index `1`.
2. Enter `20,5` value.
3. Press enter or just click anywhere.
4. As the result value of cell will become `205`.

- specific formatted numeric cell (culture `en-US`)

1. As described above, just starting at cell at column with index `2`.

### Steps to reproduce case 3
**Input string data containing numbers**

1. Open an empty cell at column with index `1`.
2. Enter `aaa78` value.
3. Press enter or just click anywhere.
4. As the result value of cell will become `aaa78`.

5. Try above steps, just starting at cell at column with index `2`.
6. As the result value of cell will become `78`.

### Demo

Base (`0.35.0`): http://jsfiddle.net/wojciech/2adb2at5
Similar problems, but other steps (`0.32.0`): http://jsfiddle.net/wojciech/bq83du9k

### Your environment
* Handsontable version: 0.35.0, <= 0.32.0
* Browser Name and version: Google Chrome 63.0.3239.84
* Operating System: macOS High Sierra 10.13.2

**Comment by krzysztofspilka** [comment]
@wszymanski Have we already added an information on how the comma and period symbols are handled? For instance, for the below, it should be clear what happens when we enter `6,2` and submit - what we really save (floating point) and why it matters.

```
type: 'numeric',
        numericFormat: {
          pattern: '0,0.00 $',
          culture: 'de-DE'
        }
```


#documentation

**Comment by wszymanski** [comment]
Oh, you reminded me to add the documentation to https://docs.handsontable.com/demo-numeric.html.
