### ISSUE TITLE
htContextMenu z-index values out of sync

### ISSUE THREAD

**Issue by rayokao** [handsontable/handsontable#4707]
### Description
CSS for .htContextMenu differs between the minified and the nonminified versions.

Nonminified: z-index:1060
Minified: z-index:10

### Steps to reproduce
1. Download source and compare files

### Your environment
* Handsontable version: 1.15.0

**Comment by AMBudnik** [comment]
Thank you for sharing @rayokao 

I can see that version 1.11.0 was the one that made the change.

**Comment by AMBudnik** [comment]
Hi @rayokao 

I just got a feedback for one of our developers.
It looks like the behavior is intended as we are using this https://github.com/NMFR/optimize-css-assets-webpack-plugin (which is using https://github.com/ben-eb/cssnano) and the cssnano is the one responsible for this change.
Here's a quick tutorial on how it works and how it should be done like this https://github.com/ben-eb/cssnano/tree/master/packages/postcss-zindex#example

However, thank you very much for your effort to share the issue/

**Comment by dinkar2010** [comment]
htContextMenu {
          position: absolute !important;
          z-index: 11000 !important; /*needs to be higher than 10000 - z-index for Twitter Bootstrap modal (#1569)*/
        }

**Comment by dinkar2010** [comment]
.htContextMenu {
          position: absolute !important;
          z-index: 11000 !important; /*needs to be higher than 10000 - z-index for Twitter Bootstrap modal (#1569)*/
        }
