### ISSUE TITLE
Support for the selection of non-consecutive cells

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4708]
### Description

This issue is about making support for the selection of non-consecutive cells. The first step to complete this new feature is to build a prototype which works visually without any glitches. The selection shouldn't break any previous functionality.

**Comment by AMBudnik** [comment]
related https://github.com/handsontable/handsontable/issues/2119

**Comment by krzysztofspilka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Selection of non-consecutive cells/rows/columns](https://trello.com/c/syKGe2VN/19-selection-of-non-consecutive-cells-rows-columns)

**Comment by budnix** [comment]
## New API

* `hot.getSelectedLast()` Returns the last coordinates applied to the table as an array `[row, col, endRow, endCol]`;
* `hot.getSelectedRangeLast()` Returns the last coordinates applied to the table as a `CellRange` object;
* `hot.alter('remove_row', [[1, 4], [10, 1]])` Supports removing non-consecutive rows. Instead of passing row index we can pass an array of arrays where the first item is row index where the row will be removed from and at the second index is 'amount', count of rows to be removed;
* `hot.alter('remove_col', [[1, 4], [10, 1]])` Same as above but for columns. Only removing actions support that new feature.

## Braking Changes (methods and options):
* Previously `hot.selection.empty()`, now `hot.emptySelectedCells()`;
* Changed selection colors:
    - area borders, was #89aff9 -> has #4b89ff
    - area background, was #b5d1ff -> has #005eff
    - current selection border, was #5292f7 -> has #4b89ff
* Removed `multiSelect` setting replaced with `selectionMode: 'single'`;
* Added new option `selectionMode` which can be set as `'single'` (previously as `multiSelect: false`), `'range'` (previously as `multiSelect: true`) and `'multiple'` (new non-consecutive mode);

## Braking Changes (hooks):
 * `afterSelectionEnd` 
   - _previously_: `afterSelectionEnd(rowStart, columnStart, rowEnd, columnEnd)`
   - _now_: `afterSelectionEnd(selectedCells)` where `selectedCells` looks like:
```js
      [
        {
          from: {row: 5, col: 0},
          to: {row: 8, col: 0}
        },
        {
          from: {row: 10, col: 3},
          to: {row: 12, col: 4}
        }
      ]
```
 * `afterSelectionEndByProp`
   - _previously_: `afterSelectionEndByProp(rowStart, columnStartProperty, rowEnd, columnEndProperty)`
   - _now_: `afterSelectionEndByProp(selectedCells)` where `selectedCells` looks like:
```js
      [
        {
          from: {row: 5, col: "id"},
          to: {row: 8, col: "id"}
        },
        {
          from: {row: 10, col: "city"},
          to: {row: 12, col: "address"}
        }
      ]
```
 * `afterSelection`
   - _previously_: `afterSelection(rowStart, columnStart, rowEnd, columnEnd, preventScrolling)`
   - _now_: `afterSelection(selectedCells, preventScrolling)` where `selectedCells` looks like:
```js
      [
        {
          from: {row: 5, col: 0},
          to: {row: 8, col: 0}
        },
        {
          from: {row: 10, col: 0},
          to: {row: 12, col: 0}
        }
      ]
```
 * `afterSelectionByProp`
   - _previously_: `afterSelectionByProp(rowStart, columnStart, rowEnd, columnEnd, preventScrolling)`
   - _now_: `afterSelectionByProp(selectedCells, preventScrolling)` where `selectedCells` looks like:
```js
      [
        {
          from: {row: 5, col: "id"},
          to: {row: 8, col: "id"}
        },
        {
          from: {row: 10, col: "city"},
          to: {row: 12, col: "address"}
        }
      ]
```

**Comment by dmt0** [comment]
Did `hot.selection.selectedHeader` move as well as a result of this change?
