### ISSUE TITLE
Headers selection glitches when multi-selection is disabled

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4711]
### Description

Headers selection glitches when multi-selection is disabled. In that case, row and column header are highlighted correctly but they changed their selection while mouse movement. They behave as if the multi-selection was still enabled.

### Steps to reproduce

1. Go to the demo provided below and try to select multiple cells.

### Demo

https://jsfiddle.net/3gas9z6q/7/

![kapture 2018-01-11 at 10 47 15](https://user-images.githubusercontent.com/571316/34819015-d74f463c-f6bc-11e7-95dc-f338d1002923.gif)

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: any
* Operating System: any

**Comment by budnix** [comment]
I've found another issue related to `multiSelect` option. The multi-selection randomly appears in some scenarios.

![kapture 2018-01-11 at 11 31 53](https://user-images.githubusercontent.com/571316/34821217-460493d8-f6c3-11e7-9f26-a57d382592c1.gif)

**Comment by AMBudnik** [comment]
@budnix 

This issue seems to be gone. Please check https://jsfiddle.net/handsoncode/vvkpxmp3/

I've changed the 

`multiSelect: false,`

to 
  `selectionMode: 'single'`

**Comment by budnix** [comment]
Yep, this issue is no longer exist.

**Comment by AMBudnik** [comment]
Thanks for checking @budnix
