### ISSUE TITLE
Sorting cannot be undone when the persistent state is enabled

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4712]
### Description

Sorting cannot be undone when the persistent state is enabled.

### Steps to reproduce

1. Sort first column;
2. Refresh the page by clicking the "Run" button to make sure that `PersistentState` plugin works correctly.
3. Return to the original data order by clicking the same header as previous;
4. Click the "Run" button. In result sorting, is still applied to that column which shouldn't.

### Demo

https://jsfiddle.net/3gas9z6q/8/

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
The issue is no longer replicable in v 5.0.1
