### ISSUE TITLE
Child rows (show extra / detailed information) in handsontable? 

### ISSUE THREAD

**Issue by xeoshow** [handsontable/handsontable#4714]
### Description

Hello,

I am using Handsontable Community Edition, and just would like to have the similar function for my web app as below:
https://datatables.net/examples/api/row_details.html
 
Previously I was using datatables and now changed to handsontable, all others seems great, while did not find feature in the Handsontable Community Edition as above link shows, which can expand the row and show extra information.

How should I do in Handsontable Community Edition? Great thanks!

### Demo

https://datatables.net/examples/api/row_details.html

### Your environment
* Handsontable version: 0.35.0 (Handsontable Community Edition)
* Browser Name and version: chrome
* Operating System: windows

**Comment by AMBudnik** [comment]
Hi @xeoshow  the option is available in Handsontable PRO. It's called nested Rows. Here's a demo https://docs.handsontable.com/pro/1.15.0/demo-nested-rows.html

**Comment by xeoshow** [comment]
Thanks for kind help, currently I am not yet ready to buy Pro version, so just would like to know if there is any workaround solution in the community version? 
Thanks v much!

**Comment by AMBudnik** [comment]
I do not think that it would be possible in CE version as hiding rows is also a PRO feature and without show/hide option there's no way to get the same effect.

**Comment by AMBudnik** [comment]
Sorry, but this would need a lot of coding to do the same in CE version.

**Comment by xeoshow** [comment]
@AMBudnik OK, thanks for your kind help as well. :-)
