### ISSUE TITLE
getdata from one handsontable and posting it to another handsontable

### ISSUE THREAD

**Issue by chethan1095** [handsontable/handsontable#4721]
get ajaxdata from one handsontable and linkit to another handsontable through a button

**Comment by AMBudnik** [comment]
Hi @chethan1095 

I know your goal, but where have you ended with the progress? What you already implemented?

**Comment by chethan1095** [comment]
hi @AMBudnik 
what i am trying to do is i have two handsontable from first handsontable i want to link data to second handsontable how to do it..... 2nd handsontable is on modal

**Comment by chethan1095** [comment]
![link xcm client to ext client](https://user-images.githubusercontent.com/33021783/35039177-1324e622-fba3-11e7-8962-154005ba2043.png)
![modal of link ext client](https://user-images.githubusercontent.com/33021783/35039181-1475726c-fba3-11e7-9c87-9352cc80fa0f.png)

**Comment by AMBudnik** [comment]
Here's a similar demo http://jsfiddle.net/78cm8rzc/

The key to key the data in the second table (the one in the window) is to update its data using `afterChange` hook on the first table.
