### ISSUE TITLE
i  want to use  this handsontable 

### ISSUE THREAD

**Issue by a408228147** [handsontable/handsontable#4722]
so I need to cite which js ,it can to work.thanks.

**Comment by AMBudnik** [comment]
Hi @a408228147 

Can you tell me a little bit more about your request? What exactly are you struggling with in the implementation?

**Comment by a408228147** [comment]
I let manualRowResize is true ,but The emergence of a scroll bar , i don't need it .

**Comment by a408228147** [comment]
i  want  to set   <td>  some style , so  what  can i get it <td> this object.  my function is   
var td = $("tbody")[0].rows[row].cells[col]  ,$(td).css("color", "red”);  but html is only  show forty-two <tr>
if i use my function to find  row is fifty-five ,they will say  can't find is <td> ,so How do I solve.

**Comment by a408228147** [comment]
the  table  all the time  refresh ,so i set some style  will be not.

**Comment by AMBudnik** [comment]
The best way to maintain the styles is to but them inside `cells` method. 
Here is a live example http://jsfiddle.net/swx43n2p/
