### ISSUE TITLE
EnterMoves function FF issue

### ISSUE THREAD

**Issue by timabilov** [handsontable/handsontable#4727]
- When i am describe **plain** _enterMoves_ as a function FF cannot find _event_ variable there. Works without function.
This must work also with function

### Steps to reproduce
1. Just describe enterMoves with some function(with arg or without doesn't matter)
2. When you actually press enter on cell it stuck with event  is not defined

http://jsfiddle.net/pja50uh2/1/

### Your environment
* Handsontable version: 0.34.5, 0.35.0
* Browser Name and version: FF 57
* Operating System: MAC os

So sad that there is no any compatibility.
I was changed  v from 0.34.5 to 0.35.0 and there is more issues that i have to fix. I think you must be focused on regression tests now although library is way big and for sure not enough community help - i understand.

**Comment by AMBudnik** [comment]
Thank you for sharing the issue. In the docs, we state that it should work with a function and currently it does not for the Firefox. Surprisingly it works on Edge.

ps. thanks for spotting the version that changes the behavior. That is super useful.

**Comment by AMBudnik** [comment]
Still works the same in v 5.0.1.

**Comment by AMBudnik** [comment]
Replicable in v `6.0.1`. 

`Inform Gr # 19574`

**Comment by arfis** [comment]
Are there any plans on fixing this issue soon or is there a workaround? Thanks

**Comment by AMBudnik** [comment]
Hi @arfis 

you can use the `afterDocumentKeyDown` hook to change the behavior for <kbd>Enter</kbd> key
Demo: http://jsfiddle.net/m7Ld9r5p/

**Comment by AMBudnik** [comment]
I've tried it with FF 75 and Handsontable v 7.4.2 http://jsfiddle.net/ukbsg6Lv/ and it works well.
@pnowak can you check this on your device?

**Comment by pnowak** [comment]
In my device works well, too.

**Comment by AMBudnik** [comment]
Great, thanks. 
I'm closing this as solved.
@timabilov I hope that it works for you as well
