### ISSUE TITLE
A single merge cell is merged too much, and there will be no smooth rolling

### ISSUE THREAD

**Issue by cuijian-dexter** [handsontable/handsontable#4728]
### Description

A single merge cell is merged too much, and there will be no smooth rolling.
such as：
{row：0，col：0，rowspan:1，colspan：1000}
### Steps to reproduce

1.Data（{ row：0，col：0，rowspan:1，colspan：1000 } ）is placed in a table
2.Rolling scrollbar is unfluency

### Your environment
* Handsontable version:0.35.0
* Browser Name and version:chrome 60.0.3112.101
* Operating System:windows 10

**Comment by AMBudnik** [comment]
Hi @cuijian-dexter 

Thank you for report.

Is this issue the same as https://github.com/handsontable/handsontable/issues/4421? It sounds really alike. 

If something at https://github.com/handsontable/handsontable/issues/4421 is missing please leave a comment/suggestion.

**Comment by cuijian-dexter** [comment]
Excuse me, Are you rewriting the mergeCells plugin？

**Comment by AMBudnik** [comment]
Yes, we are. It takes a lot of time so there's no deadline. However you can check this Trello card for updates https://trello.com/c/SPxx77h0/85-re-write-of-merge-cells-4214

**Comment by cuijian-dexter** [comment]
@AMBudnik  Thank you for your help.Look forward to a new version
