### ISSUE TITLE
How can I set keyboard hotkey for "row_above/row_below...” contextmenu ?

### ISSUE THREAD

**Issue by wck821829906** [handsontable/handsontable#4729]
No idea for setting hotkey for "row_above/row_below...” contextmenu, ask for help,thanks

**Comment by AMBudnik** [comment]
Hi @wck821829906 

have you already made an event logic in the [`afterDocumentKeyDown` ](https://docs.handsontable.com/pro/1.15.0/Hooks.html#event:afterDocumentKeyDown) hook?

If you did the next step would be to call [`alter`](https://docs.handsontable.com/pro/1.15.0/Core.html#alter)method with the `insert_row` value. The index can be taken from the [`getSelected`](https://docs.handsontable.com/pro/1.15.0/Core.html#getSelected) method

**Comment by wck821829906** [comment]
@AMBudnik Thanks for your respond, I have figured out the solution just like what you say...
