### ISSUE TITLE
Dropdown list in cell.

### ISSUE THREAD

**Issue by mariraja** [handsontable/handsontable#473]
Hi,

I am new to jquery-handsontable. 
I am trying to add a HTML dropdown list in Handsontable cell, the dropdownlist options will vary for each row based on an "id" which we pass.

So for this case scenario kindly provide a sample code.

**Comment by AMBudnik** [comment]
I think that there demo can be helpfull: http://codepen.io/js-ziggle/pen/vEwdKq?editors=001
Please select 'Steve' to see changes.
