### ISSUE TITLE
Unable to change dropdown source on selecting a value from another dropdown.

### ISSUE THREAD

**Issue by anushrigupta** [handsontable/handsontable#4730]
I am using the evaluation version of Handsontable. I am trying change the source of one dropdown on selecting a value from another dropdown. I have tried using the below:

 modifyData: function (row, column, valueHolder, ioMode) {
                            if (this.toPhysicalColumn(column) === 38 && ioMode === 'set') {
                                var estimateTypes = getEstimateType(valueHolder.value.split(" ").join(""));
                                **var estimateTypeCellData = hot.getCellMeta(row, column);
                                estimateTypeCellData.source = estimateTypes;**
                            
                            }
                        },
--------------------------------------------------------------------------------------------------------------

 modifyData: function (row, column, valueHolder, ioMode) {
                            if (this.toPhysicalColumn(column) === 38 && ioMode === 'set') {
                                var estimateTypes = getEstimateType(valueHolder.value.split(" ").join(""));
                                **hot.setCellMeta(row, 36, "source", estimateTypes);**
                               
                            
                            }
                        },

However, both the solutions are not working.
 What is it that I am doing wrong?

I am using Chrome as the browser.

**Comment by AMBudnik** [comment]
Hi @anushrigupta 

I highly encourage to read our blog post about cell dependencies at https://handsontable.com/blog/articles/expand-your-app-with-cell-dependencies

In the `Select-dependent cells` paragraph, you have a demo that uses `select` cell type to do the same. `Dropdown` and `autocomplete` use the same structure as `select` so it shouldn't be tough to make an example with `dropdown` as well.
