### ISSUE TITLE
Duplicate columns when moving a column

### ISSUE THREAD

**Issue by jeremys18** [handsontable/handsontable#4731]
I have a hands on table with movable columns. The columns move fine but when I move the very last column it doesn't move, it duplicates. Again, if I move any other column it works.

Here's the table def with dummy headers:

hot = new Handsontable(container, {
        data: data.AccountMaps,
        rowHeaders: true,
        colHeaders: ['', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H, 'I', 'J', 'K'],
        colWidths: [0, 120, 150, 150, 360, 80, 130, 130, 130, 130, 80, 150],
        columns: [
            {
                data: 'AA',
                editor: false,
                readOnly: true
            },
            {
                data: 'A',
                editor: false,
                readOnly: true
            },
            {
                data: 'B',
                editor: false,
                readOnly: true
            },
            {
                data: 'C',
                editor: false,
                readOnly: true
            },
            {
                type: 'dropdown',
                data: 'D',
                source: $.map(data.Taxonomies, function (key) { return key.Value })
            },
            {
                renderer: eRenderer,
                data: 'E',
                editor: false,
                readOnly: true
            },
            {
                renderer: TRenderer,
                data: 'F'
            },
            {
                renderer: TRenderer,
                data: 'G'
            },
            {
                renderer: TRenderer,
                data: 'H'
            },
            {
                renderer: TRenderer,
                data: 'I'
            },
            {
                renderer: TRenderer,
                data: 'J'
            },
            {
                type: 'text',
                data: 'K'
            }
        ],
        hiddenColumns: {
            columns: [0],
            indicators: false
        },
        maxRows: data.numberOfRows,
        filters: true,
        afterGetColHeader: addInput,
        beforeOnCellMouseDown: doNotSelectColumn,
        manualColumnMove: true,
        manualColumnResize: true,
    });

So in this example, if I move column K anywhere it will duplicate the entire column to the right, values and all. 

This is not something I expect to happen when I move a column.

Also if I execute hot.toVisualColumn(11) it gives back 11 no mater where I move the column. But 11 is no longer the correct column number. 

I have the latest pro version from the site so it's not an outdated version.

**Comment by AMBudnik** [comment]
Hi @jeremys18 

I have used the code to create a demo http://jsfiddle.net/ux8xup5g/
Some elements are missing
- data
- custom renderers
- addInput
- doNotSelectColumn

However, I have managed to get an odd behavior when we move the `K` column. Do you get the same behavior in your app?

**Comment by jeremys18** [comment]
That's it! If I move k in your demo it duplicates and turns into a copy of where I moved it.

But why?

**Comment by AMBudnik** [comment]
Thank you for confirming. It's hard to tell what can cause the issue but I guess that maybe we are taking the wrong indexes to replace the data.

![gif](https://user-images.githubusercontent.com/10757813/35209985-b4e010c6-ff50-11e7-8714-52676eb54d66.gif)

In the following demo column `G` gets data from column `K`. It only happens for the last column.
And if we remove `columns` settings it works fine

http://jsfiddle.net/6beL2jjo/

**Comment by AMBudnik** [comment]
The issue was posted by our developer at https://github.com/handsontable/handsontable/issues/4470

**Comment by jeremys18** [comment]
The issue you linked is almost 6 months old and still open. Is this something that won't be resolved?

**Comment by AMBudnik** [comment]
There were many other issues to resolve and we wanted to fix issues that are related to refactors (merge cells, comments).
I have updated https://github.com/handsontable/handsontable/issues/4470
The first parameter of `afterColumnMove` returns false data. I think that this can be the cause and now when we know it it will be easier to fix. I will try to boost the 'fixing process'.

**Comment by AMBudnik** [comment]
Hey @jeremys18 

We just fixed an issue related to yours. Please update to 8.0.0-beta1 and check if it solved for you as well.

Below are the resources

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```

And this is how you can download the beta from NPM

`npm i handsontable@beta`
