### ISSUE TITLE
Can't get cell of date type on the (moment js's) relative time format

### ISSUE THREAD

**Issue by Bartaf83** [handsontable/handsontable#4735]
I need dates be displayed on the relative time format (e.g "2 days ago").

I have tried setting the dateFormat as indicated in the moment.js documentation : 
`dateFormat: moment().startOf('day').fromNow(),`
but the cell turns red and what is displayed on it looks wrong [demo](https://i.imgur.com/zBKG4JX.gifv)

but when i set dateFormat to 'DD/MM/YYYY' it works very well [demo2](https://i.imgur.com/qt7Skba.gifv) (this shows that there is no problem caused by the date input format)

I have tried pass the `onSelect` function as in [this answer](https://stackoverflow.com/a/38579281/1705922).
```
onSelect: function(date) {
   console.log('%c date : ' + date);
}
```
 in the `datePickerConfig` but the date argument is always undefined and i also don't know how to get the reference to the `field `element as mentionned in that question (they used pikaday seperatly and not in the handsontable) 

I also tried the  `toString `function as mentionned in the Pikaday documentation but it didn't trigger.

**Comment by AMBudnik** [comment]
As I suppose your data looks like
![zrzut ekranu 2018-01-19 o 15 26 48](https://user-images.githubusercontent.com/10757813/35155206-3e9ca4c6-fd2d-11e7-9a12-d453d46058da.png)
and you would like it to be converted to
![zrzut ekranu 2018-01-19 o 15 27 06](https://user-images.githubusercontent.com/10757813/35155213-422c765c-fd2d-11e7-8d6c-fcc653b0c850.png)
If you want to process the data in the different way that is displayed you should create a custom renderer.

**Comment by Bartaf83** [comment]
I've actually created a custom rendrer for date cells but the copy / paste didn't work with it, that's why i've tried the build-in date rendrer.

**Comment by AMBudnik** [comment]
Can you share the recent progress via demo? Maybe there's a render() call missing
