### ISSUE TITLE
Help needed: Confirm Portuguese translation

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4736]
## Welcome community!
We have just received a translation for the **Portuguese** language at the https://github.com/handsontable/handsontable/pull/4763.

Please help us to confirm it. 
**5 votes+** will allow us to confirm the translation and pull the changes.

Thanks!

**Comment by krzysztofspilka** [comment]
@AMBudnik and there's a new label #helpneeded

**Comment by AMBudnik** [comment]
Hi guys! The Portuguese language has been officially added to Handsontable version 1.17.0+

Thank you @juliozuppa for contributing and
@luciano-schirmer @freitasmurillo @ElHoro @allyssonm @renatotbueno @rennerw @mensonones for confirmations

**Comment by luciano-schirmer** [comment]
Awesome! I updated in my application that uses Portuguese language. Everything working great, congrats for the handsontable team.
