### ISSUE TITLE
column.data function receives Window as "this" instead of ColumnSettings or GridSettings or DataMap

### ISSUE THREAD

**Issue by pmunin** [handsontable/handsontable#4740]
### Description

When I specify in settings provider functions like column.data or column.cells, in the body of the function developer expects/needs some way to get a context Handsontable instance that this executed for. In **column.cells** function this=ColumnSettings has all information about the cell metadata is retrieved for, including row,col and instance of Handsontable. I expect the same behavior for **column.data** function, however it received global window as this and I see no way to receive a Handsontable context it's executed in. (getelementbyId(...) - not an option for me, as i have multiple instances of ht with no ids).

### Steps to reproduce

1. create hotSettings object providing column objects like {title:"Column 1", data:function(...){...},cells:function(...){...}}
2. in data function use console.log("Column data context:" this,arguments);
3. see there are no objects in output that can link you with handsontable instance.

### Demo

https://jsfiddle.net/pmunin/yz1Lb2Lk/
(see console messages)

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: chrome 64..., x64
* Operating System: Ubuntu 17.10 and Windows 7 SP1

**Comment by AMBudnik** [comment]
Thank you for sharing the issue @pmunin

**Comment by AMBudnik** [comment]
Please track changes to https://github.com/handsontable/handsontable/issues/4929 for updates
