### ISSUE TITLE
How to use JS to control the style of a cell?

### ISSUE THREAD

**Issue by setWan** [handsontable/handsontable#4745]
Hi@AMBudnik 
How to use JS to control the style of a cell?
Can the width of a cell be controlled by a percentage?

**Comment by AMBudnik** [comment]
Hi @setWan 
Handsontable does not support percentage values yet.
To style a cell, I recommend `cells` method. Here's an example of `cells` used to style the whole table http://jsfiddle.net/swx43n2p/

**Comment by setWan** [comment]
Hello @AMBudnik 
How to use JS to control the style of a cell?Or I can custom validator?

**Comment by AMBudnik** [comment]
A validator is used to mark cells valid/invalid which is done by the `htInvalid` class. If you wish to change the way cells look while they're invalid you can overwrite the class or change the class via 1
[`invalidCellClassName`](https://docs.handsontable.com/pro/1.15.0/Options.html#invalidCellClassName) option.
