### ISSUE TITLE
Rendering inside of flex box

### ISSUE THREAD

**Issue by shablenko** [handsontable/handsontable#4748]
Hi, i am working on complex application with a lot of flex boxes, i am using handsontable with react and bootstrap (render inside of modals or collapsible e.t.c.) and i`m facing troubles with scrollbars which are appearing randomly while rendering table and dissapear after any actions on table (like resize column).

It is very hard to reproduce, but i almost managed to do a [demo](https://jsfiddle.net/xrgx8dvw/6/), the issue in jsfiddle is very close to my case, but my case is a bit different:

1) it reproduced only in IE11(maybe lower, but i dont care about lower versions);
2) table content is overlapped by scrollbars as in example, but they won`t dissaper after any action (i.e. resize)

### My environment
* Handsontable version: **handsontable@0.35.0, handsontable-pro@1.13.1**
* Browser Name and version: **IE 11**
* Operating System: **Windows 10 x64**

**Comment by AMBudnik** [comment]
Hi @shablenko 

we have already discussed this subject in a few posts.
Please take a look at this one (table visibility) https://github.com/handsontable/handsontable/issues/4579
and this one (flexbox container + IE 11) https://github.com/handsontable/handsontable/issues/4598

**Comment by shablenko** [comment]
I saw there only one possible fix, and it did not work for me

**Comment by AMBudnik** [comment]
The issue https://github.com/handsontable/handsontable/issues/4598 hasn't been fixed yet. I think that we will be able to get back to this subject while doing the [layers project](https://trello.com/c/Dldqj6AT/87-rewrite-layers-to-improve-scrolling-4632)
