### ISSUE TITLE
Sorting time column is ignoring am/pm

### ISSUE THREAD

**Issue by JustinCreasy** [handsontable/handsontable#4751]
### Description
When a column of type: "time" and a timeFormat of "h:mm:ss a" is used the column does not sort correctly. It ignores whether a time is am or pm. I believe this happens with other timeFormat's as well but the format mentioned here is what is in my JSFiddle.

### Steps to reproduce
1. go here: https://jsfiddle.net/jcreasy/55akp71w/9/
2. Attempt to sort the "Time" column

### Demo
https://jsfiddle.net/jcreasy/55akp71w/9/

### Your environment
* Handsontable version: Pro version: 1.15.1 (I have also seen in Free edition v0.35)
* Browser Name and version: Tested in Chrome (63), FF (57), and Edge 38
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing @JustinCreasy 
It is definitely something we need to consider.

**Comment by vtjc2002** [comment]
Hi, we are facing the same issue.  Any update on this?

**Comment by AMBudnik** [comment]
I am sorry but there is no update on that issue yet.

**Comment by AMBudnik** [comment]
Works the same (sorting alphabetically, not by value) in `8.0.0-beta1` official https://jsfiddle.net/fauy0t52/

**Comment by adrianszymanski89** [comment]
Hi, @JustinCreasy  and @vtjc2002 I am happy to announce that this issue is fixed in v14.4.0.

Related pull request: https://github.com/handsontable/handsontable/pull/10956

Release notes: https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-4-0

Thank you again for sharing the report!
