### ISSUE TITLE
rowHeights option does not work for Chinese

### ISSUE THREAD

**Issue by superpig** [handsontable/handsontable#4752]
### Description
I set `rowHeights: 24` & `colWidths: 80` in handsontable option, when it was used for  Chinese, the height of Chinse is still over the height of row which I have set, but English text works well.

### Steps to reproduce
1. set `rowHeights: 24` & `colWidths: 80` option
2. input a long Chinese text in cell until it over the max lenght of row

### Demo
![image](https://user-images.githubusercontent.com/5066518/35424501-0d1a8870-028f-11e8-80d0-ef72b7be65ee.png)

### Your environment
* Handsontable version: 0.33.0
* Browser Name and version: Chrome Version 63
* Operating System: OS 10.11.6

**Comment by AMBudnik** [comment]
Hi @superpig 

Always if you add more content using `colWidths` the table ignores `rowHeights`. The main rule is that the content has to be visible.
Here's an example http://jsfiddle.net/pkvmm46e/

If I am missing anything please share a demo

**Comment by superpig** [comment]
@AMBudnik  Here's an example [http://jsfiddle.net/8uw67pbt/](url), they work differently

**Comment by AMBudnik** [comment]
Thank you for sharing the demo. That's an interesting case.
I have found a workaround (add a wrapper via custom renderer). Here you can test it http://jsfiddle.net/aL0j9ys0/
However, we should investigate it and check why it behaves differently.

**Comment by superpig** [comment]
I have found that it's style problem, here is my workaround: 
```css
.handsontable td {
  word-break: keep-all;
}
```

**Comment by AMBudnik** [comment]
Thanks for an update @superpig
