### ISSUE TITLE
Length of underlying table htCore gets messed up when adding rows.

### ISSUE THREAD

**Issue by wbcshow** [handsontable/handsontable#4755]
### Description

I have just recently started messing with handsontable and had created a button that when clicked would add several rows to the bottom of the current grid.  While testing the fixed header, I noticed that things would stop working after I clicked the button 4 or 5 times.

### Steps to reproduce

1. Click the button labeled Load more data.
2. An alert is displayed showing the row where the insert takes place. It should increment by 6.
3. Continue clicking the button and taking note of the alert message.

Things seem to work fine until I reach 22 (4,10, 16, 22).  At that point, instead of incrementing by 6 it starts to decrementing.

### Demo

https://jsfiddle.net/wbcshow/mcgrbu0n/8/

### Environment
* Handsontable version: - to be honest, I'm not sure.  I had a very difficult time getting the write files loaded.  I think I am using the latest version.
* Browser Name and version: IE 11
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @wbcshow 

can you resend the demo? It does not load anything besides a button.

**Comment by AMBudnik** [comment]
JSFiddle needs all the resources to be imported from `https` sites. You can just change the URL from `http` to `https`

**Comment by wbcshow** [comment]
Thanks. I added the s on each link and it did change the web console but I am still having issues with something.  Here is another screen print:
![image](https://user-images.githubusercontent.com/23139688/35514709-18d48a9c-04d5-11e8-8792-5f5b5535bae8.png)
I checked each url to make sure it was bringing back the js or css and found that these two were not:

https://handsontable.com/bower_components/ruleJS/dist/full/ruleJS.all.full.js
https://handsontable.com/bower_components/handsontable-ruleJS/src/handsontable.formula.js

Any idea what I'm doing wrong with these two lines?

**Comment by AMBudnik** [comment]
Hi @wbcshow 
Here's an updated demo https://jsfiddle.net/jyren2aq/
I just pushed the main resources `full.js` and `full.css` (+ latest jQuery) to the resources tab (left menu).

However, I do not see anything odd in the behavior and was able to get `46` alert doing the same clicking.

**Comment by wbcshow** [comment]
When I click the updated demo link:
 https://jsfiddle.net/jyren2aq/

I am taken to a blank screen.  Do you need to give me access or permissions to the link?

**Comment by wbcshow** [comment]
Okay I have given up on jsFiddle and created a codepen account.  I tried to recreate exactly what I had in the origianl jsfiddle.  Here is the link to the code pen:

https://codepen.io/wbcshow/pen/bLGxVP/

All that should happen is 6 rows should be added each time you click the button on the page.  It works for a few clicks but then stops working.  Please have a look and let me know what you find.

Thanks,
Steve...

**Comment by AMBudnik** [comment]
Hi @wbcshow 

Can you check if adding `renderAllRows: 'true'` solves the issue?
It helps on my local machine.

**Comment by wbcshow** [comment]
Yep that did the trick.  Thank you so much.

**Comment by AMBudnik** [comment]
Great. Thanks for the confirmation.
I am closing the ticket.
