### ISSUE TITLE
Help needed: Confirm Japanese translation

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4757]
## Welcome community!
We have just received a translation for the **Japanese** language at the https://github.com/handsontable/handsontable/pull/4756.

Please help us to confirm it. 
**5 votes+** will allow us to confirm the translation and pull the changes.

Thanks!

**Comment by hand-dot** [comment]
@AMBudnik Can you merge it?

**Comment by hand-dot** [comment]
@AMBudnik Thank you!

**Comment by AMBudnik** [comment]
Thank you for the PR @hand-dot 

and for your confirmations
@aeries06 @mrdShinse @nihen @Irs-yukawa 

The Japanese language has been officially added to Handsontable v1.17.0+
