### ISSUE TITLE
Unlimited right button menu

### ISSUE THREAD

**Issue by setWan** [handsontable/handsontable#4758]
When I new a Handsontable, I'll add a menu
![image](https://user-images.githubusercontent.com/31428016/35504587-6a6133e4-051e-11e8-9eed-0d0376ad3ea0.png)

**Comment by setWan** [comment]
HI@AMBudnik 
Is it possible to control the readOnly property of a cell with JS?

**Comment by AMBudnik** [comment]
Hi @setWan 

I am not sure what you would like to achieve. Can you tell me a little bit more about the `unlimited menu` concept? Would you like to update it with some larger amount of options?

When it comes to `readOnly` property you can manipulate it via `cell` or/and `cells` settings. More about it at [cells](https://docs.handsontable.com/pro/1.15.1/Options.html#cells)

**Comment by setWan** [comment]
Hi @AMBudnik 
I have many different forms. I will use tags to switch tables. When I switch, I will empty the current DOM object and re new a table, so that there will be multiple menus.

**Comment by AMBudnik** [comment]
Oh, I see. Yes, you can have multiple sets of menus. You should be able to switch between them via [updateSettings](https://docs.handsontable.com/pro/1.15.1/Core.html#updateSettings) method.
Let me know if you would have any difficulties with the code. I can help.

**Comment by setWan** [comment]
谢谢，我想我先试一下。非常感谢

**Comment by setWan** [comment]
Thank you. I think I'll try it first. Thanks very much

**Comment by AMBudnik** [comment]
You're welcome @setWan
