### ISSUE TITLE
Validator should also receive column and row indices

### ISSUE THREAD

**Issue by Maximaximum** [handsontable/handsontable#4765]
### Description

The validator functions should receive, besides the value to be validated and the callback arguments, the column and row indices of the cell being validated.

I need to be able to perform different kinds of validations based on the row and column indices.

This somehow relates to https://github.com/handsontable/handsontable/issues/4023

### Your environment
* Handsontable version: 0.28.4
* Browser Name and version: Chrome 63.4
* Operating System: Windows 8.1

**Comment by budnix** [comment]
Hi, @Maximaximum 

I think that right now the validators meet your criteria. The validator function is always triggered with `cellProperties` as a function context which contains all information about validated cell including row and column.

I've prepared a simplified demo at http://jsfiddle.net/budnix/x6u5vv9d/.

**Comment by Maximaximum** [comment]
Oh! I didn't see any mention about this in the documentation, but perhaps it was just my inattentiveness.

Thank you.
