### ISSUE TITLE
Documentation is unclear about inclusion of dependencies in the `full` package

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#4766]
The page https://docs.handsontable.com/0.35.1/tutorial-quick-start.html instructs me to install Handsontable using Bower and use the files `handsontable.full.js` and `handsontable.full.css`.

The page https://docs.handsontable.com/0.35.1/demo-date.html tells that Pikaday and Moment must be included in `<head>` separately, because they are not included in Handsontable.

This is untrue, because Pikaday and Moment are already bundled within `handsontable.full.js`

---

This document https://github.com/handsontable/handsontable/blob/master/dist/README.md is out of date, too, because it also says that Pikaday and Moment are not in the `full` bundle.

**Comment by AMBudnik** [comment]
Issue moved to [handsontable/docs #74](https://github.com/handsontable/docs/issues/74) via [**ZenHub**](https://www.zenhub.com/)
