### ISSUE TITLE
Multiple validators for a cell

### ISSUE THREAD

**Issue by Maximaximum** [handsontable/handsontable#4768]
### Description
Is there a way for a cell to have multiple validators?

For example, I need all of my columns to be validated against being non-empty and against a certain blacklist. But also, each of my columns needs specific additional validators: some need to be number-only, some need AutocompleteValidator etc.

Is this achievable?

### Your environment
* Handsontable version: 0.28.4
* Browser Name and version: Chrome 63.4
* Operating System: Windows 8.1

**Comment by AMBudnik** [comment]
You should create a custom validator in this case. Here's an example on how to create a custom validator https://handsontable.com/blog/articles/2017/12/guide-to-basic-data-validation

**Comment by Maximaximum** [comment]
Thanks, but what I'm asking for is declaratively combining multiple validators for a single cell.
Though, perhaps, this should rather be asked in ngHandsontable issues than here?..

I'd like to be able to combine validators like this (in angularJS): 
```
    <hot-table datarows="$ctrl.usersToImport" min-spare-rows="1" hot-id="userImportTable">
      <hot-column data="Email" title="'E-mail'" validator="[$ctrl.RequiredValidator, $ctrl.EmailValidator, $ctrl.NotInBlacklistValidator]"></hot-column>
      <hot-column data="LastName" title="'Family Name'" validator="$ctrl.RequiredValidator"></hot-column>
    </hot-table>
```

**Comment by AMBudnik** [comment]
Sorry for a delay @Maximaximum 
there is no possibility load a few validators this way. You would need to create a new one that uses functionalities of the validators that you need.

**Comment by Maximaximum** [comment]
Well, that's a pity because for any combination of different validators one actually has to create their validator. This is not too convenient, I'd say.

**Comment by AMBudnik** [comment]
But if you create a single one the beforeValidate and afterValidate are easy to handle and understand. With multiple validators, we would need to change the logic. Also, you have a larger control over the validator as you only have one.

**Comment by emilenriquez** [comment]
is there any way to call the existing validators inside the custom validator? @AMBudnik

**Comment by AMBudnik** [comment]
Yes @emilenriquez 

Here's an example http://jsfiddle.net/pecmzzcf/
The `TextRender` (defined text renderer) is called inside the `firstRowRenderer`. And here https://handsontable.com/blog/articles/getting-started-with-cell-renderers you can get some more info about the rendering process and some more complex examples
