### ISSUE TITLE
Slow rendering and scrolling issues

### ISSUE THREAD

**Issue by MDron** [handsontable/handsontable#477]
this could be a duplicate issue (not sure), but want to describe problem more clearly

for large enough tables (usually 3 or more columns with Autocomplere + few Date columns and like arround 100-200 rows), scrolling (via scrollbar) becomes lagged and hard to use.

(keyboard PgUp,PgDown - are ok, up and down arrows works like ultrafast scrolling if holded).

Just generated a demo
http://jsfiddle.net/R7whg/2/

**Comment by PassHours** [comment]
The problem still exists. HOT rendering in IE is very slow...tried with the latest version. 
But the same is working well in Chrome
