### ISSUE TITLE
Undo after copy multiple rows at the end of the table 

### ISSUE THREAD

**Issue by HienNguyen711** [handsontable/handsontable#4770]
### Description
After copy multiple rows at the end of the table, it is impossible to undo. But at the beginning and at the middle of the table, this works fine

### Your environment
* Handsontable version:latest
* Browser Name and version:Chrome 63.0.3239.132 (Official Build) (64-bit)
* Operating System:MacOS Sierra Version: 10.12.4

**Comment by AMBudnik** [comment]
Hi @HienNguyen711 

Can you share any demo/example where this behavior is replicable?

**Comment by AMBudnik** [comment]
I am closing the issue as there is no reply for more than a week.
