### ISSUE TITLE
Capture event when the filter menu is displayed

### ISSUE THREAD

**Issue by briancaldass** [handsontable/handsontable#4772]
### Description

I need to capture event when the filter menu is displayed

### Steps to reproduce

1.
This is my table
![image](https://user-images.githubusercontent.com/16884130/35701638-975ed28c-0764-11e8-8d50-dd45691c663d.png)

2.
I need to capture the event when I click on the filter indicator, and the menu is displayed

![image](https://user-images.githubusercontent.com/16884130/35701661-ab939986-0764-11e8-97bb-48e403d96a0c.png)

**Comment by AMBudnik** [comment]
Hi @briancaldass 

the [afterDropdownMenuShow](https://docs.handsontable.com/pro/1.15.1/Hooks.html#event:afterDropdownMenuShow) should meet your requirements.

**Comment by briancaldass** [comment]
Thanks

**Comment by AMBudnik** [comment]
You're welcome @briancaldass
