### ISSUE TITLE
Can't scroll on Firefox

### ISSUE THREAD

**Issue by lewisjb** [handsontable/handsontable#4773]
### Description
If your mouse is over a handsontable, you can't scroll down the page.

This looks similar, but different to #4521 

### Steps to reproduce

1. Create a basic handsontable (no overflow:hidden)
2. Hover your mouse over it
3. Try to scroll around the page

### Demo
https://docs.handsontable.com/pro/1.14.2/demo-paginating.html
or
http://jsfiddle.net/s2q1ypjq/1/

### Your environment
* Handsontable version:0.35.1
* Browser Name and version: Firefox Quantum 57.0.4 
* Operating System: Kubuntu 17.04

**Comment by TRManderson** [comment]
If your mouse ends up over a HoT due to scrolling, you can continue to scroll (until you move your mouse over the HoT again)

**Comment by AMBudnik** [comment]
Thank you for sharing @lewisjb

**Comment by AMBudnik** [comment]
Hi @lewisjb @TRManderson 

Can you tell me if this issue is still replicable? I have used this demo info@envisio.com (from the 1 post) but did not replicate any scrolling issues. Tested on FF 59 on Windows 10

**Comment by lewisjb** [comment]
@AMBudnik When I update the version to 0.38.1 I can longer replicate it.

**Comment by AMBudnik** [comment]
Great. Thank you for the confirmation. I guess that we can close this issue.
