### ISSUE TITLE
[0.23.0+] Row headers misalignment when updating data with custom renderer

### ISSUE THREAD

**Issue by OliChu** [handsontable/handsontable#4774]
### Description

If I update my data with the loadData method, and if I have a custom renderer (in my case: imageRenderer) modifying the row height, I end up with misaligned and wrongly numbered RowHeaders.

It usually re-render correctly if I update any cell content. 

Is this a known issue and is there a way to rerender rowHeaders after a custom renderer?

### Steps to reproduce

1. Create a table with imageRenderer
2. Load new data (some data have no image)

### Demo

https://jsfiddle.net/Oli_Chu/vuz31xkz/30/

### Your environment
* Handsontable version: latest
* Browser Name and version: Chrome 
* Operating System: Ubuntu

**Comment by AMBudnik** [comment]
Thank you for sharing the example. 

Usually, `autoRowSize` should fix this kind of issues but it looks like the heights of some of the rows are recalculated faster than the content height. I can see that you have used the _img_ class container for the image with fixed pixels values which is correct.

Adding extra rendering and loading the data with a delay does not help so I guess that we should check this issue a little closer.

**Comment by AMBudnik** [comment]
It looks like when we delete the Materialize lib from this demo it looks a little bit better.

With Materialize
![image](https://user-images.githubusercontent.com/10757813/38355686-f588434a-38bd-11e8-97b0-ce51a52d8565.png)


Without Materialize
![image](https://user-images.githubusercontent.com/10757813/38355720-1182219c-38be-11e8-9a6b-29f23d40d43a.png)


It looks like the [version `0.23.0` ](https://jsfiddle.net/handsoncode/u9yw7s5y/)has broken the functionality one version before ([`0.22.0`](https://jsfiddle.net/handsoncode/L9k0ohcv/)) the example looks fine.

**Comment by krzysztofspilka** [comment]
Connected with #4796

**Comment by krzysztofspilka** [comment]
Will be fixed in #4796
