### ISSUE TITLE
pass handsontable data into semantic modal

### ISSUE THREAD

**Issue by chethan1095** [handsontable/handsontable#4778]
Hi i want to pass data which is there in handsontable to form inside semantic modal using jquery how can i achieve it... can anyone please help me

**Comment by AMBudnik** [comment]
Hi @chethan1095 

here is an example window that I took and placed Handsontable inside. Let me know if it works for you as well.

**Comment by chethan1095** [comment]
sorry @AMBudnik where is the example

**Comment by AMBudnik** [comment]
Sorry, my bad., Forgot the link.
Here it is https://codepen.io/anon/pen/rJMaNJ?editors=1010

**Comment by chethan1095** [comment]
sorry @AMBudnik my question is when i clicked on any one of the row inside handsontable a modal should pop up

**Comment by AMBudnik** [comment]
Here is an example of a button https://codepen.io/anon/pen/wyoLvX?editors=1010
I am sure that there is also a way to do the same via `afterOnCellMouseDown `hook, but I am not a jQuery expert.

**Comment by chethan1095** [comment]
Thank You so much @AMBudnik it worked
