### ISSUE TITLE
Choppy scrolling when using trackpad

### ISSUE THREAD

**Issue by kasrak** [handsontable/handsontable#4779]
### Description

Scrolling seems to get stuck/janky when scrolling over the left row headers. In this GIF, the scrolling is smooth when scrolling over the main table, but becomes choppy when the cursor is over the row headers:

![handsontable-scroll](https://user-images.githubusercontent.com/331454/35826040-6d08b8a8-0a6c-11e8-9231-0f2def362409.gif)

Tested on Chrome 63.0.3239.132 on macOS 10.13.2 using the Macbook's trackpad.

### Steps to reproduce
1. Go to https://handsontable.com/examples?headers
2. Try scrolling by using a trackpad while the mouse cursor is over the row headers (first column on the left)

### Demo
https://handsontable.com/examples?headers

### Your environment
* Handsontable version: 0.35.1
* Browser Name and version: Chrome 63.0.3239.132
* Operating System: macOS 10.13.2

**Comment by AMBudnik** [comment]
Thanks for sharing @kasrak 

We have replicated it on Mac (Chrome)

**Comment by swistach** [comment]
Hi @kasrak,
Currently, it should work correctly.
Feel free to reopen if you have still that issue.
