### ISSUE TITLE
Custom renderer called for each row in my table on change of a single cell

### ISSUE THREAD

**Issue by Darkvater** [handsontable/handsontable#478]
Using version 0.8.9.
I have added a custom renderer for one of my columns.
However every time I change the value of a cell the renderer is called for each row of that column. Even if the value changed is in a different column.

This seems to me like a big waste of resources, especially if your table is big. What is the rationale behind this?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by rajanand02** [comment]
Do we have a fix for this? This is major performance issue in my application. i have custom renderer for every cells and if i render 100 rows 20+ columns the editing itself became very slow. If I make a change in one cell the custom renderer is getting called for all 100 rows. This is [approved](https://github.com/handsontable/handsontable/wiki/Feature-requests) for development on 8th Mar 2013 itself.

**Comment by AMBudnik** [comment]
Hi @rajanand02 
we do not have any update on this case yet.

**Comment by PassHours** [comment]
@rajanand02 Yes you are right... it's a big performance hit and is sad that it's not getting addressed. This is the reason we had to pull out handsontable from production and replaced it with plain vanilla excel upload/download feature to make clients happy.

**Comment by AMBudnik** [comment]
should be added with https://github.com/handsontable/handsontable/issues/773

**Comment by arfis** [comment]
Hi, please was this issue solved somehow?

**Comment by AMBudnik** [comment]
Hi @arfis It's more a feature than a bug as Handsontable has been working like this since the beginning. We are planning to change this behavior and allow developers to rerender only parts of the code. Here's a Trello card to follow for updates https://trello.com/c/m9KTygSV/80-rewrite-renderers-to-improve-performance-2152

**Comment by jkyadav** [comment]
@AMBudnik Any update on this? this is really a waste of resources now some of my client are denying to use the system because of the performance of this tool.

**Comment by AMBudnik** [comment]
Hey @jkyadav please check my reply to https://github.com/handsontable/handsontable/issues/4277

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
