### ISSUE TITLE
[1.10.2+] Filter by value erased by checkboxes in cells

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4780]
### Description

The list of values is the `filter_by_value` is erased when we check any of the checkboxes in the table.

### Steps to reproduce

1. Open the dropdown menu for column `A`
2. Uncheck `Lorem`
3. Check any checkbox from column `G`
4. Open dropdown menu

**Result**:
All options in the filter by value are unchecked.
![gif](https://user-images.githubusercontent.com/10757813/35856107-41a731b6-0b35-11e8-8623-25d9c32eef7f.gif)

**Expected**:
All the options in the filter by value besides `Lorem` are checked.

### Demo

http://jsfiddle.net/r6L3sy6b/

### Your environment
* Handsontable version: 1.15.1
* Browser Name and version: Chrome 63
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
The issue started to appear from [version `1.10.2`](https://docs.handsontable.com/pro/1.10.2/tutorial-release-notes.html)

**Comment by AMBudnik** [comment]
Fixing this bug may also fix https://github.com/handsontable/handsontable/issues/4345

**Comment by swistach** [comment]
It will be fixed here: handsontable/handsontable-pro#72
