### ISSUE TITLE
when scrolling is not on the left, open the editor, drag the scroller to the left, then keydown some word, the whole view will jump to the left

### ISSUE THREAD

**Issue by zuan336** [handsontable/handsontable#4782]
### Description
when scrolling is not on the left
1. keydown to open the editor
2. drag the scroller to the left
3. then keydown some word
the whole view will jump to the left,  Layout error

### Steps to reproduce
![qq20180207-123339](https://user-images.githubusercontent.com/28526494/35898713-342abe8a-0c03-11e8-88c4-5a32288697ea.gif)

**Comment by AMBudnik** [comment]
Can you share a demo that you've been using to replicate the issue?

**Comment by AMBudnik** [comment]
I am closing the issue as there is no reply for more than a week.

**Comment by zuan336** [comment]
I just use your official website example.

**Comment by zuan336** [comment]
what demo? Too funny! You can take any of your official example as a demo...

**Comment by AMBudnik** [comment]
Hi @zuan336 

it's important for us to always share any example where the issue can be replicable.
I can see that you have already created a new topic so I will not open this one.
