### ISSUE TITLE
How to use autocomplete values with key before posting

### ISSUE THREAD

**Issue by HelloMoli** [handsontable/handsontable#4783]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/3gas9z6q/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by HelloMoli** [comment]
I want to use dropdown cellType but it only support Array such as source:['apple','banana']  I wanna like 
source:[{key:'a',name:'apple'},{key:'b'},name:'banana']   like an HTML name/value select

**Comment by AMBudnik** [comment]
This option is not available at the moment. The subject has been already raised at https://github.com/handsontable/handsontable/issues/2305

**Comment by HelloMoli** [comment]
thanks @AMBudnik
