### ISSUE TITLE
Reset filter state

### ISSUE THREAD

**Issue by ToujouAya** [handsontable/handsontable#4784]
### Description

The filter state and value don't change when update data and setting table. I would like to know to reset filter state and value when update data and setting in hansontable 
### Steps to reproduce

1. Filter any value
2. Update change data or change setting columns
3. Filter still keeping  with old value 

### Your environment
* Handsontable version: 1.14
* Browser Name and version : Chrome Version 63.0.3239.132
* Operating System: Mac OS 10.11.6

**Comment by AMBudnik** [comment]
Hi @ToujouAya 

Can you share a demo? How are you changing the value that has been filtered out?

**Comment by ToujouAya** [comment]
@AMBudnik 
Here demo 
https://jsfiddle.net/gyzv5zf1/
I use loadData method to change data

**Comment by AMBudnik** [comment]
OK, I see. It looks like we need to re-render the view to have fresh filters. Editing a cell works fine but I surprised that the `hot.render()` does not help.
Thank you for sharing the issue. I will mark it as a bug.

**Comment by AMBudnik** [comment]
The issue is replicable in v `1.18.1` and doesn't seem to be connected to any issue.

**Comment by AMBudnik** [comment]
Happens in 5.0.0 as well

![gif](https://user-images.githubusercontent.com/10757813/42689132-6c0a4a0c-869f-11e8-909c-a45640a7054d.gif)

**Comment by AMBudnik** [comment]
Hey @pnowak please also take a look at https://github.com/handsontable/handsontable/issues/5244
it looks like a very similar (if not the same) case

**Comment by AMBudnik** [comment]
Please track changes to the same issue on our Pro board https://github.com/handsontable/handsontable-pro/issues/93

**Comment by AMBudnik** [comment]
Hi @ToujouAya 

We just fixed an issue related to yours. Please update to 8.0.0-beta1 and check if it solved for you as well.

Below are the resources

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```

And this is how you can download the beta from NPM

`npm i handsontable@beta`
