### ISSUE TITLE
Clone header overlaps handsontable cells 

### ISSUE THREAD

**Issue by jarben** [handsontable/handsontable#4787]
When a cell is rendered as handsontable or autocomplete, a second HOT instance overlaps popup menu:

![image](https://user-images.githubusercontent.com/561365/35979872-b8195a30-0ce9-11e8-854d-b31ab6ef1b14.png)

Demo: http://jsfiddle.net/jarben/c2szqw0h/
Version: 0.35.1
OS: win

**Comment by AMBudnik** [comment]
Thank you for sharing. I have replicated the issue.
As I workaround I recommend to bump up the `z-index` of the `handsontableInputHolder` class
Updated demo http://jsfiddle.net/gspxpq1s/

**Comment by jarben** [comment]
Cool, thanks for a workaround @AMBudnik !

**Comment by AMBudnik** [comment]
You're welcome @jarben 
Now, as we know how the workaround it would be easier to fix it in the official version.

**Comment by pnowak** [comment]
The old demos won't work on newer version of Handsontable (a consequence of selection API change). Updated demo - http://jsfiddle.net/hjf34cLu/

**Comment by AMBudnik** [comment]
Hi @jarben 

please update to v 2.0.0. (CE and PRO) and let me know if it's fixed for you.
