### ISSUE TITLE
Unable to import JSON when columns:[data: tag used

### ISSUE THREAD

**Issue by tman32768** [handsontable/handsontable#4788]
### Description
If I create a new table to import JSON data and add the data: tag the array is imported as [null, null, null]

If I comment out the data field as below my JSON data imports and displays in the table without problems

### Steps to reproduce
javascript code follows
###
hot = new Handsontable($container[0], {
  columnSorting: true,
  startRows: 10,
  startCols: 3,
  currentRowClassName: 'currentRow',
  currentColClassName: 'currentCol',
  rowHeaders: true,
  renderAllRows: true,
  colHeaders: ['Active','Desc', 'Value'],
  colWidths: [150,150, 150],
  columns: [
    {
//    	data: 'active',
    	type: 'checkbox'
    },
    {
//        data: 'desc',
		type: 'text'
    },
    {
//    	data: 'value',
    	type: 'numeric',
    	numericFormat: {
        pattern: '+0,0.000',
        },
        allowEmpty: false,
        Float: 3
    }
###
my JSON data being imported from PHP script
###
{"mytable":
	[
		{"active":true,"desc":"SomeText 0","value":0.000},
		{"active":false,"desc":"SomeText 1","value":1.100},
                ...
		{"active":false,"desc":"SomeText 9","value":9.000}
	]
}
###
### Your environment
* Handsontable version: 0.35.1
* Browser Name and version: all/any safari/firefox/chrome
* Operating System: OSX and iOS

**Comment by AMBudnik** [comment]
Hi @tman32768 

here's a topic that may help https://github.com/handsontable/handsontable/issues/872#issuecomment-364797026

**Comment by tman32768** [comment]
The problem is with the javascript code not PHP

**Comment by AMBudnik** [comment]
Can you share a demo that will help me to debug it, @tman32768 ?

**Comment by tman32768** [comment]
Hi Aleksandra

 

I’m interested in possibly purchasing a license but there’s a few issues which prevents me from making the purchase.

 
Is there any way to export JSON key pairs with handsontables?
 

Right now if I import a JSON string like 

{"name": "Mike","phone": "123-456-7890"}

 

When I export it I get a string like

{"data": "Mike","data": "123-456-7890"}

 

I was hoping to avoid having to use extra table data fields or separate javascript arrays to preserve the key names.

 
How does licensing work? If I buy a developer license are you simply selling the full source code for the current year or are you binding the code to an ip address or machine id or keycode like the demo pro version?
Does the javascript code simply stop working after 12 months on all installations or do I get unlimited use of the sourcecode I purchase? I’m looking for something on Intranet use only.
What’s the difference between a developer and a reseller? https://www.componentsource.com/product/handsontable-pro/prices shows a Handsontable Pro license for $147 – what’s that all about?
 

Mike

**Comment by AMBudnik** [comment]
Hi @tman32768 

I have asked our Sales manager to send you an email about the license.

When it comes to data binding usually when you have a record as 

```
var data = [
     {"name": "Mike","phone": "123-456-7890"}
];
```

you can pass it via `columns `settings like this

```
columns: [
    {data: 'name'},
    {data: 'phone'}
]
```

Here is an example http://jsfiddle.net/xLw3cqjv/1/
Would you like the data to be viewed differently?

**Comment by tman32768** [comment]
Hi Aleksandra

 

I see the columns in the samples but as soon as I add the “data” tag the table stops working and no data gets displayed.  There are no debuggable error messages or any reason I can find why this happens.  Here is the code I’m using.  If I comment out //data lines it works.  If I use the code as is I get a blank table.

 

hot = new Handsontable($container[0], {

                columnSorting: true,

                startRows: 10,

                startCols: 3,

                maxRows: 10,

                maxCols: 3,

                currentRowClassName: 'currentRow',

                currentColClassName: 'currentCol',

                rowHeaders: true,

                renderAllRows: true,

                colHeaders: ['Active','Desc', 'Value'],

                colWidths: [150,150, 150],

                columns: [ 

                {

                                data: 'active',

                                type: 'checkbox',

                                className: "htCenter htMiddle"

                },{

                               data: 'desc',

                                className: "htCenter htMiddle",

                                type: 'text'                                          

                },{

                                data: 'value',

                                type: 'numeric',

                                numericFormat: {

                                               pattern: '+0,0.000',

                               },

                                className: "htCenter htMiddle",

                                allowEmpty: false,

                                Float: 3

                }

 

 

 

Mike

**Comment by AMBudnik** [comment]
Your keys in data have to reflect the `data` parameters used in `columns`. Here is a working example http://jsfiddle.net/1dch739c/

**Comment by tman32768** [comment]
I'd appreciate it if you didn't post complete personal emails and addresses here on a public forum.  I get enough spam already and I don't need to be targeted by even more spam crawlers.

**Comment by AMBudnik** [comment]
Hi @tman32768 

Please let me know where your data has been exposed? I will erase it.

**Comment by tman32768** [comment]
The data was exposed here:

https://github.com/handsontable/handsontable/issues/4788#issuecomment-366609152

I purged the email headers from our emails from this forum.

**Comment by AMBudnik** [comment]
It is unavailable and I cannot check it. 
I am sure that it did not appear in my comment as I am the only one who can change the content of it. I think that it may be caused by the Github auto-email reply (when a reply is sent via mail client, not the Github board) then the email (mine and yours) are visible in the message, here on Github. 
That is annoying, but that's how Github works and I am really sorry but I can't do much about it.

**Comment by tman32768** [comment]
It's the way you have Github email configured or your email client.  You are the only vendor I've seen that does it this way.

**Comment by AMBudnik** [comment]
I will ask our admin to check that. Maybe it's something that we have missed while adding the repository or maybe it can be easily changed now.
Sorry for the inconvenience.
