### ISSUE TITLE
ScrollToCell option in SelectCell functionality is not working properly.

### ISSUE THREAD

**Issue by 80010ekta** [handsontable/handsontable#4789]
### Description
When I am using the SelectCell function and I am providing the row,col and **scrollToCell** option, it is highlighting that particular selected cell but **not scrolling automatically** to reach the position of that selected cell.

### Demo
http://fiddle.jshell.net/sunpc/o1a5krn4/light/

In this demo,it is highlighting the cell but not scrolling to that position.

### Your environment
* Handsontable version: I am using the CDN link as follows:-
https://docs.handsontable.com/pro/1.14.3/bower_components/handsontable-pro/dist/handsontable.full.min.js
* Browser Name and version: Google Chrome Version 50.0.2661.102 (64-bit)
* Operating System: Ubuntu 16.04 LTS

**Comment by AMBudnik** [comment]
Hi @80010ekta 

I remember this issue being fixed in the newer versions. Please try the updated demo http://fiddle.jshell.net/xw0kgwht/ (version 1.15.1)
