### ISSUE TITLE
bug with pasting double quotation marks to cell

### ISSUE THREAD

**Issue by wck821829906** [handsontable/handsontable#4790]
### Description
When I try to paste double quotation masks to handsontable, I gotonly single one pasted.

### Steps to reproduce

1. copy double quotation masks
2. paste to handsontable
3. only single one pasted

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: chrome 63.0
* Operating System: Window 7

**Comment by wck821829906** [comment]
@AMBudnik the demo pls refer to above reproduce steps described very clear, Thanks

**Comment by AMBudnik** [comment]
I tried to replicate it using this demo https://docs.handsontable.com/pro/1.15.1/demo-scrolling.html
But it seems to work fine. Paste data is correct and it also appears the same in the editor.

![2gif](https://user-images.githubusercontent.com/10757813/36020496-3ceaee38-0d83-11e8-9e39-e58386521513.gif)

Please tell me what I am missing.

**Comment by wck821829906** [comment]
Just only copy "", no content inside it, try again...

**Comment by wck821829906** [comment]
![111](https://user-images.githubusercontent.com/17002975/36021166-e80af4c0-0dbf-11e8-9a31-33187ce9ec2e.gif)
shown as above.

**Comment by AMBudnik** [comment]
Thank you for sharing the details. I have replicated the issue using the same demo as before.

**Comment by AMBudnik** [comment]
Still works the same in v 5.0.1
Tested on https://docs.handsontable.com/pro/5.0.1/demo-scrolling.html

**Comment by swistach** [comment]
This issue will be solved within #4931
