### ISSUE TITLE
First Column header in CSV export as Blob has double quotes around

### ISSUE THREAD

**Issue by jruef** [handsontable/handsontable#4795]
### Description
When we have a handsontable with the columns AAA, BBB we would like that the exported csv has the column headers AAA,BBB instead we get AAA,"BBB".

### Steps to reproduce
1. Goto http://jsfiddle.net/api/post/library/pure/ (from: https://docs.handsontable.com/pro/1.15.1/demo-export-file.html#examples)
2. Replace line 45 with:  `exportPlugin.downloadFile('csv', {columnHeaders: true, columnDelimiter: ';', filename: 'MyFile'});`
3. Run and then hit "Export as File" Button

### Demo
See step 1. and 2. above.

### Your environment
* 0.35.1
* Chrome 64.0.3282.140
* MacOS 10.13.3

**Comment by AMBudnik** [comment]
Hi @jruef 

I am not able to get the column header appear differently from the one I put inside a table. Here's the demo I'm using http://jsfiddle.net/5owedwjd/
(Windows 10 / Chrome 63, Excel)

**Comment by jruef** [comment]
Hi @AMBudnik 

When i download the file from your example and open it in Excel, MacOs, Chrome 64 the header row is: AAA;"BBB";"CCC";"DDD";"E";"F";"G". There are the double quotes missing around AAA. Also see the attached screenshot.
<img width="1167" alt="screen shot 2018-02-16 at 11 47 06" src="https://user-images.githubusercontent.com/411848/36304222-24fedece-130f-11e8-82c5-52f82ab062a7.png">

**Comment by AMBudnik** [comment]
Hm..

It looks like you have the same Excel version as me but a different OS.

It looks like this on my device and at my colleague's MacAir.

![image](https://user-images.githubusercontent.com/10757813/36417060-30a8892c-162b-11e8-94b1-0d14adca735e.png)

It looks like your Excel does not have the delimiter set.

**Comment by jruef** [comment]
I have a MacOS 10.13.3. I open the csv in Excel directly. I have the same issue when i open the csv in text editor. Can you please fix the issue?

**Comment by AMBudnik** [comment]
I won't be able to fix the issue without replicating it first. I have also tested the example on Sierra High. It has to be related to Excel settings. Can you check [what you have in the settings](https://support.office.com/en-us/article/change-the-character-used-to-separate-thousands-or-decimals-c093b545-71cb-4903-b205-aebb9837bd1e)?

**Comment by jruef** [comment]
Seems to be an Excel Issue. Can't reproduce it on another MacOs 10.13.3.
