### ISSUE TITLE
option autoRowSize renders too large heights in fixed rows

### ISSUE THREAD

**Issue by alligator77** [handsontable/handsontable#4796]
### Description
With option autoRowsSize render too large heights in fixed rows and cols. 
And somewhere rows not match grid lines in fixed cols and other data

### Demo

https://jsfiddle.net/L1z6nfhL/6/

### Your environment
* Handsontable version: 0.35.1
* Browser Name and version: Firefox 55, Chrome 64
* Operating System: Win 7

**Comment by AMBudnik** [comment]
Thank you for sharing the demo and for your effort to investigate it.

I have replicated the issue.

**Comment by AMBudnik** [comment]
Here is how it looks in v `0.38.1`

![gif](https://user-images.githubusercontent.com/10757813/38352691-5036ae1c-38b4-11e8-8b3d-ab53c9d5f0cc.gif)

The row all fixed rows seem to be too high.

**Comment by krzysztofspilka** [comment]
@alligator77 @AMBudnik We have to add an HMTL handling to the autoRowSize option.

**Comment by krzysztofspilka** [comment]
This task should include loading images in HTML (reported in #4774)

**Comment by AMBudnik** [comment]
We get the same effect after updating to the newest version of Handsontable https://jsfiddle.net/handsoncode/3f48weoL/

**Comment by AMBudnik** [comment]
This issue is the same as https://github.com/handsontable/handsontable/issues/7503 and commenting out fixing does not change the effect.

Please feel free to add a comment to https://github.com/handsontable/handsontable/issues/7503
