### ISSUE TITLE
Custom renderers called multiple times while scrolling

### ISSUE THREAD

**Issue by snaptopixel** [handsontable/handsontable#4797]
### Description
Trying out Handsontable and noticing that custom renderers are invoked many times while scrolling. This is a major performance issue and blocker for us adopting it. They should only re-render when the value changes.

### Steps to reproduce
1. Add this renderer
```js
  const trackRendering = [];

  Handsontable.renderers.registerRenderer('count-renders', (_instance, td, _row, _col, _prop, value, _cellProperties) => {
    const tRow = trackRendering[_row] || [];
    const tCol = ++tRow[_col] || 0;
    trackRendering[_row] = tRow;
    trackRendering[_row][_col] = tCol;
    td.innerHTML = tCol;
  });
```
2. Create a table with enough data to cause scrolling
1. Add a column with the renderer above
1. Scroll around and watch the numbers climb ever higher

**Comment by AMBudnik** [comment]
Hi @snaptopixel 

Each cell has a renderer and that is why when they are loaded the renderer is called. You can use the `renderAllRows: true` settings (like here http://jsfiddle.net/3dz8ggme/) to load cells at the beginning, then the renderer won't be called until you change a cell's content but it will slow down the table at the beginning.
