### ISSUE TITLE
After change on filtered columns, minRows is applied again

### ISSUE THREAD

**Issue by alexon1234** [handsontable/handsontable#4801]
### Description
After you do a change on a filtered columns, the minRows are applied again. 
It is okay this behaviour or it is a bug?

### Steps to reproduce
1. Filtered a row
2. Make a change
3. MinRows is applied again

### Demo

http://jsfiddle.net/a1o06co3/

### Your environment
Handsontable version of https://docs.handsontable.com/pro/1.15.1/demo-filtering.html

**Comment by AMBudnik** [comment]
I could replicate the issue with the `empty cells` scenario on `1.18.1`. Updated example http://jsfiddle.net/handsoncode/kr3qt79z/

Can you confirm that it works for your scenario as well?

**Comment by AMBudnik** [comment]
I think that we can close this issue.

Let me know if you still experience the same issue after updating.
