### ISSUE TITLE
on Checkbox select/unselect "afterChange" event fired multiple times.

### ISSUE THREAD

**Issue by mianRafay** [handsontable/handsontable#4804]
### Description
I have to create instance of handson's table on selection of item from selection panel on a single screen. 
If I select all the selection panel items one by one , and then  I click on the checkbox to change the value. It fires the **afterChange** event multiple times and it also changes the value of other instances checkbox value.

### Demo
1- Select item one by one from the "Selection Panel" .  Whenever we click on the left panel , a new handson's table instance is generated.
![image](https://user-images.githubusercontent.com/21196285/36250613-2ce76534-1260-11e8-8983-9ab86722d9b2.png)

2- Click on checkbox

![image](https://user-images.githubusercontent.com/21196285/36250644-3ceac5ac-1260-11e8-8bcd-ce583ad831a1.png)

3- Event Count Console
![image](https://user-images.githubusercontent.com/21196285/36250807-b0c18808-1260-11e8-8150-aa118efd86d2.png)

### Your environment
* Handsontable version: 0.35.1
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @mianRafay 

sorry, but I won't be able to help without a piece of code or a demo. Could you create one, please?

**Comment by mianRafay** [comment]
The code , call a broadcast event on selection click and generate a new handson's table.

//broadacst that event on each selection change


    $scope.$on('externalDataConfigrationCtrl_initialize', function (event, args) {
    var externalDataGrid =" ";
    var gridData = [];
    $scope.selectedExternalData = null;

      $rootScope.$broadcast('appEvent:btnVisibility', { buttonType: 'remove', action: false });
        $('#defaultExternalMessageText').show();
        $('#externalDataConfigrationGrid').empty();
      
        if (args.dataConfiguration && args.dataConfiguration.externalItems) {
            gridData = args.dataConfiguration.externalItems;
        }

        if (gridData.length > 0) {
            $('#defaultExternalMessageText').hide();
        }
        var dataTypeList = [
            'text',
            'date',
            'double',
            'integer',
            'boolean'
        ];
        var dateFormat = [
          "YYYY/MM/DD",
          "MM/DD/YYYY",
          "DD/MM/YYYY",

          "YYYY-MM-DD",
          "MM-DD-YYYY",
          "DD-MM-YYYY",

          "YY/MM/DD",
          "MM/DD/YY",
          "DD/MM/YY",

          "YY-MM-DD",
          "MM-DD-YY",
          "DD-MM-YY",

          "YYYY/M/D",
          "M/D/YYYY",
          "D/M/YYYY",

          "YYYY-M-D",
          "M-D-YYYY",
          "D-M-YYYY",

          "YY/M/D",
          "M/D/YY",
          "D/M/YY",

          "YY-M-D",
          "M-D-YY",
          "D-M-YY",  
        ];
        var booleanFormat = [
          "Accepted/Declined",
          "Active/Inactive",
          "Checked/Unchecked",
          "Correct/Incorrect",
          "Enabled/Disabled",
          "On/Off",
          "Yes/No",
          "True/False",
          "1/0",
          "Y/N",
          "T/F"
        ];

        /*---Handson Table for Connection Grid-------*/
        var externalDataGridTable = document.getElementById('externalDataConfigrationGrid');
      
        externalDataGrid = new Handsontable(externalDataGridTable, {
          stretchH: "all",
          autoColumnSize: true,
          colWidths: ['100', '100', '50', '55', '90', '180', '60', '120'],
          colHeaders: ['ID', 'Field', 'Label', 'Key', 'Include', 'Data Type', 'Format', 'Length', 'Filter'],
          fillHandle: false,
          renderAllRows: true,
          currentRowClassName: 'currentRowSelection',
          outsideClickDeselects: false,
          columns: [
            { data: 'id' },
            { data: 'fieldName', type: 'text', editor: false },
            { data: 'label', type: 'text' },
            { data: 'isKey', renderer: primaryKey },
            {
              data: "isInclude",
              type: "checkbox",
            },
            { data: "dataType", type: 'dropdown', source: dataTypeList, strict: true, allowInvalid: true },
            { data: "format", type: 'dropdown', strict: true, allowInvalid: true },
            { data: 'length' },
            { data: 'filter' },
          ],
          data: gridData,
          cells: function (row, col, prop) {
            $('#externalDataConfigrationGrid td:nth-child(1), th:nth-child(1)').css('display', 'none');
            $('#externalDataConfigrationGrid td:nth-child(2), th:nth-child(2)').css('border-left', '1px solid #CCC');
           
            var cellProperties = {};
            cellProperties.readOnly = false;
            return cellProperties;
          },

          manualColumnResize: true,
          manualRowResize: true,
          manualColumnFreeze: true,
          afterSelection: function (row, col) {
            var externalDataRow = this.getDataAtRow(row, 0);
            $scope.selectedExternalDataRowId = externalDataRow[0];

            var externalItems = dataConfigurationObject._selectedDataConfig.externalItems;
            dataConfigurationObject._selectedDataConfig.selectedExternalItem = (externalItems) ? dataConfigurationObject._selectedDataConfig.externalItems.filter(function (f) { return f.id == externalDataRow[0]; })[0] : '';
            this.selectCell($scope.selectedExternalDataRowId);
          },
          afterChange: function (changes, source) {
              var instance = this;

              if (source !== 'edit')
                return;

              if (!dataConfigurationObject._selectedDataConfig)
                  return;
              if (!dataConfigurationObject._selectedDataConfig.selectedExternalItem)
                return;

              $.each(changes, function (index, element) {
                var rowIndex = element[0];
                var columnIndex = element[1];
                var newValue = element[3];
                dataConfigurationObject._selectedDataConfig.selectedExternalItem                = dataConfigurationObject._selectedDataConfig.externalItems[rowIndex];
                dataConfigurationObject._selectedDataConfig.selectedExternalItem[columnIndex]   = newValue;

                  if (columnIndex == 'dataType') { // Checking if the event has been triggered within the column datatype
                      setDropDownSource.call(instance, rowIndex, newValue);
                  }
              });
              storageMgr._dataConfigrationTab.updateExternalItem(dataConfigurationObject._selectedDataConfig.identity.id,
                  dataConfigurationObject._selectedDataConfig.selectedExternalItem, function () {
                    $rootScope.$broadcast('appEvent:btnVisibility', { buttonType: 'saveTab', action: true });
                    return false;
                  });

            },
            afterLoadData: function () {
                var instance = this;
                var data = instance.getData();
                var value;
                for (var row = 0; row < data.length; row++) {
                    value = data[row][0];
                    setDropDownSource.call(instance, row, value, true);
                }
                instance.render();
            }
        });

        function setDropDownSource(row, value, init) {
            var instance = this;
            var cellPropertiesOption = instance.getCellMeta(row, 6);
            if (value == 'date')
                cellPropertiesOption.source = dateFormat;
            else if (value == 'boolean')
                cellPropertiesOption.source = booleanFormat;
            else
                cellPropertiesOption.source = null;
            if (!init)
                instance.setDataAtCell(row, 6, "");
        }
    

        function primaryKey(instance, td, row, col, prop, value, cellProperties) {
            var escaped = Handsontable.helper.stringify(value),
                img;

            if (escaped.indexOf('http') === 0) {
                img = document.createElement('IMG');
                img.src = value;

                Handsontable.Dom.addEvent(img, 'mousedown', function (e) {
                    e.preventDefault(); // prevent selection quirk
                });

                Handsontable.Dom.empty(td);
                td.appendChild(img);
            }
            else {
                // render as text
                Handsontable.renderers.TextRenderer.apply(this, arguments);
            }

            return td;
        }


        externalDataGrid.render();
});

**Comment by AMBudnik** [comment]
I have tried to put it inside a Fiddle at http://jsfiddle.net/8ssLu1z5/
Can you check what I'm missing here? I would like to load the table and check the events/methods that are called.

**Comment by AMBudnik** [comment]
Hi @mianRafay 

have you already found an answer/fix for the issue?

**Comment by AMBudnik** [comment]
I am closing the issue as there is no reply from Author for more than a week
