### ISSUE TITLE
Scroll to cell + ColWidths < Column Width = Text Wrap and not scroll until cell

### ISSUE THREAD

**Issue by alexon1234** [handsontable/handsontable#4808]
### Description
I instance a Handsontable with `colWidths:`. If text > colWidths, text gets wrap.
If i try to do selectCell, in order to scroll to the row. It does not scroll good to the row.

I guess this happen because the row gets selected first, then colWidths is applied and make the rows bigger so it does not scroll right. 
If I do not use colWidths, columns would do autosize, but client doesn't want (I dont know why)

### Steps to reproduce
1. Write text bigger than column width
2. Text gets wrap
3. Try to scroll to row > 20

### Demo

http://fiddle.jshell.net/xw0kgwht/9/

**Comment by AMBudnik** [comment]
Can you record it @alexon1234?
I do not see anything suspicious.

**Comment by alexon1234** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7301545/36301318-a88b747e-1304-11e8-9d35-7709e9ae6922.gif)

**Comment by AMBudnik** [comment]
Sorry, but I do not see what you are changing there in the code. Is there a `100%`?


When I load the table (Chrome 64/ Windows 10) it looks like this

![image](https://user-images.githubusercontent.com/10757813/36301614-c16a58ce-1305-11e8-9e4e-df97cf40d13c.png)

**Comment by alexon1234** [comment]
Yeah that is the problem it should appear at the bottom the line 30. Thats the line im trying to scroll to

**Comment by AMBudnik** [comment]
Please let me test it with the latest version (should be ready after about 2 hours). It is a breaking change for selection, so this behavior may change as well.

**Comment by alexon1234** [comment]
Yeah sure not problem. Thanks for the fast reply 😄

**Comment by alexon1234** [comment]
The problem is now solve with the version 0.36
I updated the new code with the new functions
