### ISSUE TITLE
getFirstVisibleColumn is not a function

### ISSUE THREAD

**Issue by briancaldass** [handsontable/handsontable#4809]
### Description

when I call the function getFirstVisibleColumn I get an error, but in the documentation it says it's a function

### Steps to reproduce
getFirstVisibleColumn is not a function

![image](https://user-images.githubusercontent.com/16884130/36285066-308310cc-1278-11e8-8d20-d690fa745ce3.png)

Documentation:

![image](https://user-images.githubusercontent.com/16884130/36285111-582fae8c-1278-11e8-98fb-41fd3054399e.png)

**Comment by AMBudnik** [comment]
Hi @briancaldass 

This method is a part of the `autoColumnSize` plugin. Have you used the `getPlugin` method?
Here's an example http://jsfiddle.net/pjnuc74h/1/
