### ISSUE TITLE
Background color is overwritten by selection

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4812]
### Description

Since Handsontable 0.36.0/1.16.0 the background color is being overwritten by CSS property in a class .area, namely: `background-color: transparent` and `none`.

### Steps to reproduce

1. Go to https://handsontable.com/features,
2. Select multiple cells in "At risk" column,
3. See how the pale red background is removed.

### Demo

https://handsontable.com/features

### Your environment
* Handsontable version: 1.16.0 / 0.36.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/4815
