### ISSUE TITLE
The selection removes the custom background from the cells

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4813]
### Description

The selection removes the custom background from the cells which have defined custom background color.

### Steps to reproduce

1. Go to https://handsontable.com/features and select all cells (<kbd>CMD</kbd>+<kbd>A</kbd>);
2. In the result, column 'at risk' which has custom CSS classes with background-color defined as `#ffecec` got blue color.

![kapture 2018-02-16 at 12 34 32](https://user-images.githubusercontent.com/571316/36306222-1f70a17e-1317-11e8-85f1-b9f65dad744e.gif)

### Your environment
* Handsontable version: 0.36.0
* Browser Name and version: -
* Operating System: -

**Comment by krzysztofspilka** [comment]
Duplicates #4812

**Comment by AMBudnik** [comment]
Released: v0.37.0
