### ISSUE TITLE
The selection completely disappear when context menu is triggered

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4814]
### Description

When non-contiguous selections are applied to the table and If we want to try open the context menu on that selection its disappears. The selection work with context menu only on the latest layer.

### Steps to reproduce

1. Go to https://handsontable.com/features;
2. Make at least 2 layers of the selection;
3. Press right button on the first layer.
4. In the result, the context menu will appear but the whole selection disappears.

![kapture 2018-02-16 at 13 03 05](https://user-images.githubusercontent.com/571316/36307087-bc1f742a-131a-11e8-8d1d-22e0b8870a40.gif)

### Your environment
* Handsontable version: 0.36.0
* Browser Name and version: any
* Operating System: any

**Comment by krzysztofspilka** [comment]
Same as #4816

**Comment by AMBudnik** [comment]
Releases: v0.37.0
