### ISSUE TITLE
Removing non-contiguous rows has a flaw

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4815]
### Description

I'm removing non-contiguous rows using the new selection options available since 1.16.0 / 0.36.0. In most cases, this doesn't work consistently.

### Steps to reproduce

1. Go to https://handsontable.com/examples?context-menu&headers
2. Select rows: 1-4 and 6-10
3. Remove the selected rows using context menu
4. You get the wrong elements as a result.

### Demo

https://handsontable.com/examples?context-menu&headers

### Your environment
* Handsontable version: 1.16.0 / 0.36.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/4815
