### ISSUE TITLE
Context menu must not be closed in a second selection

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4816]
### Description

I cannot open a context menu by clicking on a header of a second selected area.

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.16.0/demo-context-menu.html
2. Select rows 1,2 and 3,4
3. Right-click in a header of row 1 or 2.

### Demo

https://docs.handsontable.com/pro/1.16.0/demo-context-menu.html

### Your environment
* Handsontable version: 1.16.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/4817

**Comment by wojciechczerniak** [comment]
Problem still exists in 0.37

![https://user-images.githubusercontent.com/4718998/36739127-7bc98334-1bdf-11e8-9711-3a6a485679d2.gif](https://user-images.githubusercontent.com/4718998/36739127-7bc98334-1bdf-11e8-9711-3a6a485679d2.gif)

Your environment
- Handsontable version: 0.37.0
- Browser Name and version: Firefox 58.0.2 (64-bit)
- Operating System: macOS

**Comment by budnix** [comment]
I've confirmed, this bug still exists but only for headers. If I try the same with regular cells it works.
