### ISSUE TITLE
Unexpected formatting change v0.35.1+

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4820]
### Description

The formatting has been changed in v0.35.1+

### Steps to reproduce

1. Open a demo
2. Type `5k` in any cell of the `Price ($)` column

**Result**: The cell becomes invalid and data is not replaced.

**Expected**: The `5k` should appear as `5000` like it did before, in [version `0.35.0`](https://docs.handsontable.com/0.35.0/demo-numeric.html).

### Demo

https://docs.handsontable.com/0.35.1/demo-numeric.html

### Your environment
* Handsontable version: Handsontabe 0.35.1+
* Browser Name and version: Chrome 64
* Operating System: Windows 10

**Comment by krzysztofspilka** [comment]
@AMBudnik I'm not sure that we should handle shortcuts such as 5k, 10k etc. To be discussed.

**Comment by AMBudnik** [comment]
`5k` has been previously changed to `5000` according to NumbroJS (docs: http://numbrojs.com/format.html)

![image](https://user-images.githubusercontent.com/10757813/36416357-243d675e-1629-11e8-8567-412e25a93bc4.png)

Of course, it should happen only for `numeric` cells. 
And what is important, it worked like this till v 0.35.1

**Comment by Ubersteinn** [comment]
I have users confused as to why values like 1,234.56 are not considered numbers since it is not obvious to them the comma is the problem. I just tell them to reformat, but it is easily forgettable and distracts them from their work. It has come to me as a 'bug' a few times already. 

I understand if it is not worth including. Just wanted to give some user input.

**Comment by AMBudnik** [comment]
Thank you for your feedback @Ubersteinn 

If that has come to you several times it is definitely something that shouldn't be ignored.

**Comment by Rex90** [comment]
Hi - do we have a timeline of when this is going to be fixed or should we implement our own resolvers?

**Comment by AMBudnik** [comment]
We have just pushed the issue to the `Discussion` tab in our ZenHub. We will discuss the issues within this group before the next release.

**Comment by AMBudnik** [comment]
Still `number k` is considered false validated with Handsontable v7.4.2, Numbro [v2.1.2](https://github.com/handsontable/handsontable/blob/master/package-lock.json#L7803) https://jsfiddle.net/AMBudnik/vm4q3z6r/

**Comment by AMBudnik** [comment]
v8.2.0 works the same https://jsfiddle.net/handsoncode/54shprb0/ (`5k` is not converted to a number)

**Comment by Osky772** [comment]
This is the same case as in #5344 and I copy-pasted the answer from that issue:

After a discussion with our devs, we decided not to "fix" this behavior. The current behavior is correct already, and I will explain why.

In our docs you can find this statement:
> Make sure your cell values are numbers and not strings as Handsontable will not parse strings to numbers. You can input float-typed values in the numeric editor only using a dot or a comma as a decimal separator. For example, both `500000.5`, `500000,5` will be accepted.

Read more: https://handsontable.com/docs/8.3.1/demo-numeric.html

You should pass numeric-like values to numeric cells. You can't pass "string" values to numeric cells. Passing a value like `15%`, `15k` or `15randomtext` etc. is passing a string value.

Furthermore, in version `0.35.0` passing a value `13%` had been causing changing a real value in data until version `0.35.1`. The Handsontable `numericFormat` option doesn't work that way anymore:

> Please keep in mind that this option is used only to format the displayed output! It has no effect on the input data provided for the cell.
The numeric data can be entered to the table only as floats (separated by a dot or a comma) or integers, and are stored in the source dataset as JavaScript numbers.

Read more: https://handsontable.com/docs/8.3.1/Options.html#numericFormat

Anyway, if you want to parse values like that you can do it inside the `beforeChange` hook and use for example `numbro`:
```js
const hot = new Handsontable(container, {
  cell: [
    {
      row: 0,
      col: 0,
      type: "numeric",
      numericFormat: { pattern: "0,0.00%" }
    }
  ],
  colHeaders: true,
  data,
  stretchH: "all",
  beforeChange(changes) {
    for (let change of changes) {
      const [col, row, oldValue, newValue] = change;
      const { type } = this.getCellMeta(row, col);

      if (type !== 'numeric') {
        return;
      }

      const parsedValue = numbro.unformat(newValue);

      if (type === 'numeric' && parsedValue !== undefined) {
        change[3] = parsedValue;
      }
    }
  }
});
```

**Comment by AMBudnik** [comment]
Thank you for your valuable feedback, @Osky772 
I think that with that reply we can close the issue.
