### ISSUE TITLE
Sorting is case sensitive

### ISSUE THREAD

**Issue by alexon1234** [handsontable/handsontable#4822]
### Description
Trying to sort words words that contains accent or speacial characters are sorted differently.

**Is there a way to set the sorting avoiding case sensitive characters?**

### Steps to reproduce
1. Try to order words that contain special character or accents
2. Accented words will appear at the end

### Demo
https://jsfiddle.net/28xfwjxm/5/

**Comment by AMBudnik** [comment]
Hi @alexon1234 

you can check the [`sortFunction`](https://docs.handsontable.com/pro/1.16.0/Options.html#sortFunction) as it's made to relay on your types.
I guess that here https://handsontable.com/blog/articles/easy-ways-to-sort-different-types-of-data-in-your-app at the `Unit of areas` we have a similar case.

**Comment by alexon1234** [comment]
Thanks for the info

**Comment by AMBudnik** [comment]
You're welcome @alexon1234

**Comment by dkwebtec** [comment]
now it's called `compareFunctionFactory`

```
        columnSorting: {
            sortEmptyCells: false,
            indicator: true,
            initialConfig: {
                column: 0,
                sortOrder: 'asc'
            },
            compareFunctionFactory: localeComparer
        },

```
I have made a custom one with locale sorting

```
const localeComparer = function (sortOrder, columnMeta) {
    return function (value, nextValue) {
        var result;

        if (value === null) return 1;
        if (nextValue === null) return -1;
        if (value === null && nextValue === null) return 0;

        result = value - nextValue;

        if (isNaN(result)) {
            return (sortOrder === "desc") ? nextValue.toString().localeCompare(value) : value.toString().localeCompare(nextValue);
        }
        else {
            return (sortOrder === "desc") ? -result : result;
        }
    }
};


```
