### ISSUE TITLE
afterChange not triggered when data is an object

### ISSUE THREAD

**Issue by Quotechnique** [handsontable/handsontable#4826]
### Description
When an object is given as column data with a handsontable cell type,  `afterChange` is not triggered.
Moreover, it is not possible to display a property of the object unless a custom renderer is used.

### Demo
https://codepen.io/Calcimicium/pen/MQVXpG?editors=1010

### Your environment
* Handsontable version: 0.33.0
* Browser Name and version: Chrome 64.0.3282.167
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @Quotechnique 

I wanted to create as simple as possible example  and did this http://jsfiddle.net/8644qkmr/
Is there anything here that I'm missing as here it logs the data via `afterChange`.

**Comment by Quotechnique** [comment]
Imagine an address is not only a street but is compound by a postal code, a city, a country and is saved in a database so it could have an id, my data could be like that:

    var myData = [{
      id: 2,
      name: "Mike",
      address: {
        id: 1
        street: "Sample Av",
        postalCode: "75000",
        city: "Paris",
        country: "France"
      }
    }];

And if I have a data source of adresses, it could be like this one:

    var adresses = [
      { id: 1, street: "Sample Av",      postalCode: "49100", city: "Angers", country: "France" },
      { id: 2, street: "Lorem ipsum",    postalCode: "12345", city: "Foo",    country: "France" },
      { id: 3, street: "Dolor sit amet", postalCode: "67890", city: "Bar",    country: "France" },
      { id: 4, street: "Consectetur av", postalCode: "10111", city: "Hello",  country: "France" },
      { id: 5, street: "Elit av",        postalCode: "21314", city: "World",  country: "France" }
    ]

Because I'd like to select the adress in a list, I choose to use the handsontable cell type:

    columns: [{
      data: 'address.street',
      type: "handsontable",
      handsontable: {
        data: adresses
      }
    }]

If I want the displayed value to be the street only, I have to use `getValue`:

    handsontable: {
      data: adresses,
      getValue: function() {
        var selected = this.getSelected();
        var rowIndex = selected[0][0];
        var data     = this.getSourceDataAtRow(rowIndex);
        return data.street
      }
    }

But only the `street` property of `address` is updated in `myData` as you can see in the log:
http://jsfiddle.net/Calcimicium/5dwvczr0/50/

Now, if I want to give an entire object to a column, I can set the `data` property like this:

    columns: [{
      data: 'address',
      /* */
    }]

But from this point, `afterChange` is not trigger anymore, even if `getValue` function returns the whole `data` instead of only the `street` property:

    columns: [{
      /* */
      handsontable: {
        data: adresses,
        getValue: function() {
          var selected = this.getSelected();
          var rowIndex = selected[0][0];
          var data     = this.getSourceDataAtRow(rowIndex);
          return data;
        }
      }
      /* */
    }]

The main handsontable displays `[object Object]` but this is not a problem, I can use a custom renderer based on the `AutocompleteRenderer` (to keep the arrow) to display the value of the `street` property:

    columns: [{
      /* */
      renderer: function(hotInstance, td, row, column, prop, value, cellProperties) {
      	Handsontable.renderers.AutocompleteRenderer.apply(this, arguments);
        const textNode = td.childNodes[0];
        textNode.textContent = value.street;
      }
    }]

http://jsfiddle.net/Calcimicium/opg4o1y5/14/

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting @Quotechnique 
I've lost a notification.

Have you already managed to push the project further or found anything related to the issue?

**Comment by Quotechnique** [comment]
Unfortunatelly I didn't find anything.

**Comment by AMBudnik** [comment]
I have asked our developer to check your case and send me some tips till Friday.

**Comment by AMBudnik** [comment]
Hi @Quotechnique 

please take a look at this demo http://jsfiddle.net/b318upp6/ and let me know if the solution works in your project as well

**Comment by Quotechnique** [comment]
Yes, that's it !
