### ISSUE TITLE
Setting "wordWrap: false" messes up row height for firefox

### ISSUE THREAD

**Issue by jazztickets** [handsontable/handsontable#4827]
### Description

Firefox:
![screenshot-2018-2-20 handsontable - features](https://user-images.githubusercontent.com/425930/36442301-896a6c68-1632-11e8-8f4f-ba281a09f87d.png)

Chrome:
![2018-02-20-114144_1920x1080_scrot](https://user-images.githubusercontent.com/425930/36442455-1412d0b2-1633-11e8-9c72-8e5dc0dcd73b.png)

### Steps to reproduce

1. Set wordWrap: false in settings

### Demo

Happens on features page: https://handsontable.com/features

### Your environment
* Handsontable version: v0.36.0
* Browser Name and version: Firefox 58.0.2
* Operating System: Arch linux

**Comment by AMBudnik** [comment]
Hm... besides the charts that look different on every browser I do not have the same multiline behavior.

It looks like the arrow from the dropdown is causing this issue as it shifts to the next row. Do you have 100% zoom or any system settings that may relate to this behavior?

**Comment by jazztickets** [comment]
Nothing system related that I can think of. It happens on Windows 7 too. What OS are you on?

**Comment by AMBudnik** [comment]
I'm on Windows 10 but checked it also on Mac High Sierra (10.13.3)

**Comment by jazztickets** [comment]
Weird, cause the bug still happens on Windows 10 for me. I used the image "MSEdge on Win10 (x64) Stable (16.16299)":

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by AMBudnik** [comment]
I will ask our developer to check this on his device.

**Comment by swistach** [comment]
On MacOS 10.13.4 + Firefox 60.0.1 is the same result: http://jsfiddle.net/perd68a0/

**Comment by AMBudnik** [comment]
Works fine in v 5.0.1 http://jsfiddle.net/aLco1sdv/
Thank you again for sharing @jazztickets
