### ISSUE TITLE
lost alignment between fixed rows and rest of table

### ISSUE THREAD

**Issue by christophehalna** [handsontable/handsontable#4831]
### Description

when a rowheight changes because of a large content in a "fixed cell"  when you navigate (scroll) to the left columns, the height gets back to a default value for new loaded columns

### Steps to reproduce

1. go to https://docs.handsontable.com/0.36.0/demo-fixing.html
2. in cell B2, change text to "dd ddd dd ddd ddd dd d d  ddddddddddddddddddd"
3. use horizontal scroll bar to display right most columns

=> as soon as you see que "Q" column, the table is broken, with differents heights between fixed part and the rest 

### Your environment
* Handsontable version: 0.36
* Browser Name and version: Google Chrome 64.0.3282.167 
* Operating System:  Win 10

**Comment by AMBudnik** [comment]
Hi @christophehalna 

If you are using longer data I recommend switching the `autoRowSize` on. Here's an updated example http://jsfiddle.net/handsoncode/v2c8r6jx/
