### ISSUE TITLE
setDataAtCell clear/delete current editor value

### ISSUE THREAD

**Issue by uziel200** [handsontable/handsontable#4836]
### Description

When you put data with setDataAtCell and there is an open editor the value is deleted.

### Steps to reproduce

1. Handsontable with and afterChange event for an simple ajax call
2. The ajax call sould be a delay, for a correct visualitation of the error
3. Capture data in other field while the ajax call finish but dont confirme
4. When the ajax call finish an put data whith setDataAtCell the data of the editor is deleted 😢 

### Demo

![error](https://user-images.githubusercontent.com/5307189/36615544-3e7d2d32-18a6-11e8-9790-612420fcbf46.gif)

### Your environment
* Handsontable version: 0.34.4 the issue is perssintent in 0.36.0
* Browser Name and version: Firefox 56, Quantum, Safari
* Operating System: Windows and MacOS

**Comment by AMBudnik** [comment]
You're right. 

I have replicated the same case here http://jsfiddle.net/handsoncode/4ampuexL/ where I just use the `setTimout` with `setDataAtCell` while I edit any other cell that `(1,1)`

**Comment by uziel200** [comment]
I was checking the **handsontable.full.js** of version 0.36.0 and: `setDataAtCell`call a function named `applyChanges` than function check if there is an active editor and update the editor with `activeEditor.refreshValue()` (this is in the line 15239).

There is a way to call `setDataAtCell` and make that activeEditor.refreshValue(); don't execute? For the moment if you comment the line 15239 of **handsontable.full.js** the issue is fixed.

**Comment by AMBudnik** [comment]
I am not sure if that would be achievable without any source code changes however, I will ask our developer to check it and be back with his feedback.

**Comment by uziel200** [comment]
I was checking that the only parameter that arrives to that function is **source**, maybe that `activatorEditor.refreshValue` will only be executed when source is different from `dontRefreshActiveEditor`

```js
if(source !== 'dontRefreshActiveEditor'){
    activeEditor.refreshValue();
}
```

**Comment by AMBudnik** [comment]
Hi @uziel200 

sorry for keeping you waiting.

It looks like we are not able to provide a solid solution to this case. It would need the asynchronous calls to be supported and we do not do have this solution implemented. It would totally change the logic that we already have so surely it would take more than a few lines of code.
