### ISSUE TITLE
[0.34.5+] updateSettings in afterSelectionEnd breaks copyPaste

### ISSUE THREAD

**Issue by mringler** [handsontable/handsontable#4837]
### Description

When using `updateSettings()` in the `afterSelectionEnd` handler, copyPaste no longer works.

### Steps to reproduce

1. copy cell content c1
2. set `afterSelectionEnd` to call  `updateSettings({})`
3. press *Ctrl+C* on a non-empty cell c2
4. go to another cell and press *Ctrl+V*
5. nothing is pasted
6. disable `updateSettings()` in `afterSelectionEnd`
7. press *Ctrl+V* on an empty cell
8. c1 is pasted into the cell

### Demo

https://jsfiddle.net/yhy5cmzo/51/

### Your environment
* Handsontable version: 0.36.0
* Browser Name and version: Chromium 64.0.3282.167 & Firefox 58.0.2
* Operating System: Ubuntu 17.10 (64-bit)

**Comment by AMBudnik** [comment]
Thank you for sharing @mringler 

I have replicated the issue.

**Comment by AMBudnik** [comment]
Hi @mringler 

I was not able to replicate this issue in the latest version. Can you check that, please?

**Comment by mringler** [comment]
Hi @AMBudnik,

I have changed the jsfiddle to use Handsontable v0.38.1:

https://jsfiddle.net/yhy5cmzo/64/

But I see the same behavior as described above, where copying does not work. Did you refer to an upcoming release?

Thank you

**Comment by AMBudnik** [comment]
Yes, sorry. I took the wrong steps (forgot to click the button). 

Have you been already using this code before and it worked (and got buggy after some time) or did it appear like something new?

I am checking if there is any version that worked well with this scenario.

**Comment by mringler** [comment]
It worked with 0.25: https://jsfiddle.net/yhy5cmzo/65/

**Comment by AMBudnik** [comment]
something that happened in v 0.34.5 has created the issue.[ Here is a demo using v `0.34.5` ](https://jsfiddle.net/handsoncode/1sL0280q/ )(that doesn't work) and [here is a version before `0.34.4` ](https://jsfiddle.net/handsoncode/63k17Lbn/)that works great.

In `0.34.5` we have fixed only one issue: https://docs.handsontable.com/0.34.5/tutorial-release-notes.html so it must be it. The issue has been fixed for Safari but I am testing this behavior on Chrome.

**Comment by daxsorbito** [comment]
Hi any workaround for this?

**Comment by AMBudnik** [comment]
Hi @daxsorbito 
currently, the only way would be to downgrade the software.

**Comment by swistach** [comment]
This issue will be solved within #4931
