### ISSUE TITLE
Trigger Header Dropdown Menu

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#4838]
Hi,

  can anyone help me to trigger column Header dropdown menu..??
i tried by fire click event on <button class="changeType"> DOM.
Bt it doesn't send necessary callback params.(ie. which column I triggered ).So is there any other way to achieve this??

Thanks in Advance

**Comment by AMBudnik** [comment]
Have you tried the `open` method? Here's an example http://jsfiddle.net/handsoncode/7cetmgkc/
