### ISSUE TITLE
Accordion like table.

### ISSUE THREAD

**Issue by sushant1221** [handsontable/handsontable#4839]
I am trying to achieve something like this as shown below.
Can anyone tell me the approach to solve this problem.

arrow is the button inside the cell on clicking that I can  expand and show the data within , which has header on top i.e. 2016,2017... and so on?

![untitled](https://user-images.githubusercontent.com/8128497/36655864-40412b36-1aeb-11e8-9f80-a71cd274ea7b.jpg)

**Comment by AMBudnik** [comment]
Hi @sushant1221 

our hiddenRows sounds like the option that you need. Have you tested it: [hiddenRows](https://docs.handsontable.com/pro/1.16.0/demo-hiding-rows.html)?
