### ISSUE TITLE
Why does't have 'onCellDblClick' Events?

### ISSUE THREAD

**Issue by lql0ve** [handsontable/handsontable#4840]
Why does't have 'onCellDblClick' Events?

BTW: #4200 When are we now?

**Comment by AMBudnik** [comment]
Hi @lql0ve 

the https://github.com/handsontable/handsontable/issues/4200 hasn't been added yet. 

When it comes to double-click, here's an issue to follow to be up to date on the subject: https://github.com/handsontable/handsontable/issues/3912 and here https://github.com/handsontable/handsontable/issues/2266 is a workaround added by one of our Users.
