### ISSUE TITLE
Nested row with angularjs

### ISSUE THREAD

**Issue by sushant1221** [handsontable/handsontable#4841]
I tried implementing this https://jsfiddle.net/handsoncode/gLsz2sLj/
using ngHandsontable and came up with this https://jsfiddle.net/vqkt0hgv/14/

But in angular expand and collapse icons are not being shown?

Is there anything extra I need to add to get it working?

**Comment by AMBudnik** [comment]
Please check the following issue for updates https://forum.handsontable.com/t/nested-rows-angularjs/1830
