### ISSUE TITLE
Internationalization improvement

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4844]
Below tasks should be done or discussed.

1. Wrappers version could be updated (they are fixed with older Handsontable version).
2. Handsontable version on [my.handsontable.com](https://my.handsontable.com) could be updated.
3. Tag `@preserve` of comment should be discussed.
4. Last updated section of comment might be updated in process of a build.
5. Custom borders items of context menu have plural inside, but it has only one form inside language file.
6. The width of context menu could be dynamically expanded.
7. Non-contiguous selection could be treated separately by translation.
8. TypeScript file for languages could be updated.
9. Property `__esModule` should be excluded from the effect of languages helpers.

Extra propositions:

- `Data to` inside filters drop-down menu
- Order of filter elements

**Comment by AMBudnik** [comment]
Hey. 
According to our recent policy, I am closing this proposition of a change as we are not currently working on the piece of code that it relates to.
Once we open an issue we check all pinned issues and pull requests even if they are closed so please keep track of updates to this issue. All additional comments are also highly appreciated.
