### ISSUE TITLE
Deleting multiple cells when one of them is a checkbox breaks

### ISSUE THREAD

**Issue by lewisjb** [handsontable/handsontable#4845]
### Description
If you select multiple cells, and one of them is a checkbox; then you press DELETE, it breaks.
I say "it breaks" because what happens differs depend on the scenario.

### Steps to reproduce
_Click on checkbox cell and drag right_: neither cell is deleted
_Click on checkbox cell and drag left_: other cell is deleted, and checkbox becomes `#bad-value#`
_Click on checkbox cell and then ctrl+click a cell from another column_: other cell deleted, checkbox becomes `#bad-value#`
_Click on cell from other column and then ctrl+click on checkbox cell_: checkbox deleted, other cell isn't

### Demo
http://jsfiddle.net/d5843rm2/2/

### Your environment
* Handsontable version: 0.36.0
* Browser Name and version: Chrome 64
* Operating System: Kubuntu

**Comment by AMBudnik** [comment]
Hi @lewisjb 

Can you record the steps? Either I'm doing it wrong or it works fine on Windows

**Comment by lewisjb** [comment]
Hey @AMBudnik 

Here's a gif of me reproducing each case as mentioned in my original post (in order), for each case, I do the selection, press delete, then ctrl + z, and move onto the next one; (the first one is hard to see the steps because nothing gets deleted). I also recorded this on Chrome on my Windows 10 machine, so it is not a Linux specific issue.

![image](https://im.ezgif.com/tmp/ezgif-1-8efbd7818c.gif)

**Comment by AMBudnik** [comment]
Thank you for sharing the .gif @lewisjb 

The issue with the `#bad-value#` has been already raised at https://github.com/handsontable/handsontable/issues/4106 but I do not see an issue which describes the second issue: where when you select the checkbox as a first cell from the area it prevents the cut operation.

**Comment by lewisjb** [comment]
@AMBudnik The "cut operation" works fine (except for `#bad-value#`, as mentioned in that other ticket), this bugs stops deletion (from DELETE/BACKSPACE)

**Comment by AMBudnik** [comment]
Exactly. It is definitely something that has to be fixed.

**Comment by AMBudnik** [comment]
For all interested users please track changes to https://github.com/handsontable/handsontable/issues/4106
