### ISSUE TITLE
Undo doesn't work for moving columns

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4846]
### Description

Undo doesn't work for moving columns

### Steps to reproduce

1. Move any column to any other position
2. Use <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd>

**Result**: Nothing changes.
**Expected**: The column should return to its first position.

### Demo

http://jsfiddle.net/jrhumujk/

### Your environment
* Handsontable version: 0.36.0
* Browser Name and version: Chrome 64
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
The issue still replicable in v`0.38.1` and did not work in any previous version either.

**Comment by AMBudnik** [comment]
The same in v5.0.1 http://jsfiddle.net/8be3xkov/

**Comment by AMBudnik** [comment]
To complete the subject I wanted to add that the `undoRedo` plugin is able to undo movement of rows but it doesn't do the same for columns.
Updated demo http://jsfiddle.net/AMBudnik/an32tx07/ (8.0.0-beta1)

[`UndoRedo` has many missing pieces of description](https://github.com/handsontable/docs/issues/3), but we should keep consistency between operations on rows and columns so I call it a bug.

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/buwhyokq/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Issue update: This functionality was introduced in Handsontable v14.2.0.

Please check this PR for reference. https://github.com/handsontable/handsontable/pull/10746
