### ISSUE TITLE
Show hide row on button click

### ISSUE THREAD

**Issue by sushant1221** [handsontable/handsontable#4848]
I have  implemented hiding rows with ngHandsonTable with handsontable-pro.

So what I am doing is on button click I am hiding rows using updatesettings()
On button click check the condition using  

> afterOnCellMouseDown

```
afterOnCellMouseDown: function (event, cords, TD) {
            var tableInstance = this;
            console.log(event.realTarget.className.indexOf('myBtdown')); //myBtdown      myBtUp
            console.log(event.realTarget.className.indexOf('myBtUp')); //myBtdown      myBtUp
            console.log(cords);
            // tableInstance.getCellMeta(cords.row, cords.col);

            if (event.realTarget.className.indexOf('myBtdown') < 0 && event.realTarget.className.indexOf('myBtUp') < 0) {
                return;
            } else if (event.realTarget.className.indexOf('myBtdown') >= 0) {
                // TD.childNodes[1].style.backgroundColor = 'red';
                // // tableInstance.render();
                $scope.hideRows(tableInstance,cords, TD);
            } else if (event.realTarget.className.indexOf('myBtUp') >=0){
                $scope.showRows(tableInstance,cords, TD);
            }
        }

```

I am calling $scope.hideRows(tableInstance,cords, TD);

```
$scope.hideRows = function (hotInstance,cords, TD) {
        console.log(hotInstance);
        var showHideSettings = {
            hiddenRows: {
                rows: [1, 2]
            }
        }
        hotInstance.updateSettings(showHideSettings);
    }
```

now on another button click I am doing this

```
 $scope.showRows = function (hotInstance,cords, TD) {
        console.log(hotInstance);
        var showHideSettings = {
            showRows: {
                rows: [1, 2]
            }
        }
        hotInstance.updateSettings(showHideSettings);
    }

```
What am i doing wrong here? 
But even after updating the hidden rows are not being shown up.

**Comment by sushant1221** [comment]
@AMBudnik  I have resolved the issue. But now I am facing another problem.

PLease have a look at this.
I just edited this [official link to ngHandsontable toggle show/hide rows](http://handsontable.github.io/ngHandsontable/demo/index.html#/PRO-hiding-rows)

I am trying to show/hide multiple rows. I am able to hide multiple rows but not able to show the same rows.

[my edited show hide rows version](http://jsbin.com/rikecafogi/1/edit?html,js,output)

Can you please have a look it? 

Thanks and Regards
Sushant

**Comment by JustinCreasy** [comment]
Your problem is the methods hideRows and isHidden do not receive the same parameters. The method isHidden takes one integer at a time instead of an array. If you change your if to:

`if (hiddenRows.isHidden(4) && hiddenRows.isHidden(5) && hiddenRows.isHidden(6))`

it works.

**Comment by AMBudnik** [comment]
Sorry for the delay @sushant1221 

Thank you for your feedback @JustinCreasy 
that is a good hint
