### ISSUE TITLE
Improper selection after paste, when allowInsertRow is disabled.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4849]
### Description
If you disable `allowInsertRow` or/and `allowInsertCol`, then selection is calculated improperly. 

### Steps to reproduce
1. Select `A1:C3`
2. Copy or cut selected area
3. Select `D4`
4. Paste

Result: Only `D4` is selected.

### Demo
https://jsfiddle.net/d1owrv8d/

### Your environment
* Handsontable version: 0.15.0+
* Browser Name and version: Any
* Operating System: Any

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment]
Works the same in v5.0.1

**Comment by swistach** [comment]
This issue will be solved within #4931
