### ISSUE TITLE
handsontable version 8.0 with virtual rendering freezes the page on Internet Explorer -8 

### ISSUE THREAD

**Issue by mastersidd** [handsontable/handsontable#485]
Hi ,
If you open the Demo page 
http://handsontable.com/demo/scroll.html
from Handsontable site in IE 8 . it shows multiple alert of stop sunning script .

Please help me out how to avoid this alert message while opening the handsontable with more then 200 records and 70 columns .without that Script alert in IE 8,.

Thanks 
Mastrsidd

**Comment by krzysztofspilka** [comment]
With v. 0.12.0 we dropped support for IE 8 and 9. https://github.com/handsontable/handsontable/releases/tag/0.12.0
