### ISSUE TITLE
Removing non-contiguous rows does not work with merged cells

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#4850]
### Description
Removing rows using non-contiguous selection throws an error and removes wrong rows when selected rows contains merged cell.

### Steps to reproduce
1. Select few non-contiguous rows with merged cell among them
2. Use context menu to remove those rows
3. Wrong rows are removed and there is an error in browser console: `Error: Incorrect value of the rowsRenderCalculator      handsontable.full.min.js:36:62416`

### Demo
![https://user-images.githubusercontent.com/4718998/36737660-e4a3695a-1bdb-11e8-828a-76ece4bc3072.gif](https://user-images.githubusercontent.com/4718998/36737660-e4a3695a-1bdb-11e8-828a-76ece4bc3072.gif)

### Your environment
* Handsontable version: 0.37.0
* Browser Name and version: Firefox 58.0.2 (64-bit)
* Operating System: macOS

**Comment by krzysztofspilka** [comment]
@AMBudnik to be confirmed in 0.37.0 / 1.17.0

**Comment by AMBudnik** [comment]
Hi @krzysztofspilka 
we've tested it with @wojciechczerniak 
The issue is solved in v0.37.0
