### ISSUE TITLE
minSpareRows option with null data displays incorrect number of rows

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4852]
### Description

If you have null data with minSpareRows set it will show the null data as the spare rows which is incorrect. In the example provided there is 2 rows of null data with 1 min spare row but it only displays 2 rows which it should display 3 is shown with data.

### Steps to reproduce

1. Go to: http://jsfiddle.net/Lp4qn55v/909/ (should display 3 rows, 2 with data and 1 spare)
2. Uncomment Line 8 and comment Line 9
3. Run again (should display 2 blank rows with no spare row, should be displaying 3 rows)

### Demo

http://jsfiddle.net/Lp4qn55v/909/

### Your environment
* Handsontable version: 1.15.0 (pro)
* Browser Name and version: Google Chrome 64.0.3282.140
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @jeremy-smith-maco 

thank you for sharing.

I am not sure but it looks like the same issue has been raised at https://github.com/handsontable/handsontable/issues/3943

Please check the point `3`

**Comment by jeremy-smith-maco** [comment]
I think that seems to be the same issue. I tried looking in the issues before hand but obviously didn't see that one haha.

**Comment by AMBudnik** [comment]
If there's anything crucial to solving the case in https://github.com/handsontable/handsontable/issues/3943 please add it.
