### ISSUE TITLE
An outdated info in "Demos / Rows and columns / Moving" section

### ISSUE THREAD

**Issue by arogachev** [handsontable/handsontable#4855]
https://docs.handsontable.com/0.36.0/demo-moving.html

This part:

```
The draggable move handle appears:

- in the right part of the column header,
- in the top part of the row header.
```

is outdated and confusing.

That how it was in previous versions:

https://docs.handsontable.com/0.15.1/demo-moving-rows-and-columns.html

![Version 0.15.1](https://user-images.githubusercontent.com/8326201/36776448-0418ba1a-1c90-11e8-823f-72e961633e33.gif)

That how it works now:

https://docs.handsontable.com/0.36.0/demo-moving.html

![Version 0.36.0](https://user-images.githubusercontent.com/8326201/36776493-35393944-1c90-11e8-8314-a52ecc9ed91f.gif)

**Comment by AMBudnik** [comment]
Thank you for spotting that! That's true. The information placed in the tutorial is outdated.

**Comment by wojciechczerniak** [comment]
Moved to https://github.com/handsontable/docs/issues/4
