### ISSUE TITLE
Merged Cells + entire column selection doesn't highlight the merged cell.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4860]
### Description
On the current `develop` branch (pre-0.37.0), there's an issue with selecting an entire column containing the merged cell.

### Steps to reproduce
1. Go to http://jsfiddle.net/py4dyoqn/3/
2. Select the columns from `C` to `D` by clicking and dragging on the column headers
**Result:** The merged `B2` cell remains white, which is ok
3. Select the columns from `A` to `E`
**Result:** The merged `B2` cell remains white, which is **not** ok, because it's selected in its entirety, and should be highlighted like any other cell.

### Demo
http://jsfiddle.net/py4dyoqn/3/

**Comment by krzysztofspilka** [comment]
Same things happens when pressing CMD/CTRL+A in a sheet

**Comment by AMBudnik** [comment]
Hi @jansiegel 

the demo seems to be broken. Can you let me know if the issue here https://github.com/handsontable/handsontable/issues/4951 seem to be the same/similar case?

**Comment by jansiegel** [comment]
@AMBudnik Nope, it's different - updated the demo links in the initial comment.
