### ISSUE TITLE
Selecting columns/rows for merged cells should be improved

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4861]
### Description

Selecting columns/rows using a keyboard, in a sheet containing merged cells, works in a strange way. The selection sometimes highlights more than 1 column/rows, only because there are merged cells somewhere in the grid.

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.17.0/demo-merged-cells.html
2. Select column A by click on its header
3. Press shift and arrow right several times

### Demo

https://docs.handsontable.com/pro/1.17.0/demo-merged-cells.html

### How this should work

![kapture 2018-02-28 at 10 35 37](https://user-images.githubusercontent.com/8048526/36780774-3a7c200e-1c74-11e8-8b07-6711cc013651.gif)

### Your environment
* Handsontable version: Pro 1.17.0 / CE 0.37.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by AMBudnik** [comment]
Here's the same issue with more examples and investigation https://github.com/handsontable/handsontable/issues/4859
