### ISSUE TITLE
Sizing the container with `max-width` and `max-height` unstead of `width` and `height`?

### ISSUE THREAD

**Issue by wismill** [handsontable/handsontable#487]
Hi, would like to put a limit to the size of the table, and make the scrollbars visible only when the table is bigger than the given dimensions.

I have used the css properties `width` and `height` on the container but when the table is too small, then there is an ugly empty space.

My first thought was to use the css properties `max-width` and `max-height` unstead of `width` and `height` on the container, but it does not work with handsontable 8.11.

Is there another way?

**Comment by vallieresc** [comment]
I'm looking forward to this feature. Will this be included in the next release?

**Comment by dflock** [comment]
+1

**Comment by groetzi** [comment]
+1

**Comment by seanthebean** [comment]
:+1:

**Comment by markusp72** [comment]
+1

**Comment by AMBudnik** [comment]
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Comment by wismill** [comment]
@AMBudnik can you link the feature request to this page and conversely?

**Comment by AMBudnik** [comment]
Hi @wismill. Github users can only share their ideas at Github board. After investigating they're are approved or closed (if implemented, bugged or related). If approved send to https://github.com/handsontable/handsontable/wiki/Feature-requests

**Comment by stanleyxu2005** [comment]
Currently I tried to observe container's resize event and set width in pixels explicitly.

**Comment by minteliuwm** [comment]
++

**Comment by AMBudnik** [comment]
Hey,

we've added an option in Handsontable 7.0.0 that can interest you https://github.com/handsontable/handsontable/issues/5749 
From now on we support a container with relative dimensions (%, vh, vw, rem, em)

**Comment by AMBudnik** [comment]
This topic is further continued in the discussions panel at https://github.com/handsontable/handsontable/discussions/7943
