### ISSUE TITLE
Cell edit commit has long delay in IE11

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#4872]
### Description
In IE11 when you commit a cell change (press Enter) there is a noticeable delay. In our app (using `react-handsontable` wrapper) it looks like this:

![img](http://g.recordit.co/WrCDJX15mO.gif)

The focus rectangle lingers on the old cell for a moment. On the handsontable website I see a similar delay after committing an edit in the examples.

### Steps to reproduce

1. Edit a cell
2. Press enter
3. Noticeable delay before next cell is focused and can be edited

### Demo

https://handsontable.com/features

### Your environment
* Handsontable version: 0.36
* Browser Name and version: IE 11
* Operating System: Win 8.1

**Comment by AMBudnik** [comment]
Hi @aaronbeall 

Than you for sharing. 

ps. It does not look so bad on IE 11 on Windows 10.

**Comment by aaronbeall** [comment]
I just tried on a Windows 10 machine with IE11 and Edge and saw the same delay.

**Comment by AMBudnik** [comment]
Yes. It is highly probable. As soon as we get this done the performance for most of the operations will dramatically improve.

**Comment by nimesha95** [comment]
Any updates on this issue? I'm facing it too in IE 11 handsontable 6.1.1

**Comment by aaronbeall** [comment]
I'm closing this bug because we have dropped support for IE11. Handsontable performance in IE11 isn't great, but nothing in IE11 is great. :) Meaningful changes to Handsontable performance are covered in other issues.
