### ISSUE TITLE
add `afterColumnCollapse` hook

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4873]
### Description

There would be great if we could add an `afterColumnCollapse` hook.

### Your environment
* Handsontable version: 1.16.0
* Browser Name and version: Chome 64
* Operating System: Windows 10

**Comment by moonjoungyoung** [comment]
+1

**Comment by AMBudnik** [comment]
This feature request is closed, But it will be automatically reopened after we attach it to a milestone.

**Comment by subashdbc** [comment]
It would be great to have this hook `afterColumnCollapse`. Is there any alternative hook is available for this, on the latest version?

**Comment by AMBudnik** [comment]
I am sorry @subashdbc there is no other hook that does exactly the same

**Comment by subashdbc** [comment]
@AMBudnik thanks. I believe this will be available on this next release +1

**Comment by AMBudnik** [comment]
Please track the progress of the hooks here https://github.com/handsontable/handsontable/issues/6193

**Comment by AMBudnik** [comment]
Hi @subashdbc @moonjoungyoung we've just released v 8.0.0 where both hooks (before/after) are introduced.

https://handsontable.com/docs/8.0.0/Hooks.html#event:afterColumnCollapse
https://handsontable.com/docs/8.0.0/Hooks.html#event:beforeColumnCollapse
