### ISSUE TITLE
Resizing non-contiguous headers should work

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4876]
### Description

Select two non-contiguous columns or rows by clicking on their headers. Now, having that the Resize plugin is enabled, resize one of the columns or rows. Currently, it works only for the column or row being actually resized. But it should work for all the selected columns or rows.

![screen shot 2018-03-01 at 15 21 29](https://user-images.githubusercontent.com/8048526/36849392-3f456bfe-1d64-11e8-9ea3-bcf83b4891c6.png)

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.17.0/demo-resizing.html
2. Select two non-contiguous columns or rows
3. Resize one of them

### Demo

https://docs.handsontable.com/pro/1.17.0/demo-resizing.html

### Your environment
* Handsontable version: 1.17.0 / 0.37.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by AMBudnik** [comment]
Still works the same in v `2.0.0`

**Comment by AMBudnik** [comment]
It works well in v 8.1.0 -https://handsontable.com/docs/8.1.0/demo-resizing.html
we can 
* expand many columns
![expand](https://user-images.githubusercontent.com/10757813/95202891-3c439f00-07e2-11eb-9f1c-c72d312b26bf.gif)

* shrink manually
![shrink](https://user-images.githubusercontent.com/10757813/95202918-46fe3400-07e2-11eb-975a-70427df3cfd1.gif)

* shrink by db-click
![db-click](https://user-images.githubusercontent.com/10757813/95202936-4bc2e800-07e2-11eb-8d7e-dfe094e1eaed.gif)

This functionally was added by this PR https://github.com/handsontable/handsontable/issues/7162 and merged to [v8.1.0](https://handsontable.com/docs/8.1.0/tutorial-release-notes.html)
