### ISSUE TITLE
Custom Validator does not work with Custom Renderer

### ISSUE THREAD

**Issue by ffpedro** [handsontable/handsontable#4877]
### Description
After adding a custom validator and a custom renderer to the same column, the validator function still returns the expected value but invalid class is not added.

### Steps to reproduce
1. Define a custom validator and a custom renderer to the same column.
2. Enter some invalid data.
3. Notice that invalid class is not added, so the cell does not get styled as invalid. 
4. Comment custom renderer lines and notice that validation works properly.

### Demo
With both custom renderer and custom validator:
https://jsfiddle.net/1x4qaLj4/34/
With custom renderer lines commented:
https://jsfiddle.net/1x4qaLj4/33/

### Your environment
* Handsontable version: 1.16.0
* Browser Name and version: Chrome 64.0.3282.186
* Operating System: Windows

**Comment by AMBudnik** [comment]
Thank you for sharing the example. I have replicated the bug.

**Comment by evenmind** [comment]
Have the same issue, any workaround for this ?

**Comment by AMBudnik** [comment]
Sorry @evenmind but the issue is deep inside the core so there is currently no workaround

**Comment by lukabann** [comment]
Issue is fixed https://jsfiddle.net/1Lqbgao0/1/
Problem was a overwritten class on line 47.
