### ISSUE TITLE
Using SPACE on non-contiguous checkbox-type cells

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4882]
### Description

It should be possible to change the state of a checkbox-type, non-contiguous cells using <kbd>SPACE</kbd>.

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.17.0/demo-checkbox.html#default
2. Select two non-contiguous ranges in the column "Available"
3. Press <kbd>SPACE</kbd>

### Demo

https://docs.handsontable.com/pro/1.17.0/demo-checkbox.html#default

### Your environment
* Handsontable version: 1.17.0 / 0.37.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by AMBudnik** [comment]
Works the same in v 5.0.1

**Comment by aninde** [comment]
This is fixed by `v8` https://jsfiddle.net/aninde/chg68wyv/.
It's still broken on `7.4.2` https://jsfiddle.net/aninde/7s6j82ah/
