### ISSUE TITLE
Merged cells declared out of the table range get partially rendered.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4887]
### Description
When declaring merged cells outside of the table range they are still visible in the table (if the `row` property has the exceeding value, one row of the declared merged cell is visible, analogously with columns)

### Steps to reproduce
1. Go to http://jsfiddle.net/067kxptu/1/
**Result:** As you can see, the merged cells have the `row` and `col` properties set to `55`, which is way beyond the table limits, and they're still partially visible

**Comment by krzysztofspilka** [comment]
When the `row` is set to `0` then there is a missing value in the console warn.
http://jsfiddle.net/0cz5cqyn/

> handsontable.full.min.js:45 The merged cell declared at [, 55]

**Comment by MateuszG** [comment]
When the `column` is set to `0` then there is a missing second value  on the list in the console warn.

> handsontable.full.js:64292 The merged cell declared at [2, ] is positioned (or positioned partially) outside of the table range. It was not added to the table, please fix your setup.

for data
`mergeCells: [
      {row: 2, col: 0, rowspan: 1, colspan: 25},
    ]`
