### ISSUE TITLE
Paste into multiple selected cells only populates the last cell

### ISSUE THREAD

**Issue by mringler** [handsontable/handsontable#4894]
### Description
After selecting several cells with Ctrl+click, I cannot populate them with paste, but only the last selected cell.
Expected behavior: all selected cells are populated.

### Steps to reproduce

1. Copy content of cell
2. Select several cells with Ctrl+click, selected cells are highlighted
3. Press Ctrl+V
4. Note how selected cells remain unchanged except for the one selected last

### Demo

https://jsfiddle.net/yhy5cmzo/62/

### Your environment
* Handsontable version: 0.36.0
* Browser Name and version: Chromium 64.0.3282.167 & Firefox 58.0.2
* Operating System: Ubuntu 17.10 (64-bit)

**Comment by AMBudnik** [comment]
Hi @mringler 

Please share updates to https://github.com/handsontable/handsontable/issues/4878
The subject covers  copy/cut/paste operations of multiple layers of selection
