### ISSUE TITLE
An unwanted selection being left after selecting all cells

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4895]
### Description

There is an unwanted selected cell left after using CMD/CTRL+A. If it's pressed for a second time then that selection disappears.

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.17.0/demo-scrolling.html
2. Select any cell
3. Press CMD/CTRL+A. Press it again.

**This bug exists since 1.16.0 / 0.36.0.**

![Kapture 2018-03-02 at 17.36.20.gif](https://images.zenhubusercontent.com/5a96afc04b5806bc2bc8c6c0/404e2128-3dee-4131-bcde-de4dd59833a2)

### Demo

https://docs.handsontable.com/pro/1.17.0/demo-scrolling.html

### Your environment
* Handsontable version: 1.17.0 / 0.37.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by budnix** [comment]
This bug is fixed since 1.18.0.
