### ISSUE TITLE
add `setRowMeta`, `getRowMeta` methods

### ISSUE THREAD

**Issue by kamdobrz** [handsontable/handsontable#4901]
### Description
As user I would like to set meta data object to row.
For example: 
`setRowMeta(row, key, value)`

As user I would like to get meta data object from row.
For example: 
`getRowMeta(row)`

### Your environment
* Handsontable version: 1.16.0

**Comment by wojciechczerniak** [comment]
Looks like related to #4055

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for sharing. I hope that we'll be able to publish it soon.

**Comment by ottosson** [comment]
I would love to see this feature implemented (as well as set/getColumnMeta). It would save me from adding hidden columns to store id:s and other meta data for each row.

**Comment by henricook** [comment]
I'd also like a getAllRowMeta and setAllRowMeta in the ideal world - because i'll be persisting this and loading it alongside my data
