### ISSUE TITLE
add `setColMeta`, `getColMeta` methods

### ISSUE THREAD

**Issue by kamdobrz** [handsontable/handsontable#4902]
### Description
As user I would like to set meta data object to column.
For example: 
`setColMeta(col, key, value)`

As user I would like to get meta data object from column.
For example:
`getColMeta(col)`

### Your environment
* Handsontable version: 1.16.0

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for sharing. I hope that we'll be able to publish it soon.
