### ISSUE TITLE
Shouldn't be possible to define merge cells between fixed overlays.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4906]
### Description
Currently, you can define merge cells between fixed overlays. In Google Sheets, a user has not able to do this action.

### Steps to reproduce
1. Go to demo.

### Demo
https://jsfiddle.net/reh2fu80/

### Your environment
* Handsontable version: 0.15.0+
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
I am closing this proposition of a change as we are not currently working on the piece of code that it relates to.
Once we open an issue we check all pinned issues and pull requests even if they are closed so please keep track of updates to this issue. All additional comments are also highly appreciated.
