### ISSUE TITLE
Should be possible to block merging using beforeMergeCells.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4908]
### Description
In most of our `before action` hooks are possible to prevent further action by `return false`.
Currently, a developer has no possibility to prevent merging.

**Comment by AMBudnik** [comment]
I am closing this proposition of a change as we are not currently working on the piece of code that it relates to.
Once we open an issue we check all pinned issues and pull requests even if they are closed so please keep track of updates to this issue. All additional comments are also highly appreciated.
