### ISSUE TITLE
High CPU Usage When Scrolling

### ISSUE THREAD

**Issue by jamesckemp** [handsontable/handsontable#4909]
### Description
Scrolling a table with `renderAllCells === false` causes very high CPU usage.

![cpu](https://user-images.githubusercontent.com/1853915/37063285-d43b79ee-2190-11e8-82aa-1787c0f13e1a.gif)

### Steps to reproduce

1. Load up the scrolling demo.
2. Load up activity monitor.
3. Scroll the table up and down and see the CPU usage rise above 100%.

### Demo
https://docs.handsontable.com/0.24.3/demo-scrolling.html

**Comment by AMBudnik** [comment]
Hi @jamesckemp 

What's your OS? I've tried Chrome 64 on Windows 10 and hot o 4.5% with a faster scrolling I could perform.

**Comment by jamesckemp** [comment]
Hey, I'm on Sierra 10.12.4, Chrome 64.0.3282.186

**Comment by AMBudnik** [comment]
Have you tried a newer version? We're now on 0.37.0 and you've used 0.24.3 in the demo.

**Comment by jamesckemp** [comment]
My local copy is `0.36.0` - I ran `npm update` yesterday and that's the latest it pulled.

**Comment by AMBudnik** [comment]
Thank you for checking that. Hm.. do not think if we can improve the score. I think that the renderers improvement can lower the value. It has been reported on our Trello https://trello.com/c/646bhIv1/83-improve-scrolling-synchro-performance-in-ie-firefox
tomorrow we have a meeting to discuss this subject so hopefully, the table will scroll faster.

**Comment by swistach** [comment]
Hi @jamesckemp,
We've introduced a few improvements in v0.38.0. Currently, scrolling should work better.
https://docs.handsontable.com/5.0.0/demo-scrolling.html

Feel free to reopen, if you still have a problem with high CPU usage.
