### ISSUE TITLE
When I execute the undo operation, I get into the afterRemoveRow callback method?

### ISSUE THREAD

**Issue by setWan** [handsontable/handsontable#4910]
Hi@AMBudnik
When I execute the undo operation, I get into the afterRemoveRow callback method?
When I undo second lines and second columns, afterRemoveRow returns (2,2)

**Comment by setWan** [comment]
Hi @ AMBudnik 
This problem has been solved, and the afterRemoveRow method has a return to type
Thank you very much.

**Comment by AMBudnik** [comment]
Glad to hear that. Thank you for an update @setWan 
I am closing the issue.
