### ISSUE TITLE
[0.37.0+] Cell selection is not calculated properly if merged cells are in selection.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4912]
### Description
As you can see below. If you try to select merged cells and single cells from last column/row, then the selection is calculated improperly.

![merge_selection](https://user-images.githubusercontent.com/11849621/37091471-918ccd46-2208-11e8-9db2-6f286d01ae05.gif)

### Steps to reproduce
1. Try to select `A1:H4`
Expected: Selected `A1:H6`
Result: selected `A1:H4`

### Demo
https://jsfiddle.net/yxudqx9w/

### Your environment
* Handsontable version: 0.37.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
It has changed a little bit in v `2.0.0`, and yes the `0.37.0` was the first verion to produce this bug.

![image](https://user-images.githubusercontent.com/10757813/39354620-39364e8a-4a0b-11e8-8388-2c1bb57d8a70.png)

**Comment by AMBudnik** [comment]
It works the same in v `5.0.1`
