### ISSUE TITLE
renderAllRows not work with updateSettings.

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#4913]
### Steps to reproduce
hello, 
by default we have renderAllRows to false,

for certain action, we need to update renderAllRows to true temporary(handsontable is already displayed)

if i execute 
hot1.updateSettings({renderAllRows: true});    
hot1.render();  

, 
i have not all the rows in the source html.

regards

JM

### Demo

http://jsfiddle.net/jeanmarc/L9pf7eof/3/

### Your environment
* Handsontable version: all versions
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Thank you for reporting this issue @jeanmarc78 

It looks like the 

`hot1.updateSettings({renderAllRows: true}); `

rerenders the table (I have added a hook to track that) but the rows aren't loaded cause when we scroll the `afterRender` callback is called. This does not happen if we use the `renderAllRows: true` in the initialization.

Demo: http://jsfiddle.net/8hnrnLcq/

**Comment by jeanmarc78** [comment]
hello,
i think, i found a workaround

**hot.updateSettings({viewportRowRenderingOffset: 100000});  
hot.updateSettings({viewportColumnRenderingOffset: 200});**  

    i put large value to simulate renderallRows and rendererallColumns


and to revert to default
   
**hot.updateSettings({viewportRowRenderingOffset: 'auto'});  
hot.updateSettings({viewportColumnRenderingOffset:  'auto'});**      

do you see a disadvantage ?

regards
jm

**Comment by AMBudnik** [comment]
Looks like a good workaround doing `viewportRowRenderingOffset `equal to `renderAllRows` (which is the `countRows()`) and `viewportColumnRenderingOffset `to `countCols()` (is even better as `renderAllRows `doesn't cover horizontal scrolling.

Still, we need to fix it internally.

ps. for all the users who are interested in this subject. Please remember that using offset option will jam your table while it loads if you have a lot of data.

**Comment by amitkumar-shingora** [comment]
I tried viewportColumnRenderingOffset but it is not working. The viewportRowRenderingOffset working fine.

**Comment by AMBudnik** [comment]
Works the same in v 8.0.0-beta1 
http://jsfiddle.net/AMBudnik/fmek56d1/

**Comment by srdjan-medjo** [comment]
> Looks like a good workaround doing `viewportRowRenderingOffset `equal to `renderAllRows` (which is the `countRows()`) and `viewportColumnRenderingOffset `to `countCols()` (is even better as `renderAllRows `doesn't cover horizontal scrolling.
> 
> Still, we need to fix it internally.
> 
> ps. for all the users who are interested in this subject. Please remember that using offset option will jam your table while it loads if you have a lot of data.

So we lose virtualization with this fix? That is not ideal. Can this be fixed on your side? This problem still exists in v11.1.0

**Comment by adrianszymanski89** [comment]
Hi @srdjan-medjo 

I retested it with the newest version (12.3.0), and it seems that the original issue is gone: http://jsfiddle.net/aszymanski/fo6qxchs/

Can you please confirm?
