### ISSUE TITLE
'beforeChange' hook is not called when loadData

### ISSUE THREAD

**Issue by sgrit** [handsontable/handsontable#4916]
### Description
loadData doesn't call 'beforeChange' hook although 'afterChange' hook is called.

### Demo

https://jsfiddle.net/3gas9z6q/21/

### Your environment
* Handsontable version: 0.37.0 (CE)
* Browser Name and version: Google Chrome 61.0.3163.100 (Official Build) (64bit)
* Operating System: Windows10

**Comment by AMBudnik** [comment]
Hi @sgrit 

Out docs states that:

> loadData - Action triggered by Handsontable after the loadData or updateSettings({data: myData})(with data property) method has been called;

src: [docs](https://docs.handsontable.com/0.37.0/tutorial-using-callbacks.html#page-source-definition)

But I think that we wouldn't mind adding a callback that is triggered before the data is loaded as we already have an [`afterLoadData` ](https://docs.handsontable.com/0.37.0/Hooks.html#event:afterLoadData)callback. Currently calling

`instance.loadData([[1,2]])`

does not trigger `beforeChange` and I guess that nothing more that callbacks that are harder to use. We definitely trigger `before/afterRender` and `before/afterCreateRow/Column` but these callbacks don't necessary are provided to handle this kind of operations.

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for sharing. I hope that we'll be able to publish it soon.
