### ISSUE TITLE
Calling wrong 'beforeKeyDown' hook

### ISSUE THREAD

**Issue by rogerioangelis** [handsontable/handsontable#4917]
### Description

when I have an autocomplete cell in a table. If i edit the text cell first and after I tried to use autocomplete's options list, the wrong hook is called. The expected is the 'beforeKeyDown' from AutoComplete instead of 'beforeKeyDown' from TextEditor

### Steps to reproduce

1. Go to https://docs.handsontable.com/0.37.0/demo-autocomplete.html
2. Edit Year cell
3. Edit any autocomplete 
4. When list options, arrow down and up doesn't work. I can't select an option with the keyboard

### Demo

https://docs.handsontable.com/0.37.0/demo-autocomplete.html

### Your environment
* Handsontable version: 0.37.0
* Browser Name: Chrome
* Operating System: Any

**Comment by AMBudnik** [comment]
Hi @rogerioangelis 

Thank you for sharing the issue. It has been already raised at https://github.com/handsontable/handsontable/issues/3782
