### ISSUE TITLE
Duplicated autofill handles between fixed areas

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4920]
### Description

Since 1.17.0 / 0.37.0 there is a bug that causes displaying multiple autofill handles when selecting areas that are fixed and non-fixed.

![screen shot 2018-03-09 at 11 14 46](https://user-images.githubusercontent.com/8048526/37202732-9f88cb78-238b-11e8-8e9f-b457d7de3b65.png)

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.17.0/demo-fixing.html
2. Make a selection between fixed and non-fixed parts of the grid
3. See the result

### Demo

https://docs.handsontable.com/pro/1.17.0/demo-fixing.html

### Your environment
* Handsontable version: 1.17.0 / 0.37.0 (it exists in 1.17.1 and 0.37.1 as well)
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by jansiegel** [comment]
Released in `0.38.1`.
