### ISSUE TITLE
Get row index and column index of value inside validator of column

### ISSUE THREAD

**Issue by ShraddhaShinde93** [handsontable/handsontable#4922]
### Description
Hi,
I am having validator callback to validate cell of that column. When the validator validates value after that I want to know the row index and column index of that column,because I want to show different validation messages as comment for different validation condition

### Your environment
* Handsontable version:1.14.3

**Comment by watnab** [comment]
"beforeValidate" seems to receive "Row index" and "Property name / column index".
https://docs.handsontable.com/pro/1.14.3/Hooks.html#event:beforeValidate

**Comment by AMBudnik** [comment]
Thank you for your feedback @watnab 
You are right, the `beforeValidate` hook seems to be a good help for @ShraddhaShinde93 

@ShraddhaShinde93 do you need anything else?

**Comment by AMBudnik** [comment]
I assume that we can close the issue as there is no reply from the author, but @ShraddhaShinde93 feel free to comment if you'd need anything.
