### ISSUE TITLE
Help needed: Confirm Chinese (TW) translation

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4923]
## Welcome community!
We have just received a translation for the **Chinese (TW)** language at the https://github.com/handsontable/handsontable/pull/4919

Please help us to confirm it. 
**5 votes+** will allow us to confirm the translation and pull the changes.

Thanks!

**Comment by osinglee** [comment]
@AMBudnik 我已经看到有5票。

**Comment by AMBudnik** [comment]
Thank you @osinglee @kunloon @ccicc @hugebanana @LittleHChan for your thumbs up. The translation has been released in Handsontable `3.0.0`
