### ISSUE TITLE
Filtering data with prop function does not seem to work

### ISSUE THREAD

**Issue by antihero9082** [handsontable/handsontable#4927]
### Description
When using a function to populate data, it seems like filtering is not being applied correctly. (Seems to be coming from getAtColumn).  When the property is a function, it looks to be attempting direct access to the row prop instead of calling the prop function.

### Demo
http://jsfiddle.net/far7xw2c/25/

### Your environment
* PRO 1.15.1
* Chrome Version 64.0.3282.186
* Operating System: Ubuntu 16.04

**Comment by antihero9082** [comment]
Hi @AMBudnik,
I tried removing `minSpareRows` in the demo (it does not exist in my current use case) and the issue presists.
http://jsfiddle.net/far7xw2c/28/

**Comment by AMBudnik** [comment]
CAn you tell me how to replicate the issue? I guess that I misunderstood the case.

**Comment by antihero9082** [comment]
Hi @AMBudnik, the issue is replicated in the fiddle. (http://jsfiddle.net/far7xw2c/28/)

When we attempt to filter a value in the `emails` column, you will notice that the value exists in the `filter_by_value` list. However, when we attempt to apply the filter based off of either of the values, the filter fails.

**Comment by AMBudnik** [comment]
Thank you. That helped.
You're right. The filtering for the last column does not work. I will ask our programmer is there any workaround for that.

**Comment by AMBudnik** [comment]
HI @antihero9082 

just an update here. It looks like this PR https://github.com/handsontable/handsontable/pull/4574/files can help us to solve the following issue

**Comment by swistach** [comment]
Hi @antihero9082,
Unfortunately, we don't support this feature right now.
@AMBudnik mentioned about a pull request, which could add this feature, but we didn't merge it yet. I think even with new feature your use case is different and would be necessary to modify your solution.
At this moment, I think you can try to use a different data schema.

**Comment by AMBudnik** [comment]
Hey @antihero9082 
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for sharing. I hope that we'll be able to publish it soon.
