### ISSUE TITLE
Columns in the first calls have `this` on `window`

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#4929]
### Description
Probably the first Handsontable calls don't have an Handsontable instance and therefore as `this` is a global `window` object.

### Demo
https://jsfiddle.net/5637xpxb/

### Related issue:
#4740

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
Duplicate of #5001
