### ISSUE TITLE
Row height changes when scrolling horizontally

### ISSUE THREAD

**Issue by Laplandia** [handsontable/handsontable#493]
Suppose there is a column with a lot of text in the left part and it takes several lines. When you scroll to the right, row height gets much smaller after this column is no longer seen.

**Comment by krzysztofspilka** [comment]
Connected with #2107

**Comment by lanierhall-doubleline** [comment]
If this is fixed can someone comment on how to make it work? As of v0.19.0 row heights still resize down when the wrapped columns are out of sight.

**Comment by budnix** [comment]
Hi @lanierhall-doubleline, you can prevent this behaviour by enabling AutoRowSize plugin (`autoRowSize: true`)

**Comment by tkane2000** [comment]
I ran into this In 1.7.4 and found that in addition to enabling the AutoRowSize plugin you have to set viewportColumnRenderingOffset to the number of columns in the table.  Otherwise, they won't all be rendered and won't be considered by the AutoRowSize plugin.

**Comment by Aden-Kurmanov** [comment]
> Hi @lanierhall-doubleline, you can prevent this behaviour by enabling AutoRowSize plugin (`autoRowSize: true`)

I have 65 rows and it does not work, but if i left only 10 rows it works

**Comment by AMBudnik** [comment]
Hi @Aden-Kurmanov, this issue is marked as solved.

If the following scenario described by author does not work for you please send us a demo at support@handsontable.com
