### ISSUE TITLE
Should outsideClickDeselects influence getLastVisibleRow()

### ISSUE THREAD

**Issue by mattRedBox** [handsontable/handsontable#4932]
### Description
We have a a tabbed editor which uses handsontable to work within different tabbed worksheets.
However when using large datasets, say, 20 000ish rows,
if the setting is"
`{outsideClickDeselects: false}`
then all 20000 rows are included in any calculations of visible rows ie: getLastVisibleRow() shows 
20 000. This of course causes performance issue when moving between tabs and repaint of table
When we set 
`{outsideClickDeselects: true}`, this problem disappears, and getLastVisibleRow() shows the desired behaviour again of say only 10.
We have experimented with other settings and followed advice setout in doc about improving performance and haven't got anything unusual in the settings - removing/changing other settings doesn't seem to have any effect on the getLastVisibleRow() count.

Is this behaviour expected? And if so, why?

### Your environment
* Handsontable version: 37.0
* Browser Name and version: Chrome
* Operating System: MacOSX

**Comment by mattRedBox** [comment]
Hi 
I think I can see why we're seeing what looks like a complete render when 
`outsideClickDeselects: false`
[https://github.com/handsontable/handsontable/blob/master/src/tableView.js#L139](https://github.com/handsontable/handsontable/blob/master/src/tableView.js#L139)

In our own environment by removing this method, I can see that we get the expected behaviour whereby we can allow:
`outsideClickDeselects: false`
.. and getLastVisibleRow() shows the desired behaviour again of say only 10.

Does the editor have to be destroyed when `outsideClickDeselects: false` ? What behaviour is enabled by destroying the editor or can something else be done here?

**Comment by swistach** [comment]
Hi @marrRedBox,
Thank you for your sharing, but could you recreate this issue based on my example: http://jsfiddle.net/opxdbrgg/?

**Comment by AMBudnik** [comment]
I think that we can close this issue as there's no response for a week
