### ISSUE TITLE
Possible to add columnIndex to queryMethod call?

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4944]
### Description

We are implementing a custom queryMethod but we need to know which column it is currently searching on as we are adding the ability to search per column. All this requires is a couple lines changing in the code. This is where the queryMethod callback is called: https://github.com/handsontable/handsontable/blob/9c504663a1002880abbd1b0b5bca98da65d0bcd6/src/plugins/search/search.js#L29

Can easily just pass in the columnIndex by changing this
`var testResult = cellQueryMethod(queryStr, cellData);`
to this
`var testResult = cellQueryMethod(queryStr, cellData, colIndex);`

If not we can just clone the library and do it ourselves but just wanted to pose the idea.

**Comment by AMBudnik** [comment]
Thank you for sharing the idea. It sounds like a good plan.

**Comment by jeremy-smith-maco** [comment]
We no longer need this as we are bypassing the whole search query method now but can still leave it up as a feature in-case anyone else may want it.

**Comment by AMBudnik** [comment]
Thank you for an update @jeremy-smith-maco

**Comment by AMBudnik** [comment]
As mentioned in the https://github.com/handsontable/handsontable/issues/5042 I am temporary closing this issue

**Comment by wojciechczerniak** [comment]
We've got PR for this #5980

**Comment by aninde** [comment]
@jeremy-smith-maco according to your wish, we introduced `cellProperties` in `7.1.2`.  The new version will be released next week. 
`cellProperties` was added to the arguments of search's queryMethod so that it would be possible to tell what kind of data was being queried. https://github.com/handsontable/handsontable/blob/c6579078ce2801b313f7a74a7ec88e0eb572e5cb/src/plugins/search/search.js#L150

**Comment by AMBudnik** [comment]
I'm happy to announce that we just released Handsontable `7.2.0`. Again thank you for your feedback and constant support Jeremy.
