### ISSUE TITLE
Handsontables loads only 10-12 <tr> but i am having 40 rows.

### ISSUE THREAD

**Issue by snehakhk** [handsontable/handsontable#4945]
### Description
Hi, i am new to handsontable and using jquery with Handsontable and when i try to load data it only loads 10-12 <tr> in handsontable  but i have 40 rows ,I am not getting why this is happening.I am getting all 40 records from database but when i create handson table it creates only limited number of <tr> but that number is not fixed .
some times it is loading 10 <tr> sometimes it loading 12 <tr>.

Is this time related issue?

**Comment by AMBudnik** [comment]
Hi @snehakhk 

If you would like to have all rows rendered you can use `renderAllRows` method or offset options 
https://docs.handsontable.com/pro/1.18.0/Options.html#viewportColumnRenderingOffset
https://docs.handsontable.com/pro/1.18.0/Options.html#viewportRowRenderingOffset

**Comment by snehakhk** [comment]
@AMBudnik Thanks your solution works for me.

**Comment by AMBudnik** [comment]
Great! I'm happy to hear it.
I am closing the topic as it's solved.
