### ISSUE TITLE
How to set the table to specify the color of the column header

### ISSUE THREAD

**Issue by setWan** [handsontable/handsontable#4946]
Hi @AMBudnik 
How to set the table to specify the color of the column header

**Comment by AMBudnik** [comment]
Hi @setWan 

here is a demo that shows how to color column headers https://codepen.io/handsoncode/pen/ggvENy
Currently, it's done only by external CSS settings

**Comment by setWan** [comment]
Hi @setWan
The problem has been solved. Thank you very much.

**Comment by AMBudnik** [comment]
Great!

I am closing this topic.
