### ISSUE TITLE
 Callback after validating all the cells

### ISSUE THREAD

**Issue by briancaldass** [handsontable/handsontable#4949]
### Description

Currently I have an application in which I use handsontable, the problem is that I can not find a way to execute a function after validating the cells, in the documentation there is the afterValidate method, but this does not work for me since it is executed every time it is validated a cell individually, I need a way to do it by validating all the records in the table, keeping in mind that I have records of 5 thousand to 1 million.

Keep in mind that I have more than 80 columns in the table

I can not provide a demo since it is a very large application with many technologies, but here at a glance

![screenshot_1](https://user-images.githubusercontent.com/16884130/37534102-d1df5bba-2911-11e8-841c-7bd9b6bce573.png)

**Comment by AMBudnik** [comment]
Hi @briancaldass 

I am not sure if currently, it is achievable. We would need to have a `source` argument of the `afterRender` method or a new hook. I have created a topic that you can track for changes at https://github.com/handsontable/handsontable/issues/4952
