### ISSUE TITLE
Cells aren't selected properly with nestedColumns enabled

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4951]
### Description

Cells aren't selected properly with `nestedColumns `enabled

### Steps to reproduce

1. Select column `E`

Result:

![image](https://user-images.githubusercontent.com/10757813/37585883-db3e277c-2b5a-11e8-8a9f-17bff77a88ec.png)

Expected:

![image](https://user-images.githubusercontent.com/10757813/37585919-00ac2d6a-2b5b-11e8-918a-fa03ed84c41b.png)

### Demo

https://docs.handsontable.com/pro/1.18.0/demo-nested-headers.html

### Your environment
* Handsontable version: 0.38.0/1.18.0
* Browser Name and version: Chrome 
* Operating System: Windows 10

**Comment by krzysztofspilka** [comment]
@jansiegel  Looks good to me 👍

**Comment by AMBudnik** [comment]
Thanks!
