### ISSUE TITLE
The Chinese IME has error 

### ISSUE THREAD

**Issue by zuan336** [handsontable/handsontable#4958]
### Description
When the editor or the chrome was upgraded, the original modified error was reproduced.
### Steps to reproduce

1.When keydown to edit a cell use Chinese IME, the first entered letter is missing.

### Demo

![qq20180321-102422](https://user-images.githubusercontent.com/28526494/37692249-665a9f0a-2cf2-11e8-81d2-88627c6262a8.gif)

https://handsontable.com/examples

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/4662

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report with the gif. It helps a lot.

**Comment by theRichu** [comment]
Korean has same problem again,
![handsontable_error](https://user-images.githubusercontent.com/4320530/39473062-f44a37c0-4d87-11e8-8eb4-a1e28b6d2cdd.gif)

Google Chrome | 65.0.3325.181 (Official Build) (64-bit)
OSX 10.13.4 (17E199)

**Comment by AMBudnik** [comment]
Hi @zuan336 

the issue should be solved in v 4.0.0
Please update and let me know if it works for you.
https://github.com/handsontable/handsontable/issues/4662
