### ISSUE TITLE
If there are multiple table in a page, How  can I set id for every table.

### ISSUE THREAD

**Issue by solace202** [handsontable/handsontable#4959]
when I render multiple table in a page, I found sometimes there only have one table, Because every table have the same id. So I want to know How to set id for every table?

**Comment by AMBudnik** [comment]
Hi @solace202 

what do you mean by saying 

> Because every table have the same

What you do with the table ID once you get it?

**Comment by AMBudnik** [comment]
Did you find what you wanted to do? I can help if you need some guidance.

**Comment by Dhaya-JC93** [comment]
Can any Help to create Multiple Table with Handsontable Plugin

**Comment by AMBudnik** [comment]
Hi @Dhaya-JC93 

Each table is a new instance. Here is an example http://jsfiddle.net/handsoncode/p19nrhjr/1/ 
In the example on table is on the site and another one is in a window.
