### ISSUE TITLE
[0.27.0+] Infinity header updates

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4961]
### Description

The Handsontable goes to some weird scroll infinity loop when it's initialized at the bottom of the page. This is caused only when the last row is selected. The cell corner extends the height of the body which is treated by Handsontable as a scroll changing and it triggers rendering infinitely.

### Steps to reproduce

1. Go to https://jsfiddle.net/budnix/u2rb8sdc/2/;
2. Scroll result frame to the bottom of the page;
3. Select column `B` and scroll to the bottom again;
4. In result, the `afterGetColumnHeaderRenderers` and `afterGetRowHeaderRenderers` hooks are triggered infinitely.

### Demo

https://jsfiddle.net/budnix/u2rb8sdc/

### Your environment
* Handsontable version: 0.38.1
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
This issue firstly was replicable in v `0.27.0` when we added header selection.

Here is v `0.26.0` when it worked fine https://jsfiddle.net/handsoncode/y80z6z2x/1/ but the header hasn't been selected.
