### ISSUE TITLE
Nested Headers doesn't support non-contiguous header selection

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4964]
### Description

Nested Headers doesn't support non-contiguous header selection.

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.18.1/demo-nested-headers.html;
2. Select the O column then by pressing the <kbd>CTRL/CMD</kbd> select the R column;
3. In result, the headers are incorrectly marked.

### Screenshot
![kapture 2018-03-22 at 13 23 46](https://user-images.githubusercontent.com/571316/37770319-5852b892-2dd4-11e8-99f0-0f7ccf154c00.gif)

### Your environment
* Handsontable version: 0.38.1
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
It looks much better in v `5.0.1`

![image](https://user-images.githubusercontent.com/10757813/44988784-2b355d80-af8c-11e8-861d-1a082e0a9f4e.png)

However, as I believe, it would be better to have the `O` headers selected the same as `R`.

**Comment by AMBudnik** [comment]
It works way better with this PR https://github.com/handsontable/handsontable/pull/6828
https://jsfiddle.net/AMBudnik/aL1fwszn/
![Zrzut ekranu 2020-04-24 o 12 49 34](https://user-images.githubusercontent.com/10757813/80204967-1ce8f900-862a-11ea-8801-b3652729bc1b.png)

But it still needs some changes to cover complex cases.
![myexample](https://user-images.githubusercontent.com/10757813/80205196-7f41f980-862a-11ea-90c3-8e575996caf2.gif)

**Comment by AMBudnik** [comment]
v8.0.0 seems to work the same as my previous demo https://jsfiddle.net/AMBudnik/5rtzxj83/
We still get two layers when we select R and then F while holding <kbd>CMD</kbd> key.

![Zrzut ekranu 2020-09-10 o 11 26 18](https://user-images.githubusercontent.com/10757813/92711047-90c93b00-f358-11ea-9272-3ae0b578063b.png)
