### ISSUE TITLE
Numeric Cell Editor: Allow Numeric Characters Only

### ISSUE THREAD

**Issue by melloware** [handsontable/handsontable#4965]
### Description
When using a Numeric Cell Editor you can type "aaa" and then get a validation error.  A better UX experience would be to allow only valid numeric entries like "+-.123456789" and all other keystrokes blocked.

### Steps to reproduce
1. Edit a Numeric Cell
2. Type "aaa"
3. any alphabetic character should not be allowed to be typed

### Demo
https://docs.handsontable.com/0.38.1/demo-numeric.html

### Your environment
* Handsontable version: 0.38.1
* Browser Name and version: Chrome 64
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thanks. That's a cool idea.

**Comment by melloware** [comment]
This is what we use now but its too brute force as it affects all editors on the whole sheet.

```javascript
    $hot.updateSettings({
       beforeKeyDown: function (e) {
           // prevent Alpha chars in numeric sheet cells
           var key = e.charCode || e.keyCode || 0;
           // allow backspace, tab, delete, enter, arrows, numbers and keypad numbers
           // ONLY home, end, F5, F12
           console.log('Key: ' + key + ' Shift: ' + e.shiftKey);
           var isNumeric = ((key == 8) || (key == 9) || (key == 13) || (key == 46)
                           || (key == 116) || (key == 123) || ((key >= 35) && (key <= 40))
                           || ((key >= 48) && (key <= 57)) || ((key >= 96) && (key <= 105)));

           if (!isNumeric || e.shiftKey) {
               // prevent alpha characters
               e.stopImmediatePropagation();
               e.preventDefault();
           }
       },
```

**Comment by AMBudnik** [comment]
That is cool. Looks like the only thing you're missing (to avoid adding it everywhere) is to use cell meta to differ a cell type. 

You can get it from [`getCellMeta`](https://docs.handsontable.com/pro/1.18.1/Core.html#getCellMeta) method. Like define row and column via `getSelectedLast` and use the coordinates on the `getCellMeta `method, which looks the following http://jsfiddle.net/handsoncode/3029o398/

**Comment by melloware** [comment]
@AMBudnik that is fantastic! Thanks for this hint.

**Comment by AMBudnik** [comment]
You're welcome @melloware  :)

**Comment by lesterjanpearson** [comment]
This doesnt work on copy paste? its preventing from pasting data

**Comment by melloware** [comment]
You are right.  Looks like I need to figure out a way to allow CTR+C, CTRL+V, CTRL+X.

**Comment by AMBudnik** [comment]
You can create a boolean variable, let's say `isCTRLPressed`, which checks if the last used key is a CTRL or Command (OSX). If you track down (by the `beforeKeyDown`) if the CTRL/CMD is pressed you change the `isCTRLPressed` value to `true`. 
When user clicks another key you check if that is a digit or `'c'/'v'/'x'`. Otwerwise when `isCTRLPressed` returns `false` you just skip the `'c'/'v'/'x'` condition.

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for share it. I hope that we'll be able to publish it soon.

**Comment by lunar-safari** [comment]
The updated method works great, thanks! 
Shame they can't do something like....
```
{
        type: 'numeric',  
        numericFormat: { pattern: '0,0' },
        strict: true     // <====
      },
```

**Comment by JakeAlmer** [comment]
This works pretty good but note it lets you copy paste junk data in so its not full proof.

**Comment by melloware** [comment]
@JakeAlmer Agreed its not perfect, but feel free to help refine it!  I wrote this method for a client and its definitely not bulletproof.

**Comment by jaco-pixeldump** [comment]
hello,

just to refine @melloware beforeKeyDown evt

...
                       var isNumeric = (e.target.selectionStart === 0 && key == 109
                                         || [8, 9, 13, 46, 116, 123, 189, 190].indexOf(key) > -1
                                         || (key >= 35 && key <= 40)
                                         || (key >= 48 && key <= 57)
                                         || (key >= 96 && key <= 105))

...

this let you input negative number taking care of right position, just first char

**Comment by Jimmy-CY-Yang** [comment]
> This works pretty good but note it lets you copy paste junk data in so its not full proof.

I added the 'beforeChange' event to prevent pasting junk data:

```
beforeChange: function(changes, source) {
        if (source === 'CopyPaste.paste') {
          // check every paste value in numeric cell, if not numeric, set value to null
          changes.forEach((element, index) => {
            // element: [row, prop, oldVal, newVal]
            let row = element[0];
            let col = this.propToCol(element[1]);
            let cellType= this.getCellMeta(row, col).type;
            if (cellType=== "numeric" && isNaN(element[3])) {
              element[3] = null;
            }
          });
        }
      },
```

**Comment by adrianszymanski89** [comment]
Hi @Jimmy-CY-Yang 

Thank you for your input.
