### ISSUE TITLE
Add utils that check className.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#4972]
### Description
Because `className` can be `String` or `Array` it would be good to have a class which handle `className` appropriately.

**Comment by AMBudnik** [comment]
Again thank you for sharing!
I am closing this proposition of a change as we are not currently working on the piece of code that it relates to.
Once we open an issue we check all pinned issues and pull requests even if they are closed so please keep track of updates to this issue. All additional comments are also highly appreciated.
