### ISSUE TITLE
Not working with Angular 5  in production mode

### ISSUE THREAD

**Issue by Polyterative** [handsontable/handsontable#4978]
### Description

Handsontable gets incorrectly uglifyed by angular 5. 
When enabling `--build-optimizer=true` or just `--prod` in  Angular 5's `ng build` (building production bundles) the resulting bundle does not work. 

[The error itself](https://i.imgur.com/yfxh5Bi.png)
Sourcemaps were activated

Working build script:         
- `ng build    --prod  --env=prod      --build-optimizer=false -aot=true`

My NOT working build script:

-  `ng build    --prod  --env=prod      --build-optimizer=true  -aot=true`

### Steps to reproduce

When using Angular 5 `ng build ` just build in production with `--prod`. It won't work because Angular's build optimizer corrupts handsontable's code for some reason

### Demo

~

### Your environment
* Handsontable version: 0.38.1
* Browser Name and version: Chrome  65.0.3325.181 
* Operating System: Windows 10 64bit, Mac OS

**Comment by AMBudnik** [comment]
Hi @Polyterative 

have you tried our [Angular wrapper](https://github.com/handsontable/angular-handsontable)?

**Comment by Polyterative** [comment]
Hi, @AMBudnik 
Yes I did. 
I wasn't satisfied so I used the ` .js` directly creating the typings by myself.

**Comment by AMBudnik** [comment]
Can you tell me what was the main reasons that the wrapper failed your expectations?
I am asking as here, in the Vanilla version I do not think that we will make some Angular related changes soon. Most of them are (hopefully) done by the wrapper (if they're possible).

In the case above I am not sure it is wrapper related but if you could share your opinion on the wrapper that would be helpful.

**Comment by MarcusCalidus** [comment]
@Polyterative 
could you please post your tsconfig.json? I was able to reproduce the exact same problem using Angular 6.1.6 ... as well as with the Angular Wrapper and the "normal" js version.

It works however with following module and target settings:
```
"module": "es2015",
"target": "es5",
```

**Comment by Polyterative** [comment]
@MarcusCalidus 
Here it is.
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "alwaysStrict": true,
        "strictNullChecks": false,
        "strictPropertyInitialization": true,
        "target": "es6",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2017",
            "dom"
        ],
        "paths": {
            "@app": [
                "src/app"
            ],
            "@app/*": [
                "src/app/*"
            ],
            "@env": [
                "src/environments"
            ],
            "@env/*": [
                "src/environments/*"
            ]
        }
    },
    "exclude": [ "bin", "node_modules" ]
}
```

HS works in my current production with Angular 6 with the above caveat
If I can help you in anyway feel free to ask

**Comment by wojciechczerniak** [comment]
If I understood correctly this issue was resolved with the configuration shown above.
