### ISSUE TITLE
Specific row or cell validation

### ISSUE THREAD

**Issue by evenmind** [handsontable/handsontable#4985]
### Description
Hi, is there a way to validate only a specific row or cell instead of validate all cells in the table with hot.validateCells() ? I have a huge table with +5k rows so it takes to much time to validate all cells. I would like to validate only one row because I use "autosave" so after a cell is changed I update the entier row in database, but i need to know if all cells in this row are valid. 

Thank you in advance.

### Your environment
* Handsontable version:  1.18.1

**Comment by AMBudnik** [comment]
The conversation has already been continued at https://forum.handsontable.com/t/validate-a-specific-row-or-cell/1931/4

**Comment by gebrits** [comment]
Why is this closed? Seems unresolved

**Comment by AMBudnik** [comment]
hey @gebrits the topic is continued on forum https://forum.handsontable.com/t/validate-a-specific-row-or-cell/1931/2 if that's TLTR Handsontable currently works the way you validate all the cells via `validateCells()`. However, you can also call methods for rows and columns

https://handsontable.com/docs/7.2.2/Core.html#validateRows
https://handsontable.com/docs/7.2.2/Core.html#validateColumns

In this process, you end up with many calls to the renderer. That is why we are working on this topic https://github.com/handsontable/handsontable/issues/5769

**Comment by patrickryan79** [comment]
Not sure if this helps anyone, but I'm able to trigger validation on a specific cell by re-setting its value.

`getColHeader` will get you the headers where you can find the index of the column you want to validate unless you already know it.
`getDataAtCell` will get you the current value
`setDataAtCell` using the same value will trigger validation.

Let me know if there's a better way to do this. My particular use-case was if a country changed, depending on its value determined whether or not the region was required. So in the validator for country, I can fire off the region validation. Heck my implementation was from forever ago and now I'm in the new docs so this could be obsolete.

As far as validating a row, you can pass in the index of the row:

`hot.validateRows([3, 4, 5], (valid) => {})`

https://handsontable.com/docs/7.4.2/Core.html#validateRows
