### ISSUE TITLE
I can not copy\paste content when it is in the jQuery modal dialog box

### ISSUE THREAD

**Issue by GitSergeyGit** [handsontable/handsontable#4987]
### Description

Hello everyone, there is a similar question [here](https://github.com/handsontable/handsontable/issues/1480), the fact is that I can not copy / paste inside the modal window, The problem is exactly like [here](http://jsfiddle.net/734r3/)
added
```
$.widget( "ui.dialog", $.ui.dialog, {
            /*! jQuery UI - v1.10.2 - 2013-12-12
            *  http://bugs.jqueryui.com/ticket/9087#comment:27 - bugfix
            *  http://bugs.jqueryui.com/ticket/4727#comment:23 - bugfix
            *  allowInteraction fix to accommodate windowed editors
            */
            _allowInteraction: function( event ) {
                if ( this._super( event ) ) {
                    return true;
                }
                // address interaction issues with general iframes with the dialog
                if ( event.target.ownerDocument != this.document[ 0 ] ) {
                    return true;
                }

                // address interaction issues with dialog window
                if ( $( event.target ).closest( ".handsontable" ).length ) {
                    return true;
                }

                // address interaction issues with iframe based drop downs in IE
                if ( $( event.target ).closest( ".handsontable" ).length ) {
                    return true;
                }
            },
            /*! jQuery UI - v1.10.2 - 2013-10-28
            *  http://dev.ckeditor.com/ticket/10269 - bugfix
            *  moveToTop fix to accommodate windowed editors
            */
            _moveToTop: function ( event, silent ) {
                if ( !event || !this.options.modal ) {
                    this._super( event, silent );
                }
            }
        });
 $(document).ready(function () {
            /**
             * overriding jqueryui dialog
             */
            (function($) {
                $.widget("ui.dialog", $.ui.dialog, {
                    _allowInteraction: function(event) {
                        console.log("override");
                        if(this._super(event)) {
                            return true;
                        }
                        return $(event.target).hasClass('copyPaste');
                    },
                });
            })(jQuery);
```
found [here](https://stackoverflow.com/questions/33273094/handsontable-cannot-type-in-jquery-ui-dialog)
but nothing helps

**Comment by AMBudnik** [comment]
Hi @GitSergeyGit 

In one of these issues, there was a link to this workaround http://jsfiddle.net/9zwoy5fn/? Have you already tested it?

ps. Can you share a demo? I will test it and check if there anything we can do with it now (a workaround) or need to wait for the official fix.

**Comment by GitSergeyGit** [comment]
@AMBudnik 
only managed to reproduce)
[ind.zip](https://github.com/handsontable/handsontable/files/1870962/ind.zip)

**Comment by AMBudnik** [comment]
Thank you for sharing @GitSergeyGit 

You are right. It doesn't work. The data is not copied at all and we can paste data only in the edit mode of a cell. 

I have tried to add a `contextMenu` to check if pasting works from a button but something is stealing the click event and the menu is not working at all (I have tried to make a column `readOnly`). I do not know if Handsontable can get the focus back or keep it before it is passed further.

**Comment by GitSergeyGit** [comment]
@AMBudnik,
an error was detected
the problem was in this line
`$ ('# modalItemDel'). modal ('show');`
after I removed it all works correctly

**Comment by AMBudnik** [comment]
Great! Thank you for an update. Are the `contextMenu `works now for you as well or should I report it to the team?

**Comment by GitSergeyGit** [comment]
Yes, everything works as it should, thanks

**Comment by AMBudnik** [comment]
Thanks for the confirmation. I guess that we can close the issue.
