### ISSUE TITLE
beforeAutofill method;baseRange argument is undefined

### ISSUE THREAD

**Issue by zohar001** [handsontable/handsontable#4989]
### Steps to reproduce

`1.var
    container = document.getElementById('example1'),
    hot;
  
  hot = new Handsontable(container, {
    data: Handsontable.helper.createSpreadsheetData(100, 18),
    rowHeaders: true,
    colHeaders: true,
    contextMenu: true,
    mergeCells: true
  });`
`2.hot .addHook('beforeAutofill', function(start, end, data, baseRange) {
			console.log(data);
			console.log(baseRange);
		});`
3.

### Demo

https://jsfiddle.net/handsoncode/3gas9z6q/

### Your environment
* Handsontable version:0.38.1
* Browser Name and version:chrome65
* Operating System:win10

**Comment by AMBudnik** [comment]
Thank you for sharing this issue report. It looks like we're missing some documentation on that hook.

It states at https://docs.handsontable.com/pro/Hooks.html#event:beforeAutofill

that 

> The coordinates of the base area for autofill.

but we do not write anything about the 'base area' and what exactly it is.

**Comment by AMBudnik** [comment]
The 4th argument is currently unavailable https://github.com/handsontable/handsontable/blob/5.0.1/src/pluginHooks.js#L605
