### ISSUE TITLE
getLastVisibleRow is returning null

### ISSUE THREAD

**Issue by 29thfloor** [handsontable/handsontable#4990]
I'm trying to debug an issue where in certain cases, clicking to edit a cell is causing the viewport to scroll to the top. Most times we're finding that the user has their browser zoomed in and having them zoom out "fixes" the issue.

I don't know if there's a way I can show an example of what's happening but I think I see where this is happening in the HoT code.

In `WalkontableScroll.scrollViewport`, `this.getLastVisibleRow()` is returning `null`, which is causing `topOverlay.scrollTo(coords.row, true);` to be called, which is somehow calculating a `newY` value of `-694`. So the user clicks to edit a cell and the viewport tries to scroll to -694 which causes it to scroll back to the top of the page.

I know this isn't much to work with but I'm wondering if you can think of a reason why getLastVisibleRow() would return null, specifically when the viewport is zoomed in or the table is being displayed in a small viewport. As long as a table has visible rows I would think that should return *something*.

**Comment by AMBudnik** [comment]
Hi @29thfloor 

Can you tell me what are the steps to get the `null` value for `getLastVisibleRow`? Is it any specified zoom value or container size?

**Comment by AMBudnik** [comment]
I am closing this issue as there's no reply for nearly 2 weeks
