### ISSUE TITLE
Ajax and row update

### ISSUE THREAD

**Issue by kakariko-village** [handsontable/handsontable#4991]
### Description
Hi,  is there anyway to use Ajax in one cell (like dropdown menu) then updating the whole row that cell belong with Handsome table?

### Demo
```
var tableHeader = [
  "Type",
  "Name",
  "Data",
  "User",
  "Token",
  "Timestamp"
];

var tableColumns = [
    {
        data: "type",
        type: 'dropdown',
        source: [typeOne, typeTwo, typeThree]
    },
    {
        data: "user_name"
    },
    {
        data: "user_data"
    },
    {
        data: "username"
    },
    {
        data: "token",
        type: 'dropdown',
        source: tokenList
    },
    {
        data: "timestamp"
    }
];

$('#logTable').handsontable({
    stretchH: 'all',
    allowInvalid: false,
    rowHeaders: true,
    colHeaders: tableHeader,
    columns: tableColumns,
    minSpareRows: 1
});

```
### Your environment
* Handsontable version: 0.21.0
* Browser Name and version: All browsers
* Operating System:  Windows 10

**Comment by AMBudnik** [comment]
Hi @kakariko-village 

Can you give me an example of use? I am not sure if I understand it correctly.

**Comment by kakariko-village** [comment]
I updated the source code, please read first post. The idea is when "type" cell change (it's a dropdown list), the whole row is updated too with data come from ajax call. I don't know how to trigger the change event of certain cell and how to update the row that cell belongs to.

**Comment by AMBudnik** [comment]
Thank you for sharing additional information. 

What you should consider is the [`afterChange `hook ](https://docs.handsontable.com/pro/1.18.1/Hooks.html#event:afterChange) that will listen to the `type` cell. If it meets the change requirements use the [`setDataAtCell()` method](https://docs.handsontable.com/pro/1.18.1/Core.html#setDataAtCell) to replace the content of cells in the corresponding row.

The row, column, old value and new value of the cell are provided via `afterChange `hook parameters.
