### ISSUE TITLE
Incomplete blockCalculation feature for selection

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4996]
### Description

The documentation states that the `blockCalculation` contains only `row` and `column` but in fact, this object supports additionally `cell` and `cells` properties (https://github.com/handsontable/handsontable/blob/develop/src/selection/mouseEventHandler.js). The problem with this new properties is that they are used interchangeably in the source code and this should be standardized to use only the `cell` property. The most of plugin what I found uses the `cell` property.

### Your environment
* Handsontable version: 0.38.1
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Still remains the same, for docs version 7.4.2.

The documentation states that the 4th parameter of the `beforeOnCellMouseDown` callback is an object that shares `row`, `column` and `cells` objects

![Zrzut ekranu 2020-05-5 o 10 58 28](https://user-images.githubusercontent.com/10757813/81049989-8fc26180-8ebf-11ea-8114-e9370a8f858c.png)

However, the proper key is `cell`, so there's a typo

![Zrzut ekranu 2020-05-5 o 11 00 59](https://user-images.githubusercontent.com/10757813/81050093-b97b8880-8ebf-11ea-8ea9-50905f6746a2.png)

Demo https://jsfiddle.net/trhznf17/1/

Additionally, the 4th parameter is not well explained. Whatever I do they all seem to return `false`.

This also applies to `beforeOnCellMouseOver` callback.
