### ISSUE TITLE
Can you drag a cell down to get the next number sequentially

### ISSUE THREAD

**Issue by akrome11** [handsontable/handsontable#5003]
I am looking for the feature where like excel if you have a column with an id of 1 and you select and and drag it down it will filll in the columns with the next number sequentially so 2,3,4 ect.. I see that with the examples if you do this is fills it in with the same data so 1,1,1,1. I was wondering if this feature exists.

**Comment by AMBudnik** [comment]
Hi @akrome11 

we do not have the autoincrement feature yet. But personally, I think that it is very useful.

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for share it. I hope that we'll be able to publish it soon.
