### ISSUE TITLE
Handsontable render height issue

### ISSUE THREAD

**Issue by abtx** [handsontable/handsontable#5006]
### Description
Handsontable is not updating its height correctly when the `render()` is called. The table is rendered correctly to begin with, then data object gets content appended to it and `render()` is called on the HT instance. 

The height is updated only after having scrolled a little bit into the new appended content (i.e. inside of the container which behaves like `overflow` is set to `scroll`). Only then the table height is expanded. 

Appending more data makes the container height incorrect too.

Desired behaviour would have the table container to reflect the height correctly and immediately after the `render()` is called.

EDIT: it's the `wtHider` element not sized correctly, and it's height is set explicitly

### Steps to reproduce

1. Create a HT with some data
2. Try pushing new elements to your data array 
3. Scroll down

### Your environment
* Handsontable version: ^0.38.1
* Browser Name and version: Opera 52.0.2871.40
* Operating System: OSX

**Comment by AMBudnik** [comment]
Can you record the behavior? I guess that I do not understand it correctly.

Here's a demo I've made http://jsfiddle.net/handsoncode/swmfkgnb/ and the video where I track table height. 
![gif4445](https://user-images.githubusercontent.com/10757813/38483999-404b5a92-3bd5-11e8-8e12-a3a4b514cce6.gif)

Also I do not know why you refer to the `wtHider`. It always has the same height when a new element is added.

![gif4446](https://user-images.githubusercontent.com/10757813/38484073-92c9fc4c-3bd5-11e8-94e5-3e9fc5e01db8.gif)

Please let me know what I'm missing here.

**Comment by abtx** [comment]
@AMBudnik I'm using Angularjs and adding more data to the scope variable, which I use for `data` in HT. Here's a demo:
![ht-issue](https://user-images.githubusercontent.com/5509711/38487292-399eb8a0-3c12-11e8-9dad-2efe3d43ac4b.gif)

**Comment by abtx** [comment]
Another weird artefact I'm getting when scrolling, seems that the `render` has some issues with HT's ghost table:
<img width="1211" alt="screen shot 2018-04-09 at 16 26 46" src="https://user-images.githubusercontent.com/5509711/38487508-fa90eab0-3c12-11e8-82ba-9b976afa6389.png">

**Comment by AMBudnik** [comment]
I have a few questions @abtx  as I'm not able to replicate in on vanilla
Do you use the AngularJS wrapper from https://github.com/handsontable/ngHandsontable?
Do you use the latest Handsontable version 0.38.1 CE/1.18.1 PRO?

**Comment by abtx** [comment]
I'm not using AngularJS, and using version ^0.38.1

**Comment by AMBudnik** [comment]
Are you able to send any demo of tests @abtx? That would help us a lot.

**Comment by AMBudnik** [comment]
Sorry, that was a typo.

I meant any demo that we can download or open online and debug. Cause without a code that represents the bug I am not able to do anything productive - only divagate about the issue.

**Comment by abtx** [comment]
I've tried to do `hot.getData().push(el);` and re-rendering instead of appending to the scope object and re-rendering (as in [this example](http://jsfiddle.net/yk64yv8q/4/)), but that sadly doesn't seem to do the job

**Comment by abtx** [comment]
It seems that wrapping HT initialisation in a function and running it when new data is appended to the datasource removes the weird on-scroll behaviour, but the height and width of HOT are calculated incorrectly (ie. there's an added white space on both horizontal and vertical axes)

**Comment by AMBudnik** [comment]
I have replicated the issue on Safari on OSX on my colleagues device. I have seen this issue before somewhere...

**Comment by AMBudnik** [comment]
First associated issue can be this one https://github.com/handsontable/handsontable/issues/3433 but the second one that looked the same seem to be missing. I will search for it and pin it up when I find it.

**Comment by AMBudnik** [comment]
Did you find it working on any version before 0.38.1?

**Comment by abtx** [comment]
@AMBudnik hi Alex, no, this is the only version I worked with. I've tested on OSX Sierra 10.12.6 Opera 52.0.2871.40,  Chrome 65.0.3325.181, Safari 10.1.2 (12603.3.8) doesn't display the table at all, and Firefox Quantum 60.0b9 (64-bit). Is there another HOT version I should try and see if it will work for me?

**Comment by AMBudnik** [comment]
As I cannot find the issue that had a very similar video for your image

<img width="1211" alt="38487508-fa90eab0-3c12-11e8-82ba-9b976afa6389" src="https://user-images.githubusercontent.com/10757813/38735767-130727de-3f2a-11e8-86c3-e3b4f261b346.png">

I think that the issue has been fixed, but none of the versions refer to a different scenario. Maybe this one https://github.com/handsontable/handsontable/issues/3204, but it is an old version - 0.23.0

**Comment by abtx** [comment]
@AMBudnik did you say you did reproduce this issue though? The linked issue might be related but it's different to the one here :/

**Comment by AMBudnik** [comment]
Yes, I thought that maybe it's a regression.

I'll ask our devs to investigate this issue.

**Comment by abtx** [comment]
Anyone having this issue please try and test with [this CDN](https://docs.handsontable.com/2.0.0/bower_components/handsontable/dist/handsontable.full.js).

**Comment by Prahadeesh92** [comment]
Handsontable version 7.2.2. Same issue occurs for me. Is this issue fixed?

**Comment by waqasnazir1** [comment]
Same issue occurs for me. Any solution?

**Comment by AMBudnik** [comment]
Hey @waqasnazir1 @Prahadeesh92 
Can you share your implementation with me on support@handsontable.com?
