### ISSUE TITLE
[mobile] Warning in console may be showed when fast touch actions are performed

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#5009]
### Description
When @krzysztofspilka played a little bit with the demo by dragging and dropping the selection (randomly, very fast), the console warning appeared: `[Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`.

![screen shot 2018-04-09 at 15 56 39](https://user-images.githubusercontent.com/141330/38502059-bd7ffce6-3c0e-11e8-8314-e9bcfbd3b8e6.png)

### Demo

https://jsfiddle.net/handsoncode/3gas9z6q/

### Your environment
* Handsontable version: 1.18.1
* Browser Name and version: Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1
* Operating System: iPad with iOS 10.3.3

**Comment by AMBudnik** [comment]
Hey. 
According to our recent policy, I am closing this proposition of a change as we are not currently working on the piece of code that it relates to.
Once we open an issue we check all pinned issues and pull requests even if they are closed so please keep track of updates to this issue. All additional comments are also highly appreciated.
