### ISSUE TITLE
context menu delete rows returns on 1 index in beforeRemoveRow

### ISSUE THREAD

**Issue by lesterjanpearson** [handsontable/handsontable#5012]
How to get all the index that I will remove using the context menu remove?

```
hot.addHook('beforeRemoveRow', function(index, amount) {
        console.log(index);      
});
```

**Comment by AMBudnik** [comment]
Hi @lesterjanpearson 

I've already sent my comment to https://github.com/handsontable/handsontable/issues/806 but we can continue the conversation here.

Can you share the requirements? Do you need indexes or removed rows? If so, [the 3rd parameter of the `beforeRemoveRow` returns them](http://jsfiddle.net/handsoncode/47qf33gk/). The issue may be a little bit more complicated if you use filtering or sorting.

**Comment by lesterjanpearson** [comment]
looks like this is what I am looking for, thanks

**Comment by AMBudnik** [comment]
Great! I'm happy to hear that. I guess that we can close the issue.
