### ISSUE TITLE
Can the table be dropdown and increase?

### ISSUE THREAD

**Issue by setWan** [handsontable/handsontable#5013]
Hi @AMBudnik 
Can a table have the same drop-down number as Excel does increase?

![_20180410184632](https://user-images.githubusercontent.com/31428016/38552703-8e289872-3cef-11e8-8e18-0dd5d6669c92.png)

**Comment by AMBudnik** [comment]
Sorry, but we do not have this feature implemented yet. 
Please track progress on this issue for updates https://github.com/handsontable/handsontable/issues/5003
