### ISSUE TITLE
error run in linux

### ISSUE THREAD

**Issue by ezaohei** [handsontable/handsontable#5018]
### Description
helio, I happened an issue, I deployed handsontable in linux server.
then visit this page from IE(version 11) and Firefox explorer,  Firefox can work, but IE  happen error, error decription [SCRIPT1010: Expected identifier].

then I try to doployed handsontable to wondow server, visit by Firefox and IE both can work as normal.

I just used lastest handsontable version, still have this issue.

### Your environment
* Handsontable version:handsontable-0.34.5
* Browser Name and version: IE 11
* Operating System: Linux version 2.6.32-279.19.1.el6.x86_64

thank you very much.

**Comment by AMBudnik** [comment]
Hi @ezaohei 

Can you share any example that we can test?

**Comment by AMBudnik** [comment]
I believe that this is no longer an issue as there are 2 weeks now without a comment.
