### ISSUE TITLE
Dropdown cell type doesn't work with nestedRows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5019]
### Description

Reported at: https://forum.handsontable.com/t/nested-rows-dropdown-inot-closing-ssue/1960

The dropdown list doesn't close and we are able to select any other cell.

### Steps to reproduce

1. Pick any dropdown option from the last column.

![23gif](https://user-images.githubusercontent.com/10757813/38603666-86354dde-3d6e-11e8-8d90-f4667990e546.gif)

It only works via `columns` when we do not pass `data` http://jsfiddle.net/handsoncode/2t57228w/ but then we are not able to use the `nestedRows `functionality.

### Demo

http://jsfiddle.net/handsoncode/vybq8hh2/

### Your environment
* Handsontable version: 1.18.1
_The issue doesn't seem to be related to any version._
* Browser Name and version: Chrome 65
* Operating System: Windows 10

**Comment by devil1bi** [comment]
when will this be fixed?

**Comment by AMBudnik** [comment]
Hi @devil1bi 

The issue is pretty new and it hasn't been scheduled yet. We schedule our releases 1 month upfront. Now we have scheduled work for more than 2 releases as we are planning to fix/rewrite important parts of the library.

**Comment by AMBudnik** [comment]
It works the same in v 5.0.1

**Comment by AMBudnik** [comment]
The issue remains the same in 8.0.0.-beta2-rev6 http://jsfiddle.net/vqo2grxj/

**Comment by AMBudnik** [comment]
The _album_ cell (dropdown column) has been defined as an array (not a single value) so the implementation was incorrect. If we change the cell in that column to a single value dropdown works well.
