### ISSUE TITLE
Devtools switch for puppeteer

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#5021]
### Description

When the developer wants to debug tests it is necessary to change the options in two places of the `test/script/run-puppeteer.sh` file. The developer has to set `devtools` property to `true` and comment/delete `--headless` argument from launch options.

The idea is to add a variable which will be responsible for setting those settings from a single line.

### Your environment
* Handsontable version: -
* Browser Name and version: -
* Operating System: any

**Comment by budnix** [comment]
The same action has to be added to the handsontable-pro repo.

**Comment by swistach** [comment]
This issue is closed temporarily. We will reopen it for development as it became a part of the test environment improvements task reported at #7581
