### ISSUE TITLE
[0.30.0+] Fill handle double-click fills left instead of down

### ISSUE THREAD

**Issue by djcooke** [handsontable/handsontable#5023]
### Description
When you double-click the fill handle for a cell, the value in that cell should be autofilled into all of the cells below it as long as data has been entered in the cell to the left of the one being filled. This works correctly as long as there is at least one applicable cell to fill.

If the column to the left is empty, then double-clicking the fill handle causes the autofill to happen sideways, filling all cells to the left. The same happens if there is data in one cell to the left, but not in any below.

### Steps to reproduce
1. start with a blank Handsontable at least 3x3
2. enter any value into cell B1 (middle top if the table is 3x3)
3. double-click the fill-handle for B1. The value will be copied left

### Demo
https://jsfiddle.net/6zgv3exz/15/

If you double-click the fill handle on the cell containing '2', the value is autofilled down as expected. If you double-click the fill handle on either of the cells containing '3' or '4', the value is autofilled left instead.

### Possible solution

Initializing `lastFilledInRowIndex` to `-1` [here](https://github.com/handsontable/handsontable/blob/c6bcadac818374b311a2965272a79c49ced0b1f7/src/plugins/autofill/autofill.js#L330) probably fixes the problem, which occurs when the following loop has zero iterations.

I have made a different change to my local copy as we wanted the autofill to extend to the bottom of the table regardles of whether there is any data to the left.

### Your environment
* Handsontable version: 0.38.1
* Browser Name and version: Firefox 59.0.2
* Operating System: Ubuntu

**Comment by AMBudnik** [comment]
Thank you for sharing this scenario. The behavior of autofill in inconsistent.

![gif](https://user-images.githubusercontent.com/10757813/38670728-e484111e-3e49-11e8-8bb4-6188954bcbfd.gif)

If we get `2` in `B1:B3` we should get `3` in `D1:D3` instead od `C1:D1`

**Comment by AMBudnik** [comment]
Here's how the example worked before we made a refactor in v `0.30.0`.


![22gif](https://user-images.githubusercontent.com/10757813/39036664-7c9d46ca-447e-11e8-8385-3e4f8cdaa1f5.gif)
v `0.29.2.`. It simply did not do anything for value `3`. I will mark it as a regression but maybe we should consider checking if the `3` can act like `2` a populate the value to `D2` and `D3 `cells.

**Comment by kalugny** [comment]
I am also suffering from this problem

**Comment by wojciechczerniak** [comment]
5.0.2-RC: https://jsfiddle.net/rdhktn3f/ 👍

**Comment by AMBudnik** [comment]
Thank you. Issue solved in v 5.0.2
