### ISSUE TITLE
Validate a single cell

### ISSUE THREAD

**Issue by briancaldass** [handsontable/handsontable#5024]
How can I validate a single cell, after editing it? In the documentation I do not see what function can help me, since I have a performance problem in my app, I can not use validate row or validate columns or validatecells. If I already have this topic, pass me the id of the issue

**Comment by AMBudnik** [comment]
Hi @briancaldass 

a similar issue has been already raised at https://github.com/handsontable/handsontable/issues/3276
Please track progress to this ticket for updates
