### ISSUE TITLE
Dropdown/autocomplete menu hidden with preventOverflow

### ISSUE THREAD

**Issue by djcooke** [handsontable/handsontable#5032]
### Description
When `preventOverflow: 'horizontal'` is used, dropdown/autocomplete menus for the bottom table row(s) are hidden. This may include multiple rows. It is most obvious when the table has only one row, in which case no dropdowns will ever be visible.

### Steps to reproduce
1. Create a table with the setting `preventOverflow: 'horizontal'` that includes a dropdown column
2. Try to open the dropdown menu for the last row in the table
3. The menu is not visible

### Demo
https://jsfiddle.net/gjy5ncr9/6/

### Work-around
This probably isn't a proper fix, but the change I've made locally to work around this issue is to add the following css:

```
.handsontableEditor.autocompleteEditor, .handsontableEditor.autocompleteEditor .ht_master .wtHolder {
  min-height: 138px;
}
```

Demo of work-around: https://jsfiddle.net/gjy5ncr9/5/

### Your environment
* Handsontable version: 0.38.1
* Browser Name and version: Firefox 59.0.2
* Operating System: Ubuntu

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report and for your time to investigate it,

As an older task (here https://github.com/handsontable/handsontable/issues/3828) for the same issue already has a milestone attached I need to close this report. However, I've left there a note that you've found a workaround. I think that a lot of users will find it useful 👍
