### ISSUE TITLE
Installing handsontable

### ISSUE THREAD

**Issue by arunkumar413** [handsontable/handsontable#5033]
### Description

Unable to install handsontable. Getting a 404 error for handsontable.full.js

I tried the 3 steps mentioned in [this](https://docs.handsontable.com/2.0.0/tutorial-quick-start.html) guide to get started with handsontable. However there seems to be an issue with handsontable npm install. Is there a client side library as well?

arun@devilbox ~ $ sudo npm install handsontable
[sudo] password for arun: 
npm WARN saveError ENOENT: no such file or directory, open '/home/arun/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/arun/package.json'
npm WARN arun No description
npm WARN arun No repository field.
npm WARN arun No README data
npm WARN arun No license field.
+ handsontable@2.0.0
updated 1 package in 2.066s
arun@devilbox ~ $_ 

### Your environment
* Handsontable version:
* Browser Name and version: firefox
* Operating System: Linux Mint 18

**Comment by AMBudnik** [comment]
Hi @arunkumar413 

If you install the package inside an empty directory (without npm project initialized `npm init`) that message doesn't mean that something is wrong. You should be able to use it.

Here's the same situation, where I've just created a directory and installed Handsontable

![image](https://user-images.githubusercontent.com/10757813/38792274-7e55fe1a-414c-11e8-8d5b-ad0aaf255d20.png)

Here's what you should get in the project directory

![image](https://user-images.githubusercontent.com/10757813/38792304-a46f1032-414c-11e8-93cf-af8dbbd97aa5.png)

so if I add a `index.html` file in the app directory I refer to the resources via

```
<link rel="stylesheet" href="node_modules/handsontable/dist/handsontable.full.css">
<script src="node_modules/handsontable/dist/handsontable.full.js" charset="utf-8"></script>
```

and if you use a simple implementation like this one

```
<html>
  <head>
    <link rel="stylesheet" href="node_modules/handsontable/dist/handsontable.full.css">
    <script src="node_modules/handsontable/dist/handsontable.full.js" charset="utf-8"></script>
  </head>
  <body>
    <div class="container"></div>
    <script>
      var container = document.querySelector('.container'), hot;
      hot = new Handsontable(container, {});
    </script>
  </body>
</html>
```

you should get an empty table 

![image](https://user-images.githubusercontent.com/10757813/38792460-588e5b04-414d-11e8-9a2c-23b2ab6f22a6.png)

I was testing it on Windows. Unfortuantely I do not have any device with native Linux.

Please redo the following steps and let me know if it still doesn't work for you.

**Comment by AMBudnik** [comment]
I believe that we can close this issue as there are no additional questions for more than a week.
