### ISSUE TITLE
isSorted returns true after running setSortingColumn on every column to be 'undefined'

### ISSUE THREAD

**Issue by khansf** [handsontable/handsontable#5037]
### Description
Even after looping trough the column numbers and setting their sort to 'undefined' on all of them, the isSorted() still returns true.

The check for isSorted that returns true happens in afterChange, but the loop happens before that.
### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version:     "angular-handsontable": "^1.0.0-beta3", "handsontable-pro": "^1.15.1",
* Browser Name and version: Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System: MAC

**Comment by AMBudnik** [comment]
Hi @khansf I believe that you have experienced this issue https://github.com/handsontable/handsontable/issues/3434
If I'm wrong let me know the details and we'll reopen the ticket.

**Comment by khansf** [comment]
Yes updateSettings did not work for me either, I had use sortOrder variable instead of isSorted.

**Comment by AMBudnik** [comment]
This issue should be solved with the `updateSettings` refactor + fix. We are planning it for June, so please stay tuned with [our ZenHub](https://app.zenhub.com/workspace/o/handsontable/handsontable/boards?repos=1790564,85198294) to track progress

**Comment by khansf** [comment]
Thank you!
