### ISSUE TITLE
Determine source index from `afterChange` row index with sorting or filtering

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5040]
### Description
Maybe I missed it but I can't find a way to determine the source data index from the `afterChange` hook's row index, regardless if you have sorting or filtering applied. I did try ColumnSorting plugin `untranslateRow()` but this gives `undefined` if no sorting is applied and doesn't seem to take into account filtering.

### Steps to reproduce

1. Enabled `filters`
2. Apply a filter
3. Handle `afterChange` and inspect a change's `row` value
4. Try to correlate that `row` value to what's in your source data

### Demo

http://jsfiddle.net/wLjuj5fh/
In the above apply a sort and filter then make a change to a cell and look at the console output.

### Your environment
* Handsontable version: pro-2.0.0
* Browser Name and version: Chrome 65
* Operating System: MacOS High Sierra

**Comment by AMBudnik** [comment]
I'm not sure if that's what you are looking for but it looks like the `toPhysicalRow` is the method. Here's a demo http://jsfiddle.net/vujby2hm/

Let me know if it's that or I've missed something.

**Comment by aaronbeall** [comment]
Yes, that's exactly what I was looking for! Just to be sure, in this case "visible" does not mean the same thing as `countVisibleRows()` which only accounts for rows rendered within the viewport? That's what I thought `toPhysicalRow()` and `toVisibleRow()` was referring to, but I see that's not the case. IMO the terminology is a bit confusing here. Thank you for the guidance.

**Comment by AMBudnik** [comment]
Yes, the `countVisibleRows `returns a number of visible rows. It doesn't relate to indexes.
Yes, the name of some methods can be a problem. Sometimes we even make debates on how some new functions should be called :)

**Comment by aaronbeall** [comment]
Every developer knows that struggle. :) Thanks for all your help!
