### ISSUE TITLE
[1.10.2+] Editing a cell when filter_by_value is applied clears the filter selection

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5041]
### Description
After you have applied a `filter_by_value` if you make any cell change the filter unselects all values the next time you open it.

### Steps to reproduce

1. Open dropdown menu with `filter_by_value`
2. Unselect one of the values
3. Make a change to the cell
4. Open the dropdown -- all the `filter_by_value` values are unchecked

### Demo
http://jsfiddle.net/kn8hfbgj/

![img](http://g.recordit.co/cISsSeRkGB.gif)

### Your environment
* Handsontable version: pro-2.0.0
* Browser Name and version: Chrome 65
* Operating System: MacOS High Sierra

**Comment by AMBudnik** [comment]
Thank you for sharing this report @aaronbeall 

I have replicated the issue. It acts the same as the one with `checkbox` at https://github.com/handsontable/handsontable/issues/4780

And it's also a regression from `1.10.1`. It's started to erase the results from v `1,10,2`

**Comment by aaronbeall** [comment]
In case it helps something fishy I noticed is that it seems the filter condition args for one column gets mutated when editing another column. What I mean is:

1. Apply filter to column 0
2. In `afterFilter` store the the `conditionsStack` and notice the values in `args` for the `filter_by_value` condition
3. Edit data in column 1 (different column than the filter is applied to
4. In `afterChange` check the state of the object you stored in `afterFilter` and notice that the values in `args` for the `filter_by_value` condition (which still points to column 0) has *changed* to be all the values of the edited column instead

You can see it on the console logs of this demo: http://jsfiddle.net/1L6wmtg8/

**Console after step 2:**
![image](https://user-images.githubusercontent.com/2973900/38938187-f5ad128a-42f2-11e8-982d-8ac67b1ef5cc.png)

**Console after step 4:**
![image](https://user-images.githubusercontent.com/2973900/38938218-08128a36-42f3-11e8-8553-ab9d83479486.png)

Notice column still is `0` but the `args` have changed to values in the edited column, even though no filter action has occurred.

**Comment by aaronbeall** [comment]
Related case, a little less problematic than the one above but still odd:

![img](http://g.recordit.co/VMVb77m620.gif)

**Comment by AMBudnik** [comment]
Thanks for investigating it. That will surely help.
It looks like a bunch of scenarios can erase the `filter)by_value` list. We may find something else while testing.

**Comment by AMBudnik** [comment]
Hi @aaronbeall 

have you tried it with 5.0.0? It doesn't erase the list for me (Win 10/Chrome 67) and my colleague on OSX

**Comment by AMBudnik** [comment]
It looks like it's fixed. Please let me know if it works for you @aaronbeall and if not I'll reopen the topic.

**Comment by aaronbeall** [comment]
Yep it's fixed in 5.0.0! Thanks!
