### ISSUE TITLE
Possible to add before/afterCellMouseUp hooks?

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#5042]
### Description

Is it possible to add a `(before|after)CellMouseUp` hooks similar to the `(before|after)CellMouseDown` hooks? Would be helpful. We can use the the `afterSelectionEnd` as a similar hook but we need the mouse event to check which mouse button causes the hook/event.

This is our current workaround:
```
afterOnCellMouseDown: (event) =>
{
    this.leftClick = (event.button === 0);
},
afterSelectionEndByProp: (startRow, startProp, endRow, endProp) =>
{
    if (startRow !== endRow || startProp !== endProp || !this.leftClick)
    {
        return;
    }

    // Handle "mouse up" event
},
```

**Comment by AMBudnik** [comment]
Sure. I'll add it to our feature request list.

**Comment by AMBudnik** [comment]
Again thank you for sharing this and [`columnIndex` feature requests.](https://github.com/handsontable/handsontable/issues/4944)
We are closing all the tickets that relate to features that are not in progress nor on our Roadmap. They are still visible on our ZenHub (so please fear not, we won't throw them away).
