### ISSUE TITLE
Fix Walkontable tests

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#5043]
### Description

After migration e2e runner to the puppeteer, the Walkontable tests don't pass when the scrollbars are set as autohidden (macOS). To fix this issue the `--hide-scrollbars` argument should be used (which is by default enabled in headless mode) in the launcher to prevent OS dependant options about scrollbars. Additionally, the Walkontable tests which are dependant on that scrollbars should be fixed to be more agnostic.

### Steps to reproduce

1. Enable autohide scrollbars in macOS preferences;
2. Run tests;
3. In result, several Walkontable tests fail.

### Your environment
* Handsontable version: 2.0.0
* Browser Name and version: -
* Operating System: macOS

**Comment by budnix** [comment]
After investigating the problem I've spotted that the same issue exists for Handsontable tests. These tests should be fixed too.

**Comment by swistach** [comment]
#7296 solves a problem with running Walkontable tests on Windows - it's only the first step to make tests OS/browser-agnostic. Because of that, I leave this issue open.

**Comment by swistach** [comment]
This issue is closed temporarily. We will reopen it for development as it became a part of the test environment improvements task reported at #7581
