### ISSUE TITLE
loadData doesn't seem to work

### ISSUE THREAD

**Issue by PMR18** [handsontable/handsontable#505]
Hi,

I am trying to use the loadData method to render the table with data returned from a .Net webmethod.

``` javascript
 $container.handsontable({

        dataSchema: { StaffId: null, StaffName: null },
        startRows: 5,
        startCols: 2,
        colHeaders: true,
        colHeaders: ['StaffId', 'Name'],
        columns:
        [
            { data: "StaffId" },
            { data: "StaffName" }
        ]
    });

```

Code below is attached to a button to perform the load

``` javascript
 $.ajax({
            url: "Training.aspx/GetStaff",
            data: "{'AssessmentId':'" + Id + "'}",
            dataType: 'json',
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            success: function (data, status) { handsontable.loadData(data); }
        });
```

When I look in Chrome the webmethod does return the data the I am expecting it to (see below) but the table does not render.

{"d":"[{\"StaffId\":648,\"StaffName\":\"Linda Mitchell\"},{\"StaffId\":650,\"StaffName\":\"Hilary Crocker\"},{\"StaffId\":651,\"StaffName\":\"Rosemary Busfield\"},{\"StaffId\":653,\"StaffName\":\"Santa Antonaci\"},{\"StaffId\":654,\"StaffName\":\"Maxine McManus\"},{\"StaffId\":655,\"StaffName\":\"Tendai Zvomuya\"},{\"StaffId\":906,\"StaffName\":\"Anne Nicole\"},{\"StaffId\":1289,\"StaffName\":\"Karen Roscorla\"},{\"StaffId\":1290,\"StaffName\":\"Christina Mullins\"},{\"StaffId\":1291,\"StaffName\":\"Jean Farmer\"},{\"StaffId\":1292,\"StaffName\":\"Francesca Joseph\"},{\"StaffId\":1293,\"StaffName\":\"Jayne Wager\"},{\"StaffId\":1294,\"StaffName\":\"Nicola Walter\"},{\"StaffId\":1295,\"StaffName\":\"Julia Coaker\"}]"}

Any help on what I am doing wrong would be much appreciated.

thanks

Pete

**Comment by mukta88** [comment]
Hello,
I need to append new data to current data in handsontable.
But when I use loaddata, it replaces current data.
What can be a solution?

**Comment by thakursagar** [comment]
Hello all, I try to display dynamic data in handsontable in a new tab(pop-up) but the table does not load on the first time. I have to click in the area where the table will load and then the table shows up. What is the problem here?

Thanks
Sagar

**Comment by PMR18** [comment]
I am on annual leave until 1st Sept. For any support issues please contact richard.chapman@weblogik.co.uk


kind regards

Pete
