### ISSUE TITLE
Undo/redo with minSpareRows

### ISSUE THREAD

**Issue by superfille** [handsontable/handsontable#5053]
### Description
So the problem is that undo and redo does not work if you have minSpareRows set to 1 and change the row before the spare row.

### Steps to reproduce
1. In my fiddle, on the fourth row (Schweiz), from ID to Units enter some random values in each cell
I entered the numbers 1 to 6

4	CHF	CHF	Swiss Franc	0.9775	CHF / USD
My change ->
1	2	3	4	5	6

2. Now do undo with the keyboard (ctrl + z) until you can't do it anymore.
For me, undo works until the Currency column, where it does not change back to Swiss Franc. But if I undo again the Code, Country and ID columns change back to the correct values.

Result after undo to ID column:
4	CHF	CHF	4	0.9775	CHF / USD
Should be
4 CHF	CHF	Swiss Franc	0.9775	CHF / USD

3. Now try doing redo (ctrl+r)
I can only redo the first column (ID)

### Demo
https://jsfiddle.net/14tv0djw/1/

### Your environment
* Handsontable version: 2.0.0
* Browser Name and version: Chrome Version 66.0.3359.117
* Operating System: Windows

**Comment by virror** [comment]
When are this getting fixed? Its a seriously annoying issue for me.

**Comment by AMBudnik** [comment]
I am sorry but it hasn't been planned yet. Maybe we will be able to schedule it for December but the copy-paste meeting is on Tuesday so I am not able to promise anything now.

**Comment by virror** [comment]
Thank you for considering this issue : )

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/4ez0so6n/

**Comment by AMBudnik** [comment]
When we remove all code https://jsfiddle.net/hfct2wm4/1/ that doesn't matter we can see that this is the same issue as https://github.com/handsontable/handsontable/issues/7258

**Comment by AMBudnik** [comment]
Hi @sebworks2024 this issue is closed as it is a duplicate of https://github.com/handsontable/handsontable/issues/7258. Then https://github.com/handsontable/handsontable/issues/7258 is closed as it is a part of the scope of a bigger issue. However, I see that this issue is already on our todo list. I should have an update here shortly.
