### ISSUE TITLE
afterColumnSort fired twice init

### ISSUE THREAD

**Issue by homura** [handsontable/handsontable#5055]
### Description
afterColumnSort is fired twice init. Is there a hook that only fired when sort indicator is clicked

### Steps to reproduce

1. set `columnSortting: { column: index }`

### Demo

https://jsfiddle.net/ayh5jtt5/

### Your environment
* Handsontable version: 2.0.0
* Browser Name and version: Chrome 65.0.3325.181
* Operating System: macOS Sierra 10.12.6

**Comment by AMBudnik** [comment]
Thank you for sharing this issue.

You are right. When we use 

```
columnSorting: {
    column: 2,
    sortOrder: true,
  },
```

the `afterColumnSort` is called twice.

**Comment by pnowak** [comment]
Hook `afterColumnSort` is fired by `sort` method, which in turn is called by the method `sortBySettings`. First call is made by the `afterInit` hook. The second one goes from `afterUpdateSettings`.
And that's why fired twice.

**Comment by AMBudnik** [comment]
Thanks for checking that @pnowak 
I think that we shouldn't change it now so I am closing the issue
