### ISSUE TITLE
Problem when undo a row removal with filtered Rows

### ISSUE THREAD

**Issue by pberge** [handsontable/handsontable#5060]
### Description
If I remove a row and the handsontable is filtered by any value, when I undo the action it doesn't know the table is filtered.

### Steps to reproduce

1. Filter table by value
2. Delete any Row
3. Undo

### Your environment
* Handsontable version: 1.8
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @pberge 

However, I believe that we should stick to this issue https://github.com/handsontable/handsontable/issues/4019 that shares the same issue description.
