### ISSUE TITLE
The minimum height of a row containing merged cells is calculated incorrectly

### ISSUE THREAD

**Issue by aaltaev** [handsontable/handsontable#5066]
### Description
I have a handsontable with such options:
```javascript
data: [
    ["Lorem ipsum dolor sit amet, consectetur adipiscing elit.", "", "", 4, 5],
    ["Lorem ipsum dolor sit amet, consectetur adipiscing elit.", 2, 3, 4, 5]
],
colWidths: 150,
rowHeaders: true,
colHeaders: true,
autoRowSize: true,
manualRowResize: true,
manualColumnResize: true,
mergeCells: [
    {row: 0, col: 0, rowspan: 1, colspan: 3}
]
```
As you may see, I enabled `autoRowSize` in combination with `manualRowResize` and `manualColumnResize`. I also fixed the width of the column with a value of 150 and merged some cells in the first row.

As a result, it is impossible to manually reduce the height of the first row less than a certain value, although it has a lot of empty space.

### Demo
http://jsfiddle.net/7o63zwvr/

### Your environment
* Handsontable version: 0.38.1
* Browser Name and version: All browsers
* Operating System: Windows 10 Enterprise 64 bit

**Comment by AMBudnik** [comment]
Thank you for sharing this issue. You're right the first row shouldn't be so high.

![image](https://user-images.githubusercontent.com/10757813/39420860-b9530bfa-4c66-11e8-85d7-38de7463329a.png)

**Comment by aaltaev** [comment]
Hi @AMBudnik !
Can you please tell when to expect a fix?

**Comment by AMBudnik** [comment]
Hi @aaltaev 

I am sorry but I do not see it on the list for June. We will surely do a second stage of the mergeCells plugin fix but I do not know any date yet.

**Comment by aaltaev** [comment]
Thanks you @AMBudnik !

I have already found a workaround for my work project: disable `autoRowHeight` plugin and set the `viewportColumnRenderingOffset` option so that the row height does not change with horizontal scrolling.
Given that disabling the plugin helped, I assume that the problem is in it.

**Comment by AMBudnik** [comment]
Thank you for sharing the tips @aaltaev

**Comment by AMBudnik** [comment]
Works the same in v7.2.1 http://jsfiddle.net/snx9oe5b/ 
Related (or has the same root) to https://github.com/handsontable/handsontable/issues/4907

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/4796

**Comment by AMBudnik** [comment]
Actually this is the same issue as https://github.com/handsontable/handsontable/issues/4796 cause turning of `autoRowSize` solves the issue.
