### ISSUE TITLE
Refactor of manual row move

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#5068]
### Description
The `manualRowMove` plugin should use array mappers like other plugins (physical indexes inside array should be mapped to visual indexes).

Plugins like `nestedRows` and `columnSummury` should be prepared for a new way of working `moveRow` and `moveRows` functions.

Warn: PRO changes haven't been done yet.

**Comment by wszymanski** [comment]
Plugins like `nestedRows` and `columnSummury` should be prepared for a new way of working `moveRow` and `moveRows` functions.

Warn: PRO changes haven't been done yet.

**Comment by wojciechczerniak** [comment]
Done and merged with #5751
