### ISSUE TITLE
[2.0.0] When using preventOverflow, textarea of overflowed cells is misplaced

### ISSUE THREAD

**Issue by paolostyle** [handsontable/handsontable#5073]
### Description
Title.

### Steps to reproduce
1. https://jsfiddle.net/handsoncode/xugydsf4/
2. Go to cell that is visible only when you scroll the table horizontally, e.g. M24 or any other cell in column higher than M
3. Try editing value in that cell
4. Textarea in which you're editing the value appears in some weird place to the right of the edited cell

Seems like this bug appeared in 2.0.0, it worked fine in 0.38.1, you can see it yourself by changing version of handsontable in that jsfiddle to 0.38.1. Any chance you'll be able to hotfix it in May? Or can you suggest some workaround (other than downgrading to 0.38.1)?

### Your environment
* Handsontable version: 2.0.0
* Browser Name and version: Chrome, Firefox
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @paolostyle 

this issue got solved in 6.1.0 published yesterday. Please update and let me know if it works for you as well
