### ISSUE TITLE
When mergeCells property is defined, some kind of updating data causes Uncaught TypeError

### ISSUE THREAD

**Issue by sgrit** [handsontable/handsontable#5075]
### Description
When mergeCells property is defined, some kind of updating data causes Uncaught TypeError. I found it occurs when one of the mergedCells' colspan is 1 and then try to delete a column (or columns).

### Steps to reproduce

See jsfiddle below.

### Demo

https://jsfiddle.net/8ffpsqt6/18/

### Your environment
* Handsontable version: 2.0.0
* Browser Name and version: Chrome 61.0.3163.100 (Official Build)
* Operating System: Windows 10

### My countermeasure
Tentatively, I inserted following code into the head of  applySpanProperties function.
```
  if (!TD) {
    return;
  }
```

**Comment by sgrit** [comment]
For version 3.0.0 or newer, this problem seems to be resolved. Thank you.

**Comment by AMBudnik** [comment]
Ok, great! Thank you @sgrit
