### ISSUE TITLE
getData() with the format of getSourceData()

### ISSUE THREAD

**Issue by betslayer-hesham** [handsontable/handsontable#5076]
### I want to get the original row

getData() returns an array of arrays and getSourceData() returns an array of original objects, when I click a cell a can use the getDataAtRow(row) to get the array of the current row, however I need the the matched original object .. how can I achieve this ?

**Comment by AMBudnik** [comment]
Hi @betslayer-hesham 

Does this example http://jsfiddle.net/handsoncode/r7roepu3/ meet the requirements?

**Comment by AMBudnik** [comment]
I believe that it does as we do not get any new comments so I'm closing the topic.
