### ISSUE TITLE
How to display xml file in Handsontable?

### ISSUE THREAD

**Issue by jay1yun** [handsontable/handsontable#5077]
### Description
I am absolutely new for Handsontable, and I would like to get some helps from existing users.

I have a xml data file that I want to display it on Handsongrid. After display it, I want to add a sort of OnSelect event to make next action.  

Where can I see an example for that? Can any one help? Thanks!!

**Comment by AMBudnik** [comment]
Hi @jay1yun 

Handsontable accepts only [JSON as an external format of data](https://docs.handsontable.com/pro/2.0.0/tutorial-load-and-save.html). You would need to convert it.

The select action can be done by a[ `afterSelecionEnd`  hook.](https://docs.handsontable.com/pro/2.0.0/Hooks.html#event:afterSelectionEnd) Let me know if you'd need more help with that one.
