### ISSUE TITLE
How to implement "Search and replace" logic in Handsontable as we do in excel?

### ISSUE THREAD

**Issue by vroon-s** [handsontable/handsontable#5079]
As we can find the specific text and replace with another one in Excel. How to implement the same in HandsonTable? Any help or existing code would helpful.

**Comment by AMBudnik** [comment]
Hi @vroon-s 

Cool idea! I would definitely ask the `getDataAtCell` and after I get coordinates of the cells that contain the exact phrase then call `setDataAtCell `for the same coordinates with the phrase no 2 (replacer).
