### ISSUE TITLE
I do not want the input file to clear

### ISSUE THREAD

**Issue by usernamehogehoge** [handsontable/handsontable#5080]
### Description

When I input a character to 1A after selecting 1B file, the value of file button 1B is reset

### Steps to reproduce

1.[1B] select file
2.[1A] enter character
3.[1B] clear file value

### Demo

http://jsfiddle.net/hU6Kz/5692/
<img border="0" src="https://i.imgur.com/LSj0LDX.gif">

### Your environment
* Handsontable version:2.0.0
* Browser Name and version: chrome 66.0.3359.139
* Operating System: mac 10.13.4

**Comment by AMBudnik** [comment]
Hi @usernamehogehoge The file name is rendered but not saved. Each time you change content for a cell (cell `A1` in this case) you call a renderer again and the values are refreshed. You would need to save the file name (`setDataAtCell` method) after user drops the file on the cell ([`afterOnCellMouseOut`](https://docs.handsontable.com/pro/2.0.0/Hooks.html#event:afterOnCellMouseOut))

**Comment by usernamehogehoge** [comment]
i want to get $_FILES by PHP

**Comment by AMBudnik** [comment]
Hi @usernamehogehoge 
what do you mean by writing `I'd like to set the file in input file.`?The edit mode of a cell?

**Comment by usernamehogehoge** [comment]
http://jsfiddle.net/hU6Kz/5705/
I would like to set the file before afterOnCellMouseOut.

**Comment by AMBudnik** [comment]
Thank you for sharing the code. To make it work you'd need to create a custom editor. Your file is not saved so each time someone edits another cell the renderer that is called erases the file.
