### ISSUE TITLE
 Migrate to the latest version of the Numbro library

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5081]
### Description

I've been just reported with an issue related to language use.

>  For now, if we're importing and using Handsantable as CommonJS module, importing of the file with languages inside the Numbro doesn't work correctly. More details were described in the current issue - https://github.com/BenjaminVanRyseghem/numbro/issues/304 

### Your environment
* Handsontable version: 2.0.0
* Browser Name and version: Chrome 65
* Operating System: Windows 10

Inform Gr#14287

**Comment by swrobel** [comment]
Release notes say "Hopefully, numbro 2.0.0 is 99% backward compatible with the previous version (1.11.1)."

**Comment by AMBudnik** [comment]
Hi @swrobel 
can you please check if everything works fine in your project?
