### ISSUE TITLE
[1.16.0+] disableVisualSelection doesn't work via cells method

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5082]
### Description

Since v `1.16.0` we are not able to set `disableVisualSelection `via cell properties.
It works for the whole instance > http://jsfiddle.net/xb6bemq6/

### Steps to reproduce

1. Go to http://jsfiddle.net/aa93rdrx/ (`1.16.0`)
2. Select any cell in column `B`

**Result**: Cell is selected
**Expected**: Cell should be selected.

### `setCellMeta` demo
1. Go to broken `1.16.0` demo > http://jsfiddle.net/zqr2gbws/
2. Select cell `0,0`

**Result**: Cell is selected
**Expected**: Cell should be selected like here http://jsfiddle.net/f2pxrdw4/ working `1.15.1.`;

### Your environment
* Handsontable version: 1.16.0+
[Last working `1.15.1`](http://jsfiddle.net/8qaLuzrj/)
* Browser Name and version: Chrome 65
* Operating System: Windows 10

Inform GR#14337

**Comment by bigsweater** [comment]
It seems as though `disableVisualSelection` works *only* on the whole table -- it doesn't work at all for columns, either.

Here's the commit that introduced the bug, according to `git bisect`:

592eae36ad331b2861f63db7ce91f074360fc96b

Related issues: #4708 

And a diff between the last good commit and first bad commit:

https://github.com/handsontable/handsontable/compare/505846fc23...592eae36ad331b2861f63db7ce91f074360fc96b

**Comment by AMBudnik** [comment]
Thank you for doing the investigation @bigsweater

**Comment by supra28** [comment]
@AMBudnik Any ETA on this?

**Comment by AMBudnik** [comment]
The Roadmap for Q4/2019 is already full and we do not know (yet) what are plans for 2020, but `regression` type of bugs are usually those which has to be fixed first. Please stay tuned.

**Comment by AMBudnik** [comment]
Works the same using v 8.0.0-beta 1 
Demo https://codesandbox.io/s/misty-dawn-ooh7t

**Comment by wszymanski** [comment]
Since `1.16.0` there is also problem with option `disableVisualSelection` when it is set globally (for the whole table). It's also regression.

Before


https://user-images.githubusercontent.com/141330/105062090-80e60400-5a7a-11eb-8041-792c0415ca60.mp4

After


https://user-images.githubusercontent.com/141330/105062100-84798b00-5a7a-11eb-95c8-16b1fe8b0e95.mp4

**Comment by aninde** [comment]
This bug has been fixed and on v8.3.2.
Thankfully to the hard work of @wszymanski, we improved the operation of this functionality.

`disableVisualSelection` works at any level of the cascade settings, ie for the entire table, for specific cells in each [columns](https://handsontable.com/docs/8.3.1/Options.html#columns) or specific [cells](https://handsontable.com/docs/8.3.1/Options.html#cells).

In this context, each cell has an association with their coordinates: `x` row and `y` columns, which may have `X` and `Y` headers.
As part of the cells option, we set a cell with the `x` and `y` coordinates whether it should highlight the header `X` and `Y`.

[disableVisualSelection](https://handsontable.com/docs/8.3.1/Options.html#disableVisualSelection) can be:
- assigned only the selected cell headers (`header`)  example https://jsfiddle.net/35atjkzx/
<img width="130" alt="Screenshot 2021-03-10 at 15 24 05" src="https://user-images.githubusercontent.com/30186818/110643741-b4105e00-81b4-11eb-9a23-edbcca1bdb6c.png">

- assigned to selected cell border (`current`) example https://jsfiddle.net/jqxonc3b/ 
<img width="178" alt="Screenshot 2021-03-10 at 15 25 05" src="https://user-images.githubusercontent.com/30186818/110643909-dbffc180-81b4-11eb-94e8-e725352f6dbc.png">

- assigned to selected area (`area`) example https://jsfiddle.net/g9r1t82y/1/ 
<img width="171" alt="Screenshot 2021-03-10 at 15 25 14" src="https://user-images.githubusercontent.com/30186818/110644401-56304600-81b5-11eb-8a95-2d6df3694bb6.png">


- assigned to all the above-mentioned options with `disableVisualSelection: true` Grey cell C1 example https://jsfiddle.net/nt47c3jw/ 
<img width="329" alt="Screenshot 2021-03-10 at 15 25 25" src="https://user-images.githubusercontent.com/30186818/110643935-e15d0c00-81b4-11eb-910d-d7a494594427.png">

**Comment by AMBudnik** [comment]
Thank you for solving this case. We can close the issue as solved for v8.3.2 of Handsontable.

@bigsweater @supra28 if you'd be still experiencing this issue after updating to v8.3.2 please let me know.
