### ISSUE TITLE
I want set a new background color to new row when after Create Row

### ISSUE THREAD

**Issue by yangxiaojun1** [handsontable/handsontable#5083]
### Description
I set a new row background color but not effective,If you could reply me soon,I would be appreciated.

### Demo
   afterCreateRow:function(index, amount,source) {
	   var ele = this;
	   var colunms = hot.getSettings().columns;
	      for (var j = 0; j < colunms.length; j++) {
	    	     $(ele.getCell(index,j)).css('background', 'blue');
	      }
  }

**Comment by tomasdivito** [comment]
@AMBudnik Sorry for getting into this issue but how would I do it after loading data to the table? I want to do it to every row.

I tried using a renderer when the data changes but didn't painted all the rows but only the first visible part of the table.

**Comment by AMBudnik** [comment]
Hi @tomasdivito 

what is an exact scenario? The loading of data our on any particular situation (button) or you need it after the table initializes? Here we track an option of adding new rows via context menu, in your case it would need to cover/paint new rows of data that are added?

**Comment by tomasdivito** [comment]
Hey @AMBudnik 

Sorry I thought I already answered this the other day, came to check if I got a response to that and reailze that I didn't answered (?)

Anyway the thing is like this, I need that when the table is initialized and loaded with the initial data by calling `loadData` with the data that I receive to draw all the rows based on one of the values of a property of the objects that form the array of objects that are my data.

I tried something like adding a renderer when I configure the table in the `cell` option to check if the cell is the one that has the value I'm looking, compare it and add the class to the row but that only worked for coloring (and not perfectly) the rows that were on sight. Not the other not even when scrolling. :/ And I found the api to not be as flexible with rows but more with cells.

**Comment by AMBudnik** [comment]
Hi @tomasdivito 

can you share me a demo with the code mentioned here ?

> I tried something like adding a renderer when I configure the table in the cell option to check if the cell is the one that has the value

**Comment by AMBudnik** [comment]
Hi @tomasdivito 

are you still working on this piece of code?

**Comment by AMBudnik** [comment]
I believe that we can close the issue as there is no reply from the author
