### ISSUE TITLE
when  some row has mergeCell include formula.  the formula can not be used.

### ISSUE THREAD

**Issue by Maru-z** [handsontable/handsontable#5088]
### Description

when  some row has mergeCell include formula.  the formula can not be used.
### Steps to reproduce

1. use plugins   mergecells on rows where formula  in  this row
2. use plugins formulas:true
3.  formula cell  can not be used  . only #Value ,        1.17version  is no problem

### Demo

 you can  show  or  hide  mergecells  to see  problems
https://jsfiddle.net/Marus/dw7Lg5y6/15/

### Your environment
* Handsontable version:1.8.3
* Browser Name and version:Chrome 66
* Operating System:windows 10

**Comment by AMBudnik** [comment]
Hi @Maru-z 

`=ROUND(D4-D5-D6-D7-D8-D9-D10+D11+D12,2)`

doesn't seem to be a correct `ROUND` formula syntax
docs: https://support.office.com/en-us/article/round-function-c018c5d8-40fb-4053-90b1-b3e7f61a213c

Here https://jsfiddle.net/reth8pog/ is a simplier case that works

**Comment by Maru-z** [comment]
Hi, @AMBudnik 
 i already  update formula  to  simple '.  but   formula  not show in cell.
 you can  hide mergeCells. you can see  formula  in  current cell.   if  show mergeCells.  formula  only show once  on init.
https://jsfiddle.net/Marus/reth8pog/1/

**Comment by AMBudnik** [comment]
I am sorry but I do not understand the bug.

We have only 2 formulas in your data set

![image](https://user-images.githubusercontent.com/10757813/39863349-ad380f90-5446-11e8-98f1-3c28ea70e03f.png)

Cell `D8` takes a value of `D4` and `D10` takes a value of `D9` and they all show the same value, which is `0` and this is correct.

I do not understand the content of the table - please tell me it it is important for this use case.

**Comment by AMBudnik** [comment]
Hi @Maru-z do I miss anything here or this is no longer an issue?

**Comment by AMBudnik** [comment]
I believe that we can close this issue as there's no more comments

**Comment by night2575058497** [comment]
I also have this situation, how to solve it?

**Comment by cheery550** [comment]
@AMBudnik 
Maybe there is an bug in mergeCells.js.

```
this.hot.runHooks('beforeMergeCells', cellRange, auto);
      rangeEach(0, mergeParent.rowspan - 1, function (i) {
        rangeEach(0, mergeParent.colspan - 1, function (j) {
          var clearedValue = null;

          if (!clearedData[i]) {
            clearedData[i] = [];
          }

          if (i === 0 && j === 0) {
            clearedValue = _this4.hot.getDataAtCell(mergeParent.row, mergeParent.col);
          } else {
            _this4.hot.setCellMeta(mergeParent.row + i, mergeParent.col + j, 'hidden', true);
          }

          clearedData[i][j] = clearedValue;
        });
      });
      this.hot.setCellMeta(mergeParent.row, mergeParent.col, 'spanned', true);
      var mergedCellAdded = this.mergedCellsCollection.add(mergeParent);

      if (mergedCellAdded) {
        if (preventPopulation) {
          populationInfo = [mergeParent.row, mergeParent.col, clearedData];
        } else {
          this.hot.populateFromArray(mergeParent.row, mergeParent.col, clearedData, void 0, void 0, this.pluginName);
        }

        this.hot.runHooks('afterMergeCells', cellRange, mergeParent, auto);
```
if mergeCells contains an formula(for example, the formula is "=C1+A1" and whose parsed value is 100), 
“getDataAtCell”  will get the value of the formula, not the formula itself. so if we have an formula in mergeCells, the formula will be lost.

Duo to the GWF, sorry for not providing sample code in "jsfiddle.net".

Thanks!

**Comment by AMBudnik** [comment]
Thank you for doing the investigation @cheery550 but we need to have an example where this does not work as apparently it works for some cases.
