### ISSUE TITLE
Issue with fixedColumnsLeft and merged cells

### ISSUE THREAD

**Issue by Raphael007123** [handsontable/handsontable#5089]
### Description
I have used the fixedLeftColumn feature in my Handsontable. And then I merged all cells in a row and pasted an HTML form inside that cell. then we can see the form gets splited. And cannot type in the form input fields.

### Steps to reproduce

(im doing as same as in the description)
1.click on any 1st cell of a row
2.click on the edit button ( creating a new row and merged the cell )
3. result: the form seems splited

### Demo
http://plnkr.co/edit/wFyBiwxRN9En0VdgHeMj?p=preview

### Your environment
* Handsontable version: 0.12.0
* Browser Name and version: chrome ,66
* Operating System: win 7

**Comment by AMBudnik** [comment]
We have 2 issues here.

1. `A1` is too narrow

![image](https://user-images.githubusercontent.com/10757813/39856365-e9d0d0b6-542f-11e8-9531-5f4dbb3fd4a6.png)

The brown area should cover the blue one to be the same in width as the green area.

2. Rows are misaligned

![image](https://user-images.githubusercontent.com/10757813/39856408-1d397552-5430-11e8-822b-e9e0ff0ad668.png)

Issu no 2 can be fixed by adding `autoRowSize: true` to settings, and then we have

![image](https://user-images.githubusercontent.com/10757813/39856507-8666a446-5430-11e8-9cb4-f9eeae641085.png)

**Comment by AMBudnik** [comment]
Hi @Raphael007123 

It looks like the issue can be wrapper related or any additional settings cause this issue.

I have created a simple vanilla example here http://jsfiddle.net/a2gpu0at/ and it does not cause the same issue.

![gif](https://user-images.githubusercontent.com/10757813/39910681-a0ada930-54f8-11e8-9335-626c972cf56e.gif)

Can you help me with this one? You can try to comment some settings and check if that changes anything.

**Comment by Raphael007123** [comment]
Hi @AMBudnik 

It's because of the issue with fixedLeftColumn and mergeCells in the table settings. if I don't merge the cells the issue will get fixed.

You can see, if you merge the row cells in http://jsfiddle.net/a2gpu0at/ the issue will reproduce.

But I cannot remove that setting, it's our requirement. Any possibilities for removing fixedLeftColumn for the newly created row ??

**Comment by AMBudnik** [comment]
I'm trying in different ways to get this working but did not find any workaround yet.

**Comment by Raphael007123** [comment]
Hi, 

Any updates on this @AMBudnik

**Comment by AMBudnik** [comment]
Without merging the rows it could be possible but as soon as I merge the rows it gets messy. [There are a lot of issues related to merging](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Plugin%3A+merge+cells%22+label%3A%22Type%3A+Bug%22). I believe that one of them is blocking us here.

**Comment by Raphael007123** [comment]
Thank for the update @AMBudnik :)

**Comment by wow-222** [comment]
Has this problem been fixed?

**Comment by AMBudnik** [comment]
Hey @wow-222 

The issue hasn't been fixed yet. It is reported here https://github.com/handsontable/handsontable/issues/4670
