### ISSUE TITLE
Type definition renderer

### ISSUE THREAD

**Issue by oleksandr-dakal** [handsontable/handsontable#5091]
### Description
Type definition not correct for interface Handsontable.renderer.Base. cellProperties defined as GridSettings that is not correct and break typing when try to use renderer from cellProperties.

Your environment
Handsontable version: 2.0.0
Browser Name and version: Chrome 65.0.3325.181
Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you @oleksandr-dakal 

we'll check that

**Comment by aaronbeall** [comment]
@oleksandr-dakal What exactly is wrong about the type definition?

**Comment by AMBudnik** [comment]
Hey @oleksandr-dakal 

We've updated the Handsontable to v `7.0.0` were we've added all the changed proposed by Aaron https://github.com/handsontable/handsontable/pull/5767
