### ISSUE TITLE
Move jQuery wrapper to its own repository

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#5096]
### Description
All our wrappers are organized as a separate packages and published to NPM. jQuery is the only one that is hidden somewhere in our main code base. To keep everything neatly organized we should extract jQuery wrapper too. New repo `jquery-handsontable` and NPM package just like any other wrapper `@handsontable/jquery`. It's going to have its own section in documentation too.

It's there, but we will make it super easy to find and use just like any other of our wrappers.

- [ ] Move code to `jquery-handsontable`
- [ ] Add documentation section for jQuery
- [ ] Add jQuery logo to supported frameworks

**Comment by AMBudnik** [comment]
I am closing this proposition of a change as we are not currently working on the piece of code that it relates to.
Once we open an issue we check all pinned issues and pull requests even if they are closed so please keep track of updates to this issue. All additional comments are also highly appreciated.
