### ISSUE TITLE
How to validate dropdown on change in Handsontable?

### ISSUE THREAD

**Issue by VijeshVenugopal** [handsontable/handsontable#5098]
### Description
Hi,
I would like to know about how to validate a dropdown after a value has been changed. I went through the handsontable docs and found out that calling afterValidate method will validate the cell. I applied the same and set a style using setCellMeta. But the change is not reflecting after render the handsontable. Could you please provide an assistance regarding this issue?

**Comment by AMBudnik** [comment]
Hi @VijeshVenugopal 

`afterValidate` is a hook that runs after a validation process. And to trigger a validation you call a core method called [`validateCells()`](https://docs.handsontable.com/pro/3.0.0/Core.html#validateCells).

If that won't help please share a demo with the example.
