### ISSUE TITLE
Can't copy an once merged area 

### ISSUE THREAD

**Issue by manglobe** [handsontable/handsontable#5101]
Hi! I'm back~ with an other problem. :(
step:
1. Merge an area 'A'.
2. Unmerge the area  'A'.
3. Write  some  value into the area 'A'.
4. Copy 'A' to other area.
5. Only the first value was paste, and the selection range was also wrong.

I checked several hooks. And I see at `beforeCopy`, this problem has happend.
Should I do something at `beforeUnmergeCells` ?
http://jsfiddle.net/ywxacqLp/

![2018-05-17_16-08-44](https://user-images.githubusercontent.com/19583202/40164670-c73922ac-59ec-11e8-99c6-5ec3ec1ac4aa.gif)

**Comment by AMBudnik** [comment]
Thank you for sharing the issue.
I've replicated it. It looks like it doesn't seem to work in `3.0.0` nor any of the older versions.

> Should I do something at beforeUnmergeCells ?

It should work without any additional settings. It's a bug.

**Comment by manglobe** [comment]
@AMBudnik I resolved this problem. But I changed the sourse code.
![_15272395658763](https://user-images.githubusercontent.com/19583202/40536517-0430a254-603f-11e8-95e4-3af52a020410.png)

Maybe you can find a better way to resolve , if you publish the new version and resolve this problem ,
please give me a reply , thanks.  :)

**Comment by AMBudnik** [comment]
Thanks for sharing @manglobe 
I'm adding the *improvement suggestion* label as a tip for the devs.
I will let you know as soon as it gets fixed :)

**Comment by AMBudnik** [comment]
Hey @manglobe 

we've just released v 7.1.0 where we've fixed the issue. Please let me know if it works for you as well.
