### ISSUE TITLE
Resize editor bug while changing datasource

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#5103]
### Description

The editor doesn't resize when datasource was changed. This only happens when an editor is open.

### Steps to reproduce

1. Open editor of the A1 cell;
2. After 3 seconds the `setTimeout` function change the data source and re-render the table;
3. As a result, you'll see not resized editor.

### Demo

https://jsfiddle.net/8ffpsqt6/21/

![kapture 2018-05-17 at 11 10 51](https://user-images.githubusercontent.com/571316/40168150-0a9dfc0e-59c3-11e8-8d0e-be76aefd9575.gif)

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Also replicable in 7.4.2 https://jsfiddle.net/AMBudnik/b9jz7peg/

**Comment by swistach** [comment]
Since v8 there is `setSourceDataAtCell` method to manipulate data in that way: https://jsfiddle.net/Lkbo3n0p/
and the new version seems to work as expected.
