### ISSUE TITLE
[2.0.0+] Open editor overlaps elements in clone top element

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#5105]
### Description
In #4787 we changed `z-index` of cloned areas and `inputHolder`. Unfortunately, now open editor overlaps fixed areas.
![issue-scroll-editor](https://user-images.githubusercontent.com/11849621/40176540-029a052a-59dc-11e8-92da-a39f23a3c9bf.gif)

### Steps to reproduce
1. Go to demo
2. Open A4
3. Scroll down a table

### Demo
http://jsfiddle.net/5jcxstcy/

### Your environment
* Handsontable version: 2.0.0+

**Comment by AMBudnik** [comment]
@swistach 

Please check it also for bottom fixed rows

![bug](https://user-images.githubusercontent.com/10757813/44461948-2cbd6800-a613-11e8-93fc-62725cfb3ba5.gif)

**Comment by AMBudnik** [comment]
and the `rowHeaders` 

demo https://jsfiddle.net/handsoncode/Lpz2n7cm/ (`v 6.0.1`)

![gif](https://user-images.githubusercontent.com/10757813/46394831-9dfc3a80-c6ea-11e8-9ab3-82b77912ecdd.gif)

**Comment by pnowak** [comment]
Closed https://github.com/handsontable/handsontable/pull/6269
