### ISSUE TITLE
Unable to click next column while editing autocomplete cell

### ISSUE THREAD

**Issue by ElGrimbo** [handsontable/handsontable#5107]
### Description
When editing an autocomplete cell I click the leftmost portion of the next cell, expecting it to deselect what I'm currently editing and select the one I've clicked. But nothing happens. However if I click anywhere in the right-hand portion of the cell it works as expected.

It looks like the .handsontableInputHolder div which wraps the dropdown element is getting in the way.

![image](https://user-images.githubusercontent.com/10922976/40311761-aa7d1000-5d08-11e8-9b59-1ecec6113928.png)

### Steps to reproduce

1. Set up a table with two columns, the left one should be of type autocomplete
2. Start editing in the autocomplete cell to bring up the suggestions div
3. Click somewhere in the next cell, close to the left border

### Demo
https://jsfiddle.net/grimbot/dc29dyok/1/

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version:  Chrome 66.0.3359.139 (Official Build) (64-bit)
* Operating System: Windows 7 Pro 64-bit

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @ElGrimbo 

I believe that this is the same issue that our programmer spotted some time ago and reported at https://github.com/handsontable/handsontable/issues/3758
