### ISSUE TITLE
Moving columns with `hiddenColumns` and `persistenState` turned on erases columns values.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5108]
### Description

Moving columns with `hiddenColumns` and `persistenState` turned on erases columns values.

### Steps to reproduce

1. Move column `K` to the position of column `F`.

**Result**:
Two empty columns `G` and `J`.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/10757813/40347275-f9775f0c-5d9f-11e8-9ea3-03529348e919.gif)

### Demo
http://jsfiddle.net/Lq2r9cem/1/

### Your environment
* Handsontable version: `3.0.0`
* Browser Name and version: Chrome 66
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
Not related to `persistentState`. We've got a simpler example here: #5598

Duplicate of #5598

**Comment by AMBudnik** [comment]
Referenced issue solved in v 8.0.0
