### ISSUE TITLE
Custom Attributes support for a row

### ISSUE THREAD

**Issue by mashit** [handsontable/handsontable#511]
How can i apply some custom attributes to handontable rows?

Lets say i want some of TRs to have a attribute `data-dd-id=X`.
Currently I am using handsontable version 0.8.3. And i am passing data as an array of key value pairs.

Data looks like - 

`{"id":86,"name":"Mashit","_tr_attr1":"value1"}`

And if i could tell handsontable that keys starting with _tr_ are meant to be row attributes and not data.

**Comment by GuptaDi** [comment]
Hello, but without creating a column, cant we just add an attribute to a newly about to be created row?

**Comment by AMBudnik** [comment]
Hi @GuptaDi 
Can you share more details about your request?
We will be adding a similar feature via `rows` settings https://github.com/handsontable/handsontable/issues/4055
