### ISSUE TITLE
Uncaught TypeError while selecting the cell (allowInvalid: false)

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#5119]
### Description

The Handsontable throws an exception when while opened editor another cell is selected. This occurs when the table has defined async validators and the `allowInvalid` is set to `false`.

### Steps to reproduce

1. Open the demo and open an editor for B2 cell (double click);
2. Scroll to B20 and select the cell (single click);
3. In result, the `TypeError` is thrown.

### Demo

https://jsfiddle.net/8ffpsqt6/22/

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Works the same in v `5.0.1`.

If we [add `renderAllRows`](https://jsfiddle.net/vhnuyc08/) and keep all the elements in rendered when clicked on `B20` we are moved to `B2`.

**Comment by wojciechczerniak** [comment]
Just for reference possible duplicates: #5258 #5128
