### ISSUE TITLE
Append Filter Multiple Time

### ISSUE THREAD

**Issue by sudhanshu1607** [handsontable/handsontable#5122]
HandsonTable filter append again and again after new data added in table

### Steps to reproduce

1. i have get data using jquery Ajax and bind it using Handsontable 
2.now i have created custome paging as per y requirement and get anther data using jquery ajax and load in same handsontable with same settings
3.at second time load data filter issue occured

 var hotElement = document.querySelector('#hot'), hot;
        //var hotElementContainer = hotElement.parentNode;
        var hotSettings = {
            data: null,
            columns: [
                { data: 'myNumber', type: 'text' },
            ],
            rowHeaders: true,
            autoWrapRow: true,
            colHeaders: [
                'myNumber'
            ],
            filters: true,
            dropdownMenu: true,
            columnSorting: true,
        };
        hot = new Handsontable(hotElement, hotSettings);

### Your environment
* Handsontable version: 1.11.0
* Browser Name and version: : firefox  v60
* Operating System:windows

![handsontableissue](https://user-images.githubusercontent.com/9925745/40574979-1e2be2f2-60fa-11e8-9027-a0e375257c6a.PNG)

**Comment by AMBudnik** [comment]
Hi @sudhanshu1607 
could you send a demo? With this settings, I cannot replicate the issue.

**Comment by sudhanshu1607** [comment]
Issue has been resolved

**Comment by abhinavsarja** [comment]
@sudhanshu1607 @AMBudnik 
  Can you help me know how this issue was resolved. 
I have the same issue each time a handsontable is re-rendered in my React application.
Filters grow beyond control. 

Unfortunately I cannot give a demo because it requires some reload to be triggered from other page

**Comment by AMBudnik** [comment]
Hey @sudhanshu1607 

I've never got a demo so haven't had a chance to replicate the issue.
If you can prepare one I can help.

**Comment by abhinavsarja** [comment]
This is my screenshot
![image](https://user-images.githubusercontent.com/14216994/50889378-c8b90600-1432-11e9-8a7f-547d96521ae5.png)

**Comment by abhinavsarja** [comment]
@AMBudnik  Issue is now resolved.

Reason for issue was to load the handsontable again during data refresh instead of just using hot.updateSettings. 
I did something like below and issue is resolved. 

this.hot.updateSettings({
         	        hiddenColumns: {
         	          columns: [7, 8],
         	        },
         	        data: data
                      })
         	 }

**Comment by AMBudnik** [comment]
Great to hear that, @abhinavsarja 
Thanks for the update
