### ISSUE TITLE
Only append part of data to table with virtual rendering mechanism

### ISSUE THREAD

**Issue by futianshu** [handsontable/handsontable#5123]
### Description
Hi, team:
I am testing .getSourceData().push() to append rows to a table. When refresh the page, 50 rows could be loaded to the table. And the button "Load" should append 50 more rows to the table. 

When the scrolbar is to the top, the append function works well (appending rows from 51 to 100).

But when the scrollbar is to the bottom, the append function could only append rows from 51 to 56 on render. I think something goes wrong on the virtual rendering mechanism of handsontable.

Would you help me, please?

### My Code
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>testHandsontable</title>
    <script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="js/handsontable.full.min.js"></script>
    <link rel="stylesheet" media="screen" href="css/handsontable.full.min.css">
</head>
<body>
    <button id="load">Load</button>
    <div id="example"></div>
</body>

<script type="application/javascript">
    var data1 = [];
    var data2 = [];

    var oneData = [];
    oneData.push('<a href="javascript:void(0)">1</a>');
    oneData.push('<a href="javascript:void(0)">2</a>');
    oneData.push('<a href="javascript:void(0)">3</a>');
    oneData.push('<a href="javascript:void(0)">4</a>');
    oneData.push('<a href="javascript:void(0)">5</a>');
    oneData.push('<a href="javascript:void(0)">6</a>');
    oneData.push('<a href="javascript:void(0)">7</a>');
    oneData.push('<a href="javascript:void(0)">8</a>');
    oneData.push('<a href="javascript:void(0)">9</a>');
    oneData.push('<a href="javascript:void(0)">10</a>');

    for (var i = 0; i < 50; i++) {
        data1.push(oneData);
        data2.push(oneData);
    }

    var container = document.getElementById('example');
    var hot = new Handsontable(container, {
        fillHandle: false,
        rowHeaders: true,
        colHeaders: ["c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10"],
        colWidths: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
        rowHeaderWidth: 100,
        data: data1,
        editor: false,
        renderer: "html",
        height: 500
    });

    $("#load").click(function(){
        for (var i = 0; i < data2.length; i ++) {
            hot.getSourceData().push(data2[i]);
        }
        hot.render();
    });
</script>
</html>
```
### My Environment
* Handsontable version: 3.0.0
* Browser Name and version: Chrome 64.0.3282.186 (64 bit)
* Operating System: Win7

**Comment by AMBudnik** [comment]
HI @futianshu 

I've tried your code on Win 10 / Chrome 66 and it seems to work fine

![gif](https://user-images.githubusercontent.com/10757813/40602996-e476c218-625a-11e8-9701-5ef13c466ca8.gif)

Can you update your browser and check if that still occur?

**Comment by futianshu** [comment]
Hi @AMBudnik 

Thank you for your comment.

I have just found that when my browser's zoom is 80%, my code works fine, but when 100% or other zoom, it makes mistake.

I have no idea why my code is related with browser's zoom.

Would you change your browser's zoom and try again, please?

**Comment by AMBudnik** [comment]
I think that this can be related to one of these issues https://github.com/handsontable/handsontable/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+zoom but what i new about this situation is the fact that it doesn't work well on 100%

**Comment by wojciechczerniak** [comment]
I wouldn't consider this as a bug. Modifing `sourceData` by reference will break Handsontable indexing and meta data. We can push new data with Handsontable API: 

v7.1.1 example: https://jsfiddle.net/setLd9v5/
v3.0.0 example: https://jsfiddle.net/q4r0gk9s/

Please double check and correct me if I'm wrong @AMBudnik @aninde

**Comment by AMBudnik** [comment]
I've tried 90%, 100%, and 125% and the behavior is correct.

If the issue is still replicate in your project after updating to `7.1.1.` please send me a demo where the issue can be replicable at support@handsontable.com

@aninde if you'd find a way to replicate the issue please reopen the topic and share the details
