### ISSUE TITLE
Cannot read property 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#5126]
### Description

The Handsontable throws an error when the table is initialized with an empty array or the whole data was removed leaving the corner overlay. In this case when the user clicks that corner and tries to texting something the `Uncaught TypeError: Cannot read property 'removeEventListener' of undefined` error is thrown.

### Steps to reproduce

1. Click the top-left corner overlay;
2. Press <kbd>a</kbd>;
3. In result the error occurs.

### Demo

https://jsfiddle.net/8ffpsqt6/24/

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
Error is still replicable in `7.1.1` v. 

**Demo**
https://jsfiddle.net/aninde/b2n0gvyo/

**Comment by aninde** [comment]
This issue will be fixed in `7.1.2` v. 
An error in console is no longer replicable in the console after above reproduction. 

**Demo**
`7.1.2` v.  https://jsfiddle.net/aninde/wvrfpb8s/
