### ISSUE TITLE
how to render all columns

### ISSUE THREAD

**Issue by byte9527** [handsontable/handsontable#5132]
### Description
when these columns are too many, handsontable  just render  these columns of visible, but i want to render all columns.

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 0.33
* Browser Name and version:
* Operating System: windows

**Comment by AMBudnik** [comment]
Hi @byte9527 

You can use offset settings to take control over the amount of rendered rows and columns
https://docs.handsontable.com/pro/3.0.0/Options.html#viewportColumnRenderingOffset
https://docs.handsontable.com/pro/3.0.0/Options.html#viewportRowRenderingOffset
