### ISSUE TITLE
[1.16.0+] We cannot add a new row in the nestedRows 

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5133]
### Description

We cannot add a new row in the `nestedRows `

### Steps to reproduce

1. Click anywhere in the table with <kbd>RMB</kbd> to use *Insert row above*

Result: The row is not added and we get a console error.
`Uncaught TypeError: Cannot read property 'row' of undefined`

### Demo

http://jsfiddle.net/handsoncode/3aekftny/

### Your environment
* Handsontable version: `1.16.0+`
* Browser Name and version: Chrome 66
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
The following issue has been already discussed here https://github.com/handsontable/handsontable/issues/5133

**Comment by AMBudnik** [comment]
Fixed with https://github.com/handsontable/handsontable/issues/6324

**Comment by pnowak** [comment]
If I try `Insert row above` or `below` on the first nested children I get the same error as it was before - `Uncaught TypeError: Cannot read property 'row' of undefined`. 

Here is a demo - https://jsfiddle.net/9g1ohn35/
Click on the second row in the table with RMB to use `Insert row above`.

Could you check this @AMBudnik?

**Comment by AMBudnik** [comment]
I agree @pnowak 
However, the bug related to the 2nd row (first child) has been reported separately here https://github.com/handsontable/handsontable/issues/7137
Issue no 5133 related to the general use of the `Insert row above` on a nested data, and 7137 relates to particular elements of the dataset that do not respond to this method.

**Comment by AMBudnik** [comment]
Issue solved in v8.0.0

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
