### ISSUE TITLE
Create multiple cells under one header

### ISSUE THREAD

**Issue by TomashVlad** [handsontable/handsontable#5137]
### Description

I want to create 2 or more cells to be under one header

U can see in link below:

https://ibb.co/jn4WoJ

So far, i managed to implement data and it looks like this, but I can't split cell under one header to have each one data:

https://ibb.co/jCcnvy

And in my angular 4 ts file in looks like this:

https://ibb.co/h2B5Xd

Is there any way to create 2 or more cells under one header and how can i do that because, i couldn't find it in documentation. Thanks to all

### Your environment
* Handsontable version: 
* Browser Name and version: Chrome 67.0.3396.62
* Operating System: Win10

**Comment by AMBudnik** [comment]
Hi @TomashVlad 

If I understand the `nestedHeaders` is the feature that will fit here perfectly. Here's a demo http://jsfiddle.net/handsoncode/xt152sb0/
Let me know if that's it or I've missed anything.
