### ISSUE TITLE
How to mearge 2 data value

### ISSUE THREAD

**Issue by sudhanshu1607** [handsontable/handsontable#5140]
### Description
i want to show id with name .
how can i create this???
here i have explaned create 2 columns with saprate id and name ut i want oth in same column with any seprate like - or , or ()
currently it comes
id     name
1      myName

but i want

id
1-myName

 hotElement = document.querySelector('#hot'), hot;
//var hotElementContainer = hotElement.parentNode;
var hotSettings = {
data: null,
columns: [
{ data: 'id' ,'Name'},
],
rowHeaders: true,
autoWrapRow: true,
colHeaders: [
'id','Name'
],
filters: true,
dropdownMenu: true,
columnSorting: true,
};
hot = new Handsontable(hotElement, hotSettings);

Your environment
Handsontable version: 1.11.0
Browser Name and version: : firefox v60
Operating System:windows

**Comment by AMBudnik** [comment]
Hi @sudhanshu1607 

`columns` allows you to load data only from one source. However, you can create a custom renderer to concat those two fields into one and pass it as a `innerHTML` for the cell.
