### ISSUE TITLE
A json pair with a key name with and underscore won't populate the data

### ISSUE THREAD

**Issue by dschueler** [handsontable/handsontable#5141]
### Description
if I have a key/value pair of say "start_date":"2018-12-04" then the data won't populate into the table...no apparent error in console..it just disappears.
This data is coming from an object...

If I change the key to startdate  then it works. This causes me a problem since that key name is required in another plugin I am sharing the dataset with. I would love a quick fix for this.

**Comment by dschueler** [comment]
Anybody home?

**Comment by AMBudnik** [comment]
Hi @dschueler 

we had a national day off yesterday so sorry for the delay.

Can you share your settings? I've just tried the `key` here http://jsfiddle.net/handsoncode/rkq6fuxe/ and it seems to work fine.

**Comment by dschueler** [comment]
Alexa...so sorry, I didn't know you were on Holiday. Thanks for the fiddle. I went back through my code and I made a second copy of the data while the first was being created. This second copy was not connected/parsed by the DHTMLX Gantt library I am using on the same page. The columns displayed OK so it looks like DHTMLX Gantt is modifying that data...it may be a timing issue. Thanks!

**Comment by AMBudnik** [comment]
You're welcome @dschueler. I'm glad that you're one step forward with the implementation.
