### ISSUE TITLE
Editor Flying Above the Selected Cell when editing

### ISSUE THREAD

**Issue by nidhityagi46** [handsontable/handsontable#5142]
Issue seems to be associated with Scrolling. When I scroll down the grid and select a particular cell, click on it to edit, the editor seems to be placed much above the selected column 
![error](https://user-images.githubusercontent.com/26898947/40764084-29659f68-64c5-11e8-9d4d-1b3e90ea9b58.PNG)

### Steps to reproduce

1. Scroll down the grid
2. click on a cell to edit text
3. Editor misplaced much above the selected cell

### Demo
window.hot = new Handsontable(container, {
                data: data.d.results,
                minSpareRows: 1,
                rowHeaders: true,
                colHeaders: false,
                colHeaders: colHeaders,
                columnSorting: true,
                sortIndicator: true,
                contextMenu: true,
                columns: colSttings,
                manualColumnResize: true,
                manualRowResize: true,
                allowRemoveColumn: false,
		stretchH : 'all',

### Your environment
* Handsontable version: Version: 3.0.0
* Browser Name and version: IE 11 and Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hi @nidhityagi46 

thank you for sharing the example. 

I think that we already have this reported at https://github.com/handsontable/handsontable/issues/5105 (fixed area) and https://github.com/handsontable/handsontable/issues/4832 (going outside of the table).
