### ISSUE TITLE
HTML Rendering in Handsontable [ Open ]

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#5144]
can anyone suggest me a best way to render HTML in handsonTable, and in my usecase i need to bind Events to those HTML DOM. I tried these method with the help of afterRender call back [https://docs.handsontable.com/2.0.0/demo-custom-renderers.html](url) ,

is there any other method  available?? to solve this use case. 

>  Rendering HTML Elements with Event

**Comment by AMBudnik** [comment]
HI @Sundarcj 

I think that the easiest way is to define an `html` renderer and then just attach an HTML content to a cell. Here's an example with a button http://jsfiddle.net/handsoncode/bra4qfy7/

**Comment by Sundarcj** [comment]
Hi @AMBudnik  

   Thank you !!.
But my problem is clearly explained in your jsfiddle it self .[http://jsfiddle.net/gvjhncx7/1/](url)
what happen when i click the buttons which are not present while first time render. The Event is not binded to those DOM because they are virtual rendered rows. So, there is a solution which i tried lot of times that is do the even binding on each scroll. I need a better solution **other than after render even binding**!!!

Thank u advance

**Comment by AMBudnik** [comment]
I will check that and be back to you.

**Comment by Sundarcj** [comment]
any updates ??

**Comment by AMBudnik** [comment]
Hi @Sundarcj 

I've asked one of our developers for his tips. I should get any today.

**Comment by AMBudnik** [comment]
Hi again @Sundarcj 

what do you think about this code http://jsfiddle.net/3akf1b8e/
Does it meet your project requirements?

**Comment by Sundarcj** [comment]
@AMBudnik   Thanks again 
vl check and vl let u knw

**Comment by AMBudnik** [comment]
I believe that we can close the issue as there's no reply for 2 weeks. If you've any questions feel free to ask @Sundarcj
