### ISSUE TITLE
Row Header 

### ISSUE THREAD

**Issue by nidhityagi46** [handsontable/handsontable#5145]
### Description
The row header seems to be missing after a count of 29-30 rows. 

### Demo

![image](https://user-images.githubusercontent.com/26898947/40836872-0255633a-65b6-11e8-92ea-bbd7fcd5bda7.png)

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: IE 11 & Chome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Please fill the Description @nidhityagi46 
I do not know how to help you

**Comment by nidhityagi46** [comment]
Yes, I was just updating the same. Thank you for your assistance.

**Comment by AMBudnik** [comment]
Now the link is missing. Please add one.

Before that you can check if adding `renderAllRows: true` solves the issue.

**Comment by AMBudnik** [comment]
I believe that we can close the issue
