### ISSUE TITLE
The frozen column's cell are not align to others when I change the scrollbar styles.

### ISSUE THREAD

**Issue by CCCMeng** [handsontable/handsontable#5148]
### Description
The frozen column height is not align to others when I change the scrollbar styles.

### Steps to reproduce
1. scroll to the bottom

### Demo
http://jsfiddle.net/ezoyu8ue/3/

### Environment
* Handsontable version: v3.0.0
* Browser Name and version: Chrome
* Operating System: win 10

My English is bad please don't mind

**Comment by CCCMeng** [comment]
I found the problem

**Comment by ImagineZzf** [comment]
How to solve it?

**Comment by AMBudnik** [comment]
@ImagineZzf that particular example is related to the custom CSS settings. If you change `width: 6px;` for the `::-webkit-scrollbar` element to `width: 8px;` it looks well.
Updated demo http://jsfiddle.net/4zwj03c5/
