### ISSUE TITLE
My requirement is: render the requested data with each click(Not clicking handsontable). But when I clicked for the first time, the data could not be rendered.

### ISSUE THREAD

**Issue by mofengfs** [handsontable/handsontable#5149]
@wszymanski Hi, this is my demo
I think this is an initialization problem because I have already triggered the initialization of the table without clicking the button. I think this should have a solution.

### [stackblitz demo](https://stackblitz.com/edit/js-sa6uhd?ctl=1&embed=1&file=index.html&hideExplorer=1)
My code is as shown below

### 1. code ----------------------------------------------------------------------------------------------------
![qq 20180604144421](https://user-images.githubusercontent.com/16655229/40902249-fc3d9fce-6805-11e8-9310-01f53fa34a45.png)

### 2. default  --------------------------------------------------------------------------------------------------
![default](https://user-images.githubusercontent.com/16655229/40950615-1166648a-68a6-11e8-8c64-ab563f42847b.png)

### 3. First click  ------------------------------------------------------------------------------------------------
![1](https://user-images.githubusercontent.com/16655229/40950065-a08e4234-68a3-11e8-90a4-b85cc3649668.png)

### 4. Second click  --------------------------------------------------------------------------------------------
![4](https://user-images.githubusercontent.com/16655229/40950547-d4a907d2-68a5-11e8-8410-739f4b1b3cf7.png)

**Comment by AMBudnik** [comment]
If you want to do anything on a click on the table you can use the table container like here http://jsfiddle.net/handsoncode/da5r6b1p/
Let me know if I'm missing something.

**Comment by mofengfs** [comment]
@AMBudnik 
I think you misunderstood what I meant, I want to click elsewhere, and then present the data in the handsontable instead of clicking the handsontable.

**Comment by AMBudnik** [comment]
Oh I see.
Ok so the issue has to be with the container size. Try to add some fixed values for `height` and `width` via CSS and check if that will show columns on the first click. If that won't help you can also try to add a slight delay (~20ms)

**Comment by mofengfs** [comment]
hi , @AMBudnik 
I'm sorry, I tried both ways. The problem is the same as the original.

**Comment by AMBudnik** [comment]
Hm... in most of the cases it helped. It only doesn't work if you use Angular 1 and `cloak` or in some .NET implementations. As I believe you do not have any of those?

**Comment by mofengfs** [comment]
@AMBudnik 
I don't use any other frameworks or libraries. I just use handsontables.

**Comment by AMBudnik** [comment]
Maybe adding `hot.render()` after `30ms`?

**Comment by mofengfs** [comment]
@AMBudnik 
I have tried it, it's useless.

**Comment by AMBudnik** [comment]
Apparently, there's something I'm missing. I'll ask my colleague to check it out and I'll back with news.

**Comment by mofengfs** [comment]
@AMBudnik 
Thank you!

**Comment by AMBudnik** [comment]
Hi @mofengfs 
I just got a reply.

> You can change the ``beforeChangeRender`` with 
> 
> ```js
> columns: [
>       {data: 'afl'},
>       {data: 'duration'},
>       {data: 'gain'},
>       {data: 'muted'},
>       {data: 'name'},
>       {data: 'pan'},
>       {data: 'path'},
>       {data: 'pfl'},
>       {data: 'soloed'}
>     ],
> ```
> 
> Then, when you click for the first time the whole table loads. The problem lays in the asynchronous loading f data as the number of columns appears as `0`.

**Comment by mofengfs** [comment]
@AMBudnik 
This means adding columns at initialization is an option, but this experience is not very good. Still thanks for your reply.

**Comment by mofengfs** [comment]
@AMBudnik 
The problem has been solved, thank you!

**Comment by AMBudnik** [comment]
Did something change @mofengfs ?

**Comment by AMBudnik** [comment]
If you'd need any guidance please let me know
