### ISSUE TITLE
columnHeaderHeight option does not work when small value is given

### ISSUE THREAD

**Issue by ejubkadric94** [handsontable/handsontable#5154]
### Description
If columnHeaderHeight is set to value lower than 25, the height of column headers remain at 25 pixels.

Earlier I ran across this issue: https://github.com/handsontable/handsontable/issues/3837 and I had to use the provided workaround to solve the issue. And indeed, workaround removes the problem for rows, but the problem is still there for columns.

### Demo

http://jsfiddle.net/koxgbc2y/

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Ubuntu 17.10

**Comment by AMBudnik** [comment]
Hi @ejubkadric94 

Can you add more settings of yours? I believe that we would be able to create a CSS hack until it gets fixed but I would need to have an example with _mergeCells_ that is as similar as possible to your example.

**Comment by AMBudnik** [comment]
I believe that we can close the issue as there's no update for a long time
