### ISSUE TITLE
Column Drop Down Menu in Handson 2.0

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#5160]
hi,
  am currently moved to handson 2.0 ,currently am facing issues in Column dropdown [Its not shown in header ] .Is there any changes?? In dropdown construction for 2.0

**Comment by AMBudnik** [comment]
Hi @Sundarcj 

it looks like the PRO script did not load and you're on CE version.

**Comment by Sundarcj** [comment]
@AMBudnik 
No i have license. and it is pro version

**Comment by AMBudnik** [comment]
Can you check if the resources are correct? It that won't help please send me a demo at support@handsontable.com
