### ISSUE TITLE
[2.0.0+] Fixed bottom rows bug

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#5163]
### Description

Fixed bottom rows not working since 2.0.0. This is a regression.

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/2.0.0/demo-fixing-bottom.html;
2. Scroll horizontally;
3. In result, the fixed bottom rows are out of sync with the main table scroll.

### Demo

https://docs.handsontable.com/pro/2.0.0/demo-fixing-bottom.html

### Your environment
* Handsontable version: 2.0.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Wow! We need to fix this. It looks awful on Chrome/Win

![gif](https://user-images.githubusercontent.com/10757813/41148139-8c93d5fc-6b08-11e8-98da-52c69c8e742d.gif)
