### ISSUE TITLE
Context menu getting repeated for all row , using ver 3.0.0

### ISSUE THREAD

**Issue by primeO** [handsontable/handsontable#5168]
### Description
Working on handsontable ver3.0.0 context menu is getting repeated for all rows . 

<link rel="stylesheet" type="text/css"
				href="https://handsontable.com/static/css/main.css"></link>
<link type="text/css" rel="stylesheet"
				href="#{request.contextPath}/odassets/grid/handsontable.full.css"></link>
<script src="#{request.contextPath}/odassets/grid/handsontable.full.js"></script>

     var 
            table = document.getElementById('table1');
           
            var hot = new Handsontable(table, {
                data: data,
                columns: cols, 
                colHeaders: 
                [ 'XXXX' , 'XXXXX' , 'XXXXX' , 'XXXX'], 
                stretchH: 'all',
                width: 1400,
                autoWrapRow: true,
                height: 500,
                colWidths: 100,
                rowHeights: 25,
                filters: true,
                manualRowResize: true,
                manualColumnResize: true,
                contextMenu: true
            });
          

### Your environment
* Handsontable version: 3.0.0 
* Browser Name and version: chrome , morzilla
* Operating System:windows

**Comment by AMBudnik** [comment]
@primeO 

Can you record it, please? I have used fake `data` and commented out `column` as they are not defined in the example and the context menu works fine for me.

I'm testing it on Chrome 67, Windows 10.

**Comment by primeO** [comment]
thanks @AMBudnik , Issue has been resolved . problem with dynamic tabs .

**Comment by AMBudnik** [comment]
Thank you for confirmation.

I'm closing the issue
