### ISSUE TITLE
Long-touch doesn't trigger Context-Menu

### ISSUE THREAD

**Issue by PiotrKupniewski** [handsontable/handsontable#5171]
Hi everyone, 
I have a problem like in topic. When i touch long the screen on iPad ( iOS 11.4, generation 5) there is do nothing. On the other hand when i do it the same on phone with Android, there open the context-menu window.

Maybe you have save solutions for this issue?  

Open in mobile safari : 
http://jsfiddle.net/api/post/library/pure/

and try to open with a long touch

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: Safari newest, updated with  #iOS
* Operating System: iOS 11.4

**Comment by AMBudnik** [comment]
Hi @PiotrKupniewski 

please track changes to the following issue https://github.com/handsontable/handsontable/issues/4833 It has been made for `Android 7.0.0; SM-G955F` but if you could add the information about your testing environment that will help us to do the tests

**Comment by PiotrKupniewski** [comment]
@AMBudnik,

Thanks for your response.
As i said it works on Android , i mean opening the context-menu with a long touch.
On iOS mobile devices it doesn't work. In my opinion it is problem with compatibility with Safari.
I think i just added information about my enviroment.

I have some ideas to walkaround, like : 
- opening context-menu while editing cell, but could not create new instance of ContextMenu and open it on edit cell action or on button click. Some ideas? 

Thanks

**Comment by AMBudnik** [comment]
Sorry for the confusion. I was actually thinking about merging your information into the #4833 but maybe it would be better to keep them separate as they refer to different devices.
I am not sure if we'd be able to find any cause without debugging. I'll mark the issues as a bug for our devs to research.

**Comment by Splaktar** [comment]
This appears to be caused by the following in https://handsontable.com/docs/sass/modules/ModCommon/_normalize.scss
```css
html {
    -webkit-touch-callout: none;
}
```
Docs: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout

Workaround that may work:
```css
html {
  -webkit-touch-callout: default;
}

**Comment by AMBudnik** [comment]
thank you for investigating this issue and sharing a workaround @Splaktar

**Comment by wojciechczerniak** [comment]
From #4833:

> ### Description
> 
> Cannot use a context menu on a mobile device
> ### Steps to reproduce
>     1. Open http://jsfiddle.net/Lp4qn55v/887/ on a mobile device
>     2. Tap and hold on any cell
>     3. Try and use any function of the context menu
> 
> ### Demo
> http://jsfiddle.net/Lp4qn55v/887/
> ### Your environment
> 
>     * Handsontable version: 1.15.0 (pro)
>     * Browser Name and version: Google Chrome 64.0.3282.137
>     * Operating System: Android 7.0.0; SM-G955F

**Comment by PiotrKupniewski** [comment]
> 
> 
> This appears to be caused by the following in https://handsontable.com/docs/sass/modules/ModCommon/_normalize.scss
> 
> ```css
> html {
>     -webkit-touch-callout: none;
> }
> ```
> 
> Docs: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout
> 
> Workaround that may work:
> 
> ```css
> html {
>   -webkit-touch-callout: default;
> }
> ```



> 
> 
> This appears to be caused by the following in https://handsontable.com/docs/sass/modules/ModCommon/_normalize.scss
> 
> ```css
> html {
>     -webkit-touch-callout: none;
> }
> ```
> 
> Docs: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout
> 
> Workaround that may work:
> 
> ```css
> html {
>   -webkit-touch-callout: default;
> }
> 

Thanks for your help 

> 
> 
> This appears to be caused by the following in https://handsontable.com/docs/sass/modules/ModCommon/_normalize.scss
> 
> ```css
> html {
>     -webkit-touch-callout: none;
> }
> ```
> 
> Docs: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout
> 
> Workaround that may work:
> 
> ```css
> html {
>   -webkit-touch-

**Comment by wojciechczerniak** [comment]
@PiotrKupniewski Can you explain why have you closed the issue?

**Comment by PiotrKupniewski** [comment]
@wojciechczerniak  Sorry, my mistake. I diddnt want it.

**Comment by wojciechczerniak** [comment]
Ok, I'll reopen then 👍

**Comment by AMBudnik** [comment]
It still does not work for v8.0.0
I've tried this demo https://handsontable.com/docs/8.0.0/demo-context-menu.html on iPhone Xs Safari

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Interoperability problems using Mobile devices and some core features** task reported at https://github.com/handsontable/handsontable/issues/7520

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
