### ISSUE TITLE
After sorting and source data change, toPhysicalRow incorrectly returns data.length instead of correct translated index

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5172]
### Description
I have an issue where `hotInstance.toPhysicalRow()` is incorrectly returning the source data array `length` instead of the actual translated row. This happens consistently in my app with the following sequence of actions (which includes websockets triggering some of the actions), but I haven't been able to manually recreate a minimal demo of the behavior:

### Steps to reproduce
1. Sort on a column
2. Append a new row to the source data array
3. Call `hotInstance.render()`
4. The `afterRenderer` hook is called, inside that I call `hotInstance.toPhysicalRow(row)`. For the row that was just added I get `data.length` instead of the correct source array index of the row.
5. I also notice in the debugger that `getData()` shows the row as completely null (row 6):
![image](https://user-images.githubusercontent.com/2973900/41235877-c9dd4888-6d5d-11e8-9074-3e33b1039848.png)

Even though `getSourceData()` for that row is populated (source row index 46):
![image](https://user-images.githubusercontent.com/2973900/41236096-3a30b228-6d5e-11e8-88ab-cbadaa370055.png)
...
![image](https://user-images.githubusercontent.com/2973900/41236009-0a1fa6d4-6d5e-11e8-9990-bdbc9a84dcfe.png)

And this is what I get after `toPhysicalRow()`:
![image](https://user-images.githubusercontent.com/2973900/41236194-7ccdc04e-6d5e-11e8-8e09-14fdc9df3e47.png)

### Code
I render Handsontable with the `react-handsontable` wrapper like this:
```
        <HotTable root={ id }
                      ref={ this.setRef }
                      data={ data }
                      colHeaders={ colHeaders }
                      columns={ columns }
                      fixedColumnsLeft={ 1 }
                      manualColumnResize={ true }
                      afterRenderer={ this.handleAfterRenderer }
                      afterChange={ this.handleAfterChange }
                      afterCreateRow={ this.handleAfterCreateRow }
                      afterValidate={ this.handleAfterValidate }
                      afterColumnSort={ this.handleAfterColumnSort }
                      afterFilter={ this.handleAfterFilter }
                      afterSetDataAtCell={ this.handleAfterSetDataAtCell }
                      afterSelectionEndByProp={ this.handleAfterSelectionEndByProp }
                      rowHeaders={ true }
                      readOnly={ readOnly }
                      stretchH="all"
                      autoWrapRow={ true }
                      allowInsertRow={ allowAddProjects }
                      allowInsertColumn={ false }
                      minSpareRows={ allowAddProjects ? 1 : 0 }
                      allowInvalid={ !!allowInvalid }
                      columnSorting={ ProjectsTable.COLUMN_SORTING_CONFIG }
                      sortIndicator={ true }
                      filters={ true }
                      dropdownMenu={ !allowAddProjects && this.dropdownMenuConfig }
                      wordWrap={ false }
                      rowHeights={ 32 }/>
```

And the relevant `afterRenderer` code looks like this:
```
handleAfterRenderer = (td, row, col, prop, value, cellProperties) => {
    const physicalRow = hotInstance.toPhysicalRow(row);
    const rowData = hotInstance.getSourceDataAtRow(physicalRow);
    // Right here `rowData` is undefined in the above example, which leads to TypeError below
    const rowId = rowData[ROW_ID];
    const user = presenceUsers.find(u => hasEvent(u.lastActivityEvent, rowId, prop));
    td.classList.toggle(styles.cellPresenceHighlight, !!user);
    if (user) {
      const elem = document.createElement("span");
      elem.textContent = getUserInitials(user.user) || "";
      elem.className = styles.cellPresenceInitials;
      td.appendChild(elem);
    }
}
```
(Aside: this is a mechanism to render a special highlight and user initials around cells that other users are editing, anything I'm doing wrong here please point out!)

### Demo
Attempt to re-create with demo, but it doesn't exhibit above behavior:
<s> http://jsfiddle.net/6tcen8yo/ </s>

### Your environment
* Handsontable version: Pro 2.0.0 and React Wrapper
* Browser Name and version: Chrome 66
* Operating System: MacOS High Sierra

**Comment by AMBudnik** [comment]
Hi @aaronbeall 

I hope that the issue can be solved via https://github.com/handsontable/handsontable/issues/5112 but it is a subject for investigation. Thank you for reporting

**Comment by wojciechczerniak** [comment]
@aaronbeall The general idea is that you're getting different results with `getData` and `getSourceData` because one of the plugins returns wrong item physical index that refers to source data. Two things are important here: which plugins you have enabled and how you add the row to the source data.

If you are modifying data object through reference then there is little that we can do. Plugins are not notified about changes made outside the Handsontable and can't update their meta data. Your new row does not exist in their meta, a `null` is returned and empty row will be rendered. Try using the Handsontable API `alter('insert_row')` method, which triggers `afterCreateRow` hook.

If that won't resolve the issue a demo would be helpful.

**Comment by aaronbeall** [comment]
Thanks for the feedback, @wojciechczerniak. Indeed I'm modifying the source data directly... I can see how this is an issue. 

I've struggled with this quite a lot, basically reconciling our data model with that of the table. Changes to the source data model can happen from anywhere, both small and large, both by the user and by other users concurrently, both by direct user action and "side effects" by the server pushed to all clients, and the table is essentially just a live "view" of the data. Right now I have a function that compares the incoming data with what's currently in the table and updates the table's source data directly for any difference (row added, row deleted, row moved, row data updated), then calls `render()` (there are some nuances but that's the general idea). I had at one point tried calling the `alter()` methods but ran into performance problems when there were many changes. I also ran into many issues simply re-setting the entire data anytime changes were detected, the table was essentially unusable. That's how I landed at the current approach. I will revisit this approach.

Closing for now.

**Comment by wojciechczerniak** [comment]
We had `observeChanges` plugin for that but it has it's own issues and I don't recommend it anymore. It had to watch `data` object for changes in the interval and make a diff at each cycle. Not the best approach. 

But if you have your own logic to add/remove rows and you know what was changed you can notify other plugins as the `observeChanges` did:

https://github.com/handsontable/handsontable/blob/c2ba2dc02e3eb883a58f976ef5944fa629dc981d/src/plugins/observeChanges/observeChanges.js#L98-L104

I took the same approach with Redux/Vuex stores. Some operations had to be taken outside and handled with hooks. But that's also related to `data` object being modified by the store. You're right, we should work on APIs for data updates and I've already found some shortcomings, we will address them soon.
