### ISSUE TITLE
Improve CSS frameworks compatibility

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5175]
### Description
Overwrite common frameworks (Bootstrap, Foundation) by specifying some of the features for table, tr, td, th, thead and tbody in our CSS file.

**Comment by AMBudnik** [comment]
I am closing this proposition of a change as we are not currently working on the piece of code that it relates to.
Once we open an issue we check all pinned issues and pull requests even if they are closed so please keep track of updates to this issue. All additional comments are also highly appreciated.
