### ISSUE TITLE
Crl + C on Row not working on Google Chrome

### ISSUE THREAD

**Issue by Joshua-W-Adams** [handsontable/handsontable#5176]
### Description

I recently updated my Handsontable library in my web application to version 3.0.0.

However, when I try to copy a whole row by clicking on the row header then pressing crl + c nothing is copied to the clipboard.

I am using Google Chrome 67.0.3396.87.

This error can be replicated by going to the following url and trying to copy a row. https://handsontable.com/examples

Does anyone know why this functionality is not working? I suspect it may be a bug with the new version of the Handsontable library.

### Steps to reproduce

1. Open google chrome
2. Go to https://handsontable.com/examples
3. Left click on any row header
4. Now that the whole row is highlighted, press crl + c
5. Open MS Excel
6. Press crl + v to try and paste row to sheet
7. Row is not pasted to the sheet

### Demo

https://handsontable.com/examples

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: Google Chrome 67.0.3396.87.
* Operating System: W10.

**Comment by AMBudnik** [comment]
Hi @Joshua-W-Adams 

sorry, but I cannot replicate it and I'm also on Chrome 67/Windows 10.

![gif](https://user-images.githubusercontent.com/10757813/41645358-0973494c-7471-11e8-8b2e-b3049df0610c.gif)

This demo is currently using v `4.0.0`. Can you update to `4.0.0` and check if you still get the same behavior?

**Comment by Joshua-W-Adams** [comment]
Hi Alexandra,

I updated my handsontable-pro library to v4.0.0 and the issue still persists in my web application.

However, the issue is no longer present in https://handsontable.com/examples now that it is upgraded to v4.0.0.

Do you have any ideas on specific settings I may have enabled or disabled in my handsontable that may be causing this to occur? Otherwise ill see if I can get it to replicate on a JSfiddle.

Also what program did you use to make that GIF in your post above?

Cheers,

Josh

**Comment by AMBudnik** [comment]
Hi Josh,

if

> the issue still persists in my web application

then I guess that the only way to check what's wrong is to push the code to JSFiddle and check if it still replicable. Maybe you use some options or methods that change this behavior?

ps. I'm using a small tool called [GitCam](https://download.cnet.com/GifCam/3000-12511_4-75891451.html).

**Comment by AMBudnik** [comment]
Thank you for doing the investigation @rscotton 
I'm afraid that the team won't pick the https://github.com/handsontable/handsontable/issues/5054 before we do the copy-paste refactor.

**Comment by Joshua-W-Adams** [comment]
Further to discussions above. I have done some further testing. See summary below.

v3.0.0
https://jsfiddle.net/JoshAdams/f2Lp40hm/

- Copy and paste does not operate at all. However, this is only apparent on Chrome and Opera and works correctly on Firefox and Edge.

v4.0.0
https://jsfiddle.net/JoshAdams/3nf1byu0/

- Copy and paste does not operate when readOnly: true on For Chrome and Opera. Operates correctly on Firefox and Edge.
- Operates correctly when readOnly: false for Chrome, Opera, Firefox and Edge

v1.18.1
https://jsfiddle.net/JoshAdams/0pkhq2xj/

- Copy and paste operates correct on all browsers, irrespective of readOnly status.

@AMBudnik - When is the copy-paste re-factor due to complete? As there are definitely issues that have been introduced to it since 1.18.1.

@rscotton  - To answer your questions to AMBudnik and myself in your previous post. It is likely that the primary example is not exhibiting this issue as it is not set to readOnly:true. And I am using a custom cell editor in my implementation but when I updated to v4.0.0 and disabled readOnly mode this issue was no longer prevalent for me.

**Comment by AMBudnik** [comment]
Hi @Joshua-W-Adams 

there are two `regression` issue introduced in v 2.0.0 and 4.0.0
https://github.com/handsontable/handsontable/issues/5054
https://github.com/handsontable/handsontable/issues/5201 
However, the `5201` is going to be fixed within the next version of Handsontable (5.0.0) planned for next week.

We do not have any refactoring in plans for July.

**Comment by swistach** [comment]
This issue will be solved within #4931

**Comment by AMBudnik** [comment]
Please update to 6.1.0 we published a fix for this issue
