### ISSUE TITLE
Filtering doesn't work after moving rows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5178]
### Description

Filtering doesn't work after moving rows

### Steps to reproduce

1. Move last row (`BMW`) to the first position
2. Filter `BMW` out

![gif](https://user-images.githubusercontent.com/10757813/41334095-8e86d186-6ee4-11e8-98e9-0b4ecc9e05a6.gif)

Expected:
We get 4 rows without `BMW`.

Received:
`BMW` is gone but also `Opel`. We get an extra empty row.

### Demo

http://jsfiddle.net/e9akj1ts/

### Your environment
* Handsontable version: 3.0.0
_Doesn't seem to work well in any version_
* Browser Name and version: Chrome 67
* Operating System: Windows 10

Possibly will be gone after https://github.com/handsontable/handsontable/issues/5112
_Inform Gr# 15345_

**Comment by AMBudnik** [comment]
Works the same in v 5.0.0

**Comment by pnowak** [comment]
I think that this bug is result of no communication between rowsMapper trimRows and rowsMapper manualRowMove. We just have to waiting to Global index mapper #5112

**Comment by AMBudnik** [comment]
Works the same in `7.1.1`
![image](https://user-images.githubusercontent.com/10757813/65045917-f2321600-d95f-11e9-9a7d-19a9e90d9e2d.png)
http://jsfiddle.net/handsoncode/caLguq4o/

In `8.0.0.-rc1` it's fixed
http://jsfiddle.net/handsoncode/ueb42ncp/
![image](https://user-images.githubusercontent.com/10757813/65046075-36bdb180-d960-11e9-8c14-1515beb1906e.png)

**Comment by AMBudnik** [comment]
Works well now http://jsfiddle.net/wc1evju0/ (8.0.0-beta1)

![GIF](https://user-images.githubusercontent.com/10757813/68929079-d397a200-078b-11ea-9f96-d67c69d79443.gif)

**Comment by AMBudnik** [comment]
I'm glad to announce that this issue can be closed as solved http://jsfiddle.net/5rxgjof2/1/
