### ISSUE TITLE
Merge Cells plugin disables selectionMode: single

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#5181]
### Description
`selectionMode: 'single'` won't work with enabled merge cells plugin.

### Steps to reproduce
1. Set `selectionMode: 'single'`
2. You can only select one cell. https://jsfiddle.net/acqx8spb/
3. Add merge cells plugin: `mergeCells: true`
4. You can select a range of cells now. https://jsfiddle.net/acqx8spb/2/

### Demo
Before: https://jsfiddle.net/acqx8spb/
After: https://jsfiddle.net/acqx8spb/2/

### Your environment
* Handsontable version: 4.0.0
* Browser Name and version: Firefox 60.0.2
* Operating System: Mac OS

**Comment by AMBudnik** [comment]
Works the same in 8.0.0 beta1 https://jsfiddle.net/1j2dsfpL/

**Comment by warpech** [comment]
In fact, using `selectionMode: 'single'` with `mergeCells: []` creates an incorrect, weird state, in which:

- cells can be selected like in `selectionMode: 'range'`
- headers are highlighted like `selectionMode: 'single'`

We spent several hours investigating this in a project. Maybe this combination of features should be disabled (or at least add a console warning?) until there is a fix.

<img width="1100" alt="Screenshot 2020-07-29 at 09 20 15" src="https://user-images.githubusercontent.com/566463/88769540-d5b85a00-d17c-11ea-812c-080db893b6b0.png">

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/dev-handsontable/issues/810 as solved .
