### ISSUE TITLE
[2.0.0+] Missing colheaders in collapsible/edit option

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5188]
### Description

Missing colheaders in collapsible/edit option. We have to edit some cells to replicate the issue. 

**An subject for further investigation.**

### Steps to reproduce

1. Collapse all the columns
2. Select all cells and remove their content
3. Expand any column (in  my example it was `E`)

![gif](https://user-images.githubusercontent.com/10757813/41467284-2d0dcc2a-70a6-11e8-8c29-d5ca4d16a9f2.gif)

### Demo

https://docs.handsontable.com/pro/4.0.0/demo-collapsing-columns.html

### Your environment
* Handsontable version: 2.0.0+
_1.18.1 works fine_
* Browser Name and version: Chrome 67
* Operating System: Windows 10

**Comment by pnowak** [comment]
Duplicate - https://github.com/handsontable/handsontable-pro/issues/105

**Comment by AMBudnik** [comment]
Released: v5.0.2
