### ISSUE TITLE
Binding to data via MVC

### ISSUE THREAD

**Issue by PollyAnna44** [handsontable/handsontable#519]
Hi, 

I am having problems displaying the data that I get using my MVC framework.

The data consists of an IEnumerable list of type DocCat, which only has 3 fields - CategoryId, Name, and Details, and it gets the information successfully - 

![ControlMethod](https://f.cloud.github.com/assets/3935939/296077/40ff33e6-94d7-11e2-8748-4acb6d9a56d5.JPG)

In my view I am displaying the info using the following jQuery syntax - 

![View](https://f.cloud.github.com/assets/3935939/296079/8717325c-94d7-11e2-8f75-96e70d3688ab.JPG)

the result is just a long list of the data but no HandsOnTable - 

![result](https://f.cloud.github.com/assets/3935939/296082/c16e18e4-94d7-11e2-9071-125122b74bd0.JPG)

I would really appreciate any help telling me where I am going wrong.

All much appreciated.

Kind regards, 

Polly

**Comment by yehia2amer** [comment]
Please take a look at this example for more details on how to implement "Handsontable" with MVC

http://www.codeproject.com/Tips/1074230/Load-and-save-Handsontable-data-from-to-Controller
