### ISSUE TITLE
After sorting, Data should change as view changes

### ISSUE THREAD

**Issue by abhishek3999** [handsontable/handsontable#5192]
Data source should change at the time of sorting.
Because in my case I used links withing table to show pdf.when I used to columnSorting:true,view gets changes but link's reference unchanged.What should I do?

**Comment by AMBudnik** [comment]
I am closing the issue as there's no reply for more than a week but if you're still looking for a fix @abhishek3999  let me know

**Comment by abhishek3999** [comment]
Sorry for late reply.
I explain senario:
In hot table 10 rows as records having feature sorting,searching. rows
containing linkable records so that when we click one of record opens PDFs.
All works fine until we don't sort.
Once we proceed to sort and click to view PDF for particular record from a
row then PDF mismatches.
It means that sorting done but data could not sorted.
Please help me on this issue.

**Comment by AMBudnik** [comment]
Your issue might be related to https://github.com/handsontable/handsontable/issues/5112 but without a demo, it will be hard to share a real opinion. Can you push your initialization setting in the JSFiddle?

**Comment by abhishek3999** [comment]
``const options = {
      rowHeaders: true,
      colHeaders: [],
      colWidths: 100,
      formulas: true,
      search: true,
      contextMenu: ['hidden_columns_show', 'hidden_columns_hide', 'freeze_column'
        , 'unfreeze_column', 'alignment', 'remove_row'],
      autoInsertRow: false,

      height: 560,
      filters: true,
      dropdownMenu: ['filter_by_condition', 'filter_by_value', 'filter_action_bar'],
      minSpareRows: 1,
      manualColumnResize: true,
      manualRowResize: true,
      manualColumnFreeze: true,
      manualColumnMove: true,
      hiddenColumns: {

        indicators: true
      }


    };``
After that I call an API to get data.option['data'] = response; In response I get links of pdf that I shows in coloumns.
        this.hot = new Handsontable(document.getElementById("hot-table"), options)
In html
<div id="hot-table" class="hot handsontable htColumnHeaders"></div>
that's it.
hope this helps.If do you need more inputs please let me know.
sorting performs.all rows sorts,

**Comment by AMBudnik** [comment]
Can you also add `data`? Without it, I will be hard to understand the action of

> After that I call an API to get data.option['data'] = response; In response I get links of pdf that I shows in coloumns.

**Comment by abhishek3999** [comment]
@aleksandra

This issue was related index mapping.
One more thing want to ask that is If I would apply filter then filtered
data shows in a table.
then how could I map index.I have getSourceData() that is complete data
records.
after filter, some records get trimmed and will get filtered records.how to
get this filter record object.
getData() is not working for me

Please do help.

**Comment by AMBudnik** [comment]
Hi @abhishek3999 
`getData` method returns an array even if data is an object. That is definitely something to change but we do not have any method to return an entire array of objects for data after sorting/filtering/trimming. You can try to check what indexes are visible (`toPshyhicalRow()`) and then use `getSourceDataAtRow()` method to return a full object for a row.

**Comment by AMBudnik** [comment]
Here is a demo http://jsfiddle.net/n68krug5/

**Comment by abhishek3999** [comment]
Thank you so much. Resolved issue.

On Tue, Jul 3, 2018 at 12:51 PM, Aleksandra Budnik <notifications@github.com
