### ISSUE TITLE
Date not displaying on handsontable 

### ISSUE THREAD

**Issue by primeO** [handsontable/handsontable#5194]
### Description
Trying to render date on handsontable , showing unexpected number in line 1 . Am i missing any thing !!
### Code
	
		
				<script src="#{request.contextPath}/odassets/grid/moment.js"></script>
				<script src="#{request.contextPath}/odassets/grid/pikaday.js"></script>
				<link type="text/css" rel="stylesheet"
				href="#{request.contextPath}/odassets/grid/pikaday.css"></link>

 var cols = [
                                     { data: 'XXXXX', type: 'text'},
                                    
                                     { data: 'XXXXX', type: 'text'},
                                     { data: 'XXXXX', type: 'text'},
                                     { data: 'XXXXX', type: 'text'},
                                     { data: 'XXXXX', type: 'text'},
                                     { data: 'XXXXX', type: 'text'},
                                     { data: 'DeliveryDate', type: 'date' }
                                    ];  
                        

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version:
* Operating System:

And is there any demo for both time and date .

**Comment by AMBudnik** [comment]
Sorry @primeO but it is hard to guess what is causing the issue. I do not see any number in the first line of 

```js
var cols = [
{ data: 'XXXXX', type: 'text'},
{ data: 'XXXXX', type: 'text'},
{ data: 'XXXXX', type: 'text'},
{ data: 'XXXXX', type: 'text'},
{ data: 'XXXXX', type: 'text'},
{ data: 'XXXXX', type: 'text'},
{ data: 'DeliveryDate', type: 'date' }
 ]; 
```
can you create a JSFiddle?

> And is there any demo for both time and date .

We do not have any date-time cell type, only those two separately:
1. [Date](https://docs.handsontable.com/pro/4.0.0/demo-date.html)
2. [Time](https://docs.handsontable.com/pro/4.0.0/demo-time.html)

**Comment by primeO** [comment]
please find the link : 

https://jsfiddle.net/prime0/6tcs8wh7/5/#&togetherjs=tLidvtQ3be

**Comment by AMBudnik** [comment]
How to replicate the issue you're facing?

> unexpected number in line 1

I do not get in on initialization or cell edit.

**Comment by primeO** [comment]
@AMBudnik 
"unexpected number in line 1"
thanks for your reply , that issue i had resolved just it is the problem of my data which had been passed .
Data which i was passing is including of minutes . 

in this case also iam getting only the year as you can see in my link . Any solution for that .

**Comment by AMBudnik** [comment]
Hi @primeO 

the system does not know how to make ``MM/DD/YYY` from a value of `7780` (`g`).
You have a date related format in `b` but no `type: date` settings, like for column `g`

**Comment by primeO** [comment]
Thanks @AMBudnik . Issue is resolved

**Comment by AMBudnik** [comment]
Also closing this one. 

Have a great day @primeO
