### ISSUE TITLE
[4.0.0+] Handsontable cell type can be opened only once

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5195]
### Description

We are not able to open a table-in-table more than once without using double click.

### Steps to reproduce

1. Open cell containing `Tesla`
2. Open cell containing `Volvo`

**Result**:
There's no table-in-table effect - only an opened editor for `Volvo`.

![gif](https://user-images.githubusercontent.com/10757813/41533901-bb7ac2f8-72fc-11e8-87dc-9c533e274227.gif)

### Demo

buggy `4.0.0` -  http://jsfiddle.net/bfxjq67p/
working: `3.0.0` - http://jsfiddle.net/6kzwbntc/

### Your environment
* Handsontable version: 4.0.0
* Browser Name and version: Chrome 67
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
Demo in 5.0.1 RC: http://jsfiddle.net/bfxjq67p/5/ 👍

**Comment by AMBudnik** [comment]
Thanks for fixing!
