### ISSUE TITLE
Scrolling using 'wheel' while constraining width but not height of table (also see #2845)

### ISSUE THREAD

**Issue by d95sld95** [handsontable/handsontable#5198]
### Description

I am trying to allow full page vertical scroll when the mouse cursor is over the HOT table. But it seems like the 'wheel' events gets hijacked somehow. 

The setup is like this: 

```
<div flex>
   <div id="hot" style="overflow: scroll; height: 100%"></div> 
<div>
```
I tried to follow the steps in issue #2845 but I was not successful. 

### Steps to reproduce

1. Goto http://jsfiddle.net/t0m84fna/7/
2. Place your mouse cursor over the handsontable and try and scroll up or down using your mouse 'wheel' or finger swipe. 
3. Move your cursor outside the handsontable and scroll up or down like in 2.)

I am looking for the behaviour from step 3 when the cursor is over the HOT table.

### Found the code
In line 24818 of the handsontable.full.js file the following code is registering the wheel. If I comment out the listenersToRegister.push from the code below it all works as I would like. I just don't know what side effects it might have and how I could possibly remove the event listener from my code so I do not need to modify handsontable.full.js. 

```
      var isHighPixelRatio = window.devicePixelRatio && window.devicePixelRatio > 1;

      if (isHighPixelRatio || !(0, _browser.isChrome)()) {
        listenersToRegister.push([this.instance.wtTable.wtRootElement.parentNode, 'wheel', function (event) {
          return _this.onCloneWheel(event);
        }]);
      } else {

```

### Demo

http://jsfiddle.net/t0m84fna/7/

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: Chrome 67.0.3396.87
* Operating System: OSX Sierra (v.10.12.6)

**Comment by AMBudnik** [comment]
Hi @d95sld95 

it looks like here's the issue to follow https://github.com/handsontable/handsontable/issues/4114
Handsontable doesn't support any rush `overflow` changes as it uses `px` value to generate itself it needs fixed `width` and `height` to generate properly.
