### ISSUE TITLE
Copy/Paste colHeaders and rowHeaders

### ISSUE THREAD

**Issue by eugeniospolti** [handsontable/handsontable#52]
Hi ,

is there a way to copy/paste to Excel my row and col headers?

**Comment by kodmax** [comment]
The hotfix no longer works and it is really useful to be able to export (copy) to excel with the columns header names.

**Comment by XMais** [comment]
I needed this function for my project so i fixed it for the new version:

handsontable.full.js - Line 5498

/**

DataMap.prototype.getRange = function(start, end, destination) {
  var r,
      rlen,
      c,
      clen,
      output = [],
      row;
  var getFn = destination === this.DESTINATION_CLIPBOARD_GENERATOR ? this.getCopyable : this.get;
  rlen = Math.max(start.row, end.row);
  clen = Math.max(start.col, end.col);
  for (r = Math.min(start.row, end.row); r <= rlen; r++) {
    row = [];
    for (c = Math.min(start.col, end.col); c <= clen; c++) {
      row.push(getFn.call(this, r, this.colToProp(c)));
    }
    output.push(row);
  }
	
	// Add these lines
	
	var theaders = this.instance.getColHeader();
	
	theaders = theaders.slice(start.col, end.col+1);	
	
	output.unshift(theaders);

  return output;
};

**/

**Comment by XMais** [comment]
I fixed it for the newest 1.14.3.
However, since i currently dont own the Pro-version of handsontable, the lines may  be inaccurate.

**Change the core method getRangedData** - line 71747 and following in evaluation version
`key: 'getRangedData',
value: function getRangedData(ranges) {`

**to this:**

`var _this4 = this;

      var dataSet = [];
      var copyableRows = [];
      var copyableColumns = [];

      // Count all copyable rows and columns
      (0, _array.arrayEach)(ranges, function (range) {
		  
		
		// XMAIS - add col headers
			var colHeaders = hot.getColHeader();
			
			colHeaders = colHeaders.slice(range.startCol, range.endCol+1);
			colHeaders.unshift('');
			
			dataSet.push(colHeaders);
		// END
		  
        (0, _number.rangeEach)(range.startRow, range.endRow, function (row) {
          if (copyableRows.indexOf(row) === -1) {
            copyableRows.push(row);
          }
        });
        (0, _number.rangeEach)(range.startCol, range.endCol, function (column) {
          if (copyableColumns.indexOf(column) === -1) {
            copyableColumns.push(column);
          }
        });
      });
      // Concat all rows and columns data defined in ranges into one copyable string
      var rowHeaders = hot.getRowHeader();
	  (0, _array.arrayEach)(copyableRows, function (row) {
        var rowSet = [];
		
		// XMAIS - add row headers
			var rowHeader = rowHeaders.slice(row,row+1);
		
			rowSet.push(rowHeader);
		// END

        (0, _array.arrayEach)(copyableColumns, function (column) {
          rowSet.push(_this4.hot.getCopyableData(row, column));
        });

        dataSet.push(rowSet);
      });
	  
	  
      return dataSet;`

**Comment by paulo-raca** [comment]
Neat, Thanks :)

@XMais, would you mind creating a PR for that? (You will probably have to add an enable flag?)

**Comment by pdivos** [comment]
Many thanks @XMais, works like charm!

**Comment by chris601** [comment]
This will update the headers,, out of the library !!

beforeCopy: function (data, coords) {
          let Range = this.getSelectedRange();
          let cell = getSelectedOrdered(this);
          let sRow = cell[0];
          let eRow = cell[2];
          let sCol = cell[1];
          let eCol = cell[3];

          let RowHeaders = this.getRowHeader().slice(sRow, eRow + 1).map(String);
          let ColHeaders = this.getColHeader().slice(sCol, eCol + 1).map(String);
          data.unshift(ColHeaders);

          for (let x in data) {
            if (+x === 0) {
              data[+x].unshift("");
            } else {
              data[+x].unshift(RowHeaders[+x - 1]);
            }
          }
        },
