### ISSUE TITLE
Paste using shift+insert

### ISSUE THREAD

**Issue by matkus** [handsontable/handsontable#520]
Hello.

In most applications i can easyly copy and paste using CTRL+Ins/Shift+Ins insted of CTRL+C/CTRL+V.
it is much easier to use for someone lefthanded or if you have your habits back from DOS times (in both cases, it's me ;) )

Copy to clipboard (CTRL+INS) works fine, but paste (SHIFT+INS) does not. Anyone knows any way to make it work like it should?

**Comment by AMBudnik** [comment]
This option is currently available. It loads copied content into a single cell.

![2gif](https://cloud.githubusercontent.com/assets/10757813/25219512/088af3ca-25af-11e7-89bb-2c7a9024d9d6.gif)
