### ISSUE TITLE
Side-by-side view with several instances of handsontable

### ISSUE THREAD

**Issue by onyx1337** [handsontable/handsontable#5205]
Hello, 
Is it possible to connect somehow several tables to make side-by-side view. (connect scrolls to scroll simultaneously )  
Is there some scroll events ?

**Comment by AMBudnik** [comment]
Hi @onyx1337 

You can use the [`afterScrollHorizontally`](https://docs.handsontable.com/pro/4.0.0/Hooks.html#event:afterScrollHorizontally) event on the first table to activate [`scrollViewportTo`](https://docs.handsontable.com/pro/4.0.0/Core.html#scrollViewportTo) method on the second table.

**Comment by AMBudnik** [comment]
Hi @onyx1337 
Issue reopened? Do you need any feedback on this case?

**Comment by onyx1337** [comment]
Hi @AMBudnik 
Sorry, I found out that afterScrollHorizontally doesn't return event. 
How I can get scrollLeft  value ?

**Comment by AMBudnik** [comment]
Hm... you're right. Maybe the `getFirstVisibleColumn`/ `getLastVisibleColumn` would help?
Here's a demo http://jsfiddle.net/aed5tyfm/

**Comment by onyx1337** [comment]
Thank you , but I'm looking for accurate pixel value (because in case of using getFirstVisibleColumn scrolling will not be smooth , it will be unevenly)
Maybe there is some other option ?

**Comment by AMBudnik** [comment]
Hm... I'm just leaving work now but I'll check it on Monday and share my thoughts.

**Comment by AMBudnik** [comment]
Hi @onyx1337 

it looks like the `wtHolder` div holds the event http://jsfiddle.net/m9a7ofcz/

**Comment by onyx1337** [comment]
@AMBudnik Wow, it's awesome, thank you a lot.

**Comment by j770657446** [comment]
![image](https://user-images.githubusercontent.com/48500891/61111334-eb000f00-a4bb-11e9-992b-f6ff116f9f77.png)
