### ISSUE TITLE
TypeScript definitions for ColumnSorting are wrong

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5209]
### Description
I recently upgraded to `4.0.0` and noticed that the type definitions for column sorting are incorrect. Some issues I ran into:

1. `Handsontable.plugins.ColumnSorting.sort()` is defined with no parameters, [but it should have `(column, order)`](https://github.com/handsontable/handsontable/blob/master/src/plugins/columnSorting/columnSorting.js#L149):
```ts
interface ColumnSorting {
  sort(column: number, order?: "asc" | "desc" | "none"): void;
}
```
2. `Hooks.afterColumnSort()` defines order as `boolean` instead of the new enum. I think it should be:
```ts
interface Hooks {
  afterColumnSort?: (column: number, order: "asc" | "desc" | "none") => void;
}
```
3. The `ColumnSorting` defines some stuff that I don't see in the documentation or the runtime objects, like `dateSort()` and `defaultSort()`. 

In general seems like the definitions have not been updated to match the changes made to the sorting plugin recently?

### Your environment
* Handsontable version: Pro 4.0.0
* Browser Name and version: Chrome
* Operating System: MacOS High Sierra

**Comment by AMBudnik** [comment]
> In general seems like the definitions have not been updated to match the changes made to the sorting plugin recently?

You're right. I do not see any changes in the definitions file after we changed the values for columnSorting. Thanks for reporting @aaronbeall

**Comment by aaronbeall** [comment]
@AMBudnik Would you accept a PR with these changes? I'm not sure if you guys have some scripts to generate `handsontable.d.ts` or if it's maintained by hand?

**Comment by AMBudnik** [comment]
Not so happy to admit but we're doing it manually. Thank you for sharing the PR!

**Comment by budnix** [comment]
PR was merged. The issue can be closed.

**Comment by AMBudnik** [comment]
Great! Thanks for merging
