### ISSUE TITLE
Copy/Paste AutoComplete with strict mode in IE8

### ISSUE THREAD

**Issue by grfrm99** [handsontable/handsontable#521]
Based on the "Cell types" sample (http://handsontable.com/demo/renderers.html)

1. Add the strict mode to the "color" cell:
    { data: "color",
        type: 'autocomplete',
        source: ["yellow", "red", "orange", "green", "blue", "gray", "black", "white"], 
        strict: true /* Set Autocomplete cell to strict mode */
    }

2. Open the page in IE8
3. Select more than one rows
4. Copy and paste the rows
5. Data are missing for the autocomplete cells

![CopyPaste_IE8](https://f.cloud.github.com/assets/3863007/298560/978c78c0-9560-11e2-8780-caf921838e7c.png)
.

Tested on 0.8.15

**Comment by AMBudnik** [comment]
Dropped support for IE8
