### ISSUE TITLE
Handsontable cell edit mode mouse right click event

### ISSUE THREAD

**Issue by VenubabuSunkara** [handsontable/handsontable#5213]
![image](https://user-images.githubusercontent.com/9213644/41915481-74fa21ac-7973-11e8-8d07-246086fb2eb7.png)

In excel we have cell edit mode context menu with different options. How can i do custom on handsontable, event is not firing. Please help me

**Comment by AMBudnik** [comment]
I am not sure if I understand correctly. Would you like to know how to add `paste` to the contextMenu or create any custom option for the `menu`?

**Comment by VenubabuSunkara** [comment]
Hi AMBudnik,

**Below 2 screen shorts are taken in Microsoft excel**
1.    ![image](https://user-images.githubusercontent.com/9213644/41977932-42f0f048-7a3e-11e8-98e8-2aaea5b9f6ba.png)
2.    ![image](https://user-images.githubusercontent.com/9213644/41978041-89646bfe-7a3e-11e8-9022-d58c16bdca1c.png)

**Below 2 screen shorts are taken in Handsontable**
3.   ![image](https://user-images.githubusercontent.com/9213644/41978111-b82fc8d4-7a3e-11e8-950b-7e81d83a6c06.png)
4.    ![image](https://user-images.githubusercontent.com/9213644/41978222-fda28a1e-7a3e-11e8-8342-0380ec855516.png)


1. Microsoft Excel Cell on click we can able to see small context menu as per screen short 2
Is there any feature is available same like in handsontable

**Observations on handsontable**
 
1. I observed on cell select and right click Context menu is dynamically generating content and adding in div
2. After cell edit mode it is the dynamic context menu html is going empty
3. I found one example in online (jquery.handsontable.full.js and css) this files we will add into page cell edit mode also context menu is displaying but problem is we unable to create object on handsontable

Please help me.

**Visited Link:**
https://www.jqueryscript.net/demo/Excel-like-Data-Grid-Editor-For-jQuery-handsontable/demo/contextmenu.html   (Edit mode context menu)


![image](https://user-images.githubusercontent.com/9213644/41978833-4443b9c4-7a40-11e8-9475-1560aaf931dc.png)

**Comment by AMBudnik** [comment]
This conversation has been continued at email.

**Comment by wildergeorge** [comment]
When editing a cell, the custom context menu disapears and the windows context menu appears as seen in this screenshot:
![context menu edit](https://user-images.githubusercontent.com/38075046/44022717-ade775e2-9ee8-11e8-98d2-3c9c8c548321.jpg)

We would expect to see the custom context menu as seen in this screenshot:
![context menu normal](https://user-images.githubusercontent.com/38075046/44022738-c5023f3c-9ee8-11e8-85af-d34f9e3fd3c5.jpg)


The example in the link mentioned above (https://www.jqueryscript.net/demo/Excel-like-Data-Grid-Editor-For-jQuery-handsontable/demo/contextmenu.html) shows that it should be possible to have the context menu in editing mode. 
When looking at the examples on handsontable.com we also see the basic context menu and not the custom context menu of handsontable. Is it possible to use the custom context menu when editing a cell, as seen in the example above?

```javascript
      var containerTeilwort = document.getElementById('qualiPrivatkundenTeilwortErgebnis');
      var dataForTable2 = [];

      tablePkTeilwoerterListe = new Handsontable(containerTeilwort, {
        data: dataForTable2,
        stretchH: 'all',
        minRows: 17,
        minCols: 10,
        contextMenu: {
          callback: function(key, options){

            if(key == 'speichern'){
              privatkundenTeilwortlisteSpeichern(this.getSourceDataAtRow(tablePkTeilwoerterListe.getSelected()[0][0]));

            }else if(key == 'loeschen'){

            }
          },
          items: {
            speichern: {
              name: "Speichern"
            },
            copy: {
              name: "Kopieren"
            },
            loeschen: {
              name : "Datensatz löschen"
            }
          }
        },
        colHeaders: ['Element'],
        columns:[
          {data: 'ELEMENT'}
        ],
        rowHeaders: true
      });
```

Thanks in advance !

**Comment by AMBudnik** [comment]
Thanks for spotting that @wildergeorge 
I will discuss this subject with the team

**Comment by wojciechczerniak** [comment]
Excel has the advantage of being a standalone app, we're in the web browser. Preventing native context menu for textarea/input is possible but will probably break the Internet. We're not going to do that.

The context menu inside input is important from accessibility point of view. Web browser has more control over the input, copying, pasting and more. Those are more important for many. Note: Google Spreadsheet does the same.

It still Javascript so find the input, add your event listener and trigger our custom context menu. But it should stay as a custom implementation. If you need help with that we might provide consulting services, please contact us: hello@handsontable.com.
