### ISSUE TITLE
How to get those merged cell's data?

### ISSUE THREAD

**Issue by lycclsltt** [handsontable/handsontable#5215]
I try to use "hot.mergeCells.mergedCellInfoCollection" but console log show it is undefined.

**Comment by AMBudnik** [comment]
Hi @lycclsltt 

we do not have any external API for `mergedCellInfoCollection`. If you mean `mergedCellsCollection` then you should get to the plugin via `got.getPlugin('mergeCells')` and then call the method. Here is a demo http://jsfiddle.net/z6qd5ase/

**Comment by lycclsltt** [comment]
Thank you ,this problem has resloved. But I want to known how to show the table by order desc?
for example , the id is  10, 9, 8, 7.....1.

**Comment by AMBudnik** [comment]
You can set sorting order via `sortOrder: 'desc'`, like

```
var hot = new Handsontable(document.getElementById('example'), {
  columnSorting: {
    column: 0
    sortOrder: 'desc'
  }
});
```

**Comment by lycclsltt** [comment]
![image](https://user-images.githubusercontent.com/8135799/41961412-ff7b3f12-7a24-11e8-9e45-0ae602ea067d.png)

I used this code but it dosen't work.

columnSorting: {
            column: 0,
            sortOrder: 'desc', 
  },

**Comment by AMBudnik** [comment]
Ohh... so you mean the row headers, right? Then, you can use a code like this http://jsfiddle.net/28mf41sc/

**Comment by lycclsltt** [comment]
cool ！

**Comment by suheweiyang** [comment]
> Hi @lycclsltt
> 
> we do not have any external API for `mergedCellInfoCollection`. If you mean `mergedCellsCollection` then you should get to the plugin via `got.getPlugin('mergeCells')` and then call the method. Here is a demo http://jsfiddle.net/z6qd5ase/

i tried this, it's dosen't work in my code , getPlugin is not a function

**Comment by suheweiyang** [comment]
> Thank you ,this problem has resloved. But I want to known how to show the table by order desc?
> for example , the id is 10, 9, 8, 7.....1.

how???

**Comment by AMBudnik** [comment]
All this information can be read from the `afterMergeCells` hook https://jsfiddle.net/AMBudnik/h2x14tuL/
