### ISSUE TITLE
hiddenRows! Pressing issues

### ISSUE THREAD

**Issue by byMoya** [handsontable/handsontable#5217]
### Description

Hi, the data have 17000 rows, but I only need render 3 rows, I use the hiddenRows plugin to hide others,
but When the handsontable init, it will render all rows cause browser crashes, how to fix this? Thanks!

### Your environment
* Handsontable version: 4.0.0
* Browser Name and version: chrome
* Operating System: win10

**Comment by AMBudnik** [comment]
Hi. Have you tried [`maxRows`](https://docs.handsontable.com/pro/4.0.0/Options.html#maxRows)?

**Comment by byMoya** [comment]
the maxRows is not useful, for example. i want to show [400, 600,999] is Array(17000), if I set maxRows: 100,the table is empty

**Comment by AMBudnik** [comment]
It looks like the only ways would be to pass these 3 records to another array used as a `data` of Handsontable. All other techniques are loading the full set and trimming it which will cause performance isues
