### ISSUE TITLE
Coords for the column header

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#5219]
how to get column header x , y position ?

**Comment by AMBudnik** [comment]
Hi @Sundarcj 

Do you mean the viewport coordinates?

**Comment by AMBudnik** [comment]
There is no API for this operation but you can use native JavaScript. Here's a demo http://jsfiddle.net/yo1t4z6h/ and here's a script that I've used https://stackoverflow.com/questions/442404/retrieve-the-position-x-y-of-an-html-element
