### ISSUE TITLE
IME editor doesn't show

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5223]
### Description

IME editors don't work for Internet Explorer 11. The first letter is being cut.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/10757813/42151847-8ab3e7c0-7dde-11e8-8301-33bb9486adcb.png)

Related to: https://github.com/handsontable/handsontable/issues/4662

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 4.0.0
* Browser Name and version: Internet Explorer 11
* Operating System: Windows 10

**Comment by ruzia** [comment]
@AMBudnik Hi, I faced this bug on handsontable pro 6.2.2.
any new update or workaround?

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting but I wasn't able to find a workaround for this issue.

**Comment by AMBudnik** [comment]
As [support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

However, this issue is also replicable on Edge
<img width="153" alt="edge_ver" src="https://user-images.githubusercontent.com/10757813/85018020-c0f3aa00-b16c-11ea-875a-7333c7b60558.png">


**Chrome**
![a](https://user-images.githubusercontent.com/10757813/85018038-c94be500-b16c-11ea-9529-5581b7699487.gif)


**Edge**
![v](https://user-images.githubusercontent.com/10757813/85018033-c6e98b00-b16c-11ea-88f9-94f74a9bf6b9.gif)

The IME is simply not there.

**Comment by aninde** [comment]
This issue is no longer reproducible on current LTS Edge  103.0.1264.77 (Official build) (x86_64) on macOS, but still valid on Windows 10.

**Comment by AMBudnik** [comment]
Hi @ruzia we did some tests, and it seems that this issue is no longer replicable.

I will close it as solved. If there is anything we are missing please leave a comment.
