### ISSUE TITLE
preserve comments in nghandsontable

### ISSUE THREAD

**Issue by jnjagtap** [handsontable/handsontable#5224]
how to  implement -comments should be preserved in output even id data is updated in the table.?

**Comment by AMBudnik** [comment]
Please do not post issues regarding wrappers on the vanilla's Github board. ngHandsontable has its own board at - https://github.com/handsontable/handsontable

ps. I do not fully understand the request. Can you share a demo and scenario that you would like to acheive?

**Comment by AMBudnik** [comment]
I am closing this issue as we have continued the conversation at https://github.com/handsontable/angular-handsontable/issues/106#issuecomment-401809301
