### ISSUE TITLE
Is it possible to navigate the datepicker calendar using the keyboard?

### ISSUE THREAD

**Issue by Parkaboy** [handsontable/handsontable#5226]
Hi, not sure if this is the right place to ask this, using pikaday I am able to navigate through the datepicker calendar without using the mouse but I am not able to do that using handsontable 0.24.3, is there any way to acomplish that?

**Comment by AMBudnik** [comment]
Sorry, but we do not have support for that action. If the datapicker is opened keyboard navigation is still on the table (edited cell is focused).
