### ISSUE TITLE
[0.35.1+] Cannot unmerge cells when there is only one column

### ISSUE THREAD

**Issue by trieuduong1602** [handsontable/handsontable#5227]
### Description
When I define only one column, and merge the top two rows (in example). Then I click on other cells and try to unmerge the merged cell before but "merge cells" option is gray

### Demo
http://jsfiddle.net/khzwt7s8/4/

### Your environment
* Handsontable version: 4.0.0
* Browser Name and version: Chrome 67.0.3396.99
* Operating System: Win 10

**Comment by AMBudnik** [comment]
The bug is a regression of version PRO 1.15.1 (last working http://jsfiddle.net/cez12pwh/1/).

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @trieuduong1602 

I have replicated the issue.

![gif](https://user-images.githubusercontent.com/10757813/42204862-2711ab4c-7ea3-11e8-85ef-67b206d4ca9f.gif)

It looks like we need to merge `A3` as well to get an `unmerge` option in the context menu.

![2gif](https://user-images.githubusercontent.com/10757813/42204932-544ba964-7ea3-11e8-8879-75f602a23cf5.gif)

**Comment by trieuduong1602** [comment]
The problem continues occuring when you click on other cells, you could make that example continue with my link http://jsfiddle.net/khzwt7s8/4/ :D

**Comment by trieuduong1602** [comment]
in merge function, I see you are using this line code:

**Comment by AMBudnik** [comment]
Sounds like a good clue to start with.

**Comment by AMBudnik** [comment]
The main issue with unmerging the cells does not affect v .7.2.1. Updated demo http://jsfiddle.net/14mceupv/
@trieuduong1602 please update and let me know if it works for you as well.
