### ISSUE TITLE
Mouse highlighting without drag in read mode

### ISSUE THREAD

**Issue by abhishek3999** [handsontable/handsontable#5232]
Hi,

Facing issue with mouse click right and left.
In read mode,When I right click of mouse and then clicks left .
And just moving mouse over table.It gets highlighting without any click.

Please find  video link here => http://recordit.co/kw6uXBdnJ6

Regards,
abhishek3999

**Comment by AMBudnik** [comment]
Sorry but I do not understand or can't replicate the same behavior. Are you able to replicate the same one using this demo?

**Comment by abhishek3999** [comment]
Yes. table  highlights on mouse over by
Clicking right and after left.
Same behavior also appearing when I open PDF by click on another tab and
come back to table page.

**Comment by AMBudnik** [comment]
I'm not able to replicate it. It may be a matter of a browser or device. I am testing it on Windows 10 / Chrome 67.

**Comment by AMBudnik** [comment]
Can you share details on your device/OS?

**Comment by abhishek3999** [comment]
Sure.
macOS high sirra 10.13.5
Chrome  67.0
Also checked on Windows 10 chrome latest up to date.
Please try to check with using 🐁.

**Comment by AMBudnik** [comment]
Thank you. I wasn't able to replicate the same behavior on Windows 10 but my colleague did it on Mac.

**Comment by coljung** [comment]
I have actually replicated this as well.

Mac Os 10.12.6
Chrome 67.0

**Comment by AMBudnik** [comment]
We've tested the code in the version 5.0.0 and it works the. The 5.0.0 will be released on the 11th of July.

**Comment by AMBudnik** [comment]
The issue will be fixed within this change https://github.com/handsontable/handsontable/issues/5201

**Comment by abhishek3999** [comment]
Okay.
Thanks

**Comment by AMBudnik** [comment]
Hi @abhishek3999 @coljung please update to 5.0.0 the issue should be gone.
