### ISSUE TITLE
is there only way to sum a row? 

### ISSUE THREAD

**Issue by rianran1993** [handsontable/handsontable#5236]
### Description

I want to sum from A1 to G6 , is there only way to do? 
### Demo

http://jsfiddle.net/kcLer615/8/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @rianran1993 

I think that the best way would be to add a SUM of each column `=SUM(SUM(A1:A6), SUM(B1:B6), SUM(C1:C6), SUM(D1:D6), SUM(E1:E6), SUM(F1:F6), SUM(G1:G6))`

**Comment by rianran1993** [comment]
ok, you mean use ```formulas: true ``` ,right?

**Comment by AMBudnik** [comment]
Exactly

**Comment by rianran1993** [comment]
ok , thanks . I will try
