### ISSUE TITLE
NumericFormat messing up decimals ( after upgrading to v 4.0.0 )

### ISSUE THREAD

**Issue by coljung** [handsontable/handsontable#5237]
### Description
NumericFormat appears broken after upgrading from 1.1.18 to 4.0.0

### Steps to reproduce
1. Apply numeric format
2. Expect percentage / currency to have proper formatting

### Demo
For the demo, the percentage issue can be reproduced, but not the currency one.
Percentages have this pattern: %0, which USED to remove decimals, now they are included. If i use this instead: %0.0, i do get one decimal, and if i an extra 0 to my pattern, then the result is a percent with 2 decimals. Not sure what is happening.
http://jsfiddle.net/j10c4gty/1/

And with currency i have a similar issue. I used to have: pattern: '$0,000', and my numbers would show up exactly without decimals, now not a single decimal is removed.

### Your environment
* Handsontable version: 4.0.0
* Browser Name and version: Chrome ( latest )
* Operating System: OS Sierra

**Comment by AMBudnik** [comment]
The issue seem to be related to this one https://github.com/handsontable/handsontable/issues/5031

Thank you sharing @coljung

**Comment by AMBudnik** [comment]
I think that we will need to add the option ourselves, the [NumbroJS 2.0 provides a lot of changes](http://numbrojs.com/news.html), and there's one connected to the issue

>not precising a mantissa now means to keep them all while it used to mean to trim it off (numbro(123.456).format(0,0) now is 123.234 instead of 123)

**Comment by swistach** [comment]
Hi @coljung.
In Handsontable 4+ `numericFormat.pattern` could be defined as an object.
You can use below configuration:
```
numericFormat: {
  pattern: {
    output: "percent",
    mantissa: 0
  },
  culture: 'de-DE'
}
```

Updated demo: http://jsfiddle.net/vftsc25p/
Detailed information of new formatting you can find here: http://numbrojs.com/format.html

Feel free to reopen this issue if it'll still work incorrectly.

**Comment by AMBudnik** [comment]
Thanks for checking that @swistach !

**Comment by coljung** [comment]
Yes indeed, I changed the setup and it worked.

Thanks
