### ISSUE TITLE
Autocomplete and Load from ajax display issue. 

### ISSUE THREAD

**Issue by clgerhardt** [handsontable/handsontable#5238]
### Description

Following a similar model for the load and save tutorial I want to load in data from django view as a json then call table.loadData(data). Before doing this, I loop through the data and grab the values of "first_name" and store them into an array which can then be used with autocomplete to pass in as the source. When I given the column of first_name the type autocomplete and load the source from the first_name array. The table isn't populated with the data i originally got when i called table.loadData(data). Instead it shows the columns and first_name column with the autocomplete feature but no initial data loaded. 

### Steps to reproduce
I'm working through django which is using views to pass data along to the html page. Other than that, the demo below shows how my code is but can't actually pull data because it isn't connected to my django site. 

### Demo
![before load click](https://user-images.githubusercontent.com/22062735/42341902-95bf225c-8062-11e8-9140-5b39186af0f6.PNG)

![after load click](https://user-images.githubusercontent.com/22062735/42341907-9b9f1df8-8062-11e8-9342-d2814e751b61.PNG)

(here you can see id nor first_name are populated but the autocomplete shows the first_name passed to it through source. )

https://jsfiddle.net/aenLmouw/1/

### Your environment
* Handsontable version: 4.0.0
* Browser Name and version: Google Chrome, Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 64 bit

**Comment by AMBudnik** [comment]
Hi @clgerhardt 

the demo breaks on the `workplanside` element being references at the 9 line. Adding a sample DIV with that ID doesn't allow me to see a table even when the error in the console is gone.

At the first glance (from the description) it looks like you use incorrect keys for the `columns` options. If your data is an object you should add `data` option and define a `key` from your dataset to be placed in line `52`.

**Comment by clgerhardt** [comment]
Hey, @AMBudnik 

I updated the Demo to show exactly what I am talking about. If you could or someone else check it. There is an array on line 5 which a name in, I later set the source for the first name column to that array. However, I also want to have the table itself to be loaded from a external json when the load button is clicked. When i press the load button, the cells of the table are not filled but the autocomplete of the table does work which is shown by the drop down arrow for the first name column. **How would I get these cell to be pre-filled by using table.loadData(json) ? ** It isn't working with autocomplete.

**Comment by AMBudnik** [comment]
Thank you @clgerhardt 

I have asked my colleague to check the demo and help me to solve this case.

**Comment by AMBudnik** [comment]
Hi @clgerhardt 

here is what I got from my colleague
https://jsfiddle.net/h9orznsc/
Does it solve your use case?

**Comment by AMBudnik** [comment]
Hi @clgerhardt 

a source for the autocomplete cell type is always an array, even when you use a function as a source it has to return an array (not an object)
