### ISSUE TITLE
Hiding custom border through setBorders method doesn't work

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#5240]
### Description

Hiding custom border through `setBorders` method doesn't work when cells within range don't contain any border. In that case when we removing the border by passing `{top: false}` object in the second argument it adds the border where shouldn't.

This bug applies to all edges: `top`, `right`, `bottom` and `left`.

### Steps to reproduce

1. Select all cells and trigger `setBorder` using CustomBorder plugin (provided demo do it automatically).
2. In result, cells which didn't have any borders now have a top border.

### Demo

https://jsfiddle.net/4w7nh0us/2/

### Your environment
* Handsontable version: 5.0.0
* Browser Name and version: any
* Operating System: any

**Comment by wojciechczerniak** [comment]
Demo in 5.0.1 RC: https://jsfiddle.net/07rebtqz/ 👍
