### ISSUE TITLE
Jump to top when clicking cell.

### ISSUE THREAD

**Issue by lumnn** [handsontable/handsontable#5242]
### Description
Firefox only (My version is 62 - Developer Edition).
When the active cell is read only, and you click on another cell the whole page jumps up.

### Steps to reproduce
1. Open Firefox
2. Navigate to https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers
3. Right click on ID column. Make it "read-only"
4. Scroll down a bit
5. Click on one of read-only cells and then on any other non read-only cell.

### Demo
![peek 2018-07-09 10-17](https://user-images.githubusercontent.com/2505114/42441950-4efb4b5a-8361-11e8-8a04-a3580f45144d.gif)

### Your environment
* Handsontable version: The one on example page. I assume it's 4.0.0
* Browser Name and version: Firefox Developer Edition 62.
* Operating System: Arch Linux

**Comment by melloware** [comment]
We also have a user reporting this [issue](https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/611#) in Firefox in HT Community version 5.0.1.

**Comment by melloware** [comment]
Our user reported the JS fix in this issue solved his problem: https://github.com/handsontable/handsontable/issues/7

Still a workaround rather than a fix.

**Comment by melloware** [comment]
Looks like it may be fixed in next release: https://github.com/handsontable/handsontable/issues/5220

**Comment by AMBudnik** [comment]
Yes, I also hope that it will solve the issue you've mentioned here. Tomorrow's the release.

**Comment by wojciechczerniak** [comment]
I'm closing this one as a duplicate. #5220 is our working issue, so it's better to keep all the discussion in one place. Thanks for reporting the issue and all the details.
