### ISSUE TITLE
Performance Issue when selecting All checkbox

### ISSUE THREAD

**Issue by Sheetal1289** [handsontable/handsontable#5248]
Hi

I have handsontable with Header checkbox and each row contain checkbox. when user click on header checkbox, all row level checkbox get selected. we are facing performance issue when more than 3000 or 4000 records in handsontable. It takes time checked. It takes more time when your are using filters.
we are using setDataAtRowProp to check the checkbox.

As you mention in our previous thread i try to implement following logic in my code  
http://jsfiddle.net/aoc7yzgw/

but facing issue in that also 
Error message : Uncaught TypeError: Invalid attempt to destructure non iterable instance. Handsontable.full.min.pro.js
Line Number :45

Handsontable Version :- Version: 1.15.0
Release date: 06/12/2017 (built at 06/12/2017 12:54:51)

I am using following code in my javascript file.
var checkAll = function (obj) {

if (!isNaN(obj) || obj === NaN) {

    return obj;
}
if (typeof Handsontable === "undefined") {
    return;
}
var containerHand = document.getElementById('Product_catalog_creation_table');
$(containerHand).unbind();
Handsontable.dom.addEvent(containerHand, 'click', function (event) {
var newState = event.target.checked;
console.log(newState);
var sourceData = hot1.getSourceData();
var rows = sourceData.length;

    for (var row = 0; row < rows; row += 1) {
        sourceData[row]['isActive'] = newState;
    }
    hot1.render();
});
}

**Comment by AMBudnik** [comment]
Hi @Sheetal1289 

please track progress to this issue https://github.com/handsontable/handsontable/issues/4352
it covers a change of cell value (the same action as a checkbox state change).
