### ISSUE TITLE
[2.0.0+] Fixed rows bottom are misaligned

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5249]
### Description

Fixed rows bottom are misaligned

### Steps to reproduce

1. Scroll fast to the end of the grid and back

![fix](https://user-images.githubusercontent.com/10757813/42555853-e364fa46-84e9-11e8-8de8-b0d3f5057c0f.gif)

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 2.0.0+
Seem to work fine on [1.18.1](https://docs.handsontable.com/pro/1.18.1/demo-fixing-bottom.html)
* Browser Name and version: Chrome 67
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Might be related to https://github.com/handsontable/handsontable/issues/5070

**Comment by sagersx** [comment]
I updated my fiddle https://jsfiddle.net/hericus/w5egzkc0/ to show the horizontal scrolling issue.

**Comment by sagersx** [comment]
This fiddle shows how fixedRowsBottom stops working after an alter remove_row.  https://jsfiddle.net/hericus/hew4ur3o/

**Comment by AMBudnik** [comment]
The same issue as https://github.com/handsontable/handsontable/issues/5163
