### ISSUE TITLE
Export csv don't take in consideration the region decimal character

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#5250]
### Description
i try to use the export csv plugin with handsontable for culture fr-FR
the decimal character is ','

### Steps to reproduce

1.click download file csv
2.open file csv with excel
3.the decimal character become '.'

### Demo
http://jsfiddle.net/jeanmarc/aq10ecw4/15/

### Your environment
* Handsontable version: test PRO 4.0.0
* Browser Name and version: google chrome
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 

the plugin export data (not a visual representation of data) and in your dataset there are commas

```
      {car: "Mercedes A 160", year: 2017, price_usd: 7000.12, price_eur: 7000.12},
      {car: "Citroen C4 Coupe", year: 2018, price_usd: 8330.12, price_eur: 8330.12},
      {car: "Audi A4 Avant", year: 2019, price_usd: 33900.12, price_eur: 33900.12},
      {car: "Opel Astra", year: 2020, price_usd: 5000.12, price_eur: 5000.12},
      {car: "BMW 320i Coupe", year: 2021, price_usd: 30500.12, price_eur: 30500.12}
```

The plugin doesn't support an export of formatting and styling yet.
