### ISSUE TITLE
[3.0.0+] cell invalid after copy paste from excel in version PRO 4.0.0

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#5251]
### Description
when i copy cells from excel to handsontable, the cells become invalid, the problem doesn't ocurr in 
handsontable 3.0.0

### Steps to reproduce
![image](https://user-images.githubusercontent.com/11042160/42566029-794f7c8c-8505-11e8-8c09-957fae32fd1c.png)

copy the select cell by ctrl +c and paste

https://docs.handsontable.com/pro/4.0.0/demo-numeric.html

![image](https://user-images.githubusercontent.com/11042160/42566148-edc0c8f0-8505-11e8-9c5a-724a7d80caa6.png)

if i try with 3.0.0, no problem
![image](https://user-images.githubusercontent.com/11042160/42566212-2b9c00e0-8506-11e8-9884-9616cad85cb1.png)

### Your environment
* Handsontable version: TEST PRO 4.0.0
* Browser Name and version: Chrome
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing @jeanmarc78 

I have replicated the same bug. It also works the same in 5.0.0.

We need to edit cell again to mark it valid.

**Comment by alaincao** [comment]
Hello,

just FYI, this is the same thing in community edition v4.0.0 & v5.0.0.  
If you enter the cell's edit mode, the error state disappears.  

I have also noticed that you can replicate the issue much more simply:  
* using any text editor, if you copy/paste only the number (e.g. "1.23") the cell is not in error state
* but if you copy/paste the number **with the trailing end-of-line character** (e.g. "1.23[crlf]"), the cell does show as error.

So it seems simply that when pasting, the trailing space characters are not trimmed.

**Comment by AMBudnik** [comment]
Thank you for your investigation @alaincao

**Comment by AMBudnik** [comment]
**I do not have access to Excel but I was testing it with Google Sheets**

With minimal settings as follows

```js
startRows: 5,
type: "numeric",
```
using version `7.4.0` we do not receive a false validation 
![ok](https://user-images.githubusercontent.com/10757813/74138197-70ce6f00-4bf1-11ea-9252-d4badbfb1c8f.gif)

Demo https://codesandbox.io/s/dropdown-cell-type-source-change-y3xqu

but it also works the same in `7.3.0` 
https://codesandbox.io/s/dropdown-cell-type-source-change-7iz57

...so it works the same in Excel we can close the issue as solved.

**Comment by aninde** [comment]
On Excel, it works the same like in Google SpredSheet.

**Comment by aninde** [comment]
Fixed by 7.3.0.

**Comment by AMBudnik** [comment]
Cool, thanks for checking @aninde !

@jeanmarc78  @alaincao I think that now we can officially close the issue as solved.
