### ISSUE TITLE
update the columnSummary Option  but  hot.updateSettings() doesn't work

### ISSUE THREAD

**Issue by rianran1993** [handsontable/handsontable#5255]
### Description
update the columnSummary Option  but  hot.updateSettings() doesn't work

### Steps to reproduce

1. 
2.
3.

### Demo
http://jsfiddle.net/7vejtb3g/10/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by rianran1993** [comment]
may be the same as [#3597](https://github.com/handsontable/handsontable/issues/3597)

**Comment by AMBudnik** [comment]
Hi @rianran1993 
yes, I think that we should stick to #3597
