### ISSUE TITLE
vue中使用handsontable自定义渲染函数中获取vue的属性

### ISSUE THREAD

**Issue by tangfengyes** [handsontable/handsontable#5257]
### Steps to reproduce

1.data是对象数组，类似[{  1 : {ID:1,NAME:'10',2s:'父对象类'},  2 : {ID:2,NAME:'11',2s:'父对象类ID'}}]。单元格中要显示的内容是对象的某两个属性的拼接，如'1 : 父对象类',  属性是由vue属性指定的，但是无法获取vue对象。
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by tangfengyes** [comment]
@AMBudnik  Thanks.I found a solution:  
//renderer
objectRenderer(instance, td, row, col, prop, value, cellProperties) {
    let vue_instance = instance.rootElement.__vue__.$parent		
}
but  I'm not sure it's always working

**Comment by tangfengyes** [comment]
//renderer
objectRenderer(instance, td, row, col, prop, value, cellProperties) {
    let vue_instance = instance.rootElement.__vue__.$parent		
}

**Comment by AMBudnik** [comment]
If you'd have any issues using Vue we have a special board for it at https://github.com/handsontable/vue-handsontable-official and I highly recommend checking our wrapper for Handsontable in Vue.
