### ISSUE TITLE
How to prevent pop-up keyboard when scrolling in a readonly table

### ISSUE THREAD

**Issue by homura** [handsontable/handsontable#5264]
### Description

Touching or scrolling the readonly table make keyboard pop up on a mobile device

![image](https://user-images.githubusercontent.com/7511174/42817492-d791b2e2-8a00-11e8-8d2e-05081d80c129.png)

### Demo

**code**
https://jsfiddle.net/vj9tsewL/1

### Your environment
* iPhone6s
* iOS 9.3.2

* One Plus 3
* Android 7.1

**Comment by AMBudnik** [comment]
Hm... Are you able to replicate the same behavior using this demo http://jsfiddle.net/jo0zwrgu/1/? Your example doesn't have a `readOnly` state turned on.

I've tested my demo on the same device and it doesn't show the window.

**Comment by homura** [comment]
@AMBudnik 

Sorry, I updated my jsfiddle.
I found flick scroll the table could make the keyboard pop up

![image](https://user-images.githubusercontent.com/7511174/42820628-2c23ba96-8a09-11e8-887a-0b8e41dc14bc.png)

**Comment by AMBudnik** [comment]
I'm sorry but I cannot replicate it. 

I have tried iPhone 6S - iOS 11.4 and iPhone 5s - 11.4
It looks like the older version of iOS may have this problem.

**Comment by fattypanda** [comment]
@AMBudnik  This problem also exists in the android emulator, the version is android 7.0

**Comment by AMBudnik** [comment]
Thanks for checking @fattypanda 
Android v `7` is from 2016 so we should check that out. I am reopening the topic.

**Comment by jeremyslaton** [comment]
@AMBudnik 
I was also having this issue on iOS 11.3, on full version 5.0.1 of handsontable.

I upgraded to iOS 11.4.1 and it is better, but is still happening on checkbox columns.

**Comment by AMBudnik** [comment]
Thank you for sharing the comment and checking it out @jeremyslaton

**Comment by swk777** [comment]
is there any progress？

**Comment by AMBudnik** [comment]
Sorry @swk777 this issue hasn't been scheduled yet.

**Comment by AMBudnik** [comment]
@swk777 I just got an info that this may be fixed in the next release as it related to another issue that is scheduled.

**Comment by swk777** [comment]
@AMBudnik great news, big thx!

**Comment by AMBudnik** [comment]
Hey @swk777 @homura @jeremyslaton @fattypanda 
have you tried the version `7.0.2`? I've tested it on iOs and old Android phone and it works well. I do not get the keyword popping in once I select a cell.

If still does not work for you please let me know and I'll reopen the topic.
