### ISSUE TITLE
Can't determine Excel cell reference id

### ISSUE THREAD

**Issue by GrononS** [handsontable/handsontable#5266]
I searched and searched but I can't find a way to get the excel style cell reference for a selected cell.
What I would like to do it something like hot.getCellReference(0, 0) and get A1 in return. I need this to be able to create formulas on the fly.  

I know this has to be built in somewhere because I can create the formula =sum(A1:A5) and it knows what I am talking about so how do I get this cell reference from the cell itself rather than the column and row numbers?

Thanks!
Brian

**Comment by AMBudnik** [comment]
Hi @GrononS 

can you give me an exact example of what you get and what you'd like to get? Formula cells aren't styled in any particular way so I'm not sure what you mean.

**Comment by GrononS** [comment]
For example, if I execute hot.getSelected() I currently get an array with 4 values such as [0, 4, 2, 5].
I would like the ability to get back something like this [0, 'E', 2, 'F'] so that I can build a formula such as =sum(E1:F3). Note: formulas begin at row 1 so 0 = 1, 2 = 3 when converting from row / col to cell references.

Also, I would like to be able to execute hot.getCellMeta(0, 0) and be able to reference a meta property in the following fashion:
var meta = hot.getCellMeta(0, 0);
// a property named meta.cellReference would be equal to A1 for row 0 cell 0.
// Or you can even break the cell reference into 2 properties such as meta.rowReference = 1 and colReference = 'A' so that I can use A1 to refer to the cell in a formula.

I hope I was able to make this more clear. Thanks for responding :)

**Comment by GrononS** [comment]
I think I may have found something that works for me.

Handsontable.helper.spreadsheetColumnLabel(0) will return 'A' which will work for me. I don't see it documented on handsontable's website.

Is this safe for me to use?

Thanks,
Brian

**Comment by AMBudnik** [comment]
Helpers aren't officially supported, it's more a set of methods that we use internally but if it meets your project requirements that it's great. You'd be able to get this information but after some modifications.
