### ISSUE TITLE
Rendering <select> HTML in cells 

### ISSUE THREAD

**Issue by wangdaodao** [handsontable/handsontable#5267]
### Description
I use Rendering creat select in cell, but it`s not work.This select is unfocus.

![Rendering](http://7xkaad.com1.z0.glb.clouddn.com/select.gif)

### Demo

https://jsfiddle.net/8ffpsqt6/68/

### Your environment
* Handsontable version:2.0.0
* Browser Name and version:Chrome 66.0.3359.181
* Operating System:win 7 64

**Comment by AMBudnik** [comment]
Hi @wangdaodao 

please look at the same subject at https://forum.handsontable.com/t/html-content-loses-focus-in-version-1-15-1/1882

You need to use `beforeOnCellMouseDown` hook
