### ISSUE TITLE
columns配置type:'handsontable'显示bug

### ISSUE THREAD

**Issue by qq986063761** [handsontable/handsontable#5268]
### Description
配置中的columns中的object，type:设置'handsontable'模拟下拉，下拉箭头点击效果bug；

### Steps to reproduce
1.对同一个cell第一次点击下拉箭头，正常；
2.第二次点击下拉箭头，未显示出来，但是实际上已经存在下拉元素了；
3.期望是每一次点击下拉箭头都应该正常显示下拉元素；
4.bug出现时图如下
![image](https://user-images.githubusercontent.com/18366007/42867298-cb1a9a96-8aa1-11e8-864a-f0f7a7aa1c1c.png)

### Demo
https://jsfiddle.net/8ffpsqt6/74/

### Your environment
* Handsontable version: 5.0.0
* Browser Name and version: chrome(67.0.3396.99)
* Operating System: windows10

**Comment by AMBudnik** [comment]
Can you translate the text into English, please? I'm not sure if I understand what Google means while translating your description.

Does it sound similar to this case https://github.com/handsontable/handsontable/issues/5195?

**Comment by qq986063761** [comment]
yes, it is similar;

**Comment by qq986063761** [comment]
thanks,i use type is dropdown,is ok;

**Comment by qq986063761** [comment]
I'm sorry that my English is not very goodo(*￣︶￣*)o

**Comment by AMBudnik** [comment]
No problem :) I'm happy that the issue is solved.
