### ISSUE TITLE
Changing data while in edit results in edit to wrong data

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5270]
### Description
If you change data while in edit mode, the editor doesn't track with the change and can result in editing a different row or even adding a new row.

### Steps to reproduce
1. In the demo below enter editing a cell, make some changes but don't commit them yet
2. Wait 5 seconds or longer, a row will be deleted
3. Commit the cell edit

**Result:** 
Edit is applied to wrong cell.
![](http://g.recordit.co/1gmvpTFFEO.gif)

**Expected Result:** 
Any of the following:
* Cell editor follows the cell as it moves due to row above being deleted
* Commit applies the change to the original entered cell
* If the cell you entered for edit is deleted, the editor is closed without changes

### Demo

http://jsfiddle.net/kv76qcd5/6/

### Your environment
* Handsontable version: 5.0.0
* Browser Name and version: Chrome 67 
* Operating System: MacOS High Sierra

**Comment by AMBudnik** [comment]
Hi @aaronbeall 

I've tested the code somewhere before. Have me mentioned this subject somewhere else?

**Comment by aaronbeall** [comment]
@AMBudnik Yes indeed, I posted [on the forums](https://forum.handsontable.com/t/changing-data-while-in-edit-results-in-edit-to-wrong-data/2189) because I wasn't sure if there was already a solution, and you asked me to log an issue here, it just too me a long time to get around to it. :)

**Comment by AMBudnik** [comment]
Oh yes! Thank you :)

**Comment by AMBudnik** [comment]
It works the same in `7.1.1` http://jsfiddle.net/handsoncode/53naxt8m/ 
![image](https://user-images.githubusercontent.com/10757813/65044841-f9f0bb00-d95d-11e9-8526-f897c30da143.png)


but a bit different in `8.0.0.-rc1` http://jsfiddle.net/handsoncode/ga75nf4m/
![image](https://user-images.githubusercontent.com/10757813/65044716-bd24c400-d95d-11e9-96c4-7be6647a96e7.png)
![image](https://user-images.githubusercontent.com/10757813/65044894-168cf300-d95e-11e9-9d64-915782d150d7.png)


After we approve the new value (click <kbd>ENTER</kbd>) new value is erased.

**Comment by aaronbeall** [comment]
Actually, the 8.0.0 behavior might be fine with me. The bigger problem is applying an edit to the wrong data. Dropping an edit is not as troublesome. The conditions that lead up to this are pretty edgy.

**Comment by wszymanski** [comment]
There are some changes in introduced index mappers that modify the way in which `splice` on the data works. 

The `ObserveChanges` will be deprecated soon and data modifications will be possible only by using the `alter` method. This task won't be done in the scope of the #5751. However, we have some conclusions. Thanks for your contribution @aaronbeall. After reading your comments we would like to: 

- close an editor and don't save data when actually removed row/column contains edited cell,
- an editor should follow the cell otherwise

There is a problem now as `alter` close editor and save changes.

**Comment by aaronbeall** [comment]
> data modifications will be possible only by using the `alter` method.

Can you elaborate or point me to more info on this? It's of interest to me because [the following is a tangent to this issue, sorry -- I've brought this up in other issues but I'm still grappling with the right solution] I have gone down the path of updating source data directly (ie modifying the array passed as `data` then calling `render()` and such) to solve various performance related issues when updating in large data sets. I have since realized this causes all sorts of trouble for HT, because I'm manipulating data outside its normal flow. I *had* looked into using [`alter`](https://handsontable.com/docs/7.1.1/Core.html#alter) early on but it had two major problems:
1. When updating a lot of data (say 1000 cells in a 10,000 cell table) it was incredibly slow, because each update was a separate call to `alter()`. What I seemed to need was a way to perform a bulk change then render once. Updating source data and calling `render()` did the trick. Little did I know the pain I was setting myself up for later...
2. The `alter()` method works on _visual_ data. When sorting and filtering is in play this becomes a problem. It seems that in some cases I really could not reconcile the difference between changes to my source data and the table's data via `alter()`, for example how do I update a piece of data that is currently filtered out? How do I control where a piece of data should be in the _source_ data when the current visual position is different? It seemed impossible.

I can formulate both these two problems into issues, or are they being addressed elsewhere already?
