### ISSUE TITLE
is there any way to calculate in diffrent table

### ISSUE THREAD

**Issue by rianran1993** [handsontable/handsontable#5271]
### Description
I want to calculate the a1  in table A, but its value equal b1 in table B plus c1 in table C. now I save table B and table C in database. I can choose  a1 = b1 + c1. But if I insert row or column in table B.this may cause a1 = b1 + c1 error。so is there any way to solve this?

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
We do not officially support cross-tab formulas. However, you can use `getDataAtCell `method to perform the same operations. Here is an example http://jsfiddle.net/x910e6zm/

**Comment by rianran1993** [comment]
in this example, I will save ```hot3.setDataAtCell(1,1, hot2.getDataAtCell(0,0) + 12);``` in database as a rule. but if I insert a row before row 0 in hot2, the rule will calculate error. because the rule should be ```hot3.setDataAtCell(1,1, hot2.getDataAtCell(1,0) + 12);``` . so is there any way to save the cell as a object which has a uid. I just want to use this uid.

**Comment by AMBudnik** [comment]
You can refer to the cell by using its physical address via [`toPhysicalRow`](https://docs.handsontable.com/pro/5.0.0/Core.html#toPhysicalRow)

**Comment by rianran1993** [comment]
@AMBudnik sorry, I don't know how to use in this  [demo](http://jsfiddle.net/x910e6zm/9/), can you give me a example?

**Comment by AMBudnik** [comment]
It looks like the only way to refer to a value of any cell that has been defined before altering columns and rows would be to create a clone of the data and pass a value straight from the array as the data is being changed by the reference.

**Comment by rianran1993** [comment]
@AMBudnik  I want to set the data sources like this ```[[name1-id1,name2-id2]]```, is there any way to just show name1 in the cell, but the source data is name1-id1. and if cell change to name111, then the source data will be name111-id1. I just want the id from database.

**Comment by AMBudnik** [comment]
You can use the `slice()` method inside a custom renderer. But as your name can have 5 or more chars you'd need to get track on the `-` char.

**Comment by rianran1993** [comment]
okay, I will try, thanks.
