### ISSUE TITLE
Formula doesn't recalculate When IF mentions diving by zero

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5272]
### Description

The formula results in a bug as the if false value returns a bug (we can't divide by zero). If you type there anything else the formula works.

As mentioned on our forum
> an IF() must never evaluate both the true & false results, because for example that could lead to a division by zero error from the route which the IF() will not follow. It must evaluate the condition first, and only then decide which single one of the two result to evaluate.

### Steps to reproduce

1. Uncomment the first line of data to see proper behavior

### Demo

http://jsfiddle.net/y7wp6qvm/

### Your environment
* Handsontable version: 5.0.0
not version related
* Browser Name and version: Chrome 67
* Operating System: Windows 10

Inform [forum](https://forum.handsontable.com/t/cell-value-displays-value/2218/21)

**Comment by AMBudnik** [comment]
We should stick to the origin repo https://github.com/handsontable/formula-parser/issues/57

**Comment by makdv** [comment]
This is still not fixed
