### ISSUE TITLE
Performance issue: splicing source data with observeChanges/columnSorting triggers "observe change" on all data that comes after the spliced index

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5274]
### Description
If you have `observeChanges` enabled (or in my case `columnSorting` enabled, which automatically enables it) and you splice a row from or into the source data, all following row data fires off `afterChange` with `source="ObserveChanges.change"`. Even if you ignore observe changes the Handsontable seems to get locked up processing all the "changes". 

### Steps to reproduce
1. Open the [linked demo](https://jsfiddle.net/8ffpsqt6/106/)
2. Click the "Delete first row" button
![](http://g.recordit.co/jxBpMlm9sM.gif)
3. Notice that the UI hangs for a few seconds and you'll see a lot of "observe change" logs:
![](http://g.recordit.co/dt5C2cvQhO.gif)

This is with a 500 row, 10 col spreadsheet. The problem is worse with more data, in my case 5000 rows, and seems to get worse over time (until you refresh the browser). Chrome memory profile seemed to show an increasing number of objects allocated that didn't all seem to be deallocated:

![image](https://user-images.githubusercontent.com/2973900/42966042-d53b6adc-8b69-11e8-979b-a78611dee453.png)
*Each spike is single deletion of a source data row, very similar to the demo code.*

If you manually turn `observeChanges` off the performance issues completely disappear, even with a massive 5000 row, 100 col data source: https://jsfiddle.net/8ffpsqt6/108/

***Question:** Why is `observeChanges` automatically turned on by `columnSorting`? What effect would manually turning it off have on sorting? Is that a viable workaround here?*

### Demo

https://jsfiddle.net/8ffpsqt6/106/

### Your environment
* Handsontable version: 5.0.0
* Browser Name and version: Chrome 67
* Operating System: MacOS High Sierra

**Comment by aaronbeall** [comment]
After looking into this a bit it seems like its a problem with the [json-patch library](https://github.com/Starcounter-Jack/JSON-Patch) that's being used. Apparently this behavior with array splicing is a [known limitation with no plans to be fixed](https://github.com/Starcounter-Jack/JSON-Patch/issues/204). :( 

So I'd really love to know the answer to 

> Why is `observeChanges` automatically turned on by `columnSorting`? What effect would manually turning it off have on sorting? Is that a viable workaround here?

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting. We've been asked this questions before but I cannot find the topic. I'll ask my colleague to check when `columnSorting` triggers `observeChanges`.

**Comment by AMBudnik** [comment]
It looks like the `observeChanges` is used to perform proper sorting after adding or removing rows. It fires for `afterCreateRow` and `afterRemoveRow` hooks.
