### ISSUE TITLE
render key-value dropdown in autocomplete

### ISSUE THREAD

**Issue by rishabh2712** [handsontable/handsontable#5276]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Sorry but we do not have an option like that yet, @rishabh2712 

Here's a topic to follow https://github.com/handsontable/handsontable/issues/2305
