### ISSUE TITLE
Copy Paste from Excel Multi Rows not working 5.0.0 (Community Edition) 

### ISSUE THREAD

**Issue by polatic** [handsontable/handsontable#5277]
### Description

I create an simple table using latest handsontable community edition : https://cdn.jsdelivr.net/npm/handsontable/dist/handsontable.full.min.js

I've copy multiple rows from excel and paste into new simple table.
Only one records filled with last column contains merging last record + index 1 next record.

This issues occured with version 4.0

I use previous handsontable version 3.0 and it's works well

### Steps to reproduce

1. Create simple table
2. Copy paste multiple lines from Excel 2016

### Demo
No demo

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: Chrome
* Operating System: Mac

**Comment by AMBudnik** [comment]
Could you try to paste the rows into this example https://docs.handsontable.com/pro/5.0.0/demo-scrolling.html?

![gif](https://user-images.githubusercontent.com/10757813/43126679-a5f51de6-8f2d-11e8-9c7b-5c249db83537.gif)

Have you checked the console for errors?

**Comment by AMBudnik** [comment]
I have been testing it on Windows 10 and now on Mac (High Sierra 10.13.6)

![mac](https://user-images.githubusercontent.com/10757813/43138381-ef8175f6-8f4e-11e8-8944-0dba9bdc198f.png)

but it just works fine.

**Comment by polatic** [comment]
@AMBudnik anything i can do to share more detail about the bug cause? My specs OS X EL Capitan, Office 15.14, Chrom 67.0. I will test it on Windows and will let you know about the result.

**Comment by AMBudnik** [comment]
I'm using the same Chrome version on Windows 10 and Mac. Can you save and send the file that you're using as a database?

**Comment by kazhe** [comment]
I can confirm the bug being there in Handsontable 5.0 - and it manifests on Handsontable examples as well. (and the bug is there in both community and Pro versions)
Environment: Mac, latest version of Chrome (68), Excel 15.41 (there is no bug in Excel 16.x).
I added a hook on beforePaste and saw that the data it receives is a one dimensional array instead of a 2d array which should be there (and which you get in Firefox). 
Therefore the main requirement for reproduction = Excel v15.x.

**Comment by AMBudnik** [comment]
We were able to replicate in one device.

**Comment by swistach** [comment]
This issue will be solved within #4931

**Comment by AMBudnik** [comment]
I am happy to inform that this issue is solved in v6.1.0 released yesterday
