### ISSUE TITLE
how to disable native focus function in own editor

### ISSUE THREAD

**Issue by element150** [handsontable/handsontable#5278]
### Description
I am using this editor https://github.com/mydea/handsontable-chosen-editor and when I click on cell which is using this editor it throws error TypeError: this.mainElement.select is not a function. I did some research and this issue came with verison 4.0.0 by adding this part of code:  

// Add an empty space to texarea. It is necessary for safari to enable "copy" command from menu bar.
this.mainElement.value = ' ';
this.mainElement.select();

I don't know how to edit that editor, so I would appriciate help with it.

What I need is prevent this error, but it can happend only if in those cells with custom editor is somehow disabled native focus behavior.

### Steps to reproduce
1. use https://github.com/mydea/handsontable-chosen-editor
2. click on cell using custom editor

### Demo
https://jsfiddle.net/8ffpsqt6/114/

### Your environment
* Handsontable version: 5.0.0
* Browser Name and version: Mozilla Firefox
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
I'm sorry but I can't help you with that. The editor has been written by someone else and it looks like it does not support newer versions of Handsontable. Maybe the author will consider updating the library.

**Comment by AMBudnik** [comment]
If you do not need Safari support you should just comment those lines. You may need to do it after each update (or the Handsontable) but if you do not have any control over the `chosen editor` then that may be the only way. I have asked my colleague to check that and he proposes the same solution.

**Comment by element150** [comment]
Yeah I was thinking about more universal solution, so I dont have to do it every update but thanks.

**Comment by element150** [comment]
And I was like thinking that this part of the editor will overwrite, atleast it seemed logical to me

**ChosenEditor.prototype.focus = function () {};**

but it always call this again and again

**key: 'focus',
    value: function focus() {
      // Add an empty space to texarea. It is necessary for safari to enable "copy" command from menu bar.
      this.mainElement.value = ' ';
      this.mainElement.select();
    }**

**Comment by dtomaszewski** [comment]
@AMBudnik You ask him to comment code in downloaded library ? Any further info about this problem ?

**Comment by AMBudnik** [comment]
Hey @dtomaszewski 

https://github.com/mydea/handsontable-chosen-editor is not part of our product line. We did not create it and we cannot fix it.

**Comment by dtomaszewski** [comment]
@AMBudnik of course but You asked him to comment 

`// Add an empty space to texarea. It is necessary for safari to enable "copy" command from menu bar.
this.mainElement.value = ' ';
this.mainElement.select();`

which is HT code :P 

Maybe it would be useful for @element150 :

I had similar issue here but it was caused that in my private editor TEXTAREA was replaced with content editable DIV element which do not have `select()` method.

**Comment by AMBudnik** [comment]
It's really hard to tell if that still works - that was a year ago and our code changed a lot. 
As it's a custom code the only thing I can propose is a custom development service. Then we'll schedule a code review and maybe we'd be able to propose a change that will allow you to get this working and keep the ability to update Handsontable.

**Comment by dtomaszewski** [comment]
I'm not saying You should fix some random lib cases. All I think You can do is to make Your code more resistant in this place. However it may be wrong that people switches their TEXTAREA to some other things IDK.

**Comment by AMBudnik** [comment]
I will ask our developer to take a look at this on Monday.

**Comment by AMBudnik** [comment]
Here's a feedback from the developer:

> We made a lot of changes in `textEditor `after this issue occurred.
> Including removing of this code 
> `this.mainElement.value = ' '; this.mainElement.select();.`
> 
> But on issue board, @element150 prepared a solution for his problem -mydea/handsontable-chosen-editor#9 (comment).
> And this solution works - https://jsfiddle.net/3fbtqmkz/
