### ISSUE TITLE
Merge className renderer

### ISSUE THREAD

**Issue by Geminii** [handsontable/handsontable#5284]
### Description
Hi everybody, 
I need to add a class on a row to customize background color of one row. But it's not possible to add class into `tr` element. So, i have follow the guide on [https://docs.handsontable.com/5.0.0/Options.html#cells](url). 
The problem, is that i can't merge multiple renderer. I don't know how to fix this.

I need to color the latest row, but this row need to keep the color when i sort on column.  
How to do this ? 
Another question : it's possible to fix the latest row without changing value when sorting ? 

### Demo
http://jsfiddle.net/pak7bt4c/41/

### Your environment
* Handsontable version: 5.0.0 pro
* Browser Name and version: All browsers
* Operating System: All systems

Thanks a lot for your answer. 
Best regards :)

**Comment by AMBudnik** [comment]
Hi @Geminii 

Do you want the last row or a row with content of `Taux d'acceptation..` to remain grey after sorting?

ps. you do not need a renderer to use `%`

```js
        editor: false,
        type: 'numeric',
        className: "extra-bold blue",
        numericFormat: {
            pattern: '0 %',
        },
```

should work faster than
```js
              editor: false,
              type: 'numeric',
              renderer: function colorPercentage(hotInstance, TD, row, col, prop, value, cellProperties) {
                TD.className = "extra-bold blue";
                TD.innerHTML = value + ' %';
              }
```

however then `100` would be `10000 %` not `100 %`, as percentage is counted from `1` being `100 %` so you'd need to change data.

The same situation is for other columns.

```js
 {
              editor: false,
              type: 'numeric',
              renderer: function colorNumbeBlue(hotInstance, TD, row, col, prop, value, cellProperties) {
                TD.className = "blue pointer";
                TD.innerHTML = value;
              }
},

```
is nothing more than

```js
{
              editor: false,
              type: 'numeric',
              className: "blue pointer";
}
```

**Comment by Geminii** [comment]
Hi @AMBudnik 
Thanks for the tip about className :) I need a renderer because i apply a function into the value. But i simplify in this example. 

I want to have a row with content of `Taux d'acceptation..` to remain grey before and after sorting. So when i will sort on a column, the row will stay grey. But at the moment, only grey style are apply. I need in this row to apply column rendering too. 

Thanks a lot for your help :)
ps : i update the jsfiddle.

**Comment by AMBudnik** [comment]
With a help of my colleague I've managed to solve the case - http://jsfiddle.net/rboktnxy/

**Comment by Geminii** [comment]
Oh it works ! 
Ok i saw how you did it! 
So i need to add a condition into cells. This label can be change but i will success to do it. 

Thanks again a lot Aleksandra for your help and at your colleague :)
Regards,
