### ISSUE TITLE
Bug: Formulas for flat data do not parse on dynamic changes to the dataset

### ISSUE THREAD

**Issue by GrononS** [handsontable/handsontable#5285]
Regarding Handsontable 5 Pro:

Formulas will parse correctly for the initial load of table data but changes to the data set after the initial load will not correctly parse the formula.

[Example: Click the button to dynamically add a formula to the table](http://jsfiddle.net/tgqL4m0o/1/)

As you can see in the example, clicking the button adds the formula but instead of showing the computed value it will show the formula.

Also, validating the cell produces a result that indicates the cell value is not valid.
`hot.validateCell("=B1", hot.getCellMeta(0, 0), function(a, b, c){console.debug(a)}, null);`

Is there a way I can force the table to recognize the new value as a formula and force it to parse?
I need this method of updating the data to work because adding formulas via _setDataAtCell_ causes massive rendering delays that makes the table impossible to work with.

**Comment by AMBudnik** [comment]
Thank you for sharing the demo @GrononS 

I have replicated the issue

**Comment by rbarato** [comment]
@GrononS I think your issue can be solved with a recalculateFull after change, follows your fiddle updated: http://jsfiddle.net/tgqL4m0o/8/

@AMBudnik regarding the related ticket I opened last week (MIN/MAX bug after cell change) we were able to work it around by adding a custom formula to override the default min/max and doing the necessary parseFloat to the arguments. Here's how we accomplished it: https://jsfiddle.net/rbarato/ofLry1qg/4/

There are some adaptations but I tried to explain in the fiddle.

Regards

**Comment by AMBudnik** [comment]
Thank you for sharing the demo with me @GrononS Appreciated.

**Comment by wojciechczerniak** [comment]
If you modify `data` object outside of Handsontable API you're responsible for updating meta.

Handsontable has an API for changing data: http://jsfiddle.net/gr2xwq89/ and it will recalculate formula on change. Not a bug.
