### ISSUE TITLE
unable to run handsontable

### ISSUE THREAD

**Issue by prem0909** [handsontable/handsontable#5286]
### Description

Hi, I am trying to show a spreadsheet using handsontable
I am running the server using flask, and am getting an error. I'd appreciate it veery much if you can help. I am stuck on this for a week!

I started the run by typing 
python run.py

I get the error message (in CLI)
127.0.0.1 -- [26/Jul/2018 20:57:20] "GET /node_modules/handsontable/dist/handsontable.full.min.js HTTP/1.1" 404 -
127.0.0.1 -- [26/Jul/2018 20:57:20] "GET /node_modules/handsontable/dist/handsontable.full.min.css HTTP/1.1" 404 -

### Steps to reproduce

I have the following directory structure:

.\
   run.py
   node_modules\
   app\
      __init__.py
      views.py
      templates\
	 view5.html
==============================================
The file contents are as follows:
run.py
======
from app import app
app.run(debug=True)

app\__init__.py
===============
from flask import render_template
from flask import Flask

app = Flask(__name__)
from app import views

app\views.py
============
from flask import *
import pandas as pd
from app import app

@app.route("/")
def view_pl():
    return render_template('view5.html')

app\templates\view5.html
========================
<!DOCTYPE html>
<html>
<title>v5</title>

<script src="node_modules/handsontable/dist/handsontable.full.min.js"></script>
<link href ="node_modules/handsontable/dist/handsontable.full.min.css" rel="stylesheet" media="screen">
<div id="example"></div>
  <script type="text/javascript">
  var data1 = [
    ['', 'Tesla', 'Nissan', 'Toyota', 'Honda', 'Mazda', 'Ford'],
    ['2017', 10, 11, 12, 13, 15, 16],
    ['2018', 10, 11, 12, 13, 15, 16],
    ['2019', 10, 11, 12, 13, 15, 16],
    ['2020', 10, 11, 12, 13, 15, 16],
    ['2021', 10, 11, 12, 13, 15, 16]
  ],
  container1 = document.getElementById('example1'),
  settings1 = {
    data: data1
  },
  hot1;
hot1 = new Handsontable(container1, settings1);
</script>
</html>
<style>var

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 5.0.0
* Browser Name and version:67.0.3396.99 (Official Build) (64-bit)
* Operating System:Windows 7 Home premium service pack 1, 64 bit

**Comment by wojciechczerniak** [comment]
Hi @prem0909,

The error message suggests that your server blocks access to Handsontable files. Maybe node_modules folder is not in the public path. It's not a problem with Handsontable though and we can't help with server side code. Python and Flask are not technologies we're familiar with. Sorry.
