### ISSUE TITLE
fixedColumnsLeft not working correctly with collapsibleColumns

### ISSUE THREAD

**Issue by david-crouch** [handsontable/handsontable#5290]
### Description
Columns that are frozen with fixedColumnsLeft are not able to be made collapsible.

### Steps to reproduce
1. Configure nested headers and columns to be collapsible
2. Configure fixedColumnsLeft to include a group of collapsible columns
3. Columns that are frozen are not collapsible. Any collapsible columns to the right of the frozen columns will collapse/expand correctly.

### Demo
https://jsfiddle.net/8ffpsqt6/192/
In the above demo, the collapsible columns for C are working, but those for B are not present.

### Your environment
* Handsontable version: 5.0.0.0
* Browser Name and version:  Edge, Chrome (latest)
* Operating System: Windows 10 Pro

**Comment by AMBudnik** [comment]
Thank you for sharing @david-crouch 

you're right. The collapsing feature is gone.
Updated demo https://jsfiddle.net/2aufk381/

**Comment by benliq** [comment]
Any fix for this issue? Thanks

**Comment by AMBudnik** [comment]
I do not see any 'easy' workaround. Changing the z-index does not help.

**Comment by AMBudnik** [comment]
I think that this might be a matter of a hidden element as `C` column displays and works properly.

Updated to `7.1.1` https://jsfiddle.net/vr6qsoaj/

**Comment by wojciechczerniak** [comment]
This is done on purpose in our code: 

```ts
column >= this.hot.getSettings().fixedColumnsLeft
```

Here:

https://github.com/handsontable/handsontable/blob/98878a6bb6edbed065b7961bc97d4b799e908503/src/plugins/collapsibleColumns/collapsibleColumns.js#L469-L477

@AMBudnik I wouldn't call it a bug. This was done on purpose, either because it would break otherwise or it was not on the spec from the start. Maybe it was left for the second stage or never intended to work that way.

**Comment by AMBudnik** [comment]
Updated demo https://jsfiddle.net/0bsqmxdg/ (`8.0.0-beta1`)

![Zrzut ekranu 2020-01-31 o 10 40 45](https://user-images.githubusercontent.com/10757813/73528968-27726880-4416-11ea-9d05-1c8c29d47a51.png)

**Comment by vargulio** [comment]
Hi @AMBudnik 
I didn't catch if this is resolved in version 8+?

**Comment by AMBudnik** [comment]
v8.2.0 https://jsfiddle.net/handsoncode/ey2kpdqb/

@vargulio this topic is still opened and hasn't been qualified for the next milestone
I will make sure to mention you (@) as soon as it changes.

**Comment by AMBudnik** [comment]
Thank you again for sharing this idea!

I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
