### ISSUE TITLE
Applying conditional style through cells method

### ISSUE THREAD

**Issue by nethore** [handsontable/handsontable#5296]
Hi,

I'm using Handsontable cells method to apply specific settings (like a renderer, a number format, ...) from an array that match my data array.

Is it possible to define a cell style (bg-color, color, ...) directly from the cells method without passing through a renderer, because I must be able to assign an unlimited number of colors.

For exemple something like that would be awesome:
```
cells: function (row, col, prop) {
    if (result.settings[row][col].bgColor)
         // For exemple result.settings[row][col].bgColor = '#47d0ae';
         cellProperties.style.backgroundColor = result.settings[row][col].bgColor;
    return CellProperties;
}
```
Thanks a lot in advance,

Nikolas

### Your environment
* Handsontable version: 5.0.0 with Angular Wrapper
* Browser Name and version: Chrome
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Hi @nethore 

Have you considered to attach classes? It works faster and it isn't overwritten by editing or rendering (like it happens for styles).

Then the syntax is

`cellProperties.className = 'name-of-a-class'`

ps. you're missing a `cellProperties` declaration in the following `cells` implementation. It should be

`var cellProperties = {}`
