### ISSUE TITLE
Dropdown values for new empty rows created by using minSpareRows

### ISSUE THREAD

**Issue by Prahadeesh92** [handsontable/handsontable#5297]
### Description
I want to know to how to give dropdown values for new empty rows which created by using minSpareRows.

**Comment by wojciechczerniak** [comment]
I'm closing this issue as a duplicate:

https://github.com/handsontable/handsontable-pro/issues/100 
https://github.com/handsontable/angular-handsontable/issues/113 
https://github.com/handsontable/ngHandsontable/issues/246 
https://github.com/handsontable/handsontable/issues/5297
