### ISSUE TITLE
Printing custom borders with bootstrap css

### ISSUE THREAD

**Issue by lucamaral** [handsontable/handsontable#5298]
### Description
When users is printing the page, custom borders css was overwrited by bootstrap print css.
I made some changes to border.js source. I added "!important" to borders background style.

Before:
```
createBorders(settings) {
  ...
  style.backgroundColor = (this.settings[position] && this.settings[position].color) ? this.settings[position].color : settings.border.color;
```

After:
```
createBorders(settings) {
  ...
  let backgroundColor = (this.settings[position] && this.settings[position].color) ? this.settings[position].color : settings.border.color;
  style.setProperty("background", backgroundColor, "important")
```

### Demo
http://jsfiddle.net/nufpehd9/1/

My question is, What do you think about use "!important" to overwrite bootstrap print css?

**Comment by AMBudnik** [comment]
Hi @lucamaral 

Thanks for checking that and providing a solution.

We use a lot of `important!` but we're not proud of it, to be honest. I'll ask the team about their opinion.

**Comment by aninde** [comment]
This issue will be fixed on the new version with SVG borders.
Tested on Firefox, Chrome, Brave, Opera / Mac OS,
IE, Edge, Edge Dev / Windows 10.

@lucamaral we are currently testing a new way of drawing `customBorders` based on SVG, not a div.
After testing, we will merge this option to the new version 8.0.0-beta. The new version will contain many breaking changes, we will describe them in detail in the migration guide and on the blog.

**Comment by swistach** [comment]
Hi @lucamaral,
Thank you for your involvement to improve Handsontable!
I close this issue because it will be a part of the scope of #6467.
Please track work progress there.
