### ISSUE TITLE
[0.34.5+] Paste of row does not work after multiple clicks on target row header cell

### ISSUE THREAD

**Issue by flohil** [handsontable/handsontable#5300]
### Description

When I copy a whole row and try to insert its contents into another row, the insertion only works if I click on the second row's header cell one single time. If I click on the second row's header cell multiple times before inserting, the mouse pointer switches to "draggable" mode and the insert event does not seem to be fired.

**Expected Result: **
The contents of the first row are inserted into the second row.

**Actual Result: **
The contents of the first row are not inserted into the second row. The insert event does not seem to be triggered when the mouse pointer for a row is in "draggable" state

### Steps to reproduce

1. Open the Handsontable Demo page: https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers
2. Select the whole first row (with the European flag) by clicking on its left table header cell (1)
3. Press Ctrl + C to copy the row
4. Click on the left table header cell (2) of the second row (with the Japanese flag)
5. Click on the left table header cell (2) of the second row again
6. Press Ctrl + V to insert the contents of the first row into the second row

### Your environment
* Handsontable version: Latest? -> the one used on the Handson Table Demo Page
* Browser Name and version: Google Chrome Version 60.0.3112.78
* Operating System: Ubuntu 16.04

**Comment by swistach** [comment]
This issue will be solved within #4931

**Comment by AMBudnik** [comment]
Thank you for sharing :) Please update to 6.1.0 where this issue should be fixed entirely
