### ISSUE TITLE
When click  CMD/CTRL+F or  CMD/CTRL+D multiselect mode is activate

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5302]
### Steps to reproduce
1. https://handsontable.com/examples?headers
2. click `CMD + F` or `CTRL + F`
3. clicking or dragging across cells
4. multiselect mode is activate

### Your environment
* Handsontable version: 5.0.0
* Browser Name and version: Chrome 68.0
* Operating System: macOS Sierra 10.12.6

**Comment by wojciechczerniak** [comment]
Demo in 5.0.1 RC: http://jsfiddle.net/9t16y4qm/ 👍
