### ISSUE TITLE
getSourceDataAtCell returns same as getDataAtCell

### ISSUE THREAD

**Issue by craigbenstock** [handsontable/handsontable#5318]
### Description

v5.0
When implementing data and columns as per your atricle:
https://docs.handsontable.com/5.0.0/tutorial-data-sources.html 
(Object data source with custom data schema)

getSourceDataAtCell() returns the cell value, which is the same result as getDataAtCell().

I would expect it to return the original data object.

### Steps to reproduce
I have data in the shape of array of objects e.g.
  ...
    data: [
      { "example": { "displayname": "john", "servername": "johnsmith" } },
      ...
    ]

I have columns set up to map with displayname, e.g.
  ...
    columns: [
      { "data": "example.displayname", "readOnly": true },
      ...
    ]

I am using a custom renderer, and on click I want to get & use the 'servername' to return to the server.

When I use instance.getData() I get the array of table values returned as expected.
When I use instance.getSourceData() I get my original data array returned as expected.
When I use instance.getDataAtCell(0,0) I get the table cell value as expected.

HOWEVER, when I use instance.getSourceDataAtCell(0,0) I get ONLY THE CELL VALUE returned.

This to me is not as expected.  Should return { "displayname": "john", "servername": "johnsmith" }, and not 'john'

For now I can attempt a workaround by using getSourceData() and creating my own method to find the related servername value.

However, this looks like a bug to me.

### Demo
none

### Your environment
* Handsontable version: 5.0
* Browser Name and version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @craigbenstock 

to understand it can I ask you to create a demo with above implementation and exactly point which value should be changed and how?

**Comment by craigbenstock** [comment]
Here is a fiddle example:

https://jsfiddle.net/cab79/Lb281fLx/84/

**Comment by AMBudnik** [comment]
Thank you, great and clear demo!

You can use `hot4.getDataAtRowProp(0, 'name');` to get the full object.

**Comment by AMBudnik** [comment]
I just got a tip from one of our developers that you can also use 

`hot4.getSourceDataAtRow(0)[‘name’];`

as you may not get the `key` from the `datamap` if you do not define `dataSchema` without the `name`

**Comment by craigbenstock** [comment]
Thank you

**Comment by AMBudnik** [comment]
You're welcome @craigbenstock  I'm happy to help 👍

**Comment by craigbenstock** [comment]
Can i re-open this please.
The following getSourceData functions still do not return the expected data:

getSourceDataAtCol()
getSourceDataAtCell()

They only retrun the vales and not the source data.

The fiddle that I posted above in 2018 is still a relevant example ( https://jsfiddle.net/cab79/Lb281fLx/84/ ).

The 'solution' in this thread is proving impracticle for my needs and frankly it's not really a solution.

These sourceData functions should return sourceData and they don't.

**Comment by wojciechczerniak** [comment]
![Screenshot 2021-03-05 at 12 22 08](https://user-images.githubusercontent.com/4718998/110109222-6c04cc00-7dad-11eb-842f-c7a701e48643.png)

`{"first":"Ted","last":"Right"}` is not the source data for column `1`
`name.first` is, works correctly. Am I missing something?

**Comment by craigbenstock** [comment]
Sorry wojciechczerniak but I disagree.
What would be the point of getSourceDataAtCell(0, 1) if it returns the same result as getDataAtCell(0, 1)?
It should return the source object, not the data value.

**Comment by AMBudnik** [comment]
The `hot4.getSourceDataAtCol(1)` returns `["Ted"]`, so `hot4.getSourceDataAtCell(0, 1)` cannot return anything more complex (as the `{"first":"Ted","last":"Right"}` object).

Correct me if I'm wrong @wojciechczerniak but wouldn't we need something like this them 

 `var getSourceDataAtCell = JSON.parse(copy)[0]['name'];`

when copy is a `let copy = JSON.stringify(nestedObjects)`

Demo: https://jsfiddle.net/3g5jvbea/1/
![image](https://user-images.githubusercontent.com/10757813/110111560-d2d7b480-7db0-11eb-8a61-51267610e505.png)

**Comment by wojciechczerniak** [comment]
@craigbenstock It returns the source object (a primitive value in this case) that is set for the column in `columns`.

You have set column `1` to have `name.first` as its content. `getDataAtCell` will return "Ted". OK, no questions here.

Problem is that when you call `getSourceDataAtCell` you expect the whole object `{ first, last }` that is stored as `name` property on the source data row. What you expect is a parent of the cell content and this is a wrong assumption. Source data in the cell was set to `name.first`, not the whole `name` object.

Yes, in this case both methods should display exactly the same output*. 

---

So, when they will differ? When any plugin or developer will modify the data flow:

```ts
modifyData(row, column, valueHolder) {
  valueHolder.value = valueHolder.value + ' 2';
}
```

https://jsfiddle.net/hkv3z9wp/

To put it more in context, if you would go with key-value approach, that the cell source data is an object of some kind: `price: { value: 12.43, currency: "USD",  ... }` and use for `getDataAtCell` only the value (sorting etc) the `getSourceDataAtCell` would be a reference to that object with all it's properties.

Similar example: https://jsfiddle.net/s7v6dtk5/

---

Everything is fine with the logic here.

`getSourceData` is simply referenced to the `data` object. 
`getSourceDataAtRow` will reference `data[row]`, the whole object at the row index. 
`getSourceDataAtCell` is mapped to `data[row][property]` OR deeper. In your case `data[row]["name"]["first"]`.

---


*Although, they may be different references. I will skip that for simplicity

**Comment by craigbenstock** [comment]
Hi @wojciechczerniak , thanks for the detailed reply.  I'll have to consider my implementation differently.
