### ISSUE TITLE
afterChange hook triggered more than once

### ISSUE THREAD

**Issue by tangfengyes** [handsontable/handsontable#5319]
a cell has custom validator,when copypaste,afterChange will trigger twice,once is edit,and anthor is validator,bug I only want once

**Comment by AMBudnik** [comment]
Hi @tangfengyes 

thank you for sharing. I believe that this subject is related to the one that I've mentioned at https://github.com/handsontable/handsontable/issues/5204

**Comment by AMBudnik** [comment]
Hi @tangfengyes 

Issue https://github.com/handsontable/handsontable/issues/5204 is closed as solved. Could you please let me know if the issue still persistent for you?
