### ISSUE TITLE
removerow 'button' on right side of table?

### ISSUE THREAD

**Issue by scottfrenz** [handsontable/handsontable#532]
Hello. Thanks for such an awesome jquery widget!

I have the removerow extension, and it's working great, but I was wondering if there's a way to put the remove button on the right side of the table instead of the left?

I've been hacking at the removeRow.js file for awhile, and admittedly, my DOM/jquery skills are still lacking.  I can't seem to figure it out.

Thanks!

-Scott

**Comment by kotmatpockuh** [comment]
@richardbatty is it possible to display X in your code only when cell is selected in the row?
