### ISSUE TITLE
After the cell changes color, download, can the handsontable keep the color? Or upload to the server and keep the color the next time the page loads.

### ISSUE THREAD

**Issue by mofengfs** [handsontable/handsontable#5320]

**Comment by AMBudnik** [comment]
The metadata settings are usually kept in the `cells` method via classes.  It depends on you if you want to store them and get it back after server updates. Can you share more precise scenario on how it should change?

**Comment by AMBudnik** [comment]
I am closing the issue as there's no reply for more than a week. If you're still looking for an answer please post a comment
