### ISSUE TITLE
Custom editor SetValue() return value is ignored in cases where the data array holds an object.

### ISSUE THREAD

**Issue by astegmaier** [handsontable/handsontable#5323]
### Description
Similar to @pmunin in #4414, am trying to use handsontable to render an array-of-arrays with custom objects as cell values.

In this context, SetValue() of a custom editor function doesn't work properly. According to the documentation, the value that you return from this function should be set as the value of a cell. But this doesn't work (i.e. the return value is simply ignored) if the existing value of the cell is an object.

### Repro Steps / Demo

See this jsfiddle: https://codepen.io/astegmaier/pen/NBorrp

In it, I've written a custom editor that should override all user input with the string "Test getValue() return value." If you edit the cells that have simple strings or numbers in them, this works. But if you edit the cells that have objects in them, it doesn't.

@OnderBoz identified the root cause to #4414, and after debugging I think it's the same thing that's causing this issue: [these lines](https://github.com/handsontable/handsontable/blob/95320cffa2df92143fbcfc14fb1c7fbca6147de3/src/core.js#L757-L774) in `populateFromArray`

Would it be safe to remove these checks? I don't understand what good they are doing?

### Your environment
* Handsontable version: 5.0
* Browser Name and version: chrome
* Operating System: windows

**Comment by AMBudnik** [comment]
Hi @astegmaier 
I am sorry to say that but Handsontable does not suppose to support an object as a data source for a single cell. The current data structure is not officially supported and we haven't tested the features and functionalities using this type of data.
