### ISSUE TITLE
Typo in handsontable.d.ts

### ISSUE THREAD

**Issue by astegmaier** [handsontable/handsontable#5324]
[This line](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L624) of `handsontable.d.ts` defines `AutoColumnSize.sampleGenerator` (singular). If you call this in code you will get `undefined`.

According to the [documentation](https://gist.github.com/budnix/146d2d269cec5b60a8b5467d6addae86#AutoColumnSize+samplesGenerator), this should be `AutoColumnSize.samplesGenerator` (plural). Calling this in code will work.

**Comment by AMBudnik** [comment]
Thank you for spotting that. You're right. There's a typo.

**Comment by swistach** [comment]
I've merged your PR. Thank you again for your involvement!
