### ISSUE TITLE
handsontable render make 

### ISSUE THREAD

**Issue by xiaochulailai** [handsontable/handsontable#5327]
### Description

![image](https://user-images.githubusercontent.com/16815220/44025747-83b1bc16-9f23-11e8-99ba-1f9aeff9a674.png)
![image](https://user-images.githubusercontent.com/16815220/44025916-002337ac-9f24-11e8-89c0-a79d735c61e1.png)

### Steps to reproduce

1.cell:[{row: 9, col: 3, className: "htRight",
                    type: 'numeric',
                    numericFormat: {
                        pattern: '0.00'
                    },
                    render: blueRender
                }]
var blueRender = function (instance, td, row, col, prop, value, cellProperties) {
        //注意 渲染器并不是只执行一次， 比如滚动条滚动到行时 也会触发，所以不要写太复杂逻辑
        Handsontable.renderers.TextRenderer.apply(this, arguments);
        td.style.background = '#99CCFF';
    }
2. if I set render, the 'data' is 2.00, cell display 2, no 2.00 . I delete the render, it's 2.00, I think the render make the numericFormat no work.
3. my English is so sorry, but i think u can understand ,may be ... hahahaha

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 5.0
* Browser Name and version: chrome 
* Operating System: win10

**Comment by AMBudnik** [comment]
Hi @xiaochulailai 

You use a `numeric` cell type with a formatting but then you rewrite it with a `TextRenderer`

`Handsontable.renderers.TextRenderer.apply(this, arguments);`

**Comment by xiaochulailai** [comment]
thank you so so so so much~
I use the NumericRenderer , it's ok now~

**Comment by xyd113** [comment]
arguments是什么呀，我arguments报错'arguments' is not allowed in class field initializer

**Comment by wojciechczerniak** [comment]
`arguments` is internal javascript variable inside a function that represents all arguments as an array. If you're using strict mode, `arguments` variable has limitations, you should use spread operator or list all arguments by name.
