### ISSUE TITLE
When we change data on collapsed rows we get an error

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5328]
### Description

When we change dataset on collapsed rows we get an error

`Uncaught TypeError: Cannot read property '__children' of undefined`

### Steps to reproduce

1. Open the console
2. Collapse all the rows
3. Click the <kbd>Change Data</kbd> button. It calls `updateSettings` and adds a new dataset with a fewer children per a parent row.

### Demo

https://codepen.io/nalandial/pen/RBqbOa?editors=0010

### Your environment
* Handsontable version: Handsontable PRO 5.0.0
* Browser Name and version: Chrome 67
* Operating System: Windows 10

_Inform Gr # 17081_

**Comment by AMBudnik** [comment]
duplicate of https://github.com/handsontable/handsontable/issues/3914

**Comment by AMBudnik** [comment]
Fixed with 8.0.0-beta1

**Comment by AMBudnik** [comment]
8.0.0.-beta1 https://jsfiddle.net/yzs83bru/3/ (**solved**)
8.0.0.-beta2-rev1 https://jsfiddle.net/yzs83bru/4/ (broken)
8.0.0.-beta2-rev6 https://jsfiddle.net/yzs83bru/2/ (still broken)

**Comment by AMBudnik** [comment]
**Solved** in 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/1Lmhq63a/

**Comment by aninde** [comment]
Still works with 8.0.0-beta2-rev18 https://jsfiddle.net/aninde/n8ps549e/

**Comment by aninde** [comment]
Remains solved with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/8jgk4f7q/1/.

**Comment by AMBudnik** [comment]
Issue solved in Handsontable v 8.0.0.


CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
