### ISSUE TITLE
[4.0.0+] Cursor moves to another line on cell edit - Excel copy/paste

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5330]
### Description

When we copy some data from Excel to Handsontable and edit the cell the editor shifts to another line.

### Steps to reproduce

1. Copy a single cell from Excel to Handsontable 
2. Edit the same cell

**Result**:
![gif-bug](https://user-images.githubusercontent.com/10757813/44033812-cdd731da-9f0b-11e8-9d50-9e65fd6676ff.gif)

**Expected**:
![gif-ok](https://user-images.githubusercontent.com/10757813/44034092-8f4fb9cc-9f0c-11e8-9c7b-44e0e48bafd0.gif)

_Inform Gr #17108_

### Demo

https://docs.handsontable.com/pro/4.0.0/demo-scrolling.html

### Your environment
* Handsontable version: [4.0.0.](https://docs.handsontable.com/pro/4.0.0/demo-scrolling.html)
Last working [3.0.0](https://docs.handsontable.com/pro/3.0.0/demo-scrolling.html)
* Browser Name and version: Chrome 67
* Operating System: Windows 10

**Comment by Ahuahuachi** [comment]
This is also causing problems when pasting more than one cell.

**Comment by AMBudnik** [comment]
Thank you for sharing that @Ahuahuachi 
Hopefully, we will be able to fix the issue in the next (September's) release.

**Comment by AMBudnik** [comment]
Hi @Ahuahuachi 

I am happy to inform that this issue should be gone after updating to `6.1.0`

**Comment by Ahuahuachi** [comment]
Thanks @AMBudnik!
