### ISSUE TITLE
The official demo can only show 22 pieces of data？

### ISSUE THREAD

**Issue by WGL878420** [handsontable/handsontable#5334]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @WGL878420 

Handsontable CE or PRO doesn't limit the number of rows or columns.

Where did you find a demo that does that?
