### ISSUE TITLE
Is handsontable support like excel which having multiple sheets ?

### ISSUE THREAD

**Issue by SaibabaGajulawar** [handsontable/handsontable#5335]
I just want to simulate Excel sheet with handsontable . if any example please let us know for my reference , thank in advance ?

**Comment by AMBudnik** [comment]
Currently, Bootstrap tabs are the best in simulating multiple sheets http://jsfiddle.net/x910e6zm/ but we're working on our own solution (just need more time to test and repair)

**Comment by jacksontong** [comment]
@AMBudnik has this been implemented?

**Comment by AMBudnik** [comment]
Hi @jacksontong could you tell me what are your exact requirements for multiple sheets at support@handsontable.com? We can discuss some options.
