### ISSUE TITLE
React Handsontable.destory() or setting data leads to DetachedDom tree.

### ISSUE THREAD

**Issue by kevinjiaxu96** [handsontable/handsontable#5337]
### Description
Calling Handsontable.destory() or just setting the data for HotTable causes detachedDom in chrome-dev-tool memory.

Note: Only rendering Handsontable and a button to change data and delete table.

### Steps to reproduce
1. Fill Handsontable with data.
2. Call destory on hotInstance or change data.
3. Take heap snapshot.

### Screenshot
<img width="220" alt="untitled" src="https://user-images.githubusercontent.com/26973140/44124388-d7e1d3f2-9fe1-11e8-9163-c6f20af4bed8.png">

<img width="282" alt="untitled" src="https://user-images.githubusercontent.com/26973140/44124630-0abb10a8-9fe3-11e8-92bd-7742393ae43e.png">

### Environment
* Handsontable version: 5.0.0
* @handsontable/react: 1.0.0
* Electron: 2.0.7
* Operating System: MacOS
* React: 16.4.2

**Comment by AMBudnik** [comment]
Can you share a demo that will help us to replicate the issue?

**Comment by AMBudnik** [comment]
I am closing the issue report as there is no feedback for a week. Please add a demo @kevinjiaxu96 if you can
