### ISSUE TITLE
Fixing bottom rows scrolling

### ISSUE THREAD

**Issue by robivinh** [handsontable/handsontable#5339]
### Description
Sometime it not scrolling left and right.

### Steps to reproduce

1. Scroll down
2. Scroll left

![image](https://user-images.githubusercontent.com/7790293/44131523-cf4da7c4-a07d-11e8-9d8e-96f012807db7.png)

### Demo
https://docs.handsontable.com/pro/5.0.0/demo-fixing-bottom.html

### Your environment
* Handsontable version: 5.0.0
* Browser Name and version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 10 Pro Version 10.0.17134 Build 17134

**Comment by AMBudnik** [comment]
Hi @robivinh 

this issue has been presented at https://github.com/handsontable/handsontable/issues/5163 and will be fixed in the new version.
