### ISSUE TITLE
Autocomplete: Attach related data to autocomplete choices

### ISSUE THREAD

**Issue by thom801** [handsontable/handsontable#535]
I am running into an issue with autocomplete at the moment. I'm wondering if something is already in place to solve my problem, otherwise it may be a good feature to add in. What I need is something similar the following:

```javascript
columns: [
  {
    data: "user"
    source: [
      { user_id: 1, title: "John Doe" },
      { user_id: 2, title: "Teddy Foobar" }
    ]
  }
]
```

The `columns` option in the table constructor could accept an object that can contain data related to the autocomplete choice. This way I could have information related to the particular autocomplete choice instance in my database. Is there anything existing that could solve this issue? Thanks in advance!

**Comment by motin** [comment]
Afaik, this is not possible currently without a plugin like https://github.com/trebuchetty/Handsontable-select2-editor/

**Comment by thom801** [comment]
@warpech would you consider merging this feature in if I built it out? This is an old issue but it looks like it would be useful so I'd love to contribute. Otherwise maybe a plugin would be a good route.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by jlsalmon** [comment]
Any update on this? This is a highly desirable feature. I too would be happy to contribute to this.

**Comment by elgubenis** [comment]
+1

**Comment by ahghatol** [comment]
Any update on this feature? Is it available now? I think without this feature handsontable autocomplete is useless.

**Comment by AMBudnik** [comment]
Hi @ahghatol it's not under development yet - when it will be issue gets reopened or updated.

**Comment by afbruno** [comment]
+1

**Comment by afbruno** [comment]
I've been looking for it for about 2 years now. It's unbelievable how it still does not exist in Handsontable.

**Comment by elgubenis** [comment]
@afbruno you could use a custom select plugin to create this custom field in your table, https://select2.github.io/ is a great plugin for that

**Comment by baukaman** [comment]
+1

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
