### ISSUE TITLE
Pasting fails intermittently and causes the screen to scroll to the top.

### ISSUE THREAD

**Issue by donald-s** [handsontable/handsontable#5350]
### Description
When pasting data into multiple cells in succession that triggers a data or settings update, pasting randomly fails and causes the screen to scroll to the top. Scrolling back down and attempting to paste the data results in the paste continuing to fail and the screen scrolling back to the top. You can only get the paste to work by clicking on the cell or by using the arrow keys to navigate away from the cell and then navigate back to the cell.

### Steps to reproduce
The bug is unfortunately difficult to reproduce. I'm unable to consistently reproduce the paste issue. That said, here are the steps to reproduce the scroll issue:

1. Paste a value into multiple cells in succession that cause the table data / settings to update until the paste fails and the screen scrolls to the top.
1. Select a cell.
2. Paste into the cell.
3. As quickly as possible, use the down arrow to select the next cell and paste into it.
4. Repeat until the paste fails and the screen scrolls to the top.

### Demo
https://jsfiddle.net/don_schrimsher/xvoqgzet/

As mentioned above, I'm unable to consistently reproduce the failed paste issue. This demo includes the scroll issue only. To reproduce in the demo:

1. Scroll down to the bottom of the table (so that you can't see the top of the table).
2. Click on one of the cells on the bottom row.
3. Paste.

### Your environment
* Handsontable version: 5.0.1
* Browser Name and version: Google Chrome 68.0.3440.106
* Operating System: macO High Sierra 10.13.6

The issue appears to be due to a race condition in enabling the plugin and setting focus on the cell. It seems that the `onAfterSectionEnd` hook isn't being fired correctly in the copy paste plugin when the issue occurs. I believe the fix will need to somehow queue paste commands that are then run once the copy paste plugin is enabled. If someone can point me in the right direction with where to implement this, I'd be happy to open a PR for it. For now, I'm opening a PR to fix the scroll issue. The scroll issue is due to [this line here](https://github.com/Keystone-Strategy/handsontable/blob/9983e8e10128abcd8cd021d761618448ab5945d8/src/editors/textEditor.js#L73) being set to -9999px top and left. When the element receives focus, it causes the browser to scroll.

**Comment by AMBudnik** [comment]
Hi @donald-s 

Can I ask you to create a video or a gif? I'm not able to replicate the issue but maybe I'm doing something wrong or I'm just not as fast with the down arrow.

**Comment by donald-s** [comment]
@AMBudnik Sorry for the delay in getting back to you. It looks like this has been fixed in v6, so I'm going to close this PR.
