### ISSUE TITLE
hot table's header section is different width from data section when container's width specified as percentage

### ISSUE THREAD

**Issue by mewalig** [handsontable/handsontable#5351]
hot table's data rows are a different width from the header rows. It appears this may only occur If the target container's width is specified in percentage, in which case the wtHolder element inherits the width as a percentage. So if the container width = 90%, then wtHolder's width is 90%, and its width in pixels ends up being 90% of 90%. 

Note: I'm displaying the hot table inside a bootbox modal (after the modal is shown)-- wouldn't think that matters but haven't checked outside of that use case.

For example:

HTML:
```
<div id="hot_div" style="width:90%">
```

Javascript:
```
let hotSettings = {
  colHeaders: [...],
  data: [...],
  columns: [...],
  height: 400,
  rowHeaders: true
};
let output_div = $('#hot_div')[0];
Handsontable(output_div, hotSettings)
```

**Comment by AMBudnik** [comment]
Hi @mewalig 

Can you share a demo where the issue can be replicable? I couldn't replicate it at http://jsfiddle.net/yjeta20b/

**Comment by mewalig** [comment]
http://jsfiddle.net/yjeta20b/15/

**Comment by AMBudnik** [comment]
Thank you for sharing the demo @mewalig 

I have replicated the issue but haven't found any solution to fix it. I am adding the `bug` label.

**Comment by AMBudnik** [comment]
Hey @mewalig 

Can you update to v `7.0.2` and let me know if it works for you? We've made a quick research and found out that it should work fine now, even if we haven't had an intention to support it in the first place. 
If the issue's still there in your app after updating to v `7.0.2` please prepare a new demo.

**Comment by mewalig** [comment]
Thanks. Looks good! working demo: http://jsfiddle.net/7wc089fu/

**Comment by AMBudnik** [comment]
Great! Thank you for confirmation.
