### ISSUE TITLE
Editable "handsontable in handsontable" cell

### ISSUE THREAD

**Issue by optilude** [handsontable/handsontable#536]
Hi,

The new "handsontable in handsontable" cell type (http://handsontable.com/demo/handsontable.html) is really cool. Are there any plans to make the child table editable, and allow storing the whole table rather than a single value (i.e. the underlying value at a given cell becomes a list of objects or a list of lists)?

This would open up all kinds of interesting use cases, modelling parent-child relationships. Right now to do this, I've created a custom cell type that stores a handsontable config in its properties, with a renderer that shows a link that opens a modal dialogue with a "child" handsontable, and a callback hook that stores the edited list-of-objects against a cell in the parent table. This works, but it's quite clunky. The new cell type looks much nicer.

Martin

**Comment by 57even** [comment]
+1

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
