### ISSUE TITLE
Browser crashing with a certain amount of data

### ISSUE THREAD

**Issue by sruchot** [handsontable/handsontable#5360]
Hello,

I'm trying to implement a data visualization tools for my application using HoT.
For that, it may require to display a 'large' data set.

My tests were done using HoT Version: 5.0.0.

I tried two simple test cases using the following link [http://jsfiddle.net/xhh4vnmh/](http://jsfiddle.net/xhh4vnmh/).

First setting data to Handsontable.helper.createSpreadsheetData(1000000, 10), basically 1M row with 10 columns. Rendering it's quite fast and scolling seems fine, but around 800k, the rows disapear. It seems that the scroll calculation is fine though.

Then, testing with Handsontable.helper.createSpreadsheetData(1000000, 50) will just crash the browser.

Maybe those test case are not to be handle by HoT but I prefered to at least enter this issue to have some more insights on that.

Thanks.

**Comment by AMBudnik** [comment]
Hm... It's hard to propose any solution for that case. 

The Handsontable needs its own calculations and browser is not going to handle them all when you have a billion cells.

The number of cells that can be rendered may increase when we'll add a single-cell rendering. We are planning to change the way that cells are being rendered, however, there's a long way to achieve this goal.
