### ISSUE TITLE
Rows calculator miscalculating the number of rows to be rendered.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#5365]
### Description
When the rows calculator gets a `NaN` instead of a `Number` as the row height, it forces the table to render all rows.
For example, setting a `modifyRowHeight` hook with unhandled `undefined` height value, makes a large table virtually unusable.

### Steps to reproduce

1. Go to http://jsfiddle.net/js_ziggle/p3om6nue/13/
2. Edit any cell, the number of rendered rows should be around `20`
3. Click the button, it will add a `modifyRowHeight` hook callback
4. Edit any cell and notice the number of rendered rows and the table performance.

### Demo
http://jsfiddle.net/js_ziggle/p3om6nue/12/

**Comment by wojciechczerniak** [comment]
5.0.2-RC: http://jsfiddle.net/jmehurfy/ 👍
