### ISSUE TITLE
Dropdown list visibleRows not working

### ISSUE THREAD

**Issue by Prahadeesh92** [handsontable/handsontable#5370]
### Description
I am using handsontable-pro version 5.0.1. Dropdown list visibleRows not working. Please see screenshot for the reference.

In my code, I mentioned the visibleRows:4
var columnObj = {
          data: dataName,
          title: value.title,
          type: value.fieldType,
          visibleRows:4
        };

![dropdownlist-handsontable](https://user-images.githubusercontent.com/13902011/44463705-3ad0b000-a636-11e8-94fa-46d05c3bc2c5.PNG)

**Comment by AMBudnik** [comment]
Hi @Prahadeesh92 

can you share an example? i've tried http://jsfiddle.net/x59qwha2/ on Chrome 67 but it works well

**Comment by Prahadeesh92** [comment]
I think this issue is similar to #4172 issue ?.  You metioned in that "The issue is still replicable in v5.0.1 (demo http://jsfiddle.net/Lydwbovs/)".

**Comment by AMBudnik** [comment]
So it is the same as #4172 and you update the `height` or there is something else that causes the bug? If it is a different issue please create a demo where I'll be able to replicate the issue.

**Comment by AMBudnik** [comment]
Oh, yes, thank you for the description.

I think that we should stick to the issue reported at #4172. It will be easier for the developers to gather opinions and investigation results based on similar use cases in the same topic. 
If we are missing anything in the #4172 please post a comment there describing your implementation. It will also help all those users who have the same issue to track changes to the subject.
