### ISSUE TITLE
hot.selection.selectedHeader still available somewhere?

### ISSUE THREAD

**Issue by dmt0** [handsontable/handsontable#5371]
### Description
After upgrading HOT from 0.38 to 2.0.0, `hot.selection.selectedHeader` disappeared. I have not seen that as a braking change for the releases. Searching for it in the current code base yields no results. Please advise.

**Comment by dmt0** [comment]
Found `HOT.selection.isSelectedByAnyHeader()` which serves my purpose.

**Comment by budnix** [comment]
To extend this topic about API changes I can add from myself that breaking change was introduced in 2.0.0 version. And you are right there is nothing about this changes in release notes.

Previously we could check header selection like this:
```
hot.selection.selectedHeader.cols // for column selection
hot.selection.selectedHeader.rows // for row selection
hot.selection.selectedHeader.corner // for corner selection
```
now
```
hot.selection.isSelectedByColumnHeader()
hot.selection.isSelectedByRowHeader()
hot.selection.isSelectedByCorner()
// and new method equivalent to .. `hot.selection.selectedHeader.cols || hot.selection.selectedHeader.rows`
hot1.selection.isSelectedByAnyHeader() 
```

**Comment by budnix** [comment]
@jansiegel Can we add this changes to "Braking Changes" section?
