### ISSUE TITLE
I am trying to update changes made in handsontable to the database(SQL Server) using mvc controller.I am new to web development.Kindly tell me how can i save the changes made in the table to the mutiple table in the database.

### ISSUE THREAD

**Issue by RahulRaj4** [handsontable/handsontable#5374]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @RahulRaj4 

Here's a tutorial that may help https://docs.handsontable.com/pro/5.0.1/tutorial-load-and-save.html
Unfortunately, as a front-end library, we do not have any data connectors yet nor any more tutorials on that subject.
