### ISSUE TITLE
[3.0.0+] server-side beforeColumnSort with return false does not update order

### ISSUE THREAD

**Issue by s1monj** [handsontable/handsontable#5377]
### Description
When returning false with beforeColumnSort for server-side sorting, clicking the header should also toggle the order and display the indicator. Column number updates correctly. This worked before the column sort refactoring.

### Steps to reproduce
```
columnSorting: true,
sortIndicator: true,
beforeColumnSort: function(column, order){
  console.log('col:'+column+' order:'+order);
  return false
}
```

### Demo
http://jsfiddle.net/simonlj/ydck5uz4/

### Your environment
* 5.0.1
* Firefox 52
* Centos Linux

**Comment by AMBudnik** [comment]
Thank you for sharing the report @s1monj 

You're right. As we did not mention any changes being done to `beforeColumnSort` I treat it as a `regression` `bug`.

**Comment by AMBudnik** [comment]
The issue stays the same in v `6.0.1`. The `beforeColumnSort` hook has changed its parameters but still, after we pass `return false` we do not get the values`

Updated demo http://jsfiddle.net/handsoncode/z6p8jyqt/
