### ISSUE TITLE
Date value is not displayed by datepicker option

### ISSUE THREAD

**Issue by Prahadeesh92** [handsontable/handsontable#5378]
### Description
By selecting a date with datepicker, the date is not displayed in the table.

### Your environment
* Handsontable version: 5.0.1 (pro)
* Browser Name and version: Firefox
* Operating System: Windows 0

**Comment by AMBudnik** [comment]
Hi @Prahadeesh92 

are you able to replicate this issue using our main `date` demo at https://docs.handsontable.com/pro/5.0.1/demo-date.html?

It works fine for me but maybe you have a different settings.

**Comment by AMBudnik** [comment]
I believe that this is no longer an issue as there's no reply for more than a week
