### ISSUE TITLE
css class for tr elements

### ISSUE THREAD

**Issue by Paul-A-Kavan** [handsontable/handsontable#5379]
My goal is to use css to style the first and last rows that contain any highlighted/selected area.

The issue is that the classes (such as .current .currentRow .area .highlight) used for selected cells are applied directly to the th or td elements. Therefore, I cannot use nth-of-type or nth-child selectors on the tr elements. 

Would it be possible to use an existing class or create a new class for any tr that parents a selected or highlighted td element? The result of such a solution would be the ability to style at the table row level for selections. Please let me know if this is feasible! And thanks for all the hard work on this great product!!

**Comment by AMBudnik** [comment]
Hi @Paul-A-Kavan 

do you mean something like this http://jsfiddle.net/b0jhqdcf/?

**Comment by Paul-A-Kavan** [comment]
Thanks for the response! This is a great way to add custom classes to the cells but this requires the use of the cell coordinates, r and c. Is there a way to do this for the tr elements, where we don't have coordinates? 

In particular, the goal is to style the first and last rows of a selected area and include the <th> elements not just the cells with table coordinates. I doubt it's possible to use something like setCellMeta from the API on tr elements which is why I thought that this needed to be something of a more fundamental code change.

**Comment by AMBudnik** [comment]
Yes, currently there is no way to address the TR element, only TDs elements inside a given row index.

**Comment by Paul-A-Kavan** [comment]
Okay, thank you for confirming. 
To conclude this issue, I would just say that this feature would be valuable in the future if possible and thank you for all your effort on handsontable!!
