### ISSUE TITLE
Adding Pagination with Angular 

### ISSUE THREAD

**Issue by sarwin-github** [handsontable/handsontable#5383]
Hello, 

I'm integrating handsontable to Angular 6.01 with Angular Materials and typescript. I was wondering if it's possible to add pagination or does anyone already did this? Thank you in advance.

**Comment by AMBudnik** [comment]
Hi @sarwin-github 

officially we do not support pagination. You may want to consider reloading chunks of data inside the same table, but it is a showstopper for sorting or filtering.
