### ISSUE TITLE
Handsontable triggers alot of change-detection runs in Angular after reassigning [data] property on the hot table component. 

### ISSUE THREAD

**Issue by salcio** [handsontable/handsontable#5384]
### Description
I seem to have similar problem to the one described in [issue 4100](https://github.com/handsontable/handsontable/issues/4100). But it happens when `data ` property on hot-table component is reassigned. After reassign every event in Hot-table triggers change-detection in angular. In the [demo](http://jsfiddle.net/salcio/pj28uc4y/) that've created mouse move triggers change detection. In my app it is event worse, it looks like there is a timer interval that raises the ngDoChecks.

### Steps to reproduce
Open demo then:

- click 'clickMe' button. It will initialize the table with data.

- monitor console output. When you move the mouse nothing new should be reported in console.

- click 'clickMe' button again. That will reset dataset property which is bound to data property on the component.

- monitor console output. As you move mouse new messages will appear - reported by ngDoCheck method. 

### Demo
http://jsfiddle.net/salcio/pj28uc4y/

### Your environment
* Handsontable version: 5.0.1
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by swistach** [comment]
Hi @salcio,
thank you for your sharing.
Probably `this.hotInstance.updateSettings(newSettings, false);` https://github.com/handsontable/angular-handsontable/blob/master/lib/pro/src/hot-table.component.ts#L361 should be called inside `runOutsideAngular(() => {...}`.

**Comment by salcio** [comment]
Hi @swistach 
Thanks for pointing me to the source code. 
I can confirm that after overriding updateSettings method on the component instance change-detection is not triggered. As a temporary hacky workaround I'm using something like that 

```
private fixNgDoCheckssBug() {
    const old = this.hotTable.updateHotTable;
    this.hotTable.updateHotTable = function (newSettings: object) {
      const table= this;
      this._ngZone.runOutsideAngular(() => {
        old.apply(table, [newSettings]);
      });
    };
}
```

When can we expect proper fix for this and a new version of Angular wrapper ?

**Comment by AMBudnik** [comment]
Issue moved to [handsontable/angular-handsontable #116](https://github.com/handsontable/angular-handsontable/issues/116) via [**ZenHub**](https://www.zenhub.com/)

**Comment by AMBudnik** [comment]
Hey @salcio 

please update the Handsontable for Angular wrapper to v 3.0.0
we've fixed that issue
