### ISSUE TITLE
Add `beforeSetCellMeta` hook with an ability to cancel the changes

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5388]
### Description

Add `beforeSetCellMeta` hook with an ability to cancel the changes
I was specifically thinking of blocking unwanted comments (block a comment for a certain cell or block bad language in the comments) but it can also relate to other metadata.

### Your environment
* Handsontable version: 5.0.1
* Browser Name and version: Chrome 68
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
This feature request is closed, But it will be automatically reopened after we attach it to a milestone.

**Comment by aninde** [comment]
Done by https://github.com/handsontable/handsontable/pull/6778.

**Comment by AMBudnik** [comment]
Added to v8.0.0 https://handsontable.com/docs/8.0.0/Hooks.html#event:beforeSetCellMeta
