### ISSUE TITLE
Drag fill doesn't scroll

### ISSUE THREAD

**Issue by optilude** [handsontable/handsontable#539]
In Excel (and other spreadsheets), if I select some cells and start to drag-fill across (I've only tested this horizontally), the sheet scrolls right or left with my mouse. In Handsontable, I can only drag-fill into visible rows, so I can't copy a sequence  any more than one screen-full at a time.

This is very limiting to my use case. ;-) I may try to dig into it, though this part of the code scares me.

**Comment by krzysztofspilka** [comment]
It works in v. 0.13.1, thanks for reporting @optilude
