### ISSUE TITLE
Does handsontable automatically calculate the result between two columns when the cell is dragged down after entering the formula in it like Excel?

### ISSUE THREAD

**Issue by fengtong** [handsontable/handsontable#5391]
![fc0c9bd9-c8e5-478d-9966-b7e552ac1907](https://user-images.githubusercontent.com/20556813/45129662-ba728900-b1b7-11e8-8356-223775c68d4b.png)
![qq 20180905175619](https://user-images.githubusercontent.com/20556813/45129675-cb22ff00-b1b7-11e8-8565-cb395df52311.png)

**Comment by AMBudnik** [comment]
Hi @fengtong 

It should update. Here is an example where it does http://jsfiddle.net/q8nLdvpx/

![gif](https://user-images.githubusercontent.com/10757813/45139218-4e8c2280-b1af-11e8-8639-167a285f52c1.gif)

If you have a case where it does not work please share a demo and a step-by-step bug scenario

**Comment by fengtong** [comment]
Hi @AMBudnik thanks~~

![data](https://user-images.githubusercontent.com/20556813/45139999-2834aa00-b1e4-11e8-855a-667b2751013b.gif)

Like this gif picture~Can the latest version handsontable do that?

**Comment by AMBudnik** [comment]
Our Formula Plugin is not able to autofill the formula yet. It will return you a value of the first cell's formula.

**Comment by AMBudnik** [comment]
You're welcome @fengtong
