### ISSUE TITLE
Can't use Ctrl + C to copy row/col which has first cell is read only

### ISSUE THREAD

**Issue by cuongurus** [handsontable/handsontable#5392]
### Description
Can't use Ctrl + C to copy row/col which has first cell is read only.
It's work when use Copy in Context Menu.

### Steps to reproduce

1. I create a Handsontable and make cell[0][1], cell[1][0] read only.
2. Click on second row header then press Ctrl + C but nothing can be pasted out.
3. Same when click on second column header.

### Demo

http://jsfiddle.net/17ry4ut2/8/

### Your environment
* Handsontable version: 5.0.1
* Browser Name and version: Chrome 69
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you sharing @cuongurus 

Yes, you're right. If I want to copy-paste the 2nd row I just paste nothing (it even doesn't copy).

**Comment by AMBudnik** [comment]
It looks like the [`beforeCopy` is not triggered for the 2nd-row copy operation](http://jsfiddle.net/z5fjksg3/). 
The `modifyCopyableRange` hook returns proper array of copyable range. 
The `afterDocumentKeyDown` recognizes the keys properly.

**Comment by swistach** [comment]
This issue will be solved within #4931
