### ISSUE TITLE
Is there a way to delay calling the API when using autocomplete

### ISSUE THREAD

**Issue by Pradhyo** [handsontable/handsontable#5396]
### Description

Is there a way to delay calling the API when using autocomplete as shown [here](https://docs.handsontable.com/5.0.1/demo-autocomplete.html#strict-ajax)?

This works exactly as documented but I would like to wait 1 second before making an API call after the user stops typing for performance reasons.

I am using @handsontable/angular@2.0.0

**Comment by AMBudnik** [comment]
You can check

```js
```

in

```js
success: function (response) {
            console.log("response", response);
            //process(JSON.parse(response.data)); // JSON.parse takes string as a argument
            process(response.data);

          }
```

**Comment by Pradhyo** [comment]
Thanks for getting back, that's not what I wanted but I was able to achieve it using [this](https://stackoverflow.com/questions/52262811/ignore-multiple-successive-function-calls-in-typescript-from-within-the-function/52281613#52281613).

**Comment by Pradhyo** [comment]
@AMBudnik However, I notice implementing the above answer broke copy-paste functionality.

**Comment by AMBudnik** [comment]
Can you share a demo with your last version of implementation?
