### ISSUE TITLE
Display chemical formula

### ISSUE THREAD

**Issue by akina-OS** [handsontable/handsontable#5397]
### Description
Display chemical formula

### Steps to reproduce
Hello, we are using handsontable now, but we have a problem, our data contains chemical formulas, we tried to use html tags like '&lt;sub&gt;&lt;/sub&gt;', but when initializing the table, '<' and '>' have been escaping. Is there any better way? Thank you

### Demo
H<sub>2</sub>O

###  dev
* Handsontable version: Handsontable 0.11.4
* Browser Name and version:  Google Chrome 68.0.3440.106（32）
* Operating System: windows

**Comment by AMBudnik** [comment]
Hi @akina-OS 

I've used a renderer here http://jsfiddle.net/19qeyLh0/ so it only shows a value. If you could bright more light on the actual i/o data I can help you to accomplish the goal (I love chemistry!).

**Comment by akina-OS** [comment]
> Hi @akina-OS
> 
> I've used a renderer here http://jsfiddle.net/19qeyLh0/ so it only shows a value. If you could bright more light on the actual i/o data I can help you to accomplish the goal (I love chemistry!).

I am very happy that you are willing to help me. I am very sorry. I saw your message two days later. I am a Chinese, so English is not very good. What you mean is that after the ‘handsontable’ is initialized, use the method to replace the contents. It's a pity that I don't have a business here and I can't do it many times. Because of the content inside the form, there are still locations that are dynamic. Is there any way to support the 'html' tag of the 'sub' class when the table is initialized..... (Thank you for your answer again, this is the first question I asked on github. Very happy (●ˇ∀ˇ●)

**Comment by AMBudnik** [comment]
I am happy to help. If you need anything else please let me know.
