### ISSUE TITLE
Page scrolling top when selecting cell - Mobile

### ISSUE THREAD

**Issue by lucasncne** [handsontable/handsontable#5399]
### Description

The same bug that was happening with Firefox (which was fixed at version 5.0.2) is happening using the mobile version of Chrome. Also, when you edit a cell, after pressing Enter, you can't edit the second one unless you type enter again or click on it.

### Steps to reproduce

1. Access this page: [https://docs.handsontable.com/5.0.2/demo-mobiles-and-tablets.html](https://handsontable.com/examples) using a mobile phone
2. Try to click on any cell
3. Get mad

### Your environment
* Handsontable version: 5.0.2
* Browser Name and version: Chrome 69.0.3497.91 (Mobile)
* Operating System: Android

**Comment by AMBudnik** [comment]
Hi @lucasncne 

can you resend the demo? It does not redirect to any table example

**Comment by lucasncne** [comment]
@AMBudnik 
Sorry, it was working at the moment of my post...
If you access the example table of the official website using the Chrome (mobile) you can replicate the issue.
[https://handsontable.com/examples](url)

**Comment by AMBudnik** [comment]
Thank you @lucasncne 

I have replicated the issue.

I can select a cell but if I double-click it scrolls to the top of the page.

![gif](https://user-images.githubusercontent.com/10757813/45621983-c77a5c80-ba82-11e8-97b8-1b7773458a1f.gif)

**Comment by eKristensen** [comment]
Any updates? I have the same problem on Android 9 with Chrome 69. Only a single click is all it takes for it to jump to the top, making any interaction on mobile impossible.

Where? Still the demo: https://handsontable.com/examples

**Comment by lucasncne** [comment]
Nothing yet.
If you find any temporary solution please tell me, I'm still looking for one.

**Comment by AMBudnik** [comment]
Hey @lucasncne @eKristensen 

have you tried the latest version? Seem to work fine now.

![RPReplay_Final1555484851](https://user-images.githubusercontent.com/10757813/56267959-90d7f380-60f0-11e9-9d5a-37c2163a1bc8.gif)

I've tried it with https://handsontable.com/docs/7.0.2/demo-scrolling.html

**Comment by AMBudnik** [comment]
I'm closing the issue as I could not replicate it, but if there's anything I'm missing please let me know.

**Comment by eKristensen** [comment]
Hi there. Sorry for not getting back to you.

I can no longer replicate the issue myself. Thanks!

Have a great day :)

**Comment by AMBudnik** [comment]
Thank you for the update. I'm glad that it works for you as well @eKristensen
