### ISSUE TITLE
onDrawn (or onScrolled) event

### ISSUE THREAD

**Issue by optilude** [handsontable/handsontable#540]
I'm trying to sync multiple Handsontable instances on one page, so that if one is scrolled horizontally, the others move with it. I thought this would be pretty easy - listen to an event when table 1 is scrolled, get the viewport offset, and scroll the other table - but it turns out to be very difficult to work out when a table has been (re)drawn due to scrolling. 

It would be very helpful to have an event triggered in `WalkontableTable_doDraw()` or similar that just notifies when the table is drawn so post-draw actions can be triggered.

I can probably just do this and issue a pull request, but I'd like some feedback first. With the pace of development recently (which is great!) I'm worried that I'd have to maintain a branch for a long time if @warpech didn't merge the pull request relatively soon :)

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by stla** [comment]
I did something of this kind [here](http://stackoverflow.com/a/41416452/1100107) but it is specific to a particular case and it is done in a Shiny app.

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
