### ISSUE TITLE
Row index of header is same as the row index of first row

### ISSUE THREAD

**Issue by rupindersingh2** [handsontable/handsontable#5400]
### Description
In the following demo, whenever you try to sort column 'B', you get an alert which is supposed to come up only when you select any cells in column 'B' and not select the header. I want to be able to sort without the alert coming up as my application shows a popup in place of the alert

http://jsfiddle.net/t79u4w66/25/

* Handsontable version: 5.0.1

**Comment by AMBudnik** [comment]
Hi @rupindersingh2 

you get an alert when you select the header as this action automatically select the cells in column` B`. To solve it I've added a helper called `isHeaderSelected`. It turns on and off when header gets selected via `beforeOnCellMouseDown` hook. It is added to the `IF` condition in the `15` line.

Demo http://jsfiddle.net/ehpcdoq5/
