### ISSUE TITLE
[4.0.0+] a new cell i selected still has the background color of the last cell i selected 

### ISSUE THREAD

**Issue by graceliu4709** [handsontable/handsontable#5402]
### Description
  firstly,i double click a cell ,then i double click another cell,the new cell i selected it's background color is supposed to white,while, it turns out the background color is the background color of the cell i have selected before

### Steps to reproduce

1.double click one cell(this cell has a background color not white)
2.double click another cell
3.you can see the new cell's background isn't white(i want it to be write)

### Demo

https://jsfiddle.net/api/post/library/pure/
### Your environment
* Handsontable version: v5.0.2
* Browser Name and version: chrome  69.0.3497.81
* Operating System: win7 64

**Comment by AMBudnik** [comment]
Hi @graceliu4709 

Can you resend a demo? It did not save.

**Comment by graceliu4709** [comment]
Hi @AMBudnik 
sorry that link doesn't work ,here is demo form the docs
https://docs.handsontable.com/pro/5.0.2/demo-conditional-formatting.html

**Comment by AMBudnik** [comment]
Wow. I have never seen this bug before. I will investigate it and share my thoughts.

**Comment by graceliu4709** [comment]
yeah that's true. But now i am doing a project that i can change the cells' background  color to any kind of color  manually , so it's inappropriate to use a className. By the way it works fine with version 0.34.0

**Comment by AMBudnik** [comment]
It looks like the version `4.0.0` broken the correct behavior
https://docs.handsontable.com/pro/4.0.0/demo-conditional-formatting.html

**Comment by AMBudnik** [comment]
We already closed the milestone, but we'll see. If there's enough time we can try to fix it.

Thank you for reporting @graceliu4709

**Comment by graceliu4709** [comment]
so it is a bug i will wait a new version to come out

**Comment by AMBudnik** [comment]
Hi @graceliu4709 

thank you again for sharing the report. The issue should be solved in v 6.0.1
