### ISSUE TITLE
Help needed: Confirm Italian translation

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5407]
## Welcome community!
We have just received a translation for the **Italian** language at the https://github.com/handsontable/handsontable/pull/5406.

Please help us to confirm it. 
**5 votes+** will allow us to confirm the translation and pull the changes.

Thanks!

**Comment by giovannipessiva** [comment]
Hi, I checked it, it's ok

**Comment by AMBudnik** [comment]
Thank you @giovannipessiva

**Comment by AMBudnik** [comment]
Hi @giovannipessiva Italian is now the official language of Handsontable Pro 6.1.0+
Thank you for your effort to check it
