### ISSUE TITLE
Using ellispis for long cell content instead of wrapping it to the next line

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [handsontable/handsontable#5408]
For my use case I'd like to show my tabular data on single line rows and use ellipsis in case the content overflows. The content is read-only so there is no need to enlarge the cell for editing purposes.

![obrazek](https://user-images.githubusercontent.com/3907898/45648708-9e30ef00-bac9-11e8-8962-f16102ed1182.png)

There are lot of columns and not all of them have to be shown completely as their values can be guessed by first few characters. It helps to show lot of data in a very compact form.

**Comment by AMBudnik** [comment]
Hi @jan-tosovsky-cz 

here is an example that can help https://jsfiddle.net/hnm2y6jz/

You should define the new CSS settings for the `.handsontable td` elements and add some predefined widths for columns via `colWidths`.

**Comment by jan-tosovsky-cz** [comment]
Cool, this is exactly what needed. It would be nice to have an option for this though.

**Comment by AMBudnik** [comment]
We can mark the topic as a `feature request` :)

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for sharing. I hope that we'll be able to publish it soon.

**Comment by 12345zp** [comment]
> 
> 
> Hi @jan-tosovsky-cz
> 
> here is an example that can help https://jsfiddle.net/hnm2y6jz/
> 
> You should define the new CSS settings for the `.handsontable td` elements and add some predefined widths for columns via `colWidths`.
I defined new Css and setted colWidth to fix my case.  
[css]
`.handsontable td {  
	overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}`
[handsontable setting]
`columns {
 { readOnly: true,type: 'text',   width: 120 , data: 'text' ,className: "htCenter", renderer: "html"},
....
}`
