### ISSUE TITLE
Scroll event not propagating outside HOT instance

### ISSUE THREAD

**Issue by ahadzic** [handsontable/handsontable#5414]
### Description
When web page contains content above and below embedded HOT instance, such that it provides vertical scroll for user, once that mouse cursor is positioned over table scroll event is contained to HOT instance and is not passed to outside web page. Table inside scrolls work correctly, but it does not propagate event to the outside.
Once user leaves HOT instance scrolling is behaving regularly.

Is any workaround known to fix this issue.

### Steps to reproduce

1. Visit specified link in demo.
2. Make sure to be scrolled to the top.
3. Position mouse over HOT table.
4. Scroll to the bottom.
5. HOT table scroll is activated, but page doesn't scroll it's content.

### Demo

Easiest way to replicate is to use Example page (easier if more options are selected) on specified browsers.
https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: Firefox 62, Safari (latest)
* Operating System: Linux, Mac

**Comment by AMBudnik** [comment]
Hi @ahadzic 

we have been reported about the same behavior here https://github.com/handsontable/handsontable/issues/5212

Please track changes to https://github.com/handsontable/handsontable/issues/5212 for updates
