### ISSUE TITLE
Wrong typing for beforeColumnMove

### ISSUE THREAD

**Issue by guillaumep** [handsontable/handsontable#5416]
Documentation says about beforeColumnMove's arguments:

Name | Type | Description
-- | -- | --
columns | Array of numbers | Array of visual column indexes to be moved.
target | Number | Visual column index being a target for moved columns.

https://docs.handsontable.com/pro/5.0.2/Hooks.html#event:beforeColumnMove

But the typing in handsontable.d.ts has:

`beforeColumnMove?: (startColumn: number, endColumn: number) => void;`

It should be:

`beforeColumnMove?: (columns: number[], target: number) => void;`

**Comment by guillaumep** [comment]
Note: same thing is happening for beforeRowMove.

**Comment by AMBudnik** [comment]
Thank you for sharing @guillaumep

**Comment by AMBudnik** [comment]
Hi @guillaumep 

we haven't scheduled the epic nor the PR yet but will surely consider adding the PR first

**Comment by guillaumep** [comment]
@AMBudnik Is there something I can do to help this be merged?

It has already been one month the PR has been opened. Do other contributors to Handsontable have to wait this long too?

**Comment by AMBudnik** [comment]
I will try to push the code review for https://github.com/handsontable/handsontable/pull/5425 to the next milestone

**Comment by guillaumep** [comment]
@AMBudnik Thanks!

**Comment by AMBudnik** [comment]
Hi @guillaumep 

the changes are published. Please update to `6.2.0`
