### ISSUE TITLE
How to keep an object inside a cell and bind with one of the object property

### ISSUE THREAD

**Issue by RahulBadenkal** [handsontable/handsontable#5417]
### Description

I have kept an object inside the handsontable cell, and written a custom renderer that will display only one of the property of the cell. And whatever the user enters in this cell will change that property value only. (basically 2-way binding with a single property of the object)
But the problem I am facing is that at the time of editing the cell, [Object Object] is being displayed which is not what i want. How to make sure that even at the time of editing the property value is being displayed?

I would really **NOT** like to make another array of array that holds only the property value and bind that to hot

### Demo

https://jsfiddle.net/8ffpsqt6/287/

**Comment by AMBudnik** [comment]
Hi @RahulBadenkal 

the editor, if default, uses the value that you have in the `data`. You can create a custom editor, [here's a syntax](https://jsfiddle.net/handsoncode/ep2q6kut/).
