### ISSUE TITLE
Paste of merged cell replaces less content than merge size

### ISSUE THREAD

**Issue by rbarato** [handsontable/handsontable#5418]
### Description
When I paste a merged cell content to a single cell, it replaces less cells than the amount of cells in the merge array. It only affects single rows.

### Steps to reproduce
1. Merge cells A1:A5
2. Copy content
3. Paste content to B1

### Demo
https://jsfiddle.net/mdrbcsqu/

![sep-26-2018 17-29-06](https://user-images.githubusercontent.com/1949592/46107774-a3b9c380-c1b2-11e8-8a8c-28cb126b10b2.gif)
### Your environment
* Handsontable version: 5.0.2

* Browser Name and version: Chrome 69
* Operating System: MacOS High Sierra

**Comment by AMBudnik** [comment]
Thank you for sharing the issue @rbarato 

I think that it might be loosely related to https://github.com/handsontable/handsontable/issues/5101

I did not find any version where this operation would work fine.

**Comment by rbarato** [comment]
Hi @AMBudnik, it seems somehow related. It's not a big issue though. Thanks!

**Comment by wojciechczerniak** [comment]
Fixed since v6.1: https://jsfiddle.net/efL64qtx/

**Comment by AMBudnik** [comment]
Thanks for checking @rbarato Can you confirm?

**Comment by rbarato** [comment]
Hi @AMBudnik, it's fixed! Although it's not pasting the "merge", but I think that could be treated as an enhancement not a bug.

Thanks for that.

**Comment by AMBudnik** [comment]
Great :) Thank you for the prompt reply
