### ISSUE TITLE
[4.0.0+] Enter invalid date with `allowInvalid: false` breaks table

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5419]
### Description

If you have a table with `allowInvalid: false` and you try to enter an invalid date into a `date` cell you get stuck in the cell without any way to get out: pressing Escape does not revert to the original value, focus remains locked in the cell, and even entering a valid date and pressing Enter doesn't close the cell editor. 

### Steps to reproduce

1. Take the [date demo](https://docs.handsontable.com/5.0.2/demo-date.html) and add `allowInvalid: true` -- [example here](https://jsfiddle.net/9k172y56/)
2. Enter an invalid date into the date column, like "abc", press Enter
3. The cell keeps focus in editor and clears the value, press Escape or enter a valid date and press Enter

**Result:** nothing happens, the cell is stuck in edit and will not give up focus: 
- Escape does not revert to original value. 
- Clicking outside the cell keeps focus in edit.
- Entering a valid date and pressing Enter is not accepted.

![](http://g.recordit.co/2DeLqx41m0.gif)

**Edit:** I noticed that you can get out of the cell editor by entering a valid value and clicking another cell (pressing Enter at that point doesn't work, but clicking outside the cell does).

### Demo

https://jsfiddle.net/9k172y56/

### Your environment
* Handsontable version: 4.0.0 Pro
* Browser Name and version: Chrome 69
* Operating System: MacOS High Sierra

**Comment by AMBudnik** [comment]
Thank you for sharing the bug and the scenario. The .gif tells us everything.
I have replicated it in the newest version. Thanks for checking the last version that worked. You've mentioned the 4.0.0 was the first one to break the functionality.

**Comment by AMBudnik** [comment]
Thanks again @aaronbeall 
Released in 6.2.0
