### ISSUE TITLE
Render with Nested rows without being collapsed

### ISSUE THREAD

**Issue by nimesha95** [handsontable/handsontable#5420]
Hi, Is it possible to do the above task. Because in my case i have large number of rows and when rendering happens they all displays collapsed.
Any way to render these rows being collapsed? 
Thanks

**Comment by AMBudnik** [comment]
Hi @nimesha95 

I am not sure if I understand. By default, the nestedRows aren't collapsed like here https://docs.handsontable.com/pro/6.0.0/demo-nested-rows.html in our official demo. If you want to collapse them you can use the `collapsingUI` from its plugin. Here's an example http://jsfiddle.net/r1ag21u6/
