### ISSUE TITLE
filter_by_condition Today, Yesterday, Tomorrow not always applicable

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5424]
### Description
I am using the `filter_by_condition` configuration option. On a `date` column it shows the filter by condition options "Today, Yesterday, Tomorrow". However my `dateFormat` is `"MMM YYYY"` (ex "Sep 2018"), which makes those options pretty useless.

**Questions:**
- Is there a way to hide the Today, Yesterday, Tomorrow filter condition options?
- Is there a way to customize the filter by conditions at all?

**Requests:**
- Make the `filter_by_condition` a bit smarter about dates, rather than just offering `[Today, Tomorrow, Yesterday]`, look at the `dateFormat` and use `[This Month, Next Month, Last Month]` or `[This Year, Next Year, Last Year]` depending on whether the `dateFormat` includes days, months, or years. Or it could look at the range of dates to determine what to show.
- Add a configuration option to explicitly set the above options.

**Comment by AMBudnik** [comment]
Hi @aaronbeall 

currently, we do not have any API to handle a set of the options in the `filter_by_condition`. You are able to turn them off in the source code but I assume that you already know that and the fact that turning them on when needed would be extremely difficult.

I have discussed this subject about 2 weeks back but unfortunately, I do not think that we will be able to schedule this enchantment for any milestone in 2018. We have just released a new feature called multi-column sorting and there are still things that we need to fix to make it work perfectly. Then there's already a full list of tasks to be done in the October https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22October+2018%22.

**Comment by AMBudnik** [comment]
Hey @aaronbeall 
thank you for sharing this, the [`filter as you type`](https://github.com/handsontable/handsontable/issues/5030) and the [formatting issue with the numeric cell type](https://github.com/handsontable/handsontable/issues/5031) issues.

We are closing all the tickets that relate to features that are not in progress nor on our Roadmap. They are still visible on our ZenHub (so please fear not, we won't throw them away).
