### ISSUE TITLE
Typescript esModuleInterop issue

### ISSUE THREAD

**Issue by pmunin** [handsontable/handsontable#5428]
### Description

When creating new typescript project, executing `tsc --init` it generates tsconfig.json with default settings, which include `"esModuleInterop": true"`. And this cause compilation error, because 
`import * as Handsontable from {handsontable}` will not want to treat Handsontable as a class, but only as a namespace instead.

For average user it's really hard to cherry-pick and find that `esModuleInterop` is causing the issue, so it would be great if this can be solved somehow.
Suggestion: using default import maybe? so user will write `import Handsontable from 'handsontable'`

### Steps to reproduce

1. create new package (npm init), add typescript 3.0.0 and handsontable 6.0.0 as dependencies
2. initialize typescript project by command `node_modules\.bin\tsc --init`
3. create index.ts with code: 
```ts
import * as Hot from 'handsontable'

export function render(element:HTMLDivElement) {
    new Hot(element,{})
}
```
4.  compile with command `node_modules\.bin\tsc`

**Expected result**: successful compilation
**Actual result:** compilation error

> Cannot use 'new' with an expression whose type lacks a call or construct signature. new Hot(element,{})

### Your environment
* Handsontable version: 6.0.0
* Browser Name and version: 
* Operating System: win7 x64

**Comment by wojciechczerniak** [comment]
Thanks for detailed steps to reproduce the issue.

`esModuleInterop` does exactly what you are suggesting (it implies `allowSyntheticDefaultImports`). According to Typescript 2.7 Release Notes [1] with `esModuleInterop` you shouldn't use namespace import anymore:

> Note: The new behavior is added under a flag to avoid unwarranted breaks to existing code bases. We highly recommend applying it both to new and existing projects. For existing projects, namespace imports (`import * as express from "express"; express();`) will need to be converted to default imports (`import express from "express"; express();`).


In `Typescript >= 2.7` with `esModuleInterop` flag the correct way to import HoT is:
```typescript
import Handsontable from 'handsontable'

export function render(element:HTMLDivElement) {
    new Handsontable(element,{})
}
```

You will still get an error though. Implied `lib` for default `target` and `module` flags don't include `"es6"` but we need it. I'm not sure if we can do anything about that. Any ideas are welcome.


----
[1] https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop

**Comment by AMBudnik** [comment]
I believe that we can close the issue as there are no additional comments and we do not treat this behavior as a Handsontable-generic bug. 
However, thank you for sharing the concerns. This discussion will surely help other users struggling with the same subject.
