### ISSUE TITLE
Pickaday Moment import breaks webpack 4 production build

### ISSUE THREAD

**Issue by ThomasLabstep** [handsontable/handsontable#5430]
Hello,

We have a create-react-app with webpack 4 and babel 7.

Our production build has a warning that turns into an error:

```
./node_modules/handsontable/node_modules/pikaday/pikaday.js 29:17-24
Critical dependency: the request of a dependency is an expression
```

What is the right fix?

Thanks.

### Your environment
* Handsontable version: latest
* Browser Name and version: Chrome
* Operating System: Mac

**Comment by wojciechczerniak** [comment]
Hi @ThomasLabstep ,

Looks like a webpack/babel issue to me, not a bug in Handsontable. We need your configuration details and steps to reproduce the issue to confirm the problem is with Handsontable.

**Comment by ThomasLabstep** [comment]
Thanks for your feedback.

We use a custom Webpack 4 + Babel 7 version of Create React App. We didn't customize much even though we ejected the configuration.

To get the original configuration, use this:

```
npx create-react-app@next --scripts-version=2.0.0-next.3e165448 app-name
yarn upgrade react-scripts@2.0.0-next.3e165448
yarn eject
```

Then add handsontable in this demo app.

Build the production release, you should see the warning.

See also: https://github.com/dbushell/Pikaday/issues/604

**Comment by TCezarRod** [comment]
It seems to be related to the upgrades on the new create-react-app version. 
I got the same problem in a previously-working project right after upgrading react-scripts from 1.1.4 to 2.0.3.

I'm using `@handsontable/react@^1.1.0` with `handsontable@^5.0.1`

**Comment by wojciechczerniak** [comment]
I've seen that you found a solution in dbushell/Pikaday#811. It's not a bug in Handsontable but I'm leaving this issue for now as a reminder that we need to address this issue in Pikaday and update dependency.

**Comment by wojciechczerniak** [comment]
Might not be an issue anymore: https://github.com/facebook/create-react-app/issues/5272#issuecomment-433406678.
