### ISSUE TITLE
We're not able to edit data if its provided key has a dot.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5439]
### Description

We're not able to edit data if its provided key has a dot.

```
var dataObject = [{
  'a.b': 14,
  onedChng: 0.0092
}];
```
### Steps to reproduce

1. Open editor

Result: data is gone

### Demo

https://jsfiddle.net/handsoncode/bezjt7ps/

### Your environment
* Handsontable version: 6.0.1
_doesn't seem to be version related_
* Browser Name and version: Chrome 69
* Operating System: Windows 10

`[inform Gr# 19095]`

**Comment by AMBudnik** [comment]
We've discussed this internally and decided to do not allow to provide a dot inside a key as it is not recommended as a good practice.

**Comment by marsbomber** [comment]
@AMBudnik I am the one who sent you the bug report originally. 

Here's my use case. In the app I develop, the headers (column names) are user defined. There's no reason for me to block users to use names such as `no. of students`. 

In fact, Handsontable did the cell rendering despite the column name  includes dot. The only thing that's not working is how Handsontable seeds the editor with an initial value. Am I correct?

If you guys decide against supporting dots in column names, how should I go about my use case?

Thanks

**Comment by AMBudnik** [comment]
I am afraid that the only way to make it work right now is to replace the dot or create a parser which adds a different key for the object and replaces it for the use of `data` in Handsontable.

**Comment by marsbomber** [comment]
Hi @AMBudnik, thanks for the reply. Just to be clear, I need to display the headers with `dots` in the title string, for the columns that belong to headings with or without `dots`, I need to be able to edit the cell values.

Can you give me a gist to point me to the right way to achieve what I want to do?

**Comment by AMBudnik** [comment]
It is only a title of a column or row you shouldn't have any problems with that. Here is a working demo https://jsfiddle.net/handsoncode/xzorp6yj/

**Comment by kntmrkm** [comment]
I use handsontable via React.

If I pass a string with a dot in the columns option, I get the same problem as this issue.

Why don't you fix it to allow dot-included strings? Please let me know why.
It seems strange to go to the trouble of being aware of that when using HOT.

```
<Box {...rest}>
          <HotTable
            ref={ref}
            className={classNames(hotTableStyle)}
            data={data}
            rowHeaders={true}
            nestedHeaders={nestedHeaders}
            columns={columns}
            width="100%"
            height="auto"
            colWidths={100}
            stretchH="all"
            cells={renderCell}
```
@AMBudnik

**Comment by AMBudnik** [comment]
Hi @kntmrkm 

I will allow myself to open this thread and mark it for a re-review. I do not think that much has changed here but if I get the green light from the team I will update this thread.

**Comment by kntmrkm** [comment]
any update? @AMBudnik

**Comment by AMBudnik** [comment]
Hi @kntmrkm there are no further updates yet. But I will make sure to notify you when that changes.

**Comment by Yishaq13-getnuvo** [comment]
Hi @AMBudnik,

We are experiencing the same issues. In our use case, the keys are generated by our customers and sometimes they include '.' and we don't want to restrict them.

It would be great if you could share some insights if this fix is planned on your side or not.

**Comment by magierg** [comment]
still able to replicate the issue in editor : https://jsfiddle.net/pz05kgob/2/
