### ISSUE TITLE
Button in header doesn't work

### ISSUE THREAD

**Issue by mikro45** [handsontable/handsontable#5444]
### Description
If I put a button in a header I can click it, but nothing happens.

### Steps to reproduce
1. Put a button in a header.
2. Add the event listener to a button.
3. Click it.

### Demo
http://jsfiddle.net/tp1dck26/

### Your environment
* Handsontable version: 6.0.1
* Browser Name and version: Chrome 69
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @mikro45 

the event of a button click is stolen by the table, but you can use the click event of the element via `beforeOnCellMouseDown` event. Here's a demo http://jsfiddle.net/handsoncode/bgsf4y0w/
