### ISSUE TITLE
Multi-column Sorting doesn't work with filtering

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5449]
### Description

Multi-column Sorting doesn't work with filtering.

### Steps to reproduce

1. Sort the column `B`
2. Open filters for the same column and uncheck `C-max Energi`

![gif](https://user-images.githubusercontent.com/10757813/46457965-7671a480-c7b4-11e8-9bb3-785388c18ec2.gif)

Result:
`C-max Energi` is still in the table but `Model 3` is gone (physical 0)

### Demo

https://jsfiddle.net/handsoncode/gnj4ve09/

### Your environment
* Handsontable version: `6.0.1`
* Browser Name and version: Chrome 69
* Operating System: Windows 10

Related https://github.com/handsontable/handsontable/issues/5112
Inform `GR # 19158`

**Comment by wszymanski** [comment]
Issue moved to [handsontable/handsontable-pro #149](https://github.com/handsontable/handsontable-pro/issues/149) via [**ZenHub**](https://www.zenhub.com/)
