### ISSUE TITLE
can we covert column data as row data in handsontable 

### ISSUE THREAD

**Issue by rsurendar** [handsontable/handsontable#545]

**Comment by AlexanderAA** [comment]
That would be an awesome feature, I guess. I use that all the time. Can someone with enough knowledge about hansontable internals at least describe what would be required to add the feature?

**Comment by bdarwin** [comment]
This would be a great feature to have. If it is just plain data then it's fine. But when we have cell properties attached to each column then it is giving us headaches to transpose data along with cell props.

**Comment by AMBudnik** [comment]
@AlexanderAA http://jsfiddle.net/1cwdLbcm/ maybe this example would help

**Comment by bdarwin** [comment]
May be I commented in a wrong thread. 
But as I explained plain data is fine.  
For example we have column headers attached to configuration and let's say I want to switch the orientation means I want to transpose the table in such a way that column headers become row headers and data is displayed accordingly.
