### ISSUE TITLE
Editor top offset incorrect when using preventOverflow with set height

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#5453]
### Description

(Running on `develop` branch)
Having `preventOverflow` set to `horizontal` and having a set height on the table causes editor top offset to be incorrect when scrolling veritcally. Related to #5073.

### Steps to reproduce

1. `preventOverflow` set to `horizontal` and have a set `height`
2. Scroll vertically
3. Open editor

### Your environment
* Handsontable version: 6.0.1 (develop)
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
I'm happy to inform that we've fixed the issue in v `7.0.0`. Thank you again for your feedback, Jeremy.
