### ISSUE TITLE
Column with formulas doesn't filter properly

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5455]
### Description

Bug reported at https://forum.handsontable.com/t/formula-column-doesnt-filter/2451/3

### Steps to reproduce

1. Open filters and clean the `filter by value`
2. Choose `6030` and confirm

Result:
We should get `6030` value in a row but the table is empty.

### Demo

https://jsfiddle.net/handsoncode/yhzgtLb0/

### Your environment
* Handsontable version: `6.0.0`
_doesn't seem to be version related_
* Browser Name and version: Chrome 69
* Operating System: Windows 10

_inform Zen 26605, 26992_

**Comment by aninde** [comment]
A bug is still replicable in `8.0.0-rc1` v. https://jsfiddle.net/aninde/m0fjap76/

**Comment by AMBudnik** [comment]
This issue is still replicable using v 8.0.0.
Here's an updated demo https://jsfiddle.net/uy0Ldv8s/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Still broken in v9 https://jsfiddle.net/z8uwtsv4/

**Comment by HakanAkkurt** [comment]
Is there any solution for this bug?

**Comment by AMBudnik** [comment]
Hi @HakanAkkurt 

This issue was closed as a part of the bigger scope of the project reported here https://github.com/handsontable/handsontable/issues/8511 

I will notify you once we solve it.

**Comment by AMBudnik** [comment]
It works the same in the latest version v11 https://jsfiddle.net/94fnmu21/3/

**Comment by aninde** [comment]
This issue will be fixed by the upcoming v12. 
Working demo https://jsfiddle.net/Lk2fbr6q/

**Comment by AMBudnik** [comment]
Thanks, guys! I'm closing this issue as solved in v12.

For everyone who is tracking changes to this topic please check our release notes https://handsontable.com/docs/release-notes/#_12-0-0 and the migration guide https://handsontable.com/docs/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls
