### ISSUE TITLE
Some column get shown while using `hiddenColumns` and moving columns

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5456]
### Description

Some column get shown while using `hiddenColumns` and moving columns

### Steps to reproduce

1. When we move column `M` between `P` and `Q` the `O` column is shown

### Demo

https://jsfiddle.net/handsoncode/dtqzr4jL/

### Your environment
* Handsontable version: `6.0.1`
doesn't seem to be version related
* Browser Name and version: Chrome 69
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
I just got a hint from our user

> seems that when ever a column is moved or frozen, the hidden column indexes are not updated.

**Comment by wojciechczerniak** [comment]
#5598 has a better example. The column is not shown, our dynamic titles make that confusion. It's clearer with #5598 screencast.

Duplicate of #5598

**Comment by AMBudnik** [comment]
Referenced issue solved in v 8.0.0
