### ISSUE TITLE
Some cells is losing their formulas when there are merged cells in the same sheet

### ISSUE THREAD

**Issue by dbucardi** [handsontable/handsontable#5459]
### Description
Some cells is losing their formulas when there are merged cells in the same sheet.

### Steps to reproduce
1. Create a sheet that contains formulas and merged cells
2. Change the values to update the cells with formulas
3. Check that some cells around the merged cell did not update the values

### Demo
http://jsfiddle.net/zs3y9L52/

![bug-formulas-and-merged-cells](https://user-images.githubusercontent.com/34770114/46557864-b70b1400-c8c1-11e8-8f3f-4f1ca2f412dd.gif)

### Your environment
* Handsontable version: 5.0.2
* Browser Name and version: Chrome
* Operating System: Mac OS

**Comment by AMBudnik** [comment]
Thank you for sharing the example. I have replicated the issue with the latest version (`6.0.1`) as well. The bug doesn't seem to be connected to any version of the software.

**Comment by fencygu** [comment]
this bug modify below, I modify the handsontable.js can use . 
@AMBudnik I can't commit,
plugins\mergeCells\mergeCells.js
223 line
//const dataAtRange = this.hot.getData(...populationDataRange);
modify to get sourceData:
const dataAtRange = this.hot.getSourceData(...populationDataRange);

380 line
//clearedValue = this.hot.getDataAtCell(mergeParent.row, mergeParent.col);
modify to get sourceData:
clearedValue = this.hot.getSourceDataAtCell(mergeParent.row, mergeParent.col);

**Comment by AMBudnik** [comment]
I have narrowed the bug here https://github.com/handsontable/handsontable/issues/6359

Please feel free to share any comments If I missed anything.
