### ISSUE TITLE
autocomplete is inconsistent in treatment of angle brackets in option text

### ISSUE THREAD

**Issue by diana-seattle** [handsontable/handsontable#547]
I need to display some literal text (not an html tag) within angle brackets within the list of autocomplete options, such as: 

        aaa <mytext> bbb

When the cell contains no text, the option text displays fine, but if the cell does contain text, then the option text displays as:

        aaa bbb

I've tried escaping the angle brackets, but then the behavior is worse.  The escaped text appears in the option list when the cell is empty, and when the cell contains text, the unescaped text appears for only the left bracket.  And when the user selects the option, the escaped angle brackets appear in the cell.

**Comment by AMBudnik** [comment]
Actually in 0.13.1 I'm using, if you type 

```ccc <mytext> ddd```

as one of autocomplete values, the prompt you will get is 

```ccc ddd```

 but the end value which appears after chosing 

```ccc ddd``` 

from the autocomplete list is 

```ccc <mytext> ddd```
