### ISSUE TITLE
How to bind JSON data to dropdown?

### ISSUE THREAD

**Issue by ChetanChaudhari03** [handsontable/handsontable#5476]
### Description
I have JSON object data for Dropdown type. That have ID and Name property these property want to bind to dropdown but when I bind data to dropdown using source property [object object ] that should be show on the screen when editing that cell.

### Steps to reproduce

1.create handsontable grid
2.bind data
3.bind column and set some column as dropdown and provide JSON object with ID and Name

### Demo

https://jsfiddle.net/chetanchaudhari03/c2ovughd/5/

### Your environment
* Handsontable version: CDN
* Browser Name and version: Chrome/IE/Firefox
* Operating System:Windows 8/ Windows 7/ Windows 10 / any

**Comment by AMBudnik** [comment]
Hi @ChetanChaudhari03 

a dropdown cell type source has to be a one-dimensional array. You'd need to parse the JSON.

**Comment by ChetanChaudhari03** [comment]
sorry but I have value & text pair data in JSON object. What comes from main object that is value & that value should be match with JSON object of dropdown. So can you help me to set this JSON object with dropdown

**Comment by ChetanChaudhari03** [comment]
Please help me to bind JSON object to dropdown with name & value pair.

**Comment by AMBudnik** [comment]
I am sorry but we do not support a key & value pairs yet.

**Comment by ChetanChaudhari03** [comment]
How much time required for develop. We are thinking to buy licences.

**Comment by AMBudnik** [comment]
We have this on our to-do list, but haven't schedule or review it yet. Unfortunately, I do not know how long it can take to develop this feature. 
We have been asked to develop it a couple of times but it is a change that requires some ground adjustments so we have hesitated to do it.
