### ISSUE TITLE
paste from spreadsheet append extra CRLF in the cell

### ISSUE THREAD

**Issue by sawke28** [handsontable/handsontable#5478]
### Description
when copy and paste multiple row from googlespread sheet, extra CRLF is appended automatically in cells except last cell.

### Steps to reproduce
1. copy rows from google spreadsheet 
2. paste handsontable
3.

### Demo
https://drive.google.com/open?id=1yxfWlA5RJ7KYcoadJI2LkVgw0nI92Ym1

### Your environment
* Handsontable version:6.01
* Browser Name and version: chrome 69.0.3497.100
* Operating System: win10

**Comment by AMBudnik** [comment]
Hi @sawke28 

this issue has been reported at https://github.com/handsontable/handsontable/issues/5330 and will be solved with this epic https://github.com/handsontable/handsontable/issues/4931 (possibly in October).
