### ISSUE TITLE
Mobile editor opens all the time (on click and scroll)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5479]
### Description

Just the opposite situation to https://github.com/handsontable/handsontable/issues/4538
I got a hint that it might be related to the IME editor.

### Steps to reproduce

1. Open https://docs.handsontable.com/pro/6.0.1/demo-scrolling.html on any mobile device and scroll.

### Your environment
* Handsontable version: 6.0.1
* Browser Name and version: Mobile Safari/ Chrome
* Operating System: iOs/ Android

**Comment by jandom** [comment]
@AMBudnik many thanks for the fix!

Is there any demo page (like the https://docs.handsontable.com/pro/6.0.1/demo-scrolling.html above) where we can go and scroll to verify that this is working?

**Comment by tom-elliott** [comment]
Hey! Product manager from Labstep here. Thanks for working on this. Unfortunately, this fix doesn't work on Android. We have tried it within our own app and on the demo page (https://docs.handsontable.com/pro/6.0.1/demo-scrolling.html)

Devices and operating system:

Google Pixel 3, Android 9

Huawei MediaPad T3 7, Model number BG2-W09, Android version 6.0
