### ISSUE TITLE
persistentState: ManualColumnMove is only attribute applied when manually running 'persistentStateSave'

### ISSUE THREAD

**Issue by pwentz** [handsontable/handsontable#5480]
### Description
When using `persistentStateSave` to manually save the table state, the only state that gets applied to the rendered table is `manualColumnMove`, regardless of whether the `render` method is called after each save.

### Steps to reproduce
1. Visit [this fiddle](http://jsfiddle.net/rhcfjqsn/22/)
2. If there are any previously saved settings, make sure to press the `clear` button to wipe your `localStorage`
3. Make any sort of changes to the table that would be persisted. Try clicking on a column header to apply a sort. Resize some of the column widths. Make sure to actually move columns around!
4. Click the `Save` button to manually save the preferences.
5. Now refresh the page. Notice that the only change that seems to be applied is the order of the columns.
6. Refresh the page again. Now you will notice that the rest of the changes are appropriately applied.

### Demo
http://jsfiddle.net/rhcfjqsn/22/

**Comment by AMBudnik** [comment]
Thank you for sharing the issue. I have replicated it.

**Comment by AMBudnik** [comment]
Please update to `7.4.2` http://jsfiddle.net/AMBudnik/6nmv879p/ - the issue is fixed.
