### ISSUE TITLE
The first row was mistakenly deleted after the sort operation

### ISSUE THREAD

**Issue by bxfxf** [handsontable/handsontable#5509]
### Description

The first row was mistakenly deleted after the sort operation

### Steps to reproduce

1.First click on the column header, order, 
2.the second click on the column header, reverse order, 
3.the third click on the column header, cancel the sorting, 
4.right click on the 2nd row (or 3rd row), then the 1th row will be deleted

### Demo

https://jsfiddle.net/tvh4p7jz/

### Your environment
* Handsontable version:5.0.2 /6.0.1
* Browser Name and version: chrome 68
* Operating System:win 10

**Comment by wojciechczerniak** [comment]
Related issue #5446 #5510

**Comment by AMBudnik** [comment]
To be checked with https://github.com/handsontable/handsontable/issues/5446

**Comment by AMBudnik** [comment]
Welcome @bxfxf 

can you update to 6.2.0 and check if the issue is still there?
We've just fixed a very similar issue at https://github.com/handsontable/handsontable/issues/5446

**Comment by bxfxf** [comment]
It has been fixed! Thank you!
