### ISSUE TITLE
Possibility to remove/disable cell highlight?

### ISSUE THREAD

**Issue by Darkvater** [handsontable/handsontable#551]
Would it be possible to add an option to handsontable that doesn't do any cell highlighting, selection, etc. and decouple from the mouse events?

Basically a read-only (disabled) version that is just a table, but with the handsontable plusses of custom renderers, layout, dynamic update.

**Comment by phasjim** [comment]
Neither of those worked for me, but what I did below worked pretty well.

onSelection: function (r, c, r2, c2) { // readOnly cannot be selected
                        if (this.view.settings.columns[c].readOnly) {
                            this.deselectCell();
                        } 
                    }

**Comment by phasjim** [comment]
Neither of those worked for me, but what I did below seems to work!

```
onSelection: function (r, c, r2, c2) { // readOnly cannot be selected
                        if (this.view.settings.columns[c].readOnly) {
                            this.deselectCell();
                        } 
                    }
```

**Comment by MetaMemoryT** [comment]
:+1: this should be re-opened as their is obviously interest in non select-able cells.

Their should be a more declarative way to disable cell selection.

**Comment by budnix** [comment]
Maybe this options is what you want? see http://docs.handsontable.com/0.15.0-beta6/Options.html#disableVisualSelection

**Comment by MetaMemoryT** [comment]
Ah, thanks.

Didn't see that.

**Comment by compwright** [comment]
In more recent versions (I'm on v0.31), you'll need to use `onAfterSelectionEnd` instead of `onSelection`.

**Comment by compwright** [comment]
If you have some columns that are read-only and you want to show cell selections for only the cells that are editable, do this:

```js
beforeGetCellMeta: function(r, c, props) {
    if (!props.readOnly && props.disableVisualSelection === true) {
        props.disableVisualSelection = 'area';
    }
};
```

**Comment by powtok** [comment]
@codename- I got an idea.
`.handsontable .wtBorder {
  display: none !important;
}`
