### ISSUE TITLE
After the sort operation, modifying the values of some rows triggers the previous row data to be cleared

### ISSUE THREAD

**Issue by bxfxf** [handsontable/handsontable#5510]
### Description

After a sort operation, modifying the value of line 12th triggers the first 3 rows of data to be erased by mistake.

### Steps to reproduce

1.  open https://jsfiddle.net/k9qvd43t/
2. Set the value of line 12th
3. The first 3 rows of data will be erased by mistake.

### Demo

https://jsfiddle.net/k9qvd43t/

### Your environment
* Handsontable version:5.0.2 /6.0.1
* Browser Name and version:chrome 68
* Operating System:win 10

**Comment by wojciechczerniak** [comment]
Related issue #5446

**Comment by AMBudnik** [comment]
Thank you for reporting @bxfxf 

I will check it out once we complete the task at https://github.com/handsontable/handsontable/issues/5446 scheduled for November

**Comment by AMBudnik** [comment]
Hey @bxfxf 

Please check that one as well. It should also be fixed with
https://github.com/handsontable/handsontable/issues/5446

**Comment by bxfxf** [comment]
It has been fixed! Thank you!
