### ISSUE TITLE
Hondsontable-PRO filter not working with cells function

### ISSUE THREAD

**Issue by akshaykumarv** [handsontable/handsontable#5512]
### Description
I am applying custom renderer to each cell using the cell function. Along with that I also use filter feature from the pro edition. But we actually apply filters I am getting **"Uncaught TypeError: Cannot read property '0' of undefined"** in the cells function where I get cell value for each cell to determine the custom renderer that I want to use.

I am able to reproduce them in the following jsfiddle link.
### Steps to reproduce

1. Define cells function in hotSettings and get cell value for each row, col. 
2. Apply any filter on the table.
3.

### Demo

https://jsfiddle.net/7q2yz5du/

### Your environment
* Handsontable version: handsontable-pro/vue 3.0.0
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @akshaykumarv 

I have left your report at https://github.com/handsontable/handsontable-pro/issues/158 and replied. As there is no point of keeping two the same tickets I will close this one
