### ISSUE TITLE
Can't keep cell style and " numericFormat" at the same time

### ISSUE THREAD

**Issue by graceliu4709** [handsontable/handsontable#5513]
### Description

Like the demo, i cannot keep the cell style and "numericFormat" at the same time, but i need to achieve that and i don't know how. In my real project i change the style and cell type dynamically.
So i wonder if you could give me any advice?
### Demo

https://jsfiddle.net/GraceLiu/xoc3ezqL/1/

### Your environment
* Handsontable version: v6.0.1
* Browser Name and version: chrome 69
* Operating System: windows

**Comment by AMBudnik** [comment]
Hi @graceliu4709 

you are using the `TextRenderer` in the `15` line.

Here is a version with `NumericRenderer` https://jsfiddle.net/u1hqwr2g/

**Comment by graceliu4709** [comment]
Thanks a lot. That perfectly solve my problem!

**Comment by AMBudnik** [comment]
Great :) Thank you for confirmation
