### ISSUE TITLE
Add the HiddenRows-related hooks to pluginHooks.js

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#5522]
### Description
Related to handsontable/handsontable-pro#163.

The new hooks:
- beforeHideRows
- afterHideRows
- beforeUnhideRows
- afterUnhideRows
- beforeHideColumns
- afterHideColumns
- beforeUnhideColumns
- afterUnhideColumns

need to be added to `pluginHooks.js`.

**Comment by subashdbc** [comment]
Hi Guys,
Waiting for these new hooks to be released :)

**Comment by AMBudnik** [comment]
Hey @subashdbc 

it just happened. Please update to `7.0.0` to use the new hooks :)

**Comment by subashdbc** [comment]
Hi @AMBudnik 

I am not sure If I have taken it correctly with regard to this release.
My thought [From Forum](https://forum.handsontable.com/t/collapsed-columns-summary/2845/2) was when we collapse and uncollapse the column we will get the indexes of hidden columns 
But it seems it doesn't get hooked when I collapse and uncollapse [JS Fiddle](https://jsfiddle.net/subashdbc/6u4pdLe0/7/)
Is it wrong or Am I missing something here? 
Thanks

**Comment by AMBudnik** [comment]
Thank you for mentioning that. As I was instructed collapsing uses hiddenColumns plugin only partially so it is never calling the hooks. However, we should further discuss this subject.

ps. here's a connected topic https://github.com/handsontable/handsontable/issues/4873
