### ISSUE TITLE
Pasting multiple columns does not add columns to table

### ISSUE THREAD

**Issue by matkus** [handsontable/handsontable#553]
Hello

I have another problem.
When i paste table from excel to handsontable, it does not add columns, if there are less than in copied data.
For example, if i have handsontable with 5x2 cells, and i copy 20x20 cells of data, it will add 20 rows, but only first 5 columns. On all tables i've checked on handsontable.com examples it added as many rows as i needed, but never added columns, on my own table it didn't do anything, but since it's my table, it's probably my own misconfiguration or something.
Of course if you'll set copy limit it should block me, but if i have default limit (1000x1000 acording to documentation), i should be able to paste 20x20 table without problems.

You can reproduce it in any table in examples. Just open excel, write any date (more columns, than in handsontable table), copy it and paste to table.

**Comment by AMBudnik** [comment]
Please check our updated [demo](http://handsontable.com/) it should satisfy your needs.
