### ISSUE TITLE
Copying a whole column only copies 1000 entries

### ISSUE THREAD

**Issue by lulezi** [handsontable/handsontable#5531]
### Steps to reproduce
1. Get a table with more than 1000 rows.
2. Click on header to select one whole column.
3. Copy.
4. Paste and scroll down to last entry.

### Demo
![copy-column-only-copies-1000-entries 2018-10-19 18_11_17](https://user-images.githubusercontent.com/870062/47230419-7388cd80-d3ca-11e8-8f25-67bc1134eb38.gif)

### Your environment
* Handsontable version: 6.1.0
* Browser Name and version: Chrome 70.0.3538.67 and Firefox 61.0.1
* Operating System: macOS 10.12.6

**Comment by cuongurus** [comment]
Hi @lulezi 
See the docs:
[https://handsontable.com/docs/6.1.0/CopyPaste.html#rowsLimit](https://handsontable.com/docs/6.1.0/CopyPaste.html#rowsLimit)

**Comment by lulezi** [comment]
Hi @cuongurus, thanks a lot! I was looking for this in https://handsontable.com/docs/6.1.0/demo-copy-paste.html but couldn't find it there.

**Comment by AMBudnik** [comment]
Thanks for your support @cuongurus :)
