### ISSUE TITLE
Clarify documentation on Undo/Redo

### ISSUE THREAD

**Issue by dmt0** [handsontable/handsontable#5532]
### Description
From https://handsontable.com/docs/6.1.0/UndoRedo.html :

> Note, that not all actions are currently undo-able. The UndoRedo plugin is enabled by default.

The question is, what is and what is not undoable as of now?

**Comment by AMBudnik** [comment]
You're right, we need to check what's going on in the code or try it out to know.

Changes that can be undone
* editing
* insert row/column
* remove row/column
* filtering

**Comment by dmt0** [comment]
Just looked at the code. Add to the list:
- cell alignment
- row move
- cells merge/unmerge

https://github.com/handsontable/handsontable/blob/master/src/plugins/undoRedo/undoRedo.js

**Comment by wojciechczerniak** [comment]
Moved to https://github.com/handsontable/docs/issues/3
