### ISSUE TITLE
[6.1.0+] Version 6.1.0 broke the 'cut' and 'copy' buttons in the context menu

### ISSUE THREAD

**Issue by astegmaier** [handsontable/handsontable#5535]
### Description
The upgrade from 6.0.1 to 6.1.0 appears to have broken the 'cut' and 'copy' buttons in the right-click menu.

### Steps to reproduce

1. Make sure you are using version 6.1.0, and have handsontable configured with `copyPaste = true` and `contextMenu = true`
2. Select some cells
3. Right click
4. Click 'cut' or 'copy'

Result: nothing happens.

### Demo
Here is a demo of the buttons working in version 6.0.1:
http://jsfiddle.net/astegmaier/mzyh56vr/

And here is a demo of the buttons broken in version 6.1.0:
http://jsfiddle.net/astegmaier/69gk2pxt/

### Your environment
* Handsontable version: 6.1.0
* Browser Name and version: I see the same results in the latest version of chrome, firefox, and edge.
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the report @astegmaier 

I have replicated the issue. That is a regression from 6.0.1

**Comment by swistach** [comment]
Hi @astegmaier 
Thank you! The fix is on the next release branch (6.1.1)

**Comment by swistach** [comment]
Hi @astegmaier,
Thank you! The fix is on the next release branch (6.1.1)

**Comment by AMBudnik** [comment]
Just released. Thank you @astegmaier  :)
