### ISSUE TITLE
Insert first row on empty sheet

### ISSUE THREAD

**Issue by awenger63** [handsontable/handsontable#5536]
### Description
I would like to insert fisrt row on empty sheet

### Steps to reproduce
In context menu, I always want to be able to insert row than I initialize this functionnality never disable
`"row_above": {disabled: function () {return false;}}`

But when you choice this menu, this error appear in version 5.0.2 on rowAboveItem function
 `TypeError: c[Math.max(...)] is undefined
`

### Your environment
* Handsontable version: 5.0.2

I test this, and it seem's to work !
`this.alter('insert_row', 0, 1, 'ContextMenu.rowAbove');`

Is it possible to change function like this
`callback: function callback(key, normalizedSelection) { var latestSelection = normalizedSelection[Math.max(normalizedSelection.length - 1, 0)]; if (typeOf latestSelection === 'undefined') { this.alter('insert_row', 0, 1, 'ContextMenu.rowAbove'); } else { this.alter('insert_row', latestSelection.start.row, 1, 'ContextMenu.rowAbove'); } },`

Thanks for your help

**Comment by AMBudnik** [comment]
Hi @awenger63 

You should not get any issues with the default context menu settings.

Can you share a demo where this issue can be replicable?

**Comment by melloware** [comment]
@wenger63 it looks like its working in this JSFiddle: https://jsfiddle.net/yp1jmkqt/

**Comment by melloware** [comment]
It looks like we are still having the issue but I can't figure out why.  Its definitely failing in the Javascript somwhere.

**Comment by AMBudnik** [comment]
Can you share a .zipped project where the issue can be replicable? I do not know how to help as long as the JSFiddle works as expected.

**Comment by melloware** [comment]
So this is the error I am seeing:
```
Uncaught TypeError: Cannot read property 'end' of undefined
    at Core.callback (sheet.js.jsf?ln=primefaces-extensions&v=6.3-SNAPSHOT:58571)
    at sheet.js.jsf?ln=primefaces-extensions&v=6.3-SNAPSHOT:57586
    at arrayEach (sheet.js.jsf?ln=primefaces-extensions&v=6.3-SNAPSHOT:1730)
    at CommandExecutor.execute (sheet.js.jsf?ln=primefaces-extensions&v=6.3-SNAPSHOT:57585)
    at ContextMenu.executeCommand (sheet.js.jsf?ln=primefaces-extensions&v=6.3-SNAPSHOT:57376)
    at Menu.<anonymous> (sheet.js.jsf?ln=primefaces-extensions&v=6.3-SNAPSHOT:57249)
    at sheet.js.jsf?ln=primefaces-extensions&v=6.3-SNAPSHOT:12261
    at arrayEach (sheet.js.jsf?ln=primefaces-extensions&v=6.3-SNAPSHOT:1730)
    at Menu.runLocalHooks (sheet.js.jsf?ln=primefaces-extensions&v=6.3-SNAPSHOT:12260)
    at Menu.executeCommand (sheet.js.jsf?ln=primefaces-extensions&v=6.3-SNAPSHOT:59011)
```
When when tracing into HandsonTable the error is here:

```javascript
function rowBelowItem() {
  return {
    key: KEY,
    name: function name() {
      return this.getTranslatedPhrase(C.CONTEXTMENU_ITEMS_ROW_BELOW);
    },
    callback: function callback(key, normalizedSelection) {
      var latestSelection = normalizedSelection[Math.max(normalizedSelection.length - 1, 0)];

      this.alter('insert_row', latestSelection.end.row + 1, 1, 'ContextMenu.rowBelow');
    },
    disabled: function disabled() {
      var selected = (0, _utils.getValidSelection)(this);

      if (!selected) {
        return true;
      }

      return this.selection.isSelectedByColumnHeader() || this.countRows() >= this.getSettings().maxRows;
    },
    hidden: function hidden() {
      return !this.getSettings().allowInsertRow;
    }
  };
}
```

On this exact line of code it says "end" is basically NULL.

```javascript
this.alter('insert_row', latestSelection.end.row + 1, 1, 'ContextMenu.rowBelow');
```

**Comment by AMBudnik** [comment]
Is there a way for you to share the code where I will be able to replicate it? It is hard to propose any solution when it works in the JSFiddle.

**Comment by melloware** [comment]
@AMBudnik I would say close this ticket until I can find a way to verify the problem.  I can always open another ticket in the future!

**Comment by AMBudnik** [comment]
Ok @melloware feel free to open a new ticket

**Comment by awenger63** [comment]
@AMBudnik Thanks for your help, hope @melloware can a find the solution.
