### ISSUE TITLE
[6.1.0+] The focus from input in a header is stolen

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5541]
### Description

The focus from input in a header is stolen

### Steps to reproduce

1. Try to type anything in a column input (Custom implementations > Filter as you type )

![gif](https://user-images.githubusercontent.com/10757813/47412523-4b072780-d76c-11e8-85dd-6d2a40ccec22.gif)

**Result**.
You need to be super fast to do it, as the focus is quickly stolen.

### Demo

https://handsontable.com/docs/6.1.0/demo-filtering.html

### Your environment
* Handsontable version: `6.1.0`+
works well in [6.0.1](https://handsontable.com/docs/6.0.1/demo-filtering.html)
* Browser Name and version: Chrome 70
* Operating System: Windows 10

inform `GR # 20068` and [forum](https://forum.handsontable.com/t/gh-5541-have-a-doubt-on-filter/2641) and [forum](https://forum.handsontable.com/t/gh-5541-attempting-to-enter-filter-criteria-after-sorting-only-allows-one-character-then-edits-field-below/2695) and [here](https://forum.handsontable.com/t/gh-5541-beforeoncellmousedown-problem/2745) and [forum](https://forum.handsontable.com/t/unable-to-edit-input-text-box-in-column-header/2868)

**Comment by AMBudnik** [comment]
Hey @AMBudnik 

Please check the updates on the issue. It is waiting to be merged. Should be ready for the new version.

**Comment by wojciechczerniak** [comment]
Should close #401 and #4082

**Comment by fengjac** [comment]
Hi @AMBudnik 
The issue is still in v6.2.2. When will it be resolved? Thank you very much!

**Comment by AMBudnik** [comment]
Hey @fengjac hopefully we'll fix it for the next release (6th of March).

**Comment by AMBudnik** [comment]
Hey @fengjac 

Hey! I just wanted to let you know that we've fixed the issue 
Please update to `7.0.0` to use it.
