### ISSUE TITLE
Autofill should have an option to skip hidden cells.

### ISSUE THREAD

**Issue by vk-sourcefuse** [handsontable/handsontable#5542]
### Description

Dragging in cells changing values of hidden cells also

### Steps to reproduce

: Video for steps : https://drive.google.com/file/d/1JrBwi9rkQsHZu2_GqT_6cdWaiXlJYp38/view

### Demo

https://jsfiddle.net/vaibhavsourcefuse/yhom40p9/

**Comment by AMBudnik** [comment]
Thank you for sharing. I think that the Autofill should have an option to skip hidden cells.

**Comment by AMBudnik** [comment]
Additionally to can try to use trimming instead. Here's a tutorial https://handsontable.com/docs/6.1.1/demo-trimming-rows.html

**Comment by vk-sourcefuse** [comment]
Thanks a lot @AMBudnik  , It is working perfectly :+1:

**Comment by AMBudnik** [comment]
Great :) I'm glad that it helped.

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for sharing. I hope that we'll be able to publish it soon.

**Comment by wojciechczerniak** [comment]
Not a feature. We had a bug that should be fixed with #5957
