### ISSUE TITLE
[6.1.0+] Copy/Paste read/write clipboard incorrectly

### ISSUE THREAD

**Issue by cuongurus** [handsontable/handsontable#5544]
### Description

Copy a cell with value == 0, NaN or null then paste empty to other cell or excel.
I believe function arrayToTable(input) with below lines of code cause to this issue:
```js
    for (var column = 0; column < columnsLen; column += 1) {
      tempElement.innerText = '' + (rowData[column] || '');

      columnsResult.push('<td>' + tempElement.innerHTML + '</td>');
    }
```
### Your environment
* Handsontable version: 6.1.0+
* Browser Name and version: Chrome 70
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
@cuongurus You're right, `0` is a valid value. But is there a use case for `NaN` and `null` that you are mentioning them?

**Comment by cuongurus** [comment]
@wojciechczerniak, hard to describe my use case but fix value == 0 is enough. I will use string "NaN" instead. Thanks!

**Comment by AMBudnik** [comment]
Welcome @cuongurus 

I am more than happy to say that the fix is published!
