### ISSUE TITLE
Context menu "Remove rows" disabled issue

### ISSUE THREAD

**Issue by lgpage** [handsontable/handsontable#5549]
### Description
With the context menu limited to editing rows only ('row_above', 'row_below', and 'remove_row') and not columns I would expect the Ctrl+A shortcut to select all cells and have the "Remove rows" enabled on the context menu however the "Remove rows" option is disabled.

### Steps to reproduce
1. Select any cell
2. Push Ctrl+A
3. R-click to get context menu
4. Remove rows is disabled

![hot-ctrl-a-remove-rows-disabled](https://user-images.githubusercontent.com/1577821/47671553-7351b480-dbb8-11e8-9e39-b2c577d6498d.gif)

### Demo
https://jsfiddle.net/vg45pcmg/3/

### Your environment
* Handsontable version: 6.1.x
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
The options are disabled as the headers are also selected.
You can overwrite the `CMD/CTRL` + `A` shortcut via [`afterDocumentKeyDown` hook](https://handsontable.com/docs/6.1.1/Hooks.html#event:afterDocumentKeyDown) to get the rows (only)
