### ISSUE TITLE
TABbing between inputs does not work an expected

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5551]
### Description

I am using a demo from our examples https://handsontable.com/docs/6.0.1/demo-select.html
Just added more columns to make the bug more visible.

### Steps to reproduce

1. TAB between the inputs in headers

Eventually, you get lost with the focus.

![gif](https://user-images.githubusercontent.com/10757813/47706161-d713c600-dc28-11e8-88c7-7e441124181e.gif)

And further TABbing won't scroll you anywhere.

### Demo

https://jsfiddle.net/bx6h4dwf/

### Your environment
* Handsontable version: 6.0.1
Next version has a `regression` bug
* Browser Name and version: Chrome 69
* Operating System: Windows 10

**Comment by lucashtc** [comment]
A similar problem happens when I click on a column ahead and try to do the search it jumps to another alone

**Comment by AMBudnik** [comment]
Still broken and it doesn't seem to be related to any version.

**Comment by AMBudnik** [comment]
Works the same on latest Chrome 79 and Handsontable 8.0.0-beta1 https://jsfiddle.net/0jb6eso2/

**Comment by AMBudnik** [comment]
Works the same in `8.0.0-beta2-rev18` https://jsfiddle.net/n2ax6zcg/

**Comment by AMBudnik** [comment]
Hi @lucashtc 

That example in the documentation was not fully suitable for a larger number of columns. We have eventually removed it from the docs.

Please contact me if you are still using this type of search at support@handsontable.com.
