### ISSUE TITLE
Error: net::ERR_ADDRESS_INVALID at http://0.0.0.0:7992/test/E2ERunner.html

### ISSUE THREAD

**Issue by jdmcnair** [handsontable/handsontable#5558]
### Description

Running tests via `npm run test:e2e` should succeed. Instead I'm getting an "ERR_ADDRESS_INVALID" error.

### Steps to reproduce

1. Run `npm run test:e2e`.
2. Be on windows 10 (not totally sure if that's significant, but I'm guessing that's the factor, since this seems to be working for others).
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 6.1.1
* Browser Name and version: phantomjs
* Operating System: Windows 10

**Comment by budnix** [comment]
Merged into develop branch. Thanks for PR!
