### ISSUE TITLE
Slow removing large number of rows with manualRowMove: true

### ISSUE THREAD

**Issue by emilschutte** [handsontable/handsontable#5561]
First off, thanks for your great work on Handsontable.

### Description
When I remove a large-ish number of rows from a table using `updateSettings` with a new `data` property, it takes a long time (~20s for ~90k rows, for example).  I'm finding the time is spent in `arrayMapper`'s `removeItems` method.

https://github.com/handsontable/handsontable/blob/bb6871349289add4f4692ebe6627c408b6bce251/src/mixins/arrayMapper.js#L77

I might be missing something, but it seems like it would be possible to make this run faster.  For example, it's not clear to me that the function call, slice and concat overhead are necessary.  I don't like premature optimization but it seems like removing many rows at once is not an unusual use case (for us, this is needed when we remove many rows from view when collapsing a tree structure).

This only happens when `manualRowMove` is configured true.

### Steps to reproduce

1. Initialize a table with 100k rows and `manualRowMove: true`
2. Call `updateSettings` with `data` a new array with many fewer rows (e.g. 10k vs the original 100k)
3. Wait for the table to finish re-rendering

### Demo

https://jsfiddle.net/bm1zetnd/

### Your environment
* Handsontable version: 6.1.1
* Browser Name and version: Chrome 70.0.3538.77 (Official Build) (64-bit)
* Operating System: Mac High Sierra

Let me know if I can provide any other info to help.  Thanks.

**Comment by AMBudnik** [comment]
Thank you for reporting and investigating this case @emilschutte 
Definitely, it takes too long to get the new dataset.

**Comment by emilschutte** [comment]
Thanks @AMBudnik.  Would you be open to a small PR that just speeds up this one function using a `for` loop?

**Comment by AMBudnik** [comment]
Sure @emilschutte! :)

**Comment by AMBudnik** [comment]
Hey @emilschutte 

I'm happy to spread the good news. This issue has been fixed in the newly released version - 6.2.1

Again thanks for sharing :)

**Comment by emilschutte** [comment]
Thank you!
