### ISSUE TITLE
Multiple selection stacks ranges

### ISSUE THREAD

**Issue by brianxautumn** [handsontable/handsontable#5570]
### Description
Should multiple selection allow selection of duplicates? When ctrl clicking on rows or columns it keeps creating overlapping selections. Shouldn't the behavior be to deselect row/column if already selected? The way it is now its not possible to deselect from a multiple selection.

### Steps to reproduce

1. Open a demo with selection mode multiple
2. control click a row or column
3. repeat on same row/column
4. Selection keeps stacking

### Demo
https://handsontable.com/docs/6.1.1/demo-selecting-ranges.html

**Comment by AMBudnik** [comment]
Hi @brianxautumn 

multiselection creates layers. That is why you should be able to set the same or corresponding range of cells in another click.

**Comment by brianxautumn** [comment]
Is there a way to disable the layers, or allow users to deselect a cell out of the selection?

**Comment by AMBudnik** [comment]
Theoretically, it should, but I did not try it yet. As I believe you'd need to select the area once again.
