### ISSUE TITLE
hiddenColumns doesn't work with columnSorting

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#5571]
### Description
hello,
i try to hide a column
with
hot.getPlugin('hiddenColumns').hideColumns([0]);
hot.render(); 

and columnSorting to true

if i set columnSorting  to false, it works

regards
jm
### Demo
https://jsfiddle.net/jeanmarc/bjwzf6so/2/

### Your environment
* Handsontable version: PRO 6.1.1
* Browser Name and version:Chrome 70
* Operating System:windows 10

**Comment by AMBudnik** [comment]
This works fine in `6.1.1` https://jsfiddle.net/handsoncode/decn2hq5/ where we previously replicated the issue might it be related to a browser?
@aninde please check it on your device as well

**Comment by aninde** [comment]
@AMBudnik you're right, That demo work well in `6.1.1`, `7.1.1` and `8.0.0-rc1`. However, demo from @wszymanski doesn't even with a new index mapper. `Update settings` is still problematic even with new **index mapper**. 

**Demo**
ver. 8.0.0-rc1 https://jsfiddle.net/aninde/najfhc5w/

**Comment by AMBudnik** [comment]
### Case 1

Main issue where we cannot have columnSorting enabled to hide a column

7.4.2 https://jsfiddle.net/ufcmhegy/ (broken)

8.0.0-beta1 https://jsfiddle.net/ufcmhegy/1/ (**solved**)

8.0.0-beta2-rev1 https://jsfiddle.net/ufcmhegy/2/ (still working correctly)

### Case 2

Calling empty object in updateSettings after hiding a column.

7.4.2 https://jsfiddle.net/4tjzhrpm/ (broken)

8.0.0-beta1 https://jsfiddle.net/yzs83bru/ (broken)

8.0.0-beta2-rev2 (7.05 10:07) https://jsfiddle.net/yzs83bru/1/  (still broken)

**Comment by wojciechczerniak** [comment]
Case 2 is a sepparate issue #4121

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 

Our 8.0.0-beta2 fixes that issue. 
(We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.)

Please let me know it it works in your project.

Full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2

**Comment by AMBudnik** [comment]
> Case 2 is a sepparate issue #4121

Case 2 has been redirected here and now it is redirected back to its original post, where it is one of the two issues - one is solved and second is not. To remove this circular connection I've moved Case 2 (from this post) and https://github.com/handsontable/handsontable/issues/4121#issuecomment-638555212 (which relates to the same scenario) to a new Github issue https://github.com/handsontable/handsontable/issues/7165

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 

we can officially close this issue as solved in v 8.0.0 https://jsfiddle.net/tdup5867/
