### ISSUE TITLE
Auto Fill Down should increment when a number

### ISSUE THREAD

**Issue by tdlovejoy** [handsontable/handsontable#5574]
### Description
I would like it if the autofill down would increment a number or if the end of the string is a number increment down.  for exmaple, 1,2,3,...  or ID1, ID2, ID3

### Steps to reproduce
1. Put 1 in the first row
2. Drag the Autofill down

### Your environment
* Vue wrapper version:  3.0
* Handsontable version: 6.0
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by tdlovejoy** [comment]
Is there anyway that I can extend the current AutoFill to implement my own version?

**Comment by tdlovejoy** [comment]
do you know how to do this using the vue wrapper?  or is it possible?  I tried a couple different version but it never seems to catch the event

```
 this.$refs.hotTableComponent.hotInstance.hooks('hook:beforeAutofill', function (start, end, data) {
      console.log('beforeAutofill')
      this.initialSelection = data
    })
    this.$refs.hotTableComponent.hotInstance.hooks('hook:beforeAutofillInsidePopulate', function (index, direction) {
      console.log('beforeAutofillInsidePopulate')
      this.direction = direction
    })
    this.$refs.hotTableComponent.hotInstance('hook:beforeAutofill', function (start, end, data) {
      console.log('beforeAutofill')
      this.initialSelection = data
    })
    this.$refs.hotTableComponent.hotInstance('hook:beforeAutofillInsidePopulate', function (index, direction) {
      console.log('beforeAutofillInsidePopulate')
      this.direction = direction
    })
```

**Comment by tdlovejoy** [comment]
Let me know why this is not the right way to go, I am intercepting the beforeAutofill event, and then I am filling the data array with the information I want to get copied into the cells.  Code is below

`this.$refs.hotTableComponent.hotInstance.addHook('beforeAutofill', function (start, end, data) {
      console.log('beforeAutofill')
      for(var k = 0; k <= (end.col - start.col); k++) {
        var str = data[0][k],
          matches = str.match(/\d+$/),
          number;

        if (matches) {
          let init = parseInt(matches[0], 10) + 1
          let strInit = data[0][k].replace(matches[0], '')
          data[0][k] = strInit + init
          for(var i = 1; i <= (end.row - start.row); i++) {
            if(!(data[i])) {
              data.push(data[0].slice())
            }
            data[i][k] = strInit + (init + i)
          }
        }
      }
    })
`

**Comment by dmt0** [comment]
The way I did it is `HOT.setDataAtCell(newChanges);` and I did this in `afterChange`, cause I figured otherwise my changes would be overwritten by default ones. So basically I'm making sure that I'm writing into the cells after autofill did the write.

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for sharing. I hope that we'll be able to publish it soon.

**Comment by azal-io** [comment]
Hi,

Any updates???

**Comment by azal-io** [comment]
jexcel has this feature already and also x-spreadsheet. It seems all of the data grid / spreadsheet ones have this implemented. Why it has been not added to Handsontable?
Thanks

**Comment by pnowak** [comment]
Hi @azal-io 

In recent days our developers work on the stable release of 8.0.0 version. 

We dedicated 2019 and the first half of 2020 to refactor & improve Handsontable. Only with a fast-working and stable engine, we'll be ready to develop new functionalities. 

The further bigger features for us are finish eco-renderer and add accessibility.
So, unfortunately,  I don't think that this feature is in our to-do list in the near future.

**Comment by allen0977** [comment]
I implemented a solution (using Angular but it should be the same everywhere).   I needed to use lodash.cloneDeep to make an unmodified version of data, otherwise it gets manipulated and didn't work correctly.

I chose to ONLY look at the column I named "fraction", but it'd be pretty easy to extend this to a property of the column or something like that.    I also allow the user to do simple patterns (start with 2 even numbers or multiples of 3, etc)

Hopefully this helps someone else out there.


beforeAutofill: (start, end, data) => {
                // Needs to clone data to know starting value, data array is modified for values output (no return)
                const origData = cloneDeep(data);

                // Determine left-to-right or right-to-left
                let updateStartCol: number, updateEndCol: number;
                if (start.col <= end.col) {
                    updateStartCol = start.col;
                    updateEndCol = end.col;
                } else if (start.col > end.col) {
                    updateStartCol = end.col;
                    updateEndCol = start.col;
                }

                for (let column = 0; column <= updateEndCol - updateStartCol; column++) {
                    // ONLY do autoincrement on FRACTION field (name of property, not header)
                    if (this.newSubmissionTableInstance.colToProp(updateStartCol + column) === 'fraction') {
                        let incr = 1;
                        if (origData.length > 1) {
                            // Allow for even digit or simple patterns
                            incr = parseInt(origData[1][0], 10) - parseInt(origData[0][0], 10);
                        }
                        for (let row = 0; row <= end.row - start.row; row++) {
                            if (!data[row]) {
                                // COPY all original columns selected into data[row] before modifying contents below
                                data[row] = origData[0].slice();
                            }
                            // MODIFY the fraction column.   incr * length handles if more than 2 rows are highlighted for patterns
                            data[row][column] = parseInt(origData[0][column], 10) + row * incr + incr * origData.length;
                        }
                    }
                }
            },
