### ISSUE TITLE
Removing rows is not shifting cell meta data

### ISSUE THREAD

**Issue by kirliam** [handsontable/handsontable#5577]
### Description
After removing a row, cell meta data is not being shifted as expected.

### Steps to reproduce
JSFiddle: https://jsfiddle.net/92wLg3oq/1/
Note that the 5th row has green background, since I added the green className to the cell meta data.
Now remove any of the first 4 rows. The green cell is still in the 5th row, it should be moved to the 4th row!

### Your environment
* Handsontable version: 6.1.1
* Browser Name and version: Chrome 70.0.3538.77
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @kirliam 

in your code, you attach a class to a cell with an index of `4`. If you would like it to behave dynamically I recommend using `cells` method. Here's a demo https://jsfiddle.net/og5ctkeL/

**Comment by kirliam** [comment]
Hello @AMBudnik 
Yeah, I know the cells method, but your example behaviour is exactly the same as the one described in my issue! It's not shifting the 
In my example, I have the cell (4,0) with background  in red! So, if I remove or insert a row between 0 and 4 indexes, I would expect the red background to be shift one UP or DOWN. In other words, the red background should stay in the row with name Pierre Barbaut. That would be the logical and expected behaviour in a excel like grid!

**Comment by AMBudnik** [comment]
OK I see I see the difference now. Do you sort it as well? How it should behave after sorting? Can we attach the green background to the value of `5`?

**Comment by kirliam** [comment]
Yeah, the background colors is related to the row data, so you can attach it if the id is 5.

**Comment by AMBudnik** [comment]
Ok, so this should work https://jsfiddle.net/p0quymgn/
I used the `getDataAtCell` method but only on the `id` column.

**Comment by kirliam** [comment]
That's it.
  So I was misunderstanding the way cell meta data was stored internally. If I set some property in the 4th metadata row, it'll be kept there no matter new rows are inserted or removed!
  My use case here is a CRUD grid: the user insert, remove and modify rows, then click a Save button and the server response ca, accept or not those changes. I was attaching the errors to the cell meta data. So I guess the only way to do that in a consistent way is attach the errors to the datasource itself, since the metadata will not shift as I would expect when rows are added/removed!

**Comment by AMBudnik** [comment]
Sorry, I guess that I did not understand fully. What keeps you from using the code above in the application? Maybe I'll be able to help.
