### ISSUE TITLE
Sort order is lost when a new item is inserted into the data source

### ISSUE THREAD

**Issue by kirliam** [handsontable/handsontable#5579]
### Description
In a previously sorted grid, if we insert a row into the related datasource, the grid mess up with the data.

### Steps to reproduce
1. Create a grid with columnSorting = true
2. Sort some column
3. Insert a new item into the datasource

Note that if you skip the step 2, it works as expected.

### Demo
https://jsfiddle.net/kirliam/b80v24c6/1/

### Your environment
* Handsontable version: 6.1.1
* Browser Name and version: Chrome 70.0.3538.102
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
What is an intended behavior here? You would like to add to the visual index? I am asking as the sorting is just changing indexes visually - they still have a physical index. When you attach a new row you get two cells with the same index. That is why now we turn off the sorting when you add a row.

**Comment by kirliam** [comment]
Yes, the intention is to add to the visual Index. Basically, it's a CRUD grid, and this is the scenario when the server response says it's not possible to delete a row.
I also tried to remove sorting > insert the row > restore sorting, but It didn't work as well.
I can't use the alter() method, since I need to insert the row in a specific physical Index in the data source array.

**Comment by AMBudnik** [comment]
You may want to save the order first and then return it after adding a new row in the [`beforeCreateRow` hook](https://handsontable.com/docs/6.2.0/Hooks.html#event:beforeCreateRow)
