### ISSUE TITLE
Clicking on a cell is inserting new line

### ISSUE THREAD

**Issue by vk-sourcefuse** [handsontable/handsontable#5581]
### Description

Is there any keyboard shortcut which can insert new blank line ?
Is it possible to insert new line above the clicked cell if I press any keyboard key while clicking on cell, or by any possible way ?

### Steps to reproduce

1. Video : https://drive.google.com/file/d/1Kbq3x4aKMqP200DE2HkPFIvOTDwVQcZh/view

### Your environment
* Handsontable version:
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Welcome @vk-sourcefuse 

In Handsontable you can add a row after any action. However, there is no predefined shortcut for adding it. The reason may lay in the logic of your application. I think I saw a similar case with `minSpareRows` some time ago. Can you share a demo where this issue can be replicable (as I believe you do not want this new row to be added)?

**Comment by vk-sourcefuse** [comment]
Hi, We couldn't replicate same behaviour till now, so closing this for now.
Thanks for quick response @AMBudnik  .
