### ISSUE TITLE
autoRowSize renders wrong height after hiding column

### ISSUE THREAD

**Issue by entspannt** [handsontable/handsontable#5588]
### Description
What happens: After hiding a column with autoRowSize enabled only the row height of rows in viewport get resized.
What should happen: All rows should have their height adjusted.

### Steps to reproduce
1. Hide Cover column
2. Scroll a bit down

### Demo
Fiddle: https://jsfiddle.net/ayszxkh1/3/

### Your environment
* Handsontable version:  handsontable-pro@6.2.0
* Browser Name and version: Chrome 70.0.3538.102
* Operating System: MacOS 10.14

**Comment by chris14465** [comment]
Same issue here.

**Comment by AMBudnik** [comment]
Thank you for sharing @entspannt @chris14465 

This may not be an easy case as this column is only hidden (not deleted) so this higher content is still there (just invisible).

**Comment by AMBudnik** [comment]
> Then why is it changing the row height of the visible rows and not those below? 
that is why I have added the `bug` label. Surely it is not something that we would expect so it has to be fixed.

**Comment by entspannt** [comment]
Ok, thanks for the clarification!

**Comment by AMBudnik** [comment]
You're welcome @entspannt 
I'll ping you as soon as we get our hands on it.

**Comment by nimesha95** [comment]
Hi any updates on this issue? Or any work-around?

**Comment by sagarbendale** [comment]
hide the `.ht_clone_left and .ht_clone_top_left_corner` If you are ok with row headers not visible all the time

**Comment by AMBudnik** [comment]
I haven't changed the version yet - just wanted to check what is happening and it looks like the Chrome 79 and macOS Catalina are bugless.

Can it be a browser thing? I do not see any oddities here.

![issue](https://user-images.githubusercontent.com/10757813/71584053-4f1d9a80-2b11-11ea-924a-a5bf37e02613.gif)

**Comment by AMBudnik** [comment]
I've just checked Windows 10 with Chrome 79 and it works well.
