### ISSUE TITLE
Editor expands beyond cell

### ISSUE THREAD

**Issue by webnard** [handsontable/handsontable#5589]
### Description
If the body element is styled with `display: grid`, the table's text fields expand beyond their cell.

![expand](https://user-images.githubusercontent.com/1213808/48593784-76b0a400-e90b-11e8-89e1-c320a6ea936e.png)

This doesn't happen if any other ancestor of the table is set as a grid display item. For example…

**[This Works](http://jsfiddle.net/qyh9814r/1/)**

```html
<html>
<body>
  <section style="display:grid;">
     <p></p>
     <aside>
       <figure>
         <div id=table>
```

**[But this doesn't](http://jsfiddle.net/jy238u9z/1/)**

```html
<html>
<body style="display:grid;">  <!-- now on the body element -->
  <section>
     <p></p>
     <aside>
       <figure>
         <div id=table>
```

### Steps to reproduce

1. Set CSS to `body{display: grid;}`

### Demo
http://jsfiddle.net/ojgq3f7e/2/

### Your environment
* Handsontable version: 6.2.0
* Browser Name and version:
  * Firefox Quantum 63.0.1
  * Google Chrome 70.0
* Operating System: Arch Linux

**Comment by AMBudnik** [comment]
I wanted to check other options of the `display` as there are around `20` of them. However, it looks like only `grid` and `inline-grid` causes the issue. 
When we pick `table-column` and `table-column-group` table does not appear. 

It works the same in `7.3.0` http://jsfiddle.net/s9oud7xb/

**Comment by adrianszymanski89** [comment]
Closing this issue, as it was fixed in v.12.2.
