### ISSUE TITLE
Need to customize the rule, I should write in what event?

### ISSUE THREAD

**Issue by inputherf** [handsontable/handsontable#5592]
### 

I now need to use regular to judge the format problem of a column of data. After entering the data automatically, I do not need to click a button to judge again. What event do I need to write this method in?Urgent please!

**Comment by AMBudnik** [comment]
Hi @inputherf 

for 

> After entering the data automatically

you can use [`afterChange` hook](https://handsontable.com/docs/6.2.0/Hooks.html#event:afterChange). Have you already tried it?

**Comment by inputherf** [comment]
> Hi @inputherf
> 
> for
> 
> > After entering the data automatically
> 
> you can use [`afterChange` hook](https://handsontable.com/docs/6.2.0/Hooks.html#event:afterChange). Have you already tried it?

thanks, i will try
