### ISSUE TITLE
Floating Horizantal scrollbar at bottom of screen, when the table Horizantal scrollbar is not visible

### ISSUE THREAD

**Issue by rahulmurkute-tudip** [handsontable/handsontable#5594]
Floating horizontal scrollbar at bottom of the screen

Steps to reproduce
1. Fill up the data that exceed the horizontal and vertical limit. So that horizontal and vertical scrolls appear.
2. Suppose there are 100 records and only 60 records are visible to the screen, so for remaining 40 records, we have to scroll vertically. There is also horizontal scroll at the end of the handsontable because of lots of columns.
3. So for the horizontal scroll of 1st record, we have to do vertically scroll first to appear horizontal scroll and scroll horizontally then again scroll vertically to the first record to see the column.

**Comment by AMBudnik** [comment]
I am sorry but I do not understand the last step. Is there any other demo/example that you can show me that does the same job?
