### ISSUE TITLE
Add Aria tabbing

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5596]
### Description

We should add ARIA practices to support screen readers.
SRC: https://www.w3.org/TR/wai-aria-practices/examples/table/table.html

### Your environment
* Handsontable version: any
* Browser Name and version: cross-browser
* Operating System: any

reported at [forum](https://forum.handsontable.com/t/gh-2519-support-for-the-visually-impared/2625/2)

**Comment by AMBudnik** [comment]
This feature request is closed, But it will be automatically reopened after we attach it to a milestone.

**Comment by jurajvalkucak** [comment]
Hi, I also would appreciate ARIA support to conform to grid role.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role
