### ISSUE TITLE
The column's data is being erased when we move column after a hidden area of columns.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5598]
### Description

The manualColumnMove conflicts with hiddenColumns. The column's data is being erased when we move column after a hidden area of columns.

### Steps to reproduce

1. Click <kbd>Hide columns</kbd> button
2. Move column `Fil` after column `Nave`

![gif](https://user-images.githubusercontent.com/10757813/48831242-bac1ff80-ed76-11e8-99f9-b78d2f781872.gif)

Result: 
`Nave` column becomes empty.

### Demo

https://jsfiddle.net/vbfndyug/

### Your environment
* Handsontable version: 6.2.0
_Doesn't seem to be connected to any version_
* Browser Name and version: Chrome 70
* Operating System: Windows 10

inform [forum](https://forum.handsontable.com/t/gh-5598-moving-columns-replaces-old-column-header-and-data/2792) and [here](https://forum.handsontable.com/t/gh-5598-error-when-hidden-column-after-move/3355)

**Comment by wojciechczerniak** [comment]
Related bug reports:  #5108 #5456

Check @wszymanski comment here for details: https://github.com/handsontable/handsontable/issues/5456#issuecomment-458854217

**Comment by wojciechczerniak** [comment]
Few more details here: https://github.com/handsontable/handsontable-pro/issues/25

**Comment by mudit-maven** [comment]
Facing same issue, any updates on this bug?

**Comment by AMBudnik** [comment]
Sorry, no updates yet.

**Comment by Chris25602** [comment]
bump.

**Comment by AMBudnik** [comment]
`7.1.1`
![image](https://user-images.githubusercontent.com/10757813/65038511-65cc2700-d950-11e9-87e1-af1f39a7f95f.png)
https://jsfiddle.net/handsoncode/90kLt6vj/

`8.0.0.-rc1`
![image](https://user-images.githubusercontent.com/10757813/65038573-872d1300-d950-11e9-9ad2-b44f7088a730.png)
https://jsfiddle.net/handsoncode/mh473xak/

`8.0.0.-rc1` introduces a new type of bug where the header is cut.

**Comment by aninde** [comment]
The header is cut even in a newer version.
`8.0.0-rc1` doesn't fix described here issue and create additional error with the cutting header. 

**Demo**
https://jsfiddle.net/aninde/70yzg6kh/

**Comment by AMBudnik** [comment]
Headers are mismatched cause of the regression in 8.0.0-beta2-rev1 however, the main issue with empty column is **solved** i **8.0.0.-beta2-rev2** https://jsfiddle.net/rf3m1o4j/  
  
In 8.0.0-beta1 is remained broken https://jsfiddle.net/rf3m1o4j/1/

**Comment by AMBudnik** [comment]
The main issue works well in 8.0.0-beta2-rev13 https://jsfiddle.net/AMBudnik/egpvnodc/
To confirm the state of the issue - it was broken in 7.4.2 https://jsfiddle.net/AMBudnik/32arLy7n/  nor 7.0.0 https://jsfiddle.net/AMBudnik/pd5vur3k/ so The regression label has to be taken off.

**Comment by AMBudnik** [comment]
The main issue works well in 8.0.0-beta2-rev13 https://jsfiddle.net/AMBudnik/egpvnodc/
To confirm the state of the issue - it was broken in 7.4.2 https://jsfiddle.net/AMBudnik/32arLy7n/  nor 7.0.0 https://jsfiddle.net/AMBudnik/pd5vur3k/ so The regression label has to be taken off.

**Comment by AMBudnik** [comment]
Hi @Chris25602 @mudit-ag Good news! 

We've just released 8.0.0-beta2 that fixes the mentioned issue.
We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes [https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2](https://slack-redir.net/link?url=https%3A%2F%2Fgithub.com%2Fhandsontable%2Fhandsontable%2Freleases%2Ftag%2F8.0.0-beta.2)
NPM [https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2](https://slack-redir.net/link?url=https%3A%2F%2Fwww.npmjs.com%2Fpackage%2Fhandsontable%2Fv%2F8.0.0-beta.2) 

All feedback's appreciated.

**Comment by Guobacai** [comment]
Hi @AMBudnik 

Here is the fiddle. I made a little change to yours.
https://jsfiddle.net/guobacai/b5y26sgm/1/

After reloading the data, the moved column is restored to its original place.

Reproduce Steps:
1. Move the column "Spos" to be the last position.
2 Click button "Reload Data".

What I would expect is the column "Spos" stay at the last position. However, it moves back to the first position.
I think this is very common use case. 
For instance, the table has pagination.
On the first page, user move the first column to the last position.
After loads the data of second page, it would expect the columns have the same status.

**Comment by pnowak** [comment]
Hi @Guobacai 

`loadData` loads new data to Handsontable and resets the cell meta. 
So it takes `colHeaders` from our settings. 

You have to first cache the `colHeaders` after the move, and then use it by `updateSettings` with load data.

**Comment by AMBudnik** [comment]
This issue is officially fixed in Handsontable v 8.0.0 https://jsfiddle.net/hu1r8bwp/

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
