### ISSUE TITLE
Could you please tel me ,what is  the flow of editing the cell 

### ISSUE THREAD

**Issue by rsurendar** [handsontable/handsontable#560]
i mean which function call first tel very very importent to me.

which function call happen first when cell edit first please tel me , i am trying to undertand but i am not geting 

when cell loss the focus (means using tab or enter ) ,which function call first 

 function onDblClick() {
    that.beginEditing(col,row, prop, true);
  }
please explain me the flow  very urgent   please give replay.

I am Trying to edit cell r-1 c-0

![image](https://f.cloud.github.com/assets/3841515/360697/016a0376-a1a4-11e2-809b-82bad3151c27.png)

But data Updated at R=1 c=0 but in next cell of edited cell.

![image](https://f.cloud.github.com/assets/3841515/360687/8d489da4-a1a3-11e2-82e0-8d065e85f0ac.png)

**Comment by AMBudnik** [comment]
Issue closed, in lack of reply from a issue author.
