### ISSUE TITLE
Column header text input filtering cursor loses focus

### ISSUE THREAD

**Issue by s1monj** [handsontable/handsontable#5600]
### Description

Custom column filtering using an input text box no longer works - can not maintain focus on input while typing.

The official example from the HoT web site does not work:
https://handsontable.com/docs/6.2.0/demo-filtering.html

### Steps to reproduce

1. Type in any column header input box and the cursor disappears

### Demo
https://handsontable.com/docs/6.2.0/demo-filtering.html

### Your environment
* Handsontable version: 6.2.0
* Browser Name and version: Firefox 52, Chrome 57
* Operating System: Linux

**Comment by AMBudnik** [comment]
Hey @s1monj 

please track down to this topic https://github.com/handsontable/handsontable/issues/5541

A fix to this issue is already in development.

**Comment by AMBudnik** [comment]
Hey @s1monj 

We;ve just closed and solved https://github.com/handsontable/handsontable/issues/5541
Please update to v `7.0.0`
