### ISSUE TITLE
Configured numeric format pattern not applied to cell

### ISSUE THREAD

**Issue by Fewthlix** [handsontable/handsontable#5601]
### Description
Pattern of a numeric cell is not applied correctly.

### Steps to reproduce
1. Define a numeric cell with pattern '0.0,00' and culture 'de' 
2. Type in the value '1,23'
3. The value will be converted to the wrong format '1.23' (note the comma setting)

### Demo
Type in the cell '1,23' and it will convert the number to '1.23'.
https://jsfiddle.net/Fewthlix/vdw87a29/

### Your environment
* Handsontable version: 6.0.1
* Browser Name and version: latest versions of Edge, Firefox, Chrome

**Comment by AMBudnik** [comment]
Hey @Fewthlix 

Please find the demo attached https://jsfiddle.net/yzmted4u/

De `culture` syntax for Germany is `de-DE` (deutsch-Deutschland)

**Comment by Fewthlix** [comment]
Thank you!
