### ISSUE TITLE
Hiding ContextMenu for specific columns

### ISSUE THREAD

**Issue by ashishcs062** [handsontable/handsontable#5602]
Hi Guys,

Is there any way to hide ContextMenu for one/more columns and show for others at the same time?
I want to hide ContextMenu for the 1st column in my table.

Thanks,
Ashish

**Comment by AMBudnik** [comment]
That is the same situation as in your other post, meaning, you can use `hidden` method on the custom `contentMenu` `item`. Here's an example for hiding `Custom option` for the column index `0` http://jsfiddle.net/uyv25hcq/

**Comment by ashishcs062** [comment]
Thanks a lot Aleksandra :)
