### ISSUE TITLE
Disable 'Remove row' from contextMenu for the last row/ last merged row

### ISSUE THREAD

**Issue by ashishcs062** [handsontable/handsontable#5603]
Hi Guys,

I want to Disable 'Remove row' from contextMenu when there is only the last row/ last merged row remaining in the table.

Example-
We are seeing 'Remove Rows' in the contextMenu-
![1](https://user-images.githubusercontent.com/35444809/48895682-a5d19300-ee80-11e8-9791-5f71f35eb2de.PNG)

It should be hidden/disabled when there only one row/ merged row-

![2](https://user-images.githubusercontent.com/35444809/48895785-e29d8a00-ee80-11e8-8495-a9c210e2997c.PNG)

Thanks,
Ashish

**Comment by AMBudnik** [comment]
Hey @ashishcs062 

You can use this logic http://jsfiddle.net/76hLdkpw/ (custom `items` in the `contextMenu` object).
`hidden` is used to point out when the option disappears from the menu.

**Comment by ashishcs062** [comment]
Thanks a lot Aleksandra :)
