### ISSUE TITLE
Input is not working, It working only if you paste some text.

### ISSUE THREAD

**Issue by priyankadarokar** [handsontable/handsontable#5604]
I am trying to use **Custom implementations** in https://handsontable.com/docs/6.2.0/demo-filtering.html

But the custom created input is working only if you paste some text. It is not working normally.

Please check and help me.

**Comment by AMBudnik** [comment]
Hey @priyankadarokar 

to confirm - Is this https://github.com/handsontable/handsontable/issues/5541 the same issue?

**Comment by AMBudnik** [comment]
Thank you.

We are already working on it. I do not see any commits yet, but I hope it will be fixed in the next version.

Thank you for sharing. Please share progress to this issue at https://github.com/handsontable/handsontable/issues/5541

**Comment by AMBudnik** [comment]
Hey @priyankadarokar 

Please update to v `7.0.0.`. We've just solved https://github.com/handsontable/handsontable/issues/5541
