### ISSUE TITLE
In iframe + firefox, clicking on the cell the 'page scroll to top' issue still exist

### ISSUE THREAD

**Issue by vincent-cm** [handsontable/handsontable#5605]
### Description

It is an fixed issue before 3.x.x which clicking on any cell, the container will auto scroll to the page top if there are space to do.

It has been fixed after 3.x.x but I found the same issue when I am using iframe to contain the table, and this issue only on firefox (no matter the system),

The extended issue what I am finding is in other browser, if it is in iframe, the default scrollbar (on body) shaking (moving up and revert to its original position quick) when you click the cell, (this one may be related to the above bug)

**Please investigate any listener with the scroller omitted to check if it is in a iframe.**

### Steps to reproduce

1. as above
2.
3.

### Your environment
* Handsontable version: 6.2.0 (existing bug from 3.x.x)
* Browser Name and version: (Firefox)Mozilla/5.0 (Macintosh; Intel …) Gecko/20100101 Firefox/63.0
* Operating System: macOS, windows 7, windows 10

**Comment by AMBudnik** [comment]
Hey @vincent-cm 

can you record the behavior or create a demo with a test scenario? I am not able to replicate the issue.

I am testing our example in the blog post https://handsontable.com/blog/articles/2018/11/feature-spotlight-multi-column-sorting
we use the `<iframe>` to post the JSFiddle examples

Tested on: Windows 10/ Firefox

**Comment by AMBudnik** [comment]
Thank you very much for sending the video. I have replicated the issue.

**Comment by vincent-cm** [comment]
@AMBudnik Can you please **reopen** this bug, observed this bug did _not_ fixed.
Reason: The jsfiddle used by your demo page has changed, jsfiddle is no longer using iframe. So even thought it is scrolling fine on Firefox, it should not indicate the bug fixed.

To Reproduce, open any Firefox browser
1. Open this link [https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe)
2. Copy and paste following code into **body** part of the left side editor, replace all content of **body**

```
<iframe src="https://www.w3schools.com/code/tryit.asp?filename=G2EPME2C1SQB" width="800" height="800">
</iframe>
```

3. Click "**run**" inside the loaded iframe over the right preview pane
4. Resize the browser height to make scrollbar appear, scroll down the content and click on one of the table cells.

Observed that the whole page scroll to top.


> It is hard to reproduce since service like _jsfiddle_, _cssbin_ are blocking iframe embedding and only can be run once. Once saved, it will add up a restricted header check and blocks the loading.
