### ISSUE TITLE
How to  adding an ID attribute on handsontable checkbox

### ISSUE THREAD

**Issue by Abdul-anas** [handsontable/handsontable#5606]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Thank you for creating a new issue. It is much better than post a new comment on an old topic.

Please share the details/requirements for the attribute,

Is that a new/custom attribute, 
should it be added to the checkbox or can be added to a whole cell that holds the checkbox,
what is a purpose of this attribute and which methods/hooks needs to have an access to it
