### ISSUE TITLE
Feature req: Edit on select

### ISSUE THREAD

**Issue by provegard** [handsontable/handsontable#561]
I would like to start editing as soon as a cell i selected. My current hack is an `onSelection` handler that looks like this (CoffeeScript, and $timeout is AngularJS's wrapper around setTimeout):

```CoffeeScript
    editOnSelect = (r, c, r2, c2) ->
        if r == r2 and c == c2
            $timeout(() ->
                instance = $('#hotTarget').data("handsontable")
                e = $.Event("keydown", { keyCode: 113 })
                instance.$table.trigger(e)
            )
        else
            $('#hotTarget').handsontable("destroyEditor")
        return
```

I.e., it sends an F2 key to the table. This works, but only when 'asyncRendering` is turned off.

It would be nice to be able to write `handsontable('beginEdit', r, c)` or similar, or have an `editOnSelect` option built-in in Handsontable.

**Comment by AMBudnik** [comment]
This feature is now available. If you would have any other ideas, feel free to open a new issue.
