### ISSUE TITLE
Different date picker Icon 

### ISSUE THREAD

**Issue by yogiv88** [handsontable/handsontable#5610]
Is it possible for us to change the icon ▼ for date picker and use custom icon?

**Comment by AMBudnik** [comment]
Without changing the source code there's only a chance to do it using CSS. But it's only a fake replacement. Here https://jsfiddle.net/jretkoa2/ I am adding `::after` element and paint the old element with the color of the cell's background.
The next obstacle is that we are using `htAutocompleteArrow` class to add the arrow by default, and this class is also used for autocomplete and dropdown cell types.

**Comment by yogiv88** [comment]
I need to change the icon for date picker alone.

**Comment by yogiv88** [comment]
or if I apply a class for a particular column, then I can handle it using CSS

**Comment by AMBudnik** [comment]
You can add a class via `columns` or `cells` methods, however, you still need to handle the class that is already applied. We did not intend to make this element replaceable.

**Comment by yogiv88** [comment]
We want to differentiate the date cells from other types explicitly, that's why. can you share an example on how to add class to a column? I can't find how to do that in documentation. TIA
