### ISSUE TITLE
how to solve dropdown type in cell when column is sorted

### ISSUE THREAD

**Issue by achrafbs** [handsontable/handsontable#5611]
I try to create same dropdown type for same value in colomn D. So i have a issue in my handsontable when i sort the column D. In my example i have the cells 8330 and 33900 are in dropdown type. Normally the cell 8330 is the unique value which be in dropdown type.

In the first showing, it works fine but when i sort the column D, the issue is appear.

[https://jsfiddle.net/4py8vf61](url)

JS 

```
  function getCarData() {
    return [
      {car: "Mercedes A 160", year: 2017, price_usd: 7000, price_eur: 7000},
      {car: "Citroen C4 Coupe", year: 2018, price_usd: 8330, price_eur: 8330},
      {car: "Audi A4 Avant", year: 2019, price_usd: 33900, price_eur: 33900},
      {car: "Opel Astra", year: 2020, price_usd: 5000, price_eur: 5000},
      {car: "BMW 320i Coupe", year: 2021, price_usd: 30500, price_eur: 30500}
    ];
  }
  var
    container = document.getElementById('example1'),
    hot;
  
  hot = new Handsontable(container, {
    data: getCarData(),
    columnSorting: true,
    colHeaders: true
  });
	
  hot.updateSettings({
        cells: function(row, col)
        {
          if (col === 3 && hot.getDataAtCell(row,col) === 8330) {
          var cellMeta = {};
          cellMeta.type = 'dropdown';
          cellMeta.source = [
             'LL',
             'SS'];
          return cellMeta;
          }
        },
        sortIndicator: true,
        });
```
HTML

`<div id="example1" class="hot handsontable htColumnHeaders"></div>`

CSS

```
</style><!-- Ugly Hack due to jsFiddle issue -->

<script src="https://docs.handsontable.com/pro/5.0.1/components/handsontable-pro/dist/handsontable.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="https://docs.handsontable.com/pro/5.0.1/components/handsontable-pro/dist/handsontable.full.min.css">
<script src="https://docs.handsontable.com/pro/5.0.1/components/numbro/dist/languages.min.js"></script>

```
Please help

**Comment by AMBudnik** [comment]
Hey @achrafbs 
The table did not know that you would want an extra space for the `dropdownArrow` so it did not adjust the columns.
If you add `hot.render()` after `updateSettings` it will work fine.

Example https://jsfiddle.net/m1dw8bsv/

**Comment by achrafbs** [comment]
Hey AMBudnikm

Thanks for your answer.
The issue still present when you sort the table. I want that the dropdown is affected just from 8330 not for 33900.

Please help.

**Comment by AMBudnik** [comment]
Hey @achrafbs 

please try this one https://jsfiddle.net/og5ctkeL/
