### ISSUE TITLE
continus removeRow cause error in formula situation

### ISSUE THREAD

**Issue by iaminvictus1993** [handsontable/handsontable#5613]
### Steps to reproduce

1. remove row 1
2.remove row 1
3. look console

### Demo

http://jsfiddle.net/s6t768pq/2956/
![removebug](https://user-images.githubusercontent.com/22359049/48998065-34018e00-f18d-11e8-997e-beb8f9d304d8.gif)
### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by iaminvictus1993** [comment]
is something wrong  with  sum?

**Comment by AMBudnik** [comment]
Thank you for sharing. That is definitely an issue with the `remove_row` option.
When it comes to the `#VALUE!` the message it is shown because we cannot add two empty string,[ it works only for numbers.](http://jsfiddle.net/cfLpt9kb/)

**Comment by AMBudnik** [comment]
Demo updated to `7.4.2` http://jsfiddle.net/AMBudnik/9rj5xu4k/

The error does not show if we start to remove rows from the bottom.

**Comment by swistach** [comment]
Hi @iaminvictus1993,
We fixed that bug in v8: https://jsfiddle.net/92yrovdp/
I close this issue, but let us know if you facing this problem after upgrade to the new version.
