### ISSUE TITLE
Updating settings makes summary columns editable

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5616]
### Description
I noticed that when I update settings with `updateSettings()` that the `columnSummary` destination cells become editable, even though they should be readonly. I've noticed this behavior with various types of updated settings, though none of them should set the column summary cells to writable.

### Steps to reproduce

1. Open [demo link](https://jsfiddle.net/c8mywsu0/) which includes `columnSummary` settings
2. Click the "Update settings" button which triggers `updateSettings({ columns })`

Notice the column summary cells become editable.

![](http://g.recordit.co/HAHDbPHqA2.gif)

### Demo

https://jsfiddle.net/c8mywsu0/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by aaronbeall** [comment]
Hm, seems like `columnSummary` can't be updated at all after initial render...

**Comment by AMBudnik** [comment]
We have a related topic at https://github.com/handsontable/handsontable/issues/3597

ps. we had a meeting today and `summaries` are one of the subjects that will come up in 2019. The performance is the most important task but summary calculations are also there.

**Comment by AMBudnik** [comment]
I've just checked how the issue works in v 8.0.0 https://jsfiddle.net/m8gukfeb/ and it works the same as described in the main issue report.

**Comment by aninde** [comment]
This issue is still replicable with v12 https://jsfiddle.net/5gw74ucn/

**Comment by adrianszymanski89** [comment]
Hi @aaronbeall I am happy to announce that this issue is fixed in v14.4.0.

Related pull request: hhttps://github.com/handsontable/handsontable/pull/10955

Release notes: https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-4-0

Thank you again for sharing the report!
