### ISSUE TITLE
Add tabindex property

### ISSUE THREAD

**Issue by arifemrecelik** [handsontable/handsontable#5625]
Hey there,

I'm using Handsontable for React project. And I try to focus first of cell table with `tabIndex`. But handsontable doesn't have `tabIndex` as a prop. 

Is this feature in your future plan or do you have an another solution for that?

**Comment by AMBudnik** [comment]
Welcome @arifemrecelik 

this topic has been mentioned here https://github.com/handsontable/handsontable/issues/5596 as `tabIndex` should be a part of our Aria-compatible changes.

Please track changes to https://github.com/handsontable/handsontable/issues/5596 for updates.
