### ISSUE TITLE
Broken UI for moving rows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5626]
### Description

I wasn't able to replicate it in the JSFiddle nor on our webiste (they seem to add some additional styles). The issue is replicable on a clear website.

### Steps to reproduce

1. Grab one row with a <kbd>LMB</kbd> and don't drop

Here's how it looks like.

![2gif](https://user-images.githubusercontent.com/10757813/49221352-23455800-f3d9-11e8-8f2c-c648b6f0176e.gif)

The thick black line should appear on the top edge of the cell. Further we want to drop the row the messier shadow/line gets.

### Demo

```js
var box = document.querySelector('.box');

var settings = {
  data: Handsontable.helper.createSpreadsheetData(30, 10),
  colHeaders: true,
  rowHeaders: true,
  manualRowMove: true
}

var hot = new Handsontable(box, settings);
```
_(vanilla, no additional styles or dependencies)_

[boot-test.zip](https://github.com/handsontable/handsontable/files/2629024/boot-test.zip)

### Your environment
* Handsontable version: 6.2.0
_doesn't seem to be related to any version_
* Browser Name and version: Chrome 70
* Operating System: Windows 10

**Comment by swistach** [comment]
Hi @AMBudnik,
You need to add `<!DOCTYPE html>` on the top of `index.html` :) (or other correct DOCTYPE declaration).

**Comment by AMBudnik** [comment]
Thanks for spotting that @swistach 

the issue is gone
