### ISSUE TITLE
cell dropdown overfloww

### ISSUE THREAD

**Issue by AncaWebDev** [handsontable/handsontable#5629]
Hi,

I have a long dropdown menu inside a cell, and whenever I scroll inside the dropdown menu, the whole table scrolls down at the same time. Is there a way to display the whole list in dropdown menu so there's no need to scroll, or disable the table scroll while on the dropdown scroll?

I tried using {overflow:visible} on a few selectors and none of them worked.

Please, I'm out of ideas

**Comment by AMBudnik** [comment]
Hey @AncaWebDev 

Can you share a demo where this issue can be replicable? Does the menu take the full height of the HAndspntable container, its parent or window?

**Comment by AMBudnik** [comment]
I am closing this issue as there's no reply. But if you're still struggling with the code please let me know.
