### ISSUE TITLE
Row Header becomes increasingly misaligned with rows they represent when autoRowSize:true and rowHeaders:true options are turned on

### ISSUE THREAD

**Issue by SteveEngine** [handsontable/handsontable#5637]
### Description

When both the autoRowSize property and the rowHeader property are set to true, and the table has intermixed rows where some rows need a larger row height than others, the rowHeaders become increasing misaligned with the row they represent.

I would expect the rowHeaders to stay aligned for all the rows regardless.

If I set the autoRowSize property to false, then the rowHeaders are aligned properly.

### Steps to reproduce

1. Set the autoRowSize, and rowHeader options to true
2. Load a table that has rows that have both single row height columns multi line row heights in the same table intermixed

See jsFiddle demo below, scroll to the bottom to see the rows become increasingly misaligned.

### Demo

http://jsfiddle.net/v49drzus/

### Your environment
* Handsontable version: both 5.0.2 and 6.2.0
* Browser Name and version:  Chrome Version 71.0.3578.80 (Official Build) (64-bit)
* Operating System: Windows 7 Enterprise - Service Pack 1

**Comment by AMBudnik** [comment]
Hey @SteveEngine 

I am using Windows 10 and Chrome 71 but wasn't able to replicate the issue

![gif](https://user-images.githubusercontent.com/10757813/49585144-e1c72680-f95d-11e8-9ea3-a671c24791e5.gif)

Do you use any other scroll than 100%

**Comment by AMBudnik** [comment]
Hey @SteveEngine 

do you have any progress or additional findings?

**Comment by SteveEngine** [comment]
@AMBudnik 

Sorry for the long delay, I got moved onto another project and didn't get time to swing back around until now.  The js fiddle reproduced the error on my work machine (Windows 7 Chrome), but it looked fine on my home machine (Windows 7 Chrome).  

My monitor's resolution at work is 1920 x 1200, although when I changed it to 1920x1080 I still noticed the same error. 

If I zoom the browser in up to 400% everything lines up perfectly

![image](https://user-images.githubusercontent.com/45608139/61313875-5baf7000-a7c9-11e9-9f59-08dbe8c15af2.png)

**Comment by SteveEngine** [comment]
@AMBudnik 

I found if I add a fixed row height value through the rowHeights parameter, the discrepancy mostly goes away:

New Fiddle with rowHeights: '30px' added
http://jsfiddle.net/n8stk9cg/

![captured (3)](https://user-images.githubusercontent.com/45608139/61322993-e51c6d80-a7dc-11e9-9207-81f7d5f6c6bc.gif)

It seems like whatever is dynamically calculating the rowHeights is different in the rowHeader number bar then the actual table, but that is just speculation on my part.

**Comment by AMBudnik** [comment]
Thank you for the feedback. I think that this may be related to https://github.com/handsontable/handsontable/issues/4767
