### ISSUE TITLE
current focused cell level error

### ISSUE THREAD

**Issue by wangbeggar** [handsontable/handsontable#5644]
### Description
current focused cell level error

steps:   doubleClick edit  and try rolling

Look at the official website
![image](https://user-images.githubusercontent.com/11613516/49631030-7a77a800-fa2b-11e8-9dad-96cdd615a65c.png)

**Comment by AMBudnik** [comment]
Thank you for sharing @wangbeggar 

That is a regression type issue that has been reported at https://github.com/handsontable/handsontable/issues/5105

Please track changes to https://github.com/handsontable/handsontable/issues/5105 for updates
