### ISSUE TITLE
Support for numeric value without decimal places

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5645]
### Description

As mentioned in our forum https://forum.handsontable.com/t/numeric-format-pattern-issue-whole-units-display-as-0-00-and-not-0/2656/2 it is very hard to get a numeric value without decimal places. It has recently changed is Numbro but it looks like we do not fully support their changes.

### Your environment
* Handsontable version: 6.2.0+
* Browser Name and version: any
* Operating System: any

The topic will be reopened after it gets into a milestone.

**Comment by JAspeling** [comment]
Has this been resolved?

**Comment by AMBudnik** [comment]
The feature hasn't been added yet @JAspeling

**Comment by wojciechczerniak** [comment]
For anyone who finds this issue, this is and was possible with:
```
numericFormat: {
  pattern: {
    mantissa: 0
  },
}
```
