### ISSUE TITLE
Render big table

### ISSUE THREAD

**Issue by rafaelnovello** [handsontable/handsontable#565]
Hi!

Sorry about this topic again...but I just want to known how big tables can be rendered with handsontable. I tested a table with 95 rows and 60 columns, loaded with ajax, and it was very slow to handle data.

Is there any optimization possible?

Thank you very much!

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).
