### ISSUE TITLE
Custom storage gets replaced by HOT's own storage

### ISSUE THREAD

**Issue by chhinendu** [handsontable/handsontable#5658]
### Description
If you need to use your own storage, you could change that in beforeInit. 
`var persistentStatePlugin = this.getPlugin('PersistentState');
        persistentStatePlugin.storage = persistFactory.getPersister(persistFactory.getPersisterType().LOCAL_STORAGE,
            storageName);`
Here 'persistFactory' is our own custom made library.

### Steps to reproduce
However this works fine untill you call the updateSettings(), after the call, the custom storage gets replaced by HOT's own storage.

### Demo
NA

### Your environment
* Handsontable version: 6.2.0
* Browser Name and version: Chrome v70
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hey @chhinendu 

to be honest I am not the expert but from the discussion with our team, I can share some ideas. I've been told that it might be easier and faster to create a copy of the plugin. The plugin itself was not made in the way that it could allow to change the storage.
