### ISSUE TITLE
hiddenColumns gets reset and not picked from persisted state when updateSettings called

### ISSUE THREAD

**Issue by chhinendu** [handsontable/handsontable#5659]
### Description
hiddenColumns gets reset and not picked from persisted state when updateSettings called.

### Your environment
* Handsontable version: 6.2.0
* Browser Name and version: Chrome v70
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @chhinendu 

it is written in our docs that 

> Turns on saving the state of column sorting, column positions and column sizes in local storage.

This means that persistent state does not work for hiding.

**Comment by chhinendu** [comment]
@AMBudnik Should this be considered as a feature for future releases ?

**Comment by AMBudnik** [comment]
I think that we may end up with a completely different system to support saving hidden rows and columns.
