### ISSUE TITLE
Out of stack space in IE11 on version 6.2.1

### ISSUE THREAD

**Issue by stephanvierkant** [handsontable/handsontable#5664]
I've just upgraded from 6.2.0 to 6.2.1 and I'm getting this error on IE11:

> Out of stack space

**Comment by AMBudnik** [comment]
Hey @stephanvierkant 

It works as expected at https://handsontable.com/docs/6.2.1/demo-scrolling.html on my Windows 10/ IE 11
Can you share a demo where this issue can be replicable?

**Comment by stephanvierkant** [comment]
I can confirm that. It's working on Win7/IE11.

I'm using Webpack and that makes creating a demo a bit harder, but I'll try to create one.

**Comment by AMBudnik** [comment]
Hey @stephanvierkant 

if you haven't created a demo yet I got a hint that you can try to clear the _node_modules_ directory and the `package-lock.json` and `yarn.lock` files. Then install dependencies once again (if you haven't tried it already).

**Comment by AMBudnik** [comment]
I guess that we can close the issue as there's no feedback for 2 weeks but if you're still having the issue please let me know.

**Comment by AMBudnik** [comment]
Hey @stephanvierkant 

have you had a chance to check this issue or share your settings?
