### ISSUE TITLE
Unable to get onclick of button inside cell handsontable for angular

### ISSUE THREAD

**Issue by tanveerrafiqueIVL** [handsontable/handsontable#5668]
### Description
I have rendered buttons inside cell but I am unable to get onclick of this in my angular 5's component. I tried to put alert() in onclick, I tried a function and then I tried angular's (click) function but nothing worked. Any help will be appreciated.
Thanks a lot.

here is my code:

`columns.push({
				data: index, renderer:
			        function percentRenderer(instance, td, row, col, prop, value, cellProperties) {
						Handsontable.renderers.HtmlRenderer.apply(this, arguments);
						if(value.data == 'TRUE'){
							td.innerHTML = '&#10004;';
						}
						else if(value.data == 'FALSE'){
							td.innerHTML = '&#10006;';
						}
						else if(value.data == 'UNMARKED'){
							td.innerHTML = '<button onclick="alert(\'clicked\')" value="\'TRUE\'">&#10004;</button><button value="\'FALSE\'">&#10006;</button>';
						}
						else{
							td.innerHTML = value.data;
						}
					}
			});`

**Comment by AMBudnik** [comment]
Hey @tanveerrafiqueIVL 

Please find this demo - https://stackblitz.com/edit/angular-handsontable-custom-renderer?file=app%2Fapp.component.ts it has comments that should explain it all. But it not please let me know.

**Comment by tanveerrafiqueIVL** [comment]
@AMBudnik thank you for answering my query, sadly it seems that I can't get the callback as there's no way to register those callbacks at angular. My problem was that based on cell value I wanted to show buttons and wanted to get the value on click of those buttons. I guess there's no solution for this. I wanted something like this
![screen shot 2018-12-15 at 6 56 55 pm](https://user-images.githubusercontent.com/16731647/50043728-40e21500-009b-11e9-9277-5f8183ca91a0.png)

**Comment by AMBudnik** [comment]
You can still change the value of a cell based on the content of a sibling cell via `afterChange` hook > `setDataAtCell` but it will not trigger the click via renderer.

**Comment by tanveerrafiqueIVL** [comment]
@AMBudnik you mean to say that I can get the value of those clicks via afterChange hook? I didn't understand it correctly I guess.

**Comment by AMBudnik** [comment]
here https://stackblitz.com/edit/angular-handsontable-custom-renderer-gy72fx?file=app/app.component.ts we can get an element that user clicks, even if that's a button. However, this demo is a bit different from what you'd like to achieve. You want to change a text/class of a button what user clicks it?

**Comment by tanveerrafiqueIVL** [comment]
actually I have cell values as PRESENT, ABSENT and UNMARKED, so based on these values I have to show two buttons in a cell whose value is UNMARKED and the buttons will be PRESENT and ABSENT.
Now if the user clicks on PRESENT then I want to know that he clicked on PRESENT out of those two buttons.

**Comment by AMBudnik** [comment]
Here https://stackblitz.com/edit/angular-handsontable-custom-renderer-jxpfdn?file=app/app.component.ts I'm logging a className of the button. I hope it will help you to progress with the app

**Comment by tanveerrafiqueIVL** [comment]
Thanks a ton Alexandra for your help :) it will work for me. 👍
