### ISSUE TITLE
How to create cascading dropdown(autocomplete)

### ISSUE THREAD

**Issue by nikunj24u** [handsontable/handsontable#567]
Hello there,

I want to create cascading dropdown (autocomplete) in one of page.
Cascading dropdown(auntocomplete)
Let's say, I have table with 3 Columns (Column-A,Column-B,Column-C)
OnChange of Column-A, I need to update the source of Column-B and then OnChange of Column-B I need to update the source of Column-C.

Is it possible to create such cascading dropdown in current version of Handsontable(Handsontable 0.8.17).
If it is possible, Can you please provide a an example?

Regards,
Nikunj Patel

**Comment by rajivseelam** [comment]
Any suggestions on how to solve this problem? http://stackoverflow.com/questions/34243048/handsontable-select2-dropdown-options-change-for-next-row
