### ISSUE TITLE
[5.0.2+] htInvalid shifts when row are added/removed

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5674]
### Description

`htInvalid` which stands for an invalid cell shifts when rows are added/removed

### Steps to reproduce

1. Type `y` in 3rd row of the last column
2. Delete the column above the red field

Result
![invalid](https://user-images.githubusercontent.com/10757813/50010046-ba550700-ffb8-11e8-9cb1-3186f70eb879.gif)

How it should be (`5.0.1` and before)
![correct](https://user-images.githubusercontent.com/10757813/50010069-c640c900-ffb8-11e8-9c15-bba59e6fd307.gif)

### Demo

https://jsfiddle.net/b0329fn4/ 

### Your environment
* Handsontable version: 5.0.2+
* Browser Name and version: Chrome 71
* Operating System: Windows 10

reported at [forum](https://forum.handsontable.com/t/remove-rows-with-htinvalid-class-errors/2719)

**Comment by wszymanski** [comment]
Fix for the problem just when removing one row. The table's way of work, before change f1747b3912ea3b21fe423fd102ca94c87db81379 was restored. There is still problem when removing more than one row.

**Comment by AMBudnik** [comment]
Thank you for fixing guys!

**Comment by AMBudnik** [comment]
Works well in `7.1.1` and doesn't break in `8.0.0-rc1`.

`8.0.0.-rc1` demo https://jsfiddle.net/handsoncode/76mxpyvu/
