### ISSUE TITLE
Array data is not handled correctly in populateFromArray

### ISSUE THREAD

**Issue by jdmcnair** [handsontable/handsontable#5675]
### Description
If cell data is represented by an array, and the array data changes from a populated array to an empty array (or vice versa), the `populateFromArray` code produces a null change set. This happens because the value passed to `duckSchema` resolves differently for an empty array than for an array with elements. This happens in other scenarios as well, say where a populated array has string value selections and the changed strings are different lengths.

### Steps to reproduce

1. Use an array data type for a column. I'm using a custom multiselect editor, which is how the array data is being edited.
2. Change the array selection from an array with at least one element to an empty array.
3. See that the changes are rejected because the changeset returned from `populateFromArray` is null.

### Demo

I've created pull request #5676 with a unit test that demonstrates the issue.

### Your environment
* Handsontable version: 6.1.1
* Browser Name and version: Chrome 70.0.3538.102
* Operating System: Win10

**Comment by AMBudnik** [comment]
Thank you very much for spotting that and sharing the pull request, Jason.

**Comment by AMBudnik** [comment]
And another change for v`7.0.0` :) Thank you @jdmcnair
