### ISSUE TITLE
Hiding rows based on data 

### ISSUE THREAD

**Issue by AncaWebDev** [handsontable/handsontable#5679]
I have a table of more than 10.000 rows and one of thee columns is "status" and the options are "complete" and "incomplete"

Is there a way in which when you press a button the table only renders the rows which have a status of "incomplete"?

For example in this fiddle, I would like to hide all the rows where the political party is "democratic" when I click on a button.

https://jsfiddle.net/r0f5xavk/?utm_source=website&utm_medium=embed&utm_campaign=r0f5xavk

Thanks

**Comment by AncaWebDev** [comment]
Sorted, thanks anyway!

**Comment by AMBudnik** [comment]
Thank you for the update.

I guess that we can close the issue.
