### ISSUE TITLE
Pasting text into "contains" filter value does not filter data

### ISSUE THREAD

**Issue by duklewski** [handsontable/handsontable#5680]
### Description
What is happening: When pasting text (with the mouse) into a filtering menu the filter is not applied.
What should happen: The filter should be applied to the dataset.

### Steps to reproduce

1. Copy data from a column that has a filter (i.e. "et" from column B in the demo)
2. Click the filter dropdown and select "Contains"
3. Right-click in the "Value" field that appears and select "Paste" from the menu
4. Click "Ok"
5. See that the filter dropdown is highlighted green but the spreadsheet was not filtered
6. See that if you open the filter dialog again the "Value" field has no data

### Demo
This can be demo'ed in the documentation itself: https://handsontable.com/docs/6.2.1/demo-filtering.html

### Your environment
* Handsontable version: 5.0.2 (but issue still exists in version 6.2.1
* Browser Name and version: Chrome 70.0.3538.110
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
Thank you for sharing. I have replicated it on a Mac / Chrome 71 as well.

The issue is present only when we use a menu to paste the value, keyboard shortcut works as expected.

**Comment by AMBudnik** [comment]
This issue got solved by hiding the menu for paste @duklewski 
Now you can only paste the value using CMD/CTRL + V which filters the rows.
Demo updated to https://jsfiddle.net/ne10p4uc/1/ 8.0.0 (working well)
https://jsfiddle.net/ne10p4uc/2/ 7.4.2 (working well)
