### ISSUE TITLE
Not able to distinguish between normal cells and non-editable cells where "editor":false

### ISSUE THREAD

**Issue by vk-sourcefuse** [handsontable/handsontable#5681]
### Description

Not distinguish between normal cells and non-editable cells where "editor":false
We want to add some css of backgroud-color & text-color to visually see cells where editor is false.
As you can see by inspect-element there is no class added on cell columns / cells where we can add some css.

### Steps to reproduce

1. Visually there is no difference in such cells
2. Inspect element, there is no class also on such cells
3. So, basically not able to add css on such cells

### Demo

https://handsontable.com/docs/6.2.1/demo-disabled-editing.html

### Your environment
* Handsontable version: latest
* Browser Name and version: chrome

**Comment by AMBudnik** [comment]
Hey @vk-sourcefuse 

If you're the one who makes the cells `editor: false` you can add the class the same way as you disabled the editor. In this case https://handsontable.com/docs/6.2.1/demo-disabled-editing.html you can add

```
  {
      data: 'car',
      editor: false,
      className: 'your-class'
    },
```
sample: https://jsfiddle.net/o75phuvm/

Can you share your case scenario? Even when the settings come from a database you are still using `cells`/`cell` or `columns` method to switch the editor state.

**Comment by vk-sourcefuse** [comment]
Hi, adding :
className: "htCenter htMiddle custom-disable-class" 
worked fine.
Closing this issue. 

Thanks again for your help . :+1:
