### ISSUE TITLE
Row and col headers disapper when modal reopen

### ISSUE THREAD

**Issue by arifemrecelik** [handsontable/handsontable#5685]
### Description
I'm using Handsontable in a modal.

**What is happening:** When you reopen modal I can't see row and col headers of Handsontable.
**What should happen:** They shouldn't disappear 

### Steps to reproduce

1. Put HotTable to in a modal.
2. Open and close modal.
3. When you try to reopen modal, most probably you won't see row and col headers

### Demo
![chrome-capture](https://user-images.githubusercontent.com/9434244/50275603-c3c6ef00-0450-11e9-9f74-4003481cf5d0.gif)

I just clicked for the see row and col headers.

### Workaround
When I faced with this problem, I noticed that one part of css was like that.

![image](https://user-images.githubusercontent.com/9434244/50275774-3e900a00-0451-11e9-8bac-9336f6449580.png)

When I overwrite it as `visibility: visible`, it fixed. But I'm not sure will it break something in future or not? Could you give me some detail about what is doing this css part?

### Your environment
* Handsontable version: 6.1.1
* Browser Name and version: Chrome 71.0.3578.98
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
Hey @arifemrecelik 

can you share any demo where this issue can be replicable?

**Comment by arifemrecelik** [comment]
Hello @AMBudnik ,

Sorry I couldn't share a jsfiddle demo. But I created a git repo for reproduce the issue.

https://github.com/arifemrecelik/handsontabletest.git

**Comment by AMBudnik** [comment]
Thank you for sharing.

I have replicated the issue. It looks like the React wrapper does not respond to the Modal window.

**Comment by Fluorz** [comment]
+1

**Comment by swistach** [comment]
Hi @arifemrecelik, @Fluorz,
In `handsontable@8` and `@handsontable/react@4` `<HotTable> ` seems to work as expected: https://codesandbox.io/s/elastic-brook-4c0xu?file=/src/App.js

I close this issue. If you will face this problem again after migration let us know here.
Thank you for your involvement!
