### ISSUE TITLE
Handsontable won't work inside an iframe when initialized outside of it

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#5686]
### Description
Handsontable doesn't work when created in an iframe document of a document that it has been loaded into.

The proposed fix is to use document (`ownerDocument`) of passed .H wrapper, rather than to rely on global document variable.

### Steps to reproduce

1. Create an `<iframe>` with Handsontable container inside
2. Initialize Handsontable on that container
3. Check console for error

### Demo
https://codepen.io/jacekbogdanski/pen/pqEaOY

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Firefox
* Operating System: OSX

**Comment by marek-baranowski** [comment]
+1

I would really appreciate having this fixed as this is a blocker - we have to use Handsontable inside an iframe.

**Comment by AMBudnik** [comment]
@marek-baranowski just released it in v `7.0.0`
