### ISSUE TITLE
Copying a multi-line character string will paste it with some unnecessary line breaks inserted

### ISSUE THREAD

**Issue by rooneywr10** [handsontable/handsontable#5688]
### Description

Copying a multi-line character string will paste it with some unnecessary line breaks inserted. 
When creating a table on the evaluation event registration screen, I copied the table already created in Excel and pasted it in handsontable, it was pasted with unnecessary line breaks added. 
### Steps to reproduce

Original excel sample data only cell like this:
https://pasteboard.co/HSHwt6P.jpg

### Demo

https://jsfiddle.net/p3xsc6g8/4/

### Your environment
* Handsontable version: 6.2.1
* Browser Name and version: chorme
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Hey @rooneywr10 

Can you confirm that this is the same issue as described here https://github.com/handsontable/handsontable/issues/5647?

**Comment by rooneywr10** [comment]
Hi @AMBudnik.
Thanks for your answer.
I agree with you about this ticket same issue #5647

**Comment by AMBudnik** [comment]
Thank you for a prompt reply. Please track progress to https://github.com/handsontable/handsontable/issues/5647 for updates.
