### ISSUE TITLE
beforeChange event i cahnge a value, but the relate formula calculate wrong

### ISSUE THREAD

**Issue by iaminvictus1993** [handsontable/handsontable#5689]
### Steps to reproduce

1. copy the example val in cell 0,0
2. then triggle afterChange 
3.check cell 0,2

![beforechange-formula](https://user-images.githubusercontent.com/22359049/50327553-96e70a80-052a-11e9-9164-609caa68416f.gif)

### Demo

https://jsfiddle.net/umx6fh71/3/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey @iaminvictus1993 

Unfortunately, in some cases formulas does not update upon data changes.

Here's a workaround that you can use https://jsfiddle.net/vyjcz06k/ until the issue gets solved.

**Comment by iaminvictus1993** [comment]
@AMBudnik  thanks , I want to  change Data the formula cell can calculate instantly. but  your demo is not run as my expect too

**Comment by AMBudnik** [comment]
I will investigate that issue. Till this time I leave the issue marked as a `bug`.

**Comment by AMBudnik** [comment]
Works exactly the same with the @aninde build https://jsfiddle.net/q2emgo6u/ 
The formula from `0, 2` cell does not update.

**Comment by swistach** [comment]
I'd like to add that `afterSetDataAtCell` hook (which is used in formulas and is invoked before `beforeChange` hook) added to the init settings is running after the plugin's one. In the result of that, there is no option to overwrite change through these two hooks. There are other options to manipulate data, one of them is `modifyData` hook, but there is also a simpler way to achieve this calculation. You can use `beforePaste` hook, where is possible to overwrite data to paste before it gets through `afterSetDataAtCell`: https://jsfiddle.net/m1uc59d8/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
This issue works the same when we use the new _HyperFormula_ engine. Updated demo https://jsfiddle.net/a1m74g9h/

**Comment by adrianszymanski89** [comment]
Inform [ZD](https://handsontable.zendesk.com/agent/tickets/29071)

**Comment by AMBudnik** [comment]
Hi @iaminvictus1993 

I am thrilled to announce that the release of v13.0.0 is now available! This version brings an array of exciting updates and improvements. For a comprehensive list of all the changes, please visit the following link: [Handsontable Release Notes](https://handsontable.com/docs/javascript-data-grid/release-notes/). Thank you for your support, and we hope you enjoy the latest release!
