### ISSUE TITLE
beginEditing lost initial value

### ISSUE THREAD

**Issue by Darmody** [handsontable/handsontable#5694]
### Description

Calling `const activeEditor = this.table.getActiveEditor().beginEditing()` always lost initial value.
It should begin edit with cell value as default.

### Steps to reproduce

I record a gif reproduced the issue: http://g.recordit.co/LEoC43ZToH.gif

### Demo

below is my code: 
```js
  afterChange() {
   setTimeout(() => {
      const activeEditor = this.table.getActiveEditor()
      activeEditor.beginEditing()
      activeEditor.enableFullEditMode()
    })
}

```

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Mac

**Comment by AMBudnik** [comment]
Hey @Darmody 

can I ask you to share a full demo (JSFiddle/JSBin)? It will be much easier to debug the code.

**Comment by Darmody** [comment]
@AMBudnik Hey there! Thanks for your reply.

JSFiddle demo: https://jsfiddle.net/8ffpsqt6/327/

**Comment by AMBudnik** [comment]
You're right- now's the perfect order. I can confirm.

**Comment by Darmody** [comment]
@AMBudnik Got it. Thank you!
