### ISSUE TITLE
Cant scroll page when set manualRowsMove true when use safari and chrome

### ISSUE THREAD

**Issue by moJiXiang** [handsontable/handsontable#5695]
### Description
Table still cant scroll when set manualRowsMove true when use safari and chrome

### Demo
https://handsontable.com/docs/6.2.2/demo-moving.html?_ga=2.111260998.37399556.1545879185-1389440913.1545879185

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: safari 12.0.1 (14606.2.104.1.1), chrome 71.0.3578.98
* Operating System: mac

**Comment by AMBudnik** [comment]
Hey @moJiXiang 

I'm working on MacBook Air and Chrome 71. Here the demo works perfectly. You just use the touchpad to scroll?

**Comment by AMBudnik** [comment]
I'm closing the issue. We could not replicate the issue on Windows nor Mac.

**Comment by AMBudnik** [comment]
Is there any possibility for you to check the events of the browser? We cannot replicate it on any device
