### ISSUE TITLE
Simple text cell edit non latin alphabet breaks the editor 

### ISSUE THREAD

**Issue by tran4o** [handsontable/handsontable#5696]
### Description
Broken editing & selection after submit cell edit with cyrillic chars. 

### Steps to reproduce
1. Go to the main handsontable example
2. Type in the currency column something like 'АБВГДЕЖЗИ'..
3. After pressing enter editor is broken, selected cells never get deselected and selection dom elements are created on every interaction. 
4. Handsontable gets broken after recreation too...

### Demo
https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers

### Your environment

* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71.0
* Operating System: Windows 10 Pro

**Comment by AMBudnik** [comment]
Hi @tran4o 

I can see that it works as expected when we copy/paste the content you've sent so it has to be related to the editor itself. I would need to install a keyboard on my device. Is that Tajik language?

**Comment by AMBudnik** [comment]
I have installed the Bulgarian language with the keyboard but it works well. Please check the below video

![keyboard](https://user-images.githubusercontent.com/10757813/50559669-918f7a00-0cf9-11e9-9f63-39fb4c7df8dd.gif)

**Comment by tran4o** [comment]
![2f638073-d493-43f9-ycb1-7be214443cbb](https://user-images.githubusercontent.com/1221874/50559813-17fc8980-0d03-11e9-88f9-08d4862f6a38.gif)

**Comment by AMBudnik** [comment]
I think that I am doing exactly the same. We have the same version of Handsontable, same options enabled, the same browser - only the system is different. I will have an opportunity to test this on a Windows on Wednesday.
![sample](https://user-images.githubusercontent.com/10757813/50560059-01533400-0cfd-11e9-9ca3-ad7aae9a00d0.gif)

**Comment by tran4o** [comment]
i was able to get a hacky solution , temporary fixing it in my case, i replaces some key down handler code in the built version directly, here some brief explanation : 

var onBeforeKeyDown = function onBeforeKeyDown(event) {

...
>>>>>>>>>>>>>>> replace 
 default:
      break;
>>>>>>>>>>>>>>> with 

	case 27:
	  break;
	  
    default:
	  return  (0, _event.stopImmediatePropagation)(event);

**Comment by AMBudnik** [comment]
It works on my Windows 10 Home and Pro as well. I am not able to replicate the issue.

**Comment by tran4o** [comment]
Now i know how to reproduce it. 
It's connected with the language switch shortcut (WIN+SPACE) and maybe not with particular language. To reproduce it switch the language after entering cell edit.

**Comment by AMBudnik** [comment]
Ohh I see. So this has to be the same issue as described here https://github.com/handsontable/handsontable/issues/5640
