### ISSUE TITLE
Arrow navigation on iPad Pro broken

### ISSUE THREAD

**Issue by adrianschneider94** [handsontable/handsontable#5697]
### Description
Instead of navigating to the next cell, handsontable enters the edit mode of the active cell and inserts for example `UIKeyInputRightArrow`, when I try to navigate with the arrow keys on my hardware keyboard (iPad Pro 12,9" 2015).

### Steps to reproduce
1. Select cell in any example on the handsontable.com website
2. Press an arrow

### Your environment
* Handsontable version: Whatever the website uses, probably the newest.
* Browser Name and version: Safari (AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1) and Chrome (AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/71.0.3578.89 Mobile/15E148 Safari/605.1)
* Operating System: iOS 12.1.1

**Comment by AMBudnik** [comment]
It was hard to gather the right tools to test it but we finally did the test and can confirm the bug.

Thank you for sharing @adrianschneider94

**Comment by adrianschneider94** [comment]
It works on my iPad now. Can I close the issue?

**Comment by AMBudnik** [comment]
That's great news, Adrian. What version of Handsontable works on the device?

**Comment by adrianschneider94** [comment]
I tried it on your website.

**Comment by AMBudnik** [comment]
Great, so I think that we can close the issue.

Than you for the feedback.
