### ISSUE TITLE
When StretchH and autorowsize are used at the same time, extra white space is displayed in the cell

### ISSUE THREAD

**Issue by bxfxf** [handsontable/handsontable#5701]
### Description
When StretchH and autorowsize are used at the same time, extra white space is displayed in the long string cell

### Steps to reproduce

1.Set fixed column width
2.Configuring the StretchH option and autorowsize option

### Demo

https://jsfiddle.net/k9qvd43t/2/

### Your environment
Handsontable version:.6.2.2
Browser Name and version:chrome 68
Operating System:win 10

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @bxfxf 

I have replicated the described behavior.

**Comment by AMBudnik** [comment]
Stays the same in `7.2.1` https://jsfiddle.net/3f7tz4ks (and in the latest `14/10/19 8.0.0-rc1` build)

**Comment by AMBudnik** [comment]
Just to mention, calling the `render()` method solves the issue https://jsfiddle.net/AMBudnik/xb42wLcp/

**Comment by AMBudnik** [comment]
While updating to v 8.0.0. we get the same effect. Updated demo https://jsfiddle.net/AMBudnik/72h1xfmn/

**Comment by AMBudnik** [comment]
I have created a case for issue https://github.com/handsontable/handsontable/issues/3925 as the subject is the same. We just get a bit different result as the dataset differ.
I will update this subject after fixing https://github.com/handsontable/handsontable/issues/3925
