### ISSUE TITLE
Copying some text from Excel will result in additional blank lines

### ISSUE THREAD

**Issue by bxfxf** [handsontable/handsontable#5703]
### Description

Copying some text from Excel will result in additional blank lines
See ： https://github.com/bxfxf/tmpfile/blob/master/copy1.png

### Steps to reproduce

1. copy A1 and A2 cell content from this excel : https://github.com/bxfxf/tmpfile/blob/master/test1.xlsx
2.open https://jsfiddle.net/k9qvd43t/3.  paste data to A1 and A2 cell
3.You will see some blank lines in A1 and A2 cell

### Demo

https://jsfiddle.net/k9qvd43t/3

### Your environment
Handsontable version:.6.2.2
Browser Name and version:chrome 68
Operating System:win 10

**Comment by AMBudnik** [comment]
Hey @bxfxf 

this issue sounds very much like this one https://github.com/handsontable/handsontable/issues/5647

Can you confirm?

**Comment by bxfxf** [comment]
> Hey @bxfxf
> 
> this issue sounds very much like this one #5647
> 
> Can you confirm?

Yes, they are similar.  If the excel text contains space character, it will be converted to a newline when pasted. If the excel text contains line breaks, it will produce blank lines when pasted.

**Comment by AMBudnik** [comment]
Thank you for confirmation. I think that we should stick to a single topic if they are the same but if we're missing anything in the #5647 please share a comment
