### ISSUE TITLE
hiddenColumns option interferes with keyboard movement.

### ISSUE THREAD

**Issue by ahndohun** [handsontable/handsontable#5704]
### Description
If hiddenColumns is set on the first or last column of a table row, it will no longer move if the first or last row is reached on the keyboard.

### Steps to reproduce
Continue moving left or right of the selected line with the keyboard until you move to the previous or next column.

### Demo
Examples that work as expected - https://jsfiddle.net/ak1803bj/1/
An example that fails - https://jsfiddle.net/ak1803bj/2/

### Your environment
* Handsontable version: 6.2.2

**Comment by AMBudnik** [comment]
That's an interesting case. Thank you for sharing @ahndohun

**Comment by AMBudnik** [comment]
8.0.0.-beta1 https://jsfiddle.net/q8aLv0p9/ (broken)  
8.0.0-beta2-rev2 https://jsfiddle.net/q8aLv0p9/1/ (**solved**)

**Comment by AMBudnik** [comment]
Hi @ahndohun 

I have good news! We've just released 8.0.0-beta2 that fixes the following issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment]
Hi @ahndohun 

here's a demo updated to the official (stable) version 8.0.0 https://jsfiddle.net/k7uf2qs0/

I hope that it works for you as well. I would really appreciate all the feedback.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
