### ISSUE TITLE
Filter causes Minsparerows to have problems

### ISSUE THREAD

**Issue by bxfxf** [handsontable/handsontable#5707]
### Description

Filter and minsparerows are used at the same time, and then load the data through LoadData(), Minsparerows fail to achieve the desired results.

### Steps to reproduce

1.Set Minsparerows to 7 and minRows to 10.
2.Set filters to be true.
3.load the data through LoadData(), 
4.You will see 7 blank lines displayed between line 10th to 17th instead of the end.

### Demo

https://jsfiddle.net/k9qvd43t/4/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: chrome 71
* Operating System: win 10

**Comment by AMBudnik** [comment]
Thank you for sharing the example @bxfxf 
You're right the `filters` cause this issue.

**Comment by rupesh-verma** [comment]
hi.
i'm also facing same problem please suggest me right solution

**Comment by AMBudnik** [comment]
This issue hasn't been scheduled yet. Once we get any updates here I'll ping you @rupesh-verma

**Comment by AMBudnik** [comment]
@wojciechczerniak you were right with this topic
It is fixed with the latest build (`24/09/19`). Updated demo https://jsfiddle.net/handsoncode/ar47kcm1/

**Comment by AMBudnik** [comment]
Demo updated to 8.0.0.-beta1 working well https://jsfiddle.net/6gLzf2ck/

@bxfxf @rupesh-verma please try it out and leave a feedback

**Comment by bxfxf** [comment]
> Demo updated to 8.0.0.-beta1 working well https://jsfiddle.net/6gLzf2ck/
> 
> @bxfxf @rupesh-verma please try it out and leave a feedback

Yes, it is fixed on 8.0.0.-beta1 build.Thank you very much!

**Comment by AMBudnik** [comment]
Great! Thank you for feedback @bxfxf

**Comment by AMBudnik** [comment]
Hi @bxfxf @rupesh-verma 

we can officially closed this issue as fixed. I've just tested it with the new version fi Handsontable 8.0.0 https://jsfiddle.net/4s9kxa5n/ and it works great. 

Again, thank you for sharing :-)
