### ISSUE TITLE
request new method to get cell merge

### ISSUE THREAD

**Issue by ByboyCn** [handsontable/handsontable#5708]
Dear
  I need a method to get cell merge ,but I didn't find this method in the api documentation, can you add this method?

**Comment by ByboyCn** [comment]
https://jsfiddle.net/Byboy/ughaze9s/6/
look is
I found a method in lssues 

> #1765

 and tested it, but the results were not good. When I use "hotInstance.mergeCells.mergedCellInfoCollection", I am prompted that MergeCells is empty, so it cannot be used.

**Comment by AMBudnik** [comment]
Hey @ByboyCn 

you would like to check if a cell will some coordinates is a part of a merged area or you want to get an array of merged cells coordinates?

**Comment by ByboyCn** [comment]
hi @AMBudnik 
I want to cache the handsontable so that it can be rendered again, so I need to get all the data of the table. I also need to get all the merge information in this table.

**Comment by ByboyCn** [comment]
I need a function to get the coordinate information of all merged cells

**Comment by ByboyCn** [comment]
hi @AMBudnik 
Thank you very much, I thought there was a simpler solution, so I asked~
you can close my question.

**Comment by ByboyCn** [comment]
hi @AMBudnik 
Thank you very much, I thought there was a simpler solution, so I asked~
you can close my question.

**Comment by RockNHawk** [comment]
Excuse me ,could you tell me how can I get the full into of the mergedCell array, the old API not work now ?

**Comment by RockNHawk** [comment]
I resolved my problem:

var hc = hot.getPlugin('mergeCells').mergedCellsCollection.mergedCells;
console.log("hc",hc)

**Comment by suheweiyang** [comment]
i have the same problem too, have you  solved it ???

**Comment by suheweiyang** [comment]
> i have the same problem too, have you solved it ???

not after event , it's no use for this

**Comment by AMBudnik** [comment]
hey @suheweiyang the `afterMergeCells` hook doesn't work for you? 
Updated demo https://jsfiddle.net/AMBudnik/h2x14tuL/

**Comment by suheweiyang** [comment]
no,i need a collection of all the merge range,but in this, it's just one , if i push it in array everytime i merged . if i want to render this table again, 


There's a lot of redundant data in this.





------------------ 原始邮件 ------------------
发件人: "Aleksandra Budnik"<notifications@github.com>; 
发送时间: 2019年5月17日(星期五) 晚上7:03
收件人: "handsontable/handsontable"<handsontable@noreply.github.com>; 
抄送: "Mr.Chen"<361065284@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [handsontable/handsontable] request new method to get cell merge(#5708)




hey @suheweiyang the afterMergeCells hook doesn't work for you?
 Updated demo https://jsfiddle.net/AMBudnik/h2x14tuL/

**Comment by suheweiyang** [comment]
i need a collecton,if everytime i merged and record it , it too much and useless



------------------ 原始邮件 ------------------
发件人: "Aleksandra Budnik"<notifications@github.com>; 
发送时间: 2019年5月17日(星期五) 晚上7:03
收件人: "handsontable/handsontable"<handsontable@noreply.github.com>; 
抄送: "Mr.Chen"<361065284@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [handsontable/handsontable] request new method to get cell merge(#5708)




hey @suheweiyang the afterMergeCells hook doesn't work for you?
 Updated demo https://jsfiddle.net/AMBudnik/h2x14tuL/

**Comment by suheweiyang** [comment]
damned, i fixed this, the way to get all mergeData like this:
        let mergeData =this.$refs.table.hotInstance.getPlugin('MergeCells').mergedCellsCollection.mergedCells;
console.log(mergeData)

**Comment by suheweiyang** [comment]
> hey @suheweiyang the `afterMergeCells` hook doesn't work for you?
> Updated demo https://jsfiddle.net/AMBudnik/h2x14tuL/

Thanks for your help
