### ISSUE TITLE
Pressing Enter when in numeric field of last do not focus on next row.

### ISSUE THREAD

**Issue by faizalsomani** [handsontable/handsontable#5709]
### Description

When in a numeric field column in last row, inserting a value and pressing enter creates a new row after it but focus do not go to the new row. It works for text field column.

### Demo

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29962323/50859694-10239180-1362-11e9-8d96-2d61c1774b66.gif)

### Your environment
* Handsontable version: 0.31.2
* Browser Name and version: chrome
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Hey @faizalsomani 

Have you already solved the issue? If not please share your settings and I'll reopen the issue for you.

**Comment by jpatel3** [comment]
How did you resolve this? I am running into something similar where numerical value column, hitting enter moves the focus to next column when its last row, compare to categorical attribute column, it keep adding new row and moves the focus to next row.

**Comment by AMBudnik** [comment]
Hi @jpatel3 the issue was closed as we couldn't replicate the issue using our default documentation examples and author did not send a code sample. If you could share a demo with steps on how to replicate the issue we'll do our best to help.

Generally, and we can see this here https://handsontable.com/docs/javascript-data-grid/numeric-cell-type/, when you edit the last cell in the grid (and this is also a numeric cell) the focus after hitting <kbd>ENTER</kbd> does not change, only the editor is closed. You can alter that behavior using [the `enterMoves` option](https://handsontable.com/docs/javascript-data-grid/api/options/#entermoves).

**Comment by jpatel3** [comment]
I think thats correct, as last cell in grid in that column is numerical for numerical column

**Comment by AMBudnik** [comment]
@jpatel3 there are some variables missing, but with the current `enterMoves` configuration (tested at https://jsfiddle.net/handsoncode/8b9yspxj/) it seems that it works well (on Enter selection moves to a row below it or stays if the changed row is the last one). But I can see that you have some custom logic for the `afterChange` hook so maybe that changes the thing. Can you apply those changes to the demo?

**Comment by jpatel3** [comment]
@AMBudnik I think if there is a value, it moves perfectly fine in our code as well, you can try here in interactive manner - 
https://tuvalabs.com/dataset-uploader/userdataset/

Click on Insert Data button in middle, and that should give you edit mode for handsontable.  

In the example you provided on jsfiddle, it doesn't add dummy row automatically if its last row, I can give it a try to add that logic and see if we see same behavior. 

In our environment, first row is attribute name or header and subsequent are values. `afterChange` does nothing but helps us to keep track of the changes.  We keep track of the table updates to update the visualization tool above, so it helps to communicate on changes applied.

**Comment by AMBudnik** [comment]
Hi @jpatel3 

Do we have any updates here?

> I can give it a try to add that logic and see if we see same behavior

**Comment by jpatel3** [comment]
@AMBudnik We were able to tweak the logic to get desired behavior based on your suggestion.

**Comment by AMBudnik** [comment]
I am more than happy to hear that, thank you for the update @jpatel3
