### ISSUE TITLE
[Discussion] Best practice to set (customized) styles to cells?

### ISSUE THREAD

**Issue by DongShi** [handsontable/handsontable#5710]
### Description
Hey, there.
We are now deploying HOT in production and meet some performance quirks. 
See the following console logs:
![image](https://user-images.githubusercontent.com/5009987/50881123-a1a30a00-141b-11e9-9dce-721764cf5815.png)

I think the reflow is caused by styling, so please read on:

Our scenario requires A LOT of styling of the TD, TH cells of HOT.
Based on different appTheme, tableTheme and other variables, various borders, background and font related styles are applied to HOT cells, like the following:
![image](https://user-images.githubusercontent.com/5009987/50880983-2e00fd00-141b-11e9-9a10-804d2bd0c77d.png)

Note that user can also change these colors on UI **for individual cells.**

our current approach is to split the styles into two kinds:
1. defaults styles
These are fixed styles and we prepared several css files form them. To make them work, we add some class string to needed cell in cells function, like 

```javascript 
cells (row, col, td) {
    isTitleCell(td) {
        addClass(td, 'titleClass')
    }
}

```
2. dynamic styles.
These are viable styles and we modify the styles property of the cell directly, also in cells function, like

```javascript 
cells (row, col, td) {
     hasUserSetFont(td, font) {
        td.style.color = font.color  
    }
}

```
I am wondering if there is any guide line from HOT team to apply the styles efficiently?

I myself also search the HOT document, and find that you do have some pointers on [optimizing css](https://handsontable.com/docs/6.2.2/tutorial-good-practices.html),  I want to add two comments:
1. it seems Object.assign is equally good as cached style (https://jsperf.com/change-css-in-many-ways/11)
2. While cssText way is very slow, but it only cause one reflow, right? Cached style would cause multiple reflow, no?  (I could be wrong on this)

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Yes, you can define a custom renderer in the `cells` method as well.

> how to add styles in a batch mode to avoid DOM reflow?
I'll check it out and let you know.

**Comment by AMBudnik** [comment]
Hey @DongShi 

I had a discussion with our developer said that if you're using the `cells` method you're already doing it the best way for the batch mode

**Comment by DongShi** [comment]
Hey @AMBudnik 
Thanks for the info, again, I want a double-confirm, because this is important for us:
I am using the custom renderers under cells function.
And inside the renderer, I am assigning styles to TD/TH, I guess this also can also benefit your 'batch' architecture, right?
```javascript
cells (row, col, td) {
let cp = {}
    isTitleCell(td) {
        cp.renderer = myRenderer,
        cp.className  = 'titleClass'
    }
return cp
}

function myRenderer(TD, row, col) {
   handsontable.renderers.NumericRenderer.apply(this, arguments);
   if (shouldColorItRed) {
      TD.style.color = 'red'
   }
   if (shouldHideBorder) {
     TD.style.border = 'none'
   }
   ....
}

```

**Comment by DongShi** [comment]
Ok, this is where problem happens,: we let user set customized style on each single cells as they will (border, background, font), there is no such possibility to mapping each style to a 'class', for example, the color (font color, background color, border color) can be set via a color-picker (resulting in a dynamic RGBA value),

What's your suggestion to handle such requirement, if not using renderer?
@AMBudnik

**Comment by AMBudnik** [comment]
Hows is the user changing the color? Maybe you could use a color picker to create a CSS class in the JS. Here is an article on Stackoverflow https://stackoverflow.com/questions/1720320/how-to-dynamically-create-css-class-in-javascript-and-apply that will help you to create CSS classes dynamically.

**Comment by DongShi** [comment]
Good Question, @AMBudnik 
In our product, use can choose to style cells with editors, like the following(The ones in red highlight are color pickers), They can change not just colors, but also font and other formats:

![image](https://user-images.githubusercontent.com/5009987/51483441-03785200-1dd4-11e9-9b4b-6dae43de0d99.png)


Moreover, user can pre-set the style of target cells in many other ways, one of which is via something we called thresholds or conditions. 
The idea is simple: user can define some (complex) formula like,

>
> 1) if the day-of-week is Monday and
> 2) our profit is 2M$ or lower and
> 3) however one year ago, the profit was 3M,
> 
> Then put all cells under profit in red background, underlined font and dashed borders


And these are NOT shared formats across tables, which means if you set some style in a table, that style works for that table only. I believe these requirements are common in data analysis products like domo, qlick or tableau.

I think your proposed article works in a small scale, for each styling user set, adding a style script in head. And I will give a try and see how it fits if there is a big number of table (and a lot of user-set stylings) in the system.

Thanks for the reply :)

**Comment by AMBudnik** [comment]
That's a pretty complex solution. Handsontable is styling grandpa. It can understand and do some basic stuff, but when you ask it to add many styles, formulas, and switch between them smoothly then there could be a problem - it just wasn't designed this way.

**Comment by DongShi** [comment]
I surely understand HOT is not designed for such scenario, but I do think that similar requirements would appear if not from us, then from others.

To share some funny facts, for those mentioned products (domo, qlick, etc), they almost all use home-made table solutions.
For us, before we decide to adopt HOT, we actually did a review of available options in the market (agGrid, antd grid, jquery table, HOT, spreadJS, etc), and it seems NONE can fit the styling scenario (even though spreadJS looks a bit more promising).

So why not you guys make HOT the first one to meet? 
Just my two cents. 😆

**Comment by AMBudnik** [comment]
When the first lines of the Handsontable had been written it was just a tool to show data, nothing fancy or smart. After it gained popularity users and contributors kept asking about the features related to logic: sorting, moving, filtering and we kept on adding new logic. Now it is really difficult to make it more responsive and styling-friendly.  Some of the changes would require digging deep inside the core. But... it's also something that won't skip us. Sooner or later we need to make it possible.

**Comment by DongShi** [comment]
Really appreciate it.

But I want to get myself right: conditions and thresholds are surely NOT in a table solution's scope. I just hope that HOT can make styling on cell faster.

In our product, we just use HOT as viewers to display calculated data and styles (some are css, some are style attributes for those conditions and thresholds ).

Keep up the good work. :)

**Comment by AMBudnik** [comment]
>  I just hope that HOT can make styling on cell faster.

we are actually working on it from the beginning of January, but... that's a huge task so we'll need to wait a bit longer for some new commits being pushed on the public.

> Keep up the good work. :)
👍 thanks
