### ISSUE TITLE
Nested rows `collapseAll()` and `expandAll()` very slow on large data sets

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5711]
### Description

With larger data sets the `collapseAll()` and `expandAll()` APIs freeze the UI and take awhile to complete. In my real app I've seen it take as long as 30 seconds. I ran into this with `nestedRows` but I also tried using `trimRows` directly and had similar issues. Profiler shows a lot of time spent in `arrayEach` and `collapseMultipleChildren` as well as repeated GC activity. 

Did a little profiling and I'm not totally clear, but it seems to be spending a lot of the time in this function: https://github.com/handsontable/handsontable-pro/blob/af54e7ea124d594fef9058e2b7ca0b2160fd3a39/src/plugins/nestedRows/ui/collapsing.js#L111

The `(anonymous)` function below is the callback in the `arrayEach` linked above:

![image](https://user-images.githubusercontent.com/2973900/51001221-58c38200-14fd-11e9-9cad-1c90942c40b5.png)

![image](https://user-images.githubusercontent.com/2973900/51008387-8e766400-1519-11e9-95fe-a361d55a728e.png)

I am not sure but since `rowsToTrim = rowsToTrim.concat(this.collapseChildren())` is creating a new array with every iteration, possibly that is causing memory allocation churn and GC which slows things down? Maybe `rowsToTrim.push(...this.collapseChildren())` would improve things?

### Steps to reproduce

1. Open https://jsfiddle.net/k74xfL5d/ which is table with 5000 rows and 20 nested rows for each row.
2. Click "Collapse All", which calls `getPlugin("nestedRows").collapsingUI.collapseAll()`
3. Note the UI freezes for a number of seconds

### Demo

https://jsfiddle.net/k74xfL5d/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71.0.3578.98
* Operating System: macOS Mojave 10.14.1

**Comment by aaronbeall** [comment]
I hacked at the code and found that I got a huge speed improvement by changing the implementation of [`collapseMultipleChildren()`](https://github.com/handsontable/handsontable-pro/blob/af54e7ea124d594fef9058e2b7ca0b2160fd3a39/src/plugins/nestedRows/ui/collapsing.js#L107) and [`expandMultipleChildren()`](https://github.com/handsontable/handsontable-pro/blob/af54e7ea124d594fef9058e2b7ca0b2160fd3a39/src/plugins/nestedRows/ui/collapsing.js#L294) where it used `concat()` to
```
    arrayEach(rows, (elem) => {
      rowsToTrim.push(...this.collapseChildren(elem, false, false));
    });
```
and
```
    arrayEach(rows, (elem) => {
      rowsToUntrim.push(...this.expandChildren(elem, false, false));
    });
```
respectively, along with changing [`untrimRows()`](https://github.com/handsontable/handsontable-pro/blob/af54e7ea124d594fef9058e2b7ca0b2160fd3a39/src/plugins/trimRows/trimRows.js#L172) implementation where it was using `arrayEach()` and `splice()` to
```
this.trimmedRows = this.trimmedRows.filter(r => rows.indexOf(r) == -1)
```

I'll put together a PR for this in the morning.

**Comment by AMBudnik** [comment]
Fixed! :) Thank you for contributing.
