### ISSUE TITLE
prepareHorizontalAlignClass function may have some porblem?

### ISSUE THREAD

**Issue by iaminvictus1993** [handsontable/handsontable#5714]
### Description

this function merge my custom className, and I think it should be
```
// origin
var replacedClassName = className.replace('htLeft', '').replace('htCenter', '').replace('htRight', '').replace('htJustify', '').replace('  ', '');

var replacedClassName = className.replace('htLeft', '').replace('htCenter', '').replace('htRight', '').replace('htJustify', '').replace('  ', ' '); //temp change '' to ' ', may regex better
```
the same as prepareVerticalAlignClass

### Demo
![preparehorizontalalignclass](https://user-images.githubusercontent.com/22359049/51164129-ebd23280-18d6-11e9-9210-62ca0f285c97.gif)

### Your environment
* Handsontable version: 6.2.0
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey,

Can you share the full code (demo)? I do not know how to help

**Comment by iaminvictus1993** [comment]
[demo](https://jsfiddle.net/rh0g3v4p/)

step: 
1. change cell 0,0  alignment to right
2. check cell 0,0 cellMeta className

**Comment by AMBudnik** [comment]
Oh yes, it erases your class. You'd need to create a custom context menu to keep the class that adds the red color while manipulating the alignment.
