### ISSUE TITLE
Feature: Floating objects (such as charts and images)

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#5715]
I would like to insert images, charts, and other elements into my spreadsheet. These objects should be scrollable and work with virtual rendering.

There are several requirements that should be taken into consideration, namely:

1. How to calculate the position of the object on the grid?
2. Where (and how) to keep the coordinates of particular objects?
3. How to render objects "entering" the viewport? It should be dependent both on the size of the viewport **and** the object.

**Comment by leriel** [comment]
4. How to make objects scroll with rest of the grid

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
