### ISSUE TITLE
How can i merge two rows in the nestedHeaders

### ISSUE THREAD

**Issue by momolela** [handsontable/handsontable#5717]
### Description

How can i merge two rows in the nestedHeaders,like this.
![image](https://user-images.githubusercontent.com/12458848/51247060-ef44e700-19c6-11e9-825d-1c630ff56847.png)

**Comment by AMBudnik** [comment]
The `rowspan` option for the nestedHeaders is not yet supported.

related topic: https://github.com/handsontable/handsontable/issues/191
