### ISSUE TITLE
Custom Filter + nestedHeader lose input

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#5720]
### Description
hello,
i use the custom implementation for filter PRO and nestedHeaders.
if i enter a letter , the hansontable is filtered but i can't see the letter i type.

if i remove nestedHeaders , it works
regards
jm

![image](https://user-images.githubusercontent.com/11042160/51265962-47292100-19ba-11e9-8397-1162c97c0256.png)

i type the letter l
![image](https://user-images.githubusercontent.com/11042160/51265987-5ad48780-19ba-11e9-9550-c87949865c3e.png)

### Demo
https://jsfiddle.net/jeanmarc/be7afnwr/1/

### Your environment
* Handsontable version:6.0.0
* Browser Name and version: chrome 71
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Hey @jeanmarc78 

the letter is not visible as the table rerenders. You'd need to attach it once again to make it visible.

**Comment by jeanmarc78** [comment]
hello,
what do you mean by " attach it once again to make it visible" ?
have you an example ?

best regards
jm

**Comment by AMBudnik** [comment]
In the `debounceFn` method you call `filter()` which repaints the table and as long as the input's `innerHTML` is null (it is not added or modified in the `getInitializedElements` function) it gets erased after rerendering the table.
You should be able to use the `getInitializedElements` with a new parameter, which is content, after line `13` where you call `filter()` (rerender the table).
It surely isn't the only way to do it but I hope that it is more clear now.

**Comment by jeanmarc78** [comment]
ok i understand now .
the stange thing or not is when an handsontable without nestedHeader is filtered , it's not necessary to add  the new parameter in getInitializedElements

regards
jm

**Comment by AMBudnik** [comment]
Yes, you're right. It might be a matter of ordering the operations. It is a subject for further investigation.

**Comment by hemantnigam** [comment]
@jeanmarc78 Could you please provide the sample code for how you resolved the Issue. I'm also facing the same issue.

**Comment by jeanmarc78** [comment]
hello
https://jsfiddle.net/jeanmarc/be7afnwr/81/

regards
jm

**Comment by hemantnigam** [comment]
Thanks @jeanmarc78

**Comment by wojciechczerniak** [comment]
Issue very similar to #1540. Handsontable should be able to rerender the table whenever it's necessary. So we have to store the value and set it again when renderer requests the headers. Exactly what the author of this thread did 👍 

Without nested headers it would be needed eventually (the example in #1540 doesn't have them). I think we can mark this as solved.

**Comment by hemantnigam** [comment]
Hi @jeanmarc78 

We are implementing datatable with **nestedheaders** having more than **1000 rows**.
For **Pagination**, we are using 
         hot.updateSettings({
              hiddenRows: {
                rows: that.getArray(clicked),
                indicators: false
              }
          });
So updateSettings is taking a lot of time to render update handsontable and screen freezes while rendering.

So, Could you please help us in improving the performance of the table.

**Comment by AMBudnik** [comment]
Hey @hemantnigam that doesn't tell us much (demo https://jsfiddle.net/handsoncode/jtfwdk2u/). As this topic is already closed please send me the details on email support@handsontable.com
