### ISSUE TITLE
scrolling autocomplete Editor cause whole table to scroll and the dropdown list display issue

### ISSUE THREAD

**Issue by angelina999990** [handsontable/handsontable#5722]
### Description
 + Issue 1: When open an autocomplete editor and scroll up in a scrollable table, the editor will overlap the column header.
 + Issue 2: When scroll on the long dropdown editor, it causes the whole table to scroll.

[refer to #5629 ](https://github.com/handsontable/handsontable/issues/5629)

### Steps to reproduce
1. open https://jsfiddle.net/jcb9g0hp/.
2. open on of the dropdown editor on the 'Chassis color' or 'Bumper color'
3. scroll the dropdown list

### Demo
https://jsfiddle.net/jcb9g0hp/

### Your environment
* Handsontable version: v6.2.2
* Browser Name and version: Chrome - Version 71.0.3578.98
* Operating System: Mac OS 10.13.3

**Comment by AMBudnik** [comment]
Thank you for sharing the issue. It is already reported at https://github.com/handsontable/handsontable/issues/5105

Please track changes to https://github.com/handsontable/handsontable/issues/5105

**Comment by angelina999990** [comment]
> Thank you for sharing the issue. It is already reported at #5105
> 
> Please track changes to #5105

What about the second issue,  scrolling on dropdown list causes the whole table to scroll ??

**Comment by AMBudnik** [comment]
Sorry, I did not mention that.
That is our current intended behavior.
