### ISSUE TITLE
Re-ordering not working properly for computed columns

### ISSUE THREAD

**Issue by harishrathor** [handsontable/handsontable#5724]
### Initially loaded Table before reordering column : 

![before column move](https://user-images.githubusercontent.com/17585779/51383155-a617a300-1b3e-11e9-9937-064267f1b7b4.png)

### After reordering
![after column move](https://user-images.githubusercontent.com/17585779/51383178-b6c81900-1b3e-11e9-9d75-c1a992072fa6.png)

And also immediate next column values are also being replaced by moved column (Refer to 'Offer Code' Column in the attached imaged)
### Environment
* Handsontable version:   "handsontable": "6.1.1", "@handsontable-pro/angular": "^3.0.0", "handsontable-pro": "^6.1.1"
* Browser Name and version: Chrome (Latest)
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hey @harishrathor 

Could you attach a demo?

**Comment by AMBudnik** [comment]
I guess that we close the issue as there's no feedback for 10 days.
