### ISSUE TITLE
Can drag down in edit state?

### ISSUE THREAD

**Issue by wayne798** [handsontable/handsontable#5728]
### Description

When I edit one cell , I want to drag down to fill the next cells like excel , but now I have to make this cell lose focus , after this i can drag down from that cell to auto fill the next cells.
### Steps to reproduce

1.edit one cell, now how to drag down to fill the next cells
2.I have to make this cell lose fouce, then I select this cell again , now I can drag down 
3.How can I drag down from the cell which i just input a string?

### Your environment
* Handsontable version: development
* Browser Name and version: firfox 64.02
* Operating System: Mac os sierra

**Comment by AMBudnik** [comment]
Hey @wayne798 

I have discussed with our CTO about this subject and we decided not to treat it as a feature. Google Sheets also does not allow the user to autofill the values with an opened editor.
However that you for sharing the idea. We are always eager to hear about new ideas.
