### ISSUE TITLE
how to remove selected row in a handsontable using pop method in jquery 

### ISSUE THREAD

**Issue by chethan1095** [handsontable/handsontable#5729]
I have a handsontable which looks like this below image 
![sky2 3](https://user-images.githubusercontent.com/33021783/51453700-f5d8b300-1d66-11e9-8948-5582a9d62b6b.png)

 Now if i select something it should remove from that table for ex. **email** it should delete email. But for me it is deleting last row 

           ` var text = $(e.target).text();     `     
            var result = this.data.filter(function (obj) {
                return obj.columnsexpo === text;
            });

` this.data.pop({ columnsexpo: text, placeholder: true });`
` this.tab.handsontable("loadData", this.data);
                console.log(this.data);`

i am writting this outside handsontable function so i don't need afterSelection function and this.alterRow

**Comment by AMBudnik** [comment]
Please share a demo with your settings.

**Comment by wojciechczerniak** [comment]
Note: Please do not modify `data` object outside of Handsontable. For all operations like that you should use `alterRow` method. Otherwise plugins won't work correctly.

**Comment by AMBudnik** [comment]
The same issue has been opened on our forum so I'm closing the GH issue https://forum.handsontable.com/t/issue-how-to-remove-selected-row-in-a-handsontable-using-pop-method-in-jquery/2844
