### ISSUE TITLE
Handsontable doesn't refresh its size after window.resize

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#5730]
### Description
Our listener's callback doesn't work correctly: [source code](https://github.com/handsontable/handsontable/blob/master/src/3rdparty/walkontable/src/event.js#L97)
Even with forced `.draw()` a table doesn't recalculate after window resize.

To-do list:
- [x] fix refresh table after `window.resize`
- [x] fix refresh table after `window.resize` even if table is not mounted to window
- [x] add a new hook `afterWindowResize()`
- [x] add public method to resize table `.refreshDimensions()`
- [ ] new blog post: `How to efficiently redraw Walkontable after resize it's container`

### Steps to reproduce
1. Initialize Handsontable
2. Resize window 
![jan-21-2019 09-13-38](https://user-images.githubusercontent.com/11849621/51460855-e5bbd600-1d5c-11e9-9b8d-fc7ade507d3d.gif)

### Demo
https://jsfiddle.net/b1jdaqLe/

### Your environment
* Handsontable version: any
* Browser Name and version: any
* Operating System: any

**Comment by wojciechczerniak** [comment]
Related issue: #2766. Should be fixed with #5747.
