### ISSUE TITLE
Set up additional selectionMode for range of cells

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5737]
### Description

As mentioned on forum https://forum.handsontable.com/t/selection-of-an-already-selected-cell/2817/6 it would be great to have more selection modes available.

_The following options relate to a single layer._

**Unite**
One united range
![unite](https://user-images.githubusercontent.com/10757813/51739918-fccb3280-2092-11e9-99e6-001aa0c429b5.png)

**Exclude**
Two ranges
![exclude](https://user-images.githubusercontent.com/10757813/51739925-048ad700-2093-11e9-8d7d-10bd53f3723f.png)

**Intersect**
One range
![intersect](https://user-images.githubusercontent.com/10757813/51740131-79f6a780-2093-11e9-96e1-7437d2ba447a.png)

**Substract**
One range
![substract](https://user-images.githubusercontent.com/10757813/51740220-b1fdea80-2093-11e9-85d6-faa2ad68eb64.png)

**Comment by somename85** [comment]
+ 1 for Unite

**Comment by sirhoe** [comment]
+1 for Unite

**Comment by AMBudnik** [comment]
Those options would also suit merging. Now when there are two areas for merged cells with the same coordinates only one of them is visible.

**Comment by dkwebtec** [comment]
can we expect this in the new version? selecting more layers is not suitable for us.

Do you have a workaround how to join layers so each cell will be selected only once but still the selected area will be non-contiguous?

**Comment by AMBudnik** [comment]
@dkwebtec this functionality requires the selection to act differently. Not only we need to change the visual aspect of the selection but also we need to define how the ranges react on operations, like: edit, copy, paste, cut, and so on.
We do not have a specification for this issue yet but we are open for suggestions.

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
