### ISSUE TITLE
Comments plugin - Setting for position

### ISSUE THREAD

**Issue by nethore** [handsontable/handsontable#5746]
### Description
Currently we are displaying handsontable in fullscreen and when we assign a comment to the column which is on the right of the table, comment editor is hidden by the window edge.

Is there any way to setup the comments plugin to display the editor below the cell ?

Thanks a lot

### Steps to reproduce
1. Create an handsontable spreadsheet in fullscreen
2. Add a comment on the right columns.
3. Try to display editor.

### Demo
<img width="549" alt="handsontable" src="https://user-images.githubusercontent.com/23243216/51898036-55127500-23b0-11e9-8e36-6a8566cece75.png">

### Your environment
* Handsontable version: 6.0.0 - Angular WRapper
* Browser Name and version: Chrome 71
* Operating System: Macos X Sierra

**Comment by AMBudnik** [comment]
Thank you for sharing @nethore 

I believe that this is the same issue https://github.com/handsontable/handsontable/issues/4785 so please leave a comment there if I'm missing something crucial

**Comment by AMBudnik** [comment]
Hi @nethore 

I have good news. We just launched the Handsontable v12.1.0, where the issue https://github.com/handsontable/handsontable/issues/4785 (about comments positioning) is fixed.

Here you can read the full list of changes https://handsontable.com/docs/release-notes/#_12-1-0.
