### ISSUE TITLE
columnSummary has no effect

### ISSUE THREAD

**Issue by hz91213** [handsontable/handsontable#5748]
### Steps to reproduce

1.
![qq 20190130144949](https://user-images.githubusercontent.com/29476419/51963592-13acc300-249f-11e9-8b9f-0d38e9424d7e.png)

2.
3.

### Demo

https://jsfiddle.net/hz91213/mvou4y2f/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Thank you for sharing. It looks like the `columnSummary` does not update upon `updateSettings` call.
Demo in vanilla https://jsfiddle.net/handsoncode/3p6ofn9q/

**Comment by hz91213** [comment]
@AMBudnik How to use updateSettings in vue? Thank you.

**Comment by AMBudnik** [comment]
Hey @hz91213 

have you tried a reference like this `this.$refs.hotTableComponent.hotInstance.updateSettings({...})`?

**Comment by hz91213** [comment]
@AMBudnik Thank you. I'll try it. I'll ask you again if I have any problems.

**Comment by AMBudnik** [comment]
ok @hz91213 

I'm closing the topic, but if you'll leave any update we'll reopen it
