### ISSUE TITLE
Nested rows with Drag and Drop feature

### ISSUE THREAD

**Issue by arvindjayakumar90** [handsontable/handsontable#5750]
We have a requirement where we should have nested rows in handsontable. In each row we should be able to add a sub row. Also the drag and drop feature should be available for all rows. In the example which was available, I was able to drag and drop only the child rows. It was not working for parent rows. Is it the existing functionality ? 

### Demo

http://jsfiddle.net/ms79dwv4/

**Comment by AMBudnik** [comment]
Please check this topic for updates https://forum.handsontable.com/t/nested-rows-with-drag-and-drop-feature/2894
