### ISSUE TITLE
Couldnt update the hidden rows while on filter

### ISSUE THREAD

**Issue by boobalganesan** [handsontable/handsontable#5752]
### Description
I tried to update the hidden rows while I am on filter, but I couldnt.

### Steps to reproduce

1. Be on filter
2. Try to update the rows that are filtered out
3. Receives error as the new data source doesnt have the filtered dataset

**Comment by AMBudnik** [comment]
Hey @boobalganesan 

I have replied to your post on the forum https://forum.handsontable.com/t/update-hot-on-both-filtered-and-unfiltered-rows-while-on-filter/2902 with the same request.

Please continue discussion on forum
