### ISSUE TITLE
selectionMode: single doesn't work in mergeCells are enabled

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5754]
### Description

The `selectMode: single` is not respected when we enable `mergeCells`

### Steps to reproduce

1. click one cell and try to select any other cells without unclicking the mouse button.

### Demo

https://jsfiddle.net/handsoncode/phqxbw61/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Windows 10

Issue reported on forum https://forum.handsontable.com/t/selectionmode-doesnt-work-while-we-use-mergecells/2760/5

### Related
https://github.com/handsontable/handsontable/issues/4859

**Comment by wojciechczerniak** [comment]
Duplicate of #5181 ?

**Comment by AMBudnik** [comment]
yup @wojciechczerniak 
I did not spot your issue as it is not marked as a bug :) closing mine.
