### ISSUE TITLE
Copy-paste from excel adds extra `\n` character 

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#5756]
### Description
When copy-pasting text from excel extra '\n' symbol is added in the middle of the copied text.

### Steps to reproduce
1. Download the following file: [Product Bug .xlsx](https://github.com/handsontable/handsontable/files/2827421/Product.Bug.xlsx)
2. Copy any cell that contains text
3. Paste it to Handsontable grid provided in JS fiddle. In console you can see how copied text look like after parsing. 
Something like this: 
![image](https://user-images.githubusercontent.com/710513/52202582-f6516d80-287f-11e9-9bca-292a4c86332d.png)
 Extra symbol is added after `B2C` word. Symbol position may vary depending on text length.

There are no any spec. symbols  in this text, you can even write you own text and then copy it.
Issue happens in `CopyPaste` plugin, `onPaste` method in the following line of code:
```
if (textHTML && /(<table)|(<TABLE)/.test(textHTML)) {
        pastedData = tableToArray(textHTML);
      } else {....
```

### Demo
https://jsfiddle.net/andrewQwer/yto7cu3L/7/

### Your environment
* Handsontable version: 6.2.0
* Browser Name and version: Chrome 72
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the issue @andrewQwer 

related https://github.com/handsontable/handsontable/issues/5647

**Comment by andrewQwer** [comment]
Yes, @AMBudnik,  you are right, it's the same issue.

**Comment by AMBudnik** [comment]
Thank you for confirmation. If we're missing something in #5647 please add a comment there.
Thanks in advance.
