### ISSUE TITLE
Last selected date instance is repeating in all new rows.

### ISSUE THREAD

**Issue by crazyjavatricks** [handsontable/handsontable#5757]
### Description

Last selected date object is coming in newly created row's date cell.
![handsontable_dateissue](https://user-images.githubusercontent.com/11722540/52192536-999a8680-2870-11e9-82f6-f5d70b0e7d98.PNG)

### Steps to reproduce
1. HandsOnTable with date cell type
2. Default value should be there for date cell or change the current date to some other within the current month.
3. Try to add new row using context menu.

4. Click on the date field. Previously selected date will be selected by default in the calendar.

_Note: This is repeating only while we selecting the date in current month ._

### Demo

https://jsfiddle.net/A6454/daowp1ge/5/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome  71.0.3578.98
* Operating System: Windows 10

**Comment by crazyjavatricks** [comment]
Thanks @AMBudnik for your update.

**Comment by adamdehaven** [comment]
This is still an issue in version `7.0.3`

In the meantime, is there a way to access the Pikaday methods in the settings like in the `datePickerConfig` options by utilizing `onOpen` or something similar?

**Comment by AMBudnik** [comment]
@adamdehaven do you mean something like this https://jsfiddle.net/30tj7kLa/?

**Comment by adamdehaven** [comment]
@AMBudnik Something like that exactly 👍

**Comment by AMBudnik** [comment]
This issue is still replicable using v8.2.0 https://jsfiddle.net/xyrwj7cz/1/ 
![bug_](https://user-images.githubusercontent.com/10757813/104917572-deebec00-5993-11eb-90ad-429f1dbc1339.gif)

**Comment by swistach** [comment]
Hi @crazyjavatricks, @adamdehaven please follow #6636.
I merge them because they are the same issue. Thank you for your involvement and detailed investigation!

**Comment by AMBudnik** [comment]
Hi @crazyjavatricks 

This issue is officially fixed in v10
You can test it here https://jsfiddle.net/ywj9m71n/1/
