### ISSUE TITLE
beforeRenderer hook should be cancellable

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#5762]
### Description
As a frequently used hook, `beforeRerender` should be able to be cancellable.
In #2152 you can find the whole context - I decided to create a separated issue to keep a definition of the problem as simple as possible.

### Steps to reproduce
1. Go to the demo
2. Cells should be empty

### Demo
https://jsfiddle.net/ej3oxc0g/

### Your environment
* Handsontable version: any
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
