### ISSUE TITLE
FixedCols/Rows bug after remove col / row

### ISSUE THREAD

**Issue by rbarato** [handsontable/handsontable#5765]
### Description
If I set fixedColumnsLeft or fixedRowsTop, remove a col/row inside that range then I try to update the fixed properties, the one that had removed items doesn't get removed.

### Steps to reproduce

1. Click on Freeze button
2. Remove any col/row inside the frozen are (cols A:C, rows 1:3)
3. Click Unfreeze

### Demo
https://jsfiddle.net/rbarato/nvr1t4bu/2/

### Your environment
* Handsontable version: 5.0.2
* Browser Name and version: Chrome 71
* Operating System: MacOS HighSierra 10.13

**Comment by AMBudnik** [comment]
Hey @rbarato 

I can see that you have a new pic on the profile 👍 

Isn't the issue the same as https://github.com/handsontable/handsontable/issues/3879 ? Looks pretty similar.

**Comment by rbarato** [comment]
HI @AMBudnik, yeah, I think the bugs can relate. The scenario is slightly different but my guess is that it shares the same root cause.

**Comment by AMBudnik** [comment]
Thank you for confirmation.

I guess that we can close the issue but check it after fixing #3879 to be sure that it's gone.
