### ISSUE TITLE
Table context menu items should have ids

### ISSUE THREAD

**Issue by s-williams** [handsontable/handsontable#5770]
### Description
Items in the table right-click context menu do not have html id attributes assigned to them.  Additionally, when creating a custom context menu item, it is not simply possible to add an id to an option - you must do a work around, see below. Ideally, the standard default context menu options would have an id and, when creating custom options, you will be able to set an id on the wrapper element just like you can set name.

IDs would be useful in selenium testing and general accessibility.

### Steps to reproduce
1. Go to demo
2. Right click in table to open context menu
3. Examine option in context menu in browser dev tools and note that there is no id for each item.

### Demo
https://jsfiddle.net/5hn1L860/

### Your environment
* Handsontable version:  6.2.2

### Workaround
When creating a custom context menu item, it is not simply possible to add an id to an option - you must instead either add an element with an id as part of the renderer or name function. This is kind of ugly. See demo below.

https://jsfiddle.net/5hn1L860/7/

**Comment by AMBudnik** [comment]
Hey @s-williams 

can you share an example on how you'd like to process the IDs? Usually, in custom options, you can process all needed information.

**Comment by s-williams** [comment]
Hey @AMBudnik. Not sure what you mean by process or custom options. Please clarify.

**Comment by AMBudnik** [comment]
Hey @s-williams 

Sure. I mean the processes, methods that you trigger before/after you get the ID from the context menu option.

**Comment by s-williams** [comment]
IDs are used in my place of work for testing with Selenium. Our implementation of which requires all interactables on our web tools to have IDs associated with them therefore IDs are needed on context menu options so that our test tools can easily interact with them.

**Comment by AMBudnik** [comment]
And would that help if you would add the IDs to labels? Here's an example http://jsfiddle.net/handsoncode/b8Lv257m/
I've added ID to the second option of the menu

**Comment by s-williams** [comment]
Yes, that is one of the workarounds I've found and it does work. Because of the ease of this workaround, this can probably be considered a low priority issue (if this is even an issue at all). However, I had not found any documentation on this or any other GitHub issue on adding IDs to the context menu and therefore felt obligated to raise this as an issue on GitHub.

**Comment by AMBudnik** [comment]
Sure, thanks @s-williams 

it would be better to have those than not 👍

**Comment by wojciechczerniak** [comment]
We're not going to add IDs everywhere. Adding them to elements is an additional operation (performance). Searching for an ID would be longer (performance) if we would pollute IDs space. If they're needed only for testing then it should be done only in that environment.  

I've added this to our todo list for documentation guides. Thanks for reporting, we didn't know that there is a need for such a guide and try to fill this gap soon.
