### ISSUE TITLE
getSourceData functions return wrong data for nested rows

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5771]
### Description

This *might* be working as designed but at the very least it's a pitfall (one that I personally fell into and spent several hours debugging until I realized this was the root cause). When `nestedRows: true` many of the source data functions (`getSourceData`, `getSourceDataArray`, `getSourceDataAtRow`, `getSourceDataAtCol`) return incorrect data (only `getSourceDataAtCell` is correct). To get the source data you'd have to use the `nestedRows.dataManager` functions, which is currently undocumented.

![demo](http://g.recordit.co/l84qYyMUqg.gif)

### Steps to reproduce

1. Open the demo: https://jsfiddle.net/3dtyqrvs/3/
2. Click on the cells
3. Note the console output, all the normal `hot.getCellData...` functions return wrong data beyond the first parent row. Gets especially funky after collapsing some rows.

### Demo

https://jsfiddle.net/3dtyqrvs/3/

### Fix

Current behavior silently fails. Fixes could be:
- If nested rows is enabled, those functions throw a meaningful error.
- If nested rows is enabled, those functions silently call through to the appropriate `dataManager` functions to get the correct data.

### Your environment
* Handsontable version: Pro 6.2.2
* Browser Name and version: Chrome
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Thank you for the investigation, Aaron.

You're right, we get half of the result for actual row and the other for the same row but when the parents are collapsed.

**Comment by AMBudnik** [comment]
Hi @aaronbeall 

can you help me to test it?

It looks like `getSourceDataAtCol` and `getSourceDataAtRow` are returning correct data in 8.0.0.-beta2-rev5 https://jsfiddle.net/p69wcvaq/

**Comment by pnowak** [comment]
Hi @aaronbeall 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by trayan16** [comment]
@pnowak I am also facing this issue. Thank you for the feedback, Do you now, when it will be released?

**Comment by pnowak** [comment]
Hi @trayan16 

You can use the 8.0.0 beta2 version.

If it comes to release stable 8.0.0 I don't want to guess.
I think that could take a few weeks.

**Comment by AMBudnik** [comment]
Another issue fixed by v 8.0.0 :) 🥳 

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases

@trayan16 all resources of 8.0.0 are online. I hope that it will also solve your issue.
