### ISSUE TITLE
beforeCreateRow hook returns different values than documented

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5772]
### Description

Issue reported on our forum at https://forum.handsontable.com/t/beforecreaterow-index-parameter-is-boolean/2932

Not sure if that is intended (used somewhere) but surely it is not a documented case.

![zrzut ekranu 2019-02-8 o 08 54 35](https://user-images.githubusercontent.com/10757813/52465530-33b74300-2b7f-11e9-93dd-9331a9f962c7.png)

And the definition file

> beforeCreateRow?: (index: number, amount: number, source?: string) => void;

### Steps to reproduce

1. `Filters` are commented. **Use context menu to add a row. In the console**, you'll find the arguments printed.
2. **Enable `Filters`, add a row via context menu.** You get another set of logs, but this time the first argument is not a number, it is a boolean value.

![zrzut ekranu 2019-02-8 o 08 51 00](https://user-images.githubusercontent.com/10757813/52465368-aecc2980-2b7e-11e9-9407-e118bd27fdea.png)

### Demo

https://jsfiddle.net/wjmug84z/

### Your environment
* Handsontable version: 6.2.2
_doesn't seem to be related to any version_
* Browser Name and version: Chrome 71
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
Duplicate of  #5585

**Comment by AMBudnik** [comment]
Thanks for checking. While the label filter is missing (hopefully be back soon) it's harder to track down the duplicates.

I'm closing the issue.
