### ISSUE TITLE
Context menu is always shown even if all items are hidden.

### ISSUE THREAD

**Issue by AndrewKuzich** [handsontable/handsontable#5784]
### Description
Context menu is always shown even if all items are hidden. 

### Steps to reproduce
1. right click any cell from first column 
2. right click any cell from oter columns except for the first one
3. compare 

### Demo
https://jsfiddle.net/akuzich/um4x5wa0/24/

### Your environment
* Handsontable version: last 
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Hey @AndrewKuzich 

thanks for sharing. We have the same issue here https://github.com/handsontable/handsontable/issues/3865. If we've missed some there please leave a comment.
