### ISSUE TITLE
RangeError: toFixed() digits arguments must be between 0 and 100

### ISSUE THREAD

**Issue by devchris** [handsontable/handsontable#5790]
### Description
The table works fine in the development environment but after deploying it to the server I'm getting the following error:

<img width="515" alt="screen shot 2019-02-13 at 6 05 54 pm" src="https://user-images.githubusercontent.com/15280263/52750556-91ea8880-2fba-11e9-824e-2b2c0774000d.png">

This is how the table looks like:

<img width="613" alt="screen shot 2019-02-13 at 6 10 50 pm" src="https://user-images.githubusercontent.com/15280263/52750611-be9ea000-2fba-11e9-9d2d-4c6094803b0e.png">

I am able to put in characters but not a number. As soon as I put in a number, it errors out. And again, this only happens on deployment on a server.

My code:

HTML:
```
<hot-table [settings]="tableSettings" [hotId]="instance"></hot-table>
```

Component:
```
const columns = [
          { data: 'time', title: 'Time', editor: false },
          { data: 'monday', title: 'Monday', type: 'numeric', },
          { data: 'tuesday', title: 'Tuesday', type: 'numeric' },
          { data: 'wednesday', title: 'Wednesday', type: 'numeric' },
          { data: 'thursday', title: 'Thursday', type: 'numeric' },
          { data: 'friday', title: 'Friday', type: 'numeric' },
          { data: 'saturday', title: 'Saturday', type: 'numeric' },
          { data: 'sunday', title: 'Sunday', type: 'numeric' },
        ];

        this.tableSettings = {
          data: this.initData,
          columns: columns,
          afterValidate: function (data, value, row, prop, source) {
            if (!value) {
                alert('Only numbers allowed!');
            }
          }
```

In this case data is just an empty object. So the table is completely empty.

### Your environment
* Handsontable version: handsontable@6.2.2 @handsontable/angular@3.0.0
* Browser Name and version: Chrome  71.0.3578.98
* Operating System: MacOS

Server this is running on is an ec2 instance on AWS.

**Comment by wojciechczerniak** [comment]
Hi @devchris,

Stacktrace for your minified app won't tell us much. Function names are obscured and line number always is 1. If you're reporting a bug in Handsontable we will need simplified demo to replicate the issue.

If you cannot replicate the issue outside your app maybe we can offer you a consulting service to debug your app? Or you can use the extended support if you have Pro version. Please contact our support@handsontable.com

**Comment by skinandbones** [comment]
I ran into this issue after upgrading packages.  I believe the issue is related to:
https://github.com/BenjaminVanRyseghem/numbro/issues/402

numbro is a handsontable dependency.  You can try using an older version of numbro and/or bignumber.js.

**Comment by arif-hanif** [comment]
i am having similar issue on react-handsontable

**Comment by AMBudnik** [comment]
Hey @arif-hanif are you able to share a demo where we'd be able to replicate the issue? If you use react here's a base that you can use to build the example https://jsfiddle.net/handsoncode/ncy2sfeo/

**Comment by arif-hanif** [comment]
i found the issue was with numbro as well not handsontable

**Comment by AMBudnik** [comment]
Thank you for sharing this information @arif-hanif

**Comment by devchris** [comment]
@jansiegel Installing numbro 2.1.1 fixes the issue! Thanks a lot!

**Comment by wentjun** [comment]
For those who are using handsontable v7.0.0 and and @handsontable/angular v4.0.0: how can we workaround this issue? 

Will it be fixed in subsequent releases?

**Comment by wojciechczerniak** [comment]
You have to install previous numbro version: `npm i numbro@2.1.1`. 

Handsontable `v7.0.1` will be released on Monday with frozen numbro version.

**Comment by seharri92** [comment]
Our issue only occurs on a built version, we are using create-react-app 2 with handsontable-pro 6.2.3 (haven't had time to upgrade to v7). It will run fine in a dev environment, but when we build the application numbro crashes the app. Explicitly installing numbro to 2.1.1 fixed our issue

**Comment by melloc01** [comment]
If you're using `yarn` you are probably looking for this: https://yarnpkg.com/en/docs/selective-version-resolutions

**Comment by nethore** [comment]
This problem is back for me and it seems https://github.com/handsontable/handsontable/blob/e7a3fab2b031ede90ff09c4fd655968511ab9d3e/package.json#L74 package.json is set up for 2.1.2.

**Comment by wojciechczerniak** [comment]
Hi @nethore,

We've updated the `numbro` recently, because Terser was patched last year. 

Which version do you use?

**Comment by nethore** [comment]
Hi, thank you for your quick answer 😉,
To be honest I've no idea, we are using angular 7.2.15 and cli 7.3.9. I will check deeper and update the post if I find out in dependencies.

**Comment by wojciechczerniak** [comment]
Maybe it's not necessary to update Angular? Updating Terser should be sufficient.

The fix was released in Terser v4.1.3: https://github.com/terser/terser/commit/9c045fd8fa110415b1d5c60c971d39cab7b4d8fb

**Comment by Calidus** [comment]
I hit this issue using:
```
handonstable 7.4.2
@handsontable/angular 5.1.0
@angular 7.2.2
```

**Comment by jeffal** [comment]
I am also hit this issue. Rolling back to handsontable 7.3.0 resolved the issue.

**Comment by AMBudnik** [comment]
Hey @jeffal can you send over your demo/implementation to support@handsontable.com? We'll check if there's something that can be done to fix it.

**Comment by jsamons** [comment]
I am still running into this issue as of v8.3.2. It would appear that the issue is still open with the numbro folks. Are there any plans to release a new version using numbro 2.1.1?

**Comment by wojciechczerniak** [comment]
@jsamons What tools do you use to build your app? Issue was solved in Terser and we don't have to lock the numbro version

https://github.com/handsontable/handsontable/issues/5790#issuecomment-587096044
