### ISSUE TITLE
BUG: Expand collapsed column, is expanding also 'child' collapsed columns, except the first child

### ISSUE THREAD

**Issue by benliq** [handsontable/handsontable#5792]
### Description
While expanding a collapsed column, it is also expanding 'child' collapsed columns, (except the first child)
Child collapsed columns should not expand or collapse while expanding/collapsing parent

### Steps to reproduce
https://codepen.io/js-ziggle/pen/WQdobO

- First collapse E and F
- Then Collapse B
- Now If you expand B, column E stay collapsed, but column F is expanded. 

On Handsontable Pro

**Comment by AMBudnik** [comment]
Thank you for sharing @benliq 

you're right `F` is expanded. It happens for `I` and `J` the same, `J` is expanded.

**Comment by AMBudnik** [comment]
Still happens in `7.3.0` https://jsfiddle.net/15xs34ro/

![GIF](https://user-images.githubusercontent.com/10757813/72521485-cbc3af00-385b-11ea-9913-0c7b48a06ffa.gif)

Here's `8.0.0-beta1` https://jsfiddle.net/15xs34ro/2/
The behavior is the same, but as this version introduces [new hooks for the collapsing plugin](https://github.com/handsontable/handsontable/pull/6203/files) it's good to check it as well.

![image](https://user-images.githubusercontent.com/10757813/72522441-fe6ea700-385d-11ea-9ae3-f14eeca6cff8.png)

**Comment by AMBudnik** [comment]
This issue is fixed with https://github.com/handsontable/handsontable/pull/6716
Demo https://codepen.io/aleksandra-budnik/pen/WNQwzMo

**Comment by benliq** [comment]
Great! Thanks a lot @AMBudnik

**Comment by AMBudnik** [comment]
As #6716 is not a part of an officially released version yet, I'll keep the issue open.

**Comment by pnowak** [comment]
In 8.0.0.-beta2-rev2 still works well - https://jsfiddle.net/8tjr9suL/4/

<img width="312" alt="Zrzut ekranu 2020-05-8 o 12 21 41" src="https://user-images.githubusercontent.com/1555809/81396930-9e5e8200-9126-11ea-808b-3890cd980bf9.png">

**Comment by pnowak** [comment]
Hi @benliq 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment]
Hi @benliq 

now it is official. The Handsontable v 8.0.0 is online and this issue is solved within.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
