### ISSUE TITLE
after insert row,there exists tow same formula,someting wrong with my code?

### ISSUE THREAD

**Issue by iaminvictus1993** [handsontable/handsontable#5793]
### Steps to reproduce

1. row 2  right click, insert row with formula
2.  row 1  right click , insert row with formula
3. check there exists two '=SUM(A3,B3)'

### Demo
https://jsfiddle.net/a79pgzkv/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by iaminvictus1993** [comment]
https://jsfiddle.net/05yvu8zq/1/     after add some extra option it work as my expect

**Comment by AMBudnik** [comment]
Hey, @iaminvictus1993 your `cells` method blocks the formulas from working.

**Comment by iaminvictus1993** [comment]
@AMBudnik  I mean  there should not exist two same formula like '=SUM(A3,B3)', I just use cells to make it look directly

**Comment by AMBudnik** [comment]
I see. Is there anything else I can do for you. As I believe

> after add some extra option it work as my expect

here you solved the previous issue.
