### ISSUE TITLE
Consider removing `stopPropagation(event);` from `dropdownMenu` `onTableClick` method

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5800]
### Description
This method is a listener for the whole table to `click` action and for that reason prevents modal dialog from opening.
Maybe `Event.preventDefault` is enough, or maybe both (`stopPropagation` and `preventDefault`) are useless and should be removed.

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Contact https://forum.handsontable.com/t/modal-dialog-does-not-open-with-dropdownmenu-enabled/2956/8 after adding the change.
