### ISSUE TITLE
Handsontable is not rendering properly in case of multiple tables in same page.

### ISSUE THREAD

**Issue by abhishek9180** [handsontable/handsontable#5801]
### Description

The table cell disappears while switching between different accordions and/or tabs and user needs to click the cell explicitly in order to make the table visible again.
In the demo given below, after clicking on any cell of each table all of them becomes visible and they don't disappear again but in local environment table disappear on switching between accordions and tabs.

![capture1](https://user-images.githubusercontent.com/16050524/53022731-c90cde00-3481-11e9-994a-651202a7910a.PNG)
(Handsontable after loading)

![capture2](https://user-images.githubusercontent.com/16050524/53022738-cc07ce80-3481-11e9-820c-b72a3d30d08a.PNG)
(Handsontable after clicking on cell)

### Steps to reproduce

1. Open the demo given below and you can see the table doesn't render properly (all cells are hidden including header except few cells)
2. click on any visible cell and the table becomes visible.

### Demo

https://stackblitz.com/edit/handsontable-example

### Environment
* Handsontable version:  "@handsontable-pro/angular": "^3.0.0", "handsontable-pro": "^6.2.2".

**Comment by AMBudnik** [comment]
Hey @abhishek9180 

this issue related only to Bootstrap (as far as I can see) and only for Angular (I've a vanillaJS demo here http://jsfiddle.net/x910e6zm/) so I'll move to Angular repository

**Comment by AMBudnik** [comment]
Issue moved to [handsontable/angular-handsontable #145](https://github.com/handsontable/angular-handsontable/issues/145) via [**ZenHub**](https://www.zenhub.com/)

**Comment by AMBudnik** [comment]
I just got a hint that you can also follow this subject https://github.com/handsontable/handsontable/issues/5322

**Comment by abhishek9180** [comment]
Hey @AMBudnik 

The issue is now fixed by calling render() method on table instance. Thanks for help 👍

**Comment by AMBudnik** [comment]
Great, Thank you for an update.

**Comment by AMBudnik** [comment]
I just wanted to update the topic as the linked issue just got solved with Handsontable v12.3.0 at https://github.com/handsontable/handsontable/issues/5322
