### ISSUE TITLE
[6.1.0+] We're no longer able to select text in readOnly cells

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5810]
### Description

We're no longer able to select text in readOnly cells

### Steps to reproduce

1. Try to select text in any of the cells. 

You should be able to select it (just like in 6.1.0).

![demo](https://user-images.githubusercontent.com/10757813/53233294-5cfec580-368d-11e9-89f6-5f36a6ba5a80.gif)

### Demo

https://jsfiddle.net/AMBudnik/pb8x50no/ 6.1.0 (broken)
https://jsfiddle.net/AMBudnik/sbf9g3qk/ 6.0.1 (working)

### Your environment
* Handsontable version: 6.1.0+
* Browser Name and version: Chrome 71
* Operating System: Windows 10

Inform forum https://forum.handsontable.com/t/copy-text-from-handsontable-grid-using-browser-only/2977

**Comment by xoneill** [comment]
Are you ever going to fix it?

**Comment by AMBudnik** [comment]
Yes, but there's no ETA yet. Here's our current task-list https://github.com/handsontable/handsontable/milestones

**Comment by AMBudnik** [comment]
Works the same in 8.0.0-beta2-rev11

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/ywbjdgv1/

**Comment by AMBudnik** [comment]
This issue is still replicable in v8.2.0

**Comment by wszymanski** [comment]
It will be fixed within https://github.com/handsontable/handsontable/issues/6372.
