### ISSUE TITLE
`getLastVisibleColumn` not working properly.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#5812]
### Description
On the current `develop` (https://github.com/handsontable/handsontable/commit/133b78ccd4488f33e398712caf1a1fe28ce503cf)  branch, the `getLastVisibleColumn` doesn't return the proper value, when scrolling to the end of the table, when the table has a css `border` applied to it.

### Steps to reproduce
1. Create a Handsontable instance with a border around the container, or go to https://jsfiddle.net/js_ziggle/d8oLe5np/
2. Scroll the table to the right until you reach the end of the table
3. Call `hot1.view.wt.wtTable.getLastVisibleColumn()` in the console

**Result:** It should return `499`, as there are `500` columns declared (and it does in `6.2.2`), but it returns `498` instead.

### Demo
https://jsfiddle.net/js_ziggle/d8oLe5np/

**Comment by swistach** [comment]
It'll be fixed by #5811.
