### ISSUE TITLE
getCellsMeta sometimes returns undefined for some of the cells.

### ISSUE THREAD

**Issue by Pradhyo** [handsontable/handsontable#5814]
### Description

[getCellsMeta](https://handsontable.com/docs/6.2.2/Core.html#getCellsMeta) sometimes returns undefined for some of the cells.

![image](https://user-images.githubusercontent.com/7895492/53277271-0d41ed80-36d1-11e9-8a53-92a709f49f8a.png)

This seems to be random and happens to different cells at different times.

In the below case, at one point all cells seem to have had metadata but after a while some cells had undefined.

![image](https://user-images.githubusercontent.com/7895492/53277563-783ff400-36d2-11e9-8eee-cf319a82a303.png)

This was causing issues when I tried to check if there are any invalid cells.

```ts
    var isTableInvalid = this.hotTablesVC.firstHotInstance.getCellsMeta().some(meta => {
      if ('valid' in meta && meta.valid == false)
        return true;
    });
```

I fixed this by ignoring cells with undefined but wanted to check if this is expected behavior.

### Steps to reproduce
This seems to be random - it has happened for different cells at different times for the same [data](https://handsontable.com/docs/6.2.2/Options.html#data) and [columns](https://handsontable.com/docs/6.2.2/Options.html#columns).

### Your environment
* @handsontable/angular: 2.0.0
* handsontable: 6.1.1
* Browser Name and version: Chrome Version 72.0.3626.109
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
Welcome @Pradhyo 

the value you get depends on the rendering and the size of the viewport. Here' s a demo with comments that can help https://jsfiddle.net/oe06w4jn/
Handsontable usually loads a couple of columns more to enable smooth scrolling.

**Comment by Pradhyo** [comment]
@AMBudnik  thanks for getting back.
How do I check if all cells in a table are valid?

I have this code now but if the metadata for some cells is undefined for the default value of `renderAllRows`, could this function return the wrong value?

```
    var isTableInvalid = this.hotTablesVC.firstHotInstance.getCellsMeta().some(meta => {
      if (meta && 'valid' in meta && meta.valid == false)
        return true;
    });
```

If this is not a reliable way to check validity of a table, what's the best way to do so?

**Comment by AMBudnik** [comment]
Have you tried the `afterValidate` hook? Here's an example https://jsfiddle.net/7m9t8vL3/ I've set it up to print only invalid values

**Comment by Pradhyo** [comment]
Got it - so I would have to track the list of invalid cells based on `afterValidate` and determine if the table is invalid based on the list of invalid cells.
I am closing because this is not related to original issue anymore.
