### ISSUE TITLE
Request: async rendering (web workers?)

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5816]
### Description

It would be amazing if Handsontable supported async rendering. In particular, when trying to initialize the table with a large data set (90k rows, for example) there is a long UI freeze, especially on slower browsers and if features like sorting are enabled. I have done some performance profiling and see a lot of time spent in the data mapper and running hooks like `modifyRow`. The table's DOM rendering is quite fast once it gets past the initialization of the data. 

### Demo
https://jsfiddle.net/hwarem1v/1/
1. Takes 1s to generate 100k rows with 50 columns. This can be offloaded into a worker.
2. Click "Load Data"
3. Takes 10s to render it in the table. This locks the UI and cannot be offloaded into a worker.

I know asking for async rendering is no small thing. But it would be really amazing to make the table feel like it handles large data sets much more responsively.

In my case this is compounded by the fact that `nestedRows` have problems updating data, so I have resorted to re-instantiating the table after applying custom sorting and filtering to the data outside the table (since `nestedRows` doesn't properly support sorting and filtering). This works quite well for smaller data sets, but the UI hangs whenever the user sorts or filters because the table has to be re-instantiated and hangs on large data sets.

**Comment by AMBudnik** [comment]
That would be great. Thanks for sharing Aaron.

**Comment by BertrandMarlair** [comment]
I made a little piece of code that uses a web worker. It calculates two values and tests if the result is pair or not. In this code if the purpose is only to make cells green after a series of calculations by maximizing performance by doing everything asynchronously

**Demo**

[codesandbox](https://codesandbox.io/s/react-handsontable-web-worker-yrl9z)

**Comment by AMBudnik** [comment]
Thank you again for sharing this idea!

I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
