### ISSUE TITLE
querstion about dropdown 

### ISSUE THREAD

**Issue by zzzyting** [handsontable/handsontable#5818]
### Description
when I enter the contents in the cell are inconsistent with the sourcei of dropdown, the cell's background trun 'red'，but in cell  { type:autocompelete }, it can not trun ' red' by set strict true,
so, are there any good ways to slove it? thanks!

### Steps to reproduce
1,cell {
     type: 'dropdown',
      source: ['invoice+', 'cost-']
}
2,enter any contents   inconsistent with the source.
### Demo

![ee1](https://user-images.githubusercontent.com/25153242/53404732-3aeca680-39f1-11e9-9764-e3b4709a2beb.PNG)

![rwer2](https://user-images.githubusercontent.com/25153242/53404740-3e802d80-39f1-11e9-9197-8149d2b19927.PNG)

**Comment by AMBudnik** [comment]
Hey @zzzyting 

Do you have the `allowInvalid` set to `false` or `true`? Here, in the second table, you can spot the difference when you type an invalid value and click anywhere outside the table https://handsontable.com/docs/6.2.2/demo-autocomplete.html

**Comment by zzzyting** [comment]
Hi,@AMBudnik ,
Actually,  at cell {type: 'dropdown'} ,  I allow my users  type an invalid value. but I don't want this cell' backgroud-color  trun to 'red'

**Comment by AMBudnik** [comment]
If you do not want the validation to run you need to use the `strict: false` option, like in the first example on the page that I've sent you.
