### ISSUE TITLE
IE11 and Edge after close contextMenu by click outside check both instance of hot

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5822]
### Description
We need investigate why handsontable instance from `contextMenu` react to `mouseDown` event, even if it's destroyed.

This issue is related to this PR - https://github.com/handsontable/handsontable/pull/5813
 
### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: IE11 - Windows 7 and Egde - Windows 10

**Comment by AMBudnik** [comment]
As [support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

Following the steps from the [PRs steps](https://github.com/handsontable/handsontable/pull/5813)

>to reproduce take this steps - click in the cell, next open contextMenu and click besides table or inside table.

On my Edge 
<img width="153" alt="edge_ver" src="https://user-images.githubusercontent.com/10757813/85021738-90167380-b172-11ea-8948-b3f65eeff7d0.png">

on Windows 10 and Handsontable 8.0.0-beta2-rev15 it works as expected for the `mousedown` event provided by the `afterOnCellMouseDown` Handsontable hook.

![good](https://user-images.githubusercontent.com/10757813/85022566-c6082780-b173-11ea-88d1-d1e2e0e2403e.gif)


It correctly refers to the main table.
