### ISSUE TITLE
The autocomplete element doesn't display when the table have only one row

### ISSUE THREAD

**Issue by PkBantee** [handsontable/handsontable#5823]
Table generate one row cause data has one row. The table has one field/column that is autocomplete field so when the field was edited, it's not show any drop down/selector. The field should show the dropdown. If CC have any solutions or resolve version, please tell me. Thanks for your responding.

Browser Name and version: Chrome 72
Operating System: windows

**Comment by AMBudnik** [comment]
Hey @PkBantee 

can you share a demo? Here https://jsfiddle.net/sf3hwgq4/ it looks and works as expected.

**Comment by AMBudnik** [comment]
I guess that I can close the issue. There are more than 3 weeks without a reply.
