### ISSUE TITLE
Add carriage copy function

### ISSUE THREAD

**Issue by rudacs** [handsontable/handsontable#5826]
### Description
When you try to copy the contents of the cells. In some programs like SAP you need \r.

Maybe put as a parameter that is to add or not \r at the time of copying.

This greatly affects my clients. They have to copy and put for example in Excel to then copy and paste into the systems.

**Comment by AMBudnik** [comment]
Related topic https://github.com/handsontable/handsontable/issues/5647

**Comment by wojciechczerniak** [comment]
Can you provide more details @rudacs for this use case? When an where exactly do you need `\r`? Does the values have multiple lines? Can you provide sample data?

**Comment by rudacs** [comment]
In case it is the copyPaste plugin. In my cases, I need to copy it \r\n at the end of each line. Instead of \n. On systems that will be pasted it does not work without \r. So I suggested a parameter to set the end of line. It would also be a suggestion to configure \t

**Comment by rudacs** [comment]
In the case is the inverse of the related item. This is when copying from the component to other applications.

**Comment by AMBudnik** [comment]
Hey @rudacs I'm happy to announce that this issue has been solved with https://github.com/handsontable/handsontable/issues/5684 in v `7.1.0`.
