### ISSUE TITLE
how can i use renderer with vue render

### ISSUE THREAD

**Issue by CNJackyYe** [handsontable/handsontable#5828]
### Description
this renderer demo used document operation, but i want to use vue components in the hottable, how can i do that

**Comment by wojciechczerniak** [comment]
You have to add custom renderer that will create component instance and mount it inside the TD.

We have an issue for that feature: https://github.com/handsontable/vue-handsontable-official/issues/101 and a PR https://github.com/handsontable/vue-handsontable-official/pull/105 if you want to try it. Let us know how it works for you.
