### ISSUE TITLE
Sort indicator not visible when column header is truncated

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5830]
### Description

If the column size is small enough to truncate the header text, the sort indicator is not visible. 

### Steps to reproduce

1. Open demo: https://jsfiddle.net/a5ox91e4/
2. Sort on a column
3. Notice the sort indicator is not visible at all

Ideally we need "proper" header text truncation, like
```
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
```
On an inner text element:
![image](https://user-images.githubusercontent.com/2973900/53672330-0de9ff00-3c50-11e9-9b22-4321bfa38d78.png)
Or something like that.

### Demo

https://jsfiddle.net/a5ox91e4/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey @aaronbeall 

The issue has been raised some time ago by our developer at https://github.com/handsontable/handsontable/issues/5443 It is a part of an epic issue https://github.com/handsontable/handsontable/issues/5442

**Comment by aaronbeall** [comment]
@AMBudnik I actually found that issue while searching, and this is issue is different as it does *not* relate to using the dropdown menu plugin or having multi-line headers. It has to do with header truncation due to fixed width header and long header text. Hopefully that is covered by #5442 epic. :)

**Comment by AMBudnik** [comment]
I wasn't convinced either if that's the same case but got a message from our CTO who checked the issue and told me that this fix should close both issues.
