### ISSUE TITLE
Scroll Performance degrades when hiddenColumns are in the viewport

### ISSUE THREAD

**Issue by tkane2000** [handsontable/handsontable#5839]
### Description
In large tables, with large groups of hidden columns, vertical and horizontal scroll performance is very choppy/janky.  For instance, if you have 100 columns and 10 - 60 are hidden, as you scroll to the right hot will stutter as it the hidden columns cross into the viewport and it will stutter continuously as you scroll vertically.

Note: the hiddenColumns plugin hides columns by setting their widget to 0, so each hidden column still has to be rendered by hot.  This is the the cause of the problem because if we set all columns to visible, performance improves, with the exception of being on a 4k monitor in which you can display a large number of columns at the same time at a high resolution.

I've played around with setting viewportColumnRenderingOffset and viewportRowRenderingOffset, but that hasn't solved the problem. Setting viewportColumnRenderingOffset to the full length of columns improves horiz scroll, but makes vertical scrolling a bit worse.  Setting viewportColumnRenderingOffset to auto and not setting viewportColumnRenderingOffset seems to be best, but as I said, not enough to fix the issue.

When scrolling vertically, we're seeing the following warning repeatedly in the console:
"[Violation] Forced reflow while executing JavaScript took 644ms"
It looks like this was brought up in Improve forced reflow and layout #3370, but was not resolved.

Major clients are complaining so we're hoping to fix it within the next 2 weeks.  With that in mind, if you have any suggestions for hacks please share!  For instance, is there a way to NOT render hidden columns while you're scrolling?

We're also interested in a longterm fix.

### Steps to reproduce
1. Go to https://jsfiddle.net/tkane2000/s1qc8gu3/17/
2. Scroll by dragging scroll bar horizontally and notice jankiness as the hidden columns next to column 13 come into view.
3. Scroll  horizontally so that column 13 in is view.  Scroll by dragging scroll bar vertically and notice jank.

Note: the problem is MUCH worse on our site probably because of custom rendering and the fact that the viewport can be bigger displaying more columns and rows than it can on jsfiddle.  I've tried disabling our custom renderers, etc.  We see a bit of improvement, but the problem still exists.  Unhiding all columns helps significantly.

### Demo

https://jsfiddle.net/tkane2000/s1qc8gu3/17/

### Your environment
* Handsontable version: "handsontable-pro": "3.0.0"
* Browser Name and version: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
* Operating System: Mac OS, Mojave

**Comment by AMBudnik** [comment]
Hey @tkane2000 

Can I ask you to copy/paste your investigation results to this post https://github.com/handsontable/handsontable/issues/4381 where we already started a conversation about the impact of hiddenColumn plugin on the performance?

Additionally, here https://github.com/handsontable/handsontable/issues/5769 is a topic that I recommend you to follow.
