### ISSUE TITLE
'Undefined' Error in IE11

### ISSUE THREAD

**Issue by Sundarcj** [handsontable/handsontable#5840]
Handsontable throws invalid argument in headerObj.colspan.. anyone have idea about it?
<img width="374" alt="handsontableissue" src="https://user-images.githubusercontent.com/29049117/53950138-90ac0780-40f1-11e9-88fd-0354177a90be.PNG">

**Comment by AMBudnik** [comment]
Hey @Sundarcj 

can you share a demo where this issue can be replicable? I couldn't replicate it with our demos.

**Comment by Sundarcj** [comment]
Hi @AMBudnik  am unable to reproduce in jsfiddle , this issue occurs in my build, am using 2.0 pro licensed version, do u have anyidea ?? when will headerobj.colspan become undefined?

**Comment by AMBudnik** [comment]
Have you tried to update to a newer version? If you can't load 7.0.0 you should try 6.2.2

**Comment by AMBudnik** [comment]
Please update to 6.2.2+ ale let me know if it works for you.
