### ISSUE TITLE
Inconsistent options' behaviour in contextmenu for comments

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#5841]
### Description
- [ ] `Add comment` should be hidden if more than one cell is selected
- [ ] `Read-only comment` is disabled if more than one cell is selected and highlighted cell doesn't contain comment
- [ ] `Delete comment` is active even if selected cells don't have comments
- [ ] `Delete comment` doesn't work if selection starts from bottom-right to top-left

### Demo
https://handsontable.com/docs/7.0.0/demo-comments_.html

### Your environment
* Handsontable version: any

**Comment by AMBudnik** [comment]
Another case (moved from https://github.com/handsontable/handsontable/issues/6824)


We should disable the `Delete comment` option in the context menu when the menu is opened for a cell that **does not have** a comment attached.

![Zrzut ekranu 2020-04-21 o 12 20 34](https://user-images.githubusercontent.com/10757813/79854926-87036300-83ca-11ea-90fd-267f787aa1dd.png)

**Result**
* the `Delete comment` option is enabled.
* the `afterSetCellMeta` hook is called 

https://jsfiddle.net/AMBudnik/31asth5g/
