### ISSUE TITLE
Test specs don't clean up DOM tree after their completion

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#5842]
### Description
A certain test specs leave unnecessary elements in a DOM tree.
- [ ] `Core_init  should create table even if is launched inside custom element`
 leaves `<div id="testContainer"></div>`
- [ ] `Core_view should not shrink table when width and height is not specified for container`
leaves `<div style="width: 50px;"></div>`
- [ ] `Handsontable.Dom isVisible should return false for table with parent 'display: none'`
leaves `<div style="display: none"></div>`

Furthermore:
- [ ] We should add test spec to verify if test specs left unnecessary elements in DOM tree

### Steps to reproduce

1. Run `npm run test:e2e`
2. Initialise local server eg.: `http-server`
3. Go to `localhost:8080/test/E2ERunner.html`
4. Open DevTools and check a list of `document.body`'s children list

### Your environment
* Handsontable version: any

**Comment by jansiegel** [comment]
Should be fixed with #6077.
