### ISSUE TITLE
destroy() doesn't remove elements from DOM tree

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#5843]
### Description
After `destroy()`, Handsontable should cleanup a DOM tree from unnecessary elements.

- [ ] FiltersUI leaves `.htFiltersConditionsMenu`- https://jsfiddle.net/9Lotpe1k/
- [ ] DateEditor leaves`.htDatepickerHolder` - https://jsfiddle.net/2qasm4zc/
- [ ] ContextMenu leaves `.htContextMenu` - https://jsfiddle.net/8ez1htjk/
- [ ] DropdownMenu leaves `.htDropdownMenu` - https://jsfiddle.net/0L7ug48z/
- [ ] Comments leaves `.htCommentsContainer` - https://jsfiddle.net/xwne02q1/

### Steps to reproduce
1. Go to examples from above list
2. Open console in DevTools
3. Click `Run test` button instructions in above examples

### Your environment
* Handsontable version: any

**Comment by jansiegel** [comment]
Should be fixed with #6077.
