### ISSUE TITLE
[1.14.0+] Missing border left/top when use hiddenColumns/hiddenRows.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5847]
### Description
And rowHeaders/colHeaders isn't switched on.
In TH with class `.firstVisibleColumn` (added from `hiddenColumns` plugin) adds style `border-left-width: 0;`.

### Demo

https://jsfiddle.net/bzua1pyt/
https://jsfiddle.net/uhr5an76/

### Your environment
* Handsontable version: At least 1.14.0 - http://jsfiddle.net/w3ycztv2/
* Browser Name and version: Chrome  72.0.3626.119, Firefox 65.0.1  and Safari 12.0.1
* Operating System: OS Sierra 10.12.6

**Comment by wojciechczerniak** [comment]
Looks like a duplicate of #5817 but has more info about columns, 1.14+ version, labels. 

We should merge those issues @pnowak @AMBudnik ?

**Comment by AMBudnik** [comment]
I've updated https://github.com/handsontable/handsontable/issues/5817 (issue's still there for `8.0.0-rc1`). 
> de-synchronized by 1px

yup. I would call it the same issue @wojciechczerniak

**Comment by wojciechczerniak** [comment]
Cool. Closing as duplicate of #5817
