### ISSUE TITLE
Numeric cell type fails to validate -.n

### ISSUE THREAD

**Issue by moodyroto** [handsontable/handsontable#5848]
### Description
When omitting the zero on negative decimals, numeric cell types fail validation (eg, -.1). This is also true for positive numbers when including a plus sign (+.1). Issue only appears on manual entry, or pasting values.

### Steps to reproduce

1. Using any HOT with a numeric column, or specifically this fiddle https://jsfiddle.net/5avynusk/. 
2. Navigate to any numeric cell (ie, any cell in the Level column)
3. Manually change a value to -.1
4. Witness the cell turn red, and display as invalid

### Demo
https://jsfiddle.net/5avynusk/

### Your environment
* Handsontable version: v7.0.0
* Browser Name and version: Reproduced in Chrome 72, Firefox 64, Microsoft Edge 42, IE 11
* Operating System: Windows 10

![image](https://user-images.githubusercontent.com/4803724/53975273-77e02980-40d2-11e9-8676-3f7c5073b352.png)

**Comment by moodyroto** [comment]
I haven't tested to confirm, but issue is likely this line, https://github.com/handsontable/handsontable/blob/master/src/helpers/number.js#L14

**Comment by AMBudnik** [comment]
You're right. If the value of `.9` is converted to `0.9` then `-.9` should become `-0.9`.

Thank you for sharing @moodyroto

**Comment by pnowak** [comment]
The bug still replicate, work the same - https://codesandbox.io/s/vibrant-dan-ocigf

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 https://jsfiddle.net/AMBudnik/th0gk5ez/ works the same
