### ISSUE TITLE
upgrading to v7.0.0 prod config throwing tofixed()

### ISSUE THREAD

**Issue by nyc-cr2** [handsontable/handsontable#5850]
### Description

It seems after upgrading to v7.0.0 we're getting the errors below similar to issue #5790 relying on numbro@2.1.2.  Running as prod config

Any suggestions, should we rollback our upgrade or is there a fix coming?

`-- handsontable@7.0.0
  `-- numbro@2.1.2

### Steps to reproduce

[1.]Similar to (https://github.com/handsontable/handsontable/issues/5790)
![error1](https://user-images.githubusercontent.com/16924038/54073425-ee0c9980-4254-11e9-803a-f6e73ce3b03d.jpg)
![error2](https://user-images.githubusercontent.com/16924038/54073426-f1078a00-4254-11e9-8f2f-49aded15d304.jpg)

)

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: chrome
* Operating System: win 10

**Comment by AMBudnik** [comment]
Thank you for sharing the issue. You're right there's an inconvenient incompatibility between numbro and the webpack's plugin.
Our Developer is already assigned to the issue and doing the best he can to solve it.

**Comment by jansiegel** [comment]
It seems to be the same issue as #5790 indeed. I've posted some possible solutions there, could you check if they work for you, @nyc-cr2?

**Comment by wojciechczerniak** [comment]
Already released.
