### ISSUE TITLE
HTML/renderer shows in "filter by value" dropdown

### ISSUE THREAD

**Issue by danives3d** [handsontable/handsontable#5853]
### Description
When using the 'HTML renderer' to show the data inside the table, and enabling the "filter_by_value" dropdown, the HTML markup shows in the dropdown.

### Steps to reproduce

1. Create a table with a column that uses the HTML renderer for the column
2. Enable filters
3. Enable the 'filter_by_value' in the dropdown menu

### Demo
https://jsfiddle.net/0nhradvg/2/

### Your environment
* Handsontable version: 6.2.1
* Browser Name and version: Chrome Version 70.0.3538.110
* Operating System: OSX

### Possible Solution

There is a call to `createLabel` in the JavaScript code, that generates the label for the filter. To fix this for my problem, I changed the function to the following:

```
function createLabel(text) {
  var label = document.createElement('label');
  label.className = 'htCheckboxRendererLabel';
  var div = document.createElement('div');
  div.innerHTML = text;
  label.appendChild(document.createTextNode(div.innerText));
  return label.cloneNode(true);
}
```

This strips out the HTML from the label. A better solution might be to update the `checkboxRenderer` method to determine if the column is using the HTML renderer and then strip the HTML in the createLabel function.

**Comment by AMBudnik** [comment]
Thank you again for sharing this idea!

I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
