### ISSUE TITLE
Nested rows cannot change parent position

### ISSUE THREAD

**Issue by minchopm** [handsontable/handsontable#5856]
### Description
Please provide a functionality to change parent positions.

**Comment by AMBudnik** [comment]
Hi @minchopm Could you help us to specify the feature request.

Which of those scenarios should we add?

### Scenario 1
Move the whole parent when we hold parent row
![case1](https://user-images.githubusercontent.com/10757813/84736097-59d7c900-afa5-11ea-913e-e54f79870085.gif)

**Expected result**
![Zrzut ekranu 2020-06-16 o 07 46 53](https://user-images.githubusercontent.com/10757813/84736187-91467580-afa5-11ea-808a-5b19d8e3602f.png)

### Scenario 2
Move the whole parent when we hold all children along with parent.
![case2](https://user-images.githubusercontent.com/10757813/84736383-fac68400-afa5-11ea-9c96-77142ab4ad10.gif)

**Expected Result**
![Zrzut ekranu 2020-06-16 o 07 51 26](https://user-images.githubusercontent.com/10757813/84736473-33fef400-afa6-11ea-91ac-c2c4c5343393.png)

**Comment by AMBudnik** [comment]
Thank you again for sharing this idea!

I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
