### ISSUE TITLE
CollapsibleColumns option to collapse all except last column

### ISSUE THREAD

**Issue by shaicoleman** [handsontable/handsontable#5858]
I would like to have an option to be able when using the CollapsibleColumns plugin, to collapse all except the last column. At the moment, it can only keep the first column.

This would would make the behaviour similar to the Auto-Outline feature in Excel, and would be useful when there's a total in the last column.
e.g. https://youtu.be/VzV8LWgetIo?t=261

**Comment by AMBudnik** [comment]
as a part of https://github.com/handsontable/handsontable/issues/5864

**Comment by allanbowe** [comment]
Our project also requires the ability to collapse all except the last column  - so, +1

**Comment by AMBudnik** [comment]
Thank you again for sharing this idea!

I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
