### ISSUE TITLE
Trim rows plugin doesn't cooperates properly with manualRowMove plugin

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#5860]
### Description
Trim rows plugin doesn't work properly when visual indexes of rows were changed.

### Steps to reproduce
Case 1:

1. Open: https://jsfiddle.net/2fvc15gu
2. Click on the button to trim row.
3. Take a look at rows order. At position `0, 0` we can see the row with `A9` inside.

Case 2:

1. Open: https://jsfiddle.net/2q8f3skm
2. Click on the button to trim row.
3. The first row becomes empty.

### Your environment
* Handsontable version: <= 1.8.0
* Browser Name and version: Google Chrome 65.0.3325.181
* Operating System: macOS Hight Sierra 10.13.3

**Comment by AMBudnik** [comment]
#### 7.1.1
![image](https://user-images.githubusercontent.com/10757813/65030605-1978eb00-d940-11e9-9ce0-33f1b06fb45c.png)

#### 8.0.0-rc1
![image](https://user-images.githubusercontent.com/10757813/65030668-36152300-d940-11e9-9523-c67efc323226.png)

**Result**
The `0` row is being trimmed and then we move the row with index `7` up to the top. So, as long as the `trimRows()` uses physical indexes the issue got solved. Should we add this information to the [docs](https://handsontable.com/docs/7.1.1/demo-trimming-rows.html)?

**Comment by wojciechczerniak** [comment]
> Note: Should we add this information to the docs - handsontable/docs#75?

Yes 👍   

Please add JSFiddle links.

**Comment by AMBudnik** [comment]
Fixed officially in 8.0.0-beta1 https://jsfiddle.net/g1Lmb05o/

**Comment by AMBudnik** [comment]
Case 1 solved in v 8.0.0 https://jsfiddle.net/j28pb3u9/
Case 2 solved in v 8.0.0 https://jsfiddle.net/g8cou5tq/
