### ISSUE TITLE
currentColClassName doesn't work properly with nestedHeaders

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5861]
### Description

reported at https://forum.handsontable.com/t/gl-55-nested-headers-with-currentheaderclassname-currentcolclassname-currentrowclassname/1044/5
`Moved from GL #55`

> current class isn't added to selected column if index is not equal coords.col of highest header

Same happens for `currentHeaderClassName`. The lowest level headers keep the dark-grey background color after they have been selected.

![gif](https://user-images.githubusercontent.com/10757813/52953186-0e98b080-3387-11e9-87c1-9c1b5f58375c.gif)

### Demo

http://jsfiddle.net/AMBudnik/15zxm63s/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
It doesn't seem to change in `7.3.0` http://jsfiddle.net/zab81tfx/ and the SVG changes http://jsfiddle.net/Lbews4mf/1/

**Comment by AMBudnik** [comment]
It doesn't work in `7.4.2` http://jsfiddle.net/9od8pg7x/ 
Works the same in `8.0.0-beta1`http://jsfiddle.net/c8fhgeyt/1/

**Comment by pnowak** [comment]
**Solved** in 8.0.0.-beta2-rev2 - https://jsfiddle.net/sLhk01ue/

<img width="557" alt="Zrzut ekranu 2020-05-8 o 13 59 42" src="https://user-images.githubusercontent.com/1555809/81403711-4dee2100-9134-11ea-8106-0aeaaefee011.png">

**Comment by AMBudnik** [comment]
Works well in v 8.0.0. Updated demo https://jsfiddle.net/ydgrvh16/
