### ISSUE TITLE
We get `Maximum call stack size exceeded` when enabling summaryCalculations and minSpareRows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5863]
### Description

We get `Maximum call stack size exceeded` when enabling summaryCalculations and minSpareRows

### Steps to reproduce

1. Run the demo

![image](https://user-images.githubusercontent.com/10757813/52628601-4f408780-2eb8-11e9-8d8c-7e75f7a32529.png)

### Demo

http://jsfiddle.net/handsoncode/y1rc27dz/1/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Windows 10

`Moved from GL #172`

**Comment by aninde** [comment]
Still not fixed with 7.4.0 @AMBudnik demo https://jsfiddle.net/0rtx5pg9/ from #6695

**Comment by AMBudnik** [comment]
After updating @aninde demo to `8.0.0-beta1` it seems to be fixed https://jsfiddle.net/mcd63qth/ 
- we get the expected result
- there is no error

It solves the main issue (1 post) http://jsfiddle.net/8u5pzdbg/

It also solves the issue with the `numeric` cell type http://jsfiddle.net/1v3nb9a6/

> It happens the same when we settype: numeric
> Demo: http://jsfiddle.net/AMBudnik/e6qmdfov/
> 
> Uncomment type to reproduce. (mentioned in GL #124)

**Comment by AMBudnik** [comment]
The issue is solved with v 8.0.0

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage anyone to test the new version and leave some feedback. 

@jeffrey008 please let me know if it helps you as well.
