### ISSUE TITLE
Make collapse/expand plugin in nested header configurable

### ISSUE THREAD

**Issue by williamboman** [handsontable/handsontable#5864]
Hi! I'd rather use the HiddenRows, rather than the hard-coded TrimRows plugin, when using the nested headers feature. The HiddenRows and TrimRows plugins seem to have quite similar interfaces.

**Comment by swistach** [comment]
Hi @williamboman,
we removed hard-coded dependencies between our plugins in v8. You can read more about changes in our release notes: https://github.com/handsontable/handsontable/releases/tag/8.0.0 and in our migration guide: https://handsontable.com/docs/8.2.0/tutorial-migration-guide.html

I'm closing this issue, but feel free to ask us here if you don't find answers in the above links.
