### ISSUE TITLE
Undo hook informing about stack changes

### ISSUE THREAD

**Issue by jacekbogdanski** [handsontable/handsontable#5866]
### Description

It would be great to have a dedicated hook informing about `undoRedo` plugin stack change. Currently, it seems to be no easy way to get that information except using `Proxy` object (or similar method changing the internals of the undo plugin) for [`doneActions and undoneActions`](https://github.com/handsontable/handsontable/blob/master/src/plugins/undoRedo/undoRedo.js#L27-L28) arrays.

Simplified use case:

1. A user modifies table cell.
1. Undo plugin adds new action into `undoRedo` stack.
 **Expected:** `afterUndoStackChange` hook is fired.
1. A user performs undo action by keyboard shortcut or context menu.
**Expected:** `afterRedoStackChange` hook is fired.

It also probably makes sense to pass `undoRedo` action into proposed hooks.

AFAIK [`undoRedo`](https://github.com/handsontable/handsontable/blob/master/src/plugins/undoRedo/undoRedo.js) plugin modifies both `doneActions` and `undoneActions` stacks on undo or redo action. Note that my feature request doesn't follow plugin implementation in that case, skipping counterpart hook execution, so it's easy to distinguish both operations.

**Comment by AMBudnik** [comment]
Thank you for sharing the proposition. I am wondering if it would be better the create a separate hook or push the changes to the [`beforeUndo` hook](https://jsfiddle.net/drnpco1h/).

**Comment by wojciechczerniak** [comment]
Note: `before*` hooks should give the possibility to skip adding some actions to undo stack. Check #6358 for details.

**Comment by AMBudnik** [comment]
I'm adding the need for this new hook to the scope of this issue https://github.com/handsontable/handsontable/issues/7508
