### ISSUE TITLE
[2.0.0+] "disableVisualSelection: current" is ignored work

### ISSUE THREAD

**Issue by RichTeaTime** [handsontable/handsontable#5869]
### Description
Docs describe "disableVisualSelection" possible values:
> • true - Disables any type of visual selection (current and area selection),
> •	false - Enables any type of visual selection. This is default value.
> •	'current' - Disables the selection of a currently selected cell, the area selection is still present.
> •	'area' - Disables the area selection, the currently selected cell selection is still present.
> •	'header' - Disables the headers selection, the currently selected cell selection is still present.

However, calls to ```this.highlight.isEnabledFor(_highlight.CELL_TYPE)``` fail to match 'current' which is clearly what's intended.

### Steps to reproduce
1. Set disableVisualSelection: 'current' or ['current'...]
2. Run and select a cell
EXPECTED: The current cell is not highlighted, as requested.
ACTUAL: The current cell is still highlighted, the disableVisualSelection value is ignored.

3. Set disableVisualSelection: 'cell' or ['cell']
4. Run and select a cell
EXPECTED: The current cell is highlighted, the disableVisualSelection value is ignored.
ACTUAL: The current cell is not highlighted.

### Demo
https://jsfiddle.net/v5wxdfzq/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 72.0.3626.109
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
It also does not work in 8.0.0-beta1 https://jsfiddle.net/g8wktpz5/

**Comment by AMBudnik** [comment]
It still does not work in v8.0.0 https://jsfiddle.net/AMBudnik/7oxb9gca/
The condition ([docs](https://handsontable.com/docs/8.0.0/Options.html#disableVisualSelection))
> Disables the selection of a currently selected cell, the area selection is still present.
is not met 

![issue](https://user-images.githubusercontent.com/10757813/92712106-8196bd00-f359-11ea-9be1-3af8b7474bb6.gif)

**Comment by AMBudnik** [comment]
I've checked all the options available for the '`disableVisualSelection`' option, and still only '`current`' does not work as described. It should allow only area selection but it allows to select a single cell as well.

**Comment by wszymanski** [comment]
> Not sure how to submit a pull request on this, but changing `highlight.isEnabledFor` from:
> 
> ```
>   var type = highlightType === 'current' ? CELL_TYPE : highlightType;
> ```
> 
> to
> 
> ```
>   var type = highlightType === CELL_TYPE ? 'current' : highlightType;
> ```
> 
> would probably do it.

Thanks, that's proper approach 🙂 There is information [how to contribute](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md).

**Comment by aninde** [comment]
I am very pleased to see that this bug has been fixed in the upcoming `v8.3.2`.

In the screenshot from the demo, cell A1  is marked with disabled visual selection for the current selection.
<img width="150" alt="Screenshot 2021-03-10 at 13 34 40" src="https://user-images.githubusercontent.com/30186818/110630228-66d8c000-81a5-11eb-9ac0-561e9411699b.png">

### Demo
https://jsfiddle.net/mgd6f5jq/ `v8.3.2` (fixed)

Tested on 
macOS 11.2.2 (20D80) - Chrome  `88.0.4324.192`, Safari  `14.0.3 (16610.4.3.1.4)`, Firefox `86.0` , Edge `89.0.774.48`, Opera `74.0.3911.203` 
Windows 10 - Chrome  `88.0.4324.192` , Edge `89.0.774.48`, IE `11`, Firefox `86.0`

**Comment by AMBudnik** [comment]
I'm happy to see this regression fixed!
@RichTeaTime, I'd be more than grateful for your feedback about Handsontable v8.3.2, where this issue is solved.
