### ISSUE TITLE
Value-Text paring in Autocomplete

### ISSUE THREAD

**Issue by nikunj24u** [handsontable/handsontable#587]
Hello,
I want to add Value-Text paring in Autocomplete.

Value-Text means,
Value | Text
1	 | Ted
2	 | John
3	 | Steve
4	 |  Ben

Value - will be stored in database.
Text - will be display in autocomplete.

I need to store selected Text's Value instead of Text in database.

Can you please tell me how can i set Value-Text paring in Autocomplete? 
If possible give sample jsfiddle too.

Thanking you,
Nikunj Patel

Update: I found similar open issue https://github.com/warpech/jquery-handsontable/issues/584, Sorry for the duplication.

**Comment by tdjun** [comment]
I made new cell type which was customized autocomplete.
https://github.com/tdjun/Handsontable-autocomplete2

**Comment by rajanand02** [comment]
@warpech an example would be really helpful for `type: 'handsontable'`

**Comment by AMBudnik** [comment]
Hi @rajanand02 
Here's an example for the `handsontable` cell type: https://docs.handsontable.com/pro/1.5.1/demo-handsontable.html
and the JSFiddle: http://jsfiddle.net/cubmjrs0/

**Comment by paulhodel** [comment]
http://bossanova.uk/jexcel/working-with-dropdowns

**Comment by pindamonhangaba** [comment]
I'm using this custom renderer and editor, with a basic string-lookup to simulate key-value dropdown:
https://gist.github.com/pindamonhangaba/00f1d865d86d57ab929d2ad3c9dd54c7

Very simple, but comes with the cost of a whole iteration on your source values.

**Comment by evenmind** [comment]
@pindamonhangaba do you have an example or a jsfiddle of your solution pls?

**Comment by paulhodel** [comment]
Using jExcel you can do that. Example: http://jsfiddle.net/orz8frko/3/

**Comment by AMBudnik** [comment]
Hi @zk118 @pindamonhangaba @rajanand02 @tdjun @nikunj24u @kritochin @setthase @dansabirov 

We just launched Handsontable v16.1.0, where you can set up your key-value dropdown/autocomplete cell.

Here is the corresponding pull request https://github.com/handsontable/handsontable/pull/11773 that also adds two new methods: valueGetter and valueSetter.

In this guide, you can test it out https://handsontable.com/docs/react-data-grid/autocomplete-cell-type/#array-of-objects, and here is the full list of changes https://handsontable.com/docs/react-data-grid/changelog/#_16-1-0 - we also added LTS support, Pagination, and a Loading screen.

Hope you'll like it.
