### ISSUE TITLE
Hiding columns affect selection of hidden columns

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5871]
@AMBudnik commented on [Tue Feb 12 2019](https://github.com/handsontable/handsontable/issues/5785)

### Description

Hiding columns affect selection of hidden columns.

![gif](https://user-images.githubusercontent.com/10757813/52627503-d5a79a00-2eb5-11e9-898b-28b65ec21125.gif)

### Steps to reproduce

1. Select a cell in column `A`
2.  Move right with the arrow

### Demo

http://jsfiddle.net/handsoncode/d3kx2fs0/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Windows 10

`moved from GL #121`

**Comment by wojciechczerniak** [comment]
Not fixed in 7.3.0: https://jsfiddle.net/t7uh6p2a/

Should be solved in #6178

**Comment by AMBudnik** [comment]
7.4.2. http://jsfiddle.net/3dm1jsfq/ (broken)

8.0.0-beta1 http://jsfiddle.net/3dm1jsfq/1/ (broken)

8.0.0-beta2-rev2 http://jsfiddle.net/3dm1jsfq/2/ (**solved**)

![](https://user-images.githubusercontent.com/10757813/81390950-9994d080-911c-11ea-973a-77c4430882c0.gif)

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 http://jsfiddle.net/6qmctxfo/. Issue closed as solved.
