### ISSUE TITLE
AVERAGE doesn't allow to define numbers as strings

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5872]
### Description

AVERAGE doesn't allow to define numbers as strings

### Steps to reproduce

1. Just check the results for Average, Sum, and Min
2. Only the Average value has an error.

### Demo

http://jsfiddle.net/iboylmz/mg067fd8/3/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Windows 10

`Moved from GL #139`

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
This example with pre-v9 version does not change https://jsfiddle.net/handsoncode/tm3rbj1p/

**Comment by wojciechczerniak** [comment]
> This example with pre-v9 version does not change https://jsfiddle.net/handsoncode/tm3rbj1p/

The results are correct? You're calculating empty cells, you can't divide 0 by 0. Did you meant to use `C1:C5` ranges?

**Comment by AMBudnik** [comment]
My bad! @wojciechczerniak you're right. There was a typo where the AVERAGE refers to the A column, while it should refer to the C column.

Updated example to pre-v9 https://jsfiddle.net/handsoncode/417toes9/ works well

![image](https://user-images.githubusercontent.com/10757813/119145468-f45c4a00-ba49-11eb-94ec-9de13ceea005.png)

**Comment by AMBudnik** [comment]
Everything also works well in the official v9 (released yesterday) even when we update the values https://jsfiddle.net/3exgnq0y/1/

For everyone interested, here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
