### ISSUE TITLE
Hiding rows and fixing them causes rows misalignment

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5873]
### Description

Hiding rows and fixing them causes rows misalignment

![bug](https://user-images.githubusercontent.com/10757813/52718185-2ba63b80-2fa3-11e9-8af3-20c7014c8c85.png)

### Steps to reproduce

1. Just check the fiddle

### Demo

https://jsfiddle.net/handsoncode/j3yx6wxd/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Windows 10

`Moved from GL #144`

**Comment by wojciechczerniak** [comment]
Fixed JSFiddle: https://jsfiddle.net/tum7pvqe/

But it doesn't matter if rows are hidden or not: https://jsfiddle.net/v6j1htar/

IMO duplicate of #4454. What do you thing @AMBudnik ?

**Comment by AMBudnik** [comment]
Yes, it's the same issue. I'm closing this one.
