### ISSUE TITLE
hiddenRows doesn't work properly with autoWrapRow/autoWrapCol

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5877]
### Description

> Steps to reproduce: 
> 1) Go to the demo
> 2) Select A1
> 3) Press → or  ↓ four times
> 
> After the last visible cell in row, selection should be moved to the first visible cell in next row.
> Problems occurs only when the last col/row is hidden.

### Demo

http://jsfiddle.net/AMBudnik/d9pefh1m/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Windows 10

`Moved from GL #122`

**Comment by AMBudnik** [comment]
Also reproducible in v `7.0.0` http://jsfiddle.net/j9muzqtc/

**Comment by AMBudnik** [comment]
It still does not move the selection in `8.0.0-beta1` http://jsfiddle.net/rvwdc8se/

**Comment by AMBudnik** [comment]
Still broken in 8.0.0.-beta2-rev2 http://jsfiddle.net/9ea30bux/

HiddenColumns only work well http://jsfiddle.net/9ea30bux/1/ - this has been fixed in 8.0.0.-beta2-rev2 here #5704 but now the

**Comment by AMBudnik** [comment]
**Solved** in 8.0.0-beta2-rev13 http://jsfiddle.net/AMBudnik/fgz8dxLw/

**Comment by aninde** [comment]
Updated demo with v8.0.0 http://jsfiddle.net/aninde/gk5wu6oe/. Still working well. Issue closed as solved.

**Comment by aninde** [comment]
This bug can be reproduced without set autoWrapRow.autoWrap col, so I'm changing the title.
Updated demo - v6.2.2 http://jsfiddle.net/AMBudnik/d9pefh1m/.
