### ISSUE TITLE
npm task for unit tests throws errors on Windows.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5878]
### Description

> Handsontable tests are not working on Window' machines. There are some issues related to eslint rules. Also, the unit test task fails - there is a problem with getting environment variable on Windows.

`Moved from GL #169`

**Comment by AMBudnik** [comment]
Please check if they are still an issue in this repository.

**Comment by swistach** [comment]
Bug still exists.

https://github.com/handsontable/handsontable/blob/master/package.json#L28 
Definition and use of the env variable in our tasks chain don't work on Windows.

`npm run test:e2e` called separately, works ok.
