### ISSUE TITLE
onBeforePaste event

### ISSUE THREAD

**Issue by chronossc** [handsontable/handsontable#588]
Hello!

Sometimes when we paste from excel and have many lines (ex, 3000 or more) browser be busy, locked (and I have a core I7 with 16G RAM). I was hopping that we have a onBeforePaste to know that something will be pasted and show something to user saying to "Wait a bit, get a cooffe." :)

**Comment by einarj** [comment]
+1 

We get huge pastes where each row requires quite a bit of manipulation and in some cases AJAX calls to the server. It would be lovely to be able to start a spinner before all that work takes place.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by ziaulrehmandevsinc** [comment]
@bpostlethwaite  i was hoping you would have submitted pull request of this event, but found nothing. If you can point us to something useful in this regard that would be helpful. Any workaround or any link to some fork who might have this implementation

**Comment by ziaulrehmandevsinc** [comment]
We have added this hook, will try to make a full pull-request, until than, this might help some one.

In handsontable.full.js file, 
1- Register the hook( i selected the location where CopyPaste is registering some hooks which is after this line 'Handsontable.hooks.register('afterCopyLimit');') by adding this line
Handsontable.hooks.register('beforePaste');

2- Run this hook: I added this line in onPaste method of CopyPaste after all values have been initialized, before doing anything else we run this hook. To be brief just beofre this line 'instance.addHookOnce('afterChange', ...' in onPaste method. Line i added is:
Handsontable.hooks.run(instance, 'beforePaste', inputArray, areaStart, areaEnd);

We can pass up-to 6 arguments anything you need here, and recieve them in onPaste callback.


I know this all might look a little too expressive or something like that, but i am writing this to help anyone like me save a few hours.

**Comment by bpostlethwaite** [comment]
Sorry @ziaulrehmandevsinc! I never ended up revisiting that code.

**Comment by ziaulrehmandevsinc** [comment]
I have worked on this feature, and my branch is ready, but i am facing access denied error:

*****************
git flow feature publish issue-588
Username for 'https://github.com': ziaulrehmandevsinc
Password for 'https://ziaulrehmandevsinc@github.com': 
remote: Permission to handsontable/handsontable.git denied to ziaulrehmandevsinc.
fatal: unable to access 'https://github.com/handsontable/handsontable.git/': The requested URL returned error: 403
fatal: Couldn't find remote ref feature/issue-588
Fatal: Could not fetch branch 'feature/issue-588' from remote 'origin'.
*****************

@AMBudnik or anyone please guide how can i make this pull request.

**Comment by ziaulrehmandevsinc** [comment]
Here is pull-request with beforePaste event:
https://github.com/handsontable/handsontable/pull/3882

**Comment by ziaulrehmandevsinc** [comment]
There is another older(from  Oct 8, 2015) but better pull request, which is not approved yet, also has beforeCopy hook, for anyone who might be looking for these events in future, until they any of these are approved.:
https://github.com/handsontable/handsontable/pull/2876

**Comment by AMBudnik** [comment]
This callback will be added in v0.31.1 https://github.com/handsontable/handsontable/issues/4068

Thanks again for sharing :)

**Comment by ziaulrehmandevsinc** [comment]
Great.
