### ISSUE TITLE
[Filters] Tests doesn't destroy drop-down menu elements

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5880]
### Description

> Unnecessary elements aren't removed from DOM.
> 
> Steps to reproduce
> 1) Run tests by command: npm run test:e2e.dump -- --watch
> 2) Open part of Filters UI tests in a browser at localhost.
> 3) Open Chrome console.
> 4) Open Elements tab.
> 5) Elements like on below image are added to DOM.
> 

### Demo

http://localhost:9000/test/E2ERunner.html?spec=Filters%20UI%20Simple%20filtering%20(one%20column)
![screen_shot_2017-09-05_at_12 13 01](https://user-images.githubusercontent.com/10757813/52953495-ee1d2600-3387-11e9-92c3-a6767e9f6682.png)

`Moved from GL #190`

**Comment by AMBudnik** [comment]
related https://github.com/handsontable/handsontable/issues/5878

**Comment by swistach** [comment]
It will be resolved in #5843

**Comment by AMBudnik** [comment]
Thanks for checking @swistach
