### ISSUE TITLE
When we hide first column on IE we get double border for top left corner

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5881]
### Description

When we hide the first column on IE we get double border for a top left corner

### Steps to reproduce

1. Click the button

![gif](https://user-images.githubusercontent.com/10757813/52631194-684c3700-2ebe-11e9-9703-6b928cc9f18b.gif)

You'll see a double line for the top left corner.

### Demo

http://jsfiddle.net/hvysytt6/embedded/result,css,html,js

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: IE 11
* Operating System: Windows 10

`Moved from GL #156`

**Comment by aninde** [comment]
Similar behavior found with fixed or freezed columns.  Appears double border between column headers at index 0 and 1. Details in [#4601](https://github.com/handsontable/handsontable/issues/4601).

**Comment by aninde** [comment]
Another case of a double line on the headers border is related with enabling `fixedColumnsLeft`.
It isn't browser-related, because it appears in everyone. Occurs only when `fixedColumnsLeft` is enabled.

**Demo**
v. `7.2.2` https://jsfiddle.net/aninde/qaptny30

**Comment by AMBudnik** [comment]
Fixed in 8.0.0-beta1 http://jsfiddle.net/8yktr93e/

**Comment by AMBudnik** [comment]
Solved in 8.0.0-beta2-rev2 (tested on IE11 Win 10)

![](https://user-images.githubusercontent.com/10757813/81395125-6144c080-9123-11ea-9872-0c474efb7fbd.gif)

**Comment by AMBudnik** [comment]
As [support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them. 

However, as this issue has been already fixed it will be closed with the release of Handsontable 8.0.0.

The issue is not replicable on Edge.
![image](https://user-images.githubusercontent.com/10757813/85023373-edabbf80-b174-11ea-8e20-7501d32990ed.png)

**Comment by AMBudnik** [comment]
The main issue is not replicable on Edge http://jsfiddle.net/2rpzvnLt/ with v8.0.0
As @aninde wrote the case with duplicated border in a header relates to all the browser and it is replicable in v 8.0.0 https://jsfiddle.net/usm4w8Lp/ (tested on Chrome) so I have moved it here 

> Another case of a double line on the headers border is related with enabling `fixedColumnsLeft`.
> It isn't browser-related, because it appears in everyone.
> 
> **Demo**
> v. `7.2.2` https://jsfiddle.net/aninde/qaptny30
