### ISSUE TITLE
nestedHeaders duplicate a header name if more columns are added

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5882]
### Description

~~> After insert/delete column on left or inside the range of nested headers, the indexes of nestedHeaders are not changed.~~
When we add a new column to the already define set of nestedHeaders we get one duplicated header name.

### Steps to reproduce

1. Add a couple of columns to see how the nested headers change

![GIF](https://user-images.githubusercontent.com/10757813/71893048-d3dc6a00-314a-11ea-8417-edaed9312334.gif)

**Result**
You can see a double `W` header. Once you add more columns they are empty (correct).

### Demo

https://jsfiddle.net/AMBudnik/r7tqd6gb/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Windows 10
 
`Moved from GL #58`

**Comment by AMBudnik** [comment]
Works the same in `7.3.0`. The `W` is duplicated 

https://jsfiddle.net/t2u6o13g/
![Zrzut ekranu 2019-12-30 o 10 25 56](https://user-images.githubusercontent.com/10757813/71575887-df96b380-2aee-11ea-9a3e-91d183ad36a9.png)

and then there are no names for headers.

![Zrzut ekranu 2019-12-30 o 10 31 38](https://user-images.githubusercontent.com/10757813/71576065-9430d500-2aef-11ea-8755-6e94ddee68af.png)

Besides duplicated `W` it sounds OK, but I am not sure if it shouldn't change if we enable `colHeaders` https://jsfiddle.net/q4c91okw/. They are meant to add other letters of the alphabet as headers to the 0 level of `nestedHeaders`.


ps. works the same in `8.0.0-beta1` as well https://jsfiddle.net/q4c91okw/1/

**Comment by wojciechczerniak** [comment]
Isn't it working as expected? For standard headers, we have `bindRowsWithHeaders` plugin to achieve this kind of behavior for rows, but there is no plugin for headers.

Nested headers are declarative, you name each one to create the correct configuration. And they overwrite `colHeaders`, might not be the best idea to fall back to `colHeaders` functionality.

A feature request? Except for the duplicated `W`, we should fix it. Not a big issue though, if dev has to declare headers for the created column, she will overwrite it anyway.

**Comment by AMBudnik** [comment]
> A feature request? Except for the duplicated W, we should fix it. 

I do not have any issues with empty headers. It is reasonable to keep them empty and/or use `colHeaders` to fill them up. But `W` is surely a bug.

**Comment by wojciechczerniak** [comment]
@AMBudnik Then change the issue name and description to indicate the actual bug that has left (double `W`). It should be an easy and actionable task.

**Comment by AMBudnik** [comment]
**Solved** in 8.0.0-beta2-rev2 with #6716  
https://jsfiddle.net/peu08yzc/

![](https://user-images.githubusercontent.com/10757813/81395787-884fc200-9124-11ea-9008-2e8c16e62bf0.png)

**Comment by aninde** [comment]
Still works well with stable `v8` https://jsfiddle.net/aninde/foLwsnhd/.

**Comment by AMBudnik** [comment]
Thank you for confirming @aninde 
We can call it solved.
