### ISSUE TITLE
Filtering and sorting don't work together

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5890]
### Description
After filtering and then sorting `hot.toVisualRow(index)` method returns `null` not a visual index row. Without `sort` it returns the appropriate indices.

### Steps to reproduce

1. Go to https://jsfiddle.net/jua824m7/
2. Open `console` and see the result.

### Demo

https://jsfiddle.net/jua824m7/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
`inform Gr #24647`

**Comment by AMBudnik** [comment]
Issue fixed in `8.0.0.-rc1`.

Updated demo https://jsfiddle.net/handsoncode/t486es3L/
``` js
filtersPlugin.addCondition(0, 'gt', [1]); // we remove row index 0
columnSortingPlugin.sort({
  column: 0, sortOrder: 'desc' // we should get 3,2
});
console.log(hot.toVisualRow(0)); //has been filtered out - null
console.log(hot.toVisualRow(1)); //Should be 1
console.log(hot.toVisualRow(2)); //Should be  0
```
All data logged correctly.

**Comment by AMBudnik** [comment]
Works well in the official 8.0.0-beta1 https://jsfiddle.net/jwsch47t/

**Comment by AMBudnik** [comment]
This issue remains solved in v 8.0.0 https://jsfiddle.net/1fhLsa6x/

**Comment by david-ying-chan** [comment]
Hi, I'm having this issue in the project right now, is there a quick fix way for version 7.2.1? Thanks!

**Comment by AMBudnik** [comment]
@david-ying-chan this issue was related to a lack of a mechanism that is added to v8.0.0 (the index mapper). As you can see https://github.com/handsontable/handsontable/issues/5751 it would be very hard to implement those changes to 7.2.1 and you would end up with a possibility of serious incompatibilities. We highly recommend updating to 8.0.0

**Comment by david-ying-chan** [comment]
@AMBudnik thanks for your reply!
