### ISSUE TITLE
allowInvalid=false, strict=true doesn't work correctly with fixedColumnsLeft/fixedRowsTop

### ISSUE THREAD

**Issue by chearon** [handsontable/handsontable#5892]
### Description

If you have `{allowInvalid: false}` those cells should discard bad changes and the validator always says it's correct. So if you paste/dragbox a value onto one of those cells, it should not turn red, including inside fixed cells on the left/top with the `fixedColumnsLeft` and `fixedRowsTop` options. This bug only seems to happen when you have `{strict: true}` on the cell.

### Steps to reproduce

1. HOT instance with `{fixedColumnsLeft: 1}` and the first column is `{type: "autocomplete", allowInvalid: false, strict: true...}`
2. Paste or dragbox a value into that cell that's invalid
3. Cell stays red, even though it shouldn't. Without `{fixedColumnsLeft: 1}` the cell would stay plain

`.htInvalid` gets removed here on the master table but not the left clone, not sure if it should be using a different API call or something: https://github.com/handsontable/handsontable/blob/d0aac96b07497347eba7d8307c5b70e0081410f4/src/core.js#L970

### Demo

https://jsfiddle.net/8z5k1gxr/

(Use the drag box to drag a value from the right into the left column, or paste a bad value)

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Thank you for sharing the issue @chearon 

you're right. When I comment out the fixed columns the data is not validated. 

I do not see any previous version of Handsontable working differently.

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/n59j4ept/

**Comment by AMBudnik** [comment]
This issue is still replicable in v8.2.0 https://jsfiddle.net/amn3qp0k/

Without `fixedColumnsLeft` (Correct. Value does not change so it is not marked invalid)
![image](https://user-images.githubusercontent.com/10757813/105031179-3a31e300-5a55-11eb-943c-5e1ff6baf77f.png)


With `fixedColumnsLeft` (Incorrect)
![image](https://user-images.githubusercontent.com/10757813/105031144-29816d00-5a55-11eb-90aa-f24a5ac9b598.png)

**Comment by adrianszymanski89** [comment]
Hi @chearon 

I am happy to inform you that this issue was fixed in the newest release of Handsontable 14.5: https://github.com/handsontable/handsontable/pull/11035
