### ISSUE TITLE
Regression in 7.0.0: removing change in beforeChange breaks table

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5893]
### Description

As of upgrading to 7.0.0 we ran into an issue where canceling a date cell change in `beforeChange` breaks the table -- the cell renders stuck in edit and editing other cells doesn't work. At this point I've noticed this happens with `date` and `autocomplete` cells but not `text` cells. I haven't checked other cell types.

Example [demo](https://jsfiddle.net/vLgyojer/) where `beforeChange` removes the first change: 

![img](http://g.recordit.co/ZwN9CrggcK.gif)

### Steps to reproduce

1. Add a `beforeChange` hook which performs `changes.splice(0, 1)`
2. Create a `date` or `autocomplete` column.
3. Edit a cell in one of those columns and commit.

### Demo

https://jsfiddle.net/vLgyojer/

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Thank you for reporting and investigating the issue. You're right. The `7.0.0` is one to blame here. The editor does not close and selection gets broken.

**Comment by aaronbeall** [comment]
In the meantime I have a workaround to set the `nextValue` to the `prevValue` in `beforeChange`, then in `afterChange` I filter out all changes where `prevValue==nextValue`. I would still think this should be fixed, since the docs describe using `null` or `splice()` in `beforeChange` which currently doesn't work for some cell types.

**Comment by AMBudnik** [comment]
I'm glad to see another issue fixed. Thank you Aaron :)
the fix is available in v `7.1.1.`
