### ISSUE TITLE
Cells in cells function call for every cell in the table

### ISSUE THREAD

**Issue by m2a2x** [handsontable/handsontable#5895]
Hello,

I want to mention very huge problem for us with upgrading from very old version to the latest one:

**cells function**

> cells function
> Defines the cell properties for given row, col, prop coordinates. Any constructor or column option may be
> overwritten for a particular cell (row/column combination) using the cells property in the Handsontable constructor.

We were expecting from start it calls only visible cells. But it's not! It's calling all cells which present in datasource. 
And this is the only entry point where you could make cells readOnly. And it's calling our internal functions multiple times for the whole range not for only visible cells. You could find sample, it fails with 7.0 and it fails with 6.2 etc.

### Demo
https://jsfiddle.net/9ps1g7um/1/

### Your environment
* Handsontable version: 6.2, 7.0
* Browser Name and version: chrome
* Operating System: mac, windows

**Comment by AMBudnik** [comment]
Hey @m2a2x 

I believe that I have mentioned this issue before here https://github.com/handsontable/handsontable/issues/5204 but if I missing anything in issue no 5204 please add your comment.

**Comment by AMBudnik** [comment]
Hi @m2a2x 

The origin issue was just closed as solved https://github.com/handsontable/handsontable/issues/5895
This issue is no longer replicable in Handsontable 12.3.0
