### ISSUE TITLE
getCell topmost doesn’t work for fixedRowsBottom = 1

### ISSUE THREAD

**Issue by m2a2x** [handsontable/handsontable#5896]
> getCell(row, column, topmost)
> topmost - If set to true, it returns the TD element from the topmost overlay. For example,
> if the wanted cell is in the range of fixed rows, it will return a TD element from the top overlay.

But it doesn't work if:
fixedRowsBottom = 1

It returns bottom td, not top one.
Could be checked here:
https://jsfiddle.net/h4d1La3m/

### Your environment
* Handsontable version: 6.2+
* Browser Name and version: chrome
* Operating System: mac/windows

**Comment by wojciechczerniak** [comment]
Only when we want to get first fixed bottom row. Works for the second one: https://jsfiddle.net/rL23mh1j/

We're missing `>=` in this line?

https://github.com/handsontable/handsontable/blob/d0aac96b07497347eba7d8307c5b70e0081410f4/src/3rdparty/walkontable/src/core.js#L122

**Comment by AMBudnik** [comment]
inform [forum](https://forum.handsontable.com/t/gh-5896-getcell-topmost-doesnt-work-for-fixedrowsbottom-1/3068/2)

**Comment by AMBudnik** [comment]
Released in v 7.1.0 :) Please update and share your feedback.
