### ISSUE TITLE
How can I save the whole table to database? 

### ISSUE THREAD

**Issue by palespring** [handsontable/handsontable#5897]
### Description

Hi, the situation is like this,

there are two buttons, one named 'save', the other named 'load'.

When I finished designing the table, I would click the 'save' button, and the table will be saved to databse, not only the data, but also table styles, such as background color, merged cells, etc.

When I need to modify it again, I press the ‘load’ button and the table will be loaded(from database,not the localStorage or persistentState). I can continue to change it on the basis of the before.

I don't know which method I can use, I have tried to use 'getSettings()', but it too large to save in the database...Is there any better ways? Thanks. :grinning:
### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version:
* Operating System: Windows

**Comment by palespring** [comment]
Any one can help me?

**Comment by AMBudnik** [comment]
Hey @palespring 

there is no one method that loads all the settings and returns them easily. I would recommend using the after hooks for particular features that you use + `cells` array for classes/types.

**Comment by wuganzhi** [comment]
> 任何人都可以帮助我吗？

Do you solve the problem? I have the same requirements, and I get an empty {} using getSettings().  I can only get the data in the table through getData(), which will cause all the styles and merges Cell and other operations are lost
