### ISSUE TITLE
Select editor will throw an error on arrow key down

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#5899]
### Description

Select editor will throw an error when user wants to navigate options using the arrow keys.
Reference: #5898

`event` variable is not defined before use in `onBeforeKeyDown` callback:

https://github.com/handsontable/handsontable/blob/5b7697a348ced1434eff5e5464bfff30e4d5c57b/src/editors/selectEditor.js#L286-L290

### Steps to reproduce

1. https://jsfiddle.net/gx5o87bL/
2. Open editor for column B
3. Use arrow up / down to change the value
4. `ReferenceError: event is not defined`

### Demo

https://jsfiddle.net/gx5o87bL/

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: Firefox
* Operating System: OS X

**Comment by AMBudnik** [comment]
This issue is no longer replicable using v.8.2.0 

Tested using Chrome 87/Firefox 84 on Windows 10.
