### ISSUE TITLE
contextMenu doesn't disabled some options when nestedRows is turn on

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5901]
### Description
`Insert row above` and `Insert row below` doesn't disabled in `contextMenu` when `nestedRows` is turn on, but both of them should be turned off. 

### Steps to reproduce

1. Try to click `Insert row above` or `Insert row below`. Nothing happens. So both options should be turned off, when `nestedRows` is turn on.

### Demo

https://jsfiddle.net/2tcaphyg/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by aninde** [comment]
We need to rethink the logic of inserting rows when `nestedRows` in enabled. Related to #6324.

**Comment by wszymanski** [comment]
@pnowak There was an error in console. It was described by @aninde within https://github.com/handsontable/handsontable/issues/6324. I'm closing it.
