### ISSUE TITLE
Cascading Dropdown 

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#5903]
hello,
i try to make work "cascading drop down" work,
i make a simple case .
when i choose a car named Tesla , i have 2 colors black or white
when i choose a car named Nissan , i have 2 colors blue or red

http://jsfiddle.net/jeanmarc/gur9dkh4/4/

if i change for the second line  "Nissan" ,  the color from  "Blue" to "red", it works , i have in the console chrome the two lines

process blue col 1 row 1
process red col 1 row 1

Now, if i enter in the editor for the second line like
![image](https://user-images.githubusercontent.com/11042160/54765589-15227e00-4bfa-11e9-8a41-b2203c46bf9a.png)

i don't choose a value , i click on row 3 column 0, i have invalid cell
![image](https://user-images.githubusercontent.com/11042160/54765728-4f8c1b00-4bfa-11e9-9767-6d2e73e1897a.png)
and in the console
process red col 1 row 1
process red col 0 row 3

it's related with hot.getSelectedLast(), i don't know how to get the column and row from the list i leave.
i don't know why function (query, process) is called twice
any help would be appreciate.

### Your environment
* Handsontable version: PRO 3.0.0
* Browser Name and version: Chrome 73
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @jeanmarc78 

this case looks very similar to the example of https://handsontable.com/blog/articles/2016/4/expand-your-app-with-cell-dependencies in the Select-dependent cells paragraph.

If I'm wrong please let me know but I think that the proposed JSFiddle should help

**Comment by jeanmarc78** [comment]
hello,
thanks but it's not the same, i would like to limit the select list drop down color when a user choose a car.
when the car is Tesla , the user can only select black or white color, it's a kind of "dynamic drop down "

regards
jm

**Comment by AMBudnik** [comment]
To limit a list you still should pass a new list (just shorter) via the `afterChange` hook.
