### ISSUE TITLE
New version of chrome is throwing errors on scroll for HT

### ISSUE THREAD

**Issue by m2a2x** [handsontable/handsontable#5904]
### Description
On every single scroll HT chrome is throwing hundreds errors:

[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312

### Steps to reproduce

Steps to reproduce:
1) Parent window has scroll
2) HT has scroll

Scroll first parent window down. Return to HT, scroll HT, console is wholly red.
https://jsfiddle.net/1gp9zuw3/

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 6.2
* Browser Name and version: chrome
* Operating System: windows

**Comment by AMBudnik** [comment]
Thank you for sharing the report.

One of our developers replicated the issue and is investigating it.

**Comment by AMBudnik** [comment]
Hey @m2a2x 

I'm glad to inform that this issue has been solved in v `7.0.0`. Please update and let me know if it works for you.
