### ISSUE TITLE
Selection of a whole row does not happen consequently after selecting a row header.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5906]
### Description

Selection of a whole row does not happen consequently after selecting a row header.

### Steps to reproduce

1. Select (LBM) cell B2
2. Use RMB for the 2nd row header  
3. Select (LBM) cell A2
4. Use RMB for the 2nd row header 

**Result**:
You should get a selection of a whole row when you RMB the header of a row, but when you previously selected the first cell from a row, then it does not happen.

### Demo

https://jsfiddle.net/AMBudnik/g56mudLk/

Inform Zen #22678

### Your environment
* Handsontable version: 7.0.0
It doesn't seem to be version related.
* Browser Name and version: Chrome 72
* Operating System: MacOS Mojave

**Comment by AMBudnik** [comment]
Remains the same in `8.0.0-beta2-rev21` https://jsfiddle.net/pwdetrv1/

**Comment by AMBudnik** [comment]
Solved in `8.0.0-beta2-rev22` https://jsfiddle.net/c50hs82n/

**Comment by AMBudnik** [comment]
Works well using latest build https://jsfiddle.net/zejugrt4/ (frozen beta2)

**Comment by aninde** [comment]
Still, works well with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/p915wcjm/.

**Comment by AMBudnik** [comment]
Issue solved in v 8.0.0

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
