### ISSUE TITLE
fixedRowsBottom throwing errors when height is too short

### ISSUE THREAD

**Issue by m2a2x** [handsontable/handsontable#5907]
### Description
When fixedRowsBottom are the only rows visible on the tables they throwing errors when you click on them.

Cannot read property 'position' of undefined
https://jsfiddle.net/f16e4kL2/

### Steps to reproduce

1. Make table size exact to fixed bottom rows amount
2. Click on the latest fixed row
3. You will get error  Cannot read property 'position' of undefined

### Demo
https://jsfiddle.net/f16e4kL2/

### Your environment
* Handsontable version: 6.2
* Browser Name and version: chrome
* Operating System: windows

**Comment by AMBudnik** [comment]
Thank you for sharing the demo. Actually, we only get an error when the table is to short to show all the fixed rows.
If I change the `100` to `300` for the height settings it works as expected.

**Comment by m2a2x** [comment]
> Thank you for sharing the demo. Actually, we only get an error when the table is to short to show all the fixed rows.
> If I change the `100` to `300` for the height settings it works as expected.

@AMBudnik thank you for so prompt answer. Actually we have scenario, where table appear on the screen at the bottom part and after scrolling we increase it height. While it's small at the bottom our users could click on it and get errors which is definitely not ok.

We are using your table as commercial user and we expect version stability, it's mean we can not limit ourself by limit of height or something. Thank you for understanding.

**Comment by AMBudnik** [comment]
Thank you for additional description. We will investigate this issue and report it back.

**Comment by m2a2x** [comment]
Hello guys, any news on it?
We are getting a lot of troubles here.

**Comment by AMBudnik** [comment]
Hey @m2a2x 

do you have the same example as the one from the link (1 post)?

![Zrzut ekranu 2019-06-27 o 10 03 33](https://user-images.githubusercontent.com/10757813/60248434-ef74d700-98c2-11e9-8d7a-d0a8653b4c79.png)

**Comment by AMBudnik** [comment]
We had a chat about this case but to be honest we don't know what would be a perfect solution in this case. If the container is so narrow that it cannot show a header and all the fixed rows - how it should act and look? What would be the desired behavior?

**Comment by wojciechczerniak** [comment]
Looks like it's fixed in 7.1.1: https://jsfiddle.net/tohnkvsd/ 

My guess on #6079 or #6084. Please confirm, @AMBudnik @aninde

**Comment by AMBudnik** [comment]
There's no error in `7.0.0` but it still looks bad

![image](https://user-images.githubusercontent.com/10757813/65140225-62977080-da0e-11e9-885f-7d4a57f0b89e.png)

([`8.0.0.-rc1`](https://jsfiddle.net/handsoncode/eLafbutw/))

**Comment by wojciechczerniak** [comment]
Already in progress: https://github.com/handsontable/handsontable/pull/6269#issuecomment-532553106

Let's focus on the throwed error here, and we will fix the look as a part of #5947 / #6269

**Comment by aninde** [comment]
@wojciechczerniak @AMBudnik I confirm, the issue described here is fixed in 7.1.1. and 8.0.0rc1 v.

**Comment by AMBudnik** [comment]
Cool. So if we all agree we can close this topic.
