### ISSUE TITLE
In iframe + firefox, clicking on the cell the 'page scroll to top' issue still exist

### ISSUE THREAD

**Issue by vincent-cm** [handsontable/handsontable#5910]
@AMBudnik @swistach Can you please **reopen** this bug (https://github.com/handsontable/handsontable/issues/5605), observed this bug did _not_ fixed.
Reason: The jsfiddle used by your demo page has changed, jsfiddle is no longer using iframe. So even thought it is scrolling fine on Firefox, it should not indicate the bug fixed.

To Reproduce, open any Firefox browser
1. Open this link [https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe)
2. Copy and paste following code into **body** part of the left side editor, replace all content of **body**

```
<iframe src="https://www.w3schools.com/code/tryit.asp?filename=G2EPME2C1SQB" width="800" height="800">
</iframe>
```

3. Click "**run**" inside the loaded iframe over the right preview pane
4. Resize the browser height to make scrollbar appear, scroll down the content and click on one of the table cells.

Observed that the whole page scroll to top.

> It is hard to reproduce since service like _jsfiddle_, _cssbin_ are blocking iframe embedding and only can be run once. Once saved, it will add up a restricted header check and blocks the loading.

**Comment by vincent-cm** [comment]
```
                                var scrollEventTarget = { insideFrame: false } 

				container.addEventListener('mouseenter', function() {
					scrollEventTarget.insideFrame = true;
					scrollEventTarget.scrollX = window.scrollX;
					scrollEventTarget.scrollY = window.scrollY;
				});

				container.addEventListener('mouseleave', function() {
					scrollEventTarget.insideFrame = false;
				});

				document.addEventListener('scroll', function() {
					if (scrollEventTarget.insideFrame)
					window.scrollTo(scrollEventTarget.scrollX, scrollEventTarget.scrollY);
				});
```

Btw, I added above workaround to prevent event triggering for the container with hansontable, hope it helps.

**Comment by AMBudnik** [comment]
Thank you for creating a new issue. It will be much easier to track progress. The previous one already had a list of commits.

**Comment by wojciechczerniak** [comment]
@vincent-cm We've got a PR #5891 ready. Maybe you can check it out?

**Comment by vincent-cm** [comment]
@AMBudnik please check the video below, just follow above reproduce step on macOS, also windows 10.
[http://sendvid.com/uptzunuu](video)

**Comment by AMBudnik** [comment]
I was able to replicate the issue, thank for sharing the video @vincent-cm

**Comment by AMBudnik** [comment]
Welcome back @vincent-cm 

we've just pushed a new version of Handsontable - 7.0.0 where we fixed the issue.

Please update and check if it works for you as well.

**Comment by vincent-cm** [comment]
@AMBudnik Can you fix this version on 6? As we raised the bug on a free version which should not close this issue as per License guide.

**Comment by wojciechczerniak** [comment]
@vincent-cm  No. It doesn't work this way. We're fixing bugs, adding features and releasing new version using the `semver`.
