### ISSUE TITLE
[2.0.0+] Dropdown scrolling effecting table scrolling

### ISSUE THREAD

**Issue by tjgambs** [handsontable/handsontable#5913]
### Description

Scrolling inside a dropdown effects both the dropdown and the table behind it. This should instead be only scrolling the dropdown.

### Steps to reproduce

1. Open a dropdown with greater than 10 values
2. Scroll inside that dropdown
3. The scrolling effects both the dropdown as well as the table behind it.

### Demo

https://jsfiddle.net/tjgambs/acyrwhm2/34/

![example](https://user-images.githubusercontent.com/10355191/54950607-a3a34200-4f0f-11e9-9e47-67dae870d182.gif)

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 73.0.3683.86, Firefox 62.0.2, Safari 12.0.3
* Operating System: MacOS 10.14.3 

In terms of replicating this issue, all browsers on MacOS have the issue as shown in the gif above: Chrome, Firefox and Safari. I haven't had any problem with Google Chrome on Linux, but when I try to use Firefox on Linux, this scrolling issue appears again.

I did some searching through your old issues and I found this issue that appears to be similar to mine: #4651

Any help regarding the issue would be greatly appreciated. Thanks.

**Comment by tjgambs** [comment]
As a follow up on this issue, I have done some debugging and have found that the correct functionality exists on handsontable v1.18.1. After the update to v2.0.0, the scrolling issue begins to appear. I hope this helps.

**Comment by AMBudnik** [comment]
Really appreciate @tjgambs 

I can also add that it works fine on Windows 10, but breaks on Mac.

**Comment by AMBudnik** [comment]
we've just spotted a similar issue here https://github.com/handsontable/handsontable/issues/4651 not sure if this is the same one or not

**Comment by tjgambs** [comment]
Hey @AMBudnik,

Yeah, I mentioned that issue towards the bottom of my issue. #4651 appears to be experiencing the same problem as me. Thanks for looking into this. Please let me know of any leads, I can help debug on my end.

**Comment by tjgambs** [comment]
Hey@AMBudnik,

@apegadoboureghida and I dug into this issue today and proposed a solution. This solution works for us, let us know if it works for you guys. Thanks.

**Comment by AMBudnik** [comment]
would you be able to create a pull request @tjgambs?
Only then I'll be able to pass the code changes to a developer.

**Comment by AMBudnik** [comment]
Hey @tjgambs 

Thanks again Tim, for sharing this issue.

The fix is available in v `7.1.1`
