### ISSUE TITLE
Filters and trimRows plugins can't work simultaneously

### ISSUE THREAD

**Issue by Samitier** [handsontable/handsontable#5915]
### Description
The plugins `filter` and `trimRows` are incompatible and cannot work at the same time.

### Steps to reproduce
1. Initialize a table with the options `filters: true` and `trimRows: [someRowIndex]`.
2. If both options are specified, `trimRows` will not filter any row.

### Demo
https://jsfiddle.net/dgmLat68/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 72
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the issue. I have replicated the bug. When I comment out the `filters` `trimRows` hides the 4th row.

Related topics: 
https://github.com/handsontable/handsontable/issues/4567
https://github.com/handsontable/handsontable/issues/5112

**Comment by vk-sourcefuse** [comment]
Yes, same is minSpareRows adds extra spare lines if we use with "trimRows: [],"

**Comment by AMBudnik** [comment]
Issue fixed in 8.0.0-rc1
Updated demo https://jsfiddle.net/handsoncode/asjoku45/
Tested on Chrome 77 / Windows 10.

#### Previosuly
`trimRows` (`trimRows: [4]`) has blocked by filters (`filters: true`)

#### In 8.0.0-rc1
`trimRows` is able to work with filters plugin and the trimmed row is not visible on the table initial load

![image](https://user-images.githubusercontent.com/10757813/65028244-0ebc5700-d93c-11e9-9c17-eb07701e98af.png)

**Comment by AMBudnik** [comment]
Hi @Samitier @vk-sourcefuse 

We've just released version 8.0.0-beta1 where this issue is fixed https://jsfiddle.net/z6c14qgo/
As this is only a beta now we do not recommend using it on the production. However, we wanted to share the version for you to test so any comment highly appreciated 👍

**Comment by vk-sourcefuse** [comment]
Thanks :)

**Comment by AMBudnik** [comment]
@vk-sourcefuse already knows the good news, but @Samitier hasn't been notified yet that v 8.0.0 is now online and along with other 150+ other issues it solves this issue as well :-)
Updated demo https://jsfiddle.net/sk4dzyoL/

Feel free to leave some feedback.

**Comment by vk-sourcefuse** [comment]
Yes, Now 
` filters: true,
  trimRows: [4]`
 are working at same time. Thanks @AMBudnik  for updating regarding this issue too :+1:
