### ISSUE TITLE
After setting the table style and background color with Handsontable, if the set table style and background color are saved locally or exported

### ISSUE THREAD

**Issue by cangqiongduanxue** [handsontable/handsontable#5918]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by cangqiongduanxue** [comment]
![image](https://user-images.githubusercontent.com/34528217/55001738-3aefbe80-5010-11e9-9f25-a724c3e76230.png)

**Comment by AMBudnik** [comment]
Hey @cangqiongduanxue 

How to replicate the issue?

**Comment by cangqiongduanxue** [comment]
I want to save the table style and the background color of the cell. Next time I open the table, I can keep the set style and background color. How can I operate this?

> Hey @cangqiongduanxue
> 
> How to replicate the issue?

I want to save the table style and the background color of the cell. Next time I open the table, I can keep the set style and background color. How can I operate this?

**Comment by AMBudnik** [comment]
> I want to save the table style and the background color of the cell.

It depends on how you change the background. Do you pass a className from a server call or allow your user to pick it up from an input. Can you send over a demo with your settings and configuration at support@handsontable.com?
