### ISSUE TITLE
Horizontal scrolling breaks with date column

### ISSUE THREAD

**Issue by bgrohman** [handsontable/handsontable#592]
When I add a date typed column, the table will not allow me to scroll horizontally past the date column.

I created a jsFiddle based on the date cell type demo.

http://jsfiddle.net/6XSs3/1/

**Comment by AMBudnik** [comment]
Does not occur - issue related to Datepicker. Please check [this example](https://jsfiddle.net/AMBudnik/8c2g4h96/) which work as expected.
