### ISSUE TITLE
setDataAtCell sets undefined in the active editor

### ISSUE THREAD

**Issue by Samitier** [handsontable/handsontable#5920]
### Description
We have a table with undefined cells. When we are editing an undefined cell, if we execute `setDataAtCell` for an arbitrary cell with an arbitrary value, the current cell being edited gets `undefined` as text value.

### Steps to reproduce
1. Create a table with undefined cells
2. Start editing a cell
3. Execute `setDataAtCell` for an arbitrary cell
4. The cell being edited will get the string `undefined` as value

### Demo
https://jsfiddle.net/pe9szoga/
(the first cell is selected programatically and `setDataAtCell` will execute after 2 seconds, revealing the bug).

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 72
* Operating System: Windows 10

Possible related issue: #4836

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @Samitier 

You're right the `undefined` is translated to a string. It looks like `null` is not affected.

**Comment by AMBudnik** [comment]
Hi @Samitier 

Please update to 7.4.2, this issue is already solved https://jsfiddle.net/AMBudnik/6zfygxq8/
