### ISSUE TITLE
exporting to excel for large length data gives wrong value

### ISSUE THREAD

**Issue by NKatty** [handsontable/handsontable#5923]
![demo](https://user-images.githubusercontent.com/48983364/55064149-800f0180-509f-11e9-8cb2-2ab44674e7cd.PNG)
### Description
While exporting data to excel(csv), we have a value of length 15 which is then opening in scientific form in excel after exporting.
Is there any way that the same value can be exported as string without giving the exponential value 

### Steps to reproduce
1. Open the Fiddle link https://handsontable.com/docs/7.0.0/demo-export-file.html 
2.Then you can go to Live examples for Export to file
3. Change a column value to 312784293847293
4. Now export the sheet and you will see the value as 3.12784E+14. It should be 312784293847293847204. 

### Your environment
* Handsontable version: 5.0.1
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @NKatty 

have you considered calling `setCellMeta` for the cell to pass `cellType = 'text'` just before running the export?

**Comment by NKatty** [comment]
no I did not use setCellMeta .. I am doing exactly what the Fiddle example shows.
Can you please explain how to resolve this.

**Comment by AMBudnik** [comment]
When I use this demo https://jsfiddle.net/2gkbrhjy/ (just added some numeric data. Then I get the whole number in Excel.

**Comment by NKatty** [comment]
So now when you are exporting this to excel it is showing 3.13E+14 value.
I need it as 312784293847293 in export file..
Please see the attached screenshot. Here the input data was 479374829473482940 but I am getting 479374829473482000 as exported value.
![Capture1](https://user-images.githubusercontent.com/48983364/55129548-8653bb00-513d-11e9-893f-95988d1d08b9.PNG)

![demo2](https://user-images.githubusercontent.com/48983364/55129532-76d47200-513d-11e9-8e16-c195ca43dc56.PNG)

**Comment by NKatty** [comment]
yes.. do we have a way to solve this

**Comment by AMBudnik** [comment]
It is more a feature request cause we cannot change the way excel converts it. I have discussed the subject with our CTO and he told me that we can treat this is a feature request.

**Comment by NKatty** [comment]
Please let me know once this gets a solution.
Thanks in advance

**Comment by AMBudnik** [comment]
We've checked the example once again and it looks like it's a matter of parsing numbers on the Handsontable side so it's rather a bug.

**Comment by NKatty** [comment]
Formatting the column is not giving me the exact value.
It is removing e notation but adding 0. Not able to retrieve the inital number.
Can you provide a solution here

**Comment by wojciechczerniak** [comment]
1. Open the demo @AMBudnik have provided: https://jsfiddle.net/2gkbrhjy/
2. Export to CSV
3. Open `Handsontable 2019-04-02.csv` file in any text editor:

```
1,312784293847293,5,6
2,3,2,6
3,4,1,0
4,7,4,7
5,8,5,7
6,9,6,5
```

Looks like everything is ok. If Excel, Open Libre, Numeric or any other application displays it differently it's because of formatting or import CSV settings. Nothing for us to do.

Here's the screenshot that you've attached earlier, the correct value is already there:
![55129532-76d47200-513d-11e9-8e16-c195ca43dc56](https://user-images.githubusercontent.com/4718998/55382944-37d06300-5527-11e9-93ac-b1f91c90bf42.PNG)

**Comment by NKatty** [comment]
But the correct value was 479374829473482940 not 479374829473482000 as you can see in the above example that i mentioned

**Comment by NKatty** [comment]
In text editor it shows the correct value, but i cannot ask the user to first export in csv , then open in any text editor to check the correct value.

**Comment by wojciechczerniak** [comment]
Sorry, I was looking for a bug in Handsontable. You don't have to ask the user to open file in text editor. I'm showing the file content just to verify that we've done everything correctly.

It's a limitation of Excel: http://excelunplugged.com/2014/05/19/15-digit-limit-in-excel/

I guess we can import them as Text:
![Screenshot 2019-04-02 at 10 31 29](https://user-images.githubusercontent.com/4718998/55389698-0f9c3080-5536-11e9-9b04-0a791ce955de.png)
![Screenshot 2019-04-02 at 10 32 11](https://user-images.githubusercontent.com/4718998/55389699-1034c700-5536-11e9-84fe-ff3ab011c821.png)
![Screenshot 2019-04-02 at 10 32 40](https://user-images.githubusercontent.com/4718998/55389700-1034c700-5536-11e9-99ee-868f63119fbd.png)
![Screenshot 2019-04-02 at 10 33 06](https://user-images.githubusercontent.com/4718998/55389701-1034c700-5536-11e9-9458-bd1d9f05f5e8.png)

**Comment by Vera1128** [comment]
> ![demo](https://user-images.githubusercontent.com/48983364/55064149-800f0180-509f-11e9-8cb2-2ab44674e7cd.PNG)
> 
> ### Description
> While exporting data to excel(csv), we have a value of length 15 which is then opening in scientific form in excel after exporting.
> Is there any way that the same value can be exported as string without giving the exponential value
> 
> ### Steps to reproduce
> 1. Open the Fiddle link https://handsontable.com/docs/7.0.0/demo-export-file.html
>    2.Then you can go to Live examples for Export to file
> 2. Change a column value to 312784293847293
> 3. Now export the sheet and you will see the value as 3.12784E+14. It should be 312784293847293847204.
> 
> ### Demo
> ### Your environment
> * Handsontable version: 5.0.1
> * Browser Name and version: Chrome
> * Operating System: Windows 10

you got a solution?

**Comment by AMBudnik** [comment]
Hi @Vera1128 have you tried the latest @wojciechczerniak  comment?
