### ISSUE TITLE
How to add multiple checkbox in a cell

### ISSUE THREAD

**Issue by shiyuanzheng** [handsontable/handsontable#5924]
Hey, How to add multiple checkbox selection boxes in a cell，I have tried it for a long time, I don't know how to do it, can you help me?
As shown in the picture below
![image](https://user-images.githubusercontent.com/21303085/55067103-0fc1a980-50ba-11e9-85b3-2a0dc38a4b65.png)

### Your environment
* Handsontable version: 6.2.2

**Comment by AMBudnik** [comment]
Hey @shiyuanzheng 

do you mean something like this https://jsfiddle.net/d0sow4ru/?

**Comment by shiyuanzheng** [comment]
Hi @AMBudnik 
Sorry, this is my current processing method, but I can't meet the current project requirements, and can't handle effective data processing in html mode.
I now want to use the checkboxRenderer mode to display multiple checkboxes. I read this part of the source code and can add multiple checkboxes, but they all bind the same cell data,So I can't select a single checkbox.

**Comment by AMBudnik** [comment]
> I can't meet the current project requirements, and can't handle effective data processing in html mode.

Can you tell me more about it? If you want to share a demo or just doesn't want to share information on Github please write to me at support@handsontable.com
