### ISSUE TITLE
Cells with longer text are misleading copy&paste

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5925]
### Description

Cells with longer text that are copied from Excel or Google Sheets are misleading copy&paste so me miss the empty cells after paste.

### Steps to reproduce

1. Type The following data into Excel of Google Sheets (`B` is empty)
![image](https://user-images.githubusercontent.com/10757813/55076984-03782500-5097-11e9-82a8-b3bdd3449c85.png)

2. Select those 4 cells and paste then into Handsontable
https://handsontable.com/docs/7.0.0/demo-numeric.html

**Result**:
The empty cell is skipped and you get 3 cells only

### Demo

https://handsontable.com/docs/7.0.0/demo-numeric.html

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: Chrome 73
* Operating System: Windows 10

**Comment by swistach** [comment]
Present since v6.1.0. What is interesting, Excel considers overlapped cells as a colspan
```
 <tr height=21 style='height:16.0pt'>
<!--StartFragment-->
  <td height=21 colspan=2 width=174 style='height:16.0pt;mso-ignore:colspan;width:130pt'>A very long content</td>
  <td align=right width=87 style='width:65pt'>123</td>
  <td align=right width=87 style='width:65pt'>456</td>
<!--EndFragment-->
 </tr>
```

with `mso-ignore: colspan` in inline styles.
Support for merged cells in CopyPaste should resolve this issue.

**Comment by serajin** [comment]
Adding "word-wrap" option to excel cells will temporary fix this bug, or making sure that no text is overlapping into another cell. While not ideal, it will at least resolve the issue temporarily until this bug is fixed in a newer version of Handsontable.

**Comment by AMBudnik** [comment]
Thank you for fixing @swistach !
Working version form 7.1.0
