### ISSUE TITLE
How to clear the format of the set cell

### ISSUE THREAD

**Issue by shiyuanzheng** [handsontable/handsontable#5926]
### Description
Hello, after setting the cell to time format, what can I do to clear the time format of this setting, because I want to change this cell to a normal text format. I set the cell type and render to 'text' is invalid. When I enter the text in the cell, I still verify whether it is time format. You can try the demo I created. If you have a good method, you Can you tell me, thank you very much.
Cell is set to time format:
![image](https://user-images.githubusercontent.com/21303085/55138721-1bbb7300-516f-11e9-840f-276c35e784a0.png)
Cell is set to text format:
![image](https://user-images.githubusercontent.com/21303085/55138743-25dd7180-516f-11e9-82da-c036c490a96a.png)

### Demo
http://jsfiddle.net/kaissica/Lj7hxcqv/5/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 73
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
You can reset the validator (line `33`). Updated demo http://jsfiddle.net/5mksb29p/

**Comment by shiyuanzheng** [comment]
@AMBudnik 
Thank you very much, this is valid, the input text will not be verified after the 'Time' format is changed to 'text', but some other properties about the time format are still set in the current cell settings, such as "{timeFormat: ' HH:mm:ss', correctFormat: true, defaultDate: moment().format('HH:mm:ss')}", is there any way to remove these attributes and restore the original attribute configuration of the cell.

**Comment by shiyuanzheng** [comment]
And when the cell format is set to ‘date’, the cell type and render are set to ‘text’, and after validator = undefined, the cell is still of type date. I click again to trigger the pop-up of the selected date again.
![image](https://user-images.githubusercontent.com/21303085/55149089-76ab9500-5184-11e9-83c6-f3220b45b761.png)
![image](https://user-images.githubusercontent.com/21303085/55149431-1d903100-5185-11e9-8c31-952ca824fa55.png)

**Comment by AMBudnik** [comment]
What do you do? I
1. Click the `date` button
2. Click the `clear` button
and I do not get the date editor that you have

**Comment by AMBudnik** [comment]
I believe that you've found a solution as there's no reply for more than a week but if not, please leave a comment and I'll reopen the topic.
