### ISSUE TITLE
I can’t reset/reinitialize the table after I have opened a table with data

### ISSUE THREAD

**Issue by palespring** [handsontable/handsontable#5928]
### Description

There are three buttons, 'OpenClick', 'updateClick', 'ResetClick'

The expected result is like this:

- if I click the 'OpenClick' button, it will show like this --
![image](https://user-images.githubusercontent.com/32152214/55205116-82429e80-520c-11e9-8eb2-707f78ddca71.png)

- if I click the 'updateClick' button, it will show like this --
![image](https://user-images.githubusercontent.com/32152214/55205140-9d151300-520c-11e9-9b50-e8cc9c495c0d.png)

- and if I click the 'ResetClick', it will show like this --
![image](https://user-images.githubusercontent.com/32152214/55205156-ae5e1f80-520c-11e9-8fe8-5c5bb0d8c012.png)
But the actual result is, when I click on the first two buttons, it shows correctly. But when I click the 'resetClick' button (after the 'updateClick'), it shows this -- 
![image](https://user-images.githubusercontent.com/32152214/55205172-c33ab300-520c-11e9-9d53-dfc32dd55168.png)
Obviously it is not correct.

I tried using the destroy() method, but it gives an error.
![image](https://user-images.githubusercontent.com/32152214/55205216-ed8c7080-520c-11e9-8a45-48ab715ef7b4.png)

And the table dosen't re-initial. Any one can help me? Thanks.

### Steps to reproduce

1.open the demo
2.click three buttons one by one
3.press F12 to open the Chrome Developer mode console

### Demo

https://jsfiddle.net/Jeremy_Chan/wtxq4cv5/

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: Chrome 73.0.3683.75 64bits
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
This topic has been already published on our forum https://forum.handsontable.com/t/i-cant-reset-the-table-after-i-have-opened-a-table-with-data/3105/5

Please continue the conversation in the same topic.
