### ISSUE TITLE
Support for custom sort algorithms

### ISSUE THREAD

**Issue by bgrohman** [handsontable/handsontable#593]
I need to be able to implement a custom sort algorithm to apply when a user clicks on a column header. I'd like to be able to pass in a custom comparison function that accepts the two rows being compared along with which column was chosen for sorting.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by jdmcnair** [comment]
I haven't tried it, but it looks like the requested feature is now available: https://docs.handsontable.com/0.24.1/Options.html#sortFunction

**Comment by AMBudnik** [comment]
Has been added with https://github.com/handsontable/handsontable/issues/3308
