### ISSUE TITLE
Handsontable use method loadData in IE11 loading takes too lang

### ISSUE THREAD

**Issue by 80sky** [handsontable/handsontable#5930]

**Comment by 80sky** [comment]
![image](https://user-images.githubusercontent.com/22342011/55273812-3fb3bb80-530b-11e9-926e-9e406bff6a64.png)
![image](https://user-images.githubusercontent.com/22342011/55273821-54904f00-530b-11e9-85cb-2bc19057942b.png)

What should I do，Thanks！

**Comment by 80sky** [comment]
I use the interface to dynamically fetch data and then dynamically render the list

**Comment by AMBudnik** [comment]
Good approach @80sky 

I think that we can close the issue ad the `loadData` itself just changes the data underneath the table and rerenders the view. It a matter of rendering itself that it takes so long.
