### ISSUE TITLE
If any of cells is specified as a `checkbox` changing a checkbox in a header produces an error

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5934]
### Description

If any of cells is specified as a `checkbox` changing a checkbox in a header produces an error.

We get an error if we use `type: 'checkbox',` for the table or use it for any given cell. It doesn't matter if it is in the same column or row with the changed header.

### Steps to reproduce

1. Open the console
2. Click the checkbox in the header

![GIF](https://user-images.githubusercontent.com/10757813/55390541-b9c88800-5537-11e9-952c-b90f6043467f.gif)

### Demo

https://jsfiddle.net/hb59w8sq/
or here https://jsfiddle.net/gup8tm3s/

### Your environment
* Handsontable version: 7.0.0
_Doesn't seem to be version related_
* Browser Name and version: Chrome 73
* Operating System: Windows 10

Inform [forum](https://forum.handsontable.com/t/typescript-error-property-registerrenderer-does-not-exist-on-type-renderers/3100/12)

**Comment by mallory-eaton** [comment]
Any progress on this bug?

**Comment by AMBudnik** [comment]
Sorry, there is no milestone attached yet

**Comment by mirkogeest** [comment]
I have also the same problem. Solved it adding this hook to the settings:

```
      beforeChange: (change, source) => {
        if(change.length && change[0] && change[0].length && change[0].filter(value => Number.isNaN(value)).length) {
          return false;
        }
        return true;
      },
```

**Comment by AMBudnik** [comment]
This issue is still replicable in v8.2.0 https://jsfiddle.net/Laut9wyo/

**Comment by aninde** [comment]
This issue willed by v8.4.0/
Demo https://jsfiddle.net/k64zc0rd/
