### ISSUE TITLE
expect false but the result of isEmptyRow is true

### ISSUE THREAD

**Issue by duanyijie** [handsontable/handsontable#5935]
### Description
the result of isEmptyRow is true when the type of first col is Array while the value is [] 
but it should be false because it has value in the rest of cols

here is the code : 
```
 isEmptyRow(row) {
    let col;
    let colLen;
    let value;
    let meta;

    for (col = 0, colLen = this.countCols(); col < colLen; col++) {
      value = this.getDataAtCell(row, col);

      if (value !== '' && value !== null && isDefined(value)) {
        if (typeof value === 'object') {
          meta = this.getCellMeta(row, col);

          return isObjectEqual(this.getSchema()[meta.prop], value); 
         // the situation is
         // this.getSchema()[meta.prop] is []
         // value is []
         // isObjectEqual([], []) is true
         // it should be continued when the result is true
        }
        return false;
      }
    }

    return true;
  },
```

![image](https://user-images.githubusercontent.com/16126552/55540693-0d80d000-56f6-11e9-8483-35614b8a369c.png)

### Demo
I can't visit https://jsfiddle.net/handsoncode/8ffpsqt6/ some how
so there is no demo

### Your environment
* Handsontable version: 6.0.1
* Browser Name and version: Chrome 71.0.3578.98
* Operating System: win10

**Comment by AMBudnik** [comment]
Sorry, there are some variables that do not tell me much. Maybe you can send a .zip or use other js playground (Codepen, Stackblitz)

**Comment by AMBudnik** [comment]
I think that the issue might be already solved as there's no reply for more than 10 days

**Comment by AMBudnik** [comment]
Just got a new demo from our developer https://jsfiddle.net/js_ziggle/91hmvaop/ so the issue's confirmed. Please stay tunned @duanyijie

**Comment by AMBudnik** [comment]
I've been provided with a new demo where we use the array structure to define columns https://jsfiddle.net/954fybsx/ and here it works great. There are no errors and the table is editable.
I guess that it makes the issue no longer a problem and it can be closed.
