### ISSUE TITLE
dataMap.js--dataRow is undefined

### ISSUE THREAD

**Issue by hutiantian04** [handsontable/handsontable#5937]
### Description
src\dataMap.js
In the 656 row， set function， ‘’dataRow ‘’may be undefined; but in the 699 row，【dataRow [prop] = newValue; 】directly used, reported an error.
error: Uncaught TypeError: Cannot set property 'xxxxx' of undefined

### Your environment
* Handsontable version: 7.0.1
* Browser Name and version: Google Chrome version: 73.0.3683.86
* Operating System: win10

**Comment by AMBudnik** [comment]
Hi @hutiantian04 

when do you get this error? Can you send a demo where the issue can be replicable?

**Comment by hutiantian04** [comment]
I clicked on other buttons outside the table of the screen, and then gave the value to the table again.

**Comment by hutiantian04** [comment]
dataMap.js:789 Uncaught TypeError: Cannot set property 'xxx' of undefined
    at DataMap.set (dataMap.js:789)
    at applyChanges (core.js:1139)
    at Object.onQueueEmpty (core.js:1275)
    at Object.checkIfQueueIsEmpty (core.js:983)
    at Object.removeValidatorFormQueue (core.js:977)
    at core.js:1075
    at done (core.js:1189)
    at core.js:1213
    at ColumnSettings.autocompleteValidator (autocompleteValidator.js:17)
    at core.js:1205

**Comment by AMBudnik** [comment]
Can you send over a demo or tell me on which of our official demos are you able to replicate this issue https://handsontable.com/docs/7.0.1/tutorial-introduction.html

**Comment by hutiantian04** [comment]
handsontable for angular
step1：click button，Call the API and get the data
step2：rebind table data
ins: Handsontable;
this.ins = this.hotRegisterer.getInstance('hot');
operationApiDataList() {
    this.apiDatas = [];
    const option = <ApiOption>{
      apiKey: 'readDatas',
    };
    this.services.geReadDatas(option).subscribe(
      (val) => {
        this.handsontableDatas = [];
        this.mergeCells = false;
        if (val && val.length > 0) {
          this.handsontableDatas = val;
          // set the merge line
          // this.mergeCells is array
          this.setMergeCells();
        }
        if (this.ins) {
          this.ins.updateSettings({
            mergeCells: this.mergeCells,
            data: this.handsontableDatas,
          });
        }
      },
      (err) => {
      }
    );
  }

**Comment by AMBudnik** [comment]
Can you check if adding `outsideClickDeselects: false' after `mergeCells: this.mergeCells,` solves the issue?

**Comment by hutiantian04** [comment]
Hi AMBudnik 
The issue is solved, thank you very much.

**Comment by hutiantian04** [comment]
Hi AMBudnik
This problem has appeared again.

step1： Data is shown in the table
step2：Click button，Call the API and get the data
step3：Rebind table data and the data is empty
ins: Handsontable;
this.ins = this.hotRegisterer.getInstance('hot');
operationApiDataList() {
this.apiDatas = [];
const option = {
apiKey: 'readDatas',
};
this.services.geReadDatas(option).subscribe(
(val) => {
this.handsontableDatas = [];
this.mergeCells = false;
if (val && val.length > 0) {
this.handsontableDatas = val;
// set the merge line
// this.mergeCells is array
this.setMergeCells();
}
if (this.ins) {
this.ins.updateSettings({
mergeCells: this.mergeCells,
data: this.handsontableDatas,
});
}
},
(err) => {
}
);
}
![1](https://user-images.githubusercontent.com/39802580/55940320-7629f880-5c72-11e9-8279-ed5dc85e4528.png)

**Comment by AMBudnik** [comment]
Please share a demo, where this issue can be replicable.

**Comment by hutiantian04** [comment]
Hi AMBudnik
Sorry, I tried to make a demo, but demo didn't have this problem.

**Comment by AMBudnik** [comment]
It means that something might be wrong within the code. The` 'undefined' `issue may come from the wrong order of operations. You should check of the following method correspond to the element that exists.
