### ISSUE TITLE
[6.1.0+] We can't paste merged data from Excel

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5940]
### Description

We can't paste merged data from Excel. We get a chunk of data.

### Steps to reproduce

1. Copy merged area from Excel
2. Paste to the https://handsontable.com/docs/7.0.1/demo-merged-cells.html demo

![aaGIF](https://user-images.githubusercontent.com/10757813/55798433-2fe86400-5acf-11e9-9987-4fe2719d56bf.gif)

### Demo

https://handsontable.com/docs/7.0.1/demo-merged-cells.html

### Your environment
* Handsontable version: 6.1.0+
6.0.1 works fine.
* Browser Name and version: Chrome 74
* Operating System: Windows 10

Related https://github.com/handsontable/handsontable/issues/5101
Inform [forum](https://forum.handsontable.com/t/how-do-i-copy-out-a-merged-cell/3142)

**Comment by AMBudnik** [comment]
We can also think about keeping the merged area merge the cells after we paste data. 👍

**Comment by yanglinpvp** [comment]
We use Bootstrap for css, I can't paste the merged content at all.
![image](https://user-images.githubusercontent.com/19279918/58864245-ec812f00-86e6-11e9-9392-e6176304c62c.png)

**Comment by krzysztofspilka** [comment]
@yanglinpvp what about now? We made some improvements in the latest 7.0.1.

**Comment by AMBudnik** [comment]
I think that we can close the topic but if it still doesn't work for you after updating to 7.1.0 please leave a comment.
