### ISSUE TITLE
Schema compare methods

### ISSUE THREAD

**Issue by Anmolk22** [handsontable/handsontable#5941]
I am using handsontable version 1.17.0 via ng2-handsontable wrapper for angular.
I had a grid where the two cells data represented different schema's for example 
cell1 = {
 key_one: 'KeyOne'
}
cell2 = {
 key_two: 'KeyTwo'
}

when I drag and drop from cell2 to cell1 then AutoFill.fill event is not emitted.
When I did some debugging I found that the it compares the schema and on that basis it add it to a list. Is it a expected behavior ?

currently I am using Angular 5 and ng2-handsontable (<a>https://www.npmjs.com/package/ng2-handsontable</a>)

**Comment by AMBudnik** [comment]
Can you share a demo and the action scenario? That would help a lot.

**Comment by AMBudnik** [comment]
I believe that this issue can be closed as there's no update for more than a week, but feel free to post the demo if there's still something that concerns you.
