### ISSUE TITLE
Can't resolve '../node_modules/handsontable/dist/handsontable.full.css' in '/Users/Enzyme/WebstormProjects/study/src/components'

### ISSUE THREAD

**Issue by jk90mn** [handsontable/handsontable#5944]
### Description

I ran the vue basic usage demo in the offical website of Handsontable.But i get i a error.

Can't resolve '../node_modules/handsontable/dist/handsontable.full.css' in '/Users/Enzyme/WebstormProjects/study/src/components'

### Steps to reproduce

I  use npm install handsontable @handsontable/vueue.And follow the guide in offical guide of the vue basic example.And I copy the example code into my basic Vue's Helloworld.vue.Then I got a error like below.

### Your environment
+ @handsontable/vue@4.0.0
+ handsontable@7.0.2
* Browser Name and version:Chrome
* Operating System:OSX

**Comment by AMBudnik** [comment]
Hi @jk90mn 

When I've built a project using CLI and copy-pasted exact code from the tutorial I also got the same message, but once you change the UL for CSS file it works well.

New path `'../../node_modules/handsontable/dist/handsontable.full.css' `

ps. here's a demo (zipped) https://we.tl/t-7GSqdKySCC
