### ISSUE TITLE
 handsontable‘s the last column drop-down width

### ISSUE THREAD

**Issue by hutiantian04** [handsontable/handsontable#5946]
### Description
handsontable for angualr，the  last column drop-down width is not displayed correctly

### Steps to reproduce

1.Not the last column，The dropdown width is correct
![2](https://user-images.githubusercontent.com/39802580/55946113-a9728480-5c7e-11e9-8db9-a7eb0a02ccc6.png)

2.The last column，The dropdown width is incorrect
![3](https://user-images.githubusercontent.com/39802580/55946156-bee7ae80-5c7e-11e9-80e5-23677d409bb6.png)

### Your environment
* Handsontable version: 7.0.1
* Browser Name and version:Google Chrome version: 73.0.3683.86
* Operating System:win10

**Comment by AMBudnik** [comment]
hi @hutiantian04 

what CSS settings do you have for the Handsontable and its parent?

**Comment by hutiantian04** [comment]
hi AMBudnik
If that's the only way, that's it. Thank you very much.

**Comment by AMBudnik** [comment]
We can consider this issue as a request for change. I would keep it opened.
