### ISSUE TITLE
[5.0.1+] Selection is covering on the fixed bottom rows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5947]
### Description

Selection is covering the fixed bottom rows

### Steps to reproduce

1.Select a cell that you can scroll up and down
2. Move the selected cell under the fixed bottom rows

![GIF](https://user-images.githubusercontent.com/10757813/55949286-89c56700-5c52-11e9-9440-b95d3bbdf867.gif)

### Demo

https://jsfiddle.net/handsoncode/soukg0q7/
5.0.0 works fine https://jsfiddle.net/handsoncode/gs7o631y/

### Your environment
* Handsontable version: 5.0.1+
Broken from 5.0.1
* Browser Name and version: Chrome 73
* Operating System: Windows 10

**Comment by budnix** [comment]
It appears that this issue will be fixed within https://github.com/handsontable/handsontable/pull/6157 https://jsfiddle.net/hfs758u0/.

**Comment by aninde** [comment]
This bug will be fixed by `7.1.2` v. 

**Demo**
`7.1.2`  v. https://jsfiddle.net/aninde/zvhf8m7p/

**Comment by AMBudnik** [comment]
Yeaa.. thanks guys :) Closing
