### ISSUE TITLE
allowInsertColumn not work when columns property specified

### ISSUE THREAD

**Issue by RockNHawk** [handsontable/handsontable#5949]
### Description
allowInsertColumn not work when columns property specified, if columns property removed, the allowInsertColumn worked again.

### Demo
https://jsfiddle.net/4rmk9p1c/

var container = document.getElementById('example1');
       var hot = new Handsontable(container, {
            contextMenu: true,
            allowRemoveColumn: true,
            allowRemoveRow: true,
            allowInsertColumn: true,
            allowInsertRow: true,
                       columns:[{},{},{}],
             data: Handsontable.helper.createSpreadsheetData(200, 3),
    rowHeaders: true,
    colHeaders: true,
    width: '100%',
    height: 320,
    colWidths: [45, 100, 160, 60, 80, 80, 80],
    rowHeights: [50, 40, 100],
    manualColumnResize: true,
    manualRowResize: true
  });

![image](https://user-images.githubusercontent.com/3222379/55962330-37f8fd00-5ca3-11e9-9c39-f1cb2048b9fc.png)

### Your environment
* 7.0.2 & 7.0.0

**Comment by AMBudnik** [comment]
Hey @RockNHawk 

the `columns` always sets a number of columns. No matter how many columns are in the data https://jsfiddle.net/AMBudnik/jw63ax2b/ `columns` adds or cuts them. It will also cut out the `minSpareCols` https://jsfiddle.net/AMBudnik/q4hLndt1/ 
We can say that it has the highest priority.

**Comment by RockNHawk** [comment]
@AMBudnik Thank you for taking the time to reply to me.
I use column is just to define a custom render, but also want's allow user insert new column,
but now this cause the table column locked.
Could  we consider allowing this option to be configured ?

**Comment by AMBudnik** [comment]
You can add a custom option to add a column, via button, context or dropdown menu. To add a column you'd need to update the `columns` settings. Here is an example https://jsfiddle.net/AMBudnik/nsyqcwu9/
