### ISSUE TITLE
Columns sorting is not working if the header text is with HTML content

### ISSUE THREAD

**Issue by subashdbc** [handsontable/handsontable#5951]
Hi,

I have configured settings like this
 ```
data: [list of data],
nestedHeaders: [ list of nested rows ],
columns: [columns array],
hiddenColumns: true,
colHeaders: true,
collapsibleColumns: true,
columnSorting: true,
manualRowMove: true,
```
here, sorting is working if only I press the sort icon, not when I press the header label. I have HTML content in the header text, If I remove HTML content and leave as plain text it works.
But how can we do with HTML content on the header?
Thanks in advance!

**Comment by AMBudnik** [comment]
Hey @subashdbc 

can you send over a demo? I've made one here https://jsfiddle.net/AMBudnik/ofvxuehj/ but the bolding tag for `O` column does not change the way we sort. You can stil click the header name to sort the table.

**Comment by subashdbc** [comment]
@AMBudnik thanks for the reply.
In the demo itself if you try to click only on `O` it is not sorting. That's the issue

**Comment by AMBudnik** [comment]
Yes, you're right! 
I've been testing this on Chrome 73 where this works fine, but it is broken for Firefox. 
Once I do not click the letter (a pixel away does the job) and then click the letter it works again. It looks like the issue has been introduced in v `7.0.0`, [`6.2.2`](https://jsfiddle.net/q27o05jd/2/) works fine.

**Comment by AMBudnik** [comment]
To sum it up.

It does not work from v `7.0.0` for Firefox.

Simplified demo https://jsfiddle.net/AMBudnik/98tbxqh1/

**Comment by wojciechczerniak** [comment]
It doesn't work in v6.2.2 either. Not even in Chrome (depends where you click). Or v3: https://jsfiddle.net/5dmuph04/

The reason is we check if the clicked element is `span`, any other HTML will break this check.
https://github.com/handsontable/handsontable/blob/671d7240267a11315f005a389728d113d9964313/src/plugins/columnSorting/columnSorting.js#L819

**Comment by subashdbc** [comment]
Yes, it is even not working on 6.2.3. 
But if we wrap something like this, 
`<span class="colHeader columnSorting sortAction">
   <div>
      <span>HEADER TEXT</span>
   </div>
</span>`
it works

**Comment by nikolaiivanov17** [comment]
There's a CSS workaround that you can use:

```
.handsontable span.colHeader.columnSorting:after {
	content: '';
	width: 100%;
	height: 100%;
	position: absolute;
	top: 0;
	left: 0;
}
```

**Comment by AMBudnik** [comment]
@nikolaiivanov17 @subashdbc 

This issue is not replicable in v 8.0.0 of Handsontable https://jsfiddle.net/jgcen3bd/ but it also worked well in 7.4.2 https://jsfiddle.net/ycsx3gjn/ so I call it solved.
