### ISSUE TITLE
Possible to defer rendering temporarily?

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#5952]
### Description

Is it possible to somehow defer rendering temporarily until we re-enable it? In the example provided there are 4 renders happening and we would want to possibly stop the first 3 from running and only running it once which would speed up how quickly our table loads.

### Demo

https://imgur.com/Nrjracw

**Comment by AMBudnik** [comment]
Hey @jeremy-smith-maco 

currently, there is no easy way (you might find a workaround but it would be hard to keep an ability to update), but... we're planning to add this ability in the future. 
We're still working on a pattern that will allow us to use the table in the most effective way and at the same time do not leave the developers with no choice on how they renderer their data.
I recommend checking the updates for this topic https://github.com/handsontable/handsontable/issues/5769
