### ISSUE TITLE
Modal PopUp scope is undefined

### ISSUE THREAD

**Issue by ishan30** [handsontable/handsontable#5955]
We are using handsontable with angular 7.
We have a page in which we are implementing handsontable.
We have created a svg icon button to delete the data and put in the each row of last column.
We have used column property:
{ type:'text',
renderer: this.deleteRenderer
}

We have created renderers in which we have defined the svg icon and click event using td.innerHTML

WHEN THIS BUTTON IS CLICKED, we are getting this.modalService is undefined error.

We have injected modalService from NgbModal in the constructor.

We have tried putting the svg button out of Handsontable's scope and we are able to open modal popup and all scopes are available but when we use this as inline button, we are getting scope undefined error 

Please help.

**Comment by AMBudnik** [comment]
Hey @ishan30 

can you share any demo or a video? If you cannot share a demo here please send it at support@handsontable.com

**Comment by AMBudnik** [comment]
There's a week without the demo or any other comment so I believe that I can close this topic.

**Comment by ishan30** [comment]
Hey, the issue has been resolved! Apologies for the delay in reply. 
Instead of creating external renderer, we created the inline function for renderer in order to overcome the problem of losing the scope!
