### ISSUE TITLE
Sorting breaks adding new rows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5956]
### Description

I thought that this issue can be related to this one https://github.com/handsontable/handsontable/issues/5617 but guess it is not the same case. However, it should be fixed with https://github.com/handsontable/handsontable/issues/5112

### Steps to reproduce

1. Sort column
2. Use the button

You get the new row copied into an existing row. The `getData()` method shows the data correctly but it is rendered wrong.

### Demo

https://jsfiddle.net/AMBudnik/zp0ks8y5/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
The issue stays the same after introducing changes to #5751 on the branch https://github.com/handsontable/handsontable/tree/feature/issue-5751.
Tested on Chrome 76/ macOS Mojave / local server.

Jimmy is stll duplicated
![Zrzut ekranu 2019-09-13 o 13 40 56](https://user-images.githubusercontent.com/10757813/64860019-29d15300-d62c-11e9-865f-8d8afdcec04f.png)

**Comment by aninde** [comment]
The issue is still replicable at current version 7.1.1.

**Comment by aninde** [comment]
New `index mapper` fixed inserting data after and before loadData. It will be released soon.

We are currently testing an 8.0.0rc version with many breaking changes, I recommend observing information from issue [#5751](https://github.com/handsontable/handsontable/issues/5751).

**Demo**
8.0.0rc - https://jsfiddle.net/aninde/x7jbc32s/ - fixed

**Environment**
Handsontable version:8.0.0.rc
Browser Name and version: Google Chrome version 76.0.3809.100
Operating System: macOS Mojave 10.14.6

**Comment by AMBudnik** [comment]
Update: @aninde is right.
The issue's gone in 8.0.0.rc

**Comment by AMBudnik** [comment]
No issues on the official beta1 for 8.0.0 https://jsfiddle.net/Lk528ned/

**Comment by AMBudnik** [comment]
The issue is not replicable in v 8.0.0 https://jsfiddle.net/2asbft7v/. I'm closing this issue as solved.
