### ISSUE TITLE
Aborted column move via beforeColumnMove still fires afterColumnMove

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5958]
### Description

With `manualColumnMove` enabled, if you abort a move by returning `false` from `beforeColumnMove` you still get an `afterColumnMove` event hook fired. This is not what I'd expect, and also not consistent with `beforeChange`/`afterChange` which skips the `afterChange` hook if the change was aborted by returning `false` from `beforeChange`.

### Steps to reproduce

1. Enable `manualColumnMove`
2. Add `beforeColumnMove` hook that ruturns false
3. Add `afterColumnMove` hook
4. Move a column -- the `afterColumnMove` hook fires

### Demo

https://jsfiddle.net/9p83mt5h/

### Your environment
* Handsontable version: 7.0.2
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Thank you for sharing the issue. You're right, the `afterColumnMove` hook runs, even when we block the action of column movement. According to the docs it should change only when there's a physical change

>Fired by ManualColumnMove plugin after changing order of the visual indexes.

**Comment by AMBudnik** [comment]
And another issue bites the dust :) Thank you for your constant help, Aaron.
