### ISSUE TITLE
use handsontable with an existing table

### ISSUE THREAD

**Issue by paladice** [handsontable/handsontable#596]
Hello,

do you know if I can use hansontable jquery plugin with a table which is already exists ?

Because in the documentation, I saw that we can create a table with handsontable like that :

    var data = [
      ["", "Kia", "Nissan", "Toyota", "Honda"],
      ["2008", 10, 11, 12, 13],
      ["2009", 20, 11, 14, 13],
      ["2010", 30, 15, 12, 13]
    ];

    var $container = $("#example1");
    $container.handsontable({
      data: data
    });

But I wish to do something like that :

    $("#monTableau").handsontable();

in order to give handsontable's feature to my table

Do you have an idea please ?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
