### ISSUE TITLE
ERROR TypeError: "changes is null" with afterChange hook.

### ISSUE THREAD

**Issue by NabeelAhmadK** [handsontable/handsontable#5965]
**Below is my hot-table.**
```
<hot-table [hotId]="id" [settings]="handsonSettings" [data]="dataset"
                [licenseKey]="handsonSettings.licenseKey"  [afterChange]="onAfterChange">
</hot-table>
```
....
</hot-table>

I am getting error:
  ERROR TypeError: "changes is null"
```
onAfterChange = (hotInstance, changes?:any) => {   
    let sourceRowArr = [];
    changes.forEach((row, index) => {
      this.changedRow.push(row[0]);
    });
```

**Environment:**
* Angular Version: 7.0
* Handsontable version: 7.0.0
* Browser Name and version: Chrome/Firefox
* Operating System: Linux (Ubunto 18)

**Comment by wojciechczerniak** [comment]
Demo is missing, but my guess is that on table initialization the `afterChange` callback is called with `null` because changes collection could be huge here, all data rows are loaded then. You can change `source` argument to check if `afterChange` origin is `loadData` and ignore it.

**Comment by NabeelAhmadK** [comment]
Thanks. The issue is resolved .. I was missing something. 
Thank you.
