### ISSUE TITLE
this combination of settings makes it impossible to modify cell data

### ISSUE THREAD

**Issue by Reidwork** [handsontable/handsontable#5967]
### Description
I tried to set the columnSummary and the columnSorting. Then I found I couldn't modify cell data.

### Steps to reproduce
Set both columnSummary and columnSorting on the same table, then try to modify cell data.

### Demo

https://jsfiddle.net/thbx47yv/

### Your environment
* Handsontable version: 7.0.3
* Browser Name and version: Chrome 73.0.3683.103 
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Hey @Reidwork 

we haven't prepared the `columnSummary` to support column sorting operations. Currently, the summaries are also treated as a part of the dataset. [Here are two issues that already covered this subject](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Summary+calculations%22+label%3A%22Column+sorting%22) so please track changes to them for fresh news.
