### ISSUE TITLE
the data was inserted with some empty rows

### ISSUE THREAD

**Issue by duanyijie** [handsontable/handsontable#5968]
### Description
![20190417_155902](https://user-images.githubusercontent.com/16126552/56270980-fbf1ec00-6129-11e9-89a5-fbf729fbc3a3.gif)

### Steps to reproduce
1. click loadData button

two empty rows would be inserted into data cause minSpareRows is 2 and filters is true

![image](https://user-images.githubusercontent.com/16126552/56269953-9866bf00-6127-11e9-88a5-0ad9733fa1e9.png)
by the way, the boder is not aligned after i clicked reset button

### Demo
https://codepen.io/duanyijie/pen/BEYNNw

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @duanyijie 

this issue has been already reported here https://github.com/handsontable/handsontable/issues/5707 but it is a bit more complicated. You can still have the `filters` enabled if you load more data at the beginning https://codepen.io/anon/pen/rbJVyE?editors=0010

**Comment by AMBudnik** [comment]
Hi @duanyijie 

We just fixed an issue related to yours. Please update to 8.0.0-beta1 and check if it solved for you as well.

Below are the resources

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```

And this is how you can download the beta from NPM

`npm i handsontable@beta`

**Comment by AMBudnik** [comment]
Hi @duanyijie 

the referenced issue has just been closed as fixed https://github.com/handsontable/handsontable/issues/5968 for v 8.0.0
