### ISSUE TITLE
Paste multiline cells from googlesheet lost CRLF

### ISSUE THREAD

**Issue by leaderpol** [handsontable/handsontable#5970]
### Description
Past cells with multiline from googlesheet to hansontable lost CRLF

### Steps to reproduce
1. Open a google sheet
2. Set a cell with
"a
b
c
d"
3. copy and paste it to hansontable you will have
"a
bcd"

The bug is line 81212
cell.innerHTML = cell.innerHTML.trim().replace(/<br(.|)>(\n?)/, '\n');

have to be
cell.innerHTML = cell.innerHTML.trim().replace(/<br(.|)>(\n?)/**g**, '\n');

Regards ;)

**Comment by AMBudnik** [comment]
Good day,

here's Aleksandra. We've exchanged emails. Thank you for sharing this issue. We'll check if with #5684

**Comment by AMBudnik** [comment]
Hey @leaderpol 

we've released `7.1.0` with https://github.com/handsontable/handsontable/issues/5684 and this issue seem to be fixed.

![image](https://user-images.githubusercontent.com/10757813/59331678-cebe5600-8cf4-11e9-8e57-6dc609db3f78.png)

I'm closing this topic. But if, for any reason, this does not work on your end please let me know.
