### ISSUE TITLE
drag and drop cells

### ISSUE THREAD

**Issue by dmitry-saritasa** [handsontable/handsontable#5973]
Is it possible to have a drag and drop on cells? For example I have an empty cell A2, can I drop a value from A1 in it? I.e. A1 becomes empty and A2 has now value from A1?

I understand I can do copy/paste/delete A1, but I'm looking for selection one or many cells and dropping them in a new position.

**Comment by wojciechczerniak** [comment]
Handsontable doesn't have this functionality yet. Maybe you can use `afterOnCellMouseDown` to check which cell was dragged and `afterOnCellMouseUp` to check where it was dropped? Ten clear first one and set data for the second. You probably need to handle the UI and conflict with selection or turn it off, depends on the UX you want to achieve.
