### ISSUE TITLE
vue use handsontable merge cells flicker and disintegration

### ISSUE THREAD

**Issue by bibi941** [handsontable/handsontable#5974]
### Description
i am use the getPlugin('mergeCells'),when i merge the cells and then click side cell.The cell will  flicker and disintegration.

### Steps to reproduce

![QQ20190418-115726 2.gif](https://i.loli.net/2019/04/18/5cb7f64dec504.gif)
1.
2.
3.

### Your environment
* Handsontable version:Handsontable 7.0.0 Handsontable/vue 4.0.0
* Browser Name and version:chrome 73
* Operating System:macos 10.14.4

**Comment by AMBudnik** [comment]
Hey @bibi941 

please send over a demo that you're using.

**Comment by AMBudnik** [comment]
Hey @bibi941 

do you have any updates here? A demo would definitely help a lot.

**Comment by AMBudnik** [comment]
I guess that this is no longer an issue as there is no response.
