### ISSUE TITLE
cells hook triggered many times，never ending

### ISSUE THREAD

**Issue by hutiantian04** [handsontable/handsontable#5975]
### Description
Hi AMBudnik
handsontable for angular
After the cell drops down to select the data，cells will trigger  many times， never ending. But I only want once. Demo can't appear this problem.
### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version:7.0.2
* Browser Name and version:Google Chrome version: 73.0.3683.86
* Operating System:win10

**Comment by hutiantian04** [comment]
Hi AMBudnik
Sorry to bother you, I already know the reason. afterChange need to judge source[0][2] !== source[0][3],then cells will stop.

**Comment by AMBudnik** [comment]
That's OK :) If you'd need anything let me know. 
ps. you can also send a message at support@handsontable.com
