### ISSUE TITLE
Request: header renderer

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5977]
### Description

Originally posted on the forum: https://forum.handsontable.com/t/how-to-style-specific-column-headers/3064

I want to style specific column headers, basically setting different backgrounds, borders, and icons. It does not follow a predictable order so I cannot do this with CSS `nth-child` and such. I have to do it based on the columns I have. The current methods I'm aware of to customize the headers are a bit limited:

1. I can use HTML in the `colHeaders` array, but this is limited to just the inner label of the header, I can't manipulate the TH itself to set a CSS className, background or border, for example.

2. I can use `afterGetColHeader` to manipulate the TH element (which is what I've done so far) but it is pretty cumbersome and lacking, for example it only gives you the visual column index, but with `nestedHeaders` it doesn't tell you which level the header is. 

### Request

1. Ability to set a column header class name on a column, say `column.headerClassName`. Probably would be "right" to also allow overriding the other header classnames like `activeHeaderClassName` on a per column basis.
2. Ability to set a column header renderer, say `column.headerRenderer`, with signature like `(instance, TH, col, row, colHeader, columnProperties) => TH` where `colHeader` is the value passed to `colHeaders` or `nestedHeaders` for that specific TH, and `columnProperties` is the `ColumnSettings` for the column associated with that header.
3. Add `row` or `headerLevel` to `afterGetColHeader`.

**Comment by AMBudnik** [comment]
Thank you for moving the topic.

**Comment by aaronbeall** [comment]
Addition part to this could be:
4. Add `beforeHeaderRenderer` and `afterHeaderRenderer` hooks to manipulate the TH element. (Maybe this is easier than having a `column.headerRenderer` property? I was poking around the code and couldn't find the header rendering implementation.)

**Comment by AMBudnik** [comment]
Sure. Sounds like a natural process to add the hooks while exposing a header renderer.

**Comment by talamaska** [comment]
seems like something I would need as well in order to put custom tooltips in the header in angular I need a renderer like for the cell in order to resolve and inject an angular component

**Comment by shallwefootball** [comment]
how about this https://handsontable.com/docs/7.1.0/demo-custom-renderers.html#page-header

**Comment by aaronbeall** [comment]
@shallwefootball That's a good example of how to use HTML in the header label (option 1 in the original post above) but doesn't let you customize the TH itself, for example set a background or border.

**Comment by talamaska** [comment]
@shallwefootball I saw this example, but i don't like this global event listener on the table. The header cell already has event listeners hooks afterOnCellMouseDown etc. The thing is that its not propagating the events to the inner components. This special logic with event listeners is not natural in angular. The custom renders for crlls that are not headers act as expected.

**Comment by jacktang** [comment]
I want to add svg icons or font-awesome icons into row header, do you have some examples?

**Comment by AMBudnik** [comment]
Hey @jacktang 

here's an example https://jsfiddle.net/AMBudnik/1ez4gpuw/ (if you're using sorting you'd need to add some extra logic)

**Comment by ChandraAdapa10** [comment]
Hi Ambudnik,

I would like to add custom icon for each cell based on custom context menu item click, I have tried to do that and it is not working .

could you please assist me with an demo for angular.

Thanks

**Comment by AMBudnik** [comment]
Hi @ChandraAdapa10 can you share with me a draft of the option via support@handsontable.com?

**Comment by eribean** [comment]
Any news on this? This would help me out too?

**Comment by AMBudnik** [comment]
Hi @eribean
 
This task hasn't been added to the sprint yet.

Here's our current workflow for the next version https://github.com/handsontable/handsontable/projects/3

**Comment by AMBudnik** [comment]
Thank you again for sharing this idea!

I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
