### ISSUE TITLE
 the handsontable header merge rows

### ISSUE THREAD

**Issue by hutiantian04** [handsontable/handsontable#5982]
### Description
How does the handsontable header merge rows？

### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version:7.0.1
* Browser Name and version:Google Chrome version: 73.0.3683.86
* Operating System:win10

**Comment by AMBudnik** [comment]
Hey @hutiantian04 

what do you mean? Would you like to merge the rows of headers like in the [nestedHeaders functionality](https://handsontable.com/docs/7.0.2/demo-nested-headers.html)?

**Comment by hutiantian04** [comment]
Hi AMBudnik
Yes,  I would like to merge the rows of headers like in the nestedHeaders functionality.

**Comment by AMBudnik** [comment]
Currently, there is only a way to merge the columns `colspan'`. Here's the topic to follow https://github.com/handsontable/handsontable/issues/191 to get the latest news about the `rowspan`. Once we add this functionality on our to-do list the issue is opened and receives a milestone.

**Comment by hutiantian04** [comment]
Hi AMBudnik
I know，thank you！

**Comment by deepthan** [comment]
I have implemented rowspan, which can be set in the same way as' nestedHeaders' and 'colspan', if you need it, please contact me at Github.
for example
```
nestedHeaders:  [
  [ { label: 'c', rowspan: 3}, { label: 'B', colspan: 9 }],
  ['', { label: 'E', colspan: 4 }, { label: 'F', colspan: 4 },  { label: 'G', rowspan: 3}],
  ['', { label: 'I', colspan: 2 }, { label: 'J', colspan: 2,  rowspan: 2 }, { label: 'K', colspan: 2 }, { label: 'L', colspan: 2 }, ''],
  ['N', { label: '2', colspan: 1 }, 'P', '', '', 'S', 'T', 'U', '22', '']
];

```

To render
![37818273a1cfa70243ff246937a0d9f](https://user-images.githubusercontent.com/22695767/158949613-993eae5d-83e6-497e-bd5e-40a05fde52ca.png)

**Comment by robsonbarretoefeso** [comment]
Hello,

I thought the solution for merging lines in the header handontable was cool.

You can share ?

**Comment by franck-lynn** [comment]
```
export function handleAfterGetColHeader(
  col: number, //
  th: HTMLTableCellElement,
  headerLevel: number,
  colHeaders: (string | number)[]
) {
  nextTick(() => {
 

    if (headerLevel === 0 && !th.getAttribute('colSpan')) {
      th.rowSpan = 2 
      th.style.borderBottom = 'none'
      th.style.verticalAlign = 'middle'
    }

 
    if (headerLevel === 1 && !colHeaders[col]) {
 
      th.className = 'hidden'
      // th.classList.add('hidden-row')
    }
  })
}
```
The nextTick() function is vue .

in parent component, I got a  hot instance, 
and 
hot.addHook('AfterGetColHeader', handleAfterGetColHeader)

it works by rowspan

but problem is  when I refresh browser, it will be twinkle

**Comment by adrianszymanski89** [comment]
Hi @franck-lynn 

Thank you for your input. I tried to use your solution in a minified example, but I'm getting errors because of the second conditional statement in your code. Can you please modify it to show us how it should look?

https://jsfiddle.net/handsoncode/z6t8xv7h/

**Comment by franck-lynn** [comment]
@adrianszymanski89 
Sorry, I can't load the jsfuddle.net, 

```
<script setup lang="ts">
import { ref, onMounted, DefineComponent, nextTick } from 'vue'
// import Handsontable from 'handsontable'
import Core from 'handsontable/core'
import { GridSettings } from 'handsontable/settings'
import { HotTableProps, VueProps } from '@handsontable/vue3/types'
import { HotTable } from '@handsontable/vue3'
// import { Settings as NestedHeadersSettings } from 'handsontable/plugins/nestedHeaders'
import 'handsontable/dist/handsontable.full.css'
import { AppDict } from '@/constants'

import { registerAllModules } from 'handsontable/registry'
registerAllModules()

const hotRef = ref<DefineComponent<VueProps<HotTableProps>>>()
const instance = ref<Core>()

const data = [
  { itemNo: 1, catalog_number: 'AAAA', qty: 2, price: 10, amount: '=PRODUCT(C1, D1)', remark: 'remark something' },
  { itemNo: 2, catalog_number: 'BBBB', qty: 3, price: 20, amount: '=PRODUCT(C2, D2)' },
  { itemNo: 3, catalog_number: 'CCCC', qty: 4, price: 30, amount: '=PRODUCT(C3, D3)' },
]

const hotSettings: GridSettings = {
  dataSchema: { itemNo: null, catalog_number: null, qty: null, price: null, amount: null, remark: null },
  nestedHeaders: [
    ['item_no', 'catalog_number', 'qty', { label: 'untaxed  price ', colspan: 2 }, 'remark'], //
    ['', '', '', 'unit price', 'amount', ''],
  ],

  height: 300,
  columns: [
    { data: 'itemNo' },
    { data: 'catalog_number' },
    { data: 'qty' },
    { data: 'price' },
    { data: 'amount' },
    { data: 'remark' },
  ],

  stretchH: 'all',
  manualColumnResize: true,
}

onMounted(() => {
  instance.value = hotRef.value!['hotInstance']
  const hot = instance.value
  if (!hot) return

  // hot.getColHeader() cache colHeader data, only get second row ?  
  const colHeaders = hot.getColHeader()
  hot.addHook('afterGetColHeader', (col: number, th: HTMLTableCellElement, headerLevel: number) => {
    afterGetColHeader(col, th, headerLevel, colHeaders)
  })
})

function afterGetColHeader(
  col: number, // col index
  th: HTMLTableCellElement,
  headerLevel: number,
  colHeaders: (string | number)[]
) {
  nextTick(() => {
    if (headerLevel === 0 && !th.getAttribute('colSpan')) {
      th.rowSpan = 2
      th.style.borderBottom = 'none'
      th.style.verticalAlign = 'middle'
    }
    if (headerLevel === 1 && !colHeaders[col]) {
      th.className = 'hidden'
    }
  })
}
//
</script>
<template>
  <div class="w-full m-2 z-10">
    <hot-table ref="hotRef" :data="data" :settings="hotSettings" :license-key="AppDict.hotKey" />
  </div>
</template>

```
AppDict.hotKey = 'non-commercial-and-evaluation'

The problem:
browse refreshed  can't redraw view, when I resize browse , it works.

**Comment by franck-lynn** [comment]
hot.getColHeader()    only get the second row data,

**Comment by franck-lynn** [comment]
```
onMounted(() => {
  instance.value = hotRef.value!['hotInstance']
  const hot = instance.value
  if (!hot) return

  // hot.getColHeader() cache colHeader data, only get second row ?  
  const colHeaders = hot.getColHeader()
  hot.addHook('afterGetColHeader', (col: number, th: HTMLTableCellElement, headerLevel: number) => {
    afterGetColHeader(col, th, headerLevel, colHeaders)
  })

 // add this would resolve browse redraw , it would fire afterGetColHeader hook.
 document.documentElement.style.transform = 'scale(1.005)'
  setTimeout(() => {
    document.documentElement.style.transform = 'scale(1.0)'
  }, 200)


})
```

**Comment by adrianszymanski89** [comment]
Hi @franck-lynn 

Thank you for your code. I'll try to minify it and then post it here as a proposed solution in a code demo.

**Comment by adrianszymanski89** [comment]
@franck-lynn 

I managed to simplify your solution, and now I get no errors, but even though the column headers are merged in some areas, the selection isn't working correctly. Can you please confirm if that's also your output?

https://jsfiddle.net/handsoncode/u5ghd03m/

**Comment by franck-lynn** [comment]
> @franck-lynn
> 
> 我设法简化了您的解决方案，现在我没有收到任何错误，但是即使列标题在某些区域中合并，选择也无法正常工作。你能确认这是否也是你的输出吗？
> 
> https://jsfiddle.net/handsoncode/u5ghd03m/

I can't  access this websit  'https://jsfiddle.net/handsoncode/u5ghd03m/'
sorry sir.

**Comment by adrianszymanski89** [comment]
@franck-lynn 

Thank you for the updated example, but it seems that it's not building correctly. Can you please check on your side?

**Comment by franck-lynn** [comment]
@AMBudnik  O, I'm sorry.  I delete default css, It looks well.
I found getColHeader() only get last row data in nestHeaders.
```
const colHeaders = hot.getColHeader();
``` 
for example: 
```
export const nestedHeaders = [
  // colspan mustbe first

  ["ItemNo", { label: "price with tax", colspan: 2 }, "remark"],
  ["", "price", "amount", ""],
];
```
only get : 
colHeaders  =  ["", "price", "amount", ""]

**Comment by AMBudnik** [comment]
Hi @franck-lynn 

yes, the `getColHeader()` at the moment gets the `colHeaders` values. Here https://github.com/handsontable/handsontable/issues/4392 you can track the `feature` to alter this behavior.

Till that happens you can use the array of arrays to parse the data and get the details about the headers. Here's an example https://jsfiddle.net/b1e7q654/
