### ISSUE TITLE
The difference between handsontable.full.js and handsontable.js

### ISSUE THREAD

**Issue by jerrold1108cn** [handsontable/handsontable#5986]
The difference between handsontable.full.js and handsontable.js

**Comment by AMBudnik** [comment]
Hey @jerrold1108cn 

`Handsontable.full.js` loads all the dependencies and `handsontable.js` doesn't.

I recommend this article https://handsontable.com/blog/articles/2017/1/how-to-build-a-custom-version-of-handsontable. It pretty old as it reminds the CE and PRO version, but it has this plugin-dependency table that will help you understand how we manage the dependencies.
