### ISSUE TITLE
custom editor can't obtain focus and select content of editor in mergeCells

### ISSUE THREAD

**Issue by cheery550** [handsontable/handsontable#5987]
I define a custom editor,like this:
```
<div style="position: absolut;" contenteditable="true">
    <p> value </p>
</div>
```

when I dblclick an mergecells, the editor can't obtain focus and can't select the content of editor

**Comment by AMBudnik** [comment]
Hi @cheery550 

maybe this example would help https://jsfiddle.net/handsoncode/xzvtdyu8/

It uses a password custom editor. For the merged cells it works the same way as it works for the rest.

**Comment by cheery550** [comment]
@AMBudnik , Thanks for your answered, 
I don't know why https://jsfiddle.net/handsoncode/xzvtdyu8/ can't be opened.

Due to password costom editor is an "<texture></texture>", it can obtain focus forcedly. 
editor like:
```
<div style="position: absolut;" contenteditable="true">
    value
</div>
```
 can work well in mergedCells and single cell.

editor like:
```
<div style="position: absolut;" contenteditable="true">
    <p> value </p>
</div>
```
can't work well in mergedCells, but works well in single cell.
I wonder whether handsontable does some thing to stop click or select event in mergedCells only.

**Comment by AMBudnik** [comment]
Hey @cheery550 

it looks like there has to be an `INPUT` or `TEXTAREA`. `DIV` is not accepted even if it's `contenteditable`.
