### ISSUE TITLE
Filter checkbox

### ISSUE THREAD

**Issue by LayerDevTeam** [handsontable/handsontable#5988]
### Description

When filtering checkbox columns, our customers are selecting ‘Is Empty’ and think the filter is broken. They don’t realise that they should select ‘Is Equal To’ then type ‘True’.
### Steps to reproduce

1. Filter a checkbox column
2. Filter by condition
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/1

### Your environment
* Handsontable version: na
* Browser Name and version: na
* Operating System: na

**Comment by AMBudnik** [comment]
Hey @LayerDevTeam 

if you found filter names misleading I can propose a custom name selection. 

You can change the names via [internationalization](https://handsontable.com/docs/7.0.2/tutorial-internationalization.html). The tutorial tells us about the languages, cause it is its main purpose. However, the key to a change is replacing the strings. You can type there anything you find more convenient.
