### ISSUE TITLE
Manually add new row or column

### ISSUE THREAD

**Issue by tony6636** [handsontable/handsontable#599]
Hi, I want to manually add a new row/column. I know that that feature is built-in via mouse right button click, but it seems that plugin has the protection of manual data sheet grow

```
function addColumn(sheetData) {
    sheetData[0].push('');

    for (var i = 1; i < sheetData.length; i++) {
        sheetData[i].push('');
    }

    return sheetData;
}

function addColumn() {        
    $("#sheet").handsontable("loadData", addColumn($("#sheet").handsontable("getData")));

}
```

**Comment by remmel** [comment]
the minSpareCols functionality doesn't seem to work when using the columns attribute

var hot2 = new Handsontable(container2, {
            data: getCarData(),
            columns: [
                {
                    type: 'text'
                },
                 {
                    type: 'text'
                }
            ],
            minSpareCols: 1,
            minSpareRows: 1
        });

**Comment by AMBudnik** [comment]
Hi @remmel 
You a re right the `minSpareCols` do not work after you define `columns`. Currently it's intended and marked as a feature: https://github.com/handsontable/handsontable/issues/2440

If you would like to have the one empty column all the time you should:
1) add one empty column at the beggining
2) trigger the `updateSettings` via `afterChange` hook to update the `columns` option. 

Suggested approach: http://jsfiddle.net/6fzzfcsy/
