### ISSUE TITLE
cannot read property "removeeventlistener" of undefined - reat HotTable component

### ISSUE THREAD

**Issue by faycelbouamoud** [handsontable/handsontable#5991]
### Description
*Sometimes* whene I want to reload the handsontable with different data and settings, it fires this exception "removeEventListener" of undefined

![image](https://user-images.githubusercontent.com/32583333/56886768-05efe500-6a70-11e9-9b15-9812f208f40f.png)

### Steps to reproduce
1. Load the grid with settings and cells with click event listener
2. trying to reload the grid with different setup
3. Fires exception "removeEventListener" of undefined

### Your environment
* Handsontable version: 7.0.2
* Browser Name and version: Chrome
* Operating System: WIN10

**Comment by faycelbouamoud** [comment]
![image](https://user-images.githubusercontent.com/32583333/56886744-f8d2f600-6a6f-11e9-8c23-580113c514a1.png)

**Comment by AMBudnik** [comment]
Hey

What do you mean by saying

> trying to reload the grid with different setup

Can you send over a demo or record the behavior?

**Comment by faycelbouamoud** [comment]
sorry I don't have a demo right now. 😞 
the problem is : for example, whene I try to reload the grid with different (styles, rendering, merging etc.) based on my data and a structure to redesign the grid.
**sometimes** whene I change from a grid to another this error occured. and I think it happened whene I added a ClickEventListener on TD element whene rendering the TD element.

**Comment by AMBudnik** [comment]
I am sorry, but this sounds like a custom case and I need to reproduce the behavior to help. Without a demo this is impossible.

I'm closing the issue but once you'll prepare any demo we'll reopen it and discuss it together.

**Comment by epernice** [comment]
I'm running into this as well... For me it's happening when I call setDataAtCell (but only in certain circumstances that I'm trying to narrow down). I was only able to get around it by modifying handsontable code so that the unObserve function has an if guard around element.removeEventListener (so that it doesn't try to call that method if element is undefined). I'm working on trying to reproduce in a minimal case.

**Comment by epernice** [comment]
Ok, I have a fiddle that reproduces the issue:
https://jsfiddle.net/yb24t3zh/1/

**Comment by AMBudnik** [comment]
I have replicated the issue. Thank you for sharing the demo @epernice

**Comment by AMBudnik** [comment]
Hey @epernice 

The bug you're experiencing is the same as this one https://github.com/handsontable/handsontable/issues/6214
If I use `7.1.0.` in your project it works well.

Please track changes to https://github.com/handsontable/handsontable/issues/6214
