### ISSUE TITLE
Unable to load data asynchronously on Nuxt.js

### ISSUE THREAD

**Issue by schantanu** [handsontable/handsontable#5993]
### Description
1. Nuxtjs template not loading data using the [asyncdata](https://axios.nuxtjs.org/usage) method
2. HTTP GET method takes more than one click to load data

### Steps to reproduce

1. Configured `nuxt.config.js` to changes as per the overall mentions at https://github.com/handsontable/vue-handsontable-official/issues/70 
2. Recreated project on Codesandbox
https://codesandbox.io/s/zwz2qnx40p

### Demo
https://zwz2qnx40p.sse.codesandbox.io/table

### Your environment
* Handsontable version: 7.0.2

**Comment by wojciechczerniak** [comment]
You've got object data without defining `columns` so it tries to guess columns. But i cannot do that on initialization because `data` array is empty. Use array of arrays or define `columns` and everything should be ok. https://24889nmlrn.sse.codesandbox.io/table
