### ISSUE TITLE
ViewportRowRenderingOffset / RenderAllRows creates extra space at bottom of table

### ISSUE THREAD

**Issue by veeru1087** [handsontable/handsontable#5994]
### Description
When we use ViewportRowRenderingOffset to total number of rows, or use RenderAllRows: true, The table is loading the all rows at once. However when we scroll to bottom of the table it is creating extra space at the end. 

### Steps to reproduce

1. Set ViewportRowRenderingOffset: <total rows> Or set RenderAllRows: true
2. Scroll to end of the table
3. See the empty space at the end of scrolling

### Demo
https://jsfiddle.net/mo9yen7c/

### Your environment
* Handsontable version: 6.2.0
* Browser Name and version: Chrome 74.0
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Can you record it, please?

It does not seem to load any excess space on my device. I'm using Chrome 73 on Windows 10.

**Comment by veeru1087** [comment]
@AMBudnik Thanks for responding! It is crazy - I am unable to reproduce it either in the same JS fiddle link. I played with different versions but could not reproduce. Could you give me some time so I will try to come back with a JS Fiddle to reproduce this.

**Comment by AMBudnik** [comment]
Sure, please take your time. I will close the ticket as it does not address anything that we can fix now, but as soon as I get any update here I'll reopen the topic.
