### ISSUE TITLE
Options colWidths setting column width is invalid

### ISSUE THREAD

**Issue by hutiantian04** [handsontable/handsontable#5998]
### Description
Options colWidths setting column width is invalid

### Steps to reproduce

1.
![colwidth](https://user-images.githubusercontent.com/39802580/57350174-97a5d380-718f-11e9-92d9-535310dbd674.png)

2.
3.

### Demo

http://jsrun.net/TSXKp/edit

### Your environment
* Handsontable version:7.0.2
* Browser Name and version:Google Chrome version: 73.0.3683.86
* Operating System:win10

**Comment by talamaska** [comment]
Have you tried using the a function?
```
colWidths: function(index) {
  return index * 10;
},
```

**Comment by hutiantian04** [comment]
![image](https://user-images.githubusercontent.com/39802580/57591398-b75c4380-7563-11e9-85b4-0c113f7a3951.png)
I found the cause of the problem, but I don't know how to solve it.
【width】is the width I set，when only width > cachedWidth，use the width I set. But I always wanted to use 【width】, not 【cachedWidth】，how to solve it?

**Comment by hutiantian04** [comment]
> Have you tried using the function style?
> 
> ```
> colWidths: function(index) {
>   return index * 10;
> },
> ```

I've tried it,

**Comment by AMBudnik** [comment]
This is a bug, with those settings we should be able to set `colHeaders` to `100` when the header name is long but it doesn't work for `nestedHeaders`.

**Comment by hutiantian04** [comment]
Hi AMBudnik 
This problem has been solved.The solution is as follows：
.handsontable th {
  width: 5px;
}
