### ISSUE TITLE
handsontable 7.0.2 context menu issue with multiple selected rows in case of 1st column hidden

### ISSUE THREAD

**Issue by vk-sourcefuse** [handsontable/handsontable#5999]
### Description
handsontable 7.0.2 context menu issue on multiple seected rows in case of 1st column hidden

### Steps to reproduce

Please check this video: https://drive.google.com/file/d/1RrwYNBb6-9NwKg5s6vdJcTILflsHwe38/view

### Demo

http://jsfiddle.net/1n8fdmt7/

### Your environment
* Handsontable version: 7.0.2
* Browser Name and version: In all browsers
* Operating System: In all OS

**Comment by AMBudnik** [comment]
Thank you for sharing the video. I have replicated the issue.
You're right - only the first column is an issue here.

I cannot see any correlation to previous versions.

**Comment by vk-sourcefuse** [comment]
Hey @AMBudnik , is there any workaround for this ?

**Comment by AMBudnik** [comment]
Does this http://jsfiddle.net/pgdemw2L/ work in your example?

**Comment by AMBudnik** [comment]
Works the same in v 8.0.0-beta1 http://jsfiddle.net/AMBudnik/fm7vaecs/

**Result**
![Zrzut ekranu 2020-04-16 o 14 08 44](https://user-images.githubusercontent.com/10757813/79454596-cd804880-7feb-11ea-9bfa-a706d4f94f62.png)

**Expected result** (row headers selected)
![aa](https://user-images.githubusercontent.com/10757813/79454838-310a7600-7fec-11ea-9557-f1449dade991.png)

**Comment by AMBudnik** [comment]
Issue **solved** in 8.0.0-beta2-rev14 http://jsfiddle.net/AMBudnik/ndtv5hxf/

![Zrzut ekranu 2020-06-16 o 11 20 37](https://user-images.githubusercontent.com/10757813/84756705-6f5beb80-afc3-11ea-964a-95cda065873a.png)

**Comment by AMBudnik** [comment]
Hi @vk-sourcefuse 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

**Comment by vk-sourcefuse** [comment]
Great !! Thanks !!, I'll check in beta2 but as the software is live so I will wait for main release, can't take risk of using beta version in production :)

**Comment by AMBudnik** [comment]
@vk-sourcefuse I will update you once the stable 8.0.0 is ready :)

**Comment by AMBudnik** [comment]
Hi @vk-sourcefuse the day has come! We've released Handsobtable v 8.0.0

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js

NPM npm i handsontable

Release Notes https://github.com/handsontable/handsontable/releases

**Comment by vk-sourcefuse** [comment]
Great.. good to know.. I can see in release notes that too many other issues has been resolved in this release. We'll plan to upgrade it in our project asap. Thanks
