### ISSUE TITLE
Custom tooltip for column header

### ISSUE THREAD

**Issue by ishan30** [handsontable/handsontable#6002]
Hi, We are trying to provide custom tooltip, i.e. text different than the column header text.

Let's say my column header is Age, but I want to show tooltip as "Calculation based on the birth-date" instead of default tooltip "Age" using colHeaders.

Is there any way to apply custom text in column header?

**Comment by AMBudnik** [comment]
You can use HTML `title` attribute inside the `colHeaders` or the `afterGetColHeader` hook.

**Comment by ishan30** [comment]
Hi, Can you please post any example with title inside the colHeaders?

**Comment by ishan30** [comment]
I've written something like :

 ` colHeaders: (col)  => {
        if (col === 6) {
          return '<div title="Calculation">Metric 1</div>';
        } else {
          return col.toString();
        }
      },`

It's not working.
I've also tried following:
` afterGetColHeader: (i,th) =>{
        
        if(Number(th)===6){
          console.log(i);
          th.innerHTML="temp text";
        }
      }
`

None of this working. With afterColHeader we're getting object of core and column index.
Please note we are using TypeScript. Appreciate if you provide more details.

**Comment by AMBudnik** [comment]
Here is for the `colHeaders` https://jsfiddle.net/handsoncode/30o24utx/ and the hook https://jsfiddle.net/handsoncode/yg589q7k/

**Comment by ishan30** [comment]
Thanks for sharing.
My mistake was I was also using `title` property under the `columns` section, so it was overriding the `colHeaders`.
