### ISSUE TITLE
Can I use handsontable in a react-native mobile app?

### ISSUE THREAD

**Issue by manoojm** [handsontable/handsontable#6007]
### Description
I could not find any documentation around using handsontable in a react-native app. I could however see that my react web app renders fine when accessed in a mobile. Would like to know if I can use the handsontable in my react-native app as well.

**Comment by AMBudnik** [comment]
Welcome @manoojm 

we haven't tested it before but if you're able to attach a DIV element and run an instance of Handsontable on it it should work.
The other case is the mobile support. We support only CRUD operations for those devices.
