### ISSUE TITLE
handsontable for Svelte 3

### ISSUE THREAD

**Issue by ansarizafar** [handsontable/handsontable#6008]
Is there any plan to provide handsontable svelte 3 component https://svelte.dev

**Comment by AMBudnik** [comment]
I do not see this on our Roadmap but I'm attaching the 'feature' label. We'll discuss the subject and check if it fits our company mission. We'd love to be compatible with all useful tools but sometimes it might be a challenge.

**Comment by tkolyak** [comment]
I have used [this](https://www.nielsvandermolen.com/external-javascript-sveltejs/) method, result is here:
https://svelte.dev/repl/a72e2b46e44e4ea18e98a8b0d6643000?version=3.16.7

**Comment by AMBudnik** [comment]
Thank you for your feedback.

I'm moving this topic to Github Discussions. I welcome everyone to discuss this subject and share your feedback. See you there!
