### ISSUE TITLE
Comments persisting in React Redux Example

### ISSUE THREAD

**Issue by cdesch** [handsontable/handsontable#6009]
### Description
Comments and validation disappear after redux store update. Should they persist in the redux store as well?

Based on the [React Redux Example](https://handsontable.com/docs/7.0.2/frameworks-wrapper-for-react-redux-example.html), why does the things like comments and validition disappear after changes to the table? I see that the `afterUpdate` hook is called back with `loadData` which clears the comments and validation since it is being loaded from redux store. `afterUpdate` is being called after the Redux Store is being updated from this function performing the dispatch:

    onBeforeHotChange(changes, source) {
      reduxStore.dispatch({
        type: 'updateData',
        dataChanges: changes
      });
      return false;
    }

Where do we keep comments and validation when using redux such that they are not lost with each table update?

Code Sample: https://jsfiddle.net/kickinespresso/mrbagcv0/14/

### Steps to reproduce

In the demo, add a comment using the context menu, then make a change to the table.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1207795/57528754-225a1000-7301-11e9-95ce-ed005c7a02f5.gif)

### Demo

https://jsfiddle.net/kickinespresso/mrbagcv0/14/

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: Chrome 74.0.3729.131
* Operating System: Mac OS 14.4.4

**Comment by AMBudnik** [comment]
Sorry to keep you waiting. Our developer is checking the redux store.

**Comment by AMBudnik** [comment]
Unfortunately, `loadData` every time you call `updateSettings` resets the `cellMeta` - https://handsontable.com/docs/7.0.3/Core.html#loadData.
User may cache `cellMeta`, but it's difficult to achieve.
