### ISSUE TITLE
Allow using fillHandle true/false on columns and cells

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6014]
### Description

Allow using `fillHandle `true/false on `columns` and `cells`. Currently, you can set it up only on an instance level.

https://jsfiddle.net/handsoncode/k1yzef7u/

### Your environment
* Handsontable version: 7.0.3
* Browser Name and version: Chrome 74
* Operating System: Windows 10

inform [forum](https://forum.handsontable.com/t/how-do-i-disable-the-drag-copy-for-cells/3240)

**Comment by MelodicCrypter** [comment]
Hi guys, any update on this one?

**Comment by AMBudnik** [comment]
This functionality hasn't been added yet @MelodicCrypter But you have an option to block the autofill action in the `beforeChange` hook. That's a solid workaround before introducing the official support for fillHandle per row/column.

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
