### ISSUE TITLE
request: indication that autocomplete strict mode is selecting a value

### ISSUE THREAD

**Issue by davestewart** [handsontable/handsontable#6016]
### Description

In autocomplete `strict` mode, the `source` property is used to determine validity.

When `source` is a function – say an AJAX call – the function is called multiple times. This makes sense for typing to get suggestions, but when **selecting** a suggestion, there is no way for the function to know that this is a selection, not a request:

```
Action      Typing      Action          Response

Typing      A           Call server     Aardvark, Ambulance, Anteater
Typing      AN          Call server     Anteater
Selection   Anteater    Call server     Anteater
```

If (as I am) the developer is caching responses to typed entries, we can use the cached data to speed up the display of choices.

However, because a **selection** is effectively the same as saying "give me this option you have already fetched" if we had a way to differentiate between a request and a selection, we could skip this final server request:

```
source (query, process, isPicking) {
  if (!isPicking) {
    return store.fetch().then(process)
  }
  else {
    process(store.getSelection(query))
  }
}
``` 

Only a small tweak, but it gives devs the opportunity to handle this more intelligently.

### Demo

- https://jsfiddle.net/davestewart/mjof5ysn/19/

### Your environment
* Handsontable version: 7.02
* Browser Name and version: Chrome
* Operating System: OSX

**Comment by AMBudnik** [comment]
Hey @davestewart 

Once a user selects an option it performs a click event of the element with a `listbox` className. Not sure if that's going to help to remove unnecessary calls but I guess that it answers your question.

**Comment by davestewart** [comment]
Hey @AMBudnik 

> I guess that it answers your question

I don't think that makes it any clearer!? Did I miss something.

Here's an updated version; I've grabbed the editor state. My guess is that `STATE_WAITING` means it's closing, so I used that in place of the suggested `isPicked` parameter, and it seems to work:

https://jsfiddle.net/davestewart/mjof5ysn/28/

Does that make it any clearer?

**Comment by AMBudnik** [comment]
Yea.. I misunderstood the case. Sorry for the fuss.

**Comment by davestewart** [comment]
No worries :)

What do you think of the proposal as it stands?

**Comment by AMBudnik** [comment]
To be honest you did great research and I (as a Support Manager) couldn't even go that far without help from developers.

> PS. I realise I'm probably bombarding you with a lot of questions / ideas / proposals at the moment!

that's good :) I may need some time to answer all of them. Some parts of the code are as old as the library itself so it's great that someone wants to take out all of the rusty mechanisms and question if those are correct.
