### ISSUE TITLE
Restore changed cell selection on undo/redo

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6017]
### Description
Restore changed cell selection on undo/redo.

Like spreadsheet does:
![gsheet](https://user-images.githubusercontent.com/4718998/57761996-f1ae1800-76fe-11e9-8f2f-78310fdf22f9.gif)

### Steps to reproduce

1. Change cell A1
2. Change cell B3
3. Select cell D1
4. Undo
5. Undo
6. Data is changed back, but selection stays as D1

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 7.0.3
* Browser Name and version: Firefox
* Operating System: OS X

**Comment by AMBudnik** [comment]
Fixed in v 7.1.0
