### ISSUE TITLE
Scrolling Issue for tables with fixed heights

### ISSUE THREAD

**Issue by ghowlettgomez** [handsontable/handsontable#6018]
### Description

Suppose that the handsontable exists within a vertically scrollable container. If the table has a set height and the table exceeds that height, then one can scroll within the table without scrolling in the broader container. If the table is not as large as its set height, then one would scroll in the larger container instead of the table. When one puts their mouse over the headers when the table is not larger than its height and tries to scroll, no scrolling happens. The behavior should be similar to what happens when the mouse is put over the data; the larger container scrolls.
### Steps to reproduce

1. Locate handsontable in a larger container that is vertically scrollable. 
2. Put mouse over the headers.
3. Attempt to scroll  #vertically with mouse.

### Demo

https://jsfiddle.net/zhm4o6uj/

### Your environment
* Handsontable version: Occurs in handsontable 6.2.3 and latest.
* Browser Name and version: Version 74.0.3729.131 (Official Build) (64-bit)
* Operating System: Ubuntu 18.04.2 LTS

**Comment by AMBudnik** [comment]
Hey @ghowlettgomez 

On Windows 10/ Chrome 74 I'm able to scroll when hovering a header even when I change the structure

```html
<div id="wrapper">
  <div id="container"></div>
  <div style="height: 300px; width: 100;"></div>
  <div style="height: 20px; width: 100;"></div>
</div>
```

to
```html
<div id="container"></div>
```

ps. maybe you mean `horizontal scrolling`? You have 10 rows that are fully visible in the example so it is not possible to scroll vertical.

**Comment by ghowlettgomez** [comment]
My apologies, I was imprecise with how I phrased the issue. There are only 10 rows so there is no vertical scrolling on the table. The issue is that while there is no vertical scrolling on the table, there should be scrolling on the rest of the page. When the mouse is over a cell, one can scroll up and down the page. When the mouse is over the header, one cannot vertically scroll up and down the page.

**Comment by AMBudnik** [comment]
I'm not an Angular expert but from a conversation with our programmer we came out to a conclusion that it can be an Angular issue. Especially when `ChangeDetectionStrategy` doesn't do you any favors.

**Comment by AMBudnik** [comment]
Thank you for sharing additional results. This issue seems like this one https://github.com/handsontable/handsontable/issues/5212
Can you confirm?

**Comment by ghowlettgomez** [comment]
I can confirm. While using chrome the issue is limited to when the mouse is above the headers, when I am using Firefox 66.0.5 (64-bit) I cannot scroll when I have my mouse over any part of the table.

**Comment by AMBudnik** [comment]
Thank you for confirmation. I think that we can close this issue as everything we need is in 5212. But if we're missing something there please add a comment.
