### ISSUE TITLE
How to set a default value in a column dropdown when is added a new line? 

### ISSUE THREAD

**Issue by jamesandrade7** [handsontable/handsontable#6019]
I have a column dropdown  and i need always when i create a new line or add new values the dropdown column should start with a default value. 

It's possible?

**Comment by AMBudnik** [comment]
Hey @jamesandrade7 

You can use `dataSchema` like here https://jsfiddle.net/handsoncode/fr091pqu/ or a renderer (here like a placeholer) https://jsfiddle.net/handsoncode/m9wLj3er/
