### ISSUE TITLE
.sort function error after upgrading to latest version.

### ISSUE THREAD

**Issue by kalyantolety** [handsontable/handsontable#6020]
I upgraded to latest handsontable version and I get .sort is not a function error in browser console. I tried to add property to columns individually to disable sorting but them I get "cannot set property left of undefined"error in console.

![image](https://user-images.githubusercontent.com/33827767/58014001-7345e180-7b15-11e9-9c51-facb347b60c4.png)

This I tried and solves sort function error but I get some styling errors from handsontable frequently.
![image](https://user-images.githubusercontent.com/33827767/58013936-4f829b80-7b15-11e9-8030-9e3af23a5832.png)

![image](https://user-images.githubusercontent.com/33827767/58013895-35e15400-7b15-11e9-8c2c-39faabf5f043.png)

Is there something wrong in my configuration?

**Comment by AMBudnik** [comment]
I can see that you've been using an older version that 7.0.2 before. Sorting methods have changed - now to get the same result you attach[ an object with configuration](https://handsontable.com/docs/7.0.3/ColumnSorting.html#sort).
Demo https://jsfiddle.net/handsoncode/jvnf3qcy/

**Comment by kalyantolety** [comment]
I have tried it already. You can see in my second image. Then I keep getting console error as in third image from browser with handsontable.

**Comment by AMBudnik** [comment]
As this seems to work in the JSFiddle (attached before) I would need to ask you about a demo where I'll be able to replicate the issue. Can you put the code into JSFiddle or StackBlitz?

**Comment by kalyantolety** [comment]
I removed my js and css and put new copies of handsontable and then I replaced the className 'htMiddle' with "htLeft" attribute for the one that I'm applying the non sort-able  property and I now don't see the error. Only some warning. Thanks.
