### ISSUE TITLE
Deprecation warning for Element.createShadowRoot

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6024]
### Description
Our helper `isWebComponentSupportedNatively` bases on deprecated `Element.createShadowRoot`
https://www.chromestatus.com/features/4507242028072960

We should add support for [`Element.attachShadow`](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow) or adjust implementation to a new standard's requirements.

### Your environment
* Handsontable version: any
* Browser Name and version: Chrome 75+, Firefox, Safari
* Operating System: any

**Comment by AMBudnik** [comment]
Done with https://github.com/handsontable/handsontable/pull/6625/files
