### ISSUE TITLE
Prevent undo plugin keyboard shortcuts

### ISSUE THREAD

**Issue by jacekbogdanski** [handsontable/handsontable#6028]
### Description

I couldn't find an easy way to prevent undo plugin keyboard shortcuts. As far as I know, there is no such option for this plugin. 

I found that you can overwrite some hooks using `updateSettings`, however, undo plugin hooks are [reattached every time](https://github.com/handsontable/handsontable/blob/master/src/plugins/undoRedo/undoRedo.js#L712) when using `hot.updateSettings` function, so this method doesn't work for this special case.

I also tried to use `afterDocumentKeyDown` to customize `beforeKeyDown` hook as a workaround but seems that despite `event.stopImmediatePropagation` method, `beforeKeyDown` is still invoked by [afterDocumentKeyDown](https://github.com/handsontable/handsontable/blob/27ef4d49161f974e90843ff219d6c59ba86cc770/src/editorManager.js#L305). Stopped propagation is also not respected by [undoRedo plugin](https://github.com/handsontable/handsontable/blob/27ef4d49161f974e90843ff219d6c59ba86cc770/src/plugins/undoRedo/undoRedo.js#L631-L645).

Could you provide some API option to disable undo plugin keyboard shortcuts?

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: Any
* Operating System: Any

**Comment by AMBudnik** [comment]
Glad to see this issue fixed. The fixed version is available from `7.1.0`
