### ISSUE TITLE
Web Components version of Handsontable

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#603]
Handsontable v0.8.22 (soon to be released) is the first version of HOT that includes support for [Web Components](http://www.w3.org/TR/components-intro/) using [Toolkitchen Toolkit](http://toolkitchen.github.io/) library.

This ticket is reserved space for comments about this experimental implementation.

We are looking forward to be the first class citizen of Web Components. Please share your thoughts, improvement ideas and pull requests!

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
