### ISSUE TITLE
Method for adding rows or columns with data

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6032]
### Description

We are able to call `setDataAtCell`/`setDataAtRowProp` for a single value in the array. We can also replace the whole dataset via `loadData`. It will be beneficial to add an option like:
* `setDataAtCol`
* `setDataAtRow`

It can also be an option in the [`alter` method](https://handsontable.com/docs/7.0.3/Core.html#alter) to pass an array of data when we use `insert_col` and `insert_row` key.

### Your environment
* Handsontable version: 7.0.3
* Browser Name and version: n/a
* Operating System: n/a

**Comment by aarondfrancis** [comment]
I'm currently running into this as well. I tried modifying the underlying data, as it's passed by reference [1][2], but apparently the length changing isn't captured. Not sure exactly why, I'm sure there's a perfectly reasonable Javascript explanation for that.

You can see that changing a property of an existing record works, but we're not able to _add_ records.

https://jsfiddle.net/ynL0wxap/

I'm currently trying to append new (populated) rows that are being sent from the server, but am not quite sure how to do it at the moment.

Thanks!

[1] Very old issue: https://github.com/handsontable/handsontable/issues/264
[2] Docs: https://handsontable.com/docs/7.3.0/tutorial-data-binding.html

**Comment by aarondfrancis** [comment]
As usual, I had an idea for something crazy just after posting. 🤦‍♂ 

https://jsfiddle.net/je82y6or/

In this example, I pushed four records onto the source array and then called `alter('insert_row', null, 4)` to add four rows to the table. Magically, my data was there.

Is this method a good idea or no? It seems to work, but I'm not sure if I should rely on it?

**Comment by wojciechczerniak** [comment]
There is [setDataAtRowProp](https://handsontable.com/docs/7.3.0/Core.html#setDataAtRowProp) method. Is it not what you're looking for?

https://jsfiddle.net/wom7dueq/

To avoid multiple renders you may use the arrayOfArrays notation for `setDataAtRowProp`: `hot.setDataAtRowProp([[10, 0, 'B11'], [11, 0, 'B12']]);`

For the method that is request in this issue, I would use:
```ts
function insertRowAndSetData(rowIndex, rowArray) {
 hot.alter('insert_row', rowIndex);
 hot.setDataAtRowProp(rowArray.map((value, prop) => [rowIndex, prop, value]));
}
```
Usage:
```ts
insertRowAndSetData(10, ['A11', 'B11', 'C11']);
```
Although there may be an unnecessary render involved.

**Comment by wojciechczerniak** [comment]
> Is this method a good idea or no? It seems to work, but I'm not sure if I should rely on it?

Changing data by reference won't trigger the `afterChange` hooks.

**Comment by wojciechczerniak** [comment]
You may take a look at [populateFromArray](urlhttps://handsontable.com/docs/7.3.0/Core.html#populateFromArray method as well. With `shift` parameters it allows to insert data between rows/cols.

Should work something like:
```ts
 hot.populateFromArray(12, 0, [['B11'], ['B12']]);
```

https://jsfiddle.net/gsu3d5kv/

**Comment by aarondfrancis** [comment]
Thanks for the quick reply @wojciechczerniak.

> Is this method a good idea or no? It seems to work, but I'm not sure if I should rely on it?

The answer to that is definitely a "no". 😂 

While it seems like it works, it actually doesn't. If you push 4 items onto the source array and then call `alter` to add four rows, you actually end up with 8 rows, 4 showing your data and 4 not showing that are totally blank. When you try to do the same thing again later, you'll see the 4 old blank rows instead of your new data, so it doesn't work that well.

I don't think I can use `populateFromArray` in my real app, because my source is all objects and I need to reference them by key.

I ended up writing a plugin to hack around it for now, but I would be in favor of a proper `appendData` solution at some point in the future!

Here's my plugin for now:

```js
import PluginFactory from './plugin-factory';

let AppendData = PluginFactory('appendData');

let pending = [];

AppendData.prototype.enable = function () {
    this.addHook('afterCreateRow', this.afterCreateRow.bind(this));

    // Add the `appendData` method on to the HoT instance.
    this.hot.appendData = this.appendData.bind(this);
}

AppendData.prototype.afterCreateRow = function (index, amount, source) {
    if (source !== 'append_data') {
        return;
    }

    let changes = [];
    for (let i = 0; i < amount; i++) {
        for (let key in pending[i]) {
            changes.push([index + i, key, pending[i][key]]);
        }
    }

    this.hot.setDataAtRowProp(changes, 'append_data');
}

AppendData.prototype.appendData = function (data) {
    pending = data;

    let selection = this.hot.selection;
    let _refresh = this.hot._refreshBorders;

    // We have to overwrite some stuff here to force HoT to not kill our
    // selection. If we didn't do this, someone could be in the middle
    // of editing a cell when new data is appended, which would blur the
    // cell. If they continued typing as if the cell was not blurred,
    // they would overwrite the previous value.
    this.hot.selection = {
        isSelected: () => false
    }
    this.hot._refreshBorders = () => false

    // Add the right number of rows, using a hysterically large number to
    // always force them to go to the bottom. Use the 'append_data' source
    // so that we can catch it on the 'afterCreateRow'.
    this.hot.alter('insert_row', 100000000, data.length, 'append_data');

    // Turn everything back on.
    this.hot._refreshBorders = _refresh;
    this.hot.selection = selection;

    this.hot.render();
}

export default AppendData;

```


On a side note, I need to figure out a good way to test all of my plugins. Can you point me to a simple test harness to get me started? I need to make sure all of my crazy hacks work in future releases!

**Comment by aarondfrancis** [comment]
I totally missed your first comment about `setDataAtRowProp`. I didn't realize that would _add_ rows if they didn't already exist. Was going through my emails just now and saw that.

So now my plugin is far far simpler.

```js
import PluginFactory from './plugin-factory';

let AppendData = PluginFactory('appendData');

AppendData.prototype.enable = function () {
    // Add the `appendData` method on to the HoT instance.
    this.hot.appendData = this.appendData.bind(this);
}


AppendData.prototype.appendData = function (data) {
    let last = this.hot.countVisibleRows();

    let changes = [];

    for (let i = 0; i < data.length; i++) {
        for (let key in data[i]) {
            changes.push([last + i, key, data[i][key]]);
        }
    }

    this.hot.setDataAtRowProp(changes, 'append_data');
}

export default AppendData;
```

Guess I should've read more closely. Thanks @wojciechczerniak!

**Comment by aarondfrancis** [comment]
Updated plugin for 8.0.0: https://github.com/handsontable/handsontable/issues/7288#issuecomment-699009531

**Comment by AMBudnik** [comment]
Thank you for all the feedback.

I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
