### ISSUE TITLE
How to align the text content to top border of td, but leave some paddings, for cells with rowSpan > 1 ?

### ISSUE THREAD

**Issue by DongShi** [handsontable/handsontable#6034]
### Description

Hey there:
By default, we put a htMiddle class to td, so td text is vertically centered, and this works great for normal cells (rowSpan = 1, etc).

However, for tall cells (rowSpan is very big), user might have to scroll to see the centered text, which is a bit annoying.

![image](https://user-images.githubusercontent.com/5009987/58606074-aaae4e00-82cc-11e9-9f0a-94da6e1b3d58.png)

So, we wonder if it is possible to push up the text, but leave the the same top padding as for htMiddle， like the following (mocked)
![image](https://user-images.githubusercontent.com/5009987/58606319-81da8880-82cd-11e9-8f96-c69bb8e80cb3.png)

btw， it seems htTop will leave no top padding. So probably we can not simple add htTop to tall tds.

![image](https://user-images.githubusercontent.com/5009987/58606137-e2b59100-82cc-11e9-9d07-8a4e55340ecf.png)

### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version: latest
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Hey @DongShi 

currently, it can only be done by custom styling (a new class with new styles).

**Comment by DongShi** [comment]
@AMBudnik can you give an example on how this class shoulde be look like
It does not seem like an easy task to manipulate the text inside a td/tr.

**Comment by AMBudnik** [comment]
Maybe something like this https://jsfiddle.net/29Lakzgj/ ?
But this is a fixed `padding`. If the height of the row changes you'd need to control the CSS settings via variables.

**Comment by DongShi** [comment]
Sounds good, I will try your approach out.
