### ISSUE TITLE
The function loadManualRowHeights is return a array, but in the typescript .d.ts file it is defined as void

### ISSUE THREAD

**Issue by linjiayu2012** [handsontable/handsontable#6035]
### Description
The function loadManualRowHeights is return a array, but in the typescript .d.ts file it is defined as void

**Comment by AMBudnik** [comment]
Thank you for sharing. You're right it should return an array if the `persitentState` was used for row resize https://jsfiddle.net/jcL75bt0/

**Comment by AMBudnik** [comment]
Updated demo https://jsfiddle.net/AMBudnik/382z7oar/ v7.4.2

Here https://github.com/handsontable/handsontable/blob/df81543c2d3d65ef5775b1b05bec55e7d3c79b24/src/plugins/manualRowResize/manualRowResize.js#L131 we can see that the `loadManualRowHeights` function returns the `storedState`.

**Comment by wojciechczerniak** [comment]
@pnowak Looks like this issue has a merged PR and awaits QA. But it's not added to a release. Can you update it's status?

**Comment by pnowak** [comment]
Updated in https://github.com/handsontable/handsontable/issues/6465

**Comment by AMBudnik** [comment]
Hi @linjiayu2012,

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

**Comment by aninde** [comment]
In 7.4.2 and before, was:
https://github.com/handsontable/handsontable/blob/f517f721e23d75367b8cf491bff3c6de3ee18367/handsontable.d.ts#L1455
With `v8` will be:
https://github.com/handsontable/handsontable/blob/5051859a956f409efcfdf435deb5db3ad33922f2/handsontable.d.ts#L1381

Working demo with `8.0.0-beta2` https://jsfiddle.net/aninde/69nwd3uc/.

**Comment by AMBudnik** [comment]
Official 8.0.0 (fixed)

https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1380
