### ISSUE TITLE
Range slider in Filters

### ISSUE THREAD

**Issue by Shadowsrik** [handsontable/handsontable#6036]
Hello,

Is it possible to set filters to select numeric values with in a range using SLIDER?

I know he filter has option greater than  and so on. But I would like to set the range values using a slider

**Comment by AMBudnik** [comment]
Sorry @Shadowsrik 

there is no way to modify the filters via official API. However, this sounds like a good idea.

**Comment by Shadowsrik** [comment]
Are there any plans to implement this for pro users?

**Comment by AMBudnik** [comment]
Hey @Shadowsrik there are no longer PRO and CE users. Now it is only one Handsontable.
I do not see any similar task on our Roadmap but will surely let you know once we get this done.

**Comment by Shadowsrik** [comment]
Hi @AMBudnik, that would be great. I will be waiting for it.

**Comment by AMBudnik** [comment]
Thank you for sharing this proposition.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback. 
See you there!
