### ISSUE TITLE
Scrolling within autoCompleteEditor dropdown causes table to scroll instead of dropdown

### ISSUE THREAD

**Issue by desainn** [handsontable/handsontable#6042]
### Description
I have a Handsontable that utilizes vertical scrolling to accommodate the overflow of rows within its container. Scrolling the table works fine with the mousewheel.

When I add a dropdown within the cells with a long list of values that also needs a scroll bar, mousewheel scrolling causes the table to scroll instead of scrolling within the dropdown list.

I've messed around with the overflow css properties and the only way I've been able to fix it is by adding overflow: visible to the handsontable container. This unfortunately causes the main table to overflow the container causing rendering performance issues so its not an acceptable solution.

Ideally I'd like to have the table's overflow within the container but still be able to scroll through the long dropdown list.

### Steps to reproduce
1. Create handsontable with enough rows to overflow container and add `overflow: hidden` to ensure vertical scrollbar appears for table
2. Add dropdown/autoComplete to column with list long enough to have a scrollbar
3. Open dropdown and attempt to scroll down vertically. It will scroll the table instead of scrolling the dropdown list.

### Demo
http://jsfiddle.net/6vahq924/

### Your environment
* Handsontable version: 7.0.3
* Browser Name and version: Chrome & Firefox (lastest versions)
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
It seems to work fine on my device (Windows) but here's a similar issue for Mac https://github.com/handsontable/handsontable/issues/5913. Do you get the same result?

**Comment by desainn** [comment]
Fairly similar, yes. What was the solution for that issue?

**Comment by AMBudnik** [comment]
Here is a corresponding PR https://github.com/handsontable/handsontable/pull/5921/files
It is `ready for review` so it should be published in no time.
