### ISSUE TITLE
Add hook: afterEditorClose

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6044]
### Description

We already have `afterBeginEditing` but don't have a hook that is called when we finish the process. The `afterChange` covers closing the editor with <kbd>Enter</kbd> and clicking outside the cell but doesn't cover the <kbd>ESC</kbd> button.

### Your environment
* Handsontable version: 7.0.3
* Browser Name and version: n/a
* Operating System: n/a

**Comment by imageslr** [comment]
Or called `afterEndEditing` / `afterFinishEditing`. This hook is useful in some case, such as automatically change cell type after close editor, just like behavior in Excel.

**Comment by AMBudnik** [comment]
Thank you for sharing feedback on my issue.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback. 
See you there!
