### ISSUE TITLE
Sorting, observeChanges, custom renderers with click events problem.

### ISSUE THREAD

**Issue by MaryElizabethWatson** [handsontable/handsontable#6047]
Hi, we are the noticing the rendering is invoked multiple times, too. And we have problems with custom links in cell also (#3567). We check issue #2630 and then we set observeChanges to false and didn't find any issue in way we use your grid. Sorting work good as expected, and changes owned to correct row even if we change, when use sorting. observeChanges is required for using sorting? Can you describe some bad scenarious that we can get, when observeChanges set to false and sorting set to true?

**Comment by wojciechczerniak** [comment]
If you modify `settings.data` through reference i.e. `data.push(newRow)` or `data.splice()` then sorting can't notice the change. If you do it with Handsontable API you're safe, all necessary hooks are triggered and plugins are updated correctly.

**Comment by MaryElizabethWatson** [comment]
Thanks for answering, we use only Handsontable API in this cases, so we'll continue to use `observeChanges = false` as fix for problem about calling multiple renderers) Have a nice day!
