### ISSUE TITLE
Custom Filter implementations has wrong column indexes

### ISSUE THREAD

**Issue by mudit-maven** [handsontable/handsontable#6048]
### Description

Go to the url : 

### Steps to reproduce

1. Open the JSFiddle mentioned in the URL https://handsontable.com/docs/7.0.3/demo-filtering.html#custom-implementations
2. JSFiddle URL : https://jsfiddle.net/api/post/library/pure/
3. Add 4 more columns by increasing data.
4. Type : safad in last column and scroll horizontally.
![record](https://user-images.githubusercontent.com/33653805/59268022-67a78f80-8c69-11e9-8913-469e04ff6583.gif)

### Demo

https://jsfiddle.net/68bxg7z5/

### Your environment
* Handsontable version: 1.4.1
* Browser Name and version: Chrome 74.0.3729.169 (Official Build) (64-bit)
* Operating System: Windows 10 Home

**Comment by AMBudnik** [comment]
It seems to work fine (I'm on the same system and browser). I have attached 4 additional columns with all data as `null`.
When I used `safad` string inside the last (`J`) column input I got no rows > nothing matches this search.

**Comment by mudit-maven** [comment]
> It seems to work fine (I'm on the same system and browser). I have attached 4 additional columns with all data as `null`.
> When I used `safad` string inside the last (`J`) column input I got no rows > nothing matches this search.

Did you scroll the table?

**Comment by AMBudnik** [comment]
Yes, the whole data is invisible. Maybe it is a matter of settings up viewport size? Can you record the oddity?

**Comment by AMBudnik** [comment]
It's nearly a week without any response. Do you still get the same result @mudit-maven ?
