### ISSUE TITLE
How can we add a class to a specific autocomplete list item?

### ISSUE THREAD

**Issue by veeru1087** [handsontable/handsontable#6049]
### Description
As I see, we can only supply list of strings to autocomplete source. There is no way we can style one of those items (adding a class), based on a condition.

I have tried inserting html, but it displays HTML when we edit the selected cell.

### Your environment
* Handsontable version: 6.2.0
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hey @veeru1087 

You can change CSS styling for a particular element in the list by using nth-child() like here https://jsfiddle.net/4s15yedc/

**Comment by veeru1087** [comment]
@AMBudnik, Thanks for answering. My requirement is different. The order of the items may change. 
Let's say, my drop down source is cming from database with each of them having a property "highlight" with a value "true" or "false". What if I want to style only the items with "highlight: true"? Is there any way we can add a class conditionally?

**Comment by AMBudnik** [comment]
I think that the only way would be to create a custom editor in this case.

**Comment by veeru1087** [comment]
Hi, can you point to any resource or example on how do I create a custom editor for autocomplete? We tried to create a react component using memoized containers, but it was so slow.

**Comment by AMBudnik** [comment]
Here https://handsontable.com/docs/7.1.0/tutorial-cell-editor.html are the methods and code snippets for the cell editors.
If you're using one of our wrappers here are the examples for those

- React https://handsontable.com/docs/7.1.0/frameworks-wrapper-for-react-custom-editor-example.html
- Angular https://handsontable.com/docs/7.1.0/frameworks-wrapper-for-angular-custom-editor-example.html
- Vue https://handsontable.com/docs/7.1.0/frameworks-wrapper-for-vue-custom-editor-example.html
