### ISSUE TITLE
Why does Handsontable not show all cells in fullscreen mode?

### ISSUE THREAD

**Issue by patrickluethi** [handsontable/handsontable#6050]
### Description
First i create a Handsontable with the function addTable. I create a div with the id 'hotTable' which is the container of the Table. When i try to set that container div fullscreen everything works fine. But if i try to scroll down the table doesnt show any more Information. The rest of the table is just black.

### Demo
// If status = false request fullscreen
fullscreen(status, id, callback = function () {}) {
  if(status) {
    document.exitFullscreen();
  } else {
    var element = document.getElementById(id);
    element.parentNode.requestFullscreen();
    element.style.width = '100%';
    element.style.height = '100%';
    element.style.overflow = 'auto';
  }
callback();
}

// create Handsontable
addTable(ifcClass) {

  let self = this;
  this._hots[ifcClass] = null;
  this._tabs[ifcClass] = document.createElement("DIV");
  this._div.appendChild(this._tabs[ifcClass]);
  this._div.id = "hotTable";
  // add a button to open the tab
  let func = function() {
    self.openTab(ifcClass)
  };

  // let btn = newButton(ifcClass, func);
  // this._rightButtonDiv.appendChild(btn);
  // this._contentDiv.appendChild(this._tabs[ifcClass]);

}

I expect to set the container fullscreen which works and Table to extend it. But the table doesnt load complety just the first few rows.

Here is a JSFiddle with the same problem:

https://jsfiddle.net/patrickluethi97/qreLuxkb/

**Comment by AMBudnik** [comment]
The fullscreen mode messes up with the `position` setting of Handsontable (`rowHeaders` stick to their places.).

To show all the rows you can use `renderAllRows: true` but it doesn't change `rowHeaders`

**Comment by patrickluethi** [comment]
Thanks works great! But now we have a new problem. The loading process is extremly slow, is there any way to speed that up? We have about 18'000 cells.

**Comment by AMBudnik** [comment]
Yes, `renderAllRows: true` forces the table to load all the rows at once to it makes you wait longer at the beginning but makes scrolling faster. 
I do not see any other workaround for now. Hot is very sensitive when it comes to `position` and `overflow` settings. You may try to change those.

**Comment by patrickluethi** [comment]
Okay thanks!

**Comment by wojciechczerniak** [comment]
@patrickluethi Set Handsontable to width/height 100% of the container and modify container size: https://jsfiddle.net/jsfLn3pc/

**Comment by AMBudnik** [comment]
Please do not close this topic @patrickluethi 

I would leave this issue open. Maybe there's something we'll be able to do with it.

**Comment by AMBudnik** [comment]
That was a quick one. Thanks for stepping in Wojciech! Agree, now it works as expected. Doesn't it @patrickluethi ?

**Comment by patrickluethi** [comment]
@wojciechczerniak thank you! @AMBudnik works perfect solved my issue and is still fast!

**Comment by AMBudnik** [comment]
Great! So now we can close the topic :)
