### ISSUE TITLE
Datapicker position changes when we set height

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6053]
### Description

When we set a fixed height for the table the datapicker window does change its position while scrolling.

height is set (doesn't stick to the input)
![set](https://user-images.githubusercontent.com/10757813/59489449-7ddc6800-8e82-11e9-95a7-eb7f4f5fff7e.gif)

height is not defined
![not-set](https://user-images.githubusercontent.com/10757813/59489445-7ae17780-8e82-11e9-8771-7cdf8a10782a.gif)

### Steps to reproduce

1. Open any date cell
2. Scroll vertically

### Demo

https://jsfiddle.net/AMBudnik/e7xkfjLn/

### Your environment
* Handsontable version: 7.1.0
_Doesn't seem to be related to any version._
* Browser Name and version: Chrome 75
* Operating System: Mac Mojave

Related topic https://github.com/handsontable/handsontable/issues/3483

Inform [forum](https://forum.handsontable.com/t/vuejs-issue-position-the-datepicker-after-scrolling/3359)

**Comment by sb-st** [comment]
Same problem with horizontal scrolling:
https://jsfiddle.net/AMBudnik/e7xkfjLn/

**Comment by AMBudnik** [comment]
Thank you for feedback @sb-st 

It looks like it works the same in `7.3.0` for both directions

![GIF](https://user-images.githubusercontent.com/10757813/74150899-3671cb80-4c0b-11ea-89df-ae8cd88642d3.gif)

**Comment by AMBudnik** [comment]
Works the same both directions for v8.2.0 https://jsfiddle.net/handsoncode/gv56y2jx/ when the editor is opened

![date_cell](https://user-images.githubusercontent.com/10757813/105356720-1062f280-5bf4-11eb-9aa6-2fd8b21ab583.gif)

and the same as before (when `height` is not defined) editor is being closed https://jsfiddle.net/handsoncode/d4h9mb6q/

![date_cell_heightno](https://user-images.githubusercontent.com/10757813/105356930-5cae3280-5bf4-11eb-9126-a0c6732772fa.gif)

**Comment by AMBudnik** [comment]
Hi All! 

We just fixed this issue in v14.3.0 by this PR https://github.com/handsontable/handsontable/pull/10892

Here you can read more about the changes within that version https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-3-0

CC @sb-st
