### ISSUE TITLE
Unable to prevent contextmenu showing on col and row headers

### ISSUE THREAD

**Issue by talamaska** [handsontable/handsontable#6055]
### Description
Unable to prevent contextMenu showing on col and row headers
Please assist with support

### Your environment
* Handsontable version: 7.0.3
* Browser Name and version: Chrome 69 / Electron 4.x
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
We should add an ability to block the menu by returning `false` in the `beforeContextMenuShow` hook but that doesn't work so I used the click event and `updateSettings` https://jsfiddle.net/AMBudnik/4b5qzf7u/

**Comment by talamaska** [comment]
@AMBudnik actually 
```
if ((coords.col < 0 || coords.row < 0) && event.button === 2) {
      console.log('should disable propagation');
      this.hotInstance.getPlugin('contextMenu').disablePlugin();
    } else {
      this.hotInstance.getPlugin('contextMenu').enablePlugin();
    }
```
this seems more reliable it doesn't lose the contextMenu configs if you have set something

**Comment by AMBudnik** [comment]
That's true :) @talamaska
