### ISSUE TITLE
How to add metadata for a cells as bulk on updatingSettings?

### ISSUE THREAD

**Issue by subashdbc** [handsontable/handsontable#6056]
Hi,
How to add metadata for a particular cell as bulk? I also see that we can achieve this with `setCellMeta(row, column, key, value)` method, but here when adding 100 of records at the same time on the table when we call setCellMeta it takes some time to add the meta property values.
So it would be good that we can set it as bulk(array of an array). 
Here I have used `cell` property to set metadata as bulk like this,
```
cellsMeta = [{ row: 0, col: 0, custom_value: '12345' } ............ etc]
handsonInstance.updateSettings({
       cell: cellsMeta
 })
```
not sure if this is the correct method to set the meta property. But here comes another problem when I remove a row and the next row moves up on the table then it becomes another set of logic to change the rest of the rows to next on cellsMeta variable  (not sure this is the correct way).

But I see that `handsonInstance.setCellMeta(row, column, key, value)` maintains correctly when removing the rows also. So is it possible to set the cellMeta as bulk so that it can be used set on `updateSettings`

Thanks in advance!

**Comment by AMBudnik** [comment]
Hey @subashdbc 

have you tried the [cells](https://handsontable.com/docs/7.1.0/Options.html#cells) option? 

Here are two couple of examples that will show you how to use the option
http://jsfiddle.net/AMBudnik/8L46mbzv/
http://jsfiddle.net/swx43n2p/

**Comment by subashdbc** [comment]
@AMBudnik Thanks

**Comment by subashdbc** [comment]
Hi @AMBudnik 

[Cells](https://handsontable.com/docs/7.1.0/Options.html#cells) option is the same as [cell](https://handsontable.com/docs/7.1.0/Options.html#cell)
When we remove it doesn't work as like `handsonInstance.setCellMeta(row, column, key, value)` setting it like this

the problem is when I have a list of rows, and for each row we need to set the metadata so I use `cell` to store the data, but when we remove the row(s) the next row(s) occupies the space of row(s) which was deleted right? So `cell` doesn't get updated, the values remain the same as before.

but when we try to add metadata like this  `handsonInstance.setCellMeta(row, column, key, value)`, when removing the row also it works correctly and maintains the row values. the one problem here could be is, when adding more rows it takes much time.

Guide me here! Thanks

**Comment by AMBudnik** [comment]
I think that `cells` is the best one as you are able to pass all the meta like in the `cell` option but it is easier to update it. The `setCellMeta` method is a good pick if you want to change only a couple of values. 
Additionally, if you want to pass a `className` to all the cells in some columns you may use `columns` options.
