### ISSUE TITLE
Can HOT show Headers as images?

### ISSUE THREAD

**Issue by DongShi** [handsontable/handsontable#6057]
### Description

Hey there, is it possible to show the header content as images
I see you can show image on data cells, as in your demo:

![image](https://user-images.githubusercontent.com/5009987/59548821-f75d7e80-8f86-11e9-93e8-0a0d92acbbe3.png)

but how about headers?

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: latest
* Browser Name and version: Any
* Operating System: Any

**Comment by AMBudnik** [comment]
Hi @DongShi 

Yes, it can. You can use `HTML` inside the `afterGetColHeader` and `afterGetRowHeader` hooks. Here's an example for both of them https://jsfiddle.net/u372sn1j/

**Comment by DongShi** [comment]
Thanks @AMBudnik , again!

**Comment by AMBudnik** [comment]
You're welcome :)
