### ISSUE TITLE
Performance and CPU wastage issue due to some handsontable properties.

### ISSUE THREAD

**Issue by meta-rohit-singhavi** [handsontable/handsontable#6058]
### Description
I am using multiple handsontable instances on my webpage and facing major performance issue when I render multiple handsontables on the page (more than around 20 tables with around 25 columns and 100 rows for example). 
After using chrome's devTools I got to know that scripting and cpu usage was there even in case the page was ideal. I did a console log in timer function of zone.js file and it was being called infinitely in case of any single table creation. 
**The issue in code which I found was somehow due to the two properties of handsontable ( filters and columnSorting )** and after setting these two properties as false simultaneously, the console log of zone.js file doesn't get called infinitely and CPU usage and scripting size is also shown as zero in case the page is ideal. 
But even after removing these two properties my page responsiveness decreases and it hangs a lot in case of multiple tables.

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 75
* Operating System: Windows

**Comment by AMBudnik** [comment]
I've run an instance of Handsontable in an incognito mode and checked how many seconds it took to run the `afterRender` hook.
The settings are

```
data: Handsontable.helper.createSpreadsheetData(5000, 25),
colHeaders: true,
columnSorting: true,
dropdownMenu: true,
filters: true
```

Rounds
```
14.265
13.798
15.425
14.364
13.842
```
the average is `14,338`

When I disabled `columnSorting`, `dropdownMenu` and `filters`

Rounds
```
0.636
0.723
0.675
0.646
0.585
```
the average is `0,653` so the difference is obviously noticeable.

The issue for lowering performance while using Filters is already reported here https://github.com/handsontable/handsontable/issues/4352 so I've checked the `columnSorting` alone.

Rounds
```
13.969
14.21
13.432
15.712
12.996
```
the average is `14,06` so we can say that it's crucial for performance.

**Comment by AMBudnik** [comment]
As I did not share any demo after doing the research... I think that it would be better to track it down via [performance-lab](https://github.com/handsontable/performance-lab)

**Comment by wojciechczerniak** [comment]
@AMBudnik do you have a test case you've used for the numbers? ColumnSorting in v8 is no longer enabling ObserveChanges which IMO are responsible for the this. So the issue might be resolved already

**Comment by AMBudnik** [comment]
Hey @wojciechczerniak after a short discussion with @budnix I released that the metrics that I chose weren't reliable. We should take some time to test it in Performance Lab. That would allow us to receive 
measurable values that could be checked across the versions of Handsontable.

**Comment by AMBudnik** [comment]
Hi @meta-rohit-singhavi 

yesterday we've released Handsontable v 8.0.0. Could you check if the CPU wastage is still an issue?

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases

**Comment by wojciechczerniak** [comment]
Each plugin may add some weight to data processing. Filtering and sorting are obvious candidates for bottlenecks. Unfortunately, there is no reproduction code. The OP says, that even without those properites the application hangs. OP mentions `zone.js` so it's probably Angular app. No configuration or code provided. Problem may be somewhere else.

@meta-rohit-singhavi @AMBudnik Either provide a reproduction, or we have to close this issue as a non-actionable.

**Comment by AMBudnik** [comment]
As we check all the future versions of Handsontable in the Performance Lab I agree that we should close this subject as already checked.

@meta-rohit-singhavi If you see that some particular settings are causing issues between the versions of Handsontable please let me know. I'm monitoring all the emails to support@handsontable.com
