### ISSUE TITLE
Set Handsontable to 100% width and height and if necessary with scrollbar

### ISSUE THREAD

**Issue by patrickluethi** [handsontable/handsontable#6061]
How can i set Handsontable width and height to 100% always. I want the table to always extend the whole screen size or inside an additional div container. The default width of each cell should be set to minWidth. So if there are to many columns the table extends over the whole screen and adds in a horizontal scrollbar.

I searched many forums for any solutions but couldnt find anything helpful. I tried to set the diffrent Handsontable divs to 100% but whenever i did that, the whole table started to bug.

```
var hot = new Handsontable(container, {
  data: data(),
  minSpareCols: 1,
  minSpareRows: 1,
  rowHeaders: true,
  colHeaders: true,
  contextMenu: true,
  width: '100%',
  height: '100%',
});
```

I set the width and height bouth to 100% but that doesnt change anything.

I created a JSFiddle which displays a Table with the exact problem. Just press once on Fullscreen and exit again. After that you will see how the table doesnt extend to the Scrollbar.

https://jsfiddle.net/6gvkLyf1/

Thank you for helping!

**Comment by AMBudnik** [comment]
Hey @patrickluethi 

I can see that you continue the subject from https://github.com/handsontable/handsontable/issues/6050

Can share a draft on how the table should look like? I'm not sure if I understand how it should look in the end.

**Comment by patrickluethi** [comment]
Hi @AMBudnik 

It is not the exactly the same subject as #6050. 

You know that i have a div as a container around the table. Now that div is always the same fixed size. Now I would like to have the Table columns each a bit bigger in the width so it is the same size as the width of the container.
But now it is important that the columns need to have their minimum width size. So if there are a big amount of columns they all have the minimum width size and the table goes over the fixed size div. In this case the table should just expand with a horizontal scrollbar. 
I hope that you understand now what my problem is. 

Thanks you :)

**Comment by AMBudnik** [comment]
We do not have `min-` and `max-` CSS settings implemented yet ([topic to follow](https://github.com/handsontable/handsontable/issues/3301)), but maybe you'd find the [`stretchH`](https://handsontable.com/docs/7.1.0/Options.html#stretchH) useful. It allows you to use 100% width of the viewport.

**Comment by patrickluethi** [comment]
It is not really doing anything for me. Also when i change some options or try to play with it in chrome. All 3 Options remain the same for me.

**Comment by AMBudnik** [comment]
The same? That's shouldn't happen. For example this https://jsfiddle.net/gy1ou5q2/ should expand the columns to equally take space to fill the container horizontally.

**Comment by patrickluethi** [comment]
After a day of try and error we realised that the error is caused of an div resize function. The handsontable works fine now, the `stretchH` did the job for us.

Thanks for your help.
