### ISSUE TITLE
[7.1.0] Error when we move MULTIPLE rows in a nestedRows table

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6066]
### Description

If you'd like to move a child from one parent to another you get an error in the console. 
![image](https://user-images.githubusercontent.com/10757813/60017262-a3d6e900-9688-11e9-901c-d22ed79189f6.png)

### Steps to reproduce

1. Move any children from one parent to another

### Demo

https://jsfiddle.net/718jnLop/2/

and when we want to move the rows while having some parents collapsed table misaligns.

![issue](https://user-images.githubusercontent.com/10757813/60017635-82c2c800-9689-11e9-9355-6d397964f549.gif)

and you get this error

![image](https://user-images.githubusercontent.com/10757813/60017552-442d0d80-9689-11e9-91cd-020945776034.png)

### Your environment
* Handsontable version: 7.1.0
_It doesn't seem to be related to any version._
* Browser Name and version: Chrome 75
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
The issue stays the same after introducing changes to https://github.com/handsontable/handsontable/issues/5751 on the branch https://github.com/handsontable/handsontable/tree/feature/issue-5751.
Tested on Chrome 76/ macOS Mojave / local server.

We still get the same error in the console while moving children rows from one parent to another.
![Zrzut ekranu 2019-09-13 o 12 59 29](https://user-images.githubusercontent.com/10757813/64857966-584c2f80-d626-11e9-92c7-a4f919f177ed.png)

**Additional information**
* The issue doesn't happen if a row is moved within the same parent.
* The row is successfully moved. The error shows after the row is moved (`afterRowMove` is called before we get the error in the console).

**Comment by AMBudnik** [comment]
Glad to see this working correctly using v`8.0.0-rc1` for this scenario.

Updated demo https://jsfiddle.net/8yztfan2/

There ano no errors in the console (like before). Everything's working smoothly even between multiple parents.

**However**, there is a new issue that hasn't been present in `7.1.1`. It happens when we move multiple rows.

### Scenario
1. Select those two rows
![image](https://user-images.githubusercontent.com/10757813/64956606-4f0fcc80-d88b-11e9-93bf-fd826ea33cc1.png)
2. Move them after `Alabama Shakes` from the `Best Rock Performance`
![image](https://user-images.githubusercontent.com/10757813/64956712-87afa600-d88b-11e9-9511-01ee8c7ca021.png)

Till that point, everything's fine in `7.1.1` and `8.0.0-rc1` 

3. Move the two rows (Elle and James) back to their place - after `Alabama Shakes` from the `Best Rock Song`
![image](https://user-images.githubusercontent.com/10757813/64957030-4075e500-d88c-11e9-9fc0-48dc91255840.png)

In `8.0.0-rc1` James and Elle decided to just into `Best Metal Performance` instead.

**Comment by AMBudnik** [comment]
The previous case mentioned `columnSorting` as the bug factor and in reality, it makes the bug worse. However, the new bug (with multiple rows) is also visible without the `columnSorting`.
The difference is the rows are back to `Best Rock Song` but they appear in the `14` instead of `16`.

This case should be further tested as the 'shade' is not placed well and we may get false results.

**Comment by aninde** [comment]
In the new v. 8`.0.0rc-1` appears one more error that was not occur in `7.1.1.`
The nested row cannot be moved down to another parent row if it is the first child row.
But any nested (even first) row can be moved up to the upper parent row.

**Comment by aninde** [comment]
This bug is still at the newest ver. of `8.0.0rc-1`. Additionally, @AMBudnik found other [bug](https://github.com/handsontable/handsontable/issues/6067#issuecomment-534943034)  that also occurs here.

**Comment by wszymanski** [comment]
We introduce a new breaking change from `8.0.0`. Moving rows will be possible just by drag using UI or by the `dragRows`/`dragRows` methods of the `ManualRowMove` plugin.

**Comment by wszymanski** [comment]
New files:

https://cdn.jsdelivr.net/gh/handsontable/handsontable@42bc4bc26be17ba37498ee1db72362f8561212e8/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@42bc4bc26be17ba37498ee1db72362f8561212e8/dist/handsontable.full.css

**Comment by AMBudnik** [comment]
Well done @wszymanski Elle & James got back successfully 👍 

![GIF](https://user-images.githubusercontent.com/10757813/66297198-8522f800-e8ef-11e9-913a-2421cc813852.gif)

**Comment by aninde** [comment]
@wszymanski described here the issue is no longer replicable in the latest build. However, there is regression when you tried to move nested row to be the last in the table https://github.com/handsontable/handsontable/issues/6067

![Screenshot 2019-10-07 at 10 48 21](https://user-images.githubusercontent.com/30186818/66297488-0c706b80-e8f0-11e9-865c-5f0d61bb673f.png)

Demo:
v. latest `8.0.0-rc1` https://jsfiddle.net/aninde/Lz2a5j1b/

**Comment by AMBudnik** [comment]
Fixed in the beta https://jsfiddle.net/1f6a5bsd/ Thank you!

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 https://jsfiddle.net/9cms3tg0/
- no console errors
- we are able to move one and more rows between parents
so I call this issue solved.
