### ISSUE TITLE
[7.1.0.+] We cannot move nested row to become the last one in the table

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6067]
### Description

We cannot move any element to become the last one in the table and we get an error in the console.

### Steps to reproduce

1. Try to move any row to make it the last one.

You'll get
![image](https://user-images.githubusercontent.com/10757813/60018422-9a02b500-968b-11e9-932d-afc37b2aaa61.png)

### Demo

https://jsfiddle.net/qLmxczpo/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome 75
* Operating System: Windows 10

Related https://github.com/handsontable/handsontable/issues/4567

**Comment by AMBudnik** [comment]
Tested with build `8.0.0.-rc1` (25/09/2018) https://jsfiddle.net/970tdon2/

We no longer get the error in the console.
We are able to move a row. However, the row should be the last one and it's one before the last one.

![example](https://user-images.githubusercontent.com/10757813/65589015-aba87100-df88-11e9-8e06-87d54e8e4c2e.gif)

As we're able to move a row to the last position when data is not nested we should not mark this as fixed.
https://jsfiddle.net/7sxebqhn/

![gif](https://user-images.githubusercontent.com/10757813/65589763-e068f800-df89-11e9-9e83-c89ffd3cf829.gif)

What do you think @wojciechczerniak @aninde ?

**Comment by aninde** [comment]
@AMBudnik good job with finding this bug, it works the same in #6066. even in older version of 8.0.0-rc1.
 I found something [similar](https://github.com/handsontable/handsontable/issues/6066#issuecomment-533517142)  in #6066 , we aren't able to move down row if it first child.

**Comment by aninde** [comment]
Duplicates #6066, so I'm closing described here issue.

**Comment by aninde** [comment]
The issue is still replicable in the latest build of `8.0.0-rc1`.

v. [latest](https://github.com/handsontable/handsontable/issues/6066#issuecomment-538893137) `8.0.0-rc1` https://jsfiddle.net/aninde/Lz2a5j1b/

**Comment by wojciechczerniak** [comment]
Not related to index mapper and `v8.0.0`.

This happens when `rowObject` is null in `getRowObjectParent`. Line 303 has a bug, `typeof null` is "object". Condistion shouldn't be met and this function probably should return `null`.

https://github.com/handsontable/handsontable/blob/42bc4bc26be17ba37498ee1db72362f8561212e8/src/plugins/nestedRows/data/dataManager.js#L302-L308

**Comment by AMBudnik** [comment]
@wojciechczerniak was right. It stays **unsolved** in 8.0.0-beta2-rev6 https://jsfiddle.net/nu0Lg3yw/

**Comment by AMBudnik** [comment]
The issue is still replicable using v 8.0.0 https://jsfiddle.net/ndqx9rze/

**Comment by pnowak** [comment]
In v8.0.0, we don't get an error, but we can't move any row to make it the last one.
Here's an updated demo - https://jsfiddle.net/wxhfbytk/

**Comment by aninde** [comment]
This issue will be fixed by the upcoming `v8.1.0` https://jsfiddle.net/aninde/03gLpqkw/.

**Comment by AMBudnik** [comment]
Thank you for taking care of the issue. We can call this issue solved.
