### ISSUE TITLE
How to insert or delete columns?

### ISSUE THREAD

**Issue by Jeff-Tian** [handsontable/handsontable#6068]
### Description

How to insert or delete columns by context menu? I can insert or delete rows but the inserting or deleting columns always disabled, why?

### Steps to reproduce

1.
2.
3.
![image](https://user-images.githubusercontent.com/3367820/60032435-1b346900-96d9-11e9-9f71-491a9b80b163.png)

### Demo

The official demo: https://handsontable.com/examples?headers&context-menu

### Your environment
* Handsontable version:         See the official demo
* Browser Name and version: Chrome
* Operating System:   Windows or Mac

**Comment by AMBudnik** [comment]
It is only disabled when you use an array of objects as a data source or when you use an array of arrays but set the `columns` option.

If you'd like to enable this option for objects you'd need to create a custom context menu item that operates on [`columns`](https://handsontable.com/docs/7.1.0/Options.html#columns).

**Comment by Jeff-Tian** [comment]
@AMBudnik Thank you for the explanation!
