### ISSUE TITLE
Fixed bottom Row is displayed twice when screen is resized

### ISSUE THREAD

**Issue by ashish1697** [handsontable/handsontable#6069]
### Steps to reproduce

1. fixed bottom row one or two
2. resize the screen to 90 or less
3. scroll down, ypu can see the same row twice which is fixed

### Demo

https://handsontable.com/docs/7.1.0/demo-fixing-bottom.html

### Your environment
* Handsontable version:7.1.0
* Browser Name and version: chrome  version 75
* Operating System: windows 10
![pic 1](https://user-images.githubusercontent.com/38009643/60100427-58e7cf00-9777-11e9-882a-6bbb1eac028f.JPG)

**Comment by AMBudnik** [comment]
Hey @ashish1697 

does it sound exactly like https://github.com/handsontable/handsontable/issues/4454?
Please confirm.

**Comment by ashish1697** [comment]
Hi @AMBudnik 
Issue is same, but not sure about the screen resize.

**Comment by AMBudnik** [comment]
It looks like this cause fixedRowsBottom are an extra layer that is added to the table so it can stay on the top. At the same time, it is kept on the bottom of the container so it uses the fixed position. These position settings do not differ where the table ends - they use the container as the relevant object to stick to.

Please track progress to #4454 and if that won't fix your app, we'll reopen this task.
