### ISSUE TITLE
Nested custom header.

### ISSUE THREAD

**Issue by shallwefootball** [handsontable/handsontable#6070]
can’t custom headers in using `nestedHeaders` ref with https://handsontable.com/docs/7.1.0/demo-custom-renderers.html#page-header

so how about this idea. call “nestedCustomHeaders”

```
nestedHeaders: [
  ['A', {label: 'B', colspan: 8}, 'C'],
  function customHeader(col) {
    return ‘some text<button>good</button>’
  } 
]
```

**Comment by AMBudnik** [comment]
Hey @shallwefootball 

you can pass on any HTML to a header - just change `B` to `some text<button>good</button>`.

But... I think that we should improve the `afterGetColHeader` hook. Now it just doesn't really understand that we have multiple headers so it gets pretty complicated to attach the new custom data into desired column header. I guess that this https://jsfiddle.net/handsoncode/179p56yk/ might be the best solution for now.
