### ISSUE TITLE
Horizontal scroll bar changes size when scrolling

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#6072]
### Description
When scrolling horizontally the scroll bar changes size which forces me to grab the scroll bar again to be able to scroll to the end. I don't really know how I can reproduce this issue so I just want to mention it here and see if this is a known issue or if I've missed something obvious.

Otherwise just see this as a friendly notice that this is a thing. =)

### Demo
![handsontable_scroll_issue](https://user-images.githubusercontent.com/3355320/60244307-6b1e5600-98ba-11e9-94d2-896d352e0c48.gif)

**Comment by AMBudnik** [comment]
Hey @ottosson 

can you share your settings or a demo where's we'd be able to replicate the same?

**Comment by AMBudnik** [comment]
Hey @ottosson 

anything new here?

**Comment by ottosson** [comment]
It seems I've been fiddling with the CSS:

```
  .wtHider {
    width: 100% !important;
  }

  .wtSpreader {
    width: 100% !important;
  }
```

Can't quite remember why I put them there to begin with, but removing them fixed the problem.

**Comment by ottosson** [comment]
Actually on closer investigation it didn't help... Don't know why it seemed to work at first.

I've removed all custom styles and still have the same problem. I can't reproduce the bug exactly in Stackblitz but it demonstrates the effect. It's lazy loading columns and changing the scroll bar when they are loaded.

In [this demo](https://stackblitz.com/edit/handsontable-scroll-issue) I still use the .wtHider css, but in my electron app it's removed.

Can I make HoT load all the columns directly?

**Comment by AMBudnik** [comment]
You can try to set [`viewportColumnRenderingOffset`](https://handsontable.com/docs/7.1.0/Options.html#viewportColumnRenderingOffset) for [`instance.countCols` ](https://handsontable.com/docs/7.1.0/Core.html#countCols).

**Comment by wojciechczerniak** [comment]
> It seems I've been fiddling with the CSS:
> 
> ```
>   .wtHider {
>     width: 100% !important;
>   }
> 
>   .wtSpreader {
>     width: 100% !important;
>   }
> ```
> 
> I think I was trying to style the filter window and wasn't specific enough with my css-selectors. Removing them mitigated the problem.

It's `.wtHider` and `.wtSpreader` that are responsible for virtual rendering and scrollbar. `.wtHider` has width in `px` that is calculated total of all columns widths. If you force it with `!important` the scrollbar won't work correctly.

**Comment by ottosson** [comment]
Thanks @AMBudnik that solves my problem until I figure out what I might have done wrong!

Thanks @wojciechczerniak for that explanation. (I've since removed the css in my application but the problem persisted anyway and I wanted to demonstrate the effect in the Stackblitz example.)
