### ISSUE TITLE
Strange datetime behavior

### ISSUE THREAD

**Issue by rvictordelta** [handsontable/handsontable#6073]
### Description
Hello,

Columns with type: 'date' don't play well with datetimes.  I use javascript to load the current date and time and specify dateFormat: 'YYYY-MM-DD HH:mm:ss' into a handsontable cell.  If I edit the value and press tab to move to the next cell, my edits are preserved (as expected).  However, if I edit the value and click on another cell, the time snaps to 00:00:00 while edits to the date portion are preserved.

Thanks!

### Steps to reproduce
1. Enter a datetime value into a cell e.g. '2019-06-27 07:54:24'
2. Edit any component of the datetime
3. Click any where else to conclude the edit, and not that the time component snaps to 00:00:00
4. Note that the time does not snap to 00:00:00 you press tab after editing the cell

### Demo
http://jsfiddle.net/568oqbef/

### Your environment
* Handsontable version: reproduced on 7.1.0
* Browser Name and version: Chrome 74
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hey @rvictordelta 

the `date` and `time` are two separate cell type in Handsontable.
The date-time cell type has been requested here https://github.com/handsontable/handsontable/issues/3505 (the topic will get opened once we'd be ready to work on it).
