### ISSUE TITLE
beforeColumnMove and beforeRowMove to stop move the column or row

### ISSUE THREAD

**Issue by bright21051** [handsontable/handsontable#6075]
I want to manual move row or column.
Before I move, I need to judge whether has any merge cell in my selects, or new position whether I can move to.
So how can I trigger the manualColumnMove/manualRowMove, and not to move?

**Comment by AMBudnik** [comment]
Hey @bright21051 

you can use the `beforeColumnMove` hook and return false

Here's an example https://jsfiddle.net/handsoncode/5ovut9r8/

It should work the same for rows.

**Comment by bright21051** [comment]
@AMBudnik  Thanks! I knew how to do. 
I have another question:
All before hook can return false and will do nothing?

**Comment by AMBudnik** [comment]
Not all, but most. We're working on making them work the same way. If you'd have any case where it doesn't work this way (besides the beforeInit and beforeRender as that's the separate case) let me know.

**Comment by bright21051** [comment]
OK I got it. I will. Thanks a lot.
