### ISSUE TITLE
[7.0.0+] Scrollbar displays only once

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6076]
### Description
When we click the dropdown cell we get a scrollbar for the list of choices but only for the first time. 6.2.2 works fine.

### Steps to reproduce

1. Open a dropdown.
2. Close and open again.
![Kapture 2019-07-01 at 12 01 56](https://user-images.githubusercontent.com/1555809/60428546-582cbe00-9bf9-11e9-9897-32c26cf7a622.gif)

### Demo

https://jsfiddle.net/handsoncode/dfyq8n13/1/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
@pnowak @aninde Can you check this in v8?

Random v8.1.0 test https://jsfiddle.net/93pb0avq/ look ok. But we should check other versions and browsers.

**Comment by pnowak** [comment]
Yes, you right @wojciechczerniak. It works well - https://jsfiddle.net/0d1Le39z/

I checked on Chrome, Safari, FF and Opera.

**Comment by AMBudnik** [comment]
It also works for me on all major browsers. I recommend closing this as solved.
