### ISSUE TITLE
numeric and renderer

### ISSUE THREAD

**Issue by gbelmm** [handsontable/handsontable#608]
how to use and include
type: 'numeric' and 
 type: {renderer: yellowRenderer} 

in cell type

**Comment by najor** [comment]
In version 0.12.6 the <code>Handsontable.NumericRenderer.renderer</code> changed. Now is found under <code>Handsontable.renderers.NumericRenderer</code>, so the function will be like this:

<pre>
function yellowNumericRenderer(instance, td, row, col, prop, value, cellProperties) {
  Handsontable.renderers.NumericRenderer.apply(this, arguments);
  td.style.background = 'yellow';
}
</pre>


Just to save some time if somebody tries.

**Comment by warpech** [comment]
Actually that changed in 0.10, so long time ago. But thanks for udpating!
