### ISSUE TITLE
copy-paste

### ISSUE THREAD

**Issue by stw13813013798** [handsontable/handsontable#6080]
### Steps to reproduce

1. columns:function(){
   return {
      renderer: myRenderer,
      editor: 'customized editor'
  }
}
2. when i use ctrl + c/v  ,it does not work

### Your environment
* Handsontable version: 7.0.3
* Browser Name and version: chrome:72.0
* Operating System: windows

**Comment by AMBudnik** [comment]
Hey @stw13813013798 

Can you attach a demo?

**Comment by AMBudnik** [comment]
I believe that this is no longer an issue as there's no reply for a week.
