### ISSUE TITLE
updateSettings breaks headers

### ISSUE THREAD

**Issue by craigbenstock** [handsontable/handsontable#6081]
### Description
After calling update settings on the table, the headers which were frozen to the top of the table become displaced and render incorrectly when scrolling.

### Steps to reproduce

1. call updateSettings()
2. scroll to the bottom right
3. scroll back up

(best described in fiddle below.)

### Demo
https://jsfiddle.net/cab79/hjxe2tvu/3/

### Your environment
* Handsontable version: latest CDN 7.1
* Browser Name and version: Chrome - Version 75.0.3770.100 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @craigbenstock 

the issue is gone when we comment out the `preventOverflow: 'horizontal'`.
Here are related topics
https://github.com/handsontable/handsontable/issues/4303
https://github.com/handsontable/handsontable/issues/3108
