### ISSUE TITLE
Bug when sorting Handsontable

### ISSUE THREAD

**Issue by patrickluethi** [handsontable/handsontable#6082]
### Description
When i sort the table after globalid and press on a row, the table starts tu bug and complett diffrent row is shown. For example the two images. In the first one I sorted the table after globalid. After that I press on row 3 the table show like in the second image. Does anyone know why? 
![image](https://user-images.githubusercontent.com/37138821/60570538-1410f900-9d72-11e9-9753-6fb1272f70bc.png)
![image](https://user-images.githubusercontent.com/37138821/60570840-a9ac8880-9d72-11e9-9b90-471c9d340733.png)

**Comment by AMBudnik** [comment]
Hey @patrickluethi 

Can you share a demo for this case?

**Comment by AMBudnik** [comment]
I believe that this is no longer an issue as there's no reply for a week.

**Comment by patrickluethi** [comment]
This is still an open problem. We tried to recreate the error on JSFiddle but havent been able to do it yet. We still try to search for a solution.

**Comment by AMBudnik** [comment]
If you have the same code in the app and in the JSFiddle maybe some external scripts are making the change.
Nevertheless, if you'd find anything please send me the feedback at support@handsontable.com
