### ISSUE TITLE
[6.1.0]  The native selection deselects when `fragmentSelection` is used on Chrome 

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#6083]
### Description
The `fragmentSelection` feature doesn't seem to work on Chrome since version `6.1.0` and in Firefox since `0.36.0`.

Also, the test cases ([like this one](https://github.com/handsontable/handsontable/blob/d0aac96b07497347eba7d8307c5b70e0081410f4/test/e2e/settings/fragmentSelection.spec.js#L67)) don't work properly - they return the same results, no matter if `fragmentSelection` is set to `true` or `false` (also, they didn't show, that the feature isn't working properly)

### Steps to reproduce
1. Go to https://jsfiddle.net/bfw06cmg/1/
2. Select the text spanning between cells, for example, "irst sec"

**Result:** In Chrome, after lifting the mouse button the text selection disappears completely, in Firefox it stays selected only in the first selected cell.

**Comment by AMBudnik** [comment]
Inform [forum](https://forum.handsontable.com/t/gh-6083-selected-text-in-cell-loses-text-selection-when-you-let-go-left-mouse-click/3946)

**Comment by AMBudnik** [comment]
We get the same behavior after updating to v8.0.0 https://jsfiddle.net/AMBudnik/hgeozsyL/

**Comment by aninde** [comment]
According to my manual tests, this issue has not been fixed. It is still impossible to mark between the cells on Chrome and Firefox. While on safari it works beautifully as before.

Demo v8.4.0 https://jsfiddle.net/z4n1dm8s/

![chrome](https://user-images.githubusercontent.com/30186818/117174811-6720c080-adce-11eb-8121-be4305639f31.gif)

Not fixed on:
Chrome v90 90.0.4430.93,
Firefox 88.0.0 & 88.0.1 
both on macOS Pro 11.2.3 (20D91)

Example from Safari - where it's working
![safari](https://user-images.githubusercontent.com/30186818/117174824-6b4cde00-adce-11eb-8799-ab9e806f50c3.gif)
