### ISSUE TITLE
Once we enable columnSorting we cannot run the merge() method

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6086]
### Description

Once we enable `columnSorting` we cannot run the merge() method. It erases the data from the merged area but does not add the layer.

![image](https://user-images.githubusercontent.com/10757813/60663783-7b0cdb80-9e60-11e9-8dc4-21e7f06355f5.png)

### Steps to reproduce

1. Comment out the `columnSorting` to see this merged properly

### Demo

https://jsfiddle.net/handsoncode/3ho1dp9m/

### Your environment
* Handsontable version: 7.1.0
_Doesn't seem to be version related._
* Browser Name and version: Chrome 75 
* Operating System: Windows

**Comment by wojciechczerniak** [comment]
Related to `observeChanges`. Disable the plugin and we have merged cell: https://jsfiddle.net/Lxz2t8nm/

**Comment by AMBudnik** [comment]
Fixed with the latest build from @wszymanski 

https://jsfiddle.net/ez6xwm52/ (`8.0.0-rc1 from 14/10`)

**Comment by AMBudnik** [comment]
Works well on the official beta https://jsfiddle.net/Ltqmgyfr/ Thanks!

**Comment by AMBudnik** [comment]
Demo updated to 8.0.0 https://jsfiddle.net/7spw4fkh/ (merge is solved).
