### ISSUE TITLE
numericFormat not work properly

### ISSUE THREAD

**Issue by duanyijie** [handsontable/handsontable#6087]
### Description
![image](https://user-images.githubusercontent.com/16126552/60701390-30599500-9f2e-11e9-8975-70e3d56ec91a.png)

### Steps to reproduce
check the demo

### Demo
https://codepen.io/duanyijie/pen/QXaWOX

### Your environment
* Handsontable version: latest
* Browser Name and version: chrome 74.0.3724.8
* Operating System:win10

**Comment by AMBudnik** [comment]
You're missing the language file @duanyijie 

https://codepen.io/anon/pen/LKBvYw?editors=1010 (added in line `7`).

**Comment by duanyijie** [comment]
Sorry for the bother
