### ISSUE TITLE
Duplicated rows while using manualRowMove with improper index

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6088]
### Description

When we want to pass an index greater than the last index in the table we get duplicated data. The last row is put in the top of the table and it gets the same data as the first previous row. 

I would propose to just abort the action of moving if the index in `manualRowMove` is higher then `countCols()-1`.

The `beforeRowMove` tries to find the index of `9` in the 9-element array.

### Steps to reproduce

1. check the result

### Demo

https://jsfiddle.net/AMBudnik/uh1xm3ys/

### Your environment
* Handsontable version: 7.1.0
_Doesn't seem to be related to any version._
* Browser Name and version: Chrome 75
* Operating System: Mac Mojave

**Comment by AMBudnik** [comment]
Fixed with the latest (25/09/19) build for `8.0.0-rc1`.
![Zrzut ekranu 2019-09-25 o 11 20 17](https://user-images.githubusercontent.com/10757813/65587827-cb3e9a00-df86-11e9-9505-9d46f7f16b31.png)

Updated demo https://jsfiddle.net/Ly7ew5hk/
We no longer get a duplicated row. None of the rows are moved as there's no row with index `16`. There are no console error or toher problems.
Well done!

Previous behavior (7.1.1)
![Zrzut ekranu 2019-09-25 o 11 21 42](https://user-images.githubusercontent.com/10757813/65587833-ce398a80-df86-11e9-8c2e-b0f7d9045f1e.png)

**Comment by AMBudnik** [comment]
Glad to see this fixed in 8.0.0.-beta1 https://jsfiddle.net/s7ahLgoq/

**Comment by pnowak** [comment]
Good news! This issue got solved v8.0.0. Here's an updated demo - https://jsfiddle.net/npxv5cgt/

**Comment by AMBudnik** [comment]
Thanks for checking @pnowak 
We can close this issue as solved.
