### ISSUE TITLE
Replace `mergeSort` with Array.prototype.sort

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6091]
### Description

As the newest browsers implement the stable sort algorithm maybe its time to consider to remove `mergeSort` (https://github.com/tc39/ecma262/pull/1340)? 

What about IE?

### Demo

https://github.com/handsontable/handsontable/blob/master/src/utils/sortingAlgorithms/mergeSort.js

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment]
I'm closing this issue as done and released in Handsontable v12.1.3
