### ISSUE TITLE
how to add a row of data at the bottom

### ISSUE THREAD

**Issue by j770657446** [handsontable/handsontable#6093]
I want to add a row of data at the bottom to count the sum of the data in each column, but I don't want to bind this data to the data source. Is there any good solution?

I hope someone can help me think of a good solution.
Thanks

**Comment by AMBudnik** [comment]
Hey @j770657446 

everything that you add to the table will become a part of the dataset. You'd need to create an additional one-row table with the total to get this done.

**Comment by j770657446** [comment]
thanks
