### ISSUE TITLE
Can this be done to fix the right column?

### ISSUE THREAD

**Issue by j770657446** [handsontable/handsontable#6094]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey @j770657446 

we can only fix the left column. 

If you're interested in this feature please track changes to https://github.com/handsontable/handsontable/issues/1428
