### ISSUE TITLE
headings of columns and rows are not visible

### ISSUE THREAD

**Issue by davs20** [handsontable/handsontable#6098]
### Description
If you use handson table with a step-by-step form created in bootstrap 4.1 and nav components, for some reason the headings of columns and rows are not visible, until you click inside a cell.

##Demo
https://jsfiddle.net/301kyp5f/

### Steps to reproduce

1. Install bootstrap 4.1
2. Install Handsontable
3.Use nav tap of bootrap and create a steps wizard form 
4.On each nav initialize a different handsontable instance with different data. 
5. Go through each step and try each table

### Your environment
* Handsontable version:7.1
*JQuery 3.3.1
* Browser Name and version: Google Chrome V75
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @davs20 

I'm missing a demo here. Can you add one?

**Comment by davs20** [comment]
> Hey @davs20
> 
> I'm missing a demo here. Can you add one?
Yes, I already put it in the original post

**Comment by AMBudnik** [comment]
Can I ask you to record the odd behavior? From the code, it looks just as I would expect.

**Comment by davs20** [comment]
I found this problem in another post and I already know how to solve it, the table must be rendered every time a step is shown, this way my table shows complete

**Comment by davs20** [comment]
the problem its very similar to https://forum.handsontable.com/t/incorrect-behavior-when-using-tables-with-fixed-columns-with-bootstrap-tabs/1852

**Comment by AMBudnik** [comment]
I'm happy that you've found the workaround. 

If you'd need any further help or spot something unusual please send me an email at support@handsontable.com
