### ISSUE TITLE
How to create two handsontable instances in a page

### ISSUE THREAD

**Issue by j770657446** [handsontable/handsontable#6099]

**Comment by AMBudnik** [comment]
Hey @j770657446 

you need to have two separate DIVs as each DIV holds only one instance.

Here is an example https://jsfiddle.net/handsoncode/71rL49kt/

You can use the same settings for both the tables but in the example, I have used two different sets of settings. 

If you'd need anything else or have some questions to this example please write directly to me at support@handsontable.com.

Cheers!

**Comment by j770657446** [comment]
thanks
