### ISSUE TITLE
IE 8 Add New Row Issue

### ISSUE THREAD

**Issue by rohde1jt** [handsontable/handsontable#610]
When adding a new row in IE8, instead of adding the row and expanding the containing `<div>`, the row is added but the `<div>` remains the same height, forcing a vertical scroll bar.

This happens when adding a new row programitcally, from the context menu, or from typing in the spare row.

**Comment by AMBudnik** [comment]
Issue closed cause of:
* no recent replies
* dropped support for Internet Explorer 8
