### ISSUE TITLE
line high wrong view

### ISSUE THREAD

**Issue by Command-Solider** [handsontable/handsontable#6100]
### Description
line high wrong view

### Steps to reproduce

1. press "alt+enter" to make it linebreak  and input content
2.many times repeat 1
3.left serial number col height will be shorter than right data 

### Your environment
* Handsontable version: v7.1.0
* Browser Name and version: Chrome 75.0.3770.100
* Operating System: windows 7

**Comment by AMBudnik** [comment]
Hey @Command-Solider 

> left serial number col height 

this tells me that I should have a demo in your post. Please add one.

**Comment by AMBudnik** [comment]
Hey @Command-Solider 

I think that the issue's already gone as there are no updates, but if I'm wrong please leave a comment and I'll reopen the subject.
