### ISSUE TITLE
Feature Sorting by row Headers

### ISSUE THREAD

**Issue by IgorFIE** [handsontable/handsontable#6101]
### Description
In our software we created a rotated version of a normal table, so instead of having Column Headers, and data by rows, we have Row Headers with data by columns.

![Screenshot from 2019-07-11 09-55-29](https://user-images.githubusercontent.com/17085338/61037005-20c0cd00-a3c2-11e9-8fe9-72516807c81e.png)

We notice that Row Headers don't have a sorting by Row, Is it possible to have this option? Or a option to rotated a table (converts an existent table to a rotated version, and uses all the definitions done to the normal one, but in a rotated way)?

(Also having a lot of performace problems since we have lots of columns, and we need to have autoColumnSize set to true, we may need a function like "renderAllColumns" so we can set it to false. Even if we use "viewportColumnRenderingOffset" as true, it takes lots of time to load a chart, since it needs to calculate all the column sizes).

**Comment by AMBudnik** [comment]
Hey @IgorFIE 

we have a helper that translates columns to rows but it's only for data. We haven't thought about creating a row sorting as well.

What you can do is use the native JS. 

1) get the data from [`getDataAtRow`](https://handsontable.com/docs/7.1.0/Core.html#getDataAtRow), 
2) remove the row with [alter ](https://handsontable.com/docs/7.1.0/Core.html#alter)method.
3) sort the array via [native JS](https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Obiekty/Array/sort) and 
4) change the dataset accordingly (modify the data array, `loadData` method).

That's the theory. It should work, but if not and something goes wrong just let me know. That's an interesting case and I hope you'll be able to get a decent hack for it.

**Comment by IgorFIE** [comment]
I know that I can do something like that, but we can't just implement a hack because it's a "hack", that means we need to maintain it if there is an update from handsontable. 

We are actually stuck on handsontable 4.0.0, because we did a hack that we saw on one of your issues, and because of that now a lot of our stuff breaks if we try to upgrade.

At the moment we don't need that functionality (that's why I reported it as a feature, with other possible enhancements you guys may also consider), when the time comes if handson as a solution would be perfect, if not I'll do the "hacking".

**Comment by AMBudnik** [comment]
> We are actually stuck on handsontable 4.0.0, because we did a hack that we saw on one of your issues, and because of that now a lot of our stuff breaks if we try to upgrade.

and what was that? Maybe it has been already fixed.

**Comment by IgorFIE** [comment]
> and what was that? Maybe it has been already fixed.

https://github.com/handsontable/handsontable/issues/4454
https://github.com/handsontable/handsontable/issues/4370

**Comment by AMBudnik** [comment]
So I guess that for #4454 you're changing the height of the table by checking the `getLastVisibleRow` and  `instance.countRows()` and changing the height via `updateSettings`?

For the #4370 we might have a change after introducing[ the index mapper](https://github.com/handsontable/handsontable/issues/5112), as this issue looks like a incorrect index being returned.

**Comment by IgorFIE** [comment]
> So I guess that for #4454 you're changing the height of the table by checking the getLastVisibleRow and instance.countRows() and changing the height via updateSettings?

Yes

**Comment by IgorFIE** [comment]
> So I guess that for #4454 you're changing the height of the table by checking the getLastVisibleRow and instance.countRows() and changing the height via updateSettings?

Yes

**Comment by IgorFIE** [comment]
Oh I accidentally closed this...

> So I guess that for #4454 you're changing the height of the table by checking the getLastVisibleRow and instance.countRows() and changing the height via updateSettings?

Yes

**Comment by AMBudnik** [comment]
you wrote the hacks gets you stuck with v `4.0.0`. What's the hack for #4370 that is stopping you from updating?

**Comment by IgorFIE** [comment]
#4454 - we used a hack that dosaki wrote, if the original issue is fixed then we don't need the hack and we can upgrade. 
#4370 - we don't use a hack but we just move any hidden column to the beginning

#4370 is not a show stopper, but #4454 is, because the API that we use in the hack is gone or not having the same behavior, and the issue is not fixed on latest versions

**Comment by AMBudnik** [comment]
Thank you for sharing this proposition and all the ideas.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback. 
See you there!
