### ISSUE TITLE
Wrong typings in CopyPaste plugin

### ISSUE THREAD

**Issue by talamaska** [handsontable/handsontable#6102]
### Description
I'm breaking the process of pasting with a modal dialog if the columns of the copied data are more thant my table. If the users confirms, I slice the data, and I try to perform manual paste
I'm calling ```this.hotInstance.getPlugin('copyPase').paste(sliceddata)```
the problem is that typescript is finding this
```
copy(triggeredByClick?: boolean): void;
cut(triggeredByClick?: boolean): void;
paste(triggeredByClick?: boolean): void;
```
while in the code of the plugin i clearly see this is not the case 
https://github.com/handsontable/handsontable/blob/master/src/plugins/copyPaste/copyPaste.js#L184 
```cut()```
and 
https://github.com/handsontable/handsontable/blob/master/src/plugins/copyPaste/copyPaste.js#L274
``` paste(pastableText = '', pastableHtml = pastableText) { ```

I need some whay to do it manually.

### Your environment
* Handsontable version: 7.0.1
* Browser Name and version: Chrome 69 electron 4.1.5
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing, We'll check it out.

**Comment by AMBudnik** [comment]
Sorry, for keeping you waiting, I'm not a TypeScript expert 🐤 but asked our devs for feedback and you're 100% right - we should change that.
Wouldn't it too much to ask for a pull request?

**Comment by talamaska** [comment]
sure, there you go

**Comment by AMBudnik** [comment]
@talamaska I'm happy to notify you that we've made a couple of improvements to the .ts file in the newest version 7.2.0 - published today.

Here's a full list of changes https://handsontable.com/docs/7.2.0/tutorial-release-notes.html
