### ISSUE TITLE
How to connect two handsontables without gaps

### ISSUE THREAD

**Issue by j770657446** [handsontable/handsontable#6104]
![image](https://user-images.githubusercontent.com/48500891/61097526-3996b480-a48e-11e9-8259-8e5b4261c707.png)

**Comment by wojciechczerniak** [comment]
Please use issue template and add a working jsfiddle example. Otherwise we cannot help you.

**Comment by AMBudnik** [comment]
Hey @j770657446 

@wojciechczerniak is right, we'd need a demo to check what styling is used. By default, the DIVs with tables are places one after another https://jsfiddle.net/AMBudnik/qntdjo2f/

![Zrzut ekranu 2019-07-15 o 09 51 27](https://user-images.githubusercontent.com/10757813/61201875-22520400-a6e6-11e9-8923-e55702a94d48.png)

**Comment by AMBudnik** [comment]
As there's no demo I think that you might already solve the issue, but if there's still something we can help you with please leave a comment.
