### ISSUE TITLE
HOT-in-HOT cell type and Readonly

### ISSUE THREAD

**Issue by nethore** [handsontable/handsontable#6105]
### Description
Hi,
I was wondering if it is possible to setup a cell that is readonly with a type "handsontable".
It would be very useful for us to give possibility to the user to navigate through history of a cell by displaying another table with previous values for each cell.

So it would not be use as selector but only as a viewer.

### Steps to reproduce
1. Set a cell as readonly = true and type = "handsontable"
2. Impossible to open the hot-in-hot

**Comment by AMBudnik** [comment]
Hey @nethore 

You can use `beforeChange` hook

 ```
beforeChange: function(){
    	return false
    }
```
to show the list but do not allow to make a change.

**Comment by nethore** [comment]
Thanks a lot, very useful :)
