### ISSUE TITLE
Dropdown data problem on bottom row

### ISSUE THREAD

**Issue by chanh2505** [handsontable/handsontable#6108]
### Description
I have a dropdown column. And my problem happens when I choose data on rows near bottoms. The datasource only shows 1-2 options. I need the dropdown can show more.
I think it is covered by the below div. 
I try to set the options with preventOverflow but it not working.
Please see more with this: 
[https://jsfiddle.net/chanh2505/90vkn3L4/19](url)
![image](https://user-images.githubusercontent.com/19482911/61195724-2c7aff00-a6f4-11e9-8e9a-7aa09a22d193.png)

**Comment by AMBudnik** [comment]
Hey @chanh2505 

there's a DIV which is scrollable. The list is as long as the container.

![Zrzut ekranu 2019-07-15 o 08 26 58](https://user-images.githubusercontent.com/10757813/61198453-6808cf80-a6da-11e9-8c2c-4c1db4cca9fd.png)

**Comment by chanh2505** [comment]
Yes @AMBudnik ,
I know that, because in my form has many parts. So I need a parent div to limit the handsontable height.
Or if you use the option height, the row in bottom will not display all dropdown data.

**Comment by AMBudnik** [comment]
I think that you can track changes to this topic https://github.com/handsontable/handsontable/issues/5954 - that should meet the requirements.
We do not want to duplicate the tickets so please add a comment in `5954` if in your opinion anything's missing.
