### ISSUE TITLE
Allow to move the cells (Excel-like)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6109]
### Description

There's a feature of moving cells (not whole rows or columns) in Excel. I got a hint that we could add this functionality to Handsontable.

![move-feature](https://user-images.githubusercontent.com/10757813/61200209-f6804f80-a6e0-11e9-910f-08cbcb1f91b6.gif)

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: n/a
* Operating System: n/a

`inform Zen #23165`

**Comment by PeterIttner** [comment]
👍 
Any ideas when this if this is going to be implemented anytime soon?

**Comment by AMBudnik** [comment]
That's a big change that might have to need a new plugin implemented.
I'll let you know as soon as we'll move forward with the subject.

**Comment by PeterIttner** [comment]
I think that is would be similar to the autofill plugin.
It would be great to know if and when it's on your roadmap.

**Comment by PeterIttner** [comment]
Any Update here? Can I expect anything in the next 3 month?

**Comment by AMBudnik** [comment]
Hey @PeterIttner 

I am sorry but we have scheduled work for another 2 months ahead. And planning a new feature usually takes more time than fixing bugs.

**Comment by keyserfaty** [comment]
Any idea when this could be implemented?

**Comment by AMBudnik** [comment]
We do not add any new feature now (Q1/2019) as we are processing two very complex projects: stable 8.0.0 and new formula engine.
Nevertheless, I highly encourage to leave emotes. Once we have a planning meeting that's the easiest way to count the users' votes.

**Comment by AMBudnik** [comment]
Thank you for sharing ideas on my issue.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback. 
See you there!
