### ISSUE TITLE
License suggestion for R community: rhandsontable

### ISSUE THREAD

**Issue by trshafer** [handsontable/handsontable#6110]
In the `R` programming language, there is a library for importing `handsontable` into an `R` application for easy table manipulation. The library is a relatively small shim for passing JavaScript options from `R` to `handsontable`.

Library package: https://cran.r-project.org/web/packages/rhandsontable/index.html
Github source: https://github.com/jrowen/rhandsontable

Since the license migration from 6.x to 7.x, we would appreciate some guidance for how best to proceed on keeping `handsontable` up to date. While I have addressed the technical change of supporting `7.1.0`, the `rhandsontable` author and community is unsure for how the `handsontable` authors would like for `rhandsontable` to proceed.

* Technical change of updating to `7.1.0`: https://github.com/jrowen/rhandsontable/pull/318
* Dialog discussing updating to `7.1.0`: https://github.com/jrowen/rhandsontable/issues/317

In this specific example, the [7.0.1 release](https://github.com/handsontable/handsontable/releases/tag/7.0.1) of `handsontable` addressed an issue when embedded within an `<iframe>`, and a `rhandsontable` user is running into this bug of the currently included `handsontable` `6.1.1` version.

Thanks for your excellent `handsontable` library and we look forward to working with you on how the `R` community can best keep up to date, given the new license changes. @jrowen, anything you would like to add?

**Comment by jrowen** [comment]
I think this is a great summary of the current situation.

**Comment by wojciechczerniak** [comment]
Hi @trshafer, @jrowen,

Thanks for contacting us and the kind words guys. You did great job for R community and naturally we would love to see the project continued. I've run this issue through the team and we think that the best option is to look at `rhandsontable` as any other language/framework wrapper. Currently we have three that are actively maintained: [`@handsontable/react`](https://github.com/handsontable/react-handsontable), [`@handsotnable/angular`](https://github.com/handsontable/angular-handsontable)  and [`@handsontable/vue`](https://github.com/handsontable/vue-handsontable-official). 

You can check any of them how we're doing this, but basically: each is licensed under the MIT license and the Handsontable is a dependancy that the developer has to install separately (package.json `peerDependencies`). He can install earlier MIT version  `<= 6.2.2` or newer `> 7.1.0` branch with the correct `licenseKey`. If he chooses to use the latest it's up to him to choose `non-commercial-and-evaluation` license or buy one for commercial purposes.

Is it something that is possible with R package management?

The PR jrowen/rhandsontable#318 unfortunately is not enough. It contains a copy of Handsontable 7.1.0 without its LICENSE file. This can indicate that Handsontable code is licensed under https://github.com/jrowen/rhandsontable/blob/master/LICENSE or as stated in https://github.com/jrowen/rhandsontable/blob/master/LICENSE.note that it's licensed under MIT which no longer is true. This can mislead `rhandsontable` community into loading proprietary software into their projects.

----

Examples how it looks like in other wrappers are here: [https://handsontable.com/docs/7.1.0/tutorial-license-key.html](https://handsontable.com/docs/7.1.0/tutorial-license-key.html) If you need to link to the details on licensing: [https://handsontable.com/docs/7.1.0/tutorial-licensing.html](https://handsontable.com/docs/7.1.0/tutorial-licensing.html) and we provide an overview in our readme: [https://github.com/handsontable/handsontable#license](https://github.com/handsontable/handsontable#license)

**Comment by trshafer** [comment]
Thanks for the detailed information, that's really helpful. Additionally the license instructions provided in https://github.com/handsontable/react-handsontable#license is a helpful starting point. 
I will absolutely update https://github.com/jrowen/rhandsontable/pull/318 to ensure the LICENSE file is included next to the source of `handsontable`. We'll take a look at the other wrappers and the documentation provided.

**Comment by trshafer** [comment]
I have updated the PR to include the `LICENSE.txt` file in every location of `handsontable` assets and updated the information in the `Readme.md` and `License.note` file. I have added instructions for installing a previous version of `rhandsontable` which will lock them to the currently supported `handsontable` of `6.1.1`.

**Comment by wojciechczerniak** [comment]
@trshafer Great work! Looks like you've solved the puzzle.

Please, don't hesitate to contact us if you have any further questions.
