### ISSUE TITLE
Cleanup tests from pending specs

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6111]
### Description

Currently, Handsontable contains 41 pending specs which are not touched for years. It should be revised if that tests can be enabled or if they should be removed.

The same for Walkontable tests - there are 8 pending tests.

### Steps to reproduce

1. `npm run test:e2e`

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Still no improvement. We have 45 pending tests in v8.2.0

**Comment by swistach** [comment]
This issue is closed temporarily. We will reopen it for development as it became a part of the test environment improvements task reported at #7581
