### ISSUE TITLE
We can show row/columns when they're all hidden

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6113]
### Description

When we hide all the columns (for example with the context menu) there’s no way to get them back. 
You even cannot do the **undo**. 

### Steps to reproduce

1. Hide all the columns
2. Try to make them show

### Demo

https://jsfiddle.net/handsoncode/fkwyj4c3/

### Your environment
* Handsontable version: 7.1.0
_works the same way from the beginning_
* Browser Name and version: Chrome 75
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Doesn't seem to be fixed in develop https://jsfiddle.net/v20r1dnq/ (beta2 develop branch from 28th of April)

**Comment by AMBudnik** [comment]
**Solved** with 8.0.0-beta2-rev2 https://jsfiddle.net/wf4d8stv/

![](https://user-images.githubusercontent.com/10757813/81397455-a8cd4b80-9127-11ea-904b-d023fd9cc9cc.gif)

**Comment by aninde** [comment]
Updated demo v8.0.0 https://jsfiddle.net/aninde/Lj0d1y82/. Still works well.
We can show hidden rows or columns even when all of them are hidden. Issue solved.
