### ISSUE TITLE
Typo in viewportColumnCalculatorOverride function

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6115]
### Description

While refactoring Walkontable renderer I've spotted that in the `viewportColumnCalculatorOverride` function is a typo. In this line, https://github.com/handsontable/handsontable/blob/master/src/tableView.js#L585 `startRow` should be changed to `startColumn`. This bug causes the wrong virtual DOM calculation for columns.

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: any
* Operating System: any

**Comment by wszymanski** [comment]
Updated

There is problem within `viewportColumnCalculatorOverride` method:

https://github.com/handsontable/handsontable/blob/a58d4e235c90bb896d7d7488b7a00c197cffa1a4/src/tableView.js#L839

first, mentioned below line:

https://github.com/handsontable/handsontable/blob/a58d4e235c90bb896d7d7488b7a00c197cffa1a4/src/tableView.js#L857-L858

**Comment by aninde** [comment]
Check during performance benchmark of the v8.4.0.

**Comment by AMBudnik** [comment]
Issue closed as solved in [v8.4.0](https://github.com/handsontable/handsontable/issues/7998)
