### ISSUE TITLE
How to get each column totals at the bottom inside Handsontable ?  Please Help Urgently

### ISSUE THREAD

**Issue by senniksoft** [handsontable/handsontable#6116]
### Description
I can get each column totals with filters enabled as an example in the demo but the problem is I want to show each column totals at the bottom of the table. I 've tried minSpareRows to add an empty row at the end of the table in order to set each column totals but it does not work with filters. Another approach I 've tried was to add an empty row at the end of the table so as to set each column totals but when filter applied it is removed. So please show me a way to handle this problem and let me show a row with each column totals at the bottom with filters enabled.

I 've read all Github issues and forums regarding this problem but cannot find a useful example.

### Advanced Demo with each column totals calculation with filters enabled.
https://jsfiddle.net/fatihsennik/Lwem0r3o/81/

### My environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome Latest
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @senniksoft 

if you're printing the summaries outside the Handsontable you'll need to use plain javascript. 

You can check this great example list on SO https://stackoverflow.com/questions/1230233/how-to-find-the-sum-of-an-array-of-numbers

The arrays of values for the calculation can be delivered by calling the [`getDataAtCol` method](https://handsontable.com/docs/7.1.0/Core.html#getDataAtCol). Be sure, though to check if the values are all `numeric` type.

**Comment by senniksoft** [comment]
Thank you for your answer. However, in the demo, I am already calculated each column totals based on column numeric type, the problem is how to show them inside handsontable as a row at the bottom?

**Comment by AMBudnik** [comment]
Have you tried https://handsontable.com/docs/7.1.0/demo-summary-calculations.html ? It sounds like something that you may want to try.

**Comment by senniksoft** [comment]
Dear Aleksandra. Yes, I also tried that but it does not work with the filter enabled and eventually, after two days of hard hacking I was able to sum each column totals at the bottom inside handsontable by appending custom tfoot. Here is the Demo; https://jsfiddle.net/fatihsennik/Lwem0r3o/99/ However, now the problem is my table contains more than 20 columns and when I scroll horizontally handsontable, the sum row is not moving along with handsontable. How to solve this problem? I 've spent too much time on this and cannot complete this for production.  Please help me.

**Comment by AMBudnik** [comment]
Hey @senniksoft what do you think about this one https://jsfiddle.net/handsoncode/ze4dh5mp/ ?

**Comment by senniksoft** [comment]
Dear Aleksandra.  Thank you for your answer. However, By using two separated instance of the handsontable caused problem to scrollbar problem between two instances when the first table needs a horizontal scroll and another problem is that columns resize in the first table will not alter second sum table columns size dynamically and also below the sum table will not behave like the way fixedRowsBottom property and it will be not handy when table rows exceeds thousands of rows.

**Comment by AMBudnik** [comment]
Yes, that's true - it is not fixed and you'd need to add a couple of callbacks to copy the changes from the table1.

**Comment by senniksoft** [comment]
Dear Aleksandra. Thank you for your quick answer. Here's the demo that I was able to scroll horizontally after appending sum row inside #container .ht_master .wtHolder https://jsfiddle.net/fatihsennik/Lwem0r3o/105/
How to stick this sum row at the bottom?
What I tried was to change a div position to sticky, actually, it did the job but removed horizontal scroll again due to position sticky drawbacks. Here 's the demo with sticky position;
https://jsfiddle.net/fatihsennik/Lwem0r3o/108/
I am very close to a solution please help :)

**Comment by senniksoft** [comment]
?

**Comment by AMBudnik** [comment]
It's obviously nothing that we would find the official API. I guess the 'position' is the one to use, but you may want to use two containers where one sticks to the fixed height and another one that can be scrolled.

**Comment by senniksoft** [comment]
Thank you for the suggestion I will also try that but in order to scroll them horizontally at the same time I need to detect horizontal scroll on Handsontable by getting scrolled width or I need to attach jquery scroll event to the table to get the same result. At the moment I can only detect scroll event by the following API;
`hot.addHook("afterScrollHorizontally", function () {});`
How to get scrolled width? or how to attach jquery scroll event to the table?

**Comment by AMBudnik** [comment]
You can track the first and the last visible column
https://handsontable.com/docs/7.1.0/AutoColumnSize.html#getFirstVisibleColumn
https://handsontable.com/docs/7.1.0/AutoColumnSize.html#getLastVisibleColumn

and when you want to scroll the table then it's [scrollViewportTo](https://handsontable.com/docs/7.1.0/Core.html#scrollViewportTo)

**Comment by AMBudnik** [comment]
I guess that we can close the topic as there are no updates. If you have some additional questions Fatih, feel free to send me an email at support@handsontable.com

**Comment by senniksoft** [comment]
Dear Aleksandra. Thank you for your solutions. it helped a lot.
