### ISSUE TITLE
I would like to know how to listen to right-click delete a row of data？

### ISSUE THREAD

**Issue by Protagonistss** [handsontable/handsontable#6117]
### Steps to reproduce

1. I set the right-click menu to delete a row of data  in the vue project
2.But the deleted data cannot be retrieved, No trigger(afterChange)
3. Please reassure

### Your environment
* Handsontable version: 7.1
* Browser Name and version: google chrome
* Operating System: mac os

**Comment by AMBudnik** [comment]
Hey @Protagonistss 

the [`beforeRemoveRow` hook ](https://handsontable.com/docs/7.1.0/Hooks.html#event:beforeRemoveRow)should meet your requirements.  And here's an example http://jsfiddle.net/handsoncode/uhq0jx9y/
