### ISSUE TITLE
twitter typeahead.js

### ISSUE THREAD

**Issue by gbelmm** [handsontable/handsontable#613]
Is it possible to user this component has many more options than the bootstrap?

https://github.com/twitter/typeahead.js

http://twitter.github.io/typeahead.js/examples/

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
