### ISSUE TITLE
Calling `setState` in some event handlers triggers full recalculation of formulas

### ISSUE THREAD

**Issue by reneegyllensvaan** [handsontable/handsontable#6132]
### Description

We're using Handsontable with the formula plugin and the react wrapper. We're running into severe performance issues because of constant full recalculations. Apparently calling  `setState` in any parent component of the Handsontable react wrapper seems to trigger a `loadData` event, which in turn causes a full recalc of the spreadsheet. This is causing major performance issues in the parts of our application that use the component. 

### Steps to reproduce

1. Handle some event from handsontable
2. Call `this.setState` on a parent component somewhere

### Demo

http://jsfiddle.net/a4pv8r9k/

### Your environment
* Handsontable version: 7.0.3
* Browser Name and version: Firefox 68.0 and Chrome 75.0.3770.142
* Operating System: OSX

**Comment by AMBudnik** [comment]
Hey @reneegyllensvaan 

I'm closing this issue as the demo is not in React and this repository is made for the Vanilla version.

As it doesn't reflect any particular issue I really would like you to send me a demo with your project (can be only Handsontable with fake data) at support@handsontable.com
It will be much easier to share some ideas.

**Comment by reneegyllensvaan** [comment]
For reference, I accidentally linked the wrong Jsfiddle on this, here's the one with the issue reproduced: https://jsfiddle.net/c1o7pbLv/
