### ISSUE TITLE
How to download handsontable/vue@3

### ISSUE THREAD

**Issue by j770657446** [handsontable/handsontable#6134]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @j770657446 

Here's a tutorial for loading Handsontable 7.1.0 with the Vue wrapper https://handsontable.com/docs/7.1.0/frameworks-wrapper-for-vue-installation.html
The current Vue version for the wrapper is [Vue 2.5.0](https://github.com/handsontable/vue-handsontable-official/blob/master/package.json) and the general Vue version is [2.6.10](https://github.com/vuejs/vue/releases).

The Vue 3 itself is not ready yet, [it is planned for 2020](https://mdbootstrap.com/vue-3/).
