### ISSUE TITLE
Why my nestedHeaders don't work

### ISSUE THREAD

**Issue by j770657446** [handsontable/handsontable#6136]
nestedHeaders: ['A', 'C', 'C', 'C', 'C', 'C'],   it  did‘t work

**Comment by AMBudnik** [comment]
Hey @j770657446 

The [`nestedHeaders`](https://handsontable.com/docs/7.1.0/demo-nested-headers.html) option keeps an array of arrays https://jsfiddle.net/AMBudnik/84sdaxtk/

**Comment by j770657446** [comment]
![image](https://user-images.githubusercontent.com/48500891/61523323-b43f7100-aa46-11e9-8571-c889e768bdd8.png)
![image](https://user-images.githubusercontent.com/48500891/61523343-c3262380-aa46-11e9-8600-c5724d0454eb.png)
I still don't know how to solve the problem. Maybe I should go up to the latest version.

**Comment by AMBudnik** [comment]
For v 7.1.0 the

`nestedHeaders: ['A', 'C', 'C', 'C', 'C', 'C']`

looks like this 

![Zrzut ekranu 2019-07-19 o 11 25 06](https://user-images.githubusercontent.com/10757813/61524993-e1285f80-aa17-11e9-84d7-d4911160c066.png)

What we see in the screenshot are actually `colHeaders` (the line under the `nestedHeaders`).

What version of Handsontable do you use? It looks like you're on CE (< 7.0.0).

**Comment by j770657446** [comment]
my CE  (< 7.0.0)  How to achieve the header

**Comment by AMBudnik** [comment]
`NestedHeaders` option for version [< `7.0.0`](https://handsontable.com/docs/6.2.2/demo-nested-headers.html) was only a part of Handsontable PRO. It means that you should purchase a license for the software. If you are still testing the software you should update to `7.0.0+` and use the evaluation `licenceKey`.

**Comment by j770657446** [comment]
Ok 
Thanks for your advice

**Comment by AMBudnik** [comment]
You're welcome.
