### ISSUE TITLE
How to save and load data when columns settings is set?

### ISSUE THREAD

**Issue by felixOvianet** [handsontable/handsontable#6137]
### Description
When the `columns` attribute of the grid `settings` is not set, everything is working fine.
But when the `columns` attribute of the grid `settings` is set to validate the data's format it looks like it's impossible to load the data. Why is that?

### Steps to reproduce
1. Go to this fiddle: https://jsfiddle.net/scdbzrv5/1/
2. Modify the grid and hit save
3. The grid is reset. Then click 'load the previously saved data': everything is fine.
4. Uncomment  the `columns` attribute of the grid `settings` and re-run the fiddle. Then restart from point 2.
5. Datas cannot load at point 3.

### Demo
https://jsfiddle.net/scdbzrv5/1/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Firefox 68.0
* Operating System: macOs Mojave 10.14.5

**Comment by AMBudnik** [comment]
Hey @felixOvianet 

it works well on my Mojave/Chrome 75 https://jsfiddle.net/AMBudnik/znxasq2g/
I just needed to comment out `data` for `columns` as the data source is an array `Handsontable.helper.createSpreadsheetData(4, 4)` not an object. 

![demo](https://user-images.githubusercontent.com/10757813/61535440-9405b700-aa32-11e9-8fb3-c8583393e11c.gif)

Am I missing something?

**Comment by felixOvianet** [comment]
What if you don't comment out the `data` for `columns`?
I mean, is it possible to save the datas as a mapped object?
Because `this.hotRegisterer.getInstance(this.id).getData();` only return a simple array.
(I hope i'm clear enough, sorry).

**Comment by AMBudnik** [comment]
It should be possible by the use of [dataSchema](https://handsontable.com/docs/7.1.0/Options.html#dataSchema). But it doesn't work in this example https://jsfiddle.net/AMBudnik/5dkaz1r3/
I'll check it out and get back to you.

**Comment by AMBudnik** [comment]
Hey @felixOvianet 

I just got a feedback from our developer and he told me that you'd need to save this data (possibly by the `afterChange` hook) to get this working.

**Comment by felixOvianet** [comment]
Hi @AMBudnik,
thank you for your answer, does this mean you cannot use `this.hotRegisterer.getInstance(this.id).getData();` to export the datas?

**Comment by AMBudnik** [comment]
[`getData` ](https://handsontable.com/docs/7.1.0/Core.html#getData)is used to gather all the data that is presented in the table (with sorting, moving applied). And, as mentioned before, it works well with array data. But, it gets lost when you refer to columns > data without actually sharing the data.

**Comment by felixOvianet** [comment]
Thank you, that helped a lot. I'm closing the issue, since this is not one.
