### ISSUE TITLE
CustomBorders plugin in React HotTable do not change borders of a cell once it is inited

### ISSUE THREAD

**Issue by imageslr** [handsontable/handsontable#6139]
### Description

In react `HotTable` component, when `customBorders` props is updated, the borders of a cell will not change once it is inited.

For example, if I have a cell border config like this:
```js
  customBorders: [{
        row: 1,
        col: 2,
        left: {
          width: 5,
          color: 'red'
        }
      }, {
        row: 2,
        col: 2,
        left: {
          width: 5,
          color: 'red'
        }
      }]
```

Then I change border in (1, 2) to this:
```js
    customBorders: [{
      	row: 1, 
        col: 2,
        left: {
          width: 10,
          color: 'blue'
        }
      }]
```

The border at cell (1, 2) will remain the same as before: `red`, instead of `blue`. 

However, if I at first run `clearBorders()` then updateSettings, things will be right.

### Demo
https://jsfiddle.net/0ptfdvy7/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome latest
* Operating System: Mac OS 10.14

**Comment by AMBudnik** [comment]
Please fill the demo. It lacks the logic of the borders.

**Comment by imageslr** [comment]
Sorry I pasted a wrong link. I have update the demo.

**Comment by AMBudnik** [comment]
Thank you for updating the example, however, I do not see anything improper here.

The `clearBorders` method is the one you should call to remove the previously changed cells 

> Clear custom borders.
....
// Using without param - clear all customBorders.
customBordersPlugin.clearBorders();

and you are using it the correct way in the `clearAndSetBorders` method.

![fine](https://user-images.githubusercontent.com/10757813/61625492-2ac4b480-ac7b-11e9-9111-fe261263c888.gif)

**Comment by imageslr** [comment]
Thank you. The problem I said is that if I click `setBorders` button, the state will change to:
```js
customBorders: [{
      	row: 1, 
        col: 2,
        left: {
          width: 10,
          color: 'blue'
        }
      }]
```

So the border should be `10px` and `blue` color. However, the border at cell (1, 2) is still **5px** and **red**. 

I mean since `HotTable` is a react component, isn't its view binding to its state? If I update the `customBorders` in state to: `..., {width: 10, color: 'blue'}, ...`, the border should update to `10px` and `blue`  automatically without using `clearBorders()`. 

Thank you again for your rapid response.

**Comment by AMBudnik** [comment]
Hey @imageslr 

I just got an update from our developer

> `setBorders `from user app isn't the same as `setBorders `from `customBorders `plugin.
> So the Client changes only the state of his app. He needs to use the method from our plugin - https://jsfiddle.net/0b4nvm8a/

**Comment by imageslr** [comment]
Thank you! It's very clear. I think I can clear all borders in `componentWillUpdate` method so that I don't need to handle this plugin's appearance additionally.

```js
  componentWillUpdate() {
    this.hot && this.hot.getPlugin("customBorders").clearBorders();
  }
```
