### ISSUE TITLE
`scrollViewportVertically` scrolls too far on Windows, causing 2 tests to fail

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6141]
### Description
PR https://github.com/handsontable/handsontable/pull/6128 revealed that there is a problem with the method `wtScroll.scrollViewportVertically`. This method seems to scroll 1 pixel too far on Windows, causing the first cell to be incompletely visible. This causes two tests to fail:

![image](https://user-images.githubusercontent.com/566463/61632609-8d26b080-ac8d-11e9-9b8d-888bdf1c9d9f.png)

### Steps to reproduce

1. Run Walkontable test suite on Windows
2.
3.

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome 75
* Operating System: Windows

**Comment by swistach** [comment]
Fixed in v7.2.0 - E2E tests should be stable on Windows. Thank you @warpech!
