### ISSUE TITLE
a mistake in handsontable.d.ts

### ISSUE THREAD

**Issue by swk777** [handsontable/handsontable#6142]
### Description

"userHeaders" should be "useHeaders"
![Screen Shot 2019-07-23 at 11 57 45](https://user-images.githubusercontent.com/1302797/61690106-240d6e80-ad5b-11e9-9f08-3626f46e0fb6.png)

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Thank you for sharing @swk777 the PR is ready.

**Comment by AMBudnik** [comment]
Hey @swk777 

this issue just got fixed. It is available in v 7.1.1
