### ISSUE TITLE
Property `culture` in `numericFormat` not working when set to other language

### ISSUE THREAD

**Issue by imageslr** [handsontable/handsontable#6145]
### Description

Hi, I'm using webpack to develop handsontable. I have set a cell's type as "numeric" and I want it to format with Chinese currency `RMB`:
```js
{
  type: "numeric",
  numericFormat: {
    pattern: "$0,0",
    culture: "zh-CN"
  }
}
```

But it's not working. Rendered text of the cell was still `$123.00` rather than `￥123.00`.

I know it's because of the lack of `numbro`'s language file, but I don't know how to import it in a webpack project.

I have tried following steps, they all failed:
1. add `script` in `pageframe.html`:

```html
<script src="http://handsontable.com/docs/7.1.0/components/numbro/dist/languages.min.js"></script>
```

2. import numbro's language file in the beginning of `index.tsx`:

```js
import 'numbro/dist/language.min.js' // This indeed be imported, I logged it
```

I would appreciate it if you could please tell me how to solve this problem.

**Comment by imageslr** [comment]
I have also copied the content of [this link](https://handsontable.com/docs/7.1.0/components/numbro/dist/languages.min.js) ( shown in the jsfiddle demo of the [document](https://handsontable.com/docs/7.1.0/demo-numeric.html)) to a js file `languages.js` in my project, and import this file in `index.jsx`. Still not working.

**Comment by AMBudnik** [comment]
Hey @imageslr 

can you send over a demo? If it's confidential you can send it on the emails (support@handsontable.com). While using the latest version of Handsontable it works as expected https://jsfiddle.net/handsoncode/6wb5m1xy/ 
I've just changed the `en-US` culture to `zh-CN` from the official numeric example https://handsontable.com/docs/7.1.0/demo-numeric.html

**Comment by imageslr** [comment]
Hello @AMBudnik , I have created a simple demo with `create-react-app`. The project has been uploaded: [handsontable-i18n-test.zip](https://github.com/handsontable/handsontable/files/3431186/handsontable-i18n-test.zip)

```
cd handsontable-i18n-test
yarn
yarn start
```

 As you can see, I moved the official numeric example code into my react component, but the currency symbol was still wrong. 

![image](https://user-images.githubusercontent.com/17822028/61869789-1d275d00-af0f-11e9-8acb-70eb328f596d.png)

**Comment by imageslr** [comment]
Hi, I've found a solution at https://github.com/handsontable/handsontable/issues/6145 . Add these lines in entry file should set languages correctly.

```diff
// index.tsx
import * as React from "react";
import { HotTable } from "@handsontable/react";
...

+ import numbro from "numbro";
+ import languages from "numbro/dist/languages.min.js";
+ Object.values(languages).forEach((l: any) => numbro.registerLanguage(l));
```

**Comment by AMBudnik** [comment]
I'm glad to see this solved and thank you for sharing the fix.

**Comment by wojciechczerniak** [comment]
@AMBudnik can you create an issue in docs repo that we should add this to the tutorials?

**Comment by AMBudnik** [comment]
Sure @wojciechczerniak that's a good idea.

**Comment by AMBudnik** [comment]
Hi @Elecweb we need a couple of days to release a whole documentation rewritten to React. There's also an example with `culture` use for two different languages with an `import`. I'm sorry to hear that it was causing you problems. It should have been added a long time ago. Hopefully, the new documentation will be much better for React developers. 

ps. If you found anything missing or misleading in the documentation please let me know at support@handsontable.com

**Comment by adrianszymanski89** [comment]
Hi @Elecweb 

This information wasn't added to our documentation yet. However, the workaround proposed above is not the only option. You can also set the correct culture like that:

```diff
// index.tsx
import * as React from "react";
import { HotTable } from "@handsontable/react";
...

+ import numbro from "numbro";
+ import zhCN from "numbro/dist/languages/zh-CN.min";

+ numbro.registerLanguage(zhCN);
```

You will also need to install Numbro v. 2.1.2 as a dependency in your project to make it work correctly.

**Comment by Elecweb** [comment]
@adrianszymanski89  @AMBudnik Thank you for your help
