### ISSUE TITLE
Copying of readonly cells fails when using selectCells

### ISSUE THREAD

**Issue by moodyroto** [handsontable/handsontable#6146]
### Description
Coping data (ctrl + c) after using the `selectCells` methods does not work for any cells set to read only.

### Steps to reproduce

1. Using this fiddle - https://codepen.io/moodyroto/pen/XvXvdW
2. Select any disabled cell (eg, Row 20, Column D)
3. Hit Ctrl + Shift + Up Arrow, selecting cells from Row 20 to Row 1 in Column D
4. Hit Ctrl + C to attempt to copy those cells
5. Paste the clip board data somewhere else, and notice the clipboard data does not contain any of the cells attempting to be copied.

Note: If you repeat these steps for editable cells (eg, Row 20, Column B) Handsontable works as expected.

### Demo
Handsontable v7.1.1 Example - https://codepen.io/moodyroto/pen/XvXvdW
Handsontable v6.2.2 Example - https://codepen.io/moodyroto/pen/qebwNN

### Your environment
* Handsontable version: v7.1.1 and v6.2.2
* Browser Name and version: Chrome v75.0.3770.142
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @moodyroto 

you're right. Once we modify the selection, copy does not work. The `beforeCopy` hook is not triggered. However, the `getCopyableText` shows proper data and `modifyCopyableRange` reads the coordinates well.

Simplified the example https://jsfiddle.net/handsoncode/4tk97o3n/

I've replicated it with the latest (`7.1.0`) version and this issue doesn't seem to be version related. It breaks in `7.1.0` as well as in `2.0.0`.

**Comment by moodyroto** [comment]
@AMBudnik - Thanks for confirming. Do you know if there are any workarounds for this? Perhaps using different API calls?

**Comment by AMBudnik** [comment]
You can try to call [`copy()`](https://handsontable.com/docs/7.1.0/CopyPaste.html#copy) via [`afterDocumentKeyDown`](https://handsontable.com/docs/7.1.0/Hooks.html#event:afterDocumentKeyDown). It that won't help maybe reselecting the range?

**Comment by swistach** [comment]
Hi @moodyroto,
When I changed `changeListener` to `false` in `selectCells` and used `beforeKeyDown` instead of `afterDocumentKeyDown` your example works properly.
Demo: https://codepen.io/swistach/pen/JjPONoa

**Comment by moodyroto** [comment]
@swistach - I just added your suggestion to our app, and it fixed the issue we were seeing. Thank you very much for the help!

**Comment by swistach** [comment]
Excellent!
You're welcome 😄
