### ISSUE TITLE
A new value is not kept when we change cells really fast

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6151]
### Description

If we change the values of cells extremely fast, in some cases the new value is not kept.

### Steps to reproduce

All the actions have to be done very fast
1. Try to use <kbd>8</kbd> and <kbd>ENTER</kbd> to check that some cells haven't kept the <kbd>8</kbd> value.

![fast](https://user-images.githubusercontent.com/10757813/105357850-b2370f00-5bf5-11eb-9cbf-b868ba21b52a.gif)

### Demo

http://jsfiddle.net/handsoncode/4pbkjfo9/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome 75
* Operating System: Mac Mojave

**Comment by AMBudnik** [comment]
The same demo using v8.2.0 doesn't close the editor so fast but the result is still incorrect

http://jsfiddle.net/handsoncode/kr7p1t5g/
![image](https://user-images.githubusercontent.com/10757813/105359909-473b0780-5bf8-11eb-8d2b-a4384652869c.png)

**Comment by adrianszymanski89** [comment]
Issue re-tested on v. 12.0.1. Performance is even better now than with v. 8.2.0 but still not quite there:

http://jsfiddle.net/aszymanski/ybjrmakw/

**Comment by AMBudnik** [comment]
This issue is no longer replicable. Updated demo: https://jsfiddle.net/479g31Lw/
