### ISSUE TITLE
Need data change source `CopyPaste.cut` in CopyPaste plugin.

### ISSUE THREAD

**Issue by imageslr** [handsontable/handsontable#6156]
Hello, I need to distinguish user's `cut` action from `edit`. However, currently both these actions use a same `source` in `afterChange` hook: `edit`. 

I think it's better to use an extra source such as `CopyPaste.cut` so that one can tell user's actions more precisely. 

As a workaround, I have changed data modify codes in `copyPaste` plugin. https://github.com/handsontable/handsontable/blob/7.1.0/src/plugins/copyPaste/copyPaste.js#L465

**Comment by AMBudnik** [comment]
You're right @imageslr 

when we delete the a cell content (for example with <kbd>DEL</kbd> key) I can image that `edit` is the correct change type. However, while using <kbd>CTRL/CMD</kbd> + <kbd>X</kbd> and/or using the `Cut` option form the context menu I should get `CopyPaste.cut` source.

We'd need to add one in the source table https://handsontable.com/docs/7.1.0/tutorial-using-callbacks.html? but as we have the `cut` method in the `copyPaste` plugin and `beforeCut/afterCut` hooks the new `source` sounds reasonable.

Thank you for sharing this proposition.

**Comment by swistach** [comment]
Hi @imageslr,
We'll resolve this problem in #4106 (PR #6031).
Next week we'll release a new version of Handsontable and the fix will be there! :)

**Comment by imageslr** [comment]
Thank you all! Looking forward to the update :)

**Comment by swistach** [comment]
Change introduced in v`7.1.1`: https://jsfiddle.net/4o2ger7j/

**Comment by imageslr** [comment]
Thank you for your response!
