### ISSUE TITLE
Adjust AutoRowSize to new IndexMapper architecture.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6170]
### Description
#5751 introduces a new architecture for index translation. We have to adjust AutoRowSize plugin to be compatible with IndexMappers.

Changes have to base on `feature/issue-5751` branch.

**Comment by wojciechczerniak** [comment]
Merged with #5945

**Comment by wszymanski** [comment]
> > Merged with #5945
> 
> Not yet.

Done! :P
