### ISSUE TITLE
Radio buttons labels in filters dropdown should inherit font size

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6172]
### Description

Radio buttons labels in filters dropdown should inherit font size. They are too big atm.

![Screenshot 2019-08-01 at 14 55 29](https://user-images.githubusercontent.com/4718998/62295039-860d5880-b46c-11e9-979b-ab482b01155f.png)

### Steps to reproduce

1. Got to https://handsontable.com/docs/7.1.0/demo-filtering.html
2. Select any "Filter by condition"
3. And / or radio buttons will be shown

### Demo

https://handsontable.com/docs/7.1.0/demo-filtering.html

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Firefox
* Operating System: OS X

**Comment by aninde** [comment]
As this is not done yet I move this issue to the `In development`.

**Comment by wojciechczerniak** [comment]
Outdated task
