### ISSUE TITLE
 No scrolling when using fixedColumnsLeft (on tablets)

### ISSUE THREAD

**Issue by katomasa1254** [handsontable/handsontable#6175]
### Description
Hi, I'm Japanese.
I'm sorry if it is strange English.

I am displaying the grid using Handsontable.
`fixedColumnsLeft: 5, `
to fix the left 5 columns.
When I scroll this fixed column, I want to scroll the column which is not fixed at the same time.
(I want to synchronize scrolling)

This does not occur on PCs, but only on tablets (Fire FD).

On PC, scrolling in fixed columns is synchronized without any problem and non fixed columns are also scrolled.

If you delete `fixedColumnsLeft: 5, ` and lose a fixed column, scrolling works in sync.
You can also scroll along with fixed columns if you scroll by placing the mouse on a non-fixed row.

If you hover over a fixed row and scroll, only the fixed row is scrolled
You will lose synchronization with the non-fixed columns.
What should I do?

My HandsonTables's environment is
Handsontable.packageName = 'handsontable-pro';
Handsontable.version = '1.2.0';
var baseVersion = '0.23.0';
May be this is very very old.
Does updating solve this problem?

**Comment by AMBudnik** [comment]
Good day @katomasa1254 

Can you record the behavior?

Here's what I got on the iPhone XS 

![iphonexs](https://user-images.githubusercontent.com/10757813/62935847-7a088b80-bdc8-11e9-9824-18198c80f089.gif)

It seems like the desired result, besides the fact the rows get a bit misaligned when we move them. When we release the touch event they get back to their places.

**Comment by AMBudnik** [comment]
I guess that we can close the topic as there's no reply for some time now. Please share a comment if you're still experiencing that issue @katomasa1254

**Comment by katomasa1254** [comment]
Thank you for reply.
I'm sorry, it was my summer vacation.
So I can't read your answer.

Demo cannot be displayed due to confidentiality.

What happens if you scroll over columns A and B without fixing the rows?
Perhaps columns A and B are scrolled, but the other columns are not scrolled.
I know in my environment that scrolling in other columns is fine.

よろしくお願いします。

**Comment by AMBudnik** [comment]
Thank you for your answer. I'm reopening the topic.

Please tell me if you have the same issue using our [official demos](https://handsontable.com/docs/7.1.1/demo-scrolling.html)? I can see that you are using a very old Handsontable version. Have you considered updating it? It will surely fix some unwanted behavior and maybe (you can ten the official examples) it will also fix the mentioned issue.

**Comment by katomasa1254** [comment]
It is my first time to question So I'm not sure if it's correct, but this is a demo.
[demo](https://jsfiddle.net/5dbzrats/1/#)

The same problem did not occur when viewing this demo site using Fire HD.
However, there was a problem that scrolling was not possible with fixed columns.
(It works without problems when viewed from a PC.)
Scrolling without problems is possible for unfixed columns.

If I update HandsonTable, will it be in the same state?
I want to scroll in a fixed column as well as a non-fixed column.

**Comment by AMBudnik** [comment]
Thank you for sharing the demo @katomasa1254 

I will ask our colleagues to try to replicate the issue.
I've tried it on iPad mini, don't have Fire FD, which runs on Android. This might be the difference that we're looking for.

**Comment by AMBudnik** [comment]
I have tried an Android tablet using browserstack, but just got this issue https://github.com/handsontable/handsontable/issues/4624 scrolling works bad (misaligns) but moves. Unfortunately, this tool doesn't have Fire HD on the list so I could not test it.

**Comment by katomasa1254** [comment]
@AMBudnik Thank you for trying.
This problem occur by major browsers.(I have tried to Chrome and Firefox.)

**Comment by AMBudnik** [comment]
> This problem occur by major browsers.(I have tried to Chrome and Firefox.)

Thank you for feedback. I believe that as it more device-related we still should take a look at it.

**Comment by AMBudnik** [comment]
I've tested our fixing demo https://handsontable.com/docs/8.0.0/demo-fixing.html so the issue is still replicable. Not only on the Fire FD.

Device/OS Settings (used on Browserstack)
os=android
os_version=10.0
device=Samsung+Galaxy+S20
device_browser=chrome

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Interoperability problems using Mobile devices and some core features** task reported at https://github.com/handsontable/handsontable/issues/7520

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
