### ISSUE TITLE
Row selection ignores columns that are hidden at the end

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6181]
### Description

Row selection ignores columns that are hidden at the end. Should select entire row.

### Steps to reproduce

1. Hide last column or few last columns
2. Click on row header
3. `hot.getSelectedRangeLast()` returns range that ignores columns hidden at the end
4. Does not happen if last column is visible, selected range is entire row.

### Demo

https://jsfiddle.net/Ljtasfvx/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Firefox Quantum
* Operating System: Mac OS X

**Comment by AMBudnik** [comment]
7.4.2 https://jsfiddle.net/5p34rnqg/ (result 10 12)

8.0.0.-beta1 https://jsfiddle.net/5p34rnqg/1/ (result 10 12)

8.0.0.-beta2-rev2 https://jsfiddle.net/5p34rnqg/2/ (result 12 12 ) **solved**

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 https://jsfiddle.net/mkbjnLg1/

Issue closed as solved.
