### ISSUE TITLE
Custom Render functions are not being applied to column 0

### ISSUE THREAD

**Issue by Calidus** [handsontable/handsontable#6182]
### Description
Custom render functions are not being applied to the first column. Col of 0 is never passed to the render function. 

### Steps to reproduce
1. create a table with rows and columns
2. compare the col to 0 inside the a custom render function, expect col to be 0 

### Demo
Simple example of setting the background color to blue for column 0
https://jsfiddle.net/t3a8p2r9/1/

Broken inside the documentation as well, Column 0 cells are not bold or italics
https://handsontable.com/docs/7.1.0/demo-custom-renderers.html

### Your environment
* Handsontable version: 7.1
* Browser Name and version: Chrome 
* Operating System: win10 64bit

**Comment by wojciechczerniak** [comment]
Your first column (index: 0) does not have `customRenderer`:
```
    columns: [
      {},
      {renderer: customRenderer}
    ],
```

**Comment by Calidus** [comment]
I just updated the fiddle. Thanks for catching the typo.
