### ISSUE TITLE
Need data change source `delete`

### ISSUE THREAD

**Issue by imageslr** [handsontable/handsontable#6183]
Hello, I need to remove some cell meta when user click `backscpace` on keyboard to delete all content at a cell. However, currently this action uses a source `edit`.

Thank you very much!

**Comment by imageslr** [comment]
I found a solution: use `beforeKeyDown` hook and call `event.stopImmediatePropagation()` (thanks for the flexible hooks).  Maybe changing source to `delete` is not useful for other developers, but add fourth param might be useful if it provides keys user typed. Thanks for your consideration.

Feel free to close this issue.

**Comment by AMBudnik** [comment]
I'm glad that you found the way to achieve the goal.

Feel free to open a new ticket when needed.
