### ISSUE TITLE
Trace filtering process after clicking 'Ok' in a dropdownmenu

### ISSUE THREAD

**Issue by HardRock4Life** [handsontable/handsontable#6189]
I need to find a piece of Handontable code which is responsible for filtering data when a button 'OK' in a DropDownMenu gets clicked. Can you explain the process of filtering or help me to find the necessary file in your project?

**Comment by AMBudnik** [comment]
Hey @HardRock4Life 

You can check the `beforeFilter` and `afterDropdownMenuHide`, but the second one runs after `beforeFilter`. Demo https://jsfiddle.net/2zpswtk8/

**Comment by HardRock4Life** [comment]
Many thanks, Alexandra!
