### ISSUE TITLE
"random" ordering of rows on filter for pre-filtered data.

### ISSUE THREAD

**Issue by dmitryfil** [handsontable/handsontable#6192]
### Description

When starting with a pre-filtered data, after adding a few more rows and try to apply a filter, order appear to be off.

### Steps to reproduce

1. Have a pre-filtered data (let's say we have a column "Active", checkbox), and we hide inactive records on loading.
2. Last row is used for input, so it would be always visible, by using ```minSpareRows: 1``` rows.
3. Create a few new records, similar to last active record in a table, new empty line (for new row), would always show up at the end.
4. Filter column with ex. "Contains" filter - now empty row (and other rows) would change their order.

For version 5.0.2 it seems that it's possible to fix it (and maybe it's an issue with a code in general), by adjusting ```countRows``` to ```countSourceRows``` (visual vs physical rows) - but want to check if that seems like a correct assumption. 

<img width="645" alt="SourceRows" src="https://user-images.githubusercontent.com/645493/62653429-8f466b80-b92b-11e9-9060-961e20375805.png">

### Demo

JS Fiddle: https://jsfiddle.net/3vnjm6ex/

![JS-Fiddle-Random-Rows-Issue-Animated](https://user-images.githubusercontent.com/645493/62652936-77bab300-b92a-11e9-8ce0-a157c694b5b2.gif)

### Your environment
* Handsontable version: 6.2.2 (5.0.2) 
* Browser Name and version: Chrome
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Hey @dmitryfil 

this behavior seems to be gone when we update to the latest version `(7.1.1)`. 
I can confirm that it breaks on `6.2.2`
