### ISSUE TITLE
Add hooks to collapsibleColumns plugin

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6193]
### Description
This plugin lacks some hooks which should indicate when the column is collapsed or is uncollapsed.

We need 4 new hooks - `beforeCollapsedSections`, `afterCollapsedSections`, `beforeUncollapsedSections` and `afterUncollapsedSections`. 

The naming convention requires some discussion with the rest of the team.

Additionally, `before` should block actions.

**Comment by aninde** [comment]
Done in `v8`, but names were changed to `beforeColumnCollapse`, `afterColumnCollapse`, `beforeColumnExpand`, `afterColumnExpand`. The changes include the source code and documentation.

**Comment by AMBudnik** [comment]
I'm so glad to see this hook :-) 🥳
