### ISSUE TITLE
handsontable中的单元格如何自动隐藏多出来的内容，像excel一样

### ISSUE THREAD

**Issue by win77day** [handsontable/handsontable#6194]
当单元格的内容过多时，如何自动隐藏多出来的内容，点击的时候再显示出来，就像excel一样

**Comment by wojciechczerniak** [comment]
Sorry, I don't understand. Reopen in English, thanks.

**Comment by AMBudnik** [comment]
Hey @win77day 

If the Google Translate is not fooling with me I think this is what you need https://jsfiddle.net/djhoyvfw/
