### ISSUE TITLE
afterOnCellMouseDown source code

### ISSUE THREAD

**Issue by HardRock4Life** [handsontable/handsontable#6196]
Is there a source code for such an event as 'afterOnCellMouseDown'? Where can I see how this event works?

**Comment by wojciechczerniak** [comment]
Yes it is. All Handsontable code is available in the main repository: https://github.com/handsontable/handsontable

**Comment by HardRock4Life** [comment]
If you don't mind, what is the exact directory I should look at?

**Comment by HardRock4Life** [comment]
I found a full list of events at pluginHooks.js. The key question I have - is there a default code that starts working when 'afterDropdownMenuHide' is triggered?

**Comment by wojciechczerniak** [comment]
Hook is run with`runHook('hookName', ...)` method. So I would search for `runHooks('afterOnCellMouseDown'`. It's in `/src/tableView.js` file.

**Comment by HardRock4Life** [comment]
Dziękuję, Wojciech!
