### ISSUE TITLE
Mouse wheel scrolling not working in scrollable container

### ISSUE THREAD

**Issue by rwagstaff** [handsontable/handsontable#6197]
### Description
When using the demo provided. The mouse wheel stops scrolling when hovered over the handsontable instance. I would expect the mouse wheel to continue scrolling up and down the page.

### Steps to reproduce

1. Go to the JsFiddle https://jsfiddle.net/18576u4r/2/
2. Click on a hot cell (C9)
3. Scroll up and down the mouse wheel. 

### Demo
 https://jsfiddle.net/18576u4r/2/

### Your environment
* HOT v7.1.0 (latest):
* Chrome (latest)
* Windows 10:

Thank you for your time, apologies if this is a mistake on my behalf.

**Comment by wojciechczerniak** [comment]
Thanks for the report @rwagstaff 

I think this might be a duplicate of #5212, can you check it out and let me know?

It is already fixed on our `develop` branch and will be released on Monday as v7.1.1.

**Comment by rwagstaff** [comment]
Thanks for the quick response, it does look like a duplicate. I look forward to testing in v7.1.1

**Comment by wojciechczerniak** [comment]
Thanks! I'm closing this as a duplicate of  #5212
