### ISSUE TITLE
HandsontableEditor afterOnCellMouseDown sets multiple values

### ISSUE THREAD

**Issue by RichTeaTime** [handsontable/handsontable#6198]
### Description
When writing a custom HandsontableEditor subclass (extending Autocomplete), we expect that when the user clicks on an entry in the list, that the MyEditor.setValue method will be called with the value that was clicked.

Instead, MyEditor.setValue is called with an array including all of the items from the start of the list to the clicked value.

In HandsontableEditor.prototype.prepare
<pre>
afterOnCellMouseDown: function afterOnCellMouseDown(_, coords) {
      var sourceValue = this.getSourceData(coords.row, coords.col<b>);</b>
</pre>
This getSourceData evaluates the missing col2/row2 parameters as 0,0, so returns all entries preceding the one passed, rather than returning only the expected single value.

In normal usage, the user doesn't see any difference, as the HandsontableEditor.prototype.finishEditing callback retrieves the last selected item when closing and manually assigns it, but this has a side-effect of setting a value to the first item in the list if the user clicks away.

Workaround: override the afterOnCellMouseDown in our editor with
<pre>
 afterOnCellMouseDown: function afterOnCellMouseDown(_, coords) {
      var sourceValue = this.getSourceData(coords.row, coords.col, <b>coords.row, coords.col</b>); // if the value is undefined then it means we don't want to set the value

      if (sourceValue !== void 0) {
        parent.setValue(sourceValue);
      }

      parent.instance.destroyEditor();
    }
</pre>

We then no longer need the secondary setValue in finishEditing (we call htEditor.deselectCell in our subclass to prevent this).

**Comment by RichTeaTime** [comment]
Correction, 
<pre>
 afterOnCellMouseDown: function afterOnCellMouseDown(_, coords) {
      var sourceValue = <b>this.getSourceDataAtCell(coords.row, coords.col);</b> // if the value is undefined then it means we don't want to set the value

      if (sourceValue !== void 0) {
        parent.setValue(sourceValue);
      }

      parent.instance.destroyEditor();
    }
</pre>

This returns the single selected value.

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting, @RichTeaTime 

I got a bit lost here. 

You got an array from `getSourceData` instead of a single value and `getDataAtCell` gives you a single value which all sounds like the expected behavior.

Please let me know what I'm missing.

**Comment by RichTeaTime** [comment]
The difficulty is that this is code in the handsontable library (not in my code).
The ```HandsontableEditor``` ```afterOnCellMouseDown``` calls the wrong method.
It should be calling ```getSourceDataAtCell```, not ```getSourceData```.

Now, I might be missing something here: There may be a good reason why calling ```editor.setValue``` with an array containing all elements from the start of the source array to the selected item is a neccessary use-case, but I can't imagine it. There then seems to be a fairly hacky bit of code in ```finishEditing``` that calls the ```editor.setValue``` method again with the last selected value (even if the selected value was not selected by the user)

As mentioned initially, this ```finishEditing``` method doesn't seem to work very well, as it results in the first item in the source array being assigned, even if the user ended the edit session by clicking away, without manually selecting an item from the dropdown.

STRs - https://jsfiddle.net/mga9y04z/
1. Assign a 'dropdown' cell type to a column and a source array for that dropdown
2. Load data for that column that contains empty values (e.g. null, or values not in the dropdown)
3. Click onto the arrow on the cell to open the editor
4. Wait for the dropdown to display
5. Click on another cell
EXPECTED: Cell value will be unchanged
ACTUAL: Cell value is set to the first item in the dropdown source.

To be fair, removing (or disabling) that hacky bit of code in ```finishEditing``` does cause a secondary issue with keyboard navigation, but this can be fixed with a ```onKeyDownHandler``` to actually process the Enter key to trigger item selection: 
e.g.
```
onKeyDownHandler = function (evt:KeyboardEvent):void {
            if (evt.key == "Enter") {
                const currentVal = dropdown.getValue();
                if( currentVal != null )
                    parent.setValue( currentVal );
            }
        }
```

**Comment by AMBudnik** [comment]
Hey Rich,

Thank you for doing the investigation. Now it makes a total sense. To be honest, I would expect the editor to act hacky from time to time. The code is nearly as old as the first commit to Handsontable).

We had a chat with the CTO and devs about this subject. As much as we'd like to get our hands on it and get this done as hard it is to push a new task into the milestone. But, if you'd decide to create a pull request and help us out I'll do my best to find the spot and do the review.

**Comment by AMBudnik** [comment]
I just wanted to make a quick update. The issue for opening/closing the dropdown menu without picking a value did not change for v 8.0.0 https://jsfiddle.net/AMBudnik/0raehjfz/
