### ISSUE TITLE
manualColumnMove does not work properly with updateSettings

### ISSUE THREAD

**Issue by coband** [handsontable/handsontable#6199]
### Description

When I use manualColumnMove and updateSettings at the same time the columns dont keep their original  width when i move them.  I have made a demo.  When i move B in front of A in the demo, the width of the column doesnt adjust.
Is there a way to get both working?
Originally the problem is that the first row in our table is one pixel too small and one letter always wraps on a second line. We fixed that problem by using updateSettings. So we either need to fix the original problem differently or get to work manualColumnMove and updateSettings together.

### Demo

https://jsfiddle.net/0jv36Lq9/2/
### Your environment
HOT v7.1.0 (latest):
Chrome (latest)
Windows 10:

Thank you for your time!

**Comment by patrickluethi** [comment]
You must be new to javascript :) ! No worries i got you. 

Add this after you create the handsontable

```
hot.addHook('afterColumnMove', function () {
        hot.getPlugin('AutoColumnSize').recalculateAllColumnsWidth();
});
```

**Comment by coband** [comment]
ive been programming for over 20years now but thank you it wored!!

**Comment by patrickluethi** [comment]
sure ;)
