### ISSUE TITLE
An option to set container where UI elements are attached

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6202]
### Description
We need an option to customize container where we create floating elements: context menu, editor, dropdown, and other. Items that are opened inside an `iframe` are cut by the inner window bounding box. We need an option to set an element where those UI elements should be attached to. With the default as is right now.

- [ ] New option in the settings object.
- [ ] All our elements should use this container if it's set.
- [ ] If it's not set we should have a default

### Steps to reproduce

1. Go to: https://jsfiddle.net/2ads7u9g/
2. Open Context Menu on Handsontable
3. Context Menu is cut off by the `iframe`

### Demo
https://jsfiddle.net/2ads7u9g/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Firefox, Chrome
* Operating System: Mac OS X

**Comment by f1ames** [comment]
It also concerns date picker which is used when cell type set to `date`.
