### ISSUE TITLE
Cross-browser scrollbar

### ISSUE THREAD

**Issue by HardRock4Life** [handsontable/handsontable#6205]
I need to hear your recommendation on importing Simplebar https://github.com/Grsmto/simplebar into your project, since this scroll supports cross-browsering. The problem, I have no idea into which file should I implement Simplebar's capabilities (i.e. visual) without bugs and other issues. Can you assist?

Edit: OK, I believe my question might look a bit confusing. The situation is the following - I want to implement a custom scrollbar so it would had had a same style in each browser (HOT shows a properly styled scrollbar in Chrome, but in Firefox and IE it rolls back to default).

That is the reason I made a decision this very custom scrollbar from the link above.

**Comment by AMBudnik** [comment]
Hey @HardRock4Life 

we had a similar case here https://github.com/handsontable/handsontable/issues/5576
It's a different library but the process should stay the same.
