### ISSUE TITLE
Handsontable columnSorting doesn't work when passed title as html tag

### ISSUE THREAD

**Issue by PathaShiva** [handsontable/handsontable#6207]
var arrayOfObjects = [
    { brand: "Tesla", model: "Model 3", maxSpeed: 141, range: 215, seats: 5, price: 32750, productionDate: "06/29/2007" },
    { brand: "Tesla", model: "Model S", maxSpeed: 139, range: 275, seats: 7, price: 71788, productionDate: "04/02/2012" },
    { brand: "Mitsubishi", model: "iMiEV", maxSpeed: 81, range: 99, seats: 4, price: 31426.9, productionDate: "09/11/2009" },
    { brand: "Ford", model: "Focus EV", maxSpeed: 85, range: 100, seats: 4, price: 12000, productionDate: "10/01/2011" },
    { brand: "Mitsubishi", model: "iMiEV Sport", maxSpeed: 84, range: 124, seats: 4, price: 15000, productionDate: "05/11/2007" },
    { brand: "Tesla", model: "Roadster", maxSpeed: 125, range: 244, seats: 2, price: 113904.5, productionDate: "02/17/2008" },
    { brand: "Volkswagen", model: "e-Golf", maxSpeed: 87, range: 118, seats: 5, price: 33012, productionDate: "10/05/2011" },
    { brand: "Volkswagen", model: "E-Up!", maxSpeed: 85, range: 80, seats: 3, price: 32258.75, productionDate: "11/09/2009" },
    { brand: "Ford", model: "C-Max Energi", maxSpeed: 115, range: 18, seats: 5, price: 27120, productionDate: "11/25/2014" },
    { brand: "BYD", model: "Denza", maxSpeed: 93, range: 157, seats: 5, price: 47600, productionDate: "10/01/2011" },
    { brand: "BYD", model: "e5", maxSpeed: 93, range: 136, seats: 5, price: 22966.92, productionDate: "07/19/2015" },
    { brand: "BYD", model: "e6", maxSpeed: 87, range: 199, seats: 5, price: 31440, productionDate: "06/22/2009" }
  ];
  
  var exampleContainer3 = document.getElementById('example3');
  new Handsontable(exampleContainer3, {
    data: arrayOfObjects,
    colHeaders: ["Brand", "Model", "Max speed<br>(in miles per hour)", "Range<br>(in miles)", "Seats", "Price", "Start of<br>production"],
    columns: [{
      data: 'brand' // 1st column is simple text, no special options here,
      title: `"<b>brand</b>"`
    }, {
      data: 'model'// 2nd column is simple text, no special options here,
      title: `"<b>model</b>"`
    }, {
      data: 'maxSpeed',
      type: 'numeric',
      title: `"<b>maxSpeed</b>"`
    }, {
      data: 'range',
      type: 'numeric',
      title: `"<b>range</b>"`
    }, {
      data: 'seats',
      type: 'numeric',
      title: `"<b>seats</b>"`
    }, {
      data: 'price',
      type: 'numeric',
      numericFormat: {
        pattern: '$ 0,0.00',
        culture: 'en-US',
      title: `"<b>price</b>"`
      }
    }, {
      data: 'productionDate',
      type: 'date',
      dateFormat: 'MM/DD/YYYY',
      correctFormat: true,
      defaultDate: '01/01/1900',
      title: `"<b>productionDate</b>"`
    }],
    columnSorting: true
  });

**Comment by AMBudnik** [comment]
The issue has been already mentioned here https://github.com/handsontable/handsontable/issues/5951

Please track changes to this issue for updates.
