### ISSUE TITLE
`setDataAtCell` and `setDataAtRowProp` clears value in the active editor

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#6208]
### Description
You should be able to programmatically update data in cells without losing the value in the currently active editor.

### Steps to reproduce
1. Go to fiddle https://jsfiddle.net/8a9pmchg/
2. Click in the top left cell and start typing

### Demo
https://jsfiddle.net/8a9pmchg/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome
* Operating System: OS X

**Comment by AMBudnik** [comment]
Hey @aarondfrancis 

They do not clean the value. They close the editor cause they need to process a `render()` to show the need data requested by `setDataAtCell`.

**Comment by aarondfrancis** [comment]
For anyone looking for a monkey-patch, here is mine.

```js
const monkey = function (hot) {
    const original = hot.setDataAtRowProp;

    hot.setDataAtRowProp = function (row, prop, value, source) {
        // https://github.com/handsontable/handsontable/issues/6208
        const editor = hot.getActiveEditor();
        let restore = null;

        if (editor.state !== 'STATE_VIRGIN') {
            restore = editor.getValue();
        }

        original(row, prop, value, source);

        if (restore !== null) {
            editor.setValue(restore);
        }
    }
}
```

**Comment by AMBudnik** [comment]
Thank you for sharing. I'm glad that you've found a way to meet the goal.
