### ISSUE TITLE
When we again on the same cell with RMB we get a browser menu

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6218]
### Description

When we click <kbd>RMB</kbd> on a text inside a cell twice we get two menus: browser and the context menu.

![image](https://user-images.githubusercontent.com/10757813/63326024-aa51ac00-c32b-11e9-8e85-4298228d2ed1.png)

![image](https://user-images.githubusercontent.com/10757813/63326568-d0c41700-c32c-11e9-9ade-cfc31a297edc.png)

The issue seems to be gone if we click on an empty space inside a cell.

### Steps to reproduce

1. Try to click on the same cell using <kbd>RMB</kbd>.
You should be pixel perfect and use <kbd>RMB</kbd> on the same pixel on a text inside a cell.

### Demo

any context menu example https://handsontable.com/docs/7.1.1/demo-context-menu.html

### Your environment
* Handsontable version: 7.1.1
Doesn't seem to be version related
* Browser Name and version: Chrome 76
* Operating System: Windows 10

**Comment by aninde** [comment]
It was difficult to reproduce. IMHO it is better on `7.3.0`,  but I'm not sure about assumptions.  @AMBudnik  can you check it again? 


**Demo**
https://jsfiddle.net/aninde/42w167bh/

**Comment by AMBudnik** [comment]
It's clear how to replicate this issue now.

1. Open a context menu (Handsontable)
2. Click the <kbd>RMB</kbd>on the line of our context menu. If you move the pointer slowly to the top you will notice that the pointer changes when you hover over the line (border) of the context menu. That's the place to click <kbd>RMB</kbd>

![image](https://user-images.githubusercontent.com/10757813/69043357-30e15c80-09f3-11ea-9b7f-1b5e5a4b765a.png)

![GIF](https://user-images.githubusercontent.com/10757813/69043145-c7f9e480-09f2-11ea-9ea3-0175588896a3.gif)

Replicable in `7.3.0` https://jsfiddle.net/oL6egc0x/

**Comment by aninde** [comment]
This bug is still repricable in latesst version on `7.3.0` https://jsfiddle.net/g7b64pkv/

**Comment by wojciechczerniak** [comment]
Yup, PR #6484 was not merged and this is marked for v8.0.0-beta

**Comment by aninde** [comment]
Still works with `8.0.0-beta2-rev18` https://jsfiddle.net/aninde/n8ps549e/

**Comment by aninde** [comment]
In my opinion, it's fixed in `8.0.0-beta2-rev18` https://jsfiddle.net/s3ujwn7g/1/. Tested on Firefox 77, Chrome 83 and Safari 13.1.1 / macOS Catalina 10.15.5

 This issue requires high precision and I would like to be 100% sure. @AMBudnik can you retest it?
![rev18-6218](https://user-images.githubusercontent.com/30186818/86475495-11f6c700-bd45-11ea-9f9f-cbbb47a05109.gif)

**Comment by AMBudnik** [comment]
@aninde that was a tricky one. And yes, it is fixed in `8.0.0-beta2-rev18` - when we click the border there's no system menu.

**Comment by aninde** [comment]
This issue remains fixed with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/7jdt2shg/.
