### ISSUE TITLE
setDataAtCell for a particular cell removes css of other cell

### ISSUE THREAD

**Issue by karuneshsf** [handsontable/handsontable#6220]
### Description
If we set colour in a particular cell e.g.  
$(hot.getCell(0, 0)).css({"background-color": "yellow"});

and after that I chnaged value of another cell of the same table say

hot.setDataAtCell(1, 2, "some value");

Then setting the data at cell (using setDataAtCell) removes the changed colour of previously background colour of prior cell. 

### Steps to reproduce
https://drive.google.com/file/d/1Qj5ng9JeDXhLfRHHaKvoxkRChw8VRGbO/view

### Demo
https://jsfiddle.net/98bkqrtj/26/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome (Latest)
* Operating System: Linux / Windows both

**Comment by AMBudnik** [comment]
Hey @karuneshsf 

a proper way of changing styling for cells is using `className`. Here's the changed example https://jsfiddle.net/cs6k4ypg/
