### ISSUE TITLE
handsontable Not showing cells value after adding :columns="mycolumns"

### ISSUE THREAD

**Issue by farhadniaz** [handsontable/handsontable#6222]
### Description

We are using payed version and it's not showing table cell values after adding `:columns="mycolumns"` value .

### Steps to reproduce

`:columns="mycolumns"` 

### Your environment
* Handsontable version:^4.1.0
* Browser Name and version:chrome 
* Operating System: windows

**Comment by AMBudnik** [comment]
Hey @farhadniaz 

Please share a demo where the issue can be replicable? As `mycolumns` is a variable the information is insufficient to solve the issue.

**Comment by AMBudnik** [comment]
As there is no demo it is hard to propose any fix. Please share a demo @farhadniaz and we'll reopen the topic.
