### ISSUE TITLE
Can't hide rows and merge cells at the same time

### ISSUE THREAD

**Issue by chao** [handsontable/handsontable#6224]
### Description
I try to hide the 2,3,4 rows then merge the first column of 1-2 rows, 3-4 rows, and 5-6 rows. The result is wrong.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/55872/63489986-30b1ed80-c4e6-11e9-99e8-4ea9287e1c1f.png">

### Demo
[http://jsfiddle.net/czhou/2v5y3qdb/20/](http://jsfiddle.net/czhou/2v5y3qdb/20/)

**Comment by chao** [comment]
I think the problem is caused by merging from the row which is hidden in setting.

For example, when I try to merge row A2 to A6, but the second row was hidden, the merge cells are wrong.

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/55872/63503784-b04db580-c502-11e9-838f-6376eafd77e0.png">

[http://jsfiddle.net/czhou/2v5y3qdb/30/](http://jsfiddle.net/czhou/2v5y3qdb/30/)

But when you merge row A1 to A6, it works as expected.

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/55872/63503889-f73bab00-c502-11e9-883c-4e526db0e11f.png">

[http://jsfiddle.net/czhou/2v5y3qdb/29/](http://jsfiddle.net/czhou/2v5y3qdb/29/)

**Comment by AMBudnik** [comment]
Thank you for sharing the issue. I have replicated the same using v`7.1.1` on Chrome 76/Windows 10.

It doesn't seem to be looking any better in previous versions of Handsontable.

**Comment by AMBudnik** [comment]
There's no change in 8.0.0.-beta2-rev6 http://jsfiddle.net/1wcm6aLk/

**Comment by aninde** [comment]
This bug appears to be partially repaired by `8.0.0-beta2-rev10` http://jsfiddle.net/aninde/vqydmtcp/. We are currently at the testing and correction stage of the new version.
<img width="296" alt="Screenshot 2020-06-03 at 16 37 25" src="https://user-images.githubusercontent.com/30186818/83650337-86a8db00-a5b8-11ea-9f31-79f96af980a1.png">

**Comment by wojciechczerniak** [comment]
@aninde @AMBudnik I believe this issue is fixed in the v8-beta.2.

The only case that is missing is displaying the value but it has a separate issue: #6871

**Comment by AMBudnik** [comment]
Yes, the main issue is fixed (still working in rev19 http://jsfiddle.net/6k1pcyw8/) and the separate issue has it's own topic.

**Comment by pnowak** [comment]
Hi @chao 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment]
Hi @chao 

I’m glad to announce that Handsontable v8.0.0 that solves this issue is up and running.

I highly encourage you to test the new version and leave some feedback. I hope that the amount of work that we put on the v8 will help you to improve your project.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
