### ISSUE TITLE
Across the column calculation

### ISSUE THREAD

**Issue by DaiWenqi** [handsontable/handsontable#6225]
### Description

I want to set up a sales table, where the gross profit rate needs to be calculated in real time, and the corresponding gross profit rate value can be modified immediately after manually entering.The document now appears to have only vertical cross-row calculations and no horizontal cross-column calculations

### Steps to reproduce

1.
2.
3.

### Demo

![image](https://user-images.githubusercontent.com/3348055/63492444-18dd6800-c4ec-11e9-8708-bf4c837cdf50.png)

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey @DaiWenqi 

I highly recommend this article https://handsontable.com/blog/articles/2016/4/expand-your-app-with-cell-dependencies where we share a couple of examples (in JSFiddle) on how to set cell dependencies.
All of them are based on the [`beforeChange`](https://handsontable.com/docs/7.1.1/Hooks.html#event:beforeChange) and [`afterChange`](https://handsontable.com/docs/7.1.1/Hooks.html#event:afterChange) logic. Those are hooks that are fired on every change.
