### ISSUE TITLE
setDataAtCell() Unable to echo stored formulas to table

### ISSUE THREAD

**Issue by wuganzhi** [handsontable/handsontable#6226]
Formulas in cells are stored in the database for the first edit of the table. Formulas stored in database are displayed in tables for the second edit (not the values calculated by formulas). Using setDataAtCell (row, col, formula, formula) function does not achieve the desired results.The formula I passed in, I get the value calculated by the formula (I want to get the formula itself in the table display)

**Comment by wuganzhi** [comment]
I found out what the problem was and I needed help. It's because I triggered mergeCells with updateSettings ().
You can see it here：https://jsfiddle.net/wuganzhi/sv5yeq4b/24/

**Comment by wuganzhi** [comment]
Can I update the operation of merging cells in another way? I didn't find it in the document.

**Comment by AMBudnik** [comment]
> Can I update the operation of merging cells in another way?

what do you mean exactly? What's the goal?

Do you mean that you are looking for a workaround for this issue https://github.com/handsontable/handsontable/issues/3315?

**Comment by wuganzhi** [comment]
> > Can I update the operation of merging cells in another way?
> 
> what do you mean exactly? What's the goal?
> 
> Do you mean that you are looking for a workaround for this issue #3315?

As I mentioned in the demo, the updateSettings() operation triggers the merged cell, which will cause the formula to be replaced (the value calculated by the formula will be preserved), you can look at the console print in the demo.

**Comment by wuganzhi** [comment]
> > Can I update the operation of merging cells in another way?
> 
> what do you mean exactly? What's the goal?
> 
> Do you mean that you are looking for a workaround for this issue #3315?

I sorted out the demo, which might look more intuitive. https://jsfiddle.net/wuganzhi/sv5yeq4b/40/

**Comment by AMBudnik** [comment]
Yes, I can see what you mean now. That's a great move here. Glad to see this working and thank you for the update, @wuganzhi

**Comment by wuganzhi** [comment]
> Yes, I can see what you mean now. That's a great move here. Glad to see this working and thank you for the update, @wuganzhi

I used the delay execution to avoid this bug. Let updateSettings() work first, and then set the formula after 1 second. This can avoid this problem. Is there any way to get formula gracefully?

**Comment by AMBudnik** [comment]
>  Is there any way to get formula gracefully?
You can get the formulas via source data. Here's an example https://jsfiddle.net/50a6cebu/
