### ISSUE TITLE
Data source Can I use a Table 

### ISSUE THREAD

**Issue by sxmny123** [handsontable/handsontable#6228]
Can I use the form generated by Handsontable as a data source? For example, I used Handsontable to generate a table, then can I use the last form to generate an excel next time?

**Comment by sxmny123** [comment]
How to preserve table state and data after page reload

**Comment by AMBudnik** [comment]
Hey @sxmny123 

if you want to keep the data that has been changed by the user you need to keep the changes on your backend.

To get the updated data source once a user makes changes you can use the [`afterChange`](https://handsontable.com/docs/7.1.1/Hooks.html#event:afterChange) hook to call [`getData`](https://handsontable.com/docs/7.1.1/Core.html#getData) method. That will return the whole dataset.

**Comment by sxmny123** [comment]
只能通过保存修改之后的数据作为下次的数据源，这是唯一的方式吗；非常感谢

**Comment by AMBudnik** [comment]
I am sorry, but I do not understand the question fully. Maybe it will be easier to share some examples/drafts of the expected behavior.
