### ISSUE TITLE
Custom menu callback function does not execute

### ISSUE THREAD

**Issue by wuganzhi** [handsontable/handsontable#6231]
Custom menu, after the sub-menu exceeds three levels, the callback function will not be executed (the menu is displayed normally)

Demo Url https://jsfiddle.net/wuganzhi/7uxy52me/12/

**Comment by AMBudnik** [comment]
Hey @wuganzhi 

thank you for sharing the example. This https://github.com/handsontable/handsontable/issues/3533 topic covers the same problem. If you wish to add any tips/suggestions/example please comment to https://github.com/handsontable/handsontable/issues/3533

**Comment by wuganzhi** [comment]
@AMBudnik I just want to extend some functions that calculate formulas. I am using the right-click menu. I found that the callbacks of the three-level menus are not working properly. Does the handsontable have a way to implement custom calculation formula functions? Thank you very much for your reply!

**Comment by AMBudnik** [comment]
Hey @wuganzhi 

we're using a custom form (formula-parser) to handle formulas. Here's more info about the custom function creation https://github.com/handsontable/formula-parser/releases/tag/2.3.0

**Comment by wuganzhi** [comment]
> Hey @wuganzhi
> 
> we're using a custom form (formula-parser) to handle formulas. Here's more info about the custom function creation https://github.com/handsontable/formula-parser/releases/tag/2.3.0

I see that the function library supports the INTERCEPT function on github, but I will report an error when I use it. Can you tell me how to use the INTERCEPT function? Thank you for your help!
INTERCEPT support address on github: https://github.com/handsontable/formula-parser/blob/develop/src/supported-formulas.js#L181
Demo address: https://jsfiddle.net/wuganzhi/7uxy52me/18/

**Comment by AMBudnik** [comment]
Hey @wuganzhi I've already answered https://github.com/handsontable/handsontable/issues/6234. Please continue the conversation there.
