### ISSUE TITLE
trimWhitespace=false and wordWrapping

### ISSUE THREAD

**Issue by janisdd** [handsontable/handsontable#6232]
### Description

When you set the options `trimWhitespace:false` and `wordWrap:true` wrapping is not applied 
(but I guess it should?).

When you change it to `trimWhitespace:true` and `wordWrap:true` column/cell wrapping is applied as expected.

*(`wordWrap:true` is the default so it might not be important here)*

### Steps to reproduce

- set the options

### Demo
https://jsfiddle.net/07hpocjd/

### Your environment
* Handsontable version: 7.1.1 (also tested in 6.2.2)
* Browser Name and version: Chrome 76.0.3809.100
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Agree, they shouldn't block each other. I have replicated the on Chrome 67 and FF/Windows 10 with the latest (`7.1.1`) version. 
It works the same across the versions.

**Comment by janisdd** [comment]
Because I don't think this issue has any priority (was there since 2015, introduced in https://github.com/handsontable/handsontable/commit/00dc2c8147c957bc089e194c82752fa17c223c2c) I have done some research myself

Here are the results:

in `src/renderers/textRenderer.js ` the lines

```js
if(!instance.getSettings().trimWhitespace) {
   escaped = escaped.replace(/ /g, String.fromCharCode(160));
 }
``` 

replace normal whitespace with `&nbsp;` if `trimWhitespace` is false

`trimWhitespace` actually does more than just trimming the cell value, it also changes the displayed value (whitespace are preserved when false, collapsed when true, which is somehow unexpected given the name of the option). 


Here is the cases

trimWhitespace | wordWrap | works?
---|---|---
0|0| true
0|1| false, won't wrap because the `nbsp`
1|0| true
1|1| true

The following changes will resolve the issue

`src/css/handsontable.css`

here is the link for white-spac https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

```diff
+.handsontable td.htAllowWrap {
+  white-space: pre-line;
+}
```

`src/renderers/textRenderer.js`

we only want the  `&nbsp` when we don't wrap and don't trim

```diff
-if (!instance.getSettings().trimWhitespace) {
+if (!instance.getSettings().trimWhitespace && !instance.getSettings().wordWrap) {
+//160 is &nbsp; which won't wrap and preserves sequences of whitespace
    escaped = escaped.replace(/ /g, String.fromCharCode(160));
}
```

`src/renderers/_cellDecorator.js`

we add a class because we no longer use the `&nbsp` to show whitespace

```diff

if (cellProperties.wordWrap === false && cellProperties.noWordWrapClassName) {
   classesToAdd.push(cellProperties.noWordWrapClassName);
}

+if (instance.getSettings().trimWhitespace === false && cellProperties.wordWrap) {
+  classesToAdd.push('htAllowWrap'); //maybe move this to a new var?
+}

```

**Comment by AMBudnik** [comment]
Thank you for doing the investigation @janisdd

**Comment by janisdd** [comment]
Please not that I found another issue which is related to this...

If you set `wordWrap:false` then the class `htNoWrap` is added to the cells. This will set css `white-space: nowrap` which does stop wrapping but also will also remove new line characters (visually)...

To fix this one would need to change the `htNoWrap` to set `white-space: pre` which will preserve spaces and new lines when you set `wordWrap:false`

Below a litte table (behaviour when the change is applied)

wordWrap | trimWhitespace | works?
---|---|---
false | false| no wrapping, whitespace is preserved (both because `white-space: pre` but `&nbsp;` *overwrites* this)
false | true | no wrapping (because of `white-space: pre`), whitespace is preserved (because of `white-space: pre`) (but should not preserve whitespace??)

As you can see `wordWrap: false` and `trimWhitespace: false` will not work properly as trimming is only applied after the cell was edited

So this might not be the correct solution if you want to preserve the current whitespace behaviour.

**Comment by AMBudnik** [comment]
Thank you for doing the investigation @janisdd 

We should also consider a case when we use HTML https://jsfiddle.net/handsoncode/u9zpwL7m/

**Comment by aninde** [comment]
This issue is solved with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/17a9owbq/. 
I have added it to https://github.com/handsontable/handsontable/issues/6465.  It should be in RN to the stable v8. CC: @scarletfog

**Comment by AMBudnik** [comment]
Hi @janisdd 

I’m more than happy to announce that Handsontable v8.0.0 that solves this issue is live!   Thank you again for sharing.

**CDN** https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
**NPM** npm i handsontable
**Release Notes** https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. 
I hope that the amount of work that we put on the v8 will help you to improve your project 💪

**Comment by janisdd** [comment]
Thanks for getting back to this.
I really appreciate your time and work you guys put into this project - 
In my opinion it's superior to any other solution out there (that's why I chose it ;).
