### ISSUE TITLE
Reset Table highlighted selections 

### ISSUE THREAD

**Issue by mahmoud-elnaggar2019** [handsontable/handsontable#6235]
### Description
I have a very simple question but I didn't find any answer on the docs :( 
I want to remove all selections to reset the table.
thanks :) 

### Your environment
* Handsontable 7.0.0:
* Browser Safari iOS

**Comment by AMBudnik** [comment]
Hey @mahmoud-elnaggar2019 

are you're looking for [deselectCell](https://handsontable.com/docs/7.1.1/Core.html#deselectCell)?

**Comment by mahmoud-elnaggar2019** [comment]
@AMBudnik  yes, but does it work too if I selected multiple row ?
Thanks 👍

**Comment by AMBudnik** [comment]
Yes, it resets all the selection. Here's an example https://jsfiddle.net/ftk6Lnwg/1/

**Comment by mahmoud-elnaggar2019** [comment]
@AMBudnik Thanks so much :)
