### ISSUE TITLE
beforeKeyDown runs after afterDocumentKeyDown

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6236]
### Description

The `beforeKeyDown` runs inside the `onAfterDocumentKeyDown` in the result when a developer adds logic to both hooks he gets `beforeKeyDown` result after `afterDocumentKeyDown`.

### Steps to reproduce

1. Click <kbd>ENTER</kbd> on `A1` cel with an opened console

![image](https://user-images.githubusercontent.com/10757813/64004410-800fa380-cb0e-11e9-8b73-8d832f922fe8.png)

### Demo

https://jsfiddle.net/7cnz2amh/1/

### Your environment
* Handsontable version: 7.1.1
_Does not relate to any version_
* Browser Name and version: Chrome 67
* Operating System: Windows 10

### Related
https://github.com/handsontable/handsontable/issues/3379

**Comment by AMBudnik** [comment]
It works the same for v 8.0.0 https://jsfiddle.net/AMBudnik/1gr409am/

**Comment by kirszenbaum** [comment]
As discussed with @wszymanski, this issue was fixed in #8955

**Comment by aninde** [comment]
Fixed with v12.0.0 https://jsfiddle.net/dz9L04tg/

`beforeKeyDown` is the first since this version.
<img width="383" alt="Screenshot 2022-03-14 at 19 11 57" src="https://user-images.githubusercontent.com/30186818/158234914-a07d15f5-1477-4b07-a923-f056fde3b7c2.png">

**Comment by AMBudnik** [comment]
Thank you all for participating in fixing this issue. Closed as done and published in [Handsontable v12](https://handsontable.com/docs/release-notes/#_12-0-0).
