### ISSUE TITLE
Undo changes after removed filter causes wrong cells to revert

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#6237]
### Description
I want to be able to filter the rows and make changes that I'm able to undo after I've removed the filters to show all rows again. But undo does not work as expected and the wrong cells are reverted.

### Steps to reproduce
- Filter table, for example to only show the last two row.
- Make changes to cells on each of the two visible rows
- Remove filters
- Undo changes (ctrl+z until changes are reverted)

Now you will notice that you need to press undo several times for the table to revert any changes and the wrong cells are changed.

### Demo
https://stackblitz.com/edit/handsontable-filterundo-issue

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @ottosson 

thank you for sharing the issue. This issue relates to the wrong indexes being used. The issue should be gone after introducing https://github.com/handsontable/handsontable/issues/5751 which is currently in progress.

**Comment by monu0751** [comment]
Undo is reverting wrong cells in case of  removing filter or after sorting columns.
Case 1 - Undo after sorting column
1) Do some changes in some cell.
2) Now, do sort on any column.
3) Apply undo(ctrl+Z), wrong cell gonna revert.

Case 2 - Undo after removing column filter
1) Filter any column (row index must change after filter)
2) Update any cell
3) Remove all filter
4) Apply undo(ctrl+Z), wrong cell gonna revert.

This is causing big data integrity issue.

Handsontable version: 7.4.0 (also tried 8.0.0 beta version)
Browser Name and version: Chrome
Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @monu0751 

It sounds like an issue that I have reported some time ago here https://github.com/handsontable/handsontable/issues/6475
Can you confirm?

**Comment by monu0751** [comment]
Hey @AMBudnik 

[#6475](https://github.com/handsontable/handsontable/issues/6475) is the same issue i am talking about.

**Comment by AMBudnik** [comment]
This issue remains the same after updating to v 8.0.0 https://jsfiddle.net/ne10p4uc/3/
This issue is related to https://github.com/handsontable/handsontable/issues/5636 and https://github.com/handsontable/handsontable/issues/6370

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Hi, @ottosson, I am more than happy to inform you that this issue was fixed in v14.6.0 (released today).

Here's an updated demo https://jsfiddle.net/71sogLrt/

CC @monu0751

**Comment by ottosson** [comment]
@AMBudnik that did not work for me...

Apply filter to show any two rows
remove contents of rows
remove any filter
press ctrl/cmd+z multiple times

![Oct-04-2024 15-54-06](https://github.com/user-attachments/assets/ed336d87-260c-4ec9-a7af-ad8003bae944)

**Comment by AMBudnik** [comment]
Thank you for sharing, @ottosson you are right. We followed the scenario at

#### Steps
1. Go to https://jsfiddle.net/mLanwj52/
2. Open dropdown menu for the B column
3. Filter out all the values besides et
4. Change both et values to et3
5. Open the dropdown again to show all of the values
6. Undo to change et3 back to et twice
**Result**: You are not able to get et back, ipsum becomes et, and elit becomes et.

but while using 14.6.0 with your new scenario we are left with empty data. Maybe it relates to altering many cells at once, not one by one. I will report that and get back to you upon fix.

**Comment by AutopilotNN** [comment]
@AMBudnik We faced a similar problem. In filter mode, undoing a row deletes another row.

https://github.com/user-attachments/assets/ec0033ab-7d35-40d5-aa95-b87820c8a1b3

**Comment by AutopilotNN** [comment]
When the filter is set to remove a row, action.actionType = = 'remove _ row' now adds the row to the end of the table and the recovered row replaces the next row with action.index. The last line remains empty.

**Comment by AMBudnik** [comment]
Thank you for sharing the use case, @AutopilotNN 
I believe the origin is the same, but I still made an additional note in the internal ticketing system.
