### ISSUE TITLE
date cells

### ISSUE THREAD

**Issue by JZoidberg** [handsontable/handsontable#624]
hi all,

i've specified some date cells using

```javascript
{ 
    type: "date",
    dateFormat: "mm/yy",
    changeMonth: false,
    changeYear: false
}
```

in principle that works fine. if i open the calendar and select a date the correct month and year are written into the matching cell. but if i reopen the calendar in that cell the date is automatically set to november 2018. any ideas? 

thanks!

**Comment by AMBudnik** [comment]
It should work fine by now. We had some major changes since this issue was written, especially in 0.12.6 release. If you would have any other questions, feel free to open a new issue.
