### ISSUE TITLE
How does data restore know the merged cells?

### ISSUE THREAD

**Issue by sxmny123** [handsontable/handsontable#6243]
### Description
I save the data of getSourceData() in the database.
 How does the loadData() method restore the merged cell (B2)?

### Steps to reproduce

1.
![image](https://user-images.githubusercontent.com/8567263/64221860-dca10300-cf00-11e9-9cbc-4bc002e6c3d3.png)

**Comment by AMBudnik** [comment]
Hey @sxmny123 

You'd need to create a copy of the data array. Both `getData` and `getSourceData` remove the values from merged areas.

**Comment by sxmny123** [comment]
@AMBudnik  Thank you very much for your reply
  But I understand
  I hope  Next time you enter the page  I can know which forms were merged.
  I want to keep the last operation on the form, not just the operation on the data.

**Comment by AMBudnik** [comment]
That's actually a good idea. You'll never have too much information to choose from.
