### ISSUE TITLE
When you verify it，the date in the form should be not allowed to input

### ISSUE THREAD

**Issue by DaiWenqi** [handsontable/handsontable#6247]
### Description

The date in the form is not allowed to input。Because when the user enters a letter, I can't submit it。How to disable input?
### Steps to reproduce

The config: 
"readOnly: true" and "edit:false " don't work!
columns:[{ data: "bianjiariqi", type: 'date', dateFormat: 'YYYY-MM-DD', validator: 'date', readOnly: true },......]

### Your environment
* Handsontable version: 7
* Browser Name and version: chrome
* Operating System: win7

**Comment by AMBudnik** [comment]
Hey @DaiWenqi 

I have to say that I got a bit lost here. The `readOnly` doesn't allow you to change a value in a cell. If you remove it the user is able to change the data. What other action you're lacking in with those settings? Maybe you can share a before/after desired result?

**Comment by DaiWenqi** [comment]
it's my mistake. I expect the date to be entered only with the keyboard, or with the mouse, which prevents the user from entering directly.In my scenario, I have a separate button to save data.If user makes a typo, I'm going to disable the save button。

Another question, can the drop-down box send json format?Because the database contains Numbers, the display is a string.This can be done in the native drop-down box. Now I have transformed the rendering and submission.

my table
![image](https://user-images.githubusercontent.com/3348055/64417595-fb9fc080-d0cb-11e9-8f1f-48658a675d8c.png)

**Comment by AMBudnik** [comment]
Currently, a dropdown source only accepts an array of string or an array of numbers.
