### ISSUE TITLE
Visible leading space disappears after editing cell

### ISSUE THREAD

**Issue by doakey3** [handsontable/handsontable#6252]
### Description

Visible leading space disappears after editing

### Steps to reproduce

Type the following into a cell:

```
* this is a bullet
    - this is a sub-bullet point
```
Notice that after editing, the leading space for the sub-bullet disappears.

### Demo

https://jsfiddle.net/vb3cuyfa/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Firefox 68.0.2
* Operating System: Arch Linux

**Comment by AMBudnik** [comment]
Hey @doakey3 

by default we remove whitespaces. You can revert this effect by settings up [`trimWhitespace`](https://handsontable.com/docs/7.1.1/Options.html#trimWhitespace) to `false`.
Updated demo https://jsfiddle.net/ehu5x0o7/
