### ISSUE TITLE
Not able to set value on all selections when SelectionMode = multiple and finishEditing ctrlDown = true

### ISSUE THREAD

**Issue by sirhoe** [handsontable/handsontable#6253]
### Description
[Per my thread here](https://forum.handsontable.com/t/multiple-select-mode-and-finishediting-ctrldown-true/3632). I am trying to enable multiple selection mode and set a value to all selections.

When I set set selectionMode: 'multiple' and create custom editor with finishEditing like this

```
finishEditing(restoreOriginalValue: boolean, ctrlDown: boolean, callback: Function) {
  super.finishEditing(restoreOriginalValue, true, callback);
}
```

Only the last cell changes. The documentation clearly says

> “If ctrlDown is set to true the new value will be set to all selected cells.”

The support manager in the thread (link above) seems to suggest that this is a bug and I would like to open an issue and track the progress here.

### Steps to reproduce
1. Overwrite the editor as described above, enable mutiple selectionMode.
2. Select 2 non adjacent cells, set a value
3. Expect both cells to be changes, but actual result only last cell was changed

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome 76 
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @sirhoe 

as discussed on the forum, we already have a corresponding subject raised here https://github.com/handsontable/handsontable/issues/4869 so I'm closing this topic.

However, if you feel that we did not cover the subject entirely please feel free to leave a comment.
