### ISSUE TITLE
Is there any 'tooltip'-like feature that can be applied to cells?

### ISSUE THREAD

**Issue by maguito77** [handsontable/handsontable#626]
Dear Marcin,

First of all I would like to congratulate you and the team behind this awesome piece of software named Handsontable. It is trully amazing!

I'm creating a project where I have the user to insert data in free form in a Handsontable, and, when finished, the user clicks the 'save' button and the PHP behind does all validations, analysis, and returns only the cells that contains any kind of validation problems back to the user in the same HOT. The cells approved in the validation are filtered from the user screen with a query (not an issue).

My validation script is actually writing 2 fields in the database (that feeds the HOT): err_fields and err_msg. I'm writing the data in the following format:

err_fields -> field1;field3;field5  (name of the fields, separated by ; )
err_msg -> field1 must be numeric, 9 chars long; field3 must have a value; field5 must be blank (error messages, per field, separated by ; )

All of the data flows are being done with the AJAX component, with no issue.

What I am looking for to do is:
1. paint the 'error' fields (described in err_fields field) in red, to call user attention that there is an error in that field -> I can actually do that by programatically call the renderers available in HOT (so, this is partially solved).
2. I would like to have a way for the user, by hovering the mouse over the fields with errors, the ones pained in red from item 1 above, to get like a tooltip text being presented, with the data I have defined in the err_msg field.

Note that the 'error' cell might vary from one line to another. I.e, line 1 might have fields 1 and 2 failed, line 2 might have only the field 2 failed, line 3 might have fields 1 and 3 failed, and so on. So, I need the feature to be customizable row by row.

Do you think that this might be feasible? I'm quite new to JQuery, I see in their website the wonderful things it can do, but I don't have an idea how to implement such a thing.

Many thanks in advance!
Eloi (from Brazil).

**Comment by phasjim** [comment]
@sahinci Same please! Thank you

**Comment by kevinyuliawan** [comment]
I used bootstrap's tooltip to create tooltips for cells on hover. In my code, on a cell edit, I'm first saving the cell to the server and then getting the validation errors back from the server. If I have validation errors, then I add an invalid property and set the error message so that I can access it in the cell renderer, like this:

    if(errMessageFromServer){
      table.getCellMeta(rowIndex,colIndex).isInvalid = true;
      table.getCellMeta(rowIndex,colIndex).isValid = false;
      table.getCellMeta(rowIndex,colIndex).errorMessage = errMessageFromServer;
    }else{
      table.getCellMeta(rowIndex,colIndex).isValid = true;
      table.getCellMeta(rowIndex,colIndex).isInvalid = false;
      table.getCellMeta(rowIndex,colIndex).errorMessage = false;
    }

And my cell renderer looks like this:

    function myCellRenderer(instance, td, row, col, prop, value, cellProperties){
        Handsontable.renderers.TextRenderer.apply(this, arguments);
        if(cellProperties.isValid){
          Ember.$(td).addClass('cell-valid');
        }
        else if(cellProperties.isInvalid){
          Ember.$(td).addClass('cell-invalid');
        }

        if(cellProperties.errorMessage){
         $(td).tooltip({
            trigger: 'hover',
            title: prop + ' ' + cellProperties.errorMessage,
            placement: 'auto',
            container: 'body',
            template: '<div class="tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'
          });
        }else{
          $(td).tooltip('destroy');
        }

        return td;
      },

I had to make sure the tooltip's container is set to 'body', otherwise triggering the tooltip would cause the cell's size to change. Another important thing to make sure is to call table.render() after applying the cell meta changes, so that the cells are then rerendered with the appropriate tooltip and classes.

**Comment by phasjim** [comment]
@kevinyuliawan Thanks! I'll check your method out

**Comment by kevinyuliawan** [comment]
@phasjim Good to hear :)

**Comment by kevinyuliawan** [comment]
@NDDC what in particular are you having an issue with?

**Comment by NDDC** [comment]
I need a column of date and time

**Comment by AMBudnik** [comment]
Hi @NDDC 

if you do not want to add comments you can use a `title` attribute of a DIV element. A DIV wrapper for the cell can be added via a custom renderer.
