### ISSUE TITLE
Displaying data in rows instead of columns

### ISSUE THREAD

**Issue by vix515** [handsontable/handsontable#6263]
data = [
    ['', 'Tesla', 'Nissan', 'Toyota', 'Honda', 'Mazda', 'Ford'],
    ['2017', 10, 11, 12, 13, 15, 16],
    ['2018', 10, 11, 12, 13, 15, 16],
    ['2019', 10, 11, 12, 13, 15, 16],
    ['2020', 10, 11, 12, 13, 15, 16],
    ['2021', 10, 11, 12, 13, 15, 16]
  ]
This is what handsontable will give me, [result](https://handsontable.com/docs/7.1.1/tutorial-data-binding.html)

This what I want. Basically transpose the data
Tesla     |10|10|10|10|10|
Nissan  |10|10|10|10|10|
Toyota  |10|10|10|10|10|
Honda  |10|10|10|10|10|
Mazda  |10|10|10|10|10|
Ford     |10|10|10|10|10|

Pretty much requested 6 years ago. Wanted to know if its possible now. [Link](https://github.com/handsontable/handsontable/issues/545)

**Comment by AMBudnik** [comment]
Hey @vix515 

we do not have a feature/approach on defining the object another way but you can use the helper

https://jsfiddle.net/handsoncode/Lhjxob68/

However, I do not know what you wanted to achieve with all the `10`'s in the second example. Shouldn't that be 

|2017|2018|2019|2020|2021|
Tesla|10|10|10|10|10|
Nissan|11|11|11|11|11|

.. and so on?

**Comment by AMBudnik** [comment]
I guess that we can close the issue, but if there's something I'm missing please let me know.
