### ISSUE TITLE
Using Arrow with handsontable

### ISSUE THREAD

**Issue by argenisleon** [handsontable/handsontable#6264]
Hi,

Is there any plan to support arrow format in handsontable? I think it's a better format for large data and can improve the general performance

**Comment by AMBudnik** [comment]
Hey @argenisleon 

can you share some details about the arrow format? 
I've searched the web but I could not find a way to connect it to an existing state of Handsontable and the way we handle indexes. 
However, that sounds like something interesting and I'd really like to know more about it.

**Comment by argenisleon** [comment]
I am still wrapping my mind around arrow. I will be back when I have more info. Did you check the repo https://github.com/apache/arrow/tree/master/js?

**Comment by AMBudnik** [comment]
Thank you for the link. We've already opened up a discussion about it.
I will update you as soon as we get any clarification.

**Comment by AMBudnik** [comment]
I have to admit that the subject created a very enthusiastic conversation in our dev team. This sounds like something that will meat Handsontable requirements.
I will add the 'improvement' label as we're working 24/7 to publish a new major version so we won't be able to dig deeper into the subject now.

**Comment by wojciechczerniak** [comment]
Thanks for bringing this to our attention. Looks amazing.

Unfortunately there are no plans to support arrow format in Handsontable anywhere soon. It may require rewriting our data source manager. We're working toward making it modular so prototyping such idea would be a lot easier. But until then I have to close this issue as non actionable.
