### ISSUE TITLE
About its header settings

### ISSUE THREAD

**Issue by Qingyiii** [handsontable/handsontable#6267]
Hi,I have a problem.
I want to know how to style column headers for editable and non-editable，
I couldn't find it anywhere.
Thanks..

**Comment by AMBudnik** [comment]
Hey @Qingyiii 

headers (for rows and columns) are not editable. You can add a custom logic via [`afterGetColHeader`](https://handsontable.com/docs/7.1.1/Hooks.html#event:afterGetColHeader)/[`afterGetRowHeader`](https://handsontable.com/docs/7.1.1/Hooks.html#event:afterGetRowHeader) but there are no tutorials for that.

**Comment by Qingyiii** [comment]
@AMBudnik  OK,Thank you,I'll try it.
