### ISSUE TITLE
[2.0.0] Scrolling to the last cell after removing the last column

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6272]
### Description
After removing the last column view is set on the last cell in the table (last, the most right one).
This behavior occurs since 2.0.0 versions.
Setting scrolling by adding overflow does not affect the occurrence of the problem.

### Steps to reproduce

1. Select the last column.
2. Remove column by context menu.

###  Actual result
 `clientWidth` is set on the last cell in the table.

###  Demo 
V. 2.0.0 http://jsfiddle.net/aninde/6Lempy1b/
![removing-last-one 2019-09-18 14_14_53](https://user-images.githubusercontent.com/30186818/65150663-e3616700-da24-11e9-97ea-d8e5951b2d43.gif)

###  Expected result
 `clientWidth` should not change, like in 
Demo in v. 0.38.1 http://jsfiddle.net/aninde/xg8daLmn/ without bug

###  Environment:
Handsontable version: since 2.0.0
Browser Name: any
Operating system: any

**Comment by aninde** [comment]
I'm closing the issue because it's a duplicate of [#5849](https://github.com/handsontable/handsontable/issues/5849).

**Comment by AMBudnik** [comment]
Referenced https://github.com/handsontable/handsontable/issues/5849 was fixed in v8.0.0
