### ISSUE TITLE
Pasting a copied cell that contains tab characters does not work

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#6273]
If you copy a cell that contains text which also includes one or more tab characters, those tab characters are not properly escaped and are interpreted as cell separators when pasting.  The result is that copying one such cell gets spanned into multiple cells when pasting.

**Comment by AMBudnik** [comment]
Hey @cgatesman 

I have replicated this behavior. I used this

`Tab here	bere	and there is no more tabs.`

after each `here` we have a tab. And it looks like this 

![image](https://user-images.githubusercontent.com/10757813/65244480-ecb50700-daea-11e9-8930-dea77086be83.png)

Tested on Windows 10 / Chrome 77. Demo https://jsfiddle.net/handsoncode/jf2v6re3/

@wojciechczerniak what do you think about this behavior?

**Comment by cgatesman** [comment]
Just wanted to point out, it gets even worse if you have newlines in the text.  Also note, some quotes become lost, as well:

```
Tab here "	" and
down here "	"
```

Pastes to:

<img width="425" alt="Screen Shot 2019-09-19 at 9 13 21 AM" src="https://user-images.githubusercontent.com/6276072/65247102-cc228800-dabd-11e9-8417-b4a43f6bccdc.png">

**Comment by AMBudnik** [comment]
There's already one issue mentioning quotes here https://github.com/handsontable/handsontable/issues/6167 but thank you for the example.

**Comment by wojciechczerniak** [comment]
@AMBudnik: Excel and Google Spreadsheet does the same

![Screenshot 2019-09-19 at 15 15 03](https://user-images.githubusercontent.com/4718998/65247290-6f8c9080-daf0-11e9-9538-cbb6347c2a75.png)
![Screenshot 2019-09-19 at 15 15 48](https://user-images.githubusercontent.com/4718998/65247295-71565400-daf0-11e9-8b5d-7bb9a9cbbf6e.png)

**Comment by cgatesman** [comment]
@AMBudnik see my edited comment.

**Comment by AMBudnik** [comment]
@wojciechczerniak can you check the second example of @cgatesman 
I don't Excel but I've tested it in Google Sheets

Google Sheets
![image](https://user-images.githubusercontent.com/10757813/65247523-cf833700-daf0-11e9-87ff-2b69be55476d.png)

Handsontable 
![image](https://user-images.githubusercontent.com/10757813/65247579-e75abb00-daf0-11e9-8096-995722f471d8.png)

**Comment by cgatesman** [comment]
If you paste this into an Excel cell, then copy the cell and paste again, it pastes into a single cell.  If you paste it into an editor, then copy that text and paste back into Excel, it spans two rows retaining the quotes, but converts the tabs to a single space.

I suspect when copying and pasting directly from Excel works, because it is copying different formats into the clipboard and using the appropriate one for Excel (clipboard supports multiple formats when writing data to it).  This probably isn't possible with a browser/JavaScript, but I do think this could be handled a little better in Handsontable--even if it's a matter of converting tab characters to spaces (what I will probably do as a quick fix).  If anything, it shouldn't be interpreting the tabs as a break to the next cell when the pasted data is in quotes.

**Comment by wojciechczerniak** [comment]
@AMBudnik Same as Google Spreadsheet. 

![Screenshot 2019-09-19 at 15 22 08](https://user-images.githubusercontent.com/4718998/65247795-4ddfd900-daf1-11e9-87e2-2c83d8704cd3.png)

But I would call their behavior inconsistent. It's not related to quotes because they still split the clipboard into multiple lines but then they ignore tabs inside those lines. Maybe @swistach will remember something more.

Excel, Google Spreadsheet and Handsontable will all paste the value correctly if you open the editor. Otherwise they try to parse it to a table with various results.

At least our behavior is consistent.

**Comment by wojciechczerniak** [comment]
@cgatesman You're right. Excel has it's own MIME type registered in system clipboard. We have only two `text/plain` and `text/html` available.

If we ignore tabs then we will break `text/plan` copy & paste to simple editors that doesn't support `text/html` format.

Checking for quotation is also tricky. We have to find the beginning and the end. If there are more of those that could easily break again. And we can't be sure that the quotation shouldn't just be distributed between cells. There should be a character that marks the end of a cell, and the tabulator is widely used.

We have to ask @swistach about his experience with other editors.

**Comment by cgatesman** [comment]
@wojciechczerniak, you're absolutely right (see my edit, above).  I guess the only real inconsistency in Handsontable, here, is when copying a single cell that contains tabs and pasting it into another cell causes it to span multiple cells.  This does not happen in Google Spreadsheets.

**Comment by cgatesman** [comment]
So, it looks like Google Spreadsheets converts tabs to 8 spaces when copying a cell.  This ensures that tabs in the data can only be used for cell separation.

I also have to point out that @wojciechczerniak is not right about Google Spreadsheet behaving the same way when pasting when you open the editor.  If you paste data with tabs in Google Spreadsheet while you have the cell editor open, it will ultimately convert those tabs to 8 spaces.  You can verify this by opening the editor back up after saving the cell and spacing over that area.

**Comment by cgatesman** [comment]
> @AMBudnik: Excel and Google Spreadsheet does the same

This is unfair as the problem is more about copying cells from the sheet, then pasting them back in.  Excel and Google Spreadsheet do not incorrectly span multiple cells when you do this like HOT does.

**Comment by wojciechczerniak** [comment]
@cgatesman This does not happen in Handsontable either. Once you open the editor you can paste the content with tabs. Then if you copy the cell it's copied and pasted as an `text/html` MIME type and Handsontable recognizes it as a single cell on paste.

This was introduced in version 7.1.0 if I remember correctly. Which version do you have? 

> So, it looks like Google Spreadsheets converts tabs to 8 spaces when copying a cell. This ensures that tabs in the data can only be used for cell separation.

You get different content than you've copied? Wow, didn't knew that. This isn't the content I wanted to paste. Looks like a bug to me. But you're probably right, it might be a feature 🙈  

You can do this with `beforePaste` hook.

**Comment by cgatesman** [comment]
> @cgatesman This does not happen in Handsontable either. Once you open the editor you can paste the content with tabs. Then if you copy the cell it's copied and pasted as an text/html MIME type and Handsontable recognizes it as a single cell on paste.

No.  I'm saying the problem is when you copy without opening the editor.  If I just select a cell that happens to have text with tabs, and copy it, then directly paste it somewhere else in the HOT (without opening a cell editor), it will paste across multiple cells.  This does not happen in Excel or Google Spreadsheets.

**Comment by wojciechczerniak** [comment]
Sorry, but I can't replicate the issue. I'm copying from a cell to a cell without opening the editor:

![Sep-20-2019 16-12-25](https://user-images.githubusercontent.com/4718998/65333878-9797f480-dbc1-11e9-8384-0c12b83d2a7d.gif)

Am I doing something wrong? Which version do you have?

**Comment by cgatesman** [comment]
I was testing on the Handsontable docs pages.  I'm sorry.  I can't reproduce it, either, now.  I guess I tried so many different scenarios that I got them mixed up, now.

Looking at versions, it look like this was fixed in 6.1.0, not 7.1.0.  I'm running an older version.

I could have sworn I tried this on the doc site before publishing this issue.  Maybe I was accidentally looking at an older version.  I apologize.

**Comment by cgatesman** [comment]
I realized what happened in my testing.  I copied from my older version of HOT and pasted into the new version on the HOT docs site thinking since it didn't work there, it was broken in the new version.  However, the fix to this problem was not in the pasting.  It was in the copying.

**Comment by wojciechczerniak** [comment]
No problem. That was a good discussion and I've learned something new. Hopefully this thread will help someone in the future. Great to know that it works for you @cgatesman
