### ISSUE TITLE
Only the data from the last selection area is copied

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6275]
### Description

Only the data from the last selection area is copied.

### Steps to reproduce

1. Click `A1`
2. Hold <kbd>CDM</kbd>/<kbd>Ctrl</kbd>
3. Click `A2`
4. Copy the cells
5. Paste them to `D1`

**Result**
Both cells should be pasted. But we only get `A2`.
![issue](https://user-images.githubusercontent.com/10757813/65228981-c03dc280-dacb-11e9-8bd5-f315e7e4869b.gif)

`afterCopy` logs https://jsfiddle.net/handsoncode/r1cv5oyp/

### Demo

https://jsfiddle.net/handsoncode/kwhca51L/ (`7.1.1`)
https://jsfiddle.net/handsoncode/o0v5eujp/ (`8.0.0.-rc1`)

### Your environment
* Handsontable version: 7.1.1.
_The issue doesn't seem to be related to any version_
* Browser Name and version: Chrome 77
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
Duplicate of #4878

**Comment by AMBudnik** [comment]
True, closing.
