### ISSUE TITLE
[7.0.0+] Untrimmed rows in specific situation break the table view

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#6276]
### Description
An extra `render` call used when there are trimmed rows reveals a problem with displaying the table.  

### Steps to reproduce

1. Trim any row.
2. Call `render`.
3. Call `intrimAll`.
4. The table is broken.

### Demo

https://jsfiddle.net/wojciech/27c8v5ru/

### Your environment
* Handsontable version: <= `7.1.1`
* Browser Name and version: Chrome
* Operating System: MacOS

**Comment by AMBudnik** [comment]
@wszymanski `7.0.0` was the one to introduce the issue

https://jsfiddle.net/handsoncode/1xrqtk57/ `6.2.2`
https://jsfiddle.net/handsoncode/cjvot6L8/ `7.0.0`

**Comment by wszymanski** [comment]
Btw. I've added test.

https://github.com/handsontable/handsontable/blob/86670e38446da8b52ddaa95dc370aa7de1dffe4a/src/plugins/trimRows/test/trimRows.e2e.js#L1231-L1253

**Comment by AMBudnik** [comment]
Works the same in 8.0.0-beta2-rev11 https://jsfiddle.net/AMBudnik/jmco8bwz/7/

![issue](https://user-images.githubusercontent.com/10757813/83859869-d2759480-a71e-11ea-8da4-64d5fca08f4a.gif)

**Comment by AMBudnik** [comment]
Looks the same in v 8.0.0 (works well after editing any cell)

![Zrzut ekranu 2020-08-13 o 10 40 22](https://user-images.githubusercontent.com/10757813/90113309-739d4e80-dd51-11ea-9de1-527d72fe47ff.png)
Updated demo https://jsfiddle.net/j940nfqz/

**Comment by jansiegel** [comment]
Seems to be fixed by #7286: https://codesandbox.io/s/handsontableexamples-pull-request-forked-ljtht?file=/src/index.js

Looks like it works on the currect state of `develop` (137b00ac) as well: https://codesandbox.io/s/handsontableexamples-pull-request-forked-ckh6t

Can you confirm, @AMBudnik?

**Comment by jansiegel** [comment]
In #7320 I ucommented @wszymanski's [test case](https://github.com/handsontable/handsontable/issues/6276#issuecomment-533125652).

**Comment by AMBudnik** [comment]
True @jansiegel 

Here's 8.1.0

![Zrzut ekranu 2020-10-7 o 13 41 34](https://user-images.githubusercontent.com/10757813/95328296-a8d3a200-08a5-11eb-9c12-0b410f1b7634.png)

and here's a fresh `develop` build

![Zrzut ekranu 2020-10-7 o 14 01 34](https://user-images.githubusercontent.com/10757813/95328338-b8eb8180-08a5-11eb-9013-2f9f4f43b395.png)

**Comment by aninde** [comment]
I'm glad to see that this issue will be fixed by the upcoming v8.2.0 https://jsfiddle.net/btn5h2g1/. Great job 👍 

![Screenshot 2020-11-03 at 16 14 35](https://user-images.githubusercontent.com/30186818/98004145-daca1c80-1def-11eb-904f-c9bb0a1d91d1.png)

Tested on macOS Catalina 10.15.7

Chrome Beta 87 and stable 86
FF 83.0b7 and stable 82
Safari 14 and Safari Technology Prev 14.1
Windows 10
Chrome 86
Edge 86
Edge Dev 88

**Comment by AMBudnik** [comment]
This issue is closed as solved for version 8.2.0. Thanks for fixing!
