### ISSUE TITLE
Lazy load nested children rows with loadData()

### ISSUE THREAD

**Issue by s1monj** [handsontable/handsontable#6279]
I have large numbers of nested rows, so I would like to lazy load the nested children rows from the server only when the parent is expanded.

When I call `hot.loadData()` with the updated nested data object followed by `hot.render()` it does not appear to recognise the new `__children` data. Please see:
https://jsfiddle.net/simonlj/owk5rnum/115/

Also, I understand this plugin is in alpha, but I am hoping to implement this kind of use case:

1. My customCellRenderer renders a ▶ _click to expand row_ button for each collapsed row
2. On click, the button changes to a ◌ spinner and fires off a request for children for this row ID
3. After the response is received, it calls `loadData()` with the children data, the row expands to display the children and the customCellRenderer replaces the the spinner with a ▼ _click to collapse_ button
4. On click, the children data is purged and calls `loadData()` again, which should now collapse the row (because there are no longer children values) and the customCellRenderer shows a  ▶ _click to expand row_ button again

**Comment by AMBudnik** [comment]
Hey @s1monj 

We should check if the following case still behaves the same after using the latest `develop` changes (related PR https://github.com/handsontable/handsontable/pull/6015).

Currently, we do not get any error, it looks like the table is immune to `loadData`.

**Comment by AMBudnik** [comment]
I've build a Handsontable from `develop` branch after introducing https://github.com/handsontable/handsontable/pull/6015

and it solves the problem

![image](https://user-images.githubusercontent.com/10757813/65409439-048cd380-dde8-11e9-9852-7e63d4e12255.png)

**Comment by AMBudnik** [comment]
Closed by https://github.com/handsontable/handsontable/issues/3914

**Comment by AMBudnik** [comment]
Hi @s1monj 

We just fixed an issue related to yours. Please update to 8.0.0-beta1 and check if it solved for you as well.

Below are the resources

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```

And this is how you can download the beta from NPM

`npm i handsontable@beta`
