### ISSUE TITLE
callback for on edit begin? [improvement]

### ISSUE THREAD

**Issue by jcollum** [handsontable/handsontable#628]
I'm considering adding this in as a pull request, but want to make sure that I'm not missing something. I'd like to put in a callback that at the beginning of  HandsontableTextEditorClass.prototype.beginEditing. The callback would allow the editor to get a "real" value for that cell, as opposed to a "display" value. I don't see anything in the code like this, but there is an onBeginEditing  in HandsontableHandsontableEditorClass.prototype. 

Ideally I want to store a "display" version of the data and an "edit" version.

**Comment by yuwong** [comment]
Event for before and after editing would be definitely be useful to have

**Comment by alvarotrigo** [comment]
+1

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
