### ISSUE TITLE
Misleading function description

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6281]
![image](https://user-images.githubusercontent.com/10757813/65425507-68c28e00-de0e-11e9-92c6-f7fc1d51cdbc.png)

https://github.com/handsontable/handsontable/blob/98878a6bb6edbed065b7961bc97d4b799e908503/src/3rdparty/walkontable/src/calculator/viewportColumns.js#L25

**Comment by aninde** [comment]
Changed in `7.1.2` https://github.com/handsontable/handsontable/blob/c6579078ce2801b313f7a74a7ec88e0eb572e5cb/src/3rdparty/walkontable/src/calculator/viewportColumns.js#L25
