### ISSUE TITLE
count row selected

### ISSUE THREAD

**Issue by awenger63** [handsontable/handsontable#6285]
### Description
How is it possible to count number of rows selected, without duplicate (if they are selected twice whit CTRL there are Always selected and add on getSelected) and count the line in range

### Steps to reproduce
Select some rows whit SHIFT (range) and CTRL (twice same line)
I would use getSelected().length, but this not contain rigth value if rows are seleted by Range or by duplicate sélection.

### Your environment
* Handsontable version: 6.1.1

Is it possible to have sum of amount of each range selected whit no duplicate ?
Something like countSelectedRows() ?
Thanks for your help

**Comment by AMBudnik** [comment]
Hey @awenger63 

maybe something like this https://jsfiddle.net/msj2b5tp/ 
I'm using the `indexOf` to check if the index is already in the array of selected row indexes.
Will that meet your requirements?

**Comment by awenger63** [comment]
Hi @AMBudnik 
Thanks for your code, This could be work whit CTRL selection, but not with SHIFT where selected is a range.

**Comment by AMBudnik** [comment]
You're right. Fortunately, there's a way to get this data as well.
The hook allows you to get all the coordinates
`afterSelectionEnd: function(r,c,r2,c2){}`
so what you should do is to ass a loop where `row` variable can be a value between `r` and `r2`

**Comment by awenger63** [comment]
@AMBudnik  Yes this could be, but not work when selection change and remove some row.
But whit your help and your example, I found a great solution work in case of all change selection : 
`var myRows = [];`
`for (range of PF('listCopyrightWidget').ht.getSelectedRange()) {`
`  for (i=range.from.row; i <= range.to.row; i++) {`
`   if(myRows.indexOf(i) < 0){`
`    myRows.push(i);`
`   }}}`
`console.log(myRows);
                            `

What do you mean ? 
For me it's look like ready, It'is exactly my function countSelectedRows() when return myRows.length.
Hope this can help other user.

**Comment by AMBudnik** [comment]
Yes... moving, deleting etc. would require some alterations. And only by testing you'd be able to check if you've covered all the scenarios.
