### ISSUE TITLE
fixedColumnsLeft not working correctly with hiddenColumns plugin

### ISSUE THREAD

**Issue by vk-sourcefuse** [handsontable/handsontable#6287]
### Steps to reproduce

Simply try horizontal scrolling, you'll see that fixedColumnsLeft is set to 5, but only 2 are fixed, because other are hidden. 5 visible columns should be fixed, no matter how many columns are hidden. 

### Demo
http://jsfiddle.net/1hdn8smz/

### Your environment
* Handsontable version: Any
* Browser Name and version: Any
* Operating System: Any

**Comment by AMBudnik** [comment]
Hey @vk-sourcefuse 

Firstly you fix 5 columns and then some of then get hidden. That is an intended behavior that can be seen in Google Sheets and Excel.

Below's Google Sheets and a situation where we fix 5 columns and hide B:D. 
![Zrzut ekranu 2019-09-25 o 12 51 28](https://user-images.githubusercontent.com/10757813/65594710-9d138700-df93-11e9-88d3-060df7aaa336.png)
Excel and Google Sheets do not move the fixed columns for further rows that is why we would not want to break this rule.

**Comment by vk-sourcefuse** [comment]
Okay thanks, 
As a solution, we'll give option to user to select column name by a dropdown, till that column they want to fix, internally we'll find the column-number and  will set value of fixedColumnsLeft.
