### ISSUE TITLE
getSelectedRange not update on SHIFT upstair rows selection

### ISSUE THREAD

**Issue by awenger63** [handsontable/handsontable#6288]
### Description
If you make a SHIFT row selection  Bottom to top, Selected Range data are not update

### Steps to reproduce
Select a row by mouse click  in the middle of the table
press [SHIFT] and select an other line/row upstair of this line
See on console the value of property getSelectedRange(), it is empty !

This is not happen if you select a line in the Bottom, property content the rows really selected !

### Your environment
* Handsontable version: 6.1.1

is it a bug ?

**Comment by AMBudnik** [comment]
Hey @awenger63 

it seems to work as expected in `7.1.1`.
Please check this demo https://jsfiddle.net/0ch3kaxd/ and let me know if it works for you.

**Comment by awenger63** [comment]
@AMBudnik  Yes this work and in 6.1.1 too, it is an error on my side, because when selection is  to top from the Bottom, 'from' is bigger thant 'to', Obviously ! Loop for count must be decrease
Sorry for that, all it's ok.
thanks a lot for your response

**Comment by AMBudnik** [comment]
Thanks for checking @awenger63
