### ISSUE TITLE
Change: name of autoColumnSize method getColumnWidth

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6289]
Name of [`getColumnWidth`](https://handsontable.com/docs/7.1.1/AutoColumnSize.html#getColumnWidth) is confusing to users. It can be easily confused with core method [`getColWidth`](https://handsontable.com/docs/7.1.1/Core.html#getColWidth).
I propose to change name to `getCalculatedColWidth`. @wojciechczerniak WDYT?

**Comment by wojciechczerniak** [comment]
The method is namespaced. Plugin author can name methods anyway she wants. It's not possible to coordinate all internal and external plugins method names.

I agree that the proposed change could improve it slightly, but it's not important enough to introduce a breaking change. Wontfix.
