### ISSUE TITLE
Add Rich Text Editor

### ISSUE THREAD

**Issue by singhalavi** [handsontable/handsontable#629]
We should be able to define a column to use richtext editor also it will be good if there is a option "Edit in RichText Editor" on right click

**Comment by PeterRangelov** [comment]
+1. It would be fantastic to have a cell type "rich text" in addition to the existing ones:
- text
- numeric
- checkbox
- date
- autocomplete

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by samuelstein** [comment]
is there any implementation progress on this issue?

**Comment by AMBudnik** [comment]
Unfortunately we do not have this feature in our Roadmap for this year.
You can track what we are doing here: https://trello.com/b/PztR4hpj/handsontable-roadmap-2016

**Comment by dsc-ian** [comment]
Any update on this feature?

**Comment by AMBudnik** [comment]
We'd love to have this feature in Handsontable. With a team of 5 (devs) now we need to focus on tasks that
* improve/fix performance
* fixes issues
* avoid regressions

With a Roadmap like this is it really hard to push such a time-consuming feature. However, that's surely something that we have on the back of our heads and would like to add as soon as possible.

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
