### ISSUE TITLE
Export table to pdf 

### ISSUE THREAD

**Issue by wisnubaldas** [handsontable/handsontable#6290]
### Description

Hi, How can I export my table to pdf file?

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/
![image](https://user-images.githubusercontent.com/10908214/65663427-fbf30200-e060-11e9-9ffb-2a984ba5ee17.png)

### Your environment
* Handsontable version:7
* Browser Name and version:Mozilla Firefox
* Operating System:linx mint

**Comment by AMBudnik** [comment]
Hey @wisnubaldas 

we do not have a built-in system for exporting tables to .pdf. But there are a couple of great libraries that are under MIT license and can do that easily.

**Comment by hanstsangcwc** [comment]
i use soffice, it will looks like exactly the same as excel
