### ISSUE TITLE
when copy the data from Excel file to page, the blank can not be skip and default as data.

### ISSUE THREAD

**Issue by yanglinpvp** [handsontable/handsontable#6291]
### Description
when copy the data from Excel file to page, the blank can not be skip and default as data.

### Steps to reproduce

1. Create a new page 
![image](https://user-images.githubusercontent.com/19279918/65686059-0da2cc80-e096-11e9-8e16-be80f95ca4c1.png)
a
 
2.copy data with blank row from excel file 
![image](https://user-images.githubusercontent.com/19279918/65686124-3a56e400-e096-11e9-886c-a14e3ea1cd8b.png)

3.paste on the corresponding position of the page 
![image](https://user-images.githubusercontent.com/19279918/65686328-b51fff00-e096-11e9-9447-39cc81bb4a15.png)

4.click save
![image](https://user-images.githubusercontent.com/19279918/65686507-48f1cb00-e097-11e9-824a-ea60f222451d.png)

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey,

as there is no demo I just tested our base example https://handsontable.com/docs/7.1.1/demo-scrolling.html and copied data from Google Sheets.

![Zrzut ekranu 2019-09-26 o 14 20 50](https://user-images.githubusercontent.com/10757813/65687174-2943ae00-e069-11e9-9bf1-31ea2f76f4a9.png)

and here's the result

![Zrzut ekranu 2019-09-26 o 14 21 05](https://user-images.githubusercontent.com/10757813/65687183-2fd22580-e069-11e9-80f3-343fba2bb291.png)

That is correct.

Please try to copy the same data and paste here https://handsontable.com/docs/7.1.1/demo-scrolling.html

**Comment by yanglinpvp** [comment]
Hi，

 

As I tested my data on the link https://handsontable.com/docs/7.1.1/demo-scrolling.html , there still exist the same the problem, the details are as follows:

Step1: open my data demo and copy the data



Step2: paste data on the page. When I focus the pointer in the blank cell, a blank can be seen .



 

Step2: I move the pointer and refocus on the in the blank cell, a blank disappeared .



 

 

发件人: yanglinpvp@163.com [mailto:yanglinpvp@163.com] 代表 Aleksandra Budnik
发送时间: 2019年9月26日 20:24
收件人: handsontable/handsontable
抄送: yanglinpvp; Author
主题: Re: [handsontable/handsontable] when copy the data from Excel file to page, the blank can not be skip and default as data. (#6291)

 

Hey,

as there is no demo I just tested our base example https://handsontable.com/docs/7.1.1/demo-scrolling.html and copied data from Google Sheets.

 <https://user-images.githubusercontent.com/10757813/65687174-2943ae00-e069-11e9-9bf1-31ea2f76f4a9.png> Zrzut ekranu 2019-09-26 o 14 20 50

and here's the result

 <https://user-images.githubusercontent.com/10757813/65687183-2fd22580-e069-11e9-80f3-343fba2bb291.png> Zrzut ekranu 2019-09-26 o 14 21 05

That is correct.

Please try to copy the same data and paste here https://handsontable.com/docs/7.1.1/demo-scrolling.html

**Comment by AMBudnik** [comment]
I have asked our Tester to check this issue out on her device and Excel but she got the same (expected) result.

Can you please record the behavior? Maybe it will help us to check what's the difference between your actions and ours.

**Comment by AMBudnik** [comment]
Hey @yanglinpvp 

did you have time to record the behavior? We're not able to replicate the issue on any device.

**Comment by AMBudnik** [comment]
I guess that we can close the issue report as there is no reply and we were not able to replicate the issue.
