### ISSUE TITLE
[8.0.0-rc1]  Visual width is improper after moving column

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6292]
### Description

Visual width is improper after moving column. I looks like the width take wrong column index or column index it is not changing after moving column. 
Without enabling `updateSetting` `getColumnWidht` is showing proper columns width, like it should be, but it doesn’t rendering.  `render()` doesn't fix it. 

This bug occurs since the first `8.0.0-rc1` v. Can be related to fixed #4666.
This bug doesn't occur in `7.1.1.`

**Start point:** 
col3 is the widthest.
col1 and col2 have the same width.
![start](https://user-images.githubusercontent.com/30186818/65695926-b04c5280-e078-11e9-9a49-ffd65c037aca.png)

**Case 1**
**Steps to reproduce**
Drag first column (col1) to the right after col3.
 col1 should be last column in table.

**Result**
v. `8.0.0-rc1` - bug
![1 8 0 0](https://user-images.githubusercontent.com/30186818/65695143-41222e80-e077-11e9-8087-962b4d550635.png)
**Expected result**
The width of the columns aren't changed after moving.
v. `7.1.1` - works
![1 7 1 1](https://user-images.githubusercontent.com/30186818/65695173-513a0e00-e077-11e9-96e0-0666e4a6576e.png)

**Case 2**
**Steps to reproduce**
Drag col3 between col1 and col2
**Result**
v. `8.0.0-rc1` - bug
![case2 - 8 0 0](https://user-images.githubusercontent.com/30186818/65695217-6a42bf00-e077-11e9-8e99-fe2a5ade3a67.png)
**Expected result**
v. `7.1.1` - works
![case 2 - 7 1 1](https://user-images.githubusercontent.com/30186818/65695224-6ca51900-e077-11e9-9aeb-7d0a3aee27c4.png)

**Case 3**
**Steps to reproduce**
Drag col3 before col1.
 col3 should be the first column in the table
**Result**
v. `8.0.0-rc1` - bug
![case3 - 8 0 0](https://user-images.githubusercontent.com/30186818/65695252-762e8100-e077-11e9-9de7-85915e92108e.png)
**Expected result**
v. `7.1.1` - works
![case3 - 7 1 1](https://user-images.githubusercontent.com/30186818/65695261-79297180-e077-11e9-8bd7-ffc3a2321f14.png)

### Demo
v. latest `8.0.0rc-1` https://jsfiddle.net/aninde/yxpmc9z7/
oldest v. `8.0.0-rc1` https://jsfiddle.net/aninde/peo39vsh/
without bug v. `7.1.1.` https://jsfiddle.net/aninde/98vtw25u/ 

### Your environment
* Handsontable version: any `8.0.0-rc1`
* Browser Name and version: any
* Operating System: any

@wojciechczerniak @wszymanski WDYT?

**Comment by aninde** [comment]
Same bug with improper width can be caused by `manualColumnFreeze`. 
if you freeze column, freezed column is moved on index 0 (first column in the table). However it takes the width of the column that was there before the move.

**Case 4**
Freeze the last, widest column.

**Result**
Freezed column is moved on index 0 and has improper width of 95 px, like has column1 before move. Now, the widhest is column1. 

![Screenshot 2019-10-01 at 14 32 15](https://user-images.githubusercontent.com/30186818/65962206-77392700-e458-11e9-870c-4a694c2f94ab.png)

**Expected result:** 
v. `7.1.1` 
![Screenshot 2019-10-01 at 15 32 06](https://user-images.githubusercontent.com/30186818/65967160-7789f000-e461-11e9-803e-ad217033cc71.png)



Demo:
bug v. `8.0.0-rc1` https://jsfiddle.net/aninde/ucn47rb3/
works v. `7.1.1` https://jsfiddle.net/aninde/2uyeawvz/

**Comment by wszymanski** [comment]
It should be fixed:

https://cdn.jsdelivr.net/gh/handsontable/handsontable@7e09f185cbeca686bb909f36dc6cc56b6869aba8/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@7e09f185cbeca686bb909f36dc6cc56b6869aba8/dist/handsontable.full.css

**Comment by aninde** [comment]
@wszymanski it fixed by the new build of `8.0.0-rc1`. Thank you.

After move, the widest column keeps its width.
![Screenshot 2019-10-08 at 11 59 24](https://user-images.githubusercontent.com/30186818/66386896-2cbd2a80-e9c3-11e9-99c7-55be174e6b1f.png)

**Demo:**
`freezing` - fixed `8.0.0-rc1` https://jsfiddle.net/aninde/Lwz62cs3/
`manualColumnMove` fixed `8.0.0-rc1`  - https://jsfiddle.net/aninde/a5r2b6v0/

**Comment by aninde** [comment]
Still works on the [newest](https://github.com/handsontable/handsontable/pull/5945#issuecomment-544983941) version of `8.0.0-rc1`.
demo: https://jsfiddle.net/aninde/o3gmqybd/

**Comment by AMBudnik** [comment]
Works well on IE 11 as well. Tested version `8.0.0-rc1` form the release build.

**Comment by aninde** [comment]
Still fixed in `8.0.0-beta2-rev15`https://jsfiddle.net/aninde/q73xypwg/ .
Due to the fact that `8-beta1` has already been released and this issue did not appear in the stable version 7+, I close it.
