### ISSUE TITLE
Is there an option for contextmenu to be inside a container instead of document.body

### ISSUE THREAD

**Issue by bellcliff** [handsontable/handsontable#6293]
### Description
For now, context menu is always attached to document.body, when we prefix all css, the css of handsontable is prefixed, which cause the context menu not have style at all due to the context menu is outside the app container (on which we assign the prefix class)

**Comment by wojciechczerniak** [comment]
Unfortunately no. @swistach is working on this feature in #6283 but we have no ETA

**Comment by AMBudnik** [comment]
Hey @bellcliff 

We just fixed an issue related to your. Please update to 8.0.0-beta1 and check if it solved for you as well.

Below are the reources

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```

And this is how you can download the beta from NPM

`npm i handsontable@beta`
