### ISSUE TITLE
Can I customize the formula?

### ISSUE THREAD

**Issue by sxmny123** [handsontable/handsontable#6294]
We have some special calculation formulas in our lab, such as RSD. Can I create this formula?

**Comment by AMBudnik** [comment]
Hey @sxmny123 

the formulaJS (that we use to develop `Formulas` plugin) https://github.com/handsontable/formula-parser allows creating new formulas.

![Zrzut ekranu 2019-09-27 o 12 01 27](https://user-images.githubusercontent.com/10757813/65761163-949b8780-e11e-11e9-9f96-c7cbcb70972a.png)
