### ISSUE TITLE
The -after hooks for creating and removing rows/columns are not well described in the definition file

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6296]
### Description
We are able to set a custom `source` of change in the [`alter` method](https://handsontable.com/docs/7.1.1/Core.html#alter) 

```js
alter(action: 'insert_row' | 'insert_col' | 'remove_row' | 'remove_col', index?: number | Array<[number, number]>, amount?: number, source?: string, keepEmptyRows?: boolean): void;
```

and works fine, but we do not have this ability defined in the definition file for the `-after` row/column hooks listed below

```js
      afterCreateCol?: (index: number, amount: number) => void;
      afterCreateRow?: (index: number, amount: number) => void;
      afterRemoveCol?: (index: number, amount: number) => void;
      afterRemoveRow?: (index: number, amount: number) => void;
```

we also do not mention that the `remove-` alterations provide the `physicalColumns` as mentioned in the docs.

![Zrzut ekranu 2019-09-27 o 15 11 00](https://user-images.githubusercontent.com/10757813/65771689-0c76ab80-e139-11e9-80ae-b768f9fb96a9.png)

However, all seem to be typed well for the `-before` hooks

```js
      beforeRemoveCol?: (index: number, amount: number, physicalColumns: number[], source?: ChangeSource) => void;
      beforeRemoveRow?: (index: number, amount: number, physicalColumns: number[], source?: ChangeSource) => void;
      beforeCreateCol?: (index: number, amount: number, source?: ChangeSource) => void | boolean;
      beforeCreateRow?: (index: number, amount: number, source?: ChangeSource) => void;
```

### Steps to reproduce

1. Look what's return in the console

### Demo
http://jsfiddle.net/mr7gw2xj/1/

![Zrzut ekranu 2019-09-27 o 15 14 59](https://user-images.githubusercontent.com/10757813/65771961-97f03c80-e139-11e9-9d34-3b65298b3f42.png)

### Your environment
* Handsontable version: 7.1.1.
_Not related to any version_
* Browser Name and version: Chrome 77
* Operating System: macOS Mojave

**Comment by aninde** [comment]
IMHO result in `7.1.2` is the same http://jsfiddle.net/aninde/0jmq54ky/ like in `7.1.1`

![Screenshot 2019-10-10 at 18 14 25](https://user-images.githubusercontent.com/30186818/66586978-d6e6af00-eb89-11e9-9788-352ac6f100a9.png)

@wojciechczerniak what do you think?
