### ISSUE TITLE
[Feature Request] Handle result of custom validation functions

### ISSUE THREAD

**Issue by davestewart** [handsontable/handsontable#6298]
# Proposal

**A backwards-compatible fix to pass custom validation errors to validation hooks**

## Problem
Right now, the result of validation functions is true or false.

This means we can't do anything with errors that are generated, without clever workarounds (such as re-validating, storing the errors elsewhere, etc).

### Validation callbacks

If we could pass the result of any validation as a second parameter to the callback, this could then be passed in as a final parameter to the validation hooks:

```js
function validateRate (value, process) {
  validator.validateField(value, 'rate').then(error => {
    process(!error, error)
  })
}
```

### Core update

In the HoT core, the following would be backwards-compatible, but allow error messages to be handled in hooks:

https://github.com/handsontable/handsontable/blob/master/src/core.js#L1109-L1126
```js
        validator.call(cellProperties, value, (valid, error) => {
          if (!instance) {
            return;
          }
          // eslint-disable-next-line no-param-reassign
          valid = instance.runHooks('afterValidate', valid, value, cellProperties.visualRow, cellProperties.prop, source, error);
          cellProperties.valid = valid;

          done(valid);
          instance.runHooks('postAfterValidate', valid, value, cellProperties.visualRow, cellProperties.prop, source, error);
        });
```

### Hook implementation

And in the hook:

```js
afterValidate (valid, value, cellProperties.visualRow, cellProperties.prop, source, error) {
  // do something with error
}
```

### Other concerns

Not sure how to access the TD from afterValidate... but would be useful to be able to do something like set a `data-error` property on the cell.

We are currently storing errors separately and using some other code to retrieve them as needed:

![image](https://user-images.githubusercontent.com/132681/65773724-b56ed780-e134-11e9-9b9e-723eaa8b895e.png)

I would be happy to submit a PR if I knew it would get seen to soon, but there are lots of tickets out there!

**Comment by AMBudnik** [comment]
👍 for this feature request.

A few weeks ago I've came across [a cool toastr lib](https://github.com/akserg/ng2-toasty). 
What we would need to get this lib working smoothly is the validation state manager. They also mention `warning` - which would be something like closing editor with `allowInvalid: false` on an autocomplete cell type, but now - we do not have an ability to inject an action there.

**Comment by wojciechczerniak** [comment]
@davestewart  What about `cellProperties` ?

Validator is called with Cell Meta as the context. You can add errors (in my example there can be multiple validation errors) and renderer can read from Cell Meta to use them to display the messages.

It has access to TD, and there is only one rendering cycle etc.

https://jsfiddle.net/rz7n0apo/1/

**Comment by davestewart** [comment]
Aha! OK, thanks for the input - I'll look into this

**Comment by davestewart** [comment]
FWIW, It would still be useful to be able to pass the result of the validation to the `afterValidate` hook...

**Comment by wojciechczerniak** [comment]
I think it's scattered across different tutorials. And is named either `cellProperties` or `cellMeta`. We should write a tutorial for meta as they're getting more and more useful.

> FWIW, It would still be useful to be able to pass additional data (i.e. the result of the validation) to the afterValidate hook...

In `afterValidate` hook you can `getCellMeta(row, col)`: https://jsfiddle.net/Lnud62p8/

**Comment by davestewart** [comment]
> In afterValidate hook you can getCellMeta(row, col): https://jsfiddle.net/Lnud62p8/

Ah I see, so you're basically saying cell meta is your single source of truth. Use it or lose it.

**Comment by wojciechczerniak** [comment]
Yes. Lets say "cell state" that `renderer` will recreate each time it changes: format, formula, styles, validation, even value. Some ideas are here: #6274

Although we have a bug that might prevent everyone from using to it's full potential: #6051 #6063 We're pushing hard to fix those first.

**Comment by davestewart** [comment]
@wojciechczerniak 

So I just worked with your example - it works great!

- https://jsfiddle.net/davestewart/xcjnsf8u/19/

FYI, in my app, the instance seems to be `ColumnSettings` not cell meta / properties, which is a bit confusing as I know column settings are something completely different:

```
validate: ColumnSettings {row: 5, col: 8, visualRow: 5, visualCol: 8, prop: "collateralBasketNames", …}
validate: ColumnSettings {row: 5, col: 7, visualRow: 5, visualCol: 7, prop: "termEndDate", …}
validate: ColumnSettings {row: 5, col: 6, visualRow: 5, visualCol: 6, prop: "settlementDate", …}
validate: ColumnSettings {row: 5, col: 5, visualRow: 5, visualCol: 5, prop: "loanCurrencyCode", …}
validate: ColumnSettings {row: 5, col: 4, visualRow: 5, visualCol: 4, prop: "rate", …}
```

I'm on handsontable@7.1.1.

**Comment by wojciechczerniak** [comment]
It's because we have "Cascading Configuration" model: https://handsontable.com/docs/7.1.1/tutorial-setting-options.html and settings are inherited GridSettings > ColumnSettings > CellSettings where the last object didn't had any new properties so for performance reasons we've decided to skip empty object "CellSettings" from the prototype chain.

Maybe we can do something about it when we start to work on #6274

@davestewart  What should we do with this feature request?

**Comment by davestewart** [comment]
> What should we do with this feature request?

Probably just document existing functionality better! 😆
