### ISSUE TITLE
Autocomplete's strict mode selects the first option by default

### ISSUE THREAD

**Issue by Protagonistss** [handsontable/handsontable#6299]
### Description
Using autocomplete in the handsontable, when strict is true and allowInvalid is true, the drop-down box shows an option that defaults to the first one.

### Steps to reproduce
1. Enter the character b in the autocomplete unit
2. After carriage return, I want the character b in the cell instead of blue

### Your environment
* Handsontable version: 7.0.3
* Browser Name and version: chrome
* Operating System: osx

**Comment by AMBudnik** [comment]
Hey @Protagonistss 

the same issue has been already raised here https://github.com/handsontable/handsontable/issues/5210
Please leave a comment there if you think that it's missing some samples or explanation.

**Comment by Protagonistss** [comment]
thanks, i think i get it.

**Comment by Protagonistss** [comment]
> Hey @Protagonistss
> 
> the same issue has been already raised here #5210
> Please leave a comment there if you think that it's missing some samples or explanation.

thanks, i think i get it.
