### ISSUE TITLE
Ctrl-Arrow and Ctrl-Shift-Arrow

### ISSUE THREAD

**Issue by singhalavi** [handsontable/handsontable#630]
This request might have been put by others as well, but it will be good if we are able to jump to next filled column and select continuous filled columns as in excel

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
