### ISSUE TITLE
getCellMeta() is very expensive

### ISSUE THREAD

**Issue by davestewart** [handsontable/handsontable#6303]
### Description
We use `getCellMeta()` mainly to build classes for rendering, but it seems to get called from a lot of places, even `validateCells()`.

In `getCellMeta()` we also call `getSourceDataAtRow()` so we can colour whole rows depending on other column's values, so this adds to the validation overhead where not needed!

It's strange, seeing things like reverse while loop optimisations in `_validateCells()` when I imagine the function calls around getting cell meta are going to obliterate any gains by orders of magnitude. 

### Questions

So, two questions:

1. is there some way to move the class-building code to another function?
2. is there some way to get row data before cell data, so we don't re-get the row each time we get cell meta (most of our stuff is rendering models, so values relate horizontally)

It seems that presentation and data should be handled in separate layers.

Will this all be taken care of by #6274 ?

**Comment by AMBudnik** [comment]
You're right Dave. 

Some time ago I've made mini research on cell meta and used this demo https://handsontable.com/docs/7.1.1/tutorial-using-callbacks.html to check what callbacks are made after closing the editor (without doing any changes) and got this.

![IMG_8813](https://user-images.githubusercontent.com/10757813/65939048-075d7900-e425-11e9-9036-e023df1d879e.jpg)

It's not the whole list but we can see that there are over 11k calls (`afterChange` is the `11275`) and 

* `beforeGetCellMeta`
* `afterGetCellMeta`
* `modifyRowData`
* `modifyData`

are called a couple of times for
* changed row, then
* all cells that are after this one, then
* all cells that are before this one

then the hooks take another turn and then count 

* `beforeGetCellMeta`
* `afterGetCellMeta`
* `modifyRowData`
* `modifyData`

for all the cells from `0, 0` to the last one.

Please notice that this demo doesn't provide classes and validation so with a cell witha validator the number of calls would grow exponentially.

**Theoretically**, after a short talk with a developer who'll be doing the cell meta changes, we should get a shorter list of calls. But it's too early to say anything more. We did not start the development of this task yet.

**Comment by davestewart** [comment]
Hey @AMBudnik and @wojciechczerniak ...

Following on from this conversation, I moved about 95% of the `className` stuff to my `afterRenderer` function and the end result is identical.

![image](https://user-images.githubusercontent.com/132681/66113198-3c540200-e5c4-11e9-92a8-2dfc4cef3573.png)

However, I was curious to know what impact this might have, as I presume `cells()` is called more often. This is the code I am running:

https://gist.github.com/davestewart/671b5a8715868b5491345639ff68c756

And these are the results:

| call                      | cells | afterRender |
| ------------------------- | ----- | ----------- |
| app.init                  | 1     | 1           |
| app.initSettings          | 3     | 3           |
| app.initTable             | 1     | 1           |
| settings.cells            | 1682  | 1682        |
| settings.afterGetCellMeta | 1682  | 1682        |
| settings.beforeRender     | 7     | 7           |
| settings.afterChange      | 5     | 5           |
| hot.getSourceData         | 1163  | 1163        |
| hot.getSourceDataAtRow    | 1591  | 1807        |
| settings.afterRenderer    | 216   | 216         |
| settings.beforeValidate   | 84    | 84          |
| settings.afterValidate    | 84    | 84          |

They are identical, apart from `getSourceDataAtRow()` which needs to be called in both because of the `readOnly` property for "deleted" rows seen in red, above.

But it seems that because `afterRenderer()` is only called 216 times vs 1682 for `cells()` that it would make more sense to put the complex class-building code here.

Can you advise!?

Many thanks :)

**Comment by AMBudnik** [comment]
I have to admit that I won't be able to tell where to put the logic if not there, as the list of errors could end up really long. Maybe @wojciechczerniak is more aware.
Nevertheless, anything that we can discuss now will be outdated after the changes that we're planning to make soon (cell meta refactor).

**Comment by davestewart** [comment]
> as the list of errors could end up really long

Ah... this was to add classes to cells based on cell values, rather than the validation.

It just seems to make more sense AFTER everything has been calculated.

Anyway, we are testing the hell out of the tables today, so I'll let you know

**Comment by krzysztofspilka** [comment]
@davestewart we're on it, sorry for keeping you waiting.

**Comment by davestewart** [comment]
That's great news! I'm only occasionally back with this client now, and not sure when we will next upgrade our table code, but I hope my feedback helps to improve HoT 😊

**Comment by AMBudnik** [comment]
Hi @davestewart I'm more than happy to inform you that we made a huge improvement in handling cell meta. The more complex the use is the bigger improvement we achieve.

Changes were published under Handsontable v10. I hope it will benefit your project as well!

**Comment by davestewart** [comment]
Hey Aleksandra,

Thanks for the update!

I haven't been on this project for a while now; not sure if I will be back on it as they are now (hopefully!) launching.

If / when I do go back, it will be great to see!

Hope all is well with you + the team 👋

**Comment by davestewart** [comment]
PS. Was a `getRowMeta()` implemented? Or is it even needed now?

**Comment by AMBudnik** [comment]
Hey @davestewart 

nope, but we changed the way the rendering hooks work  https://github.com/handsontable/handsontable/pull/8632 with caching some values https://github.com/handsontable/handsontable/pull/8629 and the performance of the heaviest `cells`-based examples just skyrocketed!
