### ISSUE TITLE
alter fn ng2-handsontable

### ISSUE THREAD

**Issue by chrisrodriguezmbww** [handsontable/handsontable#6305]
### Description
include alter fn from core into angular wrapper.

### Steps to reproduce

1.afterOnCellMouseDown: (event, coords, TD) => {
        Handsontable.prototype.alter('remove_row', coords.row);

Error:
zone.js?af66:192 Uncaught TypeError: handsontable__WEBPACK_IMPORTED_MODULE_2__.default.prototype.alter is not a function

**Comment by AMBudnik** [comment]
Hey @chrisrodriguezmbww 

if you're referring to https://www.npmjs.com/package/ng2-handsontable the issue should be raised in this repository https://github.com/valor-software/ng2-handsontable/issues
We are not an owner of that library.
