### ISSUE TITLE
Selection after adding and removing rows differ

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6306]
### Description

While I was testing basic CRUD operations like calling `alter` method on a selected row, row above and below I noticed that we select cells differently. 

Not sure if that is a bug, it might be intended. However, after further testing I found some situations when this diversity may cause confusing results.

### Introduction
```
Legend
Blue -  current selection 
Orange - selection before action
```

When we insert a new row above selected one the selection moves from row index `6` to `7`.

![image](https://user-images.githubusercontent.com/10757813/66107732-3ad50a80-e5c1-11e9-8723-484d7e7c449b.png)

And when we remove a row above selected one the selection stays on row index `6`. But in the result we select cell `B8` instead of `B7`.

![image](https://user-images.githubusercontent.com/10757813/66107926-ad45ea80-e5c1-11e9-90ec-6c9a840f30f5.png)

It means that when we add a row we still have our `B7` value selected, 
and when we remove a row we get `B8` selected.

### Let's play with the example
Here's a demo that loads Handsontable `v 8.0.0-rc1` `build (26/09/2019)`  https://jsfiddle.net/handsoncode/wsc2z69x/. 
`7.1.1` works the same.

* If we select `B30` and remove 10 rows above.

We shouldn't see cells in the pink area and get `B19` and after that our selected `B30`.

![image](https://user-images.githubusercontent.com/10757813/66109938-f7c96600-e5c5-11e9-9e8d-c708f2fba93a.png)

and we get 10 rows less but now we get `B40` selected.

![image](https://user-images.githubusercontent.com/10757813/66110127-6dcdcd00-e5c6-11e9-927f-5f80ef16ac0f.png)

* If we select `B30` and add 10 rows above.

![image](https://user-images.githubusercontent.com/10757813/66110323-d6b54500-e5c6-11e9-8bfb-24888e8373cd.png)

It is OK we still have the same cell selected.

### While editing
If it is not too complicated already lets imagine a different situation.
This time alteration doesn't happen on a button click - it is triggered by the server. 

To emulate the behavior I run a `beforeKeyDown` hook and call `alter` within. 
Updated demo https://jsfiddle.net/handsoncode/7c823x05/

* If we select `B30` and remove 10 rows above.

![on_server_remove](https://user-images.githubusercontent.com/10757813/66112352-f5b5d600-e5ca-11e9-98cf-6b5f34250569.gif)

We edit a cell that used to be `B40`, not `B30` even if it still exists.

* If we select `B30` and add 10 rows above.

![on_server_add](https://user-images.githubusercontent.com/10757813/66112163-9fe12e00-e5ca-11e9-990e-cf367a11f1b4.gif)

We are still editing a cell on the same index but this is already a different cell (a part of a new rows alteration).

This part might be related to the editor itself but it is surely something I needed to mention.

### Related
https://github.com/handsontable/handsontable/issues/5270

### Your environment
* Handsontable version:  `v 8.0.0-rc1` `build (26/09/2019)`
* Browser Name and version: Chrome 77
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
@AMBudnik I believe this issue was addressed in  #6997. We've discussed with @budnix whether the selection should move or stay at the same cell. It was inconsistent between row/columns and was fixed.

The scenario with an editor is probably not fixed but already reported in #5270

WDYT? @AMBudnik @aninde Can we recheck this issue?

**Comment by AMBudnik** [comment]
@wojciechczerniak the are no changes between posted examples and rev15.


**Case 1** - select `B30` and click `Remove 10 rows above` works the same in 8.0.0-beta2-rev15 
**Case 2** - select `B30` and click `Add 10 rows above` works the same in 8.0.0-beta2-rev15
https://jsfiddle.net/AMBudnik/dsfLz4mt/

Editing with rev15 works the same as well
https://jsfiddle.net/AMBudnik/n584zgtb/
![Zrzut ekranu 2020-06-17 o 14 50 39](https://user-images.githubusercontent.com/10757813/84900145-fdaa9d00-b0a9-11ea-96dd-bd478088395c.png)

**Comment by wojciechczerniak** [comment]
🤔 So we've fixed this for columns. And it was one-way fix only. When inserting them (+undo after remove).

Thanks for recheck.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Selection grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7514

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
