### ISSUE TITLE
Visual indexes are wrong when using trimRows and columnSorting

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#6310]
### Description
`hot.toVisualRow` returns `null` when using the `trimRows` and `columnSorting` plugins together.

### Steps to reproduce
1. https://jsfiddle.net/q5Lctzjp/1/

### Demo
https://jsfiddle.net/q5Lctzjp/1/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome
* Operating System: OS X

**Comment by aarondfrancis** [comment]
Maybe same as https://github.com/handsontable/handsontable/issues/5890?

**Comment by wojciechczerniak** [comment]
Probably. Should be fixed in `v8.0.0`: https://jsfiddle.net/68yk120b/

@aninde

**Comment by AMBudnik** [comment]
I would also call it a duplicate. Nevertheless, both are fixed with `8.0.0.-rc1`.

**Comment by aninde** [comment]
@aarondfrancis it will be fixed in `8.0.0-rc1`. https://jsfiddle.net/aninde/dkfgt4sn/ .

We are currently testing a version `8.0.0-rc1` with many breaking changes. Changes will be released soon. I recommend observing news from issue #5751. More about changes in the PR #5945.

**Result in `8.0.0-rc1`**
In the console, we get 2 and 3, 
instead of  2 and null.

This issue is related to  #5890 and #5915.

**Comment by aarondfrancis** [comment]
Awesome, thanks yall! 

Is there a way to target 8.0.0-rc1 from my package.json at the moment?

**Comment by wojciechczerniak** [comment]
We're planning to publish RC1 to NPM by the end of the month. Few tests are missing #5751 

If you're feeling adventurous 🙈  then I think that you can target git commit [1] in package.json [2] 🤔 

[1] 293f30429d37fea2add8a9c3df5917b2684ce02a
[2] https://docs.npmjs.com/files/package.json#github-urls

**Comment by aarondfrancis** [comment]
Oh the end of the month isn't too far away. I can wait until then! I'll keep my eyes peeled for it. Really really looking forward to the record translator cleanup, I think that will make my life a lot easier. Great work!

**Comment by aarondfrancis** [comment]
@wojciechczerniak It turned out that I needed this much sooner than I thought. I've targeted 293f304, but when it comes down I don't have the commonjs directory like I do if I target 7.1.1.

Previously I could do

```javascript
import Handsontable from 'handsontable';
```

and know I have to update all my references to 

```javascript
import Handsontable from 'handsontable/src/index';
```

Is there some build step I need to run, or is it just because I'm targeting a non-packaged version of the library?

Thanks

**Comment by wojciechczerniak** [comment]
@aarondfrancis For internal testing, we're committing only UMD build to the repository.

After `npm install` you can go to `node_modules/handsontable` and run `npm build` to create `commonjs` directory. Or if you're ok with that 'handsontable/src/index' is not the same as 'handsontable', and your build system can handle ES6 and corejs then I think this should work. To avoid changing reference I would create an alias in webpack config.

**Comment by aarondfrancis** [comment]
Currently running 8.0.0 in production! So far so good. 🤞

**Comment by wojciechczerniak** [comment]
![obraz](https://user-images.githubusercontent.com/4718998/66746195-7acda480-ee81-11e9-88a1-3ee32997d6ab.png)

~your~ our 🤔 🤣 

@aarondfrancis Awesome 👍 Thank you for putting so much trust in our work.

**Comment by AMBudnik** [comment]
Not a big news but we just release beta officially :)

**Comment by aarondfrancis** [comment]
> Not a big news

That is big news!  👏  I'll migrate my app today. Thanks for letting me know 👍

**Comment by AMBudnik** [comment]
@aarondfrancis now is the big news - 8.0.0 (finally stable)!
Thank you for your contribution 👏

**Comment by aarondfrancis** [comment]
So excited for yall! Great work <3
