### ISSUE TITLE
Preprocessing row data - possible feature suggestion

### ISSUE THREAD

**Issue by davestewart** [handsontable/handsontable#6311]
### Description

Our main use case for HoT is editing of models / rows but there doesn't seem to be much support for this.

In our cell callbacks, we do a lot of data lookups, usually starting with `getSourceDataAtRow()`. In each `validate()`, `cell()` or `afterRenderer()` callback we usually end up repeating this:

- image and explanation: https://github.com/handsontable/handsontable/issues/6303#issuecomment-537876102
- code sample: https://gist.github.com/davestewart/671b5a8715868b5491345639ff68c756

What would be really useful would be some way to pre-fetch row data, perhaps with some kind of `dirty` flag / caching / one-way data flow, so we're not constantly running the same logic / recalculations.

### Thoughts

An idea I had was something like `prepareRow()` hook which could be as simple as:

```js
function prepareRow () {
  return this.getSourceDataAtRow()
}
``` 

Or could provide more context so it would know to update itself:

```js
function prepareRow (changes, original, source, justGuessingTheseReally, ...) {
  const data = this.getSourceDataAtRow()
  if (source === 'validation') {
    if (changes.data.propB || changes.data.propC) {
      data.propA = data.propB + data.propC
      ...
    }
  }
  return data
}
```

But in a similar way that Vue **only recomputes** if something (i.e. user input, or a value set by perhaps `setCellData()`) has changed, the subsequent cell hooks would get a fully-computed / updated chunk of data to use, without needing to re-invent the wheel each time.

Subsequent functions would receive this data as an argument to be consumed:

```js
afterRenderer (td, row, col, prop, value, column, rowData) { ... }
cells (row, col, prop, rowData) { ... }
...
```

### Wrap-up

Im sure you guys have already thought of this, or there's some technical reason why it hasn't been implemented, but it seems from our day-to-day usage, that there are optimisations to be found here, **especially** with things like row-dependent cells and cross-field rendering.

Cheers,
Dave

**Comment by AMBudnik** [comment]
I think that this case extends the Stage 2 of [eco-renderers](https://github.com/handsontable/handsontable/issues/5769).
Thank you for sharing the detailed example.

**Comment by davestewart** [comment]
I added links to a previous issue with image and explanation, and also a code sample taken from our table factory function.

**Comment by AMBudnik** [comment]
Thank you for sharing this proposition, @davestewart 

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback. 
See you there!
