### ISSUE TITLE
Wrong positioning of 'htAutocompleteArrow' element in Safari and Firefox

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6313]
### Description

If we do not set `colWidths` or add additional rows by purpose (example: use of HTML, custom renderer) we should get a single line when we define value.

However, the use of `htAutocompleteArrow` element for the autocomplete, handsontable and dropdown cell type breaks this rule on the latest Safari and Firefox.

All the tests were made using the official demo https://handsontable.com/docs/7.1.1/demo-autocomplete.html

#### (looks well, one line)

![chrome](https://user-images.githubusercontent.com/10757813/66206915-b8784380-e6b1-11e9-9cc6-ea243945f22e.png)

#### (looks bad, two lines)

![firefox](https://user-images.githubusercontent.com/10757813/66206978-db0a5c80-e6b1-11e9-8ae9-2254150b2d39.png)

#### (looks bad, two lines)

![safari](https://user-images.githubusercontent.com/10757813/66206989-e5c4f180-e6b1-11e9-9e04-903879ee43be.png)

### 4.0.0 for Safari and Firefox
and in version [4.0.0.](https://handsontable.com/docs/4.0.0/demo-autocomplete.html) we got

![safari-4](https://user-images.githubusercontent.com/10757813/66207007-ecebff80-e6b1-11e9-8cc4-b7396200ab4c.png)

**Comment by AMBudnik** [comment]
It looks like available space in the autocomplete cell in Chrome is counted to `81`px and `80`px in Firefox.

### Firefox
![Zrzut ekranu 2019-10-4 o 14 31 14](https://user-images.githubusercontent.com/10757813/66207714-c62ec880-e6b3-11e9-9581-1fda704ebe09.png)

### Chrome
![Zrzut ekranu 2019-10-4 o 14 31 33](https://user-images.githubusercontent.com/10757813/66207717-c8912280-e6b3-11e9-8dfc-82a83189af32.png)

**Comment by wojciechczerniak** [comment]
@AMBudnik #3116

**Comment by AMBudnik** [comment]
Closed as a duplicate of https://github.com/handsontable/handsontable/issues/3116
