### ISSUE TITLE
Long column header prevent use of column dropdown menu

### ISSUE THREAD

**Issue by colinbrownec** [handsontable/handsontable#6315]
### Description
If there are long column headers, the dropdown menu is made inaccessible if the column header overflows on top of the dropdown menu icon.

I would expect the dropdown menu to still be accessible, and possibly for the column header text to render beneath the dropdown menu button.

### Steps to reproduce
1. create a table with `dropdownMenu=true`
2. add long column names
3. set the column width to be smaller than the text width (this can also be achieved with `manualColumnResize=true` and shrinking the column after the initial render)

### Demo
https://jsfiddle.net/dfuaLs63/1/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome 77.0.3865.90
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @colinbrownec 

thank you for sharing the bug report. This issue can be tracked here https://github.com/handsontable/handsontable/issues/5782
