### ISSUE TITLE
[8.0.0-rc1] Can't collapsed many parent of nestedRows.

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6316]
### Description
You can not collapse two parents at the same time. @wszymanski will the latest fix handle this?

v. `8.0.0-rc1` Bug - you can collapse only one parent. When you tried to collapse the second parent, when first is collapsed, the first one unwinds

### Steps to reproduce
1. Collapse the first parent row.
2. Collapse the second parent row. 

v. `8.0.0-rc1` Bug - you can collapse only one parent. When you tried to collapse the second parent, when first is collapsed,  the first one unwinds
![nested-8 0 0-rc1 2019-10-07 09_29_12](https://user-images.githubusercontent.com/30186818/66294611-aaad0300-e8e9-11e9-8f77-f6ec9f58218d.gif)
It works in original demo
v. `6.2.2`, also in latest `7.1.1`
![Screenshot 2019-10-07 at 09 24 58](https://user-images.githubusercontent.com/30186818/66292614-045efe80-e8e5-11e9-9730-8bd5f3ae7299.png)
### Demo
Demo:
works `7.1.1` http://jsfiddle.net/aninde/v1Lcunjm/
bug v. `8.0.0-rc1` https://jsfiddle.net/yf7wkm0b/

### Your environment
* Handsontable version: `8.0.0-rc1`
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
A bug is still replicable in the latest build of `8.0.0-rc1` (7.10.19)  

Demo: 
v. latest (7.10.19) `8.0.0-rc1` https://jsfiddle.net/aninde/kr2yzhv7/

**Comment by AMBudnik** [comment]
### Case 2

Demo https://jsfiddle.net/handsoncode/xabz9wv3/

1. Try to collapse all the parents
2. Move a child row from one parent to another

![GIF](https://user-images.githubusercontent.com/10757813/66297529-26aa4980-e8f0-11e9-8217-620daf90102f.gif)

**Comment by wszymanski** [comment]
It should be fixed:

https://cdn.jsdelivr.net/gh/handsontable/handsontable@ad2e44e07bde789ca11ab1b3eaf021498d54279b/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@ad2e44e07bde789ca11ab1b3eaf021498d54279b/dist/handsontable.full.css

**Comment by aninde** [comment]
@wszymanski thank you very much. It is fixed in the [latest](https://github.com/handsontable/handsontable/issues/6316#issuecomment-539062315) build `8.0.0-rc1`.
![Screenshot 2019-10-08 at 08 05 21](https://user-images.githubusercontent.com/30186818/66371109-a0027480-e9a2-11e9-8826-89ea39fd3355.png)

**Demo**
latest v. `8.0.0-rc1` https://jsfiddle.net/aninde/zwqtsrno/

**Comment by aninde** [comment]
`8.0.0-beta1` still fixed two described here cases.

**Comment by AMBudnik** [comment]
Remains solved in 8.0.0.-beta2-rev6 https://jsfiddle.net/8kghetfy/
