### ISSUE TITLE
[8.0.0-rc1] Newly inserted child row overwrites existing rows

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6320]
### Description
Newly inserted childs rows overwrites existing rows.
This regression bug occurs since the first build of `8.0.0-rc1` and is still replicable in newer buid from 7.10.18 

![insert child row 2019-10-07 16_18_11](https://user-images.githubusercontent.com/30186818/66319890-20cb5d00-e91e-11e9-861c-3d7f6532e56e.gif)
### Steps to reproduce
1. Select the first row (Best rock performance).
2. Insert child row by context menu.
3. Dispatch newly inserted row.

**Actual result:**
Newly added row in really doesn't work.
There is 5 rows.
getData doesn;t return:  last row: Elle King,Ex's & Oh's,RCA Records

**Expected result:**
Work in `7.1.1`
Should be 6 rows.
All rows should render. 
getData return all rows: _getData Best Rock Performance,,,,,Alabama Shakes,Don't Wanna Fight,ATO Records,,,,,Best Rock Song,,,,,Alabama Shakes,Don't Wanna Fight,ATO Records,,Elle King,Ex's & Oh's,RCA Records_

### Demo
bug v. `7.1.1` https://jsfiddle.net/aninde/9yavec14/
first of`8.0.0-rc1` fixed bug, https://jsfiddle.net/aninde/rjm36nkh/
latest v. `8.0.0-rc1` same as above https://jsfiddle.net/aninde/fpgyd5Lm/

### Your environment
* Handsontable version: `8.0.0-rc1`
* Browser Name and version: any
* Operating System: any

**Comment by wszymanski** [comment]
It should be fixed:

https://cdn.jsdelivr.net/gh/handsontable/handsontable@51bdbce6b6fb43708690981b9b7a1d236966f93c/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@51bdbce6b6fb43708690981b9b7a1d236966f93c/dist/handsontable.full.css

**Comment by aninde** [comment]
@wszymanski it is fixed. Thank you.

**Result:**
Newly added row expands data. All 6 rows are rendered.

`getData` returns proper rows: _Best Rock Performance,,,,,Alabama Shakes,Don't Wanna Fight,ATO Records,,,,,Best Rock Song,,,,,Alabama Shakes,Don't Wanna Fight,ATO Records,,Elle King,Ex's & Oh's,RCA Records_

![Screenshot 2019-10-08 at 08 23 49](https://user-images.githubusercontent.com/30186818/66372021-3d5ea800-e9a5-11e9-80bb-bc61489fb45b.png)

Demo: [latest](https://github.com/handsontable/handsontable/issues/6320#issuecomment-539085362) `8.0.0-rc1` https://jsfiddle.net/aninde/f3pymbra/

**Comment by aninde** [comment]
Still works on `8.0.0-beta2-rev18` https://jsfiddle.net/aninde/789tqesc/.  Due to the fact that 8-beta1 is already released, I close this issue.
