### ISSUE TITLE
[1.16.0] Can't add row below or above by contextMenu when nestedRows is on

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6324]
### Description
Could not add a row above or below when `nestedRow` is on.
There is error when tries to `insert row below` or `insert row above`. 

This bug occurs also in `7.1.1`, `7.0.0`. Due to [the experimental character](https://handsontable.com/docs/7.1.1/demo-nested-rows.html) of `nestedRow`
it's hard to find the moment since the error occurs.

### Steps to reproduce
1. Open `ContexMenu` in the second row.
2. `Insert row below`.
3. `Insert row above`.

**Actual result:**
No row is added. Error occurs in console. 
![Screenshot 2019-10-08 at 08 54 14](https://user-images.githubusercontent.com/30186818/66373745-a5af8880-e9a9-11e9-8412-4b627cf14009.png)

**Expected result:**
Adding row should be working. We need to consider the logic of inserting `nestedRows`. Current options in`contexMenu` don't provide correct operation.

### Demo

with a bug - the latest (7.10.19) v. `8.0.0rc-1` https://jsfiddle.net/aninde/c4jynq91/ (7.10.19)
with a bug- the oldest `8.0.0-rc1` https://jsfiddle.net/aninde/rjm36nkh/ (11.09.19)
with a bug v. `7.1.1` https://jsfiddle.net/aninde/9u8zk5hs/

### Your environment
* Handsontable version: `8.0.0-rc1`, `7.1.1`, `7.0.0`, 
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
Related to https://github.com/handsontable/handsontable/issues/6324.

**Comment by aninde** [comment]
Result of this reproduction change over time.
Now in latest stable version `7.2.2` result is in console: _TypeError: t.start is undefined_
and in `8.0.0-rc1` result is: _TypeError: selection.start is undefined_

**Demo**
`8.0.0-rc1` https://jsfiddle.net/aninde/vh9q6t7w/ 
`7.2.2` http://jsfiddle.net/aninde/ab041sk7/

**Comment by AMBudnik** [comment]
Works the same in 8.0.0.-beta2-rev5 http://jsfiddle.net/7umL9jwt/

**Comment by AMBudnik** [comment]
**Solved** in 8.0.0.-beta2-rev6 http://jsfiddle.net/nrtfL50o/

![Kapture 2020-05-14 at 13 45 14](https://user-images.githubusercontent.com/10757813/81930665-30640000-95e9-11ea-87c6-c8e7ee386471.gif)

**Comment by AMBudnik** [comment]
I have tested different data (same settings) and it does **NOT** work there.

8.0.0-beta2-rev6 https://jsfiddle.net/gt6m801j/ (broken)
![break](https://user-images.githubusercontent.com/10757813/82045400-53f17e00-96af-11ea-873d-0ded11070d26.gif)

#### What happens here
* the last header is cut
*  table keeps the same amount of rows, it just shifts the data

**Comment by AMBudnik** [comment]
We've decided to create a new issue for that regression https://github.com/handsontable/handsontable/issues/6897

**Comment by aninde** [comment]
This issue was introduced by `v1.16.0` http://jsfiddle.net/aninde/1ap7nshc/ (broken).
It was fixed is `v1.15.0` http://jsfiddle.net/aninde/qa7s5ymd/
