### ISSUE TITLE
[react] Installation error - core-js dependencies cannot be found

### ISSUE THREAD

**Issue by soosap** [handsontable/handsontable#6329]
There is some problem with the installation process of handontable for react. For some reason I get this error. The docs give zero clues on why that is the case. Some people have raised the issue, but generally those issues have been closed saying "handsontable looks for a older version of core-js even if a newer one is available". It is a bit frustrating to even get a hello world example running w/ handsontable. 

ERROR in ./node_modules/handsontable/es/utils/rootInstance.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.iterator' in '/Users/soosap/.../client/node_modules/handsontable/es/utils'

**Comment by AMBudnik** [comment]
Hey @soosap 

have you seen this topic https://github.com/handsontable/handsontable/issues/5888
Seems like something that could help
