### ISSUE TITLE
An ContextMenu instance doesn't appear next to overlays edge

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#6330]
### Description
If the ContextMenu plugin is enabled and we click out of fixed overlays, eg.: column and row headers - then we get the native context menu.
I checked a few version from `1.14.0` and that thing worked unstable for a long time. Eg.: in `4.0.0` all commands were disabled.

### Steps to reproduce
1. Go to https://handsontable.com/docs/7.1.1/demo-context-menu.html
2. Click <kbd>RMB</kbd> outside the overlay, next to its edge (as on GIF)
![Oct-10-2019 10-25-33](https://user-images.githubusercontent.com/11849621/66553502-86e8f780-eb4b-11e9-8456-eca530823e73.gif)

Result: You got a native context menu instead of ours.

### Demo
https://handsontable.com/docs/7.1.1/demo-context-menu.html

### Your environment
* Handsontable version: 5.0.0 (the previous version had different issues)
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Might it be related to https://github.com/handsontable/handsontable/issues/6218?

**Comment by swistach** [comment]
@AMBudnik: No, a solution from #6283 will fix #6218.
But I think #3873 is strictly related.

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/bd3kxf4t/

**Comment by nathipg** [comment]
Issue is replicable using v9.0.0: https://jsfiddle.net/357zp0sg/
Video: https://drive.google.com/file/d/1L2p1bcYQnlY6MweBm3q1D7ahm9KJRPwu/view?usp=sharing

**Comment by AMBudnik** [comment]
Hi @nathipg It seems that this issue is no longer replicable. Could you please let me know if it is fixed for you?
