### ISSUE TITLE
Enabling autoRowSize with manualColumnMove doesn't render the table

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6331]
### Steps to reproduce

1. Open the link
2. Open the console

**Result**
Handsontable doesn't load and we get an additional error message

![image](https://user-images.githubusercontent.com/10757813/66553818-24442b80-eb4c-11e9-92b3-1576f1a62334.png)

### Demo

https://jsfiddle.net/handsoncode/rwe1njL8/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome 77
works the same in `7.1.2` and `8.0.0-rc1`
* Operating System: Windows 10

inform `https://forum.handsontable.com/t/cannot-use-manual-column-move-and-auto-row-size-handsontable-fails-to-initialize/3719`

**Comment by AMBudnik** [comment]
Works the same in v `7.2.0` https://jsfiddle.net/handsoncode/12nfxwsj/

**Comment by AMBudnik** [comment]
It works fine if we call the `manualColumnMove` after initialization https://jsfiddle.net/csgj7xmt/

**Comment by swistach** [comment]
Last working version: 0.27.0 https://jsfiddle.net/p6vL572k/

**Comment by wojciechczerniak** [comment]
@AMBudnik Works ok in v8.0.0-beta.2? https://jsfiddle.net/3rxd7w59/

**Comment by AMBudnik** [comment]
Hey @wojciechczerniak 

7.4.2 - broken - https://jsfiddle.net/38npvxwo/
8.0.0-beta1 - working - https://jsfiddle.net/esdqmt94/
8.0.0-beta2 - working - https://jsfiddle.net/esdqmt94/1/
frozen 8.0.0 - working - https://jsfiddle.net/esdqmt94/2/

so we can call it closed in beta1 and close it right away.
