### ISSUE TITLE
Inconsistent selection using the right mouse button for first row/column

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6334]
### Description
After v`2.0.0` we have a problem with first row/column selection by <kbd>RMB</kbd>. There are two scenarios of this bug:
If we selected the first row and then we want to click on any column header by <kbd>RMB</kbd>.
If we selected the first column and then we want to click on any row header by <kbd>RMB</kbd>.
It occurs only when you try to click on a header by <kbd>RMB</kbd>, <kbd>LMB</kbd> works as expected.

### Steps to reproduce
1. Click <kbd>LMB</kbd>/<kbd>RMB</kbd> on first row's header 
2. Click <kbd>RMB</kbd> on one of columns headers

Result: Cell selection remains in the same state as it was after the first step.

### Demo
https://handsontable.com/docs/7.1.1/demo-context-menu.html

### Your environment
* Handsontable version: 2.0.0+
* Browser Name and version: n/a
* Operating System: n/a

**Comment by AMBudnik** [comment]
**Solved** in pre 8.0.0-beta2 https://jsfiddle.net/eznduxo9/

Old behavior (7.4.2) https://jsfiddle.net/f8d9p7xg/
![old](https://user-images.githubusercontent.com/10757813/87309484-f77ad580-c51c-11ea-8c32-6bbbf3d54395.gif)


New (fixed) behavior pre 8.0.0-beta2 https://jsfiddle.net/eznduxo9/
![new](https://user-images.githubusercontent.com/10757813/87309515-01043d80-c51d-11ea-9b74-c674bde5c3a1.gif)

**Comment by aninde** [comment]
Still fixed with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/6e0xuvqy/.

**Comment by AMBudnik** [comment]
Updated demo https://jsfiddle.net/u267r1td/ v8.0.0. Issue closed as solved.
