### ISSUE TITLE
Multiple clicking on noneditable cells make them darker

### ISSUE THREAD

**Issue by mchilicki** [handsontable/handsontable#6337]
### Description
Hi, when you block for editing some cells, you can still mark whole row or column. Then clicking few times in marked cells make them darker each time you click on it. When editing is enabled they are being edited, here there is no such thing so they are being made darker. I didn't have to made a demo, a just took one from your site, where is tutorial about 

### Steps to reproduce
1. Take Handsontable with some noneditable cells
2. Mark whole row or column
3. Click few times on marked cells with CTR key to make them darker with each click

### Demo
First Handsontable on this site has this issue
https://handsontable.com/docs/7.1.1/demo-disabled-editing.html

### Your environment
* Handsontable version: on mine machine it's 6.2.0,  on demo is 7.1.1
* Browser Name and version: Opera 63.0.3368.107 and Chrome 77.0.3865.120
* Operating System: Windows 10, Windows Server 2012 R2

**Comment by AMBudnik** [comment]
Hi @mchilicki 

I'm on the same device and browser but wasn't able to replicate the issue.

What I did
1. Select `Car` column
2. Do the same again 3 times (no change)
3. Use <kbd>a</kbd> key on the selection
4. nothing changes

What you can do is use the <kbd>Delete</kbd> and <kbd>Backspace</kbd>. As you'd need to have `readOnly: true` to block that action.

Can you record it, please?

Also, I guess that we had a similar topic before and it it was related to the touch device. I've tried it with my Lenovo's touchpad and an external Logitech mouse and there's no difference.

Our Tester also tried it on Mac and we still get the same result.

**Comment by mchilicki** [comment]
I forgot to mention, you need to select cells with ctr key.

**Comment by wojciechczerniak** [comment]
https://handsontable.com/docs/7.2.0/demo-selecting-ranges.html

> Use CMD on Mac or CTRL on Windows to select non-contiguous ranges of cells.

**Comment by AMBudnik** [comment]
Ahhh.. so this changes everything. The effect of making cell darker is applying more layers to the selection. This behavior has been added as a feature to support multiple ranges. The `selectionMode: multiple` is a default option.

Please check this tutorial https://handsontable.com/docs/7.1.1/demo-selecting-ranges.html

**Comment by mchilicki** [comment]
Ok, if it's a feature then we can close the issue. Thanks for resolving.

**Comment by AMBudnik** [comment]
If you'd like to remove the effect you should add `selectionMode: range` to your settings.
