### ISSUE TITLE
A configurable container of CopyPaste's secondary focusable element.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6343]
### Description
We have to add the possibility to configure the focusable element's container. Currently, its parent is `document.body` and there is no easy way to move it outside the `iframe` element.
It is a non-breaking change and part of the scope from #6202.

To-do list:
- [x] new option in CopyPaste's settings object, where the plugin should add the secondary focusable element
- [x] for the backward compatibility it should be added to `document.body` as currently

**Comment by aninde** [comment]
On Safari I can still reproduce https://github.com/handsontable/handsontable/issues/6492

**Comment by aninde** [comment]
Closing as released in `7.3.0` and `8-beta.1`.
