### ISSUE TITLE
[7.1.1] Some overflow settings for table parent do not allow to display the table

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6344]
### Description

Handsontable is not visible when we use `overflow` CSS property.

### Steps to reproduce

1. Compare the two versions below

#### 7.1.0
![image](https://user-images.githubusercontent.com/10757813/66832113-7d033200-ef59-11e9-8476-9593031e5865.png)

#### 7.1.1
![image](https://user-images.githubusercontent.com/10757813/66832145-90ae9880-ef59-11e9-974a-bb051781ff15.png)

### Conclusions
* there are no console errors.
* table is built in the DOM
* if applied without a parent they [work as expected](http://jsfiddle.net/handsoncode/vfd8gr9u/)
* Affected by `scroll`, `hidden`, `auto`. Not affected by `inherit`, `initial`, `overlay`, `visible` and of course `unset`.

### Demo

http://jsfiddle.net/handsoncode/3e4r78vn/ (`7.1.0.` - working)
http://jsfiddle.net/handsoncode/ycrmaxkL/ (`7.1.1` - broken)

### Your environment
* Handsontable version: 7.1.1+
* Browser Name and version: Chrome 77
* Operating System: Windows 10

Inform [forum](https://forum.handsontable.com/t/gh-5322-6344-angular-material-problem/3732)

**Comment by AMBudnik** [comment]
Also, the weird behavior of adding the rows on render (offset) is described here https://github.com/handsontable/handsontable/issues/4141#issuecomment-360429985

**Comment by aninde** [comment]
The bug is replicable in latest release `7.2.0`

v. `7.2.0` http://jsfiddle.net/aninde/g2hL4a63/

**Comment by pnowak** [comment]
I think this is intentional behaviour - https://github.com/handsontable/handsontable/pull/6074 - if we haven't height property in the handsontable settings or in parent node and we have in parent overflow `scroll` or `hidden` we don't display hot table.

**Comment by AMBudnik** [comment]
I can agree with hidden, but we would need to check if it should do the same for `scroll`. And if the answer is yes then we'd need to create an official statement about why it should work this way.

**Comment by wojciechczerniak** [comment]
@AMBudnik If the container size is not defined Handsontable default is `height: 100%`. Since the container size is `0` the 100% from `0` is `0`. You can set the `height: 'auto'` and Handsontable will stretch the container (v7.2.0):

`overflow: hidden`: https://jsfiddle.net/zb2fj1dm/
`overflow: scroll`: https://jsfiddle.net/vprLbo4t/
`overflow: auto`: https://jsfiddle.net/vprLbo4t/1/

Maybe `height: 'auto'` should be the default behavior? We can discuss the pros and cons.

I agree with @AMBudnik that `overflow: scroll` should be handled better. Should behave the same as `overflow: hidden`. We've missed this one @pnowak ?

Second minor issue is that with default `height` Handsontable will take 100% of the container but with license visible there is an additional scroll: https://jsfiddle.net/vprLbo4t/2/ In production env the license should be always set either way, so rather low priority on this one.

**Comment by pnowak** [comment]
The clue of this problem is that our fix - https://github.com/handsontable/handsontable/pull/6074 - didn't work on Firefox.

**Comment by aninde** [comment]
I'm not sure what the final assumption should be on tested `7.3.0 v. `. @AMBudnik can you double check it?
Without height `auto` table is still do not rendering on Chrome 78/Firefox 70/Safari 13
http://jsfiddle.net/xb7scr9L/1/
![Screenshot 2019-11-14 at 17 32 03](https://user-images.githubusercontent.com/30186818/68881012-a1932b00-070c-11ea-834f-e6ce662961db.png)

`Height: auto`
`v. 7.3.0` https://jsfiddle.net/580rjs1g/ `height:auto
`v. 7.3.0` https://jsfiddle.net/aninde/1afu8vo9/  `overflow: hidden`
`v. 7.3.0` https://jsfiddle.net/nt0skqx7/ overlow: scroll

Overflow: scroll / Chrome 78
![Screenshot 2019-11-14 at 17 21 25](https://user-images.githubusercontent.com/30186818/68881086-c7b8cb00-070c-11ea-81c4-530f7faa1b1b.png)

Overflow: hidden / Chrome 78
![Screenshot 2019-11-14 at 17 21 11](https://user-images.githubusercontent.com/30186818/68881157-e4ed9980-070c-11ea-9024-d862f04ee3bb.png)


There is still additional scroll https://jsfiddle.net/aninde/u0kogcaj/

**Comment by AMBudnik** [comment]
Hey @aninde In the end, we should NOT have a visible container with `overflow: scroll` and without `height` defined. That was an issue for FF.

**Comment by aninde** [comment]
OK, so in `7.3.0` v. the result with `overflow: scroll` without `height` http://jsfiddle.net/aninde/udamv0fz/
![Screenshot 2019-11-15 at 08 28 00](https://user-images.githubusercontent.com/30186818/68924861-fae97180-0781-11ea-9608-34bddbfdb1be.png)
@pnowak do we understand the assumptions well? Was this the planned effect?

**Comment by pnowak** [comment]
Yes, this is the planned effect.

**Comment by aninde** [comment]
So this issue is fixed by `7.3.0`

**Comment by aninde** [comment]
On currently tested latest build of `7.3.0 v` (6.12) everything works according to assumptions. The result is correct and the same like in above http://jsfiddle.net/aninde/fecL4q7z/

**Comment by AMBudnik** [comment]
That was an interesting case. Thanks for solving guys!
