### ISSUE TITLE
Missing typings for `instance.undoRedo`

### ISSUE THREAD

**Issue by briwa** [handsontable/handsontable#6346]
### Description
We are using a custom undo/redo buttons for the table where it would need to be disabled when there's no undo/redo. We are using [`isUndoAvailable`](https://handsontable.com/docs/6.2.2/UndoRedo.html#isUndoAvailable) and [`isRedoAvailable`](https://handsontable.com/docs/6.2.2/UndoRedo.html#isRedoAvailable) as per docs.

It works fine in JS, the values are correctly presented from the function, however, in TS the typing says `instance.undoRedo.isUndoAvailable` is undefined (same for `isRedoAvailable`). In fact, the whole `instance.undoRedo` itself is not there.

Now, I am not sure if this is supposed to be retrieved from `instance.getPlugin('undoRedo')` since it's a plugin, but it's not there either (`undoRedo` isn't one of the listed plugins in the typings and it returns `undefined` in the browser). I was hoping to get an enlightenment on this, and maybe if you could add a proper types to `instance.undoRedo`. Thank you.

### Steps to reproduce

1. Create the instance of Handsontable in Typescript
2. Do `instance.undoRedo.isUndoAvailable` or any members of `instance.undoRedo` for that matter
3. It's there in the browser, but the typing says it's not there.

### Demo
https://codesandbox.io/s/handsontable-typing-bug-2r45j
Head over to `index.ts`. You'll see that the values of `hot.undoRedo.isUndoAvailable` and `isRedoAvailable` can be printed on the browser, but the typing says it's not there.

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Any browser
* Operating System: Any operating system

**Comment by AMBudnik** [comment]
Thank you for sharing @briwa 

I agree. If those methods are listed in the official docs they should be defined the .ts file.

**Comment by AMBudnik** [comment]
Hi @briwa 
I'm glad to announce that this issue also makes it to the 8.0.0-beta2

**Comment by briwa** [comment]
@AMBudnik Thank you for looking into this. Will check it out. I'll close this issue.

**Comment by AMBudnik** [comment]
We need to keep this issue opened until we'll be able to push a stable version (8.0.0), not beta.

**Comment by aninde** [comment]
This issue should be fixed with `8.0.0`, but we can test with React-Handsontable after update to support v8.0.0  https://github.com/handsontable/react-handsontable/issues/189 will be done.

**Comment by AMBudnik** [comment]
This issue is solved for v8.0.0
