### ISSUE TITLE
hot.updateSettings behavior inconsistent after manualRowMove

### ISSUE THREAD

**Issue by abhinavsarja** [handsontable/handsontable#6349]
We have a handsontable  with rows which can be ranked by dragging/ dropping using manualRowMove. After moving the rows , we call hot.updateSettings which returns the data may or may not be exactly similar to the move.

### Steps to reproduce

1. Open http://jsfiddle.net/asarja123/tzdwf6ok/25/
2. Manually move one row . We are expecting a different data to be updated after we move row.
3. But data updated is not as expected.
 
http://jsfiddle.net/asarja123/tzdwf6ok/25/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome (Latest)
* Operating System: Windows

We resolved the issue by clearing the data and doing hot.updateSettings twice. We can share the fiddle also if you need it.

**Comment by AMBudnik** [comment]
Hey @abhinavsarja 

please test this version http://jsfiddle.net/xL1r26j4/

We are working on an index mapper that fixes around 40 issues related to using indexes. This should get to an official version next month.

**Comment by abhinavsarja** [comment]
Thanks @AMBudnik. 
The JSfiddle that you have provided is how we expect it to behave,

**Comment by AMBudnik** [comment]
Great. So please expect the 8.0.0-(rc1) version next month.

If you would like to know a bit more about the changes and the scope of work here's a topic to check https://github.com/handsontable/handsontable/issues/5751

**Comment by abhinavsarja** [comment]
Hi @AMBudnik , Any expected date of delivery for the above fix?

**Comment by AMBudnik** [comment]
@abhinavsarja we'll be having a code freeze next week so the 8.0.0-rc1 should be published at the beginning of November.
