### ISSUE TITLE
Rename filter condition in DropDownMenu

### ISSUE THREAD

**Issue by HardRock4Life** [handsontable/handsontable#6353]
### Description
In condition filter, I need to change the name of 'Greater than' option.

### Steps to reproduce
1. Changing values in corresponding properties in the "languages" folder didn't change anything

**Comment by AMBudnik** [comment]
Hey @HardRock4Life 

have you done all the steps from this tutorial https://handsontable.com/docs/7.2.1/tutorial-internationalization.html?

Did you change other options and they worked?

**Comment by HardRock4Life** [comment]
Right, everything worked just fine. 
Dziękuję! :)
