### ISSUE TITLE
We're not able to move column  when all columns are selected by ctrl + a

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6355]
### Description
After clicking <kbd>CTRL</kbd>+<kbd>A</kbd> or <kbd>CMD</kbd>+<kbd>A</kbd> you can’t click on header of column to move column. 
This bug regards only to columns.

### Steps to reproduce

1. Use demo http://jsfiddle.net/aninde/qtnc2edm/
2. Select one cell, then click <kbd>CTRL</kbd>+<kbd>A</kbd> to select all.
3. Click on the header of the first column.

**Actual result**
You can move the column. Selection doesn't change when you click on the header.
However, the is no bug while you're clicking at row header. 
![Screen Recording 2019-10-17 at 13 47 47 2019-10-17 13_58_38](https://user-images.githubusercontent.com/30186818/67007061-dc427d00-f0e6-11e9-9b8b-adc729ac073d.gif)

**Expected result:** 
We should be able to click and select one header to move the column.
In Google Spreadsheet and Excel with the same reproduction, you can select the column by clicking on its header and move it. 
![Screen Recording 2019-10-17 at 11 45 40 2019-10-17 14_02_22](https://user-images.githubusercontent.com/30186818/67007045-d351ab80-f0e6-11e9-9955-114119f2a4fa.gif)

### Demo
v. `7.2.1` with bug http://jsfiddle.net/aninde/qtnc2edm/
v. `2.0.0`with bug  http://jsfiddle.net/aninde/4rbujyna/ 

### Your environment
* Handsontable version: probably in all, at least since 2.0.0+
* Browser Name and version: any
* Operating System: any

**Comment by wojciechczerniak** [comment]
@aninde Looks like it's fixed in v8: https://jsfiddle.net/1q3x7wek/ 

Please re-check this issue with the latest v8-rev. @AMBudnik WDYT about this functionality, should work like that?

**Comment by AMBudnik** [comment]
True. Works well in `8.0.0-beta2-rev18` http://jsfiddle.net/qwpatfuL/
Did not work in 7.4.2 http://jsfiddle.net/2v8ya4gd/ and 8.0.0-beta1 http://jsfiddle.net/c1oLjqhx/
Even clicking on the header did not work as expected. I should have mark a single column, but as you can see on the video

![previous](https://user-images.githubusercontent.com/10757813/86445278-646ac000-bd12-11ea-88bd-a4a69a582706.gif)

when I click header A selection does not change.

In 8.0.0-beta2-rev18 we are able to select column A.

![ok](https://user-images.githubusercontent.com/10757813/86445405-9b40d600-bd12-11ea-876a-c61cb9fe62c7.gif)

**Comment by AMBudnik** [comment]
Issue released in Handsontable v8.0.0
