### ISSUE TITLE
Allow developers to add an ignored source to the UndoRedo plugin

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#6358]
Hey y'all,

I have a proposal. I think it would be quite nice to expose a functionality whereby we can add our own source to the UndoRedo plugin, such that that source totally ignored.

Y'all are already ignoring sources from an array here:
 https://github.com/handsontable/handsontable/blob/44998e6455bbc35cc00d98c4085506aa6ae812ef/src/plugins/undoRedo/undoRedo.js#L34

but there is no way for us to crack into that array from the outside.

My proposed API would be something like:

```js
hot.undoRedo.ignoredSources.push('server');
```

As you can tell from my example, my use case is that I have changes coming down from the server (from other users) that are being applied to my spreadsheet. Those changes should not be undo-able, because they weren't done by the user editing this sheet in the first place.

Hope all that makes sense, happy to clear anything up if needed.

(I can currently work around it, so no rush.)

**Comment by AMBudnik** [comment]
I adore the idea.

If we'd add your idea along with https://github.com/handsontable/handsontable/issues/5866 that would cover all the scenarios where we decide what to undo/redo.

That would improve all the server-side operations like loading data or applying filters.

**Comment by wojciechczerniak** [comment]
Awesome idea. I think that mentioned #5866 should be enough to handle this. Like in any other `before*` hook it should be possible to reject the change. Then we can refactor merge cells and undo-redo to filter actions without "magic list".

And we could avoid adding this check to each undo action. This way it would be more generic and handled within one place in the code: when something is added to undo stack.

**Comment by aarondfrancis** [comment]
> It shouldn't be aware of merge cells or any other source.

This is a good call. I agree that using the `before*` is more consistent with the rest of the library.

👏

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by wojciechczerniak** [comment]
Note: I've described a proposal for the solution here https://github.com/handsontable/handsontable/pull/7500#issuecomment-797403918

**Comment by john-swallow-cenduit** [comment]
HandsonTable 8.4.0 includes hooks that allow the process of adding to the undo stack to be controlled.
https://handsontable.com/blog/articles/2021/5/whats-new-in-handsontable-8-4-0

See also #6948
