### ISSUE TITLE
Formula is converted to a value if merged areas are included

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6359]
### Description

Extending the title description:
If the result of the formula has a merged area of the left side and at the same time on the top, it is converted to a value. 
![image](https://user-images.githubusercontent.com/10757813/67076432-6c3b0200-f18d-11e9-8848-3c100d77c241.png)

It does not happen if there is only one merged are on left OR on top.
![Zrzut ekranu 2019-10-18 o 09 59 56](https://user-images.githubusercontent.com/10757813/67076756-19157f00-f18e-11e9-8558-e414ff2975e2.png)
![Zrzut ekranu 2019-10-18 o 09 59 35](https://user-images.githubusercontent.com/10757813/67076757-19ae1580-f18e-11e9-8384-4edc4fd9ad9e.png)

In cases where the merged areas are on bottom OR on the left only one area breaks the formula.

![Zrzut ekranu 2019-10-18 o 10 06 12](https://user-images.githubusercontent.com/10757813/67077450-97265580-f18f-11e9-89f5-34f7143b8689.png)
![Zrzut ekranu 2019-10-18 o 10 07 31](https://user-images.githubusercontent.com/10757813/67077500-ac9b7f80-f18f-11e9-873c-484e5aafda8d.png)

### Steps to reproduce

1. Open editor for cell with value `6`.

**Expected**
You should see the `=SUM(B2*2)` in the editor

**Result**
You see the value instead.

### Demo

https://jsfiddle.net/kx90uqvL/2/

### Your environment
* Handsontable version: 7.2.1
_Doesn't seem to be related to any version_
* Browser Name and version: Chrome 77
* Operating System: Windows 10

Inform [forum](https://forum.handsontable.com/t/gh-6359-why-formulas-dont-work/3795), [forum](https://forum.handsontable.com/t/trouble-with-formulas-and-merged-cells/4267) and [forum](https://forum.handsontable.com/t/gh-6359-when-a-array-is-set-to-mergecells-property-functions-are-replaced-by-its-values/5434/2), Zen 26970, [Zen](https://handsontable.zendesk.com/agent/tickets/29590)

**Comment by gnsilence** [comment]
When can you repair this problem, I think someone has put forward the solution

**Comment by AMBudnik** [comment]
Hi @gnsilence 

As presented here

![Zrzut ekranu 2020-04-9 o 09 49 26](https://user-images.githubusercontent.com/10757813/78871071-6e4c9200-7a47-11ea-9e4e-95223a426e38.png)

we are adding a new formula plugin with an engine called HyperFormula. Once we succeed we will be able to check if those issues apply to the new plugin. Now, this is yet unknown.

**Comment by gnsilence** [comment]
> Hi @gnsilence
> 
> As presented here
> 
> ![Zrzut ekranu 2020-04-9 o 09 49 26](https://user-images.githubusercontent.com/10757813/78871071-6e4c9200-7a47-11ea-9e4e-95223a426e38.png)
> 
> we are adding a new formula plugin with an engine called HyperFormula. Once we succeed we will be able to check if those issues apply to the new plugin. Now, this is yet unknown.

I see someone says to change this mergeCells  plug-in can be solved,"issues/5459", but I don't know how to modify it, this problem cause great confusion for us.
Once has the merger, formula can't load properly

**Comment by AMBudnik** [comment]
The Author of #5459 suggested this part is the issue but does not say what's wrong here. He also do not want to share a pull request.

> plugins\mergeCells\mergeCells.js
223 line
//const dataAtRange = this.hot.getData(...populationDataRange);
modify to get sourceData:
const dataAtRange = this.hot.getSourceData(...populationDataRange);

> 380 line
//clearedValue = this.hot.getDataAtCell(mergeParent.row, mergeParent.col);
modify to get sourceData:
clearedValue = this.hot.getSourceDataAtCell(mergeParent.row, mergeParent.col);

So no one has checked that tip. 
We are still preparing version 8.0.0 which is our priority.

**Comment by AMBudnik** [comment]
This issue remains the same in v 8.0.0 https://jsfiddle.net/AMBudnik/5qaspvk0/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by ppbntl19** [comment]
@AMBudnik 
Getting the same issue
Here is a simple  example to replicate-  https://jsfiddle.net/ppbntl19/syopu74v/3/

**Comment by AMBudnik** [comment]
Works the same in pre-v9 https://jsfiddle.net/handsoncode/d4peqo2h/

**Comment by AMBudnik** [comment]
I'm reopening this issue as the linked epic is closed as done https://github.com/handsontable/handsontable/issues/6466

**Comment by qcurtemanjc** [comment]
I am experiencing this issue as well

**Comment by AMBudnik** [comment]
Works the same in 12.1.0 - formula is converted to a number https://jsfiddle.net/6w4fuLka/

![Screenshot 2022-08-26 at 12 22 44](https://user-images.githubusercontent.com/10757813/186883322-12ec5726-e54e-4416-8e51-7f57dc34eeba.png)

![Screenshot 2022-08-26 at 12 23 15](https://user-images.githubusercontent.com/10757813/186883364-e36056ee-6870-4451-9281-3299159b9b59.png)

**Comment by wszymanski** [comment]
If this bug is not a minor version it should not be carried over to milestone 12.1.4.

**Comment by aninde** [comment]
This issue will be fixed by v12.2 https://jsfiddle.net/aninde/3z42smcf/. The demo has been updated[ to use the new formula engine](https://handsontable.com/docs/9.0/migration-from-8.4-to-9.0/#plugin-initialization).

<img width="221" alt="Screenshot 2022-10-20 at 16 50 21" src="https://user-images.githubusercontent.com/30186818/196982785-a320f8b6-f0f5-42eb-8da9-1ff3bb232da2.png">

**Comment by AMBudnik** [comment]
Hi @gnsilence @ppbntl19 @qcurtemanjc

The following issue is no longer replicable using Handsontable v12.2.0 (released yesterday).

Here https://handsontable.com/docs/react-data-grid/release-notes/#_12-2, you can read more about the changes in this version.
