### ISSUE TITLE
Triggering CMD + SHIFT + 4 on Mac after selecting a cell triggers multi-selection

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6360]
### Description

Once we select a cell and wants to take a screenshot on Mac with <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>4</kbd> we enter the multi selection mode that is normally triggered by <kbd>CMD</kbd> but here we get a behavior of keeping <kbd>CMD</kbd> pressed.

### Steps to reproduce

1. Select any cell
2. trigger <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>4</kbd> to make a screenshot
3. Select any other cell and continue

### Demo

https://jsfiddle.net/gkqh3odj/1/

### Your environment
* Handsontable version: 7.2.1
_Does not relate to any version_
* Browser Name and version: Chrome 77
* Operating System: macOS 10.15 Catalina

**Comment by aninde** [comment]
Duplicates of #6012.

**Comment by AMBudnik** [comment]
true @aninde
