### ISSUE TITLE
Sorting plugin can not getting right sorted items

### ISSUE THREAD

**Issue by magic-evan** [handsontable/handsontable#6361]
### Description
I have enabled sorting function, and loaded data in table, and when I have copied 3 items to the end row in table, then 2 items will be in auto created rows , But the sorting plugin "rowsMapper" only had latest 2 items mapping.

### Steps to reproduce
1. columnSorting: true
2. Copied the 3 items and paste to end row, 2 items in auto created new rows.
3. console output [{0:3},{1:4}] array. 

### Demo
https://jsfiddle.net/1mbcstk7/

### Your environment
* Handsontable version: 
* Browser Name and version: chrome
* Operating System:

**Comment by AMBudnik** [comment]
Hey @magic-evan 

I get a bit different result (If I'm taking the right steps)

![image](https://user-images.githubusercontent.com/10757813/67184554-53785980-f3e4-11e9-8610-8d04663f1a1e.png)

However, can you load there resources instead

https://cdn.jsdelivr.net/gh/handsontable/handsontable@b364760caee51c4b3ac30af4653a53d69dbd889a/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@b364760caee51c4b3ac30af4653a53d69dbd889a/dist/handsontable.full.css

and let me know if now the result meets your requirements?

**Comment by AMBudnik** [comment]
I think that you should be looking at the official API. The `rowsMapper` is exposed but is not a recommended way to gather information.

If you'd like to get the data you should call `getData` https://jsfiddle.net/w42np3co/ or `getSourceData` if you move/sort rows and wants to get the initial order https://jsfiddle.net/u9em3obd/

If you use sorting you can also check what is the order of the columns using `afterColumnSort` hook.

In the task that we are doing here https://github.com/handsontable/handsontable/issues/5751 we introduce a global index mapper. You can check how the plugins will be constructed within this demo https://jsfiddle.net/Lthvqscm/ (please do not use this on the production, it is not an official version yet).

**Comment by magic-evan** [comment]
> I think that you should be looking at the official API. The `rowsMapper` is exposed but is not a recommended way to gather information.
> 
> If you'd like to get the data you should call `getData` https://jsfiddle.net/w42np3co/ or `getSourceData` if you move/sort rows and wants to get the initial order https://jsfiddle.net/u9em3obd/
> 
> If you use sorting you can also check what is the order of the columns using `afterColumnSort` hook.
> 
> In the task that we are doing here #5751 we introduce a global index mapper. You can check how the plugins will be constructed within this demo https://jsfiddle.net/Lthvqscm/ (please do not use this on the production, it is not an official version yet).

Thanks for your advice, I use this property(sortMap.columnStatesManager.sortedColumnsStates) to resolved my problem.
