### ISSUE TITLE
How do I disable drag replication？

### ISSUE THREAD

**Issue by chen-ABC** [handsontable/handsontable#6362]
### Description
![image](https://user-images.githubusercontent.com/30097790/67183422-03b18680-f414-11e9-92e5-76a6d28bd507.png)

I want to disable this feature or someone can tell me how to customize its behavior.

### Your environment
* Handsontable version 7.1.1:
* Browser Name and version chrome 64:
* Operating System windows7:

**Comment by AMBudnik** [comment]
Hi @chen-ABC 

you should turn off the `fillHandle`. Here's the example https://jsfiddle.net/20trap9e/1/

```js
fillHandle: false // possible values: true, false, "horizontal", "vertical"
```

src: https://handsontable.com/docs/7.2.1/demo-auto-fill.html

**Comment by chen-ABC** [comment]
@AMBudnik  thanks
