### ISSUE TITLE
minSpareCols with undo adds too many columns

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6363]
If we add `minSpareCols` to the equation it is easier to get the columns back but we get too many columns.

Updated demo https://jsfiddle.net/handsoncode/5cwb9agr/

### Steps to reproduce
1. Select A and B column by dragging
2. Use the context menu to delete columns
3. Undo

**Result**
We get 4 columns instead of 3. With 2 spare columns, there are 6 columns after undo and so on.

![66485094-7a5f9300-eaa8-11e9-92e4-8d52f57d0c87](https://user-images.githubusercontent.com/10757813/67185275-bb7b6f80-f3e5-11e9-81ec-869b2f1482ea.gif)

### Your environment
* Handsontable version: 7.2.1
* Browser Name and version: Chrome 77
* Operating System: Windows 10

Moved from https://github.com/handsontable/handsontable/issues/6327

**Comment by AMBudnik** [comment]
### Case 2
1.  Go to demo https://jsfiddle.net/AMBudnik/fvyus9bL/ (`7.4.2`)
2. Select columns `A` and `B`
3. Use <kbd>CTRL/CMD</kbd> + <kbd>C</kbd> to copy those columns
4. Click `C` column
5. Use <kbd>CTRL/CMD</kbd> + <kbd>V</kbd> to paste those columns 

You get `5` columns `(1` blank).

![Zrzut ekranu 2020-04-8 o 11 50 36](https://user-images.githubusercontent.com/10757813/78770684-31bd5f80-798f-11ea-81a5-4ec4ce432971.png)

6. Use <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd> to undo

Result is expected

![Zrzut ekranu 2020-04-8 o 11 52 12](https://user-images.githubusercontent.com/10757813/78770810-692c0c00-798f-11ea-8069-de61586c73f7.png)

7. Undo again

![Zrzut ekranu 2020-04-8 o 11 52 19](https://user-images.githubusercontent.com/10757813/78770822-6cbf9300-798f-11ea-8da7-7359923a5cde.png)

What happened? Column `A` is gone.

**Comment by AMBudnik** [comment]
### Case 3
1. Go to https://jsfiddle.net/AMBudnik/1dwr46mL/
2. Select columns `A` and `B`
3. Use <kbd>CTRL/CMD</kbd> + <kbd>C</kbd> to copy those columns
4. Click `C` column
5. Use <kbd>CTRL/CMD</kbd> + <kbd>V</kbd> to paste those columns 
6. Move `E` after `B` column
7. Use <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd> to undo

The result after first undo
![Zrzut ekranu 2020-04-8 o 12 01 10](https://user-images.githubusercontent.com/10757813/78771587-b2c92680-7990-11ea-948c-c6e72a7a544b.png)

The result after second undo
![Zrzut ekranu 2020-04-8 o 12 01 16](https://user-images.githubusercontent.com/10757813/78771607-bceb2500-7990-11ea-9fdf-62ef7aa94377.png)

After that we are not able to undo again, to get back to the starting point.

8.0.0-beta1 works the same https://jsfiddle.net/AMBudnik/mL6vcp2r/

**Comment by AMBudnik** [comment]
Using pre 8.0.0-beta2 on Windows 10 / Chrome 83

### Main case - solved
Demo https://jsfiddle.net/Lswxrvdq/
Result
![ok](https://user-images.githubusercontent.com/10757813/87305317-90f2b900-c516-11ea-8967-b43b0469999c.gif)

### Case 2 - still replicable 
Demo https://jsfiddle.net/fydxcvhL/

### Case 3 - still replicable 
Demo https://jsfiddle.net/cLt9wk80/

**Comment by AMBudnik** [comment]
I moved cases 2 and 3 to a separate issue https://github.com/handsontable/handsontable/issues/7112

**Comment by aninde** [comment]
Main case is still fixed with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/f9op4c7z/.

**Comment by AMBudnik** [comment]
Updated demo v 8.0.0 https://jsfiddle.net/5qsyr6ae/ Issue solved (along with the missing border visible on the demo above)
