### ISSUE TITLE
undo remove row no found in autocomplete

### ISSUE THREAD

**Issue by gbelmm** [handsontable/handsontable#637]
example 

http://jsfiddle.net/7JHQ5/1/

undo ctrl+z remove row no found in autocomplete

**Comment by AMBudnik** [comment]
Still occurs. Reproduced on Chrome 41.0.2272.118

**Comment by budnix** [comment]
Updated demo http://jsfiddle.net/7JHQ5/3/

**Comment by krzysztofspilka** [comment]
Fixed in 0.17.0
