### ISSUE TITLE
UI breaks when scrolling.

### ISSUE THREAD

**Issue by congkhanh197** [handsontable/handsontable#6373]
### Description
UI breaks when scrolling. See image below.

### Steps to reproduce
1. Scroll to end of page (end row).
2. Scroll to the right.

![Screen Shot 2019-10-22 at 6 53 49 PM](https://user-images.githubusercontent.com/15651028/67285637-20c48300-f502-11e9-840d-f0ae8164feda.png)

### Demo
https://jsfiddle.net/fzb185jg/1/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Google Chrome (77.0.3865.120) 
* Operating System: macOS 10.14.6

**Comment by AMBudnik** [comment]
Thank you for sharing @congkhanh197 

This issue is already reported here https://github.com/handsontable/handsontable/issues/4670. Please follow it for updates.
