### ISSUE TITLE
Undo doesn't work for merged area (UI)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6374]
### Description

Undo doesn't work for merging (UI doesn't change) but data gets back perfectly.

### Steps to reproduce

1. Use autofill on `A1` to copy value to `D1:F3`
![image](https://user-images.githubusercontent.com/10757813/67285343-a7b03600-f4d7-11e9-8b0d-b9f070854780.png)

2. Click any cell
3. Click undo
4. Click the button <kbd>Get data</kbd>

**Result**

![image](https://user-images.githubusercontent.com/10757813/67285510-fd84de00-f4d7-11e9-880f-2b81b4a9f139.png)

The merged area is still visible, we can see `D1` cell but the data is back

![image](https://user-images.githubusercontent.com/10757813/67285751-6ff5be00-f4d8-11e9-9f4b-049dd39bf646.png)

### Demo

https://jsfiddle.net/u6pf21tn/1/ (`7.2.1`)

### Your environment
* Handsontable version: 7.2.1
Doesn't seem to be version related
* Browser Name and version: Chrome 77
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
### Case 2
Demo http://jsfiddle.net/AMBudnik/cw9j86b4/ (v7.4.2)

#### Steps
1. Autofill cell `A1` all the way down
2. Use <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd> to undo the changes

![issue](https://user-images.githubusercontent.com/10757813/79985355-c73a1280-84aa-11ea-90db-262350c9a05b.gif)

**Comment by AMBudnik** [comment]
### Case 3

1.  Go to https://jsfiddle.net/5ropsLzx/
2.  Use context menu to remove row with value `A5`
3.  Undo to get back to the initial settings.

**Result**

`A6` is merged, not `A5`.

![](https://user-images.githubusercontent.com/10757813/81264902-7bf33880-9042-11ea-983d-9091ba48cd1f.gif)

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. 

Here's an updated demo for **case 1** - https://jsfiddle.net/zvnreb79/
Here's an updated demo for **case 2** - https://jsfiddle.net/41o7L56q/
Here's an updated demo for **case 3** - https://jsfiddle.net/62kmz3qe/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
