### ISSUE TITLE
Fixed columns looks like frozen for contextMenu when manualColumnFreeze works

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6375]
### Description
From version [`8.0.0-rc1`](https://github.com/handsontable/handsontable/pull/5945#issuecomment-544933578) coworking with other plugins of `fixed` and `frozen` plugins will be different. 
When `contextMenu`  is enabled and `manualColumnFreeze` is enabled fixed column looks like frozen and it can be odd and incomprehensible for users. 

We should distinguish them in the `context menu`.

Some differences in performance of `fixed` and `frozen`:
When `manualColumnFreeze` is enabled are enabled with `manualColumnMove` you cannot move columns.
When only `fixedColumnsLeft`, `fixedRowsTop` or `fixedRowsBottom` are enabled with `manualColumnMove` you are able to move column.
When `manualColumnFreeze` works with enabled `fixed` column and with `manualColumnMove`, move of column is impossible.

![Screenshot 2019-10-22 at 14 38 37](https://user-images.githubusercontent.com/30186818/67286651-0f678080-f4da-11e9-8184-de46bb45fa70.png)

### Demo

https://jsfiddle.net/aninde/b87gkzcr/

### Your environment
* Handsontable version: at least 2+
* Browser Name and version: any
* Operating System: any

**Comment by wojciechczerniak** [comment]
@aninde @AMBudnik what's going on in this issue? `manualColumnFreeze` and `fixedColumnsLeft` are the same features, no wonder that "fixed column looks like frozen". Both names are used for the same thing.

**Comment by aninde** [comment]
> @aninde @AMBudnik what's going on in this issue? `manualColumnFreeze` and `fixedColumnsLeft` are the same features, no wonder that "fixed column looks like frozen". Both names are used for the same thing.

Yes, but we should have it documented (https://github.com/handsontable/docs/issues/83) so I close this issue.
