### ISSUE TITLE
Hiding rows while there is a merged area involved causes data shifting and unexpected merged area coordinates

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6376]
### Description

Hiding rows while there is a merged area involved causes data shifting and unexpected merged area coordinates.

### Steps to reproduce

1. Go to demo
2. Check the result
3. Comment our the `hiddenRows` settings
4. Compare both results

![image](https://user-images.githubusercontent.com/10757813/67363890-a2ea9100-f56e-11e9-9788-93f0c9122ada.png)

**Expected**
![image](https://user-images.githubusercontent.com/10757813/67364737-6fa90180-f570-11e9-923a-0cfde0c6da94.png)

It looks like the merged area cuts `E3` totally and pushes data right and we get a doubled right border for `A4`

![image](https://user-images.githubusercontent.com/10757813/67364618-3375a100-f570-11e9-81f3-05dfad7d1fd2.png)

### Demo

https://jsfiddle.net/hpqjyuz2/

### Your environment
* Handsontable version: 7.2.1
_It doesn't seem to be version related_
* Browser Name and version: Chrome 77
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
If we merge more cells they shift even further

![image](https://user-images.githubusercontent.com/10757813/67384012-9d05a780-f590-11e9-81ca-5192cdc3a92d.png)
demo https://jsfiddle.net/ryqozcaf/

Now there are `A` and `B` cells where we expect `D` and `E` to be.

According to `getData` we get the correct result

![image](https://user-images.githubusercontent.com/10757813/67384356-51073280-f591-11e9-8605-0e0343aad7d6.png)

but the editor still holds `A3` instead of `D2`.

![image](https://user-images.githubusercontent.com/10757813/67387123-819d9b00-f596-11e9-8274-64b3dff3de42.png)

**Comment by AMBudnik** [comment]
The issue is also replicable with filters (as they hide rows)

Steps
1. Go to https://jsfiddle.net/u6pf21tn/4/
2. Autofill `A1` to left
3. Click the button
4. Filter column `D` to exclude `empty cells`
5. Click the button

**Result**
![Zrzut ekranu 2019-10-25 o 15 02 03](https://user-images.githubusercontent.com/10757813/67573354-6cf90880-f738-11e9-8847-af18820390ad.png)

![Zrzut ekranu 2019-10-25 o 15 02 36](https://user-images.githubusercontent.com/10757813/67573394-80a46f00-f738-11e9-9834-f250181ea371.png)

Data is printed according to our needs but the merged area covers too many cells.

**Comment by AMBudnik** [comment]
When we load the first demo https://jsfiddle.net/hpqjyuz2/ and try some 

* select cell `B1` alone then it is fine, 
* but if we select `C1` and then `B1` (without CTRLM/CMD or SHIFT) we get `B1`, `C1` and `B3` selected.

![GIF](https://user-images.githubusercontent.com/10757813/68392211-93bc3380-0169-11ea-8e8f-29664ceeade2.gif)

**Comment by AMBudnik** [comment]
I took another step to look for the pattern of displacement.

After adding a third merged area it becomes obvious that the last cell covered by the merged area is shifted right

![image](https://user-images.githubusercontent.com/10757813/68396173-683d4700-0171-11ea-8a46-cdc4b33d17c3.png)

![merged movement](https://user-images.githubusercontent.com/10757813/68396252-8dca5080-0171-11ea-89ec-b9a773079a0a.gif)

So if we 
* select column `A`, We get all the `A~` cells + the last cell from merged area, which is `A7`
* select column `B` we already are shifted with `A7` so `B7` is selected + the last cell from merged area in column `B`, which is `B4`
* select column `C` we get what is shifted from columns `A` and `B` and then get the last cell from merged area in column `C`, which is `C3`
* select column `D` or `E` we are just left with cells from the columns that haven't been shifted before.

When I merge cell a bit different, then the result changes a bit but the general rules stay the same. Here the largest merge is on column `C`
![GIF_reverted merge](https://user-images.githubusercontent.com/10757813/68396950-b1da6180-0172-11ea-801f-cef4dd8adaec.gif)

I believe that there are dozens of cases that we could mention in this post. We just need a big cup of coffee and some time :)

**Comment by AMBudnik** [comment]
Not an enthusiast of a monologue but I needed to share the following case. It also breaks the UI pretty badly.

Go here and just observe https://jsfiddle.net/ywoh9n6p/

![image](https://user-images.githubusercontent.com/10757813/69139993-eda1ef00-0ac1-11ea-8194-bb72b88201ff.png)

* missing cells `C4:E5`
* missaligned rows
* missing border top for the first-row header
* missing borders for headers `C:E`

The data is not back when we edit cells but something is available in the `C` column's filer.

![image](https://user-images.githubusercontent.com/10757813/69140199-538e7680-0ac2-11ea-8aa9-1ec1d59a8c19.png)

So let's try what happens when we use the filer.

* Pick `(Blank cells)`
![GIF_2](https://user-images.githubusercontent.com/10757813/69140303-889ac900-0ac2-11ea-8e45-dd828e0b143c.gif)
Not bad!

* Pick any other value
![GIF_2](https://user-images.githubusercontent.com/10757813/69140331-9a7c6c00-0ac2-11ea-8dfc-f02b2626b626.gif)
Might be OK

* Pick everything besides `C3`
![GIF__4](https://user-images.githubusercontent.com/10757813/69140508-eaf3c980-0ac2-11ea-838f-72dd878058c6.gif)
We get double borders?

**Comment by AMBudnik** [comment]
### Main case

remains the same in 8.0.0.-beta2-rev2 https://jsfiddle.net/1hw5pcqv/

### Case 2

remains the same in 8.0.0.-beta2-rev2 https://jsfiddle.net/rwLdeuqx/

### Case 3 

remains the same in 8.0.0.-beta2-rev2 https://jsfiddle.net/f1zsqa75/1/

### Case 4

Now, when I go to that demo https://jsfiddle.net/hpqjyuz2/ (7.2.1) I cannot select B1 without other cells - they select automatically. It works well when I deselect that cells and select B1 again.

![](https://user-images.githubusercontent.com/10757813/81400671-f77de400-912d-11ea-8fdd-2274c078cd2a.gif)

7.4.2 https://jsfiddle.net/w5trd0mo/1/

8.0.0.-beta1 https://jsfiddle.net/snyea0tb/

8.0.0.-beta2-rev2 https://jsfiddle.net/w5trd0mo/

### Case 5

remains the same in 8.0.0.-beta2-rev2 https://jsfiddle.net/L3vw8c76/

**Comment by AMBudnik** [comment]
**Case 1** solved in 8.0.0-beta2-rev13 https://jsfiddle.net/AMBudnik/0Lot5kca/
![Zrzut ekranu 2020-06-9 o 15 19 31](https://user-images.githubusercontent.com/10757813/84152209-a3378e00-aa64-11ea-94d5-b65958ab5845.png)

**Comment by aninde** [comment]
**Case 2** solved in `v8.0.0-beta2-rev13` https://jsfiddle.net/aninde/rfuw89qt/
<img width="327" alt="Screenshot 2020-06-09 at 15 29 58" src="https://user-images.githubusercontent.com/30186818/84153524-4b018b80-aa66-11ea-851a-4b5df642a9fe.png">

**Case 3** still the same, but I'm not sure if it was a bug. `v8.0.0-beta2-rev13` https://jsfiddle.net/aninde/ayqpvjL9/
I will examine it and possibly open a separate issue

![case3-rew13](https://user-images.githubusercontent.com/30186818/84154724-bf88fa00-aa67-11ea-81aa-1a09be3a77a2.gif)

**Case 4** solved https://jsfiddle.net/aninde/ej1mofsg/ 
![case4-rev13](https://user-images.githubusercontent.com/30186818/84156087-602be980-aa69-11ea-8c5b-b431fbe33327.gif)

**Case 5** also fixed by `8.0.0-beta2-rev13` https://jsfiddle.net/aninde/ck3u7ro8/
<img width="435" alt="Screenshot 2020-06-09 at 15 58 47" src="https://user-images.githubusercontent.com/30186818/84156778-3921e780-aa6a-11ea-9a80-d1a8cefbcb64.png">
![case5](https://user-images.githubusercontent.com/30186818/84158108-c580da00-aa6b-11ea-8784-7ea17d61bf3b.gif)

**Comment by aninde** [comment]
Summary: only case 3 remains unfixed. I would close this issue after release and later I would move Case 3 to a separate issue.

**Comment by AMBudnik** [comment]
Here's the update for v 8.0.0

Main case - https://jsfiddle.net/nrhjcuad/- SOLVED
Case 2 - https://jsfiddle.net/uLwv2szc/1/ - SOLVED
