### ISSUE TITLE
Invalid use of <br> in content section

### ISSUE THREAD

**Issue by Qingyiii** [handsontable/handsontable#6377]
hello,I have another problem

In the content of Td,I used <br>. But they don't change lines.

How to make it effective. thanks..

**Comment by Qingyiii** [comment]
The other one is select.
 why not the items of the list(combo box) do not displayed as the sequnce of my setting ?

**Comment by AMBudnik** [comment]
If you need `<br>` and other `HTML` tags you should use the HTMLRender. Here is an example https://jsfiddle.net/9x8Lfe3j/

Unfortunately, I do not understand the second request
> why not the items of the list(combo box) do not displayed as the sequnce of my setting ?

Can you share more details or send a demo with your current progress on support@handsontable.com?

ps. be sure to secure the data from XSS attacks as we do not block those attempts.

**Comment by AMBudnik** [comment]
If there are no additional questions here I guess that we can close the topic.
