### ISSUE TITLE
`walkontable.css` and `handsontable.css` stylesheets are not in sync

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6381]
### Description

Styles that directly affect Walkontable are currently defined in two stylesheets:

- `walkontable.css` - this is the file used by Walkontable test runneer
- `handsontable.css` - this is the file used by the Handsontable build task

If styles defined for Walkontable are not in sync, we run into situation when Walkotnable tests check something different than the actual rendering in Handsontable.

`walkontable.css` is generally neglected compared to `handsontable.css`. You can see that when you load the Walkontable test runner in a web browser, the test cases look visually broken because of missing classes.

Example lines that should be in sync but are not:
   - https://github.com/handsontable/handsontable/blob/4925ce0b74f064ca67ecac83b568b952878b7910/src/css/handsontable.css#L120-L126
   - https://github.com/handsontable/handsontable/blob/4925ce0b74f064ca67ecac83b568b952878b7910/src/3rdparty/walkontable/css/walkontable.css#L80-L85

**Comment by aninde** [comment]
Tested during tests `7.3.0` and `8.0.0-beta1`. I haven't found the bugs.

**Comment by warpech** [comment]
According to the Slack discussion, it was not released in `7.3.0`, but only in `8.0.0-beta1`: https://handsoncode.slack.com/archives/C4PV4S33Q/p1582040307012100

**Comment by AMBudnik** [comment]
Issue solved in Handsontable v8.0.0

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
