### ISSUE TITLE
Infinite scroll loop on Chromium-based browsers

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6382]
### Description
There are a few factors which lead to this bug.
I can confirm it's present in Handsontable initialized inside an `iframe` element in a container with additional margins. What is significant, `iframe`'s window has to has a role of the scrollable container for Handsontable.
Then, if you try to set `scrollTop` and `scrollLeft` properties for `container.ownerDocument.documentElement` then you will get a infinite `scroll` loop.
This issue is present only in Chromium-based browsers.
 
### Steps to reproduce
Go to the demo and follow the instruction.

### Demo
https://jsfiddle.net/4f68q3hs/

### Your environment
* Handsontable version: 7.0.0+
* Browser Name and version: Chrome, Opera, MS Edge Dev
* Operating System: macOS

**Comment by AMBudnik** [comment]
Demo updated to v8.2.0 https://jsfiddle.net/handsoncode/r8hzajds/ 
Works well on my Chrome 87 - I do not experience the infinite loop.

**Comment by AMBudnik** [comment]
Closed as solved.
