### ISSUE TITLE
helper.isOutsideInput contains hard-coded classNames

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6383]
### Description
We use `helper.isOutsideInput` to determine if `mouseup` event was fired on an Handsontable's element. If the element is "outside" then we call `unlisten` on an Handsontable instance. The problem is you cannot extend the list of supported classNames.
The only option is to use `handsontableInput` or `copyPaste`/`HandsontableCopyPaste`.

### Steps to reproduce
1. Initialize Handsontable
2. Select entire column, eg.: ` A `
3. Change className of the editor's input from `handsontableInput` to `whatever`.
5. Use <kbd>ENTER</kbd> to open editing mode.
6. Click on opened `textarea`.
7. Try to close editor using <kbd>ESC</kbd>

### Demo
https://jsfiddle.net/6po2scjb/

### Your environment
* Handsontable version: 2.0.0+ (guess it's present even longer)
* Browser Name and version: n/a
* Operating System: n/a

**Comment by swistach** [comment]
@budnix suggested using common data-attr for these elements which should be recognized as a part of Handsontable.

**Comment by aninde** [comment]
Works with `8.0.0-beta2` like before https://jsfiddle.net/aninde/5823uhns/. It is still broken. The editor still doesn't open with Enter. @AMBudnik can you double check me?

**Comment by AMBudnik** [comment]
Yup, the event is present https://jsfiddle.net/vt4w8cfz/ (afterDocumentKeyDown) but the editor does not open.

Here's the editor when I open it with db-click (`<input>` element is not added)
![Zrzut ekranu 2020-07-15 o 12 02 38](https://user-images.githubusercontent.com/10757813/87532390-5c583c00-c693-11ea-9fb7-4b7f9085f6dd.png)

**My environment**
Chrome 83
![Zrzut ekranu 2020-07-15 o 12 05 42](https://user-images.githubusercontent.com/10757813/87532498-8b6ead80-c693-11ea-8db8-c4ac3c273c86.png)

**Comment by aninde** [comment]
Due to the fact that it doesn't work, I am removing it from the 8.0.0 epic.

**Comment by wojciechczerniak** [comment]
@budnix in #6652 wrote:
> The "input" element which is created in the createElements method must have an "data-hot-input" attribute 

The original example just demonstrated the problem and was not proposing any solution. So it won't work without changes

https://jsfiddle.net/gfk7x9La/

**Comment by aninde** [comment]
As @wojciechczerniak wrote original demo could not work properly on any version without changes (`this.TEXTAREA.setAttribute('data-hot-input', '')`). 

With these changes, this issue is solved by `8.0.0-beta2` https://jsfiddle.net/gfk7x9La/. 
<kbd>ENTER</kbd> opens editor.
https://jsfiddle.net/aninde/fabrx85q/ updated demo `v2.0.0` - is still broken.

**Comment by AMBudnik** [comment]
`8.0.0-beta2` works fine for <kbd>ESC</kbd> but `8.0.0` does not https://jsfiddle.net/g12avy83/

**Comment by AMBudnik** [comment]
> ### Description
> We use `helper.isOutsideInput` to determine if `mouseup` event was fired on an Handsontable's element. If the element is "outside" then we call `unlisten` on an Handsontable instance. The problem is you cannot extend the list of supported classNames.
> The only option is to use `handsontableInput` or `copyPaste`/`HandsontableCopyPaste`.
> 
> ### Steps to reproduce
> 1. Initialize Handsontable
> 2. Select entire column, eg.: `A`
> 3. Change className of the editor's input from `handsontableInput` to `whatever`.
> 4. Use ENTER to open editing mode.
> 5. Click on opened `textarea`.
> 6. Try to close editor using ESC
> 
> ### Demo
> https://jsfiddle.net/6po2scjb/
> 
> ### Your environment
> * Handsontable version: 2.0.0+ (guess it's present even longer)
> * Browser Name and version: n/a
> * Operating System: n/a

**Comment by AMBudnik** [comment]
I've moved it to https://github.com/handsontable/handsontable/issues/7233 as a regression.

**Comment by AMBudnik** [comment]
My bad. That's not a regression. The previous demo was lacking the input attribute
`this.TEXTAREA.setAttribute('data-hot-input', '')`

https://jsfiddle.net/y1eog8vL/
