### ISSUE TITLE
Cells with text have different rendered height from empty cells in Chromium 78 (Electron 7)

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#6384]
### Description
I don't know if this is a Chromium or Handsontable issue. Everything is working well in v6, but when I update my Electron application to v7 cells with text content started to look like they didn't have a bottom-border anymore:

![image](https://user-images.githubusercontent.com/3355320/67550678-5ab2a680-f707-11e9-9e56-5193776c2d0d.png)

Looking closer it seems like the cells are growing from the bottom and is eating the pixel below the cell. (Exaggerating the CSS properties a bit to make the issue more visible)

![image](https://user-images.githubusercontent.com/3355320/67551174-9306b480-f708-11e9-91ef-9dd5dff3dbb0.png)

If I remove the border-bottom for td the height difference seems to disappear (but then I don't have borders...).

![image](https://user-images.githubusercontent.com/3355320/67551389-0c9ea280-f709-11e9-992c-72b883b7c401.png)

And when I move the application window to a high dpi screen the effect is the opposite

![image](https://user-images.githubusercontent.com/3355320/67551768-f218f900-f709-11e9-85d4-66484209f17f.png)

I haven't made any changes other than the Electron version. And downgrading to v6 "fixes" the issue.

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chromium 78
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @ottosson 

Can you share your configuration?

I've made a really simple one with 7.2.2. where it seems to work fine in-app and in Chrome 78. However, I'm on Mac today so this might be the difference.
Do you use any other libraries?

![Zrzut ekranu 2019-10-25 o 10 34 08](https://user-images.githubusercontent.com/10757813/67556360-4d031e00-f713-11e9-911e-05614918cfee.png)

**Comment by ottosson** [comment]
I haven't seen the effect just looking in Chrome either. So this is a tricky issue to pin down...

```
hotSettings: Handsontable.GridSettings = {
    data: [],
    outsideClickDeselects: true,
    rowHeaders: true,
    colHeaders: true,
    startRows: 1,
    startCols: 1,
    viewportColumnRenderingOffset: 500,
    trimWhitespace: false,
    maxRows: 0,
    filters: true,
    rowHeights: 20,
    dropdownMenu: ["filter_operators", "filter_by_value", "filter_action_bar"],
    fillHandle: {
      autoInsertRow: false,
    },
    fixedColumnsLeft: 2,
    licenseKey: "non-commercial-and-evaluation",
    columns: [],
    afterColumnResize: () => {
      this.myTable.render();
    },
    beforeChange: (changes: [number, number, string, string][]) => {
      changes.forEach((change) => {
        if (!change[3]) {
          change[3] = "";
        }
      });
    },
    afterChange: (changes) => {
      if (!changes) {
        return;
      }

      changes.forEach(([row, col, oldValue, newValue]) => {
        const cellProperties = this.myTable.getCellMeta(row, col as number);

        if (cellProperties.orgValue !== newValue) {
          this.myTable.setCellMeta(row, col as number, "hasChanged", true);
        } else {
          this.myTable.setCellMeta(row, col as number, "hasChanged", false);
        }
      });

      this.myTable.render();
    },
  };
```

and some custom css:
```
.handsontable {
  color: #222;
  font-size: 85%;

  .htUIInput.htUIButtonOK input {
    background-color: #eee !important;
    border: 1px solid #d2d1d1 !important;
    color: #000 !important;
  }

  .htUISelectionControls {
    padding-right: 4px;
  }

  .htUIInput.htUIButtonOK input:hover {
    border-color: #b9b9b9 !important;
  }

  .htUIClearAll a,
  .handsontable .htUISelectAll a {
    text-decoration: none;
  }

  .htUIMultipleSelect .ht_master .wtHolder {
    overflow-y: auto;
    background: transparent;
  }

  .htUIMultipleSelect .handsontable .htCore {
    width: 100%;
  }
}

.htDropdownMenu table tbody tr td .htItemWrapper {
  margin-left: 0 !important;
  margin-right: 0 !important;
}

.htDropdownMenu table tbody tr td {
  padding: 0px 6px 0 6px !important;
}

.lockedCell {
  background-color: #f0f0f0 !important;
  color: black !important;
  white-space: nowrap !important;
}

textarea.handsontableInput {
  background-color: #ffe1b0;
  color: black;
}
```

**Comment by AMBudnik** [comment]
With those settings, I still got no issues.

![Zrzut ekranu 2019-10-25 o 13 58 44](https://user-images.githubusercontent.com/10757813/67569645-b2650800-f72f-11e9-8b5d-aa7cb6b02c3c.png)

However, what I changed is loading data on the initialization. Can you please make a test and load data from our helper?

`Handsontable.helper.createSpreadsheetData(rows, columns)`

How do you add the `o` ? Is that a renderer or you're using CSS `::after` > `content`?

**Comment by ottosson** [comment]
It is not a ::after pseudo-element. When using the Handsontable helper it still looks the wrong:

![image](https://user-images.githubusercontent.com/3355320/67570488-d3c6f380-f731-11e9-821e-a5db50c357d4.png)

Maybe it has more to do with Electron then?

**Comment by AMBudnik** [comment]
I saw a similar result in one of our Client's tables. I have asked him for feedback. However, in his case the missing borders were gone more randomly so this might be something different.

**Comment by AMBudnik** [comment]
@aninde please check this on your device
I did not get feedback from the mentioned Client

**Comment by ottosson** [comment]
I tried to start a new Electron 7 project from scratch, and it looks correct there. So maybe it's just a case of "too many moving parts"... and something in my application is wrong.

**Comment by AMBudnik** [comment]
Thank you for checking that. I am very curious about what's causing these misalignments.

**Comment by ottosson** [comment]
Yup, sure is annoying =) If I ever figure out what caused it I will add it to this thread.

Closing for now as it doesn't seem to be neither Electron or Handsontable that is causing the issue as far as I can tell right now.
