### ISSUE TITLE
Wrong selection area after sorting with hidden rows

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6386]
### Description
Sorting with hidden some rows lead the invalid area of selections.

### Steps to reproduce

1. Sort the second column.
2. Next sort third column.

### Demo

https://jsfiddle.net/kjz76who/1/

![Oct-25-2019 14-21-07](https://user-images.githubusercontent.com/1555809/67576155-548bec80-f73e-11e9-90db-1854ee0ea43f.gif)

**Comment by AMBudnik** [comment]
Remains the same in 8.0.0-beta2-rev6 https://jsfiddle.net/f5bdwLnh/

**Comment by AMBudnik** [comment]
**Solved** in 8.0.0.-beta2-rev10 https://jsfiddle.net/AMBudnik/a0ekxbsq/

**Comment by AMBudnik** [comment]
The issue solved in v8.0.0. Updated demo https://jsfiddle.net/p6dc2rL0/
