### ISSUE TITLE
Is there a way to show columns <td> equal to data column counts?

### ISSUE THREAD

**Issue by dsc-ian** [handsontable/handsontable#6391]
Is there a way to show all `<td></td>` in the html instead of appending it when scrolling. Like I have a Data 

var data = [
    ['1','2','3','4',....'30'],
    ['1','2','3','4',....'30'],
    ['1','2','3','4',....'30']
]

at render it can only show `<td></td>` that fit on screen for example 4 `<td>` but I have 30 `<td> `all in all but in only show it in the html 4 `<td>` is there a way to just show all 30 `<td>`?

**Comment by aarondfrancis** [comment]
Maybe check out https://handsontable.com/docs/7.2.0/Options.html#renderAllRows.

**Comment by AMBudnik** [comment]
True. If all the columns are renderer `renderAllRows: true` will work. If you load more columns then you'd need to add [viewportColumnRenderingOffset](https://handsontable.com/docs/7.2.2/Options.html#viewportColumnRenderingOffset) as well.
