### ISSUE TITLE
Some headers are gone if we hide and show them again

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6395]
### Description

Some headers are gone if we hide and show them again.

### Steps to reproduce

1. Go to https://jsfiddle.net/2qvgynd1/
2. Wait and see that two last headers are missing

![headers](https://user-images.githubusercontent.com/10757813/67684885-47683b00-f994-11e9-85ee-5caa5c8be176.gif)

3. Open editor of any cell to see borders comming back.

### Styles 
The missing header seems to be styled well

![image](https://user-images.githubusercontent.com/10757813/67685664-cc078900-f995-11e9-896f-435dd686f846.png)

However, they do not fit into the `ht_clone_top` element
![image](https://user-images.githubusercontent.com/10757813/67685922-2dc7f300-f996-11e9-8320-8af32fd31971.png)

### Demo

https://jsfiddle.net/2qvgynd1/

### Your environment
* Handsontable version: 7.2.2
_Does not seem to be version related_
Also, replicable using resources from the [latest rc-1 build](https://github.com/handsontable/handsontable/pull/5945#issuecomment-544983941) https://jsfiddle.net/mr9vo1ge/
and [SVG improvements](https://github.com/handsontable/handsontable/pull/6157/files)
* Browser Name and version: Chrome 77
* Operating System: Windows 10

`inform Zen # 23698`

**Comment by AMBudnik** [comment]
Still remains the same in 8.0.0.-beta1 https://jsfiddle.net/qo1askxt/ and 8.0.0.-beta2-rev2 https://jsfiddle.net/qer6do8g/

**Comment by aninde** [comment]
This issue will be fixed by the upcoming `v8.1.0` https://jsfiddle.net/z9vhy076/
Works well on every supported browser on macOS Catalina 10.15.17.

**Comment by AMBudnik** [comment]
I'm glad to see this issue solved. Thank for fixing @jansiegel
