### ISSUE TITLE
Rows of type Dropdown turning into multiline cells instead of automatic column size fitting entire row.

### ISSUE THREAD

**Issue by michaelpulis** [handsontable/handsontable#6396]
Hi, I'm encountering an issue where cells of the type dropdown span turn into multiline cells, instead of the auto col size adjusting the size accordingly:
![image](https://user-images.githubusercontent.com/35961035/67696335-f7df3a80-f9a6-11e9-9af3-a6fe66e1e859.png)

Upon click the size of the cell changes to the correct value, and the table proceeds to awkwardly shift from the cell being one line, to two lines, which causes the entire table to stutter as in shifts between the two states.

Any idea what could be causing this issue/how to correct it?

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: Chrome 77.0.3865.120 
* Operating System: Windows 8.1

**Comment by AMBudnik** [comment]
Hi @michaelpulis 

please share your settings.

**Comment by michaelpulis** [comment]
The table has the following settings: 

nested headers
width: '100%',
filters: true,
dropdownMenu: true, 
manualColumnResize: true,
manualRowResize: true,
minSpareRows: 0, 
autoRowSize: false,
autoColSize: false,
allowInsertRow: false,
contextMenu: true,
custom cell drawing

**Comment by AMBudnik** [comment]
This happens as you do not have any space in this string. Here https://github.com/handsontable/handsontable/issues/3116 is the same issue.

Please feel free to any anything to https://github.com/handsontable/handsontable/issues/3116 if you think that we're missing any crucial details.

**Comment by michaelpulis** [comment]
So there hasn't been a fix found yet?

**Comment by AMBudnik** [comment]
Not yet. But as more users are having the same issue we might speed up the scheduling process. We did not finish 2 major topics that we're doing for the last couple of months. Once we'll be able to push the changes (in v 8.0.0-rc1) we'll have more time for bug-fixing.
