### ISSUE TITLE
Export To Many Files

### ISSUE THREAD

**Issue by linkzda** [handsontable/handsontable#6398]
### Description
Hi, when i export to csv my table, handsometable generate multiple files ( 4 csv's or more) and each file contain different information of my table.  I just want only 1 csv. 

### Demo
var btnExport= document.getElementById("btnExporPub");
            var exportPlugin1 = hot.getPlugin("exportFile");

            btnExport.addEventListener("click", function() {
              exportPlugin1.downloadFile("csv", {
                bom: false,
                columnDelimiter: ",",
                columnHeaders: true,
                exportHiddenColumns: true,
                exportHiddenRows: true,
                fileExtension: "csv",
                filename: "Handsontable-CSV-file_[YYYY]-[MM]-[DD]",
                mimeType: "text/csv",
                rowDelimiter: "\r\n",
                rowHeaders: true
              });
            });

### Your environment
* Handsontable version: 7.2.1
* Browser Name and version: Chrome 78.0.3904.70 (Build oficial) (64 bits)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
We are not able to overwrite your file. We can only generate a new one.
