### ISSUE TITLE
Date cell type - Today is not working properly

### ISSUE THREAD

**Issue by FEndo** [handsontable/handsontable#640]
I was looking at your demo page (http://handsontable.com/demo/date.html) for the datepicker and just realized that the "Today" on the picker is not working properly.
It actually updates the month and year on the picker but it did not update the day. If you do that manually, then it is OK, it writes the "Today" date on the field.

Thanks,
Flavio

**Comment by AMBudnik** [comment]
Issue related to abandoned library.
