### ISSUE TITLE
Nested Headers seems limited to 1000 for the first nested header

### ISSUE THREAD

**Issue by mscotch1** [handsontable/handsontable#6406]
### Description
The nested header plugin seems to have some kind of limit for 1000 nested subheaders for the first superheader. The highlighting still works correctly, but the boundary between superheaders is in the wrong spot, and there are columns at the end of the matrix that are seemingly hanging off the edge with no super header at all.

### Steps to reproduce
1. Make Handsontable with two levels of nested headers, the top level of which should contain over 1000 subheaders in a superheader
2. Scroll to the boundary of the superheaders

### Demo
https://jsfiddle.net/Lbpcw0eh/2/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Firefox 71.0b2 and Chrome 78.0.3904.70
* Operating System: Windows 10 Home

**Comment by AMBudnik** [comment]
Thank you for sharing @mscotch1 

I'd need to investigate the subject a bit further as if we set up `viewportColumnRenderingOffset: 2010` we have 4 headers missing.

![image](https://user-images.githubusercontent.com/10757813/67865575-c80b7080-fb27-11e9-89b4-e8772095ce0c.png)


**What do we know**
* The data length is `2005` elements (2003 named, + 0 + disc) 
* there are 3 header elements with the same length of (1, 1002, 1002)
![image](https://user-images.githubusercontent.com/10757813/67865024-e329b080-fb26-11e9-9517-ba42dd1ca385.png)

**Comment by AMBudnik** [comment]
Additionally, when we zoom out we get

![image](https://user-images.githubusercontent.com/10757813/68390844-6de15f80-0166-11ea-9a8b-bd50b1d18525.png)

**Comment by wojciechczerniak** [comment]
HTML Table spec limits `colspan` to maximum of 1000: https://html.spec.whatwg.org/multipage/tables.html#dom-tdth-colspan

**Comment by AMBudnik** [comment]
good finding @wojciechczerniak ! 👍

**Comment by wojciechczerniak** [comment]
@AMBudnik We need `wontfix` label. This is a limitation in HTML and web browsers.

@scarletfog Maybe we should add this to the plugin "known limitation" or "features" section.

**Comment by AMBudnik** [comment]
Issue moved to [handsontable/docs #105](https://github.com/handsontable/docs/issues/105) via [**ZenHub**](https://www.zenhub.com/)
