### ISSUE TITLE
The last edited cell is invalid unless I select another 

### ISSUE THREAD

**Issue by asaadmohammed74** [handsontable/handsontable#6408]
### Description
When I change a cell then click a button and then call `validateCells` on the click event, I get invalid unless I focus on another cell then click again, then I get valid

### Steps to reproduce
1. Edit a cell
2. Click a button
3. Call `validateCells` without selecting another cell after the edit

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome for Android 77
* Operating System: Android 7

![IMG_20191031_131048](https://user-images.githubusercontent.com/33846280/67942501-a28e6d80-fbe0-11e9-9a3c-ff44d4b1d6f3.png)

**Comment by aninde** [comment]
@asaadmohammed74 thank you for reporting the problem. Can you add a demo so that we can try to reproduce the problem?

**Comment by asaadmohammed74** [comment]
sorry but I'm on mobile, jsfiddle isn't working very well.
but as I said it's a pretty standard setup just a normal table a button

**Comment by AMBudnik** [comment]
Hey @asaadmohammed74 

the `"Some data is invalid"` message does not come from Handsontable itself.

Can you guide me on adding your logic to this demo https://jsfiddle.net/5pq674yr/? Table looks the same but I guess that some crucial settings are causing the bug.

**Comment by AMBudnik** [comment]
If you still get the same issue please send me a message to support@handsontable.com
