### ISSUE TITLE
colHeaders order is not updated after manual move with empty object data source

### ISSUE THREAD

**Issue by s1monj** [handsontable/handsontable#6413]
### Description
When a column with no object data (no keys) is moved the header order is not saved.

getColHeader() should return the column header order after a manual move regardless of missing data.

workaround: ensure empty keys (eg "colA": null) are in data.

### Steps to reproduce
1. Move column cB to before cA - header order is saved correctly.
2. Move column cD to before cC - header order is not saved.

### Demo
https://jsfiddle.net/simonlj/fma54dcx/60/

### Your environment
* Handsontable version: @latest (7.2.2)

**Comment by AMBudnik** [comment]
Not sure if that's an issue if you declare that data for 3rd column should be something that does not exist. 
If you add missing keys in the first line of data https://jsfiddle.net/sjybvwn7/ that it works as expected.

This issue has to be further investigated. Not sure if we do not count `data` length besides working on the result of `countCols` which shows `4` (correct value).

@wojciechczerniak how do you think?

**Comment by s1monj** [comment]
Our use case is that users create new columns/headers and arrange them in order before they start entering data.

We use afterColumnMove to save the column order to the server based getColHeader() so that the order of the columns is saved before they start inputting data.

The workaround of creating null keys is an easy fix so this is not a big problem, I just expected the getColHeader() and headers order to be independent of the data.

**Comment by AMBudnik** [comment]
Hey @s1monj 

I've been told that it changes in the 8.0.0. Please test this demo https://jsfiddle.net/0shap84L/ and let me know if it works for you.

**Comment by AMBudnik** [comment]
Hey @s1monj 

Have you had time to test it?

**Comment by AMBudnik** [comment]
Issue **solved**, works well in 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/2dru9os5/ but it also worked well in 8.0.0-beta1 https://jsfiddle.net/AMBudnik/xeqyd45f/ (as previously mentioned)

**Comment by AMBudnik** [comment]
Hi @s1monj 

i’m glad to announce that Handsontable v8.0.0 that solves this issue is live!   

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. ✍️ 

I hope that the amount of work that we put on the v8 will help you to improve your project.
