### ISSUE TITLE
Unable to replace Array type value with non-Array type

### ISSUE THREAD

**Issue by twjacobsen** [handsontable/handsontable#6414]
### Description
All my data is provided and validated through our backend - and some of my data contains multiple values (data from the backend is an array).
But, if the user chooses to input just one value (ie. selecting from a Autocomplete), HOT tries to save a string.
This fails (without any indication as to what happened).

After debugging, I found a check in `core.js` that disallows updating data if original value is of object type and new value is not.

What can I do to get around this limitation? And, what are the arguments around having this limitation?

### Steps to reproduce
See the demo data

### Demo
https://jsfiddle.net/bzc3aqu4/

### Your environment
* Handsontable version: 7.1.1 (I looked at the source code, the check is 4+ years old so I don't think it's related to a recent version change :) )
* Browser Name and version: Latest Chrome
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
Hey @twjacobsen 

have you considered passing structures of data via cell meta instead? Autocomplete/dropdown/select cell types can only hold an array of string or an array of numbers. While the cell meta do not have any limitations. Here's a simple example with adding and receiving cell meta https://jsfiddle.net/handsoncode/tb7rw0xk/

**Comment by twjacobsen** [comment]
Hi, sorry for the late reply.

I'm not sure how your suggestion could help me. In your example, the data in the grid is not an array, it's just a string.

I can't easily introduce special handling for this kind of data, because Handsontable just receives the data and we use one of the Handsontable hooks to react to changes.

So, I'm just wondering why it's not allowed to replace source data of object type with new data of non-object type.

**Comment by AMBudnik** [comment]
Hey @twjacobsen 

I guess I'm missing something here. First of all Handsontable officially only supports an array of objects or an array of arrays. 

> Handsontable binds to your data source (list of arrays or list of objects) by reference. 
src https://handsontable.com/docs/7.2.2/tutorial-data-binding.html

so if you want to use nested data or pass multiple information to the cell you can
- parse the data, or
- use metadata (as mentioned in the post above)

**Comment by twjacobsen** [comment]
Right, I understand what's supported - and we provide data in a supported fashion.

```
// Snipped from the demo attached to the issue:
data: [
    ['', 'Tesla (edit fails)', 'Nissan', 'Toyota', 'Honda', 'Mazda', 'Ford'],
    ['2017', [10], 11, 12, 13, 15, 16],
    ['2018', [10], 11, 12, 13, 15, 16],
    ['2019', [10], 11, 12, 13, 15, 16],
    ['2020', [10], 11, 12, 13, 15, 16],
    ['2021', [10], 11, 12, 13, 15, 16]
  ]
```
Look at the 2nd column of rows 1...N - that's whats introducing our problem. It's supported just fine, and if I try to write an array to cell (1,1), it works just fine. But if I try to write just a string, it does not. No warning, no error, the value is just ignored.

So what I'm asking is, what's the reason for enforcing this kind of limitation? And is there something I can do to work around it without having to rework all my existing logic?

**Comment by AMBudnik** [comment]
To be honest applying `[10]` instead of `10` is already using something that is not supported and everything that goes after this step hasn't been tested and might produce unwanted behavior. There are dozen of methods that expect a single value not an array.

**Comment by twjacobsen** [comment]
There is a very explicit check in `core.js` to "handle" this:

https://github.com/handsontable/handsontable/blob/master/src/core.js#L793

So I'm assuming it's something some developer has thought about at some time. So I'm just looking for an explanation beyond what's in the comments in the code.

**Comment by AMBudnik** [comment]
@wojciechczerniak maybe you'd be able to guide us here?

**Comment by wojciechczerniak** [comment]
@AMBudnik No, sorry. You will have to ask at the next dev meeting.

I'm pretty surprised it worked up to this point. Data should be mapped to Handsontable format and the other way round on export / database save.

**Comment by twjacobsen** [comment]
Any news on this?

As a workaround, I've had to add this to our editors:

```typescript
editor.prototype.saveValue = function(valueToSave: unknown, ctrlDown: boolean) {
  ...
  if (isMultiValue) {
    valueToSave = valueToSave.map(innerValue => innerValue.map(v => _.castArray(v)));
  }

  parentEditor.saveValue.apply(this, [valueToSave, ctrlDown]);
}
```

This does feel like a hack though, mostly because `valueToSave` is typed as `any` in the model, and that gives me very little confidence this hack will keep working through the versions of HOT.

Are there better ways to do it? I mean, it works, but eh...........

**Comment by dtomaszewski** [comment]
Hi @AMBudnik how it could be marked as answered and closed when problem still exists ?

**Comment by wojciechczerniak** [comment]
@dtomaszewski What would you expect us to do? Should we mark this as a feature request? 

Like I mentioned earlier, this is not supported. Only primitive JS types (and not all of them) are supported as a value in an array of arrays configuration, and an object which contains primitive values in an array of objects use case.

**Comment by twjacobsen** [comment]
So, what is the reason for not supporting arrays as values? I mean, I would guess that's a pretty common way of representing multiple values in a single cell.

**Comment by AMBudnik** [comment]
Hey @twjacobsen 

If you need more information within a single cell we offer a [`handsontable` cell type](https://handsontable.com/docs/7.3.0/demo-handsontable.html) and/or [cell meta](https://jsfiddle.net/handsoncode/tb7rw0xk/).

**Comment by twjacobsen** [comment]
The data I need for a workaround is there. I have the working code present.

But, it still feels like something that should be supported out of the box.

To repeat my question:

What's the **supported** way of handling **mixed types of data**? Ie. replacing a string value with an array value or an array value with a string value, when editing.

**Comment by AMBudnik** [comment]
I can imagine that this is not the answer you'd like to get but Handsontable data is 2-dimensional, so we do not support arrays as values for cells. You can imagine a room full of seats where only one person can take a seat or a seat can be empty. We're just like that, we allow only a single value to be addressed under `[X, Y]` coordinates. 

> But, it still feels like something that should be supported out of the box.

Of course, data can be very complex but at this point, we support simple structures only.
