### ISSUE TITLE
colHeader does not render after undoing remove column

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6416]
### Description
colHeader does not render correctly after removing undo column.

### Steps to reproduce

1. Use demo https://jsfiddle.net/aninde/5wubtf8o/
2. Remove column B.
3. Undo removing column B by <kbd>cmd/ctrl</kbd>+<kbd>z</kbd>

![Screen Recording 2019-11-04 at 08 55 43 2019-11-04 08_57_38](https://user-images.githubusercontent.com/30186818/68106379-c18f4700-fee1-11e9-98c8-061ecb54a903.gif)

### Demo

https://jsfiddle.net/aninde/5wubtf8o/
fixed `1.18.1` https://jsfiddle.net/aninde/w7adzxgs/

### Your environment
* Handsontable version: 2+
* Browser Name and version: Firefox 70
* Operating System: MacOs Pro Catalina 10.15

**Comment by aninde** [comment]
Duplicates https://github.com/handsontable/handsontable/issues/6410

**Comment by aninde** [comment]
The issue is replicable on 8.0.0 and it is related with https://github.com/handsontable/handsontable/issues/6670

**Comment by aninde** [comment]
Closing as a duplicate of very rich linked https://github.com/handsontable/handsontable/issues/6992.

**Comment by AMBudnik** [comment]
#6670 has been fixed in Handsontable v 8.0.0
