### ISSUE TITLE
TrimRows plugin performance issue

### ISSUE THREAD

**Issue by bamminger** [handsontable/handsontable#6420]
### Description
We use the TrimRows-Plugin to render a hierarchy with handsontable. Using that plugin with a lot of rows creates a performance bottleneck in our application. Using a Set instead of an Array to check if a row is trimmed, improves the performance significantly. A "hacked" version with the improved performance can be found in the demo.

### Steps to reproduce
1. Handsontable with a lot of trimmed rows (> 50k)
2. Untrim a lot of these rows
3. Untrimming / Trimming is really slow

### Demo
https://jsfiddle.net/e546yvbn/6/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: IE 11, Chrome 78, Firefox 70
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the demo. Maybe there is something that can be done to make it works faster. Surely, this subject has to be investigated.

**Comment by AMBudnik** [comment]
Hi @bamminger 

we've just published Hansontable 8.1.0 that improves the performance of trimming rows.

Here's a little updated https://handsontable.com/blog/articles/2020/10/handsontable-8.1.0-has-been-released
