### ISSUE TITLE
Horizontal Scrolling slow with the presence of a row header

### ISSUE THREAD

**Issue by pinuchfab** [handsontable/handsontable#6422]
### Description
For a grid configured with 20+ columns (just enough to trigger the horizontal scroll) and a row header sticking at the left of the grid, the horizontal scrolling is jumping and slow. The response is unfortunately poor which I believe "initially" might be caused to the way the row header is redrawn.

### Steps to reproduce

1. create a grid with 20+ columns to essentially trigger horizontal scrolling
2. make sure the grid is configured to have a row header (with or without a function)
e.g: rowHeaders: (row) => "<div class="rowHighlight"></div>",
3. make sure the grid has 100+ records
4. try to scroll horizontally, please notice the jumping

### Demo
No demo as yet

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Version 78.0.3904.87 (Official Build) (64-bit)
* Operating System: Win10

**Comment by AMBudnik** [comment]
Hey @pinuchfab 

do you mean the jumping when we scroll up and down (vertically)?

![GIF](https://user-images.githubusercontent.com/10757813/68390307-450c9a80-0165-11ea-8ed4-61322b0d1ef1.gif)

I am not able to get any weird behavior while scrolling horizontally.

I'm also on Windows 10 and Chrome 78

**Comment by pinuchfab** [comment]
We will send you a video.
I have actually noticed a strange visual in your video, the row headers seems to jump slightly from the left border when the scroll bar departs and comes back at x=0.
Also the value you have more simple than ours, we have text and ellipsis, also we do have icons inside some of the cells.
I have attached a screen shot for understanding a bit better our more complex usage of the grid.
Regards,
Fabien

![image](https://user-images.githubusercontent.com/18369301/68668417-ff264c80-053f-11ea-8fba-9cc42d8c436e.png)

**Comment by AMBudnik** [comment]
Do you use any styling for containers that are parents for the Handsontable's `DIV`?

**Comment by pinuchfab** [comment]
Our parent container is essentially flex:
![image](https://user-images.githubusercontent.com/18369301/68758289-707c0300-0605-11ea-8dd0-9ff5e7785da7.png)

also we have a bit of styling added to the actual handson widget (under the parent shown above):
![image](https://user-images.githubusercontent.com/18369301/68758786-5abb0d80-0606-11ea-8cfe-0d205921dc97.png)

I m going to see if changing some of the styling helps,
I have noticed the redraw while scrolling is caused in parts by a style change on the grid:
![image](https://user-images.githubusercontent.com/18369301/68758942-ae2d5b80-0606-11ea-887a-9507e08bdc8d.png)

innerBorderLeft is added or removed.

Not sure if this helps,
I will send a video next.
Fabien

**Comment by pinuchfab** [comment]
Using the perf monitor, I am trouble shooting to identify the culprit:
This is me clicking on the scroll bar right button to scroll the grid to the right.
It took 1sec.
Details of actions:
![image](https://user-images.githubusercontent.com/18369301/68789404-50683600-063d-11ea-82e4-dd3d5f557064.png)


By drilling a bit more I have identified the expensive calls:
![image](https://user-images.githubusercontent.com/18369301/68789834-19465480-063e-11ea-913e-b3033d4499f7.png)

Then I isolated the culprits:
![image](https://user-images.githubusercontent.com/18369301/68790334-04b68c00-063f-11ea-88cc-3c69d029a4a4.png)

I have noticed hat the autocomplete is expensive to redraw (autocomplete renderer).
We have 1/4 of columns set as autocomplete.
To reduce the impact I have changed our code to use text renderer instead for read-only mode (autocomplete only necessary in edit mode):
![image](https://user-images.githubusercontent.com/18369301/68792279-f4a0ab80-0642-11ea-9821-45b0706820f6.png)

Other notice-able expensive calls are (HoT I believe):
![image](https://user-images.githubusercontent.com/18369301/68792436-3fbabe80-0643-11ea-8a71-bc061568c6bd.png)
![image](https://user-images.githubusercontent.com/18369301/68792821-0d5d9100-0644-11ea-9e2f-abf8fddc8b99.png)
![image](https://user-images.githubusercontent.com/18369301/68792911-37af4e80-0644-11ea-840e-cd1db7c8c7e7.png)
![image](https://user-images.githubusercontent.com/18369301/68793155-9bd21280-0644-11ea-9c64-3713b7a886f9.png)


Our code use a almost 10% of the total time:
![image](https://user-images.githubusercontent.com/18369301/68790126-9f629b00-063e-11ea-83a0-0928da92e32b.png)
![image](https://user-images.githubusercontent.com/18369301/68792068-8e1b8d80-0642-11ea-833b-1b1978f95a9a.png)
![image](https://user-images.githubusercontent.com/18369301/68793362-f79c9b80-0644-11ea-94c4-9088d438063e.png)


I hope this helps.
Fabien.

**Comment by pinuchfab** [comment]
I have also noticed this expensive redraw when compensating the with during an horizontal scroll:
![image](https://user-images.githubusercontent.com/18369301/68853552-26ad1e80-06d2-11ea-91d1-35ae879bda11.png)

Commenting out the compensation prevents an expensive relayout calcultion when strating scrolling.

**Comment by pinuchfab** [comment]
We have mostly solve our problem of performance but are not 100% satisfied.
Actions taken:
-> In HoT code: I commented out the code for scroll row header correction (as shown in previous comment)
-> In HoT code: I have disabled the code that insert an innerLeftBorder class when scrolling  (as shown in previous comment)
-> From our Code: in readonly mode, I have switched off the autocomplete renderers, and instead use text renderer

The remaining problem is when the scroll thumb leaves the left edge, which takes 500ms.
Could you please help us understanding what could slow down this action.
But also is someone looking into improving the points mentioned above,.
Thanks for your help on this matter.

**Comment by pinuchfab** [comment]
Here is a demo showing the remaining issue with horizontally scrolling from or to left edge.

[Video.zip](https://github.com/handsontable/handsontable/files/3851092/Video.zip)

**Comment by AMBudnik** [comment]
> We have mostly solve our problem of performance but are not 100% satisfied.

I think that you should be satisfied after we publish those changes https://github.com/handsontable/handsontable/issues/5769

**Comment by AMBudnik** [comment]
Hey @pinuchfab 

have you had time to test our beta version?

`npm install handsontable@beta`

resources

https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js

I got a lot of positive feedback on this version's performance

**Comment by pinuchfab** [comment]
Hello,
We are now trying the new beta and will come back to you whether the scrolling has improved both vertically and horizontally.
Regards,

**Comment by pnowak** [comment]
Hi @pinuchfab 

Ok. We will wait for your conclusion.
