### ISSUE TITLE
The column type: data is not protected against pasting data using autoFill / fillHandle

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6423]
### Description
When we have next to each other a column of the `numeric type`, and next to the column of the `data type` with the help of autoFill it is possible to drag the data.
Regardless of setting `allowInvalid`. 
The columns are protected against pasting.

### Steps to reproduce

1. Use demo https://jsfiddle.net/aninde/o1y7bz3s/ 
2. Select first row in `Price` column.
3. Drag FillHandle to the right.

**Actual result:**
The data will not be displayed and an error will appear in the console.
_TypeError: e.search is not a function_ //Firefox
_TypeError: e.search is not a function. (In 'e.search(/[A-z]/g)', 'e.search' is undefined)_ //Safari

![column_different_types](https://user-images.githubusercontent.com/30186818/68306134-3e205200-00a9-11ea-89ea-069c229e4720.gif)

**Expected result:**
This should work as if you were pasting incorrect data. Such as is implemented on `numeric` type. The cell should be colored in red. The error should not appear in the console.

Example of good security of `numeric` type column
![Screenshot 2019-11-06 at 15 25 01](https://user-images.githubusercontent.com/30186818/68306374-bb4bc700-00a9-11ea-8982-71b36f88373a.png)

### Demo

https://jsfiddle.net/aninde/o1y7bz3s/

### Your environment
* Handsontable version: 1.14+
* Browser Name and version: any
* Operating System: MacOs Pro Catalina, but not related

**Comment by aninde** [comment]
The issue stays the same with 7.4.0 v. https://jsfiddle.net/aninde/o1y7bz3s/2/

**Comment by AMBudnik** [comment]
Hey @aninde 
this seems to be the same as https://github.com/handsontable/handsontable/issues/4119
Action - using fill handle from a numeric to a date cell type
Result - error in the console
