### ISSUE TITLE
我合并了几行之后，再插入行，那我之前合并的行会拆开

### ISSUE THREAD

**Issue by webwhy** [handsontable/handsontable#6427]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey @webwhy 

we provide support only in English and Polish. Please create a new, full report in English.
