### ISSUE TITLE
Resizing is able to make rows shorter than expected what results in row misalignment

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6429]
### Description

It's a bit hard to replicate but after a couple of tries, you should get the same result. The issue relates to resizing rows manually. It looks like we're able (in some odd cases) to make rows shorter than the default value.

### Steps to reproduce

1. Make a row higher
2. Double click the handler of the row
3. Try to trigger the handler a bit higher

![GIF](https://user-images.githubusercontent.com/10757813/68382360-d83cd480-0153-11ea-9cab-00c2a80d43bb.gif)

**Result**
* Rows are a bit misaligned
* The last header is cut
* `afterRowResize` hook shows odd values. The last printed result is `12` while it is a bit more.

### Additional info
* even when [dbclick doesn't work in 8.0.0-rc1 from 31/10/19](https://github.com/handsontable/handsontable/issues/6428) we're able to get the same result by just moving the handler a couple of times up. Demo https://jsfiddle.net/h2g87seo/5/

### Demo

https://jsfiddle.net/h2g87seo/4/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 77
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
@AMBudnik Can't reproduce with random beta.2: https://jsfiddle.net/Lpwbj07e/

- We did some fixes for `afterRowResize` arguments recently
- DBLClick was fixed in beta.2
- Headers is not cut
- Rows are not missaligned


But, please, retest it properly.

**Comment by AMBudnik** [comment]
@wojciechczerniak I've tried the beta2 (last rev 22) https://jsfiddle.net/5uycp1xj/ and couldn't replicate the issue. However, I'm testing this on macOS. I'll check it out on Windows on Monday.

**Comment by AMBudnik** [comment]
I've tried the same demo on Windows 10 and the issue is not replicable. Good catch @wojciechczerniak! 
We can add to 8.0.0 RN as we need to do some small adjustments.
