### ISSUE TITLE
The `afterRowResize` hook shares unbelievable results in the 2nd parameter

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6430]
### Description

The `afterRowResize` hook shares unbelievable results in the 2nd parameter. It looks like we're getting some cursor coordinates instead of the row height value.

![image](https://user-images.githubusercontent.com/10757813/68383386-d5db7a00-0155-11ea-9c76-ea70c5c25aaf.png)

As the `beforeRowResize` is buggy and it shows something [completely different](https://github.com/handsontable/handsontable/issues/3328) we should check those two issues altogether.

### Steps to reproduce

1. Make any row higher
2. Use the same handler to move it up the cell you previously resized

![negative values in hook](https://user-images.githubusercontent.com/10757813/68383098-46ce6200-0155-11ea-88cf-d95d164263b4.gif)

### Demo

https://jsfiddle.net/h2g87seo/6/ (`8.0.0-rc1 from 31/10` broken)
https://jsfiddle.net/h2g87seo/7/ (`7.2.2` broken)
https://jsfiddle.net/h2g87seo/8/ (`6.2.2` broken)
It doesn't seem to be version related

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 77
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
Looks like it was fixed in v8-beta2: https://jsfiddle.net/h3gmo8Ls/

Probably with #3328. @AMBudnik please confirm

**Comment by AMBudnik** [comment]
@wojciechczerniak 

I've checked 8.0.0-beta2-rev18 https://jsfiddle.net/csd0t374/ However, what concerns me is the `null` value when we try to resize the row to be smaller than the 22px defined. Is that intended?

**Comment by wojciechczerniak** [comment]
> However, what concerns me is the `null` value when we try to resize the row to be smaller than the 22px defined. Is that intended?

Will be fixed in #7074

**Comment by AMBudnik** [comment]
True. Issue fixed with https://github.com/handsontable/handsontable/issues/7074 in `8.0.0-beta2-rev21`

**Comment by AMBudnik** [comment]
Fix is available from version 8.0.0-beta2 and stable 8.0.0.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
