### ISSUE TITLE
After moving resized row backlight’s row (shadow) is not displayed properly on Firefox and Edge (nonChromium) on Windows

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6431]
### Description
After moving resized row backlight’s row (shadow) is not displayed properly.
It always displayed on the top of table, even when you resized and moved the last row. 

**Exceptions:**
This bug occurs only on Firefox 70 and 62/ MacOs Catalina 10.15 and Windows 10/ IE 11 and Microsoft Edge. However, bug doesn't appear on Microsoft Edge Dev 80 on MacOs. 

### Steps to reproduce

1. Use demo https://jsfiddle.net/aninde/5ef1a08y/
2. Resize first row.
3. Move resized row to the bottom of table and drop it.
4. Select the resized row once again.

**Actual (bugs) result:**
Firefox
The shadow of row (backlight in code) is displayed on the top of the table.
![resize-move-shadow](https://user-images.githubusercontent.com/30186818/68383894-c7419280-0156-11ea-9808-99b428508c02.gif) 

Windows 10/ Internet Explorer 11
Even worse. In addition, blue overlay selection is only on the half of cell
![image (1)](https://user-images.githubusercontent.com/30186818/68384988-20122a80-0159-11ea-8138-5d060a15915a.png)

Windows 10/ Microsoft Edge
![image (2)](https://user-images.githubusercontent.com/30186818/68385120-5fd91200-0159-11ea-9700-a88f8c237490.png)

**Expected result:**
Backlight should be moved with a row. Just like moving resized columns. 
![moving resized columns](https://user-images.githubusercontent.com/30186818/68384323-acbbe900-0157-11ea-9b16-6ffab1d3fc20.gif)

### Demo

v latest `7.2.2` https://jsfiddle.net/aninde/5ef1a08y/
v. `1.14.0 (0.34.0)` https://jsfiddle.net/aninde/82v5bg3x/

### Your environment
* Handsontable version: 1+
* Browser Name and version: 
  - Firefox 70, 62 - bug, 
  - Internet Explorer 11  and Microsoft Edge on Windows 10 - bug
  - Safari 10.13, Chrome 78, Microsoft Edge Dev 80, Brave 0.69, Opera 64 - no bug
* Operating System: Os X Pro Catalina 10.15

**Comment by wojciechczerniak** [comment]
@aninde Was it fixed in `v8.0.0-beta`?

**Comment by aninde** [comment]
This issue is repricable in `v8.0.0-beta` Demo https://jsfiddle.net/qdtug0pv/
![6431-8 0 0beta](https://user-images.githubusercontent.com/30186818/71664112-03a8fd80-2d58-11ea-8089-c864ee41304b.gif)

**Comment by AMBudnik** [comment]
![works](https://user-images.githubusercontent.com/10757813/85120687-e394ca00-b223-11ea-8b87-c97f4f42b576.gif)
Here's what I get for Handsontable `7.4.2` on my Edge / Windows 10
<img width="153" alt="edge_ver" src="https://user-images.githubusercontent.com/10757813/85120714-ee4f5f00-b223-11ea-92bf-d00980626c95.png">
Seem to work fine, @aninde  Can you check it on your device?

**Comment by AMBudnik** [comment]
It also works well for Firefox

Tested in Firefox 8.0.0-beta2-rev16 https://jsfiddle.net/vg8eo7t9/ and 7.4.2  https://jsfiddle.net/vLeyj1zr/ so we can call it closed as **solved**.

**Comment by aninde** [comment]
I was able to replicate this bug on old (non-Chromium)`Edge v44` and on Firefox 77/ Windows 10 with `7.4.2`. and `v.8.0.0-beta2-rev16`. It's solved on Edge Devs v.84 (Chromium-based). 

There are differences in operation on both browsers where the bug occurs.
In Edge shadow after the second shift appears to be moved to the down from its proper place.

![GIF 19 06 2020 13-56-47](https://user-images.githubusercontent.com/30186818/85130769-d7b20380-b235-11ea-9a12-56352763f3ae.gif)

In Firefox, it doesn't display correctly from the top of the table, just below the headers.
![ff](https://user-images.githubusercontent.com/30186818/85130806-e8fb1000-b235-11ea-9f1a-319a34d9a468.gif)

**Comment by aninde** [comment]
This issue can be recreated on Firefox and Edge (non Chromium based) only on Windows. Tested on Windows 10.

**Comment by pnowak** [comment]
This issue works fine on Chrome, Firefox and Safari / macOS Catalina 10.15.6 - https://jsfiddle.net/npxv5cgt/

**Comment by jansiegel** [comment]
`8.0.0` seems to work fine on the latest Firefox on Windows 10.

**Comment by AMBudnik** [comment]
I've tried the v8.0.0 demo using Browserstack on Chrome 85 and Firefox on Windows 10. I wasn't able to replicate the same issue.

**Comment by aninde** [comment]
https://jsfiddle.net/aninde/cgyk845o/ updated demo with v8.0.0. 
It works well on Edge v84 v.85  (Edge Devs) and Firefox 80.0.0  / Windows 10.

As the commenters above wrote, the issue is no longer present in current versions of browsers on Windows, so I'm closing this issue.

**Comment by AMBudnik** [comment]
Thank you for confirmation @aninde 👍
