### ISSUE TITLE
Can't detach from parent 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6432]
### Description
You can't detach from a parent. There is an error in console. A bug is replicable since `7.0.0` version. 
An error occurs in console always - even in `7.0.0` v. http://jsfiddle.net/aninde/ju7yf1tz/, but features look like it works.

It doesn't work at all in the latest version `v. 7.2.2`  http://jsfiddle.net/aninde/83cxv9uL/

### Steps to reproduce
1. Open console.
2. Open `contextMenu`.
3. Click `Detach from parent`

Actual result:
The error always appears in the console.
Depending on version you are able to detach child from parent. 

![Screenshot 2019-11-07 at 16 37 53](https://user-images.githubusercontent.com/30186818/68403275-f965eb00-017c-11ea-9e0c-19c0382b680d.png)

### Demo

`7.2.2 v.`  http://jsfiddle.net/aninde/83cxv9uL/
`7.2.0 v.` http://jsfiddle.net/aninde/joba2qf0/
`7.0.0 v.` http://jsfiddle.net/aninde/ju7yf1tz/

### Your environment
* Handsontable version: since 2.0.0 @AMBudnik thank you 👍 
* Browser Name and version: any
* Operating System: MacOs Pro Catalina 10.15

**Comment by aninde** [comment]
Luckily this bug will be fixed before the new index mapper in `8.0.0-rc1` v. 
http://jsfiddle.net/aninde/76td9m2b/

**Comment by AMBudnik** [comment]
Hey @aninde 

try the scenario with `rowHeaderWidth`. It is hard to tell if that is regression when the detaching failed but surely that's an issue.

Steps
1. Go to http://jsfiddle.net/Ljw2mubx/ (@aninde resources)
2. Detach `Child 1 - 2`
3. row header widths are narrower
4. as we used `bindRowsWithHeaders: true` I would expect to get `Child 1 - 2` as a header of the detached row but I get `Child 5 - 2`

**Comment by aninde** [comment]
After undoing detaching rowHeaders are still narrowed 
<img width="260" alt="Screenshot 2019-11-08 at 10 15 04" src="https://user-images.githubusercontent.com/30186818/68464351-cb31eb00-0210-11ea-80e5-386d5d881674.png">

**Comment by wojciechczerniak** [comment]
@AMBudnik @aninde If an error is fixed then we can close this issue / mark for a release.

The header width problem you're describing is reported in #6006

**Comment by AMBudnik** [comment]
7.4.2 - broken - http://jsfiddle.net/0r5gehtx/
8.0.0-beta1 - working - http://jsfiddle.net/bytLozgw/
8.0.0-beta2-rev18 - still working - http://jsfiddle.net/bytLozgw/1/

I'm adding release: beta1, bet2, 8 and an epic connection

**Comment by AMBudnik** [comment]
@aninde I hope that this bug is gone for good :)

Dear Handsontable Users you should no longer experience the same issue in v 8.0.0.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
