### ISSUE TITLE
Manually merged cells become unmerged after add new row or col

### ISSUE THREAD

**Issue by webwhy** [handsontable/handsontable#6434]
### Description
Manually merged cells become unmerged after add new row or col

### Steps to reproduce

1.merge cells
2.add new rows
3.the merged cells become unmerged

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:7.0
* Browser Name and version: chorme
* Operating System:
none

**Comment by webwhy** [comment]
please help my dear friend

**Comment by AMBudnik** [comment]
Hey @webwhy 

Are you using version 7.2.2?

Here's a demo https://jsfiddle.net/t8mev4ky/

and the scenario
1. Merge `A1: C5`
2. Click `D3` with <kbd>RMB</kbd>
3. Choose `Insert row above`

![Zrzut ekranu 2019-11-8 o 08 49 53](https://user-images.githubusercontent.com/10757813/68459114-c1a28600-0204-11ea-89db-f7794d9e7e14.png)

Result

![Zrzut ekranu 2019-11-8 o 08 50 29](https://user-images.githubusercontent.com/10757813/68459140-d848dd00-0204-11ea-9846-261968abc208.png)
