### ISSUE TITLE
Manual row resize handler throws an error when bottom rows overlay is enabled

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6435]
### Description

Manual row resize handler throws an error when the rows bottom overlay is enabled. It only happens when the data is shorter than the table height.

### Steps to reproduce

1. Go to https://jsfiddle.net/1hrynsk5/;
2. Try to resize the 9th row;
3. As a result, in the console, you'll see `TypeError` exception.

### Demo

https://jsfiddle.net/1hrynsk5/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
I do not need to resize (Tried it on Chrome 78 / Catalina) I get the

![Zrzut ekranu 2019-11-8 o 09 50 35](https://user-images.githubusercontent.com/10757813/68462674-498c8e00-020d-11ea-9b9b-5d7429d77080.png)

Once I hover over the `9th` and `10th` row in the upper area of the table (not the duplicated layer below)

It got broken in the 7.0.1 patch https://jsfiddle.net/0veynwaL/
Here's a non-bugged 7.0.0 version https://jsfiddle.net/p431ka29/

**Comment by wojciechczerniak** [comment]
v8.0.0-beta.2 will not throw an error: https://jsfiddle.net/dau8371m/

We will get a warning that the element is not a part of an overlay if we try to resize row 9 using the main overlay copy, but the functionality still works. I guess it's a debug warning. Will be fixed when we stop rendering those rows twice with  #4454.

@AMBudnik Fixed in v8?

**Comment by AMBudnik** [comment]
@wojciechczerniak you bet it is! IMO it looks even better

7.0.0
![Zrzut ekranu 2020-07-2 o 12 55 04](https://user-images.githubusercontent.com/10757813/86350781-7e00fe80-bc63-11ea-978f-0c73fbf19d76.png)


8.0.0-beta2-rev18
![Zrzut ekranu 2020-07-2 o 12 55 10](https://user-images.githubusercontent.com/10757813/86350795-81948580-bc63-11ea-8c7d-c6a3ee0b8e71.png)


Demo https://jsfiddle.net/bodvxcq8/

**Comment by AMBudnik** [comment]
Issue officially fixed in 8.0.0. Updated demo https://jsfiddle.net/y8xrqutw/
