### ISSUE TITLE
Filtering option is not showing after update from 6.1.0 to 6.2.2

### ISSUE THREAD

**Issue by Prahadeesh92** [handsontable/handsontable#6438]
### Description
Filtering option is not showing after update handsontable version from 6.1.0 to 6.2.2

 Filtering option is shown, when I downgrade to 6.1.0 , Filtering option is not shown for version 6.2.2.
 Is there any solution to fix it.

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome and 78.0.3904.87 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @Prahadeesh92 

can you share some examples? It works fine in our demo https://handsontable.com/docs/7.2.2/demo-filtering.html

**Comment by Prahadeesh92** [comment]
Demo : https://jsfiddle.net/ua2ny10v/1/

**Comment by AMBudnik** [comment]
The version you use in the demo is the old CE version which do not have some of the features like filters but also nested rows, nested headers, dropdown menu, etc.

Here are the resources for version 6.2.2 but for Handsontable PRO 

https://cdn.jsdelivr.net/npm/handsontable-pro@6.2.2/dist/handsontable.full.min.css
https://cdn.jsdelivr.net/npm/handsontable-pro@6.2.2/dist/handsontable.full.min.js

Nevertheless, if you have an active license I recommend checking our newer version.

**Comment by Prahadeesh92** [comment]
Thanks. Its working

**Comment by AMBudnik** [comment]
Great 👍 Thanks for confirmation.
