### ISSUE TITLE
Rows Misalignment when scroll to right 

### ISSUE THREAD

**Issue by Ivan-lv** [handsontable/handsontable#6439]
### Description
When scroll right, rows heights in master table not sync with rows heights in left clone (freezed column) and vice versa.

#4202

### Steps to reproduce
1. open https://jsfiddle.net/Lert_iv/dox3c9rw/4/
2. scroll to right

![image](https://user-images.githubusercontent.com/14289580/68468274-84a4b680-0239-11ea-92d1-e2ae95e18374.png)

### Demo
https://jsfiddle.net/Lert_iv/dox3c9rw/4/

### environment
* Handsontable version: 7.2.2
* Browser Name and version: Google Chrome 78.0.3904.87
* Operating System: Win 10

**Comment by AMBudnik** [comment]
Hey @Ivan-lv 

adding `autoRowSize: true` solves this case https://jsfiddle.net/enmrwvab/

**Comment by Ivan-lv** [comment]
@AMBudnik Thanks for replying, but in my more copmplicated case it's not working. I will try to create example that will be corresponds my case.

**Comment by Ivan-lv** [comment]
@AMBudnik 

I've prepared new example - https://jsfiddle.net/Lert_iv/dox3c9rw/45/

Changes: RU language added, count of columns increased,  number type set, numericFormat used.

![scroll_right](https://user-images.githubusercontent.com/14289580/68572234-b8285080-0486-11ea-952c-269436937200.gif)

**Comment by AMBudnik** [comment]
If we remove your custom function `setRuLanguageToNumbro` it works as expected. Unfortunately, we do not support every feature of Numbro so this might be one of these options. You may think about creating a custom renderer to get the desired look.
