### ISSUE TITLE
Columns not rendering if data length too long

### ISSUE THREAD

**Issue by demikhovr** [handsontable/handsontable#6440]
### Description
Columns not rendering if data length too long. Only hot.render() on afterScrollHorizontally helps.

### Steps to reproduce
1. Open demo https://jsfiddle.net/bajcLpye/
2. Scroll to right
![image](https://user-images.githubusercontent.com/29978554/68532702-e3e5f200-0331-11ea-8d74-f22f87233477.png)

### Demo
https://jsfiddle.net/bajcLpye/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Google Chrome 78.0.3904.87
* Operating System: macOS Mojave 10.14.6

**Comment by AMBudnik** [comment]
Hey @demikhovr 

thank you for sharing the issue but I guess that this is the same case as this one https://github.com/handsontable/handsontable/issues/3448

Am I right?

**Comment by demikhovr** [comment]
Yes. I guess you're right. Thank you.

**Comment by AMBudnik** [comment]
Thank you for confirmation. Please track #3448 for updates
