### ISSUE TITLE
Handsontable render height issue when load data while scrolling

### ISSUE THREAD

**Issue by Prahadeesh92** [handsontable/handsontable#6442]
### Description
Handsontable render height issue when load data while scrolling

The same issue is referenced in issue #5006

### Your environment
* Handsontable version: 6.2.2 & also in 7.2.2
* Browser Name and version: Chrome & 78.0.3904.87
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @Prahadeesh92 

the issue from #5006 was replicable only on Mac devices. Are you able to the same issue on Windows?

Please, share a demo or a video.

**Comment by Prahadeesh92** [comment]
Issue is fixed by using this property 'renderAllRows' : true
