### ISSUE TITLE
[8.0.0-beta.1] Editor doesn't appear in fixed area

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6443]
### Steps to reproduce

1. Go to demo.
2. Try open editor in `fixedRowsBottom` or `fixedRowsTop` or `fixedColumnsLeft` and write something.
3. The editor cannot be seen.

### Demo

https://jsfiddle.net/2b3udpsL/1/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by aninde** [comment]
Demo with bug  `8.0.0-beta.1` v. https://jsfiddle.net/aninde/r2wcLp18/

**Comment by AMBudnik** [comment]
The same issue in IE <3

![what](https://user-images.githubusercontent.com/10757813/68676550-95676c00-055a-11ea-8c7c-de48f6428e2d.gif)

**Comment by aninde** [comment]
The new build of `8.0.0-beta.1` fixed described here issue. The editor is opening, there is ability to copy and paste data from fixed row/column. 
**Demo**
`8.0.0-beta1` v. https://jsfiddle.net/aninde/r2wcLp18/

**Comment by aninde** [comment]
@AMBudnik can you check it on Windows / IE?

**Comment by AMBudnik** [comment]
True, works well on IE 11 on my Windows 10 👍

**Comment by wojciechczerniak** [comment]
Fixed and merged. Not needed for release.
