### ISSUE TITLE
Selection doesn't draw background well on resized and empty cells in IE

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6450]
### Description

Selection in IE 11 doesn't work well. 
* it does not respect new cell side and 
* it does not add background to empty cells.

#### Resizing
1. Resize 1st row
2. Select any column

![image](https://user-images.githubusercontent.com/10757813/68678096-93eb7300-055d-11ea-8dfd-77da45500ca1.png)

It does not work well for resizing rows but works well for columns.

#### Empty cell
1. Remove content front `A2`
2. Select `A` header

![image](https://user-images.githubusercontent.com/10757813/68678191-c301e480-055d-11ea-8aab-18b0a7b8c184.png)

### Demo

[downloadable demo](https://drive.google.com/file/d/13g37jrHEHbtopWHi3FDLxcG0PE96iPWh/view?usp=sharing) (as most JS playground do not support IE)

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: IE 11
* Operating System:  Windows 10

**Comment by aninde** [comment]
As [support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

This issue works as expected for the `8.0.0-beta2-rev15` on Windows 10 and the latest `Edge Dev v85` and real `Edge v44` so we can call it closed as fixed.
<img width="153" alt="edge_ver" src="https://user-images.githubusercontent.com/10757813/85009449-b7fbdc00-b15e-11ea-900b-cc9b631e6333.png">
