### ISSUE TITLE
Expose nestedRows' collapseAll method

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6455]
### Description

The `instance.getPlugin(‘nestedRows’).collapsingUI.collapseAll();` is a well known method that allows `nestedRows` to collapse all parent rows. Now it is hidden under `collapsingUI` object. 

### Demo

Check how it works https://jsfiddle.net/ecxdhw1b/1/ (7.2.2)

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: N/A
* Operating System: N/A

**Comment by wojciechczerniak** [comment]
And should be. `collapsingUI` is an internal implementation.

Please describe what use case is missing and then we can discuss how to implement it as a public API.

**Comment by AMBudnik** [comment]
`collapsingUI` is (and probably should be) internal but we can make an alias. 

Currently, API for `nestedRows` is really poor. Adding `collapseAll()` and [collapseAllChildren()?](https://github.com/handsontable/handsontable/issues/6454) would definitely enrich the plugin.

The use case is pretty obvious: we have many children rows inside parents in the grid and we do not want to show them all upfront. 
If you open this demo https://jsfiddle.net/ue0bLdvj/ (`7.2.2`) you need to scroll to `74` row even if you're not interested in the `Best Rock Performance` album and as a user, you may get confused about how long the list is. 

![GIF](https://user-images.githubusercontent.com/10757813/68752060-fa769c80-0602-11ea-87b9-094e95aae302.gif)

So why they don't just click the button? [People tend to scroll](https://medium.com/@ThomasPitou/navigation-psychology-principles-f74ec32ee874) as a first action, they usually do not study UI. And even if that is not something that can convince you we should add this possibility because of many of our Clients who decide to use `nestedRows`. They ask how to collapse the rows on the initialization as this is a requirement in their project.

**Comment by rodrigolmmota** [comment]
The collapse/expande all nested children in nested rows is a important feature for us to demonstrate balance sheets and income statements. If it becomes a feature soon, I am going to renew my handsontable license. The most important information is shown if all nested rows are collapsed (i.e., the most important information is always in the parent's rows, but the user must be able to see a specific information in details by expanding parent rows.) Hope to hear from you soon, thank you.

**Comment by AMBudnik** [comment]
@rodrigolmmota can you share your use case with me on support@handsontable.com? We can try some approaches.

**Comment by AMBudnik** [comment]
We get more and more requests about collapsing/showing nested rows.

**Comment by jeremy-smith-maco** [comment]
We are also using `collapseAll()` in one of our tables when it is constructed to collapse all of the rows. The parent row contains basic information about an item such as its label and what not and all children rows contain different issues related to the item, each with descriptions and stuff.

If not exposing the `collapseAll()` method, at least some way to specify a config for the nested rows plugin to have them collapsed by default.

The performance of collapseAll is quite bad as well when it comes to larger tables. An example: https://jsfiddle.net/jeremy_smith_maco/4rjo57Lf/

Our table has approximately 7500 parent rows and each one has about 12 children rows and running collapseAll takes about 40 seconds which is pretty bad.

**Comment by AMBudnik** [comment]
Thank you for sharing all the feedback.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share their ideas. 
See you there!
