### ISSUE TITLE
[8.0.0-beta1] A column becomes narrower if we change its order and the column before it was narrower.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6458]
### Description

A column becomes narrower if we change its order and the column before it was narrower. It happens when we remove the content. As it is hard to put it into words I recommend taking the below steps to replicate the issue.

### Steps to reproduce

1. Move `Short` to become a middle column
2. Select header of `Short
3. Use <kbd>Delete</kbd>
4. `Bit Longer` is narrower than expected

### Demo

https://jsfiddle.net/o893p752/ (`8.0.0-beta1`) - broken
https://jsfiddle.net/o893p752/1/ (`7.2.2`) - working

### Your environment
* Handsontable version: 8.0.0-beta1
* Browser Name and version: Chrome 78
* Operating System: Windows 10

**Comment by aninde** [comment]
Fixed, previous ( now deprecated) version of `8.0.0-rc1` from 30.10 https://jsfiddle.net/aninde/ntdf6em9/

**Comment by aninde** [comment]
Maybe this is related https://github.com/handsontable/handsontable/pull/5945#issuecomment-546953820

**Comment by AMBudnik** [comment]
There's also case 2 that works well in `7.2.2`

1. Select columns `Bit longer` and `A very long header`
2. Move them before `Short`
3. Type anything in the first column

![GIF_2](https://user-images.githubusercontent.com/10757813/68766943-1e94a680-0620-11ea-860b-8b0c32e2bc93.gif)

**Result**
`Short` becomes narrower.

It does not look so bad now but it is if we use `dropdown menu` like here https://jsfiddle.net/eLr2jcq1/

![GIF__](https://user-images.githubusercontent.com/10757813/68766973-2fddb300-0620-11ea-86d9-b981844c0174.gif)

the dropdown menu button is covered by the title.

**BUT!**

This time it did not work well in the previous build https://jsfiddle.net/nreycb1s/ (I got the resources from @aninde demo)

**Comment by AMBudnik** [comment]
https://jsfiddle.net/wog68eyn/  new `8.0.0-beta1` Case 2

![issue____](https://user-images.githubusercontent.com/10757813/68771983-4d634a80-0629-11ea-9b22-22cb582b60e9.gif)

Now the header of the first column is cut.

**Comment by aninde** [comment]
@AMBudnik [Case 2](https://github.com/handsontable/handsontable/issues/6458#issuecomment-553425024) works on latest build of `8.0.0-beta1`. You used build from 30.10
Demo: https://jsfiddle.net/aninde/vf0L2qem/
![Screenshot 2019-11-13 at 16 48 35](https://user-images.githubusercontent.com/30186818/68779772-7db0e600-0635-11ea-8703-c29eb8c3d1fd.png)

**Comment by aninde** [comment]
[Case 1](https://github.com/handsontable/handsontable/issues/6458#issue-522177801)  is also fixed by new build `8.0.0-beta1` https://jsfiddle.net/aninde/3xzLod4y/
![Screenshot 2019-11-13 at 19 27 30](https://user-images.githubusercontent.com/30186818/68792471-afcd4280-064b-11ea-82f5-b29002594c5b.png)

**Comment by AMBudnik** [comment]
Confirmed. Both bugs solved.

Case 1
![GIF_](https://user-images.githubusercontent.com/10757813/68834338-d3c56e00-06b5-11ea-999f-bed7b8c7eddc.gif)

Case 2
![case_](https://user-images.githubusercontent.com/10757813/68834337-d3c56e00-06b5-11ea-8b3d-d31339210230.gif)
