### ISSUE TITLE
colHeader is truncated after moving hiddenColumn

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6463]
### Description
After moving hidden column colHeaader is truncated. 
Looks even worse then in stable version. 

`8.0.0-beta.1`
![Screenshot 2019-11-13 at 17 35 52](https://user-images.githubusercontent.com/30186818/68784005-295d3480-063c-11ea-8834-32dd5f4ec76a.png)

`7.2.2`
![Screenshot 2019-11-13 at 17 35 35](https://user-images.githubusercontent.com/30186818/68784024-3548f680-063c-11ea-9705-29883febb757.png)

### Steps to reproduce

1. Open demo `8.0.0-beta.1` https://jsfiddle.net/aninde/bLd84r6a/
2. Move column G where is column E.
3. Notice column header. 

### Demo

not good `7.2.2` forked from [demo hiding columns](https://handsontable.com/docs/7.2.2/demo-hiding-columns.html) https://jsfiddle.net/aninde/bq1adeLg/
worse `8.0.0-beta.1` https://jsfiddle.net/aninde/bLd84r6a/

### Your environment
* Handsontable version: `8.0.0-beta.1` 
* Browser Name and version: Firefox 70
* Operating System: MacOs Pro Catalina 10.15

**Comment by aninde** [comment]
Latest build of `8.0.0beta1` 13.11.19 restored small pixel shift on the right border of table that was in `7+ v.` and doesn't fixed truncating of header after moving. 
![Screenshot 2019-11-13 at 19 06 12](https://user-images.githubusercontent.com/30186818/68791284-41878080-0649-11ea-8b62-7cd338f7881c.png)

![Screenshot 2019-11-13 at 19 10 52](https://user-images.githubusercontent.com/30186818/68791355-6bd93e00-0649-11ea-8f70-ac136ca59949.png)

**Comment by AMBudnik** [comment]
Issue **solved** in 8.0.0.-beta2-rev2 https://jsfiddle.net/dahvwq0x/

Header names as mismatched cause of the #6851 but the columns are not blank.

**Comment by AMBudnik** [comment]
Remains **solved** in 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/w630kmaL/

**Comment by AMBudnik** [comment]
Demo updated to v8.0.0 https://jsfiddle.net/t81bmxo7/. Issue closed as solved.
