### ISSUE TITLE
Copy '&' symbol from another row will produce unexpected '&amp;' string

### ISSUE THREAD

**Issue by vincent-cm** [handsontable/handsontable#6470]
### Steps to reproduce

1. type a long string include & character to any cell, e.g. 'ajsdfajsd .  lakdkf& ha;sdjkfakldjs'
2. copy the cell into another cell
3. the '&' char is replaced by an unencoded ''&amp;''
--

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Latest Windows, macOS, Chrome
* Operating System: Latest Windows, macOS, Chrome

**Comment by AMBudnik** [comment]
Hey @vincent-cm 

this topic is already mentioned here https://github.com/handsontable/handsontable/issues/1535 and is planned for version 7.3.0 (estimated release date 18/11)
