### ISSUE TITLE
Formula + Move Columns are buggy

### ISSUE THREAD

**Issue by msamsel** [handsontable/handsontable#6473]
### Description
Using a manual move column with formulas breaks it.

#### First scenario
1. Open demo page
2. Move column E somewhere
3. Notice that equations remain not transformed in a new position

#### Second scenario
1. Open demo page
2. Move column B (text) behind column E (formula)
3. Notice that a moved column has now applied formulas however when you try to edit cell with a double click you'll see a string underneath

### Demo

https://jsfiddle.net/4jem02gw/13/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 78
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Hey @msamsel 

Here's the same https://github.com/handsontable/handsontable/issues/4668 so I'm closing this one.
