### ISSUE TITLE
Move column + sort are not intuitive

### ISSUE THREAD

**Issue by msamsel** [handsontable/handsontable#6474]
### Description
Sort column should not block manual column move

### Steps to reproduce

1. Open demo
2. Try to move column by clicking into a header name
3. It could be nice to detect when the user just clicks into the header to sort it and when he starts to drag it to move column to a different position. Currently, always sorting is applied, what might be problematic for users to move narrow columns.

### Demo

https://jsfiddle.net/0pmkudah/1/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 78
* Operating System: MacOS

**Comment by AMBudnik** [comment]
>Currently, always sorting is applied, what might be problematic for users to move narrow columns

True. 
@wojciechczerniak what do you think? It is possible?
Could we track if the button release was made on the same pixel?

**Comment by wojciechczerniak** [comment]
Should be. I'm not sure if it's not already reported by @swistach. We spoke about this recently.

**Comment by AMBudnik** [comment]
I did not find anything related in his topics, so we can keep this topic opened.
