### ISSUE TITLE
When we filter the undo stack gets corrupted

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6475]
### Description

Related to https://github.com/handsontable/handsontable/issues/2325
When we filter the undo stack gets corrupted.

### Steps to reproduce

1. Paste anything to cell `A1`
2. Filter this value out in `A` column
3. Paste the same value in `A2`
4. Open the `A` filter and click `OK`
5. Try to undo both pasted values

![corrupt undo stack - filtering](https://user-images.githubusercontent.com/10757813/69057867-d3f59e80-0a12-11ea-9048-1c6ab7e44248.gif)

### Demo

https://jsfiddle.net/bcgL6zre/ (official 7.2.2 demo [Filtering](https://handsontable.com/docs/7.2.2/demo-filtering.html) copy)

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 78
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
It doesn't change in `8.0.0-beta1`

**Comment by monu0751** [comment]
Is there any update on this bug... as it is also not working in 8.0.0-beta.1 version

**Comment by AMBudnik** [comment]
The undo-redo might need a separate epic. However, now we focus on stable 8.0.0. so it is hard to define when we'll take the action to solve the undo-redo issues.

**Comment by AMBudnik** [comment]
Works the same in 8.0.0-beta2-rev12 https://jsfiddle.net/AMBudnik/zkLe3d6t/

**Comment by AMBudnik** [comment]
Here's the demo updated to v 8.0.0 https://jsfiddle.net/L04uhq9g/
This issue is still replicable.
However, it works well when we operate on a different column instead of a different row (step no 3)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
