### ISSUE TITLE
customBorders plugin is missing in the definition file

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6477]
### Description

The `customBorders` are missing in the `PluginsCollection` definition in the TypeSctipt file. 
Reference: https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L2347
This is used to pass options for `getPlugin` method.
https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L61

It is also not mentioned in the `Plugins` interface
https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L2308

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome n/a
* Operating System: n/a

**Comment by aninde** [comment]
`customBorders` are present in `PluginsCollection` in `handsontable.d.ts` of v8. (`pre-8.0.0-rev1` and earlier `8-beta2`)
https://github.com/handsontable/handsontable/blob/5051859a956f409efcfdf435deb5db3ad33922f2/handsontable.d.ts#L2301

**Comment by AMBudnik** [comment]
Solved in v 8.0.0
