### ISSUE TITLE
window.frameElement throws errors in MSEdge, IE and Safari

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6478]
### Description
After changes with adding `uiContainer`, we had to add traverse through parent frames.
Unfortunately, a simple loop on `frame.frameElement` doesn't work stable at the sandboxed iframes in MSEdge, IE and Safari. Moreover, doesn't allow to create a HOT instance on MSEdge/IE, because the user gets `Access is denied` error.
On Safari, we get CORS error message.

MSEdge issue: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19082980/

### Steps to reproduce
1. Run https://handsontable.com/docs/demo-scrolling.html in jsfiddle on MSEdge/IE/Safari with open dev tools.

### Your environment
* Handsontable version: 7.3.0-rc / 8.0.0-beta.1
* Browser Name and version: MSEdge, IE, Safari
* Operating System: macOS, Windows

**Comment by aninde** [comment]
New version `7.3.0` https://jsfiddle.net/du8mnefs/ pasting do not work on **Safari** when 

```
copyPaste: {uiContainer: document.body},
editor: false
```

**Comment by aninde** [comment]
The new version of `7.3.0` fixed described here issue https://jsfiddle.net/0cjLp1ka/. 
Tested locally on `Windows 10`/ `IE` (changed in js, iframe code `append` on `appendChild`), `Microsoft Edge`, `Microsoft Dev Edge`. 
`Mac Os Pro Catalina 10.15` / `Safari 10.13`, `Firefox 70`, `Chrome 78`.

**Comment by aninde** [comment]
A new build of `7.3.0 v`  still fixed described here bug https://jsfiddle.net/e2khovft/ @budnix thank you very much for the help with the demo. Tested on Safari 13 / Mac OS Catalina, IE and Edge / Windows 10 / BrowserStack.

**Comment by aninde** [comment]
I tested it locally with React wrapper. Handsontable was injected in  iframe with different URL adress. `contextMenu` was injected to new feature `uiContainer` and worked on Safari / Mac Os but it was still with https://github.com/handsontable/handsontable/issues/6505

**Comment by wojciechczerniak** [comment]
Looks like this was released in v7.3.0
