### ISSUE TITLE
We're missing the last row header if we get a merged cell in the last row of the dataset after filtering.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6481]
### Description

We're missing the last row header if we get a merged cell in the last row of the dataset after filtering.

### Steps to reproduce

1. Open the filter for column `B` to filter out everything more than `B1` and `(Blank cells)`
2. Confirm it with <kbd>OK</kbd> button

![GIF](https://user-images.githubusercontent.com/10757813/69135261-22f60f00-0ab9-11ea-91cf-1e62f819ecc2.gif)

**Result**
We're missing header for the `4th` row. 
We are able to get it back only after editing a cell in the last row. Additionally, there's an empty row.

Works the same on FF 70
![image](https://user-images.githubusercontent.com/10757813/69135721-db23b780-0ab9-11ea-877c-9be7c468f79e.png)

### Demo

https://jsfiddle.net/kvpd8qea/8/ 

### Your environment
* Handsontable version: 7.2.2
_It doesn't seem to work well in any version._(also in `8.0.0-beta1`, and `7.3.0`)
* Browser Name and version: Chrome 78
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
It seems to be related to the same bug so I allowed myself to add Case 2.

### Case 2
1. Go to https://jsfiddle.net/gav509hq/2/ (`7.3.0`)
2. Open dropdown menu for `C` column
3. Filters out `C1`

**Result**
The row is gone but `C2` and `D2` got erased.

![GIF](https://user-images.githubusercontent.com/10757813/74237880-cfb8e480-4cd4-11ea-84f5-39faa4f177a1.gif)

`getData()` returns
![image](https://user-images.githubusercontent.com/10757813/74237967-03940a00-4cd5-11ea-9f0e-6e304dd76af0.png)

If we bring `C1` back everything's OK.

**Comment by AMBudnik** [comment]
### Updates for v 8.0.0

* The main issue - https://jsfiddle.net/t2msh8Lu/ seems to be **solved**

![Zrzut ekranu 2020-08-11 o 14 37 43](https://user-images.githubusercontent.com/10757813/89898006-3feee700-dbe0-11ea-92ca-8a38c1ea3b05.png)

* Case 2 - https://jsfiddle.net/x12L3n76/ remains the same (**broken**)
![Zrzut ekranu 2020-08-11 o 14 41 13](https://user-images.githubusercontent.com/10757813/89898315-c7d4f100-dbe0-11ea-85cb-4fd3da2c07fa.png)



Data visibility issue has been raised here https://github.com/handsontable/handsontable/issues/7183 and https://github.com/handsontable/handsontable/issues/6871 so we should not judge that behavior while considering the issue as solved or not.

**Comment by AMBudnik** [comment]
Case 2 remains the same for v 8.1.0 https://jsfiddle.net/y16x5b4p/1/

**Comment by swistach** [comment]
The second case is described separately: https://github.com/handsontable/handsontable/issues/6482
