### ISSUE TITLE
Document keydown (or focus) events are propagated to highlighted cell even if its editor is not opened

### ISSUE THREAD

**Issue by pinuchfab** [handsontable/handsontable#6483]
### Description
Document keydown event are propagated to a highlighted cell even if its text editor is not opened.

### Steps to reproduce

1- open a div with an input on top of a grid that has a cell highlighted (but its editor not opened)
2- set focus to top div input, have a keydown evt handler for the input stopping immediate propagation
3- press backspace
4- the highlighted cell behind the div is reset and should not have been reset

### Demo

[VideoKeydownProblem.zip](https://github.com/handsontable/handsontable/files/3863325/VideoKeydownProblem.zip)

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: Version 78.0.3904.87 (Official Build) (64-bit)
* Browser Name and version: Chrome
* Operating System: Windows10

**Comment by AMBudnik** [comment]
Hey @pinuchfab 

As you did not create a demo I've made one but here https://jsfiddle.net/AMBudnik/j6xh8wr0/ it works well. 

Can you share any details of your implementation?

**Comment by pinuchfab** [comment]
Hello, I did provide a video showing the issue, but no demo is term of code.
Looking at your demo, two observations:
-> you are using a more recent version of HoT, I m using 6.2.2.
-> Also, the problem doesn't occur if the focus is not set automatically to the input. I only see the problem when I force the input to be focused (check step 2). I have changed your example to force a focus, the problem doesn't occur in that demo. 
input.focus()

I have fixed the problem by adding a onBeforeKeydown and essentially cancelling the event if something is opened based on this article
https://github.com/handsontable/handsontable/issues/3477

I ll carry on investigating why HoT capture the document event and assume it is targeted for a cell even so the event target is actually the input.

Regards,
Fabien

**Comment by AMBudnik** [comment]
Thank you for the prompt reply, Fabien.

> the problem doesn't occur in that demo.

That is why it would be hard to replicate. Without replication, I can only guess how to help.

> I ll carry on investigating why HoT capture the document event and assume it is targeted for a cell even so the event target is actually the input.

Please update me with the result or possibly with a demo.

ps. have you tried to update to 7.2.2?

**Comment by AMBudnik** [comment]
Hey @pinuchfab 

do you have any updates here? Did you try 7.2.2 or our beta?
