### ISSUE TITLE
Method selectCells is too slow.

### ISSUE THREAD

**Issue by wj42ftns** [handsontable/handsontable#6487]
Method: selectCells https://handsontable.com/docs/7.2.2/Core.html#selectCells is too slow.
For example, selections of 60 cells took for me more than 3 seconds: http://jsfiddle.net/wj42ftns/8bspqd6r/28/

Handsontable version: 7.2.2
Browser Name and version: Chrome Version 77.0.3865.120 (Official Build) (64-bit)
OS: Ubuntu 18.04.3 LTS x86_64 
Host: Inspiron 15 7000 Gaming 
Kernel: 4.15.0-70-generic 
CPU: Intel i7-7700HQ (8) @ 3.800GHz 
GPU: Intel Integrated Graphics 
GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
Memory: 10705MiB / 15906MiB

**Comment by AMBudnik** [comment]
Hey @wj42ftns 

that's not a lightning-fast load. That's true, but not all the [performance tips](https://handsontable.com/docs/7.2.2/tutorial-performance-tips.html) were used to create this example.

If you set a fixed height for the instance container you can get less than 2s http://jsfiddle.net/AMBudnik/quz12e7x/

![Zrzut ekranu 2019-11-20 o 10 53 51](https://user-images.githubusercontent.com/10757813/69228552-0e327d80-0b84-11ea-8801-1facc2a1869e.png)

and if you add http://jsfiddle.net/AMBudnik/quz12e7x/ 
```js
  rowHeights: 22,
  autoRowSize: true,
  colWidths: 100,
```

it's 1.1 - 1.3 s

![Zrzut ekranu 2019-11-20 o 10 55 10](https://user-images.githubusercontent.com/10757813/69228723-5fdb0800-0b84-11ea-9c9c-623bbf00f1ca.png)

Then adding

```js
viewportColumnRenderingOffset: 0,
viewportRowRenderingOffset: 0,
```

will finally give us less than a second http://jsfiddle.net/AMBudnik/ao60kc5h/

![Zrzut ekranu 2019-11-20 o 10 58 11](https://user-images.githubusercontent.com/10757813/69228926-c3653580-0b84-11ea-972d-66c231631f86.png)


that is actually a very cool demo to track performance.
