### ISSUE TITLE
[7.3.0] Pasting HTML instead of content of cells.

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6489]
### Description
Pasting content with added HTML code result pasting all plain HTML.

### Steps to reproduce

1. Open Excel, fill cell with `1              2`. 
2. Open demo https://jsfiddle.net/aninde/t96zwc0f/ paste content. 

### Result
**Case 1**
Firefox 70, Safari 13, Chrome 78, Opera 64
![Screenshot 2019-11-20 at 18 04 46](https://user-images.githubusercontent.com/30186818/69260484-448dee00-0bc0-11ea-96c9-a37f9fd67c82.png)

**Case 2**
Pasting multilines from `Excel 16.31` to `Safari 13.0.3`
<img width="159" alt="Screenshot 2019-11-20 at 16 04 43" src="https://user-images.githubusercontent.com/30186818/69250293-b3168000-0baf-11ea-86b7-43cb574446dc.png">
![Screenshot 2019-11-20 at 16 04 50](https://user-images.githubusercontent.com/30186818/69250289-b14cbc80-0baf-11ea-93a0-972cc0fe1176.png)

**Case 3**
In `Numbers`/`MacOs` fill one cell with a simple one character, fill the next cell with multi-line content.
![69253514-0b03b580-0bb5-11ea-9339-c48bdc089c4a](https://user-images.githubusercontent.com/30186818/69260347-01cc1600-0bc0-11ea-9546-0320a1a3a76d.png)
![69254123-01c71880-0bb6-11ea-8e0a-4d02f950b0eb](https://user-images.githubusercontent.com/30186818/69260342-00025280-0bc0-11ea-838f-880ef1b5ccbc.png)
https://jsfiddle.net/y0ofpcab/ - 7.3.0 broken
https://jsfiddle.net/aninde/qtcg6nkm/ - 7.2.2 fixed

### Demo

https://jsfiddle.net/aninde/t96zwc0f/ `7.3.0 v.`

### Your environment
* Handsontable version: `7.3.0`, works on previous version
* Browser Name and version: Safari 13.0.03, Excel 16.31, even worse on Numbers 6.2.1 - also on Chrome
* Operating System: MacOsCatalina 10.15

**Comment by aninde** [comment]
New version 7.3.0 https://jsfiddle.net/du8mnefs/ **pasting do not work on Safari** when

```
copyPaste: {uiContainer: document.body},
editor: false
```

**Comment by swistach** [comment]
> New version 7.3.0 https://jsfiddle.net/du8mnefs/ **pasting do not work on Safari** when
> 
> ```
> copyPaste: {uiContainer: document.body},
> editor: false
> ```

This is the other problem and should be added separately.
Initially, I notice that calling `focus()` method doesn't work on elements which are out of the active frame. It needs deeper investigation.

**Comment by aninde** [comment]
This issue is fixed in latest build of `7.3.0` https://jsfiddle.net/bfgk1a7n/. 
That was tested with `iframe` and `uiContainer` on` 
MacOs Pro Catalina 10.15`/`FF`, `Chrome`, `Dev Edge`, `Brave` 
 `Windows 10`/  `IE`, `Dev Edge`, `Real Edge`, `Google spreadsheet`, 
`Ubuntu 18.04.4 LTS`/, `Firefox Quantum 68.0.1,` `Libra Office 6.0.7.3`and `Gnumeric`.
Working on `Safari` is still issue due to https://github.com/handsontable/handsontable/issues/6492.

**Comment by aninde** [comment]
Still works on Chrome 78, FF 71, Safari ( but only without defined `editor:false` due to https://github.com/handsontable/handsontable/issues/6492) Microsoft Dev Edge and on IE and Edge/Windows 10. 

![pasting-excel-chrome](https://user-images.githubusercontent.com/30186818/70522042-a6e36a00-1b40-11ea-887e-b39cc1b4aeb1.gif)


https://jsfiddle.net/3z5fct4g/
https://jsfiddle.net/aninde/qtx0Lk4d/

**Comment by aninde** [comment]
Still works with `7.4.2`. Closing as fixed by `7.4.+`
