### ISSUE TITLE
Customize clicking header to sort behavior 

### ISSUE THREAD

**Issue by jacktang** [handsontable/handsontable#6496]
The default behavior of clicking header to sort is 
* click once, the column data is sorted in `asc` order,
* click twice, it is sorted in `desc` order,
* click third time, it backs to `normal` order.

How can I change the behavior to   `desc sort` -> `asc sort` -> `normal` sequence?

**Comment by AMBudnik** [comment]
Hi @jacktang 

the behavior is programmed to work one way and it is not customizable. You can, however, apply your own logic using [`ColumnSorting` plugin](https://handsontable.com/docs/7.2.2/ColumnSorting.html#sort).

> // sort ascending first visual column
> hot.getPlugin('columnSorting').sort({ column: 0, sortOrder: 'asc' });
