### ISSUE TITLE
[Performance] hot.updateSettings triggered refreshBorder method many times might cause low performance

### ISSUE THREAD

**Issue by loverobby** [handsontable/handsontable#6498]
### Description

If there are data and mergeCells changed, when invoking the hot.updateSettings to render the grid, it will trigger refreshBorder many time cause slow performance.

### Steps to reproduce

1. Change the settings of data, mergeCells and others.
2. After data and mergeCells change, call hot.updateSettings to render the grid
3. You will see that the _refreshBorder will be invoked four times to handle the render logic, but it only need once at the end.

The expectation is that why handsontable has no any API for settings setup but no renders, we can make the render when we call render method.

### Demo

https://jsfiddle.net/fy0Lu9z2/3/
Please click the grid cellls and see the scenario.

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome/78.0.3904.97
* Operating System: MacOS 10.14.5 (Mojave)

**Comment by AMBudnik** [comment]
Hi @loverobby 

thank you for your input. This behavior may change in the nearest future.

We're rebuilding the process of borders redrawing https://github.com/handsontable/handsontable/issues/6467 as we'd like to publish it in the stable `8.0.0` https://github.com/handsontable/handsontable/issues/6465
If you have any ideas on how can we improve the refactor please feel free to leave a comment in this post https://github.com/handsontable/handsontable/issues/6467

**Comment by AMBudnik** [comment]
While batching the operations done on the `afterOnCellMouseUp` event we wet 90% fewer calls to the renderer. The demo itself also loads significantly faster. 

Demo https://jsfiddle.net/handsoncode/p1t7Lmq4/

I think that we can close this issue as solved.
