### ISSUE TITLE
Changing the source onBeforeChange

### ISSUE THREAD

**Issue by adjiandov** [handsontable/handsontable#6499]
### Description
Hello, I have a question regarding the beforeChange hook. I have a problem where based on a change I have custom logic which can update several cells based on this change. Previously I have gathered the changes and issued a 
`hot.setDataAtCell(changesArray...., customSourceName);
return false;`

However this triggered new change event, which in my opinion is unnecessary. I realized that I can just manipulate the incoming changes attribute to achieve the same outcome without triggering new change event. However after the changes are made the 'afterChange' hook receives the changes with source 'edit'. Is there any way I can "silently" change the source as well in the beforeChange hook?

Thank you

HT version: 6.2.2

**Comment by mythbobo** [comment]
yes, I have the same problem,  cells render mode, i change cell add html, it will change back

**Comment by AMBudnik** [comment]
Hi @adjiandov  @mythbobo 

If you want to stop the infinite loop where `setDataAtCell` triggers the change event you should pass any (custom) string parameter to the `customSourceName` and them use them in the IF statement if the change hook.

**Comment by adjiandov** [comment]
Hello @AMBudnik,
that is my current implementation, but that also means a second (the custom one) change event. I wanted to avoid that, I would like to manipulate the changes object and attach a custom source, so that when it comes to the afterChange hook, it will "know" that this changes were manipulated etc.

**Comment by AMBudnik** [comment]
Would it be possible to get a demo with the latest progress? I think that it would be much easier to share some thoughts via code samples.

**Comment by AMBudnik** [comment]
As there are no updates and demos I need to close it.
