### ISSUE TITLE
How to create a checkbox column in table

### ISSUE THREAD

**Issue by pvagithub** [handsontable/handsontable#650]
Hi all,
I want create a checkbox first column in table. the header column also checkbox.
If user click checkbox on header, all rows in column will be checked.
As me know, the handsontable not support it. So, i try to reasearch on internet but it's not working.
Please tell me demo or example about that you know.

Thanks any help.
An.

**Comment by Abdul-anas** [comment]
Hi How to add an attribute on handsontable checkbox

**Comment by AMBudnik** [comment]
Hey @Abdul-anas 

can you share a little bit more information about this requirement? What attribute do you need, where you'd like to use it?

As this topic is from 2013 I recommend creating a new ticket or sending me an email at support@handsontable.com
