### ISSUE TITLE
When downloadfile exports excel, 2-1 becomes February 1, 19-1-1 becomes January 1, 2019

### ISSUE THREAD

**Issue by 18722147927** [handsontable/handsontable#6503]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
We do not export excel files. CSV is a pure text file and this probably depends on Excel settings that is responsible for parsing plain data.

Please provide an example and reproductions steps so we can test and confirm the issue.
