### ISSUE TITLE
Cursor in the dropdown menu of the filter component sometimes stuck and don't want to move

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6506]
### Description

The input elements are not responsible for key navigation in some situations.

### Steps to reproduce

1. Go to https://jsfiddle.net/vwoa4u82/;
2. Try to filter the first column by condition "Begins with";
3. Enter "lo" in the input below;
4. Move the cursor to the beginning of the word then try to the end of the word;
5. As a result, the right arrow is somehow blocked;

### Demo

https://jsfiddle.net/vwoa4u82/

### Your environment
* Handsontable version: 7.3.0 & 8.0.0-beta.1
* Browser Name and version: Chrome
* Operating System: macOs

**Comment by budnix** [comment]
My first thought was that this issue is related to https://github.com/handsontable/handsontable/pull/6504. However, I almost finished my PR and this bug still occurs.

**Comment by aninde** [comment]
This will be fixed by latesrt build of `7.3.0 v. (6.12) 

https://jsfiddle.net/aninde/s5n39drw/
![6506-chrome](https://user-images.githubusercontent.com/30186818/70518755-30903900-1b3b-11ea-9557-f3dbd66289f7.gif)

**Comment by AMBudnik** [comment]
This issue should be already closed as it was fixed in [`7.3.0`](https://jsfiddle.net/zpe8y3fb/) and it still works well even with the [latest revision of 8.0.0-beta2](https://jsfiddle.net/964a5Ljc/)
