### ISSUE TITLE
Formula parser is crashing when referencing cells with reference

### ISSUE THREAD

**Issue by rbarato** [handsontable/handsontable#6509]
### Description
When using formulas with cell references, Handsontable crashes if I use cascading references (reference of a reference).

Each reference to another cell adds up 100-200ms to the load time to a point where it becomes unusable. 

This is a common scenario in our business.

### Steps to reproduce
1. Add a number in cell D2
2. In cell D3 input the formula =$D$2+D2+D2
3. In cell D4 input the formula =$D$2+D3+D3
4. Repeat changing line until cell D16 (=$D$2+D15+D15)

You can see performance dropping until it crashes. In the Demo there are 2 data vars (data and data2).

Data is smaller and takes 32008ms to load. Data2 crashes the table (actually I left it processing and it took up to 18 minutos to render the sheet).

I've added a button to toggle the formulas after the table is initially loaded so the performance bottleneck can be compared with the sheet load time.

### Demo

https://jsfiddle.net/rbarato/a6dkzrqo/9/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 78
* Operating System: MacOS Mojave

**Comment by AMBudnik** [comment]
Hey @rbarato 

the issue is already mentioned here https://github.com/handsontable/handsontable/issues/4357
However, at the beginning of 2020, we will introduce a new formula engine that won't have the issues of the formula-parser.

**Comment by rbarato** [comment]
Thanks @AMBudnik, looking forward to it.
