### ISSUE TITLE
addTree

### ISSUE THREAD

**Issue by navindian** [handsontable/handsontable#651]
Hi 

I wish to have the functionality that is available JQGrid addTree in handsontable. Can anybody comment now on how should the approach be. 

![jqgrid-addtree](https://f.cloud.github.com/assets/1062603/496181/5445bb0c-bbdb-11e2-9ec2-c8a4fccf102e.png)

Current Scenarios:
1. onClick of Cash1, Cash2 toggles.
2. on Click of Cash2, Cash3 toggles.

I have implemented the same in the following url. But wish to have complete approach with all future scenarios. 

http://jsfiddle.net/navindian/hU6Kz/1996/embedded/result/

I have seen other handsontable, but wish to have the exact scenario as in jqgrid addtree.

Please Comment.

**Comment by AMBudnik** [comment]
Please track changes in https://github.com/handsontable/handsontable/issues/1924
