### ISSUE TITLE
Sometimes can't drag scroll bar

### ISSUE THREAD

**Issue by EmilioCristalli** [handsontable/handsontable#6510]
### Description
When the scroll bar is at the top, I can't click and drag it to scroll down.
If I scroll down a little using two fingers on the trackpad, and then try to click and drag the bar again it works (it's like there's something at the top of the table that overlaps with the scroll bar and doesn't let me click it).

From what I was able to test, it only happens when the container is wider than the table (ie the scrollbar is outside of the table), and when macOS is configured to only show scroll bars "Automatically based on mouse or trackpad"

![Screen-Recording-2019-11-29-at-3 29 26-PM](https://user-images.githubusercontent.com/972779/69885706-32e1d000-12bd-11ea-8852-9bbbda61d9ae.gif)

### Steps to reproduce
1. Create table inside container that is wider than the table
2. Add enough rows to have a vertical scroll bar
3. Try to click and drag the scroll bar from the top of the table

### Demo
https://jsfiddle.net/rzxdewyt/1/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 78.0.3904.108
* Operating System: macOS Mojave (10.14.16)

**Comment by AMBudnik** [comment]
@pnowak please test this on your Mac.

As I can see there are 3 ways to manage scrolls on Mac
> Scroll bars appear in a window when there’s content that doesn’t fit into the window’s current size.
> * Automatically based on mouse or trackpad: Scroll bars are shown depending on the mouse or trackpad you’re using.If your device allows gestures, scroll bars are hidden until you start scrolling. Otherwise, they’re visible.
> 
> * When scrolling: Hide scroll bars until you start scrolling.
> * Always: Scroll bars are always shown.

src https://support.apple.com/en-ca/guide/mac-help/mchlp1225/mac

I know that we had a similar conversation in the team before. However it was associated with the fact that we can't force someone to change the system settings, nor we aren't able to show scroll even when it is not defined to show it.

I think that this situation might be what they planned for the `Automatically` visible scrollbars. Nevertheless, as a Windows user, I might be wrong.

**Comment by AMBudnik** [comment]
We've tried some approaches and it looks like this is intended behavior and we won't be able to change it. 

Nevertheless, thank you for posting this case. I believe that some of our users may also look for this subject.
