### ISSUE TITLE
AutoFill does't work

### ISSUE THREAD

**Issue by chao** [handsontable/handsontable#6511]
### Description

In the demo [Auto fill in vertical direction only with creating new rows](https://handsontable.com/docs/7.2.2/demo-auto-fill.html) when you double click the right corner of a cell, it should auto fill the cells in the same column.

But I only works when you double click cells from left to right columns by sequence. For example, when you double click B4 right corner it will auto fill B5,B6 with value 30, then you double click right corner of C4 it will auto fill C5,C6 with value 15. But if you double click E4 cell right corner, nothing happens.

### Steps to reproduce
Auto fill works in the way.

1. double click the right corner of Cell B4;
1. double click the right corner of Cell C4;
1. double click the right corner of Cell D4;
1. double click the right corner of Cell E4;

Auto fill broken in this way.
1. double click the right corner of Cell E4;
1. double click the right corner of Cell D4;
1. double click the right corner of Cell C4;
1. double click the right corner of Cell B4;

### Demo
This bug can be reproduced on the demo of the document page (https://handsontable.com/docs/7.2.2/demo-auto-fill.html)

![autofill2](https://user-images.githubusercontent.com/55872/69935595-551f5c00-1510-11ea-9330-601760448b35.gif)

**Comment by AMBudnik** [comment]
Do you remember this topic @wojciechczerniak? We already discussed it and as far as I remember we agreed to fill the data when the column on the left is already filled - the Left-to-right rule.

**Comment by wojciechczerniak** [comment]
Yup. Otherwise, it would be difficult to find where fill should end. Spreadsheets have an algorithm that is looking for closest cells that are not `blank`. We're not ready to cover all the edge cases here and went with a simplified (see `selectAdjacent` method) approach. 

It should be possible to use `onCellCornerDblClick` to set selection and trigger the fill action. Or extend the `selectAdjacent` plugin method.

**Comment by AMBudnik** [comment]
> It should be possible to use onCellCornerDblClick to set selection and trigger the fill action.

True. Thank you for the input.

@chao as far as we'd like to cover all the cases, as @wojciechczerniak said, for now, you should stick to `onCellCornerDblClick` if you'd like to fill the data this way

> double click the right corner of Cell E4;
> double click the right corner of Cell D4;
> double click the right corner of Cell C4;
> double click the right corner of Cell B4;
