### ISSUE TITLE
PreventOverflow feature doesn't work if multiColumnSorting plugin is enabled

### ISSUE THREAD

**Issue by mrdivyansh** [handsontable/handsontable#6514]
### Description
`PreventOverflow` doesn't work if `multiColumnSorting`/`columnSorting` plugin is enabled.

### Steps to reproduce

1. Set `PreventOverflow: 'horizontal'`
2. Set `multiColumnSorting: true` or `columnSorting: true`
3. Scroll the table vertically.

### Demo
https://jsfiddle.net/7aqz4spk/1/

![Gif Demo](https://user-images.githubusercontent.com/8512339/69955151-00391100-1523-11ea-9e2a-90c56eed9bb1.gif)

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome v78.0.3904.97
* Operating System: MacOS 10.15.1

**Comment by AMBudnik** [comment]
Hey @mrdivyansh 

seem to work fine with our beta https://jsfiddle.net/d3ok1avj/

We are still testing it but it is already on our develop branch if you'd like to try it.

**Comment by AMBudnik** [comment]
I guess that we can close a topic as it seems to work on our develop but...

@aninde maybe we have a topic that was created for/cause of `8.0.0` and sound familiar to this one? There are[ 5 topics](https://github.com/handsontable/handsontable/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+PreventOverflow) related to `preventOverflow` but none of them is marked as a `8.0.0` issue. The `8.0.0` is purely magical but it is unusual if something just happen to be fixed without anyone's interaction.

**Comment by wojciechczerniak** [comment]
The bug report is about 7.2.2 version. If this is fixed on develop we should add it to release notes.

Or it may be related to `observeChanges` which is now not enabled by sorting plugins. Maybe @wszymanski have an idea which change could affect `preventOverflow` rendering?

**Comment by wszymanski** [comment]
I have no idea how, but it fix was already done within the `8.0.0-beta.1`. Probably it's related to the `ObserveChanges` plugin.

**Comment by AMBudnik** [comment]
Remains solved in 8.0.0-beta2-rev6 https://jsfiddle.net/1gyzdtq3/

**Comment by aninde** [comment]
Remains solved with `pre-8.0.0` https://jsfiddle.net/aninde/8zrv7y1k/.

**Comment by AMBudnik** [comment]
Hi @mrdivyansh 

I’m glad to announce that Handsontable v8.0.0 that solves this issue is live!   

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. I hope that the amount of work that we put on the v8 will help you to improve your project.
