### ISSUE TITLE
Improve tests based on mouse events

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6519]
### Description

This issue is about improving all tests that depend on mouse events. Doing some issue I've found that a lot of currently written tests test a behavior based on event simulation that triggers only a single event (uncompleted flow) or completely flow (`mousedown` -> `mouseup` -> `click`) but triggered one by one - too laboratory. 

The whole chain of the mouse events should be called for each test. Moreover, after `mousedown` event there should be placed some sort of delay that emulates time the button was release (+ device lag?).

I think this leads to a situation where a feature is not tested completely. 

Some examples:
 * https://github.com/handsontable/handsontable/blob/master/src/plugins/dropdownMenu/test/dropdownMenu.e2e.js#L309
 * https://github.com/handsontable/handsontable/blob/master/src/plugins/comments/test/comments.e2e.js#L350
 * https://github.com/handsontable/handsontable/blob/master/src/plugins/contextMenu/test/contextMenu.e2e.js#L214

### Your environment
* Handsontable version: -
* Browser Name and version: -
* Operating System: -

**Comment by swistach** [comment]
Maybe cypress's approach might be an inspiration: https://github.com/cypress-io/cypress/blob/master/packages/driver/src/cy/mouse.js#L403

**Comment by swistach** [comment]
This issue is closed temporarily. We will reopen it for development as it became a part of the test environment improvements task reported at #7581
