### ISSUE TITLE
wrong calculation in contextMenu

### ISSUE THREAD

**Issue by baoloc1993** [handsontable/handsontable#6523]
https://github.com/handsontable/handsontable/blob/b9e14ee9c45dc8f42e23414c93e82e6b805f6879/src/plugins/contextMenu/menu.js#L403

Cannot display the contextMenu due to this wrong calculation. It should be 
`      var left = this.offset.left + cursor.left;`

**Comment by AMBudnik** [comment]
Connected to https://github.com/handsontable/handsontable/issues/6524

**Comment by AMBudnik** [comment]
As there are no updates and we're struggling to understand a need of this report I need to close it.
