### ISSUE TITLE
Context menu display wrong position

### ISSUE THREAD

**Issue by baoloc1993** [handsontable/handsontable#6524]
https://github.com/handsontable/handsontable/blob/b9e14ee9c45dc8f42e23414c93e82e6b805f6879/src/plugins/contextMenu/menu.js#L372

Should be
`var top = this.offset.below + cursor.top - this.container.offsetTop;`

**Comment by wojciechczerniak** [comment]
Why? What use case would it solve? Do you have multiple scrollable containers? Do you have iframe? How many nested iframes?

Please attach a demo

**Comment by baoloc1993** [comment]
I dont use iframe. The container is scrollable

**Comment by AMBudnik** [comment]
Hey @baoloc1993 

It would be great if you could share a demo or recording and send this fix + https://github.com/handsontable/handsontable/issues/6523 via pull request? 
This way we'd be able to test it and compare our thoughts.

**Comment by AMBudnik** [comment]
As there are no updates and we're struggling to understand a need of this report I need to close it.

**Comment by aimfeld** [comment]
I have a similar issue which might be related to this one, my context menu always opens about 100px below the cursor.

**Comment by AMBudnik** [comment]
Hi @aimfeld 

Could you send me a demo/reproduction of the issue at support@handsontable.com?

**Comment by aimfeld** [comment]
@AMBudnik We'll try to isolate the problem and provide a jsfiddle.

**Comment by aimfeld** [comment]
We have worked around the problem by correcting for margin-top of our main container:

```
.htContextMenu {
  margin-top: -55px;
} 
```

Unfortunately, we haven't been able to reproduce this with jsfiddle - it works fine there, even with margin. We are using bootstrap 5.0.0 for our layout btw.

**Comment by AMBudnik** [comment]
Thank you for the update @aimfeld 
I think that the CSS settings of sibling elements or a parent DIV may change how the context menu is shown.
