### ISSUE TITLE
Remove helpers that cover IE8 or not needed anymore

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6525]
### Description

I have found that some helpers are not needed anymore. The dist files size can be reduced by deleting them. Here helpers which can be removed:

1. https://github.com/handsontable/handsontable/blob/master/src/helpers/dom/event.js `stopPropagation`, `pageX`, `pageY` that props and methods can be called directly on Event objects (MDN says that support is good enough);
2. https://github.com/handsontable/handsontable/blob/master/src/helpers/dom/element.js `polymerWrap` and `polymerUnwrap` (helpers used for old Polymer version). For `setCaretPosition` `else` expression for IE can be removed;

### Your environment
* Handsontable version: -
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment]
https://github.com/handsontable/handsontable/issues/7026

**Comment by AMBudnik** [comment]
We can call this to-do list as done and implemented in v 8.0.0
