### ISSUE TITLE
Row header width varies when removing a row.

### ISSUE THREAD

**Issue by samueljTRQ** [handsontable/handsontable#6527]
### Description
       I am using stretchH option and I am setting a fixed width for row headers. But the width of row header width changes when removing a row.

### Steps to reproduce

1. set rowHeaderWidth to 30.
2. set stretchH config as all.
3. Now remove a row the row header width will increase.

### Demo
https://angular-hot-issues.stackblitz.io

### Your environment
* Handsontable version: 7.2
* Browser Name and version: Chrome v78.0
* Operating System: Windows 7 X64

**Comment by AMBudnik** [comment]
Hey @samueljTRQ 

Are you able to replicate the issue here https://jsfiddle.net/tmh5xdv0/?

The demo you've sent does not load (maybe that's some issues with the Stackblitz).
![GIF](https://user-images.githubusercontent.com/10757813/70225906-33acb300-1750-11ea-803d-c1dffcdc1550.gif)

**Comment by AMBudnik** [comment]
I'm closing this topic as there are no updated for more than a week but if there's still something going on, please let me now @samueljTRQ
