### ISSUE TITLE
Only allow drop down values in cell of type drop down

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#6528]
### Description
When I have a cell set to type drop down I can still delete the value completely or copy/paste values that is not in the drop down list. How can I lock the cell values to only allow the values from the drop down, also blocking empty value (remove with delete or backspace buttons) if empty value is not available as alternative?

### Steps to reproduce
1. select any cell with value other than drop down values of other cell
2. copy value
3. paste to cell of type drop down
4. value is now something that is not available in drop down list

### Demo
https://stackblitz.com/edit/handsontable-drop-down-delete

**Comment by AMBudnik** [comment]
I like this idea! I've investigated the subject a little and it looks like we may need something more than `beforeKeyDown` (to block writing something in the editor), as (like you mentioned) we still can paste or autofill a value.

**Comment by AMBudnik** [comment]
Thank you for sharing this proposition.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback. 
See you there!
