### ISSUE TITLE
Input of the filter component loses focus after clicking

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6530]
### Description

The input of the filter component loses focus after clicking on that element. This issue was introduced within https://github.com/handsontable/handsontable/pull/6504.

### Steps to reproduce
![Kapture 2019-12-04 at 15 05 55](https://user-images.githubusercontent.com/571316/70149074-ae6dc380-16a7-11ea-933e-37165bfd0e8f.gif)

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Works well with the latest build (6.12) 

https://jsfiddle.net/AMBudnik/fvbk2syn/

Tested on Catalina and Chrome 78/ FF 70/ Safari
