### ISSUE TITLE
dropDownMenu do not work on iPad and mobile

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6531]
### Description
Open https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers on on `iPad` or mobile device.
Try open dropDownMenu.
Nothing happened. 

But when you opened https://handsontable.com/docs/7.2.2/demo-dropdown-menu.html dropDownMenu opens, but do not work. 
The behavior is the same on `iPad` (software version 13.2.3) and on `Android 9`, `Android 8.1`, `iPhone 13.1.3`.
![mobile-dropdownmenu 2019-12-04 16_27_24](https://user-images.githubusercontent.com/30186818/70156203-dbc06e80-16b3-11ea-9e91-baae3ff729c6.gif)

**Expected result:**
The behavior is inconsistent. My suggestion for an expected results are:
1. Blocked dropDownMenu on mobile and iPad and add an explanation in the documentation like it was on the first version of Handsontable. 
2. Fixed it 

### Your environment
* Handsontable version: 7.2.2, probably 
* Browser Name and version: Safari, Chrome on mobile
* Operating System: Android, IOS

**Comment by AMBudnik** [comment]
Can you recheck it with v8 @aninde 

It works well on my iPhone Xs


![ok](https://user-images.githubusercontent.com/10757813/91442625-6ebcbc80-e872-11ea-925a-083118b19ccf.gif)

**Comment by aninde** [comment]
True, 8.0.0 appears to have fixed the problem on smartphones but not on iPad. Although to be honest it seems to me that it works worse on the zoom.

![iphone](https://user-images.githubusercontent.com/30186818/91560662-7b0c4c80-e93a-11ea-8330-7273a52f505b.gif) 

Tested demo:
https://handsontable.com/docs/8.0.0/demo-dropdown-menu.html
https://jsfiddle.net/aninde/ja39wmoe/
and locally via GhostLab. 

Tested on the latest version of iOS 13.6.1 (iPhone SE MX9U2PM/A) Safari, Chrome
Android 10.1.0.278 (Huawei Mate 20) Chrome
iPad OS 13.6.1 and 13.3.1 (iPad), Safari, Chrome
