### ISSUE TITLE
Set focus without mouse click

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#6542]
Is it possible to set focus programmatically, like this.table.setFocus() to get back to the latest focus state after mouse clicking outside the table?
It would be really nice to be able to do this after clicking buttons or after a form submit and so on.

### Steps to reproduce
1. Use table
2. Click (button, input, ...) outside of table
3. Try to undo last changes (ctrl+z), edit selected cell or other table commands without clicking the table.

**Comment by AMBudnik** [comment]
Hey @ottosson 

are you looking for something like this https://jsfiddle.net/sghpa793/1/ `outsideClickDeselects: false` with a selective undo (only for table)?

**Comment by ottosson** [comment]
That's weird... I'm actually already using `outsideClickDeselects: false` (forgot to mention). Also maybe worth mentioning that I'm using the Angular wrapper and Angular Material, but I can't recreate the issue in Stackblitz with Angular.

Maybe it's the combination of several thing that's causing a bug. I should dig a little bit in my project now that I know that it should work out of the box!

But I guess my wish stands, that there should be a setFocus method. Sometimes I don't want the table to have focus when I press buttons, so this is a tricky situation.

**Comment by AMBudnik** [comment]
> But I guess my wish stands, that there should be a setFocus method. Sometimes I don't want the table to have focus when I press buttons, so this is a tricky situation.

yes, currently you'd need to attach some extra logic. I'll mark it as a feature request.

**Comment by AMBudnik** [comment]
Thank you for sharing this proposition, @ottosson 

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback. 
See you there!
