### ISSUE TITLE
When we fix columns and merge cells at the same time we may end up with ambiguous cell rendering.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6543]
### Description

When we fix columns and merge cells at the same time we may end up with ambiguous cell rendering.

![image](https://user-images.githubusercontent.com/10757813/70430334-ddef4800-1a7a-11ea-85a9-c2240a29a4c0.png)

Might it be better to remove (hide) the content under the `B` column and leave it like this

![image](https://user-images.githubusercontent.com/10757813/70430394-0119f780-1a7b-11ea-9fa9-9dbca9e4ebd5.png)

### Steps to reproduce

1. Just check the demo

### Demo

https://jsfiddle.net/bqn3Lxau/ 

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 78
* Operating System: Windows 10

Related to https://github.com/handsontable/handsontable/issues/3704

**Comment by wojciechczerniak** [comment]
The expected result is to display the content in both. But fixed overlay should trim it and the rest is visible in the main area:

![Screenshot 2020-07-07 at 14 04 35](https://user-images.githubusercontent.com/4718998/86778563-d0bf2980-c05a-11ea-9773-b6916766535d.png)

@AMBudnik I think this is a duplicate of #3704 just a slightly different scenario. Can we merge those two issues? It will be easier to work on if we have all the use cases in a single thread. The root couse and fix will be the same.

**Comment by AMBudnik** [comment]
@wojciechczerniak true. It seems to be the same case.
