### ISSUE TITLE
Performance issue w/hidden columns

### ISSUE THREAD

**Issue by dboskovic** [handsontable/handsontable#6545]
When you have a hidden column and edit a row near the end for the first time, this gets triggered except that it has to flatten `n` rows because of the way this array is indexed - eg with 1m rows, it must flatten 1m undefined rows in addition to the 40 in view. This should only flatten the cellMeta that is currently in display offset. Hidden columns inherently doesn't work with large files as a result of this issue.

https://github.com/handsontable/handsontable/blob/123fbe058cd01ba42c1a876ba9fa2de7e1da5bd2/src/core.js#L2407-L2409

**Comment by AMBudnik** [comment]
Hey @dboskovic 

please share the comment on this topic https://github.com/handsontable/handsontable/issues/4381 ? Both topics relate to the performance issue in `hiddenColumns` and it would be great to keep it all in one topic.

**Comment by wojciechczerniak** [comment]
@dboskovic It's already in the process of refactor:

https://github.com/handsontable/handsontable/pull/6254/files#diff-0469ad8090f37215221909a3d10792c6R177-R179

https://github.com/handsontable/handsontable/pull/6254/files#diff-102d9aa3357de91cbcd6adc1e9b23e84R162-R171

You may take a look at #6254 and let us know what you think.

**Comment by AMBudnik** [comment]
Hi @dboskovic we just updated the refferenced issue https://github.com/handsontable/handsontable/issues/4381 

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.
