### ISSUE TITLE
`getByRange` for sourceData doesn't work properly with nested object data.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#6548]
### Description
Calling `getSourceData(r1, r2, c1, c2)` (and technically `getByRange` from `dataSource.js`) on an instance with data containing nested objects doesn't work properly.

### Steps to reproduce
1. Declare the dataset as an array of nested objects, e.g.: 
```
[
  {
    lorem: { first: 1, second: 2 },
    ipsum: 'test 2' 
  }
]
```
2. Declare the `columns` as:
```
columns: [
    { data: 'lorem.first' },
    { data: 'lorem.second' },
    { data: 'ipsum' }
  ]
```
3. Call `hot.getSourceData(0,0, 0, 2)`

**Result:**
![image](https://user-images.githubusercontent.com/7397134/70524077-b664b200-1b44-11ea-86d7-37d42ca97eda.png)

### Demo

https://jsfiddle.net/js_ziggle/ja0ky6oe/

Will be probably fixed in #6546.

**Comment by aninde** [comment]
This issue is fixed by `v8` https://jsfiddle.net/aninde/50vznwqj/
Result:
<img width="151" alt="Screenshot 2020-08-05 at 11 30 40" src="https://user-images.githubusercontent.com/30186818/89396673-2268db80-d70f-11ea-8f36-0d3e8f4058f9.png">
