### ISSUE TITLE
[feature request] support row span setting in nestedHeader

### ISSUE THREAD

**Issue by DongShi** [handsontable/handsontable#6553]
### Description
By now , it seems we can only set colSpan in [nestedHeader](https://handsontable.com/docs/7.2.2/NestedHeaders.html), but there are cases we need to merged header cells by row (setting rowSpan > 1).

A common use case is to display columns title with common text, in our case, we need to display three metrics: NorthEast-Revenue, NorthEast-Unit Price and NorthWest-Revenue.

It looks much nicer if we can group together the "Region" part on top of detailed metric name.
Also, in this case, we want the NorthWest-Revenue to be a meged cell (rowspan = 2)

![image](https://user-images.githubusercontent.com/5009987/70618108-0890fa80-1c4d-11ea-8bda-aa0719127492.png)

Please be noted many other libs already support this, if HOT can not support this, we have to evaluate other solutions..

two  example:
[Ant-design table
](https://ant.design/components/table/#components-table-demo-grouping-columns)

![image](https://user-images.githubusercontent.com/5009987/70620136-645d8280-1c51-11ea-8822-912358c0113c.png)

[tabulator](http://tabulator.info/docs/4.5/columns#groups)
![image](https://user-images.githubusercontent.com/5009987/70620091-4d1e9500-1c51-11ea-95da-a8622316d0eb.png)

### Steps to reproduce

1. Just see my description above
2.
3.

### Your environment
* Handsontable version: Latest
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Thank you for sharing the topic. We have discussed it a couple of times but did not create an official topic to relate to.

**Comment by AMBudnik** [comment]
Thank you for sharing this proposition.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback. 
See you there!
