### ISSUE TITLE
Can't populateFromArray when cell is read only

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#6555]
### Description
(#2701 seems to deal with the same issue but is closed, so I'm opening this question)

I want to populate read only cells using the populateFromArray. Since it's a programmatic way to change cells I would expect it to work, but it does not...

Am I approaching this wrong? Are there any reasonable workarounds for this?

### Steps to reproduce

1. Set column to read only
2. use populateFromArray to set data to table
3. Data in read onlycells will not be populated

### Demo
https://stackblitz.com/edit/handsontable-populatefromarray

**Comment by AMBudnik** [comment]
Here https://jsfiddle.net/xv57h18r/ it works fine. The same if we just pick one column and it readOnly via `cells` method https://jsfiddle.net/xv57h18r/1/ or uses `columns` https://jsfiddle.net/xv57h18r/2/
so I guess it might be related to Angular. It is surely something that has to be checked.

**Comment by ottosson** [comment]
That's unfortunate. setDataAtCell works so I guess I could use that as a temporary workaround for now. But I guess it will be slow to set each cell individually...

I'd appreciate it if you'll have a look at this issue.

Thanks

**Comment by AMBudnik** [comment]
Hey @ottosson 

I've asked a developer for help. Here's his investigation report

This is a planned action. In the vanilla version, the client scenarios behave the same here https://jsfiddle.net/o0n8stkx/

On this line in `populateFromArray` - https://github.com/handsontable/handsontable/blob/master/src/core.js#L773 - we check `cellMeta` and if it's readOnly it's ignored and the loop continues.

So this isn't a bug,

**Comment by ottosson** [comment]
Ok, thanks. Would it be interesting to add a force flag to populateFromArray? Now I've made a workaround where I remove all readOnly settings and applies them after I run the populate command. Not ideal but works for in this case.

**Comment by AMBudnik** [comment]
I've closed the issue but wanted to confirm if the solution works for you (you've mentioned a flag).
