### ISSUE TITLE
Pasting objects only works if their schemas match

### ISSUE THREAD

**Issue by lulezi** [handsontable/handsontable#6561]
### Description
When pasting an object that has other attributes than the existing data (i.e. their schemas don't match), the paste fails.

### Steps to reproduce
1. Copy A1. 
2. Paste it to A2 => B2 changes from "prop" to "other" as expected. 
3. Paste it to A3 => A3 doesn't change (and neither does B3).

### How to fix
We tracked it down to the `isObjectEqual(orgValueSchema, valueSchema)` in `populateFromArray`. Is there any particular reason why this check is needed? I can provide a PR if that'd be helpful.

### Demo

https://jsfiddle.net/L8qjt46u/

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: Chrome and Edge
* Operating System: macOS 10.12.6 and Windows 10

**Comment by AMBudnik** [comment]
Hey @lulezi 

as mentioned here https://handsontable.com/docs/7.3.0/tutorial-data-binding.html

> Handsontable binds to your data source (list of arrays or list of objects) by reference.

and in the demo you use 

```
var data = [
  { foo: {bar: "prop"}},
  { foo: {bar: "other"}},
  { }
]
```

which is currently too complex for Handsontable to handle.

**Comment by lulezi** [comment]
Thanks @AMBudnik for clarifying.
