### ISSUE TITLE
Down border of CustomBorder sticking out under left overlay while scrolling on iOS 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6566]
### Description
Down border of `CustomBorder` sticking out under left overlay while scrolling horizontally on Ipad and iPhone on 100% zoom. Interestingly, the bug does not appear after the zoom. 
This bug looks like https://github.com/handsontable/handsontable/issues/4142#issuecomment-287709079 but it occurs without fixed/frozen column.

### Steps to reproduce

1. Open demo https://jsfiddle.net/aninde/t752kqnr/ on Ipad or iPhone.
2. Scroll table horizontally - broken. 
3. Zoom it and repeat steps - fixed.

`7.2.2 v.`
![ipad-7 2 2](https://user-images.githubusercontent.com/30186818/70812125-4b76dd80-1dc7-11ea-86aa-619d0739920a.gif)

`7.2.2 v. + SVG borders` 
![ipad-PR-svg](https://user-images.githubusercontent.com/30186818/70812454-ec659880-1dc7-11ea-94b5-2b129f9ff204.gif)

### Demo

https://jsfiddle.net/aninde/t752kqnr/ - `7.2.2 v.`
https://jsfiddle.net/aninde/6r0s7mcx/ - [currently tested](https://github.com/handsontable/handsontable/pull/6157) new SVG borders 

### Your environment
* Handsontable version: 7.2.2, 7.3.0, even on new way of drawing SVG borders
* Browser Name and version: Safari on iPad and iPhone 6
* Operating System: iOS

**Comment by krzysztofspilka** [comment]
@aninde @AMBudnik  I suggest marking this issue as `won't fix` and closing it.

**Comment by AMBudnik** [comment]
I've also asked @wojciechczerniak for an opinion on the subject.

We agreed that with the current scroll settings that is the desired (and accepted) outcome. @aninde I'm closing this ticket.
