### ISSUE TITLE
CSS grids can break handsontable rendering

### ISSUE THREAD

**Issue by mscotch1** [handsontable/handsontable#6567]
### Description
Placing a Handsontable within a CSS grids grid item and trying to size the table dynamically can lead to table flickering.

### Steps to reproduce
1. Place a Handsontable within a CSS grids grid item
2. Attempt to give it a height of '100%' in the table settings
3. The table does not show up immediately, but programmatic calling of the table's "render" function does render the table. Then, scrolling makes the table flicker.

*Note*: For some reason, the height has to be set to 100% exactly. There is no screen flickering if the height is set to 99.999% or some other value

### Demo
https://jsfiddle.net/ydc9buLf/7/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome Version 79.0.3945.79 (Official Build) (64-bit)
* Operating System: Windows 10 Home, Version 1903, OS build 18362.535

**Comment by AMBudnik** [comment]
I have replicated the flickering of the 2nd table. That is surely something unexpected and could be marked as a bug, but I have a hunch that it won't be something easy to fix.

**Comment by AMBudnik** [comment]
Works the same in `8.0.0-beta1` https://jsfiddle.net/AMBudnik/ovrnadjz/

**Comment by AMBudnik** [comment]
Hi @mscotch1 

We just tested the following use case using Handsontable v12.3 https://jsfiddle.net/y6jusxzk/. It seems to work across all major browsers. Could you confirm?
