### ISSUE TITLE
Handsontable Angular - custom renderer with numeric value not working

### ISSUE THREAD

**Issue by jzinkovich** [handsontable/handsontable#6568]
### Description

I have a column with the following definition:

 {

                                    type: 'numeric',
                                    numericFormat: {
                                      pattern: '$0,0.00',
                                      culture: 'en-US' // this is the default culture, set up for USD
                                    },
                                    allowEmpty: true,
                                    renderer: this.getMoney
},

Custom Render method:  getMoney

```
getMoney(instance, td, row, col, prop, value, cellProperties) {
      if(instance.getSourceData()[row]) {
        var moneyTransaction:MoneyTransactionCargo = instance.getSourceData()[row] as MoneyTransactionCargo
        if(moneyTransaction.breakdown) {
             var expenseChanged:PersonMoneyTransactionCargo = moneyTransaction.breakdown.find(x => x.personId === 1);
             if(expenseChanged) {
                  console.log(expenseChanged.amount) --> this does show the numeric value
                   value = expenseChanged.amount;
             }
         }
      }
      Handsontable.renderers.NumericRenderer.apply(this, arguments);
    }

```

When my table renders there is no value in the column.  What am I doing wrong?

Handsontable Version 7.2.2
Chrome 78.39
Mac: Catalina

**Comment by AMBudnik** [comment]
Hey @jzinkovich 

can you share the code via demo? Maybe the reference is wrong, or maybe you need to add anything as an `else` statement.

**Comment by AMBudnik** [comment]
As there are no updates and/or a demo I guess that I need to close it.
