### ISSUE TITLE
Array/Object cell type feature request

### ISSUE THREAD

**Issue by maxcorbeau** [handsontable/handsontable#6569]
### Description
When editing an array value, Handsontable refuses to take the input into account. There doesn't seem to be an array/object type:
https://handsontable.com/docs/7.3.0/tutorial-cell-types.html

### Steps to reproduce
1. Go to http://jsfiddle.net/t9jrq8d5/
2. Try to edit cell C3
3. Grid won't take your input even if you input a JSON.stringify-compatible value

### Feature request
Add Array/Object cell types which apply JSON.parse to the input and use JSON.stringify as renderer.

**Comment by AMBudnik** [comment]
Hey @maxcorbeau 

as mentioned here https://github.com/handsontable/handsontable/issues/6561

> Handsontable binds to your data source (list of arrays or list of objects) by reference.

and in the demo you use 

```
  data: [
    [null],
    ["1,2"],
    [ [1,2] ],
  ],
```

which is currently too complex for Handsontable to handle.

**Comment by maxcorbeau** [comment]
> which is currently too complex for Handsontable to handle.

That's why I raised the matter as a feature request :)

**Comment by AMBudnik** [comment]
The nested data feature has been raised here https://github.com/handsontable/handsontable/issues/2371
We keep feature request closed and open them after adding to the backlog.

**Comment by maxcorbeau** [comment]
OK thanks, no need to update here if an updated is posted in #2371
