### ISSUE TITLE
Cell with Multiple Lines and scrolling

### ISSUE THREAD

**Issue by d3chapma** [handsontable/handsontable#657]
When a table has a cell that has multiline content and the table has a horizontal scrollbar, when you scroll the table such that the multiline content is no longer visible the table shrinks and the scrollbar stays in its original position. 

I assume the proper behaviour would be to not let the table shrink, but that may be difficult with virtual rendering.

See this example and scroll the table to the right: http://jsfiddle.net/wpWMJ/16/

**Comment by AMBudnik** [comment]
Please try [it](https://jsfiddle.net/wpWMJ/128/) now, it should work fine.

**Comment by gstanislav** [comment]
Still reproducible for me. 

http://jsfiddle.net/jhu3v3w1/ - scroll right.

**Comment by AMBudnik** [comment]
@gstanislav please check this example http://jsfiddle.net/jhu3v3w1/2/ `autoRowSize: true`
