### ISSUE TITLE
Fill data in handsontable cells using selenium for automation testing

### ISSUE THREAD

**Issue by vk-sourcefuse** [handsontable/handsontable#6570]
### Description

We want to fill the values in cells using SELENIUM for automation testing, so for that, 
: is it possible to add unique ID to each cell of handsontable, so that we can pick that to enter value manually, 
: If we scroll table, it deletes old cells (<td>) , is it possible to keep previous cells too?
: or is there any way to run setDataAtCell using Selenium ?

### Demo

 https://drive.google.com/file/d/1WxkyqEQMnyWa_bcornfmtZj4uPigTi1Y/view

### Your environment
* Handsontable version: Any
* Browser Name and version: Any
* Operating System: Any

**Comment by vk-sourcefuse** [comment]
Hi @AMBudnik  @pnowak  @wojciechczerniak , can anyone please suggest anything on it? 
We've purchased a license from you, do we need to share licenseKey or do emails from that account for faster response / support on the product ?

**Comment by wojciechczerniak** [comment]
Hi @vk-sourcefuse. The quickest way to reach our support engineers is via our contact form at https://handsontable.com/contact?category=technical_support or support@handsontable.com We're using Github mostly to track bugs and features, issues here are not reviewed on a daily basis. Sorry for the late answer.

1. You can add ID with custom renderer
2. You can disable virtual rendering with `renderAllRows` option
3. You can call `setDataAtCell` as any other Javascript in Selenium, you just need a reference to Handsontable instance

**Comment by vk-sourcefuse** [comment]
Thanks @wojciechczerniak , I've created this working jsfiddle, https://jsfiddle.net/vaibhavsourcefuse/qswhd75p/ .
