### ISSUE TITLE
Table doesn't render properly row headers.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6572]
### Description
If we have trimmed rows and after move row, the hot table doesn't render properly `rowHeaders`.

### Steps to reproduce

1. Go to https://jsfiddle.net/m0tyehpd/
2. In console use `hot.getPlugin("trimRows").untrimAll();`
3. Next call `hot.render();`

### Demo

https://jsfiddle.net/m0tyehpd/

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version:
* Operating System:

**Comment by pnowak** [comment]
Duplicate - https://github.com/handsontable/handsontable/issues/6276

**Comment by AMBudnik** [comment]
Mentioned issue #6276 has been fixed within version 8.2.0
