### ISSUE TITLE
Data type change stops table from rendering 

### ISSUE THREAD

**Issue by SchnitzelAndSpaetzle** [handsontable/handsontable#6573]
### Description
When the loading data is an array of arrays and `loadData` is called with an array of objects, the table should rerender. Instead its just empty. 

### Steps to reproduce
1. Load jsfiddle below
2. Click load new data.

Note: if you click it twice the data will load.

### Demo
https://jsfiddle.net/r9xeo2L5/1/

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: Mozzila Firefox 72.0b5 (64-bit), Chrome Version 79.0.3945.79 (Official Build) (64-bit)
* Operating System: Windows 10 Pro (64bit)

**Comment by AMBudnik** [comment]
True. Thank you for sharing @SchnitzelAndSpaetzle 

This issue has been already raised here https://github.com/handsontable/handsontable/issues/4204
