### ISSUE TITLE
Separate testing and security audit in CI

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6574]
### Description
Currently, we have a single CI job that performs a dependency security (`npm audit`) and then, only if the audit succeeds, performs functional and unit testing.

Most of the time, security audit failures happen for reasons unrelated to the author of a commit. Therefore, it is not desired that such failures can block the execution of tests and mark the commit as failed.

My proposal, given at today's weekly kick-off meeting, is to split the CI jobs into two:

1. A job that runs on every commit and marks the commit bad if the tests fail. I don't know about CodeShip, but in GitHub Actions, the CI workflows can have names. I would call this one `Functional and unit testing`.
2. A job that runs on every commit and marks the commit bad if the `npm audit` fails (and maybe other audits, too). I would call it `Dependencies audit`.

#### Bonus question

What Snyk is for, if it passes even when `npm audit` failed on CodeShip? As can be seen in this commit: https://github.com/handsontable/handsontable/pull/6547/commits/7a660af8bcdb93f421a9935cd7347464ec0d3152. Build results:

- CodeShip: https://app.codeship.com/projects/26649/builds/45260634
- Snyk: https://app.snyk.io/org/krzysztofspilka/project/cf43850b-6912-419d-9516-86db851456d8/pr-check/70268f81-bb23-4255-bc94-50de188ea664?refs=develop..7a660af8bcdb93f421a9935cd7347464ec0d3152

![image](https://user-images.githubusercontent.com/566463/70918542-7d827c80-201f-11ea-93cb-494dea5d0748.png)

**Comment by wojciechczerniak** [comment]
Done in #6648
