### ISSUE TITLE
Get distinct values in a column

### ISSUE THREAD

**Issue by michaelpulis** [handsontable/handsontable#6577]
### Description
To my knowledge, there is no function which returns the distinct values in a column

### Similar Functionality
Similar functionality already exists in the filtering plugin
![image](https://user-images.githubusercontent.com/35961035/70998410-99495980-20d7-11ea-9f98-7b9870ade8fe.png)
The screenshot above shows that internally, the distinct values are being stored/found somewhere, and I'm curious to know if that data can be accessed.

### Already Attempted
A solution has already been written, but since this particular table contains many cells, it is quite slow to find the values. If an internal data structure already exists which contains this data it would speed up the performance considerably.

**Comment by AMBudnik** [comment]
Hey @michaelpulis 

That is a part of the plugin. There's no external API to get distinct values. I guess that I would just call [`getDataAtCol`](https://handsontable.com/docs/7.3.0/Core.html#getDataAtCol) and maybe use [`includes`](https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Obiekty/Array/includes).
