### ISSUE TITLE
Row header width varies when removing a row.

### ISSUE THREAD

**Issue by samueljTRQ** [handsontable/handsontable#6578]
### Description
I am using stretchH option and I am setting a fixed width for row headers. But the width of row header width changes when removing a row.

### Steps to reproduce
1. set rowHeaderWidth to 30.
2. set stretchH config as all.
3. Now remove a row the row header width will increase.

### Demo
https://angular-hot-issues.stackblitz.io

### Your environment
* Handsontable version: 7.2
* Browser Name and version: Chrome v78.0
* Operating System: Windows 7 X64

**Comment by samueljTRQ** [comment]
If the demo doesn't work please try this https://angular-hot-issues.stackblitz.io

**Comment by samueljTRQ** [comment]
![HOT-Issue-6578](https://user-images.githubusercontent.com/49991045/71071954-8e5bfb00-21a3-11ea-8d96-1ec9406cd078.gif)

**Comment by AMBudnik** [comment]
The same as https://github.com/handsontable/handsontable/issues/6580 so I am closing this as a duplicate.
