### ISSUE TITLE
Context menu failing when cell has HTML child nodes

### ISSUE THREAD

**Issue by davestewart** [handsontable/handsontable#6579]
### Description

I have a cell with custom HTML, and right click is failing when the right click is over a child node:

```
contextMenu.js?8661:365 Uncaught TypeError: Cannot read property 'nodeName' of null
    at isValidElement (contextMenu.js?8661:365)
    at ContextMenu.onAfterOnCellContextMenu (contextMenu.js?8661:380)
    at Core.eval (contextMenu.js?8661:202)
    at Hooks.run (pluginHooks.js?76d1:1966)
    at Core.runHooks (core.js?cf0b:3833)
    at Object.onCellContextMenu (tableView.js?df81:521)
    at Settings.getSetting (settings.js?6242:164)
    at Walkontable.getSetting (core.js?1533:266)
    at Event.onContextMenu (event.js?8e85:237)
    at HTMLDivElement.eval (event.js?8e85:69)
isValidElement @ contextMenu.js?8661:365
onAfterOnCellContextMenu @ contextMenu.js?8661:380
eval @ contextMenu.js?8661:202
run @ pluginHooks.js?76d1:1966
Core.runHooks @ core.js?cf0b:3833
onCellContextMenu @ tableView.js?df81:521
getSetting @ settings.js?6242:164
getSetting @ core.js?1533:266
onContextMenu @ event.js?8e85:237
eval @ event.js?8e85:69
callbackProxy @ eventManager.js?8c32:65
```

The error is here:

```js
    value: function onAfterOnCellContextMenu(event) {
      var settings = this.hot.getSettings();
      var showRowHeaders = settings.rowHeaders;
      var showColHeaders = settings.colHeaders;

      function isValidElement(element) {
        // HERE!
        return element.nodeName === 'TD' || element.parentNode.nodeName === 'TD';
      }
```

The cell HTML is:

```html
<td class="anValue anReadOnly anRemoved current highlight">
    <span class="symbol">EUR</span>
    <span class="value">2,044,800</span>
</td>
```

The error is with `parentNode` which in my case is `null` even though the clicked node is `<span class="value">2,044,800</span>`.

Clicking where the `span` is not, allows the menu to work.

This is on a read-only column. Not sure if that helps?

### Steps to reproduce

Create a custom renderer with HTML child elements, and right click. The column may need also to be read only.

### Demo

Too complex to provide a demo, sorry!

### Your environment

* Handsontable version: 7.1
* Browser Name and version: Chrome
* Operating System: OSX

**Comment by AMBudnik** [comment]
Hey Dave,

I guess that I made all the steps here https://jsfiddle.net/v3a9bkw1/ but couldn't replicate the issue. Do you see something obvious missing?

**Comment by davestewart** [comment]
Hmm. That is strange!

I'm away for Christmas now, but I'll make a note to look at it when I get back in Jan.

Happy Christmas, and speak then.

PS. We are close to launching!

**Comment by wojciechczerniak** [comment]
> PS. We are close to launching!

I've seen the teasers on Twitter, can't wait to check the live version 🍾 🤞

**Comment by AMBudnik** [comment]
Happy Christmas 🎄I keep my fingers crossed for the launch!

**Comment by davestewart** [comment]
And you too!

**Comment by AMBudnik** [comment]
Hey Dave.

I hope that the launch was a blast!
Have you had time to check the context menu topic?

**Comment by davestewart** [comment]
Hey Aleksandra!

We are built, but not launched yet 😅

Do you mean this thread, or was there a topic on the forum?

**Comment by AMBudnik** [comment]
> We are built, but not launched yet 😅

Ohhh, sorry. I thought that the project is already up and running.

> Do you mean this thread, or was there a topic on the forum?

This one. I wanted to replicate it but wasn't able to get anything similar. So I would be grateful for any demos where the issue can be replicable.

**Comment by davestewart** [comment]
OK! Well, I'm in next week (down to one day a week on that project) so let me take a look then.

Yes, we're excited to launch as well. We are a two-sided marketplace so just need to secure customers on both sides, then we are up and running!

You will be the _first_ to know, I promise 😁

**Comment by AMBudnik** [comment]
Cool! :) I keep my fingers crossed and eyes open.

**Comment by AMBudnik** [comment]
Hey Dave, how's progress?

**Comment by davestewart** [comment]
I'll drop you a mail!

**Comment by AMBudnik** [comment]
@davestewart I'll reopen the issue when you'll be ready to continue.
