### ISSUE TITLE
Hooks beforeColumnResize and beforeRowResize should disable row/column resize

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6581]
### Description
Disabling works only for double-click. 
We should disable this action so that it returns false from these hooks for resizing, independent of the actions made (manual resize or by API).

**Comment by AMBudnik** [comment]
inform [forum](https://forum.handsontable.com/t/restrict-the-manual-column-resizer-to-handsontable-width/4231)

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback. 
See you there!
