### ISSUE TITLE
We're not able to undo changes while using summary calculations and `numeric` cell data.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6582]
### Description

We're not able to undo changes while using summary calculations and `numeric` cell data.

### Steps to reproduce

1. Edit cell `A1`
2. Use <kbd>CTRL/CMD</kbd>+<kbd>Z</kbd>

**Result**
The summary is selected, it flickers and the value does not change back.

### Demo

https://jsfiddle.net/AMBudnik/p6tu75Lw/

### Your environment
* Handsontable version: 7.3.0
`Doesn't seem to be related to any version`
* Browser Name and version: Chrome 78
* Operating System: macOS Catalina

**Comment by aninde** [comment]
The issue stays the same with the new version of `numbro` in `7.4.0 v.` https://jsfiddle.net/aninde/eLx7aotf/ (minified v.) https://codesandbox.io/s/6582-740-6f3cf (full v.)

**Comment by AMBudnik** [comment]
Demo updated to v8.0.0 https://jsfiddle.net/v6b49dcr/1/ works the same as described.

![bug](https://user-images.githubusercontent.com/10757813/90507165-bbf3ac80-e155-11ea-8912-744a3f27d85c.gif)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
