### ISSUE TITLE
a little change about isCommandPassive function in menu.js

### ISSUE THREAD

**Issue by maketubo** [handsontable/handsontable#6583]
let isCommand can be a function then also help to make sure the menu is not
closed more automatically after the user trigger the command through the UI

### Demo
![image](https://user-images.githubusercontent.com/14799012/71249848-0fa8be80-2359-11ea-89f8-21fd5b5c81a7.png)

**Comment by AMBudnik** [comment]
Hey @maketubo 

if you'd like to propose a change in the code it needs to follow the [Contributing guidelines](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md).

Now we do not know what is the purpose of the change. Is it a bug (what does it fix) or a feature (what it adds)?
