### ISSUE TITLE
manual row move on sorted data

### ISSUE THREAD

**Issue by jabbad-92** [handsontable/handsontable#6586]
### Description
When you want to move a row to another position, and you have sorted by a column, it does not do it correctly

### Steps to reproduce

1. Sort by A column
2. Move row 7 to position 0
3. It's move antoher row

### Demo
https://jsfiddle.net/w741n69r/

**Comment by AMBudnik** [comment]
Hey @jabbad-92 

Please try the same scenario with this demo (updated to Handsontable 8.0.0-beta1) https://jsfiddle.net/qvrz2c5f/
The beta introduces an index mapper that solves most of index-related issues.

**Comment by AMBudnik** [comment]
Hey @jabbad-92 

any updates?

**Comment by jabbad-92** [comment]
Hi,

With Handsontable 8.0.0-beta1 it's work correctly

Thanks

**Comment by AMBudnik** [comment]
Great! Thank you for feedback.
