### ISSUE TITLE
iOS: Borders are missing while editing a cell

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6588]
### Description

The issue has been mentioned here https://github.com/handsontable/handsontable/issues/5203#issuecomment-569623794

When we're using iOS on iPhone Xs (we have to check this on other devices, including Android) the borders are gone when we enter edit mode

![issue](https://user-images.githubusercontent.com/10757813/71572774-0d74fb80-2ae1-11ea-851b-5271b6f06fb3.gif)

Fortunately, the issue is mostly fixed with the SVG borders

![issue](https://user-images.githubusercontent.com/10757813/71577116-2a1a2f00-2af3-11ea-9554-cf7049695e01.gif)

However, now after closing the editor cell lacks the custom borders. To get them back we need to select any other cell or edit the last one.

### Steps to reproduce

1. Enter this demo on a mobile device https://jsfiddle.net/q7uLn3kr/ 
2. Edit any cell

**Result**
You'll see that the border is gone

### Demo

@aninde 's build from https://github.com/handsontable/handsontable/issues/6566

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: Chrome 78
* Operating System: iOS

**Comment by aninde** [comment]
I have tested it on 7.4.1 v. and there, borders are missing only while editing cell from fixed row/column.

**Comment by AMBudnik** [comment]
The [same demo](https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers)
 and same device - iPhone Xs using `7.4.2` 

![mobile](https://user-images.githubusercontent.com/10757813/75023933-e6abc380-5498-11ea-9251-2a64e8436961.gif)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Interoperability problems using Mobile devices and some core features** task reported at https://github.com/handsontable/handsontable/issues/7520

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by aninde** [comment]
Fixed by v8.4.0.

**Comment by AMBudnik** [comment]
Issue closed as solved for [v 8.4.0](https://github.com/handsontable/handsontable/issues/7998)
