### ISSUE TITLE
Bicolored table switches its colors when scrolled horizontally

### ISSUE THREAD

**Issue by HardRock4Life** [handsontable/handsontable#6590]
### Description
I need to have a bicolored table, I've followed your recommendations at https://handsontable.com/docs/3.0.0/tutorial-styling.html and used this code:

```
/* Every odd row */
.ht_master tr:nth-of-type(odd) > td {
  background-color: #f00;
}

/* Every even row */
.ht_master tr:nth-of-type(even) > td {
  background-color: #f00;
}
```

### Demo
https://jsfiddle.net/ot37wu48/
To see the effect, scroll vertically at random area of the table (in case, those are rows 77, 81, 85 and 89), then scroll horizontally. Let's say if you start at 89. Then if goes like this:
1) scrolled to 85 -> scrolled horizontally -> nothing changed;
2) scrolled to 81 -> scrolled horizontally -> nothing changed;
3) scrolled to 77 -> scrolled horizontally -> 77th row has changed its color from light to dark;
3) scrolled back to 81 -> scrolled horizontally -> 81th row has changed its color back from dark to light;

Maybe there is an alternative path to set colors, e.g. using fixed rules at the ```Cells``` properties from https://handsontable.com/docs/7.3.0/Options.html#cells?

Wesołych Świąt i Szczęśliwego Nowego Roku!

UPD: should the property ```"renderAllRows"``` be helpful at it? 
Looks like it is, but performance falls drastically... :(

**Comment by AMBudnik** [comment]
Hi @HardRock4Life 

Can you share a recording/video? I'm not able to replicate the issue. Are you on Mac/Windows and Chrome 79?

> Wesołych Świąt i Szczęśliwego Nowego Roku!

Thank you :)

**Comment by HardRock4Life** [comment]
> Can you share a recording/video? I'm not able to replicate the issue. 

I could try to do that.

> Are you on Mac/Windows and Chrome 79?

That's right, Windows exactly.

**Comment by wojciechczerniak** [comment]
IMO it would be better to use `cells` and `cellProperties` to add `even`/`odd` class. An idea that @HardRock4Life already mention in the first comment.

```ts
cells: function (row, column) {
  return {
    className: row % 2 === 0 ? 'even' : 'odd',
  }
}
```

**Comment by HardRock4Life** [comment]
So, here's the progress I've got: added @wojciechczerniak code into the 
```
hot.updateSettings({
 cells: function (row, column) {
  return {
    className: row % 2 === 0 ? 'even' : 'odd',
  }
}
});
```

and applied CSS styles like this:

```
td.even.htDimmed {
  background-color: #005fa1;
  color:white;
  font-size: 8px;
}

td.odd.htDimmed {
  background-color: #00487a;
  color:white;
  font-size: 8px;
}
```

However, when I apply filters from the DropDownMenu, some rows are having same color, because some rows got trimmed due to filtering. Tried to use ```hot.render()``` method - didn't work. Looking for something to use instead of ```render()``` now :|

**Comment by HardRock4Life** [comment]
Does it make much difference, if I write like this:
```            
cells: function (row, column) {
  const visualRow = this.instance.toVisualRow(row);

  return {
    className: visualRow % 2 === 0 ? 'even' : 'odd',
  }
}```
?

**Comment by AMBudnik** [comment]
`this` in `cells` is an object of properties and `this.instance` is an instance, so true - you should use `this.instance` for `toVisualRow` method.

**Comment by HardRock4Life** [comment]
Hm, not working yet, but I still keep trying

**Comment by AMBudnik** [comment]
Do you get any errors in the console or the result is incorrect @HardRock4Life ?

**Comment by HardRock4Life** [comment]
> Can you share a recording/video?

Eventually, I'll try to show it using screenshots.
So, here is the table from the very first fiddle (https://jsfiddle.net/ot37wu48/):
![image](https://user-images.githubusercontent.com/21273349/72864427-c819a780-3cf5-11ea-8cb4-78b644376b12.png)


E.g. I scroll till here:
![image](https://user-images.githubusercontent.com/21273349/72864475-f5665580-3cf5-11ea-86da-1129dd1856f9.png)


Scroll it horizontally and...
![image](https://user-images.githubusercontent.com/21273349/72864491-0ca54300-3cf6-11ea-9d7e-ddefae6ebc5a.png)





> Do you get any errors in the console or the result is incorrect @HardRock4Life ?

I had a typo that wouldn't let rows to get painted. I've finally wrote code like this:

```
      afterDropdownMenuHide: () => {
        this.hot.updateSettings({
          cells: function(row, col) {
            const visualRow = this.instance.toVisualRow(row);

            return {
              className: visualRow % 2 === 0 ? 'even' : 'odd'
            };
          }
        });
        this.hot.render();
      }
```
Without ```render()```, classes wouldn't refresh. Now it works fine! :)

**Comment by AMBudnik** [comment]
> Without render(), classes wouldn't refresh. Now it works fine! :)

Yes! Thank you for the update. I'm glad to hear that. 
Is there anything else that concerns you?

**Comment by HardRock4Life** [comment]
There is still one thing, though. It is, when I scroll, the table randomly 'jumps over' some rows or scrolls discontinously.

**Comment by AMBudnik** [comment]
Wow. This sounds odd. I would love to replicate this issue.

**Comment by HardRock4Life** [comment]
> Wow. This sounds odd.

Totally agree 😃 
Let's see if I can do it at some demo as well.

**Comment by HardRock4Life** [comment]
https://jsfiddle.net/ax6tpovg/2/
Here it loads fine. What do you think, maybe decreasing the amount of rendered rows would cause less load onto a table?

**Comment by AMBudnik** [comment]
The number of rows shouldn't be an issue.
Maybe there's a mismatch between the libraries. What frameworks/libraries are used in the project?

**Comment by HardRock4Life** [comment]
Excuse me for a continious silence. No, there aren't any external libraries used

**Comment by AMBudnik** [comment]
Hey @HardRock4Life 

Could you send over a video that shows the issue on support@handsontable.com?
