### ISSUE TITLE
autoRowSize break layout

### ISSUE THREAD

**Issue by godshades** [handsontable/handsontable#6591]
### Description
Break layout when set autoRowSize = true and scroll down fast
### Steps to reproduce

1. autoRowSize = true, lazyload ( 100 rows each)
2. If I scroll slow layout still OK
3. If I move fast (Ex: go to row 300), after finish load data, height of row header will shorter
After that, I scroll again (up or down) layout will become normal

Sr for my bad english. Does anyone have same problem

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome, Firefox
* Operating System: Win 10

**Comment by AMBudnik** [comment]
Hey @godshades 

here https://jsfiddle.net/7rng2vsj/ I'm testing 300 rows x 5 columns data and can't replicate the issue.

Testing environment: Windows 10, Chrome 79, Handsontable 7.3.0, mouse scroll

Do you get the same issue on my demo? Can you record it?

**Comment by AMBudnik** [comment]
Hey @godshades 

do we have any updates here?

**Comment by godshades** [comment]
sorry, I don't know how to explain but I alreaydy solve problem
