### ISSUE TITLE
handsontable compatability with dojo

### ISSUE THREAD

**Issue by sindhus91** [handsontable/handsontable#6592]
### Description

handsontable compatability with dojo

### Steps to reproduce

1. i have imported  <script src="js/mc/handsontable.full.min.js"></script>
   <style type="text/css">@import "js/mc/handsontable.full.min.css"</style>
in my jsp page
2. I have created a handontable in js
3. I am getting error - Uncaught ReferenceError: Handsontable is not defined

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* dojo version: 1.8
* Browser Name and version: google crome
* Operating System: centOS

**Comment by AMBudnik** [comment]
Hey @sindhus91 

we do not have any example of the Handsontable working on Dojo, but I have found a similar issue on our forum https://forum.handsontable.com/t/dojo-compatibility/2465/2

Please let me know if that hint changes anything.
