### ISSUE TITLE
How to fetch the values from handsontable in dojo

### ISSUE THREAD

**Issue by sindhus91** [handsontable/handsontable#6596]
### Description
how to fetch the values of handsontable using dojo

### Steps to reproduce

1.i have created hansontable in js.
2.i am getting the values from database.
3.i have give button to save at the end.
4. i need to fetch all the values of the handson table.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:Chrome
* Operating System:centOS

**Comment by AMBudnik** [comment]
Hey @sindhus91 

to get all data with one click you can call [getData](https://handsontable.com/docs/7.3.0/Core.html#getData) in the button. Have you tried it?
