### ISSUE TITLE
Way to count/get comments?

### ISSUE THREAD

**Issue by keyserfaty** [handsontable/handsontable#6597]
### Description
Is there a way to count how many comments are there in a table? I find a way of doing it using `afterRenderer` but seems to perform very poorly.

### Your environment
* Handsontable version: 7.3.0 (running on React)
* Browser Name and version: Chrome v70.9.
* Operating System: MacOS

**Comment by AMBudnik** [comment]
There's no one method to get the score but it's achievable. I imagine that there a couple of ways to get this done.

The one that I thought about is to use the native `querySelectorAll` for the `htComment` class https://jsfiddle.net/yxuht48k/ but you need to use `renderAllRows` or the `~offset` settings as not all the cells are printed in the DOM.

**Comment by AMBudnik** [comment]
Actually let's rename the topic to a feature request. I really like the idea on having more control over the comments.

**Comment by keyserfaty** [comment]
I think that sounds even better than what I ended up doing. Will try that out. Thanks :)

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback. 
See you there!
