### ISSUE TITLE
Handsontable which contain user defied tooltip with help icon for headers

### ISSUE THREAD

**Issue by abhaya957** [handsontable/handsontable#6598]
### Description

We have handsontable, we want to have Help icon in header and On hover it should display tooltip.
### Steps to reproduce

1. Header should have help icon 
2. On hover on help icon it should display different tool tip for different header.
3. Please see image attached for more info.

### Your environment
* Handsontable version: 0.31.2
* Browser Name and version: Google chrome
* Operating System: Windows:  79.0.3945.88

[vehicle.txt](https://github.com/handsontable/handsontable/files/4025340/vehicle.txt)

![img](https://user-images.githubusercontent.com/24875457/71807069-7a176980-3090-11ea-8d95-3e0a4d213f5a.png)

Thanks,
Abhay

**Comment by AMBudnik** [comment]
Hey Abhay,

You can use the [`afterGetColHeader` hook](https://handsontable.com/docs/7.3.0/Hooks.html#event:afterGetColHeader) to attach HTML to the header. Example https://jsfiddle.net/pfbueL6o/

Then you just attach the event for the class names is the header.
