### ISSUE TITLE
handsontable scrollBy

### ISSUE THREAD

**Issue by godshades** [handsontable/handsontable#6599]
Hi
How can I using scrollBy method to scroll inside handsontable

**Comment by godshades** [comment]
I'm trying using 
`$('#editTable').scrollTop += 100;`
But it return

> "function(e){return _(this,function(e,t,n){var r;if(x(e)?r=e:9===e.nodeType&&(r=e.defaultView),void 0===n)return r?r[i]:e[t];r?r.scrollTo(o?r.pageXOffset:n,o?n:r.pageYOffset):e[t]=n},t,e,arguments.length)}100"

**Comment by AMBudnik** [comment]
Hey @godshades 

the official API does not contain `scrollBy` method. If you are scrolling to a certain cell I can propose [`scrollViewportTo` method](https://handsontable.com/docs/7.3.0/Core.html#scrollViewportTo).

Here's https://jsfiddle.net/dmp15hk9/ a demo that scrolls the viewport to cell `100, 100` (which is the `CW101` content) after 2 seconds after loading the page.

**Comment by godshades** [comment]
@AMBudnik 
Hi, can I get last row number of current viewport

**Comment by AMBudnik** [comment]
The **getLastVisibleRow** should do the job. https://handsontable.com/docs/7.3.0/AutoRowSize.html#getLastVisibleRow
