### ISSUE TITLE
formulas is too slow

### ISSUE THREAD

**Issue by wg0120** [handsontable/handsontable#6607]
### Description

Formulas in handsontable is calc too slow and browser stop work when hansontable load more than 100 rows data.

### Your environment
* Handsontable version: 7.3
* Browser Name and version: chrome
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Hey @wg0120 

we are working on a new formula engine that in planned to work faster. We should get first results in Q1/2020. Stay tunned.
