### ISSUE TITLE
[svg] selection, fill and autoFill covers fixedBorder or frozen-border

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6628]
### Description

On 8.0.0-svg related PR's (#6594 & #6593) selection, fill and autoFill covers fixedBorder or frozen-border. Previous fixed border covers a most of objects. 
 On every image firs and second rows are fixed. 
`v. 7.3.0` https://jsfiddle.net/3fmhgjn5/
Fixed border beetween row 2 and row 3 cover selection, fill and autofil. It works like that on Excel on Google Spreadsheet.
![Screenshot 2020-01-10 at 17 05 35](https://user-images.githubusercontent.com/30186818/72167615-c08c0180-33cb-11ea-9cb8-734cd61a20a1.png)

`v 8.0.0.-svg` https://jsfiddle.net/sr61h4m3/1/
selection, fill and autofil covers fixed border. Even custom settings. 
![Screenshot 2020-01-10 at 17 04 50](https://user-images.githubusercontent.com/30186818/72167618-c255c500-33cb-11ea-8f5c-391fe202b71c.png)

### Excel
![Screenshot 2020-01-10 at 17 27 33](https://user-images.githubusercontent.com/30186818/72169244-08f8ee80-33cf-11ea-8522-dab3f1c07114.png)

### Google spreadsheet
![Screenshot 2020-01-10 at 17 28 47](https://user-images.githubusercontent.com/30186818/72169227-01d1e080-33cf-11ea-9fea-b862d289361d.png)

### Case 1
fixedRowsTop

### Case 2
fixedColumnLeft/frozen column

`v. 7.3.0`
![Screenshot 2020-01-10 at 17 34 05](https://user-images.githubusercontent.com/30186818/72169747-fd59f780-33cf-11ea-92b5-32253f4df710.png)

`v 8.0.0.-svg`
![Screenshot 2020-01-10 at 17 33 21](https://user-images.githubusercontent.com/30186818/72169756-05199c00-33d0-11ea-8597-40033e7cc50e.png)

### Case 3
fixedRowsBottom
row 98 is fixed
`v. 7.3.0`
![Screenshot 2020-01-10 at 17 35 09](https://user-images.githubusercontent.com/30186818/72169644-d00d4980-33cf-11ea-8cd3-430d73abf2fb.png)

`v 8.0.0.-svg`
![Screenshot 2020-01-10 at 17 34 52](https://user-images.githubusercontent.com/30186818/72169670-d8fe1b00-33cf-11ea-8ea4-007651a42eb2.png)

We have no assumptions, but due to the fact that our stable version, Excel and Google spreadsheet have a different order, I report it as regression.

**Comment by warpech** [comment]
Thank you @aninde for reporting. I think this is covered by https://github.com/handsontable/handsontable/issues/6639.

In the knowledge base, we have defined how borders overlap the "Frozen line": https://kb.handsontable.com/display/HAN/Borders. The same rule applies to "custom borders" and "selection borders".

**Comment by krzysztofspilka** [comment]
This is an issue reported for the SVG borders project, which was rejected and won't be implemented in Handsontable.
