### ISSUE TITLE
The `datePickerConfig` is inherited by other `date` type columns that are opened after the one with the `datePickerConfig` defined.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6636]
### Description

The `datePickerConfig` is inherited by other `date` type columns that are opened after the one with the `datePickerConfig` defined.

#### Case 1
**Open them one after another**
1. Open date picker for column `A`. You should see one month. Correct!
2. Open date picker for column `B`. You should see three months. Correct!
3. Open date picker for column `C`. You should see one month. **Incorrect!**

![GIF](https://user-images.githubusercontent.com/10757813/72323743-af801080-36a9-11ea-8a6b-0111b3276e41.gif)

#### Case 2
**Open them from right to left**
1. Open date picker for column `C`. You should see one month. Correct!
2. Open date picker for column `B`. You should see three months. Correct!
3. Open date picker for column `A`. You should see three months. **Incorrect!**

![GIF2](https://user-images.githubusercontent.com/10757813/72323775-c3c40d80-36a9-11ea-9558-ea7330472c78.gif)

#### Case 3
Described in https://github.com/handsontable/handsontable/issues/5757

### Additional information
* it happens the same if we add more columns. It seems that the config is kept until the cell gets a new one. 
* passing empty object as the `datePickerConfig` doesn't reset the settings https://jsfiddle.net/u74az1dh/. I guess that we are looking for a certain option in the config and then apply it.

### Demo

https://jsfiddle.net/f5w8vu2a/

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: Chrome 79
* Operating System: Windows 10

Inform [FORUM-4023](https://forum.handsontable.com/t/datepickerconfig-multiple-date-fields/4023/1)
Possibly related to https://github.com/handsontable/handsontable/issues/5757

**Comment by aninde** [comment]
This issue will be fixed by v10. 
Demo http://jsfiddle.net/c931oj4u/ v10

**Comment by AMBudnik** [comment]
True. Cases 1 and 2 are solved in v10
