### ISSUE TITLE
[svg] Introduce "Frozen line" to mark the edge of fixed rows/columns

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6639]
### Description

The SVG borders PR (https://github.com/handsontable/handsontable/pull/6157) contains a visual breaking change:

> When scrolling horizontally or vertically on the border fixed/frozen col/row, the line selection or right border of the selected cell if the border is bigger than 1 px.
> Check out demo https://codesandbox.io/s/gifted-noyce-hdvx5
> ![svg-stage2-6594-ff](https://user-images.githubusercontent.com/30186818/71974182-1cf6f180-3211-11ea-8724-b952d04e2b30.gif)

More details about that problem here by @aninde: https://github.com/handsontable/handsontable/pull/6594#issuecomment-572005899

---

@krzysztofspilka, @wojciechczerniak and I have discussed how to change the spec to fix the problem reported in https://github.com/handsontable/handsontable/pull/6594#issuecomment-572005899. 

Our conclusion is to introduce a new feature in this PR: "Frozen line" [1]. The borders (incl. custom borders and selection borders) will not be rendered on the frozen line, except for the parts of borders that are thicker than the frozen line [2].

This will be fixed within the SVG borders PR https://github.com/handsontable/handsontable/pull/6157.

Links to the updated specs:

- [1] https://kb.handsontable.com/display/HAN/Frozen+line
- [2] https://kb.handsontable.com/display/HAN/Borders ([change highlight](https://kb.handsontable.com/pages/diffpagesbyversion.action?pageId=22053066&selectedPageVersions=9&selectedPageVersions=8))

🚨 This is a (Visual) breaking change

**Comment by aninde** [comment]
A naive question to be 100% sure of your requirements. @warpech  is frozen = fixed?

**Comment by warpech** [comment]
I have an implementation that I will soon push to the PR. However, one change was proposed and I will decide if I can make it in 8.0.0: https://github.com/handsontable/handsontable/issues/6651

**Comment by warpech** [comment]
Implemented in PR https://github.com/handsontable/handsontable/pull/6157 (commit 7cad0e687e509f72f94f9d56bc1fe144dce8e5e4). The task #6651 will be done at some other time.

**Comment by warpech** [comment]
Closing as the SVG PR was closed. Explanation in https://github.com/handsontable/handsontable/pull/6157#issuecomment-1012200057
