### ISSUE TITLE
with fixedColumnsLeft , collapsibleColumns don't work

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#6640]
### Description
when i freeze the first two columns with fixedColumnsLeft: 2 ,
and i use also  Collapsible Columns for the two same columns, the icon collapsible don't appear

### Steps to reproduce
https://jsfiddle.net/jeanmarc/3odc4w91/9/

if i remove fixedColumnsLeft: 2 it works

### Demo

https://jsfiddle.net/jeanmarc/3odc4w91/9/

### Your environment
* Handsontable version: PRO  7.3.0
* Browser Name and version: Chrome 79
* Operating System: WINDOWS 10

**Comment by AMBudnik** [comment]
Hey @jeanmarc78 

Please follow this topic for updates https://github.com/handsontable/handsontable/issues/5290
