### ISSUE TITLE
with hidden column , collapsibleColumns don't work well

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#6641]
### Description
A hidden column appears after collapse/ expand header column

### Steps to reproduce

1.I collapse the column "I"
2.if i expand the column "I" , the Hidden column O appears

### Demo

https://jsfiddle.net/jeanmarc/3odc4w91/11/

### Your environment
* Handsontable version:PRO 7.3.0
* Browser Name and version:Chrome 79
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
This issue should be fixed after adding the hiddenColumns to the index mapper.
@aninde what do you think?

**Comment by aninde** [comment]
@AMBudnik thanks for your vigilance. I will add it to the list of issues tested during testing of new hidden columns and check it out when PR's will be ready.

**Comment by wojciechczerniak** [comment]
Duplicate of #6879
