### ISSUE TITLE
I cannot access older version Handsontable 

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#6643]
### Description
i go to https://handsontable.com/docs/4.0.0/demo-filtering.html

![image](https://user-images.githubusercontent.com/11042160/72439894-1a177600-37a8-11ea-8fcd-69492f58116c.png)

if i click to "edit jsfiddle"
i have the error
![image](https://user-images.githubusercontent.com/11042160/72439982-4a5f1480-37a8-11ea-98f0-a4d900513ec0.png)

### Your environment
* Handsontable version: 4.0.0
* Browser Name and version: Chrome 71
* Operating System:Windows 10

**Comment by wojciechczerniak** [comment]
Look like a JSFiddle temporary issue. Can you try again?

**Comment by jeanmarc78** [comment]
hello,
it's not temporary but i choose a newer version
https://handsontable.com/docs/6.2.2/demo-filtering.html
it works

regards
jm

**Comment by AMBudnik** [comment]
That's a JSFiddle issue, I've reported it yesterday https://github.com/jsfiddle/jsfiddle-issues/issues/1522
