### ISSUE TITLE
How can we change a specific row property in handsontable?

### ISSUE THREAD

**Issue by sach127** [handsontable/handsontable#6645]
### Description

I want keep all the cells of the handsontable readOnly initilly. At the end of each row want add an edit botton on clicking on which a user should get edit access for that specific row.
i tried using setCellMeta event but, i am getting below error everytime i use it,
**Cannot read property 'setCellMeta' of undefined**

Can anyone please suggest me how can i implement this requirment in TypeScript
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey @sach127 

there are a couple of ways to do this, my favorite is the `cells` method. Here is how it works https://jsfiddle.net/sqhvwduf/
