### ISSUE TITLE
Copy/paste functionality for cells with array values

### ISSUE THREAD

**Issue by JanVanRyswyck** [handsontable/handsontable#6649]
### Description
We have a scenario with several columns where the cells contain an array of numbers (IDs). For these cells we've created a custom multi-select editor. The issue that we're experiencing is that the copy/paste functionality (CTRL+C/CTRL+V) provided by the built-in plugin doesn't seem to work with a value containing an array. 

### Steps to reproduce

1. Open the demo (see below).
2. Select the first cell of the first row (containing the comma-separated values).
3. Press CTRL+C or CMD+C
4. Select the first cell of the second row.
5. Press CTRL+V or CMD+V

=> The values of the first cell are not copied to the second cell. Performing the same for cells of the second or third column does work as expected.

### Demo
https://codesandbox.io/s/copypaste-array-values-ee5jz

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by wojciechczerniak** [comment]
The clipboard content is always kept as a string, this is a limitation of web browsers. We have an access to `text/plain` and `text/HTML` mime types.

We could create our own clipboard in memory, but what if you would want to copy & paste to a different Handsontable instance on another page or browser tab? I think that the best approach here would be to pre-process strings with `beforePaste` hook.

You can parse the value on your own. Kind of pre-processing:
https://codesandbox.io/s/copypaste-array-values-qy3fk

**Comment by JanVanRyswyck** [comment]
@wojciechczerniak I can't seem to find a beforePaste hook in your example.

**Comment by wojciechczerniak** [comment]
Sorry, I forgot to save. It should be fixed now.

```ts
        beforePaste: (data, coords) => {
          data[0][0] = data[0][0].split(',');
        }
```

**Comment by JanVanRyswyck** [comment]
Thanks. I'll give it try.

**Comment by JanVanRyswyck** [comment]
That seems to do the trick. Thanks.
