### ISSUE TITLE
Ctrl+D should work similar to Excel

### ISSUE THREAD

**Issue by singhalavi** [handsontable/handsontable#665]
it should copy the first column data to selected cells.

**Comment by ericremoreynolds** [comment]
+1

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
Video example:

![ctrl d](https://cloud.githubusercontent.com/assets/10757813/21449688/4433bc52-c8f0-11e6-91bd-4702502cf9e4.gif)

**Comment by AMBudnik** [comment]
Hi All.

We are moving feature ideas and improvements to Github Discussions to gather all the ideas on UI and API. That will help us to continue the development of the functionality in the future.

Please feel welcome to share your feedback via the Github Discussions panel if you have any additional ideas.
