### ISSUE TITLE
Change priority of selection borders on the frozen line

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6651]
In https://github.com/handsontable/handsontable/pull/6157, the relation between the frozen line and any kind of border is implemented according to the following spec, tracked in #6639:

> ### Edges with the frozen line
> 
> We do not render the part of a border that overlaps with a freeze line. However, if the width of the border is bigger than 1, we render the part of the border that bleeds on the other side of the freeze line.

However, today @wojciechczerniak and @krzysztofspilka suggested that this gives a bad UI experience, and it would be better if we added a sesne of depth. That means a cell selection should be rendered:

- above the frozen line, when the selection is on an overlay with a higher z-index
- behind the frozen line, when the selection is on an overlay with a lower z-index

The request is only about selection borders. Custom borders should always have a lower priority than the frozen line.

Suggested change to the spec:

> ### Edges with the frozen line
> 
> #### Custom borders
> We do not render the part of a custom border that is on the freeze line. However, if the width of the custom border is bigger than 1, we render the part of the custom border that bleeds on the other side of the freeze line.
> 
> #### Selection borders
> For selections made on a pane that is lower in the visual hierarchy, we do not render the part of a selection border that is on the freeze line. 
> 
> For selections made on a pane that is higher in the visual hierarchy, we render the part of a selection border that is on the freeze line.

This is proposed outside of scope for 8.0.0.

**Comment by warpech** [comment]
Some prestudy is on the branch https://github.com/handsontable/handsontable/tree/feature/issue-6064-frozen-line4, but it won't be finished for 8.0.0.

**Comment by warpech** [comment]
Question to product manager. Should the header edge act the same way as the frozen line? That means:

- custom borders do not cover the header edge
- selections cover the header edge

The header edge is still somehow different than the frozen line, in regard that it has the color of the gridline. But I think that this is fine.

Currently in 8.0.0 candidate (after https://github.com/handsontable/handsontable/issues/6639 in https://github.com/handsontable/handsontable/pull/6157), it is like that, but it is not officially specified.

In 7.x, both custom borders and selections covered the header edge.

@krzysztofspilka

**Comment by krzysztofspilka** [comment]
@warpech by "edge lines" you meant "right borderline of the row header and bottom borderline of the column header", right? If so, then the behavior described above is correct.

Just please double-check if this works fine when headers are not enabled. I'm asking about this because we represent the mixed approach and other, well-known online software may work differently.

![Screen Shot 2020-01-28 at 12 35 42](https://user-images.githubusercontent.com/8048526/73260686-b723d700-41ca-11ea-9332-a4c717f65386.png)

**Comment by warpech** [comment]
Today this was confirmed by us in person. I have updated the KB pages:

-  https://kb.handsontable.com/display/HAN/Visual+priority
-  https://kb.handsontable.com/display/HAN/Borders

**Comment by warpech** [comment]
The frozen line will also get a new color. The page https://kb.handsontable.com/display/HAN/Frozen+line is updated with the new color value.

**Comment by warpech** [comment]
Implemented in 59b71c2942e0784f961a31d7448900bda23f9aa6 as part of the SVG borders PR #6157.
