### ISSUE TITLE
Row header width changes when adding a child row.

### ISSUE THREAD

**Issue by samueljTRQ** [handsontable/handsontable#6658]
### Description
I am using stretchH option and I am setting a fixed width for row headers. But the width of row header width changes when adding a child row(By clicking the Add Child(>) button).

### Steps to reproduce
1. Set rowHeaderWidth to 30.
2. Set stretchH config as all.
3. Once page is loaded, Click on Add Child(>) button.
4. Now look at the row header width. It will be increased.

### Demo
https://stackblitz.com/edit/angular-hot-issues

### Your environment
* Handsontable version: 7.2
* Browser Name and version: Chrome v78.0
* Operating System: Windows 7 X64

I have created this same issue before some time, You have closed it since I didn't reply for you query.
Hence I am creating this new issue. Please don't close this ticket as duplicate. I will follow this promptly.
https://github.com/handsontable/handsontable/issues/6578#issue-539062990
https://github.com/handsontable/handsontable/issues/6527#issue-532640254

**Comment by AMBudnik** [comment]
Hi @samueljTRQ 

I can see that you are working on DOM elements. Try to use Handsontable API to do the same. You can use [cells](https://handsontable.com/docs/7.3.0/Options.html#cells) method to manage classes.

**Comment by AMBudnik** [comment]
> now I can see the row header width increasing when I select add child from the context menu and reverts to original width when I click add row.

Can you record it?

**Comment by samueljTRQ** [comment]
![captured](https://user-images.githubusercontent.com/49991045/73059708-4c1d8c00-3ebc-11ea-9b2d-4ff399cd6401.gif)

**Comment by AMBudnik** [comment]
Thank you for the video.

The header of a row widest when you add new rows. It also happens in the official demo https://handsontable.com/docs/7.3.0/demo-nested-rows.html
