### ISSUE TITLE
Why is my Handsontable custom cell renderer only working for the first row when hiddenColumns and colWidths is set?

### ISSUE THREAD

**Issue by Joshua-W-Adams** [handsontable/handsontable#6659]
### Description
I have the following handsontable configured:

```ts
var container = document.getElementById('example1'),
    hot;

var data = [];

for (var i = 0; i < 100; i++) {
 data.push({"id": 1, "rgba": "204,255,204,1"});
}

function callback (row, column, prop) {
  const cellProperties = {};
  cellProperties.renderer = renderer;
  return cellProperties;
}

function renderer (instance, td, row, col, prop, value, cellProperties) {
  Handsontable.renderers.TextRenderer.apply(this, arguments);
  var rdata = instance.getSourceDataAtRow(row);
  var colour = rdata.rgba;
  td.style.backgroundColor = 'rgba(' + colour + ')';
}

hot = new Handsontable(container, {
  data: data
  , cells: callback

  // adding either of these in isolation allows the rendering to continue working. However adding both together causes only the top row to render correctly.
  , hiddenColumns: true
  , colWidths: 150
});  
```

The problem I am encountering is my custom renderer is designed to set the background colours of each handsontable row based on the value in the rgba column. Which works fine initially.

However, when both the hiddenColumns: true and colWidths: 150 (or any number) properties are introduced, it causes an issue whereby only the top row of the handsontable will render correctly.

But adding either of these properties in isolation lets the rendering work correctly.

So does anyone know why this is occurring and how to fix it?
### Steps to reproduce
See above.

### Demo
https://jsfiddle.net/JoshAdams/sgLm5ev2/

### Your environment
* Handsontable version: 1.18.1
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hey @Joshua-W-Adams 

it relates to data, which is define as an empty array at the beginning. You can use `render()` method to force Handsontable to recalculate number of rows.

https://jsfiddle.net/ndep6khc/ (line `37`)

**Comment by Joshua-W-Adams** [comment]
Hey @AMBudnik 

The data array is not defined as empty orginally, there is a block of code that pushes data to the array sychronously before it is set to the handsontable....

for (var i = 0; i < 100; i++) {
 data.push({"id": 1, "rgba": "204,255,204,1"});
}

Also while calling the render() method may work at setting the colours, this is not really a great solution as it adds un-necessary additional renders to the handsontable when it loads, i.e. instead of rendering once, it now renders twice. This can be a massive performance cost on larger handsontables, which is the case that I have in production.

Any other ideas on whats causing the problem?

Thanks for the help :)

Josh

**Comment by AMBudnik** [comment]
If we change

> td.style.backgroundColor = 'rgba(' + colour + ')';

to defining color via `className` in the `cells` method https://jsfiddle.net/xrjdemLa/

When you use `getSourceDataAtRow` you cannot call it on the initialization as the data hasn't been loaded yet. I guess that a renderer is a must in this case, but @pnowak please correct me if I'm wrong. Maybe there's something I'm missing.

**Comment by pnowak** [comment]
If the renderer is defined as `columns` in hot settings - https://jsfiddle.net/62La4e0f/ - no additional render needed.

So I think `cellProperties` in `calback` isn't a well defined because the cell properties need to be given `row, col, prop` coordinates.

**Comment by Joshua-W-Adams** [comment]
@AMBudnik Thanks for the class name suggestion, but in this case its not really ideal, as the rgba codes are defined in a database and the intention is to let uses set whatever rgba code they want in the database then have this colour displayed in the front end. With this solution I would have to make a class name for every rgba code combination (255x255x255 = 16581375!) so its not ideal.

@pnowak ok, well adding renderings with columns work as intended. I guess i'll rewrite the rendering module in my application to bet set at the column level as opposed to the cell level. Is this the best way to set renderers to ensure maximum compatibility with the handsontable library?

**Comment by pnowak** [comment]
If you want to attach renderer to a particular column the `column` settings is the best.
And if you want to append renderer to specific cells, you use `cells` settings and inside it determine `row` and `col`.
But when you want renderer to the whole table, you should use `renderer: myRenderer,`.
