### ISSUE TITLE
Txt area comments - display issues on Firefox

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6661]
### Description
Sometimes the text area of the comment disappears moment after displaying.

Maybe this is related with fixed columns/rows or browser. I'll investigate it later. 
This can be adequate to https://github.com/handsontable/handsontable/issues/6519

### Steps to reproduce
1. Open demo on Firefox https://codesandbox.io/s/gallant-wildflower-41mni
2. Select cell A1 and add comment by contextMenu
![comment-ff](https://user-images.githubusercontent.com/30186818/72997790-1bc2e880-3dfd-11ea-97ae-c017a052cd17.gif)

It cannot be reproduced on version 2.0

### Demo

https://codesandbox.io/s/gallant-wildflower-41mni

### Your environment
* Handsontable version: 3+
* Browser Name and version: Firefox 72
* Operating System: macOs Catalina 10.15

**Comment by aninde** [comment]
This bug occurs also with Angular wrapper.

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 https://codesandbox.io/s/crazy-cerf-08tjz works well on my macOS Catalina 10.15.3 on Firefox 79 and Chrome 84.0.4147.135. But it breaks on Firefox 80.

**Comment by AMBudnik** [comment]
Now it does not work for me on Chrome 85 and Handsontable 8.1.0

**Comment by aninde** [comment]
This issue is fixed on the upcoming v11.1.0 https://jsfiddle.net/vhzedyrn/.

**Comment by AMBudnik** [comment]
Issue fixed in Handsontable v11.1.0
