### ISSUE TITLE
Lostfocus works incorrectly for header inputs (filters)

### ISSUE THREAD

**Issue by Astimus** [handsontable/handsontable#6663]
1. Click input in header
2. Click next to the table
![image](https://user-images.githubusercontent.com/7124116/73158302-7e193300-40f4-11ea-8002-c1ea37a5a902.png)
3. Cursor disappeared but focus remained on the input header
![image](https://user-images.githubusercontent.com/7124116/73158414-ca647300-40f4-11ea-829b-6b39d896ac01.png)
4. Input should lose focus

### Demo
https://1drv.ms/u/s!ApG7TdB4GolFgdVILYQoqKFL_EDhsg?e=hvM8c3

### Environment
* Handsontable version: 1.18.1
* Browser Name and version: Chrome 79.0.3945.117 (64 bit)
* Operating System: Windwos 10

**Comment by AMBudnik** [comment]
Thank you for sharing @Astimus 

That is our official demo https://handsontable.com/docs/7.3.0/demo-filtering.html
It works the same using `7.3.0`.

**Comment by AMBudnik** [comment]
This issue in not replicable on `7.4.2` https://handsontable.com/docs/7.4.2/demo-filtering.html

I'm closed it as **solved**. If you'd have any similiar issue please let me know @Astimus
