### ISSUE TITLE
[svg] Loss of selection border during scroling when fixed rows are enabled

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6665]
### Description
Sometimes top border of area.highlight is loss during scrolling. 
Related to or even Case 2 of  https://github.com/handsontable/handsontable/issues/6646

![loss-selection-border-ff](https://user-images.githubusercontent.com/30186818/73174423-ff2df580-4107-11ea-8894-8589c195f024.gif)

### Steps to reproduce

1. Open demo (edited) https://codesandbox.io/s/happy-sanderson-1wkoh
2. Select by rows 3,4, 5 and 5 by clicking on rowHeader. 
3. Scroll it horizontally **using magic trackpad** to the end, then back and forth.

#### Actual result
 Top selection border area.highlight vanishes

#### Expected result
All borders should be visible. 

### Demo
EDIT: Update
https://codesandbox.io/s/happy-sanderson-1wkoh

### Your environment
* Handsontable version: 8.0.0-svg
* Browser Name and version: any
* Operating System: macOS

**Comment by budnix** [comment]
It's worth to mention that the same happens for the bottom overlay.

![Kapture 2020-01-27 at 13 48 35](https://user-images.githubusercontent.com/571316/73176025-c4c65780-410b-11ea-89af-1f0b5a851011.gif)

**Comment by warpech** [comment]
I managed to reproduce locally. Any kind of scrolling works for reproduction, but there must be zero fixed columns and more than 1 fixed row.

**Comment by pnowak** [comment]
This issue isn't a replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/yhwztvnx/

**Comment by AMBudnik** [comment]
Great news @pnowak if it's solved we can close it.

**Comment by warpech** [comment]
As the OP says, the problem only exists on the SVG branch and still needs to be fixed there.

**Comment by krzysztofspilka** [comment]
This is an issue reported for the SVG borders project, which was rejected and won't be implemented in Handsontable.
