### ISSUE TITLE
[svg] Support for Bootstrap

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6666]
### Description
Looks like we lost Bootstrap compatibility with after changes on SVG branch. 
After adding Bootstrap customBorders, fixed/frozem rows and columns split up. 

Our documentation says that we support [bootstrap](https://handsontable.com/docs/7.3.0/tutorial-bootstrap.html)

#### Case 1
Moved customBorders + moved fixed columns. 
https://codesandbox.io/s/bootstrap-800-svg-o6j1m

#### Case 2 
~https://codesandbox.io/s/bootstrap-800-svg-je9wr~
Uncomment `width` and `height` in demo
~The table moves and does not position correctly relative to headers~ the shift occurred only yesterday. This case is now out of date.
![Screenshot 2020-01-27 at 14 12 53](https://user-images.githubusercontent.com/30186818/73177418-41a70080-410f-11ea-9e11-d6ac763eb523.png)

#### Case 3
EDIT: https://codesandbox.io/s/botstrap-svg-sipyu new demo with Bootstrap 
there is no moved table, but columns, selection and autofill are still on wrong places 
![Screenshot 2020-01-28 at 13 24 10](https://user-images.githubusercontent.com/30186818/73263806-afb3fc00-41d1-11ea-96d2-21b95ffd8ced.png)
![Screenshot 2020-01-28 at 13 24 03](https://user-images.githubusercontent.com/30186818/73263809-b0e52900-41d1-11ea-929f-07ded6e8cf6b.png)

### Demo
https://codesandbox.io/s/bootstrap-800-svg-je9wr

### Your environment
* Handsontable version: 8.0.0-svg
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
Bug with the table shift bug out of date, it appeared yesterday, no longer appears on the demo built by codesandbox bot today.

**Comment by aninde** [comment]
A change to the sandbox version indicates that these problems have always been present. Unless I messed up in HTML file.

**Comment by warpech** [comment]
I agree, I can reproduce the same problems with 7.22 and 7.3.0

**Comment by warpech** [comment]
> This is an issue reported for the SVG borders project, which was rejected and won't be implemented in Handsontable.

This is the same message that was used to close other projects related to the abandoned PR https://github.com/handsontable/handsontable/pull/6157
