### ISSUE TITLE
Column hiding issue after columns moved manually

### ISSUE THREAD

**Issue by sravan8519** [handsontable/handsontable#6668]
### Description
When I hide a column after columns are re-ordered manually (columns moved manually), then It is hiding the previous column, which was loaded initially.

Initial Columns : A,B,C,D,E,F,G,H,I,J,K,L
after re-order : B,C,D,A,E,F,G,H,I,J,K,L
Now I am trying to hide column 'B', then it is hiding column 'A'. and column 'B' data is not visible.
Not able to unhide column 'A'

### Steps to reproduce
1. Manually move the column position (From column 'A' to index 3 then columns looks like B,C,D,A,E,F,G,H,I,J,K,L).
2. Hide column 'B'.
3. Column 'A' will be hidden and column 'B' data is not visible and not able to unhide column 'A'

### Demo

https://jsfiddle.net/aq0Lsgf9/

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: Chrome and 78.0.3904.87
* Operating System: windows 7
![column_hiding](https://user-images.githubusercontent.com/30467792/73178384-218b3780-4137-11ea-95d3-f76acc2eb781.gif)

**Comment by pnowak** [comment]
Thank you for the report. 

This issue should be fixed after adding the hiddenColumns to the index mapper - https://github.com/handsontable/handsontable/pull/6547
So we should add to our checklist - https://github.com/handsontable/handsontable/issues/6178. @aninde what do you think?

**Comment by aninde** [comment]
@pnowak thank you. I added it to our list.

**Comment by pnowak** [comment]
7.4.2 https://jsfiddle.net/f15Lsy6t/ (broken)
8.0.0.-beta1 https://jsfiddle.net/0mfqor4b/ (broken)
8.0.0.-beta2-rev2 https://jsfiddle.net/L135e6ps/ (**issue solved**)

<img width="607" alt="Zrzut ekranu 2020-05-8 o 13 25 46" src="https://user-images.githubusercontent.com/1555809/81401447-a2db6880-912f-11ea-86ca-c16ea2502335.png">

**Comment by pnowak** [comment]
Hi @sravan8519 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment]
Hi @sravan8519 

We've just released Handsobtable v 8.0.0. When this issue is solved. Here's an updated demo https://jsfiddle.net/a6e1mtxk/

![Uploading Zrzut ekranu 2020-08-6 o 11.58.18.png…]()
