### ISSUE TITLE
Headers are deselected after undoing removing

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6670]
### Description
After undoing removing or deleting we lose selection on headers and can't select header again.

### Steps to reproduce

1. Open demo https://codesandbox.io/s/hiddenrows-pv1mg
2. Select one header.
3. Click <kbd>DELETE</kbd>
3. Undo by <kbd>cmd/ctrl</kdb> + <kdb>z</kdb>

#### Case 1
colHeaders
![col-headers](https://user-images.githubusercontent.com/30186818/73187266-6efcaa00-4121-11ea-8d1d-0c9bbe65cdd3.gif)

#### Case 2
rowHeaders 
![row-headers](https://user-images.githubusercontent.com/30186818/73187270-70c66d80-4121-11ea-9c3f-665b4ce54b5d.gif)

### Demo
 

https://codesandbox.io/s/hiddenrows-pv1mg

### Your environment
* Handsontable version: 7+, 8.0.0-beta
* Browser Name and version: any
* Operating System: macOS

**Comment by AMBudnik** [comment]
@aninde Case 1 works for me on `rev21` Chrome 83 https://jsfiddle.net/w61Lygrs/3/ as well as case 2 https://jsfiddle.net/w61Lygrs/4/

**Comment by aninde** [comment]
This issue is solved by `8.0.0-beta2-rev21`. Works also on Edge 81, Firefox 78, and Safari 13/ macOS.

**Comment by AMBudnik** [comment]
Issue solved in Handsontable 8.0.0.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
