### ISSUE TITLE
[svg] selection flickers when autofill is on last column

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6671]
### Description
When we select the last column the autofill corner in the previous version is shifted so that it does not affect the table viewport and no horizontal scrollbar appears. It produces funny glitches

7.3.0
![7 3 0](https://user-images.githubusercontent.com/571316/73069184-5dab6780-3ead-11ea-805c-c0790f738be6.png)

PR
<img width="80" alt="PR" src="https://user-images.githubusercontent.com/571316/73069191-6439df00-3ead-11ea-9e2c-f25993bb05d6.png">

Found by playing with stretching demo https://handsontable.com/docs/7.3.0/demo-stretching.html

It produces funny glitches
![Kapture 2020-01-24 at 13 31 13](https://user-images.githubusercontent.com/571316/73069391-e6c29e80-3ead-11ea-9f6a-43655b8fac37.gif)

### Demo
https://jsfiddle.net/aninde/Ltsa21p9/ - 8.0.0-svg

### Your environment

Handsontable version: 8.0.0-svg
Browser Name and version: any
Operating System: any

_Originally posted by @budnix in https://github.com/handsontable/handsontable/pull/6157#issuecomment-578111454_

**Comment by warpech** [comment]
Fixed in 59b71c2942e0784f961a31d7448900bda23f9aa6, as part of the SVG borders PR (#6157).

**Comment by krzysztofspilka** [comment]
This is an issue reported for the SVG borders project, which was rejected by us.
