### ISSUE TITLE
Remove `debug` key (key, css, docs)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6672]
### Description

Adding  `debug: true` doesn't allow us to build an instance. We get an error issue that stops the table from appearing.
![image](https://user-images.githubusercontent.com/10757813/73251393-2e506f80-41b9-11ea-87fa-a1d0328d946a.png)

### Steps to reproduce

1. Just open the demo - it's ok
2. Change the version to 7.1.1 - it doesn't load

### Demo

https://codesandbox.io/s/debug-true-bug-fjhlz 7.1.0 (working)

### Your environment
* Handsontable version: [7.1.1+](https://handsontable.com/docs/7.1.1/tutorial-release-notes.html)
* Browser Name and version: Chrome 79
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
`debug` was for us. Currently, it is not a supported option and we're in the process of removing it.

**Comment by AMBudnik** [comment]
OK, so let's rename it.

**Comment by aninde** [comment]
Work with `8.0.0-beta.2` https://codesandbox.io/embed/debug-true-bug-unsbn?codemirror=1.

**Comment by AMBudnik** [comment]
Debug removed

![Zrzut ekranu 2020-08-7 o 10 55 51](https://user-images.githubusercontent.com/10757813/89628443-971d5080-d89c-11ea-8cbe-b858023c64f5.png)

we can call it solved for v 8.
