### ISSUE TITLE
[8.0.0-beta.1] Massive init improvement on huge table 

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#6676]
👋 👋 

I'm currently working on a table with ~60k rows and 9 columns and wanted to share a huge improvement I kinda stumbled across.

I noticed that after I had received all my records via ajax that it was taking a _very_ long time to initialize my HoT table so I opened the Chrome performance tab and looked into where the bottlenecks could be. 

The vast majority of the problem was in the `autoColumnSize` plugin. The docs *clearly* state that this plugin can degrade performance, so that wasn't a huge surprise to me.

The before:

![Screen Shot 2020-01-30 at 2 42 43 PM](https://user-images.githubusercontent.com/881931/73489067-9cd72e00-436f-11ea-9984-5c5e56689630.jpg)

Around 7700 ms

I couldn't just turn it off because our users expect the functionality, but I also needed to figure out a way to short-circuit it if at all possible. 

What I came up with was a tiny plugin that turns off `autoColumnSize` if there are manual column sizes stored in localStorage. Because if we already have the sizes from localStorage, there's no sense wasting all the time to calculate them again.

AND, the plugin stores the auto-calculated sizes in localStorage after the first calculation, so next time we get the benefit.

Here is the after:

![Screen Shot 2020-01-30 at 2 40 54 PM](https://user-images.githubusercontent.com/881931/73489419-2a1a8280-4370-11ea-80a7-3bbb477025b2.jpg)

Under 400 ms.

And the columns are still sized correctly! Obviously this is a massive win.

Here's the plugin: 

```js
import PluginFactory from './plugin-factory';

let SkipAutoSizing = PluginFactory('skipAutoSizing');

SkipAutoSizing.prototype.enable = function () {
    this.columnWidthsStored = false;

    this.enableAutoColumnSizeIfNeeded();

    this.hot.addHookOnce('afterRender', this.storeAutoSizedColumns.bind(this));
}

SkipAutoSizing.prototype.enableAutoColumnSizeIfNeeded = function () {
    let columns = this.hot.getPlugin('persistentState').storage.loadValue('manualColumnWidths');

    this.columnWidthsStored = columns && columns.length;

    // The column widths were not stored, so we'll need
    // to enable the autoColumnSize plugin.
    if (!this.columnWidthsStored) {
        this.hot.getPlugin('autoColumnSize').enablePlugin();
    }
}

SkipAutoSizing.prototype.storeAutoSizedColumns = function () {
    // They were already stored, no need to store them again.
    if (this.columnWidthsStored) {
        return;
    }

    let widths = [];
    for (let c = 0; c < this.hot.countCols(); c++) {
        widths.push(this.hot.getColWidth(c));
    }

    // Put them in localstorage for the next page reload.
    this.hot.getPlugin('persistentState').storage.saveValue('manualColumnWidths', widths);
}


export default SkipAutoSizing;
```

I think the stock `autoColumnResize` plugin could be updated to check to see if there are already manual column sizes stored. This might improve the out-of-the-box user experience. 

Hopefully that's helpful to someone.

**Comment by AMBudnik** [comment]
Thank you for sharing the tips, Aaron.

That could actually work. I had a really quick chat with a developer and he told me that if columns data won't change it's already a working solution, but if they change we'd need to track (maybe in the cell meta) what column should be recalculated.

**Comment by aarondfrancis** [comment]
Thanks for the response @AMBudnik!

I'll maybe clarify just a tiny bit. If manual column widths are stored, that means that the user has explicitly decided what width a particular column should be. No amount of data changing should override what the user has explicitly set, so I think the default autoSizing plugin should respect that. In fact, I think manualColumn sizes _already_ override autoSizing sizes, so all that's really happening is a bunch of wasted cycles calculating auto sizes which are then thrown away.

What I _don't_ think the default autoSizing plugin should do is store auto-sized widths as if they were manually set. That seems too aggressive for an out-of-the-box feature, I'm just doing that in my plugin because it makes sense for our application.

Hope that helps!

**Comment by AMBudnik** [comment]
> Hope that helps!

I think it will. At this point, you are far above a standard Handsontable user so each finding is precious.

**Comment by texas697** [comment]
@aarondfrancis so you are saying that even with manual column sizes it is still using the built in autosizer?
If so how do I use your plugin?

**Comment by aarondfrancis** [comment]
@texas697 from what I've seen, yes. It will calculate auto sizes and _then_ apply manual sizes, wiping out the calculated sizes and wasting a bunch of time.

You can see my plugin skeleton at https://github.com/handsontable/handsontable-skeleton/issues/6

Also, 👋 from up here in Dallas!

**Comment by texas697** [comment]
@aarondfrancis 
got it working! appreciate it
