### ISSUE TITLE
If freezing column is multiple lines, row height does not match

### ISSUE THREAD

**Issue by ikeryo1182** [handsontable/handsontable#6677]
### Description

if there is freezing column which is multiple line, row height does not match to freezing column.

![12d688ba9bd826c49d500b59dc66b796](https://user-images.githubusercontent.com/29964919/73512837-82b05500-442e-11ea-9aad-739825332b3a.gif)

### Steps to reproduce

1. Prepare two or more rows and many columns, and then make some column freezing.
2. Enter mulitple lines text to the second or later row of freezing column.
3. Scroll a lot to the right.

### Demo

https://handsontable.com/docs/7.3.0/demo-fixing.html
It is the same settings with the above

### Your environment
* Handsontable version: 7.2.0,
* Browser Name and version: Chrome  79.0.3945.130
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Hey @ikeryo1182 

please add [autoRowSize: true](https://handsontable.com/docs/7.3.0/Options.html#autoRowSize) to your instance settings and let me know if it solves the issue.

**Comment by ikeryo1182** [comment]
It seems fixed. Thanks.
