### ISSUE TITLE
Need a way to update source data in filtered state

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#6680]
### Feature Request

Some way to modify the _source data_, equivalent to `populateFromArray()` and `setDataAtCell()` but against source data, not visual data, and reliably redraw the table to match the source data (with any current sort, filter, nested row state, etc).

I've brought this up in a few other threads, but I'm finally logging it as it's own issue because it's something I need a solution to. It takes some explaining...

### Context
One of the breaking changes in 8.0.0 is:

> Modifying the table’s data by reference and calling `render()` will not work as it used to anymore. From this point onward, all the data-related operations need to be performed using the API methods, such as `populateFromArray` or `setDataAtCell`.

This makes sense. Unfortunately, my app currently relies quite heavily on "modifying the table's data by reference and calling `render()`" (for reasons explained below), so I need to refactor this, and I've run into some problems.

My app's data management is like this:
1. JSON data is initially loaded from the server in pages (can be 100k+ rows worth of data when all done)
2. JSON data is stored locally (using Redux store)
3. Redux store data is rendered by views (mostly in React)
4. When data is changed by user input: Redux store is updated by replacing immutable data, then views redraw
5. When data is changed by other users in the system: data is pushed to clients using websocket, Redux store is updated by replacing immutable data, views redraw (same as 4)

Handsontable is a unique kind of view:
1. Redux store data has to be transformed into Table data (rows with column keys)
2. Table stores data internally and mutates it based on user input
3. User changes in the Table need to be synced to the outside immutable data in Redux store (and sent as API requests for persistence and other users)
4. When the Redux store data changes from the outside, Table data needs to be synced and the table redrawn, but ignore Redux store changes that are already present in the Table (ie don't react to the user's own edits in the table)

### Problem

The "React way" to do this would be to memoize the transformation of Redux store data to Table data, something like:
```
memoizedTableData = memoize(storeDate => storeDataToTableData(storeDate));

<HotTable data={ memoizedTableData(storeData) }>
```
Such that `<HotTable>`'s `data` prop is only updated (and internally `hot.updateSettings({ data })` is called) if the `storeData` has been changed. I could even narrow this down to memoize individual rows. Unfortunately, this kills Table performance since the entire table data is updated for even a single change, and it messes with some of the Table's internal state. This is not a usable solution.

The suggested solution is to use `populateFromArray()` and `setDataAtCell()` (and `alter()`?) to apply external changes from the Redux store to the Table data. The problem with these functions is that they can only update _visible data_, if I understand correctly.

This creates some problems, each of which I would love some feedback:
1. First of all, I have to translate the source data location to visual data location... I think `toVisualRow()` and `toVisualColumn()` are all I need here, but it isn't entirely clear when nested rows are in use.
2. If the source data is currently filtered out, there's no way to update it.
3. If a row is added while table is sorted or filtered, there's no way to control where in the source data the row should be, so removing the sort will show the row in the wrong place.
4. If a row is moved while table is sorted or filtered, same problem as 3.

For this reason I think I need source versions of these functions:
- `populateSourceFromArray()`
- `setSourceDataAtCell()`
- `alterSource()`

Which would modify the source data and make the expected visual changes.

Even better would be a reconciliation function so I don't have to figure out what changed from the outside:
```
hot.updateSourceData(newSourceData) // only updates source and visual data that changed using strict equality checks
```

### Pre-8.0 solution
In 7.x I was able to solve the problems listed above by:
1. Initially transform the Redux store data into Table data
2. When Redux store changes I compare to the Table data
3. Directly mutate the Table data by reference for just what changed, call `render()` (with some caveats, especially with nested rows)

### Possible workaround after 8.0
I have not yet tried this, but this may be a workaround:
1. Given previous and next source data, translate to visual data
2. If visual data is present, update it
3. If visual data is not present, flag the table source as outdated
4. If changes include inserting or moving rows while sorted or filtered, flag the table source as outdated
5. When sorting or filtering changes, if the table source is outdated, reload all the data from the Redux store

I'm a bit concerned about 5, though, since it means the entire table data will be replaced, which in my previous experience was a performance bottleneck, especially since my data can be 100k+ rows.

**Comment by aarondfrancis** [comment]
@aaronbeall I ran into the same thing, you may check out the discussion on https://github.com/handsontable/handsontable/issues/6309 and https://github.com/handsontable/handsontable/issues/6546

**Comment by AMBudnik** [comment]
True :) This is already being developed as we speak.

**Comment by aaronbeall** [comment]
Will this breaking change also effect updating columns or column headers and calling `render()`, or should that still work?

**Comment by AMBudnik** [comment]
@aaronbeall I have been told that there's only one extra render() added but it is inside a method that did not exist before the feature so we shouldn't worry about incompatible changes.

**Comment by wojciechczerniak** [comment]
> ### Pre-8.0 solution
> 
> In 7.x I was able to solve the problems listed above by:
> 
> 1. Initially transform the Redux store data into Table data
> 2. When Redux store changes I compare to the Table data
> 3. Directly mutate the Table data by reference for just what changed, call `render()` (with some caveats, especially with nested rows)
> 
> ### Possible workaround after 8.0
> 
> I have not yet tried this, but this may be a workaround:
> 
> 1. Given previous and next source data, translate to visual data
> 2. If visual data is present, update it
> 3. If visual data is not present, flag the table source as outdated
> 4. If changes include inserting or moving rows while sorted or filtered, flag the table source as outdated
> 5. When sorting or filtering changes, if the table source is outdated, reload all the data from the Redux store
> 
> I'm a bit concerned about 5, though, since it means the entire table data will be replaced, which in my previous experience was a performance bottleneck, especially since my data can be 100k+ rows.

In the latest v8.0.0-beta.2 builds your pre-8.0 solution should work as well with a small change to the method used for updating source data. 

`v8.0.0` from `beta.2` introduces `setSourceDataAtCell` to modify source data and it's using physical indexes / object props.
https://github.com/handsontable/handsontable/blob/6d24b71d46041ad0bcbfcbddc7b8ba6550823382/src/core.js#L2423-L2430

---

> The suggested solution is to use populateFromArray() and setDataAtCell() (and alter()?) to apply external changes from the Redux store to the Table data. The problem with these functions is that they can only update visible data, if I understand correctly.

Good ideas I see here. `setSourceDataAtCell` may be to atomic.

---

There is another approach I would want to try at some point. We've added new hook `modifySourceData` that is called with `iomode` for `set` and `get` request. 

https://github.com/handsontable/handsontable/blob/6d24b71d46041ad0bcbfcbddc7b8ba6550823382/src/pluginHooks.js#L1005-L1015

It could be used to switch the value at a very low lvl:

```ts
handsontable.addHook('modifySourceData', function (row, column, valueHolder, iomode) {
  if (iomode === 'set') {
    reduxStore.dispatch({
      type: 'setCellData',
      row: row,
      column: column,
      newValue: valueHolder.value
    });
  } else if (iomode === 'get') {
     // FIXME: make a copy if not a simple value
     valueHolder.value = reduxStore.getState().data[row][column];
  }
});
```

https://codesandbox.io/s/react-handsontable-pr-9w0m0?file=/src/index.js Handsontable still needs some kind of `data` copy to initialize correctly, but all values can be `null` to minimize memory usage. Not the most elegant solution 😒 

And we have to recreate all CRUD operations to keep the reduxStore in sync: create/remove row/column. Move, sort, and metadata indexes should be handled by the Handsontable correctly internally though.

----

Anyway, `setSourceDataAtCell` should solve this issue. Right @aaronbeall?

**Comment by aaronbeall** [comment]
> Anyway, `setSourceDataAtCell` should solve this issue. Right @aaronbeall?

Yes, this is essentially what I am looking for! Two additions, though:

1. If I call `setSourceDataAtCell()` multiple times (say to update 1000 cells) will there be a performance bottleneck, or are are the updates batched in any way? This is the case I have where a new page of data is loaded.

2. In addition to updating existing rows of data I need to add rows and delete rows. Will `setSourceDataAtCell()` work to add rows? How can I delete rows?

3. How does this work with nested rows?

**Comment by AMBudnik** [comment]
@aarondfrancis 
https://jsfiddle.net/xoubkcpd/ in this case `setSourceDataAtCell` and `setDataAtCell` seem to take the same time. With or without the initial data https://jsfiddle.net/xoubkcpd/1/ (+ `nestedRows` https://jsfiddle.net/v2w6kf8t/)
There's a way to run the `silentMode` for the method, but as mentioned here https://github.com/handsontable/handsontable/pull/6935#issuecomment-634516886 it's private.

**Comment by wojciechczerniak** [comment]
> > Anyway, `setSourceDataAtCell` should solve this issue. Right @aaronbeall?
> 
> Yes, this is essentially what I am looking for! A few additions, though:
> 
> 1. If I call `setSourceDataAtCell()` multiple times (say to update 1000 cells) will there be a performance bottleneck, or are the updates batched in any way? This is the case I have where a new page of data is loaded.

That's a lot. The method will trigger a render, so yes, there will be a performance bottleneck. As @AMBudnik mentioned there an argument to skip the render, but it's currently not documented. Batching should be our next step.

> 2. In addition to updating existing rows of data I need to add rows and delete rows.  Will `setSourceDataAtCell()` work to add rows? How can I delete rows?

First, you will have to use `alter` to insert a row/column, then you can fill it with data. `setSourceDataAtCell` will work only on cells that are already in the dataset. We want to make it more convenient #6032. Do you think it should work on physical indexes as well? Do you need to insert rows/columns between items that are trimmed/filtered/collapsed at a specific position?
 
> 3. How does this work with nested rows?

Making it work correctly with NestedRows took most of the time needed to implement it. Should be ok.

**Comment by aaronbeall** [comment]
> That's a lot. The method will trigger a render, so yes, there will be a performance bottleneck. 

Yeah, it's certainly not an ideal scenario. There might be a better way for us to handle it, I don't know. Basically, we page in the data 1000 rows (actually "projects" but analogous to table rows) at a time in order to speed up time to first render, but there could be 10k+ by the time it's done. Each batch of 1000 need to be inserted as they are loaded, but the load in those chunks. Any suggestions here? 

> First, you will have to use alter to insert a row/column, then you can fill it with data. `setSourceDataAtCell` will work only on cells that are already in the dataset.

Aha, yes that makes sense, and that will work nicely for adding new rows. Even in a filtered/sorted state it's acceptable to me to just append them to the end of the visible rows, users can re-sort/re-filter manually afterwards. 

> Do you think it should work on physical indexes as well? Do you need to insert rows/columns between items that are trimmed/filtered/collapsed at a specific position?

I don't think we really need to add rows between trimmed/filtered rows (it might be better if we could, but it's not a big deal to me, as I said user can always re-sort/re-filter after updates), however I do sometimes need to remove a source row that might be currently filtered out. If I understand how `alter()` currently works, that would not be possible, so yes, I would l think providing physical indexes would be needed --  correct me if there's another way to delete filtered out rows.

**Comment by AMBudnik** [comment]
Hi @aaronbeall we are converting feature requests that still need some attention to Github Discussions where we can divagate on what to add and what to alter. At the same time, users can leave their votes, which I found super cool.
I'm wondering if you could convert this issue into a discussion as you wanted the `setSourceDataAtCell` to provide some extra info/logic. But if not, and `setSourceDataAtCell` is completely OK, we can close this topic as solved.

**Comment by AMBudnik** [comment]
OK, I think that as there are no new thoughts to this subject we can call it solved with the introduction of `setSourceDataAtCell` and close it.
