### ISSUE TITLE
Couldn't start ng dev server(Ng Serve). Got compilation issues in the console.

### ISSUE THREAD

**Issue by samueljTRQ** [handsontable/handsontable#6683]
### Description
Cannot use ng serve. Throws the below error
![image](https://user-images.githubusercontent.com/49991045/73738152-ec4f9c80-4769-11ea-8695-e1799449dcc6.png)

### Your environment
* Handsontable version: 8.0.0-beta.1
* Browser Name and version: 79
* Operating System: Windows 10 x64

**Comment by wojciechczerniak** [comment]
Angular wrapper was not yet updated for `v8.0.0`. We will do that after the beta.

**Comment by samueljTRQ** [comment]
Thanks for your time. You have been of great help.
