### ISSUE TITLE
tableView viewportRowCalculatorOverride wrong logic

### ISSUE THREAD

**Issue by hakonleung** [handsontable/handsontable#6691]
### Steps to reproduce

if viewportOffset is 'auto', variable center should be center row index but not 
```
const center = calc.startRow + calc.endRow - calc.startRow;
```

**Comment by pnowak** [comment]
I have to admit logic in this calculation is odd and we need further investigate this subject.
I connect your issue with another https://github.com/handsontable/handsontable/issues/6115 

Thanks for reporting @hakonleung

**Comment by hakonleung** [comment]
> I have to admit logic in this calculation is odd and we need further investigate this subject.
> I connect your issue with another #6115
> 
> Thanks for reporting @hakonleung

BTW, Handson has poor performance when table size is large and cellRenderer is complicated ：(

**Comment by AMBudnik** [comment]
Hey @hakonleung 

that

> Handson has poor performance when table size is large and cellRenderer is complicated 

will be fixed within https://github.com/handsontable/handsontable/issues/5204

**Comment by AMBudnik** [comment]
Hi @hakonleung 

The origin issue was just closed as solved https://github.com/handsontable/handsontable/issues/5204
This issue is no longer replicable in Handsontable 12.3.0
