### ISSUE TITLE
Bug in afterChange if column header contains a dot

### ISSUE THREAD

**Issue by benedikt-bauer** [handsontable/handsontable#6694]
### Description
If a column header contains a dot, the afterChange function does not work properly.
It always considers the cell's value prior to the change as "undefined". 

### Steps to reproduce
1. Create a Handsontable with a column header that contains a dot
2. Add afterChange function where the value prior to the change is involved.
3. Change the value in a cell -> the value prior to the change will be considered as "undefined"

### Demo
JS Fiddle Link:
https://jsfiddle.net/95r7ovw8/3/

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: Firefox 72.0.2
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @benedikt-bauer 

Thank you for taking the time to share this finding.

It's about the key (in data) not the name of a header. Here's a related topic https://github.com/handsontable/handsontable/issues/5439

**Comment by benedikt-bauer** [comment]
Hi @AMBudnik,

thanks for the quick reply and the link to the related topic.
With the information there, I found a way to get passed the dot "problem" :)

Since it's solved for me, I close the issue now.

Thanks again!
