### ISSUE TITLE
columnSummary, Filters and spare rows are causing 'RangeError: Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6695]
### Description

When we enable `columnSummary`, `Filters` and `minSpareRows` we get

![Zrzut ekranu 2020-02-7 o 09 51 07](https://user-images.githubusercontent.com/10757813/74014634-614feb80-498f-11ea-838e-b4eeecc02325.png)

It doesn't allow us to proceed with any operation on the table. Fortunately, it is fixed with `8.0.0-beta1`

### Steps to reproduce

1. Open console

### Additional info
* it is not fixed within `7.4.0` https://jsfiddle.net/0rtx5pg9/1/
* it is fixed in `8.0.0-beta1` https://jsfiddle.net/0rtx5pg9/2/
* related https://github.com/handsontable/handsontable/issues/6465

### Demo

https://jsfiddle.net/0rtx5pg9/

### Your environment
* Handsontable version: 7.3.0
_Seem to work the same in all versions_
* Browser Name and version: Chrome 79
* Operating System: Mac Catalina

**Comment by AMBudnik** [comment]
same as https://github.com/handsontable/handsontable/issues/5863

**Comment by aninde** [comment]
Remains solved with `8.0.0-beta.2` and `pre-8.0.0` https://jsfiddle.net/aninde/bLw3687p/.
