### ISSUE TITLE
[7.2.0] Display problems with fixedRowsBottom: overlaying selection on nonfixed row

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6698]
### Description

1. Table with row and colHeaders and fixedRowsBottom is not displayed correctly. 
FixedBottomRows are doubled. Selection on them too. After an event display is correct.

2. FixedRowBottom overlays selection on nonfixed rows even when display is correct after some even (e. g. mouse click)

### Steps to reproduce

1. Open demo https://codesandbox.io/s/fixed-overlays-selection-5hbwl or https://jsfiddle.net/aninde/mqso7zhy/

<img width="190" alt="Screenshot 2020-02-10 at 13 40 55" src="https://user-images.githubusercontent.com/30186818/74151228-feb75380-4c0b-11ea-89df-a5732ec2fe47.png">

![Screenshot 2020-02-10 at 13 25 54](https://user-images.githubusercontent.com/30186818/74151283-1f7fa900-4c0c-11ea-8464-74aabc1ded93.png)

### Demo

https://codesandbox.io/s/fixed-overlays-selection-5hbwl
https://jsfiddle.net/aninde/mqso7zhy/

### Your environment
* Handsontable version: 7.2.0+ and 8.0.0beta
* Browser Name and version: FF 72, Chrome 82, Safari 13.0.4
* Operating System: macOs

**Comment by pnowak** [comment]
Good news! This issue got solved v8.0.0. Here's an updated demo - https://jsfiddle.net/hw8qjb1k/

**Comment by AMBudnik** [comment]
We can call this issue solved by v 8.0.0
