### ISSUE TITLE
[5.0.2] EDGE Dropdown menu onMouseOut event causes critical errors when hovering over vertical scrollbar

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6699]
### Description

* The issue doesn't happen if we do not have the vertical scroll bar
* Using the same steps in React 
![image](https://user-images.githubusercontent.com/10757813/74157651-ec8fe200-4c18-11ea-8766-e09da19d8e68.png)
https://codesandbox.io/s/gh-newissue00001-qf1nx

### Steps to reproduce

1. Mouse over the dropdown menu icon
2. Move move on the vertical scrollbar on the right

![image](https://user-images.githubusercontent.com/10757813/74157393-81dea680-4c18-11ea-8d90-e7986a2a0e37.png)

**Result**
![image](https://user-images.githubusercontent.com/10757813/74157292-522f9e80-4c18-11ea-8101-b9ed08029a94.png)

### Demo

https://jsfiddle.net/5yv3mha2/ `5.0.1` - working
https://jsfiddle.net/5yv3mha2/1/ `5.0.2` - broken

### Your environment
* Handsontable version: 5.0.2+
* Browser Name and version: Edge
* Operating System: Windows 10

**Comment by aninde** [comment]
I'm struggling to replicate this. @AMBudnik can you make gif with marked clicks?ge

**Comment by AMBudnik** [comment]
#### Additional info
* `7.3.0` works the same https://jsfiddle.net/w98025m1/
* loading `8.0.0-beta1` doesn't work at all https://jsfiddle.net/mxdy8rb9/
![image](https://user-images.githubusercontent.com/10757813/74217648-599e8880-4ca8-11ea-92bf-1b07fd599036.png)

* here's the cursor video @aninde - you just hover the dropdown and hover the right scroll
![edge bug](https://user-images.githubusercontent.com/10757813/74217548-0f1d0c00-4ca8-11ea-9ab1-6c75352d8535.gif)

**Comment by aninde** [comment]
This bug does not occur on the Edge Dev (engine: Chromium) / Windows 10.

**Comment by aninde** [comment]
This bug also does not uccur on Edge 80 and Edge Dev 81 / macOs Cataliana. Edge is not supported on Linux, so we can assume that it only appears on Windows.

**Comment by aninde** [comment]
This issue is solved by `8.0.0-beta2-rev15` https://jsfiddle.net/kuq2syvo/

**Comment by AMBudnik** [comment]
Issue fixed in v 8.0.0. Updated demo https://jsfiddle.net/80ftygwb/
