### ISSUE TITLE
Error during loading of E2E test runner in Edge and IE

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6713]
### Description

The E2E test runner located at `/test/E2ERunner.html` fails to start in Edge and IE due to unsupported syntax.

The error message is:

> Error during loading: Expected identifier, string or number in http://localhost:5000/test/dist/e2e.entry.js line 75633

### Steps to reproduce

1. Build the E2E test suite using `npm run test:e2e`
2. Start the static file server at a local port, e.g. 8080
3. Open the test runner in the web browser by going to http://localhost:8080/test/E2ERunner.html

### Your environment
* Handsontable version: 7.4.0
* Browser Name and version: Edge 44.18362.449.0 (EdgeHTML 18.18363) & IE 11
* Operating System: Windows 10

![image](https://user-images.githubusercontent.com/566463/74660646-d04ef080-5196-11ea-9339-5ae132ef1c14.png)

![image](https://user-images.githubusercontent.com/566463/74660678-dfce3980-5196-11ea-83f5-91af1e096697.png)

**Comment by aninde** [comment]
On MacOS, you can run then on Edge or Edge Dev. 

I heard that they are unsupported by IE.

**Comment by wojciechczerniak** [comment]
Looks like it was done in #6715

**Comment by AMBudnik** [comment]
issue solved in v8.0.0.
