### ISSUE TITLE
[7.0.0] Pasting several rows (e.g from Excel) when formula is enabled is impossible

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6714]
### Description
Pasting several cells from Excel when formula is enabled is impossible since 7.0.0 version.
It works in a 6.2.2 version. 
When you try to paste some rows in 7+ v. an error occurs and codesand box crashes. 
Locally, an error occurs in the console.

:warning: Do not open codesandbox with 7.0.0 v. Use jsfidle demo instead. 

**FF:**
this.hot.getSourceData(...)[physicalRow] is undefined

**Chrome:**
cannot set property '0' of undefined

**Actual result**
![Screenshot 2020-02-17 at 15 35 34](https://user-images.githubusercontent.com/30186818/74663983-26269700-519d-11ea-985a-a7d83f19a38f.png)
![Screenshot 2020-02-17 at 15 35 42](https://user-images.githubusercontent.com/30186818/74663988-27f05a80-519d-11ea-8b79-ba156b8126a9.png)

**Expected result from 6.2.2**
 ![pastingExcel7 4 0](https://user-images.githubusercontent.com/30186818/74663780-b4e6e400-519c-11ea-9fde-de5be3176cc6.gif)

### Steps to reproduce

1. Open demo https://codesandbox.io/s/pasting-with-formulas-xhd4i or https://jsfiddle.net/aninde/mgx73z80/
2. Copy data and paste then into A1.

=$B4=C$2
=$B5=C$2
=$B6=C$2
=$B7=C$2
=$B8=C$2
=$B9=C$2
=$B10=C$2
=$B11=C$2
=$B12=C$2
=$B13=C$2
=$B14=C$2
=$B15=C$2
=$B16=C$2
=$B17=C$2
=$B18=C$2
=$B19=C$2
=$B20=C$2
=$B21=C$2
=$B22=C$2

3. Toggle to 6.2.2 version on dependencies and try again.

### Demo

https://codesandbox.io/s/pasting-with-formulas-xhd4i
working `v. 6.2.2` https://jsfiddle.net/aninde/nL7arvto/
bug `v 7.0.0` https://jsfiddle.net/aninde/mgx73z80/

### Your environment
* Handsontable version: 7+
* Browser Name and version: Firefox 73, Chrome 80
* Operating System: macOs

**Comment by aninde** [comment]
Actual bugsy result from local testing:
![Screenshot 2020-02-17 at 15 54 02](https://user-images.githubusercontent.com/30186818/74664444-00e65880-519e-11ea-8ddc-7beb5f6852c6.png)
only one row is added, header borders aren't rendering correctly.

**Comment by AMBudnik** [comment]
8.0.0-beta2-rev14 
* loads all the rows but 
* ref is still visible
* there are no console errors 

Demo https://jsfiddle.net/AMBudnik/0p4wo2he/

**Comment by pnowak** [comment]
Good news! This issue got solved v8.0.0. Here's an updated demo - https://jsfiddle.net/Lceatb2s/
