### ISSUE TITLE
Cannot read property 'defaultView' of undefined

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6718]
### Description

When the Handsontable is initialized with `fixedRowsTop` and `fixedRowsBottom` higher than rows length then the table throws errors while clicking the cells.

### Steps to reproduce

![Kapture 2020-02-19 at 15 10 21](https://user-images.githubusercontent.com/571316/74842032-fce74180-5329-11ea-95eb-29fb968d23f4.gif)

### Demo

https://jsfiddle.net/budnix/bu0aoskp/

### Your environment
* Handsontable version: Since 7.2.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
The 8.0.0.0-beta2-rev3 produces other issue and removes columns https://jsfiddle.net/3512f4qb/
![Zrzut ekranu 2020-05-12 o 13 22 42](https://user-images.githubusercontent.com/10757813/81680664-be0de700-9453-11ea-9d42-be6ac9a5bd3c.png)

**Comment by aninde** [comment]
This issue is fixed by `v8` https://jsfiddle.net/aninde/qvs2k3xg/.
