### ISSUE TITLE
how can I pass json data to handsontable in react?

### ISSUE THREAD

**Issue by rishi1804** [handsontable/handsontable#6720]
### Description

I want to create a spreadsheet using the JSON data that will be fetched from and API I am unable to pass this kind of data. 

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey @rishi1804 

you can use a parsed `JSON` in the data option. Example https://jsfiddle.net/zfd0g54w/

**Comment by rishi1804** [comment]
@AMBudnik I want to fetch data from my API and that API will return the data in JSON format.  and now plz tell me how can I fetch the data from the API in react and use the same to create handsontable.

**Comment by AMBudnik** [comment]
Hey @rishi1804 

please share an input/output example with me via email support@handsontable.com

**Comment by rishi1804** [comment]
@AMBudnik  ok

**Comment by AMBudnik** [comment]
The conversation is continued on emails.
