### ISSUE TITLE
Cannot copy value with select2 editor

### ISSUE THREAD

**Issue by godshades** [handsontable/handsontable#6721]
Hi, I'm using handsontable 6.2.2 with custom config select2
everything work OK, but when I select cell use " editor: 'select2' " I can't copy paste this cell value
does anybody have same problem

**Comment by godshades** [comment]
I found #6227  is almost same
but my js don't have this.TEXTAREA.select = function()
here is mine: https://jsfiddle.net/jbrzwomg/

**Comment by AMBudnik** [comment]
Hey @godshades 

the creator of the Select 2 Editor is **trebuchetty** not **Handsontable**.

I recommend posting the same question on their repository https://github.com/trebuchetty/Handsontable-select2-editor
