### ISSUE TITLE
Add paste option to context menu

### ISSUE THREAD

**Issue by camilstaps** [handsontable/handsontable#6730]
### Description
The context menu has predefined `cut` and `copy` options but there is no predefined `paste`. Apparently it used to exist (#23, #3496). Was there a reason why it was removed? Can it be added again?

### Steps to reproduce
1. Create a table with `contextMenu: ['cut','copy','paste']`
2. Open cell context menu
3. Note that `paste` does not have a capital or a callback: it is not recognized as a standard option

### Demo
https://jsfiddle.net/tbnafhy9/ (from [the docs](https://handsontable.com/docs/7.4.2/demo-context-menu.html#page-specific))

### Your environment
* Handsontable version: 8.0.0-beta.1
* Browser Name and version: 68.5.0esr
* Operating System: Debian 10

**Comment by AMBudnik** [comment]
Hey @camilstaps 

> Was there a reason why it was removed? Can it be added again?

browsers have raised the security levels some time ago and currently, there is no supported way to paste the clipboard content via JS.  I guess that are some hacks but as mentioned in this [SO topic](https://stackoverflow.com/questions/57322905/how-to-paste-the-clipboard-content-automatically-in-my-webpage)

> without user permission, reading or altering the clipboard contents is not permitted.

**Comment by camilstaps** [comment]
@AMBudnik that makes sense, thanks for the explanation!
