### ISSUE TITLE
After column move click handlers fire on previous column

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#6735]
### Description

If a click handler is added to a `td` from a renderer, then the column associated with that renderer is moved, the tds in the old column position still have the handler.

For `addEventListener` I'm not sure there's much that could be done about this.

For `onclick` HT could null it out during a column change. We are using `onclick` precisely because it's easy to remove it via `null`.

It's not clear to me exactly when and how HT recycles TD element... for example if you assign `style` or `className` or `classList` from a renderer, then move the column, the TDs in the old column clear out all that stuff even if I don't have a renderer that explicitly does so. Where is the code/logic to do that, and can clearing out `onclick` be part of it?

### Steps to reproduce

1. Create table with `manualColumnMove` and one column with a renderer that has `td.onclick = () => alert("clicked")`
2. Move the column with the click handler, say from index 1 to index 2
3. Click the column in the old index, ie index 1
Result: click handler and alert is fired
Expected: no click handler in the column which no longer has the click renderer

### Demo

https://jsfiddle.net/4hz3ks2f/

### Your environment
* Handsontable version: 7.2.1
* Browser Name and version: Chrome 79.0.3945.130
* Operating System: macOS 10.14.4

**Comment by AMBudnik** [comment]
That's an interesting use of the renderer. But you're right. I've tested 8.0.0-beta1 as at the first glance it looks like an issue of incorrect index mapping. However, 8.0.0-beta1 works the same https://jsfiddle.net/yLnbexm1/
I've added a background to show that the renderer moves with the column. 
Hm... this subject surely needs further testing but I already can call it a bug.

**Comment by aaronbeall** [comment]
Yeah, I think `afterOnCellMouseDown` seems like the right way to do this, lesson learned. In the meantime I found a workaround in the renderer:
```
const wrapper = document.createElement("div");
wrapper.append(...td.childNodes);
td.append(wrapper);
wrapper.onclick = () => alert("clicked");
```
Basically move whatever was rendered to the `td` (from parent renderer) into a wrapper, then assign the `onclick` to the wrapper. When the TD is recycled the wrapper is removed, so the click handler is gone with it.

Feel free to close this bug if you feel it's out of scope. FWIW it was a surprise that took some investigating to figure out, so if there's anything reasonable that _can_ be done to avoid this pitfall, it'd be nice.
