### ISSUE TITLE
Moving column with nestedHeaders set does not update headers

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#6740]
### Description

Moving a column should move the column header with it. I am guessing it's some limitation due to nested headers being used but we are mainly wanting this for the `ManualColumnFreeze` plugin which uses the `ManualColumnMove` plugin to freeze columns but we want the headers to move with the column. May be related to #6001 but couldn't find any other similar issues.

### Steps to reproduce

1. Move a column

### Demo

http://jsfiddle.net/6o4y5s21/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome v80
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey Jeremy,

the same topic has been already raised here https://github.com/handsontable/handsontable/issues/4150

besides the ability to keep the headers, we get the 'D' header for 2 columns just after loading the data - that's a bug but already mentioned here https://github.com/handsontable/handsontable/issues/5882

so I guess that everything is already covered.

**Comment by jeremy-smith-maco** [comment]
I couldn't find anything related to the issue but those would be it. Thanks @AMBudnik.
