### ISSUE TITLE
Too many values pasted when column is hidden

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#6743]
### Description
When a column is hidden and the selection spans the hidden column, an extra value is pasted into the table.

### Steps to reproduce
1. Select & copy B2.
2. Hide B.
3. Select A2 --> C2.
4. Paste.

Notice that *D2* now holds the pasted value as well.

### Demo
https://jsfiddle.net/7nsbrm82/

![paste](https://user-images.githubusercontent.com/881931/75595943-feb0b380-5a53-11ea-81da-36416dc27dc8.gif)

Found this while debugging on #6742.

### Your environment
* Handsontable version: 8 beta
* Browser Name and version: Chrome
* Operating System: OS X

**Comment by AMBudnik** [comment]
Thank you for sharing @aarondfrancis 

I see a similar topic here https://github.com/handsontable/handsontable/issues/5824 It is not the same but surely related

**Comment by wojciechczerniak** [comment]
We should check this after #6547 and add to the #6178 list

**Comment by pnowak** [comment]
Unfortunately, the issue still has broken in 8.0.0.-beta2-rev2 - https://jsfiddle.net/ugbt8e59/

<img width="288" alt="Zrzut ekranu 2020-05-8 o 12 43 29" src="https://user-images.githubusercontent.com/1555809/81398589-c3a0bf80-9129-11ea-884b-2a9f38525ca6.png">

**Comment by AMBudnik** [comment]
**Remains the same** in 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/kjs52pen/

**Comment by AMBudnik** [comment]
v8.0.0 demo https://jsfiddle.net/AMBudnik/xzLjbs04/ We still paste 3 values

![Zrzut ekranu 2020-08-28 o 15 35 17](https://user-images.githubusercontent.com/10757813/91566519-1bb33a00-e944-11ea-9b37-10c328fb2c2c.png)

**Comment by wszymanski** [comment]
It should be done within https://github.com/handsontable/handsontable/pull/7246.

**Comment by aninde** [comment]
@aarondfrancis I'm glad to see that this issue will be fixed by the upcoming `v8.1.0`.  https://jsfiddle.net/aninde/oczhmrd1/.
We plan to release it this week (Oct 1), as long as everything goes well.

![fixed-6743-ff81](https://user-images.githubusercontent.com/30186818/94441158-b5b80d80-01a2-11eb-9957-637458c76535.gif)

Works well on every supported browser on macOS.

**Comment by AMBudnik** [comment]
Thank you for the demo @aninde and @aarondfrancis for reporting the issue.
We can officially close the issue as solved for v 8.1.0

**Comment by aarondfrancis** [comment]
Upgraded to 8.1.0 and confirmed the fix. Thanks!
