### ISSUE TITLE
When data is null the minSpareRows/minSpareCols are the only rows/columns visible in the table

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6748]
### Description

When data is null the `minSpareRows` are the only rows visible in the table. Check this by running the example.

### Steps to reproduce

1. Just open the example

**Result**
There are 3 rows.

**Expected result**
There are 5 rows.

2. Change `null` to `'null'` (string) (2 x in line `3`)

**Result === Expected Result**
There are 5 rows.

### Additional information
* it also works for empty strings https://jsfiddle.net/y9a36xrz/1/
* it also works for `undefined` https://jsfiddle.net/y9a36xrz/2/
* works the same in `8.0.0-beta1` https://jsfiddle.net/y9a36xrz/
* works the same for columns https://jsfiddle.net/y9a36xrz/5/ (`3` columns instead of `5`)

### Demo

https://jsfiddle.net/y9a36xrz/4/ (`7.4.2`)

### Your environment
* Handsontable version: 7.4.2
_Doesn't seem to be version related._
* Browser Name and version: Chrome 80
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
`null` is an empty row. A row with `"null"` string is not empty.

If rows are empty, then `minSpareRows` are not adding new ones.

**Comment by wojciechczerniak** [comment]
Wontfix. Use `isEmptyRows` to customize the behavior
