### ISSUE TITLE
[7.4.2] Hook: modifyRow: RangeError call stack exceeded

### ISSUE THREAD

**Issue by Hydhen** [handsontable/handsontable#6750]
### Description
Get the hook setup or catch the exception and not freeze the whole table

### Code
```ts
dataset: any[] = [
    {
        id: '0', __children: [
            {
                id: '00', __children: [
                    { id: '000' }
                ]
            },
            {
                id: '01', __children: [
                    { id: '010' },
                    { id: '011' }
                ]
            }
        ]
    }
];

ngOnInit() {
    setTimeout(() => {
        this.hotInstance = this.hotRegisterer.getInstance(this.id);

        this.hotInstance.getPlugin('nestedRows').enablePlugin();
        this.hotInstance.loadData(this.dataset);
        // This one works
        this.hotInstance.addHook('afterSelection', (rowId: number) => this.selected(rowId));
        // This one raise the exception
        this.hotInstance.addHook('modifyRow', (rowId: number) => this.modified(rowId));
    });
}

modified(rowId: number): void {
    const row = this.hotInstance.getDataAtRow(rowId);
    console.log(rowId + ': ' + row[0]);
}
```

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Google Chrome Developer Version 82.0.4068.4
* Operating System: Windows 10 1909

**Comment by wojciechczerniak** [comment]
`getDataAtRow` method is the one that calls `modifyRow` hook. You're calling them in circle.

**Comment by Hydhen** [comment]
Oh, ok

Do you know how i could retrieve my row data if I cannot use `getDataAtRow` ?

Or maybe I'm making things wrong here, I want a callback for a modified cell and retrieve the row to update some internal values

I tried `modifyData` but the callback is called several times even on cells that has not been modified

**Comment by AMBudnik** [comment]
>  I want a callback for a modified cell and retrieve the row to update some internal values

For me it sounds like a `getDataAtRow` in the `afterChange` hook like here https://jsfiddle.net/kv3drop2/

**Comment by Hydhen** [comment]
> 
> 
> > I want a callback for a modified cell and retrieve the row to update some internal values
> 
> For me it sounds like a `getDataAtRow` in the `afterChange` hook like here https://jsfiddle.net/kv3drop2/

Indeed it seems exactly what I was searching for !
Thanks !
