### ISSUE TITLE
afterOnCellMouseOver is not activated on re-entering the table

### ISSUE THREAD

**Issue by rmonje** [handsontable/handsontable#6753]
### Description

If you when on console when afterOnCellMouseOver  is fired, you will see that is not fired when  re-entering the table

### Steps to reproduce

1. Specify afterOnCellMouseOver  and print on log when is fired "console.info('fired');"
2.  Run application and move cursor inside the table. It appears "fired" on the Console/log
3. Move the cursor outside the table.
4. Move the cursor inside the table (first cell in the edge)
5. "fired" is not written in the Console

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: from old (2015) to latest
* Browser Name and version: Chrome
* Operating System: Windows
[handsontable_mouseover_issue.txt](https://github.com/handsontable/handsontable/files/4287696/handsontable_mouseover_issue.txt)

**Comment by AMBudnik** [comment]
Hey @rmonje 

it seems to be the same issue as https://github.com/handsontable/handsontable/issues/4634 and https://github.com/handsontable/handsontable/issues/4296

**Comment by rmonje** [comment]
Yes, It's the same

**Comment by AMBudnik** [comment]
Thank you for confirmation. I will update you once we solve any of those issues.

**Comment by komalbatra3** [comment]
Hi @AMBudnik,

Is there any resolution/ workaround for this issue?

**Comment by AMBudnik** [comment]
Hi @komalbatra3 you can use a native `mouseover` callback on the Handsontable container https://jsfiddle.net/9bLej2mx/

**Comment by komalbatra3** [comment]
Hi @AMBudnik,

We need td/th details as well to show td/th specific details in hover. Do we get those details with native mouseover callback?

**Comment by AMBudnik** [comment]
You can get some basic information like the element TD/TH as well, it's className or (a bit hacky but still achievable) row header and its index https://jsfiddle.net/8v1eb3f7/ @komalbatra3
