### ISSUE TITLE
After running open() method for getActiveEditor() cell doesn't lose selection

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6754]
### Description

It got broken in `7.0.0` but as the `open()` method of `getActiveEditor()` was broken before that I did not attach the `regression` label.

This issue happens **only** when there is no content in the editor.

### Steps to reproduce

1. Click outside the table

![GIF](https://user-images.githubusercontent.com/10757813/75887629-638c5500-5e2a-11ea-8071-b2e422015bfc.gif)

**Result**
`B2` cell is selected.

**Expected result**
No cells are selected.

2. Type anything in the editor
3. Click outside the table

**Result** === **Expected result**
No cells are selected.

### Demo

https://jsfiddle.net/kj9zuh8a/2/ 7.4.2

### Related topics
* https://github.com/handsontable/handsontable/issues/6752

### Your environment
* Handsontable version: 7.0.0+
* Browser Name and version:  Chrome 80
* Operating System: Windows 10

**Comment by swistach** [comment]
It's the wrong use of internal methods, the detailed explanation you can find here: 
https://github.com/handsontable/handsontable/issues/6752#issuecomment-767644883
