### ISSUE TITLE
how do I differentiate the pasted data from handsontale or excel?

### ISSUE THREAD

**Issue by hhhhhhqqqqqq** [handsontable/handsontable#6757]
### Description

I want to know the pasted data from handsontable or excel 
However, I found that the onPaste function only parsed the data without distinguishing the specific source of the data.
So that I can't get the style of the data that I'm pasting
Is there a good solution?

**Comment by AMBudnik** [comment]
Hey @hhhhhhqqqqqq 

have you already tried https://handsontable.com/docs/7.4.2/Hooks.html#event:beforePaste hook?
Demo https://jsfiddle.net/rqc7eufn/

It will tell you what is the data and where it is was pasted.

You won't be able to copy-paste cells with styling. You also won't be able to differentiate what is the source of the data (the browser for the security reason does not pass this information).

**Comment by hhhhhhqqqqqq** [comment]
Thank you very much for your prompt reply. I tried to solve the style problem in other ways.

**Comment by hhhhhhqqqqqq** [comment]
@AMBudnik Thank you very much for your prompt reply. I tried to solve the style problem in other ways.

**Comment by AMBudnik** [comment]
OK. Thank you for the update.
I guess that we can close the ticket then.
