### ISSUE TITLE
[svg] Incomplete border on the overlay edge when the border range contains a merged cell

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6760]
### Description

Originally reported by @budnix in PR review https://github.com/handsontable/handsontable/pull/6157#issuecomment-593852229:

> When the merged cell is selected, the border width is not constant (https://jsfiddle.net/oma4vwb1/). And it seems that the red border (autofill) neither doesn't render well. 

Longer version: 

#### Problem A

When a merged cell is rendered on the edge of row header (or fixed rows/column overlay), only the original part of the cell border is drawn on the edge of the row header (or on the frozen line).

Steps to repro:

1. Select a merged cell on an edge of row headers. 
2. Notice that only a part of the blue border is rendered with the desired thickness.

#### Problem B

Draggin the auto fill handle from a cell that is rendered on the edge of row header (or fixed rows/column overlay) to a merged cell, results with only the original part of the merged cell border drawn on the edge of the row header (or on the frozen line).

Steps to repro:

1. Select any cell on an edge of row headers. 
2. Drag the autofill handle onto a merge cell. Notice that only a part of the red border is drawn on the headers border.

### Demo

This demo can be used to reproduce problems A and B: https://jsfiddle.net/oma4vwb1/

### Your environment
* Handsontable version: https://github.com/handsontable/handsontable/pull/6157/commits/44c3704fbf18bc1c08ce15b5b493e5205f3b9975
* Browser Name and version: any
* Operating System: any

This screenshot shows problems A and B: 

![Kapture 2020-03-03 at 10 13 16](https://user-images.githubusercontent.com/571316/75761557-9276ce00-5d39-11ea-871c-6f936f1df4c6.gif)

**Comment by warpech** [comment]
Fix that works, but it's obviously not architected correctly: https://github.com/handsontable/handsontable/commit/3acb42a97f324a34fe472fe2e9ab930e2f26554f

I need direction how to fix it with a more proper architecture. I suppose the tests should be added in the merged cells plugin? If you have any comments, they can be added directly to the commit.

This is not a separate PR, because I want to include it in the SVG borders PR: https://github.com/handsontable/handsontable/pull/6157

**Comment by warpech** [comment]
Alternative fix with a more decoupled architecture, using `getCellMeta` instead of direct access to merged cells plugin: https://github.com/handsontable/handsontable/commit/1252472ebdf259af57ada1a769a536c03b440ff2

I will add the tests tomorrow and push it to the SVG borders PR.

**Comment by warpech** [comment]
Final version of the fix was pushed in https://github.com/handsontable/handsontable/pull/6157/commits/e1c107eb2a7cd1d13cc5d1696ce07f24ff7e7f66 as part of the SVG borders PR.

**Comment by budnix** [comment]
It seems that merge cells are more problematic here. With SVG border the selection is getting a part on merged cells which were defined right after the header (https://jsfiddle.net/budnix/7bnwcmL6/4/).

SVG borders
![Kapture 2020-03-13 at 10 02 23](https://user-images.githubusercontent.com/571316/76606365-67973180-6512-11ea-9493-3aeecf5bca09.gif)

The latest HoT version (7.4.2)
![Kapture 2020-03-13 at 10 03 44](https://user-images.githubusercontent.com/571316/76606400-7a116b00-6512-11ea-9fd7-1e81386e4b74.gif)

**Comment by warpech** [comment]
As discussed with @krzysztofspilka and @wojciechczerniak yesterday, the problem in the above GIF is that when the column B, C, F, G or H is selected, the left edge of the selection is not rendered. This must be fixed.
