### ISSUE TITLE
fixedColumnsLeft option and the autoRowSize option together, the height of the column is rendered incorrectly.

### ISSUE THREAD

**Issue by ahndohun** [handsontable/handsontable#6765]
### Description

fixedColumnsLeft option and the autoRowSize option together, the height of the column is rendered incorrectly.
The interesting thing is that more than two lines will cause an exact 1.11px difference.

### Steps to reproduce

1. fixedColumnsLeft: 4, autoRowSize: true
2. style no overwrite

### Demo

**If the column of column text is only one line, no problem.**
![2-1](https://user-images.githubusercontent.com/19940813/76390314-8aa9d000-63b0-11ea-918f-905f283e35dc.png)
![2-2](https://user-images.githubusercontent.com/19940813/76390318-8c739380-63b0-11ea-8d0f-92c254649cd6.png)

**However, if the text stretches beyond two lines, the height value will be different.**
![1-1](https://user-images.githubusercontent.com/19940813/76390390-a9a86200-63b0-11ea-890e-bbb7f0b7a478.png)
![1-2](https://user-images.githubusercontent.com/19940813/76390308-88477600-63b0-11ea-90f7-4e4240899407.png)

### Your environment
* Handsontable version: 6.2.0
* Browser Name and version: Chrome 80.0.3987.132
* Operating System: mac os catalina 10.15.2

**Comment by AMBudnik** [comment]
Hey @ahndohun 

I do not see any difference in height for the cell `(5, 5)` in this demo https://jsfiddle.net/krgfa28z/1/ with or without the `fixedColumnsLeft`. 

Are you able to replicate the same with my demo?

I am using the same system setting Chrome 80.0.3987.106 on Catalina

**Comment by ahndohun** [comment]
My explanation was insufficient.
Reproducible by reducing the font size of the browser (90%)
![image](https://user-images.githubusercontent.com/19940813/76582534-d88e1780-6519-11ea-820a-0417079fccd3.png)

**Comment by AMBudnik** [comment]
Thank you for the additional details. The following case has been already raised here https://github.com/handsontable/handsontable/issues/3118
I will update you once we get https://github.com/handsontable/handsontable/issues/3118 solved.
