### ISSUE TITLE
require('handsontable') crash node

### ISSUE THREAD

**Issue by djmisterjon** [handsontable/handsontable#6773]
### Description
Hey any idea why i can use require('handsontable') to my node app ? _(nwjs)_
It crash on my side ?

### Steps to reproduce

1. `npm i handsontable`
2. `const Handsontable = require('handsontable');`

### Demo
![image](https://user-images.githubusercontent.com/24865815/77267924-95027e80-6c7a-11ea-9953-f71dd64b3921.png)

### Your environment
```json
{
  "name": "pixi-dtle",
  "version": "1.0.0",
  "description": "PIXI DATA TEXT LOCALIZATION EDITOR tool for game and app dev",
  "scripts": {
    "dev": "nw src/ --remote-debugging-port=9222",
    "prod": "nwbuild --platforms win32,win64,linux64 --buildDir dist/ src/"
  },
  "keywords": [
  ],
  "author": "jon.lepage",
  "license": "MIT",
  "devDependencies": {
    "nw": "^0.44.5-sdk",
    "nw-builder": "^3.5.7",
    "nwjs-types": "^1.0.0"
  },
  "dependencies": {
    "handsontable": "^7.4.2",
    "pixi.js": "^5.2.1",
    "recursive-readdir": "^2.2.2"
  }
}
```
thanks for help.
What am doing wrong ?

**Comment by djmisterjon** [comment]
I also try with cdn only
```js
<link href="https://cdn.jsdelivr.net/npm/handsontable/dist/handsontable.full.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/handsontable/dist/handsontable.full.min.js"></script>
```
Get same error !!
![image](https://user-images.githubusercontent.com/24865815/77285913-92b71900-6ca8-11ea-8555-67bfd64551ca.png)

Here more info about environment.
```js
JSON.stringify(process.versions,null,'*')
"{
*"node": "13.10.1",
*"v8": "8.0.426.27",
*"uv": "1.34.2",
*"zlib": "1.2.11",
*"brotli": "1.0.7",
*"ares": "1.15.0",
*"modules": "79",
*"nghttp2": "1.40.0",
*"napi": "5",
*"llhttp": "2.0.4",
*"openssl": "1.1.1d",
*"icu": "65.1",
*"unicode": "12.1",
*"nw": "0.44.5",
*"node-webkit": "0.44.5",
*"nw-commit-id": "a060f45-6b2b07b-ca5e4a9-7029918",
*"nw-flavor": "sdk",
*"chromium": "80.0.3987.149"
}"
```
Thanks for help

**Comment by AMBudnik** [comment]
Hi @djmisterjon 

have you set the debugger to stop on every error? The following polyfill uses catch so you might be stopped.

I've checked the nw.js on my device and it works well.
![Zrzut ekranu 2020-03-23 o 10 55 35](https://user-images.githubusercontent.com/10757813/77304553-e5b6bd80-6cf4-11ea-8924-96c31f8d2eb9.png)

Do you have this project anywhere in [your repos](https://github.com/djmisterjon?tab=repositories)?

**Comment by djmisterjon** [comment]
Hey thanks first for your time to help. :)
Humm interesting, it the first time i get suggest to disable debug to make run app !
Yes seem work if i disable my debugger  !
![image](https://user-images.githubusercontent.com/24865815/77332598-9ecac700-6cf8-11ea-8bf7-3e4eb39c9a20.png)

But how am I supposed debug without debugger ? Is there a suggest hack to allow this ?
Do i have to manually hack all myself? or is there already a solution ?
Because the app is huge and i don't know how your engine work under the hood.
I'm more used to, Canvas and Webgl.

**Comment by djmisterjon** [comment]
> Do you have this project anywhere in [your repos](https://github.com/djmisterjon?tab=repositories)?
Yes i can made one tonight if necessary. it will a open source free projet.
I therefore intended to create a public repo of the project.

**Comment by AMBudnik** [comment]
There are a couple of ways to debug the code. You can manually add the statement to your code, but you also can set up (and sometimes it is set by default) an [IDE debugger](http://www.qnx.com/developers/docs/6.5.0/index.jsp?topic=%2Fcom.qnx.doc.ide.userguide%2Ftopic%2Fdebug_Base_.html). Depending on those settings you can define on what errors the code are stopped. If you choose the most restrictive option you will be held on each error - even the one that will not happen naturally in the browser. 
You should check the settings of your code editor.

**Comment by djmisterjon** [comment]
https://github.com/microsoft/vscode/issues/93272#issuecomment-602941053
