### ISSUE TITLE
No hidden column indicators when used with nestedHeaders option

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#6774]
### Description

Had a look and couldn't find any other issues in relation to this problem already so forgive me if I missed it. It appears when using the `hiddenColumns` option with `indicators` set to `true` as well as setting the `nestedHeaders` option it doesn't display the hidden column indicators or even attempt to apply the classes to the table headers at all.

### Steps to reproduce

1. Create table with `hiddenColumns: { indicators: true }` option and `nestedHeaders` option
2. Hide column(s)
3. No indicators appear

### Demo

http://jsfiddle.net/z10ad9pf/1/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome v80
* Operating System: Windows 10

**Comment by pnowak** [comment]
Hi @jeremy-smith-maco 

When I set a `colHeaders` everything works well - http://jsfiddle.net/9y5ej3u1/2/

So I think that without `colHeaders` `hiddenColumn` plugin doesn't work properly. 
Therefore it's crucial to set this option.

**Comment by jeremy-smith-maco** [comment]
Yeah it works with `colHeaders` fine. I don't see why it wouldn't be able to work with `nestedHeaders`. You would just need to apply the indicators to the last row of table headers. If this is intended behaviour then maybe the documentation should be updated with bolded text saying "MUST USE `colHeaders` OPTION, NOT `nestedHeaders` IF YOU WANT INDICATORS TO WORK".

**Comment by pnowak** [comment]
Yes, you right. 

I added an issue in our docs repo - https://github.com/handsontable/docs/issues/102
