### ISSUE TITLE
Exponential rerenders are caused by a hook that updates React state

### ISSUE THREAD

**Issue by BitterDone** [handsontable/handsontable#6779]
### Description
What should happen: A hook should execute once per action, and cause a single re-render
What happens: Multiple re-renders are triggered, increasing exponentially

### Steps to reproduce
1. Create a minimal sample React app
2. Replace App.js with:
```import React, { useState } from 'react';
import Handsontable from 'handsontable';
import { HotTable } from '@handsontable/react';

function App() {
    const [testStateCounter, setTestStateCounter] = useState(0);

    const _test = (changes, source) => {
        console.log(testStateCounter)
        setTestStateCounter(testStateCounter+1)
    }

    Handsontable.hooks.add('afterChange', _test);

    return (<div id="hot-app">
        <HotTable settings={{
            data: [['1']],
            rowHeaders: true,
            colHeaders: ['', 'comments'],
            licenseKey: 'non-commercial-and-evaluation',
            width: 500,
            height: 100,
        }}/>
    </div>);
}

export default App;
```

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/
Working on it, will update after some sleep.

### Your environment
* Handsontable version: 
"@handsontable/react": "^3.1.2",
"handsontable": "^7.4.2",
* Browser Name and version:
Chrome Version 80.0.3987.149 (Official Build) (64-bit)
* Operating System:
OS X 10.14.6

**Comment by AMBudnik** [comment]
Hey @BitterDone 

issues related to React are usually reported on the [React board](https://github.com/handsontable/react-handsontable) (here's the Vanilla). However, please take your time to create the demo. I will move the topic if the issue is React-oriented.

**Comment by AMBudnik** [comment]
Hey @BitterDone 

have you had time to create a demo? Is there any progress on the issue?

**Comment by AMBudnik** [comment]
I guess that we need to close the topic cause of lack of activity. But once you create a demo please share and I'll reopen the topic.

**Comment by BitterDone** [comment]
Hi @AMBudnik, apologies for the delay. I'll have a Github link posted sometime today.
Thank you!

**Comment by BitterDone** [comment]
Hi @AMBudnik - here's a link to a minimum create-react-app that shows the issue:
https://github.com/BitterDone/handsontable-nPlus1-rerender 

One correction, it appears to not be exponential rerenders, just n+1.

In the Apps.js, I created a `useState` hook that simply holds a counter integer.  Then I added an `afterChange` hook to the Handsontable, which logs & updates the counter in state. When the `setTestStateCounter` line is uncommented, no interaction is needed beyond loading the page. Something causes the hook to trigger upon render, which updates state, which causes a rerender, on to infinity. My quick test just now printed up to 51 before hitting the max update depth error:
`Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

App.js from the Github link:
```
import React, { useState } from 'react';
import Handsontable from 'handsontable';
import { HotTable } from '@handsontable/react';

function App() {
    const [testStateCounter, setTestStateCounter] = useState(0);

    const _test = (changes, source) => {
        console.log(testStateCounter)
        // setTestStateCounter(testStateCounter+1)
    }

    Handsontable.hooks.add('afterChange', _test);

    return (<div id="hot-app">
        <HotTable settings={{
            data: [['1']],
            rowHeaders: true,
            colHeaders: ['', 'comments'],
            licenseKey: 'non-commercial-and-evaluation',
            width: 500,
            height: 100,
        }}/>
    </div>);
}

export default App;
```

**Comment by AMBudnik** [comment]
Hey @BitterDone 

should this be the result
![Zrzut ekranu 2020-04-6 o 14 06 08](https://user-images.githubusercontent.com/10757813/78556771-db75e280-780f-11ea-8d1a-d6f187e6c95f.png)

I think that we could share the details on emails (mine is support@handsontable.com) and once we'll be ready to define what's the exact cause we'll get back to Github.

**Comment by BitterDone** [comment]
@AMBudnik That's what it initially looks like when `// setTestStateCounter(testStateCounter+1)` is commented, yes.
But when the line is uncommented, the n+1 re-renders occur and you actually don't see the UI before it crashes/the error screen appears

**Comment by BitterDone** [comment]
![nPlusOne](https://user-images.githubusercontent.com/4481910/78842197-fdfd2c80-79c4-11ea-8888-94d008e3585b.PNG)
 This is the result of enabling that line. Note that it console.logs from 0 to 51 in the Developer Console. Before this 0-51, it logged out 0-50, and 0-49, 0-48, etc.

**Comment by pnowak** [comment]
Hi @BitterDone 

It seems that `afterChange` hook call `setState` and `setState` react  `afterChange` whereby run into endless looping and at the end crash the app.
I wonder what is your goal?

**Comment by BitterDone** [comment]
Correct, that's a statement of the issue.

The goal in this example is to count the number of changes made to a cell in the table. My exact use case is different, but this behaves the same.

The bug, as I see it, is that the re-render triggers `afterChange`, which shouldn't happen, and is the reason for this ticket

**Comment by pnowak** [comment]
I think you should make use `source` in `afterChange` hook. 
So in that, you could react if changes come from editing for example.

Here is a demo - https://codesandbox.io/s/usestate-inside-afterchange-eekhs

On the other hand, you have to hold your data to properly show in the table.

**Comment by pnowak** [comment]
You could use another approach with `afterChange` in settings options (not add hooks).
Here is a demo - https://codesandbox.io/s/usestate-inside-afterchange-7p5v9

However, no matter which option you choose you to have to program other features like hold data in the cell.

**Comment by BitterDone** [comment]
Ah ok. Thank you, @pnowak - this structure makes more sense to me. I appreciate the explanation!

**Comment by pnowak** [comment]
I'm glad I could help you @BitterDone
