### ISSUE TITLE
Add persistentState support for filtering

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6782]
### Description

The `afterFilter` hook, which may return a complex object describing filtering configuration might be difficult and time-consuming to be set in the localStorage. The plugin that does it for other operations is called `persistentState`.

Currently the `persistentState` is a functionality that saves the key-value information for 
* sorting
* moving (columns and rows)
* resizing (columns and rows)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 83
* Operating System: OS Catalina

Inform [Client](https://forum.handsontable.com/t/gh-6782-6783-is-there-any-way-to-save-and-restore-user-preferences-like-column-resize-sorting-ordering/4241/13) after publishing

**Comment by egibney** [comment]
Any idea when this might be prioritized? Thank you :)

**Comment by AMBudnik** [comment]
Hey @egibney[ we can save the state of the filter right now](http://jsfiddle.net/AMBudnik/1ebkcdan/). But the PersistentState is not yet planned to support this plugin.

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback.
See you there!
