### ISSUE TITLE
Autocomplete query lags behind in Firefox

### ISSUE THREAD

**Issue by bitwolfe** [handsontable/handsontable#6784]
### Description
We've noticed an issue with the autocomplete querying being out of sync with what is shown on the screen when using Firefox. With a source function, the query sent to queryChoices seems to lag behind what is actually shown.

### Steps to reproduce
1. Edit an autocomplete cell
2. Type one character at a time and check the actual query. The query is always one step behind.

It doesn't matter if you clear first or not either, same thing happens no matter what you do.

This works perfectly fine when testing in Chrome.

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Firefox Developer Edition 75
* Operating System: MacOS 10.14

**Comment by AMBudnik** [comment]
Can you record it @bitwolfe ?

I'm already on Firefox 83 and it works the same as Chrome.

**Comment by bitwolfe** [comment]
@AMBudnik Sure, here's a quick gif with what I'm seeing and the console log of the source function's query input

![autocomplete_lag](https://user-images.githubusercontent.com/670705/77759492-749d4000-703d-11ea-9911-313300082ff7.gif)

**Comment by bitwolfe** [comment]
I'm seeing the same lag in the regular edition of Firefox 74 as well. Both editions of Firefox tested on their latest versions.

**Comment by AMBudnik** [comment]
Can you share a demo as well? I've tried the following code https://jsfiddle.net/nhgtbyko/ in FF 74 but it logs the query (and it has to be the same query) just when we typed it.

**Comment by AMBudnik** [comment]
Hey @bitwolfe do we have any update here?

**Comment by bitwolfe** [comment]
I've been trying to reproduce the issue in a demo but have so far been unsuccessful. Our source function makes an ajax request and calls the callback once completed, so I've tried to imitate that delay in the demo but haven't been able to reproduce the issue we are seeing in our application. I'm now wondering if it could be due to the data amount, because our table has about 5-10 columns and 1000 rows with some simple styling through the cells function. I'd need to do some more testing when I get the chance.

**Comment by AMBudnik** [comment]
> our table has about 5-10 columns and 1000 rows with some simple styling through the cells function.

It does not seem to be too-much for Handsontable. Are you able to check if wrapping the` console.log `into `setTimeout()` changes anything?

**Comment by AMBudnik** [comment]
Hey @bitwolfe

Please let me know if it works for you 

> Are you able to check if wrapping theconsole.log into setTimeout() changes anything?

**Comment by AMBudnik** [comment]
I guess that we can close the topic as there are no additional comments or questions. 
Feel free to leave a comment if there are still some problems and the issue will be reopened.
