### ISSUE TITLE
"Hide" property missing in CustomBorders typings

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6788]
### Description

`BorderOptions` type defined in the typings file does not contain the `hide` property: https://github.com/handsontable/handsontable/blob/d3689b1b6febf94ffb78e3b5e72dbacf9f6104d4/handsontable.d.ts#L2536

According to the docs, this is a valid property. It is listed in the last code snippet on the page: https://handsontable.com/docs/7.4.2/CustomBorders.html

### Your environment
* Handsontable version: 7.x
* Browser Name and version: any
* Operating System: any

**Comment by pnowak** [comment]
You're right @warpech. `hide` is missed in our definition file.

On the other hand, `style` doesn't exist, I think. 
So `type BorderOptions` need improvement.

**Comment by aninde** [comment]
On current stable `v7.4.2` is:

https://github.com/handsontable/handsontable/blob/f517f721e23d75367b8cf491bff3c6de3ee18367/handsontable.d.ts#L2535-L2539

With next `v8` will be:
https://github.com/handsontable/handsontable/blob/5051859a956f409efcfdf435deb5db3ad33922f2/handsontable.d.ts#L2510-L2515

**Comment by AMBudnik** [comment]
v8.0.0 https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts
![Zrzut ekranu 2020-09-1 o 12 37 24](https://user-images.githubusercontent.com/10757813/91839789-ed896f00-ec4f-11ea-975a-4068644fdb21.png)
