### ISSUE TITLE
SUMIF formula does not allow to use strings in conditions

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6790]
### Description

`SUMIF` allows to sum values based on string conditions.

![Zrzut ekranu 2020-03-31 o 09 12 00](https://user-images.githubusercontent.com/10757813/77997630-0b187c80-7330-11ea-93ef-419b498d8f1e.png)
src https://support.office.com/en-us/article/sumif-function-169b8c99-c05c-4483-a712-1697a653039b

However the same does not work in Handsontable.

### Steps to reproduce

1. Check the error in the table
2. Once we replace the logic to numbers it works well https://jsfiddle.net/th6csvbr/1/

![Zrzut ekranu 2020-03-31 o 09 20 23](https://user-images.githubusercontent.com/10757813/77998139-e2dd4d80-7330-11ea-9832-7a6d53aeb10c.png)
![Zrzut ekranu 2020-03-31 o 09 20 32](https://user-images.githubusercontent.com/10757813/77998143-e4a71100-7330-11ea-8488-99bdaa82bb71.png)

### Demo

https://jsfiddle.net/th6csvbr/

### Your environment
* Handsontable version: 7.4.2
Works the same in **8.0.0-beta1**
* Browser Name and version: Chrome 83
* Operating System: Os Catalina

**Comment by shanath111** [comment]
Hi @AMBudnik ,
The Issue  #6790 is still open, what is the solution for that?

**Comment by AMBudnik** [comment]
Hi @shanath111 
This issue hasn't been scheduled yet, but might be fixed after introducing a new formula plugin https://github.com/handsontable/handsontable/issues/6466

**Comment by shanath111** [comment]
I tried using the latest release of handson table i.e 1.8.0 , which was giving me the same error,

**Comment by AMBudnik** [comment]
@shanath111 

> This issue hasn't been scheduled yet,

It was not solved yet. It will produce the same issue in v 8.0.0. 

I will be sure to notify you once we fix it.

**Comment by shanath111** [comment]
Sure thanks for the quick response

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Works well in pre-v9 https://jsfiddle.net/handsoncode/grn05azv/ (we can use a string as a 2nd parameter)

**Comment by AMBudnik** [comment]
The issue is also gone for the official Handsontable v9.0.0

Update demo https://jsfiddle.net/erpvb0wk/1/
