### ISSUE TITLE
When nestedHeaders are enabled wrong column is removed

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6794]
### Description

When `nestedHeaders` are enabled wrong column is removed. Always the last column is removed.

### Steps to reproduce

1. Remove `Name` column via `dropdownMenu`

**Result**
`Street` column is removed and data shifts.

![image](https://user-images.githubusercontent.com/10757813/78026748-72e4bc80-735c-11ea-9106-0412b6d75ea5.png)

### Demo

https://jsfiddle.net/AMBudnik/pwykfvux/

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 83
* Operating System: OS Catalina

**Comment by AMBudnik** [comment]
The behavior **remains the same** after updating to 8.0.0-beta2-rev14 https://cdn.jsdelivr.net/gh/handsontable/handsontable@730c08e62d04b028092f4078c95d2b417aafdec9/dist/handsontable.full.min.js

**Comment by wojciechczerniak** [comment]
The description is wrong. Correct column was removed. NestedHeaders configuration is not changed though and columns stay the same as they were defined at the init. I believe this was designed that way, but we can improve.

**Comment by AMBudnik** [comment]
> I believe this was designed that way, but we can improve.

I'm changing the label to 'improvement suggestion'
