### ISSUE TITLE
Question: How can I implement table with drop-down column headers?

### ISSUE THREAD

**Issue by ZerdoX-x** [handsontable/handsontable#6796]
### Description
I wan't to put select tag into colHeaders and have ability to get and save values that user selected.
I have tried just to put them like this:
```
colHeaders: `
<select>
    <option value="1">First option</option>
    <option value="2">Second option</option>
    <option value="3">Third option</option>
</select>
`
But it renders to default value when I am resizing column for example or changing any value in the table. I am trying to develop this on Vue.js, but I don't have any ideas how can I complete this..
```

* Handsontable version: ^7.4.2
* Handsontable/vue version: ^4.1.1
* Browser Name and version: Google Chrome | 83.0.4093.3
* Operating System: Linux Ubuntu 19.10

**Comment by AMBudnik** [comment]
Hey @ZerdoX-x 

I recommend using the `afterGetColHeader` hook. It runs with the same value after each render. The important note here is to update the `afterGetColHeader` value once any of the options is chosen. To do this you need to track change event on that select and trigger
[`updateSettings`](https://handsontable.com/docs/7.4.2/Core.html#updateSettings) > [`afterGetColHeader`](https://handsontable.com/docs/7.4.2/Hooks.html#event:afterGetColHeader) again where the select has a value of the selected option.

https://jsfiddle.net/AMBudnik/orzhs8eL/

**Comment by ZerdoX-x** [comment]
I got it working, but now I wan't to get a value of this select tag. How can I do it? Maybe I can add event listener "change" on headers somehow?

**Comment by AMBudnik** [comment]
> Maybe I can add event listener "change" on headers somehow?

yes. now everything is just native JS https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event

**Comment by ZerdoX-x** [comment]
Yeah, I know. I tnink it's a crutch but I used "onchange" to get values in my Vue.js app. I have defined global variable (window.headerChangeHandler) I don't really like it but ok. Thank you. If some one will need my code (it's very verbose btw) contact me
