### ISSUE TITLE
Selection on IE doesn't work for empty cells when column is clicked.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6798]
### Description

Selection on IE doesn't work for empty cells while clicking the column header. Their background is white, not blue.

### Steps to reproduce

1. Click `Code name` column

![ie](https://user-images.githubusercontent.com/10757813/78227254-47cdaa80-74cd-11ea-9382-98faf05382ad.gif)

### Demo

https://handsontable.com/docs/7.4.2/demo-sorting.html

### Additional info
* Works well in Edge

### Your environment
* Handsontable version: 7.4.2
_It doesn't seem to work well in any version._
* Browser Name and version: Internet Explorer 11.1098.17763.0
* Operating System: Windows 10

**Comment by aninde** [comment]
As[ support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

This issue cannot be reproduced on real Edge / Windows 10 with current stable 7.4.2 and `8.0.0-beta2-rev15` https://jsfiddle.net/f0ws763h/ so, I'm closing it. 
- `v16`
- `v44`
- `v83` (latest) 
- Edge Dev `v85`

<img width="581" alt="Screenshot 2020-06-18 at 13 37 45" src="https://user-images.githubusercontent.com/30186818/85016727-97398380-b16a-11ea-8d21-045bc65e720e.png">
