### ISSUE TITLE
Cannot focus column filter inputs 

### ISSUE THREAD

**Issue by AlfonsProebstl** [handsontable/handsontable#6799]
### Description
Column filter demo breaks after second colmun filter in Edge / not able to focus filters in IE

### Steps to reproduce

1. Type into first column filter (not working in IE)
2. Try to type into second column (not working in Edge)

### Demo

https://handsontable.com/docs/7.4.2/demo-filtering.html#custom-implementations

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Microsoft Edge 44.18362.449.0 / Internet Explorer 11.719
* Operating System: Windows 10 1903

**Comment by AMBudnik** [comment]
Hi @AlfonsProebstl 

when I enter the demo I get the same issue as this one https://github.com/handsontable/handsontable/issues/5415

Is that the same issue?

**Comment by ajangles** [comment]
In Edge you can edit the input once, then none of the other wills work. I am able to type into the drops down from as shown in issue #5415 in Edge. 

![2020-04-02_20-26-55](https://user-images.githubusercontent.com/6114691/78232712-60b37b80-7520-11ea-9ec5-eb841ee77f31.gif)

**Comment by AMBudnik** [comment]
Ahh, ok. That issue is reported here https://github.com/handsontable/handsontable/issues/5820
