### ISSUE TITLE
fixedRowsBottom and columnSorting 

### ISSUE THREAD

**Issue by toresenneseth** [handsontable/handsontable#6804]
Hi, first of all - great product!

Here's an issue.

### Description
With column sorting and fixedRowsBottom enabled, the fixed rows are also sorted, while they should stay fixed.

### Steps to reproduce
1. Enable column sorting
2. Set fixedRowsBottom to one
3. Click the column header to sort the column. 

It seems like columns where the cell values of the fixed rows are null or undefined stays fixed, but I don't know whether this behavior is intentional or coincidental.

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 80.0.3987.149
* Operating System: Windows 10

Additional question:
Is there any API that lets me exclude rows from being sorted?

-Thanks!

**Comment by AMBudnik** [comment]
Hi @toresenneseth 

It sounds exactly as my request from here https://github.com/handsontable/handsontable/issues/3600
Can you confirm?

**Comment by toresenneseth** [comment]
Hi,

Yes, it's the same thing.  It prevents us from enabling both of these features at the same time, because users will complain about the sorting of the summary row.

**Comment by AMBudnik** [comment]
In 8.0.0-beta1 (and soon introduced 8.0.0 stable version) it will be possible to lock some rows from being sorted https://jsfiddle.net/AMBudnik/4mz2qony/

**Comment by toresenneseth** [comment]
Ah, so with this API, it looks like you can exclude _any_ row from being sorted. This is very useful, and solves another issue for us in the way we use handsontable (or rather, the type of data we display).

I will keep a lookout for v8 and try it as soon as I get a chance.
-Thanks
