### ISSUE TITLE
autoColumnSize

### ISSUE THREAD

**Issue by duncanluo** [handsontable/handsontable#6805]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey @duncanluo 

if you're having any issue with the AutoColumnSize please fill the issue with demo and step-by-step description on how to replicate the issue. Till that time I'm keeping this topic closed.
