### ISSUE TITLE
customize column header with react? 

### ISSUE THREAD

**Issue by mx2323** [handsontable/handsontable#6809]
hi there, i didn't see this mentioned anywhere, but is there anyway to customize the header when using the react wrapper beyond setting the text? 

I would just like to have each column have a line of text in bold, and some other text in italic on the line below it.

thanks!

**Comment by AMBudnik** [comment]
HI @mx2323 

you can use the afterGetColHeader hook to add HTML (bold, italic). Here's an example https://jsfiddle.net/AMBudnik/bqokf213/
