### ISSUE TITLE
Setting the height in CSS does not trigger the virtual scrolling

### ISSUE THREAD

**Issue by stof** [handsontable/handsontable#681]
If the height of the element is set in CSS instead of being set through the ``style`` attribute in the DOM, the virtual scrolling is not applied properly, making the extra rows overflow from the container.

see http://jsfiddle.net/hU6Kz/2130/ for a reproduceable case. I put some text after the table to make it clear it overflows.

**Comment by AMBudnik** [comment]
Hi guys, I've tried it on Chrome 41.0.2272.104 (64-bit) on mac, text is displayed below (not behind). Please leave us a feedback if after updating to 0.14.1 this issue will still occur. Till the issue will stay unreplied it'll be closed.
