### ISSUE TITLE
表格里的公式可以自定义吗,就比如使用office excel里的公式(=sum(a1+a2))

### ISSUE THREAD

**Issue by 17853490062** [handsontable/handsontable#6810]
表格里的公式可以自定义吗,就比如使用office excel里的公式(=sum(a1+a2))

**Comment by AMBudnik** [comment]
Hi @17853490062 

As long as `A1` and `A2` are numbers `'=SUM(A1 + A2)'` will work. Example https://jsfiddle.net/AMBudnik/hcy1fbjr/
