### ISSUE TITLE
not scrolling vertically? 

### ISSUE THREAD

**Issue by mx2323** [handsontable/handsontable#6812]
### Description
i read through the documentation, and something is still not clear to me. 

my table appears to be scrolling horizontally ( i actually really like how when i scroll to the right, it takes up the entire screen...

but it doesnt appear to be able to scroll vertically at all. 

https://imgur.com/a/Gin5h0b

any quick tips on how to get the table to scroll vertically?

**Comment by pnowak** [comment]
Hi @mx2323 

Without a demo, can be hard to find a solution. Especially we don't have an issue similar to yours.

Can you attach a demo where we can reproduce the issue? 
Do you use some bootstrap or material UI?

**Comment by mx2323** [comment]
pnowak - thanks for the reply! gotta say, ive tried a bunch of react spreadsheet libraries and definitely handsontable is the best. 

not sure if this counts as a demo - but here's a quick way to get to this issue. 
**you can try the following -** 
go to http://devel.structure.rest:8080/app/editor
drop this example csv file on the bar on the part on the left https://gist.github.com/mx2323/a603c50721801ff509694072d6008bff. 
you'll see a handsontable on the right - this one actually works because i hard code the height to 320px.

to get to the one that doesnt work - 
drag **transform** from the steps on the left to the canvas, then connect your file to the transform step, then click on the transform step to see the handsontable that doesn't scroll vertically. 


i uploaded a short 15 second video here to show you how to get to the table that doesnt work - 
https://imgur.com/a/06qT5aM

**Comment by mx2323** [comment]
for now, i just hard set the width and height.
