### ISSUE TITLE
Store Manual Column Widths by Prop

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#6814]
👋 

Have another suggestion for y'all.

We've run into a little bit of a UX snafu when we have `manualColumnResize` turned on, as well as `persistentState` and we add a new column to the data.

Imagine the scenario where you have 2 columns in your data:

| Name | Email |
| --- | --- |
| Aaron | aaron@example.com |

And your user has manually sized those columns to be sizes e.g. 100 and 200

| Name | Email |
| --- | --- |
| (100) | (200) |
| Aaron | aaron@example.com |

With the `manualColumnResize` plugin, the data will be stored in localStorage as 

```
[100, 200]
```

But then when you add a new column, this all gets mucked up. So let's say we add ID:

| ID | Name | Email |
| --- | --- | --- |
| (100) | (200) | (null) |
| 1 | Aaron | aaron@example.com |

Now the width that the user specifically set for "Name" is being applied to "ID", and the width for "Email" is being applied to "Name" because the stored state is still `[100, 200]`.

My preference would be that the stored state be an object of `{prop: width}`, to more accurately represent the user's intention. The user resized the "Name" column, it is mostly irrelevant that "Name" happened to be index `0` at one point. 

If there are no props, you could still store the data as e.g.

```
{
  0: 100,
  1: 200,
}
```

and get exactly the same behavior you have now!

No rush on this. As a workaround, we currently intercept the `persistentState` hooks and do this ourselves, but it would be nice to have the core handle this for us. (We're also storing filter conditions by prop, which lets our users save filters between reloads, which is great. But that's another issue for another day!)

**Comment by AMBudnik** [comment]
True, there is no change whenever we add new columns. 

I see that you suggested recreating the values to return an object 

```js
{
  0: 100,
  1: 200,
}
```

I would like to receive this `[100, undefined, 200]`, but I get the point. It's a lot of manual work when we allow adding columns.

**Comment by AMBudnik** [comment]
Hi @aarondfrancis 

I'm moving this topic to Github Discussions. And I welcome everyone interested in the subject to discuss this functionality and share their feedback.

See you there!
