### ISSUE TITLE
beforeremovecellclassnames doesn't work

### ISSUE THREAD

**Issue by hujinbo** [handsontable/handsontable#6817]
### Description

I want to use `beforeremovecellclassnames` to clear the class name of the `afterdrawselection` setting, but it doesn't work.

### Steps to reproduce

1. Set the class name of the current row and column in the `afterdrawselection` method.
2. Clear the old class name "currentarea" in the `beforeremovecellclassnames` method.
3. Click the table several times, you will find that the old class name has not been clear up.

### Demo

https://codesandbox.io/s/xenodochial-neumann-lkkzh
![Animation](https://user-images.githubusercontent.com/29507557/79449153-4a73e800-8015-11ea-9017-e081f0a08c14.gif)

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 81.0.4044.92
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
Hi @hujinbo 

The docs say it's suppose do be an array of strings, not a string. Have you tried that?

**Comment by hujinbo** [comment]
> Hi @hujinbo
> 
> The docs say it's suppose do be an array of strings, not a string. Have you tried that?

Ohhh...I was confused by trying too many methods, but I managed to do it with your help now. Appreciated for your kind support. 
I use the following code to achieve the effect I want.
```
  afterDrawSelection: function(
    currentRow,
    currentColumn,
    cornersOfSelection,
    layerLevel
  ) {
    var startRow = cornersOfSelection[0];
    var startColumn = cornersOfSelection[1];
    if (currentRow === startRow || currentColumn === startColumn) {
      return "currentArea";
    }
    return;
  },
  beforeRemoveCellClassNames: function() {
    return "currentArea";
  }
```
![2](https://user-images.githubusercontent.com/29507557/79484715-a9058a00-8046-11ea-9049-e75f54d8b156.gif)  


But I have another question: 
When I use `currentrowclassname` and `currentcolclassname ` and click the header, why do all the rows and columns apply my class name.
https://codesandbox.io/s/pensive-margulis-4mrh6
![1](https://user-images.githubusercontent.com/29507557/79484078-bc642580-8045-11ea-85e2-0a5f6db47dc3.gif)

**Comment by pnowak** [comment]
Hi @hujinbo 

> why do all the rows and columns apply my class name.

This is intended behaviour for `currentRowClassName` as it is written in our docs - https://handsontable.com/docs/7.4.2/Options.html#currentRowClassName
