### ISSUE TITLE
Can I trigger a click event on a cell manually? 

### ISSUE THREAD

**Issue by nvacheishvili** [handsontable/handsontable#6822]
### Description
Is there a way to trigger a click event on a cell manually? There are bunch of things I'd like to happen afterOnCellMouseDown, but I cannot trigger the event manually (without the user actually clicking on it).  @AMBudnik

**Comment by AMBudnik** [comment]
Hey @nvacheishvili 

that's a programming issue. Here's a related topic https://stackoverflow.com/questions/2381572/how-can-i-trigger-a-javascript-event-click

**Comment by nvacheishvili** [comment]
@AMBudnik I do not think so, since I used click, mousedown events using 'trigger' or just plainly calling the function using jquery. Could you please provide a demo on how to trigger a click using javascript? Does not matter if its vanilla JS or jquery.

**Comment by AMBudnik** [comment]
Our official API does not contain a method to achieve this goal. But if you could share your latest progress I can review the code and share some hints.

**Comment by nvacheishvili** [comment]
Hi @AMBudnik, thanks for reaching out. This is a simple demo that I grabbed from your website, along with all click events I tried to setup so that I could manually trigger clicking on EUR, but its not working out. 
https://jsfiddle.net/mn5uac3y/2/
Let me know your thoughts on this please.

**Comment by AMBudnik** [comment]
A single click on a cell only results in a cell selection. You do not need to fake the click event to achieve this goal - you can call [`instance.selectCell(row_index, column_index)`](https://handsontable.com/docs/7.4.2/Core.html#selectCell). Was that the goal?

**Comment by nvacheishvili** [comment]
@AMBudnik no, the goal is to trigger afterOnCellMouseDown manually without the user needing to actually click on a cell

**Comment by nvacheishvili** [comment]
Also, I think this should be a very simple thing to achieve - I looked through your codebase and implementations that are available publicly but could not find much about why a click event triggered manually like this could be prevented.

**Comment by AMBudnik** [comment]
Still, I do not think that this is the way we should do it @nvacheishvili 
Every attempt to trigger click events programmatically is considered ambivalent...
I'm sure that setting up a function to run whatever you hold in your `afterOnCellMouseDown` and just running it on the page load (or Handsontable initialization) would be much better.

What do you run inside the `afterOnCellMouseDown` that needs to be called on the initialization (by the force click you requested)?

**Comment by nvacheishvili** [comment]
I know this could be avoided and I could write a workaround for it, but I think I have already too many things that are set up and working right in my afterOnCellMouseDown function. I understand that you might think this is the right way to do it, but I was just wondering if I could do it. I really think triggering a call manually should not have been such a big deal. So is there no way to do it? @AMBudnik

**Comment by nvacheishvili** [comment]
The workaround would just take much more dev time, so if there is a way that you know this could work, please let me know

**Comment by AMBudnik** [comment]
I'll discuss this subject with @pnowak and come to to you shortly

**Comment by pnowak** [comment]
Hi @nvacheishvili 

I prepared the demo on how to resolve your issue.
Here is a link - https://jsfiddle.net/mfhqz69L/

You need to know that we can't listen `click` because `click is fired after a full click action occurs; that is, the mouse button is pressed and released while the pointer remains inside the same element. mousedown is fired the moment the button is initially pressed.` 
This is a link to full documentation - https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event

**Comment by natashkela** [comment]
Hi @AMBudnik and @pnowak - I really appreciate that you took your time for resolving this issue. 
I am thinking that we will probably try to do a workaround for this issue since initMouseEvent function might be dropped any time according to the documentation - https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/initMouseEvent

**Comment by AMBudnik** [comment]
Great @natashkela let me know about the result

**Comment by AMBudnik** [comment]
Hey @natashkela 
If you'd have any additional questions regarding this query please send me an email to support@handsontable.com

**Comment by nvacheishvili** [comment]
@AMBudnik thanks will do! 👍

**Comment by heaxo** [comment]
I also have this requirement. I need to manually trigger a click on a cell. I tried to use getCell to call the click() event, but Handsontable did not trigger some hooks

**Comment by adrianszymanski89** [comment]
Hi @heaxo 

Did you try the solution provided earlier in this topic? It should meets your requirement: https://jsfiddle.net/aszymanski/ojftnwpv/

**Comment by adrianszymanski89** [comment]
Hi @heaxo 

Did you try the solution provided earlier in this topic? It should meets your requirement: https://jsfiddle.net/aszymanski/ojftnwpv/
