### ISSUE TITLE
GanttChart initialization is broken

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6827]
### Description

The _GantChart_ plugin messes with plugin initialization process. This affects all plugins which use property `this.pluginName` (defined in the Base class).  The property holds the original plugin name but somehow the _GanttChart_ resets that property to `null`. The plugins which are imported below the _GanttChart_ (https://github.com/handsontable/handsontable/blob/master/src/plugins/index.js#L34) are affected. 

The issue occurs while developing and testing the 8.0.0 version. It needs to be investigated.

### Your environment
* Handsontable version: 7.4.1
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment]
As [support for the Gantt Chart is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7022) we decided to close all the issues that relate to that feature.
