### ISSUE TITLE
Undo should not work for cells merged on the initialization

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6829]
### Description

Undo should not work for cells merged on the initialization, the cells that the developer set up to be merged. 
Currently, even the cell that is set up on the initialization can be undone.

### Steps to reproduce

1. Select cells `A1:D5`
![Zrzut ekranu 2020-04-22 o 15 15 55](https://user-images.githubusercontent.com/10757813/79986369-3b28ea80-84ac-11ea-8f4c-f0e018a4cc30.png)
2. Merge those cells
3. Use <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd> to undo the changes

**Result**
![Zrzut ekranu 2020-04-22 o 15 18 12](https://user-images.githubusercontent.com/10757813/79986538-817e4980-84ac-11ea-94c3-67a3bbd8f92c.png)

4. Click <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd> again
![Zrzut ekranu 2020-04-22 o 15 18 40](https://user-images.githubusercontent.com/10757813/79986594-96f37380-84ac-11ea-82fe-5692d7811b3c.png)

### Related issues
* https://github.com/handsontable/handsontable/issues/6374

### Demo

http://jsfiddle.net/AMBudnik/eLyb3dzm/

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/04e1tvru/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
