### ISSUE TITLE
[Extension point request] Expose the editor implementation classes

### ISSUE THREAD

**Issue by stof** [handsontable/handsontable#683]
Our project uses a datepicker plugin for Bootstrap, which conflicts with the jQueryUI plugin (they both use ``.datepicker()``) but provides a different API. So I cannot use the built-in DateEditor to provide a datepicker on a field.
I wanted to copy its code and adapt it for the bootstrap-datepicker, but I cannot as it accesses ``HandsontableTextEditorClass`` which is kept private inside the Handsontable build. Would you accept a PR exposing these objects to allow extending them when building our own editors instead of having to copy-paste the whole TextEditor ?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
I'm transferring this issue into a discussion.
Please feel free to leave your comment and suggestion for this change.
