### ISSUE TITLE
Wrong union type for `startPosition`

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6840]
### Description
It is a wrong union type `startPosition: number | number`. 
It should be `number | null`.

**Comment by wojciechczerniak** [comment]
@pnowak Looks like this issue has a merged PR and awaits QA. But it's not added to a release. Can you update it's status?

**Comment by pnowak** [comment]
Updated in https://github.com/handsontable/handsontable/issues/6465

**Comment by aninde** [comment]
On current main stable 7.4.2 is:
https://github.com/handsontable/handsontable/blob/88d78a5be5e37ad703c11914c86690d2436d3024/handsontable.d.ts#L2019

On `v8` will be:
https://github.com/handsontable/handsontable/blob/5051859a956f409efcfdf435deb5db3ad33922f2/handsontable.d.ts#L1959

**Comment by AMBudnik** [comment]
The issue officially solved in yesterday's release of Handsobtable v 8.0.0
