### ISSUE TITLE
[8.0.0-beta1] Backspace in filter by value option does not work initially

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6842]
@RanaOsamaAwadallah commented on [Mon Apr 27 2020](https://github.com/handsontable/react-handsontable/issues/181)

### Description
Backspace in filter by value option does not work initially. However if you focus out then focus in again it works.

### Steps to reproduce
1. Enable filters and dropdown
2. Try searching by value (type any value)
3. Delete (backspace)

### Demo
https://codesandbox.io/s/declaring-column-settings-1u5ew?file=/src/index.js

### Your environment
* React wrapper version: 3.1.3
* Handsontable version: 8.0.0-beta.1
* Browser Name and version: Chrome 81.0.4044.122 (Official Build) (64-bit)
* Operating System: Windows 10

---

@AMBudnik commented on [Mon Apr 27 2020](https://github.com/handsontable/react-handsontable/issues/181#issuecomment-619977133)

Thank you for sharing @RanaOsamaAwadallah 

I have replicated the same using simplified demo https://codesandbox.io/s/declaring-column-settings-plfc7 on Chrome 83 on Windows 10 and macOS Catalina.

The demo loads Handsontable `8.0.0-beta1` but it works well in `7.4.2` https://codesandbox.io/s/declaring-column-settings-jee5e

UPDATE: Issue is also replicable for Vanilla https://jsfiddle.net/AMBudnik/0f1q3aLv/

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/5415

**Comment by pnowak** [comment]
Fortunately, in our current develop branch works well - https://jsfiddle.net/mqvfha85/

**Comment by AMBudnik** [comment]
Thanks for checking @pnowak 
It has been added to the **Other fixed issues** section of the 8.0.0 epic.

**Comment by AMBudnik** [comment]
Works well in 8.0.0.-beta2-rev2 https://jsfiddle.net/4z978qe3/
