### ISSUE TITLE
Comments window disappears in ng handsontbale 5.1.0

### ISSUE THREAD

**Issue by ChandraAdapa10** [handsontable/handsontable#6844]
HI Team,

we are unable to add cell comments in nghandsontable as comments window disappearing.

### Your environment
* Handsontable version:5.1.0
* Browser Name and version:google chrome 81.0.4044.122
* Operating System:windows 10

**Comment by AMBudnik** [comment]
Hi @ChandraAdapa10 

We have noticed that comments do not show in 3 cases 
* https://github.com/handsontable/handsontable/issues/6661 in Firefox
* https://github.com/handsontable/handsontable/issues/3961 when window is resized
* when you have console opened (also relates to https://github.com/handsontable/handsontable/issues/3961)

Also, if you are using ngHandsontable it does not load the latest version of Handsontable by itself so you'd need to check the version. The ngHandsontable's latest version is [0.13.0](https://github.com/handsontable/ngHandsontable/releases) not 5.1.0. 5.1.0 is closer to the version of angular-handsontable, when the newest is the patch 5.1.1 (made 13 days ago https://github.com/handsontable/angular-handsontable/releases).

**Comment by ChandraAdapa10** [comment]
Hi AMBudnik,

it was my bad the version i mentioned was angular-handsontable.
I have upgraded to 5.1.1 and updated the dependencies to 7.4.2, but still comments window will disappear for few cells and I have observed that, if i try to add comment on same cell multiple times from contextmenu, after 3 or 4 times it started working .

could you please assist on this?

**Comment by AMBudnik** [comment]
Can you record it and send over a demo via Stackblitz, @ChandraAdapa10 ?

**Comment by ChandraAdapa10** [comment]
HI Ambudnik,

I am not sure we can reproduce this issue in Stackblitz ,I will create a demo and let you know 

thanks

**Comment by AMBudnik** [comment]
Hey @ChandraAdapa10 

If that helps you can use this demo as a base https://stackblitz.com/edit/angular-tybwca?file=src/app/hello.component.ts or the CodeSandbox which works slower but it's more organized (my opinion) https://codesandbox.io/s/setdataatcell-settimeout-external-call-in-angular-pg4gk

Here https://codesandbox.io/s/test-demo-comments-em74s I've made simple demo with comments
![Zrzut ekranu 2020-05-4 o 08 43 22](https://user-images.githubusercontent.com/10757813/80941714-71873380-8de3-11ea-9bfc-550c8b8d8844.png)
but it works as expected so it means that the issue might be related to some other settings or CSS presets.

**Comment by ChandraAdapa10** [comment]
Hi AM  Budnik,

Thanks for sharing the Demo, actually i tried to reproduce the issue in the demo and it is not happening but in our project we see this issue, removing handsontable dependencies and installing again will resolve this issue.

Thanks Again
Chandra Adapa

**Comment by AMBudnik** [comment]
> we see this issue, removing handsontable dependencies and installing again will resolve this issue.

Thank you for the update. Please share a comment once you test it and if the issue is replicable I will reopen the topic.
