### ISSUE TITLE
[UX] How can we avoid two scroll bars?

### ISSUE THREAD

**Issue by mrdivyansh** [handsontable/handsontable#6853]
### Description
When I render Handsontable (with no height and width) inside an HTML container (with fixed height and overflow auto) along with some other contents. I see two scroll bars one for the container and another for the table.

My expectation was to see one scroll bar for the container because I haven't assigned any fixed height to the table. Ideally, the table should take space as per its content instead of assuming a random fixed height and showing a scroll bar.

I think that it's kind of bad user experience when we show two scroll bars on a page/container. I avoid this situation as much as I can.

Do we have any workaround to fix this UX issue?

[GIF](https://user-images.githubusercontent.com/8512339/81294668-d87b4580-908c-11ea-89af-78ab3cb98c1b.gif)

### Demo
https://jsfiddle.net/6wtrqx8n/

### Your environment
* Handsontable version: 7+
* Browser Name and version: Any
* Operating System: Any

**Comment by AMBudnik** [comment]
Hi @mrdivyansh 

the table does not fit into the container so it needs to show a scroll - that is expected behavior. I believe that you may find some CSS hacks for that but that would require testing. 
I recommend checking the StackOverflow topics.
