### ISSUE TITLE
After re-rendering of react component, hiding colHeaders is invalid

### ISSUE THREAD

**Issue by hujinbo** [handsontable/handsontable#6854]
### Description

I configured the `colHeaders` in React, and clicked to hide it.
When state changes, causing the component to re-render, the header will be displayed again, which is incorrect. How can i fix it ?

### Steps to reproduce

1. Click the 'Hide header' button in the demo.
2. Click the 'Refresh' button in the demo.
3. You will see that the header is displayed again, and it is not aligned.

### Demo

https://codesandbox.io/s/inspiring-waterfall-mhzc9
![demo](https://user-images.githubusercontent.com/29507557/81305798-56e9de80-90b1-11ea-8ea6-63d2226295da.gif)

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 81.0.4044.92
* Operating System: Windows 10

**Comment by pnowak** [comment]
Hi @hujinbo 

If you change `colHeaders` state too in `refresh` everything is well displayed.
Here is an updated demo - https://codesandbox.io/s/strange-fire-s9u9w?file=/src/App.js

You have to do this because without it `colHeaders` is still `false` and hot-table admittedly render it in the next cycle but doesn't fit the rest of the table.

**Comment by hujinbo** [comment]
Hi @pnowak 
Thanks for your quick reply, but I'm afraid you misunderstood what I said.
In the demo you provided, when click `refresh`, the `colHeaders` is displayed again.
What I want is that when I `refresh`, the `colHeaders` remains hidden.

**Comment by pnowak** [comment]
Ok. I see now.

If you change the version of `handontable` to the newest 7.4.2, the issue will be gone.
Here is an updated demo - https://codesandbox.io/s/ecstatic-faraday-jj0u3

**Comment by hujinbo** [comment]
Ok, Thanks
