### ISSUE TITLE
[8.0.0-beta2-rev1] When nestedRows are enabled we cannot call updateSettings

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6855]
### Description

When `nestedRows` are enabled we cannot call `updateSettings`. No further actions required.
The issue is now visible when we use `updateSettings` to pass` nestedRows: false` http://jsfiddle.net/nbo8Lf7z/

After fixing check https://github.com/handsontable/handsontable/issues/4716

### Steps to reproduce

1. Open the console to see the error

### Demo

http://jsfiddle.net/vye5p2n3/ 8.0.0-beta2-rev1 (**broken**)
http://jsfiddle.net/vye5p2n3/1/ 8.0.0-beta1 (working well)
http://jsfiddle.net/vye5p2n3/2/ 7.4.2 (working well)

### Your environment
* Handsontable version: 8.0.0-beta2-rev1
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by wszymanski** [comment]
May be related to the https://github.com/handsontable/handsontable/pull/6678.

**Comment by AMBudnik** [comment]
Might be a cause of the following misalignment of rows and false `rowHeaders`

http://jsfiddle.net/hLdjyamq/ (beta2)
![Zrzut ekranu 2020-05-12 o 14 50 33](https://user-images.githubusercontent.com/10757813/81693310-03d0ac80-9460-11ea-95b9-f77a85efe5c9.png)

http://jsfiddle.net/L6mpz9wj/ (beta1)
![Zrzut ekranu 2020-05-12 o 14 50 41](https://user-images.githubusercontent.com/10757813/81693332-0a5f2400-9460-11ea-829b-fb4b0fbe9c14.png)

To be tested after fix.

**Comment by AMBudnik** [comment]
Both issues : Main and `rowHeaders: false` are gone in 8.0.0.-beta2-rev8 http://jsfiddle.net/AMBudnik/tv96f1qa/
