### ISSUE TITLE
[8.0.0.-beta2-rev2] Filter by value list is blank if we pick Filter by condition after choosing a value from Filters.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6861]
### Description

Filter by value list is blank if we pick Filter by condition after choosing a value from Filters.

Might be related to https://github.com/handsontable/handsontable/issues/6497

### Steps to reproduce

1. Go to column `C`
2. Scroll Filter by value to exclude `C8` (do not click OK)
3. Open Filter by condition list
4. Pick 'Is empty'

**Result**
The list of values in the Filter by value is gone.
![beta2](https://user-images.githubusercontent.com/10757813/81564200-ad983680-9397-11ea-857a-48502c2169fe.gif)

### Demo

https://jsfiddle.net/bjrpvcet/ 8.0.0.-beta1 (working)
https://jsfiddle.net/hzk0bop9/ 8.0.0.-beta2-rev3 (broken)

### Additional info
* issue is not replicable if we do not scroll the filter by value list at first (here to find C8). We do not need to pick `C8` to test it.

### Your environment
* Handsontable version: 8.0.0.-beta2-rev2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
Works the same in 8.0.0-beta2-rev8 https://jsfiddle.net/AMBudnik/fL3p89qo/

**Comment by wojciechczerniak** [comment]
@AMBudnik @aninde I don't see it on the regression list. What's the status here?

**Comment by AMBudnik** [comment]
Before (issue) the list of filter_by_value was empty, until we scrolled. 

![Zrzut ekranu 2020-07-2 o 11 17 23](https://user-images.githubusercontent.com/10757813/86340774-b7cb0880-bc55-11ea-93a0-fb59ca19901a.png)

However, now (8.0.0-beta2-rev18) it is working as expected

![solved](https://user-images.githubusercontent.com/10757813/86340780-b994cc00-bc55-11ea-9643-8e2389b270c7.gif)

I would remove it from the 8.0.0 release epic as this was a regression. What we should do it is to add it to the 'Test for beta2' on /quality repository and close it as solved.
