### ISSUE TITLE
When we move rows and undo the move handler position does not update

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6863]
### Description

When we move rows and undo the move handler position does not update. As a result, we can resize another row.

### Steps to reproduce

1. Move row 3 to after 5th row
2. Resize row 4
3. Click <kbd>CTRL/CMD</kbd>+<kbd>Z</kbd> to undo

![move](https://user-images.githubusercontent.com/10757813/81655489-90ff0b80-9436-11ea-905b-15cf846c47fa.gif)

**Result**
Resize handler is still available and if we use it, it resizes a wrong row.

### Demo

https://jsfiddle.net/cpv9eLzx/2/ 7.4.2

### Additional info
* works the same in 8.0.0.-beta2-rev3 (11.05) https://jsfiddle.net/cpv9eLzx/3/
* It doesn't seem to work differently in any version

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/pna1xft2/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
