### ISSUE TITLE
[8.0.0.-beta2-rev3] Can't resize column just after the hidden one

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6867]
### Description

If we try to resize the second column (`C`) we can't. 
On the other hand, if we try to resize the next one (`D`) we resize the previous one (`C`).

![May-12-2020 12-06-13](https://user-images.githubusercontent.com/1555809/81671493-5783cb80-9449-11ea-91af-1a7c436f13e3.gif)

In version  8.0.0-beta.1 works well - https://jsfiddle.net/kp1av0ch/

### Steps to reproduce

1. Try to resize the second column (`C`).

### Demo

https://jsfiddle.net/34uh2ndc/

### Your environment
* Handsontable version: 8.0.0.-beta2-rev3
* Browser Name and version: Chrome 80
* Operating System: macOS Mojave

**Comment by aninde** [comment]
Previous, the wrong column is resized. Row resizing works.

https://jsfiddle.net/aninde/9hmo5j71/ v7.4.2 (works)
https://jsfiddle.net/aninde/9tcudhgm/ v 8.0.0-beta1 (works)
https://jsfiddle.net/aninde/nce3sjoL/ v8.0.0.-beta2-rev5 (broken)
https://jsfiddle.net/aninde/yxeuo5ta/ v8.0.0.-beta2-rev3 (broken)

Case 2
Adding some fixed columns significantly reduces performance
https://jsfiddle.net/aninde/7r2s8wny/ v8.0.0.-beta2-rev5 (broken)
https://jsfiddle.net/aninde/bf5yrhoa/ v 8.0.0-beta1 (works)

**Comment by AMBudnik** [comment]
**Solved** in 8.0.0-beta2-rev10 https://jsfiddle.net/AMBudnik/bLgwnjrz/

![resize](https://user-images.githubusercontent.com/10757813/83264532-811a5200-a1c0-11ea-826b-d4aad5e2f657.gif)
