### ISSUE TITLE
Undo: Add support for fixing columns

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6869]
### Description

We are not able to undo/redo fixing columns - in the result when we remove fixed columns and bring them back they're not fixed anymore.

### Steps to reproduce

1. Remove columns A-C that are fixed
2. Undo

![fixed](https://user-images.githubusercontent.com/10757813/81675171-ada73d80-944e-11ea-9ef7-9781afab2e85.gif)

**Result**
Columns are back but they're not fixed.

### Demo

https://jsfiddle.net/sm7d8x4n/1/

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: n/a
* Operating System: n/a

**Comment by aninde** [comment]
This issue will be fixed by `v8` with changes on selection after restoring removed columns. 
https://jsfiddle.net/aninde/whezjkpm/1/
![fixed-8](https://user-images.githubusercontent.com/30186818/89304333-9d79b580-d66d-11ea-9b54-14f787fa1bc8.gif)

**Comment by AMBudnik** [comment]
For anyone following this topic: We just launch Handsontable v 8.0.0 where this issue is fixed.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
