### ISSUE TITLE
Change Header Issue

### ISSUE THREAD

**Issue by ajrkadakkal** [handsontable/handsontable#687]
How to change header fields dynamically  based on the cell field changing?

**Comment by AMBudnik** [comment]
Can you specify what and how you would like to change? We provide a `updateSettings` method which you can call (more about [methods](https://github.com/handsontable/handsontable/wiki/Methods)). Maybe you could provide a demo?

**Comment by AMBudnik** [comment]
Issue closed in lack of needed demo. If you still face this issue please prepare one and we'll see what we can do.
