### ISSUE TITLE
[8.0.0.-beta2-rev1] Merged area is not highlighted if a part of it is hidden

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6873]
### Description

Merged area is not highlighted if a part of it is hidden.

### Steps to reproduce

1. Go to https://jsfiddle.net/h8t7wmdr/
2. Select columns `A-C`

**Result**
The merged area is not highlighted
![Zrzut ekranu 2020-05-13 o 10 10 42](https://user-images.githubusercontent.com/10757813/81788244-87db7080-9502-11ea-8ec9-7495f70ac7cb.png)

**Expected result**
![Zrzut ekranu 2020-05-13 o 10 10 11](https://user-images.githubusercontent.com/10757813/81788266-8f027e80-9502-11ea-9965-4f24488483d6.png)

### Demo

https://jsfiddle.net/h8t7wmdr/ 8.0.0.-beta2-rev3 (broken)
https://jsfiddle.net/235snLvr/ 8.0.0.-beta2-rev1 (broken)
https://jsfiddle.net/8uho2f3L/ 8.0.0-beta1 (works well)
https://jsfiddle.net/8uho2f3L/1/ 7.4.2 (works well)

### Your environment
* Handsontable version: 8.0.0.-beta2-rev1
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
Works the same if we hide right part (without visible data) https://jsfiddle.net/7a3cq2mt/
![Zrzut ekranu 2020-05-13 o 10 24 06](https://user-images.githubusercontent.com/10757813/81789178-e48b5b00-9503-11ea-9bae-42ff72410979.png)

**Comment by AMBudnik** [comment]
### Case 2
Context menu for merged cell sows different option in context menu
https://jsfiddle.net/AMBudnik/ktqogzwb/ 8.0.0.-beta2-rev7 - 8.0.0.-beta2-rev10
https://jsfiddle.net/AMBudnik/dbcqm7vk/1/ 7.4.2 - 8.0.0-beta2-rev6

**Steps**
1. Go to https://jsfiddle.net/AMBudnik/ktqogzwb/
2. Open context menu for `A` header

**Result**
In versions from 8.0.0.-beta2-rev7 to 8.0.0.-beta2-rev10 we get `Merge cells` option
![Zrzut ekranu 2020-06-4 o 07 42 51](https://user-images.githubusercontent.com/10757813/83719337-2d33c100-a637-11ea-9fce-2985ae306a51.png)

**Steps**
1. Go to https://jsfiddle.net/AMBudnik/dbcqm7vk/1/
2. Open context menu for `A` header

**Result**
In version from 7.4.2 to 8.0.0.-beta2-rev6 we get `Unmerge cells`
![Zrzut ekranu 2020-06-4 o 07 45 00](https://user-images.githubusercontent.com/10757813/83719422-55bbbb00-a637-11ea-912c-e9a7fb645348.png)

**Comment by aninde** [comment]
A list of known bugs that can be related:
- Merged Cells + selection causes improper merge cell highlight. #4859
- Hiding rows while there is a merged area involved causes data shifting and unexpected merged area coordinates #6376

**Comment by AMBudnik** [comment]
Main case **solved** with 8.0.0-beta2-rev13 https://jsfiddle.net/AMBudnik/8fjdnq0p/
The case 2 **solved** with 8.0.0-beta2-rev13https://jsfiddle.net/AMBudnik/js1dwt7y/

Well done!
