### ISSUE TITLE
[8.0.0.-beta2-rev3] Show column/row doesn't work when column/row has been moved

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6874]
### Description
It occurs when we move column which is before the hidden one. In our case this is the first column.

Previously, in version 8.0.0-beta.1 and 7.4.2, although after moving we have a bug the proper column is showing well.

version 8.0.0-beta.1 - https://jsfiddle.net/7gfqhdaL/

7.4.2 - https://jsfiddle.net/qgbheLkt/

### Steps to reproduce

1. Move the first column `A` after column `C`.
2. Click button `Show column`.

### Result
Nothing happen.

### Expected
Column `B` should be shown.

### Demo

https://jsfiddle.net/o2xmfet5/

### Your environment
* Handsontable version: 8.0.0.-beta2-rev3
* Browser Name and version: Chrome 80
* Operating System: macOS Mojave

**Comment by pnowak** [comment]
The analogical situation we have when we try show row after the first row was moved.  

Here is a demo - https://jsfiddle.net/6m3zw2xk/

### Steps to reproduce

1. Move the first row `1` after row `3`.
2. Click button `Show column`.

### Result
Nothing happens.

### Expected
Row `2` should be shown.

**Comment by wszymanski** [comment]
To be precise. At the start visual index `1` (physical index `1`) is hidden. After moving the column `A` after column `C` (column `B` is hidden) we have hidden visual column index `0` (physical column index `1`).

Hidden columns and it's `showColumn` work using visual column indexes, so calling `showColumn(1)` should give no effect (visual column index `1` isn't hidden). However, `showColumn(`0`) should work properly also for selection. @budnix fixed bug for it.

**Comment by AMBudnik** [comment]
Main issue in 8.0.0-beta2-rev11 https://jsfiddle.net/AMBudnik/1fa4d3jr/ @pnowak can you confirm?

Issue for moving rows **solved** in 8.0.0-beta2-rev11 https://jsfiddle.net/AMBudnik/x3mw1kcv/

![fixed](https://user-images.githubusercontent.com/10757813/83749977-df35b200-a664-11ea-814d-c23b214720c9.gif)

**Comment by wojciechczerniak** [comment]
@AMBudnik @pnowak Why it's not closed, yet? Do we have something to do here?

**Comment by pnowak** [comment]
Yes, I confirm as regards to the main issue. 

But the issue for moving rows are **not** solved in 8.0.0-beta2-rev11 https://jsfiddle.net/AMBudnik/x3mw1kcv/
Neither in rev-18 - https://jsfiddle.net/AMBudnik/x3mw1kcv/

**Comment by wojciechczerniak** [comment]
Regression fixed 👍
