### ISSUE TITLE
[8.0.0.-beta2-rev3] Comment doesn't show the value.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6875]
### Description
If we have a comment in column after hiding column it isn't showing its value.

### Steps to reproduce

1. Hover over at a cell `C3`.

### Result
Comment area is empty.

### Expected
Comment `Bar` should be shown.

7.4.2 - https://jsfiddle.net/m6x0w7nz/
8.0.0. beta-1 - https://jsfiddle.net/4pe697hf/
8.0.0. beta-2-rev3 - https://jsfiddle.net/neu4jh0a/

### Your environment
* Handsontable version: 8.0.0. beta-2-rev3
* Browser Name and version: Chrome 80
* Operating System: macOS Mojave

**Comment by pnowak** [comment]
When you move column with a comment after hidden column, the value of comment disappears.

Here is a demo - https://jsfiddle.net/ygonedvz/
Move the first column to `D`.
![May-22-2020 14-03-52](https://user-images.githubusercontent.com/1555809/82667424-202ad100-9c38-11ea-96a1-161239722f40.gif)


Additionally, after moving the column `A` changing to `C`.

**Comment by AMBudnik** [comment]
Main issue **solved** with 8.0.0.-beta2-rev11 https://jsfiddle.net/AMBudnik/obn8y2t0/

![Zrzut ekranu 2020-06-4 o 13 33 05](https://user-images.githubusercontent.com/10757813/83751943-f88c2d80-a667-11ea-9c86-ee90f53a1fa2.png)

Case with moving columns also **solved** with 8.0.0.-beta2-rev11 https://jsfiddle.net/AMBudnik/h5r9zdo6/
![solved](https://user-images.githubusercontent.com/10757813/83752067-2e311680-a668-11ea-8b93-447c72e5d707.gif)
