### ISSUE TITLE
[8.0.0.-beta2-rev3] Focus is staying in both - in the header input and cell textarea.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6877]
### Description
Only after the second click on the keys, the focus disappears from the input header.
![May-13-2020 13-31-03](https://user-images.githubusercontent.com/1555809/81807874-28d82480-951f-11ea-9fa2-edf070de5a82.gif)

In version `8.0.0-beta.1` works well - https://jsfiddle.net/49c6bzwd/
![May-13-2020 13-31-41](https://user-images.githubusercontent.com/1555809/81808068-73f23780-951f-11ea-8657-ff086a04da46.gif)

In `7.4.2` works well too - https://jsfiddle.net/v7Lsze4j/
![May-13-2020 13-32-04](https://user-images.githubusercontent.com/1555809/81808075-76ed2800-951f-11ea-8ab3-3d416e53da63.gif)

### Steps to reproduce

1. Focus in the header input
2. Next click in the cell.

### Result
Both areas are focused on.

### Expected
Only the cell area should be focused on.

### Demo

https://jsfiddle.net/1bxLm69y/

### Your environment
* Handsontable version: 8.0.0. beta-2-rev3
* Browser Name and version: Chrome 80
* Operating System: macOS Mojave

**Comment by pnowak** [comment]
In general, the focus is stolen by input. 

Here is a demo with `search` plugin - https://jsfiddle.net/5vmaqsd6/
<img width="279" alt="Zrzut ekranu 2020-05-13 o 15 17 53" src="https://user-images.githubusercontent.com/1555809/81817575-372d3d00-952d-11ea-8bdd-b38cf213f8ba.png">

**Comment by aninde** [comment]
Fixed by `8.0.0-beta.2-rev8` https://jsfiddle.net/aninde/t5hoa8v3/1/ 
![6877-rev8](https://user-images.githubusercontent.com/30186818/82921856-28a54380-9f79-11ea-94a9-68a24323e887.gif)

https://jsfiddle.net/aninde/5geyLt0k/ `8.0.0-beta.2-rev8` (fixed) demo with search plugin
