### ISSUE TITLE
[8.0.0.-beta2-rev1] We cannot autofill a merged cell if it's partly hidden

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6878]
### Description

We cannot autofill a merged cell if it's partly hidden. The red border is visible but the value does not populate.

### Steps to reproduce

1. Try to autofill the merged cell down

**Result**
![broken](https://user-images.githubusercontent.com/10757813/81809679-0562a900-9522-11ea-986b-2f7a6c78d4a2.gif)

**Expected Result**
![ok](https://user-images.githubusercontent.com/10757813/81809670-01cf2200-9522-11ea-90ee-d2e145b4db12.gif)

### Demo

https://jsfiddle.net/jvLwnx43/ 7.4.2 (works well)
https://jsfiddle.net/za4pgLto/ 8.0.0.-beta1 (works well)
https://jsfiddle.net/za4pgLto/1/ 8.0.0-beta2-rev1 (broken)

### Your environment
* Handsontable version: .0.0-beta2-rev1
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by wszymanski** [comment]
Extra cases here: https://github.com/handsontable/handsontable/pull/6939#pullrequestreview-419074546.

**Comment by wszymanski** [comment]
Waiting for https://github.com/handsontable/handsontable/pull/6939 @wojciechczerniak. There are some cases which don't work. I asked for help @aninde who will describe it here.

**Comment by aninde** [comment]
Described here issue is still broken on latest rev10 https://jsfiddle.net/aninde/gq31uprc/1/

This bug developed over the new beta versions, it was a little more fixed each time, so great job 🙂 Among others the double borders between cells were fixed.

Unfortunately, there are still things to improve in 8.0.0-beta2-rev10.
Described here issue is still broken on latest rev10. https://jsfiddle.net/aninde/gq31uprc/1/

Every case works better during rev7.
**Case 2**  merged from not hidden to not hidden https://jsfiddle.net/aninde/1fya0oxt/
![rev10c1](https://user-images.githubusercontent.com/30186818/83542792-c2ca3600-a4fb-11ea-878f-470043f04a27.gif)

It's possible to drag horizontally autofill from `mergedCells` to the end of the table.
**Exception**: when headers are off, one line escapes after autofill from right to left of the table. I will put on a new issue
However vertical autofill works better but gives the wrong result. After dragging autofill to A10, A6 & A7 are merged together, without display, and A8-A9-A10 are merged with A2 in the display.

**Case 3.** merged from hidden to not hidden https://jsfiddle.net/aninde/3pw7tqon/
![rev10cc2](https://user-images.githubusercontent.com/30186818/83542801-c5c52680-a4fb-11ea-9823-09da013f4a9e.gif)

merged cells do not display content
you cannot drag the autofill horizontally to the end of the table,
Vertical autofill from `mergedCells` doesn’t work also.

**Case 3. partially fixed** merged from not hidden to hidden https://jsfiddle.net/aninde/0w1vdjrn/
![rev10c3](https://user-images.githubusercontent.com/30186818/83542811-c9f14400-a4fb-11ea-9d76-f97b7c59bc65.gif)

you cannot drag the autofill horizontally to the end of the table.
**Vertical autofill is fixed.** Cells from A6-A9 are merged and A2 is displayed.

 **Case 4** merged from hidden to hidden https://jsfiddle.net/aninde/u0n1ygpz/
![rev10c4](https://user-images.githubusercontent.com/30186818/83542828-ce1d6180-a4fb-11ea-9b91-389a0d461d80.gif)

you cannot drag the autofill horizontally to the end of the table.
Vertical autofill is broken. Cell aren’t merged and display of content is wrong.

**Comment by AMBudnik** [comment]
Issue **solved** in 8.0.0-beta2-rev12 https://jsfiddle.net/AMBudnik/57sqLgk2/
We may experience lacking blue background, however, that is covered in other issue.

**Comment by aninde** [comment]
I checked, IMO case 3 and 4 are also repaired in rev12
Case 3 https://jsfiddle.net/aninde/7jpkchwn/ `v 8.0.0-beta2-rev12`
![case3-rev12](https://user-images.githubusercontent.com/30186818/84144719-091e1880-aa59-11ea-91a7-6cdb4024e319.gif)

Case 4 https://jsfiddle.net/aninde/0z5wgpj4/ `v 8.0.0-beta2-rev12`
![case4-rev12](https://user-images.githubusercontent.com/30186818/84144724-0ae7dc00-aa59-11ea-8e2c-1c411bd3b667.gif)
![rev12-4](https://user-images.githubusercontent.com/30186818/84144735-0fac9000-aa59-11ea-96a0-50c06a1b4767.gif)

**Comment by AMBudnik** [comment]
True. If we autofill hidden but merged cells it makes sense 👍 
Thanks for checking @aninde
