### ISSUE TITLE
Column width in relative dimensions

### ISSUE THREAD

**Issue by OlgaIOn** [handsontable/handsontable#6880]
Hi, is it possible to set column width in relative dimensions? (%, em)

**Comment by pnowak** [comment]
Unfortunately, relative dimensions aren't supported.

So no matter how you enter the numbers - https://handsontable.com/docs/7.4.2/Options.html#colWidths, they will be treated as if they were given in pixels

**Comment by AMBudnik** [comment]
Hi @OlgaIOn 

` colWidths: '100%'` sets all the columns to 100px wide.
`colWidths: '100em'` equals `colWidths: '100%'` equals `colWidths: '100rem'`.
Here's a related topic https://github.com/handsontable/handsontable/issues/5749

**Comment by OlgaIOn** [comment]
@pnowak, @AMBudnik, thanks for your reply. It's a pity! It would be very helpful. 
Could you please add this to your feature request list?

**Comment by AMBudnik** [comment]
@OlgaIOn Sure - but we'd require to specify how it should work. 

Would you agree that % values added to `colWidths` should scale the columns based on the width of the table? 

**Example**
If developer sets up `colWidths: ['10%', '50%', '30%']` while having a `500px` wide table, and `3` columns it total. They end up with columns resized to `50px, 250px, 200px`. 

If so, what happens in the cases when % values do not much 100% in total?

**Comment by OlgaIOn** [comment]
Hi @AMBudnik 

> Would you agree that % values added to colWidths should scale the columns based on the width of the table?

Yes

> If so, what happens in the cases when % values do not much 100% in total?

There is empty space on the right side of the table. Same as if the columns width is set in px:
https://jsfiddle.net/rub8cjo7/1/

**Comment by AMBudnik** [comment]
There's a large spectrum of cases that we'd need to consider but that is a good idea for a feature/improvement.

**Comment by AMBudnik** [comment]
Thank you for sharing the idea.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback.
See you there!
