### ISSUE TITLE
Bug: Nested headers and hidden columns highlight the next column

### ISSUE THREAD

**Issue by nikemax** [handsontable/handsontable#6881]
### Description
It seems there is a mistake in the algorithm of using multiple nested headers and hiding some of them. When to select some of the columns via clicking in the header - it highlight also next parent children 

### Steps to reproduce
1. Add 3 levels of nested headers
2. Add not the last columns in the parent children (3-rd layer) as hidden
3. Click on the 2-nd layer and see: the next column is highlighted too
![image](https://user-images.githubusercontent.com/1199745/81823907-87ac9680-953d-11ea-9825-41cc35e4e2c5.png)

### Demo
https://jsfiddle.net/ryc80sk4/

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: Any
* Operating System: Any

**Comment by AMBudnik** [comment]
@nikemax thank you for sharing.

* 8.0.0.-beta1 https://jsfiddle.net/Ldsv3tq0/ works the same
* 8.0.0.-beta2-rev1 https://jsfiddle.net/9vzrc7a8/1/ **fixed**
* 8.0.0.-beta2-rev5 https://jsfiddle.net/9vzrc7a8/ works the same as rev1

However, in beta2 the table does not fit the range it has been given. It's stretched and the hidden indexes are used across all the row levels.

We have already discussed this subject here https://github.com/handsontable/handsontable/issues/6879 and will fix that issue in the second stage.

Related subject https://github.com/handsontable/handsontable/issues/4964

I think that the issue can be added to the 8.0.0-beta2 release as it relates to a single header selection, not the non-contiguous one.

**Comment by pnowak** [comment]
Hi @nikemax 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment]
Hi @nikemax Now it's official. Handsontable v8.0.0 that solves this issue is live!   

I highly encourage you to test the new version and leave some feedback. 

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
