### ISSUE TITLE
[8.0.0.-beta2-rev1] The view of the table moves when clicked LMB on the corner in iframe

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6883]
### Description
After clicking the corner, the table will scroll when it is in an iframe. Unfortunately, the bug cannot be reproduced on earlier versions, because it occurs from `pre-beta2`

![Kapture 2020-05-13 at 19 46 13](https://user-images.githubusercontent.com/30186818/81848090-de719a80-9554-11ea-818f-6947aee86751.gif)

### Steps to reproduce

1. Open demo
2. Click LMB on a corner and select all cells

**Result:**
All cells should be selected, the view is shifted.

**Expected result:**
All cells should be selected, but a view on the table shouldn't be moved.

### Demo

https://jsfiddle.net/aninde/Lv9mfpcx/2/ - `v7.4.2` - can not be reproduced
https://jsfiddle.net/aninde/qvLw3z4y/ - `v8.0.0-beta1` - can not be reproduced
https://jsfiddle.net/aninde/4d2059b3/ `vpre-8.0.0.-beta2-rev1` **(broken)**
https://jsfiddle.net/aninde/nzg3j6ks/  `vpre-8.0.0.-beta2-rev3` **(broken)**
https://jsfiddle.net/aninde/jfqbc6a1/ `vpre-8.0.0.-beta2-rev5` **(broken)**

https://jsfiddle.net/aninde/h5z6k23x/ `vpre-8.0.0-beta2` - curently rev5 (broken), can be fixed after update of jsdelivery

### Your environment
* Handsontable version: pre-8.0.0.-beta
* Browser Name and version: Chrome, Firefox, Safari
* Operating System: macOS Catalina 10.15

**Comment by aninde** [comment]
Using shortcut `selectAll` by <kbd>ctrl+a</kbd>  does not cause this bug.

![ctrl+a rev5](https://user-images.githubusercontent.com/30186818/81915428-da845d80-95d2-11ea-85ce-e19b55e195a1.gif)

**Comment by wszymanski** [comment]
Should be done within https://github.com/handsontable/handsontable/pull/6541.

**Comment by aninde** [comment]
This bug is also replicable without iframe, with `rev6` on iPad on Chrome and Brave, but not on Safari.

**Comment by jansiegel** [comment]
This bug is not caused by an `iframe`. I replicated it on Chrome, Firefox and Safari without an `iframe` (also on an iphone on Safari).
It's basically the corner header scrolling the table after clicking it, when the table dimensions are narrower than its contents: https://jsfiddle.net/js_ziggle/nqh4aboj/

**Comment by AMBudnik** [comment]
Main issue **solved** in 8.0.0-beta2-rev12 https://jsfiddle.net/AMBudnik/4g0y6dw9/
![ok](https://user-images.githubusercontent.com/10757813/83881392-d87c6d00-a740-11ea-8bd4-a69638e67b2a.gif)


Tested on macOS Catalina
Chrome 80, Safari 13 and Firefox 77

**Comment by aninde** [comment]
Still solved in 8.0.0-beta2-rev13 https://jsfiddle.net/aninde/e40yw1s6/
