### ISSUE TITLE
[8.0.0.-beta2-rev5] Error when hovering over the fixed column header immediately next to the hidden column and setting manualColumnResize to true.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6885]
### Description
We got the error `Uncaught TypeError: Cannot read property 'left' of undefined` when hovering over header with fixed columns,  manualColumnResize set to true and immediately next to the hidden column.
![May-14-2020 09-50-07](https://user-images.githubusercontent.com/1555809/81908729-e3246600-95c9-11ea-9873-05c50bdc6fd9.gif)

In `beta.1` - https://jsfiddle.net/s4d9mopL/ - and `7.4.2` https://jsfiddle.net/hkeuq5of/1/ - we don't have this error.

### Steps to reproduce

1. Hover over the end of column `C`
2. Open a console and see an error message.

### Demo

https://jsfiddle.net/hk13wp47/1/

### Your environment
* Handsontable version: 8.0.0.-beta2-rev5
* Browser Name and version: Chrome 80
* Operating System: macOS Mojave

**Comment by pnowak** [comment]
A similar error exists for manual row resize and `fixedRowsTop` - `Uncaught TypeError: Cannot read property 'firstChild' of undefined`.

Here is a demo - https://jsfiddle.net/owzdy56c/

**Comment by AMBudnik** [comment]
8.0.0-beta2-rev11 https://jsfiddle.net/AMBudnik/rd93ncvk/ does not show the error for columns and rows https://jsfiddle.net/AMBudnik/7mzxfour/

Issue **solved**.
