### ISSUE TITLE
NestedRows, when collapsed, do not remain resized row heights for rows further than the first one.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6886]
### Description

NestedRows, when collapsed, do not remain resized row heights for rows further than the first one.

### Steps to reproduce

1. Collapse both parents
2. Db-click the resize handler to set the default height
3. Expand the parents

**Result**
Second row stays the same.
![res](https://user-images.githubusercontent.com/10757813/81912786-5c728780-95cf-11ea-855d-5004b9002b93.gif)

### Explaining the title.
We can see that the first row accommodated the new, db-clicked size while the 2nd remained to be 50px-heigh. If we add more values to colWidths we'd observe that the 3rd row, 4th and so on do not accommodate. 

### Demo

https://jsfiddle.net/tqexh5nu/ 7.4.2
https://jsfiddle.net/aepcu7th/1/ 8.0.0.-beta2-rev5 (works the same)

### Your environment
* Handsontable version: 7.4.2
_Doesn't seem to be version related_
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by wojciechczerniak** [comment]
How is that a bug? Was this functionality part of the spec?

Manual row resize (to whom double click belongs to) works on a single row. There is a potential for resizing multiple rows when they are selected but it's far from nested rows and double click may not belong there either.

IMO works as intended.

**Comment by AMBudnik** [comment]
Maybe that's not the perfect scenario @wojciechczerniak 🤔 You're right this does not feel bad.

However, I've tried something else and this looks like a big. 

1. Go to the same demo https://jsfiddle.net/AMBudnik/dwv04kpc/
2. Use db-click to  get default height of the 2nd cell
3. Collapse the first parent

![issue](https://user-images.githubusercontent.com/10757813/83756798-d8606c80-a66f-11ea-848a-debcc82ba5e6.gif)


works the same in rev11 of 8.0.0-beta2 https://jsfiddle.net/AMBudnik/ck8pjbrd/1/

**Comment by wojciechczerniak** [comment]
Yup, this looks like a bug. Heights should be stored in indexMap, but the children structure from nestedRows may interfere here. Heights are updated on row move or remove. But here, nothing like that happens. Maybe trimming should be taken under consideration CC @wszymanski 

A new issue then?

**Comment by wszymanski** [comment]
I would create a new issue. Probably the `GhostTable` is used for recalculation. I don't know why. It shouldn't happen as you said, @wojciechczerniak.

**Comment by AMBudnik** [comment]
Thank you @wszymanski @wszymanski for confirmation I've moved that issue to https://github.com/handsontable/handsontable/issues/6985
and I'm closing this one as won't fix - intentional.
