### ISSUE TITLE
[8.0.0.-beta1] Removing nested rows don't work in some cases + hooks get wrong parameters

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#6890]
### Description
There are two problems:

- Hooks `beforeRemoveRow` and `afterRemoveRow` get wrong arguments `[Handsontable < 8.0]` while removing collapsed rows (there are `null`s),
- @jansiegel found that row being parent with nested children can't be removed (an error is thrown) [`Handsontable >= 8.0.0.-beta1`].

### Steps to reproduce

1. Open the demo https://jsfiddle.net/wojciech/j4fs38oz.
2. Collapse all rows.
3. Remove the last row.

### Demo

https://jsfiddle.net/wojciech/j4fs38oz

**Comment by AMBudnik** [comment]
**Version Comparision scenario**
1. Remove row that contains `Best Metal Performance`
2. Check the console

![remove](https://user-images.githubusercontent.com/10757813/82990038-d9542700-9ffb-11ea-9f7f-addaf73a1f3e.gif)


8.0.0.-beta1 - 8.0.0.-beta2-rev7 https://jsfiddle.net/AMBudnik/4xzkvgau/
![Zrzut ekranu 2020-05-27 o 09 20 55](https://user-images.githubusercontent.com/10757813/82989764-782c5380-9ffb-11ea-8ffb-0575631f83b4.png)


8.0.0-beta2-rev8 https://jsfiddle.net/AMBudnik/1twjydzg/
![Zrzut ekranu 2020-05-27 o 09 21 59](https://user-images.githubusercontent.com/10757813/82989970-bd508580-9ffb-11ea-96fa-d8997784fc3a.png)
