### ISSUE TITLE
[8.0.0.-beta2-rev6] Invalid comment position right behind the hidden column

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6896]
### Description
If we want to add a comment in the column right behind the hidden column position of comment container has the wrong position. It is as if in the column without a hidden one.

<img width="518" alt="Zrzut ekranu 2020-05-15 o 12 43 37" src="https://user-images.githubusercontent.com/1555809/82042198-c95a5000-96a9-11ea-8b76-211b7daf1f7a.png">

Work well in 7.4.2 - https://jsfiddle.net/jo50zx9n/
<img width="519" alt="Zrzut ekranu 2020-05-15 o 12 43 12" src="https://user-images.githubusercontent.com/1555809/82042257-e1ca6a80-96a9-11ea-8593-63d8024c29a7.png">

and in beta.1 - https://jsfiddle.net/o7Lq6gk3/
<img width="519" alt="Zrzut ekranu 2020-05-15 o 12 42 53" src="https://user-images.githubusercontent.com/1555809/82042277-e98a0f00-96a9-11ea-8da2-b2bc4eeb3f25.png">

### Steps to reproduce

1. Select cell from column `C`.
2. Add a comment by `contextMenu`

### Demo

https://jsfiddle.net/41ksjdpe/

### Your environment
* Handsontable version: 8.0.0.-beta2-rev6]
* Browser Name and version: Chrome 81
* Operating System: macOS Catalina

**Comment by pnowak** [comment]
A similar issue occurs for a hidden row and `fixedRowsTop`. 

Additionally, if we add a comment in the first visible rows when we next hover over at the cell is showed a comment value from hidden one.

![May-22-2020 13-05-42](https://user-images.githubusercontent.com/1555809/82661835-0df76580-9c2d-11ea-8e61-01454ef99263.gif)


Here is a demo - https://jsfiddle.net/L6hgbp0o/

**Comment by AMBudnik** [comment]
**Solved** in 8.0.0-beta2-rev11 https://jsfiddle.net/AMBudnik/2csfk9pu/  for columns and https://jsfiddle.net/AMBudnik/dgfr1L9c/ for rows.
