### ISSUE TITLE
[8.0.0.-beta1] We cannot add (alter method) more than one row while using `nestedRows`

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6898]
### Description

We cannot add (alter method) more than one row while using `nestedRows`.

### Steps to reproduce

1. Click <kbd>Add 2 parents</kbd>

**Result**
Nothing changes, you get an error in the console.

![Zrzut ekranu 2020-05-18 o 12 44 05](https://user-images.githubusercontent.com/10757813/82204670-9b714780-9905-11ea-8550-3235a1c7d121.png)

### Demo

https://jsfiddle.net/8qLkxwsm/1/ 8.0.0.-beta2-rev6 (broken)
https://jsfiddle.net/8qLkxwsm/2/ 8.0.0-beta1 (broken)
https://jsfiddle.net/8qLkxwsm/3/ 7.4.2 (partly working)
In 7.4.2 if we call alter() for 2 rows only one is added, but there's no error.

### Related issues
* https://github.com/handsontable/handsontable/issues/6891

### Your environment
* Handsontable version: 8.0.0.-beta2-rev6
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
7.4.2 produces the same error is we try to undo adding new rows

![Zrzut ekranu 2020-05-18 o 13 43 00](https://user-images.githubusercontent.com/10757813/82209503-a334ea00-990d-11ea-8432-1eeb6afc48fe.png)

**Comment by jansiegel** [comment]
This should be fixed with #6889

**Comment by AMBudnik** [comment]
Solved in 8.0.0.-beta2-rev8 https://jsfiddle.net/AMBudnik/ptv2uLko/
![ok](https://user-images.githubusercontent.com/10757813/83006235-32c75080-a012-11ea-9051-c19edcc3aa91.gif)
