### ISSUE TITLE
[8.0.0-beta2-rev1] rowHeaders are shifted after clicking on corner when every columns are hidden

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6902]
### Description
When there is no defined width and height clicking on corner when all columns are hidden causes impropert shifted of rendered rowHeaders.
When example is open by codesandbox,  an additional error occurs: Assertion failed: Expecting an unsigned number.

Related to https://github.com/handsontable/handsontable/issues/6883

### Steps to reproduce

1. Open demo, click on a random cell.
2. Click <kbd>cmd + a</kbd> to select all cells.
3. Hide them all via contextMenu.
4. Click LMB on the corner.

![bug-rev1](https://user-images.githubusercontent.com/30186818/82222611-d08b9300-9921-11ea-9afc-728c312694e9.gif)

### Demo

https://codesandbox.io/embed/800-beta2-rev1-h2x03?codemirror=1 rev.6 **(broken)**
https://jsfiddle.net/aninde/sx906kfd/1/ 8.0.0-beta2-rev1 **(broken)**

### Your environment
* Handsontable version: pre-8.0.0.-beta2-rev1
* Browser Name and version: Chrome 81, Firefox 76, Safari 13.1
* Operating System: macOs Catalina 10.15

**Comment by aninde** [comment]
This bug can be reproduced in `v8.0.0-beta2rev7` https://codesandbox.io/embed/800-beta2-rev1-h2x03?codemirror=1

**Comment by jansiegel** [comment]
Should be fixed with #6883.

**Comment by aninde** [comment]
Solved by `8.0.0.-beta2-rev12` https://jsfiddle.net/aninde/ervnof5q/
