### ISSUE TITLE
trimRows and hiddenRows with certain settings break borders

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6904]
### Description

The `trimRows` and `hiddenRows` with certain settings break borders. It seems to break when we hide the first row.

### Steps to reproduce

1. Just open the example

![Zrzut ekranu 2020-05-19 o 11 50 17](https://user-images.githubusercontent.com/10757813/82312224-0df62c00-99c7-11ea-912a-755794e599a5.png)

### Demo

https://jsfiddle.net/AMBudnik/pda268gu/ 7.4.2 (broken)
https://jsfiddle.net/AMBudnik/eLmrh8s6/ 8.0.0.-beta2-rev6 (still broken)

### Relates issues
* https://github.com/handsontable/handsontable/issues/5817

### Your environment
* Handsontable version: 7.4.2
_It doesn't seem to be related to any version_
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
### Case 2
8.0.0.-beta2-rev6 https://jsfiddle.net/AMBudnik/vgL980ks/ (works the same in 7.4.2 https://jsfiddle.net/AMBudnik/ke4ny19o/)

![filter](https://user-images.githubusercontent.com/10757813/82321435-1e150800-99d5-11ea-925b-ca76f86d6601.gif)

**Steps to reproduce**
1. Filter out `A1`, `A2`, and `A3`

**Comment by wojciechczerniak** [comment]
@AMBudnik Do w need a duplicate for #5817?

**Comment by AMBudnik** [comment]
@wojciechczerniak I think that this issue should be checked after #5817  
as this one is more complicated - it adds double border when we trim rows.

**Comment by wojciechczerniak** [comment]
Those are lines from hidden rows, different issue. Probably metadata update on CRUDs. Will be obsolete after #6887, where lines are no longer added for hidden rows.

I guess we can review it after next beta2 builds

**Comment by AMBudnik** [comment]
Solved in 8.0.0-beta2-rev7 https://jsfiddle.net/AMBudnik/kgdfnwLs/

![Zrzut ekranu 2020-05-22 o 09 18 02](https://user-images.githubusercontent.com/10757813/82641746-28b9e200-9c0d-11ea-8c44-c792a8b5e2a3.png)

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 https://jsfiddle.net/3txwvp0c/. This issue is solved.
