### ISSUE TITLE
We cannot auto fill using db-click if hiddenRows is used

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6905]
### Description

We cannot auto fill using db-click if `hiddenRows` is used on the cells that are just right below the auto-filled cell.

### Steps to reproduce

1. Remove values from `A2:A7`
2. DoubleClick click the blue rectangle of `A1` to autofill

**Result**
Nothing changes.

![Zrzut ekranu 2020-05-19 o 12 44 05](https://user-images.githubusercontent.com/10757813/82317381-71d02300-99ce-11ea-9e79-be5982d38d68.png)

3. Go to https://jsfiddle.net/AMBudnik/3nvk4fs2/ instead and repeat steps 1 and 2

**Result**
You're able to autofill the values.

### Demo

https://jsfiddle.net/AMBudnik/q2nja86m/ 7.4.2 (broken)
https://jsfiddle.net/AMBudnik/c7w3n16e/ 8.0.0-beta2-rev6 (still broken)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by wojciechczerniak** [comment]
This should be retested on #6887 branch, or after merge

**Comment by AMBudnik** [comment]
**Does not change** for 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/gzjrd9kh/

**Comment by AMBudnik** [comment]
After a short chat with @wojciechczerniak we decided to
* change the label to 'feature'
* add 'to be discussed' label as there's no solution we can compare it

**Comment by aninde** [comment]
Update with `v8` https://jsfiddle.net/aninde/pnaLh1tc/.
Nothing changed.

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback.
See you there!
