### ISSUE TITLE
fragmentSelection doesn't work

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6906]
### Description

Since 6.1.0 the `fragmentSelection` option doesn't work. 

### Steps to reproduce

1. Try to select the table using the native selection;
2. After mouse up the selection disappears, shouldn't;

### Demo

https://jsfiddle.net/bdru0jm5/1/ (works)
https://jsfiddle.net/bdru0jm5/2/ (not) 

### Your environment
* Handsontable version: 6.1.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
This issue has been already raised by @jansiegel here https://github.com/handsontable/handsontable/issues/6083

**Comment by AMBudnik** [comment]
Issue solved with https://github.com/handsontable/handsontable/issues/6083 in Handsontable [v8.4.0](https://github.com/handsontable/handsontable/issues/7998). Updated demo https://jsfiddle.net/handsoncode/rcy0saet/
