### ISSUE TITLE
Organize the test suits for the hidden rows and columns plugin 

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6908]
### Description

As the IndexMapper is build-in into the Core it influences other modules such as Selection (with Transformation), Walkontable rendering, etc. For now, the _HiddenRows_ and the _HiddenColumns_ plugin are covered with a lot of different tests that checks if the above-mentioned modules work as it should when the index is hidden. However, some of them should be moved to Core as the HiddenMap is not strictly reserved for the our plugin (the map can be implemented/used by an external developer).

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: - 
* Browser Name and version: - 
* Operating System: -

**Comment by swistach** [comment]
This issue is closed temporarily. We will reopen it for development as it became a part of the test environment improvements task reported at #7581
