### ISSUE TITLE
Redux/Immutability issues

### ISSUE THREAD

**Issue by underfisk** [handsontable/handsontable#6909]
### Description

Currently, I'm developing a project using react (with hooks) and I ran into a performance issue running HoT with redux updates, it is very slow and provokes to re-render everything.
This gets out of control from HoT plugin consumer, we have no way of inspecting what's going behind the scenes but reconciliation is not being considered on references, most of components and values are the same (I'm also using Immutable.js List and convert down .toArray because for some reason HoT mutates my data when I send an array)
What I would like to know is what's the current status of immutability support/reconciliation?

### Steps to reproduce

1. Create a react project with hooks and configure a redux storage
2. Create around 100 rows, perform updates with a delay of ~2sec to simulate an HTTP request
3.Perform a single row update, new row, and batch update

### Demo

https://codesandbox.io/s/redux-hot-example-cyo4c
This demo doesn't show it correctly but gives an idea that if you set up with redux and it renders all rows and doesn't compare which ones must be re-rendered

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: All browsers
* Operating System: Arch Linux

**Comment by underfisk** [comment]
The data provided to Handsontable is mutated on plugin instead of being only updated in the internal structure when using redux we need to block using Immutable data structures, this is not good to deal with. 
Is there any way of disabling the mutation on the data provided?

**Comment by pnowak** [comment]
Hi @underfisk 

I'm not sure that disabling the mutation is possible in Handsontable.

I asked for help our React Developer.
I will surely notify you about the response.

**Comment by underfisk** [comment]
@pnowak The thing is that mutating data in React is a bad practise and we get no control over it also when using Redux the data is only changed via a reducer action.
With the time i see Handsontable doesn't support very well basic concepts nor React

**Comment by wojciechczerniak** [comment]
> @pnowak The thing is that mutating data in React is a bad practise and we get no control over it also when using Redux the data is only changed via a reducer action.
> With the time i see Handsontable doesn't support very well basic concepts nor React

How's that?

Javascript works this way. Any variable type other than primitive (https://developer.mozilla.org/en-US/docs/Glossary/Primitive) value will be passed around by the reference.

The very first example from Redux (https://redux.js.org/basics/reducers) says that you have to create a copy of the data to break the reference between the component and the redux store.

> We don't mutate the state. We create a copy with Object.assign(). Object.assign(state, { visibilityFilter: action.filter }) is also wrong: it will mutate the first argument. You must supply an empty object as the first parameter. You can also enable the object spread operator proposal to write { ...state, ...newState } instead.

This works both ways.

**Comment by underfisk** [comment]
@wojciechczerniak Do you guys test the plugin in React? React has to contain mostly immutable data structures, mutating will intercept the lifecycle and prevent re-renders. If you mutate directly the data, our structure will not provoke a re-render since we are not invoking the setState.
I know how javascript references work but with React you can't work the same way you work with vanillajs or as Vuejs (their structure is mentioned to be mutated since they have observers)
Now i mean there are visual problems with Handsontable, the white space, the merged cells that render empty td when it's not visible and also with redux we need to force our data structured with Immutable data, most of the plugins i've worked like AgGrid they don't mutate our data directly, they allow us to even stop their internal mutation
I'm just saying that we need to be notified of the changes but not updating directly the data we pass by reference

**Comment by AMBudnik** [comment]
Hi @underfisk we test all the plugins in vanilla, and the wrappers before each release. 

Thank you for sharing your concerns. You've made a clear statement of what you need and expect from the data management process. We value all feedback that allows us to define ideas clearly. It saves us a lot of additional questions.

Feel free to open a new ticket if you spot anything that concerns you (just please check if there aren't any similar issues already reported).

**Comment by jansiegel** [comment]
@underfisk The thing is, `@handsontable/react` is a React wrapper for a vanilla library, so it doesn't use React API for all the operations that are happening.
You can either break the reference, like @wojciechczerniak said, or utilize Handsontable's hook infrastructure to recognize when the data-related operations are happening.

**Comment by underfisk** [comment]
@jansiegel I did break the reference but it does not solve the issue at all.
Basically with default handsontable editing it will try to mutate first the data i send, be it a copy or not and notify me later, i need a way of intercepting that and save only at redux and prevent that override. I tried with custom editors, i've developed an external popover and that saves okay because handsontable has no control over it but the default text editor i wanna inherit it and prevent the internal editing because each time redux comes will send you the data updated.
You can test what i was saying with text editor + react, you'll notice that it stucks for some ms and only closes after the re-render and the UX becomes poor
The idea that @wojciechczerniak gave i had already developed the solution to prevent direct mutation but that was not my main point, the point is that i needed control over how handsontable updates.
For example in AgGrid i can disable that because they notify me of that change and i can say to update internally or not and in that callback, i would update on redux and prevent the editing internally.
Handsontable needs better support for immutability structures, especially with react wrapper so my solution would be allowing to intercept whether we want to save or not by having some callback when the data changes and we would return some boolean value
