### ISSUE TITLE
Virtualization on big merge cells

### ISSUE THREAD

**Issue by underfisk** [handsontable/handsontable#6910]
### Description

This is a common problem that when we have a big merge cell that for instance occupies 95% of the table size, we need to somehow chunk it because the current HoT behavior is rendering the whole merge if we have 1k on that parent merged cell it will render all of those.
What I need to know is if there's something I can do to optimize this or if HoT support any handling for this big merge cells

### Steps to reproduce

1.Create a big merge cell with for instance 100 rows on it
2. Review the DOM and see those that every row is rendered (or almost every row)

### Demo

https://jsfiddle.net/sv72w3pu/6/

### Your environment
* Handsontable version:7.4.2
* Browser Name and version: Any
* Operating System: Arch linux

**Comment by AMBudnik** [comment]
This topic is already created here https://github.com/handsontable/handsontable/issues/4421
Please comment https://github.com/handsontable/handsontable/issues/4421 if needed
