### ISSUE TITLE
Printing the table cut rows if they do not fit into the printing area.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6912]
### Description

Printing the table cut rows if they do not fir into the printing area.
Here's how Handsontable looks when we want to print it

![image003](https://user-images.githubusercontent.com/10757813/82445380-fdb47e80-9aa4-11ea-882c-f39e002a360e.jpg)

and here's Google Sheets

![Zrzut ekranu 2020-05-20 o 14 18 18](https://user-images.githubusercontent.com/10757813/82445390-01e09c00-9aa5-11ea-8600-51f1b3da9ac7.png)

Google Sheets moves the next row down on the next page if it does not fit entirely on the same page.

![Zrzut ekranu 2020-05-20 o 14 22 25](https://user-images.githubusercontent.com/10757813/82445600-68fe5080-9aa5-11ea-8bc4-7e46c9d97ccc.png)

### Demo

https://jsfiddle.net/AMBudnik/sfzru9v7/

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

Inform Zen 24849

**Comment by underfisk** [comment]
This also happens to me when the table rows size doesn't match the container size, the wtHolder is not relative 100% to its parent.
Also, I've noticed there sometime when wtHolder is resizing it goes crazy resizing it's height until i run out of memory

**Comment by AMBudnik** [comment]
> Also, I've noticed there sometime when wtHolder is resizing it goes crazy resizing it's height until i run out of memory

Can you create a separate issue for this bug, @underfisk? I haven't been reported about any similar issue as I recon.

**Comment by jumpei-yamauchi** [comment]
We have tried the following css rules and a few more variations as well but haven't been able to get it to work. 

   @media print {
        table.htCore tr    { page-break-inside:avoid!important; page-break-after:auto!important }
        table.htCore td   { page-break-inside:avoid!important; page-break-after:auto!important }
   }
   @media print {
        table.htCore tr::after,
        table.htCore td::after {
            content: ''; display: block;
            page-break-after: always!important;
            page-break-inside: avoid!important;
            page-break-before: avoid!important;       
        }
   }

**Comment by underfisk** [comment]
@jumpei-yamauchi because the issue is .wtHolder it calculates the height, there's the issue

**Comment by jumpei-yamauchi** [comment]
We have also been trying to add table header on every page but no avail so far. 

@media print {
   table.htCore > thead { display:table-header-group !important; }
}

Does this have to do with .wtHolder as well or is something different happening here.

**Comment by underfisk** [comment]
The weird part is that if you set your table to 100% and it's relative to it's parent the blank space makes no sense, it should only use the space of it's row sizes and now reserve unnecessary space.
We've migrated in from AgGrid to Handsontable and there are many things that I'm starting to regret

**Comment by AMBudnik** [comment]
Thank you all for sharing feedback on my issue.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback.
See you there!
