### ISSUE TITLE
[8.0.0-beta2-rev7] Clicking on corner doesn't select all cells and view is shifted

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6915]
### Description
We got 2 bugs here: 
1. Wrong view on the shifted table, similar to bugs introduced in iframe https://github.com/handsontable/handsontable/issues/6883 and after hiding all cells https://github.com/handsontable/handsontable/issues/6902.

2. In this revision 7 clicking on corner select only first column, which is a regression compared to the operation of rev6 and previous versions `8.0.0-beta2`. Only after the second click on corner, all cells can be selected.

![rev7-corner](https://user-images.githubusercontent.com/30186818/82556579-526dfd00-9b6a-11ea-82c0-36e4737e24f2.gif)

### Steps to reproduce

1. Open demo
2. Click LMB on corner

**Expected result:**
Selection of all cells without shifting the view on the table.

### Demo

https://codesandbox.io/embed/800-beta2-rev1-h2x03?codemirror=1 -`v8.0.0-beta2-rev7`(broken even worse)
https://codesandbox.io/embed/800-beta2-rev1-h2x03?codemirror=1 `v8.0.0-beta2-rev.6` (broken)

### Your environment
* Handsontable version: [8.0.0-beta2-rev7]
* Browser Name and version: Firefox 76, Chrome 81
* Operating System: macOs Catalina 10.15

**Comment by jansiegel** [comment]
Seems to be fixed with #6883.

**Comment by aninde** [comment]
Solved by `8.0.0.-beta2-rev12` https://j7e4y.csb.app/
![6915](https://user-images.githubusercontent.com/30186818/84031107-694b8680-a995-11ea-8642-b90528403d75.gif)
