### ISSUE TITLE
[8.0.0.-beta2-rev7] Wrong index for guideline when moves rows

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6917]
### Description
If some rows are hidden and the other we move the guideline is always in there as if rows aren't hidden.

![May-21-2020 14-47-50](https://user-images.githubusercontent.com/1555809/82560683-32423c00-9b72-11ea-8af8-e08eb18eecf7.gif)

In the 7.4.2 - https://jsfiddle.net/for879xy/
and in beta.1 - https://jsfiddle.net/xz289bLa/ - works as expected.

### Steps to reproduce

1. Move the first row, for example.

### Demo

https://jsfiddle.net/trg8efuq/

### Your environment
* Handsontable version: 8.0.0.-beta2-rev7
* Browser Name and version: Chrome 81
* Operating System:

**Comment by pnowak** [comment]
The analogical situation we have when we try show row after the first row was moved.  

Here is a demo - https://jsfiddle.net/6m3zw2xk/

### Steps to reproduce

1. Move the first row `1` after row `3`.
2. Click button `Show column`.

### Result
Nothing happens.

### Expected
Row `2` should be shown.

**Comment by AMBudnik** [comment]
### Case 2

#### Steps to reproduce

1. Try to move `A1` after `A4`

**Result**
`A1` stays at its position, but hidden rows change.

![issue](https://user-images.githubusercontent.com/10757813/82644906-5a817780-9c12-11ea-98e9-529d62208086.gif)

**Comment by aninde** [comment]
This bug is fixed with `8.0.0.-beta2-rev8`
https://jsfiddle.net/aninde/qb4g3ydr/
![6917-rev8](https://user-images.githubusercontent.com/30186818/82915045-88e3b780-9f70-11ea-9534-bd602b058eae.gif)
