### ISSUE TITLE
Double table with parent scroll

### ISSUE THREAD

**Issue by underfisk** [handsontable/handsontable#6919]
### Description

So I'm trying to disable the scrolls from Handsontable because I have a parent which will control the scroll but HoT is always setting the scroll, I've used the preventOverflow and set overflow to hidden but it still continues
The goal is having a parent that controls 2 tables inside a container, both have to contain a unique scroll

### Steps to reproduce

1.Create a parent container
2. Create 2 tables and set overflow to hidden
3.Set overflow auto to the parent container and grids to 100% relative

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 7.1.4
* Browser Name and version: Any
* Operating System: Arch linux

**Comment by AMBudnik** [comment]
Hey @underfisk 

Can you send over a demo and a reproduction video? I guess that I've did not quite get the scenario https://jsfiddle.net/AMBudnik/34kfczwm/

**Comment by underfisk** [comment]
@AMBudnik Your demo has 2 tables, it's correct but what i want is not having scroll inside the HoT table, i want the parent in your case the div with class "wrapper" to control that scroll and basically have a unique scroll (ofc both HoT would have to be at 100%)
I want to control the overflow with a single scroll not having the parent scroll + the tables

**Comment by AMBudnik** [comment]
Hadsontable is a `DIV` element, which has an HTML `TABLE` element with `TRs`, `THs`, and `TDs` inside it. If that list if too long the scroll appears automatically. This is the desired behavior, and there might be some CSS hacks to change that. But we did not test any approaches and they may not be fully supported by the structure that we create under the Handsontable DIV. 
However, if you decide to investigate that subject further I'd be more than pleased to discuss possible implementations.

**Comment by underfisk** [comment]
@AMBudnik It's desired but there must be a way to set the grid to 100% and the parent control it's scroll, i have done it by setting wtHolder overflow to hidden but sometimes it glitches.
Also another issue related to that is that my Handsontable at 100% renders white space, makes no sense when 100% means having space for all the rows and only that space but wtHolder has the double with white space on half

**Comment by AMBudnik** [comment]
>my Handsontable at 100% renders white space

Can you send over a recording with an exact demo? I think that each example of Handsontable's position and visibility has to be treated separately. 
We've just been reported on an issue with Handsontable visibility when you use padding https://github.com/handsontable/handsontable/issues/6927 so each small change may affect ho Handsontable is rendered. I personally prefer constructing Github issues like this

Case1 
- subject
- description
- video
- demo

Case2
- subject
- description
- video
- demo

It makes it easier while testing and ensures us that we've covered all the cases.

**Comment by AMBudnik** [comment]
Hi @underfisk 

> Can you send over a recording with an exact demo?

I'd like to investigate this case.

**Comment by AMBudnik** [comment]
Hi @underfisk any news here? If we do not have a demo or any test scenario we won't be able to investigate the case.

**Comment by underfisk** [comment]
@AMBudnik Here you go
https://jsfiddle.net/jaskile12/5umzdyj3/1/

**Comment by AMBudnik** [comment]
Hi @underfisk Is that a proper demo? Here's what I get.

![Zrzut ekranu 2020-06-3 o 13 44 15](https://user-images.githubusercontent.com/10757813/83632975-74bb3e00-a5a0-11ea-8379-95d46e4efce7.png)

**Comment by underfisk** [comment]
@AMBudnik That's why i get when i set 100% on HoT to be relative to the parent height/width, so yes that's the correct.
Anyway what you need to do is set a container 100% height/width and have a top and bottom which can be 50%/50% height but when i set HoT to be 100% it won't display anything at all

**Comment by AMBudnik** [comment]
@underfisk true. In this scenario, you need to add fixed dimensions for the #container https://jsfiddle.net/AMBudnik/a5wsvbkp/

**Comment by underfisk** [comment]
@AMBudnik But we're using material ui box to fit on our responsive container which means it creates breakpoints based on the %, i can't inject pixels to the root container.
Btw what's the reason for HoT not fitting on 100%?

**Comment by AMBudnik** [comment]
We'd need to add a calculation that treats the DIV size as an inheritance from the parent size. As you see here https://jsfiddle.net/AMBudnik/v2wcgz7h/ when I add another parent layer with fixed values it does not work.
I can imagine that this can be an obstacle when you create responsive layouts. That's surely something that we'd need to focus on when we'll move to the project related to responsiveness.

**Comment by underfisk** [comment]
@AMBudnik Our project is used primarily material-ui, if you try to setup a demo with it, you'll run into this issue (we have a window resize detector that updates the height/width as a workaround but this is memory heavily so we really need a better solution)

**Comment by AMBudnik** [comment]
The demo that we've been missing is this one https://jsfiddle.net/vk3s9fgb/ it allows us to show both of the tables. If anyone who's been watching this thread has any further questions please feel free to contact me on support@handsontable.com
