### ISSUE TITLE
Multi select within only one row

### ISSUE THREAD

**Issue by joseramalho** [handsontable/handsontable#692]
I'm developing a component and I need to be able to select a group of cells of just one row, is that possible? I didn't find any way to do that.

And also, we are only able to select cells that are neighbors or can we select for instance the first and third cell of one row?

**Comment by AMBudnik** [comment]
For further information in this subject please follow https://github.com/handsontable/handsontable/issues/2119 which is a 0.14.1 milestone candidate.
