### ISSUE TITLE
Issue when pasting value in a row that has formulas

### ISSUE THREAD

**Issue by jordan-lumley** [handsontable/handsontable#6920]
### Description
Hey All, 

Evaluating handsontable to see if it will fit my companies needs. I am running into an issue whenever I copy and paste a value into a cell and then the formulas show the "#VALUE!" message until I click into the cell and back out. The cell appears to need to be focused and active to fix the formula's calculations

### Steps to reproduce
1. Copy $691.22 into a VOLUME cell and youll see the read only formula cells show the red error VALUE. Click into the cell then back out and it's fine. 

### Demo
https://jsfiddle.net/h2tvyq89/

https://im3.ezgif.com/tmp/ezgif-3-82cf3b173741.gif

### Your environment
* Handsontable version: latest
* Browser Name and version: google chrome
* Operating System: linux mint

**Comment by AMBudnik** [comment]
Thank you for sharing the report @jordan-lumley 

The `$` char before the values makes them appear as a `string` (even if you declared the formatting to start with a dollar). If we remove it works well again. 
This is how the validator is working. If you'd like to work around this you could create a custom validator that supports values if they start with `$`.
