### ISSUE TITLE
Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#6926]
👋 

I'm running into an issue where I sporadically get error tracking alerts that say "Cannot read property 'tagName' of null"

I've tracked it down to this line: https://github.com/handsontable/handsontable/blob/88d78a5be5e37ad703c11914c86690d2436d3024/src/plugins/manualColumnResize/manualColumnResize.js#L256

Here is the info I get from Sentry:

![Screen Shot 2020-05-22 at 4 30 44 PM](https://user-images.githubusercontent.com/881931/82711153-2c1f8e80-9c4a-11ea-926a-fdac4760f770.jpg)

![Screen Shot 2020-05-22 at 4 31 00 PM](https://user-images.githubusercontent.com/881931/82711169-33df3300-9c4a-11ea-88c9-471681f62394.jpg)

Unfortunately that's all I get, and I'm not really sure how to reproduce it. Was hoping y'all might have some ideas 😬

**Comment by aarondfrancis** [comment]
Forgot to mention, Chrome on OSX on `8.0.0-beta.1`

**Comment by pnowak** [comment]
Hi @aarondfrancis 

It's an interesting insight. 

I wish that we could reproduce this issue manually. 
If I understand correctly it, this issue should occur after hover over `TH` elements with set `manualColumnResize`. I tried with different settings, unfortunately without success.

Nevertheless, it definitely needs further investigation.

**Comment by wojciechczerniak** [comment]
🕵️ 

1. "Cannot read property 'tagName' of null"
2. `tagName` is read from `element.parentNode`
3. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/parentNode) `parentNode` can be `null` when: "Document and DocumentFragment nodes can never have a parent, so parentNode will always return null. It also returns null if the node has just been created and is not yet attached to the tree."

![Jul-02-2020 12-30-49](https://user-images.githubusercontent.com/4718998/86348432-f5cd2a00-bc5f-11ea-896e-a9c55657e956.gif)

I was able to reproduce the issue when a header is outside of the viewport:

1. Go to: https://jsfiddle.net/y5uztqsf/
2. Select columns Q to R, should be fine
3. Select columns S to T, there's an error

For some reason `<div>T</div>` that the event gets as an `event.target` has no parentNode (and is not attached to the DOM?). Further investigation needed.

Thanks @aarondfrancis for reporting. Do you use nestedHeaders with manualColumnResize or should we narrow down the reproduction further?

**Comment by aarondfrancis** [comment]
Amazing detective work @wojciechczerniak! 

We do not use nested headers, but I do programatically change column sizes via the manualColumnResize plugin pretty often. I'll see if I can narrow it down on my side given the information you've discovered. That gives me a place to start. Thanks!

Will report back.

**Comment by aarondfrancis** [comment]
Ok, I added a plugin that was supposed to give me more insight into this, and I just got the error reported again in sentry.

Here is the plugin:

```js
import Handsontable from 'handsontable';
import PluginFactory from './plugin-factory';
import {rangeEach} from 'handsontable/commonjs/helpers/number';

let CustomManualColumnResize = PluginFactory('debugColumn', Handsontable.plugins.ManualColumnResize);

CustomManualColumnResize.prototype.enablePlugin = function () {
    const {rootWindow, rootElement} = this.hot;

    this.eventManager.addEventListener(rootElement, 'mouseover', e => this.onMouseOver(e));
}

CustomManualColumnResize.prototype.onMouseOver = function (event) {
    try {
        this._superClass.prototype.checkIfColumnHeader.call(this, event.target);
    } catch (e) {
        Raven.setExtraContext({
            event: event,
            target: event.target
        })

        throw e;
    }
}


export default CustomManualColumnResize;
```

And here's the new context from Sentry:
![image](https://user-images.githubusercontent.com/881931/87819315-9c552580-c831-11ea-9e46-c624d0684b83.png)


Doesn't seem very helpful at all to me :( 

Is there some other context I could grab?

**Comment by aninde** [comment]
Look like this issue will be fixed in the upcoming v8.2.0. If everything goes well, we plan to release it on next week.
Demo https://jsfiddle.net/aninde/rh7uwgeo/

**Comment by aarondfrancis** [comment]
🎉  Nice work yall!

**Comment by AMBudnik** [comment]
We can now officially close this issue as done.

Thank you for your continuous feedback, Aaron!
