### ISSUE TITLE
populateFromArray with 'shift_right' method results with an error console if there are fewer rows than declared in the method

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6929]
### Description

`populateFromArray` with `shift_right` method results with an error console if there are fewer rows than declared in the method.
I would expect the method to create new rows after shift the empty values right. If that won't be possible, then we should show a console warning that the dataset is not sufficient.

### Steps to reproduce

1. Go to https://jsfiddle.net/AMBudnik/21svk8gz/

**Result**
![Zrzut ekranu 2020-05-25 o 15 02 38](https://user-images.githubusercontent.com/10757813/82815133-cffe7980-9e98-11ea-8f39-22c7eb1f1f23.png)

![Zrzut ekranu 2020-05-25 o 15 02 47](https://user-images.githubusercontent.com/10757813/82815137-d3920080-9e98-11ea-9b4f-03fcf7c86d75.png)

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/ 7.4.2 (broken)
https://jsfiddle.net/AMBudnik/az7s1kbt/ 8.0.0.-beta2-rev2 (broken)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by aninde** [comment]
This issue will be fixed by v11.
Demo https://jsfiddle.net/aninde/bsvke903/

**Comment by AMBudnik** [comment]
Thank you for fixing @wszymanski and checking @aninde 
Closed as solved in v 11.
