### ISSUE TITLE
When I create handsontable control in page which is in the iframe element,why when I click cell the frame scroll bar auto scroll.

### ISSUE THREAD

**Issue by zgchizi** [handsontable/handsontable#693]
The page construction just like the:

&lt;iframe&gt;&lt;!--Iframe has H Scroll Bar--&gt;
   &lt;html&gt;&lt;!--This page is very high--&gt;
    &lt;body&gt;
          &lt;div id='handsontable&gt;'&lt;/div&gt;
    &lt;body&gt;
   &lt;/html&gt;
&lt;/iframe&gt;

When I click the cell of handsontalbe, the scrollbar of iframe auto scroll.Please tell me what should I do to fix this issue.

**Comment by AMBudnik** [comment]
Please prepare a demo, it'll be much easier to investigate this issue.

**Comment by AMBudnik** [comment]
Issue closed in lack of author's reply for more than a month.
