### ISSUE TITLE
Formulas do not calculate if they're used as new values in the beforeChange hook

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6932]
### Description

Formulas do not calculate if they're used as new values in the `beforeChange` hook.

### Steps to reproduce

1. Select `2016` and `2017`
2. Autofill those values to the 4th row

**Result**
Formulas are not calculated, even when `formulas` (as a plugin) are turned on.
![oo](https://user-images.githubusercontent.com/10757813/82874372-279ef280-9f36-11ea-88e5-2458f47db61c.gif)

### Additional info
* values do not calculate even if we reopen and close the cell

### Related issues
Issues when formulas do not calculate 
* https://github.com/handsontable/handsontable/issues/4668
* https://github.com/handsontable/handsontable/issues/4430
* https://github.com/handsontable/handsontable/issues/3908
* https://github.com/handsontable/handsontable/issues/4066

### Demo

https://jsfiddle.net/AMBudnik/rd8L1n02/ 7.4.2

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

[forum](https://forum.handsontable.com/t/gh-6932-how-to-populate-cells-with-changing-values-by-autofill/4419/18)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
The main issue is no longer replicable in pre-v9 https://jsfiddle.net/handsoncode/Lzo1a8hr/ 
This issue has to be reviewed after changes to other autofill issues reported at https://github.com/handsontable/handsontable/issues/8050 https://github.com/handsontable/handsontable/issues/8063

**Comment by AMBudnik** [comment]
The main issue with formulas being converted to strings is **fixed in v9** https://jsfiddle.net/xc5gqLn1/4/
A related issue is opened https://github.com/handsontable/handsontable/issues/8107 for blocking the values in the `beforeChange` hook.

**Comment by AMBudnik** [comment]
The issue will be fixed after the official release of v9.0.0

**Comment by AMBudnik** [comment]
Sorry for the confusion. The main issue is **NOT** fixed. After considering all the changes within the `beforeChange` the result is (at the moment of v9 freeze)

To avoid further confusion the result of the first main scenario is currently (v9 freeze)

![image](https://user-images.githubusercontent.com/10757813/120284543-a43c7d80-c2bc-11eb-91e5-e0229d257721.png)

Where the expected result should be

![image (1)](https://user-images.githubusercontent.com/10757813/120284574-ac94b880-c2bc-11eb-9aca-94a9c5b15c20.png)

**Comment by AMBudnik** [comment]
To confirm, we get the same scenario using v10 as in v9
![image](https://user-images.githubusercontent.com/10757813/135254485-2def8409-ca45-4326-a779-a00b1e3c057c.png)
Updated fiddle https://jsfiddle.net/a7pzksr1/

**Comment by AMBudnik** [comment]
Stays the same in v12.4.0 https://jsfiddle.net/handsoncode/2dx9w3nh/

**Comment by krzysztofspilka** [comment]
To be checked against https://github.com/handsontable/dev-handsontable/issues/1310

**Comment by aninde** [comment]
I confirm that this issue will be fixed by the upcoming v13.0 https://jsfiddle.net/m9q50z2s/

![image](https://github.com/handsontable/handsontable/assets/30186818/92556088-da96-45c3-afe1-8817e64731a8)

**Comment by AMBudnik** [comment]
Closed as fixed in v13.0.0.
Here's the full list of changes - [Handsontable Release Notes](https://handsontable.com/docs/javascript-data-grid/release-notes/#_13-0-0)
