### ISSUE TITLE
Select all cells

### ISSUE THREAD

**Issue by fulldecent** [handsontable/handsontable#6938]
In the example at https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers&csv-export&sorting

Clicking the top-left header cell should select all cells in the table.

Currently, clicking there does nothing.

**Comment by pnowak** [comment]
Hi @fulldecent 

This feature - clicking in the left-top corner selects the whole table - will be available on the 8.0.0 version. 

Until now this action selects only the first cell. So it is expected behaviour.

**Comment by wojciechczerniak** [comment]
This should be possible with `selectAll` method in the `afterOnCellCornerMouseDown` hook.
