### ISSUE TITLE
[1.16.0] Removing and undoing removing nestedrows when all uncollapsed parents are selected don't work

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6942]
### Description
When all uncollapsed parents rows are selected removing all of them by `contextMenu` don't work and there's an error in console.

**Expected result:** 
we want to be able to delete all selected rows and undo this operation.
The question remains whether we want nested children-rows to return after the undo.

Might be related to https://github.com/handsontable/handsontable/issues/6941
https://github.com/handsontable/handsontable/issues/6860
https://github.com/handsontable/handsontable/issues/6860

#### Steps to reproduction
1. Select with <kbd>cmd</kbd> (macOS) or <kbd>ctrl</kbd> (Windows, Linux) all parents
2. Remove rows by contextMenu

**Actual result** 
**Chrome in v7.4.2**
Only the last parent is removed. 
One error in console
_Chrome:  Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) handsontable.full.js:372_ 
![case1-chrome](https://user-images.githubusercontent.com/30186818/82996109-c5f98980-a004-11ea-8af9-26c1514a39a9.gif)

**Chrome in v1.16.0**
When we got 4 parents, 2 last of them will be removed
Two errors in console
_handsontable.full.min.js:26 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
handsontable.full.min.js:45 Uncaught TypeError: Cannot read property '__children' of null_

<img width="462" alt="Screenshot 2020-05-27 at 11 42 30" src="https://user-images.githubusercontent.com/30186818/83003843-2ab9e180-a00f-11ea-9bd8-4033f5e6cff0.png">

### Demo

https://jsfiddle.net/572Lefpz/ - v7.4.2 (broken)
https://jsfiddle.net/wojciech/j4fs38oz - v8.0.0-beta1 (broken)
https://jsfiddle.net/aninde/9q5hjobm/ - v8.0.0-beta2-rev1 (broken)
http://jsfiddle.net/aninde/tm1ghxsb/ - v1.16.0 (broken, first version with noncontinous selection)

### Your environment
* Handsontable version: 1.16.0
* Browser Name and version: Firefox, Chrome
* Operating System: macOs Mojave

**Comment by aninde** [comment]
`v8.0.0-rev8` gives same bugsy result error in Chrome after that reproduction, but we can undo it, and received empty row. In the previous version undoing that deleting doesn't return any row.
VM63 handsontable.full.js:409 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
![case1-chrome-rev8](https://user-images.githubusercontent.com/30186818/83006081-fb58a400-a011-11ea-8ebc-8d75cb0d3e3a.gif)

https://jsfiddle.net/aninde/gewvpcmk/ - v8.0.0-beta2-rev8

**Comment by AMBudnik** [comment]
It works the same in v 8.0.0 https://jsfiddle.net/AMBudnik/4nm2jkrs/

**Comment by jeremy-smith-maco** [comment]
+1
I am encountering this issue.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **NestedRows grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7510

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
