### ISSUE TITLE
Trim plugin - improve performance a lot by replacing .concat

### ISSUE THREAD

**Issue by gutinono** [handsontable/handsontable#6943]
### Description
Hi,

I'm using handsontable 8.0.0-beta.1.

I'm showing tables of more than 10 000 rows and using _Trim Rows_ plugin on these tables.
When trimming/untrimming rows it get's really slow due to one line: https://github.com/handsontable/handsontable/blob/cd76da8dce1b4e5d45c775fdc229b8a8184be992/src/plugins/trimRows/trimRows.js#L119

Array.concat is crazy slow in comparison to Array.push.

`return indexesList.concat(physicalIndex);`
Could be simply replaced by:
`indexesList.push(physicalIndex);`

It tested it and I got time reduced from 18 seconds to less than a second to trim/untrim just one row in the table.

### Steps to reproduce
1. Open a table with a lot of rows (>10 000) & make use of _Trim Rows_ plugin
1.1. It's maybe important to note that the table has a lot of small groups of trimmed rows one after the other. Each groups is between 1 & 50 rows.
2. Trim/Untrim just one row => it's super slow

### Your environment
* Handsontable version: 8.0.0-beta.1
* Browser Name and version: I'm using Electron 7.1.2, so Chromium version 78.0.3904.113
* Operating System: Ubuntu

**Comment by underfisk** [comment]
@gutinono I agree with you, .concat is much slower and also they couldn't prevent using concat and use ES6 spread operator but the main issue of the plugin is that there is no immutability, they mutate a lot of and with some frameworks as angular/react it becomes an issue

**Comment by pnowak** [comment]
Hi @gutinono 

The method you mention `getTrimmedRows` is changed in the newest version at we working right now. On the version 8.0.0. we use a global index mapper. After testing in beta2 we detect performance improvement.

You could check this yourself by using the following resources (so far they are not available at npm):
https://cdn.jsdelivr.net/gh/handsontable/handsontable@cd106d7fa7f6ba259a1cf70532876f815b2508af/dist/handsontable.full.min.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@cd106d7fa7f6ba259a1cf70532876f815b2508af/dist/handsontable.full.min.css

Every feedback will be appreciated.

**Comment by gutinono** [comment]
Hi @pnowak,

Thanks a lot for that. I'll give a try.

Do you know by when beta2 might be released in npm?

**Comment by gutinono** [comment]
By the way I just tested the CDN version you sent and indeed it's much much faster.

Thanks for the support.

**Comment by pnowak** [comment]
I'm glad that you see a performance boost.

We are currently testing and fixing found regression. 
So it hard to say when exactly we publish beta2 version.
I suppose it could be a few weeks.

**Comment by underfisk** [comment]
@pnowak Any news regarding immutability support on editors? What i mean is that using Redux when saving, the editor freezes some considerable ms because it's mutating the internal data, is there any way in the future that we can only update outside and Handsontable just notify of the changes on afterChange/beforeChange ? Just saying that with React this plugin becomes really slow

**Comment by pnowak** [comment]
@underfisk Unfortunately, there are no plans to change that structure for version 8 or 9.

**Comment by underfisk** [comment]
@pnowak Okay, it's just because there is no way of having this table performant, we ran into a lot of performance troubles in production because of the mutation that is done internally, we've tested and the default text editor with ~100rows takes like 2seconds to close when we dispatch a redux action onBefore/onAfter change and it's bad because we dont want to wait the plugin to mutate first and close after

**Comment by pnowak** [comment]
@underfisk I understand you, but we are a small company (4 developers) who are totally booked. 

Moreover, we have already planned the next versions and I cannot promise you that we will discuss your issue in the near future.

**Comment by gutinono** [comment]
Anyway thanks a lot @pnowak for the support.

I believe that the issue can be closed then.

Ps: I really enjoy using Handsontable: a big thanks to your small company then 😉
