### ISSUE TITLE
Undo should not stack data changes made by the developer

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6948]
### Description

When the developer defines data and sets some values with `setDataAtCell` and `setDataAtRowProp` those values can be reverted with undo.
I think that the user should only have the ability to revert their own changes.

### Steps to reproduce

1. Select any cell
2. Use <kbd>CMD/CTRL</kbd> + <kbd>Z</kbd> to undo

**Result**
The `setDataAtRowProp` action is undone.
![demo](https://user-images.githubusercontent.com/10757813/83124855-0b868700-a0d7-11ea-9d7e-94694759825a.gif)

### Demo

https://jsfiddle.net/AMBudnik/z2x1ru08/ 7.4.2
https://jsfiddle.net/AMBudnik/zjmo097f/ 8.0.0-beta2-rev9

### Additional info
* `loadData` is not stacked in undo 👍 

### Reated issues (undo activity)
* https://github.com/handsontable/handsontable/issues/6829

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/c0f8r7a6/

**Comment by AMBudnik** [comment]
We have a **Case 2** here that I would like to test after the fix.

Demo https://jsfiddle.net/handsoncode/y7pthg5r/1/ (React, Handsontable v8.2.0)
Tested using Chrome 87, Windows 10.

**Steps**
1. Change all the cells in the first table
2. Try to undo those changes.

You will see that data in table 2 is changed. This is a necessary step to replicate the issue. If we do not change the data in the 2nd table the issue is not replicable and undo stuck does not get corrupted.

**Comment by wojciechczerniak** [comment]
I've described a proposal for the solution here https://github.com/handsontable/handsontable/pull/7500#issuecomment-797403918

**Comment by aninde** [comment]
This issue will be fixed by the upcoming v8.4.0 https://jsfiddle.net/473p9akh/.
