### ISSUE TITLE
[8.0.0-beta2-rev1] When editor is opened cell content is not selected

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6954]
### Description

We've made a change that makes us compatible with other tools like Excel and Google Sheets. But the change wasn't planned and it might be causing too much (unpredicted) damage at this point, so we need to revert the old behavior. 

### Steps to reproduce

1. Use db-click on `A1`

**Result - 8.0.0.-beta2-rev1**
Content is not selected
![rev10](https://user-images.githubusercontent.com/10757813/83146221-451aba80-a0f6-11ea-80af-4eba6b6434fb.gif)

**Previous versions**
![742](https://user-images.githubusercontent.com/10757813/83146229-4815ab00-a0f6-11ea-947c-814d37dda6b8.gif)

### Demo

https://jsfiddle.net/AMBudnik/u8rgf1md/ 8.0.0-beta1
https://jsfiddle.net/AMBudnik/mrajnzkf/1/ 8.0.0-beta2-rev1

### Your environment
* Handsontable version: 8.0.0.-beta2-rev1
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
Handsontable v[7.4.2](https://jsfiddle.net/AMBudnik/pxtsg7ka/) to [8.0.0-beta2-rev10](https://jsfiddle.net/AMBudnik/rLbw84pd/), on Firefox 76.0.1 does not select content on cb-click.
I've tried various versions (`2.0.0` included) and it seems to work that way for a long time.

**Comment by wojciechczerniak** [comment]
@AMBudnik So this isn't a v8 regresson? Shouldn't we change subject and remove the assignee?

**Comment by jansiegel** [comment]
@AMBudnik I can't find a version in which the editor contents were selected after double clicking. To me, it looks like this is not a regression, nor a bug.

**Comment by AMBudnik** [comment]
Hey @jansiegel 

Handsontable v7.4.2, Firefox 76.0.1 **does not select content** when you db-click. I've tested it on my Macbook Air with Catalina. It's replicable in the docs https://handsontable.com/docs/7.4.2/demo-scrolling.html
However, today I've updated to 77.0 and it seems to randomly work both ways 🤔 
ps. be sure to db-click cause many of us instinctively click 3 times ;-)

All the other browsers using all Handsontable versions (till 8.0.0-beta2-rev1) **do select** content on db-click.

When it comes to the regression, and the bug tags we had a long conversation about this subject. That's why you can see **bug** and **improvement** on the same topic 😄 I personally found it as an improvement.

**Comment by jansiegel** [comment]
@AMBudnik I just tried `7.4.2` on Chrome, Firefox and Safari, and neither of those browsers select the contents on double-click. All of them do when you triple-click, but that didn't change either.

**Comment by wojciechczerniak** [comment]
Can't replicate it either. Chrome 83, Firefox 76.0.1, Safari 13.1. macOS Catalina. None of the browsers will select content on double click. 

Should we use mouse or touch pad?

**Comment by jansiegel** [comment]
> Should we use mouse or touch pad?

I tried both, it always worked the same between browsers and pre-8.0/8.0 versions.

**Comment by AMBudnik** [comment]
> Should we use mouse or touch pad?

I'm using a touchpad. Double-tap.

But wait, let's skip the Firefox difference, as apparently we're not getting the same result on Chrome as well. We discussed the same with @wszymanski @aninde on the private chat and then the content was getting selected and now it doesn't? I got lost here a bit.


Below is my Chrome v80.0.3987.149 incognito touchpad reproduction from today (the same as above)

![rev1](https://user-images.githubusercontent.com/10757813/83622019-c0192080-a58f-11ea-95aa-38326c28e292.gif)
`8.0.0-beta2-rev1` (and all the way to [rev10](https://jsfiddle.net/AMBudnik/mrajnzkf/3/))

![beta1](https://user-images.githubusercontent.com/10757813/83622028-c4453e00-a58f-11ea-923e-2a480719f4b3.gif)
`8.0.0-beta1`

I remember that @aninde was also able to replicate the same as we had a discussion on using BrowserStack to check how it works in Firefox 68. @aninde can you check that, please?

**Comment by AMBudnik** [comment]
I've checked it with @aninde, and @budnix, and tried it on my Windows 10 and it seems to work that way only on my Macbook Air. I've compared touchpad settings with @aninde - they're the same so it has to be a minor settings-related issue.

I do not think that we should focus on this issue @wojciechczerniak 
We can even close it, and I'll reopen it if I find the difference that makes my device select the content.

**Comment by aninde** [comment]
I confirm that I was unable to reproduce this error on any browser in any version. I even switched the trackpad settings to the same as @AMBudnik, but that didn't help in the reproduction either. I think the problem is due to computer settings.
