### ISSUE TITLE
[svg] Missing frozen line if the overlay ends with a merged cell

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6957]
### Description

Found reported today by @krzysztofspilka on Slack (https://handsoncode.slack.com/archives/D4R71E8P5/p1590673640044100?thread_ts=1590673378.041300&cid=D4R71E8P5). A regular gridline is rendered instead of the frozen line at the edge of an overlay, if the last cell before the overlay edge is a merged cell.

Similar but not the same as #6762

### Steps to reproduce

1. Create a table than contains `fixedColumnsLeft: 2, fixedRowsTop: 2` and make a merged cell in the range 0, 0 -> 0, 1

### Your environment
* Handsontable version: PR #6157 (SVG borders branch, commit 53f333e72b90f85fe12ada6f3ad5329a30acbf5a) 
* Browser Name and version: any
* Operating System: any

**Comment by krzysztofspilka** [comment]
And here's the screenshot.

![](https://user-images.githubusercontent.com/8048526/83157606-1b689000-a104-11ea-9cf0-85f45b348d6c.png)

**Comment by warpech** [comment]
Closing as the SVG PR was closed. Explanation in https://github.com/handsontable/handsontable/pull/6157#issuecomment-1012200057
