### ISSUE TITLE
[8.0.0.-beta2-rev7] When we undo removing of columns/rows selection covers too many columns/rows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6963]
### Description

When we undo removing of columns selection covers too many columns. 

### Steps to reproduce

1. Remove columns `A, B, C` with context menu
2. Undo

**Result rev7 (broken)**
![broken](https://user-images.githubusercontent.com/10757813/83259481-6643df80-a1b8-11ea-8691-7bf92feb57a3.gif)

**Result rev6 (works well)**
![ok](https://user-images.githubusercontent.com/10757813/83259492-6e9c1a80-a1b8-11ea-9a6b-f6ec313a32ee.gif)

### Demo

https://jsfiddle.net/AMBudnik/wuqysphr/ 8.0.0.-beta2-rev6 (works well)
https://jsfiddle.net/AMBudnik/u34fc1ns/ 8.0.0-beta2-rev7 (**broken**)
https://jsfiddle.net/AMBudnik/ybtserdL/ 8.0.0-beta2-rev10 (still broken)

### Your environment
* Handsontable version: 8.0.0.-beta2-rev7
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
I've changed the title as the following rule also applies to rows.

**Steps**
1. Go to https://jsfiddle.net/AMBudnik/3pzuynre/
2. Select rows 2-5
3. Remove them by context menu
4. Use <kbd>CMD/CTRL</kbd> + <kbd>Z</kbd> to undo

**!important**
If Undo is many by context menu it works well.

**Comment by AMBudnik** [comment]
We had problems with the selection of non-adjacent rows in rev1, in rev7 it got worse. I have reported it in this topic https://github.com/handsontable/handsontable/issues/6964

**Comment by budnix** [comment]
Connected with #6964

**Comment by aninde** [comment]
This issue is solved by `8.0.0-beta2-rev15` https://jsfiddle.net/aninde/cnew6ftb/

![6963-rev15](https://user-images.githubusercontent.com/30186818/84915588-44ee5900-b0bd-11ea-80bb-aa0b58879b47.gif)
