### ISSUE TITLE
After moving a row from the bottom to the top, the row indices change if the first row is hidden.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6965]
### Description
If we hide the first row, index signature starts from `2`. But if we move the second visual row to the top, the index changes to `1`. At the same time indicators for `hiddenRows` move to the bottom.
![May-29-2020 15-40-32](https://user-images.githubusercontent.com/1555809/83266811-a197db80-a1c3-11ea-928b-c53ec6bb27a4.gif)

### Steps to reproduce

1. Move the second row to the top (in our case `3`).
2. Move the second row to the top (currently`2`).

### Demo

https://jsfiddle.net/tjyxomp8/

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
**Fixed** in 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/2gkvswnb/

**Comment by AMBudnik** [comment]
Issue fixed in v 8.0.0. Updated demo https://jsfiddle.net/veg2mktr/
