### ISSUE TITLE
How to use handsontable in typescript?

### ISSUE THREAD

**Issue by byMoya** [handsontable/handsontable#6968]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @byMoya 

Here's a definition file that will help you to build the application https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts

Here's the topic https://forum.handsontable.com/t/is-it-possible-to-initiate-table-dynamically-from-typescript-in-angular-6/2576 that will guide you on how to initiate a project.

And here https://stackblitz.com/edit/typescript-handsontable-jxufxn?file=index.ts is a Stackblitz example that you can use to experiment with the library.

ps. If you have some questions on the use of Handsontable I highly recommend using emails. We're available on support@handsontable.com - we generally use Github to report issues and feature ideas.
