### ISSUE TITLE
It’s possible to select hidden column/row.

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6974]
### Description

It’s possible to select hidden column/row

### Steps to reproduce

1. Open demo https://jsfiddle.net/aninde/y0dhqu5g/
2. Select a hidden column or row by click on the button.
3. Click one again on the same button.

![select-hidden-7 4 2](https://user-images.githubusercontent.com/30186818/83659442-d6d96a80-a5c3-11ea-9fc7-fcfdb4f1d65d.gif)

### Demo

https://jsfiddle.net/aninde/y0dhqu5g/

### Your environment
* Handsontable version: any
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
Solved by `8.0.0-beta2-rev-1`. Still fixed on rev10 https://jsfiddle.net/aninde/30uabvot/
![Kapture 2020-06-03 at 18 02 26](https://user-images.githubusercontent.com/30186818/83659894-6d0d9080-a5c4-11ea-8b46-6f6a6ba487b2.gif)

**Comment by AMBudnik** [comment]
After introducing changes in https://github.com/handsontable/handsontable/pull/7027 we get

- unselected cells 
- selected headers (grey background)

Updated demo https://jsfiddle.net/81czfw0b/. Issue solved.
