### ISSUE TITLE
Cannot selectAll when the first row is hidden

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6975]
### Description
Cannot `selectAll` when the first row is hidden

### Steps to reproduce

1. Open demo https://jsfiddle.net/aninde/sgha42qy/
2. Click on any cell.
3. Select all cells by <kbd>cmd</kbd>+<kbd>A</kbd>

**Result:** Error in console, nothing is selected.

### Demo

https://jsfiddle.net/aninde/sgha42qy/

### Your environment
* Handsontable version: any
* Browser Name and version: any 
* Operating System: any

**Comment by aninde** [comment]
Solved by `8.0.0-beta2-rev1.` Still fixed in `rev10` https://jsfiddle.net/aninde/vgk83mcy/
<img width="351" alt="Screenshot 2020-06-03 at 18 14 46" src="https://user-images.githubusercontent.com/30186818/83661316-35074d00-a5c6-11ea-95fd-7604c6d9b441.png">

**Comment by AMBudnik** [comment]
Works as expected in the stable v8.0.0. Updated demo https://jsfiddle.net/g2uyzox4/
