### ISSUE TITLE
Incorrect column header highlight when merged cells are unmerged and hiddenColumns are used

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6978]
### Description

_The issue moved from case 3 from_ https://github.com/handsontable/handsontable/issues/6872

Incorrect column header highlight when merged cells are unmerged.

### Steps to reproduce

1. Select both columns by clicking on their headers suing RMB
2. Use `Merge cells` from the context menu
3. Select both columns by clicking on their headers using RMB
4. Use 'Shown columns' from the context menu

**Result**
![merge-show-undo](https://user-images.githubusercontent.com/10757813/83737415-4185b700-a653-11ea-97f1-02c1ce55e820.gif)

I would expect to get the same result as we get (cause we do not support undo-redo for hiding/showing) but with header `A` highlighted (not all of them).

### Demo

https://jsfiddle.net/AMBudnik/2t5sdgoz/ 8.0.0-beta2-rev10 (broken)
https://jsfiddle.net/AMBudnik/bp0xrv1y/ 7.4.2 (broken)

### Your environment
* Handsontable version: 7.4.2
_It doesn't seem to work differently in any version_
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by wojciechczerniak** [comment]
@AMBudnik This works for me differently than shown on your GIF:

![Jul-03-2020 13-39-30](https://user-images.githubusercontent.com/4718998/86465846-bcb1ba00-bd32-11ea-9a50-4ededbbf0ee8.gif)

IMO headers are highlighted correctly. But WDYT? CC @aninde

**Comment by AMBudnik** [comment]
@wojciechczerniak 
Steps where not complete based on the video issue reproduction. I've updated it.
In your repro you're selecting those cells by cell dragging and I use columns selection.

**Comment by wojciechczerniak** [comment]
Nope. Still works.

But I see now the difference. You're using Undo. This issue is not about unmerging, but about undo/redo ignoring selection. We have a few similar issues already but we can keep this one as an additional use case.

**Comment by aninde** [comment]
@AMBudnik @wojciechczerniak you've presented two different cases.
1. Selecting cells + colHeaders before merging.
2. Selecting only cells before merging

The difference in these reproductions causes a different highlight effect on the cells.
this can be seen in the first version  `1.14.0` https://jsfiddle.net/aninde/e29cf0sm/ of Handsontable. In the later versions by losing selection after merging, this difference is blurred.

**Selecting cells + colHeaders** 
![selection-on-collumns-1 14 0](https://user-images.githubusercontent.com/30186818/86584499-448f0280-bf85-11ea-96b5-9b76d52ef049.gif)

**Selecting only cells**
![selectiing-cell-1 14 0](https://user-images.githubusercontent.com/30186818/86584508-48bb2000-bf85-11ea-913b-d8f5d4eccf63.gif)

With `8.0.0-beta1`. https://jsfiddle.net/aninde/hbaq7gd2/ Works like in the `7.4.2`

In my opinion, with the description of the report, as it is, no bug was reported here. 
Possible loss of selection after cells marked from headers height can be a bug, but I think that we reported this before. 

We need information about the expected effect after undo and change of title if we agree to leave this issue open.

**Comment by AMBudnik** [comment]
Till that point
![ok](https://user-images.githubusercontent.com/10757813/86586302-f7f8f680-bf87-11ea-9e43-e77dcdcbcdf7.png)

it works how I would expect it to work.

The issue is what I see on the next step (doing undo for merging).

Bad result (any - 8.0.0-beta2-rev10)
![bad](https://user-images.githubusercontent.com/10757813/86586669-8e2d1c80-bf88-11ea-83b2-54f726382ea2.png)

(I guess expected result) in 8.0.0-beta2-rev18 https://jsfiddle.net/z4Lno5sc/
![working](https://user-images.githubusercontent.com/10757813/86586695-9a18de80-bf88-11ea-93f4-99e267cf8c1b.png)

@wojciechczerniak @aninde I suggest adding this issue as solved to release 8.0.0 and 8.0.0-beta2 (+ 8.0.0 epic mention).

**Comment by aninde** [comment]
From  revision 18 8.0.0-beta2 we have a huge difference, after merging we do not lose the selection from headers. This can be caused by https://github.com/handsontable/handsontable/pull/7027

CC: @scarletfog maybe this can be useful for RN.

**Comment by wojciechczerniak** [comment]
> (I guess expected result) in 8.0.0-beta2-rev18 https://jsfiddle.net/z4Lno5sc/
> ![working](https://user-images.githubusercontent.com/10757813/86586695-9a18de80-bf88-11ea-93f4-99e267cf8c1b.png)

Yup, this is what I've seen.

> @wojciechczerniak @aninde I suggest adding this issue as solved to release 8.0.0 and 8.0.0-beta2 (+ 8.0.0 epic mention).

 Up to you. You're the bug reporter. Tell us if this solves your issue 🙂

**Comment by AMBudnik** [comment]
@wojciechczerniak yes, it solves the issue. The selection in the latest version follows our rules of header selection.

**Comment by AMBudnik** [comment]
v8.0.0 dem0 https://jsfiddle.net/cLb6ut1e/. Issue is solved.
