### ISSUE TITLE
[8.0.0.-beta2-rev11] Cannot get on the merged cell by navigating with the keyboard.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6981]
### Description
When we navigation by keyboard and try to open/close cell editor by <kbd>Enter</kbd> we can't move to the merged cell.
![Jun-04-2020 15-33-44](https://user-images.githubusercontent.com/1555809/83764454-401bb500-a67a-11ea-942d-4f1a84e58f27.gif)

In version 7.4.2 and beta.1 works as expected.
![Jun-04-2020 15-35-44](https://user-images.githubusercontent.com/1555809/83764701-8bce5e80-a67a-11ea-9e03-565a97e863e3.gif)

7.4.2 - https://jsfiddle.net/04qa8nst/
8.0.0-beta.1 - https://jsfiddle.net/6qrwavdx/

### Steps to reproduce

1. Click to a cell from the first column and navigate by using `Enter` key.

### Demo

https://jsfiddle.net/e83pf2gu/

### Related issue
https://github.com/handsontable/handsontable/issues/6973

### Your environment
* Handsontable version: 8.0.0.-beta2-rev11
* Browser Name and version: Chrome 83
* Operating System:

**Comment by aninde** [comment]
The ability to use <kbd>Enter</kbd> to move on the table is still broken in `v8.0.0-beta2-rev14` comparing to `7.4.2` While navigating with arrows or tabs works the same as in `7.4.2.` will not works perfectly.

**rev14**
![enter](https://user-images.githubusercontent.com/30186818/84662249-dcb44180-af1b-11ea-8ca5-bd915d7ea895.gif)

**7.4.2**
![enter-7 4 2](https://user-images.githubusercontent.com/30186818/84662260-df169b80-af1b-11ea-9b2d-07de4d305a27.gif)

Navigation with <kbd>RIGHT</kbd> arrow or TAB is still the same. Reported here https://github.com/handsontable/handsontable/issues/6973
![right arrow](https://user-images.githubusercontent.com/30186818/84662439-1ab16580-af1c-11ea-9f99-7f5871abb52a.gif)
![right arro-7 4 2](https://user-images.githubusercontent.com/30186818/84662450-1c7b2900-af1c-11ea-9b94-7c5e9648b176.gif)

**Comment by aninde** [comment]
This issue is solved by `8.0.0-beta2rev15` https://jsfiddle.net/aninde/7hk8py4c/1/
It's possible to navigate by <kbd>ENTER</kbd>. Navigation with <kbd>ARROWS</kbd> and <kbd>TAB</kbd> works as in stable 7.4.2.
![fix156981](https://user-images.githubusercontent.com/30186818/84877740-2bcbb500-b089-11ea-84b9-a420689d5e0c.gif)
