### ISSUE TITLE
Selecting secondary mergedCell causes improper highlight

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6984]
### Description

When we select not the first merged cell, this cell will be incorrectly highlighted.

If we select A2 (`hot.selectCell(1,0)`) selection works proper, but selecting A3 or A4 when we merged A2-A3-A4 incorrect UI class `current area highlight` will be added.

Related to https://github.com/handsontable/handsontable/issues/4859

<img width="309" alt="Screenshot 2020-06-04 at 18 02 34" src="https://user-images.githubusercontent.com/30186818/83780551-9ba36e00-a68d-11ea-81a6-a93657a382a5.png">

### Steps to reproduce

1. Open demo https://jsfiddle.net/aninde/0gjhveab/

This bug can be also reproduced by choosing cell E2 and clicking the right arrow on keyboard.
Bug is replicable only when we moved focus from left to right. Not otherwise.
![4 0 0saf](https://user-images.githubusercontent.com/30186818/83780435-71ea4700-a68d-11ea-8068-ff3d5cc0ab1a.gif)

### Demo

https://jsfiddle.net/aninde/0gjhveab/

### Your environment
* Handsontable version: 1.14.0 (0.34)
* Browser Name and version: Chrome 83, FF 77, Safari 13.1.1
* Operating System: macOS Catalina 10.15.5

**Comment by aninde** [comment]
Another example

https://jsfiddle.net/aninde/73j85phn/ - `v.7.0.0`
<img width="322" alt="Screenshot 2020-06-08 at 15 39 58" src="https://user-images.githubusercontent.com/30186818/84038246-feec1380-a99f-11ea-95c4-9f22d226a88c.png">

https://jsfiddle.net/aninde/60rbmt5a/ - `v.6.2.2` partially fixed, but stil not perfect
<img width="322" alt="Screenshot 2020-06-08 at 15 40 18" src="https://user-images.githubusercontent.com/30186818/84038261-06132180-a9a0-11ea-8a66-f0b71e90d0c4.png">

**Comment by AMBudnik** [comment]
This main issue is no longer replicable in v8.0.0 https://jsfiddle.net/AMBudnik/43s19rbt/

![merge](https://user-images.githubusercontent.com/10757813/91962241-8aa9dd80-ed0c-11ea-8546-62ceb4d1556f.gif)

**Comment by wojciechczerniak** [comment]
Does it work correctly? Shouldn't it be  E1 -> A2 -> B2 -> ... -> E2 -> A2 -> B3 (next row) ? Looks like we're in the loop now

**Comment by AMBudnik** [comment]
> Looks like we're in the loop now

True. We should have a spec for it. Here's a related issue https://github.com/handsontable/handsontable/issues/4665

**Comment by swistach** [comment]
I close this issue due to:
- requested issue is the same problem as #4859,
- "selection loop" issue is requested in #4665.
