### ISSUE TITLE
Row heights are not kept on nestedRows if we collapse them

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6985]
### Description

Row heights are not kept on `nestedRows` if we collapse them. It happens whenever we make the 2nd row bigger (by dragging) or smaller (by dbclick, default).

### Steps to reproduce

1. Go to the same demo https://jsfiddle.net/AMBudnik/dwv04kpc/
2. Use db-click to get default height of the 2nd cell
3. Collapse the first parent

**Result**
![aaa](https://user-images.githubusercontent.com/10757813/83841962-32aa0d80-a702-11ea-9bb8-e4b212c62172.gif)

### Demo

https://jsfiddle.net/AMBudnik/dwv04kpc/ 7.4.2 (broken)
https://jsfiddle.net/AMBudnik/ck8pjbrd/1/ 8.0.0-beta2-rev11 (broken)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/rfbvj1ka/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **NestedRows grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7510

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
