### ISSUE TITLE
Trimming does not get values back when merged cells are included in the dataset

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6989]
### Description

Trimming does not get values back when merged cells are included in the dataset.

~~You may spot the rowHeaders elements missing, this issue is already reported here https://github.com/handsontable/handsontable/issues/6276~~ fixed for v 8.2.0

### Case 1
1. Merge cells from the `A` column
2. Click the button below table (it call `untrimAll()` method)

**Result**
`A10` value is gone.
![merge-header](https://user-images.githubusercontent.com/10757813/83860944-42d0e580-a720-11ea-966e-29554debc158.gif)

### Case 2 
1. Merge rows `2:4`
2. Click the button below table (it call `untrimAll()` method)

**Result**
We get the row back but it's empty.
![row-merge](https://user-images.githubusercontent.com/10757813/83861210-9a6f5100-a720-11ea-8288-2f3ae8112c83.gif)

### Demo

https://jsfiddle.net/AMBudnik/Lwk054ph/ 7.4.2 (broken)
https://jsfiddle.net/AMBudnik/7td4oucf/ 8.0.0-beta2prev11 (broken)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80 
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
#### Updates to v 8.0.0

1. * [x] Case 1 - the issue is still replicable https://jsfiddle.net/d5f91noa/
1. * [x] Case 2 - the issue is still replicable https://jsfiddle.net/2641jtsm/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **MergeCells grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by bj00rn** [comment]
Is this issue actively being worked on?

I really think you should update the docs stating that the combined usage of trimRows and mergeCells is unsupported. As it stands, using both plugins results in unpredictable behaviour.

**Comment by AMBudnik** [comment]
Just a note: Replied at https://github.com/handsontable/handsontable/issues/7509#issuecomment-1960999762
