### ISSUE TITLE
When we undo column removal selection does not redraw to a whole row

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6993]
### Description

When we undo column removal selection does not redraw to a whole row.

### Steps to reproduce

1. Remove column `B`
2. Select first row
3. Click <kbd>CMD/CTRL</kbd> + <kbd>Z</kbd> to undo

**Result**
![selection](https://user-images.githubusercontent.com/10757813/83878002-bdf3c500-a73b-11ea-9772-2c4221353dea.gif)

### Demo

https://jsfiddle.net/AMBudnik/97e53qob/ 7.4.2 (broken)
https://jsfiddle.net/AMBudnik/hzy9rf3k/ 8.0.0-beta2-rev11 (broken)

### Related issues
* https://github.com/handsontable/handsontable/issues/6944
* https://github.com/handsontable/handsontable/issues/6895

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
It also works this way if we have selected all the 3 columns before column removal.

**Steps**
1. Go to https://jsfiddle.net/AMBudnik/qag5nukm/
2. Select first row
3. Click the button below the table
4. Undo

**Result**
![btn](https://user-images.githubusercontent.com/10757813/83878799-f647d300-a73c-11ea-973f-1b08818bb599.gif)

**Comment by aninde** [comment]
Maybe can be related with https://github.com/handsontable/handsontable/issues/6670

**Comment by aninde** [comment]
With the same reproduction in `Excel` or `Google Spreadsheet` selection is on the restored column. I would wonder if this is a bug or not if we have no requirements. Maybe the bug is that we don't have Excel o GS behavior? Maybe the selection should be on the restored element? @AMBudnik @wojciechczerniak WDYT?


![excel-undo](https://user-images.githubusercontent.com/30186818/84022133-10282680-a986-11ea-9728-02ad648461f5.gif)
![gs-undo](https://user-images.githubusercontent.com/30186818/84022137-11f1ea00-a986-11ea-8c31-ac5511e2b383.gif)
![gs-undo2](https://user-images.githubusercontent.com/30186818/84022142-13231700-a986-11ea-8018-29ea1eac68c9.gif)

**Comment by AMBudnik** [comment]
@aninde true. If we remove a column selection on undo should be moved to that column. As it happens here https://jsfiddle.net/AMBudnik/cqarg1od/ (don't mind the missing header, it's reported).

**Comment by wojciechczerniak** [comment]
> @aninde true. If we remove a column selection on undo should be moved to that column. As it happens here https://jsfiddle.net/AMBudnik/cqarg1od/ (don't mind the missing header, it's reported).

Please select the cell before `undo`. It may look like it works like that but it isn't.

@AMBudnik @aninde There is no spec for this, but I agree, looks better if the selection is restored. Although, it gets more complicated when we undo/alter columns or rows with API. We don't have a selection to restore. We need a project from the UX perspective for both cases. Something

**Comment by wojciechczerniak** [comment]
@aninde @AMBudnik Looks like it's working ok in rev18: https://jsfiddle.net/t1dLmas8/1/ ?

**Comment by AMBudnik** [comment]
@wojciechczerniak 

it works the same using revision 18th on my Chrome 83 / macOC Catalina

![broken](https://user-images.githubusercontent.com/10757813/86338075-2efe9d80-bc52-11ea-978d-2fc609de8579.gif)

**Comment by aninde** [comment]
It works also on Safari 13.1, Firefox 77 and Edge 80 / Mac OS.

> Please select the cell before `undo`. It may look like it works like that but it isn't.
> 
 Selecting cell before undo does not affect the selection change in Excel.

**Comment by AMBudnik** [comment]
Remains the same in `8.0.0-beta2-rev21` https://jsfiddle.net/nutybawv/
Tested on Chrome 83 / macOS Catalina 10.15.3

**Comment by aninde** [comment]
Remains the same with `v8.0.0` https://jsfiddle.net/aninde/e3d5vx2b/.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
