### ISSUE TITLE
How to get Header Column name/value or Header Name in Nested Header - **URGENT**

### ISSUE THREAD

**Issue by pablomagalhaes** [handsontable/handsontable#6994]
### Description
I would like to get header name/value 

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 7.4.2 - Reactjs
* Browser Name and version: Chrome
* Operating System: Mac OS

**Comment by pnowak** [comment]
Hi @pablomagalhaes 

You could use `getColHeader` - https://handsontable.com/docs/7.4.2/Core.html#getColHeader

Here is a simple example - https://jsfiddle.net/eruxo085/ 
If you open a console you could see an array of column headers.

**Comment by pablomagalhaes** [comment]
Hi @pnowak - But this don't works in nestedHeaders.

**Comment by pnowak** [comment]
You have to use a method from a `nestedHeaders` plugin - `getHeaderSettings`.

First, you need to have access to the plugin itself by `getPlugin` - `const nestedHeadersPlugin = hot.getPlugin('nestedHeaders');`. 
And then you could use `getHeaderSettings` - nestedHeadersPlugin.getHeaderSettings(headerLevel, columnIndex)`. Where `headerLevel` is a header level (0 = most distant to the table) and `columnIndex` is a visual column index. 

So, for example, when you call `getHeaderSettings(0, 0)` you get an object with these properties: 
```collapsible: false
colspan: 2
isBlank: false
isCollapsed: false
isHidden: false
label: "7-LPA-D"
origColspan: 2```.

**Comment by pnowak** [comment]
Did this work for you @pablomagalhaes?

**Comment by pablomagalhaes** [comment]
yes @pnowak . Thank you so much

**Comment by pnowak** [comment]
Thanks @pablomagalhaes 

So I close this issue.

**Comment by pablomagalhaes** [comment]
@AMBudnik - can you show me a demo to:  nestedHeadersPlugin.getHeaderSettings(0, 0)
