### ISSUE TITLE
 [8.0.0.-beta2-rev12] The error occurs after using autoFill when we perform 3 specific steps

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6995]
### Description
When auto-filling in 3 specific steps cells we get an error `TypeError: Cannot read property 'row' of undefined`.

To reproduce this issue we have to first auto-fill a few cells from row or column. Next, all of them auto-fill a few rows and columns at a clip.
A then, finally, auto-fill in the opposite direction. 
![Jun-05-2020 15-36-47](https://user-images.githubusercontent.com/1555809/83882438-686ee680-a742-11ea-89e1-40a13a0f9944.gif)

### Possible source of this bug:
https://github.com/handsontable/handsontable/pull/6856

### Demo

https://jsfiddle.net/c26o4htz/4/

### Your environment
* Handsontable version: 8.0.0-beta.2-rev12
* Browser Name and version:
* Operating System:

**Comment by aninde** [comment]
Solved by `8.0.0-beta2-rev15` https://jsfiddle.net/aninde/3y7mj6sh/
Tested with headers and without. 

![6995-rev15](https://user-images.githubusercontent.com/30186818/84916205-0f963b00-b0be-11ea-83f4-77cc3a7e23ca.gif)
