### ISSUE TITLE
viewportColumnCalculatorOverride set wrong property of "calc"

### ISSUE THREAD

**Issue by Guobacai** [handsontable/handsontable#6996]
### Description
I am not sure if this is an issue. It is worth to check though.
In the method "viewportColumnCalculatorOverride", if the option "viewportColumnRenderingOffset" is 'auto', it sets the "calc.startRow" instead of "calc.startColumn". Is that correct?

### Demo
https://jsfiddle.net/guobacai/4abn7dpu/11/
The demo seems good to me. But, I am not sure if that is expected result.

### Your environment
* Handsontable version: Handsontable 8 beta.2 revision 10.
* Browser Name and version: Chrome 81
* Operating System: Mac

**Comment by pnowak** [comment]
Yes, this is a typo.
Thank you for reporting.

Unfortunately, we came to the conclusion that fixing the typo in one place could break a logic cycle in another part of the code. So it needs further investigation.

As we have already one issue open about this topic - https://github.com/handsontable/handsontable/issues/6115 - I'll close yours as a duplicate.

**Comment by Guobacai** [comment]
Thank you @pnowak
