### ISSUE TITLE
[8.0.0-beta2-rev1] We cannot add a column on the left when there's no data (data is filtered out)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6998]
### Description

We cannot add a column on the left when there's no data (data is filtered out)

### Steps to reproduce

1. Filter out all the rows
2. Open dropdown menu

**Result**
You cannot add a column on the left, but can add one on the right.
![Zrzut ekranu 2020-06-8 o 15 00 18](https://user-images.githubusercontent.com/10757813/84033209-cbf25180-a998-11ea-9317-0e7ca3a843b4.png)

**Expected result**
![Zrzut ekranu 2020-06-8 o 15 01 15](https://user-images.githubusercontent.com/10757813/84033291-ea584d00-a998-11ea-8a59-f08fb2f3bce4.png)

### Demo

https://jsfiddle.net/AMBudnik/yo7psbwz/ 7.4.2 (works well)
https://jsfiddle.net/AMBudnik/mr7ej1zp/ 8.0.0-beta1 (wroks well)
https://jsfiddle.net/AMBudnik/dr32xbLs/ 8.0.0-beta2-rev1 (**broken**)
https://jsfiddle.net/AMBudnik/o26w0dhf/ 8.0.0-beta2-rev12 (still broken)

### Additional info
* works well when data is hidden with `hiddenRows` https://jsfiddle.net/AMBudnik/nr4kqt8o/

### Your environment
* Handsontable version: 8.0.0-beta2-rev1
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by aninde** [comment]
This issue is fixed on [merge-candidate PR#7027](https://github.com/handsontable/handsontable/pull/7027) for `8.0.0-beta2`
https://jsfiddle.net/nmh35vLc/ `vPR#7027`
![fixed-PR#7027](https://user-images.githubusercontent.com/30186818/85279417-abd98c80-b486-11ea-960c-3aad2893ce63.gif)

**Comment by AMBudnik** [comment]
Issue solved in v 8.0.0-beta2-rev18 https://jsfiddle.net/b7wveznq/

![solved](https://user-images.githubusercontent.com/10757813/86127101-ad86fe00-badf-11ea-9026-acb029eef696.gif)

You may see that the filters are attached to the wrong column, however, that's a separate issue (not a regression) reported here https://github.com/handsontable/handsontable/issues/6830
