### ISSUE TITLE
text wrap in cell will cause misalign

### ISSUE THREAD

**Issue by llcat** [handsontable/handsontable#7000]
### Description
text wrap in cell will cause misalign, when your cell is a fixed width and content is too long, content is wrapped, it's good, but when I scroll to right, when other column's cell is empty, it will cause misalign，this issue really puzzle me a long time, how could i avoid this problem?

### Steps to reproduce

1. please see my  [demo](https://jsfiddle.net/pino_yu/frjybwvh/17/)
2. scroll handson-table to bottom, then scroll to right.
3. you will see a misalign in table.
  
![handsonbug](https://user-images.githubusercontent.com/17900822/84104258-bee06b80-aa47-11ea-9929-a0b299af9219.PNG)

### Demo

https://jsfiddle.net/pino_yu/frjybwvh/18/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome 83.0.4103.61
* Operating System: Win10

**Comment by pnowak** [comment]
Hi @llcat 

If you use an `autoRowSize: true` options the issue is gone.

Here is an updated demo - https://jsfiddle.net/5bo6k3he/1/

**Comment by llcat** [comment]
@pnowak thk for your reply! that's option work well~
