### ISSUE TITLE
We are not able to use 'Clear column' on the last visible column if filters were applied to a removed column

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7003]
### Description

We are not able to use `'Clear column'` on the last visible column if filters were applied to a removed column.
It works this way only if you want to clear the last visible column. It may be blocked by https://github.com/handsontable/handsontable/issues/7002

### Steps to reproduce

1. Go to https://jsfiddle.net/AMBudnik/pn5tedrg/
2. Filter out `A1` from `A` column
3. Use `'Remove column'` for column `A`
4. Open dropdown menu for column `B`

**Result**
The `'Clear column'` option is disabled.
![remove_issue](https://user-images.githubusercontent.com/10757813/84137894-a70be600-aa4d-11ea-8ea8-480f5d578356.gif)

### Demo

https://jsfiddle.net/AMBudnik/pn5tedrg/ 7.4.2 (broken)
https://jsfiddle.net/AMBudnik/jp0n2vsb/ 8.0.0-beta2-rev12 (broken)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chome 80
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 https://jsfiddle.net/1jahtr9m/ - the issue is still replicable

**Comment by wszymanski** [comment]
The `Filters` plugin doesn't have an influence on the way how the drop-down menu looks like.

Minimum example for the bug: https://jsfiddle.net/wojciech/qdzbm0sw.

### Steps to reproduce
1. Use 'Remove column' for column A
2. Open dropdown menu for column B

**Comment by aninde** [comment]
This issue will be fixed by the upcoming v8.2.0

v8.2.0 https://jsfiddle.net/zrjway9n/
Tested on macOS Catalina 10.15.7
- Chrome Beta 87 and stable 86
- FF 83.0b7 and stable 82
- Safari 14 and Safari Technology Prev 14.1

Windows 10
- IE 11
- Chrome 86
- Edge 86
- Edge Dev 88

**Comment by AMBudnik** [comment]
I'm glad to see this issue fixed. Thank you Team ! :)
