### ISSUE TITLE
We cannot set focus to a column to open context menu after applying a filter

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7005]
### Description

We cannot set focus to a column to open context menu after applying a filter. It may happen cause the filter is taking out the focus from a column.

### Steps to reproduce

1. Go to https://jsfiddle.net/AMBudnik/sn0gfrva/
2. Filter out any value from column `A`
3. Click RMB on that column

**Result**
You need to click another cell first, then you can activate focus on the column with RMB.
![focus](https://user-images.githubusercontent.com/10757813/84146215-a1b59800-aa5b-11ea-9d03-da0a2b2fa3ce.gif)

### Demo

https://jsfiddle.net/AMBudnik/sn0gfrva/ 7.4.2 (broken)
https://jsfiddle.net/AMBudnik/3wnhuksc/ 8.0.0.-beta2-rev12 (broken)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by wojciechczerniak** [comment]
Related to #5906 ?

**Comment by AMBudnik** [comment]
Remains the same in `8.0.0-beta2-rev21` https://jsfiddle.net/9w0fzd4r/
It may be related, but both issues are still the same in the latest beta2 revision.

**Comment by AMBudnik** [comment]
Works well using latest build https://jsfiddle.net/t05mq41r/ (frozen beta2)

**Comment by aninde** [comment]
This still works good with `v8` https://jsfiddle.net/aninde/2oy84ctp/.
