### ISSUE TITLE
Header merge

### ISSUE THREAD

**Issue by DrakLu** [handsontable/handsontable#7007]
[###]([url](url)) Description

### Steps to reproduce

1.I want to merge up and down the list header ，But I didn't see the rowspan attribute in the column

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:7.4.2
* Browser Name and version:edge
* Operating System:win10

**Comment by DrakLu** [comment]
What I want is a merge header, not a cell merge

**Comment by pnowak** [comment]
We have a `nestedHeaders` option - https://handsontable.com/docs/7.4.2/demo-nested-headers.html

Does it meet your requirements?

**Comment by AMBudnik** [comment]
I guess that we can close the topic as there are no updates for 10 days. But if there's anything we can do for you @DrakLu feel free to contact us here or on emails. We're available on support@handsontable.com

**Comment by deepthan** [comment]
I have implemented rowspan, which can be set in the same way as' nestedHeaders' and 'colspan', if you need it, please contact me at Github.
for example
```
nestedHeaders:  [
  [ { label: 'c', rowspan: 3}, { label: 'B', colspan: 9 }],
  ['', { label: 'E', colspan: 4 }, { label: 'F', colspan: 4 },  { label: 'G', rowspan: 3}],
  ['', { label: 'I', colspan: 2 }, { label: 'J', colspan: 2,  rowspan: 2 }, { label: 'K', colspan: 2 }, { label: 'L', colspan: 2 }, ''],
  ['N', { label: '2', colspan: 1 }, 'P', '', '', 'S', 'T', 'U', '22', '']
];

```

To render
![37818273a1cfa70243ff246937a0d9f](https://user-images.githubusercontent.com/22695767/158949613-993eae5d-83e6-497e-bd5e-40a05fde52ca.png)
