### ISSUE TITLE
Allow dynamic hide elements in DropDownMenu with conditional external variable or function

### ISSUE THREAD

**Issue by pablomagalhaes** [handsontable/handsontable#7009]
### Description

I would like to hide element in menu with variable value or function

### Steps to reproduce

1.
2.
3.

### Demo

Follow Example 
http://jsfiddle.net/pablot/e4rtLubp/153/

### Your environment
* Handsontable version: 7 >
* Browser Name and version: Chrome
* Operating System: MAC OS

**Comment by AMBudnik** [comment]
Hi @pablomagalhaes 

Here's an example that may interest you http://jsfiddle.net/handsoncode/npbs31d0/
Line `31` adds the hidden function that controls the option visibility. In the example, function uses selection indexes to hide the option once the selected row is index === 0

**Comment by pablomagalhaes** [comment]
Hi @AMBudnik - I'm sorry, but I don't think you understood me well. I want to hide a menu item via an external variable.

Example, I'm using React if I want to pass a variable that is in the state to do an if or else to hidden menu

**Comment by AMBudnik** [comment]
Here's a variable option http://jsfiddle.net/AMBudnik/7p8n1a5v/ 
Once you click the button you change the state of `turnThisOptionOff` that controls if the first option is visible or not. That's a vanilla version but it works the same for all the wrappers.

**Comment by pablomagalhaes** [comment]
Hi @AMBudnik - But this not works on ReactJs can you update this example, please:
http://jsfiddle.net/pablot/e4rtLubp/154/

if is possible passing, the variable from callback

**Comment by AMBudnik** [comment]
`Callback` is made to describe the action that takes place when the user chooses the option. `Hidden` controls the option visibility. Those are two separate options. `Hidden` has to return a boolean value. `True` hides the option, `false` shows it.

**Comment by pablomagalhaes** [comment]
@AMBudnik - So, how can I set the menu to hidden from the column name ? Please Help me

**Comment by AMBudnik** [comment]
You can listen to https://handsontable.com/docs/7.4.2/Hooks.html#event:afterGetColHeader hook that holds the column name and column index. Then, if meets your requirements share that index to the `hidden` function of the context menu.

**Comment by pablomagalhaes** [comment]
@AMBudnik - Please, can you show me with example in fiddle ?

**Comment by AMBudnik** [comment]
We construct custom demos on demand only for Clients with Extended/Premium support plans. However, as you're new to Handsontable I can share some demos for you to start.

Here is our base demo for constructing a React version of a custom context menu https://handsontable.com/docs/7.4.2/frameworks-wrapper-for-react-custom-context-menu-example.html

And here's a demo that should help you to add the functionality to your project https://jsfiddle.net/sfrb1pn9/2/

ps. as we keep Github for bug/feature purposes could you send all the advice/guidance on our email support@handsontable.com?

**Comment by pablomagalhaes** [comment]
@AMBudnik - Thanks for you support

**Comment by AMBudnik** [comment]
You're welcome. I'm glad to help.

**Comment by pablomagalhaes** [comment]
@AMBudnik - Another question please. How to call external function in reactjs inside callback ?

**Comment by AMBudnik** [comment]
Here https://jsfiddle.net/AMBudnik/xa9740ez/ is an example that uses function to log a message when column B opens a context menu.
