### ISSUE TITLE
[8.0.0-beta.2-rev13] Selecting a partially-hidden merged cell gives it a wrong color overlay.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#7010]
### Description
When selecting a partially-hidden merged cell, it gets a blue overlay, and it shouldn't.

Works fine until `rev13`.

### Steps to reproduce

1. Go to https://jsfiddle.net/js_ziggle/x29rhkgt/
2. Select the merged cell at (1, 1)

### Demo
https://jsfiddle.net/js_ziggle/x29rhkgt/

**Comment by wszymanski** [comment]
The below test hasn't guaranteed the case as we can see.

https://github.com/handsontable/handsontable/blob/7fbf9c8c19ecd96fbb7fc5721b2fb26419126e64/src/plugins/hiddenColumns/test/hiddenColumns.e2e.js#L5800-L5844

I will investigate.

**Comment by aninde** [comment]
This issue is solved by `8.0.0-beta2-rev18` https://jsfiddle.net/aninde/xmotLk3u/
<img width="209" alt="Screenshot 2020-06-30 at 14 44 46" src="https://user-images.githubusercontent.com/30186818/86127511-4c135f00-bae0-11ea-8102-0e39da91b0db.png">
