### ISSUE TITLE
TrimRows with fixed overlays

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7011]
### Description

Fixed overlays act wrong when trimRows is used.

#### case 1 
Now on the develop branch, the bottom overlay is not visible after trimming 4 out of 5 rows:
![Zrzut ekranu 2020-06-16 o 09 26 12](https://user-images.githubusercontent.com/571316/84744567-be9a2000-afb3-11ea-9766-9cea66c4e478.png)

Should be:
![Zrzut ekranu 2020-06-16 o 09 26 40](https://user-images.githubusercontent.com/571316/84744584-c22da700-afb3-11ea-9b89-efaa7ea4658b.png)

#### case 2
Now on the develop branch, the top overlay is shrunk to 0 when it has the same number of rows as dataset and one (or more) row is trimmed:
![Zrzut ekranu 2020-06-16 o 09 30 22](https://user-images.githubusercontent.com/571316/84745421-d32ae800-afb4-11ea-9ba5-892c0ebb523a.png)

Should be:
![Zrzut ekranu 2020-06-16 o 09 32 17](https://user-images.githubusercontent.com/571316/84745043-4bdd7480-afb4-11ea-8d8f-a26199ed1da2.png)

### Steps to reproduce

1. The provided demo should render one row for bottom overlay, instead, there are no rows;
2. The top overlay should be shrunk to one row but instead, it has 0 rows (only header is rendered here);

### Demo

https://jsfiddle.net/btynomau/2/

### Your environment
* Handsontable version: 8.0.0-beta.2-rev13
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment]
Both cases **fixed** in rev15 of 8.0.0-beta2

#### Case 1 https://jsfiddle.net/etm92rwv/
```js
fixedRowsTop: 1,
fixedRowsBottom: 1, 
trimRows: [0,1,2,4]
```
![Zrzut ekranu 2020-06-17 o 13 50 31](https://user-images.githubusercontent.com/10757813/84894933-f089b000-b0a1-11ea-81df-6fb03ec2ead1.png)

#### Case 2 https://jsfiddle.net/etm92rwv/1/
```js
fixedRowsTop: 2,
trimRows: [0]
```
![Zrzut ekranu 2020-06-17 o 14 01 34](https://user-images.githubusercontent.com/10757813/84895734-12376700-b0a3-11ea-91a9-003a6c5db7c7.png)


Tested on Chrome 83 macOS Catalina
