### ISSUE TITLE
How to calling inside callback external function in REACTJS. **URGENT

### ISSUE THREAD

**Issue by pablomagalhaes** [handsontable/handsontable#7013]
### Description

I would like to calling in callback context menu external function

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by pablomagalhaes** [comment]
@AMBudnik - can you help me?

**Comment by AMBudnik** [comment]
Hi @pablomagalhaes 

As mentioned before we keep Github for bugs and features. All 'how to'/guidance questions we answer on emails.

Please send me an email to support@handsontable.com (and refer to your license ID).
