### ISSUE TITLE
How to open Modal inside DropDown Menu item

### ISSUE THREAD

**Issue by pablomagalhaes** [handsontable/handsontable#7014]
### Description

In reactjs how to call modal inside item callback

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @pablomagalhaes 

As mentioned before we keep Github for bugs and features. All 'how to'/guidance questions we answer on emails.

Please send me an email to support@handsontable.com (and refer to your license ID).
