### ISSUE TITLE
Remove GanttChart plugin

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#7022]
### Description

- [x] Remove GanttChart from the main bundles
- [x] Remove GanttChart from v8 guide docs
- [x] Remove GanttChart from v8 api docs
- [x] Remove GanttChart from the website
- [ ] We can keep the plugin code in the repository for now
- [x] Would be cool to have a deprecation warning when someone tries to use gantchart in the settings

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
Will be done after removing https://github.com/handsontable/docs/commit/9483684ebc93dd3c61ce15e2ab892eb10335fe59#r40872457.

**Comment by aninde** [comment]
https://github.com/handsontable/handsontable/issues/7022#issuecomment-663466473 its done. We can close it after the release of `v8`.

**Comment by AMBudnik** [comment]
>  Would be cool to have a deprecation warning when someone tries to use gantchart in the settings

We get an error in the console, not a warning https://jsfiddle.net/AMBudnik/2sLgeh1o/ and the table does not show up.

![Zrzut ekranu 2020-09-1 o 12 47 03](https://user-images.githubusercontent.com/10757813/91840613-40aff180-ec51-11ea-8636-15f75b0c3e3e.png)

**Comment by lyqeyes** [comment]
Hi, is there a plan to support `GanttChart` in the coming future ?

**Comment by AMBudnik** [comment]
Hi @lyqeyes 

We do not have plans to re-add it in upcoming months but we are always pleased to receive feedback from our Users. 
Have you used the GanttChart in your project? If you'd like to look for some alternative functionalities please let me know. My email is support@handsontable.com
