### ISSUE TITLE
Deprecate HeaderTooltips plugin

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#7023]
### Description

Starting with version 8.0.0 the Header Tooltips plugin will be deprecated. We will remove it in the next major version.

- [x] Add a deprecation message to the release notes
- [x] Add a deprecation warning when someone enables HeaderTooltips plugin
- [x] Add a deprecation warning to the HeaderTooltips documentation pages 
- [x] Add a deprecation warning to config options in API reference

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
There is a deprecation message to the release notes and a deprecation warning when someone enables HeaderTooltips plugin.

Documentation needs to be updated. CC: @scarletfog 
After that and after v8 release, this issue will be ready to close.

**Comment by scarletfog** [comment]
@aninde it is present in the docs, probably on the `next` branch but it should be double-checked before closing the ticket

![image](https://user-images.githubusercontent.com/20072336/88038340-602e0780-cb46-11ea-8534-22b4461daa58.png)

![image](https://user-images.githubusercontent.com/20072336/88038405-763bc800-cb46-11ea-9df9-271c44571e10.png)

**Comment by aninde** [comment]
Done by https://github.com/handsontable/docs/commit/bdbcf163aa6274a2301c63887cc4302e307503e5.
