### ISSUE TITLE
Deprecate IE support

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#7026]
### Description

Starting with version 8.0.0 the support for IE web browser will be deprecated. We will remove all the workarounds at some point in one of the next major releases. Until then HoT will work in IE browsers as it does currently, but we will no longer try to fix or workaround IE bugs.

- [x] Add a deprecation message to the release notes
- [x] Remove IE from the supported browsers in the documentation
- [x] Add the deprecation warning to the supported browsers page in the docs

This will unblock #6635

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Label changed from 'IE/Edge' to 'Edge'.

**Comment by AMBudnik** [comment]
To be closed with https://github.com/handsontable/handsontable/issues/7026

**Comment by aninde** [comment]
Done by https://github.com/handsontable/docs/commit/28454e88bbd3bb26382c308601a5f476305f8762.

**Comment by AMBudnik** [comment]
We can call this to-do list as done and implemented in v 8.0.0

**Comment by AMBudnik** [comment]
v12 made the final changes to this issue 

> Dropped support for Internet Explorer 11 and non-Chromium Edge. Handsontable 11.x becomes the long-term support (LTS) version for Internet Explorer 11 and non-Chromium Edge, until the end of 2023

Here https://github.com/handsontable/handsontable/issues/9434 you can read more about the changes in v12
