### ISSUE TITLE
[1.18.0] Too many layers of highlight with noncontinuous selection on merged cells

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7028]
### Description
Selecting a merged cell by `noncontinous selection` causes to many layers of highlight. 
Highlight is too dark. Styling has changed over versions, but unfortunately, the effect has remained incorrect.

### Steps to reproduce

1. Open demo https://jsfiddle.net/aninde/eqkb7fy8/
2. While holding <kbd>cmd</kbd> select cells E5-E4-E3-E2-D2-B2
![1 17 0-bug](https://user-images.githubusercontent.com/30186818/85025481-be4a8200-b177-11ea-8260-9bc3ca84181c.gif)

### Demo

https://jsfiddle.net/aninde/eqkb7fy8/  broken `v1.18.0`
https://jsfiddle.net/aninde/2zeah3vd/ broken `v2.0.0` with hiddenColumns
https://jsfiddle.net/aninde/9qx8wzr4/ broken `v8.0.0-beta2-rev15`

**Case 2**
A highlight is even darker when some merged cells are also hidden.
This can be seen from the second version https://jsfiddle.net/aninde/2zeah3vd/

<img width="328" alt="Screenshot 2020-06-18 at 15 33 24" src="https://user-images.githubusercontent.com/30186818/85026781-657be900-b179-11ea-85fc-96df88d87a4a.png">

### Your environment
* Handsontable version: 1.18.0+ and 2+ with hiddenColumns
* Browser Name and version: Chrome 83, Firefox 77
* Operating System: macOS Catalina 10.15.5

**Comment by AMBudnik** [comment]
Issue **fixed** in `8.0.0-beta2-rev21` https://jsfiddle.net/7sjgz3re/

**Before**
![Zrzut ekranu 2020-07-10 o 14 21 23](https://user-images.githubusercontent.com/10757813/87154055-d31ebf00-c2b8-11ea-9fc8-c1f28a963051.png)


**After**
![Zrzut ekranu 2020-07-10 o 14 22 07](https://user-images.githubusercontent.com/10757813/87154061-d4e88280-c2b8-11ea-9662-f780ea34e340.png)

**Comment by aninde** [comment]
This issue remain fixed with `8.0.0-rev1` https://jsfiddle.net/aninde/xjzc8hau/.

**Comment by AMBudnik** [comment]
Issue officially fixed in Handsontable v 8.0.0
