### ISSUE TITLE
How to use  hot.getPlugin('nestedHeaders') with getHeaderSettings(0,0)   In React js.

### ISSUE THREAD

**Issue by pablomagalhaes** [handsontable/handsontable#7033]
### Description

const nestedHeadersPlugin = hot.getPlugin('nestedHeaders');.

And then you could use getHeaderSettings - 
nestedHeadersPlugin.getHeaderSettings(headerLevel, columnIndex). Where headerLevel is a header level (0 = most distant to the table) and columnIndex is a visual column index.

So, for example, when you call nestedHeadersPlugin.getHeaderSettings(0, 0) you get an object with these properties:

### Demo

This is my Demo:  http://jsfiddle.net/pablot/1e4kdvw3/69/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by pablomagalhaes** [comment]
@AMBudnik - Sorry, can you help me? Please

**Comment by AMBudnik** [comment]
Hi @pablomagalhaes 

Please follow the guide from this comment https://github.com/handsontable/handsontable/issues/7013#issuecomment-644554294

> As mentioned before we keep Github for bugs and features. All 'how to'/guidance questions we answer on emails.

> Please send me an email to support@handsontable.com (and refer to your license ID).

We have a lot of issues opened on Github and need to make sure that all of them refer to bugs/features.
