### ISSUE TITLE
Handsontable pre-compressed with Brotli:11 on open source CDN

### ISSUE THREAD

**Issue by praisedpk** [handsontable/handsontable#7039]
I have added Handsontable on PageCDN. Current size of [handsontable.full.min.js](https://pagecdn.io/lib/handsontable/7.4.2/handsontable.full.min.js) on PageCDN is just **228 KB** that is around 42 KB smaller than normal due to better compression. The files are available on CDN here: https://pagecdn.com/lib/handsontable

Adding this CDN link on download page or in docs is helpful for users looking to reduce JS size.

Thanks.

**Comment by AMBudnik** [comment]
That's an interesting finding, thank you for sharing @praisedpk and giving us some idea on how to serve the files to reduce bundle size.

**Comment by praisedpk** [comment]
Thanks @AMBudnik for your time.

Many JS projects list multiple CDNs to choose from specially when every CDN has different pros and cons. That's why I created this issue.

However, decision is yours.

Thanks :)

**Comment by AMBudnik** [comment]
That's true. I'll mention the idea among the team and if we'd decide to include Brotli in our installation guide I'll update this thread.

**Comment by wojciechczerniak** [comment]
Thanks! We will keep it under consideration on our dev ops backlog. Meanwhile, this is not an actionable issue for Handsotable product so I'm closing it during this week cleanup.
