### ISSUE TITLE
getHeaderSettings Not works on React Js

### ISSUE THREAD

**Issue by pablomagalhaes** [handsontable/handsontable#7040]
### Demo

http://jsfiddle.net/pablot/1e4kdvw3/69/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @pablomagalhaes 

The `getHeaderSettings` is not a part of the `nestedHeaders` plugin. Here is a set of the officially supported [`nestedHeaders` methods.](https://handsontable.com/docs/7.4.2/NestedHeaders.html)

![Zrzut ekranu 2020-06-23 o 08 51 52](https://user-images.githubusercontent.com/10757813/85370368-e0088800-b52e-11ea-97d2-0f7ed6263e1e.png)

**Comment by pablomagalhaes** [comment]
But, How to get nested Header Name ?

**Comment by AMBudnik** [comment]
> But, How to get nested Header Name ?

Correct me if I'm wrong. You want to get all headers as an array/list or only top/bottom/all headers that are assigned to the dropdown menu column?

**Comment by pablomagalhaes** [comment]
Yes , sure. Look my example: 

 http://jsfiddle.net/pablot/1e4kdvw3/70/

How to get name of Top Header and column i select in moment.

> 7-LPA-D > M

**Comment by AMBudnik** [comment]
`hot.getSettings().nestedHeaders` returns an array of your nestedHeaders. Then you can use the `hot.getSelected()[0][1]` to return a selected column.

**Comment by pablomagalhaes** [comment]
Can you show how to make this here In React Js

 http://jsfiddle.net/pablot/1e4kdvw3/70/

**Comment by AMBudnik** [comment]
All methods remain the same for React for Handsontable or any other wrapper. The Only aspect that you need to solve is hot to get your 'hot' (instance). Here https://handsontable.com/docs/7.4.2/frameworks-wrapper-for-react-hot-reference.html is a demo that shows you how to achieve this in React.

**Comment by pablomagalhaes** [comment]
@AMBudnik - Yes i see. Thank you so much. But How to know top Header if the column has the same name.

Example:  

7-LPA-D > MD 
3-SPS-74 > MD

**Comment by AMBudnik** [comment]
Here's an example of the lowest header level https://jsfiddle.net/3ug6n0o1/ (N - W).
If you'd like to get the highest level your 

`hot.getSettings().nestedHeaders[(lvls.length - 1)][column]`

would need to be rewritten, as `lvls.length - 1` indicates the last array in the `nestedHeaders` array. You can just use `0` here

`hot.getSettings().nestedHeaders[0][column]`

but then you'll need to use the `colspan` (number) to shift the expected result, but that pure coding. There is no official API to achieve it. 
In the future, we plan to use some callback like `afterGetColHeader`, but currently, it works only for the 1lvl-header.

**Comment by pablomagalhaes** [comment]
@AMBudnik Thanks, but in the case i need to High Level header example   (N = H or D or A) 
in case i need to H or D or A you understand me?

**Comment by AMBudnik** [comment]
> @AMBudnik Thanks, but in the case i need to High Level header example (N = H or D or A)
> in case i need to H or D or A you understand me?

All the levels are here 

`hot.getSettings().nestedHeaders[number][column]`

hot.getSettings().nestedHeaders[**0**][column] - top level - A - C
hot.getSettings().nestedHeaders[**1**][column] - D - G
hot.getSettings().nestedHeaders[**2**][column] - H - M
hot.getSettings().nestedHeaders[**3**][column] - lowest level - N - W

**Comment by pablomagalhaes** [comment]
@AMBudnik - I don't understand how to use colspan. this still with error. 

https://jsfiddle.net/pablot/572gzp36/47/

**Comment by AMBudnik** [comment]
Thiago, you are asking me to work around functionality that we haven't provided yet. I'm trying to use officially supported methods to provide you some kind of guarantee that you can still update to newer versions without incompatibility errors. 

However, figuring out how to use `colspan` number to return level information is a purely JS task. I'm familiar with our API but when it comes to programming my skills are rather basic. I guess that I would start with an analysis 

If headers look like this
![Zrzut ekranu 2020-06-24 o 08 29 14](https://user-images.githubusercontent.com/10757813/85508721-e8c39180-b5f4-11ea-9325-08c787097b2f.png)
You can (one of the options)

Reconstruct that array to contain strings
`[A, B, B, B, B, B, B, B, B, C]` ... and so on.
Your `colspan` tells you how many `B`'s should be added to the array. 
Once you get a result like that you can use 

`let highHeader = hot.getSettings().nestedHeaders[0][column];`

to get the top level
`let highHeader = hot.getSettings().nestedHeaders[1][column];`
to get 2nd level... and so on.
