### ISSUE TITLE
afterSelectionEnd returns incorrect data when clicking on a column when we have all the rows hidden

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7045]
### Description

`afterSelectionEnd` returns incorrect data when clicking on a column when we have all the rows hidden.

### Steps to reproduce

1. Click `A` header

**Result**
`7.4.2`
![Zrzut ekranu 2020-06-23 o 11 44 05](https://user-images.githubusercontent.com/10757813/85388825-dc80fb00-b546-11ea-817c-e754ccb07f36.png)
![Zrzut ekranu 2020-06-23 o 11 40 47](https://user-images.githubusercontent.com/10757813/85388475-68deee00-b546-11ea-8eb2-1e34a42e8abd.png)

`8.0.0-beta2-rev16`
![Zrzut ekranu 2020-06-23 o 11 43 30](https://user-images.githubusercontent.com/10757813/85388763-c7a46780-b546-11ea-921c-67cb9dbb8172.png)
![Zrzut ekranu 2020-06-23 o 11 41 19](https://user-images.githubusercontent.com/10757813/85388521-7a27fa80-b546-11ea-9f50-62d51c215a0c.png)

### Demo

https://jsfiddle.net/Lvwcxnsd/10/ 7.4.2 (broken)
https://jsfiddle.net/f7c32xoj/17/ 8.0.0-beta2-rev16 (solved)

### Related issues
* https://github.com/handsontable/handsontable/issues/6728

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
Result in `8.0.0-beta2-rev21` https://jsfiddle.net/1rn2f09o/

![Zrzut ekranu 2020-07-10 o 14 13 13](https://user-images.githubusercontent.com/10757813/87153302-8dadc200-c2b7-11ea-8f7a-3cb826a56dc4.png)

![Zrzut ekranu 2020-07-10 o 14 13 20](https://user-images.githubusercontent.com/10757813/87153311-90101c00-c2b7-11ea-9ce4-66beada2d0ee.png)
(after adding the `-1` value for a header)

**Comment by aninde** [comment]
Remains solved with `8.0.0-beta2` and `pre-8.0.0` https://jsfiddle.net/aninde/fez6x54o/.

**Comment by AMBudnik** [comment]
Thank you for solving team! Fix to this issue is available in v 8.0.0 

**CDN** https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
**NPM** npm i handsontable
**Release Notes** https://github.com/handsontable/handsontable/releases
