### ISSUE TITLE
`maxCols` doesn't seem to work properly with `dropdownMenu`.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#7048]
### Description
When we set `maxCols` to smaller than declared dataset and we want to `clearColumn` we don't have this option in `dropdownMenu`:
<img width="269" alt="Zrzut ekranu 2020-06-24 o 10 59 23" src="https://user-images.githubusercontent.com/1555809/85526308-2da5f300-b60a-11ea-9dce-78d76007652f.png">

Without `maxCols` we have this option:
<img width="283" alt="Zrzut ekranu 2020-06-24 o 10 59 39" src="https://user-images.githubusercontent.com/1555809/85526328-33033d80-b60a-11ea-9db8-9b86d5865a8f.png">

### Steps to reproduce

1. Open the demo and click `dropdownMenu`.

### Demo

https://jsfiddle.net/0brhdqx2/

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version:
* Operating System:

`Inform Zen 24981`

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 https://jsfiddle.net/AMBudnik/9xtgy30a/ works the same as described.

**Comment by swistach** [comment]
We fixed it in v8.2: https://jsfiddle.net/g65vkux1/ 🎉
