### ISSUE TITLE
[8.0.0-beta2-rev11] Moving resized row / selection on fixed, scrolled table causes errors

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7049]
### Description
Fast scrolling and selection cause error in console when resizing and moving are enabled with fixed rows/columns.
This bug can be reproduced in two ways - Case 1 and Case 2.

_TypeError: Cannot read property 'firstChild' of undefined_ in Chrome

**Case 1**
![moving-resized](https://user-images.githubusercontent.com/30186818/85567618-4f66a080-b631-11ea-9941-69a14d5aad4e.gif)

**Case 2**
![scrolling-with-resize-move-fixed-enabled-chrome](https://user-images.githubusercontent.com/30186818/85566730-9738f800-b630-11ea-9a24-2ac2ae670c0c.gif)

### Steps to reproduce
**Case 1**
1. Resize the first row
2. Try to move it to the end of the table only using a mouse, you want to scroll the table with this move.
 
**Case 2**
1. Select the first column by clicking on its header
2. Scroll down by trackpad (I used Magic Mouse) it cannot be reproduced without losing focus
3. Click on the random cell

### Demo

https://jsfiddle.net/uLa0qfke/ `v.8.0.0-beta2-rev11` - broken
https://jsfiddle.net/1pjyrhmq/ `v.8.0.0-beta2-rev16` - broken
https://jsfiddle.net/aninde/mxf1tqd5/ `v7.4.2` - fixed
https://jsfiddle.net/aninde/Lgv03srb/. - `v8.0.0-beta.1` - fixed

### Your environment
* Handsontable version: v.8.0.0-beta2-rev11+
* Browser Name and version: Firefox 77, Chrome 83
* Operating System: macOS Catalina 10.15.5

**Comment by budnix** [comment]
The issue is fixed within https://github.com/handsontable/handsontable/pull/7044.

**Comment by aninde** [comment]
Both cases are solved with `8.0.0-beta2-rev17` https://jsfiddle.net/aninde/z4jevpt1/2/.
