### ISSUE TITLE
[8.0.0-beta2-rev1] HOT's not highlighting the header A with a grey background when the method `selectCell` is called on a hidden cell

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7052]
### Description

Deconstructing the issue from https://github.com/handsontable/handsontable/issues/7051 I'm adding the issue for not highlighting the header A with a grey background when the method `selectCell` is called on a hidden cell.

### Steps to reproduce

1. Just open the demo

### Demo

https://jsfiddle.net/ytsr4e7L/ 7.4.2 (working)
https://jsfiddle.net/ytsr4e7L/1/ 8.0.0-beta1 (wroking)
https://jsfiddle.net/ytsr4e7L/2/ 8.0.0-beta2-rev1 https://jsfiddle.net/ytsr4e7L/2/ (**broken**)
https://jsfiddle.net/ytsr4e7L/4/ 8.0.0-beta2-rev17 (still broken)

### Your environment
* Handsontable version: 8.0.0-beta2-rev1
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina

**Comment by budnix** [comment]
This PR https://github.com/handsontable/handsontable/pull/7053 fixes this issue.

**Comment by AMBudnik** [comment]
Fixed in 8.0.0-beta2-rev17 https://jsfiddle.net/0ervpa75/

I've tested 3 cases
* selecting 0, 0 (as in the issue)
* selecting 2nd column
* selecting both columns
All 3 cases are working as expected.
