### ISSUE TITLE
[8.0.0-beta2] Handsontable does not appear on IE9 

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7054]
### Description

[8.0.0-beta2] Handsontable does not appear on IE9. We are slowly deprecating Internet Explorer support but decided to publish this bug report.

When we try to build any instance we are getting only console errors. The number of errors grows with each mouse move.

![ie](https://user-images.githubusercontent.com/10757813/85857150-94b5da00-b7b9-11ea-9fcc-228d625ff419.png)

### Sources for local build

8.0.0-beta2-rev17
https://cdn.jsdelivr.net/gh/handsontable/handsontable@12aba961774e177460c1428bc05afe8dba9159fd/dist/handsontable.full.min.js

### Additional info
* works well on IE 11 and IE 10

### Your environment
* Handsontable version: 8.0.0-beta2
* Browser Name and version: IE 9
* Operating System: Windows 10

**Comment by wszymanski** [comment]
It seems that it doesn't work also on IE 10. Probably related to https://github.com/handsontable/handsontable/pull/6887 which introduced private methods. It seems that the default polyfill for the feature uses `WeakMap` [supported from IE 11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap).

**Comment by wszymanski** [comment]
It seems that https://github.com/handsontable/handsontable/pull/6425 have broken IE9.

**Comment by AMBudnik** [comment]
I've just checked the emulation of IE9 on my Windows 10 and the issue is fixed. 
Tested with v 8.0.0-beta2-rev18
