### ISSUE TITLE
React Redux with Nested Header don't work. 

### ISSUE THREAD

**Issue by pablomagalhaes** [handsontable/handsontable#7055]
### Description

I need to use React Redux with nested header but i get error when try to use.
### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by pnowak** [comment]
Hi @pablomagalhaes 

As you may see in this demo - https://jsfiddle.net/yub9qvg0/ - we use `nestedHeaders` in our `Redux` example and we don't have any error.

So can you show your implementation?
