### ISSUE TITLE
data manipulation before paste understanding

### ISSUE THREAD

**Issue by natinati8520** [handsontable/handsontable#7056]
Hi

### Description
When I paste data to the table I want to do some data manipulation on it before it will be paste.
I used the "beforePaste" hook and change the data variable but the data that was pasted was the original one.
Is it even possible to do what I just tried?

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: chrome 83.0.4103.116
* Operating System: win 10

**Comment by AMBudnik** [comment]
Hi @natinati8520 

Here's https://jsfiddle.net/jqdm3zrw/ an example on how to change data via `beforePaste` hook.

**Comment by natinati8520** [comment]
Thanks, it worked!
Is there any functional way doing it?

**Comment by AMBudnik** [comment]
Not really @natinati8520, we only serve the hook - the rest is on the developer.
