### ISSUE TITLE
[8.0.0-beta1-rev1] Custom borders are changing coordinates when data is hidden

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7057]
### Description

Custom borders are changing coordinates when data is hidden.

### Steps to reproduce

1. Just open the demo to see the difference in borders

**7.4.2**
![Zrzut ekranu 2020-06-29 o 15 06 40](https://user-images.githubusercontent.com/10757813/86009177-2facef00-ba1a-11ea-92d2-37270d9d7307.png)

**8.0.0-beta2-rev17**
![Zrzut ekranu 2020-06-29 o 15 10 49](https://user-images.githubusercontent.com/10757813/86009636-bcf04380-ba1a-11ea-9591-9772a38bdee6.png)

### Demo

https://jsfiddle.net/mohye6v5/2/ 8.0.0-beta2-rev17 (broken)
https://jsfiddle.net/mohye6v5/3/ 8.0.0-beta1-rev1 (**broken**)
https://jsfiddle.net/4hg5fsmv/ 8.0.0-beta1 (working)
https://jsfiddle.net/t45orfL9/ 7.4.2 (working)

### Your environment
* Handsontable version: 8.0.0-beta1-rev1 
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina

**Comment by aninde** [comment]
Solved by `8.0.0.-beta2-rev20` https://jsfiddle.net/aninde/s85ykbt6/ with breaking change. Details are described in  https://github.com/handsontable/handsontable/pull/7083
![solved](https://user-images.githubusercontent.com/30186818/86902578-6f589280-c10e-11ea-8935-134ad1023a6a.gif)
