### ISSUE TITLE
[8.0.0-beta1-rev1] custom border is added on the wrong coordinates if data is hidden before the cell with the border

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7058]
### Description

The custom border is added on the wrong coordinates if data is hidden before the cell with the border.

### Steps to reproduce

1. Open context menu to add any border to cell `D1`
2. Click anywhere in the table

**Result 8.0.0-beta1-rev1+**
Border is added to `F1` instead `D1`.
![bad](https://user-images.githubusercontent.com/10757813/86010784-2ae93a80-ba1c-11ea-88e3-6af3a7b3b59f.gif)

### Important
* it works well if we try to add borders before hidden columns

### Demo

https://jsfiddle.net/41swhont/2/ 8.0.0-beta2-rev17 (broken)
https://jsfiddle.net/41swhont/5/ 8.0.0-beta1-rev1 (**broken**)
https://jsfiddle.net/41swhont/4/ 8.0.0-beta1 (broken)
https://jsfiddle.net/41swhont/3/ 7.4.2 (working)

### Related issues
* https://github.com/handsontable/handsontable/issues/7057

### Your environment
* Handsontable version: 8.0.0-beta1-rev1
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina

**Comment by aninde** [comment]
I'm very glad to see that it's solved by `8.0.0-rev20` https://jsfiddle.net/aninde/tzdeob08/ in both cases. When you add border from contextMenu on cell and from colHeader.
![solved-rev20](https://user-images.githubusercontent.com/30186818/86904903-9ebcce80-c111-11ea-9f4c-5ed490358cda.gif)
