### ISSUE TITLE
How to have dynamic with for a column?

### ISSUE THREAD

**Issue by josegrad** [handsontable/handsontable#706]
I'm a bit confused with widths. I just changed from release 0.6 to 0.9
With 0.6 the tables would automatically stretch each column to fit the data. Now apparently there is the strecthH option, the column width and colWidths to manipulate widths. But with absolute values or options that affect all or no columns.

It would be nice to be able to specify a single column to stretch.
Or in the colWidths to be able to tell columns that can stretch.

Maybe I'm missing something (?)
I this fiddle: http://jsfiddle.net/vVbLr/18/
How can I make the second column to adapt to the contents, or just have a max width? Leaving the other columns as they are since their content fits.

**Comment by banwait-amarjeet** [comment]
I am using "autoColumnSize" and it is working perfectly but I need to set min-width and max-width also so any col-width should should vary in between defined min and max range.
I there any way to do this.

**Comment by abdulwahabplus** [comment]
Is there any way to set min-width for columns ?

**Comment by AMBudnik** [comment]
Hi @abdulwahabplus 
If you would like to set a min width and then expand the table if there's more content you would need to:
1. set `colWidths: number`, where `numer` is a value in pixels for the column
2. trigger a change event to modify column width if content length is more than the column can handle.
