### ISSUE TITLE
Problems with adding rows from the corner when all rows are trimmed

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7061]
### Description
1. Inconsistency - you can't **add rows** from the menu in column headers, but you can do that from the corner. I report it to open a discussion.
<img width="319" alt="Screenshot 2020-06-29 at 16 25 28" src="https://user-images.githubusercontent.com/30186818/86018757-127e1d80-ba26-11ea-94ed-6619f0892eba.png">
<img width="283" alt="Screenshot 2020-06-29 at 15 53 25" src="https://user-images.githubusercontent.com/30186818/86018767-15790e00-ba26-11ea-8733-8632c19c1822.png">
<img width="268" alt="Screenshot 2020-06-29 at 15 53 32" src="https://user-images.githubusercontent.com/30186818/86018774-16aa3b00-ba26-11ea-9aa4-fc3dc75792ef.png">

2. You cannot undo the addition of the first newly added row.

![cannot-und0](https://user-images.githubusercontent.com/30186818/86018652-ef536e00-ba25-11ea-94f0-bad9d4fda452.gif)

### Steps to reproduce

1. Open contextMenu on corner.
2. Add row below.
3. Undo by CMD+Z or via `contextMenu`

Result:
Nothing happens with newly added row. In the contextMenu `undo` is grey (non-avaliable)

### Demo

 https://jsfiddle.net/aninde/7o6ept9y/

### Your environment
* Handsontable version: 1+
* Browser Name and version: Firefox 77, Chrome 83
* Operating System: macOS Catalina 10.15

**Comment by AMBudnik** [comment]
#### Below is the behavior comparison when top-left corner is clicked with RMB

pre 8.0.0-beta2 https://jsfiddle.net/6vo42ue3/
![image](https://user-images.githubusercontent.com/10757813/87307600-30657b00-c51a-11ea-9066-b2d4ed924773.png)

7.4.2 https://jsfiddle.net/fqxm491v/
![742_](https://user-images.githubusercontent.com/10757813/87307731-63a80a00-c51a-11ea-81c6-e67e63281e74.png)

**Comment by aninde** [comment]
This issue had two bug reports: 
1. Inconsistency - you can't add rows from the menu in column headers, but you can do that from the corner. https://github.com/handsontable/handsontable/issues/7061#issuecomment-657549568
2. Inability to undo an added line from a corner.

Both of them are fixed by `v8.0.0` https://jsfiddle.net/aninde/h6zkbas9/. Changes were introduced by https://github.com/handsontable/handsontable/pull/7082#issue-445323799
