### ISSUE TITLE
[8.0.0-beta2-rev17] Click on the corner doesn't select headers when rows are trimmed

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7063]
### Description

When I click on the corner when there are some cells then the row and column headers are highlighted. However when the rows or columns are trimmed then nothing happens. it would be nice if headers were highlighted in this case.

This is related to how the `selectAll` method works (or doesn't work).

### Steps to reproduce

1. Go to https://jsfiddle.net/budnix/056f1mxa/;
2. Trim all rows using Filters feature;
3. Click on the corner;
4. In a result nothing happens;

### Demo

https://jsfiddle.net/budnix/056f1mxa/

### Your environment
* Handsontable version: ~8.0.0-beta.2-rev17
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
Related to https://github.com/handsontable/handsontable/issues/7061

**Comment by aninde** [comment]
This issue is solved by `8.0.0-beta2-rev19` https://jsfiddle.net/aninde/fjxc4w35/
![fixed](https://user-images.githubusercontent.com/30186818/86771345-59859780-c052-11ea-95af-197bce3107bc.gif)
