### ISSUE TITLE
Multi handsontables bug in one page 

### ISSUE THREAD

**Issue by appleyangz** [handsontable/handsontable#7067]
### Description

If i create multi Handsontables ,for example  :
<div id="hot1"></div>
<div id="hot2"></div>
then , init handsontable use js ：
var hot1 = new Handsontable(hotEle1, hotSettings1);
var hot2 = new Handsontable(hotEle2, hotSettings2);
then , if I operate hot1,same change occured in the hot2,
like the screenshot
![image](https://user-images.githubusercontent.com/20251286/86221342-5eac9780-bbb7-11ea-9093-90edf1670441.png)

### Steps to reproduce

1.Handsontable version:7.3.0
2.Browser Name and version:chrome
3.Operating System:win10

**Comment by pnowak** [comment]
Hi @appleyangz 

Can you show your implementation?

I tried to reproduce your issue - https://jsfiddle.net/7m3go4zx/ - but without success.

**Comment by AMBudnik** [comment]
Hi @appleyangz please share the demo at support@handsontable.com when you'll be ready.
