### ISSUE TITLE
We have to update type definition for `beforeColumnResize` and `beforeRowResize`

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#7070]
### Description
After switching parameters in this PR - https://github.com/handsontable/handsontable/pull/6090 - in `beforeColumnResize` and `beforeRowResize` the first parameter could be `null` (not just the `number` as it stands in our type definition).

**Comment by pnowak** [comment]
After a short discussion, we decide that this is a bug, unfortunately. 
So TS definitions are correct.

**Comment by AMBudnik** [comment]
We fixed the issue with getting null values instead of numeric in v 8.0.0
