### ISSUE TITLE
The row/column resize hooks should not return `null`.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#7074]
### Description
The row/column-resizing hooks should not return `null` values.

**Related issues:**
- https://github.com/handsontable/handsontable/issues/6430#issuecomment-652941090
- https://github.com/handsontable/handsontable/issues/7070
- https://github.com/handsontable/handsontable/pull/6090

### Steps to reproduce

1. Go to https://jsfiddle.net/csd0t374/, resize a row to a minimal value and watch the console.

### Demo
https://jsfiddle.net/csd0t374/

**Comment by AMBudnik** [comment]
Issue fixed in `8.0.0-beta2-rev21` https://jsfiddle.net/k87eb9f2/
Now we receive `23` instead of `null` in the same scenario.

**Comment by AMBudnik** [comment]
Works well using latest build https://jsfiddle.net/6re5oxwk/ (frozen beta2)

**Comment by AMBudnik** [comment]
Officially fixed in v 8.0.0 https://jsfiddle.net/r076j385/ (no `null` detected).
