### ISSUE TITLE
[2.0.0] Loss of selection after merging from headers

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7076]
### Description
When we select cells by choosing col headers and try to merge cells we losing header selection.

### Steps to reproduce
1. Select both columns by clicking on their headers suing RMB
2. Use `Merge Cells` from the context menu

**Result**: Losing selection and focus on headers

![merge-2 0 0](https://user-images.githubusercontent.com/30186818/86588263-afdbd300-bf8b-11ea-949d-b013d319d78f.gif)

### Demo

https://jsfiddle.net/aninde/8tcsvabn/

### Your environment
* Handsontable version: 2+
* Browser Name and version: Firefox 78
* Operating System: macOS Catalina 10.15.5

**Comment by aninde** [comment]
This issue is solved by `8.0.0-beta2-rev18`  https://jsfiddle.net/z4Lno5sc/
![solved-rev18](https://user-images.githubusercontent.com/30186818/86588319-c550fd00-bf8b-11ea-82fb-7cd26b3e6713.gif)

**Comment by AMBudnik** [comment]
Officially fixed in Handsontable v 8.0.0. Updated demo https://jsfiddle.net/kpsuf836/
