### ISSUE TITLE
How can I set a conditional style for a "date" type of cell?

### ISSUE THREAD

**Issue by joechanhk** [handsontable/handsontable#7078]
### Description
I can set a conditional style for a cell like if the day is past style.color = 'red' however it doesn't works after I set the type of cell into "date"

### Steps to reproduce

1.Make a renderer for a column
2.Make a style for it (make it works on this step)
3.Set cellProperties.type = 'date' (this seems overrite the above setting, the cells become date type but style disabled)

 hot = new Handsontable(container, {
	data	: data,
	columns : [
		{
			renderer:function(hotInstance, TD, row, col, prop, value, cellProperties){
				TD.innerHTML = value;
				TD.style.color = 'red';
				cellProperties.type = 'date'; 
			}
		},
		{},{}
	]
}

### Demo

I'm sorry, can't access the link :  https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 77.0.3865.90
* Operating System: Window 10

**Comment by AMBudnik** [comment]
Hi @joechanhk 

`Date` is treated as a string. There are no official API methods to handle date calculations. The API that we use it provided by our dependencies, but methods are not exposed outside the plugins.
I recommend checking this topic https://stackoverflow.com/questions/5619202/converting-a-string-to-a-date-in-javascript where there's a discussion on how to convert strings to actual comparable values.

**Comment by joechanhk** [comment]
Hi @AMBudnik 

Thank you very much for the quick respond, I have no problem for handle the date calculations but I can't set style ( e.g. set color as red ) for the cell which set as a date type, in other words how can I display a colored fonts in a date type cell?

Thanks again

**Comment by AMBudnik** [comment]
@joechanhk 

The `td.style.color = 'red';` used in your example above should work.
Example https://jsfiddle.net/zmt51oc0/
Result
![Zrzut ekranu 2020-07-7 o 10 32 33](https://user-images.githubusercontent.com/10757813/86749039-37cde580-c03d-11ea-88bf-5b613f55f85e.png)

Code
![Zrzut ekranu 2020-07-7 o 10 32 50](https://user-images.githubusercontent.com/10757813/86749049-3a303f80-c03d-11ea-8314-4574efb81e52.png)

If it doesn't work you might have some other CSS settings conflicting the one from renderer, example: general styles, formatting from `cell`/`cells`.

**Comment by joechanhk** [comment]
It's works!
Thank again for helping me out.
