### ISSUE TITLE
How to get width column 

### ISSUE THREAD

**Issue by pvagithub** [handsontable/handsontable#708]
Hi All,
I want create a new table similar the old table to width column. the new table no data but old table data is available, How to get width each column the old table to set width column of the new table.
Thanks.
An.

**Comment by AMBudnik** [comment]
I'm not sure if I understand it correctly. You want to have one table filled with data and a second table empty but with the same amount of rows/cols as the first table? Can you provide a demo of your code?

**Comment by AMBudnik** [comment]
Issue will stay closed till an author's reply
