### ISSUE TITLE
Autocomplete list not fully accessible

### ISSUE THREAD

**Issue by MuyBien** [handsontable/handsontable#7081]
### Description

I have an autocomplete column and a handsontable container with fixed height (this is important). When I start typing characters in the last row of the autocomplete column, the possibles values are shown in top of the cell but they are not accessible. It seems that only one is showing but in fact there is a scroll for showing more and sometimes some values are behind the table.

### Steps to reproduce

1. Go to http://jsfiddle.net/k46d28nr/
2. Start typing in the last row of column "Autocomplete with source"

### Demo

http://jsfiddle.net/k46d28nr/

There is 3 possibles values here but only one is shown.
![image](https://user-images.githubusercontent.com/1921522/86750214-18838800-c03e-11ea-98f6-16bc9d02e7d9.png)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 83 and FF 78
* Operating System: Ubuntu 18.04.4

**Comment by AMBudnik** [comment]
Hi @MuyBien 

thank you for sharing the issue. It is caused by the overflow settings, and has been reported here https://github.com/handsontable/handsontable/issues/3828

I will update you once we get it done.

**Comment by MuyBien** [comment]
Oh yeah, thanks! I didn't see it!
