### ISSUE TITLE
[8.0.0-beta2-rev19] Fixed columns and rows doesn't work while scrolling

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7086]
### Description
Fixed/frozen row and columns are not fixed when scrolling in both directions without defined `height` and `width`.

This applies to:
`fixedColumnLeft`, `freezeColumn`, `fixedRowsTop` and `fixedRowsBottom`.

### Steps to reproduce

Open a demo and scroll it in both directions

**Actual result:**
![broken-fixing](https://user-images.githubusercontent.com/30186818/86893516-0834e100-c102-11ea-8bc4-08ff3449ab30.gif)

**Expected result:**
No worse than in `7.4.2`

### Demo

https://jsfiddle.net/aninde/qv6aesfb/ - `v.7.4.2` (solved)
https://jsfiddle.net/aninde/hm12drc7/ - `8.0.0-beta.1` (solved)
https://jsfiddle.net/aninde/qydsh63t/ - `v.8.0.0-beta2-rev18` (solved)
https://jsfiddle.net/aninde/dvpxjo49/ - `v.8.0.0-beta2-rev19` (**broken**)
https://jsfiddle.net/aninde/4tf5vbk0/ - `v.8.0.0-beta2-rev20` (**broken**)

### Your environment
* Handsontable version: v.8.0.0-beta2-rev19
* Browser Name and version: Firefox 78, Chrome 83, Safari
* Operating System: macOS Catalina 10.15

**Comment by AMBudnik** [comment]
Surprisingly, borders are correct

![Zrzut ekranu 2020-07-8 o 10 13 52](https://user-images.githubusercontent.com/10757813/86894763-d02e9d80-c103-11ea-982e-6b06ef92f1f7.png)

**Comment by aninde** [comment]
And if you check the first three columns in the contextMenu, they are correctly frozen.

**Comment by aninde** [comment]
This issue is fixed with `8.0.0-beta2-rev22` https://jsfiddle.net/aninde/ujymfk7b/
