### ISSUE TITLE
[8.0.0-beta2-rev18] Editor is shifted when we use fixedRowsBottom (double top border)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7087]
### Description

Editor is shifted when we use `fixedRowsBottom`. We get a double top border.

### Steps to reproduce

1. Edit cell `A6`

**Result**
![Zrzut ekranu 2020-07-8 o 10 26 12](https://user-images.githubusercontent.com/10757813/86895930-7c24b880-c105-11ea-93ca-23a31e5ed1f1.png)

**Expected result**
![Zrzut ekranu 2020-07-8 o 10 25 41](https://user-images.githubusercontent.com/10757813/86895921-77f89b00-c105-11ea-99f6-db0ab8131252.png)

### Demo

https://jsfiddle.net/gd8r0vs7/4/ 7.4.2 (works well)
https://jsfiddle.net/gd8r0vs7/3/ 8.0.0-beta2-rev17 (works well)
https://jsfiddle.net/gd8r0vs7/1/ 8.0.0-beta2-rev18 (**broken**)
https://jsfiddle.net/gd8r0vs7/2/ 8.0.0-beta2-rev19 (broken)

### Your environment
* Handsontable version: 8.0.0-beta2-rev18
* Browser Name and version: Crome 83
* Operating System: macOS Catalina

**Comment by budnix** [comment]
Should be fixed within https://github.com/handsontable/handsontable/pull/7084.

**Comment by AMBudnik** [comment]
True. Issue fixed after merging #7084 to `8.0.0-beta2-rev21` https://jsfiddle.net/c7zw5kgq/
