### ISSUE TITLE
[8.0.0-beta2-rev18] We cannot move the selection from a rowHeader to a colHeaders (and the opposite) using CMD/CTRL +SHIFT

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7089]
### Description

We cannot move the selection from a rowHeader to a colHeaders (and the opposite) using <kbd>CMD/CTRL</kbd> + <kbd>SHIFT</kbd>.

### Steps to reproduce

1. Keep holding <kbd>SHIFT</kbd> through all the steps
2. Click any rowHeader
3. Click any colHeader

**Result**
Nothing changes when you do step 3.

**Expected result**
Selection changes from rowHeader to a colHeader.

### Demo

https://jsfiddle.net/9o20dyub/ 7.4.2 (working)
https://jsfiddle.net/hw5t60m2/ 8.0.0-beta1 (working)
https://jsfiddle.net/hw5t60m2/1/ 8.0.0-beta2-rev1 (working)
https://jsfiddle.net/hw5t60m2/2/ 8.0.0-beta2-rev17 (last working)
https://jsfiddle.net/hw5t60m2/3/ 8.0.0-beta2-rev18 (**first broken**)
https://jsfiddle.net/pa1k7yog/2/ 8.0.0-beta2-rev20 (broken)

### Your environment
* Handsontable version: 8.0.0-beta2-rev18
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina

**Comment by wojciechczerniak** [comment]
I do not see this as a bug. Change in the behavior for sure.

But when you select a row, the only reasonable way to expand the selection with SHIFT is another row. I do not make sense to expand row selection to a column. SHIFT + click should do nothing in that case.

**Comment by jansiegel** [comment]
@AMBudnik @wojciechczerniak I believe there are to main issues here:
1. <kbd>SHIFT</kbd> + clicking on a row, then on a column
2. <kbd>CMD/CTRL</kbd> + clicking on a row, then on a column

The shift+cmd problem is a result of those two, I think. Either way, both of them should be probably fixed, right?

**Comment by aninde** [comment]
Looks like `rev22` solved this issue https://jsfiddle.net/aninde/5dbx8nL2/
![solved-ff78](https://user-images.githubusercontent.com/30186818/87168185-62829d00-c2ce-11ea-96d2-816bb9742f6f.gif)
