### ISSUE TITLE
"empty" not reported for afterChange and beforeChange events

### ISSUE THREAD

**Issue by josegrad** [handsontable/handsontable#709]
The documentation for the afterChange and beforeChange events claims that the source argument will carry one of the strings: "alter", "empty", "edit", "populateFromArray", "loadData", "autofill", "paste"

In which condition the "empty" is carried? In the next jsfiddle deleting the contents of a cell the source string contains "edit" not "empty".

http://jsfiddle.net/GwvNy/16/

I've tried OSX and Windows with same result.

**Comment by AMBudnik** [comment]
I reproduced it, you're right - it serves `edit` when deleting the content of the cell. We have to take a closer look at this issue.

**Comment by krzysztofspilka** [comment]
Actually, there should not be such action like "empty" as removing is an editorial action.

Fix: removed "empty" from the docs.

**Comment by AMBudnik** [comment]
Hi @josegrad 
we decided finally to do not use `empty` type of change so it will still appear as an `edit`.
Again thanks for sharing!
