### ISSUE TITLE
[7.1.1+] two handsontables with comments - destroying one table breaks comment editor in other table

### ISSUE THREAD

**Issue by dwntwnbrown** [handsontable/handsontable#7091]
### Description
When creating two handsontables with comments, when destroying one table impacts the other tables comment editor not allowing it to display (the comment indicators are still visible).

### Steps to reproduce

1. Create two handsontables with comments
2. Destroy one table
3. Comments editor no longer displays in the other table

### Demo

https://jsfiddle.net/davbro/9zmL02hb/5/

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: chrome 83.0.4103.97
* Operating System: macos mojave 10.14.6

**Comment by AMBudnik** [comment]
Thank you for sharing the description along with a demo. 

I've replicated the bug on 7.4.2 (provided) as well as in the 8.0.0-beta2-rev20 https://jsfiddle.net/ksod3xnj/.

**Comment by AMBudnik** [comment]
This behavior is a regression.
https://jsfiddle.net/jwrfgyh0/ 7.1.1 was the version to break this functionality.
https://jsfiddle.net/f2cto3am/ 7.1.0 working well.

**Comment by AMBudnik** [comment]
It works the same in v 8.0.0 https://jsfiddle.net/AMBudnik/t9r21amn/

**Comment by AMBudnik** [comment]
I'm glad to see this issue solved.

@dwntwnbrown please update to [v8.4.0](https://github.com/handsontable/handsontable/issues/7998) and let me know if it works for you as well.
