### ISSUE TITLE
AfterCreateRow does not let me call validateRows.

### ISSUE THREAD

**Issue by gigilucena** [handsontable/handsontable#7092]
### Steps to reproduce

1. Create a new row 
2. try to add validateRows in afterCreateRow.
3. It will not validate

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @gigilucena 

I've tried this approach (`numeric` data with one invalid value) https://jsfiddle.net/spk47u0m/ and the `afterValidate` hook is called but the invalid cell does not turn red.

#### Version check
Unfortunately, this issue remains the same in `8.0.0-beta2-rev20` https://jsfiddle.net/zua8jhk6/

#### Investigation result
Possibly, It happens this way as the `afterCreateRow` hook runs before the `afterValidate` hook. If I use the `setTimeout()` function to delay the `validateCells()` method it works as expected https://jsfiddle.net/zua8jhk6/1/

**Comment by gigilucena** [comment]
Thank you for the quick response. I used setTimeout like you mention above and it is working.

**Comment by AMBudnik** [comment]
Great. I'll let you know @gigilucena once we fix this issue officially

**Comment by AMBudnik** [comment]
Hi @gigilucena 

Can you help me here? It seems that this issue is no longer replicable.
I tested it here https://jsfiddle.net/01kwb4o8/ using the latest Chrome. It also seems to be solved for the old version.

**Comment by gigilucena** [comment]
Hello! Yes it is fixed. Thank u!Sent from my iPhoneOn Jan 19, 2023, at 1:30 AM, Aleksandra Budnik ***@***.***> wrote:﻿
Hi @gigilucena
Can you help me here? It seems that this issue is no longer replicable.
I tested it here https://jsfiddle.net/01kwb4o8/ using the latest Chrome. It also seems to be solved for the old version.

**Comment by AMBudnik** [comment]
Thank you very much for the confirmation. I'm closing this issue as solved.
