### ISSUE TITLE
3

### ISSUE THREAD

**Issue by zhanglongyue** [handsontable/handsontable#7093]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
@zhanglongyue please fill the description.

**Comment by AMBudnik** [comment]
I guess that this issue was created by an accident If not, feel free to contact me on support@handsontable.com or create a new issue with a full description.

**Comment by zhanglongyue** [comment]
Sorry, it was an accident
