### ISSUE TITLE
Pasting over a column does not respect empty cells

### ISSUE THREAD

**Issue by josegrad** [handsontable/handsontable#710]
#### Short version

Pasting vertically (over a column) the empty cells are not respected - unless they are all empty.

#### Long version

Asume you have this column in excel:

```javascript
empty cell
22
empty cell
empty cell
```

If you copy and paste the 4 cells into the table available in http://handsontable.com/ you can see that in the table all 4 rows take the value of the second row. The empty cells are not respected and the result is:

```javascript
22
22
22
22
```

If you have a row like this:   
```javascript
 empty cell | 22 | empty cell | empty cell
```
Then the pasted result is correct and all empty cells are respected.

If you copy/paste several rows and colums all cell contents are respected also.

So apparently when pasting vertically (over a column) the empty cells are not respected - unless they are all empty.

Bug or feature? I would expect empty cells to be respected...

**Comment by AMBudnik** [comment]
Please try the same [demo](http://handsontable.com/) empty cells are copied as empty.
