### ISSUE TITLE
[7.1.1+] Changing checkbox state while using autoRowSize: true with multi-level data causes row misalignment

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7102]
### Description

Changing checkbox state while using `autoRowSize: true` with multi-level data causes row misalignment.

### Steps to reproduce

1. Change the last checkbox in column `A` from `false` to `true`

![issue](https://user-images.githubusercontent.com/10757813/87127172-c89b0000-c28d-11ea-83d3-13842ed900cc.gif)

### Demo

https://jsfiddle.net/vd3t7eL8/3/ `7.0.0` (working)
https://jsfiddle.net/vd3t7eL8/2/ `7.1.1` (**first of broken**)
https://jsfiddle.net/vd3t7eL8/ `7.4.2` (broken)
https://jsfiddle.net/vd3t7eL8/1/ `8.0.0.-beta2-rev21` (still broken)
https://jsfiddle.net/AMBudnik/26t5exfd/ 8.0.0 stable (still broken)

### Your environment
* Handsontable version: 7.1.1+
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina

Inform [forum](https://forum.handsontable.com/t/gh-7102-sticky-columns-moving-with-checkbox-selection/4529)

**Comment by wszymanski** [comment]
It seems that bug isn't related to `disableVisualSelection` option. @AMBudnik could you confirm it?

**Comment by AMBudnik** [comment]
@wszymanski good catch! Here is a new demo https://jsfiddle.net/handsoncode/qnfz940d/ 
I removed `colHeaders` and `disableVisualSelection` as those aren't needed to replicate the issue.


Tested using Chrome 87/Windows 10.

**Comment by AMBudnik** [comment]
Thank you guys, it looks great.

For everyone interested in the latest patch that solved the issue here https://handsontable.com/docs/release-notes/ is the full list of changes.
