### ISSUE TITLE
Additional, native for macOS editor selection in Firefox 78 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7103]
### Description
Version `78` of `Firefox` introduces to the Handsontable editor the native selection of the active element so far only known from `Safari` and `iOS browsers.`

This is an additional selection used in macOS systems for the active element.
Highlight border in `Firefox` is thicker than in `Safari`.

An additional selection does not appear in `Edge`, `Chrome`, and `Opera` on `macOS`, so it's inconsistent.

The colour of that highlight can be changed in System Preferences/General.

`Firefox 78`
![image](https://user-images.githubusercontent.com/30186818/87132539-4ebb4480-c296-11ea-992a-87493c3350f6.png)  ![image](https://user-images.githubusercontent.com/30186818/87132628-714d5d80-c296-11ea-9846-0a48959b6dbf.png)

 `Safari 13`
 ![image](https://user-images.githubusercontent.com/30186818/87132576-609ce780-c296-11ea-905a-28c220484fe3.png)  ![image](https://user-images.githubusercontent.com/30186818/87132610-6b577c80-c296-11ea-8b1b-ac4620a5626f.png)

### Steps to reproduce

1. Open editor at https://jsfiddle.net/aninde/knh9rw7z/ on Firefox 78 or Safari on macOS.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: not related
* Browser Name and version: Firefox 78, Safari
* Operating System: macOS Catalina 10.15.5

**Comment by aninde** [comment]
Related to https://github.com/handsontable/handsontable/issues/6955

**Comment by aninde** [comment]
It's fixed with `pre-8.0.0` https://jsfiddle.net/aninde/c0awdm89/. There is no additional border on `Firefox 78.0.2` anymore.
I have added this for https://github.com/handsontable/handsontable/issues/6465. CC: @scarletfog

**Comment by AMBudnik** [comment]
I'm glad to see this fixed in 8.0.0.

**Release Notes** https://github.com/handsontable/handsontable/releases

**CDN** https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
**NPM** npm i handsontable
