### ISSUE TITLE
[8.0.0-beta.2] some e2e tests not pass in some browsers

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7110]
### Description
Some e2e test does not pass in the browsers.

### macOS Catalina 10.15.5, Retina 15-inch
focus on a browser with a maximized window, visible scrollbars

#### Chrome 83.0.4103.116
  does not pass on my smaller (Retina 13-inch) macOS with the same settings.
1. **NestedRows > Cooperation with the `ManualRowMove` plugin > should move single row between parents properly (moving from the bottom to the top)
Expected ‘Alabama Shakes’ to equal ‘Ghost’.
Expected $[0] = 2 to equal 1.
Expected $[2] = 2 to equal 1.**

#### Firefox 78.0.2
1.	Comments > Styling > should display the comment editor in the correct place Expected $.top = 356 to equal 355.75.
2.	Comments > hidden row an column integration > should display the comment editor in the correct place, when the active cell is past hidden rows/columns Expected $.top = 356 to equal 355.75.
3.	HiddenRows > AutoRowSize > should return proper values from the `getRowHeight` function (when indicator is enabled) Expected 43 to be 23.
4.	HiddenRows > AutoRowSize > should return proper values from the `getRowHeight` function (when indicator is disabled) Expected 43 to be 23.
5.	HiddenRows > manualRowMove > UI > backlight > should get correct position and size while grabing the row placed after hidden rows Expected 569.25 to be 616.25.
6.	HiddenRows > manualRowMove > UI > backlight > should get correct position and size while grabing the multiple rows placed after hidden rows Expected 569.25 to be 616.25.
7.	HiddenRows > manualRowMove > UI > backlight > should get correct position and size while grabing the row placed before hidden rows Expected 569.25 to be 616.25.
8.	HiddenRows > manualRowMove > UI > backlight > should get correct position and size while grabing the multiple rows placed before hidden rows Expected 569.25 to be 616.25.
9.	manualColumnResize > should resize appropriate columns to calculated autoColumnSize width after double click on column handler after updateSettings usage with new `colWidths` values Expected 88 to be 89.
10.	**NestedRows > Cooperation with the `ManualRowMove` plugin > should move single row between parents properly (moving from the bottom to the top) Expected 'Alabama Shakes' to equal 'Ghost'.
 Expected $[0] = 2 to equal 1. Expected $[2] = 2 to equal 1.**

#### Safari 13.1.1 (15609.2.9.1.2)
1. HiddenRows > AutoRowSize > should return proper values from the `getRowHeight` function (when indicator is enabled) Expected 43 to be 23.
2. HiddenRows > AutoRowSize > should return proper values from the `getRowHeight` function (when indicator is disabled) Expected 43 to be 23.
3.  manualColumnResize > should resize appropriate columns to calculated autoColumnSize width after double click on column handler after updateSettings usage with new `colWidths` values Expected 88 to be 89.
4. MultiColumnSorting > Numbers presenting sorting sequence > should be properly hided when just one column is sorted Expected '' to equal 'none'.
5. Filters UI > should inherit font family and size from body
Expected '16.799999237060547px' to be '16.8px'. 

Two last one from Safari are already reported here https://github.com/handsontable/handsontable/issues/6602

#### Microsoft Edge Version 80.0.361.50
1. **NestedRows > Cooperation with the `ManualRowMove` plugin > should move single row between parents properly (moving from the bottom to the top)
Expected ‘Alabama Shakes’ to equal ‘Ghost’.
Expected $[0] = 2 to equal 1.
Expected $[2] = 2 to equal 1.**

#### Opera Version 68.0.3618.173
1. **NestedRows > Cooperation with the `ManualRowMove` plugin > should move single row between parents properly (moving from the bottom to the top)
Expected ‘Alabama Shakes’ to equal ‘Ghost’.
Expected $[0] = 2 to equal 1.
Expected $[2] = 2 to equal 1.**

### Your environment
* Handsontable version: 8.0.0-beta.2
* Browser Name and version: Chrome 83, Firefox 78, Safari 13
* Operating System: macOS Catalina

**Comment by wojciechczerniak** [comment]
Fixed in #7121
