### ISSUE TITLE
[8.0.0-beta.2] Removing all rows or all columns when data is set for nestedRows

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7116]
### Description
We can not remove all columns from the context menu opened anywhere when we have data set with nested childers as in the demo for nestedRows.
Related to https://github.com/handsontable/handsontable/issues/7117

**Actual result:**
**8.0.0-beta2**
![Screenshot 2020-07-13 at 16 04 48](https://user-images.githubusercontent.com/30186818/87314266-43c91400-c523-11ea-9081-788a5b8a0aba.png) ![Screenshot 2020-07-13 at 16 12 23](https://user-images.githubusercontent.com/30186818/87315134-60b21700-c524-11ea-939b-772f81ded71a.png)

**FF**
![Screenshot 2020-07-13 at 16 48 56](https://user-images.githubusercontent.com/30186818/87318613-dfa94e80-c528-11ea-8bdd-6bfff53bcf08.png)

**Chrome**
![Screenshot 2020-07-13 at 16 50 42](https://user-images.githubusercontent.com/30186818/87318720-049dc180-c529-11ea-8c9c-7b35aecc4d59.png)

**Expected result:**
No error in the console if we are to have this option. 

### Steps to reproduce

1. `Remove columns` from the corner in contexMenu 
 or
2. Select all cells by CMD + A and opening at any cell contextMenu and click `Remove columns`

### Demo

https://jsfiddle.net/aninde/hyt9qa86/ - full.js `8.0.0-beta2` and `8.0.0-beta2-rev22` (broken)
https://jsfiddle.net/aninde/n3h6aLxy/ - min.js `8.0.0-beta2` and `8.0.0-beta2-rev22` (broken)
https://jsfiddle.net/aninde/1rq6w5eb/ - `8.0.0-beta-rev21` (can not be reproduced)
https://jsfiddle.net/aninde/e1r9gwxd/ - `7.4.2` (can not be reproduced)

### Your environment
* Handsontable version: 8.0.0-beta2
* Browser Name and version: Firefox 78, Chrome 83
* Operating System: macOS Catalina 10.15.5

**Comment by wojciechczerniak** [comment]
The error says it all. It's not possible to remove columns when `data` source is an array of objects or `columns` option is specified. @budnix should we check `isColumnModificationAllowed`?

**Comment by budnix** [comment]
> @budnix should we check `isColumnModificationAllowed`?

True https://github.com/handsontable/handsontable/pull/7125/files#diff-980a6b6b86286fede5e66557f5e50d91.

**Comment by aninde** [comment]
This issue is solved by`pre-8.0.0-rev1`https://jsfiddle.net/aninde/u8hf3xw0/. Behaviour from version 7 has been restored. there is no option to delete columns.

**Comment by aninde** [comment]
I am closing it as a regression on version 8.0.0-beta.2. Cannot be reproduced on the stable 7+ version.
