### ISSUE TITLE
[8.0.0-beta.2] Ability to delete column when data is set for nestedRows

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7117]
### Description
Related to https://github.com/handsontable/handsontable/issues/7116
As the title said in `8.0.0-beta2`we have the ability to delete column when data is set for nestedRows from `contextMenu`. `dropdownMenu` doesn't have this option.

![image](https://user-images.githubusercontent.com/30186818/87316735-6f99c900-c526-11ea-9612-a78a01e33fee.png)
![image](https://user-images.githubusercontent.com/30186818/87316749-7294b980-c526-11ea-9076-fd399f23c37a.png)

In `7.4.2` we aren't able to remove any columns.  In `beta-2`, this option is available in the menu and causes errors. Maybe it should be grey and inactive? 
![Screenshot 2020-07-13 at 16 21 21](https://user-images.githubusercontent.com/30186818/87315892-488ec780-c525-11ea-99dc-1b70bcd826a1.png)

We didn't have this option in 7+, this is not consistent and causes errors reported in https://github.com/handsontable/handsontable/issues/7116.

### Steps to reproduce

`Remove columns` from the corner in contexMenu
 or
Select all cells by CMD + A and open at any cell contextMenu and click `Remove columns`

### Demo

https://jsfiddle.net/aninde/wkpv8f3y/ - `7.4.2`
https://jsfiddle.net/aninde/n3h6aLxy/ - `8.0.0-beta2` and `8.0.0-beta2-rev22` (broken)
https://jsfiddle.net/aninde/1rq6w5eb/ - `8.0.0-beta-rev21` (can not be reproduced)

### Your environment
* Handsontable version: 8.0.0-beta2
* Browser Name and version: Firefox 78, Chrome 83
* Operating System: macOS Cataina 10.15.5

**Comment by wojciechczerniak** [comment]
Same as https://github.com/handsontable/handsontable/issues/7116#issuecomment-657653826

**Comment by budnix** [comment]
The issue will be fixed by https://github.com/handsontable/handsontable/pull/7125.

**Comment by aninde** [comment]
This issue is solved bypre-8.0.0-rev1https://jsfiddle.net/aninde/u8hf3xw0/. Behavior from version 7 has been restored. There is no option to delete columns.
<img width="268" alt="Screenshot 2020-07-16 at 16 07 18" src="https://user-images.githubusercontent.com/30186818/87681721-41fb8c80-c77f-11ea-9983-ca6e9a3f6449.png"> <img width="333" alt="Screenshot 2020-07-16 at 16 07 33" src="https://user-images.githubusercontent.com/30186818/87681725-432cb980-c77f-11ea-8a55-8b6eecbd9089.png">

**Comment by aninde** [comment]
I am closing it as a regression on version `8.0.0-beta.2`. Cannot be reproduced on the stable `7+` version.
