### ISSUE TITLE
Set renderer and format in cellProperties

### ISSUE THREAD

**Issue by kapocris** [handsontable/handsontable#713]
Hello, apparently is not possible to set a custom format and render function at the same time. Please, have a look at my code: 

Format works but the renderer function is never called.

``` javascript
cells: function (r, c, prop) {
                //Here we can change every single cell's properties.
                var cellProperties = {}
                cellProperties = {
                    readOnly: _viewModel.readOnly,                    
                    type: 'numeric', 
                    renderer: typeof (changesObj['row' + r]) != 'undefined' && typeof (changesObj['row' + r]['col' + prop]) != 'undefined' ?
                            editableUpdatedCellRenderer : editableCellRenderer
                    ,
                    format: _viewModel.inputMode == Forecasts.InputModes[0] ? '0' : '0.00'
                }
                return cellProperties
            },
```

Thanks

**Comment by BOZii** [comment]
Implemented the above solution for changing formatting dynamically, in my case, after a ddl type is selected it changes the adjacent cell to proper format (ie. "Number" -> 0.00 , "Money" -> $0.00). My problem is that that it changes the formatting for the entire column, is there a way to change the format of just a single cell? without setting a custom renderer that checks the value and changes it based on regex. Thanks
