### ISSUE TITLE
Highlight gets wrongly position if header height is too much

### ISSUE THREAD

**Issue by underfisk** [handsontable/handsontable#7130]
### Description

If you set a big height on the headers, it will make the highlight to appear likely behind the header (this example on the first cell) but there are cases where the positioning is "cut" or just placed a little above

### Steps to reproduce

1. Create a custom header renderer and set it's height to be big 
2.Create a couple of rows to test
3. Open an editor or select the cell

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
@underfisk Please share a demo. The demo attached does not have the mentioned logic.

**Comment by underfisk** [comment]
@AMBudnik The demo is the default one but its hard to replicate our custom wrapper, i have managed to fix the issue but i would like to know why it happens and if it's known.
Also, i noticed Handsontable usually sets the first column height to the max height available but what if i want to give an height to the column? I can mislead

**Comment by AMBudnik** [comment]
@underfisk without a demo or at least a video with a reproduction I won't be able to specify the nature of the bug. Here's an example that adds extra height to a header via `afterGetColHeader` and it works as expected https://jsfiddle.net/t72k6zqd/2/

![afterGetColHeader](https://user-images.githubusercontent.com/10757813/87671795-3ce41080-c772-11ea-8b93-c7a7f0048ac2.gif)

**Comment by underfisk** [comment]
@AMBudnik I tried that like you did in there but our custom wrapper has more complex components and that's why its hard to replicate (our enterprise code cannot be shared)
I just opened this issue so you guys could investigate/review because right now I have managed to fix the issue, i'm not so sure how the glitch happened but it did, i also had contacted the support and sent a Demo, the only replied i had was that we were missing a placeholder class when the editor (popover) is open but the real issue was related to the height of our columns

**Comment by AMBudnik** [comment]
> our enterprise code cannot be shared

Understandable. However, can you load false data and record the behavior? 

> the real issue was related to the height of our columns

That is already a trace, but it is not enough for us to start an investigation. Can you share how do you manage to make the 
- afterGetColHeader
- colHeaders
- CSS
- columnHeaderHeight
- using HTML

**Comment by underfisk** [comment]
We only use afterGetColHeader and onCells to modify

**Comment by AMBudnik** [comment]
> onCells

do you mean this https://handsontable.com/docs/7.4.2/Options.html#cells ?

**Comment by underfisk** [comment]
@AMBudnik Yes, some properties are given there but most of our custom cell renderer are something like this
```ts
renderer: (_, TD) => {
 TD.innerHTML = ""
  const div = document.createElement("div")
  ReactDOM.render(OurDynamicCellRenderer..., div)
  TD.appendChild(div)
 return TD
}
```
This is a simple example but the only problem doing that is that when Handsontable unmounts the cell, react component has no knowledge of it and then some binds still live and that's really an issue (virtual dom is kinda useless using Handsontable with React, that's what i also mentioned on React-wrapper, to handle this things)
Also we do the same with afterGetColHeaders, usually we either bind only some styling or simply render the whole

**Comment by AMBudnik** [comment]
Hi @underfisk 

I was not able to replicate the issue. I've tried macOS Catalina 10.15.3 and Windows 10. 
Until you will be able to share a demo where the issue can be replicable I will keep this topic closed.
