### ISSUE TITLE
[8.0.0-beta.2/8.0.0-rev1] Moving collapsed nestedRow causes error

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7132]
### Description
In a specific case when we try to move collapsed nestedRows (parent row) browser's console throws an error.
This error should be handled in `v8.0.0-beta.2` It's thrown in both options: move up and move down

In version 8.0.0-beta.1 and versions 7+, nothing happens when I try to reproduce this bug - there is no bug, and there is no shift. 

### Steps to reproduce

**Case 1**
1. Open demo, collapse all parents rows.
2. Try move upward any row from.

**Case 2**
1. Collapse first parent row.
2. Double-click on the second uncollapsed row.

The result is the same.

`pre-8.0.0-rev1`
`8.0.0-beta.2`
![bug-beta2](https://user-images.githubusercontent.com/30186818/87676383-d7dfe900-c778-11ea-8020-1ce7c87954f8.gif)

`8.0.0-beta.1` and `7.4.2`
![8 0 0-beta 1-nestedR-ff78](https://user-images.githubusercontent.com/30186818/87674251-0ad4ad80-c776-11ea-8da8-764c55c7e641.gif)

### Demo

https://jsfiddle.net/aninde/tfcuazqr/ - `7.4.2` (solved)
https://jsfiddle.net/aninde/two5v2zr/ - `8.0.0-beta.1` (solved)
https://jsfiddle.net/aninde/ktzy0a94/ - `8.0.0-beta.2` (broken)
https://jsfiddle.net/aninde/w6cahfo9/ - latest `pre-8.0.0-rev1` (broken)

### Your environment
* Handsontable version: 8.0.0-beta.2 and pre-8.0.0-rev1
* Browser Name and version: Firefox 78, Edge 83
* Operating System: macOS Catalina 10.15.5, Windows 10

**Comment by AMBudnik** [comment]
Demo updated to v8.0.0 https://jsfiddle.net/AMBudnik/9vwn5dgx/ shows the same issue.

**Comment by aninde** [comment]
Both cases of this issue will be fixed by `v8.1.0`. https://jsfiddle.net/aninde/w4n8yt7c/

**Case 1**

![fiexd-7132](https://user-images.githubusercontent.com/30186818/94444423-99b66b00-01a6-11eb-9ceb-15f16367306b.gif)
**Case2**

![fixed-case2](https://user-images.githubusercontent.com/30186818/94444431-9ae79800-01a6-11eb-9a68-8fa5d8b4e0e3.gif)

**Comment by AMBudnik** [comment]
Issue closed as solved for Handsontable 8.1.0
