### ISSUE TITLE
'Insert row above' while using nestedRows produces Uncaught error when we use it for a first child [Urgent]

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7137]
### Description

'Insert row above' while using `nestedRows` produces Uncaught error when we use it for a first child.

We have fixed the behavior of using 'Insert row above' but it apparently did not cover this case. If you try to use this option on any other element (parent, nth-child) it works as expected.

### Steps to reproduce

1. Use 'Insert row above' on the `Alabama Shakes` (2nd row)

**Result**
The row is not added and you get the console error.
![Zrzut ekranu 2020-07-17 o 12 14 44](https://user-images.githubusercontent.com/10757813/87775891-1df38600-c827-11ea-8f1c-1303a2c30cfa.png)

### Demo

https://jsfiddle.net/zo1jhx49/ 7.4.2 (broken)
https://jsfiddle.net/vf4nxou7/ 8.0.0-beta1 (broken)
https://jsfiddle.net/mpdw5t78/ 8.0.0-beta2-rev22 (broken)
https://jsfiddle.net/0bfsrLqp/4/ 8.0.0-rev1 (broken)
https://jsfiddle.net/AMBudnik/08vwazpf/ 8.0.0 (broken)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina 10.15.3

_Inform Zen 26480_

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **NestedRows grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7510

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by aninde** [comment]
This issue will be fixed by v.10 http://jsfiddle.net/fq34grd6/.

**Comment by AMBudnik** [comment]
Thank you for fixing it. I also did not replicate the issue using v10.
