### ISSUE TITLE
After selecting the top-left element the row range resizing is not possible

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7139]
### Description

After selecting the top-left element the row range resizing is not possible. We only resize a single column.

### Steps to reproduce

1. Click top-left element
2. Click row header 1
3. Hold SHIFT and click row header 10
4. Resize the last row

**Result**
One row expands
![bug](https://user-images.githubusercontent.com/10757813/87789950-1db3b480-c840-11ea-8554-5a959808f88a.gif)

**Expected result** (google sheets)
All rows expand
![gs](https://user-images.githubusercontent.com/10757813/87790561-05906500-c841-11ea-8e7e-1b3d93ace69b.gif)

### Demo

https://jsfiddle.net/s3xjd6zv/ 8.0.0-rev1 (broken)
https://jsfiddle.net/s3xjd6zv/1/ 8.0.0-beta2-rev22 (broken)
https://jsfiddle.net/s3xjd6zv/2/ 8.0.0-beta2-rev18 (broken)
https://jsfiddle.net/s3xjd6zv/3/ 8.0.0-beta2-rev1 (broken)
https://jsfiddle.net/s3xjd6zv/4/ 8.0.0-beta1 (broken)
https://jsfiddle.net/s3xjd6zv/5/ 7.4.2 (broken)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina 10.15.3

**Comment by bud-e** [comment]
Hi @AMBudnik ,

The above PR fixes the current issue and added the support for non-contiguous selected rows.
So, Now with the above changes user can change the height of selected rows which are non-contiguous (selected using **ctrl** key)

Thanks.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8414798/89123504-7357b480-d502-11ea-9a9a-c2048b7a73dc.gif)

**Comment by AMBudnik** [comment]
Looks great! Thank you for sharing @bud-e

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/y6xcr3dv/

**Comment by aninde** [comment]
This issue will be fixed by `v8.1.0` for both columns and rows.
https://jsfiddle.net/aninde/rL1wmbz4/ `v8.1.0`

![7139-fixed-ff](https://user-images.githubusercontent.com/30186818/94427400-4edd2900-018f-11eb-97d2-059feaed7a3e.gif)

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/pull/7162 as done.
