### ISSUE TITLE
Very slow horizontal scroll on large number of columns in 0.9.1

### ISSUE THREAD

**Issue by mtasic85** [handsontable/handsontable#714]
There is an issue with performance when number of columns is greater then 50. I'm testing on ArchLinux x86_64 and Chromium  27.0.1453.93.

Here is test case: http://jsfiddle.net/LkJ38/10/.
I've reused that code form someone else, and increased number of columns.

**Comment by krzysztofspilka** [comment]
We changed the way columns are drawed in v.0.12.0. They are now rendered dynamically, you can specify how many rows need to be loaded before and after the viewport. This should fix the performance issue connected with large amount of columns displayed with Handsontable.

https://github.com/handsontable/handsontable/releases/tag/0.12.0
