### ISSUE TITLE
Editorial in documentation

### ISSUE THREAD

**Issue by kkayal** [handsontable/handsontable#7141]
The documentation at

https://handsontable.com/docs/7.4.2/tutorial-cell-editor.html

says "This method does need to return any value" in the explanation of the three methods open(), close() and focus(). It seems it should say the opposite, that these methods do not need to return any value.

**Comment by pnowak** [comment]
Hi @kkayal 

Thank you, you right.  

I move this issue to our docs repo - https://github.com/handsontable/docs/issues/121 - and close this issue.

Thank you again.
