### ISSUE TITLE
Filters - Filter dropdown is rendered inside body tag relative to body tag

### ISSUE THREAD

**Issue by HarithaKR** [handsontable/handsontable#7143]
If I click on filter button, filter dropdown is rendered inside the body tag and its positioned relative to body tag. Instead, is there an option to customize the target element where the filter dropdown should be rendered?

* Handsontable version: 3.0.0
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by pnowak** [comment]
Hi @HarithaKR 

We introduced this feature in 7.3.0 version. You can read about this in our release notes - https://handsontable.com/docs/7.4.2/tutorial-release-notes.html
So you have to update your Handsontable version.

Here is a demo - https://jsfiddle.net/ka5ub68q/
It works for `contextMenu` as well as `dropdwonMenu`.

**Comment by HarithaKR** [comment]
could you provide a demo with dropdownMenu rendered in custom target?
The position of the dropdown is not correct. If I provide a target for dropdownMenu, it is displaying some additional contents in the dropdown (Context menu items) and the dropdown is positioned far from the column

**Comment by HarithaKR** [comment]
For contextMenu, this options seems working in jquery application. 
https://jsfiddle.net/ka5ub68q/
I tried the same in react application for dropdownMenu. It is rendering dropdown menu items along with contextMenu items and the position of dropdown menu is far away from the column. Some times its beyond the viewport. 
Is width and height mandatory for the custom container?
Please assist on this.

**Comment by HarithaKR** [comment]
![image](https://user-images.githubusercontent.com/23190851/88155675-03098300-cc26-11ea-8bd5-e5763ef09941.png)
![image](https://user-images.githubusercontent.com/23190851/88155713-11f03580-cc26-11ea-9c7d-1ad9894368fe.png)
Please check these images

**Comment by wojciechczerniak** [comment]
Screenshots are unfortunately not enough to debug this issue. There might be multiple reasons why the position is calculated incorrectly. `iframe`, absolutely or relatively positioned parents, transforms, flexbox, grid, other CSS properties. Can you trace your styles for the properties that are responsible for the wrong position and recreate the scenario in jsfiddle?

**Comment by AMBudnik** [comment]
Hi @HarithaKR 

if you do not want to share your code on Github I propose to send it to our Support Team (support@handsontable.com). I will do my best to help you solve this issue.
