### ISSUE TITLE
[8.0.0] Double border on colheaders after undoing removal when we set fixed columns and formulas

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7146]
### Description
Undoing removal of rows from the context menu makes bottom colHeaders border doubled in a specific situation when, we set:
- columns option
- formulas
- fixedRowsBottom
- rowHeaders and colHeaders (as we using corner (top-left element))

![on-rows](https://user-images.githubusercontent.com/30186818/88187273-9cd92c00-cc36-11ea-910f-c57c3d755613.gif)

### Steps to reproduce

* Click RMB on the corner and remove rows by `contextMenu`
* Undo.
   or
* Select all rowHeaders
* Click RMB and remove rows by `contextMenu`. In the `v7.4.2` undo from `contextMenu`.

**Case 1**
**Columns as a function**
https://jsfiddle.net/aninde/xz6rwpLy/ 
**Case 2**
https://jsfiddle.net/aninde/tLnfybq1/ 

### Demo

https://jsfiddle.net/aninde/xz6rwpLy/  `pre-8.0.0-rev1` (broken)
https://jsfiddle.net/aninde/tLnfybq1/  `pre-8.0.0-rev1` (broken)
https://jsfiddle.net/aninde/ybn945u3/ `v.8.0.0-beta.2` (fixed)
https://jsfiddle.net/aninde/3r2bq9vs/ `v.8.0.0-beta.1` (fixed)
https://jsfiddle.net/aninde/b6c9y30q/ `v.7.4.2` (fixed)  

### Your environment
* Handsontable version: pre-8.0.0-rev1
* Browser Name and version: Firefox 78, Chrome 83
* Operating System: macOS Catalina 10.15.6

**Comment by wszymanski** [comment]
It seems that: https://github.com/handsontable/handsontable/pull/7109 has broken it. Looking through [the history of `develop`](https://github.com/handsontable/handsontable/commits/develop) commit 7e15af798aad2cc583c2eec148690515b3281c3c works, but 3075b4371ea9acbf731a2371b30e4ae7d1925ac8 doesn't. Thanks @jansiegel 🥇

**Comment by wojciechczerniak** [comment]
Fixed in #7152
