### ISSUE TITLE
How would you get the current cell indices upon selection in React.js?

### ISSUE THREAD

**Issue by emanuallan** [handsontable/handsontable#7148]
I know you are able to access the data by using the data variable, but how do I get the cell (row and column) that a user is presently editing or writing into?

**Comment by emanuallan** [comment]
So the moment they begin editting it, we have the row and column index of where their editting is taking place on the table?

**Comment by emanuallan** [comment]
or perhaps a row and index of the cell they just finished editing?

**Comment by pnowak** [comment]
Hi @emanuallan 

You could use `afterSelection` hook - https://handsontable.com/docs/7.4.2/Hooks.html#event:afterSelection
Here is a demo - https://jsfiddle.net/wqtk853o/

Let me know if it follows your idea.

**Comment by emanuallan** [comment]
Hey @pnowak , THANKS FOR YOUR HELP! afterSetDataAtCell also helped too. I appreciate the documentation and the demo too!
