### ISSUE TITLE
Dynamic Data Source from Model in C# for Nested Rows

### ISSUE THREAD

**Issue by div1505209** [handsontable/handsontable#7153]
### Description

I want to know the structure of Model created in C#  .NET framework ( MVC ) which will be suitable to feed in a handsontable instance with **Nested Rows**.

### Steps to reproduce

1. Just create a sample Model with data in C# .NET framework ( MVC ) and load it to Handsontable's Instance with Nested Rows.

### Your environment
* Handsontable version: 7.3.0 
* Browser Name and version: Chrome Version 84.0.4147.105 (Official Build) (64-bit)
* Operating System: Windows 10 Enterprise

**Comment by pnowak** [comment]
Hi @div1505209 

Can you prepare a demo where we can reproduce the issue? 
Please describe all the steps to do so.

**Comment by AMBudnik** [comment]
Hi @div1505209 

We do not have any official code samples for C# .NET, however, this demo https://jsfiddle.net/AMBudnik/04h15qmd/1/ should give you some overall idea on nestedRows generators. Basically, it is a matter of correct object nesting.

If you'd like to discuss this demo or exchange some ideas feel free to send me a message (support@handsontable.com) as we try to keep GH for issue reporting.
