### ISSUE TITLE
Allow moving column headers with the column data.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#7156]
### Description
For example, we have **A, B, C, D, E, F** as our column headers. If we drag column E one step backwards, the expected column positioning should be **A, B, C, E, D, F**. 
Currently, only the data of column E was moved, but the position remained still: **A, B, C, D, E, F**.

`inform Forum #4586`

**Comment by wojciechczerniak** [comment]
If you define column headers `colHeaders: ['A', 'B', 'C', 'D', 'E']` they will be moved with data: https://jsfiddle.net/s87jadmu/

If you enable automatic column headers `colHeaders: true` they will be always auto generated in an arbitrary order. 

Works as expected.

**Comment by AMBudnik** [comment]
True. Forum ticket updated.
