### ISSUE TITLE
Deleting a sorted row causes its styling to be applied to an unrelated row.

### ISSUE THREAD

**Issue by harishtella** [handsontable/handsontable#7158]
### Description
Deleting a row using .alter, after the row has been sorted causes its styling to be applied to an unrelated other row. 

NOTE: It could be that the row is related in the sense that it's the first row in the original dataset order that did not have a special attribute as true--which styles the row. See the js-fiddle for this example.

### Steps to reproduce
1. Open the js fiddle and run it.
2. Sort the table by age.
3. Click the button to delete the first (now blue) row.
4. An unrelated row in the table suddenly becomes blue, even though it does not have a `true` value for it's special attribute.

### Demo
https://jsfiddle.net/x7jLm8so/7/

### Your environment
* Handsontable version: 7.4.2 
* Browser Name and version: Chrome Version 84.0.4147.89
* Operating System: OSX 10.13.6

**Comment by pnowak** [comment]
Hi @harishtella 

Thank you for reporting.
We need some time to thoroughly investigate your problem.

I'll be in touch soon.

**Comment by harishtella** [comment]
Sounds good @pnowak, thank you.

**Comment by pnowak** [comment]
This is an interesting case @harishtella  
Even if I changed the Handsontable version to 8.0.0 and used to visual helpers - https://jsfiddle.net/cn0fmvbj/ - the issue still occurs.

The main issue seems related to that cells are triggered too early and doesn't trigger after meta modification.

**Comment by pnowak** [comment]
Fortunate this issue has a solution.

The issue arises from the fact that we need to clean up classes before adding them to the next rendering cycle. Otherwise,
sooner or later, all cells will have that class. 
Here is an updated demo - https://jsfiddle.net/71vLo24t/

Another solution is slightly different. It based on the fact that `cells` always return new cell properties and clears everything. 
Here is a demo with this approach - https://jsfiddle.net/s2kzx3dy/

Since we have a solution I delete the label: Bug.

Does it meet your goal?

**Comment by harishtella** [comment]
Yes this meets my needs @pnowak. Thank you very much!

One thing I noticed that seems to be fixed in Handsontable 8.0 is that the cells function called with the physical row and col indices.

Where as in Handsontable 7.4, it looks like cells is called with the visual indices even though the docs say it is call with physical indices. https://handsontable.com/docs/7.4.2/Options.html#cells

See the comments in this js-fiddle to see a specific example.
https://jsfiddle.net/axcfpq7w/1/

Perhaps I should create a separate issue for this?

**Comment by AMBudnik** [comment]
Hi @harishtella 

@pnowak is ooo so I allowed myself to continue the topic. 
Below I used 2 bases example to compare v 7.4.2 and v 8.0.0. (frozen branch) and they both work the same with the initial column sorting.

8.0.0 - https://jsfiddle.net/4jqzvds3/
7.4.2 - https://jsfiddle.net/69xr2udp/3/

Result for attaching `readOnly` state to a cell coordinates `0, 0` with descending order of sorting for column `C`.

![Zrzut ekranu 2020-08-4 o 12 13 58](https://user-images.githubusercontent.com/10757813/89282580-09e3bd00-d64c-11ea-8632-f2cff21177b3.png)

**Comment by wojciechczerniak** [comment]
> Where as in Handsontable 7.4, it looks like cells is called with the visual indices even though the docs say it is call with physical indices. https://handsontable.com/docs/7.4.2/Options.html#cells

The documentation was right in that case. The sorting plugin was introducing wrong indexes and this was fixed in v8.

**Comment by harishtella** [comment]
@wojciechczerniak Got it, thank you. It would be great if there was a note about the sorting plugin changing these physical indices to visual ones for future users of 7.4. It would have saved me some time. All the best.

**Comment by wojciechczerniak** [comment]
@harishtella For sure. We've just release the `v8.0.0` with a dedicated [Migration Guide](https://handsontable.com/docs/8.0.0/tutorial-migration-guide.html) and complete [Release Notes](https://github.com/handsontable/handsontable/releases/tag/8.0.0). I hope they have all the info you had in mind. Sorry we couldn't deliver them earlier for the beta versions.
