### ISSUE TITLE
Changing Cell Default Values upon createSpreadsheetData

### ISSUE THREAD

**Issue by emanuallan** [handsontable/handsontable#7159]
so currently Handsontable.helper.createSpreadsheetData(15, 15), creates a table with cell values that are A1, A2, A3.... etc etc. Is there a way to initialize the table to where the rows are all empty (I know I could just set a bunch of empty strings but maybe there's a better way)?

**Comment by pnowak** [comment]
Hi @emanuallan 

If you don't provide data you receive the table with empty cells. 
Here is a demo - https://jsfiddle.net/2bk154n3/

If you need to initiate the table with 15 by 15 dimensions for example you have to use `startCols` - https://handsontable.com/docs/7.4.2/Options.html#startCols and `startRows` https://handsontable.com/docs/7.4.2/Options.html#startRows options.
Here is a demo - https://jsfiddle.net/7seLdxpq/

**Comment by emanuallan** [comment]
Just a quick follow up, are the values in those initialized cells empty strings or `null` (I'm not at my desk right now or Id check)?

**Comment by emanuallan** [comment]
Just a quick follow up, are the values in those initialized cells empty strings or null? Id check but since we're not passing in a data array in your example, how do you get access to the array in which the cells are inside of?

**Comment by pnowak** [comment]
You can get access to the data by the `getData` method - https://handsontable.com/docs/7.4.2/Core.html#getData.

As you can see in this updated demo - https://jsfiddle.net/sfc6k9g0/ - empty cells are initialized with `null` value.

**Comment by emanuallan** [comment]
thank you for your help! :)
