### ISSUE TITLE
Select custom values by default in filter_by_value in filter functionality 

### ISSUE THREAD

**Issue by mayanksaurabh** [handsontable/handsontable#7173]
### Description
Presently in the filter_by_value dropdown option, all values are selected by default. Is there a way to pass the values that we need to be selected by default. 

For example -1:  
In this pic, I want that "In-ReExpression" should not be selected. "In-ReExpression" box should be unselected by default and its values should only appear in the column if we select it. The option of the "In-ReExpression" value should be there but it should be unchecked by default.
![handson](https://user-images.githubusercontent.com/19463877/89525750-4d812700-d804-11ea-937b-5722f76c1cd0.png)

Will really appreciate the help. 
Thanks

**Comment by AMBudnik** [comment]
Hi @mayanksaurabh 

as mentioned before

> Currently, there are two options
> - all are selected (default)
> - none are selected http://jsfiddle.net/wy133cgy/6/
> The filtering plugin does not provide any public API to modify the list of values or to change their state (checkbox).

However, as you have created a new topic I can mark it as a feature request, as I'm sure this functionality could be useful for some users.

**Comment by AMBudnik** [comment]
Thank you for sharing this idea. I really like it!

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality (maybe some possible API as well) and share their feedback.
See you there!
