### ISSUE TITLE
the docs of Handsontable.helper

### ISSUE THREAD

**Issue by xch1029** [handsontable/handsontable#7176]
### Description
will there is the docs of Handsontable.helper? sometimes I want to study  Handsontable.helper thoroughly!

**Comment by AMBudnik** [comment]
Hi @xch1029 helpers are methods that allows us to make testing easier. We often use `Handsontable.helper.createSpreadsheetData(row, column)` to create a dataset to fill the examples. We do not plan to expose any helpers into the official documentation as a set of supported methods.

**Comment by xch1029** [comment]
> Hi @xch1029 helpers are methods that allows us to make testing easier. We often use `Handsontable.helper.createSpreadsheetData(row, column)` to create a dataset to fill the examples. We do not plan to expose any helpers into the official documentation as a set of supported methods.

ok, I get it, thanks
