### ISSUE TITLE
There's a typo in the definition file for the afterRemoveRow hook

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7179]
### Description

There's a typo in the definition file for the `afterRemoveRow` hook.

![Zrzut ekranu 2020-08-7 o 13 05 02](https://user-images.githubusercontent.com/10757813/89639846-a4433b00-d8ae-11ea-8fc9-8512a7ef5d4a.png)

The `afterRemoveRow` hook should refer to `PhysicalRows` instead of `PhysicalColumns`.

Documentation is correct

![Zrzut ekranu 2020-08-7 o 13 06 52](https://user-images.githubusercontent.com/10757813/89639993-e5d3e600-d8ae-11ea-963d-c284770a4818.png)

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: n/a
* Operating System: n/a

**Comment by wojciechczerniak** [comment]
Release in `v8.1.0`
