### ISSUE TITLE
I want to use spaces to make the table appear indented, is this not feasible?

### ISSUE THREAD

**Issue by Warrens-yg** [handsontable/handsontable#7181]
Like this:
![批注 2020-08-07 222536](https://user-images.githubusercontent.com/46614146/89655071-86082a00-d904-11ea-85a2-7e354ed24fd4.png)

**Comment by AMBudnik** [comment]
Hi @Warrens-yg 

You can turn on the `HTML` renderer and use the space code `&nbsp;` like here https://jsfiddle.net/c2o7L1rx/
