### ISSUE TITLE
Cannot read property 'indicator' of undefined after version 8 update

### ISSUE THREAD

**Issue by Kappyh** [handsontable/handsontable#7182]
### Description
After update my angular application to use the new version of handsontable this message now appears in the console:
```
core.js:4197 ERROR TypeError: Cannot read property 'indicator' of undefined
    at ColumnSorting.onAfterGetColHeader (columnSorting.js:832)
    at Core.<anonymous> (columnSorting.js:232)
    at Hooks.run (pluginHooks.js:2090)
    at Core.runHooks (core.js:4047)
    at TableView.appendColHeader (tableView.js:1136)
    at Array.<anonymous> (tableView.js:624)
    at ColumnHeadersRenderer.render (columnHeaders.js:131)
    at TableRenderer.render (table.js:306)
    at Renderer.render (index.js:109)
    at MasterTable.draw (table.js:343)
```
The only thing I did has update de handsontable for the 8 version and the handsontable/angular for the version 6.0.1

### Steps to reproduce
Update de the handsontable 7 for the handsontable 8, using a table with columnSorting property equals true.
My table is simple, but uses the property ``` [columnSorting]="true" ```.

### Your environment
* Handsontable version: 8.0.0 , Handsontable/angular 6.0.1
* Browser Name and version:  Chrome Version 84.0.4147.105 (Official Build) (64-bit)
* Operating System: MacOS Catalina 10.15.6
* Angular: 10.0.8

**Comment by AMBudnik** [comment]
Hi @Kappyh 

This issue might be related to other settings in your project. Here's an example that uses `columnSorting` https://jsfiddle.net/71cbz5hr/ in the Angular for Handsontable v 6.0.1.

Can you fill my example with remaining settings ?

**Comment by Kappyh** [comment]
> Hi @Kappyh
> 
> This issue might be related to other settings in your project. Here's an example that uses `columnSorting` https://jsfiddle.net/71cbz5hr/ in the Angular for Handsontable v 6.0.1.
> 
> Can you fill my example with remaining settings ?

I think can be something in my angular application. Thank you.

**Comment by AMBudnik** [comment]
Thank you for the update, Gabriela. Feel free to send me a message to support@handsontable.com if you won't be able to find the cause.
