### ISSUE TITLE
The merged area covers too many cells after filtering

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7184]
### Description

The merged area covers too many cells after filtering.

The issue is also replicable with filters (as they hide rows).

**Steps**

1.  Go to https://jsfiddle.net/dez8cvmg/
2.  Autofill `A1` to right
3.  Click the button
4.  Filter column `D` to exclude `empty cells`
5.  Click the button

**Result**

![Zrzut ekranu 2019-10-25 o 15 02 03](https://user-images.githubusercontent.com/10757813/67573354-6cf90880-f738-11e9-8847-af18820390ad.png)

![Zrzut ekranu 2019-10-25 o 15 02 36](https://user-images.githubusercontent.com/10757813/67573394-80a46f00-f738-11e9-9834-f250181ea371.png)

Data is printed according to our needs but the merged area covers too many cells.

### Demo

https://jsfiddle.net/dez8cvmg/

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Chrome 84
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Related issue https://github.com/handsontable/handsontable/issues/6481

**Comment by warpech** [comment]
Simpler reproduction using the same fiddle as above: 

**Steps**

1.  Go to https://jsfiddle.net/dez8cvmg/
2. Notice that the cell A1 is a merged cell with rowspan 3, colspan 3.
3. Filter column `A` to exclude `A1`

**Expected** 

The first row should disappear and the merged cell should now be with rowspan 2, colspan 3 (at least this is what happens in spreadsheet apps)

**Actual**

The first row disappears but the merged cell remains with rowspan 3, colspan 3 - but now in a wrong row, overlapping the cells D1, D2, D3.

<img width="358" alt="Screenshot 2020-12-28 at 16 52 22" src="https://user-images.githubusercontent.com/566463/103226749-16372200-492d-11eb-95b7-f83073e3295b.png">

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **MergeCells grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
