### ISSUE TITLE
Financing

### ISSUE THREAD

**Issue by brillout** [handsontable/handsontable#7187]
Hi :wave:,

I'm Romuald from the [Lsos](https://lsos.org/), an organization that develops financial solutions for open source, and we are currently reaching out to projects we like.

We have several solutions depending on your financial goals and we can help with:
- Increasing donations
- Starting/increasing consulting work for your users
- Earning a living from your open source work
- Remunerating and hiring a small engineering team for your open source projects

For example, we can increase donations with the [Lsos Donation Reminder](https://github.com/Lsos/donation-reminder#lsos-donation-reminder) and the [Lsos Donation Fund](https://lsos.org/fund).

We can also leverage a license clause if you are interested in receiving a substantial remuneration from your open source work. Our license clauses are designed to keep code:
1. Accessible: everything stays free for individuals and small companies &mdash; only large companies pay a small fee.
2. Open: anyone can fork the code and remove the license clause.

Large companies want two things: open source and a way to pay for software. They prefer paying for well-maintained tools rather than using free but unreliable tools. At the end of the day, a license clause can be a win for everyone.

We are focusing on solving the financials of a handful of projects first to then eventually tackle the open source financing problem at large. Let me know if you are interested.

Rom

**Comment by AMBudnik** [comment]
If you have any business proposal please share it on emails. You can reach me at support@handsontable as well as hello@handsontable.com.
