### ISSUE TITLE
Blazor Support

### ISSUE THREAD

**Issue by manthena** [handsontable/handsontable#7190]
Is there any plan to release a wrapper for [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor)?

**Comment by AMBudnik** [comment]
Hi @manthena 

There is no official support for this tool. But if it allows you to inject HTML/JS into a website you should get no issue while doing the implementation. 

Have you already gave it a try?

**Comment by AMBudnik** [comment]
If you would have any issues with the implementation please feel free to share the details with me on emails (support@handsontable.com)

**Comment by manthena** [comment]
Hi @AMBudnik 

Technically, yes it’s possible to use to JavaScript version within Blazor application, but it doesn’t leverage on the advantages of Blazor framework.

1.	All JavaScript code needs to be specified in the root _Host.cshtml file which is loaded into all pages of the application - https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1
2.	We would not be able to utilize the two way data binding features of Blazor - https://medium.com/informatics/two-way-data-binding-on-asp-net-core-blazor-c33982d70ba0
3.	JavaScript itself is treated as a second-class citizen in Blazor apps (similar to angular apps). C# is the preferred way to go in Blazor (similar to Typescript in Angular/React frameworks)

We did develop on a small sample application using Handsontable JavaScript version within Blazor application, but it was very cumbersome to deal with JavaScript code and call the related JS events from Blazor events.

Slowly the adoption of Blazor is growing and several enterprises are considering it for internal business applications. Here are some links which can give you some insights.

https://stackoverflow.blog/2020/02/26/whats-behind-the-hype-about-blazor/
https://insights.stackoverflow.com/trends?tags=blazor
https://insights.stackoverflow.com/trends?tags=blazor%2Cangular%2Creactjs
https://www.telerik.com/blogs/blazor-vs-angular-web-developers

Our team internally used to do development on ASP.NET MVC, but now all the new projects are being developed on Blazor.
In the past we used Telerik Spreadsheet for ASP.NET MVC - https://demos.telerik.com/aspnet-mvc/spreadsheet
There are several features that Handsontable offers that we want in our Blazor applications.

Since you already have a Typescript wrapper for Angular framework, I am assuming it would be relatively reasonable effort to develop a wrapper for Blazor. I hope Handsontable would consider it … it would be of great help to Microsoft Developer community.

Thanks!

**Comment by AMBudnik** [comment]
Thank you for your feedback @manthena I will investigate the subject and discuss the same with the team.

**Comment by manthena** [comment]
Thank you @AMBudnik for considering.

Not just web, Blazor is slowly becoming one-stop framework for all types of application development in Microsoft community – Web, Mobile and Desktop. Here are few additional articles for your analysis.

For Web, Blazor supports both Server Side and WebAssembly apps - https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1

Mobile
https://www.zdnet.com/article/ios-and-android-developers-microsofts-blazor-for-building-mobile-apps-gains-traction/
Blazor Mobile Web Binding - https://devblogs.microsoft.com/aspnet/hybrid-blazor-apps-in-mobile-blazor-bindings-july-update/
Blazor support in upcoming .NET Multi-platform App UI - https://github.com/dotnet/maui
https://medium.com/young-coder/can-microsoft-unify-desktop-and-mobile-34f08348178b

Desktop
As an electron alternative - https://blog.stevensanderson.com/2019/11/01/exploring-lighter-alternatives-to-electron-for-hosting-a-blazor-desktop-app/
SteveSandersonMS is from Microsoft and one of the creators of Blazor. You can find his profile and contributions on Github - https://github.com/SteveSandersonMS

There is a lot happening in this space, and Blazor is becoming the unifying framework from Microsoft for cross platform development. And the good thing is Blazor itself is open source - https://github.com/dotnet/aspnetcore/tree/master/src/Components

Many popular component providers have released controls for Blazor
https://demos.telerik.com/blazor-ui/
https://blazor.syncfusion.com/demos
https://demos.devexpress.com/blazor/
https://www.infragistics.com/products/ignite-ui-blazor
https://demos.componentone.com/blazor/blazorexplorer/

It would be really great to see Handsontable support this ecosystem.

**Comment by AMBudnik** [comment]
Hi @manthena 

I am changing this topic as a feature request and will update you on the status.

**Comment by manthena** [comment]
Thank you @AMBudnik !

**Comment by dkperformance** [comment]
anything new about blazor wrapper?

**Comment by AMBudnik** [comment]
We did not plan to add any new framework support in this quarter. But thank you for leaving your vote for this functionality.

**Comment by AMBudnik** [comment]
Thank you for all your feedback on this integration.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback.
See you there!
