### ISSUE TITLE
Sorting Date Columns

### ISSUE THREAD

**Issue by its-mahdi** [handsontable/handsontable#720]
It seems there is a problem with sorting Date columns. Basically handsontable can't sort the date columns properly.

Please take a look at the Demo tables provided by handsontable offically and try to sort the date column:

http://handsontable.com/demo/date.html

**Comment by frediche** [comment]
It is because the date format Handsontable uses is very restrictive (it uses the default JavaScript Date() function). It is preferable to use Moment.js (http://momentjs.com/). 

This hook works with Moment.js pre-loaded:

In handsontable.full.js:

Look for (around line 9000):
```
var aDate = new Date(a[1]);
var bDate = new Date(b[1]);
```

Replace with:
```
var aDate = moment(a[1], "DD/MM/YYYY");
var bDate = moment(b[1], "DD/MM/YYYY");
```
With the date format you want. Or without format if you want the default Moment.js parsing.

**Comment by pramodsvidyarthi** [comment]
The issue still persists in pro version of hot also, inadequate sort on date fields. Im using moment in the  data of the columnsettings and that didn't help too.

**Comment by AMBudnik** [comment]
Hi @pramodsvidyarthi 
Could you create a demo where this issue can be replicable in your spare time?

**Comment by pramodsvidyarthi** [comment]
@AMBudnik : Sry, my bad i figured out that i had set the field type to text in the column settings, now it does the sort like a charm, but i dont want the dropdown icon in that field since its readonly, is there way i can disable or turn off the visibility of that icon on that field??

**Comment by AMBudnik** [comment]
@pramodsvidyarthi this case would need a little trick. I guess that if your cell is readOnly and it doesn't take a part in some kind of calculations you can change it to a text cell. I don't know your code but it's the first approach that came to my mind.

**Comment by pramodsvidyarthi** [comment]
@AMBudnik thats where im stuck if i make it a text cell that the sort would be incorrect. Shall do a demo on it asap and revert back to u.

**Comment by pramodsvidyarthi** [comment]
@AMBudnik https://jsbin.com/lerububupu/edit?html,js,output

Here im trying something similar and not getting whats expected. Thanks in advance.

**Comment by AMBudnik** [comment]
@pramodsvidyarthi 
I shouldn't share this idea as it's inelegant and could be a problematic but here's what we got it in the DOM:
`<div class="htAutocompleteArrow">▼</div>`
Maybe you can try to erase innerHTML of this element. It only holds an arrow. Example: https://jsbin.com/ducawohile/1/edit?html,js,output

**Comment by pramodsvidyarthi** [comment]
@AMBudnik Thanks for the workaround :+1:
