### ISSUE TITLE
Bug when destroying table. Ghost box stay and multiply when I click on tabs 

### ISSUE THREAD

**Issue by gigilucena** [handsontable/handsontable#7201]
### Description

Hello,

I have been stuck on a problem with handsontable for couple days now. I have a handsontable on a tab. When I switch tabs a ghost little box keep showing on my other tabs. When I inspect the ghost element I saw that was related with a ghost table. 

See pict: 
<img width="242" alt="Screen Shot 2020-08-18 at 2 44 28 PM" src="https://user-images.githubusercontent.com/18387281/90568905-b43a0500-e161-11ea-8dd9-8a3f0d130c9d.png">
<img width="457" alt="Screen Shot 2020-08-18 at 2 44 48 PM" src="https://user-images.githubusercontent.com/18387281/90568908-b56b3200-e161-11ea-8aa3-2b9bbc8b8b54.png">

The ghost box keeps multiplying each time that I click on the tab that my handsontable is. I believe it is a bug on the destroy event. It does not destroy the following tags.

<div class="htMenu htContextMenu"></div>

<textarea class="HandsontableCopyPaste" tabindex="-1" autocomplete="off" wrap="hard"></textarea>

<div class="htMenu htDropdownMenu"></div>

Is there a work around it?

### Steps to reproduce

1. Add couple tabs on your website. Where one of those tab load a handsontable.
2. switch tabs. The handsontable is destroyed when you switch tabs. However, it let some ghost box that multiply.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Google Chrome - Version 84.0.4147.125 (Official Build) (64-bit)
* Operating System: mac OS mojave v 10.14.6

**Comment by AMBudnik** [comment]
Hi @gigilucena 

I can see that you are using Svelte. We do not officially support it yet but are gathering feedback so I'm glad that you've reported this behavior.

Would it be possible for you to help us build a sample project where this issue can be replicable? If you do not want to share the project details on Github please feel welcome to share it on emails (support@handsontable.com).

**Comment by gigilucena** [comment]
Hello, Thank you so much for your quick response. I will prepare something and send to you by email.

**Comment by AMBudnik** [comment]
Great. Thank you.
As we will cover this subject on emails I'm closing this issue report.

**Comment by warpech** [comment]
The solution was in the customer's code. Handsontable was not properly destroyed before removing from DOM. Solution: https://github.com/handsontable/consulting/commit/fbb9999955ca421857e64d2b1fe9d6cd3a65b380
