### ISSUE TITLE
Handsontable scrolling in Observable notebook

### ISSUE THREAD

**Issue by gnestor** [handsontable/handsontable#7202]
### Description
When scrolling, the table should render cells outside of the initial viewable area. It appears that the scroll events are not being recognized in this context vs. the Stackblitz demo (https://jsfiddle.net/api/post/library/pure/).

### Steps to reproduce

1. Go to https://observablehq.com/@gnestor/handsontable-scrolling
2. Try to scroll

### Demo

https://observablehq.com/@gnestor/handsontable-scrolling

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Chrome 84
* Operating System: macOS

**Comment by AMBudnik** [comment]
Hi @gnestor 

Can you re-attach the demo? 

The following link (and the one placed on the website) redirects to an empty JSFiddle project.

**Comment by gnestor** [comment]
@AMBudnik Sorry, you can access that demo by going to the docs and clicking the "Edit" button in the code example: https://handsontable.com/docs/8.0.0/demo-scrolling.html

**Comment by AMBudnik** [comment]
When I use the https://handsontable.com/docs/8.0.0/demo-scrolling.html demo I do not see the same behavior as visible in the example above.


**Our example**
![hot](https://user-images.githubusercontent.com/10757813/90860340-1d9c5c80-e38a-11ea-8a4b-84655c8a35fa.gif)

**Observable**
![obs](https://user-images.githubusercontent.com/10757813/90860352-22f9a700-e38a-11ea-9184-16d95d72c659.gif)


And here https://jsfiddle.net/y5e9vj0r/ I made a demo using your DIV and instance settings and it scrolls well in the code sandbox. I think that it might be related to the CSS attached to the DIV or its parent but without a demo there the issue can be replicable in a sandbox I can only share tips to check
* overflow
* display
* z-index
settings of the #example1 DIV and its parent.

**Comment by AMBudnik** [comment]
@gnestor, before we will be able to define if any of API/CSS can help us to make the example work you can try to add `renderAllRows: true `to your table settings. 

Updated demo https://observablehq.com/@ambudnik/handsontable-scrolling

If you add this option you get all the rows, but `rowHeaders `are not updated with the scroll. I will do my best to push the subject forward and update you with all my findings.

**Comment by gnestor** [comment]
I can confirm that `renderAllRows` fixes the issue of rows not rendering as the user scrolls 👏

I noticed that the header row didn't scroll with the rest of the rows, with or without `renderAllRows`. It seems like this may also be the symptom of handsontable not recognizing scroll events in this context.

**Comment by AMBudnik** [comment]
Hi @gnestor 

It seems that the event issue has the same origin as this one handsontable/handsontable#5633.

Initializing Handsontable inside a virtually created element with `inspect` breaks the scrolling.

**Comment by gnestor** [comment]
Ok, making progress! 

I can confirm that calling `hot.view.wt.wtOverlays.updateMainScrollableElements()` (based on [this comment](https://github.com/handsontable/handsontable/issues/5633#issuecomment-444741138) fixes the header scrolling issue 🎉 

I was able to remove `renderAllRows` because `hot.view.wt.wtOverlays.updateMainScrollableElements()` fixes rows being rendered. It also makes horizontal scrolling ~5x more performant 👍

This is a great workaround but in the future, it would be great to have this working out-of-the-box.

**Comment by AMBudnik** [comment]
> it would be great to have this working out-of-the-box

That's true, @gnestor. I will keep this issue opened and notify you once we fix it internally.

**Comment by swistach** [comment]
Hi @gnestor,
I'm glad the workaround helped you. Due to we want to keep the focus on the source of the problem I'm going to close this issue.
Please track progress in #5633.
