### ISSUE TITLE
Autofill formulas not working

### ISSUE THREAD

**Issue by tarnishablec** [handsontable/handsontable#7203]
### Description

Autofill formulas not working

should auto fill cells with formula

### Steps to reproduce

1. fill a cell with a formula
2. drag autofill rectangle to another cell 
3. just copy the value but not auto calculate formula for new cell

### Demo

https://codesandbox.io/s/handsontable-bug-twkiy

### Your environment
* Handsontable version: latest
* Browser Name and version: latest
* Operating System: windows 10

![fill](https://user-images.githubusercontent.com/42984497/90625100-a5c81800-e24b-11ea-9e94-c89a8adbb1d4.gif)

**Comment by tarnishablec** [comment]
I wonder know is this a bug or wrong setting or just there is not implementation yet?

**Comment by AMBudnik** [comment]
Hi @tarnishablec 

Thank you for sharing this question.

Autofill for formulas is copying a value. It is not generating a new formula.
This functionality is mentioned here https://github.com/handsontable/handsontable/issues/4315

We haven't scheduled it yet but rest assured, I will notify you once we get this done.
