### ISSUE TITLE
Handson Table is throwing #VALUE Error for some of the complex formulas

### ISSUE THREAD

**Issue by shanath111** [handsontable/handsontable#7204]
### Description

Handson Table is not supporting complex formulas, Like sumif and other, where as same formula is evaluated by Excel,

Some of the expected formulas are listed below, and also simple sample is given in the JS fiddle.
=IF($AA6="No",0,IF($AB6=0,$U6,IF($AB6="",$U6,IF(AND(($U6>=$AB6),($U6<=$AC6)),$U6,AVERAGE($AB6,$AC6)))))
=SUMIF($I$2:$I$6B204,"Relevant",O2:O64)

[Demo](https://jsfiddle.net/th6csvbr/)
https://jsfiddle.net/th6csvbr/

### Your environment
* Handsontable version:Latest version
* Browser Name and version:chrome
* Operating System:Windows

**Comment by AMBudnik** [comment]
Hi @shanath111 

`SUMIF` issue is already reported here https://github.com/handsontable/handsontable/issues/6790
Could you share a demo with the complex formula that did not work for you (both demos attached are `SUMIF`s)

**Comment by AMBudnik** [comment]
Hi @shanath111 

do we have any updates on the complex formula subject?

**Comment by shanath111** [comment]
Hi Thanks for the update,

Since SUMIF is more crucial for over requirement we decided to go with other tool,

thanks for your timely support.

Regards
Shanath Shetty
________________________________

**Comment by AMBudnik** [comment]
Thank you for the update. I guess that we can close this topic.
