### ISSUE TITLE
Inserting a new row directly in data array and calling updateSetting to see it appear reset the undo redo stack

### ISSUE THREAD

**Issue by pinuchfab** [handsontable/handsontable#7216]
### Description
In order to add children rows under a parent row dynamically, we grammatically insert rows under it:

**e.g: Expand row A with two child row A1 and A2:**
data before expanding row A:
A
B
C

data after expanding row A:
A
-A1
-A2
B
C

We essentially inserted A1 and A2 rows by changing the data directly, then we call updateSettings ({ data: newData});
our new rows are displayed in v8, but the whole undo redo stack is cleared because this is what updateSettings does. V7 didn't clear the undo redo stack, so this is why we log this problem even so we know render() has been deprecated.

In order to prevent loosing the undo redo stack, we keep reference of the undoRedo lists before calling updateSettings and restore it as well as modifying the row index in the changes bag for changes that exist for rows positioned after row A, which will be B and C.

**e.g:**
undo stack before expanding row A
changes: [{1, ...}]  // a change exists on row B, row index 1

undo stack after expanding row A:
changes: [{2, ...}]    // previous row idx + 1 because we inserted a new row before row B, change row index is now 2

This technique of keeping the undo redo stack, calling updateSetting, then rebuilding the stack and restoring it seems to work.
Even so it is rather delicate and we are improving it a bit.

This allows us to add/remove rows without using the insert/delete hooks (which are considered changes and are recorded in the undo redo stack).

Is there a better way to achieve what we want to do without saving/restoring the undo redo stack?

Alternatively we would use the NestedRow feature? But it looks like the nested rows needs to be added at initialization, and we might end up with a big data as some of our nested rows list can be huge. 

Or is there a way to tell HoT that we have inserted or deleted rows directly to or from the data array, and prevent updateSettings to clear the undo redo stack, as well as updating the undo redo stack based on the position of insert or delete? Essentially we believe that the insert hook does something similar, as inserting a row via right click seems to re-organize the undo redo stack.

Thanks for helping us.

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: v8.0beta
* Browser Name and version: chrome
* Operating System: win10

**Comment by AMBudnik** [comment]
Hi @pinuchfab 

I've created a demo to help us discuss this subject https://jsfiddle.net/65ra79jn/1/

Please feel it with your custom undoRedo and provide expected/actual behavior in a step-by-step scenario.

**Comment by pinuchfab** [comment]
Hello @AMBudnik 
I actually found a bug in the NestedRow demo you provided as well as the official website, the undo redo doesn't behave properly after collapsing the nested rows.
I believe I have implemented a solid custom solution which essentially save the undo redo stack and restore it with a little shifting of the changes row index based on the position I have pushed or removed data from the internal data.
The algo is something like this:
saveUndoRedoStack(); // copy undo and redo arrays into prevDoneActionsArr and prevUndoneActionsArr arrays
data.insert({ newRow }, atIndex = 2); // insert a new row in data array @ pos 2
updateSetting( { data: newData}); // undo redo cleared, new row shown properly
handonstable.UndoRedo.doneActions = prevDoneActionsArr;
handonstable.UndoRedo.undoneActions = prevUndoneActionsArr;
shiftUndoRedostack(); // this shifts all the existing changes or insert row position by the number of row inserted or removed.
// Undo redo stack back to normal and working properly.

So saving the stack, making the change and restoring the stack with a shift or row position works.
Is there anything I should be concerned about?

I propose we have a call and I show you the result of my solution.

Regards,
Fabien

**Comment by AMBudnik** [comment]
Thank you for sharing additional details @pinuchfab 

Please share your contact info and the step-by-step issue description for 

> I actually found a bug in the NestedRow demo you provided as well as on the official website

on my email support@handsontable.com
