### ISSUE TITLE
Rendering custom react component in handsontable

### ISSUE THREAD

**Issue by z-sanjivini** [handsontable/handsontable#7219]
### Description

I wanted to render a custom react component in the handsontable. I went through the documentation to find HotColumn component to achieve this. All the examples use data as array of arrays in this component whereas array of objects would have been more prefereable. Also I have been having this below issues: 

Not able to access React component events like on change etc of custom editor component.
Not able to access any event of internal rendered custom react component.

### Your environment
* Handsontable version: ^8.0.0
* Browser Name and version: Chrome 84
* Operating System: Mac High Sierra

**Comment by AMBudnik** [comment]
Hi @z-sanjivini 

Please share a demo showing your latest progress and license ID with me on support@handsontable.com. I'll do my best to help you build the functionality.

**Comment by z-sanjivini** [comment]
I can share with you the demo but Im afraid I am not a licensed user.

Thanks & Regards,

Sanjivini Ahuja
Zenarate Inc.
________________________________

**Comment by z-sanjivini** [comment]
Hi,

This is in regards to my previous query on github. I have just started using your tool and was facing an issue when I use it along with custom components in React. I am planning to buy a license once I am sure about its usability for my work.
It would be great if you could respond. Have a nice day!

Thanks & Regards,

Sanjivini Ahuja
Zenarate Inc.
________________________________

**Comment by AMBudnik** [comment]
Hi @z-sanjivini 

I did not get any email from you on support@handsontable.com. Please share the demo and your project requirements on emails. 
We want to keep Github as a place to report confirmed issues and feature requests.

**Comment by AMBudnik** [comment]
I got the email. We can close this topic.
