### ISSUE TITLE
Error when remove row.

### ISSUE THREAD

**Issue by gigilucena** [handsontable/handsontable#7225]
### Description

We sometimes get an error when removing a row from the handsontable. I tried to do some investigation and figure out how to replicate the error.  It happens when we try to remove a row after we had insert a new row.
I installed the handsontable version 8 to see if it would fix it, but it did not.

The error is the following:
![Screen Shot 2020-08-26 at 2 28 10 PM](https://user-images.githubusercontent.com/18387281/91361480-3b642a00-e7ad-11ea-8e4d-20b140fcb1ee.png)

### Steps to reproduce

1. Have a table with some rows.
2. Insert a new row at the bottom of the table.
3. After inserting the row, try to remove the row above the one that you just inserted.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 8
* Browser Name and version: google chrome - Version 84.0.4147.135 (Official Build) (64-bit)
* Operating System: IOS 10.14.6

*** I noticed that if I add a new row, refresh the page and try to remove a row the error does not happens. However, If I need to refresh the page each time that I add a row to the table, it will be time consuming.

**Comment by AMBudnik** [comment]
Hi @gigilucena 

Can you share a demo where this issue can be replicable? 
I've tried your scenario using this demo https://jsfiddle.net/AMBudnik/u5nov3wb/1/ on Chrome 84/macOS Catalina 10.15.3 but did not succeed with issue replication.

**Comment by AMBudnik** [comment]
As I'm with Gigi on emails I'm closing this issue.
