### ISSUE TITLE
Filter by value input is inactive for Handsontable inside a modal window

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7226]
### Description

Filter by value input is inactive for Handsontable inside a modal window. We cannot type, the focus is gone.

### Steps to reproduce

1. Open dropdown menu for any column
2. Try to type anything in the filter by value

### Demo

http://jsfiddle.net/AMBudnik/arenu56s/1/

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: chrome 84
* Operating System: macOS Catalina 10.15.3

Inform Zen 25352

**Comment by luca-costanzo** [comment]
Hi @AMBudnik ,

after many attempts I found the event listener causing this issue, it was a focus listener set by Bootstrap when initializing the modal and it was "conflicting" with others set by Handsontable.
I fixed it by setting the option `focus: false` at modal initialization:
[https://getbootstrap.com/docs/4.5/components/modal/#options](https://getbootstrap.com/docs/4.5/components/modal/#options)

I suggest you also to set options `backdrop: 'static', keyboard: false` just to avoid any further problem of unexpected event listeners conflicting with Handsontable.

Regards,
Luca

**Comment by AMBudnik** [comment]
Thank you for sharing your findings, Luca.

**Comment by swistach** [comment]
Probably there is nothing else we can do with that at the moment except configuration.
Bootstrap modal [enforces `focus` by default](https://github.com/twbs/bootstrap/blob/main/js/src/modal.js#L284-L293) - probably to allow keyboard navigation only in open modal context. At the same time, Handsontable expects to `focus` elements attached to the `body` element.
Many of the table's UI elements we append to the `instance.container.ownerDocument.body`. They are out of the modal box, so the fragment of code I linked above enforces to focus modal box.
Here is an updated example: http://jsfiddle.net/crf8ab1k/

Disabling the `focus` option for the modal box has, unfortunately, the downside. User can navigate through focusable elements in the layout - using <kbd>TAB</kbd> combination - to reach elements from outside the modal box.

Support for components such as bootstrap modals will be possible if we implement ideas from #7782.

For now, the best option here is to prepare a guide in our documentation, e.g., "How to integrate Handsontable in Bootstrap 4.x". 🙂

**Comment by AMBudnik** [comment]
Works the same in v12.2.0 http://jsfiddle.net/h67reawj/ (updated demo the first one does not work anymore)

**Comment by AMBudnik** [comment]
Hi @luca-costanzo I have good news. 
It seems that this issue is no longer replicable. Here https://jsfiddle.net/g4rkdbt8/1/ is the updated demo.

**Result**
<img width="673" alt="Zrzut ekranu 2024-02-19 o 13 46 06" src="https://github.com/handsontable/handsontable/assets/10757813/44971fe8-738b-4163-b0eb-40f157de4b5b">
