### ISSUE TITLE
[8.0.0] Using updateSettings() breaks column sorting in specific cases

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7228]
### Description

Updating `colWidths` breaks column sorting for `nestedHeaders` implementation. We get a console error of the indicator.
It works the same for `multiColumnSorting`.

### Steps to reproduce

1. Open console

**Result**
![Zrzut ekranu 2020-08-28 o 09 29 08](https://user-images.githubusercontent.com/10757813/91533943-0375f780-e911-11ea-8a46-a06a988e0445.png)

### Demo

https://jsfiddle.net/AMBudnik/5ms4rpqf/ 8.0.0 - broken
https://jsfiddle.net/AMBudnik/wfdLp8x2/ 8.0.0-beta1 broken
https://jsfiddle.net/AMBudnik/bja6zyp7/ 7.4.2 - working
https://jsfiddle.net/AMBudnik/xr5p7j9n/ 7.0.0 - working

### Related issues
* https://github.com/handsontable/angular-handsontable/issues/213 

### Your environment
* Handsontable version: 8.0.0-beta1
* Browser Name and version: Vanilla
* Operating System: macOS Catalina

Inform [`forum`](https://forum.handsontable.com/t/cannot-read-property-indicator-of-undefined/4612/11)

**Comment by AMBudnik** [comment]
I've changed the title as it appears that calling an empty `updateSettings()` will also produce the issue 

https://jsfiddle.net/AMBudnik/5v9hLpxr/ v8.0.0 - broken
https://jsfiddle.net/AMBudnik/2csa6unf/ v8.0.0-beta1 - broken
https://jsfiddle.net/AMBudnik/qafebycm/ v 7.4.2 - working

**Comment by ottosson** [comment]
I get this error when i run updateSettings with maxRows included.

**Comment by budnix** [comment]
I got the same error while working on my/hot/com project. As a workaround, I resigned from using `updateSettings` in favor of creating a new HoT instance.

**Comment by wszymanski** [comment]
> ```js
>   columns: [{}, {}, {}, {}, {}, {}],
>   columnSorting: true,
>   colHeaders: true
> ```

Good job, this example has the minimum configuration which helped a lot. I will fix it soon.

**Comment by bitwolfe** [comment]
We ran into this issue as well when upgrading to 8.0. Looking forward to the release of a fix!

**Comment by aninde** [comment]
@bitwolfe @ottosson I'm glad to see that this issue will be fixed by the upcoming `v8.1.0` https://jsfiddle.net/aninde/ehcyszro/ [Case 2](https://github.com/handsontable/handsontable/issues/7228#issuecomment-682377639) https://jsfiddle.net/aninde/1wogebLd/
We plan to release it this week (Oct 1), as long as everything goes well.

**Comment by AMBudnik** [comment]
Hi @bitwolfe @ottosson we've just released Handsontable v.8.1.0 where this issue is no longer replicable.
