### ISSUE TITLE
[8.0.0] setDataAtRowProp Set  auxiliary properties isn't working in 8.0

### ISSUE THREAD

**Issue by giorgitus** [handsontable/handsontable#7230]
### Description
In my application I use setDataAtRowProp to set some auxiliary properties to my data. In version 7 it wasn't a problem but in 8 I receive this error:
Uncaught Error: Assertion failed: Expecting an unsigned number.
    at assert (modules.js?hash=614bb67c3586a4e88231c19c4e3be5ec442cb6af:48315)
    at LazyFactoryMap.obtain (modules.js?hash=614bb67c3586a4e88231c19c4e3be5ec442cb6af:87836)
    at CellMeta.getMeta (modules.js?hash=614bb67c3586a4e88231c19c4e3be5ec442cb6af:107405)
    at MetaManager.getCellMeta (modules.js?hash=614bb67c3586a4e88231c19c4e3be5ec442cb6af:106714)
    at Core.getCellMeta (modules.js?hash=614bb67c3586a4e88231c19c4e3be5ec442cb6af:82007)
    at validateChanges (modules.js?hash=614bb67c3586a4e88231c19c4e3be5ec442cb6af:80304)
    at Core.setDataAtRowProp (modules.js?hash=614bb67c3586a4e88231c19c4e3be5ec442cb6af:80594) 

### Demo
here the demo with 8.0.0
https://jsfiddle.net/gtoniolo/cu2dj6p9
and here with 7.4.2
https://jsfiddle.net/gtoniolo/cu2dj6p9/2

### Your environment
Handsontable version: 8.0.0
Browser Name and version: Vanilla
Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
Thank you for sharing the issue scenario @giorgitus 
I confirm the issue replication on macOS Catalina 10.15.3 / Chrome 84. 

It looks like we cannot add a column by adding an external key. If we want to use the `setDataAtRowProp` method to replace a value of already defined key it works well.

**Comment by AMBudnik** [comment]
Hi @giorgitus 

we had a quick chat about this issue among the team and it turned out that this behavior follows the rules set for v8.0.0.
We will add missing information to our docs.

**Comment by giorgitus** [comment]
Ok, 
is there any other way to add an hidden auxiliary properties to my data?what do you suggest?

Thank you

**Comment by scarletfog** [comment]
@giorgitus does `setSourceDataAtCell` https://handsontable.com/docs/8.0.0/Core.html#setSourceDataAtCell work for you?

**Comment by giorgitus** [comment]
I'm so stupid. That's the right method to do it. The source code wasen't mine so I didn't investigate enought.

**Comment by scarletfog** [comment]
No, no, it's just documentation that should be more descriptive and helpful, I will improve it. 
Glad it worked for you!

**Comment by swistach** [comment]
Hi @giorgitus, I'd like to put in my tuppence worth, here is a demo adjusted to the v8: https://jsfiddlle.net/8pg517ud/ just in case someone else will face a similar problem.
Thank you for your involvement! :)

**Comment by scarletfog** [comment]
The migration guide was updated https://handsontable.com/docs/8.0.0/tutorial-migration-guide.html alongside release notes.  I am closing this issue.
