### ISSUE TITLE
[7.3.0] Using updateSettings() in the ~after and ~beforeCreateCol hook prints console error

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7231]
### Description

Using `updateSettings()` in the ~`after` and ~`beforeCreateCol` hook prints console error.

![image](https://user-images.githubusercontent.com/10757813/91705102-ce6ddd00-eb7c-11ea-83d9-55e271bc2e62.png)

### Steps to reproduce

1. Use 'Insert column left' or 'Insert column right' on `Tom` cell.
2. Open the console

![image](https://user-images.githubusercontent.com/10757813/91705159-e5143400-eb7c-11ea-9d3a-c9d0fcff5f91.png)

### Demo

https://jsfiddle.net/xnga04p7/1/ 7.2.0 (working well)
https://jsfiddle.net/xnga04p7/ **7.3.0 (broken)**
https://jsfiddle.net/xnga04p7/2/ 8.0.0 (broken)

### Your environment
* Handsontable version: 7.3.0+
* Browser Name and version: Chrome 84
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Using a context menu to apply the `col_left` key fails as well https://jsfiddle.net/xnga04p7/3/. We get the same error in the console.

**Comment by OlgaIOn** [comment]
The same error for **mergeCells** when using `updateSettings()` in the ~`after` and ~`beforeMergeCells`.
https://jsfiddle.net/fod3rpc6/1/

**Comment by AMBudnik** [comment]
True, thank you for sharing the example @OlgaIOn

**Comment by AMBudnik** [comment]
Hi @OlgaIOn 

We just released Handsontable v8.3.2 which solves this bug. I'd love to hear your feedback on the version.
