### ISSUE TITLE
Multiple Table in Single Page getting Hide

### ISSUE THREAD

**Issue by SathishRamV** [handsontable/handsontable#7232]
when i try to use multiple table in same page ,Handsontable getting hidden

**Comment by AMBudnik** [comment]
Hi @SathishRamV 

what settings do you use?

Here https://jsfiddle.net/uonkvjpb/ I've generated two tables. One uses `hiddenColumn`, second does not.
Please update my demo in the way it will replicate the issue you're facing.

**Comment by AMBudnik** [comment]
Hi @SathishRamV 

do we have any updates here?
