### ISSUE TITLE
Performance bottleneck for the AutoColumnSize plugin

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#7235]
### Description
There is a big problem with the performance of the `AutoColumnSize` plugin. It seems that the calculation done by the plugin takes a very long time even for tables with a simple configuration. It's also noticeable for cooperation with `TrimRows`, `HiddenRows` and `HiddenColumns` plugins which was mentioned within https://github.com/handsontable/handsontable/pull/7223. The below image shows a bottleneck occurrence just after untrimming rows.

![Screenshot 2020-09-01 at 10 08 30](https://user-images.githubusercontent.com/141330/91824675-6af6b480-ec3b-11ea-94c8-d63a1c5a36bc.png)

Please keep in mind that @aarondfrancis mentioned some kind of improvement within https://github.com/handsontable/handsontable/issues/6676 which should be also considered.

### Your environment
* Handsontable version: <= 7.4.2.

**Comment by aarondfrancis** [comment]
Happy to help if I can!
