### ISSUE TITLE
Handling errors resulting from the lack of support for removed features

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7237]
### Description
When the user tries to declare a removed plug-in, an error appears in the console informing about its removal.
However, after that, many more errors appear in the console. 

We should block that additionals error so that the user doesn't get the impression that this situation is not handled.

This applies to:
https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/core.js#L1901-L1909

-  `ganttChart` https://jsfiddle.net/aninde/qomzhex7/
-  The `rows` setting https://jsfiddle.net/aninde/bysuz7gm/
- The `cols` setting https://jsfiddle.net/aninde/3s7ny14d/

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: any
* Operating System: any

**Comment by warpech** [comment]
> after that, many more errors appear in the console

What is the example of these errors? I can see some errors on mouse over, is this what you mean?

![image](https://user-images.githubusercontent.com/566463/109302935-4a9a6200-783a-11eb-929b-3714c463b28c.png)
