### ISSUE TITLE
Trimming rows doesn't set correct table height

### ISSUE THREAD

**Issue by feberhard** [handsontable/handsontable#7241]
### Description
Trimming or hiding rows, when setting the table data through `loadData(...)` or `updateSettings({ data: ... })` and having a fixed row and column, doesn't update the table height. 
After a resize of the browser window, the table height is correct.
When setting the data immediately in `new Handsontable(...)` or when not using fixed rows and columns, the problem doesn't occur.

### Steps to reproduce
1. Have `fixedRowsTop: 1, fixedColumnsLeft: 1`
2. Set data through `loadData(...)` or `updateSettings({ data: ...})`
3. Trim rows
4. Scrollbar still shows the height before the trimming

### Demo
https://jsfiddle.net/t8qjd7k4/6/

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Chrome Version 85.0.4183.83 (Official Build) (64-bit)
* Operating System: Windows 10 (2004)

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @feberhard 

It looks like the data attachment time changes the situation

https://jsfiddle.net/AMBudnik/7d0yrbv1/

It works well in my demo, but when we use delay it breaks.

**Comment by aninde** [comment]
The upcoming v8.2.0 fixes this problem, scrollbar no longer appears after trim.
Demo v8.2.0 https://jsfiddle.net/aninde/cvqsn49k/

![8 2 0](https://user-images.githubusercontent.com/30186818/98002956-7064ac80-1dee-11eb-8f67-1baeeac4b035.gif)

Tested on macOS Catalina 10.15.7

- Chrome Beta 87 and stable 86
- FF 83.0b7 and stable 82
- Safari 14 and Safari Technology Prev 14.1

Windows 10

- IE 11
- Edge 86
- Edge Dev 88
- Chrome 86

**Comment by AMBudnik** [comment]
Hi @feberhard @bamminger 

We are happy to announce that the new version of Handsontable - 8.2.0 - that fixes this issue has been published.
