### ISSUE TITLE
How to ajax data in handsontable type cell and refresh

### ISSUE THREAD

**Issue by tzwhyqq** [handsontable/handsontable#7247]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/
<div class="main-card-content">
        <hot-table
          ref="excelTable"
          :settings="tableSettings"
        />
      </div>

tableSettings: {
  afterDocumentKeyDown: (event) => {
       
          const hot = this.$refs.excelTable.hotInstance
          const val = hot.getActiveEditor().TEXTAREA.value

        

          openapi.getList({
            key: val
          }).then(({ code, data, message }) => {
            if (code == 200) {
        

              this.tableSettings.columns[2].handsontable.data = data
              console.log(this.tableSettings.columns[2].handsontable.data)

              hot.updateSettings({
                columns: this.tableSettings.columns
              })
           
            } else {
              this.$message.error(message )
            }
          })
        }
   columns: [
  {
            data: 'rawMaterialCode',
            width: 100,
            type: 'handsontable',
            handsontable: {
              colHeaders: ['code', 'color', 'eCode', 'eColor', 'spec'],
              columns: [
                {
                  data: 'code',
                  width: 120
                },
                {
                  data: 'color',
                  width: 100
                },
                {
                  data: 'eCode',
                  width: 100
                },
                {
                  data: 'eColor',
                  width: 100
                },
                {
                  data: 'spec',
                  width: 100
                }
              ],
              data: [],
              className: 'rowTable',
              getValue: function() {		// 显示选择的值
                var selection = this.getSelectedLast()
                return this.getSourceDataAtRow(selection[0]).code
              },
              strict: true

            }
          }
]
}

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @tzwhyqq 

I can see that you are trying to run an async function on every `afterDocumentKeyDown` call. Wouldn't it be better to use `afterChange` instead? Here's a tutorial https://handsontable.com/docs/8.0.0/tutorial-load-and-save.html
