### ISSUE TITLE
Is there a way to maintain filters after use loadData function ?

### ISSUE THREAD

**Issue by donkw** [handsontable/handsontable#7249]
### Description
I need to use 'loadData' function to update the table data, becuase there are a lot of data return from server, i don't want to update the cell value in a loop. Is there a way to update data and maintain the current filters?

**Comment by AMBudnik** [comment]
Hi @donkw 

the `afterFilter`and `beforeFilter` hooks return information about the filter config that has been applied for a column. Here's an example http://jsfiddle.net/handsoncode/c8phv3dy/

Once you store the config you can call `addCondition` method of `Filters` plugin, like so

> filtersPlugin.addCondition(column_index, operation_name, [value]));

**Comment by donkw** [comment]
> Hi @donkw
> 
> the `afterFilter`and `beforeFilter` hooks return information about the filter config that has been applied for a column. Here's an example http://jsfiddle.net/handsoncode/c8phv3dy/
> 
> Once you store the config you can call `addCondition` method of `Filters` plugin, like so
> 
> > filtersPlugin.addCondition(column_index, operation_name, [value]));

Thanks @AMBudnik ,
I can't find the method `addCondition` in version 8.0. Has this method been deprecated? Is there an alternative?

**Comment by AMBudnik** [comment]
@donkw `addCondition` has been removed by a broken ESLint rule. It will be readded to the docs. Our Tech Writer is already checking if all other methods are listed.
This method is not visible in the docs but it is working for all the versions. If you like to construct a rule for this method please let me know and I will help.
