### ISSUE TITLE
Add a description for the refreshDimensions core method

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7250]
### Description

Add a description for the `refreshDimensions` core method.

Reference https://github.com/handsontable/handsontable/blob/master/src/core.js#L1630

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: n/a
* Operating System: n/a

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/handsontable/pull/7265
