### ISSUE TITLE
Duplicate Footers with Small Datasets

### ISSUE THREAD

**Issue by vancan1ty** [handsontable/handsontable#7251]
### Description
When there is a small number of rows in a grid, Handsontable will display multiple copies of the "fixedRowsBottom" rows.  Display of footer rows is a common use-case and footers should never be duplicated IMO.

### Steps to reproduce

1. Create a handsontable grid with a fixed height.
2. Add a handful rows to the grid, and set "fixedRowsBottom" to >= 1.
3. Note that you will see the footers twice.

You may argue that then the developer should change the height of the grid depending on the number of rows, but even if you start dynamically shrinking the grid it's actually hard to get the bottom of the grid data to line up perfectly with the start of the footers... see for example testcase three below.

### Demo

Here are three examples of the problem:
1. A grid which is close to handsontable default styling and has fixedrowsbottom.
https://jsfiddle.net/wa41gn8q/21/
![image](https://user-images.githubusercontent.com/2806839/92278836-e4e0a500-eeaa-11ea-87fd-8836b36dd613.png)

2. Styling a little more customized (closer to our specific usecase, we use custom css to make the grid more compact)
https://jsfiddle.net/on2sw1v5/25/
![image](https://user-images.githubusercontent.com/2806839/92278885-fe81ec80-eeaa-11ea-8d4f-26456a2cd7ec.png)

3. Third example derived from handsontable default demo by removing "fixedRowsTop" line -- if you scroll down you will see that "Israeli New Shekel" is duplicated.
https://jsfiddle.net/mwvj1pxt/1/
![image](https://user-images.githubusercontent.com/2806839/92278692-9df2af80-eeaa-11ea-8031-bb6864256f54.png)

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Chrome 85.0.4183.83
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @vancan1ty 

It seems that this issue is the same as https://github.com/handsontable/handsontable/issues/4454

I will notify you with any changes to https://github.com/handsontable/handsontable/issues/4454

**Comment by AMBudnik** [comment]
Hi @vancan1ty 

I just wanted to make an update here as well as the $4454 was closed and solved in Handsontable v12.1.0
