### ISSUE TITLE
with fixedColumnsLeft, When I moved srcoll bar, the button is moved also

### ISSUE THREAD

**Issue by fredchengfei** [handsontable/handsontable#7254]
### Description
with fixedColumnsLeft, When I moved srcoll bar, the button is moved also
![2020-09-08_150404](https://user-images.githubusercontent.com/66353504/92443911-c0573680-f1e4-11ea-9f93-f61754e0de69.jpg)
![2020-09-08_150506](https://user-images.githubusercontent.com/66353504/92443917-c2b99080-f1e4-11ea-92be-ea4a4c3eec79.jpg)

### My environment
* Handsontable version:8.0.0
* Browser Name and version:Chorme
* Operating System:win10

**Comment by AMBudnik** [comment]
Hi @fredchengfei 

It looks like the behavior of the button is related to the CSS settings of your website. Please fill this demo https://jsfiddle.net/AMBudnik/sg93ukhe/ with your settings.

**Comment by fredchengfei** [comment]
https://jsfiddle.net/joethesoldier/o4yt5g03/1/#&togetherjs=gyJmO0Gpby

**Comment by fredchengfei** [comment]
https://jsfiddle.net/mxd9rzap/3/#&togetherjs=ANpmjswk77

**Comment by AMBudnik** [comment]
@fredchengfei you need to add width and height for the container to trigger right scroll https://jsfiddle.net/AMBudnik/uygvf9te/ (lines 44-45)

**Comment by AMBudnik** [comment]
If you would have any further questions please feel free to send me an email (Support@handsontable.com)
