### ISSUE TITLE
The HoT goes into the infinite loop while scrolling

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7256]
### Description

The HoT goes into a loop when the header column is enabled and the scrollable element is `window` object. The fun fact is that it happens only when the user clicks the link which is embedded into `<p>` element (maybe others too). When the link is embedded into `<div>`, `<span>` or `<strong>` element as in the demo the issue not exist. The story is more interesting when I say that the click event, in that case, does nothing. There is no handler attached to the click event.

While investigating the issue I've spotted that this happens only on Chrome and it's reproducible on v84, v85, v86 (Chrome Beta). I've tested on Chrome Canary (v87) and didn't found any issues.

### Steps to reproduce
![Kapture 2020-09-09 at 10 06 27](https://user-images.githubusercontent.com/571316/92573200-b76a7180-f285-11ea-9431-1f67454f536d.gif)

In 7.4.2 and below the header jumps but without going into the loop.
![Kapture 2020-09-09 at 10 21 29](https://user-images.githubusercontent.com/571316/92573995-d1f11a80-f286-11ea-9dfc-e283a9f5a74e.gif)

### Demo

https://jsfiddle.net/budnix/r609bLns/

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Chrome (v84, v85, v86)
* Operating System: macOS Catalina

**Comment by aninde** [comment]
This issue will be fixed by `v8.1.0` https://jsfiddle.net/tpL2h16a/
Tested on Chrome 85, 86 (Beta), 87 (Canary) / macOS Catalina 10.15.7

**Comment by AMBudnik** [comment]
We can close the issue as solved for v 8.1.0. Good work guys!
