### ISSUE TITLE
Undo doesn't work for 2nd operation if minSpareRows are used along with numeric cell type

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7258]
### Description

Undo doesn't work for 2nd operation if `minSpareRows` are used along with `numeric` cell type. Surprisingly, it works well in Vanilla but it does not work for all the wrappers.

### Steps to reproduce

1. Type 't' in A1
2. Use <kbd>TAB</kbd>
3. Type 't' in A2
4. Use <kbd>TAB</kbd>
5. Use Undo
6. Use Undo

### Demo

**Vanilla** works fine https://jsfiddle.net/AMBudnik/tyjfkhed/
**React** doesn't work https://jsfiddle.net/AMBudnik/5t4w1h3g/
Here is a demo in **Angular** - https://jsfiddle.net/8wzo1r73.
And in **Vue** - https://jsfiddle.net/vmfhk75a/.

We've checked with @pnowak that it works the same in v7.4.2

### Your environment
* Handsontable version: 8.0.0 
* Wrappers: React, Angular, Vue
* Browser Name and version: Chrome 85
* Operating System: macOS Catalina 10.15.3

**Comment by AMBudnik** [comment]
This issue is also replicable when a cell is
* date
* dropdown
* autocomplete
* time

But it works well for
* checkbox

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by jansiegel** [comment]
@AMBudnik This problem is still happening, but it affects the vanilla version as well - in your vanilla example you've defined `minSpareRows` as `true` (unlike `minSpareRows: 1` in the wrappers).

https://jsfiddle.net/js_ziggle/a2o4cuk3/

**Comment by AMBudnik** [comment]
Thanks for spotting that @jansiegel I'm changing the description.

**Comment by adrianszymanski89** [comment]
Inform ZD (29310)

**Comment by Wojciech-Swiderski** [comment]
Issue resolved:
https://jsfiddle.net/tvod4k2n/1/

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1BvQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78215a5a5dead02c30b08ca1601ad8d77977374a/Screen%20Recording%202025-02-18%20at%2011.14.40.mov)
