### ISSUE TITLE
Some e2e test does not pass on Firefox and Opera

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7261]
### Description
Tested as intended on [docs](https://handsontable.com/docs/8.0.0/tutorial-testing.html) .
Another failed test still exists https://github.com/handsontable/handsontable/issues/6601.
These tests were running on an earlier version of Handsontable.

**Failed tests:**
```
NestedRows > Cooperation with the `ManualRowMove` plugin > should move single row between parents properly (moving from the bottom to the top)
Expected 'Alabama Shakes' to equal 'Ghost'.

Expected $[0] = 2 to equal 1.
Expected $[2] = 2 to equal 1.
```
<img width="952" alt="Screenshot 2020-09-09 at 16 31 04" src="https://user-images.githubusercontent.com/30186818/92612662-5dd06a00-f2ba-11ea-9b00-1bf64c071baf.png">

```
UndoRedo > core features > Object data > undo > should undo removal of fixed row on the bottom
Expected 1 to be 0.
```
<img width="643" alt="Screenshot 2020-09-09 at 16 31 21" src="https://user-images.githubusercontent.com/30186818/92612675-60cb5a80-f2ba-11ea-9c37-3a546884f444.png">

### Your environment
* Handsontable version: 8.0.0 (branch `master`)
* Browser Name and version: Firefox 80.0.1, incognito mode
* Operating System: macOS Catalina 10.15.6, Retina 15-inch

**Comment by wojciechczerniak** [comment]
Done in  #7321
