### ISSUE TITLE
Undo doesn't undo the correct cell after moving the column that contains the changed cell

### ISSUE THREAD

**Issue by pinuchfab** [handsontable/handsontable#7266]
### Description
Given three column A,B,C, I make a change on a cell in column A, then I move column A after B, then undo my change on A.
Expected: Cell in column A should be undone
Actual: Cell in column B is updated, A left as it is

### Steps to reproduce

1. make a change on a cell in column A
2. move column A after B
3. undo

### Demo
From any fiddle demo,
just add  manualColumnMove: true to grid seetings.

### Your environment
* Handsontable version: 8.0.0beta1
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by wojciechczerniak** [comment]
The problem is that  Undo doesn't work for moving columns #4846, the missing undo step should firstly move the column back, and then change would be applied for the right column.
