### ISSUE TITLE
Sticky row when sorting?

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#7267]
Hey team,

I've got a question about what the best way to implement something would be.

We've got a set of data that I want to be sortable, but I want a particular row to *always* be at the top (e.g. sticky), and I can't quite figure out how to get there.

I tried implementing my own global custom sorter, but the comparator only receives discrete values instead of entire rows. Without the row I can't figure out if that's the sticky row or not. 

We're currently swapping out my old custom vue table with HoT in another part of the app, so I've attached a gif of the functionality that I'm trying to replace.

Would be grateful for any ideas yall have!

Thanks

![Sep-10-2020 15-54-23](https://user-images.githubusercontent.com/881931/92804648-13b0bc80-f37e-11ea-8544-002fc9e6a381.gif)

**Comment by AMBudnik** [comment]
Hi @aarondfrancis 

Here's a demo that works with the latest version (8.0.0) https://jsfiddle.net/AMBudnik/hk0eos3g/

**Comment by wojciechczerniak** [comment]
@AMBudnik `executeBatchOperations` was renamed to `batch`. Demo was created for beta and we should recheck/update it.

**Comment by aarondfrancis** [comment]
Never would've figured this out myself... Thanks @AMBudnik and @wojciechczerniak, this is totally perfect!

**Comment by aarondfrancis** [comment]
💥  Plugin time!

```js
import PluginFactory from './plugin-factory';

let StickyRows = PluginFactory('stickyRows');

StickyRows.prototype.enable = function () {
    this.handleHook('afterColumnSort');
    this.handleHook('afterFilter');
}

StickyRows.prototype.stickyKey = function () {
    return this.getSettings()['key'] || '_sticky';
}

StickyRows.prototype.getStickyRows = function (visual) {
    return this.hot.getSourceDataAtCol(this.stickyKey())
        .map((sticky, index) => {
            if (!sticky) {
                return false;
            }

            return visual ? this.hot.toVisualRow(index) : index;
        })
        .filter(index => index !== false);
}

StickyRows.prototype.getVisualStickyRows = function () {
    return this.getStickyRows(true)
}

StickyRows.prototype.getPhysicalStickyRows = function () {
    return this.getStickyRows(false)
}

StickyRows.prototype.afterColumnSort = function () {
    this.hot.rowIndexMapper.moveIndexes(this.getVisualStickyRows(), 0);
}

StickyRows.prototype.afterFilter = function () {
    let map = this.hot.getPlugin('filters').filtersRowsMap;

    // When we upgrade to 8.0.0 this has been renamed to `batch`.
    // https://github.com/handsontable/handsontable/issues/7267
    this.hot.executeBatchOperations(() => {
        this.getPhysicalStickyRows().forEach(index => {
            map.setValueAtIndex(index, false);
        });
    });
}

export default StickyRows;
```

**Comment by carterax** [comment]
@aarondfrancis would be helpful if you could please share us your plugin factory.
