### ISSUE TITLE
How to expand the content menu to allow me to enter the specified number and start button

### ISSUE THREAD

**Issue by MulderLiu** [handsontable/handsontable#7268]
### Description

我想扩展一下右键菜单，可以让我输入指定的数字后，新增我指定数字的行数，现在遇到的问题是一旦设置了iscommad：false go按钮就不起作用，iscommad：true 时，无法输入数字

I want to expand the right-click menu to allow me to input the specified number and add the number of rows I specify. The problem now is that once the iscommad: false go button is set, it will not work. When iscommad: true, the number cannot be entered

### Demo

https://jsfiddle.net/3qrpj20e/1/

**Comment by AMBudnik** [comment]
Hi @MulderLiu 

Here's a demo https://jsfiddle.net/gfrytsou/ We've added `event.preventDefault` method to avoid closing the menu too soon.

**Comment by MulderLiu** [comment]
hi @AMBudnik  Thanks for your help, I implemented this function and improved it a little bit https://jsfiddle.net/dgsw8qbv/1/
