### ISSUE TITLE
When all cells are selected the isSelectedByRowHeader value is not updated

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7271]
### Description

When all cells are selected the `isSelectedByRowHeader` value is not updated.

### Steps to reproduce

1. Open the console to check what's printed
2. Use CMD/CTRL + A to select all the cell
3. Use RMB on row header 2 (index 1)

**Result**
You see an option that should not be visible for this row
![Zrzut ekranu 2020-09-14 o 14 16 54](https://user-images.githubusercontent.com/10757813/93084855-fab54d80-f694-11ea-86d5-6cb11ff84677.png)

**Expected result** (the one you get if you skip step 2)
You do not see the option that is not visible for that row.
![Zrzut ekranu 2020-09-14 o 14 17 52](https://user-images.githubusercontent.com/10757813/93084921-17ea1c00-f695-11ea-9605-eadc3443adca.png)

You can see that it doesn't matter how many times you open the context menu for row `1` you always get `false` in the console as a result of the `isSelectedByRowHeader()` check.

### Demo

https://jsfiddle.net/AMBudnik/3q0d2go5/ 8.0.0 (broken)
https://jsfiddle.net/AMBudnik/s4ua8mec/ 7.4.2 (broken)

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Chrome 85
* Operating System: macOS Catalina 10.15.6

**Comment by wojciechczerniak** [comment]
RMB on selected range doesn't change the selection. The selection was made earlier and not `byRowHeader`.

If you select something by CMD/CTRL + A then the selection is made by both, row and column, headers. `isSelectedByRowHeader` is `true` only when the selection was made by row header.

Not a bug.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/7272
