### ISSUE TITLE
When we use RMB on a cell from the same row that the header the isSelectedByRowHeader value is not updated

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7272]
### Description

When we use RMB on a cell from the same row that the header the `isSelectedByRowHeader` value is not updated.

### Steps to reproduce

1. Open the console
2. Use RMB on 2 row header (index 1)
3. Use RMB on cell `F2`

**Result**
You see 'Custom option 1' in the menu
![Zrzut ekranu 2020-09-14 o 14 29 45](https://user-images.githubusercontent.com/10757813/93086043-cb9fdb80-f696-11ea-97f8-5fd65c920330.png)

**Expected result**
You see 'No available options'
![Zrzut ekranu 2020-09-14 o 14 30 24](https://user-images.githubusercontent.com/10757813/93086090-deb2ab80-f696-11ea-828e-c2a45366e930.png)

You can see that it doesn't matter how many times you open the context menu for cells in the 2nd row (index 1) you always get `true` in the console as a result of the `isSelectedByRowHeader()` check.

### Demo

https://jsfiddle.net/AMBudnik/3q0d2go5/ 8.0.0 (broken)
https://jsfiddle.net/AMBudnik/s4ua8mec/ 7.4.2 (broken)

### Relates issues
* https://github.com/handsontable/handsontable/issues/7271

### Your environment
* Handsontable version: Handsontable 8.0.0
* Browser Name and version: Chrome 85
* Operating System: macOS Catalina 10.15.6

**Comment by wojciechczerniak** [comment]
Same as #7271, this is how the selection should work. When something is selected then RMB is not changing the selection. The context menu opens for the already selected range. Otherwise, it wouldn't be possible to open a context menu for a range, it would reset instantly to a single cell.

Won't fix.

**Comment by AMBudnik** [comment]
Thank you for the clarification. Closing.
