### ISSUE TITLE
Extend batch method to suspend render

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#7274]
### Description
Version `v8.0.0` introduced `batch` method that suspends Index Mappers cache recalculation until all the changes are applied. This way heavy calculations are done only once. The same should apply to our `render()` pipeline. If multiple plugins or operations are called in sync, we only need to render the final output of their combined result. 

https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/core.js#L962-L978

There should be no magic though, so my proposal is to have a public API that the developer could use to further optimize their apps if they need to.

### API proposal

```tsx
class Core {
  private #renderSuspended = false;

  public isRenderSuspended() {
    return this.#renderSuspended;
  }

  public suspendRender() {
    this.#renderSuspended = true;
  }

  public resumeRender() {
    this.renderSuspended = false;
    this.render();
  }

  public batch(callback) {
    this.suspendRender();

    callback();

    this.resumeRender();
  }

  public render() {
    if (!this.isRenderSuspendedn()) {
      // do the render stuff
    }
  }
}
```

#### How to use it

Simple public API

```tsx
hot.batch(function () {
  hot.alter('insert_row');
  hot.alter('insert_col');
  hot.getPlugin('columnSorting').sort();
});
```

Advanced public API

```tsx
hot.suspendRender();

hot.alter('insert_row');
hot.alter('insert_col');
hot.getPlugin('columnSorting').sort();

hot.resumeRender();
```

#### Internal ops

Batch will not have any impact on rendering time and layout trashing but it will reduce the number of render cycles for CRUD operations resulting in less layout trashing overall, less freezes, and a more responsive feel. We have to identify the places that will benefit from suspend/resume, some candidates are: `updateSettings`, `runHooks`, `init`, `undoRedo`. But we may update them in steps. Once we have the public API and it's tested we can optimize bottlenecks step by step.

Ref: 

Cells method calls renderer a couple of time for a single cell #5204

#### Plugins

Handsontable initialization should be a one `batch` op resulting in a single render when everything is good to go. Plugins are also reinitialized on `updateSettings` so this change will improve it's performance as well (`updateSettings` is used by framework wrappers, a bottleneck for reactivity).

Ref: 

Merge cells plugin does not work in the initial render #7164

#### UndoRedo

Each Undo or Redo action can combine multiple operations. For example, if the user removed a few columns, the undo action have to:

- add the columns back
- restore data in the columns
- restore meta-data for the columns and cells
- set the selection

Each individually may call a `render()` to display the results, but we're interested only in the final result for all of them combined, a restored state from before the user action.

Ref:

[https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/plugins/undoRedo/undoRedo.js#L388-L390](https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/plugins/undoRedo/undoRedo.js#L388-L390)

To name one. But there are more brutal examples (notice the additional render at the end):

[https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/plugins/undoRedo/undoRedo.js#L475-L515](https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/plugins/undoRedo/undoRedo.js#L475-L515)

#### User (developer)

During the development, whenever custom actions are needed, the developer may batch the API calls and limit the render cycles to a minimum.

### Hooks

It might be a good idea to extend suspending/resuming with hooks.

```tsx
  suspendRender() {
    this.renderSuspended = true;
    this.runHooks('renderSuspended');
  }

  resumeRender() {
    this.renderSuspended = false;
    this.runHooks('renderResumed');
    this.render();
  }
```

For example, HyperFormula has it's own mechanism for suspending evaluation, this way we can sync both:

```tsx
// formulaPlugin.js
this.hot.addHook('renderSuspended', () => { 
  this.hyperformula.suspendEvaluation();
});

this.hot.addHook('renderResumed', () => { 
  this.hyperformula.resumeEvaluation();
});
```

### Be aware

Some plugins may not be ready for this approach and written to relay on the render output. Those plugins should be refactored which may be additional work.

The current `batch` method was created to suspend IndexMappers cache updates. We have to figure out how those should work with suspending rendering as well. Especially check if there are use cases where we want to suspend render but not recalculation.

We can solve this by splitting suspend/resume for render and calculation (currently I don't have better names, although recalculation sounds more like formulas, not index mappers)

```tsx
hot.suspendRecalculation();

// do index mappers operations

hot.resumeRecalculation();
```

And batch would use both:

```tsx
  batch(callback) {
    this.suspendRender();
    this.suspendRecalculation();

    callback();

    this.resumeRecalculation(); // + recalculate index mappers cache
    this.resumeRender();
  }
```

But if someone needs to control the flow precisely, the `suspendRecalculation` / `resumeRecalculation` and `suspendRender` / `resumeRender` should handle those use cases well.

**Comment by aarondfrancis** [comment]
I liked this idea so much I made a quick and dirty version and monkey-patched it in for now!

```js
hot.suspend = function (cb) {
    // Cache the real render function.
    let render = hot.render;

    // Set up a counter.
    let missed = 0;

    // Anytime HoT tries to render, just record it.
    hot.render = () => missed++;

    // Batching suspends index thrashing while
    // we're executing the developer's actions.
    hot.batch(cb);

    // Restore the real render function.
    hot.render = render;

    return missed;
}
```

**Comment by wojciechczerniak** [comment]
@aarondfrancis When you do it, it looks so easy 😄 How does it work for you? Any noticable perf improvement?

**Comment by aarondfrancis** [comment]
Ha, because I only have to worry about _my_ use case, yall have to worry about _every_ use case!

> How does it work for you? Any noticable perf improvement?

It works great so far. I'm working on a "Saved View" feature so that users can save and re-apply filters, column sorting, and shown/hidden columns all at once. (Kind of like Google Sheets has.) Based on what the user has saved, I'm able to skip about 5-7 renders by suspending until all the parts of the saved "view" are applied.

The saved milliseconds are nice, but it's also nice to not have the table "jump" around as it's applying different parts. It just "snaps" once it's done.

**Comment by wojciechczerniak** [comment]
Thanks! We observe a 3x boost #7406. 
 
There were some questions  #7408 that we can close 

#### Internal uses

Looks like initialization, `loadData`, and `updateSettings` are already optimized. No boost here. 🤞 for `undoRedo`


#### `silentMode`

We will be able to remove `silentMode` from `setSourceDataAtCell`. It was private and used only internally.
https://github.com/handsontable/handsontable/blob/34793d5e9ee10176941ebe2589996daa80b5effd/src/core.js#L2455

The correct use will be:
```ts
instance.suspendRendering();
instance.setSourceDataAtCell( ... );
instance.resumeRendering();
```

And here, one change from the original spec that @budnix made, `resumeRendering` is not calling a `render`. Without that change, the code above would not be possible.

**Comment by aarondfrancis** [comment]
Ok the way you've implemented nested suspended rendering is genius and elegant.

https://github.com/handsontable/handsontable/commit/275a0470e1b6c3253a166fb892ec4e5662145866#diff-8ab41fe13597e1554b5d6b4c227b5f123ff2d6726a7f3688a8b8d1224fe1d4f3R1687-R1691

**Comment by aninde** [comment]
The tests showed no other bugs. 
You can find the description of the tests [here](https://github.com/handsontable/quality/issues/85#issuecomment-768974154).

**Comment by AMBudnik** [comment]
I'm happy to close this issue as a result of adding this functionality to Handsotable v.8.3.0

If anyone would be interested in learning more about it feel free to send us a message at support@handsontable.com 

ps. thank you @aarondfrancis for your encouragement and belief :-)
