### ISSUE TITLE
[8.0.0] Resizing browser vertically doesn't trigger render

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#7285]
Hey yall 👋 

I'm in the process of migrating from 8.0.0-beta1 to 8.0.0 (!!) and noticed an issue that when the browser is resized *only* vertically, the render method is not fired which means the browser might be too short to display the contents of the table.

FYI It appears to be the same in beta1 as it is in 8.0.0.

### Steps to reproduce
Go to https://jsfiddle.net/68fuchb4/3.
Resize from the bottom up until some of the rows are no longer visible. 
Try to scroll and note that you can't.
Resize width.
Note the `rendered!` console comment, and the fact that you can scroll now.

I've attached a video. It's hard to tell that I'm trying to scroll after the vertical resize... but I am!

![Sep-23-2020 17-44-02](https://user-images.githubusercontent.com/881931/94080485-69e11f00-fdc4-11ea-83ff-d5a3a4816e63.gif)

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Chrome
* Operating System: OS X

**Comment by AMBudnik** [comment]
Hi @aarondfrancis 

Thank you for sharing the demo. I've replicated the issue.

It seems that the CSS - tailwind does not cooperate well with Handsontable CSS settings. If we remove it table scrolls as expected. I guess that it might be related to some `overflow` settings. Simply changing the order of resources did not work so maybe there are some CSS changes that are overwriting what's already set by Handsontable.

When it comes to the call to renderer when I change no of rows to 220 instead of 22 I get the logs.

**Comment by aarondfrancis** [comment]
Thanks for the response @AMBudnik.

In this case, Tailwind is just a simple way to apply some pretty standard css. The demo css is the same as the demo here: https://github.com/handsontable/handsontable/issues/6452.

We put the grid inside of a flex container so that we can mimic a Google Sheets style experience with a menu at the top and a footer at the bottom of the screen, and then have *only* the grid be scrollable.

With regard to the 220 instead of 22, you still get the issue but it's actually more pernicious. If you start with a tall screen with 220 rows and then shrink it down vertically, you won't be able to scroll to row 220, because the table hasn't re-rendered to account for the new height, so it thinks it *is* showing you all the rows.

Hope that helps clarify!

**Comment by wojciechczerniak** [comment]
@aarondfrancis You have to set `height: "100%"` so Handsontable height is controlled by the flex container: https://jsfiddle.net/78L0vwdn/ In the default `height: "auto"` mode Handsontable is forcing the height based on its content.

**Comment by aarondfrancis** [comment]
@wojciechczerniak right you are, that totally fixed it. Thanks for the help, I didn't know about the `height: 100%` trick.

Here's my "app" layout skeleton (fixed header & footer) with the 100% tip solving the problem: https://jsfiddle.net/q02kxe51.
