### ISSUE TITLE
Misleading activating the htFiltersActive` class as if we had filters enabled when we cannot use them.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#7291]
### Description
When we try to filter and at the same time we return false in the `beforeFilter` hook filtering is applied. This is the desired behavior. 
Nevertheless, after this operation, we have a green color to indicate that filters are activated. 

<img width="556" alt="Zrzut ekranu 2020-09-25 o 14 56 04" src="https://user-images.githubusercontent.com/1555809/94269698-4b536300-ff3f-11ea-8ead-c75ed3d61ec6.png">
<img width="404" alt="Zrzut ekranu 2020-09-25 o 14 43 47" src="https://user-images.githubusercontent.com/1555809/94269441-f283ca80-ff3e-11ea-8e59-d9faa0471332.png">

### Demo

https://jsfiddle.net/xv3p4jcr/

### Your environment
* Handsontable version: 8.0.0.
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
This one is already reported @pnowak https://github.com/handsontable/handsontable/issues/6558
