### ISSUE TITLE
[8.0.0] Can no longer subclass plugins

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#7293]
### Description
Alright, we're really getting into the weeds now. One of my last steps in my 8.0.0-beta1 --> 8.0.0 migration is is to migrate my custom search plugin. 

In `beta1` I was able to use my [plugin factory](https://github.com/handsontable/handsontable-skeleton/issues/6#issuecomment-674196068) to extend either the BasePlugin or any of y'alls first party plugins. 

Now with the release of 8.0.0 I'm no longer to extend the Search plugin. I haven't tested on any other first party plugins. It appears that the `hot` getter is now returning `undefined` instead of the hot instance.

I've looked through [the diff](https://github.com/handsontable/handsontable/compare/8.0.0-beta.1...8.0.0) and don't see any changes to the base plugin or the search plugin that tip me off. 

I tried manually setting the `hot` variable in the constructor, but it's a read-only getter.

I tried passing the `hotInstance` variable to the `getSettings` call, but that just leads to another error, since `hot` is returning undefined elsewhere.

### Steps to reproduce

https://jsfiddle.net/t92whpkc/

1. Run the fiddle, note the console statements.
2. Comment out the beta1 script, switch to 8.0.0.
3. Run again, note the errors.

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Chrome
* Operating System: OS X

**Comment by aarondfrancis** [comment]
I've got this narrowed down to a single failing commit, but not sure where to go from there.

The first commit that causes this failure is https://github.com/handsontable/handsontable/commit/0b23fea4b75adf9e2f2abdb57bc12daefd4a36e6.

I manually bisected my way to this commit and it seems like the source of this particular error is that the outputs of the build directory have changed quite a bit. 

I grabbed the last working `commonjs` folder and the first broken `commonjs` build and diff'ed the two. (I built using `cd node_modules/handsontable && npm install && npm run build:commonjs`).

Here is one screengrab from `plugins/search/search.js`, https://github.com/handsontable/handsontable/commit/efa806df7c46bcd563177cf008d25352ca34b40c is on the left and https://github.com/handsontable/handsontable/commit/0b23fea4b75adf9e2f2abdb57bc12daefd4a36e6 is on the right.

![image](https://user-images.githubusercontent.com/881931/94469993-9d3cf880-018c-11eb-96a4-66906bde1786.png)


Here is the diff from earlier in the file that contains the referenced functions (`getPrototypeOf` and `_createSuper`)

![image](https://user-images.githubusercontent.com/881931/94470250-04f34380-018d-11eb-9be9-cdc7f5078833.png)


So it looks like somewhere one of the transpilation steps changed how they are doing subclassing. I'm not enough of a javascript expert to know how to fix this. Do y'all have any ideas?

**Comment by AMBudnik** [comment]
Thank you for sharing the results of your findings. I mean.. wow! You've made an amazing job to get to the bottom of the issue. 

We had a quick chat on those results and we have some ideas but before the release (we're in a middle of a code freeze) we won't have much time to share the most-effective approaches (only some rough ideas). Nevertheless, we should discuss the subject sooner than later.

**Comment by aarondfrancis** [comment]
Ha well I knew this was an obscure one, and I've maintained repos where people just say "It doesnt work!!11!!" and I know how frustrating that is :D 

Any crazy ideas yall have I'd be willing to try out, this is the last thing keeping us from merging our 8.0.0 upgrade branch! Feel free to drop unformed hypothesis here and I can run them down.

**Comment by aarondfrancis** [comment]
I think I've stumbled across a solution, although I'm not sure exactly _why_ it's working. 

In my old factory, I was doing this: 

```js
let plugin = function (hotInstance) {
    // Call the BasePlugin constructor.
    parent.call(this, hotInstance);

    this.optionalCall('setup')

    this._superClass = parent;

    this.settings = this.getSettings();
}
```

In the new one, apparently `parent.call` can return an object _if_ you're extending a plugin that's not the BasePlugin. So now we capture the returned object and use is as the `this` object.

```js
let plugin = function (hotInstance) {
    // Call the BasePlugin constructor.
    let _this = parent.call(this, hotInstance) || this;

    _this.optionalCall('setup')

    _this._superClass = parent;

    _this.settings = _this.getSettings();

    return _this;
}
```

Not sure why the transpiler was changed, but this seems to be working. If yall have any better ideas or warning about this, please let me know.

**Comment by swistach** [comment]
It seems to be a change in `@babel/plugin-transform-classes`, a required dependency for `@babel/preset-env`.

| Handsontable version | uses |
|----|----|
|8.0.0-beta.1 | `@babel/plugin-transform-classes@7.7.0` |
|v7.4.2 | `@babel/plugin-transform-classes@7.8.3`|
|v8.0.0 |  `@babel/plugin-transform-classes@7.10.4`|

and here is a list of RN in [https://github.com/babel/babel](https://github.com/babel/babel) repository, with any reference to `babel-plugin-transform-classes`:
- https://github.com/babel/babel/releases/tag/v7.8.4
  - Here, https://github.com/babel/babel/pull/11049 might be related.
- https://github.com/babel/babel/releases/tag/v7.8.6
  - Here, https://github.com/babel/babel/pull/11134 might be related.
- https://github.com/babel/babel/releases/tag/v7.9.0
  - Here, https://github.com/babel/babel/pull/8656 might be related.
- https://github.com/babel/babel/releases/tag/v7.9.2
  - Here, https://github.com/babel/babel/pull/11298 might be related.
- https://github.com/babel/babel/releases/tag/v7.9.5
  - Here, https://github.com/babel/babel/pull/11341 might be related. 
  - Here, https://github.com/babel/babel/pull/11358 might be related. 
- https://github.com/babel/babel/releases/tag/v7.9.6
  - Here, https://github.com/babel/babel/pull/11401 might be related. 
  - Here, https://github.com/babel/babel/pull/11480 might be related.
- https://github.com/babel/babel/releases/tag/v7.10.0
  - Here, https://github.com/babel/babel/pull/11514 might be related.

I hope it might help to investigate if it's something we can fix/change or it's babel's issue or it's nothing we would like to touch.
I think we could consider releasing pure package, without polyfills, just to let end-developers decide what they wont to use.
