### ISSUE TITLE
An error occurs when using trimRows by API.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#7303]
### Description

If we use trimRows method like trimRowsPlugin.trimRow (1, 2, 9); - the  `Cannot read property 'getTrimmedIndexes' of null`  error is thrown.

In the previous version - `7.4.2` - the error doesn't occur.
Here is a demo for `7.4.2` - https://jsfiddle.net/aeh61oxy/.

### Steps to reproduce

1. Go to the demo - https://jsfiddle.net/s1j7xvzp/.
2. Open the console.

### Demo

https://jsfiddle.net/s1j7xvzp/

### Your environment
* Handsontable version: 8.0.0.
* Browser Name and version:
* Operating System:

**Comment by swistach** [comment]
Actually, it's expected behaviour.
Before v8, `trimRows` have been allowing using its API without enabling it because of the fact as `Filters` needed it.
After v8, we create `indexMapper` only if `enablePlugin()` was called.
