### ISSUE TITLE
Cancelling trimRows in beforeTrimRow hook doesn't stop the execution of the operation.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#7304]
### Description

Even if we're cancelling trimming rows in the beforeTrimRow hook (by returning false) that action is performed in the table dataset.
Furthermore, the hook `beforeTrimRow` doesn't be called.

It could be related to https://github.com/handsontable/handsontable/issues/7303

### Steps to reproduce

1. Go to the demo - https://jsfiddle.net/w5hLs328/. As you can see, the table has an 8 (not 10) rows.

### Demo

https://jsfiddle.net/w5hLs328/

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version:
* Operating System:

**Comment by swistach** [comment]
Accordingly to the release notes of v7, `beforeTrimRows` hook is present since that version. I checked the behaviour you describe above and is the same as in 7.0.0.
I know that `manual*Move` calls its hooks at initialization, but this inconsistency should be discussed in the core team.
