### ISSUE TITLE
[8.1.0] Horizontal Scroll Causes Headers to Slip

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#7306]
### Description
When scrolling a table horizontally, the headers become misaligned.

Here's a gif from the fiddle:

![Oct-01-2020 11-58-01](https://user-images.githubusercontent.com/881931/94840161-9d800280-03dd-11eb-9b1c-a165e3d6a615.gif)

And a gif from our app, where it seems markedly worse:

![Oct-01-2020 12-00-41](https://user-images.githubusercontent.com/881931/94840274-ca341a00-03dd-11eb-8ac1-a7959dadd898.gif)

### Steps to reproduce
1. https://jsfiddle.net/45d6cgem/
2. Scroll left and right

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: Chrome Latest
* Operating System: OS X

**Comment by aarondfrancis** [comment]
It appears it can cause the row headers to slip as well. These don't bounce back like the column headers do:

![image](https://user-images.githubusercontent.com/881931/94840949-ed12fe00-03de-11eb-9c56-d563ac82c693.png)

**Comment by aarondfrancis** [comment]
I tested 8.1.0 on most recent Chrome (Version 85.0.4183.121 (Official Build) (64-bit)) and a few versions back (Version 83.0.4103.61 (Official Build) (64-bit)) and got the same issue. 

The column headers slipping is unsightly, but the row misalignment is a real problem, so we'll have to rollback to 8.0.0-beta1 unfortunately.

**Comment by AMBudnik** [comment]
Hi @aarondfrancis I'm also on the same Chrome version and macOS Catalina, and the 'jumping' behavior seems to be the same in 8.0.0 as it is for v 8.1.0. Do you experience different results for v 8.0.0?

Does the demo with the checkboxes and the mentioned effect

> row headers to slip as well. These don't bounce back

is also replicable if you remove the checkboxes?

**Comment by aarondfrancis** [comment]
@AMBudnik no I get the same behavior on 8.0.0 as 8.1.0, but 8.0.0-beta1 doesn't suffer. That's what we rolled back to.

I'll see if removing all custom renderers has any effect.

**Comment by wojciechczerniak** [comment]
I've checked both versions, beta nad 8.1, and both look the same. There is a slight delay on both. Scroll events are more and more passive and this depends on other computations. Which method do you use to scroll? Scrollbar, mouse wheel, touchpad?

In the second example there is a corner missalignment. Might be a reason why row headers are shifted. Can you reproduce this as jsfiddle?

![94840949-ed12fe00-03de-11eb-9c56-d563ac82c693](https://user-images.githubusercontent.com/4718998/94932948-08a70300-04ca-11eb-828c-4a41375a0ce0.png)

**Comment by aarondfrancis** [comment]
I think you're right re: the horizontal slippage. I just tried it on beta1 and it does look to be pretty much the same. I guess I just never noticed it there and did notice it when I was checking it out after upgrade. 

Scrolling via magic mouse causes them to slip pretty badly, scrolling via scrollbar drag is totally fine. Do you know of anything I can try to improve that?

The persistent vertical misalignment seems to be caused by my custom headers.

I think the first argument of the `afterGetColumnHeaderRenderers` changed from `visual` column to `rendered` column and I didn't fully carry through the change to account for the top left corner element.

So it seems like a classic case of upgrading and 1) seeing old problems as new and 2) seeing my problems as library problems. Sorry!

I would be interesting in seeing the horizontal scroll improve, but since it's the same as beta1, I think I can re-merge the 8.1.0 upgrade.

I'll go ahead and close this since it's not really a bug in any way

**Comment by wojciechczerniak** [comment]
> Scrolling via magic mouse causes them to slip pretty badly, scrolling via scrollbar drag is totally fine. Do you know of anything I can try to improve that?

Unfortunately no. One layer has to be updated with the scroll position after the other emits an event. While the scrollbar works ok, wheel events Chrome switched to passive mode hence the delay. Most of our ideas were blocked by IE. I hope we can go back to the drawing board soon.

> I think the first argument of the `afterGetColumnHeaderRenderers` changed from `visual` column to `rendered` column and I didn't fully carry through the change to account for the top left corner element.

The code has changed. Hidden columns are no longer rendered. But it should be translated from `rendered` to `visual`.
https://github.com/handsontable/handsontable/commit/5a1457f9e869b2be1cb6041ddb9c1eba38bec5e3#diff-24033f033992c272cc008ff988b20046R418-R423
May we have an unintended breaking change here @wszymanski ?

**Comment by aarondfrancis** [comment]
Thanks for the explanation, that's helpful.

> Most of our ideas were blocked by IE. 

_pretends to be surprised_

**Comment by aarondfrancis** [comment]
> Most of our ideas were blocked by IE.

@wojciechczerniak are there any Chrome-only workarounds I can implement on my side in the meantime? We mandate all of our employees use Chrome.

**Comment by wszymanski** [comment]
> The code has changed. Hidden columns are no longer rendered. But it should be translated from `rendered` to `visual`.
> [5a1457f#diff-24033f033992c272cc008ff988b20046R418-R423](https://github.com/handsontable/handsontable/commit/5a1457f9e869b2be1cb6041ddb9c1eba38bec5e3#diff-24033f033992c272cc008ff988b20046R418-R423)
> May we have an unintended breaking change here @wszymanski ?

Unfortunately, it looks like it.

**Comment by wojciechczerniak** [comment]
> > Most of our ideas were blocked by IE.
> 
> @wojciechczerniak are there any Chrome-only workarounds I can implement on my side in the meantime? We mandate all of our employees use Chrome.

@aarondfrancis Sorry, no workarounds. Fixes were deep in Walkontable, changing overlays management and events/sync between them.


> > The code has changed. Hidden columns are no longer rendered. But it should be translated from `rendered` to `visual`.
> > [5a1457f#diff-24033f033992c272cc008ff988b20046R418-R423](https://github.com/handsontable/handsontable/commit/5a1457f9e869b2be1cb6041ddb9c1eba38bec5e3#diff-24033f033992c272cc008ff988b20046R418-R423)
> > May we have an unintended breaking change here @wszymanski ?
> 
> Unfortunately, it looks like it.

@wszymanski Should it work like that or is it a bug? Can you report an issue then?

**Comment by wszymanski** [comment]
> @wszymanski Should it work like that or is it a bug? Can you report an issue then?

It seems that Walkontable (which doesn't have information about translations and performs operations on renderable indexes) base on the `columnHeaders` method (defined within showed above `tableView.js` file). We can see below that every `draw` takes a result of the function defined within `columnHeaders`.

https://github.com/handsontable/handsontable/blob/a170795f4c105f09def906e26827c6c695f1af35/src/3rdparty/walkontable/src/table.js#L229

It's kind of internal thing, but we have a hook for that. Header renderers are created by a handled function, so probably we should leave it as it is (adding "extra layer" is impossible?). However, documentation for that could be clearer, and extra information in the breaking change section would be useful.
