### ISSUE TITLE
Improve the PR template with Contributing requirements

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7307]
### Description

We should improve the PR template with Contributing requirements. That is
* contributors should know about the guidelines when they submit a new PR
* contributors should know that they need to sign a CLA document

**Comment by aninde** [comment]
This is done and published https://github.com/handsontable/handsontable/blob/master/.github/PULL_REQUEST_TEMPLATE.md

I wonder if it is not worth adding information for which the development should be requested, not the domain. It seems obvious, but there are cases where users forget about it. Example: https://github.com/handsontable/handsontable/pull/7224
