### ISSUE TITLE
Misspelled typings, UndoRedo.doneAction

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#7312]
### Description
`Handsontable.UndoRedo.doneAction` seems to be misspelled and should be Handsontable.UndoRedo.doneAction**s**.
Related to (https://github.com/handsontable/angular-handsontable/issues/159).

### Demo

https://stackblitz.com/edit/handsontable-angular-argqrn?file=app%2Fapp.component.ts

### Your environment
* Handsontable version: 8.1.0

**Comment by AMBudnik** [comment]
Thank you for sharing the finding. You're right - there's a typo.
We've made a PR to fix it https://github.com/handsontable/handsontable/pull/7316

**Comment by aninde** [comment]
Present in v8.3.0 
https://github.com/handsontable/handsontable/blob/8b6e9c404ac0aa4fb211a6bedbd68b7fbd81c658/handsontable.d.ts#L1618-L1619

Closed #7312.
