### ISSUE TITLE
Cannot read property 'split' of undefined in issue template demo

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#7313]
### Description
Checking the console when opening the default JSFiddle example from the issue template and you'll get error messages:
 _Uncaught (in promise) TypeError: Cannot read property 'split' of undefined_

### Steps to reproduce

1. Open JSFiddle link
2. Check console output

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 8.1
* Browser Name and version: Chrome 85
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
In `_dist-linters.js`? It's not our file 😕 JSFiddle has its own problems.

**Comment by ottosson** [comment]
Oh! Sorry about that. I thought I checked and saw it in the HOT code. Closing 🤐

**Comment by wojciechczerniak** [comment]
> I thought "handsoncode" had something to do with handsontable! 

It has! It's our company and the jsfiddle account name :) And that's the reason why it's a part of the URL, but files are theirs anyway.

**Comment by ottosson** [comment]
Right! Sorry about the mix-up =P
