### ISSUE TITLE
[8.1.0] Index -1 when selecting row/column range

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#7314]
### Description
When I select an entire row or column I get -1 as row/col index. Not sure if this is intentional to indicate entire row/col selection?

Edit: I seem to have missed that part in the 7->8 migration guide. This is a bit awkward when working with ranges, as you have to check for -1 and modify the rangeObject everywhere. Or have I misunderstood/missed something?

### Steps to reproduce

1. Select row (click row/col header)
2. afterSelection event should have -1 as row/col

### Demo
https://jsfiddle.net/7vuqf128/

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: Chrome 85
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
It's intentional. We prefer to give more info to the developer and let him use it or drop it. Headers in Handsontable are indexed with negative numbers, so when their included in the selection you will have to normalize them if that information is useless to you `row = Math.max(0, row)`. It's harder to make it the other way round. If someone needs the info about headers, previously there were no way to get that information.

**Comment by ottosson** [comment]
Got it. Can I use CellRange.highlight to get the visually selected cells, which starts on index 0 if row/col has been selected?

**Comment by wojciechczerniak** [comment]
The highlight is used for drawing borders. Most of the time should be 1:1 with what you're looking for, but IMO, if something is for other purposes you can't be sure.

IRC `from` and `to` are `CellCoords` type and have `normalize()` method.
```
CellRange.from.normalize()
CellRange.to.normalize()
```
https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/3rdparty/walkontable/test/unit/cell/coords.spec.js#L5-L12

Or some handy helper on your side

**Comment by ottosson** [comment]
Normalize sounds like a good idea, but I don't see it on the Handsontable.wot.CellRange type and it throws a TypeError: `range.normalize is not a function`

```
interface CellCoords {
  col: number;
  row: number;
}

interface CellRange {
  highlight: CellCoords;
  from: CellCoords;
  to: CellCoords;
}
```
