### ISSUE TITLE
Improve definitions for `CellCoords` and `CellRange`

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7317]
### Description

In a reference to https://github.com/handsontable/handsontable/issues/7314 I request improving definitions for `CellCoords` and `CellRange `.

Definitions https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L199

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: n/a
* Operating System: n/a

**Comment by AMBudnik** [comment]
ps. we could also remove 'modifyRowSourceData' as this line has been added accidentally https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1905

**Comment by adrianszymanski89** [comment]
This issue seems to be no longer valid. `CellCoords` already have type definition for `normalize()` method. The only thing that is still present is an unnecessary type definition for `modifyRowSourceData` hook that no longer exists, so I will delete it.

**Comment by warpech** [comment]
Reopening as this should be closed only after the release of 12.1.3

**Comment by AMBudnik** [comment]
I'm closing this issue as done and released in Handsontable v12.1.3
