### ISSUE TITLE
Q: Possible to combine multiple actions into single undo/redo step?

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#7324]
As the title says, is it possible to combine multiple actions into a single undo/redo step?
I would very much like to be able to undo an insert_row alter, combined with populateFromArray, as they from a user perspective should be a single action.

**Comment by AMBudnik** [comment]
Hi @ottosson 

I am not sure if I understand. Could you share a demo and a step-by-step tutorial to define what behavior you'd like to change?

**Comment by ottosson** [comment]
https://jsfiddle.net/b76tLpkh/

Here you can see that the "Add row with content"-action has to be undone two times to be completely undone. The content and the row are undone in two steps now.

**Comment by AMBudnik** [comment]
I can see it now, thank you.

The subject of the undoing of grouped action was mentioned here https://github.com/handsontable/handsontable/issues/4030 
and then here https://github.com/handsontable/handsontable/issues/6731 we have an opened feature request for stacking actions.
I will make sure to update you once we add the support for https://github.com/handsontable/handsontable/issues/6731 
As this topic describes what's already mentioned in the above issue report and need to close it as a duplicate.

**Comment by ottosson** [comment]
Thanks! Looking forward to that feature.
