### ISSUE TITLE
rowHeights causes strange rendering bug

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#7325]
### Description
I tried to reproduce an issue I have in my Electron app where when I add rows between existing rows and scroll to the bottom, the last rows are missing, or at least not physically visible. It's only when I edit a cell that the table adjusts itself and I can see the missing rows. I have tried a manual render() after adding the rows, but that does not solve the problem.

When I try to recreate the issue in a jsfiddle I can't get the issue to appear, but I get another strange rendering bug instead, where the row numbers at the bottom of the table are missing. Maybe they are related somehow.

I think it has to do with the rowHeights setting, where the problem disappeared when I removed that setting.

I thought I should at least mention it to see if it is me who's doing something stupid or if it really is a bug.

### Demo

https://jsfiddle.net/y7r4ghw1/

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: Chrome 86
* Operating System: Windows 10

**Comment by aarondfrancis** [comment]
Ran into something similar the other day! Row heights have to be at least 23px (unfortunately).

See https://handsontable.com/docs/8.1.0/Options.html#rowHeights

**Comment by ottosson** [comment]
Oh! I seem to have missed that detail! Maybe it should notify/throw an error or something if wrong value has been set?

**Comment by AMBudnik** [comment]
Hi,

there's a note in the docs

> Height should be equal or greater than 23px. Table is rendered incorrectly if height is less than 23px.

but we should consider adding this message as a warning in the console.
