### ISSUE TITLE
Inserting 0 Rows Doubles the Filter's TrimMap Length

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#7326]
### Description
If you call `alter('insert_row', 0, 0)` the filter trim map unexpectedly doubles. Other maps might exhibit the same behavior.

I have no idea what it's doing or why, but it was _really_ throwing off some calculations for us for a while there. We now prevent against inserting 0 rows, but that doesn't seem like ideal behavior.

### Steps to reproduce
1. https://jsfiddle.net/md8L2xpt/
2. Observe the log statements

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: Chrome
* Operating System: OS X

**Comment by AMBudnik** [comment]
Thank you for sharing the finding, Aaron.

It seems that when we add 0 rows the map is bigger than when we add 1 row.

Calling

> hot.alter('insert_row', 0, 0);

4 times, give us `16` as a result of the map length. While calling

> hot.alter('insert_row', 0, 1);

4 times, gives us `5`.

**Comment by aninde** [comment]
Log statements from v8.1.0 are the same that log statments from upcoming v8.2.0. This is probably not the effect we were aiming for. @swistach WDYT?

**Demo**
https://jsfiddle.net/md8L2xpt/ v8.1.0
https://jsfiddle.net/aninde/7tsuykh5/1/ v8.2.0

**Comment by aarondfrancis** [comment]
❤️   Excellent, thanks for fixing!
