### ISSUE TITLE
Rubber band effect when scrolling between fixed columns and unfixed columns

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#7327]
### Description
When scrolling larger tables in my Electron application I get a strange rubber band like effect between the scrolling of fixed columns and unfixed columns. The same goes when I have no fixed columns but between row headers and table contents. It's more noticable on a high dpi monitor.

![hot_rubberband](https://user-images.githubusercontent.com/3355320/95556310-6b8d2280-0a13-11eb-846d-8667ecac9be4.gif)

I'm not able to reproduce the issue in a demo, but maybe someone can help me anyway.
This demo shows basically the same config as I'm using in my application: https://jsfiddle.net/284wgdos/

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: Chromium 85 (Electronjs 10)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @ottosson 

As I understand this only happens if you define Handsontable instance in the Electron? Do you have the same effect when you set up minimal settings (colHeaders, rowHeaders, helper for data creation)? Are you able to define what are the styles attached to the parent container of the Hot instance?

**Comment by ottosson** [comment]
Parent divs for the table is basically just a bunch of containers with height 100%

```
container {
  display: flex;
  flex-direction: column;
  height: 100%;
}
```

What I did notice though is that if I build the project (which is an Angular application) it's a lot less noticeable, and not really a problem anymore.

If I can recreate the issue in the browser I might open it up again. Until then, thanks!
