### ISSUE TITLE
 Header merge

### ISSUE THREAD

**Issue by tzwhyqq** [handsontable/handsontable#7331]
### Description

Why does the nestedHeaders attribute have no rowcol attribute, and there is no way to merge vertically if you want to merge
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:7.4.2
* Browser Name and version:edge
* Operating System:win10

**Comment by AMBudnik** [comment]
Hi @tzwhyqq 

this feature is not yet supported. Here's a reference issue https://github.com/handsontable/handsontable/issues/6553
I will make sure to ping you up when it's ready.
