### ISSUE TITLE
Failed to mimify npm run production

### ISSUE THREAD

**Issue by inicio015** [handsontable/handsontable#7343]
### Description

When I compile my project in laravel and vuejs in npm prod mode it throws me the following errors, when it is configured in developer it does not happen, obviously when it does not mimic, what could be happening?
in my instances I use this to fill the table that comes from php
      `this. $ refs.hotTableComponent.hotInstance.loadData (data);` 
### Steps to reproduce

1. DOMException: "Node cannot be inserted at the specified point in the hierarchy"
2. this.hotInstance is null
3. this.$refs.hotTableComponent.hotInstance is null

### Your environment
* Handsontable version:8.0.0
* Browser Name and version: Mozilla  / version73.0.1
* Operating System: Windows 7 64bit

**Comment by AMBudnik** [comment]
Hi @inicio015 

Could you send me the project zipped to support@handsontable.com ? I will build the app on my device and check what causes the issue.

**Comment by inicio015** [comment]
> Hi @inicio015
> 
> Could you send me the project zipped to [support@handsontable.com](mailto:support@handsontable.com) ? I will build the app on my device and check what causes the issue.

YES I already sent it

**Comment by AMBudnik** [comment]
I got the app and replied by email.
