### ISSUE TITLE
Row heights can't be smaller than 22 pixels 

### ISSUE THREAD

**Issue by SereneA** [handsontable/handsontable#7347]
### Description: Limit on row-height to 22 pixels 

In our project we have many grids designed and displayed on an in-house desktop application, we plan to display the same grids on browsers, however most of our grids are not being displayed correctly because of the limit of row height to 22 pixels.

Unfortunately, the problem is blocking because it's impossible for us to adjust all of our grids to take into account this limitation. And at the moment most of what we have already is highly impacted

Example:
![image](https://user-images.githubusercontent.com/73224573/96708006-e9004d80-1398-11eb-8a20-734d261001cb.png)

### Steps to reproduce
I don't believe the steps to reproduce are necessary, [problem has been previously identified,](https://github.com/handsontable/handsontable/issues/4021) please check 

![image](https://user-images.githubusercontent.com/73224573/96708258-3ed4f580-1399-11eb-9999-0bf3500f2248.png)

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: Firefox 81.0.1 (64 bits)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Welcome @SereneA 

I can see that you've quoted me. I guess that now we can update those examples with one that uses line-height for TDs http://jsfiddle.net/AMBudnik/au351vpb/ it makes the row with data as height as the content. As the content takes less space the height is not 22px it is 14px.

![Zrzut ekranu 2020-10-21 o 13 26 09](https://user-images.githubusercontent.com/10757813/96713505-ffaaa280-13a0-11eb-9b2a-0ed9337070ee.png)

You can set a smaller height to only some of the rows http://jsfiddle.net/AMBudnik/d05ktc23/ 

![Zrzut ekranu 2020-10-21 o 13 26 57](https://user-images.githubusercontent.com/10757813/96713594-1ea93480-13a1-11eb-9afe-51a441251861.png)


You also can cut the text visually by developing a custom renderer like here - http://jsfiddle.net/AMBudnik/ovcyxfL5/ 
![renderer-example](https://user-images.githubusercontent.com/10757813/96713272-9e82cf00-13a0-11eb-8d0c-a93ea54e1a78.gif)

Those are some of the methods that may or may not cover all the needs. Nevertheless, the quoted reply is a part of an issue that is still opened and we should avoid duplicating subjects. I need to close this ticket and keep the origin ticket opened. I will, however, make sure to update you once we provide a solid support for narrowing rows within https://github.com/handsontable/handsontable/issues/4021.
