### ISSUE TITLE
Numeric fields are not emptied when data function returns null – previous value persists.

### ISSUE THREAD

**Issue by craigmarvelley** [handsontable/handsontable#7349]
Hi, I have an issue with numeric fields when loading data in to the table.

### Description

I have a table with a column of cells of the numeric type. Sorting is enabled on the column, and my server handles the sort. When the response returns, I load the new data in to the table via `loadData`.

The column is set up to call a function to retrieve the data for each cell, and the function returns null if there is no data available for the row/cell in question.

It appears that when this occurs, the cell maintains the existing value from the previous load, rather than blanking it out.

If I return a default number, this gets applied. The issue is specifically caused by the data function returning null for a numeric field.

### Steps to reproduce
1. Set up a table with a numeric column which performs sorting on the server. The data for this table should be obtained via a function, like this:

```
const columnData = {
        data : this.dataForColumn( column ),
        type : 'numeric',
        readOnly : true
};
```

That function should check the object which corresponds to the row for a value for the numeric column, and return `null` if there is no value.

2. Perform sorting via AJAX. The data returned should consist of objects which have values for the numeric column in some cases, and undefined values for the others. 
3. Load the result in to the table via `loadData( results )`
4. Sort the table by the numeric column

### Demo
It's difficult to provide a demo because of the server-side element. Please contact me if you need more information.

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Safari 14.0
* Operating System: Mac OS

**Comment by AMBudnik** [comment]
Thank you for sharing the issue description @craigmarvelley 
Would you be able to replicate the same issue by emulating server response in a JSFiddle? I've made a starter that can help https://jsfiddle.net/AMBudnik/0vnz53rj/

**Comment by AMBudnik** [comment]
Hi @craigmarvelley 

as there is no reply further in this thread I need to close it.
Please feel free to update me on the subject on my email support@handsontable.com
