### ISSUE TITLE
[8.0.0+] maxCols/Rows with hiddenColumns/rows and larger dataset produces unexpected selection issues and table rendering

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7350]
### Description

`maxCols/Rows` with `hiddenColumns/rows` and larger dataset produces unexpected selection issues and table rendering. 

**Important**: It happens only when your dataset contains more rows and columns than defined by `maxCols` and `maxRows`.

#### Hide all the rows and columns 
0. We set up `maxCols: 5` and `maxRows: 5`, and hide 5 row and 5 columns 
1. Go to https://jsfiddle.net/AMBudnik/ae54b7fg/ (7.4.2) - it is ok, we cannot see any data
2. Go to https://jsfiddle.net/AMBudnik/7326rz5n/ (8.0.0) - you get the rest of the columns that were supposed to be blocked by maxCols / maxRows.

7.4.2 Result
![Zrzut ekranu 2020-10-23 o 10 07 50](https://user-images.githubusercontent.com/10757813/96973108-c21c5580-1517-11eb-8d63-3292b6d51096.png)

8.0.0 Result
![Zrzut ekranu 2020-10-23 o 10 09 08](https://user-images.githubusercontent.com/10757813/96973152-cea0ae00-1517-11eb-99aa-fb9499c4f635.png)

#### Hide some of the rows and columns 
0. We set up `maxCols: 5` and `maxRows: 5`, and hide 2 row and 2 columns 
1. Go to https://jsfiddle.net/AMBudnik/ae54b7fg/ (7.4.2) - it is ok, we the rest of the dataset (3 columns x 3 rows)
2. Go to https://jsfiddle.net/AMBudnik/3xp7qmrs/ (8.0.0) - you should see C, D, and E columns but we get 2 more; we should see 3 rows but we get 5.

7.4.2 Result
![Zrzut ekranu 2020-10-23 o 10 11 13](https://user-images.githubusercontent.com/10757813/96973474-3951e980-1518-11eb-87cc-c9446c206b7c.png)

8.0.0 Result
![Zrzut ekranu 2020-10-23 o 10 12 37](https://user-images.githubusercontent.com/10757813/96973527-4b338c80-1518-11eb-96cb-81f379be59aa.png)

### Additional complications
Not only rendering of the rows and columns is impaired, but we can also experience a lot of side effects.
* selection of headers is broken. Go to https://jsfiddle.net/AMBudnik/3xp7qmrs/ and select some row and column headers. Then try to use CMD/CTRL + A to select all
* selecting cells from rows that should not display produces console error `handsontable.full.js:16893 Uncaught TypeError: Cannot read property 'sourceToRendered' of null`
* context menu does not allow to add any columns
* editing cells in the unwanted cells is not saved
* while removing rows via context menu we still get new rows so it always equals 5
* you can hide rows and columns by context menu but you still get new rows and cols from your dataset. When you reach the last column/row from your dataset option for hiding does not work.
* removing all the columns does not work
![Zrzut ekranu 2020-10-23 o 10 23 44](https://user-images.githubusercontent.com/10757813/96974712-e6793180-1519-11eb-9562-49c90fd1e836.png)
![Zrzut ekranu 2020-10-23 o 10 23 51](https://user-images.githubusercontent.com/10757813/96974728-eb3de580-1519-11eb-841f-972c7354fd1c.png)

### Demo

https://jsfiddle.net/AMBudnik/5dr78L6y/ 8.1.0 - broken
https://jsfiddle.net/AMBudnik/djLsqf4u/ 8.0.0 - broken
https://jsfiddle.net/AMBudnik/Lmxjrtk0/ 7.4.2 - working well

### Your environment
* Handsontable version: 8.0.0+
* Browser Name and version: Chrome 86
* Operating System: macOS Catalina 10.15.6

**Comment by aninde** [comment]
This issue has been fixed by v8.3.2. The problems described in `Additional complications` are also out of date in v8.3.2

### Case 1
https://jsfiddle.net/gzcr8tey/
Result: maxCols/Rows are properly hidden when they should

<img width="76" alt="Screenshot 2021-03-10 at 16 45 30" src="https://user-images.githubusercontent.com/30186818/110656266-1458cd00-81c0-11eb-830d-1cbe5f265300.png">


### Case 2
Result: proper columns C, D, and E are visible
https://jsfiddle.net/7xwsgek0/

<img width="238" alt="Screenshot 2021-03-10 at 16 48 31" src="https://user-images.githubusercontent.com/30186818/110656704-7a455480-81c0-11eb-8436-c6f5c882ca34.png">

**Comment by AMBudnik** [comment]
That was an interesting regression. Thank you, @wszymanski, for fixing and @aninde, for testing 🥇
