### ISSUE TITLE
[8.1.0] Error in console when filter is active and summary is set

### ISSUE THREAD

**Issue by DevilWarrior** [handsontable/handsontable#7352]
### Description
I have a summary row added on my table (row 0) when a filter is applied to a column and the summary row is hidden (did not match criteria) trying to update the column with a new value raises an Assertion error.

`Uncaught Error: Assertion failed: Expecting an unsigned number.`

### Steps to reproduce
1. Set a column summary
2. Set a filter on a different column so that it hides the summary row
3. Add a new value to the column with summary

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: FireFox 81.0.1 | Chrome 86.0.4240
* Operating System: OSX | WIN

**Comment by AMBudnik** [comment]
Hi @DevilWarrior 

Thank you for sharing the issue report. I am trying to replicate the same on my device but I'm not notified about any errors in the console.

Here https://jsfiddle.net/AMBudnik/ypuhfn7o/ I've made a demo with SUM summary on the `B` column. I've opened the demo on my Chrome 86 on macOS Catalina 10.15.7 and hide value `11` from the `B` column. Then changed some data and returned `11`. No matter which row I hide there's no error.

Are you able to replicate the same issue using my demo or should I add anything more to the settings?

**Comment by DevilWarrior** [comment]
I'm using a function for the column summary, could that be the issue? Leaving it here:

```
const snaps_build_column_summary = () => {

    let summary = [];

    let col = (__COL_LINE_COST__);
    while (col < __COL_TABLE_END__) {
        const col_sum = {
            destinationRow: 0,
            destinationColumn: col,
            type: 'custom',
            forceNumeric: true,
            suppressDataTypeErrors: false,
            customFunction: (endpoint) => {
                if (__summary_enabled__ == false) return;
                const handsome_instance = __snapshot_handsome__;
                if (handsome_instance) {
                    const column = endpoint.sourceColumn;
                    return snaps_find_column_total(column, handsome_instance);
                }
            }
        };
        col++;
        summary.push(col_sum);
    }
    return summary;
}
```

**Comment by DevilWarrior** [comment]
To expand a bit more, the regular summary doesn't work on my end since since I need to summary on the top and the default 'sum' takes the summary row itself into consideration, hence I have the function "snaps_find_column_total" to grab the values of the column for me and figure out weather I should add them or not. this also checks a "status" columns on the table to know weather I should add the value or not.

**Comment by DevilWarrior** [comment]
Here's a screenshot of the error

![Screen Shot 2020-10-26 at 2 07 23 PM](https://user-images.githubusercontent.com/11341203/97210866-93f77980-1794-11eb-9291-e32664045f3b.png)

**Comment by AMBudnik** [comment]
Hi @DevilWarrior 

could you pass those custom settings to my demo? There are too many variables that haven't been described to tell if that piece of code is responsible for the error.
You can also check if using 'true' for 'suppressDataTypeErrors' changes anything.

**Comment by DevilWarrior** [comment]
HI, sorry for the delayed response, I have made a JSFiddle to show the issue, (see link below). To replicate the issue:

* Update any value on either the ABC or DEF columns to see the summary properly working
* Set a filter on either the STATUS or VOLUME column by condition "Is not empty"
* Now try to update either of the columns ABC or DEF again, you shall see a "script error" con the console

https://jsfiddle.net/390o2m57/4/

**Comment by AMBudnik** [comment]
Thank you for sharing the demo. The biggest issue seems to be the fact we want to place a value in a row that is not visible. Do you plan to allow filtering out the row with summaries? Cause that can be blocked by the `beforeFilter` hook.

**Comment by DevilWarrior** [comment]
@AMBudnik Sure, I would actually prefer to show the top summary row regardless of filtering, you mentioned the `beforeFilter` can you point me in the right direction for how to archive this? I've read the [documentation](https://handsontable.com/docs/8.1.0/Hooks.html#event:beforeFilter) but it's a bit unclear for me still.

**Comment by AMBudnik** [comment]
That's totally true, the `conditionStack` of the [`beforeFilter` hook](https://handsontable.com/docs/8.1.0/Hooks.html#event:beforeFilter) looks complex. But there's a pattern. I'm not sure if that would cover all the cases but I would start with something like this https://jsfiddle.net/xfLq4w2j/
This code blocks an operation when a User tries to filter out the "" which is a blank row. Would that suit your use case, @DevilWarrior?

**Comment by DevilWarrior** [comment]
Actually this would not work necessarily since one of the filters used the most is (is_not_empty), I actually need to just need to always skip row at index 0 regardless of filter match. Would this be possible to catch on `beforeFilter`?

**Comment by AMBudnik** [comment]
Hi @DevilWarrior 
I've chatted with our Support Engineer about this subject and he sent me this demo https://jsfiddle.net/52g97hrp/

**Comment by DevilWarrior** [comment]
Hi, thanks for looking into this, this somewhat works but it's kind of hacky. It does works but then when re-setting the filter it does create yet another row. Should I post this on the internal forum?

**Comment by DevilWarrior** [comment]
Actually it seems there was an issue similar to this one previously that had exactly what I needed:

https://github.com/handsontable/handsontable/issues/3672#issuecomment-628518737

Here's the sample:
https://jsfiddle.net/wojciech/2rdua5ek


Unless you say otherwise this does work for me, I customize the code so that it only takes into consideration the first row but it does seems to work through my limited testings.

**Comment by AMBudnik** [comment]
Oh true, I forgot about that functionality as it uses a private API. However, it works well.
