### ISSUE TITLE
Numeric Format not respected

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#7353]
### Description
i have a column   with   pattern: '0%' for numeric format

### Steps to reproduce

1. I enter 1.11
2. the output gives me 111.00000000000000001%

![image](https://user-images.githubusercontent.com/11042160/97174954-141cdf80-1793-11eb-9293-c1ae4aebd935.png)

### Demo
https://jsfiddle.net/jeanmarc/kvLqbzp6/4/

### Your environment
* Handsontable version: 8.1
* Browser Name and version: Chrome 86
* Operating System:Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @jeanmarc78 

I have replicated the same behavior I was able to get some other odd results as

editor
![Zrzut ekranu 2020-10-27 o 14 13 01](https://user-images.githubusercontent.com/10757813/97306330-a0480900-185e-11eb-8adb-3a4250440385.png)


renderer
![Zrzut ekranu 2020-10-27 o 14 13 34](https://user-images.githubusercontent.com/10757813/97306334-a211cc80-185e-11eb-82e6-29a493936f7e.png)

We do not experience that issue when we set a format with decimals `pattern: '0.00%'`.

**Comment by swistach** [comment]
Hi @jeanmarc78,
Accordingly to our documentation for [numericFormat](https://handsontable.com/docs/8.3.0/Options.html#numericFormat), in `pattern` property you can set [format config object](https://numbrojs.com/format.html) for numbro with a proper configuration: 
```
numericFormat: {
  pattern: {
    output: "percent",
    mantissa: 0
  },
}
```
Here you can find a working example: https://jsfiddle.net/1Lvta5h2/

I close this issue but feel free to reopen if you face any problem with implementing the solution for percentage values formatting.
