### ISSUE TITLE
[8.0.0] Fixed rows will cause a double border in the scrollable container

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7356]
### Description

Turning on the `fixedRowsTop`  with `fixedRowsBottom` doubles the bottom border of the column headers.
This applies to the specific case where we have a dataset of at least 14 x 2. 
This bug does not occur when we have dataset 13 x 2.

**This bug occurs only on current browser betas and subsequent versions, eg Canary**
Luckily we have time to really do their releases.

Browser name | Release date |
--- | --- | 
Chrome Beta v87.0.4280.27 | [Nov 17](https://www.chromestatus.com/features/schedule)
Chrome Canary v88.0.4305.0 | [Jan 19](https://www.chromestatus.com/features/schedule)
Firefox Beta v83.0b4 |  [Nov 17](https://wiki.mozilla.org/Release_Management/Calendar)
Safari Technology preview Release 114 (Safari 14.1, WebKit 15611.1.1.3) | [probably March 2021](https://gist.github.com/jakub-g/48a16195280a7023f570ffa5c8a4eae5)
Edge Developer Edition v88.0.673.0 | [Jan 21](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule)
Opera Developer v73.0.3856.0 | -

`v7.4.2` fixed
<img width="176" alt="Screenshot 2020-10-27 at 14 08 23" src="https://user-images.githubusercontent.com/30186818/97305864-ef416e80-185d-11eb-8a1e-870cc0617f02.png">

`v8.0.0 and 8.1.0` **broken**
<img width="178" alt="Screenshot 2020-10-27 at 14 12 02" src="https://user-images.githubusercontent.com/30186818/97306276-8d353900-185e-11eb-9020-cee6c2d14b4d.png">

### Demo

https://jsfiddle.net/qpbk9y6t/1/ - v8.0.0 **broken**
https://jsfiddle.net/qpbk9y6t/2/ - v7.4.2 - fixed

### Your environment
* Handsontable version: 8+
* Browser Name and version: all beta versions of the browsers we support
* Operating System: macOs Catalina 10.15.7

**Comment by aninde** [comment]
This bug occurs when the number of rows in demos increases.

**Steps to reproduce:**
1. Open demo
2. Increase the number of rows in the data set
3. Save and refresh demo

 It can be reproduced in current browser versions as well, so I guess it is about something else. I will test this thoroughly once again.

**Comment by swistach** [comment]
The bug occurs only if the `window` is a scrollable container and there are enough rows to be vertical scrollable: https://jsfiddle.net/v5yf0g8m/

It's related to adding `innerBorderTop` class, which adds an additional border.

**Comment by aninde** [comment]
I suppose that fix for this issue will be added in the next Handsontable version as a result of merging https://github.com/handsontable/handsontable/pull/7491 to the develop.

Meanwhile on the v8.3.0 this issue remain the same https://jsfiddle.net/aninde/91qvcres/.

**Comment by aninde** [comment]
I'm very glad to see that this issue has been fixed by v8.3.2
https://jsfiddle.net/j9bp8vag/

<img width="100" alt="Screenshot 2021-03-10 at 16 50 30" src="https://user-images.githubusercontent.com/30186818/110656971-bed0f000-81c0-11eb-9d5c-2e4b4667f7f3.png">

Tested on 
macOS 11.2.2 (20D80) - Chrome  `88.0.4324.192`, Safari  `14.0.3 (16610.4.3.1.4)`, Firefox `86.0` , Edge `89.0.774.48`, Opera `74.0.3911.203` 
Windows 10 - Chrome  `88.0.4324.192` , Edge `89.0.774.48`, IE `11`, Firefox `86.0`.

**Comment by AMBudnik** [comment]
I'm glad to see another regression fixed in Handsontable v8.3.2
