### ISSUE TITLE
`fixedRowsTop` Changes After Truncating Data

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#7358]
### Description
👋   We're running into an issue with one of our tables where when we replace the data in the table (remove all the rows and then add data back) the `fixedRowsTop` setting doesn't stick around.

### Steps to reproduce
1. Initialize a table with data and `fixedRowsTop = 1`
2. Truncate all the rows
3. Observe that the `fixedRowsTop` is no longer `1`

### Demo
https://jsfiddle.net/49n3sz8e/1/

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: Chrome Latest
* Operating System: OS X

**Comment by AMBudnik** [comment]
Thank you for sharing, Aaron. 

I've updated the demo as we missed that last step (reload the data) https://jsfiddle.net/AMBudnik/ufc136z9/ But, I agree. When we reload it fixing is not applied. 

#### Additionally
* it also breaks when we remove first two rows `hot.alter('remove_row', 0, 2); `
* using `hot.alter('remove_row', 0, 1);` removes one fixed row

#### Version
I've checked v8.0.0 and 7.0.0 and it doesn't seem to be a regression.
8.0.0 - https://jsfiddle.net/AMBudnik/8Lae9yrp/
7.0.0 - https://jsfiddle.net/AMBudnik/tz3q4bfw/

**Comment by AMBudnik** [comment]
Hi @aarondfrancis 

I was testing this demo today. This issue no longer exists if we update to v13.0.0 https://jsfiddle.net/tp6ywk73/1/ and use both `insert_row_below` and `insert_row_above` options.

Could you confirm?

**Comment by AMBudnik** [comment]
Oh, I see. Thank you for the prompt response anyway. I will close this issue as solved.
