### ISSUE TITLE
[7.2.0+] Row movement while using CSS transform property causes multiple issues

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7359]
### Description

Row movement while using CSS `transform` property causes multiple issues.

```
Note: You need to enable `colHeaders` to make it work properly. 
If there are no `colHeaders` you cannot move the last row to the first position.
```

### Steps to reproduce

1. Try to move row 4 anywhere. You'll be able to see wrong shadow placement.

![Zrzut ekranu 2020-10-28 o 10 07 59](https://user-images.githubusercontent.com/10757813/97415449-8ca3ad80-1905-11eb-9439-f9df50f44732.png)

2. Try to move the last row to be the first one. It is not possible as the last available position is index 1.

### Demo

* https://jsfiddle.net/AMBudnik/katcq41p/ 8.1.0 - broken
* https://jsfiddle.net/AMBudnik/b02kdzoq/ 8.0.0 - broken, you can move the last row to the first position but the move is not saved).
* https://jsfiddle.net/AMBudnik/2wnyojd4/ 7.4.2 - case 1 is OK (shadow) but case 2 fails
* https://jsfiddle.net/AMBudnik/rcxvda45/ 7.2.0 - first broken version
* https://jsfiddle.net/AMBudnik/esfgry76/ 7.1.0 - last working version
* https://jsfiddle.net/AMBudnik/e9xbg4rf/ 7.0.0 - both cases work (you can see an odd editor placement but that does not apply for newer versions)

### Related issues
* https://github.com/handsontable/handsontable/issues/6201 'Size no longer works correctly when underneath a transform'

### Your environment
* Handsontable version: 7.2.0+
* Browser Name and version: Chrome 86
* Operating System: macOS Catalina 10.15.7

Zen [25805](https://handsontable.zendesk.com/agent/tickets/25805)

**Comment by wszymanski** [comment]
It seems that `transform` doesn't work stable for Handsontable. There should be done more than fix for row movement - headers are moving while scrolling, there are some window jumps on clicks. What's more some layers overwrite position by using `translate3d` directive within `style` attribute. It would be really hard to separate just part of scope mentioned within task, thus I'm leaving it for now.

**Comment by wojciechczerniak** [comment]
Note. `transform` here should exclude `rotate`. We can support all other transforms but this. Working in any other directions in way beyond a bug fix.

**Comment by arfis** [comment]
Hi guys, is there any progress in this issue?

**Comment by AMBudnik** [comment]
Hi @arfis 

we made the first research on the issue. But it seems to be more demanding than previously predicted so we needed to postpone the work.

I will, however, notify you once we solve it.

**Comment by AMBudnik** [comment]
Hi @arfis 

We checked this issue once again, and it seems that the issue is no longer replicable using the v12.3.0 version https://jsfiddle.net/q9us7cpf/. Could you confirm?

**Comment by arfis** [comment]
Hi @AMBudnik if the col header is not there, it is still not possible to move

**Comment by AMBudnik** [comment]
Hi @arfis we tested the following use case (move the last row to the 1st position in the grid) using Handsontable v12.3.1 and the issue is fixed https://jsfiddle.net/aninde/pumzwexc/. Can you please check that on your side?

**Comment by AMBudnik** [comment]
So many edge cases are related to this issue. You're right with `colHeaders` off, we cannot move the last row to the first position. Let me update the team.

**Comment by AMBudnik** [comment]
Good news! This issue was solved in v14.0.0 https://jsfiddle.net/45c0fs1h/ by this PR https://github.com/handsontable/handsontable/pull/10482

@arfis please update to v14 and let me know if it works for you as well.

**Comment by arfis** [comment]
hm i have still the same issue when the colHeaders are off

**Comment by AMBudnik** [comment]
@arfis Can you share your recent browser/OS settings? When I remove the `rowHeaders` it also works well on my Chrome 119/macOS Ventura.

![Zrzut ekranu 2023-12-6 o 08 34 18](https://github.com/handsontable/handsontable/assets/10757813/fb4a0670-03d8-41d6-b852-d3c4ec904dae)

The only thing is that it usually selects two cells as the table with those CSS scrolls momentarily after we select a cell.

**Comment by arfis** [comment]
rowHeaders are ok, colHeaders off are causing the problem for me, as it was mentioned few comments before.
Here is the example updated:
https://jsfiddle.net/v5Lxae3s/

OS: macOS Ventura (Version 13.5.1 (22G90))
Chrome: Version 119.0.6045.159 (Official Build) (arm64)

**Comment by AMBudnik** [comment]
It seems that we're on the same settings but `colHeaders: false` (disabled) also does not cause the half-selected cell for me. Do you use any browser zoom or system scaling?

Here's how it works for me.

![Zrzut ekranu 2023-12-6 o 09 00 37](https://github.com/handsontable/handsontable/assets/10757813/6c9707d6-ab0b-428b-91e7-db3da38484c7)

**Comment by arfis** [comment]
And the moving to the first position is working? Cause im not really now writing about the half-selection, but about the moving to the first position.
