### ISSUE TITLE
comment box does not work 

### ISSUE THREAD

**Issue by kissxic** [handsontable/handsontable#7363]
### Description
When there is a scroll bar, the display position of the comment box is not correct and does not work properly.

![20201029144803](https://user-images.githubusercontent.com/17944114/97535159-28144b80-19f6-11eb-803b-60fe4768bbf2.png)

### Your environment
* Handsontable version:8.1 ,contextMenu, commentsAddEdit
* Browser Name and version:Chrome Latest
* Operating System:win 10

**Comment by AMBudnik** [comment]
Hi @kissxic 

This issue seems to be the same as this one https://github.com/handsontable/handsontable/issues/6744 
Am I right?

**Comment by AMBudnik** [comment]
If that is not the same issue please share an update. Till that time I will keep #6744 as the original issue and close this one.
