### ISSUE TITLE
The copy/paste works differently after HTML sanitizing

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7369]
### Description

After sanitizing the HTML clipboard data introduced within https://github.com/handsontable/handsontable/issues/7292 I've spotted that pasting multiline data from Excel works differently. I mean in the provided example it works even better than in 8.1.0. The new behavior is caused by DOMPurify which removes the styles added by Excel. The style is processed by the parseTable utils, when the cell has whiteSpace set as `nowrap` (https://github.com/handsontable/handsontable/blob/develop/src/utils/parseTable.js#L328) then a different regex is used to transform new BRs to new lines. As this style is missing after sanitizing and the code works better, the question is whether these conditions are needed there? 

### Steps to reproduce

1. Paste this to the Excel cell
```
1 2 3 4 5
br      
6 7 8 9 0 - 
```
2. Format the cell (you can do this through the context menu), choose "Alignment" and uncheck "Wrap text";
3. Copy the cell and paste it to the Handsontable cell;
4. In results, the values are rendered the same in both 8.2.0 and 8.1.0 but after editing in the 8.1.0 the value gots additional spaces wherein the 8.2.0 it's ok.  

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/ (8.1.0)
https://jsfiddle.net/budnix/b76heyjL/1/ (8.2.0)

### Your environment
* Handsontable version: Upcoming 8.2.0 version 
* Browser Name and version: -
* Operating System: -

**Comment by swistach** [comment]
It seems to me like a bug which we fixed accidentally. I tested manually copying & pasting between GS-HOT-Excel-LO.
The last thing is manually filled clipboard with a styled table and/or custom elements.

IMO we need only to add missing test spec in code. We can add a note to changelog.

Thank you @budnix for your help!

**Comment by budnix** [comment]
But then [this part of code](https://github.com/handsontable/handsontable/blob/develop/src/utils/parseTable.js#L315-L330) seems to be redundant. After removing all `style` tags from the clipboard, the `styleSheetArr ` array will be always empty?

**Comment by swistach** [comment]
Yes, it seems to `styleSheetArr` array will be always empty. Unfortunately, there are only a few test specs and definitely don't cover edge-cases.
I'll add missing specs basing on issue-list from #5684 and #4931.
If everything will work as we expect I'll remove unused code.

**Comment by aninde** [comment]
**Comparison**
**v8.1.0** 
![Screenshot 2020-11-06 at 15 23 27](https://user-images.githubusercontent.com/30186818/98376634-13623400-2044-11eb-9353-99810c432f6c.png)

**v8.2.0**
![Screenshot 2020-11-06 at 15 23 37](https://user-images.githubusercontent.com/30186818/98376637-152bf780-2044-11eb-9e1c-2085762a0b77.png)

**Comment by aninde** [comment]
Today's build RC-8.20. After pasting, there isn't extra space, pasting works fine. 
https://jsfiddle.net/j6ebqL9a/ v8.2.0 build date: 09/11/20
<img width="411" alt="Screenshot 2020-11-09 at 12 14 41" src="https://user-images.githubusercontent.com/30186818/98534884-6e369e00-2285-11eb-8198-e78c6428804e.png">
