### ISSUE TITLE
How to fixed a column in right ,can some one gave a way to do it

### ISSUE THREAD

**Issue by leepyng** [handsontable/handsontable#7370]

**Comment by AMBudnik** [comment]
Hi @leepyng 

this functionality is not supported yet.

If you'd like to vote for adding this functionality please add a 'thumbs-up' for this topic https://github.com/handsontable/handsontable/issues/6775

**Comment by leepyng** [comment]
Hi @AMBudnik 
I had find a way to achieve the issue by setting the last column with the css style bellow:
```
.handson-table {
  thead th:last-child {
    position: -webkit-sticky; 
    position: sticky;
    right: 0;
  }
  tbody td:last-child {
    position: -webkit-sticky; 
    position: sticky;
    right: 0;
  }
}
```

and it works for my require

**Comment by AMBudnik** [comment]
Hi @leepyng 

It seems that this pattern fixes one column, but after some scrolling, if fixes another one https://jsfiddle.net/82fg5hte/1/

**Comment by leepyng** [comment]
@AMBudnik 
Yes ,that can happen. So I set a default  columns render with the property   :
`viewportColumnRenderingOffset: 99`
[https://jsfiddle.net/znrb0hq9/](https://jsfiddle.net/znrb0hq9/)
