### ISSUE TITLE
[8.0.0+] Incorrect rendering related to data validation and hidden columns

### ISSUE THREAD

**Issue by kkayal** [handsontable/handsontable#7377]
### Description

After aborting an invalid data entry, the cell shows the value of the next cell instead of the original value of the current cell.
This happens when

- Column A is hidden
- Column B is numeric
- Column B: 'allowInvalid' property is false

| B | C  |
|----|-------|
| 1  | Smith |
| 2  | James |
| 3  | Tail  |

### Steps to reproduce

1. Select cell B2 in the jsfiddle below
2. Enter an invalid value. E.g 'aa'
3. Press enter (the editor refuses 'aa' as expected)
4. Press ESC (Cell B2 shows James instead of 2)

Note 1: That this seems to be rendering problem. The stored value seems to be intact, since copy & paste works correctly. So if you continue as follows

5. Press CTRL-C to copy the cell B2 to the clipboard
6. Paste somewhere else (you get the correct value, which is 2 and not James)

Note 2: If you skip step 3, there is no problem.

### Demo

http://jsfiddle.net/kkayal/jdom67L3/

### Environment

* Handsontable version: 8.1.0
* Browser Name and version:
  - Chromium Version 86.0.4240.183 (Official Build) snap (64-bit) on Ubuntu 20.04.1
  - Safari Version 14.0 (15610.1.28.1.9, 15610) on MacOS 10.15.7

**Comment by AMBudnik** [comment]
Thank you for sharing this issue report, @kkayal 

That is a regression. 

I've tried 
8.0.0 - http://jsfiddle.net/p827e0ju/ - broken (we get `James`)
7.4.2 - http://jsfiddle.net/s5Lqpzny/ - working well(we get `2`)
7.0.0 - http://jsfiddle.net/p827e0ju/1/ - working well(we get `2`)

**Comment by kkayal** [comment]
It seems the problem has been fixed as of version 8.2.0

**Comment by AMBudnik** [comment]
Thank you for checking and reporting, @kkayal 
I got the same improvement http://jsfiddle.net/AMBudnik/kjot0smd/ the issue seems to be gone in v 8.2.0

**Comment by AMBudnik** [comment]
We'll keep this issue opened @kkayal 
We need to add some tests to make sure this issue won't come back in the future.

**Comment by AMBudnik** [comment]
Hi @kkayal 

we just released Handsontable v.8.3.0 that fixes this issue.

I'd be grateful for your feedback after updating to the newer version. Thanks!

**Comment by aninde** [comment]
**Demo** 
http://jsfiddle.net/davn54sm/ v8.3.0 working well on Chrome Beta 88, Safari 14.0.2 and safari Technology Preview Release 119 (Safari 14.1, WebKit 16611.1.10.1) / macOS Big Sur 11.1

**Comment by kkayal** [comment]
Thanks! It works fine.
