### ISSUE TITLE
Introducing a monorepo.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#7380]
### Description
After this issue's finished, the following projects should be present in this repository in a form of a *monorepo*:

- `handsontable`
- `@handsontable/react`
- `@handsontable/vue`
- `@handsontable/angular`

Every package in the repo will from now on be released with the same version number (starting with the next `handsontable` version).
The monorepo functionality should (most probably) be done using `npm workspaces` and custom helper scripts. Note: `npm workspaces` require using `npm@7` to work.

Additionally:

* [x] All the packages should be cross-linked with each other (e.g. `@handsontable/react` should have a link to the local `handsontable` in its `node_modules`)
* [ ] ~The LICENSE file in the main repo should have information about the packages having different licenses in their respective subdirectories.~ Each of the packages have their own `LICENSE` file, so there's no need for any changes.
* [x] All the projects in the repo should have a common `CHANGELOG.md` file.
* [x] After commiting changes to a package, only the build and tests for that package should be run automatically on CI.
* [x] After merging tasks to  `develop`,  `release/*`, and `master` branches, build and test scripts for all the packages should be triggered on CI.
* The following helper scripts should be created:
  * [x] `build` command for each package
  * [x] `build` command for all the packages in the correct order
  * [x] `test` command for each package
  * [x] `test` command for all the packages
* [x] The CodeSandbox CI script should be configured to match the monorepo concept and structure.
* [x] There should be no Code of Conduct and Contribution Guide file duplicates in the subprojects. The files in the main repo should be modified to match the new structure.
* [x] The issue and PR templates should be modified to match the new structure.
* [x] The documentation should be updated with the new building and testing scenarios.

**Comment by jansiegel** [comment]
Currently I'm keeping `handsontable` in the root of the repo, but [it causes some issues which I'm not sure can be resolved in the long term](https://github.com/npm/feedback/discussions/96). It's possible I'm going to have to move it to a subdirectory, like `packages/handsontable`.

**Comment by wojciechczerniak** [comment]
Finishing touches:

- [ ] Old repositories for wrappers:
  - [ ] Archive (after release)
  - [ ] Disable issues, wiki, PRs
  - [ ] Add git hook to display a message on `git clone`:  https://gist.github.com/krzysztofspilka/ab426f65e9a458086f26409fa2757a32
  - [ ] Add a warning to the readme: https://gist.github.com/krzysztofspilka/ab426f65e9a458086f26409fa2757a32
- [ ] New README for main Handsontable package: https://gist.github.com/krzysztofspilka/99f59733e97d0e7f0352a63451904c1a
- [ ] New README files for wrappers
  - [ ] React: https://gist.github.com/krzysztofspilka/6ea55e7568e89dec0183102c99d349de
  - [ ] Angular: https://gist.github.com/krzysztofspilka/d7ac6bd1e8804f481761c944f7070e72
  - [ ] Vue: https://gist.github.com/krzysztofspilka/630591379f5e2531910d96f3154e7419
- [ ] Move all images to the main repo `/resources` directory: 6x images: logo HOT, logo JS, 3x logo frameworks, screenshot
- [ ] Remove LICENSE.txt from `/wrappers/*` directories
- [ ] Copy LICENSE.txt and PDF licenses on `prepublish` + add some kind validation that those files are present before publishing new version
- [ ] Remove info about MIT license at docs pages: 
  - [ ] https://handsontable.com/docs/frameworks-wrapper-for-react-installation.html
  - [ ] https://handsontable.com/docs/frameworks-wrapper-for-angular-installation.html
  - [ ] https://handsontable.com/docs/frameworks-wrapper-for-vue-installation.html
- [ ] Prepare releases for:
  - [ ] Handsontable (8.3.2) 
  - [ ] Angular 7.0.0
  - [ ] React 5.0.0
  - [ ] Vue 6.0.0

**Comment by AMBudnik** [comment]
Monorepo has been introduced for v8.3.2 of Handsontable.
More about the changes I've described under this topic https://github.com/handsontable/handsontable/issues/7637 

Thank you @jansiegel and @wojciechczerniak, great work!
