### ISSUE TITLE
Column `trimWhitespace` setting has no effect

### ISSUE THREAD

**Issue by kokopelli314** [handsontable/handsontable#7387]
### Description

Setting the `trimWhitespace` option to `false` has no effect: values that begin or end with white spaces are still trimmed.

Expected result: if a column has `trimWhitespace: false`, values entered in that column should not be trimmed of whitespace.

It appears that `trimWhitespace` currently only works at the HandsOnTable instance level.

### Steps to reproduce

1. Create a HandsOnTable instance with a column that has the `trimWhitespace: false` option set
2. Enter a value that begins and/or ends with spaces in this column and hit enter
3. See that the value in HoT is trimmed

### Demo

https://jsfiddle.net/1ranu2mc/4/

### Your environment
* Handsontable version: 8.2.0 (also tested with HoT 7.4.2) 
* Browser Name and version: tested in most recent Firefox and Chrome
* Operating System: MacOS

**Comment by AMBudnik** [comment]
That's true. Thank you for sharing @kokopelli314 

We need to define the value on the instance level https://jsfiddle.net/AMBudnik/g3p29hef/
I've also tried the `cells` method without success https://jsfiddle.net/AMBudnik/9u43kfao/

**Comment by AMBudnik** [comment]
`trimWhitespace` option is not available in the docs https://github.com/handsontable/handsontable/issues/9329

**Comment by aninde** [comment]
This issue will be fixed by the upcoming v12.1.3 https://jsfiddle.net/fq1bsdnx/.

**Comment by AMBudnik** [comment]
Hi @kokopelli314 

I have great news!

We just released Handsontable v12.1.3, which solves this issue.

Updated demo result
<img width="148" alt="Screenshot 2022-09-22 at 11 49 40" src="https://user-images.githubusercontent.com/10757813/191716159-fb028747-2527-482b-969a-8776981bede1.png">


I'm closing this issue as solved. However, if you'd need anything, please send me an email at support@handsontable.com
