### ISSUE TITLE
hideRows is undone with updateSettings

### ISSUE THREAD

**Issue by camilstaps** [handsontable/handsontable#7391]
### Description
Calling `updateSettings` on an instance where `hideRows` (`hiddenRows` plugin) has been used to hide some rows seems to reset the state of the plugin, causing all rows to be visible again. The expected behaviour is that the hidden rows remain hidden (at least when the updated settings are unrelated).

### Steps to reproduce

See https://jsfiddle.net/pf03kgaq/:

```js
hot1.getPlugin('hiddenRows').hideRow(3);
hot1.render();

window.setTimeout(
	() => hot1.updateSettings({height: '200px'}),
	1000
);
```

Initially, the row of year 2019 is hidden. After 1s, `updateSettings` causes it to be shown again. I would expect that setting the table height does not influence the hidden rows.

When the hidden rows are set in the initial settings (i.e. `hiddenRows.rows: [3]`), this problem does not occur: https://jsfiddle.net/pf03kgaq/1/

### Demo
https://jsfiddle.net/pf03kgaq/

### Your environment
* Handsontable version: 8.2.0
* Browser Name and version: Firefox 68
* Operating System: Debian 10

**Comment by AMBudnik** [comment]
Hi @camilstaps 

Thank you for sharing the issue report. I have already reported the same issue here https://github.com/handsontable/handsontable/issues/7165 so I have to close this ticket. 
Nevertheless, I will send you a notification as soon as https://github.com/handsontable/handsontable/issues/7165 is fixed.

Also, if you feel that we should add some more details to https://github.com/handsontable/handsontable/issues/7165 please feel free to add a comment.

**Comment by camilstaps** [comment]
@AMBudnik apologies, thanks!

**Comment by AMBudnik** [comment]
Hi @camilstaps 

I have good news. We just release the linked issue in Handsontable v12.
Please check the changes within Handsontable v12 at https://handsontable.com/docs/release-notes/#_12-0-0
