### ISSUE TITLE
How to achieve doublescroll (horizontal bars) in handsontable ? 

### ISSUE THREAD

**Issue by VirajBhatt** [handsontable/handsontable#7395]
If we restrict the width of the table and keep height to 100%, for more number of records, it's time consuming to go all the way down to scroll to left / right. A horizontal scroll bar at the top and bottom would be a nice way out for this.

**Comment by AMBudnik** [comment]
Hi @VirajBhatt 

I am not sure if I understand the settings of your use case. Could you tell me what should I add/change in this demo https://jsfiddle.net/AMBudnik/1rga3mo5/ and what would be the desired outcome?

**Comment by AMBudnik** [comment]
It's nearly a week without any update so I assume that the issue may be already solved. If it's not, please feel free to share more details on my email at support@handsontable.com
