### ISSUE TITLE
SelectCells is slow when passed a lot of discontiguous selections

### ISSUE THREAD

**Issue by breck7** [handsontable/handsontable#7397]
https://github.com/handsontable/handsontable/blob/34793d5e9ee10176941ebe2589996daa80b5effd/src/selection/selection.js#L553

If you call `selectCells` with a hundred selections, it seems slow:

```
ht.selectCells(
                oneHundredCellPositions.map((pos) => [pos.row, pos.column, pos.row, pos.column])
            )
```

**Comment by AMBudnik** [comment]
Hi @breck7 

I am not sure if that method was tested for making that many selections at the same time. However, with the about of selected data, it does not seem to work that slow https://jsfiddle.net/AMBudnik/ns79zcfd/

**Comment by AMBudnik** [comment]
Hi @breck7 

as we do not have any updates here I am closing this issue.

However, if you'd like to discuss it further please send me an email at support@handsontable.com
