### ISSUE TITLE
Unable to have the dropdown menu on the first row of the nested headers

### ISSUE THREAD

**Issue by mariuscomiati** [handsontable/handsontable#7398]
Hello, I could not find how can I have the dropdown menu on the first row of the nested headers. Is that possible?

**Comment by AMBudnik** [comment]
Hi @mariuscomiati 

when you enable `dropdownMenu` on `nestedHeaders` this is what'd get.

![Zrzut ekranu 2020-11-18 o 12 11 45](https://user-images.githubusercontent.com/10757813/99523544-80a48c00-2997-11eb-848d-8c495837ae1f.png).

All of the columns on the lowest level get an icon of a dropdown menu.

And even if you set up the first column to be the only one showing the options like here https://jsfiddle.net/AMBudnik/4k0dhjru/

![Zrzut ekranu 2020-11-18 o 12 38 57](https://user-images.githubusercontent.com/10757813/99526094-1261c880-299b-11eb-808e-d73bd2a4cb0f.png)

the menu icon is still visible for all of the columns. 

When a user clicks the menus for other columns they would get a notification that there are no options available.

![Zrzut ekranu 2020-11-18 o 12 40 07](https://user-images.githubusercontent.com/10757813/99526207-3c1aef80-299b-11eb-826a-84187f7e877b.png)
