### ISSUE TITLE
The isDeprecated hook is missing in the typings

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7399]
### Description

As mentioned in the docs research report handsontable/support#260 we do not mention the [`isDeprecated` hook](https://handsontable.com/docs/8.1.0/Hooks.html#isDeprecated) in the definition file.

![Zrzut ekranu 2020-11-18 o 13 12 03](https://user-images.githubusercontent.com/10757813/99529170-aafa4780-299f-11eb-9f6f-5e3b1a9dac96.png)

![Zrzut ekranu 2020-11-18 o 13 14 21](https://user-images.githubusercontent.com/10757813/99529378-fca2d200-299f-11eb-87cc-de53d58a2349.png)
Demo: https://jsfiddle.net/AMBudnik/1nd3vbxu/

### Your environment
* Handsontable version: 8.2.0
* Browser Name and version: n/a
* Operating System: n/a

**Comment by aninde** [comment]
That hook is on definition file in the v8.3.0.
https://github.com/handsontable/handsontable/blob/eedc625c8cba5f802fa12122a1192c0fe64331fa/handsontable.d.ts#L1934
