### ISSUE TITLE
TypeScript definition adjustments

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7400]
### Description

As mentioned in the docs research report handsontable/support#260 we do not mention some of the options/methods, and hooks in our definition file. Some of them are reported in separate issues, below is the rest of the list. 

This list also contains some smaller issues regarding definitions.

#### Typo
1. [x] Fix typo in the first parameter of the `afterColumnCollapse` hook in the .ts file. The `currentCollapsedColumn` has to be renamed to `currentCollapsedColumns`. 
1. [x] Fix typo in the first parameter of the `afterColumnExpand` hook in the .ts file. The `currentCollapsedColumn` has to be renamed to `currentCollapsedColumns`. 
1. [x] Fix typo in the `afterCopyLimit` hook. Change `selectedColumnds` to `selectedColumns`.
1. [x] Fix typo in the `afterGetColHeader` hook. The first parameter should be renamed to `column`.
1. [x] Fix typo in the `afterRenderer` hook. The third parameter should be renamed to `column`.
1. [x] Fix typo in the `beforeRenderer` hook. The second parameter should be renamed to `column`.
1. [x] Fix typo in the `afterSetCellMeta` hook. The second parameter should be renamed to `column`.
1. [x] Fix typo in the `afterGetCellMeta` hook. The second parameter should be renamed to `column`.
1. [x] Fix typo in the `modifyColWidth` hook. The second parameter should be renamed to `column`.
1. [x] Fix typo in the `modifySourceData` hook. The second parameter should be renamed to `column`.
1. [x] Fix typo in the [`cells`](https://github.com/handsontable/handsontable/blob/develop/handsontable.d.ts#L1650) option. The second parameter should be renamed to `column`.

#### Rewrite/Update
1. [x] Update parameters in the `beforeColumnMove` hook. Definition introduces two parameters: `columns` and `target`, while we already have: `movedColumns, finalIndex, dropIndex, movePossible`.
1. [x] Update parameters in the `afterColumnMove` hook. Definition introduces two parameters: `columns` and `target`, while we already have: `movedColumns, finalIndex, dropIndex, movePossible, orderChanged`.
1. [x] Add missing boolean return type for the `afterTrimRow` hook.
1. [x] Add missing boolean return type for the `beforeTrimRow` hook.
1. [x] Add missing boolean return type for the `afterUntrimRow` hook.
1. [x] Add missing boolean return type for the `beforeUntrimRow` hook.
1. [x] Add missing boolean return type for the `beforeFilter` hook.
1. [x] Add missing boolean return type for the `beforeHideColumns` hook.
1. [x] Add missing boolean return type for the `beforeUnhideColumns` hook.
1. [x] Add missing boolean return type for the `beforeHideRows` hook.
1. [x] Add missing boolean return type for the `beforeUnhideRows` hook.

#### Other
1. [x] Move the `afterUnlisten` hook to follow the alphabetic order of hooks.
1. [x] Move the `beforeRemoveCellClassNames` hook to follow the alphabetic order of hooks.
1. [x] Move the `beforeRemoveCellMeta` hook to follow the alphabetic order of hooks.
1. [x] https://github.com/handsontable/handsontable/issues/7399

### Your environment
* Handsontable version: 8.2.0
* Browser Name and version: n/a
* Operating System: n/a

**Comment by scarletfog** [comment]
note: `afterRender` has just one param, it was probably about `afterRenderer`

**Comment by AMBudnik** [comment]
@scarletfog true. I've updated the list.

**Comment by aninde** [comment]
Tested with `handsontable.d.ts` from [v8.3.0.](https://github.com/handsontable/handsontable/blob/release/8.3.0/handsontable.d.ts).

I marked everything because it was done and tested.

**Comment by AMBudnik** [comment]
Thank you @aninde we can close it as solved for v8.3.0
