### ISSUE TITLE
Batching operations doesn't work for operations already batched  

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7408]
### Description

When I execute filtering or sorting logic within the `batch` method I've got different results when I run the logic from the outside of the batch callback. I think that this applies to any plugin which uses the IndexMapper internally.

Edit: It seems that after adding the `render` call (https://jsfiddle.net/budnix/2cftwqsa/1/) the table looks good. The [batch docs](https://handsontable.com/docs/8.2.0/Core.html#batch) nothing says about that. @wojciechczerniak is it a bug or missing documentation?
### Steps to reproduce

1. The demo is clear enough.

### Demo

https://jsfiddle.net/budnix/2cftwqsa/

### Your environment
* Handsontable version: 8.2.0
* Browser Name and version: -
* Operating System: -

**Comment by wojciechczerniak** [comment]
@budnix Missing documentation for the current `batch` implementation. It was prepared for internal use and IndexMapper layer only and therefore has no effect on `render()` which was called by the plugins anyway.

You're right though that using it outside of the plugin will require manual render as `batch` does not trigger it yet.

When we extend `batch` to suspend rendering IMO it should trigger the render at the end, as described in #7274.  I guess that would solve this issue and give you the behavior you've expected?

But then we probably should stop using `batch` internally to avoid calling `render()` so in #7274 for internal flow control  I've proposed:

```ts
hot.suspendRecalculation();

// do index mappers operations

hot.resumeRecalculation();
```

Alternatively, we could create `batchRender` and `batchOperations` but IMO that would be too much.
