### ISSUE TITLE
manualRowMove and undo/redo repeatedly breaks undo history

### ISSUE THREAD

**Issue by sinbino** [handsontable/handsontable#7409]
### Description

Repeating undo/redo after a row operation with manualRowMove will break the undo history and corrupt the table.
If the undo/redo is done slowly, the problem does not occur, but if the undo/redo is repeated at high speed with key auto-repeat, the problem occurs.

### Steps to reproduce

1. go to https://jsfiddle.net/sinbino/yjoaLbd7/
2. Write about 10 columns of values in the first row.
3. Drag that row down about 10 rows.
4. Rewrite all the values in that row.
5. Press and hold cmd+Z (on the Mac) to quickly go back to the beginning of the undo history.
6. Press and hold cmd+shift+Z (on a Mac) to quickly redo to the end of the undo history.
7. If you repeat steps 5.6. many times, the table will collapse.

If you don't hold down cmd+Z and slowly repeat the undo/redo, the problem doesn't seem to occur.
Even very light tables do not seem to cause problems.

### Demo

https://jsfiddle.net/sinbino/yjoaLbd7/

### Your environment
* Handsontable version: 8.2.0
* Browser Name and version: 87.0.4280.67（Official Build（x86_64）
* Operating System: macOS Catalina 10.15.7

**Comment by sinbino** [comment]
Other issue:

Use jsfiddle above.

1. Enter the appropriate value in the vertical direction.
Example: Put the values 1-6 in cells A1-A6.

2. Use manualRowMove to swap rows.
Example: swap rows 3 and 4 by dragging the mouse. 

3. delete all the rows at once.
 Example: select rows 1-6 and delete them by clicking "Remove rows" in the context menu.

4. undo with Cmd+Z (on a Mac). You will be expected to return to the state of step 2, but in fact you will return to the state of step 1.

**Comment by AMBudnik** [comment]
I wasn't able to replicate the issue on Chrome 87, macOS Catalina 10.15.7.

I've Added values from 1 to 10

![Zrzut ekranu 2020-11-23 o 14 50 04](https://user-images.githubusercontent.com/10757813/99969750-2fcbd380-2d9b-11eb-8e31-657249f38561.png)

Then used autofill of A1 and kept using Undo and Redo but it worked well and without any glitches.

@aninde can you check this on your device?

**Comment by aninde** [comment]
I couldn't make the [first reproduction](https://github.com/handsontable/handsontable/issues/7409#issue-748455555) either. I did it on `Chrome beta` in the same version 87.0.4280.67, but I failed. Although, I have Big Sur (macOS 11), but that shouldn't have an effect. I tried 2 variants, as you can see on the gif. In the first variant you can see a delay in data rendering, part of the table at the bottom is rendered only after an event.

@sinbino maybe you could send us gif reproducing this case? 
![7409](https://user-images.githubusercontent.com/30186818/99978625-783cbe80-2da6-11eb-92d6-d657984f5388.gif)
![bug?](https://user-images.githubusercontent.com/30186818/99980470-93103280-2da8-11eb-98c7-479f8a446cc4.gif)

However, I was able to reproduce the [2 case](https://github.com/handsontable/handsontable/issues/7409#issuecomment-732015479).

Wrong result: data is restored in wrong order, at cell A2 should be '7' and selection is moved down.
![bug - another case](https://user-images.githubusercontent.com/30186818/99979518-79222000-2da7-11eb-9c75-9fab1321c689.gif)

### Case 3
**Reproduction:**
Populating some data at cells.
Moving one cell up.
Selecting all cells by clicking in the corner.
Remove all cells.
Undo.

**Result**: wrong order is restored, only moved cell is returned. 
![case 2](https://user-images.githubusercontent.com/30186818/99978617-7541ce00-2da6-11eb-87f3-332cc8c6620a.gif)

**Comment by AMBudnik** [comment]
Thank you @aninde 
That's also a great idea with the video reproduction. @sinbino can you share it with us? That would definitely help us to confirm if we're on the same page.

**Comment by sinbino** [comment]
First of all, my deepest apologies for the delay in responding.

I have created a gif that reproduces the image.
The procedure for creating it was as follows

1. Go to https://jsfiddle.net/sinbino/yjoaLbd7/.
2. Enter the numbers 1 to 10 in A1 to J1.
3. Drag and drop row #1 to row #10 to move it.
4. Overwrite A10 to J10 with the numbers 11 to 20.
(After this is the part shown in the gif.)
5. Press and hold cmd + Z to go back to the beginning of the history.
6. Press and hold cmd + shift + Z to go to the end of the history.
(Repeat the above.)

The environment used for this reproduction is Catalina (10.15.7) and Chrome 87.0.4280.88.

![repro](https://user-images.githubusercontent.com/22654430/102072092-b9277080-3e44-11eb-9bee-fccb13aea67c.gif)

**Comment by AMBudnik** [comment]
That's a pretty complex scenario. 

I wasn't able to write consecutive numbers that fast some I wrote anything else that I fought under the fingers but I've replicated the issue. My row `0` is completely removed while I get one cell value in the row `10`. 

I believe that speed matters. But sometimes I feel like I'm speeding up but can't replicate the same issue.

**Comment by sinbino** [comment]
My mac has [System Preferences] - [Keyboard] - [Key Repeat] set to Fastest.
As a test, I changed this to one latch slower than Fastest, and the problem no longer reproduced.

It may have something to do with the time interval between undo runs.
On slower systems, longer intervals may also cause the problem.
I think we need to provide proper blocking for undo execution without expecting users to do undo slowly.

**Comment by aninde** [comment]
@sinbino I also failed to make your reproduction, despite the same settings. I'll practice some quick typing, maybe it will help.

I have a question about one point of your reproduction. Do you use <kbd>TAB</kbd> to move to the next cell? 

By default, the Handsontable editor jumps down when the editor is closed.

**Comment by sinbino** [comment]
@aninde 

> Do you use TAB to move to the next cell?

No, I am using the arrow keys to move the cells to reproduce the problem.

When the problem occurs, I hold down cmd + Z and cmd + shift + Z and keep the key auto-repeat until it stops at the beginning/end of the history.

**Comment by sinbino** [comment]
I am using a Mac in a Japanese environment.
Is it possible that the language setting is affecting the performance of chrome?

**Comment by sinbino** [comment]
I tested it in multiple environments.

MacBookPro 15inch 2016, i7-2.9GHz, 16GB RAM, Catalina 10.15.7
* Chrome 87.0.4280.88 (without extension) - encountered problems
* Firefox 81.0.1 (without extension) - no problem
* Safari 14.0.1 (without extension) - no problem

Windows Desktop, i9-9900k, 32GB RAM, Windows10
* Chrome 87.0.4280.88 (without extension) - no problem

**Comment by aninde** [comment]
I was able to reproduce it with described settings (fastest Key repeat) on Catalina 10.15.7 with MacBook Air (13-inch, 2017), so I guess it's about the conditions: **Catalina + Chrome + fastest Key repeat** 
Before, I wasn't able to recreate it on Big Sur 11.0.2.

Sadly this bug occur on 
- Chrome 87.0.4280.88
- Chrome Beta 88.0.4324.41 (here it is the weakest delay, but it is not perfect)
- Chrome Canary 89.0.4357.0

This bug dropped to an almost imperceptible glitch as soon as I dropped the speed slightly to default state. 
Even greater reduction in speed means that there is no visual bug.

**My default settings:**
![Screenshot 2020-12-16 at 19 31 42](https://user-images.githubusercontent.com/30186818/102390965-5e714e80-3fd5-11eb-835e-4c5882caaf4c.png)

**Chrome  87.0.4280.88 the fastest key repeat**
![chrome-87](https://user-images.githubusercontent.com/30186818/102390111-477e2c80-3fd4-11eb-9dab-413b292d310e.gif)

**Chrome 87.0.4280.88 slightly slower than the fastest** 
![chrome87-slower-keyboard](https://user-images.githubusercontent.com/30186818/102390696-08041000-3fd5-11eb-9a7d-fbc91da85a9a.gif)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Hi @sinbino 

It's been a long time since the last update, but I think we have finally fixed this issue.

It works well when we undo

![working-well](https://github.com/user-attachments/assets/e81355ce-d29a-4525-8f32-86089d6ecd2f)


I hope it is also fixed on your side.
