### ISSUE TITLE
The second part of changes to prepare new modularization approach

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#7412]
Description
Accordingly to #7381 description, we have to prepare the following things:

- prepare a mechanism to make possible registering built-in plugins in the proper order (same as we already have in `src/plugins/index.js`)
- add a possibility to load only these plugins what end-devs need (ES and CJS bundles)

This should not affect UMD builds and should be backwards-compatible.

**Comment by aninde** [comment]
Closed #7412.
