### ISSUE TITLE
handsontable column type - expand direction

### ISSUE THREAD

**Issue by akoskm** [handsontable/handsontable#7416]
Is there a way to control in which direction the `handsontable` column type expands?

![image](https://user-images.githubusercontent.com/3111627/100533626-c9b1d700-3206-11eb-8756-01b279567883.png)

I have a use-case where the last dropdown is almost at the edge of the screen:

![image](https://user-images.githubusercontent.com/3111627/100533653-15648080-3207-11eb-9c0b-b37ae59c0edf.png)

and I would like the table to expand to the left instead of right.

**Comment by AMBudnik** [comment]
Hi @akoskm 

there is no API to control the direction of cell data extension. This behavior is strictly the reason for this issue https://github.com/handsontable/handsontable/issues/6045

**Comment by akoskm** [comment]
Thanks @AMBudnik, are there any plans to support this in the future?

**Comment by AMBudnik** [comment]
@akoskm I do not see any similar feature in our Roadmap.
If we would allow changing the direction we may end up with some serious misalignments related to CSS settings applied on Clients' projects. But I believe that Handsontable just should understand where's the best place to expand the info.
