### ISSUE TITLE
Migration from colOffset

### ISSUE THREAD

**Issue by dtomaszewski** [handsontable/handsontable#7418]
### Description
colOffset https://handsontable.com/docs/7.4.2/Core.html#colOffset was removed in 8.0 it's breaking change in our project, what's the official migration guide to replace it in v8 ?

### Steps to reproduce
Migration from v7 to v8

### Demo
N/A

### Your environment
* Handsontable version: migration to v8
* Browser Name and version: n/a
* Operating System: n/a

There is no information about it in migration guide, it only stays that it's removed :
![Screenshot 2020-12-01 at 08 50 46](https://user-images.githubusercontent.com/4403684/100712049-6c5a8900-33b2-11eb-95a5-76d3768babf0.png)

**Comment by wojciechczerniak** [comment]
Can you describe your use case?

**Comment by dtomaszewski** [comment]
One use case would be to get row and topmost row element from hot to add/remove some css class to it. Solution which is in our codebase looks like this :

`
const cell: HTMLTableCellElement | null = htInstance.getCell(rowIndex, htInstance.colOffset());
const row: HTMLTableRowElement = cell!.closest('tr')
`

It has few years so it may be rusty, I'd appreciate if You have some more up to date solution to do the thing.

**Comment by dtomaszewski** [comment]
I also see that thing we need here is Approved in feature requests but still in Under consideration part of FR :

![Screenshot 2020-12-01 at 10 56 01](https://user-images.githubusercontent.com/4403684/100725111-e9dac500-33c3-11eb-8e68-cf736409d899.png)

I wonder how it can be done now when colOffset is removed.

**Comment by AMBudnik** [comment]
Hi @dtomaszewski If I understand it correctly you can use the `autoRowSize` logic like so https://jsfiddle.net/AMBudnik/n6eu38yv/ 

```js
let row = hot.getPlugin('AutoRowSize').getFirstVisibleRow();
console.log(hot.getCell(row, 0).parentElement)
```

Is that helpful?

**Comment by dtomaszewski** [comment]
Hi @AMBudnik not really, I'd like to get row element when I have the index of this row. In Your solution it's always first row.

**Comment by AMBudnik** [comment]
OK, so I misunderstood the use case. I thought that you need the TR element when they change over a scroll. Could you brief me with possible scenarios when the element is needed and may be changed (example: adding/removing rows)?

**Comment by dtomaszewski** [comment]
I have row index and I want to have row element to for example add/remove some css classes to whole row. By whole row I mean both layers, below and topmost.

**Comment by dtomaszewski** [comment]
@AMBudnik any news about it ?

**Comment by wojciechczerniak** [comment]
The only way currently is to dig deeper to Walkontable methods, `colOffset` was an alias:
https://github.com/handsontable/handsontable/blob/88d78a5be5e37ad703c11914c86690d2436d3024/src/core.js#L3046-L3048
However, the returned value from Walkontable has changed. It's no longer a visual index.  Since `v8.0.0` Walkontable works on renderable indexes. You have to translate it from renderable to visual first: 

https://jsfiddle.net/budnix/qz2r5j8d/

This has to be treated as a workaround. Currently, there is no access to renderable indexes from public APIs. I'm not sure how public APIs should look like here, that's why I've asked for your use case. We're trying to figure out how and why developers would use those. Thanks for your input.

**Comment by dtomaszewski** [comment]
@wojciechczerniak thanks for Your answer. It seems that this workaround works for my case however I'm a bit concerned that this will be removed in future releases. Please remember to support this use case when this api will be modified.

**Comment by dtomaszewski** [comment]
Hi @wojciechczerniak I can see that it has been slightly changed in newest HT version. Can you confirm that now official way of solving this issue is to do it like that: 

`instance.view.activeWt.wtTable.getFirstRenderedColumn()`

Or there is another better way ?

**Comment by dtomaszewski** [comment]
@wojciechczerniak thanks for update! @AMBudnik any news here ? :)

**Comment by AMBudnik** [comment]
Thanks for pinging, @wojciechczerniak :) have a great day, mate!

@dtomaszewski, we're heading into a rabbit hole here, `wt` was changed to `_wt`. Updated demo https://jsfiddle.net/1jza4owv/ 

ps. I would prefer to have a call where we discuss in details what the requirements are than to offer API that generally is private. If you like that idea, let me know at support@handsontable.com

**Comment by dtomaszewski** [comment]
@AMBudnik good idea, I'll reach you there :)
