### ISSUE TITLE
Problem in column move feature used on autocomplete cell.

### ISSUE THREAD

**Issue by gururajiv** [handsontable/handsontable#742]
Hi,

I am trying to implement column move feature of handsontable. it is not working if my column type is "autocomplete" however it works perfectly with normal cell type. When i move "autocomplete" column then it move all the data of moved column to the new position but it does not move the cell properties.

Sample of the same is on jsFilddle.
http://jsfiddle.net/Hkq66/

Thanks,

Rajeev

**Comment by AMBudnik** [comment]
It should not occur anymore, if you have still this issue, please write back.
