### ISSUE TITLE
How do you do it with a single rowHeader row and then you have a large area set up what do you do with borders

### ISSUE THREAD

**Issue by ywyixx** [handsontable/handsontable#7422]
1. Multiple lines sharing a Single rowHeader
2. a large area set up what do i do with borders

**Comment by AMBudnik** [comment]
Hi @ywyixx 

Answering your questions

**Ad.1.**
We do not support `rowspan `of headers yet. Each row has its own header. You may however use [`nestedRows `feature](https://handsontable.com/docs/8.2.0/Options.html#nestedRows) to provide some more information to a single row.

**Ad.2.**
What is the exact expected result? I'll do my best to help if you provide some examples of current/expected behavior.

**Comment by ywyixx** [comment]
Ad.2.
For example, if you select a 10x10 cell and set the border, it will be slow




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "handsontable/handsontable"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 晚上6:06
收件人:&nbsp;"handsontable/handsontable"<handsontable@noreply.github.com&gt;;
抄送:&nbsp;"朝九"<7570820@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [handsontable/handsontable] How do you do it with a single rowHeader row and then you have a large area set up what do you do with borders (#7422)





 
Hi @ywyixx
 
Answering your questions
 
Ad.1.
 We do not support rowspan of headers yet. Each row has its own header. You may however use nestedRows feature to provide some more information to a single row.
 
Ad.2.
 What is the exact expected result? I'll do my best to help if you provide some examples of current/expected behavior.

**Comment by ywyixx** [comment]
sry, my mistake,&nbsp;it should be select a 10x10 cell.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "朝九"                                                                                    <7570820@qq.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 上午9:35
收件人:&nbsp;"handsontable/handsontable"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [handsontable/handsontable] How do you do it with a single rowHeader row and then you have a large area set up what do you do with borders (#7422)



Ad.2.
For example, if you select a 10x10 cell and set the border, it will be slow




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "handsontable/handsontable"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 晚上6:06
收件人:&nbsp;"handsontable/handsontable"<handsontable@noreply.github.com&gt;;
抄送:&nbsp;"朝九"<7570820@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [handsontable/handsontable] How do you do it with a single rowHeader row and then you have a large area set up what do you do with borders (#7422)





 
Hi @ywyixx
 
Answering your questions
 
Ad.1.
 We do not support rowspan of headers yet. Each row has its own header. You may however use nestedRows feature to provide some more information to a single row.
 
Ad.2.
 What is the exact expected result? I'll do my best to help if you provide some examples of current/expected behavior.

**Comment by AMBudnik** [comment]
Hi @ywyixx 

Can you share your use case with me on support@handsontable.com? The default demo https://jsfiddle.net/8ya1bskr/ couldn't work better on Chrome 87. It imminently adds the borders via `contextMenu`.

**Comment by ywyixx** [comment]
I used fixing in accordance with the document, but the result I got is inconsistent. same code.
I need to know why the table is only partially rendered.
The version is 6.2.2.
Hope to hear from you soon.

**Comment by AMBudnik** [comment]
Hi @ywyixx 

Have you sent me the demo to support@handsontable.com? I do not see any new emails.
