### ISSUE TITLE
[Bug Report] [8.2.0] contextMenu 'left' style in Wrapper for Vue is setted a error value

### ISSUE THREAD

**Issue by microkof** [handsontable/handsontable#7423]
### Description

![Image](https://wx3.sinaimg.cn/large/3e2cf89cly1glehiy1rltj20mx0ux413.jpg)

↑↑↑↑Left style is an absurdly negative numbers.

### Steps to reproduce
1. Wrapper for Vue

### Demo

```
<template>
  <div class="app-container">
    <hot-table :settings="hotSettings"></hot-table>
  </div>
</template>

<script>
import { HotTable } from "@handsontable/vue";
import 'handsontable/languages/zh-CN';
import "handsontable/dist/handsontable.full.css";
export default {
  components: {
    HotTable,
  },
  data() {
    return {
      hotSettings: {
        data: [
          {
            id: 1,
            name: "",
            price: 13,
            currency: "PLN",
          },
          {
            id: 2,
            name: "Nissan",
            price: 14,
            currency: "USD",
          },
          {
            id: 3,
            name: "",
            price: 300,
            currency: "USD",
          },
        ],
        colHeaders: ["数字", "下拉", "价格 ($)", "欧元 (€)"],
        columns: [
          {
            data: "id",
            type: "numeric",
          },
          {
            data: "name",
            editor: "select",
            selectOptions: ["Kia", "Nissan", "Toyota", "Honda"],
          },
          {
            data: "price",
          },
          {
            data: "currency",
          },
        ],
        startRows: 30,
        startCols: 6,
        minSpareRows: 1,
        contextMenu: ['row_above', 'row_below', 'remove_row'],
        rowHeaders: true,
        class: "hot-table",
        licenseKey: "non-commercial-and-evaluation",
        language: 'zh-CN',
      },
    };
  },
};
</script>
```

### Your environment
* Handsontable version: 8.2.0
* Browser Name and version: Chrome 69
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @microkof 

The same does not happen on our official demo for Vue https://handsontable.com/docs/8.2.0/frameworks-wrapper-for-vue-custom-context-menu-example.html 
![image](https://user-images.githubusercontent.com/10757813/101336531-e25f6400-387a-11eb-9722-83aa9bb3c681.png)

This issue might be related to the fact that context-menu has its z-index and position that relates to the Handsontable. I assume that your left menu is a slider menu (it hides and shows)?

**Comment by AMBudnik** [comment]
Hi @microkof 

do we have any updated here?

**Comment by microkof** [comment]
> Hi @microkof
> 
> do we have any updates here?

I try to test the code in pristine page, it is OK. The problem is caused in a UI framework, but I haven't found the cause of the problem.

Give me a few days, let me test it further.

And a little bit more, the difference between the left error value and the normal value is exactly the width of the viewport.

**Comment by AMBudnik** [comment]
Hi @microkof it's been almost 3 weeks since the last update.
I need to close this topic.

However, we can still discuss this issue here or on the email support@handsontable.com
