### ISSUE TITLE
setSourceDataAtCell() doesn't work after updateSettings() with nestedRows

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#7428]
### Description
I'm using HT 8.2.0 and run into an issue where it seems that after updating data, using `setSourceDataAtCell()` doesn't work anymore. 

This demo includes the basic scenario I have, where I use `setSourceDataAtCell()` from a context menu and have nested rows.

### Steps to reproduce

1. Open demo: https://jsfiddle.net/hcf56qtn/
2. Right click on one of the parent rows and choose "Set data", note the ID cell changes to "999"
3. Click the "Update data" button, which simply regenerates the data and updates the table
4. Repeat step 2, note that "999" is not properly set

### Demo

https://jsfiddle.net/hcf56qtn/

### Your environment
* Handsontable version: 8.2.0
* Browser Name and version: Chrome Version 86.0.4240.198 
* Operating System: MacOS 10.14.4

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report, @aaronbeall I've replicated the same behavior on my Chrome 87/ Win10.

What I've observed:
* we still get the info from `afterSetSourceDataAtCell` that the value changed https://jsfiddle.net/5Loj1w3e/
* adding an additional render or delay doesn't help
* as Aaron mentioned, it works well without `nestedRows` https://jsfiddle.net/ux3tzf17/. It doesn't break when we simply add `nestedRows: true`, but when we pass the nested data structure.

**Comment by aaronbeall** [comment]
Another odd observation, if you log `hot.getSourceData()` after setting the data, it looks like the data itself does not change on step 4 above (though it does change in step 2). (Also, unrelated, but `getSourceData()` returns all the child rows as parent rows.)

**Comment by AMBudnik** [comment]
> Also, unrelated, but `getSourceData()` returns all the child rows as parent rows

True. I've mentioned that subject here  https://github.com/handsontable/handsontable/issues/7236

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **NestedRows grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7510

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
@aaronbeall could you please check if that works now? I tested it with 12.3.0 and it should work fine now.

**Comment by aaronbeall** [comment]
@AMBudnik Hm, it looks like the bug still exists. Sorry I did not respond sooner! The issue is specifically that set data at cell no longer works *after* `updateSettings()` is called. Here's an example:
![image](https://user-images.githubusercontent.com/2973900/215506933-448e8fdf-1d71-4891-9878-09d09329361d.png)

Note that "set data at cell" works on Name 1 and Name 0, but then after clicking on Update Settings it no longer works on the other cells.

**Comment by aaronbeall** [comment]
@AMBudnik This appears to be fixed with https://github.com/handsontable/handsontable/issues/9844 - the underlying cause was that `updateSettings({ data })` was a call to `updateData()` which broke the data references

**Comment by AMBudnik** [comment]
🥳 Thanks for checking that, @aaronbeall that great news!
