### ISSUE TITLE
is there a way to disable arrows navigation wraparound?

### ISSUE THREAD

**Issue by am21** [handsontable/handsontable#7432]
### Description
Using down arrow to navigate a table, if we hit the last cell at the bottom, it will go back to the top at the next column. Is there a way to disable this behavior and just stay at the bottom?

### Your environment
* Handsontable version: 8.2.0
* Browser Name and version: Firefox 83.0
* Operating System: Win10

**Comment by aarondfrancis** [comment]
@am21 Check out [autoWrapRow](https://handsontable.com/docs/8.2.0/Options.html#autoWrapRow) and [autoWrapCol](https://handsontable.com/docs/8.2.0/Options.html#autoWrapCol).

I think setting those to false should give you what you're looking for ✌️

**Comment by am21** [comment]
exactly what I needed, awesome, thanks!
