### ISSUE TITLE
using cell reference when column headers are set, results in reference error

### ISSUE THREAD

**Issue by appsworld** [handsontable/handsontable#7433]
### Description

When you reference a cell that has a column header, it appears the logic that gets the reference to the cell fails to appropriately map the cell hence resulting in a #REF! error.

### Steps to reproduce

1. Create a Handsontable
2. Name the column headers instead of setting it to true, i.e     colHeaders: An Arrray of Columns vs  colHeaders: true
3. Reference the column headers either in code or in the rendered UI and they will result in a reference error. In our example fiddle you can type =$HAND$1 + 2 in any column except the HAND column

### Demo

An ideal state of of using references:
https://jsfiddle.net/epw7ts0q/

The version with the #REF!  Reference Error
https://jsfiddle.net/o7s1yqfu/

Tried in version 8.0.2 as well. You can find those fiddles at https://jsfiddle.net/epw7ts0q/1 and https://jsfiddle.net/o7s1yqfu/1 respectively 
### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome
* Operating System: Linux and Windows

**Comment by AMBudnik** [comment]
Hey @appsworld 

in the example, with the `REF` error you pass a different data.
If you want to use a variable (`HAND`) it has to be defined https://jsfiddle.net/8ofd4610/ it is not a header title.

**Comment by appsworld** [comment]
@AMBudnik , does that mean even when you have column headers you cannot reference the headers by their name? I.e https://jsfiddle.net/cp89yab2/. Looking at the tolabel() function which is used by CellReference in https://github.com/handsontable/formula-parser/blob/0df57d6b13710ed6f39ac7fb531b8346d867c8ea/src/helper/cell.js the column value is derived the cell index and the upper case alphabet. Should we not use the column headers as the reference instead?

**Comment by AMBudnik** [comment]
Column header names `A, B, C, ...` and Row header names `1, 2, 3,...`  are a representation of a cell address `A1, B1, A2,...` but you always refer to a cell coordinate. If I change the column name (like here) https://jsfiddle.net/9ztdbfcy/ it doesn't affect the formula.
I can imagine column name-based reference being pretty useful but this Formula plugin currently does not support it.
