### ISSUE TITLE
Using freezeColumn with fixedColumnsLeft turned on freezes too many columns

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7435]
### Description

Using `freezeColumn` with `fixedColumnsLeft` turned on freezes too many columns. 

### Steps to reproduce

1. Go to demo (when I freeze column index `5`)

**Result**
We have column `0` and column `5` frozen.

![image](https://user-images.githubusercontent.com/10757813/102463145-04ab6b80-404b-11eb-9b60-5cc5c01ac40c.png)

### Additional info
I need to use `unfreezeColumn` on index `0` to get the desired result https://jsfiddle.net/zy60x7jw/9/ 

### Demo

https://jsfiddle.net/zy60x7jw/2/ - 8.2.0 (broken)
https://jsfiddle.net/zy60x7jw/1/ - 8.0.0 (broken)
https://jsfiddle.net/zy60x7jw/4/ - 7.0.0 (broken)
https://jsfiddle.net/zy60x7jw/6/ - 6.0.0 (broken)

### Your environment
* Handsontable version: 8.2.0
_It doesn't seem to be a regression_
* Browser Name and version: Chrome 87
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
It works the same in v8.3.0 https://jsfiddle.net/handsoncode/ufekd4L3/

**Comment by swistach** [comment]
This behaviour is explained here: https://github.com/handsontable/handsontable/issues/6845#issuecomment-770819052 - unfreezing do the opposite action to that one I've explained there.
And it's work exactly as we expect🙂
