### ISSUE TITLE
[8.0.0+] Freeze column when used with fixedColumnsLeft freezes the wrong column index

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7436]
### Description

Freeze column when used with fixedColumnsLeft freezes the wrong column index. Even though https://github.com/handsontable/handsontable/issues/7435 is not a regression I belive that they may be connected.

### Steps to reproduce

1. Scroll horizontally to see that versions 8+ fix column B (incorrect) and older versions freeze column F (correct)

### Demo

https://jsfiddle.net/handsoncode/dwk61u2b/ - 8.2.0 (broken)
https://jsfiddle.net/handsoncode/q86fzest/ - 8.0.0 (broken)
https://jsfiddle.net/handsoncode/7seb2nku/ - 7.4.2 (working well)

### Connected issue
* https://github.com/handsontable/handsontable/issues/7435 - Using `freezeColumn` with `fixedColumnsLeft` turned on freezes too many columns

### Your environment
* Handsontable version: 8+
* Browser Name and version: Chrome 87
* Operating System: Windows 10

**Comment by wszymanski** [comment]
@AMBudnik It seems that bug is effect of using [fixedColumnsLeft](https://handsontable.com/docs/8.3.0/Options.html#fixedColumnsLeft) with improper value. It can't be `boolean`, it should be a `number` 🙂 I can't reproduce it when using numeric values for mentioned settings. Could you confirm it?

**Comment by AMBudnik** [comment]
Hey @wszymanski it's like a deja vu... I guess that we've already had this conversation. 
And yes. You are right. We can close this issue.
