### ISSUE TITLE
[8.0.0+] The use of fixedRowsTop: 1 with fixedRowsBottom: true adds an additional border on the vertical scroll

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7437]
### Description

The use of `fixedRowsTop: 1` with `fixedRowsBottom: true` adds an additional border on the vertical scroll.

Connected to: https://github.com/handsontable/handsontable/issues/7356 

### Steps to reproduce

1. Scroll vertically

Initial state
![image](https://user-images.githubusercontent.com/10757813/102470292-134a5080-4054-11eb-8b5b-84873b883fe4.png)

After scrolling
![image](https://user-images.githubusercontent.com/10757813/102470326-1e9d7c00-4054-11eb-8665-900786131bfa.png)

After scrolling without `fixedRowsBottom: true`, or any numeric value for the bottom row option, on before v8
![image](https://user-images.githubusercontent.com/10757813/102470406-396ff080-4054-11eb-83ea-df65697f5243.png)

### Additional info
It might be connected to the fact that in 7.4.2 setting up `true` for those options had the same effect as setting up `1` https://jsfiddle.net/handsoncode/vre07s65/

### Demo

https://jsfiddle.net/handsoncode/8bh2c9af/ - 8.2.0 (broken)
https://jsfiddle.net/handsoncode/7sfh1e2g/ - 8.0.0 (broken)
https://jsfiddle.net/handsoncode/bn2h7rc0/ - 7.4.2 (working well)

### Your environment
* Handsontable version: 8+
* Browser Name and version: Chrome 87
* Operating System: Windows 10

**Comment by wszymanski** [comment]
@AMBudnik 

Does `fixedRowsBottom` set to `boolean` make sense? Docs says that there should be passed `number`: https://handsontable.com/docs/Options.html#fixedRowsBottom.

**Comment by AMBudnik** [comment]
@wszymanski that's right. And I'm going to close this ticket 👍

**Comment by warpech** [comment]
Regarding boolean, I guess it's a similar story to setting the value as a string, which I reported a while ago: https://github.com/handsontable/handsontable/issues/6494. 

I think we should implement type checking, because these errors never seem to end.
