### ISSUE TITLE
add checkbox into nestHeaders

### ISSUE THREAD

**Issue by 1442897550** [handsontable/handsontable#7441]
### Description
    when i want to add an checkbox into nestHeaders, it seems normal. But when click it to change, the console report an error which i can't resolve.

### Steps to reproduce

1.
![image](https://user-images.githubusercontent.com/51740528/102762010-a7008180-43b2-11eb-8093-49ce8e0832b7.png)
2.
![image](https://user-images.githubusercontent.com/51740528/102762053-b4b60700-43b2-11eb-84ee-f3851243e42f.png)

### Your environment
* Handsontable version:8.2.0
* Browser Name and version:Google Chrome 87.0.4280.88
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Hey @1442897550 

The checkbox itself doesn't cause any errors on my device (same system/browsers as yours). 
Can you fill my demo https://jsfiddle.net/handsoncode/by05Lqz9/ with your settings? 

If those settings are confidential please send the demo to support@handsontable.com

**Comment by 1442897550** [comment]
> Hey @1442897550
> 
> The checkbox itself doesn't cause any errors on my device (same system/browsers as yours).
> Can you fill my demo https://jsfiddle.net/handsoncode/by05Lqz9/ with your settings?
> 
> If those settings are confidential please send the demo to [support@handsontable.com](mailto:support@handsontable.com)

your example really works for me. thank u so much.

**Comment by AMBudnik** [comment]
I believe that we can close this ticket as there's no reply for 2 weeks.

Please send me an email if you still experience the same behavior.
