### ISSUE TITLE
Breaking behaviour: Handsontable inconsistently not rendering all rows

### ISSUE THREAD

**Issue by GoodMorgon** [handsontable/handsontable#7447]
I'm using handsontable v8.1.0 with two different settings depending on if a variable is set to true or false. 

Please consider that sharing a full working example will be very time-consuming, however I think the below will be sufficient to showcase the issue.

In my application I've wrapped my logic concerning handsontable in a vue-instance. But, when using my "module" with shared_mode = true handsontable does not properly render all rows, despite new data clearly being there.

Consider the below indicative code of how my handsontable is setup and what type of settings I've used.

```

example = new Vue({

       data: {
               excel          : null,
               excel_data     : null,
               excel_colnames : null,

               shared_mode    : false
              },

    methods: {
              initialize: function () {

                  this.excel = new Handsontable(
                                                document.getElementById('hot-table'),
                                                {
                                                 licenseKey         : 'non-commercial-and-evaluation',
                                                 data               : null,
                                                 colHeaders         : null,
                                                 columns            : null,
                                                 hiddenColumns      : {
                                                                       columns: [2, 3],
                                                                       indicators: true
                                                                      },
                                                 width              : '100%',
                                                 height             : '100%',
                                                 maxRows            : 50000,
                                                 minRows            : 100,
                                                 rowHeaders         : true,
                                                 columnSorting      : true,
                                                 stretchH           : 'all',
                                                 className          : "htCenter",
                                                 allowInsertColumn  : false,
                                                 allowRemoveColumn  : false,
                                                 contextMenu        : true,
                                                 filters            : false,
                                                 dropdownMenu       : false,
                                                 manualColumnResize : true,
                                                 manualRowResize    : true,
                                                 renderAllRows      : false
                                                 }
                                                 )

                  this.excel.colPlugin = this.excel.getPlugin('hiddenColumns')

              },
              update: function () {

                    this.excel.updateSettings({colHeaders: this.excel_colnames})

                    console.log(this.excel_data) # picture of chrome devtools console output is this statement

                    this.excel.loadData(this.excel_data)

              },
              shared_mode: function () {

                  if (this.excel) this.excel.updateSettings({columns: this.column_settings})

              }

    },
    computed: {
               column_settings: function () {

                   if (this.shared_mode === true) {

                       return [
                               {editor: false},
                               {editor: false},
                               {editor: false},
                               {editor: false},
                               {editor: false},
                               {
                                type: 'numeric',
                                allowInvalid: false
                               }
                              ]

                   } else {

                       return [
                               {
                                type: 'date',
                                dateFormat: 'YYYY-MM-DD',
                                correctFormat: true,
                                datePickerConfig: {
                                                   firstDay: 1,
                                                   showWeekNumber: true,
                                                   numberOfMonths: 2
                                                  },
                                allowInvalid: false
                               },
                               {
                                type: 'numeric',
                                allowInvalid: false
                               },
                               {
                                type: 'numeric',
                                allowInvalid: false
                               },
                               {
                                type: 'numeric',
                                allowInvalid: false
                               },
                               {
                                type: 'numeric',
                                allowInvalid: false
                               }
                              ]

                   }

               }
    },

    mounted: function () {

        this.initialize()
        this.excel.updateSettings({columns: this.column_settings})

    }

})

```
![#1](https://user-images.githubusercontent.com/55554176/102920650-5f015d80-448b-11eb-8976-029c964058f1.png)
![#2](https://user-images.githubusercontent.com/55554176/102920653-60cb2100-448b-11eb-8d1b-270259158af3.png)

As you can see the data clearly contains 195 rows, but only 129 rows are rendered. The 129 rows is the previous value from when this.excel_data had another dataset. I.e. handsontable does not render the new rows correctly. No error or warning messages are printed either.

I've tried different possible solutions, such as upgrading to 8.2, changing settings, execution order of update statements... none of them worked. The only possible solution I've not tried yet is to destroy the table and reinitiate it upon each display, but this shouldn't be necessary.

If a fix could be found to this issue it would be of great help!

**Comment by AMBudnik** [comment]
Hi @GoodMorgon 

I can see that the 195-element array printed in the console is the `this.excel_data`. 

I have some questions that may help us to solve the case.
1. What do you get when you print [getData()](https://handsontable.com/docs/8.2.0/Core.html#getData) after loading that 195-element array (195 elements or 129)?
2. Does anything change when you select or edit a cell (it triggers an additional render)?
3. Are you able to replace `this.excel_data` with a helper `Handsontable.helper.createSpreadsheetData(200, 10)` and check if it loads 200 rows?
4. May it be possible that the structure of the `this.excel_data` dataset is not consistent after the 129th element?

**Comment by GoodMorgon** [comment]
Hello,

Printing `getData()` shows 129 elements. The table works just as usually otherwise, it's just that somehow it refuses to update the data.

Using `Handsontable.helper.createSpreadsheetData(200, 10)` will not print 200 rows, but 129 :/

I've checked the data structure after the 129th row, everything is in order (the fact that the helper function also produces inconsistent number of rows speaks to this being an internal issue of handsontable...)

![#3](https://user-images.githubusercontent.com/55554176/103027098-83c20780-4555-11eb-80e7-46b2d9811142.png)

**Comment by AMBudnik** [comment]
>  have now tested the code with v.7.4.2 and there it works

That is a crucial piece of information. Have you read our [migration guide](https://handsontable.com/docs/8.2.0/tutorial-migration-guide.html)? We might have changed something that relates to your settings/used features.

> I believe the issue is with the update of the column settings. If there is a function for handsontable to print it's 'state' I can do that and provide and upload it here for you.

There's a core method called [getSettings](https://handsontable.com/docs/8.2.0/Core.html#getSettings) but nearly all the settings are changed for the prototype https://jsfiddle.net/handsoncode/9mn2jwxd/

![image](https://user-images.githubusercontent.com/10757813/103408313-3865b580-4b62-11eb-9784-42d446620d93.png)

**Comment by GoodMorgon** [comment]
@AMBudnik Thank you for your reply.

I believe the bug is related to the hideColumn plugin (https://handsontable.com/docs/8.2.0/demo-hiding-columns.html) as I need to call the `render()` function upon each call where the plugin is related for everything to work. To my understanding this should not be necessary.

Is there any indication of a possible update for this plugin? Or is there any other way I can dynamically hide columns without using the hideColumn plugin?

Thanks

**Comment by AMBudnik** [comment]
>  I need to call the render() function upon each call where the plugin is related for everything to work

It depends. When user clicks the Hide/Show column via context menu everything is already handled and you do not see to add the `render()`. However, if you want to use the plugin API to showColumn/hideColumn then the `render()` call is needed.

Demo https://jsfiddle.net/handsoncode/296Lxu8m/

**Comment by AMBudnik** [comment]
I guess that we can close this ticket and move to email. If there's anything else that concerns you and the rows are not being renderer after using the `render()` method please contact me at support@handsontable.com
