### ISSUE TITLE
componentWillMount and compnentWillUpdate warnings in console from HandsOnTable

### ISSUE THREAD

**Issue by henricook** [handsontable/handsontable#7450]
### Description
When looking at the console for my app during development I have to constantly look around these warnings:

Desired fix: Prefix with UNSAFE or update to new React guidelines

### Steps to reproduce
1. Put HOT on a page
2. Load page
3. Open console and refresh

### Demo
![image](https://user-images.githubusercontent.com/82004/103212216-284f9b00-4902-11eb-96d3-71aa3dc2da59.png)

### Your environment
* Handsontable version: 8.2.0
* React version: 17.0.1
* Browser Name and version: Firefox 84
* Operating System: Linux/Ubuntu

**Comment by wojciechczerniak** [comment]
Hi @henricook 

They are prefixed: https://github.com/handsontable/react-handsontable/blob/7a581606e1a7c4f51c3ea642e8b8f5c28c6fd6be/src/helpers.tsx#L200-L209 for React version 16.3+

Which version do you use? Are you running strict mode?

**Comment by henricook** [comment]
Hi @wojciechczerniak - I am running strict mode! Is that my issue? That it reports even if you've made the appropriate name changes?

**Comment by henricook** [comment]
Hmm I removed my strictmode tags and it's still showing

**Comment by wojciechczerniak** [comment]
As the warning states, it's possible "to suppress this warning in **non-strict mode**".

We can't rewrite the wrapper to new methods yet. Using non-prefixed/prefixed approach gives us backward compatibility with older React versions.

**Comment by henricook** [comment]
I've got my `App` wrapping StrictMode tags removed and the warning still appears but I'll assume this is something I'm doing wrong and close this, sounds like you know all about it. Thanks for the tips!
