### ISSUE TITLE
handsontable 是否兼容IE浏览器11的版本?

### ISSUE THREAD

**Issue by gulanglei** [handsontable/handsontable#7452]
handsontable 是否兼容IE浏览器11的版本?

**Comment by AMBudnik** [comment]
Hi @gulanglei 

Yes, we support Internet Explorer 11 (if that was the question)
![image](https://user-images.githubusercontent.com/10757813/103399588-05132e80-4b42-11eb-947f-1b94d6e972a1.png)

src: https://handsontable.com/docs/8.2.0/tutorial-compatibility.html

**Comment by gulanglei** [comment]
thank you very much
