### ISSUE TITLE
Filtering with Hide and Show Columns misaligns the filter input and the source column

### ISSUE THREAD

**Issue by saleemepoch** [handsontable/handsontable#7456]
### Description
I am using the "Filter as you type" tutorial here: https://handsontable.com/docs/8.2.0/demo-filtering.html - but with Hide/Unhide columns plugin. When the columns are hidden, I expect the filter input to shift along with the columns underneath it. But the filter columns retains its position, resulting in the input changing the source column adjacent to it, and not right below it.

### Steps to reproduce
1. Hide a column
2. Then type something in the filter input and it will filter the column adjacent to it.

### Demo
https://jsfiddle.net/hru7fjsv/

Here is the code being used for your convenience:
```

  var dataObj = [
    ['Lorem', 'ipsum', 'dolor', 'sit', '12/1/2015', 23],
    ['adipiscing', 'elit', 'Ut', 'imperdiet', '5/12/2015', 6],
    ['Pellentesque', 'vulputate', 'leo', 'semper', '10/23/2015', 26],
    ['diam', 'et', 'malesuada', 'libero', '12/1/2014', 98],
    ['orci', 'et', 'dignissim', 'hendrerit', '12/1/2016', 8.5]
  ];
  // Event for `keydown` event. Add condition after delay of 200 ms which is counted from time of last pressed key.
  var debounceFn = Handsontable.helper.debounce(function (colIndex, event) {
    var filtersPlugin = hot.getPlugin('filters');
  
    filtersPlugin.removeConditions(colIndex);
    filtersPlugin.addCondition(colIndex, 'contains', [event.target.value]);
    filtersPlugin.filter();
  }, 200);
  
  var addEventListeners = function (input, colIndex) {
    input.addEventListener('keydown', function(event) {
      debounceFn(colIndex, event);
    });
  };
  
  // Build elements which will be displayed in header.
  var getInitializedElements = function(colIndex) {
    var div = document.createElement('div');
    var input = document.createElement('input');
  
    div.className = 'filterHeader';
  
    addEventListeners(input, colIndex);
  
    div.appendChild(input);
  
    return div;
  };
  
  // Add elements to header on `afterGetColHeader` hook.
  var addInput = function(col, TH) {
    // Hooks can return value other than number (for example `columnSorting` plugin use this).
    if (typeof col !== 'number') {
      return col;
    }
  
    if (col >= 0 && TH.childElementCount < 2) {
      TH.appendChild(getInitializedElements(col));
    }
  };
  
  // Deselect column after click on input.
  var doNotSelectColumn = function (event, coords) {
    if (coords.row === -1 && event.target.nodeName === 'INPUT') {
      event.stopImmediatePropagation();
      this.deselectCell();
    }
  };
  
  var hot = new Handsontable(document.getElementById('example3'), {
    data: dataObj,
    colHeaders: true,
    rowHeaders: true,
    className: 'as-you-type-demo',
    filters: true,
    colWidths: 100,
    afterGetColHeader: addInput,
    beforeOnCellMouseDown: doNotSelectColumn,
    hiddenColumns: {
      indicators: true
    },
    contextMenu: ['col_left', 'col_right', 'hidden_columns_hide', 'hidden_columns_show'],
  });


```

**Comment by AMBudnik** [comment]
Thank you for sharing the example, @saleemepoch 

I've replicated the issue. That example (posted in the docs) wasn't prepared to work with `hiddenColumns`. Even though it was working before v8 it hasn't been tested using hidden columns. In v8 we've made some crucial changes.

When you use `hiddenColumns` in v8+ your `colIndex` changes (in 7.4.2 it was the same index). However, you can use the newly introduced indexMapper to get the correct index of the column after it has been hidden. Here's an example https://jsfiddle.net/handsoncode/fjuk2v0g/

Let me know if it works for you, @saleemepoch 

**Reference**
Migration guide: https://handsontable.com/docs/8.0.0/tutorial-migration-guide.html 
Filters in headers: https://handsontable.com/docs/8.0.0/demo-filtering.html
