### ISSUE TITLE
handsontable.d.ts missing some updates for some plugins

### ISSUE THREAD

**Issue by mohamedaymenkarmous** [handsontable/handsontable#7457]
### Description
I was upgrading my project from the version "handsontable": "^7.4.2" to the version "handsontable": "^8.2.0" because I wanted to use the new version of the event afterColumnMove() that was published since the version 8.0.0rc-1 (details: #6005).
The new version of that function is supposed to have [4 parameters instead of 2 starting from the version 8.0.0](https://handsontable.com/docs/8.0.0/Hooks.html#event:afterColumnMove). But when I updated the package I get the following error:
```
error TS2322: Type '(movedColumns: any, finalIndex: any, dropIndex: any, movePossible: any, orderChanged: any) => void' is not assignable to type '(columns: number[], target: number) => void'.
  node_modules/handsontable/handsontable.d.ts:1757:7
    1757       afterColumnMove?: (columns: number[], target: number) => void;
               ~~~~~~~~~~~~~~~
    The expected type comes from property 'afterColumnMove' which is declared here on type 'GridSettings'
```

So, when I looked back to the [handsontable.d.ts#L1757](https://github.com/handsontable/handsontable/blob/34793d5e9ee10176941ebe2589996daa80b5effd/handsontable.d.ts#L1757) we can see that during the last commit it seems that the function parameters were not updated and from the same commit, the actual version of the project is 8.0.2: [package.json#L13](https://github.com/handsontable/handsontable/blob/34793d5e9ee10176941ebe2589996daa80b5effd/package.json#L13)

### Steps to reproduce

1. Install the project with the latest version (8.0.0 at least)
2. Enable the `manualRowMove` feature:
```
hotSettings = {
manualColumnMove: true,
afterColumnMove: function(movedColumns, finalIndex, dropIndex, movePossible, orderChanged) {}
};
```

### Demo
Since I'm not familiar with the main project handsontable and I used "@handsontable/angular": "^6.0.1" which implements the mentioned version and steps, I skipped the demo for simplicity.

### Your environment
* Handsontable version: ^8.2.0
* Browser Name and version: Chrome 87.0.4280.88 (latest version)
* Operating System: Debian 9 (64 bits)

Thank you for your work, is it possible to update the handsontable.d.ts file or am I in the wrong path?

**Comment by wojciechczerniak** [comment]
Duplicate of #7400 and fixed in #7407. Thanks for reporting!

**Comment by mohamedaymenkarmous** [comment]
Thank you @wojciechczerniak 
I'm closing this issue since this is duplicate
But since this fix is not yet available in the master/main branch, is it going to be available soon or for the time being it's only available in the develop branch until all the version is going to be stable enough to be merged in the master/main branch?

**Comment by AMBudnik** [comment]
Hi @mohamedaymenkarmous we're starting a code freeze in a couple of days. The new version of Handsontable should be ready before the end of January.

**Comment by mohamedaymenkarmous** [comment]
Awesome!
Thank you
