### ISSUE TITLE
Error thrown when I try to edit cell with renderer "TextRenderer"

### ISSUE THREAD

**Issue by ankitgoyal100** [handsontable/handsontable#7460]
### Description
I have a cell with renderer "TextRenderer". I set the renderer with this line of code:
```
      column.renderer = function (instance: any, td: any, row: any, col: any, prop: any, value: any, cellProperties: any) {
        if (typeof value === "boolean" || value == null) {
          return Handsontable.renderers.CheckboxRenderer.apply(this, arguments);
        }

        return Handsontable.renderers.TextRenderer.apply(this, arguments);
      }
```

The column is of `type` = `checkbox`

When I try to edit the cell with the `TextRenderer`, it throws this error:
<img width="1029" alt="Screen Shot 2021-01-07 at 5 51 12 PM" src="https://user-images.githubusercontent.com/3400675/103953855-f06e0200-5110-11eb-8278-a38c4064b94a.png">

### Your environment
* Handsontable version: 8.2.0
* React version: 17.0.1
* Browser Name and version: Google Chrome
* Operating System: Mac OS X

**Comment by AMBudnik** [comment]
Hi @ankitgoyal100 

You can add the text as an editor to handle data alteration https://jsfiddle.net/handsoncode/2akmgzdn/

**Comment by ankitgoyal100** [comment]
@AMBudnik That worked, thank you!
