### ISSUE TITLE
Add ESLint rule for forbidden module imports

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7473]
### Description

Since the Handsontable was modularized some of the modules are now part of the developer API. If those modules are wrongly imported within the source code the Base version imported in the developer's app won't be able to remove the unused code (it applies mostly in the CommonJS environment or within older bundlers like Webpack 3 and lower).

The following modules are sensitive to the described issue:
 * for Cell Types
   * :x: `import { registerCellType } from '../cellTypes';`
   * :white_check_mark: `import { registerCellType } from '../cellTypes/registry';`
 * for Editors
   * :x: `import { registerEditor } from '../editors';`
   * :white_check_mark: `import { registerEditor } from '../editors/registry';`
 * for Plugins
   * :x: `import { registerPlugin } from '../plugins';`
   * :white_check_mark: `import { registerPlugin } from '../plugins/registry';`
 * for Renderers
   * :x: `import { registerRenderer } from '../renderers';`
   * :white_check_mark: `import { registerRenderer } from '../renderers/registry';`
 * for Validators
   * :x: `import { registerValidator } from '../validators';`
   * :white_check_mark: `import { registerValidator } from '../validators/registry';`
 * for i18n
   * :x: `import { registerLanguageDitionary } from '../i18n';`
   * :white_check_mark: `import { registerLanguageDitionary } from '../i18n/registry';`

It's easy to make a mistake, even more so for an inexperienced developer.

The solution may be adding a rule to the ESLint which would inform the developer (with explanation) about its mistake.

### Your environment
* Handsontable version: 8.3.0
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
Tested locally with the combination of:
- Webpack 4.29
- Webpack 5
- node 10, 12, 14, 14
- mode: production
- mode: development

**Comment by AMBudnik** [comment]
Thank you for adding and testing the changes.

I'm closing this issue as a part of the released Handsontable v8.3.2.
