### ISSUE TITLE
Class names should be merged instead of overwritten

### ISSUE THREAD

**Issue by chaosflaws** [handsontable/handsontable#7476]
### Description
In some cases, column and cell settings should be merged instead of overwritten.

### Demo
http://jsfiddle.net/chaosflaws/1zj25ryv/5/

Here, I would expect the first cell to have a blue background and green text, but the class name of the row is overridden by the cell.

### Your environment
* Handsontable version: current
* Browser Name and version: Firefox 84.0.2
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @chaosflaws 

by specifying the `className` in `cell` option you give that `className` a priority to overwrite anything that is given on the instance and columns level. 

But, you can use more than one class name within the `className` option. Here http://jsfiddle.net/wtxc6kbj/1/ we have oldclass and newclass being used for `0, 0` cell.

**Comment by chaosflaws** [comment]
I am aware of the possibility, but it does not solve the problem at hand. If e. g. I wanted to assign a particular class to a column and afterwards apply another class to a certain row (by setting the className on every cell), there is no easy way to know which columns have a certain className and which don't.

**Comment by AMBudnik** [comment]
We can also do it like this http://jsfiddle.net/handsoncode/ue1aqnh3/16/
But.. you are right. An option to replace/add a className by specifying className for instance/columns/cell would definitely be more developer-friendly.

**Comment by wojciechczerniak** [comment]
I don't agree. That would make clearing the `classNames` very difficult. An empty string would be added to the end of `classList`.

`cells` can be callback to modify the `cellProperties` add/remove or overwrite `classNames` completely. When used as an object and `className` as a string the properties should use cascading settings and overwrite the less specific ones (ie. cell settings overwrite columns settings). For any other use case scenario it is up to the developer to merge the `classNames` to their requirements.

```ts
cells: function(row, col. cellProperties) {
  cellProperties.className = cellProperties.className + ' newClass';
}
```

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback.
See you there!
