### ISSUE TITLE
The Handsontable modules do not support TypeScript

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7489]
### Description

The modularized version of the Handsontable does not support TypeScript. Currently, only the Base module (`import Handsontable from 'handsontable/base'`) can be imported without an error.

![image](https://user-images.githubusercontent.com/571316/105493918-4e2a4e80-5cba-11eb-836f-3dcc76639a2c.png)

List of modules that should support TS:
 * `handsontable/editors`, and [specific editors](https://github.com/handsontable/handsontable/blob/develop/package.json#L115);
 * `handsontable/renderers`, and [specific renderers](https://github.com/handsontable/handsontable/blob/develop/package.json#L459);
 * `handsontable/validators`, and [specific validators](https://github.com/handsontable/handsontable/blob/develop/package.json#L495);
 * `handsontable/cellTypes`, and [specific cell types](https://github.com/handsontable/handsontable/blob/develop/package.json#L71);
 * `handsontable/plugins`, and [specific plugins](https://github.com/handsontable/handsontable/blob/develop/package.json#L307);
 * `handsontable/i18n`, and [specific languages](https://github.com/handsontable/handsontable/blob/develop/package.json#L163);

### Your environment
* Handsontable version: 8.3.0
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
Tested locally with v11.

**Comment by konstantintieber** [comment]
This is awesome to see! Thanks for your work. Will it be released with v11 or could it also be available via a minor release soon?

**Comment by AMBudnik** [comment]
Hi @konstantintieber we do not plan to add any minor release before v11.

**Comment by AMBudnik** [comment]
Hi @konstantintieber we just released the new version.

If you would like to read more about the newest release here's everything listed and described https://github.com/handsontable/handsontable/issues/8949

**Comment by konstantintieber** [comment]
@AMBudnik is there a plan to support `handsontable/helpers` as well?

**Comment by AMBudnik** [comment]
@konstantintieber at the moment `helpers` are not exposed and there are no plans to alter that behavior.
