### ISSUE TITLE
returning false on beforeChange callback has no effect

### ISSUE THREAD

**Issue by ghiculescu** [handsontable/handsontable#749]
The [documentation](https://github.com/warpech/jquery-handsontable/wiki/Events#events-available-in-09) states that:

```
To cancel all edit, return false from the callback or set array length to 0 (changes.length = 0).
```

For the `beforeChange` event. However, returning `false` does not cancel the edit. It seems that in [line 1536](https://github.com/warpech/jquery-handsontable/blob/master/dist/jquery.handsontable.full.js#L1536) the call to the callback is done via `instance.runHooks`, but the [runHooks](https://github.com/warpech/jquery-handsontable/blob/master/dist/jquery.handsontable.full.js#L2585) function on line 2585 doesn't return anything.

Setting the length of the `changes` array to 0 seems to work. Is returning `false` no longer supported?

**Comment by Shemulik** [comment]
It is not fixed

**Comment by AMBudnik** [comment]
Hi @Shemulik This issue was closed 9 years ago. Could you please provide us your configuration and steps to replicate the issue at support@handsontable.com
