### ISSUE TITLE
Return a instance in afterInit hook

### ISSUE THREAD

**Issue by LancelotLewis** [handsontable/handsontable#7493]
### Description

In vue or react wrapper, we need use ref to get the instance of handsontable, it's a lit bit of tedious. I think maybe add a callback params in afterInit hook is a easy way to get instance.

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @LancelotLewis 

The `afterInit` does not return the instance but `this` is the instance. Here I'm using the `countRows()` instance method within `afterInit` hook https://jsfiddle.net/handsoncode/zhjwpLyu/

**Comment by LancelotLewis** [comment]
You are right, it work on react, but it's work on vue
