### ISSUE TITLE
copyPasteEnabled property is missing from hiddenColumns.Settings typings

### ISSUE THREAD

**Issue by john-swallow-cenduit** [handsontable/handsontable#7499]
### Description
The copyPasteEnabled setting used with hiddenColumns is missing from the typings file handsontable.d.ts. 

namespace hiddenColumns {
    interface Settings {
      columns?: number[];
      indicators?: boolean;
    }
  }

This does not prevent its use - but it does require a Typescript user to cast the Settings to any in order to set it.
It also prevents the normal grid settings configuration from being used to set the value.

public hotSettings: Handsontable.GridSettings = {
  hiddenColumns: {
    copyPasteEnabled: false    
  }
}

### Steps to reproduce
Either:
1. Try to add hiddenColumns to your GridSettings and set the copyPasteEnabled property. Typescript will complain that there is no such setting on hiddenColumns.Settings
Or:
1. In Typescript code try to set this.hot.getSettings().hiddenColumns.copyPasteEnabled. This will not compile due to the property not being available on hiddenColumns.Settings.

This last can be worked around by casting to any:
(this.hot.getSettings().hiddenColumns as any).copyPasteEnabled = false;
but this really shouldn't be necessary if this is a valid property, as it is.

### Demo

Neither of these are helpful as they don't perform the typings checks that produce the issue.

### Your environment
* Handsontable version: 8.0.0 (I have checked 8.1.0 and 8.2.0 also which all have the same issue).
* Browser Name and version: Chrome 88.0.4324.104
* Operating System: WIndows 10

**Comment by AMBudnik** [comment]
Thank you for sharing this report @john-swallow-cenduit 

we also do not mention this option in the docs. 

![image](https://user-images.githubusercontent.com/10757813/106259053-fee69f80-621e-11eb-8e39-29aed117ed97.png)

But we have a test scenario for it https://github.com/handsontable/handsontable/blob/8b6e9c404ac0aa4fb211a6bedbd68b7fbd81c658/src/plugins/hiddenColumns/__tests__/plugins/copyPaste.spec.js#L105

ps. it should also be added for [`hiddenRows`](https://github.com/handsontable/handsontable/blob/8b6e9c404ac0aa4fb211a6bedbd68b7fbd81c658/src/plugins/hiddenRows/hiddenRows.js#L32)

**Comment by NeSy** [comment]
> ### Description
> The copyPasteEnabled setting used with hiddenColumns is missing from the typings file handsontable.d.ts.
> 
> namespace hiddenColumns {
> interface Settings {
> columns?: number[];
> indicators?: boolean;
> }
> }
> 
> This does not prevent its use - but it does require a Typescript user to cast the Settings to any in order to set it.
> It also prevents the normal grid settings configuration from being used to set the value.
> 
> public hotSettings: Handsontable.GridSettings = {
> hiddenColumns: {
> copyPasteEnabled: false
> }
> }
> 
> ### Steps to reproduce
> Either:
> 
> 1. Try to add hiddenColumns to your GridSettings and set the copyPasteEnabled property. Typescript will complain that there is no such setting on hiddenColumns.Settings
>    Or:
> 2. In Typescript code try to set this.hot.getSettings().hiddenColumns.copyPasteEnabled. This will not compile due to the property not being available on hiddenColumns.Settings.
> 
> This last can be worked around by casting to any:
> (this.hot.getSettings().hiddenColumns as any).copyPasteEnabled = false;
> but this really shouldn't be necessary if this is a valid property, as it is.
> 
> ### Demo
> Neither of these are helpful as they don't perform the typings checks that produce the issue.
> 
> ### Your environment
> * Handsontable version: 8.0.0 (I have checked 8.1.0 and 8.2.0 also which all have the same issue).
> * Browser Name and version: Chrome 88.0.4324.104
> * Operating System: WIndows 10

Another solution (similar to yours) is to define it in the properties : 
`
      hiddenRows: {
        copyPasteEnabled: false,
      } as any,
`

**Comment by AMBudnik** [comment]
Again thank you for your input @john-swallow-cenduit @NeSy 
We have updated the page.
