### ISSUE TITLE
Undo does not immediately undo rows added by a paste operation

### ISSUE THREAD

**Issue by john-swallow-cenduit** [handsontable/handsontable#7501]
### Description
For me this is definitely an undesired behaviour. You may well consider it more of a feature request. I post it here for comment.

If I paste data such that the HandsonTable makes rows for the data to go into and then hit undo - in my opinion it should reverse BOTH operations - the pasting of the data AND the addition of the rows. It puts the addition of the rows in as a separate undoable action and you have to undo them individually.

### Steps to reproduce
1. Open https://jsfiddle.net/handsoncode/6jxnat70/
2. Select the first cell of the final row ('Mike')
3. Paste the following three lines of data:

a
b
c

4. Click ctrl-z once

Expected result: the single undo should undo the pasted data AND the creation of the two rows it made to accommodate the new data.

Actual result: I have to click undo three times to get back to the same position - which is twice more than the number of operations I made to get here.

### Demo
Issue can be seen using the default jsfiddle template.
https://jsfiddle.net/handsoncode/6jxnat70/

### Your environment
* HandsonTable version: 8.3.0
* Browser Name and version: Chrome 88.0.4324.104
* Operating System: Windows 10

**Comment by john-swallow-cenduit** [comment]
I reckon that undoing the entire action as a block is probably a tall order due to the way that the Undo/Redo basically puts event invocations onto a stack and there is no composite "make a bunch of rows that look like this" type change. However, the situation could be SIGNIFICANTLY improved if the paste operation caused a SINGLE add row instruction to go onto the stack that could then be undone in a single action. That way a paste resulting in 10 new rows would only take 2 undo actions to reverse rather 10 + 1 = 11. 

Right now the paste action will fire afterCreateRow 10 times once each for each of the 10 rows it wants rather than once with row count = 10

**Comment by john-swallow-cenduit** [comment]
In the following I added console.log to show the afterCreateRow events that are happening:
https://jsfiddle.net/jg08yvhc/2/

**Comment by AMBudnik** [comment]
Hi @john-swallow-cenduit 

I fully agree. Currently, we need to use the undo too often. I've mentioned the situation of summaries https://github.com/handsontable/handsontable/issues/7323 that makes all undo operations tiresome.

And that is why I've created this feature request https://github.com/handsontable/handsontable/issues/6731 where we will be able to stack those operations and avoid using CMD + Z more than needed.

As https://github.com/handsontable/handsontable/issues/6731 relates to a wide range of changes I would like to close this issue as a duplicate.
However, I strongly encourage you to leave any propositions/changes to the mentioned topic.
