### ISSUE TITLE
getSourceDataAtRow in modifyRowData event causes stack exceeded error

### ISSUE THREAD

**Issue by mirkogeest** [handsontable/handsontable#7504]
### Description
I'm migrating my code from handsontable 7.4.2 to 8.3.0 and @handsontable/react from 3.1.2 to 4.0.0

I have. function to change the color of a row conditionally, depending on a value of the same row, but I get an error:
"handsontable.full.min.js:34 Uncaught RangeError: Maximum call stack size exceeded".

Is there a workaround to set the row color conditionally depending on a value of the same row?
Thank you!

### Steps to reproduce
Create a react file like this:
```
class ExampleComponent extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div id="example-component">
        <HotTable
          settings={
            {
              modifyRowData(row) {
                const rowData = this.getSourceDataAtRow(row);
                // Here comes code to change the color of the rowData...
              },
            }
          }/>
      </div>
    );
  }
}

ReactDOM.render(<ExampleComponent />, document.getElementById('example'));
```

Run it and you'll see the error at the console

### Demo
https://jsfiddle.net/951yqrxa/1/

### Your environment
* Handsontable version: 8.3
* Browser Name and version: Chrome Version 88.0.4324.96 (Official Build) (x86_64)
* Operating System: MacOs Catalina 10.15.4

**Comment by swistach** [comment]
Hi @mirkogeest,
accordingly to the changes we made in v8 (precisely in #6678) calling `getSourceDataAtRow` method in `modifyRowData` hook leads to the infinite loop.
A better option, in this case, is to use conditional formatting by custom renderers: https://codesandbox.io/s/practical-taussig-8lxq3?file=/src/App.js
I attached explanations in inline comments.
I close this issue but feel free to reopen it if the above solution doesn't solve your conditional formatting problem.
