### ISSUE TITLE
What is the best way of syncing handsontable with data source

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#7511]
Hi,

I'm using handsontable to show complex set of data and every time something changes in handsontable I have to sync this change back to data source. Sometimes changing of one cell will update values in subsequent cells (clear them or populate) and what I do right now to achieve this - after user changes data at specific cell  I do required changes in data source model and call `loadData` after that.

So my update cycle looks like this:

Initial data load from data source using `data` property -> user changes a cell -> main data source is modified according to some business logic (more than 1 model property may be changed on this step) -> `hot.loadData` is called to reflect data source changes.

That works fine for some simple cases, but when I start using column sorting or other features that affects handsontable visual data set I need to respectivly update my data source (sort or filter) so when I next time call load data it looks the same way as it looked in handsontable grid before the update. 

So my question is: 
Is there any recommended way of working with handsontable in one way sync manner without calling extra `loadData` for a whole dataset but to have an ability to reflect subsequent cells changes, and keep any sorting or filtering made via handsontable?

**Comment by AMBudnik** [comment]
Hi @andrewQwer 

I'm not sure if I follow each of the steps you need to take to accomplish the goal. However, it seems that the suspend rendering functionality (added in v8.3.0) is exactly what you need. Have you already tested it? Here's some more info https://handsontable.com/docs/8.3.0/tutorial-suspend-rendering.html 

If you'd like to discuss it further let me know by email (support@handsontable.com)

**Comment by andrewQwer** [comment]
Ok, not exactly what I meant but it looks like this option can help to optimize performance. Thank you!
