### ISSUE TITLE
Cells become more blue when clicking with Ctrl+Left Mouse Button

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#7513]
### Description
Cells become more blue when clicking with Ctrl+Left Moust Button

![image](https://user-images.githubusercontent.com/710513/107011486-bf80fb80-67a8-11eb-90bd-2d3736d75438.png)

Top cell was clicked 1 time.
Bottom cell was clicked 6 times with Ctrl button.

Not sure if that was designed to work this way.

**Comment by AMBudnik** [comment]
Hi @andrewQwer 

This is a functionality of multi-layer selection. You can turn it off by adding 

`selectionMode: 'range'`

docs: https://handsontable.com/docs/8.3.0/Options.html#selectionMode

**Comment by andrewQwer** [comment]
But the same cell can be selected multiple times and become more blue than those that was selected only 1 time, is that correct behavior?

**Comment by AMBudnik** [comment]
Can you record the behavior with a tool that shows clicks? I am not able to replicate this behavior in v8.3.0 using Chrome 87/ Win 10

**Comment by andrewQwer** [comment]
https://user-images.githubusercontent.com/710513/107080095-d43dad80-6801-11eb-8b56-a5bf3adbde94.mp4

I just hold Ctrl and do mouse clicks

**Comment by AMBudnik** [comment]
Yes. That is planned. We allow creating layers of selection regardless of the coordinates of the selected range (in this case the range is just one cell).

**Comment by andrewQwer** [comment]
Ok, got it, thanks.
