### ISSUE TITLE
CSS is tree shaken by Webpack 4

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#7516]
### Description
Since we declare `sideEffects` as an array, only files that are covered by this list are not tree shaken on production builds if they were not used as a reference in code. Currently, we only have language files since they are automatically registered and can be simply imported to be used: `import 'handsontable/languages/pl-PL`. However, there is another category of files that are commonly used in such a manner, CSS files i.e.: `import 'handsontable/dist/handsontable.full.css'`. In version `v8.3.0` such an import will be tree shaken and the CSS will be striped from the production build.

### Steps to reproduce

1. Use Webpack 4 with `css-loader` and (optional) extract css
2. Import CSS as JS module: 
  a. `import 'handsontable/dist/handsontable.full.css'` note, it's not assigned to a variable
  b. `import style from 'handsontable/dist/handsontable.full.css'` it is assigned to a variable but DO NOT use it in code
3. Build in `production` mode. Tree shaking is then used and `sideEffects` applied

### Solution

Add `*.css` to the `sideEffects` array. BTW. AFAIK we can use patterns, no need to list all the files:

```js
"sideEffects": [
  "*.css",
  "./languages/*"
]
```

### Your environment
* Handsontable version: 8.3.0
* Browser Name and version: any
* Operating System: any

Inform zen#26006

**Comment by aninde** [comment]
This issue will be fixed by the upcoming v8.3.1.

Tested locally with combination of:
- Webpack 4.29
- Webpack 5
- node 10, 12, 14, 14
- mode: production
- mode: development
