### ISSUE TITLE
Formula doesnt get calculated properly on load

### ISSUE THREAD

**Issue by minalkumar2893** [handsontable/handsontable#7522]
The Formulas doesn't get calculated properly on load. but when i change something or just double click on the source cell, it gets calculated properly. i tried this on a jsfiddle that i found in the formulas demo page: https://jsfiddle.net/minalkumar2893/Ltvk9zqb/7/
Also attaching a loom video: https://www.loom.com/share/600d948db42f44dfa73202256c3cd3b5

**Comment by AMBudnik** [comment]
Hi @minalkumar2893 we have a similar issue here https://github.com/handsontable/handsontable/issues/4678 I will merge your case with that one
