### ISSUE TITLE
Upgrade ESLint and its plugin and parser dependencies

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7531]
### Description

The monorepo PR updates the ESLint that causes disabling some rules mentioned [here](https://github.com/handsontable/handsontable/pull/7434/files#r566090558). It would be nice if that rules can be enabled or at least analyzed if they fit our code style. 

Another nice to have is to upgrade ESLint and its parser to the latest version to support static syntax checking for our `scripts/` which are written in native ES. Right now the files are omitted. The lib uses the [babel-eslint](https://www.npmjs.com/package/babel-eslint) parser which is deprecated. 

These packages could also be upgraded:
```json
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsdoc": "^20.3.1",
```

### Your environment
* Handsontable version: -
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment]
Officially released under Handsontable v9.
