### ISSUE TITLE
Register Vue Component as Renderer / Editor

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#7535]
As far as I can tell from the docs, the only way to register a custom renderer or editor is to pass in a function or register it globally. Alternatively we can create `HotColumns` that serve as editors and renderers. What I would really like to do is register a vue component as a renderer or editor. Is that possible?

I see that internally, when `HotTable` sees a component is wraps it up to meet the function definition https://github.com/handsontable/vue-handsontable-official/blob/master/src/HotTable.vue#L129. Could that be exposed or shimmed somewhere?

My desired experience would be something like this: 

```js

// import the .vue component
import LinkRenderer from './renderers/link'; 

Handsontable.renderers.registerRenderer('LinkRenderer', LinkRenderer);
```

Is something like that possible now, or could it be added? 

Thanks!

**Comment by swistach** [comment]
Hi @aaronbeall, @mismith, @h8art,
We merged wrapper for vuejs into our main repository, `handsontable/handsontable`, and now it's available as a monorepo.
We also transfer all issues into one common issue board.
