### ISSUE TITLE
Row and column changes cause cellMeta to be emptied

### ISSUE THREAD

**Issue by chen-ABC** [handsontable/handsontable#7538]
### Description
Row and column changes cause cellMeta to be emptied
I want to keep CellMeta  data
### Steps to reproduce
1.Click the setcellmeta button, and then position 1,1 font turns red
2.Create rows or columns, or delete rows and columns
3.cellMeta tobe empty

### Demo
https://jsfiddle.net/enogx7ka/1/

### Your environment
* Vue wrapper version: 2.6.10
* Handsontable version: 7.2.2
* Browser Name and version: chrome 64
* Operating System: window 10

**Comment by AMBudnik** [comment]
Hey @chen-ABC we should keep the bug reports opened. Otherwise, it will be hard to track the level of issues and the progress of future development.

**Comment by jansiegel** [comment]
Seems to be fixed with #7263. @AMBudnik, could you confirm?

**Comment by AMBudnik** [comment]
Great news! @jansiegel is right @chen-ABC 
When we update to the newest version the cell metadata is no longer removed on alteration of the dataset. You can test it here https://jsfiddle.net/quogeLy0/1/ 

If you'd have any issues, please let me know @chen-ABC 
I'm closing this issue as solved.
