### ISSUE TITLE
Undoing removed rows does not revert to initial state if some rows were trimmed

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#7542]
### Description
To reproduce this issue, some prerequisites are necessary. You have to initialize Handsontable with `trimRows` option defined as an array of indexes. If we remove all rows and undo this action, then we get a different set of rows.

### Steps to reproduce
1. Select all rows
2. Remove rows using a context menu
3. Undo removing rows (using the context menu or keyboard shortcut)

### Demo
https://jsfiddle.net/cnfa2z1u/

https://user-images.githubusercontent.com/11849621/108362700-5cee1d80-71f4-11eb-855f-673eed5730d7.mp4

### Your environment
* Handsontable version: v2+
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
Related to https://github.com/handsontable/handsontable/issues/6934.

**Comment by AMBudnik** [comment]
This issue is no longer replicable in Handsontable v12.1.3 https://jsfiddle.net/mkbqz7cd/ 

When we undo the action, all the correct rows are back.
