### ISSUE TITLE
Repeatedly changing the height will cause it to crash.

### ISSUE THREAD

**Issue by sinbino** [handsontable/handsontable#7546]
### Description

Repeatedly changing the height will cause it to crash.

### Steps to reproduce

1. Go to jsfiddle below.
2. Press the "SWITCH HEIGHT" button repeatedly.
3. It freezes after about 20 times and the console reports a js error.
```
[Vue warn]: Error in callback for watcher "mergedHotSettings": 
(found in <HotTable>)
RangeError: Invalid array length
    at Array.concat (<anonymous>)
    at getListWithInsertedItems (handsontable.full.js:55764)
    at PhysicalIndexToValueMap.insert (handsontable.full.js:39878)
    at handsontable.full.js:40049
    at Map.forEach (<anonymous>)
    at MapCollection.insertToEvery (handsontable.full.js:40048)
    at handsontable.full.js:75461
    at IndexMapper.executeBatchOperations (handsontable.full.js:75019)
    at IndexMapper.insertIndexes (handsontable.full.js:75454)
    at helpers.ts:64
```
The handsontable 8.1.0 only demo will not crash.
The handsontable 8.1.0 and @handsontable/vue 5.1.0 demos will crash.

Our requirements are as follows.
* I must use @handsontable/vue.
* I need to dynamically change the height of the handsontable to fit the window size. To do so, I dynamically change the handsontable settings.height parameter.

### Demo

This will cause a crash.
handsontable 8.1.0 + @handsontable/vue 5.1.0
https://jsfiddle.net/sinbino/19r26cq3/

This will not cause a crash.
handsontable 8.1.0 only
https://jsfiddle.net/sinbino/nmw8j4s5/

### Your environment
* Vue wrapper version: 5.1.0
* Handsontable version: 8.1.0
* Browser Name and version: Chrome 86.0.4240.80
* Operating System: MacOS Catalina 10.15.7（19H2）

**Comment by sinbino** [comment]
@aninde 
Thank you.

**Comment by AMBudnik** [comment]
Hi @sinbino 

I have the pleasure to let you know that Handsontable v12 where this issue is fixed is live.

For everyone who is tracking changes to this topic please check our release notes https://handsontable.com/docs/release-notes/#_12-0-0 and the migration guide https://handsontable.com/docs/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls
