### ISSUE TITLE
Vue 2: While loading Handsontable v8.0.0 with nestedRows applied we get fewer rows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7548]
### Description

While loading Handsontable v8.0.0 with `nestedRows` applied we get fewer rows.

### Steps to reproduce

1. Open all the demos to check what's loaded in Handsontable

Vue loading Handsontable v 7.4.2 and lower
![Zrzut ekranu 2020-11-19 o 14 27 51](https://user-images.githubusercontent.com/10757813/99672251-70fa7580-2a73-11eb-9101-8fea19c0f23c.png)

Vue loading Handsontable v 8.0.0 and higher
![Zrzut ekranu 2020-11-19 o 14 28 01](https://user-images.githubusercontent.com/10757813/99672317-866f9f80-2a73-11eb-959a-466284279b94.png)

### Demo

* 7.0.0 https://jsfiddle.net/AMBudnik/32sm9nuy/ - vue (ok)
* 7.4.2 https://jsfiddle.net/AMBudnik/pugy6850/ - vue (ok)
* 8.0.0  https://jsfiddle.net/AMBudnik/c4nfmg6x/ - vue (not ok)

Other wrappers for compare
* 8.2.0 https://jsfiddle.net/AMBudnik/41yqpds9/ - angular ok
* 8.2.0 https://jsfiddle.net/AMBudnik/6uqmjp13/ - react ok

### Your environment
* Vue wrapper version: 5.1.0
* Handsontable version: 8.0.0
* Browser Name and version: Chrome 87
* Operating System: macOS Catalina 10.15.7

Send update on [forum](https://forum.handsontable.com/t/vue-204-vue-handsontable-5-x-nested-rows-only-first-level-is-visible/4825), and [forum](https://forum.handsontable.com/t/vue-204-doesnt-work-collapsible-rows-via-vue-handsontable-7-4-2/5006)

**Comment by aninde** [comment]
This issue will be fixed by v8.4.0 https://jsfiddle.net/5ewLdcgh/.

**Comment by AMBudnik** [comment]
Awesome! Thank you for fixing guys!
