### ISSUE TITLE
minSpareRows > 0 crashes in datamap.get

### ISSUE THREAD

**Issue by nachoab** [handsontable/handsontable#755]
for (var i = 0, ilen = sliced.length; i < ilen; i++) {
          out = out[sliced[i]];
          if (typeof out === 'undefined') {
            return null;
          }
        }

error: out is undefined
when you specify columns in which an array is inside an object, like:

            columns: [
                {data: 'geometry.coordinates.1'},
                {data: 'geometry.coordinates.0'}
            ]

in this case, because of the last field in priv.settings.data with all null values, 'out' its undefined at last iteration an so it crashes.

A possible solution is checking that 'out' has a null value inside the loop:

        for (var i = 0, ilen = sliced.length; i < ilen; i++) {
          if (!out) {
            return null;
          }
          out = out[sliced[i]];
          if (typeof out === 'undefined') {
            return null;
          }
        }

**Comment by AMBudnik** [comment]
Can you please prepare a full [JSFiddle demo](https://jsfiddle.net/api/post/library/pure/) for your example?

**Comment by AMBudnik** [comment]
Issue will stay closed till a needed demo or an author's reply.
