### ISSUE TITLE
setState called inside afterSelectionEnd hang hot

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#7554]
### Description
When we want to use `setState` inside `selection` `hooks` (but maybe it is similar to other `hooks`) the `handsontable` act slowly. Maybe this is caused by trigger `updateSettings` by `setState`, but this needs further investigation.

### Steps to reproduce

1. https://github.com/handsontable/support/issues/137

### Demo

https://jsfiddle.net/u9m0pL7o/17/

### Your environment
* React wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by jansiegel** [comment]
I can't seem to reproduce this issue, @aninde, could you help?

**Comment by AMBudnik** [comment]
@jansiegel this was the original demo https://jsfiddle.net/c1o7pbLv/ and at the moment of reporting was extremely laggy but when I test it with the latest version it works well.

**Comment by aninde** [comment]
I confirm, it works correctly. I checked on `Safari 15.2 (17612.3.6.1.6)` and `Chrome 99.0.4844.35`  on macOS 12.1 (21C52) and on `Edge 98` and `FF 97.0.1` on Windows 10 Pro.

**Comment by warpech** [comment]
Closing as not reproducible
