### ISSUE TITLE
Custom contextMenu with React

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#7559]
### Description
Enable to use react component as a custom `contextMenu` or `dropdownMenu`. 
It definitely needs a lot of considerations about how to approach it.

The idea comes from @mx2323 in https://github.com/handsontable/handsontable/issues/6811

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback.
See you there!
