### ISSUE TITLE
Using `setState` within `afterFilter` hook call results in the cancelation of filtering

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7567]
### Description

Using `setState` within `afterFilter` hook call results in the cancelation of filtering.

### Steps to reproduce

1. Filter out any values via **filter by value** option.

**Result**
The values as still there. They are removed if you comment our the `setState` method in the `afterFilter` hook.

### Demo

https://jsfiddle.net/eudmgt63/2/

### Related issues
* https://github.com/handsontable/react-handsontable/issues/132
* (forum origin) https://forum.handsontable.com/t/call-setstate-in-after-hooks-will-not-trigger-rerender/4761

### Your environment
* React wrapper version: 4.0.0
* Handsontable version: 8.0.0
* Browser Name and version: Chrome 86
* Operating System: macOS Catalina 10.15.6

**Comment by AndyStobirski** [comment]
I've encountered this bug as well. It's rather annoying and pretty much sinks any plan of mine to use HandsOnTable due to my requirements.

**Comment by masry707** [comment]
@AndyStobirski I've changed the Handsontable version to 7.4.2 and it works fine with me.

Here is a working example using version 7.4.2
https://jsfiddle.net/ysx9dgLq/

**Comment by AndyStobirski** [comment]
@masry707 That works perfectly. Thanks for taking the time to share this with me.

**Comment by murattishkul** [comment]
@masry707 any idea how to make it to work in 9.0.0 version?

**Comment by masry707** [comment]
@murattishkul sorry I have not tried it.
but you can use this [fiddle](https://jsfiddle.net/ysx9dgLq/) and install v9.0.0 and check if it works

**Comment by masry707** [comment]
@murattishkul it seems not working yet. check [this](https://jsfiddle.net/03upqgmz/2/)
and I don't know how to make it work.

**Comment by masry707** [comment]
@murattishkul it seems not working yet. check [this](https://jsfiddle.net/03upqgmz/2/)
and I don't know how to make it work.

**Comment by AMBudnik** [comment]
Hi @murattishkul 
The @masry707 is right. This issue hasn't been scheduled for development yet.

**Comment by murattishkul** [comment]
I got kinda of workaround for this
I store conditionsStack in localstorage in afterFilter hook:
`localStorage.setItem("planningOpenTableConditions", JSON.stringify(conditionsStack));`
and I apply those filters by using addCondition in afterInit hooks like this:
`let conditions = [];
    try {
      conditions = JSON.parse(localStorage.getItem("planningOpenTableConditions") || "[]");
      let plugin = context.getPlugin("Filters");
      for (let i = 0; i < conditions.length; i++) {
        plugin.addCondition(
          conditions[i].column,
          conditions[i].conditions[0].name,
          conditions[i].conditions[0].args,
          conditions[i].operation
        );
      }
      plugin.filter();
    } catch (err) {
      console.log(err);
    }`
hope this helps

**Comment by aninde** [comment]
Fixed with v12.0.0. Tested locally on React demo example.

**Comment by AMBudnik** [comment]
Hi @AndyStobirski @masry707 @murattishkul we just released Handsontable v12 where this issue is fixed. Here https://handsontable.com/docs/release-notes/#_12-0-0 you can read more about the changes.

If you would have any questions or concerns please contact us at support@handsontable.com
