### ISSUE TITLE
Sum Fields.

### ISSUE THREAD

**Issue by cbanicolas** [handsontable/handsontable#757]
Hi, i need to sum some cols with the total value of the column.

Then i should make a validation because the sum cant exceed 10 for example.

Here it is a capture:

http://oi39.tinypic.com/38v3q.jpg

For example, i need in the last row the total values for the columns like it is displayed in the image.

Any way to do it ? Thanks alot !

**Comment by AMBudnik** [comment]
Issue closed from lack of demo. If you still need an answer to that question, please prepare a [JSFiddle demo](http://jsfiddle.net/) for your issue.
