### ISSUE TITLE
Use Angular component as an editor and renderer

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#7573]
⚠️  WIP

### Description
Very similar feature to what we did for Vue wrapper: https://github.com/handsontable/vue-handsontable-official/issues/101 and we're doing for React wrapper (add link later).

- [x] We already have `<hot-column>` component
  - [ ] Docs: We have an example with declared `<hot-column>` but maybe we should have a specific example to explain that and the basic example should be simpler
  - [ ] Docs: Add an example with `<hot-column>` and a `for` loop (is this possible in the Angular?)
- [ ] Support Angular components as `hot-renderer` or `hot-editor`
  - [ ] Docs: Add an example with `hot-renderer`
  - [ ] Docs: Add an example with `hot-editor`

#### With each column declared by hand (done 👍 )
```typescript
@Component({
  template: `
  <div>
    <hot-table [colHeaders]="true" [rowHeaders]="true">
        <hot-column data="id" [readOnly]="true" title="ID"></hot-column>
        <hot-column data="name" title="Full name"></hot-column>
        <hot-column data="address" title="Street name"></hot-column>
    </hot-table>
  </div>
  `,
})
class AppComponent { ... }
```

#### With `*ngFor` loop
```typescript
@Component({
  template: `
  <div>
    <hot-table [colHeaders]="true" [rowHeaders]="true">
        <hot-column *ngFor="let item of items; index as i;" [data]="item.data" [readOnly]="item.readOnly" [title]="item.title"></hot-column>
    </hot-table>
  </div>
  `,
})
class AppComponent { ... }
```

### Custom renderer / editor
We've choose to use attributes for components inside `hot-column` to mark them as `hot-renderer` or `hot-editor` or both at the same time.

```typescript
@Component({
  template: `
  <div>
    <hot-table [colHeaders]="true" [rowHeaders]="true">
        <hot-column data="id" [readOnly]="true" title="ID">
           <date-viewer hot-renderer></date-viewer>
           <date-picker hot-editor></date-picker>
        </hot-column>
        <hot-column data="address" title="Street name">
           <date-picker hot-renderer hot-editor></date-picker>
        </hot-column>
    </hot-table>
  </div>
  `,
})
class AppComponent { ... }
```

* Pros:
  - Single component can be market both as `hot-renderer` and `hot-editor`
  - They're not always needed. When component is both the renderer and the editor we can omit the directives. This gives us clean and simple markup that other options can't provide [1].
* Cons:
  - Attribute name might be in conflict with other component attributes (very unlikely because we have `hot-` namespace)

#### As a helper function
From what we have learned in Vue we have to wrapp the component to match Handsontable interface. The wrapper function can be a helper so if someone wants to use `settings` object but a custom Angular renderer (s)he can use the helper for that.

```typescript
// columns as a function example (but with better function name)
import { HotTable, HotColumn, WrapRenderer } from '@handsontable/angular';

const components = [[ ... ], ... ];

const hotSettings = {
  columns: function (col, row) {
    return {
      renderer: WrapRenderer(components[col][row])
    }
  }
}
```

### Editor component interface
We will need an interface for components that can be used as an editor

```typescript
// should be imported from handsontable.d.ts ?
interface CellEditor {
  focus: () => void;
  open: () => void;
  close: () => void;
  getValue: () => any;
  setValue: (newValue: any) => void;
  init: () => void;
}

@Component({ ... })
class AngularCellEditor implements CellEditor {

}
```

This way we can wrap component to work with our Editor lifecycle:

```typescript
import { BaseEditor } from 'handsontable';

getCellEditorFromComponent(component: CellEditor) {
  return class extends BaseEditor {
    getValue() {
      return component.getValue();
    }
    setValue(value) {
      component.setValue(value);
    }
  }
}
```

### Renderer component interface
Similar to CellEditor interface, but renderer currently is just a render function.

```typescript
interface CellRenderer {
  value: string;
  td: HTMLTableCellElement;
  instance: HandsontableInstance;
  row: number;
  column: number;
  prop: any;
  cellProperties: Handsontable.CellProp;
}

@Component({ ... })
class AngularCellRenderer implements CellRenderer {

}
```

We have no renderer lifecycle but it will be easier to wrap to HOT:

```typescript
getCellRendererFromComponent(component: CellRenderer) {
  return function(instance, TD, row, col, prop, value, cellProperties) {
    let cachedComponent = cache.get(TD);

    cachedComponent.$data.value = value;
    cachedComponent.$data.td = TD;
    cachedComponent.$data.row = col;
    cachedComponent.$data.prop = prop;
    cachedComponent.$data.cellProperties = cellProperties;

    return TD.appendChild(cachedComponent.$el);
  }
}
```

### One component to rule them all (implement both)

```typescript
@Component({ ... })
class AngularCellRenderer implements CellRenderer, CellEditor {

}
```

### Notes

- [ ] Handle error when both `<hot-column>` and `<hot-table columns="[ ... ]">` are defined
- [ ] Handle error when where `<hot-column>` slot has more than one/two/supported components
- [ ] Handle error if `<hot-column>` children are not marked as `hot-renderer` or `hot-editor` 
- [ ] Handle error if `<hot-column renderer="CutomRender">` and `<hot-column><custom-renderer hot-renderer></custom-renderer></hot-column>` are both defined. Same for editor.
- [ ] Check if component implements correct interface methods
- [ ] Find a way to provide context to the component. State and router for example.

**Comment by AMBudnik** [comment]
Thank you for sharing @wojciechczerniak 

That's a perfect idea for the Github Discussions panel. Let's discuss it there.
