### ISSUE TITLE
Zoom breaks dropdown scrollbar

### ISSUE THREAD

**Issue by john-swallow-cenduit** [handsontable/handsontable#7583]
### Description
Scroll bar on a dropdown with enough items to require it should remain anchored to the drop down list itself and the top and bottom should line up with the list on all levels of browser zoom. But it breaks on zoom levels that are not 100% in various ways.

### Steps to reproduce
Several different issues
1. Zoom to 110%
2. Open the dropdown list with lots of items in it (Chassis color) and scroll to the bottom.
Expected: Scrollbar is butted up against the drop down body. Scroll bar extends to the bottom of the listbox and no further.
Actual: Scrollbar is floating away from the listbox and is longer than the listbox

It gets worse as you zoom further.

![image](https://user-images.githubusercontent.com/58601615/108863192-d87f0e80-75e8-11eb-91ed-1e4c198bb38d.png)

1. Zoom to 90%
2. Open the dropdown list with lots of items in it (Chassis color) and scroll to the bottom.
Expected: Scrollbar is butted up against the drop down body. Scroll bar extends to the bottom of the listbox and no further.
Actual: Horizontal scrollbar has kicked in

![image](https://user-images.githubusercontent.com/58601615/108863509-2eec4d00-75e9-11eb-9b48-9e90dd488e1b.png)

Under 100% zoom it looks ok:
![image](https://user-images.githubusercontent.com/58601615/108863375-0cf2ca80-75e9-11eb-8126-bd5cf91a029c.png)

Clearly there are a number of issues open that relate to zoom:
https://github.com/handsontable/handsontable/issues/7527

but this one does not appear among these. I don't think it's a duplicate.

### Demo
https://jsfiddle.net/0scvhdxu/5/

### Your environment
* Handsontable version: 8.3.1 but also applies to 8.0.0
* Browser Name and version: Chrome Version 88.0.4324.182 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing this scenario, @john-swallow-cenduit 

I will add it to the **Interoperability problems using zoom/system UI scaling and some core features** task reported at https://github.com/handsontable/handsontable/issues/7527

We temporarily close all the issues that are part of the bigger task. This way we have a solid list of issues for a certain subject and can schedule the fix effectively.

I will update you as soon as we fix this issue.
