### ISSUE TITLE
Handsontable in angular material tab

### ISSUE THREAD

**Issue by jhgeluk** [handsontable/handsontable#7592]
### Description

I have a Handsontable inside multiple angular material tabs. Whenever I select a tab, I want to get the Handsontable instance and update the column headers.

However, when I try to get the Handsontable instance using the hotId, the getInstance() method returns: undefined.

What could be the issue? The table is displaying properly with the initial data.

The tabs are also being lazy-loaded, making sure there is only **one** handsontable component at the time.

### Steps to reproduce

1. Create 3 Angular material tabs (with for loop) 
2. Add handsontable component in tab content
3. Try to access handsontable with getInstance() method.

### Your environment
* Handsontable version: 6.13.4
* Browser Name and version: Chrome (version: 88.0.4324.192)
* Operating System: macOS

**Comment by swistach** [comment]
Hi @jhgeluk,
We fixed `HotRegisterer` in `@handsontable/angular@5`, which requires Handsontable v7+. The latest version of the wrapper is `6.0.1`.

If you upgrade your setup, Handsontable should work well.

**Comment by jhgeluk** [comment]
This does not solve the issue.

**Comment by swistach** [comment]
Ok, I reopen the issue then. May I ask you to share a demo (e. g.: on stackblitz or codesandbox)?
It will help us a lot to investigate the problem.

**Comment by jhgeluk** [comment]
I fixed it by not using the lazy loading functionality of Angular Material Tabs/Expansion table and creating multiple Handsontables and tracking their ID's.

**Comment by AMBudnik** [comment]
I can close this issue.

If anyone would stumble across this issue please send the demo to me at support@handsontable.com
