### ISSUE TITLE
visibleCalculator returns error result

### ISSUE THREAD

**Issue by huangjinqiang** [handsontable/handsontable#7594]
### Description
[rows|columns]VisibleCalculator will return error result in some cases

### Steps to reproduce
1. scroll the table to such position, just hide the rowHeader
![image](https://user-images.githubusercontent.com/26299039/109463948-d44b6900-7aa0-11eb-8520-1135b13f8cce.png)
2. get the rowsVisibleCalculator by ``` aa.view.wt.wtViewport.rowsVisibleCalculator ```

### Demo
https://codepen.io/huangjinqiang/pen/rNWdoBO

### Your environment
* Handsontable version: seems all versions

**Comment by AMBudnik** [comment]
Hi @huangjinqiang 

How do you hide the rowHeaders?

I wasn't able to replicate the issue using Chrome 87 on Windows 10. I've tried to scroll, change the viewport size, and editor some cells. Can you record the error appearance?

**Comment by huangjinqiang** [comment]
hi @AMBudnik

> hide the rowHeaders

just scroll the table to such position while the rowHeaders is out of sight
![GIF 2021-3-2 10-31-17](https://user-images.githubusercontent.com/26299039/109587925-db2ab800-7b42-11eb-8e14-4f612164e419.gif)

btw, seems the ``` calculate ``` doesnt work as expected

**Comment by AMBudnik** [comment]
Thank you for sharing the additional information. However, I am not sure if I understand what is your request for this method rowsVisibleCalculator (it is an internal method). I also do not get any error in the console (I also tried Firefox to be sure).

Can you please tell that how you try to use the rowsVisibleCalculator in your application?

**Comment by huangjinqiang** [comment]
![GIF 2021-3-2 19-53-36](https://user-images.githubusercontent.com/26299039/109645018-397e8780-7b91-11eb-8086-ea18b98f5f6a.gif)
as u can see, i dblclick to focus the cell in row 4 column G，but scroll caused by the wrong visibleCalculator , i finally focus To the cell in row 3 column G.

i may be easy to reproduce if you set ``` .body { height 600px } ```

**Comment by AMBudnik** [comment]
Thank you for sharing the additional details.

I wasn't logging the `rowsVisibleCalculator` so I wasn't able to get the spot when the selection breaks and we have two cells selected instead of one. Now I've replicated the issue.

Example with logs made of the `afterScrollVertically` hook https://codepen.io/aleksandra-budnik/pen/QWGBZqW?editors=0010

Reproduction on Chrome 87 / Windows 10

![bug](https://user-images.githubusercontent.com/10757813/110102886-9783b880-7da5-11eb-8754-82db38659644.gif)

For those who want to replicate the issue: 
* scroll by dragging the scrollbar very slowly (it's easy to miss the null for `startPosition`.

**Comment by huangjinqiang** [comment]
thats it !

in the `calculate`, lack of information about how the `calculationType ` is designed , i have to wait for your fix.

thanks for you work!!

**Comment by AMBudnik** [comment]
The `view` element is not in the official API. We have also changed the privacy level of the `_wt` reference from

```js
aa.view.wt.wtViewport.rowsVisibleCalculator
```

to 

```js
 aa.view._wt.wtViewport.rowsVisibleCalculator
```

The result of the call in v12.
![Screenshot 2022-06-13 at 15 12 02](https://user-images.githubusercontent.com/10757813/173361312-0ea91c92-d345-4e75-8b0a-4cd74b67caa6.png)

I think that we can close the issue as there are no associated bug scenarios related to this thread. @huangjinqiang if you would like to chat more about the possibilities to replace the following logic with an official API-approach please send us a message at support@handsontable.com
