### ISSUE TITLE
Question: How can I inherit the metadata on copy/paste & autofill

### ISSUE THREAD

**Issue by jhgeluk** [handsontable/handsontable#7596]
### Description
I need to inherit the metadata from the origin cell when a copy/paste and/or autofill.fill action occurs.
I've tried multiple possibilities but everytime the new copied cells do not inherit the origin cell metadata.

How can I make this work?

**Comment by AMBudnik** [comment]
Hi @jhgeluk 

Handsonrable copies only raw data. However, if you wish to copy from Handsontable and paste to Handsontable you can use our API to gather metadata and attach it to the new cell. 

Here https://jsfiddle.net/t75wx9vu/ is an example of how to get a copied cell along with the comment. And here https://jsfiddle.net/t75wx9vu/2/ cell is copied with the `className` attached to it.

**Comment by jhgeluk** [comment]
Thanks, however this does not work for the Autofill.fill (drag) feature. Is there a solution for that too?

**Comment by AMBudnik** [comment]
The autofill is a different action for Handsontable as a different source of change.

We have a hook for autofill - `beforeAutofill` and `afterAutofill`. Here is how it would look https://jsfiddle.net/f6o2jx1n/ if you would like to autofill a single cell vertically down.

As you can see here

`let comment = this.getCellMeta(row-1, col).comment; //autofill vertically down`

I use row-1 as the index from the hook starts from the changed cell, not the origin cell.

Alternatively, you can also use `beforeChange`/`afterChange` hooks. It depends on the scope of the operations you'd like to cover.

**Comment by jhgeluk** [comment]
Awesome! Is there a way I can differentiate a vertical autofill from a horizontal autofill so I can make this work for both scenarios?

**Comment by jhgeluk** [comment]
I think I will have to use the modifyAutofillRange to select the origin metadata(s) since it will be more suitable for larger selections.

It would be nice to add inheriting metadata as a feature, I can't be the only one that is looking for this.

**Comment by AMBudnik** [comment]
> It would be nice to add inheriting metadata as a feature, I can't be the only one that is looking for this.

That's true. We've been asked for copying the cell with the background a couple of times.

When it comes to the direction of the autofill the first parameter is start, 2nd is end. You can compare if `start.row === end.row` (horizontal autofill) or `start.col === end.col` (vertical autofill)

**Comment by jhgeluk** [comment]
This only works when selecting one cell for the autofill action.

I've used the `modifyAutofillRange` hook and the `direction() `method from the handsontable library to determine the direction.
