### ISSUE TITLE
when i import handsontable with script tag ,i catch a error. detail information is "cannot read property 'Parser' of undefined".how to fix it. the important thing is i import "handsontable.js".i want to learn the source code

### ISSUE THREAD

**Issue by chrisTinaHAHA0** [handsontable/handsontable#7601]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @chrisTinaHAHA0 

It seems that you do not load the Formulas and currently those are required to run Handsontable.

This issue has been addressed here https://github.com/handsontable/handsontable/issues/4693

The _handsontable.js_ file does not contain dependencies. If you wish to load the script with dependencies attached you need to use _handsontable.full.js_.

**Comment by tinaChrist** [comment]
I'm sorry I didn't reply to your letter as soon as possible,it`s a busy day. and thanks for your solution. i will try as you saying

**Comment by tinaChrist** [comment]
> Hi @chrisTinaHAHA0
> 
> It seems that you do not load the Formulas and currently those are required to run Handsontable.
> 
> This issue has been addressed here #4693
> 
> The _handsontable.js_ file does not contain dependencies. If you wish to load the script with dependencies attached you need to use _handsontable.full.js_.

 I'm sorry I didn't reply to your letter as soon as possible,it`s a busy day. and thanks for your solution. i will try as you saying

**Comment by tinaChrist** [comment]
I'm sorry I didn't reply to your letter as soon as possible,it`s a busy day. and thanks for your solution. i will try as you saying

**Comment by AMBudnik** [comment]
Great, Thank you for the update @tinaChrist 
If that won't help please contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Hi @tinaChrist 

I just wanted to let you know that we have fixed the following issue in v9.

Please update and let me know if it works for you as well.

ps. here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
