### ISSUE TITLE
React componentWillMount has been renamed, and is not recommended for use...

### ISSUE THREAD

**Issue by djmisterjon** [handsontable/handsontable#7603]
### Description
ugly and lot of warn when use handsontable inside react project.
![image](https://user-images.githubusercontent.com/24865815/109788870-be8f8e00-7bdd-11eb-92e8-f7103d855fbb.png)

### Steps to reproduce
just use it .
```jsx
      <HotTable
        data={data}
      ></HotTable>
```

### Demo
https://codesandbox.io/s/declaring-column-settings-forked-ii075

### Your environment
* React version: 17.0.1
* Handsontable version: 8.1.0
* Browser Name and version: all
* Operating System: all

any way to disable those warn of fix it ? thanks 

**edit**: you can maybe try remove the `stricmode` on you side if your not able to rewrite the wrapper with last React methods.
I dont use stric on my side, but it seem handsontable use strict.
it can be a very small update. (no breakchange)
![image](https://user-images.githubusercontent.com/24865815/109790131-11b61080-7bdf-11eb-9934-63e3f00ca897.png)

**EDIT2**: disable warning are solution for avoid polluting console, it work fine but not recommended because we can bypass other important warning in dev.
![image](https://user-images.githubusercontent.com/24865815/109791613-a1a88a00-7be0-11eb-9158-b59e61f7c5f0.png)

**Please feel free to close if you wish, but I think we should keep this alive until a fix real is ​​proposed.**

**Comment by AMBudnik** [comment]
Hi @djmisterjon 

It seems that we have the same topic here https://github.com/handsontable/handsontable/issues/7450 

@wojciechczerniak referring to your comment here https://github.com/handsontable/handsontable/issues/7450#issuecomment-751701639 - would it be a good time to plan this change?

**Comment by AMBudnik** [comment]
If there is anything more to add to #7450 @djmisterjon please feel free to leave a comment.
