### ISSUE TITLE
Alternate color not correctly displayed

### ISSUE THREAD

**Issue by Maxoudela** [handsontable/handsontable#7607]
### Description

Even/odd alternations are not correctly applied for large table with scroll bar due to the virtual rendering mechanism.

When using different styles on odd and even rows with large tables and scrolling down, at some points row styles will be mixed; 'even' rows will be using 'odd' style, and vice versa.

When using my browser's DevTools to understand more what's going on, I see that the table structure in my DOM contains a portion of the table, due to the virtual rendering mechanism, and when scrolling, new rows will be added and others will be removed (from the top if we scroll down) so the row index in my table will be different than the one in my DOM with a 50% chance that they will not have the same parity (odd and even).

Relates to #6590
### Expected behavior

Rows should keep the same parity property even when virtual rendering mechanism is enabled.
### Steps to reproduce

Create a large, simple table using handsontable (about 100 rows).
Add different styles on odd and even rows, different background colors.

```
      /* Every even row */
.ht_master tr:nth-of-type(even) > td {
  background-color: mediumpurple;
}
/* Every odd row */
.ht_master tr:nth-of-type(odd) > td {
  background-color: aqua;
}
```

When previewing the table, styles are correctly applied on the first rows

![image](https://user-images.githubusercontent.com/8961645/109979629-62248f80-7cff-11eb-9b07-a4495b4d8e0c.png)

Scroll down until rows mix parity; 'even' rows will be using 'odd' style, and vice versa.

![image](https://user-images.githubusercontent.com/8961645/109979650-681a7080-7cff-11eb-84cd-7d278cd395b0.png)

row 8 is 'even' but has the 'odd' background color (aqua color).
### Demo

https://jsfiddle.net/SamHa/9k6rb14a/

To see the effect, scroll vertically at random area of the table (in the example above scroll to row 8).
### Environment

    Handsontable: version 8.3.0
    Browser: Chrome Version 88.0.4324.150
    Operating System: Windows 10 Pro build 19041.264

**Comment by Maxoudela** [comment]
The current work-around would be:
- Activate `renderAllRows: true` but that could be catastrophic for performance on specific big grids.
- Manually create a `odd` and `even` css class, and assign the class on the TD based on the actual row as mentioned [here](https://github.com/handsontable/handsontable/issues/6590#issuecomment-572477871)

**Comment by AMBudnik** [comment]
Hi @Maxoudela 

The CSS is set for TR element counted from the DOM, and Handsontable replaces those elements with scroll

![image](https://user-images.githubusercontent.com/10757813/110085550-86c94780-7d91-11eb-9b54-c79257696226.png)

To apply the row coloring I suggest using modulo in the cells settings, like so

```js
cells: function(row, col) {
    let cp = {}
    if (row % 2 !== 0) {
      cp.className = 'even'
    } else {
      cp.className = 'odd'
    }
    return cp
  }
```

Updated demo https://jsfiddle.net/q4bruo1w/1/

This way you do not need to worry about what is rendered and what's visible in the DOM.

**Comment by wojciechczerniak** [comment]
> The current work-around would be:
> * Activate `renderAllRows: true` but that could be catastrophic for performance on specific big grids.
> * Manually create a `odd` and `even` css class, and assign the class on the TD based on the actual row as mentioned [here](https://github.com/handsontable/handsontable/issues/6590#issuecomment-572477871)

Those are not "workarounds" but valid options to do what you expect with the virtual rendering feature.

IMO wont't fix
