### ISSUE TITLE
*** Remove Empty Row in React ****

### ISSUE THREAD

**Issue by pablomagalhaes** [handsontable/handsontable#7608]
### Description

I Woud like to remove empty row values.

### Steps to reproduce

1. 
2.
3.

### Demo

https://codesandbox.io/s/handsonttable-alter-removerow-issue-forked-tus7t

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @pablomagalhaes 

I see that the rows are already removed. To make them remove only if those are empty you can use the `isRowEmpty` flag https://handsontable.com/docs/8.3.1/Core.html#isEmptyRow (it returns `true` if the row is empty).

If that is not what you wanted to do. Please send me an email with the requirements.
