### ISSUE TITLE
Property 'root' does not exist on type... (root="hot")

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7609]
@yzaroui commented on [Thu Mar 04 2021](https://github.com/handsontable/docs/issues/303)

Hello,

The prop `root` used in this example does not exist in the HotTable props definition.

https://github.com/handsontable/docs/blob/a144fa04f22d1e0da7b75917c2403a5334b09545/tutorials/wrapper-for-react-simple-examples.html#L172

**Comment by AMBudnik** [comment]
Thank you for sharing the issue @yzaroui 
I've moved the issue to this repository as we're merging them.

I confirm that root is missing from the wrapper's definitions.

**Comment by wojciechczerniak** [comment]
`root` was renamed to `id` long time ago. Documentation issue

**Comment by kirszenbaum** [comment]
Fixed here:

https://github.com/handsontable/handsontable/pull/9724/files#diff-808fc60c61cbec5c4f195c8882722372881fd1ffeaa1f28a279efc27e45c31d8R146
