### ISSUE TITLE
HotColumn does not have a settings prop

### ISSUE THREAD

**Issue by yzaroui** [handsontable/handsontable#7610]
### Description
settings attribute is missing from the wrapper's HotColumn definitions.

### Demo
https://github.com/handsontable/docs/blob/a144fa04f22d1e0da7b75917c2403a5334b09545/tutorials/wrapper-for-react-hot-column.html#L24

**Comment by AMBudnik** [comment]
Thank you for sharing.

**Comment by krzysztofspilka** [comment]
@yzaroui We'd need more information about it. Could you please share the potential code output after this change? How exactly would such configuration look like then?

**Comment by warpech** [comment]
`settings` prop definitely works, as presented in the first example on the docs page: https://handsontable.com/docs/react-hot-column/#overview

However, it seems that:
- the `settings` prop is not present in the type definitions of `HotColumn`
- there is no test for the `settings` prop of `HotColumn`

**Comment by AMBudnik** [comment]
Hi @yzaroui 

Thank you again for your report.

We just fixed the issue with the following PR https://github.com/handsontable/handsontable/pull/10661. Changes are published in Handsontable v14.1.0

Here https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-1-0 is a full list of changes for v14.1.0
