### ISSUE TITLE
Column move action is causing issues when we hide columns or want to move column far away

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7613]
### Description

The column move action is causing issues. We experience the same effect (columns are jumping right-left and we cannot scroll them) with or without `hiddenColumns`. The difference is the `hiddenColumns` are causing the issues faster (within the same viewport). And we need to scroll non-hidden columns very far to get the same effect (around `CA` column with 1000 columns in total).

I've labeled the issue with hiding as it is more inconvenient with `hiddenColumns`.

### Steps to reproduce

1. Grab column 'C' and try to move it as far to right as you can

**Result**
You are not able to scroll further than `Q` column.
![hidden_columns](https://user-images.githubusercontent.com/10757813/110327120-dae65d00-8019-11eb-90d1-00eee47f04ec.gif)

### Demo

https://jsfiddle.net/ywepLuo6/ 8.3.1 - broken
https://jsfiddle.net/ywepLuo6/2/ 7.0.0 - broken
https://jsfiddle.net/ywepLuo6/3/ 6.0.0 (I was able to scroll a bit further to the AA column) - broken

### Your environment
* Handsontable version: 8.3.1
_It doesn't seem to be a regression_
* Browser Name and version: Chrome 87
* Operating System: Windows 10

Inform [forum](https://forum.handsontable.com/t/scrolling-issue-when-moving-columns-and-having-hidden-columns/5054/5), [Zen Arch 26503](https://handsontable.zendesk.com/agent/tickets/26503)

**Comment by linusArkit** [comment]
Also having this issue for one of our projects for a client.   Hopefully this issue will get fixed soon.  Does anyone know of any current workarounds?

**Comment by AMBudnik** [comment]
Hi @linusArkit the only approach that I have found while creating this issue report is to hold the column with the LMB and use the arrow right <kbd>></kbd> to move selection (as it scrolls the viewport) and then release the LMB on any desired position.

**Comment by Enakhimion** [comment]
Hi, still no solutions?

**Comment by AMBudnik** [comment]
Hi @Enakhimion we do not have any updates on this subject. But I will make sure to notify you about the fix.

**Comment by aninde** [comment]
This issue will be fixed by v12.1.0 https://jsfiddle.net/1jgaq9dn/

**Comment by AMBudnik** [comment]
Thank you for fixing this issue. I've notified Clients who waited for the fix.

I'm closing this issue as fixed in v12.1.0
