### ISSUE TITLE
** Remove Empty Roll with cell value in react 

### ISSUE THREAD

**Issue by pablomagalhaes** [handsontable/handsontable#7629]
### Description
I can't remove automatic empty roll in react.js. How do this. can you show me example. Please

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @pablomagalhaes do you mean an empty row (without data in any cell)?
If so when do you plan to remove it (on data load, on data safe, on a button click)?

ps. as this idea might be related to the way you construct the dataset please share your configuration to support@handsontable.com

**Comment by pablomagalhaes** [comment]
> on data load,

Hi Alleksandra > on data load. ( No carregamento da tabela).

If you like you can use this example ( https://jsfiddle.net/pablot/hz0mt65e/#&togetherjs=RJJyLyBk0R)

**Comment by pablomagalhaes** [comment]
Hi @AMBudnik - you know my question.
in load data i would like to remove cell in row

**Comment by AMBudnik** [comment]
Sorry for the delay, @pablomagalhaes but it is hard for me to imagine how the table should look after removing a single cell from the table. Does data swift?

Can you share any draft or screenshots of the desired result?

**Comment by pablomagalhaes** [comment]
Hi @AMBudnik - I need to remove the only empty cells in table this is my example:
https://jsfiddle.net/pablot/hz0mt65e/#&togetherjs=RJJyLyBk0R

**Comment by AMBudnik** [comment]
Great. Thank you for sharing the example. It helped me a lot to understand the use case.

I would use those two methods

* https://handsontable.com/docs/8.3.2/Core.html#isEmptyCol
* https://handsontable.com/docs/8.3.2/Core.html#isEmptyRow 

To get row and column index that is empty. Once you have those indexes (for example stored in an array) you may call the alter method (separately for each row and column) to remove them from the dataset. 
Also, I recommend using [batch](https://handsontable.com/docs/8.3.2/Core.html#batch)() method to keep all those changes within one render as the alter method calls the render itself.

**Comment by AMBudnik** [comment]
I hope that my tips helped. As there is no further feedback I'm going to close the ticket. However, feel free to send me an email if you still need some guidance, @pablomagalhaes
