### ISSUE TITLE
getcell() method  Not working (return null)

### ISSUE THREAD

**Issue by xiaowangsmile** [handsontable/handsontable#7630]
After the table is initialized, I want to get the cell property through the method, but the return is null,

The above problems only occur when the number of rows and columns in the table is greater than 15.

https://jsfiddle.net/hv8xs1to/

* Handsontable version:  8.x
* Browser Name and version: chrome88
* Operating System: win7

![image](https://user-images.githubusercontent.com/28744261/111114161-d08a0d00-859d-11eb-8c37-6206afedf153.png)

**Comment by jekorx** [comment]
The same problem, has it been solved?

**Comment by jekorx** [comment]
+1

**Comment by xiaowangsmile** [comment]
> After the table is initialized, I want to get the cell property through the method, but the return is null,
> 
> The above problems only occur when the number of rows and columns in the table is greater than 15.
> 
> https://jsfiddle.net/hv8xs1to/
> 
> * Handsontable version:  8.x
> * Browser Name and version: chrome88
> * Operating System: win7
> 
> ![image](https://user-images.githubusercontent.com/28744261/111114161-d08a0d00-859d-11eb-8c37-6206afedf153.png)
