### ISSUE TITLE
Import definitions from Numbro

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7632]
### Description

As defined in this PR https://github.com/handsontable/handsontable/pull/7631 we need to provide additional definitions for numeric cell type.

The final idea was to import those definitions from Numbro.

### Your environment
* Handsontable version: 8.3.2
* Browser Name and version: Chrome 89
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
Duplicate of #7420

**Comment by AMBudnik** [comment]
Ah, it's already there! Thank you @wojciechczerniak I'm closing this issue.
