### ISSUE TITLE
** On Data Load Remove Empty Roll with cell  value in react 

### ISSUE THREAD

**Issue by pablomagalhaes** [handsontable/handsontable#7634]
### Description

On data load. ( No carregamento da tabela).
If you like you can use this example ( https://jsfiddle.net/pablot/hz0mt65e/#&togetherjs=RJJyLyBk0R).
When table load data remove the empty cells in row.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi Pablo, I think that we can keep that conversation here https://github.com/handsontable/handsontable/issues/7629 as the other topic does not share any different point of view or a question. Please answer my questions at https://github.com/handsontable/handsontable/issues/7629 or send me an email with the draft.

Thank you.
