### ISSUE TITLE
afterInit callback no longer returns instance in angular

### ISSUE THREAD

**Issue by zangell44** [handsontable/handsontable#7636]
### Description
In version 3.x.x, we were using an `afterInit` callback with our table to make adjustments. In version 8.x.x, this is no longer working. Is there a different way I should be doing this in the upgraded version?

### Steps to reproduce
1. Set up html and corresponding callback as follows.

html
```
<hot-table id="hotTable" [afterInit]="afterTableInit" [colHeaders]="true" [rowHeaders]="true"
[data]="pageData" [settings]="{renderer: renderCell, contextMenu: contextMenu}"
[licenseKey]="00000-00000-00000-00000-00000"
></hot-table>
```

callback in Angular component
```
afterTableInit = (instance) => {
    console.log('after table init called') // it is called
    console.log('instance', instance) // instance is undefined
  // do some stuff to the table here
  }
```

### Your environment
* Handsontable version: 8.3.1
* Browser Name and version: Chrome latest
* Operating System: macOS

**Comment by wojciechczerniak** [comment]
`instance` argument was removed in `v5.0.0` https://github.com/handsontable/angular-handsontable/releases/tag/5.0.0. Handsontable instance is available as `this` context if you don't overwrite it by using arrow functions.

**Comment by swistach** [comment]
There is also a way to use arrow functions. You have to use `HotTableRegisterer`: https://handsontable.com/docs/8.3.2/frameworks-wrapper-for-angular-hot-reference.html, which stores a reference to the Handsontable instance.

Here you can find a demo: https://codesandbox.io/s/sad-microservice-epm8n?file=/src/app/app.component.ts

I close this issue for now but feel free to continue the conversation if the suggested example does not solve your problem.
