### ISSUE TITLE
CONTRIBUTING.md 'How we use Git-Flow' anchor redirects to Main wiki

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7646]
### Description
_CONTRIBUTING.md_ 'How we use Git-Flow' anchor redirects to Main wiki (for Client, for member to a 'create new page').

### Referencse
* https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md 

### Your environment
* Handsontable version: 8.3.2
* Browser Name and version: n/a
* Operating System: n/a

**Comment by warpech** [comment]
Closing as this was addressed in https://github.com/handsontable/handsontable/commit/af89cbfdab044dd05dd6e6fbb1434b523a88b274 by removing the link.
