### ISSUE TITLE
Typing in a Date cell doesn't clear it out like other cells

### ISSUE THREAD

**Issue by henderjr** [handsontable/handsontable#766]
Hello.  I'm investigating how to make some data entry quicker for my company.  It was decided to create an excel type form where a user could tab through and create rows of data quickly.  Handsontable works great for that but I must be missing something.  

How do you type in a date without it trying to default in today's date and then adding what you type to the end of the date?  Also if there is a data in there and you start typing shouldn't it overwrite what was there like any other cell type?

![image](https://f.cloud.github.com/assets/4643398/625954/2d4182ea-cfb1-11e2-9345-00d430d67a30.png)

Sorry if this is already answered somewhere.  

Thanks for any help!
-Jesse

**Comment by AMBudnik** [comment]
Actually we're using different date-picker for a `date` type, please check this [demo](http://handsontable.com/demo/date.html) it's erasing previous value with a new one after clicking to edit.
