### ISSUE TITLE
Typescript type definitions for props of hot-renderer React component

### ISSUE THREAD

**Issue by mealplana** [handsontable/handsontable#7660]
### Description

I need to render a custom component `MyComponent` in React as a renderer for a column. Following the guidance in [here](https://handsontable.com/docs/8.3.2/frameworks-wrapper-for-react-hot-column.html#object-data-source), I managed to get it to work by using the `hot-renderer` attribute in my component as shown below:

```
<HotColumn data={data}>
  <MyComponent hot-renderer />
</HotColumn>
```

Now the issue is that when I declare `MyComponent`, I don't have type definitions for the props in Typescript.

```
import { FC } from 'react';

type Props = {
  'hot-renderer': boolean;
  // cannot declare the different key/value pairs contained in "props" here as they are not passed explicitly.
};

export const MyComponent: FC<Props> = props => {
  console.log(props); // There are many values passed here, such as value, row, cell, instance data and more.
  const value = props.value; // This will be highlighted as an error by Typescript since "value" was not declared as a property of "props", even though this property and others exist.
  return (<>hello</>);
};

```

How can we declare props in MyComponent and provide them explicitly without having to rely to ts-ignore comments to disable Typescript type-checking?

### Steps to reproduce

1. Create a sample `MyComponent.tsx` file with a `MyComponent` React component as listed above. The project must have Typescript/React
2. Try to compile the Typescript code. An error will be thrown

### Demo
Sorry, didn't manage to create a demo, if it is required please let me know and will try again.

### Your environment
Package Versions:
* "handsontable": "^8.3.2"
*  "react": "^17.0.1"
*  "typescript": "^4.2.2"
*  "@handsontable/react": "^4.0.0"

* Browser Name and version: Google Chrome, or any other browser
* Operating System: windows 10

**Comment by mealplana** [comment]
Thanks! The workaround in the sandbox looks good, will try that. I actually found another way to design the code that doesn't need the `hot-renderer` property, but if I use it in the future I will try your suggestion and check whether a future version of the package exports the required types.

**Comment by AMBudnik** [comment]
Thank you again for sharing this issue report.

We discussed it with the team, and apparently, that is the correct behavior. The error from the typescript is perfectly valid as we are trying to access a value that is not defined.

If we, however, missed anything please let us know at support@handsontable.com
