### ISSUE TITLE
Is it possible to mask cell values?

### ISSUE THREAD

**Issue by akoskm** [handsontable/handsontable#7662]
I have a combination of two tables:
1. **Main** table
2. **Source** table

**Main** table has a `text` and a `handsontable` type column
![image](https://user-images.githubusercontent.com/3111627/103130462-1620f300-469d-11eb-8c9f-b413ac3d7ec2.png)

where the possible values for the `handsontable` column are coming from the **Source** table:

![image](https://user-images.githubusercontent.com/3111627/103130554-6ef08b80-469d-11eb-8939-afd310f7b450.png)

The problem with this is that when I update the values in the Source table they are not reflected in the Main table (see the first row in the Main table, it still has 0 even after I updated the Source table).

This happens because right now I'm setting the value for the Main table by making a copy of the selected row values from the Source table:

```
function getValue(this: Handsontable) {
  const selection = this.getSelectedLast();
  if (!selection) return '';

  // Get always first column (Name) of clicked row and ignore header
  // coordinates (negative values)
  const backstageRow = this.getSourceDataAtRow(
    Math.max(selection[0], 0)
  ) as number[];
  // ignore first column, copy values only
  return backstageRow.slice(1);
}

// columns definitions for Main table
{ type: 'text' },
{
  type: 'handsontable',
  handsontable: {
    colHeaders: headerLevelMappings['block.source.generic.octave_band.lp'],
    data: tableState['block.source.generic.octave_band.lp'].levels,
    getValue,
    colWidths: [120],
  },
},
```

What I'm thinking about is setting the Row Name (first column in Source table) as the value for the second column in the Main table, so I would have this as data:

<table>
<tr>
	<td>
	<td>Notes
	<td>Source
<tr>
	<td>1
	<td>test
	<td>test1
<tr>
	<td>2
	<td>yikes
	<td>test2
</table>

but on rendering I would dynamically retrieve the data from the Source table so it would display as:

<table>
<tr>
	<td>
	<td>Notes
	<td>Source
<tr>
	<td>1
	<td>test
	<td>1,2,34,4,5,6,7,4
<tr>
	<td>2
	<td>yikes
	<td>8,7,63,4,3,2,1,3
</table>

By looking at the example with book covers in [Custom Rendered](https://handsontable.com/docs/8.3.2/demo-custom-renderers.html) I thought that is pretty much made for this use-case (cell values is a URL but an image is displayed).

Unfortunately in case of a handsontable column it doesn't affect the final cell but the cells inside the handonstable:

```
handsontable: {
  colHeaders: headerLevelMappings['block.source.generic.octave_band.lp'],
  data: tableState['block.source.generic.octave_band.lp'].levels,
  getValue,
  colWidths: [120],
  cells(row, col) {
    const cellProperties = {};
    const data = this.instance.getData();

    if (col === 1) {
      cellProperties.renderer = levelsRenderer; // uses function directly
    }

    return cellProperties;
  },
},
```

![image](https://user-images.githubusercontent.com/3111627/112748291-180b9280-8fbb-11eb-8b14-3993f8735bc0.png)

**Comment by AMBudnik** [comment]
Hi @akoskm 

let me know if something like this would meet your goal https://jsfiddle.net/handsoncode/53hkz6L7/
Once I update the source of the handsontable cell type I still need to use the setDataAtCell for the main table to update.

**Comment by akoskm** [comment]
Thanks, @AMBudnik I tweaked your example a little bit and I recreated exactly the situation I'm in:

https://jsfiddle.net/ctd067wz/15/

To reproduce my problem do the following:

1. In the Main table, B1, select **test1** from the Source table
2. Go to the source table and modify some of the values for **test1**

I want these modifications to reflect in the Main table.
Now in order to have these modified values in the Main table, I have to click **B1** again and re-select the modified row from the source table.

My conclusion:
because of how I'm taking values from the source table:

```
// ignore first column, copy values only
return backstageRow.slice(1);
```

this creates a new array, it makes sense that right now these changes are not reflected in the Main table.

This is why I thought this would be a good idea:

> What I'm thinking about is setting the Row Name (first column in Source table) as the value for the second column in the Main table, so I would have this as data:
> ... 
> but on rendering I would dynamically retrieve the data from the Source table

**Comment by AMBudnik** [comment]
I might have not covered all the scenarios but maybe this will help https://jsfiddle.net/handsoncode/2rohm7qy/

**Comment by akoskm** [comment]
@AMBudnik I'm missing something but this works identical to my example.

I created a short screen recording:


https://user-images.githubusercontent.com/3111627/113282852-cc712580-92e7-11eb-9f2d-968eca93cfe0.mov

Updating the Source table values doesn't propagate to the Main table.

**Comment by AMBudnik** [comment]
Sorry, forgot one thing - https://jsfiddle.net/handsoncode/jct60qb4/ not it should work as expected.

**Comment by akoskm** [comment]
@AMBudnik thanks, this is exactly what I needed! I'll take a look later to figure out how this works.

One thing I noticed, once I select the values for the Main table and update some of the values in the Source table, I can't change the Main table values anymore.

**Comment by akoskm** [comment]
I figured out why. There is no mapping between the two tables, the main table's first row is updated when the first row of the source table changes:

```
  // source table:
  afterChange: function(changes, src) {
    if (changes && src !== "attach") {
      newValue = this.getDataAtRow(changes[0][0]);
      newValue.shift(); // B - H columns data
	  // changes[0][0] - returns 0 or 1
      hot.setDataAtCell(changes[0][0], 1, newValue, 'attach');
    }
```

<details>
<summary>Screen recording</summary>

https://user-images.githubusercontent.com/3111627/113468845-1e7d8c80-9449-11eb-8ec6-93b08971ecd1.mov

</details>

If the mapping I described in my first post could exist I should be able to dynamically update the rows

```
  afterChange: function(changes, src) {
    if (changes && src !== "attach") {
      newValue = this.getDataAtRow(changes[0][0]);
      const rowName = newValue.shift(); // B - H columns data

      // rowIndex is the index of the row from the mainTable that needs to be updated
      const rowIndex = hot.getData().findIndex(([a, b]) => b === rowName);
      hot.setDataAtCell(changes[0][0], 1, newValue, 'attach');
    }
```

Unfortunately, the only way I could see this work now is to keep a copy of the Main table that has the column names in the second column instead of the original values.

I'm surprised that I can't just use the custom renderer to have keys in Main table from Source table, 

<table>
<tr>
	<td>
	<td>Notes
	<td>Source
<tr>
	<td>1
	<td>test
	<td>test1
<tr>
	<td>2
	<td>yikes
	<td>test2
</table>

then just render the correct arrays instead of displaying the keys:

<table>
<tr>
	<td>
	<td>Notes
	<td>Source
<tr>
	<td>1
	<td>test
	<td>1,2,34,4,5,6,7,4
<tr>
	<td>2
	<td>yikes
	<td>8,7,63,4,3,2,1,3
</table>

Can't I write a custom column renderer (just as you have type: handsontable) that extends the `handsontable` renderer, but it would read from the source table when it displays its value?

**Comment by akoskm** [comment]
I ended up solving this with a custom renderer. I made a mistake:

> By looking at the example with book covers in Custom Rendered I thought that is pretty much made for this use-case (cell values is a URL but an image is displayed).
>
> Unfortunately in case of a handsontable column it doesn't affect the final cell but the cells inside the handonstable:

This was happening, because I put the renderer inside the handsontable definition, like this:

```
// columns definitions for Main table
{ type: 'text' },
{
  type: 'handsontable',
  handsontable: {
    colHeaders: headerLevelMappings['block.source.generic.octave_band.lp'],
    data: tableState['block.source.generic.octave_band.lp'].levels,
    getValue,
    colWidths: [120],
    renderer: myCustomRenderer // affects handsontable cell rendering
  },
},
```

but it should've been:

```
// columns definitions for Main table
{ type: 'text' },
{
  type: 'handsontable',
  handsontable: {
    colHeaders: headerLevelMappings['block.source.generic.octave_band.lp'],
    data: tableState['block.source.generic.octave_band.lp'].levels,
    getValue,
    colWidths: [120],
  },
  renderer: myCustomRenderer // affects outer table rendering
},
```

Thanks, @AMBudnik for your help!

**Comment by AMBudnik** [comment]
That's a quick update, @akoskm ! Thank you for keeping me in the loop.

I'm glad you solved the case.
