### ISSUE TITLE
Add definitions for suspendRender, resumeRender, resumeRender and resumeExecution

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7666]
### Description

Add definitions for `suspendRender`, `resumeRender` , `resumeExecution` and `resumeRender`. 
The batch method is added but it is not alphabetically correct so we can also move it.
+ check other related methods added with batching.

### References
1. Definition file - https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts
2. suspendRender - https://handsontable.com/docs/8.3.2/Core.html#suspendRender 
3. resumeRender - https://handsontable.com/docs/8.3.2/Core.html#resumeRender
4. resumeExecution - https://handsontable.com/docs/8.3.2/Core.html#resumeExecution
5. suspendExecution - https://handsontable.com/docs/8.3.2/Core.html#suspendExecution

### Your environment
* Handsontable version: 8.3.2
* Browser Name and version: Chrome 89
* Operating System: Windows 10

inform [Zen](https://handsontable.zendesk.com/agent/tickets/26283)

**Comment by aninde** [comment]
Done in the v8.4.0.

**Comment by AMBudnik** [comment]
Thank you for fixing @budnix 

I close this issue as solved in [v8.4.0](https://github.com/handsontable/handsontable/issues/7998).
