### ISSUE TITLE
Out of bounds cell references

### ISSUE THREAD

**Issue by nikersify** [handsontable/handsontable#7668]
By default, HyperFormula returns `null` instead of `#REF!` when referencing cells that are out of bounds of the current sheet. `#REF!`'s are returned only when referencing sheets that don't exist.

The current formulas plugin returned `#REF!`'s in such cases.

```typescript
import {HyperFormula} from 'hyperformula'

const hf = HyperFormula.buildFromArray([['=Z9']], {licenseKey: 'non-commercial-and-evaluation'})

console.log(hf.getSheetDimensions(0)) // { width: 26, height: 9 }
console.log(hf.getCellValue({sheet: 0, row: 0, col: 0})) // null
```

Moreover, it seems like the whole sheet gets internally resized (`HyperFormula#getSheetDimensions`), but that's probably irrelevant.

---

This issue should cover making the decision about how the plugin should behave.

**Comment by krzysztofspilka** [comment]
@nikersify Already discussed internally on Slack ([slack thread](https://handsoncode.slack.com/archives/CP3FX2DBM/p1617357014002100)).

I'm closing this issue as the discussion's result is inconclusive. There is an obvious discrepancy between our implementation and the specification (#REF! Reference to invalid cell (e.g., beyond the application’s abilities). ERROR.TYPE of 4.") but it's something we believe is an acceptable deviation at this point.
