### ISSUE TITLE
Get ColumnIndex number on onChange() instead of column.data: name string

### ISSUE THREAD

**Issue by Itsmesri** [handsontable/handsontable#767]
How can get column index number on onChange() instead of column.data: name string?

![image](https://f.cloud.github.com/assets/3935541/627179/06a05342-d005-11e2-9346-17f42a0c319b.png)

**Comment by AMBudnik** [comment]
Currently we use [afterChange()](https://github.com/handsontable/handsontable/wiki/Events) instead of onChange() which is deprecated
