### ISSUE TITLE
Unique IDs for Column Headers

### ISSUE THREAD

**Issue by eribean** [handsontable/handsontable#7673]
### Description

I'm trying to associate a unique ID with a column so I can access a separate array of Metadata. I cannot use the name since inserting columns results in duplicate names, and redo/undo can result in name clashing. I've looked into Index mappers but the physical / visual indices do not change with the above operations.
 

An ideal solution would have the column headers referenced by an unchanging unique id/hash. I'm open to programmatic solutions but have yet to come up with one that doesn't require setting it on every cell and slowing down rendering.

### Steps to reproduce

1.
2.
3.

### Your environment
* Handsontable version: 8.3
* Browser Name and version: Chrome / Firefox / Edge
* Operating System: Linux

**Comment by eribean** [comment]
@wojciechczerniak If I have a spreadsheet and let users insert columns on the left and right, the column index mapper ```hot.columnIndexMapper.getPhysicalFromVisualIndex(ndx)``` always returns the same input index. I tried all the available mappers in the ```columnIndexMapper``` and none of them seem to change on manipulation.

If you have a way to do this that would be great, the best solution I've come up with is to add a hidden HTML element to the column name ```<span style='display: none;'>Unique ID</span>``` but this was too complex and I eventually abandoned it. Any help would be great, I have a developer license if that is any incentive.

**Comment by eribean** [comment]
Reading the comments of #7276, it appears this might be something for me to research. I'm a little confused on how to use it though, the [documentation](https://handsontable.com/docs/8.3.2/IndexMapper.html) is a bit opaque for me. Does this allow unique id mappings for column headers?

**Comment by wojciechczerniak** [comment]
True, documentation and examples could be better.

You have to create your own Map. For your use case, a `PhysicalIndexToValueMap` can be used to store any value associated with physical index. Add it to the IndexMapper and it will handle the any CRUD operations that will shift or remove indexes.

----

First, you have to create your map instance that will store your ID:
```ts
    const idMap = new PhysicalIndexToValueMap(() => {
       return null; // or some fancy unique ID generator, this callback should return the default value for new columns
    });
```

Then register it to the `columnIndexMapper` so it will be updated with CRUD actions:
```ts
    hotInstance.columnIndexMapper.registerMap(`columnID`, idMap);
```

Now we have two basic methods: `getValueAtIndex` and `setValueAtIndex`.

```ts
  const physicalIndex = 2; // map it from visual if needed
  idMap.setValueAtIndex(physicalIndex, 'guid-212-332'); 

  hot.alter('insert_col', 1, 1);

  // map values are now shifted:
  idMap.getValueAtIndex(2); // null
  idMap.getValueAtIndex(3); // 'guid-212-332'
```

https://codesandbox.io/s/gracious-cherry-qoee5

---

Keep in mind that `loadData` currently clears the IndexMappers: #7263
If you need to preserve the IDs (ie. youre sure the order did not change) then:

```ts
const cacheIDs = idMap.getValues();

hotInstance.loadData(updatedData)

idMap.setValues(cachedIDs);
```

or you may send the IDs with data, then the order doesn't matter:

```ts
const responseColumns = response.body.columns;
const responseData = response.body.data;

const columnIDs = responseColumns.map(column => column.id);

hotInstance.loadData(responseData)
idMap.setValues(columnIDs);
```

**Comment by eribean** [comment]
@wojciechczerniak I appreciate this, I'll give this a try!

**Comment by eribean** [comment]
@wojciechczerniak I'm using the bundle from 
``` /npm/handsontable@8.3.2/dist/handsontable.full.min.js```

and I'm not sure how to  add this, from your sandbox example you import this 
```js
import PhysicalIndexToValueMap from 'handsontable/translations/maps/physicalIndexToValueMap';
```
I know you're busy and I appreciate the help.

**Comment by eribean** [comment]
Thanks for responding, I'll keep a lookout for any updates
