### ISSUE TITLE
Suggestion: Add a "toggleRow" and "toggleColumn" to hiddenRows/hiddenColumns plugins

### ISSUE THREAD

**Issue by apolinario** [handsontable/handsontable#7678]
In the "hiddenRows" and "hiddenColumns" plugins we have the hideRow/showRow and hideColumn/showColumn method.

I suggest the creation of a toggleRow / toggleColumn method to show/hide according to the previous state

**Comment by wojciechczerniak** [comment]
Thanks for the idea @apolinario but can you elaborate, is there something you cannot do that requires a change in the core functionality?

IMO plugin has everything you need to run this op. Something like:

```ts
const hiddenColumnsPlugin = hotInstance.getPlugin('hiddenColumns');

function toggleHiddenColumn(column) {
   if (hiddenColumnsPlugin.isHidden(column)) {
    hiddenColumnsPlugin.showColumn(column);
  } else {
    hiddenColumnsPlugin.hideColumn(column);
  }
}
```

If you want support for more columns
```ts
const hiddenColumnsPlugin = hotInstance.getPlugin('hiddenColumns');

function toggleHiddenColumns(columns) {
  const columnsToHide = columns.filter(column => !hiddenColumnsPlugin.isHidden(column));
  const columnsToShow = columns.filter(column => hiddenColumnsPlugin.isHidden(column));

  hotInstance.batch(() => {
    hiddenColumnsPlugin.hideColumns(columnsToHide);
    hiddenColumnsPlugin.showColumns(columnsToShow);
  });
}
```

**Comment by AMBudnik** [comment]
I think that we can close the issue as there are no additional questions or suggestions.
