### ISSUE TITLE
Is it possible to hidden specific row (Not column)?

### ISSUE THREAD

**Issue by xinfli** [handsontable/handsontable#768]
I need hide some row in Handsontable grid, for some special reason, I could not do it in data level, so is it possible do it in renderer or events?

Thanks.

**Comment by IgorVM** [comment]
Hi xinfli!
I faced with the same problem to hide row header cell. I tried to use your code, but it doesn't help. I think that it fires too soon. I call this code on event afterRender, maybe this is wrong place to call it? You said that you call it after grid was rendered, on which event you did it?
Thank you

**Comment by nopium** [comment]
Mark in your data what to hide, then in your cell renderer function:
```
if (data[row] && data[row]['hidden'] === true && td.parentNode && row < data.length-1) {
  td.parentNode.style.display = 'none';
}
else if ( td.parentNode) {
    td.parentNode.style.display = '';
}
```
