### ISSUE TITLE
Add information to the docs that correctFormat also applies to time cell type

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7682]
### Description
Add information to the docs that `correctFormat` also applies to time cell type.

### Links
1. correctFormat - https://handsontable.com/docs/8.3.2/Options.html#correctFormat
2. time demo where we use correctFormat https://handsontable.com/docs/8.3.2/demo-time.html

### Your environment
* Handsontable version: 8.3.2
* Browser Name and version: n/a
* Operating System: n/a

**Comment by kirszenbaum** [comment]
Done in: #9705.

I also raised a question of the `timeFormat` option missing from the [Options](https://handsontable.com/docs/api/options) page: https://handsoncode.slack.com/archives/C4PV4S33Q/p1659018528980889
