### ISSUE TITLE
When we sort a column with a merge area while calling empty object within `updateSettings` in the `afterOnCellMouseUp` hook data is removed from the cells.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7688]
### Description

When we sort a column with a merge area while calling empty object within `updateSettings` in the `afterOnCellMouseUp` hook data is removed from the cells.

### Steps to reproduce

1. Click `B` header a couple of time to sort the column

**Result**
Data is being removed.
![sort (1)](https://user-images.githubusercontent.com/10757813/113993455-c7b2f100-9854-11eb-977a-b00aea34472e.gif)

### Demo

https://jsfiddle.net/handsoncode/gxz45kab/ - 8.3.2 - broken
https://jsfiddle.net/handsoncode/zp726jxL/ - 7.0.0 - broken

### Your environment
* Handsontable version: 8.3.2
* Browser Name and version: Chrome 89
* Operating System: Windows 10

**Comment by aninde** [comment]
This issue will be fixed by v12 https://jsfiddle.net/9tk5L31y/

**Comment by AMBudnik** [comment]
Thank you for fixing it!

For everyone who is tracking changes to this topic please check our release notes https://handsontable.com/docs/release-notes/#_12-0-0 and the migration guide https://handsontable.com/docs/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls
