### ISSUE TITLE
[8.2.0] The column header layer is cut if columns are used within the `updateSettings`

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7689]
### Description

The column header layer is cut if columns are used within the `updateSettings`.

### Steps to reproduce

1. Load the demo to see that the header is cut.

![image](https://user-images.githubusercontent.com/10757813/114388783-77a99680-9b94-11eb-9960-cab327b28f77.png)

### Additional observations
* works the same for object data (with 'data' defined in columns) and array https://jsfiddle.net/handsoncode/71wdcmsr/
* edition repaints the headers and they appear properly
* adding more columns always cuts the last header progressively https://jsfiddle.net/handsoncode/c13z7bmy/
![image](https://user-images.githubusercontent.com/10757813/114389608-7b89e880-9b95-11eb-9212-a660e7fa1f73.png)

### Demo

https://jsfiddle.net/handsoncode/1Luk25nd/ - 8.2.0 - broken
https://jsfiddle.net/handsoncode/gtuxv9Lc/ - 8.1.0 - looks well

### Your environment
* Handsontable version: 8.2.0+
* Browser Name and version: Chrome 89
* Operating System: Windows 10

**Comment by aninde** [comment]
This issue is fixed by v9.0.2
Demo: https://jsfiddle.net/18stzypk/ https://jsfiddle.net/sgc0wq1n/

**Comment by swistach** [comment]
I'm happy to announce we just released v9.0.2 with the fix to this bug.
