### ISSUE TITLE
Add `allowEmpty` option to autocomplete

### ISSUE THREAD

**Issue by rahzelh** [handsontable/handsontable#769]
Is it possible in strict mode to not have to select any option after expand a list from autocomplete cell type? I need to use strict mode for autocomplete cells but with possibility to delete the value or at least to not have to use anyone from the list after expand it.

**Comment by sxchan** [comment]
excuse me, May I know whatever version have applied the patch of this issue?

**Comment by AMBudnik** [comment]
It wasn't added yet @sxchan 
I think taht we can change the issue to `feature request`

**Comment by AMBudnik** [comment]
We're moving this topic to our [Feature-requests section](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by AMBudnik** [comment]
Eventually reported at https://github.com/handsontable/handsontable/issues/7929 as a bug as in the meanwhile we also added this ability to a dropdown cell type.
