### ISSUE TITLE
formular not support draggable

### ISSUE THREAD

**Issue by shaw1111** [handsontable/handsontable#7729]
### Description

the elder version support draggble, for now it has been dropped

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @shaw1111 

Please provide a bug scenario and a demo. What do you plan to drag?

**Comment by AMBudnik** [comment]
I will keep this issue closed until we get any further details to replicate the bug.

**Comment by shaw1111** [comment]
when user drag down the cell  B1 which has fomular like as A1+1  ,the B2 cell should be filled with A2+1 like in the excel

**Comment by shaw1111** [comment]
> I will keep this issue closed until we get any further details to replicate the bug.

when user drag down the cell B1 which has fomular like as A1+1 ,the B2 cell should be filled with A2+1 like in the excel

**Comment by AMBudnik** [comment]
Thank you for sharing additional details @shaw1111 

This functionality is not available within the current Handsontable Formula plugin.
It might be added in the next iteration of the new formula plugin defined by this issue https://github.com/handsontable/handsontable/issues/6466

**Comment by wojciechczerniak** [comment]
Already in progress #7693 😄

**Comment by AMBudnik** [comment]
That's great news @wojciechczerniak!
