### ISSUE TITLE
afterChange per cell

### ISSUE THREAD

**Issue by tuimz** [handsontable/handsontable#773]
Is it possible to have an afterChange event per cell?

e.g:

    columns: [{type: 'autocomplete', readOnly: true, afterChange: function(){}}]

The reason I am asking is because I have some autocomplete values which are depending on values defined earlier in the same row, for example [0][2] depends on the value of [0][1]  for the autocomplete source.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
