### ISSUE TITLE
Clicking "remove row" from left row-header does not work.

### ISSUE THREAD

**Issue by rail24** [handsontable/handsontable#778]
I've noticed when trying to use the "remove row" functionality that right-clicking on a row's "header" doesn't work properly. However, it does work if I select a cell and then right-click on the header.

This doesn't seem right to me. If I right-click the first row's header and click "remove row", the first row should be removed. If that's not possible, then the right-click functionality should probably not pop up when right-clicking that row.

It also doesn't seem right that if I select row 5, cell 1, and then right-click the header for row 2 and click "remove row", it removes the row 5 because it was selected.

Right-clicking the row header should remove the highlighted cell, and then clicking "remove row" should remove that specific row.

I'm assuming this is based on the way that handsontable determines which row to delete (ie: remove rows that are selected), which makes sense when removing many rows, or right-clicking a specific cell in that row. It just doesn't translate to when right-clicking a row header. If the most basic way of fixing this issue is to remove right-click functionality from row-headers, then perhaps that is the most effective way to prevent user confusion on this issue.

**Comment by AMBudnik** [comment]
Please update to 0.14.1 on newer. Here's the [working demo](https://jsfiddle.net/AMBudnik/xgb49sx4/)
