### ISSUE TITLE
 this.setValue(value, callback)； if the value is an Object and has the keys different with zhe originalValue, when call the this.editfinishing, zhe object value would not setted.

### ISSUE THREAD

**Issue by yutian0414** [handsontable/handsontable#7802]
### Description

// editor
class StrategyEditEditor extends BaseEditorComponent {

   super(props){...}
   setValue(value,callback){
   this.setState((state,props)=>{return {value:value}}, callback)
}
statusChange = (value)=>{
          this.saveValue([[{value, _cellType: "status", 'a':'1'}]],  this.finishEditing);
}
}

// render
const CellRender = (props) => {return <>{value?.value ? 'success':'failed'}</>}

originalValue is {value:true, _cellType: "status"}

when i add a new key 'a' in the object value,  the editor while not set zhe value.
in this case, i want to add new attribute for render and update the source data for further useage

### Your environment
* React wrapper version: 5.0.0
* Handsontable version:8.3.2
* Browser Name and version:chrome new
* Operating System:window

**Comment by AMBudnik** [comment]
Hi @yutian0414 

Please provide an example and the steps to replicate the issue. I have created a demo with React custom editor here so you can just put your custom logic there and fork the example https://jsfiddle.net/62xrhtma/1/ 

ps. here https://jsfiddle.net/handsoncode/f0b41jug/ is a complex example of a key-value dropdown that can help you with your development.

**Comment by AMBudnik** [comment]
I can close this example as there is no feedback for 10 days or any further steps to replicate the issue.

@yutian0414 please send the demo to me at support@handsontable.com when you'll be ready
