### ISSUE TITLE
After the project is packed(npm run build) and put online，The EditorComponents listed below will become the first custom EditorComponent

### ISSUE THREAD

**Issue by limyxi** [handsontable/handsontable#7822]
### Description
I use some EditorComponents.When i run the project locally, everything is okay.But After the project is packed(npm run build) and put online, when the EditorComponents is fired, all the EditorComponents become the first EditorComponents。i want to know why this happened,and if i need to do  some additional configuration when i build the project

### Demo
LOCAL:
![image](https://user-images.githubusercontent.com/20531560/115209214-fa4fca00-a12f-11eb-8154-359654c13eee.png)
![image](https://user-images.githubusercontent.com/20531560/115209314-105d8a80-a130-11eb-9178-0698a0b97fe6.png)
ONLINE
![image](https://user-images.githubusercontent.com/20531560/115209607-587cad00-a130-11eb-91b0-7f402f4655e6.png)
![image](https://user-images.githubusercontent.com/20531560/115211011-bcec3c00-a131-11eb-9a0d-531cfda393b3.png)

### Your environment
* vue version: 2.6.11
* @handsontable/vue version:5.1.0
* handsontable version:8.3.0
* Browser Name and version:chrome
* Operating System:windows10

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting @limyxi 
Could you send over the .zip of the project to support@handsontable.com?
