### ISSUE TITLE
Can we call expand and collapse function explicitly in nested rows in handsontable

### ISSUE THREAD

**Issue by abhishek3092** [handsontable/handsontable#7829]
I have a requirement where i want collapse all the rows on load. Can we do that.

**Comment by AMBudnik** [comment]
Hi @abhishek3092 

You can use the `collapsingUI` with the `collapseChildren` method https://jsfiddle.net/handsoncode/mnse4q90/ (not yet officially documented). But, table has to be rendered to run this method.
