### ISSUE TITLE
Add copy/pasting support using `ctrl/shift + insert`

### ISSUE THREAD

**Issue by mpeula-pe** [handsontable/handsontable#7838]
### Description
`Ctrl + c` and `Ctrl + v` is usually the way of copy/pasting, but there is another way of doing this action that is `Ctrl + Insert` and `Shift + Insert`.

Handsontable supports the first approach to copy/paste content but if you try to use the latter... all the copied content is pasted into the cell, even if there are multiple rows/columns in the clipboard.

### Steps to reproduce
1. Open the jsfiddle
2. Select a 2x2 grid from the table
3. Press `ctrl + insert`
4. Select a random cell
5. Press `shift + insert`

### Demo
https://jsfiddle.net/handsoncode/8ffpsqt6/

![image](https://user-images.githubusercontent.com/30433716/115696512-0e2f4200-a363-11eb-9dec-ff3ccccee6cc.png)

### Your environment
* Handsontable version: 8.3.2
* Browser Name and version: Chrome 89.0.4389.128
* Operating System: Windows 10 (64 bits)

**Comment by AMBudnik** [comment]
Hi @mpeula-pe 

<kbd>Ctrl</kbd> + <kbd>Insert</kbd> nor <kbd>Shift</kbd> + <kbd>Insert</kbd>  are not mentioned in the official list of supported shortcuts provided at https://handsontable.com/docs/8.3.2/tutorial-keyboard-navigation.html

While adding a custom shortcut to Handsontable you can block the execution of the default event that would take place. But even if we use `preventDefault` method in the event of `beforeKeyDown` we still would need to read the clipboard (to execute the paste method of the `copyPaste` plugin like here http://jsfiddle.net/handsoncode/ga84khwb/). However, I will need to confirm that.

ps. as deduced here - https://github.com/handsontable/handsontable/issues/7429 - <kbd>Insert</kbd> works differently on devices/browsers.

**Comment by swistach** [comment]
Unfortunately, it seems to be a bug in Handsontable. Accordingly, to the following [example](https://jsbin.com/decofesesi/1/edit?js,output),  browser properly recognize `copy` and `paste` events for <kbd>Ctrl</kbd> + <kbd>Insert</kbd> and <kbd>Shift</kbd> + <kbd>Insert</kbd>.
For some reason, EditorManager:
1) on pasting - opens a fast editing mode for the highlighted cell,
2) on copying - copies an empty string/clears the clipboard.

**Comment by AMBudnik** [comment]
Thank you @swistach 
We should also then add the information to the documentation.

**Comment by aninde** [comment]
This issue is included in v9.0.2 along with the documentation supplement.

**Comment by swistach** [comment]
Hi @mpeula-pe,
I'm happy to announce we just released v9.0.2 with the fix to this bug.
