### ISSUE TITLE
help wanted: what's different in data binding between 7.0 and 8.0？

### ISSUE THREAD

**Issue by llcat** [handsontable/handsontable#7851]
### Description
the same settings work well in 7.0+ but not work in 8.0+, it seems that caused by data binding, but i don't know how to migrate it, anybody can help me?

### Steps to reproduce

1. use handsontable 7.1.0 and @handsontable/vue 4.1.0, `this.dataList = [...]` works well
2. change version handsontable 8.3.2 and @handsontable/vue 6.0.0，`this.dataList = [...]`  not work, data not display in table
see demo on codesandbox

### Demo

https://codesandbox.io/s/pensive-kirch-ocrbi?file=/src/App.vue

### Your environment
* Vue wrapper version: 6.0.0
* Handsontable version: 8.3.2
* Browser Name and version: chrome lastest version
* Operating System: win10

**Comment by swistach** [comment]
Hi @llcat,
Regarding [breaking changes in Handsontable v8](https://github.com/handsontable/handsontable/releases/tag/8.0.0), changing data by reference is no longer supported. To reflect changes, use Handsontable's API methods such as setDataAtCell, populateFromArray, etc.- full list of public methods you can find in our [documentation](https://handsontable.com/docs/8.3.2/Core.html).

Please look at the adjusted demo: https://codesandbox.io/s/condescending-mclean-bkxjx?file=/src/App.vue
