### ISSUE TITLE
Handsontable in Handsontable row selection with backer value

### ISSUE THREAD

**Issue by AndyWorral** [handsontable/handsontable#786]
I may be hoping for functionality that was not intended or perhaps am using it wrong, but is there a way to do a mix of autocomplete and HOT in HOT?

would be nice to utilize the search in HOT feature you did in the one example in the sub HOT, which would filter out rows and then would highlight the entire row which when selected would return the value of a designated property.

So you might have the following in the table
when I start typing I search name and description for matches

[Company Image] [CompanyName] [Description]

The whole row highlights like in Autocomplete when hovering row or using keyboard, and then when I select the row/enter I get a value from that row like [CompanyID]

Thanks!

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
