### ISSUE TITLE
Validate editor for "numeric" types with http://www.decorplanit.com/plugin/

### ISSUE THREAD

**Issue by AndyWorral** [handsontable/handsontable#787]
I have used this plugin (http://www.decorplanit.com/plugin/) a bit and would be nice to use when editing a numeric field.  

Obviously would have issue with paste allowing bad values through, but would be great for single field editing. 

I think it may be as easy as calling autoNumeric(<forwardedOptions>) on the edit field and then calling ('get') when done for final value which can then be formatted by the handsontable's formatter.

**Comment by AMBudnik** [comment]
On [0.12.4](https://github.com/handsontable/handsontable/releases/tag/0.12.4) we fixed some bugs with `numeric` validator. If you would expericence some issue with that options, please reply and we'll reopen this issue.
