### ISSUE TITLE
No vertical scroll when using absolute positioning and dimensions

### ISSUE THREAD

**Issue by pjfiers** [handsontable/handsontable#792]
This is the css for my container div
```
#datagrid {
    position:absolute;
    top:42px;        
    left:0;
    right:0;
    bottom:10px;                
    overflow:scroll;
}
````
These are my HOT settings
````
$datagrid.handsontable({
    data: <?php echo $jsData; ?>,
    manualColumnResize: true,
    fixedRowsTop: 1,
    fixedColumnsLeft: 1,
    stretchH: 'all',                    
    columnSorting: true,
    colHeaders: [<?php echo $jsHeaders; ?>]
    columns: [<?php echo $jsCols; ?>]
});
````
Horizontal scrolling works, although the scrollbar is rendered outside the visible document.

Vertical scrolling doesn't, no scrollbar is rendered and moving the active cell down doesn't scroll the content vertically either.

**Comment by AMBudnik** [comment]
Can you provide an information what you echo in `colHeaders` and `columns`?

**Comment by AMBudnik** [comment]
Issue closed in lack of further author's activity for a month.
