### ISSUE TITLE
afterCreateRow event fires before handsontable is fully initialized. Is this intended or a bug?

### ISSUE THREAD

**Issue by Assimilater** [handsontable/handsontable#795]
So basically I'm trying to pre-populate a new row in a way that will stick (and either http://handsontable.com/demo/prepopulate.html has a bug in that it doesn't 'fills the row with the template values' which would be another matter or it simply doesn't do this). So I tried approaching it with the event afterCreateRow (see my fiddle: http://jsfiddle.net/Assimilater/gqy9P/4/).

However it appears that in referencing Table.handsontable('method', ...) inside this method causes an error while it's initializing?

Am I doing something wrong or is this a bug?

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.
