### ISSUE TITLE
Support variable/dynamic width row headers

### ISSUE THREAD

**Issue by chahu** [handsontable/handsontable#797]
Handsontable lacks the ability to properly display headers if they are dynamically populated from user data or other data **not** known at development time.

http://jsfiddle.net/4587J/10/

Please see the above example; refresh a few times to see the truncation issue.  The situation for row headers in particular is bad.  Writing css **during development** with a **fixed** pixel width is not a viable solution.  Header widths should dynamically adjust at runtime depending on the data.  Column headers work for the most part; the only issue appears to be a 200 pixel limit which concerns me less than the situation for row headers.

Suggestions welcome.  Thanks.

**Comment by filipstachura** [comment]
+1

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
