### ISSUE TITLE
New docs: Before the deploy seek for errors in the console

### ISSUE THREAD

**Issue by Osky772** [handsontable/handsontable#7986]
### Description

While working on the new documentation project, I've noticed some problems in the developer console.
Create a PR to the `feature/issue-7624` branch.

1. In "Guides" - Vue examples: open page with the Vue rendered in the preview and then open "Installation" page. It doesn't breaks the preview.

https://user-images.githubusercontent.com/33433795/117468791-56e71d80-af55-11eb-9d27-0e8d3cfb9d4b.mov

2. In "https://dev.handsontable.com/docs/next/dropdown-cell-type/": select something in the dropdown and then open next page. It doesn't breaks the preview.

https://user-images.githubusercontent.com/33433795/117468902-73835580-af55-11eb-95c8-8ef6f8ff44c1.mov

3. Everywhere: refresh the page where the preview examples are. It breaks example previews of the refreshed page.

https://user-images.githubusercontent.com/33433795/117469271-cd841b00-af55-11eb-96a7-ac9db9142e4a.mov

**Comment by Siemienik** [comment]
Thank you @Osky772 for this issue, I marked it as TODO.

**Comment by aninde** [comment]
On my part, I finished it. on the occasion of the 1st iteration of tests, I reported:
https://github.com/handsontable/handsontable/issues/8301
https://github.com/handsontable/handsontable/issues/8300
https://github.com/handsontable/handsontable/issues/8289
https://github.com/handsontable/handsontable/issues/8271

**Comment by aninde** [comment]
Cases reported https://github.com/handsontable/handsontable/issues/7986#issue-879173650 are fixed. 
Closing https://github.com/handsontable/handsontable/issues/7986 as done.
