### ISSUE TITLE
Prevent input checkbox from being deleted

### ISSUE THREAD

**Issue by kongondo** [handsontable/handsontable#800]
Is it possible to prevent an input checkbox from being deleted? I know I can use read only on a column with checkboxes but that means I will not be able to select those checkboxes. Alternatively, how do I avoide the #bad value# error if an input checkbox is deleted? Thanks.

**Comment by tronghuy** [comment]
This is less of a hack than using HTML and solve the problem for me. When defining the checkbox in columns set checkedTemplate:true and uncheckedTemplate:null.

Example
columns: [{ data:'hasCoffee', type:'checkbox', checkedTemplate:true, uncheckedTemplate:null }]

To avoid the #bad value# error when rendering, I set any value associated with a checkbox cell to null (if it is undefined or false) before passing the data to handsontable.
