### ISSUE TITLE
Read-only merger

### ISSUE THREAD

**Issue by qingshanrumng** [handsontable/handsontable#8013]
### Description

Read-only cells are merged and not immediately implemented.It requires me to click on multiple other cells before it merges the read-only cells. I don't know why, but I need read-only cell merges to be as fast as normal cell merges.
The official demo also has this bug
### Steps to reproduce

1.Set read-only properties to several cells in the official demo（https://handsontable.com/examples?headers&merge-cells&manual-resize&manual-move&conditional-formatting&filters&fixed）
2.Merge the set of read-only cells and you will see that they are not merged,But when you click on other cells, it merges
3.The official demo also has this bug

### Demo
<!--- https://handsontable.com/examples?headers&merge-cells&manual-resize&manual-move&conditional-formatting&filters&fixed

### Your environment
* Vue wrapper version:"vue": "2.6.12",
* Handsontable version:"@handsontable/vue": "^6.0.0",
* Browser Name and version:Google 90.0.4430.212
* Operating System:windo10

**Comment by AMBudnik** [comment]
Hi @qingshanrumng 

Thank you for sharing the issue report. This issue is already reported at https://github.com/handsontable/handsontable/issues/5184
I will update you as soon as we fix it.

**Comment by qingshanrumng** [comment]
Thank you for answering my questions,I will try the `editor:false` you propose in the #5184 to achieve the functionality I need.

**Comment by AMBudnik** [comment]
If you'd need anything else @qingshanrumng please feel free to contact me at support@handsontable.com
