### ISSUE TITLE
[QUESTION] Is there a reliable way to count HT renders

### ISSUE THREAD

**Issue by dtomaszewski** [handsontable/handsontable#8018]
Description
I'd like to start using batch feature to reduce HT renders. It would be good to know whether is there any reliable way of counting how many times HT is rendered, it'll be very useful while introducing batch in more places.

It can be source code place or whatever it needs just to get this value.

Steps to reproduce
N/A

Your environment
Handsontable version: 8.4.0
Browser Name and version: Chrome 90
Operating System: MacOs

**Comment by AMBudnik** [comment]
Hi @dtomaszewski 

I recommend logging `afterRender` calls (reference: https://handsontable.com/docs/8.4.0/Hooks.html#event:afterRender)

**Comment by dtomaszewski** [comment]
Thanks @AMBudnik :)
