### ISSUE TITLE
[8.4.0] Missing collapsibleIndicator on IE

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8028]
### Description
There is no `collapsibleIndicator` and script causes error on the IE with v8.4.0 while collapsing columns are enabled.

<img width="670" alt="Screenshot 2021-05-13 at 13 57 27" src="https://user-images.githubusercontent.com/30186818/118122478-34d91980-b3f3-11eb-96ca-718b36c92335.png">

Error is on line in the full.js
`td.colSpan = headerObj.colspan;`

### Steps to reproduce

1. Open https://handsontable.com/docs/8.4.0/demo-collapsing-columns.html on IE

### Demo

https://handsontable.com/docs/8.4.0/demo-collapsing-columns.html

### Your environment
* Handsontable version: 8.4.0
* Browser Name and version: Internet Explorer 11
* Operating System: Windows 10

**Comment by swistach** [comment]
I'm happy to announce we just released v9.0.2 with the fix to this bug.
