### ISSUE TITLE
[8.0.0+] `toHTML()` returns an error if only `colHeaders` or `rowHeaders` are on

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8041]
### Description

The `toHTML()` returns an error if `colHeaders` are on in versions 8+

### Steps to reproduce

1. Go to https://jsfiddle.net/handsoncode/bqepxasw/ (7.4.2.)
2. Log result 
![image](https://user-images.githubusercontent.com/10757813/118469908-75dc7100-b706-11eb-92dd-56ec28d4738a.png)
3. Go to https://jsfiddle.net/handsoncode/3mg8rsxc/ (8.0.0)
4. Log result
![image](https://user-images.githubusercontent.com/10757813/118469567-1b431500-b706-11eb-815c-525eabb2a71a.png)

### Details
* it works well if we turn off both - column and row headers https://jsfiddle.net/handsoncode/021Lp9jd/1/
* it breaks for only `colHeaders` or only `rowHeaders` https://jsfiddle.net/handsoncode/k46vr73o/

### Demo

https://jsfiddle.net/handsoncode/1efLzgu7/ 7.4.2 - last working
https://jsfiddle.net/handsoncode/3mg8rsxc/ 8.0.0 - first broken 
https://jsfiddle.net/handsoncode/6ua5efqr/ - (current) 8.4.0 - still broken

### Your environment
* Handsontable version: 8+
* Browser Name and version: Chrome 89
* Operating System: Windows 10

**Comment by aninde** [comment]
This issue will be fixed by v9.0.2
Demo https://jsfiddle.net/zd2cL7gh/

Result from v9.0.2:
`<table><thead><tr><th>A</th><th>B</th><th>C</th></tr></thead><tbody><tr><td >3</td><td >5</td><td >6</td></tr><tr><td >6</td><td >7</td><td >9</td></tr></tbody></table>`

**Comment by swistach** [comment]
I'm happy to announce we just released v9.0.2 with the fix to this bug.
