### ISSUE TITLE
[9.0.0] Cells' formulas miss calculation when the value is deleted

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8044]
### Description

When the cells' formulas point to the cells that are deleted using the <kbd>DELETE</kbd> key. The calculated values are `0` and there should be an empty string.

The same bug can be reproduced when the formula points to the cell out of the table range.

### Steps to reproduce

1. Go to https://jsfiddle.net/budnix/spc8bm1r/2/;
2. Try to delete the A1 cell;
3. In results, the B1 cell that points to the A1 (`=A1`) has the value `0`;
4. Additionally, the E1 cell with `=AB20` formula calculates its value as `0`. I assume that here an empty string should be returned or some kind of error.

### Demo

https://jsfiddle.net/budnix/spc8bm1r/2/

### Your environment
* Handsontable version: 9.0.0
* Browser Name and version: -
* Operating System: -

**Comment by wojciechczerniak** [comment]
I think that the reason for this behavior is an Excel compatibility feature called `evaluateNullToZero`. Set to `true` as default for the new plugin

<img width="263" alt="Screenshot 2021-05-17 at 15 32 23" src="https://user-images.githubusercontent.com/4718998/118497136-15106100-b725-11eb-872a-251708a91f1d.png">

> Additionally, the E1 cell with =AB20 formula calculates its value as 0. I assume that here an empty string should be returned or some kind of error.

A cell `=AB20` as long as it's not beyond `maxRows` and `maxCols` settings is a part of the sheet. The cells beyond those limits are in fact returned as `#REF!` error.

**Comment by wojciechczerniak** [comment]
Works as designed
