### ISSUE TITLE
[9.0.0] Sorting doesn't work while HyperFormula is enabled as formulas engine 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8046]
### Description

Sorting doesn't work when HyperFormula is working as a formulas engine. 
There's any information about it in the logs or documentation. 

This is a regression compared to the previous engine, so I'm adding the proper label. 
without HyperFormula + v8.4.0 https://jsfiddle.net/qb7cw8g0/

### Case 1
Sorting, multicolumnSorting doesn't seems to work
Demo v9.0.0 from [PR ](https://github.com/handsontable/handsontable/pull/7648)+ HF v.0.6.0
https://codesandbox.io/s/test1-forked-h2s9m
### Steps to reproduce

1. Open demo
2. Click to sort or any header

**Actual result**
Nothing changes

### Case 2
The read-only property is shifted when sorting between cells, but the cell values themselves do not sort.
https://codesandbox.io/s/sorting-handsontable-wtih-hf-forked-f3bjv
![readonly-sorting](https://user-images.githubusercontent.com/30186818/118507621-b18b3100-b72e-11eb-8e97-1e341145bac6.gif)

### Demo

https://codesandbox.io/s/test1-forked-h2s9m

### Your environment
* Handsontable version: build from https://github.com/handsontable/handsontable/pull/7648, pre9.0.0
* Browser Name and version: Chrome
* Operating System: macOS

**Comment by wojciechczerniak** [comment]
Sorting is not supported by the current plugin and on a future feature list for the new one

![Screenshot 2021-05-17 at 16 43 59](https://user-images.githubusercontent.com/4718998/118508066-1fcff380-b72f-11eb-9f0d-611b525c6adc.png)

**Comment by budnix** [comment]
It seems that documentation was no up to date. The old formulas engine supports sorting 🤯

**Comment by nikersify** [comment]
Should be fixed after #8067

**Comment by aninde** [comment]
Works with v9.0.0 https://jsfiddle.net/aninde/gq1cLzrj/.
