### ISSUE TITLE
[9.0.0] Some new formulas e2e  doesn't support IE

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8051]
### Description

Some new tests don't pass in the IE 11 due to the lack of support.
1.  https://github.com/handsontable/handsontable/blob/783607d9d8a39bd6ec41d94dfc6e28a451cb4a9a/src/plugins/formulas/__tests__/formulas.spec.js#L84-L111
<img width="698" alt="Screenshot 2021-05-17 at 10 28 43" src="https://user-images.githubusercontent.com/30186818/118497005-f1e5b180-b724-11eb-840a-e300dc135415.png">

2.  https://github.com/handsontable/handsontable/blob/783607d9d8a39bd6ec41d94dfc6e28a451cb4a9a/src/plugins/formulas/__tests__/initialization.spec.js#L53-L75
<img width="916" alt="Screenshot 2021-05-17 at 10 28 51" src="https://user-images.githubusercontent.com/30186818/118497010-f3af7500-b724-11eb-870e-2cbc77742515.png">

3. https://github.com/handsontable/handsontable/blob/783607d9d8a39bd6ec41d94dfc6e28a451cb4a9a/src/plugins/formulas/__tests__/initialization.spec.js#L723-L758

<img width="1190" alt="Screenshot 2021-05-17 at 10 29 22" src="https://user-images.githubusercontent.com/30186818/118639511-46963480-b7d8-11eb-92e4-41313f915051.png">

4. https://github.com/handsontable/handsontable/blob/783607d9d8a39bd6ec41d94dfc6e28a451cb4a9a/src/plugins/formulas/__tests__/initialization.spec.js#L53-L75
<img width="928" alt="Screenshot 2021-05-17 at 10 28 58" src="https://user-images.githubusercontent.com/30186818/118639514-47c76180-b7d8-11eb-87c2-1c8fcee567a7.png">

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: v9.0.0 from [PR ](https://github.com/handsontable/handsontable/pull/7648)+ HF v.0.6.0
* Browser Name and version: Internet Explorer 11
* Operating System: Windows 10

**Comment by nikersify** [comment]
Closed via #8064
