### ISSUE TITLE
Feature Request: Accessibility VPAT

### ISSUE THREAD

**Issue by codekiln** [handsontable/handsontable#8052]
Please include a few basic features to disclose your level of engagement with accessibility / a11y / inclusive design: 
1. Ensure the docs have an accessibility section - they [don't currently have any search results for accessibility](https://handsontable.com/docs/8.4.0/tutorial-introduction.html): 
![image](https://user-images.githubusercontent.com/140930/118549164-13489c80-b729-11eb-9cbe-2c8a802abee8.png)
2. Author a [Voluntary Product Accessibility Template (VPAT)](https://www.section508.gov/sell/vpat) or Accessibility Conformance Report (ACR) and link to it in your docs. A VPAT is a "tool for vendors to document product compliance to Section 508 and facilitate government market research on ICT with accessible features" (see wikipedia article for [Voluntary Product Accessibility Template](https://en.wikipedia.org/wiki/Voluntary_Product_Accessibility_Template). 

Right now, it's not clear whether a11y gets any significant attention by this product or whether the product has participated in any a11y audits.

**Comment by AMBudnik** [comment]
Hi @codekiln 

Providing all the necessary changes for accessibility (as not all are met now) is our plan for Q3-Q4 this year.

**Comment by AMBudnik** [comment]
I'm moving this topic to Github Discussions. I will update the subject as soon as we move to the development of this task. 

But I also welcome everyone to share their ideas and requests regarding Accessibility.
