### ISSUE TITLE
[9.0.0] Uncaught Error - Table breaks when `minSpareRows` or `minSpareCols` are added

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8054]
### Description

Uncaught Error - Table breaks when `minSpareRows` or `minSpareCols` are added

![image](https://user-images.githubusercontent.com/10757813/118621998-3164da00-b7c7-11eb-9b27-8b935ea220ff.png)

### Steps to reproduce

1. Open 9.0.0 demo
2. Comment out the `minSpareRows`  /`minSpareCols` to remove the error and display the table again

### Demo

https://jsfiddle.net/handsoncode/q8orpLjv/ 8.4.0 - displays
https://jsfiddle.net/handsoncode/wdeh4fuq/ 9.0.0 - doesn't display (spare rows)
https://jsfiddle.net/handsoncode/512svwdc/  9.0.0. - doesn't display (spare columns)

### Your environment
* Handsontable version: 9+
* Browser Name and version: chrome 89
* Operating System: Windows 10

**Comment by nikersify** [comment]
Brief investigation, seems like the `modifyData` hook is getting called before we have the chance to `this.engine.addSheet` in `onBeforeLoadData`, probably related to #8056

**Comment by AMBudnik** [comment]
### Update for the recent build for v9

**spare rows** - https://jsfiddle.net/agfhbodw/1/
We no longer get the error but the spare rows are not attached

**spare columns** - https://jsfiddle.net/mpuysw87/
We no longer get the error but the spare columns are not attached

In both cases when we comment out the formula missing spare rows and columns appear.

**Comment by AMBudnik** [comment]
As the main issue is fixed I'm closing this repression and open a new issue at https://github.com/handsontable/handsontable/issues/8110 for the lack of spare rows and columns in the latest build.
