### ISSUE TITLE
[9.0.0] Moving columns/rows doesn't work

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#8058]
### Description
It seems that moving element doesn't work. After drag using mouse we can see that sequence of indexes doesn't change.

#### For columns (similar behaviour for rows)

1. Open the demo.
2. Drag any cell with `B1` value at first position.
3. You can see that position of cell won't change.

Before (probably also bugged in some cases?)

![before](https://user-images.githubusercontent.com/141330/118632106-645f9b80-b7d0-11eb-8b71-49f7a63f8bc8.gif)

After

![after](https://user-images.githubusercontent.com/141330/118632138-6b86a980-b7d0-11eb-8aef-1fe69b97e3c1.gif)

### Demo

https://jsfiddle.net/wojciech/m6450tj8

### Your environment
* Handsontable version: 9.0.0

**Comment by AMBudnik** [comment]
We should also check the case when the rows are programmatically moved like here https://jsfiddle.net/handsoncode/7kng1hsv/ (it also works well when we comment out the formula engine)

**Comment by nikersify** [comment]
Should be fixed after #8067

**Comment by AMBudnik** [comment]
Moving columns **is achievable** using the v9 build https://jsfiddle.net/xn19v8k5/1/
However, instead of getting a string in the place of formula, we get a value in the place of formula.

![moved](https://user-images.githubusercontent.com/10757813/119649202-a9b04880-be22-11eb-9225-10cb5d7a04c9.gif)

**Comment by AMBudnik** [comment]
As we can move the columns I've separated the issue with the removal of the formula here https://github.com/handsontable/handsontable/issues/8114 
We can call this regression solved.

**Comment by AMBudnik** [comment]
The https://github.com/handsontable/handsontable/issues/8114 was just fixed in v12.4.0
