### ISSUE TITLE
Getting actual removed rows from 'afterRemoveRow' callback

### ISSUE THREAD

**Issue by markschl** [handsontable/handsontable#806]
Hi

I'm trying to get a reference to the actual row data from the removed rows. The 'afterRemoveRow' event callback will get me the row index, however since the rows have already been removed from the data I can't see an easy way to get the deleted rows (unless I miss something).

Would it be possible to pass those rows as event data (i.e. as 3rd argument)? This should be easy, since the 'splice' command in your code returns those items, if I get it correctly.

thanks!

**Comment by lesterjanpearson** [comment]
When remove multiple rows using context menu only returns 1 index. how do you get the rest of the index?

**Comment by AMBudnik** [comment]
Hi @lesterjanpearson 

what exactly you'd like to get? The hook returns 3 parameters so maybe it'll be possible to extract needed data from them.

**Comment by lesterjanpearson** [comment]
so I highlight 3 rows, right click, press remove row, it removes the rows. but the beforeRemoveRow only returns 1 index of the remove

**Comment by AMBudnik** [comment]
@lesterjanpearson please continue at https://github.com/handsontable/handsontable/issues/5012
