### ISSUE TITLE
[9.0.0] `ManualColumnFreeze` freezes wrong columns when HF is used

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8060]
### Description

`ManualColumnFreeze` freezes wrong columns when HF is used.

### Steps to reproduce

1. Go to https://jsfiddle.net/handsoncode/tdh5r384/
2. Use column freeze on column `B` -> column `A` is frozen (incorrect)
3. Comment out the formulas and save the fiddle
4. Use column freeze on column `B` -> column `B` is frozen (correct)

### Demo

https://jsfiddle.net/handsoncode/qzj83Lt9/ 9.0.0 - broken
https://jsfiddle.net/handsoncode/8oqj21e3/ 8.4.0 - working well

### Your environment
* Handsontable version:  9+
* Browser Name and version: Chrome 89
* Operating System: Windows 10

**Comment by nikersify** [comment]
Should be fixed after #8067

**Comment by AMBudnik** [comment]
True @nikersify It **works well** with the recent build https://jsfiddle.net/u274ktvb/

![freeze](https://user-images.githubusercontent.com/10757813/119648435-be401100-be21-11eb-9b35-296c2f93525c.gif)

**Comment by nikersify** [comment]
I'm assuming this can be closed then @AMBudnik
