### ISSUE TITLE
[9.0.0] column width is not updated when formula result needs more space (number of chars is greater than on the init)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8061]
### Description

The column width is not updated when formula result needs more space (number of chars is greater than on the init)

### Steps to reproduce

1. Go to https://jsfiddle.net/handsoncode/jyv5som1/
2. Type 99999 in `B1`

Result in v9 (column does not expand with value)
![v9](https://user-images.githubusercontent.com/10757813/118645167-e5be2a80-b7de-11eb-9bc8-2112f81e51a6.gif)

Result in v8
![v8](https://user-images.githubusercontent.com/10757813/118645217-f1115600-b7de-11eb-83f8-2b104117760a.gif)

### Demo

https://jsfiddle.net/handsoncode/146eprgt/ v9 - broken
https://jsfiddle.net/handsoncode/dn8p6c9z/ v8.4.0 - working

### Your environment
* Handsontable version: 9+
* Browser Name and version: Chrome 89
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
### Case 2
#### It also does not shrink accordingly to the content

1. Go to https://jsfiddle.net/handsoncode/joenrc5b/ (v9)
2. Change `B1` to `1`

Result v9
![v9_](https://user-images.githubusercontent.com/10757813/118646002-eefbc700-b7df-11eb-9eb7-d0db55750ea6.gif)

Result in v8.4.0 (https://jsfiddle.net/handsoncode/vkxf1wdc/)
![v8_](https://user-images.githubusercontent.com/10757813/118646117-0fc41c80-b7e0-11eb-9daa-499709fd5fce.gif)

**Comment by aninde** [comment]
#### Case 2
Result in v9.0.0 + HF  https://jsfiddle.net/aninde/z9csvb0m/ 
wrong width, wrong validation
![Kapture 2021-05-21 at 09 40 10](https://user-images.githubusercontent.com/30186818/119100948-c3175600-ba18-11eb-98d2-2895d3408436.gif)

Result in v8.4.0 (https://jsfiddle.net/aninde/xvsnr4od/ )
<img width="324" alt="Screenshot 2021-05-21 at 09 40 38" src="https://user-images.githubusercontent.com/30186818/119100888-b3980d00-ba18-11eb-928e-474b3098d521.png">

<img width="324" alt="Screenshot 2021-05-21 at 09 40 38" src="https://user-images.githubusercontent.com/30186818/119100888-b3980d00-ba18-11eb-928e-474b3098d521.png">

Found by @wszymanski

**Comment by aninde** [comment]
This case is fixed in v9.0.0 
https://jsfiddle.net/aninde/91vdnrg8/ 
<img width="383" alt="Screenshot 2021-06-10 at 13 07 14" src="https://user-images.githubusercontent.com/30186818/121514928-dea8c780-c9ec-11eb-9c09-a655d04a3269.png">
