### ISSUE TITLE
[9.0.0] Autofill truncates column header 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8063]
### Description
Autofill truncates the column header even when formulas aren't enabled. 
Sometimes (with array data source) made for column 1 (A) and column 2 (B) works correctly, it breaks from 3 (C).
This is a regression to v8.4.0.

### Steps to reproduce

1. Open demo. 
2. Select the first cell in column C or B if col C is empty.
3. Autofill downwards or to the left.

### Case 1
Array data source
https://jsfiddle.net/w2rgzapx/ v9.0.0 (broken)
https://jsfiddle.net/h5qnx0kf/3/ v8.4.0 (works)
![Screenshot 2021-05-18 at 17 29 31](https://user-images.githubusercontent.com/30186818/118680080-b9b2a180-b7fe-11eb-8971-1efd53aa911b.png)

### Case 2
Object data source
https://jsfiddle.net/8qrokepu/1/ v9.0.0 (broken)
https://jsfiddle.net/vt94c50L/ v8.4.0 (works)
![Screenshot 2021-05-18 at 17 29 44](https://user-images.githubusercontent.com/30186818/118680113-bf0fec00-b7fe-11eb-9935-e83028ffa42a.png)

### Case 3 
Function data source and schema
https://jsfiddle.net/90fokj4g/1/ v9.0.0 (broken)
https://jsfiddle.net/90fokj4g/ v8.4.0 (works)
![Screenshot 2021-05-18 at 17 29 59](https://user-images.githubusercontent.com/30186818/118680144-c33c0980-b7fe-11eb-9fe1-401225d760d7.png)

### Your environment
* Handsontable version:  v9.0.0 from [PR](https://github.com/handsontable/handsontable/pull/7648)
* Browser Name and version: Chrome 90
* Operating System:

**Comment by AMBudnik** [comment]
### Update for v9 build (26th of May) - all cases for the truncated header are fixed

Case 1 - **solved** https://jsfiddle.net/wet3ap42/
![image](https://user-images.githubusercontent.com/10757813/119647435-8daba780-be20-11eb-84e9-667b67577821.png)

Case 2 - **solved** https://jsfiddle.net/z2hog1yd/
![image](https://user-images.githubusercontent.com/10757813/119647564-b338b100-be20-11eb-87c1-6e4bc3314b99.png)

Case 3 - **solved** https://jsfiddle.net/fxke65u0/1/
![image](https://user-images.githubusercontent.com/10757813/119647669-d7948d80-be20-11eb-920e-54e029f29b50.png)
