### ISSUE TITLE
[9.0.0] Validation is broken when cell data being changed.

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8066]
### Description

Editing cell value to set a new one- a formula- causes a validation error. It occurs by a red background without console errors.

https://user-images.githubusercontent.com/2893099/118807299-639a3880-b8a8-11eb-970e-4b4cfc1392f7.mp4

After a short investigation with a team, we found:
* The error exists only if a formula as a value has proceeded.
* The error does NOT exist if `hot.validateCells()` function is called.
* The error occurs independently of the used wrapper or without.

As the source of this bug we point to the difference between `validateCells => _validateCells => validateCell` and `setDataAtCell => validateChanges => validateCell`. 
Where the first one gets data by calling `getDataAtCell()`, and the second one by using `changes[i][3]`.

Links to the source:
* https://github.com/handsontable/handsontable/blob/783607d9d8a39bd6ec41d94dfc6e28a451cb4a9a/src/core.js#L3283
* https://github.com/handsontable/handsontable/blob/783607d9d8a39bd6ec41d94dfc6e28a451cb4a9a/src/core.js#L1127

### Steps to reproduce
1. On the "Setting up a locale" demo
2. Edit cell and type a formula `=1+2`
3. [Or following by this movie](https://user-images.githubusercontent.com/2893099/118807299-639a3880-b8a8-11eb-970e-4b4cfc1392f7.mp4)

### Demo

https://github.com/Siemienik/handsontable-storrybooks/commit/591acf3fb7d9690dcec6ea4881bb8bad762be3ac#diff-c6f6cf3335c1b529b6d5944f547a5b6c6eda67b144979492f638fc2d6c3a16ecR113-R171

### Your environment
* Handsontable version: pre9.0.0
* Browser Name and version: Brave `Version 1.24.85 Chromium: 90.0.4430.212 (Official Build) (x86_64)` 
* Operating System: MacOS

**Comment by jansiegel** [comment]
Can't reproduce it, seems to be working fine now, @aninde, can you confirm?

**Comment by Siemienik** [comment]
It works now, probably fixed with some other issue
