### ISSUE TITLE
[9.0.0] Enabling HF prevents default cell initialization

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8069]
### Description

Enabling HF prevents default cell initialization.

### Case 1
Initialization

https://jsfiddle.net/Lnbco90v/ v9.0.0  with HF (broken)

<img width="680" alt="Screenshot 2021-05-19 at 14 42 31" src="https://user-images.githubusercontent.com/30186818/118814761-c68fcd80-b8b0-11eb-9ce5-12933b09bb73.png">

https://jsfiddle.net/s2m6kwp0/ v9.0.0 without HF (works)
<img width="278" alt="Screenshot 2021-05-19 at 14 42 41" src="https://user-images.githubusercontent.com/30186818/118814826-d9a29d80-b8b0-11eb-93a3-ee1c389ebfca.png">

### Case 2
Adding HyperFormula changes cell rendering while the custom editor is used.

Demo based on https://handsontable.com/docs/8.4.0/frameworks-wrapper-for-react-custom-editor-example.html.
Issue found by @Osky772.

v9.0.0 with HF (broken)
![Screenshot 2021-05-19 at 14 23 13](https://user-images.githubusercontent.com/30186818/118811901-d528b580-b8ad-11eb-9f97-a36b6586b777.png)

`v9.0.0 without HF` & `v8.4.0` 
![Screenshot 2021-05-19 at 14 20 16](https://user-images.githubusercontent.com/30186818/118811667-8ed35680-b8ad-11eb-9f9b-d4051571b89d.png)

### Demo

https://jsfiddle.net/2gt3edfy/5/ v9.0.0 with HF (broken)
https://jsfiddle.net/4Lqd5n2p/ v9.0.0 without HF (works)
https://jsfiddle.net/an0hf25c/ v8.4.0 (works)

### Your environment
* Handsontable version: v9.0.0 from [PR](https://github.com/handsontable/handsontable/pull/7648)
* Browser Name and version: Chrome 90
* Operating System: macOS 11.2.3

**Comment by nikersify** [comment]
For context, this doesn't seem to be an issue with rendering per-se, if you include some `data` the cells render fine: https://jsfiddle.net/d3rqmebx/

It's very likely this is just an issue with initialization, you can remove everything but `{formulas: {engine: HyperFormula}}` and still end up with a similar result: https://jsfiddle.net/Lnbco90v/

**Comment by aninde** [comment]
@nikersify true, thank you. I'll change this issue.

**Comment by aninde** [comment]
Demo update with v9.0.0 https://jsfiddle.net/aninde/96uxhbog/.
The bug is still valid.

**Comment by aninde** [comment]
This issue is fixed by v9.0.0 
https://jsfiddle.net/aninde/Lmgn603h/
![Screenshot 2021-06-07 at 15 15 00](https://user-images.githubusercontent.com/30186818/121023022-2d632100-c7a3-11eb-9fce-4218b8325baf.png)
