### ISSUE TITLE
Custom Context Menu example don't work as expected

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8073]
### Description
Custom context menu adds two rows instead of one. The additional row is added to the bottom of the table.
Issue found by @Siemienik  

Same example with React, Angular or Vanilla works well.

### Steps to reproduce

1. Open the context menu at any cell.
2. Insert row.

![inserting-vue](https://user-images.githubusercontent.com/30186818/118824609-48d0bf80-b8ba-11eb-80a0-befb204d6789.gif)

### Demo
https://jsfiddle.net/tj5a08rc/

### Your environment
* Vue wrapper version: 8.4.0
* Handsontable version: 8.4.0
* Browser Name and version: Chrome 90
* Operating System: macOS 11.2.3

**Comment by AMBudnik** [comment]
Reported at https://github.com/handsontable/handsontable/issues/8148
