### ISSUE TITLE
[9.0.0] When the new formula engine is defined undo does not bring back data in the previously removed columns

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8076]
### Description

When the new formula engine is defined undo does not bring back data in the previously removed columns.
If we comment our the engine it works well.

Note: Row removal works as expected.

### Steps to reproduce

1. Remove a column using context menu
2. Hit <kbd>CMD/CTRL</kbd> + <kbd>Z</kbd> to undo

![undo](https://user-images.githubusercontent.com/10757813/118970473-8f7ff180-b96e-11eb-861c-af58977ed7dc.gif)

### Demo

https://jsfiddle.net/handsoncode/bfkpcayv/ v9 - broken
https://jsfiddle.net/handsoncode/jw1podh7/ v9 without the formula engine defined - working well
https://jsfiddle.net/handsoncode/1ku4mvch/ v8.4.0 - working well

### Your environment
* Handsontable version: 9+
* Browser Name and version: Chrome 89
* Operating System: Windows 10

**Comment by aninde** [comment]
Removing via drop-down menu causes the same bug.
https://jsfiddle.net/j2L3sq1c/

**Comment by AMBudnik** [comment]
@aninde it works well with the latest freeze version https://jsfiddle.net/a3qj064h/1/ (I have even checked if the data is correct when we reorder the columns and it works as a charm)

**Comment by AMBudnik** [comment]
I'm happy to see this regression gone in the official release. I'm closing this issue as done.
