### ISSUE TITLE
Remove the deprecated plugins for 9.0.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#8083]
### Description
We need to remove the deprecated plugins in `9.0.0`:
- [Header Tooltips](https://handsontable.com/docs/8.4.0/demo-header-tooltips.html)
- [Observe Changes](https://handsontable.com/docs/8.4.0/ObserveChanges.html)

**Comment by AMBudnik** [comment]
Plugins are removed and the corresponding information is added to the migration guide v8 - v9 https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html
