### ISSUE TITLE
Is there a way to disable "row jumping" when one moves past its limits?

### ISSUE THREAD

**Issue by almosnow** [handsontable/handsontable#8085]
### Description
Hi all,

Let's say you are focused on the first column of any given row, then when you go left (i.e. by pressing left on the keyboard), the cursor would go to the last cell of the previous row. Similarly, if you are at the last column and press right, it would jump to the next row. I know this is a feature and I can understand how it would be heplful, but for my particular project I would like to disable it. Is there a way to do this?

### Your environment
* Handsontable version: v7+
* Browser Name and version: Chrome
* Operating System: Web

**Comment by AMBudnik** [comment]
Hi @almosnow 

You can block this operation using `stopImmediatePropagation` function for the `e.key === 'ArrowLeft'` and the first column (`column === 0`) in the `beforeKeyDown` callback.

Demo https://jsfiddle.net/handsoncode/m14y2egh/

**Comment by almosnow** [comment]
Thank you, that's a nice solution :D
