### ISSUE TITLE
Add a method/hook to track invalid cells like trackInvalidCells: true

### ISSUE THREAD

**Issue by marcok** [handsontable/handsontable#809]
Hi

Is there a way to get the count of invalid cells due to the new validator?

Marco

**Comment by AMBudnik** [comment]
Issue closed in lack of additional questions.

**Comment by adamdehaven** [comment]
I'd like to reopen this -- counting the number of cells with the `.htInvalid` class only works if the cell is currently within the viewport. If the cell is not visible at the time of checking, a count of zero will be returned.

**Comment by AMBudnik** [comment]
If you'd like to get the data outside the viewport you should use the following options
`viewportColumnRenderingOffset`
`viewportRowRenderingOffset`
If you set those to maximum (number of rows and columns in your table) the loading may take a bit longer but you'll get faster scrolling and information about all the cells (with their classes).

**Comment by adamdehaven** [comment]
@AMBudnik That's helpful, but I'm not sure I want to degrade the performance for the check.

As a separate question (I should prob. open another issue, but, here we are) is it possible within the `validateCells` method to get an array of invalid cells? (or something similar?)

I'm running `validateCells` before submitting data, however, if one or more cells are invalid, I'd like to select the first invalid cell.

**Comment by AMBudnik** [comment]
It is pretty much the same situation - to get all the elements with `htInvalid` className you'd need to render all of them. When it comes to searching the first one you can use a loop on `hot.getCell(1,1).className` and check if any of the classes in the array equals `htInvalid`.

**Comment by adamdehaven** [comment]
@AMBudnik I guess I could quickly toggle the visibility and check for invalid cells; just seems less than ideal when I'm thinking about it.

I'd like to suggest a feature request whereby a boolean setting could be set (something like `trackInvalidCells: true`) that would keep a running array of invalid cell indexes even if they _are not_ in the rendered area. This would have a corresponding method that would return the array of invalid cell indexes. I imagine setting the array could simply be hooked into the `afterValidate` function. 

I suppose I could also do this myself, but... yeah lol

This would be extremely helpful for use cases (like mine) where the table may have over 40 columns and over 500 rows and there's a need to track invalid cells.

**Comment by AMBudnik** [comment]
Good idea @adamdehaven 
I've reopened the topic and changed the title.

**Comment by AMBudnik** [comment]
Thank you again for sharing this idea!

I'm moving this topic to Github Discussions. I welcome everyone to discuss this functionality and share your feedback. See you there!
