### ISSUE TITLE
The MIN and MAX methods break in range notation when used together.

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8104]
### Description

The MIN formula does not support column range notation (or I missing something).

### Steps to reproduce

1. Go to https://jsfiddle.net/e6nwfdus/;
2. The cell D5 contains the MIN formula `=MIN(A:A)` the calculated value is `50.18` should be `10.26`;

### Demo

https://jsfiddle.net/e6nwfdus/

### Your environment
* Handsontable version: 9.0.0
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
I made some investigation. My conclusion is that:
MIN() formula supports range notation. However, this is broken when before the MIN method, there is a MAX function.
In that case MAX() function is broken. 

There seems to be a dependency between the MAX() and MIN() methods when they have range notation.

Demo https://codesandbox.io/s/happy-https-yowoj

**Max() before MIN (broken)**
<img width="463" alt="Screenshot 2021-06-10 at 12 13 21" src="https://user-images.githubusercontent.com/30186818/121507946-67bc0080-c9e5-11eb-9af5-89841e1353df.png">

****Max after MIN - MIN() is fixed, MAX() is broken**
<img width="456" alt="Screenshot 2021-06-10 at 12 11 42" src="https://user-images.githubusercontent.com/30186818/121507958-6a1e5a80-c9e5-11eb-8f60-aee4f2c7dc7b.png">

**Comment by izulin** [comment]
https://github.com/handsontable/hyperformula/pull/711

**Comment by jansiegel** [comment]
@aninde Could you re-check if it's working correctly now?

**Comment by aninde** [comment]
Works well for the current `develop` branch both when functions have single notation and rank notation. 
It will be possible to close this issue after the next release.

Demo: https://jsfiddle.net/e9y8sk1n/ (current `develop` branch).
