### ISSUE TITLE
[9.0.0] One e2e fails on Safari and FF

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8106]
### Description
MultiColumnSorting > data type: time > should properly rewrite time into correct format after sort
Expected '19:55' to equal '7:55:00 pm'.

### Your environment
* Handsontable version: 9.0.0
* Browser Name and version: Safari Version 14.0.3 (16610.4.3.1.7), FF 88.0.1
* Operating System: macOS  11.2.3 (20D91)

**Comment by jansiegel** [comment]
@aninde Are you sure it's an issue for `9.0.0`? It seems to look the same on `8.4.0` and before.

**Comment by aninde** [comment]
@jansiegel I run e2e tests during every freeze and report those that do not pass. 

Maybe the browser version has an impact on it, I will repeat testing on older versions using the BrowserStack.

![Screenshot 2021-05-26 at 15 59 54](https://user-images.githubusercontent.com/30186818/119673428-a1183c00-be3b-11eb-9604-6136a1cab604.png)



On freeze to v8.4.0 I reported https://github.com/handsontable/handsontable/issues/7910.

**Comment by aninde** [comment]
Repeated with the same result on Safari 13.1.2

**Comment by aninde** [comment]
@jansiegel you were right, this test fails also on current `develop` and on `master`.

**Comment by aninde** [comment]
Fixed by v9.0.0.
