### ISSUE TITLE
[9.0.0] We are not able to alter the number of rows by pasting data

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8109]
### Description

We are not able to alter the number of rows by pasting data or autofill.
It seems that data is replaced in the top of the table instead of adding new rows.

### Steps to reproduce

1. Copy the whole dataset
2. Paste it in the last cell in the grid

**Expected Result**
You should get more rows with pasted data.

![good](https://user-images.githubusercontent.com/10757813/119658162-1e888000-be2d-11eb-8fde-30537f461550.gif)

**Result**
No more rows are added than defined before paste.

![bad](https://user-images.githubusercontent.com/10757813/119658170-20eada00-be2d-11eb-90de-dc7b8b1f89d7.gif)

### Demo

https://jsfiddle.net/f36gyw9L/

### Your environment
* Handsontable version: v9+
* Browser Name and version: Chrome 89
* Operating System: Windows 10

**Comment by aninde** [comment]
This issue was fixed by v9.0.0
https://jsfiddle.net/aninde/evwx0kma/

![Screenshot 2021-06-07 at 15 12 29](https://user-images.githubusercontent.com/30186818/121022690-db220000-c7a2-11eb-9477-a2a35ee47ebd.png)
