### ISSUE TITLE
Invalid argument in IE8

### ISSUE THREAD

**Issue by pedroteixeira** [handsontable/handsontable#811]
I've seen happening on IE8 only for now in the current line:

```javascript
this.COLGROUP.childNodes[c + displayThs].style.width = this.columnStrategy.getSize(c) + 'px';
```

the function this.columnStrategy.getSize(c) returns "Infinity" might be causing it.

**Comment by AMBudnik** [comment]
We do not support IE 8 any more, but if you would have any questions about newer versions of IE (and not only), please give us a feedback.
