### ISSUE TITLE
[9.0.0] Spare rows and columns are not visible if formulas are enabled

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8110]
### Description

Spare rows and columns are not visible if formulas as enabled.
When we disabled formulas it works well.

### Steps to reproduce

1. Go to https://jsfiddle.net/4fcn3jg9/

**Expected result**
![image](https://user-images.githubusercontent.com/10757813/119658892-ef264300-be2d-11eb-8c77-3ddddfd14224.png)

**Actual result**
![image](https://user-images.githubusercontent.com/10757813/119658859-e46bae00-be2d-11eb-8e21-27f29b6fcdab.png)

### Demo

https://jsfiddle.net/4fcn3jg9/ 9.0.0. - broken
https://jsfiddle.net/4fcn3jg9/1/ 8.4.0 - works well

### Your environment
* Handsontable version: 9+
* Browser Name and version: Chrome 89
* Operating System: Windows 10

**Comment by aninde** [comment]
### Case 2
Pre-populating rows don't work with formulas in v9.0.0
https://jsfiddle.net/aninde/o9kh2rsm/ v9.0.0 (broken)

<img width="280" alt="Screenshot 2021-05-27 at 14 56 31" src="https://user-images.githubusercontent.com/30186818/119829684-c9676f80-befb-11eb-8996-1010eda8422a.png">

https://jsfiddle.net/aninde/augLe0mq/ v8.4.0 (fixed)
<img width="277" alt="Screenshot 2021-05-27 at 14 56 40" src="https://user-images.githubusercontent.com/30186818/119829699-ccfaf680-befb-11eb-88ec-aeed2231d27e.png">

**Comment by aninde** [comment]
This issue was fixed and released with v9.0.0.

https://jsfiddle.net/aninde/p30gqxje/ v9.0.0 
![Screenshot 2021-06-07 at 15 11 13](https://user-images.githubusercontent.com/30186818/121022450-9f873600-c7a2-11eb-9321-7c2ed7340f89.png)


https://jsfiddle.net/aninde/xj46b2h0/ v9.0.0 pre-populating rows

**Comment by AMBudnik** [comment]
Case 2 also fixed in the official v9 https://jsfiddle.net/n4Lyvo8d/
