### ISSUE TITLE
[9.0.0] Dataset isn't restored after undoing column removal on these column

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8113]
### Description
After removing a column, empty one is restored by undo.

Reported by @Siemienik 

### Steps to reproduce

1. Remove column by contextMenu
2. Undo

### Actual result 
v9.0.0 https://jsfiddle.net/aninde/bht8mg1n/
The restored column is empty.
![Kapture 2021-05-26 at 16 03 22](https://user-images.githubusercontent.com/30186818/119673798-f3595d00-be3b-11eb-9114-e79537fbf4cd.gif)

### Expected result 
v8.4.0 (https://jsfiddle.net/aninde/7ykejtq8/)
The restored column has an unchanged dataset.
<img width="352" alt="Screenshot 2021-05-26 at 16 04 49" src="https://user-images.githubusercontent.com/30186818/119674042-2a2f7300-be3c-11eb-8983-5f830698eee3.png">

### Demo

https://jsfiddle.net/aninde/df74yreb/ v8.4.0 (works)

### Your environment
* Handsontable version: 9.0.0
* Browser Name and version: Chrome 90
* Operating System: macOS 11.2.3 (20D91)

**Comment by jansiegel** [comment]
@aninde I think you forgot to fill the issue details.

**Comment by aninde** [comment]
@jansiegel  the description is ready :) sorry for the delay.

**Comment by AMBudnik** [comment]
Do we have the same issue here https://github.com/handsontable/handsontable/issues/8076 ?

**Comment by aninde** [comment]
@AMBudnik true.
I'm closing this issue because it's a duplicate of https://github.com/handsontable/handsontable/issues/8076.

**Comment by AMBudnik** [comment]
Issue is fixed with https://github.com/handsontable/handsontable/issues/8076 for v9
(RN https://github.com/handsontable/handsontable/releases/tag/9.0.0)
