### ISSUE TITLE
[9.0.0] We cannot add a new row or a new column to the end of the table

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8121]
### Description
Related to https://github.com/handsontable/handsontable/issues/8109 and maybe to https://github.com/handsontable/handsontable/issues/8112.
Reported by @wszymanski

It looks like there is some block to increase the number of rows and cells.
Inserting columns or rows to the right or bottom end of the table doesn't work when formulas are enabled.
![insert](https://user-images.githubusercontent.com/30186818/119823368-03814300-bef5-11eb-916a-e7bb55d21b38.gif)

### Case 1
Adding a new row on the current last row from contextMenu
https://jsfiddle.net/aninde/g4pnfjeu/ v9.0.0  (broken)
https://jsfiddle.net/aninde/4wmjagop/ v8.4.2 (fixed)

### Case 2
Adding a column to the right from contextMenu or dropdownMenu 
https://jsfiddle.net/aninde/g4pnfjeu/ v9.0.0  (broken)
https://jsfiddle.net/aninde/d6pcmh2u/ v8.4.2 (fixed)
![insert-dropdown](https://user-images.githubusercontent.com/30186818/119824958-bef6a700-bef6-11eb-8540-3cefd512c362.gif)

### Case 3 
Inserting by alter don't work either
https://jsfiddle.net/aninde/3ycfbgkt/ v9.0.0 (broken)
https://jsfiddle.net/aninde/w4gadbj6/ v8.4.0 (fixed)

**Actual result**
<img width="197" alt="Screenshot 2021-05-27 at 14 36 58" src="https://user-images.githubusercontent.com/30186818/119827088-09792300-bef9-11eb-88b1-adf29c97ea3a.png">

**Expected result**
![Screenshot 2021-05-27 at 14 36 03](https://user-images.githubusercontent.com/30186818/119827002-f0707200-bef8-11eb-9b61-04cffebe65f9.png)

### Case 4 
Reported by @AMBudnik 
Undo after setDataAtCell
`beforeChange` and `afterChange` returns null when they shoudn't
https://jsfiddle.net/aninde/o9nber12/ v9.0.0 (broken)
https://jsfiddle.net/aninde/v8cdopku/ v8.4.0 (fixed)

**Actual result**
![Screenshot 2021-05-27 at 14 38 45](https://user-images.githubusercontent.com/30186818/119827437-6c6aba00-bef9-11eb-8981-c54f8fa8418d.png)

**Expected result**
![Screenshot 2021-05-27 at 14 39 42](https://user-images.githubusercontent.com/30186818/119827460-71c80480-bef9-11eb-9495-0e79fb15f7fa.png)

### Demo

Case 1 & 2
https://jsfiddle.net/aninde/g4pnfjeu/ v9.0.0  (broken)
https://jsfiddle.net/aninde/4wmjagop/ v8.4.2 (fixed)

Case 3
https://jsfiddle.net/aninde/3ycfbgkt/ v9.0.0 (broken)
https://jsfiddle.net/aninde/w4gadbj6/ v8.4.0 (fixed)
Case 4
https://jsfiddle.net/aninde/o9nber12/ v9.0.0 (broken)
https://jsfiddle.net/aninde/v8cdopku/ v8.4.0 (fixed)

### Your environment
* Handsontable version: 9.0.0
* Browser Name and version: Chrome 90
* Operating System: not releted

**Comment by jansiegel** [comment]
Should be fixed with #8109.

**Comment by aninde** [comment]
This bug was reported during the testing of the release candidate of v9.0.0. 
All cases are fixed on the currently released v9.0.0. 

Casev 1, 2,  https://jsfiddle.net/aninde/dpj7L608/ v9.0.0

![Screenshot 2021-06-01 at 14 41 50](https://user-images.githubusercontent.com/30186818/120326581-2b074f80-c2e9-11eb-9e73-c09a6c722d9a.png)

Case 4 https://jsfiddle.net/aninde/th89xkw3/ v9.0.0

![Screenshot 2021-06-01 at 14 42 32](https://user-images.githubusercontent.com/30186818/120326572-28a4f580-c2e9-11eb-9d6f-63c4d81ac056.png)

I'm closing #8121 as done and fixed.
