### ISSUE TITLE
New docs: undefined "last update" date

### ISSUE THREAD

**Issue by Osky772** [handsontable/handsontable#8128]
Go to any page in the new docs: https://dev.handsontable.com/docs/next/api/

At the bottom, there is the wrong date format.
This "Date" string shows whenever `$page.lastUpdated` is `undefined` in:
https://github.com/handsontable/handsontable/blob/50245d43ee5190bf1bc93e957de0b102ecde4ce3/docs/.vuepress/config.js#L94

Actual behaviour:
![Screenshot 2021-05-28 at 15 20 54](https://user-images.githubusercontent.com/33433795/119990165-4d872900-bfc8-11eb-93dd-8e1da2f7f851.png)

**Comment by Siemienik** [comment]
done in #8172
