### ISSUE TITLE
Binding data not shown

### ISSUE THREAD

**Issue by Nighteye841228** [handsontable/handsontable#8131]
### Description

when I use
```
mounted: function () {
    this.bindingData = [
      { id: 1, title: "wow", book: "gello?", test: "wellwellwell" },
      { id: 1, title: "wow", book: "gello?", test: "wellwellwell" },
      { id: 1, title: "wow", book: "gello?", test: "wellwellwell" },
      { id: 1, title: "wow", book: "gello?", test: "wellwellwell" },
      { id: 1, title: "wow", book: "gello?", test: "wellwellwell" },
      { id: 1, title: "wow", book: "gello?", test: "wellwellwell" },
    ];
}
```
the data won't show in the sheet but using `created()` it will.
my component is set like:
```
<hot-table
          :data="bindingData"
          :rowHeaders="true"
          width="100%"
          height="600"
          :autoRowSize="true"
          :colHeaders="true"
          :manualRowResize="true"
          :manualColumnResize="true"
>
</hot-table>
```

### Your environment
* Vue wrapper version: vue-cli
* Handsontable version: latest
* Browser Name and version: firefox 88.0.1
* Operating System: macOS 10.14 mojave

**Comment by AMBudnik** [comment]
Hi @Nighteye841228 

here's a corresponding subject that I've opened https://github.com/handsontable/docs/issues/158 
We are working on the new docs and will add missing examples soon

**Comment by Nighteye841228** [comment]
thanks for help! 
Actually, I want to mount some data gotten from API.
These data are really created after handsontable exist...
So adding `$nextTick` is one solution so far...?

**Comment by AMBudnik** [comment]
Yes, @Nighteye841228 if you want to use the `mounted` hook you need to add `nextTick`
