### ISSUE TITLE
Double validator call issue

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8138]
### Description

When the Formulas plugin is enabled the `validator` function (and validation hooks) are triggered twice for the changed values. No matter if it was triggered from API or UI. Additionally, I've found that validation is not triggered when the Formulas plugin works in linked workbook mode. Changing the value in the first instance does not update the validity state in the second instance.

### Steps to reproduce

1. Go to https://jsfiddle.net/budnix/tq1jck3v/;
2. Change the value of the cell B1 to `10`;
3. The validator in both sheets is customized and always returns `false` (all changed and related cells should be marked as red). The first sheet works but its validator function is called twice and the second sheet is not updated at all - in context of the validity state.

### Demo

https://jsfiddle.net/budnix/tq1jck3v/

### Your environment
* Handsontable version: 9.0.0
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
Works as expected with v9.0.1 https://jsfiddle.net/aninde/0cabLuyr/.
