### ISSUE TITLE
Remove non used dependencies

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8140]
### Description

Since the _ObservedChanges_ plugin has been removed recently there are still some artifacts in the source code that should be removed. The `jsonpatch` internal lib is no longer used and can be safely removed. Probably the dependency list on docs should also be updated.

### Your environment
* Handsontable version: 9.0.0
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
Done in v9.0.1
