### ISSUE TITLE
[8.4.0] VUE - using alter() for adding rows adds too many rows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8148]
### Description

Adding a new adds additional row at the bottom of the table. This issue does not occur in Angular or React wrappers, nor in the Vanilla version.

Calling `alter()` works the same as the context menu https://jsfiddle.net/7qm4rbxL/ 

### Steps to reproduce

1. Add a new row via context menu for the 2nd row

**Result**
You get two new rows added (one at the bottom of the table).

### Demo

https://jsfiddle.net/m826w9b7/ 9.0.0 - still broken
https://jsfiddle.net/n2qsh4fx/1/ 8.4.0 - broken
https://jsfiddle.net/1naqwrLz/2/ 8.3.2 - works well

### Your environment
* Vue wrapper version: 8.4.0
* Handsontable version: 8.4.0
* Browser Name and version: Chrome 90
* Operating System: Windows 10

_Inform Zen 26478_

**Comment by aninde** [comment]
This issue will be fixed by the v9.0.2 https://jsfiddle.net/8cekL23w/

**Comment by swistach** [comment]
I'm happy to announce we just released v9.0.2 with the fix to this bug.
