### ISSUE TITLE
Fixing formatting bugs in the new docs

### ISSUE THREAD

**Issue by Osky772** [handsontable/handsontable#8149]
### Description
This issue has been created to track all found styling bugs in the new docs.

- [x] the button HTML is outside the HTML tree (?) weird (see screen recording below)

https://user-images.githubusercontent.com/33433795/120995920-2a0d6c80-c786-11eb-8c54-618d30637d3c.mov

- [x] The HOT preview should have more height. I think that ideally, the preview tab should adjust the height depends on the HOT demo with the max height set to e.g. 320px.

![Screenshot 2021-06-07 at 12 07 16](https://user-images.githubusercontent.com/33433795/120998995-e8ca8c00-c788-11eb-98d4-0d96f282c729.png)

- [x] on the first view of the Preview tab the HOT is not rendered properly

![Screenshot 2021-06-07 at 12 09 54](https://user-images.githubusercontent.com/33433795/120999318-46f76f00-c789-11eb-98c6-493574ac6feb.png)

- [x] [Clipboard demo](https://dev.handsontable.com/docs/next/basic-clipboard/#trigger-copy-cut-programmatically)
buttons are sticked to the grid

<img width="653" alt="clipboard" src="https://user-images.githubusercontent.com/33433795/121877890-66ebdd00-cd0b-11eb-96d3-d9b014c47c35.png">

- [x] [Export to CSV demo](https://dev.handsontable.com/docs/next/export-to-csv/#overview)
examples have buttons sticked to the grid
<img width="679" alt="export-to-csv" src="https://user-images.githubusercontent.com/33433795/121878143-aa464b80-cd0b-11eb-8ce3-b9b439f5af94.png">

- [x] [Internationalization (i18n)demo](https://dev.handsontable.com/docs/next/internationalization-i18n/#demo)
First we write about `da-DK` a then we display `pl-PL` in the demo. Display `da-DK` in the demo to stay consistent with the content.
<img width="671" alt="Internationalization-i18n" src="https://user-images.githubusercontent.com/33433795/121880873-d0b9b600-cd0e-11eb-93a4-612823c4e154.png">

- [x] [Row parent-child demo](https://dev.handsontable.com/docs/next/row-parent-child/#preparing-the-data-source)
Unwanted blank space under the grid
<img width="647" alt="row-parent-child" src="https://user-images.githubusercontent.com/33433795/121881128-1d9d8c80-cd0f-11eb-8b48-b0d5c3778b0c.png">

- [x] [Saving data demo](https://dev.handsontable.com/docs/next/saving-data/#saving-changes-using-a-callback)
Buttons are sticked to the grid, too close to the demo either.

![image](https://user-images.githubusercontent.com/30186818/121875247-87666800-cd08-11eb-85ee-8463cbc3a821.png)

- [x] [Column filter- custom filter demo](https://dev.handsontable.com/docs/next/column-filter/#custom-filter-menu)
- [x] [Filter as you type demo](https://dev.handsontable.com/docs/next/column-filter/#filter-as-you-type)
 
Grid overlaps both demos area 

![image](https://user-images.githubusercontent.com/30186818/121878999-a535cc00-cd0c-11eb-885a-23ba85f9e314.png)

- [x] [Demo in manual resizing](https://dev.handsontable.com/docs/next/grid-size/#manual-resizing)

Button for expanding/collapsing is sticked to the grid

![image](https://user-images.githubusercontent.com/30186818/121879368-0c538080-cd0d-11eb-8a03-cbd09707927b.png)

- [x] [Plugins](https://dev.handsontable.com/docs/next/plugins/) - we miss the “table of contents” on the right hand side here. 
- [x]  Turning  “[internal plugin](https://dev.handsontable.com/docs/next/plugins/#internal-plugin)” and “external plugin” into headers

<img width="1436" alt="Screenshot 2021-06-14 at 12 39 33" src="https://user-images.githubusercontent.com/30186818/121879853-98fe3e80-cd0d-11eb-952e-adb30a585aa7.png">

- [x] [Performance](https://dev.handsontable.com/docs/next/performance/#turn-off-autorowsize-and-or-autocolumnsize)
 part of the content is unintentionally wrapped with the info box

![image](https://user-images.githubusercontent.com/30186818/121880241-11fd9600-cd0e-11eb-823d-3c131762abd2.png)

**Comment by Osky772** [comment]
>  on the first view of the Preview tab the HOT is not rendered properly

is fixed already

**Comment by Siemienik** [comment]
>  The HOT preview should have more height. I think that ideally, the preview tab should adjust the height depends on the HOT demo with the max height set to e.g. 320px.

I could not reproduce the same view as on the attached screenshot. It was fixed. I guess.

**Comment by Siemienik** [comment]
> Grid overlaps both demos area

It works for me
