### ISSUE TITLE
New Docs: Redirect /using-callbacks to /events-and-hooks

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8153]
As we renamed the page `Using Callbacks` to `Events and Hooks`, it is required to add a redirection to maintain traffic incoming into the old URL.

**Comment by budnix** [comment]
Done.

https://dev.handsontable.com/docs/next/tutorial-using-callbacks.html -> https://dev.handsontable.com/docs/next/events-and-hooks/
