### ISSUE TITLE
New docs: Broken demos on Column filter page

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8155]
### Description
All 3 demos from the Column filter page needs adjustments.

- [ ] 1. [Demo Basic configuration](https://dev.handsontable.com/docs/next/column-filter/#basic-configuration)  doesn't works, dropdown doesn't opens menu 
- [ ] 2. [Demo custom filter](https://dev.handsontable.com/docs/next/column-filter/#custom-filter-menu) dropdown doesn't work either , buttons class `changeType` looks odd, its very big and blue, like btn `submit` to jsfiffle 
- [ ] 3. [Demo Filter as you type](https://dev.handsontable.com/docs/next/column-filter/#filter-as-you-type), error on input

**Comment by Siemienik** [comment]
@budnix could I close it?
