### ISSUE TITLE
New docs: JSFiddle throws an error after opening an editor

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8159]
On the old docs page at https://handsontable.com/docs/8.4.0/frameworks-wrapper-for-angular-custom-editor-example.html as well as at http://localhost:8080/docs/next/angular-custom-editor-example/ the demo doesn't work when run in JSFiddle.

**Comment by Siemienik** [comment]
I've tried to fix this bug. After a short research, I think it is a bug on the jsfiddle side.

As you suggested at the meeting, I implement a mechanism to remove the edit button for broken on jsfiddle examples.
PR: #8174

I will not close this issue. However the problem will be hidden, so I move this into a backlog.

**Comment by Siemienik** [comment]
@budnix could it be close?

**Comment by budnix** [comment]
> @budnix could it be closed?

Sure!
