### ISSUE TITLE
New docs: problem with param in the License Key configuration

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8160]
As following the License Key page, this code should be correct: ` <hot-table :data="hotData" licenseKey="non-commercial-and-evaluation">`. However it isn't.

I have to use  :settings with license key defined: `  <hot-table :data="hotData" :settings="settings">`

So, we provide the wrong information on the page about the license OR something went wrong with param `licenseKey`.

**Comment by budnix** [comment]
I've checked all wrappers and Vue2, React, and Angular supports the syntax mentioned in the documentation.
