### ISSUE TITLE
New docs: Fix "undefined" values

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8162]
Fix "undefined" values (spare quotes) as defined in column G in this file shared on Slack by @wojciech: https://handsoncode.slack.com/files/U93RD5PCJ/F021NBKTNKA/options-may-5-2021.xlsx

**Comment by Siemienik** [comment]
Blocked by: #8191 #8188

**Comment by Siemienik** [comment]
done in #b364b9c
