### ISSUE TITLE
Vue wrapper throws errors on route change

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8165]
Vue wrapper throws errors on route change. This can be spotted in the new docs. Enter any page with the Vue demo and exit to another page outside the Vue category. See the console for the error being thrown.

Go to https://dev.handsontable.com/docs/next/vue-simple-example/
Exit to https://dev.handsontable.com/docs/next/

**Comment by jansiegel** [comment]
This looks like an issue with the new docs.

I think when changing the page, the Handsontable instance is being destroyed, but the Vue component of the wrapper isn't. Could someone confirm? @Siemienik

**Comment by Siemienik** [comment]
> I think when changing the page, the Handsontable instance is being destroyed, but the Vue component of the wrapper isn't.

That's right, however similar errors doesn't happen in anothers wrapper. That why we want's to handle it from the wrapper level.

When the HOT instance being to be destroyed, the Vue component should react to that event.

**Comment by jansiegel** [comment]
@Siemienik There may be no errors on the other wrappers, but they leave zombie components behind on each page change. 

For example, this is the app state after visiting the React example a couple of times:
<img src="https://user-images.githubusercontent.com/7397134/122414660-9870dc80-cf87-11eb-89df-7008d296d774.png" height=140/>

Generally, I think it'd be better to destroy the components and not rely on their internal logic to do the cleanup, but I guess we could make this work the other way as well.

cc @wojciechczerniak

**Comment by jansiegel** [comment]
@Siemienik There may be no errors on the other wrappers, but it looks like they leave zombie components behind on each page change. 

For example, this is the app state after visiting the React example a couple of times:
<img src="https://user-images.githubusercontent.com/7397134/122414660-9870dc80-cf87-11eb-89df-7008d296d774.png" height=140/>

Generally, I think it'd be better to destroy the components and not rely on their internal logic to do the cleanup, but I guess we could make this work the other way as well (if it's possible? Can a react component unmount itself? That doesn't seem like a good practice.)

cc @wojciechczerniak

**Comment by wojciechczerniak** [comment]
From what you say fixing this will only mask the problem at hand, there is a memory leak in docs application. Destroying Handsontable instances on page change in PWA was created for examples build in Vanilla JS. In frameworks, developer should use framework features to manage component lifecycle. Destroying Handsontable inside a component that still uses it is the best way to have many more errors thrown in the console.

IMO We should change the error being thrown to something more meaningful, and add it to all three wrappers.

**Comment by jansiegel** [comment]
> From what you say fixing this will only mask the problem at hand, there is a memory leak in docs application. Destroying Handsontable instances on page change in PWA was created for examples build in Vanilla JS. In frameworks, developer should use framework features to manage component lifecycle. Destroying Handsontable inside a component that still uses it is the best way to have many more errors thrown in the console.
> 
> IMO We should change the error being thrown to something more meaningful, and add it to all three wrappers.

☝️ this

**Comment by Siemienik** [comment]
@wojciechczerniak ok, that makes sense 👏 

Assumes, todo:
1. [ ] "We should change the error being thrown to something more meaningful, and add it to all three wrappers."
2. [ ] Docs application should better handle previewed examples lifecycle

**Comment by budnix** [comment]
I can confirm that the issue is about how the docs handle the `hot` instances. For wrappers (Vue, React, Angular) the code calls the `destroy` method of the internal instance. That creates a memory leak in the context of the framework (the listeners are still there etc.). 

I am currently working on this problem.
