### ISSUE TITLE
New docs: Fixing broken links

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8168]
### Description

Some links were reported as incorrect from the broken link checker and should be fixed.

**Comment by Siemienik** [comment]
Actual broken links report generated by logic added in #8212 
[report-check-links.xlsx](https://github.com/handsontable/handsontable/files/6650136/report-check-links.xlsx)

**Comment by Siemienik** [comment]
* [ ] http://127.0.0.1:8088/docs/next/api/auto-column-size/
    * [ ] `/docs/next/api/GhostTable/` resolved as: `http://127.0.0.1:8088/docs/next/api/GhostTable/`
    * [ ] `/docs/next/api/SamplesGenerator/` resolved as: `http://127.0.0.1:8088/docs/next/api/SamplesGenerator/`
* [ ] http://127.0.0.1:8088/docs/next/api/hooks/
    * [ ] `/docs/next/api/AutoColumnSize/` resolved as: `http://127.0.0.1:8088/docs/next/api/AutoColumnSize/`
    * [ ] `/docs/next/api/SampleGenerator/` resolved as: `http://127.0.0.1:8088/docs/next/api/SampleGenerator/`
    * [ ] `/docs/next/api/UndoRedo/` resolved as: `http://127.0.0.1:8088/docs/next/api/UndoRedo/`
* [ ] http://127.0.0.1:8088/docs/next/api/index-mapper/
    * [ ] `/docs/next/api/DataMap/` resolved as: `http://127.0.0.1:8088/docs/next/api/DataMap/`
    * [ ] `/docs/next/api/to/` resolved as: `http://127.0.0.1:8088/docs/next/api/to/`
* [ ] http://127.0.0.1:8088/docs/next/api/options/
    * [ ] `/docs/next/api/AutoColumnSize/` resolved as: `http://127.0.0.1:8088/docs/next/api/AutoColumnSize/`
    * [ ] `/docs/next/api/DragToScroll/` resolved as: `http://127.0.0.1:8088/docs/next/api/DragToScroll/`
    * [ ] `/docs/next/api/plugin-hooks/` resolved as: `http://127.0.0.1:8088/docs/next/api/plugin-hooks/`
* [ ] http://127.0.0.1:8088/docs/next/api/plugins/
    * [ ] `https://dev.handsontable.com/docs/next/api/header-tooltips/` resolved as: `https://dev.handsontable.com/docs/next/api/header-tooltips/`
    * [ ] `https://dev.handsontable.com/docs/next/api/observe-changes/` resolved as: `https://dev.handsontable.com/docs/next/api/observe-changes/`
    * [ ] `https://dev.handsontable.com/docs/next/api/touch-scroll/` resolved as: `https://dev.handsontable.com/docs/next/api/touch-scroll/`
* [ ] http://127.0.0.1:8088/docs/next/autocomplete-cell-type/
    * [ ] `/docs/next/guides/cell-types/handsontable-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/handsontable-cell-type.html`
* [ ] http://127.0.0.1:8088/docs/next/basic-clipboard/
    * [ ] `/docs/next/guides/cell-features/api/core.html#isListening` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-features/api/core.html#isListening`
    * [ ] `/docs/next/guides/cell-features/api/pluginHooks.html#aftercopy` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-features/api/pluginHooks.html#aftercopy`
    * [ ] `/docs/next/guides/cell-features/api/pluginHooks.html#aftercut` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-features/api/pluginHooks.html#aftercut`
    * [ ] `/docs/next/guides/cell-features/api/pluginHooks.html#afterpaste` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-features/api/pluginHooks.html#afterpaste`
    * [ ] `/docs/next/guides/cell-features/api/pluginHooks.html#beforecopy` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-features/api/pluginHooks.html#beforecopy`
    * [ ] `/docs/next/guides/cell-features/api/pluginHooks.html#beforecut` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-features/api/pluginHooks.html#beforecut`
    * [ ] `/docs/next/guides/cell-features/api/pluginHooks.html#beforepaste` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-features/api/pluginHooks.html#beforepaste`
    * [ ] `/docs/next/guides/context-menu.html#page-custom` resolved as: `http://127.0.0.1:8088/docs/next/guides/context-menu.html#page-custom`
* [ ] http://127.0.0.1:8088/docs/next/building/
    * [ ] `/docs/next/guides/building-and-testing/internationalization.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/building-and-testing/internationalization.html`
* [ ] http://127.0.0.1:8088/docs/next/cell-editor/
    * [ ] `/docs/next/guides/cell-functions/setting-options.html#page-config` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-functions/setting-options.html#page-config`
* [ ] http://127.0.0.1:8088/docs/next/cell-function/
    * [ ] `/docs/next/guides/cell-functions/cell-editor.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-functions/cell-editor.html`
    * [ ] `/docs/next/guides/cell-types/cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/cell-type.html`
* [ ] http://127.0.0.1:8088/docs/next/cell-renderer/
    * [ ] `/docs/next/guides/getting-started/using-callbacks.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/getting-started/using-callbacks.html`
* [ ] http://127.0.0.1:8088/docs/next/cell-type/
    * [ ] `/docs/next/guides/cell-types/autocomplete-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/autocomplete-cell-type.html`
    * [ ] `/docs/next/guides/cell-types/checkbox-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/checkbox-cell-type.html`
    * [ ] `/docs/next/guides/cell-types/date-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/date-cell-type.html`
    * [ ] `/docs/next/guides/cell-types/dropdown-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/dropdown-cell-type.html`
    * [ ] `/docs/next/guides/cell-types/handsontable-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/handsontable-cell-type.html`
    * [ ] `/docs/next/guides/cell-types/numeric-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/numeric-cell-type.html`
    * [ ] `/docs/next/guides/cell-types/password-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/password-cell-type.html`
    * [ ] `/docs/next/guides/cell-types/select-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/select-cell-type.html`
    * [ ] `/docs/next/guides/cell-types/setting-options.html#page-config` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/setting-options.html#page-config`
    * [ ] `/docs/next/guides/cell-types/time-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/time-cell-type.html`
* [ ] http://127.0.0.1:8088/docs/next/column-filter/
    * [ ] `/docs/next/guides/columns/dropdown-menu.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/columns/dropdown-menu.html`
* [ ] http://127.0.0.1:8088/docs/next/column-hiding/
    * [ ] `/docs/next/guides/columns/context-menu.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/columns/context-menu.html`
* [ ] http://127.0.0.1:8088/docs/next/column-menu/
    * [ ] `/docs/next/guides/columns/context-menu.html#page-specific` resolved as: `http://127.0.0.1:8088/docs/next/guides/columns/context-menu.html#page-specific`
* [ ] http://127.0.0.1:8088/docs/next/comments/
    * [ ] `/docs/next/guides/cell-features/context-menu.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-features/context-menu.html`
* [ ] http://127.0.0.1:8088/docs/next/context-menu/
    * [ ] `/docs/next/guides/accessories-and-menus/api/plugins/comments/comments.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/accessories-and-menus/api/plugins/comments/comments.html`
    * [ ] `/docs/next/guides/accessories-and-menus/api/plugins/copyPaste/copyPaste.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/accessories-and-menus/api/plugins/copyPaste/copyPaste.html`
    * [ ] `/docs/next/guides/accessories-and-menus/api/plugins/customBorders/customBorders.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/accessories-and-menus/api/plugins/customBorders/customBorders.html`
    * [ ] `/docs/next/guides/accessories-and-menus/api/plugins/filters/filters.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/accessories-and-menus/api/plugins/filters/filters.html`
    * [ ] `/docs/next/guides/accessories-and-menus/api/plugins/hiddenColumns/hiddenColumns.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/accessories-and-menus/api/plugins/hiddenColumns/hiddenColumns.html`
    * [ ] `/docs/next/guides/accessories-and-menus/api/plugins/hiddenRows/hiddenRows.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/accessories-and-menus/api/plugins/hiddenRows/hiddenRows.html`
    * [ ] `/docs/next/guides/accessories-and-menus/api/plugins/manualColumnFreeze/manualColumnFreeze.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/accessories-and-menus/api/plugins/manualColumnFreeze/manualColumnFreeze.html`
    * [ ] `/docs/next/guides/accessories-and-menus/api/plugins/mergeCells/mergeCells.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/accessories-and-menus/api/plugins/mergeCells/mergeCells.html`
    * [ ] `/docs/next/guides/accessories-and-menus/api/plugins/nestedRows/nestedRows.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/accessories-and-menus/api/plugins/nestedRows/nestedRows.html`
    * [ ] `/docs/next/guides/accessories-and-menus/api/plugins/undoRedo/undoRedo.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/accessories-and-menus/api/plugins/undoRedo/undoRedo.html`
* [ ] http://127.0.0.1:8088/docs/next/dropdown-cell-type/
    * [ ] `/docs/next/guides/cell-types/autocomplete-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/autocomplete-cell-type.html`
* [ ] http://127.0.0.1:8088/docs/next/internationalization-i18n/
    * [ ] `/docs/next/guides/internationalization/contributing.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/internationalization/contributing.html`
* [ ] http://127.0.0.1:8088/docs/next/performance/
    * [ ] `/docs/next/guides/advanced-topics/api/dataMap/metaManager/metaSchema.html#autocolumnsize` resolved as: `http://127.0.0.1:8088/docs/next/guides/advanced-topics/api/dataMap/metaManager/metaSchema.html#autocolumnsize`
    * [ ] `/docs/next/guides/advanced-topics/api/dataMap/metaManager/metaSchema.html#autorowsize` resolved as: `http://127.0.0.1:8088/docs/next/guides/advanced-topics/api/dataMap/metaManager/metaSchema.html#autorowsize`
    * [ ] `/docs/next/guides/advanced-topics/api/dataMap/metaManager/metaSchema.html#colwidths` resolved as: `http://127.0.0.1:8088/docs/next/guides/advanced-topics/api/dataMap/metaManager/metaSchema.html#colwidths`
    * [ ] `/docs/next/guides/advanced-topics/api/dataMap/metaManager/metaSchema.html#viewportcolumnrenderingoffset` resolved as: `http://127.0.0.1:8088/docs/next/guides/advanced-topics/api/dataMap/metaManager/metaSchema.html#viewportcolumnrenderingoffset`
    * [ ] `/docs/next/guides/advanced-topics/api/dataMap/metaManager/metaSchema.html#viewportrowrenderingoffset` resolved as: `http://127.0.0.1:8088/docs/next/guides/advanced-topics/api/dataMap/metaManager/metaSchema.html#viewportrowrenderingoffset`
    * [ ] `/docs/next/guides/advanced-topics/modules.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/advanced-topics/modules.html`
    * [ ] `suspend-rendering.mdx` resolved as: `http://127.0.0.1:8088/docs/next/performance/suspend-rendering.mdx`
* [ ] http://127.0.0.1:8088/docs/next/row-hiding/
    * [ ] `/docs/next/guides/rows/context-menu.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/context-menu.html`
* [ ] http://127.0.0.1:8088/docs/next/row-moving/
    * [ ] `/docs/next/guides/rows/api/pluginHooks.html#afterrowmove` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/pluginHooks.html#afterrowmove`
    * [ ] `/docs/next/guides/rows/api/pluginHooks.html#beforerowmove` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/pluginHooks.html#beforerowmove`
    * [ ] `/docs/next/guides/rows/api/plugins/manualRowMove/manualRowMove.html#dragrows` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/plugins/manualRowMove/manualRowMove.html#dragrows`
    * [ ] `/docs/next/guides/rows/api/plugins/manualRowMove/manualRowMove.html#ismovepossible` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/plugins/manualRowMove/manualRowMove.html#ismovepossible`
    * [ ] `/docs/next/guides/rows/api/plugins/manualRowMove/manualRowMove.html#moverows` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/plugins/manualRowMove/manualRowMove.html#moverows`
* [ ] http://127.0.0.1:8088/docs/next/row-sorting/
    * [ ] `/docs/next/guides/rows/api/dataMap/metaManager/metaSchema.html#columns` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/dataMap/metaManager/metaSchema.html#columns`
    * [ ] `/docs/next/guides/rows/api/pluginHooks.html#aftercolumnsort` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/pluginHooks.html#aftercolumnsort`
    * [ ] `/docs/next/guides/rows/api/pluginHooks.html#beforecolumnsort` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/pluginHooks.html#beforecolumnsort`
    * [ ] `/docs/next/guides/rows/api/plugins/columnSorting/columnSorting.html#clearsort` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/plugins/columnSorting/columnSorting.html#clearsort`
    * [ ] `/docs/next/guides/rows/api/plugins/columnSorting/columnSorting.html#getsortconfig` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/plugins/columnSorting/columnSorting.html#getsortconfig`
    * [ ] `/docs/next/guides/rows/api/plugins/columnSorting/columnSorting.html#issorted` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/plugins/columnSorting/columnSorting.html#issorted`
    * [ ] `/docs/next/guides/rows/api/plugins/columnSorting/columnSorting.html#setsortconfig` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/plugins/columnSorting/columnSorting.html#setsortconfig`
    * [ ] `/docs/next/guides/rows/api/plugins/columnSorting/columnSorting.html#sort` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/plugins/columnSorting/columnSorting.html#sort`
    * [ ] `/docs/next/guides/rows/cell-types.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/cell-types.html`
* [ ] http://127.0.0.1:8088/docs/next/row-trimming/
    * [ ] `/docs/next/guides/rows/api/core.html#getData` resolved as: `http://127.0.0.1:8088/docs/next/guides/rows/api/core.html#getData`
* [ ] http://127.0.0.1:8088/docs/next/select-cell-type/
    * [ ] `/docs/next/guides/cell-types/dropdown-cell-type.html` resolved as: `http://127.0.0.1:8088/docs/next/guides/cell-types/dropdown-cell-type.html`

**Comment by Siemienik** [comment]
After 1st and 2nd iteration:

From | To
--- | ---
http://127.0.0.1:8088/docs/next/api/auto-column-size/ | /docs/next/api/GhostTable/
http://127.0.0.1:8088/docs/next/api/auto-column-size/ | /docs/next/api/GhostTable/
http://127.0.0.1:8088/docs/next/api/auto-column-size/ | /docs/next/api/SamplesGenerator/
http://127.0.0.1:8088/docs/next/api/auto-column-size/ | /docs/next/api/SamplesGenerator/
http://127.0.0.1:8088/docs/next/api/hooks/ | /docs/next/api/sample-generator/
http://127.0.0.1:8088/docs/next/api/Hooks/ | /docs/next/api/sample-generator/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/data-map/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/data-map/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/data-map/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/data-map/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/data-map/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/data-map/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/data-map/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/HidingMap/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/IndexesSequence/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/PhysicalIndexToValueMap/
http://127.0.0.1:8088/docs/next/api/index-mapper/ | /docs/next/api/TrimmingMap/
http://127.0.0.1:8088/docs/next/api/options/ | /docs/next/api/DragToScroll/
http://127.0.0.1:8088/docs/next/api/Options/ | /docs/next/api/DragToScroll/

**Comment by Siemienik** [comment]
Done in #8192
