### ISSUE TITLE
Validator issues

### ISSUE THREAD

**Issue by marcok** [handsontable/handsontable#818]
I have two issues with the new Validator:
1. Validator and autocomplete
   When I use Validator and autocomplete like
   {data: "producer", type: { editor:  Handsontable.AutocompleteEditor }, validator: hotValidators.notEmpty, allowInvalid: true },
   then new rows are not invalid, when producer is empty. The validator is called and returns false but cell stay white.
2. Type numeric and Ajax Load
   On numeric cols like
   {data: "addOutput1", type: 'numeric' },  
   After loading data from ajax (loadData) and data is is null for a cell then cell gets red althougt there is no not null validator (in fact there is no validator at all). When I enter cell (e.g. double click) and leave cell without changing anything it gets white.

JSON data from server looks like 
"outputs":[{"id":1885,"week":1,"output":0,"addOutput1":0,"addOutput2":0,"addOutput3":0,"addOutput4":0,"addOutput5":null,"addOutput6":null,"created":"2012.10.29 17:27:44","updated":"20

the issue is on addOutput5 and addOutput6. Is null wrong? Do I have to return someting else?

**Comment by felixhagspiel** [comment]
@marcok I need to know as well how we can change the default behaviour of the numeric validator. I also need it to allow '0'. Thanks

**Comment by marcok** [comment]
I created an own validator like:

```javascript
    	notNullNumericValidator: function (value, callback) {
    		if (!value || 0 === value.length){
    			callback(false);
    		}else{
    			if (Handsontable.helper.isNumeric(value)){
    				callback(true);
    			}else{
    				callback(false);
    			}
    		}
    	},
    	notNullZeroValidator: function (value, callback) {
    		if (!Handsontable.helper.isNumeric(value) || parseFloat(value) == 0) {
    			callback(false);
    		}else{
    			callback(true);
    		}
    	}
```

**Comment by felixhagspiel** [comment]
@marcok I also added an custom numeric validator, but the problem is that I also set `type: "numeric"` in the columns property of the table and then handsontable automatically sets it to invalid when its value is `0`. I set the numeric type because I need the exported data to be numbers and not strings. Do you know a solution for that?

**Comment by marcok** [comment]
Actually I dont understand your problem. I'm using:

**Comment by felixhagspiel** [comment]
@marcok sorry, it works, I just had a stupid mistake in my code. Thanks for your help!
