### ISSUE TITLE
[8.0.0] Parent row data is reverted when it's changed between row alteration [Urgent]

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8180]
### Description

Parent row data is reverted when it's changed between row alteration.

### Steps to reproduce

1. Right-click any parent row and click on `Insert Child Row`.
2. Enter any data on the same parent row.
3. Again right-click the same parent row and click on `Insert Child Row`.
4. Parent row data is reverted

**Result**
![bug](https://user-images.githubusercontent.com/10757813/121516785-e79a9880-c9ee-11eb-94c6-ea3d7be8c9d8.gif)

### Demo

https://jsfiddle.net/b6qy0h79/ 7.0.0 - works well
https://jsfiddle.net/b6qy0h79/2/ 8.0.0 - **first broken**
https://jsfiddle.net/Lg13seqo/ - 8.3.2 broken
https://jsfiddle.net/Lg13seqo/1/ - 9.0.0 broken

### Your environment
* Handsontable version: 8.0.0+
* Browser Name and version: Chrome 91
* Operating System: Windows 10

_Inform Zen 26480 p1.1._

**Comment by AMBudnik** [comment]
### Scenario 2 - required to work after fix

- Go to https://jsfiddle.net/4980emLp/ 
- Right-click the first parent row “Mix” and choose `Insert child row` from the context menu.
- Change Parent item name from “Mix” to “Mix NEW”.
- Right-click the same parent row “Mix NEW” and choose `Insert child row` from the context menu.

Result: The parent row changes from “Mix NEW” to “Mix”

![bug](https://user-images.githubusercontent.com/10757813/130026511-f1965dc7-62b0-4302-9208-85d0ee2c02d7.gif)

**Comment by AMBudnik** [comment]
Issues to check after the fix
* https://github.com/handsontable/handsontable/issues/7137 
* https://github.com/handsontable/handsontable/issues/7138

**Comment by wszymanski** [comment]
May be related to https://github.com/handsontable/handsontable/pull/6889.

**Comment by aninde** [comment]
This issue will be fixed by v10 https://jsfiddle.net/sj9cgfah/
Case 2 https://jsfiddle.net/w2arfv6s/

**Comment by AMBudnik** [comment]
True, works well for my Case 2 as well
https://jsfiddle.net/crvLbdpy/
![image](https://user-images.githubusercontent.com/10757813/135248326-c3631992-eb49-48d0-826f-efe65f223b1e.png)
