### ISSUE TITLE
Parents of nested rows are expanded when we add a row [Urgent]

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8181]
### Description

Parents of nested rows are expanded when we add a row.

### Steps to reproduce

1. Collapse `Best Metal Performance` and `Best Rock Song` parents
2. Use context menu to `Insert row above` on the row below the collapsed parents (`Best Rock`)

**Result**
Parents are expaded.
![issue](https://user-images.githubusercontent.com/10757813/121518139-6e03aa00-c9f0-11eb-9b61-6f1af8b052a6.gif)

### Demo

https://jsfiddle.net/e3051krc/ 9.0.0 - broken
https://jsfiddle.net/b6qy0h79/3/ 8.0.0 - broken
https://jsfiddle.net/e3051krc/1/ 7.4.2 - broken (it was adding a bug in the console)
https://jsfiddle.net/e3051krc/3/ 7.0.0 - broken (it was adding a bug in the console)

### Your environment
* Handsontable version: 9.0.0
_It doesn't seem to be a regression_
* Browser Name and version: Chrome 91
* Operating System: Windows 10

_Inform Zen 26480 p2._

**Comment by AMBudnik** [comment]
### Scenario 2 - required to work after fix

- Go to https://jsfiddle.net/4980emLp/ 
- Right Click “Lynchee Puree” and choose `Insert child row` from the context menu.
- Collapse “Lynchee Puree” 
- Right-click “Milk Curd” and choose `Insert row below` from the context menu.

Result: The collapsed “Lynchee Puree” expanded.

![bug2](https://user-images.githubusercontent.com/10757813/130031428-668ddc61-94ae-4e76-a752-e080d60ca2e6.gif)

**Comment by aninde** [comment]
This issue will be fixed by v10 https://jsfiddle.net/1pb2genm/.

**Comment by AMBudnik** [comment]
True!

Also works well for the second scenario (the parent does not expand itself)

![image](https://user-images.githubusercontent.com/10757813/135248740-9f05543f-4ccc-4d96-930f-69623772f66e.png)

https://jsfiddle.net/95pz6y0r/2/
