### ISSUE TITLE
New Docs: sync API Reference content with JSDOCs

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8191]
### Description
While I'm working on #8162 I point, that we have some manually changed content for API Reference pages.

File list: 
* [x] core.md
* [x] formulas.md
* [x] headerTooltips.md
* [x] indexMapper.md
* [x] metaSchema.md
* [x] multipleSelectionHandles.md
* [x] observeChanges.md
* [x] pluginHooks.md
* [x] touchScroll.md
* [x] undoRedo.md

**Comment by aninde** [comment]
`observeChanges.md` and  `headerTooltips.md` should be removed. Reported in the https://github.com/handsontable/handsontable/issues/8193

**Comment by Siemienik** [comment]
done in #8199
