### ISSUE TITLE
New docs: Pages that should generate

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8194]
### Description

Some pages that were probably generated from the code in the previous documentation are not generated in the new one.

It is difficult to list them because they cannot be accessed from the search engine on the documentation page. you can enter them in google which indexes some, or manually.

List of pages to be generated (WIP) :
Not sure about the api location @krzysztofspilka?
- [ ] https://dev.handsontable.com/docs/next/api/SamplesGenerator/
- [ ] https://dev.handsontable.com/docs/next/api/GhostTable/ 
- [ ] https://dev.handsontable.com/docs/next/api/DataMap/
- [ ] http://127.0.0.1:8080/docs/next/cell-editor/#selecting-proper-editor-for-an-active-cell - page about Cascading configuration is commented out in metaSchema.js file 

### Links

Old documentation:
https://handsontable.com/docs/9.0.0/SamplesGenerator.html
https://handsontable.com/docs/9.0.0/GhostTable.html
https://handsontable.com/docs/9.0.0/global.html
https://handsontable.com/docs/9.0.0/DataMap.html
https://handsontable.com/docs/9.0.0/tutorial-setting-options.html#page-config

**Comment by Siemienik** [comment]
As far as can I see while I checked it on the production server. We have 404 only for https://handsontable.com/docs/9.0/global


We have also broken links for:
http://127.0.0.1:8080/docs/next/cell-editor/#selecting-proper-editor-for-an-active-cell - page about Cascading configuration is commented out in metaSchema.js file

https://handsontable.com/docs/9.0.0/tutorial-setting-options.html#page-config

**Comment by Siemienik** [comment]
I have no idea how to generates the `global` page properly for now. I skip this issue until #8335.

**Comment by Siemienik** [comment]
followed by: https://github.com/handsontable/handsontable/issues/8335
