### ISSUE TITLE
New Docs: Improvement to the Hello World app

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8197]
### Description

@wszymanski can we make some changes as discussed on [Slack](https://handsoncode.slack.com/archives/C01KNSJ4M08/p1623411964015900)?

1. Let's gray out the Angular and Vue tabs. You can use color #CFDBE4
2. Let's use the light theme of the embedded iframe(s)
3. Please alter the content above the iframe as discussed and linked on [Slack](https://handsoncode.slack.com/archives/C01KNSJ4M08/p1623415052023600) together with @kirszenbaum 
4. Please adjust the font-family and font-size so they are the same as in our other demos
5. Please adjust the height of Handsontable inside the iframe so it doesn't produce double scrollbars

Connected with #8173

**Comment by aninde** [comment]
@wszymanski the demo needs some polishing.
1. dropdown menu doesn't close itself, although it should when I sort the table on Chrome 92.0.4515.51.

![dropdownmenu](https://user-images.githubusercontent.com/30186818/122227844-8f183f00-ceb7-11eb-9a72-8c35ad37a5d8.gif)

**Comment by wszymanski** [comment]
> @wszymanski the demo needs some polishing.
> 
> 1. dropdown menu doesn't close itself, although it should when I sort the table on Chrome 92.0.4515.51.
> 
> ![dropdownmenu](https://user-images.githubusercontent.com/30186818/122227844-8f183f00-ceb7-11eb-9a72-8c35ad37a5d8.gif)

Isn't it problem with Hansontable?

**Comment by aninde** [comment]
> > @wszymanski the demo needs some polishing.
> > 
> > 1. dropdown menu doesn't close itself, although it should when I sort the table on Chrome 92.0.4515.51.
> > 
> > ![dropdownmenu](https://user-images.githubusercontent.com/30186818/122227844-8f183f00-ceb7-11eb-9a72-8c35ad37a5d8.gif)
> 
> Isn't that a problem with Hansontable?

It is. Nested headers broke this. https://jsfiddle.net/aninde/cg0486hm/ Reported https://github.com/handsontable/handsontable/issues/8232.

**Comment by aninde** [comment]
2. Another adjustment: reducing the height of the Handsontable inside the CS because the bottom scrollbar is hiding 

![image](https://user-images.githubusercontent.com/30186818/122233120-17004800-cebc-11eb-94ed-4996828d1c6b.png)

**Comment by Siemienik** [comment]
@wszymanski is this issue done?

**Comment by wszymanski** [comment]
> @wszymanski is this issue done?

I think so, it's marked as done in project.
