### ISSUE TITLE
New Docs: Codesandbox makes the console red in Vue example

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8198]
Codesandbox makes the console red.

http://localhost:8080/docs/next/vue-hot-column/#a-more-advanced-example

**Comment by AMBudnik** [comment]
The following issue is not replicable using version 11
Updated link https://handsontable.com/docs/vue-hot-column/#a-more-advanced-example and demo https://jsfiddle.net/syg7f5on/
