### ISSUE TITLE
New docs: fix the title in Hooks

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8201]
### Description

This page at https://dev.handsontable.com/docs/next/api/hooks/ has the wrong title.

- **Now**: Hooks
- **Should be:** Hooks - API Reference - Handsontable Documentation

**Comment by budnix** [comment]
https://github.com/handsontable/handsontable/pull/8189 resolves that issue

**Comment by Siemienik** [comment]
Done in #8199
