### ISSUE TITLE
Prepare the Hello World App for the new docs (Vue 2)

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#8207]
We would like to present Handsontable in a business context to our early adopters. To do so, we'd need to create an exemplary demo of Handsontable for the new documentation. The requirements are put together by @krzysztofspilka in Google Sheets, and shared in the discussion on Slack: [link](https://handsoncode.slack.com/archives/C01KNSJ4M08/p1619429219004300)

**Checklist:**

- [x] Demo works smoothly with the provided data set
- [x] There are no performance issues
- [x] Available for Vue at CodeSandbox

**Comment by warpech** [comment]
Done in https://github.com/handsontable/handsontable/pull/8404
