### ISSUE TITLE
[2+, 8.4.0] Ticking a checkbox changes the width of the cell 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8211]
### Description
Ticking a checkbox changes the width of the cell. 
EDIT: This is an old case, probably since v2 or even before. 
Was fixed on v8.0.0-8.3.2.

**v2.0.0**
![2](https://user-images.githubusercontent.com/30186818/121912555-f8ba1100-cd30-11eb-9bc6-9f4a8b9ed88f.gif)

This case is looking better in RC-9.0.1, but but still not as good as before 8.4.0.

**v8.4.0 broken**
![Kapture 2021-06-14 at 15 56 00](https://user-images.githubusercontent.com/30186818/121904130-387cfa80-cd29-11eb-8f78-7fd0cd961f54.gif)

**v8.3.2 fixed** 
![8 3 2](https://user-images.githubusercontent.com/30186818/121905035-01f3af80-cd2a-11eb-8ba1-d7c818b844ae.gif)

**vRC-9.0.1 broken**
![901](https://user-images.githubusercontent.com/30186818/121905070-0ddf7180-cd2a-11eb-93ee-376553608d2a.gif)

### Steps to reproduce

1. Tick (check) checkbox in the A1 cell

### Demo

Simplest case https://jsfiddle.net/aninde/92z4013w/ v2.0.0 (broken)
Simplest case https://jsfiddle.net/1dayn9wc/ v8.4.0 (broken)
https://jsfiddle.net/aninde/zgtu1hwy/ v8.4.0 (broken)
https://jsfiddle.net/aninde/5sawmhex/ v8.3.2 (fixed)
https://jsfiddle.net/aninde/knsev9u8/ vRC-9.0.1 (broken, different then v8.4.0)

### Your environment
* Handsontable version: 2+
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
@swistach show possible workaround with usage of [modifyAutoColumnSizeSeed](https://handsontable.com/docs/9.0.0/Hooks.html#event:modifyAutoColumnSizeSeed).
https://jsfiddle.net/vqmfz831/.

**Comment by aninde** [comment]
This case needs e2e tests because it comes back to us as a regression, even though it was fixed in v8.0.0.

**Comment by aninde** [comment]
This issue is fixed by v12.0.1 https://jsfiddle.net/v2r5p98x/

**Comment by AMBudnik** [comment]
I hope that we got rid of this regression once and for all. 
For everyone interested in the latest patch that solved the issue here https://handsontable.com/docs/release-notes/ is the full list of changes.
