### ISSUE TITLE
contextMenu and hooks are not working along

### ISSUE THREAD

**Issue by bottas** [handsontable/handsontable#822]
I have used contextMenu with few options and callback in my sample and also tried to plug in a hook for afterChange event. When I have these two, contextMenu is not coming along. It is appearing only when the hook plugin funciton is not assigned. Is this a known issue, kindly investigate?

**Comment by AMBudnik** [comment]
I modified you demo a little cause it tried to download files from a local drive, it this [demo](https://jsfiddle.net/4e9dzxqg/) callbacks work with `contextMenu: ["about"]` like you described. Can you lead me to find what you are looking for? 
I'm workng on 0.14.1 - please update and leave us feedback.
