### ISSUE TITLE
Date/Time In cell

### ISSUE THREAD

**Issue by nyrd** [handsontable/handsontable#823]
Hey, 

Is there a way to add a date-time format to a cell? (As opposed to just basic Date) 

I would be looking for something along the lines of  : yy-mm-dd HH:MM:SS

I've been using "https://github.com/trentrichardson/jQuery-Timepicker-Addon" where I've needed it elsewhere, maybe some way to integrate this?

thanks

**Comment by JPPK** [comment]
Why was this closed? It's not like DateTime fields are a feature of great rarity or little utility. Writing custom renderers is hardly easy.

**Comment by AMBudnik** [comment]
@JPPK we are planning to add this type of cell in Handsontable PRO. Here's http://handsontable.com/coming-soon.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button where you can be up-to-date with our new features.

**Comment by JPPK** [comment]
Well, I've actually solved this issue as I described in https://github.com/handsontable/handsontable/issues/2698, but thanks for replying anyway!
