### ISSUE TITLE
Pikaday: wrong week numbers in datepicker

### ISSUE THREAD

**Issue by sb-thdata** [handsontable/handsontable#8237]
The week numbers in pikaday@1.8.0 are 1 off in 2021. This issue got fixed with pikaday@1.8.2
https://github.com/Pikaday/Pikaday/issues/878

Are there any plans to update the pikaday dependency to 1.8.2?

**Comment by AMBudnik** [comment]
Hi @sb-thdata 


That's true. It's been a while and we forgot about the update. Let me set the issue up as a `change` so we will have it officially reported and ready for change.

ps. we have one subject referenced here https://github.com/handsontable/handsontable/issues/7282

**Comment by AMBudnik** [comment]
Hi @sb-thdata 

We just launched Handsontable v12.1.0 and with that PR https://github.com/handsontable/handsontable/pull/9558 we pumped Pikaday to 1.8.2.

I'm closing this issue as solved. However, if you would find any issues please contact me at support@handsontable.com
