### ISSUE TITLE
`afterChange` doesn't return proper results if the action comes from an auto-filled formula

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8238]
### Description

`afterChange` doesn't return proper results if the action comes from an auto-filled formula.

The issue is not replicable in pre9 versions as autofill changed its behavior.

### Steps to reproduce

1. Autofill cell `B1` to `B2`
2. Check the console

![repro](https://user-images.githubusercontent.com/10757813/122386928-a5350680-cf6e-11eb-86a5-2bcf41d6f67e.gif)

**Expected result**
![image](https://user-images.githubusercontent.com/10757813/122386772-7f0f6680-cf6e-11eb-9f47-e0ca1f033da7.png)
(which we do get when we edit the same cell once again)

**Actual result**
![image](https://user-images.githubusercontent.com/10757813/122386640-5dae7a80-cf6e-11eb-8dad-27975362ed1c.png)

### Demo

https://jsfiddle.net/handsoncode/fo95mz4n/ 9.0.0 - broken

### Your environment
* Handsontable version: 9.0.0+
* Browser Name and version: Chrome 91
* Operating System: Windows 10

Inform [Forum](https://forum.handsontable.com/t/autofill-does-not-send-formula-to-onchange-handler/5291)

**Comment by ocordsen** [comment]
Hi,
do you maybe have an idea, if there might be a patch release soon which includes a fix for this bug? This might be a show stopper for us otherwise. :(

**Comment by ocordsen** [comment]
In case you didn't notice yet, `beforeChange` seems to have the same problem.

**Comment by AMBudnik** [comment]
True @ocordsen 

we should also take a look at the `getData` return in the `beforeChange` method.

**Comment by AMBudnik** [comment]
@ocordsen before v9 where we introduced the HyperFormula Autofill copied the value - not the formula so using an older version won't help.

But I will make sure to notifuy you once we fix this issue.

**Comment by AMBudnik** [comment]
Hi @ocordsen This issue is no longer replicable in the latest version of Handsontable - v12.4.0. Updated demo https://jsfiddle.net/o3au71qb/

I'm closing this issue as solved.
