### ISSUE TITLE
New docs: IE 11 support

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8257]
### Description

The current version of documentation from `feature/issue-7624` doesn't work on IE 11 on Windows 10 Pro.

![image](https://user-images.githubusercontent.com/30186818/122790068-3f22e900-d2b8-11eb-9004-7aa21f93c755.png)

![image](https://user-images.githubusercontent.com/30186818/122790086-434f0680-d2b8-11eb-8da9-27848fcaea60.png)

**Comment by budnix** [comment]
I've checked the issue and it's true that IE does not work on IE but only in the local (development) environment. On production build e.g. https://dev.handsontable.com/docs/binding-to-data/ it works.

In the development phase, the support is not necessary I think that the issue can be closed. @aninde do you agree?

**Comment by aninde** [comment]
> I've checked the issue and it's true that IE does not work. But only in the local (development) environment. On production build e.g. https://dev.handsontable.com/docs/binding-to-data/ it works.
> 
> In the development phase, the support is not necessary I think that the issue can be closed. @aninde do you agree?

Sure, that's good news.

**Comment by budnix** [comment]
Ok .. I can complete the issue that there is something with IE. I've got some errors on production build e.g:

![2021-06-23 o 11 02 49](https://user-images.githubusercontent.com/571316/123069044-b8365380-d412-11eb-8333-9eb29128cb6a.png)
