### ISSUE TITLE
Right click choice insert row above , but two rows are actually added

### ISSUE THREAD

**Issue by linxianseng** [handsontable/handsontable#8261]
### Description
just the title

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/dezfbgjt/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @linxianseng 

I believe that I have reported the same issue here https://github.com/handsontable/handsontable/issues/8148 so I am closing this report.
I will also make sure to update you once we solve https://github.com/handsontable/handsontable/issues/8148
