### ISSUE TITLE
New docs: Design 404 error page

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8266]
Currently, 404 pages have no design and do not care about user experiences.

It should show sidebar and navbar
It should link into the current version (default is `latest`) introduction page.
I might print some other information or graphic to make the user calm.

**Comment by AMBudnik** [comment]
I think that this issue can be closed as we already have z `404` page

<img width="487" alt="Screenshot 2022-10-29 at 11 10 33" src="https://user-images.githubusercontent.com/10757813/198823442-7e048812-5034-4c6f-ac82-1e99d9a08759.png">
