### ISSUE TITLE
How can I change a cell's editor and renderer after the table's loaded?

### ISSUE THREAD

**Issue by StephenChips** [handsontable/handsontable#8267]
Say I have a cell that displays an image URL, and outside the table, there is a group of buttons that can determine how to render the cell. For instance, we provide three renderer: **pure text**, **image previewer**, and **image uploader**. I wish when an user click one of those buttons, the cell will change the renderer and re-render itself. Different renderer has different user operation. When I implement this feature, I hope I can reuse Handsontale's built-in renderers, e.g. the **text renderer**, instead of writing a new one, which may result in some style incosistency problems. How can I achieve this goal? What API should I understand and use?

**Comment by AMBudnik** [comment]
Hi @StephenChips 

I did not have a snippet for loader but within the scheme of the renderer I would suggest that approach https://jsfiddle.net/handsoncode/jscdvnf2/

**Comment by StephenChips** [comment]
That's a nice idea for implementing such functionality, however, it still cannot solve my second problem: how to reuse Handsontable's built-in renderer in my custom renderer?

Maybe there wasn't enough details of this problem, let me explain it more: I want my **pure text** renderer behave as same as the default Handsontable text editor, which user can select, click and change texts, rather just has some readonly plain old text in it, and **I don't want to achive this by writing another ugly self-defined text editor in it.**, e.g. put an `<input>` tag or something in the cell, instead, I would like to access Handsontable's built-in *text* cell type's renderer, and ask it to repaint the cell again.

How should I get the default text renderer and use it? what public methods does it provide for initializing, rendering and destorying the content of the cells. Please reference relative document and gives some code snippets for example.

I will be very appreciated.

**Comment by AMBudnik** [comment]
Hi @StephenChips 

Within my demo, I used a predefined `HtmlRenderer` (line _13_). It does the same as the `textRenderer` but it also respects all the HTML tags. As you can see you are able to paste/edit those cells and when you paste a correct URL to an image the new image appears in the cell. Is anything else missing to accomplish this goal?

**Comment by AMBudnik** [comment]
I'm closing this issue as done as I did not get any further feedback.
However, if this statement is still true

>Is anything else missing to accomplish this goal?

please send me a message to support@handsontable.com
