### ISSUE TITLE
[9.0.1+] Uncaught TypeError: Cannot read property 'validateCell' of undefined

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8268]
### Description
As mentioned by @haraleib when data to a virtual sheet is added Handsontable tries to validate that as well. As the second sheet is not an instance of Handsontable we get an error.

### Issue transferred from discussion https://github.com/handsontable/handsontable/discussions/8263

<div type='discussions-op-text'>

<sup>Originally posted by **haraleib** June 22, 2021</sup>
Encountered the exception "_Uncaught TypeError: Cannot read property 'validateCell' of undefined_" **with handsontable version 9.0.1, which works in version 9.0.0**.

When using two sheets inside one hyperformula instance, I get this Exception if the second sheet has formulas which reference to the first sheet.

**jsfiddle Example:** https://jsfiddle.net/1yrfujg8/1/

**How to reproduce it in the provided example:**

- Open Browser-Debugger
- Type in a value, as mentioned in the screenshot

![image](https://user-images.githubusercontent.com/19574757/122907193-2a476380-d353-11eb-97cf-15d9f07c3cf8.png)

**Exception in the browser debugger**

![image](https://user-images.githubusercontent.com/19574757/122908847-e190aa00-d354-11eb-8e00-80f23330476d.png)
</div>

**Comment by haraleib** [comment]
Is there any new information for this bug? Unfortunately this is a regression for me to update from V9 to a newer Version of Handsontable.

**Comment by AMBudnik** [comment]
Hi @haraleib this issue hasn't been scheduled yet. If you have a short deadline on that specific use case please email me at support@handsontable.com

**Comment by vipina1019** [comment]
any update on this issue?

**Comment by haraleib** [comment]
Tried to update today to V11.1.0 to see if it is fixed indirectly through some other issues, but as expected the problem is still there.
I think to encourage/improve the usage of hyperformula with handsontable it should be scheduled for one of the next releases, as this regression makes it impossible to update,.. unfortunately.

**Comment by AMBudnik** [comment]
The v12 and v12.1. are already fully booked. But if you would need to get this issue solved now we can offer consulting services, as we have a separate team there. If you are interested @vipina1019 @haraleib please contact me at support@handsontable.com

**Comment by haraleib** [comment]
> In my opinion the root cause of this problem is that `sheet2` (in jsfiddle example) is not attached to any `hot` instance while Formulas Plugin tries to call `hot` methods on it.
> 
> I didn't test it but it should be sufficient to add the following code to [this line](https://github.com/handsontable/handsontable/blob/2dbc605c14b4f13eb25b77679f1c1cab98a274ad/handsontable/src/plugins/formulas/formulas.js#L513)
> 
> ```js
> if (!hot) {
>   return;
> }
> ```

@AMBudnik I tested the fix and the fix works as expected. Already using it in production.
Would be cool if the fix find its way in the official release soon :-)

**Comment by AMBudnik** [comment]
Thank you for feedback, @haraleib 
The issues are added to the next milestone. If there won't be any unexpected changes in our plans we will add the changes to the next version after v12.0. I will keep you updated.

**Comment by aninde** [comment]
Demo with v12.0.1 https://jsfiddle.net/jLf09mz5/1/ still didn't work, but [e2e test](https://github.com/handsontable/handsontable/pull/9476/files#diff-7b66fef7b23beb36f36182f6648b87d4e04e1ba5c150b2fb8f1990fd4876a0ee) with this case passed. @budnix can you check it?

**Comment by budnix** [comment]
> Demo with v12.0.1 https://jsfiddle.net/jLf09mz5/1/ still didn't work, but with a different warning, however [e2e test](https://github.com/handsontable/handsontable/pull/9476/files#diff-7b66fef7b23beb36f36182f6648b87d4e04e1ba5c150b2fb8f1990fd4876a0ee) with this case passed. @budnix can you check it?

The error is related to the wrong HF API usage. Fixed demo https://jsfiddle.net/tL04mqnv/.

**Comment by aninde** [comment]
@budnix thank you for spotting that :)

**Comment by AMBudnik** [comment]
@haraleib @vipina1019 we just released Handsontable v12.0.1 with fixes for this issue.

Here https://handsontable.com/docs/release-notes/ is the full list of changes in the latest patch.
