### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#827]
I am not sure but are there any licensing issue with HandsonTable.
Is it free to use?

Please let me know.

**Comment by EmilMoe** [comment]
I can see it has the MIT license here but on your website you have paid licenses and only a free trial. Not sure what the license actually is?

**Comment by AMBudnik** [comment]
@EmilMoe currently we have 2 products: one is placed here and it's called Handsontable (under MIT License) and the second one is Handsontable PRO (placed at out website https://handsontable.com/). The differences between those two products are in list of features. Handsontable PRO provides more features like: filtering, formula support, nested rows and columns, etc. At the bottom of this page you can find all the features that are in the PRO version: https://handsontable.com/features.html

We know that it may be confusing and we are already made some steps to change this situation but I cannot share any additional details yet.
