### ISSUE TITLE
New docs: Search input overlaps with dropdown to select version

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8270]
### Description
Search input overlaps dropdown to select the version on smaller screens. Maybe padding is missing for both elements.
This starts when the window width is 960 px - the dropdown is completely obscured. It looks good only from the width of about 1084 px. 

![Kapture 2021-06-23 at 13 11 56](https://user-images.githubusercontent.com/30186818/123087643-10765100-d425-11eb-9bba-31eac66ce2bd.gif)

### Your environment
* Docs version: https://github.com/handsontable/handsontable/pull/7626/commits/15f93a42df237202bafcd1d03ae1f91b9d48799a

**Comment by krzysztofspilka** [comment]
It behaves like this by design.

**Comment by aninde** [comment]
@krzysztofspilka the result of this design is that this is how it looks on iPad 6th, iOS 14.5.1 
On the right side of logo there is `N`, then search engine, then Guides. Uncollapsed search engine overlaps logo.

https://user-images.githubusercontent.com/30186818/123968521-952e1580-d9b7-11eb-99ac-de05c029fb24.MP4
