### ISSUE TITLE
New docs: Version dropdown to previous versions works incorrect

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8278]
### Description
Version dropdown for the previous version generates urls incorrectly

### Steps to reproduce
![Jun-24-2021 12-24-15](https://user-images.githubusercontent.com/2893099/123247601-5ac00680-d4e7-11eb-9bd9-a8dc768d7661.gif)

**Comment by budnix** [comment]
Duplicate https://github.com/handsontable/handsontable/issues/8279 :)
