### ISSUE TITLE
New Docs: Links for the older docs don't work 

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8279]
Links to the older documentation version do not work. The links that point to the older documentation should be constructed using a 3-digits pattern.
![Kapture 2021-06-24 at 12 24 22](https://user-images.githubusercontent.com/571316/123247833-8f33c280-d4e7-11eb-827a-421b4269702a.gif)

**Comment by Siemienik** [comment]
Needs to revert:
https://github.com/handsontable/handsontable/pull/8244/files#diff-2ef40d3a197e471d65055c88a638907ba2b0a9d0f9720f9ebdb643de3ba51bf1R35-R52
