### ISSUE TITLE
autocomplete in firefox is hidden to early

### ISSUE THREAD

**Issue by andydeakin** [handsontable/handsontable#828]
This issue is apparent in the autocomplete demo, so I will not reproduce an example here. (Handsontable 0.9.6)

I am using firefox 21.0 under windows, and when you either click on the down arrow, or double click the box to edit, the dropdown list appears. Sometimes, the drop-down box then disappears as soon as you attempt to mouse over it making it impossible to select anything. This appears to be random, and happens about 50% of the time. 

I cannot reproduce this error in chrome or IE8.

I have spent quite a while trying to get to the bottom of this, and have only managed to find that commenting out the following lines in Typeahead.prototype > mouseleave fixes the issue.
```javascript
    , mouseleave: function (e) {
    	//this.mousedover = false
    	//if (!this.focused && this.shown) this.hide()
    }
```
Has anyone else had this problem or managed to find a proper fix?

As a slight aside, the autocomplete ajax demo does not work because it looks like php is not being parsed on the server, so the php source is being served up rather than the json it should spit out.

**Comment by AMBudnik** [comment]
Please update your hot to [0.13.1](https://github.com/handsontable/handsontable/releases/tag/0.13.1) and if you still face this issue, please let me know.
