### ISSUE TITLE
New docs: Search input moves to the left after click 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8281]
### Description

Search input tremble right and left after a click 

![Kapture 2021-06-24 at 12 34 33](https://user-images.githubusercontent.com/30186818/123248769-97d8c880-d4e8-11eb-952f-e4ff248a0eb3.gif)

https://dev.handsontable.com/docs/

**Comment by Osky772** [comment]
Closing as done in https://github.com/handsontable/handsontable/pull/8303
