### ISSUE TITLE
New docs: Lack of icons in the theme switcher

### ISSUE THREAD

**Issue by Osky772** [handsontable/handsontable#8282]
The theme switcher should have icons: a sun for the light theme and a moon for a dark theme.

<img width="440" alt="Screenshot 2021-06-24 at 12 40 33" src="https://user-images.githubusercontent.com/33433795/123249561-614f7d80-d4e9-11eb-913d-7e6bb0239794.png">
<img width="440" alt="Screenshot 2021-06-24 at 12 40 41" src="https://user-images.githubusercontent.com/33433795/123249574-657b9b00-d4e9-11eb-8e22-03e74fa42580.png">

**Comment by aninde** [comment]
Icons should looks as were here https://github.com/handsontable/handsontable/pull/8243#issuecomment-866784788
