### ISSUE TITLE
New docs: Internet Explorer 11 improvements

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8284]
### Description

A couple of things in the appearance of the documentation on Internet Explorer 11 require adjustments

- [ ] 1. Logo Handsontable is shifted to the right
- [ ] 2. Jsfidle EDIT buttons get very dark after hover.

![image](https://user-images.githubusercontent.com/30186818/123252322-711c9100-d4ec-11eb-87fd-528771057a06.png)
![image](https://user-images.githubusercontent.com/30186818/123252334-74b01800-d4ec-11eb-94e0-c03fbf95c9f2.png)

Related to https://github.com/handsontable/handsontable/issues/8246

### Your environment
* Browser Name and version: Internet Explorer 11 
* Operating System: Windows 10 Pro

**Comment by warpech** [comment]
Closing as the docs site will not support IE11 anymore.
