### ISSUE TITLE
New docs: Inactive tabs have wrong styles for dark theme

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#8287]
### Description
As you can see on the below images, styles for `docs/hello-world/` page in dark theme don't show that some tab is inactive. It has `#cfdbe4` color for in on light theme.

![Screenshot 2021-06-24 at 15 06 29](https://user-images.githubusercontent.com/141330/123268520-63700700-d4fe-11eb-94ed-966711ce2eea.png)
![Screenshot 2021-06-24 at 15 06 35](https://user-images.githubusercontent.com/141330/123268530-65d26100-d4fe-11eb-9f17-65c6c802704a.png)

**Comment by aninde** [comment]
Closing as done by https://github.com/handsontable/handsontable/pull/8326.
