### ISSUE TITLE
New docs: A blink effect when entering the dark theme

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8288]
### Description

My browser remembers that I want to use the dark theme in the documentation. However, when I open the docs in a fresh tab, it "blinks" with a white theme first, and only then, after 200-300 ms, it switches to the dark theme. It looks bad.

### Steps to reproduce

1. Open new docs, choose a dark theme, close new docs
2. Open new docs in a new tab/window
3. See how it blinks at the first load

**Comment by budnix** [comment]
Close as done

**Comment by aninde** [comment]
Still valid after entering or reloading page with dark theme

https://user-images.githubusercontent.com/30186818/193294430-86385651-31e0-448c-a8b9-1d11bc3d936d.mov
