### ISSUE TITLE
New docs: Custom-block warning is unreadable on a dark theme

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8291]
### Description

- [ ] 1. Open https://dev.handsontable.com/docs/next/column-virtualization/#configuring-the-column-virtualization and enable dark theme.

![Screenshot 2021-06-24 at 17 49 07](https://user-images.githubusercontent.com/30186818/123293943-b05ed800-d514-11eb-95a5-70456142f1d6.png)
- [ ] 2. https://dev.handsontable.com/docs/next/row-parent-child/#row-parent-child
- [ ] 3. https://dev.handsontable.com/docs/next/row-virtualization/#configuring-row-virtualization

@krzysztofspilka should this demo be surrounded by a warning? 

![Screenshot 2021-06-24 at 18 11 05](https://user-images.githubusercontent.com/30186818/123297151-9a064b80-d517-11eb-945e-d1f3417eec66.png)

**Comment by Osky772** [comment]
Closing as done in https://github.com/handsontable/handsontable/pull/8310
