### ISSUE TITLE
New docs: Handsontable is polluted by the dark theme style

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8294]
### Description
- [ ] 1. Open https://dev.handsontable.com/docs/next/cell-renderer/#rendering-custom-html-in-cells and switch dark theme.
Content of `Title` column is unreadable on Chrome `92.0.4515.59` / macOS `11.2.3 (20D91)`

![Kapture 2021-06-24 at 18 20 19](https://user-images.githubusercontent.com/30186818/123298689-0b92c980-d519-11eb-8204-8582db614309.gif)

- [ ] 2. `summary` tag on https://dev.handsontable.com/docs/next/modules/#tree-shaking

![Screenshot 2021-06-24 at 19 11 51](https://user-images.githubusercontent.com/30186818/123305180-1bfa7280-d520-11eb-8701-21714461326c.png)

**Comment by Osky772** [comment]
Closing as done in https://github.com/handsontable/handsontable/pull/8310
