### ISSUE TITLE
New docs: Tables aren't responsive on mobile 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8296]
### Description
Some of the tables aren't responsive on mobile in portrait mode. 
Tested on Safari / iPhone SE 2020 iOS 14.6.
This was also the case in the older version, so it's a low priority.

if necessary, I can list them all, right now I stopped testing on https://dev.handsontable.com/docs/next/api/plugins/

- [ ] table https://dev.handsontable.com/docs/next/cell-editor/#common-editor-properties is very hard to read on mobile

 - [ ]  https://dev.handsontable.com/docs/next/context-menu/#context-menu-with-specific-options
 - [ ]  https://dev.handsontable.com/docs/next/migration-from-8.4-to-9.0/#available-methods

![image](https://user-images.githubusercontent.com/30186818/123300270-b5268a80-d51a-11eb-8dd7-df202d5dc9b1.png)

- [ ] all from https://dev.handsontable.com/docs/next/api/core/

![image](https://user-images.githubusercontent.com/30186818/123306550-bad39e80-d521-11eb-969c-1794686a4952.png)

- [ ] some from the hooks page. 
- https://dev.handsontable.com/docs/next/api/hooks/#afteraddchild is fixed
- https://dev.handsontable.com/docs/next/api/hooks/#afterautofill it's broken

**Comment by AMBudnik** [comment]
Here's what I see on Chrome 91/ Windows 10 for the migration guide (page is wide, no zoom)

![image (5)](https://user-images.githubusercontent.com/10757813/123434828-2e7eb580-d5cd-11eb-9246-0dff616b1363.png)

**Comment by aninde** [comment]
Despite changes from https://github.com/handsontable/handsontable/pull/8341  this table still looks odd on mobile https://dev.handsontable.com/docs/next/api/plugins/

<img width="378" alt="Screenshot 2021-06-30 at 15 35 40" src="https://user-images.githubusercontent.com/30186818/123969872-e7236b00-d9b8-11eb-9804-ff5a6c8f0f05.png">

<img width="367" alt="Screenshot 2021-06-30 at 15 38 44" src="https://user-images.githubusercontent.com/30186818/123970446-6ca71b00-d9b9-11eb-9d23-0ff0c3a2aa49.png">
<img width="411" alt="Screenshot 2021-06-30 at 15 39 11" src="https://user-images.githubusercontent.com/30186818/123970479-6e70de80-d9b9-11eb-9870-1f18425e9350.png">

**Comment by aninde** [comment]
Done by #8341.
