### ISSUE TITLE
New docs: Edit button overlaps Preview on mobile

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8297]
### Description
On some demos, `EDIT` button overlaps `Preview` on narrow screens and on mobile.
Tested on Safari / iPhone SE 2020 with iOS 14.6

#### List of the demos where the EDIT button needs a shift
- [ ] https://dev.handsontable.com/docs/setting-options/#entire-grid
- [ ] https://dev.handsontable.com/docs/setting-options/#single-column
- [ ] https://dev.handsontable.com/docs/setting-options/#single-row
- [ ] https://dev.handsontable.com/docs/events-and-hooks/#all-available-hooks-example
- [ ] https://dev.handsontable.com/docs/next/selection/#getting-data-from-the-selected-ranges
- [ ] https://dev.handsontable.com/docs/next/selection/#modifying-the-selected-cells
- [ ] https://dev.handsontable.com/docs/next/formatting-cells/#custom-cell-borders
- [ ] https://dev.handsontable.com/docs/next/searching-values/#custom-search-result-class

![image](https://user-images.githubusercontent.com/30186818/123308359-d93a9980-d523-11eb-886b-b9e668a6e8e0.png)

**Comment by Osky772** [comment]
Closing as done in https://github.com/handsontable/handsontable/pull/8312
