### ISSUE TITLE
Change Style specific cell

### ISSUE THREAD

**Issue by raulgq** [handsontable/handsontable#830]
You can change the background to a specific cell when the data already loaded?

**Comment by okahara** [comment]
How do you "set" or keep that background changed.  When I edit another cell after the background color changes, it disappears or reverts back to the original state.

**Comment by ravi590** [comment]
@codename-    After applying bacground color to one or multiple cells, if i edit a new cell and focus out, then background colors of all the cells in the table are being reset.Can any one help me how to retain background color of cell?

**Comment by AMBudnik** [comment]
Hi @okahara and @ravi590 you should include all styling in a custom renderer.

**Comment by ravi590** [comment]
Thanks.

**Comment by free1227** [comment]
@AMBudnik I have stored my style.but in the cell, if i set color,text-align style will lost.They cannot mix.
`CssRender : function(obj){
			var prop = {};
			prop.renderer = function(instance, td, row, col, prop, value, cellProperties){
				hot.renderers.HtmlRenderer.apply(this, arguments);
			    for(var objCss in obj){
			    	$(td).css(objCss,obj[objCss]);
			    }
			};
			var items = toolbar.get.getCurrentElem();
			var tempitemCoord;
			for(var i=0;i<items.length;i++){
				tempitemCoord = toolbar.get.getCoords(items.get(i));
				toolbar.handsontable.setCellMetaObject(tempitemCoord.row,tempitemCoord.col,prop);
				toolbar.handsontable.render();
			}
		}

setBold:function(id){
			var boldStatue = toolbar.status["Bold"];
			if(!id){
				if(boldStatue == 0){
					//toolbar.get.getCurrentElem().css('fontWeight','bold');
					var obj = {"fontWeight":"bold"};
					toolbar.core.CssRender(obj);
					toolbar.status["Bold"] = 1;
				}else{
					//toolbar.get.getCurrentElem().css('fontWeight','normal');
					var obj = {"fontWeight":"bold"};
					toolbar.core.CssRender(obj);
					toolbar.status["Bold"] = 0;
				}
			}else{
				//根据ID查找
			}
			//置焦点
			toolbar.core.setFocus();
			toolbar.core.clearTarget();
		}


setColor : function(value,id){
			
			var colorNum = value;
			var obj = {"backgroundColor":colorNum};
			toolbar.core.CssRender(obj);
			toolbar.core.clearTarget();
		}
`

**Comment by AMBudnik** [comment]
Hi @free1227 
Can you create a demo? It will be much easier to test.

ps. currently if you want to change only a background of a cell you can use `cells` method. You do not need to call a renderer.

**Comment by emilenriquez** [comment]
I am experiencing this as well. was there a fix for this bug?

**Comment by AMBudnik** [comment]
Hi @emilenriquez 

Please create a demo and a bug scenario.
