### ISSUE TITLE
New docs: Hello world app throws errors

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8300]
### Description

Open with the console https://dev.handsontable.com/docs/next/hello-world/

![Screenshot 2021-06-25 at 09 39 06](https://user-images.githubusercontent.com/30186818/123388782-7c79c600-d599-11eb-8dbe-20d1e17554b9.png)

**Comment by aninde** [comment]
Apart from errors, there are also many warnings on this page.
Additionally, after starting the demo, the console displays an error.
_editor.main.js:146 Uncaught Error: Cannot read property 'readFile' of undefined
TypeError: Cannot read property 'readFile' of undefined_
<img width="1013" alt="Screenshot 2021-07-06 at 16 06 55" src="https://user-images.githubusercontent.com/30186818/124614099-331c5700-de74-11eb-816e-0d302056adb7.png">

After a few clicks on the demo using the keyboard, I see unnecessary warnings.
<img width="489" alt="Screenshot 2021-07-06 at 15 53 38" src="https://user-images.githubusercontent.com/30186818/124614003-1bdd6980-de74-11eb-8785-38b9061a5f0c.png">

**Comment by AMBudnik** [comment]
This issue is no longer replicable using the latest version of the documentation. I tested it on Chrome 105 / macOS Monterey for React and Vanilla version of the demo that is now available at https://handsontable.com/docs/javascript-data-grid/demo/
