### ISSUE TITLE
Destroying Handsontable instances bound to the wrappers make them throw errors and crash.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#8311]
### Description
Issue based on the discussion in #8165.

Currently, destroying the Handsontable instance bound to the wrappers leaves behind the unusable wrappers, causes memory leaks, and throws errors.
Wrappers should display an appropriate warning when they recognize the HOT instance was destroyed, and stop calling the HOT instance's API.

### Steps to reproduce

1. Destroy the HOT instance in bound to the wrapper.
2. Try to do some operations on the wrapper.

### Demo

https://jsfiddle.net/js_ziggle/yr6g2eb7/

**Comment by aninde** [comment]
This issue will be fixed by v9.0.2 https://jsfiddle.net/476wnt9m/.

Very good idea with adding a warning to the console: _The Handsontable instance bound to this component was destroyed and cannot be used properly._

**Comment by swistach** [comment]
Hi @henricook,
I'm happy to announce we just released v9.0.2 with the fix to this bug.
