### ISSUE TITLE
[8.0.0] The selection gets doubled highlight on the edge of the table

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8317]
### Description

The selection blinks on the edge of the table. It's not happened in the 7.4.2 version.

![Kapture 2021-06-28 at 09 28 50](https://user-images.githubusercontent.com/571316/123597259-65ceab80-d7f3-11eb-83dc-8e543d247c84.gif)

Go to https://jsfiddle.net/kvyctxas/, grab the horizontal scrollbar and try to scroll from the most left to right. As a result, the selection blinks.

### Demo

https://jsfiddle.net/kvyctxas/

### Your environment
* Handsontable version: >=8.0.0
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
This issue will be fixed by the upcoming release of v12.1.3 https://jsfiddle.net/6vu5203o/. It works on the LTS Chrome 105.0.5195.125, Safari 15.6 (17613.3.9.1.5), Firefox 104, and Edge 105.0.1343 on Windows 10 and macOS 12.5. RTL mode also works.

**Comment by AMBudnik** [comment]
I'm closing this issue as solved in Handsontable v12.1.3
