### ISSUE TITLE
New docs: Dark mode changes the color of some elements within the datepicker

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8318]
### Description

This issue can be tested within this demo https://dev.handsontable.com/docs/next/date-cell-type/ and the dark mode.

![image (5)](https://user-images.githubusercontent.com/10757813/123623526-d4206780-d80d-11eb-8132-67f233da722b.png)

Here's the light mode

![image](https://user-images.githubusercontent.com/10757813/123623625-f6b28080-d80d-11eb-9c20-26760dd30b18.png)

### Your environment
* Handsontable version: frozen docs
* Browser Name and version: Chrome 91
* Operating System: Windows 10

**Comment by Osky772** [comment]
Closing as done in https://github.com/handsontable/handsontable/commit/e5b3d8309a7ab058233a659e6a927518814fd6ef and https://github.com/handsontable/handsontable/pull/8325
