### ISSUE TITLE
New docs: Fix anchor links 

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8330]
### Description
In the new docs engine, we have to use lower case for the anchor.  This issue assumes to change all anchor to match new engine.

camelCase and UpperCase could be found by the regex:

`\]\([^#)]*#[a-z-]*[A-Z]`

https://regexr.com/60tt3

![image](https://user-images.githubusercontent.com/2893099/123765936-7dc32f80-d8c6-11eb-9e2d-ebade21ea090.png)

To fully accomplish this issue:
* [x] update the content of `/next/guides`
* [ ] update the API ref generator (`jsdoc-convert`)

**Comment by aninde** [comment]
Part 1 is ready to merge on https://github.com/handsontable/handsontable/pull/8334.
