### ISSUE TITLE
Changes after CR for New Documentation project

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#8332]
### Description
As the title says, we need some improvements for new docs.

- [x] Removed favicon and logo files
- [x] Removed unnecessary comments
- [x] Refactored config for VuePress
- [x] Updated `.gitignore` file
- [x] Updated `package.json` file
- [x] Updated `package-lock.json` file
- [x] Removed most of files from `/next/api` directory

### Linked PRs

1. #7626

**Comment by budnix** [comment]
Close as done
