### ISSUE TITLE
Frozen columns are disturbed when column sorting is enabled

### ISSUE THREAD

**Issue by yhb1319170996** [handsontable/handsontable#8342]
### **Frozen columns are disturbed when column sorting is enabled**

After using columnsorting: true, right-click the fixed column function. The fixed column is not the specified one, but the first one

### Steps to reproduce

1.Add the columnsorting: true attribute
2.Use fixed column （manualColumnFreeze: true, contextMenu: true, ）
3.Right click the column to freeze. You will find that the first column is frozen instead of the column you selected

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @yhb1319170996 

Please provide a demo where the issue can be replicable.

I have added the settings you've mentioned here https://jsfiddle.net/handsoncode/uc49zaev/ but wasn't able to replicate the issue. I've tested it on Chrome 91 / Windows 10 using Handsontable v9.0.1 (latest)

**Comment by yhb1319170996** [comment]
Thank，The problem has been solved. My 7.2.2 will cause this problem. I have switched to 8.0.0

**Comment by AMBudnik** [comment]
I'm glad to hear that :) Thank you for the update, @yhb1319170996
