### ISSUE TITLE
New docs: Listbox of search area goes out of viewport on mobile on portrait mode

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8353]
### Description
Expanded listbox of search area goes out of viewport on mobile.
This makes it impossible to actually see the search results in portrait mode on mobile. 
Tested on iPhone SE 2020/ iOS 14.6 and Samsung Galaxy A51 / Android 11.

Result from  iPhone SE 2020/ iOS 14.6 

https://user-images.githubusercontent.com/30186818/124117045-f1547080-da6f-11eb-94ab-d3449a21eff3.MP4

### Steps to reproduce

1. Open https://dev.handsontable.com/docs/next/  on mobile view
2. Enter `test` into search engine

### Your environment

* Browser Name and version:  iOS 14.6, Android 11
* Operating System: Safari, Chrome, Samsung Internet

**Comment by Siemienik** [comment]
@aninde could I close this issue? or would you like to test it once again and confirm that it is done?

**Comment by AMBudnik** [comment]
@aninde Can we close this?

**Comment by aninde** [comment]
@AMBudnik yes, the problem is no longer there.

**Comment by AMBudnik** [comment]
Closed as done.
