### ISSUE TITLE
New documentation: scrolling doesn't look like properly on dark theme

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#8355]
### Description
As the title says, we have some problem with the dark theme. Demos flickers with dark background while scrolling, as we can see on the below image.

![dark (1)](https://user-images.githubusercontent.com/141330/124238423-df7ad800-db18-11eb-8dec-dbd852ab94fa.gif)

**Comment by Siemienik** [comment]
@aninde could I close this issue? or would you like to test it once again and confirm that it is done.?

**Comment by krzysztofspilka** [comment]
@aninde ?

**Comment by aninde** [comment]
Closing as done.
