### ISSUE TITLE
Filter by value does not work

### ISSUE THREAD

**Issue by Silentirk** [handsontable/handsontable#8359]
### Description
It seems to me that filter by value just does not work in any version of handsontable.

### Steps to reproduce
1. Enter something in "filter by value", for example "EUR" in "Currency"Column on https://handsontable.com/examples?headers&filters
2. Press OK. 
3. Nothing is filtered

### Your environment
* 9.0.1 but also tried to reproduce on 8.4.0 and 7.4.2:
* Edge 91.0.864.59, Chrome 84.0.4147.89:
* Windows 10, Windows Server 2012R2

**Comment by Silentirk** [comment]
Sorry, just found that you have to press "Clear"before entering something. It's just very confusing for those who are used to excel, but I can understand the logic now.
It would be good to have an option to choose an excel-like behavior though.

**Comment by AMBudnik** [comment]
Thank you for sharing the opinion @Silentirk 
We have an opened discussion on this subject here https://github.com/handsontable/handsontable/discussions/7765
