### ISSUE TITLE
Drag and Drop with check box

### ISSUE THREAD

**Issue by zwilcox** [handsontable/handsontable#836]
It seems when you drag and drop check boxes with uneven amount of checks and unchecks, you get a '#bad value#' in the cells where unchecked boxes should be.

One way to reproduce this. create a column with check marks using the checkmark renderer and editor.  select the first row and their row to be checked with the second row to be unchecked.  Select row 1-3.  Drag that to four rows below.  A '#bad value#' will appear where the unchecked mark should be.

I've dug into the checkbox renderer and found where this happens.  I've added an extra else if condition where it checks value.  My fix is down below:

```javascript
		else if (value === null) { //default value
			INPUT.className += ' noValue';
			TD.appendChild(INPUT);
		} 
		else if(value === ''){
			//this was an expansion of the handsontable checkbox editor to fix
			//a bug i found when performing a drag/drop operation when not all
			//boxes where even
			INPUT.checked = false;
			TD.appendChild(INPUT);
		}
		else {
			instance.view.wt.wtDom.fastInnerText(TD, '#bad value#'); //this is faster than innerHTML. See: https://github.com/warpech/jquery-handsontable/wiki/JavaScript-&-DOM-performance-tips
		}

```

**Comment by AMBudnik** [comment]
Please update to 0.13.1, seems to work fine with our [demo](http://handsontable.com/demo/checkbox.html)
