### ISSUE TITLE
New docs: improve the way how to version the Hello World app

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8360]
### Description
This issue assumes to improve the further way for versioning Hello World app:

Currently it is:

```vue
<HelloWorld :sandboxesIds="[
  'handsontable-javascript-data-grid-hello-world-app-dzx8f',
  'handsontable-typescript-data-grid-hello-world-app-145es',
  'handsontable-react-data-grid-hello-world-app-yt46w',
]"></HelloWorld>
```

Expected:

```vue
<HelloWorld>
  <CodeSandboxTab name="JavaScript" tabId="js" csId="handsontable-javascript-data-grid-hello-world-app-dzx8f" />
  <CodeSandboxTab name="TypeScript" tabId="typescript" csId="handsontable-typescript-data-grid-hello-world-app-145es" />
  <CodeSandboxTab name="React" tabId="react" csId="handsontable-react-data-grid-hello-world-app-yt46w" />
  <DisabledTab name="Angular" tabId="angular" />
  <DisabledTab name="Vue" tabId="vue" />
</HelloWorld>
```

This makes sense in many ways:
* currently, we could not add the Angular or Vue tabs for the next version without changing currently released versions.
* currently, we attach ids to the tabs by order in an array. After this issue, we explicitly set all params from MD level.
* That way enables us to manipulate tab orders depending on docs versions.

**Comment by wojciechczerniak** [comment]
I agree ☝️very good idea, two things:

- IMO `tableId` is redundant, we can use `name` with `toLowerCase` or toKebabCase transform
- IMO `DisabledTab` is unnecessary. We should go with `<CodeSandboxTab disabled=true>`

**Comment by wszymanski** [comment]
Information about which file is selected should be also versioned. The idea to select specific file in sandbox was [developer here](https://github.com/handsontable/handsontable/commit/84d258abb1a8269973d3393c6f56f08f0e678477). However, I suggest to implement it within this task.

**Comment by Siemienik** [comment]
done in #8427
