### ISSUE TITLE
Feature Request: case-insensitive filter options

### ISSUE THREAD

**Issue by dawncold** [handsontable/handsontable#8363]
### Description
![Screenshot from 2021-07-05 20-27-33](https://user-images.githubusercontent.com/502856/124472156-5b527a00-ddd0-11eb-8c76-e4e8c9c9600d.png)

When I use filter function demo: https://handsontable.com/docs/9.0.1/demo-filtering.html, I found the filter by value options are ordered by ASCII value instead of ordering by value with case-insensitive.

I checked some products, like Apple Numbers, Microsoft Excel, Google Sheets, they use case-insensitive ordering for filter options.

So, I think it could be helpful to provide an option for developer to sorting the filter options.

**Comment by AMBudnik** [comment]
Hi @dawncold 

we already have this topic reported in the Discussions at https://github.com/handsontable/handsontable/discussions/7707 
Please check that subject for updates.
