### ISSUE TITLE
New docs: 404 on Suggest edits links

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8380]
### Description

On each page there is link to the `Suggest edits`. Now all of those links returs. 404. 

Example
https://dev.handsontable.com/docs/vue-hot-column/#_3-binding-the-state-between-components
404 - https://github.com/handsontable/handsontable/edit/develop/docs/9.0/guides/integrate-with-vue/vue-hot-column.md

### Your environment
* Handsontable version: Documentation 07.07.21
* Browser Name and version: any
* Operating System: any

**Comment by budnix** [comment]
It will be automatically fixed after the `feature/issue-7624` branch merging to the `develop`. When I replace the `/develop/` part in the example URL with the `/feature/issue-7624/` it works. I assume that the issue can be closed after the release, is here as a reminder :)

**Comment by aninde** [comment]
@budnix you were right :) After the release, these links work properly, so I'm closing the issue.
E. g. link from https://handsontable.com/docs return to the https://github.com/handsontable/handsontable/edit/develop/docs/9.0/guides/getting-started/introduction.md.
