### ISSUE TITLE
New docs: Note under the batch graph is hidden

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8389]
### Description

Note under the batch graph is hidden.

**New docs**
https://dev.handsontable.com/docs/batch-operations/#overview
![image](https://user-images.githubusercontent.com/10757813/124757783-3c69fa00-df2e-11eb-878a-8aa7fc138ad2.png)

**Old docs**
https://handsontable.com/docs/tutorial-suspend-rendering.html
![image](https://user-images.githubusercontent.com/10757813/124757851-4e4b9d00-df2e-11eb-9f42-97aee075e320.png)

### Your environment
* Handsontable version: -
* Browser Name and version: Chrome 91
* Operating System: Windows 10

**Comment by kirszenbaum** [comment]
Fixed in #9706
