### ISSUE TITLE
New docs: [mobile] Tables on the Manual Column move needs some adjustments - first two columns are too narrow

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8390]
### Description

Those columns do not look perfect on the Desktop version. But the mobile version is far harder to read.

**Desktop**
![image](https://user-images.githubusercontent.com/10757813/124759782-53a9e700-df30-11eb-8d9b-5ad420c02cd2.png)

**Mobile**
![mobile](https://user-images.githubusercontent.com/10757813/124759606-19404a00-df30-11eb-9ef8-5bbfe28a2c90.gif)

### Your environment
* Handsontable version: -
* Browser Name and version: Safari for iOs
* Operating System: 14.6 iOs, iPhone Xs

**Comment by aninde** [comment]
Addressed here https://github.com/handsontable/handsontable/issues/8296#issuecomment-871413971 and here https://github.com/handsontable/handsontable/pull/8376.

**Comment by aninde** [comment]
I am closing this issue as a duplicate #8376.
