### ISSUE TITLE
[9.0.0] No render when data in HyperFormula is updated outside of Handsontable

### ISSUE THREAD

**Issue by rsify** [handsontable/handsontable#8391]
### Description
Issue extracted from https://github.com/handsontable/handsontable/pull/8134 (2.)

### Steps to reproduce
1. Create a Handsontable instance with `formulas` enabled, using an external HyperFormula instance (e.g. `const hf = HyperFormula.buildEmpty()`
2. Use `HyperFormula#setCellContents`
3. Handsontable should re-render, but doesn't.

See this test for more details https://github.com/handsontable/handsontable/blob/9a3ecca37b95ae157a21a6bd84d6987867ec5a8d/src/plugins/formulas/__tests__/formulas.spec.js#L2562-L2575

### Your environment
* Handsontable version: https://github.com/handsontable/handsontable/commit/0def352bb60257f8822b47156b94c25b05634fe9, issue was technically always present in the new plugin though.

**Comment by AMBudnik** [comment]
Note to myself : inform [forum](https://forum.handsontable.com/t/gh-8391-hyperfomula-updating-cell-formula-references-which-is-the-proper-method/5446)

**Comment by wszymanski** [comment]
I've pushed done changes within: https://github.com/handsontable/handsontable/commit/e6b6e5d9d0c3b4b23ff610b8988bdd4f156c7488. They address few proper reaction on changes coming from actions done on Handsontable, such as row insertion or using `setDataAtCell` and from the outside, like using engine's `setCellContents` method. In first case, an sync in reaction to triggered `valuesUpdated` hook shouldn't be performed, unlike the second case.

**Comment by warpech** [comment]
This issue was discussed internally at https://handsoncode.slack.com/archives/D4QHNCTS4/p1637156318000300 (@warpech, @wszymanski)

**Comment by krzysztofspilka** [comment]
Closed due to inactivity.
