### ISSUE TITLE
New docs: Some pages don't have the right menu Table of contents.

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8392]
### Description
Some random pages don't have the right menu Table of contents. Mainly related to wrappers.

### List of these pages:
- [ ] https://handsontable.com/docs/api/ _the menu is here, but it doesn't work, so it's as if it wasn't there. I am adding this amendment in order not to open up a new issue for it._
- [ ] https://dev.handsontable.com/docs/hello-world/
- [ ] https://dev.handsontable.com/docs/react-setting-up-a-locale/
- [ ] https://dev.handsontable.com/docs/row-prepopulating/
- [ ] https://dev.handsontable.com/docs/handsontable-cell-type/
- [ ] https://dev.handsontable.com/docs/file-structure/ - I don't insist on it, because there is not much content here

**React - half of them**

- [ ] https://dev.handsontable.com/docs/react-custom-context-menu-example/
- [ ] https://dev.handsontable.com/docs/react-custom-renderer-example/
- [ ] https://dev.handsontable.com/docs/react-language-change-example/
- [ ] https://dev.handsontable.com/docs/react-redux-example/
- [ ] https://dev.handsontable.com/docs/react-hot-reference/

**Angular - all**

- [ ] https://dev.handsontable.com/docs/angular-installation/
- [ ] https://dev.handsontable.com/docs/angular-simple-example/
- [ ] https://dev.handsontable.com/docs/angular-custom-id/
- [ ] https://dev.handsontable.com/docs/angular-setting-up-a-locale/
- [ ] https://dev.handsontable.com/docs/angular-custom-context-menu-example/
- [ ] https://dev.handsontable.com/docs/angular-custom-editor-example/
- [ ] https://dev.handsontable.com/docs/angular-custom-renderer-example/
- [ ] https://dev.handsontable.com/docs/angular-language-change-example/
- [ ] https://dev.handsontable.com/docs/angular-hot-reference/

**Vue  - half of them**

- [ ] https://dev.handsontable.com/docs/vue-simple-example/
- [ ] https://dev.handsontable.com/docs/vue-setting-up-a-locale/
- [ ] https://dev.handsontable.com/docs/vue-custom-id-class-style/
- [ ] https://dev.handsontable.com/docs/vue-custom-context-menu-example/
- [ ] https://dev.handsontable.com/docs/vue-language-change-example/

### Expected result:
Right menu as on https://dev.handsontable.com/docs/api/.

### Your environment
* Handsontable version: Documentation 07.07.21
* Browser Name and version: Chrome 92.0.4515.80
* Operating System: macOS 11.2.3 (20D91)

**Comment by wszymanski** [comment]
I would not add `Table of contents` for every page. Just two, below pages has more than `2` paragraphs and I would do changes just for them. Most of mentioned pages contain just `Overview` and `Example` visible on one screen.

- https://handsontable.com/docs/handsontable-cell-type/
- https://handsontable.com/docs/angular-installation

WDYT @krzysztofspilka?

**Comment by AMBudnik** [comment]
I think that this issue needs an update. A few pages listed on top do not seem to have this issue.

**Comment by krzysztofspilka** [comment]
I checked most of the listed pages and I think they already have a ToC.
