### ISSUE TITLE
New docs: [9.0.0+ Docs]: All of the Angular's demos uses `Babel + JSX` JSFiddle config instead `TypeScript`

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8394]
### Description

This issue is replicable using old and new docs from v9+ of the `Referencing the Handsontable instance` page for Angular.
Older versions are using TypeScipt config.

### Steps to reproduce

1. Go to https://handsontable.com/docs/9.0.1/frameworks-wrapper-for-angular-hot-reference.html
2. Click `edit` to run the demo in JSFiddle
3. When you open the demo table does not show and there's an error in the console. When you change the config to `TypeScript` it works well again.

![repro](https://user-images.githubusercontent.com/10757813/124763574-69211000-df34-11eb-875a-e0d843398430.gif)

### Your environment
* Handsontable version: 9+
* Browser Name and version: Chrome 91 
* Operating System: Windows 10

**Comment by aninde** [comment]
The same issue occurs on new docs https://dev.handsontable.com/docs/angular-hot-reference/ so, I'm adding proper project.
