### ISSUE TITLE
Handsontable documentation gets a major refresh

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8402]
Hi All!

In a large boost to the [Handsontable](https://handsontable.com/) developer experience, we're proud to present a revamped version of our [documentation portal](https://handsontable.com/docs/). Find out what's new!

### Brand-new layout
We revamped the documentation portal's visuals:
* **Table of contents on the right-hand side**: get an overview of every page at a single glance.
* **Clear composition**: your screen real estate is put to good use.
* **Responsive design**: explore the documentation on your device of choice, in portrait or landscape mode.

![iphone](https://user-images.githubusercontent.com/10757813/124921184-6c7dcf80-dff8-11eb-9177-94c25803bfce.gif)

### Dark theme
Your tired eyes will love it: discover the Handsontable documentation dressed in the new dark theme.

![macbook4](https://user-images.githubusercontent.com/10757813/124921277-83bcbd00-dff8-11eb-964b-7bd648e0935e.gif)

### Content structure overhaul
It's not just bells and whistles—we took care of the content as well:
* **New information architecture**: we redesigned the information structure from the ground up, so you can focus on what matters.
* **Guides vs API reference**: the carefully written implementation guides and the automatically-generated API reference now live in two separate sections.
* **Linguistic check**: native English speaker or not, you'll now find our documentation easier to read.

### Better search engine
The search is now at the heart of our documentation:
* First of all, it's **blazing fast!**
* It's **more accurate**.
* Search **results are clearly grouped** into the guides section and the API reference section.

![macbook1](https://user-images.githubusercontent.com/10757813/124921382-a0f18b80-dff8-11eb-967d-bf0c61535b97.gif)

### New documentation tool stack
Most of it all is possible thanks to our new documentation engine, based on [VuePress](https://vuepress.vuejs.org/):
* The whole portal is now built as a **single-page application (SPA)**, which boosts the **performance**—everything just clicks.
* You can easily [build the documentation locally](https://github.com/handsontable/handsontable/tree/develop/docs).
* On our side, we can now write in **Markdown**. For us, it makes the Handsontable documentation easier to maintain. For you, it means more frequent updates and more accurate content.

### Code and preview tabs
Code examples get an upgrade in their own right:
* Code samples now sport **Handsontable previews** right next to them.
* You can easily **switch between** the code samples and the preview, using tabs.

![macbook2](https://user-images.githubusercontent.com/10757813/124921492-c1214a80-dff8-11eb-92d0-992c4be2030c.gif)

### New content
While working on the update, we couldn't resist bringing in some new goods along the way:
* A whole new section with [examples](https://handsontable.com/docs/examples/) covering real-life use cases.
* A new page dedicated to [security](https://handsontable.com/docs/security/).
* More information on Handsontable's [IME support](https://handsontable.com/docs/ime-support/).
* Our [versioning policy](https://handsontable.com/docs/versioning-policy/) description.
* A brand-new ["Hello, world!"](https://handsontable.com/docs/hello-world/) app (which actually does a lot more than say hello).

![macbook3](https://user-images.githubusercontent.com/10757813/124921583-d72f0b00-dff8-11eb-9466-28aae885dc2f.gif)

### Coming soon
If this sounds like a lot, brace yourself—there's more on the way:
* More **examples**.
* More **new content**.
* More **frequent updates**, also independently from the software update cycle.
* More rewrites and language improvements.

We hope you like it and [stay tuned](https://twitter.com/handsontable) for more!

**Comment by davestewart** [comment]
Yay VuePress!

My site is also built in VuePress. 

It's fast and has a great DX.

Well done!

**Comment by warpech** [comment]
Closing the announcement as it has served its purpose. This article was also published on our blog, where you can find more announcements like this: https://handsontable.com/blog/articles/2021/7/handsontable-documentation-gets-a-major-refresh
