### ISSUE TITLE
Undefined this.getDataAtCell inside afterChange on Handsontable

### ISSUE THREAD

**Issue by Arun9032** [handsontable/handsontable#8406]
hi Team,
I am having Handsontable for editing particular rows, i could not get the row values with this.getDataAtCell() inside afterChange() function, it says that this.getDataAtCell() is undefined. Please help in resolving this for editing the cell data and getting the particular rows.

**Comment by AMBudnik** [comment]
Hi @Arun9032 

In the Vanilla version `this` inside the `afterChange` hook is the instance of Handsontable (example http://jsfiddle.net/b6jdukrp/) so you should not get this error even if you refer to a cell that does not exist. So I assume that you might be using a framework?. Am I right?

**Comment by AMBudnik** [comment]
I'm closing this topic as there's no update for 3 weeks.
However, if you would like to continue the subject @Arun9032 please contact us at support@handsontable.com
