### ISSUE TITLE
Vertical mouse scrolling still does not work without horizontal scrollbar in 0.9.6 

### ISSUE THREAD

**Issue by logeshkumars** [handsontable/handsontable#841]
Help me...
Vertical mouse scrolling still does not work without horizontal scrollbar in 0.9.6

**Comment by AMBudnik** [comment]
Please update to 0.14.1 and leave us feedback it it still occurs.

**Comment by AMBudnik** [comment]
I assume this issue can be closed in lack of recent activity.

**Comment by viktor-hunko** [comment]
Faced with same pb in latest version of handsontable (Mac, Chrome v.58), scroll doesn't work if mouse is over header. Any idea how it can be fixed ?
Thanks,

**Comment by AMBudnik** [comment]
Hi @viktor-hunko 

the issue that you have described is opened at https://github.com/handsontable/handsontable/issues/4114
