### ISSUE TITLE
New docs: Duplicated page HyperFormula Integration needs to be removed

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8411]
### Description

Page [HyperFormula integration](https://handsontable.com/docs/hyperformula-integration/#overview)   includes content from   [Formula calculation](https://handsontable.com/docs/formula-calculation/#formula-calculation) and should be removed as it was mention here https://github.com/handsontable/handsontable/pull/8299.   The whole [file](https://github.com/handsontable/handsontable/blob/develop/docs/9.0/guides/formulas/hyperformula-integration.md) needs deletion because it is still accessible from the search engine and URL.

The only difference in the content is the **infobox** under the first header.

On [Formula calculation](https://handsontable.com/docs/formula-calculation/#formula-calculation) infobox contain: 
```
In Handsontable 9, we introduced a new formula plugin. To upgrade your Handsontable version from 8 to 9, see the migration guide.
```

On deprecated page to removal [HyperFormula integration](https://handsontable.com/docs/hyperformula-integration/#overview) it is:
```
To use HyperFormula within Handsontable's default formulas plugin, you only need your existing Handsontable license key.

To use HyperFormula independently from Handsontable, you need a license key dedicated to HyperFormula. For details, contact our Sales Team (opens new window).
```
I think we should merge the content of both infoboxes, shorten it,  and place it on the site `Formula calculation`. @krzysztofspilka WDYT?

### Demo

https://handsontable.com/docs/hyperformula-integration/#overview

**Comment by krzysztofspilka** [comment]
@aninde let's keep the second one (longer version). Thanks.
