### ISSUE TITLE
New docs: Demo Handsontable cell type the view is to be improved

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8413]
### Description

Demo Handsontable cell type does not roll out as should be.

Is:

![Screenshot 2021-07-09 at 16 32 08](https://user-images.githubusercontent.com/30186818/125094285-6b6da080-e0d3-11eb-9325-cdde5ff727e6.png)

Shoud be:

![Screenshot 2021-07-09 at 16 33 02](https://user-images.githubusercontent.com/30186818/125094264-67da1980-e0d3-11eb-8450-7ecc36482157.png)

### Demo

https://handsontable.com/docs/handsontable-cell-type/ broken
https://handsontable.com/docs/8.4.0/demo-handsontable.html fixed

**Comment by budnix** [comment]
The demo is fixed in https://github.com/handsontable/handsontable/pull/8449. The Handsontable Cell Type demo has another issue with overlapping parent element but AFAIK we can't do anything with that.
