### ISSUE TITLE
New docs: Content needs update on page Comments

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8416]
### Description

The option comments has the properties `read-only`  and `style` which should be included in the API reference in the same way we documented `displayDelay` .

### Demo

https://handsontable.com/docs/api/comments/#comments 
Source code: https://github.com/handsontable/handsontable/blob/master/src/plugins/comments/comments.js#L27
https://github.com/handsontable/handsontable/blob/master/src/plugins/comments/comments.js#L26

**Comment by AMBudnik** [comment]
Already done. I'm closing this issue as solved.

<img width="801" alt="Screenshot 2022-11-03 at 15 43 52" src="https://user-images.githubusercontent.com/10757813/199752241-cbb9e5c2-dd7e-45a8-9851-b580e2fdac59.png">
