### ISSUE TITLE
Horizontal scrollbar can get into a state where it will not scroll to show all of last column

### ISSUE THREAD

**Issue by edallen** [handsontable/handsontable#842]
This table with a horizontal scrollbar will sometimes become unable to scroll all the way to the right. Only part of the last column shows. It can vary how much of it is revealed from only a sliver to something like the picture shown. I always see at least a part of the last column, but often not enough to be useful.

When it was in the state shown in the screenshot, dragging the horizontal scrollbar further to the right would just make the scrollbar thumb spring back. The table would scroll no further.

Changing the width of the browser window cleared the issue away and I was then able to scroll all the way. Narrowed browser windows seem to have something to do with it.

![screen shot 2013-06-27 at 9 34 10 am](https://f.cloud.github.com/assets/586/717242/e14db506-df47-11e2-914e-2c83b870a0fe.png)

This was in Chrome but I believe we have seen the same behavior in Firefox.

**Comment by AMBudnik** [comment]
Hi guys, please update to [0.14.0](https://github.com/handsontable/handsontable/releases/tag/0.14.0) and give us a feedback if this issue still occurs.

**Comment by AMBudnik** [comment]
Issue closed in lack of recent acitivity and will stay closed till an answer.
