### ISSUE TITLE
Incorret comment in `Conditional formatting` example

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8422]
There's also a comment to change in the code snippet

![image](https://user-images.githubusercontent.com/10757813/106125483-85867880-615c-11eb-8d74-35ce05a3b732.png)

The class is not called "negative".

_Originally posted by @AMBudnik in https://github.com/handsontable/docs/issues/241#issuecomment-768958470_

**Comment by kirszenbaum** [comment]
Fixed in #9716
