### ISSUE TITLE
New docs: SourceCodeLink adjustment

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8424]
### Description

- [ ] 1. The @wojciechczerniak proposal to remove this container and rewrite it to HTML and MD https://github.com/handsontable/handsontable/pull/7626#discussion_r660540267.

- [x] 2. As @wojciechczerniak said in https://github.com/handsontable/handsontable/pull/7626#discussion_r658618061

**Is:** 
`const exampleRegex = /^(source-code-link)\s*(\S*)\s*([\S|\s]*)$/;`

**should be:**
`const sourceCodeLinkRegex = /^(source-code-link)\s*(\S*)\s*([\S|\s]*)$/;
`
at 
https://github.com/handsontable/handsontable/blob/ea866deea05e4934a8144154ec6105a2a9fbf17b/docs/.vuepress/containers/sourceCodeLink.js#L6

- [ ] 3. Removal of `<OutboundLink/>` based on discussion at https://github.com/handsontable/handsontable/pull/7626#discussion_r659764380

https://github.com/handsontable/handsontable/blob/ea866deea05e4934a8144154ec6105a2a9fbf17b/docs/.vuepress/containers/sourceCodeLink.js#L17

**Comment by Siemienik** [comment]
AD 1 & 3. I will not do it because I don't see the sense in these requests.
