### ISSUE TITLE
Typo in /tutorial-modules page

### ISSUE THREAD

**Issue by Osky772** [handsontable/handsontable#8452]
### Description

Under the section "How to use modules" the last paragraph has a typo.

The sentence starts with: "The use cases may **wary** greatly, (...)", but it should be: "The use cases may **vary** greatly, (...)".

### Links
https://handsontable.com/docs/8.3.0/tutorial-modules.html

**Comment by adrianszymanski89** [comment]
This issue is no longer valid for new documentation.
