### ISSUE TITLE
Remove `most popular` phrase from binding data tutorial

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8457]
### Description

I'm referring to
![image](https://user-images.githubusercontent.com/10757813/103631278-0fb73480-4f43-11eb-836c-c693e6c0c7a4.png)

In all those years in Support, I can definitely say that objects are way more popular. Nevertheless, I would just suggest removing that statement from the description.

### Links

https://handsontable.com/docs/8.2.0/tutorial-data-sources.html

**Comment by kirszenbaum** [comment]
Fixed here: https://github.com/handsontable/handsontable/pull/9724/files#diff-4f389bdb0cd1e6d01e0a35a306e168240881e254f756b0ba8a243766d36a0ea6R23
