### ISSUE TITLE
AND/OR filters: Missing documentation for custom items

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#8461]
@AMBudnik commented on [Wed Jul 12 2017](https://github.com/handsontable/handsontable/issues/4395)

### Description

We should add a description and possibly a demo to show how to add the `AND/OR` filters to a custom dropdown menu.

- [ ]  Array http://jsfiddle.net/s08gnk1r/
- [ ] Object http://jsfiddle.net/L6u9dzzd/

### Your environment
* Handsontable version: 1,12,0
* Browser Name and version: Chrome 59
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
I also suggest adding some visuals for better understanding. Here's what we can do https://github.com/handsontable/handsontable/issues/4253

**Comment by AMBudnik** [comment]
This issue is no longer valid. The following info is added on the Content Menu page https://handsontable.com/docs/react-data-grid/context-menu/. Closing as done.
