### ISSUE TITLE
Options>columns - define what are the cell properties and explain function

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8468]
### Description
It is said that

![Zrzut ekranu 2020-10-9 o 12 30 11](https://user-images.githubusercontent.com/10757813/95573078-3391d980-0a2b-11eb-84b1-84c17549793f.png)

but we do not explain what can be defined as cell properties. We should also add the link to the data https://handsontable.com/docs/8.1.0/Options.html#data.

We also should explain the function (what parameters are possible and what is returned) as a source of columns.

Reference: https://github.com/handsontable/docs/issues/9
The issue has been reported as a part of the https://github.com/handsontable/support/issues/254 investigation

**Comment by kirszenbaum** [comment]
@AMBudnik

> we do not explain what can be defined as cell properties.
The description looks different now that at the time of creating this issue. I'm just changing the wording slightly.

> We should also add the link to the data
I'm adding the link

> We also should explain the function (what parameters are possible and what is returned) as a source of columns.
I believe that's already covered by the new [description](https://handsontable.com/docs/api/options/#columns) of `columns`, but please let me know if you think we could improve it further.

PR: #9702 (addresses #8467 as well)

**Comment by AMBudnik** [comment]
>I believe that's already covered by the new [description](https://handsontable.com/docs/api/options/#columns) and code sample of columns, but please let me know if you think we could improve it further.

True. As far as I remember, it was altered a couple of months ago.
