### ISSUE TITLE
Auto fill - small changes

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8470]
### Description
* Avoid using other application names
* 'Log to console' button produces a console error for the first demo
* 'to adding' sounds odd
> Additionally, to adding new rows when it comes to the edge of the table bottom we need change autoInsertRow to true.

### Links
Autofill - https://handsontable.com/docs/8.1.0/demo-auto-fill.html
support task (origin) - https://github.com/handsontable/support/issues/259

**Comment by kirszenbaum** [comment]
> Avoid using other application names

I guess we changed the course on that (e.g., https://handsontable.com/docs/keyboard-shortcuts/#navigation-keyboard-shortcuts)

> * 'Log to console' button produces a console error for the first demo

Doesn't apply to the new docs.

> 'to adding' sounds odd
Doesn't apply to the new docs.

**Comment by AMBudnik** [comment]
True. OK, so we can close the issue as solved.
