### ISSUE TITLE
Hiding rows - misleading information

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8474]
### Description
On the page we state that

> You can show/hide certain rows straight from the Context menu using the following keys: hidden_rows_show and hidden_rows_hide.

But the demo below this description uses the default context menu 

```js
data: Handsontable.helper.createSpreadsheetData(12,5),
  colHeaders: true,
  rowHeaders: true,
  contextMenu: true,
  hiddenRows: {
    rows: [3, 5, 9],
    indicators: true
}
```

Wouldn't it be better to use those defined keys or provide two demos,
* first with default demo to show that enabling hiding shows 'Hide row' / 'Show row'
* second with the  `hidden_rows_show` and `hidden_rows_hide` keys only

#### Other issues on the page

* the 'gets data' doesn't seem to sound good in 
> Rows being hidden are included in a DataMap (gets by the getData method), but they aren't rendered.

* remove one 'See the examples section for more details.' from the 'Additional options' paragraph.
![Zrzut ekranu 2020-10-22 o 10 10 17](https://user-images.githubusercontent.com/10757813/96843667-e06a4e80-144e-11eb-9ed8-3d743481ab5d.png)

I would just leave the one at the end. They both redirect to the same place on the page.

### Related issue
* hidden columns - basically the same set of issues - https://github.com/handsontable/docs/issues/231

### Links
hiding rows - https://handsontable.com/docs/8.1.0/demo-hiding-rows.html
support task (origin) - https://github.com/handsontable/support/issues/259

**Comment by kirszenbaum** [comment]
All points mentioned in this issues are being fixed in https://github.com/handsontable/handsontable/pull/8692

**Comment by AMBudnik** [comment]
Great! Thank you @kirszenbaum 
Please feel free to close this ticket after your PR approval.
