### ISSUE TITLE
Using Callbacks Tutorial

### ISSUE THREAD

**Issue by caseyredisatwork** [handsontable/handsontable#8480]
Can you please add some basic validator logic to the tutorial so that it's easier to see how their corresponding events get fired in relation to others like before/after change, render etc?  I have a situation where I want to bypass further validation of a cell and/or change the background color of a modified cell and my attempts to do so so far are getting overridden by changes happening in some other event.

**Comment by swistach** [comment]
Hi @caseyredisatwork, we moved documentation into a mono-repository - to keep the reported issue closest to the code, we transferred it to https://github.com/handsontable/handsontable/issues. You can find more details in #8402.

**Comment by AMBudnik** [comment]
Now we have the `edit` button to alter the demo's logic, so I think that this issue can be closed.
