### ISSUE TITLE
Fill the description of afterSelection > preventScrolling

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8482]
Fill the description of `preventScrolling` parameter of the `afterSelection` hook.

Name | Type | Description
-- | -- | --
row | Number | Selection start visual row index.
column | Number | Selection start visual column index.
row2 | Number | Selection end visual row index.
column2 | Number | Selection end visual column index.
preventScrolling | Object | Object with value property where its value change will be observed.
selectionLayerLevel | Number | The number which indicates what selection layer is currently modified.

It just doesn't tell us much. Here's what we get after selecting a cell.
![image](https://user-images.githubusercontent.com/10757813/61286432-1e47e400-a7c3-11e9-928f-bede0d29e3b8.png)

src: https://jsfiddle.net/handsoncode/fte5qm98/

**Comment by warpech** [comment]
@kirszenbaum it seems to me that this issue should be closed since #8844 is done. Please check
