### ISSUE TITLE
Fill the possible keys for the context and dropdown menu

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8483]
As mentioned in the Handsontable repository here https://github.com/handsontable/handsontable/issues/6114 we should mention all other keys that can be used for the context menu and dropdown menu.

**Comment by AMBudnik** [comment]
@kirszenbaum I think that this issue is also no longer valid. It seems that we have it all at https://handsontable.com/docs/javascript-data-grid/context-menu/, and any of those links here work, so it's hard to specify what was in them. What do you think?

The only missing part seems to be the `submenu` (we have a demo, but options are not specified in the docs). 
But it has its own issue at https://github.com/handsontable/handsontable/issues/8541

**Comment by kirszenbaum** [comment]
@AMBudnik – yeah, let's close this one and add `submenu` in #8541.
