### ISSUE TITLE
Remove executeCommand method from documentation

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8484]
We have posted the description of possible keys that can be used by the `executeCommand` method of the `contextMenu` plugin. However, the description does not provide enough information on how to trigger those processes. 
As the following method is not able to process the operations alone (we may need to open the menu first) I assume that it should not be mentioned in the official documentation.

**Comment by kirszenbaum** [comment]
@AMBudnik

The `executeCommand()` appears in 3 places in the API ref:
- [`ContextMenu`](https://handsontable.com/docs/api/context-menu/#executecommand)
- [`DropDownmenu`](https://handsontable.com/docs/api/dropdown-menu/#executecommand)
- [`Menu`](https://handsontable.com/docs/api/menu/#executecommand)

I'm hiding all 3 in this PR: #9698 

If we should do sth else instead, please let me know here or in the PR, thanks!

**Comment by AMBudnik** [comment]
@kirszenbaum I checked the subject once again along with tests scenarios where we use the `executeCommand` method and the "missing description of how to use it" from my first post related to the need for a cell selection. I tested the following method here https://jsfiddle.net/vjzke85m/ where it works great

```js
//code
hot.selectCell(0,0,0,2);
hot.getPlugin('contextMenu').executeCommand('alignment:center');
```

outcome
![Screenshot 2022-08-02 at 10 46 49](https://user-images.githubusercontent.com/10757813/182332602-c0b6d833-4b4d-4598-b8c0-6fb1ac118113.png)

so with that results, I would rather add a line of text to the description of the method at 

http://localhost:8000/docs/next/api/menu/#executeCommand
http://localhost:8000/docs/next/api/dropdown-menu/#executecommand
http://localhost:8000/docs/next/api/context-menu/#executecommand

that states 'following method works for selected cell/cells and doesn't do anything when cells are not selected' (or something similar). 

One thing still raises my eyebrow, meaning, what are those `additional parameters
![Screenshot 2022-08-02 at 10 51 16](https://user-images.githubusercontent.com/10757813/182333543-b3969f02-c448-463f-8b3f-42080cc1bd8d.png)
but definitely, I had a change of heart regarding the deletion of the following method.

**Comment by kirszenbaum** [comment]
@AMBudnik - thanks! I updated the PR: #9698.

Regardint the "additional parameters", I suppose these are parameters related to specific context menu actions (e.g., if there's an additional parameter needed for the `'remove_row'` command, it should be added as `...params`. But I'm not sure.
