### ISSUE TITLE
Add description for datePickerConfig

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8486]
The following ticket relates to the [date demo](https://handsontable.com/docs/7.1.0/demo-date.html ) and the `datePickerConfig` object.

As it is a `datePicker` config I do not suggest to add it as an option to the documentation, even when [it's defined in the definition file](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1704).
However, I would expect to get a link to the examples or definitions of those configs. Additionally, we should inform the developers which options from the list are supported (as all, unfortunately, aren't).

**Comment by kirszenbaum** [comment]
Done in #8959 , moving do Done
