### ISSUE TITLE
The search option is missing a function tag

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8487]
The `search` function is supposed to support functions

![image](https://user-images.githubusercontent.com/10757813/62044418-2fe9ac80-b203-11e9-8810-3cc4db4fb723.png)

but we do not mention this in the tags of the option 

![image](https://user-images.githubusercontent.com/10757813/62044448-409a2280-b203-11e9-81c5-ed7599b2d1c6.png)

and it's not in the [definition file](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1764) 

![image](https://user-images.githubusercontent.com/10757813/62044518-72ab8480-b203-11e9-9aaa-cff16cfa1609.png)

**Comment by swistach** [comment]
Definition is already correct: https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1697
