### ISSUE TITLE
Missing information on type of indexes

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8494]
1) We should mention that trimming works on physical indexes in the documentation

* trimming introduction https://handsontable.com/docs/7.1.1/demo-trimming-rows.html
* method `trimRows` https://handsontable.com/docs/7.1.1/Options.html#trimRows

2) Define indexes that are used for `beforeChange`/`afterChange` hooks https://github.com/handsontable/handsontable/issues/1501 and how to get both indexes for that operation.

**Comment by AMBudnik** [comment]
We also have to change the following paragraph
> The trimRows property needs to be set to an array of row indexes to enable the plugin

in `Setup` as we can also enable the plugin by passing `true` to `trimRows`.

**Comment by kirszenbaum** [comment]
> We should mention that trimming works on physical indexes in the documentation
   trimming introduction https://handsontable.com/docs/7.1.1/demo-trimming-rows.html
    method `trimRows` https://handsontable.com/docs/7.1.1/Options.html#trimRows

Done in #9718.

> Define indexes that are used for `beforeChange`/`afterChange` hooks https://github.com/handsontable/handsontable/issues/1501 and how to get both indexes for that operation.

Done in #9718.

> in Setup as we can also enable the plugin by passing true to trimRows.

Done in #9718.
