### ISSUE TITLE
Hook afterOnCellMouseDown get wrong coords when click a mergedCell

### ISSUE THREAD

**Issue by Xianbei233** [handsontable/handsontable#8498]
### Description
Hook afterOnCellMouseDown get wrong coords when click a mergedCell,it should return the top-left cell's coords but return the down-right cell's coords

### Steps to reproduce

1. merge a cell 
2. creat a afterOnCellMouseDown hook
3. select the merged cell

### Your environment
* Handsontable version: 9.0.1
* Browser Name and version: chrome
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Thank you for reporting @Xianbei233 

I would also see the begging coordinate as the one that is returned by the hook. Or even an array of coordinates as it is returned by selection https://jsfiddle.net/tg4pkjx3/3/

@wojciechczerniak, what's your opinion?

**Comment by wszymanski** [comment]
> Thank you for reporting @Xianbei233
> 
> I would also see the first-cell coordinate as the one that is returned by the hook. Or even an array of coordinates as it is returned by selection [jsfiddle.net/tg4pkjx3/3](https://jsfiddle.net/tg4pkjx3/3/)
> 
> @wojciechczerniak, what's your opinion?

@AMBudnik For me, it's definitely a bug. Hook should inform about first visible, clicked cell. I would not extend it to array of coordinates. For me, it should be be simple coordinates as we can see within `hot.getSelectedRangeLast().highlight`.

**Comment by AMBudnik** [comment]
Great! Thank you for feedback @wszymanski 
Let's name it a `bug` then.

**Comment by aninde** [comment]
This issue will be fixed by v11.
Demo https://jsfiddle.net/aninde/vmukog04/.

**Comment by AMBudnik** [comment]
Hi @Xianbei233 I'm more than glad to inform you that the issue you reported was fixed and the new fixed version is Handsontable v11.

Here is the migration guide from v10 to v11 https://handsontable.com/docs/migration-from-10.0-to-11.0/ and if you would like to read more about the newest release here’s everything listed and described https://github.com/handsontable/handsontable/issues/8949
