### ISSUE TITLE
[HyperFormula] Update HF to v1.0.0

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#8502]
### Description

With the release of [HyperFormula v1.0.0](https://github.com/handsontable/hyperformula/releases/tag/1.0.0) we can move forward with fixing regressions and tightening the integration. To to that, we need to update current 0.6.2 version we use to latest v1.0.0.

### To do

Use [HyperFormula Migration Guide](https://handsontable.github.io/hyperformula/guide/migration-from-0.6-to-1.0.html) to update current FormulaPlugin to newest HF version.

- [ ] Update methods to use `sheetId` instead `sheetName`
- [ ] Check if we're using any "matrix" methods, errors, options (probably), update to "array" ones
- [ ] Check all methods that may now use `SimpleCellRange` instead `leftCorner`, `width`, and `height`
- [ ] Document the breaking change in formula syntax

### NON goals

Don't refactor the code with new features yet. Just update.

###  Should fix

- [ ] #8104
- [x] #8057

### Links
[HyperFormula v1.0.0 Release](https://github.com/handsontable/hyperformula/releases/tag/1.0.0)
[HyperFormula Migration Guide](https://handsontable.github.io/hyperformula/guide/migration-from-0.6-to-1.0.html)

**Comment by AMBudnik** [comment]
Note to myself: update Client on [forum](https://forum.handsontable.com/t/gh-8502-cannot-implement-hyperformula-v1-0-0-in-angular/5383)

**Comment by AMBudnik** [comment]
Handsontable v10 uses HyperFormula v1.2.0
https://github.com/handsontable/handsontable/blob/master/package.json#L101
