### ISSUE TITLE
Custom editors with different HTML attributes

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#8527]
### Description

It seems that there is a problem with using custom editor which has different attributes for different columns. I've created two columns using `HotColumn` component and tried to set `min` and `max` attributes of created DOM elements using `props`.

There has been created two HTML `inputs`, but just one of them was used.

<img width="890" alt="Screenshot 2021-07-19 at 13 03 49" src="https://user-images.githubusercontent.com/141330/126161310-37f2c473-2f3a-47f1-b8d0-6127be8a4009.png">

I've found that [`createLocalEditorPortal` method](https://github.com/handsontable/handsontable/blob/e8e8f30bbe1677cda0b2ab62e166f77b64531994/wrappers/react/src/hotColumn.tsx#L128-L135) is used twice (for each column) and it seems that there is used some kind of cache internally. Probably it's responsible for creating only one editor element for one type. It should be rethought how custom elements should be used and created.

### Steps to reproduce

1. Open a demo: https://codesandbox.io/s/declaring-a-custom-editor-as-a-component-bug-3jbwp
1. Inspect DOM
2. You can see that there are 2 elements with different `min` and `max` elements. Just one of them is focused after opening an editor (for example after double click).

**Comment by AMBudnik** [comment]
Issue closed as solved in Handsontable v11.

For everyone who would like to update from v10 I recommend the migration guide  https://handsontable.com/docs/migration-from-10.0-to-11.0/
