### ISSUE TITLE
HyperFormula gpu.js Errors

### ISSUE THREAD

**Issue by ndantonio** [handsontable/handsontable#8532]
Hello,

I'm trying to update my handsontable to latest version (9.0.0) but getting this upon starting the server:

![image](https://user-images.githubusercontent.com/20949522/126435750-b873f086-a759-431f-bdf5-ef0e6036d74d.png)

What is the problem here? Please help.

Thanks.

**Comment by swistach** [comment]
Hi @ndantonio,
Would you please verify what version of TS do you use? HyperFormula requires at least typescript@3.8 (for `import type` syntax).
If you use the older version of typescript (than 3.8), please upgrade it first and let us know if it solved building issues.

**Comment by ndantonio** [comment]
I am using 3.5.3, okay I will do that and update here. Thanks @swistach !

**Comment by ndantonio** [comment]
Hi @swistach, yes you are correct because of the TS version. Closing this ticket. Thanks!

**Comment by swistach** [comment]
I'm hyper glad it helped! 😊
Thank you for your feedback.
