### ISSUE TITLE
Summary calculations - provide some changes

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8535]
### Description
* we should mention on the start that using the summaries does not generate the empty row itself.
* The first example (demo) does not have any description. It looks like something is missing there.
* 'Nested Rows plugin' in 
> This allows many possible usages: for example, you can easily calculate a total for a group in a group parent combining this plugin with the Nested Rows plugin.

returns `404`.

* change 'ot' to 'it' in
> Takes a custom function and applies ot to the values in the specified column and row range.

* 'forceNumeric' is not well explained. We say that when used the '9a' becomes '9' but 'a9' does not. There is also no reference to that option within https://handsontable.com/docs/8.1.0/Options.html

* the 'forceNumeric' in 
> If your table doesn't contain only numeric data, you can either skip the non-numeric entries in the calculation, throw an error or try to parse them to float using the forceNumeric option.

lack code formatting

* `suppressDataTypeErrors` option could have a working demo 

* 'count' counts only cells that are 'null'. Empty string is not counted - we should let the users know.
Demo https://jsfiddle.net/AMBudnik/qbpw9rfv/ 

### Links
Summary calculations - https://handsontable.com/docs/8.1.0/demo-summary-calculations.html
support task (origin) - https://github.com/handsontable/support/issues/259

**Comment by kirszenbaum** [comment]
Related to #8538

**Comment by kirszenbaum** [comment]
- [ ] We should mention on the start that using the summaries does not generate the empty row itself.
- [ ] The first example (demo) does not have any description. It looks like something is missing there.
- [ ] 'Nested Rows plugin' returns 404 in:
> This allows many possible usages: for example, you can easily calculate a total for a group in a group parent combining this plugin with the Nested Rows plugin.

- [ ] Change 'ot' to 'it' in
> Takes a custom function and applies ot to the values in the specified column and row range.

- [ ] 'forceNumeric' is not well explained. We say that when used the '9a' becomes '9' but 'a9' does not. There is also no reference to that option within https://handsontable.com/docs/8.1.0/Options.html

- [ ] the 'forceNumeric' in 
> If your table doesn't contain only numeric data, you can either skip the non-numeric entries in the calculation, throw an error or try to parse them to float using the forceNumeric option.

lack code formatting

- [ ] `suppressDataTypeErrors` option could have a working demo 

- [ ] 'count' counts only cells that are 'null'. Empty string is not counted - we should let the users know.
Demo https://jsfiddle.net/AMBudnik/qbpw9rfv/

**Comment by kirszenbaum** [comment]
Left to do:
- [ ] We should mention on the start that using the summaries does not generate the empty row itself
- [ ] `forceNumeric` is not well explained. We say that when used the `9a` becomes `9` but `a9` does not.
- [ ] `suppressDataTypeErrors` option could have a working demo
- [ ] `count` counts only cells that are 'null'. Empty string is not counted - we should let the users know.
