### ISSUE TITLE
Change: Missing requirement for Summary calculations

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8538]
**Description:**
We should to highlighted separately in the description missing requirements for `Summary calculations`.
In HOT configuration should be spare empty row for the result of the summary calculation.
This appears in the demo, but we want to have more user-friendly docs. 

**Where:**
https://handsontable.com/docs/7.1.1/demo-summary-calculations.html

**Comment by kirszenbaum** [comment]
Related to #8535

**Comment by kirszenbaum** [comment]
This issue is a duplicate of the first item in [this issude](https://github.com/handsontable/handsontable/issues/8535#issuecomment-888205033). I'll deal with it in #8535 , closing this one
