### ISSUE TITLE
Move Selection Box?

### ISSUE THREAD

**Issue by seiyria** [handsontable/handsontable#854]
Hi, just a quick question.

Would it be possible to move a selection box from one spot to another using the box in the bottom right?

For example, moving it from [here](http://puu.sh/3toWO.png) to [here](http://puu.sh/3toY6.png) by dragging the box in the bottom right.

**Comment by AMBudnik** [comment]
Unfortunately your links are broken. I assume you want the same feature like in this issue https://github.com/handsontable/handsontable/issues/282 if not, please reply.
