### ISSUE TITLE
Numeric: comma as separator only during editing

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8547]
https://handsontable.com/docs/7.3.0/demo-numeric.html

> For example, both 500000.5, **500000,5** will be accepted. You are not able to use thousands separator in the editor. 

comma as separator can be used, but not during initialization. only when editing.

  We should add this because it may mislead users.

**Comment by kirszenbaum** [comment]
@aninde - the issue is still valid in the current docs: https://handsontable.com/docs/numeric-cell-type/#usage

I'm addressing it here: #9701.

The whole **Numeric cell type** page should be thoroughly rewritten, but it's out of scope here.
