### ISSUE TITLE
afterDeselect - false description

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8548]
src https://handsontable.com/docs/7.4.2/Hooks.html#event:afterDeselect

The description informs us that once a current cell is deselected it runs the hook.

![Zrzut ekranu 2020-03-25 o 10 02 18](https://user-images.githubusercontent.com/10757813/77519414-ba140e80-6e7f-11ea-9edb-d0845cd00786.png)

However, it runs only when no cell is selected.

Related subject https://forum.handsontable.com/t/how-is-afterdeselect-fired/4251

**Comment by kirszenbaum** [comment]
Fixed in [9724](https://github.com/handsontable/handsontable/pull/9724/files#diff-9c8662f02ad3bdda7b952d5aba2a3e3e1ee8ca2600f3bedffb0f3781022992a1R221)
