### ISSUE TITLE
Options>cells - change definition of coordinates

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8555]
### Description

We say that

> Defines the cell properties for given row, col, prop coordinates.

But prop is not the 3rd element of cell coordinates. Coordinates are described by 2 dimensions. I would change it to 

> given row, col/prop coordinates

SRC: https://handsontable.com/docs/8.1.0/Options.html#cells
The issue has been reported as a part of the handsontable/support#254 investigation

**Comment by kirszenbaum** [comment]
@AMBudnik – the new docs changed the `cells` description, I think we close the issue: https://handsontable.com/docs/api/options/#cells

**Comment by AMBudnik** [comment]
@kirszenbaum, we can and we should. Thanks for the update.
