### ISSUE TITLE
editor - description improvement

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8558]
### Description
Here's the editor description in our docs

![Zrzut ekranu 2020-10-12 o 12 49 43](https://user-images.githubusercontent.com/10757813/95738391-7224cf80-0c89-11eb-98bb-ee71b38c7940.png)

We can see that text is the only editor that does not have a page attached (and has an unnecessary comma).
The text editor is important as this is the default editor, when a cell type is not defined. We should find the best page to link it to the text editor or provide a new one.

### Links
editor docs - https://handsontable.com/docs/8.1.0/Options.html#editor

**Comment by kirszenbaum** [comment]
@AMBudnik – the issue doesn't seem relevant anymore: https://handsontable.com/docs/api/options/#editor

Can we close it?

**Comment by AMBudnik** [comment]
👍 , closing @kirszenbaum
