### ISSUE TITLE
Get currently selected cell data?

### ISSUE THREAD

**Issue by seiyria** [handsontable/handsontable#856]
There doesn't appear to be a way to get the currently selected cell data.. it'd be nice to have that. Currently what I'm trying to do is something like this: 

```javascript
	var cells = $("#table").handsontable('getSelected');
	if(cells) {
		console.log(cells);
		var inst = $("#table").handsontable('getInstance');
		console.log(inst);

//necessary because the order of the range of returned cells varies depending on how it was selected
		var iMin = cells[0] < cells[2] ? cells[0] : cells[2];
		var iMax = cells[0] > cells[2] ? cells[0] : cells[2];
		var jMin = cells[1] < cells[3] ? cells[1] : cells[3];
		var jMax = cells[1] > cells[3] ? cells[1] : cells[3];

		for(var j=jMin; j<jMax; j++) {
			for(var i=iMin; i<iMax; i++) {
				console.log(inst.getCellMeta(i, j));
			}
		}
	}
```
But here's the thing, assuming I select top-left to bottom-right, the number of ColumnSettings objects I get seems to be off by varying amounts, see [this](http://puu.sh/3tx01.png) and [this](http://puu.sh/3tx1L.png). Plus, my for() loop won't work when I select a single column/row (I could work around this, but that's not the point).

It'd really be nice to have a "getCellMetaForRange" function or something - then I could just loop through the affected cells and apply changes as necessary.

**Comment by AMBudnik** [comment]
`afterSelection` event should be an answer for your need. More about [events](https://github.com/handsontable/handsontable/wiki/Events)
