### ISSUE TITLE
enterBeginsEditing - description improvement

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8560]
### Description
We should remove the reference to other projects in the description of `enterBeginsEditing`.

### Links
* enterBeginsEditing docs - https://handsontable.com/docs/8.1.0/Options.html#enterBeginsEditing

**Comment by kirszenbaum** [comment]
@AMBudnik - this issue is no longer relevant: https://handsontable.com/docs/api/options/#enterbeginsediting

Can we close it?

**Comment by AMBudnik** [comment]
Yes, the reference is gone. I'm closing the issue as solved.
