### ISSUE TITLE
renderer - small adjustments

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8561]
### Description
I do not think that those commas and dots are necessary.

![Zrzut ekranu 2020-10-12 o 14 56 36](https://user-images.githubusercontent.com/10757813/95748982-24b15e00-0c9b-11eb-9dad-37d68a857304.png)

 Especially cause they are not used across the docs. Examples
* preventOverflow (dots only) - https://handsontable.com/docs/8.1.0/Options.html#preventOverflow
* selectionMode (dots only) - https://handsontable.com/docs/8.1.0/Options.html#selectionMode
* editor (only one dot at the end) - https://handsontable.com/docs/8.1.0/Options.html#editor
* type (only one dot at the end) - https://handsontable.com/docs/8.1.0/Options.html#type

This makes me think that we do not have any specs on how to construct unordered lists. 

### Links
renderer docs - https://handsontable.com/docs/8.1.0/Options.html#renderer

**Comment by kirszenbaum** [comment]
@AMBudnik - I think the issue can be closed: https://handsontable.com/docs/api/options/#renderer

**Comment by AMBudnik** [comment]
True, @kirszenbaum. I'm closing the issue.
