### ISSUE TITLE
data source - description improvement

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8562]
### Description
I would change the paragraph naming **Object data source with column as a function** as it indicates that my data is a function. Ad what happens in the demo is setting up `columns` option as a function.

### Links
Object data source with column as a function - https://handsontable.com/docs/8.1.0/tutorial-data-sources.html#page-column-func
Class-based data https://jsfiddle.net/623ek5zn/
support task (origin) - https://github.com/handsontable/support/issues/258

**Comment by kirszenbaum** [comment]
@AMBudnik – the issue's no longer relevant, I'd close it
