### ISSUE TITLE
Using the HotColumn component - small impovements

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8569]
### Description
* the **object data source** link does not work
![Zrzut ekranu 2020-10-19 o 14 24 44](https://user-images.githubusercontent.com/10757813/96450807-f7bef700-1216-11eb-9ecd-1bd639a3843e.png)

* the `autoColumnSize` in **note that autoColumnSize is enabled by default** should be a link to https://handsontable.com/docs/Options.html#autoColumnSize

### Links
Using the HotColumn component - https://handsontable.com/docs/8.1.0/frameworks-wrapper-for-react-hot-column.html
support task (origin) - https://github.com/handsontable/support/issues/258

**Comment by kirszenbaum** [comment]
@AMBudnik
> the object data source link does not work

That's not present in the new docs

> the autoColumnSize in note that autoColumnSize is enabled by default should be a link to https://handsontable.com/docs/Options.html#autoColumnSize

I added API ref links to every option mentioned on the page: #9704.

**Comment by AMBudnik** [comment]
Good idea, @kirszenbaum 
I'm closing this issue as done.
