### ISSUE TITLE
Using the hot-column component (Vue) - fix some issue

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8570]
### Description
* The page itself has some console errors
![Zrzut ekranu 2020-10-20 o 10 51 06](https://user-images.githubusercontent.com/10757813/96563412-365dbb80-12c2-11eb-8335-49ae912f8a78.png)

* when we use the 'EDIT' button below the 'Object data source' example we get a table that does not look the same as the one on the page.

![Zrzut ekranu 2020-10-20 o 10 53 39](https://user-images.githubusercontent.com/10757813/96563704-8c326380-12c2-11eb-8c31-4294246f95be.png)
page

![Zrzut ekranu 2020-10-20 o 10 53 48](https://user-images.githubusercontent.com/10757813/96563708-8f2d5400-12c2-11eb-93c1-849d8013483c.png)
JSFiddle

* we could add a link to the page that explains what is the **LRU** 
![Zrzut ekranu 2020-10-20 o 10 56 53](https://user-images.githubusercontent.com/10757813/96564142-0ebb2300-12c3-11eb-9553-0f9cc99f8cb2.png)

* the 'Using the renderer/editor components with v-model' demo when provided with `10` as the input value select first and second cell.
![Zrzut ekranu 2020-10-20 o 11 02 43](https://user-images.githubusercontent.com/10757813/96564695-cbad7f80-12c3-11eb-8240-6ff0b226f72d.png)

* typo - change 'addition' to 'additional' in
> To use an external editor component with Handsontable, you'll need to create an addition "bridge" component[...]

* typo - change 'in in' to 'it in'
> The editor implementation is pretty straightforward: you need to import your dependency, place in in your editor template

### Links
Using the hot-column component (Vue) - https://handsontable.com/docs/8.1.0/frameworks-wrapper-for-angular-custom-editor-example.html
support task (origin) - https://github.com/handsontable/support/issues/258

**Comment by adrianszymanski89** [comment]
@AMBudnik 

All of the issues described here are no longer replicable in the new documentation except the one regarding selecting more than one row by typing the value in `input` element. I will address that problem by limiting the `maxLength` input property to 1 character.
