### ISSUE TITLE
Change return statements for hooks in the docs

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8577]
### Description

Based on [@pnowak findings](https://github.com/handsontable/support/issues/260) I wanted to gather those that relate to the return statement of hooks.

* [`beforeRowResize`](https://handsontable.com/docs/8.1.0/Hooks.html#event:beforeRowResize) actual `Returns: {number}`, should be changed to `Returns: {number|undefined}`
* [`beforeSetCellMeta`](https://handsontable.com/docs/8.1.0/Hooks.html#event:beforeSetCellMeta), should add `Returns: {boolean | void}`
* [`beforeStretchingColumnWidth`](https://handsontable.com/docs/8.1.0/Hooks.html#event:beforeStretchingColumnWidth) actual `Returns: {number}`, should be changed to `Returns: {number|void}`
* [`modifyGetCellCoords`](https://handsontable.com/docs/8.1.0/Hooks.html#event:modifyGetCellCoords) add all the options listed in the .ts file `void | [number, number] | [number, number, number, number]`

**Comment by kirszenbaum** [comment]
Fixed here:

https://github.com/handsontable/handsontable/pull/9724/files#diff-9c8662f02ad3bdda7b952d5aba2a3e3e1ee8ca2600f3bedffb0f3781022992a1R991-R1528
