### ISSUE TITLE
Suggestions for examples

### ISSUE THREAD

**Issue by xiaota** [handsontable/handsontable#8586]
### Description

Hello, 
For some reasons, I cannot open the website [jsfiddle](http://jsfiddle.net), so can you provide another platform to store the [examples](https://handsontable.com/docs/examples/)? 
Thanks very much

**Comment by swistach** [comment]
Hi @xiaota
Thank you for your request. We plan to migrate the `Examples` section into our codebase (https://github.com/handsontable/handsontable/tree/master/examples).
Until we have done this, we can provide a particular example on codesandbox/stackblitz. Which examples do you need to preview (and let us know on what alternative platform)?

**Comment by xiaota** [comment]
@swistach Thanks a lot again~
It's wonderful

**Comment by xiaota** [comment]
@swistach I'm very happy for that you can respond my request.
Codesandbox is ok. And I need these examples:
- [How to add a background color to a newly added row](https://jsfiddle.net/handsoncode/k17rydob)
- [How to attach an animation to a cell after a value is changed](https://jsfiddle.net/handsoncode/sj1L4vwk)

Is becasue I use `afterChange` get the changed cells, and add classname on these cells, but when scroll the table, the classname disappeard, even I used `renderAllRows={true}`. I hope these examples can resolve my problems.

Thanks a lot again~

**Comment by swistach** [comment]
No problem! Below you find examples:
- How to add a background color to a newly added row
  https://codesandbox.io/s/brave-snyder-lepu9

- How to attach an animation to a cell after a value is changed
  https://codesandbox.io/s/exciting-currying-djbws

**Comment by xiaota** [comment]
That's realy a great help, resolved my problem. Thanks a lot!
