### ISSUE TITLE
[8.4.0+] NestedHeaders do not apply headers for more columns than is defined in `startCols`

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#8589]
### Description
Investigating #8587, I noticed that NestedHeaders do not apply headers configuration for some columns. I checked that, and in the result, I found a problem in a specific situation:
- we do not define `data`,
- we define more objects in `columns` than is defined in `startCols` (by default is 5),
- nestedHeaders configuration should fit our `columns` configuration,

As a result, we can see headers only for columns that do not exceed the number defined in `startCols`.
The `columns` option should have a higher priority in defining columns number than `startCols` (and Indeed, it had up to v8.3.2). In v8.4.0, we introduced a regression with the foregoing behaviour.

### Steps to reproduce
1. Go to the demo
2. Compare `columns` and `nestedHeaders` configurations with what you see.

### Demo
https://jsfiddle.net/xrh1usb3/

### Your environment
* Handsontable version: 8.4.0+
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
This issue will be fixed by v11.1.0 https://jsfiddle.net/z9njrqxp/1/.

**Comment by AMBudnik** [comment]
Issue closed as fixed in v 11.1.0
