### ISSUE TITLE
Missing support for `source` argument in `setSourceDataAtCell` if changes are an array

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#8599]
### Description
The `setSourceDataAtCell` method, similarly to `setDataAtCell`, accepts an array of changes in the first argument.
Unfortunately, we missed adding support for the `source` argument if someone used an array of changes.

At the moment, end-developers might try to use it that way:
```
setSourceDataAtCell(changes, _, __, source)
```
But only if they don't use TS, otherwise `tsc` will throw an error.

### Steps to reproduce
1. Go to the demo.
2. Compare `setSourceDataAtCell` usages.

### Demo
https://jsfiddle.net/L7re6cbw/

### Your environment
* Handsontable version: >=8.0.0
* Browser Name and version: any
* Operating System: any

Inform Zen#26759

**Comment by warpech** [comment]
Reopening as this should be closed only after the release of 12.1.3

**Comment by AMBudnik** [comment]
I'm closing this issue as done in version 12.1.3. The `source` was added to the definition of the `setSourceDataAtCell()` method.
