### ISSUE TITLE
getInstance is undefined

### ISSUE THREAD

**Issue by bottas** [handsontable/handsontable#860]
I am rendering Handsontable using render action. On the first time, when the page is rendered, all the operations work fine. The table gets loaded again using HREF url.action (to avoid loading the entire page). At this instance, the following line gives me undefined:

`container.handsontable('getInstance')`

This is happening while I try to get the current row and column during context menu click. But this method gives me the instance corrects (on the second HREF load) during afterChange event. Can you please help?

**Comment by AMBudnik** [comment]
Issue closed in lack od needed demo.
