### ISSUE TITLE
Using @handsontable/angular produces lots of optimization bailouts warnings

### ISSUE THREAD

**Issue by BlindDespair** [handsontable/handsontable#8613]
### Description

When running angular project with `@handsontable/angular` it produces lots of warning build time about optimization bailouts, can that be fixed?

### Steps to reproduce

1. Add handsontable to the project
2. Start using it
3. Run `ng serve`

### Your environment
* Angular version:10.0.1
* Handsontable version:7.4.2
* Wrapper version:5.1.1
* Browser Name and version:Chrome 92.0.4515.107
* Operating System: OS X

**Comment by AMBudnik** [comment]
Hi @BlindDespair 

Here we have a corresponding topic https://forum.handsontable.com/t/commonjs-or-amd-dependencies-can-cause-optimization-bailouts/5197

**Comment by BlindDespair** [comment]
@AMBudnik thank you for the response. I've seen that topic but I don't see a solution there. The answer there is very theoretical and does not look like something practical I could do now to have the errors gone. I feel like I am not supposed to build my own `core-js`. I would like to be able to install `@handsontable/angular` import its module and use it without seeing warnings.

**Comment by AMBudnik** [comment]
I've consulted our developer and there is not much we can do about the warnings. Those warnings only indicate that we use polyfills and it does not make your application worse in any way.

**Comment by BlindDespair** [comment]
@AMBudnik I am grateful for you asking the developer, I really appreciate it, but I think everyone who uses this module with angular would appreciate if this can be solved somehow long term, because there are quite many warning that create a lot of noise in the console which can lead to potentially missing something important and essencially is a poor Developer Experience. If your developers think that this is not an issue on your side, I would recommend them to open an issue on @angular/cli.
Or perhaps there is a different way this can be configured? For example when using `lodash` there is a similar problem, but it can be added to `"allowedCommonJsDependencies"` in `angular.json` and the warnings go away. It would be great if we could do something similar about these polyfills.

**Comment by AMBudnik** [comment]
With the current lack of hands to work (vacation time), I do not think that we have any time for additional research. However, the subject is interesting so I'll move it to Github Discussions.
