### ISSUE TITLE
Data is being corrupted when we perform some row alterations [urgent]

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8614]
### Description

Data is being corrupted when we perform some row alterations.

### Steps to reproduce

- Right-click any row e.g. “Milk Curd” and click on `Insert child row` 
- Right-click the newly added row and click Remove Row. 
- Right-click any parent e.g. “Mix” and click `Insert child row`.

Result: The recently deleted row/rows re-appear and the last item is missing _(Date Syrup)_.

![reproduction](https://user-images.githubusercontent.com/10757813/128019419-e44815ab-edb0-4189-8438-5686ae4cc51b.gif)

### Demo

https://jsfiddle.net/oyakcvjn/ v 9.0.2 - broken

### Your environment
* Handsontable version: 9.0.2
* Browser Name and version: Chrome 91
* Operating System: Windows 10

`Inform Zen # 26480`

**Comment by AMBudnik** [comment]
Thank you for fixing it @wszymanski 

I did not reproduce the issue using v10.

**Comment by aninde** [comment]
This issue will be fixed by v10 https://jsfiddle.net/wugf58eq/.
However, after step 1 header is truncated on v9.0.2 and v10. This case will be reported separately.
