### ISSUE TITLE
Error creating dynamic columns

### ISSUE THREAD

**Issue by inicio015** [handsontable/handsontable#8625]
### Description

I am using laravel and I get the data from a query and then pass it to a handsontable, I want to do something like this in the vuejs with handsontable, that is, pass it the title and the data of said column, so I save some code and I can reuse the handsontable component, when I do it the columns are empty, sorry for the mediocre code of my code but I am a newbie.
is this possible?
First of all, Thanks

### Steps

1. Step arrangement of column where is the title and name of the column
2. I receive the column and go through it in hot-column, using the :data = "item.name"

### Demo

https://jsfiddle.net/86hbumL1/57/

###  Environment
* Vue wrapper version: 2.6.14
* Handsontable version: 9.0
* handsontable/vue version: 5.1.0
* Browser Name and version:  Google Chrome V92.0.4515.131
* Operating System: Windows 10 pro

**Comment by AMBudnik** [comment]
Hi @inicio015 

I do not have any experience with Laravel. But when it comes to the dynamic header setup you can use the `afterGetColHeader` callback further explained in the documentation https://handsontable.com/docs/api/hooks/#aftergetcolheader

If that wouldn't help please contact me at support@handsontable.com to discuss some additional approaches to resolve that requirements.
