### ISSUE TITLE
what does cell property actually contains

### ISSUE THREAD

**Issue by dlinah** [handsontable/handsontable#8626]
### Description
I've been trying to get a full description of what column/cell's property object contains, so can get an understanding of what I can change in columns, but I didn't find it anywhere, looked for "cell property", "cell's meta", search the API reference and even the library types.

### Links
https://handsontable.com/docs/api/options/#columns
https://handsontable.com/docs/disabled-cells/#read-only-columns

**Comment by AMBudnik** [comment]
Thank you for your valuable feedback @dlinah 

We have defined the task to fill the needed information within this issue report https://github.com/handsontable/handsontable/issues/8476

As this topic covers the same case I need to close it. But I will make sure to inform you once we add the information.

In the meanwhile I invite you to discuss the details of available `columns` options on emails. You can reach me at support@handsontable.com
