### ISSUE TITLE
Column header alignment slightly off sometimes

### ISSUE THREAD

**Issue by mikeyrt16** [handsontable/handsontable#8627]
### Description
We are consuming handsontable in its simplest form in React (not sure if it's React wrapper related) like:

```
<Table
    columns={columns}
    data={data}
 />
```

And we get column header alignment issues like this

![image](https://user-images.githubusercontent.com/10453522/128783042-b198ab6b-890f-40e6-97e9-1066bd852d17.png)

Is this a known issue. Do you know why this happens and what we need to do to avoid it?

### Steps to reproduce
Intermittent. Unsure what is required to reproduce.

### Your environment
* React wrapper version: 8.4.0
* Handsontable version: 8.4.0
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hi @mikeyrt16 

The most probable cause is an interaction in the CSS settings.
It might be related to styles attached to Handsontable but also some external CSS settings that overwrite table's settings.

**Comment by AMBudnik** [comment]
Hi @mikeyrt16 

As there are no updates on the subject, I'm closing this issue.
If you are still having the same issue, please share the implementation details with me at support@handsontable.com
