### ISSUE TITLE
Can I cancel merging cell?

### ISSUE THREAD

**Issue by StephenChips** [handsontable/handsontable#8628]
### Description

I saw the hooks `beforeChange` can return `false` to cancel all edits to a cell, do cell merging has same feature?

**Comment by AMBudnik** [comment]
There is a hook called `beforeMergeCells` but at the moment it does not provide an ability to block merging. You also get the information of the cellmeta change within the `beforeSetCellMeta` that also cannot be blocked.
Currently, to block the merging you would need to inject your custom checking mechanism depending on the method of merging (content menu, custom logic appended to a button, etc.)

If you'd like to discuss some of the options please feel free to send me the request to support@handsontable.com
