### ISSUE TITLE
Docs: add security certificate

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#8633]
On [this](https://handsontable.com/docs/security/#security-certification) page, add the PDF with the security certificate:

[Security_certificate.pdf](https://github.com/handsontable/handsontable/files/6967577/Security_certificate.pdf)

https://handsontable.com/docs/security/#security-certification

**Comment by warpech** [comment]
@AMBudnik it seems to me that this issue should be closed. Please check.

**Comment by AMBudnik** [comment]
@warpech confirmed. The certificate is already online. I'm closing this issue.
