### ISSUE TITLE
[9.0.1+] When we update data using `NOW()` or `TODAY()` formulas an `Uncaught TypeError` is thrown during cell edition 

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8634]
### Description

When we update data using formulas an error 
> Uncaught TypeError: Cannot read property 'validateCell' of undefined

is thrown during cell edition.

Important: I haven't found any other formulas than `TODAY` and `NOW` causing this problem.

### Steps to reproduce

1. Open the console
2. Edit any cell

**Result**
![error_](https://user-images.githubusercontent.com/10757813/129023637-513e669a-cfd9-487b-b29f-6903c2e6b49f.gif)

### Demo

https://jsfiddle.net/u8615exj/8/ 9.0.0 - works well
https://jsfiddle.net/u8615exj/11/ 9.0.1 - broken

### Your environment
* Handsontable version: 9.0.1+
* Browser Name and version: Chrome 91
* Operating System: Windows 10

_Inform zen 26826_

**Comment by sequba** [comment]
Duplicate of #8268. Fixed in [v2.0.1](https://github.com/handsontable/handsontable/releases/tag/12.0.1). @AMBudnik it should be closed.

**Comment by AMBudnik** [comment]
True. I've updated the demo to the latest version https://jsfiddle.net/q1uLdjne/1/ where this issue does not occur. Thank you for the update, @sequba
