### ISSUE TITLE
Issue with filter option

### ISSUE THREAD

**Issue by rorramesh** [handsontable/handsontable#8635]
### Description
I am using handsontable update settings method on afterchange event. When I am clicking on filters 1st time its loading fine. After that design got disturbed and filters are overlapping.

### Steps to reproduce

1.
![image](https://user-images.githubusercontent.com/86957525/129032899-c92d9d12-3001-40eb-8bd5-4f1bf201c8b2.png)
2.
![image](https://user-images.githubusercontent.com/86957525/129033042-af574d11-ebcc-49f5-be09-29e61d9edc8c.png)

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @rorramesh 

Could you share an updated demo (the one that is loaded in your first post is the default demo) with your settings?

Only then we will be able to replicate the issue, debug and share some updates.

**Comment by rorramesh** [comment]
@AMBudnik Thank you so much for your response, I will update the fiddle and let you know.

**Comment by rorramesh** [comment]
@AMBudnik  I have added demo in fiddle and issue is not reproducing. I think I have issue with my existing css.
