### ISSUE TITLE
Cell editor takes up full width when parent element is a flexbox

### ISSUE THREAD

**Issue by krishraghuram** [handsontable/handsontable#8637]
### Description

When the parent element of a handsontable is a flexbox in vertical direction, then when editing the cell, the editor textarea is larger than the cell, and takes up all the space till the right edge of the table.

### Steps to reproduce

1. Create an html element with `display: flex; flex-direction: column;`.
2. Add a child div to it.
3. Setup handsontable on the child div.
4. Double click on any cell to edit the cell.
5. The cell editor's width is more than the cell width. In fact, the cell editor takes up all the space till the right edge of the table.

### Demo

https://jsfiddle.net/krishraghuram/54jm1rs9/

### Your environment
* Handsontable version: 9.0.2
* Browser Name and version: Chrome 84.0.4147.89
* Operating System: Linux

**Comment by swistach** [comment]
Hi @krishraghuram,
Thanks for reporting. That bug is already reported in #3815, so I close your issue because it's a duplicate.

**Comment by aninde** [comment]
@krishraghuram this issue will be fixed by the upcoming v12.2 https://jsfiddle.net/krishraghuram/54jm1rs9/.
