### ISSUE TITLE
The description of `persistentStateLoad` and `persistentStateSave` is not fully correct

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8638]
### Description

Both of those hooks are stating that they are called only when `persistentState` is enabled. However, even if `persistentState` is set to `false` those hooks are triggered.

### Links

1. `persistentStateLoad` - https://handsontable.com/docs/api/hooks/#persistentstateload
2. `persistentStateSave` - https://handsontable.com/docs/api/hooks/#persistentstatesave

Inform [forum](https://forum.handsontable.com/t/gh-8638-the-hook-persistentstatesave-is-called-even-when-the-option-persistentstate-is-set-to-false/5440)

**Comment by kirszenbaum** [comment]
Fixed in #9709.
