### ISSUE TITLE
Docs: rewrite the "Column summary" topic

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#8655]
Rewrite the [Column summary](https://handsontable.com/docs/column-summary/) topic.

Topic plan:
- Overview/About
  - Example
- Setting up column summary
  - Step 1
  - Step 2
  - Step 3
  - Result
- Additional options

Add links to the API ref (for options, methods, and plugins).

**Comment by warpech** [comment]
@AMBudnik it seems to me that this issue should be closed. Please check.

**Comment by kirszenbaum** [comment]
@warpech @AMBudnik this issue is done, closing
