### ISSUE TITLE
White space eclipses header when opening dropdown menu in the iframe

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8658]
### Description

When I open the dropdown menu in the [Hello World App]() in the Handsontable guides, it causes an appearance of white space in the top right corner placed directly on multiple headers.

This bug appears in an `iframe` (Codesandbox). I couldn't reproduce it in other conditions, for example outside the `iframe`.

### Steps to reproduce

1. Run any demo at https://handsontable.com/docs/hello-world/
2. Open the dropdown menu for column 1
3. Open the dropdown menu for column 2
4. Notice the white space in the top right corner

### Demo

https://handsontable.com/docs/hello-world/

https://user-images.githubusercontent.com/8048526/130052635-8bdc7a9c-367e-4457-9979-2a3bef2f00f8.mov

### Your environment
* Handsontable version: 9.0.x
* Browser Name and version: Chrome 92
* Operating System: macOS BigSur 11.2

**Comment by krzysztofspilka** [comment]
Also, the scrollbar handle hides under Handsontable's header.
<img width="210" alt="Screen Shot 2021-08-24 at 16 18 02" src="https://user-images.githubusercontent.com/8048526/130633394-98c14d2b-1001-4ff7-959c-332e6182f348.png">

**Comment by budnix** [comment]
Closing as duplication of https://github.com/handsontable/handsontable/issues/8658.
