### ISSUE TITLE
Delete removed core methods from definition file: `rowOffset`, `colOffset`

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8659]
### Description

In Handsontable v8.0.0 we made the following change

> `rowOffset` and `colOffset` were removed since they aliased the methods from Walkontable. #6547

However, we did not remove the methods from the definition file.

Release notes https://handsontable.com/docs/release-notes/#_8-0-0

### Your environment
* Handsontable version: 8+
* Browser Name and version: n/a
* Operating System: n/a

**Comment by warpech** [comment]
Reopening as this should be closed only after the release of 12.1.3

**Comment by AMBudnik** [comment]
I'm closing this issue as done and released in Handsontable v12.1.3
