### ISSUE TITLE
Remove the default clipboard limits

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8660]
### Description

I noticed that in some cases the limit we put on the clipboard capacity might be problematic for end users, especially those who expect that the grid's behavior is similar to popular spreadsheet/grid software.

To ease that pain, let's remove the default limits defined in `columnsLimit` and `rowsLimit`. They should copy an unlimited number of rows and columns.

**API:**
- https://handsontable.com/docs/api/copy-paste/#columnslimit
- https://handsontable.com/docs/api/copy-paste/#rowslimit

**Comment by AMBudnik** [comment]
Done in v10. We can easily paste more than 1000 copied rows https://jsfiddle.net/qznxf1gc/5/
