### ISSUE TITLE
Add a default font size, color and family

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8661]
### Description

I noticed the inconsistency in CSS properties. For instance, we declare the specific styles of headers, selection, menus, etc. but at the same time, we miss such basic properties as a `font-family` and `font-size`.

Our goal is to make sure, that the default instance of Handsontable deployed on a clean page will look attractive without any extra work needed from the developer.

New global styles (make sure they apply to menus - context, column, dropdown) and accessories such as license key notification are provided below:
```
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Helvetica Neue", Arial, sans-serif;
font-size: 13px
font-weight: normal
color: #373737
```

Links color (`<a>`)
`color: #104acc`

### Result preview:
<img width="623" alt="Screen Shot 2021-08-19 at 15 00 50" src="https://user-images.githubusercontent.com/8048526/130072776-c37fa9f2-f6ea-416b-9f2f-c2f222f1b9d7.png">

Consider removing additional styling from code snippets in our docs:
https://github.com/handsontable/handsontable/blob/master/docs/.vuepress/theme/styles/handsontable.styl

**Comment by AMBudnik** [comment]
Changed in Handsontable v10
