### ISSUE TITLE
Change the default settings of autoWrapCol and autoWrapRow

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8662]
### Description

When a user unintentionally presses the <kbd>arrow up</kbd> or <kbd>arrow left</kbd> while being in cell 0,0 (A1), the selection jumps to the last cell in the last column. It is kind of annoying and I would like to change the default behavior of the two options responsible for it.

**Let's change `autoWrapCol` and `autoWrapRow` default setting to `false`.**

https://handsontable.com/docs/api/options/#autowrapcol
https://handsontable.com/docs/api/options/#autowraprow

**Comment by aninde** [comment]
This change is introduced by v10.
