### ISSUE TITLE
[Angular v9.0.2+]The `console.warn()` is thrown each time the `getInstance` method is called

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8664]
### Description

The `console.warn()` is thrown each time the `getInstance` method is called.

Warning message
> The Handsontable instance bound to this component was destroyed and cannot be used properly.

### Steps to reproduce

1. Open console log (the method is called via `afterInit` hook)

### Demo

https://jsfiddle.net/opj7gr3b/ - 9.0.2 - shows warning
https://jsfiddle.net/opj7gr3b/3/ - 9.0.1 - does not show the warning

### Your environment
* Angular version: 9.0.2
* Handsontable version: 9.0.2
* Wrapper version: 9.0.2
* Browser Name and version: Chrome 91
* Operating System: Windows 10

Update Zen 26981, 26900 and GH, and [forum](https://forum.handsontable.com/t/afteinit-hook-not-returning-table-instance-angular/5463/4)

**Comment by AMBudnik** [comment]
I've connected the PR that relates to the introduction of this regression - https://github.com/handsontable/handsontable/pull/8313

**Comment by Siemienik** [comment]
done in #8712
