### ISSUE TITLE
onHover - Drag and Drop support

### ISSUE THREAD

**Issue by mariotacke** [handsontable/handsontable#867]
Hello,

I know i'm asking for quite a bit with this "simple" question, however, I was wondering if there is a working implementation of a drag and drop out there?
In a perfect world, I would like to have 2 Handsontables and be able to drag a single cell from one table to the next. 

I am currently experimenting with JQuery Draggable/Droppable, however, it is not returning the desired results.

http://jqueryui.com/draggable/
http://jqueryui.com/droppable/

Any advice would be great!

Thanks for this great plugin!
Mario

**Comment by AMBudnik** [comment]
More information about this subject please track changes to https://github.com/handsontable/handsontable/issues/1608 issue.
