### ISSUE TITLE
Performance issues when rerendering the component without making any changes to it

### ISSUE THREAD

**Issue by danielpza** [handsontable/handsontable#8674]
### Description

Rerendering the handsontable react component without changing any parameters causes a performance lag, most noticeable with larger datasets. Since nothing was changed I expect it to not have any performance issues at all.

Here is a video with a lag radar, notice I didn't change any of the data, only caused a rerender in the react component

https://user-images.githubusercontent.com/17787042/130703924-0a169460-fa1a-43ff-8d67-ea9035328781.mp4

Code:

```tsx
import { HotTable } from '@handsontable/react';
import 'handsontable/dist/handsontable.full.css';
import React, { useState } from 'react';
import Handsontable from 'handsontable';

const data = Handsontable.helper.createSpreadsheetData(5000, 100);

export default function Default() {
	const [, setState] = useState({});
	const rerender = () => setState({});
	return (
		<div id='example-component'>
			<button onClick={rerender}>rerender</button>
			<HotTable width='100%' height='100%' licenseKey='non-commercial-and-evaluation' data={data} />
		</div>
	);
}
```

### Steps to reproduce

- create a spreatsheet data with more than 10000 rows and pass it to the handsontable component, 
- cause a rerender in the react tree

### Demo

https://jsfiddle.net/n7xqoyzv/

increase the number of rows to notice more lag

### Your environment
* React wrapper version: 9.0.2
* Handsontable version: 9.0.2
* Browser Name and version: Firefox 
* Operating System: Ubuntu Linux

**Comment by AMBudnik** [comment]
Hi @danielpza 

Thank you for the report.

I think that we have everything listed here https://github.com/handsontable/handsontable/issues/8372 but if you think that we should add some tests scenarios to that issue please feel free to leave a comment.

**Comment by AMBudnik** [comment]
We will update this topic after fixing https://github.com/handsontable/handsontable/issues/8372

**Comment by AMBudnik** [comment]
Hi @danielpza 

we just released [Handsontable v12](https://handsontable.com/docs/release-notes/#_12-0-0). Could you please update and let us know if it improves the performance in your case?
