### ISSUE TITLE
Generating API reference od documentation fails on Windows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8677]
### Description

While testing changes to the docs made by @kirszenbaum I found out that the command

>npm run docs:API

of https://github.com/handsontable/handsontable/blob/master/docs/README.md#getting-started-with-handsontable-documentation (2nd step) produces errors on my Windows 10 machine (I have also tested it with macOS Catalina where it works well).

Here is the outcome of `npm run docs:API`

![error1](https://user-images.githubusercontent.com/10757813/130770274-e5f9166f-e27e-4702-a4f6-796a11e57d8a.png)

![error_final](https://user-images.githubusercontent.com/10757813/130770616-7b49ea26-2ed2-44ea-9bdc-acca2cc9d79f.png)

Then in the next step `npm run docs:start` we are informed by https://github.com/handsontable/handsontable/blob/develop/docs/.vuepress/docs-links.js#L23 that there are missing files

![missing_files](https://user-images.githubusercontent.com/10757813/131133683-24ea4f33-3aa4-414f-99c8-a978e565a81f.png)

In the result, the /docs are build however linking result in `404` (take a look at the generated URL)

![browser_404](https://user-images.githubusercontent.com/10757813/130771029-3804ea34-5ae5-4d5b-a96c-a2476fb2609d.png)

### Testing environment
* System: Windows 10
* Browser: Chrome 91
* Node: 14.7.0 with npm 7.10.0 (also does not work with node 16.3.0)

**Comment by AMBudnik** [comment]
@aninde please check it out in your spare moment

**Comment by AMBudnik** [comment]
Thanks for checking and confirming @aninde

**Comment by warpech** [comment]
Closing as fixed in #9163
