### ISSUE TITLE
Guide - Formula calculation - Incorrect URL to Formulas plugin

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#8695]
### Description
The URL to the `Formulas` plugin, which you can find in the tip box right after the page's title, points to the not existing resource.

### Links
https://handsontable.com/docs/formula-calculation/
https://github.com/handsontable/handsontable/blob/master/docs/next/guides/formulas/formula-calculation.md?plain=1#L22

**Comment by kirszenbaum** [comment]
The issue is no longer there: https://handsontable.com/docs/formula-calculation/

Closing.
