### ISSUE TITLE
[9.0.2] NestedRows is not working in updateSettings

### ISSUE THREAD

**Issue by gianadrias** [handsontable/handsontable#8697]
### Description
I tried to change row data to nestedrows after init of handsontable and it's not working.

### Steps to reproduce

1. Initialize table
2. add function after init
3. set nestedrows to true and update data.

### Demo
https://jsfiddle.net/sqrm4e2t/3/

### Your environment
* Handsontable version: 9.0.2
* Browser Name and version: Chrome
* Operating System: Any

**Comment by AMBudnik** [comment]
Hi @gianadrias 

Thank you for sharing the bug report.

This issue has been already addressed in https://github.com/handsontable/handsontable/issues/7510 under issue **no.8**
As we do not want to duplicate issues I will close this one and set myself a reminder to notify you once we solve the issue.
