### ISSUE TITLE
Display handsontable on full window (without stretching) with column resize enabled.

### ISSUE THREAD

**Issue by Naveen-Bhat** [handsontable/handsontable#870]
I would like to use this tool in one of our project. I was doing some experiment with the features. Its really an awesome tool. However, I have few questions regarding one of the feature which is asked by our client.

How to display the handsontable on full window without stretching-out the columns?
According to the document, I can display on full screen using "stretchH: 'all'" but if this is the case, then I wont be able to resize the columns smoothly. Hence I don't want to stretch the columns.

I tried to accomplish with various ways but of no use. Here is one of the way: http://jsfiddle.net/knvn/u7nYk/

as you can see, it displays a gap between the scrollbar and grid/table content. Also, I would like to have a horizontal scroll bar on the window rather than the grid itself. I placed two textarea's to demonstrate this. It will be appreciable, if I could get the  same column resizing behaviour in handsontable.

Please let me know, if you are not able to get my question.

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity and no unresolved questions.
