### ISSUE TITLE
Import from `../dataMap` in `dataMap/index` is incorrectly resolving in Liferay's tool

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#8704]
### Description
Currently, our `dataMap/index` reexports DataMap class from the upper directory (by importing it from `../dataMap`).
Some tools, such as [Liferay](https://help.liferay.com/hc/en-us/articles/360018181631-Configuring-liferay-npm-bundler) used by our clients, interpret `../dataMap`, as a reference to the directory not to file:
```
./core
  import { ... , DataMap } from './dataMap/index'

./dataMap/index
  import DataMap from '../dataMap' // translated as `../dataMap/index`
```
`../dataMap/index` has no default export, ending with the hidden problem in `./core` because DataMap will be `undefined`.

Then, when Handsontable initializes a new instance, the `load()` method tries to create a `new undefined`.

### Steps to reproduce
1. Build package including Handsontable using `liferay-npm-bundler` with presets for `angular`
2. Deploy `*.jar` package as a Liferay's portlet

There are no demo - either `steps to reproduce` requires the whole env to run, and supposedly we will not be able to reproduce that issue.

### Client's environment
* Handsontable version: 8.4.0+
* Browser Name and version: any
* Operating System: any
* node: 10.24.1
* npm: 6.14.12

**Comment by aninde** [comment]
This issue will be fixed by v10. Tested locally.
