### ISSUE TITLE
HotRegisterer.getInstance falsely reports destruction of instance

### ISSUE THREAD

**Issue by john-swallow-cenduit** [handsontable/handsontable#8707]
### Description
Following the release of 9.0.2 and the fix for #8313 HoT reports the warning: "The Handsontable instance bound to this component was destroyed and cannot be used properly." whenever HotRegisterer.getInstance() is called. It does this even when the instance is new and untouched.

### Steps to reproduce
1. Open your own Angular example from the documentation here; https://handsontable.com/docs/angular-hot-reference/
2. Click the Load Data button
3. View the console data

Expected: no warning in the console
Actual: console has warning: "The Handsontable instance bound to this component was destroyed and cannot be used properly."

### Demo
https://jsfiddle.net/ehray5f7/

### Your environment
* Angular version: 8
* Handsontable version: 9.0.2
* Wrapper version: 9.0
* Browser Name and version: Chrome Version 93.0.4577.63 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @john-swallow-cenduit 

I believe that this is the same issue as described here https://github.com/handsontable/handsontable/issues/8664 
Please confirm.

**Comment by john-swallow-cenduit** [comment]
I concur.

**Comment by AMBudnik** [comment]
Thank you for the prompt reply. 
As this report covers the same case, I need to close it as a duplicate. But I will update you as soon as we fix the issue.
