### ISSUE TITLE
SUMPRODUCT with +3 arrays results with N/A

### ISSUE THREAD

**Issue by bjorngrundtalf** [handsontable/handsontable#8711]
I'm using handsontable with hyperformula to recreate an economic model in web interface. While recreating the calculations I realised that SUMPRODUCT supports only two arrays as inputs when documentation shows  this example:

SUMPRODUCT(Array1; Array2...Array30)

Each time when I try to input different amount of arrays than two I receive 'N/A' as an output. Is there any trick to make it work with more arrays?

**Comment by AMBudnik** [comment]
I'm closing this topic as it is already reported at https://github.com/handsontable/hyperformula/issues/810
