### ISSUE TITLE
How to Load and Save Data to a MySql Database Table

### ISSUE THREAD

**Issue by cihat74** [handsontable/handsontable#872]
Hi,

I am certainly in need of that perfectly suiting system for my project. But I couldn't find an example about how to make that work with mysql after a lot of searches. There is an example for MySqllite but I don't know what strings to change.

Could anyone help me? A fully working example would be great indeed.

**Comment by Fahri28** [comment]
Hi @warpech 
i'm new using handsontable and interest to use handonstable in my personal project, after we open the url you have shared, seem to be unavailable, so i want to know how to save and load the data from mysql database using php in handsontable

thanks in advance

**Comment by AMBudnik** [comment]
Hi @Fahri28 
Here's a working link https://github.com/handsontable/handsontable/blob/0.35.0/demo/php/functions.php
