### ISSUE TITLE
SUM function returns wrong values when used in some columns

### ISSUE THREAD

**Issue by bjorngrundtalf** [handsontable/handsontable#8730]
While debugging calculation I realised the SUM function returns different values when I use it in different columns. In the example below row 222 supposed to be a sum of rows 219:220 from the same column. Sample format of this function: "=SUM(G$219:G$220)"

![image](https://user-images.githubusercontent.com/87017952/133861098-405a332b-279a-4ea4-a120-9d60bed5f74e.png)

![image](https://user-images.githubusercontent.com/87017952/133861208-7275fe8d-a4a5-420e-9df3-d4aea11a74eb.png)

As you see, values in column F and G are different for no particular reason - considering I do not miss anything here. I tried to test multiple cases and this issues doesn't alway apply to the same columns.
Would you be able to advise what might be causing this?

---
I'm using:
- Google Chrome 93.0.4577.82 (64bit)
- Handsontable: 9.0.2

**Comment by bjorngrundtalf** [comment]
Hi Krzysztof,
Here is a demo:
https://codesandbox.io/s/floral-smoke-12j6d?file=/index.html

I struggle to recreate it in a small sample, hence that there are so many cell and calculation. The problem is illustrated in the Calculations sheet in cells "H220", "I220", "J220". At first I thought there's some issue with overall calculations, however, if you manually overwrite the input cells the problem still appears.

It would be rgeat to hear if you know what might be causing this.

**Comment by AMBudnik** [comment]
Hi @bjorngrundtalf 

In your example, columns `H`, `I`, and `J` are holding the same `SUM` syntax, but they refer to cells with different data origins:

- Cell `H221` sums `'Model Parameters'!E80` with 'Model Parameters'!E81;
- Cell `I221` sums `'Model Parameters'!E84` with 'Model Parameters'!E85;
- Cell `J221` sums `'Model Parameters'!E88` with 'Model Parameters'!E89;

and those cells within the `Model Parameters` sheet hold different values 

![image](https://user-images.githubusercontent.com/10757813/134007241-415f4e3b-f529-45e1-bf8e-e1d7511b0d08.png)

When I run your example, all those values seem to recalculate correctly.

![data](https://user-images.githubusercontent.com/10757813/134006914-aa9d2665-5bb9-40fa-8f8e-eb7928f046ae.gif)

So I assume that something in your code blocks the proper recalculation of all of the cells. However, as it works in the demo, it is hard to say what causes this issue.

**Comment by AMBudnik** [comment]
Hey @bjorngrundtalf I'm closing this issue as there are no updates after my last comment. But if you'd have any further questions or need guidance you can reach me at support@handsontable.com
