### ISSUE TITLE
Copy Paste to SAP

### ISSUE THREAD

**Issue by Pulsar7377** [handsontable/handsontable#8731]
Description:

When you paste cells into SAP, in the last column, only the last row is being properly pasted.
I was hoping it was related to the issue   #5826 and fixed in 7.1.0 but unfortunately no.

here is what is happening;

![image](https://user-images.githubusercontent.com/35552426/134077042-ba7c0894-b98f-4f36-a1ed-12770840b75e.png)

cells pasted in SAP

![image](https://user-images.githubusercontent.com/35552426/134077216-7a061c64-f154-4a70-aef8-e72da1f9d3de.png)

if I select the empty column to the right 

![image](https://user-images.githubusercontent.com/35552426/134077369-49684058-83cb-4bd0-ad56-65bc92640b4e.png)

it shows the column with the 3 so it happens only for the last column.

![image](https://user-images.githubusercontent.com/35552426/134077544-fdb84859-e0b8-487a-acbd-b1cdf5021c39.png)

I am using the latest version, I tried to use the version 7.1.0 to see if this got broken in earlier version but it did not work properly either.

Thanks

**Comment by Pulsar7377** [comment]
Following up on my issue. Thanks to rudacs and his recommendation about adding the  \r in  #5826 , I have added  \r in the library SheetClip.js , After rebuilding, everything is working properly and the cells are pasted properly in SAP.

just changing this

`    if (r !== rLen - 1) {
      str += '\n';
    }
  }
`
to this

`    if (r !== rLen - 1) {
      str += '\r\n';
    }
  }
`

easy fix :-)

**Comment by AMBudnik** [comment]
Hi @Pulsar7377 

Thank you for the swift update! 
I just have one question: what do you mean by SAP? We have an improvement suggestion with the `\r` but we do not have full information on how to replicate the issue.
