### ISSUE TITLE
Want to add a column of same type date and it is being rendered after clicking on existing column date using context menu or filter and dropdown but it not working

### ISSUE THREAD

**Issue by Shinkey** [handsontable/handsontable#8740]
### Steps to reproduce

1.
2.
3.

### Demo
.ts
tableSettings: any = {
    viewportColumnRenderingOffset: 27,
    viewportRowRenderingOffset: 'auto',
    colWidths: 250,
    height: 450,
    columnSorting: true,
    //width: 1000,
    maxRows: 22,
    dropdownMenu: true,
    contextMenu: true,
    filters: true,
    rowHeaders: true,
   manualRowResize: true,
    manualColumnResize: true,
    licenseKey: 'non-commercial-and-evaluation',
    colHeaders: ['ID', 'ResourceName', 'Role', 'Date', 'Total Hours'],
    columns: [
      {
        type: 'numeric'
      },
      {
        type: 'dropdown',
       source: ['Euro', 'Ringmi']
      },
      {
        type: 'autocomplete',
       source: ['EUR' , 'AUS', 'ZEN']
      },
      {
           type: 'date',
           dateFormat: 'MM/DD/YYYY',
          },
          {}
    ],
    manualRowMove: true,
    manualColumnMove: true
  };
  dataset = Handsontable.helper.createSpreadsheetData(10, 5);
.html
<hot-table
  [settings]="tableSettings"
  [data]="dataset"></hot-table>
//below are stackblitz link
https://stackblitz.com/edit/handsontable-angular-fi5ddj?file=app/app.component.ts
https://handsontable-angular-fi5ddj.stackblitz.io

### Your environment
* Angular version: 7.23.0
* Handsontable version:9.0
* Wrapper version:
* Browser Name and version:chrome
* Operating System: Windows 64

**Comment by AMBudnik** [comment]
Hi @Shinkey 

If you would like to add any column via the context menu while using `columns` option you need to create a custom option. Here https://jsfiddle.net/w68kmxrL/ is an example of how to add a custom option. In your example, you may read the type of the selected column and then expand your `columns` with a new column of the same type.

ps. generally, we keep Github as a place to share bugs and feature ideas. If you have any questions regarding this or other functionalities feel welcome to send us a message to support@handsontable.com
