### ISSUE TITLE
How to add date-picker/date as a header of a column using hot-column

### ISSUE THREAD

**Issue by Shinkey** [handsontable/handsontable#8743]
### Steps to reproduce

1.
2.
3.

### Demo

https://stackblitz.com/edit/handsontable-angular

### Your environment
* Angular version:7
* Handsontable version:9
* Wrapper version:
* Browser Name and version:chrome
* Operating System:windows

**Comment by AMBudnik** [comment]
Hi @Shinkey 

as mentioned in our previous conversation as https://github.com/handsontable/handsontable/issues/8740 
>If you have any questions regarding this or other functionalities, feel welcome to send us a message to support@handsontable.com 

To answer your question, I would need to be provided with more details about your implementation.
