### ISSUE TITLE
How to add a datepicker/date to a header of a column with hot-column

### ISSUE THREAD

**Issue by Shinkey** [handsontable/handsontable#8744]
### Steps to reproduce

1.
2.
3.

### Demo

https://stackblitz.com/edit/handsontable-angular-sf4z58?file=app/app.component.ts
https://handsontable-angular-sf4z58.stackblitz.io

### Your environment
* Angular version:7
* Handsontable version: 9
* Wrapper version:
* Browser Name and version:chrome
* Operating System:window

**Comment by AMBudnik** [comment]
This issue is a duplicate of https://github.com/handsontable/handsontable/issues/8743 so it has to be closed.

Please see the comment under https://github.com/handsontable/handsontable/issues/8743 for guidance.

Thank you.
