### ISSUE TITLE
Possible deprecation method warnings

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8748]
### Description

After installing a new project using React CLI I got two warnings related to the deprecation of React hooks.

We should check if there's a way to avoid showing those warnings without breaking the backward compatibility for older React versions.

Warnings that appear

 ```
react-dom.development.js:67 Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: HotTable
```

```
react-dom.development.js:67 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: HotTable
```

### Your environment
* React wrapper version: 9.0.2
* Handsontable version: 9.0.2
* React version: 17.0.2
* Browser Name and version: Chrome 94
* Operating System: Windows 10

Inform [Zen](https://handsontable.zendesk.com/agent/tickets/28139), and [Zen](https://handsontable.zendesk.com/agent/tickets/28795)

**Comment by AMBudnik** [comment]
@aninde, can you help me check which versions of React show the same notification and if there's a difference for a production build?

**Comment by warpech** [comment]
This issue will be prioritised as `componentWillMount` and `componentWillUpdate` continue to give worrying warnings to the users: https://www.reddit.com/r/reactjs/comments/ssn0t1/adding_a_non_react_library/hwyw0uv/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by warpech** [comment]
Since React 16.3, the proper name for these methods are `UNSAFE_componentWillMount` and `UNSAFE_componentWillUpdate`. It feels that it is enough to use the new method names to address this issue.

**Comment by jakub-bao** [comment]
+1

I am facing this issue as well. Although, it's only a warning message, it happens to spam my test reports.
This warning appears in my test report dozens of times.

If you are facing the same issue you can temporarily suppress the warning by overriding your test command in `package.json`
```
"scripts":{
    "test": "react-scripts test --silent",
 }
```

However, this will hide all warnings. Which are more often than not useful to be noticed. So I vote for a better fix as well.

**Comment by warpech** [comment]
We will soon rename the methods, thanks for your patience. In React 18, the warning is a bit stricter:

```
"Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: %s", "HotTable"
```

**Comment by AMBudnik** [comment]
Thank you for fixing the issue. We no longer get those warnings after updating to Handsontable v12.1.0.

<img width="788" alt="Screenshot 2022-06-28 at 13 45 55" src="https://user-images.githubusercontent.com/10757813/176170551-05e11628-9fc7-4df5-8a71-1e9dfc9b3a34.png">


I'm closing this issue as solved.
