### ISSUE TITLE
getCell error

### ISSUE THREAD

**Issue by tamtakoe** [handsontable/handsontable#875]
getCell(row, col) make error (v.0.9.9):
<pre>Uncaught TypeError: Cannot read property 'cellCount' of undefined jquery.handsontable.full.js:8806
WalkontableTable.getLastVisibleRow jquery.handsontable.full.js:8806
WalkontableTable.isRowAfterViewport jquery.handsontable.full.js:8819
WalkontableTable.getCell jquery.handsontable.full.js:8781
Handsontable.TableView.getCellAtCoords jquery.handsontable.full.js:3035
getCell jquery.handsontable.full.js:2075
Megatable.applyCellContent table.js:423
Megatable.openDocument table.js:125
Megatable.init table.js:33
Megatable table.js:7
(anonymous function) table.js:466
jQuery.extend.each jquery-1.8.2.js:611
jQuery.fn.jQuery.each jquery-1.8.2.js:241
$.fn.megatable table.js:462
(anonymous function) view:1575
fire jquery-1.8.2.js:974
self.fireWith jquery-1.8.2.js:1082
jQuery.extend.ready jquery-1.8.2.js:406
DOMContentLoaded jquery-1.8.2.js:83
</pre>
selectCell(row, col) make same error. getCellMeta(row, col) work correct

**Comment by AMBudnik** [comment]
Please update to 0.14.1 or newer version.
