### ISSUE TITLE
Fix RegExp vulnerability and clean up major code smells

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8752]
### Description

As the title says the issue is about fixing regular expression vulnerability found in the helper that checks if the value is a numeric value and implementing a GHA workflow with Code Quality tool that requires clean up major code smells.

### Your environment
* Handsontable version: -
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment]
Released in Handsontable v10.0.0
