### ISSUE TITLE
[10.0.0] wtBorder area is shifted with nestedHeaders on Chrome 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8756]
### Description

`wtBorder area` is shifted in v10.0.0 on Chrome 93.0.4577.82 (latest) and Beta 95.0.4638.17. 
It looks well on Firefox 92 and Safari 14.1.2 (16611.3.10.1.6).

This bug was before but **with v10 the offset is bigger**.

**v10.0.0**
<img width="212" alt="Screenshot 2021-09-27 at 18 31 57" src="https://user-images.githubusercontent.com/30186818/134949832-caa1acb8-bb4a-4f04-9de3-09b540af4288.png">
<img width="271" alt="Screenshot 2021-09-27 at 18 32 06" src="https://user-images.githubusercontent.com/30186818/134949818-a12d83f6-a203-4c02-8d31-be82a10ccf60.png">

**v9.0.2**
<img width="201" alt="Screenshot 2021-09-27 at 18 38 23" src="https://user-images.githubusercontent.com/30186818/134950168-17747242-7d41-4f20-be54-18b2f73dfbf7.png">
<img width="238" alt="Screenshot 2021-09-27 at 18 29 18" src="https://user-images.githubusercontent.com/30186818/134950218-7dbda67c-1d9f-496a-a764-a841d28e7a05.png">

###  Steps to reproduce

1. Select header D
2. Select header E

### Demo
https://jsfiddle.net/uj5wogcm/ v9.0.2
https://jsfiddle.net/fjxszqpg/ v10.0.0-RC

### Your environment
* Handsontable version: 10
* Browser Name and version: Chrome  93.0.4577.82 (latest) and Beta 95.0.4638.17
* Operating System: macOS 11.6 (20G165)

**Comment by aninde** [comment]
Fixed for v11.1.0 https://jsfiddle.net/jwuzo4sx/.

**Comment by AMBudnik** [comment]
Issue closed as fixed in Handsontable v11.1.0
