### ISSUE TITLE
Bump numbro to >2.3.3

### ISSUE THREAD

**Issue by chaosflaws** [handsontable/handsontable#8758]
### Description

Please bump the numbro dependency to >2.3.3. A bug that we encountered upstream has been fixed there: https://github.com/BenjaminVanRyseghem/numbro/pull/590

**Comment by AMBudnik** [comment]
Thank you for sharing the information along with the reference, @chaosflaws

**Comment by AMBudnik** [comment]
Hi @chaosflaws 

Great news! We just released Handsontable v15.0.0 where we merged https://github.com/handsontable/handsontable/pull/10929.

Thank you for your feedback once again.
