### ISSUE TITLE
Demo “Search of values” if set option outsideClickDeselects=true

### ISSUE THREAD

**Issue by zgchizi** [handsontable/handsontable#876]
Demo http://handsontable.com/demo/search.html, when set  option outsideClickDeselects=true ,table cann't lose focus. V0.9.9

**Comment by AMBudnik** [comment]
This issue should be fixed.
 
Checked in on:
* Chrome 41 (OSX & Windows 7)
* Firefox 37 (OSX & Windows 7)
* IE11 (Windows 7)

If you would experience this issue in your code please update to 0.14.1 and if it would still occur prepare a JSFiddle demo.
