### ISSUE TITLE
[RTL] LeftOverlay

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8763]
### Description

When I set `dir='rtl'` the left overlay displayed incorrectly on the left of the website.  ~It should display on the right of the table.~ It should be not visible.

~The second issue is naming mismatch because it contains left which is start for LTR and end when RTL. This Overlay should be renamed to `Start`.~

### Steps to reproduce

Following this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/f229aab5311a146c4a84b1892c2b0b57d291e216/vanilla/configurations.js#L5-L10)

```js
configurations.JustATable = {
    data: Handsontable.helper.createSpreadsheetData(60, 10),
    colHeaders: true,
    rowHeaders: true,
    licenseKey: "non-commercial-and-evaluation",
};
```
I got: 
![image](https://user-images.githubusercontent.com/2893099/135087649-2a8a93b4-c5ba-49c5-bc7d-0ae11c13f903.png)

**Comment by Siemienik** [comment]
As we discussed in. a [slack thread](https://handsoncode.slack.com/archives/C02GFJGLTGQ/p1637067892006300), we want to keep `LeftOverlay` without renaming. To cover the same functionality for RTL, I add `RightOverlay` and which will switch visibility depending on direction.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
