### ISSUE TITLE
[RTL] TopOverlay

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8764]
### Description

When I set `dir='rtl'` the top overlay displayed incorrectly on the left of the website. It should display on the right, above the table.

### Steps to reproduce

Following this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/f229aab5311a146c4a84b1892c2b0b57d291e216/vanilla/configurations.js#L5-L10) 

```js
configurations.JustATable = {
    data: Handsontable.helper.createSpreadsheetData(6, 10),
    colHeaders: true,
    rowHeaders: true,
    licenseKey: "non-commercial-and-evaluation",
};
```
I got: 
![image](https://user-images.githubusercontent.com/2893099/135088562-3cd76844-d706-4fce-ad35-e7c05e126197.png)

**Comment by Siemienik** [comment]
Setting: `height : "auto"` moves the headers to the correct position

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
