### ISSUE TITLE
[RTL] TopLeftCorner

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8765]
### Description

When I set `dir='rtl'` the top **left** overlay displayed incorrectly on both sides of the top overlay (which is also displayed incorrectly, see #8764 ).  ~**It should display only on the right of the top overlay.**~

~The second issue is naming mismatch because it contains `left` which is start for LTR and end when RTL. **This Overlay should be renamed to `TopStartCorner`.**~

### Steps to reproduce

Following this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/f229aab5311a146c4a84b1892c2b0b57d291e216/vanilla/configurations.js#L5-L10) 

```js
configurations.JustATable = {
    data: Handsontable.helper.createSpreadsheetData(6, 10),
    colHeaders: true,
    rowHeaders: true,
    licenseKey: "non-commercial-and-evaluation",
};
```
I got: 
![image](https://user-images.githubusercontent.com/2893099/135089488-1be149c6-8893-4d80-9f62-0bb9da25e069.png)

**Comment by Siemienik** [comment]
As we discussed in. a [slack thread](https://handsoncode.slack.com/archives/C02GFJGLTGQ/p1637067892006300), we want to keep `TopLeftCorner` without renaming. To cover the same functionality for RTL, I add `TopRightCorner` and which will switch visibility depending on direction.

**Comment by aninde** [comment]
Looks as expected with v12.0.0.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
