### ISSUE TITLE
[RTL] Incorrect selection issues

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8768]
### Description

When I set `dir='rtl'` selection starts to works totally incorrectly.

### Steps to reproduce

Following this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/f229aab5311a146c4a84b1892c2b0b57d291e216/vanilla/configurations.js#L5-L10) 

```js
configurations.JustATable = {
    data: Handsontable.helper.createSpreadsheetData(6, 10),
    colHeaders: true,
    rowHeaders: true,
    licenseKey: "non-commercial-and-evaluation",
};
```

Clicks: J2, J3, J4, I2, I3, I4

I got:

https://user-images.githubusercontent.com/2893099/135161082-6d02389c-e73b-45d7-9a66-48bb77b042d2.mp4

See: Cell selection (blue border) is drawn outside the table. ⚠️

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
