### ISSUE TITLE
[RTL] Shifted borders for selections

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8769]
### Description

I tested multiple selections with RTL turned on. Background colors look works correctly, I see an issue with selection borders.

LTR borders are correct:

https://user-images.githubusercontent.com/2893099/135166563-4d4c60fd-1d23-4d8b-85d3-1ad03cd8c29a.mp4

RTL without borders:

https://user-images.githubusercontent.com/2893099/135166613-0b33f684-2f03-49a3-a961-9f52dbe1adda.mp4

### Steps to reproduce

I used this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/5e7ac56d642da53b3529f2dfbda36f3a8c9a5845/vanilla/configurations.js#L448-L454) 

```js
configurations.MultileSelection = {
    data: Handsontable.helper.createSpreadsheetData(20, 20),
    colHeaders: true,
    rowHeaders: true,
    selectionMode: 'multiple',
    licenseKey: "non-commercial-and-evaluation",
};
```

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
