### ISSUE TITLE
[RTL] Custom Borders disappear

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8785]
### Description

I tested custom borders for RTL. I pointed that the borders disappear for `dir=rtl`.

### Steps to reproduce

I used this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/5e7ac56d642da53b3529f2dfbda36f3a8c9a5845/vanilla/configurations.js#L396-L420) 

```js
configurations.CustomBorders = {
    data: Handsontable.helper.createSpreadsheetData(5, 6),
    rowHeaders: true,
    colHeaders: true,
    stretchH: 'all',
    customBorders: [
        {
            range: {
                from: { row: 1,  col: 1 },
                to: { row: 3,  col: 4 }
            },
            top: { width: 2,  color: '#5292F7' },
            left: { width: 2,  color: 'orange' },
            bottom: { width: 2,  color: 'red' },
            right: { width: 2,  color: 'magenta' }
        },
        {
            row: 2,
            col: 2,
            left: { width: 2,  color: 'red' },
            right: { width: 1,  color: 'green' }
        }
    ],
    licenseKey: 'non-commercial-and-evaluation'
};
```

On the video:
1. Starts with LTR, borders are ok
2. Switches to RTL, borders not existing.

https://user-images.githubusercontent.com/2893099/135425033-b9f926b7-e351-481a-9843-871f122c8113.mp4

**Comment by aninde** [comment]
Left and right option of customBorders don't work with enabled `rtl`. Custom borders can be set with `start` and `end` option. 
With this changes this issue works with v12.0.0 https://jsfiddle.net/Lfyzhg23/

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
