### ISSUE TITLE
setCellMeta()

### ISSUE THREAD

**Issue by tamtakoe** [handsontable/handsontable#879]
Is there a function that can be set meta for cells (not only into cell or col settings)?

**Comment by indiecollin** [comment]
I am currently dealing with the last issue thelok mentioned. Is there a fix for changing the renderer multiple times?

**Comment by AMBudnik** [comment]
Hi @indiecollin 
you should be able to change the renderer as often as required. Here's an example http://jsfiddle.net/0L5o774f/1/ that changes the renderer each 500ms.
