### ISSUE TITLE
[RTL] NumericCellType / Currency formatting issue 

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8791]
### Description

https://jsfiddle.net/p4zg6cs2/
As can be pointed in the following demo, currency formatting fails for RTL mode.
For RTL, currency formats should look exacly same as in LTR. 

LTR:
<img width="398" alt="Screenshot 2021-09-30 at 14 51 38" src="https://user-images.githubusercontent.com/2893099/135458792-26512a1f-c42d-4a3a-92e0-290287080cfc.png">
RTL:
<img width="806" alt="Screenshot 2021-09-30 at 14 51 19" src="https://user-images.githubusercontent.com/2893099/135458829-600b2730-68a3-4140-9636-857bfdafd88b.png">

**Comment by AMBudnik** [comment]
Just to add, we should also check the use of percentage and currency
Based on the research % how to appear on the left

### Percentage
LTR - `40%` RTL - `%40`

### Currency
LTR 
#### 1.000.000 dirhams 

RTL  
![Zrzut ekranu 2021-10-6 o 12 54 39](https://user-images.githubusercontent.com/10757813/136189854-278d0b0c-87a2-4af6-9547-53ea75994d89.png)

**Comment by aninde** [comment]
Solved in the v12.0.0 https://jsfiddle.net/y8bjm5hg/

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
