### ISSUE TITLE
[RTL] AutocompleteCellType, icon placement

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8795]
### Description

For RTL, the icon which is showing on the cell's start should be moved to the left.

![image](https://user-images.githubusercontent.com/2893099/135597449-8fdd9c0e-bae1-48d7-8aed-a0385b8e51cd.png)

~Additionally, there is an issue with the editor's cursor, see #8792 ~

### Steps to reproduce
1. Use this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/6d6908bf6a50f936c88daf5d6c766ed30a5870da/vanilla/configurations.js#L497-L527):

```js
{
    licenseKey: 'non-commercial-and-evaluation',
    data: [
        ['BMW', 'black', 'black'],
        ['Nissan', 'blue', 'blue'],
        ['Chrysler', 'yellow', 'black'],
        ['Volvo', 'white', 'gray']
    ],
    colHeaders: ['Car', 'Chassis color', 'Bumper color'],
    columns: [
        {
            type: 'autocomplete',
            source: ['BMW', 'Chrysler', 'Nissan', 'Suzuki', 'Toyota', 'Volvo'],
            strict: false
        },
        {
            type: 'autocomplete',
            source:  ['yellow', 'red', 'orange and another color', 'green',
    'blue', 'gray', 'black', 'white', 'purple', 'lime', 'olive', 'cyan'],
            strict: false,
            visibleRows: 4
        },
        {
            type: 'autocomplete',
            source:  ['yellow', 'red', 'orange and another color', 'green',
    'blue', 'gray', 'black', 'white', 'purple', 'lime', 'olive', 'cyan'],
            strict: false,
            trimDropdown: false
        }
    ]
}
```

**Comment by wszymanski** [comment]
It's worth to mention that within this issue there is also changed position of "suggestion box" and for me it works properly.

LTR:

![image](https://user-images.githubusercontent.com/141330/141788405-f8382224-fdbf-4405-886d-a276ed11a2e8.png)

RTL:

![image](https://user-images.githubusercontent.com/141330/141788429-77a9c216-afff-48e7-b932-39bacdc8bf7a.png)

**Comment by Siemienik** [comment]
> I suppose that it's the desired solution.

Correct

**Comment by budnix** [comment]
The linked PR is merged to the `rtl` branch so I think the issue can be closed.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
