### ISSUE TITLE
[RTL] CheckboxCellType

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8797]
### Description

For the RTL it moves the text to the correct alignment, however, it needs to improve margins/paddings. Look at the screenshot:

![image](https://user-images.githubusercontent.com/2893099/135600266-0c1afd89-6657-420e-b01c-4ad68d4cadf2.png)

### Steps to reproduce
1. Use this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/b5537e12b09cba6d5183a489d3a27f23d7035274/vanilla/configurations.js#L528-L562) with RTL:
```js
{
    data: [
        { car: 'Mercedes A 160',  available: true, comesInBlack: 'yes' },
        { car: 'Citroen C4 Coupe',  available: false, comesInBlack: 'yes' },
        { car: 'Audi A4 Avant',  available: true, comesInBlack: 'no' },
        { car: 'Opel Astra',  available: false, comesInBlack: 'yes' },
        { car: 'BMW 320i Coupe',  available: false, comesInBlack: 'no' }
    ],
    colHeaders: ['Car model', 'Accepted (label after)', 'Comes in black (label before)'],
    height: 'auto',
    columns: [
        {
            data: 'car'
        },
        {
            data: 'available',
            type: 'checkbox',
            label: {
                position: 'after',
                property: 'car' // Read value from row object
            },
        },
        {
            data: 'comesInBlack',
            type: 'checkbox',
            checkedTemplate: 'yes',
            uncheckedTemplate: 'no',
            label: {
                position: 'before',
                value: 'In black? '
            },
        },
    ],
    licenseKey: 'non-commercial-and-evaluation'
};
```

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
