### ISSUE TITLE
[RTL] Date cell type

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8800]
## Description

For RTL, I see some issues to resolve:
1. The icon should be moved to the left
2. datapicker should open from right to left. Currently, it's open from right to right (out of the page, and breaks to new lines) - see the video below.
3. Datapicker controls & logic are still in LTR.

https://user-images.githubusercontent.com/2893099/135605217-09b2b8e2-ddee-4dfd-8686-4f1cf14ef3ce.mp4

## How to reproduce?

1. Use this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/cac5faac862eea65f501cffc656c838ea043be47/vanilla/configurations.js#L563-L593):
```js
{
    licenseKey: 'non-commercial-and-evaluation',
    data: [
        ['01/14/2021'],
        ['12/01/2022'],
        ['11/19/2023'],
        ['02/02/2021'],
        ['07/24/2022']
    ],
    height: 'auto',
    columns: [
        {
            type: 'date',
            dateFormat: 'MM/DD/YYYY',
            correctFormat: true,
            defaultDate: '01/01/1900',
            // datePicker additional options
            // (see https://github.com/dbushell/Pikaday#configuration)
            datePickerConfig: {
                // First day of the week (0: Sunday, 1: Monday, etc)
                firstDay: 0,
                showWeekNumber: true,
                numberOfMonths: 3,
                disableDayFn(date) {
                    // Disable Sunday and Saturday
                    return date.getDay() === 0 || date.getDay() === 6;
                }
            }
        },
    ]
}
```

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
