### ISSUE TITLE
[RTL] Dropdown cell type

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8802]
## Description

For RTL, the dropdown opens in the wrong possition and doesn't cover the current cell.

LTR | RTL
---|---
![image](https://user-images.githubusercontent.com/2893099/135607657-11bde435-7791-4e6d-9889-5d80cda5e6f1.png) | ![image](https://user-images.githubusercontent.com/2893099/135607614-8f52d4e1-c716-4ef8-ba5f-940173256522.png)

## Reproduction:

1. Use this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/f5b68a02915533e97905b80127af0cf17d1b43e4/vanilla/configurations.js#L594-L603):

```js
{
    data: [['black'], ['blue'], ['black'], ['gray']],
    columns: [
        {
            type: 'dropdown',
            source: ['yellow', 'red', 'orange', 'green', 'blue', 'gray', 'black', 'white']
        }
    ],
    licenseKey: 'non-commercial-and-evaluation'
};
```

**Comment by aninde** [comment]
Done in v12.0.0 https://jsfiddle.net/juwat790/

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
