### ISSUE TITLE
[RTL] Time cell type

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8805]
## Description

I suppose that RTL and LTR time format should be the same, e.g., `8:00:00 pm`. I mean that `am`/`pm` should always be on the right.

![image](https://user-images.githubusercontent.com/2893099/135618284-79b9601c-bcc2-4343-adea-9de67292ffa8.png)

## Reproduction

1. Use this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/d679c4b8563dc4c7254589449863cd72ab5e83e2/vanilla/configurations.js#L653-L663):

```js
{
    data: [[1332284400000], ['10 30'], ['8:00 PM'], [1332284400000], [1332284400000]],
    licenseKey: 'non-commercial-and-evaluation',
    columns: [
        {
            type: 'time',
            timeFormat: 'h:mm:ss a',
            correctFormat: true
        },
    ]
}
```

**Comment by aninde** [comment]
We established that if we do not have specific requirements from a specific client, then the date format should be the same as in the LTR. 
https://jsfiddle.net/ow567xqt/ v12.0.0

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
