### ISSUE TITLE
autocomplete drop down goes bihind outer div

### ISSUE THREAD

**Issue by spsaran** [handsontable/handsontable#881]
version 0.9.6
IE 8

auto complete drop down goes behind the outer div when outer div style is 'overflow: hidden'.  I can't change the outer div, it is coming from portal container. Can you place the typeahead ul div in document level instead of handsontable div? so that it will come over all other div.

**Comment by AMBudnik** [comment]
Please track changes in https://github.com/handsontable/handsontable/issues/2098
