### ISSUE TITLE
Support modularization for Angular wrapper

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8818]
### Description

Since 8.3.0 Handsontable can be modularized. However, that feature is not implemented in the Angular wrapper. The issue is about research and implementation of the missing feature.

Related issues:
 * #8816

### Your environment
* Angular version: -
* Handsontable version: -
* Wrapper version: 10.0.0
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
Tested locally with v11.

**Comment by AMBudnik** [comment]
Closed as released in Handsontable v11.

For anyone interested in the subject of modularization in Angular please visit https://handsontable.com/docs/angular-modules/
