### ISSUE TITLE
Support modularization for Vue wrapper

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8820]
### Description

Since 8.3.0 Handsontable can be modularized. However, that feature is not implemented in the Vue wrapper. The issue is about research and implementation of the missing feature.

Related issues:
 * #8816

### Your environment
* Vue wrapper version: 10.0.0
* Handsontable version: -
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
Tested locally with v11.

**Comment by AMBudnik** [comment]
Closed as released in Handsontable v11.

For anyone interested in the subject of modularization in Vue please visit https://handsontable.com/docs/vue-modules/
