### ISSUE TITLE
Bad performance custom borders

### ISSUE THREAD

**Issue by OlgaIOn** [handsontable/handsontable#8823]
### Description
The tables with multiple borders are very slow, so that it is impossible to work with them. 
With a table size of 20x20, when deleting and setting borders again, the table hangs for a more than 1 minute. 

As far as I can see the problem is known for a long time  (#6467)
Do you continue to work on the problem? When can you count towards the improvements in performance? 

### Steps to reproduce
1. Set borders green (performs quickly, because there are no borders)
2. Set borders red (performs more than 1 minute, because borders should be deleted first)

### Demo
https://jsfiddle.net/ue07r83f/3/

### Your environment
* Handsontable version 10.0.0

**Comment by AMBudnik** [comment]
Hi @OlgaIOn 

That issue has the `on hold` status as we decided not to use SVG. After that investigation, no further work was done to check other possibilities. We might change the title of that issue. But still, it provides a valuable list of linked issues, so we treat that epic report as the main issue related to the performance of custom borders. It means that I need to close your report as a duplicate.

I will make sure to send you a notification once we make progress on that matter. I agree with you. It definitely takes too much time to work with larger setups of custom borders.

**Comment by jwueller** [comment]
This issue should at least be significantly mitigated by the #9044 performance fix.

**Comment by AMBudnik** [comment]
Thank you @OlgaIOn for reporting the bug and @jwueller for your time and effort to help us to fix it. Great job!

The changes are available in Handsontable v11.1.0. Here is a full list of changes https://handsontable.com/docs/release-notes/#_11-1-0

**Comment by warpech** [comment]
Note that regarding the general performance of custom borders, the issue https://github.com/handsontable/handsontable/issues/6467 remains open.
