### ISSUE TITLE
[RTL] ContextMenu

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8825]
### Description

For RTL:
* [x] Context menu should prefer to open from right to left
* [x] Content of context menu (each item) should be aligned to the right
* [x] The arrows to sub-menus should be on the left.
* [x] The submenu should open from right to left 

### How to reproduce:

1. Use this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/610f03de38a979a1c65d71b08897786140699a91/vanilla/configurations.js#L78-L84):
```js
{
    data: Handsontable.helper.createSpreadsheetData(5, 20),
    colHeaders: true,
    rowHeaders: true,
    contextMenu: true,
    licenseKey: "non-commercial-and-evaluation",
}
```
2. On `K2` click right mouse button
3. Result: 
![image](https://user-images.githubusercontent.com/2893099/135901517-6eef7dc1-6610-4327-9421-d7030b310ca7.png)

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
