### ISSUE TITLE
Wrong description of Context menu with specific options

### ISSUE THREAD

**Issue by kanasann1106** [handsontable/handsontable#8827]
### Description

I found a mistake in the documentation description.
I think this is the correct content.

Key | Purpose | Extra conditions
-- | -- | --
row_below | Insert row below action |  
remove_row | Remove row action |  

![スクリーンショット 2021-10-05 11 16 05](https://user-images.githubusercontent.com/22334731/135949749-1ff033b6-adc0-43cd-9035-4d80cbca3f77.png)

### Links

https://handsontable.com/docs/context-menu/#context-menu-with-specific-options

**Comment by AMBudnik** [comment]
Thank you for the report @kanasann1106 

You are absolutely right! That description has to be changed.
@kirszenbaum please add me as a reviewer

**Comment by AMBudnik** [comment]
Hey @kanasann1106 !
@kirszenbaum already fixed the issue on the production. Definitions are updated.
