### ISSUE TITLE
Trouble sorting column of type 'numeric'

### ISSUE THREAD

**Issue by mludlum** [handsontable/handsontable#883]
I have set a column to be type 'numeric'.  The underlying data is integer strings.  I expected the data type to be honored when sorting but it does not.  As a workaround, I tried formatting with leading zeroes, but it does not seem that Numeral.js supports leading zeros.    I also would like the empty row to be at the bottom and requested in another issue.

So, I made this change to the sort function.  What do you think?
```javascript
    this.sortIndex.sort(function (a, b) {
      var type = instance.view.settings.columns[instance.sortColumn].type;
      var a1 = a[1];
      var b1 = b[1]
      if (type === 'numeric')
      {
          try
          {
              if (a1 !== null)
                  a1 = Number(a1);
              if (b1 !== null)
                  b1 = Number(b1);
          }
          catch (e)
          {

          }
      }
      if (a1 === b1) {
        return 0;
      }
      if (a1 === null) {
        return 1;
      }
      if (b1 === null) {
        return -1;
      }
      if (a1 < b1) return instance.sortOrder ? -1 : 1;
      if (a1 > b1) return instance.sortOrder ? 1 : -1;
      return 0;
    });
    sortingEnabled = true;
  };
```

**Comment by kevin-j-morse** [comment]
Same issue here. If the datatype of the source data is a string handsontable ignores the column type 'numeric' and the sorting doesn't work.

1
100
101
...
2
200

**Comment by jakefreeberg** [comment]
:+1:

**Comment by igorladela** [comment]
+1

**Comment by laughsmile** [comment]
After I pasted data from excel,the numeric column can not sort properly.
Please help.

**Comment by Maxi7** [comment]
@psmolenski, @wilwade: in neither of your jsFiddles a table is created. Are there any changes in the meanwhile?

**Comment by wilwade** [comment]
@Maxi7 Mine was failing due to issues loading libraries: http://jsfiddle.net/13fmnzvL/  This one will work (although you might need to turn off privacy badger if you use it.)

**Comment by snuuve** [comment]
I have same problem, data is string, column type is 'numeric' and sorting is wrong.
http://pl.tinypic.com/r/2zgdu9v/8

**Comment by AMBudnik** [comment]
Hi,
I couldn't reproduce it with the first demo. Could anyone confirm that this occurs with 0.23.0?
