### ISSUE TITLE
[8.4.0] `updateSettings` throws an error in modularized HoT environment

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8830]
### Description

Handsontable throws an error when the `updateSettings` method is called. It only happens when the application uses a modularized version of Handsontabke and the _UndoRedo_ plugin is not used.

### Demo

[8.3.0] https://codesandbox.io/s/thirsty-bhaskara-y62iw?file=/src/index.js (works)
[8.4.0] https://codesandbox.io/s/romantic-sea-utc96?file=/src/index.js (doesn't work)

### Your environment
* Handsontable version: 8.4.0
* Browser Name and version: any
* Operating System: any

**Comment by aninde** [comment]
This issue will be fixed by v11. Tested locally.

**Comment by AMBudnik** [comment]
Issue closed as fixed in Handsontable v11.

If anyone would like to check the full list of changes please visit https://github.com/handsontable/handsontable/issues/8949
