### ISSUE TITLE
[RTL] ColumnFreeze

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8832]
### Description

For RTL, currently, Frozen columns are on the correct side of the website (on the right). However, it is necessary to improve the position.
Additionally, it is enabled to scroll to the right (empty space there), which should be disabled.
Scrolling to the left is disabled, which is incorrect.

### How to reproduce

1. Use this [configuration](https://github.com/Siemienik/handsontable-storrybooks/blob/09904430ff26e102250aa212d8ca3d09e2f7c502/vanilla/configurations.js#L806-L810):
```js
 {
    data: Handsontable.helper.createSpreadsheetData(100, 50),
    fixedColumnsLeft: 2,
    licenseKey: 'non-commercial-and-evaluation'
};
2. Scroll to the right, see empty space (incorrect)
3. Scroll to the left, scrolling blocked on the starting position (incorrect)
4. Result:
```
https://user-images.githubusercontent.com/2893099/136018575-a6efe19d-583d-4953-ab00-acb110b52a0b.mp4

**Comment by aninde** [comment]
if the user wants to use this option with RTL enabled, he is warned to use `fixedColumnsStart`.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
