### ISSUE TITLE
[RTL] ManualColumnResize

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8835]
### Description

For RTL, the manualColumnResize plugins need the following fixes:
1. Indicators are invisible and placed in the wrong place.
2. Currently, dragging the indicator to the left causes decreasing column width, it should increase the width.
3. Dragging the indicator to the right causes increasing column width, it should decrease the width.

### How to reproduce

1. Use this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/5dcd2d182fc343fa4996a235fe75bbb268978359/vanilla/configurations.js#L821-L832)
```js
{
    data: Handsontable.helper.createSpreadsheetData(5, 5),
    width: '100%',
    height: 'auto',
    colHeaders: true,
    rowHeaders: true,
    colWidths(index) {
        return (index + 1) * 40;
    },
    manualColumnResize: true,
    licenseKey: 'non-commercial-and-evaluation'
}
```
2. move the mouse over headers from right to left.
3. if the mouse goes over the indicator, click and drag it into the left and release - column should become bigger, however, it isn't
4. continue the move to the left, click the second founded indicator and moved it to the right then release. Column increased its width, should decrease.

https://user-images.githubusercontent.com/2893099/136029271-4c2f2610-8c8d-46d4-a9f4-e7a7392e03bd.mp4

**Comment by aninde** [comment]
Works well with v12.0.0 https://jsfiddle.net/0r9fhq1n/

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
