### ISSUE TITLE
[8.0.0+] Nested Rows, updating settings expands all parents and not keeping the previous state ( was working in version 8+ )

### ISSUE THREAD

**Issue by dragoshzava** [handsontable/handsontable#8838]
### Description
When updating settings of the handsontable instance through update settings, the nested rows are expanded all the time and does not keep the persistent state of collapsed/expanded.

### Steps to reproduce
1. create a nested rows table
2. collapse all rows , collapse any row, or expand ( the action doesnt matter, it should look different from initial load/state )
3. update the instance through updateSettings ( width/height etc )
4. after update all rows are expanded by default

### Demo
1. enter this url https://jsfiddle.net/Resems/dfg8vLc4/9/
2. collapse 3 out of 4 parents for example
3. click the update settings button, which only updates the width.
4. the table gets expanded.

### Your environment
* Handsontable version: 10
* Browser Name and version: Chrome Latest
* Operating System: Windows 10

### Notes
It is working on version 8+ which we currently use, while trying to update to version 10 this seems to not work anymore.
I also tried settings persistent state, did not help.

### Additional question
Is there any way to preserve the state, maybe getting the collapsed/expanded parents and passing it on updateSettings?
In the documentation there is no information about sending which row/parent/cell should be expanded or not, by default all are expanded i see.

Thank you.

**Comment by dragoshzava** [comment]
@aninde thank you, is there a release date for it ?

**Comment by AMBudnik** [comment]
Hi @dragoshzava we are still making some small changes so that date isn't fixed yet. I will notify you as soon as we release the version.

**Comment by AMBudnik** [comment]
Hi @dragoshzava Handsontable v12 is live!

Please check our release notes https://handsontable.com/docs/release-notes/#_12-0-0 and the migration guide https://handsontable.com/docs/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls

If you would have any issues with updating to the newer version or if there are still issues to be fixed send me an email at support@handsontable.com

**Comment by viotile** [comment]
Hello @AMBudnik ,
I have found that "updateSetting" method is not working with update data with version : 12.1.2 but working fine with version 7.4.0

Only added new variable and updated category name
When user click on "update setting" button then it should display like below image but with latest version (12.1.2)  
Content is not updating as you can see in image "111" should be added before 1st cell data

<img width="279" alt="image" src="https://user-images.githubusercontent.com/8554562/188663797-6b80f9e5-3a91-46e7-bf70-ba4ef3ac95c6.png">

Here is fiddle: 
Version 7.4.0:  [https://jsfiddle.net/803hdypm/](https://jsfiddle.net/803hdypm/) (Working)
Version 12.1.2: [https://jsfiddle.net/egpamjb1/](https://jsfiddle.net/egpamjb1/)

**Comment by AMBudnik** [comment]
@viotile case is described by https://github.com/handsontable/handsontable/issues/9844 (already mentioned on the forum)

**Comment by AMBudnik** [comment]
Hi @viotile 

Hi @viotile We just released Handsontable v12.3.1 where we fix issue https://github.com/handsontable/handsontable/issues/9844

Here https://handsontable.com/docs/javascript-data-grid/release-notes/#_12-3-1 are the Release Notes for the version.
