### ISSUE TITLE
Wrong Scrollbars height 

### ISSUE THREAD

**Issue by try2** [handsontable/handsontable#884]
Hello, 

I try example on http://handsontable.com/demo/scroll.html about vertical and horizontal scrollbars,  i found layout problem when i try to quick scroll the table,  height scrollbars and height of table is not same, after i quick scroll the table using mousewheel.
 you can look detail of error on this images.

![image](https://f.cloud.github.com/assets/5011578/796545/2f0035be-ed29-11e2-87c8-9f626c805595.png)

There is other example, 
![image](https://f.cloud.github.com/assets/5011578/796692/b4ff90da-ed2c-11e2-81c5-fac36f539d4f.png)

i'm  using Chrome Browser ( Version 28.0.1500.71 m ) and Internet Explorer 9, and using handsontable version 0.99,

**Comment by AMBudnik** [comment]
This case should work like expected since previous release. If you still have this issue, please reply.
