### ISSUE TITLE
Outdated dependencies in React-based examples hosted on codesandbox

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#8840]
### Description
As mentioned in the issue's title, examples hosted on codesandbox uses outdated dependencies to `handsontable@8.3.2` and `@handsontable/react@5.0.0`.

All of them are in the `Using the HotColumn component` guide:
- [ ] [Declaring column settings
](https://handsontable.com/docs/react-hot-column/#declaring-column-settings)
- [ ] [Declaring a custom renderer as a component
](https://handsontable.com/docs/react-hot-column/#declaring-a-custom-renderer-as-a-component)
- [ ] [Object data source
](https://handsontable.com/docs/react-hot-column/#object-data-source)
- [ ] [Declaring a custom editor as a component
](https://handsontable.com/docs/react-hot-column/#declaring-a-custom-editor-as-a-component) additionally uses `react@16.14`
- [ ] [Using the renderer/editor components with React's Context
](https://handsontable.com/docs/react-hot-column/#using-the-renderer-editor-components-with-react-s-context)
- [ ] [An advanced example
](https://handsontable.com/docs/react-hot-column/#an-advanced-example)

### Links
https://handsontable.com/docs/react-hot-column/

**Comment by warpech** [comment]
The dependencies in React-based examples are no longer outdated, because we no longer use CodeSandbox. All code examples are sourced from this repo.
