### ISSUE TITLE
Multiline cell editing issue

### ISSUE THREAD

**Issue by jazii** [handsontable/handsontable#886]
I tried adding some multiline content to the data variable with \n char for new line.
Once when the line number exceeds 12 if try to edit the cell, the edit box appears with 1px height or so. please see the image.
How ever if I try double click any single line cell initially, the multiline cell edit works fine.

Also in cell edit mode only left/right arrow works for moving in the cell. If use up/down arrow it switches to the next cell.

![image](https://f.cloud.github.com/assets/5014062/798545/f7f138f4-ed62-11e2-8202-0c298ff9b872.png)

**Comment by AMBudnik** [comment]
It should work as expected when updated to newest version of HOT. Please let us know, if there will be some other issues.
