### ISSUE TITLE
Autocomplete typeahead multiple values

### ISSUE THREAD

**Issue by gbelmm** [handsontable/handsontable#887]
example in hansontable http://jsfiddle.net/pQrD4/

example in bootstrap typeahead
http://jsfiddle.net/Sherbrow/BwDmM/300/

in hansontable the search works but selecting the second replaces all

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
related to: https://github.com/handsontable/handsontable/issues/1201

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
