### ISSUE TITLE
afterGetRowHeader

### ISSUE THREAD

**Issue by xiaoyuan-666** [handsontable/handsontable#8883]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @xiaoyuan-666 

we're missing some description in this issue report?
Till it remains empty I will keep it closed.
