### ISSUE TITLE
Fix canonical addresses in the documentation

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#8886]
### Description

We migrated our documentation to a new engine, VuePress, but forgot about canonical tags. They should point at the latest official revision so Google knows that all other revisions (versions) are just copies, and it's not worthy crawling them.

### Guides
```
<link rel="canonical" href="https://handsontable.com/docs/{slug}" />
```
The `Guide Introduction` page doesn't have a slug so it should always get the address:
```
<link rel="canonical" href="https://handsontable.com/docs/" />
```

### API
```
<link rel="canonical" href="https://handsontable.com/docs/api/{slug}" />
```
The `API Introduction` page doesn't have a slug so it should always get the address:
```
<link rel="canonical" href="https://handsontable.com/docs/api" />
```

### Examples
```
<link rel="canonical" href="https://handsontable.com/docs/examples/{slug}" />
```
The `Examples Introduction` page doesn't have a slug so it should always get the address:
```
<link rel="canonical" href="https://handsontable.com/docs/examples" />
```

For instance, at:
`https://handsontable.com/docs/9.0/api/bind-rows-with-headers/`
there will be this tag:
`<link rel="canonical" href="https://handsontable.com/docs/api/bind-rows-with-headers" />`

## Versions from 4.0.0 to 8.4.0

Recommend robots to not crawl these old pages by adding:
```
<meta name="robots" content="noindex, nofollow">
```
If in doubt where to put it in the code, head to specs at https://developers.google.com/search/docs/advanced/robots/robots_meta_tag

**Comment by AMBudnik** [comment]
Issue closed as fixed in Handsontable v11.
