### ISSUE TITLE
[8.0.0+] `ExpandAll()` and `toggleAllCollapsibleSections('expand')` stopped working

### ISSUE THREAD

**Issue by ahndohun** [handsontable/handsontable#8900]
### Description

The documentation states that all sections that are collapsible or expandable are expandable/collapsible, but that doesn't really work.

### Steps to reproduce

1. Collapse section b.
2. Click the collapseAll button.
3. It expects sections that are not yet collapsed to be collapsed, but nothing happens.

### Demo

https://jsfiddle.net/fstb6p9h/4/

### Your environment
* Handsontable version: 10.0.0
* Browser Name and version: chrome 95.0.4638.54
* Operating System: mac os big sur

**Comment by aninde** [comment]
@ahndohun, this issue is fixed for the upcoming v11.1.0. Demo https://jsfiddle.net/k57Ltjou/.

**Comment by AMBudnik** [comment]
Hi @ahndohun 

I'm more than happy to notify you that Handsontable v11.1.0 is already online.
Please let me know if everything works well in your project after the update.
