### ISSUE TITLE
[RTL] License info

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8910]
### Description
When I set `dir='rtl'` to the div containing Handsontable, information about the missing license is displaying incorrectly.
This happens even when I add `dir='rtl'` to the `div id='hot-display-license-info'`.

![image](https://user-images.githubusercontent.com/30186818/139255717-0ceb6a4d-0fb6-4130-91cc-e16bab123280.png)

**Comment by budnix** [comment]
I've checked the latest `rtl` branch and the license warning message is rendered correctly. No further action is necessary.

**Comment by aninde** [comment]
Licence info is align according to set layoutDirection.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
