### ISSUE TITLE
i hope that this project have a new function(我希望添加一个新的功能）

### ISSUE THREAD

**Issue by lush-99** [handsontable/handsontable#8916]
in a specific scene,  I need to merge call, that can give me a lot convenience and much chose.
在某一些场景下，我需要去合并单元格，它能给我提供很多的方便的更多的选择

**Comment by adrianszymanski89** [comment]
Hi @lush-99. Can you please provide more info on what your issue is? Some kind of demo or code snippet would be helpful.

**Comment by lush-99** [comment]
can you speak Chinese?

**Comment by lush-99** [comment]
I hope to be able to support cell merging operations like excel

**Comment by lush-99** [comment]
https://user-images.githubusercontent.com/77112588/140051897-42710b10-578e-48ec-818e-f8013a976c96.mp4

**Comment by lush-99** [comment]
@adrianszymanski89

**Comment by adrianszymanski89** [comment]
Here you can see how cell merging is done, I hope that helps:

https://jsfiddle.net/aszymanski/7Le4u9tp/9/

We set context menu language to Chinese so you can understand what's going on here.

**Comment by lush-99** [comment]
https://jsfiddle.net/aszymanski/7Le4u9tp/9/
I can’t access this address, it says I can’t access this website

**Comment by lush-99** [comment]
Cloud you please give me another.

**Comment by lush-99** [comment]
i think that is nice, if you give me a demo at github or a url which i am successful to acess adress.

**Comment by adrianszymanski89** [comment]
Ok, let's try different way. I'll send you instructions what you need to do to reproduce the demo.

Steps

1. Download languages files

![Zrzut ekranu 2021-11-3 o 14 14 24](https://user-images.githubusercontent.com/92314130/140066822-2761db67-4fa0-4be7-9346-3547b78f8bc5.png)

2.  Configuration object setup

![Zrzut ekranu 2021-11-3 o 14 17 00](https://user-images.githubusercontent.com/92314130/140067122-aace36b4-794c-41b1-9b7f-ea75f1a85146.png)

3. Final result

![Zrzut ekranu 2021-11-3 o 14 17 57](https://user-images.githubusercontent.com/92314130/140067225-b959ef3c-d28d-4e97-966c-1f25e7eb5198.png)

I hope it's all clear now.

**Comment by lush-99** [comment]
thanks, i will try it . i hope that you can solvs a lot problem if i find some Puzzled。

**Comment by AMBudnik** [comment]
Hi @Meihualu-cc issue #8400 is solved in Handsontable v12.3.1
