### ISSUE TITLE
The minimum height is 23px

### ISSUE THREAD

**Issue by SnowsofKilimanjaro** [handsontable/handsontable#8918]
### Steps to reproduce

1. why the minimum height is 23px ？ how can I set  it smaller ？ for example , I want to set  15px，What should i do 
2.
3.

### Your environment
* Handsontable version: 9.0.2
* Browser Name and version: chrome
* Operating System:

**Comment by SnowsofKilimanjaro** [comment]
Thanks for your answer, I have already seen the demo. But in my use, the height of each row is different, and the height is dynamically variable，if i set TR and TH   to a fixed height in css ，result may be like this：How to resolve？
![image](https://user-images.githubusercontent.com/13759488/140086320-8f64071b-a5dd-408f-8d8c-c322fdf0fc67.png)

**Comment by AMBudnik** [comment]
Could you list all of the requirements for the TH/TD size, please? That is important: when TH/TR should be set to fixed height/width and when it should expand (also how it should expand - vertically/horizontally). Also, some examples would help (they can be drafts or drawings of the desired result).

**Comment by SnowsofKilimanjaro** [comment]
https://jsfiddle.net/SnowsofKilimanjaro/m0rh3gu8/63/
this is a demo, when i click  button in the demo, i need show rowHeaders and colHeaders  ,if i set fixed height in css . the result  like this:
![image](https://user-images.githubusercontent.com/13759488/140318110-d610ea86-39fe-4a0f-971e-a0a85eaaddaf.png)
i have no idea about how to set  the height of TH is same to TD

**Comment by SnowsofKilimanjaro** [comment]
in the demo : https://jsfiddle.net/aszymanski/L5a1ums8/10/.  if i do not set height in css.   minimum height of row is 23px.     
 first row i set height is 10px , but result is 23px 
![image](https://user-images.githubusercontent.com/13759488/140444380-474beccd-3479-47b7-b037-1d29a8dd71f8.png)
![image](https://user-images.githubusercontent.com/13759488/140444794-0fc6e65c-e1d7-4731-b389-1f92140e99df.png)

**Comment by adrianszymanski89** [comment]
Ok. So what you are trying to do is, unfortunately, not supported at the moment. You can find more information about this issue in our documentation:

https://handsontable.com/docs/api/options/#rowheights

> The default height for rows in the rendering process equals 23px. Height should be equal or greater than 23px. Table is rendered incorrectly if height is less than 23px.

However, you are able to change the row height by CSS but that isn't the best solution.
