### ISSUE TITLE
type: 'numeric' invokes second beforeChange callback?

### ISSUE THREAD

**Issue by mariotacke** [handsontable/handsontable#892]
I wonder if this is a bug, please replicate and see for yourself.

Without a cell type specified, handsontable has ONE callback on beforeChange after an edit: http://jsfiddle.net/hU6Kz/2238/

With a cell type of 'numeric', handsontable has TWO callbacks on beforeChange after an edit: http://jsfiddle.net/hU6Kz/2237/

You can see it in the Chrome JS Console (CTRL+SHIFT+J).

I am using the source flag, but source stays the same over both callbacks. How can I prevent this from happening? Any help would be great!

**Comment by AMBudnik** [comment]
Please update to 0.13.1, seems to work as expected.
