### ISSUE TITLE
[develop] e2e tests are performed in RTL on Safari and Firefox

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8922]
### Description

Some e2e tests are performed in RTL mode on the latest Safari and Firefox. 
They do not pass through this fact when released together but pass through when released individually.
Tests from [here](https://github.com/handsontable/handsontable/pull/8868) cause it.
### Steps to reproduce

1. Build e2e tests on the `develop` branch.
2. Run them on Safari or Firefox

### Your environment
* Handsontable version: `develop`
* Browser Name and version: Safari 15.1 (17612.2.9.1.20), Firefox 94.0
* Operating System: macOS 12.0.1 (21A559)

**Comment by Siemienik** [comment]
Fixed and merged: #8923
