### ISSUE TITLE
Embedded snippets in the docs use a wrong version of Handsontable

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#8927]
### Description

It is expected that v10.0 docs will use version 10.0.x of Handsontable v.9.0 docs will use version 9.0.x of Handsontable, etc. Right now, at least on some pages, it is mixed up. For example, on:

https://handsontable.com/docs/hello-world/ (currently v10.0)
- JavaScript demo uses Handsontable 10.0.0
- TypeScript demo uses Handsontable 9.0.2
- React demo uses Handsontable 9.0.0
- Angular demo uses Handsontable 10.0.0
- Vue demo uses Handsontable 9.0.2 (but Vue wrapper 9.0.1)

https://handsontable.com/docs/9.0/hello-world/
- JavaScript demo uses Handsontable 10.0.0
- TypeScript demo uses Handsontable 9.0.2
- React demo uses Handsontable 9.0.0
- Angular demo uses Handsontable 10.0.0
- Vue demo uses Handsontable 9.0.2 (but Vue wrapper 9.0.1)

https://handsontable.com/docs/react-hot-column/ (currently v10.0)
- React demo uses Handsontable 8.3.2 (which is the only reason why this sample actually works, because Handsontable 10.0.0 with React 17 produces the error #8842 in CodeSandbox, however Handsontable 11.0.0 should work OK again)

**Comment by warpech** [comment]
Ongoing discussion about the solution on Slack: https://handsoncode.slack.com/archives/CCAJN0V1V/p1636446033001200

**Comment by warpech** [comment]
@kirszenbaum will apply a simple solution - migrate all snippets from CodeSandbox (as on page [xxx](https://handsontable.com/docs/react-hot-column/)) to our markdown solution (as on page https://handsontable.com/docs/react-simple-example/).

**Comment by jansiegel** [comment]
> migrate all snippets from CodeSandbox to our markdown solution

What about the more elaborate examples, [like this one](https://handsontable.com/docs/react-hot-column/#an-advanced-example)? They're implemented using multiple files (each component has its own, etc) - I'm wondering if presenting them as a very long snippet is still readable?

**Comment by warpech** [comment]
It is less readable, bit as a temporary measure, we don't have a choice. In future, we will present it better in a new code runner.

**Comment by kirszenbaum** [comment]
I'm closing this issue, as:
- Parts of it were dealt with in #8962 and #8966 
- The rest of the work continues in #8980
