### ISSUE TITLE
[8.0.0.+] beforeChange hook - the prop must be a number

### ISSUE THREAD

**Issue by piotrmod92** [handsontable/handsontable#8930]
Hi everyone,

Recently, I updated HoT from 7.4.2 to 10.0.0 and spotted a problem with **beforeChange** hook. In version 7.4.2, I could modify the prop within **Change** object ([row, prop, oldVal, newVal]) so it is a string. I cannot do so anymore in the version 10.0.0. At some point, I receive an error: "Assertion failed: Expecting an unsigned number."

Is it expected behaviour? Please take a look at the snippet attached.

Interestingly, in **beforeChangeRender** hook, I can still change my prop into a string.

Thank you,
Piotr

### Demo
https://codesandbox.io/s/7hzk8?file=/src/App.vue
Please try to modify any cell. You will see the error inside the web console.
If you comment out **beforeChange** hook, the **beforeChangeRender** hook works as expected.

### Your environment
* Handsontable version: 10.0.0
* Browser Name and version: Chrome/78.0.3904.130 Electron/7.2.4
* Operating System: Windows 10

**Comment by adrianszymanski89** [comment]
Hi @piotrmod92 it looks that indeed this is a regression. I'm marking the issue for further investigation.

**Demo**

https://jsfiddle.net/j8pfw34d/2/

**Comment by AMBudnik** [comment]
Hi @piotrmod92 @adrianszymanski89 

There was one small thing missing in the demo - the data was an array. That is why you could not change the `key`.
Here is an updated demo https://jsfiddle.net/3mcj8d9L/1/
