### ISSUE TITLE
copy excel to handsontable why there is an enter character 

### ISSUE THREAD

**Issue by SCTech100** [handsontable/handsontable#8932]
### Description
![image](https://user-images.githubusercontent.com/65840043/141223764-ee2f851f-41da-415c-9f72-6ccba0816135.png)
 
it become 
![image](https://user-images.githubusercontent.com/65840043/141224155-625cf3ae-a41c-4779-b835-3127e32175a2.png)

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: chrome 95.0.4638.69
* Operating System: windows 10

**Comment by adrianszymanski89** [comment]
Hi @SCTech100 I couldn't recreate your issue, can you please share you Handsontable settings code?

You can also try to paste the same text here: https://jsfiddle.net/53dc28t7/1/ and see if that works.

**Comment by SCTech100** [comment]
Thanks for the replied ..im sorry actually the problem solved as i updated
the handsontable version..

**Comment by adrianszymanski89** [comment]
No problem @SCTech100 I'm glad that the issue is solved!
