### ISSUE TITLE
How about dynamic add  options for dropdown or auto complete；

### ISSUE THREAD

**Issue by zhaowenping001** [handsontable/handsontable#8933]
### Description

Now, my dorpdown may have **up to 10,000 data**, 
so the backend interface uses paging requests, so my dropdown box needs to **dynamically add dropdown options**. 
Is there any solution for this?

### Steps to reproduce

1. I requested the first page of 50 data to source
2.When scrolling to the last few pieces of data
3.How to request a second page of data and add it to the source

### Your environment
* Angular version:7.2
* Handsontable version:8.2.0
* Wrapper version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @zhaowenping001 

We do not have out-of-the-box paging for dropdown cell type. Generally, when you add the list of choices, they are added all at once. However, you can use the `autocomplete` to filter out options that do not match the input query.

**Comment by zhaowenping001** [comment]
> Hi @zhaowenping001
> 
> We do not have out-of-the-box paging for dropdown cell type. Generally, when you add the list of choices, they are added all at once. However, you can use the `autocomplete` to filter out options that do not match the input query.

okay，thank you for replay.

Ok, I'll try to use the custom auto complete approach.

`CustAutoCompleteEditor extends Handsontable.editors.AutocompleteEditor`
handsontable was execute the method（updateChoicesList）when open the options list.
`updateChoicesList`
`const el = this.TEXTAREA_PARENT.querySelector('.wtHolder')`
first  i'm  `el.addEventListener('scorll'， function())`.
then i'm try to `new CustomEvent()` and dispatchEvent() When the list of options scrolls to the bottom；

When I listen to the CustomEvent on the component page, I execute updateChoicesList again to update the options；
But，**My drop-down box option, which automatically scrolls to show the first data**。

I have used this method twice in my project, **but yet another dropdown box will not scroll to the first option.**

**So I would like to know when to use the updateChoicesList method so that my dropdown box options don't automatically go back to the first data displayed.？？**

**Comment by AMBudnik** [comment]
I do not see any tutorials on that but I found related subjects
- https://github.com/handsontable/handsontable/issues/3514 
- https://embed.plnkr.co/muwhuxqJ03UqAnT7ZCXi/
