### ISSUE TITLE
columnDrag doesn’t work inside a table td

### ISSUE THREAD

**Issue by amanvsingh89** [handsontable/handsontable#8934]
### Description
if i add 
```
<div id="example"></div> inside a <table><tr><td> like : 
<table><tr><td> 
 <div id="example"></div>
</td></tr></table>
```

column drag stops working.

### Steps to reproduce

1.Add `<div id="example"></div> `inside table structure
2. Column drags stops working
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environmen
mamp php js 
https://user-images.githubusercontent.com/7792266/141647406-c975b88c-85fb-435a-a87e-a5280e6a9ba3.mov

t
* Handsontable version:  Handsontable 0.8.4

https://user-images.githubusercontent.com/7792266/141647403-8dae6439-5869-450f-90be-10bdbe2cc5b7.mov

:
* Browser Name and version: Chrome
* Operating System: Mac Os Monterey

**Comment by AMBudnik** [comment]
Hi @amanvsingh89 

I have created a simple table and autofill works as expected https://jsfiddle.net/enm61jhu/5/ (used version v10, tested on latest Chrome).

![Kapture 2021-11-15 at 10 59 33](https://user-images.githubusercontent.com/10757813/141761535-7025542e-e140-46e7-87d4-285a1a05d1fd.gif)

Could you share your code for this example?

**Comment by amanvsingh89** [comment]
I am using the free source, and version is : Handsontable 0.8.4

**Comment by AMBudnik** [comment]
Hi @amanvsingh89 Handsontable v0.8.4 was published in July, 2014 (ref: https://github.com/handsontable/handsontable/releases?page=17) and we cannot guarantee that it will work correctly with the use of the newest browsers.
