### ISSUE TITLE
[8.3.0+] Batching of loadData and validateRows fails

### ISSUE THREAD

**Issue by piotrmod92** [handsontable/handsontable#8938]
### Description
Hello HoT team,

I tried to combine **loadData()** and **validateRows()** within one batch to prevent my table from double rendering (otherwise, I experience an anaesthetic flickering of invalid cells). I tried **batch()**, **batchRender()**, as well as **suspendRender()/resumeRender()**, but all the methods ended up with the following error:

_Assertion failed: Expecting an unsigned number._

Note that the example uses columns array and a custom column validator.

Please let me know if combining **loadData()** along with **validateRows()** in one batch makes sense. Do you see any possible workaround? I will surely post mine if I find an alternative.

Thank you for your work!
Piotr

### Steps to reproduce

1. Enter the demo below,
2. Open the web console,
3. Wait 3 seconds, until the setTimeout triggers the batch; the error will be displayed.

### Demo
https://jsfiddle.net/1uewsc7L/25/

### Environment
* Handsontable version: 10.0.0
* Browser Name and version: Chrome/78.0.3904.130 Electron/7.2.4
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @piotrmod92 

it seems that the validation was called too soon. If we postpone the call it works well https://jsfiddle.net/byo5e1p3/2/

**Comment by piotrmod92** [comment]
Hi @AMBudnik 

Thanks for your response. That's an interesting finding.

As I tested the solution further, I think the **setTimeout()** pushes the validation out of the **batch()** callback function (it can be easily checked with console logs). The code does not throw an error, but at the same time we are deprived of batching effect.
