### ISSUE TITLE
Handsontable source code references

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8948]
### Description

All links in the docs (11.0 and next) that reffers to the source code of Handsontable returns 404. The source code of the handsontable is moved to the subdirectory and the links need to be updated.

### Links

* https://handsontable.com/docs/setting-options/#cascading-configuration - „Global Meta” link;
* https://handsontable.com/docs/api/auto-column-size/#options - „Source code” link;
* …and more.

**Comment by warpech** [comment]
Closing as done in #9137
