### ISSUE TITLE
bad performance when open formular plugin

### ISSUE THREAD

**Issue by crystalstone** [handsontable/handsontable#8956]
when I open formular plugin,  filter or sort will have bad performance，can you optimise it ？

**Comment by AMBudnik** [comment]
Hi @crystalstone 

Can you briefly introduce your project? Generally, the more formulas are in the table the slower it may work. But that should be noticeable using larger datasets. Please specify 
- the size of your dataset
- percentage of cells that contain formulas
- functionalities that you use additionally (like mentioned, sorting and filtering)
- do you validate/alter/sort/filter data on initialization or when data is loaded

If you do not want to share that data on Github you can also send us an email at support@handsontable.com

**Comment by crystalstone** [comment]
project logic:We use ajax to load source data（max size: 10w rows and 30 cols）from server;  and Put these data into a handsontable instance; For support multiple sheets，We has a class ——SheetManager to manage lots of handsontable instances; each handsontable instance open formus plugin default.
At begining，we do not has any formulas in the sheet，just has source data；But when I set 'filter plugin' enable,  That will spend more time than do not open formulas plugin. 

for example:
5w rows 10cols —— （1）open formulas plugin： click filter will cost 4s ；（2）close formulas plugin：just cost 0.4s



<img width="666" alt="2C59A3C7-2558-4A65-AF18-67EFE9637B27" src="https://user-images.githubusercontent.com/5661922/142989240-85f93faf-347c-4ef1-9586-b6a6fd7c77ab.png">




(1) the size of your dataset
5w ~ 10w rows and 20~30 cols ; 
(2) not contain any formulas also has bad performance
(4) do not filter data when data is loaded, we has a filter button ,  User click the button to make filter enabled

**Comment by crystalstone** [comment]
> Hi @crystalstone
> 
> Can you briefly introduce your project? Generally, the more formulas are in the table the slower it may work. But that should be noticeable using larger datasets. Please specify
> 
> * the size of your dataset
> * percentage of cells that contain formulas
> * functionalities that you use additionally (like mentioned, sorting and filtering)
> * do you validate/alter/sort/filter data on initialization or when data is loaded
> 
> If you do not want to share that data on Github you can also send us an email at [support@handsontable.com](mailto:support@handsontable.com)

When I click filter button, will cause modify data hook, which has been added in formula plugin. the 'onModifyData' funtion  cost lots times.

This also happeded when i init my source data sheet.

![8024A6B9-9903-4A29-A5BB-47392944F671](https://user-images.githubusercontent.com/5661922/142991226-6cee2d8d-d912-49ea-becb-f48a513bf03a.png)

**Comment by crystalstone** [comment]
formular updatePlugin will called when i update filter plugin setting. it is not useful , i think.

**Comment by crystalstone** [comment]
countEmptyRows api and so on will cause 'modifyData' hook and make bad performance.

**Comment by AMBudnik** [comment]
And can you send us some code samples? I do not know what does that `filter` button does (it is not a part of Handsontable UI).'

Can you share it here http://jsfiddle.net/mvs6yg0z/5/? I have 3 sheets of Handsontable, each 20 x 10 fields with all of them having formulas enabled. I added a button with the ability to filter the columns and I do not see any delay.

**Comment by crystalstone** [comment]
> 
filter button  just update filter setting:
const goToFilter = true (or false)
instance?.updateSettings({
        dropdownMenu: goToFilter
          ? ['filter_by_value', 'filter_action_bar']
          : false,
        filters: goToFilter,
      })

instance?.updateSettings  will call formular updatePlugin  always which cause bad performance

**Comment by crystalstone** [comment]
> 
filter button  just update filter setting:
const goToFilter = true (or false)
instance?.updateSettings({
        dropdownMenu: goToFilter
          ? ['filter_by_value', 'filter_action_bar']
          : false,
        filters: goToFilter,
      })

instance?.updateSettings  will call formular updatePlugin  always which cause bad performance

**Comment by AMBudnik** [comment]
My button in the demo (JSFiddle above) does the same when it comes to updating the instance of Handsontable. So if your works slower than maybe the response of `goToFilter` takes more time than expected.

**Comment by crystalstone** [comment]
> And can you send us some code samples? I do not know what does that `filter` button does (it is not a part of Handsontable UI).'
> 
> Can you share it here http://jsfiddle.net/mvs6yg0z/5/? I have 3 sheets of Handsontable, each 20 x 10 fields with all of them having formulas enabled. I added a button with the ability to filter the columns and I do not see any delay.

another reason of bad performance is onModifyData function will always be run,  when i use countEmptyRows and so on

**Comment by crystalstone** [comment]
> instance?.updateSettings will call updatePlugin function of formula plugin always which cause bad performance



> My button in the demo (JSFiddle above) does the same when it comes to updating the instance of Handsontable. So if your works slower than maybe the response of `goToFilter` takes more time than expected.

no,  the reason is 
(1) "instance?.updateSettings will call updatePlugin function of formula plugin always which cause bad performance" 
(2) onModifyData function will always be run, when i use countEmptyRows and so on

eg: I modify formula plugin like the below pic, performance better

![image](https://user-images.githubusercontent.com/5661922/143030041-0dab18f0-1ee9-46be-b843-6d3a50baa8af.png)

**Comment by crystalstone** [comment]
> My button in the demo (JSFiddle above) does the same when it comes to updating the instance of Handsontable. So if your works slower than maybe the response of `goToFilter` takes more time than expected.

5w rows may has bad performance obviously； 20 rows can not find bad performance obviously

**Comment by crystalstone** [comment]
> And can you send us some code samples? I do not know what does that `filter` button does (it is not a part of Handsontable UI).'
> 
> Can you share it here http://jsfiddle.net/mvs6yg0z/5/? I have 3 sheets of Handsontable, each 20 x 10 fields with all of them having formulas enabled. I added a button with the ability to filter the columns and I do not see any delay.

I have changed the code of http://jsfiddle.net/mvs6yg0z/5/,  set hot 5w rows .   you can open formula plugin ， click filter button。 and close formula plugin，click filter button。compare these two situation.

**Comment by AMBudnik** [comment]
Can you resend the demo, please? It has to be forked for me to see your changes.

**Comment by crystalstone** [comment]
> Can you resend the demo, please? It has to be forked for me to see your changes.

ok, please wait some time, may be one or half day.

**Comment by crystalstone** [comment]
> Can you resend the demo, please? It has to be forked for me to see your changes.
you can look this :  https://jsfiddle.net/crystalstone/7t42acrz/95/
(may need wait 8~9s to show table)

![image](https://user-images.githubusercontent.com/5661922/143227367-1a290d27-64c7-4533-96ae-ed517a69166d.png)

**Comment by adrianszymanski89** [comment]
Hi @crystalstone thank you for all of the information you give us. We managed to test other cases and it looks that indeed there is some kind of performance issue. We will report it and we'll let you know when the issue will be solved.

Loading times for table size of 50 000 x 10 cells:

- Default table: about 2s;
- Formulas, dropdown menu and filters added: about 15s;
- Dropdown menu and filters added: about 13s;
- Formulas alone: about 5s;
- 
Loading times for table size of 25 000 x 10 cells:

- Default table: about 1s;
- Formulas, dropdown menu and filters added: about 5s;
- Dropdown menu and filters added: about 3s;
- Formulas alone: about 4s;
- 
Loading times for table size of 10 000 x 10 cells:

- Default table: about 1s;
- Formulas, dropdown menu and filters added: about 3.5s;
- Dropdown menu and filters added: about 2s;
- Formulas alone: about 3s;

**Comment by crystalstone** [comment]
> 

hi， the formulas plugin has other problems
（1）when use sort and filter ,  formula may be error 
   (2)  when hide or show rows / cols ,  formula may be error  tow

**Comment by AMBudnik** [comment]
Hi @crystalstone 

IF you have spotted more errors can we please talk by email at support@handsontable.com? We will test them one by one and report on Github separately
