### ISSUE TITLE
The `test:e2e.watch` script tends to crash with an error.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#8961]
### Description
When running the `test:e2e.watch` script, I (usually) get the following error:

```
Error: listen EADDRINUSE: address already in use :::8086
```

It looks like the `test:e2e.puppeteer` script is triggered too early (?), while the first batch of commands (`build:umd` and `test:e2e.dump`) is still ongoing, then after the build is finished, the `test:e2e.puppeteer` command is not terminated properly, blocking itself from being re-run.

### Steps to reproduce

1. Call `npm run test:e2e.watch` from the `handsontable` directory

### Your environment
* Handsontable version: `11.0.1`
* Operating System: macOS Catalina

**Comment by Siemienik** [comment]
Slack thread with some details: https://handsoncode.slack.com/archives/C4PV4S33Q/p1637685051029300

**Comment by aninde** [comment]
Works as expected with v11.1.0.

**Comment by AMBudnik** [comment]
Closed as fixed in Handsontable v11.1.0
