### ISSUE TITLE
the formulas plugin not do nothing when sort or filter or hide rows ... lead to data error

### ISSUE THREAD

**Issue by crystalstone** [handsontable/handsontable#8977]
hi， the formulas plugin has some problems
(1）when use sort and filter , formula may be error
(2) when hide or show rows / cols , formula may be error too

**Comment by AMBudnik** [comment]
Hi @crystalstone 

to mark an issue as a `bug` I would need to get some more details about the case - demo and /or a scenario of reprodcution.
