### ISSUE TITLE
Display Excel in webpage using Handsontable

### ISSUE THREAD

**Issue by Muruganandhu** [handsontable/handsontable#898]
hi I had a requirement to display Excel in webpage, only one sheet which is selected, I have tried with handsontable, I did some what 75 % of the requirement and I was not able to complete fully due to importing full excel format using the handsontable feature.

can any one help one this.

Thanks,
Muruganandhan

**Comment by AMBudnik** [comment]
Issue closed in lack of author's response.

**Comment by varanmahesh** [comment]
https://github.com/varanmahesh/HandsonTableImport.git .Check this out. I have built an import function through which you can display excel on handsontable

**Comment by AMBudnik** [comment]
Hi @varanmahesh that's definitely something to check.
