### ISSUE TITLE
Update the "Hello world" page

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#8980]
Update the [Hello world](https://handsontable.com/docs/hello-world/) page:
~~- [ ] Migrate the CodeSandbox demo to the docs' `::: example` containers~~
  ~~- [x] JavaScript~~
  ~~- [ ] React~~
  ~~- [ ] Angular~~
  ~~- [ ] Vue~~
- [x] Change the title from "Hello world" to "Demo"
- [x] Rewrite the page's text to stress the fact that the demo is not an end-user showcase, but is meant to let developers see the code
- [x] Redirect URL: `/hello-world/` to `/demo/`

### Links
https://handsontable.com/docs/hello-world/

**Comment by warpech** [comment]
The "Demo" example is now online: https://handsontable.com/docs/demo/

Some points from the above checklist are not done yet. They should be addressed soon or moved to new issues.

**Comment by warpech** [comment]
Closing as all of the tasks are either done or decided to be out-of-scope
