### ISSUE TITLE
nestedHeaders do not show headers for columns without data at first row

### ISSUE THREAD

**Issue by mirkogeest** [handsontable/handsontable#8984]
### Description
The nested column headers are only shown when the first row has data set on the corresponding column. Also, if some column data is missing, then the last column does not show the header.

My case is that I show a grid where only the first 2 columns have data: the user has to fill the rest of the data. But how will he fill it if there are no column headers?

I've seen some solution setting a first hidden row with all null data, but in my case this would be written to our database, and it would also affect row count, stats, ...

### Steps to reproduce
Please see the demo

### Demo
https://jsfiddle.net/mirkocucumber/0wmzh63a/1/

### Your environment
* React wrapper version: 0.3.2
* Handsontable version: 11.0.1
* Browser Name and version: Version 96.0.4664.55 (Official Build) (arm64)
* Operating System: Mac OS Big Sur

**Comment by adrianszymanski89** [comment]
Hi @mirkogeest we have almost identical case already here: https://forum.handsontable.com/t/issue-with-handsontable-nested-headers-for-empty-grid/5676

Can you please confirm if that's the same situation that you have?

**Comment by mirkogeest** [comment]
Hi @adrianszymanski89, yes it's the same issue, with some more fail cases. The solution proposed there is not acceptable for me. If a grid has headers and/or dataSchema, why is it not showing them? No excel like tool works this way!

**Comment by AMBudnik** [comment]
Hey @mirkogeest 

have you also seen https://github.com/handsontable/handsontable/issues/8587 marked in the forum post from @adrianszymanski89 comment? If that is your case then that issue is reported as a bug (and regression) and will be solved soon.

**Comment by AMBudnik** [comment]
Ah, sorry for the first confusion. I see what's going on, and that is a `bug`.

We do not tend to show empty columns without a dataset, but once you define that you have columns like here https://jsfiddle.net/6uy4803x/7/ it works all well, and headers are shown. However, for `nestedHeaders` is does not work. Once I add them the page is empty. 
This issue does not seem to be related to regression from v8.4.0 (it works the same in v8.0.0).

Thank you for sharing this issue report with us @mirkogeest 
I will notify you as soon as we fix it.

**Comment by AMBudnik** [comment]
Hi @mirkogeest 

We have fixed corresponding issues in Handsontable v11.1.0 and it seems that this issue is also solved https://jsfiddle.net/615e94ws/
Please update and let me know if it works for you.
Here https://handsontable.com/docs/release-notes/#_11-1-0 is a full list of changes

(CC: @aninde)
