### ISSUE TITLE
Docs: Bring back the Hello World page

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#8989]
In #8988, we temporarily hid the Hello world page (for versions `9.0`, `10.0`, and `11.0`), due to CodeSandbox problems.

To do in this issue:
- **After** #8980 is done (i.e. the demos are successfully migrated from CodeSandbox), bring the Hello World pages back

**Comment by warpech** [comment]
Done in https://github.com/handsontable/handsontable/pull/8982. Some remaining tasks are tracked in https://github.com/handsontable/handsontable/issues/8980
