### ISSUE TITLE
exporting file as csv in react

### ISSUE THREAD

**Issue by zekhoi** [handsontable/handsontable#8992]
I have an issue while exporting the data, i have followed the documentation but there is no exportfile with react documentation. Can somebody help me?

**Comment by AMBudnik** [comment]
Hi @zekhoi 

It seems to be the same topic as this one https://forum.handsontable.com/t/how-to-exportfile-in-react-nexjtjs/5715 where my colleague shared an example of a couple of hours ago.

If you would still have any questions regarding the topic please feel free to write to us at support@handsontable.com
