### ISSUE TITLE
Docs: Change duplicate topic titles

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#8993]
To do:
- [x] Change duplicate topic titles and menu items (every topic title should be unique)
- [x] Don't edit links and filenames for now

**Comment by kirszenbaum** [comment]
Done in #9003 , moving to Done

**Comment by AMBudnik** [comment]
Closed with the fixed merged to `develop` described by https://github.com/handsontable/handsontable/pull/9003#event-5732632547
