### ISSUE TITLE
Docs: Shorten `metaTitle` tags

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#8995]
To do:
- [ ] Shorten all `metaTitle` tags. Get rid of redundant info so that each `metaTitle` can display in full on hovering over the tab in the browser

**Comment by AMBudnik** [comment]
@kirszenbaum could we make a small change here so the naming is the same for both wrappers? 
![Zrzut ekranu 2021-12-3 o 13 19 46](https://user-images.githubusercontent.com/10757813/144601581-2a1df27a-77db-499a-a59f-7af696c56ea0.png)

**Comment by kirszenbaum** [comment]
@AMBudnik - I didn't change that, as I guess the disparity comes from the code:

<img width="593" alt="1" src="https://user-images.githubusercontent.com/29247866/144611929-8da8b545-4e49-4c3d-9483-a5d18cbf326c.png">
<img width="620" alt="2" src="https://user-images.githubusercontent.com/29247866/144611951-7da776c7-6ae8-460b-93d8-badd72bf6ae9.png">

But the component is called `HotColumn` anyway:
<img width="468" alt="3" src="https://user-images.githubusercontent.com/29247866/144612166-6cf5717b-b6b5-4bac-bfe3-96303c9d0afd.png">
<img width="465" alt="4" src="https://user-images.githubusercontent.com/29247866/144612196-b54630f1-2558-434f-a168-cbbc877bfca2.png">

So you're right, let's change it to `HotColumn`. I'll make the change in #9003.

**Comment by AMBudnik** [comment]
@kirszenbaum is that still valid?

**Comment by kirszenbaum** [comment]
@AMBudnik – no, since we changed SEO metadata in #9820 anyway. Closing.
