### ISSUE TITLE
Docs: Missing info on Handsontable support for different HyperFormula versions

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#8999]
To do:
- [ ] Add info on which version of Handsontable supports which version of HyperFormula

- Handstontable 9 supports HyperFormula 1.0 
- Hyperformula 1.3 supports Handsontable 10 and later

**Comment by kirszenbaum** [comment]
Done in #9004, moving to Done

**Comment by AMBudnik** [comment]
Closed with the merge of https://github.com/handsontable/handsontable/pull/9004 
Thank you for adding that specification @kirszenbaum I'll update the Client
