### ISSUE TITLE
Handsontable looks up the wrong column configuration when a column's "data" field is set to a function

### ISSUE THREAD

**Issue by FooBarWidget** [handsontable/handsontable#900]
Consider this:
<pre>
var counter = 0;

function model(name) {
  var result = function(row, value) {
    return name;
  }

  if (false) {
    // Workaround: change string representation on every call.
    var stringRepresentation = result.toString();
    stringRepresentation += " /* " + (counter++) + " */";
    result.toString = function() {
      return stringRepresentation;
    }
  }
  return result;
}

$('#data_table').handsontable({
  data: [{ a: 1, b: 2 }],
  columns: [
    {
      type: "numeric",
      data: model("123")
    },
    {
      type: "numeric",
      data: model("not text")
    }
  ]
});
</pre>

This will create a table with two cells, with contents "123" and "not text". The intention is that the first cell is always valid, and the second cell always invalid.

After the table is loaded, doubleclick on "123" and modify its value. "not text" suddenly becomes valid even though we did not modify it. This is because Handsontable is looking up the incorrect element in the "columns" array. `datamap.colToProp` failed us here.

The reason why that happened is because `colToProp` maps the value of the "data" field to a column number. Although `model("123")` and `model("not text")` returns distinct function objects, they have the same string representation, causing colToProp to map both functions to a single column number.

By changing `if (false)` to `if (true)` in the above example, the code will ensure that each function instance has a different string representation, which fixes the bug. You will probably want to do this automatically in Handsontable.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by budnix** [comment]
Hi,

I tested this behavior with the newest version of Handsontable and it seems to be fine - http://jsfiddle.net/qrduhh7b/1/. Can you confirm that?

**Comment by budnix** [comment]
Issue will stay closed till an author's reply.
