### ISSUE TITLE
vue custom hot-renderer mess up with manualColumnMove

### ISSUE THREAD

**Issue by hank-cp** [handsontable/handsontable#9002]
### Description
Using vue component as custom cell renderer, and enable `manualColumnMove` at the same time, when the column dragging is done, the hot-renderers doesn't renderer expected column. please see the demo belows.

Also, when using plain inline cell renderer (as another demo below), everything works well as expected.

### Steps to reproduce

1. go to the [vue custom hot-renderer demo](https://jsfiddle.net/pLkvs4bj/) below
2. drop the column *p* ahead of column *image*
3. column *p* is moved but it's renderered by `ImageRenderer`, which is unexpected, as well as column *image*

### Demo

vue custom hot-renderer demo: https://jsfiddle.net/pLkvs4bj/
plain inline cell renderer demo: https://jsfiddle.net/5xn9s4kd/1/

**Comment by adrianszymanski89** [comment]
Hi @hank-cp 

Thank you for your message. We managed to recreate the problem and it seems that it occurs when all of the columns are created by custom renderer.

Example: https://jsfiddle.net/uwftvd9y/4/

We will investigate this issue further and we'll keep you updated.

**Comment by ssprusakov** [comment]
Hi, i wrote about this problem in #7647

**Comment by adrianszymanski89** [comment]
HI @ssprusakov thank you for the information!

**Comment by AMBudnik** [comment]
As This report describes the same issue as #7647 we will close it and update it after #7647 is fixed.
