### ISSUE TITLE
[10.0.0] Typo in the valueAccordingPercent helper

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9006]
### Description

There is a typo in the [valueAccordingPercent](https://github.com/handsontable/handsontable/blob/2dbc605c14b4f13eb25b77679f1c1cab98a274ad/handsontable/src/helpers/number.js#L114) helper. Cause that the _AutoRow_ and _AutoColumn_ plugins throw an error when the sync limit option is used.

### Steps to reproduce

1. Go to https://jsfiddle.net/budnix/nswdxLp9/1/;
2. In the console you'll see `Uncaught TypeError: t.tostring is not a function` error.

### Demo

https://jsfiddle.net/budnix/nswdxLp9/1/

### Your environment
* Handsontable version: 10.0.0
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment]
Note to myself: update [forum](https://forum.handsontable.com/t/bug-in-function-valueaccordingpercent/5730)

**Comment by aninde** [comment]
This issue is fixed for v11.1.0 https://jsfiddle.net/px43hwqc/
