### ISSUE TITLE
Vue 3: Update badges

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9009]
### Description

Our new wrapper for Vue 3 has wrong badges in the `README.md` file. All badges should be updated to point to the relevant Vue 3 resource. Warning - some badges need to be configured blindly, because things like the NPM package do not exist yet.

I guess that @jansiegel can provide the snippets for these badges if needed and review the changes.

### Links

- https://github.com/handsontable/handsontable/blob/ddfd5bce763a9931daaecee805662edfc367eb9d/wrappers/vue3/README.md

**Comment by kirszenbaum** [comment]
@jansiegel - I guess we neeed to update the links below. There's no npm package yet, I'm guessing we'll call it `@handsontable/vue3`. 

| Old | New |
| --- | --- |
| https://img.shields.io/npm/dt/@handsontable/vue.svg | https://img.shields.io/npm/dt/@handsontable/vue3.svg |
| https://img.shields.io/npm/dm/@handsontable/vue.svg | https://img.shields.io/npm/dm/@handsontable/vue3.svg |
| https://npmjs.com/package/@handsontable/vue | https://npmjs.com/package/@handsontable/vue3 |
| https://app.codeship.com/projects/1ec34290-ed0a-0131-911c-1a47c8fbcce0/status?branch=master | ? |
| https://app.codeship.com/projects/26649 | ? |
| https://app.fossa.io/api/projects/git%2Bgithub.com%2Fhandsontable%2Fhandsontable.svg?type=shield | ? |
| https://app.fossa.io/projects/git%2Bgithub.com%2Fhandsontable%2Fhandsontable?ref=badge_shield | ? |
| https://snyk.io/test/github/handsontable/handsontable/badge.svg?targetFile=package.json | https://snyk.io/test/github/handsontable/handsontable/badge.svg?targetFile=wrappers/vue3/package.json |
| https://snyk.io/test/github/handsontable/handsontable?targetFile=package.json | https://snyk.io/test/github/handsontable/handsontable?targetFile=wrappers/vue3/package.json |

**Comment by warpech** [comment]
> Do we know how we're going to publish #8991?

The PR #8991 should be merged to the `develop` branch ASAP. This will enable it only in the staging version of our docs (https://dev.handsontable.com/docs/next/), which is useful for early adopters who will get this link from us by request.

For anyone else, the content of that PR will become only after the next release. Let's discuss on the next Weekly meeting how exactly. Will we:
- we create `docs/11.1` from `docs/next`
- copy the contents of `docs/next` to `docs/11.0`, but add special information on the Vue3 pages that this wrapper is avaliable since 11.1. I prefer this.

**Comment by kirszenbaum** [comment]
Done in #9020, closing

**Comment by warpech** [comment]
Note that one more thing is needed after the first release: https://github.com/handsontable/handsontable/issues/9090
