### ISSUE TITLE
Fix Snyk badge for Handsontable

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9010]
### Description

It seems that our Snyk badge for Handsontable was not updated as it should in https://github.com/handsontable/handsontable/pull/8851

To fix this, it is required to update the project (done my me already) and update the READMEs.

In both README files (https://github.com/handsontable/handsontable/blob/master/README.md, https://github.com/handsontable/handsontable/blob/master/handsontable/README.md) the badge snippet should be updated to:

```
[![Known Vulnerabilities](https://snyk.io/test/github/handsontable/handsontable/badge.svg?targetFile=handsontable/package.json)](https://snyk.io/test/github/handsontable/handsontable?targetFile=handsontable/package.json)
```

Based on the information from https://support.snyk.io/hc/en-us/articles/360003997277-Badge-Support-for-Repositories

**Comment by kirszenbaum** [comment]
Done in #9017, moving to Done
