### ISSUE TITLE
The NestedRows plugin throws an error with wrong dataset

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9018]
### Description

The _NestedRows_ plugin throws an error when the `updateSettings` method is called. This only happens when Handsontable is initialized with `nestedRows: true` setting and when the dataset is not matched to the plugin requirements - is not an Array of Objects. At first, the plugin logs an error and disables itself but it turns back on settings change.

### Steps to reproduce

1. Go to https://jsfiddle.net/budnix/9L07jwtm/1/;
2. After the timeout (1,5s) the `updateSettings` method is called;
3. As a result the _NestedPlugin_ throws a TypeError `Uncaught TypeError: Cannot read properties of null (reading 'length')`.

### Demo

https://jsfiddle.net/budnix/9L07jwtm/1/

### Your environment
* Handsontable version: 11.0.1
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment]
Note to myself - check https://github.com/handsontable/handsontable/issues/7017 after release

**Comment by aninde** [comment]
This issue is fixed for the upcoming v11.1.0 https://jsfiddle.net/w3ohuraz/. From now on the plugin stops working when an incorrect dataset is given and the logs inform the user about it.

**Comment by AMBudnik** [comment]
Closed as fixed in Handsontable v.11.1.0
