### ISSUE TITLE
afterSelection and afterDeselect events dont work

### ISSUE THREAD

**Issue by tamtakoe** [handsontable/handsontable#902]
onSelection
onSelectionByProp
onSelectionEnd
onSelectionEndByProp
afterSelectionByProp
afterSelectionEnd
afterSelectionEndByProp
work

afterSelection
afterDeselect
not work

**Comment by AMBudnik** [comment]
`afterSelection`
`afterDeselect`
Hooks are working as expected in the newest version, demo: http://jsfiddle.net/yz1ue6b2/
