### ISSUE TITLE
`updateSettings` causes `updatePlugin` calls for all previously-enabled plugins.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#9021]
### Description
When calling `updateSettings`, all the enabled plugins get their `updatePlugin` method called, regardless of their `PLUGIN_KEY` being present in the new settings.
For example, calling `updateSettings({})` on an instance with the Merge Cells plugin previously enabled will cause the plugin to disable and re-enable itself. This may result in unexpected scenarios.

Related tasks:
- #6806

### Demo
https://jsfiddle.net/js_ziggle/gt9xu3h4/

**Comment by aaronbeall** [comment]
Just want to throw in my +1 for this issue. I recently updated from 7 to 11 and it seems the use of `updateSettings()` (via React props) is breaking a lot of our use cases. I get a lot of null ref errors from HT plugins after an `updateSettings()` is called.

**Comment by aninde** [comment]
Thanks to the fixes in 12.0.0, when updating a previously initialized plug-in with updateSetting, there is no recalling. Updated demo https://jsfiddle.net/mvzr4yb7/.
