### ISSUE TITLE
[7.2.0+] Cell editor does not open with a `keydown` action if a cell in a multi-cell selection is outside the viewport

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9022]
### Description

Cell editor does not open with a `keydown` action if a cell in a multi-cell selection is outside the viewport. The `beforeKeyDown` event is responding but the cell editor does not open.

### Steps to reproduce

1. go to http://jsfiddle.net/u3sj9t75/2/
2. select cells `A1:A50` by mouse click (if you hold SHIFT + ARROW DOWN the issue is not replicable)
3. press any key

**Before 7.2.0 - correct behavior**
With a `keydown` editor open and the table scrolls to the edited cell

**In 7.2.0 and after**
With a `keydown` editor does NOT open and the table does NOT scroll to the edited cell

### Demo

http://jsfiddle.net/u3sj9t75/2/ - v11.0.1. (latest) - broken

### Your environment
* Handsontable version: 7.2.0+
* Browser Name and version: Chrome 96
* Operating System: macOS Monterey 12.0.1

Inform 27407

**Comment by liniwalid** [comment]
please take in consideration if different both mouse selection and keyboard selection.
looking forward to see that bug fixed
Thank you

**Comment by AMBudnik** [comment]
Thank you for your input @liniwalid 
I will make sure to notify you once we solve this regression.

**Comment by AMBudnik** [comment]
Hi @liniwalid 

We just released Handsontable v12.1.3 which fixes this issue.

Here https://handsontable.com/docs/release-notes/#_12-1-3 you'll be able to read more about the changes in Handsontable v12.1.3.
