### ISSUE TITLE
Remove Codeship badges from wrappers, add GitHub Actions, SonarCloud

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9024]
### Description

Currently, our README.md files for wrappers have a badge for Codeship service that we no longer use. 

This badge should be replaced with:
- a GitHub Actions "Tests" badge (same as in https://github.com/handsontable/handsontable/blob/develop/README.md). 
- a Sonarcloud badge (same as in https://github.com/handsontable/handsontable/blob/develop/README.md). 

These badges cover the whole workspace - so they are relevant for all wrappers.

### Links

- https://github.com/handsontable/handsontable/blob/develop/wrappers/angular/README.md
- https://github.com/handsontable/handsontable/blob/develop/wrappers/react/README.md
- https://github.com/handsontable/handsontable/blob/develop/wrappers/vue/README.md
- https://github.com/handsontable/handsontable/blob/develop/wrappers/vue3/README.md when ready

**Comment by warpech** [comment]
This is on hold, until I clarify if we actually use Codeship or not in the wrappers.

**Comment by warpech** [comment]
Ok, I don't see Codeship triggered for recent builds and the last build on Codeship was 2 months ago. These badges can be removed.

**Comment by kirszenbaum** [comment]
Done in #9038, moving to **Done**
