### ISSUE TITLE
How to flip the direction of the excel behavior so that new records are columns not rows ?

### ISSUE THREAD

**Issue by hazem-taha** [handsontable/handsontable#9028]
Hello,

How to flip the direction of the excel behavior so that new records are columns not rows, so that new records are added in horizontal direction..

Is there a way to do this ?

Thanks in advance.

**Comment by AMBudnik** [comment]
Hi @hazem-taha 

Could you share any drafts of what it should look like before and after adding a new record? 
The first thing that came to my mind is a structure like this https://jsfiddle.net/qmbfnkau/1/ but if you need anything else than please specify the details.

**Comment by hazem-taha** [comment]
@AMBudnik 
Exactly this is what I'm trying to achieve!! Thanks Alot, **BUT** the big challenge here for me is how to set the cell type for each cell separately ?
Since the default behavior is that we set the cell type (ex: dropdown) and this affects the entire column in a vertical way, but in my case, I'm welling to do this in a horizontal way so that the dropdown cells are for the entire row, not for the column, was I clear describing this ?

**Comment by hazem-taha** [comment]
https://user-images.githubusercontent.com/46519001/145381957-c15572cb-b5e0-4b89-8229-d935a10abcb6.mov

this is an example for what I need to do..

**Comment by AMBudnik** [comment]
>Exactly this is what I'm trying to achieve!! Thanks Alot, BUT the big challenge here for me is how to set the cell type for each cell separately ?

To do that you can use `cells`, `cell` and `setCellMeta()` method. I this that `cells` might b the best option if you plan to add the same `type` to all the cells in the same row.

**Comment by hazem-taha** [comment]
Great, thanks alot @AMBudnik 
Regarding that code snippet you posted https://jsfiddle.net/qmbfnkau/1/ how are these cells drawn ? since I cannot find that in the JS part, and what is meant by this licence part ? 
![image](https://user-images.githubusercontent.com/46519001/145398690-018294f0-6b45-45ec-aa9b-ed73ca49d716.png)

**Comment by hazem-taha** [comment]
Thanks alot @AMBudnik  🔥 👍

**Comment by AMBudnik** [comment]
I'm happy I could help @hazem-taha 

If you would need anything else please feel free to open a new discussion on Github or send me an email to support@handsontable.com
