### ISSUE TITLE
Horizontally expanding grid not working properly

### ISSUE THREAD

**Issue by hazem-taha** [handsontable/handsontable#9036]
Hello,

I found this example for constructing columns data https://handsontable.com/docs/binding-to-data/#array-of-objects-with-custom-data-schema

and did some changes to apply same idea for rows but it does not work.., my failing snippet is here https://jsfiddle.net/j41hbemn/7/

Thanks in advance

**Comment by hazem-taha** [comment]
I added vue lable by mistake, sorry about that.

**Comment by AMBudnik** [comment]
Thank you for a prompt update. I'm glad that you solved the case.

ps. I will also close the discussion at https://github.com/handsontable/handsontable/discussions/9035 as it mentions the same topic.

For any future cases, you can contact us directly at support@handsontable.com

**Comment by hazem-taha** [comment]
@AMBudnik 
Thanks for your response, but the issue is not solved, I meant I added the issue under vue issues category by mistake.

**Comment by AMBudnik** [comment]
No problem, I will look at it later today and 2ill update you at https://github.com/handsontable/handsontable/discussions/9035 to avoid duplicating the same content
