### ISSUE TITLE
if  have a transform on some parent ,the highlight area are incorrect

### ISSUE THREAD

**Issue by SnowsofKilimanjaro** [handsontable/handsontable#9048]
### Description

 if  have a transform on some parent ,the highlight area is incorrect
### Steps to reproduce

1.
2.
3.

### Demo
[
![image](https://user-images.githubusercontent.com/13759488/146583382-398527d7-b80f-4f7c-913a-6ef9275d43e0.png)
](url)

### Your environment
* Handsontable version:11
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @SnowsofKilimanjaro 

We have issues related to 
* `transform` - `rotate` at https://github.com/handsontable/handsontable/issues/7359 
* `transform` - `scale` at https://github.com/handsontable/handsontable/issues/7580 and https://github.com/handsontable/handsontable/issues/6201

Could you tell me a bit more about the issue you experienced? We definitely need a demo to confirm the issue and check if it works the same across browsers and versions of Handsontable.

**Comment by SnowsofKilimanjaro** [comment]
https://jsfiddle.net/SnowsofKilimanjaro/m0rh3gu8/81/

in the demo  i use  
transform: scale(1.5);
transform-origin: left top;

 when i  select a cell  ,the highlight area is incorrect 
![image](https://user-images.githubusercontent.com/13759488/146864343-9cc16b0b-74e1-4b0c-bd06-1cbbf914d2e2.png)

**Comment by AMBudnik** [comment]
Hi @SnowsofKilimanjaro 

My colleague investigated that case and it seems that this issue is regression. He has created a new issue here https://github.com/handsontable/handsontable/issues/9054 
I will make sure to update you as soon as we fix that issue.

ps. if there's anything missing in his description please feel free to add a comment.

**Comment by AMBudnik** [comment]
Hi @SnowsofKilimanjaro 

I am more than happy to finally announce a fix for this issue. Here's an updated version https://jsfiddle.net/8bsz3d6h/

You can find it fixed in [v14.0.0](https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-0-0)
