### ISSUE TITLE
After sorting, filling a column using drag corner fails 

### ISSUE THREAD

**Issue by cage77** [handsontable/handsontable#9052]
Hello
It seems some re-indexing is not happening correctly after sorting a column (using version 11.0.1).

Steps to replicate

1) Create a table, with several columns.  
2) Fill one of the columns with numeric data for example (i recommend around 10 cells to be filled).
3) Sort that column (make sure the cells are indeed rearranged - because it matters to shuffle a bit the data)
4) go to a different column (that supposes to be empty) and add a value in the first cell.
5) Try to fill the next 3 cells, by dragging down the right-bottom corner of the first cell .

After all these steps, on the column that we try to fill using the right-bottom-corner, some other cells (except the first 4) will appear with  extra data , even our intention is to just fill the first 4 cells for example. The fact that other columns are filled automatically is a problem, because it adds extra data where it should not be (and in big tables, the user might not know the data was altered on different cells). I guess it is a matter if reindexing the table.
![error](https://user-images.githubusercontent.com/16489369/146773614-c7cee103-5615-47b5-9e3f-076ab69f3ec8.png)

**Comment by cage77** [comment]
PS: Note that in my sample everything happen AFTER i sorted the data after the field "Denominator Instances". Issue seems to be there even in version 6.xx

**Comment by cage77** [comment]
Another issue that appears, is for example if you manually type the data, cell by cell in that column, at some point it also fills the other cells automatically (probably based on an old index) - which can generate unwanted data. In the photo below i've typed 0011223456 on the 4th cell and when i went to next cell, the value also appeared on 15th. Then i've typed 9911992233 then after hit enter/return key the same value also appeared on 10 cell.
![error2](https://user-images.githubusercontent.com/16489369/146774182-9034cd88-0bad-468e-9b4a-a6baa1a14abf.png)

**Comment by AMBudnik** [comment]
Hi @cage77 

Thank you for sharing all those examples and descriptions. Would it be too much to ask for a demo to replicate the same scenario? I think that the issue is related to the data type in the columns and maybe their format. But I would need to see the code to confirm. Also, I do not see any other `column Sorting` and `auto fill` issues on our Github board to which I can relate.

**Comment by cage77** [comment]
Good morning Aleksandra, 

I took some time to make a small demo here: https://qmav.co.uk/demo.html (i've reduced a lot of the code in order to keep only things that matters to the case and make it easy to follow)

While i was doing it, i noticed there is an afterChange hook, that supposes to clean the value in a certain way (initialy was an regexp, but to make it more visible, i added a string at the end of the entered value).

So , here it is how things can be reproduced:

Simply visit the demo page, then click on the "Denominator" header column to sort ascending (just click once on that header). Then in the column NPI, at line 4  enter some text (let's say 123) and press enter. Once you press enter, you will see that on line 15 will appear 123[X] (that is "123" the typed text and my control string "[X]" added for demo purposes).

While the data is altered using data[row][col] = newValue  , I've also tried to use hot.setDataAtCell() however, this also triggers the afterChange hook so it will eventually go into an infinite loop and crash.  The problem appears only if the sorting was used previous to entering data.

The challenge is to alter/regexp the freshly typed data, after the sort (on a different column) was used. 

If you need more info please let me know (I also commented in the code the line that causes the duplicate line to be generated).

**Comment by AMBudnik** [comment]
Thank you for the additional details, @cage77  Could you also send over the JavaScript part?
I can access it from Chrome, but it's minified so extremely hard to read.

![Zrzut ekranu 2021-12-21 o 12 53 54](https://user-images.githubusercontent.com/10757813/146925927-ad753b0f-accf-4cfb-94ad-342a41e2cd10.png)

The key to solving every issue is to be able to debug it, so if you could share the code via JSFiddle or any other code sandbox that allows debugging the code that would be perfect.

**Comment by cage77** [comment]
Hi Aleksandra - I am sorry, I forgot that server has enabled some optimizations to reduce the code size.

Pasted here the code in jsfiddle:
https://jsfiddle.net/h1d9rg3k/

**Comment by AMBudnik** [comment]
Thank you. I have only one more doubt. What I'm doing (based on those steps above) is

1. Go to https://jsfiddle.net/5xmh6sLd/
2. Type long numbers in the first 10 cells of the NPI column (they are automatically added [x] for the fist cell and [x][x] for others)
3. Sort NPI column

and I'm not sure what to do in the 4th step. It is written that

>go to a different column (that supposes to be empty) and add a value in the first cell.

but NPI is the only empty column in the grid.

**Comment by AMBudnik** [comment]
We do not recommend using `data[row][col]` reference. To set up the new value i recommend using those `changes` array with the `setDataAtRowProp` like here https://jsfiddle.net/wvnyxhs1/2/. I've tested it out with sorting. And I removed the render() in the hook as it was already being triggered once.

**Comment by AMBudnik** [comment]
I'm happy to hear that @cage77 :) 
Feel free to contact me directly at support@handsontable.com with any questions.
