### ISSUE TITLE
How to apply collapsible/grouped rows for horizontally expanding grid

### ISSUE THREAD

**Issue by hazem-taha** [handsontable/handsontable#9068]
Hello,

I have the below colde for printing a horizontally expanding grid with some rows that needs to be collapsible

```
<template>
  <div id="example1">
    <button class="btn btn-info text-white mb-2" @click="addCol">New</button>
    <hot-table :settings="hotSettings" ref="hotRef"></hot-table>
  </div>
</template>

<script>
import { HotTable } from "@handsontable/vue";
import { registerAllModules } from "handsontable/registry";
import Vuex from "vuex";

registerAllModules();

export default {
  data: function () {
    return {
      template: this.tmplt,
      hotSettings: {
        data: [
          [""],[""],[""],[""],[""],[""],[""],[""], 
        ],
        colHeaders(index) {
          return `Property (${index + 1})`;
        },
        rowHeaders: (i) => {
            console.log('this.tmplt[Object.keys(this.tmplt)[i]]', this.tmplt[Object.keys(this.tmplt)[i]]);
            return this.tmplt[Object.keys(this.tmplt)[i]].title
          },
        rowHeaderWidth: 135,
        minColWidth: 135,
        height: "auto",
        licenseKey: "non-commercial-and-evaluation",
        afterChange: () => {
          if (this.hotRef) {
            this.$store.commit("updateData", this.hotRef.getSourceData());
          }
        },
      },
      hotRef: null,
    };
  },
  mounted() {
    this.hotRef = this.$refs.hotRef.hotInstance;
    this.$store.subscribe((mutation, state) => {
      this.logStoreData();
    });
    this.$store.commit("updateData", this.hotRef.getSourceData());
    this.setupCol();
  },
  store: new Vuex.Store({
    state: {
      hotData: null,
      hotSettings: {
        readOnly: false,
      },
    },
    mutations: {
      updateData(state, hotData) {
        state.hotData = hotData;
      },
      updateSettings(state, updateObj) {
        state.hotSettings[updateObj.prop] = updateObj.value;
      },
    },
  }),
  methods: {
    addCol() {
      let hot = this.$refs.hotRef.hotInstance;
      hot.alter("insert_col", hot.countCols());
      this.setupCol(hot.countCols() - 1);
    },
    logStoreData() {
      for (const [key, value] of Object.entries(this.$store.state)) {
        console.log("key", key);
        console.log("value", value);
      }
    },
    setupCol(col = 0) {
      let hot = this.$refs.hotRef.hotInstance;
      var ind = 0;
      for (var ind = 0; ind < this.hotSettings.data.length; ind++) {
        hot.setDataAtCell(ind, col, "");
      }
    },
  },
  computed: {
    tmplt() {
      let template = {
          name: {
              title: 'Name', 
              type: 'text'
          },
          career: {
              title: 'Career',
              type: 'text',
              readonly: true,
              value: 'Work Information'
          },
          job_title1: {
              title: 'Job Title (1)',
              type: 'text'
          },
          organization1: {
              title: 'Organization (1)',
              type: 'text',
          },
          job_title2: {
              title: 'Job Title (2)',
              type: 'text'
          },
          organization2: {
              title: 'Organization (2)',
              type: 'text',
          },
          job_title3: {
              title: 'Job Title (3)',
              type: 'text'
          },
          organization: {
              title: 'Organization (3)',
              type: 'text',
          },

      };

      console.log('template', template);
      return template;
    },
  },
  watch: {
    hotSettings(newVal) {
      console.log("newVal", newVal);
    },
  },
  components: {
    HotTable,
  },
};
</script>

<style scoped>
</style>

```

I'm trying to make the career related fields to be collapsible, but as per the documentation, in order to do this, the `hotSettings->data` needs to be an array of objects..
https://handsontable.com/docs/row-parent-child/#preparing-the-data-source

Is there a workaround to achieve this in my case ? 

Thanks in advance

**Comment by AMBudnik** [comment]
Hi @hazem-taha  the `__children` key defined a child node. It has to be within your dataset.

**Comment by hazem-taha** [comment]
@AMBudnik 
Thanks for your response.

But I was asking if there is any workaround to apply this when I have a dataset as an array of arrays ? Since the grid I'm building is horizontally expanding not the normal one in which a record is represented as a row.

**Comment by AMBudnik** [comment]
Do you have any draft of how it should look? At the first glance, I am not able to tell how it should look reversed.

**Comment by hazem-taha** [comment]
This is a grid I'm working in which a record is reporesented as a column (horizontally expanding grid)..
![image](https://user-images.githubusercontent.com/46519001/147822735-4e9e620c-da86-4e9a-8bd9-7e28999c486f.png)

I need to make the FYI rows to be collapsible since they may reach over 30 records, in order to decrease the vertical scrolling effort.

In this case, the data set value inside the `hotSettings` object needs to be an array of objects with the use of the `__children` key to imlpement this, but this is not possible in my case since I have to make the data set an array of arrays in order to print a horizontally expanding grid.

**Comment by AMBudnik** [comment]
>I have to make the data set an array of arrays in order to print a horizontally expanding grid.

So as I assume you do not have data at the start of the table, but you want to show something (headers, empty row) and then new data is loaded with what we see on the screenshot?

**Comment by hazem-taha** [comment]
at the start, I have only one column with empty cells
then I use a computed property called `tmplt` that returns a template object I created to use for structuring the columns' rows like this
![image](https://user-images.githubusercontent.com/46519001/147825401-2051e40e-1f27-4350-85d4-ea09eaba30cd.png)

and then I call a custom function called `setupCol` on the `mounted`  ..
![image](https://user-images.githubusercontent.com/46519001/147825492-e74d9c60-1337-417e-be7f-4810aa97e66a.png)

Also I have a button that adds columns by calling the `addCol` method in the previous screenshot.

Here is how my initial `data` looks like..

```
.
.
return {
      template: this.tmplt,
      hotRef: null,
      hotSettings: {
        data: [['']],
        colHeaders(index) {
          return `Property (${index + 1})`;
        },
        .
        .
        .
```
and then for each attribute in the template object I call the `setupCol`.

**Comment by AMBudnik** [comment]
The `nestedRows` functionality will not work in the array data so you would need to return the data object if you want to use that functionality. 

Alternatively, you can use [`hiddenRows`](https://handsontable.com/docs/row-hiding/#step-1-specify-rows-hidden-by-default) to hide those rows after the initialization of the table. Hiding allows you to add identification of hidden rows 

![Zrzut ekranu 2021-12-31 o 15 13 26](https://user-images.githubusercontent.com/10757813/147827663-5fa2bd5f-5ac3-46b1-ac54-126aad17958d.png)

and turns on an option in the context menu to show the rows. And if you need a button or anything like in the `nestedRows` you can attach one by [`afterGetRowHeader` hook.](https://handsontable.com/docs/api/hooks/#aftergetrowheader).

Which option sounds better to meet your requirements?

**Comment by hazem-taha** [comment]
Thanks so much @AMBudnik 
I think I have only one question which is the `hiddenRows` since I think in my case, `data` needs to be an array of arrays not an array of objects.

Thanks again ❤️

**Comment by hazem-taha** [comment]
Hello @AMBudnik 

I tried applying the `hiddenRows` but it is not working in my Vue app..

![image](https://user-images.githubusercontent.com/46519001/147847155-0c3209d4-6c3a-49f3-b4b9-3b1ca3460a54.png)

The rows are still visible..
Another question: How to hide/show rows manually using a button click listener ?

**Comment by AMBudnik** [comment]
if you are using the latest version of Handsontable you need to make sure that the `hiddenRows` plugin is imported and registered. Here is a tutorial that shows how to determine if the plugin is ready to be used https://handsontable.com/docs/vue-modules/ 

Answering the second question. You can call the [`hideRow()` method](https://handsontable.com/docs/api/hidden-rows/#hiderow) for a single row index or [`hideRows()`](https://handsontable.com/docs/api/hidden-rows/#hiderows) for multiple row incides. /just be sure to add `render()` call after you use `hideRow()/hideRows()` as they view does not update automatically, it has to be rendered. 

Here https://handsontable.com/docs/row-hiding/#row-hiding-api-methods you can check how it works.

**Comment by hazem-taha** [comment]
Hello @AMBudnik 
I tried the below
`import {hiddenRows} from 'handsontable/plugins'`
    
`this.hotRef.getPlugin('hiddenRows').hideRows([1, 10])`

but it says 

![image](https://user-images.githubusercontent.com/46519001/147924585-e587da08-cd5e-4aad-9c81-613c3087cf3a.png)


and here is what I get as response from the `getPlugin()` function..
![image](https://user-images.githubusercontent.com/46519001/147924542-2e39df97-b99e-46d8-85f2-5cbf7bcead06.png)

**Comment by AMBudnik** [comment]
At the first glance, your code looks correct. I've made a demo https://jsfiddle.net/snux8fLz/2/ maybe it will help you to spot the difference within the code. If not, please share an example where this issue can be replicable.

**Comment by AMBudnik** [comment]
Hey @hazem-taha do we have any updated on that issue?

**Comment by hazem-taha** [comment]
Oh sorry @AMBudnik 
I forgot to update this issue, yes it works with me fine

```
      let plugin = this.hotRef.getPlugin('hiddenRows');

      plugin.hideRows(........);

      this.hotRef.render();

```

Thanks alot!

**Comment by AMBudnik** [comment]
Thank you for the update. I'm closing this issue as solved.
