### ISSUE TITLE
How to change the background color of the row headers for particular cells ?

### ISSUE THREAD

**Issue by hazem-taha** [handsontable/handsontable#9069]
Hello,

As the title says, How to change the background color of the row headers for **particular** cells instead of the default gray one ?

Thanks in advance.

**Comment by adrianszymanski89** [comment]
Hi @hazem-taha 

Yes, you can do it. Here's an example: https://jsfiddle.net/aszymanski/65kehpL9/28/

**Comment by hazem-taha** [comment]
Thanks @adrianszymanski89 so much,
I have a question, how can I use the `Handsontable` class methods in Vue like in lines 16 and 17 ?

**Comment by adrianszymanski89** [comment]
You have to set `hotRef: null` in the data object and the set the reference to Handsontable instance like this - `this.hotRef = this.$refs.wrapper.hotInstance;`

Now you can use it just as Handsontable reference in Vanilla JS

**Comment by hazem-taha** [comment]
@adrianszymanski89 
Thanks for your response, can you please check if the example url is valid?

**Comment by adrianszymanski89** [comment]
Sorry, indeed the link was wrong, this one is correct: https://jsfiddle.net/4wmbe2t3/

**Comment by hazem-taha** [comment]
![image](https://user-images.githubusercontent.com/46519001/147674322-acc98461-76e6-40f1-b60c-c569c334d9e3.png)

and this is the mounted function

![image](https://user-images.githubusercontent.com/46519001/147674373-17c2be09-3cc9-4b38-af4f-064a46611c02.png)

But getting the below error

`[Vue warn]: Error in mounted hook: "TypeError: Cannot read properties of undefined (reading 'dom')"`

**Comment by adrianszymanski89** [comment]
Hi @hazem-taha 

Here you can find an example how to do it with Vue: https://jsfiddle.net/y2p5vcxs/2/

It's very similar approach, the only thing that you need to keep in mind is that you always have to add `.handsontable` class in CSS in order to overwrite the default class
