### ISSUE TITLE
How to apply formula to the new row when insert

### ISSUE THREAD

**Issue by t-walker-wei** [handsontable/handsontable#9071]
### Description
Automatic apply formula when insert row.

### Steps to reproduce

Steps in https://jsfiddle.net/walker_wei/ezmvs0jk/

### Demo

https://jsfiddle.net/walker_wei/ezmvs0jk/

### Your environment
* Handsontable version: 11.0.1
* Browser Name and version:  Chrome Version 96.0.4664.110 (Official Build) (64-bit)
* Operating System: Window10

**Comment by t-walker-wei** [comment]
I figure out one method is litsen to event **afterCreateRow**
`hot1.addHook('afterCreateRow', (row, amount) => {
      console.log(`${amount} row(s) were created, starting at index ${row}`);
      hot1.setDataAtCell(row, 3, '=SUM(B' + (row + 1) + ':C' + (row + 1) + ')');
});

**Comment by AMBudnik** [comment]
Thank you for a prompt update. That is correct `afterCreateRow` triggers when a new row is added. I'm closing this topic as solved.
