### ISSUE TITLE
Option minSpareRows conflict with setDataAtCell() in afterCreateRow hook

### ISSUE THREAD

**Issue by t-walker-wei** [handsontable/handsontable#9072]
### Description
When try to remove the spare row, the page will stuck in deadloop and keep insert new rows

### Steps to reproduce

1.Right click on spare row to call the menu
2.Click Remove row
3.If comment setDataAtCell() , the deadloop will nerver happen
### Demo

https://jsfiddle.net/walker_wei/13hxav7f/4/

### Your environment
*Handsontable version: 11.0.1
*Browser Name and version: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
*Operating System: Window10

**Comment by AMBudnik** [comment]
Hi @t-walker-wei 

That is intended behavior. Here https://jsfiddle.net/kLx4b8d1/1/ it goes slower.
When you want to add a value to the last row (which is what you are doing in the`31st` line in the demo) the `afterCreateRow` is triggered again as `minSpareRows` is adding a new blank row.

What would be the desired result in your opinion?

**Comment by t-walker-wei** [comment]
> Hi @t-walker-wei
> 
> That is intended behavior. Here https://jsfiddle.net/kLx4b8d1/1/ it goes slower. When you want to add a value to the last row (which is what you are doing in the`31st` line in the demo) the `afterCreateRow` is triggered again as `minSpareRows` is adding a new blank row.
> 
> What would be the desired result in your opinion?

What I want is not go inside the loop keeping insert new row when remove the blank spare row. Your solution is set a delay for setDataAtCell(). If I change timeout from 1500 to 500, the problem still there. From my understanding,  setDataAtCell() function is hook to afterCreateRow somehow.

**Comment by AMBudnik** [comment]
So maybe the `source-`approach then, @t-walker-wei 
You can add the `source` (a string representation of your changes made by the `setDataAtCell` method) and then use it to construct a condition to avoid the loop. Here' an example https://jsfiddle.net/xLd3npza/3/

**Comment by t-walker-wei** [comment]
> So maybe the `source-`approach then, @t-walker-wei You can add the `source` (a string representation of your changes made by the `setDataAtCell` method) and then use it to construct a condition to avoid the loop. Here' an example https://jsfiddle.net/xLd3npza/3/

This method not work. You can rerun jsfiddle and remove line 5 (that blank row), you would see the issue.

**Comment by AMBudnik** [comment]
Thank you for feedback @t-walker-wei 
we will look into this issue and update you soon.

**Comment by AMBudnik** [comment]
Hi @t-walker-wei 

To provide a well-crafted solution based on your requirements I may need to get more details on your project requirements. Can you please send those details to support@handsontable.com ?
