### ISSUE TITLE
How to access dom object from the handsontablel ref  in vue

### ISSUE THREAD

**Issue by hazem-taha** [handsontable/handsontable#9073]
Hello, 

I have this code 
![image](https://user-images.githubusercontent.com/46519001/147674444-60beb9c5-1e02-4fef-9835-c84a1bc0279e.png)

and this is the mounted function

![image](https://user-images.githubusercontent.com/46519001/147674373-17c2be09-3cc9-4b38-af4f-064a46611c02.png)

But getting the below error

`[Vue warn]: Error in mounted hook: "TypeError: Cannot read properties of undefined (reading 'dom')"`

Thanks in advance.

**Comment by adrianszymanski89** [comment]
Issue solved here: https://github.com/handsontable/handsontable/issues/9069
