### ISSUE TITLE
[7.0.0] The comment box disappears once it's added

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9075]
### Description

The comment box disappears once it's added by the context menu.

![Kapture 2021-12-31 at 10 15 18](https://user-images.githubusercontent.com/571316/147814567-67d97d68-03eb-44de-a71a-1d07ee18ab12.gif)

The last working version is 6.2.2.

### Steps to reproduce

1. Go to https://jsfiddle.net/budnix/nohdbtxk/;
2. Trigger the context menu o any cell and click the "Add comment" menu option;
3. As a result, the comment box is added but it disappears after ~500ms.

### Demo

https://jsfiddle.net/budnix/nohdbtxk/

### Your environment
* Handsontable version: 11.0.1
* Browser Name and version: Chrome, FF
* Operating System: macOS Big Sur

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/6661

**Comment by aninde** [comment]
This issue is fixed on the upcoming v11.1.0 https://jsfiddle.net/vhzedyrn/.

**Comment by AMBudnik** [comment]
I'm more than happy to see this issue fixed. Thank you guys! I will update the Clients.
