### ISSUE TITLE
insert_col does not work with formulas

### ISSUE THREAD

**Issue by hazem-taha** [handsontable/handsontable#9078]
Hello,

In my grid, I have some formulas, and the grid itslef is expanding horizontally where records are represented by columns.
I have this in the `hotSettings` object in my Vue app
```
formulas: {
          engine: HyperFormula,
        },
```

when running the below code to insert a new column
`this.hotRef.alter("insert_col", this.hotRef.countCols());`
I get the below error..

![image](https://user-images.githubusercontent.com/46519001/147861143-cee80452-1825-4f60-8c40-03ed9e4fc4c3.png)

at this line as per chrome console..
![image](https://user-images.githubusercontent.com/46519001/147861148-9a0bd427-4a09-42b0-a852-ba46b1489099.png)

Thanks in advance.

**Comment by AMBudnik** [comment]
Hi @hazem-taha 

Are you sure that the reference to the instance is set correctly? Here is what I end up with when turning on the formulas and using your `alter` https://jsfiddle.net/nawkpeu5/2/. It works well, and columns are added at the end of the table.

**Comment by hazem-taha** [comment]
Thanks @AMBudnik 
The reference is set correctly and the formula works fine for the first default column, but when I try to add a new column I get that error.

**Comment by AMBudnik** [comment]
@hazem-taha 

Please guide me on what steps should I take to replicate that issue. Or what should I change in my demo.

When I simply use the button with your `alter` method it works for more than one column.
![Kapture 2022-01-03 at 12 06 48](https://user-images.githubusercontent.com/10757813/147923879-8d654588-c528-4fcc-bbfe-77bd664f4b2b.gif)

**Comment by AMBudnik** [comment]
Hi @hazem-taha 

Could you update me on this subject?
