### ISSUE TITLE
How to add multiple select field to cell in vue

### ISSUE THREAD

**Issue by hazem-taha** [handsontable/handsontable#9079]
Hello,

How to add multiple select field to cell in vue ?

**Comment by AMBudnik** [comment]
Hi @hazem-taha 

Selecting multiple options within one cell is not yet supported. Here is a connected topic https://github.com/handsontable/handsontable/issues/1201

I will close this thread as we have all the information needed in #1201 But I will also set myself a notification to update you as soon as we add this functionality.
