### ISSUE TITLE
Docs: Document the setData() and updateData() methods

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#9080]
To do:
- Document changes made in:
  - #8972 
  - #9037 
 
The changes address #7263.

Input: https://gist.github.com/jansiegel/0d346b860be2e7b8eed53fa374212cb7

**Comment by kirszenbaum** [comment]
Done in #9084, moving to Done

**Comment by AMBudnik** [comment]
Issue closed as added to the Handsontable v11.1.0
