### ISSUE TITLE
Function call typo in helpers/number.js

### ISSUE THREAD

**Issue by andriychuma** [handsontable/handsontable#9082]
### Description
The `valueAccordingPercent()` function in `helpers/number.js` looks to be buggy because of a typo. I guess, `percent.tostring()` should be `percent.toString()`. I found it visually, and didn't investigate whether it affects the library in any way.

### Your environment
The latest `handsontable` code base, at `80dac620e9414d37e0f0b592cf3cd75dcb5e0cad`

**Comment by adrianszymanski89** [comment]
Hi @andriychuma 

This issue is already known to us and will be fixed with the next Handsontable release, you can track it here: https://github.com/handsontable/handsontable/issues/9006

**Comment by AMBudnik** [comment]
Hi @andriychuma 

We recently released Handsontable v11.1.0 where this issue is solved
Here https://handsontable.com/docs/release-notes/ you can find the full list of changes

**Comment by andriychuma** [comment]
Thank you, @AMBudnik!
