### ISSUE TITLE
Invalid behavior when using minSpareRows and dataSchema with default value set

### ISSUE THREAD

**Issue by Antoniossss** [handsontable/handsontable#9083]
### Description
So when you use minSpareRows and dataSchema 
http://jsfiddle.net/Lnepr3dv/1/

additional rows gets added everytime you edit anything in the table 

```
var container = document.getElementById('example');

var hot = new Handsontable(container, {
  data: [],
  minSpareRows: 1,
  rowHeaders: true,
  colHeaders: true,
  contextMenu: true,
    columns: [
    {data: 'foo'},
    {data: 'bar'},
    {data:"third"},
    {data:"forth"}
  ],
  dataSchema:{
  	foo:null,
    bar:"im the default",
    third:null,
    forth:null
  }
});
```

### Steps to reproduce
Open jsfiddle and start changing values in some cells (any cells)

### Demo
http://jsfiddle.net/Lnepr3dv/1/

**Comment by adrianszymanski89** [comment]
Hi @Antoniossss 

This issue is known to us, here are some ideas for the workaround that you can use: https://github.com/handsontable/handsontable/issues/5069
