### ISSUE TITLE
datePickerConfig不能修改语言设置

### ISSUE THREAD

**Issue by yaya1286249672** [handsontable/handsontable#9086]

**Comment by yaya1286249672** [comment]
i18n修改不生效

**Comment by AMBudnik** [comment]
Hi @yaya1286249672 

here https://handsontable.com/docs/internationalization-i18n/ you can read more about i18n config. If that does not work for you I would need to receive details about your implementation to specify what is issing.

**Comment by yaya1286249672** [comment]
这个语言设置没有问题的   想问下设置时间选择器的语言本地化怎么设置   给你看下我的截图

**Comment by yaya1286249672** [comment]
这个语言设置没有问题的  想问下设置时间选择器的语言本地化怎么设置  
使用的是react ：v 17.0.2
handsontable：v11.0

**Comment by yaya1286249672** [comment]
解决了  自己写的bug  哈哈哈
