### ISSUE TITLE
Register the Vue3 wrapper in Snyk and update the Vue3 README.md with the new badge

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9090]
### Description

The Snyk badge in https://github.com/handsontable/handsontable/blob/develop/wrappers/vue3/README.md needs updating, because now it points to the root `package.json` not the Vue3 wrapper's `wrappers/vue3/package.json`.

To fix that, we must first create a subproject in Snyk for the Vue3 wrapper, but that can only be done after the Vue3 wrapper was merged to `master`.

So after the release of 11.1.0 please ping me to create the Vue3 subproject in Snyk, and then insert the following badge code in Vue3 wrapper's `README.md`, to be released in 12.0.0:

```
[![Known Vulnerabilities](https://snyk.io/test/github/handsontable/handsontable/badge.svg?targetFile=wrappers/vue3/package.json)](https://snyk.io/test/github/handsontable/handsontable?targetFile=wrappers/vue3/package.json)
```

**Comment by kirszenbaum** [comment]
Done in #9119, closing
