### ISSUE TITLE
Whether batch selection is supported while cross-column selection is disabled？

### ISSUE THREAD

**Issue by chenxuanzong** [handsontable/handsontable#9091]
### Description

I want to be able to batch select cells in the current column or select cells across rows in the current column and disable range selection across columns. I look at the document and it seems that only single, range, multiple is supported, but this does not meet my requirements. What should I do
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/c6rgz08x/

### Your environment
* React wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @chenxuanzong 

Could you please share examples of the desired result and the example of an operation that should be blocked?
