### ISSUE TITLE
How to set default conditions in filter conditions

### ISSUE THREAD

**Issue by Searworld** [handsontable/handsontable#9092]
### Description

Hello, I want to  set default conditions is 'contain', not 'none',  what should I do ？
![image](https://user-images.githubusercontent.com/23454040/148740962-d3ebeea6-44de-44ba-85b4-133de533d891.png)

I try,  But the styles of all filter conditions are selected，I don't want to select the style

`
const filtersPlugin = this.handsontable.getPlugin('filters')
    data.headerTitle[0].forEach((key, index) => {
     filtersPlugin.addCondition(index, 'contains', [''])
})
filtersPlugin.filter()
`

### Steps to reproduce

1. filter
2.
3.

### Demo

https://jsfiddle.net/handsoncode/dezfbgjt/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by adrianszymanski89** [comment]
Hi @Searworld 

Unfortunately, you can't change the default condition in the filtering options. What you can try to do is to make a custom plugin that will replace the default filtering. We can also offer you consulting regarding this issue. For more information about it, you can contact us at support@handsontable.com

**Comment by Searworld** [comment]
ok. thanks
