### ISSUE TITLE
[RTL] The horizontal scroll not working

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9094]
### Description

The horizontal scroll not working for the main table overlay.

LTR mode:
![Kapture 2022-01-10 at 11 24 45](https://user-images.githubusercontent.com/571316/148750787-1fb04f72-946a-430f-abb0-4d9115a13dfe.gif)

RTL mode:
![Kapture 2022-01-10 at 11 26 09](https://user-images.githubusercontent.com/571316/148750894-0c197f50-e0a6-40e6-898e-0aa2e959a089.gif)

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
