### ISSUE TITLE
Remove the redundant `setData` method.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#9095]
### Description
After a discussion with @warpech and @kirszenbaum, we decided to remove the `setData` method (planned to be released in `11.1.0`), as it doesn't introduce much value when compared to `loadData`.

### Related issues
- https://github.com/handsontable/handsontable/issues/7263
- https://github.com/handsontable/handsontable/pull/8972
- https://github.com/handsontable/handsontable/pull/9037

**Comment by AMBudnik** [comment]
Closed as https://github.com/handsontable/handsontable/pull/9096#issuecomment-1009737453 for Handsontable v11.1.0
