### ISSUE TITLE
[8.4.0+] `nestedHeaders` headers do not expand with title

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9099]
### Description

The `nestedHeaders` headers do not expand with the title. The issue is reproducible once you open the link.

`8.3.0` and before
![Zrzut ekranu 2022-01-10 o 15 36 23](https://user-images.githubusercontent.com/10757813/148783676-135c2215-ee2a-4953-8e56-7bdde40c088e.png)

`8.4.0` and after
![Zrzut ekranu 2022-01-10 o 15 37 08](https://user-images.githubusercontent.com/10757813/148783661-b2390534-ceeb-4281-acb2-b24ddf538490.png)

### Demo

https://jsfiddle.net/2wLv7p8x/ - 11.1 (pre build that solves other `nestedHeaders` regressions) - broken
https://jsfiddle.net/t9wsn3ok/ - 8.4.0 - first broken
https://jsfiddle.net/uc7d4e1L/3/ 8.3.0 - last working well

### Your environment
* Handsontable version: 8.4.0+
* Browser Name and version: Chrome 96
* Operating System: macOS Monterey

Update [Zen](https://handsontable.zendesk.com/agent/tickets/27511)

**Comment by aninde** [comment]
This issue is fixed by v12.0.1 https://jsfiddle.net/8sjvmn9w
<img width="310" alt="Screenshot 2022-05-13 at 10 41 02" src="https://user-images.githubusercontent.com/30186818/168245803-8811807b-5dfe-4b6b-ae0c-60b4ddc5bde1.png">

**Comment by AMBudnik** [comment]
Thank you for fixing it!

The fix is available from Handsontable v12.0.1. I'm closing this issue as solved.
