### ISSUE TITLE
merge cells problem

### ISSUE THREAD

**Issue by SnowsofKilimanjaro** [handsontable/handsontable#9100]
### Steps to reproduce

1. when i use context menu to merge cells
![image](https://user-images.githubusercontent.com/13759488/148918185-875ed59f-ef9d-4917-b4c2-334528a057d6.png)
2.result like this: some borders gone 
![image](https://user-images.githubusercontent.com/13759488/148918293-d30434f2-ffae-43f7-b59c-20aa5bc106ca.png)

### Demo
[
https://jsfiddle.net/handsoncode/8ffpsqt6/](https://jsfiddle.net/94ofrLwd/)

### Your environment
* Handsontable version:11
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @SnowsofKilimanjaro 

the same issue I reported here https://github.com/handsontable/handsontable/issues/8400 in the thread.
Please free free to add a comment to my thread if I missed anything.
I will also notify you once that issue is solved.
