### ISSUE TITLE
Getting error when trying to remove multiple columns consecutively using remove_col

### ISSUE THREAD

**Issue by hazem-taha** [handsontable/handsontable#9101]
hello,

I have a horizontally expanding grid, and I'm trying to remove columns with empty 1st and 2nd cells once the user clicks the submit buttons

```
removeEmptyColumns() {
      let dataArr = this.hotRef.getSourceData();
      let emptyInd = [];
      for (let colInd = 2; colInd <= this.hotRef.countCols() - 1; colInd++) {
        if(!dataArr[0][colInd] && !dataArr[1][colInd]) {
          emptyInd.push(colInd);
        }
      }

      let self = this
      this.hotRef.batchExecution(() => {
        for (let index = emptyInd.length - 1; index >= 0; index--) {
          self.hotRef.alter('remove_col', emptyInd[index]);
        }
      })
    }
```

but I'm getting the below error

![image](https://user-images.githubusercontent.com/46519001/148926835-a9de0b23-2f5e-4caf-944c-946dc76345e1.png)

Please note that I'm trying to remove empty columns which are not always adjacent.

Thanks in advance

**Comment by AMBudnik** [comment]
Hi @hazem-taha 

Please fill my demo with the logic that will help us to replicate the issue https://jsfiddle.net/j6dcegw1/5/ 
It might be connected to the placement of your formulas and cell dependencies.
If that would require sharing data that you found sensitive please contact us at support@handsontable.com to discuss the details. Nevertheless, I do not think that it requires to have specifically your dataset (more than a pattern of it).

**Comment by hazem-taha** [comment]
Hello @AMBudnik 

I added the logic to the demo and not getting the expected result..but also not getting a console error

https://jsfiddle.net/xs1brLyu/26/

**Comment by AMBudnik** [comment]
Hi @hazem-taha 

Here https://jsfiddle.net/xfgm3dt5/9/ is an example that shows how the `alter` is altering your table with given indexes. After the first operation, the rest of referenced indexes are not available.

**Comment by AMBudnik** [comment]
Hey @hazem-taha 

I'm closing this ticket as there is no reply for a week. But if you still have any questions please feel free to send us an email to support@handsontable.com
