### ISSUE TITLE
[RTL] Text editor positioning, sizing

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9106]
### Description

There is an issue with text editor positioning and sizing. Based on the #9105, #9104, and #9098 fixes I can reproduce the issue. Sometimes the misalignment is on the table edge, sometimes after scroll. Generally, the editor has to be checked after merging the mentioned PR to the `rtl` branch.

![Kapture 2022-01-13 at 10 19 49](https://user-images.githubusercontent.com/571316/149301591-a0348506-f472-4e2f-bcb0-71cbb46c36e5.gif)

**Comment by aninde** [comment]
Tested during code freeze of v12.0.0. No issues found.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
