### ISSUE TITLE
Handsontable 11.1.0: Vue 3 support and updateData()

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9112]
Hi All!

We just released Handsontable 11.1.0. This version adds Vue 3 support, fixes numerous bugs, and introduces a new method: [`updateData()`](https://handsontable.com/docs/api/core/#updatedata).

### Vue 3 support

Until today, Handsontable offered wrappers for three of the most popular JavaScript frameworks: [React](https://handsontable.com/docs/react-simple-example/), [Angular](https://handsontable.com/docs/angular-simple-example/), and [Vue 2](https://handsontable.com/docs/vue-simple-example/).
Handsontable 11.1.0 adds one more wrapper, dedicated specifically to [Vue 3](https://handsontable.com/docs/vue3-simple-example/).

With [Vue 3 as the new default](https://twitter.com/youyuxi/status/1474752902694465538?s=20) just around the corner, we couldn’t think of a better time to start supporting it. But why create a separate wrapper?

Well, if you work with Vue or follow its development, you’re probably aware that the coming of Vue 3 was little short of a revolution. As for many other libraries, catching up required quite a few changes on our side. At the same time, we’re aware that many Vue developers are sticking with Vue 2, at least for the time being – that’s why we decided to split the Vue wrapper in two, and keep both Vue 2 and Vue 3 users happy.

Also, remember that since [version 11.0.0](https://handsontable.com/blog/articles/2021/11/handsontable-11.0.0-modularization-for-react-angular-and-vue), the framework wrappers can benefit from Handsontable’s [modularization features](https://handsontable.com/docs/modules/). It’s no different with the new wrapper: you can [use modules](https://handsontable.com/docs/vue3-modules/) to optimize the size of your Vue 3 app and make your Handsontable experience even more efficient.

### A new way to change Handsontable’s data: `updateData()`

There are a few different ways to change Handsontable’s data. For example:
* Using the [`updateSettings()`](https://handsontable.com/docs/api/core/#updatesettings) method to change the [`data`](https://handsontable.com/docs/api/options/#data) configuration option
* Using the [`setDataAtCell()`](https://handsontable.com/docs/api/core/#setdataatcell) method to change multiple cells at once
* Calling the [`alter()`](https://handsontable.com/docs/api/core/#alter) method
* Calling the [`loadData()`](https://handsontable.com/docs/api/core/#loaddata) method, to replace the data and reset the states of cells, rows and columns

In Handsontable 11.1.0, we’re adding a new one: [`updateData()`](https://handsontable.com/docs/api/core/#updatedata).

The [`updateData()`](https://handsontable.com/docs/api/core/#updatedata) method lets you replace your grid’s data, but keep the states of your cells, rows and columns intact. This means that the [configuration options](https://handsontable.com/docs/setting-options/) of your [cells](https://handsontable.com/docs/setting-options/#setting-cell-options), [rows](https://handsontable.com/docs/setting-options/#setting-row-options) and [columns](https://handsontable.com/docs/setting-options/#setting-column-options) stay the same, including your cells’ [formatting](https://handsontable.com/docs/formatting-cells/) and [`readOnly`](https://handsontable.com/docs/api/options/#readonly) states, and the order of your [rows](https://handsontable.com/docs/row-moving/) and [columns](https://handsontable.com/docs/column-moving/).

To help you make the most of the new method, we also added two new hooks:
* [`beforeUpdateData`](https://handsontable.com/docs/api/hooks/#beforeupdatedata)
* [`afterUpdateData`](https://handsontable.com/docs/api/hooks/#afterupdatedata)

### Bugs fixed

Handsontable 11.1.0 brings numerous bug fixes as well. Removing events will no longer hamper Handsontable’s performance (#9044). The [`Comments` ](https://handsontable.com/docs/api/comments/)plugin’s editor won’t disappear after adding a comment anymore (#9075). The [`CollapsibleColumns`](https://handsontable.com/docs/api/collapsible-columns/) plugin will properly expand all collapsed columns. For more, check the release notes below.

### Release notes: what we added

* Added [`updateData()`](https://handsontable.com/docs/api/core/#updatedata), a new method that allows for replacing Handsontable’s [data](https://handsontable.com/docs/api/options/#data) without resetting cells’ configuration options, rows’ states, and columns’ states. #7263
* _Vue_: Added [Vue 3](https://v3.vuejs.org/guide/migration/introduction.html#overview) support, by introducing a [new wrapper](https://handsontable.com/docs/vue3-simple-example/). #7545

### Release notes: what we changed

* Updated the TypeScript definition of the [`setDataAtCell()`](https://handsontable.com/docs/api/core/#setdataatcell) method. #8601
* Extended the `Code Examples Deployment` GitHub Actions workflow, to allow for deploying code examples to [GitHub Pages](https://pages.github.com/). #9058

### Release notes: what we fixed

- Fixed an issue where the [`autocomplete`](https://handsontable.com/docs/autocomplete-cell-type/) editor’s suggestion list didn’t update properly. #7570
- Fixed an issue where nested headers didn’t render when [`data`](https://handsontable.com/docs/api/options/#data) wasn’t defined. #8589
- Fixed some end-to-end tests that failed on mobile devices. #8749
- Fixed an issue where the rendered selection could get shifted by 1px. #8756
- Fixed an issue where the first column’s border didn’t display properly. #8767
- Fixed an issue where the [`CollapsibleColumns`](https://handsontable.com/docs/api/collapsible-columns/) plugin’s [`expandAll()`](https://handsontable.com/docs/api/collapsible-columns/#expandall) method didn’t expand collapsed columns. #8900
- Fixed end-to-end test scripts that occasionally crashed. #8961
- Fixed a typo in the `valueAccordingPercent()` helper. #9006
- Fixed an issue where the [`NestedRows`](https://handsontable.com/docs/api/nested-rows/) plugin could throw a type error after calling the [`updateSettings()`](https://handsontable.com/docs/api/core/#updatesettings) method. #9018
- Fixed an issue where performance was affected by removing events. #9044
- Fixed a wrong TypeScript definition of the [`MultiColumnSorting`](https://handsontable.com/docs/api/multi-column-sorting/) plugin’s [`sort()`](https://handsontable.com/docs/api/multi-column-sorting/#sort) method. #9067
- Fixed an issue where the [`Comments`](https://handsontable.com/docs/api/comments/) plugin’s editor disappeared after adding a comment. #9075
- _React_: Fixed a wrong return type. #9000

You can find detailed release notes for this and previous Handsonable versions [here](https://handsontable.com/docs/release-notes/).

**Comment by gauravjagtap-2611** [comment]
How can I use this for R shiny App?

**Comment by gauravjagtap-2611** [comment]
I did not find any document on expanding and collapsing rows functionality in Rhandontable in R-Shiny

**Comment by AMBudnik** [comment]
Hi @gauravjagtap-2611 rHandsontable is a different product and author. Here are their docs https://jrowen.github.io/rhandsontable/ and repository https://github.com/jrowen/rhandsontable
