### ISSUE TITLE
How to dynamically merge cells, and there is a merge effect after filtering

### ISSUE THREAD

**Issue by 3csj9** [handsontable/handsontable#9115]
### Steps to reproduce

1.
![企业微信截图_16421544676070](https://user-images.githubusercontent.com/87298451/149496984-a34ddb85-7a00-4d25-9fb0-b721f511ad94.png)

2.
![企业微信截图_16421544761621](https://user-images.githubusercontent.com/87298451/149497020-33d26034-baf2-4067-b51e-165f94e5ca08.png)

3.
![企业微信截图_16421544845216](https://user-images.githubusercontent.com/87298451/149497035-007f36e6-3a9e-4969-bdc8-374b3238b141.png)

### Demo

https://jsfiddle.net/handsoncode/dezfbgjt/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by 3csj9** [comment]
After merging, the filter items in column A should only have 1 and 2, but there is an extra blank。After filtering 1, there should be two rows, but only the first row。

**Comment by DaoSen-v** [comment]
I have the same problem, how can I solve it

**Comment by AMBudnik** [comment]
Hi @DaoSen-v 

it's hard for me to tell - do you select only `1` to show within the filer?

**Comment by 3csj9** [comment]
@AMBudnik ,
After merging, the second row should be filled with 1, not cleared, so after filtering 1, there should be two rows of results

**Comment by 3csj9** [comment]
@AMBudnik 
The second picture is only to show that there are several filter items in the first column after the merger. I only checked the number 1 to filter in the actual operation.

**Comment by 3csj9** [comment]
![demo](https://user-images.githubusercontent.com/87298451/149856037-4b2e0aa7-5632-401b-89ca-74c8c2502d80.gif)

**Comment by AMBudnik** [comment]
Thank you for the additional details, @3csj9 
I'm waiting for feedback from my colleague. I will update this ticket as soon as I get it.

**Comment by AMBudnik** [comment]
Hi @3csj9 @DaoSen-v 

I can confirm that the following scenario is not a result of a bug. Merging only takes place on the visual level of the table and does not change data underneath. While filtering works on the dataset - not on the visual representation of the cell.

We have already made a note to add that information to the documentation https://github.com/handsontable/handsontable/issues/9122

What you can do to make it work as you planned is
1) use `setDataAtCell()` method within the `afterMergeCells` hook to alter the data underneath 
2) add change detection on those merged cells in the `afterChange` hook

If you would need any further details or help with the implementation please contact me at support@handsontable.com

**Comment by 3csj9** [comment]
Thank you very much for your prompt reply. @AMBudnik 
But I have a little difficulty now, because I don't have a hansontable mailbox, I can't open the document you shared. 
Can you invite me and register an email for me? Many thanks!

**Comment by AMBudnik** [comment]
@3csj9 You do not need a @handsontable.com email (those are for our team :) ) - anything you will send from regular emails registered on your company domain or simple @gmail will work. And the link above redirects to another issue on the Github in the same Handsontable repository that we are now.
