### ISSUE TITLE
Upload a Docker image of the Docs to the package registry on every commit

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9123]
### Description

Currently, Docker image of the docs is uploaded to our registry[1] when a commit is pushed to the `develop` branch.

It would be useful to generate and upload the images on any commit, because then they can easily be tested locally, e.g.:

```sh
docker create -p 8000:80 --name docs ghcr.io/handsontable/handsontable/handsontable-documentation:latest
docker start docs
docker exec docs sh -c 'mv html docs && mkdir html && mv docs html'   # needed to fix paths for Nginx
start http://localhost:8000/docs/index.html                           # opens default browser
```

The benefit is that it allows to run the docs locally very quickly when reviewing documentation PRs.

### Links

1. https://github.com/handsontable/handsontable/pkgs/container/handsontable%2Fhandsontable-documentation

**Comment by Siemienik** [comment]
Additional TODO: 
* [ ] update https://github.com/handsontable/handsontable/blob/master/docs/README-DEPLOYMENT.md 
* [ ] clean-up untagged.

**Comment by warpech** [comment]
Closing as done in https://github.com/handsontable/handsontable/pull/9157
