### ISSUE TITLE
[RTL] The selection handlers for mobile devices are not working

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9124]
### Description

The selection handlers for mobile devices are not working in RTL document mode.

in RTL mode (missing selection handlers):
![image](https://user-images.githubusercontent.com/571316/149947847-2e6fddcf-ca25-4985-8b56-abc2fd66efa2.png)

in LTR mode:
![image](https://user-images.githubusercontent.com/571316/149947975-e82eee1c-e632-4fc7-aea9-61817c8746ea.png)

Related issue: #8760

**Comment by aninde** [comment]
Selection works on mobile with `rtl`, `ltr` and `rtl` direction inherit from parent div with v12.0.0 on LTS iOS 15.3.1 and Android 10, 11 and 12. Tested on Chrome, Safari, Samsung Internet.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
