### ISSUE TITLE
[RTL] Custom Borders API

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9129]
### Description

The plugin configuration API needs to be enhanced to work with RTL. Currently, the configuration allows changing the right and left borders by defining the object keys with the same names. It works predictably on LTR but it does not in RTL. On RTL the "right" border is rendered on the left and vice versa, like in the screenshot:

![2022-01-19 o 14 29 54](https://user-images.githubusercontent.com/571316/150140618-b61b4e9d-5f6d-41eb-b8cc-3339ad6cf4b6.png)

All two demos use the same configuration:
```js
customBorders: [
  {
    row: 2,
    col: 2,
    left: { width: 4,  color: 'red' },
    right: { width: 8,  color: 'green' }
  }
],
```

It's confusing that's why the new naming has to be implemented. To be backward-compatible the old naming will work only if Handsontable is running in LTR mode. In RTL mode the error will be printed when the "left" and/or "right" property name is used. The direction-less options are "**start**" and "**end**", for example:

```js
customBorders: [
  {
    row: 2,
    col: 2,
    start: { width: 4,  color: 'red' },
    end: { width: 8,  color: 'green' }
  }
],
```
In that case, in both layout types, the "start" key defines the border placement nearest the left overlay (or right in RTL) and "end" the farthest position.

![image](https://user-images.githubusercontent.com/571316/150540174-9f20df86-27b7-4809-ad36-efa61284dd06.png)

Related to https://github.com/handsontable/handsontable/issues/8785.

**Comment by aninde** [comment]
Work as expected with v12.0.0, both with inherit `rtl` direction from parent div and set by `layoutDirection`.
Updated demo https://jsfiddle.net/w5x6jatf/.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
