### ISSUE TITLE
Can't insert new-line within middle of text using Ctrl-Enter

### ISSUE THREAD

**Issue by diana-seattle** [handsontable/handsontable#913]
If I position the caret within the middle of the text in a cell and press Ctrl-Enter, a newline is inserted at the end of the text rather than at the caret.

**Comment by AMBudnik** [comment]
Please update to 0.14.1 - it should work fine like in our [main demo](http://handsontable.com/). If you would have issues with your code - feel free to provide a sample demo, and we'll see what we can do.
