### ISSUE TITLE
[RTL] Turning on/off the RTL feature

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9132]
### Description

The issue describes the Handsontable option that will be used to enable or disable the support for RTL. After discussion, the team agreed to use the `layoutDirection` option name. The option allows set three values:
 * `'rtl'` The option sets the `dir="rtl"` attribute to the root Handsontable element forcing the browser to render the table in right-to-left direction mode;
 * `'ltr'` The option sets the `dir="ltr"` attribute to the root Handsontable element forcing the browser to render the table in left-to-right direction mode;
 * `'inherit'` (default value) Handsontable tries to detect the document direction mode by traversing from the root Handsontable element ending in the `<HTML>` element. Then sets the `dir` attribute to the root Handsontable element with the same value as detected earlier. Thanks to that Handsontable won't be rendered incorrectly after further changes in the "dir" attribute of the parent element.

The `layoutDirection` option can be set only while Handsontable initialization. Only then the rendering engine is able to prepare the overlays to render in LTR or RTL modes. That's why the value can not be changed using the `updateSettings()` method. If the option key will be passed to the method the warning should be printed in the console.

**Comment by aninde** [comment]
Done in v12.0.0

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
