### ISSUE TITLE
 Cannot read properties of undefined (reading 'isDestroyed')  at HotTableRegisterer.getInstance (handsontable-angular.js:25:1)

### ISSUE THREAD

**Issue by jaballe** [handsontable/handsontable#9138]
### Description
Cannot get instance of the hot table 

### Steps to reproduce

1. Added hot table in my component html
<hot-table [hotId]="id"
        licenseKey="non-commercial-and-evaluation">
       </hot-table>
2. Attempted to create an instance of hotTable:
this.hotInstance = this.hotRegisterer.getInstance(this.id);
3. Encountered an errror:
![image](https://user-images.githubusercontent.com/11425937/150562147-87f16860-505f-496a-bfbb-ed185000a151.png)

### Demo

https://stackblitz.com/edit/handsontable-angular

### Your environment
* Angular version: 11.0.0
* Handsontable version: "handsontable": "^10.0.0",
* Wrapper version:   "@handsontable/angular": "^10.0.0",
* Browser name and version: Chrome
* Operating system: Windows 10

**Comment by AMBudnik** [comment]
Hi @jaballe 

is that the correct demo? When I open it up on Chrome I get the following error from _zone.js_. However the table is loaded and it works well.
![Zrzut ekranu 2022-01-24 o 12 49 19](https://user-images.githubusercontent.com/10757813/150777859-449ff2da-55b3-40d1-8f53-2774ac16ace1.png)

**Comment by AMBudnik** [comment]
Hi @jaballe do we have any updates on this subject?

**Comment by EssyTech** [comment]
I have the same issue and this is a major blocker. We paid for a license and I can't grab the instance.

**Comment by AMBudnik** [comment]
If the issue still persists please send me the implementation details at support@handsontable.com

**Comment by jaballe** [comment]
Hi Aleksandra,

Sorry somehow that stackblitz was added by mistake in the issue I've raised. I have created a new one based off of that: https://stackblitz.com/edit/handsontable-angular-dmuh5j?file=app%2Fapp.component.ts. This seems to be working correctly though. Although it shows how I call the hot table since the table settings and data are dynamic.

It looks like it's working correctly when I tried here but in my case where we are dealing a much huge data, this is a perennial problem. Also the problem is it is not consistent, sometimes it happens, sometimes it works correctly.

**Comment by AMBudnik** [comment]
> Also the problem is it is not consistent, sometimes it happens, sometimes it works correctly.

Those are the most challenging issues to solve. As soon as you spot the pattern, then it is easier. But without it and the steps to replicate the issue it will be hard to specify what can be done to fix it.

**Comment by ortbauer** [comment]
Hi Jessa,

I encountered the same problem in our application and it was in deed a bit tricky to find. Following setup:
- Table data/settings updated onChanges()
- calls ....updateSettings(settings)
This does not ensure the table is already initialized, as onChanges is called before onInit. Anyhow - hot requires the component to be initialized in order to update it's settings. (added a simple state flag to ensure update settings is only called upon initialization ... ugly but it works)
