### ISSUE TITLE
ColSpan in ColHeaders

### ISSUE THREAD

**Issue by PassHours** [handsontable/handsontable#916]
Is it possible to do "colspan" in handsontable's colHeaders

![colspan](https://f.cloud.github.com/assets/4745102/855233/b6c0afc4-f51c-11e2-8a4d-66831c310817.png)

Please advice.

Any fiddle example will be great.

**Comment by AMBudnik** [comment]
This option is[ currently available in Handsontable PRO](https://docs.handsontable.com/pro/demo-nested-headers.html)
