### ISSUE TITLE
Wrong TypeScript definition in the BasePlugin class

### ISSUE THREAD

**Issue by ssprusakov** [handsontable/handsontable#9175]
### Description
The following properties and functions are missing from the typescript definition of the BasePlugin class:
 - `readonly hot: Handsontable.Core`
 - `addHook<K extends keyof Events>(key: K, callback: Events[K] | Array<Events[K]>): void;`

### Steps to reproduce
1. Use typescript
2. Try to create a new plugin according to the [documentation](https://handsontable.com/docs/11.0/plugins/)
3. `this.hot` generates `Property 'hot' does not exist on type 'MyNewPlugin'.` error
4. `this.addHook('beforeKeyDown', (event) => { console.log(event.key); });` generates `Argument of type '(event: any) => void is not assignable to parameter of type '() => void'.` error

### Demo
Not required

### Your environment
* Handsontable version: 11.0.1
* Browser name and version: Chrome 96.0.4664.110
* Operating system: Windows 10

**Comment by mjastrzebowski** [comment]
Hey @ssprusakov, thanks for the report, I've checked and these types are actually missing and need to be fixed on our side, we will update you once it will be done

**Comment by mjastrzebowski** [comment]
Hi @ssprusakov, the fix is merged to `develop` branch, it will be released in the new version

**Comment by ssprusakov** [comment]
@mjastrzebowski Thank you!

**Comment by aninde** [comment]
Fixed with v12.0.0.0

**Comment by AMBudnik** [comment]
Hi @ssprusakov 

we just released Handsontable version 12 where we fixed the definition. Thank you again for your feedback. I'm closing this issue as solved.

Here https://handsontable.com/docs/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls you can read more about the changes in v12.
