### ISSUE TITLE
[RTL] ManualRowResize

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9177]
### Description

The _ManualRowResize_ plugin does not work in RTL. The handlers do not appear on mouse over events.

LTR:
![Kapture 2022-02-01 at 14 37 50](https://user-images.githubusercontent.com/571316/151978376-01fee5be-6b1a-4a1d-8fea-34472866e322.gif)

RTL (nothing happens):
![Kapture 2022-02-01 at 14 38 31](https://user-images.githubusercontent.com/571316/151978530-4f3a0a41-adcc-4035-a0a0-879101912f7d.gif)

### Your environment
* Handsontable version: any
* Browser name and version: any
* Operating system: any

**Comment by aninde** [comment]
Work well with v12.0.0 https://jsfiddle.net/qxjtovmb/1/

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
