### ISSUE TITLE
[RTL] Insert column on the left/right actions 

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9178]
### Description

The "Insert column left" and "Insert column right" commands execute the actions in the opposite way than expected. Inserting the column on the left should always add a column on the left. In RTL mode it's reversed.

![Kapture 2022-02-01 at 14 47 40](https://user-images.githubusercontent.com/571316/151980561-2d461768-9b47-4c39-bbdf-effbf9783d52.gif)

### Your environment
* Handsontable version: any
* Browser name and version: any
* Operating system: any

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
