### ISSUE TITLE
Horizontal Scroll jumping on initial scroll from left side

### ISSUE THREAD

**Issue by ruwayfaahmed** [handsontable/handsontable#9185]
## Description

I have an issue identical to the one in issue [#6422](https://github.com/handsontable/handsontable/issues/6422) which is recalculating styles after rendering on scroll. This still exists but can't be really seen if you have a table of a low number of columns and viewportColumnRenderingOffset not used or set to 0.

 I believe this is an issue to do with the overlays referring to this comment in `/handsontable/3rdparty/walkontable/src/table.mjs`, in the `render` method line `404`

```
if (positionChanged) {
          // It refreshes the cells borders caused by a 1px shift (introduced by overlays which add or
          // remove `innerBorderTop` and `innerBorderLeft` CSS classes to the DOM element. This happens
          // when there is a switch between rendering from 0 to N rows/columns and vice versa).
          wtOverlays.refreshAll();
          wtOverlays.adjustElementsSize();
        }
```

The issue occurs higher up in this function after rendering the table where it calculates the column widths again after styles are applied causing layout thrashing and recalculation of styles again.

## Example
You can see in this gif below that there is a slight but noticeable lag and skip when starting to scroll.

![scroll](https://user-images.githubusercontent.com/60347080/152229185-ab9ab2fb-42a6-42b8-8712-ebed709629f8.gif)

## Performance
You can see the forced reflow here when checking the performance of scroll event. It is taking around 30-35ms on each recalculation which is pretty observables especially when the cells render within 0.5ms 
![image](https://user-images.githubusercontent.com/60347080/152226362-daa4ac7e-dc3f-4b0d-ab97-e3cd76c1f04a.png)

**Comment by AMBudnik** [comment]
Hi @ruwayfaahmed 

Thank you for sharing the issue report. Could you also share the configuration object for your instance of Handsontable (if you cannot send it here please update me on support@handsontable.com)? 

We need to
* replicate the issue
* be able to debug the code
* specify the lag does not relate to any custom logic added to the demo

**Comment by AMBudnik** [comment]
I'm closing this issue as there's been no reply for more than 2 weeks.

If you still have any issues please send us the demo at support@handsontable.com
