### ISSUE TITLE
[RTL] DropdownMenu arrow button

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9186]
### Description

The arrow button for the _DropdownMenu_ plugin is not positioned in the correct position when Handsontable runs in RTL mode. On LTR it's placed on the right in RTL it **should** be placed on the left.

RTL:
![2022-02-3 o 11 49 29](https://user-images.githubusercontent.com/571316/152328564-2ee05cff-0f5a-47c3-a31e-7670e5986b73.png)

Part of #8760.

Continuation of #8826 and the issue description based on [the comment](https://github.com/handsontable/handsontable/issues/8826#issuecomment-1028057055).

**Comment by aninde** [comment]
Tested with https://github.com/handsontable/handsontable/issues/8826#issuecomment-1067220332. Fixed.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
