### ISSUE TITLE
[RTL] Inconsistency in displaying negative numbers in default cells and headers 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9187]
### Description
Minus sign is after digit and should be before, like in LTR in the default text cells and headers.
According to [Wikipedia](https://en.wikipedia.org/wiki/Modern_Arabic_mathematical_notation#:~:text=Negative%20signs%20are%20written%20to,%D9%A2%2F%D9%A7%202%2F7), the arithmetic signs should be written in the LTR even with RTL text direction. 

Other arithmetic signs  (eg `%` ) are displaying correctly even in default text cells and other cell types.

The same negative number is displayed correctly when the cell has a numeric type.

### Demo
 Part of the sample configuration
```
        layoutDirection: 'rtl',
        data: [
            { car: 'Mercedes A 160', year: -2017, price_usd: -7000, price_eur: -7000 },
            { car: 'Citroen C4 Coupe', year: 2018, price_usd: 8330, price_eur: 8330 },
            { car: 'Audi A4 Avant', year: 2019, price_usd: 33900, price_eur: 33900 },
            { car: 'Opel Astra', year: 2020, price_usd: 5000, price_eur: 5000 },
            { car: 'BMW 320i Coupe', year: 20, price_usd: 30500, price_eur: 30500 }
        ],
        colHeaders: ['-3', 'Text cell', 'Numeric, currency format cell', 'Plain numeric cell', '10%'],
        rowHeaders: ['-1', '10%', ''],
        columnSorting: true,
        height: 'auto',
        licenseKey: 'non-commercial-and-evaluation',
        columns: [{
                data: 'car'
            },
            {
                data: 'year',
                type: 'text'
            },
            {
                data: 'price_usd',
                type: 'numeric',
                numericFormat: {
                    pattern: '$0,0.00',
                    culture: 'en-US' 
                },
                allowEmpty: false
            },
            {
                data: 'price_eur',
                type: 'numeric',
            }
        ]
```

![Screenshot 2022-02-02 at 17 31 35](https://user-images.githubusercontent.com/30186818/152335993-ae69c025-1e80-4489-81b5-bae7caede435.png)

### Your environment
* Handsontable version:  RTL-RC commit 11c0b41ef5f3d1d93d01fc5e6a2132348a40a9d1
* Browser name and version: not related
* Operating system: not related

**Comment by krzysztofspilka** [comment]
If the minus is treated as a string, then it's not minus, it's a plain dash character. Therefore, it should be reversible in the same exact way the text is. Am I right here @aninde?

**Comment by aninde** [comment]
@krzysztofspilka Yes, you are right. I am closing because it is not a bug.
