### ISSUE TITLE
[RTL] Missing TS types for `layoutDirection` option

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9192]
### Description

There is missing TypeScript types for new `layoutDirection` option.

### Your environment
* Handsontable version: - 
* Browser name and version: - 
* Operating system: -

**Comment by aninde** [comment]
Fixed in v12.0.0.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
