### ISSUE TITLE
[RTL] Hide the implementation details from the Cell editor page

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9194]
### Description

The [cell-editor](https://handsontable.com/docs/cell-editor/) page contains some examples that reveal the internal implementation details of the cell editors. That needs to be changed to give developers only examples that promote using only stable public APIs.

After the [PR ](https://github.com/handsontable/handsontable/pull/9176) is merged and released the examples (in the current shape) will stop work.

### Links

https://handsontable.com/docs/cell-editor/#selecteditor-creating-editor-from-scratch

**Comment by aninde** [comment]
👍

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
