### ISSUE TITLE
[RTL] The date picker wrong layout direction

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9195]
### Description

The date picker from the date cell type is not rendered correctly on RTL.

Currently it looks like:
![image](https://user-images.githubusercontent.com/571316/152511938-cff9258d-5a75-4137-b4e1-9cccdd564b3f.png)

Should be:
![image](https://user-images.githubusercontent.com/571316/152512022-f1d0b137-80b4-4fd4-8267-5c5fc3f43696.png)

### Your environment
* Handsontable version: -
* Browser name and version: -
* Operating system: -

**Comment by aninde** [comment]
Done with v12.0.0
