### ISSUE TITLE
Extend Renderer

### ISSUE THREAD

**Issue by bottas** [handsontable/handsontable#921]
I need to extend Text / Date / Numeric renderer to something like as below:
<pre>
Handsontable.TextRenderer = function (instance, TD, row, col, prop, value, cellProperties) {
        var escaped = Handsontable.helper.stringify(value);
        instance.view.wt.wtDom.fastInnerText(TD, escaped); //this is faster than innerHTML. See: https://github.com/warpech/jquery-handsontable/wiki/JavaScript-&-DOM-performance-tips
        if (cellProperties.readOnly) {
            instance.view.wt.wtDom.addClass(TD, 'htDimmed');
        }
        if (cellProperties.valid === false && cellProperties.invalidCellClassName) {
            TD.className = cellProperties.invalidCellClassName;
        }
// New CODE
        if (cellProperties.isMandatory != null) {
            if (cellProperties.isMandatory) {
                instance.view.wt.wtDom.addClass(TD, 'mandatoryColumn');
            } else {
                instance.view.wt.wtDom.addClass(TD, 'optionalColumn');
            }
        }
        else {
            instance.view.wt.wtDom.removeClass(TD, 'mandatoryColumn');
        }
    };
</pre>

For now, I have overwritten the renderer methods to validate for isMandatory property and use the CSS classes accordingly. Can this be incorporated in a generic way into HOT so that I can get newer version of HOT wihout trouble?

**Comment by AMBudnik** [comment]
If you still face this issue after updating to 0.14.1, please prepare a JSFiddle demo. As the activity of this issue ended in 2014 it will stay closed till an author's reply.
