### ISSUE TITLE
How to realize multiplayer real-time online editing

### ISSUE THREAD

**Issue by 3csj9** [handsontable/handsontable#9210]
### Description

What I want to achieve is that when A is editing, if B is also editing, the cell edited by B will show that B is editing.
### Steps to reproduce

1.I achieved the effect of selecting the cell and changing the content of the cell to B is editing through **setDataAtCell** and **setCellMeta** functions, and then set the cell style to achieve the effect of selected editing
![企业微信截图_16444602142724](https://user-images.githubusercontent.com/87298451/153325787-ce60c3e0-0b6d-4f01-ab95-f294362a9de9.png)

2.But what I have implemented is only that when the cell is successfully modified by B, it will prompt that a cell in A has been modified, and I cannot achieve real-time change reminder that B is also editing when A is editing; and I only implemented the modified cell. Grid styles don't give cells a hint that xx is being edited.
![image](https://user-images.githubusercontent.com/87298451/153364934-51a84007-bd56-472b-8a6e-ec44e3ac6c3a.png)

3.The effect I want to achieve is shown below
![企业微信截图_16444580758419](https://user-images.githubusercontent.com/87298451/153325882-316755b8-abe4-4b07-8c19-5331611b808e.png)

### Demo

https://jsfiddle.net/handsoncode/dezfbgjt/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by AMBudnik** [comment]
Hi @3csj9 

You can have only one cell in the edit mode at the moment. Also, if you would like to alter the visuals of the table (add a cell highlight), that would require the table to rerender. Rendering closes a cell editor. So if you plan to add the highlight, you'd need to reopen the cell editor.
