### ISSUE TITLE
[RTL] RTL languages vs `layoutDirection`(after feedback)

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9211]
### Description

The issue is about changing how the Handsontable works with RTL. After the feedback that we've got from @alshakero, it's turned out that the code needs to be changed. In some cases, the table should behave differently than we originally thought.

The UI of the table should be rendered from the right to left **only** if the `language` option is set to use Arabic (or other RTL language). Otherwise, the UI of the table is always rendered from left to right. Even, when the `layoutDirection` option is set to `'rtl'`. Setting the option to `'rtl'` instructs Handsontable to render the table (columns, cells) from right to left, the UI stays as if it were LTR.

Here is the list of table' features that use UI. Those plugins need to be adjusted to follow the above feedback. All gifs show what it currently looks like in RTL.
* _Selection_
![Kapture 2022-02-10 at 15 15 13](https://user-images.githubusercontent.com/571316/153425531-3b5b8640-e318-4a4d-98c6-9cfda5946e89.gif)
* _CollapsibleColumns_
![Kapture 2022-02-10 at 15 19 20](https://user-images.githubusercontent.com/571316/153426355-35f809af-e0fb-479b-82ea-6264e93a415b.gif)
* _ColumnSorting_
![Kapture 2022-02-10 at 15 20 13](https://user-images.githubusercontent.com/571316/153426510-d688a31c-3665-4d78-8557-c96ff1a803ec.gif)
* _Comments_
![Kapture 2022-02-10 at 15 22 35](https://user-images.githubusercontent.com/571316/153426982-c5bcba79-153b-4e37-9aeb-60d8d5d0a864.gif)
* _ContextMenu_
![Kapture 2022-02-10 at 15 23 21](https://user-images.githubusercontent.com/571316/153427129-5f0a52c8-56fb-4dc0-a21a-0c06555b867d.gif)
* _DropdownMenu_
![Kapture 2022-02-10 at 15 29 13](https://user-images.githubusercontent.com/571316/153428257-1c330bc6-65b4-4ec5-a4de-219d96c65579.gif)
* _Filters_ (rendered in dropdown menu)
![Kapture 2022-02-10 at 15 30 17](https://user-images.githubusercontent.com/571316/153428481-fa52d449-1e18-4c9a-a698-e5ea45949fa6.gif)
* _ManualColumnResize_
![Kapture 2022-02-10 at 15 12 49](https://user-images.githubusercontent.com/571316/153425120-315a4838-aa1c-4578-900b-9ed5d7f9313d.gif)
* _NestedHeaders_
![image](https://user-images.githubusercontent.com/571316/153429007-aad2c6a9-b194-4c88-97ba-0215b2d2ad0e.png)

Related issue https://github.com/handsontable/handsontable/issues/8760

**Comment by aninde** [comment]
List supplement:
- draggable move handle and shadow while moving columns
- UI indicators from the hiddenRows

We should think about every feature that could rewrite into RTL, which are also:
- Hiding columns
- Custom borders
- Freezing
- Merge cells
- Read-only

What about text alignment during RTL mode with LTR language?
