### ISSUE TITLE
beforeCreateCol error / hook behavior

### ISSUE THREAD

**Issue by luastoned** [handsontable/handsontable#9216]
### Description
When `tableMeta.columns` is provided `isColumnModificationAllowed` returns `false` and an error in [createCol](https://github.com/handsontable/handsontable/blob/2dbc605c14b4f13eb25b77679f1c1cab98a274ad/handsontable/src/dataMap/dataMap.js#L361) is thrown.

I would suggest that the `beforeCreateCol` hook (or a new one) is called before that initial check.
This would allow proper handling of situations like `tab` to create new column.

### Steps to reproduce
1. Create a table with columns defined
2. Press Tab on the rightmost column

### Demo

https://jsfiddle.net/3cj8ehb0/4/

### Your environment
* Handsontable version: 11.1
* Browser name and version: FF 98
* Operating system: Win10

**Comment by AMBudnik** [comment]
Hi @luastoned 

We intentionally block the ability to add new columns when the set of columns is defined by the `columns` option. If you would like to add a new column and use `columns` at the same time you would need to alter the logic to update `columns` via `updateSettings`. If that should work for the `TAB` key you can use the [`beforeKeyDown` hook](https://handsontable.com/docs/api/hooks/#beforekeydown).

**Comment by luastoned** [comment]
Well, other options like `minSpareCols: 1` don't work either.
A proper hook / callback solution would allow to update the `columns` in any case.

**Comment by luastoned** [comment]
I understand that `columns` need to be updated manually (via context menu for example) - I ended up doing just that.
It's nonetheless odd that the proper callback simply ends in an error.. 

Oh well, I'll have to place a couple hooks to get somewhat similar results to the intended way.
