### ISSUE TITLE
[RTL] Wrong Comments position when the table is scrolled

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9217]
### Description

The textarea element of the _Comments_ plugin is mispositioned when the table is scrolled horizontally. It happens only when the table is initialized with RTL mode.

![Kapture 2022-02-16 at 10 26 42](https://user-images.githubusercontent.com/571316/154234887-69985ee5-6ba0-41d8-a4bb-2acebd41284d.gif)

**Comment by aninde** [comment]
Fixed with v12.0.0 https://jsfiddle.net/x0gwu7fk/

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
