### ISSUE TITLE
About Column freezing

### ISSUE THREAD

**Issue by ywyixx** [handsontable/handsontable#9223]
### Description
When I used the freeze column function, I found that the side of the selection box near the freeze column was blocked by 1px.

### Steps to reproduce

1. Please go directly to the section of the documentation on Column freezing

### Demo

![image](https://user-images.githubusercontent.com/75475607/154669780-89815f30-aa4f-41f9-8ce1-3b557ddece47.png)
<img width="228" alt="image" src="https://user-images.githubusercontent.com/75475607/154669828-9cb95c51-bd17-4a74-9778-1943d40e4672.png">

### Your environment
* Handsontable version: 10.0.0 and 6.2.2
* Browser name and version: chrome 98.0.4758.102
* Operating system: mac and windows

**Comment by AMBudnik** [comment]
Hi @ywyixx 

we intentionally remove the 1px border from cells that in the edge of the fixed area of columns. I have tested v10 and v6.2 on Chrome and they both look the same. Could you please share the exact URL you are testing?

**Comment by ywyixx** [comment]
https://handsontable.com/docs/10.0/column-freezing/#freeze-columns-at-initialization
You just need to open the document to see the problem. please reply as soon as possible, thank you.

**Comment by AMBudnik** [comment]
@ywyixx This is not a problem. The cells are intentionally styled differently when they are near the fixed area of cells.
