### ISSUE TITLE
Filter the result after filter is different from excel

### ISSUE THREAD

**Issue by duanyijie** [handsontable/handsontable#9224]
### Description
when I use filter with search in 'filter by value' , the result in handsontable is different from excel

### Steps to reproduce
1. click first col's dropdown button, type 'C' in the search input , select 'Camido' only and click 'OK' button
2. do it again in excel
3. the result in handsontableis different from excel
![20a53d2d14b6fd3437418fcee6b48b9](https://user-images.githubusercontent.com/16126552/154918680-b162ed6b-7c13-47b2-9b78-ace1d9cf421e.png)
![image](https://user-images.githubusercontent.com/16126552/154919028-0b6b7c8e-c19e-4162-be45-449df6ad5130.png)

### Demo
no demo

### Your environment
* Handsontable version: latest
* Browser name and version: chrome 99
* Operating system: win10

**Comment by AMBudnik** [comment]
Hi @duanyijie 

That is correct. When you open a filter menu all of the values are selected

![Zrzut ekranu 2022-02-21 o 15 08 33](https://user-images.githubusercontent.com/10757813/154970860-7a27448d-e07c-4521-ad9f-aad1090de548.png)


so it is easier to exclude some of the values. But if your intention is to show only a couple of values you need to click the `clear` button and select checkboxes of values in your interest. 


![Zrzut ekranu 2022-02-21 o 15 08 43](https://user-images.githubusercontent.com/10757813/154971088-039728bf-dfb4-4ddd-9647-c13539cf44dc.png)

and then when you confirm the choice with the green `OK` button you get only what you wanted to see


![Zrzut ekranu 2022-02-21 o 15 08 49](https://user-images.githubusercontent.com/10757813/154971152-05e3a1fc-06f3-4212-a06c-c6ed873dd7fd.png)
