### ISSUE TITLE
how to listen freeze events

### ISSUE THREAD

**Issue by 19Qingfeng** [handsontable/handsontable#9228]
when i use ManualColumnFreeze Plugin to freeze column,How to listen for freeze/unFreeze events ? 

I didn't find the corresponding information in the documentation.

**Comment by adrianszymanski89** [comment]
Hi @19Qingfeng 

Unfortunately, there isn't a hook for manualColumnFreeze plugin. There is an issue reported regarding this topic, you can watch it to see when we will start working on it.

https://github.com/handsontable/handsontable/issues/6783

**Comment by warpech** [comment]
Closing in favor of a new issue #9248 that tracks the implementation of the hooks proposed in #6783.

**Comment by 19Qingfeng** [comment]
ok thanks, I define the frezz action in context menu by myself.
