### ISSUE TITLE
[RTL] Missing `fixedColumnsStart` option

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9235]
### Description

To support the new `fixedColumnsStart` option in the Angular wrapper there is a need to update the HotColumn component, see https://github.com/handsontable/handsontable/blob/master/wrappers/angular/projects/hot-table/src/lib/hot-table.component.ts#L35.

### Your environment
* Angular version: - 
* Handsontable version: -
* Wrapper version: -
* Browser name and version: -
* Operating system: -

**Comment by aninde** [comment]
Done in the v12.0.0

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
