### ISSUE TITLE
Unwanted rectangle elements in dropdown menu

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9240]
### Description

The `develop` build contains a bug that appeared in unwanted rectangle elements in the dropdown menu.

![2022-02-24 o 10 34 35](https://user-images.githubusercontent.com/571316/155498260-538b8e47-1d36-45ab-8f35-8edce2885126.png)

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: `develop` branch
* Browser name and version: -
* Operating system: -

**Comment by AMBudnik** [comment]
For everyone who will stumble this issue: please update to Handsontable v12 where this issue is solved.

Here https://handsontable.com/docs/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls you can read more about the changes in v12.
