### ISSUE TITLE
How can i reRender HotColumn ? 

### ISSUE THREAD

**Issue by 19Qingfeng** [handsontable/handsontable#9247]
Hi, I have some problems difficult to solve when i use HotColumn.

I want to add column by dynamic, But when I call HotTable reRender, HotColumn not reRender.

How can i reRender HotColumn ?

**Comment by AMBudnik** [comment]
Hi @19Qingfeng 

Generally, the `render()` method rerenders all of the cells and you cannot pick only a single column. If I may ask, what stands by the need to rerender that column?
