### ISSUE TITLE
Add `afterColumnFreeze` and `afterColumnUnfreeze` hooks

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9248]
### Discussed in https://github.com/handsontable/handsontable/discussions/7755

<div type='discussions-op-text'>

<sup>Originally posted by **AMBudnik** March 27, 2020</sup>
### Description

In the time of writing this request, freezing calls the moving plugin once we freeze a column
https://jsfiddle.net/wsby13rc/
https://github.com/handsontable/handsontable/blob/bb6871349289add4f4692ebe6627c408b6bce251/src/plugins/manualColumnFreeze/manualColumnFreeze.js#L117
But that is not a way to track freezing as now it does not tell the developer if the column moved or has been frozen.

`Structure`
As we are able to freeze and unfreeze only one column at the time the following hook can return only an **index** of a column or **property** for an object type data.

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 83
* Operating System: Os Catalina

Inform [Client](https://forum.handsontable.com/t/gh-6782-6783-is-there-any-way-to-save-and-restore-user-preferences-like-column-resize-sorting-ordering/4241/13) after publishing</div>

**Comment by aninde** [comment]
Done in v12.1.0

**Comment by AMBudnik** [comment]
Works great! Demo for everyone to test the new hooks https://jsfiddle.net/p5ruLfmg/ 
Closed as solved in Handsontable [v12.1.0.](https://handsontable.com/docs/release-notes/#_12-1-0)
