### ISSUE TITLE
Dropdown menu does not work on IE 10

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9255]
### Description

The Dropdown menu does not work on IE 10.

![Kapture 2022-02-25 at 12 31 03](https://user-images.githubusercontent.com/571316/155708136-9a0f1c02-e249-4c4b-bc09-436152026c3b.gif)

Error:
```log
Unable to get property 'length` of undefined or null reference
```

### Your environment
* Handsontable version: `develop` branch
* Browser name and version: IE10
* Operating system: Windows 7

**Comment by warpech** [comment]
We do not support IE 10 anymore, this is a won't fix
