### ISSUE TITLE
After setting the cell background transparency, the data overlaps when the cell is edited

### ISSUE THREAD

**Issue by 3csj9** [handsontable/handsontable#9256]
### Steps to reproduce

1.I set the background color of a cell as rgba(0,0,0,0)
2.When I want to edit this cell again, the following picture will appear
![企业微信截图_16458613848894](https://user-images.githubusercontent.com/87298451/155836570-b738a7b8-06d1-4c9f-a12c-6ff8c37c8e3c.png)

3.How to get this edit mode back to normal

### Demo

https://jsfiddle.net/handsoncode/dezfbgjt/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by adrianszymanski89** [comment]
Hi @3csj9 

Can you please reproduce the issue inside the demo that you uploaded? It's missing all the parts that you mentioned. As there are a few ways to change the cell background color it would speed up the investigation process.

Thanks

**Comment by 3csj9** [comment]
When I set the cell background color to rgba(0,0,0,0) in the re-render function, the editing of the cell has the above problem.
![企业微信截图_16461847928296](https://user-images.githubusercontent.com/87298451/156277789-fc0e620c-e1d6-4ef5-b5fc-42a04c1d57b5.png)
