### ISSUE TITLE
Changed data in Vue2 is not reflected in the table

### ISSUE THREAD

**Issue by shkim208** [handsontable/handsontable#9257]
### Description
Changed data in Vue2 is not reflected in the table.

### Steps to reproduce
1. Set up a table with data generated by Handsontable.
2. Click the "Change data" button to call the onLoadData() function.
3. Even though it is set to an empty array, the table cannot be updated.

![image](https://user-images.githubusercontent.com/46837941/155958523-b28ddd48-af93-4d4a-a08a-ffdda6c706b8.png)

### Demo
https://jsfiddle.net/shkim208/7apo8m6r/104/

### Your environment
* Vue wrapper version: 2.6.14
* Handsontable version: 11.1.0
* Browser name and version: any
* Operating system: any

**Comment by AMBudnik** [comment]
The subject continued on email.

**Comment by zhongguodong** [comment]
Hi @AMBudnik 
Is response data not currently supported?Need to call the loadData method manually?

**Comment by AMBudnik** [comment]
Hi @zhongguodong 

For getting the data we no longer call `settings.data` we have dedicated methods. Please check this demo https://stackblitz.com/edit/vitejs-vite-dyddgp?file=src%2FApp.vue,src%2Fmain.js&terminal=dev using latest Vue and latest Handsontable version. We have

* `getData()` - https://handsontable.com/docs/javascript-data-grid/api/core/#getdata
* `getSourceData()` - https://handsontable.com/docs/javascript-data-grid/api/core/#getsourcedata

**Comment by zhongguodong** [comment]
Get the data. I got it. Do you still need to call instance methods to load data? For example:this.$refs.hotTableComponent.hotInstance.loadData([['1','2']]) @AMBudnik

**Comment by AMBudnik** [comment]
Yes, @zhongguodong all of the [Core methods](https://handsontable.com/docs/javascript-data-grid/api/core) need to be called for the instance, so with the use of Vue you need to set up the instance reference (as in the demo).
