### ISSUE TITLE
[RTL] Dropdown cell type - unwanted right border

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9258]
### Description

The dropdown cell type after expanding available items shows the list with an unwanted right border. It only happens in RTL mode.

RTL (bug):
![Zrzut ekranu 2022-02-28 o 10 24 47](https://user-images.githubusercontent.com/571316/155957847-10f66e22-92ab-41b0-bb60-ea78564eb26b.png)

LTR
![image](https://user-images.githubusercontent.com/571316/155957876-f5e5793e-3dd2-4942-ae9b-4ee0bb2f9a49.png)

**Comment by aninde** [comment]
Resolved in the v12.0.0 https://github.com/handsontable/handsontable/issues/8802#issuecomment-1067226017

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 (RTL Support), published in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
