### ISSUE TITLE
Header row not resizing correctly

### ISSUE THREAD

**Issue by rianbotha** [handsontable/handsontable#9264]
### Description
When handsontable is set to `stretchH="all"` the header row does not resize correctly when you make the viewport smaller and then larger again. The header seems to retain the previous width.

After scaling down and then up again:
![Screenshot 2022-03-02 at 14 29 25](https://user-images.githubusercontent.com/11853275/156361908-c8fb7b11-42a3-41f9-b408-e8f5b83ae21f.png)

### Steps to reproduce

1. Scale your window smaller in the x-axis
2. Make the window larger again
3. Observe the gap at the end of the header row

### Demo

https://jsfiddle.net/czdqks4y/

### Your environment
* React wrapper version: 11.1.0
* Handsontable version: 11.1.0
* Browser name and version: Chrome 98.0.4758.109
* Operating system: MacOS 12.2.1

**Comment by adrianszymanski89** [comment]
Hi @rianbotha 

This issue is known to us, it's been already reported here: https://github.com/handsontable/handsontable/issues/6368

You can track the progress there. I'm closing this issue now.

**Comment by rianbotha** [comment]
Is there any plan to work on this issue? I see it has been around since version 7.

**Comment by adrianszymanski89** [comment]
@rianbotha there are no plans for working on this issue during the nearest quarter. I'll let you know when the issue will be fixed.
