### ISSUE TITLE
Duplicated `licenseKey` declaration within the `columns`> `datePickerConfig` config

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9266]
### Description

Duplicated `licenseKey` declaration that should be removed.

![Zrzut ekranu 2022-03-2 o 14 20 59](https://user-images.githubusercontent.com/10757813/156369584-feadf781-4fee-44ea-8a34-7f2a04be8596.png)

### Links

https://handsontable.com/docs/date-cell-type/#basic-example

**Comment by kirszenbaum** [comment]
Done in #9711
