### ISSUE TITLE
How do I get the total number of rows in the filtered results

### ISSUE THREAD

**Issue by Searworld** [handsontable/handsontable#9282]
### Description

Hello,  How do I get the total number of rows in the filtered results？
"handsontable.countRows"  is to get the total number of rows in the table,  but i want to get the filtered row count.
thanks~~

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by AMBudnik** [comment]
Hi @Searworld 

You can use the `rowIndexMapper` to get the renderer rows. Example https://jsfiddle.net/xd4sew2t/1/ and if you need to count how many rows are left you just check the length of the array https://jsfiddle.net/xd4sew2t/2/

**Comment by Searworld** [comment]
Hi @AMBudnik 
i can't open jsfiddle, what API can check array length? thanks~~

**Comment by AMBudnik** [comment]
Hey @Searworld 

If you cannot access the demo here is the code

```js
var container = document.getElementById('container');
var hot = new Handsontable(container, {
  data: Handsontable.helper.createSpreadsheetData(10, 5),
  width: 500,
  height: 300,
  rowHeaders: true,
  colHeaders: true,
  filters: true,
  dropdownMenu: true
});

let filtersPlugin = hot.getPlugin('filters');
filtersPlugin.addCondition(0, 'by_value', [['A1', 'A2', 'A3', 'A8']]);
filtersPlugin.filter();
console.log(hot.rowIndexMapper.renderablePhysicalIndexesCache.length)
```

where 
* `addCondition` add the filter condition
* `filter` repaints the table
* `rowIndexMapper` holds the array of `renderablePhysicalIndexesCache` after filtering so when we have the array we can call the `length` function to get a numeric representation of the array length. That equals the total number of visible rows.

**Comment by Searworld** [comment]
thanks~ @AMBudnik
