### ISSUE TITLE
Improve the `suspendRender` and `resumeRender` description

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9287]
### Description

We should improve the `suspendRender` and `resumeRender` descriptions by adding the statement that each `suspendRender` should equal the calls of `resumeRender`.

We got a message from one of the Customers that the description could be interpreted differently
> it does not state that number of calls to suspend/resume must match which is not obvious. For example I was expecting that if I call suspend X time then 1 resume will be enough, which is not true. 

### Links

https://handsontable.com/docs/api/core/#resumerender

**Comment by kirszenbaum** [comment]
Fixed here:

https://github.com/handsontable/handsontable/pull/9724/files#diff-768d570251433ef7c77eb6c10fae16b3ee71c88638ee1c2ec627d2e385dac632R140-R142

https://github.com/handsontable/handsontable/pull/9724/files#diff-bf6f9c23fc3252c45d93ec80d4afd013da7973589a0ee32f08d5544554626f49R1777-R1813
