### ISSUE TITLE
[12.0.0] Column headers do not match when RTL is enabled with stretchH

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9289]
### Description

The width of the column headers does not match the table with the stretch optionwhile RTL is enabled.
<img width="642" alt="Screenshot 2022-03-10 at 10 22 51" src="https://user-images.githubusercontent.com/30186818/157631136-6d0ca9a0-554d-44a3-892f-bce09fdb5386.png">

### Steps to reproduce

1. Open demo and scroll down.

### Demo

https://jsfiddle.net/80ymxcj4/1/

### Your environment
* Handsontable version: 12.0.0 
* Browser name and version: not related
* Operating system: not related

**Comment by warpech** [comment]
Closing as done
