### ISSUE TITLE
ANGULAR IVY SUPPORT

### ISSUE THREAD

**Issue by orbitturner** [handsontable/handsontable#9292]
### Description
We're having many troubles using the library since we switched to Angular 13 du to the view engine.
Can You guys implement an update for IVY support.

### Your environment
* Angular version: "@angular/core": "~13.2.0",
* Handsontable version: "@handsontable/angular": "^11.1.0"

**Comment by AMBudnik** [comment]
Hi @orbitturner 

We were not informed about issues from other Angular 12+ users. Could you please list the issues?

**Comment by orbitturner** [comment]
> Hi @orbitturner
> 
> We were not informed about issues from other Angular 12+ users. Could you please list the issues?

Hello Sorry For the late. So we are getting a lot of warnings messages when using the lib with angular 13 it usually happens at build time.

For Exemple : 👇🏾
![image](https://user-images.githubusercontent.com/39173514/160648288-06aee5eb-7b9c-485c-8f11-2c718dda7485.png)

As txt :

_Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\index.mjs depends on 'core-js/modules/es.object.get-own-property-names.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\editors\registry.mjs depends on 'core-js/modules/es.array.iterator.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\editors\registry.mjs depends on 'core-js/modules/es.weak-map.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\editors\registry.mjs depends on 'core-js/modules/es.string.iterator.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\editors\registry.mjs depends on 'core-js/modules/es.object.to-string.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\core.mjs depends on 'core-js/modules/es.array.sort.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\validators\dateValidator\dateValidator.mjs depends on 'core-js/modules/es.string.search.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\editors\dropdownEditor\dropdownEditor.mjs depends on 'core-js/modules/es.array.filter.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\renderers\checkboxRenderer\checkboxRenderer.mjs depends on 'core-js/modules/es.regexp.to-string.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\renderers\checkboxRenderer\checkboxRenderer.mjs depends on 'core-js/modules/es.string.includes.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\selection\highlight\highlight.mjs depends on 'core-js/modules/es.array.fill.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\plugins\base\base.mjs depends on 'core-js/modules/es.array.join.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\selection\highlight\highlight.mjs depends on 'core-js/modules/es.object.get-own-property-descriptors.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\selection\highlight\highlight.mjs depends on 'core-js/modules/es.object.keys.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\dataMap.mjs depends on 'core-js/modules/es.number.constructor.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
93m
Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\dataMap.mjs depends on 'core-js/modules/es.number.is-integer.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\core.mjs depends on 'core-js/modules/web.immediate.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\core.mjs depends on 'core-js/modules/es.array.reverse.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\3rdparty\walkontable\src\selection.mjs depends on 'core-js/modules/es.object.values.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\editors\dateEditor\dateEditor.mjs depends on 'pikaday'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\3rdparty\SheetClip\SheetClip.mjs depends on 'core-js/modules/es.string.starts-with.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\handsontable\plugins\filters\condition\endsWith.mjs depends on 'core-js/modules/es.string.ends-with.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\devReposit\QUALITY-CENTER\QCTOOLS-BYT\node_modules\hot-formula-parser\evaluate-by-operator\operator\formula-function.mjs depends on '@handsontable/formulajs'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies_

**Comment by AMBudnik** [comment]
The topic of those warnings was raised here https://forum.handsontable.com/t/commonjs-or-amd-dependencies-can-cause-optimization-bailouts/5197 (for Angular 7 - before Ivy)
