### ISSUE TITLE
Merged cells rendering issue

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9298]
### Description

When the table is wide enough, then cells that come after the merge are rendered incorrectly, without borders and also there is an issue with selecting them.

### Steps to reproduce
1. Scroll to the right end of the table;

### Demo

https://jsfiddle.net/wuhc3p69/

### Your environment
* Handsontable version: 11.1.0
* Browser name and version: Google Chrome 99
* Operating system: MacOS Monterey 12.2

[Zendesk](https://handsontable.zendesk.com/agent/tickets/28298)

**Comment by AMBudnik** [comment]
Solved in v15.0.0. Updated demo https://jsfiddle.net/t3vaxfod/

We added new API `merge cells > virtualized`.
