### ISSUE TITLE
Expose editors to other libraries to allow extension

### ISSUE THREAD

**Issue by optilude** [handsontable/handsontable#930]
Right now, it's impossible to build custom editors that extend HandsontableTextEditorClass, because it is not exposed outside the jquery.handsontable script (i.e. it lives inside a closure). This is a shame, because re-implementing an editor without it is pretty painful.

Can we make it available, e.g. as a property of the Handsontable class?

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by AMBudnik** [comment]
I'm transferring this issue into a discussion.
Please feel free to leave your comment and suggestion for this change.
