### ISSUE TITLE
Documentation friendly for React developers

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9303]
### Description

This is an epic about improving the docs from the perspective of the developers who use the React framework. As result of this epic, all the content of the docs should be available in a form idiomatic to React. This epic also lays the ground for adding relevant content for other frameworks (Angular, Vue 2, Vue 3) in the future.

The main branch for this epic is [`feature/react-docs`](https://github.com/handsontable/handsontable/tree/feature/react-docs) - all the subtasks will be merged to it instead of `develop`.

### Links

Internal project: https://kb.handsontable.com/display/PROJ/Documentation+friendly+for+React+developers

**Comment by AMBudnik** [comment]
Closed as all of the tasks are completed.
