### ISSUE TITLE
Integrate Code Block transformation into the build process

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9313]
This is a task in the epic https://github.com/handsontable/handsontable/issues/9303

Details are provided in the KB article https://kb.handsontable.com/display/PROJ/Documentation+friendly+for+React+developers

**Comment by jansiegel** [comment]
This issue should probably be resolved after finishing #9384 (it implements a new vuepress container, which should take care of the transformation integration).

**Comment by warpech** [comment]
Closing as tracked in #9384
