### ISSUE TITLE
Vertical scroll syncing issue with frozen column  

### ISSUE THREAD

**Issue by fuggfuggfugg** [handsontable/handsontable#9318]
### Description
I am using a heavily modified version of Handsontable. This was working as expected until recently where I noticed this issue. 
With the first column frozen,  scrolling vertically causes rows mismatching, a slight delay in rendering the remaining columns to sync with the frozen column. This happens in Chrome, FF & Safari

See Images: 
https://www.dropbox.com/s/4a8gfjluz7ww09i/1.png?dl=0
https://www.dropbox.com/s/7tegwz6zc4mg227/2.png?dl=0 

Notice in the 2nd image, The screenshots display the mismatch for the duration of the OnTableScroll call. 

### The Fix 
**This works only in Chrome.** I was able to `git bisect` and compare with an older commit. I was able to isolate the problem to the  sidebar which had a `background-image` and `background-attachment: fixed` that was missing in my latest code. When I re-apply the image and attachment, the mismatch no longer occurs and the syncing is more responsive as expected. **This works only in Chrome.** 
See Video - https://www.dropbox.com/s/uxmz3e98qwrvrz2/Handsontable%20scrolling.mov?dl=0

I assume background-attachment: fixed will force a repaint on scrolling? I was wondering if there was a cleaner fix.

### Steps to reproduce
Unfortunately I have no good way to reproduce but I can provide profiles for both with and without issue. 

### Your environment
* Handsontable version: Old version heavily modified.
* Browser name and version: Chrome Version 99.0.4844.51 (Official Build) (x86_64)
* Operating system: Mac El Capitan

**Comment by AMBudnik** [comment]
Hi @fuggfuggfugg 

There are a lot of questions that would need to be answered before we will be able to help with the investigation.

1. What are the changes that you did regarding `I am using a heavily modified version of Handsontable`?
2. When did you notice the changes (after browser update, Handsontable update)?
3. What are the settings that you found replicating the issue (is it only a set height and frozen columns)?
4. Does anything changes if you put Handsontable container outside of the parent DIV element?

**Comment by AMBudnik** [comment]
Hi @fuggfuggfugg do we have any updates on this subject?

**Comment by fuggfuggfugg** [comment]
1. What are the changes that you did regarding I am using a heavily modified version of Handsontable?
> We have one of the earlier versions of Handsontable, When I say it is heavily modified, I mean most of the columns have their own renderers with some CSS embedded. Notice the first column which also has [+/-] icons to handle tree structure. 

2. When did you notice the changes (after browser update, Handsontable update)?
> Started to noticed the scrolling issue when I removed the background-image and background-attachment from the sidebar menu on the page. 

3. What are the settings that you found replicating the issue (is it only a set height and frozen columns)?
> Removing background-image and background-attachment:fixed introduces the delayed scrolling. Adding it back fixes it again. 

4. Does anything changes if you put Handsontable container outside of the parent DIV element?
> Haven't tried this.

**Comment by AMBudnik** [comment]
@fuggfuggfugg please let me know if step no 4 with using Handsontable without any DIV parents changes anything. If that won't help I would need to ask for a demo where we will be able to replicate the issue. For the code review service please contact us at support@handsontable.com
