### ISSUE TITLE
NestedRows: cell properties are not properly set when collapsing rows

### ISSUE THREAD

**Issue by rvaandrager** [handsontable/handsontable#9322]
### Description

Cell properties set by using the cells function are not properly rendered when collapsing rows. Cell properties are set to the wrong row when some rows have been collapsed. 

### Steps to reproduce

1. Create a nested table and set some properties on rows using the cells function. In my [example](https://jsfiddle.net/9bzmgsh7/) all rows containing a category have blue text.
2. Collapse one row, for instance row 1. Row 7 will become row 2.
3. The cell properties of the original row 7 should be applied to row 2, but they are applied to row 3. All following category rows are now rendered as normal rows, where the first child of each category row is rendered blue.
4. When collapsing more rows, the cell properties disappear altogether.

### Demo

https://jsfiddle.net/9bzmgsh7/

### Your environment
* Handsontable version: 11.1.0
* Browser name and version: All
* Operating system: All

**Comment by AMBudnik** [comment]
Hi @rvaandrager 

we do not have a styling guide yet, and nestedRows has a different data structure than non0nested data. For your use case, I recommend using CSS. Here is an example http://jsfiddle.net/0x98ensb/ 

If you would need anything more than that please contact me at support@hansontable.com
