### ISSUE TITLE
[12.0.0] Cmd ⌘ + Shift ⇧ + Arrow keys don't work

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9323]
### Description

Cmd ⌘ + Shift ⇧ + Arrow keys on macOS and Ctrl + Shift + Arrow keys on Windows don't work at all with v12.
![v12cmd-shift-arr2](https://user-images.githubusercontent.com/30186818/158996630-5db7d500-bb6e-441b-bf30-268888ea6cf4.gif)

With v11 it extended the selection by 1 (one) cell only in each direction.
![v11cmd-shift-arr](https://user-images.githubusercontent.com/30186818/158996597-3a13aaf1-0148-489d-a847-9f9726e84fe9.gif)

### Expected result
Restoring working on v11. Extending selection by one cell in each direction.

### Demo

https://jsfiddle.net/1vw2f79m/ v12
https://jsfiddle.net/toy2mear/ v11

### Your environment
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by warpech** [comment]
Closing as done and verified by QA
