### ISSUE TITLE
[12.0.0] Restoring operation of Shift + Page up/down

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9327]
### Description

- Shift + Page up/down on Windows and macOS
- Shift + Fn + Arrow up/down on macOS 
should work with v12 as in v11.

### Actual result
Selection remains unchanged.

![Kapture 2022-03-22 at 11 16 25](https://user-images.githubusercontent.com/30186818/159461066-02d74096-faf0-41c0-8a0b-b56cc0f525f0.gif)

### Expected result
As page up/down. 
![Kapture 2022-03-22 at 11 27 15](https://user-images.githubusercontent.com/30186818/159461682-64607f74-2533-4041-ad37-e91f75ab0a32.gif)

### Demo

https://jsfiddle.net/oxk8md54/ v12.0.0 broken
https://jsfiddle.net/9g5x0amk/ v11.1 fixed

### Your environment
Handsontable version: 12.0.0
Browser name and version: Chrome 100.0.4896.20
Operating system: macOS 12.2.1, Windows 10

**Comment by kirszenbaum** [comment]
As discussed, this fix won't be included in the changelog and release notes (@warpech @wszymanski @AMBudnik)

**Comment by aninde** [comment]
Fixed on last RC-v12 https://jsfiddle.net/js_ziggle/28dzn6qg/

**Comment by warpech** [comment]
Closing as done and verified by QA
