### ISSUE TITLE
The `trimWhitespace` is not included in the documentation

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9329]
### Description

The `trimWhitespace` is not included in the documentation and it does not work (as described at https://github.com/handsontable/handsontable/issues/7387).

### Links

1. TS definition for it https://github.com/handsontable/handsontable/blob/2dbc605c14b4f13eb25b77679f1c1cab98a274ad/handsontable/types/settings.d.ts#L198
2. Related issues 
* https://github.com/handsontable/handsontable/issues/7387
* https://github.com/handsontable/handsontable/issues/3930
* https://github.com/handsontable/handsontable/issues/7557
3. Demo for tests https://jsfiddle.net/Lyt103o8/ (v11.1)

Inform [Zen](https://handsontable.zendesk.com/agent/tickets/29428)

**Comment by aninde** [comment]
trimWhitespace is in the code but not in the documentation

https://github.com/handsontable/handsontable/blob/7fa1857d40ee37f4e9ece759891015bf6a06148e/handsontable/src/dataMap/metaManager/metaSchema.js#L4259

I guess a typo at this point causes it not to be generated in the document
https://github.com/handsontable/handsontable/blob/7fa1857d40ee37f4e9ece759891015bf6a06148e/handsontable/src/dataMap/metaManager/metaSchema.js#L4243

**Comment by warpech** [comment]
This issue is solved by PR #9872

**Comment by AMBudnik** [comment]
Added with Handsontable v12.1.3
