### ISSUE TITLE
How can i trigger 'copy/cut/paste' event by myself?

### ISSUE THREAD

**Issue by tymzyx** [handsontable/handsontable#9336]
### Description

The code is like bellow, i closed the copyPaste in Handsontable: 
const settings = {
    ...,
    copyPaste: false,
    copyable: false,
}
const hotInstance = new  Handsontable(dom, settings);
const hTable = hotInstance.rootElement;
hTable.addEventListener('paste',  myPasteAction);
hTable.addEventListener('copy',  myCopyAction);
hTable.addEventListener('cut',  myCutAction);

But the event listener is not trigger when press keyboard shortcuts:
CTRL/CMD + V
CTRL/CMD + C
CTRL/CMD + X

### Demo
https://jsrun.net/XAeKp/edit

### Environment
* Handsontable version: 11.1.0
* Browser name and version: chrome
* Operating system: windows/macOS

**Comment by tymzyx** [comment]
Thanks for the comment @AMBudnik. 
I want to paste data with style into Handsontable copied from outer table (like Excel).
So i try to  get the clipboardData in system clipboard by ClipboardEvent.clipboardData.getData('text/html'), but now the custom event listener is not trigger.

I used an other method to get clipboardData like below:

async function getClipboardContents() {
  let text;
  try {
    const clipboardItems = await navigator.clipboard.read();
    for (const clipboardItem of clipboardItems) {
      for (const type of clipboardItem.types) {
        const blob = await clipboardItem.getType(type);
        if (item && item.type === 'text/html') {
          text = await item.text();
        }
      }
    }
  } catch (err) {
    console.error(err.name, err.message);
  }
}

But the text got from this method can not contain style info in windows, Chrome.

**Comment by adrianszymanski89** [comment]
Hi @tymzyx 

I researched the topic as it's an interesting case. Unfortunately, it looks like there wasn't really a good way to achieve it. The only option I found to successfully copy the text content from other sources with at least some kind of styling is to have a custom function on that site to make it possible to copy the content to the clipboard. Then, when you would paste such content into the cell in Handsontable it would look, for example, like this:

`<b>Example HTML data</b>`

So it's still not exactly what you need, but it's some progress. Here's an example of such a function:

https://jsfiddle.net/andreyprokhorov/xpvt214o/774620/
