### ISSUE TITLE
The definition of the `paste()` method in the `CopyPaste` plugin should be improved

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9337]
### Description

In the description of the `paste()` method we lack the important messages written on the Clipboard page that

>Due to security reasons, modern browsers disallow to read from the system clipboard.

### Links

1. Clipboard - https://handsontable.com/docs/basic-clipboard/#paste
2. `paste()` - https://handsontable.com/docs/api/copy-paste/#paste

**Comment by kirszenbaum** [comment]
Fixed here:
https://github.com/handsontable/handsontable/pull/9724/files#diff-df7f8d2f66f6cb72378be09850c1b347aa890accc2c7d3b4b559ff94f9fb48f2R314-R315
