### ISSUE TITLE
Performance issue with state updates inside selection callback

### ISSUE THREAD

**Issue by pabloimrik17** [handsontable/handsontable#9339]
### Description
Hi guys,

i have been struggling with a performance issue on my app with the HotTable component with a large dataset (~2000 rows and ~ 40 columns)

On a certain view of the app we use the HotTable to render the data, also a few action buttons (not in context menu) below the component.

One button is disabled until you have selected (click) something on the table. I have a state property with the selected cells.
I update this state variable with two callbacks afterDeselect and afterSelection. 
The data, column and colHeaders info is also on my state.
Then i pass to the component the data, colum, colHeaders props from my state data.

Every time i click on any cell, the table take some time to render the selected visual state or any change i apply.

The issue goes away if i dont store the data, colums and colHeaders on my state, instead i send the data to the HotTable via ref using updateSettings method.

Looks like in the selection callbacks, the setState update (even not updating data, colHeaders or columns) is affecting in someway the HotInstance and rendering all the time

### Demo

Bad performance (my scenario): https://codesandbox.io/s/handsontable-forked-3jp2fx?file=/src/index.js
Good performance (updateSettings, no state): https://codesandbox.io/s/handsontable-forked-b464gm?file=/src/index.js

### Your environment
* React wrapper version: 11.1.0
* Handsontable version: 11.1.0
* Browser name and version: Chrome (latest)
* Operating system: Windows 10

**Comment by AMBudnik** [comment]
Hi @pabloimrik17 

Did you consider using `afterSelectionEnd` instead of the `afterSelection`. Here https://jsfiddle.net/2yhLzxw1/2/ we can see how many times the `afterSelection` runs compare to the `afterSelectionEnd`. It makes a huge difference in your application as well.

**Comment by pabloimrik17** [comment]
Hi, i a

> Hi @pabloimrik17
> 
> Did you consider using `afterSelectionEnd` instead of the `afterSelection`. Here https://jsfiddle.net/2yhLzxw1/2/ we can see how many times the `afterSelection` runs compare to the `afterSelectionEnd`. It makes a huge difference in your application as well.

Hi i also tried that callback and the result is almost the same in my scenario, because we most of the time select cells one by one and not in range. 

The problem seems to be around how HotTable trates data prop i guess when a new render occurs. 

Is this behaviour expected? 

I mean for this case (a very common case) where you want to track the selected cells in order to update some UI outside the table, using that callback and with this size of data, is this "right or there is any change to review this with your dev team?

I think i can switch to the updateSettings way, but this is for a "Vanilla Javascript approach" than a React.

**Comment by AMBudnik** [comment]
I have asked for a second opinion and should be back with updates before the weekend.

**Comment by AMBudnik** [comment]
Hi @pabloimrik17 here https://jsfiddle.net/js_ziggle/wxjeq9d6/ is a v12 (planned to be released next week). It seems to work faster. Does it work for you as well?

**Comment by pabloimrik17** [comment]
> Hi @pabloimrik17 here https://jsfiddle.net/js_ziggle/wxjeq9d6/ is a v12 (planned to be released next week). It seems to work faster. Does it work for you as well?

Looks great! 

Can we keep this issue open until the release? I will try it ASAP and come back here to give you feedback

**Comment by AMBudnik** [comment]
Sure. I will notify you once we publish v12.

**Comment by pabloimrik17** [comment]
Hi, everything works really fast and smooth after updating to 12.0.

Thanks for everything :D

**Comment by AMBudnik** [comment]
I'm more than happy to hear that, @pabloimrik17 

Thank you for the update :-)
