### ISSUE TITLE
[12.0.0] Page up / down while editing didn't work

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9347]
### Description

Page up / down while editor didn't work as expected.

### Steps to reproduce

1. Open editor on any cell, write `test`
2. Press Page up
### Actual result
Nothing changes.
![regv12](https://user-images.githubusercontent.com/30186818/159960417-b8b1f789-16d6-4c68-b66f-e068425fbe60.gif)

### Expected result
![v11fix](https://user-images.githubusercontent.com/30186818/159960500-92dcf142-990b-4c60-b204-37d9e4a450a6.gif)

Page Up | Page Up ⇞ | When editing:save your changes, and move the selection one screen up
-- | -- | --
Page Down | Page Down ⇟ | When editing:save your changes, and move the selection one screen down

### Demo

https://jsfiddle.net/js_ziggle/28dzn6qg/ v12 broken
https://codesandbox.io/s/handsontable-react-data-grid-hello-world-app-bhipr?from-embed v11 fixed
https://handsontable.com/demo

### Your environment
* Handsontable version: Release candidate-12, js & wrappers
* Browser name and version: Edge 99, Chrome Beta 100
* Operating system: macOS 12.2.1, Windows 10

**Comment by warpech** [comment]
Closing as this was fixed in https://github.com/handsontable/handsontable/pull/9349. @aninde please reopen if otherwise.

**Comment by aninde** [comment]
This works and was tested during code freeze.
