### ISSUE TITLE
Docs: Add Czech language to the 12.1 docs

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#9354]
In #9343, we added a new translation: `cs-CZ`:

To do:
- After releasing the `12.0` docs, add `cs-CZ` to the `12.1` docs

**Comment by kirszenbaum** [comment]
I think I'm for **Czech Republic**:
- Looking at Google and language corpora, it's way more widely used
- It seems like the Czech government only [recently](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/554812/Czechia_Information_Paper-Updated_September_2016.pdf) added **Czechia** as a political name to the [UN terminology database](https://unterm.un.org/UNTERM/Display/Record/UNHQ/NA/4275087d-4018-4082-899d-95f37efeda65) (before, it was only a geographical name) but they did not remove the **Czech Republic** option, which means they're fine with it (so it's a different situation than, say, [**Holland** vs **The Netherlands**](https://www.bbc.com/news/blogs-news-from-elsewhere-49921029#:~:text=The%20country%20will%20switch%20to,will%20survive%2C%20says%20Dutch%20News.)
- If we go for a less prevalent form (**Czechia**), it sends a signal that there **is** some reason (probably political) for that, so if we want to be seen as apolitical, I'd simply use the more popular form

**Comment by warpech** [comment]
I can see that reputable big corpos use the word Czechia in some instances. Probably it is not political anymore: 
- https://github.com/handsontable/handsontable/pull/9343#issuecomment-1083629702
- https://docs.microsoft.com/en-us/partner-center/develop/partner-center-supported-languages-and-locales
- https://developer.adobe.com/experience-manager/reference-materials/6-5/coral-ui/coralui3/Coral.i18n.html
- https://support.zendesk.com/hc/en-us/articles/4408821324826-Zendesk-language-support-by-product
- https://developers.google.com/adwords/api/docs/appendix/codes-formats (expand "Country codes")
- https://webservices.amazon.com/paapi5/documentation/locale-reference/germany.html
- https://help.sap.com/viewer/7ac66320ca514acc89396a367db6dba8/4.2.8/en-US/e53ea2707ee51014a997d681b0e91070.html

**Comment by kirszenbaum** [comment]
Done in #9445 and #9446, closing
