### ISSUE TITLE
About "fixedrowsbottom"

### ISSUE THREAD

**Issue by Searworld** [handsontable/handsontable#9357]
### Description

Hi，Use config “fixedRowsBottom” to fix a row at all times.
 Can I only fix the last row when the data is outside the visualization area ? when physically filtering or loading, the data does not fix the last row in the visualization area ?  thanks~~

### Links

https://handsontable.com/docs/api/options/#fixedrowsbottom

**Comment by adrianszymanski89** [comment]
Hi @Searworld 

Just to clarify things. If I understood you correctly, you don't want to have the last, fixed row visible while, for example, filtering. Right?

![image](https://user-images.githubusercontent.com/92314130/160823241-68b61259-a7e4-475f-97b3-7515c5ba9fd7.png)

**Comment by Searworld** [comment]
@adrianszymanski89 yes

**Comment by adrianszymanski89** [comment]
That wouldn't be possible, unfortunately. If you have **fixedRowsBottom** option enabled there's always must be a fixed row (or rows).

**Comment by Searworld** [comment]
ok, thanks~ @adrianszymanski89 [adrianszymanski89](https://github.com/adrianszymanski89)
