### ISSUE TITLE
Manual Column Resize 

### ISSUE THREAD

**Issue by yosr-maker** [handsontable/handsontable#9360]
### Description
Manual Column Resize and Manual row resize doesn't work on touch screan 

### Demo

https://jsfiddle.net/handsoncode/c6rgz08x/
![Cellules](https://user-images.githubusercontent.com/57325844/161028143-778e168d-d5e0-47ba-a6c2-a64e6d120c85.png)

### Your environment
* React wrapper version: Last version 
* Handsontable version:10.0.0
* Browser name and version: chrome,mozilla.. 
* Operating system:Windows

**Comment by AMBudnik** [comment]
Hi @yosr-maker 

This topic is already reported at https://github.com/handsontable/handsontable/issues/5932 

As we do not keep duplicates of the same subject I will need to close your ticket. But I will notify you as soon as we merge the changes to https://github.com/handsontable/handsontable/issues/5932 into the official version of Handsontable.

**Comment by yosr-maker** [comment]
okey ! thank you
