### ISSUE TITLE
Improve compatibility of some keyboard shortcuts

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9361]
### Description

The issue is about adding/removing/fixing shortcuts to Handsontable. In the end, the keyboard shortcuts should be compatible with the most known spreadsheets on the market.

#### Cell navigation

Shortcut | Expected behavior | Issue
-- | -- | --
Cmd/Ctrl + Arrow up | Move to the first cell (first row) in a column | #9363
Cmd/Ctrl + Arrow down | Move to the last cell (last row) in a column | ^
Cmd/Ctrl + Arrow left | Move to the left-most cell in a row | ^
Cmd/Ctrl + Arrow right | Move to the right-most cell in a row | ^
Home | Move to the first non-frozen cell in a row | #9364
Cmd/Ctrl + Home | Move to the first non-frozen cell of the table | ^
End | Move to the last non-frozen cell in a row | ^
Cmd/Ctrl + End | Move to the last non-frozen cell of the table | ^

#### Cell selection

Shortcut | Expected behavior | Issue
-- | -- | --
Cmd/Ctrl + Shift + Arrow up | Extend the selection of cells to the first cell of the current column | #9365
Cmd/Ctrl + Shift + Arrow down | Extend the selection of cells to the last cell of the current column | ^
Cmd/Ctrl + Shift + Arrow left | Extend the selection of cells to the left-most cell of the current row | ^
Cmd/Ctrl + Shift + Arrow right | Extend the selection of cells to the right-most cell of the current row | ^
~Cmd/Ctrl + Shift + Home~ | ~Extend the selection of cells to the first non-frozen cell of the current row~ (https://github.com/handsontable/handsontable/issues/9428) | ^
~Cmd/Ctrl + Shift + End~ | ~Extend the selection of cells to the non-frozen last cell of the current row~ (https://github.com/handsontable/handsontable/issues/9428) | ^
Shift + Page up | Extend the selection of cells for one screen up | ^
Shift + Page down | Extend the selection of cells for one screen down | ^
Cmd/Ctrl + Enter | Fill the selected range of cells with the value of the active cell | #9366

#### Cell editing

Shortcut | Expected behavior | Issue
-- | -- | --
Home | Move the cursor to the beginning of the text | #9367
End | Move the cursor to the end of the text | ^
Cmd/Ctrl + Z | Undo last action entered into cell's editor | ^
Cmd/Ctrl + Y | Redo last action entered into cell's editor | ^
Cmd/Ctrl + Shift + Z | Redo last action entered into cell's editor | ^

#### Plugins

Shortcut | Expected behavior | Issue
-- | -- | --
Ctrl + M | Merge/Unmerge the selected cells (remove support for Cmd + M) | #9368

#### General

 - On macOS, all shortcuts that use the meta key should only work with the `Command` key. On other OS (Windows, Linux) the shortcut should work only with the `Control` key (#9369)
 - #9394
 - #9401

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

**Comment by AMBudnik** [comment]
All the issues on the list in this epic are closed as done and published in [Handsontable v12](https://handsontable.com/docs/release-notes/#_12-0-0).
