### ISSUE TITLE
Change behavior of the Home/End and Cmd/Ctrl + Home/End keyboard shortcuts

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9364]
### Description

The issue is about changing the behavior of the Home/End and Cmd/Ctrl + Home/End key combinations. The issue is part of the [Epic issue](https://github.com/handsontable/handsontable/issues/9361) and here are the expected results:

Shortcut | Expected behavior
-- | --
Home | Move to the first non-frozen cell in a row 
Cmd/Ctrl + Home | Move to the first non-frozen cell of the table 
End | Move to the last non-frozen cell in a row 
Cmd/Ctrl + End | Move to the last non-frozen cell of the table

**Comment by AMBudnik** [comment]
Issue closed as done and published in [Handsontable v12](https://handsontable.com/docs/release-notes/#_12-0-0).
