### ISSUE TITLE
Restore the native keyboard shortcuts in cells editors

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9367]
### Description

The issue is about restoring the native behavior of some keyboard shortcuts. There are some conflicts with OS once cell editing. The issue is part of the [Epic issue](https://github.com/handsontable/handsontable/issues/9361) and here are the expected results:

Shortcut | Expected behavior
-- | --
Home | Move the cursor to the beginning of the text 
End | Move the cursor to the end of the text 
Cmd/Ctrl + Z | Undo last action entered into cell's editor 
Cmd/Ctrl + Shift + Z | Redo last action entered into cell's editor

**Comment by warpech** [comment]
@aninde or @budnix was this a problem in 11.1.0 or was it introduced with the SM changes?

**Comment by budnix** [comment]
> @aninde or @budnix was this a problem in 11.1.0 or was it introduced with the SM changes?

@warpech Behind Home/End keyboard shortcuts there is a completely new feature. And about Cmd/Ctrl + Z/Shift + Z there was a bug that was introduced in ~0.10 or something.

**Comment by warpech** [comment]
> And about Cmd/Ctrl + Z/Shift + Z there was a bug that was introduced in ~0.10 or something.

@budnix what bug? Is there a GH issue for it that can be linked here?

**Comment by budnix** [comment]
@warpech There is no specific bug reported on the issue board. The bug was found during the investigation of how undo/redo behaves in the text-based editors versus native textarea.

**Comment by AMBudnik** [comment]
Added in Handsontable v12. Here https://handsontable.com/docs/release-notes/#_12-0-0 is the full list of changes for the version.
