### ISSUE TITLE
Remove the support for Cmd+M keyboard shortcut

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9368]
### Description

The issue is about removing the Cmd+M shortcut that triggers the cells merging. The shortcut is conflicted with macOS that by default minimized the window. The issue is part of the [Epic issue](https://github.com/handsontable/handsontable/issues/9361) and here are the expected results:

Shortcut | Expected behavior
-- | --
Ctrl + M | Merge/Unmerge the selected cells (remove support for Cmd + M)

**Comment by AMBudnik** [comment]
Issue closed as done and published in [Handsontable v12](https://handsontable.com/docs/release-notes/#_12-0-0).
