### ISSUE TITLE
Distinguish the meta keys (Cmd/Ctrl) in keyboard shortcuts depending on the OS

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9369]
### Description
The issue is about distinguishing the meta keys (Cmd/Ctrl) depending on the OS. In v11.1 and below pressing the meta keys like Command or Control are treated the same. For example, the keyboard shortcut such as `Cmd + Arrow left` can be triggered on the macOS as well as `Ctrl + Arrow left`.

Within the issue, the behavior will be changed. On macOS only the Command meta key should be used to trigger related shortcuts and on other OS like Windows, Linux only the Control meta key should be tracked.

The issue is part of the https://github.com/handsontable/handsontable/issues/9361.

**Comment by AMBudnik** [comment]
Changes introduced in Handsontable v12. Here https://handsontable.com/docs/release-notes/#_12-0-0 is the full list f changes. Issue closed as done.
