### ISSUE TITLE
Table Disappear When Putting on Tab 

### ISSUE THREAD

**Issue by KiddoV** [handsontable/handsontable#9370]
### Description
I'm trying to make multiple table on different tab. See fiddle below:

Noted when changing to different tab, the table will disappear, looks like I have to ``.render()`` the table manually after changing the tab, but it is frustrating (if I want to keep the same data on different tabs).

To make the table visible, click on the top left corner (select all). (Not a good solution)

Also when resizing window on a tab and change it to different tab, the table disappear again!

### Steps to reproduce
1. Init all tables.
2. Try to change tab.
3. Noted the table disappeared.

### Demo
https://jsfiddle.net/KiddoV/1zj5oe2d/68/

### Your environment
* Handsontable version: 11.1
* Browser name and version: Chrome, Webview2...
* Operating system: Windows 10, Windows 7

**Comment by adrianszymanski89** [comment]
Hi @KiddoV 

indeed it looks like without using `.render()` the second table isn't rendered correctly. However, it's related to the method of how visibility is managed by jQuery. It's done by switching the parameter `display: block/none` which is known to not work very well with Handsontable. If you would be able to do that by using the parameter `visibility: visible/hidden`, then everything works fine, like in the example below:

https://jsfiddle.net/aszymanski/3o0d2usv/14/

If that's not possible for you, you can also try to run the method `selectCell()` within about 10ms timeout while switching between the tabs. The second solution would be to build a new table each time the tabs are being switched, but it looks like it might not be the best way, regarding the fact that you want to keep the same data.

**Comment by KiddoV** [comment]
I guess ``.render()`` works for me, at least it's not refresh my table data every time I switch the tab.
https://jsfiddle.net/KiddoV/1zj5oe2d/102/
Thanks anyway!
