### ISSUE TITLE
helpers is not exported from package, how to import helpers

### ISSUE THREAD

**Issue by Yee1014** [handsontable/handsontable#9377]
### Steps to reproduce

1. use vue/cli@5.0.4 create project
2. use pnpm install handsontable
3. follow [Basic example in Vue 3](https://handsontable.com/docs/vue3-simple-example/#basic-example-in-vue-3)

### Demo
```
<template>
  <div class="hello">
    <h3>HandsonTable Basic Usage</h3>
    <HotTable :settings="hotSettings"></HotTable>
  </div>
</template>

<script>
import { defineComponent, ref } from 'vue'
import 'handsontable/dist/handsontable.full.css'
import { HotTable } from '@handsontable/vue3'
import { registerAllModules } from 'handsontable/registry'
import { createSpreadsheetData } from 'handsontable/helpers'

registerAllModules()

export default defineComponent({
  components: { HotTable },
  setup() {
    const hotSettings = ref({
      data: createSpreadsheetData(1000, 1000),
      colWidths: 100,
      width: '100%',
      height: 320,
      rowHeaders: true,
      colHeaders: true,
      licenseKey: 'non-commercial-and-evaluation'
    })

    return {
      hotSettings,
    }
  },
})
</script>
```

### Console Error
```
Module not found: Error: Package path ./helpers is not exported from package /xxxxx/node_modules/handsontable (see exports field in /xxxxx/node_modules/handsontable/package.json)
```

### Your environment
* Vue 3 wrapper version: 3.2.31
* Handsontable version: 11.1.0
* Browser name and version:
* Operating system:
* vue/cli version: 5.0.4
* pnpm version: 6.23.6

**Comment by AMBudnik** [comment]
Hi @Yee1014 

This question was registered 2 days ago here https://github.com/handsontable/handsontable/issues/7489#issuecomment-1087482063. At the moment helpers are not exposed and there are no plans to alter that behavior.

**Comment by ngingihy** [comment]
@AMBudnik what do you mean? i cant use 
import {createEmptySpreadsheetData } from 'handsontable/helpers' anymore

**Comment by AMBudnik** [comment]
If it was possible before it happened outside of the supported way. Helpers are internal tools and they are not considered the official API for our customers.
