### ISSUE TITLE
Improve `copyable` option description

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9380]
### Description

In the documentation, it is said that 

![Zrzut ekranu 2022-04-7 o 10 21 39](https://user-images.githubusercontent.com/10757813/162154175-70b8746b-9d65-4343-bff3-1d50bd0f0221.png)

At the moment when we set `copyable` to `false` we do not save the value in the clipboard. But instead, we add an empty value in its place. So the clipboard is altered and `beforeCopy` hook is triggered.
That is why we cannot agree with the statement that turning the option to `false` `[...] disable copying for that cell`.

### Links

`copyable` option - https://handsontable.com/docs/api/options/#copyable
demo for tests - https://jsfiddle.net/8mvL64pf/6/

**Comment by kirszenbaum** [comment]
Fixed in [9724](https://github.com/handsontable/handsontable/pull/9724/files#diff-d6f82a465a0c166188b543692fd3292bd450f09cc013dbbf3fa5dd31c6ffcb0cL1084-R1087)
