### ISSUE TITLE
The large amount of data causes the page to freeze

### ISSUE THREAD

**Issue by Searworld** [handsontable/handsontable#9389]
### Description
Hello, The large amount of data causes the page to freeze. Is there any way to solve this problem?

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by adrianszymanski89** [comment]
Hi @Searworld 

Indeed there might be a performance issue while working with large data. There is a kind of workaround that you can try to avoid that problem. By using pagination, you can split the data into smaller chunks that will be rendered faster. 

This is an example with front side pagination: http://jsfiddle.net/aszymanski/p2q3cej7/
