### ISSUE TITLE
fixedColumnsLeft和rowHeights同时使用时固定列行高和非固定列会错开

### ISSUE THREAD

**Issue by HeySkye** [handsontable/handsontable#9392]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/dezfbgjt/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by adrianszymanski89** [comment]
Hi @HeySkye 

Can you please specify what is the issue?

**Comment by Sapphire2k** [comment]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/17328005/165231728-145e46eb-f43f-4380-abed-ed97a060a02e.png">

the problem i guess is like this which i sufferred T _ T
@adrianszymanski89

**Comment by Sapphire2k** [comment]
What's more, how keep the scrollbar visible to scroll, people use mouse in Windows can't scroll

**Comment by Sapphire2k** [comment]
Thanks, @adrianszymanski89 

My first issue demo also modified from the [OP's demo ](https://jsfiddle.net/handsoncode/dezfbgjt/)
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/17328005/165471214-013e87bc-4323-476c-91de-3b58dc98a968.png">

Add Css Style And Run again
```
::-webkit-scrollbar {
  width: 4px;
  height: 10px;
}
```

For the second issue:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/17328005/165470337-ed0f82d5-0614-47ec-9bbe-a7688d2d007e.png">

U can take a look this image, i just take a screenshot from your demo

**Comment by AMBudnik** [comment]
Hi @Sapphire2k 

If I would like to remove those scrolls, I recommend setting up `height` for `4px` instead https://jsfiddle.net/uk10x9pf/4/

![Zrzut ekranu 2022-05-11 o 13 30 31](https://user-images.githubusercontent.com/10757813/167839223-6216b58a-d498-4bdc-bad9-e9a92c8d57e3.png)

However, we do not have a styling guide yet so it might not work the same when you zoom in/out.
