### ISSUE TITLE
PageUp/PageDown keyboard keys do not work with context menu

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9394]
### Description

The `PageUp`/`PageDown` keyboard keys do not work with the context menu. 

![Kapture 2022-04-15 at 11 46 54](https://user-images.githubusercontent.com/571316/163556183-6fc5b73a-09c8-49d5-9af8-524d48df432c.gif)

```log
transformation.js:41 Uncaught TypeError: Cannot read properties of undefined (reading 'highlight')
    at Transformation.transformStart (transformation.js:41:1)
    at Selection.transformStart (selection.js:380:1)
    at callback (menu.js:375:1)
    at manager.js:108:1
    at onkeydown (recorder.js:92:1)
```

### Your environment
* Handsontable version: `develop`
* Browser name and version: -
* Operating system: -

**Comment by warpech** [comment]
@aninde or @budnix was this a problem in 11.1.0 or was it introduced with the SM changes?

**Comment by budnix** [comment]
> @aninde or @budnix was this a problem in 11.1.0 or was it introduced with the SM changes?

@warpech The bug was introduced within the SM.

**Comment by AMBudnik** [comment]
Issue closed as done and published in [Handsontable v12](https://handsontable.com/docs/release-notes/#_12-0-0).
