### ISSUE TITLE
Look and feel + themes

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#9397]
Hi

I'm a long time user, customer and fan of Handsontable. It's a very nice datagrid. But looking at the (primary?) competitor Ag-Grid your grid starts to look a bit... dated.

I would really love to see the styling get some attention. Some different themes out of the box (including dark mode!) and some sleak animations when the grid updates would go a long way. This is obviously subjective, but I'm really on the fence if I should choose HOT for my next project when considering the look and feel of the grid.

I believe it's already possible to style the grid to some extent, but just looking at the case studies on your webpage nobody seems to have done that much, which says something... And from my own experience, though it was a while since I tried now, it wasn't easy and mostly broke the grid. It would be nice if it was a "feature" to easily be able to style the table.

I hope this doesn't come across as rude or inconsiderate, I love HOT and I only want you to be successful :)

**Comment by AMBudnik** [comment]
Thank you for sharing your thoughts @ottosson I informed the planning team about your ideas. And I agree that dark mode is popular and really practical so it is a great idea to be able to style Handsontable the same way.

**Comment by ottosson** [comment]
I've since I wrote this been able to create my own dark (and light) theme of the grid. This was however very tedious and resulted in quite ugly css, as well as a few !important. And I spent more time than I dare think about.

The result is satisfactory, but it would be great if you could make it easier by using documented class names instead of long super specific selectors, and absolutely no css applied by javascript (hence the !important).

![image](https://user-images.githubusercontent.com/3355320/217022794-1dadc070-c621-4c18-a9a7-a4ff3df8fd5e.png)

![image](https://user-images.githubusercontent.com/3355320/217022906-d8ac239e-2988-4123-900a-fb4461609fb9.png)

**Comment by AMBudnik** [comment]
Hi @ottosson 

That feedback is super important. Thank you for sharing the feedback along with your vision of the result for both the light and the dark theme. 

We already took some steps to determine what should be done and what is the expected outcome, but it is too soon to share any promises or drafts. I will do my best to notify you as soon as we push the first changes online.

**Comment by ottosson** [comment]
Thanks for indulging :)

What I did was declare custom properties (CSS Variables) that correspond to the different parts of the grid. H-lines, V-lines, headers, cells/rows and so on, not only colors but some heights/widths as well. That makes it trivial to create your own color scheme/theme.

**Comment by AMBudnik** [comment]
Yes, styling row heights might be tricky. At this point, I do not know if we will be able to support that. But I am really excited and hope we will be able to share something spectacular soon.

**Comment by jd-carroll** [comment]
Wondering if there was any update on supporting a custom theme?

We are evaluating Handsontable and it is our preferred option; however, the inability to style the grid will prevent us from choosing Handsontable. Is there a rough timeline to any update? 

Not asking for a specific date, more is the feeling 23'Q3, 23'Q4, or beyond?

Thank you!

**Comment by adrianszymanski89** [comment]
Hi @jd-carroll 

It is on our roadmap, but it's still a work in progress. We can't give any specific date yet, but we're hoping for Q1 2024.

**Comment by KaKi87** [comment]
Hi,
How is this going ?
Thanks

**Comment by adrianszymanski89** [comment]
Hi @KaKi87 

This project is planned for this year. We will update you once it's completed and implemented.

**Comment by ottosson** [comment]
Please have a look at my forum post: https://forum.handsontable.com/t/change-filter-menu-size/7926
This is a good example where I would expect CSS to be enough but I need to use some funky javascript to achieve wanted result.

**Comment by jd-carroll** [comment]
When is this Themes project targeting (beta) release (2024 or 2025)?

**Comment by AMBudnik** [comment]
Hi @jd-carroll 

We are working on the specification. We'd like to start in Q3 2024. However, it is too soon to specify the release date.

**Comment by AMBudnik** [comment]
And the day has come! Thank you, everyone, for your feedback—@ottosson, @jd-carroll, @KaKi87. I hope our new Main and Horizon (light/dark) themes meet your requirements.

If you haven't had a chance to test them yet, I recommend visiting the main demo page at https://handsontable.com/demo, where you can easily switch between the themes. You can also learn more about the setup and how to create your own theme here: https://handsontable.com/docs/javascript-data-grid/themes/.

P.S. If you'd like to read more about the changes in this release, visit: https://handsontable.com/docs/javascript-data-grid/changelog/.
If you'd have any ideas on what could be changes please feel free to create separate issue.

**Comment by ottosson** [comment]
Hi @AMBudnik and thanks for this. Great effort!
I'm just missing some things to make it easier to work with hot-theming.

1. I don't see any variables to style the filter menu. Maybe it shares vars with the table, I haven't looked in to this yet. But it would in any way be nice to be able to style this separately.

2. It would be nice to have a playground where the different variables could be changed and directly reflect the change in a live table.

3. If nothing else it would be nice to have better documentation of what the different vars do. Most of them are more or less self explanatory but `--ht-table-transition` is an example of a var that I don't have a clue what it does.

4. Would it be possible to add some transitions for things that "pop up" like context menus, filter dialogs, cell drop downs and so on?

I will try to implement my current look (as seen above) as a theme soon. Maybe I will have more feedback then, and maybe some of my questions will be answered as well.

Anyway, I'm sure there are still things that can be improved or tweaked, but this is a great start!

Thanks!

**Comment by AMBudnik** [comment]
Thank you for sharing the feedback, @ottosson.
I have passed it on to the project teams, but they have already gone on their Christmas break. I should have more updates next week.

**Comment by AMBudnik** [comment]
Hi @ottosson 

our designer is reviewing your feedback and there's one question: could you please specify the CSS setup that changes the way filters are presented when you alter `--ht-line-height`? 

Here, I copied styles from the Horizon to create a custom theme, and `--ht-line-height` is set to `30px`. https://stackblitz.com/edit/pgrkmldm-dtuxdu75?file=some-custom-style.css,index.js,index.html,styles.css
It doesn't seem to cause any unexpected results in the dropdown menu for filters.

![Zrzut ekranu 2025-01-8 o 09 55 07](https://github.com/user-attachments/assets/f185d6be-13be-46a5-b681-c00aa45c846d)

**Comment by ottosson** [comment]
The example link does not have the column menu activated.
I'll see if I can reproduce the issue in a clean environment. Maybe it's something in my application that is interfering.

**Comment by AMBudnik** [comment]
Sorry, @ottosson I forgot to save the progress. Here's the demo https://stackblitz.com/edit/pgrkmldm-mxzfglmp?file=some-custom-style.css,index.js,index.html,styles.css

**Comment by ottosson** [comment]
some additional input on the theming experience:

For the most part it was a nice experience. A bit fiddly at times. Compared to my own theming effort before this I only used around 30 custom properties (css variables) for basically the same result. But it's still nice to be able to do more specific changes.

One thing I'm genuinely missing is to be able to style the filter menu a separate from the grid. I've had to resort to make custom css changes to get the look I want.

variables I'm missing are filter dialog:
border
background color
height(!!!) Now it is a very small window for what could potentially be a very long list.
select all/clear should be possible to style

I would also wish for you to rename the "clear" button to "select none" and add an actual clear filter button.

This is my filter menu after a bunch of custom css

![image](https://github.com/user-attachments/assets/b1f6aad8-46bc-49c0-a213-cf3a2c0d5648)

I havent't had time to look into the issue with the check mark, but I solved it temporarily with some custom css for the filter dialog, setting the line height to 20px.

**Comment by AMBudnik** [comment]
Thank you for sharing additional feedback, @ottosson . I will write it all in our internal ticketing system that we use to plan Stage 2 of Themes. 

I remember that other users requested to change the height and width of the menu as well. So, it is definitely something we should look at. 

I will create an issue separately for the button renaming and keep you updated. Currently, you can do that by loading a [custom language](https://handsontable.com/docs/react-data-grid/language/#create-custom-languages) to Handsontable, but I guess that this might be too complex for a single change.
