### ISSUE TITLE
[DOCS] Saving data guide example doesn't work in JSFiddle

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9398]
### Description

Code example from https://handsontable.com/docs/saving-data/#overview doesn't work in edit mode in JSFiddle. It seems that this path isn't correct `/docs/11.1/scripts/json/`

### Demo

https://jsfiddle.net/aszymanski/1vy6u3op/

### Your environment
* Handsontable version: 11.1.0
* Browser name and version: Google Chrome 100
* Operating system: MacOS Monterey 12.3.1

**Comment by aninde** [comment]
This demo works opened separately due to the fix and release of the new documentation. https://handsontable.com/docs/javascript-data-grid/saving-data/#saving-changes-using-a-callback
https://jsfiddle.net/bos0xtd1/

I'm closing https://github.com/handsontable/handsontable/issues/9398 as done.
