### ISSUE TITLE
The examples installation script fails on current develop.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#9399]
### Description
Currently (as for 60c660fd199257c93bbe32fa2b26b1833a9cb5a9), it's impossible to install the dependencies of the examples using the appropriate script.

Running the `install:version` script end with the following error:
```
Error: must not have multiple workspaces with the same name
package 'examples-ts' has conflicts in the following paths:
    /Users/(...)/www/handsontable/examples/11.1.0/docs/ts
    /Users/(...)/www/handsontable/examples/next/docs/ts
```

### Steps to reproduce

1. Pull the current develop state (60c660fd199257c93bbe32fa2b26b1833a9cb5a9)
2. cd examples
3. npm run install:version [version number]
4. See the error.

**Comment by warpech** [comment]
Closing as done
