### ISSUE TITLE
Remove Shift + PageUp/PageDown keyboard shortcuts for edited cell

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9401]
### Description

The issue is about removing the `Shift + PageUp/PageDown` keyboard shortcuts from the editor's context. The mentioned shortcuts work for the grid but should do nothing when the cell editor is opened.

The issue is part of the https://github.com/handsontable/handsontable/issues/9361.

**Comment by AMBudnik** [comment]
Issue closed as done and published in [Handsontable v12](https://handsontable.com/docs/release-notes/#_12-0-0).
