### ISSUE TITLE
[Warning] pikaday.css contains IE7 css hacks (which causes errors using the Parcel bundler)

### ISSUE THREAD

**Issue by veldsla** [handsontable/handsontable#9410]
### Description
IE7 css hacks in pikaday css like *zoom and *display

### Steps to reproduce
The included pikaday.css contains IE7 hacks that were removed from pikaday in 2018:
https://github.com/Pikaday/Pikaday/commit/f9d16ba900da2b2be57ff0ed3201bd4461dd71f1

The latest Parcel2 css bundler doesn't accept the *properties and reports these as errors preventing bundling of handsontable.

### Your environment
* Handsontable version: latest
* Browser name and version: NA
* Operating system: NA

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @veldsla 
Some time ago we were also requested to bump Pikaday to `1.8.2` regarding the following request https://github.com/handsontable/handsontable/issues/8237

I will share the details of this request with the team and notify as soon as the status of this task changes.

**Comment by AMBudnik** [comment]
This warning shows each time we build a project

<img width="734" alt="Zrzut ekranu 2022-05-11 o 13 54 26" src="https://user-images.githubusercontent.com/10757813/167843631-e292949c-b8ac-48ea-aff7-3899858f840f.png">


there are 7 places in the Pikdaday CSS settings with *properties.

**Comment by AMBudnik** [comment]
Hi @veldsla 

we just released Handsontable v12.1.0 which solves this issue.
Here you can read the full list of changes https://handsontable.com/docs/release-notes/#_12-1-0.
