### ISSUE TITLE
Wrong automatic column width when using custom renderer

### ISSUE THREAD

**Issue by fbrussa-novix** [handsontable/handsontable#9425]
### Description
Sometimes the automatic column width calculation does not work properly when using custom rendering.
![image](https://user-images.githubusercontent.com/42356504/165374348-28713a1f-758d-465c-a2dd-99d612e33986.png)

### Demo
https://jsfiddle.net/uczarLmy/

### Your environment
* Handsontable version: 11.1
* Browser name and version: Chrome 99.0.4844.51
* Operating system: Ubuntu/Windows/Mac

**Comment by adrianszymanski89** [comment]
Hi @fbrussa-novix 

Indeed, there's some problem with automatic column size. You can modify the default column sizing by using this option:

https://handsontable.com/docs/api/options/#autocolumnsize

In your case, I have modified the sampling ratio so the cell content would fit.

https://jsfiddle.net/aszymanski/bp47ydca/
