### ISSUE TITLE
[12.0] Docs: RTL Demo preview sticks out

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9433]
### Description

Demo https://handsontable.com/docs/layout-direction/#rtl-support on the site https://handsontable.com/docs/layout-direction/#rtl-support goes outside the area of preview on MacBook screen  and mobiles.

<img width="736" alt="Screenshot 2022-04-28 at 14 02 22" src="https://user-images.githubusercontent.com/30186818/165748205-923799ba-cb82-4637-9493-61e064b9e133.png">

### Your environment
* Handsontable version: 12.0.0
* Browser name and version: any
* Operating system: macOS 12.2.1

**Comment by budnix** [comment]
Fixed and deployed
