### ISSUE TITLE
Handsontable examples require manual installation of npm < 8.5

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9438]
### Description

In #9149, we upgraded CI to Node 16.14.x, but unfortunately it occurred to us that this version of Node contains npm 8.5, which has a bug that makes examples not buildable: https://github.com/npm/cli/issues/4774

Currently, the only way to build examples is to have Node 16.14 and downgrade npm using `npm i -g npm@8.4`, as we did in the GitHub workflow in this PR https://github.com/handsontable/handsontable/pull/9400

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by warpech** [comment]
According to [my conversation](https://node-js.slack.com/archives/C0J6DJ4PL/p1651222059133049) on npm channel in Node.js Slack, the https://github.com/npm/cli/issues/4774 is not seen as a bug by the npm team. So we need to figure out a solution other than downgrading to 8.5.

**Comment by warpech** [comment]
We shouldn't accept using Node 16.14+ with manually downgraded npm. Our choice is to:
1. revert to Node 16.13.x - not recommended, this version is not maintaned anymore
2. stop using nested workspaces - delete the intermediate `package.json`
3. explore migrating to other workspace systems (Yarn, PMPM - maybe they support nested workspaces?)

@jansiegel is point 2 feasible?

**Comment by jansiegel** [comment]
> We shouldn't accept using Node 16.14+ with manually downgraded npm. Our choice is to:
> 
> 1. revert to Node 16.13.x - not recommended, this version is not maintaned anymore
> 2. stop using nested workspaces - delete the intermediate `package.json`
> 3. explore migrating to other workspace systems (Yarn, PMPM - maybe they support nested workspaces?)
> 
> @jansiegel is point 2 feasible?

@warpech I'll see what I can do

**Comment by jansiegel** [comment]
I made a PR with a (hopefully) working solution: https://github.com/handsontable/handsontable/pull/9495.

**Comment by warpech** [comment]
Closing as done
