### ISSUE TITLE
Please add support v-model directive

### ISSUE THREAD

**Issue by Yee1014** [handsontable/handsontable#9443]
### Description

Binding data , use v-model is so great~

### Steps to reproduce

```
v-model="data"
```

### Demo

https://jsfiddle.net/Lpz4revj/16/

### Your environment
* Vue 3 wrapper version: 3.2.31
* Handsontable version: 11.1.0
* Browser name and version: Edge
* Operating system:

**Comment by AMBudnik** [comment]
Hi @Yee1014 

Please let me know what you would like to see in the documentation besides what we have here https://handsontable.com/docs/vue-hot-column/#using-the-renderer-editor-components-with-v-model?

**Comment by AMBudnik** [comment]
I will keep this issue closed until we get some more details.
