### ISSUE TITLE
VuePress dev server shows wrong URL sometimes

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#9449]
### Description
There is some console log which shows where documentation is served, i.e.: `VuePress dev server listening at http://localhost:8081/docs`. So far, there were an opportunity to place files in main `docs` folder for the latest version of documentation. 

Since introducing https://github.com/handsontable/handsontable/pull/9371 there is no single directory for the latest version of docs (there are `javascript-data-grid`, `vue3-data-grid`, `vue2-data-grid`, `react-data-grid`, `angular-data-grid` directories). Thus, an user using dev script locally should know that URL should look like:

`http://localhost:<PORT>/docs/javascript-data-grid` (for the latest version of docs) or `http://localhost:<PORT>/docs/<VERSION>javascript-data-grid` (for another)
`http://localhost:<PORT>/docs/vue2-data-grid` (for the latest version of docs) or `http://localhost:<PORT>/docs/<VERSION>vue2-data-grid` (for another version)
`http://localhost:<PORT>/docs/vue3-data-grid` (for the latest version of docs) or `http://localhost:<PORT>/docs/<VERSION>vue3-data-grid` (for another version)
`http://localhost:<PORT>/docs/react-data-grid` (for the latest version of docs) or `http://localhost:<PORT>/docs/<VERSION>react-data-grid` (for another version)
`http://localhost:<PORT>/docs/angular-data-grid` (for the latest version of docs) or `http://localhost:<PORT>/docs/<VERSION>angular-data-grid` (for another version)

Displayed server listening URL isn't complete. Probably it's based on VuePress' [base](https://vuepress.vuejs.org/config/#base) property. An opportunity to change displayed URL or print another log should be checked.

**Comment by warpech** [comment]
I think that this is low priority until @kirszenbaum or someone else complains.

**Comment by kirszenbaum** [comment]
@kirszenbaum – if we document it, I think we're fine

**Comment by warpech** [comment]
Closing as I think it is not relevant anymore. Please reopen if I'm wrong
