### ISSUE TITLE
Not shown images for "frameworked" docs

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#9462]
### Description 

There are some problems with that, it has been described within https://github.com/handsontable/handsontable/pull/9371 in `Limitations` section. It's related to the place where images are copied by `CopyWebpackPlugin`.

Note: Please keep in mind that images are already shown for some builds. Below is the list of scripts for which you can see the problem:

 - `DOCS_VERSION=next npm run docs:start`
 - `DOCS_FRAMEWORK=javascript DOCS_VERSION=next npm run docs:start`
 - `npm run docs:build`

### Preview 

<img width="420" alt="Screenshot 2022-05-06 at 17 15 33" src="https://user-images.githubusercontent.com/141330/167162092-91e8d536-3d7d-4023-89b2-5806edf4bbe2.png">

<img width="970" alt="Screenshot 2022-05-06 at 17 19 37" src="https://user-images.githubusercontent.com/141330/167162735-ec9c53a0-5d6f-4799-82e2-7393a231283f.png">

**Comment by warpech** [comment]
Closing as done
