### ISSUE TITLE
Data not showing

### ISSUE THREAD

**Issue by usmansolushunz** [handsontable/handsontable#9466]
I'm using handsontable first time but it doesn't work and I'm not sure why ??
 this is the code

   `new Handsontable(document.getElementById("test"), {
  data: table_data,
  height: 'auto',
  colWidths: [ 100, 100, 100, 100, 100, 100, 100, 100 ,100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
  colHeaders: [
    "What",
    "Staff No",
    "Date",
    "Service",
    "Staff",
    "Qty",
    "Invoice",
    "Location",
    "Customer",
    "Customer Mob",
    "Incentive %",
    "Incentive Rate",
    "Tax %",
    "Tax",
    "Value Inc Tax",
    "Value W/O Tax",
    "Actual Sale Value inc tax",
    "Actual Sale Value W/O tax",
    "Incen_Bill_Inc_Tax",
    "Incen_Bill_w/o_Tax",
    "Incen_Actual_Inc_Tax",
    "Incen_Actual_w/o_Tax",
  ],
  columns: [
    { data: 1, type: "text" },
    { data: 2, type: "text" },   
    { data: 3, type: "date"},
    { data: 4, type: "text" },
    { data: 5, type: "numeric" },
    { data: 6, type: "text" },
    { data: 7, type: "text" },
    { data: 8, type: "text" },
    { data: 9, type: "text" },
    { data: 10, type: "text" },
    { data: 11, type: "text" },
    { data: 12, type: "text" },
    { data: 13, type: "text" },
    { data: 14, type: "text" },
    { data: 15, type: "text" },
    { data: 16, type: "text" },
    { data: 17, type: "text" },
    { data: 18, type: "text" },
    { data: 19, type: "text" },
    { data: 20, type: "text" },
    { data: 21, type: "text" },
    { data: 22, type: "text" },
    
    
  ],
//   dropdownMenu: true,
//   hiddenColumns: {
//     indicators: true
//   },
//   contextMenu: true,
//   multiColumnSorting: true,
//   filters: true,
//   rowHeaders: true,
//   manualRowMove: true,
//   afterGetColHeader: alignHeaders,
//   afterOnCellMouseDown: changeCheckboxCell,
//   beforeRenderer: addClassesToRows,
  licenseKey: "non-commercial-and-evaluation"
});`
  
 while table_data is something like this
  0: {WHAT: "PACKAGE", STAFF_NOS: 1, DATE: "2022-04-30", SERVICE: "OUTSTATION MAC BRIDAL MAKEUP",…}
Actual_Sale_Rate_inc_tax: "20650.00"
Actual_Sale_Rate_w/o_tax: 17500
CUSTOMER: "Kajol Srivastava"
Customer_Mob: "918887515895"
DATE: "2022-04-30"
INCENTIVE_RATE: 20
INVOICE: "JP-2223-0335"
Incen_Actual_Inc_Tax: 4130
Incen_Actual_w/o_Tax: 3500
Incen_Bill_Inc_Tax: 4130
Incen_Bill_w/o_Tax: 3500
Incentive%: "20"
LOCATION: "Jopling"
QTY: "1.0"
SERVICE: "OUTSTATION MAC BRIDAL MAKEUP"
STAFF: "2-Gomti Nagar"
STAFF_NOS: 1
Tax: 3150
Tax%: 18
Value_Inc_Tax: "20650.00"
Value_w/o_Tax: 17500
WHAT: "PACKAGE"
1: {WHAT: "PACKAGE", STAFF_NOS: 1, DATE: "2022-04-29", SERVICE: "OUTSTATION MAC PARTY MAKEUP",…}
2: {WHAT: "POS", STAFF_NOS: 1, DATE: "2022-03-01", SERVICE: "NAILS REFILL-NAIL EXT. REMOVAL WITH MACHINE",…}
3: {WHAT: "POS", STAFF_NOS: 1, DATE: "2022-03-01", SERVICE: "NAILS REFILL-NAIL EXT. REMOVAL WITH MACHINE",…}
4: {WHAT: "POS", STAFF_NOS: 1, DATE: "2022-03-01", SERVICE: "HAIR COLOR-ROOT TOUCHUP WITH AMMONIA",…}

**Comment by adrianszymanski89** [comment]
Hi @usmansolushunz 

If you want to bind array of objects as a data, the data object should look like this:

https://jsfiddle.net/aszymanski/1tny0jmp/

**Comment by usmansolushunz** [comment]
I did it but I want export as excel is it possible?

**Comment by adrianszymanski89** [comment]
You can only export to CSV format, here's a documentation entry about it with examples:

https://handsontable.com/docs/export-to-csv/

**Comment by usmansolushunz** [comment]
Thanks, I'll check it out.

**Comment by AMBudnik** [comment]
It seems that there are no further issues so I'm closing this ticket. 
@usmansolushunz please contact us at support@handsontable.com if the issue returns
