### ISSUE TITLE
Only first column renders if it's wider than the viewport

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#9473]
### Description

If the width of the first column is greater than the width of the viewport, Handsontable won't render other columns.

### Steps to reproduce

1. Open the demo at https://jsfiddle.net/9m3jgws1/1/
2. Check if you can reach other columns than `A`

### Your environment
* Handsontable version: 12.0
* Browser name and version: Chrome 101.x
* Operating system: macOS Big Sur

**Comment by aninde** [comment]
Fixed by v12.1.0 https://jsfiddle.net/8j9oruat/

**Comment by AMBudnik** [comment]
I confirm. The following issue is no longer replicable in [Handsontable v12.1.0](https://handsontable.com/docs/release-notes/). I close it as solved.
