### ISSUE TITLE
Having performance issues with Handsontable

### ISSUE THREAD

**Issue by Jonathan-Harrison** [handsontable/handsontable#9478]
**Description**
Hello,

We're having performance issues with Handsontable, and I'm having difficulty tracking down the cause. I initially thought it was an issue with processing the data, but I timed every function we've written and the loading and setting the data seems to only take a second, and it finishes several seconds before the data shows up. I've used performance.now() and console logs to record the time between beforeRender and afterRender, beforeLoadData and afterLoadData, and before and after I call updateSetttings, and I noticed the data takes 3-5 seconds to appear after the logs for afterLoadData, afterRender, and updateSettings appear, and I'm trying to figure out what is being done in the time so that I can try to speed it up.

The time logs I get after refreshing and navigating to the tab with the table are:

> afterLoadData:0.003 seconds
> afterRender:0.05059999999962747 seconds
> afterRender:0.031200000001117587 seconds
> afterRender:0.02890000000037253 seconds
> afterLoadData:0.21130000000074506 seconds
> afterRender:0.228 seconds
> afterRender:0.145 seconds
> updateSettings:0.7628000000007451 seconds

We're using Handsontable with the Vue wrapper, and we're using the columnSorting, filters, hiddenRows, copyPaste, and exportFile plugins. The data I'm testing on is 15 columns with around 3,500 rows. Our init for the table looks like this:
```
  <hot-table
        ref="hot"
        class="table-body"
        stretch-h="all"
        license-key="non-commercial-and-evaluation"
        :settings="hotSettings"/>
  watch: { dataVariableFromDB: { ... this.refs.hot.updateSettings( ... { data: dataFromDb ) }
```

**My environment**
- Vue wrapper version: 11.1.0
- Handsontable version: 11.1.0
- Browser name and version: Chrome (latest)
- Operating system: Ubuntu 20.04.4 LTS (focal)

**Comment by Aiden-FE** [comment]
![企业微信截图_16523470632621](https://user-images.githubusercontent.com/31586885/168036913-ec37de97-7a64-4ec9-ac5c-468b215ba5ac.png)
Me too, this looks bad.

**Comment by AMBudnik** [comment]
Thank you for sharing the investigation results @Jonathan-Harrison and @Aiden-FE 

We have already some connected topics
* `cells()` method use - https://github.com/handsontable/handsontable/issues/5204 
* row / column calculators - https://github.com/handsontable/handsontable/issues/7674
* styles - https://github.com/handsontable/handsontable/issues/4363

You have also mentioned filtering. Before v8.3 it was an issue for the performance (reported at https://github.com/handsontable/handsontable/issues/4352). But after that, we did not see any noticeable changes while enabling/disabling filters.

Did you both tried to test other (older) versions of Handsontable and have you checked the performance guidelines at https://handsontable.com/docs/performance/#overview? 

@Aiden-FE could you share your configuration details and size of the dataset?

**Comment by AMBudnik** [comment]
The `viewportColumnRenderingOffset` and `viewportRowRenderingOffset` have a bigger input when you have fewer cells in the viewport in general. For example when you use `rowHeights` and `colWidths` to expand cells and shink the container with `height`/`width`. Then using `viewportColumnRenderingOffset`/`viewportRowRenderingOffset` will add a few cells within the DOM tree, and they will be rapidly replaced upon scroll. 

I do not think that external CSS settings added to Handsontable can have a larger impact. It's more about adding styling via JS within Handsontable. 

I've asked about the older versions as we generally check each version with the previous one regarding overall performance and some general actions like scroll, selection, and edition via [the Performance Lab](https://github.com/handsontable/performance-lab). But generally, we do not make comparisons with older versions like v12 vs v8. That is why any tips regarding a specific action while skipping a few versions upon update could lead us to some conclusions. 

Well, I have to admit that this seem to be one of those issues that does not have a one single cause. It's more about doing some micro changes in many places (what we already did while introducing [batching](https://handsontable.com/docs/batch-operations/#overview)).

**Comment by Aiden-FE** [comment]
This is an online configuration example, which is so large that the example does not work
