### ISSUE TITLE
License text files contain incorrectly escaped characters

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9487]
### Description

The file `LICENSE.txt` and its derivatives (license text headers in CSS and JS files in `dist`) contain HTML escaped characters instead of quotation marks:

<img width="1260" alt="Screen Shot 2022-05-13 at 11 38 10 AM" src="https://user-images.githubusercontent.com/566463/168256456-1cb6bcb6-06e0-461c-b270-a59ba8e6ef9d.png">

This was introduced in https://github.com/handsontable/handsontable/pull/8917

Affected files are visible on the screenshot:

<img width="601" alt="Screen Shot 2022-05-13 at 11 39 36 AM" src="https://user-images.githubusercontent.com/566463/168256688-5b2e1a92-d375-4c7a-ad26-6a365abe3816.png">

### Steps to reproduce

1. Search for `quot` in the file https://github.com/handsontable/handsontable/blob/develop/LICENSE.txt
2.
3.

**Comment by aninde** [comment]
Fixed in the v12.1.0

**Comment by AMBudnik** [comment]
Solved in Handsontable v12.1.0.
Here you can read the full list of changes https://handsontable.com/docs/release-notes/#_12-1-0.
