### ISSUE TITLE
Unable to use Handsontable in React Typescript sandbox

### ISSUE THREAD

**Issue by emil-eklund** [handsontable/handsontable#9491]
### Description

The following error occurs when trying to use Handsontable in a React *Typescript* sandbox:

```
JSX element class does not support attributes because it does not have a 'props' property.(2607)
'HotTable' cannot be used as a JSX component.
  Its instance type 'HotTable' is not a valid JSX element.
    Type 'HotTable' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.(2786)
```

In local environments, [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop) or [allowSyntheticDefaultImports](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports) seems to solve the issue.
This is annoying to begin with but does not work at all in the Stackblitz Sandbox due to another error occuring when enabled:

```
Error in /turbo_modules/@handsontable/react@12.0.1/dist/react-handsontable.min.js (30:117)
Cannot use import statement outside a module
```

~~Any help is appreciated since this is blocking another bug report. 🥺~~
I was able to create [a working sandbox in Codesandbox](https://codesandbox.io/s/goofy-panini-hekcil?file=/src/App.tsx) instead of Stackblitz. 
Still, I think this should be investigated since I've now encountered it both locally and in sandbox.

### Steps to reproduce
1. [Create a new React Typescript sandbox](https://stackblitz.com/fork/react-ts)
2. [Follow Handsontable React installation Guide](https://handsontable.com/docs/react-simple-example/#examples)
3. Error should be displayed when attempting to use the component.

### Demo
https://stackblitz.com/edit/react-ts-gyus3a?file=App.tsx

### Your environment
* React wrapper version: 12.0.1
* Handsontable version: 12.0.1
* Browser name and version: Microsoft Edge 101 (64 bit)
* Operating system: Microsoft Windows 11 (64 bit)

**Comment by AMBudnik** [comment]
Hi @emil-eklund 

Sorry for keeping you waiting. We should have some investigation updates after the weekend.

**Comment by adrianszymanski89** [comment]
Hi @emil-eklund 

I was investigating your issue and I couldn't reproduce the first error in the local environment. Can you please send as a package with your project where the issue occurs?

And as for the second error, it's almost certainly related to the Stackblitz itself as I found the reports about it on their GitHub issue board.

**Comment by AMBudnik** [comment]
Hi @emil-eklund do we have any updates on the following subject?

**Comment by emil-eklund** [comment]
Hi @AMBudnik,

Apologies for the delay. I have been on holidays and not had the opportunity to respond.
I will try to reproduce it locally. 

In the meantime, @adrianszymanski89 could link to the aforementioned StackBlitz issue so I can track it? :)

**Comment by adrianszymanski89** [comment]
Hi @emil-eklund 

Sure, here's the issue I've mentioned before:

https://github.com/stackblitz/core/issues/1852

**Comment by markwhitfeld** [comment]
Hi there, just for your reference. This issue has been resolved in Stackblitz. There was some faulty logic over the order of precedence in the library we use for processing the `exports` field of a `package.json` file.

**Comment by adrianszymanski89** [comment]
Hi @markwhitfeld 

Thank you for the update! This is excellent news.

@emil-eklund 

Can you please re-check if the issue is resolved on your side?
