### ISSUE TITLE
[12.0.1] stretchH="all" option behaviour

### ISSUE THREAD

**Issue by haraleib** [handsontable/handsontable#9496]
### Description
Handsontable with strechH='all' option, hidden columns and nested headers seems not to work as expected.
_Info: Works with Handsontable V11.1.0_

### Demo

**Example with nestedHeaders (Does not work as expected V12.0.1)**
https://jsfiddle.net/w5pubx19/2/
Columns p and q are streched and column abcdefghijk... is cutted off
![image](https://user-images.githubusercontent.com/19574757/168823502-f8f83994-dab9-4ade-9740-632d2947ba32.png)

**Example with colHeaders (Does work as expected V12.0.1)**
https://jsfiddle.net/23ow8hjs/2/
The column width expands as expected to the width of the column header name for columns q,r,abcdef...
![image](https://user-images.githubusercontent.com/19574757/168826326-86d4758c-4d3b-4d95-82b3-cc71478c0f6c.png)

### Your environment
* Handsontable version: 12.0.1
* Browser name and version: Chrome Version 101.0.4951.54
* Operating system: Windows

**Comment by adrianszymanski89** [comment]
Hi @haraleib 

Thank you for reporting the issue. However, can you please specify what doesn't work as expected in your second example? I can't see the difference between v11.1.0 and v12.0.1

**Comment by haraleib** [comment]
> Hi @haraleib
> 
> Thank you for reporting the issue. However, can you please specify what doesn't work as expected in your second example? I can't see the difference between v11.1.0 and v12.0.1

Done

**Comment by haraleib** [comment]
> Hi @haraleib
> 
> Thank you for reporting the issue. However, can you please specify what doesn't work as expected in your second example? I can't see the difference between v11.1.0 and v12.0.1

Both demos are with v12.0.1. The difference is that in the first demo I use nestedHeaders and in the seconds example I use colheaders.
In v11.1.0 it works with both settings.

**Comment by AMBudnik** [comment]
So I guess that we should alter the title again, @haraleib It is a regression from `12.0.1` not `12.0.0` and it hurts.. we just fixed one regression reported by you but added a new one. I will make sure to pass the info to the planning team.

v12.0.0
https://jsfiddle.net/uLezcx17/
![Zrzut ekranu 2022-05-18 o 10 56 29](https://user-images.githubusercontent.com/10757813/169000163-8e5a69ea-74ad-434a-bc53-e9a592ea2160.png)

v12.0.1
https://jsfiddle.net/yfejzra9/1/
![Zrzut ekranu 2022-05-18 o 10 56 49](https://user-images.githubusercontent.com/10757813/169000198-0275bfac-1c38-4f67-90d9-e2455dba1bac.png)

**Comment by haraleib** [comment]
@AMBudnik Thank you very much :-)

**Comment by aninde** [comment]
Fixed by v12.1.0 https://jsfiddle.net/0bkw4ngd/

**Comment by AMBudnik** [comment]
Hi @haraleib great news! 

We just released Handsontable v12.1.0 where this issue is fixed. Here you can read the full list of changes https://handsontable.com/docs/release-notes/#_12-1-0. 

If you’d have any questions please feel free to let me know.
