### ISSUE TITLE
The content of the comments is not displayed in the documentation

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9497]
### Description

Comments work well in the Handsontable, but there aren't displaying their content in the documentation.

Look at the preview of the [demo](https://handsontable.com/docs/comments/#basic-example).

Demo in the documentation
![Screenshot 2022-05-17 at 19 01 03](https://user-images.githubusercontent.com/30186818/168870295-6420173f-2e1e-4301-9ee5-6f89329becfd.png)

Demo in the jsfiddle
![Screenshot 2022-05-17 at 19 01 34](https://user-images.githubusercontent.com/30186818/168870283-9e4f3d97-fe6f-4819-bf06-d064626042b1.png)

### Links

https://handsontable.com/docs/comments/#basic-example
https://handsontable.com/docs/comments/#make-a-comment-read-only
https://handsontable.com/docs/comments/#set-a-comment-box-s-size
https://handsontable.com/docs/comments/#set-a-delay-for-displaying-comments

### Environment
Browser: Chrome 102.0.5005.49, Safari 15.4 (17613.1.17.1.13)
OS: macOS 12.3.1 (21E258)

**Comment by krzysztofspilka** [comment]
It was a bug in the dark theme only. It's been fixed, thanks for reporting.
