### ISSUE TITLE
On click row header event

### ISSUE THREAD

**Issue by hoandang** [handsontable/handsontable#951]
Are there any events to trigger the click row header then I can collect all the data regarding to that row

**Comment by adube** [comment]
Hello.  I'm looking for this same feature: to be able to listen to column header clicks and by my own callback method.  I'm fine with using the above way to do so, but I wonder: was this officially added ?  I can't find any event looking like "headerClick" from the doc.

Thanks !

**Comment by paribhandari** [comment]
Hi,

Is the onMouseClick handler provided? I am trying to implement a toggle switch inside a cell. The switch moves, however the value of the cell does not change.

**Comment by AMBudnik** [comment]
Hi,

we currently only have the [afterOnCellMouseDown](https://docs.handsontable.com/pro/1.12.0/Hooks.html#event:afterOnCellMouseDown) hook for headers
