### ISSUE TITLE
Vuejs Nested Headers and autocomplete object using

### ISSUE THREAD

**Issue by keksum666** [handsontable/handsontable#9511]
### Description
Good afternoon, I'm using your package and ran into problems:
1) Is it possible to make nestedHeaders work with an array of objects and assign a data-key to each column, as implemented in columns
2) Is it possible to make autocomplete or select work with an array of objects as well? For example: [{ label: "Region1", value: 1 }],

When searching and displaying, the value of the label key will be displayed, and the value of the value key will be written to the data itself

Thanks.

### Steps to reproduce
-----

### Demo
-----

### Your environment
* Vue wrapper version: 2
* Handsontable version: latest
* Browser name and version: Chrome
* Operating system: Ubuntu

**Comment by AMBudnik** [comment]
Hi @keksum666 

the key-value dropdown is not yet available as a built-in functionality. To get it working you'd need to create a custom editor and replace the values shown/saved in the `getValue()`/`setValue()`

Here https://handsontable.com/docs/cell-editor/#overview is a tutorial on the Cell editor. 

When it comes to the `nestedHeaders` there is no way to use an array of objects. But If you need to keep some references you can try to use the metadata. It's just an idea as I do not know how it is used in your project. But if you could share some more details with me at support@handsontable.com I'll do my best to help.
Generally, Github is used to share bugs and feature requests and we do support on the forumand emails.

**Comment by keksum666** [comment]
@AMBudnik Thanks for the answer, I found a bypass of the nested columns restriction, maybe it will be useful to someone (I attached the code below)

I'll try to come up with something with select, thanks for the hint

`
licenseKey: 'non-commercial-and-evaluation',
        manualColumnResize: true,
        width: '100%',
        height: 'auto',
        rowHeaders: true,
        // data: createSpreadsheetData(10, 12),
        columns: [
          {data: 'field_1'},
          {data: 'field_2', type: 'dropdown'},
          {data: 'field_3'},
          {data: 'field_4'},
          {data: 'field_5'},
          {data: 'field_6'},
          {data: 'field_7'},
          {data: 'field_8'},
          {data: 'field_9'},
          {data: 'field_10'},
          {data: 'field_11'},
          {data: 'field_12'},
          {data: 'field_13'},
          {data: 'field_14'},
        ],
        nestedHeaders: [
          [{label: 'field', colspan: 14}],
          [{label: '', colspan: 2}, {
            label: 'field',
            colspan: 4
          }, {label: 'field', colspan: 8}],
          [
            {label: '', colspan: 2},
            {label: 'field', colspan: 3},
            'field',
            {label: 'field, colspan: 3},
            'field',
            {
              label: 'field',
              colspan: 3
            },
            'field',
          ],
          [
            'field',
            'field',
            'field',
            'field',
            'field',
            'field',
            'filed',
            'field',
            'field',
            'field',
            'field',
            'field',
            'field',
            'field',
          ]
        ]
      }
`

**Comment by AMBudnik** [comment]
Thank you for the update. I'm closing this issue as solved. But interested developer will still be able to find it in the browser.
