### ISSUE TITLE
Docs: Corrections for the React transformations in the documentation.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#9516]
### Description
Some of the automatically transformed snippets/examples in the React "flavor" of the documentation aren't working properly.

- Some of the examples/snippets will need to be reorganized for the snippet transformer to process them correctly, 
- Some will need to be manually rewritten for vanilla/react versions.
- The transformer will most probably need to be extended to create code with a more "native" react feel.

Information about the incomplete examples is tracked here: [Google Spreadsheet](https://docs.google.com/spreadsheets/d/15q2Bv4UCIoXLktZDDqSTupTLSSO0BWvoxfJbeUbCauU/edit#gid=0).

Part of #9441.

**Comment by warpech** [comment]
Closing as the automatic transformer was ditched. Thank you @jansiegel for the work nonetheless, I am happy that we used  the result of the transformer.
