### ISSUE TITLE
Scroll to Selected Cell (horizontal)

### ISSUE THREAD

**Issue by nyrd** [handsontable/handsontable#952]
I've encountered an Issue where using the select cell method along with the "scroll-to" property produces unexpected results. (After a few times, the scroll-to becomes erratic and no longer reliably scrolls to selected cell).

On the following demo, if you start with col A selected, then keep clicking the "Select one cell to the right" button, it will work until you get to Col I and then break down.

http://jsfiddle.net/2f3Ym/4/

**Comment by AMBudnik** [comment]
Demo does not work anymore. If you would have similar issue with current handsontable version feel free to open new issue.
