### ISSUE TITLE
manualRowMove issue with overflow: all 

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9556]
### Description

When we have Handsontable container inside another div that has a specified height, and the viewport height is lower than said div with the manualRowMove option enabled we can't move any row lower than the one before the last one.

### Steps to reproduce

1. Setup viewport height lower than specified parent div height;
2. Try to move any row to the last position;

![Kapture 2022-06-02 at 15 25 08](https://user-images.githubusercontent.com/92314130/171640022-49d068cc-3be6-4aad-a860-9c011308e678.gif)

### Demo

https://jsfiddle.net/3v6mzLr5/10/

### Your environment
* Handsontable version: 12.0.0
* Browser name and version: Google Chrome 101
* Operating system: MacOS Monterey 12.3.1

Inform [forum](https://forum.handsontable.com/t/row-move-functionality-works-incorrect/6179/2)

**Comment by AMBudnik** [comment]
Released in v12.4.0
