### ISSUE TITLE
[11.0.0+] dropdownMenu open() method with filtering

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9561]
### Description

It seems that there's a regression regarding `open()` method for dropdownMenu with the filters option turned on and it was introduced in Handsontable 11.0.0. Since that version opening `dropdownMenu` using that method throws an error:

`Uncaught TypeError: Cannot read properties of null (reading **'visualIndex')`**

### Steps to reproduce

1. Open the demo
2. See the console for error

### Demo

Case 1, v. 10.0.0 (works fine): https://jsfiddle.net/aszymanski/sz1j920L/4/
Case 2,  v. 11.0.0 (doesn't work): https://jsfiddle.net/aszymanski/sz1j920L/3/

### Your environment

* Handsontable version: 11 and 12
* Browser name and version: Google Chrome 101
* Operating system: MacOS Monterey 12.3.1

**Comment by adrianszymanski89** [comment]
Inform [Forum](https://forum.handsontable.com/t/dropdown-menu-open-method-question/6180/2)

**Comment by warpech** [comment]
This was solved in #9829 with a breaking API change. A new PR will be made to revert to the previous API

**Comment by aninde** [comment]
This issue will be fixed by the upcoming v12.1.3 https://jsfiddle.net/p5n6y43k/

**Comment by AMBudnik** [comment]
I'm closing this issue as fixed in Handsontable v12.1.3.
