### ISSUE TITLE
clear_column in context menu send ContextMenu.clearColumn as src

### ISSUE THREAD

**Issue by ichalyshev** [handsontable/handsontable#9566]
I am using typescript, and I have clear_column in context menu. If I select whole column and run "Clear column" in my afterChange handler i receive src='ContextMenu.clearColumn' not 'ContextMenu.clearColumn**_s_**' There is no 'ContextMenu.clearColumn' in ChangeSource type.

export type ChangeSource = 'auto' | 'edit' | 'loadData' | 'populateFromArray' | 'spliceCol' |
                           'spliceRow' | 'timeValidate' | 'dateValidate' | 'validateCells' |
                           'Autofill.fill' | 'ContextMenu.clearColumns' | 'ContextMenu.columnLeft' |
                           'ContextMenu.columnRight' | 'ContextMenu.removeColumn' |
                           'ContextMenu.removeRow' | 'ContextMenu.rowAbove' | 'ContextMenu.rowBelow' |
                           'CopyPaste.paste' | 'UndoRedo.redo' | 'UndoRedo.undo' | 'ColumnSummary.set' |
                           'ColumnSummary.reset';

"typescript": "3.8"
"@handsontable/react": "^12.0.1",
"handsontable": "^12.0.1",

**Comment by AMBudnik** [comment]
Hi @ichalyshev 

I just wanted to let you know that we just released Handsontable v13.1.0 where this issue is fixed.

Again, thank you for reporting.
