### ISSUE TITLE
Split documentation build and deploy process

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9570]
### Motivation
We discussed the pros and cons with the team that the documentation for all Handsontable versions is on the same branch (develop) and is always rebuilt for all versions based on a common VuePress configuration. This leads to a large number of workarounds to support old and new Handsontable versions simultaneously. It slows down the development of the engine for new versions of the documentation, and each new version extends the long process of building and deploying documentation online.

### Proposed solution
Change the monorepo architecture so that on each branch, there is only the current version documentation for that branch. There will be only the `docs/next` directory that contains the content for the version of the specified docs. 

Changes to the content of previous versions of the documentation would be made through specially created branches on Git (e.q. `docs/11.0`, `docs/12.0`). For each version of MAJOR.MINOR, Handsontable would have a branch containing the documentation for that version. Documentation from this branch would go to the production environment in the form of a Docker image. So we would have as many branches and tags in Docker as we have different MAJOR.MINOR versions.

[This approach](https://github.com/handsontable/docs/branches) was already used in the previous docs engine.

[Versioned examples](https://github.com/handsontable/handsontable/tree/develop/examples) that share the same architecture as current docs would disappear with this project. There would be only the `examples/next` directory that contains the content for the version of the released or upcoming Handsontable version. 

#### Pros
 * More simplified VuePress configuration file (without magic env variables like `DOCS_VERSION` and more);
 * Simpler content directory structure. There will be only the `docs/next` and `examples/next` directory;
 * Constant build and deploy time;
 * Easier to rebuild, regenerate docs from source code and redeploy for older versions;
 * Much less docs files duplication (`.md` files); 
 * In terms of Examples, much less vulnerabilities alerts;

#### Cons
 * Fixing a bug, adding functionality, or changing UI for several docs versions would require more effort from the developer (multiple PRs, cherry-picking);

#### General things to do
 * Create separate branches for docs 9.0...12.0 versions;
 * Move specific docs version content and examples to the `next` directory;
 * Add logic that would gather information from GitHub API about the list of available docs versions and/or the latest version (probably needed for redirects such as `/docs/some` -> `docs/12.0/some`);
 * Update Docker images build process for separate docs directory (use new/or existing GH workflow) + update staging env;
 * Update freeze/release scripts to support the new process; 

#### Phase 1: Create working Docker image for 9.0 docs version
 * Create on ~the main repo~ forked repo based on the 9.0.0 release tag `docs/9.0` branch, remove all not related `md` files, update content for 9.0 from develop branch (SEO fixes and more) and implement all the necessary things to be able to build and deploy the image to the staging;
 * Add a script that reads the branches from the GitHub API. It's necessary for detecting the latest docs version;
 * Make sure that `watch`, `build`, and automatic Docker build scripts, and GH workflow works as expected;
 * Update configuration for the staging and test the changes there;
#### Phase 2: Applying the changes to all docs versions
 * On ~the main repo~ forked repo, apply all the changes from Phase 1. Create branches for all already released docs;
 * Update configuration for the staging and test the changes there;
#### Phase 3: Adjust freeze/release and examples scripts
 * On the forked repo, add support for the split docs architecture and test the freeze, release and examples scripts;

#### Current release process
```mermaid
%%{init: { 'theme': 'base', 'gitGraph': {'mainBranchName': 'master'}} }%%
    gitGraph
       commit type: HIGHLIGHT tag:"11.0.0"
       branch develop
       commit
       commit
       commit
       branch release/12.0.0
       commit id:"Generate all docs versions, examples, HoT build"
       checkout master
       merge release/12.0.0
       commit type: HIGHLIGHT tag:"12.0.0"
       checkout develop
       merge master
```
#### Proposed process
```mermaid
%%{init: { 'theme': 'base', 'gitGraph': {'mainBranchName': 'master'}} }%%
    gitGraph
       commit type: HIGHLIGHT tag:"11.0.0"
       branch develop
       commit
       commit
       commit
       branch release/12.0.0
       commit id:"Generate docs for 12.0.0, examples, HoT build"
       checkout master
       merge release/12.0.0
       commit type: HIGHLIGHT tag:"12.0.0"
       checkout develop
       merge master
       branch docs/12.0
       merge master
       checkout develop
       commit
       commit
       commit
       branch release/13.0.0
       commit id:"Generate docs for 13.0.0, examples, HoT build"
       checkout master
       merge release/13.0.0
       commit type: HIGHLIGHT tag:"13.0.0"
       checkout develop
       merge master
       branch docs/13.0
       merge master
```

**Comment by warpech** [comment]
Closing as done in #9651
