### ISSUE TITLE
Move `@angular/core` dependency to peer dependencies

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9574]
### Description

The issue is about moving the `@angular/core` Angular wrapper dependency to peer dependencies (or dev dependencies). Then, add new tests as new examples for the Angular 9 to 14.

**Comment by AMBudnik** [comment]
Issue closed as [solved](https://github.com/handsontable/handsontable/blob/develop/wrappers/angular/package.json#L58) in [Handsontable v12.1.0](https://handsontable.com/docs/release-notes/).

**Comment by warpech** [comment]
There is a regression caused by this change, which we are tracking in #9622
