### ISSUE TITLE
poor performance about mergeCells

### ISSUE THREAD

**Issue by itwebwjl** [handsontable/handsontable#9579]
### Description
Poor performance using the merge cell plug-in

### Steps to reproduce
Poor performance using the merge cell plug-in

### Demo
none 
### Your environment
* Handsontable version: 6.2.2
* Browser name and version: laster
* Operating system: mac m1

**Comment by adrianszymanski89** [comment]
Hi @itwebwjl 

Thank you for reporting the issue, but we will need more information. What are your settings? Do you use frameworks? The example also would be helpful.

**Comment by AMBudnik** [comment]
I think that it might be related to one of those issues https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Merge+cells%22+label%3A%22Core%3A+performance%22 
But without any details, it's hard to say.

**Comment by itwebwjl** [comment]
https://github.com/handsontable/handsontable/issues/5687
<img width="972" alt="Snipaste_2022-06-14_22-03-06" src="https://user-images.githubusercontent.com/47092916/173596693-d871ac1a-11c3-4ed7-a6ff-4a3d98d7ec45.png">

**Comment by itwebwjl** [comment]
My current version
"handsontable": "6.2.2",
"@handsontable/vue": "3.1.0",

Without updating the version, can you optimize the number of times the merged cells trigger the "renderer" hook?
Thank you very much for your reply

**Comment by adrianszymanski89** [comment]
Hi @itwebwjl 

Unfortunately, there is no way to do this in versions prior to one when batch operations were introduced.

**Comment by PH8919** [comment]
@adrianszymanski89 
Hi, guy
I am evaluating the handontable and i found the performance for merging cells decrease sharply from v12.0.0. below is my evaluation code:
`function generateData() {
  let _data = [];
  let _mergeData = [];
  for (let i = 0; i < 10000; i++) {
    let _i = i / 5;
    if (i % 5 == 0) {
      _mergeData.push({ row: i, col: 0, rowspan: 5, colspan: 1 });
      _mergeData.push({ row: i, col: 3, rowspan: 5, colspan: 1 });
    }
    _data.push([`A${_i}`,`B${i}`,`C${i}`,`E${i}`,`E${i}`, `A1${i}`, `B1${i}`, `C1${i}`, `E1${i}`,`E1${i}`,`A${i}`, `B${i}`, `C${i}`,`E${i}`,`E${i}`,`A1${i}`,`B1${i}`,`C1${i}`,`E1${i}`,`E1${i}`,]);
  }
  return { data: _data, mergeData: _mergeData };
}

    let _ret = generateData();
    var container = document.getElementById("example");
    console.time("ABC");
    var hot = new Handsontable(container, {
      data: _ret.data,
      rowHeaders: true,
      colHeaders: true,
      colWidths:[80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80],
      filters: true,
      width: "100%",
      height: "100%",
      licenseKey: "non-commercial-and-evaluation",
      mergeCells: _ret.mergeData,
    });
    console.timeEnd("ABC");`
