### ISSUE TITLE
Progress and Rating columns should be editable in the main demo

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#9581]
### Description

I would expect that cells in columns "Progress" and "Rating" are editable.

- Progress: cell editor - numeric in the range 0-100. If beyond the range, set the edge value (minimum or maximum) and close the editor.
- Rating: cell editor - numeric in the range 0-5. If beyond the range, set the edge value (minimum or maximum) and close the editor.

<img width="228" alt="Screenshot 2022-06-14 at 15 49 23" src="https://user-images.githubusercontent.com/8048526/173593724-2ac8c520-46df-4407-afd3-0e9f74c62e6c.png">

### Links

https://handsontable.com/docs/demo/

**Comment by warpech** [comment]
As part of this issue:
1. the data source should be changed from an array of arrays to an array of objects
2. the source code should be improved to follow the current best practices for a given framework (if now something strikes as odd)

**Comment by warpech** [comment]
This should be done as 1 framework = 1 pull request, starting from React.

**Comment by krzysztofspilka** [comment]
[PR](https://github.com/handsontable/handsontable/pull/9935) to be finished.

**Comment by AMBudnik** [comment]
This issue is no longer applicable.
