### ISSUE TITLE
how do I copy  ## data from excel? 

### ISSUE THREAD

**Issue by fenrir-liutiecheng** [handsontable/handsontable#9597]
### Description
I want to not show ### but 1000 after selecting cells to paste, how to do it？

### Steps to reproduce

1. Enter 1000 on the Excel sheet.
<img width="542" alt="image" src="https://user-images.githubusercontent.com/57246526/174928239-a6036729-cab4-4090-963c-af00645b9374.png">

2.The cell is shortened, 1000 becomes ###, then copy.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/57246526/174928391-2382c6c3-85a8-4247-a489-4b94202c434b.png">

3.Select the cell of the handsontable and paste it directly, the display is ### (line 3). After double-clicking the cell and pasting, it shows 1000 (row 4).
<img width="271" alt="image" src="https://user-images.githubusercontent.com/57246526/174929597-0dd70ef1-67ac-4064-890f-17b7c6bf5e2d.png">

**Comment by adrianszymanski89** [comment]
Hi @fenrir-liutiecheng 

Can you please tell me what your Handsontable settings object looks like and which version you use?

I tested it following your step on the newest version of Handsontable in this example and I get the correct number instead of ### right away.

https://jsfiddle.net/aszymanski/gptvczrh/

**Comment by fenrir-liutiecheng** [comment]
My Handsontable version is 11.1.0.
setting is:

    const hotSettings: GridSettings = useDeepMemo(
      () => ({
        dataSchema: dataSchema,
        nestedHeaders: sizeChartHeaderData,
        colWidths: colWidths,
        columns: columns,
        hiddenColumns: {
          columns: [0],
        },
        readOnly: !locked,
        rowHeaders: true,
        colHeaders: true,
        width: 'auto',
        height: '272px',
        filters: false,
        trimWhitespace: false,
        selectionMode: 'range' as 'range' | 'single' | 'multiple' | undefined,
        multiColumnSorting: true,
        fixedColumnsLeft: 1,
        dropdownMenu: false,
        trimRows: true,
        comments: true,
        licenseKey: 'non-commercial-and-evaluation',
        minSpareRows: 1,
        minRows: 10,
        contextMenu: !locked
          ? false
          : {
              items: {
                row_above: {
                  name: '行を上に挿入',
                },
                row_below: {
                  name: '行を下に挿入',
                },
                remove_row: {
                  name: '行を削除',
                },
              },
            },
        afterGetRowHeader: function (row: number, TH: HTMLTableHeaderCellElement) {
          TH.className = 'lhead';
        },
        afterGetColHeader: function (i: number, TH: HTMLTableCellElement) {
          const el = TH.querySelector('.sizeInfo') || undefined;
          if (el instanceof HTMLInputElement) {
            el.addEventListener('change', onSelectSize);
          }
        },
        afterRenderer(TD, row, column, prop, value, cellProperties) {
          // clean comment
          if (
            !value &&
            TD.classList.contains('htCommentCell') &&
            !TD.classList.contains('htInvalid')
          ) {
            const instance = this as unknown as Handsontable;
            const commentsPlugin = instance.getPlugin('comments');
            commentsPlugin.removeCommentAtCell(row, column);
          }
        },
        afterChange(changes, source) {
          if (changes && (source === 'edit' || source === 'CopyPaste.paste')) {
            handleChange(changes);
          }
        },
        afterValidate(isValid, value, row, prop) {
          const instance = this as unknown as Handsontable;
          if (instance) {
            const col = instance.propToCol(prop);
            const commentsPlugin = instance.getPlugin('comments');
            let message = '';
            if (isValid) {
              commentsPlugin?.removeCommentAtCell(row, col, false);
            } else {
              const metaData = instance.getCellMeta(row, col);
              const pattern = metaData.numericFormat?.pattern;
              // not blank
              if (!value) {
                message = t('ERIN01001', { ns: 'message' });
              } else if (metaData.dataType === 'number' && !Number(value)) {
                // number valid
                if (pattern && (pattern as string).indexOf('.') !== -1) {
                  message = t('ERIN03002', { ns: 'message' });
                } else {
                  message = t('ERIN03001', { ns: 'message' });
                }
              } else if (
                metaData.dataType === 'number' &&
                (!pattern || (pattern && (pattern as string).indexOf('.') === -1)) &&
                value.toString().indexOf('.') !== -1
              ) {
                // not double number
                message = t('ERIN03001', { ns: 'message' });
              } else {
                // length valid
                const maxLength = metaData.maxLength;
                if (maxLength) {
                  message = t('ERIN02001', { ns: 'message' }).replace('%1s', maxLength as string);
                }
              }
              console.log(message);
              commentsPlugin.setCommentAtCell(row, col, message);
              commentsPlugin.updateCommentMeta(row, col, { readOnly: true });
            }
          }
        },
      }),
      [locked, onSelectSize, masterSizeId],
    );

**Comment by fenrir-liutiecheng** [comment]
@adrianszymanski89 

Thank you very much for your example, but when I copy and paste, it still appears ###。
<img width="1553" alt="image" src="https://user-images.githubusercontent.com/57246526/175452494-160da2c2-aa69-45bd-b824-d58b7c6dd6e5.png">

**Comment by adrianszymanski89** [comment]
Hi @fenrir-liutiecheng 

Let's clear out a few more things. What are your browser and operating system?

**Comment by fenrir-liutiecheng** [comment]
@adrianszymanski89 
browser:  chrome( version is 102.0.5005.115, x86_64)
os: MacOS Catalina 10.15.7

**Comment by adrianszymanski89** [comment]
Hi @fenrir-liutiecheng 

Sorry for the late response. We finally managed to reproduce the issue. It turned out that the reason for this is that our internal `CopyPaste` plugin copies and cuts data as a text/plain and a text/html MIME-type.

So, the only workaround for that is what you described in your first message - double-clicking on the cell and then pasting the value.

**Comment by adrianszymanski89** [comment]
Hi @fenrir-liutiecheng 

I did a re-check of this issue with v. 14.4.0, and I can no longer reproduce it. Can you please check this example and confirm?https://jsfiddle.net/handsoncode/aq8g3xhp/
