### ISSUE TITLE
[12.1.0] Cannot scroll horizontally with the RTL mode when height: 'auto'

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9602]
### Description

It's impossible to scroll it horizontally when `layoutDirection: 'rtl'` and Handsontable is set with height: 'auto'.
No horizontal scroll bars appear.  After clicking selection and moving it to the left, the viewport is not moving.

### Steps to reproduce

1. Open a demo and make viewport smaller.
2. Try to scroll the demo vertically
3. Select cell E1 and move selection to the left by the left arrow

**Actual result**
![Kapture 2022-06-22 at 18 21 11](https://user-images.githubusercontent.com/30186818/175084542-6bb34768-f03a-42ca-9b3b-17579bd82909.gif)

**Expected result**
![Kapture 2022-06-22 at 18 22 03](https://user-images.githubusercontent.com/30186818/175084574-9d69fa6e-fedd-45bb-abd6-e67b2eba796f.gif)

### Demo

https://jsfiddle.net/r15w62tm/ v12.1.0 broken
https://jsfiddle.net/2cp5nqfw/ v12.0.1 fixed

https://jsfiddle.net/p6jL4a85/1/ v12.1.0 with sizes - fixed

[Documetation demo](https://handsontable.com/docs/layout-direction/#rtl-support) 
https://jsfiddle.net/8mpuc3e7/  v12.1.0 broken
https://jsfiddle.net/q4so8fck/ v12.0.1 fixed

### Your environment
* Handsontable version: 12.1.0 040dc6302987a38d232dc3ccc953bf73f10fb9fb
* Browser name and version: Chrome 102.0.5005.115, Safari 15.5 (17613.2.7.1.8), Safari on iOS
* Operating system: macOS 12.4 (21F79), iOS

**Comment by krzysztofspilka** [comment]
Regarding future development: https://bit.ly/3nchKcA

**Comment by aninde** [comment]
Fixed by  dfe871d439820098d29f85ae095c032a31ad3eaa https://jsfiddle.net/q7L5t39o/.
