### ISSUE TITLE
Undo produces error after any prop update (only with hyperformula)

### ISSUE THREAD

**Issue by olosegres** [handsontable/handsontable#9613]
### Description
Hello, at Actonic we use this plugin with hyperformula. Recently has been moved to react version and stumbled upon a bug.
Undo operation produces error `There is no operation to undo` if any prop has been updated right after historical action.
```
CrudOperations.undo
https://wxvqlc.csb.app/node_modules/hyperformula/es/CrudOperations.js:501:15
HyperFormula.undo
https://wxvqlc.csb.app/node_modules/hyperformula/es/HyperFormula.js:325:28
Core.eval
https://wxvqlc.csb.app/node_modules/handsontable/plugins/formulas/formulas.mjs:443:23
fastCall
https://wxvqlc.csb.app/node_modules/handsontable/helpers/function.mjs:177:17
Hooks.run
https://wxvqlc.csb.app/node_modules/handsontable/pluginHooks.mjs:194:59
Core.runHooks
https://wxvqlc.csb.app/node_modules/handsontable/core.mjs:2105:46
UndoRedo.undo
```
From what I understand, it clears Hyperformula's internal crudOperations after any update of the HotTable.
So the undoRedo stack for hansontable and hyperformula is out of sync (redo is available in handsontable but doesn't work due to hyperformula)

### Steps to reproduce

1. Enable forumals
2. Make any prop to update after column creation
3. Create column
4. Press Command+Z

### Demo
https://codesandbox.io/s/upbeat-bush-wxvqlc

### Your environment
* React wrapper version: 18
* Handsontable version: 12.1
* Browser name and version: Chrome 103, Firefox
* Operating system: macos, linux

**Comment by adrianszymanski89** [comment]
Hi @olosegres 

Thank you for reporting this. It looks to me like the issue is connected to the state manager, which is weird as we addressed that problem in the latest releases. I'll have to dig a little bit deeper to see what's exactly going on here and get back to you after the weekend.

**Comment by adrianszymanski89** [comment]
Hi @olosegres 

I have investigated your issue further, but I didn't find related to the configuration, so the problem must lie deeper. I added needed labels so our developers will be able to work on that when this issue will appear on our roadmap.

**Comment by olosegres** [comment]
Any updates? It is very annoying issue :(

**Comment by adrianszymanski89** [comment]
Hi @olosegres 

I reinvestigated the issue to see if I can find some workaround for now. I managed actually to find one. The problem lies within `useCallback` hook, I'm not sure what is causing this issue for now, but instead, you can use `useMemo` hook, and then everything works correctly. We will further investigate the problem with the usage of `useCallback` hook, so I will keep you updated on this matter.

**Comment by adrianszymanski89** [comment]
Hi @olosegres 

We re-checked this issue as we are currently working on improving our React experience, and we discovered that it lies within our React wrapper. To be more precise, it's occurring because Handsontable is re-initialized each time when the props are updated. We will keep working on improving our React wrapper, so I'll update you when we get to that point.

**Comment by olosegres** [comment]
Hi @adrianszymanski89 

Ok, thanks. 

We could't find a workaround for this bug in some cases, f.e. when updating objects (mergeCells prop).

So we had to fork hyperformula and made little changes.
https://bitbucket.org/actonic/hyperformula/commits/b4119ce2ba0c0642cc4f4e9c1755dedabe6c2fca

I do not know is it right way to fix this problem. 
But it seems like plugin shouldn't treat its own empty undoRedo stack as error.

Let us know is it valid fix and you would like to merge such PR.

**Comment by adrianszymanski89** [comment]
Hi @olosegres 

Thank you for that. I'll propose it to our development team, and then we decide. I'll update you.

**Comment by aroth** [comment]
Also effected by this bug. Please advise as to the internal progress.

**Comment by AMBudnik** [comment]
Note to myself: update [topic](https://forum.handsontable.com/t/extending-undoredo-plugin-seeking-advice-best-practices/6546/6)

**Comment by aninde** [comment]
Hi, @olosegres. I'm currently testing the upcoming version 12.4.0, which addresses the reported issue. I have thoroughly examined the demo using the upgraded versions of Handsontable (12.4.0) and HyperFormula (v2.4.0), and I can confirm that there are no problems observed when undoing column insertions. To validate this, I have prepared a [working demo](https://codesandbox.io/s/naughty-yonath-zinv9b) for your reference.
