### ISSUE TITLE
[12.1.0] Installation of Angular wrapper 12.1.0 fails for versions of Angular other than 9 (workaround instruction)

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9622]
The newest package `@handsontable/angular@12.1.0` imposes an incorrect dependency on Angular 9, which will probably mean that it fails to install with your setup of Angular.

We will issue a patch release very soon. 

### Workaround instruction

Meanwhile, if you are using Angular version other than 9, please install the following combination of dependencies in your apps:

- `@handsontable/angular@12.0.1` - the last working version of the Angular wrapper as of today
- `handsontable@12.1.0` - the newest version of Handsontable core as of today

The above combination will give you the set of features of Handsontable 12.1.0 with the correctly installing wrapper of Handsontable 12.0.1.

We are sorry for inconvenience.

**Comment by AMBudnik** [comment]
Note to myself: inform [ZEN](https://handsontable.zendesk.com/agent/tickets/29554)

**Comment by aninde** [comment]
Tested with examples of Angular 9, 10, 11, 12 and 12. Each installed with private npm registry.

**Comment by AMBudnik** [comment]
Issue closed as fixed in Handsontable 12.1.1. Here is the full list of changes https://handsontable.com/docs/release-notes/#_12-1-1 for that given version.
