### ISSUE TITLE
Custom HTML dropdown in handsontable

### ISSUE THREAD

**Issue by goodmite** [handsontable/handsontable#9628]
### Description

I am aware Handsontable has a [cell type for dropdown](https://handsontable.com/docs/dropdown-cell-type/#overview) but I want a more customizable dropdown where I can put images/chips/text. Please see the screenshot below.

Is something like that possible in handsontable?

![](https://i.stack.imgur.com/Ifzmy.png)

**Comment by AMBudnik** [comment]
I've posted my reply on SO, but I can also paste it here

If that image/HTML element should only be visible within the cell when the editor is closed you can use a custom renderer. Then you define a cell as a default dropdown (with your source) and add a cell renderer

```
function firstRowRenderer(instance, td, row, col, prop, value, cellProperties) {
  Handsontable.renderers.DropdownRenderer.apply(this, arguments);
  td.innerHTM = `${value} ${here put your HTML element}`
}
```
And if you'd need those images/HTML elements within the list of choices then it might be easier to switch to the handsontable cell type. Then the implementation would look like this

```
{
      data: data_key/array index,
      type: 'handsontable',
      handsontable: {
        colWidths: 100, //some settings (works the same as regular table)
        data: myItems, //list of choices
        renderer: function(instance, td, row, col, prop, value){
            Handsontable.renderers.TextRenderer.apply(this, arguments);
            td.innerHTML = `${your custom HTML} ${value}`
        }
      }
}
```
