### ISSUE TITLE
Cannot dynamically add columns to HotTable after creation in Vue

### ISSUE THREAD

**Issue by JAlbert2** [handsontable/handsontable#9641]
### Description
I have a site with multiple different options for tables. The Hot-Table instance reminds the same, but the data is dynamically changed with a drop down menu. One table has 5 columns, and the other has the same 5 columns with two extra in the middle. When I switch from the 5 table to 7 table, the column headers are renamed, but the two extra columns do not appear. 

### Steps to reproduce

1. Vue HTML Code`<hot-table ref="hotTable" :settings="spreadsheetSettings" v-if="showTable">`
2. Vue JS Code `spreadsheetSettings: {
        licenseKey: 'hidden',
        rowHeaders: true,
        contextMenu: true,
        bindRowsWithHeaders: true,
        nestedRows: true,
        autoRowSize: false,
        autoColumnSize: false,
        height: '100%',
        data: [{}],
        stretchH: 'all',
        minSpareRows: 0,
        hiddenColumns: {
          columns: [0],
          indicators: false
        }
      },
      colHeaders: ['Is Variation', 'Category', 'Item Name', 'SKU', 'Total Quantity in Stock', 'Manage Stock', 'Add Variation', 'Edit Item'],`
3.colHeaders can have more headers added in between SKU and Total Quantity in Stock. Manage Stock, Add Variation, Edit Item are all buttons
4. Example data
data1: [{category: "Uncategorized", name: "Butter SS", sku: "But-ss", quantity: "$3.69", isVariation: false}]
colHeaders1: ['Is Variation', 'Category', 'Item Name', 'SKU', 'Total Quantity in Stock', 'Manage Stock', 'Add Variation', 'Edit Item']
data2: [{category: "Accessories", name: "Wristband", sku: "ACC-BND", quantity: 2, isVariation: false, cost: "5", sale_price: "5"}]
colHeaders2: ['Is Variation', 'Category', 'Item Name', 'SKU', 'Sale price', 'Cost', 'Total Quantity in Stock', 'Manage Stock', 'Add Variation', 'Edit Item']
5. Code used to update data 
`this.$nextTick(() => {
          this.$refs.hotTable.hotInstance.updateSettings({
            data: result,
            colHeaders: this.colHeaders
          })
        })`
result is the data changing

### Demo
Cannot reproduce on provided platforms since it is Vue code.

### Your environment
* Vue wrapper version: ^2.6.14
* Handsontable version: ^11.0.1
* Browser name and version: Safari & Chrome, Latest versions
* Operating system: Mac

**Comment by adrianszymanski89** [comment]
Hi @JAlbert2 

Thank you for reporting the issue. I tried to recreate your issue here based on the settings and data you provided, but it seems that still, some code is missing. Can you please update this example to the point where the issue is replicable?

https://jsfiddle.net/aszymanski/yzp2L1rc/1/

**Comment by JAlbert2** [comment]
It's a bit of a hack together from the larger source code, but I have a Zip file with a default Vue/Nuxt app that shows the error.
[Hot.zip](https://github.com/handsontable/handsontable/files/9074182/Hot.zip)
I don't know why the table is showing up twice, but one of the tables can be deleted from the source in the browser.

**Comment by adrianszymanski89** [comment]
Hi @JAlbert2 

Thank you for the code. Now it's clear to me that your issue is exactly the same as this one: https://github.com/handsontable/handsontable/issues/7544

So, unfortunately, at the moment it's not possible to do this.
