### ISSUE TITLE
@handsontable/vue v12.1.2 error in types.d.ts prevents compile

### ISSUE THREAD

**Issue by Deracination** [handsontable/handsontable#9647]
@handsontable/vue: 12.1.2
typescript: 4.7.4

```

@handsontable/vue/types.d.ts
58:71 'Handsontable' has no exported member named '_editors'. Did you mean 'editors'?
    56 | export interface BaseVueEditorMethods extends ClassMethods<Handsontable._editors.Base> {
    57 | }
  > 58 | export interface BaseVueEditorFields extends ClassFields<Handsontable._editors.Base> {
       |                                                                       ^
    59 | }
    60 | export {};
    61 |
```

work-around for now by deleting lines 56-59 from types.d.ts

**Comment by AMBudnik** [comment]
Hi @Deracination 

Sorry for such a delay. At first glance, the proposition looks good, but it works like this is the simplest test that we performed. Could you please point out how to replicate the issue to get the error?

**Comment by AMBudnik** [comment]
Hey @Deracination 
I need to close this report as there is no further feedback on how to replicate the issue.
If there's anything that can help us to replicate the case please share in the comment.
