### ISSUE TITLE
`npm run docs:start` doesn't work when there are docs versions newer than `12.0`

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#9650]
Steps to replicate:
1. Make sure you're on the `feature/react-docs` branch, and update it locally.
2. Run `npm run docs:version`, to create any new docs version (e.g. `12.1`).
3. After the new version is created, run `DOCS_FRAMEWORK=react npm run docs:start` (or any other `npm run docs:start` script).

The result:
<img width="789" alt="1" src="https://user-images.githubusercontent.com/29247866/178678294-1c3ad087-0e5a-4ae8-9687-ed51f900e405.png">

**Comment by warpech** [comment]
Closing as done
