### ISSUE TITLE
IME: The パ char is replaced by pあ in a `dropdown` cell type

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9672]
### Description

The following issue is not replicable on macOS.

Usually, in the case of Romaji input, when you click "p", it is not confirmed, and when you click "a", "ぱ" is displayed. But in some cases, like here with the dropdown, we get a different value

### Steps to reproduce

1. Download Katakana-Romaji keyboard and switch to it
2. Go to https://jsfiddle.net/d8pej0kv/
3. Use the following keys slowly to observe the result. Click <kbd>p</kbd> on your keyboard. Then click <kbd>a</kbd> on your keyboard.

**Expected result**
Content in the cell is: `パ`

**Actual result**
Content is the cell is: `pあ`

**Reproduction**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/10757813/179162638-2d6020ed-ac12-4608-abb1-5ca989176641.gif)

### Demo

https://jsfiddle.net/d8pej0kv/

### Your environment
* Handsontable version: 12.1.2
* Browser name and version: Edge
* Operating system: Windows 10

Inform [ZEN](https://handsontable.zendesk.com/agent/tickets/29591), [Zen](https://handsontable.zendesk.com/agent/tickets/30233)

**Comment by budnix** [comment]
I'm not able to reproduce the bug. I tested on Win 10, and 11 with the latest Edge (107) and mentioned words `p`, and `a` are always replaced as `ぱ` which I guess is an expected result.

**Comment by aninde** [comment]
I can't reproduce it either. On my Edge 107.0.1418.56 / Windows 10 after typing `p + a` with Hiragana set as typing language I received `せち`, with Katana `セチ`. 
<img width="362" alt="Screenshot 2022-11-22 at 13 26 11" src="https://user-images.githubusercontent.com/30186818/203316171-044c5b97-fe7c-4190-9f24-bf4a7b02df85.png">
<img width="334" alt="Screenshot 2022-11-22 at 13 25 48" src="https://user-images.githubusercontent.com/30186818/203316199-8643752d-047e-4345-bafa-29aaf682f39b.png">

I can't `パ` char on anywhere Edge on Windows by typing `p + a` and pressing SPACe, but it's not related to the Handsontable, but to the browser and OS, cause I can do that on macOS.

**Comment by AMBudnik** [comment]
@Serrrek89 I will put it on-hold (pushing to the `Icebox` on ZH) and ask those two users who reported the issue for feedback.

**Comment by AMBudnik** [comment]
Issue marked an `On-hold` @Serrrek89 
I asked for more feedback from users who reported this issue.

**Comment by ogura3106** [comment]
Condition 1: Use romaji input.
"ちせ" is Kana input. Romaji input is required.
More than 90% of people do not use kana input, but use romaji input.

Condition 2: The list must have the following contents.
・ "ぱん", "ＰＡＳＳ" (double-byte alphabet)
・This occurs when the consonant alphabet and the first alphabet of the full-width alphabet are the same.

Normally, in the case of Romaji input, when you click "P", it is not confirmed, and when you click "あ(a)", "ぱ" is displayed.
If you enter it in the hands-on table, it will be confirmed when you enter "P" and "p あ" will be displayed.
By the way, in Romaji input, if you enter "a" alone, it becomes "あ".

I will share another point of information.
Asian languages use 2 bytes to represent characters.
There are half-width and full-width concepts in the alphabet.
For example, half-width "A", full-width "Ａ"
This phenomenon only occurs when double-byte alphabets are present in the list.

**Comment by aninde** [comment]
@ogura3106 thanks for the additional explanation, thanks to this I was able to reproduce the problem, although it still looks different to me.

It seems that character replacement doesn't work when the characters used as output to replace before conversion are in the item dropdown list. Demo showing the issue https://jsfiddle.net/aninde/rkxvw0L5/
Data list for the dropdown menu without any complex charts https://jsfiddle.net/aninde/3vgqkjfL/ work well with conversion.

Steps to reproduce
1. Download Japanese language, set only Romanji input on the additional IME toolbar.
<img width="239" alt="Screenshot 2022-11-28 at 14 59 15" src="https://user-images.githubusercontent.com/30186818/204296248-8685da3f-291d-40a0-bc0d-080973ec50e4.png">
<img width="227" alt="Screenshot 2022-11-28 at 15 00 23" src="https://user-images.githubusercontent.com/30186818/204296283-c945521e-8902-4501-9d08-ff500fc48b57.png">

3. Dropdown list needs to have string 'ぱん' 
4. Open editor on dropdown cell  https://jsfiddle.net/aninde/rkxvw0L5/ type `p + a`, click SPACE to convert it to `パ`

### Result 
I don't have access to convert to IME editor, cell remains with `ぱ` .
I am able to convert `ぱ` to `パ` only when during second typing when I repeat typing p + a p + a and then pressing space. It should work like this the first time you type it.
Pasting `パ` works.

#### Edge 107.0.1418.56 / Windows 10
<img width="163" alt="Screenshot 2022-11-28 at 15 24 05" src="https://user-images.githubusercontent.com/30186818/204302381-131b052d-b570-4801-90e2-56ec4d47fe7a.png">

#### Chrome 107.0.5304.110 (Official Build) (x86_64) / macOS 12.6.2 (21G312)
Same as above.
Pasting `パ` works.

https://user-images.githubusercontent.com/30186818/204305279-59866caf-c51d-449d-92f0-300dad789507.mov

**Comment by ogura3106** [comment]
Thank you for the reproduction test.
You are missing a list value in condition 2.
Please include the full-width alphabet "ＰＡＳＳ" in the list.
When you enter "P" in romaji input, "P" is fixed and becomes "pあ".

The first demo has full-width alphabet data and will be reproduced.
The second demo will not be reproduced because there is no full-width alphabet data.

https://user-images.githubusercontent.com/54391173/204410039-cbab8fd3-9c08-4817-bc6f-b0e5b9622e76.mp4

**Comment by AMBudnik** [comment]
Thank you both @aninde @ogura3106 I was able to get the same error, and it's true romanji `a` stays in the dropdown cell but works well in a simple editor.

![Kapture 2022-11-29 at 08 03 35](https://user-images.githubusercontent.com/10757813/204461295-03d6dd81-0801-4ddc-9597-ca5c56023abe.gif)
(simple editor once we type `p` and `a`)

dropdown cell type 
![Kapture 2022-11-29 at 07 56 13](https://user-images.githubusercontent.com/10757813/204460825-310da2f8-1304-4bf5-ae57-644c40eec473.gif)

Tested on macOS Ventura, Chrome 107.

Keyboard settings
<img width="735" alt="Zrzut ekranu 2022-11-29 o 08 01 59" src="https://user-images.githubusercontent.com/10757813/204461042-93f217fc-922f-4914-ab5c-52cd34208930.png">

**Comment by ogura3106** [comment]
Thank you for the reproduction.
By the way, it did not occur in version 6.2.2.

**Comment by aninde** [comment]
This issue will be fixed by the upcoming v12.3 https://jsfiddle.net/d16foLmh/.

**Comment by AMBudnik** [comment]
hi @ogura3106

Thank you for being so helpful with the replication of the issue. We just released Handsontable v12.3.0 were this issue is fixed.

**Comment by ogura3106** [comment]
Many thanks!
