### ISSUE TITLE
Value zero should override placeholder in numeric cell type.

### ISSUE THREAD

**Issue by barneyRA** [handsontable/handsontable#9680]
### Description

In a numeric cell type, if there is a placeholder, the value zero does not override the placeholder, which it should.

### Solution / Pull Request

1. Since zero is falsy (in the numeric render at least), we need an additional check for non-zero (see both printscreens)

### Your environment
* Handsontable version: 12.0.0
* Browser name and version: Every Browser
* Operating system: Every operting System
![Screenshot 2022-07-17 205206](https://user-images.githubusercontent.com/8241029/179420642-55b75b30-0db2-4c28-8648-87a139b4b396.png)
![Screenshot 2022-07-17 205104](https://user-images.githubusercontent.com/8241029/179420646-76a138cc-04e2-42c1-b8b7-b51b66fc0407.png)

**Comment by adrianszymanski89** [comment]
Hi @barneyRA 

Thank you for pointing that out. We might consider changing it at some point.

**Comment by warpech** [comment]
@barneyRA could you create a JSFiddle that presents the problem? You can start by editing the JSFiddle on this page: https://handsontable.com/docs/numeric-cell-type/

**Comment by barneyRA** [comment]
strangely enough, in this jsfiddle, it seems to work see fiddle https://jsfiddle.net/7c0uq35r/2. There seems to be a very specific edge-case where this doesn't work.

**Comment by warpech** [comment]
@barneyRA could you help us out to reproduce this edge-case? Otherwise we are not able to investigate this any further.

**Comment by AMBudnik** [comment]
Hi @barneyRA do we have any updates regarding the edge-case you've mentioned?

**Comment by barneyRA** [comment]
I'm still trying to replicate this issue reliably in a test-setting, I will get back in touch as soon as I'll be able to do that.

**Comment by AMBudnik** [comment]
Hey @barneyRA I need to close this report as there is no further feedback on how to replicate the issue.
If there's anything that can help us to replicate the case please share in the comment.
