### ISSUE TITLE
Can not set row type, can't find the setting row type.

### ISSUE THREAD

**Issue by zgpnuaa** [handsontable/handsontable#9692]
### Description

I want to set the first row as a dropdown cell  type, but I can't find the setting row type, only the setting column type

### Steps to reproduce

1.when i set 
 rows: [
    {},
    { type: 'numeric' },
    {
      type: 'dropdown',
      source: ['yellow', 'red', 'orange', 'green', 'blue', 'gray', 'black', 'white']
    },
    {
      type: 'dropdown',
      source: ['yellow', 'red', 'orange', 'green', 'blue', 'gray', 'black', 'white']
    }
  ],
it's error.
2.
3.

### Demo

https://jsfiddle.net/6Lc0jye4/

### Your environment
* Handsontable version:  12.1.2
* Browser name and version: Chrome 101
* Operating system: Windows 10

**Comment by adrianszymanski89** [comment]
Hi @zgpnuaa 

The `rows` option doesn't exist in Handsontable. The correct way to set the dropdown cell type is to do it in the `columns` option. However, there is a kind of a workaround if you want to set the specific row to a dropdown cell type. You can use `cells` option , here's an example:

https://jsfiddle.net/aszymanski/8m260dba/1/

**Comment by zgpnuaa** [comment]
> Hi @zgpnuaa
> 
> The `rows` option doesn't exist in Handsontable. The correct way to set the dropdown cell type is to do it in the `columns` option. However, there is a kind of a workaround if you want to set the specific row to a dropdown cell type. You can use `cells` option , here's an example:
> 
> https://jsfiddle.net/aszymanski/8m260dba/1/

Thank you. It's really great.
And I found another method as follows:
cells(row, col, prop) {
    if (row === 0) {
      this.type = 'dropdown';
      this.source = ['Ni', 'Fe', 'Cr', 'Co', 'C', 'W', 'Mo', 'Al', 'Ti', 'Nb', 'Ta', 'B', 'Zr', 'Si', 'Mn', 'P', 'Pb', 'Sb', 'As', 'Sn', 'Bi', 'V', 'Ce', 'Hf'];
    }
    if(row === 1){ this.type='numeric'}
  },

**Demo**
https://jsfiddle.net/ybu29goq/
