### ISSUE TITLE
TypeError: out is null

### ISSUE THREAD

**Issue by thisissami** [handsontable/handsontable#971]
Hello,

For some odd reason, a fairly simple use case of Handsontable that worked totally fine for me yesterday is not working for me today at all, despite having 0 changes in the code. My table never loaded, and the firefox webconsole kept giving me a "TypeError: out is null" message from line 355 in the 0.9.12 release of Handsontable. 

I ended up changing this segment of code:

        for (var i = 0, ilen = sliced.length; i < ilen; i++) {
          out = out[sliced[i]];
          if (typeof out === 'undefined') {
            return null;
          }
        }

to read like this:

        for (var i = 0, ilen = sliced.length; i < ilen; i++) {
          out = out[sliced[i]];
          if (typeof out === 'undefined' || out == null) {
            return null;
          }
        }

which fixed the problem. Figured I'd share this in case this proves problematic for anybody else.

Best,
Sami

**Comment by AMBudnik** [comment]
Issue closed in lack of demo provided my issue author.

**Comment by XeroOne** [comment]
Thanks. This helped me. I got the same error when binding a row from my database to a HOT. Nothing wrong with the record other than being 25 columns wide. I'm using v.18 of HOT

**Comment by thisissami** [comment]
Oh whoops, just seeing this now - years later. Sorry for never creating a jsFiddle! I'm no longer familiar with this code, so not going to create that now. 

@XeroOne I'm glad this was of use for you. 😸
