### ISSUE TITLE
Add hook "beforeBeginEditing" to the cells

### ISSUE THREAD

**Issue by andraz-podobnik** [handsontable/handsontable#9713]
Hook “afterBeginEditing” already exists. It would be nice to have “beforeBeginEditing” hook too.

- With this one, I’d be able to prevent editing just before user starts editing
- E.g. when returning false from the function, it would not show the editor to the user

**Comment by AMBudnik** [comment]
Thank you for sharing the proposition. I think that we can connect this issue to https://github.com/handsontable/handsontable/discussions/7734.

**Comment by andraz-podobnik** [comment]
Hi Alexandra, not sure.
It's a different hook.

**Comment by AMBudnik** [comment]
Yes, I wanted to connect hook ideas for the cell editor.

**Comment by andraz-podobnik** [comment]
That's of course fine.
Please update #7734 and close this one then.

**Comment by AMBudnik** [comment]
Hi @andraz-podobnik 

I have good news, within this PR https://github.com/handsontable/handsontable/pull/10699 we added the requested hook.

Here you can read more about the changes for the new version https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-2-0
