### ISSUE TITLE
Filters Plugin - add function to set/add all conditions at once (on the initial load) 

### ISSUE THREAD

**Issue by andraz-podobnik** [handsontable/handsontable#9714]
As title says, Filters Plugin should get a function to set/add all conditions at once (on the initial load) – it would be similar to what's already available for sorting - MultiColumnSorting.setSortConfig().

**Comment by AMBudnik** [comment]
Hey @andraz-podobnik 

I already reported an idea for an initial filter here https://github.com/handsontable/handsontable/discussions/7706 so if you'd like to add something please add your comment to https://github.com/handsontable/handsontable/discussions/7706 and I will close this ticket.
