### ISSUE TITLE
Docs: React-docs: some links from the main site return 404

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9725]
### Description

After building locally new documentation version some links are not working and return 404.

Case 1
On the page http://localhost:8080/docs/next/react-data-grid/ and http://localhost:8080/docs/next/javascript-data-grid/ there is broken URL for demo http://localhost:8080/docs/next/demo/ 

Case 2
from http://localhost:8080/docs/next/react-data-grid/ and http://localhost:8080/docs/next/javascript-data-grid/#guides-for-your-framework
http://localhost:8080/docs/next/release-notes/ - 404

### Links

http://localhost:8080/docs/next/demo/

### Version
9e633a176b1b2afc5341a382d1c9e986c8103e91

opened by:
```
npm run docs:api
npm run docs:build
npm run docs:start
```
and 

```
cd ..
npm i
cd docs
npm run docs:api
npm run docs:start:no-cache
```
on Safari 15.6 (17613.3.9.1.5) / macOS 12.5 (21G72)

**Comment by jansiegel** [comment]
> On the page http://localhost:8080/docs/next/react-data-grid/ and http://localhost:8080/docs/next/react-data-grid/ 

You pasted the same URL twice

The demo is available at the prefixed url -> http://localhost:8080/docs/next/react-data-grid/demo/.

I can't find it in the sidebar, though, I'm not sure if this is meant to be that way.

**Comment by aninde** [comment]
@jansiegel thank you for spotting that. I fixed it.

**Comment by warpech** [comment]
Closing as done
