### ISSUE TITLE
Docs: React-docs: Versions 9-12 return 404

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9726]
### Description

Older version of the documentation <8 works , newer not from both version of the docs:
http://localhost:8080/docs/next/react-data-grid/ and http://localhost:8080/docs/next/javascript-data-grid/

### Links

https://handsontable.com/docs/8.4.0/tutorial-introduction.html - ok
http://localhost:8080/docs/9.0/ - 404
http://localhost:8080/docs/10.0/ - 404
http://localhost:8080/docs/11.0/ - 404
http://localhost:8080/docs/11.1/ - 404
http://localhost:8080/docs/12.0/ - 404
choosing 12.1 return http://localhost:8080/docs/react-data-grid/ - 404
next - http://localhost:8080/docs/next/react-data-grid/ - ok, works

### Version
9e633a176b1b2afc5341a382d1c9e986c8103e91

opened by:
```
npm run docs:api
npm run docs:build
npm run docs:start
```
and 

```
cd ..
npm i
cd docs
npm run docs:api
npm run docs:start:no-cache
```
on Safari 15.6 (17613.3.9.1.5) / macOS 12.5 (21G72)

**Comment by jansiegel** [comment]
I think that's fine, as the previous docs versions are stored on their separate branches. Same with choosing the current version - on production it should work alright.

@warpech, can you confirm?

**Comment by warpech** [comment]
Yes, this is by design since PR #9651. Thanks @aninde for noticing.
