### ISSUE TITLE
OnChange Event Issue

### ISSUE THREAD

**Issue by sriramselvaraj** [handsontable/handsontable#973]
Hi Team,

Firstly thanks for the wonderful tool.

I have a query regarding the handsontable.I have two dropdowns/autocomplete controls in a table onchange of any item in any of the dropdown i would like to populate the other same vice versa i want to do for the other.Can you please help  me on how to do that,I wasted almost 2 days to find it out but no improvement.

Thanks in Advance

Regards,
Sriram

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity. If you would have any unsolved questions please open a new issue.

**Comment by rkotte** [comment]
Is it just me or all the jsfiddle not working on this. All I get is the word TEST
http://jsfiddle.net/BRU3C/169/

**Comment by AMBudnik** [comment]
Hi @rkotte 
The onChange event was replaced by `afterChange` (relase note for [0.15.0](https://github.com/handsontable/handsontable/releases?after=0.15.1)). Are you using version below 0.15.0?
Here's an example of `beforeChange`/`afterChange` http://jsfiddle.net/gtemdsqq/
