### ISSUE TITLE
Docs: React-docs: Missing `HotColumn` in the left navigation bar

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9732]
### Description

Link in the left navigation for the is missing first word `<HotColumn>`, it's only `component`. Maybe it's caused by `<code>&lt;HotColumn/&gt;</code>`.
http://localhost:8080/docs/next/react-data-grid/
http://localhost:8080/docs/next/react-data-grid/next/hot-column/
<img width="746" alt="Screenshot 2022-08-02 at 14 59 59" src="https://user-images.githubusercontent.com/30186818/182384931-b45c9bee-809d-4754-b18d-9fd7dd6a1f05.png">

### Links

http://localhost:8080/docs/next/react-data-grid/
http://localhost:8080/docs/next/react-data-grid/next/hot-column/

### Version
9e633a176b1b2afc5341a382d1c9e986c8103e91

opened by:
```
npm run docs:api
npm run docs:build
npm run docs:start
```
and 

```
cd ..
npm i
cd docs
npm run docs:api
npm run docs:start:no-cache
```
on Safari 15.6 (17613.3.9.1.5) / macOS 12.5 (21G72)

**Comment by warpech** [comment]
Problem solved by changing the page title to "`HotColumn` component" (without the angle brackets) in PR #9690
