### ISSUE TITLE
[10.0+] setCellMeta doesn't change the cell type

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9734]
### Description

If we define the cell type as, for example, `password` and then we want to change the type to `text` by using `setCellMeta()` and back again to `password`, the change doesn't occur. This behavior applies to all available cell types.

This issue was present before and was solved in version 8: https://github.com/handsontable/handsontable/issues/4793

### Steps to reproduce

1. Open an example. The default cell type is set to `password`. Then, in order, we execute `setCellMeta()` to change the type to `text` and then back to `password`.

### Demo

1) v. 9 (correct behavior) - http://jsfiddle.net/aszymanski/0y1phudq/1/
2) v. 10 (and higher, incorrect behavior) - http://jsfiddle.net/aszymanski/0y1phudq/2/ 

### Your environment

* Browser name and version: Google Chrome 103
* Operating system: macOS Monterey 12.4

**Comment by AMBudnik** [comment]
It works when we use `editor` and `renderer` instead of `type`

```js
hot.setCellMeta(0, 0, 'type', 'text');
hot.render();

hot.setCellMeta(0, 0, 'editor', 'password');
hot.setCellMeta(0, 0, 'renderer', 'password');
hot.render();
```

**Comment by AMBudnik** [comment]
Thank you for fixing guys! I'm closing this issue as done.
