### ISSUE TITLE
Docs: React docs are deployed on the staging environment as JavaScript docs

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9735]
### Description

When I did a manual deployment of the `feature/react-docs` branch on the staging environment (run https://github.com/handsontable/handsontable/actions/runs/2785104153), the React pages (under https://dev.handsontable.com/docs/next/react-data-grid/installation/) present something that is half-way between React and JavaScript:

- the H1 addition says "JavaScript Data Grid" instead of "React Data Grid"
- the `only-for` containers in Markdown think that they are in JavaScript, not in React

<img width="2672" alt="Screen Shot 2022-08-02 at 11 07 14 PM" src="https://user-images.githubusercontent.com/566463/182473512-d761242e-311f-4301-b803-0ead4e123e98.png">

**Comment by krzysztofspilka** [comment]
@budnix please let's check if this issue is already solved by PR 9740

**Comment by budnix** [comment]
I've deployed the latest `feature/react-docs` branch, and everything seems to work fine.
