### ISSUE TITLE
React renderer is highly adaptive, row headers are misaligned and cannot be aligned

### ISSUE THREAD

**Issue by liang-lomo** [handsontable/handsontable#9748]
![image](https://user-images.githubusercontent.com/24806031/183027799-d272dbf5-99ec-4bea-a90b-28f7f82112c2.png)

As is shown in，after using the React renderer, table headers cannot be aligned and fixed columns are set to display inconsistently

**Comment by AMBudnik** [comment]
Hi @liang-lomo 

Did you check if adding `autoRowSize: true` to your Handsontable setup fixes the following misalignment?

**Comment by liang-lomo** [comment]
![image](https://user-images.githubusercontent.com/24806031/183030872-37a6fefb-a520-45ae-9081-c109f4483cac.png)
@AMBudnik Yes, I have added it, but it still doesn't work！

**Comment by AMBudnik** [comment]
Thank you for checking that out, @liang-lomo 

I only see a connected issue here https://github.com/handsontable/handsontable/issues/9276, but it does not seem to be the same case. Would you be able to share a demo where the issue can be replicable? I tried this configuration https://jsfiddle.net/s1xwrtpm/1/ but it does not cause the issue when `autoRowSize` is enabled.

**Comment by liang-lomo** [comment]
Thank you for your reply. You can try this link. 
https://codesandbox.io/s/handsontable-react-data-grid-hello-world-app-forked-5gucpi?file=/src/index.tsx

**Comment by AMBudnik** [comment]
Thank you for sharing the demo. After minimizing the demo I find out that this issue https://github.com/handsontable/handsontable/issues/9063 describes the same case. In your example we can see the result more clearly, but this is the same case

![Screenshot 2022-08-08 at 09 45 14](https://user-images.githubusercontent.com/10757813/183365880-d220702e-64b9-449b-8bae-0de96a9c343f.png)

**Comment by AMBudnik** [comment]
I will update you as soon as we fix https://github.com/handsontable/handsontable/issues/9063 so I am closing this issue as a duplicate.
