### ISSUE TITLE
[12.0.0+] `Clear` filter option used in `nestedHeaders` blocks dropdown menu from displaying

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9753]
### Description

When `Clear` filter option is used in `nestedHeaders` it blocks dropdown menu from displaying. The issue does not occur when we use `colHeaders` only. It also works well using Handsontable v11.1.0.

### Steps to reproduce

1. Use `clear` button in the `filter by value` list for any column
![Screenshot 2022-08-08 at 08 54 40](https://user-images.githubusercontent.com/10757813/183357273-4cb26bb7-0eb1-46cc-af6c-76ef07ef60ae.png)

3. Try to open a dropdown menu for any column.

**Result**
You are not able to open a dropdown menu for any of the columns. There are no console errors.

### Demo

https://jsfiddle.net/6pewsjxu/ - 11.1.0 (last working)
https://jsfiddle.net/6pewsjxu/1/ - 12.0.0. (first broken)

### Your environment
* Handsontable version: 12+
* Browser name and version: Chrome 103
* Operating system: macOS Monterey

Inform [Zen](https://handsontable.zendesk.com/agent/tickets/29892)

**Comment by warpech** [comment]
On the today's meeting we agreed to move it to 12.1.4

**Comment by aninde** [comment]
This issue will be fixed by v12.2 https://jsfiddle.net/aninde/25f86p3d/.

<img width="337" alt="Screenshot 2022-10-20 at 16 39 34" src="https://user-images.githubusercontent.com/30186818/196979831-58f2283e-cfa7-4399-b0df-4c3405cc18cf.png">

**Comment by AMBudnik** [comment]
Thank you. The client, who reported the issue, is updated with the release notes.

I'm closing this issue as solved in Handsontable v12.2.0
