### ISSUE TITLE
React docs: Some links in right-hand TOC don't work

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#9759]
Steps to reproduce:
1. Switch to the `feature/react-docs` branch.
2. From the `/docs` directory, run `npm run docs:start:no-cache`.
3. Open the local server URL.
4. Go to http://localhost:8000/docs/next/javascript-data-grid/cell-editor/.
5. From the right-hand TOC, select **Related API reference**. It works properly.
6. Switch to the React version of the docs.
7. From the right-hand TOC, select **Related API reference**. It doesn't work.

Most probably it's connected to how the conditional `only-for` containers work.

**Comment by jansiegel** [comment]
Resolved in #9783.
