### ISSUE TITLE
Docs: Search results for Guides and API reference are indistinguishable

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#9769]
### Description
When searching for a keyword, the search dropdown doesn't display any differences between Guides and API reference pages, which can be problematic at times:

<img width="252" alt="image" src="https://user-images.githubusercontent.com/7397134/184090931-be188721-61e2-4b1f-aaf6-9bf14c55a29d.png">

**Comment by AMBudnik** [comment]
@jansiegel I think that we can close this issue. We have a header for API Reference now

<img width="393" alt="Screenshot 2022-10-29 at 11 24 01" src="https://user-images.githubusercontent.com/10757813/198824080-77e10610-81e5-4b3c-bb7e-219c726501de.png">
