### ISSUE TITLE
0.9.12 - Ctrl V causes vertical scroll bar to move up

### ISSUE THREAD

**Issue by jackal-scratch** [handsontable/handsontable#977]
When there is a vertical scroll bar [that is not already at the top] and the body or a HOT grid has focus, hitting ctrl v (whether you're actually pasting anything or not) will cause the scroll bar to move up a little bit.

**Comment by krzysztofspilka** [comment]
@jackal-scratch can't reproduce this in v. 0.12.5, could confirm that it works?

**Comment by jackal-scratch** [comment]
Confirmed, bug is gone in latest version.

**Comment by AMBudnik** [comment]
@jackal-scratch thank's for your support.
