### ISSUE TITLE
The `getDataAtCol()` call for 125k rows of data causes the `Maximum call stack size exceeded` error.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9772]
### Case 1 - calling `getDataAtCol()`
1. Go to http://jsfiddle.net/exmoh5tw/
2. Open the console

**result**
You get the following error in the console and the data is not returned

```js
Uncaught RangeError: Maximum call stack size exceeded
    at Core.getDataAtCol (handsontable.full.js:85871:33)
    at ?editor_console=true:123:19
```

### Case 2 - using filters
1. Go to http://jsfiddle.net/exmoh5tw/1/
2. Open dropdown for any of the columns

**result**
You get the following error in the console and the data is not returned

```js
Uncaught RangeError: Maximum call stack size exceeded
    at Core.getDataAtCol (handsontable.full.js:85871:33)
    at ?editor_console=true:123:19
```

and the menu does not show (it shows if you set `height` then it is displayed below the table)

### Your environment
* Handsontable version: 12.1
* Browser name and version: Chrome 103
* Operating system: macOS Monterey

Inform [Zen](https://handsontable.zendesk.com/agent/tickets/29930)

**Comment by AMBudnik** [comment]
Checks done after fixing related issue https://github.com/handsontable/handsontable/issues/7840
Case 1 checked with 12.1.3 http://jsfiddle.net/zxhspjnr/ - issue still replicable
Case 2 checked with 12.1.3http://jsfiddle.net/2pgcvq49/1/ - issue still replicable

**Comment by aninde** [comment]
I made sure the 12.3.2 fix works with array of array and array of objects on supported browsers: Chrome 111.0.5563.64, Safari 16.3 (18614.4.6.1.6)*, Firefox 111.0, Edge 111.0.1661.41 on *macOS 13.2.1 (22D68) and Windows 10.
Demos
Case 1 http://jsfiddle.net/aninde/v0m91kua/
Case 2 array of objects http://jsfiddle.net/aninde/xc0omv53/
