### ISSUE TITLE
How to hide specific column programmatically ?

### ISSUE THREAD

**Issue by hoandang** [handsontable/handsontable#978]
Scenario: There is a checkbox at each column header, check the columns then click a button to hide the checked column.

Sounds like this eg: http://jsfiddle.net/hoandang/Lwguz/ then remove the data at the column option. But the thing is my table contains specific column name not just A, B, C and load data source from db, so the column header will be inconsistent if I remove one data at the columns option.

I came up with the method **alter** but got the error: 
    
    cannot remove column with object data source or columns option specified

**Comment by AMBudnik** [comment]
I had tried your demo @bgrohman and it worked as expected. Please try it with 0.14.1. If you would have any other issue related to this one - we'll reopen the issue.

**Comment by danieljin** [comment]
For anyone who is looking into this later, here is an updated forked jsfiddle https://jsfiddle.net/krf4wkks/
