### ISSUE TITLE
Docs: Errors on next/react-data-grid/installation/

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9788]
### Description

Page http://localhost:8080/docs/next/react-data-grid/installation/ logs errors in the browsers console.
![image](https://user-images.githubusercontent.com/30186818/185048889-77635a8a-b0e3-4bb7-9ec3-24e478571ca0.png)

### Links

Version: 16b88242ada7659c153c078a7fd5e83b16c786df
Mode: watch/dev (`npm run docs:start:no-cache`)

**Comment by warpech** [comment]
I cannot reproduce it on 16b8824 nor e39e20f3b3bb41f0d5e8e576616fe262cfcda24e (current `feature/react-docs`).

**Comment by aninde** [comment]
For me, reproduction was possible only during the first opening of the page on Chrome and Safari today in the morning. But right now, it seems to work. I made `npm i` on the main catalog `handsontable`, not in the `docs`.  That shouldn't affect it.

**Comment by aninde** [comment]
Cannot reproduce with slow 3G on staging (production server) and localhost with latest version 01759170cc15d889b331be2d22c6102fda11f915 with dev mode, so I'm closing #9788.
