### ISSUE TITLE
Docs: Add all frameworks to the dropdown in the top bar; fix the dropdown position

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9796]
In the React docs project, the framework dropdown currently only contains **JavaScript** and **React**.

Add 3 more options:

- **Angular** - should be a link to `/javascript-data-grid/angular-installation/`
- **Vue 2** - should be a link to `/javascript-data-grid/vue-installation/`
- **Vue 3** - should be a link to `/javascript-data-grid/vue3-installation/`

The design of the dropdown should be adjusted - **The left edge of the dropdown should begin where the current framework's icon is. Currently, it begins where the current framework's text is**

**Comment by aninde** [comment]
There are some issues that we need to adjust after that adjustment https://github.com/handsontable/handsontable/issues/9817
https://github.com/handsontable/handsontable/issues/9818

**Comment by warpech** [comment]
Yes, closing as done in #9441 (and its subtasks)
