### ISSUE TITLE
Docs: Remove the "Examples" page

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9797]
In the React docs epic branch, remove the "Examples" page that currently can be seen at the URLs:

- https://dev.handsontable.com/docs/next/javascript-data-grid/examples/
- https://dev.handsontable.com/docs/next/react-data-grid/examples/

The page should be removed, all links to it should be removed.

The "Examples" page should continue to work in the previously released versions, e.g. https://dev.handsontable.com/docs/12.0/examples/

Before this is ready for development:
- clarify where the removed URL https://handsontable.com/docs/examples/ should redirect to. I propose https://handsontable.com/docs/.

**Comment by kirszenbaum** [comment]
Done in #9805
