### ISSUE TITLE
Docs: edit Title and Description metadata for the pages

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9798]
The document https://docs.google.com/spreadsheets/d/1gmOkEQDvPQ5_3PKd_REmYn3Z4swh9OcAoCml_EcQVMk/edit#gid=0 contains improved Title and Description for all docs pages, in variants for JavaScript and React.

Update the `metaTitle` and `description` metadata in the docs content according to the document linked above using the new front matter developed in https://github.com/handsontable/handsontable/issues/9780.

This issue is NOT about updating page titles (`<h1>`, sidebar), only the meta titles (`<title>`).

Before this is ready for development:
- [x] @warpech should do the factual review
- [x] @warpech should check if it is possible to give custom meta titles to plugin pages in API reference
- [x] @krzysztofspilka should confirm API reference meta titles in [internal thread](https://handsoncode.slack.com/archives/C034WPQUG9W/p1661165254475329)
- [x] @kirszenbaum should do the linguistic review (especially for the cells with the orange background)

**Comment by kirszenbaum** [comment]
Done in #9820
