### ISSUE TITLE
Docs: suspendRender and suspendExecution methods have the same description

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9807]
### Description

In this section: https://handsontable.com/docs/batch-operations/#suspend-and-resume-methods both `suspendRender` and `suspendExecution` methods have the same description which is misleading.

The description from this PR https://github.com/handsontable/handsontable/pull/7406 might be a good base for fixing it.

**Comment by AMBudnik** [comment]
Duplicate of https://github.com/handsontable/handsontable/issues/9136
