### ISSUE TITLE
Docs: React-docs: Missing date on some API sites on staging environment

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9816]
### Description

Each site from documentation has div with the last update date. All sites describing API plugins have invalid date on staging environment. React and JS versions.

`<div class="last-updated">
<span class="prefix">Last Updated:</span> 
<span class="time">Invalid Date NaN, NaN</span></div>`

<img width="784" alt="Screenshot 2022-08-23 at 13 06 50" src="https://user-images.githubusercontent.com/30186818/186147153-80f602b5-52fc-46dc-8cc0-30d9f36150d2.png">

### Links

https://dev.handsontable.com/docs/next/javascript-data-grid/api/core
https://dev.handsontable.com/docs/next/javascript-data-grid/api/hooks
https://dev.dev.handsontable.com/docs/next/javascript-data-grid/api/options/#isemptyrow
https://dev.handsontable.com/docs/next/javascript-data-grid/api/auto-column-size/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/auto-row-size/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/autofill/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/bind-rows-with-headers/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/collapsible-columns/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/column-sorting/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/column-summary/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/comments/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/context-menu/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/copy-paste/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/custom-borders/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/drag-to-scroll/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/dropdown-menu/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/export-file/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/filters/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/formulas/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/hidden-columns/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/hidden-rows/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/manual-column-freeze/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/manual-column-move/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/manual-column-resize/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/manual-row-move/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/manual-row-resize/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/merge-cells/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/multi-column-sorting/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/nested-headers/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/nested-rows/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/persistent-state/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/search/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/trim-rows/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/undo-redo/
Private API Page
https://dev.handsontable.com/docs/next/javascript-data-grid/api/base-editor/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/base-plugin/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/cell-coords/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/cell-range/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/changes-observer/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/create-shortcut-manager/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/data-map/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/ghost-table/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/hiding-map/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/index-map/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/index-mapper/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/indexes-sequence/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/linked-physical-index-to-value-map/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/menu/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/physical-index-to-value-map/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/samples-generator/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/shortcut-context/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/shortcut-manager/
https://dev.handsontable.com/docs/next/javascript-data-grid/api/trimming-map/

React version
https://dev.handsontable.com/docs/next/react-data-grid/api/core
https://dev.handsontable.com/docs/next/react-data-grid/api/hooks
https://dev.handsontable.com/docs/next/react-data-grid/api/auto-column-size/
https://dev.handsontable.com/docs/next/react-data-grid/api/auto-row-size/
https://dev.handsontable.com/docs/next/react-data-grid/api/autofill/
https://dev.handsontable.com/docs/next/react-data-grid/api/bind-rows-with-headers/
https://dev.handsontable.com/docs/next/react-data-grid/api/collapsible-columns/
https://dev.handsontable.com/docs/next/react-data-grid/api/column-sorting/
https://dev.handsontable.com/docs/next/react-data-grid/api/column-summary/
https://dev.handsontable.com/docs/next/react-data-grid/api/comments/
https://dev.handsontable.com/docs/next/react-data-grid/api/context-menu/
https://dev.handsontable.com/docs/next/react-data-grid/api/copy-paste/
https://dev.handsontable.com/docs/next/react-data-grid/api/custom-borders/
https://dev.handsontable.com/docs/next/react-data-grid/api/drag-to-scroll/
https://dev.handsontable.com/docs/next/react-data-grid/api/dropdown-menu/
https://dev.handsontable.com/docs/next/react-data-grid/api/export-file/
https://dev.handsontable.com/docs/next/react-data-grid/api/filters/
https://dev.handsontable.com/docs/next/react-data-grid/api/formulas/
https://dev.handsontable.com/docs/next/react-data-grid/api/hidden-columns/
https://dev.handsontable.com/docs/next/react-data-grid/api/hidden-rows/
https://dev.handsontable.com/docs/next/react-data-grid/api/manual-column-freeze/
https://dev.handsontable.com/docs/next/react-data-grid/api/manual-column-move/
https://dev.handsontable.com/docs/next/react-data-grid/api/manual-column-resize/
https://dev.handsontable.com/docs/next/react-data-grid/api/manual-row-move/
https://dev.handsontable.com/docs/next/react-data-grid/api/manual-row-resize/
https://dev.handsontable.com/docs/next/react-data-grid/api/merge-cells/
https://dev.handsontable.com/docs/next/react-data-grid/api/multi-column-sorting/
https://dev.handsontable.com/docs/next/react-data-grid/api/nested-headers/
https://dev.handsontable.com/docs/next/react-data-grid/api/nested-rows/
https://dev.handsontable.com/docs/next/react-data-grid/api/persistent-state/
https://dev.handsontable.com/docs/next/react-data-grid/api/search/
https://dev.handsontable.com/docs/next/react-data-grid/api/trim-rows/
https://dev.handsontable.com/docs/next/react-data-grid/api/undo-redo/
Private API Page
https://dev.handsontable.com/docs/next/react-data-grid/api/base-editor/
https://dev.handsontable.com/docs/next/react-data-grid/api/base-plugin/
https://dev.handsontable.com/docs/next/react-data-grid/api/cell-coords/
https://dev.handsontable.com/docs/next/react-data-grid/api/cell-range/
https://dev.handsontable.com/docs/next/react-data-grid/api/changes-observer/
https://dev.handsontable.com/docs/next/react-data-grid/api/create-shortcut-manager/
https://dev.handsontable.com/docs/next/react-data-grid/api/data-map/
https://dev.handsontable.com/docs/next/react-data-grid/api/ghost-table/
https://dev.handsontable.com/docs/next/react-data-grid/api/hiding-map/
https://dev.handsontable.com/docs/next/react-data-grid/api/index-map/
https://dev.handsontable.com/docs/next/react-data-grid/api/index-mapper/
https://dev.handsontable.com/docs/next/react-data-grid/api/indexes-sequence/
https://dev.handsontable.com/docs/next/react-data-grid/api/linked-physical-index-to-value-map/
https://dev.handsontable.com/docs/next/react-data-grid/api/menu/
https://dev.handsontable.com/docs/next/react-data-grid/api/physical-index-to-value-map/
https://dev.handsontable.com/docs/next/react-data-grid/api/samples-generator/
https://dev.handsontable.com/docs/next/react-data-grid/api/shortcut-context/
https://dev.handsontable.com/docs/next/react-data-grid/api/shortcut-manager/
https://dev.handsontable.com/docs/next/react-data-grid/api/trimming-map/

#### Version:
fb593617c4ba469b7eed94b2eb2be2a1df3ab0f2 staging

**Comment by warpech** [comment]
Closing as done
