### ISSUE TITLE
Docs: React-docs: Incorrect links to Guides and API from navigation for Angular and Vue 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9817]
### Description

At the current staging of ae6c52cece0a3f4b9f865db3ea33c977f43b28bd
redirects for API and Guides don't work on staging when I changed the framework other than React. 

Reproduction
1. Selecting framework from dropdown list eg. Angular
2. Clicking on Guides or API Reference in the right navbar

<img width="944" alt="Screenshot 2022-08-23 at 14 49 01" src="https://user-images.githubusercontent.com/30186818/186162068-3aec46b7-0dd3-4607-9709-0713ef731ae0.png">

### Links

From main page and each related to those wrapper
 https://dev.handsontable.com/docs/next/javascript-data-grid/angular-installation/
https://dev.handsontable.com/docs/next/javascript-data-grid/vue-installation/
https://dev.handsontable.com/docs/next/javascript-data-grid/vue-simple-example/
https://dev.handsontable.com/docs/next/javascript-data-grid/vue3-custom-id-class-style/
https://dev.handsontable.com/docs/next/javascript-data-grid/vue3-installation/ 
https://dev.handsontable.com/docs/next/javascript-data-grid/vue3-hot-column/
https://dev.handsontable.com/docs/next/javascript-data-grid/angular-custom-context-menu-example/
Below pages return 404 
Clicking on Guides  in the navbar   
for Angular https://dev.handsontable.com/docs/next/angular-data-grid/
for Vue3 https://dev.handsontable.com/docs/next/vue3-data-grid/
for Vue https://dev.handsontable.com/docs/next/vue-data-grid/

Clicking on API Reference in the navbar 
for Angular https://dev.handsontable.com/docs/next/angular-data-grid/api/ 
for Vue3 https://dev.handsontable.com/docs/next/vue-data-grid/api/
for Vue3 https://dev.handsontable.com/docs/next/vue3-data-grid/
for Vue https://dev.handsontable.com/docs/next/vue3-data-grid/api/

**Comment by budnix** [comment]
I think that it's correct behavior. The [PR](https://github.com/handsontable/handsontable/pull/9777) introduced a redirect rule that automatically redirects all non-frameworked URLs to the prefixed ones (by default `javascript-data-grid`). Angular, Vue, and Vue3 don't follow the same rule as React Docs. They don't have a separate URL prefix.

**Comment by warpech** [comment]
@aninde According to the project spec, such URLs are incorrect. Are any of these 404s reproducible by clicking on the navigation?

**Comment by aninde** [comment]
@warpech all of them are reproducible by clicking on the navigation.

**Comment by warpech** [comment]
@aninde thanks for updating the instructions, it shows that there is a problem indeed.

**Comment by warpech** [comment]
Closing as done
