### ISSUE TITLE
Get all data with raw formulas

### ISSUE THREAD

**Issue by caktoy** [handsontable/handsontable#9822]
### Description
I want to get all data from the grid contains formulas, but when I use getData() it returns the final data. I only need to get the data but with the raw formulas, how I can do it? I use hansontable as vue component.

### Steps to reproduce
1. Install handsontable vue component with hyperformula option
2. Load data from source
3. Add formula to grid
4. Call getData() from hansontable instance, get the data but not with formulas

### Your environment
* Handsontable version: 12.0.1
* Browser name and version: Google Chrome
* Operating system: Windows 11

**Comment by AMBudnik** [comment]
Hi @caktoy 

The [`getSourceData()` method](https://handsontable.com/docs/api/core/#getsourcedata) returns altered data along with formulas instead of formula results. Vue demo: https://jsfiddle.net/0bknxur3/1/

Would that meet your project requirements?

**Comment by caktoy** [comment]
Hi @AMBudnik 

Perfect, that's what I looking for, but one more thing, can I also get the cell properties such as the readonly properties for the cells?

**Comment by caktoy** [comment]
Sorry, I get what I need to do, I just read the documentation, I can do it by using getCellsMeta().

I'll close this issue, thank you so much @AMBudnik.
