### ISSUE TITLE
Docs: Pages with horizontal scroll on mobile devices

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9831]
### Description

Below documentation pages have horizontal scroll on smaller screens like mobile devices, with resolution <=414.
 [Most popular mobile](https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide) resolutions are less than 414 viewport width. 
Tested on Chrome 104 / Samsung Galaxy A5 / Android 12.

A possible solution may be adding into the style

```
.table
  width: 100%
  display: block
  overflow-x: auto
```
and
```
td
  white-space: nowrap
```

### Links

**Due to the demos sticking out:**
https://handsontable.com/docs/column-hiding/ 
https://handsontable.com/docs/autocomplete-cell-type/ - demo

**Due to the table or list in the content:**

https://handsontable.com/docs/installation/
https://handsontable.com/docs/events-and-hooks/

https://handsontable.com/docs/selection/
https://handsontable.com/docs/merge-cells/
https://handsontable.com/docs/disabled-cells/

https://handsontable.com/docs/cell-renderer/
https://handsontable.com/docs/cell-editor/
https://handsontable.com/docs/cell-validator/
https://handsontable.com/docs/cell-type/
https://handsontable.com/docs/checkbox-cell-type/

https://handsontable.com/docs/context-menu/
https://handsontable.com/docs/undo-redo/
https://handsontable.com/docs/keyboard-shortcuts/
https://handsontable.com/docs/searching-values/

https://handsontable.com/docs/layout-direction/
https://handsontable.com/docs/modules/
https://handsontable.com/docs/custom-builds/
https://handsontable.com/docs/testing/
https://handsontable.com/docs/bundle-size/
https://handsontable.com/docs/third-party-licenses/
https://handsontable.com/docs/documentation-license/
https://handsontable.com/docs/release-notes/

https://handsontable.com/docs/api/core/
https://handsontable.com/docs/api/hooks/
https://handsontable.com/docs/api/options/

https://handsontable.com/docs/api/auto-column-size/
https://handsontable.com/docs/api/auto-row-size/
https://handsontable.com/docs/api/collapsible-columns/
https://handsontable.com/docs/api/column-summary/
https://handsontable.com/docs/api/comments/
https://handsontable.com/docs/api/copy-paste/
https://handsontable.com/docs/api/copy-paste/
https://handsontable.com/docs/api/drag-to-scroll/
https://handsontable.com/docs/api/dropdown-menu/
https://handsontable.com/docs/api/export-file/
https://handsontable.com/docs/api/filters/
https://handsontable.com/docs/api/hidden-columns/
https://handsontable.com/docs/api/hidden-rows/

https://handsontable.com/docs/api/base-editor/
https://handsontable.com/docs/api/data-map/
https://handsontable.com/docs/api/ghost-table/
https://handsontable.com/docs/api/index-mapper/
https://handsontable.com/docs/api/linked-physical-index-to-value-map/
https://handsontable.com/docs/api/menu/
https://handsontable.com/docs/api/menu/
https://handsontable.com/docs/api/shortcut-context/
https://handsontable.com/docs/api/shortcut-manager/

**Comment by aninde** [comment]
@krzysztofspilka what are your expectations of these sites?

**Comment by warpech** [comment]
Closing as done
