### ISSUE TITLE
Manual column resize does not resize to the handle position

### ISSUE THREAD

**Issue by johnhumbrecht** [handsontable/handsontable#984]
Thanks for fixing case 949.  While testing the new version I notice that when you grab and move a manual resize handle the column does not resize to the requested width.  It is more pronounced when you maximize the table.  

See http://jsfiddle.net/8cyp4/1/

**Comment by luxiaolu** [comment]
+1 for reopening

**Comment by Bounz** [comment]
I have also faced with this problem.

**Comment by twisk** [comment]
+1

**Comment by alvarotrigo** [comment]
+1

**Comment by budnix** [comment]
Connected with https://github.com/handsontable/handsontable/issues/3166
