### ISSUE TITLE
Enabling `nestedRows` prevents the `updateData()`'s dataset replacement

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9844]
### Description

Enabling `nestedRows` prevents the `updateData()`'s dataset replacement. The nested object dataset and non-nested dataset behave differently, so I document two cases scenarios.

#### *Non-nested data*
1. Go to http://jsfiddle.net/5a61smpw/3/
2. Check the preview (*correct*)
<img width="122" alt="Screenshot 2022-08-30 at 10 11 31" src="https://user-images.githubusercontent.com/10757813/187384754-7d3747c9-b247-4fe7-82c4-eb5f54691f92.png">
3. Comment out the `loadData()` call from line `8` and remove comment from line `9`
4. Check the preview (*wrong*) (unaltered dataset)
<img width="111" alt="Screenshot 2022-08-30 at 10 12 32" src="https://user-images.githubusercontent.com/10757813/187384978-e7b2368e-105a-4011-bf0e-be1b1abab48b.png">

**Result**
The number of columns is correct, but data is not replaced.

#### *Nested data*
1. Go to https://jsfiddle.net/ve06rdk4/
6. Check the preview (*correct*)
![Screenshot 2022-08-30 at 10 08 12](https://user-images.githubusercontent.com/10757813/187384111-d7392d12-313f-4ff9-88c4-83021b141088.png)
7. Comment out the `loadData()` call from line `172` and remove comment from line `173`
8. Check the preview (*wrong*) (unaltered dataset)
![Screenshot 2022-08-30 at 10 09 49](https://user-images.githubusercontent.com/10757813/187384431-34c58c79-3963-4f61-86e6-04cb6ac5780e.png)

**Result**
The number of columns is incorrect, data is not replaced.

### Your environment
* Handsontable version: 12.1.2
* Browser name and version: Chrome 104
* Operating system: macOS Monterey

Inform [forum](https://forum.handsontable.com/t/cant-change-data-once-nestedrows-true/6361/8)

**Comment by adrianszymanski89** [comment]
Inform [Forum](https://forum.handsontable.com/t/nestedrow-updating-settings-will-not-updating-content/6390)

**Comment by adrianszymanski89** [comment]
Inform ZD 30853.

**Comment by adrianszymanski89** [comment]
Inform ZD 31225.

**Comment by AMBudnik** [comment]
This issue is fixed in Handsontable v12.3.1.
Here is the full list of changes in this version https://handsontable.com/docs/javascript-data-grid/release-notes/#_12-3-1

**Comment by aaronbeall** [comment]
Thank you for this fix, it's a big deal to us!
