### ISSUE TITLE
Docs: React-docs: Issues with dark mode inside Redux & Vuex examples

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9856]
### Description

The demo on Redux page has the wrong style inside on the seperate PR https://github.com/handsontable/handsontable/pull/9787. Some elements inherint wrong style when dark mode is on.
```
 html.theme-dark table:not(.selected-preview *):not(.pika-table):not(.htCore) td, html.theme-dark table:not(.selected-preview *):not(.pika-table):not(.htCore) th {
    border-bottom: 1px solid #20232a;
```
<img width="324" alt="Screenshot 2022-09-01 at 14 39 26" src="https://user-images.githubusercontent.com/30186818/187916056-5cbfd357-52b3-4f25-960c-0ba592a9d409.png">
<img width="395" alt="Screenshot 2022-09-01 at 14 39 36" src="https://user-images.githubusercontent.com/30186818/187916063-6282a575-49a8-416a-b29d-883fd0b47134.png">

Searchbar looks well, so it's not related to https://github.com/handsontable/handsontable/issues/9781

### Links

Set dark mode and then open https://dev.handsontable.com/docs/next/react-data-grid/redux/#overview
or open page, set dark mode, refresh page

https://dev.handsontable.com/docs/next/javascript-data-grid/vue3-vuex-example/#example-vuex-store-dump
https://dev.handsontable.com/docs/next/javascript-data-grid/vue-vuex-example/

### Environment
Browser: Safari 15.6 (17613.3.9.1.5), Chrome 105.0.5195.52 
OS: macOS 12.5 (21G72)

**Version**
Only on https://github.com/handsontable/handsontable/pull/9787 
not on https://github.com/handsontable/handsontable/tree/feature/react-docs
staging a9586d94025ba754c387425196170bb5f7089a2e

**Comment by warpech** [comment]
Also seen in the current `feature/react-docs` branch at 140fb0cab5d616152c428b042c9f5364fd3a125c. We think it is a new problem that did not exist a few days ago.

**Comment by warpech** [comment]
This problem only exists when starting on the page https://dev.handsontable.com/docs/next/react-data-grid/redux/ directly. When you start on another page, and then navigate to the Redux page, it looks OK.

My guess is that this problem started to appear after we made the "Preview" tab open by default (PR #9440)

**Comment by warpech** [comment]
Closing as done
