### ISSUE TITLE
Double click manualColulmnResizer will extend column with to fixed value, is this by design?

### ISSUE THREAD

**Issue by xinfli** [handsontable/handsontable#986]
When double click on manualColumnResizer, width of column column size will be extended to a fixed value; if current width is greater than the value, the column width will be shrink to the fixed value.

I'm confused by the behavior, is this by design?

**Comment by LeTranAnhVu** [comment]
@psmolenski, I cannot find the function `determineColumnWidth` in v.6.2.2. Did we change the name?

**Comment by AMBudnik** [comment]
Hi @LeTranAnhVu, that code has already been replaced. Can you share your use case with me at support@handsontable.com?

**Comment by LeTranAnhVu** [comment]
@AMBudnik , Thanks for responding me. I found my solution already.

**Comment by AMBudnik** [comment]
I'm glad to hear that. Thank you for the update @LeTranAnhVu
