### ISSUE TITLE
 Problems with the use of fixed columns and merge cells

### ISSUE THREAD

**Issue by JavaPupil** [handsontable/handsontable#9866]
### Description

I need a cell with 2 rows and 10 columns for the title content,
and I need to fix the first two columns, but the end result is a little weird.

### Steps to reproduce

1.  Configure the merge cell
       mergeCells: [{ row: 0, col: 0, rowspan: 2, colspan: 10 }]
2. Set to fix the first two columns
      fixedRowsTop: 0,
      fixedColumnsStart: 2,
3.  Full Configure 
![image](https://user-images.githubusercontent.com/38714256/188322247-a8220aba-45c6-4348-a206-52671d007f5a.png)

### Demo
![image](https://user-images.githubusercontent.com/38714256/188322177-ca8b0c9f-3f78-47e2-a9ef-8021e708ade8.png)

### Your environment
* Vue wrapper version:  2.6.14
* Handsontable version:  12.1.2
* Browser name and version: chrome  102.0.5005.63(64)
* Operating system: Window 10

**Comment by AMBudnik** [comment]
Hi @JavaPupil 

Could you check if enabling the `autoRowSize` fixes the misalignments between the fixed area and the rest of the table? Here https://handsontable.com/docs/api/options/#autorowsize you can read more about this option.

**Comment by JavaPupil** [comment]
![image](https://user-images.githubusercontent.com/38714256/188484651-7aafaef8-4ce2-4da0-a73f-63fdde75bf92.png)
**You are right, But with this configuration I have two titles, and I want only one.Like the picture below.**

![image](https://user-images.githubusercontent.com/38714256/188486043-b937c3a0-7053-4d23-a87d-2f44308776ef.png)

**Comment by AMBudnik** [comment]
That is not currently possible to have only the non-fixed value shown. The fixed cell is a clone so even if you use the `:first-child` of the `TR` and `TD` you'll still be styling all the merged area https://jsfiddle.net/1o9k7bqd/1/

I am not a CSS Pro so there might be something I am missing. But generally, we do not have an option to remove the content from the second part of the fixed cell.

**Comment by AMBudnik** [comment]
... or, we can try this https://jsfiddle.net/aszymanski/vmhtdn1o/1/ (@adrianszymanski89 thanks for the demo)
@JavaPupil would that help?

**Comment by JavaPupil** [comment]
emmm...  This is really an extraordinary solution.
The title of the first line may be left.
I'm not very good at CSS either, it's just that my scene might run into it.

**Comment by AMBudnik** [comment]
That's true, @JavaPupil it should be treated more like a workaround than a solution
