### ISSUE TITLE
Click event handling incorrectly from dialog box

### ISSUE THREAD

**Issue by brian-villanueva** [handsontable/handsontable#987]
I'm using a Kendo UI Window [http://demos.kendoui.com/web/window/index.html] to create a dialog box above my handsontable. What seems to be happening is that clicks that occur above the table cells (i.e. inside the Kendo Window) are being processed by handsontable. When this happens, it can't figure out which cell is being clicked on... because obviously there is no cell since this is a layer 'above' the table.

The fix is simple. In jquery.handsontable.full.js around line 2901 beneath the comment "//X-HANDSONTABLE is the tag name in Web Components version of HOT. Removal of this breaks cell selection", this "if" statement needs to be changed from:
  if (next === null)
to:
  if ((next === null) || (next === undefined))

**Comment by AMBudnik** [comment]
Hi, do you still face the same issue after updating to [0.13.1](If you still have the same issue, please write us back, until it happen issue will be closed.)?

**Comment by AMBudnik** [comment]
If you would face similar issue with newest version, please give us a feedback.
