### ISSUE TITLE
How to install it on Angular 8.2.0

### ISSUE THREAD

**Issue by zhuangYuFeiHelloGit** [handsontable/handsontable#9874]
`npm install handsontable @handsontable/angular` will takes an error
![image](https://user-images.githubusercontent.com/17961466/188833233-9d60537a-6f5a-47d6-9f6e-403ebce5692f.png)

**Comment by adrianszymanski89** [comment]
Hi @zhuangYuFeiHelloGit 

Can you tell me what your environment looks like? I mean, OS, NodeJS and npm versions?

**Comment by zhuangYuFeiHelloGit** [comment]
> Hi @zhuangYuFeiHelloGit
> 
> Can you tell me what your environment looks like? I mean, OS, NodeJS and npm versions?

Thanks for your reply @adrianszymanski89 
OS: Windows 11
NodeJS: v16.16.0
npm: 8.3.0

My project uses Angular 8.0.2 and the handsontable/angular I installed uses Angular 12.1.2.  How can I install a handsontable/angular which uses Angular 8.0.2?

**Comment by AMBudnik** [comment]
Hi.

We need to close this issue report as we officially dropped support for Angular 13 and lower in Handsontable v13. Reference: https://handsontable.com/docs/javascript-data-grid/release-notes/#_13-0-0

I hope that you already made an update to a newer version.
