### ISSUE TITLE
Docs: React docs: Improve "Saving data" example to work locally

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9876]
### Description

There are a few problems that prevent running certain examples locally:

1. The example on the page https://dev.handsontable.com/docs/next/react-data-grid/saving-data/ should be fixed to include:
   - missing `import { createRef } from 'react'`, which is used on line `const hotRef = createRef();`
      - verify if other examples don't have this problem
   - an undefined variable `autosave`
2. ~Add CSS import to all React docs examples.~ moved to #9877 

Thanks @maciejbo-handsontable for finding these problems.

### Links

https://dev.handsontable.com/docs/next/react-data-grid/saving-data/

**Comment by aninde** [comment]
This example can't work locally due to CORS politics https://handsoncode.slack.com/archives/C034WPQUG9W/p1664190170427579?thread_ts=1664189800.275489&cid=C034WPQUG9W
