### ISSUE TITLE
Publish prerelease packagages to NPM automatically

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9879]
Currently, we don't have a simple way to publish pre-release NPM packages for internal and external testing before releasing the final version.

The proposed solution to solve that is to implement an automatic NPM package creation that goes straight to the public† NPM registry.

Requirements:

- the package should be automatically created after any commit to the `develop` or `release/*` branch (to make it easier to test a snapshot of what might be released)
- a developer should be able to manually generate a package from a `feature/*` branch (or any other branch) through manual workflow dispatch in GitHub Actions on the page https://github.com/handsontable/handsontable/actions/workflows/publish.yml (to make it easier to test work in progress)
- both employees and customers should be able to use this package (that's why we put it on the public registry)
- use a proper SemVer suffix in the package version number, that is not misleading
   - we decided to go with the version number `0.0.0-next-<shortSha>-<buildDate>` in an [internal discussion](https://handsoncode.slack.com/archives/C4PV4S33Q/p1662644133553129) (e.g. `0.0.0-next-2b3b4b-20221009`)
     - The release branch (`release/X`) is an exception. On that branch, the version number should contain the version set while creating the branch. For example, for `release/12.2.5` the pre-released version would look like `12.2.5-next-2b3b4b-20221009`
- should entail the packages for core, Angular, React, Vue 2, and Vue 3 (a prerelease wrapper package should depend on a corresponding prerelease core package) 
   - https://www.npmjs.com/package/handsontable
   - https://www.npmjs.com/package/@handsontable/angular
   - https://www.npmjs.com/package/@handsontable/react
   - https://www.npmjs.com/package/@handsontable/vue
   - https://www.npmjs.com/package/@handsontable/vue3
- should be picked up by a CDN, so the following URLs should be picked up: `https://cdn.jsdelivr.net/npm/handsontable@0.0.0-next-<shortSha>-<buildDate>/dist/handsontable.full.min.js`, `https://cdn.jsdelivr.net/npm/@handsontable/react@0.0.0-next-<shortSha>-<buildDate>/dist/react-handsontable.min.js`
    - make sure that the "latest" version (`https://purge.jsdelivr.net/npm/handsontable@latest/dist/handsontable.css`) is still resolved by JSDelivr as the last stable version, not the pre-release
- during the work, make VERY sure that we accidentally don't publish a non-prerelease to NPM, because these are hard to pull out
    - until this change is fully approved, we will publish using temporary package names: `tmphot`, `tmphot-angular`, etc...

Deliverables:

- [x] 1. a new NodeJS script that publishes Handsontable Core and the wrappers (Angular, React, Vue 2, Vue 3) to NPM as the version number `0.0.0-next-<shortSha>-<buildDate>`
- [x] 2. a new command in `package.json` in the repo root, used to run the script from point 1
- [x] 3. a new GitHub Actions workflow `Publish` (`publish.yml`) that executes the command from point 2 only on manual dispatch
- [x] 4. the GitHub Actions `test.yml` workflow is changed to dispatch `publish.yml` if (and only if) all the tests have passed and the branch name is `develop` or `release/**`
- [ ] 5. the pre-release process is documented internally at:
https://kb.handsontable.com/display/BOOK/Release+checklist
    - @warpech or @budnix will do that
- [ ] 6. the pre-release process is documented externally at: 
    - https://handsontable.com/docs/versioning-policy/ (mention that pre-releases exist, explain the suffix, add a link to the "Testing" page that gives more details)
    - https://handsontable.com/docs/testing/ (give details about how to find and use pre-releases)
    - @warpech or @budnix will do that
- [ ] 7. all the Requirements listed above are verified

The solution might entail parts of the current release scripts (explained on https://kb.handsontable.com/display/BOOK/Release+checklist, also see the discussion in #9891):
- `npm run freeze` - probably some parts that update the version number and date are useful
- `npm run release` - probably not useful
- `npm run publish-all` - probably fully useful

-----

† - It is not a problem that our "Versions" page in https://www.npmjs.com/package/handsontable will become polluted with prereleases. If it ever starts to be a problem, we can hide the prereleases by marking them with [npm deprecate](https://docs.npmjs.com/cli/v8/commands/npm-deprecate). Then they will not be listed by default on the "Versions" page unless you click "Show deprecated versions": See this version of another library for example: https://www.npmjs.com/package/rxjs/v/6.0.0-smoosh.1

**Comment by aninde** [comment]
Works like a charm https://www.npmjs.com/package/handsontable?activeTab=versions.

**Comment by AMBudnik** [comment]
Closed as done in Handsontable v12.3.0.
