### ISSUE TITLE
Docs: Improve docs meta-tags

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9882]
### Description

We want to add some new meta tags in the documentation for a better-searching experience. 

Proposed list:

- Searching values (search values)
- Column freezing (fixedColumns)
- Formula calculation (hyperformula)
- Batch operations	(batching, performance)
- Row freezing (fixedRows)

Consulted with @AMBudnik

**Comment by AMBudnik** [comment]
Closed as done.
