### ISSUE TITLE
Error nestedRows in columns data callback

### ISSUE THREAD

**Issue by rivas274** [handsontable/handsontable#9883]
### Description

When using nestedRows the callbacks of the data columns stop working.

### Steps to reproduce

-Change value of colums unidades, ancho, largo, alto
-rowData Is undefined

### Demo
https://jsfiddle.net/L4te1mvy/1/

### Your environment
* Handsontable version: 12.1
* Browser name and version: Chrome 105.0.5195.102 (Build oficial) (64 bits)
* Operating system: Windows 11(64 bits)

**Comment by AMBudnik** [comment]
Hi @rivas274 

Referring to column data as a function is not fully supported. Could you share your requirements with me at support@handsontable? I will check if there's another way to accomplish the goal.
