### ISSUE TITLE
[12.0] Cannot read properties of undefined (reading '__children')

### ISSUE THREAD

**Issue by footman9988** [handsontable/handsontable#9885]
### Description

24/5000 
hi
Update the data, such as adding a property to the data object . then insert row above or insert row below 
### Steps to reproduce

1. hot.updateSettings(data: newData )
2.  insert row above or insert row below 

### Demo

https://jsfiddle.net/footman8899/t68o7f5a/21/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by adrianszymanski89** [comment]
Hi @footman9988 

Thank you for reporting this issue. I have investigated it and, unfortunately, it's a regression that occurs in version 12.1. If possible, for time being, I suggest downgrading to version 12.0, where everything works fine. I hope this issue will be solved soon.

**Comment by footman9988** [comment]
17/5000 
Thank you very much
Ok, I'll lower the version to 11.1 and try again
