### ISSUE TITLE
Docs: Make sure that all JS, Angular, Vue 2, Vue 3 code examples can run locally

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9888]
### Description

Make sure that all code examples (examples with "Preview") for JS, Angular, Vue 2, Vue 3 can be easily run locally (by copy and paste to a typical development environment).

Blocked by #9887

**Comment by budnix** [comment]
Done within https://github.com/handsontable/handsontable/pull/10044

**Comment by budnix** [comment]
Deployed to the production within https://github.com/handsontable/handsontable/commit/810048932d6d8af2437aa8739fbe882517d51f25
