### ISSUE TITLE
Could not get the selected data in hotInstance

### ISSUE THREAD

**Issue by footman9988** [handsontable/handsontable#9899]
### Description

I can use getSelected() in the hook  but  Could not get the selected data in methods
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/footman8899/6nc0qajx/3/
### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by AMBudnik** [comment]
Hi @footman9988 

When you click a button, we automatically deselect cells. To keep the selection you need to add the `outsideClickDeselects: false` to your settings. Updated demo: https://jsfiddle.net/zxe0fngt/1/

**Comment by footman9988** [comment]
@AMBudnik  Thank you very much
