### ISSUE TITLE
Docs: React docs: Cosmetic changes to the framework dropdown & the example container

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9908]
### Description

Make the following cosmetic changes:

1. The choices in the framework dropdown should be in the following order: JavaScript, React, Angular, Vue 2, Vue 3
2. The "Preview" tab should be displayed as the first one in the example container, because it is surprising that the default tab is not the first tab

**Comment by AMBudnik** [comment]
@warpech can we close this?

**Comment by warpech** [comment]
Yes, closing as done in https://github.com/handsontable/handsontable/pull/9441
