### ISSUE TITLE
script error when pasting outside cells

### ISSUE THREAD

**Issue by JuanjoArmellino** [handsontable/handsontable#9918]
### Description

I am getting a script error when pasting outside the cells themselves. just noticed it by accident, why would i paste outside a cell, but well.. script error

this didnt happen with handsontable 7, now that im migrating to newer versions i notice this

thanks in advance
Juanjo

### Steps to reproduce

1. open any handsontable (latest version ) table ie. https://jsfiddle.net/handsoncode/8x3bv51a
2. click on C1 cell. then click outside, to the right of the C1 cell.
3. Paste with control-V

### Demo

https://jsfiddle.net/handsoncode/8x3bv51a

### Your environment
* Handsontable version: 12.1.2
* Browser name and version: firefox 104
* Operating system: windows 10 21h2

**Comment by adrianszymanski89** [comment]
Hi @JuanjoArmellino 

Thank you for reporting this issue. Of course, in earlier versions, it shouldn't work like that, but also, it shouldn't throw an error. I'll mark it as a bug.

**Comment by AMBudnik** [comment]
Hi @JuanjoArmellino 

Could you please update to v14.4.0 and verify if the issue is stil replicable? I was testing it and it seems solved now.
