### ISSUE TITLE
Missing `translateRowsToColumns` method

### ISSUE THREAD

**Issue by zumm** [handsontable/handsontable#9919]
What's happened to `translateRowsToColumns`? It's declared in `data.d.ts`, but not implemented in `data.js`.

**Comment by adrianszymanski89** [comment]
Hi @zumm 

It's our internal method, and it's not recommended for our end users to use it, as it might be changed or deleted without any warning.

**Comment by adrianszymanski89** [comment]
Hi @zumm 

I just want to inform you that we decided to remove that obsolete type from our codebase. It will be changed with the next release.

**Comment by aninde** [comment]
Since v12.2 `translateRowsToColumns` will not be mentioned in the code.

**Comment by AMBudnik** [comment]
Hi @zumm 

I just wanted to let you know that we just released Handsontable v12.2.0 where this unused method is removed.

Here you can read more about the changes that we did in this version https://handsontable.com/docs/react-data-grid/release-notes/#_12-2
