### ISSUE TITLE
`afterChange` doesn't fire if binded to component directly

### ISSUE THREAD

**Issue by zumm** [handsontable/handsontable#9920]
### Description
If you bind `afterChange` to component `HotTable` directly (like that `@after-change="handler"` it doesn't fire, but you do it with `settings` property (like that `:settings="{ afterChange: handler }"`) it does.

### Steps to reproduce
See demo.

### Demo

https://jsfiddle.net/u8rvfaz9/3/

### Your environment
* Vue 3 wrapper version: 12.1.2
* Handsontable version: 12.1.2
* Browser name and version: Opera 90.0.4480.54
* Operating system: Windows 10

**Comment by AMBudnik** [comment]
Hi @zumm 

https://jsfiddle.net/t1x0z58f/1/

One small change the `:` instead of `@` in the hook declaration in the component's props.

**Comment by zumm** [comment]
Oh, it's prop, not event. I see.

But tbh this approach (passing functions as props) is weird for vue.

**Comment by AMBudnik** [comment]
I see what you mean, @zumm. [Here's an example](https://michaelnthiessen.com/pass-function-as-prop/) of what is often used as what should be. Currently, however, it's standardized for all of our wrappers.
