### ISSUE TITLE
Comment cannot be displayed

### ISSUE THREAD

**Issue by footman9988** [handsontable/handsontable#9921]
### Description

The last column cannot display the screen when the table is full.But it makes the box bigger
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/footman8899/qn1ajL7o/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by footman9988** [comment]
Not the same!
Please look at my demo, pay attention to the column "E", the Cell "Ford".
There are comments, but they are displayed on the right, and the box is enlarged

**Comment by adrianszymanski89** [comment]
Yes, I know it's not entirely the same, but I mentioned it as it can be related. The problem here is that the comments are not jumping to the other side of the cell when the viewport isn't wide enough. I'll mark it as a bug, then.

**Comment by AMBudnik** [comment]
Hi @footman9988 

This issue is no longer replicable if we update to v12.x. Can you confirm if it also works for you when you update?

**Comment by AMBudnik** [comment]
I think that we can call the issue fixed as it covers the same case as my issue that was solved.

If there's anything we're missing here, @footman9988 please let me know.
