### ISSUE TITLE
How to detect last selected cell

### ISSUE THREAD

**Issue by loftykhanna** [handsontable/handsontable#9929]
### Description
After moving from  cell A1 to B3, how to detect previous selected cell was A1?

I tried it using getSelectedLast inside afterSelection and afterSelectionEnd but only getting value of current selected cell. 
Jsfiddle Link : [https://jsfiddle.net/loftykhanna/g6caysjp/1/](https://jsfiddle.net/loftykhanna/g6caysjp/1/)

 `
  afterSelection: function (...args) {
    console.log('afterSelection', args)
    console.log('afterSelection', this.getSelectedLast(), this.getSelected())
  },

  afterSelectionEnd: function (...args) {
    console.log('afterSelectionEnd', args)
    console.log('afterSelectionEnd', this.getSelectedLast(), this.getSelected())
  },
 `
Is there any way to detect previously selected cell?

**Comment by AMBudnik** [comment]
Hey @loftykhanna 

>Is there any way to detect previously selected cell?

The `afterSelection()` and `afterSelectionEnd()` hook run after a given action but they only hold the details about the latest action that occurs. Did you try to keep the result of `afterSelectionEnd()` in a separate variable? What do you plan to do with that previous cell information?

**Comment by loftykhanna** [comment]
Hello @AMBudnik, 
Thank you for quick reply.
I need to fire some events when user selects different row, Thats is reason I need previous selected cell. 

I have gone with similar approach - have kept value in separate variable  in afterSelectionEnd(). I was not sure if this is the right way to do it or is there any inbuilt functionality for the same.

**Comment by AMBudnik** [comment]
In this case the additional variable is the only way. We only stack details regarding filters, sorting and undoUndo. Other operations are returning only the current event information.
