### ISSUE TITLE
[12.1.0] DropDown menu doesn't show again after filtering with nestedHeaders

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9930]
### Description

If we select the `is empty` condition from the dropdown filtering menu, and then we try to re-open the dropdown menu, it won't show up. It's occurring only with `nestedHeaders`.

### Steps to reproduce

1. Set the filtering condition to `is empty` from the dropdown menu.
2. Try to re-open the dropdown menu.

### Demo

v. 12.1.0 (not working) - https://jsfiddle.net/k4bx1asv/4/
v. 12.0.0 (working) -  https://jsfiddle.net/aszymanski/Ltdock85/

### Your environment
* Handsontable version: 12.1.0
* Browser name and version: Google Chrome 105
* Operating system: macOS Monterer 12.4

**Comment by adrianszymanski89** [comment]
Inform [Forum](https://forum.handsontable.com/t/nestedheaders-not-working-after-filtering/6437)

**Comment by AMBudnik** [comment]
Seems to be related to https://github.com/handsontable/handsontable/issues/9753

**Comment by AMBudnik** [comment]
Update: Related issue just got fixed in v12.2.0 https://github.com/handsontable/handsontable/issues/9753

**Comment by AMBudnik** [comment]
I'm closing this issue as solved in v14.0 https://jsfiddle.net/jsa3Lgpf/1/
