### ISSUE TITLE
Docs: Header on the React demo which with dark theme covers the buttons due to wrong inherits

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9939]
### Description

1. Open https://handsontable.com/docs/react-hot-column/#using-the-renderer-editor-components-within-react-s-context, select dark mode of documentation, 
2. Click Preview button to see rendered demo

That header inherits from #preview-tab-example5 
```
html.theme-dark .tabs-component .tabs-component-panels section[id*=preview-] {
    color: #2f3133;
    background-color: #fff;
```

Result: 
<img width="631" alt="Screenshot 2022-09-21 at 15 54 45" src="https://user-images.githubusercontent.com/30186818/191523585-6ac65a37-7344-47dd-b026-e5d7b56856ef.png">

<img width="680" alt="Screenshot 2022-09-21 at 15 47 57" src="https://user-images.githubusercontent.com/30186818/191522236-dc3dde7c-9265-4054-87cd-f19e80ed98b7.png">

### Links

Environment:
macOS 12.5 (21G72) / Chrome 12.5 (21G72), Firefox 104 & 105

**Comment by krzysztofspilka** [comment]
I'm closing this issue because it's no longer a problem at https://dev.handsontable.com/docs/react-data-grid/cell-renderer/#using-the-renderer-component-within-react-s-context
