### ISSUE TITLE
`npm run publish-all` command exits with an error

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9941]
### Description

When the Handsontable is released, one of the scripts in the process exists with an error even thou the results are completed successfully.

![Zrzut ekranu 2022-09-22 o 10 04 34](https://user-images.githubusercontent.com/571316/191716321-75c529d9-95ef-4449-b2fb-f4e022a824c0.png)

As the error says, the `publish-package` does not exist on the `examples` project. But in fact, the `examples` project should not be called within that script. It should be ignored for that release flow.

**Comment by AMBudnik** [comment]
Closed as done in Handsontable v12.2.0
