### ISSUE TITLE
Docs: React-docs: Button for editing demos sticks out on iOS 15 & 16 and iPad 15 devices

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9945]
### Description

The button `<button type="submit">Edit in JSFiddle</button>`  goes beyond the available area on  current LTS iOS 15.6.1, 16.0.2 and 15.1 iPadOS devices on Chrome and Safari. It can be reproduced with the [BrowserStack](https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fjsfiddle.net%2Fdugvyc1p%2F&speed=1). It occurs regardless of the screen orientation, in portrait and landscape mode. On the earlier version of iOS 14, the problem does not occur

iOS 15.6.1
![307300019_1043237629738296_4440174601871345762_n](https://user-images.githubusercontent.com/30186818/191925161-4ae2c499-f0cc-49bf-89f5-cc0245daac54.jpg)
![308183837_1533515043754935_6089688322203206308_n](https://user-images.githubusercontent.com/30186818/191925177-354c1929-0615-4cdc-9935-9c4cc0680662.jpg)

iOS 14
<img width="394" alt="Screenshot 2022-09-23 at 10 53 43" src="https://user-images.githubusercontent.com/30186818/191925874-7ea65074-8b47-4dcf-ae32-6405569bfb49.png">

### Links

https://dev.handsontable.com/docs/next/react-data-grid/installation/#basic-example

### Version:
Staging 22.09.22 f27acb3c5a29e1788d038ceb6b2e4a098c680aa1

**Comment by warpech** [comment]
This should be addressed by #9933

**Comment by krzysztofspilka** [comment]
Solution: the button should be rendered within the example container inside of ` <li role="presentation" class="tabs-component-tab js-fiddle-tab”><li>`.

**Comment by krzysztofspilka** [comment]
Will be, sort of, fixed in https://github.com/handsontable/handsontable/pull/10003

"Sort of" because the form with the button is still in the wrong container. Todo for the future.
