### ISSUE TITLE
Docs: Manual resizing demo doesn't work locally

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9948]
### Description

After pasting code of demo https://dev.handsontable.com/docs/react-data-grid/grid-size/#manual-resizing compiles with 

IDE logs:
```
  Line 20:31:  Assignments to the 'triggerBtnClickCallback' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect  react-hooks/exhaustive-deps

ERROR in [eslint]
src/App.js
  Line 21:11:  'triggerBtn' is not defined     no-undef
  Line 22:9:   'exampleParent' is not defined  no-undef
  Line 24:9:   'triggerBtn' is not defined     no-undef
  Line 26:9:   'exampleParent' is not defined  no-undef
  Line 28:9:   'triggerBtn' is not defined     no-undef
```

As a result, expanding button doesn't work in the browser. It works in the documentation and in the fsdiddle. 

https://user-images.githubusercontent.com/30186818/192266664-a197fafc-c1df-4cc4-9760-2e640ec2dfbb.mov

### Links

https://dev.handsontable.com/docs/react-data-grid/grid-size/#manual-resizing

### Version
Staging 07496ab487aa11fef0c9b6b922090002c644de4d

**Comment by warpech** [comment]
This is a similar problem that was fixed in https://github.com/handsontable/handsontable/pull/9897 - `triggerBtn` and `exampleParent` are implicit JS globals created through `id` in HTML. React doesn't see these globals, because they are not available in JS strict mode.

**Comment by aninde** [comment]
I close #9948 as fixed.
