### ISSUE TITLE
Docs: Malformed header on the Demo page

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9950]
### Description

On the demo page, a header is rendered in a malformed way including the `##` characters

<img width="1369" alt="Screen Shot 2022-09-26 at 4 16 16 PM" src="https://user-images.githubusercontent.com/566463/192299738-85c6118d-8933-46ee-87a3-5e9051de0ba6.png">

I will fix this in a PR

### Links

https://dev.handsontable.com/docs/react-data-grid/demo/

**Comment by aninde** [comment]
It's fixed.
<img width="521" alt="Screenshot 2022-09-29 at 08 41 43" src="https://user-images.githubusercontent.com/30186818/192958050-2295915e-4457-4a1a-8212-16beb2da02e1.png">

**Comment by AMBudnik** [comment]
@aninde can we close it?

**Comment by warpech** [comment]
Yes, closing as done in https://github.com/handsontable/handsontable/pull/9441
