### ISSUE TITLE
Docs: Demo import { createSpreadsheetData } from './helpers' doesn't work

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9954]
### Description

During testing https://github.com/handsontable/handsontable/issues/9877 I found that demos with 
import { createSpreadsheetData } from './helpers' don't work locally. Demos are compiling with 
```
ERROR in ./src/App.js 10:0-50
Module not found: Error: Can't resolve './helpers' in '/Users/ndemytruk/quality/env/react-create/my-app/src'
```
Maybe it should be changed to 
```
import Handsontable from 'handsontable';

data={Handsontable.helper.createSpreadsheetData(200, 20)}
```
because it works, example: https://dev.handsontable.com/docs/react-data-grid/column-moving/#enabling-plugin

### Links

https://dev.handsontable.com/docs/react-data-grid/context-menu/#context-menu-with-custom-options
https://dev.handsontable.com/docs/react-data-grid/events-and-hooks/#external-control
https://dev.handsontable.com/docs/react-data-grid/instance-methods/
https://dev.handsontable.com/docs/react-data-grid/redux/#example
https://dev.handsontable.com/docs/react-data-grid/language/#demo - the second demo

**Comment by kirszenbaum** [comment]
```
import Handsontable from 'handsontable';

...

data={Handsontable.helper.createSpreadsheetData(200, 20)}
```

Seems to work both in the docs and locally.
