### ISSUE TITLE
Pasting rows freezes browser

### ISSUE THREAD

**Issue by begovic92** [handsontable/handsontable#996]
When pasting large number of new rows into table (100 or so) the browser becomes unresponsive i.e freezes.

**Comment by AMBudnik** [comment]
Please update to 0.14.0 - now it's a split of second to copy columns A and B to C and D (2k cells).

Tried on:
* Chrome 41.0.2272.104 (64-bit)
* Firefox 36.0.4

**Comment by Sheetal1289** [comment]
Hi @AMBudnik 

I am facing the same issue. when i copy and paste the data from excel or from one handsontable to another, it will freeze my browser. It is very slow. even i am copying small data like count is 35 and above then also it is taking time.  
I am using Handsontable pro Version: 1.16.0.

**Comment by AMBudnik** [comment]
Hi @Sheetal1289 
Can you share the demo you use and describe the Excel file (amount of data)?

**Comment by rohan750** [comment]
I’m evaluating the Handsontable on my project and I hit a problem. There is around 20 columns and over 500 rows in the grid and I found that the copy and paste function is very slow (around 2 min 15 sec) . Is it any way to enhance the speed?

**Comment by AMBudnik** [comment]
Hi @rohan750 can you share your instance settings with me at support@handsontable.com
I'll check what settings are in correlation with the lag on pasting.

**Comment by rohan750** [comment]
`let hotTableSettings = () => {
  // update license key here when available
  return {
    width: 1100,
    height: 1100,
    colHeaders: true,
    rowHeaders: true,
    stretchH: 'all',
    undo: true,
    search: true,
    licenseKey: 'non-commercial-and-evaluation',
    filters: true,
    dropdownMenu: [
                    'filter_by_condition',
                    'filter_operators',
                    'filter_by_condition2',
                    'filter_by_value',
                    'filter_action_bar'
    ],
    minSpareRows: 20,
    contextMenu: {
      'items': {
      }
    },
    copyPaste: { columnsLimit: 5000, rowsLimit: 5000, pasteMode: 'overwrite' },
    afterCut: (changes, coords) => {
      const hotInstance = props.hotTableComponent.current.hotInstance;
      let rowIndices = _.pluck(coords, 'startRow');

      //get hold of deleted rows here
      //or at the end to know which rows are deleted
      rowIndices.forEach(function (rowIndex, index) {
        hotInstance.alter('remove_row', rowIndex+1, 1);
      });
    }
  }
}`
