### ISSUE TITLE
Failing e2e tests on Chrome, but pass in the IDE console

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9960]
### Description

Some e2e don't pass on the latest Chrome, but they pass in the IDE console. Details in the [team discussion](https://handsoncode.slack.com/archives/C4PV4S33Q/p1664359782373789?thread_ts=1664293713.074289&cid=C4PV4S33Q).

[Comments](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments) > [Styling](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling) > [using configuration object: {"htmlDir":"ltr","layoutDirection":"inherit"}](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22ltr%22%2C%22layoutDirection%22%3A%22inherit%22%7D%60) > [should display the comment editor on the left of the cell when on the right there is no left space](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22ltr%22%2C%22layoutDirection%22%3A%22inherit%22%7D%60%20should%20display%20the%20comment%20editor%20on%20the%20left%20of%20the%20cell%20when%20on%20the%20right%20there%20is%20no%20left%20space)
Expected 2531 to be close to 2599, 0.
Error: Expected 2531 to be close to 2599, 0. at at _callee4$ (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:122643:42) at tryCatch (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27092:17) at Generator._invoke (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27072:24)
[Comments](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments) > [Styling](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling) > [using configuration object: {"htmlDir":"rtl","layoutDirection":"ltr"}](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22rtl%22%2C%22layoutDirection%22%3A%22ltr%22%7D%60) > [should display the comment editor on the left of the cell when on the right there is no left space](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22rtl%22%2C%22layoutDirection%22%3A%22ltr%22%7D%60%20should%20display%20the%20comment%20editor%20on%20the%20left%20of%20the%20cell%20when%20on%20the%20right%20there%20is%20no%20left%20space)
Expected 2531 to be close to 2599, 0.
Error: Expected 2531 to be close to 2599, 0. at at _callee4$ (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:122643:42) at tryCatch (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27092:17) at Generator._invoke (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27072:24)
[Comments (RTL mode)](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)) > [using configuration object: {"htmlDir":"rtl","layoutDirection":"inherit"}](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22rtl%22%2C%22layoutDirection%22%3A%22inherit%22%7D%60) > [Styling](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22rtl%22%2C%22layoutDirection%22%3A%22inherit%22%7D%60%20Styling) > [should display the comment editor on the right of the cell when on the left there is no left space](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22rtl%22%2C%22layoutDirection%22%3A%22inherit%22%7D%60%20Styling%20should%20display%20the%20comment%20editor%20on%20the%20right%20of%20the%20cell%20when%20on%20the%20left%20there%20is%20no%20left%20space)
Expected 2531 to be close to 2599, 0.
Error: Expected 2531 to be close to 2599, 0. at at _callee3$ (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:124128:42) at tryCatch (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27092:17) at Generator._invoke (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27072:24)
[Comments (RTL mode)](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)) > [using configuration object: {"htmlDir":"ltr","layoutDirection":"rtl"}](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22ltr%22%2C%22layoutDirection%22%3A%22rtl%22%7D%60) > [Styling](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22ltr%22%2C%22layoutDirection%22%3A%22rtl%22%7D%60%20Styling) > [should display the comment editor on the right of the cell when on the left there is no left space](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22ltr%22%2C%22layoutDirection%22%3A%22rtl%22%7D%60%20Styling%20should%20display%20the%20comment%20editor%20on%20the%20right%20of%20the%20cell%20when%20on%20the%20left%20there%20is%20no%20left%20space)
Expected 2546 to be close to 2614, 0.
Error: Expected 2546 to be close to 2614, 0. at at _callee3$ (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:124128:42) at tryCatch (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27092:17) at Generator._invoke (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27072:24)

Extracted from the https://github.com/handsontable/dev-handsontable/issues/326.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 12.1.3
* Browser name and version: Chrome 105.0.5195.125 (Official Build) (x86_64)
* Operating system: macOS and Windows 10

**Comment by aninde** [comment]
All tests are passing on Chrome with v12.3. Tested on v  108.0.5359.98 (Official Build) (x86_64), 109.0.5414.36 (Official Build) beta (x86_64) and 107.

**Comment by AMBudnik** [comment]
Closed as done in Handsontable v12.3.0.
