### ISSUE TITLE
Docs staging: The table of contents doesn't work properly

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#9963]
### Description

The "Table of contents" on the staging environment seems to be having some issues. I couldn't reproduce these issues with the currently deployed production docs, which is 12.1.3 as of Sep 28 7e815c0f9b8d20d70d8113e8bb2b6fb8a334445c.

## 1. The active items are not properly updated when the user scrolls up or down the page

The `active` item in the table of contents is not highlighted in the 🔆 light theme, so please switch to the 🌙 dark theme before testing the issue reported below.

Tested at https://dev.handsontable.com/docs/next/react-data-grid/binding-to-data/

- **Test:** Open the [binding to data](https://dev.handsontable.com/docs/next/react-data-grid/binding-to-data/) page and click on the "Function data source and schema" in the table of contents. Then use the mouse scroll, or a scrollbar, to scroll to the top of the page.
- **Result:** the active item is not updated in the table of contents.  The `.active` class is not removed, and the URL is not updated either.
- **Solution:** I would **remove** the mechanism that automatically adds anchors (#something) to the URL from our documentation. It should work like [here in the MS docs](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements#global-namespace) - in our case, the position of the box would be fixed, but the items **wouldn't** be highlighted.
 
   In my solution, when a user clicks on any item in the table of contents, a) it leads to the anchor, b) it adds an anchor to the URL, c) the active element of the table of contents doesn't get any special CSS.

## 2. The non-unique headlines can't be reached with the table of contents

- **Test:** Open https://dev.handsontable.com/docs/next/react-data-grid/column-groups/#example and click on the second item labeled "Example" in the table of contents. 
- **Result:** You will be taken to the first "Example" section, not the second.

**Comment by krzysztofspilka** [comment]
Todo

> I would remove the mechanism that automatically adds anchors (#something) to the URL from our documentation. It should work like [here in the MS docs](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements#global-namespace) - in our case, the position of the box would be fixed, but the items wouldn't be highlighted.

**Comment by Serrrek89** [comment]
Done
