### ISSUE TITLE
Docs: Vue demos crashes after switching between guides with demos of other wrappers by using the navbar

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9987]
### Description

This happens with switching links using the left navbar. The reloading page fixes it.

### Reproduction:
1. Open https://handsontable.com/docs/javascript-data-grid/
2. Change the page to Angular guide by expanding `Integrate with Angular` and clicking the second guide `Basic example in Angular` https://handsontable.com/docs/javascript-data-grid/angular-basic-example/
3. Change the page to Vue 3 guide in the same way, by using the left navbar
4. Change the page to the Vue 2 Guide `Basic example in Vue 2`

This can also be seen when switching from angular to Vue 2 and Vue 3.

### Result
The demo does not render, the console throws an error
![image](https://user-images.githubusercontent.com/30186818/193298326-69de40b6-b525-41e9-8c14-83e331bced56.png)

**Error**
```
zone.min.js:1 Unhandled Promise rejection: _vue.default is not a constructor ; Zone: <root> ; Task: Promise.then ; Value: TypeError: _vue.default is not a constructor
    at <anonymous>:15:1
    at e.invoke (zone.min.js:1:7154)
    at t.run (zone.min.js:1:2353)
    at zone.min.js:1:14394
    at e.invokeTask (zone.min.js:1:7838)
    at t.runTask (zone.min.js:1:3016)
    at g (zone.min.js:1:10129) TypeError: _vue.default is not a constructor
    at <anonymous>:15:1
    at e.invoke (https://cdn.jsdelivr.net/npm/zone.js@0.9/dist/zone.min.js:1:7154)
    at t.run (https://cdn.jsdelivr.net/npm/zone.js@0.9/dist/zone.min.js:1:2353)
    at https://cdn.jsdelivr.net/npm/zone.js@0.9/dist/zone.min.js:1:14394
    at e.invokeTask (https://cdn.jsdelivr.net/npm/zone.js@0.9/dist/zone.min.js:1:7838)
    at t.runTask (https://cdn.jsdelivr.net/npm/zone.js@0.9/dist/zone.min.js:1:3016)
    at g (https://cdn.jsdelivr.net/npm/zone.js@0.9/dist/zone.min.js:1:10129)
```

### Links

https://handsontable.com/docs/javascript-data-grid/vue-basic-example/

**Comment by krzysztofspilka** [comment]
I noticed that when I navigate from Vue 3 to Vue 2, I get errors.

- Open the console in the dev tools
- Open basic demo for Vue 2: https://handsontable.com/docs/javascript-data-grid/vue-basic-example/ (no error)
- Then open Vue 3: https://handsontable.com/docs/javascript-data-grid/vue3-basic-example/ (no error)
- Then get back to Vue 2: Open https://handsontable.com/docs/javascript-data-grid/vue-basic-example/ (**error**!)

Result
```
VM111:15 Uncaught (in promise) TypeError: _vue.default is not a constructor
    at <anonymous>:15:1
```
