### ISSUE TITLE
Docs: Search engine improvement 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9992]
### Description

The order of search results needs to be readjustment.
Now, the words from the internal header within guides are placed higher than the one in the title of the guide

### Example 1
User types `header`
**Results in React, JS** 997a22053995c518f57115736631cd77fec826b9
 v12.1: Guides about column groups, no guides about plain headers

![image](https://user-images.githubusercontent.com/30186818/193576404-c6378a46-8c27-47ce-afa1-f5efc77f954e.png)

**Old documentation, v12.0**
Column header as the 2nd result, row header as the 3th
![image](https://user-images.githubusercontent.com/30186818/193576811-e42fb4d1-866f-4097-a250-75cc9e7df6c9.png)

### Example 2 
User types `row`
**Results in React, JS** 997a22053995c518f57115736631cd77fec826b9
5 guides where in the internal header within the guide, there is word `row`.

![image](https://user-images.githubusercontent.com/30186818/193577487-9bc952a1-6344-48db-91c2-51d6229f9bc0.png)

**Old documentation, v12.0**
5 guides with `row` the tittle
![image](https://user-images.githubusercontent.com/30186818/193577879-9375401a-287e-4dc1-9cd3-6ae036c197e4.png)

### Example 3
User types `modules`
**Results in JS** 997a22053995c518f57115736631cd77fec826b9
Only about modules in the Angular, because there are all guide headers alphabetically

![Screenshot 2022-10-03 at 14 43 01](https://user-images.githubusercontent.com/30186818/193579427-86216a74-3ad3-4619-9b90-97331ad05ca9.png)

**Results in React**
Correct one; due to that only React-related guides
![Screenshot 2022-10-03 at 14 42 11](https://user-images.githubusercontent.com/30186818/193579961-b64c8f79-1b3b-45a7-b7dc-e45489587d1e.png)

**Old documentation, v12.0**
Guides about modules in each of the wrappers
![Screenshot 2022-10-03 at 14 40 43](https://user-images.githubusercontent.com/30186818/193579054-e6e0b572-99ca-48fb-bbb7-2ad2bc0b5341.png)

**Comment by krzysztofspilka** [comment]
Agree, it doesn't work right. Try to find formulas or keyboard shortcuts...
<img width="398" alt="Screenshot 2022-10-07 at 12 06 25" src="https://user-images.githubusercontent.com/8048526/194599681-657b6753-0a8b-4fc2-bc30-f9d694adc230.png">
<img width="367" alt="Screenshot 2022-10-07 at 12 05 38" src="https://user-images.githubusercontent.com/8048526/194599703-0574d7f6-e62b-4077-b858-07d0984eaae0.png">
